### ISSUE TITLE
Support building with different channels w/ different branding

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#10]
You can find icon resources here:
https://github.com/brave/muon/tree/master/app/resources

Anthony started things here, and apparently it works for macOS.
https://github.com/brave/brave-browser/tree/multi-channel
https://github.com/brave/brave-core/tree/multi-channel

So still remaining is Linux and Windows.

You can see where we have different profile directories for each OS here:
https://github.com/brave/brave-core/pull/46
https://github.com/brave/brave-core/pull/59
This doc might be helpful:
https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md

We want to support 4 channels:
release, beta, developer, and canary

#### For official build
* ~/Library/Application Support/BraveSoftware/Brave-Browser-Dev/Default for `dev` channel
* ~/Library/Application Support/BraveSoftware/Brave-Browser-Beta/Default for `beta` channel
* ~/Library/Application Support/BraveSoftware/Brave-Browser-Canary/Default for `canary` channel
* ~/Library/Application Support/BraveSoftware/Brave-Browser/Default for `release` channel

#### For unofficial build
* ~/Library/Application Support/BraveSoftware/Brave-Browser-Development/Default for `all` channel

## TODOs
- [x] channel option for build command (brave-browser)
- user dir support (brave-core)
  - [x] MacOS
  - [x] Windows
  - [x] Linux
- install dir
  - [x] MacOS
  - [x] Windows
  - [x] Linux
- app icon (brave-core)
  - [x] MacOS
  - [x] Windows
  - [x] Linux

**Comment by simonhong** [comment]
To use different tag of chrome project, how to get each tag information?
Should `package_config` of `brave-browser` contains all tags?
