### ISSUE TITLE
save password prompt has graphic (C83)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10008]
## Description 

C83 save password prompt has a graphic, where C81 password prompt did not.

## Steps to Reproduce

   1. Navigate to a site where you have to save credentials
   2. Login
   3. After login, you should be prompted to save your password

## Actual result:
C83:
<img width="341" alt="Screen Shot 2020-05-29 at 2 57 30 PM" src="https://user-images.githubusercontent.com/28145373/83297498-af982d00-a1c0-11ea-869a-e8c922b0b8f4.png">

## Expected result:
C81:
<img width="355" alt="Screen Shot 2020-05-29 at 3 07 06 PM" src="https://user-images.githubusercontent.com/28145373/83297501-b161f080-a1c0-11ea-8b00-b9ff20d7c923.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.11.37 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @mkarolin @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```
Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified STR from the description
![image](https://user-images.githubusercontent.com/38657976/84011494-d3fbc280-a993-11ea-9e80-51418731c177.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.15.5 (Build 19F101)
```

<img width="425" alt="Screen Shot 2020-06-05 at 5 05 29 PM" src="https://user-images.githubusercontent.com/2602313/83923265-e38ac980-a74f-11ea-8c48-13f249fe54e4.png">

<img width="406" alt="Screen Shot 2020-06-05 at 5 05 41 PM" src="https://user-images.githubusercontent.com/2602313/83923264-e2f23300-a74f-11ea-9661-bd67b5ec22a3.png">

<img width="446" alt="Screen Shot 2020-06-05 at 5 07 02 PM" src="https://user-images.githubusercontent.com/2602313/83923262-e2599c80-a74f-11ea-8e9b-f92d2fee7dcf.png">
