### ISSUE TITLE
site menu is missing links to cert, cookie manager, and site settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#10009]
## Description 
Site menu should still have links to cert, cookie manager, and site settings instead of being replaced with a listing of site settings (somewhat convenient but not implemented in the proper way).

## Steps to Reproduce

   1. Visit any url.
   2. Select lock icon to pull up the menu.
   3. Notice links to cert and cookie manager are missing.

## Actual result:
<img width="386" alt="Screen Shot 2020-05-28 at 11 43 07 PM" src="https://user-images.githubusercontent.com/5951041/83300371-b7e66d00-a1ac-11ea-9953-dcd5d6b1e8d6.png">

## Expected result:
<img width="316" alt="Screen Shot 2020-05-29 at 12 58 42 PM" src="https://user-images.githubusercontent.com/5951041/83300384-bd43b780-a1ac-11ea-879f-3cd7602163be.png">

## Reproduces how often: 
Easily.

## Brave version (brave://version info)

Brave | 1.11.37 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.15.5 (Build 19F83c)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No.
- Can you reproduce this issue with the beta channel? No.
- Can you reproduce this issue with the dev channel? No.
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Chromium 83 clean-up.

**Comment by rebron** [comment]
cc: @mkarolin can you take a look when you get a chance?

**Comment by rebron** [comment]
Verified fix using:

Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.15.5 (Build 19F83c)

![Screen Shot 2020-06-09 at 10 32 08 AM](https://user-images.githubusercontent.com/5951041/84180623-aae33c80-aa3c-11ea-9396-281531375878.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.5 (Build 19F101)
```

* ensured that clicking on `Certificate` correctly loads the certificate viewer
  * ensured that you can go through the various levels of the certificate
* ensured that clicking on `Cookies` opens the `Cookies in use` viewer
  * ensured that you can view/browse through the various cookies listed
   * ensured that you can remove various cookies using `Remove`
   * ensured that you can `Block` & `Unblock` cookies
* ensured that clicking on `Site settings` opens `brave://settings/content/siteDetails?site=[website]` without issues/crashes

<img width="370" alt="Screen Shot 2020-06-10 at 11 05 15 PM" src="https://user-images.githubusercontent.com/2602313/84340489-dc5c2500-ab6e-11ea-9d2c-eb5bb29e4e4c.png">
