### ISSUE TITLE
[Android] Add "refresh status" feature in Brave Rewards dropdown tipping panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#10005]
## Description 

In order to reach feature parity with desktop and iOS, the "refresh status" feature (originally https://github.com/brave/brave-browser/issues/3339) should be added to Android. 

"Refresh status" is an important feature that enjoys widespread usage among users and creators. (See https://github.com/brave/brave-browser/issues/3339 for more on initial motivations.)

@anthonypkeane @SergeyZhukovsky

**Comment by samartnik** [comment]
Test plan 1:
1. Switch on staging server.
2. Go to wikipedia.org, make sure it's not verified.
3. Click `Refresh Status` button, make sure it becomes verified.
4. Export rewards database.
5. In database change `status` in `server_publisher_info` table for wikipedia.org to 0.
6. Recheck steps 2 and 3.

**Comment by samartnik** [comment]
![device-2020-07-31-165017](https://user-images.githubusercontent.com/30602739/89076350-1915f280-d34e-11ea-8679-725ab0c1ac75.png)

**Comment by srirambv** [comment]
+1 from @Occhioverde via #11241

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/10005#issuecomment-667349532
- Verified clicking on refresh button updates the publisher list and shows verified checkmark
![1+refresh](https://user-images.githubusercontent.com/17010094/91330163-fa761080-e7c0-11ea-81bc-3357877bb442.gif)
-------------------
 Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/10005#issuecomment-667349532
- Verified clicking on refresh button updates the publisher list and shows verified checkmark
![tabrefresh](https://user-images.githubusercontent.com/17010094/91330671-acadd800-e7c1-11ea-81b9-3a92f58b6f05.gif)
