### ISSUE TITLE
[Android] Brave Shields icon hides the share button in Custom Tabs

### ISSUE THREAD

**Issue by antinucleo** [brave/brave-browser#10014]
## Description 
If you open a link with a custom tab with Brave, the Shields icon hides the share button.

## Steps to reproduce 

Open a link with a custom tab, for example a link sent by Telegram.
   

## Actual result 
You can even see a part of the share button below the Shields icon.
![Screenshot_20200530-192115](https://user-images.githubusercontent.com/54779024/83335129-daf74680-a2aa-11ea-882f-d4020a307b73.png)

## Expected result
![Screenshot_20200530-192338](https://user-images.githubusercontent.com/54779024/83335175-24e02c80-a2ab-11ea-9eb9-429de0e355cc.png)

## Issue reproduces how often 
Always.

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? The same issue both in Stable and Beta channels.

## Device details
   - Install type (ARM, x86): arm64
   - Device (Phone, Tablet, Phablet): Google Pixel 2 XL
   - Android version: Android 10
   
## Brave version
Stable 1.8.112
Beta 1.9.78

### Additional information
I think a solution could be to use the same approach of the new Firefox for Android that has a "Shields" icon too, that is to have the share button at his place (to the right) and the shield icon on the opposite place (to the left):
![Screenshot_20200530-192514](https://user-images.githubusercontent.com/54779024/83335349-7d63f980-a2ac-11ea-86c6-2ae379d78ab1.png)

**Comment by javiersantos** [comment]
It happens on Brave 1.12 (Android) as well

**Comment by machiav3lli** [comment]
Or at least add it to the bar menu. In the current situation, as a user, you only have two solutions, either copy-paste the link or switch to the full browser and then share. I think this is an essential needed fix. Thanks.

**Comment by srirambv** [comment]
This is fixed now
