### ISSUE TITLE
brave allows portscans from visited websites

### ISSUE THREAD

**Issue by glycerine** [brave/brave-browser#10016]
according to https://www.bleepingcomputer.com/news/security/list-of-well-known-web-sites-that-port-scan-their-visitors/

Brave allows portscans when browsing. This is the kind of thing I would usually expect Brave to block.

![image](https://user-images.githubusercontent.com/445247/83339554-c4de8b80-a294-11ea-81c3-678c30b56907.png)

**Comment by fmarier** [comment]
Also tracked in https://github.com/brave/brave-browser/issues/9860.
