### ISSUE TITLE
Brave Rewards: Twitter Tipping: Banner "shake" and +4 tipping values

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#10012]
## Description 

I've recently spent several hours tipping people on Twitter, and ran into a recurring issue that I'm able to reproduce with some twitter profiles. 

There are two issues observed, most often together. 

1. The tipping banner shakes / vibrates / jumps around the screen. 
2. Between 4-6 different tipping values display, instead of the expected 3 in the banner. 

## Steps to Reproduce

   1. Go to Twitter.com 
   2. Attempt to tip any of these handles: @cesarcosta86, @KurtBruhnke, @IGY6Live, @endodoug
   3. Observe tipping banner jitter + additional tipping values

## Actual result:

![Screenshot from 2020-05-29 14-35-30](https://user-images.githubusercontent.com/8979240/83309394-fcc6cf80-a1bd-11ea-89a2-3a4651b947f2.png)
![Screenshot from 2020-05-28 11-57-13](https://user-images.githubusercontent.com/8979240/83309421-0ea87280-a1be-11ea-99ff-fc1bd72f9d85.png)
![Screenshot from 2020-05-28 11-49-33](https://user-images.githubusercontent.com/8979240/83309433-1a943480-a1be-11ea-961e-281d3f0d0581.png)
![Screenshot from 2020-05-21 18-10-18](https://user-images.githubusercontent.com/8979240/83309460-2f70c800-a1be-11ea-800e-473c7adc4352.png)

## Expected result:
Should only see 3 tipping value options 

## Reproduces how often: 

Easy to repro from the handles listed in item 2 above

## Brave version (brave://version info)

Brave | 1.10.72 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}

## Version/Channel Information:

- Can you reproduce this issue with the current release? TBD
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? TBD

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@lukemulks is this still a problem?

**Comment by NejcZdovc** [comment]
closing as stale
