### ISSUE TITLE
Extension disabled by Brave, no way to enable

### ISSUE THREAD

**Issue by Nuc1eoN** [brave/brave-browser#10018]
## Test plan
See https://github.com/brave/brave-core/pull/8392

## Description
There seems to be a new security feature in place which disallows "unverified" Addons.
The Brave [support page](https://support.brave.com/hc/en-us/articles/360017914832-Why-am-I-seeing-the-message-extensions-disabled-by-Brave-?hl=de) says this is done as a protection for the user.

I am an experienced user however and know what I am doing, also I am not a malicious actor which Brave is trying to protect me from.

I would like to have an option to enable my addon even if it is unverified.

Brave v1.9.72

**Comment by rebron** [comment]
Hi @Nuc1eoN 
The unverified add-on should work for dev and nightly channels but not for release channel. What extension are you trying to sideload?

**Comment by Nuc1eoN** [comment]
Hey, I am trying to sideload [netflix-1080p](https://github.com/truedread/netflix-1080p) which is the only addon that allows me to watch netflix in 1080p on linux.

So for now I've switched to Chromium for the full netflix experience or I am rebooting to Windows.

**Comment by Peter-JanGootzen** [comment]
Then what is the developer mode for if we can't use unverified extensions?

**Comment by Peter-JanGootzen** [comment]
I found out that this restriction does not apply when installing an unpacked extension (extract the .crx into a folder with 7z and load that folder as an unpacked extension).

**Comment by Nuc1eoN** [comment]
Would any developer dare to look into this issue?

Or give an official statement what is going on?

**Comment by esjarc** [comment]
#2457 seems to be a duplicate of this.

Brave actually is unusable for me because of this very issue.

**Comment by bsclifton** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/2457

This will be fixed on Linux with https://github.com/brave/brave-core/pull/8392
