### ISSUE TITLE
[Android] Expand estimated pending rewards to three decimal places

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#10028]
## Description 
Currently the estimated pending rewards display on the brave://rewards page, and the ad grant claimed amounts round to one decimal place.  They should round to 3 decimal places so that users can see ads that yield less than 0.1 BAT per view.

**Comment by tmancey** [comment]
Fixed by https://github.com/brave/brave-browser/issues/10027

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.98 x64 build
- Verified estimated pending rewards show 3 decimal points
![image](https://user-images.githubusercontent.com/17010094/88277689-0873d580-ccd9-11ea-8bc6-6b4703f52bbf.png)


--------

Verification passed on Samsung Tab A with Android 10 running 1.11.98 x64 build
- Verified estimated pending rewards show 3 decimal points
![image](https://user-images.githubusercontent.com/17010094/88276119-6f43bf80-ccd6-11ea-82d5-1abc938ddf6a.png)
