### ISSUE TITLE
Page https://www.microsoft.com/de-de/software-download/windows10 is not loaded.

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#10024]
## Description 
Page https://www.microsoft.com/de-de/software-download/windows10 is not loaded.

## Steps to Reproduce
   1.  www.microsoft.com/de-de/software-download/windows10
   2. 
   3. 

## Reproduces how often: 
always

## Brave version (brave://version info)
Brave	1.9.76 Chromium: 81.0.4044.138 (Official Build) (32-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	Windows 10 OS Version 1909 (Build 18363.592)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
  NO
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
  Yes

**Comment by k-kruglov** [comment]
Loads for me fine. Have you tried creating new profile/disabling all the extensions you have?


![Screenshot 2020-06-02 at 13 00 12](https://user-images.githubusercontent.com/1358036/83507307-0fe4e280-a4d1-11ea-826c-93af7442cd61.png)

**Comment by Johann999** [comment]
I have no extensions.
![microsoft](https://user-images.githubusercontent.com/53431361/83529055-1e8bc380-a4ea-11ea-93e3-12e725860cc9.png)
