### ISSUE TITLE
Add pending state in the UI for uphold

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10023]
We should be adding pending state into wallet button so user can disconnect from there if they are stuck

**Comment by LaurenWags** [comment]
Marking as QA/Blocked as this needs a new 1.12.x build to test

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6140
- Verified pending popup on brave://rewards
![image](https://user-images.githubusercontent.com/34715963/89476502-220e2600-d78b-11ea-994f-301c8bdc436f.png)

- Verified pending popup on Rewards Panel
![image](https://user-images.githubusercontent.com/34715963/89476447-0440c100-d78b-11ea-9e87-f908ee920ed2.png)

Also verified in Polish locale. `Pending` is not translated. Logged https://github.com/brave/brave-browser/issues/11100
![image](https://user-images.githubusercontent.com/34715963/89478949-d57a1900-d791-11ea-80da-9c1015ce2b84.png)
