### ISSUE TITLE
Warn users that the recovery key / backup does not actually back up their BAT balance (only their estimated ad earnings)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#10021]
## Description

Since v1.3, BAT is stored and calculated locally as part of the browser's data. However, the backup/recovery key option still exists in the browser and leads users to believe that it will back up their BAT balance. In reality, the recovery key only backs up their "estimated ad earnings this month" counter, which is determined server-side.

This is deeply confusing to users, and many users are left puzzled and upset after they find out that they can only restore `0.0 BAT` of their previous balance. 

A very large number of users have been affected by this. For one example: https://www.reddit.com/r/BATProject/comments/gu182q/all_my_bats_are_gone_after_recovery/

## Possible Solution

Although this may be solved in the future with a later implementation of Sync v2 that works with Brave Rewards data, an _interim solution is required_.

For example, we can provide appropriate messaging warning users of the recovery feature and its limits.

A more limiting solution would be to hide or remove the backup feature completely (like on iOS and Android).

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/gukyz8/lost_45_worth_of_bat_d/

**Comment by cryptojennie** [comment]
+1 https://www.reddit.com/r/BATProject/comments/gx9qit/missing_bat_after_recovery/

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/all-my-bat-dissapeared/137295

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` until able to sync up with @mandar-brave

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
Revision	a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/5958
For Test plan 1 from the spec:
- confirmed text on modal matches spec
- confirmed clicking the Uphold link opens login page to Uphold
- confirmed able to switch between Backup/Restore/Reset 
- note, had to refresh brave://rewards page to get the correct backup/restore modal, logged https://github.com/brave/brave-browser/issues/11111 for this but it only seems to affect 1.12.x, 1.13.x and above aren't experiencing this

<img width="706" alt="Screen Shot 2020-08-06 at 9 56 38 AM" src="https://user-images.githubusercontent.com/28145373/89545164-00379200-d7d1-11ea-8828-7a8ce7840dae.png">


For Test plan 2 from the spec:
- confirmed text on modal matches spec
- confirmed clicking the Uphold link opens login page to Uphold

<img width="690" alt="Screen Shot 2020-08-06 at 9 54 12 AM" src="https://user-images.githubusercontent.com/28145373/89545168-0299ec00-d7d1-11ea-9270-995a5c1c4f7e.png">


The following are existing open/related issues (confirmed with @nejczdovc & @mandar-brave as appropriate)
   * To handle backup/restore notification: https://github.com/brave/brave-browser/issues/6259
   * To add 25 BAT limit messaging to uphold link on backup/restore modal: https://github.com/brave/brave-browser/issues/11023

Also spot checked the following upgrade scenarios:
1. Upgrade with only VG, opened got correct backup modal (no words displayed)
2. Upgrade with VG + user funds, got correct backup modal (words displayed)
3. Upgrade with only user funds, got correct backup modal (words displayed)
4. Upgrade with only Uphold, got correct backup modal (no words displayed)

-------------
