### ISSUE TITLE
Expand Rewards to three decimal places

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#10027]
## Description 
Currently the estimated pending rewards display on the brave://rewards page, the estimated pending rewards display on the new tab page widget, and the ad grant claimed amounts round to one decimal place.  They should round to 3 decimal places so that users can see ads that yield less than 0.1 BAT per view

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.11.78 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Windows 10 OS Version 1903 (Build 18362.900)

```
- Verified the description from the issue https://github.com/brave/brave-browser/issues/10027#issue-628119450

Clean profile:
- Viewed an ad and confirmed that brave://rewards Ads panel `Estimated pending rewards` displays 3 decimal places
![image](https://user-images.githubusercontent.com/38657976/85844190-f11bf800-b7bf-11ea-87cb-471a23981277.png)
- Verified that NTP widget `Estimated earnings so far this month` displays the 3 decimal places 
![image](https://user-images.githubusercontent.com/38657976/85844413-5374f880-b7c0-11ea-89ba-c054642f31a4.png)
