### ISSUE TITLE
Can not use google meet after to upgrade my system.

### ISSUE THREAD

**Issue by afierro** [brave/brave-browser#10025]
## Description 
After to make a full operative system upgrade, (including Brave version), I can not use google meet any more.

## Steps to Reproduce
   1. Log in to gmail.
   2. Go to meet.google.com
   3. Try to start a new meet

## Actual result:
An error message is displayed:
--------
Aw, Snap!
Something went wrong while displaying this webpage.
--------

![image](https://user-images.githubusercontent.com/3358433/83362850-ed38b980-a36a-11ea-9301-7838d9884dfe.png)

## Expected result:
A meet session is started successfully.

## Reproduces how often: 
Every time that I want to start a meet with brave.

## Brave version (brave://version info)
I'm usingOS: Arcn Linux, Linux 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux

Brave version: Version 0.60.45 Chromium: 72.0.3626.109 (Official Build) unknown (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? in my previous version (I can not repoduce it)
- Can you reproduce this issue with the beta channel? no tested there
- Can you reproduce this issue with the dev channel? no tested there
- Can you reproduce this issue with the nightly channel? no tested there

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome? No. I've tested in Chromium and there is works fine: Version 83.0.4103.61 (Official Build) Arch Linux (64-bit)

## Miscellaneous Information:
I've run Brave from console, and I can see the following errors when I tried to start a meet:
`[1:1:0531/180635.421487:ERROR:audio_context.cc(52)] Create
[1:1:0531/180635.421797:ERROR:audio_context.cc(130)] AudioContext
[1:1:0531/180635.421969:ERROR:audio_context.cc(138)] user gesture
[1:1:0531/180635.424969:ERROR:audio_context.cc(436)] IsAllowedToStart
[1:1:0531/180635.425238:ERROR:audio_context.cc(93)] starting
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
`

**Comment by afierro** [comment]
I'm sorry about that!!
There was a mistake in my upgrade.
I already fixed it by uninstall the old version manually and install the new one.
It's working perfect!!!

**Comment by bsclifton** [comment]
Thanks for the update @afierro! Super glad it's working and also thank you for sharing what fixed it for you 😄
