### ISSUE TITLE
Uphold funds AC- AC is not recorded in summary and monthly statements

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10038]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/7595 (scenario 1 from https://github.com/brave/brave-core/pull/4869)
AC is not recorded in summary and monthly statements
## Steps to Reproduce

   1. start the browser with a short interval
   2. enable rewards
   3. connect to KYC uphold
   4. add some verified sites to AC table
   5. wait for AC to be triggered
   6. No AC notification on BAT logo
   7. AC is not recorded in summary and monthly statements
   8. Logs are not recorded for `/v1/autocontribute/votes`
   9. AC amount was taken from KYC'd uphold wallet

**Note**: KYC'd uphold wallet is self-funded via sandbox uphold account
## Actual result:

![image](https://user-images.githubusercontent.com/38657976/83424244-c8674380-a449-11ea-8bb9-47e586368e50.png)

![image](https://user-images.githubusercontent.com/38657976/83424150-a79eee00-a449-11ea-8a8a-dd91924df60e.png)

## Expected result:
AC should be recorded in summary and monthly statements

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.10.79 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? not sure
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @NejcZdovc @brave/legacy_qa @rebron

**Comment by NejcZdovc** [comment]
can you please re-test it when this one lands in 1.10 https://github.com/brave/brave-browser/issues/9962. It was merged 4h ago in 1.10

**Comment by kjozwiak** [comment]
Closing as per the above 👍 @GeetaSarvadnya please recheck once https://github.com/brave/brave-core/pull/5692 lands in `1.10.x` as https://github.com/brave/brave-core/pull/5694 has been uplifted.
