### ISSUE TITLE
[Android] [Bug] Storage Issues

### ISSUE THREAD

**Issue by aliglelo** [brave/brave-browser#10031]
## Description 
Freshly installed and using browser for browsing even less than 30 minutes make total storage occupied by browser grater than 300 mbs.
While in case of [Bromite](https://github.com/bromite/bromite) using it for more than 2 days and even with 3-4 pwa installations it has less than 15m mbs of storage. 

## Steps to reproduce 

   1.Download Brave.
   2.Browse Web for some time.
   3.See app details

## Actual result 
App should be using less storage.

## Expected result
App is using almost double the storage.

## Issue reproduces how often 
Every Time

## Issue happens on 
   - Current Play Store version

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Redmi 7
   - Android version: 9.0
   
## Brave version
 1.8.112

**Comment by srirambv** [comment]
Are you enabling rewards during onboarding? 

cc: @brave/android

**Comment by aliglelo** [comment]
No I'm not using brave rewards

**Comment by aliglelo** [comment]
So finally closing the Issue because no one is here to help the users in brave neither they welcome to solve the issues of users.

**Comment by SergeyZhukovsky** [comment]
![Screenshot_20200619-095433](https://user-images.githubusercontent.com/12011303/85140721-a6284080-b213-11ea-8de3-ae9323552b35.png)
![Screenshot_20200619-095819](https://user-images.githubusercontent.com/12011303/85140730-aaecf480-b213-11ea-9df9-56f8410de875.png)
Bromit and latest Brave nightly. Freshly installed and I opened just 3 websites on both. I have no idea how 2 days of using Bromite bring you to only 15Mb as I have 15 just with 3 websites opening. It's a cache, you can clean it on both Bromite and Brave. It is used for faster loading pages in the future. It really depends also what did you open in Brave in that 30 minutes and in Bromite in 2 days. For the experiment be clear it should be the same websites ideally.
I personally don't see any problems from pics I posted above. If you see any problems could you please paste your screenshots and make sure you have the same usage for both to compare them.

**Comment by SergeyZhukovsky** [comment]
App size is a separate problem that we are working on and trying to decrease.

**Comment by aliglelo** [comment]
So here are my screenshots after two days of usage :
Before 

![Screenshot_2020-06-19-19-57-37-731_com miui securitycenter](https://user-images.githubusercontent.com/30858084/85147191-0633dc80-b23e-11ea-9319-96599cb2e12f.jpg)

And After :

![Screenshot_2020-06-19-19-57-32-392_com miui securitycenter](https://user-images.githubusercontent.com/30858084/85147253-1d72ca00-b23e-11ea-9249-6941043e3441.jpg)

**Comment by bsclifton** [comment]
Link to issue where we're trying to make APK size smaller:
https://github.com/brave/brave-browser/issues/10277
