### ISSUE TITLE
[Android] First NTP doesn't load SR images even when component is ready 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10033]
## Description 
First NTP doesn't load SR images even when component is ready 

## Steps to reproduce 

   1. Install SR build
   2. Open the browser and wait for the component to be downloaded
   3. First NTP gets the custom assets tiles but doesn't download the image

## Actual result 
First NTP doesn't load SR images even when the component is ready 
Recording: https://bravesoftware.slack.com/archives/C0816QH3R/p1590990198121500

## Expected result
Should be similar to iOS and load all current tabs with custom assets when the component is ready

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.9.77

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by GeetaSarvadnya** [comment]
Reproduced in Gionee 5.1 running `BraveModernar.1.9.77.apk`

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.10.92 on Samsung Galaxy Tab S5e (Android 9.0)

Verified test plan from the description.
Verified that if regular ntp images are not ready, a place holder is shown
Verified regular ntp images replace place holder when ready
Verified sr ntp images replace regular ntp images when ready
