### ISSUE TITLE
Link preview should show punycode encoded domain name (not decoded IDN)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1004]
Opening per comment in https://github.com/brave/browser-laptop/issues/5220 on browser-laptop

When you hover over a link on a page in browser-laptop, it shows the punycode encoded domain name (example here is an IDN being hovered over w/ mouse in browser-laptop):
<img width="272" alt="screenshot 2016-10-28 15 54 52" src="https://cloud.githubusercontent.com/assets/3362943/19797568/e72b640a-9d26-11e6-8e37-756691ef3f6e.png">

@diracdeltas notes:
> We display punycode-only to prevent homograph attacks, see for instance https://thehackernews.com/2017/04/unicode-Punycode-phishing-attack.html. Google has some standards for what unicode characters should be displayed as punycode. https://www.chromium.org/developers/design-documents/idn-in-google-chrome

**Comment by tomlowenthal** [comment]
This may already be resolved by work in Chrome.

**Comment by bsclifton** [comment]
This is definitely resolved - tested using https://www.xn--80ak6aa92e.com/ aka https://www.аррӏе.com/
