### ISSUE TITLE
Crypto wallet "Ask" setting should ask for dynamic switching of provider

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#10042]
## Description 

A user on Communty recently had a feature request regarding the Web3 provider for using Dapps function of Brave Browser.

At this time, there are four options for the drop down menu: `Ask` , `None` , `Crypto Wallets` , and `MetaMask` if it is installed. 
If a user has both  Crypto Wallets and MetaMask installed, when `Ask` is selected, brave current mechanism is using the intended behavior – the browser will default to the method you select when initially asked.

This means that you need to manually switch the option in settings each time if I want use alternative one, which is not convenient and could be adjusted to better cater to user preference.

![image](https://user-images.githubusercontent.com/3299098/83430795-231d8280-a3eb-11ea-8867-36c3271dc780.png)

### Additional Information
Initial feature request on Community:
https://community.brave.com/t/about-the-selection-of-web3-provider-for-using-dapps-in-extensions-of-settings/130001/7

**Comment by bbondy** [comment]
Interesting use case to dynamically allow both providers, thanks for posting @Brave-Matt  👍

**Comment by ryanml** [comment]
Closing this, it is a great suggestion, but we are taking things in a different direction with dapp detection/the infobar and it may no longer be relevant
