### ISSUE TITLE
Anon user funds AC- AC is not recorded in summary and monthly statements

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10040]
## Description 

Found while testing #7595 (scenario 2 from brave/brave-core#4869)
AC is not recorded in summary and monthly statements
## Steps to Reproduce

   1. start the browser with a short interval
   2. enable rewards
   3. restore wallet with user funds
   4. add some verified sites to AC table
   5. wait for AC to be triggered
   6. No AC notification on BAT logo
   7. AC is not recorded in summary and monthly statements
   8. Logs are not recorded for `/v1/autocontribute/votes`
   9. AC amount was taken from wallet and wallet balance is reduced

## Actual result:

AC is not recorded in summary and monthly statements
![image](https://user-images.githubusercontent.com/38657976/83428152-850fd380-a44f-11ea-8171-d489180db9ea.png)

## Expected result:
AC should be recorded in summary and monthly statements

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.10.79 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by kjozwiak** [comment]
@GeetaSarvadnya please retest this once https://github.com/brave/brave-core/pull/5692 lands in `1.10.x` as https://github.com/brave/brave-core/pull/5694 has been uplifted. I checked `1.11.41 CR: 83.0.4103.61` via https://github.com/brave/brave-core/pull/5692#issuecomment-637167606 and a-c is being correctly displayed in the `summary panel` and the `monthly report`. Also received a notification that the a-c went through.
