### ISSUE TITLE
A migration tool from Chrome, Safari, etc

### ISSUE THREAD

**Issue by faresd** [brave/brave-browser#10048]
## Description 
It would be great to have some migration tool for bookmarks, passwords, etc.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Hi @faresd. brave://settings/importData or in brave://settings in the Get Started section. 
We're doing this as well. https://github.com/brave/brave-browser/issues/3568
