### ISSUE TITLE
Issues with sound on itch.io

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [brave/brave-browser#10046]
## Description 
There's no sound in HTML5 games(doesn't matter if it uses WebGL or not), example: https://guerragames.itch.io/thegreenlegion. I tried to disable Shield, but that doesn't help.

## Steps to Reproduce

   1. Go to I still have problems on itch.io. Even when shield us down -- there's no sound https://guerragames.itch.io/thegreenlegion
   2.  Run the game

## Actual result:
Game runs, but there's no sound

## Expected result:
Sound should work

## Brave version (brave://version info)

Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1909 (Build 18363.836)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

I see same problem on Linux.
Sound works on other sites, like https://html5games.com/.

**Comment by rebron** [comment]
@GrigoriyMikhalkin Can you try in the latest build, 1.11.97? We made some changes to our fingerprint blocking and issue may have been fixed. I'm running Beta now and I can hear sound `https://guerragames.itch.io/thegreenlegion`

**Comment by GrigoriyMikhalkin** [comment]
Hi @rebron. Yes, it's working now, thanks!
