### ISSUE TITLE
Site settings Autoplay value selector is not showing correctly

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#10049]
## Description 

Site settings' Autoplay dropdown selector doesn't show any value by default and when clicked "Block" value is not listed, instead there is a blank line. 

## Steps to Reproduce

   1. Open Brave and navigate to a site, for example, brave.com
   2. Go to Settings -> Privacy and Security -> Site and Shields Settings -> View permissions and data stored across sites
   3. Select site visited in step 1 (brave.com)
   4. Scroll down to Autoplay setting
   5. Notice that the value for Autoplay is empty
   6. Click on the drop down and notice that there are 4 rows instead of 3 and 2 of them are empty.

## Actual result:

![image](https://user-images.githubusercontent.com/41635752/83473881-9dd0b700-a458-11ea-8d7b-27e06b60a4d1.png)

![image](https://user-images.githubusercontent.com/41635752/83473911-b345e100-a458-11ea-81a5-f166e2385737.png)

## Expected result:
The default value is shown:
![image](https://user-images.githubusercontent.com/41635752/83474075-1cc5ef80-a459-11ea-8817-782af318f554.png)

Dropdown shows correct available values:
![image](https://user-images.githubusercontent.com/41635752/83474109-30715600-a459-11ea-8b19-2eaeb0c4b757.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

1.11.41 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified STR from the description, verified in both clean and upgraded profile
![image](https://user-images.githubusercontent.com/38657976/84027249-4d071400-a9ac-11ea-8a2c-6a5a72c4c4c1.png)

**Comment by btlechowski** [comment]
Testing is blocked on https://github.com/brave/brave-browser/issues/10160
