### ISSUE TITLE
Sync passwords across platforms or integrate with Apple keychain or others.

### ISSUE THREAD

**Issue by faresd** [brave/brave-browser#10047]
## Description 

Sync passwords across platforms or integrate with Apple keychain on mac or others like one password, etc.
Maybe another solution is to have Brave own authentication service?

**Or some sort of password sync based on blockchain based en Ethereum (most secure and best solution for me).**

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing as dupe #9989
