### ISSUE TITLE
Anon user funds tips - one time tip sent is not recorded in summary and monthly report

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10041]
## Description 

Found while testing #7595 (scenario 3 from brave/brave-core#4869)

Anon user funds tips - tip sent is not recorded in the summary and monthly report

## Steps to Reproduce

   1. enable rewards
   2. restore wallet with user funds
   3. go to verified site and do one-time tip
   4. amount is reduced from the balance
   5. tip sent is NOT recorded in the summary and monthly report
   6. logs not recorded for `/v1/autocontribute/votes`
   
## Actual result:

Tip sent is not recorded in the summary and monthly report
![image](https://user-images.githubusercontent.com/38657976/83428943-e7b59f00-a450-11ea-9428-34a43cbda9ca.png)

## Expected result:
Tip sent is not recorded in the summary and monthly report

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.10.79 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? not sure
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by kjozwiak** [comment]
@GeetaSarvadnya please retest this once https://github.com/brave/brave-core/pull/5692 lands in `1.10.x` as https://github.com/brave/brave-core/pull/5694 has been uplifted. I checked `1.11.41 CR: 83.0.4103.61` and ensured the above was working as per the following:

Ensured that tips are being recorded under both the `summary panel` and the `monthly report`:

<img width="410" alt="Screen Shot 2020-06-01 at 9 00 38 PM" src="https://user-images.githubusercontent.com/2602313/83475249-efc70c00-a45b-11ea-82d0-210416cbe2ea.png">

<img width="981" alt="Screen Shot 2020-06-01 at 9 00 45 PM" src="https://user-images.githubusercontent.com/2602313/83475333-20a74100-a45c-11ea-9fe6-e6f79f820b0c.png">
