### ISSUE TITLE
Can't copy a number on Google Maps

### ISSUE THREAD

**Issue by jamesray1** [brave/brave-browser#10054]
## Steps to Reproduce

   1. Go to e.g. https://www.google.com/maps/place/Blinds+Botany/@-33.9170769,151.1723238,13z/data=!4m8!1m2!2m1!1sblinds!3m4!1s0x6b12b13d66c42bf3:0x2d96c069adf66f0a!8m2!3d-33.9486953!4d151.2002953
   2. Click copy number
   3. Paste it somewhere

## Actual result:

It's not copy-pasted.

## Expected result:
It copy-pastes.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Version 1.9.68 Chromium: 81.0.4044.138 (Official Build) unknown (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?  It is on Version 80.0.3987.116 (Official Build) (64-bit)—but that is not the latest version.

**Comment by joejoejo** [comment]
can confirm the bug is still happening on the latest beta Version 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)

**Comment by jamesray1** [comment]
Also, I updated to Version 1.9.68 Chromium: 81.0.4044.138 (Official Build) unknown (64-bit). Still occurs.

**Comment by jamesray1** [comment]
Oh wait, I can copy-paste numbers now, as expected in Chrome, Brave, and Firefox.

**Comment by jamesray1** [comment]
Now it has stopped working again!

**Comment by bsclifton** [comment]
Looks like it works for me? I believe this is a problem on the Google side. I don't see anything about the browser functionality that would be causing this
