### ISSUE TITLE
Reinstall Brave link points to the wrong download url

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#10059]
## Description 
The Reinstall Brave link for some users that are several versions back and haven't upgraded yet points to the the wrong download url. The Reinstall Brave link should point to: https://www.brave.com/download/

## Steps to Reproduce

tbd
   1. 
   2. 
   3. 

## Actual result:

![update brave](https://user-images.githubusercontent.com/5951041/83568863-86d1a980-a4d8-11ea-8119-ef95525cde67.PNG)
Download url points to https://google.com/chrome/...

## Expected result:
Reinstall Brave download url points to https://www.brave.com/download/

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by mbacchi** [comment]
The URL that they were sent to appears to be part of the [Omaha client](https://github.com/brave/omaha), which we use for our updates. If their metainstaller is old and unsupported it appears it just shows them a URL to download a new version of the browser from, so we should be able to modify [this string](https://github.com/brave/omaha/blob/master/omaha/internal/grit/goopdateres.grd#L158-L161) to point to brave.com/download.

**Comment by rebron** [comment]
Closing. Duplicate of #2942
