### ISSUE TITLE
Auto Contribute does not work if there is more than 1 verified publisher in AC list

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10058]
## Description 

If you have more than 1 verified publisher in AC list, auto contribute does not occur properly. Experienced when doing AC w/ KYC'd uphold wallet, but should check user funded (anon) and VG funded wallets also

## Steps to Reproduce

   1. Clean profile w/ flags like `/Applications/Brave\ Browser\ Dev.app/Contents/MacOS/Brave\ Browser\ Dev --enable-logging=stderr --vmodule=*rewards*=6 --log-level=2 --rewards=staging=true,reconcile-interval=3 --brave-ads-staging`
   2. Enable Rewards
   3. Connect KYC'd uphold account
   4. Add at least 2 verified publishers to AC list (I used ddg and laurenwags.github.io)
   5. Wait for AC to occur.

** When retesting, check w/ VG BAT and user funded (restored anon wallet) for step 3)

## Actual result:
Balance decreases by monthly budget but AC does not get listed in UI/monthly summary. Logs show it is retrying.

## Expected result:
AC should work

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.10.80 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @rebron @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
The issue is reproduced on

```

Brave | 1.10.80 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```

**Comment by GeetaSarvadnya** [comment]
Here are my observations on the issue.

1. Launched brave using staging flag and reconcile interval of 4 mins
2. Claimed UGP grants of 20 BAT
3. Added DDG and laurenwags.github.io pubs to AC table
4. waited for 4 mins
5. AC did not happen
6. Wallet balance reduced to 14.5 BAT at 6th min
7. Wallet balance reduced to 10 BAT at 8th min
9. Received AC notification at 9th min ad AC recorded in summary and monthly statement

**Comment by LaurenWags** [comment]
@GeetaSarvadnya  ok so looks like if you fund your wallet via VG (like UGP grant) then this works. we should double check that's still the case after this is fixed. We will also want to confirm if user funded anon cards work as well for AC.

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.10.87 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5728#issuecomment-640860615
Scenario 1:

- Verified test plan as written (using KYC'd Uphold wallet as a funding source) in brave/brave-browser#10058 (comment)
- Confirmed AC is listed in brave://rewards and on Monthly Summary:
![image](https://user-images.githubusercontent.com/38657976/84262279-fbd95a80-ab3a-11ea-9640-f5479a7ff583.png)
![image](https://user-images.githubusercontent.com/38657976/84262350-17dcfc00-ab3b-11ea-8afd-1b4b0b1c840b.png)
![image](https://user-images.githubusercontent.com/38657976/84262404-2d522600-ab3b-11ea-98f3-00911d7a59f1.png)
![image](https://user-images.githubusercontent.com/38657976/84262502-5c689780-ab3b-11ea-9259-bc74f4af2cbc.png)

Scenario 2 (wallet funded via VG like UGP grant):
