### ISSUE TITLE
Add possibility to completely reset rewards

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10064]
We should add a button in rewards page where user can clear rewards and reset everything in pre-opt in state. When clicking on a button we should be clear what this will do and link to FAQ page with even more info. User should type in something like `reset` to confirm decision.

To accomplish that we need to do the following.

- delete this files
  - ads_service folder
  - rewards_service folder
  - Rewards.log
- reset data in 
  - publisher_info_db (should just be deleted and initialization of db should be triggered)
  - Preferences (under `brave_rewards`)
- clear states in webui
  - extension panel
  - rewards page

For a reference from muon times: https://github.com/brave/brave-browser/issues/1192

**Comment by mandar-brave** [comment]
This also has potential to lose BAT if there was any virtual BAT; @NejcZdovc @evq

**Comment by NejcZdovc** [comment]
correct and we need to be really clear in modal about it

**Comment by NejcZdovc** [comment]
blocked by https://github.com/brave/brave-browser/issues/9526

**Comment by mandar-brave** [comment]
Text recommendation "Your BATs and other Rewards data will be permanently lost if you reset your wallet. Please ensure you have verified your wallet with Uphold before clicking Reset if you have any BAT in your wallet."

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc When rewards is reset, the `ads_service` folder is NOT removed from the profile folder. This step is failing as per the test plan https://github.com/brave/brave-core/pull/5913. Can you review the test plan and let us know if it's not expected then we will file an issue.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5913
- Verified the description mentioned in the issue 
- Logged follow up issue https://github.com/brave/brave-browser/issues/10934
