### ISSUE TITLE
[Android] Site stuck using old CSS

### ISSUE THREAD

**Issue by adrian5** [brave/brave-browser#10069]
## Description

A website that I had updated weeks ago was rendering in its old style in Brave, despite manual reload. It renders correctly in Private browsing mode.

## Steps to reproduce

Since I just did regular browsing, I don't know if any special action is necessary.

It's not obvious how to do a hard page refresh (flushing cache) in Brave, so I tried *Site Settings → Clear & reset* combined with a page reload – to no avail.

What fixed the issue for me was to briefly enable *Brave Shields → Block Scripts* (disabled by default) and reload the page. This appeared to cause the relevant files to be reloaded; the change persists after disabling *Block scripts* again.

Maybe there's an unforeseen code path in relation to this Brave Shields feature?

## Environment

Brave 1.8.112 (Play store) on Android 8.1.0

**Comment by joejoejo** [comment]
can you try the latest brave android release channel build as of righting it is https://github.com/brave/brave-browser/releases/tag/v1.9.79

**Comment by kjozwiak** [comment]
Going to close this as stale as there hasn't been an update since ~June. @adrian5, if you're still having issues, please feel free to comment and we can re-open the issue. Or you can always create a new issue with updated information 👍  Thanks again for filing!
