### ISSUE TITLE
Linux - Deleted Suspected Trojan Horse: bg-libs.js - Mistake?

### ISSUE THREAD

**Issue by wavesurf432** [brave/brave-browser#10068]
## Description 
Hello, I was wondering if you could help me with a problem I’m having? I posted this 10 days ago on community.brave, but haven't recieved any replies.

Last night I was doing a scan with Clamav for PUAs and bg-libs.js (/home/USERNAME/.config/BraveSoftware/Brave-Browser/odbfpeeihdkbihmopkbjmoonfanlbfcl/1.0.18/bg-libs.js) was flagged. I deleted the file, but after having done a bit more research I think this was a false positive.

I didn’t have the file saved via Timeshift. I did recover the file earlier via TestDisk, but it’s showing 0 bytes filesize, so I don’t know if this means that the file has been corrupted/changed now?

Is this an issue? Have I bricked Brave now? Was this file just something to do with cookies/cache?

If I reinstalled Brave via Synaptic Package Manager would this reset all of Brave, or would this just repair Brave so to speak and just reinstall the missing bg-libs.js file?

Any help is appreciated, thank you!

## Brave version (brave://version info)

Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux

**Comment by epicodertime** [comment]
Can you try installing brave but without the av as it could be corrupting brave installation

**Comment by srirambv** [comment]
@wavesurf432 the folder that was detected is for Brave Crypto Wallet. Do you have any Crypto Wallet account created on your profile? 

> Is this an issue? Have I bricked Brave now? Was this file just something to do with cookies/cache?

No browser is not bricked. Nothing to worry about and no need to reinstall the browser

Please try the following
1. Open `brave://component` page in a tab
2. Open `brave://wallet` in a second tab
3. Go back to tab from step 1 and wait for `Crypto Wallet` component to be listed, if it doesn't show up just reload the page
4. Click on check for update and make sure its updated to `1.0.20` which is the latest version and everything should be fine

**Comment by wavesurf432** [comment]
> @wavesurf432 the folder that was detected is for Brave Crypto Wallet. Do you have any Crypto Wallet account created on your profile?
> 
> > Is this an issue? Have I bricked Brave now? Was this file just something to do with cookies/cache?
> 
> No browser is not bricked. Nothing to worry about and no need to reinstall the browser
> 
> Please try the following
> 
> 1. Open `brave://component` page in a tab
> 2. Open `brave://wallet` in a second tab
> 3. Go back to tab from step 1 and wait for `Crypto Wallet` component to be listed, if it doesn't show up just reload the page
> 4. Click on check for update and make sure its updated to `1.0.20` which is the latest version and everything should be fine

Hey, thanks for the response!

If It's of any help, I didn't and don't have Brave's Crypto Wallet enabled, but thankfully everything worked itself out a few weeks ago; bg-libs.js automatically reinstalled itself due to a monthly payout of BAT I think. If I remember correctly, around the time I made this post, an update for Brave came out which didn't reinstall bg-libs.js. This makes me think it had something to do with Brave rewards resetting after it's monthly payout. Maybe I accidently enabled Crypto Wallet at some point while troubleshooting, but I honestly can't remember.

Anyway, all good now - thanks again!

**Comment by wavesurf432** [comment]
Hello again, 

I was just wondering, in /home/USERNAME/.config/BraveSoftware/Brave-Browser/odbfpeeihdkbihmopkbjmoonfanlbfcl, should there be a 1.0.19 and a 1.0.20 folder together or just the 1.0.20 folder? If it's the latter, I'm guessing it's not a problem to delete the 1.0.19 folder?

Any help's appreciated, thanks again!
