### ISSUE TITLE
Send dtoi param with usage ping

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#10061]
## Description 

https://docs.google.com/document/d/1iSYi_i52dP6YGdrUhP7J7DMBzxyPf9x6nFpg422LfLo/edit?usp=sharing

Each browser will need to store the YYYY-MM-DD encoded local date of installation. For the 14 days after installation, the usage ping should include a ‘dtoi’ entry containing the date of installation. After the 14 day period is over the ‘dtoi’ should be sent as null.

Example: The browser is installed on May 1st, 2020

For the dates including May 1st to May 14th, the usage ping should include the attribute 'dtoi': '2020-05-01'. For all days after the 14th of May the usage ping should send 'dtoi': null. Nothing else in the existing usage request body should change.

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` - need a new build to test, 1.11.92 or newer.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, https://github.com/brave/brave-browser/releases/tag/v1.11.92 is available

**Comment by LaurenWags** [comment]
Re-adding `QA/Blocked` until https://github.com/brave/brave-browser/issues/10610 is addressed.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from description

Ping on initial install:
<img width="746" alt="First Day" src="https://user-images.githubusercontent.com/28145373/87824315-0924eb80-c843-11ea-8f04-eb9bbde93a13.png">

Moved computer date 15 days ahead:
<img width="745" alt="15th Day" src="https://user-images.githubusercontent.com/28145373/87824333-12ae5380-c843-11ea-86be-197805051e34.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build 
- Verified `dtoi` param is set on install 
```js
{ “_id” : ObjectId(“5f33ef6be8dd460023eb6adb”), “daily” : true, “weekly” : true, “monthly” : true, “platform” : “android-bc”, “version” : “1.12.112”, “first” : true, “channel” : “release”, “woi” : “2020-08-10", “ref” : “SRI318", “country_code” : “IN”, “dtoi” : “2020-08-12", “braveDataCenter” : false, “braveAPIKeyStatus” : “matched”, “ts” : 1597239147472, “year_month_day” : “2020-08-12" }
```
- Verified moving device date ahead by 15 days `dtoi` is removed
```js
{ “_id” : ObjectId(“5f33efc7e8dd460023eb6dce”), “daily” : true, “weekly” : true, “monthly” : false, “platform” : “android-bc”, “version” : “1.12.112”, “first” : false, “channel” : “release”, “woi” : “2020-08-10", “ref” : “SRI318", “country_code” : “IN”, “braveDataCenter” : false, “braveAPIKeyStatus” : “matched”, “ts” : 1597239239922, “year_month_day” : “2020-08-12" }
```
- Logged follow up issue #11205 for missing `dtoi` instead of being sent null values

Thanks to @aekeus for helping it verify with backend system
