### ISSUE TITLE
Enabling Brave Rewards widget via settings page doesn't enable it in NTP

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10067]
## Description 

Enabling Brave Rewards widget via settings page doesn't enable it in NTP

## Steps to Reproduce

   1. Clean install 1.10.81
   2. Disable rewards and binance widget from dashboard
   3. Close browser and relaunch
   4. Enable rewards widget from brave://settings/newtab
   5. Open a new tab no rewards widget is shown, dashboard shows enabled 

## Actual result:

![Widget-Stack](https://user-images.githubusercontent.com/17010094/83629072-1ea5c500-a5b7-11ea-9865-020a61b55844.gif)

## Expected result:
Enabling widget from settings should be enabled on NTP

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Found while testing #9584
Reproduces on all platforms

**Comment by LaurenWags** [comment]
Ran into this today - noticed that if I have a NTP open when enabling from brave://settings, then the widget displays on the NTP. However, as with @srirambv steps if I don't have a NTP open when enabling from brave://settings, then the widget does not get displayed.

Reproduces for Binance widget as well.

Reproduced with


Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)


Brave | 1.11.85 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)

**Comment by LaurenWags** [comment]
@ryanml this issue doesn't have a milestone - which one should it be in?

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - `1.11.97`

**Comment by ryanml** [comment]
@LaurenWags apologies - this is in `1.12` cc: @GeetaSarvadnya

**Comment by LaurenWags** [comment]
awesome, thanks @ryanml 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified STR from the description
