### ISSUE TITLE
Change the HTTP error code Brave uses when blocking a network request to better match what other browsers and tools expect, to increase compatibility with crowdsourced filter lists

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#10063]
A long time ago we started "lying" to pages about scripts being blocked; even when we blocked a script, we didn't throw onerror, we treated it as a 200 empty. 

Now that we (all but tiny details) match uBO in capabilities, we should do what uBO does and trigger error path when adblock-rust blocks something

We should continue reporting 200 when we block-but-replace

**Comment by bsclifton** [comment]
@pes10k does this need QA? If so - can you add steps (and then mark as `QA/yes`)

**Comment by pes10k** [comment]
I dont think this needs a manual QA step, but for release notes, the below should be good i think:

```Change the HTTP error code Brave uses when blocking a network request to better match what other browsers and tools expect, to increase compatibility with crowdsourced filter lists```

**Comment by bsclifton** [comment]
@pes10k awesome! updated 😄👌

**Comment by bsclifton** [comment]
Re-opening after reverting with https://github.com/brave/brave-core/pull/7028

**Comment by bsclifton** [comment]
Re-opening; this got closed on accident from a rebase (doh)

PR in progress with https://github.com/brave/brave-core/pull/7030

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` on `Android 10` using `1.16.75 CR: 86.0.4240.193`

Ensured that websites listed under https://github.com/brave/brave-core/pull/7030#issue-514477459 didn't cause Brave to crash on both mobile & desktop versions:

* https://www.laredmaspoderosa.com - **`PASSED`** (both desktop/mobile versions of website)
https://www.ilt.edu - **`PASSED`** (both desktop/mobile versions of website)
https://www.hippie-chay.de - **`PASSED`** (both desktop/mobile versions of website)
https://www.wix.com/blog/2016/03/wix-websites-examples - **`PASSED`** (both desktop/mobile versions of website)
https://www.thegivingblock.com - **`PASSED`** (both desktop/mobile versions of website)
