### ISSUE TITLE
Enable RTCInsertable streams via origin policy

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10060]
## Description
together.brave.com will use E2E encryption. To enable this we need to enable RTCInsertable streams using origin trials.

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/5706

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5706

* Confirmed insertable streams are not supported with `1.11.97`:
<img width="745" alt="1 11 97" src="https://user-images.githubusercontent.com/28145373/87806227-868d3380-c824-11ea-824f-7f7d604f1bf7.png">

* Confirmed insertable streams are supported with `1.12.92`:
<img width="866" alt="1 12 92" src="https://user-images.githubusercontent.com/28145373/87806304-a9b7e300-c824-11ea-8ba2-36928fa0b44f.png">

* Confirmed `Crypto key` input box is disabled:
<img width="870" alt="Screen Shot 2020-07-17 at 11 57 54 AM" src="https://user-images.githubusercontent.com/28145373/87806384-cb18cf00-c824-11ea-80cf-f48d7b76faaa.png">

* Note, second site from test plan shows insertable streams as not supported, discussed with @jumde and confirmed this is expected based on configuration.
---------
