### ISSUE TITLE
Snap Package for Brave

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1007]
Initially implemented with https://github.com/brave/browser-laptop/issues/7140 (browser-laptop version 0.17.19). We currently maintain snaps for browser-laptop and should consider doing the same for brave-core

> - Did you search for similar issues before submitting this one?
> **Yes**
> 
> - Describe the issue you encountered:
> **Installing on Ubuntu, derivatives, and Linux in general could be much easier.**
> 
> - Platform (Win7, 8, 10? macOS? Linux distro?):
> **Ubuntu and Elementary (Linux)**
> 
> ### What are Snaps?
> Snap packaging was developed in order to make installation of software easier on Linux, and to make targeting the platform as a whole simpler for developers. Ubuntu is currently accepting Snap packages into its app store through their [developer portal](https://myapps.developer.ubuntu.com/dev/click-apps/). This would serve as an easier way for getting Brave on Ubuntu, and if snapd is installed on other distributions the installation is very straightforward as well.  *Snaps* is a nickname for a snap package.
> 
> ### How much work is it?
> Electron Builder now supports the generation of a snap package. This should make it much simpler to implement into the current process fairly easily. The options are detailed on the [Electron Builder wiki](https://github.com/electron-userland/electron-builder/wiki/Options#SnapOptions).
> 
> The Ubuntu community has been amazing about helping projects get their software packaged as snaps. If this is a target the Brave community is interested in hitting, then we can tap the Ubuntu folks for help and I'm sure they will gladly lend their aide.

**Comment by bsclifton** [comment]
@flexiondotorg we're trying to get this setup for brave-core. Would you be able to help answer questions?

**Comment by srirambv** [comment]
+1 for snap package on Manjaro via https://community.brave.com/t/weird-font-on-some-websites/36067/4

**Comment by Brave-Matt** [comment]
+1 from reddit

**Comment by Brave-Matt** [comment]
+1 from community:
https://community.brave.com/t/remove-brave-moun-from-ubuntu-software-center/39678

**Comment by posix4e** [comment]
Here's my new snap https://github.com/snapcrafters/brave/pull/21. I love our new snap as it has better isolation than the last one. In fact I'm running it on all of our machines. Just waiting for the snapcrafters to give it a shot. If you totally trust me, you can try my snap with

- Download https://drive.google.com/open?id=1UqtaFNLJ8B179NUG9K4xW3yaeKg7CnS4
- Then install the snap with --dangerous
- Then snap connect brave:browser-sandbox

**Comment by w0ts0n** [comment]
Just want to vouch for @posix4e, you can trust him.

**Comment by posix4e** [comment]
@w0ts0n at least if i hack them, @BrendanEich knows where I live and can send the OSS javascript goon squad

**Comment by bsclifton** [comment]
@posix4e is the snap integration at a point where it can be automated? I know it's behind a bit- would be great to get a refresh 😄

**Comment by SephReed** [comment]
Cursor size is still small. Not sure why this issue was closed (https://github.com/brave/browser-laptop/issues/9772)

**Comment by bsclifton** [comment]
@SephReed per the comment in the issue, `browser-laptop` is the old/deprecated version of Brave (the version based on Muon/electron). If you're still having an issue with the newer version of Brave, please create an issue and be sure to include your version details 😄

**Comment by srirambv** [comment]
+1 from @chemel9 via #7293

**Comment by srirambv** [comment]
@bsclifton @w0ts0n can we close this?

**Comment by w0ts0n** [comment]
yes
