### ISSUE TITLE
[Android] Super Referrer - QR Code

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#10079]
## Description 

Super Referrer (SR) uses an enhanced referrer tracking system. On iOS, we do this by directing users to a landing page and copying a referral code.

The SR link is slightly different to the normal referrer link.

The QR code on the SR custom home page uses the normal referrer link, we need to change this so that URL link for the QR code can be entered in the .json file.

Link: https://bravesoftware.slack.com/archives/CT7JC4KBM/p1591227697202100

iOS issue: https://github.com/brave/brave-ios/issues/2599

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.10.92.apk`
- Verified the test plan from https://github.com/brave/brave-core/pull/5741
- Verified that the URL `https://brave.com/r/OXB363` is sent to the user when code is shared via QR code menu from SR image
