### ISSUE TITLE
[Android] Fix USD balance in rewards panel

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#10072]
## Description 
USD balance always shows 0.0

## Steps to reproduce 

   1. add fund to the account
   2. notice that it shows 0.0 to usd balance
   3. 

## Actual result 
USD balance is always 0.0 in rewards panel
## Expected result
USD balance should show the correct value.

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.10.92 on Samsung Galaxy Tab S5e (Android 9.0)

From UGP grant:
![Screenshot_20200617-045820_Brave](https://user-images.githubusercontent.com/34715963/84850115-3b320a80-b057-11ea-9363-3bbf36c89f41.jpg)

From Verified wallet + UGP grant
![Screenshot_20200617-050825_Brave](https://user-images.githubusercontent.com/34715963/84850676-9dd7d600-b058-11ea-8b24-a527f4f57e89.jpg)
