### ISSUE TITLE
Update favicons for internal pages

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#10071]
## Description 

Follow-up to: https://github.com/brave/brave-browser/issues/8492.

Update favicons for:
- [x] brave://settings
- [x] brave://history
- [x] brave://downloads

## Steps to Reproduce

   1. Go to the internal pages above.
   2. Notice they're using chromium provided icons
   3. Expected result is that icons are Brave provided favicons

## Actual result:

<img width="616" alt="Screen Shot 2020-06-03 at 11 50 26 AM" src="https://user-images.githubusercontent.com/5951041/83677056-754bd880-a590-11ea-8460-333f16e9f288.png">

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by rebron** [comment]
cc: @simonhong

**Comment by karenkliu** [comment]
@simonhong The icons in Figma are all 24x24. Let me know if you need these in a different size or color.

Settings: https://www.figma.com/file/xWGBM3qWbu3RLuZqZGwynk/Icons?node-id=124%3A10694

![image](https://user-images.githubusercontent.com/2388823/83678104-0bccc980-a592-11ea-9faf-e85a628b58ca.png)

History: https://www.figma.com/file/xWGBM3qWbu3RLuZqZGwynk/Icons?node-id=124%3A10694

![image](https://user-images.githubusercontent.com/2388823/83678167-2606a780-a592-11ea-8443-e46fd1782bd5.png)

Downloads: https://www.figma.com/file/xWGBM3qWbu3RLuZqZGwynk/Icons?node-id=124%3A10694

![image](https://user-images.githubusercontent.com/2388823/83678251-50f0fb80-a592-11ea-9ea8-1efc8f81daa8.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.11.65 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS Version 1903 (Build 18362.30)

```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/84761076-8b24b900-afe6-11ea-8802-2cb93016581a.png)
