### ISSUE TITLE
DuckDuckGo Onion search for Tor private tab

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1008]
Carried over from https://github.com/brave/browser-laptop/issues/14601
> Instead of using https://duckduckgo.com for Private Tab with Tor, use their onion site: https://3g2upl4pq6kufc4m.onion for searching

**Comment by riastradh-brave** [comment]
We talked to DuckDuckGo, and they asked that we continue to use https://duckduckgo.com for now.  We'll consider this again in the future if their preference changes.

**Comment by aelisya** [comment]
Can't you at least let a way to the user to add it manualy in the config ? (so like that you follow their demand but you let to final choice to the user)

**Comment by eljuno** [comment]
+1s from Community https://community.brave.com/t/use-onion-address-for-duckduckgo-in-tor-window/93908?u=eljuno

**Comment by thespencertupis** [comment]
@riastradh-brave What is the reasoning behind DDG asking that Brave _not_ use the onion site?

**Comment by aelisya** [comment]
@thespencertupis maybe the server who serve the onion's one isn't powerfull enought for accept many user.

**Comment by ron-wolf** [comment]
@riastradh-brave What’s their stated reason? Is this even still their desire 8 months later? Is there some way to check again?

**Comment by ron-wolf** [comment]
Also, what happened to issue #1513 and PR brave/brave-core#635? These both seem to concern what @aelisya suggested, and yet I can’t use the functionality they aimed to implement.

**Comment by PeterDaveHello** [comment]
Similar issue on the Tor Browser project:
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/21483

BTW: Onion v2 is deprecated (https://blog.torproject.org/v2-deprecation-timeline)

DuckDuckGo now has a v3 url: https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/16955

Thanks for the heads up on the v3 url, @PeterDaveHello 😄
