### ISSUE TITLE
Implement P2A component for private ad analytics

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#10081]
Ticket includes:

1. Implement a brave component analogous to P3A to enable private ad analytics
2. Implement dummy question related to ad-confirmations to sanity check reports

Spec:
- https://docs.google.com/document/d/16rNfzPnrdxOghzfnquNVd-YTs8XyWFLn9hEW9s879wM/edit#heading=h.5qffchro4oq9

Related PRs:
- devops resources: https://github.com/brave/devops/pull/3144

**Comment by GeetaSarvadnya** [comment]
QA Blocked - until the issue https://github.com/brave/brave-browser/issues/11552 is fixed

**Comment by GeetaSarvadnya** [comment]
Removed QA blocked based on https://github.com/brave/brave-browser/issues/11552#issuecomment-685837024. 

The issue can be tested now as the test plan is precise.

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.14.72 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/5949
- Encountered https://github.com/brave/brave-browser/issues/11552

Verified P2A log for `Brave.P2A.ViewConfirmationCount`
```
[3016:9744:0902/232423.349:VERBOSE2:brave_p3a_service.cc(373)] BraveP3AService::OnHistogramChanged: histogram_name = Brave.P2A.ViewConfirmationCount Sample = 2147483646 bucket = 2147483646
```
