### ISSUE TITLE
P3A - Incorrect response values for Auto-contribute

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10088]
## Description 

P3A - Incorrect response values for Auto-contribute

(Brave.Rewards.AutoContributionsState.2)

0. No wallet created
1. Rewards Disabled
2. Wallet created, Auto-Contribute off
3. Auto-contribute enabled, no contribution so far
4. Auto-contribute enabled, one successful contribution so far
5. Auto-contribute enabled, more than one successful contribution so far

## Steps to Reproduce

      1. Clean profile 1.10.x launch using `brave.exe --rewards=staging=true,reconcile-interval=3`
      2. Enable rewards
      3. Claim UGP grant
      4. Open local-state file and look for "Brave.Rewards.AutoContributionsState.2"
      5. `Brave.Rewards.AutoContributionsState.2` is set to `3`  (`Auto-contribute enabled, no contribution so far`) as expected
      6. Wait for 1st auto contribution
      7. After AC, `Brave.Rewards.AutoContributionsState.2` is set to `3` (`Auto-contribute enabled, no contribution so far`) instead of `4` (`Auto-contribute enabled, one successful contribution so far`)
      8. Trigger 2nd auto contribution
      9. After AC, `Brave.Rewards.AutoContributionsState.2` is set to `3` (`Auto-contribute enabled, no contribution so far`) instead of `5` (`Auto-contribute enabled, more than one successful contribution so far`)

**Note:** The issue started appearing after 1.5.x

## Actual result:

P3A - Incorrect response values for Auto-contribute

## Expected result:
correct response values should be displayed for Auto-contribute in Brave Rewards

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.10.84 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes in 1.9.x, 1.8.x, 1.7.x. Not in `1.5.123`
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mattmcalister @bsclifton @rebron @iefremov

**Comment by rebron** [comment]
cc: @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
This issue is arising in Android also, Verified in the nightly build `1.20.74`

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.25.19 Chromium: 90.0.4430.72 (Official Build) nightly (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1.  Clean profile 1.10.x launch using `brave.exe --rewards=staging=true,reconcile-interval=3`
2. Enabled rewards
3. Claimed UGP grant
4. Opened `brave://local-state` and looked for "Brave.Rewards.AutoContributionsState.2"
5. Confirmed `Brave.Rewards.AutoContributionsState.2` is set to `3`  (`Auto-contribute enabled, no contribution so far`) as expected
6. Waited for 1st auto contribution
7. After AC, verified `Brave.Rewards.AutoContributionsState.2` was correctly now set to `4` (`Auto-contribute enabled, one successful contribution so far`)
8. Triggered 2nd auto contribution
9. After AC, confirmed `Brave.Rewards.AutoContributionsState.2` was set to `5` (`Auto-contribute enabled, more than one successful contribution so far`)

example | example | example | example | example | example
---------|---------|----------|---------|----------|---------
<img width="1407" alt="Screen Shot 2021-04-15 at 5 31 27 PM" src="https://user-images.githubusercontent.com/387249/114956116-104d4a00-9e13-11eb-886e-3b0990af2f78.png"> | <img width="1312" alt="Screen Shot 2021-04-15 at 5 53 33 PM" src="https://user-images.githubusercontent.com/387249/114956360-923d7300-9e13-11eb-8a98-7df0e63da158.png"> | <img width="1770" alt="Screen Shot 2021-04-15 at 5 34 16 PM" src="https://user-images.githubusercontent.com/387249/114956119-117e7700-9e13-11eb-8588-239d1962775f.png"> | <img width="1770" alt="Screen Shot 2021-04-15 at 5 34 25 PM" src="https://user-images.githubusercontent.com/387249/114956123-13e0d100-9e13-11eb-8a47-0dd79060080d.png"> | <img width="1770" alt="Screen Shot 2021-04-15 at 5 34 41 PM" src="https://user-images.githubusercontent.com/387249/114956129-16432b00-9e13-11eb-9ecf-453072dca364.png"> | <img width="1770" alt="Screen Shot 2021-04-15 at 5 35 51 PM" src="https://user-images.githubusercontent.com/387249/114956135-193e1b80-9e13-11eb-880d-872d9431d884.png">
