### ISSUE TITLE
Withdraw Funds Not Working

### ISSUE THREAD

**Issue by ByteHackr** [brave/brave-browser#10098]
## Steps to Reproduce

   1. Withdraw Funds leads to a false Uphold Page.

## Actual result:
 a false Uphold Page

## Expected result:
 a  Uphold Page with earned BAT added automatically. 

## Version/Channel Information:
 Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@ByteHackr Withdraw funds link is just a link to uphold, it will not trigger any action. When you say false uphold page, what do you mean? Can you send me the link to which you are redirected?

**Comment by ByteHackr** [comment]
yes, its redirect to 
https://uphold.com/dashboard/cards/a61153b9-276f-4a52-97d0-51e041f89238/use
![image](https://user-images.githubusercontent.com/30409831/83839039-7d368480-a718-11ea-9bdb-27971baecce9.png)

**Comment by NejcZdovc** [comment]
this url is correct

**Comment by ByteHackr** [comment]
But, earned BAT not autometically added. or noty even added manually.

**Comment by NejcZdovc** [comment]
@ByteHackr is your uphold account KYC'd? Clicking on withdraw link just opens uphold page it will not trigger transfer, this is done automatically if you have KYC uphold account added to rewards

**Comment by ByteHackr** [comment]
I use upholdsfrom last 6 months and also Withdraw BAT from last 4 months.

**Comment by ByteHackr** [comment]
![image](https://user-images.githubusercontent.com/30409831/83844068-ebcd0f80-a723-11ea-8032-58fab5e9bd65.png)

**Comment by eljuno** [comment]
The BAT should be reflected in `Brave Browser` card and user need to manually transfer it to different card to "withdrawal" it from Brave Rewards wallet.

But the issue is, BAT shown under `brave:rewards` is not reflected under `Brave Browser` card in Uphold.

It seems like that one is the "issue".

**Comment by ByteHackr** [comment]
Yes. you right.

**Comment by HTransistor** [comment]
Withdrawing BATs from Brave Browser to Brave Card in Uphold is not working for 6 months.
Here are like 50 users with the same problem:
https://community.brave.com/t/cannot-withdraw-bat/104324

They discribe the issue multiple times, probably it can help you to fix it.
