### ISSUE TITLE
Ads rewards are not refreshed after claiming an ad grant

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#10094]
## Description 

Ads rewards are not refreshed after claiming an ads grant. Ads rewards are updating if user restarts browser or after ~24 hours when cashing out tokens

## Steps to Reproduce

   1. Claim an ad grant

## Actual result:

Estimated pending rewards are not refreshed until the user restarts the browser or tokens are cashed-in ~24 hours.

## Expected result:
Estimated pending rewards should be refreshed

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed using `macOS 10.14.6 x64 Mojave`

```
Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description
* Confirmed logs got 2xx's as expected
```
[8446:775:0810/134429.870586:VERBOSE1:ads_rewards.cc(117)] OnGetPaymentBalance
[8446:775:0810/134429.870660:VERBOSE6:ads_rewards.cc(119)] URL Response:
  URL: https://ads-serve.bravesoftware.com/v1/confirmation/payment/6b46cb43-3b15-4dd1-a0d3-d4f42cae9b95
  Response Status Code: 200
```

```
[8446:775:0810/134429.985145:VERBOSE1:ads_rewards.cc(152)] OnGetAdGrants
[8446:775:0810/134429.985224:VERBOSE6:ads_rewards.cc(154)] URL Response:
  URL: https://grant.rewards.bravesoftware.com/v1/promotions/ads/grants/summary?paymentId=6b46cb43-3b15-4dd1-a0d3-d4f42cae9b95
  Response Status Code: 200
```

* Confirmed UI displayed as expected after claiming Ad grant:
<img width="1192" alt="Screen Shot 2020-08-10 at 1 45 38 PM" src="https://user-images.githubusercontent.com/28145373/89814140-b2909180-db10-11ea-99e7-d8ea550829e3.png">

----------

Verified passed using 

```
Brave	1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
Revision	a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS	Linux
```

* Verified STR from description
* Confirmed logs got 2xx's as expected
```
[4648:4648:0810/104046.668781:VERBOSE1:ads_rewards.cc(117)] OnGetPaymentBalance
[4648:4648:0810/104046.668813:VERBOSE6:ads_rewards.cc(119)] URL Response:
  URL: https://ads-serve.bravesoftware.com/v1/confirmation/payment/cf972932-452b-428c-9005-38ac279d463c
  Response Status Code: 200
```

```
[4648:4648:0810/104046.781206:VERBOSE1:ads_rewards.cc(152)] OnGetAdGrants
[4648:4648:0810/104046.781238:VERBOSE6:ads_rewards.cc(154)] URL Response:
  URL: https://grant.rewards.bravesoftware.com/v1/promotions/ads/grants/summary?paymentId=cf972932-452b-428c-9005-38ac279d463c
  Response Status Code: 200
  Body: {"amount":"20","earnings":"20","lastClaim":"2020-08-10T17:35:22.480147Z","type":"ads"}
```

* Confirmed UI displayed as expected after claiming Ad grant:
<img width="1203" alt="Screen Shot 2020-08-10 at 1 46 14 PM" src="https://user-images.githubusercontent.com/28145373/89814224-ce943300-db10-11ea-8e9d-07e5d8045313.png">

--------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.113 x64 build

- Verified steps from issue description
- Verified logs got 2xx's as expected
  - **`OnGetPaymentBalance`**
![image](https://user-images.githubusercontent.com/17010094/90155350-1f12c700-dd83-11ea-8e12-803f59a3ae4a.png)

  - **`OnGetAdGrants`**
![image](https://user-images.githubusercontent.com/17010094/90155414-2f2aa680-dd83-11ea-8307-3856df2bbd64.png)
- Verified UI shows ad grant notification 
![image](https://user-images.githubusercontent.com/17010094/90155487-48cbee00-dd83-11ea-97e9-f30eebd783c4.png)
