### ISSUE TITLE
Keep ads state when disabling Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#10097]
Keep ads state when disabling Brave Ads. Users will be able to reset ads state as part of https://github.com/brave/brave-browser/issues/10064

**Comment by GeetaSarvadnya** [comment]
Reset ads can be tested only when the issue is resolved https://github.com/brave/brave-browser/issues/10934

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5749
* Confirmed toggling Ads off does not remove ads_service folder.
* Confirmed toggling Rewards off does not remove ads_service folder.
* Confirmed reset of Rewards removes the ads_service folder.

-----------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build
- Verified viewing an ad, then toggling ads off and then back on doesn't rest  `Estimated pending rewards` and `Ad notifications received` to zero
---------
Verification passed on Samsung Tab A with Android 10 running 1.12.112 x64 build
- Verified viewing an ad, then toggling ads off and then back on doesn't rest  `Estimated pending rewards` and `Ad notifications received` to zero
