### ISSUE TITLE
Ads are not blocked in Youtube

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#10108]
## Description 

- Video ads are not blocked in Youtube 

## Steps to Reproduce

   1.  Open some videos that contains ads
example site: `https://www.youtube.com/watch?v=wq_X6_mIXHI`

 
   2. Ads remains even if the Shield is enabled
   3. 

## Actual result:

- Ads appear

## Expected result:
- No video ads in Youtube

## Reproduces how often: 

- Not reproduced on my device but got several reports on Twitter.

## Brave version (brave://version info)

User 1
- Windows10 Pro 64bit version 1909 OS build 18363.836
- Brave 1.9.76 Chromium: 81.0.4044.138(official Build) 64bit

User 2 
- macOS Mojave 10.14.6 
- Brave 1.9.76 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
We've had a few youtube ad reports on reddit/forums, some clearing cookies/cache fixes, others didn't. @antonok-edm  do we support, troubleshooting youtube ad issues via twitter.

https://twitter.com/Kargasht/status/1271053665470578690

@antonok-edm  do we support the json uBO snippet?

**Comment by antonok-edm** [comment]
@ryanbr `+js(json-prune, ...)` should be fully supported by brave/brave-core#5402 which is in Brave Stable as of 1.9.72. Should be working for those reported versions.

**Comment by ryanbr** [comment]
With the latest Brave build `Version 1.10.95` @chkk525  can you check youtube ads is now fixed?
