### ISSUE TITLE
[Android] Incognito tab is shown for non en-US languages

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10105]
## Description 
Incognito tab is shown for non en-US languages

## Steps to reproduce 

   1. Set device language to non en-US
   2. Open settings 
   3. Search engine shows `Incognito` instead of `Private`

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/83871116-15e6f780-a74d-11ea-892f-5a523d1abc9b.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/83871156-2f883f00-a74d-11ea-9917-756a44c5aa66.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet):Phone
   - Android version: 10
   
## Brave version
1.9.79

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
+1 from @fmarier via #15951

**Comment by samartnik** [comment]
Problem was with older translation that we had in Transifex. Old translations are removed and we are just waiting for the new translations. Thank you @mkarolin for the help!

**Comment by samartnik** [comment]
New translations are already applied

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.31.67 x64 beta build
- Verified setting locale to en-UK shows as Private tab

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/135991309-40bd3941-1a55-4095-bb72-8cb0b6433319.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/135991284-0941d68d-49df-4511-836a-fa2e173e566b.png>
