### ISSUE TITLE
[Android] Search keywords not working

### ISSUE THREAD

**Issue by georapbox** [brave/brave-browser#10110]
## Description 
In Settings > Search engine > Standard Tab there are keywords under each search engine. I guess these are selecting a search engine on the fly in a similar way the desktop browser behaves. If I use any of those, they don't seem to work though.

![Screenshot (Jun 5, 2020 17_56_01)](https://user-images.githubusercontent.com/6596039/83893171-497b4f00-a758-11ea-88f5-54a82bc70173.png)

## Steps to reproduce 

   1. Type `:sp <YOUR_SEARCH_QUERY_HERE>` in the address bar.
   2. Tap the "Enter" button

## Actual result 
It will perform the search with my default search engine (DuckDuckGo in my case).

![Jun-05-2020 18-20-01](https://user-images.githubusercontent.com/6596039/83893916-459bfc80-a759-11ea-9b13-95f164284f68.gif)

## Expected result
Expected to override my default search engine and perform the search with the StartPage search engine.

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version
   - Beta build

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone Motorola One (XT1941-4)
   - Android version: 10
   
## Brave version
Brave 1.9.79

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
  Not related to Brave Shields
- Does the issue resolve itself when disabling Brave Rewards?
  Not related to Brave Rewards
- Is the issue reproducible on the latest version of Chrome?
  Chrome on Android does not have similar feature  

### Additional information

Is it something that I might be doing wrong on my end?

**Comment by srirambv** [comment]
Don't think that ever worked on Android-Core.

**Comment by srirambv** [comment]
Closing in favour of #11495 as we are removing the keywords
