### ISSUE TITLE
Extension not reviewed for security and safety warning message is not displayed while adding extensions

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10113]
## Description 

Extension not reviewed for security and safety warning message is not displayed while adding extensions (ABP/Google translate/dark reader) in 1.10.x - warning message is shown for the same extensions in released version 1.9.x
## Steps to Reproduce

   1. Clean profile 1.10.86 Chromium: 83.0.4103.61
   2. Open CWS
   3. Try to add extensions (ABP/Google translate/dark reader)
   

## Actual result:

Extension not reviewed for security and safety warning message is not displayed while adding extensions (ABP/Google translate/dark reader) in 1.10.x

**1.10.86**
![image](https://user-images.githubusercontent.com/38657976/83909993-709d4500-a787-11ea-9e02-df53a0214dcd.png)
![image](https://user-images.githubusercontent.com/38657976/83910039-814dbb00-a787-11ea-9b8d-947bb890cdf3.png)
![image](https://user-images.githubusercontent.com/38657976/83910135-a3dfd400-a787-11ea-8e0a-db5bd314c3c8.png)

**1.9.x**
![image](https://user-images.githubusercontent.com/38657976/83910180-b65a0d80-a787-11ea-830c-d54babd72db2.png)
![image](https://user-images.githubusercontent.com/38657976/83910210-c671ed00-a787-11ea-9241-927681f272eb.png)
![image](https://user-images.githubusercontent.com/38657976/83910240-d689cc80-a787-11ea-9822-efe5fa84275b.png)

## Expected result:
Extension warning message should be displayed for ABP/Google translate/dark reader

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.5 (Build 19F101)
```

* ensured that clicking on `Add extension` on the modal warning users that the extension wasn't vetted by Brave installs the extension without any issues
   * ensured that clicking on `Cancel` works as expected as well

**`Extension modal for none vetted extensions`**

<img width="514" alt="Screen Shot 2020-06-10 at 10 56 09 PM" src="https://user-images.githubusercontent.com/2602313/84340087-de71b400-ab6d-11ea-8dc2-244475e84bd3.png">

<img width="619" alt="Screen Shot 2020-06-10 at 10 55 38 PM" src="https://user-images.githubusercontent.com/2602313/84340115-ee899380-ab6d-11ea-8df8-f4fa9cb41ee0.png">

**`Extension modal for vetted extensions`**

<img width="631" alt="Screen Shot 2020-06-10 at 10 59 31 PM" src="https://user-images.githubusercontent.com/2602313/84340169-0fea7f80-ab6e-11ea-856b-3d542f88deb8.png">
