### ISSUE TITLE
Affiliate ID being suggested in auto-complete for specific sites

### ISSUE THREAD

**Issue by SaschaWebDev** [brave/brave-browser#10129]
Please change brave-core\components\omnibox\browser\suggested_sites_provider_data.cc
into the following to stop making gullible people pay into the pockets of individual bad actors on this project.

/* Copyright (c) 2020 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "brave/components/omnibox/browser/suggested_sites_provider.h"

#include "base/strings/utf_string_conversions.h"

const std::vector<SuggestedSitesMatch>&
SuggestedSitesProvider::GetSuggestedSites() {
  static const std::vector<SuggestedSitesMatch> suggested_sites = {
  {
    SuggestedSitesMatch(
      "binance.com",
      GURL("https://www.binance.com?ref=AffiliateEaterID"),
      GURL("https://www.binance.com"),
      base::ASCIIToUTF16("binance.com?ref=AffiliateEaterID"),
      true)
  }, {
    SuggestedSitesMatch(
      "bitcoin",
      GURL("https://www.binance.com/en/buy-sell-crypto"
           "?fiat=USD&crypto=BTC&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.com/en/buy-sell-crypto?crypto=BTC"),
      base::ASCIIToUTF16("binance.com/en/buy-sell-crypto?crypto=BTC&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "btc",
      GURL("https://www.binance.com/en/buy-sell-crypto"
           "?fiat=USD&crypto=BTC&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.com/en/buy-sell-crypto?crypto=BTC"),
      base::ASCIIToUTF16("binance.com/en/buy-sell-crypto?crypto=BTC&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "ethereum",
      GURL("https://www.binance.com/en/buy-sell-crypto"
           "?fiat=USD&crypto=ETH&ref=AffiliateEaterID6&utm_source=brave"),
      GURL("https://www.binance.com/en/buy-sell-crypto?crypto=ETH"),
      base::ASCIIToUTF16("binance.com/en/buy-sell-crypto?crypto=ETH&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "eth",
      GURL("https://www.binance.com/en/buy-sell-crypto"
           "?fiat=USD&crypto=ETH&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.com/en/buy-sell-crypto?crypto=ETH"),
      base::ASCIIToUTF16("binance.com/en/buy-sell-crypto?crypto=ETH&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "litecoin",
      GURL("https://www.binance.com/en/buy-sell-crypto"
           "?fiat=USD&crypto=LTC&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.com/en/buy-sell-crypto?crypto=LTC"),
      base::ASCIIToUTF16("binance.com/en/buy-sell-crypto?crypto=LTC&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "ltc",
      GURL("https://www.binance.com/en/buy-sell-crypto"
           "?fiat=USD&crypto=LTC&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.com/en/buy-sell-crypto?crypto=LTC"),
      base::ASCIIToUTF16("binance.com/en/buy-sell-crypto?crypto=LTC&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "bnb",
      GURL("https://www.binance.com/en/buy-sell-crypto"
           "?fiat=USD&crypto=BNB&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.com/en/buy-sell-crypto?crypto=BNB"),
      base::ASCIIToUTF16("binance.com/en/buy-sell-crypto?crypto=BNB&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "binance.us",
      GURL("https://www.binance.us?ref=AffiliateEaterID"),
      GURL("https://www.binance.us"),
      base::ASCIIToUTF16("binance.us?ref=AffiliateEaterID"),
      true)
  }, {
    SuggestedSitesMatch(
      "bitcoin",
      GURL("https://www.binance.us/en/buy-sell-crypto"
           "?fiat=USD&crypto=BTC&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.us/en/buy-sell-crypto?crypto=BTC"),
      base::ASCIIToUTF16("binance.us/en/buy-sell-crypto?crypto=BTC&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "btc",
      GURL("https://www.binance.us/en/buy-sell-crypto"
           "?fiat=USD&crypto=BTC&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.us/en/buy-sell-crypto?crypto=BTC"),
      base::ASCIIToUTF16("binance.us/en/buy-sell-crypto?crypto=BTC&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
     "ethereum",
      GURL("https://www.binance.us/en/buy-sell-crypto"
           "?fiat=USD&crypto=ETH&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.us/en/buy-sell-crypto?crypto=ETH"),
      base::ASCIIToUTF16("binance.us/en/buy-sell-crypto?crypto=ETH&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "eth",
      GURL("https://www.binance.us/en/buy-sell-crypto"
           "?fiat=USD&crypto=ETH&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.us/en/buy-sell-crypto?crypto=ETH"),
      base::ASCIIToUTF16("binance.us/en/buy-sell-crypto?crypto=ETH&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "bnb",
      GURL("https://www.binance.us/en/buy-sell-crypto"
           "?fiat=USD&crypto=BNB&ref=AffiliateEaterID&utm_source=brave"),
      GURL("https://www.binance.us/en/buy-sell-crypto?crypto=BNB"),
      base::ASCIIToUTF16("binance.us/en/buy-sell-crypto?crypto=BNB&ref=AffiliateEaterID"),  // NOLINT
      false)
  }, {
    SuggestedSitesMatch(
      "coinbase.com/join",
      GURL("https://www.coinbase.com/join/AffiliateEaterID"),
      GURL("https://www.coinbase.com/join"),
      base::ASCIIToUTF16("coinbase.com/join/AffiliateEaterID"),
      true)
  }, {
    SuggestedSitesMatch(
      "ledger.com/pages/ledger-nano-x",
      GURL("https://shop.ledger.com/pages/ledger-nano-x?r=AffiliateEaterID"),
      GURL("https://shop.ledger.com/pages/ledger-nano-x"),
      base::ASCIIToUTF16("shop.ledger.com/pages/ledger-nano-x?r=AffiliateEaterID"),
      true)
  }, {
    SuggestedSitesMatch(
      "trezor.io/product/trezor-one-metallic",
      GURL("https://shop.trezor.io/product/trezor-one-metallic"
           "?offer_id=24&aff_id=AffiliateEaterID"),
      GURL("https://shop.trezor.io/product/trezor-one-metallic"),
      base::ASCIIToUTF16("shop.trezor.io/product/trezor-one-metallic"
                         "?offer_id=24&aff_id=AffiliateEaterID"),
      true)
  },
  };

  return suggested_sites;
}

**Comment by irissoftworks** [comment]
Tbh I see nothing wrong with these suggestions personally.

Having said that, why not add a "suggested" or "promoted" label for the suggested ref links and allow users to decide if they want to support brave in this fashion.

Also would be interesting to see some of the value gained from this to reflect on BAT. If that becomes the case I think brave users can only benefit from this and it's only fair.

**Comment by joshxyzhimself** [comment]
https://news.ycombinator.com/item?id=23442027

**Comment by joshxyzhimself** [comment]
https://news.ycombinator.com/item?id=23442027

**Comment by SaschaWebDev** [comment]
> Tbh I see nothing wrong with these suggestions personally.
> 
> Having said that, why not add a "suggested" or "promoted" label for the suggested ref links and allow users to decide if they want to support brave in this fashion.
> 
> Also would be interesting to see some of the value gained from this to reflect on BAT. If that is that case I think brave users can only benefit from this and it's only fair.

Brendan Eich himself see very much wrong with them, said multiple times he takes all the blame and the project is going to get rid of them.

https://twitter.com/BrendanEich/status/1269324204844806145?s=20

**Comment by bsclifton** [comment]
Change is now disabled in source via:
https://github.com/brave/brave-core/pull/5761

For those reading, this functionality is behind a flag which you can disable:
![image](https://user-images.githubusercontent.com/4733304/83965222-e1fff500-a866-11ea-8d08-6e44d69545c0.png)

With the fix linked above, the `Show Brave suggested sites in autocomplete suggestions` setting will be defaulted to false. **Existing users that haven't modified the setting will have it turned off with our next release (planned for Thurs June 11)**. We're also considering a hotfix that would be released before that

I've started a Nightly build and we'll also have this fix uplifted to Beta soon (with a build following the merge there)

**Comment by irissoftworks** [comment]
> > Tbh I see nothing wrong with these suggestions personally.
> > Having said that, why not add a "suggested" or "promoted" label for the suggested ref links and allow users to decide if they want to support brave in this fashion.
> > Also would be interesting to see some of the value gained from this to reflect on BAT. If that is that case I think brave users can only benefit from this and it's only fair.
> 
> Brendan Eich himself sees very much wrong with them, said multiple times he takes all the blame and the project is going to get rid of them.
> 
> https://twitter.com/BrendanEich/status/1269324204844806145?s=20

No, he didn't say it was wrong. He and other brave employees said they were going to remove it and it was a [PR] mistake. The feature itself is innocuous and not really hurting anyone. 

In other words it was removed because cry babies, and removed because of general outcry of offended ladies.

**Comment by PrincessAkira** [comment]
I would still like to have these refs because i like the browser.
Is there a way for me, to opt-in to them?

**Comment by bsclifton** [comment]
> I would still like to have these refs because i like the browser.
> Is there a way for me, to opt-in to them?

Yes - when a new build comes out, you can toggle the `Show Brave suggested sites in autocomplete suggestions` flag on the Settings page, under `Appearance`

**Comment by bbondy** [comment]
https://github.com/brave/brave-core/commit/e8fdde70a3ac2c25e6ccc567bc93c6d4059c2d72#commitcomment-39735905

**Comment by r3pek** [comment]
@bsclifton is there a brave/chrome policy that can be changed to manage this centrally?

**Comment by bsclifton** [comment]
@r3pek no - there isn't one yet. But we do have an issue to add Brave specific settings captured here:
https://github.com/brave/brave-browser/issues/9458

**Comment by bsclifton** [comment]
The fix for this rolled out today on Release channel (1.9.80) and we're deploying Android soon too. 

We've put together a post about this which you all can read here:
https://brave.com/referral-codes-in-suggested-sites/

**Comment by blackcrack** [comment]
@bsclifton :+1:
