### ISSUE TITLE
Endless tab loading after some time

### ISSUE THREAD

**Issue by TheNoim** [brave/brave-browser#10128]
## Description 

After some time working with brave, new tabs are loading forever for a few minutes. The background is just grey and no new page is loading. 

Internet is just fine. Just the browser hangs and does nothing. It takes a few minutes and then it works again. However, just after a few seconds/minutes later the issue reappears until I restart the whole system. Force quitting does not fix the issue. 

Interesting fact: Tabs which are already open just work fine. You also can navigate in tabs which are opened before the issue starts to appear. 

## Steps to Reproduce

   1. Wait few minutes (20-30 minutes)
   2. Open new tab 
   3. Try to navigate a page

## Actual result:

Endless loading. This also affects local brave pages like brave://version. 

![Internet page](https://i.imgur.com/e18Uc6B.png)
![Local page](https://i.imgur.com/M3qZhdQ.png)

## Expected result:

No endless hanging?

## Reproduces how often: 

Difficult to reproduce. 

## Brave version (brave://version info)

Brave	1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	macOS Version 10.15.5 (Build 19F101)
JavaScript	V8 8.1.307.32
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,NotificationTriggers,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality --flag-switches-begin --load-media-router-component-extension=1 --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps,BraveSync,CastAllowAllIPs,CastMediaRouteProvider,MirroringService,NewEncodeCpuLoadEstimator --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/nilsbergmann/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Have not tried
- Can you reproduce this issue with the nightly channel? Have not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:

I think, but I am not really sure, the issue started to appear after installing the supplement update of macos. I already removed all brave data to start with a fresh installation. 
I tried to start brave with logging. However, there was nothing which would indicate a fatal error.

**Comment by bsclifton** [comment]
@TheNoim something you might try-
if this happens, you can do cmd + option + i to open the dev tools. It's possible there are errors being logged to the JavaScript console- I'd be curious to know about that.

Just to confirm: this is happening after a while of using the browser... specifically when you are opening new tabs?

**Comment by rebron** [comment]
@TheNoim Can you update to our latest 1.11.x and let us know if you're still running into this issue? Also, if you can provide specific pages where you might be running into this problem, that would be good as well.

**Comment by TheNoim** [comment]
I think I will close the issue for now. It is hard to provide more info. I think it has something to do with an unstable connection, but now it got even harder for me to reproduce again. If this gets more frequent, I will reopen it with more information. Thanks anyway.

**Comment by bsclifton** [comment]
@TheNoim thanks for following up - please do let us know

**Comment by twentysixhugs** [comment]
I experience the same issue. I checked the developer tools. There's nothing in browser console, and there's nothing in Network tab either. I'm running [Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)](https://brave.com/latest/) on Ubuntu 20.04

**Comment by tatsujb** [comment]
I have the same issue as well. nothing in the browser console.

Sometimes it does open but takes 5 minutes to do so. the tab that does this is the one that was last active before closing brave. upon resuming from where you left off that tab will not load. the rest will. 

also on ubuntu (24.04)
