### ISSUE TITLE
No link to extension store from 'chrome://extensions/'

### ISSUE THREAD

**Issue by JohnstonCode** [brave/brave-browser#1012]
## Description 

When you go to the extension page there should be a link somewhere to take you to the store. Even if it is the chrome store for the time being.

## Steps to Reproduce

   1. go to 'chrome://extensions/'
   2. No link exists to the extension store

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Version 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

**Comment by iamVP7** [comment]
@JohnstonCode   are you able to see this text **Find extensions and themes in the Brave Web Store**
I recently filed an issue related to this #1001

**Comment by JohnstonCode** [comment]
@iamVP7 You only get that when you have no extensions installed. After you install one it is no longer present.

**Comment by JohnstonCode** [comment]
Chrome and chromium bot have a link in the bottom of the left-hand slide out menu

**Comment by franco27** [comment]
in "More Tools"

**Comment by kelna** [comment]
> Chrome and chromium both have a link in the bottom of the left-hand slide out menu

But not Brave.

**Comment by lukemulks** [comment]
+1 
When I'm in `brave://extensions/` I would really like to be able click a button to navigate directly to the extension store. 

If other browsers aren't doing this, it would be another reason to choose Brave.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/once-an-extension-is-installed-the-link-to-the-chrome-extension-store-disappears/40518?u=eljuno

Related to https://github.com/brave/brave-browser/issues/2497#issuecomment-446706353 ?

**Comment by oaustegard** [comment]
+1
As can be seen in the markup, the only reference to the webstore is inside a div visible only if no items are present: https://ibb.co/XVsTcsG

**Comment by 2635599** [comment]
have no idea why you guys would remove the link to the web store.

**Comment by mkarolin** [comment]
Resolved by #2497
