### ISSUE TITLE
Request for Improvement: Keyboard shortcut to enable/disable javascript

### ISSUE THREAD

**Issue by astrometrics** [brave/brave-browser#10123]
Hi, thanks for Brave, until now it's been a good experience, with most of what I have wanted and to the point.
Newbie in this project.
I'd like to request adding a keyboard shortcut to enable/disable javascript. Also it would be helpful if the javascript status could be clearly seen somewhere in the toolbar or etc, without needing to click anything.
Why: Probably Javascript is the most important security concern, and I believe it should be used disabled most of the time. For a desktop in windows, linux there's enough space to add visible statuses and it would make sense to have keyboard shortcuts.

thanks

**Comment by pdfrod** [comment]
Having a way to quickly disable/enable JavaScript would be very handy for me too.

I do web development and often I want to check how the page looks like when JavaScript is not enabled. Having to manually go to the settings page to disable it is painful and slow.

**Comment by mmmaxwwwell** [comment]
I would like to see this become a priority. People with motor accessibility issues would really appreciate being able to browse with JavaScript disabled by default, and with the current state of brave, that isn't possible.

**Comment by esthor** [comment]
This extension comes with a keyboard shortcut to do it: https://chrome.google.com/webstore/detail/quick-javascript-switcher/geddoclleiomckbhadiaipdggiiccfje
(And also +1 to this feature request; I'd like to also see it be part of Brave by default)

**Comment by fallaciousreasoning** [comment]
I'm closing this because as of https://github.com/brave/brave-core/pull/18526 if you enable brave://flags/#brave-commands you can add your own shortcut for this at brave://settings/system/shortcuts (search for shields). **Note:** this only disables/enables JS on the current page.

Right now, I don't think we're going to add a default shortcut for this.

cc @rebron
