### ISSUE TITLE
Unable to play Netflix videos due to missing Wildvine module

### ISSUE THREAD

**Issue by Geordon** [brave/brave-browser#10122]
## Description 

Unable to use Brave to play Netflix videos due to no Wildvine Content Decryption Module

## Steps to Reproduce

   1. Log into Netflix from Brave browser
   2.  Attempt to watch any video
   3. Get shown attached error message

## Actual result:

<img width="1440" alt="Screen Shot 2020-06-05 at 8 10 20 PM" src="https://user-images.githubusercontent.com/5634184/83932651-a2071800-a769-11ea-9c8c-2dab74ec82cb.png">

## Expected result:

Ability to play Netflix video

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F101)
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 

No

## Miscellaneous Information:
Netflix troubleshooting indicates to make sure that you're using an "official version of Chrome"

**Comment by ryanbr** [comment]
Tested with a new profile of Brave, after logging in. I'll get this popup:

![netflix](https://user-images.githubusercontent.com/1659004/83936116-5fe6e080-a814-11ea-991c-b40b1d344d2f.png)

Also can be configured via `brave://settings/extensions`

![settings](https://user-images.githubusercontent.com/1659004/83936142-a3414f00-a814-11ea-8988-ca4a66f2688c.png)

I would start by clearing the cookies/site-settings, and ensure `brave://settings/extensions` has the `Widevine` option enabled.

**Comment by Geordon** [comment]
That did it.  Thank you!

**Comment by anilthapa44600** [comment]
That works for me too.
