### ISSUE TITLE
"Show Brave suggested sites in autocomplete suggestions" should default to off

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#10131]
The preference that drives the behavior described in https://github.com/brave/brave-browser/issues/9572 for ref code addition to default to opt-in only

## Test Plan
1. Install Brave with a clean profile
2. Navigate to `brave:/settings`, scroll to `Appearance`

## Expected Result
3. `Show Brave suggested sites in autocomplete suggestions` setting defaults to off

## Actual Result
3. `Show Brave suggested sites in autocomplete suggestions` setting defaults to on

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)
--- | ---
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1909 (Build 18363.836)
```

* ensured that `Show Brave suggested sites in autocomplete suggestions` under `brave://settings/appearance` is disabled by default on a clean profile
* ensured that `Brave suggested sites` are not being displayed in the omnibox when `Show Brave suggested sites in autocomplete suggestions` is disabled
* ensured that `Brave suggested sites` are being displayed in the omnibox when `Show Brave suggested sites in autocomplete suggestions` has been enabled
* ensured that `Brave suggested sites` was disabled after upgrading from `1.9.76 CR: 81.0.4044.138` --> `1.9.80 CR: 81.0.4044.138`
  * ensured that `Brave suggested sites` are not being displayed under the omnibox
  * ensured that `Brave suggested sites` are being displayed under the omnibox once `Show Brave suggested sites in autocomplete suggestions` is enabled via `brave://settings/appearance` after upgrading
* ensured that disabling `Show Brave suggested sites in autocomplete suggestions` under `brave://settings/appearance` before upgrading to `1.9.80 CR: 81.0.4044.138` retains the change.
