### ISSUE TITLE
[Desktop] Annoying Youtube ADs without a skip button

### ISSUE THREAD

**Issue by hillkim** [brave/brave-browser#10135]
## Description 
I don't know if youtube improved their ads or brave just allowed the ads to play before every video without a skip button. Either way , I cant watch any video with an ad without having to switch to firefox. 

## Steps to Reproduce

   1. Go to youtube.com
   2. Play any video with an ad
   3.  Watch the add play without a skip button 

## Actual result:
Endless ad on any youtube video

## Reproduces how often: 
On every youtube video with an ad

## Brave version (brave://version info)
Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @ryanbr @pes10k

**Comment by ryanbr** [comment]
This should be fixed in Brave Beta @hillkim

**Comment by ryanbr** [comment]
Hey @hillkim has this been improved with current Brave release?

**Comment by rebron** [comment]
Closing as fixed. #8209 @hillkim Please let us know if you're still having this issue and we'll reopen.

**Comment by hillkim** [comment]
Its is fixed @rebron  and @ryanbr .  Sure no problem.
