### ISSUE TITLE
Filter user-tracking parameters on Netflix

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#10136]
## Description 
Brave should remove trackers from the links on Netflix & more
(Someting like #4239 by @fmarier)

## Steps to Reproduce

   1. Launch video on Netflix

## Actual result:
https://www.netflix.com/watch/81232204?trackId=XXXXXX

## Expected result:
https://www.netflix.com/watch/81232204

## Reproduces how often: 
100%

**Comment by fmarier** [comment]
@TheAresjej are you aware of any documentation on the `trackId` parameter?

Is it limited to first-party tracking (i.e. on Netflix properties) or do these parameters appear on other domains too to track the user across sites?

**Comment by TheAresjej** [comment]
As far as I know, it only appears on netflix when you click on anything. I gave an example of a tracker after turning on the video, but there are still a few of them on the page itself and it seems that in this way netflix records every user's interaction with the page. 😄

**Comment by fmarier** [comment]
If it's limited to first-party tracking, then I don't think we're going to touch that parameter. I can appreciate that it looks unnecessary, and I'm sure it's not the only mechanism that Netflix has to track users on its website :)

If you do find these links outside of Netflix for the purpose of linking separate first-party cookies together, then please reopen this issue. Right now, I think that removing these query parameters would only have cosmetic benefits and could lead to compatibility problems down the line.

I've documented our general principles and approach for what we include in the query filter: https://github.com/brave/brave-browser/wiki/Query-String-Filter
