### ISSUE TITLE
[Android] Replace Your Wallet in rewards page with Verify wallet to match desktop behaviour 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10139]
## Description 
 Replace Your Wallet in rewards page with Verify wallet to match desktop behaviour 

## Steps to reproduce 

   1. Install nightly
   2. Enable rewards
   3. Rewards panel shows `Verify Wallet` where was in chrome://rewards it shows `Your wallet 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/84017631-90f21d00-a99c-11ea-9958-a2ad17dc9de6.png)

## Expected result
Similar to desktop 
![image](https://user-images.githubusercontent.com/17010094/84017649-98192b00-a99c-11ea-9b89-d5bca780f6bd.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.12.4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by NejcZdovc** [comment]
currently we didn't add it to settings page as we are planing to convert it to native

**Comment by deeppandya** [comment]
@srirambv  i think we should keep it as it is. right now, we don't have an option to attached uphold from chrome://rewards so it makes sense to have your wallet. once we have native UI, we will update it. So closing this issue for now.
