### ISSUE TITLE
[Desktop] Show date for contribution on internals page

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10137]
We should show date on contribution page

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.11.68 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Windows 10 OS Version 1903 (Build 18362.30)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5766
![image](https://user-images.githubusercontent.com/38657976/85035041-5d836f80-b1a0-11ea-89f5-0795f4a12000.png)
