### ISSUE TITLE
[Webcompat] BlockFi KYC Verification failing 

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#10132]
## Description 
Reported from @murphyd `BlockFi web compatibility issue: After signing up for an account, you need to go through the typical KYC steps. One of the steps is to verify your identity with “Persona” which appears as a white box until you unblock third party cookies.`

## Steps to Reproduce

   1. Signing up for an account on `https://blockfi.com/`
   2. During the verification, fails due to third-party cookies.
   3. 

## Actual result:

KYC process fails.

## Expected result:
Allow user to signup/KYC without issues

## Reproduces how often: 

Need more details (like the cookies

## Brave version (brave://version info)

`Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

`Allow all cookies` resolves it, but we need more info on which cookies/privacy settings is failing.

**Comment by lewisf** [comment]
Hey @ryanbr. I currently work at Persona. Please let me know if there's anything I can do to assist.

**Comment by ryanbr** [comment]
Is there a way to implement persona checks without needing 3rd-party cookies @lewisf  ?

**Comment by lewisf** [comment]
I tried setting "allow all cookies" on the shield, but i still cannot get a successful load. as far as third party cookies, I don't _think_ we use anything for the KYC flow. For other parts of the site, we may load Amplitude and/or Stripe.

Interestingly enough, if I go to **Inspector -> Application -> Clear Storage -> Clear Site Data**, everything starts to load okay, but this doesn't persist forever.

Anything that's worth trying on my side to get more info?

**Comment by lewisf** [comment]
Checking back in on this @ryanbr and @murphyd. I cannot get this working by `Allow all cookies`. I've tried deleting every line item in the **Application** and **Storage** sections of the `Application` tab in Dev tools, refreshing in between, and Brave seems to still not render the page.

The only thing that works is if I'm in the **Clear storage** item in **Application** -> **Clear Storage**, check only **Local and session storage** and hit **Clear site data**.

Why does this work when clearing each item individually not work? Why does this work despite the same items getting regenerated in storage the moment our app loads again?

**Comment by ryanbr** [comment]
I think there is a tracker issue. have deployed one fix https://github.com/easylist/easylist/commit/5218108a3d226fccf9a235325ff2000398d19d23

**Comment by ryanbr** [comment]
I'm not seeing issue now, `withpersona.com` verification, Previously the throbber would be failing to go to the next page. Its looking better now, can you confirm @lewisf @murphyd the page is rendering?

**Comment by lewisf** [comment]
@ryanbr looks good to me, thanks!

**Comment by ryanbr** [comment]
Great to see, closing ticket. Thanks for confirming
