### ISSUE TITLE
Extensions installed from should have a generic name

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1013]
## Description 

Extensions installed from should have a generic name

## Steps to Reproduce

   1. Install any extension from CWS
   2. Open `chrome://extensions` and click on details 
   3. Source shows `Brave web store`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/45219664-a3946b00-b279-11e8-979a-2b8072a075f0.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/45219717-d179af80-b279-11e8-9107-592794476009.png)

## Reproduces how often: 

Easy

## Brave version (about:brave info) 

Brave | 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/51350085-8e411000-1aa7-11e9-86aa-2e049f4a7f1d.png)
