### ISSUE TITLE
Remove allow_default ability for all suggested sites

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#10141]
## Description 

Based on user feedback, matching suggested sites which may contain a referral code to user typed input is not a good idea.

## Steps to Reproduce

   1. Fresh profile
   2. Make sure Brave Suggested sites is on in preferences
   3. Type in binance.com

## Actual result:

It used to match to the first autocomplete entry

## Expected result:

It should not match to the autocomplete entry

## Reproduces how often: 
Always

## Brave version (brave://version info)
All

## Version/Channel Information:
All

- Can you reproduce this issue with the current release?  yes 
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the dev channel?  yes
- Can you reproduce this issue with the nightly channel?  yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards?  n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
n/a

**Comment by LaurenWags** [comment]
Android issue - https://github.com/brave/brave-browser/issues/10998

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Reproduced issue with STR using 1.11.104:
<img width="733" alt="Screen Shot 2020-07-29 at 1 44 31 PM" src="https://user-images.githubusercontent.com/28145373/88834459-df07ed80-d1a1-11ea-840c-f311fcc422cc.png">

* Confirmed issue does not occur with same STR on 1.12.104:
<img width="833" alt="Screen Shot 2020-07-29 at 1 44 44 PM" src="https://user-images.githubusercontent.com/28145373/88834464-e16a4780-d1a1-11ea-9303-9b883b19f2d9.png">

------
