### ISSUE TITLE
Switching to inactive tabs after a long period causes them to reload

### ISSUE THREAD

**Issue by JohnstonCode** [brave/brave-browser#1014]
## Description 

When tabes are idle for an extended amount of time and clicking back to them make them do a full reload

## Steps to Reproduce

   1. open two tabs
   2. click one tab
   3. wait 5 minutes (not 100% sure on time)

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Version 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

### Reproducible on current release:

No

**Comment by srirambv** [comment]
This is expected. Tab get discarded after a while. You can check if the tab is frozen or discarded in `chrome://discards`
![image](https://user-images.githubusercontent.com/17010094/45225477-a2b80500-b28a-11e8-97ce-09e414a327d0.png)


If the tab is frozen then switching to it wont do a full reload. If the tab is discarded then a full reload is done

cc: @bbondy

**Comment by bbondy** [comment]
You can turn this off with `chrome://flags/#automatic-tab-discarding` but that's the default. Thanks for asking though!

**Comment by JohnstonCode** [comment]
Thanks a lot!
