### ISSUE TITLE
[Android] Manual Test run on Android Tab for 1.9.x Hotfix 1 Release

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#10158]
## Per release specialty tests

 - [x] "Show Brave suggested sites in autocomplete suggestions" should default to off.([#10131](https://github.com/brave/brave-browser/issues/10131))

## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

Pre-Requisite: Put previous build shortcut on the home screen. Also, have several sites 'Added to home screen' (from 3 dots menu) and then upgrade to new build
- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify shortcut is still available on the home screen after upgrade
- [x] Verify sites added to home screen are still visible and able to be used after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify settings changes done in the previous version are still retained on upgrade

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.9.80 on Samsung Galaxy Tab S5e (Android 9.0)
