### ISSUE TITLE
Latest Mac Release PKG URL

### ISSUE THREAD

**Issue by securitygeneration** [brave/brave-browser#10152]
Is there a fixed URL (like https://laptop-updates.brave.com/latest/osx) but that serves up the latest release version of Brave as a PKG file rather than a DMG? PKGs are much more useful in mass deployments.

**Comment by bsclifton** [comment]
cc: @mbacchi @mihaiplesa @aekeus 

I know referral downloads use PKG format so we have these. But not sure if we have a permalink we can share?

**Comment by mihaiplesa** [comment]
https://brave-browser-downloads.s3.brave.com/latest/Brave-Browser.pkg

**Comment by bsclifton** [comment]
Awesome- thank you go, @securitygeneration 😄

**Comment by securitygeneration** [comment]
Awesome, thanks @bsclifton @mihaiplesa :)
