### ISSUE TITLE
[Desktop] Browser Crash when loading `brave://settings/content/all`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10160]
Follow up to https://github.com/brave/brave-browser/issues/10049

Important: This is a regression introduced in 1.10.x
Important: The browser can get into crash loop if the page is automatically opened after restart

## Steps to Reproduce

   1. Clean profile
   2. Open `brave://settings/content/all`

## Actual result:

Crash

## Expected result:
No Crash

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

**Reproducible on**
Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Ubuntu 18.04 LTS

Brave | 1.11.56 Chromium: 83.0.4103.61 (Official Build) dev (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.12.8 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @mkarolin @rebron @bsclifton

**Comment by kjozwiak** [comment]
Reproduced the issue on `macOS 10.15.5 x64 Catalina` using the following build:

```
Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.15.5 (Build 19F101)
```

I'm going to move this into `1.10.x` as a `release/blocker` as we never want to introduce new crashes. Looks like @mkarolin is already working on a fix as per https://github.com/brave/brave-core/pull/5777.

CCing @rebron @bsclifton @bbondy.

**Comment by kjozwiak** [comment]
BTW, nice find @btlechowski 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.5 (Build 19F101)
```

* ensured that loading `brave://settings/content/all` doesn't crash the browser
