### ISSUE TITLE
Limit cookie lifetime for cross-site redirections

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#10163]
In order to limit the usefulness of redirect trackers (also called bounce trackers), we could cap the lifetime of the first-party cookie they set to a very low number (e.g. 1 hour).

This would affect only:
- top-level cross-site requests
- HTTP status codes: 301, 302, 303, 307, 308

It would not help with meta refreshes or JavaScript redirects (e.g. setting `window.location`) but it would likely defeat a number of cookie syncing techniques.

To test:
- SSO login flows (e.g. `accounts.google.com` redirects to `youtube.com` to set cookies on both).
- OAuth flows involving multiple domains (e.g. #9470)

Related: #539, #817.

**Comment by fmarier** [comment]
If this simple heuristic breaks OAuth flows, we could exempt redirects which contain the expected OAuth parameters (e.g. `response_type`, `client_id`, `scope`, `state`).

**Comment by fmarier** [comment]
Other signals to consider:

- The presence of a valid [`P3P` header](https://www.w3.org/TR/P3P/) may indicate non-essential cookies.
- The presence of an explicit `SameSite=None` cookie attribute may indicate non-essential cookies.
- The presence of **both** `HttpOnly` and `Secure` cookie attributes may indicate a useful cookie

**Comment by fmarier** [comment]
@pes10k Can this be closed now that we have ephemeral first-party storage for redirects? Or is there anything useful in here that we're not yet doing?

**Comment by pes10k** [comment]
yep, good to close.  Good catch!  I'll close it now
