### ISSUE TITLE
Sync option not available in Brave Desktop[Desktop]

### ISSUE THREAD

**Issue by mraniketr** [brave/brave-browser#10166]
## Description 

The sync option is not working even after my system and brave are fully up to date.

## Steps to Reproduce

   1.  Visit  brave://sync/ on PC

**Comment by bsclifton** [comment]
Thanks for the report @mraniketr 😄 

This is something that we're working through right now. Great progress is being made and we're shooting to have this around version 1.12

Please subscribe to https://github.com/brave/brave-browser/issues/9989 and https://github.com/brave/brave-browser/issues/9241 for updates 😄
