### ISSUE TITLE
[Desktop] portion of split funded tips are being processed again on browser restart

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10176]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/10153

If you have a tip which is funded via multiple sources, when you restart the browser a portion of that tip is processed/contributed again.

## Steps to Reproduce

   1. Launch clean profile w/ flags /Applications/Brave\ Browser\ Nightly.app/Contents/MacOS/Brave\ Browser\ Nightly --enable-logging=stderr --vmodule=*/bat-native-ledger/*=6,*/brave_rewards/*=6 --log-level=2 --rewards=staging=true --brave-ads-staging
   2. Enable Rewards
   3. Claim UGP grant (30 BAT).
   4. Restore the wallet, note balance (should be at least 20 BAT)
   5. Tip kjozwiakstaging.github.io 50 BAT.
   6. Give the tip a bit of time to process.
   7. Confirmed ending wallet balance was as expected, tips panel is as expected, etc.
   8. Close and relaunch.

## Actual result:

The portion of the tip which was funded with the anon wallet (20 BAT) is processed again.

## Expected result:
Nothing should be contributed again after restart as the tip was processed in full, successfully, prior to restart.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.12.11 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @NejcZdovc @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the scenarios from https://github.com/brave/brave-core/pull/5782#issuecomment-642049788

**Scenario 1:**
- Verified the STR mentioned above
- Verified that one-time is processed (20 BAT was taken from the restored wallet and 30 BAT from UGP, 10 BAT anon wallet funds has remained in the wallet)
- Verified that the potion of BAT funded via Restored anon wallet is not processed after the browser restart
![image](https://user-images.githubusercontent.com/38657976/84353571-0ea46b80-abdd-11ea-876a-ae03f328a0b6.png)
![image](https://user-images.githubusercontent.com/38657976/84353594-16641000-abdd-11ea-8464-56368c7c4f43.png)
![image](https://user-images.githubusercontent.com/38657976/84353611-20860e80-abdd-11ea-85de-0d14a7a1731b.png)
![image](https://user-images.githubusercontent.com/38657976/84353719-46abae80-abdd-11ea-80c0-977046293958.png)
- Logged https://github.com/brave/brave-browser/issues/10217
------
