### ISSUE TITLE
[Android] Move site suggestions strings to an appropriate file

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#10175]
## Description 
Those 2 strings should be moved to `android_brave_strings.grd`

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan:
1. Once translations are ready check that options `Show top sites in autocomplete` and `Show suggested sites in autocomplete` are translated

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.10
- Verified text is translated

French| German| Polish | Japanese | 
--| -- |-- | --
![image](https://user-images.githubusercontent.com/17010094/89636121-03e61a00-d8a0-11ea-8329-e0a08518109a.png) | ![image](https://user-images.githubusercontent.com/17010094/89636136-08aace00-d8a0-11ea-8198-72c75cc86c36.png) | ![image](https://user-images.githubusercontent.com/17010094/89636147-0d6f8200-d8a0-11ea-9e4f-ca943ca2b204.png) | ![image](https://user-images.githubusercontent.com/17010094/89636156-12343600-d8a0-11ea-8e1a-bd8dbd531088.png)

-------------------------------
Verification passed on Samsung Tab A with Android 10 running 1.12.10
- Verified text is translated

French| German| Polish | Japanese | 
--| -- |-- | --
![image](https://user-images.githubusercontent.com/17010094/89636182-20825200-d8a0-11ea-8725-f9eedf5dbd60.png) | ![image](https://user-images.githubusercontent.com/17010094/89636179-1ceecb00-d8a0-11ea-8727-3faf983c7ef4.png) | ![image](https://user-images.githubusercontent.com/17010094/89636213-2b3ce700-d8a0-11ea-8582-eef57382d621.png) | ![image](https://user-images.githubusercontent.com/17010094/89636200-27a96000-d8a0-11ea-8dd2-628d7a49b62e.png)
