### ISSUE TITLE
[Desktop]

### ISSUE THREAD

**Issue by didman350** [brave/brave-browser#10173]
## Description 

I created a profile on my Brave Browser and all the BAT I collected until then have "gone"
I suppress the profile ant thought it would help to get back to normal, but I still don't have my BAT back ( about 25)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:
get back my BAT ( about 25)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@didman350 so you created new brave profile?

**Comment by didman350** [comment]
yes. and then my Bats desapear


Didier Mandin
Directeur associé
www.ak-a.fr

**Comment by NejcZdovc** [comment]
@didman350 clean profile resets tokens, so currently you can not backup tokens

**Comment by didman350** [comment]
so they are lost forever?

Didier Mandin
Directeur associé
www.ak-a.fr

**Comment by hollons** [comment]
Hi @didman350 - I can help to take a closer look. Can you send an email to Steven@brave.com with your Rewards Internals, they can be found here - brave://rewards-internals/. Thank you!

**Comment by hollons** [comment]
@didman350  - please email to me directly and refrain from posting in this thread for you own privacy.

**Comment by didman350** [comment]
??

Didier Mandin

**Comment by hollons** [comment]
Please send your information in a direct email to Steven@brave.com as opposed to in this thread. Once you send via email, I can be of direct help from there.
