### ISSUE TITLE
[Desktop] Build for musl-based system

### ISSUE THREAD

**Issue by JonasVautherin** [brave/brave-browser#10174]
## Description 
Trying to build for a musl-based system, I end up having an issue with `python3.8` apparently embedded by `depot_tool`: if I `ldd vendor/depot_tools/bootstrap-3.8.0.chromium.8_bin/python3/bin/python3.8`, I get:

```
Error loading shared library libcrypt.so.1: No such file or directory
```

It seems to me that `libcrypt.so.1` comes from `glibc`, so I am not sure what to do on a musl-based system. Is there anything I can do?

## Steps to Reproduce
Follow the "install from sources" instructions up to `npm run init`

## Brave version (brave://version info)
Latest `master` branch

**Comment by bsclifton** [comment]
@JonasVautherin for comparison, do you know if Chromium is compile-able with musl libc?

**Comment by JonasVautherin** [comment]
Alpine has it for x86_64 and aarch64: https://pkgs.alpinelinux.org/packages?name=chromium&branch=edge

**Comment by anxhb** [comment]
Any updates on this ?

**Comment by JonasVautherin** [comment]
At least I won't work on that.
