### ISSUE TITLE
Respect "do not disturb" on Linux for notifications

### ISSUE THREAD

**Issue by metal3d** [brave/brave-browser#10171]
## Description 

Using Brave for some "self PWA" and as browser, Brave doesn't respect the "do not disturb" state in Gnome for Linux users and displays notifications (Ads, messages from Slack, messages from Gmail...). 

Google Chrome respect this state AFAIK.

## Steps to Reproduce

   1. Open a web page that has got notifications activated
   2. Set your Gnome session in "do not disturb"
![image](https://user-images.githubusercontent.com/100080/84142931-f48c5100-aa55-11ea-8105-3a861b3d0738.png)

   3. Wait for notifications...

## Actual result:
Ads, and any others notifications are displayed even if I set Gnome to "do not disturb"

## Expected result:
Notifications should not appear as a popup

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux
JavaScript | V8 8.1.307.32
Flash | (désactivée)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line | /opt/brave.com/brave/brave --profile-directory=Default --app-id=kjbdgfilnfhdoflbpgamdcdgpehopbep --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,PassiveMixedContentWarning,AutoupgradeMixedContent,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,AllowPopupsDuringPageUnload,NotificationTriggers,SmsReceiver,AudioServiceOutOfProcess,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/pafer/.config/BraveSoftware/Brave-Browser/Default

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? No (and older version also works as expected, Brave is the only one who has that problem)

## Miscellaneous Information:

Related to #9243

**Comment by metal3d** [comment]
Additional note: This is **very important**. When I'm making video conferences, I don't want to let my interlocutors seeing my mail subjects when they arrive in Gmail, or message from Slack, Mattermost, and so on. Notifications should be disabled globally following the Gnome parameter.

**Comment by tmancey** [comment]
@metal3d Ads should not be shown while the browser is in full-screen mode or out of focus, i.e. another app is in focus. Can you please confirm this is working as expected for you? Thank you

**Comment by metal3d** [comment]
Sorry for the delay, it seems to work now. Thanks a lot !

**Comment by dswapnil104** [comment]
> Sorry for the delay, it seems to work now. Thanks a lot !

Not sure why but the google calendar meet notifications still get through on Pop OS , Brave browser while the DnD is turned on.
