### ISSUE TITLE
[Desktop] Set the safebrowsing api endpoint at build time

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10182]
## Description 
Safe browsing endpoint is currently set in `lib/config.js` - We should use npm config to set it during build time.

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/5826

**Comment by jumde** [comment]
Reverted: 
- https://github.com/brave/brave-browser/issues/10182
- https://github.com/brave/brave-core/pull/5825

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5826
![image](https://user-images.githubusercontent.com/34715963/88918693-29ed3800-d26a-11ea-8144-f0ecbccf0230.png)
![image](https://user-images.githubusercontent.com/34715963/88918748-46897000-d26a-11ea-8baa-fd2c8b674857.png)
![image](https://user-images.githubusercontent.com/34715963/88918731-3ec9cb80-d26a-11ea-8bed-a692e45ef3e9.png)
