### ISSUE TITLE
[Desktop] Reset last promotion fetch on wallet restore

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10181]
## Description 

When you are restoring wallet on desktop promotion last fetch should be reset so that promotion is fetched for new wallet right away. We have 10min cache for promotions now implemented in https://github.com/brave/brave-browser/issues/9513

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5786

-------
