### ISSUE TITLE
[Desktop] brave://crashes has a "Provide additional details" button that links to chromium bug reporting

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10185]
## Description 

brave://crashes page w/ C83 now contains a 'Provide additional details' button that directs the user to chromium in order to report on additional crash details. 

C81 version did not have this button on brave://crashes.

## Steps to Reproduce

   1. If not enabled, enable sending of crash reports in settings.
   2. Navigate to brave://crash 
   3. Naivgate to brave://crashes
   4. Click on Provide additional details button

## Actual result:

Button directs you to bugs.chromium.org and prompts you to login to google.
<img width="1194" alt="Screen Shot 2020-06-09 at 3 42 49 PM" src="https://user-images.githubusercontent.com/28145373/84193198-0deac880-aa69-11ea-9e04-d3467258279d.png">

<img width="1197" alt="Screen Shot 2020-06-09 at 3 51 10 PM" src="https://user-images.githubusercontent.com/28145373/84193224-14794000-aa69-11ea-8cb6-de1c605985d1.png">

## Expected result:
Button should either be removed (as it was in 1.9.x/C81 as below) or link to one of our pages.

<img width="1195" alt="Screen Shot 2020-06-09 at 3 40 57 PM" src="https://user-images.githubusercontent.com/28145373/84193234-180cc700-aa69-11ea-8d4c-b87afbc101eb.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @bsclifton @mkarolin @brave/legacy_qa

**Comment by btlechowski** [comment]
Testing is blocked on Linux due to https://github.com/brave/brave-browser/issues/4296. I marked this issue as `OS/macOS` and `OS/Windows`.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified items listed in https://github.com/brave/brave-core/pull/5798#issuecomment-643039280
* Confirmed that both `brave://crash` and `brave://gpucrash` are appearing under `brave://crashes`
* Confirmed able to manually select to upload crash reports without having the `Help improve Brave's features and performance` setting toggled on in `brave://settings/privacy` (note, after selecting to upload the crash report I do need to restart the browser as per https://github.com/brave/brave-browser/issues/1299)
* Confirmed crash reports displayed on server after restarting the browser in above scenario
* Confirmed crash reports are being sent automatically when `Help improve Brave's features and performance` is enabled via `brave://settings/privacy`
* Confirmed crash reports displayed on server in above scenario
* Confirmed clicking on `Provide additional details` redirects from bugs.chromium.org to GH
* Confirmed logging into GH autopopulates an issue per https://github.com/brave/brave-core/pull/5798#issuecomment-642304332

Example:
Here are some crash reports I generated and confirmed on the server:
<img width="536" alt="Screen Shot 2020-06-12 at 10 02 12 AM" src="https://user-images.githubusercontent.com/28145373/84511088-052a0a80-ac94-11ea-9d98-59e03ff38b4c.png">
After clicking the `Provide additional details` button and logging into GH when prompted, issue is autopopulated as below:
<img width="1048" alt="Screen Shot 2020-06-12 at 10 03 36 AM" src="https://user-images.githubusercontent.com/28145373/84511096-06f3ce00-ac94-11ea-944a-0283d5167b28.png">
