### ISSUE TITLE
[Android] Onboarding Notification

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#10191]
## Description 

As part of https://github.com/brave/brave-browser/issues/9839

Please implement the notification part of Onboarding V2

The copy for the notifications can be found on GDrive "Engagement Notifications"

**Comment by srirambv** [comment]
<details>
      <summary>Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build</summary>

   <details>
      <summary>3hrs notification when privacy report is enabled</summary>
      
   - Verified `You blocked X trackers & ads with Brave browser in the past 3 hours.` is shown after 3hrs of install when blocked trackers is more than 5.
![image](https://user-images.githubusercontent.com/17010094/91970014-f0976480-ed0e-11ea-9f66-d28a9fa52300.png)

   - Verified `Browse up to 6x faster on major news sites in Brave by blocking trackers & ads. ` message is shown after 3hrs of install when blocked trackers is less than 5
![image](https://user-images.githubusercontent.com/17010094/91969996-ed03dd80-ed0e-11ea-9568-2addde359dea.png)

   - Verified clicking the notification loads privacy report on the tab
   </details>

   <details>
      <summary>3hrs notification when privacy report is not enabled</summary>

   - Verified if privacy report is not enabled, after 3hrs of usage `Turn on privacy reports to see how many trackers & ads have been blocked in the past 3 hours.` notification is shown
![image](https://user-images.githubusercontent.com/17010094/91970032-f55c1880-ed0e-11ea-9432-a26ef5fcc10b.png)

   - Verified clicking on the notification shows onboarding on a new tab and loads onboarding

   </details>

   <details>
      <summary>24hrs notification when privacy report is enabled</summary>
      
 - Verified after 24hrs of install, `You saved Xkb data with Brave browser.` notification is shown
![image](https://user-images.githubusercontent.com/17010094/91970544-b9758300-ed0f-11ea-9063-08fb3906dcb8.png)

 - Verified clicking on the notification opens privacy report on the current tab
   </details>

   <details>
      <summary>24hrs notification when privacy report is not enabled</summary>
      
   - Verified after 24hrs of install, `Turn on privacy reports to see how much data you've saved` notification is shown.
![image](https://user-images.githubusercontent.com/17010094/91970261-4bc95700-ed0f-11ea-9b57-eff4432a9dd1.png)

   - Verified clicking on the notification opens privacy report onboarding on a new tab
   </details>

   <details>
      <summary>Default Browser notification</summary>
      
   - Verified 48hrs after install `Set Brave as your default browser for fast private browsing.` notification is shown.
![image](https://user-images.githubusercontent.com/17010094/91971108-93041780-ed10-11ea-8357-a9816f56e8ee.png)

   - Verified clicking on it brings up default browser setting option. Setting it as default opens `brave.com/blog`
   - Verified the same notification is shown on 6th day and 20th day after install as well
   - Verified subsequent notifications are not shown if Brave is set as the default browser on the first notification
   </details>

   <details>
      <summary>Battery</summary>
     
   - Verified after 6 days of install, `Brave browser uses 40% less battery on average. 🔋` notification is shown.
![image](https://user-images.githubusercontent.com/17010094/91971267-d2caff00-ed10-11ea-930e-ff3f2c0b0b3c.png)

   - Verified clicking on it opens a new tab
   </details>

   <details>
      <summary>Weekly stats</summary>
     
   - Verified after a week of install, `You blocked X trackers & ads with Brave browser last week.` notification is shown 
![image](https://user-images.githubusercontent.com/17010094/91971284-db233a00-ed10-11ea-950a-f73823b3b485.png)

   - Verified clicking on it opens privacy report on the current tab
   </details>

   <details>
      <summary>Rewards Notification</summary>
   
   - Verified if rewards is not enabled on a clean install, `Earn tokens by viewing privacy-respecting ads and support your favorite websites.` notification is shown on 10 days after install
![image](https://user-images.githubusercontent.com/17010094/91971417-0f96f600-ed11-11ea-9b67-313030006c4a.png)

   - Verified clicking the notification opens rewards panel
   - Verified same notification is shown on 30 & 35 days if rewards wasn't enabled on the first notification
   </details>

   <details>
      <summary>First 250 ads & trackers are blocked</summary>
    
   - Verified after 250 ads & trackers are blocked, `Nice! You've blocked 250 trackers & ads with Brave browser. 🔥` notification is shown 
![image](https://user-images.githubusercontent.com/17010094/91972060-0ce8d080-ed12-11ea-8a61-91c2a580783c.png)

   - Verified clicking on the notification opens a new tab
   </details>

   <details>
      <summary>First 10MB of data saved</summary>
      
   - Verified when 10MB on data is saved `Nice! You've saved 10MB with Brave browser. 🔋` notification is shown
![image](https://user-images.githubusercontent.com/17010094/91972051-09554980-ed12-11ea-97fa-9e4330d23428.png)

   - Verified clicking on it opens a new tab
   </details>

   </details>

----------------------
  <details>
      <summary>Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build</summary>

   <details>
      <summary>3hrs notification when privacy report is enabled</summary>
      
   - Verified `You blocked X trackers & ads with Brave browser in the past 3 hours.` is shown after 3hrs of install when blocked trackers is more than 5.
![image](https://user-images.githubusercontent.com/17010094/91974103-322b0e00-ed15-11ea-909e-acc3a56a0446.png)

   - Verified `Browse up to 6x faster on major news sites in Brave by blocking trackers & ads. ` message is shown after 3hrs of install when blocked trackers is less than 5
![image](https://user-images.githubusercontent.com/17010094/91973672-85509100-ed14-11ea-9e68-526e420ecb4b.png)

   - Verified clicking the notification loads privacy report on the tab
   </details>

   <details>
      <summary>3hrs notification when privacy report is not enabled</summary>

   - Verified if privacy report is not enabled, after 3hrs of usage `Turn on privacy reports to see how many trackers & ads have been blocked in the past 3 hours.` notification is shown
![image](https://user-images.githubusercontent.com/17010094/91974268-71f1f580-ed15-11ea-872f-1c48ada3184a.png)

   - Verified clicking on the notification shows onboarding on a new tab and loads onboarding

   </details>

   <details>
      <summary>24hrs notification when privacy report is enabled</summary>
      
 - Verified after 24hrs of install, `You saved Xkb data with Brave browser.` notification is shown
![image](https://user-images.githubusercontent.com/17010094/91972569-cfd10e00-ed12-11ea-85a0-2d74eb588a94.png)

 - Verified clicking on the notification opens privacy report on the current tab
   </details>

   <details>
      <summary>24hrs notification when privacy report is not enabled</summary>
      
   - Verified after 24hrs of install, `Turn on privacy reports to see how much data you've saved` notification is shown.
![image](https://user-images.githubusercontent.com/17010094/91974447-b1b8dd00-ed15-11ea-8831-3b3b057d6aa4.png)

   - Verified clicking on the notification opens privacy report onboarding on a new tab
   </details>

   <details>
      <summary>Default Browser notification</summary>
      
   - Verified 48hrs after install `Set Brave as your default browser for fast private browsing.` notification is shown.
  ![image](https://user-images.githubusercontent.com/17010094/91974537-d1500580-ed15-11ea-844c-2599d6ca2080.png)

   - Verified clicking on it brings up default browser setting option. Setting it as default opens `brave.com/blog`
   - Verified the same notification is shown on 6th day and 20th day after install as well
   - Verified subsequent notifications are not shown if Brave is set as the default browser on the first notification
   </details>

   <details>
      <summary>Battery</summary>
     
   - Verified after 6 days of install, `Brave browser uses 40% less battery on average. 🔋` notification is shown.
![image](https://user-images.githubusercontent.com/17010094/91974923-7c60bf00-ed16-11ea-9e90-f28376278d03.png)

   - Verified clicking on it opens a new tab
   </details>

   <details>
      <summary>Weekly stats</summary>
     
   - Verified after a week of install, `You blocked X trackers & ads with Brave browser last week.` notification is shown 
![image](https://user-images.githubusercontent.com/17010094/91975155-e0838300-ed16-11ea-87b3-031aade61b76.png)

   - Verified clicking on it opens privacy report on the current tab
   </details>

   <details>
      <summary>Rewards Notification</summary>
   
   - Verified if rewards is not enabled on a clean install, `Earn tokens by viewing privacy-respecting ads and support your favorite websites.` notification is shown on 10 days after install
![image](https://user-images.githubusercontent.com/17010094/91975511-69022380-ed17-11ea-98f5-97ad4b8fd5f5.png)

   - Verified clicking the notification opens rewards panel
   - Verified same notification is shown on 30 & 35 days if rewards wasn't enabled on the first notification
   </details>

   <details>
      <summary>First 250 ads & trackers are blocked</summary>
    
   - Verified after 250 ads & trackers are blocked, `Nice! You've blocked 250 trackers & ads with Brave browser. 🔥` notification is shown 
![image](https://user-images.githubusercontent.com/17010094/91976235-93a0ac00-ed18-11ea-8d0c-4b4690dbad44.png)

   - Verified clicking on the notification opens a new tab
   </details>

   <details>
      <summary>First 10MB of data saved</summary>
      
   - Verified when 10MB on data is saved `Nice! You've saved 10MB with Brave browser. 🔋` notification is shown
![image](https://user-images.githubusercontent.com/17010094/91976282-9e5b4100-ed18-11ea-8b71-a4fbac950425.png)

   - Verified clicking on it opens a new tab
   </details>

   </details>
