### ISSUE TITLE
[Desktop] mixed content is no longer being auto-upgraded

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10190]
## Description 

With C83 mixed content stopped being auto-upgraded (implemented with https://github.com/brave/brave-browser/issues/4381). 

## Steps to Reproduce

1. Open https://mixed.badssl.com
2. Click the padlock icon and make sure it's marked as secure.

## Actual result:

<img width="1534" alt="1 10 86 - RC with C83" src="https://user-images.githubusercontent.com/28145373/84198485-a127fc00-aa71-11ea-80fc-6a95680c99b6.png">

## Expected result:
Should be as it was in 1.9.x (w/ C81):
<img width="1539" alt="1 9 80 - Release" src="https://user-images.githubusercontent.com/28145373/84198511-a9803700-aa71-11ea-8220-96a37e62a475.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.9.x no, 1.10.x (w/ C83) yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel?  yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @bsclifton @fmarier @brave/legacy_qa

**Comment by diracdeltas** [comment]
This should be automatically fixed by https://chromium-review.googlesource.com/c/chromium/src/+/2454853, which is in cr88. I cherry-picked part of that change into cr87 and verified that it fixes the issue.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

Verified STR from description.

<img width="1035" alt="Screen Shot 2021-01-20 at 12 35 01 PM" src="https://user-images.githubusercontent.com/28145373/105212877-01a90c80-5b1c-11eb-948e-fa9b679fa764.png">

--------------
