### ISSUE TITLE
[Sync v2] device list update

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#10198]
When a device leaves sync chain, other devices on the sync chain will still see the leaving device listed.

In order to solve this issue, 
Server needs to:
1. ~Listen to `SyncDisabledEvent` on `/event` endpoint (components/sync/protocol/sync.proto)~
1.1. ~Client sends this event in `syncer::SyncStoppedReporter`(components/sync/driver/sync_stopped_reporter.cc)~
2. ~Prepare `SyncEntity` with same `id_string` or `client_defined_unique_tag` as the client who sends  `SyncDisabledEvent` for other clients on sync chain to fetch~
2.1. ~leave `DeviceInfoSpecifics` empty because client doesn't access it when applying deleted update (see `ProcessUpdate` in `components/sync/engine_impl/syncer_util.cc`). Also when client creates deleted `SyncEntity` commit, it sends empty specific~

3. ~Keep track device number of sync chain, when there is no devices on sync chain, delete all the data~

Client needs to: 
1.  ~Send `server_id` instead of `cache_guid` in `SyncDisabledEvent` so that server can update db~
2. ~check if itself is the last client who is about to leave the sync chain, if yes, warning user this action will clear all the data on server and ask whether to continue.~
---
OR

Client makes sure it commits delete self device info record. This method can also allow us to delete other devices on device list

cc @bridiver @jsecretan @yrliou

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5871
**Online**
![image](https://user-images.githubusercontent.com/34715963/88724358-9d882b80-d12a-11ea-9677-c5a0ca4c7dca.png)

**Offline**
![image](https://user-images.githubusercontent.com/34715963/88724860-7bdb7400-d12b-11ea-81ca-56b05e1da454.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.111 x64 build
- Verified online scenario from https://github.com/brave/brave-core/pull/5871
- Offline scenario failed. Logged #11166 
-------------
Verification passed on Samsung Tab A with Android 10 running 1.12.111 x64 build
- Verified online scenario from https://github.com/brave/brave-core/pull/5871
- Offline scenario failed. Logged #11166
