### ISSUE TITLE
[Android] Implement changes to support sync v2 on Android

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10203]
## Description 

Implement changes to support sync v2 on Android

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.108

**Migrating from sync v1**
- Verified sync is disabled after migration
- Verified infobar is shown on upgrade to 1.12.x and infobar contains `Begin Setup` which when clicked loads sync creation page

**Sync chain creation on Android and connect desktop**
- Verified creating sync chain on Android and adding desktop to the chain works fine
- Verified both devices list each other

Android | Desktop
-- | --
![image](https://user-images.githubusercontent.com/17010094/89637041-828f8700-d8a1-11ea-834f-900c3d9c3ef7.png) | ![image](https://user-images.githubusercontent.com/17010094/89636980-655ab880-d8a1-11ea-9448-efd9e6848a65.png)

- Verified bookmarks added on Android is sync'd on desktop and bookmarks added on desktop sync's to Android

**Sync chain created on Desktop and connect Android**
- Verified able to join a sync chain created on Desktop by entering code words from desktop
- Verified both devices list each other
- Verified bookmarks added on Desktop sync's to Android and bookmarks added on Android sync's to Desktop

**Connect to the chain through QR code**
- Verified able to join a sync chain created on Desktop by scanning the QR code
- Verified both devices list each other
- Verified bookmarks added on Desktop sync's to Android and bookmarks added on Android sync's to Desktop

**Connect to the chain through QR code**
- Verified able to join a sync chain created on `Device A` by scanning the QR code
- Verified both devices list each other
- Verified bookmarks added on `Device A` sync's to `Device B` and bookmarks added on `Device B` sync's to `Device A`


**Leave and re-connect to the chain**
- Verified joining a sync chain and leaving it removes the device list 
- Verified rejoining the same sync chain just shows the active devices on the list

**Autofill Sync**
- Verified adding/editing/deleting autofill works fine and sync's across devices

**Bookmark Sync**
- Verified adding/editing/reordering/deleting bookmarks works fine and sync's across devices

**History Sync**
- Verified visiting pages and adding history is sync'd across devices
- Verified deleting a single history entry is sync'd across devices
- Verified clearing browser data remove history entries across all devices 

**Open Tabs**
- Verified sending open tabs from desktop sends a notification on mobile device

Notification tray | Notificaton on app
--|--
![image](https://user-images.githubusercontent.com/17010094/89653146-7cf46a00-d8be-11ea-8317-e3bce0fec2ca.png)| ![image](https://user-images.githubusercontent.com/17010094/89656142-1291f880-d8c3-11ea-9316-eab2c30672fd.png)


- Verified sent tab is automatically added in history

**Password Sync**
- Verified saved passwords are sync'd successfully between devices
- Verified deleting stored password updates and removes it from all the devices on sync chain

**Settings Sync**
- Verified settings are sync'd across devices correctly 
-------------------------------
Verification passed on Samsung Tab A with Android 10 running 1.12.108

**Migrating from sync v1**
- Verified sync is disabled after migration
- Verified infobar is shown on upgrade to 1.12.x and infobar contains `Begin Setup` which when clicked loads sync creation page

**Sync chain creation on Android and connect desktop**
- Verified creating sync chain on Android and adding desktop to the chain works fine
- Verified both devices list each other

Android | Desktop
-- | --
![image](https://user-images.githubusercontent.com/17010094/89655950-bfb84100-d8c2-11ea-9d00-f2dc5933193c.png) | ![image](https://user-images.githubusercontent.com/17010094/89655639-4f112480-d8c2-11ea-8cf5-8038ba3f126d.png)

- Verified bookmarks added on Android is sync'd on desktop and bookmarks added on desktop sync's to Android

**Sync chain created on Desktop and connect Android**
- Verified able to join a sync chain created on Desktop by entering code words from desktop
- Verified both devices list each other
- Verified bookmarks added on Desktop sync's to Android and bookmarks added on Android sync's to Desktop

**Connect to the chain through QR code**
- Verified able to join a sync chain created on Desktop by scanning the QR code
- Verified both devices list each other
- Verified bookmarks added on Desktop sync's to Android and bookmarks added on Android sync's to Desktop

**Connect to the chain through QR code**
- Verified able to join a sync chain created on `Device A` by scanning the QR code
- Verified both devices list each other
- Verified bookmarks added on `Device A` sync's to `Device B` and bookmarks added on `Device B` sync's to `Device A`


**Leave and re-connect to the chain**
- Verified joining a sync chain and leaving it removes the device list 
- Verified rejoining the same sync chain just shows the active devices on the list

**Autofill Sync**
- Verified adding/editing/deleting autofill works fine and sync's across devices

**Bookmark Sync**
- Verified adding/editing/reordering/deleting bookmarks works fine and sync's across devices

**History Sync**
- Verified visiting pages and adding history is sync'd across devices
- Verified deleting a single history entry is sync'd across devices
- Verified clearing browser data remove history entries across all devices 

**Open Tabs**
- Verified sending open tabs from desktop sends a notification on mobile device

Notification tray | Notificaton on app
--|--
![image](https://user-images.githubusercontent.com/17010094/89656085-fa21de00-d8c2-11ea-97e4-0533014a0ed6.png) | ![image](https://user-images.githubusercontent.com/17010094/89656006-d8285b80-d8c2-11ea-9613-2c5a508e57d4.png)

- Verified sent tab is automatically added in history

**Password Sync**
- Verified saved passwords are sync'd successfully between devices
- Verified deleting stored password updates and removes it from all the devices on sync chain

**Settings Sync**
- Verified settings are sync'd across devices correctly
