### ISSUE TITLE
[Android] Disable twitter support in the panel

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10208]
We should check if site is twitter.com and just skip publisher being recorded if that is the case. This should only happen on Android.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9 running 1.10.95
- Verified no tips drop down is shown on a twitter handle 
- Verified no tips drop down is shown on a tweet from a twitter handle
- Verified tips dropdown is shown on a webpage
- Logged follow up issue #10399 for text change
