### ISSUE TITLE
[Desktop] [Meta-issue] New behavior for NTP-SI and Super-referral resources

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#10206]
## Description 
In order to provide more flexibility for the sponsored image on the new tab page (and the corresponding backgrounds for super-referrals), we want to add the following changes:

**Viewbox**: This optional field assists in ensuring that mobile portraits still appear correctly in view.  When this field is available, the client should ensure that this box of the image is always in view, zooming out if necessary and using the new backgroundColor field for ‘black bars’.  If not available, it should fall back to focalPoint.

**Logo**: Logo, alt-text, company name and destination URL specific to the background image, same format as existing logo section.  This is in the same format If not available, the client should default back to the standard logo configuration. => https://github.com/brave/brave-browser/issues/12190

**CreativeInstanceId**: A creative instance ID that has been registered in the ad server.  If the user has ads enabled, and if this field is available, the client should log views and subsequent ad actions with the standard confirmation mechanism.  If ads are not enabled or this is omitted, no action is necessary.  This will allow ads users to be more accurately rewarded for their views. => https://github.com/brave/brave-browser/issues/12190

An example of the new resource file might look like:

```
{
 wallpapers: [
   {
    imageUrl: url.jpg,
    focalPoint?:  { x: int, y: int },
    viewbox?: { x:1578, y: 1200, height: 600, width: 800 },
    backgroundColor: "#rrbbgg",
    creativeInstanceId: 3e47ee7a-8d2d-445b-8e60-d987fdeea613,
    logo: {
      imageUrl: PNG,
      alt: string,
      companyName: string,
      destinationUrl: URL, 
    }
   }
 ],
 logo: {
   imageUrl: PNG,
   alt: string,
   companyName: string,
   destinationUrl: URL,
  }
  schemaVersion: 1
}
```

**Comment by LaurenWags** [comment]
Labeling as `QA/Blocked` until test plan is confirmed. cc @jsecretan @simonhong @tmancey  @rebron @brave/legacy_qa

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
Revision	12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS	macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/6805

Confirmed each NTP SI has a different image, logo, and target URL when launching with `/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser --args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --rewards=staging=true --use-dev-goupdater-url`

**NTP SI 1:**
<img width="1145" alt="Screen Shot 2020-11-17 at 12 07 36 PM" src="https://user-images.githubusercontent.com/28145373/99422740-d876c080-28cd-11eb-81c7-bc32a2a2ae2d.png">
<img width="441" alt="Screen Shot 2020-11-17 at 12 07 45 PM" src="https://user-images.githubusercontent.com/28145373/99422747-dad91a80-28cd-11eb-9036-6201681e457f.png">
Above URL redirects to below:
<img width="1151" alt="Screen Shot 2020-11-17 at 12 07 54 PM" src="https://user-images.githubusercontent.com/28145373/99422779-e3c9ec00-28cd-11eb-9c29-f38884a922b9.png">

**NTP SI 2:**
<img width="1148" alt="Screen Shot 2020-11-17 at 12 08 42 PM" src="https://user-images.githubusercontent.com/28145373/99422823-efb5ae00-28cd-11eb-8820-cfb0cf79c41c.png">
<img width="318" alt="Screen Shot 2020-11-17 at 12 08 50 PM" src="https://user-images.githubusercontent.com/28145373/99422832-f0e6db00-28cd-11eb-9c5b-661b6ed1d74b.png">
<img width="1147" alt="Screen Shot 2020-11-17 at 12 09 00 PM" src="https://user-images.githubusercontent.com/28145373/99422841-f3493500-28cd-11eb-8912-03b27870e19c.png">

**NTP SI 3:**
<img width="1148" alt="Screen Shot 2020-11-17 at 12 09 15 PM" src="https://user-images.githubusercontent.com/28145373/99422864-f512f880-28cd-11eb-918c-5dc1c131b864.png">
<img width="335" alt="Screen Shot 2020-11-17 at 12 09 26 PM" src="https://user-images.githubusercontent.com/28145373/99422869-f6dcbc00-28cd-11eb-9acb-d3d2a6d0d2c7.png">
Above URL redirects to below:
<img width="1153" alt="Screen Shot 2020-11-17 at 12 09 41 PM" src="https://user-images.githubusercontent.com/28145373/99422896-fcd29d00-28cd-11eb-8668-9c4ac3f430e7.png">

Additional testing notes can be found under https://github.com/brave/brave-browser/issues/10488#issuecomment-726773394

---------------
