### ISSUE TITLE
[Desktop] Crash ID isn't uploaded even though Automatically sends crash reports settings is enabled 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10202]
## Description 

Crash ID isn't uploaded even though Automatically sends crash reports settings is enabled 
## Steps to Reproduce

   1. Clean profile 1.10.x
   2. Visit brave://crash in a new tab and make sure webview crashes
   3. Navigate to settings and enable `Automatically sends crash reports to Brave` setting
   4. Visit brave://crashes in 2nd tab
   5. The uploaded crash id isn't displayed, browser restart doesn't help
   

## Actual result:

Crash ID isn't uploaded even though Automatically sends crash reports settings is enabled 
![image](https://user-images.githubusercontent.com/38657976/84251318-d17fa100-ab2a-11ea-98cd-9b83c1808e5b.png)

## Expected result:

The crash ID should be uploaded when Automatically sends crash reports settings is enabled 
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton

**Comment by bsclifton** [comment]
@GeetaSarvadnya is this still an issue?
cc: @LaurenWags

**Comment by GeetaSarvadnya** [comment]
@bsclifton It's working fine now, verified in `Windows 10 x64 - 1.14.84`. Also, verified the crash report in Backtrace.

![image](https://user-images.githubusercontent.com/38657976/95084397-7148e680-073b-11eb-8947-865453b04901.png)
![image](https://user-images.githubusercontent.com/38657976/95084492-98071d00-073b-11eb-9fec-a6f5b5a21f54.png)
cc: @kjozwiak @LaurenWags
