### ISSUE TITLE
Ability to disable all ads whatsoever in Brave UI

### ISSUE THREAD

**Issue by leo-lb** [brave/brave-browser#10200]
Hello!

There is people who do not want to suffer the psychological harassement that ads are in any circumstance. Especially when one does install a web browser like Brave that has a builtin ad blocker.

Brave Web Browser is like an "ungoogled chromium" with better distribution on all platforms. On Android for example, it's one Chromium-based browser with ad blocking because Chrome on Android does not support extensions. There is reasons you would want to use Chromium-based browsers instead of Firefox because they have better performance.

Some people are not interested *at all* by the ads or earning rewards through ads, they just want the psychological harassement of ads to stop immediatly.

Yesterday I found that I now had crypto currency related ads in my "New Tab" pages, and I found no way to disable them in settings.

Thank you

**Comment by bsclifton** [comment]
@leo-lb are you looking for a single switch? you can disable the sponsored new tab page completely via the new tab page

In the bottom right, turn off `Show Sponsored Images`. You can also just turn off background images and that'll work too
![image](https://user-images.githubusercontent.com/4733304/84240902-8d04ee80-aab3-11ea-86b8-42bde8fc7171.png)

**Comment by leo-lb** [comment]
@bsclifton

Alright thank you, I could not find that switch, I will try whenever I am able to.

Yes it would be better to have a single no-nonsense switch. I do not think it pans out so great to hide such a thing behind so many different switches.

**Comment by bsclifton** [comment]
cc: @rebron

**Comment by leo-lb** [comment]
@bsclifton

Better yet it would be nice to ask *during* install whenever people want to turn on ads, donate (in crypto currency) or don't care at all.

I think it's safe to assume that no one wants ads at all by default, and if they do, they would be happy to respond yes to the question. I think it's important not to include UI dark pattern in the choice either, like by not making the turn on button for ads stick out, all buttons equal.

**Comment by leo-lb** [comment]
@bsclifton

I could disable "New Tab" ads with this switch, thank you.

What made me unable to find it is that it is not located within regular settings but in that "Customize" menu which I didnt even know existed.

A single no-nonsense switch would be good, but you could also move those ads related settings inside the corresponding section in the classical Chromium settings page.

**Comment by Merith-TK** [comment]
> 
> 
> @bsclifton
> 
> I could disable "New Tab" ads with this switch, thank you.
> 
> What made me unable to find it is that it is not located within regular settings but in that "Customize" menu which I didnt even know existed.
> 
> A single no-nonsense switch would be good, but you could also move those ads related settings inside the corresponding section in the classical Chromium settings page. I think that's where users expect things to be.

I Found on android you have to go to the apps notification settings and turn off `Brave Ads`. From the devices settings. THis is not very user intuitive, but the Brave Rewards icon stilll shows even when rewards is turned off

**Comment by Zireael07** [comment]
That sponsored images switch is so hidden, I wouldn't have expected it to be there. Please add it to general settings, too.

**Comment by Merith-TK** [comment]
> 
> 
> That sponsored images switch is so hidden, I wouldn't have expected it to be there. Please add it to general settings, too.

There isnt even a switch on mobile

**Comment by rebron** [comment]
Closing as we have a main method to disable all ads.

There is a main switch for Ads and there is a toggle to turn off Sponsored Images in both desktop and android. The toggle to turn off Sponsored images on desktop is in two places, on the new tab page itself and in brave://settings/newTab - one to display in context and one in settings.

Introducing new users to Brave, we also give another method to turn off sponsored images from the very beginning.

<img width="371" alt="Screen Shot 2020-08-07 at 9 07 59 AM" src="https://user-images.githubusercontent.com/5951041/89665409-844f4f80-d88d-11ea-916f-5fe402247217.png">

**Comment by Merith-TK** [comment]
That was not the issue, I can handle ads on my new tab, the issue was the
ads in notifications, the only way I got them to stop, was to go into my
phone's notification settings and disable them from showing. At all. There
is no toggle inside the android application to disable notification ads.

And while there is the toggle to not show ads while not in use, they still
show up when in use.

**Comment by Merith-TK** [comment]
Also, your post for closing this, only references the desktop browser,
which I have no issues with,
While the topic of this issue, was quite clearly directed to the mobile
Android version,

**Comment by Merith-TK** [comment]
Okay my email did not show the full post, for me, however the point of the android version still stands.

**Comment by bsclifton** [comment]
@Merith-TK there is - but it's a little tricky to find. When you tap the rewards icon (BAT logo), there's actually a `settings` link you can open (has a BAT logo next to it). It's not completely obvious this is a button. Once in there, you can toggle rewards

cc: @anthonypkeane @jenn-rhim
