### ISSUE TITLE
[Desktop] Crashes on start up

### ISSUE THREAD

**Issue by berkin** [brave/brave-browser#10210]
## Description 
Brave crashes on start up on macOS Catalina 10.15.5

## Steps to Reproduce
Open the brave. It crashes after 3-4 seconds. Sometimes it takes longer but not more than 30 secs.

## Reproduces how often: 

It started yesterday and it happens everytime. I removed recently installed extensions it did not help. 

## Brave version (brave://version info)

Brave	1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	macOS Version 10.15.5 (Build 19F101)
JavaScript	V8 8.1.307.32
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,MixedContentSiteSetting,SimplifyHttpsIndicator,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,DnsOverHttps --disable-features=TextFragmentAnchor,VideoPlaybackQuality,AllowPopupsDuringPageUnload,AudioServiceOutOfProcess,SmsReceiver,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers --flag-switches-begin --enable-features=PasswordImport,MixedContentSiteSetting,SimplifyHttpsIndicator,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,DnsOverHttps,BraveSync --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/berkin/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
yes
- Can you reproduce this issue with the beta channel? 
beta version even can not start. It crashes before i see the window
- Can you reproduce this issue with the dev channel? 
same as beta
- Can you reproduce this issue with the nightly channel? 
same as beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

I tried previous releases, it did not help also.

**Comment by berkin** [comment]
I have these messages in the activity monitor
`error	22:09:47.091582+0300	tccd	Prompting policy for hardened runtime; service: kTCCServiceAddressBook requires entitlement com.apple.security.personal-information.addressbook but it is missing for ACC:{ID: com.brave.Browser, PID[21043], auid: 501, euid: 501, binary path: '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser'}, REQ:{ID: com.apple.mds, PID[143], auid: 0, euid: 0, binary path: '/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mds'}
`

`Prompting policy for hardened runtime; service: kTCCServiceCalendar requires entitlement com.apple.security.personal-information.calendars but it is missing for ACC:{ID: com.brave.Browser, PID[21043], auid: 501, euid: 501, binary path: '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser'}, REQ:{ID: com.apple.mds, PID[143], auid: 0, euid: 0, binary path: '/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mds'}`

`{ID: com.brave.Browser, PID[21043], auid: 501, euid: 501, binary path: '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser'} attempted to call TCCAccessRequest without the com.apple.private.tcc.manager.check-by-audit-token entitlement`

**Comment by thefallofbecause** [comment]
This appears to be the sync bug from a few months ago popping its head up again. There have been a few users on Reddit suffering the same thing, and disabling sync has worked for them.

**Comment by berkin** [comment]
Yep disabling sync did help.
