### ISSUE TITLE
[Android] Unable to disconnect wallet if balance is below threshold

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10216]
## Description 
Unable to disconnect wallet if balance is below threshold

## Steps to reproduce 

   1. Install nightly and enable rewards on staging
   2. Claim grant and connect to uphold
   3. Tip a verified pub so balance is below threshold value
   4. Tap on verified wallet shows min balance message which is also wrong as it mentions about connecting 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/84348034-aac87580-abd1-11ea-88a1-fa0338dddac0.png)

## Expected result
Once wallet is connected balance should not determine if the account can be connected or disconnected

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.12.14

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by GeetaSarvadnya** [comment]
Verification passed oN Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.10.92.apk`
- Verified as pert of user wallet testing https://github.com/brave/brave-browser/issues/8511#issuecomment-645450793
