### ISSUE TITLE
Filter not being applied from brave://adblock

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#10218]
## Description 

Filter Sub from `brave://adblock` Easylist Cookie not being applied.

## Steps to Reproduce

   1. Subscribe to Easylist Cookie in `brave://adblock`
   2. Visit `https://in.reuters.com/` (vpn maybe needed).
   3. View blocked Ad/Trackers.
   4. `https://c.evidon.com/sitenotice/evidon-sitenotice-tag.js` should be blocked by this filter https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_general_block.txt#L542

## Actual result:
expect `/evidon-sitenotice-tag.` should be blocked

## Expected result:
Unblocked, and shows consent message (reported by @srirambv )

## Reproduces how often: 
Easily

## Version/Channel Information:
`Version 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)`

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Tested in Nightly / Aggressive-mode, didn't block this element

**Comment by ryanbr** [comment]
@antonok-edm @pes10k

**Comment by pes10k** [comment]
@ryanbr is there a relevant exception rule thats getting in the way?

**Comment by ryanbr** [comment]
Can confirm no other filters are affecting this (Checked with disconnect/unbreak/uBO lists loaded)

`https://c.evidon.com/sitenotice/evidon-sitenotice-tag.js` blocked in UbO/+Easylist Cookie

But when we enable Easylist-Cookie in `brave://adblock` this element isn't blocked.

**Comment by antonok-edm** [comment]
Just confirmed that this is working again after the crx-packager fixes.
