### ISSUE TITLE
[Desktop] UGP Token grants claimed is not shown in Monthly statement

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10217]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/10176#issue-635478207

## Steps to Reproduce

   1. Follow the STR  from https://github.com/brave/brave-browser/issues/10176#issue-635478207
   2. Open monthly statement
   3. UGP Token grants claimed is not shown in Monthly statement
   

## Actual result:

UGP Token grants claimed is not shown in Monthly statement
![image](https://user-images.githubusercontent.com/38657976/84354134-fbde6680-abdd-11ea-897b-a4c961a37092.png)

## Expected result:

UGP Token grants claimed should be shown in Monthly statement
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
this is expected as when you restore wallet rewards summary is reset
