### ISSUE TITLE
Add ability for bookmarks to open in a new tab

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1021]
Carried over from https://github.com/brave/browser-laptop/issues/10230

>	Request from community: https://community.brave.com/t/open-of-bookmarks-toolbar/4120
>
>	Good Day Devs and Community,
>
>	I realised just now that a feature I would really love to see in Brave is how it behaves when opening bookmarks.
>	Let's say you have one tab open and you're on a website browsing, it would be awesome if one can then select a bookmark (toolbar or otherwise), click on it and Brave opens up the selected bookmark in a new tab automatically, instead of opening it in the current tab (as is the behaviour now).

>	Regards

**Comment by petemill** [comment]
I would say this is a won't fix IMO - like most links anywhere, including the bookmark bar, any user can have it open in a new tab by either:
- cmd/ctrl + click
- simply middle-mouse-click

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/open-links-in-a-new-tab/48307?u=eljuno

**Comment by rebron** [comment]
Closing as wontfix per options to either cmd/ctrl + click or middle click to open a bookmark in a new tab.
