### ISSUE TITLE
[Android] Unable to disable Brave Rewards system

### ISSUE THREAD

**Issue by Merith-TK** [brave/brave-browser#10211]
## Description 
I never use the Brave Rewards system ever, I like the concept, but it gets in the way of my day to day use. So when brave updated I checked the settings for a way to turn it off like I can on desktop, To my dismay, I was unable to disable it

## Steps to reproduce 
   1. Install Brave
   2. Try to find a setting that turns off Brave Rewards
   3. Fail.

## Actual result 
No Option to turn off Brave Ads, And ads show up when I am browsing the internet.

## Expected result
Toggle Switch to turn off brave ads

## Issue reproduces how often 
Every single time one attempts to find the settings

## Issue happens on 
   - Current Play Store version?  Yes
   - Beta build? Untested

## Device details
   - Install type (ARM, x86): Armv7
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 9
   
## Brave version
Latest Google play as of 1620, 6-10-2020

### Website problems only
- Does the issue resolve itself when disabling Brave Rewards?

### Additional information
None, pretty straight forward

**Comment by srirambv** [comment]
You can disable individual items in chrome://rewads or just disable rewards

**Comment by Merith-TK** [comment]
> 
> 
> You can disable individual items in chrome://rewads or just disable rewards

This would need to be in a more user-friendly place on mobile. On PC/Desktop i can see this, like with `chrome://flags`, but on mobile that is an issue

**Comment by srirambv** [comment]
@Merith-TK  you don't need to disable any flags. On the hamburger menu if you click on `Brave Rewards` it loads rewards home page where you can disable individual items or disable rewards as a whole

**Comment by Merith-TK** [comment]
@srirambv the problem is. the icon is still on my top menu bar 
despite being turned off, that is part of the issue, i like the lion icon, but the rewards icon takes way more spae

**Comment by Merith-TK** [comment]
And for some reason it not letting me upload screenshots.

**Comment by srirambv** [comment]
Did you enable rewards and turn it off via brave://rewards page? In that case it is still enabled but inactive. You need to reset rewards so that you can completely disable it and hide the icon

**Comment by Merith-TK** [comment]
> 
> 
> Did you enable rewards and turn it off via brave://rewards page? In that case it is still enabled but inactive. You need to reset rewards so that you can completely disable it and hide the icon

1) No, Brave Rewards was enabled by default
2) Yes it is toggled off
3) where the frack is the reset button for brave rewards?

**Comment by srirambv** [comment]
> No, Brave Rewards was enabled by default 

Rewards is opt-in not opt-out. You might have enabled it during onboarding

> Yes it is toggled off

So its turned off not disabled

> where the frack is the reset button for brave rewards?

Menu -> Settings -> Advanced -> Brave Rewards -> Reset Brave rewards and restart browser then go to appearance and hide Brave rewards icon.

**Comment by Merith-TK** [comment]
Okay that fixed it.
But no, brave rewards was enabled by default for me,

And I believe that the rewards icon should only show when rewards is
actually enabled

**Comment by srirambv** [comment]
Glad that it worked. Going to close the thread now. Can discuss if anything else is needed and reopen if required.

Rewards has always been opt-in and not opt-out.
