### ISSUE TITLE
[Desktop] Brave tabs and extensions crash with nProtect GameGuard

### ISSUE THREAD

**Issue by ryanocf** [brave/brave-browser#10228]
## Description 
If you start a game that is protected by nProtect Gameguard, Brave is not operational anymore.
All tabs and most extensions will crash.

## Steps to Reproduce
   1. Open a game that is protected by nProtect GameGuard
   2. Wait until GameGuard is fully initialized
   3. Now most extensions should have crashed and every new or reloaded tab

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:
- Can you reproduce this issue with the current release? 
yes
- Can you reproduce this issue with the beta channel?
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
no
- Does the issue resolve itself when disabling Brave Rewards? 
no
- Is the issue reproducible on the latest version of Chrome? 
no

## Miscellaneous Information:
I tried it with the following games:
- Combat Arms
- Phantasy Star Online 2

I already tried to start Brave with  --disable-features=RendererCodeIntegrity parameter but no luck.

**Comment by bsclifton** [comment]
Also saw this reported with https://community.brave.com/t/brave-cannot-load-webpages-when-nprotect-gameguard-is-running/134348

I believe this is an issue with nProtect GameGuard. I am not sure how to report a bug though- I went to their website: https://nprotect.com/kr/index.html and it’s all in Korean

They’re likely blocking access to this app as it’s not recognized. Do you know if there’s another way to report the bug to them? If you wanted to test, I bet you could rename `brave.exe` as `chrome.exe` and it would probably work

**Comment by ryanocf** [comment]
Renaming `brave.exe` to `chrome.exe` worked.
So apparently they really block brave based on its process name.

nProtect has an international site for their GameGuard anticheat solution here: https://gameguard.nprotect.com/en/index.html
And I assume reporting a bug works via this form: https://nprotect.com/email/en/index.html#05_01

**Comment by cyclopssound** [comment]
I'm having the same issue with Brave while running PSO2. Which is weird since until today the two were working fine together, I'd have podcasts playing in Brave while I played.

**Comment by ryanocf** [comment]
Some updates:
For some reason, it works perfectly fine for now.
The browser tabs and extensions don't crash anymore even if you restart the browser while one of the stated games is fully initialized and running.
Thanks for the help anyways.
