### ISSUE TITLE
[Desktop] [sync v2] Leave sync chain doesn't always reflect correct UI state

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#10229]
## Description 

User has to leave sync chain twice to get UI knows it is reset. (If we don't close and reopen the sync setting tab) 

## Steps to Reproduce

   1. Setup sync chain
   2. When getting navigated to `brave://settings/braveSync`, click into setup page 
   3. Leave sync chain
   4. We can still see "Managed your synced devices" (But engine already shutdown)
   5. Go into setup page and leave sync chain again
   6. Now we can finally see "Start using sync"

## Actual result:

UI in step 4 doesn't show "Start using sync"

## Expected result:
UI in step 4 should show "Start using sync"

## Reproduces how often: 

always

## Brave version (brave://version info)

1.12.19 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Note that if in step 2 we close the tab and reopen a new tab to `brave://settings/braveSync`, UI will get correct state in step 4

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Verified STR from the description. After step 4, "Start using sync" is shown.
![10229](https://user-images.githubusercontent.com/34715963/88720159-b261c080-d124-11ea-8136-47804f7204dc.gif)
