### ISSUE TITLE
Feature Request: Add the option to show the bookmark bar only in the new tab page and when user clicks on the address bar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1022]
Carried over from brave-laptop, https://github.com/brave/browser-laptop/issues/14268

>The Brave bookmark bar, when enabled, takes away a lot of space from the browsing screen. But disabling it makes it hard to access. So, it would be great if Brave offered the option to show the bookmark bar only when the user is in the new tab page. It would even better if this feature also showed the bookmarks when the user clicks on the address bar but hide it when the user is browsing the page.

**Comment by petemill** [comment]
This is fixed right now with brave-browser (apart from the additional request to show when the address bar is clicked)

**Comment by rebron** [comment]
Marking closed. This works or is "fixed" now only because of https://github.com/brave/brave-browser/issues/1306  Going to settings-> Appearance and turning off show bookmarks bar option will allow this behavior. 

Once 1306 is fixed though and what more people want, this will be an issue again.

**Comment by sedlund** [comment]
This doesn't seem to work in Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
