### ISSUE TITLE
autotrader.com doesn't load because of adblock

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1023]
## Steps to reproduce
1. With shields enabled, visit http://autotrader.com
2. Notice totally blank screen
3. Use shields menu and pick `Allow ads and tracking` under `Ad Control`
4. Site works

**Comment by bsclifton** [comment]
Similar to https://github.com/brave/browser-laptop/issues/3303

**Comment by snyderp** [comment]
I cannot reproduce in the beta

**Comment by bsclifton** [comment]
@snyderp same- looks like it's resolved now 😄
