### ISSUE TITLE
Bold fonts suddenly started rendering not very bold

### ISSUE THREAD

**Issue by pateskinasy** [brave/brave-browser#10239]
Bold fonts suddenly started rendering not very bold

Bold is however being applied in styling as per browser inspection.

## Steps to Reproduce

   1. Just open link (e.g. front page of [eskinasy.com](https://www.eskinasy.com/))
   2. In Brave you get this:

<img width="747" alt="Screenshot 2020-06-12 at 14 34 05" src="https://user-images.githubusercontent.com/18645509/84508305-feae8980-acb9-11ea-9659-589a1b2b7549.png"> 

   3. While I expected an actual bold font like in Chrome and Safari:

<img width="747" alt="Screenshot 2020-06-12 at 14 34 00" src="https://user-images.githubusercontent.com/18645509/84508360-11c15980-acba-11ea-8b5d-bf8fdf55b510.png">

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Version 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:
- Can you reproduce this issue with the current release?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
Hi @pateskinasy Can you see if this is still an issue for you in our latest version 1.11.x? I'm seeing it as bold and can't reproduce what you're seeing.

![Screen Shot 2020-07-31 at 10 04 47 AM](https://user-images.githubusercontent.com/5951041/89059141-7fcaea00-d315-11ea-8dde-63d5f9a04983.png)

**Comment by pateskinasy** [comment]
Thanks @rebron for following up.

I confirm that after updating to latest version I no longer can replicate the issue.

Thanks!

**Comment by rebron** [comment]
Awesome. Thanks for the follow-up @pateskinasy and for filing the issue. Glad it's looking correctly.
