### ISSUE TITLE
[Desktop] Show an infobar that sync v2 is coming

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#10231]
This would be for versions 1.11.x and above.

Text:
> A new Brave Sync is coming. Get ready for the upgrade. **More information**

Link destination: https://brave.com/sync-v2-is-coming

**Comment by petemill** [comment]
Merged to v1.11.x

**Comment by btlechowski** [comment]
Marking as QA/Blocked - need a new build to test, 1.11.92 or newer.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` since https://github.com/brave/brave-browser/releases/tag/v1.11.92 is available

**Comment by LaurenWags** [comment]
sync info bar disappears before I can interact with it - logged https://github.com/brave/brave-browser/issues/10621 which blocks this issue from being tested.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-core/pull/6070 was merged.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.11.96 Chromium: 84.0.4147.89 (Official Build) (64-bit)
Revision	19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS	macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5806

Additional scenarios checked:
Scenario 1:
1. Install 1.10.97
2. Enable brave://flags flag for brave sync
3. Restart, dismiss default browser bar
4. Create a sync chain at brave://sync
5. Update to 1.11.x
6. Confirm info bar is shown

Scenario 2:
1. Install 1.10.97
2. Leave sync flag as Default (sync is disabled)
3. Restart, dismiss default browser bar
4. Update to 1.11.x
5. Confirm no info bar is shown

Scenario 3:
1. Install 1.10.97
2. Set sync flag to Disabled
3. Restart, dismiss default browser bar
4. Update to 1.11.x
5. Confirm no info bar is shown

Scenario 4:
1. Install 1.10.97
2. Set sync flag to Enabled
3. Restart, dismiss default browser bar
4. Set up sync chain
5. Set sync flag to Disabled
6. Restart browser.
7. Update to 1.11.x
8. Confirm no info bar is shown

<img width="1193" alt="Screen Shot 2020-07-14 at 1 44 22 PM" src="https://user-images.githubusercontent.com/28145373/87463109-ebefe300-c5de-11ea-943a-06095e8eab4d.png">

------
