### ISSUE TITLE
Set x-brave-api-key in stats ping header

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#10230]
#4488  Set x-brave-api-key in stats ping header 

Add `x-brave-api-key` header with usage ping. Do this instead of passing it as a query param.

## Test Plan

1. Get a release of the browser that has not sent it's daily activity ping to laptop-updates
2. Use charles/wireshark/etc and watch network requests
3. See that `api_key` as a query parameter to https://laptop-updates.brave.com/1/usage

## Miscellaneous Information:

Obsoletes test plan in https://github.com/brave/brave-browser/issues/9911

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` - need a new build to test, 1.11.92 or newer.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, https://github.com/brave/brave-browser/releases/tag/v1.11.92 is available

**Comment by LaurenWags** [comment]
Re-adding `QA/Blocked` until https://github.com/brave/brave-browser/issues/10610 is addressed.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from description

-----
