### ISSUE TITLE
[Android] Enable tap anywhere on the NTP SI notification

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#10247]
## Description 
Slack: https://bravesoftware.slack.com/archives/CQGTGBNH1/p1591994398085100?thread_ts=1591988892.081100&cid=CQGTGBNH1

Follow iOS and allow users to tap anywhere on that small alert vs only the "learn more” button

![image](https://user-images.githubusercontent.com/7606853/84555334-2c52fd00-acd1-11ea-8b66-73a668aa109b.png)

**Comment by deeppandya** [comment]
@srirambv can you verify this on nightly ? it's been fixed in previous release.

**Comment by srirambv** [comment]
@deeppandya  I don't see it on 1.14.27 which it the latest public nightly via playstore. Need to click on the learn more button to bring the modal

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build
- Verified tapping anywhere on the bottom banner brings up the rewards info modal
- Verified tapping on Hide sponsored images hides the current tab SI and disables the settings
- Verified Learn more opens FAQ page
- Verified clicking on the close button closes the banner and does not open the rewards info modal
- Verified clicking learn more on the banner brings up the rewards info modal
------------
Verification passed on Samsung Tab A with Android 10 running 1.12.112 x64 build
- Verified tapping anywhere on the bottom banner brings up the rewards info modal
- Verified tapping on Hide sponsored images hides the current tab SI and disables the settings
- Verified Learn more opens FAQ page
- Verified clicking on the close button closes the banner and does not open the rewards info modal
- Verified clicking learn more on the banner brings up the rewards info modal
