### ISSUE TITLE
[Desktop] Can't login on grammarly.com (even with brave shield down)

### ISSUE THREAD

**Issue by RubenKelevra** [brave/brave-browser#10246]
## Description 
I can't login on grammarly.com even when I deactivated the brave shield for this site. This also avoids that I can use the Grammarly plugin properly with brave, since it needs the login to access the cloud data.

## Steps to Reproduce

   1. navigate to grammarly.com
   2. login
   3. redirect to main page, with non-logged in status

## Actual result:
Login is successful but the main page is loaded after password input, and it shows the login button in the top right corner again, instead of the user account.

## Expected result:

Login works as expected.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave	1.9.80 Chromium: 81.0.4044.138 (Official Build) unknown (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	Linux
JavaScript	V8 8.1.307.32
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line	/usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=DnsOverHttps,PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,TextFragmentAnchor,AllowPopupsDuringPageUnload,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --enable-gpu-rasterization --enable-oop-rasterization --enable-quic --ignore-gpu-blacklist --enable-features=DnsOverHttps,PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,AudioWorkletRealtimeThread,AutofillShowTypePredictions,BraveSync,DecodeJpeg420ImagesToYUV,DecodeLossyWebPImagesToYUV,ExtensionsCheckup,FractionalScrollOffsets,ImpulseScrollAnimations,LegacyTLSEnforced,PaintHolding,PercentBasedScrolling,SyncSetupFriendlySettings,TLS13HardeningForLocalAnchors,TurnOffStreamingMediaCaching --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path	/usr/lib/brave-bin/brave
Profile Path	/home/ruben/.config/BraveSoftware/Brave-Browser/Default
Variations	eb1003e4-70ea8f25

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 

No

- Does the issue resolve itself when disabling Brave Rewards? 

No

- Is the issue reproducible on the latest version of Chrome? 

No

**Comment by ryanbr** [comment]
@RubenKelevra  Just tested this, with shields enabled. Logged in via Google auth, seemed to work fine here. Which login method are you using? Is it still happening?

**Comment by RubenKelevra** [comment]
I was using email and password.

Can try it again... :)

**Comment by bsclifton** [comment]
@RubenKelevra if you can upgrade to latest Brave (`1.10.95`) and then try again that would be great 😄 Let us know!

**Comment by RubenKelevra** [comment]
@bsclifton @ryanbr I just tried this version:

```
Brave | 1.10.93 Chromium: 83.0.4103.106 (Official Build) unknown (64-bit)
```

That's the latest version available from the AUR at the moment.

---

When I deactivate the Grammarly plugin, I can log in to the website, but when I activate it again, I'll get logged out and cannot login again.

So there's some compatibility issue with the connection between the website and the plugin.

**Comment by ryanbr** [comment]
I logged in via the site (not using the extension), I installed the extension, and seems to be working here.  

![gram](https://user-images.githubusercontent.com/1659004/85958569-84d10c80-b9ea-11ea-8056-85b5dac9d7bc.png)

We do have a related Grammarly ticket: https://github.com/brave/brave-browser/issues/1141    Probably safe to close this ticket.

**Comment by ryanbr** [comment]
With no plugin installed I can login via email,  (with a new email)  this probably is a dube of https://github.com/brave/brave-browser/issues/1141

**Comment by ryanbr** [comment]
Any Grammarly plugin issues we can address in https://github.com/brave/brave-browser/issues/1141   But without the plugin, social and email logins are working here. @RubenKelevra

**Comment by RubenKelevra** [comment]
This is not a dup, the extention is working fine. I just cannot login to this website when the extension is active.

This is an issue with the website, not with the extension.
