### ISSUE TITLE
[Android] Brave unsupported for adding PWA

### ISSUE THREAD

**Issue by wwwizzarrdry** [brave/brave-browser#10249]
Brave will allow you to add some websites to your home screen.

Eg. https://mobile.twitter.com/home
In the settings where it normally says, "Add to Home screen", it just says "Open Twitter".
If you tap, " Open Twitter", a dialog opens which asks you to select a supported browser from a list of I stalled browsers on your device. You can see in the screenshots that Brave is included in the list, but it is disabled and it says "Unsupported".

Screenshots:
https://imgur.com/a/So38JOB

**Comment by srirambv** [comment]
Please use the template when logging issues. Filling the template gives enough info to troubleshoot. Please add the device details and the Brave version you are running without those details its impossible to troubleshoot any issues.

**Comment by wwwizzarrdry** [comment]
> Please use the template when logging issues. Filling the template gives enough info to troubleshoot. Please add the device details and the Brave version you are running without those details its impossible to troubleshoot any issues.

Pretty straight forward. If you think this is "impossible to reproduce" with the information I've given, including screenshots, then we have bigger problems...

Just open Brave on any phone you have lying around try to add various websites to your home screen. Some work and some say "Brave is not supported". It's very easy to test.
