### ISSUE TITLE
[Android] Ads on YT

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#10241]
## Description 
There are ads on YT sometimes, we need to inject that script to prevent them
`(function() {
    const prunePaths = ['playerResponse.adPlacements', 'playerResponse.playerAds', 'adPlacements', 'playerAds'];
    const findOwner = function(root, path) {
        let owner = root;
        let chain = path;
        for (;;) {
            if ( owner instanceof Object === false ) { return; }
            const pos = chain.indexOf('.');
            if ( pos === -1 ) {
                return owner.hasOwnProperty(chain)? [ owner, chain ]: undefined;
            }
            const prop = chain.slice(0, pos);
            if ( owner.hasOwnProperty(prop) === false ) { return; }
            owner = owner[prop];
            chain = chain.slice(pos + 1);
        }
    };
    JSON.parse = new Proxy(JSON.parse, {
        apply: function() {
            const r = Reflect.apply(...arguments);
            for ( const path of prunePaths ) {
                const details = findOwner(r, path);
                if ( details !== undefined ) {
                    delete details[0][details[1]];
                }
            }
            return r;
        },
    });
})();`

We need to do it in that place
https://github.com/brave/brave-core/blob/master/browser/android/preferences/background_video_playback_tab_helper.cc

## Steps to reproduce 

Unfortunately I haven't found any video with ads before the fix. Maybe @antonok-edm has ideas on how to verify it properly.
Background video playback functionality should be also checked as there were modifications in that place. 

## Actual result 
Users complain about ads on YouTube

## Expected result
No ads on YouTube

## Issue reproduces how often 
No steps to reproduce

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Unknown, most likely yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by antonok-edm** [comment]
> Unfortunately I haven't found any video with ads before the fix. Maybe @antonok-edm has ideas on how to verify it properly.

I haven't seen any either, unfortunately.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9 running 1.10.95
- Verified playing random videos on YT didn't show any ads (skippable and non-skippable) 
- Verified searching for videos and playing them doesn't show any ads 
- Verified visiting a publisher account and playing videos from their list doesn't show any ads
