### ISSUE TITLE
Suggested sites are still shown even with setting off

### ISSUE THREAD

**Issue by jlindgren90** [brave/brave-browser#10242]
## Description 
I have the setting "Show Brave suggested sites in autocomplete suggestions" turned off. Nevertheless, suggestions for websites that I have never visited show up when I begin typing in the address bar.

## Steps to Reproduce
   1. Turn off "Show Brave suggested sites in autocomplete suggestions"
   2. Begin typing in the address bar, e.g. type the letter "m"

## Actual result:
The drop-down list includes the suggestion "gmail.com" even though I have never visited that site in Brave.

## Expected result:
The drop-down list includes only sites from history and bookmarks, and does not suggest sites I've never visited.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave	1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	Linux
JavaScript	V8 8.1.307.32
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line	/opt/brave.com/brave/brave --force-device-scale-factor=1.25 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,VideoPlaybackQuality,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver --flag-switches-begin --disable-smooth-scrolling --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/john/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the dev channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@jlindgren90 Can you go into settings and disable 'Show top sites in autocomplete suggestions`. That's simply a list of the top 500 alexa sites to help with autocomplete. Turning that off will only then show history and bookmarks.

There's the setting for `Show autocomplete in address bar` and that's the setting for turning everything off.

**Comment by rebron** [comment]
We'll do a follow-up issue to add some more description to those specific settings. cc: @Brave-Matt

**Comment by jlindgren90** [comment]
@rebron That fixed it, thank you. I assumed that "top sites" meant *my* top sites (i.e. most-visited, like on the new tab page). Maybe the setting could be renamed to "Show Alexa 500 top sites in autocomplete suggestions".
