### ISSUE TITLE
[Desktop] Apple character  (U+F8FF) doesn't display properly on Mac

### ISSUE THREAD

**Issue by dentistformyeye** [brave/brave-browser#10255]
## Description
U+F8FF is a Private Use Area Unicode character. This displays as a question mark in a diamond instead of an apple  symbol in the address bar and tab descriptions (e.g. when I search the character with my search engine). The apple character displays correctly on webpages.

## Steps to Reproduce

   1. On a Mac, use the U.S. keyboard input source.
   2. Open Brave.
   3. In the omnibox bar, type option-shift-K.
   4. [Optional] Type option-shift-K into DuckDuckGo and [search](https://duckduckgo.com/?q=%EF%A3%BF&ia=web)

## Actual result:
Step 3, omnibox:
![image](https://user-images.githubusercontent.com/51429646/84615828-0a57a700-ae98-11ea-82f7-469adb187b31.png)
Step 4, tab:
![image](https://user-images.githubusercontent.com/51429646/84615850-19d6f000-ae98-11ea-9c5f-07329f77f0c9.png)

## Expected result:
(This is a different Chromium browser, so ignore the different tab color.)
Step 3, omnibox:
![image](https://user-images.githubusercontent.com/51429646/84615796-f2802300-ae97-11ea-8219-7e8437d15611.png)
Step 4, tab:
![image](https://user-images.githubusercontent.com/51429646/84615912-4b4fbb80-ae98-11ea-9602-fb0e5da565e6.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.4 (Build 19E266)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Haven't tried.
- Can you reproduce this issue with the dev channel? Haven't tried.
- Can you reproduce this issue with the nightly channel? Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A.
- Is the issue reproducible on the latest version of Chrome? Don't have Chrome.

## Miscellaneous Information:
I first encountered the bug in Brave Desktop version 1.8.96.

**Comment by rebron** [comment]
Hi @dentistformyeye. This issue reproduces in Chrome. We'll wait for an upstream fix for it.

**Comment by dentistformyeye** [comment]
This seems to have been fixed as of Brave 1.33.106 (Chromium 96.0.4664.110), at least on macOS version 12.1.
