### ISSUE TITLE
[Desktop] Add keying for bravesoftware.com

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10253]
## Description 
We reach out to bravesoftware domains like tor.bravesoftware.com on launch. Add keying for these domains.

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/5839

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5839
* Confirmed using Fiddler that I do not see `BraveServiceKey` header using 1.11.104
* Confirmed using Fiddler that I do see `BraveServiceKey` header using 1.12.x

-------
