### ISSUE TITLE
[Desktop] Stop retrying if AC or rewards was turn off

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10257]
Right now we check if AC is off only when we start AC process. We should check if AC is off when doing retries as well. We should also check if rewards is off as well.

**Comment by mandar-brave** [comment]
@NejcZdovc to add to the issue; Monthly contributions should also be turned off immediately when the BR, or M Contributions switch is turned off.

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc @mandar-brave If I follow the steps from https://github.com/brave/brave-core/pull/5900#issue-436539253 and then turn ON the AC again, should it retry AC? (if wallet balance is sufficient)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.12.81 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.15.5 (Build 19F101)
```

Basically ran through the cases that @LaurenWags and @GeetaSarvadnya provided via https://github.com/brave/brave-core/pull/5900#issuecomment-651624999.

**`Test Case #1`** (multiple verified publishers in the a-c table using UGP grant)

* launched using `--enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/bat-native-ledger/*"=6 --rewards=staging=true,reconcile-interval=6,short-retries=true`
* enabled rewards and claimed a UGP of 30 BAT
* added three verified publishers into the a-c table before `reconcile-interval=6`

Disabled a-c via `brave://rewards` and closed the browser once the a-c process started as per the following:

```
[19483:775:0709/181922.512886:VERBOSE1:contribution.cc(167)] Staring monthly contribution
[19483:775:0709/181922.515037:VERBOSE1:contribution_ac.cc(32)] Starting auto contribution
```

<img width="1148" alt="Screen Shot 2020-07-09 at 6 23 12 PM" src="https://user-images.githubusercontent.com/2602313/87114409-85657080-c23e-11ea-94fe-b7449140ee99.png">

* ensured `contribution_info`, `contribution_info_publisher` and `unblinded_tokens` tables had the correct information/values
* ensured you can send a tip once the a-c as been interrupted/completed

**`Test Case #2`** (multiple verified publishers in the a-c table using KYC wallet)

* launched using `--enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/bat-native-ledger/*"=6 --rewards=staging=true,reconcile-interval=6,short-retries=true`
* enabled rewards and logged into a KYC account which had `15 BAT`
* added three verified publishers into the a-c table before `reconcile-interval=6`

Disabled a-c via `brave://rewards` and closed the browser once the a-c process started as per the following:

```
[20500:775:0710/000612.454295:VERBOSE1:contribution.cc(170)] Staring monthly contribution
[20500:775:0710/000612.457081:VERBOSE1:contribution_ac.cc(33)] Starting auto contribution
```

<img width="1296" alt="Screen Shot 2020-07-10 at 12 08 36 AM" src="https://user-images.githubusercontent.com/2602313/87115623-c9a64000-c241-11ea-8ce2-060994d2b4b5.png">

* ensured `contribution_info`, `contribution_info_publisher` and `unblinded_tokens` tables had the correct information/values
* ensured you can send a tip once the a-c as been interrupted/completed
* Note, full monthly budget was deducted from balance, this is expected per discussions: https://bravesoftware.slack.com/archives/CB0KCRCQN/p1593520104213200?thread_ts=1593519527.212600&cid=CB0KCRCQN and occurs when wallet is a restored anon wallet as well.

**`Test Case #3`** (multiple verified publishers in the a-c table using anon wallet)

* launched using `--enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/bat-native-ledger/*"=6 --rewards=staging=true,reconcile-interval=6,short-retries=true`
* enabled rewards and restored an anon wallet
* added three verified publishers into the a-c table before `reconcile-interval=6`

Disabled a-c via `brave://rewards` and closed the browser once the a-c process started as per the following:

```
[20698:775:0710/002037.564818:VERBOSE1:contribution.cc(170)] Staring monthly contribution
[20698:775:0710/002037.566922:VERBOSE1:contribution_ac.cc(33)] Starting auto contribution
```

<img width="1250" alt="Screen Shot 2020-07-10 at 12 21 38 AM" src="https://user-images.githubusercontent.com/2602313/87116395-b300e880-c243-11ea-8691-28a498037fc5.png">

```
[20698:775:0710/002037.564818:VERBOSE1:contribution.cc(170)] Staring monthly contribution
[20698:775:0710/002037.566922:VERBOSE1:contribution_ac.cc(33)] Starting auto contribution
```

* ensured `contribution_info`, `contribution_info_publisher` and `unblinded_tokens` tables had the correct information/values
* ensured you can send a tip once the a-c as been interrupted/completed

**`Test Case #4`** (multiple verified publishers + recurring tips using UGP grant)

* launched using `--enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/bat-native-ledger/*"=6 --rewards=staging=true,reconcile-interval=6,short-retries=true`
* enabled rewards and claimed a UGP of 30 BAT
* added four verified publishers into the a-c table and three recurring tips before `reconcile-interval=6`

Disabled a-c via `brave://rewards` and closed the browser once the a-c process started as per the following:

```
[20860:775:0710/003443.379377:VERBOSE1:contribution.cc(170)] Staring monthly contribution
[20860:775:0710/003443.382980:VERBOSE1:contribution_ac.cc(33)] Starting auto contribution
[20860:775:0710/003445.398179:VERBOSE1:contribution.cc(400)] Creating contribution(blinded) for 0 type RewardsType::RECURRING_TIP
```

<img width="753" alt="Screen Shot 2020-07-10 at 12 36 04 AM" src="https://user-images.githubusercontent.com/2602313/87118985-c82d4580-c24a-11ea-9180-d4fabdd46368.png">

* ensured `contribution_info`, `contribution_info_publisher` and `unblinded_tokens` tables had the correct information/values
* ensured that the recurring tips completed once the browser was restarted and a-c didn't complete
* ensured you can send a tip once the a-c as been interrupted/completed
