### ISSUE TITLE
[Desktop] Saved passwords are lost

### ISSUE THREAD

**Issue by maslalo** [brave/brave-browser#10250]
Hi, 
Some days ago brave started losing session passwords. When I save login data in password manager, auto log in password works, but after PC restart all passwords are lost. 
Clear passwords and other sign in data on exit is not checked.

**Comment by zatt** [comment]
My passwords are all gone after PC restart. Please, please someone help me get them back :(

Brave 1.11.97 on Windows 10

**Comment by rebron** [comment]
cc: @simonhong

**Comment by rebron** [comment]
Related issue: #3196

**Comment by simonhong** [comment]
I think this issue seems login db was corrupted while PC restarting whereas #3196 was due to using different device's login db.

**Comment by bsclifton** [comment]
It would be helpful to know if the entries are in the database? or if the database was deleted/recreated. If someone hits this problem again, I would recommend downloading/installing DB browser for SQLite
https://sqlitebrowser.org/

You can then check out the passwords in your profile directory:
`<PROFILE-DIRECTORY>/Login Data`

Sometimes, Chromium will make a backup of the corrupt DB. You might be able to find it with a name like:
`<PROFILE-DIRECTORY>/Default/._Login Data`

I'll close the issue for now - but let's try the above if this happens to someone
