### ISSUE TITLE
[Desktop] Do not proxy downloads for widevine

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10269]
## Description 
Downloads for widevine should not be proxied, it should directly reach out to *.gvt1.com and *.dl.google.com domains.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5846 using clean profile
* Confirmed able to play videos on Netflix and bitmovin after Widevine was downloaded

<img width="1214" alt="Screen Shot 2020-06-17 at 10 18 03 AM" src="https://user-images.githubusercontent.com/28145373/84910292-b4942200-b084-11ea-8da5-2d1e6db51906.png">
