### ISSUE TITLE
[Desktop] Audio not playing on npr.org

### ISSUE THREAD

**Issue by coinzdude** [brave/brave-browser#10276]
## Description 
Windows 10, For Brave Full, or Nightly, Audio will not play for this content in page `https://www.npr.org/transcripts/875548066` 
with or without shields raised.

## Steps to Reproduce

   1. Visit page, try to hit play by "8 minute listen" and content will not stream
   2. This content plays fine in Chrome
   

## Actual result:
Audio content does not play

## Expected result:
Audio should play, as it does in Chrome.

## Reproduces how often: 
On demand

## Brave version (brave://version info)
Version 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
Version 1.12.25 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit)

## Version/Channel Information:
Issue on release and nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No

- Is the issue reproducible on the latest version of Chrome? 
No

![image](https://user-images.githubusercontent.com/58857646/84705842-083e2880-af2a-11ea-81a0-e8b9422db90e.png)

**Comment by cjwijtmans** [comment]
Audio doesnt play on some twitch, youtube , nor pronounciations on dictionary streams for me either. It only happens occasionally. I typically notice it when its a mobile stream so perhaps its a decoding issues? It works on edge.

**Comment by rebron** [comment]
@coinzdude Can you try with shields again and toggle just the Trackers and Ads blocked (called Cross Site Trackers in 1.10.x). When I toggle that on and off, it starts playing.

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Testing https://github.com/easylist/easylist/commit/ccb11ad464bcb660085d1ff0f42e8ba1a5bd1f0d

Give it 24-48hrs, and re-test. @cjwijtmans  Let me know if it helps.

**Comment by coinzdude** [comment]
With Version 1.12.25 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit), this audio plays with or without Shields.  Good job!

**Comment by bsclifton** [comment]
Sweet! Thanks for the update, @coinzdude 😄👍

**Comment by cjwijtmans** [comment]
This video has no sound for me, https://www.youtube.com/watch?v=no42Jy3tUZQ.
On Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

**Comment by coinzdude** [comment]
> This video has no sound for me, https://www.youtube.com/watch?v=no42Jy3tUZQ.
> On Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

I could hear audio with Version 1.12.42 Chromium: 83.0.4103.106 (Official Build) nightly (64-bit) (windows)

**Comment by ryanbr** [comment]
I just retested in Brave release, @cjwijtmans seems fine. Ensure the  tab isn't muted. If its still failing create a new issue report

**Comment by cjwijtmans** [comment]
> I just retested in Brave release, @cjwijtmans seems fine. Ensure the tab isn't muted. If its still failing create a new issue report

The tab is not muted. The video above still doesnt play audio for me, i am waiting for a new release update though to test again later.

**Comment by ryanbr** [comment]
From youtube, there is atleast 4 ways to adjust volumes:  (via windows volume, and Brave itself) Ensure all volume settings are set correctly

![youtube-soundcontrol](https://user-images.githubusercontent.com/1659004/86980376-c70f0080-c1d7-11ea-832f-fdbb814b840e.png)

**Comment by cjwijtmans** [comment]
> From youtube, there is atleast 4 ways to adjust volumes: (via windows volume, and Brave itself) Ensure all volume settings are set correctly
> 
> ![youtube-soundcontrol](https://user-images.githubusercontent.com/1659004/86980376-c70f0080-c1d7-11ea-832f-fdbb814b840e.png)

You know, your comments are kind of insulting towards me. Other youtube videos work fine ofcourse.

**Comment by ryanbr** [comment]
> You know, your comments are kind of insulting towards me. Other youtube videos work fine ofcourse.

No insulting, just making sure all the sounds settings are set correctly. We've had instances where some users accidentally set the windows volume to mute

**Comment by coinzdude** [comment]
yeah, don't be insulted... It's a good thing to check the basics and assume nothing

**Comment by cjwijtmans** [comment]
I know it was not meant that way but anyhow. The sound works with the new stable update, Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit).

**Comment by ryanbr** [comment]
Good to know everything is working now @cjwijtmans  :)
