### ISSUE TITLE
Brave components don't actually update until restart

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#10271]
## Description 

Brave components under brave://components do not get updated/reloaded without browser restart.

Updating works correctly when browser is restarted.

## Steps to Reproduce

Tested with SpeedReader component:

   1. Launch the browser. Must be running before step 2. To use `dev` package version launch browser with `--use-dev-goupdater-url` flag, for logging `--enable-logging=stderr --v=0 --vmodule=brave_component=2`
Log should include approximately (version and timestamps would be different)
```
[49382:775:0615/130941.415990:ERROR:brave_component.cc(56)] component updated: {
   "data_file_version": "1",
   "description": "Brave SpeedReader Updater extension",
   "key": "...",
   "manifest_version": 2,
   "name": "Brave SpeedReader Updater",
   "version": "1.0.2"
}
```
   2. Publish a new component package via crx-packager (to publish `dev` version use https://ci.brave.com/view/all/job/brave-core-ext-speedreader-data-files-update-publish-dev/ > Build With Parameters > Build)
   3. Under brave://components after a while click “Check for update” for the component. It should pick up the update, update the version number and show good status
   4. New record for the same component with a higher version does not appear in logs

## Actual result:

`OnComponentReady` inherited from `BraveComponent` does not get called when component gets updated without browser restart.

In the case of Speedreader, rewriting rules do not get updated.

brave://components shows correct component version and status.

## Expected result:

`OnComponentReady` inherited from `BraveComponent` should get called when component gets updated via brave://components

In the case of Speedreader, rewriting rules should get updated and active without browser restart.

There should be two copies of log records similar to

```
[49382:775:0615/130941.415990:ERROR:brave_component.cc(56)] component updated: {
   "data_file_version": "1",
   "description": "Brave SpeedReader Updater extension",
   "key": "...",
   "manifest_version": 2,
   "name": "Brave SpeedReader Updater",
   "version": "1.0.2"
}
```

without a browser restart and with different version numbers

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.12.14 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.12.47 Chromium: 83.0.4103.116 (Official Build) nightly (64-bit)
--- | ---
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.15.5 (Build 19F101)
```

* launched using `/Applications/Brave\ Browser\ Nightly.app/Contents/MacOS/Brave\ Browser\ Nightly --enable-logging=stderr --v=0 --vmodule=brave_component=2 --use-dev-goupdater-url`

```
[51766:775:0624/001524.487341:VERBOSE2:brave_component.cc(59)] component ready: {
   "data_file_version": "1",
   "description": "Brave SpeedReader Updater extension",
   "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3j/+grwCsrYVA99oDHa+E9z5edPIV3J+lzld3X7K8wfJXbSauGf2DSxW0UEh+MqkkcIK/66Kkd4veuWqnUCAGXUzrHVy/N6kksDkrScOlpKT9zfyIvLc/4nmiyPCSc5c7UrDVUwZnIUBBpEHiwkpiM4pujeJkZSl5783RWIDRN92GDBdHMdD97JH3bPp3SCTmfAAHzzYUAHUSrOAfodD8qWkfWT19VigseIqwK6dH30uFgaZIOwU9uJV2Ts/TDEddNv8eV7XbwQdL1HUEoFj+RXDq1CuQJjvQdc7YRmy0WGV0GIXu0lAFOQ6D/Z/rjtOe//2uc4zIkviMcUlrvHaJwIDAQAB",
   "manifest_version": 2,
   "name": "Brave SpeedReader Updater",
   "version": "1.0.7"
}
```

* published new component via https://ci.brave.com/view/all/job/brave-core-ext-speedreader-data-files-update-publish-dev/7/
* waited ~20min and pulled new component via `brave://components`

```
[51766:775:0624/003721.945069:VERBOSE2:brave_component.cc(59)] component ready: {
   "data_file_version": "1",
   "description": "Brave SpeedReader Updater extension",
   "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3j/+grwCsrYVA99oDHa+E9z5edPIV3J+lzld3X7K8wfJXbSauGf2DSxW0UEh+MqkkcIK/66Kkd4veuWqnUCAGXUzrHVy/N6kksDkrScOlpKT9zfyIvLc/4nmiyPCSc5c7UrDVUwZnIUBBpEHiwkpiM4pujeJkZSl5783RWIDRN92GDBdHMdD97JH3bPp3SCTmfAAHzzYUAHUSrOAfodD8qWkfWT19VigseIqwK6dH30uFgaZIOwU9uJV2Ts/TDEddNv8eV7XbwQdL1HUEoFj+RXDq1CuQJjvQdc7YRmy0WGV0GIXu0lAFOQ6D/Z/rjtOe//2uc4zIkviMcUlrvHaJwIDAQAB",
   "manifest_version": 2,
   "name": "Brave SpeedReader Updater",
   "version": "1.0.8"
}
```

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.15.5 (Build 19F101)
```

Launched `1.11.92 CR: 84.0.4147.68` and ensured the following component was downloaded:

```
[14686:775:0709/005734.924394:VERBOSE2:brave_component.cc(59)] component ready: {
   "data_file_version": "1",
   "description": "Brave SpeedReader Updater extension",
   "key": "...",
   "manifest_version": 2,
   "name": "Brave SpeedReader Updater",
   "version": "1.0.11"
}
```

Updated the component via https://ci.brave.com/view/all/job/brave-core-ext-speedreader-data-files-update-publish-dev/11/ and waited ~10min. Went into `brave://components` and updated `Brave SpeedReader Updater` as per the following:

```
[14686:775:0709/013055.661526:VERBOSE2:brave_component.cc(59)] component ready: {
   "data_file_version": "1",
   "description": "Brave SpeedReader Updater extension",
   "key": "...",
   "manifest_version": 2,
   "name": "Brave SpeedReader Updater",
   "version": "1.0.12"
}
```
