### ISSUE TITLE
[Desktop] Set the updater endpoint at build time

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10279]
## Description 
Use npm config to set the `updater` config at build time. 

## Test Plan
Specified here: https://github.com/brave/brave-browser/pull/10281

**Comment by LaurenWags** [comment]
Labeling as `QA/Blocked` as I've requested test plan clarification from @jumde

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-browser/pull/10281
* Using production go-updater:
<img width="844" alt="Screen Shot 2020-07-29 at 3 34 29 PM" src="https://user-images.githubusercontent.com/28145373/88845662-7aa15a00-d1b2-11ea-9670-f6c1f6722218.png">

* Using dev go-updater:
<img width="905" alt="Screen Shot 2020-07-29 at 3 42 01 PM" src="https://user-images.githubusercontent.com/28145373/88845658-79702d00-d1b2-11ea-9dbd-cf0e8d90404a.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the test plan from https://github.com/brave/brave-browser/pull/10281
- Ensured that the following components download successfully in brave://components 
   - Brave Local Data Update
   - Brave Ad Block Updater
   - Brave Tor Client Updater (Mac/Win/Linux)
   - NTP Sponsored Images (US)
   - Brave SpeedReader Updater
   - Brave HTTPS Everywhere Updater
   - CRLSets
![image](https://user-images.githubusercontent.com/38657976/88898285-1e017600-d26a-11ea-8b77-4a045b8aca0c.png)

**with --use-dev-goupdater-url**
- Ensured that the above components download successfully in brave://components
