### ISSUE TITLE
Desktop - Download background images via CRX

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#10278]
## Description
Idea would be to use CRX packaging (ex: component registered with Component Updater; downloaded at run time) to download background images used in the New Tab Page.

Including all of these images increases the size of the APK (Android) and also makes updating of images harder (need to make code change + push). If separated, the initial download would be smaller and then the images themselves could be updated without a product change

cc: @rebron @anthonypkeane @SergeyZhukovsky

**Comment by karenkliu** [comment]
Is there any update on this issue? The rest of the new wallpapers from 2020 are getting held up.

**Comment by bsclifton** [comment]
Update - the packaging portion of this was separated into the following issue:
https://github.com/brave/brave-browser/issues/14797

The remaining work would be to integrate with this component for Desktop/Android 😄 It would reduce the APK size quite a bit (Android) and also reduce the size of the Desktop installer

**Comment by bsclifton** [comment]
When we do the integration, here are the params we'll need to pass to component updater:
- publicKey: `MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4L9XGAiVhCL8oi5aQhFrVllsw6VebXigTj5ow3e0fYeEztjM9FOgqMD6pl0AB8u05xKUPcdpIZqCguEzXyXh5vn+BWoEGtVezEEfjd33T4drJAYwEBvgWcFVVLNWku1/53f6TZp8IiiaOhKIANUtn/Zvw/0nUYa10nwxK4P3he4Ahj0CO6HVeu9zNRCdZFSkYdMnPnNYTU+qN88OT1DBsV1xQgd3qK+MkzPDF1okHi9a+IXiHa3FVY++QmtSrMgetJnS/qBt6VsZcejcQCd1KIpgHNyoVl5rodtBRj25o48SxYePrssMRTv9vAQmRUZZukOIL/HdeqjCHIOSQTrFEQIDAQAB`
- componentID: `aoojcmojmmcbpfgoecoadbdpnagfchel`

**Comment by bsclifton** [comment]
We'll want to keep one image in here as a default - so that while CRX downloads we can show something

@karenkliu @jamesmudgett any recommendations on which to include?

**Comment by karenkliu** [comment]
@bsclifton Let's use `spencer-moore_lake` 
<img width="231" alt="Screen Shot 2021-03-24 at 6 55 25 PM" src="https://user-images.githubusercontent.com/2388823/112406989-7f32f980-8cd2-11eb-8308-13b24bd0049c.png">

It has the 3rd-lowest file size out of our current wallpaper batch. (First one features Japan which might be confusing as a first run and 2nd-lowest is too moody for first run).

**Comment by bsclifton** [comment]
Android completed with https://github.com/brave/brave-core/pull/9635 (fixing https://github.com/brave/brave-browser/issues/17328)

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.33.51 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)


### Steps:
1. new profile
2. launched Brave
3. loaded `brave://components/`
4. confirmed `**NTP Background Images** - Version: 1.0.4` was listed as `Up-to-date`
5. opened a new-tab page
6. confirmed round of new background images
7. clicked on `Customize` at the bottom of the new-tab page
8. toggled `Show Background Images` to `Off`
9. confirmed I got a color-gradient background, instead
10. toggled `Show Sponsored Images` to `Off`
11. confirmed opening new-tab pages didn't show me any sponsored-image ads
12. toggled `Show Sponsored Images` and `Show Background Images` back to `On`
13. confirmed I saw both sponsored images and background images

NOTE: https://github.com/brave/brave-browser/issues/16309 covers the `Show Sponsored Images` toggle not behaving correctly.

example | example | example | example | example | example | example
---------|----------|---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2021-11-02 at 7 37 08 AM" src="https://user-images.githubusercontent.com/387249/139871964-2d3944e9-3261-4594-9f5f-9fcb53b8da20.png"> |  <img width="1457" alt="Screen Shot 2021-11-02 at 7 43 55 AM" src="https://user-images.githubusercontent.com/387249/139872108-8113d4eb-057b-42ea-b6ee-f9e6c1066d4b.png"> | <img width="1457" alt="Screen Shot 2021-11-02 at 7 43 05 AM" src="https://user-images.githubusercontent.com/387249/139872357-0c25ce3f-8e22-4460-ac3d-db601ae98f1a.png"> | <img width="1457" alt="Screen Shot 2021-11-02 at 7 43 25 AM" src="https://user-images.githubusercontent.com/387249/139872721-b59ab4dc-ac43-4998-a342-74c185c17291.png"> | <img width="1507" alt="Screen Shot 2021-11-02 at 8 04 57 AM" src="https://user-images.githubusercontent.com/387249/139873751-9328b197-c8a7-43f6-8833-fdc7e81e4f42.png"> | <img width="1507" alt="Screen Shot 2021-11-02 at 8 05 04 AM" src="https://user-images.githubusercontent.com/387249/139873757-02e687d7-73f6-4977-a1ce-af23cd3cd845.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 7 41 44 AM" src="https://user-images.githubusercontent.com/387249/139874054-2e9fbcc0-c0fb-4b28-b4a7-b8ff7426037b.png">
