### ISSUE TITLE
[Desktop] add info to DB and brave://rewards-internals on why AC failed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10274]
## Description 

While discussing https://github.com/brave/brave-browser/issues/10257 in Rewards/Ads mtg, it came up that it might be a good idea to include info in the database and/or brave://rewards-internals about why auto contribute fails (ex. it was started but toggled off so it was stopped or it hit retries limit, etc).

## Steps to Reproduce

TBD

## Actual result:

currently no diagnostic info to explain why AC fails

## Expected result:
Have info in db and/or brave://rewards to explain why AC fails

## Reproduces how often: 

easily

## Brave version (brave://version info)

all

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
this is already supported
