### ISSUE TITLE
[Desktop] Site settings isn't retained

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10285]
## Description 

Site settings isn't retained

## Steps to Reproduce

   1. Set FP to strict in global settings
   2. Visit YT and change FP setting to standard
   3. Page reloads but settings is retained to strict
   4. Change FP to allow, page reloads and retains settings
   5. Change FP to standard from allow, sets it to strict

## Actual result:

![site-shields-settings](https://user-images.githubusercontent.com/17010094/84731570-e048d680-afb6-11ea-8e5c-56f15f4fbc7d.gif)

## Expected result:
Site settings should override global settings and retain

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.12.25 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?  NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/uplift-approvers  when fixed should be uplifted to beta

**Comment by simonhong** [comment]
When global FP is set to strict, site settings are not stored at all. So, site settings has always strict.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.84 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description on a clean profile. Confirmed working as expected. Confirmed able to change from Strict > Standard or Allow > Standard and setting was retained on page reload. 
* Reproduced the issue using 1.11.82 (Dev). Updated to 1.11.84 and confirmed working as expected.
