### ISSUE TITLE
[Desktop] Fix crowd-deny updates

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10280]
## Description 
Crowd deny updates/installs fails on latest nightly

## Steps to Reproduce

   1. Open Brave Browser with new profile
   2. Navigate to brave://components
   3. Check crowd deny

## Actual result:
Crowd deny doesn't update

## Expected result:
Crowd deny should update

## Reproduces how often: 

Easily

## Brave version (brave://version info)
1.12.25 Chromium: 83.0.4103.97 

## Version/Channel Information:
Nightly

**Comment by rebron** [comment]
@jumde is this still an issue? I checked 1.12.108 and latest nightly and it looks like Crowd Deny updates when I manually select check for update.

**Comment by mherrmann** [comment]
@rebron I think the problem appears on automatic updates when you navigate to `brave://components` and wait for 60 seconds. See #10464.

**Comment by mherrmann** [comment]
@jumde in current versions of Brave, Crowd Deny is not installed. (It's only registered, then remains at `0.0.0.0` forever until a user happens to "check for an update" for this particular component.) Per #8709, I would remove Crowd Deny from brave://components. Do you agree with this?

**Comment by jumde** [comment]
@mihaiplesa @mherrmann - As I understand `Crowd Deny` is not fixed given it is in the list of `blacklisted components` - https://github.com/brave/brave-core/blob/5709a5804cf3c0f3f96e6c250fcb34c666d75717/chromium_src/components/component_updater/component_installer.cc#L26 - Can we re-open this issue?

**Comment by mherrmann** [comment]
@jumde it depends what you mean by "fixed". Per my [comment above](https://github.com/brave/brave-browser/issues/10280#issuecomment-738605278) I've added Crowd Deny to the list of blacklisted components to remove it. This "fixes" this issue in the sense that there is no longer an update error for crowd deny. But from what you wrote, it does not sound like that is the meaning of "fixed" you intended.

**Comment by mherrmann** [comment]
Further info: https://github.com/brave/brave-browser/issues/8709#issuecomment-737397247

**Comment by jumde** [comment]
I created a new issue to enable the component: https://github.com/brave/brave-browser/issues/13426

**Comment by LaurenWags** [comment]
Labeling as `QA/Blocked` - questions sent to @jumde 👍🏻
