### ISSUE TITLE
Extension popups have a white strip at the top and bottom

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#1028]
## Description 
There is a white strip at the top of popups for extensions (including the Brave shields panel extension).

## Steps to Reproduce
   1. Open a new tab and navigate to any website.
   2. Click the Brave shields button.

## Actual result:
![](https://user-images.githubusercontent.com/19424103/45236848-a9527680-b2a2-11e8-9a71-af170ba9adff.png)

Also occurs with third-party extensions like Bitwarden:
![](https://user-images.githubusercontent.com/19424103/45236913-e1f25000-b2a2-11e8-80de-fa8f4bb5204e.png)

## Expected result:
There should not be a white strip.

## Reproduces how often: 
Always.

## Brave version (about:brave info) 
Version 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

### Reproducible on current release:
No.

**Comment by srirambv** [comment]
This is not an issue on Linux. Its definitely an issue on Windows. 
![image](https://user-images.githubusercontent.com/17010094/45254280-c723e800-b343-11e8-930c-530d230bdc8e.png)

@Liunkae  the screenshots you posted is it from macOS ?

**Comment by Liunkae** [comment]
@srirambv Yes, macOS 10.13.

**Comment by Liunkae** [comment]
Maybe related:
If you click the ad/trackers blocked label to show the URLs, there is a white strip on the right (scrollbar placeholder?).
![](https://user-images.githubusercontent.com/19424103/45257798-84790480-b371-11e8-9a5e-4b3abd2ce1d6.png)

**Comment by srirambv** [comment]
The extra padding when showing blocked items is tracked here https://github.com/brave/brave-browser/issues/771

**Comment by petemill** [comment]
I think this is a chromium bug that is now fixed. We should check against latest chromium rebase https://bugs.chromium.org/p/chromium/issues/detail?id=849802

**Comment by petemill** [comment]
This is actually sort of by-design in Chromium, and like this in the current version.

I believe it's due to not being able to support rounded corners on web content in Windows and macOS. The border radius was reduced as to not make it so apparent, but it's still an eyesore IMO. We should consider removing border radius entirely if the fix is too difficult.

![image](https://user-images.githubusercontent.com/741836/45996596-92a57100-c051-11e8-85f3-4797a2932836.png)

**Comment by rebron** [comment]
This issue will impact shields style update https://github.com/brave/brave-browser/issues/1339
yes?

**Comment by srirambv** [comment]
+1 from @echosa for Brave rewards via #1554 
![image](https://user-images.githubusercontent.com/17010094/46880871-dea93180-ce17-11e8-916d-c8ed4a4fae1b.png)
