### ISSUE TITLE
"Show all" not visible on download bar using dark/default theme

### ISSUE THREAD

**Issue by eljuno** [brave/brave-browser#1029]
_Have you searched for similar issues? Before submitting this issue, please check the open issues and add a note before logging a new issue._ 

Yes

## Description 

"Show all" at download bar not visible when using dark/default theme. It shows properly with light theme.

## Steps to Reproduce

   1. Set Brave to dark theme at chrome://settings. Or use default theme (which also use dark theme).
   2. Try download any file from any site. When download bar appears, "Show all" not visible.
   3. Set Brave to light theme at chrome://settings.
   4. Try download any file from any site. "Show all" appears at download bar.

## Actual result:

Dark/default theme

![show-all-downloads](https://user-images.githubusercontent.com/25360853/45243935-cc6f3b80-b31f-11e8-9ccc-e553a17431be.png)

Light theme

![show-all-downloads-light](https://user-images.githubusercontent.com/25360853/45243956-e1e46580-b31f-11e8-8c2b-f6d52775cb1d.png)

## Expected result:
Text should visible when using dark theme

## Reproduces how often: 

Easily

## Brave version (about:brave info) 

Brave 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
Windows 8.1

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
This is fixed in next update
![image](https://user-images.githubusercontent.com/17010094/45244757-3ad3df80-b2c7-11e8-855e-1e39e74702f5.png)
