### ISSUE TITLE
[Desktop] `Customized Dashboard` settings tool tip is shown outside the modal popup

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10299]
## Description 

Found while testing #9455
`Customized Dashboard` settings tool tip is shown outside the modal popup

## Steps to Reproduce

   1. Clean profile 1.11.x
   2. Open a NTP and click on `Customized Dashboard` settings
   3. Mouse hover outside the `Customized Dashboard` settings modal popup
   4. `Customized Dashboard` settings tool tip is shown outside the modal popup
   
  
**Note**: when modal popup is open, mouse over on the bottom right corner icons (Bookmarks, Preferences and History) also shows `Customized Dashboard` settings tool tip

## Actual result:

`Customized Dashboard` settings tool tip is shown outside the modal popup
![image](https://user-images.githubusercontent.com/38657976/84770286-e2ca2100-aff4-11ea-809c-2744dbcdc367.png)

![image](https://user-images.githubusercontent.com/38657976/84770428-29b81680-aff5-11ea-9815-0df44ffd799e.png)

![image](https://user-images.githubusercontent.com/38657976/84771837-ac41d580-aff7-11ea-9fbe-7311097d2e81.png)

## Expected result:

`Customized Dashboard` settings tool tip should not be shown outside the modal popup
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.11.65 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS Version 1903 (Build 18362.30)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @karenkliu

**Comment by rebron** [comment]
cc: @ryanml Note priority though.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.17.42 Chromium: 86.0.4240.99 (Official Build) nightly (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Windows 10 OS Version 1903 (Build 18362.1082)


```
- Verified the STR from the description

![image](https://user-images.githubusercontent.com/38657976/96627074-f7fde600-132d-11eb-9be7-2807f5dfb84c.png)

- Verified on both clean and upgraded profiles
