### ISSUE TITLE
[Android] App crashes on opening new tab after disabling Custom Homepage theme

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#10296]
## Description 
- With bottom toolbar off, app shutdown on opening a new tab page

## Steps to reproduce 

   1. Install Brave from a referral URL associated with Custom Homepage
   2. Disable the theme in the setting (choose Brave default theme)
   2. Open a new tab page
   3. App crashes

## Actual result 
- App crash

## Expected result
- A new tab page should open 

## Issue reproduces how often 
- All the time

## Issue happens on 
   - Current Play Store version

## Device details
   - Install type (ARM, x86): Arm
   - Device (Phone, Tablet, Phablet): OnePlus 7T
   - Android version: Android 10 (Oxygen OS 10.0.9)
   
## Brave version
- 1.9.80

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards?

- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9 running 1.10.95 x64 RC build
- Verified SI tab doesn't cause crash on load
- Verified SI campaigns on multiple countries where its running and no crash
- Verified SR images doesn't cause crash when loading
- Logged https://github.com/brave/brave-browser/issues/10398 for SR as a followup to #10033
