### ISSUE TITLE
Importing from Chrome should work if Chrome is open when user initiates import

### ISSUE THREAD

**Issue by garrettr** [brave/brave-browser#103]
@darkdh suggests we prompt users to close Chrome if we detect that it is open after they initiate importing from Chrome.

Follow-up for https://github.com/brave/antimuon/pull/49#pullrequestreview-104304111.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
