### ISSUE TITLE
[Desktop] Crash in file IO on Windows browser shutdown

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#10304]
The original crash signature doesn't give much
```
`anonymous namespace'::ConstructTlsVector
‎C:\jenkins\x64-nightly\src\base\threading\thread_local_storage.cc:23
```

https://brave.sp.backtrace.io/p/brave/debug?time=quarter&filters=(_deleted%3D0%2Cptype%3Dbrowser%2C(ver%2Cregex%2C%228%5B1%7C2%7C3%7C4%5D.*%22))&fingerprint=cea913198ec15c8d4383f0168bb6868ff352512abbb23b7e86143cae301a6a14&debug=(%223b6f3%22,0,0)

but **probably** it  could be related to 
```
[ 00 ] 0x11dba10c
[ 01 ] base::ThreadLocalStorage::Slot::Set
[ 02 ] 0x1268dc15
[ 03 ] base::ScopedBlockingCall::ScopedBlockingCall
[ 04 ] base::File::Close
[ 05 ] base::File::~File
[ 06 ] 0x1597ab13
[ 07 ] 0x1597abf8
[ 08 ] 0x1597a95b
[ 09 ] 0x15978550
[ 10 ] 0x159785e0
[ 11 ] 0x159784d2
[ 12 ] 0x15978381
[ 13 ] 0x1596aec2
[ 14 ] 0x1596afa1
[ 15 ] 0x1596b014
[ 16 ] _LdrxCallInitRoutine@16
[ 17 ] LdrpCallInitRoutine
[ 18 ] LdrShutdownProcess
[ 19 ] RtlExitUserProcess
[ 20 ] _ExitProcessImplementation@4
[ 21 ] exit_or_terminate_process
```
https://brave.sp.backtrace.io/p/brave/debug?time=quarter&filters=(_deleted%3D0%2Cptype%3Dbrowser%2C(ver%2Cregex%2C%228%5B1%7C2%7C3%7C4%5D.*%22))&fingerprint=86691e23d259c361f001bbec364c3d20c05099c401a3ce98a278f906e3fd1291&debug=(%223b397%22,0,0)

or 

https://brave.sp.backtrace.io/p/brave/debug?time=quarter&filters=(_deleted%3D0%2Cptype%3Dbrowser%2C(ver%2Cregex%2C%228%5B1%7C2%7C3%7C4%5D.*%22))&fingerprint=323a24397f6c9bc53690f1385efd84f2958e8089157733cffe192e217c30a1b0&debug=(%223b062%22,0,0)

**Comment by iefremov** [comment]
cc @bsclifton

**Comment by kjozwiak** [comment]
@iefremov @tmancey @bridiver is there anything QA can do here in terms of verifcations?

**Comment by tmancey** [comment]
@kjozwiak I can confirm this crash has not occurred since this fix was merged. Thanks

**Comment by kjozwiak** [comment]
Thanks @tmancey 👍 Going to label this one as `QA/No` as there's no STR/Cases and you confirmed that it's been resolved.
