### ISSUE TITLE
[Desktop] Replace graphics on Make a call popup 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10308]
## Description 

 Replace graphics on Make a call popup 

## Steps to Reproduce

   1. Visit any page with a `tel:xxxxxx` link
   2. Click on the call button 
   3. See Chromium card with graphics

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/84795440-1e74e300-b015-11ea-903e-36942b7fe351.png)

## Expected result:
Should use custom graphics or no graphics

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.12.25 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel?  No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by rebron** [comment]
@karenkliu We could probably just remove this image altogether.

**Comment by karenkliu** [comment]
@rebron Not sure if we want to remove graphics on all the popups - I think they're helpful on some to distinguish visually its purpose. If we removed the graphics from all the popups it would be hard to tell them apart. 

@codybanxs created this graphic for us - think it'll work?

![image](https://user-images.githubusercontent.com/2388823/88595639-3a0dd900-d018-11ea-8893-e20b53fd8a78.png)

**Comment by rebron** [comment]
@karenkliu @codybanxs Fine to replace and that graphic looks good although I think we need it to fit dimensions that will work for here -> https://user-images.githubusercontent.com/17010094/84795440-1e74e300-b015-11ea-903e-36942b7fe351.png

**Comment by karenkliu** [comment]
@codybanxs can you come up with something that is a bit more horizontal?

**Comment by codybanxs** [comment]
@karenkliu @rebron I will work on a horizontal style graphic for this.

**Comment by rebron** [comment]
@srirambv Can you recheck? I think this is no longer valid now due to https://github.com/brave/brave-browser/issues/14601

**Comment by srirambv** [comment]
Yup this seems to be no longer valid. Closing the issue 
![image](https://user-images.githubusercontent.com/17010094/114967382-41a63400-9e6c-11eb-98d8-917ff599f11f.png)
