### ISSUE TITLE
Brave Rewards typo

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1030]
<img width="310" alt="screen shot 2018-09-07 at 3 35 12 pm" src="https://user-images.githubusercontent.com/639937/45246106-626d7c80-b2b4-11e8-9288-2e19273c0ace.png">
 "opt out *of* each"

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

<img width="311" alt="screen shot 2018-09-20 at 3 26 01 pm" src="https://user-images.githubusercontent.com/2602313/45842077-ab2c2900-bce9-11e8-8204-8de2d23b09bd.png">
