### ISSUE TITLE
[Desktop] Profile icon is missing (toolbar)

### ISSUE THREAD

**Issue by gsscoder** [brave/brave-browser#10300]
Profile icon is missing in the toolbar.

OS: **Windows 10**.

![brave-no-profileicon](https://user-images.githubusercontent.com/1194228/84774852-b0152e00-afde-11ea-94c7-7d8bd055359f.PNG)

Thanks for the project!

Giacomo S. S.

**Comment by rebron** [comment]
@gsscoder Do you have more than one profile? We're only displaying if you have more than one profile, otherwise it clutters up the toolbar. If you create a new profile in your menu to the right, you'll see it there.

**Comment by gsscoder** [comment]
@rebron, sorry for replying late. No I've just one profile. So it's correct, but on macOS laptop I'm sure I've one profile and the icon is displayed.
