### ISSUE TITLE
[Desktop] Global and site-specific shield settings are not retained correctly after upgrade to 1.11.x

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10303]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/9975
Global and site-specific shield settings are not retained correctly after upgrade to 1.11.x
## Steps to Reproduce

**Scenario 1:**
   1. Clean profile 1.10.x
   2. Open brave://settings/shields
   3. Change cookies settings to `Allow all cookies`
   4. Change Fingerprinting settings to `Allow all fingerprinting`
   5. Open buzzfeed.com and verify that global shield settings are retained correctly
   6. Upgrade profile to 1.11.x
   7. Open brave://settings/shields and verify that, global shield settings for Fingerprinting should be `Disabled` instead of `Standard` as FP is allowed in step 4
  8. Open buzzfeed.com and verify that, site shield settings for Fingerprinting should be `Allow all fingerprinting` instead of `Fingerprinting blocked (standard)`
   
**Scenario 2:**
   1. Clean profile 1.10.x
   2. Open brave://settings/shields
   3. Disable global setting `Block cross-site trackers` 
   4. Open Buzzfeed.com 
   5. Verify that global settings for `Block cross-site trackers` are retained for buzzfeed.com (expected)
   6. Upgrade to 1.11.x
   7. Open brave://settings/shields
   8. Verify that `Trackers and ad blocking` is set to `Standard` instead of `Disabled`

**Scenario 3:**
   1. Clean profile 1.10.x
   2. Open brave://settings/shields
   3. Change cookies settings to `Block all cookies`
   4. Change Fingerprinting settings to `Block all fingerprinting`
   5. Open Buzzfeed.com
   6. Verify that global shield setting for cookies and fingerprinting are retained for buzzfeed.com (expected)
   7. Upgrade to 1.11.x
   8. Open brave://settings/shields
   9. Verify that `Cookies blocking` is set to `All` as expected
   10. Verify that `Fingerprinting blocking` is set to `Standard` instead of  `Strict, may break sites`
   
 **Scenario 4:**
   1. Clean profile 1.10.x
   2. Open buzzfeed.com
   3. Change cookies site settings to `Allow all cookies` 
   4. Change Fingerprinting site settings to `Allow all fingerprinting`
   5. Upgrade to 1.11.x
   6. Visit buzzfeed.com, open shield and verify that `All cookies allowed` is shown as expected for cookies. Fingerprint settings is displayed as `Fingerprintblocked (standard)` instead of `Allow all fingerprinting`
  
   
## Actual result:

Global and site-specific shield settings are not retained correctly after upgrade to 1.11.x
**1.10.x**
Global shield settings
![image](https://user-images.githubusercontent.com/38657976/84785977-c4baeb80-b009-11ea-89d4-6b8aaed98835.png)
Site shiled settings
![image](https://user-images.githubusercontent.com/38657976/84786114-f16f0300-b009-11ea-98e9-2117bbf48787.png)

**Upgrade to 1.11.x**
Global shield settings for Fingerprinting should be `Disabled` instead of `Standard`
![image](https://user-images.githubusercontent.com/38657976/84786345-414dca00-b00a-11ea-83e7-369e02f88317.png)

Site shield settings for Fingerprinting should be `Allow all fingerprinting` instead of `Fingerprinting blocked (standard)`
![image](https://user-images.githubusercontent.com/38657976/84786426-62aeb600-b00a-11ea-9ae1-5eb2c94ed0ab.png)

## Expected result:
Global and site-specific shield settings should be retained correctly after upgrade to 1.11.x

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.11.65 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS Version 1903 (Build 18362.30)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @simonhong @karenkliu

**Comment by GeetaSarvadnya** [comment]
The PR https://github.com/brave/brave-core/pull/5879 may fix this issue. 
cc: @simonhong

**Comment by bridiver** [comment]
this is not a bug, it isn intentional behavior per @pes10k

**Comment by GeetaSarvadnya** [comment]
Closing the issue as per the above comments.
