### ISSUE TITLE
[Android] New design needed for tips details section on mobile

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10310]
## Description 
With 3 decimal values added to BAT balance the tips details section looks awfully styled. We should think of having a better way to display values in tips details section on Android. With smaller screen sizes it would look really bad

## Steps to reproduce 

   1. Tip a bunch of sites 
   2. Open Tips details section

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/84796434-3dc04000-b016-11ea-84a0-e3ac3842c371.png)

## Expected result
Something that doesn't look like in screenshot and looks a lot simpler and neat

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All supported versions
   
## Brave version
Release build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by bsclifton** [comment]
Will be addressed when we revisit https://github.com/brave/brave-browser/issues/10472
