### ISSUE TITLE
Cosmetic scriptlets not injected in iframes

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#10319]
Currently, scriptlet injections from 3rd party contexts (i.e., cosmetic rules of the form `##+js()`) are only injected into the top level frame of a website. This sometimes causes issues inside of 3rd-party iframes, such as youtube embedded players.

**Comment by bsclifton** [comment]
Labeled as P2 since this is causing ads to slip through for YouTube

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.10.95 Chromium: 83.0.4103.106 (Official Build) (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5878
* Reproduced the issue using `1.10.93` and test plan from PR. Using `1.10.93`, encountered 4 videos with unskippable ads on https://www.pcmag.com/news/the-best-vr-games-for-2019. When using `1.10.95` and the same article (both clean and upgrade profiles), no unskippable ads were encountered.
* Visited various articles linked from https://www.pcmag.com/news/ which contained embedded YT videos. Confirmed no unskippable ads were shown on the embedded YT videos (in contrast, `1.10.93` did have a few unskippable ads on some articles).
