### ISSUE TITLE
[Desktop] design updates to customize dialog follow up to #9455

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#10318]
## Description 

Design follow-up to #9455.

- [ ] ~Remove `Show` from the section title~ - moved to https://github.com/brave/brave-browser/issues/10591
- [ ] Remove blue focus border when selection is selected
- [ ] Remove alt text `Customize dashboard`
- [ ] Add scrim in the background (see design)
- [ ] Widget title, description and button text should all be Poppins
- [ ] Use `+` icon for `Add; button`
- [ ] Remove bottom margin for all sections, not just More cards
- [ ] Add missing widget stack icon
- [ ] Only show message when 5/5 of cards are used. 
- [ ] Use right opacity for card titles (see design)

## Design/Expected Result
![design_qa_2](https://user-images.githubusercontent.com/5951041/84834580-911a9a00-afe6-11ea-8a17-7b4ef367a33b.png)
![design_qa_3](https://user-images.githubusercontent.com/5951041/84834599-9f68b600-afe6-11ea-89a6-79b740b2358d.png)
![design_qa_4](https://user-images.githubusercontent.com/5951041/84834605-a394d380-afe6-11ea-94bb-9e77062b93a0.png)
![design_qa_5](https://user-images.githubusercontent.com/5951041/84834613-a7285a80-afe6-11ea-9aee-ee3c8bf97d7a.png)

## Reproduces how often: 

n/a

## Brave version (brave://version info)

Address fixes for Brave 1.11.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Thanks @karenkliu

**Comment by rebron** [comment]
@ryanml 1.13.x milestone right?
@karenkliu When you get a can you see if this all looks good to you? Can test in beta with 1.13.14 or higher or any Nightly build?

**Comment by karenkliu** [comment]
@rebron @ryanml We're still missing a couple design fixes from the first round:

![design QA 6](https://user-images.githubusercontent.com/2388823/89450148-ef264c80-d70e-11ea-83d6-9f29f4e881dc.png)
![design QA 7](https://user-images.githubusercontent.com/2388823/89450297-2d237080-d70f-11ea-8e85-394a18811b3d.png)

**Comment by ryanml** [comment]
@rebron yes `1.13` - I'll make the fixes @karenkliu mentioned here then uplift them

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
Revision	4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Per https://bravesoftware.slack.com/archives/CQUHQ0PM3/p1598038077005900?thread_ts=1598037921.005400&cid=CQUHQ0PM3, design changes have already been reviewed by @karenkliu

Spot checked some design elements that were listed in https://github.com/brave/brave-core/pull/6351#issuecomment-675076904 such as
 - confirmed that once the Customize modal is visible, that there's an overlay over the NTP that looks a bit darker to emphasis the Customize modal.
 - confirmed that clicking anywhere on the NTP page dismisses the Customize modal without issues
 - confirmed focus order uses Brave color (not blue)

Generally confirmed functionality of customize dashboard works
 - able to toggle items off/on via Customize Dashboard
 - confirmed these selections were reflected on brave://settings/newTab
 - confirmed able to toggle items from brave://settings/newTab and have the status reflected on Customize Dashboard
 - confirmed selections were retained on browser restart

Encountered https://github.com/brave/brave-browser/issues/11374

---------
