### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Zerocool-213** [brave/brave-browser#10321]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.90  Chromium: 83.0.4103.97
Operating System: Windows NT 10.0.18363

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/797a0000-1c55-8704-0000-000000000000

**Comment by bsclifton** [comment]
@Zerocool-213 thanks for reporting - the current recommendation is to turn off sync via brave://flags/#brave-sync, until Sync v2 arrives. If the browser crashes before that page can be loaded, you can launch Brave from command line using `--disable-sync` as a command line parameter and then disable sync via brave://flags/#brave-sync
