### ISSUE TITLE
Brave Ads category is missing for ad notifications on iOS

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#10322]
## Description 

Brave Ads category is missing for ad notifications on iOS. This issue does not affect desktop or Android.

## Steps to Reproduce

   1. View an ad

## Actual result:

Search for `Ad notification shown:` in console log. Category is blank on iOS

## Expected result:
Search for `Ad notification shown:` in console log. Category should reflect catalog segment

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description
* Confirmed `category` is not blank on desktop

```
[6118:775:0721/103233.916324:VERBOSE1:ads_impl.cc(1233)] Ad notification shown:
  uuid: 9a6d88da-9697-46bd-8f8a-168b2c3764e1
  parentUuid: 063b5536-f3b6-4f7f-a6b4-0197f0ffd5c0
  creativeInstanceId: fff195d2-969e-4109-9aa1-8d99e2176220
  creativeSetId: 44605a0a-0273-479d-be57-2c2c4af116cd
  category: technology & computing
  title: Chess.com
  body: Play and Learn Chess on the #1 Site. 
  targetUrl: https://www.chess.com/membership?ref_id=82426240
```

---------------
