### ISSUE TITLE
[Sync v2] Integrate chromium QR code generator

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#10335]
And pass the generated data to JS  for rendering so we can let mobile type to join sync chain by scanning the QR code

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verification passed on Brave Nightly v1.14.12 on Samsung s7 (Android 8.0)
Verification passed on Brave Nightly v1.14.12 on Samsung Galaxy Tab S5e (Android 9.0)

Verified test plan from https://github.com/brave/brave-core/pull/5926
I successfully added 2 devices through QR code from desktop
![image](https://user-images.githubusercontent.com/34715963/89458297-19a3f400-d767-11ea-8a87-12dec87ee011.png)
Verified that QR code is generated during Sync creation process
Verified that QR code is generated in `View Sync Code` after sync was created
Verified that QR code is generated in `Add New Device` after sync was created

Successfully synced 2 Android devices through QR code
