### ISSUE TITLE
[Sync v2] Encrypt DEVICE_INFO

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#10333]
In security review:
https://github.com/brave/security/issues/172#issuecomment-645030726

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5889

![image](https://user-images.githubusercontent.com/34715963/88722636-e12d6600-d127-11ea-9c5c-ecee4905828a.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.111 x64 build
- Verified `Device info` is listed under encryption types<br/>
   <img width=300 src=https://user-images.githubusercontent.com/17010094/89867329-f0d98f80-dba8-11ea-8f9f-05a29247059a.png>

------------

Verification passed on Samsung Tab A with Android 10 running 1.12.111 x64 build
- Verified `Device info` is listed under encryption types<br/>
   <img width=500 src=https://user-images.githubusercontent.com/17010094/89867411-0fd82180-dba9-11ea-8be2-286373c7aaf5.png>
