### ISSUE TITLE
[Desktop] Monthly contribution USD value cuts off in the BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10344]
## Description 

Monthly contribution USD value cuts off in the BR panel

## Steps to Reproduce

   1. Clean profile 1.11.x 
   2. Launch using `brave.exe --enable-logging --vmodule=*rewards*=6 --log-level=2 --rewards=staging=true`
   3. Enable rewards and claim UGP grants
   4. Visit DDG and set the recurring tip of 1 BAT or 10 BAT
   5. Open BR panel for DDG and look for USD value for recurring tip
   6. Monthly contribution USD value cuts off in the BR panel

## Actual result:

**1.11.x**
![image](https://user-images.githubusercontent.com/38657976/84937117-e8a92a80-b0f8-11ea-8928-da4a0d28de06.png)
![image](https://user-images.githubusercontent.com/38657976/84937167-fbbbfa80-b0f8-11ea-898e-d4350ae2ceb2.png)

**1.10.x**
![image](https://user-images.githubusercontent.com/38657976/84937021-c44d4e00-b0f8-11ea-9246-e237ce930b26.png)

## Expected result:
Monthly contribution USD value should not cut off in the BR panel

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.11.67 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Windows 10 OS Version 1903 (Build 18362.30)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.17.68 `
![image](https://user-images.githubusercontent.com/38657976/99399465-b4d26b00-290b-11eb-9c73-b1d7ee08375c.png)

**Comment by Miyayes** [comment]
No longer relevant in the new Rewards panel 2.0.
