### ISSUE TITLE
[Android] NTP should show an empty page only once on first tab after install

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#10341]
## Description 
App should show an empty NTP page only for the first tab after install. and once the tiles are ready to be shown, it should not show an empty NTP. Please follow https://bravesoftware.slack.com/archives/C0816QH3R/p1592405179311700 for more context

## Steps to reproduce 

   1. Open new tab page with tiles
   2. Close browser via menu
   3. Open browser, tiles are not shown

## Actual result 
![Screenshot_20200617_104531_com brave browser_nightly](https://user-images.githubusercontent.com/5146988/84933486-f5e7fa00-b0a3-11ea-89ed-18d77242d4db.jpg)

## Expected result
![Screenshot_20200617-140900_Brave](https://user-images.githubusercontent.com/5146988/84933637-334c8780-b0a4-11ea-8c88-3babfe23afdd.jpg)

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.10

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9 running 1.10.94
- Verified steps from issue description
- Verified quit and relaunch browser doesn't affect top tiles
