### ISSUE TITLE
New tab page should match fonts/typography from browser-laptop new tab page

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#1034]
Current new tab page typography does not match browser-laptop.

## Steps to Reproduce
Create a new tab. 

## Actual result:
Font used appears to be Helvetica or Arial. 

## Expected result:
New tab page should match fonts/sizes/spacing used in browser-laptop (packaged/embedded font, I believe Poppins).

## Reproduces how often: 
100%

## Brave version (about:brave info) 
Version 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

### Reproducible on current release:
No

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

* Verified all points mentioned in https://github.com/brave/brave-core/pull/1091
* Found #3380 while verifying the issue
