### ISSUE TITLE
[Desktop] Brave shows 'Show Frame-Sourcecode' in contextmenu every time

### ISSUE THREAD

**Issue by BerkeAras** [brave/brave-browser#10346]
## Description 

Brave Browser thinks the website contains an iframe and shows 'Show Frame-Sourcecode' in the context menu every time.

## Steps to Reproduce

   1. Open a basic website
   2. Just rightclick anywhere
   3. See bug

## Actual result:
(German)
![image](https://user-images.githubusercontent.com/36629890/84939131-2ba9d480-b0de-11ea-91db-9f7c16e8520e.png)

## Expected result:
It should not show the Frame options when there is no frame.

## Brave version (brave://version info)

**Brave**: 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
**Revision**: 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
**OS**: Windows 10 OS Version 1909 (Build 18363.836)
## Version/Channel Information:

It happens in the latest release.

**Comment by ko2in** [comment]
Yes. I've the same issue. I see 'View frame source' and 'Reload frame' in every web pages.

## Version:
**Brave:** Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
**OS:** Ubuntu 18.04.4 LTS (64bit)

**Comment by SoftCreatR** [comment]
Same here and it's somewhat annoying.

## Brave version (brave://version info)
**Brave**: 1.10.95 Chromium: 83.0.4103.106 (Official Build) (64-bit)
**OS**: Windows 10
**OS Version**: 1909 (Build 18363.836)

**Comment by bsclifton** [comment]
This is interesting; it seems to be present in Google Chrome too-
![image](https://user-images.githubusercontent.com/4733304/85434199-89a14680-b53a-11ea-9c64-0aa34be1ceb0.png)

I'm not sure why it would show both?

**Comment by SoftCreatR** [comment]
@bsclifton https://bugs.chromium.org/p/chromium/issues/detail?id=1085040

**Comment by bsclifton** [comment]
@SoftCreatR nice! Thanks for finding / sharing the upstream bug 😄

**Comment by bsclifton** [comment]
Closing as this was fixed with Chromium 84 🎉
