### ISSUE TITLE
Building Brave on FreeBSD

### ISSUE THREAD

**Issue by DCastellacci** [brave/brave-browser#10340]
Hello

Is it possible to build brave browser or brave core under FreeBSD ?

I'm on FreeBSD 12.1-RELEASE-p6

and the Brave Browser and Brave Core version 1.12.32
I try to build it it doesn't work

`npm run build

> brave-core@1.12.32 build /usr/home/bs/Downloads/Brave/Core/brave-core-1.12.32
> npm --prefix ../../ run build --

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /usr/home/bs/Downloads/Brave/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/usr/home/bs/Downloads/Brave/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bs/.npm/_logs/2020-06-17T18_06_50_566Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! brave-core@1.12.32 build: `npm --prefix ../../ run build --`
npm ERR! Exit status 254
npm ERR! 
npm ERR! Failed at the brave-core@1.12.32 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bs/.npm/_logs/2020-06-17T18_06_50_579Z-debug.log`

Thank you

**Comment by bsclifton** [comment]
Hi @DCastellacci 

It might be possible to build under FreeBSD, but I don't think we have attempted and it's not something we support at the moment.

You might subscribe to https://github.com/brave/brave-browser/issues/821 and then share your details there. Some other folks have commented there too and may have gotten further along in the process
