### ISSUE TITLE
[Desktop] SpeedReader sometimes returns a blank page for enabled URLs

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#10347]
## Description 

When SpeedReader rule list says that a URL is rewrite-able but the content isn't found with expected selectors a blank page gets rendered

## Steps to Reproduce

   1. Enable SpeedReader under brave://flags
   2. Navigate To e.g. https://edition.cnn.com/travel/article/wild-swimming-saved-my-life-wellness/index.html
   3. Enable SpeedReader for the page by clicking on icon next to address bar

## Actual result:

Blank page

## Expected result:

Default page if rewriting fails

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description
<img width="1197" alt="Screen Shot 2020-08-03 at 9 41 47 AM" src="https://user-images.githubusercontent.com/28145373/89189137-90759d00-d56d-11ea-8e63-58ed93b7e659.png">

-----------
