### ISSUE TITLE
[Desktop] Brave crashes frequently, even with no input

### ISSUE THREAD

**Issue by 8bitgentleman** [brave/brave-browser#10350]
Brave Version: 1.10.93  Chromium: 83.0.4103.106
Operating System: Mac OS X 10.14.6

Can you reproduce this crash?
Yes, every time I use Brave

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Brave
2. Wait ~30seconds

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c9810000-1c55-8704-0000-000000000000

**Comment by 8bitgentleman** [comment]
Seems as though this was caused by enabling #brave-sync in brave://flags/. Once disabled the browser operates normally.

**Comment by bsclifton** [comment]
This is great - thanks for sharing @8bitgentleman 😄 

I'll close out issue for now- we do have a working version of Sync v2 in Nightly 😄 I've been using it for a while on Desktop only and it's been great. The devs are working hard on an Android (hopefully in Android Nightly by next week) and iOS (starting with Bookmarks - date TBD) versions

Sync v2 is tied to 1.12.x at the moment- which is Nightly and is expected to hit stable channel August 4th
