### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Alzaphano** [brave/brave-browser#10354]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.93  Chromium: 83.0.4103.106
Operating System: Windows NT 10.0.18363

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Brave
2. go on any website
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/58840000-1c55-8704-0000-000000000000

**Comment by bsclifton** [comment]
@Alzaphano our recommendation is to turn off sync via brave://flags/#brave-sync, until Sync v2 arrives. If the browser crashes before that page can be loaded, you can launch Brave from command line using `--disable-sync` as a command line parameter and then disable sync via brave://flags/#brave-sync

Thanks for your patience - will talk to team about updating https://support.brave.com/hc/en-us/articles/360042159452-How-do-I-re-enable-Brave-Sync-
