### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jamesharr** [brave/brave-browser#10358]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.93  Chromium: 83.0.4103.106
Operating System: Mac OS X 10.15.5

URL (if applicable) where crash occurred: N/A

Can you reproduce this crash? When sync is enabled, yes...

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. I had sync enabled via about://flags
2. Sync seemed stable until this morning, and then it started crashing.

I can turn off sync via the flags and things are rock solid.

Additionally, I see this in my OSX Console:
```
Jun 18 09:06:58 my-mac Brave Browser[70000]: BUG in libdispatch client: mach_recv, monitored resource vanished before the source cancel handler was invoked { 0x7f9b0ed18c60[source], ident: 52995 / 0xcf03, handler: 0x10fa6f590 }
Jun 18 09:08:04 my-mac com.apple.xpc.launchd[1] (com.brave.Browser.6760[47302]): Service exited due to SIGSEGV | sent by exc handler[47302]
Jun 18 09:12:49 my-mac com.apple.xpc.launchd[1] (com.brave.Browser.6820[47410]): Service exited due to SIGSEGV | sent by exc handler[47410]
Jun 18 09:13:55 my-mac com.apple.xpc.launchd[1] (com.brave.Browser.6828[47485]): Service exited due to SIGSEGV | sent by exc handler[47485]
Jun 18 09:15:07 my-mac com.apple.xpc.launchd[1] (com.brave.Browser.6828[47546]): Service exited due to SIGSEGV | sent by exc handler[47546]
Jun 18 09:16:11 my-mac com.apple.xpc.launchd[1] (com.brave.Browser.6828[47597]): Service exited due to SIGSEGV | sent by exc handler[47597]
Jun 18 09:20:02 my-mac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000004e.Brave Browser[47693]): Service exited due to SIGSEGV | sent by exc handler[47693]
```

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/bd860000-1c55-8704-0000-000000000000

**Comment by bsclifton** [comment]
@jamesharr you're definitely going to want to disable Sync for the moment. There is a v2 that is live in Nightly- Android and iOS implementations are still a work in progress

@jsecretan given the recent uptick in Sync related crashes after Chromium 83 upgrade, should we consider disabling sync and presenting the modal? It might be hotfix worthy given the number of folks reporting

**Comment by bsclifton** [comment]
Closing - recommendation is to turn off sync via brave://flags/#brave-sync, until Sync v2 arrives. If the browser crashes before that page can be loaded, you can launch Brave from command line using `--disable-sync` as a command line parameter and then disable sync via brave://flags/#brave-sync

Thanks for your patience - will talk to team about updating https://support.brave.com/hc/en-us/articles/360042159452-How-do-I-re-enable-Brave-Sync-
