### ISSUE TITLE
[Desktop] Deactivate the wallet and rewards

### ISSUE THREAD

**Issue by fenchi** [brave/brave-browser#10369]
Hello,

How to deactivate the wallet and rewards?

Thank you,

**Comment by rebron** [comment]
Hi @fenchi Go to brave://rewards and select the top toggle to turn off Brave Rewards.

**Comment by fenchi** [comment]
Thank you for your answer.

I applied your solution.
But the icon is still visible to the right of the search bar which offers to reactivate it.
How can we hide it?

Thank you,

**Comment by NejcZdovc** [comment]
@fenchi go to brave://settings/appearance and check hide rewards

![image](https://user-images.githubusercontent.com/9574457/90365754-9f2c7b80-e066-11ea-8ae7-71811810a068.png)

**Comment by fenchi** [comment]
It's better.
Thank you
