### ISSUE TITLE
[Desktop] Can't complete purchase on https://www.paradoxplaza.com

### ISSUE THREAD

**Issue by Northshoot** [brave/brave-browser#10361]
## Description 

Can not complete purchase on https://www.paradoxplaza.com/on-sale/ (and they have sale now!) , the complete button will keep on spinning without further actions. Works in Safari and other browsers.

Seems like browsers is blocking
static.xsolla.com/em…0.8/widget.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cdn.cquotient.com/js/v2/gretel.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
static.hotjar.com/c/…ar-749487.js?sv=6:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
COOnepage-Start?paym…ocessorerror=true:1 Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1…kJCQlzZXRUaW1lb3V0KG8uZXZlbnRDYWxsYmFjaywgMSk7CgkJCX0KCQl9OwoJfQp9KSgpOw==' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-eval' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

That is after disabling shield.

## Steps to Reproduce

   1. Create account if you don't have
   2. Make sure to Link with Steam
   3. Add any game to card
   4. Proceed to checkout
   5. Fill in details and

Can be reproduced with or without login in.
## Actual result:

Error message if not logged in, endless spinner otherwise.

## Expected result:

going to payment options.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F101)
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,MixedContentSiteSetting,SimplifyHttpsIndicator,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,DnsOverHttps --disable-features=TextFragmentAnchor,AllowPopupsDuringPageUnload,AudioServiceOutOfProcess,SmsReceiver,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,VideoPlaybackQuality --flag-switches-begin --allow-insecure-localhost --load-media-router-component-extension=1 --enable-features=PasswordImport,MixedContentSiteSetting,SimplifyHttpsIndicator,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,DnsOverHttps,TabGroups --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes

- Can you reproduce this issue with the beta channel? 
don't use that

- Can you reproduce this issue with the dev channel? 
don't use that

- Can you reproduce this issue with the nightly channel? 
don't use that

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No

- Does the issue resolve itself when disabling Brave Rewards? 
No

- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

Thanks for great job!

**Comment by ryanbr** [comment]
I tested this, signed up. Attached to my Steam account.

I got to this page @Northshoot   (with default sheilds) Is it still failing?

![paradox](https://user-images.githubusercontent.com/1659004/87100971-db1f3480-c2a1-11ea-8163-aa821e983795.png)
