### ISSUE TITLE
Brave Browser Crashes[Desktop]

### ISSUE THREAD

**Issue by bsantos11** [brave/brave-browser#10376]
## OS
Ubuntu 18.04.4 LTS

## Description 

I updated brave browser yesterday. After the update the browser would crash within a few minutes of being opened.

## Brave version (brave://version info)

v 1.10.93
## Additional Information
I removed my brave browser from the Sync Chain that I was a part of and the browser has not crashed. I have been using it for a few hours and the browser has not crashed yet.

**Comment by bsantos11** [comment]
I removed my brave browser from the Sync Chain that I was a part of and the browser has not crashed. I have been using it for a few hours and the browser has not crashed yet.

**Comment by eljuno** [comment]
That's the reason why Sync is temporarily disabled for desktop. Sync v2 will solve this issue and will re-enable Sync.

**Comment by bsclifton** [comment]
Closing - as you noticed @bsantos11 - current recommendation is to turn off sync via brave://flags/#brave-sync, until Sync v2 arrives (it's in Nightly now 😄). If the browser crashes before that settings page for disabling can be loaded, you can launch Brave from command line using `--disable-sync` as a command line parameter and then disable sync via brave://flags/#brave-sync

Thanks for your patience - will talk to team about updating https://support.brave.com/hc/en-us/articles/360042159452-How-do-I-re-enable-Brave-Sync-
