### ISSUE TITLE
[Android] Not all settings have close button

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#10375]
## Description 
Some settings don't have close button
![device-2020-06-18-181120](https://user-images.githubusercontent.com/30602739/85140398-34e88d80-b213-11ea-8836-eb46307e519e.png)
![device-2020-06-18-181139](https://user-images.githubusercontent.com/30602739/85140408-387c1480-b213-11ea-88b3-86e5041f3d96.png)
In cr84 there were changed 2 more options
![device-2020-06-18-181338](https://user-images.githubusercontent.com/30602739/85140538-62353b80-b213-11ea-97f2-48a68259eb19.png)
![device-2020-06-18-181358](https://user-images.githubusercontent.com/30602739/85140553-65302c00-b213-11ea-99ad-b7aa08ffe6b8.png)
For consistency we should replace `menu_help` in `chrome/android/java/src/org/chromium/chrome/browser/settings/SettingsActivity.java` with close button. This way any new or changed settings will have it by default.

## Steps to reproduce 

   1. See pictures in description

## Actual result 
Not all settings have close button

## Expected result
Close button in all settings

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.9.80

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Some options declare their own menu, so we will need to separately add close button there. Follow up issue created https://github.com/brave/brave-browser/issues/15615

**Comment by samartnik** [comment]
Test plan: check that all options, apart from options in follow up issue above, have close button.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.65 x64 build
- Verified close button is available on all menu settings
- Verified clicking it closes the menu and goes back to tab

![image](https://user-images.githubusercontent.com/17010094/119126419-ea771e80-ba2a-11eb-836b-848b26847ae4.png) | ![image](https://user-images.githubusercontent.com/17010094/119126428-ee0aa580-ba2a-11eb-9c52-b24d7e4dca64.png) | ![image](https://user-images.githubusercontent.com/17010094/119126440-f236c300-ba2a-11eb-95d6-94a56b3216d0.png) | ![image](https://user-images.githubusercontent.com/17010094/119126458-f531b380-ba2a-11eb-884c-f6ad2c90cb8f.png)
-- | -- | -- | --

---------
Verification passed on Samsung Tab A  with Android 10 running 1.25.65 x64 build
- Verified close button is available on all menu settings
- Verified clicking it closes the menu and goes back to tab

![image](https://user-images.githubusercontent.com/17010094/119126743-5063a600-ba2b-11eb-84ea-e1038ecce891.png) | ![image](https://user-images.githubusercontent.com/17010094/119126750-535e9680-ba2b-11eb-9009-3df60f45cae5.png) | ![image](https://user-images.githubusercontent.com/17010094/119126761-56f21d80-ba2b-11eb-9581-5ebaf65f4c37.png) | ![image](https://user-images.githubusercontent.com/17010094/119126767-5bb6d180-ba2b-11eb-89c1-8eb21c30437b.png)
-- | -- | -- | --
