### ISSUE TITLE
Context menu search uses wrong search engine on private tabs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1037]
## Description 

Context menu search uses wrong search engine on private tabs

## Steps to Reproduce

   1. Open a private window
   2. Enable DDG switch and search for a term, uses DDG as default search engine
   3. Highlight a text on the result page and right click `Search on DuckDuckGo for "highlited word"`, opens a new tab with search results on Google which is the default search engine on profile

## Actual result:

https://youtu.be/XHAOB437u10

## Expected result:
Should use DDG for context menu search as well

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows/Linux

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Doesn't happen on normal tabs. Context menu uses the set default search engine to show results.

**Comment by bbondy** [comment]
Updated milestone to 0.58.x since it was merged there.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

- Verified context menu search uses DDG when searched from the result page
