### ISSUE TITLE
[Desktop] Make Rewards message close button more visible

### ISSUE THREAD

**Issue by eljuno** [brave/brave-browser#10378]
## Description 

Originally reported here https://community.brave.com/t/brave-rewards-wallet-not-connecting-anymore/135056 and here https://community.brave.com/t/brave-rewards-says-my-wallet-is-disconnected-but-also-says-that-its-connected/136328?u=eljuno but have seen similar feedbacks before.

Currently, X close button for Rewards messages is not clearly visible so there's a chance user didn't notice it.

## Steps to Reproduce

Waiting for the message to appear by itself? e.g. backup message or connection error message (see screenshot)

## Actual result:

![462c492be7a585562f696933c782a203d12872f6](https://user-images.githubusercontent.com/25360853/85184123-c78f3800-b2b8-11ea-872e-594f73e7d556.png)

## Expected result:

More visible

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? NDA
- Can you reproduce this issue with the dev channel? NDA
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

cc @rebron @srirambv

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6033

Close (x) button in 1.11.x | Close (x) button in 1.12.x
-- | --
![image](https://user-images.githubusercontent.com/38657976/88207307-34f20800-cc6d-11ea-9fee-d0176e71c1c8.png) | ![image](https://user-images.githubusercontent.com/38657976/88207342-40ddca00-cc6d-11ea-970b-0137f4d58964.png)
