### ISSUE TITLE
[Desktop] Feature Request : smaller or inobtrusive download status bar

### ISSUE THREAD

**Issue by didli** [brave/brave-browser#10377]
## Description 
The Download Status bar that appears when downloading a file is a bit obtrusive and takes too much space, specifically its height (could be 30% ~ 40% what it is presently).   

## Steps to Reproduce
Everytime since its configured that way.

## Expected result:
An option that produces for a smaller, compact bar is enough. 
I don't think this should be default since visually impaired people would met difficulties with a smaller status bar.

## Brave version (brave://version info)
All that I know of.

**Comment by rebron** [comment]
Thanks @didli. Closing this one as a duplicate of #1638
