### ISSUE TITLE
[Desktop] SpeedReader communicate from rewriting library when no content found

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#10372]
## Description 

SpeedReader currently falls back to normal page rendering if no content is found as defined by having less than a threshold (500) bytes in the output buffer. This is potentially fragile because there might be more boilerplate content than that.

## Steps to Reproduce

N/A

## Actual result:

Hardcoded threshold value

## Expected result:

Should propagate information on whether there was any content matching content rules from rewriting library back to url loader.

## Reproduces how often: 

N/A

## Brave version (brave://version info)

Brave | 1.12.14 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel?  N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by iefremov** [comment]
stale
