### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by devanz** [brave/brave-browser#10374]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.93  Chromium: 83.0.4103.106
Operating System: Mac OS X 10.15.5

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open brave
2. crashed within a few minutes
3.disable sync seems to resolve this issue

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/36890000-1c55-8704-0000-000000000000

**Comment by devanz** [comment]
I can see 10 more crashes but those reports are in status "Upload requested by user"

Here's another report that has been successfully uploaded
ab880000-1c55-8704-0000-000000000000

**Comment by srirambv** [comment]
For time being you can disable sync. more info https://github.com/brave/brave-browser/issues/10358#issuecomment-646173164

**Comment by bsclifton** [comment]
Closing - recommendation is to turn off sync via brave://flags/#brave-sync, until Sync v2 arrives. If the browser crashes before that page can be loaded, you can launch Brave from command line using `--disable-sync` as a command line parameter and then disable sync via brave://flags/#brave-sync

Thanks for your patience - will talk to team about updating https://support.brave.com/hc/en-us/articles/360042159452-How-do-I-re-enable-Brave-Sync-
