### ISSUE TITLE
[Desktop] Add the option to set custom background

### ISSUE THREAD

**Issue by sayedarifuddin** [brave/brave-browser#10381]
## Description 
Current setting doesn't have the option to set our own **New Tab** background.

## Steps to Reproduce

   1. Head to [brave://settings/newTab](url)
   2. The option to set custom background is absent.

![image](https://user-images.githubusercontent.com/47639147/85204135-234ad700-b334-11ea-8dcb-8166f4deb6b2.png)

## Version/Channel Information:
Version 1.12.19 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit)

**Comment by i3asm** [comment]
would be really nice

**Comment by i3asm** [comment]
isn't this supposed to be in [brave core](https://github.com/brave/brave-core)

**Comment by rebron** [comment]
@sayedarifuddin Thanks for the issue. Closing as a duplicate of #5838
