### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by lemosley01** [brave/brave-browser#10384]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.93  Chromium: 83.0.4103.106
Operating System: Windows NT 10.0.18363

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes. If I turn off the sync, it is stable. I've experienced this on two different computers in the same sync chain. 

If I disable sync, the crashes stop, so this seems to be sync related. 

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Start the browser with SYNC enabled
2. Wait
3. Crash seems to occur after a minute or so (I didn't time it).

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e4970000-1c55-8704-0000-000000000000

**Comment by chrissxYT** [comment]
wow, how did you figure that out? the same crash just happened to me too and i was hopelessly lost til i opened firefox and found this

**Comment by lemosley01** [comment]
This problem happened back in December (2019 - at least I think so), and disabling sync then stopped the crashes.

This had the exact same symptoms - started happening out of nowhere (seemingly) and the browser just exits without no warning after a minute or so, so disabling sync was the first thing I tried.

If that didn't work, I was moving on to debugging, but that's REALLY hard to do without symbols. 

@BrendanEich is there a symbol server or symbols available someplace for Windows builds of Brave? I'm very familiar with debugging post-mortem crashes in Windbg.

**Comment by vijayhardaha** [comment]
![2020-06-22_124804](https://user-images.githubusercontent.com/25227317/85259642-04a92500-b487-11ea-90cc-97a976de6b76.png)
I'm also facing crash issues. The crash is happening when I open the browser for the first time. I have settings that open my left tabs when I relaunch but with this crash, all the tabs are gone and fresh windows open in 2-3 attempts (after the crash).

I also noticee the console errors which are shown in Image.

**Comment by bsclifton** [comment]
Thanks for report folks- recommendation is to turn off sync via brave://flags/#brave-sync, until Sync v2 arrives. If the browser crashes before that page can be loaded, you can launch Brave from command line using `--disable-sync` as a command line parameter and then disable sync via brave://flags/#brave-sync

Sync v2 is in 1.12.x (Nightly) at the moment and will be floating through the channels (next in Beta, then finally in release)
