### ISSUE TITLE
[Desktop] Archive.is no longer works (unsupported browser)

### ISSUE THREAD

**Issue by nibber55** [brave/brave-browser#10383]
## Description 
Open archive.is - be redirected to "Unsupported Browser"

## Expected result:
That the website works

## Brave version (brave://version info)
1.10.93

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by nibber55** [comment]
Apparently related:
https://github.com/brave/brave-browser/issues/10219

**Comment by bsclifton** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/10219

**Comment by GfEW** [comment]
> Closing as duplicate of [#10219](https://github.com/brave/brave-browser/issues/10219)

Unfortunately, the original issue gives a 404 by now, which hampers retrospective transparency.
- Has it been deleted by the brave team?
- If so, why?
- If not, what/who else has made it vanish?
- Is there any log of such administrative actions?
