### ISSUE TITLE
[Desktop] manageProfile is blank

### ISSUE THREAD

**Issue by kaushalyap** [brave/brave-browser#10386]
## Description 

When navigate to brave://settings/manageProfile screen is blank.

## Steps to Reproduce

   1. Install Brave 1.10.90 on Fedora (Probably Linux distro does not matter)
   2. Go to brave://settings/manageProfile

## Actual result:

![Screenshot from 2020-06-21 14-26-34](https://user-images.githubusercontent.com/24698778/85220687-4a081c80-b3cb-11ea-9906-a33aa0a98b1b.png)

## Expected result:

![Screenshot from 2020-06-21 13-54-13](https://user-images.githubusercontent.com/24698778/85220662-00b7cd00-b3cb-11ea-8f95-16f96318b083.png)

Screenshot from Chrome

## Reproduces how often: 

Easily reproducible

## Brave version (brave://version info)

Brave : 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
Revision : 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS : Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

```
uname -a
Linux hostname 5.6.18-300.fc32.x86_64 #1 SMP Wed Jun 10 21:38:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by saemideluxe** [comment]
Same here
```
$ brave-browser --version
Brave Browser 83.1.10.95

$ uname -a
Linux sambook 5.6.0-2-amd64 #1 SMP Debian 5.6.14-1 (2020-05-23) x86_64 GNU/Linux

$ cat /etc/apt/sources.list.d/brave.list
deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main

$ dpkg --list | grep brave-browser
ii  brave-browser                                               1.10.95                             amd64        The web browser from Brave
```

**Comment by j0k3r** [comment]
Issue still exist in 1.10.97.
Looks like an error related to Polymer:

![image](https://user-images.githubusercontent.com/62333/86435511-69bf0f00-bd00-11ea-9730-9a44d859adc9.png)

**Comment by chkk525** [comment]
I also experience this. In my case on macOS, it is blank only when I go there from tool bar(Profile > Edit). 
![image](https://user-images.githubusercontent.com/3054915/87136488-89dd6800-c2d6-11ea-93ad-32224767996a.png)

When I access there from brave://settings/, it shows the expected menu.
![image](https://user-images.githubusercontent.com/3054915/87136642-be512400-c2d6-11ea-9195-fbabc588700c.png)

**Comment by rebron** [comment]
@kaushalyap and @chkk525 Are you still seeing this in 1.11.x?

**Comment by kaushalyap** [comment]
Not anymore seems fixed!
