### ISSUE TITLE
[Android] Unable to verify uphold on Nexus 5

### ISSUE THREAD

**Issue by Ravendwyr** [brave/brave-browser#10382]
## Description 
I am unable to link my BAT wallet on my Nexus 5 to Uphold. Attempting to do so causes the app to crash.

## Steps to reproduce 

   1. Tap on BAT Rewards triangle icon.
   2. Tap blue Verify Wallet button in the BAT Rewards popup.
   3. Tap orange Verify Wallet to begin linking.

## Actual result 
Brave force closes with "Unfortunately, Brave has stopped" window and no visible error message.

## Expected result
Continues to Uphold to continue linking process

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? No

## Device details
   - Install type (ARM, x86): Unsure, but I'm fairly certain it's not 64-bit
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 6.0.1 (not possible to update further as model was discontinued)
   
## Brave version
1.10.94

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

Admittedly this is an old phone so chances are that the age of the device and how out of date it is compared to other phones is what's causing the issue.  However I am still able to receive ads and BAT as well as tip the BAT to Brave Publishers. As of writing I have 37.5 BAT in the local wallet with 1.3 BAT as "estimated rewards pending".

I have looked for the option to export the local database (as per #9766 and #9992) however I don't have the option in Brave Settings or the Android Developer Options.

My other phone, a OnePlus 6, was able to link to Uphold successfully.  I currently have two laptops, my gaming PC, and the OnePlus linked to my Uphold account.

**Comment by Ravendwyr** [comment]
Today's update (1.10.95) did not solve the issue.

**Comment by Ravendwyr** [comment]
From the brave://version info page, in case any of this is helpful:

Brave | 1.10.99 Chromium:   83.0.4103.116 (Official Build) (32-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Android 6.0.1;   Nexus 5 Build/M4B30Z
Google Play services | SDK=12451000;   Installed=202117018; Access=3p
JavaScript | V8 8.3.110.13
User Agent | Mozilla/5.0 (Linux;   Android 6.0.1; Nexus 5) AppleWebKit/537.36 (KHTML, like Gecko)   Chrome/83.0.4103.116 Mobile Safari/537.36
Command Line | --disable-fre   --use-mobile-user-agent --top-controls-show-threshold=0.5   --top-controls-hide-threshold=0.5 --use-mobile-user-agent --enable-viewport   --validate-input-event-stream --enable-longpress-drag-selection   --touch-selection-strategy=direction --main-frame-resizes-are-orientation-changes   --disable-composited-antialiasing --enable-dom-distiller   --disable-domain-reliability --no-pings   --extension-content-verification=enforce_strict   --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid   --enable-features=DnsOverHttps,PasswordImport,MixedContentSiteSetting,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode   --disable-features=TranslateUI,TextFragmentAnchor,AllowPopupsDuringPageUnload,NotificationTriggers,InterestFeedContentSuggestions,TabHoverCards,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AutofillServerCommunication,AutofillEnableAccountWalletStorage,VideoPlaybackQuality,OfflinePagesPrefetching   --flag-switches-begin --flag-switches-end
Executable Path | No such file or   directory
Profile Path | /data/user/0/com.brave.browser/app_chrome/Default
Variations | 5e3a236d-4113a79e

**Comment by NejcZdovc** [comment]
@deeppandya @SergeyZhukovsky any ideas?
