### ISSUE TITLE
[Android] Fix text on tipping panel to remove Twitter 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10399]
## Description 
As a consequence of #10208, tipping for twitter is removed but the tips section still says to tip twitter accounts

## Steps to reproduce 

   1. Install 1.10.95
   2. Visit a twitter page and open BR panel, no tips button is shown
   3. Open rewards page and go to tips sections, shows tipping Twitter accounts 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/85283216-e2aea300-b484-11ea-9ad7-37d7d0baa5a6.png)

## Expected result
Should not have unsupported platforms listed for tipping

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Tab A 
   - Android version: 9
   
## Brave version
1.10.95

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by anthonypkeane** [comment]
Will fix when we implement the native page

**Comment by Miyayes** [comment]
This is resolved as we changed this text in general.
