### ISSUE TITLE
[Desktop] Migrate uphold_anon_address into external_wallets.uphold

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10397]
Right now `uphold_anon_address` lives in `brave.rewards` and we don't clear it when we disconnecting wallet. This should be migrated into `brave.rewards.external_wallets.uphold`, so that when we disconnect wallet we remove everything.

When migration is done we should clear and deprecate `kStateUpholdAnonAddress` value.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.13.76 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
Revision	4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Plan 1 from https://github.com/brave/brave-core/pull/6063
Prior to connecting KYC'd uphold wallet, this is what `Preferences` file looked like:
<img width="476" alt="prefs ss 1" src="https://user-images.githubusercontent.com/28145373/90520152-fac63a00-e136-11ea-9952-eeff3b9b6cee.png">

After connecting KYC'd uphold wallet, this is what `Preferences` file looked like:
<img width="348" alt="prefs ss 2" src="https://user-images.githubusercontent.com/28145373/90520158-fdc12a80-e136-11ea-8fa9-4b7ddc9cced9.png">

Plan 2 from https://github.com/brave/brave-core/pull/6063
Using 1.12.x, this is what `Preferences` file looked like with KYC'd wallet:
<img width="442" alt="prefs ss 3" src="https://user-images.githubusercontent.com/28145373/90520164-00bc1b00-e137-11ea-9590-4a67941e877a.png">

Upgrading to 1.13.x, this is what the `Preferences` file looked like:
![prefs ss 4](https://user-images.githubusercontent.com/28145373/90520177-04e83880-e137-11ea-9baf-d46d304f7118.png)
<img width="364" alt="prefs ss 5" src="https://user-images.githubusercontent.com/28145373/90520179-06196580-e137-11ea-853c-b2a1b5faea33.png">

--------
