### ISSUE TITLE
Browser crashes at system restart

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1039]
## Description 

Browser crashes at system restart

## Steps to Reproduce

   1. Upgrade to 0.55.2 on Linux
   2. Restart machine
   3. Browser crashes splash screen is shown

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/45254565-78c51800-b348-11e8-8e43-8837cad7668e.png)
![image](https://user-images.githubusercontent.com/17010094/45254567-7ebaf900-b348-11e8-86d2-4241443393e3.png)

## Expected result:
Should not crash when system is restarted

## Reproduces how often: 

Intermittent issue (80%) on 0.55.2 on Ubuntu 18.04

## Brave version (about:brave info) 

Brave | 0.55.2 Chromium: 70.0.3528.4 (Official Build) unknown (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Linux

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Not seen this on the previous build
cc: @simonhong

**Comment by iefremov** [comment]
should be fixed by now...
