### ISSUE TITLE
autotrader.com access denied [Desktop]

### ISSUE THREAD

**Issue by chrisamow** [brave/brave-browser#10396]
## Description 

Trying to go to autotrader main page, this error message comes up (it's not redirecting to https ?):
Access Denied
You don't have permission to access "http://www.autotrader.com/" on this server.
Reference #18.17cadf17.1592812919.1269833c

## Steps to Reproduce

   1. navigate to "autotrader.com"
   2. 
   3. 

## Expected result:
the web page comes up on chrome and firefox

## Reproduces how often: 

Always (today)

## Brave version (brave://version info)

Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Investigating, NZ and US IP I get an error. If not, it'll time out.

`We're sorry for any inconvenience, but the site is currently unavailable.
Please contact our support team for help.`

`Incident Number: 18.8c346d68.1592910000.140000ac`

Tested in Chrome, Brave, and Firefox. Got similar issues. I'm leaning on a serverside issue here @chrisamow

**Comment by ryanbr** [comment]
Looking at the facebook comments on https://www.isitdownrightnow.com/autotrader.com.html  seems others are having issues.

**Comment by bsclifton** [comment]
@chrisamow you're on a super old version of Brave - would you be able to upgrade please and let us know if that resolves the issue? Thanks! 😄

**Comment by chrisamow** [comment]
@bsclifton Ok, latest version looks great.

I tried upgrading the easy way and it ended up still with a release <1.0 and autotrader.com still didn't work, maybe my sources were confused.  Then I did a full uninstall and reinstall from scratch.  And it loads fine.

**Comment by ryanbr** [comment]
Still not working here, would say its a site issue. Seems to be quite a common fault they're having.

![autotrader](https://user-images.githubusercontent.com/1659004/85946366-05b2e880-b998-11ea-963f-70b1143b51e7.png)

**Comment by ryanbr** [comment]
Actually, it seems to be checking ips/geolocations. Page loaded fine via a VPN (using a New York loco). If you have access to a VPN @chrisamow try a few US locations, test in private window also (so it doesn't pick up your cookies from previous sessions)

**Comment by bsclifton** [comment]
Closing as originally reported issue is closed; however we can re-open @ryanbr if you wanted to edit issue to characterize the IP issue
