### ISSUE TITLE
[Desktop] site-specific Shields setting allow javascript is sometimes lost when restarting brave

### ISSUE THREAD

**Issue by bessw** [brave/brave-browser#10401]
## Description 

site-specific Shields setting allow javascript is sometimes lost when restarting brave

## Steps to Reproduce

   1. disable javascript in global Shield settings
   2. allow it for some sites manually
   3. restart Brave

## Actual result:

Sometimes after restarting all websites have js disabled again.

## Expected result:
Pages where I explicitly enabled js should always be remembered.

## Reproduces how often: 

Hard to say, I'm not restarting Brave that often, but it's often enough to be very annoying.

## Brave version (brave://version info)

Brave | 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Windows 10 OS Version 2004 (Build 19041.329)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@bessw Can you update to 1.12.112 and let us know if you're still encountering this issue? There's been some work done in this area since 1.10.x and want to see if this still something you're seeing.

**Comment by bessw** [comment]
I restarted Brave a few times and it didn't happen, I'll keep an eye on it and come back should it reappear.

Thanks for your great work on this browser, I really like Brave.
