### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jimwormold** [brave/brave-browser#10400]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.93  Chromium: 83.0.4103.106
Operating System: Windows NT 10.0.18363

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Joining my sync chain
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/d8a00000-1c55-8704-0000-000000000000

**Comment by bsclifton** [comment]
Thanks for report @jimwormold - recommendation is to turn off sync via brave://flags/#brave-sync, until Sync v2 arrives. If the browser crashes before that page can be loaded, you can launch Brave from command line using `--disable-sync` as a command line parameter and then disable sync via brave://flags/#brave-sync

Sync v2 is in 1.12.x (Nightly) at the moment and will be floating through the channels (next in Beta, then finally in release)
