### ISSUE TITLE
[Android] Implement infobar for Android sync v1 users about v1 will be deprecated

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10416]
Related PR https://github.com/brave/brave-core/pull/5361.

Required to make similar to desktop b-c PR https://github.com/brave/brave-core/pull/5806  to inform Android sync v1 users that sync v1 will be shut down and they need to create a new sync chain with sync v2.

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/6128 was approved and merged into `1.11.x`.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.100 x64 PR build

#### Sync Enabled
- Verified upgrading from 1.10.x with sync enabled shows the infobar immediately after launch
   <img width=350 src=https://user-images.githubusercontent.com/17010094/88386736-ee092d00-cda8-11ea-9bf2-6892fbe5771e.png>

- Verified clicking on `Learn more` open support page `https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-`
- Verified dismissing the infobar doesn't show the message again 
- Verified once the infobar is shown closing and reopening the browser doesn't show the message
- Verified post-upgrade opening a private tab via home screen shows the infobar as well

#### Sync Disabled

- Verified upgrading from 1.10.99 without sync enabled doesn't show the infobar

#### Clean Install

- Verified clean install of the build, doesn't show any infobar 

-------------------------
Verification passed on Samsung Tab A with Android 10 running 1.11.100 x64 PR build

#### Sync Enabled

- Verified upgrading from 1.10.x with sync enabled shows the infobar immediately after launch
   <img width=650 src=https://user-images.githubusercontent.com/17010094/88386820-12fda000-cda9-11ea-97ae-a56468fd18bb.png>

- Verified clicking on `Learn more` open support page `https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-`
- Verified dismissing the infobar doesn't show the message again 
- Verified once the infobar is shown closing and reopening the browser doesn't show the message
- Verified post-upgrade opening a private tab via home screen shows the infobar as well

#### Sync Disabled

- Verified upgrading from 1.10.99 without sync enabled doesn't show the infobar

#### Clean Install

- Verified clean install of the build, doesn't show any infobar 

-------------------------
