### ISSUE TITLE
[Desktop] Google sponsored links are "jittery" and sometimes temporarily garbled

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#10411]
## Description 
The google search results page often "jumps" because there's a delay in displaying sponsored links. It does not occur when cosmetic filtering is disabled.

## Steps to Reproduce

   1. Search for something that will likely trigger a sponsored link like "toyota"

## Actual result:

Sponsored (Ad) links are delayed in loading which makes the page jump and are also sometimes temporarily garbled while this is happening

## Expected result:
The page should not jump and there should be no delay in displaying the sponsored links (or alternatively hide them without reappearing)

## Reproduces how often: 
Always when there are sponsored links

## Brave version (brave://version info)
1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
yes
- Can you reproduce this issue with the beta channel? 
yes
- Can you reproduce this issue with the dev channel? 
yes
- Can you reproduce this issue with the nightly channel? 
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
yes - or just disabling cosmetic filtering
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
no

**Comment by bsclifton** [comment]
I think this is the same issue as https://github.com/brave/brave-browser/issues/9051

**Comment by bridiver** [comment]
@bsclifton I don't think it's the same issue. google.com is a different set of rules and also it's blocking 1st-party sponsored links

**Comment by antonok-edm** [comment]
Should be fixed by https://github.com/brave/brave-core/pull/6013
