### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by gallegosart** [brave/brave-browser#10428]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

**This crash took down all my open tabs on relaunch. The restore closed tabs prompt came up, but clicking it did nothing and I can't restore them manually. History exists, but not helpful to remember tabs in this case.

Brave Version: 1.10.95  Chromium: 83.0.4103.106
Operating System: Windows NT 10.0.18363

URL (if applicable) where crash occurred: Facebook

Can you reproduce this crash? No

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/0ca90000-1c55-8704-0000-000000000000

**Comment by bsclifton** [comment]
Does not look related to sync; callstack in backtrace looks like:
```
base::Value::Clone
ContentSettingsPattern::Wildcard
base::TaskAnnotator::WillQueueTask
```

**Comment by iefremov** [comment]
@bsclifton this should be https://github.com/brave/brave-browser/issues/10297
cc @bridiver

**Comment by bsclifton** [comment]
@iefremov nice! I'll go ahead and close this issue out as a dupe; We should start to see progress once 1.11.x hits release
