### ISSUE TITLE
Update Ipfs client via component extension

### ISSUE THREAD

**Issue by drbh** [brave/brave-browser#1042]
Create a component extension for updating the Ipfs client executable and provide an API for retrieving the full path of the client executable.

like: #724

**Comment by lidel** [comment]
Hi, just to make sure I understand this, now that https://github.com/brave/brave-core-crx-packager/pull/23 got merged the next step is tackling C++ side  of things in https://github.com/brave/brave-core/pull/425, correct?

cc https://github.com/brave/brave-browser/issues/819

**Comment by drbh** [comment]
@lidel yea the next steps are working on the C++ side. I made a PR looking at the Tor Private Tabs implementation. 

I need some help with using the correct test keys and extension IDs before the request is good.

**Comment by bbondy** [comment]
Duping to https://github.com/brave/brave-browser/issues/10220
