### ISSUE TITLE
Add a setting to block cookie banners

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#10433]
## Description
We have received complaints from users about having to click through cookie consent banners related to real-time bidding. We should offer a global setting (default OFF) in Shields which would:

1. Automatically deny all data sharing (like the option that's available in the Cliqz browser and can be verified using the [re:consent extension](https://chrome.google.com/webstore/detail/reconsent/djcdlbbfldmndgenehaifaiiahhhagfa)) in first-party consent manager platforms which follow the [IAB protocol](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/TCF-Implementation-Guidelines.md).
2. Hide banners using the [Easylist-Cookie](https://easylist-downloads.adblockplus.org/easylist-cookie.txt) cosmetic filters.

We could surface that setting the first time a user encounters a cookie banner via a notification.

Alternatively, instead of a new global setting, we could tie this feature to the existing "aggressive mode" blocking option.

## Design
Figma link: https://www.figma.com/file/cL22PpqneTYxJePORxUBKz/Cookie-consent-blocker?node-id=61%3A16268

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.44.71 Chromium: 105.0.5195.68 (Official Build) dev (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:

Case One: New profiles
<details>

Start browser with a new profile.
Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
Restart the browser.
Wait for first page load.
Verify that the "cookie list opt-in" bubble is displayed.
Click the "enable" button.
Verify that the bubble is closed after the animation completes.
Navigate to brave://adblock.
Expand the list of filters, and verify that the "Cookie List" filter has been enabled.
Visit another page and verify that the opt-in bubble is not displayed again.
Restart the browser and verify that the opt-in bubble is not displayed again.


</details>

Case Two: Clicking the X
<details>

Start browser with a new profile.
Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
Restart the browser.
Wait for first page load.
Click the "X" button to close the bubble.
Visit another page and verify that the opt-in bubble is not displayed again.
Restart the browser and verify that the opt-in bubble is not displayed again.


</details>

Case Three: Closing the bubble
<details>

Start browser with a new profile.
Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
Restart the browser.
Wait for first page load.
Click outside of the bubble to close the bubble.
Visit another page and verify that the opt-in bubble is not displayed again.
Restart the browser and verify that the opt-in bubble is not displayed again.

</details>

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` with
```
Brave | 1.44.79 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
### Steps:

#### Case One: New profiles - PASSED
<details>

1. Start browser with a new profile.
2. Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
3. Restart the browser.
4. Wait for first page load.
5. Verify that the "cookie list opt-in" bubble is displayed.
6. Click the "enable" button.
7. Verify that the bubble is closed after the animation completes.
8. Navigate to brave://adblock.
9. Expand the list of filters, and verify that the "Cookie List" filter has been enabled.
10. Visit another page (digikey.com) and verify that the opt-in bubble is not displayed again.
11. Confirmed cookie consent banner is blocked
12. Restart the browser and verify that the opt-in bubble is not displayed again.

`step 2` | `step 5-6` | `steps 7` | `step 8-9` | `step 10` | `step 11`|`step 12`
---------|----------|-------------|---------|-----------|---------|-------
<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189233601-9bff196d-c14c-4512-913d-b97e95a5ecc9.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189233019-9dfb04dd-f9b1-47f6-b685-a9709818c49c.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189233657-5ca8c252-e1d7-4b74-add4-3bc1252d6f70.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189233704-65443592-b519-4b09-9544-5572298ef7bd.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189233905-5699d15e-d42e-49e6-82dc-b22a9b89a683.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189234012-57954583-de11-46b0-9edf-c44df7caff4b.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189242426-e810ddc0-1f2e-4289-b254-f1b30752eaab.png">

</details>

#### Case Two: Clicking the X - PASSED
<details>

1. Start browser with a new profile.
2. Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
3. Restart the browser.
4. Wait for first page load.
5. Click the "X" button to close the bubble.
6. Visit another page (lemonde.fr) and verify that the opt-in bubble is not displayed again.
7.  Cookie consent banner is not blocked
8. Restart the browser and verify that the opt-in bubble is not displayed again.

`step 2` | `step 5` | `steps 6-7` | `step 8`
---------|----------|-----------|---------
<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189235034-c9f9ccdf-931a-4038-a1fa-3635e4355750.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189235071-1ab11e5b-d31b-4d5b-9851-c0dfad1f1668.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189241609-d6446d94-caea-453e-8e04-189d2a4bbaa0.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189241990-df48706a-87ca-4fba-bd39-8149ba1b15b1.png">

</details>

#### Case Three: Closing the bubble - PASSED
<details>

1. Start browser with a new profile.
2. Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
3. Restart the browser.
4. Wait for first page load.
5. Click outside of the bubble to close the bubble.
6. Cookie List" filter has not  been enabled in brave://adblock 
7. Visit a site (gulfnews.com) and verify that the opt-in bubble is not displayed again.
8. Cookie consent banner is not blocked
9. Restart the browser and verify that the opt-in bubble is not displayed again.

`step 2` | `step 5` | `step 6` | `step 7-8`|`step 9`
---------|----------|---------|--------|-------
<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189235034-c9f9ccdf-931a-4038-a1fa-3635e4355750.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189242701-4abed3e4-4bb7-46f9-a28a-45851af424a1.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189242819-1556dc7f-9a82-4505-9d4e-b1cc9c5d0084.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189243040-ae722758-a727-429b-b38f-93e7357f68d1.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189243186-ee6c7e87-3204-4060-8d86-3f0ccd3ec163.png">
</details>

#### Case Four: No thanks - PASSED
<details>

1. Start browser with a new profile.
2. Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
3. Restart the browser.
4. Wait for first page load.
5. Click on `No thanks`
6. Confirm the dialog dismisses
7. Visit another page and verify that the opt-in bubble is not displayed again.
8. Cookie List" filter has not  been enabled in brave://adblock 
9. Restart the browser and verify that the opt-in bubble is not displayed again.

`step 2` | `step 5` | `step 6-7` | `step 8`|`step 9`
---------|----------|---------|---------|----
<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189244082-49f108d3-e468-4d33-b6c9-d1390e7d0fb5.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189242701-4abed3e4-4bb7-46f9-a28a-45851af424a1.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189244151-be2355dc-c52d-4063-80b0-c86b350c11cb.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189245688-710d3d41-fa5e-463f-9b78-c3b208e5615b.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189244980-9d803b0c-6754-40e5-85d9-f3b3923bbf4e.png">

</details>

#### Case Five : Upgrade - PASSED
<details>

1. installed 1.43.89
2. launch Brave
3. visit lemonde.fr, which has cookie consent banner displayed, and close the browser
4. rename the profile folder to Beta
5. install 1.44.79
6. launch Brave
7. Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
8. Restart the browser.
9. Wait for first page load.
10. Verify that the "cookie list opt-in" bubble is displayed.
11. Click the "enable" button.
12. Verify that the bubble is closed after the animation completes.
13. Navigate to brave://adblock.
14. Expand the list of filters, and verify that the "Cookie List" filter has been enabled.
15. return to  another page (lemonde.fr) and verify that the opt-in bubble is not displayed again.
16. Confirmed cookie consent banner is blocked
17. Restart the browser and verify that the opt-in bubble is not displayed again.


`step1-2` |`step 3`|`step 7`|`step10`|`step 12`|`step13-14`|`step15-16`|`step 17`
----|----|-----|----|-----|----|-----|-----
<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189246343-8b0763df-58af-4f1f-a429-f0d4c7fe06c5.png">|<image width="1000" alt="image" src="https://user-images.githubusercontent.com/98358127/189246322-11d0ff9e-8ec0-4828-9765-dc0d02dd52b1.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189246680-b4596407-f58d-442e-80d0-520add788f86.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189233019-9dfb04dd-f9b1-47f6-b685-a9709818c49c.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189233657-5ca8c252-e1d7-4b74-add4-3bc1252d6f70.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189247260-35a93627-21a5-4e71-ae38-733734701455.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189247391-28d8051a-ee90-4776-9a99-84ead5f5861a.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/189247776-3e09c0a4-2ebd-4e9b-98c5-1a6cd70283da.png">



</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.44.88 Chromium: 105.0.5195.136 (Official Build) beta (64-bit) 
--|--
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Linux

### Steps:

#### Case One: New profiles -
<details>

1. Start browser with a new profile.
2. Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
3. Restart the browser.
4. Wait for first page load.
5. Verify that the "cookie list opt-in" bubble is displayed.
6. Click the "enable" button.
7. Verify that the bubble is closed after the animation completes.
8. Navigate to brave://adblock.
9. Expand the list of filters, and verify that the "Cookie List" filter has been enabled.
10. Visit another page and verify that the opt-in bubble is not displayed again.
11. Restart the browser and verify that the opt-in bubble is not displayed again.


`step 2` | `step 5` | `steps 6-7` | `step 9` | `step 10` | `step 11`
---------|----------|-------------|---------|-----------|---------




</details>

#### Case Two: Clicking the X - PASSED
<details>

1. Start browser with a new profile.
2. Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
3. Restart the browser.
4. Wait for first page load.
5. Click the "X" button to close the bubble.
6. Visit another page and verify that the opt-in bubble is not displayed again.
7. Restart the browser and verify that the opt-in bubble is not displayed again.

`step 2` | `step 5` | `steps 6` | `step 7`
---------|----------|-----------|---------



</details>

#### Case Three: Closing the bubble - 
<details>

1. Start browser with a new profile.
2. Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
3. Restart the browser.
4. Wait for first page load.
5. Click outside of the bubble to close the bubble.
6. Visit another page and verify that the opt-in bubble is not displayed again.
7. Restart the browser and verify that the opt-in bubble is not displayed again.

`step 2` | `step 5` | `step 6` | `step 7`
---------|----------|---------|--------






</details>

#### Case Four: No thanks -
<details>

1. Start browser with a new profile.
2. Enable the flag "Show an opt-in bubble for the 'Easylist-Cookie List' filter".
3. Restart the browser.
4. Wait for first page load.
5. Click on `No thanks`
6. Confirm the dialog dismisses
7. Visit another page and verify that the opt-in bubble is not displayed again.
8. Restart the browser and verify that the opt-in bubble is not displayed again.

`step 2` | `step 5` | `step 6` | `step 7` | `step 8`
---------|----------|---------|---------|----------

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per discussion with @kjozwiak and @rebron .
