### ISSUE TITLE
[Android] Inject cosmetic filtering scriptlets in all frames

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#10436]
## Description 

Similar to https://github.com/brave/brave-browser/issues/10319, we need to make sure that ads aren't appearing under embedded YT videos.

## Steps to reproduce 

   1. download/install `1.10.95 CR: 83.0.4103.106`
   2. visit https://www.pcmag.com/news/the-best-vr-games-for-2019 and play through a few of the videos

## Actual result 

You'll see ads being played that aren't skippable as per the following:

![Screenshot_20200623-225112_Brave](https://user-images.githubusercontent.com/2602313/85497302-b17cc280-b5ab-11ea-932a-2e4461becb49.jpg)

## Expected result

Ads shouldn't appear while playing through embedded videos.

## Issue reproduces how often 

100% reproducible when using the STR mentioned above. Sometimes you'll need to run through a few videos before seeing videos.

## Issue happens on 
   - Current Play Store version? `Yes` (reproduced with `1.10.95 CR: 83.0.4103.106`)
   - Beta build? `Yes` (reproduced with `1.10.96 CR: 83.0.4103.106`)

However, can't reproduce with `Nightly` using `1.12.45 CR: 83.0.4103.116`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 10`
   
## Brave version

* Using `1.10.95 CR: 83.0.4103.106` (Release) & `1.10.96 CR: 83.0.4103.106` (Beta)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @antonok-edm @anthonypkeane @SergeyZhukovsky @srirambv

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9 running 1.10.98 x64 build
- Verified test plan from issue description
- Verified on both clean install and upgrade install
- Verified on multiple sites with embedded videos
- Verified no ads when using a VPN and viewing embedded videos
