### ISSUE TITLE
[Desktop] Follow up of #9869 - `Monthly Payment` AC settings are not retained correctly in upgraded profile 1.11.x

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10438]
## Description 

Found while testing #9869 
`Monthly Payment` AC settings are not retained correctly in upgraded profile 1.11.x
## Steps to Reproduce

Scenarios 1:
   1. Clean profile 1.10.x
   2. Enable rewards
   3. Change AC settings values except for monthly payment (keep the monthly payment as it is)
   4. Upgrade profile to 1.11.x
   5. Looks for AC advanced settings value, Monthly Payment value is displayed as `0.0 BAT` and dropdown values are empty
   6. Rest other values are displayed as expected

Scenarios 2:
   1. Clean profile 1.10.x
   2. Enable rewards
   3. Change AC settings monthly payment to 50 BAT or any other value
   4. Upgrade profile to 1.11.x
   5. Looks for AC advanced settings value, Monthly Payment value is empty in UI
   6. Click on dropdown shows only `50.0 BAT` and  other dropdown values are empty
   6. Rest other values are displayed as expected

**Note**: Min page time, visit and other settings are working as expected.
## Actual result:

`Monthly Payment` AC settings are not retained correctly in upgraded profile 1.11.x
Scenario1:
![image](https://user-images.githubusercontent.com/38657976/85531985-e8df8380-b62c-11ea-8fc7-87a47cda62c5.png)
![image](https://user-images.githubusercontent.com/38657976/85532130-10cee700-b62d-11ea-8ec0-922de9b63674.png)

Scenario 2:
![image](https://user-images.githubusercontent.com/38657976/85533985-9bfcac80-b62e-11ea-8309-542b1289c55e.png)
![image](https://user-images.githubusercontent.com/38657976/85534096-afa81300-b62e-11ea-8811-5fcbd3c701f3.png)
![image](https://user-images.githubusercontent.com/38657976/85534211-c9e1f100-b62e-11ea-860e-2efb5f5347a4.png)
![image](https://user-images.githubusercontent.com/38657976/85534302-df571b00-b62e-11ea-93f8-3ec6773f7733.png)

## Expected result:

AC Advanced settings should be retained correctly in upgraded profile 1.11.x

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.11.75 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Windows 10 OS Version 1903 (Build 18362.900)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by GeetaSarvadnya** [comment]
Test plan 2 from https://github.com/brave/brave-core/pull/5647 (Upgraded profile from 1.10.x to 1.11.x)
USD conversion values are displayed 0.0 BAT after the upgrade, but if I reload the page the correct values are displayed 

Various pages where USD conversion value is displayed as 0.0 BAT
![image](https://user-images.githubusercontent.com/38657976/85539461-79b95d80-b633-11ea-8c6e-86608575dff5.png)
![image](https://user-images.githubusercontent.com/38657976/85538647-b769b680-b632-11ea-9ba4-2c9a734cf1e1.png)
![image](https://user-images.githubusercontent.com/38657976/85538719-c7819600-b632-11ea-8ca4-bf4e555e670a.png)
![image](https://user-images.githubusercontent.com/38657976/85538807-dbc59300-b632-11ea-9dc2-80b93e15a01f.png)

**Comment by zenparsing** [comment]
This repros in nightly (1.12) as well. The issue appears to be that "API parameters" are downloaded from the server and updated **after** the rewards page has finished loading data from the rewards service, and is not notified that the parameters (like "batRate", default AC amount, and AC choices) have been updated.

This issue should only appear when the user is migrated from 1.10 and the rewards page is open on restart. A fix will likely require adding a method to `RewardsServiceObserver` to allow the front-end to listen for changes to API parameters.

**Comment by LaurenWags** [comment]
@zenparsing I noticed that if I do the following, I basically encounter scenario 1, but my Rewards page was not open on restart. Does this have the same problem or should it be logged under a new issue?

Steps:
1. Install 1.10.97, Enable Rewards
2. Disable Rewards, close brave://rewards page
3. Rename profile to dev, launch w/ 1.11.x
4. Confirm Rewards are still off on upgrade.
5. Enable Rewards (I did this from the BAT logo panel)
6. Open brave://rewards page (clicked on Rewards Settings on panel)
--> on brave://rewards `Monthly Payment` is 0.000 BAT and that's also the only option available in settings. 
<img width="647" alt="Screen Shot 2020-07-02 at 1 53 21 PM" src="https://user-images.githubusercontent.com/28145373/86393879-a42a9c80-bc6b-11ea-8b0e-3e284014a7b1.png">
<img width="655" alt="Screen Shot 2020-07-02 at 1 53 29 PM" src="https://user-images.githubusercontent.com/28145373/86393884-a68cf680-bc6b-11ea-8dff-af52c019d087.png">

7. Reload of page does not fix. Close/reopen of tab does not fix. However, close/relaunch of the browser + refresh of the opened page after relaunch does fix this.


Brave | 1.11.85 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)

**Comment by zenparsing** [comment]
@LaurenWags Great catch. It looks like there's an additional issue with 1.11 (but not 1.12) where API parameters are not fetched when rewards is enabled. (I believe it's not an issue in 1.12 because the everything is restarted every time rewards is turned on, as opposed to just when the browser is started.)

I need to spend a bit more time looking into whether a single fix will solve both issues.

**Comment by LaurenWags** [comment]
Thanks @zenparsing - happy to open a separate issue if needed just let me know!

**Comment by angellyna1088** [comment]
yes help me open

Vào Th 6, 3 thg 7, 2020 lúc 18:44 Lauren <notifications@github.com> đã viết:

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 

Brave | 1.11.89 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Ubuntu 18.04 LTS

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label - during testing of PR on Nightly noticed that originally reported issues were not resolved. Shared information with @zenparsing for investigation.

**Comment by zenparsing** [comment]
Investigation uncovered two additional issues related to #7024:

- The `Select` component in `brave-ui` has a bug where the currently displayed value is not updated when the list of options is updated. I'll see if I can come up with a workaround to avoid a dependency update.
- The rewards extension is attempting to load wallet data before the state has been transitioned to prefs, and as a result is setting `walletCorrupted` to true. Furthermore, when the "wallet initialized" event occurs, a result of `LEDGER_OK` is is not correctly handled (it should reset `walletCorrupted` to false).

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.11.96 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.15.5 (Build 19F101)
```

**`Scenario #1`** from https://github.com/brave/brave-browser/issues/10438#issue-644483762

| Before Refresh        | After Refresh           |
|:-------------:|:-------------:|
| <img width="852" alt="Screen Shot 2020-07-14 at 12 51 40 PM" src="https://user-images.githubusercontent.com/2602313/87454355-da540e80-c5d1-11ea-96e5-fbbf621bca4f.png"> | <img width="665" alt="Screen Shot 2020-07-14 at 12 52 04 PM" src="https://user-images.githubusercontent.com/2602313/87454263-bb557c80-c5d1-11ea-8562-93b2e339b709.png"> |
| <img width="696" alt="Screen Shot 2020-07-14 at 12 51 50 PM" src="https://user-images.githubusercontent.com/2602313/87454425-ef30a200-c5d1-11ea-85ab-d5b5098cf2b0.png"> | <img width="659" alt="Screen Shot 2020-07-14 at 12 52 20 PM" src="https://user-images.githubusercontent.com/2602313/87454484-07082600-c5d2-11ea-9723-3117ba87d281.png">|

* Verified the closing/re-opening `brave://rewards` several times didn't reproduce the original issue after a refresh
* Verified that restarting Brave several times didn't didn't reproduce the original issue after a refresh
* Verified that enabling/disabling `a-c` several times didn't reproduce the original issue after a refresh

**`Scenario #2`** from https://github.com/brave/brave-browser/issues/10438#issue-644483762

| Before Refresh        | After Refresh           |
|:-------------:|:-------------:|
| <img width="831" alt="Screen Shot 2020-07-14 at 1 07 28 PM" src="https://user-images.githubusercontent.com/2602313/87455366-513dd700-c5d3-11ea-8396-cf1dd036f1d0.png">| <img width="664" alt="Screen Shot 2020-07-14 at 1 07 36 PM" src="https://user-images.githubusercontent.com/2602313/87455395-61ee4d00-c5d3-11ea-8f02-0281bad1a671.png"> |
| <img width="656" alt="Screen Shot 2020-07-14 at 1 07 19 PM" src="https://user-images.githubusercontent.com/2602313/87455460-7b8f9480-c5d3-11ea-8a63-9263665d9965.png">| <img width="664" alt="Screen Shot 2020-07-14 at 1 07 36 PM" src="https://user-images.githubusercontent.com/2602313/87455506-8ea26480-c5d3-11ea-8a31-be06cfdaf59c.png">|

* Verified the closing/re-opening `brave://rewards` several times didn't reproduce the original issue after a refresh
* Verified that restarting Brave several times didn't didn't reproduce the original issue after a refresh
* Verified that enabling/disabling `a-c` several times didn't reproduce the original issue after a refresh

**`Scenario #3`** from https://github.com/brave/brave-browser/issues/10438#issuecomment-653144948

* Verified that after enabling `Rewards` once Brave has been updated, `Monthly Payment` under `brave://settings` doesn't appear as `0.000 BAT`
* Verified that after enabling `Rewards` once Brave has been updated, `Monthly Payment` under `a-c` settings doesn't appear as `0.000 BAT`

Went through the above cases with both the selected default which is `20.000 BAT` and selected `50.000 BAT` from the dropdown. Both cases passed without issues.
