### ISSUE TITLE
[Desktop] Github Inline Tipping Broken

### ISSUE THREAD

**Issue by corymcdonald** [brave/brave-browser#10434]
## Steps to Reproduce

1. New Proxima-ui broke the github commits page for tipping. Other places as well

## Actual result:

![image](https://user-images.githubusercontent.com/5459225/85481014-a5323e80-b586-11ea-925d-8eb8314e5ada.png)

## Reproduces how often: 
Everytime

## Brave version (brave://version info)

Brave | 1.12.25 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.62 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
-- | --
Revision | 37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified in-line tip placement on the following pages:

<details>
<summary>Pull Request</summary>

PR description:
<img width="886" alt="PR description" src="https://user-images.githubusercontent.com/28145373/98373281-04ac5a80-200d-11eb-8e5e-5ccdc6f0376c.png">

PR comment:
<img width="904" alt="PR comment" src="https://user-images.githubusercontent.com/28145373/98373293-070eb480-200d-11eb-828e-1fc768fd3e3a.png">

</details>

<details>
<summary>Issue</summary>

Issue description:
<img width="889" alt="Screen Shot 2020-11-06 at 8 50 58 AM" src="https://user-images.githubusercontent.com/28145373/98373452-43421500-200d-11eb-83b2-dd3db591f260.png">

Issue comment:
<img width="910" alt="Screen Shot 2020-11-06 at 8 51 56 AM" src="https://user-images.githubusercontent.com/28145373/98373511-57861200-200d-11eb-8479-c53bfed4e396.png">

</details>

<details>
<summary>Commits</summary>

<img width="1211" alt="Screen Shot 2020-11-06 at 8 52 46 AM" src="https://user-images.githubusercontent.com/28145373/98373584-75537700-200d-11eb-8ce0-f3d7ef33681d.png">

</details>

<details>
<summary>Starred Repos (must be logged in to GH)</summary>

<img width="1210" alt="Screen Shot 2020-11-06 at 8 53 46 AM" src="https://user-images.githubusercontent.com/28145373/98373666-9916bd00-200d-11eb-9ca1-f90a5dce96c2.png">

</details>

<details>
<summary>Gist</summary>

<img width="1214" alt="Screen Shot 2020-11-06 at 8 54 54 AM" src="https://user-images.githubusercontent.com/28145373/98373781-c19eb700-200d-11eb-8a79-57da3f3751d8.png">

</details>

<details>
<summary>People Page</summary>

<img width="1210" alt="Screen Shot 2020-11-06 at 8 57 26 AM" src="https://user-images.githubusercontent.com/28145373/98374031-1b9f7c80-200e-11eb-8df1-7dcbff624ff6.png">

</details>

<details>
<summary>Team Page (must be logged in to GH)</summary>

<img width="1209" alt="Screen Shot 2020-11-06 at 8 56 48 AM" src="https://user-images.githubusercontent.com/28145373/98373976-062a5280-200e-11eb-97d5-0f6ab615ba9e.png">

</details>

Additional testing was completed with https://github.com/brave/brave-browser/issues/11463#issuecomment-721930510
