### ISSUE TITLE
Adblock doesn't block ads on streaming sites

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1043]
## Description 

Adblock doesn't block ads on streaming sites

## Steps to Reproduce

   1. Visit this `https://movpod.in/w533u5hoq2c7 `
   2. Wait for the page to load
   3. See horrible images which when clicked opens up sites loaded with malware

## Actual result:

Chrome with uBO vs Brave Core
![image](https://user-images.githubusercontent.com/17010094/45258660-59021400-b389-11e8-936b-c000def55fa3.png)

## Expected result:
Should block all images and links which opens up malware sites

## Reproduces how often: 

Easy

## Brave version (about:brave info) 

Brave | 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

Yes. https://github.com/brave/browser-laptop/issues/11233

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Chrome with uBlock Origin blocks all ads and popups

**Comment by ryanbr** [comment]
Safe to close? @srirambv  Site seems to be dead
