### ISSUE TITLE
Remove URLs from Brave Suggested Sites

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#10431]
## Description 
Brave Suggested Sites is already disabled by default.
And it never matches user typed things if the user manually enables it (i.e. the user must arrow down or click).

But we'd also like to remove anything that is a URL as well.  This issue is to do that last part.

## Steps to Reproduce

   1. Manually enable Brave Suggested sites
   2. Type binan

Alternately
   1. Manually enable Brave Suggested sites
   2. Type ledg

## Actual result:

Suggestion appears

## Expected result:

No suggestion should appear

## Reproduces how often: 

Always when manually enabled.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Using STR from description, reproduced issue using `1.11.97` (Release)
* Verified STR from description on `1.12.94`
<img width="1095" alt="Screen Shot 2020-07-20 at 4 11 24 PM" src="https://user-images.githubusercontent.com/28145373/87981879-f1986d80-caa3-11ea-938b-b92e96cc35c8.png">
<img width="1045" alt="Screen Shot 2020-07-20 at 4 11 47 PM" src="https://user-images.githubusercontent.com/28145373/87981882-f2c99a80-caa3-11ea-9801-005e4eb179e6.png">

* Confirmed typing something else like `bitco` does show the suggested site (when setting is enabled):
<img width="1094" alt="Screen Shot 2020-07-20 at 4 13 02 PM" src="https://user-images.githubusercontent.com/28145373/87981920-01b04d00-caa4-11ea-85a8-ff70dcde45e0.png">
