### ISSUE TITLE
[Desktop] Import password from CSV has no effect

### ISSUE THREAD

**Issue by tiagosiebler** [brave/brave-browser#10437]
## Description 

I'm trying to migrate my brave setup to a new mac. I've exported the passwords.csv from my old machine, then on the new machine I've tried to import them from the "saved passwords' section in settings:
brave://settings/passwords

This import does absolutely nothing. In case there was a csv corruption, I've tried the same CSV file with only two lines: the header and one sample row. I've attached this CSV. Nothing happens after import...

## Steps to Reproduce

   1. go to settings password page
   2. on the "saved passwords" section, click the menu to import from csv
   3. nothing happens after selecting the CSV

## Actual result:
No change in UI

## Expected result:
List of imported passwords or error/warning

## Reproduces how often: 

Always, easily reproduced

## Brave version (brave://version info)

- 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
- ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
- macOS Version 10.15.5 (Build 19F101)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 
TBC

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome?  no, works fine in Chrome

## Miscellaneous Information:

Here is a CSV you can reproduce the issue with - it works in chrome, but not in brave:
[bravePwd copy.csv.zip](https://github.com/brave/brave-browser/files/4823919/bravePwd.copy.csv.zip)

**Comment by tiagosiebler** [comment]
I've also tried copying Application Support for the brave directories across. It worked for the majority of the settings, but seems passwords weren't caught by that. Would love other ideas to migrate passwords across, if this import feature is currently broken.

**Comment by simonhong** [comment]
Did you copy user data dir then trying to import pwds from csv?
If so, current stable has the bug(https://github.com/brave/brave-browser/issues/3196) - pwds are not visible in settings page.
That fix is not yet arrived to stable.(currently in beta).
If you imported, maybe browser autofills pwds but not visible in settings.
Is this your case?

**Comment by tiagosiebler** [comment]
Did some more testing, seems the fact that I copied brave's application support folders over is interfering with the passwords feature. I've done a reset in the new machine's brave and imported passwords in the fresh install, seems to work there... happy to close this

**Comment by simonhong** [comment]
@tiagosiebler CSV Importing will work if there is no corrupted passwords in current user data.
I'll close this issue :)
