### ISSUE TITLE
[Desktop] Sync icon needs update

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#10448]
New icons:

#### Old
![image](https://user-images.githubusercontent.com/741836/85618608-dad23880-b615-11ea-91ea-ea527f88e51d.png)

#### New
![image](https://user-images.githubusercontent.com/741836/85618686-ffc6ab80-b615-11ea-8b30-69d8ea1ff0c9.png)

**Comment by rebron** [comment]
@petemill Is this issue still needed? Didn't look like we got this in time and can probably close out.

**Comment by rebron** [comment]
Closing as stale.
