### ISSUE TITLE
Video frames not visible on streaming sites

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1044]
## Description 

Video frames not visible on streaming sites

## Steps to Reproduce

   1. Open Chrome webstore
   2. Open Drak reader extension
   3. Click on the YT video to play
   4. Change the video settings to a high resolution playback
   5. Click on YouTube button to load the video on a new tab in YouTube
   6. Video frame freezes and mouse over makes it choppy (audio plays fine but video is not visible just chopped frame)
   7. Change video resolution, no difference
   8. Reload YT page, no change
   9. Load other suggested video, shows video correctly 

## Actual result:

![video1](https://user-images.githubusercontent.com/17010094/45258792-92884e80-b38c-11e8-9919-39f9b50424ab.gif)

## Expected result:
Video playback should show frames correctly and should not be chopped or corrupted

## Reproduces how often: 

Easy

## Brave version (about:brave info) 

Brave | 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

This is not limited to YouTube with high resolution playback. Happens on other streams as well.
@brave/legacy_qa  to verify on other platforms as well. 
cc: @bbondy @bridiver @simonhong

**Comment by bbondy** [comment]
how does Chromium 70 on your machine handle the same steps?

**Comment by srirambv** [comment]
Works just fine on Chrome Canary (71.0.3546.0)
![video2](https://user-images.githubusercontent.com/17010094/45260320-697ab480-b3b2-11e8-821c-93757665b8e6.gif)

**Comment by srirambv** [comment]
Verified on Chrome Dev (70.0.3538.9) and no issues.

**Comment by srirambv** [comment]
I think this was an issue with `Enable Picture in Picture` flag enabled in `chrome://flags`. I had it enabled for testing and it looks like setting it back to `Default` fixed this issue.
