### ISSUE TITLE
[Desktop] Window buttons/tabs spacing issue on macOS 11

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#10441]
## Description 

The spacing between window buttons and tabs is incorrect as they are too close together. This only seems to be happening on the macOS 11 Dev betas.

## Steps to Reproduce

   1. Open Brave (Release, Beta, Dev, and Nightly)
   2. Look at the window buttons
   3. Look at the tabs

## Actual result:

![Screen Shot 2020-06-24 at 11 24 01 AM](https://user-images.githubusercontent.com/21181118/85594083-3c41d980-b60d-11ea-91c6-45eb26b1a6df.jpg)

## Expected result:

Proper spacing between buttons and tabs.
![how-to-uninstall-Brave-on-mac-osx-uninstaller-1](https://user-images.githubusercontent.com/21181118/85592773-1405ab00-b60c-11ea-82ba-da343504b4a5.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

All Brave builds

## Version/Channel Information:

Happens on Release, Beta, Dev, and Nightly

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes, but not as extreme:

macOS 11:
![Screen Shot 2020-06-24 at 11 21 01 AM](https://user-images.githubusercontent.com/21181118/85593890-0f8dc200-b60d-11ea-9a59-922e6764d6c2.jpg)

macOS 10.15:
<img width="352" alt="thread-3880471-18099632503526762764" src="https://user-images.githubusercontent.com/21181118/85593921-17e5fd00-b60d-11ea-85fe-02d849901f60.png">

**Comment by gottabeleGIT** [comment]
Question: is this a Chromium issue (and Brave is waiting on a fix from them) or would Brave and others need to implement their own fixes?

**Comment by rebron** [comment]
<img width="387" alt="Screenshot 2022-08-17 at 1 05 21 PM" src="https://user-images.githubusercontent.com/5951041/185232625-cdbc33ce-4a8e-4650-acd6-1412e2f0744f.png">
Closing as stale. @ghost Correct in that this was resolved with the chromium pull at that time.
