### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by evaneaston** [brave/brave-browser#10456]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.97  Chromium: 83.0.4103.116
Operating System: Windows NT 10.0.18363

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.Start browser
2. Wait ~1-2 minutes
3. Crash

Cleared history and removed all extensions.  Sill happens.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/0cb10000-1c55-8704-0000-000000000000

**Comment by bsclifton** [comment]
@evaneaston curious if you have sync enabled? Can you check out brave://flags/#brave-sync? 

If so, let's try disabling that. There were some known crashes which were discovered when upgrading to Chromium 83.

Sync v2 is on the way- it's live in Nightly (only for desktop) which will be working it's way through the release channels (expected on stable ~Aug 4)

**Comment by bsclifton** [comment]
Confirmed above is a crash related to sync - you can disable via brave://flags/#brave-sync or from the CLI passing in `--disable-sync`
