### ISSUE TITLE
[Desktop] Hide sync toggle for payment integration

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#10453]
We don't support pulling payment info from Google pay for our sync service

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5936

![image](https://user-images.githubusercontent.com/34715963/89459268-a9966d80-d768-11ea-99d3-20f785a4cbbb.png)
