### ISSUE TITLE
[Desktop] when setting is enabled, show bookmarks bar on NTP even if there aren't any bookmarks

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10450]
## Description 

Follow up to #3568

In the issue above, we added informational/instructional text on the bookmarks bar to prompt users to import bookmarks. However, we don't show the bookmarks bar on NTP without any bookmarks (noted in https://github.com/brave/brave-browser/issues/3568#issuecomment-644760792). 

Per discussion with @rebron since `Always show bookmarks on New Tab page` is the default setting, we should show this informational text on the bookmarks bar on the NTP.

## Steps to Reproduce

   1. Clean profile 1.11.x
   2. You don't instructional text on the bookmarks bar on the welcome screen (because `Show Bookmarks` is toggled off per default settings). This is fine.
   3. Open NTP.

## Actual result:

No bookmarks bar is displayed because there aren't any bookmarks

## Expected result:
Bookmarks bar should be displayed with the instructional text from #3568

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.11.75 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a, text only added with 1.11.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @simonhong

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description

<img width="1197" alt="Screen Shot 2020-07-17 at 8 39 43 AM" src="https://user-images.githubusercontent.com/28145373/87817250-a4639400-c836-11ea-86dd-42b7892803c6.png">

**Comment by kjozwiak** [comment]
`Import bookmarks now..` doesn't appear as a link when using the default light theme. Created https://github.com/brave/brave-browser/issues/10798.

<img width="1234" alt="Screen Shot 2020-07-17 at 11 40 13 PM" src="https://user-images.githubusercontent.com/2602313/87844178-d00f6a00-c888-11ea-8036-b5c851928b5c.png">
