### ISSUE TITLE
[Android] Remove cookie exceptions for android

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10455]
## Description 
Android doesn't have the socialMediaBlocking toggle to disable cookie exceptions. Disable cookie exceptions till `socialMediaBlocking` is enabled.

**Comment by bsclifton** [comment]
Ticket to track adding Social Media Blocking functionality:
https://github.com/brave/brave-browser/issues/9536

**Comment by bsclifton** [comment]
Bumping to P2 per recommendation by @pes10k as there is no way to disable this functionality on Android at the moment

**Comment by jumde** [comment]
With this change we need to verify if:

https://github.com/brave/brave-browser/issues/5869 
https://github.com/brave/brave-browser/issues/5075
https://github.com/brave/brave-browser/issues/9852
https://github.com/brave/brave-browser/issues/10367

are working correctly.

**Comment by jumde** [comment]
Will be addressed by: https://github.com/brave/brave-browser/issues/9536
