### ISSUE TITLE
Buttons on Torrent viewer needs spacing

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1045]
![image](https://user-images.githubusercontent.com/17010094/45259276-d41df700-b396-11e8-9060-81ec77ba6d97.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

* Verified using test plan from https://github.com/brave/brave-core/pull/544
