### ISSUE TITLE
[Android] Sync v2 update device list when device leaving the chain

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10460]
When device leaves the chain, it should send delete device record to allow other devices in chain be informed and update the list.

Similar to desktop issue https://github.com/brave/brave-browser/issues/10198

**Comment by AlexeyBarabash** [comment]
STR (from linked issue https://github.com/brave/brave-core/pull/6027)

1. Create sync chain on desktop
2. Connect phone to the sync chain
3. Ensure there are two devices in list on desktop and phone
4. Reset sync chain on phone 
5. Wait < 1 min and ensure there is just one device on the desktop

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.12.109 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/10460#issuecomment-655186912
---------------
Verification passed on OnePlus 6T with Android 10 running 1.12.109 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/10460#issuecomment-655186912
