### ISSUE TITLE
Brave Contribute needs better wordings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1046]
## Description 

Monthly budget is renamed to Brave Contribute which sounds like what Brave is going to contribute for monthly reconcile. This needs better wording to avoid confusion

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/45259664-bb660f00-b39f-11e8-8320-2ab55c28fdfa.png)

## Brave version (about:brave info) 

Brave | 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | All

### Additional Information

cc: @bradleyrichter @bbondy @davidtemkin

**Comment by alexwykoff** [comment]
@jenn-rhim

**Comment by bbondy** [comment]
@jenn-rhim are you suggesting a change from "Brave Contribute" to "Brave Auto-Contribute"? Or do you just want this closed altogether?

**Comment by jenn-rhim** [comment]
Brave Auto-Contribute is the correct name. So it is a bug that we need the string fix.

**Comment by davidtemkin** [comment]
@jenn-rhim That's the name of the feature. The bug refers to how your monthly contribution is listed in the transaction table, which could be seen as confusing, per @srirambv . We **may** need to clarify it there, e.g., "Brave Auto-contribute monthly payment" (yes, lots of words). In any case, I am planning a review of all strings in Brave Rewards. I'd leave this open for now. cc: @bbondy

**Comment by bbondy** [comment]
Moving to 1.x until we have this clarified more.

**Comment by bradleyrichter** [comment]
one idea - remove "Brave" which should solve the original issue.

Result: 

Token Grant                10
Auto-Contributions   -10
Total                              0

**Comment by bbondy** [comment]
@davidtemkin are you ok with that?  Will move back once we have consensus on something.

**Comment by davidtemkin** [comment]
@bbondy it's an improvement, and fixes the problem Sri reported, but all strings in Brave Rewards need to be edited and this will be reviewed as part of that process. I.e., it could change again.

**Comment by NejcZdovc** [comment]
this was renamed to `Auto-Contribute`, so closing
