### ISSUE TITLE
[Desktop] website uses to much ram compared to chrome https://www.wetter.com/

### ISSUE THREAD

**Issue by epicodertime** [brave/brave-browser#10463]
## Description 
it uses too much ram and it keeps on going up

## Steps to Reproduce
 go to  https://www.wetter.com/ with brave shield disabled  

## Actual result:
it uses more ram than chrome

## Brave version (brave://version info)
brave stable 1.10.97

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no

<img width="951" alt="ram usage brave vs chrome" src="https://user-images.githubusercontent.com/41688975/85648195-3b8d5f80-b66e-11ea-9fd4-b3e6a18552c9.PNG">

**Comment by epicodertime** [comment]
and with  no extensions installed

**Comment by ryanbr** [comment]
The site is quite heavy on adservers and trackers. I just tested in a new brave profile and chrome (extensions disabled).

The delta between Chrome and Bave is around ~300Mb. 

![wetter](https://user-images.githubusercontent.com/1659004/85945962-43fad880-b995-11ea-8818-d5c6af8857c3.png)

Would re-test in Brave Beta?

**Comment by rebron** [comment]
@epicodertime Can you update to 1.12.112 and let us know if you're still having this issue?

**Comment by epicodertime** [comment]
the issue seems fixed
