### ISSUE TITLE
Prevent UI reflow on google.com search results in standard adblocking mode

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#10461]
Currently, when brave is in default cosmetic blocking mode, there is jitter on google.com when the 1p search ad is at first hidden, and then un-hidden after the process runs.

This issue is to put in place a short term, hacky fix to not apply `##.ads-ad` on `https://*.google.*/*` (or similar) when brave is in the default blocking mode, to prevent jitter

this is a short term solution for a bigger, more proper default-mode-exceptions component + service

**Comment by ryanbr** [comment]
could we just create `google.com#@#.ads-ad` in brave-unbreak, would that work?

**Comment by irfaneru** [comment]
Dear sir
Sorry  for If I send you a wrong information.
But actually sir I want to restore or recover my login details as username
and password.
Because my all rewards data gets disappear from my browser.
I have listed much more valuable information from brave browser.
I don't know how it happened, but I want my all details back.
Plz reply and solve my problem

**Comment by pes10k** [comment]
@irfaneru i am deleting your message because it is unrelated to this tread.  https://community.brave.com/ is the right place for that kind of question

**Comment by pes10k** [comment]
@ryanbr that wouldn't work bc then it would not be applied in strict / 1p blocking mode

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.94 Chromium: 84.0.4147.85 (Official Build) (64-bit)
-- | --
Revision | e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{#837}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Reproduced the reflow issue using `1.11.92` on google.com with various searches
* Verified the test plan from https://github.com/brave/brave-core/pull/5991
* Confirmed ads appear at the top on google.com searches (for certain searches such as `remove my online footprint`, `samsung galaxy phone`, etc) when in `Standard` mode for trackers & ad blocking. Confirmed the ads appear at the same time as other content, no re-flow was observed.
<img width="1194" alt="remove my online footprint - std" src="https://user-images.githubusercontent.com/28145373/87163094-d56f2200-c294-11ea-851d-cbfd6355aca8.png">
<img width="1194" alt="samsung galaxy phone - std" src="https://user-images.githubusercontent.com/28145373/87163096-d738e580-c294-11ea-9c95-46273de1e368.png">
<img width="1192" alt="delete my online data - std" src="https://user-images.githubusercontent.com/28145373/87163101-d86a1280-c294-11ea-9281-a8f1f9ca93da.png">

* Confirmed ads do not appear at the top on google.com searches (again, used searches as above, from the test plan, and others) when in `Aggressive` mode for trackers & ad blocking.
<img width="1194" alt="remove my online footprint - aggressive" src="https://user-images.githubusercontent.com/28145373/87163112-db650300-c294-11ea-90e5-1a06570081f6.png">
<img width="1196" alt="samsung galaxy phone - aggressive" src="https://user-images.githubusercontent.com/28145373/87163118-dc963000-c294-11ea-8583-61d102a89b93.png">
<img width="1195" alt="delete my online data - aggressive" src="https://user-images.githubusercontent.com/28145373/87163124-de5ff380-c294-11ea-99ee-5cd36fb88b78.png">
