### ISSUE TITLE
[Desktop] wallet not using latest version of Trezor Connect

### ISSUE THREAD

**Issue by SCBuergel** [brave/brave-browser#10468]
## Description 
brave://wallet still uses v7 of [Trezor Connect](https://github.com/trezor/connect) and not the suggested and more secure v8.

## Steps to Reproduce
   1. Setup a Trezor hardware wallet with latest firmware and connect it to your computer
   2. Open [brave://wallet](brave://wallet)
   3. In your accounts list, click `Connect Hardware Wallet`
   4. Select `Trezor` in and click `Connect`

## Actual result:
This opens https://connect.trezor.io/7/popup.html which is not the latest version

## Expected result:
I expect to be redirected to https://connect.trezor.io/8/popup.html which is the latest version

## Reproduces how often: 
Every single time

## Brave version (brave://version info)
```
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Linux
```

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No

- Does the issue resolve itself when disabling Brave Rewards? 
No

- Is the issue reproducible on the latest version of Chrome? 
Not applicable as Chrome does not ship with an integrated wallet but this is already resolved in the latest version of MyEtherWallet and MyCrypto which both redirect to v8.

**Comment by ryanml** [comment]
Related upstream issue: https://github.com/MetaMask/metamask-extension/issues/8349

**Comment by snodnipper** [comment]
I tried using it just this morning.  Attempting to select an address to enable the Unlock button is not possible at the moment 😞
![Screenshot 2020-08-10 at 12 35 52](https://user-images.githubusercontent.com/576719/89752387-bc14fc00-db06-11ea-89a7-5fc1c8bc7c85.png)

**Comment by ryanml** [comment]
@snodnipper - looks to be an issue with our dark theme. Can you try to change to the light theme via brave://settings and see if you can get through that screen?

**Comment by snodnipper** [comment]
Well I did change it to light _but_ I have more fundamental issues now.  The https://connect.trezor.io/7/popup.html is just endlessly looping.  I have closed other browsers / tabs and https://wallet.trezor.io/ seems to work as expected.

I see others have had this issue too with older versions of metamask https://community.brave.com/t/both-brave-wallet-and-trezor-connect-pages-hang-indefinitely-when-trying-to-connect-a-trezor-for-the-first-time/132401/4

I am using Metamask 8.0.6, which is working fine when accessing web3 sites.

@ryanml I am guessing that you do not have a Trezor to test out yourself?

![Screenshot 2020-08-10 at 18 38 50](https://user-images.githubusercontent.com/576719/89774609-c9e37500-db38-11ea-9d1c-22a9425920e7.png)

**Comment by HeroHann** [comment]
Might be related to this: https://github.com/MetaMask/metamask-extension/issues/8349

Please have a look. With Brave Wallet I get the same problem as with MetaMask.

Main problem: There is no option to input the passphrase directly on the Trezor instead we are forced to input it into the browser, which is a security risk.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/issue-loading-crypto-wallets/164325

**Comment by yumyum0** [comment]
I'm having a different issue entirely. I am not able to get to that screen at all. I will put the error message below. One issue that it might have been was that my Trezor wasn't connected during the process of me clicking connect. Also, I'm not sure how to reset it, as I don't have any assets in that account anyway. I wouldn't mind making a new one.

TypeError: Cannot read property ‘balance’ of undefined
at chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui.js:1:2576729
at chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1186943
at chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1187437
at y (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui.js:1:2576682)
at ha (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1059446)
at ju (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1104711)
at kl (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1090256)
at Rl (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1090181)
at xl (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1087521)
at ml (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1084265)
at is (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1112272)
at chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1113505
at Sl (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1087872)
at cs (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1113490)
at render (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui-libs.js:1:1115419)
at chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/ui.js:1:3584895

**Comment by yumyum0** [comment]
Updating Brave to the latest version and making sure the Trezor seemed to fix the issue.

**Comment by bitofit** [comment]
This thread was hijacked by an unrelated issue.  Brave still needs to update to Trezor Connect V8.  Version 7 requires users to type their passphrase into the browser instead of on device which is a security concern.

**Comment by bitofit** [comment]
> Related upstream issue: [MetaMask/metamask-extension#8349](https://github.com/MetaMask/metamask-extension/issues/8349)

This issue was resolved by Metamask back [in January](https://github.com/MetaMask/metamask-extension/issues/8349#issuecomment-759066594).  Brave Wallet still needs to upgrade from Trezor popup V7 to V8.

**Comment by bitofit** [comment]
@srirambv @ryanml can this be re-visited?  Requiring passphrases to be typed into the computer vs on hardware device is a serious security concern that should be addressed ASAP.

**Comment by Fluxty** [comment]
> @srirambv @ryanml can this be re-visited? Requiring passphrases to be typed into the computer vs on hardware device is a serious security concern that should be addressed ASAP.

Agreed. Need to update Trezor connect for Brave wallet.

**Comment by srirambv** [comment]
This will probably be addressed in the native wallet integration

cc: @bbondy @onyb @Douglashdaniel

**Comment by onyb** [comment]
It'll be a while for the native wallet to be ready. If this is a low-effort task, I think we should add support for Trezor Connect V8 in [ethereum-remote-client](https://github.com/brave/ethereum-remote-client), since this has security implications.

@srirambv Any chance you got a Trezor Model T to help with the tests?

**Comment by srirambv** [comment]
@onyb Nope only Tezor One. Doesn't work wit Brave as we still don't support V8

**Comment by onyb** [comment]
Just added support for Trezor Connect v8 with https://github.com/brave/ethereum-remote-client/commit/6bd81fa69552deca0b03596c6c4a2af7ac31a408. I was able to do a successful transaction with a Trezor Model T + on-device passphrase, using https://github.com/brave/ethereum-remote-client/pull/268.

@srirambv I updated the QA plan for EIP-1559 to include tests for Trezor integration (see https://github.com/brave/brave-browser/issues/17160).

Additionally, we're ready with support for Type-2 transactions (EIP-1559) on Trezor, and will enable it as soon as the new firmware is available (ETA September 8, 2021).

**Comment by srirambv** [comment]
Moved it into release milestone based on previous comment. Will be testing the Trezor connect using Trezor one for now

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (x86_64)
-- | --
Revision | `c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}`
OS | macOS Version 11.5.2 (Build 20G95)
Component | `1.0.38 dev`

- Verified able to connect Trezor and unlock the account
 
![image](https://user-images.githubusercontent.com/17010094/132724885-6b470287-2014-4e0f-a507-f761b827bb60.png) | ![image](https://user-images.githubusercontent.com/17010094/132726733-9a8ac3d5-f0d6-4ff3-8d5a-3d3077b677eb.png)
-- | --

--------
Verification passed on

Brave | 1.30.65 Chromium: 93.0.4577.63 (Official Build) beta (64-bit)
-- | --
Revision | `ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}`
OS | Linux
Component | `1.0.38 dev`

- Verified able to connect Trezor and unlock the account
 
![image](https://user-images.githubusercontent.com/17010094/132727141-d12ad948-2b34-495a-bd2d-598d27175adf.png) | ![image](https://user-images.githubusercontent.com/17010094/132727173-697ef446-153b-49fb-993f-5a41dda39c58.png)
-- | --

---------
Verification passed on 

Brave | 1.31.27 Chromium: 93.0.4577.63 (Official Build) nightly (64-bit)
-- | --
Revision | `ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}`
OS | Windows 10 OS Version 2009 (Build 19043.1165)
Component | `1.0.38. dev`

- Verified able to connect Trezor and unlock the account
 
![Trezor Unlock](https://user-images.githubusercontent.com/17010094/132726994-d8fe8df3-51e1-4177-a81f-408495c283da.PNG) | ![Trezor Account](https://user-images.githubusercontent.com/17010094/132726985-357eeb01-c845-45b2-bb65-ccc39e671bcf.PNG)
-- | --
