### ISSUE TITLE
[Desktop] Remove Brave Account branding for password storage

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10469]
## Description 

 Remove Brave Account branding for password storage

## Steps to Reproduce

   1. Enable Sync on nightly
   2. Create an account on a page, suggests password to store which has Brave Account branding
   3. Save Password modal also has Brave Account branding

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/85718574-4696cd00-b70c-11ea-9372-dcc64c10ac96.png)
![image](https://user-images.githubusercontent.com/17010094/85718606-4dbddb00-b70c-11ea-8018-1bf933b0a4ce.png)

## Expected result:
No Brave Account branding anywhere in the product.
Replace `Brave Account` with `Brave sync chain`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.12.45 Chromium: 83.0.4103.116 (Official Build) nightly (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{# 716}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?  NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @darkdh @rebron @bsclifton @jsecretan @brave/legacy_qa

**Comment by jsecretan** [comment]
So @rebron is Brave Sync Chain ok alternative text here?

**Comment by rebron** [comment]
Alternative text of `Brave Sync Chain` to replace is good here.

**Comment by rebron** [comment]
cc: @darkdh

**Comment by rebron** [comment]
Verified:

Brave | 1.14.27 Chromium: 85.0.4183.59 (Official Build) nightly (64-bit)
-- | --
Revision | 7cc9a5ee672625c38427a839cb1b15efd3128084-refs/branch-heads/4183@{#1216}
OS | macOS Version 10.16 (Build 20A5343i)

Looks good:

<img width="325" alt="Screen Shot 2020-08-07 at 8 51 36 AM" src="https://user-images.githubusercontent.com/5951041/89800601-ddb0bc00-dae3-11ea-9506-4ef31179bcff.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.13.73 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1903 (Build 18362.1016)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/6317
- Verified that the text is displayed as `Passwords are saved in your Brave sync chain so you can use them on any device` when clicking on password icon in the URL bar
![image](https://user-images.githubusercontent.com/38657976/90509322-c6726e00-e176-11ea-9a55-e5b702d50ba1.png)
