### ISSUE TITLE
[Desktop] MALWARE install attempts via Brave Browser Helper (Linkangood.com)

### ISSUE THREAD

**Issue by mannyrules** [brave/brave-browser#10470]
## Description 
Avast antivirus periodically informs me that it has protected me from attempted malware being installed by visiting random, seemingly innocuous sites (sometimes scholarly/education sites).

## Steps to Reproduce

   1. Using LittleSnitch Network Monitor, I typed in "linkangood.com" and found many connections to this site, but only through "Brave Browser via Brave Browser Helper (see **[screenshot](https://www.dropbox.com/s/sixaf0wesekm7v6/Screenshot%202020-06-25%2009.52.20.png?dl=0)**)
   2. I clicked each one and found these IPs being used over and over to connect to Linkangood.com:

- 23.111.228.4
- 23.111.228.220
- 64.58.121.60
- 64.58.126.236
- 172.241.69.4
- 172.241.69.20
- 172.241.69.28

3. I couldn't remember what site I had just visited when the latest Avast warning poped up, but this **[SCREENSHOT](https://www.dropbox.com/s/8emazpk5dqvahy5/Screenshot%202020-06-25%2010.25.49.png?dl=0)** shows the last websites that Brave Browser Helper visited ... except that I clicked the one just before linkangood, (ampproject.org), and it switched to the position you now see on this screenshot). I don't know if this is the culprit because clicking on it gave me a 404 error.

   3. I have since created a LittleSnitch rule to prevent incoming and outgoing connections to these IP addresses as well as www.linkangood.com

3. I have also turned off some of my plugins, but I have no way of knowing if any of them were the culprit.

## Reproduces how often: 

Intermittent issue/No steps to reproduce

## Brave version (brave://version info)

Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
![Screenshot 2020-06-25 10 25 49](https://user-images.githubusercontent.com/9612595/85729063-dc136c00-b6ce-11ea-9738-0636170a74fa.png)
![Screenshot 2020-06-25 09 52 20](https://user-images.githubusercontent.com/9612595/85729090-e2a1e380-b6ce-11ea-88f6-ed36b9e0b111.png)

[Here is a screenshot](https://www.dropbox.com/s/0r94xiyqhm3wdxv/Screenshot%202020-06-25%2010.32.07.png?dl=0
![Screenshot 2020-06-25 10 32 07](https://user-images.githubusercontent.com/9612595/85729516-43312080-b6cf-11ea-96c7-98f213188bf1.png)
) of the extensions I still have installed:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by epicodertime** [comment]
It’s possibly the update service to update brave as it is using a server close to you maybe

**Comment by mannyrules** [comment]
I can't say for sure. For now, I'll turn of the littlesnitch rules I created, and the next time I get a warning from Avast Antivirus, I'll take a screenshot and upload it here.

**Comment by rebron** [comment]
cc: @jonathansampson When you have a chance can you help verify this one?

**Comment by jonathansampson** [comment]
Those IP addresses are a subset of the many found when examining the A records for that domain: https://tools.dnsstuff.com/#adr|type=domain&&value=linkangood.com. The full set is shown below:

- 108.61.12.163
- 108.61.150.91
- 109.201.142.225
- 172.241.69.20
- 172.241.69.28
- 172.241.69.4
- 23.111.228.220
- 23.111.228.4
- 46.166.189.99
- 52.34.19.133
- 64.58.121.60
- 64.58.126.236
- 77.247.183.137
- 85.159.232.241

It does look like the user's browser requested something from that domain, but it doesn't look like the browser itself (meaning, Brave itself) specifically did this. Instead, it seems more likely that a a tab, extension, or iframe may have requested this endpoint.

If the request can be mapped to a Process ID, we could identify which extension/page is responsible for the call. Brave's internal Task Manager (found within the ☰ menu, under More Tools) could be helpful.

Closing for now, unless we have reason to believe this is anything but normal web traffic.
