### ISSUE TITLE
[PageGraph] Migrate web API logging to use enum-based interface

### ISSUE THREAD

**Issue by jueckstock** [brave/brave-browser#10477]
As of [commit 5261dd0](https://github.com/brave/brave-core/commit/5261dd03921ae84416f793a8276fd6802ee7e9ed), there are new `PageGraph::RegisterWebAPICall` and `PageGraph::RegisterWebAPIResult` interfaces that take an enum value to identify the invoked web API instead of a string.  The enum-based approach was already in place for JS-builtin logging and is preferred as it provides compile-time checking for typos.  However, all of PageGraph's older patches for web API logging still use the old string-based interface.  As time allows, we need to convert all usage of the old string-based interface over to the new enum-based interface (and eliminate the old string based interface entirely).

**Comment by goodov** [comment]
not relevant in the current PG implementation.
