### ISSUE TITLE
[Android] DDG offer is misaligned on private tab

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#10476]
## Description 
![Screenshot from 2020-06-25 16-47-03](https://user-images.githubusercontent.com/30602739/85793843-9fae3300-b703-11ea-821b-687282b56bc7.png)

## Steps to reproduce 

   1. On tablet go to private tab
   2. Decline DDG offer

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.10.94

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
@jamesmudgett @anthonypkeane could you specify how it should look. Is it on the bottom of the screen, centered horizontally?

**Comment by anthonypkeane** [comment]
Don't fix, v minor and updates are coming soon
