### ISSUE TITLE
Block autoplay by default but allow the user to change it

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1047]
I think the popup window is too much on each site and can get in the way of browsing. I find it almost as annoying as the autoplay itself. I think just the URL bar thing like widevine is enough.

Putting in 1.x backlog, but I'd love a patch.

**Comment by rebron** [comment]
Autoplay without sound is on by default in chrome/firefox/safari. We should match that behavior for autoplay without sound. 

Example: https://www.simplehuman.com and https://www.tesla.com/models (scroll to mid-page car driving video - range section)

**Comment by bbondy** [comment]
We'll do the sound only task in the context of https://github.com/brave/brave-browser/issues/1088

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/46178244-57f04280-c2b6-11e8-8e4b-6ac69a285ea0.png)
