### ISSUE TITLE
[Desktop] Gmail image signatures not loading

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#10478]
## Description 
Signatures images not showing in Gmail

## Steps to Reproduce

   1. Open Gmail
   2. Open settings
   3. Scroll down to Signature
   4. Create new signature, give it a new name
   5. Click on `Insert Image`
   6. Click Upload, Find any image on your PC

## Actual result:
![signature-broken](https://user-images.githubusercontent.com/1659004/85798845-578a2180-b792-11ea-91c3-a3d5edf02bd0.png)

## Expected result:
![signature-broken2](https://user-images.githubusercontent.com/1659004/85799005-a33ccb00-b792-11ea-9249-0f51e86025b9.png)

## Reproduces how often: 
Easily, with Shields enabled/default.

## Brave version (brave://version info)
`Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes (allow all cookies)
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

As a temp option, Allow all cookies fixes this.  Tested referrer issues, not affecting it.

Cookie issues from `googleusercontent.com`, we should allow cookies on `google.com` domain. 
![google-cookies](https://user-images.githubusercontent.com/1659004/85799204-f57dec00-b792-11ea-8121-97584fd31ceb.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Reproduced issue using 1.11.97:
<img width="859" alt="11197 - reproduce" src="https://user-images.githubusercontent.com/28145373/88067290-d0379000-cb3c-11ea-9ab2-da7afa6da876.png">

* Upgraded to 1.12.x and confirmed issue resolved:
<img width="865" alt="11294 - upgrade" src="https://user-images.githubusercontent.com/28145373/88067320-d88fcb00-cb3c-11ea-9eeb-5f04ab28038c.png">

* Verified STR from description using a clean profile:
<img width="863" alt="11294 - clean" src="https://user-images.githubusercontent.com/28145373/88067349-df1e4280-cb3c-11ea-9fa6-d53d50c98e07.png">

--------
