### ISSUE TITLE
[Android] Implement native Rewards Setting page

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#10472]
## Description 

Implement a native Rewards Setting page on Android

@jamesmudgett to work with Design to finalize a design and assets

## NOTE (@bsclifton via triage): 

fix should:
- take into account the tips screen shown in https://github.com/brave/brave-browser/issues/10310
- also take into account the auto-contribute screen shown in https://github.com/brave/brave-browser/issues/7613

**Comment by jamesmudgett** [comment]
## UX
![Settings Flow Mobile](https://user-images.githubusercontent.com/318119/89952131-49814a80-dbf2-11ea-8535-69d8df1b7913.png)

## Android Styling
![Screen Shot 2020-08-10 at 2 26 06 PM](https://user-images.githubusercontent.com/318119/89952159-5736d000-dbf2-11ea-9f2c-d97dd4fab458.png)

## Figma

https://www.figma.com/file/lu4tsEpIvnNpovX5O2BfNh/Mobile-Rewards-Settings?node-id=0%3A1

**Comment by deeppandya** [comment]
hey @jamesmudgett can we have separate screen for rewards settings? because having a settings in the same popup panel would be weird on smaller screen and it's not quite common in android to have such screens on popup menu. CC. @SergeyZhukovsky @bsclifton

**Comment by SergeyZhukovsky** [comment]
Yeah Settings usually consume a whole window, we will need to do lots of custom controls if we do it inside a popup. With doing it like Settings menu we will have an ability to open it from inside Settings as well.

**Comment by jamesmudgett** [comment]
Yes whole window on Android. Can follow the Android styling provided above.

**Comment by bsclifton** [comment]
NOTE: take into account the tips screen shown in https://github.com/brave/brave-browser/issues/10310

**Comment by Miyayes** [comment]
Closing in favor of fresher: https://github.com/brave/brave-browser/issues/16466 New designs have been completed by Cody, and Deep is making good progress here.
