### ISSUE TITLE
[Desktop] Sync - history page should show tabs from other devices

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#10473]
Chromium has tabs from other devices show on the history page. We currently hide that through commenting it all out via a patch. This can be added in, and the chromium gate on being 'signed in' can change to having sync enabled (with a link to set it up).

![image](https://user-images.githubusercontent.com/741836/85770893-3fea6480-b6d0-11ea-8a69-dc68ac9a352f.png)

This screen should be changed to prompt to "Setup Sync with Brave Browser on other devices":

![image](https://user-images.githubusercontent.com/741836/85770996-5abcd900-b6d0-11ea-89f8-562c0e6afb64.png)

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in Windows 10 x64 - 1.12.104

**Comment by darkdh** [comment]
without this section in history page, the menu will only show most recent 4 tabs

**Comment by AlexeyBarabash** [comment]
this is the same as https://github.com/brave/brave-browser/issues/12391

**Comment by bsclifton** [comment]
Set missing milestone

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.66 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/7121
-  Open Device A->App menu->History, ensured that tabs from Device B are shown with `more...` items, also ensured that click on more... redirects to `brave://history/syncedTabs` page
![image](https://user-images.githubusercontent.com/38657976/103059155-519ebd00-45ca-11eb-9b97-3a365c8ed365.png)

- Open Device B->App menu->History, ensured that tabs from Device B are shown with `more...` items, also ensured that click on more... redirects to `brave://history/syncedTabs` page
![image](https://user-images.githubusercontent.com/38657976/103059198-6e3af500-45ca-11eb-9d3b-a3b6c02ab58c.png)

**Comment by vfl97** [comment]
Still no support for iOS?
