### ISSUE TITLE
[Desktop] Balances suddenly displaying 0.0 BAT (after May 2020 ad payout)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#10471]
## Test plan
See https://github.com/brave/brave-core/pull/5935

## Description 
Android is pushing a hotfix now with logic to solve this, captured with https://github.com/brave/brave-browser/issues/9992

This issue is to test the logic on Desktop

**Comment by LaurenWags** [comment]
Added `QA/Blocked` label as this is pending uplift.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.90 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plans from https://github.com/brave/brave-core/pull/5935
* For test plan 1, started with `1.10.97` and upgraded to 1.11.x. Confirmed balance was restored as expected.
* For test plan 2, started with `1.10.97` and upgraded to 1.11.x. Confirmed balance remained 0 as expected. Saw the expected Request/Response messages in the terminal:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v1/wallets/76c7f584-da38-4c0b-a5b5-3ba018eabf34/events/batloss/1
> Method: UrlMethod::POST
> Content: {"amount": 25.000000}
> Content Type: application/json; charset=utf-8
```

```
[ RESPONSE - Sent ]
> Url: https://grant.rewards.bravesoftware.com/v1/wallets/76c7f584-da38-4c0b-a5b5-3ba018eabf34/events/batloss/1
> Result: Success
> HTTP Code: 201
> Body: null
```
