### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by SGL2586** [brave/brave-browser#10489]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.97  Chromium: 83.0.4103.116
Operating System: Windows NT 10.0.18363

URL (if applicable) where crash occurred: All sites

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Crash is occuring between 1-3 minutes into using the browser.  
2. Disabled bookmark sync based on a thread from 2019, this crash ID should be the one after disabling.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/07bb0000-1c55-8704-0000-000000000000

**Comment by SGL2586** [comment]
397cdab7-d11c-4405-871c-472f594bcb7d
confirmed issue with sync - immediate crash if try and reenable bookmark sync.

**Comment by SGL2586** [comment]
Fresh install was also tried - forgot to mention that.

**Comment by edjroz** [comment]
I'm also experiencing this crash while trying to update on Mac OS

![image](https://user-images.githubusercontent.com/14135788/85884491-c8403680-b7b0-11ea-807e-1c924a8e10b1.png)

**Comment by SGL2586** [comment]
Current 'workaround' was to remove the device with crashes from the sync group, and then readd it.  So far, stable.  So for anyone else finding this/looking for a solution, remove it from sync, then readd.  It will almost garunteed crash once readded, but the browser will be stable after (or at least so far more stable than before).

**Comment by bsclifton** [comment]
Hi folks,

The current recommendation is to disable sync. There are some known crashes that were introduced with the upgrade to Chromium 83 ☹️ We do have a new sync v2 which is live in Nightly channel and working its way back to release channel. It should be live by ~August 4th 😄
