### ISSUE TITLE
Just updated - now browser crashes every 30 seconds

### ISSUE THREAD

**Issue by nucks** [brave/brave-browser#10491]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.97  Chromium: 83.0.4103.116
Operating System: Mac OS X 10.15.5

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes, every time that I open Brave.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open the Brave browser.
2. Wait ~30 seconds.
3. The browser will crash.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c2bc0000-1c55-8704-0000-000000000000

**Comment by bsclifton** [comment]
@nucks do you have sync enabled? You can check via brave://flags/#brave-sync

I would recommend disabling this. If you can't get there fast enough, you can launch Brave via the CLI using `--disable-sync` to force sync to be disabled

**Comment by bsclifton** [comment]
Confirmed this crash is happening because of sync. The above instructions should help you out! 😄 

Sync v2 will be coming with 1.12.x which is expected to hit stable on August 4th. If you wanted a sneak preview, you can try it out on Nightly
