### ISSUE TITLE
[Desktop] Redfin.com issues with "Cross-site trackers blocked"

### ISSUE THREAD

**Issue by norsehealer** [brave/brave-browser#10499]
## Description 

when visiting redfin.com I can't click on properties for sale (on the right) nor the "More Filters" also on the right.
disabling Cross-site trackers blocked repairs the problem.

## Steps to Reproduce

   1. visit https://www.redfin.com/zipcode/90201
   2. click on the "More filters" on the right.
   3. no actions happen.
   4. disable "Cross-site trackers blocked"
   5. function is returned and "More filters" expands.

## Actual result:

nothing happens when no action is taken.

## Expected result:
while "Cross-site trackers blocked" is up, function should work on the site.

## Reproduces how often: 

I've visited the site a few dozen times. still broken.

## Brave version (brave://version info)

Brave is up to date
Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  yes (as Cross-site trackers blocked is turned off).
- Does the issue resolve itself when disabling Brave Rewards? I'm pretty sure I have this disabled.
- Is the issue reproducible on the latest version of Chrome? I dont use chrome.

## Miscellaneous Information:

the site was working fine before. i turned off my uBlock Origin and the problem persist. so I turned off cross-site tracker and the issue was fixed. thus there's an alleged issue with one of the trackers.

**Comment by ryanbr** [comment]
Can you check Brave Beta is okay? @norsehealer

**Comment by irfaneru** [comment]
Sorry

What is this?
It is useless to me and how my issue is resolved
Not understanding what you send me

**Comment by ryanbr** [comment]
From a clean profile of Brave release `Version 1.11.101`. I'm unable to reproduce this issue. Safe to close @norsehealer  ?

**Comment by rebron** [comment]
@norsehealer I'm going to close this one out. Please reopen if this is still an issue for you. I tried this in 1.12.112 which was released yesterday and it looks like it's working properly.
