### ISSUE TITLE
Unable to view twitch clips on reddit [Desktop]

### ISSUE THREAD

**Issue by Guyabay** [brave/brave-browser#10494]
## Description 
Whenever I go try to play a twitch clip from reddit it doesn't play at all. I've tried this with shield off and on, in a private tab, and they do not play at all. When I do it in private tab it doesn't load and looks like [this](https://i.imgur.com/UqIvgeC.png). I put a screenshot of what it looks like when not using a private tab in the Actual Result section of this post. 

## Steps to Reproduce

   1. Go to any subbreddit that has twitch clips posted
   2. Click the button to open the clip on the reddit page
   3. Says "Whoops! This embed is misconfigured. (Developers: Please check your browser console for more information)"

## Actual result:
[Screenshot](https://i.imgur.com/ORcwB3E.png)

## Expected result:
[Screenshot](https://i.imgur.com/5jmYAwg.png)

## Reproduces how often: 
Anytime I click on a twitch clip on reddit

## Brave version (brave://version info)
1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:
I don't use any other version so I can't speak on it. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes, issue occurs when having Brave Shield disabled. 
- Does the issue resolve itself when disabling Brave Rewards? Issue does not reslove when Brave Rewards are disabled. 
- Is the issue reproducible on the latest version of Chrome? Issue does not occur in latest version of Google Chrome.

**Comment by ryanbr** [comment]
Was reported here: https://old.reddit.com/r/brave_browser/comments/hg6ko0/unable_to_view_twitch_clips_on_reddit/

As a temp option, `allowing All cookies` in Shields will help

**Comment by ryanbr** [comment]
Just confirmed that it occurs on any site embedded twitch clips, saw same issue in Discord. Blocking the twitch cookie breaks embedded twitch clips

**Comment by diracdeltas** [comment]
cc @pes10k since we would like to avoid adding a 3p cookie exception for sites that are unrelated (like discord and twitch)

**Comment by pes10k** [comment]
@ryanbr for these kinds of issues going forward, could we
1. narrow the exception to only be from the host to the embed
2. narrow the exception rule to only target embed iframes
3. note these cases here https://github.com/brave/brave-browser/issues/8514 so that we can remove them ASAP

Let met know if you'd like a hand with any of the above too @ryanbr .  Happy to team up on it if its helpful

Thanks for pining me @diracdeltas.  What do you think of the above approach in general for these things?

**Comment by ryanbr** [comment]
Okay, made more specific @pes10k `https://clips.twitch.tv/embed?clip=` Does that look better?

**Comment by ryanbr** [comment]
edit. Make reddit and discord more specific.

`constexpr char kReddit[] = "https://[www|old]*.reddit.com/*";`
`constexpr char kDiscord[] = "https://[*.]discord.com/channels/*";`

`constexpr char kTwitch[] = "https://clips.twitch.tv/embed?*";`

**Comment by pes10k** [comment]
Thanks @ryanbr, this looks much better. Could you share a link or two that demonstrates each problem? For one i'd like to see if there is anything further we can do to reduce the scope of the exception, and second, they'll be needed for the QA team.  Thanks again for this change!

**Comment by ryanbr** [comment]
Allow all cookies need for the sites to work correctly, when embedding twitch clips. 

`www.reddit.com:`
https://www.reddit.com/r/LivestreamFail/comments/hg2kv4/moxxy_uses_aimbot/
https://www.reddit.com/r/LivestreamFail/

`old.reddit.com:` (just a mirror of reddit.com)
https://old.reddit.com/r/LivestreamFail/comments/hg2kv4/moxxy_uses_aimbot/
https://old.reddit.com/r/LivestreamFail/

Discord was only testable when logging into a discord, posting a twitch clip into a public room. Which also experienced the same issue as reddit.
(I tested this when the reddit issue was raised, and experienced the same issue).

**Comment by ryanbr** [comment]
The scope of  `https://[www|old]*.reddit.com/*`  will cover the home page and subreddits /r/.

The scope of  `https://[*.]discord.com/channels/*"` will cover each of the discord channels and private messages, after `/channels/*"` a randomised character set is used (example: https://discord.com/channels/375436620578684930/381193840159358976)
