### ISSUE TITLE
Freethoughtproject.com - ads getting beyond shields

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1049]
Carried over from https://github.com/brave/browser-laptop/issues/7245

## Description
Ads are shown even with shields up
@lukemulks has done some debugging (see original issue in browser-laptop)

## Steps to reproduce
1. Go to Freethoughtproject.com
2. See ads
3. ???

**Comment by ryanbr** [comment]
Checked the new (updated) domain `https://thefreethoughtproject.com/`  site is looking good. Closing ticket @bsclifton 

Re-open if there is any outstanding faults.
