### ISSUE TITLE
Brave Browser crashing on launch due to a bad Database file

### ISSUE THREAD

**Issue by xuvvy** [brave/brave-browser#10501]
## Description 
After using Brave without any issues for months, the same issue I had before started happening again at random: Brave would immediately close upon being launched and this would happen about twenty times before it would finally open successfully. By navigating to Brave's files and procedurally deleting files and folders I have narrowed down the issue to be due to this file: `C:\Users\%USERNAME%\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Service Worker\Database\CURRENT`, the file named "CURRENT" upon being deleted resolves this issue completely. The file "CURRENT" only contains one line:

> MANIFEST-000001

Which leads me to believe that the MANIFEST-000001 file also found in the folder might be faulty, however deleting it does not fix the issue, only deleting of the file named 'CURRENT' fixes the issue.

## Steps to Reproduce
   1. Attempt to launch Brave

## Actual result:
Brave appears to open and then immediately closes itself. Brave only successfully opens in one out of twenty or so tries.

## Expected result:
Brave should open as normal.

## Reproduces how often: 
When issue is present it happens in every attempt to launch Brave but one, on average. However, the method to get Brave to that state in the first place is unknown to me. All I know, as stated above, is which file is at fault and what it contains.

## Brave version (brave://version info)
Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

## Version/Channel Information:
This issue is happening in the current stable channel.

## Other Additional Information:
The only way to resolve the issue is to remove the "CURRENT" file from the Database folder found in: `C:\Users\%USERNAME%\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Service Worker\Database\`
The 'Database' folder in question looks like this:
![explorer_FfwXB8l7H6](https://user-images.githubusercontent.com/21984783/85960762-47e32680-b9a6-11ea-9b2d-ee9a620884cc.png)

**Comment by rebron** [comment]
@xuvvy Can you go to brave://crashes/ and send the crash reports and post the crash report id in this issue. Also, we just released 1.12.112 yesterday. Can you update to that and let us know if you're experiencing a crash.

**Comment by rebron** [comment]
cc: @iefremov This one might still be effecting users.

**Comment by iefremov** [comment]
Unfortunately, It is not really actionable without any additional info
