### ISSUE TITLE
[Desktop] settings page becomes unusable after typing any keyword and deleting that keyword

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#10506]
## Description 

Settings page becomes unusable after typing any keyword and deleting that keyword

## Steps to Reproduce

   1. Load settings page
   2. Enter keyword search mode by Command + F (or Ctrl + F)
   3. Typing any string like `testable` and delete it (by backspace or esc)

## Actual result:
Wired url(`brave://settings/syncSetup`) is set in omnibox

![image](https://user-images.githubusercontent.com/6786187/85985966-743e8780-ba26-11ea-8ec4-6fe6dac28267.png)

## Expected result:
Go to Normal settings page
![image](https://user-images.githubusercontent.com/6786187/85986029-8e786580-ba26-11ea-9865-9c086973d5e5.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.12.56 Chromium: 83.0.4103.116 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? NO
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by petemill** [comment]
I can't reproduce this. When I clear the search query, I end up back in the normal page.

**Comment by simonhong** [comment]
@petemill Did you try this with nightly?

**Comment by bsclifton** [comment]
I've ran into this for sure- thanks for logging an issue (and making PR!)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description

------
