### ISSUE TITLE
Dark/Bold Input default border

### ISSUE THREAD

**Issue by vijayhardaha** [brave/brave-browser#10509]
![image](https://user-images.githubusercontent.com/25227317/86030159-bd580100-ba51-11ea-8be3-eeb35f975000.png)

Inputs default border is too dark/bold. I think since 2nd last update I'm seeing this issue and It happens with the Extension window as well not just the browser window.

When I inspected the default user agent properly, I found that the default border with is 2px. Is this something from Brave or Chromium ? or Am I missing any setting on this issue?

**Comment by pitsi** [comment]
If it is related to this chromium 83 "feature", change c`hrome://flags/#form-controls-refresh` to false and you are done.
https://support.google.com/chrome/thread/48974735

**Comment by vijayhardaha** [comment]
Looks like it solves the problem. Thanks.
