### ISSUE TITLE
[Desktop] Brave fails to connect to KDE wallet, forgets login tokens

### ISSUE THREAD

**Issue by Zvezdin** [brave/brave-browser#10505]
## Description 

I am running KDE. By default Brave tries to use KDE wallet, I presume to store access tokens. When I start brave (with some open tabs from a previous session) KDE usually asks me to unlock my KDE wallet, brave does not load any webpages in the meantime, and when I do that brave manages to load all open tabs and I can browse as usual. However every few restarts of Brave it still asks me to unlock KDE wallet, but does not wait before loading my open tabs. Then even after I unlock KDE wallet, I am logged out of all websites. This already happens every few days which is why it is massively inconvenient. 

I have observed this on two independent machines - a desktop and a Laptop, both running KDE. 

I have installed brave from the AUR (https://aur.archlinux.org/packages/brave-bin). A possible explanation that I will try to confirm is if this happens after a package update. 

## Steps to Reproduce

   1. Open Brave on KDE
   2. Let KDE ask you to unlock KDE wallet, and do so
   3. See if brave keeps your login sessions
   4. If it does, lock KDE wallet, and try from step 1. 

## Actual result:

Brave sometimes forgets all login sessions

## Expected result:

Don't

## Reproduces how often: 

Randomly. Haven't isolated the external factors yet, but I don't have other programs open apart from Thunderbird, VSCode. 

## Brave version (brave://version info)

1.10.97 Chromium: 83.0.4103.116 (Official Build) unknown (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?

Yes. Not tested others. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Not tried but I suspect that's independent.
- Does the issue resolve itself when disabling Brave Rewards?
Already have that by default.
- Is the issue reproducible on the latest version of Chrome? 
I switched from Chromium a month ago. I've never had this issue with Chromium.

**Comment by fmarier** [comment]
It sounds like you're running into https://bugs.chromium.org/p/chromium/issues/detail?id=1065725, https://bugs.chromium.org/p/chromium/issues/detail?id=1028175 or https://bugs.chromium.org/p/chromium/issues/detail?id=658348.

Did you change your machine's user account password by any chance? I don't know whether the same is true of `kwallet`, but in my experience with `gnome-keyring`, there is a way to have the keyring be automatically unlocked and so entering the password is not necessary (and would hopefully not trigger any race conditions). What I did to unlock the `gnome-keyring` keyring was to use `seahorse` to delete the Brave keyring and then let the browser re-create it on the next startup.

**Comment by Zvezdin** [comment]
Thanks for your response! It does sound like I am running into the issues you mentioned. Weirdly and oddly enough, the problems have stopped after a few brave updates so I presume it was a chromium issue afterall that ended up getting resolved. Will reopen in case it appears again and I confirm that it's not chromium.
