### ISSUE TITLE
[Desktop] Modify Look & feel section in Shields 

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#10502]
This issue was the part of https://github.com/brave/brave-browser/issues/8838 but moved to this issue
because this Look & feel section customization is not directly related with moving brave://adblock page and easily fixed.

- Look & feel section is moved to the top to include choosing Shields default view
- Show the number of blocked items on the Shields icon is moved above choosing Shields default view

![shields](https://user-images.githubusercontent.com/2388823/83309276-b1acbc80-a1bd-11ea-8a03-5253628c11a2.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the description mentioned in the issue
- Verified that Look & Feel  `Show the number of blocked items on the Shields icon` toggle is moved up in the Shield section
- Verified that toggle  `Show the number of blocked items on the Shields icon` works as expected

1.11.x | 1.12.x
-- | --
![image](https://user-images.githubusercontent.com/38657976/88209070-c8c4d380-cc6f-11ea-9856-04a3b2e8e1e5.png) | ![image](https://user-images.githubusercontent.com/38657976/88209153-e7c36580-cc6f-11ea-87a5-ff8371278f2c.png)
