### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Pirant0409** [brave/brave-browser#10518]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.97  Chromium: 83.0.4103.116
Operating System: Windows NT 10.0.18362

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.Launching brave browser
2.White loading page appears for half a second
3.Brave crashes

Have to reproduce these steps a couple of times to manage to correctly launch brave
If i close the browser and what to relaunch it, the same issues appears.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ccd10000-1c55-8704-0000-000000000000

**Comment by bsclifton** [comment]
Not a lot of info here:
```
[ 0 ] base::Value::Clone
[ 1 ] content_settings::`anonymous namespace'::CloneRule
```

**Comment by Pirant0409** [comment]
Unfortunatly, this is the only info i can get from "brave://crashes" when checking the "Show developer details" box.
Is there an other way to get more info ?

Just for you to know, brave seems to work fine since last week now, but as an I.T student, it stills bothers me not to know what the problem was.

Have a nice day.

**Comment by iefremov** [comment]
@Pirant0409 @bsclifton this should be covered by https://github.com/brave/brave-browser/issues/10297
