### ISSUE TITLE
[Desktop] Rewards timers aren't working correctly

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10510]
## Description 

The Rewards timers aren't working correctly in 1.11.x. This is particularly evident when testing with `--rewards=reconcile-interval=x` (x is some number of minutes), although that is not required.

This does not occur in 1.10.x.

## Steps to Reproduce

   1. Clean profile in 1.11.x, launch with something like `/Applications/Brave\ Browser\ Dev.app/Contents/MacOS/Brave\ Browser\ Dev --args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6 --rewards=staging=true,reconcile-interval=3 --brave-ads-staging`
   2. Watch logs.
   3. Before enabling rewards you will see two entries something like `Timer will start in 51` (could be 4, 26, etc instead of 51)
   4. If you get something short like `Timer will start in 4` try again until you get something a bit longer like 40+
   5. Quickly enable Rewards, claim grant, set up recurring tip for a site.
   6. Wait.

## Actual result:

Recurring tip is contributed before the 3 minute `reconcile-interval` set.

## Expected result:
If timers were working correctly, in 3 minutes (or just over 3 min) you would see the recurring tip contributed.

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.11.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc

**Comment by LaurenWags** [comment]
Added `QA/Blocked` label as this is pending uplift.

**Comment by kjozwiak** [comment]
Nice find @LaurenWags 👍

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, fix should be available in https://github.com/brave/brave-browser/releases/tag/v1.11.84 and above

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.84 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description
* After launching with a fresh profile, I saw the below in the logs (this is the first `Timer` message):
```
[16192:775:0701/132741.365675:VERBOSE1:contribution.cc(264)] Timer will start in 180
``` 
Note - this is different than when tested on Nightly (1.12.x). On 1.12.x timers start after Rewards are enabled. On 1.11.x timers start when profile is launched, before Rewards are enabled. Confirmed w/ @NejcZdovc this is expected.

* Enabled Rewards, claimed UGP grant. Set up recurring tip. Confirmed recurring tip was contributed when expected (after 180s / 3min).

```
[16244:775:0701/133916.291948:VERBOSE1:contribution.cc(264)] Timer will start in 180
[16244:775:0701/133916.292586:VERBOSE1:contribution.cc(167)] Staring monthly contribution
[16244:775:0701/133916.294627:VERBOSE1:contribution.cc(264)] Timer will start in 16
[16244:775:0701/133916.295260:VERBOSE1:contribution_ac.cc(32)] Starting auto contribution
[16244:775:0701/133916.308135:VERBOSE1:contribution.cc(264)] Timer will start in 3
[16244:775:0701/133919.313515:VERBOSE1:uphold.cc(140)] Wallet data is empty
[16244:775:0701/133919.313595:VERBOSE1:contribution.cc(365)] Creating contribution(blinded) for 10 type RewardsType::RECURRING_TIP
```

-----
