### ISSUE TITLE
UNUSABLE! Crash Report

### ISSUE THREAD

**Issue by iSashaCH** [brave/brave-browser#10515]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.93  Chromium: 83.0.4103.106
Operating System: Mac OS X 10.15.5

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/5ad00000-1c55-8704-0000-000000000000

**Comment by iSashaCH** [comment]
can confirm crashes were related to #brave-sync flag being enabled, after disabling the flag crashes went away

**Comment by bsclifton** [comment]
@iSashaCH thanks for the update 😄 We'll have sync v2 live in 1.12.x (already on Nightly). It'll be working its way towards release and landing ~August 4th
