### ISSUE TITLE
Disable SharedArrayBuffer

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1051]
Details here: https://github.com/brave/browser-laptop/issues/12570

STR:

1. Go to https://xlab.tencent.com/special/spectre/spectre_check.html
2. Click the button to check your browser. It should report as not vulnerable.

**Comment by LaurenWags** [comment]
Verification Pass with
Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X

**Comment by GeetaSarvadnya** [comment]
Verification Pass on:

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
