### ISSUE TITLE
[Desktop] Youtube is showing ads after performing search action.

### ISSUE THREAD

**Issue by kamilwrobel** [brave/brave-browser#10514]
## Description 
Youtube is showing ads after performing search action.

## Steps to Reproduce

   1. Go youtube.com
   2. Type something in search bar and tap loupe button
   3. Ads will be displayed on the top of search results

## Actual result:
![image](https://user-images.githubusercontent.com/14835246/86043422-05bef100-ba49-11ea-81b6-a849c9e1b97c.png)

## Expected result:
Search results without ads.

## Reproduces how often: 
It happens frequently after search action when I type 2-3 keywords e.g "dell inspiron g3"

## Brave version (brave://version info)
Brave	1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Revision	8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS	Windows 10 OS Version 1909 (Build 18363.900)
JavaScript	V8 8.3.110.13
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,TabHoverCards,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --disable-features=AutofillServerCommunication,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,TabHoverCards,SmsReceiver,VideoPlaybackQuality,HardwareMediaKeyHandling --flag-switches-end --enable-audio-service-sandbox --disable-sync
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\48781\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-59e286d0

**Comment by bsclifton** [comment]
Can't reproduce in Brave on US version of YouTube- but easily reproducible in Chrome searching YouTube for `ergohuman plus elite`

I believe this will be fixed with the work that @jumde and @pes10k are doing with https://github.com/brave/brave-core-crx-packager/pull/138

**Comment by ryanbr** [comment]
@kamilwrobel  Hey, can you re-test in Brave-Beta, and enable `Trackers and ads` set to `Aggressive` in shields.

**Comment by kamilwrobel** [comment]
@ryanbr Sorry for delay in response, everything is fine now, thanks for support.
