### ISSUE TITLE
[Desktop] Translation in spanish for "open in private window" in bookmarks section

### ISSUE THREAD

**Issue by Kvothe838** [brave/brave-browser#10513]
Description
When right clicking on bookmarks section, it shows "Abrir en private window" instead of "Abir en una ventana de incógnito" for the translation of "Open in private window" to spanish. 

Steps to Reproduce
Right click on bookmarks section having Brave in spanish
See "Abrir en private window" as an option.

Actual result:
"Abrir en private window" as an option.
I can't upload screenshot because Ubuntu doesn't let me.

Expected result:
"Abrir en una ventana de incógnito" as an option.

Reproduces how often:
Easily reproduced

Brave version (brave://version info)
1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bits)

Is the issue reproducible on the latest version of Chrome?
No

**Comment by jheymejia** [comment]
I have the same Versión 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
But I cannot reproduce your issue, I have the options correctly translated, with only one exception: When opening a private window, the label is "Incógnico" (with C) instead of "Incógnito"

I use Windows 10 x64

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.24.16 Chromium: 89.0.4389.105 (Official Build) nightly (64-bit)
-- | --
Revision | 14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/112366077-a987b580-8cd8-11eb-99b5-6794d9f9b2c2.png)
![image](https://user-images.githubusercontent.com/34715963/112366036-9ecd2080-8cd8-11eb-8ead-4c482a06219a.png)
