### ISSUE TITLE
[Android] Brave Ads are not enabled on a fresh install when enabling rewards

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#10526]
## Description 
[Android] Brave Ads are not enabled on a fresh install when enabling rewards

## Steps to reproduce 

   1. Launch browser (fresh install)
   2. Join Rewards via onboarding

## Actual result 
Ads is disabled

## Expected result
Ads should b eenabled

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version?  No
   - Beta build? Latest master is affected

## Device details
   - Install type (ARM, x86): Arm
   - Device (Phone, Tablet, Phablet): Phone
   - Android version:
   
## Brave version
brave-core commit-hash `db291b77f2bc1299c0764c54125338f96e2b54be`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by samartnik** [comment]
Test plan:
1. Click rewards icon.
2. Join rewards from onboarding dialog.
3. When redirected back to rewards panel, close panel before wallet is created.
4. Give it a minute to finish wallet creation and go to `brave://rewards` page.
5. Make sure ads are turned on.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.12.109 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/10526#issuecomment-654439598
------------------
Verification passed on OnePlus 6T with Android 10 running 1.12.109 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/10526#issuecomment-654439598
