### ISSUE TITLE
Increase Brave Ads maximum page probability history entries

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#10520]
[Desktop] Increase maximum page probability history entries

**Comment by tmancey** [comment]
Blocked until we have further metrics

**Comment by moritzhaller** [comment]
closed by https://github.com/brave/brave-browser/issues/8398

**Comment by LaurenWags** [comment]
Testing notes from @tmancey can be found here: https://github.com/brave/brave-core/pull/6940#issuecomment-740184773

Thanks for the help with this @tmancey 👍
