### ISSUE TITLE
[Android] Do not clear url bar text on focus

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#10524]
## Description 
As per discussion https://bravesoftware.slack.com/archives/C20HMJ62H/p1592687065037300
Do not clear url bar text on focus.

## Steps to reproduce 

   1. Go to any website
   2. Click on url bar
   3. Url itself is disappeared
![device-2020-06-30-133103](https://user-images.githubusercontent.com/30602739/86158271-8d067600-bad6-11ea-837a-3885819187a2.png)

## Actual result 
Url itself is disappeared

## Expected result
Url is shown and highlighted

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.10.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan:
1. To to any website
2. Click on url bar
3. Url should be shown and highlighted

**Comment by samartnik** [comment]
After change
![device-2020-06-30-133048](https://user-images.githubusercontent.com/30602739/86158307-9abbfb80-bad6-11ea-8668-208069c41c9e.png)

**Comment by samartnik** [comment]
@jumde could you confirm if this behavior is ok or not https://github.com/brave/brave-core/pull/5978#issuecomment-654271056

**Comment by jumde** [comment]
@samartnik - comment here: https://github.com/brave/brave-core/pull/5978#issuecomment-655719364

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.106 x64 beta build
- Verified URL bar is not cleared when going into edit mode
- Verified URL bar is highlighted when selected in edit mode
- Encountered #10723
--------------------------
Verification passed on Samsung Tab A with Android 10 running 1.12.106 x64 beta build
- Verified URL bar is not cleared when going into edit mode
- Verified URL bar is highlighted when selected in edit mode
- Encountered #10723
