### ISSUE TITLE
[Desktop] Does not allow opening https pages with self-signed certificate

### ISSUE THREAD

**Issue by sagaardu** [brave/brave-browser#10521]
## Description 
Hello, since the last update it is not possible for me to open self-signed concerted pages, especially when I access through the IP instead of the DNS.

Before, I had a warning about whether I wanted to take the risks, now that warning appears but when I accept, it does nothing.

## Steps to Reproduce

   1.  Go to https://10.10.10.1
   2. La conexión no es privada
Es posible que los atacantes estén intentando robar tu información de 10.10.10.1 (por ejemplo, contraseñas, mensajes, o tarjetas de crédito). Más información
NET::ERR_CERT_AUTHORITY_INVALID
   3. Este servidor no ha podido probar que su dominio es 10.10.10.1; el sistema operativo de tu ordenador no confía en su certificado de seguridad. Este problema puede deberse a una configuración incorrecta o a que un atacante haya interceptado la conexión.

Proceder a 10.10.10.1 (inseguro)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Versión 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bits)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  i dont know
- Can you reproduce this issue with the dev channel? i dont know
- Can you reproduce this issue with the nightly channel? i dont know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?  No, chrome work perfect

**Comment by m4gn3to** [comment]
Same here!!!

**Comment by sagaardu** [comment]
Hello,

No one else has this problem?

Do you know how I can solve it?

Regards

**Comment by m4gn3to** [comment]
Not. I'm not been able to see any of my servers... Now I'm using chrome.

**Comment by sagaardu** [comment]
OK, so then I have no choice but to launch a GPO to remove it from the entire organization, we will try other options.

Regards

**Comment by culebrasolida** [comment]
facing the same issue when trying to access my router's configuration address.
Brave version 1.10.97 Chromium: 83.0.4103.116 (Official Build)

**Comment by zatkinson08** [comment]
Same issue for me.

macOS Catalina - v10.15.6
Brave: Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/7238952/93509401-44947280-f8e5-11ea-9d95-800ce7d470d3.png)

**Comment by fmarier** [comment]
@zatkinson08 The error message you are running into suggests a different problem (something about "scrambled credentials").

This is what a self-signed error message looks like: https://self-signed.badssl.com/

**Comment by fmarier** [comment]
I'm going to mark this as a duplicate of https://github.com/brave/brave-browser/issues/10562 because the original report was for the Spanish version. If there are any more problems with self-signed certificates, please open a new issue.
