### ISSUE TITLE
Reporting a scammer advertising on Brave Ads

### ISSUE THREAD

**Issue by JadianRadiator** [brave/brave-browser#10529]
## Description 

[Salt Lending](https://saltlending.com/) is a scam.
You have to put up $8000 in crypto in collateral to get a $5000 loan in crypto.
People wouldn't need a legitimate $5000 loan to begin with if they had the $8000 needed for collateral.

**Comment by jsecretan** [comment]
@lukemulks can review, but just because somebody does not like the terms of business for an advertiser does not mean it is a scam.

**Comment by lukemulks** [comment]
Does not qualify as a scam. CeFi collateral requirements are part of the financial product offering. People put in collateral, earn a yield and can take a loan for additional crypto trading. 

Appreciate the report.
