### ISSUE TITLE
[Desktop] Resource.json files are not being parsed

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10528]
## Description

Parse `resource.json` for regional ad block lists.

## Repro Steps

1. Navigate to brave://adblock
2. Select a new ad-block list to install

## Output

```
Failed to parse JSON adblock resources: EOF while parsing a value at line 1 column 0
```

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.99 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Reproduced the issue using 1.11.97, confirmed error in terminal when selecting adblock lists on brave://adblock:
```
Failed to parse JSON adblock resources: EOF while parsing a value at line 1 column 0
```

* Verified test plan from https://github.com/brave/brave-core/pull/5981 for each list on brave://adblock
* Confirmed no error in terminal was observed for any list

----------
