### ISSUE TITLE
[Desktop][Android] Creating a sync chain doesn't add devices

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10533]
## Description 

Creating a sync chain doesn't add devices

## Steps to Reproduce

   1. Create and reset Sync chain on desktop nightly a few times (I had rest it 4 times)
   2. Create a new sync chain again 5th time on desktop
   3. Add Android nightly device to the sync chain by entering the code words
   4. Both devices has sync chain enabled but doesn't list other devices and nothing gets sync'd

## Actual result:

No sync between devices even though both use the same code words

## Expected result:
Should have sync chain created and work on all devices in the chain

## Reproduces how often: 

Not really sure

## Brave version (brave://version info)

Brave | 1.12.61 Chromium: 83.0.4103.116 (Official Build) nightly (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{# 716}
OS | Linux
Android Device | OnePlus 6T 
Android Ver |10
Android Build | 1.12.61 nightly updated via Playstore

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@AlexeyBarabash  pointed out to check the user names in `brave://sync-internals` and I did see different usernames on both desktop and Android.

**Comment by AlexeyBarabash** [comment]
tried twice with todays master Android and desktop builds  - cannot reproduce.

@srirambv , could you also try it again? Maybe this was fixed be recent PRs for desktop and android.

**Comment by AlexeyBarabash** [comment]
After lots of  attempts I got sync chain created but no devices:
![image](https://user-images.githubusercontent.com/24739341/99825621-f0657300-2b5f-11eb-84c6-3cd7c60fd7aa.png)

In that time status is `initializing`
![image](https://user-images.githubusercontent.com/24739341/99825677-02dfac80-2b60-11eb-82de-22621e8f9e7f.png)

And the code words are available to copy.

So expected, Android will find zero devices in chain at this point.

After waiting for some time device appeared - not sure what the exact amount, probably ~ 1 minute

![image](https://user-images.githubusercontent.com/24739341/99825951-610c8f80-2b60-11eb-8644-0fe7c19898e8.png)

![image](https://user-images.githubusercontent.com/24739341/99826100-91ecc480-2b60-11eb-8512-644091bb6d27.png)

And I succeeded to connect through the codewords with Android phone.

@srirambv could you look in this issue again?

**Comment by AlexeyBarabash** [comment]
Confirmed with @srirambv 

>can be closed. Can't repro any more
