### ISSUE TITLE
[Desktop] Enable Speedreader on by default for Beta channel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#10537]
## Description 

Turn Speedreader on by default and tied specifically to Beta channel.

## Expected result:
Speedreader is enabled by default on Beta channel. 
Beta users can turn off speedreader via #brave-speedreader

## Reproduces how often: 

n/a

## Brave version (brave://version info)

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a 
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? Speedreader enabled only for Nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
Marking as QA/Blocked. We need to make sure that speedreader is not enabled by default in a release candidate/for release channel.

**Comment by LaurenWags** [comment]
Verified passed using

```
Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

```
Brave | 1.13.60 Chromium: 84.0.4147.105 (Official Build) dev (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6006

`1.12.x`:
<img width="1195" alt="1 12 x" src="https://user-images.githubusercontent.com/28145373/89341623-918ef300-d66f-11ea-9e2f-5bc19995b63b.png">

`1.13.x`:
<img width="1196" alt="1 13 x" src="https://user-images.githubusercontent.com/28145373/89341632-93f14d00-d66f-11ea-93c8-ab7c029a5055.png">
