### ISSUE TITLE
[Desktop] Make external wallet synchronous 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10536]
Right now `GetExternalWallets` has a callback, which is not needed as getting this data is all sync. We should change it to it actually returns map. This way we can remove a lot of complexity in the code

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5994
* Claimed staging ad grant, connected KYC'd wallet, confirmed ad grant moves to KYC'd wallet:
```
[ RESPONSE - OnTransferAnonToExternalWallet ]
> Url: https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/redacted/claim
> Result: Success
> HTTP Code: 200
```

<img width="1195" alt="Screen Shot 2020-08-05 at 1 28 22 PM" src="https://user-images.githubusercontent.com/28145373/89444333-8dbaa980-d71f-11ea-8e22-aeb45e4107e1.png">

* Confirmed able to tip verified creators (on staging):
<img width="665" alt="Screen Shot 2020-08-05 at 1 31 28 PM" src="https://user-images.githubusercontent.com/28145373/89445188-d161e300-d720-11ea-930a-985a59dae8c7.png">
<img width="420" alt="Screen Shot 2020-08-05 at 1 37 16 PM" src="https://user-images.githubusercontent.com/28145373/89445199-d3c43d00-d720-11ea-97fa-89087c355c07.png">
<img width="1175" alt="Screen Shot 2020-08-05 at 1 37 09 PM" src="https://user-images.githubusercontent.com/28145373/89445209-d6269700-d720-11ea-9c1a-aa2557cb6fcf.png">

----------
