### ISSUE TITLE
[Desktop] Request to https://www.gstatic.com/chrome/profile_avatars/ when creating a new profile

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#10531]
## Test Plan

Specified here: https://github.com/brave/brave-core/pull/6226

## Description 

When creating a new profile, a network request to Google is made.

Since we [already proxy](https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)#services-we-proxy-through-brave-servers) `https://www.gstatic.com/images/branding/product/*x/translate_24dp.png`, we probably just need to expand what that proxy covers.

## Steps to Reproduce

Use a proxy like mitmproxy to watch network requests in Brave.

   1. Click the hamburger menu.
   2. Click "Create a New Profile".

## Actual result:

A request to https://www.gstatic.com/chrome/profile_avatars/avatar_oval_royal.png (404) is made.

## Expected result:

That request should be either blocked or proxied.

## Reproduces how often: 

Always

## Brave version (brave://version info)
```
Brave	1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Revision	8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS	Linux
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 

Yes.

- Can you reproduce this issue with the beta channel? 

Haven't tried.

- Can you reproduce this issue with the nightly channel? 

Yes.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.14.68 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6226.

![image](https://user-images.githubusercontent.com/34715963/91676456-2508f600-eb40-11ea-8491-6cd963c015fd.png)

Encountered https://github.com/brave/brave-browser/issues/11444
