### ISSUE TITLE
[Desktop] Cosmetic filtering throws an error on local domains without a global suffix

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#10548]
## Description 

Cosmetic filters fail to grant exemptions due to a JS error. This only happens when the hostname does not include a global suffix.

## Steps to Reproduce

   1. Grab this test page: https://github.com/fmarier/brave-testing/blob/master/cosmetic-filtering.html
   2. Add `127.0.0.1 foobar` to `/etc/hosts`
   3. Serve the test page from a local webserver listening on `http://foobar`

## Actual result:

![Screenshot from 2020-07-02 14-51-28](https://user-images.githubusercontent.com/167821/86413035-1653af00-bc75-11ea-9f70-68ab1de44d9e.png)

## Expected result:
We should handle the error gracefully and doe the same thing as if we visit the test page on a publicly-accessible host like <https://fmarier.github.io/brave-testing/cosmetic-filtering.html>.

## Reproduces how often: 
Always

## Brave version (brave://version info)
```
Brave	1.11.83 Chromium: 83.0.4103.116 (Official Build) beta (64-bit)
Revision	8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS	Linux
```

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.94 Chromium: 84.0.4147.85 (Official Build) (64-bit)
-- | --
Revision | e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{#837}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Reproduced the error on `1.11.92` (Dev)
Both using `Standard` Tracker & ad blocking shield setting with GH page on the left, local page on the right. Error reproduces for local page, you can see they don't match:
<img width="1713" alt="1 11 92 - std" src="https://user-images.githubusercontent.com/28145373/87155436-f0d43000-c288-11ea-807d-aa163601cb9c.png">

Both using `Aggressive` Tracker & ad blocking shield setting pages match (no error on local page):
<img width="1711" alt="1 11 92 - aggressive" src="https://user-images.githubusercontent.com/28145373/87155605-385abc00-c289-11ea-88d0-3c7cc25c9284.png">


* Confirmed when using `1.11.94` with either `Standard` or `Aggressive` mode both GH and local page match
Both using `Standard` Tracker & ad blocking shield setting, pages match (except for icon, which is expected):
<img width="1717" alt="1 11 94-std" src="https://user-images.githubusercontent.com/28145373/87155868-bae37b80-c289-11ea-90fd-84e4dde599a9.png">

Both using `Aggressive` Tracker & ad blocking shield setting, pages match:
<img width="1713" alt="1 11 94-aggressive" src="https://user-images.githubusercontent.com/28145373/87155878-bdde6c00-c289-11ea-8ba9-20a49d66492f.png">
