### ISSUE TITLE
[Desktop] Brave identifies as Chromium in Pulseaudio

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#10541]
## Description 

When Brave is playing sound via pulseaudio on Linux, it shows up as "Chromium" instead of "Brave".

## Steps to Reproduce

   1. Play a video on Youtube.

## Actual result:

![Capture d’écran du 2020-07-01 18-54-58](https://user-images.githubusercontent.com/167821/86307820-91ad5600-bbcc-11ea-9ade-f221f75ec6bb.png)

## Expected result:

"Brave: Playback"

## Reproduces how often: 

Always

## Brave version (brave://version info)

```
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Linux
```

**Comment by srirambv** [comment]
+1 on Linux. It shows as Chromium in media playback in sounds settings as well

**Comment by fmarier** [comment]
Now superseded by #10919 .
