### ISSUE TITLE
Detect/block tracking 1st party beacons

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1054]
Carried over from https://github.com/brave/browser-laptop/issues/2764

## Description 
> I would like to have an option in the bravery panel to block 1x1 pixel beacons. There are sites on which beacons are used as log-in credentials, so it should be able to detect which one is actually used for logging in and which one is for tracking.

**Comment by tomlowenthal** [comment]
Related: https://twitter.com/random_walker/status/1072209450629562369
