### ISSUE TITLE
[Desktop] Github tipping regex is too permissive

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#10540]
## Description 

When visiting developer.github.com/v4, the Rewards panel confuses `v4` for a Github user and offers to tip the user.

## Steps to Reproduce

   1. Enable Rewards and Github tipping
   2. Visit developer.github.com/v4
   3. Display the Rewards panel

## Actual result:

Rewards panel thinks you're tipping github.com/v4.

![image](https://user-images.githubusercontent.com/5033691/86300634-78f36f00-bbd1-11ea-803b-81aff3c3f66c.png)

## Expected result:

Rewards panel shouldn't recognize `v4` as a Github user.

## Reproduces how often: 

Easily reproduced.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by emerick** [comment]
cc: @jonathansampson

**Comment by sgmenda** [comment]
This also seems to affect twitter, however this might be harder to fix. I can reproduce the v4 bug and the twitter bug on nightly.

![image](https://user-images.githubusercontent.com/13268492/86301570-30898080-bbd4-11ea-954f-3f2b56934268.png)

**Comment by jonathansampson** [comment]
I would assume Twitter has a relatively small set of URL patterns which can be considered. That should help us catch things like `/<lang>/tos` and more. I assume the same is true for github, although my gut says GitHub probably has more URL patterns which would need to be determined, listed, and evaluated in Brave.
