### ISSUE TITLE
[Desktop] [Android] Set an alternate private SE for users in India as DDG is blocked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10545]
## Description 

Change Private tab search engine from DDG to other for India as its currently not accessible without VPN

## Steps to Reproduce

   1. Set VPN to Indian IP
   2. Open DDG 
   3. Page doesn't load

## Actual result:

DDG fails to load as it's blocked for users in India

## Expected result:
Have an alternate for users in India as default for Private tabs

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All Channels

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? Yes 

## Miscellaneous Information:

cc: @bbondy @bsclifton @w0ts0n

**Comment by eklavya002** [comment]
the problem is with ISP, its working fine here(India).

**Comment by eklavya002** [comment]
> the problem is with ISP, its working fine here(India).

one of the ISP (Jio) has resolved the issue,but still some Isp users are facing the peoblem.

**Comment by newuser-web** [comment]
Not working on Jio

**Comment by newuser-web** [comment]
not working on Jio

**Comment by newuser-web** [comment]
Not working on Jio

**Comment by newuser-web** [comment]
@srirambv It is working now. Close this issue

**Comment by newuser-web** [comment]
@srirambv DDG is working now. Close this issue

**Comment by newuser-web** [comment]
@srirambv DDG is working now

**Comment by srirambv** [comment]
Closing as this is resolved now.
