### ISSUE TITLE
[Desktop] [Android]  Add more Purchase Intent segments for trial campaign

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#10556]
Add more Purchase Intent segments for trial campaign

**Comment by moritzhaller** [comment]
@srirambv why did we change the title do "Desktop"? This change would affect iOS/Android as well. Thanks!

**Comment by srirambv** [comment]
Updated. For iOS we will need to log an issue on iOS repo so that it gets tested. Otherwise changes wont be tested.

**Comment by moritzhaller** [comment]
> Updated. For iOS we will need to log an issue on iOS repo so that it gets tested. Otherwise changes wont be tested.

Thanks @srirambv, I will add one to the iOS repo as well

**Comment by bsclifton** [comment]
Added missing milestone

**Comment by LaurenWags** [comment]
@moritzhaller does this require different testing than https://github.com/brave/brave-browser/issues/10235 ?

**Comment by LaurenWags** [comment]
Android issue: https://github.com/brave/brave-browser/issues/10747

**Comment by moritzhaller** [comment]
> @moritzhaller does this require different testing than #10235 ?

@LaurenWags same test protocol should be fine, but both PRs are adding different urls/keywords to match against so maybe a quick spot check if those are picked up would be good.

**Comment by LaurenWags** [comment]
what's different? we were using the spreadsheet to test with for https://github.com/brave/brave-browser/issues/10235 and that doesn't indicate which were added per PR.

**Comment by moritzhaller** [comment]
@LaurenWags that should be fine then!

**Comment by LaurenWags** [comment]
Awesome 👍 Thanks for the clarification @moritzhaller!

We took the approach of checking several different items on that spreadsheet so I'm going to switch this one to `QA/No` unless there objections cc @tmancey @jsecretan @kjozwiak @rebron
