### ISSUE TITLE
[Desktop] Minor Typo in spanish translation for 404 error.

### ISSUE THREAD

**Issue by vstyler96** [brave/brave-browser#10550]
## Steps to Reproduce
Just go to a page where will exist a possible 404 error.

   1. Open brave (In spanish).
   2. Go to https://brave.com/non-existing-page
   3. The message will come by itself.

## Actual result:
![image](https://user-images.githubusercontent.com/46312870/86419959-8c1e4180-bc9a-11ea-8b41-7916cd5addb9.png)

## Expected result:
**Compruebe si hay una versión guardada**

## Reproduces how often: 
Every 404 error.

## Brave version (brave://version info)
Brave: 1.9.8
Chrome: 81.0.4044
OS: Arch Linux.

![image](https://user-images.githubusercontent.com/46312870/86420058-e6b79d80-bc9a-11ea-8886-4b2795461cc6.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Currently, yes.
- Can you reproduce this issue with the beta channel? Currently, yes.
- Can you reproduce this issue with the dev channel? Currently, yes.
- Can you reproduce this issue with the nightly channel? Currently, yes.

## Other Additional Information:
> N/A

## Miscellaneous Information:
> N/A

**Comment by bsclifton** [comment]
Thanks for reporting @vstyler96 and for closing when it was fixed 😄 I just verified this is set properly in Transifex (the backend we use to manage translations)
