### ISSUE TITLE
[Desktop] Refactor Brave Ads LoadJsonSchema to LoadResourceForId

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#10553]
[Desktop] Refactor Brave Ads LoadJsonSchema to LoadResourceForId

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.13.76 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6061.
* Confirmed catalog downloaded on both staging and prod environments.
* Confirmed catalog downloaded when joining Rewards from panel, brave://rewards, and NTP widget.
* Confirmed I saw `[15797:775:0818/082119.729585:VERBOSE1:ads_serve.cc(104)] Successfully downloaded catalog` in the logs.
* Confirmed able to trigger an ad.
* Used `--brave-ads-debug` flag to trigger short download intervals for catalog. Confirmed catalog was re-downloaded at expected interval.

--------------
