### ISSUE TITLE
[Android] Sync v2 not working after app restart on C84 base

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10569]
## Description 
Sync v2 not working on Android after app restart.

## Steps to reproduce 

1. Make installation of Nighlty 1.12.70, Chromium 84
2. Open `brave://sync-internals`
3. Optional - if you'll see FTRW collapse all apps and run Brave Browser again
4. Go settings => Sync => Start a new sync chain => Add computer => Done 
5. Wait till you'll see one device in chain
6. Close Settings
7. Ensure you see at `brave://sync-internals`  `Sync Feature enabled` is `true` and `Bookmarks Total Entries` in table is 3 (or more)
8. Kebab menu => Exit
9. Launch Brave Browser Nightly again
10. Open `brave://sync-internals` if it is closed
10.5 Wait ~1 minute

## Actual result 
11. Actual: `Sync Feature enabled` is `false`, `Bookmarks Total Entries` in table is `null`

## Expected result
11. Expected: `Sync Feature enabled` is `false`, `Bookmarks Total Entries` in table is `null`

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version? Yes, current Nightly
   - Beta build?

## Device details
   - Install type (ARM, x86): Arm
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 9
though NM   

## Brave version
1.12.70

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.109
- Verified test plan from issue description
- Verified closing and restarting the browser doesn't set Bookmarks totals to `null`
-------------
Verification passed on Samsung Tab A with Android 10 running 1.12.109
- Verified test plan from issue description
- Verified closing and restarting the browser doesn't set Bookmarks totals to `null`
