### ISSUE TITLE
[Desktop] Spanish translation breaks the "Proceed anyway" link on TLS error pages

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#10562]
## Description 
The Spanish translation for TLS error pages breaks the click handler on the button allowing users to bypass certificate errors.

This is what the button should look like:

![Capture d’écran du 2020-07-03 16-47-30](https://user-images.githubusercontent.com/167821/86501532-779b8100-bd4e-11ea-9535-90e85666c204.png)

and this is what the Spanish version looks like:
![Capture d’écran du 2020-07-03 16-46-39](https://user-images.githubusercontent.com/167821/86501538-7ff3bc00-bd4e-11ea-80af-819746f4385e.png)

This is Brave-specific since Chromium (`Versión 83.0.4103.116 (Build para desarrolladores) built on Debian bullseye/sid, running on Debian bullseye/sid (64 bits)`) works fine:
![Capture d’écran du 2020-07-03 16-45-39](https://user-images.githubusercontent.com/167821/86501521-62beed80-bd4e-11ea-9b1f-58c19138281b.png)

Originally reported on <https://community.brave.com/t/https-error-and-cant-continue/138683>.

## Steps to Reproduce

   1. Start Brave in Spanish: `LANG=es_ES.UTF-8 brave-browser`.
   2. Open <https://self-signed.badssl.com/>.
   3. Click "Advanced" button.
   4. Click "Proceder a self-signed.badssl.com" button.

## Actual result:
![Capture d’écran du 2020-07-03 16-46-48](https://user-images.githubusercontent.com/167821/86501479-f7751b80-bd4d-11ea-8848-3019bc1e0a3c.png)

Clicking the button doesn't do anything. Also, note that the hostname (`192.168.1.1` in the screenshot) is displayed twice.

## Expected result:
The error message should go away and the page

## Reproduces how often: 

Always

## Brave version (brave://version info)
```
Brave	1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Revision	8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS	Linux
```

**Comment by mkarolin** [comment]
Fixed by https://github.com/brave/brave-core/pull/5998
