### ISSUE TITLE
[Desktop] Different settings page are launched for Tor window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#10567]
## Description 

Tor window opens different settings page depends on how user opens settings page.
With app menu in Tor window, Normal profile's settings page is opened.
With shortcut(ex, `cmd + ,`), Tor profile's settings page is opened.
I think Tor window always should use normal profile's settings page instead of its own because Tor window is based on private profile. cc: @darkdh @yrliou 

## Steps to Reproduce

   1. Launch browser and open Tor window
   2. In Tor's NTP, open settings page via app menu
   3. Check normal profile's settings page is opened
   4. In Tor's NTP, open settings page via app shortcut
   5. Check different settings page is opened

## Actual result:

Different settings page are opened.

## Expected result:
Same settings page should be used.
keyboard shortcut "cmd + ," should go to normal brave://settings page

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.12.72 Chromium: 84.0.4147.68 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by darkdh** [comment]
This is fixed by https://github.com/brave/brave-core/pull/7069

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.64 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
Verified the test plan from https://github.com/brave/brave-core/pull/7069
Verified the STR from the description
