### ISSUE TITLE
[Desktop] Can't log in to new Apple credit card site

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#10568]
## Description 
VIsiting `https://card.apple.com/` unable to login  Apple credit card site

## Steps to Reproduce
Was reported by https://community.brave.com/t/cant-log-in-to-new-apple-credit-card-site/139153

   1.  Login issues when visiting `https://card.apple.com/`
   2. 
   3. 

## Actual result:

Unable to login

## Expected result:
Allow user to login.

## Reproduces how often: 

Easily, due to cookies issue. 

## Brave version (brave://version info)
`Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Allowing cookies for `card-static.cdn-apple.com` is needed.

![c42cb69f48084fa4bf79d5044e69a7b6df160fec_2_557x500](https://user-images.githubusercontent.com/1659004/86555743-58e2f780-bfa5-11ea-92a2-1bfd2ddf1d5c.png)

**Comment by rebron** [comment]
@ryanbr is this still an issue?

**Comment by ryanbr** [comment]
Resolved, can login now (just errors now because I have no card which is fine)
