### ISSUE TITLE
[Android] Implement Desktop -> Android cross promotional Modal

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#10571]
## Description 
As part of the updated onboarding, please implement "Cross Promote Brave on Desktop"

**On Day 12:** 
![image](https://user-images.githubusercontent.com/2388823/88084606-84371c00-cb39-11ea-9d6f-415880ba325f.png)

**Comment by anthonypkeane** [comment]
![brave desktop callout](https://user-images.githubusercontent.com/7606853/86837139-56d77200-c053-11ea-9235-37faac06d6e6.jpg)

**Comment by karenkliu** [comment]
This has the updates from marketing:

![image](https://user-images.githubusercontent.com/2388823/87992985-4afd9e00-ca9e-11ea-8655-d73862de443c.png)

**Comment by anthonypkeane** [comment]
Copy proposal

> Download Brave on your Desktop for a faster, more private web at brave.com

**Comment by anthonypkeane** [comment]
Hey @karenkliu 
@srirambv noted that having the brave.com text in a different colour makes it seem like brave.com is a URL which it isn't

Are you ok with @deeppandya keeping the brave.com colour the same black?

**Comment by karenkliu** [comment]
@anthonypkeane oh, I didn't realize that wasn't supposed to be a link. Sure - make it text colored

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
<details>
<summary>Verified cross-platform promotional modal is shown for a new user after 12 days of installation</summary>

English | French
-- | --
![image](https://user-images.githubusercontent.com/17010094/91934894-5c180c80-ece4-11ea-9d52-8869f734db8f.png) | ![image](https://user-images.githubusercontent.com/17010094/91934932-70f4a000-ece4-11ea-84cd-e23a9351156f.png)

</details>

-----------------------

Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
<details>
<summary>Verified cross-platform promotional modal is shown for a new user after 12 days of installation</summary>

English | German
-- | --
![image](https://user-images.githubusercontent.com/17010094/91937157-435e2580-ece9-11ea-8385-3276a103d6a0.png) | ![image](https://user-images.githubusercontent.com/17010094/91937165-478a4300-ece9-11ea-887c-9acba8db3389.png)

</details>
