### ISSUE TITLE
[Desktop] Do not apply cosmetic filtering, in default setting, to general-purpose search web search engines that we have vetted

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#10575]
We should not apply cosmetic filterings to search engine ads, for well known, reputable, general-purpose search engines, who generally have 1p or 1p-like (re yahoo.com and yimg.com) ads.

Note that this would not change in anyway network rules / blocking, which would continue to be applied universally.

Cosmetic filtering should still be applied to these sites (and all sites) when blocking is in aggressive / max mode.

Search engines covered by this list:
- duckduckgo.com
- qwant.com
- bing.com
- startpage.com
- yahoo.com
- onesearch.com
- google.com
- yandex.com

We should also apply this cosmetic-filtering-off-by-default settings to the other eTLD+1 variants of the above.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.11.94 Chromium: 84.0.4147.85 (Official Build) (64-bit)
Revision	e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{#837}
OS	macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6013 for the search engines listed in description.

* Confirmed ads do display in `Standard` mode on the SE page (except where noted)
* Confirmed ads do not display in `Aggressive` mode on the SE page (except where noted)

<details>
<summary>DDG</summary>

`Standard`
<img width="1195" alt="DDG - std" src="https://user-images.githubusercontent.com/28145373/87182422-1e819f00-c2b2-11ea-8012-ef41a80bca1e.png">

`Aggressive`
<img width="1195" alt="DDG - aggressive" src="https://user-images.githubusercontent.com/28145373/87182432-217c8f80-c2b2-11ea-89ad-81af0d579692.png">

</details>

<details>
<summary>Qwant</summary>

`Standard`
<img width="1193" alt="Qwant - std" src="https://user-images.githubusercontent.com/28145373/87182475-33f6c900-c2b2-11ea-988a-dc65624e3034.png">

`Aggressive`
<img width="1195" alt="Qwant - aggressive" src="https://user-images.githubusercontent.com/28145373/87182482-36f1b980-c2b2-11ea-9a1b-4114f289a593.png">

</details>

<details>
<summary>Bing</summary>

`Standard`
<img width="1191" alt="Bing - std" src="https://user-images.githubusercontent.com/28145373/87182493-3fe28b00-c2b2-11ea-9a8e-dc5d28f449aa.png">

`Aggressive`
<img width="1185" alt="Bing - aggressive" src="https://user-images.githubusercontent.com/28145373/87182498-42dd7b80-c2b2-11ea-88d7-bda3418f08d4.png">

</details>

<details>
<summary>Startpage</summary>

*note - confirmed thru discussions w/ @pes10k and @antonok-edm that not seeing the Ads on Startpage w/ Standard is expected. You will see them if set to Allow All. (logged/closed #10693)
`Standard`
<img width="1192" alt="Startpage - std" src="https://user-images.githubusercontent.com/28145373/87182566-6d2f3900-c2b2-11ea-9e91-a5436c596f1d.png">

`Aggressive`
<img width="1192" alt="Startpage - aggressive" src="https://user-images.githubusercontent.com/28145373/87182573-702a2980-c2b2-11ea-9cc9-9e4751c80aec.png">

</details>

<details>
<summary>Yahoo</summary>

`Standard`
<img width="1193" alt="Yahoo - std" src="https://user-images.githubusercontent.com/28145373/87182648-87691700-c2b2-11ea-80c4-8d781bfda383.png">

`Aggressive`
<img width="1195" alt="Yahoo - aggressive" src="https://user-images.githubusercontent.com/28145373/87182657-8afc9e00-c2b2-11ea-9ebd-68ddf6b712da.png">

</details>

<details>
<summary>Onesearch</summary>

`Standard`
<img width="1179" alt="onesearch - std" src="https://user-images.githubusercontent.com/28145373/87182673-9354d900-c2b2-11ea-9667-879e440e6bf2.png">

`Aggressive`
<img width="1193" alt="onesearch - aggressive" src="https://user-images.githubusercontent.com/28145373/87182679-96e86000-c2b2-11ea-9dd9-0d552bc02671.png">

</details>

<details>
<summary>Google</summary>

`Standard`
<img width="1190" alt="Google - std" src="https://user-images.githubusercontent.com/28145373/87182692-9ea80480-c2b2-11ea-9acd-a58ef15fbc26.png">

`Aggressive`
<img width="1191" alt="Google - aggressive" src="https://user-images.githubusercontent.com/28145373/87182696-a10a5e80-c2b2-11ea-8bb8-72ad20a793ce.png">

</details>

<details>
<summary>Yandex</summary>

*note - internal discussions about the Ads displaying on Yandex with Aggressive selected can be found here: https://bravesoftware.slack.com/archives/C7VLGSR55/p1594228166125900?thread_ts=1594214993.102400&cid=C7VLGSR55
`Standard`
<img width="1190" alt="Yandex - std" src="https://user-images.githubusercontent.com/28145373/87182785-ceefa300-c2b2-11ea-8886-b32165698b6c.png">

`Aggressive`
<img width="1190" alt="Yandex - aggressive" src="https://user-images.githubusercontent.com/28145373/87182796-d2832a00-c2b2-11ea-8cb6-8c14443470b7.png">

</details>

-----------------------
