### ISSUE TITLE
[Desktop] `Add to Brave` is not replaced in non-EN locales

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10570]
## Steps to Reproduce

   1. Run Brave in Polish locale
   2. Open `https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb`

## Actual result:

 `Add to Brave` is translated to `Dodaj do Chrome`
![image](https://user-images.githubusercontent.com/34715963/86621067-d155b280-bfbd-11ea-8558-fbc768ba8d4d.png)
![image](https://user-images.githubusercontent.com/34715963/86621081-d87cc080-bfbd-11ea-9b82-c2a1fa67e353.png)

## Expected result:
 `Add to Brave` is translated to `Dodaj do Brave`

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Ubuntu 18.04 LTS

Brave | 1.11.89 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Ubuntu 18.04 LTS

Brave | 1.12.73 Chromium: 84.0.4147.68 (Official Build) nightly (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @mkarolin @rebron @simonhong

**Comment by bsclifton** [comment]
I don't think there's anything we can do here?

Basically, there is a content script looking at this page which just replaced `Chrome` with `Brave`. @btlechowski can you confirm how this looks in Chrome?

As Google owns this page, we can't do anything

**Comment by btlechowski** [comment]
We are already changing `Chrome` to `Brave` in English
![image](https://user-images.githubusercontent.com/34715963/86746597-74004680-c03b-11ea-9fbe-0d78e356ded0.png)
![image](https://user-images.githubusercontent.com/34715963/86746546-6e0a6580-c03b-11ea-9794-6f39f32b75ab.png)

Chrome in Polish:
![image](https://user-images.githubusercontent.com/34715963/86749131-4a481f00-c03d-11ea-9800-3e83048ffb8a.png)

**Comment by bsclifton** [comment]
ah - sorry. For some reason, I thought the issue was a bad translation. This is definitely something actionable we should be able to fix

**Comment by btlechowski** [comment]
Still reproducible

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/96925381-5d7bdf00-14b4-11eb-8c26-0340585c36b7.png)

**Comment by gabrc52** [comment]
Can reproduce in Spanish as well. It’s probably present on all non-English languages, but I haven’t tested them all

**Comment by rebron** [comment]
cc: @emerick Is this something we can fix via Greaslion? I suspect we'd need to bring in `Add to Brave` into Greaselion as well.

**Comment by emerick** [comment]
Yes, seems fixable via a Greaselion script.

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` for now, as this cannot be checked until we get translations (see https://github.com/brave/brave-core/pull/17416#pullrequestreview-1318435907). Thanks for working through this with me @emerick!

**Comment by LaurenWags** [comment]
Translations were uplifted via https://github.com/brave/brave-browser/issues/29387 so this can be tested in `1.50.113` and above.
