### ISSUE TITLE
[Desktop] Sync V2 should have an app menu command for setup and configuration

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#10576]
v1 of sync had this, but v2 currently has this removed. We should re-add, which points at brave://settings/braveSync/setup

![image](https://user-images.githubusercontent.com/741836/86642119-840f1c00-bf90-11ea-8700-6451a4f4518b.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified `Sync` is listed in App Menu
![image](https://user-images.githubusercontent.com/34715963/89239914-e5132980-d5fa-11ea-8a1f-f066fdc18ed6.png)
Verified it opens `brave://settings/braveSync/setup`
![image](https://user-images.githubusercontent.com/34715963/89239936-f825f980-d5fa-11ea-8ffe-5d5a80ee1fa0.png)
