### ISSUE TITLE
Create npm scripts to set up a number of bookmarks, sync groups, and ledger sites

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1058]
Carried over from https://github.com/brave/browser-laptop/issues/9111

## Description
> Create npm scripts to set up a number of bookmarks, sync groups, and ledger sites, to make it easy to conduct performance tests.
>
> It is not easy to create 1000 bookmarks by hand. Even though you have done, the session file could get corrupted sometimes, and you would never create them again.
>
> A bookmark file example: https://gist.github.com/jgarber623/cdc8e2fa1cbcb6889872

**Comment by asbillings07** [comment]
Does this still need to be worked on? If so, I'd like to take on the challenge.

**Comment by bsclifton** [comment]
@asbillings07 yes - that would be great 😄 

You should be able to do one of the following fairly easily:
- create the task under `brave-browser` using Node.js; adding a new script to https://github.com/brave/brave-browser/tree/master/scripts
- create the task under `brave-core` using Python; adding a new script under https://github.com/brave/brave-core/tree/master/script 

Although you're welcome to explore other ways (this is just what we have available now) 😄 

We have some example bookmarks up at https://github.com/brave/qa-resources that you might be able to integrate with (ex: curl / wget / etc)
