### ISSUE TITLE
[Desktop] Move cosmetic filtering script injection logic from extension to native

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#10582]
With script injection in native, we can share it with android also.

Now, script injection is done at brave extension's content script.
I think we coud mov script injection to native by observing webcontent's loading state.
```
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  const action = typeof msg === 'string' ? msg : msg.type
  switch (action) {
    case 'cosmeticFilteringBackgroundReady': {
      if (msg.hideOptions !== undefined) {
        scheduleQueuePump(msg.hideOptions.hide1pContent, msg.hideOptions.generichide)
      }
      injectScriptlet(msg.scriptlet)
      break
    }

   ...
}
```

**Comment by antonok-edm** [comment]
It may be helpful to reference #5860, which adds a single hardcoded scriptlet injection on youtube.com for Android devices. That can be safely removed once general-purpose injection is working correctly.

**Comment by simonhong** [comment]
Upstream only allows using `content::RenderFrameHost::AllowInjectingJavaScript();` in only restricted configuration.
According to below comment, we should not use this for destkop and android also.
But, I'm not sure why upstream doesn't allow...

```
  // Globally allows for injecting JavaScript into the main world. This feature
  // is present only to support Android WebView, WebLayer, Fuchsia web.Contexts,
  // and CastOS content shell. It must not be used in other configurations.
  static void AllowInjectingJavaScript();
```

**Comment by simonhong** [comment]
@bridiver Could we call `content::RenderFrameHost::AllowInjectingJavaScript()` in desktop or android? Or we should avoid it?

**Comment by antonok-edm** [comment]
This was completed a while ago, desktop is currently running the native cosmetic filtering backend by default.
