### ISSUE TITLE
Remove "Show" from NTP Settings tab labels

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#10591]
In the NTP Settings, labels should not have the word "Show" in them. So `Show Brave Stats` should become `Brave Stats`

<img width="1130" alt="Screen Shot 2020-07-07 at 11 05 44 AM" src="https://user-images.githubusercontent.com/8732757/86823717-0ad00180-c042-11ea-849d-4ad58a3da006.png">

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.94 Chromium: 84.0.4147.85 (Official Build) (64-bit)
-- | --
Revision | e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{#837}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Confirmed `Show` does not display on the NTP section labels:
<img width="696" alt="Screen Shot 2020-07-10 at 8 01 24 AM" src="https://user-images.githubusercontent.com/28145373/87152452-b320d880-c283-11ea-8bc5-db9f5c2a5243.png">
<img width="704" alt="Screen Shot 2020-07-10 at 8 01 44 AM" src="https://user-images.githubusercontent.com/28145373/87152455-b4520580-c283-11ea-8e26-bc97d82e85e8.png">
