### ISSUE TITLE
[Desktop] Expired ad conversion is not removed from database 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10590]
Follow up to https://github.com/brave/brave-browser/issues/10240

## Steps to Reproduce

1. Run Brave that points to ads staging server
2. Download catalog [10240 expire.txt](https://github.com/brave/brave-browser/files/4885111/10240.expire.txt)
3. In the catalog change `endAt` to `now()+4hours`. the conversion's expire date will be `endAt+24h`
4. Load the ad catalog
5. Open `brave.com` and trigger the ad
6. Close the browser
7. Make the conversion expire
8. Run Brave
9. Open `https://www.interia.pl/` to trigger conversion
10. Check if the entry in the database(Default/ads_service/bundfle_state sqlite ad_conversions) was deleted

Important: The conversion is not triggered, which is good

## Actual result:

The entry in the database(Default/ads_service/bundfle_state sqlite ad_conversions) was not deleted:
![image](https://user-images.githubusercontent.com/34715963/86788513-8b085e00-c066-11ea-88f0-aaa5fe32778b.png)

## Expected result:
The entry is deleted

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.11.90 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @tmancey

**Comment by LaurenWags** [comment]
Reproduced on macOS

```
Brave	1.11.90 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
Revision	8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS	macOS Version 10.14.6 (Build 18G3020)
```

**Comment by tmancey** [comment]
@LaurenWags @btlechowski Discussed with @btlechowski as we only remove expired ad conversions once the catalog updates with a new catalog (i.e. the catalog id changes). This is not an issue as expired ad conversions are ignored when checking for new conversions. Thanks
