### ISSUE TITLE
[Desktop] Brave accepts TLS 1.0 and TLS 1.1 without any warning!

### ISSUE THREAD

**Issue by Cangarw** [brave/brave-browser#10607]
## Test Plan

Specified here: https://github.com/brave/brave-core/pull/6574

## Description 

Brave shows that TLS 1.0/1.1 is secure. You have to click on the lock icon to get a warning. But the lock should indicate that BEFORE clicking on it

## Steps to Reproduce

   1. go to [chair for E-Business of Univerity of Magdeburg](https://www.e-business.ovgu.de/) or [tls-v1-0.badssl.com 1](https://tls-v1-0.badssl.com:1010/) or [tls-v1-1.badssl.com 2](https://tls-v1-1.badssl.com:1011/)
   2. the site is using TLS 1.0 or TLS 1.1 and the lock next to the address bar is closed
   3. klick on the lock and then there will be a warning text

## Actual result:

The lock symbol shows a secure connection

## Expected result:
The lock symbol should show an "not secure connection"

## Reproduces how often: 

Every site that uses TLS 1.0 or TLS 1.1

## Brave version (brave://version info)

1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
  - yes
- Can you reproduce this issue with the beta channel? 
  - do not have the beta channel
- Can you reproduce this issue with the dev channel? 
  - do not have the dev channel
- Can you reproduce this issue with the nightly channel? 
  - do not have the nightly channel

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
  - no
- Does the issue resolve itself when disabling Brave Rewards? 
  - no
- Is the issue reproducible on the latest version of Chrome? 
  - no, chrome shows an "open lock" just like on an insecure http site

**Comment by rebron** [comment]
cc: @fmarier when you get a moment can you take a look?

**Comment by fmarier** [comment]
That's definitely a bug since this was [deprecated a while back in Chromium](https://www.chromestatus.com/feature/5654791610957824). We should be seeing interstitials like in Chrome:
![Screenshot from 2020-08-31 15-20-31](https://user-images.githubusercontent.com/167821/91774388-84492380-eb9d-11ea-95ca-7ad1bddf820f.png)

but for some reason that doesn't work in Brave, even with the following flags enabled:
![Screenshot from 2020-08-31 15-18-29](https://user-images.githubusercontent.com/167821/91774411-9034e580-eb9d-11ea-9217-145bfb7ddd46.png)

I tested this in Nightly:
```
Brave | 1.15.20 Chromium: 85.0.4183.83 (Official Build) nightly (64-bit)
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Linux
```

**Comment by bsclifton** [comment]
Digging in on this one...

- problem 1: we aren't defaulting the above values (in screenshot) to true 🤔 We'll want to do that
- problem 2: there's a config used when calling `ShouldSuppressLegacyTLSWarning` which is NOT initialized. This causes the check to fail and default to true:

See 
- https://source.chromium.org/chromium/chromium/src/+/master:services/network/ssl_config_service_mojo.cc;l=123-126;drc=4fdd27a642894a835da323789c52400c59e7b242
and
- https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/ssl/tls_deprecation_config.cc;l=64-68;drc=c777e0413404f32399668eb671942409bb59091b

**Comment by diracdeltas** [comment]
On Beta it doesn't even show the warning if you click on the icon. (It does for me on master)

**Comment by bsclifton** [comment]
Mystery solved - that config is initialized after a component is registered and installed via component updater
https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/component_updater/tls_deprecation_config_component_installer.cc;l=68;drc=1b7d93032127153194b576235f5697eadd84554f

By default, we don't 
![image](https://user-images.githubusercontent.com/4733304/91915708-20435f80-ec70-11ea-82cd-dd04ca0e683d.png)

If I visit brave://components and click `Check for update`, it will download
![image](https://user-images.githubusercontent.com/4733304/91915678-0bff6280-ec70-11ea-9939-68a81d1febfc.png)

After quitting/relaunching, it works as expected:
![image](https://user-images.githubusercontent.com/4733304/91915774-47019600-ec70-11ea-9b88-f07093fa64c1.png)

**Comment by bsclifton** [comment]
If we want this functionality, we should be able to:
1. Default the config values for `features::kLegacyTLSEnforced` and `security_state::features::kLegacyTLSWarnings`
2. Register this new component

**Comment by diracdeltas** [comment]
we definitely want to show TLS 1.0/1.1 as insecure like chrome does

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6574
- Reproduced the issue in `1.14.80` 
![image](https://user-images.githubusercontent.com/38657976/93082222-2a248400-f6ae-11ea-865f-d1aa1d1a4efd.png)
- Upgraded profile from `1.14.80` to `1.14.81` and ensured that the warning message is displayed 
![image](https://user-images.githubusercontent.com/38657976/93082382-78398780-f6ae-11ea-9c77-aebac5011844.png)
- Ensured that the warning message is displayed in a clean profile

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.14.82 x64 RC build
- Verified test plan from https://github.com/brave/brave-core/pull/6574

Error Page | Error page Advanced | Site info showing error
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/93342434-40a21b00-f827-11ea-9f45-41296b6e97dc.png) | ![image](https://user-images.githubusercontent.com/17010094/93342459-47309280-f827-11ea-9ff0-7366fc4b9d8c.png) | ![image](https://user-images.githubusercontent.com/17010094/93342477-4d267380-f827-11ea-8b78-224891403fe1.png)
