### ISSUE TITLE
[Desktop] Themes option in appearance settings doesn't working with NTP SR

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#10600]
## Description 

Themes subpage is not loaded when clicks themes option in settings with NTP SR

## Steps to Reproduce

   1. Prepare empty user dir (ex, mkdir ~/Library/ApplicationSupport/BraveSoftware/Brave-Browser-Nightly)
   2. Set test NTP SR (ex, echo "TECHNIK" > ~/Library/ApplicationSupport/BraveSoftware/Brave-Browser-Nightly/promoCode)
   3. Launch Brave nightly and wait NTP SR component is ready
   4. Check NTP shows SR images
   5. Load settings and click `Themes` option in `Appearance` section

## Actual result:

Nothing happened

## Expected result:
Themes subpage should be loaded

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.12.77 Chromium: 84.0.4147.68 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/88630226-e9f14e00-d0cd-11ea-9775-dc640435a93c.png)
