### ISSUE TITLE
[Desktop] Closes immediately on launching 

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#10609]
I just updated windows and now brave closes as soon as I launch it. This also happens with PWA installs. Occasionally it works but most the time it doesn't. I can't find a common thread between when it does.

https://gfycat.com/lightheartedlazycamel
![LightheartedLazyCamel](https://thumbs.gfycat.com/LightheartedLazyCamel-size_restricted.gif)

**Comment by ChildishGiant** [comment]
Windows 10 version 1909 (OS Build 18363.900)
Doesn't reproduce on nightly

**Comment by HarnischtheTrue** [comment]
same problem

**Comment by bsclifton** [comment]
@ChildishGiant curious what happens if you open that folder in Windows using explorer and right click / Run as Administator

You might also check the event viewer to see if anything was logged there (start => run, `eventvwr`)

**Comment by ChildishGiant** [comment]
I've not been able to reproduce again since. I don't recall doing anything to fix it and I can't find anything in event viewer of any relevance.

**Comment by bsclifton** [comment]
@HarnischtheTrue are you still having this problem?

**Comment by rebron** [comment]
Closing since this is fixed for @ChildishGiant. @HarnischtheTrue Let us know if you're still running into this issue on 1.13.82.
