### ISSUE TITLE
[Desktop] Previous pages opening on startup in addition to specific set of pages

### ISSUE THREAD

**Issue by OJ7** [brave/brave-browser#10611]
## Description 

I have a secondary (financials) profile created to open a set of five pages on startup. Whenever I close the last/only window for that profile and later launch the profile using the profile selector in the top right of the window, the new window shows the same tabs I left off on as well as the set of five pages I have set to show on startup. 

While writing this issue, I just tested with "Open the New Tab page" and that is exhibiting the same behavior as above so it seems like the settings have no effect.

## Steps to Reproduce

1. In a secondary profile, open up five random webpages
1. Go to [brave://settings/](brave://settings/)
1. Click "Open a specific page or set of pages"
1. Click "Use current pages"
1. Close window (all windows for profile)
1. In the main profile window, open the secondary profile using the profile switcher in the top right
1. Observe the tabs from last session are opened along with the tabs that were specified in the settings.

## Reproduces how often: 

I tried creating a new profile and I'm not able to reproduce the issue on there (yet).

## Brave version (brave://version info)

Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

Untested in other channels

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Hi @OJ7. I suspect this is the same behavior in Chrome. I'm wondering if a restart though will honor the  ""Use current pages" setting for your second profile. 

When you restart, on your second profile are you still seeing a secondary where you left off window or are you starting with the five pages on start up that you specified?

Also, when you get a chance, can you update to 1.13.82?

**Comment by OJ7** [comment]
I've been using the newer profile when I tried reproducing the issue and that's been working fine. I tried going back to the older profile and that seems to have been fixed now as well on 1.14.81.
