### ISSUE TITLE
[Android] Shields are not open in custom tab when browser is unloaded from memory

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#10612]
## Description 
Shields are not open in custom tab when browser is unloaded from memory

## Steps to reproduce 

   1. Unload browser from memory.
   2. Open custom tab (for example open link from Slack).
   3. Click on shields button, it won't open

## Actual result 
Shields are not opened

## Expected result
Shields are opened

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? no
   - Beta build? no

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.11.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan: follow STR

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.98 x64 build
- Verified able to open shields on a custom tab
- Verified changing shields settings on the page in a custom tab is retained when the same site is loaded in the browser
