### ISSUE TITLE
[Desktop] usage ping not sent for 1.11.92

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10610]
## Description 

Found while testing #10061 and #10230 

1.11.92 (Dev) is not sending a usage ping, but 1.11.90 does.

## Steps to Reproduce

   1. Open tool like Charles to watch network traffic
   2. Launch 1.11.92 with a clean profile
   3. Look for usage ping

## Actual result:

No usage ping
<img width="1194" alt="Screen Shot 2020-07-08 at 9 42 06 AM" src="https://user-images.githubusercontent.com/28145373/86926451-11bd4980-c100-11ea-95f3-7b8e9380345c.png">

## Expected result:
Should be a usage ping like there is with 1.11.90 (below was taken with a clean profile)
<img width="1245" alt="Screen Shot 2020-07-08 at 9 39 59 AM" src="https://user-images.githubusercontent.com/28145373/86926446-0ff38600-c100-11ea-9775-03e1fe274cac.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, works with 1.10.97
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? no, works with 1.12.79

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @keur @aekeus @rebron @brave/legacy_qa

**Comment by keur** [comment]
QA tested this on 1.12 and the issue is not present. Safe to assume there is some code the not included in the uplift causing problems. Let's just revert https://github.com/brave/brave-core/pull/5957 and wait until 1.12 for these changes. Thank you again QA team.

**Comment by kjozwiak** [comment]
Just some more context, also reproduced using the following build:

```
Brave | 1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.15.5 (Build 19F101)
```

I'm not seeing any usage pings under https://laptop-updates.brave.com. As per @keur, this is working on `1.12.x` and was QA'd via https://github.com/brave/brave-core/pull/5720#issuecomment-654936830 and https://github.com/brave/brave-core/pull/5823#issuecomment-654947673. @LaurenWags also confirmed that it's working on `1.12.x`.

**Comment by kjozwiak** [comment]
Reverted via https://github.com/brave/brave-core/pull/6032. Should recheck to make sure pings are still working once we get a new `1.11.x` 👍

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.94 Chromium: 84.0.4147.85 (Official Build) (64-bit)
-- | --
Revision | e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{#837}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description
<img width="1191" alt="Screen Shot 2020-07-10 at 7 57 21 AM" src="https://user-images.githubusercontent.com/28145373/87152182-3aba1780-c283-11ea-8d58-6d76dc011f91.png">
