### ISSUE TITLE
[Desktop] syncv2 info bar flashes on screen and disappears without user interaction

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10621]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/10231

Following plan A from the PR (https://github.com/brave/brave-core/pull/5806), the info bar flashes on screen and goes away without user interaction. If you blink, you'll miss it.

## Steps to Reproduce

Adapted from Plan A of PR:
   1. Clean profile 1.11.x
   2. Navigate to brave://flags, enable sync flag
   3. Restart, dismiss info bar telling you to make Brave your default browser. 
   4. Navigate to brave://sync, enable sync/set up sync chain.
   5. Restart browser
   6. Watch carefully for info bar before it disappears. 

## Actual result:

sync v2 info bar flashes on screen
![syncv2infobar](https://user-images.githubusercontent.com/28145373/86960840-1e589680-c12e-11ea-8908-464e8beb355a.gif)

## Expected result:
sync v2 info bar should be shown until user interacts with it

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @petemill @rebron @bsclifton @brave/legacy_qa

**Comment by LaurenWags** [comment]
Note - if you do the sync set up in 1.10.97 and then upgrade to 1.11.x this still happens (info bar flashes and disappears on upgrade to 1.11.x).

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/6070 was reverted and merged.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.96 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description, additional scenarios will be tested with https://github.com/brave/brave-browser/issues/10231
* Confirmed sync info bar is not dismissed on relaunch:
<img width="1193" alt="Screen Shot 2020-07-14 at 1 44 22 PM" src="https://user-images.githubusercontent.com/28145373/87458628-3faafe00-c5d8-11ea-95cf-fcbff5ed9433.png">
