### ISSUE TITLE
[Android] chrome://flags combines Chromium version number with Brave version number

### ISSUE THREAD

**Issue by dentistformyeye** [brave/brave-browser#10629]
## Description 
The version number in chrome://flags is incorrect.

## Steps to reproduce 

   1. Verify that Brave Android is 1.10.99 (Chromium 83.0.4103.116) in chrome://version
   2. Go to chrome://flags and check the version number.

## Actual result 
Version number is 83.1.10.99

## Expected result
Version number should be 83.0.4103.116

## Issue reproduces how often 
Easily reproduced.

## Issue happens on 
   - Current Play Store version? Yes.
   - Beta build? No.

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 6.0.1
   
## Brave version
1.10.99

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
This is on purpose to show the major Chromium version along with the Brave version, Closing as wont fix.

cc: @bsclifton
