### ISSUE TITLE
[Desktop] brave://flags combines Chromium version number with Brave version number 

### ISSUE THREAD

**Issue by dentistformyeye** [brave/brave-browser#10630]
## Description 

The version number in brave://flags is incorrect.

## Steps to Reproduce

   1. Verify that Brave Desktop is 1.10.97 (Chromium 83.0.4103.116) in brave://version
   2. Go to chrome://flags and check the version number in the top right.

## Actual result:

![image](https://user-images.githubusercontent.com/51429646/86969081-3256c500-c13b-11ea-908b-d71c5839f3f8.png)

## Expected result:
Version number should be 83.0.4103.116

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.15.4 (Build 19E266)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Haven't tried.
- Can you reproduce this issue with the dev channel? Haven't tried.
- Can you reproduce this issue with the nightly channel? Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

The same thing happens in Android. #10629

**Comment by srirambv** [comment]
Same as mentioned in https://github.com/brave/brave-browser/issues/10629#issuecomment-655932787
