### ISSUE TITLE
Brave blocks amazon video as ads

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1064]
Carried over from https://github.com/brave/browser-laptop/issues/9367

## Description
Brave ad blocks blocks amazon video stream

## Steps to reproduce
1. go to amazon.com / amazon.de
2. go to prime video
3. start any video with ad block on
4. disable ad block and retry ... works

**Comment by bsclifton** [comment]
Thanks to @mkhl for confirming this is still an issue - also cc: @Mephiztopheles in case you want to subscribe for updates 😄

**Comment by mkhl** [comment]
@bsclifton Thanks!

**Comment by Mephiztopheles** [comment]
Hey there,
any news to this?

**Comment by karenkliu** [comment]
This is still an issue for me. Does this have anything to do with https://github.com/brave/brave-browser/issues/3253 ?

**Comment by kjozwiak** [comment]
@bsclifton seems like a dupe of #3253 as @karenkliu pointed out above?

**Comment by bsclifton** [comment]
@kjozwiak yes - I do believe it is 😄
