### ISSUE TITLE
[Desktop] Fix deps in //brave/components/*

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10640]
```
$ gn check . //brave/components/*

ERROR at //brave/components/p3a/brave_p3a_service.cc:20:11: Include not allowed.
#include "brave/browser/brave_stats_updater_util.h"
          ^---------------------------------------
It is not in any dependency of
  //brave/components/p3a:p3a
The include file is in the target(s):
  //brave/browser:browser_process
which should somehow be reachable.
___________________
ERROR at //brave/components/p3a/brave_p3a_service.cc:21:11: Include not allowed.
#include "brave/browser/version_info.h"
          ^---------------------------
It is not in any dependency of
  //brave/components/p3a:p3a
The include file is in the target(s):
  //brave/browser:version_info
which should somehow be reachable.
___________________
ERROR at //brave/components/p3a/brave_p3a_service.cc:23:11: Can't include this header from here.
#include "brave/common/pref_names.h"
          ^------------------------
```

Also fix this: https://github.com/brave/brave-core/pull/6306/files#diff-06297a6e28b42e955d3d35f964106237R6

**Comment by iefremov** [comment]
There is still circular dependency, so reverted the initial PR https://github.com/brave/brave-core/pull/6296

**Comment by Gyuyoung** [comment]
> There is still circular dependency, so reverted the initial PR [brave/brave-core#6296](https://github.com/brave/brave-core/pull/6296)

The original CL extracted |stats_updater| target in brave/browser/ to avoid the circular dependency in //brave/components/p3a/. But, I forgot to check the |stats_updater| target. Now I upload a PR to re-land it - https://github.com/brave/brave-core/pull/6297. But, there is still unsolved issue on the |stats_updater| target. So, I add "check_includes = false" to the target for now.
