### ISSUE TITLE
[Android] Blocked item count keeps increasing on shields 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10667]
## Description 
Blocked item count keeps increasing on shields 

## Steps to reproduce 

   1. Install 1.13.2 nightly build
   2. Visit espn.com on a tab
   3. Wait for the page to load, blocked items count keeps increasing

## Actual result 
![blk](https://user-images.githubusercontent.com/17010094/87032488-54ffe100-c202-11ea-8e51-0b9dc0bda833.gif)

## Expected result
Only show items blocked

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NO
   - Beta build?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet and Phone
   - Android version: 9/10
   
## Brave version
1.13.2 Nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

New tab only shows the items blocked but shields count keeps increasing

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/brave-shields-bug/163288

**Comment by anthonypkeane** [comment]
@deeppandya thinks this is fixed in more recent builds. pls re-open it not. Thanks
