### ISSUE TITLE
Bug: update version Dev

### ISSUE THREAD

**Issue by franco27** [brave/brave-browser#1066]
Hello

My config: Windows 10 x64 

The update could not be performed since Brave ; today he said he is up to date and he was in version "Developer Channel v0.55.1"

[img]https://i.imgur.com/reaReP7.png[/img]

1/ A few days ago I installed the version dev 0.55.1
2/ today by the browser Brave, he notified that he was up to date by the tab "chrome://settings/help"
3/ I did refresh several times but refuses to notify me of the current version 0.55.2 .
4/ I was forced to update to the 0.55.2 version, download the file BraveBrowserDevSetup.exe

**Comment by srirambv** [comment]
Did you get the option to Relaunch button next to the update? Are you saying you don't see a notification bar that there was an update available?

**Comment by franco27** [comment]
I saw that Brave was looking for an update but he did not notify any new updates.  On Github there is a new version.

**Comment by srirambv** [comment]
The update notifier isn't available yet. You can see the conversation here for more info https://github.com/brave/brave-browser/issues/877
