### ISSUE TITLE
[Android] Bottom bar tab swipe is not working 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10668]
## Description 
 Bottom bar tab swipe is not working 

## Steps to reproduce 

   1. Install 1.13.2 and open a bunch of tabs
   2. Swipe on the bottom bar to switch between tabs 
   3. Doesn't swipe

## Actual result 
 Bottom bar tab swipe is not working 

## Expected result
Should switch to tabs back./forward based on swipe direction

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet):Phone
   - Android version: 10
   
## Brave version
1.13.2 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik

**Comment by srirambv** [comment]
This needs to be fixed and uplifted for 1.11.x as its broken on 1.11.93 as well. Possibly due to CR bump? 

cc: @SergeyZhukovsky

**Comment by srirambv** [comment]
Removed as part of https://chromium.googlesource.com/chromium/src/+/6db06b5cc4b9c167b8bd70e5ff20953b6b158406. Will waiting for upstream as per internal discussion https://bravesoftware.slack.com/archives/C0816QH3R/p1594645727110100

**Comment by krystean** [comment]
At least the top bar swipe still functions. However, if you did swipe the top bar to change tabs, the bottom bar's "ghost" still remains and blocks part of the page.

If upstream decides to remove it, I guess Brave should follow suit as they may implement another functionality, however that functionality is currently nonexistent so I guess it wouldn't hurt to roll back this change. It's useful too.

**Comment by eljuno** [comment]
+1 form Community

https://community.brave.com/t/cant-swipe-on-buttom-tool-bar-to-change-open-tabs/148111?u=eljuno

**Comment by srirambv** [comment]
+1 from @Valiceemo via #11083

**Comment by szaimen** [comment]
Would also love to see this working again. It is one of the best tab surfing features and very essential, imho.

**Comment by stdedos** [comment]
https://community.brave.com/t/duet-lower-bar-cannot-be-used-to-swipe-to-previous-next-tab/154395/2

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build
- Verified bottom bar swipe works as expected in switching between tabs
