### ISSUE TITLE
[Desktop] WebGL Drawing FP blocking not working correctly when FP set to Strict

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10675]
## Description 

When testing on our QA test pages for FP farbling, I noticed that if FP is set to Strict, WebGL Drawing does not appear to be working correctly.

Per discussion with @pes10k logging this and tagging @pilgrim-brave to hopefully take a look.

## Steps to Reproduce

1. Clean profile 1.11.92
2. Navigate to https://dev-pages.bravesoftware.com/farbling.html and https://dev-pages.brave.software/farbling.html
3. Confirm FP setting is `Standard` in shields
4. Generate FPs on both pages, confirm they look as expected. (ie. - they are the same across each row on each page but differ between pages for all that have Version - 1.11)
<img width="1201" alt="Standard" src="https://user-images.githubusercontent.com/28145373/87060006-fde51680-c1d7-11ea-970e-08c7e30cc3ec.png">

5. Restart browser.
6. For both pages, change FP to `Allow All` in shields
7. Generate FPs, confirm they look as expected. (ie - they are the same across each row and the same on both pages)
<img width="1198" alt="Allow All" src="https://user-images.githubusercontent.com/28145373/87060077-12291380-c1d8-11ea-8a94-e6a1b12d85b5.png">

8. Restart browser.
9. For both pages, change FP to `Strict` in shields
10 Generate FPs.

## Actual result:

WebGL Drawing is the same on both pages
<img width="1198" alt="Strict" src="https://user-images.githubusercontent.com/28145373/87060126-24a34d00-c1d8-11ea-9859-de2ebd867915.png">

## Expected result:
Expected WebGL Drawing to be different on both pages (but the same across its row)

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.11.92

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a, strict setting not available in 1.10.x
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? yes (1.11.x)
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on:

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/88720858-d5d93b00-d125-11ea-84ff-aad3aec2fe6e.png)

**Comment by pes10k** [comment]
Thanks all for documenting this!

cc @pilgrim-brave

**Comment by pes10k** [comment]
I've updated the test page text so that is clear that the farbling-style protections (different per-session, per-etld+1) should only hold in "standard" protections, and not "strict" (bc in strict we just block WebGL drawing all together, since its too difficult to randomize), and so blocking will look identical in all origins.

Thanks @LaurenWags for reporting!

**Comment by pes10k** [comment]
i've labeled "not actionable" only bc there isn't a "it was pete's test fault, not Mark's code fault" option ;)

**Comment by LaurenWags** [comment]
Removing `QA/Yes` tag since it's been tagged `closed/not-actionable`, but I did confirm both pages now reflect that WebGL Drawing farbling is only available in "standard" mode 👍 

<img width="1197" alt="Screen Shot 2020-08-31 at 10 27 04 AM" src="https://user-images.githubusercontent.com/28145373/91731260-b2fed400-eb74-11ea-9708-cfbc3c968b0e.png">
<img width="1196" alt="Screen Shot 2020-08-31 at 10 27 13 AM" src="https://user-images.githubusercontent.com/28145373/91731266-b4300100-eb74-11ea-9c97-5bf770d69aa9.png">
