### ISSUE TITLE
[Desktop] Manual test run for Tor 1.0.12 component update on macOS

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#10678]
#### Tor Client Updater 

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=/tmp/component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
- [x] Navigate to `brave.com` and `http://3g2upl4pq6kufc4m.onion/` to check if the sites work correctly.

#### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid

#### Tor Client Updater 

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=/tmp/component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
- [x] Navigate to `brave.com` and `http://3g2upl4pq6kufc4m.onion/` to check if the sites work correctly.

#### MacOS
- [ ] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [ ] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid

#### Tor Client Updater 

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=/tmp/component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
- [x] Navigate to `brave.com` and `http://3g2upl4pq6kufc4m.onion/` to check if the sites work correctly.

#### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid

#### Tor Client Updater 

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=/tmp/component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
- [x] Navigate to `brave.com` and `http://3g2upl4pq6kufc4m.onion/` to check if the sites work correctly.

#### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid

#### Tor Client Updater 

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=/tmp/component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
- [x] Navigate to `brave.com` and `http://3g2upl4pq6kufc4m.onion/` to check if the sites work correctly.

#### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid

#### Tor Client Updater 

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=/tmp/component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
- [x] Navigate to `brave.com` and `http://3g2upl4pq6kufc4m.onion/` to check if the sites work correctly.

#### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid

**Comment by kjozwiak** [comment]
#### **`macOS 10.15 Catalina - PASSED`** 

Verification **PASSED** using the following build:

```
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.15.5 (Build 19F101)
```

<img width="307" alt="Screen Shot 2020-07-13 at 11 50 24 PM" src="https://user-images.githubusercontent.com/2602313/87381991-f751f880-c563-11ea-8413-8a604cea8f0c.png">

```
Jul 13 23:50:40.258 [notice] Tor 0.3.5.11 running on Darwin with Libevent 2.1.9-beta, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jul 13 23:50:40.258 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 13 23:50:40.258 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Jul 13 23:50:40.261 [notice] Opening Socks listener on 127.0.0.1:9350
Jul 13 23:50:40.261 [notice] Opened Socks listener on 127.0.0.1:9350
Jul 13 23:50:40.261 [notice] Opening Control listener on 127.0.0.1:0
Jul 13 23:50:40.261 [notice] Control listener listening on port 56112.
Jul 13 23:50:40.261 [notice] Opened Control listener on 127.0.0.1:56112
```

```
kjozwiak@Kamils-MBP 1.0.12 % codesign -vvvv tor-0.3.5.11-darwin-brave-0
tor-0.3.5.11-darwin-brave-0: valid on disk
tor-0.3.5.11-darwin-brave-0: satisfies its Designated Requirement
```

#### **`macOS 10.13 High Sierra - PASSED`**

Verification **PASSED** using the following build:

```
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.13.6 (Build 17G13035)
```

<img width="324" alt="Screen Shot 2020-07-14 at 12 15 40 AM" src="https://user-images.githubusercontent.com/2602313/87383478-4fd6c500-c567-11ea-9f84-46a99005031e.png">

```
Jul 14 00:15:48.970 [notice] Tor 0.3.5.11 running on Darwin with Libevent 2.1.9-beta, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jul 14 00:15:48.971 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 14 00:15:48.971 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Jul 14 00:15:48.975 [notice] Opening Socks listener on 127.0.0.1:9350
Jul 14 00:15:48.975 [notice] Opened Socks listener on 127.0.0.1:9350
Jul 14 00:15:48.975 [notice] Opening Control listener on 127.0.0.1:0
Jul 14 00:15:48.975 [notice] Control listener listening on port 49234.
Jul 14 00:15:48.975 [notice] Opened Control listener on 127.0.0.1:49234
```

```
macos-10:1.0.12 kjozwiak$ codesign -vvvv tor-0.3.5.11-darwin-brave-0
tor-0.3.5.11-darwin-brave-0: valid on disk
tor-0.3.5.11-darwin-brave-0: satisfies its Designated Requirement
```

#### **`macOS 10.12 Sierra - PASSED`**

Verification **PASSED** using the following build:

```
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.12.6 (Build 16G2136)
```

<img width="303" alt="Screen Shot 2020-07-14 at 12 30 11 AM" src="https://user-images.githubusercontent.com/2602313/87384237-3d5d8b00-c569-11ea-8ef4-f788240b0aff.png">

```
Jul 14 00:30:15.530 [notice] Tor 0.3.5.11 running on Darwin with Libevent 2.1.9-beta, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jul 14 00:30:15.530 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 14 00:30:15.530 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Jul 14 00:30:15.534 [notice] Opening Socks listener on 127.0.0.1:9350
Jul 14 00:30:15.534 [notice] Opened Socks listener on 127.0.0.1:9350
Jul 14 00:30:15.534 [notice] Opening Control listener on 127.0.0.1:0
Jul 14 00:30:15.534 [notice] Control listener listening on port 49194.
Jul 14 00:30:15.534 [notice] Opened Control listener on 127.0.0.1:49194
```

```
macos-10:1.0.12 kjozwiak$ codesign -vvvv tor-0.3.5.11-darwin-brave-0 
tor-0.3.5.11-darwin-brave-0: valid on disk
tor-0.3.5.11-darwin-brave-0: satisfies its Designated Requirement
```

#### **`macOS 10.11 El Capitan - PASSED`**

Verification **PASSED** using the following build:

```
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | OS X Version 10.11.6 (Build 15G22010)
```

<img width="1248" alt="Screen Shot 2020-07-13 at 9 28 40 PM" src="https://user-images.githubusercontent.com/2602313/87385542-4f8cf880-c56c-11ea-8508-21aa54c2e2e8.png">

```
Jul 14 00:51:27.204 [notice] Tor 0.3.5.11 running on Darwin with Libevent 2.1.9-beta, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jul 14 00:51:27.205 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 14 00:51:27.205 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Jul 14 00:51:27.208 [notice] Opening Socks listener on 127.0.0.1:9350
Jul 14 00:51:27.208 [notice] Opened Socks listener on 127.0.0.1:9350
Jul 14 00:51:27.208 [notice] Opening Control listener on 127.0.0.1:0
Jul 14 00:51:27.208 [notice] Control listener listening on port 49191.
Jul 14 00:51:27.208 [notice] Opened Control listener on 127.0.0.1:49191
```

```
osx-10:1.0.12 kjozwiak$ codesign -vvvv tor-0.3.5.11-darwin-brave-0
tor-0.3.5.11-darwin-brave-0: valid on disk
tor-0.3.5.11-darwin-brave-0: satisfies its Designated Requirement
```

#### **`macOS 10.10 Yosemite - PASSED`**

Verification **PASSED** using the following build:

```
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | OS X Version 10.10.5 (Build 14F2511)
```

<img width="323" alt="Screen Shot 2020-07-14 at 1 08 04 AM" src="https://user-images.githubusercontent.com/2602313/87386443-7cdaa600-c56e-11ea-8f32-5c239bfdbfb2.png">

```
Jul 14 01:08:18.370 [notice] Tor 0.3.5.11 running on Darwin with Libevent 2.1.9-beta, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jul 14 01:08:18.371 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 14 01:08:18.371 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Jul 14 01:08:18.374 [notice] Opening Socks listener on 127.0.0.1:9350
Jul 14 01:08:18.374 [notice] Opened Socks listener on 127.0.0.1:9350
Jul 14 01:08:18.374 [notice] Opening Control listener on 127.0.0.1:0
Jul 14 01:08:18.374 [notice] Control listener listening on port 49186.
Jul 14 01:08:18.374 [notice] Opened Control listener on 127.0.0.1:49186
```

```
osx-10:1.0.12 kjozwiak$ codesign -vvvv tor-0.3.5.11-darwin-brave-0 
tor-0.3.5.11-darwin-brave-0: valid on disk
tor-0.3.5.11-darwin-brave-0: satisfies its Designated Requirement
```

**Comment by LaurenWags** [comment]
#### **`macOS 10.14 Mojave - PASSED`** 

Verification **PASSED** using the following build:

```
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

<img width="306" alt="Screen Shot 2020-07-14 at 7 41 22 AM" src="https://user-images.githubusercontent.com/28145373/87421740-6e5bb100-c5a5-11ea-9727-55430212a349.png">

```
Jul 14 07:42:07.154 [notice] Tor 0.3.5.11 running on Darwin with Libevent 2.1.9-beta, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jul 14 07:42:07.155 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 14 07:42:07.155 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Jul 14 07:42:07.160 [notice] Opening Socks listener on 127.0.0.1:9350
Jul 14 07:42:07.161 [notice] Opened Socks listener on 127.0.0.1:9350
Jul 14 07:42:07.161 [notice] Opening Control listener on 127.0.0.1:0
Jul 14 07:42:07.161 [notice] Control listener listening on port 58654.
Jul 14 07:42:07.161 [notice] Opened Control listener on 127.0.0.1:58654
```

```
lauren$ codesign -vvvv tor-0.3.5.11-darwin-brave-0 
tor-0.3.5.11-darwin-brave-0: valid on disk
tor-0.3.5.11-darwin-brave-0: satisfies its Designated Requirement
```
