### ISSUE TITLE
[Desktop] Manual test run for Tor 1.0.12 component update on Windows

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#10679]
#### Tor Client Updater

- [ ] For development go-update-server. Run brave-browser with `--user-data-dir=/tmp/component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
- [x] Navigate to `brave.com` and `http://3g2upl4pq6kufc4m.onion/` to check if the sites work correctly.

### Windows
- [x] Setup Windows SDK by downloading - https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
- [x] Run `"C:\Program Files (x86)\Windows Kits\10\bin\x86\signtool.exe" verify /pa "C:\Users\<user>\AppData\Local\BraveSoftware\Brave-Browser-<channel>\User Data\cpoalefficncklhjfpglfiplenlpccdb\<version>\tor-<version-tor>-win-brave-<version-brave>.exe"` to verify if the signature of the binary is correct.

#### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=/tmp/component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
- [x] Navigate to `brave.com` and `http://3g2upl4pq6kufc4m.onion/` to check if the sites work correctly.

### Windows
- [x] Setup Windows SDK by downloading - https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
- [x] Run `"C:\Program Files (x86)\Windows Kits\10\bin\x86\signtool.exe" verify /pa "C:\Users\<user>\AppData\Local\BraveSoftware\Brave-Browser-<channel>\User Data\cpoalefficncklhjfpglfiplenlpccdb\<version>\tor-<version-tor>-win-brave-<version-brave>.exe"` to verify if the signature of the binary is correct.

**Comment by GeetaSarvadnya** [comment]
**Windows 10 x64- PASSED**
![image](https://user-images.githubusercontent.com/38657976/87404369-aed62180-c5db-11ea-8084-ae4b1309a113.png)


```
c:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86>BraveSign.exe verify /pa "c:\Users\Dell\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.11\tor-0.3.5.10-win32-brave-0"
File: c:\Users\Dell\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.11\tor-0.3.5.10-win32-brave-0
Index  Algorithm  Timestamp
========================================
0      sha256     Authenticode

Successfully verified: c:\Users\Dell\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.11\tor-0.3.5.10-win32-brave-0

```

**Comment by LaurenWags** [comment]
**Windows 10 x86 - PASSED**

```
Brave	1.10.97 Chromium: 83.0.4103.116 (Official Build) (32-bit)
Revision	8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS	Windows 10 OS Version 1909 (Build 18363.592)
```

<img width="306" alt="Screen Shot 2020-07-14 at 7 41 22 AM" src="https://user-images.githubusercontent.com/28145373/87424096-5f76fd80-c5a9-11ea-94e2-ebbe1d8070b2.png">

```
Jul 14 08:12:01.135 [notice] Tor 0.3.5.11 running on Windows 8 [or later] with Libevent 2.1.9-beta, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jul 14 08:12:01.137 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 14 08:12:01.143 [notice] Configuration file "c:\nonexistent" not present, using reasonable defaults.
Jul 14 08:12:01.160 [notice] Opening Socks listener on 127.0.0.1:9350
Jul 14 08:12:01.162 [notice] Opened Socks listener on 127.0.0.1:9350
Jul 14 08:12:01.162 [notice] Opening Control listener on 127.0.0.1:0
Jul 14 08:12:01.163 [notice] Control listener listening on port 50104.
Jul 14 08:12:01.164 [notice] Opened Control listener on 127.0.0.1:50104
```

```
C:\Program Files\Windows Kits\10\bin\10.0.18362.0\x86>BraveSign.exe verify /pa "c:\Users\Lauren Wagner\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.12\tor-0.3.5.11-win32-brave-0"
File: c:\Users\Lauren Wagner\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.12\tor-0.3.5.11-win32-brave-0
Index  Algorithm  Timestamp
========================================
0      sha256     Authenticode

Successfully verified: c:\Users\Lauren Wagner\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.12\tor-0.3.5.11-win32-brave-0
```
