### ISSUE TITLE
Ads catalog cannot be accessed and no ads

### ISSUE THREAD

**Issue by teddywest32** [brave/brave-browser#10685]
# Description 
I was getting ads before but it has been more than a week I haven't got any ads. I have diagnosed using [this blog post](https://www.publish0x.com/null/brave-browser-how-to-check-which-ads-are-being-served-in-you-xejvnoj) 
and the browser cannot open "https://ads-serve.brave.com/v2/catalog" URL. 
I am using AWS EC2 instance and the issue seems to be persistent over AWS.

## Steps to Reproduce
   1.  Have an AWS EC2 instance running windows server image.
   2.  Open "https://ads-serve.brave.com/v2/catalog" on any browser
   3.  Nothing displays in the browser
   4. Check C:/Users/YOURUSERNAME/AppData/Local/BraveSoftware/Brave-Browser/User Data/default/ads_service and no catalog.json is found.

## Actual result:
Blank screen appears. 
The url: https://ads-serve.brave.com/v2 can be accessed and the below results appear:
{"statusCode":404,"error":"Not Found","message":"Cannot GET /v2"}

## Expected result:
Show the JSON data that consists of catalog.json data.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Build: 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Revision: 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{# 716}
OS: Windows Server OS Version 1809 (Build 17763.1282)

## Version/Channel Information:
- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Not checked
- Can you reproduce this issue with the dev channel? 
Not checked
- Can you reproduce this issue with the nightly channel? 
Not checked

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
Yes, also in firefox too.

**Comment by jsecretan** [comment]
HI @teddywest32 it is not recommended to use these over AWS instances as it makes it hard for the ad server to reliably determine the proper region for ads catalogs.
