### ISSUE TITLE
[Desktop] amount is showing zero value in logs when the existing wallet is restored

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10687]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/10315
amount is showing zero value in logs when the existing wallet is restored
## Steps to Reproduce

   1. Clean profile 1.11.x
   2. Enable rewards
   3. Connect KYC'd uphold staging wallet which has some balance (balance>0 BAT)
   4. Check the logs in POST requests to v2/wallet/WALLET_ID/claim endpoint
   5. Amount is showing as `0` `{"body":{"denomination":{"amount":"0","currency":"BAT"}`

## Actual result:

The amount is displayed as zero 

```
[ REQUEST ]
> URL: https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/WALLETID/claim
> Method: UrlMethod::POST
> Content: {"anonymousAddress":"b7621c6a-a762-4dd9-9ce1-7b153b26ee86","signedTx":{"body":{"denomination":{"amount":"0","currency":"BAT"},"destination":"d236e4dd-fca1-4f71-8756-37332fa4c593"},"headers":{"digest":"SHA-256=J2naWF66Pr5ihunvHdloPSA9/1vqQ9leQOOIJRMLVwU=","signature":"keyId=\"primary\",algorithm=\"ed25519\",headers=\"digest\",signature=\"MBBrcGUVSKpxKhz7bnf2tGcBUCj2oR3x4UiG9WkZjsLg01J3EVnkE2iIp8rDYAK7ptREVTrCM8Yx+g/x9ptyBA==\""},"octets":"{\"denomination\":{\"amount\":\"0\",\"currency\":\"BAT\"},\"destination\":\"d236e4dd-fca1-4f71-8756-37332fa4c593\"}"}}
> Content Type: application/json; charset=utf-8
> Header Content-Type: application/json; charset=UTF-8
[7000:22576:0710/133332.108:VERBOSE6:uphold.cc(165)]
[ RESPONSE - OnFetchBalance ]
> Url: https://api-sandbox.uphold.com/v0/me/cards/d236e4dd-fca1-4f71-8756-37332fa4c593
> Result: Success
> HTTP Code: 200
```

## Expected result:

The amount should be displayed as non zero 
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.11.94 Chromium: 84.0.4147.85 (Official Build) (64-bit)
-- | --
Revision | e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{#837}
OS | Windows 10 OS Version 1903 (Build 18362.900)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @AndriusA @NejcZdovc @brave/legacy_qa 

@AndriusA @NejcZdovc - Please feel free to close the issue if it's expected

**Comment by NejcZdovc** [comment]
this is expected as this API is only used for user funds and not for grants. So you should see after this request also a request like this ` /v1/suggestions/claim` that has a lot of tokens in there. And just to confirm VG is transferred to Uphold at the end right?

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Got it Thanks! Yes VG (Ad grants) are moved to uphold card.
