### ISSUE TITLE
[Desktop] Brave not installing

### ISSUE THREAD

**Issue by farwl** [brave/brave-browser#10682]
## Description 
I downloaded Brave installer and I'm thrown an error; "Installer failed to decompress archive. Please download Brave again."
I've downloaded Brave at least 20 times now. I've tried different releases / versions.

## Steps to Reproduce

   1. Download ANY version / release of Brave.
   2. Open installer.
   3. doesn't work..

## Actual result:
didn't work

## Expected result:
for it to work? maybe install?

## Reproduces how often: 
every time

## Brave version (brave://version info)

latest / any version

## Version/Channel Information:

?

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the dev channel? 
Yes
- Can you reproduce this issue with the nightly channel? 
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

![image](https://user-images.githubusercontent.com/44182379/87089596-a5783e00-c204-11ea-938b-8255bc3aa4e3.png)

**Comment by llamaiscoollmao** [comment]
This might happen because your firewall/antivirus blocks the download.

**Comment by rebron** [comment]
Hi @farwl Can you try two more times at https://brave.com/download/ and if that's not successful here:
https://github.com/brave/brave-browser/releases/tag/v1.13.82
You'll want BraveBrowserStandaloneSetup.exe on that list, I believe you're on Windows.

**Comment by rebron** [comment]
@farwl Can you tell us what Windows version you're running?

**Comment by rebron** [comment]
cc: @Brave-Matt

**Comment by farwl** [comment]
Hey I've actually been using Brave for a while now sorry for not updating on this. I got it working by using the Standalone Setup.

I'm using Windows 10 Home Edition / Version 10.0.18363
