### ISSUE TITLE
Can not download attachments in Gmail - UBUNTU 18.4.1 LTS Brave 55.2

### ISSUE THREAD

**Issue by scottf007** [brave/brave-browser#1068]
When in Gmail and I try to download an attachment it does not work. The button highlights, I can preview the pdf, I can open the pdf in a new window, but not download it. 

from console
using default settings 

m=sps,spl,spit,m_i,spt,t,it:4355 Resource interpreted as Document but transferred with MIME type application/pdf: "https://mail.google.com/mail/u/0/?ui=2&ik=4ecc431960&attid=0.1&permmsgid=msg-f:1610921310991853986&th=165b2465b6c6a9a2&view=att&disp=safe".
ICd.ha @ m=sps,spl,spit,m_i,spt,t,it:4355
V6g @ m=o2ajQe,sy1tx,sy1tr,sy1ty,sy1v6,sy1v9,sy1vg,sy1vn,NVcOs,sy1tt,sy1tw,sy1tu,sy1vb,Av2a7c,sy1tz,sy1u2,PaBahd,dFpypf,sy1rc,sy1sk,sy1tj,sy1ss,sy1ro,sy1th,sy1sl,sy1tm,sy1tq,sy1r2,sy1qc,sy1rk,sy1rm,sy1t2,sy1td,sy1tc,sy1ti,sy1tf,sy1tg,sy1tl,sy1tp,sy1tn,igbF5,MigGy,Sz7W7c,sy1v7,sy1ri,sy1ud,sy1ee,sy1qz,sy1va,sy1v8,sy1vf,sy1vd,sy1ve,PZhDZb,sy1r3,sy1r1,sy1rf,sy1u4,rMQdJc,J03Die,sy1sy,sy1u0,sy1rh,sy1u1,sy1u3,CTcde,sy16d,sy16e,sy19k,sy1a4,sy1a5,sy163,sy169,sy160,sy19l,sy19i,sy19j,sy19m,sy18x,sy18y,sy19w,sy19x,sy1a3,sydp,sy15w,sy16f,sy16a,sy16h,sy162,sy183,sy1b4,sy18u,sy19n,sy19y,sy1a2,sy190,sy1aj,sy161,sy16g,sy16r,sy196,sy1cn,sy1di,sy1dk,sy199,sy19a,sy19b,sy1bd,sy1b6,sy181,sy185,sydf,sy1bc,sy1bb,sy1ab,sy19h,sy1a1,sy1br,sy191,sy18t,sy1dw,sy1dv,sy1ds,syfj,sy1dr,sy1dq,sy16q,sy16t,sy1da,sydj,syoe,sy1an,sy194,sy1ao,sy1b8,sy1b3,sy182,sy184,sy1bi,sy1bj,sy1bk,sy1bg,sy1b5,sy1gk,sy1ec,sy19p,sy1ct,sy1cs,sy1a6,sy1aa,sy1ap,sy1b1,sy1ag,sy18z,sy1bs,sy1ez,sy1df,sy1e0,sy1ai,sy19t,sy195,sy1dx,sy1dt,sy1dp,sy1dd,sy1ef,sy1f4,sy1g8,sy1g6,sy1am,sydh,syf8,syn7,sy1be,sy1bp,sy1bo,sy1b7,sy1bh,sy1bl,sy1ba,sy1bf,sy1bm,sy1bn,sy198,sy1al,sy1gd,sy1gl,sy1gj,sy1e4,sy1ed,sy1e9,sy1eb,sy1cd,sy1cr,sy1bt,sy1do,sy1f0,sy1dg,sy1ei,sy1dz,sy1du,sy1de,sy1el,sy1dh,sy1fn,sy1fy,sy1fx,sy1g7,sy1f9,sy1fh,sy1fg,sy1fq,sy1f7,sy1ff,sy1g2,sy1g9,sy1g3,sy1fz,sy19e,sy1b2,sy1ge,sy1go,sy1gn,sy1ad,sy1eq,sy1ae,sy1e3,ld,sy172,em32,em33,em34,em35,em36,em37,em38,em39,em3a,em3b,em3c,em3d,em3e,em3f,em3g,em3h,em3i,em3j,em3k,em3l,em3m,em3n,em3o,em3p,em2x,em2y,em2z,em30,sy18r,em2u,em2w,em4a,em4b,em4c,em4d,em4e,em4f,em4g,em4h,em4i,em4j,em4k,em50,em4l,sy1fs,em4m,em4n,em4o,em4p,em4q,em4r,em4s,em4t,em4u,em4v,em4w,em4x,em4y,em4z,sy1f3,sy1f5,sy1f6,sy1fr,sy1g5,sy1g4,sy9o,syfi,sy19d,sy19f,sy19o,sy1au,sy1gm,sy1gq,sy18b,sy19g,sy1gt,sy1et,sy1es,sypa,sy16i,sy18n,sy1ar,sy193,cv,sy1gb,sy1gr,sy1gu,sy1ey,em3q,em3r,em3s,em3t,sy1b9,sy1bq,sy1gc,em3u,spcm,spc:2413
c7g @ m=o2ajQe,sy1tx,sy1tr,sy1ty,sy1v6,sy1v9,sy1vg,sy1vn,NVcOs,sy1tt,sy1tw,sy1tu,sy1vb,Av2a7c,sy1tz,sy1u2,PaBahd,dFpypf,sy1rc,sy1sk,sy1tj,sy1ss,sy1ro,sy1th,sy1sl,sy1tm,sy1tq,sy1r2,sy1qc,sy1rk,sy1rm,sy1t2,sy1td,sy1tc,sy1ti,sy1tf,sy1tg,sy1tl,sy1tp,sy1tn,igbF5,MigGy,Sz7W7c,sy1v7,sy1ri,sy1ud,sy1ee,sy1qz,sy1va,sy1v8,sy1vf,sy1vd,sy1ve,PZhDZb,sy1r3,sy1r1,sy1rf,sy1u4,rMQdJc,J03Die,sy1sy,sy1u0,sy1rh,sy1u1,sy1u3,CTcde,sy16d,sy16e,sy19k,sy1a4,sy1a5,sy163,sy169,sy160,sy19l,sy19i,sy19j,sy19m,sy18x,sy18y,sy19w,sy19x,sy1a3,sydp,sy15w,sy16f,sy16a,sy16h,sy162,sy183,sy1b4,sy18u,sy19n,sy19y,sy1a2,sy190,sy1aj,sy161,sy16g,sy16r,sy196,sy1cn,sy1di,sy1dk,sy199,sy19a,sy19b,sy1bd,sy1b6,sy181,sy185,sydf,sy1bc,sy1bb,sy1ab,sy19h,sy1a1,sy1br,sy191,sy18t,sy1dw,sy1dv,sy1ds,syfj,sy1dr,sy1dq,sy16q,sy16t,sy1da,sydj,syoe,sy1an,sy194,sy1ao,sy1b8,sy1b3,sy182,sy184,sy1bi,sy1bj,sy1bk,sy1bg,sy1b5,sy1gk,sy1ec,sy19p,sy1ct,sy1cs,sy1a6,sy1aa,sy1ap,sy1b1,sy1ag,sy18z,sy1bs,sy1ez,sy1df,sy1e0,sy1ai,sy19t,sy195,sy1dx,sy1dt,sy1dp,sy1dd,sy1ef,sy1f4,sy1g8,sy1g6,sy1am,sydh,syf8,syn7,sy1be,sy1bp,sy1bo,sy1b7,sy1bh,sy1bl,sy1ba,sy1bf,sy1bm,sy1bn,sy198,sy1al,sy1gd,sy1gl,sy1gj,sy1e4,sy1ed,sy1e9,sy1eb,sy1cd,sy1cr,sy1bt,sy1do,sy1f0,sy1dg,sy1ei,sy1dz,sy1du,sy1de,sy1el,sy1dh,sy1fn,sy1fy,sy1fx,sy1g7,sy1f9,sy1fh,sy1fg,sy1fq,sy1f7,sy1ff,sy1g2,sy1g9,sy1g3,sy1fz,sy19e,sy1b2,sy1ge,sy1go,sy1gn,sy1ad,sy1eq,sy1ae,sy1e3,ld,sy172,em32,em33,em34,em35,em36,em37,em38,em39,em3a,em3b,em3c,em3d,em3e,em3f,em3g,em3h,em3i,em3j,em3k,em3l,em3m,em3n,em3o,em3p,em2x,em2y,em2z,em30,sy18r,em2u,em2w,em4a,em4b,em4c,em4d,em4e,em4f,em4g,em4h,em4i,em4j,em4k,em50,em4l,sy1fs,em4m,em4n,em4o,em4p,em4q,em4r,em4s,em4t,em4u,em4v,em4w,em4x,em4y,em4z,sy1f3,sy1f5,sy1f6,sy1fr,sy1g5,sy1g4,sy9o,syfi,sy19d,sy19f,sy19o,sy1au,sy1gm,sy1gq,sy18b,sy19g,sy1gt,sy1et,sy1es,sypa,sy16i,sy18n,sy1ar,sy193,cv,sy1gb,sy1gr,sy1gu,sy1ey,em3q,em3r,em3s,em3t,sy1b9,sy1bq,sy1gc,em3u,spcm,spc:2415
t.Nf @ m=o2ajQe,sy1tx,sy1tr,sy1ty,sy1v6,sy1v9,sy1vg,sy1vn,NVcOs,sy1tt,sy1tw,sy1tu,sy1vb,Av2a7c,sy1tz,sy1u2,PaBahd,dFpypf,sy1rc,sy1sk,sy1tj,sy1ss,sy1ro,sy1th,sy1sl,sy1tm,sy1tq,sy1r2,sy1qc,sy1rk,sy1rm,sy1t2,sy1td,sy1tc,sy1ti,sy1tf,sy1tg,sy1tl,sy1tp,sy1tn,igbF5,MigGy,Sz7W7c,sy1v7,sy1ri,sy1ud,sy1ee,sy1qz,sy1va,sy1v8,sy1vf,sy1vd,sy1ve,PZhDZb,sy1r3,sy1r1,sy1rf,sy1u4,rMQdJc,J03Die,sy1sy,sy1u0,sy1rh,sy1u1,sy1u3,CTcde,sy16d,sy16e,sy19k,sy1a4,sy1a5,sy163,sy169,sy160,sy19l,sy19i,sy19j,sy19m,sy18x,sy18y,sy19w,sy19x,sy1a3,sydp,sy15w,sy16f,sy16a,sy16h,sy162,sy183,sy1b4,sy18u,sy19n,sy19y,sy1a2,sy190,sy1aj,sy161,sy16g,sy16r,sy196,sy1cn,sy1di,sy1dk,sy199,sy19a,sy19b,sy1bd,sy1b6,sy181,sy185,sydf,sy1bc,sy1bb,sy1ab,sy19h,sy1a1,sy1br,sy191,sy18t,sy1dw,sy1dv,sy1ds,syfj,sy1dr,sy1dq,sy16q,sy16t,sy1da,sydj,syoe,sy1an,sy194,sy1ao,sy1b8,sy1b3,sy182,sy184,sy1bi,sy1bj,sy1bk,sy1bg,sy1b5,sy1gk,sy1ec,sy19p,sy1ct,sy1cs,sy1a6,sy1aa,sy1ap,sy1b1,sy1ag,sy18z,sy1bs,sy1ez,sy1df,sy1e0,sy1ai,sy19t,sy195,sy1dx,sy1dt,sy1dp,sy1dd,sy1ef,sy1f4,sy1g8,sy1g6,sy1am,sydh,syf8,syn7,sy1be,sy1bp,sy1bo,sy1b7,sy1bh,sy1bl,sy1ba,sy1bf,sy1bm,sy1bn,sy198,sy1al,sy1gd,sy1gl,sy1gj,sy1e4,sy1ed,sy1e9,sy1eb,sy1cd,sy1cr,sy1bt,sy1do,sy1f0,sy1dg,sy1ei,sy1dz,sy1du,sy1de,sy1el,sy1dh,sy1fn,sy1fy,sy1fx,sy1g7,sy1f9,sy1fh,sy1fg,sy1fq,sy1f7,sy1ff,sy1g2,sy1g9,sy1g3,sy1fz,sy19e,sy1b2,sy1ge,sy1go,sy1gn,sy1ad,sy1eq,sy1ae,sy1e3,ld,sy172,em32,em33,em34,em35,em36,em37,em38,em39,em3a,em3b,em3c,em3d,em3e,em3f,em3g,em3h,em3i,em3j,em3k,em3l,em3m,em3n,em3o,em3p,em2x,em2y,em2z,em30,sy18r,em2u,em2w,em4a,em4b,em4c,em4d,em4e,em4f,em4g,em4h,em4i,em4j,em4k,em50,em4l,sy1fs,em4m,em4n,em4o,em4p,em4q,em4r,em4s,em4t,em4u,em4v,em4w,em4x,em4y,em4z,sy1f3,sy1f5,sy1f6,sy1fr,sy1g5,sy1g4,sy9o,syfi,sy19d,sy19f,sy19o,sy1au,sy1gm,sy1gq,sy18b,sy19g,sy1gt,sy1et,sy1es,sypa,sy16i,sy18n,sy1ar,sy193,cv,sy1gb,sy1gr,sy1gu,sy1ey,em3q,em3r,em3s,em3t,sy1b9,sy1bq,sy1gc,em3u,spcm,spc:2924
Tah.Nf @ m=o2ajQe,sy1tx,sy1tr,sy1ty,sy1v6,sy1v9,sy1vg,sy1vn,NVcOs,sy1tt,sy1tw,sy1tu,sy1vb,Av2a7c,sy1tz,sy1u2,PaBahd,dFpypf,sy1rc,sy1sk,sy1tj,sy1ss,sy1ro,sy1th,sy1sl,sy1tm,sy1tq,sy1r2,sy1qc,sy1rk,sy1rm,sy1t2,sy1td,sy1tc,sy1ti,sy1tf,sy1tg,sy1tl,sy1tp,sy1tn,igbF5,MigGy,Sz7W7c,sy1v7,sy1ri,sy1ud,sy1ee,sy1qz,sy1va,sy1v8,sy1vf,sy1vd,sy1ve,PZhDZb,sy1r3,sy1r1,sy1rf,sy1u4,rMQdJc,J03Die,sy1sy,sy1u0,sy1rh,sy1u1,sy1u3,CTcde,sy16d,sy16e,sy19k,sy1a4,sy1a5,sy163,sy169,sy160,sy19l,sy19i,sy19j,sy19m,sy18x,sy18y,sy19w,sy19x,sy1a3,sydp,sy15w,sy16f,sy16a,sy16h,sy162,sy183,sy1b4,sy18u,sy19n,sy19y,sy1a2,sy190,sy1aj,sy161,sy16g,sy16r,sy196,sy1cn,sy1di,sy1dk,sy199,sy19a,sy19b,sy1bd,sy1b6,sy181,sy185,sydf,sy1bc,sy1bb,sy1ab,sy19h,sy1a1,sy1br,sy191,sy18t,sy1dw,sy1dv,sy1ds,syfj,sy1dr,sy1dq,sy16q,sy16t,sy1da,sydj,syoe,sy1an,sy194,sy1ao,sy1b8,sy1b3,sy182,sy184,sy1bi,sy1bj,sy1bk,sy1bg,sy1b5,sy1gk,sy1ec,sy19p,sy1ct,sy1cs,sy1a6,sy1aa,sy1ap,sy1b1,sy1ag,sy18z,sy1bs,sy1ez,sy1df,sy1e0,sy1ai,sy19t,sy195,sy1dx,sy1dt,sy1dp,sy1dd,sy1ef,sy1f4,sy1g8,sy1g6,sy1am,sydh,syf8,syn7,sy1be,sy1bp,sy1bo,sy1b7,sy1bh,sy1bl,sy1ba,sy1bf,sy1bm,sy1bn,sy198,sy1al,sy1gd,sy1gl,sy1gj,sy1e4,sy1ed,sy1e9,sy1eb,sy1cd,sy1cr,sy1bt,sy1do,sy1f0,sy1dg,sy1ei,sy1dz,sy1du,sy1de,sy1el,sy1dh,sy1fn,sy1fy,sy1fx,sy1g7,sy1f9,sy1fh,sy1fg,sy1fq,sy1f7,sy1ff,sy1g2,sy1g9,sy1g3,sy1fz,sy19e,sy1b2,sy1ge,sy1go,sy1gn,sy1ad,sy1eq,sy1ae,sy1e3,ld,sy172,em32,em33,em34,em35,em36,em37,em38,em39,em3a,em3b,em3c,em3d,em3e,em3f,em3g,em3h,em3i,em3j,em3k,em3l,em3m,em3n,em3o,em3p,em2x,em2y,em2z,em30,sy18r,em2u,em2w,em4a,em4b,em4c,em4d,em4e,em4f,em4g,em4h,em4i,em4j,em4k,em50,em4l,sy1fs,em4m,em4n,em4o,em4p,em4q,em4r,em4s,em4t,em4u,em4v,em4w,em4x,em4y,em4z,sy1f3,sy1f5,sy1f6,sy1fr,sy1g5,sy1g4,sy9o,syfi,sy19d,sy19f,sy19o,sy1au,sy1gm,sy1gq,sy18b,sy19g,sy1gt,sy1et,sy1es,sypa,sy16i,sy18n,sy1ar,sy193,cv,sy1gb,sy1gr,sy1gu,sy1ey,em3q,em3r,em3s,em3t,sy1b9,sy1bq,sy1gc,em3u,spcm,spc:3199
t.Nf @ m=o2ajQe,sy1tx,sy1tr,sy1ty,sy1v6,sy1v9,sy1vg,sy1vn,NVcOs,sy1tt,sy1tw,sy1tu,sy1vb,Av2a7c,sy1tz,sy1u2,PaBahd,dFpypf,sy1rc,sy1sk,sy1tj,sy1ss,sy1ro,sy1th,sy1sl,sy1tm,sy1tq,sy1r2,sy1qc,sy1rk,sy1rm,sy1t2,sy1td,sy1tc,sy1ti,sy1tf,sy1tg,sy1tl,sy1tp,sy1tn,igbF5,MigGy,Sz7W7c,sy1v7,sy1ri,sy1ud,sy1ee,sy1qz,sy1va,sy1v8,sy1vf,sy1vd,sy1ve,PZhDZb,sy1r3,sy1r1,sy1rf,sy1u4,rMQdJc,J03Die,sy1sy,sy1u0,sy1rh,sy1u1,sy1u3,CTcde,sy16d,sy16e,sy19k,sy1a4,sy1a5,sy163,sy169,sy160,sy19l,sy19i,sy19j,sy19m,sy18x,sy18y,sy19w,sy19x,sy1a3,sydp,sy15w,sy16f,sy16a,sy16h,sy162,sy183,sy1b4,sy18u,sy19n,sy19y,sy1a2,sy190,sy1aj,sy161,sy16g,sy16r,sy196,sy1cn,sy1di,sy1dk,sy199,sy19a,sy19b,sy1bd,sy1b6,sy181,sy185,sydf,sy1bc,sy1bb,sy1ab,sy19h,sy1a1,sy1br,sy191,sy18t,sy1dw,sy1dv,sy1ds,syfj,sy1dr,sy1dq,sy16q,sy16t,sy1da,sydj,syoe,sy1an,sy194,sy1ao,sy1b8,sy1b3,sy182,sy184,sy1bi,sy1bj,sy1bk,sy1bg,sy1b5,sy1gk,sy1ec,sy19p,sy1ct,sy1cs,sy1a6,sy1aa,sy1ap,sy1b1,sy1ag,sy18z,sy1bs,sy1ez,sy1df,sy1e0,sy1ai,sy19t,sy195,sy1dx,sy1dt,sy1dp,sy1dd,sy1ef,sy1f4,sy1g8,sy1g6,sy1am,sydh,syf8,syn7,sy1be,sy1bp,sy1bo,sy1b7,sy1bh,sy1bl,sy1ba,sy1bf,sy1bm,sy1bn,sy198,sy1al,sy1gd,sy1gl,sy1gj,sy1e4,sy1ed,sy1e9,sy1eb,sy1cd,sy1cr,sy1bt,sy1do,sy1f0,sy1dg,sy1ei,sy1dz,sy1du,sy1de,sy1el,sy1dh,sy1fn,sy1fy,sy1fx,sy1g7,sy1f9,sy1fh,sy1fg,sy1fq,sy1f7,sy1ff,sy1g2,sy1g9,sy1g3,sy1fz,sy19e,sy1b2,sy1ge,sy1go,sy1gn,sy1ad,sy1eq,sy1ae,sy1e3,ld,sy172,em32,em33,em34,em35,em36,em37,em38,em39,em3a,em3b,em3c,em3d,em3e,em3f,em3g,em3h,em3i,em3j,em3k,em3l,em3m,em3n,em3o,em3p,em2x,em2y,em2z,em30,sy18r,em2u,em2w,em4a,em4b,em4c,em4d,em4e,em4f,em4g,em4h,em4i,em4j,em4k,em50,em4l,sy1fs,em4m,em4n,em4o,em4p,em4q,em4r,em4s,em4t,em4u,em4v,em4w,em4x,em4y,em4z,sy1f3,sy1f5,sy1f6,sy1fr,sy1g5,sy1g4,sy9o,syfi,sy19d,sy19f,sy19o,sy1au,sy1gm,sy1gq,sy18b,sy19g,sy1gt,sy1et,sy1es,sypa,sy16i,sy18n,sy1ar,sy193,cv,sy1gb,sy1gr,sy1gu,sy1ey,em3q,em3r,em3s,em3t,sy1b9,sy1bq,sy1gc,em3u,spcm,spc:3233
Xbh.Nf @ m=o2ajQe,sy1tx,sy1tr,sy1ty,sy1v6,sy1v9,sy1vg,sy1vn,NVcOs,sy1tt,sy1tw,sy1tu,sy1vb,Av2a7c,sy1tz,sy1u2,PaBahd,dFpypf,sy1rc,sy1sk,sy1tj,sy1ss,sy1ro,sy1th,sy1sl,sy1tm,sy1tq,sy1r2,sy1qc,sy1rk,sy1rm,sy1t2,sy1td,sy1tc,sy1ti,sy1tf,sy1tg,sy1tl,sy1tp,sy1tn,igbF5,MigGy,Sz7W7c,sy1v7,sy1ri,sy1ud,sy1ee,sy1qz,sy1va,sy1v8,sy1vf,sy1vd,sy1ve,PZhDZb,sy1r3,sy1r1,sy1rf,sy1u4,rMQdJc,J03Die,sy1sy,sy1u0,sy1rh,sy1u1,sy1u3,CTcde,sy16d,sy16e,sy19k,sy1a4,sy1a5,sy163,sy169,sy160,sy19l,sy19i,sy19j,sy19m,sy18x,sy18y,sy19w,sy19x,sy1a3,sydp,sy15w,sy16f,sy16a,sy16h,sy162,sy183,sy1b4,sy18u,sy19n,sy19y,sy1a2,sy190,sy1aj,sy161,sy16g,sy16r,sy196,sy1cn,sy1di,sy1dk,sy199,sy19a,sy19b,sy1bd,sy1b6,sy181,sy185,sydf,sy1bc,sy1bb,sy1ab,sy19h,sy1a1,sy1br,sy191,sy18t,sy1dw,sy1dv,sy1ds,syfj,sy1dr,sy1dq,sy16q,sy16t,sy1da,sydj,syoe,sy1an,sy194,sy1ao,sy1b8,sy1b3,sy182,sy184,sy1bi,sy1bj,sy1bk,sy1bg,sy1b5,sy1gk,sy1ec,sy19p,sy1ct,sy1cs,sy1a6,sy1aa,sy1ap,sy1b1,sy1ag,sy18z,sy1bs,sy1ez,sy1df,sy1e0,sy1ai,sy19t,sy195,sy1dx,sy1dt,sy1dp,sy1dd,sy1ef,sy1f4,sy1g8,sy1g6,sy1am,sydh,syf8,syn7,sy1be,sy1bp,sy1bo,sy1b7,sy1bh,sy1bl,sy1ba,sy1bf,sy1bm,sy1bn,sy198,sy1al,sy1gd,sy1gl,sy1gj,sy1e4,sy1ed,sy1e9,sy1eb,sy1cd,sy1cr,sy1bt,sy1do,sy1f0,sy1dg,sy1ei,sy1dz,sy1du,sy1de,sy1el,sy1dh,sy1fn,sy1fy,sy1fx,sy1g7,sy1f9,sy1fh,sy1fg,sy1fq,sy1f7,sy1ff,sy1g2,sy1g9,sy1g3,sy1fz,sy19e,sy1b2,sy1ge,sy1go,sy1gn,sy1ad,sy1eq,sy1ae,sy1e3,ld,sy172,em32,em33,em34,em35,em36,em37,em38,em39,em3a,em3b,em3c,em3d,em3e,em3f,em3g,em3h,em3i,em3j,em3k,em3l,em3m,em3n,em3o,em3p,em2x,em2y,em2z,em30,sy18r,em2u,em2w,em4a,em4b,em4c,em4d,em4e,em4f,em4g,em4h,em4i,em4j,em4k,em50,em4l,sy1fs,em4m,em4n,em4o,em4p,em4q,em4r,em4s,em4t,em4u,em4v,em4w,em4x,em4y,em4z,sy1f3,sy1f5,sy1f6,sy1fr,sy1g5,sy1g4,sy9o,syfi,sy19d,sy19f,sy19o,sy1au,sy1gm,sy1gq,sy18b,sy19g,sy1gt,sy1et,sy1es,sypa,sy16i,sy18n,sy1ar,sy193,cv,sy1gb,sy1gr,sy1gu,sy1ey,em3q,em3r,em3s,em3t,sy1b9,sy1bq,sy1gc,em3u,spcm,spc:3245
zY.rl @ m=o2ajQe,sy1tx,sy1tr,sy1ty,sy1v6,sy1v9,sy1vg,sy1vn,NVcOs,sy1tt,sy1tw,sy1tu,sy1vb,Av2a7c,sy1tz,sy1u2,PaBahd,dFpypf,sy1rc,sy1sk,sy1tj,sy1ss,sy1ro,sy1th,sy1sl,sy1tm,sy1tq,sy1r2,sy1qc,sy1rk,sy1rm,sy1t2,sy1td,sy1tc,sy1ti,sy1tf,sy1tg,sy1tl,sy1tp,sy1tn,igbF5,MigGy,Sz7W7c,sy1v7,sy1ri,sy1ud,sy1ee,sy1qz,sy1va,sy1v8,sy1vf,sy1vd,sy1ve,PZhDZb,sy1r3,sy1r1,sy1rf,sy1u4,rMQdJc,J03Die,sy1sy,sy1u0,sy1rh,sy1u1,sy1u3,CTcde,sy16d,sy16e,sy19k,sy1a4,sy1a5,sy163,sy169,sy160,sy19l,sy19i,sy19j,sy19m,sy18x,sy18y,sy19w,sy19x,sy1a3,sydp,sy15w,sy16f,sy16a,sy16h,sy162,sy183,sy1b4,sy18u,sy19n,sy19y,sy1a2,sy190,sy1aj,sy161,sy16g,sy16r,sy196,sy1cn,sy1di,sy1dk,sy199,sy19a,sy19b,sy1bd,sy1b6,sy181,sy185,sydf,sy1bc,sy1bb,sy1ab,sy19h,sy1a1,sy1br,sy191,sy18t,sy1dw,sy1dv,sy1ds,syfj,sy1dr,sy1dq,sy16q,sy16t,sy1da,sydj,syoe,sy1an,sy194,sy1ao,sy1b8,sy1b3,sy182,sy184,sy1bi,sy1bj,sy1bk,sy1bg,sy1b5,sy1gk,sy1ec,sy19p,sy1ct,sy1cs,sy1a6,sy1aa,sy1ap,sy1b1,sy1ag,sy18z,sy1bs,sy1ez,sy1df,sy1e0,sy1ai,sy19t,sy195,sy1dx,sy1dt,sy1dp,sy1dd,sy1ef,sy1f4,sy1g8,sy1g6,sy1am,sydh,syf8,syn7,sy1be,sy1bp,sy1bo,sy1b7,sy1bh,sy1bl,sy1ba,sy1bf,sy1bm,sy1bn,sy198,sy1al,sy1gd,sy1gl,sy1gj,sy1e4,sy1ed,sy1e9,sy1eb,sy1cd,sy1cr,sy1bt,sy1do,sy1f0,sy1dg,sy1ei,sy1dz,sy1du,sy1de,sy1el,sy1dh,sy1fn,sy1fy,sy1fx,sy1g7,sy1f9,sy1fh,sy1fg,sy1fq,sy1f7,sy1ff,sy1g2,sy1g9,sy1g3,sy1fz,sy19e,sy1b2,sy1ge,sy1go,sy1gn,sy1ad,sy1eq,sy1ae,sy1e3,ld,sy172,em32,em33,em34,em35,em36,em37,em38,em39,em3a,em3b,em3c,em3d,em3e,em3f,em3g,em3h,em3i,em3j,em3k,em3l,em3m,em3n,em3o,em3p,em2x,em2y,em2z,em30,sy18r,em2u,em2w,em4a,em4b,em4c,em4d,em4e,em4f,em4g,em4h,em4i,em4j,em4k,em50,em4l,sy1fs,em4m,em4n,em4o,em4p,em4q,em4r,em4s,em4t,em4u,em4v,em4w,em4x,em4y,em4z,sy1f3,sy1f5,sy1f6,sy1fr,sy1g5,sy1g4,sy9o,syfi,sy19d,sy19f,sy19o,sy1au,sy1gm,sy1gq,sy18b,sy19g,sy1gt,sy1et,sy1es,sypa,sy16i,sy18n,sy1ar,sy193,cv,sy1gb,sy1gr,sy1gu,sy1ey,em3q,em3r,em3s,em3t,sy1b9,sy1bq,sy1gc,em3u,spcm,spc:3317
t.aud @ m=o2ajQe,sy1tx,sy1tr,sy1ty,sy1v6,sy1v9,sy1vg,sy1vn,NVcOs,sy1tt,sy1tw,sy1tu,sy1vb,Av2a7c,sy1tz,sy1u2,PaBahd,dFpypf,sy1rc,sy1sk,sy1tj,sy1ss,sy1ro,sy1th,sy1sl,sy1tm,sy1tq,sy1r2,sy1qc,sy1rk,sy1rm,sy1t2,sy1td,sy1tc,sy1ti,sy1tf,sy1tg,sy1tl,sy1tp,sy1tn,igbF5,MigGy,Sz7W7c,sy1v7,sy1ri,sy1ud,sy1ee,sy1qz,sy1va,sy1v8,sy1vf,sy1vd,sy1ve,PZhDZb,sy1r3,sy1r1,sy1rf,sy1u4,rMQdJc,J03Die,sy1sy,sy1u0,sy1rh,sy1u1,sy1u3,CTcde,sy16d,sy16e,sy19k,sy1a4,sy1a5,sy163,sy169,sy160,sy19l,sy19i,sy19j,sy19m,sy18x,sy18y,sy19w,sy19x,sy1a3,sydp,sy15w,sy16f,sy16a,sy16h,sy162,sy183,sy1b4,sy18u,sy19n,sy19y,sy1a2,sy190,sy1aj,sy161,sy16g,sy16r,sy196,sy1cn,sy1di,sy1dk,sy199,sy19a,sy19b,sy1bd,sy1b6,sy181,sy185,sydf,sy1bc,sy1bb,sy1ab,sy19h,sy1a1,sy1br,sy191,sy18t,sy1dw,sy1dv,sy1ds,syfj,sy1dr,sy1dq,sy16q,sy16t,sy1da,sydj,syoe,sy1an,sy194,sy1ao,sy1b8,sy1b3,sy182,sy184,sy1bi,sy1bj,sy1bk,sy1bg,sy1b5,sy1gk,sy1ec,sy19p,sy1ct,sy1cs,sy1a6,sy1aa,sy1ap,sy1b1,sy1ag,sy18z,sy1bs,sy1ez,sy1df,sy1e0,sy1ai,sy19t,sy195,sy1dx,sy1dt,sy1dp,sy1dd,sy1ef,sy1f4,sy1g8,sy1g6,sy1am,sydh,syf8,syn7,sy1be,sy1bp,sy1bo,sy1b7,sy1bh,sy1bl,sy1ba,sy1bf,sy1bm,sy1bn,sy198,sy1al,sy1gd,sy1gl,sy1gj,sy1e4,sy1ed,sy1e9,sy1eb,sy1cd,sy1cr,sy1bt,sy1do,sy1f0,sy1dg,sy1ei,sy1dz,sy1du,sy1de,sy1el,sy1dh,sy1fn,sy1fy,sy1fx,sy1g7,sy1f9,sy1fh,sy1fg,sy1fq,sy1f7,sy1ff,sy1g2,sy1g9,sy1g3,sy1fz,sy19e,sy1b2,sy1ge,sy1go,sy1gn,sy1ad,sy1eq,sy1ae,sy1e3,ld,sy172,em32,em33,em34,em35,em36,em37,em38,em39,em3a,em3b,em3c,em3d,em3e,em3f,em3g,em3h,em3i,em3j,em3k,em3l,em3m,em3n,em3o,em3p,em2x,em2y,em2z,em30,sy18r,em2u,em2w,em4a,em4b,em4c,em4d,em4e,em4f,em4g,em4h,em4i,em4j,em4k,em50,em4l,sy1fs,em4m,em4n,em4o,em4p,em4q,em4r,em4s,em4t,em4u,em4v,em4w,em4x,em4y,em4z,sy1f3,sy1f5,sy1f6,sy1fr,sy1g5,sy1g4,sy9o,syfi,sy19d,sy19f,sy19o,sy1au,sy1gm,sy1gq,sy18b,sy19g,sy1gt,sy1et,sy1es,sypa,sy16i,sy18n,sy1ar,sy193,cv,sy1gb,sy1gr,sy1gu,sy1ey,em3q,em3r,em3s,em3t,sy1b9,sy1bq,sy1gc,em3u,spcm,spc:3306
GLa @ m=sps,spl,spit,m_i,spt,t,it:259
CLa @ m=sps,spl,spit,m_i,spt,t,it:260
d @ m=sps,spl,spit,m_i,spt,t,it:228
ALa.c @ m=sps,spl,spit,m_i,spt,t,it:256

**Comment by srirambv** [comment]
Does this happen only with pdf or other document types as well?

**Comment by scottf007** [comment]
tested pdf, word doc, excel, png, jpg - all behaved the same - do not download. 
also - when you click on it and preview, there is a download button - this does not work. When you open the preview in a new tab and try and download this does not work either.

**Comment by scottf007** [comment]
any word on this? I have been using this browser full time for about 3 weeks now and love it. But this is killing me :) 

Super good work, you should tell more people about this chrome version, way better than the other one, which I used for the last year.

**Comment by scottf007** [comment]
this now works - i suggest close ticket.
