### ISSUE TITLE
[Desktop] Manual test run for Tor 1.0.12 component update on Linux 

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#10680]
## Tor Client Updater 

- [ ] For development go-update-server. Run brave-browser with `--user-data-dir=/tmp/component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [ ] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [ ] Open `New Private Window with Tor` and confirm that it starts without any errors.
- [ ] Navigate to `check.torproject.org` and verify that tor is working successfully.
- [ ] Navigate to `brave.com` and `http://3g2upl4pq6kufc4m.onion/` to check if the sites work correctly.

**Comment by srirambv** [comment]
Verification passed on 


Brave | 1.11.94 Chromium: 84.0.4147.85 (Official Build) (64-bit)
-- | --
Revision | e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{# 837}
OS | Linux

- Verified updating from `development go-update-server`, component is updated to `1.0.12` for `Tor 0.3.5.11` module
![image](https://user-images.githubusercontent.com/17010094/87385303-a3f89e00-c595-11ea-9507-afbe9467d457.png)
- Verified hard reload updates the IP address 
- Verified `brave.com` is loaded on Tor window
![image](https://user-images.githubusercontent.com/17010094/87385364-c5f22080-c595-11ea-9437-d4c77c9a3d72.png)
- Verified `http://3g2upl4pq6kufc4m.onion/` is loaded on Tor window
![image](https://user-images.githubusercontent.com/17010094/87385591-5a5c8300-c596-11ea-97e7-fcb02fdf0b27.png)
