### ISSUE TITLE
[Desktop] Handle each steps error of NTP SI/SR packaging/uploading pipeline

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#10689]
For example, NTP SI Jenkins job has three steps like below.
`npm run generate-ntp-sponsored-images`
`npm run package-ntp-sponsored-images`
`npm run upload-ntp-sponsored-images-components`
If any step has failure, next step should not be run and job should be terminated immediately.

**Comment by simonhong** [comment]
@linhkikuchi can we do this in the pipeline?

**Comment by linhkikuchi** [comment]
@simonhong the pipeline has 
```
set -uo pipefail
set -e
```
so any step from the script fails, the job will fail
tested here
https://ci.brave.com/view/all-extensions/job/brave-core-ext-ntp-sponsored-publish-dev/19/
https://ci.brave.com/view/all-extensions/job/brave-core-ext-ntp-sponsored-publish-dev/20/

**Comment by simonhong** [comment]
@linhkikuchi Thanks for checking and sorry. 
I think crx-packager does not handle some errors gracefully - https://ci.brave.com/view/all-extensions/job/brave-core-ext-ntp-sponsored-publish/64/console I'll fix!
