### ISSUE TITLE
[Android] brave reward : Ad's Not Receiving

### ISSUE THREAD

**Issue by Oshekher** [brave/brave-browser#10684]
## Issue happens on 
   - Current Play Store version? , 20.8.12
   - Beta build? , NO

## Device details
   - Install type : ARM64
   - Device : PHONE
   - Android version: 10
   
## Brave version: 1.10.99

**Comment by cjwijtmans** [comment]
I have had some days where i havent recieved ads, sometimes a week. But i believe it has to do with how many ad pushes the advertisers are buying and how many people use brave plus how the ads are being distributed. I could be wrong though. Also where did my spell checker go.

**Comment by tmancey** [comment]
@Oshekher Could you please let me know your locale? Thanks

**Comment by tmancey** [comment]
@Oshekher Can you please let me know if you are now seeing Ads, if not can you please email me direct so we can investigate further

**Comment by Oshekher** [comment]
Yes now receiving

**Comment by tmancey** [comment]
@Oshekher Great news
