### ISSUE TITLE
[Desktop] Multiple problems

### ISSUE THREAD

**Issue by HarnischtheTrue** [brave/brave-browser#10697]
## Description:
1 Brave close itself on opening, need to open many new windows to remain open.
2 Brave do not stop ads on youtube anymore
3 Sometimes Brave forget my accounts (i have to unistall and reinstall the browser to solve)

## Brave version (brave://version info)
Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

As stated before i already tried to unistall and reinstall but the problems persist, I have now to try to open the browser dozen of time to have an active tab, and the adblock not working with the sistematically need to reistall the browser for my accounts, begin to be a little to much and before changing my browser, i would like to know if there is something i must fix or is a problem with this version.

thanks for your patience

**Comment by rebron** [comment]
Hi @HarnischtheTrue Can you update to 1.13.82 and let us know if you're still experiencing the issues you mentioned by going here: brave://settings/help 

Sorry to hear you're having these multiple issues. We normally will file a separate issue for each problem and invite you to go to community.brave.com when you're having multiple issues like this so we can form more specific and actionable issues here. cc: @Brave-Matt
