### ISSUE TITLE
Please add webpage dark mode

### ISSUE THREAD

**Issue by razercrypto** [brave/brave-browser#10692]
Please add web page dark mode like opera browser, dark mode will reduce eye stress.
![Screenshot_20200710-210651_1_1](https://user-images.githubusercontent.com/68118845/87172405-d2564f00-c2f1-11ea-8379-e040ca6bcd6d.png)

**Comment by newuser-web** [comment]
#6380

**Comment by bsclifton** [comment]
Thanks for the assist, @newuser-web 😄 Closing as duplicate of https://github.com/brave/brave-browser/issues/6380
