### ISSUE TITLE
[Android] Decrease size of Shields on tablets

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10690]
## Description 
New Shields implementation on tablet seems to have a very big UI. This needs to be scaled down

## Steps to reproduce 

   1. Install nightly on tablet 
   2. Visit a page and open shields

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/87162762-4b3bb380-c2be-11ea-8ac8-482848c6e0ee.png)

## Expected result
Relatively smaller shields

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NO
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 9
   
## Brave version
1.13.6

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by anthonypkeane** [comment]
Closed as dup of #10993
