### ISSUE TITLE
[Desktop] Huge ads priority in logs when priority is set to zero

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10694]
Found when testing https://github.com/brave/brave-browser/issues/5232

## Steps to Reproduce

1. Load staging catalog [ads_priority_0.txt](https://github.com/brave/brave-browser/files/4904013/ads_priority_0.txt)
1. Try to show the ad

## Actual result:

The log shows
```
[6614:6614:0710/202200.229131:VERBOSE2:ads_impl.cc(992)] 0 eligible ads with a priority of 1264684032
```

## Expected result:
TBD

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @tmancey

**Comment by tmancey** [comment]
@btlechowski Valid values are 1 to 10, thanks

**Comment by btlechowski** [comment]
Thanks @tmancey. Closing as it is fixed in nightly.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR in description, used this catalog - [zero-priority-catalog.txt](https://github.com/brave/brave-browser/files/5119452/zero-priority-catalog.txt)

* Confirmed I did not see `0 eligible ads with a priority of 1264684032` in the logs, instead I saw `[1797:775:0824/135413.425645:VERBOSE1:ads_impl.cc(1047)] Ad notification not shown: No eligible ads found` which is accurate based on the catalog used.
