### ISSUE TITLE
Estimated ads decreasing 

### ISSUE THREAD

**Issue by Mr-grey-hat** [brave/brave-browser#10708]
Brave rewards are automatically decreasing. Had 5 BAT in my brave wallet. fired laptop it itself got decreased to 4.3 BAT. Again got some Ads and clicked them, it goes to 4.7 BAT after that I shut down the laptop. Again in evening I opened and seeing that Brave rewards are again stuck to 4.3 BAT. Please help me out.

**Comment by bsclifton** [comment]
@NejcZdovc is this due to balance being a grant versus user-provided BAT? (guessing that is why it was tagged as `ads`)

**Comment by NejcZdovc** [comment]
@bsclifton this is about estimates for ads not about claimed grants afaik

**Comment by Mr-grey-hat** [comment]
Even though I have clicked multiple Ads notifications, momentarily it increases but after some time it gets stuck to same 4.3 BAT.
Enclosing today's ss here.
![Screenshot (12)](https://user-images.githubusercontent.com/21994386/87422205-dafe9c00-c5f5-11ea-8b6d-e8ae3077720c.png)

**Comment by tmancey** [comment]
@Mr-grey-hat Would you be available for a screen-share please? thanks

**Comment by Mr-grey-hat** [comment]
@tmancey I would be happily do so, but since 2 days its working fine, although I am still keeping track in case it goes wrong. I have a query, Is there any way I could reget lost BAT? I raised this issue on brave community forum also they gave some 2 BAT but the loss is more.

**Comment by tmancey** [comment]
@Mr-grey-hat If the issue occurs again please do let me know. To look into the lost bat could you please visit brave//rewards-internals and send over the payment id via email (please do not post in this chat)

**Comment by Mr-grey-hat** [comment]
@tmancey mailing u, please check

**Comment by Mr-grey-hat** [comment]
In brave-internals I checked logs and found 31 signed tokens which failed to refill to convert to unblinded tokens.

**Comment by Mr-grey-hat** [comment]
@tmancey another problem arises, Since 2-3 days I am not getting any Ad notification even though I am browsing extensively, Please look into this matter.

**Comment by tmancey** [comment]
Ad campaigns vary by country, and by operating system. In some countries, there may be fewer ads observed throughout the month based on campaign size, delivery pacing, operating systems, content categories and that advertisers have selected to run their ads to.

As we continue to generate additional demand for countries where Brave Ads are available, the consistency should improve over time.

**Comment by tmancey** [comment]
Closing issue as BAT was lost due to disabling/re-enabling ads. User will reach out for further help if needed. Thanks
