### ISSUE TITLE
[Desktop] Unable to stop Bat ads and Bat ledger services,Built in extensions

### ISSUE THREAD

**Issue by soundarrr** [brave/brave-browser#10702]
## Description 
Hello,
I started using brave browser few days ago and found it was eating up a lot of ram,I thought to end the process in the built in TASK MANAGER but it relaunches it self within a few seconds.I disabled Bat ads and rewards. I found a thread in reddit telling me to remove brave_resources.pak from directory,and so I did and i am not able to view any pdf files.But it solved my problem of eating the ram.Is there any other way to disable it. @brave-browser-releases 

## Steps to Reproduce
   1. open multiple tabs
   2. browser be idle for 5 min
   3. check task manager

## Actual result:
I am not able to disable it hence the browsers eats my ram and gpu.With 3 tabs open its eats 400mb
![ann](https://user-images.githubusercontent.com/66728880/87273160-f4202380-c4f5-11ea-8615-bb50df889cd2.jpg)

## Expected result:
As advertised the memory and GPU should be low.Need disable button for the built in extensions,BAT LEDGER SERVICE,Bat ads Service,Bat ads

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave	1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Revision	8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS	Windows 10 OS Version 1909 (Build 18363.900)
JavaScript	V8 8.3.110.13
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,VideoPlaybackQuality,TextFragmentAnchor,NotificationTriggers,TabHoverCards,SmsReceiver,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --enable-audio-service-sandbox --disable-sync
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\ELCOT\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? IDK
- Can you reproduce this issue with the dev channel? IDK
- Can you reproduce this issue with the nightly channel? IDK

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:
Hello,
I started using brave browser few days ago and found it was eating up a lot of ram,I thought to end the process in the built in TASK MANAGER but it relaunches it self within a few seconds.I disabled Bat ads and rewards. I found a thread in reddit telling me to remove brave_resources.pak from directory,and so I did and i am not able to view any pdf files.But it solved my problem of eating the ram.Is there any other way to disable it. @brave-dev

**Comment by NejcZdovc** [comment]
@soundarrr we implement this option in this issue https://github.com/brave/brave-browser/issues/9526. Now processes will only start if rewards is enabled. Hope that this fixes issue that you have. Will close the issue, but let me know if there is anything else

**Comment by soundarrr** [comment]
So are you telling me to update brave browser or do some other. please let
me know much clearer......
Regards
Soundarahari

**Comment by NejcZdovc** [comment]
@soundarrr so this change is currently in beta and will be released in ~3 weeks. You can try it out in beta, which you can find on this link https://brave.com/download-beta/

**Comment by soundarrr** [comment]
thank you

**Comment by soundarrr** [comment]
@NejcZdovc still unable to disable Brave extension......eats a lot of ram too...
![annn](https://user-images.githubusercontent.com/66728880/87500197-87ce2d00-c679-11ea-9afe-6dc6f2ec4b9d.jpg)

**Comment by NejcZdovc** [comment]
@soundarrr correct extensions were not removed. cc @bsclifton @rebron for input

**Comment by soundarrr** [comment]
so shall I open an issue

**Comment by NejcZdovc** [comment]
I think this one can be closed. We fixed services and for extension we have this one tracking https://github.com/brave/brave-browser/issues/6479 (so that only load extensions when they are needed).

**Comment by soundarrr** [comment]
ok

**Comment by soundarrr** [comment]
that issue was open from Oct 15, 2019

**Comment by soundarrr** [comment]
As of now how much people have opened an issue on this topic?

**Comment by bsclifton** [comment]
@soundarrr we don't really support disabling the Brave extension. Besides handling shields, it also does other things critical to the product (ex: New tab page, cosmetic adblocking, etc). If you wanted to look more at what would be disabled, you can view the code here:
https://github.com/brave/brave-core/tree/master/components/brave_extension/extension/brave_extension

If you really want to roll the dice, you're welcome to try- there's a command line flag I believe you can pass in which will show built in extensions. You can then disable those which you don't want.

You can launch from the CLI using `--show-component-extension-options` and then visit brave://extensions to see the hidden extensions that you can disable. Alternatively, I believe you can launch Brave using `--disable-brave-extension` and it should disable the extension.

**Comment by soundarrr** [comment]
i am not that good at those terms, please explain a bit more

**Comment by bsclifton** [comment]
@soundarrr basically it looks like you're on Windows. What you can do is right click the shortcut for Brave and pick Properties
![image](https://user-images.githubusercontent.com/4733304/87516089-aa3c5800-c631-11ea-9d38-ec7ef1397c65.png)

At the end of the `Target` field, you can paste in ` --show-component-extension-options` for example and then launch Brave and go to the brave://extensions page. To be clear, I don't recommend this 😄 With essential services no longer running, you might experience a crash or other unexpected behavior. But it would potentially save you 43MB of RAM from looking at your task manager

**Comment by soundarrr** [comment]
@bsclifton actually I need not disable it until eats ram.....By the way in the brave://settings if i change the global shield setting for trackers and ads as disabled,it will automatically go standard if I refresh the page

**Comment by soundarrr** [comment]
@bsclifton See I need not actually disable it or remove it,As a student in India now I only use Google Meet and Google Classroom where Brave shields are not needed(i made as shields down for this sites. ).The problem is even though the shields are down why it takes so much ram.Not only 43 MB of ram, when I use meet.google.com for more than 2 hours it raises to more than 100 MB of ram. That's why I decided to do it.By disabling it I knew it will coz some privacy and security issues.Even I am aware of it. The only reason I moved from Chrome to Brave is due to security and privacy. I do understand it.I need not just save 43 MB but when it raises to great levels my meet tab struggles and becomes slow, Hope fully you will understand me.........

**Comment by soundarrr** [comment]
> @soundarrr we don't really support disabling the Brave extension. Besides handling shields, it also does other things critical to the product (ex: New tab page, cosmetic adblocking, etc). If you wanted to look more at what would be disabled, you can view the code here:
> https://github.com/brave/brave-core/tree/master/components/brave_extension/extension/brave_extension
> 
> If you really want to roll the dice, you're welcome to try- there's a command line flag I believe you can pass in which will show built in extensions. You can then disable those which you don't want.
> 
> You can launch from the CLI using `--show-component-extension-options` and then visit brave://extensions to see the hidden extensions that you can disable. Alternatively, I believe you can launch Brave using `--disable-brave-extension` and it should disable the extension.

@bsclifton See I need not actually disable it or remove it,As a student in India now I only use Google Meet and Google Classroom where Brave shields are not needed(i made as shields down for this sites. ).The problem is even though the shields are down why it takes so much ram.Not only 43 MB of ram, when I use meet.google.com for more than 2 hours it raises to more than 100 MB of ram. That's why I decided to do it.By disabling it I knew it will coz some privacy and security issues.Even I am aware of it. The only reason I moved from Chrome to Brave is due to security and privacy. I do understand it.I need not just save 43 MB but when it raises to great levels my meet tab struggles and becomes slow, Hope fully you will understand me.........The main reason is there is no ads in Google meet or Google Classroom,I don't open new tabs during my virtual classes,and no shields also.So why it reaches 100 MB of ram???

**Comment by soundarrr** [comment]
no reply from brave team @bsclifton @brave-browser-releases @brave-dev

**Comment by soundarrr** [comment]
see this proof::::
![Screenshot (2)](https://user-images.githubusercontent.com/66728880/87758679-8728c880-c82a-11ea-9bb5-3567f93f1cef.png)
@bsclifton  @NejcZdovc @brave-browser-releases

**Comment by soundarrr** [comment]
and for some reason they are in 2.

**Comment by dpthegrey** [comment]
Bat Ledger service still running even after Brave rewards is not enabled. If we end process manually, On fresh restart of browser the Bat Ledger process is still on. 

![image](https://user-images.githubusercontent.com/49444980/213476316-d6cdf046-4607-451d-8826-58c4f5f0a48f.png)

### Brave Version
1.47.171 Chromium: 109.0.5414.87 (Official Build) (x86_64)
