### ISSUE TITLE
[Android] chromium bump to C84.x.x85 - Android issue for 10594

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10711]
Android issue for https://github.com/brave/brave-browser/issues/10594 per request from @srirambv

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.95 Beta build
- Verified settings/history/bookmarks/theme/shields settings/rewards settings are retained during upgrade
- Verified UI doesn't show Chrome anywhere
- Verified shields settings are retained between relaunches
- Logged an issue for sync crash on upgrade (#10725)
