### ISSUE TITLE
[Desktop] espn.com videos don't play with standard fingerprinting blocking (default)

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#10716]
## Description 

Videos on espn.com don't play with our default fingerprinting blocking (standard). Allow all fingerprinting will play the videos.

## Steps to Reproduce

   1. Go to espn.com
   2. Scroll to any of the videos.
   3. Hit play button on any of the videos (the short ones not the ones that to go to premium service) and notice the video doesn't play. 

## Actual result:

![Screen Shot 2020-07-13 at 12 08 44 PM](https://user-images.githubusercontent.com/5951041/87343608-fe481f00-c501-11ea-9402-da1cdd7ae36d.png)
stuck seeing play button screen, never moves forward.

## Expected result:
Video plays.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Brave | 1.12.82 Chromium: 84.0.4147.68 (Official Build) beta (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.16 (Build 20A4300b)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No.
- Can you reproduce this issue with the beta channel? Yes. 1.12.x
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? Yes. 1.13.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes Allow All Fingerprinting
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by pes10k** [comment]
Should be fixed by https://github.com/brave/brave-core/pull/6067

**Comment by rebron** [comment]
Closing, dupe of #10718
