### ISSUE TITLE
[Desktop] Don't cache etag and related caching information on small requests

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#10719]
Web trackers sometimes use eTags or HTTP caching values as unique identifiers for cross-site tracking

As a stop gap solution until Blink has full partitioned HTTP caching, Brave should ignore caching information on small requests (<5k).  This will both i) target the kinds of resources most frequently used to fetch / retrieve tracking tags, and ii) still keep caching tags on the kinds of resources most likely to be useful to the user (i.e. on large responses).

**Comment by pes10k** [comment]
re @bridiver 
```diff --git a/net/http/http_cache_transaction.cc b/net/http/http_cache_transaction.cc
index ad6e626898d1f51fe51d4bc38ad660ce8d8022e1..23138f022cf096b5b25a630fddc9380b39d31888 100644
--- a/net/http/http_cache_transaction.cc
+++ b/net/http/http_cache_transaction.cc
@@ -2834,6 +2834,11 @@ bool HttpCache::Transaction::ConditionalizeRequest() {
     } else {
       custom_request_->extra_headers.SetHeader(
           HttpRequestHeaders::kIfNoneMatch, etag_value);
+      size_t cache_size = entry_->EstimateMemoryUsage();
+      if (cache_size == 0 && entry_->disk_entry != nullptr)
+          cache_size = entry_->disk_entry->GetDataSize(kResponseContentIndex);
+      if (cache_size <= 1000)
+        custom_request_->extra_headers.RemoveHeader(HttpRequestHeaders::kIfNoneMatch);
     }
     // For byte-range requests, make sure that we use only one way to validate
     // the request.```

**Comment by Peacock365** [comment]
May I suggest this as a better approach:

https://gitlab.com/KevinRoebert/ClearUrls/-/blob/master/core_js/eTagFilter.js

Making this dependent on the size of the request doesn't seem like a good idea, rather, you should filter the eTag header out. The solution used by ClearURLs is what the extension eTag Stoppa for Firefox uses, as well. I recommend the same for Brave.

**Comment by pes10k** [comment]
Hello @Peacock365 , thanks you again for the link.  I don't think we'd be comfortable removing etags all togehter, as that will have a significant performance impact on users (I just ran some measurements last week on this, and the size of responses to etag'd values is pretty evenly distributed).

Some things we are considering though (no decisions made) are:
- Stripping out etags on small responses, where there is little-to-no perf cost
- Trying to list build lists of folks using etags for privacy violations
- Removing etag's for 3p requests

The "correct" solution here though will be to partition etag's under the 1p though.  This work is going on upstream in chromium (we've very excited for it), though depending on how long that will take up stream, we might consider a shorter term solution too.

Thanks again for the suggestion!

**Comment by Peacock365** [comment]
Yeah, so I didn't feel any performance impact here, my hardware isn't great (measly MacBook Pro 13" from 2015) and neither is my Internet connection, with or without ClearURLs doesn't seem to make a difference here, and yes, the extension is filtering out eTag headers like crazy. If Chromium upstream is tackling this, I suppose you should wait for what comes out of that, though.

**Comment by Peacock365** [comment]
I do realize that my setup is nowhere near a scientific test or so, haha. :-D

**Comment by pes10k** [comment]
Closing this now that Brave partitions this cache

https://brave.com/privacy-updates/14-partitioning-network-state/

**Comment by Peacock365** [comment]
@pes10k 

Sorry to say, but whatever you've done with the cache hasn't fixed the eTag tracking issue for me; Brave fails the test at http://lucb1e.com/rp/cookielesscookies/ ...

That being said, Brave 1.42.83 passes the test with ClearURLs 1.25 installed, presumably due to this commit https://github.com/ClearURLs/Addon/commit/628faf0e85919f5eea64e1ac40bf0bd781708e98 , but fails the test every single time with no extension installed. Please look into this, this doesn't seem fixed to me even though you closed the issue.

**Comment by pes10k** [comment]
This test is being deceptive, and is actually doing its trick by matching IP address and user agent if it doesn't find an etag (you can see this in the source code here https://github.com/lucb1e/cookielesscookies/blob/a23a2c8163d91063f08ca38e530b284839933d06/index.php#L15).  This is frustrating bc the site says "This tracking method works without needing to use:… Your IP address or user agent string" but, nevertheless…

You can verify this is the case by varying either your user agent string (using an extension or whatever else) or your IP (say, using a tor tab in Brave).  You'll see the site is no longer able to link your visits.

**Comment by Peacock365** [comment]
@pes10k 

The dishonesty regarding the methodology aside (I agree with you there!), can you explain why I am getting random values with ClearURLs 1.25 while Brave without the extension enabled consistently fails the test? The extension does neither change the user agent string nor the IP address... Mind you that this is not *my* issue in particular, as I consider it fixed for me thanks to the extension. It might be an issue for other Brave users though. ClearURLs seems to pass this test via dummy eTag (see the commit I linked above)...

**Comment by Peacock365** [comment]
And Brave fails this test too, by the way: https://hinternesch.com/page1

Got the link from here: https://levelup.gitconnected.com/no-cookies-no-problem-using-etags-for-user-tracking-3e745544176b

Faulty methodology there as well (serious question)?

**Comment by Peacock365** [comment]
**Cross that!** Brave with or without ClearURLs fails all tests. What really made me pass these tests was apparently the Cookie AutoDelete extension which automatically flushes my cache upon me leaving a website. Still not a good look though, Brave without Cookie AutoDelete passes neither test, ClearURLs plays no role though apparently.

**Comment by pes10k** [comment]
> https://hinternesch.com/page2.html

I'm not sure whats being tested here… we dont block sites from setting etags, we partition HTTP resources by the first level site, so if a.example sets an etag when requested from b.example, a.example can't read / access that etag when requested from c.example. This (and partitioning in general) is what prevents a.example from tracking you across websties.  Third parties see a different cache for every first party they appear under.

Additionally, we clear etags (like all HTTP cached resources) when the user clears storage, which prevents the first-party from tracking you after you clear storage (which is what the "Cookie AutoDelete" extension is doing).

All that is to say, is that this doesn't look like a bug, this looks like Brave doing whats expected and promised, and also Brave protecting you out of the box from cross site tracking (and allowing users to prevent first-party reidentification by clearing storage).
