### ISSUE TITLE
Fingerprinting 2.0: Plugins (mimetype)

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#10718]
Continuing from #9435

The new fake plugins we're adding are causing naive JS code to crash because it assumes that every plugin has at least 1 associated MIME type, so code like `navigator.plugins[0][0].type` crashes. So the fake plugins we create and inject into `navigator.plugins` should also include at least 1 associated MIME type.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/6067
- Ensured that video play without any issues in default shield settings
