### ISSUE TITLE
[Desktop] monthly payment isn't always displayed on brave://rewards correctly - follow up to 10438

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10717]
## Description 

Follow up to #10438 

`Monthly Payment` AC settings are not retained correctly in upgraded profile 1.11.x

## Steps to Reproduce

Scenario 1 from https://github.com/brave/brave-browser/issues/10438:
   1. Clean profile 1.10.97 (needs to be prior to 1.11.x since there were changes to API and prefs in 1.11.x)
   2. Enable rewards
   3. Change AC settings values except for monthly payment (keep the monthly payment as it is which 20 BAT) - Note, it does not matter if you have brave://rewards page open or closed, result on 1.11.x is the same
   4. Upgrade profile to 1.11.x (PR build)
   5. Open brave://rewards if necessary, Look for AC Monthly Payment value
--> blank in AC table, you can view the drop down to see values (no option is checked though)
--> if you open AC settings, Monthly Payment box is blank/narrow, but you can click on it to view other options (no option is checked though)
--> Page refresh fixes this

Scenario 2 from https://github.com/brave/brave-browser/issues/10438:
   1. Clean profile 1.10.97
   2. Enable rewards
   3. Change AC Monthly Budget to some other value (like 100 BAT) - Note, it does not matter if you have brave://rewards page open or closed, result on 1.11.x is the same
   4. Upgrade profile to 1.11.x (PR build)
   5. Open brave://rewards if necessary, Look for AC Monthly Payment value
--> blank in AC table, you can view the drop down to see values (no option is checked though)
--> if you open AC settings, Monthly Payment box is blank/narrow, but you can click on it to view other options (no option is checked though)
--> Page refresh fixes this

(so basically same as scenario 1 results)

## Actual result:

<img width="838" alt="scenario 1a 1" src="https://user-images.githubusercontent.com/28145373/87345261-d6ff4b00-c51d-11ea-88c0-e2e3d9dd68fa.png">
<img width="650" alt="scenario 1a 2" src="https://user-images.githubusercontent.com/28145373/87345265-d961a500-c51d-11ea-851b-337784b1bc15.png">
<img width="648" alt="scenario 1a 3" src="https://user-images.githubusercontent.com/28145373/87345270-dbc3ff00-c51d-11ea-96b0-1a5b4b370f95.png">

## Expected result:

AC monthly budget should be retained without page refresh

## Reproduces how often: 

Always

## Brave version (brave://version info)

was using https://bravesoftware.slack.com/archives/CMH8DU4TF/p1594303165277600 to test (1.11.x PR build for https://github.com/brave/brave-core/pull/6050 due to code changes w/ 1.12.x and 1.13.x that made testing difficult on Nightly)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron @zenparsing

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the STR from the description

**Scenario 1:** - Before upgrade in 1.11.x

AC1.11.x | AC advanced1.11.x | AC advanced1.11.x
-- | -- | --
![image](https://user-images.githubusercontent.com/38657976/89662022-1472b080-d8f1-11ea-90d8-cf177f8c5af9.png) | ![image](https://user-images.githubusercontent.com/38657976/89660654-44b94f80-d8ef-11ea-8ed9-237d1ae275ec.png) | ![image](https://user-images.githubusercontent.com/38657976/89661680-9d3d1c80-d8f0-11ea-995d-0499bb7ea81a.png)

After upgrade to 1.12.x
AC1.12.x | AC advanced1.12.x | AC advanced1.12.x
-- | -- | --
![image](https://user-images.githubusercontent.com/38657976/89662357-995dca00-d8f1-11ea-8f23-2a7d63b2b207.png) | ![image](https://user-images.githubusercontent.com/38657976/89662438-b85c5c00-d8f1-11ea-8497-c54e86c94672.png) | ![image](https://user-images.githubusercontent.com/38657976/89662493-cd38ef80-d8f1-11ea-87f0-79a15f96480a.png)
