### ISSUE TITLE
[Android] Location service message in Search engines settings

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#10713]
## Description 
We have a Location is allowed or not allowed message under a search engine, it does nothing as we don't let to know a location until a user allows that. This message is related to the current device location service message.

## Steps to reproduce 

Go to Settings->Standard tab and click on any search engine

## Actual result 
Observe the message

## Expected result
We should not show the message

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build
- Verified location service message is removed from both normal and private search setting

Standard Tab  | Private Tab 
-- | --
![image](https://user-images.githubusercontent.com/17010094/91321974-1b396880-e7b7-11ea-8c69-a937851580ff.png) | ![image](https://user-images.githubusercontent.com/17010094/91321986-1f658600-e7b7-11ea-8525-326c7fc6e268.png)

-------------
Verification passed on Samsung Tab A with Android 10 running 1.13.81 x64 build
- Verified location service message is removed from both normal and private search setting

Standard Tab | Private Tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/91322010-24c2d080-e7b7-11ea-97cf-bce37ef4101e.png) | ![image](https://user-images.githubusercontent.com/17010094/91322022-27bdc100-e7b7-11ea-9b7e-cb5e1016ea8c.png)
