### ISSUE TITLE
[Android] have a way to view server errors in UI - follow up to 9533

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10712]
Android specific issue for https://github.com/brave/brave-browser/issues/9533 per request of @srirambv

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.95
- Verified user can auto-refresh log in brave://rewards-internals
- Verified user can manually refresh log in brave://rewards-internals
- Verified user can clear log in brave://rewards-internals
- Verified cleared logs are not shown when refreshing the log
- Verified can download logs with `Download full log` button
- Verified can only download logs when the console shows logs. With no logs in the console, download button does nothing
-----------------
Verification passed on Samsung Tab A with Android 9 running 1.11.95
- Verified user can auto-refresh log in brave://rewards-internals
- Verified user can manually refresh log in brave://rewards-internals
- Verified user can clear log in brave://rewards-internals
- Verified cleared logs are not shown when refreshing the log
- Verified can download logs with `Download full log` button
- Verified can only download logs when the console shows logs. With no logs in the console, download button does nothing
