### ISSUE TITLE
[Android] Browser crash when loading sync v1 on upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10725]
## Description 
Browser crash when loading sync v1 on upgrade

## Steps to reproduce 

   1. Install an older version of Android 
   2. Enable Sync v1
   3. Upgrade to 1.11.93 build
   4. Open settings and go to Sync, browser crashes

## Actual result 
![sync-crash](https://user-images.githubusercontent.com/17010094/87412155-94427f00-c5c0-11ea-84c8-e15e725b0ec6.gif)

## Expected result
No crash. 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.11.93 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by Martina-Neumayer** [comment]
That same on mine Brave.

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/6073 was merged.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.98 x64 build
- Verified no crash when opening sync devices page
------------------
Verification passed on Samsung Tab A with Android 9 running 1.11.98 x64 build
- Verified no crash when opening sync devices page
