### ISSUE TITLE
[Desktop] Rewards badge checkmark not displayed for some registered publishers

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#10729]
## Description 

With the new "v4 publisher list" in 1.12, registered publishers that do **not** have a wallet address are not getting the rewards badge checkmark when visiting the site. In staging, a publisher exhibiting this behavior is `duckduckgo.com`.

If a publisher key is present in a v4 channel response file, then that publisher should have a status of at least `CONNECTED`, regardless of the wallet information returned with that publisher.

## Steps to Reproduce

   1. Start with clean profile with `--rewards=staging=true`
   2. Enable rewards
   3. Navigate to `duckduckgo.com`

## Actual result:

A checkmark is not displayed on the rewards badge.

## Expected result:

A checkmark should be displayed on the rewards badge.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6072
* Using a connected publisher, confirmed verified check mark displays on BAT logo, 1 time tip banner, recurring tip banner, AC list, recurring tip list, 1 time tip list and monthly statement
* Using a KYC'd publisher, confirmed verified checkmark displays on BAT logo, 1 time tip banner, recurring tip banner, AC list, recurring tip list, 1 time tip list and monthly statement
* Confirmed non-Brave verified publisher does not display a verified checkmark on BAT logo, 1 time tip banner, recurring tip banner, AC list, recurring tip list.
