### ISSUE TITLE
Downloaded PDFs don't load in tab when clicked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1072]
## Description 

Downloaded PDFs don't load in tab when clicked

## Steps to Reproduce

   1. Visit https://basicattentiontoken.org/ in a new tab
   2. Right click on whitepaper and save link, should download the pdf file
   3. Click on PDF file to open, Opens in a new tab but doesn't load the file
   4. Click to choose file, On linux it opens the file in the same tab, On Windows it brings the save file prompt again

## Actual result:

https://youtu.be/3Ua1hkBYJGY
If the file is downloaded from Gmail, the following errors are shown on console when clicked to open
![image](https://user-images.githubusercontent.com/17010094/45268147-3b46b480-b446-11e8-8a9f-84bcb01cb3e7.png)

## Expected result:
Should load the PDF in tab or allow system default app to launch it

## Reproduces how often: 

Easy

## Brave version (about:brave info) 

Brave | 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows/Linux

### Reproducible on current release:

No, b-l opens the file in system app

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Found while verifying #1068
cc: @bbondy @bridiver

**Comment by bgiesing** [comment]
![image](https://user-images.githubusercontent.com/7895463/46253455-d4fbf300-c441-11e8-966d-8068b7c9ff67.png)

Still happens here on Windows 10 with Version 0.56.1 Chromium: 70.0.3538.22 (Official Build) dev (64-bit). Says to enable "Allow access to file URLs" permission which the PDFjs extension doesn't have (other extensions do)

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X
