### ISSUE TITLE
[Desktop] Support OS location service on Windows

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#10722]
Use OS location service if possible instead of using network based location service (location.brave.com)

## Steps to Reproduce
   1. Open Control panel and enable location service
   2. Launch fiddler to capture request
   3. Launch browser and open console
   4. Paste below code and got position info
     ```
       navigator.geolocation.getCurrentPosition(position => {
           console.log(`${position.coords.latitude} + ${position.coords.longitude}`)
      })
    ```
   5. Check fiddler doesn't capture `location.brave.com`
   6. disable location service
   7. Repeat above 4th step
   8. Check fiddler captures `location.brave.com`

This is upstream issue for using OS location service on Windows - https://bugs.chromium.org/p/chromium/issues/detail?id=968883 and it seems that implementation is finished and they will ship it by default after some more testing.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.13.73 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1903 (Build 18362.1016)


```
- Verified the STR from the description

**When Location service is ON in windows OS**
- Verified that the fiddler doesn't capture `location.brave.com`
![2](https://user-images.githubusercontent.com/38657976/90506874-9628d080-e172-11ea-8986-b66afb13c730.png)

- Verified that the code in the console gives the o/p as below
![1](https://user-images.githubusercontent.com/38657976/90506863-91fcb300-e172-11ea-84fa-88c5537728c2.png)



**When Location service is OFF in windows OS**
- Verified that the fiddler doesn't capture `location.brave.com`
![4](https://user-images.githubusercontent.com/38657976/90506969-ba84ad00-e172-11ea-9163-dcba79fb7c8e.png)

- Verified that the code in the console gives the o/p as below
![3](https://user-images.githubusercontent.com/38657976/90506983-c1132480-e172-11ea-8eda-32d62d3a1eed.png)
