### ISSUE TITLE
Support OS location service on macOS

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#10724]
Upstream already has `CoreLocationProvider`.
However, it doesn't work if Brave is not inserted in allowed list of Location Service.
If Brave is not inserted, we should use `NetworkLocationProvider` as a fallback

On Windows, if user doesn't enable OS location service, `NetworkLocationProvider` is set even if `LocationProviderWinrt` flag is on. However, `NetworkLocationProvider` is not used on macOS as a fallback.

STR:
1. Check `MacCoreLocationBackendStudy` is enabled from brave://version
2. Load https://www.gps-coordinates.net/my-location
3. Allow location permission via site settings bubble below
<img width="381" alt="Screen Shot 2021-07-29 at 10 24 34 AM" src="https://user-images.githubusercontent.com/6786187/127417142-a6977158-2d9d-4924-900c-08838d73bc8c.png">
4. Allow Brave browser for accessing os location via `Preferences`
<img width="359" alt="Screen Shot 2021-07-29 at 10 26 24 AM" src="https://user-images.githubusercontent.com/6786187/127417223-d952edb2-5481-4e6b-9aa2-156e850baca5.png">
5. Reload and check it shows correct location

**Comment by simonhong** [comment]
It seems macOS support is in-progress and it's targeted to C86
Upstream issue - https://bugs.chromium.org/p/chromium/issues/detail?id=1051591
I think it's fine to wait upstream progress. WDYT? @bsclifton @rebron @fmarier

**Comment by bsclifton** [comment]
@simonhong SGTM 👍

**Comment by rebron** [comment]
cc: @mihaiplesa @mkarolin

**Comment by simonhong** [comment]
I think we can fix this by enabling `Core Location Backend` feature by default?

**Comment by simonhong** [comment]
Set `1.27.x` milestone as `MacCoreLocationBackendStudy` is also applied to current release channel.
I can see `MacCoreLocationBackendStudy` is enabled via brave://version like below and can get accurate location.
cc @kjozwiak @rebron 

<img width="667" alt="Screen Shot 2021-07-29 at 10 17 43 AM" src="https://user-images.githubusercontent.com/6786187/127416691-cc31ce91-4cc7-4723-b508-7ee0acbbe6dc.png">

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.27.110 Chromium: 92.0.4515.131 (Official Build) (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 10.15.7 (Build 19H1217)
```

Confirmed `MacCoreLocationBackendStudy:Enabled` on brave://version.
Confirmed prompted to select location permission preference via site settings bubble.
Confirmed selecting Block button did not prompt me to allow Brave Browser to access OS location services via `Preferences`.
Confirmed selecting Allow button did prompt me to allow Brave Browser to access OS location services via `Preferences`.
Confirmed after allowing Brave Browser to use the macOS Location Services and refreshing the https://www.gps-coordinates.net/my-location page, the map showed my correct location.

Example | Example | Example
----- | ----- | -----
<img width="1030" alt="Screen Shot 2021-08-04 at 8 29 06 AM" src="https://user-images.githubusercontent.com/28145373/128183371-95664b1c-866a-41fb-9010-95ee94112f95.png"> | <img width="360" alt="Screen Shot 2021-08-04 at 8 45 53 AM" src="https://user-images.githubusercontent.com/28145373/128183376-e163c07b-619c-4816-bd4d-19ee69efb20d.png"> | <img width="344" alt="Screen Shot 2021-08-04 at 8 46 14 AM" src="https://user-images.githubusercontent.com/28145373/128183378-a1cb5986-8372-4b17-9ebc-c79cc2b2085c.png">

----------------

**Comment by kjozwiak** [comment]
Going to exclude this from the notes as this already went out via Griffin. This was more of a double check to make sure things are working as expected.
