### ISSUE TITLE
[Desktop] RFE: Print Icon

### ISSUE THREAD

**Issue by ToddAndMargo** [brave/brave-browser#10738]
Request for Enhancement:

Would you please consider giving me a "print" icon?

Many thanks,
-T

**Comment by rebron** [comment]
Hi @ToddAndMargo Thanks for the feature request. Marking this as wontifx as we won't be adding a "print" icon for the toolbar anytime soon. In some cases though specific to .pdf documents, a print icon does appear as the likelihood for printing a pdf document is higher than printing web pages in general.

**Comment by ToddAndMargo** [comment]
Would you please reconsider this.  My customers are not using the hamburger as they do not know what it is and are use to having a print icon.  And yes, I do show them.  Goes in one ear and our the other.

Many thanks,
-T
