### ISSUE TITLE
[Desktop] Introduce bare-bones Playlist functionality

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#10736]
## Description 
It's not always convenient to stream content - you might want to watch it later or the network might not be available at a certain time

### Requirements
The goal with this issue would be to introduce a bare-bones "Playlist" feature which allows users to:
- View a playlist at brave://playlist
- Add a video to this playlist (which then downloads video)
- view items on playlist offline
- Remove items from playlist

The functionality should:
- be behind a flag (brave://flags/#playlist) 
- only be available on Nightly

Specific product features TBD; nothing is spec'ed out for Desktop (iOS has a fairly detailed spec)

### APIs used to implement this work
Part of this implementation is exposing extension APIs which can be used to interact with the playlist.

Currently, these are only used on brave://playlist - but they are implemented as a extension API (`chrome.playlist`) so that we can potentially use Greaselion to inject `Add to playlist` functionality on pages which are applicable. This functionality needs to be exposed via extension API because it would need to be accessed in an injected content or background script.

Please see https://github.com/brave/brave-browser/issues/5296 for API specific details

**Comment by iefremov** [comment]
@bsclifton do we have any spec for this?

**Comment by bsclifton** [comment]
@iefremov no we don't - but I'll be creating one soon 😄 

The main goal would be to land the code so that it doesn't become stale. Then we can work together on a spec for Desktop + Mobile

**Comment by bsclifton** [comment]
Updated https://github.com/brave/brave-core/pull/5733 with everything which should be needed for a review 😄

**Comment by bsclifton** [comment]
Closing as stale - we have a lot of work done since this issue was created 😄
