### ISSUE TITLE
[Android] chromium 84 bump

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10732]
https://github.com/brave/brave-browser/issues/10714

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.98 x64 build
![image](https://user-images.githubusercontent.com/17010094/88182607-4fee5900-cc28-11ea-8b6a-c452f41493e8.png)

Verification passed on Samsung Tab A with Android 10 running 1.11.98 x64 build
![image](https://user-images.githubusercontent.com/17010094/88182735-77452600-cc28-11ea-914b-f95717778495.png)
