### ISSUE TITLE
[Desktop]Bug - Does not restore open tabs after a computer restarts (Windows)

### ISSUE THREAD

**Issue by NagoDede** [brave/brave-browser#10739]
Problem report may be associated to the issues 10697 and 10017.

## Description 
After a computer restart, Brave does not retrieve my previous tabs while the options is set (Settings: _On start-up, Continue where you left off_).
Also, after restart needs several attempts to open Brave (request at least two attempts).

## Steps to Reproduce

   1. Use brave, with several tabs open. (I have two profiles, I don't know if it impacts. After deletion of one profile, problem remains).
   2. Restart windows / computer. Do not close tabs / Brave before.
   3. After restart, brave tabs are not restored.

## Actual result:
Request several attempts to launch Brave.
No tabs restoration after Brave restart.

## Expected result:
When brave is closed, it should restore the tabs when open again, whatever the origin of the termination.

## Reproduces how often: 
Each time computer reboots.

## Brave version (brave://version info)
Windows Desktop, Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

## Version/Channel Information:
Only use the official and stable builds (automatic updates)

**Comment by NagoDede** [comment]
A reboot with version Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit) seems OK.

**Comment by bsclifton** [comment]
Thanks for the report @NagoDede - I don't think profile would be affecting this in any way. As long as Brave is closing cleanly (ex: you quit or close the window via the X in the top right), it should be able to restore all tabs without an issue. If the process gets killed (ex: you kill in Windows Task Manager) or if Brave is experiencing a crash on close, I think that might explain the problem

Can you please check out brave://crashes and see if anything shows up there? If so- you should see a button to report the issue. Please let us know 😄

**Comment by rebron** [comment]
@NagoDede Are you still experiencing this issue with our latest release 1.13.82? You mentioned you have two profiles open when you run Brave?

**Comment by NagoDede** [comment]
Hello, 
As I delete one profile, I have now only one profile.
I can't reproduce the problem, so for me it's closed

**Comment by rebron** [comment]
@NagoDede Thanks for the follow-up. I'll close this issue then.
