### ISSUE TITLE
[Desktop] Update l10n for Chromium 84.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#10735]
## Description 

Download the latest l10n from Transifex.

**Comment by kjozwiak** [comment]
@brave/legacy_qa should run through a few locals just to make sure that nothing obvious has regressed. Shouldn't spend too much time on this though.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Generally spot checked the translation in Polish
Spot checked some of the translations that were missing

`Background image` is now translated
![image](https://user-images.githubusercontent.com/34715963/87547898-0f349400-c6ac-11ea-863c-87f3fd0c3f8d.png)

`Certificate` and `Cookies` is translated
![image](https://user-images.githubusercontent.com/34715963/87548173-66d2ff80-c6ac-11ea-91e9-f85a69bd87bb.png)

`Certificate viewer` is translated
![image](https://user-images.githubusercontent.com/34715963/87548232-7f431a00-c6ac-11ea-8f6b-46c498de48c9.png)

Logged https://github.com/brave/brave-browser/issues/10745
Logged https://github.com/brave/brave-browser/issues/10746
