### ISSUE TITLE
URL on the URL bar cannot be changed once it is autocompleted

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1073]
Carrying over from with good discussion: https://github.com/brave/browser-laptop/issues/5767

**Describe the issue you encountered:** URL on the URL bar cannot be changed once it is autocompleted

>1 Open https://www.chromium.org/
>2 Open https://www.chromium.org/Home
>3 Open https://download-chromium.appspot.com/
>4 Input ``chro``
>5 Push the down key three times
>6 Push the right key

> -> Autocompleted URL = chromium.org/Home

**Expected behavior:** The autocompleted URL should be changed to https://download-chromium.appspot.com/

>- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

>- Brave Version: 0.12.10 RC1

>- Any related issues:

**Comment by bbondy** [comment]
I don't think we want to diverge for autocomplete behavior to Chromium here, please re-open if you disagree
