### ISSUE TITLE
[Desktop] Fingerprinting settings doesn't show any blocked count (consider removing it)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10744]
## Description 

With new shields dropdown for Fingerprinting, there is no blocked item count shown in shileds. If we do not show any blocked items then we should consider removing the text 

## Steps to Reproduce

   1. Install 1.11.97
   2. Visit `https://browserleaks.com/webrtc`
   3. Set FP to standard, nothing gets blocked no block count is shown
   4. Set FP to strict, Webrtc is blocked, no block count is shown in shieids

## Actual result:

<img width="902" alt="Screenshot 2020-07-15 at 12 48 09 p m" src="https://user-images.githubusercontent.com/17010094/87542020-e0281d80-c6bf-11ea-84ff-653f3c8b4a81.png">

## Expected result:
Either show the block count and show the details view similar to 1.10.x
<img width="400" alt="Screenshot 2020-07-15 at 12 47 14 p m" src="https://user-images.githubusercontent.com/17010094/87542125-136aac80-c6c0-11ea-9ec5-93e92ded9005.png"><img width="400" alt="Screenshot 2020-07-15 at 12 54 09 p m" src="https://user-images.githubusercontent.com/17010094/87542119-0ea5f880-c6c0-11ea-9042-eb76eef96808.png">

**OR**

Consider removing it if there is nothing to show in detailed view

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{# 852}
OS | Windows 10 OS Version 1809 (Build 17763.1339)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @pes10k @karenkliu @rebron

**Comment by LaurenWags** [comment]
duplicate of https://github.com/brave/brave-browser/issues/10544?

**Comment by srirambv** [comment]
Yup exact dupe. Closing. Thanks for linking the issue @LaurenWags
