### ISSUE TITLE
[Desktop] Gemini widget with translated text overlap making it hard to read

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10742]
## Description 

Gemini widget with translated text overlap making it hard to read

## Steps to Reproduce

   1. Set locale to German
   2. Start a new profile and open a new tab
   3. Connect Gemini widget to your account
   4. Text overlap on each other making it hard to read 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/87780268-4464f180-c826-11ea-8e39-acda72bb35a8.png)

## Expected result:
The translated text should be legible to read 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.13.14 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{# 852}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanml** [comment]
@srirambv do you think you can split this issue? (One for Binance, one for Gemini) We are going to do an icon nav approach for Binance, and for Gemini we will make more efficient use of spacing.

**Comment by srirambv** [comment]
Logged https://github.com/brave/brave-browser/issues/10788 for Icon replacement
