### ISSUE TITLE
[Desktop] `Continue running background apps when Brave is closed` is not translated

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10755]
## Description 

Follow up to: #10735
`Continue running background apps when Brave is closed` is not translated
## Steps to Reproduce

   1. Set language to `Hindi`
   2. Open brave://settings
   3. Under systems `Continue running background apps when Brave is closed` is not translated
   

## Actual result:

`Continue running background apps when Brave is closed` is not translated
## Expected result:

`Continue running background apps when Brave is closed` should be translated
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.11.97 Chromium: 84.0.4147.89 (आधिकारिक बिल्ड) (64-बिट)
-- | --
पुनरीक्षण | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by kjozwiak** [comment]
Only applicable to `Win` and `Linux` as `macOS` doesn't have the above option as per the following:

<img width="1217" alt="Screen Shot 2020-07-23 at 10 36 12 AM" src="https://user-images.githubusercontent.com/2602313/88305371-67d0e600-ccd7-11ea-8e21-7968a4fc4e10.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.11.99 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/88371448-ab981e00-cdb1-11ea-9d71-a969208872df.png)
