### ISSUE TITLE
[Desktop] Brave Rewards in add widget menu jumps around when other widgets are shown/hidden

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10757]
## Description 

Brave Rewards in add widget menu jumps around when other widgets are shown/hidden

## Steps to Reproduce

   1. Install 1.13.16
   2. Open dashboard settings and add/remove existing widgets
   3. When one of the widget is added/removed Brave rewards widget moves to a different position and jumps back to its place

## Actual result:

![add widget alignement](https://user-images.githubusercontent.com/17010094/87576048-6d826680-c6ee-11ea-9585-ffb87944d5ce.gif)

## Expected result:
Widget card should retain its original position

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.13.16 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{# 852}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @karenkliu @petemill  @jamesmudgett 
@ryanml please add it to Crypto/Widgets project board if required.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.13.73 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the STR from the description
- Encountered #10299
