### ISSUE TITLE
[Desktop] Brave Desktop Browser not giving option to Remember Choice for add-ons

### ISSUE THREAD

**Issue by Minervp** [brave/brave-browser#10761]
Desktop Browser is not showing the Check Box to Remember choice for Print Client or other apps..
![image](https://user-images.githubusercontent.com/47079711/87602206-e9ee6700-c739-11ea-9ddd-c0f5dc2e028d.png)

Chrome has the same issue but has a fix by adding a Reg Entry
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
          "ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001

Can you please advise if the same Registry entry can be added to Brave? If so what's the registry path?

**Comment by rebron** [comment]
The same edit to registry should work. cc: @bsclifton

**Comment by bsclifton** [comment]
@Minervp you should be able to do this too- the path will be slightly different:
`HKEY_LOCAL_MACHINE\Software\Policies\BraveSoftware\Brave`
`"ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001`

More info in our group policy article:
https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy
