### ISSUE TITLE
[Android] Sync v2 does not sync default search engine between Desktop and Android

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10760]
Sync v2 does not sync default search engine between Desktop and Android

**Comment by srirambv** [comment]
@jsecretan @bsclifton Is this a blocker for 1.12.x release? If not can we move this one out?

**Comment by bsclifton** [comment]
Per discussion - this is not a blocker. Chrome does NOT sync search engines:
- between desktop and mobile
- between two mobile devices

So changing this behavior would be deviating from Chrome. I'll remove desktop label- as desktop=>desktop is working and mark as enhancement

@jsecretan can you help with prioritization? If this is something we don't want, we can also close 👍

**Comment by AlexeyBarabash** [comment]
Chromium does not sync DSE by purpose on Android and iOS
```C++

// static
void TemplateURLService::RegisterProfilePrefs(
    user_prefs::PrefRegistrySyncable* registry) {
#if BUILDFLAG(IS_IOS) || BUILDFLAG(IS_ANDROID)
  uint32_t flags = PrefRegistry::NO_REGISTRATION_FLAGS;
#else
  uint32_t flags = user_prefs::PrefRegistrySyncable::SYNCABLE_PREF;
#endif
...
  registry->RegisterStringPref(prefs::kSyncedDefaultSearchProviderGUID,
                               std::string(),
                               flags);

```

**Comment by bsclifton** [comment]
@AlexeyBarabash should this be re-opened?

**Comment by kjozwiak** [comment]
> @AlexeyBarabash should this be re-opened?

If we need to re-open, we should create a follow up as there's already code associated with the above issue via https://github.com/brave/brave-core/pull/14402.

**Comment by AlexeyBarabash** [comment]
@kjozwiak @bsclifton 
yes, it should be re-open, as reverting PR was merged  https://github.com/brave/brave-core/pull/14994

The follow-up issue us https://github.com/brave/brave-browser/issues/25247 .

Also creating uplift for reverting, as it reached 1.44.x.

**Comment by kjozwiak** [comment]
Reverted the above change by uplifting https://github.com/brave/brave-core/pull/15015. @AlexeyBarabash @bsclifton going to label this as `QA/No` as the changes were reverted so there's nothing @brave/qa-team can do other than run through https://github.com/brave/brave-browser/issues/25221.

Once the above work makes it into `1.44.x`, we can just point the issue that re-implements the above to this one so QA has more context re: what should be checked/verified etc..
