### ISSUE TITLE
Crash in Brave Ads RedeemUnblindedPaymentTokens

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#10767]
There are few related crashes in beta and nightly, e.g.
```
[ 00 ] confirmations::ConfirmationsImpl::SaveState()
[ 01 ] confirmations::RedeemUnblindedPaymentTokens::Redeem()
[ 02 ] base::OneShotTimer::RunUserTask()
[ 03 ] base::TaskAnnotator::RunTask(char const*, base::PendingTask*)
[ 04 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*)
[ 05 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[ 06 ] base::MessagePumpDefault::Run(base::MessagePump::Delegate*)
[ 07 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta)
[ 08 ] base::RunLoop::Run()
[ 09 ] content::UtilityMain(content::MainFunctionParams const&)
[ 10 ] content::ContentMainRunnerImpl::Run(bool)
[ 11 ] service_manager::Main(service_manager::MainParams const&)
[ 12 ] content::ContentMain(content::ContentMainParams const&)
[ 13 ] ChromeMain
[ 14 ] main
[ 15 ] start
```

https://brave.sp.backtrace.io/p/brave/triage?time=all&filters=((callstack%2Ccontains%2CRedeemUnblindedPaymentTokens))&aggregations=((guid%2Cunique)%2C(classifiers%2Chead))

**Comment by iefremov** [comment]
cc @NejcZdovc @tmancey 
cc @bsclifton to triage

**Comment by bsclifton** [comment]
Marked as P2 - since it's very important but not affecting everybody. If we do have a fix, should we hotfix? @tmancey

**Comment by tmancey** [comment]
@bsclifton @iefremov After search backtrace.io I can see 3 instances for this particular crash over "All Time", . I will attempt to run the address sanitizer again soon however would recommend as this issue is not showing up on 1.11.x or 1.13.x that we keep an eye on not prioritize as of yet. Your thoughts please?

**Comment by bsclifton** [comment]
@tmancey I'll keep as a P2 since it's a crash and we do want to fix. If we know where to look, we should try to harden that area and look for bugs (add tests if needed). Given the low number of occurrences, I think we'd uplift a fix (if available) but not hotfix

**Comment by tmancey** [comment]
Issue has not been reported in backtrace.io for 11 days, moving to backlog and will continue to monitor

**Comment by tmancey** [comment]
Crash has not occurred since 15th July on 1.12.x, closing issue as likely resolved by other refactoring work
