### ISSUE TITLE
[BUG] Default search engine setting resets after update

### ISSUE THREAD

**Issue by Sh1d0w** [brave/brave-browser#1077]
## Description 
If you set a default search engine different from google, after Brave browser updates it resets this setting to google.

## Steps to Reproduce

   1. Install Brave
   2. Set default search engine to duckduckgo
   3. Update Brave to newer version

## Expected result:
Default search engine to stay as set before the update

## Reproduces how often: 
Every time

## Brave version (about:brave info) 
Version 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

**Comment by bbondy** [comment]
@srirambv could you try this on the next update?  @Sh1d0w let me know if it keeps happening on each update too. Thanks!

**Comment by simonhong** [comment]
I didn't see this bug with recent update on MacOS and Win10.

**Comment by Sh1d0w** [comment]
@bbondy The bug was present when updating to 0.55.2, but it seems fixed on 0.55.3.

Closing, Thanks!

**Comment by bbondy** [comment]
I think it could be something like a shutdown crash so settings aren't flushed.

**Comment by Sh1d0w** [comment]
@bbondy Now that you are saying that, I remember shortly after installed and used it for a while it really crashed but I haven't noticed that settings haven't saved, as the update came right the next day.

Btw the new Brave Browser is great, solves a lot of the problems I have reported before and made me come back. Great work!
