### ISSUE TITLE
[Desktop] Show logs preview by default in brave://rewards-internals > logs 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#10778]
## Description 

In brave://rewards-internals logs, the first print out is always completely empty. In order for _any_ logs to print/display, users must first press **Refresh**. However, users often don't know to do this or are fearful that pressing something will harm the logs. Sometimes they even press to clear logs because they don't know what to do.

![image](https://user-images.githubusercontent.com/11497541/87743544-31ff9f00-c7b7-11ea-9ff9-036ab4bfac65.png)

## Steps to Reproduce

Go into brave://rewards-internals logs in v1.11+.

## Brave version (brave://version info)

v1.11 or higher (desktop)

## Solution

Show logs by default in this box.

**Comment by zenparsing** [comment]
Would another option be to simply show the logs when they first activate the Logs tab, so that they don't need to do anything?

**Comment by Miyayes** [comment]
>Would another option be to simply show the logs when they first activate the Logs tab, so that they don't need to do anything?

@zenparsing That would be ideal! I somewhat assumed it wasn't possible or had drawbacks, given it seemed like the natural thing to do but wasn't in the initial implementation :).

**Comment by zenparsing** [comment]
I think it can be done. I wonder also if we should make the "Clear" button less prominent, since pressing that accidentally will clobber the user's log file.

**Comment by NejcZdovc** [comment]
@Miyayes this was intentionally done like this as logs can be big and some old devices could have problems rendering this tab. So if user just switches between tabs things can lock on log tab. This is why I didn't add auto load, but user need to click refresh.

**Comment by NejcZdovc** [comment]
We can try it and see if we will get complains from users

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.54.84 Chromium: 115.0.5790.40 (Official Build) beta (64-bit)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | Windows 10 Version 22H2 (Build 19045.3155)
```

**Comment by Miyayes** [comment]
Looking back, this should've been label as OS/Android as well, since this kind of change affects Android too since this page is shared.
