### ISSUE TITLE
[Desktop] Opening the very first profile would result into crashing

### ISSUE THREAD

**Issue by Iamdeadlyz** [brave/brave-browser#10776]
Brave Version: 1.11.97  Chromium: 84.0.4147.89
Operating System: Windows NT 10.0.17763

URL (if applicable) where crash occurred: N/A

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Create at least 4 different profiles
2. Close all windows once done
3. Restart the computer
4. Try to open the very first profile

If it's not reproducible, I simply closed all the windows normally last night and when I tried to open it today, the very first profile can't be opened anymore. Please see the crash report for more technical details. Thank you!

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/53020000-5fc1-c604-0000-000000000000

**Comment by rebron** [comment]
@Iamdeadlyz Can you update to 1.13.82 and let us know if you're still having this issue?

**Comment by Iamdeadlyz** [comment]
Hi @rebron,

It took me a couple of tries to restore the main profile. One thing that has worked is that I downloaded the installer for Brave again then it restored the main profile after installing. 

I am now using the version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit).
