### ISSUE TITLE
[Desktop] LICENSE and LICENSES.chromium.html files missing from latest stable release (1.11.97)

### ISSUE THREAD

**Issue by mixedCase** [brave/brave-browser#10772]
## Description 

Files LICENSE and LICENSES.chromium.html are missing from latest stable release (1.11.97)

## Steps to Reproduce

   1. Download 1.11.97 release .zip for Linux
   2. Open it and take a look at the file list

## Actual result:

No LICENSE nor LICENSES.chromium.html files, like there were in 1.10.97

## Expected result:

LICENSE nor LICENSES.chromium.html files, like there were in 1.10.97

## Reproduces how often: 

Every time

## Brave version (brave://version info)

1.11.97

Rest of issue template is irrelevant.

**Comment by bsclifton** [comment]
cc: @fmarier

**Comment by fmarier** [comment]
That's a direct result of https://github.com/brave/brave-core/pull/5562. Now we know why that code was there.

The licensing info is available (and up-to-date) on these pages:
- `brave://settings/help`
- `brave://credits`

but we should at least include a copy of the MPL in the root of the zip/tarball.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.13.77 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Downloaded `brave-v1.13.77-darwin-x64-symbols.zip` from https://github.com/brave/brave-browser/releases/tag/v1.13.77.
* Unzipped the file and confirmed the `LICENSE` file is included

<img width="808" alt="10772" src="https://user-images.githubusercontent.com/28145373/90672677-7a7e0280-e224-11ea-8d35-766508fbcd4e.png">

-----------
