### ISSUE TITLE
[Desktop] Crash Report

### ISSUE THREAD

**Issue by psi4got** [brave/brave-browser#10779]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.11.97  Chromium: 84.0.4147.89
Operating System: Windows NT 10.0.19041

URL (if applicable) where crash occurred:

Can you reproduce this crash? 
This and the other crashes have the same starting point. Click on the Brave icon. It flashes like it is opening and then immediately closes. Task manager shows it completely closed and not hanging out in a stuck state. This is the third time in about a year, since I started using Brave, this has happened. It starts with a single incident and over the course of a week it takes more repeated clicks (and subsequent crash closes) before Brave will finally open. Once open it is stable, although my most used shortcuts and Brave BAT stats will be different. The BAT stats recover after a few minutes and few tabs of usage. The shortcuts...well...there will just be new random shortcuts (places I did visit, just not often) instead of the same five or so that are, in normal circumstances, always there. Eventually my usual shortcuts recover and come back.  I have an 8 core i7-6700 3.40Ghz, 32Gb of RAM, the stock, motherboard, Intel shared memory graphics on a Win10 (fully patched and up to date, drivers and all)  Lenovo M900 full tower workstation.

 I cleared windows/temp, windows/prefetch, Brave cache. Nothing helped like it did in the past. I will not clear my history/cookies or other stuff as I am in the middle of a major project and my history/cookies are a major time saver. I even downloaded a fresh copy of Brave and it installed as if my existing Brave wasn't even there (i.e. no questions/remarks about upgrading etc). I do have Brave Beta installed separately and it runs perfectly and has without issue for months. I don't use BAT features in the beta version.  I cannot remove the beta or alter it right now because, again, major project and I have separate client logins running in the beta for convenience and it a serious pain in the butt to switch profiles if stuck with one browser. I also have Firefox and Chrome (of course) installed but use those for other business and family accounts and for dev/content management stuff that doesn't run well in other browsers. Chromium based Edge is installed too though I hardly use it.  Brave (not the beta) is my system default browser for everything except the random Microsoft links that automatically ignore my preferences and only open in Edge.

I didn't have Crash reporting on until today so I'll see what happens over the coming days. Brave already sent 27 crash reports from the last two times I tried to open Brave in the last couple of hours. I'm assuming one for each failed open because I just keep clicking until the darn thing finally stays open. Yeah...it took 27 clicks over three separate user sessions just to get Brave successfully opened three times.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. I was using Davinci Resolve pretty heavily for a few hours when it happened this time but now it doesn't matter if I'm freshly rebooted or 10 hours into my day.
2. A reboot didn't solve the issue...it took even more icon clicks for Brave to finally open. I took a dinner break, came back and it took even more clicks to finally get Brave to stay open. Once open it is stable as can be except for quirks listed in paragraphs above.
3. Closing Brave, renaming the default user directory, reopening Brave worked for about five minutes before it crashed on the reopen so I restored my original user directory. (I'm now having to sign back into everything which is really 2FAnnoying. At least my history is still here).

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ee010000-5fc1-c604-0000-000000000000

**Comment by bsclifton** [comment]
Thanks for the detailed info, @psi4got - the crash ID you reported seems to be tied to an intentional crash (ex: what happens if you visit chrome://crash). I'm not sure how else this would get triggered?
```
[ 00 ] content::internal::CrashIntentionally
[ 01 ] content::HandleChromeDebugURL
[ 02 ] content::RenderFrameImpl::HandleRendererDebugURL
[ 03 ] mojo::internal::Serializer<url::mojom::UrlDataView,GURL>::Deserialize
[ 04 ] content::mojom::FrameNavigationControlStubDispatch::Accept
[ 05 ] base::internal::OperationsController::TryBeginOperation
[ 06 ] cc::RollingTimeDeltaHistory::Percentile
[ 07 ] blink::scheduler::MainThreadSchedulerImpl::CreateTraceEventObjectSnapshotLocked
[ 08 ] blink::scheduler::TraceableCounter<base::TimeDelta,&char const * const blink::scheduler::TracingCategoryName::kDebug>::Trace
[ 09 ] base::debug::ScopedLockAcquireActivity::ScopedLockAcquireActivity
[ 10 ] blink::scheduler::MainThreadSchedulerImpl::ComputeCurrentUseCase
[ 11 ] mojo::core::RequestContext::~RequestContext
[ 12 ] blink::scheduler::StateTracer<&char const * const blink::scheduler::TracingCategoryName::kInfo>::TraceImpl
[ 13 ] base::internal::flat_tree<aura::Window *,std::__1::pair<aura::Window *,aura::DefaultWindowOcclusionChangeBuilder::OcclusionData>,base::internal::GetKeyFromValuePairFirst<aura::Window *,aura::DefaultWindowOcclusionChangeBuilder::OcclusionData>,std::__1::less<void>>::find<aura::Window *>
[ 14 ] mojo::internal::ValidateContainer<mojo::internal::Array_Data<char>>
[ 15 ] blink::scheduler::TraceableState<base::Optional<blink::scheduler::MainThreadSchedulerImpl::TaskDescriptionForTracing>,&char const * const blink::scheduler::TracingCategoryName::kInfo>::Trace
[ 16 ] apps::mojom::internal::Publisher_OpenNativeSettings_Params_Data::Validate
[ 17 ] mojo::internal::ValidateStruct<blink::mojom::internal::AffectedFrame_Data>
[ 18 ] extensions::mojom::internal::GuestView_CreateMimeHandlerViewGuest_Params_Data::Validate
[ 19 ] mojo::internal::ValidateRequestGeneric
[ 20 ] base::sequence_manager::internal::SequenceManagerImpl::NotifyWillProcessTask
[ 21 ] base::WeakPtrFactory<
[ 22 ] mojo::InterfaceEndpointClient::HandleValidatedMessage
[ 23 ] mojo::MessageDispatcher::Accept
[ 24 ] IPC::`anonymous namespace'::ChannelAssociatedGroupController::AcceptOnProxyThread
[ 25 ] base::sequence_manager::internal::SequenceManagerImpl::NotifyDidProcessTask
[ 26 ] mojo::Message::Message
[ 27 ] IPC::`anonymous namespace'::ChannelAssociatedGroupController::AcceptSyncMessage
[ 28 ] base::TaskAnnotator::RunTask
[ 29 ] base::sequence_manager::internal::SequenceManagerImpl::SelectNextTask
[ 30 ] IPC::`anonymous namespace'::ChannelAssociatedGroupController::Accept
[ 31 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl
[ 32 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork
[ 33 ] base::MessagePumpDefault::Run
[ 34 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run
[ 35 ] base::internal::WeakPtrFactoryBase::WeakPtrFactoryBase
[ 36 ] base::ThreadLocalStorage::Slot::Get
[ 37 ] base::RunLoop::Run
[ 38 ] content::RendererMain
[ 39 ] base::FeatureList::InitializeFromSharedMemory
[ 40 ] base::FeatureList::RegisterExtraFeatureOverrides
[ 41 ] ChromeMainDelegate::RunProcess
[ 42 ] base::HighResolutionTimerManager::HighResolutionTimerManager
[ 43 ] content::ContentMainRunnerImpl::Run
[ 44 ] service_manager::Main
[ 45 ] MainDllLoader::Launch
[ 46 ] DllMain
```

**Comment by bsclifton** [comment]
For a quick sanity check- do you have sync enabled?  After launching, please visit brave://flags/#brave-sync and if it's enabled, please disable this setting

Please let us know! Thanks

**Comment by psi4got** [comment]
Hi Brian,

Sync was in 'Default' but, to be sure, I set it to 'disabled'.

Over the weekend Brave had another episode. 28 clicks to finally get it to
open. I turned off Brave Rewards/Brave Ads and, while it didn't eliminate
the problem, Brave seems to be opening normally most of the time. There is
an occasional multi-click to open but nothing as severe as before. I
haven't tested turning Brave Rewards/Ads back on again to see if the
'opening' problem gets worse as I have 16 hours of video editing to finish
before Wednesday. I'll test it later and I'm willing to try other stuff but
I may not respond immediately this week.

Thank you,
Patrick

**Comment by bsclifton** [comment]
@psi4got thanks for checking Patrick 😄 If you had Sync set to default, that would be disabled- which is good. I think there's another problem happening here. There are some other similar reports where Brave is crashing immediately and it can be difficult to get it to launch. Will look more into this

**Comment by rebron** [comment]
Hi @psi4got /Patrick Are you still seeing crashes and experiencing issues opening Brave with 1.13.82, our latest version in release. We addressed several crashes with the past couple of releases. And, hope your editing project went well!

**Comment by psi4got** [comment]
Hi.
Thank you for the follow up and, yes, the project this summer was awesome.
Brave is stable again! I even turned Rewards back on about two weeks ago
with no weird repercussions. I did intend to let you know that things
stabilized about a month ago(?) but things got busy and as we all know when
something is working (in this case Brave) we tend to forget to say thank
you.  Thank you for all the hard work you folks do to make Brave better and
better. I recommend it to everyone.

**Comment by rebron** [comment]
@psi4got Great to hear about things working again and that your project went well. I'll close this one out then and thanks for spreading the word. We really appreciate it.
