### ISSUE TITLE
Default enabled sync type set to Bookmarks only

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#10775]
per request on slack from @jsecretan 

Users will only see bookmark enabled when new sync chain created. More types can be enabled in `brave://settings/braveSync/setup` if users want to sync more than bookmarks

**Comment by LaurenWags** [comment]
Android issue - https://github.com/brave/brave-browser/issues/10997

**Comment by btlechowski** [comment]
`QA/Blocked` on test plan from https://github.com/brave/brave-core/pull/6104

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6104
Verified only Bookmarks are enabled after sync creation
![image](https://user-images.githubusercontent.com/34715963/89460949-73a6b880-d76b-11ea-8b63-2e946faf7515.png)

Verified the sync settings are preserved after restart
![image](https://user-images.githubusercontent.com/34715963/89460569-c5027800-d76a-11ea-9ca2-6e2fa6597523.png)

Verified only Bookmarks are enabled after sync reset
![image](https://user-images.githubusercontent.com/34715963/89460651-e95e5480-d76a-11ea-80c7-cc4dfd84ead7.png)
