### ISSUE TITLE
[Android] Bytecode patch is not applied to SearchEngineAdapter in release

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#10773]
## Description 
There is crash when try open Search engine options.
```
2020-07-16 14:44:26.580 6321-6321/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser, PID: 6321
    java.lang.NoSuchMethodError: No super method getPermissionsLinkMessage(Ljava/lang/String;)I in class Ln51; or its super classes (declaration of 'n51' appears in base.apk)
```

## Steps to reproduce 

   1. Try open Search engine options
   2. It crashes

## Actual result 
It crashes

## Expected result
No crashes

## Issue happens on 
   - Current Play Store version? no
   - Beta build? no

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.13.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build
- Verified no crash when opening search settings
- Verified changing search engine doesn't cause any crash 
------------
Verification passed on Samsung Tab A with Android 10 running 1.13.81 x64 build
- Verified no crash when opening search settings
- Verified changing search engine doesn't cause any crash
