### ISSUE TITLE
Downgrade version

### ISSUE THREAD

**Issue by sagaardu** [brave/brave-browser#10786]
## Description 

Since the last update, the browser works really bad, it does not restore the tabs that were open before closing, sometimes you have to give it twice to open it, if you give the option to restore the tabs it does not.

In short, the browser has become very unstable and I would like to return to a previous version. How can I do it?

## Steps to Reproduce

   1. Close browser 
   2. open browser
   3. tabs no restore

## Actual result:
tabs no restore

## Expected result:
tabs restore

## Reproduces how often: 
always

## Brave version (brave://version info)
Versión 1.11.97 Chromium: 84.0.4147.89 (Build oficial) (64 bits)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  I don´t know
- Can you reproduce this issue with the dev channel?  I don´t know
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? no, chrome work well

**Comment by Martina-Neumayer** [comment]
@sagaardu Well.. downgrade depends on your system. They are few different ways to do this.

**Comment by cjwijtmans** [comment]
I have had lost my open tabs a few times but only during upgrades and it has had happened to me a few stable versions before, i dont think a rollback will help you.

**Comment by sagaardu** [comment]
never before had problems until the last update

Can you tell me how the downgrade would be carried out?

**Comment by Martina-Neumayer** [comment]
@sagaardu Well.. some problems can occure because this latest update is a major one with lots of changes. And it is possible that something goes wrong. As by every update. There always is a bit of risc.

Solution is very simple: do a backup before someting bad happen.

To make an description how to downgrade the browser firstly we need to know what operating system you're using.

Or just go to the releases page, pick some oldest Brave version depending on your system and instal it.
Off course first you need to uninstall the previous one.

Releases page is here:
https://github.com/brave/brave-browser/releases

**Comment by bsclifton** [comment]
If you're having specific problems @sagaardu, I'm curious if it's related to your profile. You can try backing up / moving your profile out of the way

The profile directory will be in one of the following places:
- `%USERPROFILE%\AppData\Local\BraveSoftware\Brave-Browser\` on Windows
- `~/.config/BraveSoftware/Brave-Browser/` on Linux
- `~/Library/Application Support/BraveSoftware/Brave-Browser/` on macOS

You can basically move that folder out of the way (ex: name it `Brave-Browser2`) and you'll get a fresh profile which should be working fine. You can always go back to the old profile which has problems and export your bookmarks / saved passwords / etc and import into a new profile

Going back to an old version could corrupt the profile files. SQLite is used for a lot of items (cookies, autofill, etc) and between versions the schema is upgraded. Going back will cause a problem which can cause corruption.  However, if you wanted to use an older version of Brave, you can create a new profile directory and you should be fine (although, it's going to try and upgrade itself)

Please try and see if the issues you're seeing are happening on a new profile. We can use this issue to try and troubleshoot the problem. I'm going to close as I've given some good information. @Martina-Neumayer shared a good way to find older releases - but unless you block updates (not recommended) it'll upgrade itself
