### ISSUE TITLE
[Desktop] Enable ScrollToTextFragment

### ISSUE THREAD

**Issue by Inesicen** [brave/brave-browser#10787]
Make ScrollToTextFragment [optional](8342) for those who accept the [alleged/dubious privacy implications](https://github.com/WICG/scroll-to-text-fragment/issues/76) and want to use the feature anyway.

**Comment by rebron** [comment]
Marking this as wontfix as we don't plan on doing any work here including surfacing UI for it. This looks like a good candidate as an extension for those who want it.

**Comment by PolicyPuma4** [comment]
> Marking this as wontfix as we don't plan on doing any work here including surfacing UI for it. This looks like a good candidate as an extension for those who want it.

It's really disappointing that this is the stance Brave has on this issue. Removing useful features with not even a flag to enable them is not something I can stand by myself.

**Comment by Redsandro** [comment]
There are hundreds of useful flags in `brave://flags/` and this one in particular is a good example of something that should be handled by the browser. No one wants this moved to a _third party extension_ that would need the _permission to read and change every page you visit_. It's a security hazard waiting to happen.

Making an upstream feature opt-in: Good.
Removing an upstream feature altogether: Bad.

**Comment by fdavis99** [comment]
If you desire this option please upvote [#42393](https://github.com/brave/brave-browser/issues/42393)
