### ISSUE TITLE
Log important events in db

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10781]
Right now users tells us that something happen, but we don't if this is because we have a bug or user did some actions that triggers this at some point

To address this we should start logging important events in db so that we can see that for example user turned AC ON at time X and AC was then triggered at time Y.

We should create new table `event_log`, which would have fields:
- event_id string (guid)
- name string
- value string
- created_at timestamp

Things to log:

- [x] all state changes (so every time that we change state value; state = preference). Skip:
  - full recovery seed (just save first two bytes as sum)
  - external wallet
  - parameters
- [x] ac triggered
- [x] uphold wallet connected
- [x] uphold wallet status changed to verified
- [x] uphold wallet disconnected
- [x] recurring contribution added
- [x] recurring contribution removed
- [x] db migrated to new version
- [x] state migrated to new version
- [x] ad grants transfered

This should also be displayed on internals page.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.14.67 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
Revision	94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6383
 - Confirmed on Event logs tab of brave://rewards-internals there was an entry for `ac.enabled` set to 1 initially
 - After toggling AC off and refreshing brave://rewards-internals, confirmed there was a new entry for `ac.enabled` which was now set to 0
 - Compared to `Preferences` file to confirm this file reflects that AC is not enabled also
 - Confirmed AC setting is retained on browser restart

<img width="1194" alt="eventlogss1" src="https://user-images.githubusercontent.com/28145373/91590896-0d582480-e92a-11ea-81e8-96981256022a.png">

<img width="320" alt="eventlogss2" src="https://user-images.githubusercontent.com/28145373/91590901-0fba7e80-e92a-11ea-9a7e-ea2e7d53070f.png">


Additional tests done:
 - Spot checked values from Event logs tab on brave://rewards-internals in comparison against the `Preferences` file to confirm they matched
 - Modified each of the following items individually and confirmed a new entry was added to the Event logs tab of brave://rewards-internals for each one:
   - changed Monthly Payment value in Auto-Contribute pane
   - changed Monthly Payment value in Auto-Contribute settings
   - changed Minimum page time before logging a visit
   - changed Minimum visits for publisher relevancy
   - unchecked/checked Show non-verified sites in list
   - unchecked/checked Allow contribution to videos
   - removed recurring tip from Monthly Contributions pane
   - unchecked/checked Reddit in Tips settings
   - unchecked/checked Twitter in Tips settings
   - unchecked/checked GitHub in Tips settings
   - restored a wallet (multiple new entries on Event logs tab of brave://rewards-internals for this)
   - claimed Ad grant, connected KYC'd uphold account, confirmed Ad grant moved to Uphold (multiple new entries on Event logs tab of brave://rewards-internals for this)
   - disconnected from Uphold (manually via brave://rewards), then reconnected
   - disconnected from Uphold (manually via panel), then reconnected
   - disconnected from Uphold (manually via Uphold settings on sandbox.uphold.com), then reconnected
   - restored a wallet with user funds, connected KYC'd Uphold account, confirmed user funds moved to Uphold (multiple new entries on Event logs tab of brave://rewards-internals for this)
   - added/updated/removed recurring tip from panel
   - triggered AC
- Upgrade check 1
   - Installed 1.13.x, enabled Rewards
   - Connected KYC'd Uphold wallet
   - toggled AC off
   - deselected 2 of the options in Tip settings
   - set up 2 recurring tips
   - Closed 1.13.x, renamed profile to Dev
   - Launched with 1.14.x
   - Confirmed Event logs tab on brave://rewards-internals page
   - Confirmed `promotion_corrupted_migrated2`, `version`, `wallet.seed`, wallet.payment_id`, `enabled`, `creation_stamp`, `ac.next_reconcile_stamp`, `ac.enabled`, and `database_migrated` are listed (per https://github.com/brave/brave-core/blob/master/vendor/bat-native-ledger/src/bat/ledger/internal/state/state_migration_v5.cc)
   - Confirmed other changes made in 1.13.x are retained by checking on brave://rewards page. 
<img width="795" alt="Screen Shot 2020-08-28 at 12 07 21 PM" src="https://user-images.githubusercontent.com/28145373/91590955-25c83f00-e92a-11ea-9867-a6e229f81fd2.png">

- Upgrade check 2
   - Installed 1.13.x, enabled Rewards
   - modified some AC settings
   - Closed 1.13.x, renamed profile to Dev
   - Launched with 1.14.x
   - Confirmed Event logs tab on brave://rewards-internals page
   - Confirmed `promotion_corrupted_migrated2`, `version`, `wallet.seed`, wallet.payment_id`, `enabled`, `creation_stamp`, `ac.next_reconcile_stamp`, `ac.enabled`, and `database_migrated` are listed.
   - Confirmed other changes made in 1.13.x are retained by checking on brave://rewards page.
- Upgrade check 3
   - Installed 1.13.x, enabled Rewards
   - disabled Rewards
   - Closed 1.13.x, renamed profile to Dev
   - Launched with 1.14.x
   - Confirmed Rewards still off
   - Confirmed unable to see Event logs tab on brave://rewards-internals page
- Logged follow up issue https://github.com/brave/brave-browser/issues/11497
