### ISSUE TITLE
Disable flash in Tor Mode

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1078]
Was already implemented in `browser-laptop` with https://github.com/brave/browser-laptop/issues/13396

## Test plan
1. Open a new TOR PT
2. Visit http://homestarrunner.com/main1.html
3. Should show flash placeholder 
4. Right click shouldn't bring up context menu to allow flash to run
5. Enable flash globally
6. Repeat steps 2 and 3
7. Should still show flash placeholder and not context menu option should not show

since they are not guaranteed to use proxy settings 

related: https://bugs.chromium.org/p/chromium/issues/detail?id=163116

**Comment by diracdeltas** [comment]
Widevine should also be disabled in Tor mode. should that be combined with this or do people prefer separate issues?

**Comment by yrliou** [comment]
The test plan in the description is for browser-laptop.
Please see the test plan specified in https://github.com/brave/brave-core/pull/624.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified with test plan from https://github.com/brave/brave-core/pull/624
* Verified STR from description
