### ISSUE TITLE
[Desktop] "Import bookmarks now.." doesn't appear as link under NTP using light theme.

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#10798]
## Description 

Because now we're enabling the `Bookmark Toolbar` via the NTP even if there's no bookmarks as per https://github.com/brave/brave-browser/issues/10450, the `Import bookmarks now..` doesn't appear as a clickable link on the default theme. Looks fine when using the dark theme as per https://github.com/brave/brave-browser/issues/10450#issuecomment-660261116.

## Steps to Reproduce

   1. launch `1.12.x` (using `1.12.92 CR: 84.0.4147.89` this instance)
   2. open a NTP and you'll notice that `Import bookmarks now..` doesn't appear clickable

## Actual result:

<img width="1234" alt="Screen Shot 2020-07-17 at 11 40 13 PM" src="https://user-images.githubusercontent.com/2602313/87844119-26c87400-c888-11ea-945d-3afbee2a28c8.png">

## Expected result:

Should appear as a clickable link. Currently not obvious you can click it unless you've used the feature before.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.15.6 (Build 19G73)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron. Should be fixed before we release `1.12.x` as we're enabling the toolbar via https://github.com/brave/brave-browser/issues/10450.

**Comment by LaurenWags** [comment]
Reproduced w/ macOS Mojave 10.14.6 x64.

`Import bookmarks now...` text does not appear as a link however clicking on it does open brave://settings/importData.

<img width="651" alt="Screen Shot 2020-07-20 at 7 37 10 AM" src="https://user-images.githubusercontent.com/28145373/87933776-db66bf00-ca5b-11ea-99ce-cb7f885ef6bd.png">

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

**Comment by simonhong** [comment]
This only happens with Light theme. and the reason is the contrast ratio between toolbar color and link color is lower than chromium's minimum readable contrast ratio(`4.5f`) 
To fix this, I'll remove contrast ratio check from bookmark instruction view.
Let me know if we want to adjust our link color. cc @karenkliu 
![image](https://user-images.githubusercontent.com/6786187/88001775-e5f88580-cb3b-11ea-9557-c0617ea9753b.png)

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows 10 x64 - 1.12.94

**Light theme**

![image](https://user-images.githubusercontent.com/38657976/88176308-aff2f880-cc44-11ea-9cc0-3305f94d5d2a.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.99 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS


Light colors


![image](https://user-images.githubusercontent.com/34715963/88387256-66c0b700-cdb2-11ea-9f7e-8353ce98c560.png)|![image](https://user-images.githubusercontent.com/34715963/88387273-6d4f2e80-cdb2-11ea-83f1-6c8572b1ddd4.png)|![image](https://user-images.githubusercontent.com/34715963/88387309-79d38700-cdb2-11ea-8765-4905936f4d5c.png)
-- | -- | --

Dark colors

![image](https://user-images.githubusercontent.com/34715963/88387382-9ec7fa00-cdb2-11ea-8f7f-434afd710947.png)|![image](https://user-images.githubusercontent.com/34715963/88387394-a5ef0800-cdb2-11ea-974b-7326ee6a22dc.png)|![image](https://user-images.githubusercontent.com/34715963/88387422-b0a99d00-cdb2-11ea-9aa6-90eb2c452918.png)
-- | -- | --


Custom theme
![image](https://user-images.githubusercontent.com/34715963/88387744-6e349000-cdb3-11ea-87e1-94c34fb11d7e.png)
