### ISSUE TITLE
[Desktop] Fix signature tor-client signature failure on macOS Catalina (again)

### ISSUE THREAD

**Issue by oleyka** [brave/brave-browser#10796]
##  Description 

The same ussie as we saw in https://github.com/brave/brave-browser/issues/7987 is back again on OS X Catalina 10.15.6.

## Steps to Reproduce and Actual Result

1. Upgrade OS X Catalina from 10.15.5 to 10.15.6.
2. Observe an error when trying to use a Tor window:

![Screen Shot 2020-07-17 at 4 09 PM](https://user-images.githubusercontent.com/3523421/87837759-83586e80-c849-11ea-958e-91c514b8e92a.png)

3. Observe "No internet" screen in the Tor window.

## Expected Result

Connect to Tor and continue using the browser in Tor mode.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave | 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.15.6 (Build 19G73)
JavaScript | V8 8.4.371.19
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

## Additional information

Downgrading Brave to an earlier version doe snot resolve the issue:

Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}

**Comment by jumde** [comment]
Thanks for the report @oleyka - Looking into this now.

**Comment by jumde** [comment]
Hi @oleyka - We're not able to reproduce this issue on 10.15.6. Are you still running into this issue? If so, can you please share the outputs of the following commands:

1. Outputs the `shasum` of the tor binary: 
```
shasum -a 512 ~/Library/Application\ Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0
```

2. Checks if the binary passes the notarization requirements:
```
codesign --test-requirement="=notarized" --verify --verbose  ~/Library/Application\ Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0
```

Thanks for all your help.

**Comment by oleyka** [comment]
Sure, here's the output:

```
@:~$ shasum -a 512 ~/Library/Application\ Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0
7aeac17d69e78aa01217bd4ea75f83394acd58136db9c3c425fb4764968a8141e741f36db7cd2aca9684b0f0bb3945420aebf4ee86e4239d0aa34b2a618addff  /Users/oley/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0
@:~$ codesign --test-requirement="=notarized" --verify --verbose  ~/Library/Application\ Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0
/Users/oley/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0: valid on disk
/Users/oley/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0: satisfies its Designated Requirement
test-requirement: code failed to satisfy specified code requirement(s)
```

**Comment by rebron** [comment]
cc: @darkdh

**Comment by jumde** [comment]
Hi @oleyka, just wanted to check if you are still running into this issue. Thanks!

**Comment by oleyka** [comment]
Hey @jumde , thank you for checking back on this!

Since I filed the ticket, my OS X has received a supplemental update, 10.15.6 (19G2021), and I am now able to use Tor. I tried it with both the older version of the browser (as reported), and with the latest version, `1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)`.

Please feel free to close the issue.

**Comment by oleyka** [comment]
```$ codesign --test-requirement="=notarized" --verify --verbose  ~/Library/Application\ Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0
/Users/oley/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0: valid on disk
/Users/oley/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0: satisfies its Designated Requirement
/Users/oley/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.12/tor-0.3.5.11-darwin-brave-0: explicit requirement satisfied
```

**Comment by jumde** [comment]
Thanks for the update @oleyka!
