### ISSUE TITLE
[Desktop] Fingerprinting and Ads/Trackers Global Settings keeps reverting

### ISSUE THREAD

**Issue by AsadAlrafidain** [brave/brave-browser#10790]
## Description 

Every time fingerprinting global settings is changed to block all attempts, it'll revert back to block cross site fingerprinting

edit: it seams the problem also affect ads/trackers setting too

## Steps to Reproduce

   1. open global shield defaults
   2. change fingerprinting settings to block all attempts
   3. change ads/trackers setting to agressive
   4. check back after a while to find the fingerprinting setting has reverted back to block only cross-site fingerprinting(standard in newer releases), and the ads/trackers setting reverted back to standard

## Actual result:

the setting change is temporary

## Expected result:
The setting change should be permanent

## Reproduces how often: 

I have a fresh install on another device and it doesn't have this issue...however, it seams that "block all fingerprinting attempts" is the default setting now in new versions of brave browser, so the setting was set from the get-go

## Brave version (brave://version info)

Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Windows 10 OS Version 1909 (Build 18363.900)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by AsadAlrafidain** [comment]
It seams the issue is fixrd after the last update....closing the isue.

**Comment by AsadAlrafidain** [comment]
It seams the issue is still present even after updating...

Brave Browser Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Comment by rebron** [comment]
Hi @AsadAlrafidain We've updated the fingerprinting settings, can you let us know if you're still having issues with our current release, 1.13.82. 

The default setting for Fingerprinting is now "Fingerprinting blocking - standard". Strict and disabled are the other two options. Let us know if you set Fingerprinting to Strict if it reverts back to Standard.

**Comment by diracdeltas** [comment]
another report of this in https://github.com/brave/brave-browser/issues/11585

**Comment by AsadAlrafidain** [comment]
I also have the ads/trackers setting reverting back to default beside the fingerprinting setting, and even after updating to release 1.13.82, both these settings still revert back to default (standard)

**Comment by rebron** [comment]
@AsadAlrafidain Wanted to rule out whether you had "Clear Data on Exit" enabled as that would revert the settings.

**Comment by AsadAlrafidain** [comment]
@rebron no I don't have "Clear Data on Exit" enabled

**Comment by rebron** [comment]
@AsadAlrafidain Wanted to follow-up to see if you're still encountering this issue with our latest 1.41.100. 
Related issue https://github.com/brave/brave-browser/issues/23304 was fixed in 1.41.96.

**Comment by rebron** [comment]
Close as duplicate of https://github.com/brave/brave-browser/issues/23304
