### ISSUE TITLE
[Android] Update reward flag for status

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#10795]
## Description 
Update rewards code based on https://bravesoftware.slack.com/archives/CB0KCRCQN/p1594836766343800

## Steps to reproduce 

   1. Enable rewards from the panel
   2. Open SI New tab page

## Actual result 
NTP with SI doesn't show bottom banner

## Expected result
NTP with SI should show bottom banner for the first time

## Issue reproduces how often 
Often

## Issue happens on 
   - Current Play Store version?
   - Beta build? Yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.11.100 x64 build
- Verified bottomsheet is shown on a tab with a sponsored image
   <img width=450 src=https://user-images.githubusercontent.com/17010094/88387686-ea76a580-cdaa-11ea-941d-d60ec0858c20.png>
- Verified bottomsheet is shown only on the first sponsored image tab
- Verified clicking on `Learn more` in bottom sheet brings up the info modal 
----------------
Verification passed on OnePlus 6T with Android 10 running 1.11.100 x64 build
- Verified bottomsheet is shown on a tab with a sponsored image
   <img width=300 src=https://user-images.githubusercontent.com/17010094/88387706-f6626780-cdaa-11ea-9ea8-b32c6983e6a8.png>
- Verified bottomsheet is shown only on the first sponsored image tab
- Verified clicking on `Learn more` in bottom sheet brings up the info modal
