### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by nosht82** [brave/brave-browser#10793]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.11.97  Chromium: 84.0.4147.89
Operating System: Windows NT 10.0.19041

URL (if applicable) where crash occurred: Crashes on opining Brave Browser.

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.Opining brave as a standard user.  (If ran with elevated privileges it doesn't crash.)

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/a4070000-5fc1-c604-0000-000000000000

**Comment by nosht82** [comment]
The only thing that changed is from it working to not working is applying Windows updates KB4565503, KB4565627, KB4566785
It's windows 10 2004

**Comment by bsclifton** [comment]
@nosht82 do you have sync enabled? After launching, please visit brave://flags/#brave-sync and disable this setting

If so - Sync v1 is going away in our next major release - 1.12.x in favor of a completely new fully featured system (basically, what you get with Chrome/Chromium by default). With the next release, you'll have to create a new sync group - but you'll also have access to all the sync types (autofill data, bookmarks, passwords, etc)

Please let us know - thanks! 😄

**Comment by nosht82** [comment]
Yes. It was enabled. after disabling it, it still didn't work but as of today it is working.
Thank you.
