### ISSUE TITLE
Contents of a new tab should be configurable

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1079]
## Description
In `browser-laptop`, we allow the user to specify (under `General`) what happens when a new tab is opened. They can choose one of a few options:
![screen shot 2018-09-10 at 12 40 30 am](https://user-images.githubusercontent.com/4733304/45283277-48899080-b492-11e8-8cf1-60c3a82a8e88.png)

We should consider supporting the following options:
- Dashboard (our current behavior; which shows the picture, tiles, etc)
- Home page (user's home page)
- Default search engine
- Blank page
- Chrome's default new tab (so that users can take advantage of extensions like [Speed Dial](https://chrome.google.com/webstore/detail/speed-dial/ejbjamhkdedinncaeiackcdehpccoejm?hl=en-US))

**Comment by bsclifton** [comment]
cc: @davidtemkin @rebron for prioritization

**Comment by rebron** [comment]
Settings UI and options for this issue is here: https://github.com/brave/brave-browser/issues/960.

**Comment by bsclifton** [comment]
@rebron awesome- totally forgot about that 😄
