### ISSUE TITLE
Provide better documentation for onboarding contributors

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#108]
clifton [2:24 PM]
I think having enough documentation to jump in would be good- the format for browser-laptop is pretty nice

a lot of it could be copied- like our review process, things to consider before submitting a PR, etc
the templates could be done for issues and PRs, similar to browser-laptop

garrett [4:44 PM]
1. Reliable documentation for successfully setting up development environment on each major platform (Windows currently has problems, I filed some issues)
2. As much automated PR validation as possible (tests pass, lint, etc.) helps tip the balance in favor of “external contributors make useful contributions, and have a good experience doing so” as opposed to “external contributors burn maintainer’s time with manual testing and repetitive reviews, and get annoyed because their contributions languish or have a lot of back-and-forth in review”
3. Optional: code ownership system (e.g. OWNERS or Mozilla modules) for Brave code, so contributors know who to ask for help/review

**Comment by bsclifton** [comment]
TODO: revisit me soon! Some information captured in https://github.com/brave/brave-browser/issues/774#issuecomment-508584820
