### ISSUE TITLE
[Desktop] Dev-tools causing crashing with STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Shadow505** [brave/brave-browser#10805]
## Description 

I am having the exact same issues that has been reported at https://community.brave.com/t/devtools-crash-any-page/123939 but has not received any response. Apparently the issues still exists.

## Steps to Reproduce

1. Launch Brave
2. Visit any website, for example https://stackoverflow.com/
3. Open DevTools
4. Change any CSS property
5. Close DevTools
6. Open DevTools

## Actual result:

All tabs from the same domain (e.g. stackoverflow.com) are crashing with _STATUS_ACCESS_VIOLATION_ after step 6.

## Expected result:

Open the dev-tools

## Reproduces how often: 

Everytime.

## Brave version (brave://version info)

Brave: 1.11.97 Chromium: 84.0.4147.89
Revision: 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS: Windows 10 OS Version 2004 (Build 19041.329)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes. (1.11.97)
- Can you reproduce this issue with the beta channel? Not tested.
- Can you reproduce this issue with the dev channel?  Not tested.
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **Yes, it look like it does!**
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?  No.

**Comment by bsclifton** [comment]
Was easily able to reproduce with the steps - thanks for the report, @Shadow505 😄 Verified this is not crashing in Chrome- my guess is that it's related to our recent Chromium 84 upgrade

cc: @mkarolin @iefremov

**Comment by iefremov** [comment]
This is actually pretty popular crash - it is in top10 for renderer process (and even higher without OOM crashes). Similar instances can be found e.g. like this
https://brave.sp.backtrace.io/p/brave/triage?filters=((callstack%2Ccontains%2CKeyValuePairKeyExtractor))&aggregations=((channel%2Cdistribution%2C3)%2C(ptype%2Chead)%2C(uname.sysname%2Cdistribution%2C3))

**Comment by bsclifton** [comment]
I believe this was fixed with https://github.com/brave/brave-browser/pull/10951 - which we released yesterday

@Shadow505 could you try again? Please let us know!
