### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by yakzazazord** [brave/brave-browser#10802]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.11.97  Chromium: 84.0.4147.89
Operating System: Windows NT 10.0.17134

URL (if applicable) where crash occurred:
no specific url, it crashes at startup.
Can you reproduce this crash?
Happens everytime when I try to launch brave, it can crash 2 times in a row but the third time I try to open Brave it opens.
What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
Nothing, just trying to open Brave.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/270c0000-5fc1-c604-0000-000000000000

**Comment by bsclifton** [comment]
@yakzazazord do you have sync enabled? After launching, please visit brave://flags/#brave-sync and disable this setting

Sync v1 is going away in our next major release - 1.12.x in favor of a completely new fully featured system (basically, what you get with Chrome/Chromium by default). With the next release, you'll have to create a new sync group - but you'll also have access to all the sync types (autofill data, bookmarks, passwords, etc)

Please let us know - thanks! 😄

**Comment by rebron** [comment]
@yakzazazord If you have a chance, can you update to our latest 1.13.82 and let us know if you're still experiencing a crash.
brave://settings/help to check for the update

**Comment by yakzazazord** [comment]
so far so good.
I'll open a new issue if the problem reoccurs.
