### ISSUE TITLE
[Desktop] Repurpose the global autoplay content setting so that it allows overriding the Chrome policy

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#10807]
Background: Previously Brave had its own autoplay system, based on a list, b/c Chrome's autoplay policy was crummy.  Now Chrome's policy is a lot better than it was, so Brave has removed its custom system and just falls back on Chrome's (https://github.com/brave/brave-browser/issues/9597, https://github.com/brave/brave-core/pull/5970, etc).

However, we still have the global "autoplay" content setting as a vestigial hold over from the previous system.  We should use it to allow users to still disable autoplay, if they don't like Chrome's new-and-improved system.

**Comment by pes10k** [comment]
If we don't do this, we should remove the autoplay content setting, to avoid confusion

**Comment by pes10k** [comment]
<img width="770" alt="Screen Shot 2020-07-18 at 8 13 25 PM" src="https://user-images.githubusercontent.com/76526/87866164-25a05100-c933-11ea-8bd2-0a9dadde7cf4.png">
FWIW, this is the autoplay content setting referred to above

**Comment by timkgh** [comment]
Always block is very valuable. Please make it work instead of removing it.

**Comment by pes10k** [comment]
Thanks @timkgh. Its useful for us to get a sense of this, so we know what to prioritize. No promises on a final decision, since theres a lot of high priority things on our plate, but its useful to know that its a feature folks would use

**Comment by umbraesoulsbane** [comment]
Just chiming in on this. This is a critical feature for me. Since this became an issue in Brave I have switched to Chrome Edge. I prefer Brave (especially mobile) but the lack of zero autoplay I only use it for a handful of cases.

**Comment by bsclifton** [comment]
Per @darkdh in https://github.com/brave/brave-browser/issues/9597#issuecomment-660584268
> Just verified
>
> per site autoplay setting works
> <img width="882" alt="Screen Shot 2020-07-18 at 21 14 24" src="https://user-images.githubusercontent.com/11330831/87866911-2ee1eb80-c93c-11ea-97b1-e3ef0e94bb0d.png">
>
> global autoplay setting doesn't work
> issue tracked here
> (https://github.com/brave/brave-browser/issues/10807)
> <img width="874" alt="Screen Shot 2020-07-18 at 21 16 35" src="https://user-images.githubusercontent.com/11330831/87866913-31dcdc00-c93c-11ea-96b2-12645b468f45.png">

**Comment by pes10k** [comment]
There are three related issues here:
1. The text incorrect on the global toggle: https://github.com/brave/brave-browser/issues/10810
2. The global setting doesn't seem to apply in most cases, for most users: https://github.com/brave/brave-browser/issues/10807
3. For some users / profiles, the site specific setting doesn't work (my profile, for example): https://github.com/brave/brave-browser/issues/10811

**Comment by wolfiejunk** [comment]
Agree with others that global autoplay off should be available and easy to access.  It is for us a very high value problem and we find ourselves more and more migrating away from Brave.  Simply... Global Autoplay Off  Yes/No

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.13.71 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6130

**Autoplay default setting options**
Allowed
![image](https://user-images.githubusercontent.com/34715963/90297669-92096400-de8f-11ea-866c-2c5a519649b5.png)
Blocked
![image](https://user-images.githubusercontent.com/34715963/90297741-cf6df180-de8f-11ea-8b07-ea9b8bd300b1.png)
Verified Polish translation

**Autoplay set default block**
Video is blocked
![image](https://user-images.githubusercontent.com/34715963/90297899-6fc41600-de90-11ea-908f-e04a4cfb9ae2.png)

**Autoplay default allow**
Video is player
![image](https://user-images.githubusercontent.com/34715963/90297957-a306a500-de90-11ea-8936-e37f1cfcd2b1.png)

**Autoplay blocked through the block list**
Video is blocked
![image](https://user-images.githubusercontent.com/34715963/90298019-d6e1ca80-de90-11ea-901e-c518f6338da9.png)

**Comment by hennrynusasatria** [comment]
Hi @btlechowski 

This Autoplay blocker does not work on this site:

https://inet.detik.com/security/d-5149755/sering-dibobol-ini-pembelaan-whatsapp?tag_from=wp_beritautama

I have turned the Global Autoplay Content Setting to "Blocked", but the video keeps autoplaying on the above site, can you help to check?

Thank you.
