### ISSUE TITLE
[Android] accessing sync from Settings causes crash (x86 only)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10819]
## Description 
When I access Sync from Settings, I get the "Unfortunately Brave has stopped" message. I get it 3x, and then the app relaunches. Then I get the prompt to allow Brave to take photos/video (I get this 3x as well).

Note - this does not reproduce for me on ARM device (Android 5). @srirambv could not reproduce on his device either.

## Steps to reproduce 

   1. Install `1.11.98`.
   2. Navigate to Settings
   3. Tap on Sync

## Actual result 
Crash. Note, sometimes after tapping on OK the prompt to allow photo/video comes up, but then the same "Unfortunately..." message pops up over top of it.
![androidcrash](https://user-images.githubusercontent.com/28145373/87952922-62299500-ca78-11ea-82f6-05c5b2eafb70.png)

![androidcrash2](https://user-images.githubusercontent.com/28145373/87952934-65248580-ca78-11ea-84c1-62f948162e30.png)

## Expected result
No crash, able to access sync UI

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no for 1.10.99
   - Beta build? yes, 1.11.98

## Device details
   - Install type (ARM, x86): x86
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 6
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Note - if you had a sync chain on 1.10.99 and upgraded, you still get the crash. You do not get prompted to allow photo/video though. But you still can't access sync info.

**Comment by AlexeyBarabash** [comment]
reproduced on x86 Nightly from GP `1.13.33`, but can't  reproduce on own-built `master` (x86_32), will try own built `master` (x86_64)

**Comment by samartnik** [comment]
It was fixed in the context of https://github.com/brave/brave-browser/issues/10915

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.11.102 BraveModernx86.apk
 * Verified STR from description
   * Confirmed no crash observed.
 * Verified scenario from https://github.com/brave/brave-browser/issues/10819#issuecomment-661095494
   * Confirmed no crash observed.
