### ISSUE TITLE
[Desktop] Description of default setting for autoplay is incorrect (says "ask")

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#10810]
With a new profile, the default setting for autoplay says "Ask when a site wants to autoplay media (recommended)".  This is incorrect, since Brave never asks / prompts about autoplaying.

<img width="1097" alt="Screen Shot 2020-07-18 at 9 32 32 PM" src="https://user-images.githubusercontent.com/76526/87867098-32767200-c93e-11ea-8055-88901d9b070a.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.13.71 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6130

**Autoplay default setting options**
Allowed
![image](https://user-images.githubusercontent.com/34715963/90297669-92096400-de8f-11ea-866c-2c5a519649b5.png)
Blocked
![image](https://user-images.githubusercontent.com/34715963/90297741-cf6df180-de8f-11ea-8b07-ea9b8bd300b1.png)
Verified Polish translation

**Comment by pirivan** [comment]
Autoplay blocking doesn't work for me when I visit the [CNN](https://www.cnn.com/) web site. All videos start right away.

My environment: Brave v1.13.82, macOS Catalina 10.15.6
My brave settings: Autoplay Blocked (off), Block list empty, Allow list empty
