### ISSUE TITLE
[Desktop] autocomplete w/o id in input field reported to act differently in Chrome and Brave

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#10813]
# Description 

<img width="845" alt="EdRHG4hUwAUL-TG" src="https://user-images.githubusercontent.com/831718/87879007-e5ce7d80-c9b5-11ea-9f91-8140227859cb.png">

Chrome will throw an error saying did you mean 'autoComplete' not 'autocomplete'.
It's reported that changing to camelcase works in Chrome but not in Brave. 
It's reported that adding id='first' will work for Brave

See https://twitter.com/Steviebaah/status/1284729998620758017

**Comment by rebron** [comment]
@bbondy can you add a priority label to this one? Is this dev-concern?
