### ISSUE TITLE
[Android] Add switch to use staging server for sync v2

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10817]
To make testing easier, it is required to add switch to Preferences => Developer options which would switch sync v2 from production server to staging server.

The way to verify: open brave://sync-internals and look on `Server URL` field.

It is `https://sync-v2.brave.com/v2` for production and `https://sync-v2.bravesoftware.com/v2` for staging.

**Comment by AlexeyBarabash** [comment]
See test plan at https://github.com/brave/brave-core/pull/6288 , so QA/Yes

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.14.19 x64 nightly build
- Verified able to enable sync staging via QA options
- Verified setting up staging sync server is reflected on `brave://sync-internals` under version info
![image](https://user-images.githubusercontent.com/17010094/89493450-197a1780-d7ac-11ea-9229-208c005360b4.png)
- Verified able to sync bookmarks between Desktop beta (launched using `--sync-url=https://sync-v2.bravesoftware.com/v2`)
- Verified bookmarks added on mobile is sync'd to desktop 
- Verified when creating a sync setup with QA preferences off for staging uses `sync.brave.com`
![image](https://user-images.githubusercontent.com/17010094/89493617-7249b000-d7ac-11ea-9b0d-be077ea2d6a2.png)

---------------
Verification passed on Samsung Tab A with Android 10 running 1.14.19 x64 nightly build
- Verified able to enable sync staging via QA options
- Verified setting up staging sync server is reflected on `brave://sync-internals` under version info
![image](https://user-images.githubusercontent.com/17010094/89559383-7c4fcb00-d80d-11ea-87c6-c1b7741c602f.png)
- Verified able to sync bookmarks between Desktop beta (launched using `--sync-url=https://sync-v2.bravesoftware.com/v2`)
- Verified bookmarks added on mobile is sync'd to desktop 
- Verified when creating a sync setup with QA preferences off for staging uses `sync.brave.com`
![image](https://user-images.githubusercontent.com/17010094/89559404-8671c980-d80d-11ea-8f50-d7af55ca4713.png)
