### ISSUE TITLE
[Desktop] For some profiles, site-specific autoplay settings are not respected

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#10811]
In a fresh profile, the global autoplay setting is not applied (see [#10807](https://github.com/brave/brave-browser/issues/10807)), but site specific ones are applied.

However, for some profiles, even setting a site-specific autoplay setting doesn't affect autoplay policy.  Specifically, when @pes10k sets autoplay=blocked for blick.ch, the video in the top left still autoplays.

![blick.ch set to autoplay=blocked](https://user-images.githubusercontent.com/76526/87867192-85045e00-c93f-11ea-80be-ec416b5e77ff.png)

![image in top left of blick.ch still autoplaying, despite site-specific content setting](https://user-images.githubusercontent.com/76526/87867199-8fbef300-c93f-11ea-87d6-985ef687a340.png)

**Comment by pes10k** [comment]
**Site engagement score for blick.ch**
<img width="852" alt="Site engagement score for blick.ch" src="https://user-images.githubusercontent.com/76526/87867284-399e7f80-c940-11ea-9b82-c2df2b723e71.png">

**Truncated media engagement scores in profile**
(blick.ch doesn't appear, but here are the top entries…)

| Media Engagement |  |
| --- | --- |
| Setting Name | Setting Value |
| Min Sessions | 20 |
| Lower Threshold | 0.2 |
| Upper Threshold | 0.3 |
| Record MEI data | Enabled |
| Bypass autoplay based on MEI | Enabled |
| Preload MEI data | Enabled |
| MEI for HTTPS only | Disabled |
| Autoplay disable settings | Disabled |
| Autoplay whitelist settings | Enabled |
| Unified autoplay (preference) | Enabled |
| Custom autoplay policy | Disabled |
| Autoplay Policy | document-user-activation-required |
| Preload version | 1.0.5.0 |

| Origin | Sessions | Sessions with playback | Last Playback | Is High | Score |
| --- | --- | --- | --- | --- | --- |
| https://www.youtube.com | 834 | 710 | 2020-07-18T00:48:42.016Z | Yes | 0.85 |
| https://mit.webex.com | 24 | 17 | 2020-07-13T17:03:03.464Z | Yes | 0.71 |
| https://www.netflix.com | 21 | 12 | 2020-05-30T00:09:12.679Z | Yes | 0.57 |
| https://soundcloud.com | 13 | 10 | 2020-07-16T05:51:16.735Z | Yes | 0.50 |
| https://thequietus.com | 22 | 8 | 2020-07-16T19:57:42.980Z | Yes | 0.36 |
| https://www.instagram.com | 12 | 6 | 2020-07-13T16:56:07.052Z | Yes | 0.30 |
| http://feckingbahamas.com | 9 | 5 | 2020-07-04T19:25:54.766Z | No | 0.25 |
| http://www.openculture.com | 10 | 4 | 2020-07-14T02:27:05.080Z | No | 0.20 |
| https://together.brave.com | 6 | 4 | 2020-07-15T14:31:12.513Z | No | 0.20 |
| https://www.escapistmagazine.com | 4 | 4 | 2020-04-09T04:12:54.549Z | No | 0.20 |
| https://twitter.com | 1022 | 178 | 2020-07-18T01:53:08.555Z | No | 0.17 |
| https://www.cnn.com | 13 | 3 | 2020-05-09T23:21:21.474Z | No | 0.15 |
| https://pitchfork.com | 584 | 80 | 2020-07-18T00:50:36.802Z | No | 0.14 |
| https://www.chicagoreader.com | 22 | 3 | 2020-07-06T17:53:07.556Z | No | 0.14 |
| https://melmagazine.com | 112 | 13 | 2020-07-18T19:35:26.607Z | No | 0.12 |
| https://anamanaguchi.bandcamp.com | 3 | 2 | 2020-07-08T05:30:21.722Z | No | 0.10 |
| https://catbamboo.bandcamp.com | 4 | 2 | 2020-05-13T02:26:50.677Z | No | 0.10 |
| https://cherrycherrybomb.bandcamp.com | 5 | 2 | 2020-06-11T01:15:48.037Z | No | 0.10 |
| https://deerhoof.bandcamp.com | 2 | 2 | 2020-06-02T20:43:02.455Z | No | 0.10 |
| https://djperromx.bandcamp.com | 2 | 2 | 2020-06-06T01:05:33.437Z | No | 0.10 |
| https://hausumountain.bandcamp.com | 3 | 2 | 2020-05-18T21:50:26.016Z | No | 0.10 |
| https://meet.google.com | 2 | 2 | 2020-04-14T16:00:13.531Z | No | 0.10 |
| https://mutants4nuclearwaste.bandcamp.com | 2 | 2 | 2020-07-06T17:55:22.434Z | No | 0.10 |
| https://remodrive.bandcamp.com | 2 | 2 | 2020-06-26T21:19:16.207Z | No | 0.10 |
| https://www.8notes.com | 2 | 2 | 2020-05-15T04:00:44.496Z | No | 0.10 |
| https://www.adultswim.com | 4 | 2 | 2020-05-04T02:31:17.594Z | No | 0.10 |
| http://jplayer.org | 4 | 1 | 2020-05-20T05:15:24.529Z | No | 0.05 |
| http://sheer-mag.com | 1 | 1 | 2020-05-12T05:16:36.993Z | No | 0.05 |
| http://www.yogawithcecily.com | 8 | 1 | 2020-05-23T02:39:37.588Z | No | 0.05 |
| https://99percentinvisible.org | 3 | 1 | 2020-06-08T20:27:25.050Z | No | 0.05 |

**Comment by timkgh** [comment]
Same issue here. I have an explicit block rule for `[*.]cnn.com` and the videos still play.

**Comment by pongraczi** [comment]
Still autoplay videos from:  
* https://24.hu  (example: https://24.hu/tech/2020/07/22/google-gmail-hitelesitett-email-logo/ just roll down)
* messenger.com still plays videos automatically
etc.

Verzió: 1.11.97 Chromium: 84.0.4147.89 (Hivatalos verzió) (64 bites)

**Comment by ryanbr** [comment]
Confirming youtube is have similar issues.

Setting Autoplay in Brave on youtube.com, won't stop the video from autoplaying (so won't allow click to play). Tested with Firefox, and Edge. Blocking autoplay in the settings on Youtube, will prevent autoplay of video.

Was reported https://community.brave.com/t/the-block-auto-play-option-is-not-blocking-videos-from-automatically-playing-anymore-also-the-switch-to-this-tab-button-isnt-working-all-the-time/163567/7

**Comment by pongraczi** [comment]
I do not know, how it supposed to work, but in my case, videos still playing automatically.  
* in [twitter](https://twitter.com/GretaThunberg?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1324439705522524162%7Ctwgr%5Eshare_3&ref_url=https%3A%2F%2Fcdn.embedly.com%2Fwidgets%2Fmedia.html%3Ftype%3Dtext2Fhtmlkey%3Dcb7145f1731b4c328f8e4d2201854ceaschema%3Dtwitterurl%3Dhttps3A%2F%2Ftwitter.com%2Fgretathunberg%2Fstatus%2F1324439705522524162image%3D)
* in news site (https://24.hu some random videos in articles, I had to disable by selector to get rid of stupid videos)

Linux, Version: 1.16.72 Chromium: 86.0.4240.183 (Official version) (64 bit)

Did I miss something? Shields are up, in 24.hu I set to agressive, nothing happened, video still playing.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.18.68 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
Reproduced the issue in 1.17.x
When Autoplay is `Blocked` globally, click on any videos does autoplay on youtube.com, there is no autoplay blocked indicator in the URL bar
![image](https://user-images.githubusercontent.com/38657976/100903238-a8453980-34eb-11eb-97c6-921ca24d7d1f.png)

When Autoplay is `Blocked` globally, videos does autoplay on https://www.blick.ch/, there is no autoplay blocked indicator in the URL bar
![image](https://user-images.githubusercontent.com/38657976/100903397-dc205f00-34eb-11eb-805c-93b709a0d01f.png)

- Verified the test plan from https://github.com/brave/brave-core/pull/6980
