### ISSUE TITLE
[Android] Implement infobar for Android sync v1 users to force recreate v2 chain

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10822]
Related PR brave/brave-core#5361.

Required to make similar to desktop b-c PR brave/brave-core#5804 to inform Android sync v1 users that sync v1 will be shut down and they need to create a new sync chain with sync v2.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.12.108 x64 build
- Verified on a clean install there is no notification shown about sync v2
- Verified upgrading from 1.11.105 with sync v1 enabled to 1.12.108, notification is shown immediately upon launch
![image](https://user-images.githubusercontent.com/17010094/89560286-b077bb80-d80e-11ea-9a5d-a0d0e00436f7.png)
- Verified clicking on `Begin Setup` loads sync settings page and asks to create a new one or join an existing one
- Verified post-upgrade, quit and relaunch doesn't show notification again
-----------------------
Verification passed on OnePlus 6T with Android 10 running 1.12.108 x64 build
- Verified on a clean install there is no notification shown about sync v2
- Verified upgrading from 1.11.105 with sync v1 enabled to 1.12.108, notification is shown immediately upon launch
![image](https://user-images.githubusercontent.com/17010094/89560451-e7e66800-d80e-11ea-97dc-13cfc96d3ca0.png)
- Verified clicking on `Begin Setup` loads sync settings page and asks to create a new one or join an existing one
- Verified post-upgrade, quit and relaunch doesn't show notification again
