### ISSUE TITLE
[Android] new publisher list (v4)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10836]
https://github.com/brave/brave-browser/issues/9502

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112

**Clean Install**
**Scenario 1**
- Verified on a clean install with KYC'd account connected, 
  - Able to only tip KYC'd accounts
  - Connected/Unverified doesn't get a tip when tipped instead goes into a pending state
  - Shows correct messaging for connected publishers 
  - Shows correct messaging for unverified publishers
  - Verified contributions only list KYC'd account tips and no tips sent to connected/unverified pubs are listed

**Scenario 2**
- Verified on a clean profile, visiting various types of publishers (GitHub, Reddit, Twitter, etc) shows correct publisher status and shows correct banner info 

**Upgrade Installs**
**Scenario 1**
- Verified upgrading from `1.11.x` to `1.12.112` removed all values from `server_publisher_info` and other `server_publisher_*` tables
- Verified `publisher_prefix_list` table is populated and contains raw binary data

**Scenario 2**
- Verified removing a publisher from DB and visiting on `1.11.x` doesn't show publisher status
- Verified upgrading to `1.12.112` and checking publisher status shows as verified 
- Verified publisher data is listed again under `server_publisher_info` table 

**Scenario 3**
- Verified on `1.11.x` with a KYC'd wallet, setting a publisher as connected shows it's not ready to receive funds 
- Verified upgrading to `1.12.112` and visiting the same publisher removes all message and shows the publisher as fully KYC'd 
- Verified publisher data is set to correct state in `server_publisher_info` table

-------------
Verification passed on Samsung Tab A with Android 10 running 1.12.112

**Clean Install**
**Scenario 1**
- Verified on a clean install with KYC'd account connected, 
  - Able to only tip KYC'd accounts
  - Connected/Unverified doesn't get a tip when tipped instead goes into a pending state
  - Shows correct messaging for connected publishers 
  - Shows correct messaging for unverified publishers
  - Verified contributions only list KYC'd account tips and no tips sent to connected/unverified pubs are listed

**Scenario 2**
- Verified on a clean profile, visiting various types of publishers (GitHub, Reddit, Twitter, etc) shows correct publisher status and shows correct banner info 

**Upgrade Installs**
**Scenario 1**
- Verified upgrading from `1.11.x` to `1.12.112` removed all values from `server_publisher_info` and other `server_publisher_*` tables
- Verified `publisher_prefix_list` table is populated and contains raw binary data

**Scenario 2**
- Verified removing a publisher from DB and visiting on `1.11.x` doesn't show publisher status
- Verified upgrading to `1.12.112` and checking publisher status shows as verified 
- Verified publisher data is listed again under `server_publisher_info` table 

**Scenario 3**
- Verified on `1.11.x` with a KYC'd wallet, setting a publisher as connected shows it's not ready to receive funds 
- Verified upgrading to `1.12.112` and visiting the same publisher removes all message and shows the publisher as fully KYC'd 
- Verified publisher data is set to correct state in `server_publisher_info` table
