### ISSUE TITLE
Promotion link

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#10838]
Promote using existing Rewards space to promote existing ID verified wallet users to subscribe to offers from Uphold.
This is a general placeholder for all promotions from Uphold in Rewards.

@NejcZdovc

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` pending answers from https://bravesoftware.slack.com/archives/CB0KCRCQN/p1597406587078700

**Comment by mandar-brave** [comment]
@LaurenWags i explained on slack thread; what else do you need from me?
thanks

**Comment by LaurenWags** [comment]
Expected text for the promotional card on brave://rewards and what URL it should link to when you click on it. Thanks!

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.13.71 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6138

--------------
