### ISSUE TITLE
[Desktop] Do not log classified page url in locally persisted diagnostic log for Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#10832]
## Description 

Do not log classified page url in locally persisted diagnostic log for Brave Ads

## Steps to Reproduce

   1. Join rewards
   2. Navigate to a url

## Actual result:

url is added to diagnostic log

## Expected result:
url should not be added to diagnostic log

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? yes
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` pending question sent to @tmancey 

Want to confirm that the test plan only applies to logs going forward, not backward.

**Comment by tmancey** [comment]
This PR only applies to logs going forward as there is another PR from @NejcZdovc which will remove/disable logging which will now remove all legacy logs

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.13.77 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6139
* Confirmed `tabURL` does not appear in brave://rewards-internals logs
* Confirmed visited page does not display in logs as it relates to Ads, however if the site you visit is a verified creator info does seem to be logged in regards to fetching publisher data (tip banner, etc).

-------
