### ISSUE TITLE
Start torrent / save torrent buttons need padding

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1083]
These buttons need padding.
<img width="275" alt="screen shot 2018-09-10 at 9 09 49 am" src="https://user-images.githubusercontent.com/831718/45299352-57476600-b4d9-11e8-9424-19922bdfd085.png">

CC @cezaraugusto 

You can see the torrent page by going here and clicking on a magnet link:
https://webtorrent.io/free-torrents

**Comment by srirambv** [comment]
Dupe of #1045
