### ISSUE TITLE
[Android] Fix crash for bottomsheet dialog

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#10839]
## Description 
Resolve crash for bottomsheet dialog. 
Error : **java.lang.NoSuchFieldError: No static field design_bottom_sheet dialog of type I in class LfE; or its superclasses**

## Steps to reproduce 

   1. Open NTP with sponsored image
   2. Wait for Bottom sheet dialog
   3. 

## Actual result 
Brave app crashes when we open the bottom sheet dialog

## Expected result
It should not crash when we open the bottom sheet dialog

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
Closing this issue as it's resolved in https://github.com/brave/brave-core/pull/6117

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.11.100 x64 build
- Verified bottomsheet is shown on a tab with a sponsored image
   <img width=450 src=https://user-images.githubusercontent.com/17010094/88387686-ea76a580-cdaa-11ea-941d-d60ec0858c20.png>
- Verified no browser crash when bottomsheet is shown on a SI 
- Verified closing the bottomsheet doesn't cause any crash
- Verified clicking on `Learn more` in bottom sheet brings up the info modal 
----------------
Verification passed on OnePlus 6T with Android 10 running 1.11.100 x64 build
- Verified bottomsheet is shown on a tab with a sponsored image
   <img width=300 src=https://user-images.githubusercontent.com/17010094/88387706-f6626780-cdaa-11ea-9ea8-b32c6983e6a8.png>
- Verified no browser crash when bottomsheet is shown on a SI 
- Verified closing the bottomsheet doesn't cause any crash
- Verified clicking on `Learn more` in bottom sheet brings up the info modal
