### ISSUE TITLE
[Desktop] AC doesn't completed if you have more then 4 publisher in the list

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10834]
## Description 

Right now we have hard limit on 3 retries per step. Because when we are sending out suggestions we go through retry logic it will automatically finish after 4 publishers are process as this equals to 3 retries per step. We need to remove this limit for step `STEP_PREPARE` as this is expected to go over. We need to think over how to distinguish between valid retry and failed retry for this step.

## Steps to Reproduce

   1. enable rewards
   2. add 6 verified publishers to AC table
   3. trigger AC

## Actual result:

Only 4 publishers are processed

## Expected result:
All publishers should be processed.

## Reproduces how often: 

easily

## Brave version (brave://version info)

this was introduced with version 1.10

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified description from the issue and ensured that AC is processed for 6 publishers
![image](https://user-images.githubusercontent.com/38657976/88915496-0a620980-d282-11ea-8cf5-b599e14839b4.png)
![image](https://user-images.githubusercontent.com/38657976/88915546-25347e00-d282-11ea-8e06-9d7d1b4d41c5.png)

![image](https://user-images.githubusercontent.com/38657976/88915476-ffa77480-d281-11ea-9e4a-9a8aa504612a.png)
