### ISSUE TITLE
[Desktop] Developper Tool -> Device Toolbar: changes after editing devices list are not saved between launches

### ISSUE THREAD

**Issue by lambda0xff** [brave/brave-browser#10846]
## Description 
In the developer tools, changes to the devices list are not saved between launches

## Steps to Reproduce
   1. Open developer tools 
   2. Click 'Toggle Device Toolbar'
   3. Click 'Edit...' then select/deselect some devices
  4. Close and relaunch

## Actual result:
Changes are gone

## Expected result:
Changes should be persisted

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit) Mac OS Catalina 10.15.6

**Comment by rebron** [comment]
@lambda0xff Can you update to 1.13.82 and if you have Chrome also installed, do you notice if this is reproducing in Chrome also?

**Comment by lambda0xff** [comment]
@rebron This seems to be fixed with 1.13.82.  Also fixed in Chrome apparently.
