### ISSUE TITLE
Publisher prefix list is not downloaded after upgrading from 1.11 to 1.13

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#10841]
## Description 

After merging https://github.com/brave/brave-core/pull/6115, the publisher prefix list is no longer downloaded when upgrading from 1.11 to master. Previous to that PR being merged, database migration 28 cleared a user pref that stored the last successful publisher info download time.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6158

**Clean profile scenario**
(Validated in a staging environment)
- Verified that `Scheduling publisher prefix` log entries twice with 0 seconds and x seconds (large number) when rewards is enabled in a clean profile
```
[Jul 31, 2020, 10:25:05.9 PM:INFO:publisher_prefix_list_updater.cc(57)] Scheduling publisher prefix list update in 0 seconds
```
```
[Jul 31, 2020, 10:25:11.8 PM:INFO:publisher_prefix_list_updater.cc(57)] Scheduling publisher prefix list update in 259199 seconds
```
Clear logs and close the browser and reopen 
- Verified that `Scheduling publisher prefix` log entries is shown only once with x seconds (large number) 
```
[Jul 31, 2020, 10:26:27.0 PM:INFO:publisher_prefix_list_updater.cc(57)] Scheduling publisher prefix list update in 259123 seconds
```
