### ISSUE TITLE
[Desktop] sites in AC list do not retain verified status when upgrading to version with v4 pub list

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10840]
## Description 

Found by @zenparsing 

If you have sites in your AC list which are verified on 1.11.x and you upgrade to 1.12.x (version with v4 pub list), the sites in the AC list will no longer appear as verified.

## Steps to Reproduce

 - Install 1.11.x (current release channel version), enable Rewards, confirm entire publisher list is downloaded.
 - Visit some sites (mix of verified and unverified) to populate your AC table
 - Upgrade to 1.12.x
 - Navigate to `brave://rewards`

## Actual result:

Sites in AC list do not retain verified status

Rewards page AC table before upgrade:

<img width="589" alt="Screen Shot 2020-07-21 at 12 53 28 PM" src="https://user-images.githubusercontent.com/5995084/88199541-fdef0880-cc12-11ea-9ac8-365dec8de836.png">

Rewards page AC table after upgrade:

<img width="591" alt="Screen Shot 2020-07-22 at 12 01 03 PM" src="https://user-images.githubusercontent.com/5995084/88199631-16f7b980-cc13-11ea-9241-09bfc73480f4.png">

The verified checkmark will appear if the publisher is also in the monthly contributions table.

Monthly contributions table after upgrade:

<img width="600" alt="Screen Shot 2020-07-22 at 12 02 32 PM" src="https://user-images.githubusercontent.com/5995084/88199786-47d7ee80-cc13-11ea-9a31-433d811cabd1.png">

## Expected result:
AC list is still populated and all sites in the AC list still show the correct status (verified/not verified as applicable)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)
```
- Verified STR from the description
- Verified checkmark for the verified pubs is retained after upgrade

AC table in 1.11.x - Before the upgrade:
![image](https://user-images.githubusercontent.com/38657976/88921038-74cb7780-d28b-11ea-9101-0d8b7a5d0565.png)

AC table in 1.12.x - After the upgrade:
![image](https://user-images.githubusercontent.com/38657976/88921090-87de4780-d28b-11ea-894b-7c42b2a2a63e.png)

Monthly tips before upgrade:
Monthly tips after upgrade:
One-time tips before upgrade:
One-time tips after upgrade:
