### ISSUE TITLE
http://dl.google.com/linux/chrome/deb/ automatically added to sources.list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1084]
## Description 

Originally reported on [community ](https://community.brave.com/t/development-version-automatically-adds-google-chrome-repository/31798)
>When running sudo apt update I started wondering about multiple warnings on target packages being configured multiple times. I thought that I had accidentally added the Brave repository multiple times, but then I discovered /etc/apt/sources.list.d/brave-browser-dev.list with contents:
>```
>### THIS FILE IS AUTOMATICALLY CONFIGURED ###                                                                                                    
># You may comment out this entry, but any other modifications may be lost.                                                                       
>deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main     
>```
## Steps to Reproduce

   1. Install Brave from terminal by adding sources
   2. Enter `cat /etc/apt/sources.list/brave-browser.list` in terminal
   3. Shows Google link automatically added to sources.list file

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/45301049-10a83a80-b4de-11e8-91a6-ae3e271f9823.png)

## Expected result:
Should not add it 

## Reproduces how often: 

100%

## Brave version (about:brave info) 

All 

### Reproducible on current release:

Yes for all brave release/beta/dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by k1nghat** [comment]
is this the same? https://github.com/brave/brave-browser/issues/1409

**Comment by Mikaela** [comment]
I think so.

**Comment by k1nghat** [comment]
i had brave and brave beta installed but i removed them both and im still getting the discover source notification. do i need to manually remove the brace sources?

**Comment by Mikaela** [comment]
I would edit the two files `/etc/apt/sources.list/brave-browser.list` and `/etc/apt/sources.list/brave-browser-dev.list` and if they have the Google line, add `#` in front of the file and then save. This is so the file doesn't get recreated or the repository added, while it says that comment is fine.

The easiest way is probably to e.g. `sudo nano /etc/apt/sources.list/brave-browser.list`, arrow down twice, `#` and `Ctrl + X` and `y` when prompted to save the file.

**Comment by k1nghat** [comment]
@Mikaela not exactly as you have shown, but i should just comment out the google lines in both of the brave sources here?
![image](https://user-images.githubusercontent.com/16073360/46678903-53c3ff00-cbab-11e8-87b8-0ce90be37a25.png)

**Comment by Mikaela** [comment]
>  not exactly as you have shown, but i should just comment out the google lines in both of the brave sources here?

Sorry, I mistyped, you are correct :+1: .

**Comment by Mikaela** [comment]
This issue also affects `/etc/apt/sources.list.d/brave-browser-beta.list`.

**Comment by srirambv** [comment]
+1 from @grandtoubab via #2176

**Comment by philipbock** [comment]
The script that installs this .list file (/etc/cron.daily/brave-browser) also installs Google package signing keys into apt, theoretically allowing Google to replace any package on my system with their own version. When I installed Brave I made a choice to trust Brave Software, not Google. Please fix ASAP.

**Comment by k1nghat** [comment]
does getting put on the 1.x backlog mean this wont be fixed until 1.x is pushed?

**Comment by fmarier** [comment]
A patch for this is up for review: https://github.com/brave/brave-core/pull/1078

**Comment by user144** [comment]
I deleted Google repository. Did I do the right thing?

**Comment by k1nghat** [comment]
> Can someone of the devs explain why this is happening in the first place? Adding random software repositories on people's system is not something that should happen due to an oversight!?

it was probably just left over from the move to chrome.

**Comment by fmarier** [comment]
What is happening is that the `.deb` / `.rpm` packaging that comes with Chromium includes a cron job that runs once a day and adds the chromium repository (or re-adds it if it has been disabled). This happens at most 24 hours after installing the package and so it's not immediately obvious after installation.

If you want to get rid of it, you need to remove the repository, but also the cronjob in `/etc/cron.daily/` to prevent it from re-adding the repository. My pull request removes that cronjob so that the Chromium repo never gets added.

**Comment by srirambv** [comment]
@fmarier @mbacchi  I think the issue is not just limited to the `/etc/cron.daily/`. The file under `/opt/brave.com/brave/cron/` contains the brave-browser file which invokes the add to source list command each time the browser is launched. 

@fmarier does your PR fix this ?

**Comment by fmarier** [comment]
I didn't remove the actual cronjob in my patch because as long as it's not installed in the right place (`/etc/cron.daily`), it will not be run.

**Comment by dhollinger** [comment]
Is there anyway to prevent this error if I have to maintain a copy of the Chrome repo for work and webdev reasons?

**Comment by srirambv** [comment]
>I didn't remove the actual cronjob in my patch because as long as it's not installed in the right place (/etc/cron.daily), it will not be run.

@mihaiplesa @simonhong might be worth checking into the actual file that is getting created in `/opt/brave.com/brave/cron`. I believe this file is what is getting added to the daily cron job which is being fixed in @fmarier's PR.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.62.37 Chromium: 73.0.3683.86 (Official Build) beta (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Linux

* Verification passed on Ubuntu 18.10
* Verified no google listed in sources.list file
![image](https://user-images.githubusercontent.com/17010094/54781967-1ea8e780-4bf4-11e9-9866-f94856b4180d.png)
