### ISSUE TITLE
Uphold KYC wallet limitation (new issue)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#10855]
if user has <25 bat keep Add Funds and Withdraw; any clicks with a non ID checked wallet forces user to login. Do not take user to verify wallet modal (that will create a lot of confusion and breaks logic of the minimal 25 BAT value)

ref: https://github.com/brave/brave-browser/issues/9723

**Comment by GeetaSarvadnya** [comment]
Verification passed on 

```

Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6217

**Clean profile with wallet balance zero**
- Ensured that `Sign in to Uphold` page is displayed upon clicking on `Add Funds` and `Withdraw Funds`

**Clean profile with wallet balance 25 BAT**
- Ensured that `Verify wallet` page is displayed upon clicking on `Add Funds` and `Withdraw Funds`

**Clean profile with wallet balance 24 BAT**
- Ensured that `Sign in to Uphold` page is displayed upon clicking on `Add Funds` and `Withdraw Funds`

**Connect KYC'd account which has wallet balance less than 25 BAT**
- Ensured that `Uphold Add fund or Withdraw` page is displayed upon clicking on `Add Funds` and `Withdraw Funds`
