### ISSUE TITLE
[Desktop] [Android] Crash when leaving standalone sync chain when offline

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10856]
The browser crashes when the sync chain was created offline and subsequently was reset

## Steps to Reproduce

1. Go offline
1. Clean install
1. Open `brave://settings/braveSync/setup`
1. Click `Start a new sync chain`
1. Click `Computer`
1. Click `OK`
1. Click `Manage your synced devices`
1. Leave sync chain

## Actual result:

Browser freezes and few seconds later crashes
![sync2_crash](https://user-images.githubusercontent.com/34715963/88205736-81c5e680-cc4d-11ea-8b8c-81f8c353eb7f.gif)

## Expected result:
No Crash

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Brave | 1.13.36 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @rebron @darkdh @AlexeyBarabash @yrliou  @petemill

**Comment by LaurenWags** [comment]
Android issue - https://github.com/brave/brave-browser/issues/10996

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified STR from the description. No crash.
Verified that after going online, it was possible to create sync chain.
