### ISSUE TITLE
[Desktop] Main menu goes outside of the screen borders

### ISSUE THREAD

**Issue by JesseZomer** [brave/brave-browser#10850]
## Description 

Whenever I use the main menu the menu opens halfway outside of the screen, with alot of extra space under the 'exit' option.

## Steps to Reproduce

   1. Click the main menu button in the top right corner 

## Actual result:

![image](https://user-images.githubusercontent.com/738579/88160332-ca11e400-cc0e-11ea-91a8-e61452045cbc.png)

## Expected result:
A menu that fits inside the screen and where I can click every option

## Reproduces how often: 

Everytime on my machine

## Brave version (brave://version info)

Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit) - Windows 10 Pro Version	10.0.18363 Build 18363

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 🤷‍♂️
- Can you reproduce this issue with the nightly channel? 🤷‍♂️

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by JesseZomer** [comment]
It looks like it has something to do with my external screen. I have a 4k screen connected to my laptop. Whenever I do a right click and the contextmenu fits within the screen, there is no problem. However when i get close to the right side of my 4k monitor and I right click and the contextmenu would not fit on the screen, I get the extra spacing.

normal:
![image](https://user-images.githubusercontent.com/738579/88901273-e4704100-d250-11ea-8417-534c80489c73.png)

bugged:
![image](https://user-images.githubusercontent.com/738579/88901387-04076980-d251-11ea-9e59-6906db19b234.png)

**Comment by JesseZomer** [comment]
@rebron disabling the extension makes no difference. If I disable my external monitor the menu looks ok. Also if I keep my external monitor enabled, but drag the browser window to my laptop screen, the menu also looks ok.

This is my screen setup: 
![image](https://user-images.githubusercontent.com/738579/92079367-0e70d200-edc0-11ea-8838-5c1e01d4276a.png)

were 2 is my external monitor and 1 is my laptop screen. It only happens when I open a menu at screen 2 and the menu would hit screen 1 (or maybe hit just the border of screen 2).

**Comment by rebron** [comment]
@JesseZomer That is so strange that use of an external monitor is causing extra padding to these menus. Can I get you to update to 1.13.82 first? Any other extensions that might be causing this? I can't reproduce this with my setup with an external monitor. 

Looks like a chromium issue too since you mentioned it reproduced in Chrome.

**Comment by JesseZomer** [comment]
@rebron sorry for the late reply. Even with all extensions disabled I'm still getting the same behavior. It's indeed probably a chromium issue because I can reproduce it in chrome.

**Comment by JesseZomer** [comment]
The issue seems to be fixed 👍 Not sure what version it got fixed 🤷‍♂️
