### ISSUE TITLE
Custom style cosmetic filter rules for class selectors not applied

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#10862]
_Originally posted by @Yuki2718 in https://github.com/brave/brave-browser/issues/8478#issuecomment-600933153_

> Applying `google.*##.mn-dwn-arw:style(top: 27px !important;)` to Google search results in move of arrow icons as on uBO - for this screenshot I disabled uBO's other filters but keeping them enabled didn't change the results, only changed other appearance such that URL was shown in grey the same as the last screenshot below.
>
> ![google1](https://user-images.githubusercontent.com/58900598/77020835-68bfd700-69c8-11ea-9c3d-7ad381bae542.png) 
>
> But the same rule on Brave Nightly 1.8.22 didn't and changing the wildcard to "com" `google.com##.mn-dwn-arw:style(top: 27px !important;)` didn't make a difference.
>
> ![brave](https://user-images.githubusercontent.com/58900598/77020966-bd635200-69c8-11ea-9a8d-330c51c877e4.png)
>
> ![google2](https://user-images.githubusercontent.com/58900598/77021436-02d44f00-69ca-11ea-841e-d64a8915e626.png)

Any rules without class selectors work fine. For example, `brave.com##*:style(background: #f00 !important)` changes everything on brave.com to appear with a red background.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.13.77 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Reproduced the issue using 1.12.112 and test plan from https://github.com/brave/brave-core/pull/6176
<img width="1200" alt="Screen Shot 2020-08-19 at 11 45 33 AM" src="https://user-images.githubusercontent.com/28145373/90658425-91ffc000-e211-11ea-8cdb-bc83bbb47a32.png">

* Verified test plan from https://github.com/brave/brave-core/pull/6176 works as expected on 1.13.77
<img width="1198" alt="Screen Shot 2020-08-19 at 11 44 47 AM" src="https://user-images.githubusercontent.com/28145373/90658436-94621a00-e211-11ea-9bd4-5f8b6b5cea1e.png">

* Note, if you scroll down the page it resumes normal background. Confirmed with @antonok-edm this is ok.

-----------

**Comment by srirambv** [comment]
Removing Android label as this is desktop only. @antonok-edm confirmed it
