### ISSUE TITLE
foxnews.com doesn't render content properly

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1086]
## Description 
http://www.foxnews.com/ has problems rendering with our default settings

## Actual result:
![screen shot 2018-09-10 at 10 26 11 am](https://user-images.githubusercontent.com/4733304/45313901-076e9c00-b4e5-11e8-965e-31b2265ac12e.png)

## Expected result:
![screen shot 2018-09-10 at 10 34 33 am](https://user-images.githubusercontent.com/4733304/45313954-384ed100-b4e5-11e8-9c9f-0b6d23558a46.png)

## Reproduces how often: 
100%

## Brave version (about:brave info) 
Brave | 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Mac OS X

### Reproducible on current release:
yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
**yes**
- Is the issue reproducible on the latest version of Chrome? 
**no**

**Comment by bbondy** [comment]
Already uploaded, but in review here:
https://github.com/brave/https-everywhere-builder/pull/8

Users should get an update on the next extension update.  Clean profiles already fixed.

**Comment by LaurenWags** [comment]
Verification Pass with

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X

**Comment by GeetaSarvadnya** [comment]
Verification Pass on:

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
