### ISSUE TITLE
[Android] Sometimes device list contains an empty device name

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10864]
Sometimes device list contains an empty device name.

Reported at https://community.brave.com/t/sync-in-brave-android-beta-nigthly-dont-show-name-of-other-devices/145196/3 .

**Comment by deeppandya** [comment]
@AlexeyBarabash i think it's related to dark mode.

**Comment by AlexeyBarabash** [comment]
@deeppandya thanks, then it will be easier to reproduce

**Comment by AlexeyBarabash** [comment]
![Screenshot_20200722-233307_Brave - Nightly](https://user-images.githubusercontent.com/24739341/88225860-e3994700-cc73-11ea-80cb-3e8bc8d208ad.jpg)

And it is easy to reproduce, just switch to the dark mode

**Comment by srirambv** [comment]
Dupe of #8703

**Comment by kmansoft** [comment]
Possibly related:

I'm running Beta on two desktop systems (Windows 10 and Linux) and Android.

All three installs are set up to sync with each other - single "sync chain".

And yet, all three installs show only themselves as members of the sync chain. The other two installs which are part of the chain are not shown.
