### ISSUE TITLE
[Desktop] Unable to create sync chain due to leading and trailing whitespace in code words

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10860]
## Steps to Reproduce

1. Clean install `DeviceA` and `DeviceB`
1. On `DeviceA` open `brave://settings/braveSync/setup`
1. On `DeviceA` click `Start a new sync chain`
1. On `DeviceA` click `Computer`
1. On `DeviceA` copy the code words
1. Add leading and trailing white space to the code words
1. On `DeviceB` use the code words
1. Wait for the sync chain creation

## Actual result:

`Invalid Code Words` error is shown

## Expected result:
Leading and trailing whitespace in code words are trimmed
Sync chain is created

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Brave | 1.13.36 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @rebron @darkdh @AlexeyBarabash @yrliou  @petemill

**Comment by AlexeyBarabash** [comment]
I can reproduce.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)

```
- Issue is still reproducible in 1.20.x, logged a follow-up issue as per the QA process https://github.com/brave/brave-browser/issues/13681
