### ISSUE TITLE
[Android] Remove unused code for BottomSheetBehavior

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#10865]
## Description 
We have unused code for BottomSheetBehavior, that relies on resources that are deleted in cr86. We just need to delete it.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan:
1. Open NTP with sponsored image for the first time.
2. It will show the bottom banner and then click learn more.
![device-2020-07-22-163449](https://user-images.githubusercontent.com/30602739/88227778-1f181f00-cc3c-11ea-9990-60257086afff.png)
3. It should open bottomsheet dialog.
![Uploading device-2020-07-22-164111.png…]()

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/10865#issuecomment-662691838
![mobsheet](https://user-images.githubusercontent.com/17010094/91435199-e2080380-e85d-11ea-8d98-d96fa76ca0aa.gif)

------------

Verification passed on Samsung Tab A with Android 10 running 1.13.81 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/10865#issuecomment-662691838
![tabsheet](https://user-images.githubusercontent.com/17010094/91435274-fba94b00-e85d-11ea-8fdc-7ce805a26549.gif)
