### ISSUE TITLE
[Android] Pull brave-core PR #6173 into Android sync v2 code

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10861]
Pull brave-core PR https://github.com/brave/brave-core/pull/6173 into Android sync v2 code

**Comment by AlexeyBarabash** [comment]
Well, the STR from https://github.com/brave/brave-browser/issues/10856
does not give a crash for the current Android build (1.13.51), but I can't leave the chain when device is offline

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.108 x64 release build.
- Verified test plan form #10856
- Verified no crash if the device comes online when it's trying to create sync chain and trying to get device id.
---------
Verification passed on Samsung Tab A with Android 10 running 1.12.108 x64 release build.
- Verified test plan form #10856
- Verified no crash if the device comes online when it's trying to create sync chain and trying to get device id.
