### ISSUE TITLE
Audit Rewards server responses publisher follow-up

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#10866]
Perform publisher-related follow-up work for Rewards server responses https://github.com/brave/brave-core/pull/5918. This portion of that work was deferred to ease rebasing of the v4 publisher list work.

**Comment by LaurenWags** [comment]
Verification in progress

```
Brave | 1.14.71 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

<details>
<summary>Wallet funded via VG (UGP grant) only</summary>

- Verified wallet status is `Not connected` in brave://rewards-internals
- Verified checkmark is shown in BR panel as well as in Tipping banner for verified pubs
- Verified custom banner shown (when applicable) for verified publishers
- Verified checkmark is shown in AC table, Monthly contribution table and One-time tips panel for verified pubs
- Verified checkmark is shown in Monthly statement for AC, Monthly contributions and One-time tips for verified pubs
- Verified one-time tips and monthly tips processed successfully
- Verified AC processed successfully
- Verified wallet summary is displayed correctly
- Verified wallet summary and monthly statement are showing the correct stats for One-time tip, monthly tip and AC 
- Verified brave://rewards-internals data is shown as expected for `Contributions`, `General info` and `Promotions`
- Verified rewards summary isn't lost after browser restart
- Verified able to tip verified pubs when AC is turned off

</details>

TBD:

<details>
<summary>Wallet funded via Uphold only</summary>

TBD

</details>


<details>
<summary>Upgrade Checks</summary>

TBD

</details>
