### ISSUE TITLE
Add a note reminding developers that changes to the `brave://rewards-internals` log need a security review

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#10868]
The `brave://rewards-internals` logging code should ideally have a comment somewhere in the code that any changes (excluding deletions) to what's being collected needs a security review.

**Comment by fmarier** [comment]
@NejcZdovc @tmancey This issue is a little vague because I'm not quite sure what the best way to do this is, and how practical it is.

I suggested a comment in the code but I assume there's probably more than one place where these changes can take place, so perhaps there is a better way to document this.

**Comment by NejcZdovc** [comment]
@fmarier I would say it can easily be missed in the code. What if we add it as a checkbox in PR template?

**Comment by fmarier** [comment]
I [added it](https://github.com/brave/security/commit/9b7f5ea621ba565641d4d02dea748ec0970e419c) to the security review template, but are you suggesting the brave-core template? It might be a bit too specific for that one, I don't know.

**Comment by Miyayes** [comment]
Covered this on Nov 9, 2022 meeting with Rewards team.
