### ISSUE TITLE
[Desktop] Enable sync v2 on release channel

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#10863]
This need to uplifted to 1.12x beta channel so it can be ready for migration on 7/28

**Comment by AlexeyBarabash** [comment]
@darkdh @jsecretan ,
This issue is about both  Android and Desktop?

**Comment by darkdh** [comment]
it is desktop only. android doesn't have any restriction on sync v2
https://github.com/brave/brave-core/pull/6184#issuecomment-662853842

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6184
![image](https://user-images.githubusercontent.com/34715963/89241324-d464b280-d5fe-11ea-8c23-2c22fdaa55c1.png)

Verified `Sync` is listed in App Menu
![image](https://user-images.githubusercontent.com/34715963/89239914-e5132980-d5fa-11ea-8a1f-f066fdc18ed6.png)

Verified it opens `brave://settings/braveSync/setup`
![image](https://user-images.githubusercontent.com/34715963/89239936-f825f980-d5fa-11ea-8ffe-5d5a80ee1fa0.png)

Verified ability to create a sync chain
![image](https://user-images.githubusercontent.com/34715963/89239763-69b17800-d5fa-11ea-80e8-352675cea80b.png)
