### ISSUE TITLE
[Android] Inconsistent decimal representaion on rewards 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10874]
## Description 
 Inconsistent decimal representaion on rewards 

## Steps to reproduce 

   1. Install 1.11.8 build
   2. Enable rewards
   3. 3 decimal values are not shown in all the screens

## Actual result 

|Tips banner|Recurring tip|Onetime tip| Rewards panel| 0 balance | Grant details
| :---: | :--: | :--: | :--: | :--: | :--: | 
| ![image](https://user-images.githubusercontent.com/17010094/88258670-97bcc100-ccb8-11ea-97b6-ccd3c9dff591.png) | ![image](https://user-images.githubusercontent.com/17010094/88258695-a1462900-ccb8-11ea-8fa8-4a1633ba9aa1.png) | ![image](https://user-images.githubusercontent.com/17010094/88258707-a5724680-ccb8-11ea-8d3c-f698394ab686.png) | ![image](https://user-images.githubusercontent.com/17010094/88258742-b8851680-ccb8-11ea-9988-e2f891103419.png) | ![image](https://user-images.githubusercontent.com/17010094/88258824-eec29600-ccb8-11ea-9b76-2bd9a8ba9cf3.png) | ![image](https://user-images.githubusercontent.com/17010094/88258874-0f8aeb80-ccb9-11ea-8313-db69d9cac669.png)

## Expected result
All rewards screen should have 3 decimal values

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.11.98

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? JNA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Follow up to  #10028
cc: @tmancey @anthonypkeane

**Comment by deeppandya** [comment]
@anthonypkeane updated the changes but i can't verify it as the staging is not working right now. i will test it again once i can fund the wallet.

**Comment by deeppandya** [comment]
![Screenshot_20200730-161131_Brave](https://user-images.githubusercontent.com/5146988/88970216-0339fc00-d280-11ea-89b0-a84dc49a099e.jpg)
![Screenshot_20200730-161144_Brave](https://user-images.githubusercontent.com/5146988/88970217-03d29280-d280-11ea-9b6f-389468505f7f.jpg)
![Screenshot_20200730-161156_Brave](https://user-images.githubusercontent.com/5146988/88970218-03d29280-d280-11ea-95c2-11e09f896dee.jpg)
![Screenshot_20200730-161212_Brave](https://user-images.githubusercontent.com/5146988/88970219-03d29280-d280-11ea-9392-ae361a3734df.jpg)
![Screenshot_20200730-161230_Brave](https://user-images.githubusercontent.com/5146988/88970220-046b2900-d280-11ea-8234-1ffaa1d212ba.jpg)

**Comment by srirambv** [comment]
@deeppandya  the BAT value in selector should also have 3 decimal values 
<img width=300 src=https://user-images.githubusercontent.com/17010094/88998977-2f3e9700-d2eb-11ea-97b1-0b48a541c03b.png>

**Comment by deeppandya** [comment]
@srirambv @anthonypkeane i think we should update BAT value selector to 3 decimal points as it's an iteger value and it won't fit in the UI. we might need to update the UI

**Comment by anthonypkeane** [comment]
@jamesmudgett for ideas

**Comment by anthonypkeane** [comment]
> @deeppandya the BAT value in selector should also have 3 decimal values
> <img alt="" width="300" src="https://user-images.githubusercontent.com/17010094/88998977-2f3e9700-d2eb-11ea-97b1-0b48a541c03b.png">

Yes, add the 3 decimal places. Pls look at iOS for reference.

**Comment by deeppandya** [comment]
Okay @anthonypkeane it's Done
![Screenshot_20200804-145512_Brave](https://user-images.githubusercontent.com/5146988/89333234-b03abd00-d662-11ea-99dd-3cab97054090.jpg)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build
- Verified correct decimal representation is shown in the following screens

|Tips banner|Recurring tip|Onetime tip| Rewards panel| 0 balance | Grant details
| :---: | :--: | :--: | :--: | :--: | :--: | 
|![image](https://user-images.githubusercontent.com/17010094/89990665-9ad51c80-dc7a-11ea-960f-f3f8e3cba8f2.png) | ![image](https://user-images.githubusercontent.com/17010094/89990619-8b55d380-dc7a-11ea-922e-2890d4bc7523.png) | ![image](https://user-images.githubusercontent.com/17010094/89990641-9446a500-dc7a-11ea-95d5-69b78297940a.png) | ![image](https://user-images.githubusercontent.com/17010094/89990599-83962f00-dc7a-11ea-9157-0f07e9d62919.png) | ![image](https://user-images.githubusercontent.com/17010094/89991039-28187100-dc7b-11ea-8cf5-dec2d0757121.png) | ![image](https://user-images.githubusercontent.com/17010094/89990586-7f6a1180-dc7a-11ea-93b3-9607f37c3f3d.png)


---------------

Verification passed on Samsung Tab A with Android 10 running 1.12.112 x64 build
- Verified correct decimal representation is shown in the following screens

|Tips banner|Recurring tip|Onetime tip| Rewards panel| 0 balance | Grant details
| :---: | :--: | :--: | :--: | :--: | :--: | 
|![image](https://user-images.githubusercontent.com/17010094/89991865-5ba7cb00-dc7c-11ea-88a0-cb413e311ad6.png)| ![image](https://user-images.githubusercontent.com/17010094/89991887-64989c80-dc7c-11ea-8864-9344866cee65.png) | ![image](https://user-images.githubusercontent.com/17010094/89991875-5f3b5200-dc7c-11ea-8163-b5e4e2c32d25.png) | ![image](https://user-images.githubusercontent.com/17010094/89991845-56e31700-dc7c-11ea-8bb9-7a76e9c0505b.png) | ![image](https://user-images.githubusercontent.com/17010094/89991982-8abe3c80-dc7c-11ea-86d7-4c78bebe91d6.png) | ![image](https://user-images.githubusercontent.com/17010094/89992092-ae818280-dc7c-11ea-8664-14cea0486b1d.png)
