### ISSUE TITLE
[Desktop] Sync Settings are not applied upon change

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10877]
Sync Settings are applied after leaving or reloading the sync page which is very counter-intuitive.

## Steps to Reproduce

1. Create sync chain between 2 devices
1. `DeviceA`: Open `brave://settings/braveSync/setup`
1. `DeviceA`: Turn off `Bookmarks` under `Sync Settings`
1. `DeviceB`: Open `brave://settings/braveSync/setup`
1. `DeviceB`: Turn off `Bookmarks` under `Sync Settings`
1. `DeviceA`: Open `interia.pl` and bookmark it
1. `DeviceB`: Open `onet.pl` and bookmark it
1. Wait for sync update

## Actual result:

Bookmarks are synced on both devices
Sync Settings are not applied

![sync2_sync_settings](https://user-images.githubusercontent.com/34715963/88290156-99a57500-ccf6-11ea-9c20-ada685893e3c.gif)

Important: Closing the sync page will apply the settings
Important: Reloading the sync page will apply the settings

## Expected result:
Bookmarks are not synced
Sync Settings are applied

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Brave | 1.13.37 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @rebron @darkdh @AlexeyBarabash @petemill

**Comment by darkdh** [comment]
You have to leave sync setting page in order to make change effective. When you are still in the page, `Setup In Progress` will displayed true in `brave://sync-internals/`. Sync engine will pick up change only after `Setup In Progress` becomes false again.

**Comment by petemill** [comment]
I guess we need a Save button then

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6200 and STR from the description.
Bookmark toggle worked instantly. The bookmarks were not synced.
![image](https://user-images.githubusercontent.com/34715963/89239275-0246f880-d5f9-11ea-8b48-7a8a3642331a.png)
Re-enabled bookmark syncing and sync was successful
![image](https://user-images.githubusercontent.com/34715963/89239315-1d196d00-d5f9-11ea-8c87-53bda400f92e.png)

Also enabled `Open Tabs` syncing and it worked as expected.
