### ISSUE TITLE
[Desktop] Device list is not automatically updated when going back online

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10876]
Device list is not updated when the sync chain is created offline and then it is back online

## Steps to Reproduce

1. Go offline
1. Clean install
1. Open `brave://settings/braveSync/setup`
1. Click `Start a new sync chain`
1. Click `Computer`
1. Click `OK`
1. Click `Manage your synced devices`
1. Go online
1. Wait for the device list update

Note: I waited 15 minutes

## Actual result:

Device List is not automatically updated
All `Sync Settings` are turned off
`Transport State` is stuck on `Pending desired configuration` in `brave://sync-internals/`

![sync2_device_list](https://user-images.githubusercontent.com/34715963/88284558-e6d11900-cced-11ea-9f93-e91baa01e3e9.gif)

Important: Reloading the sync page fixes the issue.
Important: Restarting Brave fixes the issue.

## Expected result:
Device List is automatically updated and it shows one device (no need to reload the page)
All `Sync Settings` are automatically turned on
`Transport State` is set to `Active` in `brave://sync-internals/`

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Brave | 1.13.37 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @rebron @darkdh @AlexeyBarabash @petemill

**Comment by btlechowski** [comment]
Another Test Case - Sync between two devices
Both devices are stuck

1. Go offline `DeviceA` and `DeviceB`
1. Clean install `DeviceA` and `DeviceB`
1. On `DeviceA` open `brave://settings/braveSync/setup`
1. On `DeviceA` click `Start a new sync chain`
1. On `DeviceA` click `Computer`
1. On `DeviceA` copy the code words
1. On `DeviceA` click `OK`
1. On `DeviceB` open `brave://settings/braveSync/setup`
1. On `DeviceB` click `I have a sync Code`
1. On `DeviceB` paste the code words
1. On `DeviceB` click `Confirm`
1. Go online `DeviceA` and `DeviceB`
1. Wait for the sync chain creation

**Comment by darkdh** [comment]
You can't wait on sync setting page, otherwise it will be stuck with "Setup In Progress" and engine is waiting for it to be false

**Comment by btlechowski** [comment]
I noticed that the device can be stuck on sync creation even if it happens online. This happens randomly.
1. Clean install `DeviceA` and `DeviceB`
1. On `DeviceA` open `brave://settings/braveSync/setup`
1. On `DeviceA` click `Start a new sync chain`
1. On `DeviceA` click `Computer`
1. On `DeviceA` copy the code words
1. On `DeviceB` open `brave://settings/braveSync/setup`
1. On `DeviceB` click `I have a sync Code`
1. On `DeviceB` paste the code words
1. On `DeviceB` click `Confirm`
1. On `DeviceB` **Immediately** Click `Manage your synced devices`
1. On `DeviceA` click `OK`
1. On `DeviceA` **Immediately** Click `Manage your synced devices`
1. Wait for the sync chain creation

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

* Verified test plan from https://github.com/brave/brave-core/pull/6200 

* Verified STR from the description.
Before going online:
![image](https://user-images.githubusercontent.com/34715963/89239487-9fa22c80-d5f9-11ea-8aa7-13113dfe8412.png)
After going online
![image](https://user-images.githubusercontent.com/34715963/89239517-b183cf80-d5f9-11ea-8558-58d80245c308.png)

* Verified STR from https://github.com/brave/brave-browser/issues/10876#issuecomment-662983057
Before going online:
![image](https://user-images.githubusercontent.com/34715963/89239688-29ea9080-d5fa-11ea-9acc-052008c66498.png)
After going online
![image](https://user-images.githubusercontent.com/34715963/89239763-69b17800-d5fa-11ea-80e8-352675cea80b.png)

* Also verified https://github.com/brave/brave-browser/issues/10876#issuecomment-664643177 several times
