### ISSUE TITLE
No ads coming on my brave browser for about 2 weeks [Desktop]

### ISSUE THREAD

**Issue by Jlastur** [brave/brave-browser#10878]
Hello, i am from spain.

For a few months I calculate that before March in Spain you could not have ads, but since March it could be created. I have been receiving ads for 2 months and now I have not.

I have installed the browser, restored the wallet and everything remains the same. I do not see any ADS and I can not access the notifications of this month that I had 35 within the announcements section of the settings of the same, where I put the like and put the heart.

Something happens but I want to know if someone knows when they are going to solve it because we are not receiving ads and therefore we are not receiving money.

Thank you very much

**Comment by Jlastur** [comment]
I download the nightly version of brave (1.13.40) and ads work so this is a several bug on brave stable version 1.11.97

We need resolve it.

**Comment by cjwijtmans** [comment]
Android version of issue: https://github.com/brave/brave-browser/issues/10684

**Comment by tmancey** [comment]
Closing issue as currently the Spanish catalog has no campaigns so this is expected, however rest assured I have mentioned this to the ads team. Thank you, Terry

**Comment by Jlastur** [comment]
> Closing issue as currently the Spanish catalog has no campaigns so this is expected, however rest assured I have mentioned this to the ads team. Thank you, Terry

Does anyone know when there will be campaigns in Spain then? 
Because very people of another countries has been the same problem.

thanks you and regards.

**Comment by tmancey** [comment]
Ad campaigns vary by country, and by operating system. In some countries, there may be fewer ads observed throughout the month based on campaign size, delivery pacing, operating systems, content categories and that advertisers have selected to run their ads to.

As we continue to generate additional demand for countries where Brave Ads are available, the consistency should improve over time.
