### ISSUE TITLE
[Desktop] Failed to leave sync when offline when browser was restarted

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10879]
The browser goes into a state when it is not listed in Device list(indicating that it left sync). After going online, the browser recovers from that state, but it remains in the sync chain.

## Steps to Reproduce

1. Clean install
1. Open `brave://settings/braveSync/setup`
1. Click `Start a new sync chain`
1. Click `Computer`
1. Copy the code words
1. Click `OK`
1. Click `Manage your synced devices`
1. Go offline
1. Leave sync chain
1. Restart browser
1. Go online

## Actual result:

Failed to leave the sync chain.

![sync2_failed_leave](https://user-images.githubusercontent.com/34715963/88305335-a54e6700-cd09-11ea-8f23-d569ddb31af1.gif)

Note: Without browser restart, sync reset is successful

## Expected result:
Sync reset was successful.

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Brave | 1.13.40 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @rebron @darkdh @AlexeyBarabash @petemill

**Comment by AlexeyBarabash** [comment]
[[Desktop] Failed to leave sync when offline when browser was restarted #10879](https://github.com/brave/brave-browser/issues/10879)
- I can't reproduce, probably fixed by https://github.com/brave/brave-core/pull/10841

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.59 Chromium: 110.0.5481.40 (Official Build) nightly (64-bit) 
-- | --
Revision | 371638c3173bebbbb05361ed503673a3aba42e61-refs/branch-heads/5481@{#395}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/215211655-e7a27945-1cdf-484b-8ced-0226849eeaa8.png)
