### ISSUE TITLE
[Desktop] Google Translate: Automatic translate non-functional, Extension use unacceptable

### ISSUE THREAD

**Issue by wolfgrrl** [brave/brave-browser#10894]
## Description 
Google Translate is non-functional in BB.

I have my settings for "Offer to translate pages that aren't in a language you read" to ON. BB gives a pop-up asking you to install the Google Translate extension to translate webpages. 

Installation of the extension should not be required as the ability to translate is already inherent in Chrome and should work as it does in Chrome, by placing an icon in the address bar that will allow the user to toggle translation as well as to set that particular webpage to automatically translate. An option is also available in the right-click menu in Chrome to "translate webpage". This is not present in BB either. Furthermore, using the extension does not translate the webpage every time it's clicked. It's unreliable and doesn't always work. 

Having to use the translate extension places an intrusive huge white bar at the top of any page that you choose to translate. 

This has been mentioned on the Reddit page with no responses from devs. https://old.reddit.com/r/brave_browser/comments/hd3kia/webpage_translate_not_working/

This is a huge deal-breaker for me. I run a business and import my products from all over the world. The translate feature is CRUCIAL to my business.

## Steps to Reproduce
Load any foreign language webpage

## Actual result:
BB cannot automatically translate. 

## Expected result:
BB should automatically translate and allow all the settings that are inherent in Chrome. 

## Reproduces how often: 
Reproducible every time. 

## Brave version (brave://version info)

Brave | 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 2004 (Build 19041.388)

**Comment by rebron** [comment]
Hi @wolfgrrl Response to that is here. https://old.reddit.com/r/brave_browser/comments/hd3kia/webpage_translate_not_working/fzfd1n8/

Chrome has an API key for their translation service that we can't use, except via the Google Translate extension. There are other translation extensions if the Google translate one isn't working for you.

Feedback taken and appreciate it. I'm marking this as closed.
