### ISSUE TITLE
Whitelist some sites to not block autoplay by default

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1089]
https://www.youtube.com/
https://www.khanacademy.org/
https://www.twitch.tv/
https://vimeo.com/
https://udemy.com/
https://www.duolingo.com/
https://giphy.com/
https://imgur.com/
https://www.netflix.com/
https://www.hulu.com/
https://www.primevideo.com/
https://www.dailymotion.com
http://www.tv.com/
https://www.viewster.com/
http://www.metacafe.com/
https://d.tube/
https://www.spotify.com/
https://www.lynda.com/
https://soundcloud.com/
https://www.pandora.com/

what else?

**Comment by alexwykoff** [comment]
+ https://www.netflix.com/
- https://www.youtube.com/ (esp. when opened or rehydrating in non-focus tab)
+ https://www.amazon.com/ (prime video)

**Comment by bbondy** [comment]
Netflix & Youtube already in the list. primevideo.com I think is the correct link for prime video.

**Comment by maikelmclauflin** [comment]
there's https://d.tube/

and depending on how far down this rabbit hole you want to go you could include sites like lynda.com, 

podcasts probably fall under this as well 
soundcloud.com

music
pandora.com
spotify.com

may be a good thing to poll on reddit

**Comment by alexwykoff** [comment]
@bbondy good ole markdown tripped me up. that was a minus on youtube due to parenthetical reasons 😸 

https://www.spotify.com/us/ might be worth a check given @maikelmclauflin 's entry

**Comment by bbondy** [comment]
I think I prefer reasonable defaults and allow user to override over forcing the user into making some kind of decision on our timeline.

**Comment by Liunkae** [comment]
Periscope: https://www.periscope.tv and https://www.pscp.tv

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* All sites except Sound cloud( #1584) and D Tube(#1581), listed on https://github.com/brave/brave-core/pull/599 allows auto play
