### ISSUE TITLE
Search updates

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#10890]
## Description 
Small update to the engines we show by default
- Add Yahoo as an option
- Remove DDG Lite on Android
- Add ability to localize engine based on country code

Related: https://github.com/brave/internal/issues/701, https://github.com/brave/internal/issues/700

### Verify Yahoo shows as an option in onboarding
1. Fresh profile
2. Launch Brave and go through on-boarding wizard (brave://welcome)
3. Confirm Yahoo shows in drop down as first item on search engine screen
4. Confirm default is what it should be (Google for USA, DDG for DE/IE/NZ/AU)

### Verify Yahoo shows in brave://settings/
1. Fresh profile
2. Launch Brave and visit brave://settings/searchEngines
3. Confirm Yahoo shows as the first item under `Default search engines`
4. Confirm default is what it should be (Google for USA, DDG for DE/IE/NZ/AU)

#### Quick overview of how to change locale (Windows 10)
- Open settings (bottom right corner)
- Pick `Time & Language`
- On the left side-menu, pick `Region`
- Change `Country or Region`:
![image](https://user-images.githubusercontent.com/4733304/88436801-f0c04e00-cdb9-11ea-8c34-f1a6fbd2cb89.png)

#### Verify locale specific version of Yahoo URL is used in supported region
1. Set country for your OS as one which supports Yahoo (USA, Argentina, Austria, Australia, Brasil, Canada, Switzerland, Chile, Colombia, Germany, Denmark, Spain, Finland, France, Hong Kong, Indonesia, Republic of Ireland, India, Italy, Mexico, Malaysia, Netherlands, Norway, New Zealand, Peru, Philippines, Sweden, Singapore, Thailand, Taiwan, Great Britain / England / etc, Venezuela, Vietnam)
2. Fresh profile
3. Launch Brave and visit brave://settings/searchEngines
4. Inspect the Yahoo link and verify it's using the proper localized version (ex: `mx.search.yahoo.com` for Mexico)

#### Verify Yahoo is not shown in unsupported region
1. Set country for your OS as one which doesn't support Yahoo (Japan, Turkey, Russia, etc)
2. Fresh profile
3. Launch Brave and visit brave://settings/searchEngines
4. Yahoo shouldn't show in list under `Default search engines`

### Verify Yahoo shows as an option in onboarding
1. Fresh install
2. Launch Brave and tap on search bar. it should open the onboarding
3. Confirm Yahoo shows in list as first item on search engine onboarding

### Verify Yahoo shows in settings
1. Fresh install or update
2. Launch Brave and go to settings
3. Confirm Yahoo shows as the first item under `Standard Tab` and `Private Tab`

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
Revision	a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from the description

`Onboarding`:
* Confirmed Google is the default in USA but Yahoo can be selected in onboarding.
* Confirmed DDG is the default in DE/IE/NZ/AU but Yahoo can be selected in onboarding. 
* Confirmed after selecting Yahoo in onboarding the appropriate localized Yahoo is used in DE/IE/NZ/AU (confirmed in settings and by doing a search via URL bar).

`brave://settings/searchEngines`:
* Confirmed placement of Yahoo.
* Confirmed correct localized Yahoo URL is listed.
* Confirmed correct default of Google is set in US on clean profile.
* Confirmed correct default of DDG is set in DE/IE/NZ/AU on clean profiles.

`Localization (supported regions)`:
* Confirmed Yahoo URL is listed and localized for Norway in `brave://settings/searchEngines`.
* Confirmed Yahoo URL is listed and localized for Sweden in `brave://settings/searchEngines`.
* Confirmed Yahoo URL is listed and localized for Thailand in `brave://settings/searchEngines`.
* Confirmed Yahoo URL is listed and localized for Switzerland in `brave://settings/searchEngines`.
* Confirmed Yahoo URL is listed and localized for Colombia in `brave://settings/searchEngines`.

`Unsupported regions`:
* Confirmed Yahoo URL is not listed for Japan in `brave://settings/searchEngines`.
* Confirmed Yahoo URL is not listed for Turkey in `brave://settings/searchEngines`.
* Confirmed Yahoo URL is not listed for Russia in `brave://settings/searchEngines`.

`P3A`:
* Confirmed expected P3A value in `brave://local-state`
```
         "Brave.Search.DefaultEngine.2": {
            "sent": false,
            "value": "6"
         },
```

--------------
