### ISSUE TITLE
[Desktop] Brave Browser not verified on github

### ISSUE THREAD

**Issue by filippo-fresilli** [brave/brave-browser#10903]
Brave Browser not verified on Github

**Comment by srirambv** [comment]
Please add more context to the issue.

**Comment by bsclifton** [comment]
@filippo-fresilli do you have more information about what you mean? The Brave org is verified on GitHub
![image](https://user-images.githubusercontent.com/4733304/88507059-654ce580-cf90-11ea-813e-410fdb54796d.png)

As far as I know, the repos don't have a verification process. Developers doing commits can have verified commits. Is this what you're asking about? (ex: can we enforce verified commits, via GPG, etc)

**Comment by NejcZdovc** [comment]
@bsclifton I think he means that Brave is not verified on our publishers platform. You can read more about it here https://github.com/brave/support/issues/396. @corymcdonald is this supported now?

**Comment by filippo-fresilli** [comment]
Hi,
I saw the possibility to be an account verified for publishers on github, so now my account is verified on the platform. 
But as I saw, Brave is not an account verified on github. 
Here the picture to better understand:
<img width="368" alt="Schermata 2020-07-27 alle 08 51 54" src="https://user-images.githubusercontent.com/29102711/88512242-8d673380-cfe6-11ea-9ff0-5273f2524b5f.png">

**Comment by Miyayes** [comment]
Okay, it looks like whoever owns github.com/brave can verify it with our creators.brave.com account (same one we use for brave.com). cc: @w0ts0n
