### ISSUE TITLE
[Desktop] Update to latest extension view options

### ISSUE THREAD

**Issue by wolfgrrl** [brave/brave-browser#10900]
## Description 
Update to view extensions as a named list instead of only seeing extension icons. See screenshot below.
https://i.imgur.com/xYB77q9.png

## Steps to Reproduce
View extensions not shown in the toolbar.

## Actual result:
Only icons are visible: not the text of the icons as in the newer Chrome versions. 

## Expected result:
See icons and text. 

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave | 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 2004 (Build 19041.388)

**Comment by srirambv** [comment]
I believe this is expected and a new feature from Chromium to group extensions. 

cc: @petemill

**Comment by bsclifton** [comment]
The extensions menu is a feature which can be disabled by going to brave://flags/#extensions-toolbar-menu and setting the value to `Disabled`. Can you give that a shot, @wolfgrrl?

**Comment by rebron** [comment]
@wolfgrrl This is default enabled in 1.13.x. Users who want to hide the menu can go to brave://flags/#extensions-toolbar-menu and set to `Disabled`.
