### ISSUE TITLE
[Desktop] --new-window <url> CLI option doesn't open new window to url

### ISSUE THREAD

**Issue by daytonlowell** [brave/brave-browser#10909]
## Description 
When using the CLI, the `--new-window <url>` option fails to open the provided url. I've only tested this on macOS 10.14.6(Mojave), so it may be working correctly on other platforms.

## Steps to Reproduce
   1. Run `open -a "Brave Browser" --args --new-window 'https://duckduckgo.com'` from the command line.

## Actual result:
Brave is given focus, but the url isn't loaded.

## Expected result:
Brave is given focus, and the passed-in url is loaded.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G6020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes.
- Can you reproduce this issue with the beta channel? 
No
- Can you reproduce this issue with the nightly channel? 
No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No.
- Does the issue resolve itself when disabling Brave Rewards? 
No.
- Is the issue reproducible on the latest version of Chrome? 
No, this issue doesn't occur in Chrome Version 84.0.4147.89 (Official Build) (64-bit).

## Miscellaneous Information:
N/A

**Comment by rebron** [comment]
STR worked for me on macOS 11 Big Sur and 1.13.82. @LaurenWags quick check on Mojave when you have a chance? 
@daytonlowell Still an issue for you with 1.13.82?

**Comment by daytonlowell** [comment]
Yeah, I'm experiencing the same behavior as @LaurenWags, but since it's no longer appears to be Brave-specific, I can make a report on the Chromium project.

**Comment by LaurenWags** [comment]
Great! Thanks for reporting back @daytonlowell 👍

**Comment by bsclifton** [comment]
Tested on `1.19.92` on Windows - this is now working as expected 😄 I wasn't able to find an upstream bug in Chromium bug tracker

@daytonlowell let us know if you're still experiencing this! Link to the Chromium report appreciated too. Thanks 😄
