### ISSUE TITLE
[Desktop] Register with Pulseaudio as Brave instead of Chromium

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#10919]
## Description 

Add Brave branding to pulseaudio.

## Steps to Reproduce

   1. Open a pulse audio frontend like `pavucontrol`
   2. Play a song in Brave
   3. See that it is registered with the pulse audio server as Chromium

## Actual result:

[Current Display](https://i.fluffy.cc/0RJ6f7GvCsx2Sxf4ns0QfXw2fCKTf9ks.png)

## Expected result:
Shows up as Brave.

## Reproduces how often: 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Y
- Can you reproduce this issue with the beta channel?  Y
- Can you reproduce this issue with the nightly channel? Y

**Comment by btlechowski** [comment]
Did not work on 1.13.x, but worked on 1.14.x so I moved the milestone

Verification passed on

Brave | 1.14.42 Chromium: 85.0.4183.59 (Official Build) nightly (64-bit)
-- | --
Revision | 7cc9a5ee672625c38427a839cb1b15efd3128084-refs/branch-heads/4183@{#1216}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6209#issuecomment-663687696
`pavucontrol`
![image](https://user-images.githubusercontent.com/34715963/90299845-f8928000-de97-11ea-8199-da42330b9565.png)

`System audio settings`
![image](https://user-images.githubusercontent.com/34715963/90299933-69399c80-de98-11ea-9ce4-375d9e796996.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.14.68 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6209#issuecomment-663687696

![image](https://user-images.githubusercontent.com/34715963/91675016-284db300-eb3b-11ea-8443-a3eb35ebcd66.png)
