### ISSUE TITLE
[Android] Crash on attempt to open Sync settings when rewards are not available

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#10915]
## Description 
There is a crash on attempt to open Sync settings when rewards are not available

## Steps to reproduce 

   1. Install app on x86 device, where rewards are not available
   2. Goto Sync settings
   3. It will crash

## Actual result 
Crash

## Expected result
No crash

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.11.93

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan: follow STR

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.11.102 BraveModernx86.apk
 * Verified STR from description
   * Confirmed no crash observed.
 * Verified scenario from https://github.com/brave/brave-browser/issues/10819#issuecomment-661095494
   * Confirmed no crash observed.
