### ISSUE TITLE
Block 3rd Party fingerprint doesn't show FP mechanism in blocked list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1091]
## Description 

Block 3rd Party fingerprint doesn't show FP mechanism in blocked list

## Steps to Reproduce

   1. Open https://jsfiddle.net/bkf50r8v/13/ in a new tab
   2. Click on Shields, Click on blocked item for FP
   3. Shows jsfiddle shell as blocked item instead of the type of fingerprinting mechanism blocked

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/45323666-de1c3300-b519-11e8-9d64-371a6fd0396e.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/45323802-4b2fc880-b51a-11e8-9b64-8f1b66f1a7ce.png)

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No shows correct FP mechanisms that are blocked

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
moved to 1.x

**Comment by LaurenWags** [comment]
Reproduced with macOS 10.12.6:

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

**Comment by jeroen7s** [comment]
doesn't block any fingerprints at all for me :/

**Comment by pes10k** [comment]
we no longer report FP attempts bc of move to farbling
