### ISSUE TITLE
Ad notification marked as silent notification doesn't open ad's landing page 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10926]
## Description 
 Ad notification marked as silent notification doesn't open ad's landing page 

## Steps to reproduce 

   1. Enable rewards and ads 
   2. Enable background ads
   3. Ensure ads notification show up as a silent notification
   4. Click on ad notification when the app is in the background or a different app is in focus
   5. Brave opens but landing ad page doesn't load

Scenario 2 (found by @deeppandya )

1. Have notifications in tray
2. Background the app
3. Click on ad notification is not opening the landing page just the launches the app

## Actual result 
 Ad notification marked as silent notification doesn't open ad's landing page 

## Expected result
Should load the ad's landing page

## Issue reproduces how often 
Easy when you least expect
Intermittent when you try to reproduce the issue and the result is _Frustration_

## Issue happens on 
   - Current Play Store version? Yes 
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? Yeah :roll_eyes: 
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Issue originally reported by @maikelmclauflin and @samartnik on beta. I was able to reproduce the issue on release version as well

**Comment by yachtcaptain23** [comment]
Seems like some code involving notification channels was upleveled, but the lines changed in `BraveChannelDefinitions.java` to support Chromium's changes seems to be fine.

**Comment by tmancey** [comment]
@srirambv Can you please retest as discussed with @deeppandya and we are unable to reproduce on 1.15.x. Thank you, Terry

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.15.69 x64 build
- Verified both scenarios from issue description and was unable to reproduce the issue
-------------
Verification passed on OnePlus 6T with Android 10 running 1.15.69 x64 build
- Verified both scenarios from issue description and was unable to reproduce the issue
