### ISSUE TITLE
[Desktop] macOS - Settings window continually expecting me to relaunch

### ISSUE THREAD

**Issue by nexxai** [brave/brave-browser#10921]
## Steps to Reproduce

   1.  Relaunch app

## Actual result:

<img width="1659" alt="Screen Shot 2020-07-25 at 9 36 36 AM" src="https://user-images.githubusercontent.com/4316564/88460564-595f0780-ce5a-11ea-8b76-5fabf6ca09d8.png">

## Expected result:

...not that?

## Reproduces how often: 

Every single relaunch

## Brave version (brave://version info)

Brave | 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.15.6 (Build 19G73)
JavaScript | V8 8.4.371.19
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unsure
- Can you reproduce this issue with the nightly channel? Unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

n/a

**Comment by rebron** [comment]
hi @nexxai Do you remember what setting you changed to show that relaunch button? Some do require relaunch but shouldn't show every time. Also, still an issue with 1.13.82 our latest release version?

**Comment by nexxai** [comment]
Honestly, no, but the issue seems to have resolved itself and I'm just only noticing now.  I'm also not sure when it stopped so I can't even offer any insight into what might have fixed it.  I apologize for not being more attentive, but I'm just going to close this issue since it seems to be good.
