### ISSUE TITLE
[Android] Unable to create wallet on staging

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10929]
## Description 
 Unable to create wallet on staging

## Steps to reproduce 

   1. Install nightly
   2. Enable staging flag and create wallet
   3. Wallet is created but on production, verify it in logs

## Actual result 
 Unable to create wallet on staging

## Expected result
Should create wallet on staging

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.13.45

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by NejcZdovc** [comment]
@srirambv what do you see in logs?

**Comment by srirambv** [comment]
Log shows requests sent to prod endpoint instead of staging. When you try to connect to wallet with Uphold

**Comment by srirambv** [comment]
Blocked on #11114

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112
- Verified able to create a staging wallet and claim grants
--------
Verification passed on Samsung Tab Awith Android 10 running 1.12.112
- Verified able to create a staging wallet and claim grants
