### ISSUE TITLE
LedgerImpl::GetServerPublisherInfo should return info from database if fetch fails

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#10920]
## Description 

Currently, when `LedgerImpl::GetServerPublisherInfo` is called, it will check if the record found in the database is expired or missing, and if so, fetch the data using (ultimately) `ServerPublisherFetcher`, and then return the result to the caller:

https://github.com/brave/brave-core/blob/65ddf913e2dbaa40ce6139297333a7fe87b48e75/vendor/bat-native-ledger/src/bat/ledger/internal/ledger_impl.cc#L1242-L1247

If the fetch fails for some reason (e.g. files are missing on the server, or the server is down) this will end up returning an empty `ServerPublisherInfoPtr`. Instead, we should return the value that came from the database, if available.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.14.67 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6210

<img width="1192" alt="Screen Shot 2020-08-28 at 2 00 47 PM" src="https://user-images.githubusercontent.com/28145373/91601238-45b22f80-e937-11ea-95e6-e8861eda2619.png">

--------
