### ISSUE TITLE
New Tab does not work as of latest build

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#1092]
## Description 

Opening a New Tab via the `+` button next to the current tab does nothing.

Note: Using `New Tab` via the `File` system menu opens the new tab as expected

## Steps to Reproduce

   1. Start Brave
   2. Click on the `+` symbol next to current tab

## Actual result:

   Nothing happens

## Expected result:
   Should open a new tab

## Reproduces how often: 

   100%

### Reproducible on current release:

0.55.2 Chromium: 70.0.3538.12 (Developer Build) (64-bit)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@ryanml is this on mac?

**Comment by srirambv** [comment]
Reproduced on Windows as well

**Comment by srirambv** [comment]
Not sure if this helps the dot on the new tab button is where it creates a new tab. This dot is visible on Windows 7 by default and on Windows 10 only when a theme is installed #983
![newtab](https://user-images.githubusercontent.com/17010094/45395395-ed77ab00-b603-11e8-9861-065ffe32073a.gif)

**Comment by simonhong** [comment]
@srirambv  I assume this also will be fixed by https://github.com/brave/brave-core/pull/430.

**Comment by GeetaSarvadnya** [comment]
Verified on:

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
