### ISSUE TITLE
[Desktop] Brave from the zip package does not start

### ISSUE THREAD

**Issue by angelog0** [brave/brave-browser#10928]
I downloaded the [brave-v1.11.101-win32-x64.zip](https://github.com/brave/brave-browser/releases/download/v1.11.101/brave-v1.11.101-win32-x64.zip), unpacked it and double clicked the `brave.exe` but got a window saying something like this:

**Cannot start the application. The side-by-side mode configuration is not right. See event log or use command line `sxstrace.exe...**

What I need?

BTW, which is the difference between _Silent_ and _not silent_ package installer?

**Comment by rebron** [comment]
@angelog0 Do you need the .zip file versus installing normally? Normal install is via brave.com and you'll get BraveBrowserSetup.exe which you can also find here: https://github.com/brave/brave-browser/releases/tag/v1.13.82 

You can also use the standalone installer.

The silent "stub" or "full" installers suppress the installation screens for enterprise customers or distributors who bundle Brave with other software for their customers.

**Comment by angelog0** [comment]
@rebron, where can I find the standalone installer? Is there some `.zip/portable` package for Brave?

**Comment by rebron** [comment]
@angelog0 from the link I gave you here https://github.com/brave/brave-browser/releases/tag/v1.13.82 scroll down and grab BraveBrowserStandaloneSetup.exe

**Comment by angelog0** [comment]
I am afraid, but I do not install software that way. Usually I open the setup with 7z and copy the content, and do some other needed stuff. In sort, when I do not find a zip, I treat the setup as a compressed archive, often with appropriate scripts. The stup you suggest cannot be opened that way. It is a pity you do not have a similar installer.

**Comment by angelog0** [comment]
I have found that https://brave-browser-downloads.s3.brave.com/latest/brave_installer-x64.exe is the installer I am searching for and it is in some manner related to the last version.

The question is : How can I explore / browse the folder where that installer is so that I can know what `latest` means (1.13.82, 1.15... etc.)

BTW, why do you not add a **normal** zip package to avoid _all_ this work to people which do not like setup installation?

TIA

**Comment by bsclifton** [comment]
@angelog0 sorry for the inconvenience; there is an unofficial site offering a portable version which you may be interested in. They repackage it for our major releases. Check it out at https://portapps.io/app/brave-portable/
