### ISSUE TITLE
[Android] cross promotional Modal for existing user

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#10924]
## Description 
Add cross promotional Modal for existing user. 
Related issue for new user : https://github.com/brave/brave-browser/issues/10571
Related PR : https://github.com/brave/brave-core/pull/6171

## Steps to reproduce 

   1. Update brave app
   2. Open app on 12th day
   3. 

## Expected result
Should show the cross promotional modal

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
<details>
<summary>Verified cross-platform promotional modal is shown 12 days after upgrading from `1.12.113` to `1.13.83`</summary>

English | French
-- | --
![image](https://user-images.githubusercontent.com/17010094/91934894-5c180c80-ece4-11ea-9d52-8869f734db8f.png) | ![image](https://user-images.githubusercontent.com/17010094/91934932-70f4a000-ece4-11ea-84cd-e23a9351156f.png)

</details>

-----------------------

Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
<details>
<summary>Verified cross-platform promotional modal is shown 12 days after upgrading from `1.12.113` to `1.13.83`</summary>

English | German
-- | --
![image](https://user-images.githubusercontent.com/17010094/91937157-435e2580-ece9-11ea-8385-3276a103d6a0.png) | ![image](https://user-images.githubusercontent.com/17010094/91937165-478a4300-ece9-11ea-887c-9acba8db3389.png)

</details>
