### ISSUE TITLE
[Desktop] Caching bug causes user to re-auth twice with Uphold

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#10936]
If an Uphold token gets invalidated and user tries re-auth before restarting browser via Rewards Panel, the re-auth gives a "Try Again' error - if user tries again, user gets new token.

The Try Again error is a bad UX and needs to be resolved by invalidating cache on re-auth.

cc @NejcZdovc

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.14.69 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6235
 * After disconnecting:
<img width="779" alt="Screen Shot 2020-08-31 at 11 33 33 AM" src="https://user-images.githubusercontent.com/28145373/91749373-61177780-eb8f-11ea-86a0-04edaa548330.png">

 * Clicking on `Disconnected` showed login flow:
<img width="396" alt="Screen Shot 2020-08-31 at 11 33 50 AM" src="https://user-images.githubusercontent.com/28145373/91749400-696fb280-eb8f-11ea-9c1c-33900a7dab79.png">

 * After clicking login, received the authorization screen:
<img width="592" alt="Screen Shot 2020-08-31 at 11 34 05 AM" src="https://user-images.githubusercontent.com/28145373/91749434-74c2de00-eb8f-11ea-8c36-9d811a222c0e.png">

 * Confirmed after re-auth, was connected successfully:
<img width="389" alt="Screen Shot 2020-08-31 at 1 44 56 PM" src="https://user-images.githubusercontent.com/28145373/91749886-2bbf5980-eb90-11ea-8f54-230636c4ae76.png">

* Logged follow up issue for removing login flow from Disconnected state - https://github.com/brave/brave-browser/issues/11528

--------
