### ISSUE TITLE
Brave crashes 30 seconds after startup on Mac OS

### ISSUE THREAD

**Issue by regisd** [brave/brave-browser#10938]
Brave Version: 1.11.101  Chromium: 84.0.4147.89
Operating System: Mac OS X 10.15.6

URL (if applicable) where crash occurred:
Crashes even with the default tab,

Can you reproduce this crash?
Yes. 10/10 times

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Brave
2. Wait ~30 seconds

When started from the command line, I got these logs
```
[0727/195134.527913:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee85f0000, 0x2000): (os/kern) invalid address (1)
[0727/195134.631363:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5)
zsh: segmentation fault  /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser
```

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/06220000-319a-ce04-0000-000000000000

**Comment by regisd** [comment]
Just to be sure, I disabled all my extensions.

**Comment by bsclifton** [comment]
@regisd we've had an issue which might be affecting you - curious if you have the macOS Virtual Keyboard enabled?

There's a bug we're tracking for this where intermittent crashes happen:
https://github.com/brave/brave-browser/issues/7546

The other thing to check would be that Sync is disabled. You can find/disable that via brave://flags/#brave-sync

**Comment by Ronald-Baars** [comment]
I have the same issue. Every time I start brave, the fans of my Macbook Pro start running fast, even tho they're normally almost silent. Then the browser just shuts down. No error message, nothing. When you re-open the browser.

@bsclifton 
> [...]
> The other thing to check would be that Sync is disabled. You can find/disable that via brave://flags/#brave-sync

I did have sync enabled. It seems to be fixed when I disable it. Will there be an alternative for Sync in the future? I would love it to sync with my iPad and android phone. Thanks!

**Comment by regisd** [comment]
sync is off by default.
I also did the mistake of turning it on.
Apologies.
