### ISSUE TITLE
[Android] Import wallet fails 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10932]
## Description 
Import wallet was implemented for #9772 but doesn't seem to work

## Steps to reproduce 

   1. Install 1.11.x build
   2. Enable QA pref and import wallet using backup code words
   3. Get a wallet on desktop that has balance and copy the backup code words
   4. Wallet successfully imported message shows up but wallet balance doesn't update

## Actual result 
Import wallet fails

## Expected result
Import wallet should work

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.11.102

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@srirambv does this works now that staging was fixed?

**Comment by srirambv** [comment]
@NejcZdovc  staging was never a problem on RC builds. Issue was on nightly. Just tried again on RC 1.11.102 and import fails.

**Comment by anthonypkeane** [comment]
Was this one that had VG or real BAT? Thanks
