### ISSUE TITLE
Follow up of #10064 - `ads-service` folder is not deleted from profile folder after resetting the Rewards

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10937]
## Description 

Follow up of #10064 - `ads-service` folder is not deleted from profile folder after resetting the Rewards
## Steps to Reproduce

   1. Clean profile 1.12.x
   2. Enable rewards
   3. Click on the settings icon in brave://rewards page and click on Reset option
   4. Click on Reset and ensure rewards reset notification is shown
   5. Rewards is turned off instead of resetting 
   6. Open the profile folder and navigate to the Default folder
   7. `ads-service` folder is not removed even after resetting the rewards ( as per https://github.com/brave/brave-core/pull/5913 `ads-service` folder needs to be removed)
   

## Actual result:

 `ads-service` folder is not deleted from profile folder after resetting the Rewards

## Expected result:

 `ads-service` folder should be deleted from the profile folder after resetting the Rewards

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @tmancey

**Comment by srirambv** [comment]
This is happening due to rewards not being reset. Once #10934 is fixed this would be obsolete as it will reset rewards

**Comment by GeetaSarvadnya** [comment]
@tmancey I have just verified the PR brave/brave-core#6274 nightly. I can reproduce this issue in `1.14.12`

**Comment by GeetaSarvadnya** [comment]
Verified the issue against the RC `1.12.107` and Nightly `1.14.19` builds. The issue is fixed and working fine. The PR which fixed the issue is https://github.com/brave/brave-core/pull/6300

```
Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)
```

```

Brave | 1.14.19 Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)


```
