### ISSUE TITLE
[Desktop] Follow up of #10064- After re-enabling rewards, error message is shown and AC switch is still in OFF state

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10939]
## Description 

 Follow up of #10064- After re-enabling rewards, the error message is shown and AC switch is still in OFF state

## Steps to Reproduce

   1. Clean profile 1.12.x
   2. Enable rewards
   3. Click on the settings icon in brave://rewards page and click on Reset option
   4. Click on Reset and ensure rewards reset notification is shown
   5. Rewards is turned off instead of getting reset
   6. Reload brave://rewards page
   7. Brave rewards is set to OFF in brave://rewards page
   8. Enable the Brave Rewards switch in the settings page
   9. `Uh oh! The Brave Rewards server is not responding. We will fix this as soon as possible.` is shown in wallet balance 
  10. `Auto-Contribute` switch is still OFF

   

## Actual result:

After re-enabling rewards, the error message is shown and AC switch is still in OFF state
![image](https://user-images.githubusercontent.com/38657976/88574436-f939b280-d05f-11ea-9501-79c55606dfbe.png)

## Expected result:

Rewards should be reset

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{# 852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @NejcZdovc

**Comment by srirambv** [comment]
This is happening due to rewards not being reset. Once #10934 is fixed this would be obsolete as it will reset rewards

**Comment by NejcZdovc** [comment]
let's retest when #10934 lands

**Comment by LaurenWags** [comment]
Marking as QA/Blocked as this needs a new 1.12.x build to test

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the STR from the description. 
- Ensured that Rewards reset is working as expected
- Ensured `ads_service`, `rewards_service` and `Rewards.log` and `Publisher_db_info` files are removed from profile folder
-Ensured `brave_rewards` and `brave_ads` sections are removed from `Preference` file
