### ISSUE TITLE
[Desktop] P3A metric for crash reporting status

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#10931]
As discussed in Slack, we want to add a P3A metric to understand how many users have enabled crash reporting https://bravesoftware.slack.com/archives/CDNJ9SVUL/p1594193204285900

```
Q: Is crash reporting enabled?
A1: no;
A2: yes
```

**Comment by iefremov** [comment]
Test plan: check that `Help improve Brave's features and performance` preference is aligned with `Brave.Core.CrashReportsEnabled` p3a metric in local state. Metric is recorded only on startup, so changing the preference doesn't have an immediate effect.

**Comment by LaurenWags** [comment]
@rebron should this one be moved out of the 1.13.x milestone per this comment https://github.com/brave/brave-core/pull/6244#issuecomment-667861961 on the uplift PR?

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```
Brave | 1.14.66 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the test plan from https://github.com/brave/brave-browser/issues/10931#issuecomment-665471016

**Clean profile**
- Verified `Brave.Core.CrashReportsEnabled` response value as `1` when `Help improve Brave's features and performance` is toggled ON in brave://settings
![image](https://user-images.githubusercontent.com/38657976/91582760-defc3880-e96d-11ea-98a4-28bb29408497.png)
- Verified `Brave.Core.CrashReportsEnabled` response value as `0` when `Help improve Brave's features and performance` is toggled OFF in brave://settings
![image](https://user-images.githubusercontent.com/38657976/91583000-3ac6c180-e96e-11ea-9f88-a0720befb8d8.png)

**Upgrade profile** - Upgrade from `1.13.x` to `1.14.x`

- Verified that in `1.13.x` `Brave.Core.CrashReportsEnabled` stat isn't present in brave://local-state file, the stat gets reflected in 1.14.x after the upgrade and the default value is `1` as the `Help improve Brave's features and performance` is toggled ON  by default in brave://settings
![image](https://user-images.githubusercontent.com/38657976/91583643-23d49f00-e96f-11ea-958e-6142f8596d42.png)
- Verified `Brave.Core.CrashReportsEnabled`response value changes to `0` when `Help improve Brave's features and performance` settings is toggled OFF in brave://settings
![image](https://user-images.githubusercontent.com/38657976/91583967-947bbb80-e96f-11ea-8a4b-9c428901af44.png)
