### ISSUE TITLE
[Desktop] Follow up of #10064 - Reset rewards notification is shown forever even after resetting rewards

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10935]
## Description 

Follow up of #10064 - Reset rewards notification is shown forever even after resetting rewards
## Steps to Reproduce

   1. Clean profile 1.12.x
   2. Enable rewards
   3. Click on settings icon in brave://rewards page and click on `Reset` option
   4. Click on `Reset` and ensure rewards reset notification is shown
   5. Repeat the steps 3 and 4 again
   6. Rewards reset notification is shown again and also encountered https://github.com/brave/brave-browser/issues/10934

## Actual result:

Reset rewards notification is shown forever even after resetting rewards
![image](https://user-images.githubusercontent.com/38657976/88569747-837e1880-d058-11ea-9def-359b92af1284.png)

## Expected result:
Once the rewards is reset, rewards reset notification should be removed.

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.12.101 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @NejcZdovc

**Comment by srirambv** [comment]
This is happening due to rewards not being reset. Once #10934 is fixed this would be obsolete as it will reset rewards

**Comment by NejcZdovc** [comment]
let's retest when https://github.com/brave/brave-browser/issues/10934 lands

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` as this needs a new 1.12.x build to test
