### ISSUE TITLE
[Desktop] "verify" wallet link should direct to login flow if wallet does not contain >= 25 BAT

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10944]
## Description 

"verify" link on brave://rewards wallet panel needs to direct to login flow if wallet does not contain >= 25 BAT - follow up to https://github.com/brave/brave-browser/issues/10855.

## Steps to Reproduce

   1. Have less than 25 BAT
   2. Go to brave://rewards
   3. Click on verify link on bottom of wallet panel

## Actual result:

you are directed to login page on uphold

## Expected result:
should get login flow (message box w/ login and cancel buttons) as you do if you click on "Verify Wallet" button

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.12.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a for 1.11.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)


```
- Verified the STR from the description
- Confirmed if you have less than 25 BAT balance, clicking on verify link from brave://rewards page shows the login message
![image](https://user-images.githubusercontent.com/38657976/88909957-61afac00-d279-11ea-9426-f4179b726968.png)
- Verified the steps from https://github.com/brave/brave-core/pull/6220#issuecomment-665021733
