### ISSUE TITLE
[Desktop] Follow up of #10064 - `Rewards.logs` are not removed from profile folder when rewards is reset

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10943]
## Description 

Follow up of #10064 - `Rewards.logs` are not removed from profile folder when rewards is reset

## Steps to Reproduce

   1. Clean profile 1.12.x
   2. Enable rewards
   3. Reset rewards from the settings page
   4. Rewards is turned off instead of getting reset
   5. Open profile folder and navigate to the Default folder
   6. Rewards.log file is not removed from the profile folder
   
   
  

## Actual result:

`Rewards.logs` are not removed from profile folder when rewards is reset

## Expected result:
`Rewards.logs` should be removed from profile folder when rewards is reset

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @NejcZdovc

**Comment by srirambv** [comment]
This is happening due to rewards not being reset. Once #10934 is fixed this would be obsolete as it will reset rewards

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya this is working as expected. logs are deleted, but then file is recreated as it logs success of shutdown for example.
