### ISSUE TITLE
[Desktop] Add padding to `Customize` text to accomodate translations

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#10946]
## Description 
`Customize` text on the NTP needs to expand to support translations.

## Steps to Reproduce

   1. Go to NTP in Japanese version of Brave.
   2. Notice that the `Customize` translation overflows into a second line.
   3. Expected is that `Customize` translations fit into one line.

## Actual result:

<img width="425" alt="Screen Shot 2020-07-27 at 1 03 54 PM" src="https://user-images.githubusercontent.com/5951041/88587083-3f642700-d00a-11ea-97ee-5d541098735d.png">

## Expected result:
One line. [tbd] for screenshot.

## Reproduces how often: 

easy.

## Version/Channel Information:

Brave | 1.12.98 Chromium: 84.0.4147.89 (Official Build) beta (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.16 (Build 20A5323l)

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @karenkliu @ryanml @anthonypkeane

**Comment by karenkliu** [comment]
We should set the bounding box of "Customize" to fit the width of the text so it doesn't wrap in different languages.
