### ISSUE TITLE
[Android] Rate Brave does not send feedback on older Android devices - follow up to 8243

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10945]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/8243

On my Android 5.1 (ARM) and Android 6 (x86) devices the feedback I was submitting did not display on the server.

## Steps to reproduce 

   1. Using 1.11.102, rate Brave with Neutral or Sad feedback
   2. Submit text
   3. Check server

## Actual result 
No feedback displayed

## Expected result
Feedback should be displayed

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: 5.1, 6
   
## Brave version
1.11.102

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @srirambv @deeppandya

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.1.11.50.apk`

  - Verified the STR from brave/brave-browser#10945 (comment) and ensured that the feedback is sent to the server
