### ISSUE TITLE
Follow up of #10064 - `brave_ads` section is not removed from Preferences when rewards is reset

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10940]
## Description 

Follow up of #10064 - `brave_ads` section is not removed from Preferences when rewards is reset
## Steps to Reproduce

   1. Clean profile 1.12.x
   2. Enable rewards
   3. Click on the settings icon in brave://rewards page and click on Reset option
   4. Click on Reset and ensure rewards reset notification is shown
   5. Rewards is turned off instead of getting reset
   6. Reload brave://rewards page
   7. Brave rewards is reset in brave://rewards page ( rewards is set to OFF state)
   9. Open the profile folder and navigate to Default folder and looks for `Preference` file
  10. `brave_ads` section is not removed from Preferences when rewards is reset

## Actual result:

`brave_ads` section is not removed from Preferences when rewards is reset

```
"brave_ads": {
      "ads_per_day": "20",
      "ads_per_hour": "2",
      "ads_subdivision_targeting_code": "AUTO",
      "automatically_detected_ads_subdivision_targeting_code": "IN-KA",
      "enabled": true,
      "idle_threshold": 15,
      "prefs": {
        "version": 7
      },
      "should_allow_ads_subdivision_targeting": false,
      "should_show_first_launch_notification": false,
      "should_show_my_first_ad_notification": true,
      "supported_regions_last_schema_version_number": 0,
      "supported_regions_schema_version_number": 9,
      "were_disabled": false
    },
```
## Expected result:

`brave_ads` section should be removed from Preferences when rewards is reset

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @tmancey

**Comment by srirambv** [comment]
This is happening due to rewards not being reset. Once #10934 is fixed this would be obsolete as it will reset rewards

**Comment by GeetaSarvadnya** [comment]
@tmancey I have just verified the PR https://github.com/brave/brave-core/pull/6274 nightly. I can reproduce this issue in `1.14.12`

**Comment by GeetaSarvadnya** [comment]
Verified the issue against the RC `1.12.107` and Nightly `1.14.19` builds. The issue is fixed and working fine. The PR which fixed the issue is https://github.com/brave/brave-core/pull/6300

```
Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)
```

```

Brave | 1.14.19 Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)


```
