### ISSUE TITLE
[Desktop] Follow up of #10064- Click on BR panel shows `Join Rewards` even after re-enabling rewards from settings page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10941]
## Description 

Follow up of #10064  - Click on BR panel shows `Join Rewards` even after re-enabling rewards from the settings page

## Steps to Reproduce

Scenario 1:

   1. Clean profile 1.12.x staging env
   2. Enable rewards 
   3. Reset rewards via the settings page
   4. Make sure Brave Rewards switch is OFF in settings page after reset
   5. Restart the browser 
   6. Turn ON the `Brave Rewards` switch in the settings page 
   7. AC switch is still in OFF state and error message display in wallet balance ( logged #10939)
   8. Click on BR panel 
   9. BR panel shows `Join Rewards` even after re-enabling rewards from the settings page

Scenario 2: 
   1. Clean profile 1.12.x staging env
   2. Enable rewards 
   3. Reset rewards via the settings page
   4. Make sure Brave Rewards switch is OFF in settings page after reset
   5. Enable rewards from BR panel by clicking on `Enable Brave Rewards` 
   6. Verify that Brave rewards is only enabled in BR panel, rewards is still in OFF state in the settings page 

## Actual result:

Click on BR panel shows `Join Rewards` even after re-enabling rewards from the settings page
Scenario 1:
![image](https://user-images.githubusercontent.com/38657976/88577912-5ab05000-d065-11ea-8925-97a3861d3764.png)

Scenario 2:
![image](https://user-images.githubusercontent.com/38657976/88580213-ee375000-d068-11ea-81e0-53f2e65a9685.png)

## Expected result:

Click on BR panel should not show `Join Rewards` after re-enabling rewards from the settings page

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @NejcZdovc

**Comment by srirambv** [comment]
This is happening due to rewards not being reset. Once #10934 is fixed this would be obsolete as it will reset rewards

**Comment by NejcZdovc** [comment]
let's retest when #10934 lands

**Comment by LaurenWags** [comment]
Marking as QA/Blocked as this needs a new build to test

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the STR from the description. STR 1 and STR 2 are working as expected
