### ISSUE TITLE
[Desktop] Labels are not translated in `Learn more` view of Brave Shields

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10942]
Follow up to https://github.com/brave/brave-browser/issues/10671
The updated labels are not translated

## Steps to Reproduce

   1. Run Brave in German (DE) locale
   1. Navigate to a site
   1. Click on shields
   1. If not already on simple view, click on link for Simple View
   1. Click on "Learn more" link in the middle of the panel.

## Actual result:

Some labels are not translated
![image](https://user-images.githubusercontent.com/34715963/88578509-f8495680-d048-11ea-86e4-ea285b3e5471.png)

## Expected result:
Translated like:
![image](https://user-images.githubusercontent.com/34715963/88579097-c4226580-d049-11ea-89cf-4c64aeb1e0c6.png)

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @mkarolin @rebron

**Comment by mkarolin** [comment]
Looks like `Trackers & ads blocked` and `Fingerprinting blocked` (without qualifiers in parents) did not get uploaded to Transifex.

**Comment by btlechowski** [comment]
Fixed with https://github.com/brave/brave-browser/issues/11395

Verification passed on

Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

Verified STR from the description

![image](https://user-images.githubusercontent.com/34715963/91388090-ef5dc780-e836-11ea-9165-e6fdef446646.png)
