### ISSUE TITLE
favicon.ico not showing up on tab

### ISSUE THREAD

**Issue by Jan-Timon** [brave/brave-browser#10948]
## Description 

If you are looking at a site that has a favicon.ico in the root there is no favicon in the tab (unless the favicon is specified in the meta tags). It is easiest to see if you are looking at an image ( because there are no HTML meta tags).

## Steps to Reproduce

   1. Go to URL https://brave.com/wp-content/uploads/2018/02/brave_logo_2color_reversed.svg

## Actual result:

No favicon.

## Expected result:

Expected to see a favicon. Other browsers show one.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
Hi @Jan-Timon The url you pointed to is a file so the favicon won't show up there `https://brave.com/wp-content/uploads/2018/02/brave_logo_2color_reversed.svg` On brave.com the favicon shows up properly in the tab. 

Closing and marking as worksforme as this is expected behavior.
