### ISSUE TITLE
[Android] Shields doesn't update the label in advanced view when setting is changed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10953]
## Description 
Shields doesn't update the label in advanced view when the setting is changed

## Steps to reproduce 

   1. Install 1.11.102 build
   2. Visit a page and open shields and change Cookies to `Block all cookies`
   3. Click done to go back, label still says `Block cross-site cookies`
   4. Change Fingerprint to `Block all fingerprinting`
   5. Click done to go back, label still says `Block cross-site fingerprinting`

## Actual result 
Shields doesn't update the label in advanced view when the setting is changed

## Expected result
Should probably say what state it is in as per the selected setting

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ALL
   - Device (Phone, Tablet, Phablet): ALL
   - Android version:All
   
## Brave version
1.11.102

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Reported by @LaurenWags. Dont think we need to block the release on this but @anthonypkeane @SergeyZhukovsky  to decide 
cc: @karenkliu

**Comment by deeppandya** [comment]
@srirambv @LaurenWags actually it's expected. that's how we have it in spec. if you feel we should update it, then i will update it right away. it won't take much time.

**Comment by srirambv** [comment]
I am ok with just renaming it Cookies settings and Fingerprint settings. @karenkliu's can decide on the label text

**Comment by deeppandya** [comment]
@karenkliu can you mention about the text i should use for the updated settings ?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.15.69 x64 build
- Verified selecting either `Block all cookies` / `Block cross-site cookies` / `Allow all cookies` maintains the shield title as `Block Cookies`
- - Verified selecting either `Fingerprinting blocked(strict)` / `Fingerprinting blocked(standard)`` / `Allow all fingerprinting` maintains the shield title as `Block Fingerprinting`

---------------

Verification passed on Samsung Tab A  with Android 10 running 1.15.69 x64 build
- Verified selecting either `Block all cookies` / `Block cross-site cookies` / `Allow all cookies` maintains the shield title as `Block Cookies`
- - Verified selecting either `Fingerprinting blocked(strict)` / `Fingerprinting blocked(standard)`` / `Allow all fingerprinting` maintains the shield title as `Block Fingerprinting`
