### ISSUE TITLE
Use Chromium's testing/xvfb.py utility to run tests

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#10967]
## Description 

Running browser tests on Linux with `npm run test -- brave_browser_tests` results on the focus being stolen each time a test pops up a window on the screen to run, which is specially distracting and confusing when working on a single screen computer.

Chromium ships a testing utility in `src/testing/xvfb.py` which solves this problem on Linux by using Xvfb, which provides an X server on a virtual framebuffer, getting all the tests to run in there and therefore not popping out windows continuously.

While this script is only really useful on Linux (where it imposes the dependency to have `xvfb` installed), it behaves as a pass-through script on other platforms, so it should be safe to modify `npm run test` to always use it, regardless of the platform.

## Steps to Reproduce

On Linux:
   1. Grab Brave's source code and compile it
   2. Run `npm run test -- brave_browser_tests`

## Actual result:

Browser tests open windows and steal the input focus from the user continously.

## Expected result:

Browser tests should run without continuously opening windows and therefore stealing the input focus from the user.

**Comment by mariospr** [comment]
As mentioned in https://github.com/brave/brave-core/pull/6289, I gave some more thought to this and I actually think it's not that necessary after all since (1) it only improves Linux and (2) you can always run the tests manually using testing/xvfb.py by doing something like this (which is what I'm doing):
```
testing/xvfb.py  out/Release/brave_browser_tests
```

So I'm closing this PR for now, sorry for the back and forth.

**Comment by LaurenWags** [comment]
@mariospr can this be marked as `closed/wontfix` (or similar) and removed from this milestone per your comment in https://github.com/brave/brave-browser/issues/10967#issuecomment-693236229 ?

**Comment by mariospr** [comment]
Yes, it can be marked as closed/wontfix. Sorry for the noise, I thought "closing" it in github would already do the trick

**Comment by LaurenWags** [comment]
np, thanks for the quick reply!
