### ISSUE TITLE
Lastpass extension crash when clicking on [...] icon in username field

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#1096]
## Description 
Lastpass crashes in Brave Core when you click on the Lastpass icon in the username field. Down in the lower right corner a popup appears, prompting you to reload the extension. This popup looks like:

![image](https://user-images.githubusercontent.com/6763301/45367534-73b5d200-b5af-11e8-88e5-2b0324d34b5d.png)

You can also reload the extension from the extension page, which looks like this:

![image](https://user-images.githubusercontent.com/6763301/45367578-91833700-b5af-11e8-9b87-e099cde52387.png)

I am able to click on the Lastpass icon in some username/password fields, for example on the site `mail.yahoo.com`, but one that seems to be consistenly crashing the extension is `https://invest.ameritrade.com/grid/p/login`.

## Steps to Reproduce

   1. Browse to `https://invest.ameritrade.com/grid/p/login`
   2. Click on the Lastpass icon (three dots) in the User ID field.
   3. The extension crashes and you get a popup in the lower right corner that asks to reload the extension.

## Actual result:
Extension crashes and requests reloading.

## Expected result:
Prompts you to select your userid from the lastpass menu.

## Reproduces how often: 
The first time you attempt to use the Lastpass extension on page load. After reloading the extension it doesn't necessarily work but it doesn't crash either. You can reproduce again by reloading the page(CTRL-R) and then clicking on the Lastpass icon again.

## Brave version (about:brave info) 
Version 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

### Reproducible on current release:
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Possibly related to #236

**Comment by mbacchi** [comment]
This was fixed with this PR: https://github.com/brave/brave-core/pull/421

Closing.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X
