### ISSUE TITLE
Implement Ads tab on brave://rewards-internals with diagnostic information

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#10964]
- Status: `Enabled` / `Disabled`
- Users locale `en_US`
- Catalog id `9b545656-f314-48d7-9c52-978f68491b35`
- Catalog last updated timestamp `06/27/21 05:43:12 PM`
- Last un-idle timestamp `06/27/21 05:43:12  PM`

**Comment by moritzhaller** [comment]
I've added the following:

```
- language code and page classifier model ID
- country code and purchase intent model ID
```

**Comment by tmancey** [comment]
MVP delivered with
```
Users locale [LocaleHelper]
Status: Enabled/disabled [prefs::kEnabled]
Catalog id [prefs::kCatalogId]
Catalog last updated timestamp [prefs::kCatalogLastUpdated]
Last un-idle timestamp [AdsImpl::OnUnIdle]
```
We will write up a document for sign-off from the support and privacy teams for additional data points

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.24 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 12.0 (Build 21A5294g)

Steps:
1. new profile
2. launched Brave
3. loaded `brave://rewards-internals` and clicked on the `Ad diagnostics` tab
4. clicked `Refresh`; confirmed nothing displayed
5. opened `brave://rewards` and enabled Ads
6. clicked `Refresh`; confirmed I got diagnostic info
7. disabled Ads and refreshed `brave://rewards-internals`; confirmed I saw `Ads not initialized, please refresh the page.`

example | example | example
---------|---------|---------
<img width="1125" alt="Screen Shot 2021-08-16 at 5 40 53 PM" src="https://user-images.githubusercontent.com/387249/129647452-7554737c-e362-4dce-be92-80477128e182.png"> |  <img width="1127" alt="Screen Shot 2021-08-16 at 5 41 07 PM" src="https://user-images.githubusercontent.com/387249/129647467-5ff82182-5625-4d48-9651-4f220ae70ac3.png"> |  <img width="1770" alt="Screen Shot 2021-08-16 at 5 39 49 PM" src="https://user-images.githubusercontent.com/387249/129647493-379f2d0e-fd16-4150-b9bc-8a30e23aeed5.png">

**Comment by tmancey** [comment]
@stephendonner would you mind raising an issue for ads as if disabled we should show `Ads enabled: false`. Thanks

**Comment by stephendonner** [comment]
> @stephendonner would you mind raising an issue for ads as if disabled we should show `Ads enabled: false`. Thanks

Filed https://github.com/brave/brave-browser/issues/17535.

**Comment by stephendonner** [comment]
Quick verification, and it'd be good to have this be tested on all platforms, being ads-related 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.30.76 x64 build
- Verified when ads is disabled, diagnostics page shows ads not initialized
- Verified when ads is enabled, diagnostics page shows details about Location/Catalog ID/Last updated datetime stamp

![image](https://user-images.githubusercontent.com/17010094/133637740-5dccf183-3c80-4478-97ff-22f0468fd189.png) | ![image](https://user-images.githubusercontent.com/17010094/133637764-d664d981-c7a3-4dd3-8aa8-ad47561fb7d7.png)
-- | --

---------
Verification passed on Samsung Tab A with Android 10 running 1.30.76 x64 build
- Verified when ads is disabled, diagnostics page shows ads not initialized
- Verified when ads is enabled, diagnostics page shows details about Location/Catalog ID/Last updated datetime stamp

![image](https://user-images.githubusercontent.com/17010094/133637819-bb79656a-07db-4f53-b338-becd18ca3459.png) | ![image](https://user-images.githubusercontent.com/17010094/133637845-af090eb3-e8b9-4aa7-9b18-7cd3bf3ed018.png)
-- | --
