### ISSUE TITLE
[Desktop] Verified Wallet not showing whole balance 

### ISSUE THREAD

**Issue by zoidfarb204** [brave/brave-browser#10966]
## Description 

After verifying my wallet, i found my restore code from my old computer and entered that value.  I continued to have a zero balance in uphold.  When i got my ad credits for the first month the ads received prior to using the restore code was added to the uphold card, but none of the balance after. I have gotten several more months of reward in the browser that does not appear in uphold.  I have tried deleteing the connection between brave and uphold and re verifying with no luck.

![image](https://user-images.githubusercontent.com/7981174/88680862-93c4e080-d0b6-11ea-9ac6-fa9b4cdecab3.png)
![image](https://user-images.githubusercontent.com/7981174/88680908-9de6df00-d0b6-11ea-9ba2-584fb3c4988a.png)

## Steps to Reproduce

   1.  Connect brave to uphold
   2.  Put in restore code.

## Expected result:
Wallet in brave and uphold should match

## Reproduces how often: 

Haven't tried to reproduce

## Brave version (brave://version info)

Brave | 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1909 (Build 18363.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by hollons** [comment]
Hi @zoidfarb204 - thank you for reporting, and for your patience. I can help. Please email me at Steven@brave.com with your Wallet ID which can be found brave://rewards-internals/. Thanks in advance!

**Comment by NejcZdovc** [comment]
@hollons will close this one. If there is anything for me to do please reopen
