### ISSUE TITLE
Refresh token should be used in re-authorization flow (Gemini)

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#10978]
Currently, in the case of an invalid access token, the user presented with a message notifying them of the invalidity, and prompting them to re-connect. The `refresh_token` retrieved when creating the access token should be used it becomes invalid to retrieve another one. The re-connect messaging should only be shown in cases where the refresh action could not be achieved.

Test Plan:
1. Open up the NTP
2. Connect to your Gemini account in the widget, confirm no regressions.
3. Disconnect, then reconnect again, confirm no regressions.
4. It isn't really practical to wait the full period for the token to expire, but what can be done is running:

```
chrome.gemini.refreshAccessToken((success) => console.log(success))
```

Within the console from the NTP. You should it return `true`, and can confirm the new token works appropriately by updating balance or performing a trade.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux

- Verified test plan from issue description
- Verified `Connect to Gemini` opens authorization [link](https://exchange.gemini.com/auth?response_type=code&client_id=165b0c5d-7fa0-4bb7-8966-b407f48a95f1&redirect_uri=com.brave.gemini%3A%2F%2Fauthorization&scope=addresses%3Aread%2Cbalances%3Aread%2Corders%3Acreate&code_challenge=6FLL6kMDJwre9QEUceD0XlrQYLPG4lFDPz0RwfEVu6Y%3D&code_challenge_method=S256&state=olAqe1Cuvts%3D)
- Verified able to sign in using an existing account connects the widget
- Verified registration process works as expected
- Verified `Allow` works fine in authenticating the widget and loads the account details in the widget
![image](https://user-images.githubusercontent.com/17010094/91171771-f79cf200-e6d2-11ea-9d53-c397a7c61a64.png)
- Verified `Deny and exit` loads the error page as expected
![image](https://user-images.githubusercontent.com/17010094/91171806-0be0ef00-e6d3-11ea-8cfb-d71247815111.png)
- Verified denying access token doesn't connect the widget
- Verified logging out from Gemini website doesn't lose the connected state of the widget
- Verified once authenticated, the widget shows the balance in hidden view
- Verified able to trade (buy/sell) once connected
- Verified able to send/deposit crypto once connected and is listed in the widget automatically or via refresh data
- Verified widget state is retained between browser launches
- Verified able to disconnect account via widget menu 
- Verified clearing browser data doesn't disconnect widget or reset the state
- Logged follow up issue #11415
--------------------------------
Verification passed on 

Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)

- Verified test plan from issue description
- Verified `Connect to Gemini` opens authorization [link](https://exchange.gemini.com/signin?redirect=060b4bb6ecb3e2da32b8e82dd6e1e47fc6089123-1598353831746-%2Fauth%3Fresponse_type%3Dcode%26client_id%3D165b0c5d-7fa0-4bb7-8966-b407f48a95f1%26redirect_uri%3Dcom.brave.gemini%253A%252F%252Fauthorization%26scope%3Daddresses%253Aread%252Cbalances%253Aread%252Corders%253Acreate%26code_challenge%3DpPn2PtYZFtIGVBcRn0HOcghRPAy8Iq0lszOBs1CgkHk%253D%26code_challenge_method%3DS256%26state%3DSSE1kpIFQnsB5puJrVcgQSjSfJyg8hbCx9%252FrTK28IrNDR6dfAZA%253D)
- Verified able to sign in using an existing account connects the widget
- Verified registration process works as expected
- Verified `Allow` works fine in authenticating the widget and loads the account details in the widget
- Verified `Deny and exit` loads the error page as expected
![image](https://user-images.githubusercontent.com/17010094/91174979-f7532580-e6d7-11ea-9278-08a0319fa327.png)
- Verified denying access token doesn't connect the widget
![image](https://user-images.githubusercontent.com/17010094/91174971-f3bf9e80-e6d7-11ea-85da-f73d2df30580.png)
- Verified logging out from Gemini website doesn't lose the connected state of the widget
- Verified once authenticated, the widget shows the balance in hidden view
- Verified able to trade (buy/sell) once connected
- Verified able to send/deposit crypto once connected and is listed in the widget automatically or via refresh data
- Verified widget state is retained between browser launches
- Verified able to disconnect account via widget menu 
- Verified clearing browser data doesn't disconnect widget or reset the state
- Encountered issue #11415
--------------------------------
Verification passed on 

Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | macOS Version 10.15.5 (Build 19F101)

- Verified test plan from issue description
- Verified `Connect to Gemini` opens authorization [link](https://exchange.gemini.com/signin?redirect=a679b46eff8772f75b9321796362c226ac5c7232-1598353887164-%2Fauth%3Fresponse_type%3Dcode%26client_id%3D165b0c5d-7fa0-4bb7-8966-b407f48a95f1%26redirect_uri%3Dcom.brave.gemini%253A%252F%252Fauthorization%26scope%3Daddresses%253Aread%252Cbalances%253Aread%252Corders%253Acreate%26code_challenge%3DAsOpnaXc8qzKS%252FHG%252F1XiFxYL8lYXmR6gCLPkFC8vc1g%253D%26code_challenge_method%3DS256%26state%3DpokgOivOBIRkYnfM%252FiieYk0eYz4ceRTxnzuGlxd2GLwv)
- Verified able to sign in using an existing account connects the widget
- Verified registration process works as expected
- Verified `Allow` works fine in authenticating the widget and loads the account details in the widget
- Verified `Deny and exit` loads the error page as expected
![image](https://user-images.githubusercontent.com/17010094/91174990-fd490680-e6d7-11ea-8ddb-39b6c5e82189.png)
- Verified denying access token doesn't connect the widget
![image](https://user-images.githubusercontent.com/17010094/91175001-01752400-e6d8-11ea-87b3-ca5c0c97a3ea.png)
- Verified logging out from Gemini website doesn't lose the connected state of the widget
- Verified once authenticated, the widget shows the balance in hidden view
- Verified able to trade (buy/sell) once connected
- Verified able to send/deposit crypto once connected and is listed in the widget automatically or via refresh data
- Verified widget state is retained between browser launches
- Verified able to disconnect account via widget menu 
- Verified clearing browser data doesn't disconnect widget or reset the state
- Encountered issue #11415
--------------------------------

**Comment by LaurenWags** [comment]
changing to `release-notes/exclude` per discussion with @rebron
