### ISSUE TITLE
Remove unused components from brave://components

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#10972]
## Description
`brave://components` has a list of components with version 0.0.0.0 which we don't install or use. This often confuses users, limit the list to the components we do use.

**Comment by srirambv** [comment]
@jumde there are a few on Android as well does this cleanup  cover both Desktop and Android?

**Comment by jumde** [comment]
I updated the labels to reflect Android/Desktop. Let me know if you prefer a new issue for android.

**Comment by jumde** [comment]
Dupe of https://github.com/brave/brave-browser/issues/8709
