### ISSUE TITLE
[Android] Server error and missing BAT

### ISSUE THREAD

**Issue by Nasheedabdul** [brave/brave-browser#10974]
## Description 
Bat went missing after bug

## Steps to reproduce 

   1. Sometimes shows error in reward section
   2. Estimated Reward went Missing
   3. 

## Actual result 
![Screenshot_20200728_134028_com brave browser](https://user-images.githubusercontent.com/68918787/88698190-5f3b3e00-d123-11ea-9d53-4329de10f0f1.jpg)

## Expected result
Return my missing BAT and solve the error

## Issue happens on 
   - Current Play Store version?Yes
   - Beta build?No

## Device details
   - Install type (ARM, x86):ARM
   - Device (Phone, Tablet, Phablet):Phone
   - Android version: Android version 9
   
## Brave version
v1.10.99

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by anthonypkeane** [comment]
@marshall for follow up on this one once time. Thanks

**Comment by bsclifton** [comment]
Closing as stale; not enough information for us to debug unfortunately (and a lot of time has gone by). In the future, we can loop in @brave/rewards-support
