### ISSUE TITLE
[Desktop] Remove any dependency of brave-disconnect list in Brave

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#10980]
## Description 
With the removal of Disconnect list, we need to remove any dependency (references/scripts or code) in Brave.

May need to check Android and IOS also

## Miscellaneous Information:

Removed filters in Disconnect, subject to removal of file https://github.com/brave/adblock-lists/pull/428

**Comment by pes10k** [comment]
done and done, I wasn't able to find any on audit, so i think we're good here
