### ISSUE TITLE
[Android] Crash when leaving standalone sync chain when offline

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10996]
https://github.com/brave/brave-browser/issues/10856

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.12.106 x64 beta build
- Verified no crash when trying to remove a device when offline
- Verified toast message is shown about sync in progress and unable to delete the sync chain

Light mode | Dark mode
--| --
![image](https://user-images.githubusercontent.com/17010094/89386202-a6fc2f80-d6f8-11ea-8d14-242cb62d99b2.png) | ![image](https://user-images.githubusercontent.com/17010094/89386211-a9f72000-d6f8-11ea-9dd8-097b83ee2951.png)

- Verified sync chain is created after the device comes online
--------
Verification passed on OnePlus 6T with Android 10 running 1.12.106 x64 beta build
- Verified no crash when trying to remove a device when offline
- Verified toast message is shown about sync in progress and unable to delete the sync chain

Light mode | Dark mode
--| --
![image](https://user-images.githubusercontent.com/17010094/89386329-cdba6600-d6f8-11ea-9a4a-2e7583b7f2a8.png) | ![image](https://user-images.githubusercontent.com/17010094/89386337-d14ded00-d6f8-11ea-950f-e247f38a6b0f.png)

- Verified sync chain is created after the device comes online
