### ISSUE TITLE
[Desktop] Verify Wallet drop down not displayed when in Pending state - follow up to 10023

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10995]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/10023
Found while testing https://github.com/brave/brave-core/pull/6140

When in Pending state the wallet drop down should be shown but it is not.

## Steps to Reproduce

1. Clean profile, staging, enable Rewards, claim grant
1. Click on Verify wallet
1. Create a new account (email, password, etc)
1. You're momentarily taken to brave://rewards and then directed back to uphold. 
1. Go to brave://rewards, click on Verify Wallet

## Actual result:

No drop down shown

## Expected result:
Drop down should be shown reflecting "Pending" state

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.13.51 Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc

**Comment by LaurenWags** [comment]
Marking as QA/Blocked as this needs a new 1.12.x build to test

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)


```
- Verified the STR from the description and test plan from https://github.com/brave/brave-core/pull/6252#issue-458602699
- Confirmed pending popup on brave://rewards and panel
![image](https://user-images.githubusercontent.com/38657976/89420210-06395e80-d750-11ea-8260-1df4a62017ce.png)
