### ISSUE TITLE
[Android] Default enabled sync type set to Bookmarks only

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10997]
https://github.com/brave/brave-browser/issues/10775

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.106 beta build
- Verified creating a new sync chain only bookmarks is enabled in sync categories
   <img width=300 src=https://user-images.githubusercontent.com/17010094/89384935-c6925880-d6f6-11ea-97aa-9357c4299c7c.png>

-------------
Verification passed on Samsung Tab A with Android 10 running 1.12.106 beta build
- Verified creating a new sync chain only bookmarks is enabled in sync categories
  <img width=300 src=https://user-images.githubusercontent.com/17010094/89385391-710a7b80-d6f7-11ea-949a-7b2e572ef614.png>
