### ISSUE TITLE
Brave Rewards needs a 'waiter' message when opting in.

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#1099]
## Description 
On first run of browser when enabling Rewards, it is difficult to tell if the browser is responding while waiting for URL responses. Recommending to add a 'please wait' type of message. Also prevent multiple clicking of 'Opt In' (only the first click however, has any effect)

## Steps to Reproduce

   1. Open Brave on clean profile
   2. Enable Rewards
   3. Observe length of time from 'Opt In' click until the main Rewards page is displayed.

## Actual result:
Rewards page 'lags' a response

## Expected result:
The Rewards page should immediately acknowledge that the 'Opt In' button was pressed with a 'waiter' message 

## Reproduces how often: 
Always

## Brave version (chrome://version info)

Brave | 0.55.2 Chromium: 70.0.3538.12 (Developer Build) (64-bit)
Revision | ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS | Mac OS X

### Reproducible on current release:
Yes

### Website problems only:  
~~~- Does the issue resolve itself when disabling Brave Shields?~~~
~~~- Is the issue reproducible on the latest version of Chrome?~~~

### Additional Information
<!--Any additional information, related issues, extra QA steps, configuration or data that might be necessary to reproduce the issue-->

**Comment by NejcZdovc** [comment]
friendly ping to @jenn-rhim for the spinning icon that we talked about 😃

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

* Verified `Creating wallet` spinner is shown when wallet is getting created
* Verified Total line is not shown when amount is added/importing a wallet
