### ISSUE TITLE
[Android] Shields covers 2/3 of screen on landsacpe mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10993]
## Description 
Shields covers 2/3 of the screen on landscape mode

## Steps to reproduce 

   1. Install 1.11.x build
   2. Set device orientation to landscape
   3. Visit a page and open shields covers 2/3 of the screen

## Actual result 
Mobile:
![image](https://user-images.githubusercontent.com/17010094/88803277-23948880-d1a4-11ea-91f1-1d6f34022958.png)

Tablet: 
![image](https://user-images.githubusercontent.com/17010094/88803259-1c6d7a80-d1a4-11ea-8262-4c972430e00c.png)

## Expected result
Should be smaller 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.11.102

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Related tablet issue #10690

**Comment by deeppandya** [comment]
@srirambv i think we should close this issue as it's resolved in #9888

**Comment by srirambv** [comment]
@deeppandya  no this is still not fixed. If you rotate to landscape and open shields it still covers 2/3 of the screen.

**Comment by deeppandya** [comment]
@srirambv what should be the width in your opinion? half of the screen ?

**Comment by srirambv** [comment]
This is in comparision with older shields design

Older shields design | Simpler shields design
-- | --
![image](https://user-images.githubusercontent.com/17010094/93973225-be0be500-fd6b-11ea-849b-b90ff2536113.png) | ![image](https://user-images.githubusercontent.com/17010094/93973238-c532f300-fd6b-11ea-9d87-19491315bc92.png)

I feel device orientation shouldn't change the size of the shields and should maintain the same size but probably @jamesmudgett call on what should be the size
