### ISSUE TITLE
[Webcompat] https://www.mlb.com/news/ inline articles don't display

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#10994]
## Description 
Viewing `https://www.mlb.com/news/`, unable to click on "Continue Reading"

## Steps to Reproduce

   1. View `https://www.mlb.com/news/`
   2. Click on `Continue Reading`
   3. Nothing happens

## Actual result:
Unable to view inline article

## Expected result:
Site being rendered correctly

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes

## Miscellaneous Information:

Suspected filters:
```
@@||www.googletagmanager.com/gtm.js$script,domain=www.mlb.com
@@||www.mlbstatic.com/mlb.com/adobe-analytics/AppMeasurement.js$script,domain=www.mlb.com
!@@||www.googletagservices.com/tag/js/gpt.js$script,domain=www.mlb.com
!@@||www.mlbstatic.com/mlb.com/adobe-analytics/target/2.3.0/at.js$script,domain=www.mlb.com
@@||www.mlbstatic.com/mlb.com/adobe-analytics/VisitorAPI.js$script,domain=www.mlb.com
```

**Comment by rebron** [comment]
@ryanbr working for me. This looks fixed. Going to close this one out. Let's go A's! :-)
Checked on 1.13.82 and 1.14.73
