### ISSUE TITLE
[Android] Remove allow_default ability for all suggested sites

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10998]
https://github.com/brave/brave-browser/issues/10141

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.106 x64 beta build
- Verified typing `binance.com` doesn't show any suggested site
- Verified enabling `Show suggested sites in autocomplete` under Privacy and typing `binance.com` doesn't show Brave suggested URL
-------
Verification passed on Samsung Tab A with Android 10 running 1.12.106 x64 beta build
- Verified typing `binance.com` doesn't show any suggested site
- Verified enabling `Show suggested sites in autocomplete` under Privacy and typing `binance.com` doesn't show Brave suggested URL
