### ISSUE TITLE
[Desktop] Installing Brave on a Debian system with Chrome doesn't automatically set Brave as the default

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#11001]
When a user installs Chrome on Debian, it automatically becomes the default given that [Chrome has chosen an alternative priority above all other browsers](https://source.chromium.org/chromium/chromium/src/+/master:chrome/installer/linux/debian/postinst;l=11-45;drc=ac4d6f43ab804283d2420dd6c92862b325981d1e). On the other hand, when a user installs Brave, [it doesn't automatically become the default](https://community.brave.com/t/brave-does-not-open-links-clicked-when-set-as-default-browser/146608).

Given we expect more users to install Chrome first and then later switch to Brave, I think it makes sense to follow Chrome's lead and bump the alternative priority.

This is what the `x-www-browser` alternative looks like on my machine:
```
$ sudo update-alternatives --config x-www-browser
There are 7 choices for the alternative x-www-browser (providing /usr/bin/x-www-browser).

  Selection    Path                              Priority   Status
------------------------------------------------------------
  0            /usr/bin/brave-browser-stable      200       auto mode
* 1            /usr/bin/brave-browser-beta        150       manual mode
  2            /usr/bin/brave-browser-dev         0         manual mode
  3            /usr/bin/brave-browser-nightly     0         manual mode
  4            /usr/bin/brave-browser-stable      200       manual mode
  5            /usr/bin/chromium-browser-stable   200       manual mode
  6            /usr/bin/firefox                   40        manual mode
  7            /usr/bin/google-chrome-stable      200       manual mode
```

Note: the priority is only taken into account when the user hasn't made a selection. A user's choice is never overridden.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.14.68 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6253

![image](https://user-images.githubusercontent.com/34715963/91677676-b2017e80-eb43-11ea-9cbb-e73751cdbe0c.png)
