### ISSUE TITLE
[Desktop] Update icon for macOS Big Sur?

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#11002]
## Description 
Suggestion to update the icon for the macOS version of Brave to match the new macOS Big Sur icon style?

## Steps to Reproduce

   1. Upgrade to macOS Big Sur.
   2. Look at the Apple icons.
   3. Look at the Brave icon.

## Actual result:

![Screen Shot 2020-07-29 at 2 50 01 PM](https://user-images.githubusercontent.com/21181118/88846180-dcf65c80-d1aa-11ea-901b-67a113d40a5a.jpg)

## Expected result:
User new Brave icon set for Big Sur: https://drive.google.com/open?id=1jIDrXtv2tHNtlz4Qiqj4Lkbfb2ft9LIX

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
All of them

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Sort of...
![Screen Shot 2020-07-29 at 2 50 30 PM](https://user-images.githubusercontent.com/21181118/88846286-0b743780-d1ab-11ea-9fa8-e69360ed51b6.jpg)

**Comment by thefallofbecause** [comment]
Third party apps should not have to conform to Apple's choice of style and should remain consistent with their own branding.

I would not want LibreOffice, Thunderbird, GIMP or any of my other third party apps to change their icon for no real reason.

**Comment by gottabeleGIT** [comment]
I completely understand that and agree to an extent. However, in this issue, I'm mainly referring to the macOS version of the app as I would probably not expect cross-platform apps to use the Big Sur style on Windows and Linux for instance. Now, if there is no way to change the icon for just the macOS app without affecting the other platforms, that is understandable and I can close the issue.

**Comment by bsclifton** [comment]
cc: @rebron @karenkliu

**Comment by thefallofbecause** [comment]
Unless Apple impose a style guide on app icons on MacOS there should not be a change (and if they do want to do this, Apple should borrow Android's method of checking the icon programmatically and putting it in an appropriately sized box if it does not conform).

No other third party apps I used have adopted Apple's icon style (and even Apple's own apps have 2+ different styles on Mojave):
<img width="1414" alt="Screen Shot 2020-08-03 at 1 42 16 pm" src="https://user-images.githubusercontent.com/8562416/89174895-48677200-d58f-11ea-932b-7b0889b93b8f.png">


The Big Sur icon style may last one version, it may last 10, it may last 100 (but I doubt it). Only Apple can say (and even they probably don't know right now), so Brave would need to change their icon again the next time Apple decides on a stylistic change to their system app icons.

**Comment by gottabeleGIT** [comment]
Alright, I guess that makes sense. At this point I’ll leave it up to Brave then. If they’re interested, they’ll do it and if not they won’t ¯\_(ツ)_/¯

**Comment by bradleyrichter** [comment]
@gottabeleGIT Thanks for your contribution. We will investigate what is the best app icon approach for Brave in Big Sur. We can certainly use a specific set for Mac OS if needed.

At a minimum, we will reduce the icon height to fit better on the dock mixed in with the new iOS-like approach they will be 
 using.

**Comment by cperezabo** [comment]
It's been months since I created #8662. If a simple resize which cannot take more than 30 seconds is taking months, I don't want to imagine how long will it take to make the resize plus put it in a square frame...

**Comment by bsclifton** [comment]
@cperezabo I can understand the frustration and I'm sorry ☹️ While this might be a 30 second task, it would need to be reviewed and tested... and there are a lot of competing tasks. If you check our issue log, there are over 2,600 issues and some are really bad (crashing, always showing reCAPTCHA, needing to upgrade Chromium to get latest security fixes, etc). @rebron assigned this issue and https://github.com/brave/brave-browser/issues/8662 a P4 which means it's fairly low on our list (but it is on our list)

**Comment by cperezabo** [comment]
I understand, but come on guys, we are not asking to change the color of a random button... It's the app icon in the macOS dock, which has some globally followed sizes and shapes that you are not respecting at all, and it will be even more noticeable with Big Sur in some days.

**Comment by bsclifton** [comment]
@cperezabo fix by @simonhong up now in https://github.com/brave/brave-core/pull/7086

**Comment by karenkliu** [comment]
@rebron New iconset added!

**Comment by simonhong** [comment]
@karenkliu can you new add icon for development also?
![image](https://user-images.githubusercontent.com/6786187/100682278-150be700-33b9-11eb-9cae-046ec563bc5d.png)

**Comment by karenkliu** [comment]
> @karenkliu can you new add icon for development also?
> ![image](https://user-images.githubusercontent.com/6786187/100682278-150be700-33b9-11eb-9cae-046ec563bc5d.png)

Hi @simonhong , did you still need this from me?

**Comment by simonhong** [comment]
@karenkliu It's not mandatory because this icon is only used for local unofficial build.
but I think it would be good to have same style icon for development icon.
If you share it, I'll udpate.

**Comment by bsclifton** [comment]
@simonhong should this be re-opened after https://github.com/brave/brave-core/pull/7308 was merged?

**Comment by kjozwiak** [comment]
> @simonhong should this be re-opened after [brave/brave-core#7308](https://github.com/brave/brave-core/pull/7308) was merged?

Re-opening as this was reverted as per the above.

**Comment by simonhong** [comment]
Will close this because @rebron created another issue for icon update. - https://github.com/brave/brave-browser/issues/13005

**Comment by zevrix** [comment]
Brave icon now has changed - and it's really bad. Please restore the original Brave icon - which is a masterpiece.
