### ISSUE TITLE
[Desktop] SR's topsites are disappeared while toggling themes option

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#11009]
## Description 

 SR's topsites are disappeared while toggling themes option.
This is regression from https://github.com/brave/brave-core/pull/6047

## Steps to Reproduce

Scenario 1 - Clean version
   1. Setup SR and launch browser
   2. Load NTP and check default Top sites are visible
   3. Goto themes option and choose `Brave default images`
   4. Reload NTP and check default SR Top sites are still visible

Scenario 2 - Updated version
  1. Setup SR with stable version (1.11)
  2. Load NTP and check SR is loaded in NTP.
  3. Close window and copy stable's user data to development(or nightly)
  4. Launch development or nightly version
  5. Check NTP loads SR top sites properly
  6. Goto themes option and choose `Brave default images`
  7. Reload NTP and check default SR top sites are still visible

## Actual result:

Default SR top sites are not visible

## Expected result:
Default SR top sites are visible

## Reproduces how often: 

Easily

## Brave version (brave://version info)

browser has this issue since 1.13.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.13.76 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the STR from the description

**Scenario 1 - Clean version**
- Verified that default Topsites are displayed for SR profile in NTP's
![image](https://user-images.githubusercontent.com/38657976/90549765-9776ef00-e1ac-11ea-85a5-62966595a57f.png)
- Verified that default Topsites are still visible in NTP's when Theme changes to `Brave default images`
![image](https://user-images.githubusercontent.com/38657976/90549816-ad84af80-e1ac-11ea-8699-82f09dc4326c.png)
