### ISSUE TITLE
[Desktop] [Webcompat] Playstation Logins not working - follow up to 8629, 9987

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11000]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/8629, https://github.com/brave/brave-browser/issues/9987

Unable to login on store.playstation.com

## Steps to Reproduce

   1. Visit `https://store.playstation.com/` with default shields.
   2. Click on Sign In (upper right corner)
   3. Enter email, click Next
   4. Enter password, click Sign In

## Actual result:

Unable to login
<img width="436" alt="Screen Shot 2020-07-29 at 2 45 47 PM" src="https://user-images.githubusercontent.com/28145373/88840536-a6204680-d1aa-11ea-88af-61da129c8f35.png">

## Expected result:
no error, able to login

Note - if I take shields down, login works.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  yes
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

cc @pes10k @rebron @ryanbr @brave/legacy_qa

**Comment by tedens** [comment]
I disabled brave shields and this still does not allow logins. I have to use chrome just for this website so far as it works on it.

**Comment by ryanbr** [comment]
With `Ephemeral Storage` enabled, this seems to be working @LaurenWags @tedens  is this still an issue?

**Comment by LaurenWags** [comment]
@ryanbr unfortunately I no longer have this account to confirm.

**Comment by ryanbr** [comment]
Okay, closing report. I was able to sign in without issue. Works for me

**Comment by LaurenWags** [comment]
sounds good, thanks @ryanbr!
