### ISSUE TITLE
[Android] Wallet doesn't show balance if rewards is turned off

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11015]
## Description 
 Connected wallet doesn't show balance if rewards is turned off

## Steps to reproduce 

   1. Connect wallet to uphold
   2. Turn off rewards not reset
   3. Open BR panel, shows spinner loading but wallet balance never updates

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/88924560-5b1a3800-d26b-11ea-8859-4a80e665436b.png>

## Expected result
Should show wallet balance 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
GPS Build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
This happens regardless of wallet is connected or not. Turning off rewards and opening panel doesn't show the wallet balance

**Comment by deeppandya** [comment]
@srirambv this should be fixed with BRE. can you please verify ?

**Comment by srirambv** [comment]
This is not valid any more. Closing the issue.
