### ISSUE TITLE
Align App Channel Iconography and Naming Convention

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#1101]
## Description 
There seems to be a multitude of Brave app icons and naming conventions for the various channels we are soon to release floating around. Most immediately we are using a dated app icon for the Dev build and have some sizing errors for the App icons themselves. They are currently sized at 512x512 and do not fill the whole art board whereas they should be 1024x1024. 

Also, we currently have mixed naming conventions for the App versions (some including "Browser" and some not)  and the titles of the apps contain hyphens which results in looking unpolished in the dock. 

A few other tiny issues include needing to update the typeface in the labels from Helvetica to Brave's headline brand standard Poppins. There is some confusing color theory around the legacy Nightly icon as it is easily confused with a Dev icon since they are both blue. Lastly we included a version of the Brave logo without a face which isn't ideal even in instances of internal use so that was updated to correctly refer to the monochrome version which I believe is being used now currently anyway so no noticeable update will happen there.

## Legacy Channel Iconography
![image](https://user-images.githubusercontent.com/29072694/45403228-24eb5500-b60e-11e8-9df4-86e60c926389.png)

## Updated Iconography
![image](https://user-images.githubusercontent.com/29072694/45403299-7f84b100-b60e-11e8-8e07-e095d0bd021b.png)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified Beta and Dev build icons

**Comment by kjozwiak** [comment]
Closing issue as the `dev` & `beta` iconography has been checked on the three platforms. Unfortunately, we can't check `Release`, but it should be pretty obvious if there's issues once we get the builds. I don't think there's any need to wait till we get released builds.

Plus, going through #1105 will result in double checking this as well. 👍
