### ISSUE TITLE
Allow users to disable User notification ads but keep sponsored image ads

### ISSUE THREAD

**Issue by nsklaus** [brave/brave-browser#11018]
## Description 
feature request: please allow zero ads popup.
i would like to keep brave rewards system activated. i like getting rewards for viewing pictures in the new tab. but i dislike ads notification popup. as of now if i want to keep brave rewards active i must choose at minimum 1 ad per hour.
i would like to have a choice for zero ads. i'll earn less, but i could then keep brave rewards activated without getting notification popups, which are really annoying.

## Steps to Reproduce

   1. activate brave rewards
   2. see you are getting forced to allow at minimum: 1 ads popup per hour.
  

## Actual result:
getting ads notification popups

## Expected result:
i would like zero ads notification popup

## Reproduces how often: 
100% of the time. as long as brave rewards is active, i'm gettings ads notification popups from time to time.

## Brave version (brave://version info)

Brave | 1.13.51 Chromium: 84.0.4147.105 (Official Build) unknown (64-bit)
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Linux

(i am using a variant of arch linux, called artix, basicaly: arch without systemd)

## Version/Channel Information:
reproducible on all channels/versions.

- Can you reproduce this issue with the current release? 
yes
- Can you reproduce this issue with the beta channel? 
yes
- Can you reproduce this issue with the nightly channel? 
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
no
- Does the issue resolve itself when disabling Brave Rewards? 
yes (but the whole point is to keep brave rewards open, so disabling it makes no sense)
- Is the issue reproducible on the latest version of Chrome? 
no (chrome doesn't have the brave rewards system)

## Miscellaneous Information:
i prefer to earn less, but not being annoyed with ads notification popups.
earning with just the pictures in newtab is ok for me. if i wanted to earn more then i could crank up the ads number to 5 per hours. what is missing is the "zero ads per hour" option.

**Comment by srirambv** [comment]
You can turn off Ads individually which is same as 0 ads

**Comment by nsklaus** [comment]
@srirambv 
how do i do that "turn off Ads individually" ?

**Comment by rebron** [comment]
@nsklaus Turn off ads via here at brave://rewards Turning off ads is the same as your suggestion for showing 0 ads per hour.

![Screen Shot 2020-09-11 at 9 20 34 AM](https://user-images.githubusercontent.com/5951041/92949746-73f03e80-f410-11ea-9faf-63473bc72a28.png)

**Comment by nsklaus** [comment]
> @nsklaus Turn off ads via here at brave://rewards Turning off ads is the same as your suggestion for showing 0 ads per hour.
> 
> ![Screen Shot 2020-09-11 at 9 20 34 AM](https://user-images.githubusercontent.com/5951041/92949746-73f03e80-f410-11ea-9faf-63473bc72a28.png)

no it's not.
it is not the same as my suggestion. when i turn off ads, i cannot see the rewards in the new tab anymore, and i'm not receiving or getting paid bats for the pictures displayed in the new tab. have you even read the text i wrote for this issue ?
the issue is about to keep receiving rewards but only from pictures displayed in new tab, and stop being annoyed by ads notification pop ups. in case you still did not understand, let me repeat: --> *keep the rewards system open* <--
what you propose is to close the reward system. it is of course not the same. it's not even a workaround. it doesn't even make sense, considering the content of this issue i created. please read it again.

**Comment by nsklaus** [comment]
@rebron 
is this you being serious here ? i opened my issue by saying: "i would like to keep brave rewards system activated..."
and what do you propose ? "disable brave rewards system".

may i suggest a good night sleep and in the morning, you read this issue again. 
you will see that your reply, and motive for closing this issue was innapropriate. 
you misunderstood the point of this issue. the goal is to keep getting rewards. 
if people do what you propose, they won't be getting any.

**Comment by bsclifton** [comment]
@nsklaus you can turn off the sponsored images too. `Customize` in the bottom right will pop open a settings screen and then you can toggle off `Show Sponsored Images`. The backgrounds aren't tied to the "Ads" toggle that @rebron linked to

Right now, Rewards is completely separate from Ads. With ads disabled, you can still tip, see the verification status for different sites, verify with Uphold, and see your balance. I re-read your post a few times to make sure I'm not missing something, but I think you're confusing Ads with Rewards. There is no option to disable ads and get paid for ads

**Comment by nsklaus** [comment]
@bsclifton 
how is it possible that noone understand the point of this issue ? i will try to make it more simple to understand.
- the point is to keep sponsored images. 
- the point is to keep rewards system open. 
- the point is to keep seeing bat rewards in new tab. 
- the point is to lower the ads popups to zero per hour. (meaning sponsored images are the only source of bat income).

**Comment by bsclifton** [comment]
@nsklaus you can only earn rewards if you have the Ads toggle enabled.  The reason folks have had a hard time understanding is because sponsored images and ads are not related, at least not in their current form. 

Maybe @jsecretan can help provide some more detail, but I believe at a basic level that the earnings for sponsored images are divided equally among people who have ads enabled (or something like this). If you don't have ads on, you aren't eligible

**Comment by bsclifton** [comment]
@nsklaus more information available here:
https://brave.com/sponsored-images-now-available-on-all-brave-platforms/

**Comment by nsklaus** [comment]
@bsclifton 
the problem is that if i disable ads/rewards system, i do not get bat income from sponsored images anymore. also newtab doesn't display my wallet and the bats i earned so far anymore. there should be a way to keep wallet open, keep getting bat icome from sponsored images, and getting no popups ads at all (that is why i suggested a zero ads per hours setting).

**Comment by jsecretan** [comment]
Hi @nsklaus I think I understand what you are going for here.  Right now, there is no way to choose only to receive sponsored images.  We have some changes that are planned in the way we reward users for sponsored images.  When that is done, we can put in a UI to allow users to choose not to receive one type of Brave Ad or another.  I'm going to re-open this and rename it to reflect that.

**Comment by nsklaus** [comment]
@jsecretan and @bsclifton 
thank you both. this issue have been understood. that is nice to see.

**Comment by tmancey** [comment]
@nsklaus I am working on https://github.com/brave/brave-browser/issues/10488 which will resolve "We have some changes that are planned in the way we reward users for sponsored images", once this is complete we will revisit this issue. Thanks

**Comment by tmancey** [comment]
Blocked by https://github.com/brave/brave-browser/issues/10488

**Comment by cryptojennie** [comment]
+1 from the Community: https://www.reddit.com/r/BATProject/comments/lmtywf/new_tab_ads_not_counting/

**Comment by tmancey** [comment]
Closing issue as users can now enable ads but disable ad notifications by choosing 0 ads per hour from brave://rewards
