### ISSUE TITLE
[Android][Follow up of #8360] No ad grant notification shown on SI tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11010]
## Description 
Ad grant message on SI tab is not shown [Follow up of #8360]

## Steps to reproduce 

   1. Install 1.11.x build
   2. Get an Ad grant
   3. Open a tab with SI, no ad grant notification shown on SI tab

## Actual result 
No ad grant notification shown on SI tab

## Expected result
Ad grant notification shown on SI tab

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version:All
   
## Brave version
1.11.x branch

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Other text changes mentioned in #8360 works as expected. 
cc @SergeyZhukovsky @anthonypkeane @bsclifton

**Comment by kjozwiak** [comment]
Removing from https://github.com/brave/brave-browser/milestone/128 after discussing with @SergeyZhukovsky and @bsclifton. We don't have time to address this in `1.12.x` as `Sync v2` needs to go out on August 12th. Users can still claim their ad grants via the rewards panel.

**Comment by anthonypkeane** [comment]
Slack Link: https://bravesoftware.slack.com/archives/C0816QH3R/p1597264190489500?thread_ts=1597216500.464400&cid=C0816QH3R

**Comment by deeppandya** [comment]
@Miyayes is this still relevant ?

**Comment by Miyayes** [comment]
I don't think so. Will close out.
