### ISSUE TITLE
[Desktop] [Android] [Webcompat] Home Depot curbside checkin form blocked

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#11017]
## Description 

Using the link provided in a Home Depot email for curbside pickup the web page renders but the form used to input your information only works with shields down on both Android and Desktop.

The URL is: https://www.homedepot.com/c/pu?s=1521&o=WM########&cm_mmc=ecc-_-THD_READY_FOR_PICK_UP-_-V1_M1_CA-_-AT_STORE&ecc_ord=WM########

The order number (in 2 places above) is in the format WM########, with 8 numbers after the letters WM. If you generate any set of numbers it probably works, in fact I tested with `12345678` which does work.

This form should be displayed when shields are up. I am using standard not aggressive shield settings.

## Steps to Reproduce

   1. Browse to URL with 8 numbers replacing the 8 # symbols in 2 locations in the url above.
   2. 
   3. 

## Actual result:

No form displayed.

## Expected result:
Form displayed.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Version 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
AND
Brave on Android 1.10.99, Chromium 83.0.4103.116

## Version/Channel Information:

Dev and release channels on desktop
release channel on android

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
This should help @mbacchi   give it 48hrs, re-start the Brave application also. Will keep this open to confirm everything is working.

**Comment by ryanbr** [comment]
Can't reproduce this, safe to close @mbacchi ?

**Comment by bridiver** [comment]
I had this same problem and I had to go to brave://components and update `Subresource Filter Rules` and then restart. Neither of those steps should be necessary so I think there might be an issue with the component update server and potentially the code that updates the list in the browser when the new component is downloaded

**Comment by srirambv** [comment]
Removing from 1.13.x as this was added into milestone after release went out.

**Comment by bridiver** [comment]
@srirambv technically there is no milestone for this because it was a component update, not a brave update. cc @kjozwiak

**Comment by kjozwiak** [comment]
As per the process, shield issues that have been fixed by the component updater should follow the following process:

* Once closed, add the `closed/fixed-by-component-update` label
* Please don't place issues with `closed/fixed-by-component-update` into milestones
* Doesn't need QA verification

**Comment by bridiver** [comment]
@kjozwiak should we specify the component version number somewhere?
