### ISSUE TITLE
[Desktop] <video>, <audio> elements not loading

### ISSUE THREAD

**Issue by awl19** [brave/brave-browser#11016]
## Description 

On YouTube videos I get playback errors. On Reddit I just get stalled videos. On Zendesk (Support Tickets) when I try listening to phone calls, they stall. I've disabled all extensions, the Brave Shield, and Brave Rewards. I've also deleted ALL cookies/cache and browser history. My video drivers weren't up-to-date, so I updated those. Restarted my PC many times and literally just after this started happening I replaced my modem - for unrelated lag issues, but the point is, that didn't do anything either.
The issue is not occuring in Chrome or Firefox, both of which are up-to-date.

Edit: Seems to be affecting .gifv files as well - like, not even loaded from within a web page, but loaded directly from the URL. For instance, https://i.imgur.com/HBnUyLW.gifv is stuck on the 1st frame.

The timing seems to coincide with the recent update 3 days ago, but if I'm honest I only started noticing a problem 2 days ago.

## Steps to Reproduce

   1. Be on Windows 10 64-bit
   2. Be in Brave browser with my version (listed below)
   3. Load any website mentioned above and try to load a video or sound element

## Actual result:

`<video>` and `<audio>` elements not loading

## Expected result:
`<video>` and `<audio>` elements should load

## Reproduces how often: 

Every time I load a web page with `<video>` and `<audio>` elements

## Brave version (brave://version info)

Brave | 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1909 (Build 18363.959)
JavaScript | V8 8.4.371.22
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,PassiveMixedContentWarning,AutoupgradeMixedContent,WebUIDarkMode,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,TextFragmentAnchor,VideoPlaybackQuality,UseButtonTranslateBubbleUI,SmsReceiver,TabHoverCards,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-sync
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Drew\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-59e286d0

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Not sure
- Can you reproduce this issue with the nightly channel? 
Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome?
No

**Comment by ratcashdev** [comment]
same on linux. Videos not playing if #ignore-gpu-blacklist is enabled. Previous version (1.10) worked just fine.
```
Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) unknown (64-bit)
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Linux
```

**Comment by awl19** [comment]
@ratcashdev Can you tell me how to disable #ignore-gpu-blacklist?

**Comment by ratcashdev** [comment]
@awl19 brave://flags/#ignore-gpu-blacklist

**Comment by awl19** [comment]
@ratcashdev Appreciate it. Looks like it was already disabled for me. I tried enabling it just to see if that'd do anything, but...nothing.

**Comment by awl19** [comment]
Okay... suddenly everything is working again, but no new update has been issued since I created the topic. Interesting.
Closing the topic for now.
