### ISSUE TITLE
[Android] AC list isn't always sorted based on the attention percentage

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11014]
## Description 
AC list isn't always sorted based on the percentage value

## Steps to reproduce 

   1. Enable rewards and add a bunch of sites to the list
   2. Open auto-contribute list
   3. List isn't ordered as per percentage

## Actual result 
![incorrect ac list](https://user-images.githubusercontent.com/17010094/88924015-86e8ee00-d26a-11ea-9597-2c536d819acb.gif)

## Expected result
Should be ordered as per the attention percentage

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
GPS build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by anthonypkeane** [comment]
This will be resolved in #10472

**Comment by Miyayes** [comment]
If this is still an issue @srirambv in the latest version, then please refile. Lots has changed.
