### ISSUE TITLE
[Android] Fix crash on opening search engine in debug build

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#11022]
## Description 
```
java.lang.IllegalAccessError: Method 'int org.chromium.chrome.browser.search_engines.settings.BraveBaseSearchEngineAdapter.getSearchEngineSourceType(org.chromium.components.search_engines.TemplateUrl, org.chromium.components.search_engines.TemplateUrl)' is inaccessible to class 'org.chromium.chrome.browser.search_engines.settings.SearchEngineAdapter' (declaration of 'org.chromium.chrome.browser.search_engines.settings.SearchEngineAdapter' appears in /data/app/com.brave.browser_default-V4jE6tH96mULLXfaqAQ7TA==/base.apk!classes3.dex)
        at org.chromium.chrome.browser.search_engines.settings.SearchEngineAdapter.refreshData(SearchEngineAdapter.java:183)
        at org.chromium.chrome.browser.search_engines.settings.SearchEngineAdapter.start(SearchEngineAdapter.java:124)
        at org.chromium.chrome.browser.settings.BraveSearchEngineAdapter.start(BraveSearchEngineAdapter.java:37)
        at org.chromium.chrome.browser.settings.BraveSearchEnginePreference.onStart(BraveSearchEnginePreference.java:45)
```

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan: double check that you can change search engine from settings

**Comment by kjozwiak** [comment]
@samartnik does this only apply to debug builds? I don't think QA goes through debug builds. Unless it's just a double check in release builds to make sure that you can select SE from `Settings` without any issues 👍

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.13.81 x64 build
- Verified opening search setting doesn't crash the build
- Verified changing search engine doesn't cause browser to crash
---------
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build
- Verified opening search setting doesn't crash the build
- Verified changing search engine doesn't cause browser to crash
