### ISSUE TITLE
Refreshing/restarting browser after resetting wallet shows Rewards settings page

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#11024]
## Description 
After resetting your wallet, if you refresh or restart the browser, instead of remaining on the Rewards welcome page you're taken to the Rewards settings page.

## Steps to Reproduce

   1. Clean profile
   2. Enable Rewards
   3. Reset your wallet using the Gear icon
   4. Confirm the reset
   5. When you see the Rewards welcome page, refresh or restart the browser

## Actual result:

You're taken to the Rewards settings page.

## Expected result:
You remain on the Rewards welcome page.

## Reproduces how often: 

Easily.

## Version/Channel Information:

Master.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6285 
- Verified the STR from the description
- Ensured that Rewards welcome page is displayed after rewards reset, and refresh rewards welcome page still displays the rewards login page

**After rewards reset -> Rewards welcome**
![image](https://user-images.githubusercontent.com/38657976/89421690-fcb0f600-d751-11ea-9e57-71fc06423eb5.png)

**Refresh Rewards welcome page**
![image](https://user-images.githubusercontent.com/38657976/89421792-1c481e80-d752-11ea-831d-96bcfc067ed2.png)

- Additional testing on rewards reset is covered in https://github.com/brave/brave-browser/issues/10934#issuecomment-669177694
