### ISSUE TITLE
[Android] Brave browser (opened from an app) shows the Lion icon over the content (ex: the 'Tweet' button)

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#11036]
Brave browser custom tabs have the Brave icon and 'Tweet' icon on mobile.twitter.com. This was also reproducing on other sites as well.

Brave browser on Android Version 1.10.99
And Nightly 1.13.51 on Android 10.

![Screenshot_20200731_151717](https://user-images.githubusercontent.com/68992260/89023751-b4ed3180-d341-11ea-86b8-890abe554df5.jpg)

**Comment by srirambv** [comment]
Can you add steps to reproduce? Are you opening custom tabs via twitter app?

**Comment by Bluedot221** [comment]
@srirambv 


>Can you add steps to reproduce? Are you opening custom tabs via twitter app?

 ###Steps to reproduce


1. Have the Twitter Android app installed
2. Click on a link in the Twitter app (I opened the one of The Verge's article link)
3. See the custom tab open like the screenshot I attached.

**Comment by samartnik** [comment]
dup of https://github.com/brave/brave-browser/issues/9113
