### ISSUE TITLE
[Desktop] re-enabling Rewards from NTP widget doesn't update display of widget

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11039]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/9526

If you try to re-enable rewards from the Rewards NTP widget it doesn't look like it worked, but if you go to brave://rewards page you can see that Rewards are toggled on. Additionally, BAT Ads Service and BAT Ledger Service are running in task manager. A page refresh fixes the display of the widget.

## Steps to Reproduce

   1. Clean profile 1.12.x, open Task Manager. See that BAT Ads and Ledger services are not running.
   2. Enable Rewards (I did this from panel). See BAT Ads and Ledger Services are now running.
   3. Open a new tab, navigate to brave://rewards.
   4. Toggle Rewards off. See BAT Ads and Ledger Services are no longer running.
   5. Close brave://rewards page.
   6. Open NTP
   7. Click Turn on Rewards button (may need to dismiss SI message depending on which NTP image is being shown to you)

## Actual result:

Widget turns from purple (not enabled) to black (enabled) but still displays the messaging to re-join. Services (BAT Ads and BAT Ledger) are running as expected. Page refresh or clicking on Try Again fixes this. Note - Rewards is actually enabled, this seems like a display issue. 

<img width="942" alt="Screen Shot 2020-07-31 at 9 52 56 AM" src="https://user-images.githubusercontent.com/28145373/89041690-ca4b6700-d313-11ea-94db-22598289a3be.png">

## Expected result:
Display should be updated without a page refresh

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes for 1.12.x rc
- Can you reproduce this issue with the beta channel? yes for 1.13.x
- Can you reproduce this issue with the nightly channel? yes for 1.14.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @rebron @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 1.12.105

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description
<img width="1029" alt="Screen Shot 2020-08-06 at 1 49 14 PM" src="https://user-images.githubusercontent.com/28145373/89564890-b1e3bc80-d7eb-11ea-91db-f207d407ee4c.png">

* Generally confirmed I was able to turn on Rewards from brave://rewards, panel, NTP widget
* Generally confirmed after turning off Rewards via brave://rewards page, I could re-enable via brave://rewards, panel, NTP
* Generally confirmed after reset of Rewards I could re-join via brave://rewards, panel, NTP widget

-------------
