### ISSUE TITLE
[Desktop] When rewards is reset ads service should shut down

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11035]
When rewards is reset we still have logs in `Rewards.log` from functions like `AdsImpl::OnTabUpdated`, `AdsImpl::OnIdle`, `AdsImpl::OnUnIdle`, `AdNotifications::SaveState`, etc.

**Comment by NejcZdovc** [comment]
same thing if ads is off I still see in logs `confirmations_impl.cc`

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6284.
* Confirmed if rewards are reset, then `Brave-Browser/Default/ads_service` folder is deleted.
* Confirmed if rewards are reset, then `Brave-Browser/Default/rewards_service` folder is deleted.
* Confirmed re-enabling rewards creates these two folders again.
* Confirmed toggling Ads off did not remove `Brave-Browser/Default/ads_service` or `Brave-Browser/Default/rewards_service` folders.
* Confirmed no ads messages seen in logs when Ads were toggled off.
* Confirmed if Ads are toggled off and then the browser is restarted, ads are still off after restart.
* Confirmed Ads can be toggled on and ads messages start appearing in the logs. 
* Confirmed when Ads were toggled back on the ads panel information was not lost.
* Confirmed when re-enabling Ads that ads were shown based on max per hour setting.

--------

**Comment by jsecretan** [comment]
Removing Android for now because unfortunately there is limited ability to test this on Android right now, and most important is the general list of ads regressions that should ensure this didn't break anything.
