### ISSUE TITLE
[Desktop] re-enabling Rewards from panel doesn't work

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11038]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/9526

If you try to re-enable rewards from the panel it looks like it worked (panel displays correctly), but if you go to brave://rewards page you can see that Rewards are still toggled off. Additionally, BAT Ads Service and BAT Ledger Service are not running in task manager.

This does not reproduce on 1.11.104 current release version. 

## Steps to Reproduce

   1. Clean profile 1.12.x, open Task Manager. See that BAT Ads and Ledger services are not running.
   2. Enable Rewards (I did this from panel). See BAT Ads and Ledger Services are now running.
   3. Open a new tab, navigate to brave://rewards.
   4. Toggle Rewards off. See BAT Ads and Ledger Services are no longer running.
   5. Close brave://rewards page.
   6. Open panel, get Welcome Back message, click on Enable Brave Rewards button.

## Actual result:

Panel looks like it worked, however if you go to brave://rewards page you will see that Rewards are toggled off. Additionally, BAT Ads and Ledger services do not start.

I also saw the below in my logs:
```
[1270:775:0731/093548.184989:VERBOSE1:rewards_service_impl.cc(435)] Starting ledger process
[1270:775:0731/093548.296659:INFO:database_balance_report.cc(313)] Response is wrong
[1270:775:0731/093548.296735:ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_UNEXPECTED_NULL_POINTER (null field 2)
[0731/093548.301015:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffeebcc4000, 0x2000): (os/kern) invalid address (1)
[1270:37379:0731/093548.396972:ERROR:browser_child_process_host_impl.cc(726)] Terminating child process for bad message: Received bad user message: Validation failed for bat_ledger.mojom.BatLedger response [VALIDATION_ERROR_UNEXPECTED_NULL_POINTER (null field 2)]
[1270:775:0731/093548.397045:VERBOSE1:rewards_service_impl.cc(395)] Rewards not enabled
```

## Expected result:
Rewards should be enabled fully.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no for 1.11.x, yes for 1.12.x rc
- Can you reproduce this issue with the beta channel? yes for 1.13.x
- Can you reproduce this issue with the nightly channel? yes for 1.14.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @NejcZdovc @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows 10 x64 - `1.12.105`

**Comment by LaurenWags** [comment]
After discussing with @NejcZdovc here's a related scenario that should also be checked once this issue is fixed:

- Enable Rewards
- Toggle ads off and back on
- Toggle rewards off and back on (wait for all "normal" log messages to be done, pub list, etc)
- Reset Rewards
--> panel is not showing correctly. After fix confirm panel displays as expected.

```
Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6321
* Verified STR from https://github.com/brave/brave-browser/issues/11038#issue-669831729
* Verified STR from https://github.com/brave/brave-browser/issues/11038#issuecomment-667159373
* Verified STR from https://github.com/brave/brave-browser/issues/11038#issuecomment-667312347
* Generally confirmed I was able to turn on Rewards from brave://rewards, panel, NTP widget
* Generally confirmed after turning off Rewards via brave://rewards page, I could re-enable via brave://rewards, panel, NTP
* Generally confirmed after reset of Rewards I could re-join via brave://rewards, panel, NTP widget

----------
