### ISSUE TITLE
Sometimes clicking ad notifications doesn't do anything (click not being registered)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11042]
## Description 

Sometimes ad notifications that are being displayed can't be clicked. However, `Close` works. Current working theory is that this occurs when an ad that doesn't belong to your region is being used/displayed. @iefremov ran into the same issue several times as well. Some examples:

@iefremov received the following ad and wasn't able to click/interact with it other than closing the notification:

![image](https://user-images.githubusercontent.com/2602313/89079595-d3105d00-d354-11ea-9cf8-bc4499414353.png)

Here are several examples that I ran into:

```
[42103:775:0731/111713.367275:VERBOSE1:ads_impl.cc(1277)] Ad notification shown:
  uuid: 43526b47-8ac5-4df2-8b92-32bb8e30b450
  parentUuid: 450dc0a2-e82d-4ff0-8096-e4ae0252ef33
  creativeInstanceId: d8135d18-d749-4437-a805-858384c4aa4c
  creativeSetId: ed2bdcc1-800f-41c0-980d-3c5897c9b25e
  category: untargeted
  title: Crocs
  body: FREE SHIPPING on orders over €75.
  targetUrl: https://crocseu.j4df.net/c/2051959/846578/8080
```

```
[42891:775:0731/113653.239438:VERBOSE1:ads_impl.cc(1277)] Ad notification shown:
  uuid: 297ff627-0fb8-4d9c-a4d8-85269f34a114
  parentUuid: e1a2a56c-9479-4c7b-b246-4949c985def1
  creativeInstanceId: dfffd965-bba8-48f5-95c3-ab6c2af00944
  creativeSetId: ffa47a4a-5fb1-4ef0-a934-e807faf814ed
  category: untargeted
  title: Amazon Ventes
  body: Les meilleures ventes en Sports et Loisirs
  targetUrl: https://amzn.to/35LbQ8V
```

```
[43894:775:0731/181031.046285:VERBOSE1:ads_impl.cc(1277)] Ad notification shown:
  uuid: feff1091-d64a-4324-8210-7c95017de75c
  parentUuid: ed5a56c5-753f-4479-ad83-58317a577c0e
  creativeInstanceId: 64d32ecb-35a7-4b44-b300-e9dfb69c0081
  creativeSetId: 9e298d67-9edb-4add-be1b-04e38089ef2e
  category: untargeted
  title: NordVPN
  body: La VPN più veloce del mondo. Ora al 70% di sconto.
  targetUrl: https://go.nordvpn.net/aff_c?offer_id=15&aff_id=37472
```

When clicking any of the above notifications, you'll see the following in the terminal/CLI:

```
[42103:775:0731/111716.586171:WARNING:notification_display_service_impl.cc(350)] Profile not loaded correctly
[42103:775:0731/111716.586220:ERROR:profile_manager.cc(544)] Loading a profile path that does not exist
[42103:775:0731/111717.476828:WARNING:notification_display_service_impl.cc(350)] Profile not loaded correctly
[42103:775:0731/111717.476870:ERROR:profile_manager.cc(544)] Loading a profile path that does not exist
[42103:775:0731/111718.038641:WARNING:notification_display_service_impl.cc(350)] Profile not loaded correctly
[42103:775:0731/111718.038704:ERROR:profile_manager.cc(544)] Loading a profile path that does not exist
[42103:775:0731/111718.228556:WARNING:notification_display_service_impl.cc(350)] Profile not loaded correctly
[42103:775:0731/111718.228604:ERROR:profile_manager.cc(544)] Loading a profile path that does not exist
[42103:775:0731/111718.408831:WARNING:notification_display_service_impl.cc(350)] Profile not loaded correctly
[42103:775:0731/111718.408868:ERROR:profile_manager.cc(544)] Loading a profile path that does not exist
```

## Steps to Reproduce

   1. launch `1.14.6 CR: 84.0.4147.105` and enable rewards via `brave://rewards` or the rewards panel
   2. once enabled, switch ads to `5 every hour`
   3. open a Tor window and load brave.com (go idle so ad launches)

Keep running through above and you'll eventually run into the issue where you'll get an ad from a different region. You can remove `Default/ads_service\client.json` to make testing easier.

## Actual result:

Sometimes clicking on ad notifications doesn't do anything. Examples mentioned above.

## Expected result:

Clicking on an ad notification should correctly open a tab and load the ad/page.

## Reproduces how often: 

It's pretty consistent but you might need to view ~10-20ads before getting one that doesn't belong in your region.

## Brave version (brave://version info)

```
Brave | 1.14.6 Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.15.6 (Build 19G73)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes` (reported by community)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `Yes` (ads will stop being displayed)
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @tmancey @brave/legacy_qa @rebron @jsecretan @jonathansampson

**Comment by kjozwiak** [comment]
BTW, another way of reproducing the issue is having two profiles. You'll sometimes get two ad notifications at the same time. Once will work and the other won't. I'm not sure if these are related but @tmancey mentioned there's already an issue filed for two ad notifications due to multiple profiles. Example:

<img width="394" alt="Screen Shot 2020-07-31 at 11 37 03 AM" src="https://user-images.githubusercontent.com/2602313/89080418-c987f480-d356-11ea-9f6c-43738f14ae91.png">

@iefremov please add anymore information if I've missed something.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
```
- Verified the STR from the description
- Viewed more than 10 Ads in TOR window and ensured click on Ads are redirecting to ads landing page and able to open/view all the Ads
![image](https://user-images.githubusercontent.com/38657976/92569434-408da280-f29e-11ea-8cc4-5188c1ccb37f.png)
![image](https://user-images.githubusercontent.com/38657976/92569477-50a58200-f29e-11ea-80a4-b42a106fee7f.png)

**Comment by tmancey** [comment]
@GeetaSarvadnya This is also caused by https://github.com/brave/brave-core/pull/6418 so will not be fully fixed until 6418 is merged

**Comment by GeetaSarvadnya** [comment]
QA Blocked until PR https://github.com/brave/brave-core/pull/6418 is uplifted

**Comment by GeetaSarvadnya** [comment]
Verification passed on **Windows 10 x64** using

```

Brave | 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```

**Clean profile**
- Verified the STR mentioned in the description and ensured that Ads are not received from other regions
- Viewed 5 Ads and ensured that all the Ads triggered are region-specific ads (region INDIA specific)
- Ensured that able Click/View Ads and click on ads redirecting to ads landing page
- Ensured Ads shown logs are captured correctly and estimated pending rewards and ads notification received count is shown correctly in the Ads panel
- https://github.com/brave/brave-browser/issues/11042#issuecomment-667402889 Verified it several times on multiple profiles and ensured that one AD notification is shown when rewards is enabled in multiple profiles, click on AD is redirecting to the ads landing page.

![image](https://user-images.githubusercontent.com/38657976/92726826-d81cef00-f38b-11ea-806a-c7eb4ec515dd.png)

```
[13476:1164:0910/163834.095:VERBOSE1:ads_impl.cc(1288)] Ad notification shown:
  uuid: ea5af26c-08d8-486d-9640-fad82bc0db8d
  parentUuid: 27fbc654-1595-49cd-b60e-c120fef81e21
  creativeInstanceId: 31bba57c-7c17-4bad-9ede-68346b9602c4
  creativeSetId: 32439113-32d2-4b50-9497-405b7eedd1d5
  category: untargeted
  title: Hotel Deals Club
  body: Winter is coming, ready to get away? Global hotels up to 80% off. 
  targetUrl: https://travala.com/
```
![image](https://user-images.githubusercontent.com/38657976/92727006-1d412100-f38c-11ea-8dba-ed139f90b5cd.png)


**Upgraded profile** (clean profile `1.13.82` enable rewards and set 5 ads per hour and upgraded profile to `1.13.86`, opened TOR windows and viewed Ads)

- Verified the STR mentioned in the description and ensured that Ads are not received from other regions
- Viewed Ads and ensured that all the Ads triggered are region-specific ads (region INDIA specific)
- Ensured that able Click/View Ads and click on ads redirecting to ads landing page
- Ensured Ads shown logs are captured correctly and estimated pending rewards and ads notification received count is shown correctly in the Ads panel
