### ISSUE TITLE
Sell panel should include to the total amount to be received in USD (Gemini)

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#11046]
Currently, the total label in the sell screen just shows the total amount of crypto to be sold. It should display the total amount of USD to be received, which is calculated by working out `(quantity * price) - fee`.

![Screen Shot 2020-07-31 at 6 07 53 PM](https://user-images.githubusercontent.com/8732757/89090637-0ead2600-d359-11ea-9179-c1ba30118e0e.png)
![Screen Shot 2020-07-31 at 5 47 53 PM](https://user-images.githubusercontent.com/8732757/89090639-0fde5300-d359-11ea-91f3-6db11109c7fd.png)

In addition, the label on the Buy screen should read as `Total Spent`, and on Sell, `Total Received`

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.14.61 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)

- Verified total conversion value is shown in the trade window for both sell and buy

Sell | Buy
-- | --
![image](https://user-images.githubusercontent.com/17010094/91127575-70358b80-e69e-11ea-894d-030cbb4a5dad.png) | ![image](https://user-images.githubusercontent.com/17010094/91147262-f0b0b800-e6af-11ea-82a6-70f0d32d98fb.png)

------------

Verification passed on 

Brave | 1.14.61 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux

- Verified total conversion value is shown in the trade window for both sell and buy

Sell | Buy
-- | --
![image](https://user-images.githubusercontent.com/17010094/91127019-43cd3f80-e69d-11ea-929d-6d619f69ae4d.png) | ![image](https://user-images.githubusercontent.com/17010094/91147006-944d9880-e6af-11ea-9018-a545eff2bcc2.png)

------------

Verification passed on 

Brave | 1.14.61 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | macOS Version 10.15.5 (Build 19F101)

- Verified total conversion value is shown in the trade window for both sell and buy

Sell | Buy
-- | --
![image](https://user-images.githubusercontent.com/17010094/91127603-83485b80-e69e-11ea-88c9-c6ffef11014b.png) | ![image](https://user-images.githubusercontent.com/17010094/91147199-d8409d80-e6af-11ea-9da4-1a4053cb1636.png)

**Comment by LaurenWags** [comment]
https://github.com/brave/brave-browser/issues/10978#issuecomment-681073203
