### ISSUE TITLE
[Desktop] Brave Ads intermittently crashes for thumbs up, thumbs down, opt-in, out-out, save ad and flag ad

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#11044]
[ 00 ] bat_ads::mojom::BatAdsProxy::ToggleAdOptInAction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, base::OnceCallback<void 
[ 01 ] brave_ads::AdsServiceImpl::ToggleAdOptInAction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, base::OnceCallback<void 
[ 02 ] (anonymous namespace)::RewardsDOMHandler::ToggleAdOptInAction
[ 03 ] content::WebUIImpl::OnWebUISend
[ 04 ] content::WebUIImpl::OnMessageReceived
[ 05 ] content::WebContentsImpl::OnMessageReceived
[ 06 ] content::RenderFrameHostImpl::OnMessageReceived
[ 07 ] content::RenderProcessHostImpl::OnMessageReceived
[ 08 ] IPC::ChannelProxy::Context::OnDispatchMessage
[ 09 ] base::TaskAnnotator::RunTask
[ 10 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork
[ 11 ] base::(anonymous namespace)::WorkSourceDispatch(_GSource*, int (*)
[ 12 ] pkey_x25519_derive$2e8add2861916223d98704c5544dee07
[ 13 ] base::MessagePumpGlib::Run
[ 14 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run
[ 15 ] base::RunLoop::Run
[ 16 ] performance_monitor::ProcessMonitor::StartGatherCycle
[ 17 ] ChromeBrowserMainParts::MainMessageLoopRun
[ 18 ] content::BrowserMainLoop::RunMainMessageLoopParts
[ 19 ] content::BrowserMainRunnerImpl::Initialize
[ 20 ] content::BrowserMainRunnerImpl::Run
[ 21 ] content::BrowserMain
[ 22 ] content::ContentMainRunnerImpl::Run
[ 23 ] content::ContentMainRunnerImpl::Initialize
[ 24 ] std::__1::__tree_const_iterator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*>*, long> std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::less<void>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::find<base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >
[ 25 ] base::CommandLine::GetSwitchValueASCII
[ 26 ] content::ContentServiceManagerMainDelegate::IsEmbedderSubprocess
[ 27 ] service_manager::Main
[ 28 ] base::ScopedBlockingCall::~ScopedBlockingCall
[ 29 ] base::ThreadLocalStorage::Slot::Set
[ 30 ] base::internal::UncheckedScopedBlockingCall::~UncheckedScopedBlockingCall
[ 31 ] tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int, void* (*)
[ 32 ] pred8x16_mad_cow_dc_l0t_8$b1cf078a599d456bd26ecf9212b8109a
[ 33 ] content::ContentMain
[ 34 ] ChromeMain

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.14.74 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6305
 - Generally browsed such that there were several ads available in my 7-day Ads History window. 
 - Then I would click one of the following: thumbs up, thumbs down, like, or dislike buttons in the 7 day ads history and close the browser as fast as I could. 
 - Did this a bunch of times for the various ads displayed.
 - Relaunch and check brave://crashes to confirm no crash reports listed. Also, no crashes observed while closing the browser. 

<img width="972" alt="Screen Shot 2020-09-03 at 10 36 44 AM" src="https://user-images.githubusercontent.com/28145373/92129693-da061180-edd1-11ea-98b7-ae559e016299.png">
<img width="1149" alt="Screen Shot 2020-09-03 at 10 38 34 AM" src="https://user-images.githubusercontent.com/28145373/92129697-db373e80-edd1-11ea-8392-6af21dea6bcb.png">
