### ISSUE TITLE
[Android] New Brave Stats flyout should not track incognito usage

### ISSUE THREAD

**Issue by intrnl** [brave/brave-browser#11048]
## Description 

The new Brave Stats flyout on Android that is accessible by tapping the top right edge of the new tab page also keeps track of websites visited and trackers blocked during incognito mode.

## Steps to reproduce 

   1. Open a new incognito tab
   2. Visit a random website

## Actual result 

Brave Stats flyout shows websites and trackers that are encountered during incognito mode.

## Expected result

Brave Stats shouldn't show websites and trackers that are encountered during incognito mode, rather, placing them in one single item in the list, it could be "Other pages"

## Issue reproduces how often 

Easily reproduced

## Issue happens on 
   - Current Play Store version? 1.14.7
   - Beta build? Nightly

## Device details
   - Install type (ARM, x86): arm64
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
Nightly 1.14.7

**Comment by srirambv** [comment]
cc: @jamesmudgett @anthonypkeane

**Comment by diracdeltas** [comment]
if i understand correctly, this is showing URLs visited in incognito mode outside of an incognito window. if so, this is a p2 privacy/security bug. 

incognito history should never be logged to disk or be accessible outside of an incognito window. the user expectation is that it is permanently purged as soon as the incognito window is closed. 

@anthonypkeane @deeppandya

**Comment by deeppandya** [comment]
This issue is fixed in latest update on privacy reports. Please try new nightly to verify it.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.84 x64 build
- Verified sites visited in private tabs are not tracked in privacy reports
- Verified no site details or trackers blocked details is listed
-------------
Verification passed on Samsung Tab A with Android 10 running 1.13.84 x64 build
- Verified sites visited in private tabs are not tracked in privacy reports
- Verified no site details or trackers blocked details is listed
