### ISSUE TITLE
Update Gemini widget Oauth flow to use PKCE

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#11043]
Gemini now supports PKCE, so we we should use a code challenge and verifier as part of the authentication process.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux

- Verified test plan from issue description
- Verified Gemini flow as per https://github.com/brave/brave-browser/issues/10978#issuecomment-680003834
- Verified Binance widget works as expected
- Verified able to connect to the widget without any issues
- Verified Summary, Deposit, Convert and Buy tabs are displayed after connecting the widget and summary is in hide mode
- Verified disconnecting/reconnecting via the widget worked as expected and displayed the correct balance
- Verified that deposit addresses are being displayed correctly under the Deposit tab
- Verified QR code images under the Deposit tab correctly enlarges/displays the QR codes
- Verified tokens such as XRP display both a deposit address and memo address
- Verified selecting Learn More under the menu opens `https://brave.com/binance`
- Verified  selecting tokens via the Buy tab correctly updates the Buy [Token] button
- Verified clicking on the Buy button under the Buy tab correctly opens a new tab with the correct amounts already filled out
--------------------------------
Verification passed on 

Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)

- Verified test plan from issue description
- Verified Gemini flow as per https://github.com/brave/brave-browser/issues/10978#issuecomment-680003834
- Verified Binance widget works as expected
- Verified able to connect to the widget without any issues
- Verified Summary, Deposit, Convert and Buy tabs are displayed after connecting the widget and summary is in hide mode
- Verified disconnecting/reconnecting via the widget worked as expected and displayed the correct balance
- Verified that deposit addresses are being displayed correctly under the Deposit tab
- Verified QR code images under the Deposit tab correctly enlarges/displays the QR codes
- Verified tokens such as XRP display both a deposit address and memo address
- Verified selecting Learn More under the menu opens `https://brave.com/binance`
- Verified  selecting tokens via the Buy tab correctly updates the Buy [Token] button
- Verified clicking on the Buy button under the Buy tab correctly opens a new tab with the correct amounts already filled out
--------------------------------
Verification passed on 

Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | macOS Version 10.15.5 (Build 19F101)

- Verified test plan from issue description
- Verified Gemini flow as per https://github.com/brave/brave-browser/issues/10978#issuecomment-680003834
- Verified Binance widget works as expected
- Verified able to connect to the widget without any issues
- Verified Summary, Deposit, Convert and Buy tabs are displayed after connecting the widget and summary is in hide mode
- Verified disconnecting/reconnecting via the widget worked as expected and displayed the correct balance
- Verified that deposit addresses are being displayed correctly under the Deposit tab
- Verified QR code images under the Deposit tab correctly enlarges/displays the QR codes
- Verified tokens such as XRP display both a deposit address and memo address
- Verified selecting Learn More under the menu opens `https://brave.com/binance`
- Verified  selecting tokens via the Buy tab correctly updates the Buy [Token] button
- Verified clicking on the Buy button under the Buy tab correctly opens a new tab with the correct amounts already filled out
