### ISSUE TITLE
[Desktop] Chrome Webstore entries give error

### ISSUE THREAD

**Issue by autonome** [brave/brave-browser#11056]
## Description 

Error trying to view details of Chrome webstore entries

## Steps to Reproduce

   1. open https://chrome.google.com/webstore/search/ipfs%20companion
   2. click on either entry

## Actual result:

<img width="932" alt="Screen Shot 2020-08-02 at 9 05 23 PM" src="https://user-images.githubusercontent.com/50103/89142300-3ee4f800-d504-11ea-849a-95fa13cdb97d.png">

## Expected result:

Details load.

## Brave version (brave://version info)

Brave | 1.13.45 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G5033)
JavaScript | V8 8.4.371.19
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Command Line | /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=PasswordImport,ReducedReferrerGranularity,MixedContentSiteSetting,WebUIDarkMode,PrefetchPrivacyChanges,AutoupgradeMixedContent,PassiveMixedContentWarning,OmniboxContextMenuShowFullUrls,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,SmsReceiver,TabHoverCards,VideoPlaybackQuality,UseButtonTranslateBubbleUI --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox
Executable Path | /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly
Profile Path | /Users/dietrich/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
It looks like google is having issues. We could replicate same issues, some VPN locations work better than others. @autonome 

https://downdetector.com/status/chrome-web-store/

**Comment by bsclifton** [comment]
This seems to be working for me - likely problem on Google side which is resolved by the time I came here

@autonome can you please try again?

**Comment by autonome** [comment]
WFM, yep must have been a Google issue, thanks everyone!
