### ISSUE TITLE
[Desktop] Strict fingerprinting protection makes enumerateDevices() incompatible with browser extensions

### ISSUE THREAD

**Issue by CoolCmd** [brave/brave-browser#11054]
Brave 84 x64, Windows 10

Strict fingerprinting protection is turned on. JavaScript on browser extension's page (`chrome-extension://blablabla/options.html`) calls `MediaDevices.enumerateDevices()`. In this situation the following incompatibilities are exist:

1. The promise returns `undefined` instead of array (as required by the specification).
2. The promise returns `undefined` even if the extension have permission to access audio devices (by previous call `chrome.contentSettings.microphone.set({setting:'allow'})`.
3. The user cannot change the fingerprinting mode for the extension because the Brave shield is inaccessible on the extension pages.

Chrome since version 81 have fingerprinting protection for `enumerateDevices()`, which does not have above issues. I recommend Brave developers to throw away their protection and leave the Chrome protection unchanged.

**Comment by pes10k** [comment]
@CoolCmd can you see if this is still the case in nightly?  I think this should be fixed

**Comment by pes10k** [comment]
@CoolCmd just wanted to check again with you on this.  Are you still seeing this issue on your machine?  Again i think this should be solved with the new fingerprinting protections we have.  If you're not seeing, or dont' report that you're still seeing breakage, i'll close this out.  Thanks!

**Comment by CoolCmd** [comment]
@pes10k, Brave 1.15 is OK. You can close this issue.

**Comment by pes10k** [comment]
Thanks @CoolCmd !
