### ISSUE TITLE
Implement client ads pacing mechanism

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#11057]
## Description 

Implement client-side support for pass-through rate ads pacing. Rationale and calculations described in detail: https://docs.google.com/document/d/1FFuiOg7eZePJaMMhp3h_hGnRtLPoGx2hqpqcL6pZZpw/edit#

## Steps to Reproduce

Ads, especially with broad targeting criteria, currently get shown at the highest rate close to midnight when daily budgets reset. Better pacing throughout the day should yield better results for both advertisers and users.

## Actual result:

Ads often spending bulk of the daily budget within ~15-17 hours

## Expected result:

Ads should spend their daily budget in closer to the full 24 hours, while still spending the full daily budget. More budget (and impressions) should be allocated to times of day when there are more active users.

## Reproduces how often: 

Easily calculated from data

## Brave version (brave://version info)

All versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
The pacing does not work at all. Logged https://github.com/brave/brave-browser/issues/11643.
