### ISSUE TITLE
[Desktop] Wallet creation failed

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#11053]
## Description 

Installed Fresh copy of Brave (Without any previous Install or Uninstall on that system)
And tried to enable Brave Rewards but received 
**"Wallet creation failed. Please check your internet connection."**
error. And my internet connection is good.

## Steps to Reproduce

   1. Download brave BraveBrowserSetup.exe from https://brave.com/
   2.  Install Brave.
   3.  Activate Brave Rewards from initial browser tour. (failed)
   4.  Then go to settings-> Brave Rewards -> Yes i'm in! . And received below result.

## Actual result:

 Wallet creation failed
 Please check your internet connection.

## Expected result:
 should enable Brave rewards

  
## Brave version (brave://version info)

Brave	1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)
Revision	a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS	Windows 10 OS Version 2004 (Build 19041.388)
JavaScript	V8 8.4.371.22
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,VideoPlaybackQuality,UseButtonTranslateBubbleUI,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,TabHoverCards --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-sync
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\MANIKANDAN\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Tried after system restart but same error.

## Miscellaneous Information:

No

**Comment by NejcZdovc** [comment]
we had some server problems, could you please check again and let me know if not it works. Thank you

**Comment by manikandancode** [comment]
Now Works.
