### ISSUE TITLE
[Desktop] Cannot use extensions that aren't in chrome store

### ISSUE THREAD

**Issue by ZyxerZyxani** [brave/brave-browser#11051]
## Description 

Cannot use Dissenter extension. 
Even when in developer mode I cannot enable it. Please, why do you disable all extensions that cannot be found in the chrome store? WHY!?

Can I bypass it?
How can I bypass it? I have the CRX file locally. Stop this stupid censorship. Even if it is disabled by default, at least allow us to add any extension we want. If I develop my own extension I cannot try it on brave before uploading it.

**Comment by rebron** [comment]
Closing as wontfix. Doesn't look like that extension is even available anymore `https://dissenter.com/download#download-extension` and the Dissenter team wants you to download their browser. 

If you'd like to sideload extensions please use Brave Dev or Brave Nightly.
