### ISSUE TITLE
Update Installer Graphics

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#1105]
## Description 
Browser laptop had custom iconography for the mounted installer icon (at least on Mac) as well as the screen that results from needing to drag it manually to the Applications folder. We are currently serving stock instances of both. A stock installer icon and a stock Application window on OSX. 

On Windows, as far as I can tell, a mounted icon doesn't appear and there is no prompt for a subsequent window like the process in OSX. I don't believe any further refinement is needed in the Windows install flow that isn't outlined in: https://github.com/brave/brave-browser/issues/1101

## Steps to Reproduce

1. Download any channel of Brave on OSX.
2. Mount the dmg.
3. View the stock installer icon.
4. Click the installer icon and find the stock window iconography next to each other. 

## Actual result:
![image](https://user-images.githubusercontent.com/29072694/45448946-ac75aa00-b688-11e8-90b5-121ec05d312f.png)

#### Installer icons tied to the release channel.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/29072694/59218532-5715ed00-8b75-11e9-8622-8b8b8cd15173.png">

#### Custom Mounted Finder Window
<img width="720" alt="image" src="https://user-images.githubusercontent.com/29072694/59218611-7d3b8d00-8b75-11e9-9d12-86306719cce8.png">

**Comment by rossmoody** [comment]
Here are all the .icns installer icon files needed to fulfill this request. There is also a background image file that includes that arrow for the finder window. 
[installers.zip](https://github.com/brave/brave-browser/files/2377104/installers.zip)

**Comment by rebron** [comment]
cc: @bradleyrichter

**Comment by bradleyrichter** [comment]
Muon seems to have a more "pleasant surprise of customization" effect...

![image](https://user-images.githubusercontent.com/13509546/56056762-efc4f380-5d11-11e9-9d85-d210c7cd8a41.png)

**Comment by rossmoody** [comment]
Updated background graphic: 
![download-window](https://user-images.githubusercontent.com/29072694/59218906-284c4680-8b76-11e9-9521-e5afd49c6d5f.png)

**Comment by simonhong** [comment]
@rossmoody I'm working on this now. Can you attach volume icon files here for 4 channels?

**Comment by LaurenWags** [comment]
Verified passed with Brave-Browser-Beta.dmg on `macOS x64 10.13.6`

Brave	0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
Revision	111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS	Mac OS X

<img width="784" alt="Screen Shot 2019-08-01 at 3 59 24 PM" src="https://user-images.githubusercontent.com/28145373/62324166-e1444880-b476-11e9-915d-13c6d7fec73b.png">


Verified passed with Brave-Browser-Dev.dmg on `macOS x64 10.13.6`

Brave	0.69.94 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
Revision	7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS	Mac OS X

<img width="812" alt="Screen Shot 2019-08-01 at 4 02 47 PM" src="https://user-images.githubusercontent.com/28145373/62324184-eb664700-b476-11e9-8297-9e06c451f7b1.png">


Verified passed with Brave-Browser-Nightly.dmg on `macOS x64 10.13.6`

Brave	0.70.22 Chromium: 76.0.3809.87 (Official Build) nightly (64-bit)
Revision	111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS	Mac OS X

<img width="747" alt="Screen Shot 2019-08-01 at 4 05 02 PM" src="https://user-images.githubusercontent.com/28145373/62324194-f1f4be80-b476-11e9-829c-f627087dc12e.png">

cc @kjozwiak  for a second macOS check on Mojave

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following builds:

Brave | 0.70.43 Chromium: 76.0.3809.87 (Official Build) nightly (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

<img width="165" alt="Screen Shot 2019-08-07 at 12 05 45 AM" src="https://user-images.githubusercontent.com/2602313/62594208-a5124d00-b8a7-11e9-9e62-d789176e0ef9.png">

<img width="622" alt="Screen Shot 2019-08-07 at 12 06 08 AM" src="https://user-images.githubusercontent.com/2602313/62594210-a774a700-b8a7-11e9-9c43-f14d22469396.png">

Brave | 0.69.100 Chromium: 76.0.3809.87 (Official Build) dev (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

<img width="185" alt="Screen Shot 2019-08-07 at 12 11 07 AM" src="https://user-images.githubusercontent.com/2602313/62594265-f15d8d00-b8a7-11e9-9b65-c029a9ecd095.png">

<img width="614" alt="Screen Shot 2019-08-07 at 12 11 12 AM" src="https://user-images.githubusercontent.com/2602313/62594259-e9055200-b8a7-11e9-8976-104f67baa774.png">

Brave | 0.68.115 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

<img width="121" alt="Screen Shot 2019-08-07 at 12 13 20 AM" src="https://user-images.githubusercontent.com/2602313/62594339-48fbf880-b8a8-11e9-80f3-8a7a86688ea7.png">

<img width="618" alt="Screen Shot 2019-08-07 at 12 13 03 AM" src="https://user-images.githubusercontent.com/2602313/62594344-50bb9d00-b8a8-11e9-81f4-bbb35dd3678e.png">
