### ISSUE TITLE
Change canvas maximum farbling to match balanced farbling

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#11067]
As per internal discussion, to address user feedback, we have decided to change the behavior of `canvas` at maximum farbling to be the same as the balanced farbling behavior.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6324 

* Reproduced issue on `1.11.104`
![1 11 x](https://user-images.githubusercontent.com/28145373/89657809-abad1900-d89b-11ea-866e-ae1f519d1815.png)

* Upgraded to `1.12.x`, confirmed no artifacts
![1 12 x](https://user-images.githubusercontent.com/28145373/89657826-b667ae00-d89b-11ea-9947-16bfc57b4eb0.png)

* Also verified test plan on a clean profile with 1.12.x, confirmed no artifacts.

------------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.109
- Verified no artefacts are shown on the player when FP is set to block all 
----------
Verification passed on Samsung Tab A with Android 10 running 1.12.109
- Verified no artefacts are shown on the player when FP is set to block all
