### ISSUE TITLE
[Desktop] There was a problem processing your contribution message on BAT logo

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11078]
## Description 

There was a problem processing your contribution message on BAT logo
## Steps to Reproduce

   1. Clean profile 1.11.x staging environment
   2. Launch brave using `brave.exe --enable-logging --vmodule="*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/bat-native-ledger/*"=6 --rewards=staging=true,reconcile-interval=3,short-retries=true`
   3. Enable rewards
   4. Connect KYC'd uphold staging account ( should have some balance (self funded or ad grants))
   5. Add connected pub DDG to AC table
   6. Wait for AC to trigger
   8. Click on BAT logo displays the error message as `There was a problem processing your contribution`
   9. Dismiss the notification.
  10. Click on BAT logo again shows the auto contribution successful message as expected

## Actual result:

There was a problem processing your request message on BAT logo
![image](https://user-images.githubusercontent.com/38657976/89313379-0d039b00-d696-11ea-818d-b77fcc8594bc.png)

## Expected result:

`There was a problem processing your contribution message` should not be shown on BAT logo
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes in 1.11.104 not in 1.11.92
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya can you please add logs

**Comment by GeetaSarvadnya** [comment]
Shared logs via DM for privacy reasons.

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya can you try this with out short retries flag?

**Comment by NejcZdovc** [comment]
could be related to this issue https://github.com/brave/brave-browser/issues/10238

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Sure

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Verified the issues without `short-retries` flag. The issue is not reproducible, looks like issue with `short-retries` flag.

**AC with KYC'd uphold wallet:**

![image](https://user-images.githubusercontent.com/38657976/89641900-59d2b600-d8d0-11ea-9464-e07dfdd4cbb1.png)

**AC with Ad grants**
![image](https://user-images.githubusercontent.com/38657976/89641922-66efa500-d8d0-11ea-925a-defc8184875d.png)

**Comment by NejcZdovc** [comment]
thank you, closing this one as will be resolved with https://github.com/brave/brave-browser/issues/10238
