### ISSUE TITLE
[Android] Onboarding missing for German locale

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11079]
## Description 
Onboarding missing for German locale

## Steps to reproduce 

   1. Set device locale to German
   2. Clean install 1.14.10 
   3. Click on URL bar no onboarding is shown

## Actual result 
Onboarding missing for German locale

## Expected result
Should show onboarding for German locale 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.14.10

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by deeppandya** [comment]
@srirambv @bsclifton i am closing this issue  based on the discussion we have here : https://bravesoftware.slack.com/archives/C016G4AMY4A/p1596585202223900?thread_ts=1596537272.220000&cid=C016G4AMY4A

**Comment by bsclifton** [comment]
Removing milestone and adding label so this doesn't get QA'ed
