### ISSUE TITLE
[Desktop] disabling Rewards for one profile when other profile(s) are running Rewards causes problem

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11074]
## Description 

Related to https://github.com/brave/brave-browser/issues/9526, https://github.com/brave/brave-browser/issues/9196

If you have multiple profiles running BR and you disable BR for one, the BAT Ledger Service gets disabled for all profiles. This leads to a weird state where other profile(s) think Rewards is still on but it's not really. Also, we shouldn't be disabling BR for other profiles just because it's turned off for one.

Does not reproduce on 1.11.x as in that version BAT Ledger and BAT Ads svcs were always running. In 1.12.x this changed.

## Steps to Reproduce

   1. Clean profile 1.12.x (this is Profile A)
   2. Open Browser Task Manager so you can confirm BAT Ledger and BAT Ads svcs are not running
   3. Create a second profile (this is Profile B)
   4. On Profile A, enable Rewards
   5. On Profile B, enable Rewards
   6. Let all related tasks complete (pub prefix list download, get ad tokens, etc) for both profiles
   7. Note that BAT Ledger and Ads svcs are running
   8. Open brave://rewards page for Profile B and toggle Rewards off
   9. Switch to Profile A window, navigate to brave://rewards page --> see welcome page
   10. Open Panel on this page --> panel looks like BR is running
   11. Look at task manager --> BAT Ledger Svc isn't running but BAT Ads Svc is

## Actual result:

<img width="1328" alt="Screen Shot 2020-08-04 at 9 22 31 AM" src="https://user-images.githubusercontent.com/28145373/89301225-6a1c3400-d637-11ea-8064-5857236a217c.png">

## Expected result:
BAT Ledger svc shouldn't be stopped because another profile is using it

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.11.x no, 1.12.x yes
- Can you reproduce this issue with the beta channel? 1.13.x yes
- Can you reproduce this issue with the nightly channel? 1.14.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @rebron @brave/legacy_qa

**Comment by LaurenWags** [comment]
Note, if you run the above scenario a bit differently it doesn't cause an issue:

   1. Clean profile 1.12.x (this is Profile A)
   2. Open Browser Task Manager so you can confirm BAT Ledger and BAT Ads svcs are not running
   3. Create a second profile (this is Profile B)
   4. On Profile A, enable Rewards
   5. On Profile B, enable Rewards
   6. Let all related tasks complete (pub prefix list download, get ad tokens, etc) for both profiles
   7. Note that BAT Ledger and Ads svcs are running
   8. Open brave://rewards page for Profile A and toggle Rewards off
   9. Switch to Profile B window, navigate to brave://rewards page --> see expected rewards settings/details page
   10. Open Panel on this page --> panel looks like BR is running
   11. Look at task manager --> BAT Ledger Svc is still running

**Comment by Miyayes** [comment]
Closing as stale for now. Can refile if we see it still being an issue.
