### ISSUE TITLE
[Android] Sending link from Android to Desktop doesn't work

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#11077]
## Description 

Issue from https://old.reddit.com/r/brave_browser/comments/i3johv/this_happens_every_time_i_try_to_send_a_link_to/

## Steps to reproduce 

   1. Enable sync on Android device
   2. Enable `Open tabs` sync category
   3. Establish sync chain between Android and Desktop
   4. Open some page on Android (note, internal links like about:version don't work)
   5. Press kebab menu => share icon => Send to your devices

## Actual result 
   4. Enable  sync  from Chromium popup message is displayed

## Expected result
   4. Prompted to choose the device and page should be sent, other device should receive the link through notification

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version? yes, Nightly 1.14.7
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 8
   
## Brave version
1.14.7

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by eljuno** [comment]
Just asking. Can we have this fix sooner? Users reporting the issue is happened on stable version 1.12.x too

**Comment by matfantinel** [comment]
Is this the same issue?

When I try to send a tab from Android to desktop, I get a banner that asks me to setup sync in my device.

![Screenshot_20200817-113522_Brave.jpg](https://user-images.githubusercontent.com/24247035/90408161-db1f0b00-e07d-11ea-832c-fb5c905bf6dd.jpg)

I have already setup sync and added both devices, as showed on the sync menu in Android:

![Screenshot_20200817-113530_Brave.jpg](https://user-images.githubusercontent.com/24247035/90408202-ea9e5400-e07d-11ea-8f5a-255628a45706.jpg)

Also worth nothing that the opposite way works - I can send tabs from desktop to Android without issues.

Using latest stable (1.12) on both Android and desktop(Linux)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
- Verified sending tab from a mobile device is received on the desktop
- Verified able to send both HTTPS/HTTP links
- Verified clicking on the notification opens a new tab with the target URL

HTTPS | HTTP
-- | --
![image](https://user-images.githubusercontent.com/17010094/91967685-774a4280-ed0b-11ea-98cc-53c1b9b42887.png) | ![image](https://user-images.githubusercontent.com/17010094/91968057-fdff1f80-ed0b-11ea-8a52-efb35db88bd2.png)

-----------
Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
- Verified sending tab from a mobile device is received on the desktop
- Verified able to send both HTTPS/HTTP links
- Verified clicking on the notification opens a new tab with the target URL

HTTPS | HTTP
-- | --
![image](https://user-images.githubusercontent.com/17010094/91968554-b6c55e80-ed0c-11ea-92d3-1bc462e4ecaf.png) | ![image](https://user-images.githubusercontent.com/17010094/91968738-0015ae00-ed0d-11ea-9ba0-c239602ebcc1.png)
