### ISSUE TITLE
[Android] Add support for #enable-force-dark

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#11085]
## Description 
See: https://bravesoftware.slack.com/archives/C0816QH3R/p1596571834338300

Enable support for #enable-force-dark

Add a setting in Settings > Display > Appearance 
As the top menu item add

Enable "Night Mode"

Exact label text TBD

**Comment by srirambv** [comment]
`Enable "Night Mode"`  should be `Enable "Night Mode" (Experimental)`

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.15.54 x64 beta build
- Verified new settings option `Enable "Night Mode"(Experimental)` is listed under Settings -> Appearance
- Verified enabling/disabling the settings prompts for a relaunch
- Veriifed selecting later in relaunch prompt doesn't cause the webview to either go dark or remain white until browser is restarted
- Verified enabling the settings enables the flag `chrome://flags#enable-force-dark`
- Verified enabling the settings causes webview to be dark mode 

Setting | Restart alert | Flag | Dark webview
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/93734686-22933c80-fbd2-11ea-8a93-6967551813c5.png) | ![image](https://user-images.githubusercontent.com/17010094/93734690-29ba4a80-fbd2-11ea-83a6-67872486901c.png) | ![image](https://user-images.githubusercontent.com/17010094/93734697-32ab1c00-fbd2-11ea-8adb-3ff15f57801d.png) | ![image](https://user-images.githubusercontent.com/17010094/93734706-4060a180-fbd2-11ea-88a8-244d4f8da5d6.png)

**Comment by Dev-i-l** [comment]
MAKE SURE DARK MODE IS ACCESSIBLE THROUGH 3-DOT MENU.
