### ISSUE TITLE
[Desktop] Greaselion browser tests crash in Debug build

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#11081]
6 tests crashed:
    GreaselionServiceTest.ClearCache (../../brave/browser/greaselion/greaselion_browsertest.cc:181)
    GreaselionServiceTest.ScriptInjection (../../brave/browser/greaselion/greaselion_browsertest.cc:195)
    GreaselionServiceTest.ScriptInjectionDocumentEnd (../../brave/browser/greaselion/greaselion_browsertest.cc:229)
    GreaselionServiceTest.ScriptInjectionDocumentStart (../../brave/browser/greaselion/greaselion_browsertest.cc:212)
    GreaselionServiceTest.ScriptInjectionRunAtDefault (../../brave/browser/greaselion/greaselion_browsertest.cc:246)
    GreaselionServiceTest.ScriptInjectionWithPrecondition (../../brave/browser/greaselion/greaselion_browsertest.cc:263)

**Comment by NejcZdovc** [comment]
I just run them on macOS and all is passing on the latest master

**Comment by mkarolin** [comment]
@NejcZdovc in Debug build?

**Comment by NejcZdovc** [comment]
I just did regular npm run build and then tests, default is Component right?

**Comment by mkarolin** [comment]
Correct, but I believe the DCHECK only happens in DEBUG specifically here https://source.chromium.org/chromium/chromium/src/+/master:base/path_service.cc;l=327?q=PathService::RegisterProvider&ss=chromium%2Fchromium%2Fsrc because it's under `#ifndef NDEBUG`
