### ISSUE TITLE
[Android] Yahoo is not listed for non-supported region

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11080]
## Description 
Yahoo is not listed for non-supported region

## Steps to reproduce 

   1. Set region to Poland
   2. Clean install 1.14.10
   3. No Yahoo SE is shown in onboarding or in settings

## Actual result 
Yahoo is not listed for non-supported region

## Expected result
Should match iOS and list Yahoo at the bottom of the list.

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.14.10

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @bsclifton @deeppandya

**Comment by bsclifton** [comment]
This shouldn't be showing for Poland - we'll adjust iOS to remove
