### ISSUE TITLE
[Android] Yahoo isn't the first SE on the list post upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11082]
## Description 
Yahoo isn't the first SE on the list post upgrade

## Steps to reproduce 

   1. Install older version of nightly say 1.13.10
   2. Select DDG Lite on onboarding
   3. Upgrade to 1.14.10
   4. Open search settings Yahoo is on the bottom of the list

## Actual result 
Standard | Private
-- | --
![image](https://user-images.githubusercontent.com/17010094/89319671-58a74c00-d678-11ea-8714-746c1a96228f.png) | ![image](https://user-images.githubusercontent.com/17010094/89319685-5c3ad300-d678-11ea-8b5f-ecb8d7a92f20.png)

## Expected result
Should be on top post upgrade

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version?NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.14.10 nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @bsclifton @deeppandya

**Comment by srirambv** [comment]
Moving it out of 1.12.x as it doesn't need to block the release. 

cc: @bsclifton @janypiotrowski

**Comment by deeppandya** [comment]
@bsclifton @srirambv i have a solution for this issue. on upgrade i am checking if yahoo is one of the SE, i just put yahoo on top of all the other SEs. Would that be okay ? just want your opinion.

**Comment by deeppandya** [comment]
@srirambv i think it should be fixed with latest version. can you verify ?

**Comment by deeppandya** [comment]
@srirambv @bsclifton i think this issue is irrelevant at this time. we can close it.
