### ISSUE TITLE
[Android] Add developer option to enable rewards vlog output 

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#11088]
Add developer option to enable rewards vlog output

**Comment by SergeyZhukovsky** [comment]
There is an option in Developers Settings right now to Enable vlog. Just turn it on and check for logs in a logcat window.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build
- Verified enabling vlog from QA settings allows capturing logs via logcat
------------
Verification passed on Samsung Tab A with Android 10 running 1.13.81 x64 build
- Verified enabling vlog from QA settings allows capturing logs via logcat
