### ISSUE TITLE
Add a `Show speedreader button` in settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#11098]
## Description 
In brave://settings/appearance, give users the ability to show and hide the speedreader icon. Default is to show the icon.
Setting label: `Show speedreader button` with placement underneath `Show home button` 

This should be attached to the speedreader/channel flag which is currently attaching speedreader to the beta channel. Speedreader icon should not show in release channel yet.

## Design/Expected result
Add toggle for Speedreader to Appearance section:

![image](https://user-images.githubusercontent.com/2388823/109575708-373ffe80-7aa7-11eb-82f5-24cae6e894bb.png)

## Reproduces how often: 

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? Feature should not show in release channel
- Can you reproduce this issue with the beta channel? Applies to beta channel
- Can you reproduce this issue with the nightly channel? Applies to nightly channel

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by karenkliu** [comment]
Designs added!

**Comment by keur** [comment]
Resolved in https://github.com/brave/brave-core/pull/9014
