### ISSUE TITLE
Brave Ads regional ad relevance drop list forces you to scroll the entire page - follow up to 9200

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11095]
## Description 

Found while testing #9200

If you open the state level drop down on ads settings, you need to scroll the entire page to see the list. It would be nice if you only had to scroll within the drop down.

## Steps to Reproduce

   1. Install version with state level ads (1.12.x or above) and have OS set to US
   2. Enable Rewards
   3. Open Ads Settings

## Actual result:

<img width="1197" alt="Screen Shot 2020-08-05 at 10 47 22 AM" src="https://user-images.githubusercontent.com/28145373/89427721-9607ea00-d709-11ea-9690-ae8aeb4daeda.png">

## Expected result:
Smaller drop down that was limited to x number of lines (10 maybe?) and scroll within that to pick my state instead of scrolling down the whole page.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.11.x n/a, 1.12.x yes
- Can you reproduce this issue with the beta channel? 1.13.x yes
- Can you reproduce this issue with the nightly channel? 1.14.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @tmancey @jsecretan @brave/legacy_qa @rebron

**Comment by btlechowski** [comment]
Reproduced on

Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/89798456-7ff49200-db2c-11ea-87dc-cb5f1d1daf4d.png)

**Comment by tmancey** [comment]
Ok great, and yes this is simple without any mockups as no design change as such.

**Comment by tmancey** [comment]
Discussed with @zenparsing and this is no longer an issue. Please test on latest builds. Thanks
