### ISSUE TITLE
[Desktop] Cannot build from within `brave-core` on Linux

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#11099]
On Linux, `npm run build` from within the `brave-core` directory produces the following errors:
```
ERROR Input to target not generated by a dependency.
The file:
  //out/Release/brave-core
is listed as an input or source for the target:
  //brave:brave_dist_resources
but no targets in the build generate that file.

ERROR Input to target not generated by a dependency.
The file:
  //out/Release/dist/brave
is listed as an input or source for the target:
  //brave/app/linux:strip_and_dump_symbols
but no targets in the build generate that file.
```

`npm run build` within the `brave-browser` directory works as expected.

**Comment by bsclifton** [comment]
I think this was fixed with https://github.com/brave/brave-browser/pull/10885 - can you confirm if closed @bridiver?

**Comment by bridiver** [comment]
https://github.com/brave/brave-browser/pull/10885 is what broke it. It still works fine running from brave-browser

**Comment by antonok-edm** [comment]
It's been nearly a year since this broke, and I've started getting issues where I'd no longer be able to build from `brave-browser` if I accidentally attempted to build  within `brave-core`. I have no idea what I'm dealing with here, but I isolated the issue to these problematic inputs:

- `$root_out_dir/$brave_exe` in [BUILD.gn](https://github.com/brave/brave-core/blob/master/BUILD.gn#L313)

- `brave_binary` in [app/linux/BUILD.gn](https://github.com/brave/brave-core/blob/master/app/linux/BUILD.gn#L57)

If I comment those two out in an existing repo, I'm able to build from within `brave-core` once again. I doubt it's the correct solution though, so help would be appreciated.
