### ISSUE TITLE
[Desktop] Sync v2 - Bookmarks are duplicated after migration from sync v1

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#11104]
All* the bookmarks are duplicated if user migrates from sync 1 to sync 2
The reason is that after upgrade to 1.12.x bookmarks are stripped of all the sync 1 meta data and are treated as local bookmarks. This is by design.

* there could be a chance that a bookmark will get the same *guid* and won't be duplicated.

The problem is that the user may not realize that the bookmarks are now local and that they will sync to all the devices thus creating duplicates.
Even bigger problem is that we immediately encourage the user to create a sync v2 chain after migration.
![image](https://user-images.githubusercontent.com/34715963/89480112-cf396c00-d794-11ea-9de6-0c547de856ba.png)

## Steps to Reproduce

1. Install 1.11.x
1. DeviceA: Bookmark few pages
1. Create sync v1 chain
1. Wait for sync
1. Install 1.12.x
1. Create sync v2 chain

Note: this issue can be easily replicated by just using sync 2

## Actual result:

We encourage user to create sync v2 chain after upgrade which could result in bookmarks being duplicated
![image](https://user-images.githubusercontent.com/34715963/89480112-cf396c00-d794-11ea-9de6-0c547de856ba.png)
Bookmarks are duplicated after sync v2 chain is created
![image](https://user-images.githubusercontent.com/34715963/89490456-3400c080-d7ad-11ea-8e82-40dbaeb23535.png)

We also don't backup their bookmarks after upgrade to 1.12.x.

## Expected result:
Bookmarks are not duplicated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

**Comment by darkdh** [comment]
The root cause is not even related to v1 and it can be reproducible with v2 only.
Close as invalid and use https://github.com/brave/brave-browser/issues/11116 instead
