### ISSUE TITLE
[Android] Clicking Brave icon doesn't do anything

### ISSUE THREAD

**Issue by FrostedIce339** [brave/brave-browser#11109]
## Description 

Clicking brave icon doesn't do anything

## Steps to reproduce 

   1. Install a PWA such as Twitter
   2. Click a link leading to a website
   3. Click on the Brave icon; doesn't bring up any pop-up menu.

## Actual result 
Click on the Brave icon doesn't bring up any pop-up menu

## Expected result

Click on the Brave icon should bring up pop-up menu

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

Tested on Brave browser Version 1.11.105

- Can you reproduce this issue with the current Play Store version?

Yes
 
- Can you reproduce this issue with the current Play Store Beta version? 

Haven't checked

- Can you reproduce this issue with the current Play Store Nightly version?

Haven't checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 10
   
## Brave version 

Brave browser version 1.11.105

**Comment by srirambv** [comment]
Closing in favour of #9113.
