### ISSUE TITLE
[Desktop] Next payment date is null for a few seconds

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11107]
## Description 

The next payment date is null for a few seconds. As soon as enabling rewards ads panel shows empty `Next payment date` for few seconds after that the `Next payment date` is getting reflected in Ads panel

## Steps to Reproduce

   1. Clean profile 1.14.121
   2. Enable rewards
   3. Next payment date is null in Ads panel for few seconds

## Actual result:

Next payment date is null for a few seconds
![image](https://user-images.githubusercontent.com/38657976/89506591-f91c7e00-d7e8-11ea-8b7d-21f5fca9b64c.png)

## Expected result:

Next payment date should reflect immediately
## Reproduces how often: 

80 % Reproducible rate

## Brave version (brave://version info)

Brave | 1.14.21 Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey 

@kjozwiak Confirmed it's working as expected in macOS

**Comment by tmancey** [comment]
@GeetaSarvadnya @LaurenWags This is due to the time it takes to start the ads service. As the value is populated after the ads service has started I would recommend not fixing

**Comment by GeetaSarvadnya** [comment]
Closing the issue as it is reproducible once in 5x attempts.
