### ISSUE TITLE
[Desktop] I get an error when I try to go to 4chan. Please help. 

### ISSUE THREAD

**Issue by PinkShark51** [brave/brave-browser#11101]

**Comment by Jon-C-McLean** [comment]
HI @PinkShark51,

Would you be able to provide some more information about the issue? What device is this for? What version are you on? When does the issue occur? What have you tried? 

Please use the issue format provided for your device.

**Comment by PinkShark51** [comment]
![image](https://user-images.githubusercontent.com/66445308/89551518-0a5d8e80-d7d9-11ea-9d0d-752ff65c1d9a.png)

**Comment by rebron** [comment]
Hi @PinkShark51 I can't reproduce on our latest version, I was able to get to 4chan pages just fine. It looks like you might have some intermittent connection issues. Can you also use the issue template in the future? 

Thanks @Jon-C-McLean for the help!
