### ISSUE TITLE
[Desktop] need to refresh brave://rewards page to see correct backup modal after restoring an anon user wallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11111]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/10021

After restoring an anon user wallet, I needed to refresh brave://rewards page to see the correct backup modal.

## Steps to Reproduce

   1. Install 1.12.x, enable rewards
   2. Restore an anon user wallet with BAT
   3. Wait for `OnFetch` call back in terminal
   4. Open Backup modal

## Actual result:

<img width="690" alt="Screen Shot 2020-08-06 at 9 54 12 AM" src="https://user-images.githubusercontent.com/28145373/89541009-cc0da280-d7cb-11ea-803b-32cfd69128f6.png">

## Expected result:
Since I restored a wallet with BAT, I should see the below (with words, I blanked those out). Page refresh fixes this.
<img width="706" alt="Screen Shot 2020-08-06 at 9 56 38 AM" src="https://user-images.githubusercontent.com/28145373/89541047-d6c83780-d7cb-11ea-9249-b03dac2af5ba.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a for 1.11.x, yes for 1.12.x
- Can you reproduce this issue with the beta channel? no for 1.13.x
- Can you reproduce this issue with the nightly channel? no for 1.14.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.12.108`
