### ISSUE TITLE
[Android] Browser crash when trying to enable staging server

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11114]
## Description 
Browser crash when trying to enable staging server

## Steps to reproduce 

   1. Clean install 1.12.108
   2. Enable QA preferences and turn on staging rewards
   3. Try again browser crashes

## Actual result 
Browser crashes when trying to enable staging rewards

## Expected result
Should not crash and enable staging rewards

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Maybe

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.12.108

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
@srirambv should this be closed now that we've landed both https://github.com/brave/brave-core/pull/6221 and https://github.com/brave/brave-core/pull/6267?

**Comment by srirambv** [comment]
No this is still happening on 1.12.111 build even though https://github.com/brave/brave-core/pull/6221 (1.12.x uplift https://github.com/brave/brave-core/pull/6354) and https://github.com/brave/brave-core/pull/6267 (1.12.x uplift https://github.com/brave/brave-core/pull/6356)have both been uplifted.

**Comment by kjozwiak** [comment]
> No this is still happening on 1.12.111 build even though [brave/brave-core#6221](https://github.com/brave/brave-core/pull/6221) (1.12.x uplift [brave/brave-core#6354](https://github.com/brave/brave-core/pull/6354)) and [brave/brave-core#6267](https://github.com/brave/brave-core/pull/6267) (1.12.x uplift [brave/brave-core#6356](https://github.com/brave/brave-core/pull/6356) both been uplifted.

Thanks for the double check 👍 Reproducing on my S10+ running `1.12.111 CR: 84.0.4147.111`. @emerick mind taking a look as this is blocking us from QAing rewards/ads on staging for `1.12.x`.

**Comment by srirambv** [comment]
This is fixed on 1.12.112 which has the hash commit ee9ae87c6510eb331f2d23b617ea7aa31ee815ef. 

Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build
- Verified browser doesn't crash when trying to switch to staging server
-----------
Verification passed on Samsung Tab A with Android 10 running 1.12.112 x64 build
- Verified browser doesn't crash when trying to switch to staging server
