### ISSUE TITLE
[Desktop] Sync v2 initial bookmarks duplication

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#11116]
## Description 

The first device has to wait one sync interval(60s) to send its local bookmarks. When second device tries to do first time merge, it gets nothing from server.

Note: Chrome can reproduce this within 10s

## Steps to Reproduce

1. bookmark `brave://sync-internals/` on device A
2. bookmark  `brave://sync-internals/` on device B
3. Create sync chain on device A
4. Device B join sync chain shortly (less than 60s)

## Actual result:

We will see both devices have same duplicate bookmarks

## Expected result:
No duplicate bookmarks

## Reproduces how often: 

Always

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:
 However, this steps below won't have bookmark duplicated
```
1. bookmark brave://sync-internals/ on device A
2. bookmark  brave://sync-internals/ on device B
3. Create sync chain on device A
4. device B join sync chain after 60s or add a bookmark within 60s
5. There is no duplicate bookmarks
```

**Comment by btlechowski** [comment]
Thanks @darkdh !

cc @brave/legacy_qa @rebron

**Comment by btlechowski** [comment]
`QA/Blocked` as it needs build higher than `1.12.111`

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` since https://github.com/brave/brave-browser/releases/tag/v1.12.112 is available

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Ubuntu 18.04 LTS

Note: I am still able to reproduce if I create the sync chain within few(2) seconds, but it is a big improvement.

Verified test plan from the description
![image](https://user-images.githubusercontent.com/34715963/90030315-32a72a80-dcbc-11ea-9f01-3dabbaaf028f.png)

Verified test plan from https://github.com/brave/brave-browser/issues/11104#issue-674018344
![image](https://user-images.githubusercontent.com/34715963/90029601-574ed280-dcbb-11ea-81b8-184ed94bee67.png)

**Comment by kjozwiak** [comment]
@btlechowski should we create a follow up issue which will address this so it doesn't happen anymore. We should be good for the `1.12.x` release as it's a major improvement but sounds like it's still occurring?
