### ISSUE TITLE
Some videos on breitbart do not play because of fingerprinting protection

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1111]
per DM, it does work in browser-laptop though.
3p fingerprinting protection doesn't work.
Allow fingerprinting protection does work.

**Comment by yrliou** [comment]
test link shared to @srirambv through DM.

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X
