### ISSUE TITLE
[Desktop] Cleanup leftovers from legacy Tor profile implementation

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#11127]
* Cleanup utilities related to `Guest` profile, such as `SwitchToGuestProfile()` in `profile_window.h`
 * Replace complex checks such as [1] across the code with `profile->IsOffTheRecord()`

[1]
```
return !brave::IsTorProfile(profile) &&
    !profile->IsIncognitoProfile() &&
    !profile->IsGuestSession();
```

**Comment by yrliou** [comment]
@iefremov 2 is covered by https://github.com/brave/brave-browser/issues/11218.
I checked the current master for `SwitchToGuestProfile`, it doesn't seem to have left-over codes, please let me know if I still missed something, otherwise, I think we could close this issue.
