### ISSUE TITLE
[Desktop] pending rewards not moved into wallet

### ISSUE THREAD

**Issue by rodmirsantana** [brave/brave-browser#11129]
## Description 
I have pending rewards that should have been added to my wallet, but its balance is still 0, as can be seen in the screenshot below.

## Steps to Reproduce

   1. Open "Rewards page": (brave://rewards/);
   2. Check wallet balance and compare with "Estimated pending rewards" as shown on the left under the "Ads" card.

## Actual result:
[![Image from Gyazo](https://i.gyazo.com/5cbcaf1a42db3ef3627e15a7e9d09508.png)](https://gyazo.com/5cbcaf1a42db3ef3627e15a7e9d09508)

## Expected result:

Balance on wallet should be the same as on "Estimaded pending rewards", since the payout date is already due (08/07/2020) at the time of writing this issue.

## Brave version (brave://version info)
Brave | 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.15.6 (Build 19G73)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
@rodmirsantana These rewards may not have cleared and are still pending. Can you please let me know if they are not paid in September.

**Comment by rodmirsantana** [comment]
@tmancey I believe they now moved from pendint to my wallet. Please let me know if this is correct:

![Screen Shot 2020-08-20 at 07 56 58](https://user-images.githubusercontent.com/30738853/90762134-e27f2800-e2ba-11ea-95b5-442d27ec9e62.png)

**Comment by tmancey** [comment]
@rodmirsantana Looks good to me, if you experiencing any other issues please do reach out to support. Thank you
