### ISSUE TITLE
Reset Rewards crashes the browser in certain cases

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11125]
## Description 

If you reset Rewards while rewards is off or Ads is off the browser crashes. When you restart you are prompted to restore your session but the reset didn't happen so your Rewards data was not reset.

## Steps to Reproduce

Case 1:
   1. If Rewards enabled, toggle off.
   2. Click on gear icon.
   3. Choose Reset.
   1. Click Reset button.
   1. Click OK on popup.

Case 2:
   1. Leave Rewards enabled but disable Ads.
   2. Click on gear icon.
   3. Choose Reset.
   1. Click Reset button.
   1. Click OK on popup.

## Actual result:

Browser crashes.

Case 1 crash report examples:
`f5340000-45d5-d704-0000-000000000000`
`f6340000-45d5-d704-0000-000000000000`

Case 2 crash report example:
`04350000-45d5-d704-0000-000000000000`

I also see this in the logs:
```
[2968:775:0806/170849.913706:VERBOSE1:ads_service_impl.cc(656)] Shutting down and resetting ads state
[0806/170849.919832:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee78b0000, 0x2000): (os/kern) invalid address (1)
Segmentation fault: 11
```

## Expected result:
No crash

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.11.x n/a, 1.12.x yes
- Can you reproduce this issue with the beta channel? 1.13.x yes
- Can you reproduce this issue with the nightly channel? 1.14.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @NejcZdovc @tmancey @brave/legacy_qa @rebron

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - `1.12.108`

**Comment by LaurenWags** [comment]
Requires new 1.12.x build to test

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from https://github.com/brave/brave-browser/issues/11125#issue-674607248
* Confirmed no crash when resetting Rewards if Rewards are toggled off
* Confirmed no crash when resetting Rewards if Ads are toggled off but Rewards are toggled on
* Confirmed no crash when resetting Rewards if both Ads and Rewards are toggled on

---------
