### ISSUE TITLE
[Desktop] Chromium 85 update follow up: look into enabling PGO profiles.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#11121]
Chromium 84 enabled PGO for official builds on Mac and Windows:
* https://source.chromium.org/chromium/chromium/src/+/5060347a703aed0c897a27194caefe1e6a216b0c
* https://source.chromium.org/chromium/chromium/src/+/da89399184f94ee769236ca7c76f0b104a123cf3

During Chromium 85 upgrade tools have been modified to start downloading PGO profiles.
Our build process was modified to allow for it here:
https://github.com/brave/brave-core/pull/6042/commits/137d51e906d8b78999869222e9bb9998d461a0d3 ("Added custom_vars to gclient config for src."), but we @iefremov and @bridiver suggested we need to look more into it.
PGO was consequently disabled here:
https://github.com/brave/brave-core/pull/6042/commits/d3c599a308dfb4558064208d6266e4573832b208 ("Code Review: turn off PGO.").

**Comment by LifeIsStrange** [comment]
Couldn't the PGO be used for Android too now that 85 is stable?

**Comment by atuchin-m** [comment]
a duplicate for https://github.com/brave/brave-browser/issues/20086 ?

**Comment by LifeIsStrange** [comment]
@atuchin-m Brave not doing PGO builds for Android seems like a big missed opportunity for performance.. Such a key low hanging fruit!
You should also do LTO.

But if Brave really cares about the end user experience or about having a very significant competitive advantage over the competition AKA being the faster browser, the methodnis simple, in addition to PGO+LTO, dimply use BOLT as a post processing step. 
It can be used outside of llvm, the incoming merge is optional

**Comment by bridiver** [comment]
closed by https://github.com/brave/brave-browser/issues/20086 https://github.com/brave/brave-core/pull/11549
