### ISSUE TITLE
Tor process reaping on Windows

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#1113]
Currently, tor process will be left alone when browser crash or killed on Windows.
Other platforms have different strategy to handle this situation
Mac: Terminate tor process in `SuicideOnChannelErrorFilter`
Linux: `prctl(PR_SET_PDEATHSIG, SIGKILL)` through `LaunchOption.kill_on_parent_death`

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/4802

<details>
<summary>OS-chosen port for tor</summary>

![image](https://user-images.githubusercontent.com/38657976/96967844-b76cbb00-152d-11eb-9fe4-0de5358946ad.png)
![image](https://user-images.githubusercontent.com/38657976/96967885-c3587d00-152d-11eb-8616-29439c70d084.png)


</details>
