### ISSUE TITLE
Open tabs only sync's when all sync options is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11130]
## Description 

Open tabs only sync's when all sync options is enabled

## Steps to Reproduce

   1. Create a sync chain on desktop
   2. Add an Android device to the chain
   3. Enable Open tabs sync on both devices
   4. Visit a page on desktop and right click on tab, `Send to mobile device` option is missing
   5. Click on the URL bar, send to mobile icon doesn't show up 
   6. Enable History sync on both the devices
   7. Still doesn't show send to mobile device option on tab/url bar
   8. Enable Sync all on both devices
   9. Send to mobile device options shows up on URL bar and Tab

## Actual result:

Open tabs only sync's when all sync options is enabled

## Expected result:
Should be able to send open tabs between devices without having to enable sync all

## Reproduces how often: 

Easy

## Desktop Brave version:

Brave | 1.13.61 Chromium: 84.0.4147.105 (Official Build) beta (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{# 943}
OS | Linux

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jsecretan

**Comment by AlexeyBarabash** [comment]
I can reproduce, but even after `8. Enable Sync all on both devices` I cannot send link teither desktop => android or android => desktop.
But I have a lot of iterations of create/leave sync chain while trying previous tickets.

**Comment by AlexeyBarabash** [comment]
The behaviour is changed by upstream. It is possible to send tan without any options. Agreed with @srirambv in DM to close it.
