### ISSUE TITLE
[Desktop] Support Template Literals or External Files for SpeedReader content_script values

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#11135]
## Description 
Presently, the `content_script` associated with a _SpeedReadable URL_ is a simple, single-line string. Any attempt to use a multi-line template literals fails. For some domains, quite a bit of CSS or Scripting may be needed to create a better experience. In these cases, it would be helpful to have support for either multi-line content, or a reference to an external file.

**Comment by iefremov** [comment]
stale
