### ISSUE TITLE
Gemini toggle in brave://settings#newTab should not be available in unsupported regions

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#11136]
Currently, the option to toggle the Gemini widget in `brave://settings#newTab` is always available. It should be present/hidden depending on whether or not Gemini is supported.

## Steps to Reproduce
1. Fresh profile with an unsupported install region (Japan for instance)
2. Navigate to `brave://settings#newTab`.

### Result
Gemini toggle option is available

### Expected Result
Gemini toggle option is hidden

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave	1.14.67 Chromium: 85.0.4183.83 (ಅಧಿಕೃತವಾಗಿ ನಿರ್ಮಿಸಿ) dev (64-ಬಿಟ್)
ಪರಿಷ್ಕರಣೆ	94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS	Windows 10 OS Version 1809 (Build 17763.1397)
```
- Verified the STR from the description
- OS Locale is set to India (Kannada) and verified that `Gemini` toggle is not shown in `brave://settings#newTab`
- Verified that Gemini widget isn't shown in NTP and Dashboard settings
