### ISSUE TITLE
[Android] Open tabs notification shows up even after being dismissed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11131]
## Description 
 Open tabs notification shows up even after being dismissed

## Steps to reproduce 

   1. Follow steps to perform open tabs sync
   2. Wait for notifications to show up on Android
   3. Clear all notifications from the notification tray
   4. Turn off and turn on Open tabs on Android
   5. Notifications show up again even after clearing out

## Actual result 
 Open tabs notification shows up even after being dismissed

## Expected result
Once notifications are cleared should not show again if open tabs sync option is toggled

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.12.109

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @jsecretan @AlexeyBarabash

**Comment by AlexeyBarabash** [comment]
Tried to reproduce on my devices where I created/left the chain several times and desktop does not send tab to phone because in 
`SendTabToSelfBridge::SetTargetDeviceInfoList()` fires check of 
```
    // Don't include devices that have disabled the send tab to self receiving
    // feature.
    if (!device->send_tab_to_self_receiving_enabled()) {
      continue;
    }
```

I think, something like this is for https://github.com/brave/brave-browser/issues/11130

**Comment by AlexeyBarabash** [comment]
On my device somehow feature `"send_tab_to_self_receiving_enabled": false`

![image](https://user-images.githubusercontent.com/24739341/90027183-ed392c00-dcc0-11ea-924c-e183a67f3083.png)

**Comment by AlexeyBarabash** [comment]
The problem is that after enabling `Open tabs` category neither desktop nor Android device doesn't send the updated device record with updated `send_tab_to_self_receiving_enabled` field

**Comment by AlexeyBarabash** [comment]
Update: device field send_tab_to_self_receiving_enabled gets synced (in other words goes to true after `Open tabs` category is on) in 1 minute after browser restart, both on Desktop and Android.

**Comment by AlexeyBarabash** [comment]
Issue happens on desktop also

**Comment by AlexeyBarabash** [comment]
Upstream issue is https://bugs.chromium.org/p/chromium/issues/detail?id=1128297

**Comment by AlexeyBarabash** [comment]
Upstream CL is https://chromium-review.googlesource.com/c/chromium/src/+/2416688

**Comment by AlexeyBarabash** [comment]
This is not applicable anymore because it is possible to send tabs even of there are no any datatype enabled.
https://github.com/chromium/chromium/commit/41153d8c546533b998a0ccfe3119651e4f7affc5#diff-3ed5be57922886d35586c0841cf19d49904f990bb4f58780b480d885a0321eccR54
