### ISSUE TITLE
[Desktop]

### ISSUE THREAD

**Issue by Johanie1994** [brave/brave-browser#11140]
## Description 
My BAT was automatically sent to bravepublisher without me knowing it

## Steps to Reproduce

   1. Go to uphold wallet
   2. My activity
   3. BAT sent to bravepublisher

## Actual result:
 Loss 27.9BAT

## Expected result:
 I should have it back.please help

## Brave version (brave://version info)
![image](https://user-images.githubusercontent.com/69426516/89734977-c8ab3d00-da91-11ea-84f0-ed347af97d57.png)

**Comment by hollons** [comment]
Thanks @Johanie1994 for reporting! I can help to resolve. Please email me at Steven@brave.com with your Wallet ID (found on `brave://rewards-internals`). Thank you in advance!

**Comment by Johanie1994** [comment]
Why is this closed? Nothing is resolved. I sent that guy above what he needs buts still no action...

**Comment by Johanie1994** [comment]
What do you mean not actionable?

**Comment by hollons** [comment]
Hi @Johanie1994, I'm happy to help! I don't recall receiving an email regarding this issue, would you mind re-sending and I can resolve ASAP. Thanks in advance!

**Comment by Johanie1994** [comment]
> Hi @Johanie1994, I'm happy to help! I don't recall receiving an email regarding this issue, would you mind re-sending and I can resolve ASAP. Thanks in advance!

Please check email , I have just sent you my wallet ID thank you

**Comment by hollons** [comment]
Hi @Johanie1994, did you send it directly to Steven@brave.com or on Community? Do you mind if I ask the email it was sent from if the former? I'm not seeing for some reason. Sorry for the inconvenience!

**Comment by hollons** [comment]
Thanks @Johanie1994, received!
