### ISSUE TITLE
[Desktop] Brave Rewards diagnostic log crash

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11143]
See some crashes specific to logging system.

https://brave.sp.backtrace.io/p/brave/triage?filters=(_deleted%3D0%2C(ver%2Ccontains%2C%2284.%22)%2C(callstack%2Cregex%2C%22(ledger%7Crewards)%22))&aggregations=((guid%2Cunique)%2C(classifiers%2Chead))&fingerprint=9eb1f442a65820484ac51a8ad5ea6ac49d8129adc27b993b40a2ac715683c1bd

https://brave.sp.backtrace.io/p/brave/triage?filters=(_deleted%3D0%2C(callstack%2Cregex%2C%22(ledger%7Crewards)%22))&aggregations=((guid%2Cunique)%2C(classifiers%2Chead))&fingerprint=e99c9a0ecaaf85981583281d633e2fafb8af8de684571ac2af4c7a33a67f5c5c

**Comment by tmancey** [comment]
No crash reports for 1.14.x, monitoring crashes on a daily basis

**Comment by NejcZdovc** [comment]
closing for now, @tmancey please reopen if this will be problem again
