### ISSUE TITLE
[Desktop] Claim doesn't work for existing wallets 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11144]
## Description 

When you are connecting already used KYC wallet to claim it will return 200 compared to 201 for new wallets. We need to handled 200 response as well. 

## Steps to Reproduce

   1. Enable rewards
   2. Connect old KYC wallet that was already connected

## Actual result:

Claim fails

## Expected result:
Claim should work

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Uplift approved, waiting on new 1.13.x build to test.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified test plan from #6384 and #6401 
- Verified STR from the description
- Clean profile, enabled rewards claimed ag grants and wallet status is `Not connected` and Balance info is displayed as expected in brave://rewards-internals
![image](https://user-images.githubusercontent.com/38657976/91318805-4339c380-e7d9-11ea-8592-17fc2c85b565.png)
![image](https://user-images.githubusercontent.com/38657976/91318893-5b114780-e7d9-11ea-8308-c51b7e191473.png)
![image](https://user-images.githubusercontent.com/38657976/91318931-649aaf80-e7d9-11ea-9671-47d084601044.png)

- Connected KYC'd wallet and confirmed Ad grants are moved to uphold card
![image](https://user-images.githubusercontent.com/38657976/91319813-70d33c80-e7da-11ea-8397-5dd2b2077375.png)

![image](https://user-images.githubusercontent.com/38657976/91319384-f2769a80-e7d9-11ea-9d63-6742e4ace5e2.png)
![image](https://user-images.githubusercontent.com/38657976/91319437-ff938980-e7d9-11ea-8df8-8a09e35ba23c.png)
