### ISSUE TITLE
[Desktop] Removed anonymous address from Uphold flow

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11150]

**Comment by LaurenWags** [comment]
Uplift approved, waiting on new 1.13.x build to test.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.6 x64` using the following builds:

```
Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.15.6 (Build 19G73)
```

* QA was completed via https://github.com/brave/brave-browser/issues/11144#issuecomment-680932723.
