### ISSUE TITLE
[Desktop]

### ISSUE THREAD

**Issue by Ablazeskiess** [brave/brave-browser#11159]
## Description 
Weird lines appearing when hovering over videos of YouTube. 

## Steps to Reproduce

I have no clue on how to reproduce this as it happens randomly on youtube, but i know for once it started happening often recently.

I have 3 different user accounts and this happens to all 3 of them, but not at the same time so i assume its a problem with either youtube or something with the user profiles. This had happened even on no extension default browser once.

## Result:

https://imgur.com/a/Es4egzr

## Brave version (brave://version info)
Brave	1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)
Revision	a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS	Windows 10 OS Version 1909 (Build 18363.900)
JavaScript	V8 8.4.371.22
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory="Profile 5" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,AutofillServerCommunication,TextFragmentAnchor,SmsReceiver,TabHoverCards,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,UseButtonTranslateBubbleUI,VideoPlaybackQuality --flag-switches-begin --disable-features=AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,AutofillServerCommunication,TextFragmentAnchor,SmsReceiver,TabHoverCards,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,UseButtonTranslateBubbleUI,VideoPlaybackQuality,WebContentsForceDark --flag-switches-end --enable-audio-service-sandbox --disable-sync
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\Net64\AppData\Local\BraveSoftware\Brave-Browser\User Data\Profile 5
Variations	5e3a236d-4113a79e

**Comment by srirambv** [comment]
This will be fixed in 1.12.x with #11067
