### ISSUE TITLE
[Android] Update onboardingv2 based on internal feedback

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#11169]
This issue is to update onboarding v2 based on internal feedback : https://bravesoftware.slack.com/archives/C0816QH3R/p1596291019275900

Onbording spec : https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/Mobile-onboarding-v2?node-id=359%3A9604

**Comment by srirambv** [comment]
Verification passed on the following devices with Android 10 running 1.13.83 x64 build

OnePlus 6T Onboarding | OnePlus 6T Privacy report modal
-- | --
![image](https://user-images.githubusercontent.com/17010094/91940760-e4e87580-ecef-11ea-99ca-0627ee9e0712.png) | ![image](https://user-images.githubusercontent.com/17010094/91940353-39d7bc00-ecef-11ea-8bbe-0bf1c9a194b3.png)

Samsung Tab A Onboarding | Samsung Tab A Privacy report modal
-- | --
![image](https://user-images.githubusercontent.com/17010094/91940781-ed40b080-ecef-11ea-8cf5-a66a297aa2f7.png) | ![image](https://user-images.githubusercontent.com/17010094/91940370-3e9c7000-ecef-11ea-8067-103c99f5e730.png)
