### ISSUE TITLE
[Android] Remove onboarding for existing user

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#11164]
## Description 
Remove onboarding for existing user

## Steps to reproduce 

   1. Open fresh installed app, skip onboarding and Upgrade to new version
   2. Set the date to some date after 60 days. 
   3. user would see onboarding from previous verison.

## Actual result 
It shows onboarding for existing user

## Expected result
It should not show onboarding for existing user

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build
- Verified test plan from issue description
---------------
Verification passed on Samsung Tab A with Android 10 running 1.12.112 x64 build
- Verified test plan from issue description
