### ISSUE TITLE
[Desktop] Blank Video After Switching Tabs

### ISSUE THREAD

**Issue by irv075** [brave/brave-browser#11168]
## Description 
When watching a video, if you switch to a different tab and then back again, no video output is displayed. The audio can be heard and the video controls (and the rest of the page) are visible as normal - only the actual video output is blank. Looks to be a re-occurrence of #9711 

## Steps to Reproduce

   1. Open a video (YouTube/Pluralsight etc)
   2. Switch to a new tab
   3. Return to the video tab

## Actual result:

The video output is blank, but audio can be heard and the video controls are visible as normal. Refreshing the page or choosing a different video does *not* always fix the problem - the video remains blank. Switching back and forth between tabs again sometimes returns the video back to normal, or opening a new tab and navigating to the video also works.

## Expected result:
Video is displayed normally

## Reproduces how often: 
Intermittent, but usually reproducible by switching back and forth repeatedly between several tabs, remaining on each tab for a few seconds

## Brave version (brave://version info)

Brave | 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1909 (Build 18363.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
N/K
- Can you reproduce this issue with the nightly channel? 
N/K

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by rebron** [comment]
@irv075 Can you update to our latest 1.13.86 and see if this is still reproducing for you? I just tried it now and can't reproduce what you're seeing.

**Comment by irv075** [comment]
I also can't reproduce this on 1.13.86 - closing issue
