### ISSUE TITLE
Rearrange LoadURL parameters and use defaults

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#11172]
Refactor `LoadURL` so that less frequently changed parameters are at the end of the function and have default values. This will allow us to make calls to `LoadURL` that are a little clearer to read in the default case.

Something like the following may make sense:

```
void LoadURL(
    const std::string& url,
    ledger::LoadURLCallback callback
    const ledger::UrlMethod method = ledger::UrlMethod::Get,
    const std::string& content = "",
    const std::string& contentType = "",
    const std::vector<std::string>& headers = {}
);
```

**Comment by NejcZdovc** [comment]
closing as it will be fixed in https://github.com/brave/brave-browser/issues/11216
