### ISSUE TITLE
target=_blank links do not load when clicked to open in new tab

### ISSUE THREAD

**Issue by franco27** [brave/brave-browser#1117]
with Windows 10 x64 and Developer Channel v0.55.3

1/after I click on a link
Foxit Reader or Magix

2/I get an untitled tab and an empty tab. When I refresh the web page, the website is still not displayed.
sans titre = without the title
https://i.imgur.com/FqVnpPC.png

3/ I am obliged to click on the address bar to get the www.
After that, when I click on "ENTER", I am able to access the website.

I didn't have this problem with the previous version 0.55.1 or 0.55.2.

**Comment by franco27** [comment]
the link has its attributes
<a href="http://www.foxitsoftware.com/french/products/reader/" target="_blank" class="imCssLink">Aller au site Internet - Télécharger</a>

or
<a href="http://www.magix.com/fr/page-layout-designer/" target="_blank" class="imCssLink">Aller au site Internet - Télécharger</a>

**Comment by franco27** [comment]
see the problem in video
https://drive.google.com/file/d/1RcV5C2EC8C_2AjEQwX8ZiLAATnlR9KQO/view?usp=sharing
https://drive.google.com/file/d/1sQ9zFJqV-wZb5qk1Eqvsa1CWJNJX92ZP/view?usp=sharing

**Comment by franco27** [comment]
another bug, on Google Drive, impossible to play a video with Brave

**Comment by franco27** [comment]
I have disabled the blockages (grey lion head) is still this problem. with Chrome, there is no problem.

**Comment by srirambv** [comment]
>another bug, on Google Drive, impossible to play a video with Brave 

Issue tracked here https://github.com/brave/brave-browser/issues/1122

I can reproduce the issue with URL not working from the website. Thanks for reporting it. Request you to not to post all issues you find in a single thread would be difficult to traige issues

**Comment by franco27** [comment]
Thank you for your reply. yes I should have created another topic for this problem #1122

I was also writing for my first problem, see the videos to better understand
when I click on these links, a tab opens empty and without title. I did the test with Vivaldi and I do not have this problem

**Comment by bsclifton** [comment]
Closing as stale - there haven't been any new reports in ~2 years and unfortunately the links above seem to be broken now. I'm not aware of any problems with target=_blank

@franco27 if you're still using Brave, please re-open this issue if you're still experiencing the problem. Thanks 😄
