### ISSUE TITLE
Ads not blocked on Cnet.com 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1118]
## Description 

Ads not blocked on Cnet.com 

## Steps to Reproduce

   1. Visit any link on cnet.com
   2. Page shows ads which are not blocked even with adblock set to `Block Ads`
   3. Visit the same link on muon browser, all ads are blocked (see screenshot comparison)

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/45489916-bdc7c080-b733-11e8-8ca1-895014589daa.png)
Muon
![image](https://user-images.githubusercontent.com/17010094/45490000-f49dd680-b733-11e8-9c64-eff211f0882f.png)

## Expected result:
All ads should be blocked by default

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.2 Chromium: 70.0.3538.12 (Official Build) (64-bit)
-- | --
Revision | ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS | Windows

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy

**Comment by LaurenWags** [comment]
Just noticed that b-c is being detected as an ad-blocker on an NYT article (using `0.55.3`) and b-l (using `0.23.205`) is not. https://www.nytimes.com/2018/09/12/opinion/new-york-primary-election-go-vote.html

<img width="1197" alt="screen shot 2018-09-13 at 9 23 01 am" src="https://user-images.githubusercontent.com/28145373/45491905-de464980-b738-11e8-93a2-e44ee6a29101.png">

**Comment by stshank** [comment]
I have the opposite problem on CNET today: All non-ad graphics are blocked. Fresh install of Brave Core on Windows. Images come back if I take shields down. Version 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)

![image](https://user-images.githubusercontent.com/16833251/45557652-f37fae80-b7f2-11e8-9888-f7f9811573b1.png)

**Comment by hferreiro** [comment]
This is working with Brave 0.57.1

**Comment by bbondy** [comment]
It's not working fully, it's just only reproducible on some machines.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/46818181-94a84900-cd4e-11e8-9760-30facece7eda.png)
