### ISSUE TITLE
[Android] Menu icon shown on both bottom bar and in top bar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11187]
## Description 
Menu icon shown on both bottom bar and in top bar

## Steps to reproduce 

   1. Install 1.11.105 from playstore
   2. Ensure with bottom bar enabled menu button is shown on the bottom bar
   3. Upgrade to 1.12.112 build
   4. Menu button is shown on both URL bar and on bottom bar
   5. Click on menu on the URL bar, menu opens up on the bottom toolbar

## Actual result 
![androidmenu](https://user-images.githubusercontent.com/17010094/89985942-b0931380-dc73-11ea-95cd-03061b7b5375.gif)

## Expected result
Should only show menu in URL bar when bottom bar is disabled

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.012.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by LaurenWags** [comment]
reproduces on clean install of 1.12.112 on x86 device for me

**Comment by GeetaSarvadnya** [comment]
Reproduced in `1.12.112` on Android ARM 5.1.1

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/6406 and https://github.com/brave/brave-core/pull/6405 have been merged. Once we get a new RC with the above, we can run through the above again 👍

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.113 x64 build
- Verified on a clean install menu is only shown on bottom toolbar 
- Verified on upgrade from 1.11.105 with bottom toolbar enabled, menu button is only shown on bottom toolbar
- Verified on upgrade form 1.11.105 with bottom toolbar disabled, menu button is only shown on the URL bar
