### ISSUE TITLE
Hide Chromium Ads setting that conflicts with Brave ad blocking

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#1119]
## Description 
We should disable the confusing Ads setting in Chromium settings that conflicts with Brave ad blocking. I think this is a new setting for Chromium, now is a good time to hide it and avoid using it because it is not as effective as Brave ad blocking. If you open settings and search for ads, it is highlighted under the Privacy and Security -> Content Settings menu. This is the screenshot of where the setting is located:

![image](https://user-images.githubusercontent.com/6763301/45496932-7d247300-b744-11e8-8a30-6dfae3853c33.png)

And here is what the toggle looks like:

![image](https://user-images.githubusercontent.com/6763301/45496988-9c230500-b744-11e8-8b81-2b7a62d36da1.png)

## Steps to Reproduce

   1. Open Settings
   2. Search for 'ads'
   3. Go to the Privacy and Security -> Content Settings -> Ads menu

## Actual result:
Screenshots above

## Reproduces how often: 
Always

## Brave version (chrome://version info)
Version 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)

### Reproducible on current release:
yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by GeetaSarvadnya** [comment]
Ads settings is still not hidden on 0.55.6
![issue 1119](https://user-images.githubusercontent.com/38657976/46144837-ca8ffc80-c27b-11e8-8945-cbc3f3852258.gif)

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows 7

Privacy and Security -> Content Settings -> Ads menu is gone
Searching for ads does not find Ads menu (it finds Downlo`ads`)
