### ISSUE TITLE
[Android] [Follow up #9865] Rewards retains ? icon even after enabling wallet via onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11198]
## Description 
[Follow up #9865] Rewards retains `?` icon even after enabling wallet via onboarding

## Steps to reproduce 

   1. For a new user, follow steps from https://user-images.githubusercontent.com/2388823/81741066-cdd8fb80-9452-11ea-8a80-265b4f0810d9.png by moving date ahead

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/90003858-9e719f00-dc8c-11ea-8437-266ca1e020ad.png>

## Expected result
`?` should be dismissed if the user is onboarded on rewards

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.12.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/6416 was merged into `1.12.x`.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.113 x64 build
- Verified steps from issue description
- Verified `?` is removed once the onboarding is completed
---------
Verification passed on Samsung Tab A with Android 10 running 1.12.113 x64 build
- Verified steps from issue description
- Verified `?` is removed once the onboarding is completed
