### ISSUE TITLE
autoplay allowed but URL bar still reads autoplay blocked

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1120]
## Description 
When attempting to view an .mp4 file on Google Drive, even if Autoplay is enabled URL bar still says Autoplay blocked. Disabling shields and attempting to play the video does not allow video to be played and console shows errors.

## Steps to Reproduce

   1. Clean profile 0.55.3
   2. Login to Google Drive
   3. Attempt to play an .mp4 file --> see notification in URL bar about autoplay being blocked.
   4. Click on this and choose to Always Allow, video still will not play (https://github.com/brave/brave-browser/issues/1122), console errors.
   5. Put shields down, video still will not play, console errors.

## Actual result:
Autoplay is blocked even if allowed, video will not play (shields up or down):
![screen shot 2018-09-13 at 12 52 59 pm](https://user-images.githubusercontent.com/28145373/45503137-f8415580-b753-11e8-9dff-408f56cd8dfc.png)

console errors: https://gist.github.com/LaurenWags/bda1b03eaeda8a3b8060b68cfd01ff8b#file-autoplay-txt

## Expected result:
Autoplay should not be blocked, video should play, no console errors.

## Reproduces how often: 
easily

## Brave version (chrome://version info)
Brave | 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)
Revision | ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS | Mac OS X

### Reproducible on current release:
no, does not reproduce on 0.23.107

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome?  no

### Additional Information
Reproduced by @srirambv on Win.

When playing an .mp4 on photos.google.com there are two requests to allow Autoplay, photos.google.com and then youtube.googleapis.com. When playing a video from drive.google.com you don't get the second request to allow autoplay - maybe related to this issue?

**Comment by yrliou** [comment]
Please see https://github.com/brave/brave-core/pull/520 for the test plan.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

* Verified with test plan from https://github.com/brave/brave-browser/issues/1120#issuecomment-425324033
