### ISSUE TITLE
[Desktop] Promotion server url handling

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11203]
Ref: #10987

**Comment by LaurenWags** [comment]
Verification in progress

```
Brave	1.14.69 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
Revision	94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6422 using staging env.

1. Confirmed able to claim UGP grant:
<img width="405" alt="1" src="https://user-images.githubusercontent.com/28145373/91760029-a001f900-eba0-11ea-88c2-bbbda350bffb.png">

2. Confirmed able to claim Ad grant:
<img width="393" alt="2" src="https://user-images.githubusercontent.com/28145373/91760035-a1cbbc80-eba0-11ea-904b-69f56e898a48.png">

3. After claiming ad grant, confirmed Ad grant moved to Uphold:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/.........../claim
> Method: UrlMethod::POST
> Content: ...

[5201:775:0831/151729.581645:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/.........../claim
> Result: Success
> HTTP Code: 200
> Body: null
```

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v1/suggestions/claim
> Method: UrlMethod::POST
> Content: ...

[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v1/suggestions/claim
> Result: Success
> HTTP Code: 200
> Body:
```

<img width="1177" alt="3a" src="https://user-images.githubusercontent.com/28145373/91760046-a6907080-eba0-11ea-8dd6-0e4c690c2552.png">
<img width="401" alt="3b" src="https://user-images.githubusercontent.com/28145373/91760050-a85a3400-eba0-11ea-958e-f13af84348cb.png">
<img width="403" alt="3c" src="https://user-images.githubusercontent.com/28145373/91760051-aa23f780-eba0-11ea-9c57-7362db218780.png">

4. Confirmed able to 1 time tip with VG:
<img width="407" alt="4a" src="https://user-images.githubusercontent.com/28145373/91760060-aee8ab80-eba0-11ea-804d-20653ea0aa9d.png">
<img width="654" alt="4b" src="https://user-images.githubusercontent.com/28145373/91760068-b019d880-eba0-11ea-93d3-a731bf604a63.png">

5. Confirmed able to do a recurring tip with VG (AC off):
<img width="396" alt="5a" src="https://user-images.githubusercontent.com/28145373/91760075-b27c3280-eba0-11ea-8e38-5f44f0db7d23.png">
<img width="655" alt="5b" src="https://user-images.githubusercontent.com/28145373/91760078-b3ad5f80-eba0-11ea-93f7-59ec10bd86a5.png">

6. Confirmed able to do a recurring tip with VG (AC on but empty):
<img width="397" alt="6a" src="https://user-images.githubusercontent.com/28145373/91760083-b60fb980-eba0-11ea-9d16-6989f4147e82.png">
<img width="647" alt="6b" src="https://user-images.githubusercontent.com/28145373/91760085-b8721380-eba0-11ea-82b7-4f709cbf7e51.png">

7. Confirmed able to do a recurring tip + AC with VG:

8. Confirmed able to do AC only with VG:

9. Confirmed able to do one time tip with Uphold:

10. Confirmed able to do a recurring tip with Uphold (AC off):

11. Confirmed able to do a recurring tip with Uphold (AC on but empty):

12. Confirmed able to do a recurring tip + AC with Uphold:

13. Confirmed able to do AC only with Uphold:

14. Confirmed able to restore a wallet with a waiting Ad grant:
<img width="397" alt="14" src="https://user-images.githubusercontent.com/28145373/91760099-be67f480-eba0-11ea-8741-2173fc0c9265.png">

15. Confirmed able to restore a wallet with anon user BAT:
<img width="399" alt="15a" src="https://user-images.githubusercontent.com/28145373/91760105-c162e500-eba0-11ea-9dd6-c5dc4fd342ea.png">
<img width="240" alt="15b" src="https://user-images.githubusercontent.com/28145373/91760108-c32ca880-eba0-11ea-8408-363552b7e8f5.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.14.83 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/6422
