### ISSUE TITLE
[Android] Rewards panel retains the red dot after onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11202]
## Description 
Rewards panel retains the red dot after onboarding

## Steps to reproduce 

   1. Clean install 
   2. Finish rewards onboarding
   3. Panel retains red dot 

## Actual result 

![rewardsdot](https://user-images.githubusercontent.com/17010094/90011739-0d092980-dc9a-11ea-89df-cda80639a179.gif)

## Expected result
Should not retain red dot on panel

## Issue reproduces how often 
Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.12.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by deeppandya** [comment]
@srirambv this was the behaviour from previous versions. so i left it as it is. we use red dot to show notification counts. i can update it if you feel it needs to be updated.

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/6416 was merged.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.12.113 x64 build
- Verified red dot is removed once onboarding is completed
-------
Verification passed on OnePlus 6T with Android 10 running 1.12.113 x64 build
- Verified red dot is removed once onboarding is completed
