### ISSUE TITLE
[Android] Open any links from gmail or slack via Brave is causing the crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11208]
## Description 

Open any links from gmail or slack via Brave is causing the crash
## Steps to reproduce 

   1. Clean or upgraded profile `1.12.112` Chromium 84.0.4147.125
   2. Open link from Gmail or slack via Brave
   3. Brave crashes

## Actual result 
Brave crashes

## Expected result
Brave should not crash

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Not sure
- Can you reproduce this issue with the current Play Store Nightly version? Not in 1.14.10 Chromium 84.0.4147.105

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy
   - Android version: 5.1.1
   
## Brave version
1.12.112 Chromium 84.0.4147.125

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @anthonypkeane @SergeyZhukovsky

**Comment by btlechowski** [comment]
Reproduced on `1.12.112` on Samsung Galaxy Tab S5e (Android 9.0)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.113 x64 build
- Verified opening links on a custom tab via Slack didn't cause a crash
- Verified opening links on a custom tab via Gmail didn't cause a crash
- Verified opening custom tabs in the browser didn't cause the browser to crash
----------------
Verification passed on Samsung Tab A with Android 10 running 1.12.113 x64 build
- Verified opening links in the browser via Slack didn't cause a crash
- Verified opening links on a custom tab via Gmail didn't cause a crash
- Verified opening custom tabs in the browser didn't cause the browser to crash
