### ISSUE TITLE
[Desktop] Devices are not synced after upgrade from V1

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11206]
## Description 

Devices are not synced after upgrade from V1. Network error is shown in the brave://sync-internals even though there is no network issue. The issue is not reproducible in 1.14.34 ( upgrade from 1.11.x to 1.14.34). The issue persists when upgrading 1.11.x to 1.12.x

## Device Details
Device A: windows 10 (physical machine)
Device B: windows 10 (VM)
## Steps to Reproduce

   1. Install `1.11.104` on both devices A, B
   2. Launch brave with a clean profile and enable sync in both devices via chrome://flags
   3. Establish sync between Devices A, B
   4. Bookmark cnn.com in Device A and make sure it gets synced in Device B
   5. Upgrade profiles to `1.12.112` in both Devices A, B
   6. Ensure sync chain is not retained but the bookmark is retained in both devices
   7. Open brave://sync in Device A and Device B
   8. Start a sync chain in Device A and copy the code from Device A and paste it in Device B and click confirm in both devices
   9. Devices are not synced at all ( waited for 10 to 15 mins)

## Actual result:

Devices are not synced after upgrade from V1

![image](https://user-images.githubusercontent.com/38657976/90024703-cd126880-dcd2-11ea-8c2b-0a2f0b2d73eb.png)

**brave://sync-internals**
![image](https://user-images.githubusercontent.com/38657976/90024818-f632f900-dcd2-11ea-8e09-eed340416675.png)

## Expected result:
Devices should be synced after upgrade from V1

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1903 (Build 18362.959)
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? No - 1.14.34

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @jsecretan @rebron @darkdh

**Comment by btlechowski** [comment]
Not reproducible on my Windows 7 and Windows 10 machines

**Windows 7**

Brave | 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Upgraded from

Brave | 1.11.104 Chromium: 84.0.4147.105 (Oficjalna wersja) (64-bitowa)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

**Windows 10**

Brave | 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1909 (Build 18363.959)

Upgraded from

Brave | 1.11.104 Chromium: 84.0.4147.105 (Oficjalna wersja) (64-bitowa)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1909 (Build 18363.959)

**Comment by darkdh** [comment]
according to the screenshot you shared on slack
![image](https://user-images.githubusercontent.com/11330831/90046711-b396ff80-dc85-11ea-860a-c5c41e00d408.png)
`--sync-url=https://no-thanks.invalid ` that is the reason
which might related to https://github.com/brave/brave-browser/issues/8263 because some of the old features retained and duplicated
However, relaunch will make the `--sync-url` right.
![image (1)](https://user-images.githubusercontent.com/11330831/90046871-ea6d1580-dc85-11ea-81d9-0101580f2e6a.png)

**Comment by GeetaSarvadnya** [comment]
@darkdh After the relaunch issue is fixed. Devices are synced in V2

**Comment by GeetaSarvadnya** [comment]
This issue persists in android also. Verified on `BraveModernarm 1.12.112` on Android version 5.1.1. Unable to sync devices after upgrade from v1, but when I restart the browser in Android devices are getting synced V2

**Comment by GeetaSarvadnya** [comment]
@srirambv If this issue is taken care in other issues in Android repo, please remove the OS/Android label and link the issue id here.

**Comment by jsecretan** [comment]
Given the launch of Sync v2, I think this is probably no longer relevant as many who would upgrade have already done so.
