### ISSUE TITLE
[Android] "Sync isn't working" modal on new installs

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11210]
## Description 

When launching a new installation of Brave, you'll get a `Sync isn't working - Initial sync setup failed` infobar appearing at the bottom of the screen. Taping on `Open Settings` opens the `Sync and Brave services` settings page which is used by Chrome.

## Steps to reproduce 

   1. install the latest nightly brave
   2. once installed, skip the `Privacy Report` onboarding modal

You'll notice a `Sync isn't working` infobar at the bottom of the screen.

## Actual result 

| Modal  | Settings Page |
| ------------- | ------------- |
| ![Screenshot_20200812-171027_Brave](https://user-images.githubusercontent.com/2602313/90073577-74899e00-dcc7-11ea-9a09-1554a9f627c7.jpg)  | ![Screenshot_20200812-172710_Brave](https://user-images.githubusercontent.com/2602313/90073594-7f443300-dcc7-11ea-90c7-a689d058c2ef.jpg) |

## Expected result

Users who installed Brave for the first time shouldn't be seeing the `Sync isn't working` infobar.

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `N/A`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Phone`
   - Android version: `Android 10`
   
## Brave version

* Used `1.14.31 CR: 85.0.4183.59`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @btlechowski @AlexeyBarabash @SergeyZhukovsky @srirambv @ jsecretan

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
- Verified no sync message is shown when opening a normal tab or a private tab on a clean install 
- Verified no sync message is shown when opening a normal tab or a private tab when upgrading from an older build
- Verified no sync message is shown irrespective of sync is being enabled or disabled on an upgrade install
----------------------
Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
- Verified no sync message is shown when opening a normal tab or a private tab on a clean install 
- Verified no sync message is shown when opening a normal tab or a private tab when upgrading from an older build
- Verified no sync message is shown irrespective of sync is being enabled or disabled on an upgrade install
