### ISSUE TITLE
[Desktop] LoadUrl should just accept object instead of multiple paramters

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11216]
This allows us to add new flags and at the same time have one simple object. This will also save problem that @emerick reported here https://github.com/brave/brave-browser/issues/11172. We are already doing this with response.

Mojo structure:

```
struct UrlRequest {
  string url;
  array<string> headers;
  string content;
  string content_type;
  UrlMethod method;
  bool skip_log;
};
```

`skip_log` is a new option that allows skipping of request logging.

**Comment by zenparsing** [comment]
Regarding `should_log`, generally speaking it's preferable to structure boolean fields so that they default to `false`.

How will this look to use in calls to `ledger_client()->LoadURL(...)`?

**Comment by NejcZdovc** [comment]
changed to `skip_log` so that is false by default.

Example of usage:
```
ledger:: UrlRequest request;
request.url = "https://brave.com";
request.method = ledger::UrlMethod::GET;
ledger_->LoadURL->(request, some_callback);
```
