### ISSUE TITLE
[Android] Update SI banner text

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#11213]
This issue is to update text based on : https://github.com/brave/brave-browser/issues/11199#issuecomment-673026319

**Comment by srirambv** [comment]
- Verification passed on OnePlus 6T with Android 10 running 1.12.113 x64 build
   <img width=300 src=https://user-images.githubusercontent.com/17010094/90126477-a6e4db00-dd5b-11ea-8f1b-6d81ed144a96.png>

-------

- Verification passed on Samsung Tab A with Android 10 running 1.12.113 x64 build
   <img width=500 src=https://user-images.githubusercontent.com/17010094/90126560-c845c700-dd5b-11ea-8341-cf92f491f2d8.png>
