### ISSUE TITLE
[Desktop] update install extension text to remove review language

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#11214]
## Description 

Current text when installing extensions implies a Brave review. 

Text should read as:
"Brave does not review extensions for security and safety. Only install this extension if you trust the developer."

## Steps to Reproduce

   1. Go to Extension Web Store https://chrome.google.com/webstore/category/extensions?hl=en-US
   2. Select an extension to 'Add to Brave'
   3. Click 'Add to Brave' and notice dialog.

## Actual result:
<img width="487" alt="Screen Shot 2020-08-12 at 9 18 01 PM" src="https://user-images.githubusercontent.com/5951041/90094075-dd7e0f80-dce1-11ea-886c-6577389ad30a.png">

## Expected result:
![image](https://user-images.githubusercontent.com/2388823/90551625-74b1ef80-e146-11ea-9218-3a19a04cc5b9.png)

## Reproduces how often: 

See str.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
Related prior issues:
https://github.com/brave/brave-browser/issues/1408
https://github.com/brave/brave-browser/issues/3231

cc: @karenkliu @fmarier @pes10k

**Comment by bbondy** [comment]
Maybe:
Brave does not review extensions for security and safety. Only install this extension if you trust the developer.

**Comment by rebron** [comment]
Let's go with"Brave does not review extensions for security and safety. Only install this extension if you trust the developer." and I'll update the original issue.

**Comment by karenkliu** [comment]
Designs added!

**Comment by mkarolin** [comment]
@rebron, does this need to be uplifted (and if yes how high)?

**Comment by LaurenWags** [comment]
Clarifications requested from @rebron

**Comment by LaurenWags** [comment]
Confirmed with @rebron this issue is for the text change, no design changes as of right now.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.16.52 Chromium: 86.0.4240.68 (Official Build) dev (x86_64)
-- | --
Revision | ad72ee9aa8e15ed300df1238e76c7a8f4d686f97-refs/branch-heads/4240@{#1097}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified STR from description.

Confirmed displays as per the issue description:
<img width="475" alt="Screen Shot 2020-10-05 at 12 49 53 PM" src="https://user-images.githubusercontent.com/28145373/95108599-7b51f180-0709-11eb-9051-6c6364d8c946.png">

Note, extension name is not listed on the dialog box, this is logged with https://github.com/brave/brave-browser/issues/5575

----------
