### ISSUE TITLE
[Desktop] Installation Error

### ISSUE THREAD

**Issue by mallapurbharat** [brave/brave-browser#11212]
## Description 
Context as to why I'm installing the Beta version (which failed with an error)... 

- I've been facing issues with the regular stable release of Brave for the past month or more on Windows 10 Professional where it crashes around 20 seconds after starting. 

- The same release for Ubuntu/Linux works beautifully as expected. 

- One of the [issues raised on the Brave Community ](https://community.brave.com/t/brave-crashes-20-seconds-after-starting-after-new-windows-10-update-applied/143551) seemed to point to uninstalling Brave and clearing the App\LocalData folder before installation of the stable release. That didn't work. 
- Another person reported that the Beta release was working for them. So, I clean-installed Brave Beta (1.3.99.0) just now. 
- Installation failed with an error: "Egads! Installation failed. Error code: 0xa0430721."
- When I search for this error on google, it talks about chrome corrupted installation file. 
- UPDATE!! Brave Desktop Dev Channel v1.13.68 SUCCESSFULLY INSTALLS AND RUNS, BUT NOT BRAVE BETA!! 

## Steps to Reproduce
   1. Download the Brave browser Beta (1.3.99.0) 
   2. Install it
   3. Voila! See error "Egads! Installation failed. Error code: 0xa0430721.

## Actual result:

![Brave-Browser-Beta Installer 13-08-2020 07_13_16 AM](https://user-images.githubusercontent.com/10878214/90085750-5dce6000-dd36-11ea-8de2-484182e967b0.png)

## Expected result:
Install should complete successfully.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.3.99.0 (since install failed, I cannot paste brave://version information)

## Version/Channel Information:

Brave Beta 1.3.99.0
- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not Applicable 
- Does the issue resolve itself when disabling Brave Rewards? Not Applicable
- Is the issue reproducible on the latest version of Chrome? No (and not reproducible on Brave Linux as well)

## Miscellaneous Information:
Brave Desktop Dev Channel v1.13.68 SUCCESSFULLY INSTALLS AND RUNS, BUT NOT BRAVE BETA!!

Desktop Dev Channel Information (This successfully installs and runs smoothly!)
1.13.68 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)--
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1903 (Build 18362.959)

**Comment by bsclifton** [comment]
@mallapurbharat glad to hear dev is working; but Beta isn't working? Can you download a newer version of Beta?
https://brave.com/download-beta/

1.3.99 is from January (~[7 months out of date](https://github.com/brave/brave-browser/releases/tag/v1.3.99) 😱); We've made changes to the installer since then which is likely why you're seeing the error

Please let us know if this works. Thanks!

**Comment by rebron** [comment]
@mallapurbharat We're closing this one off. Let us know if you're still having this issue with our current builds and we'll open it back up.
