### ISSUE TITLE
[Desktop] Add a util function to cover Profile::IsOffTheRecord, Tor profiles, and guest sessions

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#11218]
We have Tor regular and Tor incognito profiles created when using Tor window, the regular one will return false for `Profile::IsOffTheRecord`. Some of our services currently only checks `Profile::IsOffTheRecord` where it will miss Tor regular profile, and guest profile's parent profile (they also seem to create a pair as we do for Tor).
This issue is to add a brave's own IsRegularProfile to exclude otr, Tor profiles, and guest sessions.

**Comment by tmancey** [comment]
@fmarier FYI

**Comment by yrliou** [comment]
When creating Tor window, we have a pair of profile being created, one regular dummy profile and one incognito one which is used for actual browsing. It is expected that one would return true for `Profile::IsOffTheRecord` and the other one would return false for `Profile::IsOffTheRecord`.
Plan here is to add `brave::IsRegularProfile` for our own services to use which will return `!brave::IsTorProfile && profile::IsRegularProfile`.
