### ISSUE TITLE
Brave Rewards service is associated to Tor Profiles

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#11223]
## Steps to Reproduce

   1. Launch browser
   2. Open a new Tor profile

## Actual result:

Brave Rewards service is associated to a Tor profile

## Expected result:
Brave Rewards service should not be associated to a Tor profile

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
This can also be resolved by https://github.com/brave/brave-browser/issues/11218, however until a decision has been made on how best to resolve we need to fix Brave Rewards

**Comment by tmancey** [comment]
Closing this issue as https://github.com/brave/brave-browser/issues/11218 will resolve the issue for all services including BAT Ads and BAT Ledger (Brave Rewards).

@LaurenWags If this could still be tested once the above PR lands, that would be great

**Comment by tmancey** [comment]
Discussed in DM's and re-opening as a temporary fix

**Comment by GeetaSarvadnya** [comment]
Verification passed on **Windows 10 x64** using

```

Brave | 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```

**`Test Case 1`** - running through STR/Cases outlined via https://github.com/brave/brave-core/pull/6418#issue-467330572

* launched `Nightly` via the following:

```
--args --enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6 --rewards=staging=true --brave-ads-staging
```

* enabled rewards
* claimed UGP grant
* viewed ad (ensured ad notification appeared and was counted via `brave://rewards`)
* opened `brave://rewards-internals/` and clicked on `Logs` --> `Download full log` (nothing should happen)
* logged into a KYC'd staging account via Uphold
* tipped both https://kjozwiakstaging.github.io & https://laurenwags.github.io

Once the above was done, created a new `Tor Window` and ensured that the following folders/files weren't being created/appeared within `session_profiles/Tor Profile`:

```
* ~/Library/Application Support/BraveSoftware/Brave-Browser/Default/session_profiles/Tor Profile/ads_service
* ~/Library/Application Support/BraveSoftware/Brave-Browser/Default/session_profiles/Tor Profile/rewards_service
* ~/Library/Application Support/BraveSoftware/Brave-Browser/Default/session_profiles/Tor Profile/Rewards.log
* ~/Library/Application Support/BraveSoftware/Brave-Browser/Default/session_profiles/Tor Profile/publisher_info_db
```
**`Test Case 2`** - running through STR/Cases outlined via https://github.com/brave/brave-browser/issues/11042#issue-670268909

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/11042#issue-670268909 and ensured that I didn't received random ads from other regions nor two ads at the same time. I went through the case several times and couldn't reproduce.
