### ISSUE TITLE
[Android] There is no Tab bar on tablet

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#11226]
This is a recent regression. 

## Steps to reproduce 
1. Clean install on Tablet
2. Cancel onboarding

## Actual result 
There is no Tab bar
![Screenshot_20200813-134632_Brave - Nightly](https://user-images.githubusercontent.com/34715963/90131554-9ee16700-dd6c-11ea-9f2c-05915e3ecbcb.jpg)

## Expected result
Tab bar is visible

## Issue reproduces how often 
100% repro rate

## Version/Channel Information:
BraveModernarm v1.14.36 on Samsung Galaxy Tab S5e (Android 9.0)

cc @brave/legacy_qa @SergeyZhukovsky @deeppandya

**Comment by deeppandya** [comment]
@btlechowski it happens with 1.14.28 as well. so i believe it might regression in chromium bump.

**Comment by samartnik** [comment]
@deeppandya  it's not happening for me on version 1.14.33, so it's not related to chromium bump

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.13.84 x64 build
- Verified tabs bar is visible
![image](https://user-images.githubusercontent.com/17010094/92098181-d45bfc00-edd0-11ea-82db-fe2c8f8d6834.png)
