### ISSUE TITLE
Provide a way to sort Bookmarks

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#11227]
## Description 

**1st problem(Required Feature)**: --- In bookmarks menu provide sorting feature so that bookmarks can be sorted ascending or desending based on date of creation. 
Currently latest created bookmark appears at bottomost and so if we have thousands of bookmarks we need to scroll through all them to get latest one.

Also the scroll bar is so thin that holding and dragging it to bottommost bookmark is very difficult.

**2nd Problem (Required Feature)**: --  Please provide a option to import and export bookmarks as plain csv file so it can be exported  then edited then  reorganised and then reimported to browser so that desired bookmarks can be placed at topmost easily searchable position.

3rd(Required Change):--- Change position of menu from vertical right side to bottom horizontal as in UC Browser.
 ABOVE ARE SOME FLAWS IN BASIC REQUIREMENTS /FUNCTIONS FOR A BROWSER.
PLEASE ADD THEM AS NEW FEATURE REQUEST

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:10

## Version/Channel Information:

- Can you reproduce this issue with the current release?YES 
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the nightly channel?YES 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? YES

**Comment by silvershadowcc** [comment]
This is a vital function. I've imported bookmarks from my old browser and now have to scroll through ten thousands of bookmarks to reach the recent ones. I accidently sorted the bookmarks by name and found out this could not be undone. So, I had to remove all the bookmarks and re-import them to restore the order of creation date (being glad I kept my old browser).

**Comment by tathastu871** [comment]
Please Increase the scroll bar thickness and add functionality to drag it by holding so we can fastly reach at bottom

Also add feature to import and export bookmarks in plain csv or tsv file in android browser

Add feature to sort bookmarks

**Comment by tathastu871** [comment]
Why are you not taking this issue seriously and on immediate basis. BASIC BOOKMARK FUNCTIONALITY IS USELESS ON BRAVE AND I AM SWITCHING TO DIFFERENT BROWSER

**Comment by tortino** [comment]
sorry didn't see you were talking of android.

**Comment by bsclifton** [comment]
Updated issue title to capture the first issue 👍 

- 2nd issue (Import/export) is tracked with https://github.com/brave/brave-browser/issues/6378
- 3rd issue (Menu cleanup) is tracked with https://github.com/brave/brave-browser/issues/23465

**Comment by tathastu871** [comment]
https://github.com/brave/brave-browser/issues/22619
https://github.com/brave/brave-browser/issues/20199
https://github.com/brave/brave-browser/issues/18766
https://github.com/brave/brave-browser/issues/17886
https://github.com/brave/brave-browser/issues/15386
https://github.com/brave/brave-browser/issues/15144
https://github.com/brave/brave-browser/issues/11227

**Comment by tathastu871** [comment]
Major workaround for those bookmark related issues.

In menu in bookmark manager add two option: 
1) local   bookmarks
2) Synced bookmark

So that we can use a local bookmark text or html file and browse them
 They will be faster to load as it just had to read a text file with urls

**Comment by tathastu871** [comment]
Any news on it

**Comment by mrjohnr** [comment]
Please add this feature
