### ISSUE TITLE
[Desktop] Bookmarks bar on the new tab page cannot be disabled

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#11221]
## Description 

Bookmarks bar on new tab page cannot be disabled

## Steps to Reproduce

   1.  Launch brave 
   2. Try to disable the Bookmarks bar on the new tab page
   3. See that Bookmarks bar doesn't disappear even when disabled

Note: I imported some bookmarks from an HTML 5 file

## Actual result:

Bookmarks bar on the new tab page cannot be disabled

## Expected result:

Bookmarks bar on the new tab page can be disabled

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 1.12.108 (Release)

## Version/Channel Information:

Version 1.12.108 (Release)

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't checked 
- Can you reproduce this issue with the nightly channel? Haven't checked 

## Miscellaneous Information:

![Screenshot (8)](https://user-images.githubusercontent.com/69129878/90127393-ba576c80-dd82-11ea-85b1-41b4c4ca5bb7.png)

![Screenshot (7)](https://user-images.githubusercontent.com/69129878/90127039-2edddb80-dd82-11ea-9469-f8e3d2011d74.png)

**Comment by srirambv** [comment]
Try disabling `Show bookmarks` setting under Appearance
![image](https://user-images.githubusercontent.com/17010094/90130294-22498b00-dd62-11ea-8a59-641a4193ab64.png)

**Comment by FrostedIce339** [comment]
Tried it now, doesn't work. Bookmarks bar just doens't disappear from the new tab page.

**Comment by srirambv** [comment]
Sorry meant to say disable this one 
![image](https://user-images.githubusercontent.com/17010094/90163183-abc28280-dd8d-11ea-86b7-61e1bac5cdc2.png)

**Comment by bsclifton** [comment]
This is something we did look at before. I think we decided to keep it there
cc: @simonhong @rebron

**Comment by FrostedIce339** [comment]
> Sorry meant to say disable this one 
> ![image](https://user-images.githubusercontent.com/17010094/90163183-abc28280-dd8d-11ea-86b7-61e1bac5cdc2.png)
> 

Thanks, it worked! 

But one thing confuses me is that even if I disable or enable the `Show bookmarks` preference, why is it not being disabled or enabled? 

Anyway thanks a lot for the help.

**Comment by srirambv** [comment]
Closing as fixed
