### ISSUE TITLE
[Desktop] Restore modal window shows error before entering keys

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11235]
## Description 

When you open the backup/restore modal and select Restore, there is an error message displayed before you even attempt to restore a wallet.

Does not reproduce on 1.12.x.

## Steps to Reproduce

   1. Install 1.13.x
   2. Enable Rewards
   3. Open brave://rewards
   4. Click on gear
   5. Select Restore

## Actual result:

Error displayed before user attempts to import or enter keys
<img width="691" alt="1 13 x" src="https://user-images.githubusercontent.com/28145373/90259577-41a2ef80-de18-11ea-854d-aac4289a135b.png">

## Expected result:
No error
<img width="697" alt="1 12 x" src="https://user-images.githubusercontent.com/28145373/90259585-44054980-de18-11ea-93fc-c6e42b588ca3.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.13.71 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not reproduce on 1.12.x
- Can you reproduce this issue with the beta channel? yes 1.13.x
- Can you reproduce this issue with the nightly channel? yes 1.14.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Linux

Brave | 1.13.71 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/90300954-3940c800-de9d-11ea-8061-d7c934f1cad7.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.15.52 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified STR from the description
![image](https://user-images.githubusercontent.com/38657976/93231596-86fb6980-f796-11ea-9454-9792414bd470.png)
