### ISSUE TITLE
Implement ability to remove other devices in chain for sync v2

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#11232]
Need to implement ability to remove other devices from the sync chain for sync v2

We have feedback that such ability is very required: https://community.brave.com/t/how-to-remove-device-not-available-from-sync-list/152615 .

Please use test plan at the PR https://github.com/brave/brave-core/pull/6732

**Comment by AlexeyBarabash** [comment]
Related comment https://github.com/brave/brave-core/pull/5361#pullrequestreview-435343070

**Comment by w0ts0n** [comment]
+1 here
https://reddit.com/r/brave_browser/comments/i9jip8/each_device_can_be_managed_from_any_other_device/

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.18.63 x64 beta build
- Verified trash button is shown on all listed devices in sync chain
  <img width=300 src=https://user-images.githubusercontent.com/17010094/100422868-fdfc8a80-3082-11eb-830f-762627030ee7.png>
- Verified able to remove other devices by tapping on the trash bin button next to the device name
  <img width=300 src=https://user-images.githubusercontent.com/17010094/100422882-02c13e80-3083-11eb-9a38-73dfb1ec18f0.png>

-------
Verification passed on Samsung Tab A with Android 10 running 1.18.63 x64 beta build
- Verified trash button is shown on all listed devices in sync chain
  <img width=400 src=https://user-images.githubusercontent.com/17010094/100422897-0a80e300-3083-11eb-8af1-10d87cd924bb.png>

- Verified able to remove other devices by tapping on the trash bin button next to the device name
  <img width=400 src=https://user-images.githubusercontent.com/17010094/100422913-0fde2d80-3083-11eb-88ce-33a9944f08eb.png>

**Comment by bharatmk256** [comment]
![Screenshot_2020-11-28-23-38-29-10](https://user-images.githubusercontent.com/37737418/100522988-dddbe100-31d2-11eb-9059-7f791c1114b4.jpg)

Trash icon is not visible for every devices
Brave beta 1.18.63
Android 10

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.68 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6732
**Note**: on Desktop the trash icon is shown only if the remote device in chain supports self-delete, version must be above  1.18.19

- Verified that Trash icon isn't shown for the desktop device C (this device) as the desktop has `Leave Sync Chain` option. 
Device A - Android `1.18.67`
Device B - Desktop `1.17.x` 
Device C - Desktop `1.18.68`
![image](https://user-images.githubusercontent.com/38657976/100853125-6b5a5200-34ad-11eb-9df3-dbfc0f73ca3e.png)

- Verified that the Trash icon is shown for the remote desktop device C in a sync chain. 
Device A - Desktop `1.18.68`
Device B - Android `1.18.67` 
Device C - Desktop `1.19.43`
![image](https://user-images.githubusercontent.com/38657976/100854124-98f3cb00-34ae-11eb-987c-5c7e8ad7d8c7.png)

**Comment by GeetaSarvadnya** [comment]
@bharatmk256 If you have installed the brave version which is below the self delete version `1.18.19` then the trash icon will not be shown, which is expected. Please install brave version which is higher than `1.18.19` in all the devices in a sync chain, you should be able to see the trash icon in all the devices in the sync chain, if you are not seeing the trash icon then it's a bug.

**Comment by cardin** [comment]
Is there any plans to support unsyncing devices that are **_not_** higher than `1.18.19`?

**Comment by AlexeyBarabash** [comment]
@cardin 
Sorry, we are unable to make it because this is impossible.

The client must do some actions to be removed from the chain in a proper way. 

Inherited part code from Chromium does cleanup for devices which hadn't do any activity for a long period (~3 months if I remember correctly).

**Comment by WueXiang** [comment]
@AlexeyBarabash although I dont know what is the mechanism behind this sync chain, I am pretty sure in a way or two something can be done to solve this issue. Something like letting user to clone contents from old sync chain and put it into a new sync chain, then migrate their devices to new sync chain one by one?

**Comment by AlexeyBarabash** [comment]
Hello @WueXiang,

Thanks, this is good idea. We will be able to do something similar to what you have suggested when we will split the chain id from the encryption key.
Right now the advise is to re-create sync chain and re-add only the devices which are required.
