### ISSUE TITLE
[Desktop] show more topsiteson newtab

### ISSUE THREAD

**Issue by cjwijtmans** [brave/brave-browser#11236]
Would like to have an option for 1 or 2 more rows.
So much wasted space.

**Comment by ericfurspan** [comment]
+1

The ability to add more (than 12) top sites would be great

**Comment by DmitryTestOne** [comment]
Any updates on this?
2-4 additional rows would help a lot. Especially taking into account that ui is already adapted for it.

**Comment by 424344** [comment]
I agree to have more icons, but probably brave won't do it, because it would partially hide sponsored pages...

**Comment by DmitryTestOne** [comment]
> I agree to have more icons, but probably brave won't do it, because it would partially hide sponsored pages...

In this case it could be something like a slider, to scroll the item's rows, like: 12 items in 2 rows, slide right, next 2 rows, slide right, next 2, slide back and etc.
The size of the block stays the same, more icons are added.

**Comment by cjwijtmans** [comment]
Why not both? Add more sponsors space and more web icons.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rebron** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/6619
