### ISSUE TITLE
[Desktop] Sync multiple brave instances on one PC

### ISSUE THREAD

**Issue by eggception** [brave/brave-browser#11234]
#2248  Description 
Can't sync bookmarks accross two Windows users' brave instances.
I have one Windows user for work and one for everything else, 
but i want to maintain a combined sync chain for bookmarks.

## Steps to Reproduce
1. Create seperate windows user
2. Set up new brave instance
3. Create sync chain
4. Join with second user
5. Enable bookmark sync for both

## Actual result:
Only one entry (device) listed in sync chain. Sync is not performed.

## Expected result:
Either a second row with same device name, or possibility to choose a custom device name for such cases.

## Brave version (brave://version info)
1.12.112

## Version/Channel Information:
Release

**Comment by jsecretan** [comment]
I think this should work, @AlexeyBarabash could you try to reproduce when you get a chance?

**Comment by bsclifton** [comment]
@eggception Are you using the same executable but different profiles? or using two versions of Brave (ex: Release and Beta). If using two versions of Brave, are both versions the latest?

**Comment by rebron** [comment]
@jsecretan I think the issue might be we use the same device name? Wondering if we add the feature to rename the device name or provide a way to have a unique name for a second or n instance of the same device.

@bsclifton I think it's the same executable just different Windows profiles/users.

**Comment by bsclifton** [comment]
Closing as stale - we didn't get a response. Device name being the same shouldn't matter; it would just be difficult to tell which is which. We need more info to solve
