### ISSUE TITLE
Missing a way to check latest stable version / Standardize GitHub releases

### ISSUE THREAD

**Issue by mixedCase** [brave/brave-browser#11231]
Hi, I maintain a Linux packaging script for Brave. As part of that work I need to be aware when a new stable version comes out.

Unfortunately for Linux you do not have a link under https://laptop-updates.brave.com/latest/xxxx like you do for Windows and macOS to download the latest binary (currently it seems the fallback route handler for that server redirects to manual Linux installation instructions).

Right now I'm resorting to parsing your GitHub releases every half an hour or so in an attempt to find a release marked as stable, but unfortunately the GitHub release seem to be done by hand and are not consistent (1.12.112 was first marked as stable, then prerelease like an hour or so later, then stable again; stable release titles have used different words in the past; etc).

Is there any reliable way I can check via automation what the latest release of Brave for Linux is? And if not, can we have one?

**Comment by bsclifton** [comment]
cc: @mihaiplesa @linhkikuchi

**Comment by mihaiplesa** [comment]
For now you can use https://brave-browser-downloads.s3.brave.com/latest/${CHANNEL}.version where CHANNEL is release, beta, dev, nightly to get the latest public versions.

You can also subscribe to get notified of GitHub releases and filter.

We might add https://laptop-updates.brave.com/latest/linux-xxx in the future.

**Comment by mixedCase** [comment]
@bsclifton @mihaiplesa Thank you!, that first link is exactly what I needed. Cheers
