### ISSUE TITLE
[Desktop] sync bookmarks to windows favourites folder

### ISSUE THREAD

**Issue by cjwijtmans** [brave/brave-browser#11237]
Syncing bookmarks to favourites folder should allow them to be synced with other browsers or with microsoft syncing.
Or allow me to have a git repo for syncing it, would even be better if brave used git for this from the start.

**Comment by rebron** [comment]
@cjwijtmans Thanks for filing. Closing this one out though. There are extensions for this feature and I don't see us doing work to sync bookmarks with other browsers.
