### ISSUE TITLE
[Android] Fingerprinting issue

### ISSUE THREAD

**Issue by pidus** [brave/brave-browser#11246]
## Description 

By default the browser is set to "block cross-site fingerprinting". If I manually change it for a site, I can't revert it back to default. 

## Steps to reproduce 

   1. Open a website (ghacks.net)
   2. Change the fingerprinting protection to "block all fingerprinting" 
   3. Go back
   4. Change the fingerprinting protection back to default "block cross-site fingerprinting" 
   5. Go back
   4. Check again to see the fingerprinting setting. 

## Actual result 

It's set to "block all fingerprinting" 
![Screenshot_2020-08-15-08-17-47-756_com brave browser](https://user-images.githubusercontent.com/11857051/90303918-1b408b00-ded0-11ea-8be3-f381f71d6013.png)

## Expected result

It should be set to "block cross-site fingerprinting"

## Issue reproduces how often 

Easily reproduced. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): PHONE
   - Android version: 7.1.1
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by pidus** [comment]
I'd also like to see a global option to set the fingerprinting protection type for *all* websites, like we have on desktop.

**Comment by cjwijtmans** [comment]
> I'd also like to see a global option to set the fingerprinting protection type for _all_ websites, like we have on desktop.

I was going to make an issue for this but if someone else can do that that would be great.

**Comment by cjwijtmans** [comment]
And likewise have the many global options that android provides in an easy interface for desktop. Some unification of the options and interface between platforms would be great.

**Comment by srirambv** [comment]
Thanks for the report. Verified its a regression. 

>I'd also like to see a global option to set the fingerprinting protection type for all websites, like we have on desktop.

This will be done as part of  #6831

**Comment by Hazbelll** [comment]
Do you have an ETA on when #6831 will go live?

I've also changed the global option for fingerprinting detection, but cannot go back to the default anymore (Cross-site fingerprinting).

Perhaps syncing to a desktop browser would allow this setting to be reverted from there?

**Comment by Hazbelll** [comment]
@srirambv May I ask if you might know whether there is an ETA on #6831 being completed?

It would coincidentally squash this bug and bring Brave for Android closer to parity with its Desktop counterpart.

**Comment by srirambv** [comment]
This should have been fixed with #10953. @pidus can you please update to the latest build and check once?

@Hazbelll right now there is no ETA on #6831. Its marked as P3 so it will first land on nightly and then make its way upto release but there is no hard deadline for that

**Comment by Hazbelll** [comment]
@srirambv Thank you for your response! May I ask why #6831 is deemed such a low priority?

Surely feature parity between platforms should be more important, especially as it introduces unnecessary bugs.

Once you change the global fingerprinting setting on Android for example, you cannot restore it back to the default setting - only on a per-site basis.

**Comment by Hazbelll** [comment]
> May I ask why #6831 is deemed such a low priority?

@bsclifton My apologies for the ping, but it would be appreciated if you could provide some insight to the above? Thank you.

**Comment by bsclifton** [comment]
@Hazbelll there are just a lot of things to work through ☹️ The number of developers available to grab issues on Android is limited

**Comment by Hazbelll** [comment]
@bsclifton Thank you kindly for your response and my apologies for the delay in mine.

I can understand available resources might be lacking which in turn hinders progress. It's still unclear what requires completing for #6831 to be merged for eventual release however as it looks like it's already been completed (Part of it has already been merged/released too).

From the comments, @srirambv mentions the graphics require updating to highlight what hasn't yet been completed, but no response was given and so it's not clear from a public perspective what (If anything) requires completion still.

I would like to again highlight that #6831 would bring the Android version to much closer feature parity with its Desktop counterpart, plus squashing an easily reproducible bug where once the global 'Fingerprinting Protection' setting under 'Privacy' is toggled, 'Block Cross-Site Fingerprinting' can no longer be globally restored (I can make a separate issue if required).

**Comment by anthonypkeane** [comment]
@srirambv can you please re-check

**Comment by pes10k** [comment]
Just wanted to follow up here.  @srirambv are you still seeing this?  If not, can we close?

**Comment by srirambv** [comment]
This seems fixed on the current nightly and release version. Closing the issue for now. Can reopen if it regresses again
