### ISSUE TITLE
[Desktop] Error 400 on https://www.usaa.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#11245]
## Description 
When transfering funds on `https://www.usaa.com/` can cause `400 Bad Request`

## Steps to Reproduce

   1. Login into `https://www.usaa.com/`
   2. Attempt to transfer funds
   3. Receive message of `400 Bad Request` `Request Header or Cookie Too Large`

`www.usaa.com/:1 Failed to load resource: the server responded with a status of 400 ()`

## Actual result:
<img width="569" alt="screen_shot_2020-08-14_at_9 43 10_am" src="https://user-images.githubusercontent.com/1659004/90301235-c104f180-def2-11ea-9900-9efbc6c3b338.png">

## Expected result:
Works in Brave Beta, expect not to error.

## Reproduces how often: 
Worked on fine on another Mac machine, but causing issues on a specific mac (in a new profile.)

## Brave version (brave://version info)
(Mac) Not tested in Windows `Version 1.12.112 Chromium: 84.0.4147.125`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel?  No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:
Tested with a new Brave profile, and with Shields down, User was still able to reproduce.

Works in Chrome.

Not a lot of details being shown in the console.

<img width="533" alt="screen_shot_2020-08-14_at_3 51 35_pm" src="https://user-images.githubusercontent.com/1659004/90301547-b9dee300-def4-11ea-9dc5-199aa5d37ced.png">

**Comment by ryanbr** [comment]
User had 2 Mac PC's, one fails to load it, other worked fine. We tried a new Brave profile on the problematic Mac, still caused the `Error 400`. We also tried clearing cookies before hand.

**Comment by pes10k** [comment]
Just to double check, on beta and beyond, it wasn't ever triggered?

**Comment by ryanbr** [comment]
Re-confirming with user, but initial testing confirmed Beta and Nightly worked.

**Comment by ryanbr** [comment]
Has been resolved, seemed to be fixed, user tried from another IP. Closing ticket.
