### ISSUE TITLE
[Desktop] Default site settings display issue 

### ISSUE THREAD

**Issue by georgesterpu** [brave/brave-browser#11248]
## Description 
Clicking the "View site information" lock icon in the address bar displays a long list of site permissions, with no possibility to scroll down to the bottom. This drop-down menu allows access to certificate and cookies information, but these options are not shown on screen. The listed site permissions seem unnecessarily redundant, as the default permissions are reported too. I am only able to see the bottom of this menu by making the browser window longer than my screen height, which is cumbersome. Switching to a new browser profile seems to address the issue, but I cannot find a relevant browser setting to automatically hide the default site settings in my first profile.

## Steps to Reproduce

   1. Click the "View site information" icon in the address bar

## Actual result:

![Screenshot](https://user-images.githubusercontent.com/6018251/90314176-a8540600-df09-11ea-8f6e-b858068f46dd.png)

## Expected result:
Display only the non-default site settings.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Using the brave browser from the Manjaro linux repositories, testing branch
```
Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) unknown (64-bit)
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Linux
```
also on
```
Brave 1.13.82 Chromium: 85.0.4183.83 (Official Build) unknown (64-bit)
Revision 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS Linux
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel? -N/A
- Can you reproduce this issue with the nightly channel? - N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - No 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by diracdeltas** [comment]
Seems like a Linux-only issue. I haven't seen this on MacOS. cc @fmarier

**Comment by rebron** [comment]
cc: @jonathansampson 

I think this is for all platforms and when you block all the permissions manually, you'll run into this issue where you'll have this long list and there's no scroll. You can still go the settings page and make the changes there, just that the drop down is unusable if you run out of screen space.

We're going to mark this as a p4.
