### ISSUE TITLE
[Desktop] Can't sign into Discord 

### ISSUE THREAD

**Issue by nutta-git** [brave/brave-browser#11243]
![Discordratelimit](https://user-images.githubusercontent.com/59726608/90288080-1e436900-de47-11ea-926e-25e25c124883.png)

## Description 
Can't sign-in to Discord 

## Steps to Reproduce

   1. Open a new tab
   2. Go to https://discord.com/
   3. Disable Brave Shield 
   4. Try signing in 

## Actual result:
you can't sign in, discord prompts " You are being rate limited. "

## Expected result:
Sign in to Discord

## Reproduces how often: 
[Easily reproduced]

## Brave version (brave://version info)
```
Brave	1.12.112 Chromium: 84.0.4147.125 (Official Build) unknown (64-bit)
Revision	d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS	Linux
JavaScript	V8 8.4.371.23
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
Command Line	/usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=MixedContentSiteSetting,WebUIDarkMode,PassiveMixedContentWarning,AutoupgradeMixedContent,PasswordImport,ReducedReferrerGranularity,PrefetchPrivacyChanges,DnsOverHttps --disable-features=LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,TextFragmentAnchor,UseButtonTranslateBubbleUI,VideoPlaybackQuality,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,SmsReceiver,TabHoverCards --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/brave-bin/brave
Profile Path	/home/corn/.config/BraveSoftware/Brave-Browser/Default
```

## Version/Channel Information:
Arch Linux AUR ( brave-bin ) {1:1.12.112-2}
 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
Not tested
But Discord does work fine with FireFox 79.0 (64-bit)

## Miscellaneous Information:

Also have to mention, the  reCAPTCHA was extremely "slow", required multiple tries.

**Comment by Wolfe1** [comment]
@nutta-git I just attempted this with no issues.

Brave Dev Version 1.13.71 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)

**Comment by nutta-git** [comment]
Seems like it figured it out: 
when you go on to Discord, you are supposed to click "Login" @ the top right hand corner and not sign in using "open discord / open discord for browser". 
issue is solved, thank you!
