### ISSUE TITLE
[Desktop] Brave is too verbose when extensions use the "Debug" feature

### ISSUE THREAD

**Issue by gaetschwartz** [brave/brave-browser#11249]
## Description 

When using extensions that use the debugging feature, Brave is too verbose unlike Chrome, which makes it pretty annoying to use.

![Screen Shot 2020-08-15 at 23 52 03](https://user-images.githubusercontent.com/25441359/90322313-1f61bc80-df53-11ea-8994-b31bdf08f2a4.png)

## Steps to Reproduce

   1. Install an extension like [Dart Debug](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm/related)
   2. Once installed, click on the extension.
   3. See a bar appear, with no way of hiding it or dismissing it without terminating the extension's debug session.

## Actual result:

![Screen Shot 2020-08-15 at 23 52 03](https://user-images.githubusercontent.com/25441359/90322313-1f61bc80-df53-11ea-8994-b31bdf08f2a4.png)

## Expected result:

Have a way to hide, dismiss the alert or maybe trust the extension and not show again.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

`1.13.72 Chromium: 84.0.4147.125
`
## Version/Channel Information:

- Can you reproduce this issue with the current release? Haven't tried for now.
- Can you reproduce this issue with the beta channel? Haven't tried for now.
- Can you reproduce this issue with the nightly channel? Haven't tried for now.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? **No.**

## Miscellaneous Information:

None.

**Comment by rebron** [comment]
@Blaxou Are you saying that you can close the information bar from the extension in Brave but you can in Chrome? I'm assuming the "x" closes the extension all together and not hide it?

**Comment by rebron** [comment]
cc: @petemill Are we doing anything with our infobar that might conflict with extensions using the info bar?

**Comment by Blaxou** [comment]
Exactly @rebron, pressing the x and closing the bar closes the extension too which makes us forced to keep the bar opened.
