### ISSUE TITLE
[Security] prune log responses

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#11255]
see https://github.com/brave/internal/issues/712#issuecomment-674643946 for details.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Mint 19.1 x64` using the following build:

```
Brave | 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
--- | ---
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Linux
```

* QA verification notes can be found via https://github.com/brave/internal/issues/712#issuecomment-675902420

**Comment by bbondy** [comment]
@NejcZdovc should this be marked `OS/Android`?

**Comment by diracdeltas** [comment]
@bbondy this should get fixed on android as well

**Comment by bbondy** [comment]
Understood, but wanted to see if this issue tracked the fix for Android too, or if there was a different issue for Android. If there is another issue, pls link to it. Noting too that pod leads should uplift to release channel if a hotfix is needed and ping Kamil and team to do a hotfix.

**Comment by diracdeltas** [comment]
Got it. There is no separate issue for Android.

**Comment by kjozwiak** [comment]
Going to create a duplicate issue of the above and put it into `1.13.x` as this one is in `1.12.x` and already released. This way @srirambv can verify on `1.13.x`.
