### ISSUE TITLE
[Desktop] text overlapping on uphold card

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11257]
## Description 

Follow up to #10838
text overlapping on uphold card
## Steps to Reproduce

   1. enable rewards
   2. connect KYC uphold account
   3. visit brave://rewards page
   4. text overlapping on uphold card
   

## Actual result:

text overlapping on uphold card

## Expected result:

Should not be any text overlap
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.13.72 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not sure 
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mandar-brave 

Additional info can be found here https://bravesoftware.slack.com/archives/CB0KCRCQN/p1597639817084700?thread_ts=1597406587.078700&cid=CB0KCRCQN

**Comment by mandar-brave** [comment]
@NejcZdovc pinging here if we can resolve this ahead of 1.13. thanks

**Comment by NejcZdovc** [comment]
we are too late for 1.13

**Comment by NejcZdovc** [comment]
would be good to check it out when we get new translations

**Comment by mandar-brave** [comment]
ok; moved this to P2. Please fix on priority so we can pull it up as/when we can. thanks.

**Comment by mandar-brave** [comment]
US only; translations should not be applicable.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.14.69 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)


```
- Verified the STR from the description
- There is no text/image overlap on the uphold card
