### ISSUE TITLE
[Desktop] Brave rewards stalled

### ISSUE THREAD

**Issue by vporton** [brave/brave-browser#11256]
"Brave rewards" shows 20.600 BAT apparently already several days. My rewards do not increase.

**Comment by tmancey** [comment]
@vporton Can you please let me know where you are located? Thanks

**Comment by tmancey** [comment]
@vporton Can you please email me a screenshot of the pages you are referring to. Thanks

**Comment by vporton** [comment]
> @vporton Can you please email me a screenshot of the pages you are referring to. Thanks

![Screenshot from 2020-08-20 14-23-55](https://user-images.githubusercontent.com/2900574/90764312-d1510e00-e2f0-11ea-99e4-98ac218cf3ec.png)

**Comment by tmancey** [comment]
@vporton Rewards will only appear on this screen once paid out. You can see the next payout date and estimated pending rewards for the current period by visiting brave://rewards

**Comment by vporton** [comment]
> @vporton Rewards will only appear on this screen once paid out. You can see the next payout date and estimated pending rewards for the current period by visiting brave://rewards. Thank you, Terry

No, brave://rewards shows the same (stalled) number. One more screenshot:
![Screenshot from 2020-08-20 16-11-09](https://user-images.githubusercontent.com/2900574/90774266-dec1c480-e2ff-11ea-823d-8a06b56d14e4.png)

**Comment by vporton** [comment]
Maybe it happened after I used my own affiliate link to install it on an Android phone, too?

In my understanding of the rules, I didn't violate them. The rules say that each device provides a separate affiliate payment. So why would it be a violation to provide an affiliate link for my own other device?

If I violated the rules, please point it to me and release the lock of funds. If I violated, that was not intentional.

**Comment by tmancey** [comment]
@vporton There is a known issue for some users which will resolve itself over the next few days. If you do not receive any ads by Monday could you please let me know.
