### ISSUE TITLE
Disable rewards logs and remove existing ones

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11260]
We should stop logging rewards and ads logs into file on the disk. We should also remove all existing logs that are there. Let's add a flag to rewards flag to enable logging, so that internal people can still enable them and audit them

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, this should be available to test in 1.13.78 and above.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.13.81 x64 build
- Verified clicking on the refresh button in `brave://rewards-internals` doesn't populate any logs in the view field
- Verified clicking on `Download full log` button does nothing. No file is downloaded
-------------
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build
- Verified clicking on the refresh button in `brave://rewards-internals` doesn't populate any logs in the view field
- Verified clicking on `Download full log` button does nothing. No file is downloaded
