### ISSUE TITLE
[Desktop][CW] MM import warn message is not shown on restore wallet page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11274]
## Description 

MM import warn message is not shown on restore wallet page

## Steps to Reproduce

   1. Sideload component
   2. Click on restore
   3. MM seed words note is not shown

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/90413367-4250b580-e0a6-11ea-8638-9e1376c0fd09.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/90413332-395fe400-e0a6-11ea-8946-4b64bf16b1ee.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.13.69 Chromium: 84.0.4147.125 (Official Build) beta (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Linux
Component | MM v8 rebase

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by nhutran1201** [comment]
d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.13.69 Chromium: 84.0.4147.125 (Official Build) beta (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Linux
Component | MM v8 rebase 

- Verified MM import warn message is shown on restore wallet page
![image](https://user-images.githubusercontent.com/17010094/90499476-847b0500-e141-11ea-9897-f50882cb04d0.png)

**Comment by srirambv** [comment]
Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
-- | --
Revision | `c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)
Component | `0.1.68`

- Verified MM import warn message is shown on the restore wallet page
![image](https://user-images.githubusercontent.com/17010094/90752250-0f3d3a80-e2cf-11ea-8b4a-55af4f5ffbe1.png)

-----------------------------

Verification passed on 

Brave | 1.13.75 Chromium: 85.0.4183.69 (Official Build) beta (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux
Component | `0.1.68`

- Verified MM import warn message is shown on the restore wallet page
![image](https://user-images.githubusercontent.com/17010094/90751971-b79ecf00-e2ce-11ea-89fb-1ac02dac2d6b.png)
Verification passed on 
-----------------------------

Verification passed on 


Brave | 1.14.55 Chromium: 85.0.4183.69 (Official Build) nightly (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | macOS Version 10.15.5 (Build 19F101)
Component | `0.1.68`

- Verified MM import warn message is shown on the restore wallet page
![image](https://user-images.githubusercontent.com/17010094/90752233-0b111d00-e2cf-11ea-9f9a-49873bc142a4.png)

**Comment by srirambv** [comment]
Fixed via https://github.com/brave/ethereum-remote-client/commit/b6a9d98f2918d1576d67861ee5dd500483ee6f12
