### ISSUE TITLE
Move rewards database into bat-native-ledger

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#11273]
We should follow the lead of `bat-native-ads` and move the rewards database into `bat-native-ledger`. This will enable us to write integration tests against the ledger library without having to use the browser. In turn, this will enable us to:

- Scale up the number of tests we can write without slowing down test runs.
- Write integration and unit tests tests that don't rely on UI implementation details (e.g. DOM element attributes).

**Comment by zenparsing** [comment]
@NejcZdovc In order to avoid public header dependencies on `sql` and the associated `gn check` issues, what do you think about exporting a pure virtual class, along with a `CreateInstance` method similar to how we expose ledger?

```cpp
class LEDGER_EXPORT LedgerDatabase {
 public:
  virtual RunTransaction(...) = 0;
  static LedgerDatabase* CreateInstance(const std::string& path);
};

LedgerDatabase* LedgerDatabase::CreateInstance(const std::string& path) {
  return new LedgerDatabaseImpl(path);
}

class LedgerDatabaseImpl : public LedgerDatabase {
  // ...
};
```

**Comment by NejcZdovc** [comment]
@zenparsing sounds good
