### ISSUE TITLE
Uphold balance, inconsistent or confusing compared to verified wallet balance

### ISSUE THREAD

**Issue by coinzdude** [brave/brave-browser#11275]
## Description 
Uphold balance displays a particular USD balance, with no details about $BAT balance or contribution activity, yet the price does fluctuate based on $BATUSD.  However, more confusing is that a desktop browser wallet which is verified and tied to the same uphold account displays a much different, smaller, USD balance. 

Are the verified browser wallet and uphold wallet showing different "account/wallet" balances?  Or, are these separate balances?   Can these be merged?

![image](https://user-images.githubusercontent.com/58857646/90413985-33094200-e07d-11ea-98a2-b9b6e0d033aa.png)
and below show different balances but are verified to the same uphold
![image](https://user-images.githubusercontent.com/58857646/90414189-7499ed00-e07d-11ea-9439-e416ee8b537e.png)

**Comment by eljuno** [comment]
You should only look the balance on your `Brave Browser` card.
