### ISSUE TITLE
[Desktop] Estimated pending rewards and Ad notification count is zero even when ads is shown

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11277]
## Description 

Estimated pending rewards and Ad notification count is zero even when ads is shown. Please note this is not arising when proper ads cmd line flags are used. This issue reproducible only when I launch the browser using rewards flags

Note : If I launch browser using `brave.exe --args --enable-logging --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6 --brave-ads-staging --rewards=staging=true` and view an ads. Ads panel stats are updated properly.

## Steps to Reproduce

   1. Clean profile 1.14.x launch with staging flag `brave.exe --args --enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/bat-native-ledger/*"=6 --rewards=staging=true,reconcile-interval=3,short-retries=true`
   2. Enable rewards
   3. Visit brave.com and view an Ad
   4. Estimated pending rewards and Ad notification count is zero even when ads is shown
   5. Refresh the brave://rewards page, ads history is shown

**Note**: Please note this is not arising when proper ads cmd line flags are used. This issue reproducible only when I launch the browser using rewards cmd line flags and view an ad.

## Actual result:

Estimated pending rewards and Ad notification count is zero even when ads is shown

CR - 84
![image](https://user-images.githubusercontent.com/38657976/90419252-f157b600-e0d3-11ea-841e-cb1803c8b16a.png)

CR - 85
![image](https://user-images.githubusercontent.com/38657976/90419270-f74d9700-e0d3-11ea-8a83-905170fb8ab9.png)

## Expected result:

Estimated pending rewards and Ad notification count should not be zero when ads is shown

## Reproduces how often: 

The issue is reproducible once in 1.12.x. The issue is consistently reproducible in 1.14.x

## Brave version (brave://version info)

Brave | 1.14.44 Chromium: 85.0.4183.69 (Official Build) nightly (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey 

@tmancey Please let me know if you need logs I have saved the logs. I can share in DM.
The issue is reproducible once in 1.12.x. issue is consistently reproducible in 1.14.x

**Comment by tmancey** [comment]
Closing as won't fix as `--brave-ads-staging` must be passed to match ledger, otherwise ads will not work as expected

**Comment by rounakbhowmick** [comment]
Same issue, it's showing pending

**Comment by tmancey** [comment]
> Same issue, it's showing pending

This is a different issue and not related, could you please raise a new issue or also see my email reply to you.

Thanks
