### ISSUE TITLE
Plugins FP blocking not working correctly when FP set to Standard

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11278]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/9435

When testing on our QA test pages for FP farbling, I noticed that if FP is set to Standard, "Plugins" does not appear to be working correctly. Note, if you set FP to Strict, this is working as expected.

This does not occur in 1.12.x, but does occur in 1.13.x and 1.14.x

Per discussion with @pes10k logging this and tagging @pilgrim-brave to hopefully take a look.

## Steps to Reproduce

   1. Clean profile 1.13.x, do not adjust shields
   2. Navigate to https://dev-pages.bravesoftware.com/farbling.html (and/or https://dev-pages.brave.software/farbling.html)
3. Generate Fingerprints
4. Look at the line for Plugins

## Actual result:
`This Page` and `Remote Frame` values are the same, but `Local Frame` value is different.
<img width="1198" alt="1 13 x - initial check - default shields" src="https://user-images.githubusercontent.com/28145373/90428536-23e0bf00-e092-11ea-8439-34edd82b7cad.png">

## Expected result:
All three, `This Page`, `Local Frame`, and `Remote Frame`, should the the same on the Plugins line on a given page (but these values should be different between the two pages) as they do in 1.12.x:
<img width="1207" alt="1 12 x - plugins" src="https://user-images.githubusercontent.com/28145373/90428531-217e6500-e092-11ea-89ad-5670dde281f5.png">

When retesting, confirm Strict setting in shields still works as expected.

## Reproduces how often: 

easily

## Desktop Brave version:

Brave | 1.13.73 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not reproduce on 1.12.x
- Can you reproduce this issue with the beta channel? yes, 1.13.x
- Can you reproduce this issue with the nightly channel? yes 1.14.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @pes10k @brave/legacy_qa @rebron 

Note - tagged as `OS/Android` since original issue was also tagged as Android, please remove if this does not apply.

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 1.13.77

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.15.56 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Windows 10 OS Version 1903 (Build 18362.1016)


```
- Verified the STR from the description and ensured that the Plugin value is the same for `This Page`, `Local Frame`, and `Remote` Frame

https://dev-pages.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/38657976/93616387-4e57cc00-f9f2-11ea-8b60-1839e2e3acda.png) | ![image](https://user-images.githubusercontent.com/38657976/93616418-5a438e00-f9f2-11ea-8ffe-516bc05f27a5.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.15.54 x64 beta build
- Verified plugins value is the same on both the pages with FP set to block all and block cross-site fingerpriting

https://dev-pages.bravesoftware.com/farbling.html (Block cross-site) | https://dev-pages.bravesoftware.com/farbling.html (Block all) | https://dev-pages.brave.software/farbling.html (Block cross-site) | https://dev-pages.brave.software/farbling.html (Block all)
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/93857917-41b5cb00-fcb3-11ea-8de7-fab313745642.png) | ![image](https://user-images.githubusercontent.com/17010094/93857906-3cf11700-fcb3-11ea-82be-86ccf59123ab.png) | ![image](https://user-images.githubusercontent.com/17010094/93857988-60b45d00-fcb3-11ea-87de-62886047cf28.png) | ![image](https://user-images.githubusercontent.com/17010094/93857998-66aa3e00-fcb3-11ea-9918-381ef3a79a25.png)
