### ISSUE TITLE
[Desktop] Payment server url handling

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11284]
Ref: #10987

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.15.56 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
Revision	ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6479

<details>
<summary>Using VG (UGP grant on staging), confirmed able to do 1 time tips, recurring tips, and AC</summary>

<img width="405" alt="VG1" src="https://user-images.githubusercontent.com/28145373/93908587-d2e56b80-fccc-11ea-83a8-85158817ef44.png">
<img width="950" alt="VG2" src="https://user-images.githubusercontent.com/28145373/93908592-d4169880-fccc-11ea-8fda-7b46147f1723.png">
<img width="943" alt="VG3" src="https://user-images.githubusercontent.com/28145373/93908594-d547c580-fccc-11ea-81f0-7449feeff5ae.png">
<img width="955" alt="VG4" src="https://user-images.githubusercontent.com/28145373/93908599-d5e05c00-fccc-11ea-837d-dd12265a5f6e.png">
<img width="937" alt="VG5" src="https://user-images.githubusercontent.com/28145373/93908602-d7aa1f80-fccc-11ea-84c6-c9c3ec0f3030.png">


</details>

<details>
<summary>Confirmed brave://rewards-internals showed data from above VG contributions (1 time tips, recurring tips, AC) as expected</summary>

<img width="1193" alt="VG6" src="https://user-images.githubusercontent.com/28145373/93908620-dda00080-fccc-11ea-904b-bb44de51c625.png">

</details>

<details>
<summary>Using restored anon deposited wallet (staging env), confirmed able to do 1 time tips, recurring tips, and AC</summary>

<img width="409" alt="anon1" src="https://user-images.githubusercontent.com/28145373/93908633-e1338780-fccc-11ea-89e7-e57530f85bb1.png">
<img width="947" alt="anon2" src="https://user-images.githubusercontent.com/28145373/93908640-e395e180-fccc-11ea-8906-99f6ad5e3fc4.png">
<img width="943" alt="anon3" src="https://user-images.githubusercontent.com/28145373/93908643-e42e7800-fccc-11ea-8eae-3e6f493512c6.png">
<img width="942" alt="anon4" src="https://user-images.githubusercontent.com/28145373/93908649-e4c70e80-fccc-11ea-80ba-004da8928f88.png">
<img width="943" alt="anon5" src="https://user-images.githubusercontent.com/28145373/93908652-e5f83b80-fccc-11ea-84be-aa2878b61623.png">

</details>

<details>
<summary>Confirmed brave://rewards-internals showed data from above anon wallet contributions (1 time tips, recurring tips, AC) as expected</summary>

<img width="1043" alt="anon6" src="https://user-images.githubusercontent.com/28145373/93908661-e98bc280-fccc-11ea-974e-7b279e36866a.png">

</details>

<details>
<summary>Using KYC'd Uphold wallet (staging env), confirmed able to do 1 time tips, recurring tips, and AC</summary>

<img width="412" alt="Uphold1" src="https://user-images.githubusercontent.com/28145373/93908673-ed1f4980-fccc-11ea-80ad-a8fa5c7c2054.png">
<img width="947" alt="Uphold2" src="https://user-images.githubusercontent.com/28145373/93908678-ee507680-fccc-11ea-94cb-6412054abfbe.png">
<img width="949" alt="Uphold3" src="https://user-images.githubusercontent.com/28145373/93908681-ef81a380-fccc-11ea-89b3-c00e4f23be66.png">
<img width="946" alt="Uphold4" src="https://user-images.githubusercontent.com/28145373/93908685-f01a3a00-fccc-11ea-8cb6-895abcfe7d61.png">
<img width="944" alt="Uphold5" src="https://user-images.githubusercontent.com/28145373/93908689-f14b6700-fccc-11ea-8c3f-c55fca9809ba.png">

</details>

<details>
<summary>Confirmed brave://rewards-internals showed data from above Uphold contributions (1 time tips, recurring tips, AC) as expected</summary>

<img width="1000" alt="Uphold6" src="https://user-images.githubusercontent.com/28145373/93908699-f4465780-fccc-11ea-8bad-540c845be6a9.png">

</details>

-------------
