### ISSUE TITLE
Pixel artifacts on web and browser elements

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#1128]
## Description 
If you look at certain web elements and UI elements, there are random white or black pixels drawn on the elements. This problem is found on macOS 10.13.6. This problem is found on a fresh profile. Seems like it started happening a few days ago (Brave 0.55.3 or Chromium 70.0.3538.12 maybe).

## Steps to Reproduce
   1. Go to any website.
   2. Click the Brave shields button.

## Actual result:
There are random white pixels on the UI switches:
![image](https://user-images.githubusercontent.com/19424103/45563509-2cc81680-b813-11e8-9679-0d9a2e40925e.png)

## Expected result:
There should not be any random white pixels.

## Reproduces how often: 
Almost all the time.

## Brave version (chrome://version info)
Brave | 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)
Revision | ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS | Mac OS X
JavaScript | V8 7.0.276.6
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.12 Safari/537.36

### Reproducible on current release:
I haven't tried.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? I haven't tried.

### Additional Information
More examples:
Search field and GitHub issue tags:
![](https://user-images.githubusercontent.com/19424103/45563629-8c262680-b813-11e8-98e5-0a0a4bef2c71.png)
GitHub issue tags:
![](https://user-images.githubusercontent.com/19424103/45563654-a3fdaa80-b813-11e8-8600-2fa4dafa85e2.png)
Text field selected text:
![](https://user-images.githubusercontent.com/19424103/45563667-ad871280-b813-11e8-9b72-26428b0966b8.png)

**Comment by Liunkae** [comment]
Thanks to https://github.com/brave/brave-browser/issues/1160#issuecomment-423028344 by @kevinschaich for finding the root problem: turning off hardware acceleration also resolves this issue.
![](https://user-images.githubusercontent.com/19424103/45833515-6b097e00-bcca-11e8-8741-3aad21eb59ea.png)

**Comment by Liunkae** [comment]
Fixed with brave/brave-core#531

**Comment by bsclifton** [comment]
Updated milestone since this was fixed with above PR (which landed in 0.55.x) 😄

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

* Ensured that HW Acceleration was still enabled by default
* Visited about a dozen websites and clicked on the shield, ensured there's no pixel artifacts
* Searched a large list of GH issues and didn't see any pixel artifacts
* Edited several GH issues and didn't see any pixel artifacts in the edit box

@LaurenWags when you have some time, could you go through a quick check and make sure you're not seeing the pixel artifacts anymore? Once you do a quick check, you can label it as `QA Pass-macOS`.
