### ISSUE TITLE
[Desktop] Cartridges on TIC-80 website don't have visuals

### ISSUE THREAD

**Issue by dentistformyeye** [brave/brave-browser#11281]
## Description 

TIC-80 is a fantasy console. [The website](https://tic80.com) has cartridges, applications that play in the browser. After starting a cartridge in Brave Browser, there are no graphics but sounds still play and keyboard controls (if applicable) still perform actions.

## Steps to Reproduce

   1. Go to a cartridge on https://tic80.com, such as [this one](https://tic80.com/play?cart=708).
   2. Ensure that your device's volume is on. Open the console in developer tools.
   3. Start the cartridge and play the demo or game.

## Actual result:

As expected, the page shows a preview of the cartridge after step 1.
![image](https://user-images.githubusercontent.com/51429646/93923252-1ea21000-fce1-11ea-9ddd-22b5ea6d06af.png)

The console shows these errors after step 2.
![image](https://user-images.githubusercontent.com/51429646/90464579-a17ced00-e0db-11ea-8f1f-7d05e8c010a7.png)

After step 3, the TIC-80 start-up chime plays as expected. If the cartridge has other sounds, then sounds play as expected.
![image](https://user-images.githubusercontent.com/51429646/93923029-c8cd6800-fce0-11ea-9048-17bdb1d536de.png)

However, the cartridge stays black during and after the TIC-80 start-up sequence. 
Meanwhile, the following shows up in the console.
![image](https://user-images.githubusercontent.com/51429646/93922600-24e3bc80-fce0-11ea-8f61-11baaf1a8e01.png)

## Expected result:
The cartridge should have graphics and the console shouldn't display errors or warnings.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.15.6 (Build 19G73)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Haven't tried
- Can you reproduce this issue with the beta channel? Don't know
- Can you reproduce this issue with the nightly channel? Don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Brave Rewards was not active.
- Is the issue reproducible on the latest version of Chrome? Don't know

## Miscellaneous Information:

Disregarding step 2, this issue didn't reproduce on Brave version 1.12.113 on my Android device whether or not I use the mobile version or desktop version of the site.

**Comment by rebron** [comment]
@dentistformyeye Can you try this again with the latest 1.14.81? 

We need clearer steps on what you're trying to do. We see the errors in dev console but we have no clue what you mean after that, specifically step 3. to click the embed to start the cartridge. Did you mean to play the game?

**Comment by dentistformyeye** [comment]
My bad, changing the fingerprinting shield from strict to standard resolves the issue. The problem had been my script blocker. However, my script blocker, the devtools console, and the devtools network tab all gave no indication of something being blocked.
