### ISSUE TITLE
[Desktop] user funds do not move to Uphold - follow up to 8428

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11298]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/8428 and https://github.com/brave/brave-core/pull/6000

If you have anon user funds and you connect a KYC'd uphold wallet, the user funds do not move to Uphold.

## Steps to Reproduce

Test plan 4 from https://github.com/brave/brave-core/pull/6000

- enable rewards
- restore wallet with user funds
- connect kyc uphold account
- make sure that funds are transferred 

## Actual result:

Funds not moved. See below in the logs.
```
[ RESPONSE - OnTransferFunds ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/redacted/claim
> Result: Failure
> HTTP Code: 403
> Body: {"message":"error linking wallet: failed to verify transaction: failed to verify transaction","code":403}
```

## Expected result:
funds should move 

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.13.76 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @rebron @brave/legacy_qa

**Comment by LaurenWags** [comment]
I did not add `OS/Android` label as Android didn't have the ability for users to add their own funds. Please add label if this needs to be checked there as well. cc @srirambv

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.13.x` Verified that ad grants are not moved to KYC'd uphold wallet

**Comment by LaurenWags** [comment]
uplift approved, waiting on new 1.13.x build to test

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
**Scenario 1:**
- Verified the STR from the description
- Restored a wallet with user funds
![image](https://user-images.githubusercontent.com/38657976/91331061-eabdf280-e7e7-11ea-8fef-5540f290067b.png)
- Verified wallet status is `Not connected` and `Deposited balance` is shown correctly in brave://rewards-internals
![image](https://user-images.githubusercontent.com/38657976/91331198-180aa080-e7e8-11ea-9fe1-395474b6553a.png)
- Connected KYC'd uphold wallet and confirm funds are transferred to uphold card
![image](https://user-images.githubusercontent.com/38657976/91331563-84859f80-e7e8-11ea-8b47-01dd43726136.png)
![image](https://user-images.githubusercontent.com/38657976/91331504-759eed00-e7e8-11ea-8e5b-7dbcbe5fe4b7.png)
- Confirmed seeing the below in logs
```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/redacted/claim
> Method: UrlMethod::POST
> Content: ..
```
```
[ RESPONSE - OnTransferFunds ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/redacted/claim
> Result: Success
> HTTP Code: 200
```

**Comment by LaurenWags** [comment]
Additional scenario verified (not listed in test plan from PR) using

```
Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Confirmed claim process including getting KYC'd with Uphold.

1. Claim an Ad grant on staging env:
<img width="399" alt="claim ad grant" src="https://user-images.githubusercontent.com/28145373/91337813-f4bd0280-e7a1-11ea-92a1-46ee6464dbf4.png">
<img width="215" alt="wallet balance" src="https://user-images.githubusercontent.com/28145373/91337819-f71f5c80-e7a1-11ea-949b-d48691fe278f.png">

2. Click Verify Wallet, follow prompts and provide all expected data to Uphold

3. Contacted Uphold to get KYC completed

4. Confirmed browser got KYC notice:
<img width="416" alt="acct is KYCd" src="https://user-images.githubusercontent.com/28145373/91337826-fab2e380-e7a1-11ea-8d60-abe05eec7a4b.png">

5. Confirmed Ad grant moved to Uphold account:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/........./claim
> Method: UrlMethod::POST
> Content: ........
[10503:775:0826/132157.823391:VERBOSE6:wallet_claim.cc(163)] 
[ RESPONSE - OnTransferFunds ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/........./claim
> Result: Success
> HTTP Code: 200
> Body: null
```

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v1/suggestions/claim
> Method: UrlMethod::POST
> Content: .........
[ RESPONSE - OnRedeemTokens ]
> Url: https://grant.rewards.bravesoftware.com/v1/suggestions/claim
> Result: Success
> HTTP Code: 200
> Body: 
```

<img width="403" alt="acct is KYCd2" src="https://user-images.githubusercontent.com/28145373/91337838-ff779780-e7a1-11ea-9893-d56fac23eee3.png">
<img width="1005" alt="ad grant moves to uphold2" src="https://user-images.githubusercontent.com/28145373/91337843-01d9f180-e7a2-11ea-8f17-53b8b6ed6626.png">
<img width="426" alt="ad grant moves to uphold1" src="https://user-images.githubusercontent.com/28145373/91337913-14ecc180-e7a2-11ea-8fe3-e0560ffb7e2e.png">
