### ISSUE TITLE
[Android] Tab switcher bar is absent on tablet

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#11297]
## Description 
![device-2020-08-18-103316](https://user-images.githubusercontent.com/30602739/90526398-5ba54080-e13e-11ea-929f-8eac30fb0dc7.png)

## Steps to reproduce 

   1. Just run app on tablet

## Actual result 
See picture

## Expected result
Tab switcher bar is visible

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? no
- Can you reproduce this issue with the current Play Store Beta version? no
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.14.50

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@samartnik it seems to be similar to https://github.com/brave/brave-browser/issues/11226

**Comment by samartnik** [comment]
dublicate
