### ISSUE TITLE
[Desktop][CW] Overlay shown after re-logging into account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11290]
## Description 

Overlay shown after re-logging into account

## Steps to Reproduce

   1. Side load component
   2. Create an account or restore an account
   3. Lock account from menu
   4. Login again shows an overlay with a horizontal bar. Reloading the page removes the overlay

## Actual result:

![ethoverlay](https://user-images.githubusercontent.com/17010094/90500637-133c5180-e143-11ea-9ed5-f87710b24167.gif)

## Expected result:
No overlay

## Reproduces how often: 

Easy

## Brave version (brave://version info)

MM v8 rebase component

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Found while testing #11269

**Comment by fakeharahman** [comment]
Hi! I'm new to open source, can I try to solve this issue?

**Comment by ryanml** [comment]
Hi @fakeharahman - thanks for getting in touch. This is currently an issue as part of a larger rebase I am doing for our Crypto Wallets extension, set to go out this week. Why don't you touch base next week on any `feature/crypto-wallets` issues you still see posted and I can help you get started :)

**Comment by fakeharahman** [comment]
Thanks for your response @ryanml! I will be sure to contact you next week.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
-- | --
Revision | `c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)
Component | `0.1.67`

- Verified no overlay is shown when unlocking the account
-----------------------------

Verification passed on 

Brave | 1.13.75 Chromium: 85.0.4183.69 (Official Build) beta (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux
Component | `0.1.67`

- Verified no overlay is shown when unlocking the account
-----------------------------

Verification passed on 


Brave | 1.14.55 Chromium: 85.0.4183.69 (Official Build) nightly (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | macOS Version 10.15.5 (Build 19F101)
Component | `0.1.67`

- Verified no overlay is shown when unlocking the account

**Comment by srirambv** [comment]
Fixed via https://github.com/brave/ethereum-remote-client/commit/b6a9d98f2918d1576d67861ee5dd500483ee6f12
