### ISSUE TITLE
[Android] Brave rewards seems to have reset

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11300]
## Description

I've had Brave release channel installed for a long time, ads disabled, today I had a ? icon on my BAT icon.

## Steps to reproduce 

These steps likely won't reproduce for everyone, I'm just telling the steps I took

   1. Click on the (?) BAT icon
   2. Onboarding came up (which it shouldn't have)
   3. I clicked out of it
   4. I went back into it, it had a Join button on Brave rewards

## Actual result 

It seems my Brave rewards wallet was reset 

## Expected result

No reset should happen

## Issue reproduces how often 

Probably not very often? Not sure, but it happened for me.

## Version/Channel Information:
1.12.113

- Can you reproduce this issue with the current Play Store version?  yes
- Can you reproduce this issue with the current Play Store Beta version? n/a 
- Can you reproduce this issue with the current Play Store Nightly version? n/a

## Device details
Pixel3

**Comment by bhavik2936** [comment]
Same happened to me today on Samsung M31

It said around 5 BAT in browser. Since less than 25 BAT it wasn't linked to uphold account.

**Comment by bhavik2936** [comment]
The device was not restarted nor cleared cache of browser.
