### ISSUE TITLE
[Desktop] both "Copy Magnet Link/.torrent file" buttons are not being rendered correctly once clicked

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11302]
## Description 

Whenever you click on either `Copy Magnet Link` or `Copy .torrent file` via WebTorrent, the buttons are not rendered correctly and don't display the entire border. However, clicking in anywhere on the page fixes the button.

## Steps to Reproduce

   1. load https://webtorrent.io/torrents/big-buck-bunny.torrent
   2. click on the `Save .torrent File` (notice the button is incorrectly displayed)
   3. click `Cancel` on the OS modal (so you don't save the torrent)
   4. click anywhere on the page and the button will be displayed correctly

The above also reproduces using `magnet` links as per the following:

```
magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent
```

## Actual result:

<img width="1247" alt="Screen Shot 2020-07-13 at 9 27 57 PM" src="https://user-images.githubusercontent.com/2602313/90557359-5a890900-e168-11ea-9492-ac741d1f0db5.png">

<img width="1662" alt="Screen Shot 2020-08-18 at 2 38 14 PM" src="https://user-images.githubusercontent.com/2602313/90557361-5bba3600-e168-11ea-9dd3-5295e302700a.png">

## Expected result:

<img width="1689" alt="Screen Shot 2020-08-18 at 3 23 43 PM" src="https://user-images.githubusercontent.com/2602313/90556859-8fe12700-e167-11ea-823b-1cce034a1b34.png">

<img width="1715" alt="Screen Shot 2020-08-18 at 3 23 49 PM" src="https://user-images.githubusercontent.com/2602313/90556853-8eaffa00-e167-11ea-8b64-062250528102.png">

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.14.48 Chromium: 85.0.4183.69 (Official Build) nightly (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.15.6 (Build 19G73)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by rebron** [comment]
cc: @yrliou @petemill

**Comment by diracdeltas** [comment]
it seems this has been fixed now, at least i couldn't repro

**Comment by diracdeltas** [comment]
nvm, was able to repro once i clicked on start torrent

**Comment by stephendonner** [comment]
Duping to the issue where @fallaciousreasoning attached his fix: https://github.com/brave/brave-browser/issues/24552.
