### ISSUE TITLE
[Android] No reaction on a sample ad notification after onboarding

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#11306]
## Description 
No reaction on a sample ad notification after onboarding in certain cases

## Steps to reproduce 

   1. Clean install.
   2. Finish all onboarding with enabling rewards at the end.
   3. Hit back button twice(first click closes the panel, second closes the browser).
   4. Click on sample ad notification.

## Actual result 
Nothing happens.

## Expected result
Browser opens and shows a panel.

## Issue reproduces how often 
Always.

## Version/Channel Information:

1.13.x and higher

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
- Verified steps from issue description
- Verified clicking on sample ad notification launches brave and focuses on rewards panel
-------------
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
- Verified steps from issue description
- Verified clicking on sample ad notification launches brave and focuses on rewards panel
