### ISSUE TITLE
[Android] Weird build error on arm64 and x86_64 with rust

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#11305]
STR
`npm run build -- Release  --target_os=android --target_arch=arm64 --target_apk_base=mono`

failed CI at https://ci.brave.com/job/brave-browser-build-android/265/execution/node/322/log/

errors are different one of the 
```
ojects/br_br_android/brave-browser/src/out/android_Release_arm64'
[2/11714] ACTION //brave/build/rust:rust_lib_cargo_build(//build/toolchain/android:android_clang_arm)
FAILED: brave_rust/out/arm-linux-androideabi/release/libbrave_rust.a 
python ../../brave/script/cargo.py --rustup_path=../../brave/build/rustup/ --cargo_path=../../brave/build/rustup/ --manifest_path=../../brave/build/rust/Cargo.toml --build_path=brave_rust/out --target=arm-linux-androideabi --toolchain=arm --is_debug=false --rust_flags=
error: could not remove build directory
Caused by:
  failed to remove file `/mnt/EVO970/Projects/br_br_android/brave-browser/src/out/android_Release_arm64/brave_rust/out/aarch64-linux-android/release/deps/object-48f1ea885030818f.d`
Caused by:
  No such file or directory (os error 2)

```

**Comment by bridiver** [comment]
failed again with ```01:41:10     Compiling adblock v0.2.11
01:41:10     Compiling adblock v0.3.0 (https://github.com/brave/adblock-rust?rev=96627d0a12a65effb2a45e9f16ae8d89416bfacd#96627d0a)
01:41:10  error: failed to build archive: No such file or directory
01:41:10  
01:41:10  error: could not compile `psl`.```
