### ISSUE TITLE
Upgrade from Chromium 84.0.4147.125 to Chromium 84.0.4147.135 (1.12.x).

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#11303]
Minor Chromium bump.

https://chromium.googlesource.com/chromium/src/+log/84.0.4147.125..84.0.4147.135?pretty=fuller&n=10000

QA tests:

Check branding items
Check for version bump

No specific code changes in Brave (only line number changes in patches).

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Mint 19.1 x64` using the following build:

```
Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
--- | ---
Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
OS | Linux
```

![Screenshot from 2020-08-19 02-47-02](https://user-images.githubusercontent.com/2602313/90604745-517d5380-e1cb-11ea-8438-a9529af38112.png)
