### ISSUE TITLE
Crypto Wallets MetaMask V8 Upgrade

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#11311]
This is the tracking issue for the MetaMask version 8 rebase. The following issues will be resolved:

- [ ] https://github.com/brave/brave-browser/issues/11294
- [ ] https://github.com/brave/brave-browser/issues/11292
- [ ] https://github.com/brave/brave-browser/issues/11290
- [ ] https://github.com/brave/brave-browser/issues/11274
- [ ] https://github.com/brave/brave-browser/issues/11272
- [ ] https://github.com/brave/brave-browser/issues/11269
- [ ] https://github.com/brave/brave-browser/issues/11267
- [ ] https://github.com/brave/brave-browser/issues/11264
- [ ] https://github.com/brave/brave-browser/issues/11263
- [ ] https://github.com/brave/brave-browser/issues/11262
- [ ] https://github.com/brave/brave-browser/issues/10766
- [ ] https://github.com/brave/brave-browser/issues/8176
- [ ] https://github.com/brave/brave-browser/issues/11329
- [ ] https://github.com/brave/brave-browser/issues/11327
- [ ] https://github.com/brave/brave-browser/issues/11339

cc: @srirambv

**Comment by srirambv** [comment]
Closing as most of the issues are verified. Newer issues can be added to the list as and when fixed

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
-- | --
Revision | `c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)
Component | `0.1.72`

- Verified all the listed issues on the above build

-----------------------------

Verification passed on 

Brave | 1.13.78 Chromium: 85.0.4183.69 (Official Build) beta (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux
Component | `0.1.72`

- Verified all the listed issues on the above build

-----------------------------

Verification passed on 


Brave | 1.15.4 Chromium: 85.0.4183.78 (Official Build) nightly (64-bit)
-- | --
Revision | `720ec01a54ea94d2d8b7a1d273e0fa89722fb11b-refs/branch-heads/4183@{#1603}`
OS | macOS Version 10.15.5 (Build 19F101)
Component | `0.1.72`

- Verified all the listed issues on the above build
