### ISSUE TITLE
Stop modifying WebRTC Web APIs when fingerprinting protection=strict

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#11310]
Right now, if you set fingerprinting protections to strict, the following JS APIs are removed or rendered useless:

- https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer
- https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createAnswer
- https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setLocalDescription
- https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setRemoteDescription

These APIs are not fingerprinting related; this implementation is largely because Brave used to use the fingerprinting setting to control a number of non-fp related things too (to avoid jamming up the shields UI).

We should stop modifying these methods based on fingerprinting setting, and rely on the global WebRTC setting to control the privacy properties of these methods

**Comment by cjwijtmans** [comment]
Are you sure? https://browserleaks.com/webrtc

**Comment by pes10k** [comment]
@cjwijtmans sorry, im not sure I follow your question. Can you try rephrasing?

**Comment by cjwijtmans** [comment]
Because its clear webrtc is used in multiple ways to fingerprint. I was actually surprised on android brave browser it was able to pull up wan and lan ip adress which will work even on vpn.

**Comment by pes10k** [comment]
Sure, understood.  I'm not following the connection to this issue though.  This issue is specifically not about getting IP information from the WebRTC system (which is already controlled through a global shields setting).  This is about whether you can get fingerprinting information through these methods _unrelated to ip addresses_.

**Comment by cjwijtmans** [comment]
Predicted your response, anyway. All i said is that currently even the wan and lan information can be used for some basic fingerprinting making VPNs useless. Are you completely ignoring device id enumaration? There is a reason webrtc is rendered useless, its a huge privacy leak. Do you even know what are you talking about? No wonder random privacy filters and fingerprinting plugins are doing a better job than brave currently.

**Comment by pes10k** [comment]
These comments are not related to the issue here, so I will not respond further.

For anyone else who comes across this, device enumeration fingerprinting is being handled in https://github.com/brave/brave-browser/issues/8666.  WAN and LAN IP information is already handled through other shields settings. This issue is not related to either of those topics.

**Comment by pes10k** [comment]
For a QA plan, all thats needed is to go to https://browserleaks.com/webrtc and make sure that you see the public (not local) IP when fingerprinting = strict

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.14.67 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-browser/issues/11310#issuecomment-675860214

----------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.14.82 x64 RC build
- Verified test plan from https://github.com/brave/brave-browser/issues/11310#issuecomment-675860214
