### ISSUE TITLE
[Android] Shields onboarding is not dismissed when a new tab is opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11318]
## Description 
Shields onboarding is not dismissed when a new tab is opened

## Steps to reproduce 

   1. Clean install Android build
   2. Visit a page on a new tab
   3. Wait till page finishes loading and shields onboarding is shown
   4. Click on menu and open a new tab, shields onboarding is retained, Clicking on it dismisses it

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/90591380-e3d92380-e1da-11ea-90b4-5d45cf0978c1.png)

## Expected result
Should close the modal when tapped outside it

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by deeppandya** [comment]
@karenkliu should we close the tooltip ? Because according to spec it should be closed only if user clicks on the tooltip and open the shields panel.

**Comment by karenkliu** [comment]
@deeppandya we should close it if they go to a different page (new tab, or different website). That tooltip only applies to the current page they are visiting with blocked items.

**Comment by deeppandya** [comment]
@srirambv @karenkliu I will update the code with this issue

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
- Verified shields onboarding message is not retained when a new tab is opened

------

Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
- Verified shields onboarding message is not retained when a new tab is opened
