### ISSUE TITLE
[Desktop] Enable DNS over HTTPS UI setting

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#11312]
Chromium 84 includes a user-visible DoH setting:
![download](https://user-images.githubusercontent.com/167821/90576472-3252d780-e173-11ea-91c8-80e2153758d5.jpeg)

controlled by [this feature flag](https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/chrome_features.cc;l=274-275;drc=a744f40f724c892d0353f80423e1fa3676e841b0).

**Comment by diracdeltas** [comment]
We are seeing support requests for this feature now that it's available in Chrome 85: https://twitter.com/Ginger__T/status/1313059566964400129

Is this just waiting on a design from @karenkliu?

**Comment by diracdeltas** [comment]
We probably just want to copy the Chrome UI for this in brave://settings/security > advanced:

<img width="669" alt="Screen Shot 2020-10-05 at 12 09 56 PM" src="https://user-images.githubusercontent.com/549654/95121613-2790d980-0704-11eb-9f8e-4981854da9a8.png">

**Comment by karenkliu** [comment]
let's do what @diracdeltas suggested - probably don't need a design for this one

**Comment by diracdeltas** [comment]
Seems like this has been fixed. I verified that the setting exists in 1.18 stable and that https://www.cloudflare.com/ssl/encrypted-sni/ shows that DoH is being used.

**Comment by mKoonrad** [comment]
I can confirm that it's working on Windows but not on Linux (1.18.77 Chromium: 87.0.4280.101)

**Comment by fmarier** [comment]
> I can confirm that it's working on Windows but not on Linux (1.18.77 Chromium: 87.0.4280.101)

Support for DoH in general is not yet available on Linux (in Chrome or Brave).
