### ISSUE TITLE
[Android] Bookmarks sometimes not get saved even when it appears they have been saved, neither are synced

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#11321]
## Description 
Please change method for bookmarks saving as most time they doesn't get saved and are also not synced, i lost a lot data because of that

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by jsecretan** [comment]
Hi @tathastu871 sorry to hear about this, can you ask me what devices you have in the sync chain?  Is this a desktop and Android device?

**Comment by tathastu871** [comment]
> Hi @tathastu871 sorry to hear about this, can you ask me what devices you have in the sync chain? Is this a desktop and Android device?

Its android. on pc version its not a problem and bookmarks

**Comment by jsecretan** [comment]
So @tathastu871 just to confirm, which version of the Android browser are you on?

**Comment by tathastu871** [comment]
> So @tathastu871 just to confirm, which version of the Android browser are you on?
1.12.113

**Comment by jsecretan** [comment]
Thanks @tathastu871 and when you say it happens more when you create multiple bookmarks, do you mean making them quickly one after another?  @AlexeyBarabash can you think of anything that would lead to this?

**Comment by tathastu871** [comment]
> Thanks @tathastu871 and when you say it happens more when you create multiple bookmarks, do you mean making them quickly one after another? @AlexeyBarabash can you think of anything that would lead to this?

Kind of when making multiple tabs are open and i quickly switch between tabs and add bookmarks. That may be the cause.

**Comment by bsclifton** [comment]
@srirambv can you check this? Thanks 😄

**Comment by tathastu871** [comment]
Please for god's sake make bookmarks sorted in descending order of time of creation
 Currently latest bookmark is at the bottom and i have thousands of
