### ISSUE TITLE
[Android] Text on Brave Desktop info card looks like link 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11326]
## Description 
Text on Brave Desktop info card looks like link 

## Steps to reproduce 

   1. Follow steps from https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/Mobile-onboarding-v2?node-id=697%3A5848

## Actual result 
`brave.com` on the message looks like a link. 
![image](https://user-images.githubusercontent.com/17010094/90624599-1a7d6100-e210-11ea-8590-e8fa896a0af4.png)

## Expected result
Should probably have a different colour to make it obvious that its not a link and can't be tapped

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:10
   
## Brave version
1.14.44

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by bsclifton** [comment]
Implementation matches spec. @jamesmudgett @karenkliu should anything be done to make `brave.com` not look like a link? or close as `wontfix`?

**Comment by deeppandya** [comment]
> Implementation matches spec. @jamesmudgett @karenkliu should anything be done to make `brave.com` not look like a link? or close as `wontfix`?

@bsclifton i have removed `brave.com` as link because it's not doing anything on tap. https://github.com/brave/brave-core/pull/6517

**Comment by bsclifton** [comment]
@deeppandya OK great 😄 Assigned you and put as `In progress`. When PR is merged, you can assign the milestone (1.15.x) and do the uplifts to 1.13/1.14

**Comment by karenkliu** [comment]
@deeppandya  As a reminder we talked setting `brave.com` to be the same color as the rest of the text because it's not a link over here https://github.com/brave/brave-browser/issues/10571#issuecomment-677869910

**Comment by deeppandya** [comment]
> @deeppandya  As a reminder we talked setting `brave.com` to be the same color as the rest of the text because it's not a link over here https://github.com/brave/brave-browser/issues/10571#issuecomment-677869910

@karenkliu it's done. And I have already created a PR for this. So it should be nightly soon.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83
- Verified text on cross-platform promotion doesn't look like a link 
  <img width=300 src=https://user-images.githubusercontent.com/17010094/91937582-224a0480-ecea-11ea-8816-bc54bb951c08.png>

--------------
Verification passed on OnePlus 6T with Android 10 running 1.13.83
- Verified text on cross-platform promotion doesn't look like a link 
  <img width=600 src=https://user-images.githubusercontent.com/17010094/91937556-14947f00-ecea-11ea-92d5-1d58bb2aa670.png>
