### ISSUE TITLE
[Android] Privacy report modal scale is pretty small on tablet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11322]
## Description 
Privacy report modal scale is pretty small on tablet

## Steps to reproduce 

   1. Clean install on nightly on a tablet
   2. Go through privacy report onboarding
   3. Once completed bring up a skinny privacy report modal 

## Actual result 
![skinnyprivacyreport](https://user-images.githubusercontent.com/17010094/90603915-f2800480-e1f3-11ea-939a-241043813956.gif)

## Expected result
Privacy report screen should scale on tablet.
Figma: https://www.figma.com/file/nSkt7Hz6sTU49Wtg23fBgX/Brave-Stats?node-id=201%3A3535

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.14.44

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Per @anthonypkeane  - This issue is not a blocker for 1.13. We can update this in a later release.

**Comment by bsclifton** [comment]
cc: @karenkliu for guidance on how to make this look better 😄

**Comment by anthonypkeane** [comment]
We can update this is a later release. While it doesn't look good on tablets it is functional and we can update in a later release. Not a blocker for 1.13

**Comment by deeppandya** [comment]
@karenkliu @anthonypkeane @srirambv i have updated the UI. here i have attached a recording of the implementation. 
https://slack-files.com/T04PX1BU8-F019U5K8M7X-9dd3c2b874

**Comment by srirambv** [comment]
Need to verify #11320 on tablet once this is fixed

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.13.84 x64 build
- Verified privacy report modal is scaled to device viewport 
![tabreport](https://user-images.githubusercontent.com/17010094/92098619-63691400-edd1-11ea-860f-b20ad8d7e7b3.gif)
