### ISSUE TITLE
[Android] Privacy report modal position resizes when switching between Websites and Trackers

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11320]
## Description 
 Privacy report modal jumps position when switching between Websites and Trackers

## Steps to reproduce 

   1. Clean install 1.14.44
   2. Enable privacy report via onboarding
   3. Do not visit any sites so that report has no entires
   4. Switch from websites to trackers, modal jumps from initial position even though there are no values

## Actual result 
![trackerspopup](https://user-images.githubusercontent.com/17010094/90593651-5d274500-e1e0-11ea-84cf-11394d9b5c82.gif)

## Expected result
Only resize the modal when there are entries 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.14.44

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Looks bad on Tablet 
![image](https://user-images.githubusercontent.com/17010094/90602661-062a6b80-e1f2-11ea-8964-89a337a6d5aa.png)

**Comment by deeppandya** [comment]
@srirambv I agree. I need to update the UI.

**Comment by srirambv** [comment]
Logged https://github.com/brave/brave-browser/issues/11322 as a follow up for tablet

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
- Verified privacy report modal doesn't resize when switching between websites and trackers
![statsmodal](https://user-images.githubusercontent.com/17010094/91946063-10229300-ecf7-11ea-8c98-d8fd425b6fb3.gif)

-----------

Tablet verification blocked on #11322
