### ISSUE TITLE
Better password storage in Brave

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1132]
Binaries can extract passwords stored in brave data directory. Figure out a way to prevent other binaries from extracting plaintext passwords from Brave data directories.

https://securityxploded.com/brave-password-decryptor.php

**Comment by tomlowenthal** [comment]
I don't think we can actually do much better than this — and I think that anything else would give folks a false sense of security. https://news.ycombinator.com/item?id=6166886

**Comment by bbondy** [comment]
I think https://securityxploded.com/brave-password-decryptor.php is talking about browser-laptop, and I think we aren't sure the extent of if it's a problem on brave-core.  I think we should close this for now as not actionable until something is defined that a developer can take.
