### ISSUE TITLE
[Android] Sample ad doesn't open landing page when rewards is enabled 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11323]
## Description 
Sample ad doesn't open landing page when rewards is enabled

## Steps to reproduce 

   1. Clean install nightly
   2. Enable rewards via onboarding/rewards page
   3. Finish onboarding and click on sample ad notification, doesn't load the landing page

## Actual result 
![sampleads](https://user-images.githubusercontent.com/17010094/90617209-4f84b600-e206-11ea-8f4b-4b491cecd280.gif)

## Expected result
Should load landing page

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.14.44

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by tmancey** [comment]
@SergeyZhukovsky Sample ad does not use ads lib, passing over to Android team sir

**Comment by SergeyZhukovsky** [comment]
@srirambv that's correct. We open a panel on the sample ad notification click. cc @deeppandya. Closing it.

**Comment by srirambv** [comment]
This doesn't seem fixed on 1.13.x channel. I can still see it loads the my-fist-ad page when clicking on the sample notification
![sampleadnotification](https://user-images.githubusercontent.com/17010094/91440246-3911d680-e866-11ea-953c-64da3a169e23.gif)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
- Verified clicking on ad notification opens rewards panel

---------------

Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
- Verified clicking on ad notification opens rewards panel
