### ISSUE TITLE
[Android] Implement cosmetic filtering

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#11331]
## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@SergeyZhukovsky closing it in favour of #9955. Please reopen if this is different. Since there's no info on the issue linking #9955 for tracking
