### ISSUE TITLE
[Android] Can't access brave rewards, just get spinning wheel

### ISSUE THREAD

**Issue by coinzdude** [brave/brave-browser#11349]
Stock Galaxy S9 with One UI 2.1.

Brave 1.12.113

Brave browser installed, safety check passed.  Rewards never show here, just the spinning wheel.

![image](https://user-images.githubusercontent.com/58857646/90804978-fb063700-e2e8-11ea-8dc3-844f789012cb.png)

**Comment by coinzdude** [comment]
I have since figured out that if I click "Learn More" it will load the brave rewards screen at least (chrome://rewards), so I don't know what the spinning wheel is trying to do here.

**Comment by anthonypkeane** [comment]
Invalid since BRE

**Comment by coinzdude** [comment]
Yes, this was resolved, thank you
