### ISSUE TITLE
[Android] Swipe on bottom toolbar creates a grey bar when swiped 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11346]
## Description 
Swipe on bottom toolbar creates a grey bar when swiped 

## Steps to reproduce 

   1. Install nightly build 1.14.57
   2. Open a bunch of tabs
   3. Swipe on bottom toolbar to switch between tabs
   4. Swipe action creates a grey box 

## Actual result 

Light theme | Dark Theme
-- | -- 
![bottomswipe](https://user-images.githubusercontent.com/17010094/90792524-77f1da80-e302-11ea-9cf4-916283286a2a.gif)| ![image](https://user-images.githubusercontent.com/17010094/90792487-6b6d8200-e302-11ea-91cd-fee417e06005.png)

## Expected result
Better UI

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone specific
   - Android version: 10
   
## Brave version
1.14.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Found while verifying https://github.com/brave/brave-core/pull/6457 for uplift

**Comment by anthonypkeane** [comment]
Fixed
