### ISSUE TITLE
[Desktop] update Safe Browsing text in brave://settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#11345]
## Description 
Update Safebrowsing text in brave://settings/privacy and brave://settings/safetyCheck for Chromium 86, in the "No protection section".

## Steps to Reproduce

   1. Use a build of Brave with cr86
   2. Go to brave://settings/privacy and brave://settings/safetyCheck and notice screens in Actual result.

## Actual result:
first screen - 
![image-2](https://user-images.githubusercontent.com/5951041/90791180-bfa24300-e2bd-11ea-913e-43342049f5c8.png)

second screen - 
![Screen Shot 2020-09-24 at 10 30 00 AM](https://user-images.githubusercontent.com/5951041/94179627-9c852900-fe51-11ea-8116-198c1a392656.png)

## Expected result:
first screen:
"Standard Protection" text remove:
If a site tries to steal your password, or when you download a harmful file, Brave may also send URLs, including bits of page content, to Safe Browsing.

"No Protection" text should read (basically remove the second sentence): 
Does not protect you against dangerous websites, downloads, and extensions.

second screen:
"Safe Browsing" text should read when on (basically remove the second sentence. No change in text if Safe browsing is off):
Standard protection is on. 

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by fmarier** [comment]
Also, we should remove this bit from *Standard Protection*:
> If a site tries to steal your password, or when you download a harmful file, Brave may also send URLs, including bits of page content, to Safe Browsing.

since we disable that in Brave.

**Comment by LaurenWags** [comment]
@rebron @fmarier is the part in the box that says `Checks URLs with a list of unsafe sites stored in Brave` accurate? 
<img width="693" alt="Screen Shot 2020-09-25 at 9 44 21 AM" src="https://user-images.githubusercontent.com/28145373/94279246-da4d8480-ff19-11ea-8480-10be66d08b0a.png">

**Comment by fmarier** [comment]
@LaurenWags Yes, that part is accurate. The list is stored here:
```
$ ls ~/.config/BraveSoftware/Brave-Browser-Beta/Safe\ Browsing
ChromeExtMalware.store  UrlBilling.store  UrlMalware.store  UrlUws.store
IpMalware.store         UrlMalBin.store   UrlSoceng.store
```

**Comment by LaurenWags** [comment]
great, thanks for clarifying @fmarier!

**Comment by btlechowski** [comment]
Requires build higher than 1.15.69. Marked it as `QA/Blocked` till we get a new build.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.15.70 Chromium: 86.0.4240.68 (Official Build) (64-bit)
-- | --
Revision | ad72ee9aa8e15ed300df1238e76c7a8f4d686f97-refs/branch-heads/4240@{#1097}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified STR from the description

![image](https://user-images.githubusercontent.com/38657976/95075890-9a16af00-072e-11eb-9089-dd0560b25c77.png)

![image](https://user-images.githubusercontent.com/38657976/95075657-34c2be00-072e-11eb-890b-88f7113eb63a.png)
