### ISSUE TITLE
[Android] Installed for about 90 days, ads have been showing, no rewards

### ISSUE THREAD

**Issue by coinzdude** [brave/brave-browser#11350]
Samsung s9, One UI 2.1, stock
Safety check passed, 
Brave 1.12.113

I accidentally uninstalled Brave on android just over two months ago.  New install of Brave has been getting ads, but there are no rewards, none pending.

![image](https://user-images.githubusercontent.com/58857646/90805369-8253aa80-e2e9-11ea-9407-a9b7d6ffc2af.png)

**Comment by tmancey** [comment]
@coinzdude Could you please click `View details` on the Ads panel and send a screenshot. Thank you

**Comment by coinzdude** [comment]
Coincidentally, after this time, ad revenue showed up.  Thanks!
