### ISSUE TITLE
[Desktop] Sync v2 initial bookmarks duplication - follow up to 11116

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#11358]
Follow up to https://github.com/brave/brave-browser/issues/11116
The issue still reproduces when synced in less than 2s.

## Steps to Reproduce

1. bookmark `brave://sync-internals/` on device A
2. bookmark  `brave://sync-internals/` on device B
3. Create sync chain on device A
4. Device B join sync chain shortly (less than 2s)

## Actual result:

We will see both devices have same duplicate bookmarks

## Expected result:
No duplicate bookmarks

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
-- | --
Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @darkdh @jsecretan

**Comment by jsecretan** [comment]
So, from what I know, this is something that can be reproduced in Chrome, and there may not be a whole lot we can do to work around.  Closing for now.
