### ISSUE TITLE
[Android][Follow up #11210] Sync not working message showing up on private tabs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11363]
## Description 
[Follow up #11210] Sync not working message showing up on private tabs

## Steps to reproduce 

   1. Install 1.15.2
   2. Open a new private tab
   3. Shows `Sync isn't working` message

## Actual result 
Sync isn't working message on private tab

## Expected result
Should not show sync message

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.15.2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by AlexeyBarabash** [comment]
Modified milestone to Nightly as it is merged  to Nightly only.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
- Verified no sync message is shown when opening a normal tab or a private tab on a clean install 
- Verified no sync message is shown when opening a normal tab or a private tab when upgrading from an older build
- Verified no sync message is shown irrespective of sync is being enabled or disabled on an upgrade install
----------------------
Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
- Verified no sync message is shown when opening a normal tab or a private tab on a clean install 
- Verified no sync message is shown when opening a normal tab or a private tab when upgrading from an older build
- Verified no sync message is shown irrespective of sync is being enabled or disabled on an upgrade install
