### ISSUE TITLE
Update/remove speedreader's dependency on adblock

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#11364]
@bridiver has some incoming Rust tooling updates, but these require all dependencies on the `psl`/`addr` Rust libraries to be removed. In the process of https://github.com/brave/brave-browser/issues/11233, we discovered there is one last `adblock-rust` dependency from `speedreader`. The best long-term option would be to break out a smaller part of `adblock-rust` that can be shared between the two libraries, or just remove it entirely in favor of an alternative matching engine. Failing that, upgrading `speedreader`'s dependency to match the one used for adblocking should suffice.

**Comment by antonok-edm** [comment]
@keur I believe you are in the process of working on this so I added you as an assignee

**Comment by keur** [comment]
Yeah, we are looking to just get rid of the backend that uses adblock-rs -> lolhtml rules altogther and use an implementation of readability. We need to keep it around until the readability backend is ready to go unfortunately. I have some blockers: 

- [ ] Dropping the dependency on markup5ever_rcdom.
- [ ] Implementing the whole algorithm
- [ ] Typing up the readability backend to the browser
