### ISSUE TITLE
[Desktop] WebRTC IP Handling Policy reverts to "Default public interface only"

### ISSUE THREAD

**Issue by dentistformyeye** [brave/brave-browser#11373]
## Description 

WebRTC IP Handling Policy in the "Privacy and security" section of brave://settings reverts to "Default public interface only" even when the user selects a different policy.

## Steps to Reproduce

   1. Open brave://settings. Scroll down to the "Privacy and security" section or search for "WebRTC" in the search bar. (The actual result may already appear.)
   2. Change the WebRTC IP Handling Policy to anything other than "Default public interface only".
   3. Refresh the settings page or close and reopen the settings page.

## Actual result:

![image](https://user-images.githubusercontent.com/51429646/90926062-59eaaf80-e3c0-11ea-9fc9-4097d54bf15e.png)
The WebRTC policy reverts to "Default public interface only" upon refresh of the settings page.

## Expected result:
Brave remembers the WebRTC policy that the user selects.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | macOS Version 10.15.6 (Build 19G73)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Don't know
- Can you reproduce this issue with the beta channel? Don't know
- Can you reproduce this issue with the nightly channel? Don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Don't know

## Miscellaneous Information:

Changing the fingerprinting blocking setting (strict, standard, disabled) in the shields section doesn't fix the issue, even though "Disable non-proxied UDP" is the default WebRTC policy when fingerprinting blocking is on.

**Comment by diracdeltas** [comment]
thanks for the details! closing as a dupe of https://github.com/brave/brave-browser/issues/11525 since there is already a discussion in that issue.
