### ISSUE TITLE
[Desktop][CW] Remove add card when all widgets are hidden

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11371]
## Description 

Remove add card when all widgets are hidden

## Steps to Reproduce

   1. Install beta `1.13.78`
   2. Go to settings and disable all widget cards
   3. Open a new tab shows a lonely `Add card` button

## Actual result:

![addcard](https://user-images.githubusercontent.com/17010094/90919640-b3fa6d80-e3de-11ea-9877-99c4e3a97320.gif)

## Expected result:
Should not show add card button 

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 1.13.78 Chromium: 85.0.4183.69 (Official Build) beta (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Blocked as https://github.com/brave/brave-core/pull/6476 still needs to be merged and requires a new `1.13.x` release preview.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | `94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)

- Verified add card is removed when all widgets are removed either via the dashboard or via new tab page settings
![win-add-card](https://user-images.githubusercontent.com/17010094/91291115-33f34f80-e7b2-11ea-99c0-fe653078f2ec.gif)

--------------
Verification passed on

Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | `94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}`
OS | Linux

- Verified add card is removed when all widgets are removed either via the dashboard or via new tab page settings
![linnux-add-card](https://user-images.githubusercontent.com/17010094/91290982-01e1ed80-e7b2-11ea-96c5-e055532b0490.gif)

--------------
Verification passed on

Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | `94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}`
OS | macOS Version 10.15.5 (Build 19F101)

- Verified add card is removed when all widgets are removed either via the dashboard or via new tab page settings
![mac-add-card](https://user-images.githubusercontent.com/17010094/91291200-56856880-e7b2-11ea-83d5-af9761b74e05.gif)
