### ISSUE TITLE
[Desktop] unnecessary scroll bar on sections of Customize Dashboard popup

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11374]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/10318

There's an unnecessary scroll bar on the Customize Dashboard popup on NTP. It makes sense when "More Cards" is selected, but not for the others (Background Image, Brave Stats, etc). 

Note, I'm using Mojave (10.14.6)

## Steps to Reproduce

   1. Install 1.13.x
   2. Open NTP
   3. Click on Customize

## Actual result:

See scroll bar. Same for Brave Stats, Top Sites, and Clock.

<img width="734" alt="Screen Shot 2020-08-21 at 3 34 52 PM" src="https://user-images.githubusercontent.com/28145373/90928524-07f85880-e3c5-11ea-8a8c-83ef6f3b625d.png">

## Expected result:
Scroll bar only when needed, ex. on More Cards
<img width="773" alt="Screen Shot 2020-08-21 at 3 43 53 PM" src="https://user-images.githubusercontent.com/28145373/90928567-22323680-e3c5-11ea-9d9e-5807f4662778.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @ryanml @karenkliu @rebron @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced `Windows 10 x64 - 1.13.79`

![image](https://user-images.githubusercontent.com/38657976/91157324-caf0d680-e6e2-11ea-9b1b-48f734e23202.png)

**Comment by btlechowski** [comment]
Reproduced on Linux

Brave | 1.15.14 Chromium: 85.0.4183.83 (Official Build) nightly (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/91452092-7d10d580-e87e-11ea-872d-14926965e5f3.png)

**Comment by srirambv** [comment]
+1 from @phoogm via #11480 for additional scroll bars

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/new-tab-page-scroll-bar/162253

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.16.50 Chromium: 86.0.4240.55 (Official Build) dev (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified STR from description.

Confirmed scroll bar is not shown Background Image, Brave Stats, Top Sites, and Clock sections of Customize Dashboard, example:
<img width="746" alt="Screen Shot 2020-10-02 at 3 36 08 PM" src="https://user-images.githubusercontent.com/28145373/94962944-55d4a600-04c5-11eb-9789-3efa54386dc2.png">

Confirmed scroll bar is shown on More Cards of Customize Dashboard:
<img width="741" alt="Screen Shot 2020-10-02 at 3 36 21 PM" src="https://user-images.githubusercontent.com/28145373/94962974-6258fe80-04c5-11eb-9abb-c02052d845dd.png">

------------
