### ISSUE TITLE
Automatically use new Tor identities

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1137]
When someone does a hard-refresh in a Tor window, we should also use a new Tor identity.

**Comment by bbondy** [comment]
Updated milestone on issue to 0.57.x.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.57.7 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Linux

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17010094/48994948-c002be00-f16b-11e8-8292-0e606a274d4b.gif)
