### ISSUE TITLE
[Desktop] Downloads don't prompt in 1.15.2 Chromium: 85.0.4183.69

### ISSUE THREAD

**Issue by corymcdonald** [brave/brave-browser#11370]
## Description 

When downloading an item they get "Stuck" as in they never prompt. I've seen this issue before but it was resolved when updating to the latest.

## Steps to Reproduce

   1. Go to a website and try to download

## Actual result:

![Aug-21-2020 13-32-48](https://user-images.githubusercontent.com/5459225/90918553-7b40a100-e3aa-11ea-82f5-188c77b1e7a8.gif)

## Expected result:
 The file is prompted to download

## Brave version (brave://version info)
```

Brave | 1.15.2 Chromium: 85.0.4183.69 (Official Build) nightly (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.15.5 (Build 19F101)
JavaScript | V8 8.5.210.19
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.69 Safari/537.36


```

## Version/Channel Information:
Nightly

**Comment by rebron** [comment]
@corymcdonald Is this happening on other websites? Is this just happening on Brave.com with the 'download' button at the top (as I'm seeing the prompt when clicking the main download button)? 

If this is a general issue, does restart fix the problem? Is this intermittent or happen every single time? 
Can you reproduce this issue with a new profile?

**Comment by corymcdonald** [comment]
Not happening anymore, can't reproduce consistently. I'm imagining it was something that was a problem with the upstream that got fixed.
