### ISSUE TITLE
[Android] Share button doesn't use HTTPS upgraded URLs

### ISSUE THREAD

**Issue by ckujau** [brave/brave-browser#11383]
## Description 

When opening an `HTTP` link in Brave either the site itself upgrades it to `HTTPS` (via `HTTP/302`) or Brave tries to upgrade via HTTPS-Everywhere, if possible. The site is then displayed with the little lock icon in the address bar and it's clearly a `HTTPS` address now and I can look at the certificate details and all that.

But when I now tap the `Share` button, the initial `HTTP` link is shared, **not** the upgraded `HTTPS` link.

## Steps to reproduce 

   1. Open `HTTP` link that upgrades itself to `HTTPS` or is upgraded via HTTPS-Everywhere by Brave
   2. Tap `Share` button
   3. The `HTTP` link is shared instead of the `HTTPS` link.

## Actual result 

The `HTTP` link is shared instead of the `HTTPS` link.

## Expected result

The `HTTPS` link should be shared instead of the initial `HTTP` link.

## Issue reproduces how often 

Always

## Version/Channel Information:

Reproduced on the current Play Store Beta version

## Device details
  ARM
  Google Pixel 4a
  Android version 10
  
## Brave version
v1.13.74

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?   No
- Does the issue resolve itself when disabling Brave Rewards?   No
- Is the issue reproducible on the latest version of Chrome? **Yes**

### Additional information

Example URL where I could get it reproduced reliably: `vanguardproperties dot com`

![vg](https://user-images.githubusercontent.com/822519/90991169-08772780-e55c-11ea-8871-10321e481c1a.jpg)

**Comment by garritfra** [comment]
Any implementation hints for this? I can give this one a shot.

**Comment by Aadi-27** [comment]
Hi, Can I take this issue ?

**Comment by bsclifton** [comment]
@Aadi-27 sure - hit me up if you have a pull request or have a question in general

**Comment by Aadi-27** [comment]
For some reason I can't seem to clone the repo as it says that I don't have
proper access rights.

Would you let me know the reason ? And also I was able to successfully
clone it once before but wasn't able to run "npm run init" as it gave an
ENONENT: no such directory exists kind of error.

**Comment by rahulsnkr** [comment]
Is this issue still open to be worked on? Can I take it up?

**Comment by davidcardd1** [comment]
I'd like to work on this issue, could I be assigned to it? I'm new to Open-Source contributing

**Comment by satvik2131** [comment]
is this issue still there ?

**Comment by ckujau** [comment]
No longer reproducible, closing. Thanks for the reminder!
