### ISSUE TITLE
[Desktop] Brave Ads are not displayed

### ISSUE THREAD

**Issue by Geryythekid** [brave/brave-browser#11380]
I stopped receiving ads on my main PC for like 2 weeks.

## Description 
Currently i use 4 devices, 2 phones, 2 pcs. On the secondary pc, on phones ads are working fine but i can't get any on my main.
At the time i am located in Slovakia.

## Steps to Reproduce
I browsed reddit, tried all the tips&tricks that i found, none of them helped.
 

## Actual result:
No result, still no ads.

## Reproduces how often: 
Daily, for like 2 weeks.

## Brave version (brave://version info)

Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
OS | Windows 10 OS Version 1909 (Build 18363.752)

## Other Additional Information:
Only tested with current version of brave.

- Does the issue resolve itself when disabling Brave Shields? 
- No.
- Does the issue resolve itself when disabling Brave Rewards?
- Yes, re-enabling does not help. 

## Miscellaneous Information:
I am using VPN on my all devices and everything is working fine on other devices. Tried disabling, configuring and the problem still persists. Tried to disable extensions too, that did not help either.
![ads_rewards](https://user-images.githubusercontent.com/70077026/90966465-01f09d80-e4d3-11ea-9cac-f674a690ed5c.png)
![brave_task_manager](https://user-images.githubusercontent.com/70077026/90966468-0452f780-e4d3-11ea-8a37-5f70ab946acf.png)

**Comment by tmancey** [comment]
@Geryythekid Can you please confirm if you have restored the wallet to all of these devices, i.e. using same wallet for all devices? Thanks

**Comment by tmancey** [comment]
@Geryythekid Closing this issue as a duplicate of https://github.com/brave/brave-browser/issues/11299

**Comment by Geryythekid** [comment]
@tmancey No, i haven't done that. I have the wallet(Uphold) connected only to my PCs. I don't have enough BAT to connect my phones, yet.

**Comment by Geryythekid** [comment]
@tmancey And yeah, my issue is not about "Brave Ads are not displayed". My issue is that i don't get them on my main PC, when i am getting them on others,i am not duplicating an issue.

**Comment by tmancey** [comment]
@Geryythekid If you have the same uphold account connected, this is not supported at this time and will cause issues with ads not always appearing in your browser

**Comment by tmancey** [comment]
@Geryythekid Apologies, I have reopened the ticket. Can you please visit brave://rewards-internals and search the log for the very last `not shown:` and paste the reason displayed after `not shown:`. Please do not send or paste any other logs.

**Comment by Geryythekid** [comment]
[25 Aug 2020, 1:28:35.8 am:INFO:ads_impl.cc(1003)] Ad notification not shown: Notifications not allowed 
This is on my main PC.
[Aug 25, 2020, 12:49:57.7 AM:INFO:ads_impl.cc(1003)] Ad notification not shown: Not allowed based on history
Did the same on my laptop and this came up.

**Comment by Geryythekid** [comment]
After restarting my PC i found this too:
[25 Aug 2020, 2:31:42.4 am:INFO:ads_impl.cc(1003)] Ad notification not shown: No eligible ads found
It gives me different error every time when i look at it.

**Comment by tmancey** [comment]
`Ad notification not shown: Notifications not allowed` would mean that notifications are disabled or focus assist is enabled

`Ad notification not shown: No eligible ads found` would mean there are no eligible ads at this time please keep checking back for when more ads are added to your region or allowed to be shown

`Ad notification not shown: Not allowed based on history` would mean that you have exceeded the allowed ads at this time, more will be shown once this cap is lifted

**Comment by Geryythekid** [comment]
Well, i have notifications enabled and focus assist disabled, just like the others in reddit suggested. It is really weird cuz on my laptop i am getting ads, despite :[Aug 25, 2020, 12:49:57.7 AM:INFO:ads_impl.cc(1003)] Ad notification not shown: Not allowed based on history. 
I will keep an eye on it from now on. Want me to post more if i find a different one ?

**Comment by tmancey** [comment]
@Geryythekid Please DO NOT post log but you should see the actual reason on the line(s) just above when ads are blocked based on history. Could you check and let me know please. Thanks

**Comment by Geryythekid** [comment]
[26 Aug 2020, 2:16:52.2 am:INFO:ads_impl.cc(381)] Browser state changed to idle
[26 Aug 2020, 2:20:17.4 am:INFO:ads_impl.cc(390)] Browser state changed to unidle
[26 Aug 2020, 2:20:17.4 am:INFO:ads_impl.cc(1003)] Ad notification not shown: Not in foreground


[26 Aug 2020, 2:16:31.2 am:INFO:ads_impl.cc(932)] Serving ad notification from untargeted category
[26 Aug 2020, 2:16:31.2 am:INFO:ads_impl.cc(1003)] Ad notification not shown: No eligible ads found

[26 Aug 2020, 1:35:53.5 am:INFO:ads_impl.cc(381)] Browser state changed to idle
[26 Aug 2020, 1:35:54.5 am:INFO:ads_impl.cc(390)] Browser state changed to unidle
[26 Aug 2020, 1:35:54.5 am:VERBOSE3:client.cc(545)] Saving client state
[26 Aug 2020, 1:35:54.5 am:VERBOSE3:ads_impl.cc(1344)] Event log: {"data":{"type":"settings","timestamp":"0 hours, 0 minutes, 0 seconds at 01:35","settings":{"locale":"en-GB","notifications":{"shouldShow":false},"userModelLanguage":"en","adsPerDay":20,"adsPerHour":5}}}
[26 Aug 2020, 1:35:54.5 am:INFO:ads_impl.cc(1003)] Ad notification not shown: Notifications not allowed

These are all i could find.

**Comment by tmancey** [comment]
`{"shouldShow":false}` is the cause on this device as according to Brave Ads notifications are not enabled for the Brave Browser on your Windows computer. Please check the notification settings for Brave Browser and global notification settings. Thanks

**Comment by Geryythekid** [comment]
That should not happen, it is already enabled. Tested with bennish web notifications tester and that showed up.
![Screenshot_1](https://user-images.githubusercontent.com/70077026/91337375-8bee7e00-e7d3-11ea-8215-1d8c289fc6f8.png)

**Comment by tmancey** [comment]
@Geryythekid Can you please try enabling Notifications & actions (very top of your screenshot). Thanks

**Comment by Geryythekid** [comment]
It is enabled, otherwise i could not enable the lower ones.

**Comment by tmancey** [comment]
@Geryythekid I was going by the screenshot above as at the very top Notifications & actions are Off. Can you please email me so we can arrange a screen-share to identify the issue. Thank you

**Comment by Geryythekid** [comment]
![notifications1](https://user-images.githubusercontent.com/70077026/91564745-5c5d8400-e941-11ea-983c-eb120fb9a2e2.png)
Notifications are on. I am no longer on 1909, this is an earlier version of windows, that is why it is displayed like that.
No need for screen share. I just find the problem to be very odd since i am getting errors on both pcs. Despite the warnings; on my laptop i am still getting ads normally.

**Comment by tmancey** [comment]
Could you please let me know the warning you are seeing on your laptop. Thanks

**Comment by Geryythekid** [comment]
The warnings are the same on my PC&laptop, but at different times. On my laptop i was getting ads anyways, but a few days ago i started getting ads on my PC too. Looks like brave had some sort of issues and they have been fixed. Thank you for your help sir!
