### ISSUE TITLE
[Android] Ad notification without a link is shown on watch

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11397]
## Description 
Follow up to #9397. @bbondy mentioned that he is receiving ad notifications on watch but doesn't contain a link to it.

## Steps to reproduce 

   1. Follow steps from #9397 

## Actual result 
Ad notification shown on wearable

## Expected result
No ad notifications to be shown on wearables

## Issue reproduces how often 
N/A

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No as per #9397
- Can you reproduce this issue with the current Play Store Beta version?  NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Watch
   - Android version: 10
   
## Brave version
Android Nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Issue on nightly may not be happening on release. Possible CR regression

**Comment by yachtcaptain23** [comment]
Given that custom ads notifications will be released soon and not using OS-level notifications, I'm going to mark as Won't Fix.
