### ISSUE TITLE
[Desktop] Brave does not work without hardware acceleration on OSX

### ISSUE THREAD

**Issue by davinci26** [brave/brave-browser#11396]
## Description 

Brave does not work without hardware acceleration on OSX see recording

## Steps to Reproduce

   1. Turn hardware acceleration off
   2. Restart Brave
   3. Open Brave

## Actual result:
[brave.mov.zip](https://github.com/brave/brave-browser/files/5118742/brave.mov.zip)

## Expected result:
To work as expected

## Reproduces how often: 
Every time

## Brave version (brave://version info)
I could tell you but as you can see brave is not working.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Haven't tried
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by davinci26** [comment]
Is there a way to re-enable the hw acceleration even when my browser is in that state?

The only reason I disable it is because I needed it to work around https://github.com/brave/brave-browser/issues/9710

**Comment by Martina-Neumayer** [comment]
Look at this post..
https://support.brave.com/hc/en-us/articles/360044860011-How-Do-I-Use-Command-Line-Flags-in-Brave-
And try flag: -enable-gpu

**Comment by rebron** [comment]
@davinci26 Were you able to resolve this issue? Can you also try with the latest version 1.14.84

**Comment by davinci26** [comment]
I will try later today and report back the results.

Thanks for the fix!
