### ISSUE TITLE
[Desktop][CW] Loading component opens up a new tab for brave://wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11392]
## Description 

Loading component opens up a new tab for brave://wallet

## Steps to Reproduce

   1. Open `brave://extensions` and sideload `0.1.72` component
   2. Wait till the component is loaded
   3. `brave://wallet opens up in a new tab

## Actual result:

Loading component opens up a new tab for brave://wallet

## Expected result:
Should not load in a new tab

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.13.78 Chromium: 85.0.4183.69 (Official Build) beta (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux
Component | `0.1.72`

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/ethereum-remote-client/pull/156

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
-- | --
Revision | `c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)
Component | `0.1.74`

- Verified loading component doesn't open in a new tab

-----------------------------

Verification passed on 

Brave | 1.13.78 Chromium: 85.0.4183.69 (Official Build) beta (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux
Component | `0.1.74`

- Verified loading component doesn't open in a new tab

-----------------------------

Verification passed on 


Brave | 1.15.6 Chromium: 85.0.4183.78 (Official Build) nightly (64-bit)
-- | --
Revision | `720ec01a54ea94d2d8b7a1d273e0fa89722fb11b-refs/branch-heads/4183@{#1603}`
OS | macOS Version 10.15.5 (Build 19F101)
Component | `0.1.74`

- Verified loading component doesn't open in a new tab

**Comment by srirambv** [comment]
Fixed by https://github.com/brave/ethereum-remote-client/commit/b6a9d98f2918d1576d67861ee5dd500483ee6f12
