### ISSUE TITLE
Fix mac signing

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#114]
Mac signing changed in C65 and we need to update our tooling.

**Comment by RyanJarv** [comment]
I believe this is covered by https://github.com/brave/brave-core/pull/112

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X

* Verified that `codesign -vv /Applications/Brave\ Browser\ Dev.app/` output the following:

```
/Applications/Brave Browser Dev.app/: valid on disk
/Applications/Brave Browser Dev.app/: satisfies its Designated Requirement
```
* Verified that `spctl --assess --verbose /Applications/Brave\ Browser\ Dev.app/` output the following:

```
/Applications/Brave Browser Dev.app/: accepted
source=Developer ID
```

**Comment by kjozwiak** [comment]
@LaurenWags once you go through the above with your macOS and give it a double check, you can tag this as `QA Pass-macOS` and remove the `QA/Needed` tag 👍

**Comment by LaurenWags** [comment]
Went through verification using the following build under `macOS 10.12.6 x64` - passed

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X

* Verified that `codesign -vv /Applications/Brave\ Browser\ Dev.app/` output the following:

```
/Applications/Brave Browser Dev.app/: valid on disk
/Applications/Brave Browser Dev.app/: satisfies its Designated Requirement
```
* Verified that `spctl --assess --verbose /Applications/Brave\ Browser\ Dev.app/` output the following:

```
/Applications/Brave Browser Dev.app/: accepted
source=Developer ID
```
