### ISSUE TITLE
[Android] Problem with Brave rewards location detection system

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#11400]
## Description 
Recently installed Windscribe VPN android app. After that brave added the "State level ad targeting option" with some us state selected  in my Brave Rewards Ads settings page. (Previously there is no State level ad targeting option). After that completely removed Windscribe, Cleared the mobile and brave cache. Also tried Brave rewards ON and OFF. Brave ads ON and OFF. And restarted the mobile several times. But the "State level ad targeting option" with the us state (alabama in my case) still shows. Now my ip is a local ip. But still no luck.

## Steps to reproduce 
Brave already installed with Brave rewards enabled and working fine. My current location is not US and there is no "State level ad targeting option" in the Ads settings page.

   1. Install Windscribe android app 
   2. Select US location and enable VPN
   3. Restart Mobile and enable VPN
   4. Open Brave browser and start browse.
   5. Go Brave Rewards
   6. In Ads section click view Details, then click the settings icon.
   7. It added State level ad targeting option below Maximum number of ads displayed.
   8. It automatically added the state based on the brave browser location detection system.
   9. Now Disable Windscribe vpn.
  10. Completely stop Windscribe from background and uninstall it. 
  11. Restart mobile 
  12. Check the Brave Rewards Ads Setting. It Still shows State level ad targeting option with previously selected US state
  12.  Stop brave from Background, Restart mobile, Open Brave. Try Brave rewards ON and OFF. Try Brave ads ON and OFF, Several mobile restart. But still "State level ad targeting option" with the us state on ads settings page.

## Actual result 
It still shows "State level ad targeting option" with us state list  from the Ads settings page.
![WhatsApp Image 2020-08-24 at 8 43 30 PM](https://user-images.githubusercontent.com/46480489/91068409-dba53c00-e651-11ea-9d56-733418917385.jpeg)

## Expected result
It should remove "State level ad targeting option" with us state list  from the Ads settings page.

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Not Tested
- Can you reproduce this issue with the current Play Store Nightly version? Not tested

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version: 6.0.1
![WhatsApp Image 2020-08-24 at 8 43 07 PM](https://user-images.githubusercontent.com/46480489/91067835-0a6ee280-e651-11ea-8405-63425c5d1f22.jpeg)

   
## Brave version
Brave 1.12.113, Chromium 84.0.4147.125

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards?NO
- Is the issue reproducible on the latest version of Chrome? Not tested

**Comment by tmancey** [comment]
@manikandancode Can you please select `Auto-detect` and let me know if this selects the correct state. Thank you

**Comment by manikandancode** [comment]
Currently i am in Asian country. Initially the Auto-detect option setting auto detect state as New York (plz check this) But after some time (in my case after 15 minutes)  the option  "State level ad targeting option" completely removed.  thanks.
But Brave should detect the correct location and remove  the US "State level ad targeting option"  automatically without selecting "Auto-detect" in "State level ad targeting option"

**Comment by tmancey** [comment]
If your IP address is detected as the USA, i.e. when using a VPN this option will be provided. If the IP address changes to a region outside of the USA this option will be removed

**Comment by manikandancode** [comment]
> If your IP address is detected as the USA, i.e. when using a VPN this option will be provided. If the IP address changes to a region outside of the USA this option will be removed

It is not changing (or removing the US state option) when the IP address changes to a region outside of the USA automatically.

Here we need to trigger that (removing the US state option) manually by selecting "Auto-detect" in state option. If any other option in state list then nothing happen.

It should remove automatically when the IP address changes to a region outside of the USA.

Because for reverse  (that is from outside of the USA to USA) it automatically adds that state option. So it should remove that option automatically from USA to outside of the USA without manually selecting each time Auto-detect in state option.

**Comment by tmancey** [comment]
@manikandancode Thank you for raising https://github.com/brave/brave-browser/issues/11421. We will triage the issue. Once again, thank you
