### ISSUE TITLE
Duolingo.com broken with default tracker blocking settings

### ISSUE THREAD

**Issue by clay53** [brave/brave-browser#11405]
## Description 

Doesn't work:
![image](https://user-images.githubusercontent.com/16981283/91082010-02458180-e616-11ea-97fa-f87e0919cfb4.png)
Does work: 
![image](https://user-images.githubusercontent.com/16981283/91082051-10939d80-e616-11ea-881a-e87a9dc1801a.png)

## Steps to Reproduce

   1. Go to Duolingo with default shield settings
   2. Be sad since it won't load

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:

Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
-- | --
OS | Linux

## Android Device details:
   - Install type (ARM, x86): ARM probably idk doesn't matter
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S7 and probably every other one
   - Android version: 8.1

## Version/Channel Information:

- Can you reproduce this issue with the current release?
  - Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
  - Yes
- Does the issue resolve itself when disabling Brave Rewards?
  - Probably not
- Is the issue reproducible on the latest version of Chrome?
  - Wouldn't happen in Chrome

**Comment by CeruleanSky** [comment]
@clay53 I had the same issue, but I just refreshed the duolingo page on my phone and it seems to be working again, perhaps the rules updated.  Why don't you try it again and close the issue if it works now.

**Comment by clay53** [comment]
Works for me too now. Thank you!
