### ISSUE TITLE
Remove desktop-specific Greaselion code when all platforms are migrated

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#11403]
Once all of our platforms migrate to using Greaselion to handle inline tipping, remove the temporary code we added to make Greaselion desktop- and media type-specific. This code is localized to the following files in a function named `handledByGreaselion`/`HandledByGreaselion`.

```
components/brave_rewards/resources/extension/brave_rewards/background/reducers/rewards_panel_reducer.ts
vendor/bat-native-ledger/src/bat/ledger/internal/media/media.cc
```

**Comment by Miyayes** [comment]
Vimeo doesn't always adhere to the 8s before being added to A-C table. Just noting some general finnickiness. —Lauren
