### ISSUE TITLE
[Desktop] add Greaselion configuration flag for incognito mode

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#11409]
as discussed in https://github.com/brave/security/issues/215#issuecomment-679349124, greaselion scripts run in incognito mode by default. we should add a configuration option in https://github.com/brave/brave-site-specific-scripts#configuration-file-format that indicates if the script should run in incognito contexts, since generally scripts that are related to rewards/ads should not.

**Comment by diracdeltas** [comment]
i would prefer this default to not allowed in incognito mode.

**Comment by emerick** [comment]
cc: @pilgrim-brave

**Comment by emerick** [comment]
Is this issue still relevant in light of this recent commit: https://github.com/brave/brave-core/commit/6bbdfb1137381be8787bdb39462c544446f8ce54?

**Comment by diracdeltas** [comment]
@darkdh  does this mean there's no way for greaselion scripts currently to run in incognito windows? (if so this issue can be closed)

**Comment by bsclifton** [comment]
Sorry for digging up an old issue! But it does look like that's correct- Greaselion shouldn't be running in Incognito (private) windows.
https://github.com/brave/brave-core/blob/679a703ce6c2149199f208e72bc5eb3fdbe1e367/components/greaselion/browser/greaselion_service_impl.cc#L117-L118

Confirmed by opening a private window and then opening Twitter and not seeing tips button
