### ISSUE TITLE
Grammarly extension not working for several users

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1141]
## Description 
Both @TravisEz13 and @limonte have reported that the Grammarly extension is having issues with brave-core ([reported here](https://github.com/brave/browser-laptop/issues/12289#issuecomment-421446188))

## Steps to Reproduce

   1. Install Grammarly extension
   2. Try typing into a text field
   3. Notice that a weird icon shows up

## Actual result:
@TravisEz13 reports seeing this:
![image](https://user-images.githubusercontent.com/10873629/45568454-8cbdbd80-b811-11e8-917c-e912550b5a6c.png)

@limonte reports seeing this (on github.com):
![image](https://user-images.githubusercontent.com/6059356/45570478-8ceaa700-b86b-11e8-8fac-29cf159fbe7d.png)

## Expected result:
Extension should work

## Brave version (chrome://version info)
BraveDev latest (Version 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit))

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?
no 
- Is the issue reproducible on the latest version of Chrome? 
unknown

**Comment by limonte** [comment]
> Is the issue reproducible on the latest version of Chrome?
> unknown

I mentioned in https://github.com/brave/browser-laptop/issues/12289#issuecomment-421457707 that the same extension works with latest Chrome and Opera.

**Comment by limonte** [comment]
Confirming that issue is still presented in the latest relese of a stable channel (0.55.18)

**Comment by christianjuth** [comment]
Has anyone been able to log into Grammarly Premium and have the browser extension recognize it? If I go to [app.grammarly.com](https://app.grammarly.com) it shows I am logged in. If I open the extension it says "Grammarly is active, but key features are missing" because I am not logged in.

### Steps to Reproduce
1. Install Grammarly extension
2. Open extension popup and follow login directions
3. Popup sends me to https://app.grammarly.com/?utm_medium=internal&utm_source=signinHook where I sign in
4. app.grammarly.com shows I am signed in, but Grammarly extension does not.

I have not tried turn shields off. I'm not sure how shields effect browser extensions compared to websites.

### Brave version (chrome://version info)
BraveDev latest (Version 0.57.2 Chromium: 70.0.3538.67 (Official Build) dev (64-bit))

**Comment by ergenekonyigit** [comment]
@christianjuth same problem here.

### Brave version (chrome://version info)
0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)

**Comment by MikePryn** [comment]
+1

**Comment by limonte** [comment]
Guys, please stop spamming subscribers of this issue with "+1" comments, use [GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) instead.

**Comment by markogresak** [comment]
I got it to work.

In short, I think all you need is to restart the browser after clicking the login link. 

All the steps I have taken: 
1. Install Grammarly extension
2. Go to https://app.grammarly.com and login (for extra measure, I logged out and logged back in, not sure if it's needed)
3. Disable the shields on https://app.grammarly.com (not sure this part is necessary)
4. Click the login link in extension window (you should already be logged in at https://app.grammarly.com)
5. Restart Brave browser
6. (If you did the step 3.) Go to https://app.grammarly.com and re-enable the shields

**Comment by limonte** [comment]
I just noticed that without any additional actions (except keeping Brave up-to-date of course), the Grammarly extension started to work for me 🎉 

Windows, Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)

**Comment by christianjuth** [comment]
I have Grammarly working on Brave Dev. I am also running a few other extensions (DuckDuckGoEssentials, Dashlane, and Honey) with no issues.

Mac, Version 0.57.4 Chromium: 71.0.3578.31 (Official Build) dev (64-bit)

**Comment by TravisEz13** [comment]
It was working for me on the dev build, but I quit using for reasons not relevant for this issue.  I'm fine if this issue is closed.

**Comment by bsclifton** [comment]
All known issues should be resolved now
