### ISSUE TITLE
[brave/desktop] brave tor startup

### ISSUE THREAD

**Issue by staufenberg** [brave/brave-browser#11418]
is it planed to startup the desktop version of brave in tor mode? like the incognito mode (--incognito)  maybe with --tor?

**Comment by JJohnGreenSr** [comment]
Isn't this a duplicate of #2105? Or for the first, more general question which is asked at #1457?

**Comment by bsclifton** [comment]
Good eye, @JJohnGreenSr 😄 I think this is a bit different, as it could be solved with a setting that a person changes in brave://settings. The code someone writes to fix it will be similar to those two issues though! 😄

**Comment by rebron** [comment]
cc: @darkdh

**Comment by fmarier** [comment]
@JJohnGreenSr is right, this is a duplicate of https://github.com/brave/brave-browser/issues/2105.
