### ISSUE TITLE
Remove "block count" for Fingerprinting protection in Shields

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#11429]
## Description 

When Fingerprinting settings are changed in Shields, the "count" for items blocked by the protection is never updated. According to @pes10k, this is because:

> 1. we dont have a good way of distinguishing good from bad use
> 2. as we “farble” more things, there gets to be a huge number of benign uses being reported as fingerprinting, which isn’t fair for the site
> 3. our protections are designed to not block, but just subtully modify, to address the above things

Given the above, it is misleading to have the count reflected in the Shields panel at all and can confuse users at times and/or appear as though the setting is not actually working. It may be better in the long run to simply _remove_ the count in the Shields panel and mimic the way the `Cross-site cookies` option is implemented (no count next to setting).
![fpp](https://user-images.githubusercontent.com/3299098/91225732-f2db3c80-e6d8-11ea-8d6b-7ec4d647d396.jpeg)

**Comment by srirambv** [comment]
Closing as dupe of #10544
