### ISSUE TITLE
[Android] Pdf not opening

### ISSUE THREAD

**Issue by Nasheedabdul** [brave/brave-browser#11420]
## Steps to reproduce 

   1. Pdf and apk is not opening after dowloading.
   2. It shows can't open files. 
   3. 

## Actual result 
![Screenshot_20200817_003919_com brave browser](https://user-images.githubusercontent.com/68918787/91200873-5dae6700-e71d-11ea-8c23-c6a42a5c01a9.jpg)

## Expected result

While click the file it should open 
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version: Android 9
   
## Brave version
Brave | 1.12.113 Chromium: 84.0.4147.125
-- | --

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?No
- Is the issue reproducible on the latest version of Chrome? No

### Additional information

Works fine while changing the download location to external storage.

**Comment by Nasheedabdul** [comment]
@SergeyZhukovsky check this out

**Comment by samartnik** [comment]
Test plan: try to open downloaded pdf file, it should be opened

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
- Verified able to open PDF's and APK's from downloads
----------------
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
- Verified able to open PDF's and APK's from downloads
----------------
