### ISSUE TITLE
[Android] State level ad targeting option not automatically removed after switching from USA to Non USA.

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#11421]
## Description 
This is continuity of the issue 11400
https://github.com/brave/brave-browser/issues/11400

If the IP changes from USA to a region outside of the USA, the  "State level ad targeting" option not automatically removed .

Here we need to trigger that (removing the US state option) manually by selecting "Auto-detect" in state option. If any other option in state list, then nothing happen.

It should remove automatically when the IP address changes to a region outside of the USA.

Because for reverse (that is from outside of the USA to USA) it automatically adds that state option. So it should remove that option automatically from USA to outside of the USA without manually selecting each time Auto-detect in state option.

## Steps to reproduce 

1. Change your Non USA ip to USA (using any vpn app)
2. Restart Mobile 
3. Open Brave browser and start browsing.
4. Go Brave Rewards. In Ads section click view Details, then click the settings icon.
5. It added State level ad targeting option below Maximum number of ads displayed. (its adds the USA state based on ip location)
6. Now change your ip to Non USA. (Disable vpn app and unistall)
7. Restart mobile
8. Now check the Brave Rewards Ads Setting. It Still shows State level ad targeting option with previously selected US state.Stop brave from Background, Restart mobile, Open Brave. Try Brave rewards ON and OFF. Try Brave ads ON and OFF, Several mobile restart. But still "State level ad targeting option" with the us state on ads settings page.
9. Now my ip is region outside of the USA . But it still shows USA State level ad targeting option.
10. Now choose "Auto-detect" from State level ad targeting drop down.
11. Wait some time 10- 15 minutes. And restart browser.  Now check the Brave Rewards Ads Setting. The  USA State level ad targeting option removed.

## Actual result 
USA "State level ad targeting" option not automatically removed.  we need to trigger manually by selecting "Auto-detect" in state option to remove "State level ad targeting"

## Expected result
USA "State level ad targeting" option should automatically removed when we switch from USA to Non USA.

## Issue reproduces how often 
always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? not tested
- Can you reproduce this issue with the current Play Store Nightly version?nor tested

## Device details
- Install type (ARM, x86):
- Device type (Phone, Tablet, Phablet):Phone
- Android version: 6.0.1
   
## Brave version
Brave 1.12.113, Chromium 84.0.4147.125

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
Closing issue as won't fix
