### ISSUE TITLE
[Desktop] remove "Check passwords" UI in settings

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11423]
## Description 

When you're on brave://settings/passwords there is an option to "Check passwords". We should remove this UI, it did not show in 1.12.x (C84) but does show with C85 versions of Brave.

## Steps to Reproduce

   1. Using C85 version (such as 1.13.x)
   2. Navigate to brave://settings/passwords

## Actual result:

<img width="740" alt="Screen Shot 2020-08-25 at 2 51 35 PM" src="https://user-images.githubusercontent.com/28145373/91215433-7e0d0000-e6e2-11ea-8200-c72178e3dfa6.png">

## Expected result:
This should not be displayed

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.12.x no, 1.13.x yes
- Can you reproduce this issue with the beta channel?  1.14.x yes
- Can you reproduce this issue with the nightly channel? 1.15.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @bsclifton

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.6 x64` using the following build:

```
Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.15.6 (Build 19G73)
```

Verified the STR/Cases outlined via both https://github.com/brave/brave-core/pull/6501#issuecomment-680956615 & https://github.com/brave/brave-browser/issues/11423#issue-685713001.

<img width="732" alt="Screen Shot 2020-08-27 at 12 14 19 AM" src="https://user-images.githubusercontent.com/2602313/91383849-257d5600-e7fb-11ea-9aeb-3f030f74cccc.png">
