### ISSUE TITLE
[Desktop][CW] Focus ring uses two colours when theme is set to dark 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11439]
## Description 

Focus ring uses two colours when theme is set to dark 

## Steps to Reproduce

   1. Set browser theme to dark
   2. Open dashboard settings
   3. Use keyboard to cycle through or click on an element in dashboard
   4. Focus ring uses both red and white borders

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/91281418-f7a6fb80-e77f-11ea-8ddc-a56034b3726e.png)

## Expected result:
Should be theme specific so either white or red

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.13.79 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Follow up to #11103

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.55 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified STR from description
<img width="736" alt="Screen Shot 2020-10-29 at 10 10 14 AM" src="https://user-images.githubusercontent.com/28145373/97584984-ffc52680-19ce-11eb-983c-879a682713ee.png">

Logged follow up issues: 
 - [Desktop] focus ring for X icon on Customize Dashboard has double blue/white border #12384
 - [Desktop] focus ring for toggles on Customize Dashboard still uses 2 colors #12385

--------
