### ISSUE TITLE
[Desktop] Browser crashes immediately on Ubuntu 18.04

### ISSUE THREAD

**Issue by janoskaz** [brave/brave-browser#11435]
## Description 
On Ubuntu 18.04, Brave 1.12.114, Chromium 84.0.4147.135, Brave browser crashes immediately after startup. 
## Steps to Reproduce

   1. open terminal
   2. type "brave-browser"

## Actual result:
Empty browser screen appears for a split second, but closes right away.

In terminal, following error appears:
`[9150:9150:0826/083725.566634:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.`

`/usr/bin/brave-browser: row 48:  9125 Unauthorized access to memory
 (SIGSEGV)  (core dumped [memory image saved]) "$HERE/brave" "$@"`

## Expected result:
browser starts

## Reproduces how often: 
every time

## Brave version (brave://version info)
1.12.114

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
Chromium works fine by itself

## Miscellaneous Information:
at first, the erroe was
`[2899:2899:0826/080738.832798:ERROR:vaapi_wrapper.cc(531)] The system version 1.1 should be greater than or equal to 1.5`

`[2899:2899:0826/080738.875141:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.`

after reinstalling `libva2`, the first part of error dissapeared.

purging brave-browser did not help

**Comment by Martina-Neumayer** [comment]
Go to /home/$USER/.cache/ and delete brave folder.
If not works then set in your system an environment variable:  "export MESA_GLSL_CACHE_DISABLE=true"
It is an old mesa bug described here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918433

**Comment by janoskaz** [comment]
Unfortunately it did not help, now the error is following:

`[3453:3453:0827/211239.639273:ERROR:vaapi_wrapper.cc(531)] The system version 1.1 should be greater than or equal to 1.5`
`MESA-LOADER: failed to retrieve device information`
`MESA-LOADER: failed to open i915 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)`
`failed to load driver: i915`
`MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)`
`failed to load driver: kms_swrast`
`MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)`
`failed to load swrast driver
`

**Comment by Martina-Neumayer** [comment]
Give me please an output from such command:
inxi -Fzx
Paste it on pastebin and here put the link to it.
If you don't have inxi, install it please.

First line is not a bug but just a warning that vaapi is not being initialised. Can be ignored.
Second line.. make sure you have latest libdrm installed.
Third and following lines.. it is an intel driver issue. 

Do like this.. (before you do this paste please this inxi output).
sudo apt-get purge xserver-xorg-video-intel
sudo apt-get intall -y mesa-utils libgl1-mesa-glx
Reboot the machine and should be fine.

**Comment by janoskaz** [comment]
Here is pastebin link:
https://pastebin.ubuntu.com/p/TpMyTNTDZF/

which libdrm library should i have? There are several, but libdrm-common is the latest

following the next steps did not help (xserver-xorg-video-intel was already purged and mesa-utils, libgl1-mesa-glx are in latest versions)

**Comment by Martina-Neumayer** [comment]
Yes, this "common" one should be okay.
If you have already those two installed, reinstall them both.
As I see you have a dual gpu onboard and a bit old kernel.
Now you need Intel firmware for your cpu, apm's, newest possible kernel and some nice developed radeon drivers etc.
All of these you can easily get trough this application..
https://mintguide.org/system/713-netext73-set-of-scripts-for-system-optimization.html

**Comment by janoskaz** [comment]
I have upgraded Ubuntu to 20.04, updated kernel, drivers, and everything through netext73, but the error persist. MESA related errors dissapeared, though.

Here is my current system info:
https://pastebin.ubuntu.com/p/HZrJTWZgSk/

and here is error shown in console:

`/usr/bin/brave-browser: line 48:  9122 Unauthorizes memory access (SIGSEGV)                     "$HERE/brave" "$@"`

**Comment by Martina-Neumayer** [comment]
Damn! Segmentation fault :(
Is not much you can do in the "segv case".
Try to check your ram by memtest. If it pass ok you can try brave from the beta channel.
To be honest, segfault mostly and sadly means: wait for developers to fix some bugs.

**Comment by janoskaz** [comment]
Great! beta version works! Thanks for all your help.

**Comment by Martina-Neumayer** [comment]
Nice and you're welcome 😊

**Comment by bsclifton** [comment]
Thanks for the assist, @Martina-Neumayer 😄
