### ISSUE TITLE
Device doesn't get added to sync chain

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11434]
## Description 

Device doesn't get added to sync chain

## Steps to Reproduce

   1. Create a sync chain on Android device 
   2. Add desktop to the sync chain by copying the sync code
   3. Android doesn't list the other devices in sync chain but desktop does 
   4. Android shows sync error 

## Actual result:

Sync error on Mobile | Sync username for Android | Sync username for Desktop 
-- | -- | -- | 
![image](https://user-images.githubusercontent.com/17010094/91267772-f5d33d00-e76b-11ea-8c3d-2e4402b907e0.png) | ![image](https://user-images.githubusercontent.com/17010094/91267775-f79d0080-e76b-11ea-8779-58789a430c4e.png) | ![image](https://user-images.githubusercontent.com/17010094/91268603-8bbb9780-e76d-11ea-9e83-b04caaaa9b63.png)
**Desktop devices** | **Android Devices** 
![image](https://user-images.githubusercontent.com/17010094/91267838-169b9280-e76c-11ea-9b51-314271dbdd8e.png) | ![image](https://user-images.githubusercontent.com/17010094/91267907-3c289c00-e76c-11ea-826f-0b7d7f239496.png)

## Expected result:
Device should sync and list the devices correclty 

## Reproduces how often: 

Once 

## Desktop Brave version:

Brave | 1.14.62 Chromium: 85.0.4183.78 (Official Build) beta (64-bit)
-- | --
Revision | `720ec01a54ea94d2d8b7a1d273e0fa89722fb11b-refs/branch-heads/4183@{#1603}`
OS | Linux

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @AlexeyBarabash @jsecretan

**Comment by AlexeyBarabash** [comment]
I can't reproduced. Tried on today's Nightly,
Desktops: 1.19.22
Android:  1.19.22
