### ISSUE TITLE
[Desktop]  Fails to display an image which is not an ad.

### ISSUE THREAD

**Issue by nanatani** [brave/brave-browser#11448]
## Description 

I'm using brave browser and found out that brave does not show a image which is not an ad.

## Steps to Reproduce

access to https://www.nintendo.co.jp/ring/index.html

## Actual result:

The red circle is showing where the image is missing. This also occurs with brave ios.

![0826_not-showing-image1](https://user-images.githubusercontent.com/53710740/91315708-fb279a80-e7f2-11ea-9370-81f4720abee3.PNG)

## Expected result:
displays this image.
![0826_not-showing-image3](https://user-images.githubusercontent.com/53710740/91316510-db44a680-e7f3-11ea-9dc6-dfaf1689d9de.PNG)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) （64 ビット）
-- | --
Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? : yes
- Can you reproduce this issue with the beta channel? : yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? : yes
- Does the issue resolve itself when disabling Brave Rewards? : no
- Is the issue reproducible on the latest version of Chrome? : no

**Comment by rebron** [comment]
cc: @ryanbr When you get a chance? I'm still seeing this in 1.16.x Beta channel

**Comment by ryanbr** [comment]
Missed this request, A fix is incoming.give it 24-48hrs. Sorry for the delay @nanatani

**Comment by nanatani** [comment]
@ryanbr Thanks for the fix! I checked with Desktop version Brave, and it is solved, thank you! however, for ios version, the image is still not showed...chould you check it?

**Comment by nanatani** [comment]
@ryanbr @chkk525 thank you for fixing this problem. I confirmed that it is solved in iOS too!
