### ISSUE TITLE
[Desktop][CW][Follow up #11103] Spacing between widget cards is not as per spec when Brave together is not available 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11441]
## Description 

[Follow up #11103] Spacing between widget cards is not as per spec when Brave together is not available 

## Steps to Reproduce

   1. Upgrade to 1.13.80 RC build
   2. Open a new tab and open dashboard settings
   3. Go to More cards, there is no spacing between cards aligned in two columns as Brave Together card is missing 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/91296344-5fffd800-e794-11ea-9b4f-67f80bd74ff1.png)

## Expected result:
![image](https://user-images.githubusercontent.com/2602313/90440482-4d571600-e0a5-11ea-9a98-b2fa22f0feb6.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | `94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @karenkliu

**Comment by karenkliu** [comment]
That's really weird that this is still showing up - I thought @ryanml already fixed this issue with the most recent updates.

**Comment by ryanml** [comment]
I specifically did address this one, only thing I can think of: @srirambv, do you see this present on Nightly when the Together banner is showing? I'm wondering if that is what is maybe causing this issue. cc: @karenkliu

**Comment by srirambv** [comment]
@ryanml yes this only happens when Brave Together is not available which will be most of the countries excluding NA. This is how it looks on the following build

Brave | 1.15.12 Chromium: 85.0.4183.83 (Official Build) nightly (64-bit)
-- | --
Revision | `94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}`
OS | Linux

With Brave Together | Without Brave Together
-- | --
<img width="1056" alt="Screenshot 2020-08-27 at 5 39 55 a m" src="https://user-images.githubusercontent.com/17010094/91385147-e0364400-e84d-11ea-9c79-31f6574d016b.png"> | <img width="1056" alt="Screenshot 2020-08-27 at 5 41 16 a m" src="https://user-images.githubusercontent.com/17010094/91385237-1673c380-e84e-11ea-9e82-151273f0d37b.png">

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.55 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified STR from description

<img width="747" alt="Screen Shot 2020-10-29 at 8 16 31 AM" src="https://user-images.githubusercontent.com/28145373/97572787-2aa77e80-19bf-11eb-9aaa-3e53fd2a3cc9.png">

Logged https://github.com/brave/brave-browser/issues/12381 for overlapping scroll bars

-------------
