### ISSUE TITLE
[Desktop][CW] Gemini widget button doesn't handle long translations

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11445]
## Description 

Found while spot checking translations for https://github.com/brave/brave-browser/issues/11395

When OS is set to German/Germany, the button on the Gemini widget wraps around itself. It seems like maybe this is happening because the translated text on the button is long.

Saw this for German/French, spot checked Norwegian, Finnish, Swedish, Spanish, and Portuguese and did not see this occur, those translations seem a bit shorter.

## Steps to Reproduce

   1. Be set to German/Germany or France/French.
   2. Launch 1.13.80
   3. Open NTP

## Actual result:

German:
<img width="312" alt="Bildschirmfoto 2020-08-26 um 09 34 10" src="https://user-images.githubusercontent.com/28145373/91310730-3b016a00-e780-11ea-864b-947502c77490.png">

French:
<img width="328" alt="Capture d’écran 2020-08-26 à 09 47 33" src="https://user-images.githubusercontent.com/28145373/91311527-2ffb0980-e781-11ea-89b8-df6619a55924.png">

## Expected result:
Button should look nice. 

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.13.80 Chromium: 85.0.4183.83 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
Betriebssystem | macOS Version 10.14.6 (Build 18G3020)

Brave | 1.15.11 Chromium: 85.0.4183.83 (Offizieller Build) nightly (64-Bit)
-- | --
Überarbeitung | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
Betriebssystem | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.12.x n/a, 1.13.x yes
- Can you reproduce this issue with the beta channel? 1.14.x yes
- Can you reproduce this issue with the nightly channel? 1.15.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @ryanml @srirambv

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows 10 x64 - 1.13.80 for locale `Hindi`

![image](https://user-images.githubusercontent.com/38657976/91314767-8cd3df80-e7d4-11ea-9a62-cf8b5a057b3f.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (64-bit)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | Linux

- Verified translations are handled correctly on the widget opt-in button
![image](https://user-images.githubusercontent.com/17010094/96117827-98917780-0ee2-11eb-9b8c-7b165a1879f7.png)

----------------------
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (x86_64)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified translations are handled correctly on the widget opt-in button
![image](https://user-images.githubusercontent.com/17010094/96119747-561d6a00-0ee5-11eb-9773-cecff3f1646e.png)

-----------------------
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (64-bit)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | Windows 10 OS Version 1809 (Build 17763.1490)

- Verified translations are handled correctly on the widget opt-in button
![image](https://user-images.githubusercontent.com/17010094/96119493-f921b400-0ee4-11eb-9518-7d39ab964033.png)

--------------
Logged follow-up issue for translations when widget is connected #12154
