### ISSUE TITLE
[Desktop] google account info showing in profile manager

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11444]
## Test Plan 

Specified here: https://github.com/brave/brave-core/pull/6516

## Description 

Broken out from https://github.com/brave/brave-browser/issues/11425

In 1.14.x and 1.15.x (so far), there are multiple issues with the profile manager. Second one is:

2. If you are signed into a google account, additional problems occur:
 - You get a "Manage your Brave sync chain" option that doesn't take you to sync settings (we probably want to remove this or fix where it leads to)
 - You get a "Sign out" option on profile menu  (we probably want to remove this since signing into Google shouldn't affect the profile manager)
 - Your profile icon, previously a Brave image changes to your google account image (I had to restart to see this, but it did occur - we probably want to fix this as well)

Note - above was only seen when logged into one google account. Should also confirm logging into two google accounts (ex. work and personal) when retesting. 

## Steps to Reproduce

   1. Clean profile with 1.14.x or 1.15.x
   2. Create a second profile
   3. Click on one of the profile icons --> See large "Turn on sync" button (https://github.com/brave/brave-browser/issues/11425)
   4. In one of the windows, sign into mail.google.com
   5. Click on one of the profile icons --> see "Manage your Brave sync chain" and "Sign out" options. If your profile icon hasn't changed, restart your browser and it will most likely update to your google account image.

## Actual result:

Step 5:
<img width="313" alt="Screen Shot 2020-08-25 at 3 20 14 PM" src="https://user-images.githubusercontent.com/28145373/91219717-173f1500-e6e9-11ea-8d57-ac65980b4ab3.png">

## Expected result:
Logging into Google account shouldn't have any affect on profile manager:
<img width="324" alt="Screen Shot 2020-08-25 at 3 39 19 PM" src="https://user-images.githubusercontent.com/28145373/91219786-35a51080-e6e9-11ea-974b-28e4fee07986.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.14.63 (Dev)
1.15.6 (Nightly)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.12.x C84 no, 1.13.79 CR 85.0.4183.69 not atm, but it is currently behind the others in CR version
- Can you reproduce this issue with the beta channel? yes, 1.14.63 CR 85.0.4183.78
- Can you reproduce this issue with the nightly channel? yes 1.15.6 CR 85.0.4183.78

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @mkarolin @Brave-Matt @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.14.79 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
<details>
<summary>1. Verified the test plan from the PR https://github.com/brave/brave-core/pull/6516</summary>

Step 2: Confirmed no `Accounts in Token Service` or `Refresh token events`
![image](https://user-images.githubusercontent.com/38657976/92595839-996f3200-f2c2-11ea-94cb-cfc041087c8a.png)

Step 3: Confirmed `Allow Google Login for extensions` is off by default
![image](https://user-images.githubusercontent.com/38657976/92596181-113d5c80-f2c3-11ea-8d60-2174bdbd7430.png)

Step 3: Confirmed toggling `Allow Google Login for extensions` prompts for a restart
![image](https://user-images.githubusercontent.com/38657976/92596303-3fbb3780-f2c3-11ea-80e4-f5137a446e3f.png)

Step 3: Confirmed `Allow Google Login for extensions` is on after the restart
![image](https://user-images.githubusercontent.com/38657976/92596507-890b8700-f2c3-11ea-98fc-4a4cecede989.png)

Step 4: Able to use `Google Keep extension`
![image](https://user-images.githubusercontent.com/38657976/92597105-82314400-f2c4-11ea-9854-864f5355f2a9.png)

Step 5: Able to use `Google Calendar extension`
![image](https://user-images.githubusercontent.com/38657976/92597315-db00dc80-f2c4-11ea-8da6-0027b6bf2eee.png)

Step 6: Confirmed profile menu doesn't show any Google sign in data
![image](https://user-images.githubusercontent.com/38657976/92597555-2fa45780-f2c5-11ea-918c-aa11621cf23c.png)

Step 9: Confirmed after removing site data, disabling `Allow Google Login for extensions` and relaunching, when attempting to use the Google Keep extension the Sign in button does not work
![image](https://user-images.githubusercontent.com/38657976/92598401-62028480-f2c6-11ea-8d12-0ceb09f0d56a.png)

</details>
