### ISSUE TITLE
Ads on YouTube (pre-roll and banner overlays) not blocked when video is embedded

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#1145]
**Description:** Pre-roll video ads and banner overlay ads appear on YouTube videos _that are embedded, such as those embedded or viewed on Reddit_. Otherwise, ads seem to be properly blocked when viewing on YouTube itself. 

Default shield settings.

**System Info:** Version 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit) — MacOS

**Screenshots:** 

<img width="992" alt="screen shot 2018-09-15 at 11 42 58 am" src="https://user-images.githubusercontent.com/11497541/45588114-79782400-b8dd-11e8-9404-9bdaf53b6cef.png">

Note the Gatorade pre-roll video ad in the YouTube player. 

Banner ads that overlay the video while its playing are also not blocked.

**Comment by bbondy** [comment]
Is this an issue with the muon based browser?

**Comment by Miyayes** [comment]
> Is this an issue with the muon based browser?

I don't believe so. This is something that only happens in the **Brave-core** browser. For example, https://www.reddit.com/r/Documentaries/comments/9mxt2v/the_fake_abortion_clinics_of_america_2014_women/ has ads on Core (and you can see yellow spots on the timeline for ads), but none on Muon.

**Comment by srirambv** [comment]
Haven't seen any pre-roll ads on other site with embedded videos

**Comment by bbondy** [comment]
@Miyayes is this still an issue?

**Comment by FWDekker** [comment]
I experience the same, except that it happens on YouTube itself as well.

Brave 0.55.18 // Chromium 70.0.3538.67 (Official Build) (64-bit)

**Comment by FWDekker** [comment]
I experience the same, except that it happens on YouTube itself as well.

Brave: 0.55.18 // Chromium: 70.0.3538.67 (Official Build) (64-bit)

**Comment by bbondy** [comment]
We believe an adblock update fixed this, is anyone still getting ads?

**Comment by Miyayes** [comment]
> We believe an adblock update fixed this, is anyone still getting ads?

@bbondy I'm still getting ads. Here's a screenshot of a YouTube video I just watched (embedded on Reddit). Note the banner ad. I also see a yellow notch in the video timeline when the video loads, indicating when an ad will appear: 

![image](https://user-images.githubusercontent.com/11497541/47474592-a6c1c700-d7e5-11e8-92e7-bdef426dde7b.png)

Here is the link to the video on Reddit where I was able to reproduce: https://www.reddit.com/r/MMA/comments/9r3ju5/ufc_on_youtube_derrick_lewis_watches_derrick_lewis/

On MacOS, Version 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit).

**Comment by srirambv** [comment]
I don't see the ad itself on Beta(0.56.6) but I do see the close and info button of the ad banner. This is the embedded video from the same link 
![image](https://user-images.githubusercontent.com/17010094/47500668-71db6180-d831-11e8-9896-1e4408820eed.png)

@Miyayes are you behind VPN ?

**Comment by bbondy** [comment]
Mainly I meant preroll video ads. 
For the text overlay ads I think I know how to fix that with a cosmetic content script.

**Comment by srirambv** [comment]
I dont see preroll ads on the embedded video on reddit link

**Comment by Miyayes** [comment]
Reproduced on MacOS 0.56.12. Full out **pre-roll video ad** on embedded video: 

![image](https://user-images.githubusercontent.com/11497541/48496498-17b23880-e800-11e8-81aa-d6175b7f170f.png)

**Comment by Miyayes** [comment]
This is reproducible for me, at least on Reddit, ~100% of the time. Here is a particularly _egregious_ example where the pre-roll ad is 30 seconds long, but shields removes the "skip ad" button, leaving the user no choice but to submit to resign to the full ad: 
![image](https://user-images.githubusercontent.com/11497541/49325594-4f64f400-f513-11e8-98fd-2f748664464e.png)

**Comment by antonok-edm** [comment]
This was fixed with https://github.com/brave/brave-browser/issues/10319.
