### ISSUE TITLE
[Desktop] avif photo not loading/rendering brave stable windows 10

### ISSUE THREAD

**Issue by epicodertime** [brave/brave-browser#11455]
Steps to reproduce:

go to https://jakearchibald.github.io/static-stuff/avif-scaled-test/?10

and scroll to the last photo avif and you can see its not rendering on chrome it is

Actual results:

the photo is not loading/rendering

Expected results:

it should load the photo like on chrome

**Comment by epicodertime** [comment]
firefox nightly is not affected

**Comment by hennrynusasatria** [comment]
Hi @epicodertime 

This issue also happens on Microsoft Edge Chromium v84, it seems that this issue does not happen on Google Chrome v85, thus it may be fixed once Brave Browser is updated to Chromium v85 as on #11454 

Thank you.

**Comment by epicodertime** [comment]
the image now renders
