### ISSUE TITLE
[Desktop] `Verify Wallet` button overlaps text in some locales on brave://rewards/#verify

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#11459]
On verification modal some text is overlapping

## Steps to Reproduce

1. Clean profile in Polish (PL) locale
1. enable rewards
1. claim grant
1. Open brave://rewards/#verify

## Actual result:

`Verify Wallet` button overlaps text
![image](https://user-images.githubusercontent.com/34715963/91387142-e23fd900-e834-11ea-8ced-86a97ed20fc2.png)

![image](https://user-images.githubusercontent.com/34715963/91387128-d227f980-e834-11ea-97a8-9df15132cd50.png)

## Expected result:
`Verify Wallet` button does not overlap text

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

Brave | 1.15.14 Chromium: 85.0.4183.83 (Oficjalna wersja) nightly (64-bitowa)
-- | --
Wersja | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Windows 10 x64 - 1.24.x`
