### ISSUE TITLE
[Android] [Security] prune log responses

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11456]
see https://github.com/brave/internal/issues/712#issuecomment-674643946 for details.

@srirambv if you need more context, ping me 👍

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 build
- Verification notes can be found here https://github.com/brave/internal/issues/712#issuecomment-685874363
-------------
Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 build
- Verification notes can be found here https://github.com/brave/internal/issues/712#issuecomment-685874363
