### ISSUE TITLE
[Desktop] Use Greaselion for Twitch publishers

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11466]
we should switch to GL for Twitch so that we can have faster turn around rate when something breaks.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.19.66 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/7019

<details>
<summary>Twitch user URL</summary>

</details>

<details>
<summary>Twitch video URL</summary>

</details>
