### ISSUE TITLE
[Desktop] Use GreaseLion for Reddit publishers

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11464]
we should switch to GL for Reddit so that we can have faster turn around rate when something breaks.

**Comment by LaurenWags** [comment]
Verification in progress with:

```
Brave	1.17.45 Chromium: 86.0.4240.99 (Official Build) dev (x86_64)
Revision	002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS	macOS Version 10.14.6 (Build 18G3020)
```

<details>
<summary>General</summary>

- Confirmed Greaselion script no longer needs to be installed manually, just need to confirm that Brave Local Data Updater is version >=1.0.32

<img width="374" alt="Component-SS" src="https://user-images.githubusercontent.com/28145373/97045528-e3933680-1543-11eb-961a-7455f17982d9.png">

- Confirmed visiting non-verified publishers showed the generic Reddit favicon in panel. Visited each of the below using a clean profile (staging env):
   - reddit.com/user/cryptojennie
   - old.reddit.com/user/brave_w0ts0n showed incorrect favicon, logged https://github.com/brave/brave-browser/issues/12301

<img width="396" alt="new reddit cryptojennie" src="https://user-images.githubusercontent.com/28145373/97045543-e726bd80-1543-11eb-87dc-010cc232a31e.png">
<img width="406" alt="old reddit brave_w0ts0n" src="https://user-images.githubusercontent.com/28145373/97045547-e8f08100-1543-11eb-962e-37b509a7a55b.png">

</details>
