### ISSUE TITLE
Alt - d brings up address bar and menu.

### ISSUE THREAD

**Issue by tabedzki** [brave/brave-browser#1146]
Hello,
For some while, hitting the combination `Alt + d` has had an unfortunate side effect; while it does bring the user to the url bar, it also activates the hidden menus upon release of the `Alt` key. 

I don't know how easy a fix this would be but since this not a problem for `Alt + Left Arrow`, I think this should be a relatively easy fix. Please let me know if I am wrong. 

--Tabedzki

**Comment by eljuno** [comment]
What is your Brave version?

It seems that this issue is for the current stable version of Brave while this repo is for brave-core, the upcoming rewrite version of Brave.

**Comment by tabedzki** [comment]
It is the latest release of the brave browser (release not insider or beta)
but my apologies. I did not realize this was a repo for a separate, new
version of the code.

**Comment by srirambv** [comment]
Closing as invalid
