### ISSUE TITLE
Remove rewards switch

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11467]
## Desktop
- [x] remove main switch on rewards page 
- [x] remove enable rewards in panel
- [x] remove enable rewards in NTP
- [x] remove join rewards on rewards page
- [x] remove join rewards in panel
- [x] remove join rewards in NTP
- [x] remove all checks for rewards enabled
- [x] change hide bat logo text so that is not dependent on enabled
- [x] check for wallet references in rewards_service.h, ledger.h, ledger_client.h and remove all that is not used anymore
- [x] remove all unused translations (locals)
- [x] implement new wallet creation
  - [x] promotion flow
  - [x] enabling ads
  - [x] external wallet
- [x] implement new process handling
  - [x] panel
  - [x] rewards page
  - [x] internals page
  - [x] tipping banner
  - [x] based on ads/ac settings
- [x] add migration for rewards flag for ac and ads
- [x] implement new onboarding on welcome screen
- [x] remove ads onboarding for new regions
- [x] adjust browser tests to new logic
- [x] implement new UI on rewards page

## Android
- [x] remove join rewards on rewards page
- [x] remove disabled state from the panel
- [x] remove join rewards from the panel
- [x] implement new onboarding
- [x] remove join rewards on NTP

**Comment by deeppandya** [comment]
@NejcZdovc Do we still need to `Reset Brave rewards`  in `Brave Rewards` section and `Hide Brave Rewards icon` in `Appearance` section ? i think we should remove it as we won't have any switch to disable brave rewards for BRE.

**Comment by NejcZdovc** [comment]
we still need reset so that you can reset rewards (remove wallet, db, etc). We also need hide icon, but should not be tied to enabled anymore. We will keep it on desktop as well

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/6680
<details>
<summary>Plan 1: Join Rewards switch is removed from brave://rewards page</summary>

![image](https://user-images.githubusercontent.com/38657976/100102062-17d27d80-2e89-11eb-8cce-8645b641c475.png)


</details>

<details>
<summary>Plan 2 & 3: Claim grants and send Tips</summary>

- Ensured grants can be claimed from BR panel, able to see claimed grants in wallet balance in brave://rewards page
![image](https://user-images.githubusercontent.com/38657976/100102837-253c3780-2e8a-11eb-950d-54b7b22e6b1b.png)
- Ensured claim rewards option is removed from NTP and rewards settings page once grants is claimed from  BR panel.
- Ensured able to tip verified and non verified pubs (GH/Reddit/Generic websites/YT/Twitch/Twitter/Vimeo)

Monthly tips
![image](https://user-images.githubusercontent.com/38657976/100103877-7993e700-2e8b-11eb-914f-69e8775e593b.png)

One time Tips:
![image](https://user-images.githubusercontent.com/38657976/100103921-86b0d600-2e8b-11eb-86d7-3d628cb66e9e.png)

- Encountered https://github.com/brave/brave-browser/issues/12451 for twitch pubs
- Ensured grants can be claimed from the rewards settings page and NTP's
- Ensured claimed grants is shown in wallet balance in brave://rewards page
- Ensured claimed grants are shown in monthly statements.
![image](https://user-images.githubusercontent.com/38657976/100104570-603f6a80-2e8c-11eb-856f-5386824f26e9.png)
- Ensured one time tips sent to unverified pubs are going to rewards pending table
![image](https://user-images.githubusercontent.com/38657976/100104828-ad234100-2e8c-11eb-9934-44578da80f3e.png)


</details>
