### ISSUE TITLE
[Desktop] Use GreaseLion for Github publishers

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11463]
we should switch to GL for Github so that we can have faster turn around rate when something breaks.

**Comment by LaurenWags** [comment]
`QA/Blocked` on https://github.com/brave/brave-browser/issues/12159

**Comment by LaurenWags** [comment]
the rate limiting error seen with https://github.com/brave/brave-browser/issues/12159 is not occurring at the moment, however it should still be decided what to do if/when the rate limiting happens again.

removing `QA/Blocked` for now as this issue can currently be tested.

**Comment by LaurenWags** [comment]
Verification in progress with:

```
Brave	1.17.60 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
Revision	37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS	macOS Version 10.14.6 (Build 18G6032)
```

<details>
<summary>Overall Notes for testing:</summary>

Test plan often references `Verify that tip icon is inserted in expected locations`. Per discussion with Emerick, these are the locations he provided:

```
  // Format: https://github.com/<user>/<repository>/pull/<pr_number>
  // Format: https://github.com/<user>/<repository>/issues/<issue_number>
  configureTipAction('timeline-comment-actions', commentInsertFunction)
  // Format: https://github.com/<user>/<repository>/commits/<branch_name>
  configureTipAction('js-commits-list-item', commitLinksInsertFunction)
  // Format: https://github.com/<user>?tab=stars
  configureTipAction('float-right', starringContainerInsertFunction)
  // Format: https://gist.github.com/<user>/<gist_number>
  configureTipAction('pagehead-actions', pageheadInsertFunction)
  // Format: https://github.com/orgs/<org>/people
  // Format: https://github.com/orgs/<org>/teams/<team_name>/members
  configureTipAction('member-list-item', memberListItemInsertFunction)
```

</details>

<details>
<summary>Pull Request</summary>

Verified STR from https://github.com/brave/brave-core/pull/6789 for unverified publisher (using https://github.com/brave/brave-core/pull/6743) on a clean profile.

Confirmed expected publisher (in this case, the organization) is displayed in the panel (on staging env):

<img width="1194" alt="PR1" src="https://user-images.githubusercontent.com/28145373/98159203-280ac480-1eaa-11eb-8bfe-faede2654f02.png">

Confirmed in-line tip button displays on comment areas:

<img width="1198" alt="PR1a" src="https://user-images.githubusercontent.com/28145373/98159209-2b05b500-1eaa-11eb-9792-cf4808f6e19e.png">
<img width="1195" alt="PR1b" src="https://user-images.githubusercontent.com/28145373/98159214-2c36e200-1eaa-11eb-98ea-0309bd4c153d.png">

Confirmed clicking on the in-line tip icon for a comment tips the author of the comment (note, content is not displayed for a GH in-line tip as it is for Twitter/Reddit. This is logged with https://github.com/brave/brave-browser/issues/5562):

<img width="1190" alt="PR1c" src="https://user-images.githubusercontent.com/28145373/98159226-3062ff80-1eaa-11eb-81ca-b67b8fd37e87.png">

Verified STR from https://github.com/brave/brave-core/pull/6789 for verified publisher (using https://github.com/LaurenWags/laurenwags.github.io/pull/1) on a clean profile.

Confirmed expected publisher (in this case, me) is displayed in the panel (on staging env).
Confirmed checkmark appears on BAT logo for verified publisher.

<img width="1190" alt="PR2" src="https://user-images.githubusercontent.com/28145373/98159237-3658e080-1eaa-11eb-962f-08e654028be2.png">

Confirmed in-line tip button displays on comment areas:

<img width="1191" alt="PR2a" src="https://user-images.githubusercontent.com/28145373/98159244-3953d100-1eaa-11eb-9d81-f176aa6a4d49.png">

Confirmed clicking on the in-line tip icon for a comment tips the author of the comment:

<img width="1194" alt="PR2b" src="https://user-images.githubusercontent.com/28145373/98159248-3bb62b00-1eaa-11eb-986b-b597a953c005.png">

</details>
