### ISSUE TITLE
[Android][Follow up #9435] Fingerprinting 2.0: Plugins not listed when shields is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11460]
## Description 
[Follow up #9435 ] Fingerprinting 2.0 Plugins not listed when shields is disabled

## Steps to reproduce 

   1. Visit `https://dev-pages.brave.software/farbling.html` or `https://dev-pages.bravesoftware.com/farbling.html`
   2. Disable shields and perform fingerprint test
   3. Plugins show value as `00000000` 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/91399676-4adb8580-e836-11ea-8074-3a930f0606b9.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/91399742-6d6d9e80-e836-11ea-8871-252c332ae0f5.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.13.81

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @pes10k @SergeyZhukovsky

**Comment by pes10k** [comment]
@srirambv i think we already worked through this, that `000000` is expected on Android when shields are down (since there are no plugins by default on android)
