### ISSUE TITLE
[Desktop] Remove backup/restore

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11469]

**Comment by mandar-brave** [comment]
https://docs.google.com/document/d/1FZBNIB3nzabUsw8y1GPaijEn0pFr4ddfAm-fmAgP5Nw/edit#heading=h.lde2e5o8qfu3

Details in document.

cc @jenn-rhim for minor design needs

**Comment by walidmujahid** [comment]
> https://docs.google.com/document/d/1FZBNIB3nzabUsw8y1GPaijEn0pFr4ddfAm-fmAgP5Nw/edit#heading=h.lde2e5o8qfu3
> 
> Details in document.
> 
> cc @jenn-rhim for minor design needs

The document does not seem to be public @mandar-brave. Why does the original post not have the details in the description?

**Comment by mandar-brave** [comment]
@walidmujahid the topic title should be clear, we are deprecating the wallet system like it has been for Mobile.
The document entails internal Brave specific items that are not open to public.

The PR should have all of the details of the changes. This is on hold for the moment.

**Comment by Miyayes** [comment]
This is complete.
