### ISSUE TITLE
[Desktop] Use Greaselion for Vimeo publishers

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11465]
we should switch to GL for Vimeo so that we can have faster turn around rate when something breaks.

**Comment by emerick** [comment]
CI passed, test failures on Mac/Windows were expected.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.18.62 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
Revision	0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS	macOS Version 10.14.6 (Build 18G6042)
```

Note - Vimeo videos are not added to AC list, this will be solved as part of https://github.com/brave/brave-browser/issues/12107 / https://github.com/brave/brave-site-specific-scripts/pull/28

Confirmed `Brave Local Data Updater` version is at least 1.0.38:

<img width="270" alt="Screen Shot 2020-11-25 at 9 39 53 AM" src="https://user-images.githubusercontent.com/28145373/100242387-b7802200-2f02-11eb-881f-e95fd18e5745.png">

<details>
<summary>Vimeo user URL</summary>

Verified test plan from https://github.com/brave/brave-core/pull/6955 using vimeo.com/bravelaurenwags on staging env

Confirmed that correct publisher information is displayed in the panel. Confirmed verified checkmark displays on BAT logo. Note - favicon is still incorrect and this has been logged with https://github.com/brave/brave-browser/issues/12781.

<img width="1195" alt="Screen Shot 2020-11-25 at 9 40 25 AM" src="https://user-images.githubusercontent.com/28145373/100242403-bb13a900-2f02-11eb-8a7e-ab1d689a70d7.png">

Confirmed able to tip as expected.

<img width="1198" alt="Screen Shot 2020-11-25 at 9 40 46 AM" src="https://user-images.githubusercontent.com/28145373/100242413-bfd85d00-2f02-11eb-9b17-0c149908c2ce.png">
<img width="410" alt="Screen Shot 2020-11-25 at 9 40 55 AM" src="https://user-images.githubusercontent.com/28145373/100242418-c1098a00-2f02-11eb-9d2d-c1954b32ee15.png">
<img width="949" alt="Screen Shot 2020-11-25 at 9 41 02 AM" src="https://user-images.githubusercontent.com/28145373/100242419-c23ab700-2f02-11eb-82d0-0f789c2e540a.png">
<img width="662" alt="Screen Shot 2020-11-25 at 9 41 10 AM" src="https://user-images.githubusercontent.com/28145373/100242421-c36be400-2f02-11eb-8003-2f9d33557929.png">
<img width="1166" alt="Screen Shot 2020-11-25 at 9 41 22 AM" src="https://user-images.githubusercontent.com/28145373/100242424-c4047a80-2f02-11eb-88d4-c2c26ade4f24.png">

Confirmed custom tip banner shows (if applicable).

<img width="1197" alt="Screen Shot 2020-11-25 at 9 41 38 AM" src="https://user-images.githubusercontent.com/28145373/100242435-c666d480-2f02-11eb-89e5-7bf46b2d3db0.png">

Confirmed correct publisher information for a non-verified Vimeo creator.

<img width="1196" alt="Screen Shot 2020-11-25 at 9 42 47 AM" src="https://user-images.githubusercontent.com/28145373/100242447-c9fa5b80-2f02-11eb-90f3-775627480284.png">

Confirmed tip to non-verified Vimeo creator goes to pending list as expected.

<img width="1194" alt="Screen Shot 2020-11-25 at 9 42 57 AM" src="https://user-images.githubusercontent.com/28145373/100242453-cc5cb580-2f02-11eb-82ab-59d4de6da74d.png">
<img width="1194" alt="Screen Shot 2020-11-25 at 9 43 06 AM" src="https://user-images.githubusercontent.com/28145373/100242456-ccf54c00-2f02-11eb-8e7a-cc1f308af286.png">
<img width="944" alt="Screen Shot 2020-11-25 at 9 43 18 AM" src="https://user-images.githubusercontent.com/28145373/100242459-ce267900-2f02-11eb-98d6-1e658229a7c0.png">

</details>
