### ISSUE TITLE
[Desktop] `Manage Your wallet` modal popup not removed after resetting rewards via `Reset Brave Rewards data...` 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11474]
## Description 

`Manage Your wallet` modal popup not removed after resetting rewards via `Reset Brave Rewards data...` 

## Steps to Reproduce

   1. Clean profile 1.13.x and enable rewards
   2. Navigate to `brave://settings/clearBrowserData`
   3. Click on `Reset Brave Rewards data...` link
   4. `Manage Your wallet` popup is displayed
   5. Reset the wallet by clicking on Reset
   6. Once the rewards is reset, Rewards login screen is displayed
   7. Click on `YES, I'M IN!` 
   8. `Manage Your wallet` modal popup is not removed

**Note**: In step 7 itself the URL remained as `brave://rewards/#manage-wallet` and it won't change even after enabling rewards.
## Actual result:

`Manage Your wallet` modal popup not removed after resetting rewards via `Reset Brave Rewards data...` 

![image](https://user-images.githubusercontent.com/38657976/91451034-9b84ca00-e89a-11ea-80b5-823dafb9f2a9.png)

Rewards reset via brave://rewards Gear icon  - Working fine as it redirects to correct URL
![image](https://user-images.githubusercontent.com/38657976/91451562-2d8cd280-e89b-11ea-81e1-b2feb7054427.png)
## Expected result:
After rewards reset, the URL should change to brave://rewards which will remove the Manager your wallet popup model

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by Miyayes** [comment]
@GeetaSarvadnya Is this still relevant as of Nov 2021?

**Comment by GeetaSarvadnya** [comment]
@Miyayes The issue is still reproducible in `1.42.86`. The URL remained as brave://rewards/#manage-wallet and it won't change even after enabling rewards.

```

Brave | 1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
![reset rewards](https://user-images.githubusercontent.com/38657976/182760893-ed55e426-ddac-40c3-ad39-57d9c17624d8.gif)
