### ISSUE TITLE
`Next payment date` is changed to an incorrect date after rewards reset

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11478]
## Description 

`Next payment date` is changed to an incorrect date after rewards reset
## Steps to Reproduce

   1. Clean profile 1.13.x
   2. Enable rewards
   3. Ensure that `Next payment date` is displayed as `Sep 6`
   4. Reset Rewards via brave://rewards Gear icon
   5. Opt into rewards again by clicking on `YES, I'M IN!`
   5. `Next payment date` changed to `Oct 6`

## Actual result:

`Next payment date` is changed to an incorrect date after rewards reset

![Rewards reset makes next payment date change](https://user-images.githubusercontent.com/38657976/91467614-6edaad80-e8ae-11ea-84da-a38f41d9df0f.gif)

Before rewards reset:
![image](https://user-images.githubusercontent.com/38657976/91464901-b8c19480-e8aa-11ea-9ea5-a763d8098200.png)

After rewards reset:
![image](https://user-images.githubusercontent.com/38657976/91464342-1acdca00-e8aa-11ea-8c59-9a956ee7676f.png)

## Expected result:
`Next payment date` should not change after rewards reset

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @rebron

**Comment by rebron** [comment]
cc: @jsecretan Can you help with prioritizing this one? I remember there's other related work around this.

**Comment by tmancey** [comment]
@jsecretan moved to icebox as date is correctly shown once an ad has been viewed

**Comment by tmancey** [comment]
@GeetaSarvadnya Unable to reproduce, can you please retest on 1.20.x

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)

```
- Verified the STR from the description and ensured that `Next payment date` in the Ads panel remained unchanged after rewards reset
