### ISSUE TITLE
[Desktop] Remove bind_util

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11471]
Bind util was created as we didn't know how to handle mojo pointers. Now we have a way with shared pointers. You can see example here https://github.com/brave/brave-core/blob/d3487abc76a2760ac1614e03b6f66dd78f4d62ca/vendor/bat-native-ledger/src/bat/ledger/internal/promotion/promotion.cc#L179

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.15.56 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
Revision	ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6548

<details>
<summary>Confirmed able to claim promotion (UGP grant on staging) via panel, NTP widget, and brave://rewards page</summary>

<img width="1199" alt="ss1" src="https://user-images.githubusercontent.com/28145373/93881595-1fb94a00-fcad-11ea-88d6-3de4bf3d490a.png">

<img width="390" alt="ss2" src="https://user-images.githubusercontent.com/28145373/93881588-1cbe5980-fcad-11ea-9995-9dc124f0a30a.png">

</details>

<details>
<summary>Confirmed brave://rewards-internals showed promotion data as expected for above UGP grant</summary>

<img width="1197" alt="ss8" src="https://user-images.githubusercontent.com/28145373/93881654-2fd12980-fcad-11ea-8c34-2181b150cb57.png">

</details>

<details>
<summary>Confirmed able to do 1 time tips, recurring tips, and AC using promotion</summary>

<img width="405" alt="ss3" src="https://user-images.githubusercontent.com/28145373/93881699-40819f80-fcad-11ea-9c6c-db70611b41ba.png">
<img width="950" alt="ss4" src="https://user-images.githubusercontent.com/28145373/93881712-45deea00-fcad-11ea-9b19-bc29dcaae86f.png">
<img width="943" alt="ss5" src="https://user-images.githubusercontent.com/28145373/93881723-48d9da80-fcad-11ea-987f-99ddc4c9d04f.png">
<img width="955" alt="ss6" src="https://user-images.githubusercontent.com/28145373/93881728-4aa39e00-fcad-11ea-8237-0ab9162186f2.png">
<img width="937" alt="ss7" src="https://user-images.githubusercontent.com/28145373/93881736-4d05f800-fcad-11ea-84b5-b80226c2f6b9.png">

</details>

<details>
<summary>Confirmed brave://rewards-internals showed data from above contributions (1 time tips, recurring tips, AC) as expected</summary>

<img width="1193" alt="ss9" src="https://user-images.githubusercontent.com/28145373/93881788-5d1dd780-fcad-11ea-8779-3eb1a7196807.png">

</details>

<details>
<summary>Confirmed able to restore a wallet with waiting ad grant and then confirmed I could claim that ad grant</summary>

<img width="1196" alt="ss10" src="https://user-images.githubusercontent.com/28145373/93881847-7161d480-fcad-11ea-852c-6bba89981070.png">
<img width="1192" alt="ss11" src="https://user-images.githubusercontent.com/28145373/93881861-73c42e80-fcad-11ea-9701-44df7c20b483.png">
<img width="1194" alt="ss12" src="https://user-images.githubusercontent.com/28145373/93881876-76bf1f00-fcad-11ea-93d1-cc552baedab2.png">

</details>

-------------
