### ISSUE TITLE
[Android] Clearing browsing data on exit

### ISSUE THREAD

**Issue by silvershadowcc** [brave/brave-browser#11479]
When I use a privacy friendly browser I expect to have the option not to have my browsing history saved. It is possible in the desktop browser, but the app is lacking the feature to clear browsing data on exit.

**Desktop**
![2020-08-27_181252](https://user-images.githubusercontent.com/36823114/91468006-aa1ab380-e891-11ea-8e00-ac60bec7fed0.png)

**Comment by srirambv** [comment]
Dupe of #7487
