### ISSUE TITLE
[Desktop][CW] Gemini widget displayed in unsupported region(s)

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#11483]
## Description 
The new Gemini widget is shown to French and German users, however the Gemini service is not currently available in France or Germany.

## Brave version (brave://version info)
1.13.82

**Comment by bsclifton** [comment]
cc: @ryanml @bbondy

**Comment by jonathansampson** [comment]
For a list of which regions ARE supported, refer to https://gemini.com/areas-of-availability

```json
[
    {
        "region": "North America",
        "parts": [
            "Alabama",
            "Alaska",
            "Arizona",
            "Arkansas",
            "Bermuda",
            "British Virgin Islands",
            "California",
            "Canada",
            "Cayman Islands",
            "Colorado",
            "Connecticut",
            "Delaware",
            "Florida",
            "Georgia",
            "Hawaii",
            "Idaho",
            "Illinois",
            "Indiana",
            "Iowa",
            "Kansas",
            "Kentucky",
            "Louisiana",
            "Maine",
            "Maryland",
            "Massachusetts",
            "Michigan",
            "Minnesota",
            "Mississippi",
            "Missouri",
            "Montana",
            "Nebraska",
            "Nevada",
            "New Hampshire",
            "New Jersey",
            "New Mexico",
            "New York",
            "North Carolina",
            "North Dakota",
            "Ohio",
            "Oklahoma",
            "Oregon",
            "Pennsylvania",
            "Puerto Rico",
            "Rhode Island",
            "South Carolina",
            "South Dakota",
            "Tennessee",
            "Texas",
            "Utah",
            "Vermont",
            "Virginia",
            "Washington",
            "Washington D.C.",
            "West Virginia",
            "Wisconsin",
            "Wyoming"
        ]
    },
    {
        "region": "South America",
        "parts": [
            "Argentina",
            "Brazil",
            "Chile",
            "Peru"
        ]
    },
    {
        "region": "Europe",
        "parts": [
            "Austria",
            "Belgium",
            "Bulgaria",
            "Croatia",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Estonia",
            "Finland",
            "Gibraltar",
            "Greece",
            "Hungary",
            "Iceland",
            "Ireland",
            "Italy",
            "Jersey",
            "Latvia",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Malta",
            "Netherlands",
            "Norway",
            "Poland",
            "Portugal",
            "Romania",
            "Slovakia",
            "Slovenia",
            "Spain",
            "Sweden",
            "Switzerland",
            "United Kingdom"
        ]
    },
    {
        "region": "Asia",
        "parts": [
            "Hong Kong",
            "India",
            "Israel",
            "Myanmar",
            "Philippines",
            "Singapore",
            "South Korea",
            "Taiwan",
            "Turkey",
            "Vietnam"
        ]
    },
    {
        "region": "Australia",
        "parts": [
            "Australia",
            "New Zealand"
        ]
    },
    {
        "region": "Africa",
        "parts": [
            "Egypt",
            "Nigeria",
            "South Africa"
        ]
    }
]
```

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-Bit)
-- | --
Revision | `ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}`
OS | Linux

- Verified Gemini widget is removed from NTP on clean install
- Verified Gemini widget is not listed in add more cards under dashboard settings
- Logged follow up issue #11649 for listing Gemini in New Tab Page settings for unsupported regions

**French**

New Tab widget list | Dashboard setting 
-- | --
<img width="1056" alt="Screenshot 2020-09-10 at 8 22 14 a m" src="https://user-images.githubusercontent.com/17010094/92697389-e4dc1b80-f368-11ea-9cc1-281390a620b5.png"> | <img width="1056" alt="Screenshot 2020-09-10 at 8 22 38 a m" src="https://user-images.githubusercontent.com/17010094/92697407-eb6a9300-f368-11ea-9881-9b63aa6e7895.png">

**German**
New Tab widget list | Dashboard setting 
-- | --
<img width="1056" alt="Screenshot 2020-09-10 at 8 37 07 a m" src="https://user-images.githubusercontent.com/17010094/92697451-fcb39f80-f368-11ea-8a63-05273242bda3.png"> | <img width="1056" alt="Screenshot 2020-09-10 at 8 37 12 a m" src="https://user-images.githubusercontent.com/17010094/92697475-03daad80-f369-11ea-8230-39e1423fd296.png">

--------

Verification passed on 

Brave | 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-Bit)
-- | --
Revision | `ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)

- Verified Gemini widget is removed from NTP on clean install
- Verified Gemini widget is not listed in add more cards under dashboard settings
- Logged follow up issue #11649 for listing Gemini in New Tab Page settings for unsupported regions

**French**

New Tab widget list | Dashboard setting 
-- | --
<img width="1043" alt="Screenshot 2020-09-10 at 8 42 15 a m" src="https://user-images.githubusercontent.com/17010094/92697716-3ab0c380-f369-11ea-803e-61e080e81e10.png"> | <img width="1043" alt="Screenshot 2020-09-10 at 8 42 20 a m" src="https://user-images.githubusercontent.com/17010094/92697754-43a19500-f369-11ea-9179-5870f29bde30.png">

**German**
New Tab widget list | Dashboard setting 
-- | --
<img width="1043" alt="Screenshot 2020-09-10 at 8 49 30 a m" src="https://user-images.githubusercontent.com/17010094/92697549-1523ba00-f369-11ea-8896-fbd904575897.png"> | <img width="1043" alt="Screenshot 2020-09-10 at 8 49 34 a m" src="https://user-images.githubusercontent.com/17010094/92697617-2240a900-f369-11ea-8ca6-e4ae420d0370.png">
