### ISSUE TITLE
Changing Brave Ads Setting Stops the Ads

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#11481]
## Description 

If we change any settings in Brave Rewards section like Disable/Enable ads and changing the Maximum number of ads displayed option, it stops the ad. 
Tested with Linux, windows and android.
All are syncing with same brave v2 sync chain.
All are connected with same uphold verified account.
In windows 10 i have notifications enabled and focus assist disabled.
Tested with https://www.bennish.net/web-notifications.html and notifications are working.

Brave installed in my 5 devices. 
1 in android mobile, 
1 in Windows10 and 1 in Ubuntu Linux (Dual boot in same laptop),
1 in Windows7 PC.
Another 1 in Another windows 10 PC

Totally five brave installations. All are getting ads before this problem. 

After releasing sync V2,  i setup the sync in 4 devices with the same sync chain. ( except the Windows 7 PC)

First i changed "Maximum number of ads" and ads disable and enable in android after that my ads are not working. I am not getting any ads. i also tried VPN, Stop brave from Background, Restart mobile, Open Brave. Try Brave rewards ON and OFF. Try Brave ads ON and OFF, Several mobile restart. But no use. In this process i found this https://github.com/brave/brave-browser/issues/11421

After some time i changed some ads setting in my single OS windows 10 PC. Same result. not getting ads.

This time i want to test it. So in my Ubuntu 20.04 Linux PC (dual boot with windows 10) i just changed "Maximum number of ads displayed" (not know the exact option but i think its 2 to 5 ads) option and Disable/Enable ads in rewards. After that i didn't get any ads for last 3-4 days. But the dual boot windows 10 on same machine getting the ads. Also my windows 7 PC getting ads. Using same internet connection without any VPN. Location: India

I removed my windows 10 pc and Linux pc from sync but still no ads.

## Steps to Reproduce

   1. In working ads system browser change the Maximum number of ads to some other value and disable and re enable the ads and also rewards options.
   2. Restart browser

## Actual result:

 Brave Ads are not displayed

## Expected result:
 Brave should display Ads.

## Reproduces how often: 

always

## Desktop Brave version:

Brave Linux:

Brave version (brave://version info)

Brave	1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
Revision	c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
OS	Linux
JavaScript	V8 8.4.371.23
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

-----
Windows

Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
-- | --
Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
OS | Windows 10 OS Version 2004 (Build 19041.450)
JavaScript | V8 8.4.371.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:6.0.1

## Version/Channel Information:

Brave 1.12.113, Chromium 84.0.4147.125
![WhatsApp Image 2020-08-27 at 1 48 23 PM](https://user-images.githubusercontent.com/46480489/91475058-ababa200-e8b8-11ea-90ea-e13c27603fd6.jpeg)

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? Not tested 

## Windows 10

![Annotation 2020-08-27 215130](https://user-images.githubusercontent.com/46480489/91475407-2a084400-e8b9-11ea-913c-d23a46789201.jpg)

Some not shown: logs

[Aug 23, 2020, 9:44:02.3 AM:INFO:ads_impl.cc(1003)] Ad notification not shown: Media playing in browser
[Aug 27, 2020, 9:48:09.4 PM:INFO:ads_impl.cc(1003)] Ad notification not shown: No eligible ads found
[Aug 27, 2020, 9:57:48.1 PM:INFO:ads_impl.cc(1003)] Ad notification not shown: Not in foreground

## Linux (Ubuntu 20.04.1)

![Screenshot from 2020-08-27 13-08-05](https://user-images.githubusercontent.com/46480489/91475612-72276680-e8b9-11ea-9acd-b8bd277c2153.png)
![Screenshot from 2020-08-27 13-11-40](https://user-images.githubusercontent.com/46480489/91475617-73f12a00-e8b9-11ea-9e87-b467abc21087.png)
![Screenshot from 2020-08-27 13-11-58](https://user-images.githubusercontent.com/46480489/91475620-75baed80-e8b9-11ea-9b5a-6df5446ab48d.png)

Some not shown: logs

[25 Aug 2020, 3:09:18.7 pm:INFO:ads_impl.cc(1003)] Ad notification not shown: No eligible ads found
[27 Aug 2020, 11:11:00.5 am:INFO:ads_impl.cc(1003)] Ad notification not shown: Not in foreground
27 Aug 2020, 12:29:59.9 pm:INFO:ads_impl.cc(1003)] Ad notification not shown: Media playing in browser
[27 Aug 2020, 12:36:02.2 pm:INFO:ads_impl.cc(1003)] Ad notification not shown: Media playing in browser

## Android

![WhatsApp Image 2020-08-27 at 1 26 55 PM](https://user-images.githubusercontent.com/46480489/91475706-9aaf6080-e8b9-11ea-9561-f014de0549c5.jpeg)
![WhatsApp Image 2020-08-27 at 1 27 28 PM](https://user-images.githubusercontent.com/46480489/91475714-9d11ba80-e8b9-11ea-8091-b32658e3b06c.jpeg)

**Comment by tmancey** [comment]
Please update to 1.13.x which should resolve this issue. Thank you
