### ISSUE TITLE
[Desktop] Follow up of #6259 -Backup notification is NOT shown for non-verified profiles

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11482]
## Description 

Follow up of #6259 -Backup notification is NOT shown for non-verified profiles
## Steps to Reproduce

   1. Follow steps from - Case 1 from the test plan https://github.com/brave/brave-core/pull/6344
   2. After browser restart backup notification is NOT shown.
  

## Actual result:

After browser restart backup notification is NOT shown.

## Expected result:
As per case 1, after browser restart backup notification should be shown.

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.14.66 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @zenparsing @NejcZdovc

**Comment by zenparsing** [comment]
I was unable to reproduce on master.

Here's a screenshot of the "rewards" portion of the Preferences file after editing:

<img width="470" alt="Screen Shot 2020-08-31 at 2 18 14 PM" src="https://user-images.githubusercontent.com/5995084/91752860-fb2dee80-eb94-11ea-931e-869d3e5424ca.png">

After restarting the browser and waiting 5 seconds, the notification "dot" appeared on the BAT badge.

**Comment by LaurenWags** [comment]
@GeetaSarvadnya could you give this one another try when you get a chance? I tried with below version and placement according to @zenparsing screenshot in https://github.com/brave/brave-browser/issues/11482#issuecomment-683946964 and this worked for me. 


Brave | 1.14.72 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)

**Comment by GeetaSarvadnya** [comment]
Backup notification is shown, there was a mistake while editing the preference file. Thanks, @zenparsing @LaurenWags. 

![image](https://user-images.githubusercontent.com/38657976/92217298-27a77a80-eeb5-11ea-86e9-e2f13cbbc369.png)
