### ISSUE TITLE
[Android] Allow regular Import/Export option for bookmarks outside of Sync 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#11485]
## Description 
_This issue was originally created a couple years ago (#150) but I felt requires a bit of a bump and update given how frequently it's requested._

**Many users are "blocked" from switching over to Brave due to the inability to import their browsing data** (any/call data, but primary concern seems to be bookmarks) **into Brave from another browser.** Many users have several years worth of [bookmarks] saved (a la @rebron's 2000+ bookmarks from 2011 - present!) and manually re-entering/saving all this data is unrealistic. **This option allows users to try/switch over to Brave without having to sacrifice their data** - which, after import, can now be Synced across all their devices.

**The ability to export bookmarks/browsing data also solves the issue of "backing up" your data as well** - something Brave Sync doesn't offer. This is _particularly_ relevant when un/re-installing the app: 
- If Brave is uninstalled, all associated data is cleared along with it. This can be frustrating for users who have important [bookmarks, passwords, etc] saved to Brave but either had to or tried  (unknowingly) uninstalling the app to fix an issue, change devices, or any other relevant reason. 
- Giving users the option to export their data to an HTML file (most likely) **ensures that their data is not lost should they need or want to uninstall or move the app on their device.**

### Additional Notes
Just for frame of reference - _Several_ popular web browsers already offer this option, including
- Firefox
- Vivaldi
- Opera
- Kiwi
- And even Dolphin

**Comment by Sujan319** [comment]
To do this,there should be a export options in chrome/target browser from which bookmarks/password can be export to a file.Now,chrome only exports password on android with sites name in a html file.So,if Brave implement a html importer ,password import still possible.that will work too for braves password export & import.however,for bookmarks export from brave to brave is possible by doing same.that bookmark import/export feature already in bromite browser.credits to @csagan5 main devloper of bromite for implementing this feature.So,brave can use this patch since bromite is also open source.

**Comment by srirambv** [comment]
@Brave-Matt the issue is on the current browser repo itself so no need to move it. 

cc: @SergeyZhukovsky @anthonypkeane @bbondy to get the priority for this issue

**Comment by srirambv** [comment]
https://github.com/brave/brave-browser/issues/6378 was initally logged linking issues from the older repo. NOt sure when this issue got moved from old repo to new one

**Comment by SergeyZhukovsky** [comment]
@Brave-Matt @srirambv @anthonypkeane I just want to say that fact:
1. Most of users on Android are on Chrome as it is a pre installed system app there and there is no way to export from it but only having a desktop and syncing there and Export there to a file.
2. If a user has a desktop doing #1, it's the same way to sync to Brave. You import to Brave from the exported file in Chrome and sync Brave desktop with Brave Android, that's it.

Does anyone know a way how to export Chrome's bookmarks for mobile only users?

**Comment by Sujan319** [comment]
@SergeyZhukovsky here is the thing,you are seeing one perspective i.e importing from chrome.importing bookmark not possible on android but password import still possible coz there is a export options on password section on chrome.
  Here is another perspective .assuming we have no tablet,no PC (like i haven't)and lets say we are using brave android and have bookmarks & passwords in it.Sometimes there are bugs with browser ,so to get rid of that  we clear the whole app data or reinstall it from play store or changing to a new android device .then how can i get those bookmark & passwords back??
So ,if the offline import/export (both bookmarks & password)were there ,we easily import it then.

**Comment by Brave-Matt** [comment]
@SergeyZhukovsky,
I understand what you're saying and that's an okay _workaround_ but it's also an insane amount of work/steps just for a user to _export their bookmarks_. If you list it out, a user wanting to import their bookmarks from Chrome:

1. On Chrome for Android, ensure you've Synced your data so that you can view it on Chrome desktop.
2. Export your bookmarks via HTML from Chrome desktop.
3. Import those bookmarks into Brave as HTML
4. Setup Sync chain between your Desktop and Android device
   - Start a Sync chain on Desktop
   - Open Brave on your Android device
   - Scan the code to Sync your bookmarks/data between Brave on Desktop and the mobile version

I'm still not sure why we can't offer users the option to import bookmarks as HTML into the Android application.

**Comment by Brave-Matt** [comment]
Another report/good example here:
https://community.brave.com/t/do-you-have-export-inport-feature-please/218272

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/what-is-it-that-syncs-with-android-version/250299/8?u=mattches

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/no-option-to-import-export-bookmarks-in-drop-down-menu/275218

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/import-and-export/381138/6

**Comment by cazmatronic** [comment]
+1 from me. I don't have the option on the Brave browser or on the Android app.

**Comment by chris122380** [comment]
The backing up and restoring of bookmarks (especially on mobile) are very important especially when too many times the sync token is expiring. Brave also says that sync isn't meant to be a backup solution. So we need a backup solution for mobile. To argue this can't be done when quite a few chromium-based browsers already allow it, is a poor programming excuse.

Kiwi Browser
![Screenshot_2022-10-26-22-56-14-10_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/2205798/198195827-75261cca-fd62-4836-9c1a-d2d34f666db0.jpg)

Bromite Browser
![Screenshot_2022-10-26-22-58-37-10_ed7821ed99ee442dec4ede205e7971d6](https://user-images.githubusercontent.com/2205798/198195867-9c5977bf-0a8f-4bb7-a6b4-c0bc5ce4b2ad.jpg)

**Comment by SergeyZhukovsky** [comment]
@chris122380 please point where it's been said that it's impossible to do via a file? The discussion that there is no way to pull them automatically from Chrome as you have to be logged in in your account and do it from a special website. I described details here https://github.com/brave/brave-browser/issues/6378#issuecomment-984685354.
I'm going to close this issue in favour of https://github.com/brave/brave-browser/issues/6378 which we are going to work very soon.

**Comment by ballo** [comment]
Why was this closed? I still can't import

**Comment by chris122380** [comment]
> Why was this closed? I still can't import

What happens when you go into bookmarks, click the menu dots, and click on Import Bookmarks? I use Brave sync on Brave stable so I can't test it there but I have confirmed this is Working in Brave beta. 

 When a feature is there and working the developers will usually close the GitHub request. If there are bugs or other issues after the feature request has been completed then you should go through the normal support channels or create a new GitHub bug report with the details of the issue.

**Comment by ballo** [comment]
> > Why was this closed? I still can't import
> 
> What happens when you go into bookmarks, click the menu dots, and click on Import Bookmarks? I use Brave sync on Brave stable so I can't test it there but I have confirmed this is Working in Brave beta.
> 
> When a feature is there and working the developers will usually close the GitHub request. If there are bugs or other issues after the feature request has been completed then you should go through the normal support channels or create a new GitHub bug report with the details of the issue.

Oh, my bad, dude. I couldn't give a flying rat's ass about bookmarks. I can't import passwords
