### ISSUE TITLE
[Desktop] webtorrent redirects security issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#11487]
https://hackerone.com/reports/968328

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.6 x64` using the following build:

```
Brave | 1.15.55 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | macOS Version 10.15.6 (Build 19G73)
```

Reproduced the original issue using `1.14.81 C: 85.R0.4183.102` as per the following:

| Original Issue Reproduced | Original Issue Reproduced |
| :-------------------------: | :-------------------------: |
| <img width="1238" alt="Screen Shot 2020-09-17 at 3 51 41 PM" src="https://user-images.githubusercontent.com/2602313/93521369-f8096100-f8fd-11ea-991e-4272f0d33637.png"> | <img width="742" alt="Screen Shot 2020-09-17 at 3 51 34 PM" src="https://user-images.githubusercontent.com/2602313/93521384-fd66ab80-f8fd-11ea-9a54-48e74436108f.png"> |

* Verified that I couldn't reproduce the original issue using the STR/Cases outlined via https://github.com/brave/brave-core/pull/6523#issue-474996339 with `1.15.55 CR: 85.0.4183.102`.
