### ISSUE TITLE
[Desktop] Can't update Brave Browser unless I go into Windows Safe Mode

### ISSUE THREAD

**Issue by AsadAlrafidain** [brave/brave-browser#11499]
when trying to update brave normally, I'm presented with the following error:

An error occurred while checking for updates: Update check failed to start (error code 4: 0x80070005 -- system level)

only solution that worked is booting into safe mode with networking and updating from there

Windows 10 64 bit
Brave Browser  Version 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
@AsadAlrafidain thanks for the report- we've seen some similar errors which we're looking to help resolve by updating our version of Omaha client (captured with https://github.com/brave/brave-browser/issues/5186)

One work-around you can try would be to download/install Brave from brave.com/download on top of your existing install. You won't lose anything and it might repair permissions / registry / executables if there are any problems

**Comment by rebron** [comment]
@AsadAlrafidain Are you still having issues updating? We updated our backend (Omaha client) with #5186 and with our latest release in 1.15.72. This should be fixed now. Let us know if you're still having issues updating.

**Comment by AsadAlrafidain** [comment]
@rebron It seems the issue is fixed.
Sorry it took me so long to reply

**Comment by AsadAlrafidain** [comment]
@rebron 
update: when I try to update I get this message:
"An error occurred while checking for updates: Update check failed to start (error code 4: 0x80070005 -- system level)"

requesting a re-opening of the issue

**Comment by CitizenDev** [comment]
@rebron reopen, issue still persist

**Comment by CitizenDev** [comment]
Still issue as of 1.91
