### ISSUE TITLE
[Desktop] I see no way to change the Ethereum account connected a site

### ISSUE THREAD

**Issue by vporton** [brave/brave-browser#11491]
I connected a wrong account to a site.

Now I see no way to change the account connected to this site.

Is it possible? Even if yes, the UI need to be more understandable.

**Comment by srirambv** [comment]
On `brave://wallet` you should be able to see connected sites via the account menu 
![image](https://user-images.githubusercontent.com/17010094/91555297-a7b76880-e928-11ea-9c26-ea68ef0a415b.png)![image](https://user-images.githubusercontent.com/17010094/91555360-c9b0eb00-e928-11ea-8a21-beee580028f6.png)

You should be able to disconnect the sites via browser action button itself 
![image](https://user-images.githubusercontent.com/17010094/91555210-7b9be780-e928-11ea-9c1e-60223cacce95.png)
