### ISSUE TITLE
[Desktop] Follow up of #3650 - Unable to authenticate or use Google Keep extension in Brave

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11493]
## Description 

 Follow up of #3650 - Unable to authenticate or use Google Keep extension in Brave

Once the extension is installed and added to brave, google sign-in page is displayed, the user can easily authenticate/sign-in using google credentials successfully. But, after adding google keep extension to brave in a clean profile, if we open the Brave.com website and then try Sign-In via extension bubble is failing. The Sign-In button becomes unresponsive in the extension bubble. Ideally, the user should be able to authenticate from both places.

## Steps to Reproduce

   1. Clean profile 1.14.x
   2. Navigate to https://chrome.google.com/webstore/detail/google-keep-chrome-extens/lpcaedmchfhocbbapmcbpinfpgnhiddi to install the google-keep extension
   3. Once the extension is installed google sign-in page is displayed - ignore the sign in from this page
   4. Open a `brave.com` in a new tab
   5. Click on the extension bubble and click on `google-keep extension`
   6. Click on `Sign in` for `google-keep extension`
   7. Sign-in button is unresponsive.

**Note**: It behaves the same in chrome also. Please close the issue if it's expected.

## Actual result:

Sign-in button is unresponsive.
![image](https://user-images.githubusercontent.com/38657976/91553724-81ef8b00-e94b-11ea-8ed8-68fdab677dfa.png)

## Expected result:
User should be able Sign-in google keep extension via extension bubble

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.14.66 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes - cannot authenticate- there is no google sign in after installing the extension, unable to sign via extension bubble either (user cannot authenticate extension)
- Can you reproduce this issue with the beta channel? Yes, user can authenticate using google account after installing the extension, but unable to authenticate via extension bubble
- Can you reproduce this issue with the nightly channel? Yes, user can authenticate using google account after installing the extension, but unable to authenticate via extension bubble

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? Yes - the behavior is the same in chrome also

## Miscellaneous Information:

cc: @brave/legacy_qa @jumde @rebron 

@jumde It behaves the same in chrome also, But in the issue description https://github.com/brave/brave-browser/issues/3650#issue-419242943 the expected result is Sign in button should not be unresponsive. Please close the issue if it's expected.

**Comment by bsclifton** [comment]
Closing as `wontfix`. We won't be able to implement first party APIs required for this
