### ISSUE TITLE
[Android] Disable `Offer to translate pages in other languages`

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#11496]
## Description 
We need to disable option `Offer to translate pages in other languages` as it never worked.
Additional discussion here https://bravesoftware.slack.com/archives/C0816QH3R/p1598518946070600

## Steps to reproduce 

   1. There an option in `Languages` section

## Actual result 
There is an option

## Expected result
No option

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan: just check that there is no such option in `Languages` setting

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.15.54 x64 Beta build
- Verified option is removed from language settings 

1.14.83 | 1.15.54
-- | --
![image](https://user-images.githubusercontent.com/17010094/93734965-33907d80-fbd3-11ea-8b08-9d7dd15642bd.png) | ![image](https://user-images.githubusercontent.com/17010094/93734961-2ecbc980-fbd3-11ea-9d43-e50e89dbbe6e.png)

**Comment by kvimbi** [comment]
Guess who's back.
The option disappeared and translate this page is again showing up on pages

![Screenshot_20221030-065017_Brave](https://user-images.githubusercontent.com/4610991/198864568-16e94aaa-4c3c-49fa-a4e0-8b100c34f638.jpg)
![Screenshot_20221030-064923_Brave](https://user-images.githubusercontent.com/4610991/198864573-9c3f28ad-4be2-4ed4-8a1a-98d4b54cdd8d.jpg)
