### ISSUE TITLE
Would you please work on a 32bit linux release

### ISSUE THREAD

**Issue by Tcll** [brave/brave-browser#11498]
I've installed Void Linux on my 32bit machines just so they could have more life and I could actually do some (server/network related) work on them...
but the only no longer secure browser I can install on them is Opera...

you guys are ahead of Vivaldi in that you have portable zip releases that actually work
but I'm not sure how well your engine can compete with Opera or Vivaldi's content blockers
(Opera HAS security, but it's pretty much useless since they became Google2)
I mainly use Vivaldi because I was an Opera 12 user back in the day (same developers), and the security they had back then was superior to just about anything else.

I would hope not to have to use Firefox as that's not as secure as any of the browsers mentioned here (excluding Chinese Opera)

**Comment by srirambv** [comment]
32bit support for Linux won't be available. Marking as wontfix.
