### ISSUE TITLE
[Desktop] Favicon caching

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#11506]
https://github.com/brave/internal/issues/716

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.6 x64` using the following build:

```
Brave | 1.15.55 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | macOS Version 10.15.6 (Build 19G73)
```

* Verified via https://github.com/brave/internal/issues/716#issuecomment-694490747.
