### ISSUE TITLE
Excessive CPU usage on https://www.logos.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#11505]
## Description 
CPU usage increases on https://www.logos.com/

## Steps to Reproduce

   1. Open `https://www.logos.com/`
   2. Wait 10-20 seconds, watching task manager
   3. Task manager will show high usage (see screenshot below)

## Actual result:

![logos](https://user-images.githubusercontent.com/1659004/91622304-946cd180-e9ea-11ea-8cfd-3c6c77a82ad9.png)
![taskm](https://user-images.githubusercontent.com/1659004/91647537-f6dbd580-eaaf-11ea-99f8-25a7da262606.png)

## Expected result:
CPU shouldn't be max'd out.

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
`Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
From my debugging, issue is coming from `livehelpnow.net`.  Manually aborting this script with `logos.com##+js(acis, lhnJsSdkInit)`  will stop cpu excessive usage. 

       <div class="cms-content" id="366270"><script type="text/javascript">
	window.lhnJsSdkInit = function () {
		lhnJsSdk.setup = {`
			application_id: "8cf8180a-5f50-4c57-8a69-8b6e19707db2",
			application_secret: "a2f25e77fbfd4a628504e270c4164083d02a24dd629644a688"
		};
		lhnJsSdk.controls = [{
			type: "hoc",
			id: "35b74855-6a6d-4488-833c-a1f96367e20c"
		}];
	  };

	(function (d, s) {
		var newjs, lhnjs = d.getElementsByTagName(s)[0];
		newjs = d.createElement(s);
		newjs.src = "https://developer.livehelpnow.net/js/sdk/lhn-jssdk-current.min.js";
		lhnjs.parentNode.insertBefore(newjs, lhnjs);
	}(document, "script"));
    </script></div>`

**Related tracking blocks (in shields):**

`https://www.livehelpnow.net/lhn/handler/e.ashx?c=8489&e=Chrome:%20Uncaught%20TypeError%3A%20Cannot%20read%20property%20%27_uid%27%20of%20undefined%20line%3A6%20column%3A4444%20%7C%20&p=https%3A%2F%2Fwww.logos.com%2F`
`https://www.livehelpnow.net/lhn/handler/e.ashx?c=8489&e=Chrome:%20Uncaught%20TypeError%3A%20Cannot%20read%20property%20%27style%27%20of%20null%20line%3A6%20column%344444&p=https%3A%2F%2Fwww.logos.com%2F`

**Comment by ryanbr** [comment]
Reaching out for support; https://twitter.com/fanboynz/status/1299493892983672833

**Comment by ryanbr** [comment]
Affects Android also.

![Screenshot_20200829-122445](https://user-images.githubusercontent.com/1659004/91624201-00ebce80-e9f3-11ea-9e89-e3c48a622754.jpg)

**Comment by ryanbr** [comment]
Reverting commit. https://github.com/easylist/easylist/commit/0d198ea55e8953ec355eb9f7937bb9a91168311d

This may help with the cpu issues. Will re-check this

**Comment by ryanbr** [comment]
CPU usage looking better, no longer spiking. Closing ticket.

**Comment by kjozwiak** [comment]
As per the process, shield issues that have been fixed by the component updater should follow the following process:

* Once closed, add the `closed/fixed-by-component-update` label
* Please don't place issues with `closed/fixed-by-component-update` into milestones
* Doesn't need QA verification
