### ISSUE TITLE
sync does not add rewards from all the devices in chain 

### ISSUE THREAD

**Issue by ShardulAswale** [brave/brave-browser#11513]
## Steps to Reproduce

   1. generate chain from desktop  
   2. scan QR code with mobile 
   3. check already earned rewards 

## Actual result:

I synced mobile and desktop in a chain but the expected rewards matched but the already earned did'nt.

## Expected result:
both already earned and expected rewards should have matched.

## Desktop Brave version:

Windows 10

## Android Device details:
   - Install type (ARM, x86): 8x ARM Cortex-A53
   - Device type (Phone, Tablet, Phablet): Xiaomi Redmi 6 pro
   - Android version: pie PKQ1.180917.001

## Version/Channel Information:

Current release regular
- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by thefallofbecause** [comment]
Rewards balance is not yet handled by sync. It is meant to be coming in a future release.
