### ISSUE TITLE
Brave Dev Requires High Perf GPU on Mac

### ISSUE THREAD

**Issue by kevinschaich** [brave/brave-browser#1151]
## Description 

Brave Dev requires the High-Performance GPU while Chrome / Safari do not. This can be a big drain on battery life.

Activity Monitor comparison:

![image](https://user-images.githubusercontent.com/9244728/45601227-7ef96b00-b9be-11e8-9534-943217bdbd1a.png)

## Expected result:

Brave should use low-energy internal GPU for rendering by default for efficiency.

## Reproduces how often: 

Every Launch

## Brave version (chrome://version info)

**Brave Dev 0.55.4**

```
Brave: 0.55.4 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)
Revision: ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS: Mac OS X
```

![image](https://user-images.githubusercontent.com/9244728/45601244-cbdd4180-b9be-11e8-83f7-34b7d385d841.png)

**Comment by kevinschaich** [comment]
Just another datapoint: disabling *Hardware acceleration* resolves this. We probably want internal GPU hardware acceleration though.

![image](https://user-images.githubusercontent.com/9244728/45796513-ec332780-bc6e-11e8-8abf-0dc63dbc00bb.png)

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

<img width="954" alt="screen shot 2018-10-15 at 5 05 51 pm" src="https://user-images.githubusercontent.com/2602313/46978320-a1a1a100-d09c-11e8-9b30-bde1fb3c4cf1.png">

**Comment by vyrgozunqk** [comment]
Brave 0.68.139 Chromium: 77.0.3865.90, still suffers from the same issue. Maybe this reappeared at some point or a compilation flag was missed.
