### ISSUE TITLE
remove login flow if in Disconnected state

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11528]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/10936

If in `Disconnected` state, we should not show the login flow per https://bravesoftware.slack.com/archives/CB0KCRCQN/p1598890358003000?thread_ts=1598888189.002000&cid=CB0KCRCQN

## Steps to Reproduce

   1. Install a version with login flow (ex. 1.14.x), enable Rewards
   2. Login with KYC'd uphold account
   3. Disconnect KYC account
   4. Click on Disconnected button

## Actual result:

See login flow

<img width="396" alt="Screen Shot 2020-08-31 at 11 33 50 AM" src="https://user-images.githubusercontent.com/28145373/91745567-24488200-eb89-11ea-9356-001cb9f3ad51.png">

When retesting should check disconnecting manually (via panel and brave://rewards) and should also check disconnecting from Uphold settings

## Expected result:
Should not see login flow per above slack thread

## Reproduces how often: 

easily

## Desktop Brave version:

Brave | 1.14.69 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.13.x yes
- Can you reproduce this issue with the beta channel? 1.14.x yes
- Can you reproduce this issue with the nightly channel? 1.15.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @brave/legacy_qa 
Included `OS/Android` tag as Android also has this functionality. Please remove if this will not be applicable to Android.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.6 x64` using the following build:

```
Brave | 1.15.55 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | macOS Version 10.15.6 (Build 19G73)
```

**`Test Case 1`**

Disconnect from rewards using `Disconnect from Brave Rewards` using either the rewards panel or `brave://rewards` and ensure that clicking on `Disconnected` button reconnects your wallet and doesn't display any login flow as per https://github.com/brave/brave-browser/issues/11528#issue-689350902

**`Test Case 2`**

Disconnect from rewards by removing `Brave Browser` from the `Authorized Applications` under Uphold which should disconnect the wallet from Brave. Go into `brave://rewards` and ensure that clicking on the `Disconnect` button  reconnects your wallet and doesn't display any login flow as per https://github.com/brave/brave-browser/issues/11528#issue-689350902

The above cases are not working for the rewards panel as the flow wasn't removed. Created https://github.com/brave/brave-browser/issues/11760 .
