### ISSUE TITLE
[Android] Notification not shown when 10mins of browsing time is saved

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11527]
## Description 
[Follow up to brave/brave-core/pull/6268] Notification not shown when 10mins of browsing time is saved 

## Steps to reproduce 

   1. Follow steps from https://github.com/brave/brave-core/pull/6268

## Actual result 
No notification shown

## Expected result
Should show notification

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.15.22

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Marking p1 as this is part of the notification feature going in the release. @bsclifton @anthonypkeane please change if you think otherwise

**Comment by kjozwiak** [comment]
Needs more investigation from @srirambv 👍 Will most likely miss `1.13.x` and get resolved in `1.14.x` unless @deeppandya can reproduce.

**Comment by srirambv** [comment]
This is working as expected. Notification is shown and clicking on it opens NTP as per spec. 
![image](https://user-images.githubusercontent.com/17010094/92084053-beddd680-edbe-11ea-892c-1a0297e1f9e8.png)

Closing as expected and moving it back to 1.13.x and marking it as verified
