### ISSUE TITLE
Brave Fails to Send Phone Number to Connected Mobile Device

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#11526]
## Description 
Brave offers to send phone numbers to a linked mobile device, but fails.

## Steps to Reproduce
1. Place your desktop device and mobile device on the same Sync chain
2. Configure Sync to share _addresses, phone numbers, and more_ in brave://sync/
3. Click a `tel:` link to invoke address-bar prompt
4. Request that the call be made from your mobile device

## Actual result:
Call is not made.

"Couldn't share number. Something went wrong. Try later."

## Expected result:
Call is made from mobile device; or user is prompted on mobile to make the call.

## Reproduces how often: 
Always.

## Desktop Brave version:
1.13.82

## Android Device details (my linked mobile device):

![image](https://user-images.githubusercontent.com/815158/91736114-d4f75700-eb72-11ea-9ade-da2f5304dda5.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the nightly channel? TBD

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? TBD
- Does the issue resolve itself when disabling Brave Rewards? TBD
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Desktop is currently set to Sync: _Bookmarks, History, Open Tabs,_ and _Addresses, Phone Numbers, and more_.
Android is currently set to Sync: _Bookmarks, History,_ and _Open Tabs_ (No option presented for _Addresses, Phone Numbers, and more_ on Android.

**Comment by KB3168** [comment]
is the same with version 1.16.68

**Comment by mattgphoto** [comment]
And version 1.13.82.

**Comment by mattgphoto** [comment]
Just to get an idea, how actively are you guys looking into this one? Just want to set my expectations correctly. :-)

**Comment by KB3168** [comment]
I have tried three times in the past two weeks

**Comment by AlexeyBarabash** [comment]
Confirming I could do that with Chrome, but cannot do with Brave.

**Comment by karthikkasturi** [comment]
Any update on a timeline for a fix for this? I am facing the same issue with my OnePlus 7T.

**Comment by raphaelcasimir** [comment]
Same issue here Xiaomi phone

**Comment by ThePastPlayer** [comment]
Same issue here too

**Comment by shashank68** [comment]
Confirming the issue.

**Comment by Haagimus** [comment]
Also having this issue and awaiting outcome.

**Comment by wsolorza** [comment]
bump

**Comment by conorseed** [comment]
Confirming the issue - Huawei P30 and Brave Version 1.20.110

**Comment by jason3w** [comment]
same with pixel 4xl.

**Comment by bsclifton** [comment]
cc: @anthonypkeane @rebron for triage

**Comment by ramboozer** [comment]
Still not working, I cannot do anything sync wise. I can not even send URL from Phone to PC or vice versa...says Please add device to sync chain (Which it is, with the sync everything option enabled)

**Comment by jparthum** [comment]
Same problem here.
V1.22.70

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.25.18 Chromium: 90.0.4430.72 (Official Build) nightly (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/8454

![image](https://user-images.githubusercontent.com/34715963/114912634-84421f00-9e20-11eb-8e7e-8da067a361b2.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.51 x64 Beta build
- Verified app switcher is shown when clicking on a call to number
![image](https://user-images.githubusercontent.com/17010094/117778865-ffd39800-b235-11eb-911e-1a95d497edf6.png) 
-----------
Verification passed on Samsung Tab A with Android 10 running 1.25.51 x64 Beta Build
- Verified switches to Phone app when clicked on a call to number

**Comment by eexit** [comment]
Hello,

This is still broken on v1.46.144. What is the solution for this?

Thanks!

**Comment by suuuunto** [comment]
Also not working for me
[Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)](https://brave.com/latest/)
Pixel 5a

**Comment by mrodus** [comment]
Still broken as of 1.48.171
