### ISSUE TITLE
[Desktop] Long term Brave user, stopped getting ads, USA

### ISSUE THREAD

**Issue by coinzdude** [brave/brave-browser#11530]
Currently on Windows 10, Version 1.15.15 Chromium: 85.0.4183.83 (Official Build) nightly (64-bit)

I update nightlies around 1 time per week.  I have not received an ad in several weeks at this point.  

Any idea why they have stopped?  Here's the activity log and settings:
![image](https://user-images.githubusercontent.com/58857646/91765099-6df39580-eba6-11ea-87c0-a726cbb60522.png)

**Comment by coinzdude** [comment]
This is still my situation. no new ads.  I have tried switching from nightly to release browser with the same result. Using Brave on a 2nd computer, Brave ads are almost immediately available.

**Comment by rebron** [comment]
cc: @tmancey @jsecretan

**Comment by rebron** [comment]
Duplicate issue? If not, can we get a prioritization on this one.

**Comment by tmancey** [comment]
@coinzdude Closing as this issue will be resolved by https://github.com/brave/brave-browser/issues/11952

**Comment by coinzdude** [comment]
@tmancey I updated nightly build to Version 1.17.24 Chromium: 86.0.4240.75 (Official Build) nightly (64-bit) .  Below are my settings.  Still no ads.

![image](https://user-images.githubusercontent.com/58857646/95619296-5f698b00-0a3c-11eb-97c7-bd3752bf0851.png)

**Comment by tmancey** [comment]
@coinzdude would you be available for a screen-share to investigate the issue please? Thanks

**Comment by coinzdude** [comment]
@tmancey yes, is there a way I can contact you in private?

**Comment by tmancey** [comment]
If you could please email me at tmancey@brave.com, I am available now if that helps? Thanks

**Comment by coinzdude** [comment]
Issue resolved, thanks!

**Comment by tmancey** [comment]
Closing issue as ads were not shown due to notifications being disabled in Windows and focus assist being enabled. Thanks
