### ISSUE TITLE
[Desktop] Unable to login to bitbucket.org

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#11532]
## Description 
Unable to login to bitbucket.org website

## Steps to Reproduce

   1. Login https://bitbucket.org/account/signin/
   2. Click on Google signin
   3. Fails to login, generates error message

## Actual result:

![atassian-error](https://user-images.githubusercontent.com/1659004/91771859-d6d71e00-ec37-11ea-9571-895a6d45bd55.png)

## Expected result:
Allow user to login

## Reproduces how often: 

Easily

## Brave version (brave://version info)
`Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Was reported. https://twitter.com/buggydebugger/status/1300426570364928000

2 Cookie issues being affected, (Bitbucket.org & atlassian.com)  and (atlassian.net & atlassian.com:)

**Comment by ryanbr** [comment]
Open `https://id.atlassian.com/`  and allowing `All cookies` in shields on this domain.  

Refresh the login process will allow the site to work correctly.  Allowing `all cookies` at the end of the process in url-bar shields isn't enough. 


The site redirects through a few urls during its signup:

First site:
`https://bitbucket.org/account/signin/?redirectCount=1&next=%2F`

Redirects too:
`https://id.atlassian.com/login?application=`

2nd redirect: 
`https://atlassian.net/SetCST?cst=`

3rd redirect:
`https://bitbucket.org/SetCST?cst=`

Back too:
`https://bitbucket.org/account/signin/?redirectCount=2&next=%2F`

**Comment by jonathansampson** [comment]
Other users are facing similar issues with Atlassian properties:
- https://twitter.com/Tripwire_Stone/status/1300880446998433796

**Comment by EvaFro** [comment]
I am also having this same problem (following the twitter post above with turning shields on and off). I can log in to  `https://id.atlassian.com/`, but as soon as I try to click into anything it sends me to that error page. I noticed that this started happening after I updated my Brave browser yesterday. So something in the last update made this change.

**Comment by carlos8alb** [comment]
![Sin título](https://user-images.githubusercontent.com/35976960/94102451-7d988e00-fe75-11ea-9ad3-5c6a39505bea.jpg)

**Comment by bsclifton** [comment]
I think all Atlassian sites have the same issue. Related issues:
- [Issues with Bitbucket site](https://github.com/brave/brave-browser/issues/2289)
- [Atlassian Cloud Not Loading](https://github.com/brave/brave-browser/issues/1503)
- [Interrupted page loads and ERR_NETWORK_CHANGED (problem with IPv6)](https://github.com/brave/brave-browser/issues/5958)
- [Third-party cookies: SessionOnly option.](https://github.com/brave/brave-browser/issues/4120)

**Comment by mdepitta** [comment]
This appears to be somehow Brave-specific?
I am experiencing the same issue.
On Firefox or Chrome, login is smooth.

**Comment by RobinBobin** [comment]
@carlos8alb's solution saved me.
