### ISSUE TITLE
Set flag when user changes monthly Auto-Contribution amount

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#1153]
## Description 
Add a flag in `ledger_state` to indicate that the user has changed the monthly Auto-Contribution amount

**Comment by NejcZdovc** [comment]
@LaurenWags with verbose mode you can see call to balance server

**Comment by LaurenWags** [comment]
@NejcZdovc thanks - looks like verbose flag issue is still open, https://github.com/brave-intl/bat-native-ledger/issues/62

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified test plan from https://github.com/brave/brave-core/pull/458

**Comment by LaurenWags** [comment]
@NejcZdovc in absence of flags, to check scenario 2 from https://github.com/brave/brave-core/pull/458, can we do this instead?
