### ISSUE TITLE
Brave nightly update issue, 0x80070005 

### ISSUE THREAD

**Issue by coinzdude** [brave/brave-browser#11531]
Windows 10, brave nightly, check for updates generates error code 0x80070005 

On another machine nightly updates fine.  Any ideas?

**Comment by bsclifton** [comment]
@coinzdude as a work-around, can you please try downloading https://brave.com/download-nightly ?

You can install on top of what you have (just close Brave first) and you won't lose anything (doesn't affect your profile)

**Comment by coinzdude** [comment]
Sure can.  Just hoping to get it to work since it's doing well on another machine.
