### ISSUE TITLE
[Desktop] Review non-registered components 

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#11544]
@bsclifton found that the root cause for https://github.com/brave/brave-browser/issues/10607#issuecomment-685186576 is that we don't register a necessary component.

It would be good to review the list of components we don't install to make sure there's nothing we should enable:

- [x] Subresource Filter Rules
- [x] Certificate Error Assistant (#13010)
- [x] Safety Tips (#12999)
- [x] File Type Policies (#6267)
- [x] Zxcvbn Data Dictionaries

Going forward, is there a way we can detect new ones and file issues for deciding what to do with them?

**Comment by fmarier** [comment]
> - File Types Policies

This is used by Safe Browsing and is a dependency of https://github.com/brave/brave-browser/issues/6267.

**Comment by jumde** [comment]
Wiki in progress: https://github.com/brave/brave-browser/wiki/Brave-Components

**Comment by jumde** [comment]
Reached out to Andrew Whalley to check if Safety Tips and Certificate Error Assistant are still being maintained.

**Comment by mherrmann** [comment]
@jumde In the wiki, are you sure Legacy TLS Deprecation Configuration should be unsupported? See https://github.com/brave/brave-browser/issues/10607#issuecomment-685186576.

**Comment by mherrmann** [comment]
Just to mention here that this is related to my PR https://github.com/brave/brave-core/pull/7164. In short: I think Brave currently relies on a bug to not install unwanted components. My PR would fix this bug. So any solution to this issue should probably not rely on the bug being there. @jumde pointed out that the correct way to prevent a component from being installed is to not register it in the first place. Eg. by overriding functions like `RegisterSafetyTipsComponent`.

**Comment by mherrmann** [comment]
Also linking #8709 here because I think it is very closely related.

**Comment by fmarier** [comment]
> @jumde In the wiki, are you sure Legacy TLS Deprecation Configuration should be unsupported? See [#10607 (comment)](https://github.com/brave/brave-browser/issues/10607#issuecomment-685186576).

Our [fix](https://github.com/brave/brave-core/pull/6574) isn't particularly obvious, but basically we replaced Chrome's list of exceptions with an empty list. So we disable TLS 1.0 and 1.1 for all sites, no exceptions. Therefore there is no need to load the component which updates Chrome's list.

**Comment by mherrmann** [comment]
> Therefore there is no need to load the component which updates Chrome's list.

Do you mean the component should not be updated, or it should not be present in Brave at all? Or does it not matter?

**Comment by fmarier** [comment]
> Do you mean the component should not be updated, or it should not be present in Brave at all? Or does it not matter?

The component is not needed at all in Brave. It doesn't need to be updated or even be present.

**Comment by mherrmann** [comment]
Got it, thank you. Who can tell us which components exactly should and shouldn't be in Brave?

**Comment by jumde** [comment]
@mherrmann - I think just installing the components with a non-zero (0.0.0.0) version number on start (in nightly) makes sense. You can enable Crowd Deny as well to resolve #10280.

**Comment by mherrmann** [comment]
Thank you @jumde. Do you mean that the answer to my question "which components should not be installed" is "those components that show up with version 0.0.0.0 when Brave is installed from scratch"?

**Comment by jumde** [comment]
Issues to track enabling:

1. Safety Tips: https://github.com/brave/brave-browser/issues/12999
2. Certificate Error Assistant: https://github.com/brave/brave-browser/issues/13010

**Comment by fmarier** [comment]
All components have been reviewed and issues have been filed.
