### ISSUE TITLE
[Android] Tabs bar missing on tablet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11549]
## Description 
Tabs bar missing on tablet

## Steps to reproduce 

   1. Clean install 1.13.83
   2. No tabs bar is shown 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/91936288-78697880-ece7-11ea-9e4a-f5b1fa9743a8.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/91936641-2f65f400-ece8-11ea-8ff4-6debe76396e4.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.13.83

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Marking as P1 as this is blocking UI. @bsclifton @anthonypkeane please change if you think otherwise

**Comment by kjozwiak** [comment]
Thanks @deeppandya 👍 Closing as this was fixed via https://github.com/brave/brave-core/pull/6569#issue-477622890.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.13.84 x64 build
- Verified tabs bar is visible
![image](https://user-images.githubusercontent.com/17010094/92098181-d45bfc00-edd0-11ea-82db-fe2c8f8d6834.png)
