### ISSUE TITLE
Block private browsing mode detection

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#11543]
A number of websites use the `navigator.storage.estimate()` API to detect users in private browsing mode. That API returns a hard-limited quota of 120MB in private browsing, and larger values otherwise.

This has been [proposed](https://bugs.chromium.org/p/chromium/issues/detail?id=800329) in Chromium, but appears to be a wontfix as the quota is intended to be kept fully in-memory for private browsing sessions.

There are several options here, including increasing the available quota as a temporary workaround, or simply lying about the available space (it is an _estimate_, after all!).

**Comment by fmarier** [comment]
Here's the approach that Bromite took: https://github.com/bromite/bromite/blob/master/build/patches/Hardening-against-incognito-mode-detection.patch

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.18.63 x64 beta build
- Verified test plan from https://github.com/brave/brave-core/pull/6622
- Verified only on a normal tab as its not possible to inspect private tabs on mobile

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
![oneplusinspect](https://user-images.githubusercontent.com/17010094/100424001-dc9c9e00-3084-11eb-874d-6cb7adfc9589.gif) | ![samsunginspect](https://user-images.githubusercontent.com/17010094/100424030-e7efc980-3084-11eb-80f1-33ecac80932b.gif)
