### ISSUE TITLE
[Desktop] Top site behavior seems wrong / unpredictable

### ISSUE THREAD

**Issue by TiepMesjien** [brave/brave-browser#11551]
## Test plan
See https://github.com/brave/brave-core/pull/6584

## Description
Top site pinning is still broken, doesn't do anything and get's regularly replaced by random sites, this has been an issue for well over 3 to 4 years now, on both windows 10 and linux, is it ever going to get fixed? Or has it simply been given up on?

**Comment by ikeman32** [comment]
Oh this is definitely broken but I have only just experienced any problems and posted about it in the community: 
https://community.brave.com/t/top-sites-has-a-potential-bug/159826

This started happening immediately after the last update release for Linux, before that there were no issues. What happened is that the pinned top sites completely vanished and had to be repinned as they would appear on the top sites, but they continue to randomly vanish or be replaced by an unpinned site.

**Comment by bsclifton** [comment]
Thanks for the report @ikeman32 - I'm working on a fix along with @simonhong and @petemill, which can be tracked here:
https://github.com/brave/brave-core/pull/6584

It gets rid of the need for pinning; once a site is there, it'll stay there. You can optionally switch to a "most visited" mode

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
Revision	12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS	macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/6584
Testing notes can be found under https://github.com/brave/brave-browser/issues/9457#issuecomment-712306639
Additional notes that may be helpful: there is no more pinning top site tiles with 1.17.x. Additionally, modifications to top site tiles made with 1.16.x (and before) are not retained when upgrading to 1.17.x. 

---------------
