### ISSUE TITLE
[Desktop] Follow up of #10081- Implement P2A component for private ad analytics

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11552]
## Description 

Follow up of #10081- Implement P2A component for private ad analytics

## Steps to Reproduce

**Scenario** 1:
   1. Clean profile 1.14.x launch brave using `brave.exe --args --enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/bat-native-confirmations/*"=6,"*/p3a/*"=6 --brave-ads-staging --rewards=staging=true --p3a-upload-interval-seconds=5 --p3a-rotation-interval-seconds=160`
   2. Enable rewards
   3. Open brave.com and view an Ad
   4. View console logs for `Brave.P2A.ViewConfirmationCount`
   5. Logs for P2A is displayed as `Brave.P2A.ViewConfirmationCount Sample = 2147483646 bucket = 2147483646` instead of normal P3A values like `1` or `Yes`
   6. Go to brave://local-state, and check P2A logs for `Brave.P2A.ViewConfirmationCount` - Logs are not available

**Scenario** 2:
   1. Clean profile 1.14.x launch brave using `brave.exe --args --enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/bat-native-confirmations/*"=6,"*/p3a/*"=6 --brave-ads-staging --rewards=staging=true --p3a-upload-interval-seconds=5 --p3a-rotation-interval-seconds=160`
   2. Enable rewards
   3. View console logs for `Brave.P2A.ViewConfirmationCount`
   4. Logs for P2A is displayed as `Brave.P2A.ViewConfirmationCount Sample = 2147483646 bucket = 2147483646` which is wrong because when Ads are toggled ON `Sample=2147483646 bucket = 2147483646` should not be displayed for the stat `Brave.P2A.ViewConfirmationCount` 

**Note**: Currently Case 3 and Case 4 from https://github.com/brave/brave-core/pull/5949 are not working, these should work once the above scenarios are fixed. 

## Actual result:

1. P2A logs are NOT displayed in brave://local-state
2. Logs for P2A messages are NOT displayed as expected when ads are enabled - same logs are displayed irrespective of ads state
`[17596:4380:0902/165319.145:VERBOSE2:brave_p3a_service.cc(373)] BraveP3AService::OnHistogramChanged: histogram_name = Brave.P2A.ViewConfirmationCount Sample = 2147483646 bucket = 2147483646`

## Expected result:
1. When Ads switch is ON and the ad is viewed, the response value for `Brave.P2A.ViewConfirmationCount` should be the same as P3A value
2. When Ads switch is ON logs for P2A messages `Brave.P2A.ViewConfirmationCount Sample = 2147483646 bucket = 2147483646` should not be displayed'
3. P2A logs should be shown in brave://local-state when ads is ON and ad is viewed.

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.14.71 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @moritzhaller @iefremov @jsecretan

**Comment by GeetaSarvadnya** [comment]
As per the discussion over the slack https://bravesoftware.slack.com/archives/C7VLGSR55/p1599062213168900?thread_ts=1599047533.165500&cid=C7VLGSR55 this issue is not critical hence removed release blocking label. 

@rebron please assign the milestone based on priority.
cc: @LaurenWags

**Comment by tmancey** [comment]
@moritzhaller I believe this has been resolved as part of https://github.com/brave/brave-browser/issues/11060, can you please confirm and close if this is the case. Thanks

**Comment by moritzhaller** [comment]
@tmancey yes it is, closed!
