### ISSUE TITLE
Create an interstitial page for when there are no IPFS peers

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11558]
Subset of: https://github.com/brave/brave-browser/issues/10220

# Interstitial page when there are no peers

If there are no peers but an IPFS or IPNS URL is accessed, an interstitial page (such as bad SSL certificate) will be displayed telling the user that the node doesn’t seem to be started or there are no connected peers. An option will be given on the page to use the default gateway fallback and to continue to do so automatically in the future when there are no peers.

**Comment by yrliou** [comment]
test plan specified in https://github.com/brave/brave-core/pull/6782
