### ISSUE TITLE
[Android] fix capitalization of Brave in Privacy Report setting description

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11567]
## Description 
Under Settings > Display > Privacy Report, look at the first setting. The word "brave" should be capitalized and shown as Brave instead.

## Steps to reproduce 

   1. Install 1.13.x
   2. Go to Settings
   3. Navigate to Display section and open Privacy Report.

## Actual result 
Look at first setting description
![settings](https://user-images.githubusercontent.com/28145373/92016295-25f87e00-ed20-11ea-8d80-3d69e41eafa4.png)

## Expected result
brave --> Brave

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? yes 
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
    
## Brave version
1.13.83

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `FIXED` using Brave - Nightly `1.25.46, Chromium 90.0.4430.93`, on Android 9 (Pixel Xl, arm64)

Confirmed that `Brave` is now correctly capitalized under `Settings` > `Privacy Report`

![Screenshot (Apr 28, 2021 4 43 18 PM)](https://user-images.githubusercontent.com/387249/116485886-36c2aa80-a841-11eb-9520-f97514984dd7.png)
