### ISSUE TITLE
Add a setting for which IPFS gateway to use

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11563]
Currently the user cannot change the Gateway and it is always set to https://dweb.link
We should instead allow the user to configure a different gateway.

**Comment by bbondy** [comment]
This can go in about://ipfs

**Comment by bbondy** [comment]
Putting QA/No because I'll add test cases in the master IPFS issue.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.20.87 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

Verified test plan from https://github.com/brave/brave-core/pull/7391#issue-534739631

Confirmed able to change `IPFS public gateway address` in brave://settings/extensions.
Confirmed change was reflected in settings:
<img width="706" alt="Screen Shot 2021-01-22 at 9 05 01 AM" src="https://user-images.githubusercontent.com/28145373/105500722-44d8bc00-5c91-11eb-8581-b42b245140e6.png">

Confirmed visiting ipfs:// url showed expected (gateway) URL upon navigation:
ipfs:// | Gateway
----- | -----
<img width="927" alt="Screen Shot 2021-01-22 at 9 05 18 AM" src="https://user-images.githubusercontent.com/28145373/105500809-6a65c580-5c91-11eb-89cc-f876d8a26251.png"> | <img width="911" alt="Screen Shot 2021-01-22 at 9 05 49 AM" src="https://user-images.githubusercontent.com/28145373/105500846-75b8f100-5c91-11eb-9bdb-25eaf494d68b.png">
