### ISSUE TITLE
[Desktop] Mouse Button 3 (Middle Mouse Button) click on tab bar should open new tab 

### ISSUE THREAD

**Issue by MMMMartyyyy** [brave/brave-browser#11576]
## Description 
When pressing mouse button 3 on the tab bar the browser should open a new tab.

## Actual result:
When pressing mouse button 3 on the tab bar the browser does not open a new tab.

## Expected result:
When pressing mouse button 3 on the tab bar the browser should open a new tab.

## Brave version (brave://version info)
Brave | 1.13.82 Chromium: 85.0.4183.83 (Offizieller Build) (64-Bit)
Überarbeitung | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
Betriebssystem | Windows 10 OS Version 1903 (Build 18362.1016)

**Comment by rebron** [comment]
@MMMMartyyyy Did you mean the middle mouse button? Is this working correctly with other browsers? What mouse do you have and did you program it in any special way?

**Comment by MMMMartyyyy** [comment]
@rebron Yes I meant the middle mouse button.
For example in the Firefox browser when I press the middle mouse button on the tab bar then it opens a new tab.
