### ISSUE TITLE
Filter yclid out of the query string

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#11578]
`yclid` is a [unique click tracker](https://yandex.com/support/direct/statistics/metrika.html#settings) and it is also used by Yahoo! Japan for [conversion tracking](https://ads-help.yahoo.co.jp/yahooads/ss/articledetail?lan=en&aid=20442).

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.15.63 Chromium: 86.0.4240.55 (Official Build) dev (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Ubuntu 18.04 LTS

The issues is still reproducible, it seems that the filtering does not work in general. Logged https://github.com/brave/brave-browser/issues/11924. Based on our process I mark this issue as verified.

**Comment by LaurenWags** [comment]
Marking as `release-notes/exclude` as issue still reproduces, please adjust if necessary cc @rebron

**Comment by fmarier** [comment]
> Marking as release-notes/exclude as issue still reproduces, please adjust if necessary cc @rebron

I think we can keep it because it's partially working (it does work for cross-site navigations) and the only outstanding issue is tracked in #11924 where I'm working on an uplift for early next week.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.16.69 x64 build 
- Verified test plan from https://github.com/brave/brave-core/pull/6576
- Verified all query parameter strings are removed when loading the page
- Verified typing in or copy-pasting the link removes the query params from URL
------------------
Verification passed on Samsung Tab A with Android 10 running 1.16.69 x64 build 
- Verified test plan from https://github.com/brave/brave-core/pull/6576
- Verified all query parameter strings are removed when loading the page
- Verified typing in or copy-pasting the link removes the query params from URL
