### ISSUE TITLE
[Android] Need custom layout for popover with pointing arrow

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#11574]
## Description 
Currently, the popover introducing users to Brave Shields looks like this: 

![image](https://user-images.githubusercontent.com/2388823/92022459-2557eb80-ed10-11ea-8b1d-5553b001e0cf.png)

There is no affordance of where this message is coming from so it could be misconstrued as part of the page content since it does not cover or point to the toolbar. Also, the layout is too wide for the content.

## Designs
Build a custom layout for a reusable popover UI component with a pointing arrow that can be used throughout the product to introduce users to different features.

Using motion will capture the user's attention and inform them of what to focus on first. The popover slides in as soon as the page is finished loading y-10, 0.3s with opacity:

![android shields intro](https://user-images.githubusercontent.com/2388823/81730795-e9d4a100-9442-11ea-97d4-9063915515e7.gif)

Tablet example: 

![image](https://user-images.githubusercontent.com/2388823/92022658-7536b280-ed10-11ea-9ce5-9186fd873576.png)

## Notes

Follow up to https://github.com/brave/brave-browser/issues/9555

**Comment by deeppandya** [comment]
Closing this issue as it's irrelevant
