### ISSUE TITLE
Filter out _openstat query string tracker out of URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#11579]
`_openstat` [appears to be campaign-related](https://yandex.com/support/direct/statistics/url-tags.html#url-tags__openstat-title) but when we take an example from the wild:
```
https://moscow.petrovich.ru/catalog/7198/138090/?_openstat=ZGlyZWN0LnlhbmRleC5ydTs0MDY1MTc3Mzs2OTk3NDY3MzE2O3lhbmRleC5ydTpwcmVtaXVt&yclid=7597867600238632462&utm_source=yandex&utm_medium=cpc&utm_campaign=MSK%7CDSA%7C40651773&utm_content=cid%7C40651773%7Cgid%7C3683802495%7Caid%7C6997467316%7Ckid%7C966577%7Cpos%7Cpremium1%7Cadtarget%7C%D0%A1%D1%83%D1%85%D0%B8%D0%B5%20%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5%20%D1%81%D0%BC%D0%B5%D1%81%D0%B8%20%D0%B8%20%D0%B3%D0%B8%D0%B4%D1%80%D0%BE%D0%B8%D0%B7%D0%BE%D0%BB%D1%8F%D1%86%D0%B8%D1%8F%7C%D0%93%D0%B8%D0%B4%D1%80%D0%BE%D0%B8%D0%B7%D0%BE%D0%BB%D1%8F%D1%86%D0%B8%D1%8F%7Cadtarget_id%7C966577%7Csrc%7Csearch_none%7Cdvc%7Cdesktop%7Cgoalid%7C1712089&utm_term=966577%7C%7Creg%7C%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0
```
and decode the `_openstat` base64 parameter, we get:

    direct.yandex.ru;40651773;6997467316;yandex.ru:premium

This refers to Yandex Direct which has to do with [conversion tracking](https://yandex.com/support/metrica/data/get-yclid.html).

It's not clear that all uses of [OpenStat](https://www.openstat.ru/) are user-identifying though since it depends on what the [payload contains](https://yandex.com/support/metrica/general/source-tags.html).

**Comment by fmarier** [comment]
Also, it's not clear whether this service is still in operation: https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fwww.openstat.ru%2F
![Screenshot from 2020-09-22 16-50-00](https://user-images.githubusercontent.com/167821/93948574-ab55c980-fcf3-11ea-9242-ef93efe4fb8a.png)

**Comment by fmarier** [comment]
According to [Yandex documentation](https://yandex.com/support/direct/statistics/url-tags.html#url-tags__openstat-title) the `_openstat` parameter is also used by <https://liveinternet.ru>:
> You can track ad campaign results in Yandex.Direct by using independent third-party statistics systems like Openstat or LiveInternet. Just add the special parameter (the _openstat tag) to your ad link.
and that company's analytics platform is still alive.

**Comment by fmarier** [comment]
Given that this parameter does include high-entropy values in the wild and that it appears to still be in use by one company, we will add it to the filter.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.68 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/6742
- Verified on both normal, private tab and custom tabs
--------
Verification passed on Samsung Tab A with Android 10 running 1.17.68 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/6742
- Verified on both normal and private tab
