### ISSUE TITLE
[Desktop] [BUG] Cosmetic Filter blocks page elements doesn't work under properties when copying the element

### ISSUE THREAD

**Issue by MrWaste** [brave/brave-browser#11586]
## Description 

Cosmetic Filter blocks page elements doesn’t work under properties when copying the element:

## Steps to Reproduce

   1. Go to inspect an element on a page
   2. Click properties
   3. Click an element and you won’t able to copy and paste the custom element, only type it manually.

## Expected result:
You no longer can copy and paste the custom element under the properties tab.

## Reproduces how often: 

Easily reproduced! Anyone can do this.

## Brave version (brave://version info)

Current: Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit):
Beta: Version 1.14.73 Chromium: 85.0.4183.83 (Official Build) beta (64-bit)
Dev: Version 1.14.74 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
Nightly: Version 1.15.29 Chromium: 85.0.4183.83 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the DEV channel? YES
- Can you reproduce this issue with the nightly channel? YES

Proof:
I use all Brave Browser.
![2020-09-03_122453](https://user-images.githubusercontent.com/49108816/92158300-8a7b1200-ede0-11ea-9e07-68abfd1cd9c3.png)

## Other Additional Information:

I hate typing out the full element every time I see a new ad somewhere on the internet, its a waste of time…

## Proof: 

![](https://aws1.discourse-cdn.com/brave/original/3X/7/a/7a1e054f583a0e272e56000e8822508ea8fd07ad.png)

You were allow back in the day but not anymore, why is this happening? Click the Link Below for PROOF.

![](https://aws1.discourse-cdn.com/brave/original/3X/9/0/90f4f7bb8db3deb9becf5963e88434bda316bf1a.png)

Link: https://support.brave.com/hc/en-us/articles/360018039072-How-do-I-block-additional-page-elements-

**Comment by bsclifton** [comment]
@MrWaste is this working for you now?

**Comment by MrWaste** [comment]
Yes, Somone fixed it. Thank You
