### ISSUE TITLE
[Android] Browser crash when opening a Brave custom tab 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11583]
## Description 
Browser crash when opening a Brave custom tab

## Steps to reproduce 

   1. Clean install 1.13.84
   2. Open a link via slack and select Brave as the default browser
   3. Browser crashes

## Actual result 
Browser crash when opening link via the custom tab 

## Expected result
Should not crash when opening link via custom tab

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86):ARM 
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.13.84

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/6579 was merged and `1.13.x RC3` was started.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab A (2019)` running `Android 10` using https://github.com/brave/brave-browser/releases/tag/v1.13.85.

**`Case 1`**:

* installed `1.13.85 CR: 85.0.4183.83` and made it the default browser
* opened several links via Twitter and ensured that Brave's `Custom Tab` opened within Twitter
* ensured that clicking on `Open in Brave` loads the link from a `Custom Tab` --> within Brave
* disabled `User in-app browser` via Twitter settings
* ensured that `Custom Tab` isn't being used and links are being opened within Brave (set a default)
* ensured that setting Brave as the default browser via Twitter when opening links doesn't cause any crashes/issues

Also verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/11583#issue-691880602. Basically ensured that the same STR worked on Slack.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.85 x64 build
- Verified browser doesn't crash when trying open a link in custom tab
- Verified no crash when Brave isn't set as the default browser
- Verified no crash when Brave is set as the default browser
- Verified selecting `Open in Brave` via the menu on custom tab doesn't crash the browser but loads in a new tab
