### ISSUE TITLE
Trackers & Ads Blocking Setting Not Persisting

### ISSUE THREAD

**Issue by qazero** [brave/brave-browser#11585]
## Description 
Brave's default ad blocking setting is set to Standard out of the box. When I change this to aggressive it seems to work, but when I close Brave and reopen it, then the setting changes back to the default setting of Standard. Why aren't setting persisting between restarts of the browser? I am not having this issue with any of the other settings I've tested, it is only this setting value which isn't persisting.

## Steps to Reproduce
   1. Open Brave
   2. Click on Settings > Shields
   3. In the Shields section, change "Trackers & ads blocking" from Standard to Aggressive
   4. Close Brave Browser
   5. Open Brave Browser and go to Settings > Shields
   6. In the Shields section you will find that the "Trackers & ads blocking" setting has reverted back to the default value of Standard

## Expected result:
"Trackers & ads blocking" setting should persist and not revert back to the default.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 2004 (Build 19041.450)

**Comment by diracdeltas** [comment]
cc @pes10k 

i wonder if this is the same underlying bug as #11525 

@qazero what is your default browser language?

**Comment by qazero** [comment]
English

**Comment by diracdeltas** [comment]
i think this is the same issue as https://github.com/brave/brave-browser/issues/10790; closing as dupe. thx

**Comment by diracdeltas** [comment]
reopening as it seems like a different issue

**Comment by GeetaSarvadnya** [comment]
The above issue mentioned in the STR is working for me, but the issue is arising for the **Disabled** settings option. After selecting `Disabled` option for `Trackers & Ad blocking` in the global shiled settings page, reload page resets the value to default value Standarad. STR is mentioned below:

STR 1:
1. Open Brave 1.14.x or 1.16.x
2. Open brave://settings/shields
3. Change `Trackers & Ad blocking` to Disabled
4. Reload the page or restart the browser
5. Disabled option is reverted back to Standarad

STR 2:
1. Open Brave 1.12.x or 1.13.x
2. Open brave://settings/shields
3. Change `Trackers & Ad blocking` to Disabled
4. Upgrdae the profile to 1.14.x
5. Disabled option is reverted back to Standarad

cc: @pes10k @rebron

**Comment by pes10k** [comment]
@rebron i think @simonhong looked into / fixed something like this a while back.  Could this be another version of that?

**Comment by simonhong** [comment]
As @GeetaSarvadnya mentioned above, I also can see `Disabled` option is reverted.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.15.69 Chromium: 86.0.4240.55 (Official Build) (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the STR mentioned in the description https://github.com/brave/brave-browser/issues/11585#issue-692106975
- Verified the scenarios mentioned in https://github.com/brave/brave-browser/issues/11585#issuecomment-693582182

**Comment by qazero** [comment]
This issue has returned in v1.16.68. Could you please reopen this ticket and fix? Thanks

**Comment by pes10k** [comment]
@qazero im sorry to hear you're still having this problem!  I am not able to reproduce it on my end though.  Can you say a bit more about the steps you're taking that trigger the problem and we can dig in further?

**Comment by qazero** [comment]
@pes10k Thank you for your response. The steps to reproduce hasn't changed for me since my original post. I'm not sure what extra information I could provide. Please advise. Thanks

**Comment by pes10k** [comment]
Hmm, im sorry @qazero but im not able to reproduce on my end… 

If you wouldn't mind, could you answer of these questions if you have a chance?
1. Do you see it on all pages, or only some?
2. What are your global / default shield settings (i.e. brave://settings/shields)
3. Do you still see it in private browsing (if not, that suggests something has gotten goofed in your profile, maybe a migration path we didn't account for… ?)
4. Do you see it in [nightly builds](https://brave.com/download-nightly/) (if you have tested)

**Comment by qazero** [comment]
I'm still experiencing this issue. Please find my responses to your questions below:

1. All
2.  See screenshot below:
![image](https://user-images.githubusercontent.com/10906010/116301539-6304fb00-a75d-11eb-9640-75771e9d8e2d.png)
3. Yes
4. Yes

Just to reiterate here are the steps to reproduce and additional infos below:

**Description**
Brave's default ad blocking setting is set to Standard out of the box. When I change this to aggressive it seems to work, but when I close Brave and reopen it, then the setting changes back to the default setting of Standard. Why aren't setting persisting between restarts of the browser? I am not having this issue with any of the other settings I've tested, it is only this setting value which isn't persisting.

**Steps to Reproduce**
Open Brave
Click on Settings > Shields
In the Shields section, change "Trackers & ads blocking" from Standard to Aggressive
Close Brave Browser
Open Brave Browser and go to Settings > Shields
In the Shields section you will find that the "Trackers & ads blocking" setting has reverted back to the default value of Standard
Expected result:
"Trackers & ads blocking" setting should persist and not revert back to the default.

**Reproduces how often:**
Easily reproduced

**Brave version (brave://version info)**
Brave | 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | Windows 10 OS Version 2009 (Build 19042.928)

**Comment by qazero** [comment]
Pls help!!

**Comment by luv2dnce33** [comment]
I am having this problem too on macos

**Comment by kjozwiak** [comment]
> I am having this problem too on macos

@luv2dnce33 if you're experiencing issues, mind creating a new issue? This one is pretty old which was part of a release that went out a while ago. Can you please create a new issue [here](https://github.com/brave/brave-browser/issues/new?assignees=&labels=OS%2FDesktop&template=desktop.md&title=) and add as much information as possible.

**Comment by TechieFsn** [comment]
I have the same issue reported above (realize this was from 2020, but issue either persists or has returned.)  Brave 1.71.123, Chromium 130.0.6723.116

**Comment by TechieFsn** [comment]
Nevermind.  Unchecked Clear Site and Shields settings on exit and then it retains the Aggressive setting.  Surprising that as many years as I have used Brave I just now find this setting appears to apply to ALL sites, not individual ones.
