### ISSUE TITLE
Filter out Instagram's tracker from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#11580]
The `igshid` query parameter was added to [chrome-utm-stripper](https://github.com/jparise/chrome-utm-stripper/issues/34). There are lots of [examples](https://theholeinthewallto.ca/page/7) of it in the wild, and I have tested a few to confirm that removing or tampering with the parameter doesn't seem to change anything.

However, I also haven't seen any evidence of this parameter on websites other than Instagram. There's [not a lot of information](https://www.bradymoritz.com/igshid-the-new-instagram-click-tracking-id/) about this tracker out there.

**Comment by fmarier** [comment]
Unless we find examples of this being used in a cross-site setting, let's leave it out of the filter.

**Comment by pes10k** [comment]
reopening because we now believe this is a cross site tracker

**Comment by fmarier** [comment]
We have expanded our tracking policy to include query parameters designed (or found to do so in practice) to leak a user's identity across sites: https://github.com/brave/brave-browser/wiki/Query-String-Filter/_compare/fd2df157796d6ca530442adf22ff9359048500f2...bc1adef4bce2a60c357c37927e5f4d8959ca3880

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.35.56 Chromium: 97.0.4692.56 (Official Build) nightly (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)
Steps:
1. new profile
2. opened Developer Tools | Network panel
3. loaded `https://www.instagram.com/p/CDtn9hcAYpm/?igshid=1bjglumson2t5`

Confirmed the `?igshid=1bjglumson2t5` was dropped via an internal redirect.

![image](https://user-images.githubusercontent.com/387249/147369477-0901ad3f-161a-42c9-89fc-f7401a98e0c1.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.68, Chromium 97.0.4692.56` on a `Google Pixel XL` running `Android 9.0`.

Steps:
1. installed `1.35.68`
2. loaded `http://instagram.com/p/CDtn9hcAYpm/?igshid=1bjglumson2t5`
3. looked at the URL bar, post page load

Confirmed the tracking param `?igshid=1bjglumson2t5` was not present in the URL bar.

example | example
---------|---------
![Screenshot_20211230-155126](https://user-images.githubusercontent.com/387249/147795023-c43cc50f-0fa4-486e-b8ff-45135aa87a86.png) | ![Screenshot_20211230-154710](https://user-images.githubusercontent.com/387249/147795031-40e7a365-ece8-4679-accc-e07f5669c78c.png)

**Comment by alfredonodo** [comment]
According to this site https://privacytests.org/, Brave no longer blocks igshid. Is there a problem?
Thank you

**Comment by pes10k** [comment]
@alfredonodo no this is not expected, thank you for the heads up. We will get this fixed immediately cc @arthuredelstein

**Comment by pes10k** [comment]
Hello @alfredonodo , we've looked into this and the issue is with the test (the instragram share id does not appear, as best as we can tell, to be used for cross site tracking, its used for tracking user shares w/in instagram). Brave still correctly removes the instagram share id when its used for this within-instagram purpose.

My understanding is that privacytests.org is being updated to account for this, and that the test will be changed or removed in the next update.

Thank you again for reporting the issue @alfredonodo
