### ISSUE TITLE
[Desktop] Remove sign in message on brave://apps when "Allow Google login for extensions" is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11581]
## Test Plan
Specified here: https://github.com/brave/brave-core/pull/6949

## Description 

When  `Allow Google login for extensions` is enabled in extension settings, `brave://apps` shows sign-in message 

## Steps to Reproduce

   1. Create a new profile and enable `Allow Google login for extensions` in extension settings
   2. Open `brave://apps`
   3. Shows sign in message

## Actual result:

Comparision Release(back) vs Nightly(middle) vs Beta(front)
![image](https://user-images.githubusercontent.com/17010094/92087715-c3f15480-edc3-11ea-9099-9b6034c44035.png)

## Expected result:
No sign-in message irrespective of enabling Google login for extensions

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.14.70 Chromium: 85.0.4183.83 (Official Build) beta (64-bit)
-- | --
Revision | `94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa to check on other platforms

**Comment by LaurenWags** [comment]
Does not reproduce on macOS 10.14.6 using any of the following versions:

**`Release`**
```
Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

**`Beta`**
```
Brave | 1.14.73 Chromium: 85.0.4183.83 (Official Build) beta (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Dev
```
Brave | 1.14.72 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Nightly
```
Brave | 1.15.32 Chromium: 85.0.4183.83 (Official Build) nightly (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)
```

**Comment by MrWaste** [comment]
Works in Windows 10.
Proof:
![2020-09-03_130935](https://user-images.githubusercontent.com/49108816/92162286-c87b3480-ede6-11ea-8796-1ec80a436f3b.png)

**Comment by MrWaste** [comment]
Also how did you put label "bug". Some how I can't.
Link:
https://github.com/brave/brave-browser/issues/11586

**Comment by srirambv** [comment]
Updating priority to P3. More info here https://bravesoftware.slack.com/archives/C7VLGSR55/p1603407790308500

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Reproduced the issue in 1.17.x
![image](https://user-images.githubusercontent.com/38657976/100071358-f5c50500-2e60-11eb-87e1-7f4753d514cd.png)

- Verified the test plan from https://github.com/brave/brave-core/pull/6949
![image](https://user-images.githubusercontent.com/38657976/100071384-ffe70380-2e60-11eb-9ca4-60b79f23728d.png)
