### ISSUE TITLE
[Android] Implement cosmetic filters on Android (scriplets injection)

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#11599]
## Description 
Currently we hardcode scripts that need to be injected in pages like YT for example to avoid some kind of ads, we want to improve that and pull the needed scripts from adblock list like we do when we block specific URLs.

We had ads on such embedded videos https://www.pcmag.com/news/the-best-vr-games-for-2019. We just need to make sure that we don't have them when apply the fix for this issue.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.16.65 x64 build
- Verified no ads shown on videos on the [page](https://www.pcmag.com/news/the-best-vr-games-for-2019) 
- Verified no ads on embedded YT videos as well
-----------
Verification passed on Samsung Tab A with Android 10 running 1.16.65 x64 build
- Verified no ads shown on videos on the [page](https://www.pcmag.com/news/the-best-vr-games-for-2019) 
- Verified no ads on embedded YT videos as well
