### ISSUE TITLE
Ledger Flags needed for QA

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1161]
## Description 
When QA-ing Brave Payments on browser-laptop (muon) there are several flags that we use/have used previously. These flags should be implemented for Brave Rewards to assist with QA.

- `LEDGER_NO_DELAY`
- `LEDGER_NOTIFICATION`
- `LEDGER_REFERRAL_CHECK_TIME`

`LEDGER_NO_DELAY` was also used, but I believe is not needed since there will not be a 30 minute minimum browsing time requirement for Brave Rewards. If this isn't true, then we will need this flag as well.  

Here is a list of other flags, but not all of them have been used for QA (to date):
https://github.com/brave/browser-laptop/wiki/Command-line-flags#environment-variables

cc @brave/legacy_qa for additional input

**Comment by kjozwiak** [comment]
@bsclifton I don't think this should be placed into the `1.x Backlog` unless `b-c` already has built in flags that we can use during ledger/rewards testing.

@NejcZdovc are we going to be using staging servers? If so, how can we use the staging server with `b-c`? Are we going to need any of the previously created flags to correctly test rewards? If that's the case, adding flags into `b-c` when possible is probably a good idea rather then waiting just before the `1.x` release.

**Comment by bsclifton** [comment]
@kjozwiak good call- milestone updated

**Comment by srirambv** [comment]
Assuming `LEDGER_VERBOSE=true` is still being used and is same for rewards

**Comment by NejcZdovc** [comment]
for now I will add two flags

- rewards_env : used to change staging and production server
- rewards_reconcile_delay : used to define amount of time that we should wait for contribution (defined in minutes)

**Comment by kjozwiak** [comment]
@NejcZdovc as per our earlier conversations in Slack, it seems like both `rewards_env` and `rewards_reconcile_interval` flags aren't working. Attempted the following a few times:

Using https://github.com/brave/brave-browser/releases/tag/v0.55.17, tried the following:

Attempt 1: **FAILED**

• launched using `/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser --rewards_env=stag`
• enabled `brave://rewards`
• attempted to restore a staging wallet - **FAILED**
• retrieved my `paymendid` and tried https://balance-staging.mercury.basicattentiontoken.org/v2/wallet/c5987724-0157-4dec-a9af-abb392f08533/balance - **FAILED (404)**

Attempt 2: **FAILED**

• launched using `rewards_env=stag /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser`
• enabled `brave://rewards`
• attempted to restore a staging wallet - **FAILED**
• retrieved my `paymendid` and tried https://balance-staging.mercury.basicattentiontoken.org/v2/wallet/95c7c6a5-1a74-4c9c-947d-e363284bc134/balance - **FAILED (404)**

**Comment by NejcZdovc** [comment]
@kjozwiak correct flag for package build is `/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser --rewards-env=stag`

**Comment by kjozwiak** [comment]
Thanks for the help last night @NejcZdovc 👍

* `--rewards-env=stag` - Package builds
* `--rewards_env=stag` - from source
* `--rewards-reconcile-interval` - Package builds
* `--rewards-reconcile_interval` - from source

**Comment by LaurenWags** [comment]
Verified passed on `macOS 10.12.6 x64` with

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

* Verified `--rewards-env=stag` pointed to Staging environment (verified staging wallet was created)
* Verified `--rewards-reconcile-interval=<# of minutes>` forced contribution to occur in the # of minutes specified. Note - I had to initially launch Brave with this flag prior to creating a wallet for it to work as expected.
