### ISSUE TITLE
[Desktop] Import data and settings from another Brave channel

### ISSUE THREAD

**Issue by Poopooracoocoo** [brave/brave-browser#11612]
## Description 

Import data and settings from another Brave channel

## Steps to Reproduce

This is a feature request

## Actual result:

I installed Brave Beta but when I went to import my stuff from the Stable channel I realised that you can't.

## Reproduces how often: 

easily reproduced

## Brave version (brave://version info)

1.14.73 

94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}

Windows 10 OS Version 2009 (Build 19042.450)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Thanks for the feature request, @Poopooracoocoo 😄 

We have an issue open for this already which you can subscribe to: https://github.com/brave/brave-browser/issues/1357

In the meantime, you can actually go to your profile directory and rename it to "move" between channels. This isn't a perfect solution and you should back up before doing it. You can also use the sync feature to sync your bookmarks and all data between each channel and that should work great
