### ISSUE TITLE
[Desktop] Open link in New Tor Private Window via context menu opens a tab with new tab

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#11611]
## Description 

Try opening a link via context menu in New Tor Private Window.
If there is no existed tor window, new tor window is created and that window has NTP and tab that loads requested link.
According to the https://github.com/brave/brave-browser/issues/1387#issuecomment-429152710, this is expected behavior.

## Steps to Reproduce

   1. Launch Browser and make sure thare is no tor private window 
   2. Select `Open link in private window with Tor` menu via context menu in normal window
   3. Newly created tor window has two tabs - NTP and requested link

## Actual result:

New tor window has NTP tab.

## Expected result:
New tor window should have one tab that loads requested url

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Since 0.55

## Version/Channel Information:

All channels

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.32.66 Chromium: 95.0.4638.40 (Official Build) nightly (x86_64)
-- | --
Revision | e3e7c76ba0284b16087cf4cf3153abfaef6470c7-refs/branch-heads/4638@{#624}
OS | macOS Version 11.6 (Build 20G165)

Confirmed that context-clicking on a URL and choosing `Open Link in Private Window with Tor` resulted in the Tor tab loading the link correctly, with no other (empty) tabs.

<img width="1312" alt="Screen Shot 2021-10-12 at 12 20 47 PM" src="https://user-images.githubusercontent.com/387249/137016512-d7f52387-1521-484f-8956-48943eef0a6e.png">


Reproduced the problem in 


Brave | 1.31.82 Chromium: 95.0.4638.40 (Official Build) beta (x86_64)
-- | --
Revision | e3e7c76ba0284b16087cf4cf3153abfaef6470c7-refs/branch-heads/4638@{#624}
OS | macOS Version 11.6 (Build 20G165)

<img width="1748" alt="Screen Shot 2021-10-12 at 12 20 11 PM" src="https://user-images.githubusercontent.com/387249/137016596-b9fc18dd-ae6b-46e8-b609-1c07254ad020.png">

where I got an extra, empty tab to the left of the correctly opened link in Tor.
