### ISSUE TITLE
Add ephemeral DOM Storage support

### ISSUE THREAD

**Issue by mrobinson** [brave/brave-browser#11619]
This issue tracks the addition of ephemeral storage (described in #8514) for DOM Storage APIs (`localStorage` and `sessionStorage`).

**Comment by bbondy** [comment]
@mrobinson please set the milestone when closing issues and pull request. You'll want to select the 1.18.x Nightly in this case. Thanks!

**Comment by mrobinson** [comment]
@bbondy Thanks for the heads up. I've adjusted the issue here and in the PR.
