### ISSUE TITLE
"Ad notifications received this month" and "Estimated earnings" are reset to 0 at midnight UTC time not local time

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11618]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/9870

It looks like `Ad notifications received this month` on Ads panel of brave://rewards page is reset to 0 when the new month starts in UTC time, not local time.

example - if you are on the east coast of the US and it is EDT, then your timezone is UTC-4. I'd expect `Ad notifications received this month` to reset to 0 when the clock rolls over to 12:00am on Oct 1. However, this is occurring at 8pm on Sept 30.

## Steps to Reproduce

Have a profile with ads viewed for the month. Wait for month end and watch the brave://rewards page when it would be 12:00am on the first day of the month in UTC time. 

## Actual result:

`Ad notifications received this month` changes to 0 early in my example using EDT.

## Expected result:
`Ad notifications received this month` should change to 0 in local time (midnight) when the new month starts.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.14.75 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes, reproduces on 1.13.x
- Can you reproduce this issue with the beta channel? yes, reproduces on 1.14.x
- Can you reproduce this issue with the nightly channel? yes, reproduces on 1.15.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @tmancey 

Note - I added `OS/Android` tag as this functionality is available there, however, if the fix is not applicable please remove this tag.

**Comment by tmancey** [comment]
@LaurenWags @jsecretan Requires further discussion as confirmed ads, payment balances and promotions are stored as UTC on the server, which is why we originally chose to use UTC to reset the counter

**Comment by MrWaste** [comment]
Has this been fixed?

**Comment by tmancey** [comment]
@MrWaste This has not been fixed as needs further discussion. Thanks

**Comment by tmancey** [comment]
@MrWaste This will be fixed as part of https://github.com/brave/brave-browser/issues/16028

**Comment by Miyayes** [comment]
Increasing priority to P2 as user confusion and support volume spikes extremely high at turn of the month, according to community.brave.com, Twitter, and our subreddits.
