### ISSUE TITLE
setting to disable UGP notifications

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1162]
## Description 
Browser-Laptop advanced preferences has a setting to disable token (UGP) notifications, Brave Rewards should have this as well.

## Steps to Reproduce

   1. Navigate to Settings
   2. Look for a way to disable token (UGP) notifications.
   3. 

## Actual result:
No way to disable token (UGP) notifications.

## Expected result:
Should be a way to disable token (UGP) notifications.

## Reproduces how often: 
easily

## Brave version (chrome://version info)
all

### Reproducible on current release:
yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
On browser-laptop (muon) this is located on the Advanced Settings page (about:preferences#advanced).

**Comment by NejcZdovc** [comment]
cc @davidtemkin @jenn-rhim @mandar-brave

**Comment by davidtemkin** [comment]
Not a bug. UGP notifications in Brave Rewards only occur once a user has opted into Brave Rewards.
