### ISSUE TITLE
[Android] Settings menu unreachable on Android 7

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#11620]
## Description 
Some users reported that they cannot reach a settings menu after 1.13.85 upgrade. All the reviews came from Android 7 devices. We were able to replicate it on emulator on Android 7 device as well
![Screenshot from 2020-09-08 09-49-24](https://user-images.githubusercontent.com/12011303/92503807-c7c01500-f1cf-11ea-8461-fd611eea5fa9.png)

## Steps to reproduce 

   1. Install Brave on Android 7 device
   2. Click on 3 dots to reach Settings menu
   3. Observe only New tab menu like on the picture above

## Actual result 
Observe a full menu

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Nexus 6 Emulator with Android 7 running 1.13.86 x64 build
- Verified able to open menu on the bottom bar without issues 
![bottombar](https://user-images.githubusercontent.com/17010094/92729810-c6771f80-f36a-11ea-8cd3-1d59cef099f3.gif)
