### ISSUE TITLE
[Desktop] Select MetaMask as the default Dapp provider if it is installed

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11623]
## Description 
We will no longer prompt if the user would like to use Crypto Wallets or MetaMask. When MetaMask is installed, we'll change to use MetaMask, even if the user is currently using and has setup Crypto Wallets.

# QA test cases:

## Installing Crypto Wallets without MetaMask

1. Fresh profile
2. Go to brave://settings/extensions, web3 provider should be set to Ask
3. about://wallet, install the component, create a wallet (Remind me later for passphrase backup)
4. Reload brave://settings/extensions, web3 provider should still be set to Crypto Wallets
5. Load cryptokitties.co, click on Start, it should show a popup from Crypto Wallets

## Installing Crypto Wallets without MetaMask through a Dapp

1. Fresh profile
2. Go to brave://settings/extensions, web3 provider should be set to Ask
3. Load cryptokitties.co, click on Start, it should show an infobar w/ 1 button, click on Setup Crypto Wallets. It should open up brave://wallet
4. Go to brave://settings/extensions, web3 provider should be set to Crypto Wallets

## Install Crypto Wallets MetaMask installs should override it

5. Continuing from the last step, install MetaMask https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en
6. Go to brave://settings/extensions, web3 provider should show MetaMask
7. Reload the crypto kitties page, then press Start, it should show the popup for MetaMask.

## Uninstall MetaMask

8. Continuing from the last test, uninstall MetaMask
9. Go to brave://settings/extensions, web3 provider should be set to Crypto Wallets
10. Reload the crypto kitties page, then press Start, it should show the popup for Crypto Wallets.

## Setting Dapp provider to None even w/ MetaMask installed

11. Continue from the last test, reinstall MetaMask
12. Reload the crypto kitties page, then press Start, it should show the popup for MetaMask.
13. Go to brave://settings/extensions and set it to None
14. Reload the crypto kitties page, in the developer console window.web3 should be undefined

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (64-bit)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | Linux

- Verified test plan from issue description
----------------------
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (x86_64)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified test plan from issue description
-----------------------
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (64-bit)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | Windows 10 OS Version 1809 (Build 17763.1490)

- Verified test plan from issue description
