### ISSUE TITLE
[Desktop] Pending verifications from 1.13.x Release #2

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11631]
Current list of issues that have been fixed/resolved in [`1.13.x Release #2`](https://github.com/brave/brave-browser/milestone/136) but haven't been verified by QA as  [`1.13.x Release #2`](https://github.com/brave/brave-browser/milestone/136) was released on `Android` only.

- [ ] [Desktop][CW] Gemini widget displayed in unsupported region(s) - #11483
- [ ] [Desktop] Sign setup.exe - #11378

Above should also be checked and added to release notes if a `release-notes/include` is used.

**Comment by srirambv** [comment]
Closing as RC build is available and can be verified
