### ISSUE TITLE
[Android] Auto rotate is off but screen is rotating after 1.13.85 update

### ISSUE THREAD

**Issue by newuser-web** [brave/brave-browser#11632]
## Description  
Auto rotate is off but screen is rotating in brave browser

## Steps to reproduce 

   1. Turn off Auto rotate
   2. Open any website 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 9
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by newuser-web** [comment]
@srirambv Do you need any more information from me?

**Comment by srirambv** [comment]
Am not sure I understand the issue. Would it be possible to do a screen recording of the issue?

**Comment by newuser-web** [comment]
Auto rotate screen is off in my phone setting. But in brave browser when I am changing the orientation of my device, screen is rotating from horizontal to vertical or vice-versa.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/mobile-browser-is-rotating-automatically-even-screen-rotation-setting-is-turned-off-in-mobile/161534

Thread has a video recording as well

**Comment by newuser-web** [comment]
@srirambv This issue starts to occur when I click on the newly added privacy report icon.

**Comment by newuser-web** [comment]
@srirambv Clicking the newly added privacy report icon causes this problem.

**Comment by newuser-web** [comment]
@srirambv Clicking the newly added privacy report icon causes this problem.

**Comment by jonathansampson** [comment]
[Another user](https://twitter.com/HarunaChieP/status/1304450493079379970) experiencing this behavior notified us through Twitter. At this time, the Tweet includes a video as well.

I was **unable** to reproduce the issue on 1.12.113 and 1.167 on my Pixel 3 XL running Android 10.

**Comment by newuser-web** [comment]
I'm facing this issue after 1.13.85 update. To reproduce this bug click on the privacy report icon and after that change the orientation of the phone.

**Comment by newuser-web** [comment]
I'm facing this issue after 1.13.85 update. To reproduce this bug click on the privacy report icon , after that come back on the homepage of brave and then change the orientation of the phone.

**Comment by urbenlegend** [comment]
I am also getting this issue whenever I press the Privacy Reports icon and then close the panel that pops up. I am running 1.13.87 on a Pixel 2XL.

**Comment by intrnl** [comment]
Isn't this related to #11059?

Brave Stats/Privacy Reports causing rotation lock to no longer be honored

**Comment by bsclifton** [comment]
Added missing milestone after fix was merged 😄 👍

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.14.83 x64 build
- Verified on GPS build even without enabling privacy report and auto-rotate turned off changing device orientation auto-rotates the browser
- Verified upgrading to 1.14.83, with auto-rotate turned off changing device orientation doesn't auto-rotate the browser with or without privacy report being enabled
--------
Verification passed on OnePlus 6T with Android 10 running 1.14.83 x64 build
- Verified on GPS build even without enabling privacy report and auto-rotate turned off changing device orientation auto-rotates the browser
- Verified upgrading to 1.14.83, with auto-rotate turned off changing device orientation doesn't auto-rotate the browser with or without privacy report being enabled

**Comment by FrAmed46** [comment]
bump. still happening, no setting to fix
