### ISSUE TITLE
setting to disable Brave Rewards Notifications

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1163]
## Description 
Brave Payments has a setting to disable notifications entirely, Brave Rewards should have this as well.

## Steps to Reproduce

   1. With Brave Rewards enabled, navigate to chrome://rewards.
   2. Look for a way to disable Brave Rewards Notifications.
   3. 

## Actual result:
No way to disable Brave Rewards Notifications.

## Expected result:
Should be a way to disable Brave Rewards Notifications.

## Reproduces how often: 
easily

## Brave version (chrome://version info)
all

### Reproducible on current release:
yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
On browser-laptop (muon) this is located on the Payments page (about:preferences#payments) when you click on the gear icon.

**Comment by NejcZdovc** [comment]
cc @davidtemkin @jenn-rhim @mandar-brave

**Comment by davidtemkin** [comment]
The notification system for Brave Rewards is different (and has yet to be implemented).

Not sure we want to do this. 

1. UX is different -- red dot on BR icon vs. browser notification
2. No notifications are generated until the user opts in to BR (except for the initial "1" to get the user to open the panel)
3. Once a user has opted in, we need a way of notifying them, period. 

Suggest we close this

**Comment by LaurenWags** [comment]
Per discussion in today's b-c triage meeting with @davidtemkin and @kjozwiak - going to close this one out.

**Comment by bbondy** [comment]
Added to dupe / invalid / not actionable milestone.
We want everything part of some milestone for triage reasons.
