### ISSUE TITLE
Removing all folders/files associated with ads/rewards from "session_profiles/Tor Profile"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11645]
## Description 

If the user has been using rewards and has opened a `Tor Window`, they'll have several files/folders/logs associated with ads/rewards within `session_profiles/Tor Profile`. We've stopped this from happening via https://github.com/brave/brave-core/pull/6418 but haven't covered the cases of removing files that might have already existed. Example of files that might already be in `session_profiles/Tor Profile` but are not being removed after updating to a version with https://github.com/brave/brave-core/pull/6418 merged.

```
* ~/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/ads_service
* ~/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/rewards_service
* ~/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/publisher_info_db
```

Similar to the following issue:

* [Desktop] removing previous rewards.log from "session_profiles/Tor Profile" #11644

## Steps to Reproduce

   1. launch a version of brave before https://github.com/brave/brave-core/pull/6418 was merged
   2. enable rewards
   3. go into `/BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/` and you should see several folders/files associated with ads/rewards as mentioned above.
   4. update to a new version and you'll notice the folders/files associated with ads/rewards haven't been removed

## Actual result:

https://github.com/brave/brave-core/pull/6418 doesn't remove the folders/files that already exists within `/BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/` that might be associated with rewards/ads.

## Expected result:

Should remove all the folders/files associated with rewards/ads from `/BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/`

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.16.4 Chromium: 85.0.4183.102 (Official Build) nightly (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | macOS Version 10.15.6 (Build 19G73)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @diracdeltas @rebron @NejcZdovc @jsecretan @tmancey for prioritization.

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows `10 x64 - 1.13.86`

**Comment by btlechowski** [comment]
Reproduced on

Brave | 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Ubuntu 18.04 LTS

**Comment by tmancey** [comment]
Closing issue as cannot reproduce
