### ISSUE TITLE
[Desktop] Avoid relying on innerHTML for Brave Rewards & Welcome pages

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#11642]
## Description 

For Chromium 87, we needed to push a patch named "Disable Trusted Types mitigation on Brave's Welcome & Rewards pages" that disables the Content Security Policy for Trusted Types in Brave's Welcome and Rewards WebUI pages, since they rely on the ability to assign untrusted text to the `innerHTML` element to deal with translations and error messages (you can search for `dangerouslySetInnerHTML` in `*.tsx` files to find where exactly this is a problem).

This is consistent with what upstream Chromium does for pages that don't support Trusted Types yet (see [CL 2234238](https://crrev.com/c/2234238)), but it would be good if Brave's WebUI pages could eventually migrate from this model, which would need some refactor of the current JS code, which heavily relies on `innerHTML` for translations.

Chromium change:

## Steps to Reproduce
   1. Build Cr87-based Brave with the patch mentioned in the description reverted
   2. Load Brave Rewards main page (brave://rewards)

## Actual result:
The page doesn't load and there's an error on the console saying _"This document requires 'TrustedHTML' assignment."_

## Expected result:
The page should work fine, no errors on the console.

## Reproduces how often: 
Always, assuming the patch mentioned in the description is reverted

## Brave version (brave://version info)
Brave 1.15.37 or newer (Chromium: 87.0.4250.0 (Developer Build) (64-bit)), but only with the patch reverted.

**Comment by diracdeltas** [comment]
good call, we shouldn't be using innerHTML anyway. (it's mentioned in our security review guidelines)

**Comment by diracdeltas** [comment]
@mariospr how do i revert this patch for a build? sorry i've not had to do this before.

**Comment by mariospr** [comment]
> @mariospr how do i revert this patch for a build? sorry i've not had to do this before.

Apologies, I think I might have poorly explained the problem in the description :thinking: 

There is no patch to revert on any current build, nor even on a branch right now... the problem only affect**ed** the WIP branch `cr87` until we figured out the patch to solve the issue, which has been applied in https://github.com/brave/brave-core/commit/37848a5f. This was not a problem before (neither on the current stable cr85-based version of Brave, nor on the incoming cr86-based one), so the only way you could experience this problem is by building the `cr87` branch from sources with the path https://github.com/brave/brave-core/commit/37848a5f reverted on top.

So, when I said that the problem reproduces _"always for Brave 1.15.37 or newer (Chromium: 87.0.4250.0), but only with the patch reverted"_, it was just a way for me to show where the problem was before it got worked around for the incoming cr87-based release, not that the problem is still reproducible in there. But, as said, this is a workaround and the true fix would be to avoid relying on innerHTML, which is what this issue is actually for.

Hope that this clarifies things, but please feel free to ask more questions if not! :slightly_smiling_face:

**Comment by zenparsing** [comment]
For localization of strings that may contain markup (such as links) when displayed, we should use the pattern described [here](https://github.com/brave/brave-browser/wiki/Strings-and-Localization:-string-formatting).

**Comment by diracdeltas** [comment]
@mariospr ah ok, thanks for clarifying.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.16.43 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 1903 (Build 18362.1016)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/6669
- Encountered https://github.com/brave/brave-browser/issues/11907

**Comment by srirambv** [comment]
Removed `OS/Android` label after discussing with @NejcZdovc
