### ISSUE TITLE
[Desktop][CW][Follow up to #11483]Gemini entry in new tab page settings is not removed for unsupported region

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11649]
## Description 

[Follow up to #11483]Gemini entry in newtab page settings is not removed for unsupported region

## Steps to Reproduce

   1. Clean install 1.13.86 for French region
   2. Open a new tab no Gemini widget is found
   3. Open Settings -> New Tab page -> Gemini switch is still available

## Actual result:

**Linux**

French | German
-- | --
<img width="1056" alt="Screenshot 2020-09-10 at 8 33 59 a m" src="https://user-images.githubusercontent.com/17010094/92695557-3df68000-f366-11ea-9e07-9458b120af40.png"> | <img width="1056" alt="Screenshot 2020-09-10 at 8 37 22 a m" src="https://user-images.githubusercontent.com/17010094/92695820-a6456180-f366-11ea-8ecc-5f1e69275cf5.png">

**Windows**

French | German
-- | --
<img width="1043" alt="Screenshot 2020-09-10 at 8 42 32 a m" src="https://user-images.githubusercontent.com/17010094/92696788-0092f200-f368-11ea-8f29-af748c26ed8b.png"> | <img width="1043" alt="Screenshot 2020-09-10 at 8 49 42 a m" src="https://user-images.githubusercontent.com/17010094/92697018-5cf61180-f368-11ea-94d9-719781b20988.png">

## Expected result:
Gemini option should not be in NTP settings when widget isn't available

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-Bit)
-- | --
Revision | `ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}`
OS | Linux

Brave | 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-Bit)
-- | --
Revision | `ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No 
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No. Was verified to not have it https://github.com/brave/brave-core/pull/6538#issuecomment-686481306

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows for unsupported region `India`. Although the `Gemini` widget is not shown in NTP but in new tab settings the option is still available/enabled 

![image](https://user-images.githubusercontent.com/38657976/92702259-9c276100-f36e-11ea-9499-03cf6bd2532f.png)

**Comment by srirambv** [comment]
@rebron this is an issue only on 13.x branch. Its not an issue on 1.14.x branch. Are we ok to close this out or should it be fixed for 13.x branch as well? 
![image](https://user-images.githubusercontent.com/17010094/93077559-e23b3800-f680-11ea-80b3-17caeb19ac09.png)

**Comment by ryanml** [comment]
Keeping out of `1.13.x` cc: @rebron @srirambv
