### ISSUE TITLE
[Desktop] removing previous rewards.log from "session_profiles/Tor Profile"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11644]
## Description 

If a user has previously exported logs via `brave://rewards-internals` and has use `Tor`, they still might have a copy in the following directory:

```
* /BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/
```

This was partially fixed via https://github.com/brave/brave-browser/issues/11260 but didn't cover the `/session_profiles/Tor Profile/` case.

## Steps to Reproduce

   1. launch a version of brave before https://github.com/brave/brave-core/pull/6439 was merged
   2. enable rewards
   3. go into `/BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/` and you should see `Rewards.log`
   4. update to a new version and you'll notice the `Rewards.log` is removed from ``/BraveSoftware/Brave-Browser-Nightly/Default/` but not from `/BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/`.

## Actual result:

<img width="953" alt="Screen Shot 2020-09-09 at 10 39 34 PM" src="https://user-images.githubusercontent.com/2602313/92675432-642c0980-f2ed-11ea-966b-d03a95d7411e.png">

## Expected result:

`Rewards.log` should be removed from `/BraveSoftware/Brave-Browser-Nightly/Default/session_profiles/Tor Profile/`

## Reproduces how often: 

100% reproducible using the STR mentioned above.

## Brave version (brave://version info)

```
Brave | 1.16.4 Chromium: 85.0.4183.102 (Official Build) nightly (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | macOS Version 10.15.6 (Build 19G73)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @diracdeltas @rebron @NejcZdovc @jsecretan @tmancey for prioritization.

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows `10 x64 - 1.13.86`

**Comment by btlechowski** [comment]
Reproduced on

Brave | 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Ubuntu 18.04 LTS

**Comment by mkarolin** [comment]
@kjozwiak @Miyayes do you think this is still actionable? I can't even install a version pre STR 1 that is able to join Rewards at this point. Also, I don't believe we create `Default/session_profiles/Tor Profile/` any more either. WDYT?

**Comment by kjozwiak** [comment]
> @kjozwiak @Miyayes do you think this is still actionable? I can't even install a version pre STR 1 that is able to join Rewards at this point. Also, I don't believe we create `Default/session_profiles/Tor Profile/` any more either. WDYT?

@mkarolin yup, lets close this off. As you pointed out, we don't even create a `Tor Profile` folder under `Sessions` anymore. I doubt anyone is going to be downloading the older version mentioned above. Even if they do, they'll have issues enabling rewards as it was refactored a bunch of times between then and now. @Miyayes going to close this off, please re-open if you feel differently.
