### ISSUE TITLE
[Desktop] Restoring new wallet fails

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11647]
## Description 

We need to handle this error as success and return 0 balance.

```
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.brave.software/v3/wallet/uphold/b60b2138-839a-4203-9fb5-b8d34c0ea531
> Result: Failure
> HTTP Code: 400
> Body: {"message":"wallet not capable of balance inquiry","code":400}
```

## Steps to Reproduce

   1. Clean profile
   2. Enable rewards
   3. Open backup dialog
   4. Get recovery keys from local storage
   5. Restore wallet

## Actual result:

Restore is successful, but you get server error

## Expected result:
No server error

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@NejcZdovc could you clarify what you mean by
> Get recovery keys from local storage
in the STR?

**Comment by NejcZdovc** [comment]
@LaurenWags sadly this use case is not viable anymore as we removed it from local storage as well. So you will just need recovery keys from older wallet

**Comment by LaurenWags** [comment]
@NejcZdovc will any 24 word wallet work as long as it has a zero balance?

**Comment by NejcZdovc** [comment]
@LaurenWags yes it will

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.16.47 Chromium: 86.0.4240.55 (Official Build) dev (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description using a wallet with 0 BAT balance as per https://github.com/brave/brave-browser/issues/11647#issuecomment-699535876

```
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/............................
> Result: Success
> HTTP Code: 200
> Body: {"total":0,"spendable":0,"confirmed":0,"unconfirmed":0}
```


-------------
