### ISSUE TITLE
[Android] Implement Widgets on Android

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#11658]
## Description 
Please implement Widgets on Android.

Details can be found in the "Mobile Widgets" doc on G-Drive

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.71 x64 RC build
- Verified on a clean install NTP shows widgets
- Verified default widget is privacy stats
- Verified Privacy Stats/Favourites/Binance is the order of widget stack
- Verified able to scroll up or down on the widget stack
- Verified widget can be added/removed by selecting `Remove widget` via widget menu
- Verified widget can be added/removed by selecting `Edit Stack` via widget menu
- Verified tapping on `Edit Stack` opens up settings for widget stack 
- Verified left/right swipe on widget stack settings removes the specific widget 
- Verified clicking on the `+` button next to the widget adds it at the bottom of the widget stack
- Verified widget order can be changed by moving the entry within the widget stack
- Verified removing all widgets in the stack doesn't leave a widget container window 
- Verified when the device is set to non-EN locale, widget text doesn't overflow or gets cut off. 
- Verified changing device orientation doesn't stretch widgets. Changing orientation sets the widget to the top right corner of NTP
- Verified on landscape mode, the widget doesn't overlap on the NTP SI links
- Verified stats are retained on upgrade from 1.16.x and tapping on privacy stats brings up the bottom sheet report
- Verified clicking on favourites from upgrade loads the site correctly 
- Verified able to delete top sites from the widget on both clean install and upgrade
- Verified changing bottom toolbar behaviour doesn't mess up with the widget location
------------
Verification passed on Samsung Tab A with Android 10 running 1.17.71 x64 RC build
- Verified on a clean install NTP shows widgets
- Verified default widget is privacy stats
- Verified Privacy Stats/Favourites/Binance is the order of widget stack
- Verified able to scroll up or down on the widget stack
- Verified widget can be added/removed by selecting `Remove widget` via widget menu
- Verified widget can be added/removed by selecting `Edit Stack` via widget menu
- Verified tapping on `Edit Stack` opens up settings for widget stack 
- Verified left/right swipe on widget stack settings removes the specific widget 
- Verified clicking on the `+` button next to the widget adds it at the bottom of the widget stack
- Verified widget order can be changed by moving the entry within the widget stack
- Verified removing all widgets in the stack doesn't leave a widget container window 
- Verified when the device is set to non-EN locale, widget text doesn't overflow or gets cut off. 
- Verified changing device orientation doesn't stretch widgets. Changing orientation sets the widget to the top right corner of NTP
- Verified on landscape mode, the widget doesn't overlap on the NTP SI links
- Verified stats are retained on upgrade from 1.16.x and tapping on privacy stats brings up the bottom sheet report
- Verified clicking on favourites from upgrade loads the site correctly 
- Verified able to delete top sites from the widget on both clean install and upgrade
