### ISSUE TITLE
[Android] location message says "Chromium" instead of "Brave"

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11656]
## Description 
In 1.12.113 (C84) the message asking for location said "Brave needs access...".

In 1.13.83 and 1.13.86 (C85), the message now says "Chromium needs access..."

## Steps to reproduce 

   1. Install 1.13.x version of Brave (1.13.83 or 1.13.86 will work)
   2. Tap on URL bar, can keep Google as the SE
   3. Enter a search term that would prompt a location 

## Actual result 
1.13.x versions show message with "Chromium"
![Android1 13 x](https://user-images.githubusercontent.com/28145373/92777033-cdebf800-f36d-11ea-8fb6-72a29a634f15.jpg)

## Expected result
Should be like 1.12.x version that says "Brave"
![Android1 12 x](https://user-images.githubusercontent.com/28145373/92777046-d0e6e880-f36d-11ea-9c01-8bc1b843f95f.jpg)

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.13.83, 1.13.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @srirambv

**Comment by btlechowski** [comment]
Not reproducible on Tablet.

Brave v1.13.86 on Samsung Galaxy Tab S5e (Android 9.0)

![Screenshot_20200910-200237_Brave](https://user-images.githubusercontent.com/34715963/92780270-31dce380-f3a3-11ea-9589-8b605db4fc99.jpg)

**Comment by kjozwiak** [comment]
Reproduced the issue on `Samsung Galaxy S10+` running `Android 10` using https://github.com/brave/brave-browser/releases/tag/v1.13.86.

* launched `1.13.86 CR: 85.0.4183.102`
* kept Google as the default SE via onboarding
* tapped on the URL and used `pizza` as the search term

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/92787317-faf0d880-f376-11ea-9876-1a652b68fb35.jpg" width=300>
</p>

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.87 x64 build
- Verified no Chromium branding is used on location access message
![image](https://user-images.githubusercontent.com/17010094/92860689-72af1980-f3f0-11ea-9716-e69d7b008482.png)
-------------
Verification passed on Samsung Tab A with Android 10 running 1.13.87 x64 build
- Verified no Chromium branding is used on location access message
![image](https://user-images.githubusercontent.com/17010094/92864077-a0965d00-f3f4-11ea-98b3-fca745251c48.png)
