### ISSUE TITLE
Rewards Windows

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1165]
Rewards are currently disabled on Windows, because of anonize is not working there.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Windows

* Verified `chrome://rewards` works
* Verified able to enable Brave Rewards works
* Verified able to claim grants 
* Verified sites are getting listed under auto-contribute
* Verified disable rewards shows wallet details
