### ISSUE TITLE
[Android] Location permission under site settings lists app as Chrome instead of Brave

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11668]
## Description 
 Location permission under site settings lists app as Chrome instead of Brave

## Steps to reproduce 

   1. Install 1.10.99
   2. Visit google.com and open site settings 
   3. Shows `Turn on permissions for Brave in Android Settings`
   4. Upgrade to 1.11.105
   5. Open site settings for google.com
   6. Shows `Turn on permissions for Chrome in Android Settings`

## Actual result 
![sitesettings](https://user-images.githubusercontent.com/17010094/92868662-e144a500-f3f9-11ea-8dd4-eec20871da33.gif)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/92867660-caea1980-f3f8-11ea-81bb-4849553f66a5.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.11.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@anthonypkeane @bsclifton Added P2 to get it uplifted for 1.14.x please modify it if required.

**Comment by bsclifton** [comment]
Fixed on Nightly / Chromium 86. Putting in 1.15 so we can verify

**Comment by srirambv** [comment]
- Verification passed on OnePlus 6T with Android 10 running 1.15.66 x64 beta build
![image](https://user-images.githubusercontent.com/17010094/94435879-9fef1c00-0193-11eb-9d7e-f77238ddb5fb.png)
- Verification passed on OnePlus 6T with Android 10 running 1.15.66 x64 beta build
![image](https://user-images.githubusercontent.com/17010094/94435893-a382a300-0193-11eb-94ba-b8d1dc5e1a44.png)
