### ISSUE TITLE
[Desktop] Greaselion doesn't respect twitter-tips-enabled precondition

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#11664]
## Description 

Greaselion doesn't respect the `twitter-tips-enabled` precondition.

## Steps to Reproduce

Create a `Greaselion.json` file like this:

```
[
  {
    "urls": [
      "https://twitter.com/*",
      "https://*.twitter.com/*"
    ],
    "scripts": [
      "scripts/brave_rewards/publisher/twitter/twitter.bundle.js"
    ],
    "preconditions": {
      "twitter-tips-enabled": true
    }
  }
]
```

   1. Launch browser with a clean profile
   2. Enable Rewards
   3. Disable Twitter tipping in Rewards settings
   4. Relaunch browser
   5. Visit site that matches Greaselion rule with precondition

## Actual result:

Greaselion script runs even though Twitter tips is disabled.

## Expected result:

Greaselion script shouldn't run, since `twitter-tips-enabled` precondition hasn't been satisfied.

## Reproduces how often: 

Every time

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by emerick** [comment]
Seems like this code enables/disables the `rewards-enabled` and `twitter-tips-enabled` preconditions as a unit even though they're separate settings:

```
void RewardsServiceImpl::EnableGreaseLion(const bool enabled) {
  #if BUILDFLAG(ENABLE_GREASELION)
    if (greaselion_service_) {
      greaselion_service_->SetFeatureEnabled(greaselion::REWARDS, enabled);
      greaselion_service_->SetFeatureEnabled(greaselion::TWITTER_TIPS, enabled);
    }
  #endif
}
```

cc: @pilgrim-brave

**Comment by LaurenWags** [comment]
Per internal discussions, this issue should be tested when Twitter tipping with Greaselion lands (projected to be 1.17.x). As such, I have logged a follow up issue (https://github.com/brave/brave-browser/issues/11997) for that milestone and will be marking this one as `QA/No` and `release-notes/exclude`. Please adjust if needed.
