### ISSUE TITLE
[Desktop] having problems with ddos protection by Cloudflare and the missing page Wayback Machine message displaying

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#11665]
Description
 The missing page Wayback Machine message displaying shows up even with pages that are not missing just using website protection checks powered by Cloudflare, also called DDoS protection by Cloudflare.

Steps to Reproduce
  1.  Go to a site that uses DDoS protection by Cloudflare example https://audacityteam.org/
  2. You should see the message 
  3. If you do not see the message/DDoS protection by Cloudflare use incognito mode
  4. Repeat steps 1 and 2

Actual result:
![Screenshot 2020-09-10 204732](https://user-images.githubusercontent.com/5640119/92844550-fa2a6780-f3b3-11ea-9367-8a79fb2f23de.jpg)

Expected result:
To not show that message unless there is a 404 page or some error page like that.

Reproduces how often: 
Most times but Cloudflare must save something to their services and/or cookies because it does not happen every time you visit a site. The site I can reproduce it most is https://audacityteam.org/

Brave version:
Brave | 1.15.47 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Windows 10 OS Version 2009 (Build 19042.508)

Version/Channel Information:
This has happened since I can remember after you guys released a version that included the missing page Wayback Machine message.

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? I don't know, I don't have that installed

Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? No because I have never seen The missing page Wayback Machine message displaying like on brave.

**Comment by dentistformyeye** [comment]
Duplicate of #8401, which was closed as wontfix

**Comment by joejoejo** [comment]
Sorry about the duplicate post. Tried to search for the problem before posting and did not find anything.

**Comment by bsclifton** [comment]
No worries, @joejoejo - thanks for the report 😄 And thanks for the assist, @dentistformyeye
