### ISSUE TITLE
Screen artifacts with some elements, e.g. checkboxes

### ISSUE THREAD

**Issue by leshik** [brave/brave-browser#1167]
## Description 
I'm seeing some artefacts, mostly with checkbox elements in js popups, that are not present in Google Chrome, but exist in Brave Browser Dev.

## Steps to Reproduce

   1. Open any page that you know has checkboxes
   1. Start clicking them (checking on and off), or the space around

## Actual result:
Here is an example:
![brave-dev](https://user-images.githubusercontent.com/443678/45674669-c404d500-bb57-11e8-9967-066c02c9802a.gif)

## Expected result:
No visible artefacts.

## Reproduces how often: 
Always.

## Brave version (chrome://version info)
```
Brave	0.55.4 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)
Revision	ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS	Mac OS X
```
### Reproducible on current release:
No.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No, it doesn't matter.
- Is the issue reproducible on the latest version of Chrome? 
No.

**Comment by andrewcking** [comment]
Looks like the same issue as #1160 but also being seen in 0.55.4 (#1160 was reported on 0.55.3)

**Comment by bsclifton** [comment]
I believe this was fixed with https://github.com/brave/brave-core/pull/531

**Comment by kjozwiak** [comment]
Quick QA note: You can also use https://github.com/brave/qa-resources/blob/master/wikitemplate.md for verification to make that the checkboxes aren't disappearing. Please check several websites that use checkboxes when verifying.

**Comment by LaurenWags** [comment]
Verified passed with `macOS 10.12.6 x64`

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified with checkboxes on test plan as well as test plan from https://github.com/brave/brave-browser/issues/1160
cc @kjozwiak to try on his mac as well
