### ISSUE TITLE
[Android] Hide device info 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11695]
## Description 
Hide device info when tests are performed

## Steps to reproduce 

   1. Visit `https://deviceinfo.me`
   2. Result shows device details

## Actual result 

<img width=300 src=https://user-images.githubusercontent.com/17010094/93081729-9fc92980-f687-11ea-84cb-b9ee70615270.png>

## Expected result
Similar to FIrefox 
<img width=300 src=https://user-images.githubusercontent.com/17010094/93081724-9d66cf80-f687-11ea-9c8d-1177f7c87081.png>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.13.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? Yes

### Additional information

cc: @pes10k @anthonypkeane @diracdeltas @SergeyZhukovsky 
Originally reported in community https://community.brave.com/t/biggest-problems-with-brave/162328

**Comment by pes10k** [comment]
Good news, this is already fixed by https://github.com/brave/brave-browser/issues/9190 :)
