### ISSUE TITLE
[Android] Be able to customize Adblock list

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#11693]
## Description 

Hi,

@brave-browser-releases 

Regarding the Android version, can you please add a feature?

According to his design pattern, users can enter the whitelist by themselves.

https://i0.wp.com/shaadlife.com/wp-content/uploads/2020/07/ZomboDroid-12072020095655-min-scaled.jpg

Thank you.

**Comment by ryanbr** [comment]
hey @e-d-e  

Manually entering domains is a good feature request. In the interim, if you're wanting to whitelist a site. Just disabling `Trackers and Ads` in the shields url bar. Which will keep its setting when you visit this site again.

**Comment by bsclifton** [comment]
Custom filters are available via brave://adblock. The interface is not the easiest to use - and it's definitely not discoverable. We do have an issue captured for moving this into settings (under shields) to make it more discoverable:
https://github.com/brave/brave-browser/issues/8838
