### ISSUE TITLE
Typos and phrasing improvements in chrome://rewards

### ISSUE THREAD

**Issue by echosa** [brave/brave-browser#1169]
There are typos on `chrome://rewards`:

> The wallet and created here

should be

> The wallet created here

<img width="1041" alt="screen shot 2018-09-18 at 4 56 09 am" src="https://user-images.githubusercontent.com/133786/45679958-5927af80-baff-11e8-9193-7a9552dbf158.png">

---

> Do you know that you've been paying for the web content with your data for the digital ads? You didn't have a voice in it and worse, you're exposed to privacy and security risks

would be better worded without the extra "the"-s, and needs a period at the end, and a comma

> Do you know that you've been paying for web content with your data through digital ads? You didn't have a voice in it and, worse, you're exposed to privacy and security risks.

<img width="517" alt="screen shot 2018-09-18 at 5 00 21 am" src="https://user-images.githubusercontent.com/133786/45680140-c4718180-baff-11e8-9461-61bdfc419687.png">

---

> Get paid for the ads. And pay directly the favorite content creators at your will. That way, they can grow and continue delivering the content that delights you.

shouldn't start a sentence with "and" and could use some rewording:

> Get paid for the ads, and directly pay your favorite content creators at your will. That way, they can grow and continue delivering the content that delights you.

<img width="513" alt="screen shot 2018-09-18 at 5 02 07 am" src="https://user-images.githubusercontent.com/133786/45680238-04386900-bb00-11e8-94ac-4939743d0382.png">

---

> Set budget and browse normally. Your favorite sites get paid automatically.

would be better as

> Set a budget […]

or

> Set your budget […]

<img width="294" alt="screen shot 2018-09-18 at 5 03 30 am" src="https://user-images.githubusercontent.com/133786/45680304-35189e00-bb00-11e8-8109-cff4640297d9.png">

---

> A simple way to support content creators. Set monthly allowance and browse normally. Your favorite sites (content sites only) receive your contributions automatically. You can exclude sites from funding here.

Again, this would be better with 

> Set a monthly allowance […]

or

> Set your monthly allowance […]

Also, there's an extra `}` after 

> Your monthly allowance gets divided based on your attention metric.}

<img width="568" alt="screen shot 2018-09-18 at 5 10 14 am" src="https://user-images.githubusercontent.com/133786/45680687-267eb680-bb01-11e8-86f9-8ba8c1032e16.png">

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/46082086-34b97c00-c16c-11e8-9d67-f54aec809276.png)
`Your data is safe with our Shields` doesn't relate to Ads here. Should be removed or appropriate text should be added

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/46082320-d2ad4680-c16c-11e8-8114-59aeb79eb5b7.png)
![image](https://user-images.githubusercontent.com/17010094/46082327-d640cd80-c16c-11e8-970b-9acd8fc47504.png)

Bullet points should not have `.` at the end of sentence

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux
