### ISSUE TITLE
[Desktop] Provide an in-browser-action UI way to detect when Crypto Wallets is not the selected web3 provider

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11696]
## Description 

We have a setting for selecting the web3 provider here:
brave://settings/extensions

<img width="706" alt="Screen Shot 2020-09-14 at 10 20 45 AM" src="https://user-images.githubusercontent.com/831718/93097759-f88ec700-f673-11ea-8dfc-8b9e054d8598.png">

However, we should also add an indication within our browser action button UI that tells the user when we're not the selected web3 provider. 

This can be accomplished with an API which is currently already exposed to both Crypto Wallets and MetaMask:
`chrome.braveWallet.getWeb3Provider`. It returns the extension ID that is the current provider in a callback as the first param.

## Steps to Reproduce

   1. Install MetaMask
   2. Verify in settings that Crypto Wallets is not the selected Dapp provider brave://settings/extensions (MetaMask will be)
   3. Go to brave://wallet and login so the Crypto Wallets extension gets loaded
   4. Open the browser action button for Crypto Wallets

## Actual result:

No indication that Crypto Wallets is not the current web3 provider for Dapps.

## Expected result:

Some indication should be there so a user doesn't wonder why it isn't the web3 provider.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | Linux
Component | `1.0.17 Dev`

- Verified browser action UI shows info about CW not being the default web3 provider
![image](https://user-images.githubusercontent.com/17010094/100202096-c366e680-2ef8-11eb-9a27-32750e4966d6.png)
- Verified clicking on settings opens up the settings page and sets focus to extensions
----------
Verification passed on 

Brave | 1.19.31 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | Windows 10 OS Version 1809 (Build 17763.1577)
Component | `1.0.17 Dev`

- Verified browser action UI shows info about CW not being the default web3 provider
![image](https://user-images.githubusercontent.com/17010094/100203726-e1cde180-2efa-11eb-9120-eb8fc040bbdb.png)
- Verified clicking on settings opens up the settings page and sets focus to extensions
----------
Verification passed on 

Brave | 1.18.61 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | macOS Version 10.15.7 (Build 19H2)
Component | `1.0.17 Dev`

- Verified browser action UI shows info about CW not being the default web3 provider
![image](https://user-images.githubusercontent.com/17010094/100188852-01591000-2ee3-11eb-895a-64d6183b2235.png)
- Verified clicking on settings opens up the settings page and sets focus to extensions
