### ISSUE TITLE
[Desktop] Incorrect UserAgent is causing Unsupported OS error on some sites

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#11707]
## Description 
Unknown in UserAgent is causing issues on sites like zoom

## Steps to Reproduce

   1. Navigate to Devtools > Console
   2. Execute navigator.userAgent

## Actual result:
```
navigator.userAgent
"Mozilla/5.0 (Unknown; Intel Mac OS X ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.30 Safari/537.36"
```

## Expected result:
```
navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
```

## Reproduces how often: 
Easily

## Brave version (brave://version info)
1.16.14 Chromium: 86.0.4240.30 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel?  No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.6 x64` using the following build:

```
Brave | 1.16.17 Chromium: 86.0.4240.30 (Official Build) nightly (x86_64)
-- | --
Revision | 09f50eb5535879364cf00e72653462a509ef6bdc-refs/branch-heads/4240@{#552}
OS | macOS Version 10.15.6 (Build 19G73)
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/11707#issue-701243141 and ensured the correct user agent was being used as per the following:

```
--> navigator.userAgent

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.30 Safari/537.36"
```
