### ISSUE TITLE
Bookmark button colour doesn't update when switching between dark/light theme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1170]
## Description 

Bookmark button colour doesn't update when switching between dark/light theme

## Steps to Reproduce

   1. Set browser theme to dark/default
   2. Change theme to light
   3. Bookmark button doesn't change colour unless you click it 

## Actual result:

![bmkbtn](https://user-images.githubusercontent.com/17010094/45689772-ca2c8e80-bb22-11e8-8fbe-77aaff55d278.gif)

## Expected result:
Should change similar to other URL bar buttons

## Reproduces how often: 

100%

## Brave version (chrome://version info)

Brave | 0.55.4 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)
-- | --
Revision | ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS | Windows

### Reproducible on current release:

NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

#974 
cc: @kjozwiak @LaurenWags to verify on macOS

**Comment by LaurenWags** [comment]
Reproduced on macOS using 0.55.4

**Comment by bbondy** [comment]
@petemill merged label is only needed for PR. Thanks.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X
