### ISSUE TITLE
Purchase intent is not extracted from google.com

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#11704]
It works when searching google through URL bar.
It does not work when searching for keywords through google.com

This is a regression introduced in 1.14.x. Does not reproduce in 1.13.86.

Note: Issue found by @LaurenWags 

## Steps to Reproduce

1. Clean profile
1. Enable rewards
1. Wait till ads catalog and all components are downloaded
1. Close Brave
1. Open `google.com` and search for `amd`
1. Check `purchaseIntentSignalHistory` in `ads_service/client.json`

## Actual result:

Purchase intent is not extracted from google.com

## Expected result:
Purchase intent is extracted from google.com

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.14.79 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

Brave | 1.16.14 Chromium: 86.0.4240.30 (Official Build) nightly (64-bit)
-- | --
Revision | 09f50eb5535879364cf00e72653462a509ef6bdc-refs/branch-heads/4240@{#552}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @rebron @moritzhaller @tmancey

**Comment by tmancey** [comment]
Fixed as part of https://github.com/brave/brave-browser/issues/6000

**Comment by btlechowski** [comment]
@tmancey https://github.com/brave/brave-browser/issues/6000 is still open. Can I reopen this one and remove it from 1.20.x milestone?

**Comment by btlechowski** [comment]
Seems to be working.

Verification passed on

Brave | 1.28.98 Chromium: 92.0.4515.115 (Official Build) beta (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/127835655-abe71ada-fd38-475d-8ba1-4335b923cb9c.png)
