### ISSUE TITLE
Move ENS resolution outside of Crypto Wallets extension

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11708]
## Description 

In Crypto Wallets settings there is an IPFS gateway to use for ENS resolutions.
We should aggregate that usage inside of the other IPFS handling instead so it works always even if the Crypto Wallets extension is not in use. 

Further we currently resolve to:
https://app.ens.domains/name/vitalik.eth

If no record is set I don't think we should resolve for it.  We could show a suggestion for this though.

If the user is in an address field, we'd need to instead resolve to an address.

We'll use a Cloudflarea gateway for the initial implementation of this.

**Comment by DaniellMesquita** [comment]
Don't forget that UnstoppableDomains and ENS (.crypto, .eth, etc) should always appear in the address bar, even after resolving/redirection to an IPFS URL.

There should also have a button to copy the IPFS URL of a site or its own asset (integrate it on inspect element?).

**Comment by az1az1** [comment]
Also name resolution didnt work for me until i cleared my dns cache for some reason: sudo systemd-resolve --flush-caches

**Comment by bbondy** [comment]
For ENS I believe we could use the Cloudflare endpoint when crypto wallets is not enabled.
https://medium.com/the-ethereum-name-service/ens-partners-with-cloudflare-on-improved-eth-link-service-4801bf9148ff

**Comment by ilyaigpetrov** [comment]
> For ENS I believe we could use the Cloudflare endpoint when crypto wallets is not enabled.

It makes it easier to block all .eth sites, e.g., during some Internet shutdown or some censorship abuse.
Is it feasible to give user a choice: 1) either use a Cloudflare endpoint, 2) or use a own native instance like with Brave and IPFS?

**Comment by DaniellMesquita** [comment]
There are a lot of inspiration to be used from IPFS Companion, such as identifying an IPNS address and redirecting (visit Uniswap with IPFS Companion if you want to test) and showing the IPFS CID of an URL to copy/pin.

**Comment by bbondy** [comment]
Implemented here:
https://github.com/brave/brave-browser/issues/14477

It will be enabled by default on Nightly soon.
It can be enabled by default in  brave://flags with today's Nightly.
