### ISSUE TITLE
[Desktop] Remove Chromium cookie flyouts 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11709]
## Description 

Remove Chromium cookie flyouts 

## Steps to Reproduce

   1. Install/Upgrade to 1.16.x nightly 
   2. Visit a page
   3. Chromium cookie menu shows up

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/93114980-33641f80-f6b3-11ea-8e6b-1ccbab79f679.png)
![image](https://user-images.githubusercontent.com/17010094/93115002-395a0080-f6b3-11ea-84dd-6a2eca23a365.png)
![image](https://user-images.githubusercontent.com/17010094/93115012-3eb74b00-f6b3-11ea-8c65-e14109fddada.png)
![image](https://user-images.githubusercontent.com/17010094/93115030-44149580-f6b3-11ea-8b59-43e8952b2f8a.png)
![image](https://user-images.githubusercontent.com/17010094/93115048-47a81c80-f6b3-11ea-94d4-ae079e629417.png)

## Expected result:
Dont show Chromium message

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.16.12 Chromium: 86.0.4240.30 (Official Build) nightly (64-bit)
-- | --
Revision | `09f50eb5535879364cf00e72653462a509ef6bdc-refs/branch-heads/4240@{#552}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.15.63 Chromium: 86.0.4240.55 (Official Build) dev (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Reproduced the issue as described with `1.16.12` (default settings) using `neowin.net`:
<img width="1193" alt="Screen Shot 2020-09-25 at 10 33 12 AM" src="https://user-images.githubusercontent.com/28145373/94279800-9dce5880-ff1a-11ea-8684-a2c75948cd00.png">
<img width="1196" alt="Screen Shot 2020-09-25 at 10 33 36 AM" src="https://user-images.githubusercontent.com/28145373/94279804-9eff8580-ff1a-11ea-975f-51c32d9ab2e2.png">
<img width="1195" alt="Screen Shot 2020-09-25 at 10 33 51 AM" src="https://user-images.githubusercontent.com/28145373/94279809-a030b280-ff1a-11ea-8311-c0355c7db981.png">

Visited `neowin.net` using `1.15.63` (default settings) and there is no Chromium cookie bubble in the URL bar:
<img width="1195" alt="Screen Shot 2020-09-25 at 10 35 11 AM" src="https://user-images.githubusercontent.com/28145373/94279986-e128c700-ff1a-11ea-8436-44f7ee2fbc08.png">

Visited a few other sites, no Chromium cookie bubble on any of them (`pinterest.com`, `slashdot.org`, `cnn.com`).

--------
