### ISSUE TITLE
Remove window.web3 insertion 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11703]
## Description 

On  November 16, 2020 MetaMask will be removing window.web3 and using window.ethereum instead
https://github.com/MetaMask/metamask-extension/issues/8077

We should also not inject window.web3 for better cross compat with MetaMask around the same date.

To do this we will need to:
- Stop detecting for duplicate web3 objects in `app/scripts/inpage.js`
- Stop importing `'./lib/setupWeb3'` from within that file as well.
- Remove `app/scripts/lib/setupWeb3.js`
- Remove web3 references in `inpage-provider` dep. We should probably hard fork `inpage-provider` as well. It is still MIT licensed, but with recent MetaMask license changes on the metamask extension repo,  we should just maintain our own.

**Comment by srirambv** [comment]
@marshall can you add a test plan for this?

**Comment by bbondy** [comment]
Reverting so re-opening this.
