### ISSUE TITLE
[Desktop] Clicking on Brave Ads in KDE marks them as dismissed rather than clicked.

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#11713]
## Description 
Clicking on Brave Ads in KDE marks them as `dismissed` in the 7-day ads history instead of `clicked`

## Steps to Reproduce
   1. Install Brave on a Linux system with the KDE desktop installed.
   2. Wait for ad notification to appear.
   3. Click on ad notification and notice that the ad is loaded in a Brave tab.
   4. Go to 7-day ad history in `brave://rewards`

## Actual result:
All clicked ads are marked as `dismissed` instead of `clicked`.

## Expected result:
Clicked ads should be marked as clicked. Closed ads (clicking the X button on the KDE notification) should be marked as `dismissed` or `viewed`.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave: 1.13.86 Chromium: 85.0.4183.102 (Official Build) unknown (64-bit)
Revision: ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS: Linux

**More info:**
I am using an up-to-date Arch install as of Sep 14, 2020.
KDE Plasma 5.19.5
KDE Frameworks 5.74.0

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested.
- Can you reproduce this issue with the nightly channel? Not tested.

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
Closing issue as wont fix as this issue will be resolved by https://github.com/brave/brave-browser/issues/9592
