### ISSUE TITLE
[Desktop] Can't use date picker on Airbnb.com

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#11710]
## Description 

The date picker on Airbnb.com doesn't work unless Trackers & ads are set to "allow". Seems to be a Shields webcompat issue. Filing this bug for an external Brave user.

## Steps to Reproduce

   1. Go to airbnb.com
   2. Randomly pick a Location to visit, along with any check-in/check-out dates and hit search
   3. Pick any listing in the results
   4. On the listing page, click on the date range picker on the sticky righthand panel
   5.  See that it doesn't work

## Actual result:

Date picker hangs at loading state
<img width="1175" alt="Screen Shot 2020-09-14 at 10 52 32 AM" src="https://user-images.githubusercontent.com/2388823/93120794-bae06d00-f678-11ea-8b90-3bb2ce9ab95c.png">

## Expected result:
<img width="1245" alt="Screen Shot 2020-09-14 at 10 52 49 AM" src="https://user-images.githubusercontent.com/2388823/93120845-cfbd0080-f678-11ea-8933-07da2e1af4f8.png">

## Reproduces how often: 

Easily

## Desktop Brave version:

All versions have this issue

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? yes
- Does the issue resolve itself when disabling Brave Rewards?  n/a
- Is the issue reproducible on the latest version of Chrome? no

**Comment by pes10k** [comment]
@ryanbr looks like a filter list issue.  can you take a look when you have a chance?

**Comment by ryanbr** [comment]
Hey @karenkliu this should fix it, just a partial revert from another commit. Give it 24-48hrs, let me know of any issues.

I'll keep the ticket open until its confirmed.

**Comment by ryanbr** [comment]
Is it looking better @karenkliu ?

**Comment by karenkliu** [comment]
@ryanbr Yes it's fixed! :)
