### ISSUE TITLE
[Desktop][CW-Binance]Calls to fetch deposit info should be optimized 

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#11718]
Currently, calls to fetch deposit info and coin networks happen as part of the update interval, which fetches things like Balance and Prices. Once these deposit info is set, subsequent calls should not follow. It will remain as part of the user triggered refresh data action. This will greatly reduce request overhead.

Test Plan:
1. Perform a general regression test ensuring that deposit info is set correctly and is retained when refreshing data manually. There will not be visible behavior differences with this change.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (64-bit)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | Linux

- Verified deposit transaction works as expected
- Verified balance updates automatically once a deposit is done
- Verified balance updates manually when clicked on refresh after a deposit is done
----------------------
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (x86_64)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified deposit transaction works as expected
- Verified balance updates automatically once a deposit is done
- Verified balance updates manually when clicked on refresh after a deposit is done
-----------------------
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (64-bit)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | Windows 10 OS Version 1809 (Build 17763.1490)

- Verified deposit transaction works as expected
- Verified balance updates automatically once a deposit is done
- Verified balance updates manually when clicked on refresh after a deposit is done
