### ISSUE TITLE
[Desktop] Fingerprint webauthn doesn't work on nightly

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#11716]
## Description 
More details here: https://github.com/brave/brave-browser/issues/3642

## Steps to Reproduce

   1. Navigate to yubico.com/u2f
   2. Start the registration workflow

## Actual result:
 Fingerprint sensor option is not displayed

## Expected result:
 Fingerprint sensor option should be displayed

## Reproduces how often: 

Easily

## Brave version (brave://version info)
1.16.14 Chromium: 86.0.4240.30 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by kjozwiak** [comment]
@jumde reproduced the above issue using the following build:

```
Brave | 1.16.17 Chromium: 86.0.4240.30 (Official Build) nightly (x86_64)
-- | --
Revision | 09f50eb5535879364cf00e72653462a509ef6bdc-refs/branch-heads/4240@{#552}
OS | macOS Version 10.15.6 (Build 19G73)
```

STR:

* visited https://demo.yubico.com/webauthn-technical/registration
* started the authentication process

| Registration Process | Registration Process |
| :-------------: | :-------------: |
| <img width="932" alt="Screen Shot 2020-09-15 at 2 18 00 PM" src="https://user-images.githubusercontent.com/2602313/93248948-93fc6680-f75e-11ea-8e49-940f5dec2ad1.png"> | <img width="917" alt="Screen Shot 2020-09-15 at 2 18 08 PM" src="https://user-images.githubusercontent.com/2602313/93248931-8cd55880-f75e-11ea-9aac-293395fd74f2.png">  |

| Logging/Authenticating |
| :-------------: |
| <img width="967" alt="Screen Shot 2020-09-15 at 2 18 20 PM" src="https://user-images.githubusercontent.com/2602313/93249050-b7271600-f75e-11ea-9044-bf0714510af4.png"> |

**Comment by kjozwiak** [comment]
Clearing milestone after discussing with @jumde. We'll try getting this into a `1.15.x` HF but isn't urgent enough to release ASAP. We'll wait and add the above into the release when either a minor CR bump comes down the pipeline or we need to release ASAP due to a security issue/major regression.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.15.74 Chromium: 86.0.4240.80 (Official Build) (x86_64)
-- | --
Revision | 7ed88b53bda45a2d19efb4f8706dd6b6cad0d3af-refs/branch-heads/4240@{#1183}
OS | macOS Version 10.15.7 (Build 19H2)
```

* Verified using the STR/Cases outlined via https://github.com/brave/brave-core/pull/6751#issuecomment-707890654

Went through https://demo.yubico.com/webauthn-technical/registration and ensured that both `Built-in sensor` and `Built-in sensor` options worked without any issues.

**`Built-in sensor example`**

Example | Example | Example | Example |
--|--|--|--|
<img width="1219" alt="Screen Shot 2020-10-14 at 2 07 04 AM" src="https://user-images.githubusercontent.com/2602313/95950278-380b1900-0dc2-11eb-91b1-4999577a2202.png"> | <img width="1225" alt="Screen Shot 2020-10-14 at 2 07 12 AM" src="https://user-images.githubusercontent.com/2602313/95950287-3d686380-0dc2-11eb-80a8-4d411d5f4804.png"> | <img width="1228" alt="Screen Shot 2020-10-14 at 2 07 19 AM" src="https://user-images.githubusercontent.com/2602313/95950304-41948100-0dc2-11eb-8a8f-09c01b0eaeeb.png"> | <img width="1212" alt="Screen Shot 2020-10-14 at 2 07 34 AM" src="https://user-images.githubusercontent.com/2602313/95950318-478a6200-0dc2-11eb-99e8-91d05f762511.png">

Example | Example | Example |
--|--|--|
<img width="1223" alt="Screen Shot 2020-10-14 at 2 07 41 AM" src="https://user-images.githubusercontent.com/2602313/95950417-7a345a80-0dc2-11eb-8041-2a7f31ce4992.png"> | <img width="1235" alt="Screen Shot 2020-10-14 at 2 07 54 AM" src="https://user-images.githubusercontent.com/2602313/95950426-7d2f4b00-0dc2-11eb-801f-09b4f52147f1.png"> | <img width="1229" alt="Screen Shot 2020-10-14 at 2 08 00 AM" src="https://user-images.githubusercontent.com/2602313/95950436-81f3ff00-0dc2-11eb-9da3-141264432208.png">

**Comment by jfirebaugh** [comment]
I just updated Brave to 1.15.72 and I'm now locked out of sites where I was using Fingerprint webauthn.

I tried Brave Nightly but it crashes immediately on startup.

**Comment by kjozwiak** [comment]
@jfirebaugh definitely not good! Regarding the crashes that you're experiencing with `Nightly` & `BETA`, does this only happen when going through the `WebAuthn` flow? Does it happen when you don't have a Yubikey plugged in?

> I just updated Brave to 1.15.72 and I'm now locked out of sites where I was using Fingerprint webauthn.

Out of curiosity, can you login into the websites that are having issues with WebAuthn using Chrome?

**Comment by probablyup** [comment]
This should be reopened, I just encountered the issue using fingerprint sensor on my 2019 MBP running Brave on Catalina. I was attempting to authenticate with onelogin.com which does work on Edge & Chrome.
