### ISSUE TITLE
staging env is being used for wallets

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1171]
## Description 
Seems as though the 0.55.3 build (and possibly before) are using the staging environment for Brave Rewards Wallets. Per discussion with @NejcZdovc they should be production wallets.

## Steps to Reproduce
Scenario 1: 
Enable rewards.
Claim UGP.
Note expiration date of UGP is in 2037 - this does not appear to be a valid UGP grant (those expire in approximately 3 months) and matches those grants used by v1 staging on browser-laptop. 

Scenario 2:
On browser-laptop version (0.23.107), create a staging wallet. You do not need to put any funds into it. 
Backup staging wallet.
Go to brave-core. 
Enable rewards if not already enabled.
Use the restore functionality with the wallet created in b-l.
Wallet is restored successfully.

## Actual result:
Appears as though staging wallets are being used.

## Expected result:
Production wallets should be used.

## Reproduces how often: 
Easily

## Brave version (chrome://version info)
Brave | 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)
Revision | ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS | Mac OS X

### Reproducible on current release:
no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by NejcZdovc** [comment]
initial work was done here https://github.com/brave/brave-core/pull/392

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

- confirmed Brave Rewards are using production not staging wallets
