### ISSUE TITLE
[Android] Auto Rotation Bug/Regression

### ISSUE THREAD

**Issue by pidus** [brave/brave-browser#11717]
## Description 
Screen auto rotates after privacy report icon is tapped even though auto-rotation is blocked in the system. 
![IMG_20200915_085036](https://user-images.githubusercontent.com/11857051/93161645-9778f900-f730-11ea-97a9-f6a98963f16f.jpg)

## Steps to reproduce 

   1. Align the phone vertically. Turn of auto-rotation in the system. 
   2. Open Brave. Tap on the privacy report icon on the homepage. 
   3. Rotate the phone. 

## Actual result 
Screen auto-rotates bypassing the phone's system setting. 

## Expected result
Screen should not auto-rotate. 

## Issue reproduces how often 
Easily. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes. 
- Can you reproduce this issue with the current Play Store Beta version? Not tested. 
- Can you reproduce this issue with the current Play Store Nightly version? Not tested. 

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 7.1.1
   
## Brave version
1.13.87

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by pidus** [comment]
Restating the browser fixes the issue. But can be reproduced again.

**Comment by srirambv** [comment]
Possibly fixed with https://github.com/brave/brave-browser/issues/11632 

cc: @deeppandya

**Comment by deeppandya** [comment]
@srirambv @pidus Created PR for the issue : https://github.com/brave/brave-core/pull/6650

**Comment by srirambv** [comment]
Closing in favour of #11632 which is already uplifted
