### ISSUE TITLE
Rename web3 provider to Ethereum provider

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11711]
## Description 

Since `windows.web3` is going away it doesn't make sense to call it a web3 provider anymore. We should call it an Ethereum provider. 

<img width="249" alt="Screen Shot 2020-09-14 at 3 14 26 PM" src="https://user-images.githubusercontent.com/831718/93128120-03aa1d00-f69d-11ea-99e9-5bbc416290f2.png">

New text: Ethereum provider for using Dapps

<img width="843" alt="Screen Shot 2020-09-14 at 3 15 33 PM" src="https://user-images.githubusercontent.com/831718/93128227-29cfbd00-f69d-11ea-8f73-113cf8a3f1c6.png">

New text: Would you like to start Crypto Wallets for Ethereum support?

# Test Plan

Just make sure chrome://settings in the Extension setting shows the right text. Also the infobar which comes up when you visit cryptokitties.co

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.16.55 Chromium: 86.0.4240.72 (Official Build) dev (64-bit)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

Verified text was updated `Ethereum provider for using Dapps` in `brave://settings/extensions`:
![image](https://user-images.githubusercontent.com/34715963/95360865-4cd04400-08cc-11eb-96f3-f9a46dfdcef0.png)
![image](https://user-images.githubusercontent.com/34715963/95360838-43df7280-08cc-11eb-9a31-b0b4986e4411.png)

Verified infobar on `cryptokitties.co`:
![image](https://user-images.githubusercontent.com/34715963/95361316-e0097980-08cc-11eb-9bb0-a4cf92f4bccc.png)
![image](https://user-images.githubusercontent.com/34715963/95361334-e5ff5a80-08cc-11eb-8668-a1fdf2a44f9e.png)


Verified Polish locale
![image](https://user-images.githubusercontent.com/34715963/95361645-47272e00-08cd-11eb-878f-b329984039f9.png)
![image](https://user-images.githubusercontent.com/34715963/95361603-3b3b6c00-08cd-11eb-9db5-8a2cb8d40372.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (x86_64)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified `brave://settings/extensions` is renamed to `Ethereum provider for using Dapps` 
![image](https://user-images.githubusercontent.com/17010094/95853185-e96f6780-0d4c-11eb-89fb-d7516c7eeef2.png)
- Verified setup info bar has the changed text `Would you like to start Crypto Wallets for Ethereum support?`
![image](https://user-images.githubusercontent.com/17010094/95853324-220f4100-0d4d-11eb-8559-b12fb26aa95f.png)

----------

Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (64-bit)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | Windows 10 OS Version 1809 (Build 17763.1490)

- Verified `brave://settings/extensions` is renamed to `Ethereum provider for using Dapps` 
![image](https://user-images.githubusercontent.com/17010094/95853501-70244480-0d4d-11eb-901c-7d96579597d4.png)
- Verified setup info bar has the changed text `Would you like to start Crypto Wallets for Ethereum support?`
![image](https://user-images.githubusercontent.com/17010094/95853532-7f0af700-0d4d-11eb-9407-7cabc88cd9a4.png)
