### ISSUE TITLE
Support CNAME adblocking

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#11712]
The API described in #7117 is primarily used by extensions to block resources that served from many different domains to circumvent traditional adblocking techniques. Similarly, Brave's most important use-case for the DNS resolution API is to integrate it with Shields.

Shields should block any network requests where either the original URL or that URL's canonical name (DNS CNAME record) matches any adblock rules.

Since our network blocking is done in C++ code, this doesn't necessarily need to be exposed as a Javascript API.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.63 Chromium: 87.0.4280.49 (Official Build) unknown (x86_64)
-- | --
Revision | f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified test plan from https://github.com/brave/brave-core/pull/6640. Confirmed `https://xxxx.mathon.fr/xxxxxxxxxxx.js` listed in shields with above build. Confirmed `https://static.criteo.net/js/ld/ld.js` is not listed in shields on Network tab of Dev Tools.

<details>
<summary>Screenshots</summary>

<img width="1484" alt="Screen Shot 2020-11-09 at 7 08 43 AM" src="https://user-images.githubusercontent.com/28145373/98539753-dae87300-225a-11eb-8844-5c640974db7b.png">
<img width="556" alt="Screen Shot 2020-11-09 at 7 10 20 AM" src="https://user-images.githubusercontent.com/28145373/98539758-dc19a000-225a-11eb-8c05-ed99a471555a.png">

</details>

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.66 x64 beta build
- Verified `https://xxxx.mathon.fr/xxxxxxxx.js` is blocked 
- Verified `https://static.criteo.net/js/ld/ld.js` is not listed 
![image](https://user-images.githubusercontent.com/17010094/98832541-da0b3900-2434-11eb-9a5e-4eb4d1fd56c5.png)
------------
Verification passed on Samsung Tab A with Android 10 running 1.17.66 x64 beta build
- Verified `https://xxxx.mathon.fr/xxxxxxxx.js` is blocked 
- Verified `https://static.criteo.net/js/ld/ld.js` is not listed 
![image](https://user-images.githubusercontent.com/17010094/98832766-1e96d480-2435-11eb-967f-6741183f5ad9.png)
