### ISSUE TITLE
Dapp detection script should be minified

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11725]
Currently there's a script that gets inserted to pages for Dapp detection.
It should be minified but it isn't currently.

Old:

<img width="525" alt="Screen Shot 2020-09-15 at 4 13 41 PM" src="https://user-images.githubusercontent.com/831718/93259886-8f3fae80-f76e-11ea-9397-009685cf5733.png">

New:
<img width="1202" alt="Screen Shot 2020-09-15 at 4 15 34 PM" src="https://user-images.githubusercontent.com/831718/93259989-b4342180-f76e-11ea-8e60-13482af15417.png">

# QA plan

1. Fresh profile
2. Load Crypto Kitties
3. Use DOM inspector and look in the <head> of the scripts tag
4. Ensure it looks like the above screenshot in the New section, and not the Old section.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.16.55 Chromium: 86.0.4240.72 (Official Build) dev (64-bit)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified the injected script is minified:
![image](https://user-images.githubusercontent.com/34715963/95362875-07f9dc80-08cf-11eb-8194-b2ea34da3498.png)
