### ISSUE TITLE
chrome incognito icon is used in allow cookies sites list

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11738]
## Description 

chrome incognito icon is used in allow cookies sites list
## Steps to Reproduce

   1. Open Brave 1.16.x or 1.14.x
   2. Visit brave://settings/cookies
   3. Open a PT window and visit any site
   4. Come back to brave://settings/cookies again
   5. chrome incognito icons are displayed under `Sites that can always use cookies` section
   

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/93363579-18d1a800-f865-11ea-9f75-6405a3481513.png)

## Expected result:
Brave branded icons should be displayed

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.16.19 Chromium: 86.0.4240.30 (Official Build) nightly (64-bit)
-- | --
Revision | 09f50eb5535879364cf00e72653462a509ef6bdc-refs/branch-heads/4240@{#552}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron

**Comment by mihaiplesa** [comment]
@brave/design @mherrmann will help us with this if you can point us to which icons to use.

**Comment by mherrmann** [comment]
We need a 20x20 SVG to replace the icon in the above screenshot.

**Comment by karenkliu** [comment]
Here you go!

[private-mode.svg.zip](https://github.com/brave/brave-browser/files/5496227/private-mode.svg.zip)

**Comment by mherrmann** [comment]
Thank you @karenkliu!

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.57 Chromium: 87.0.4280.66 (Official Build) beta (64-bit)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | Windows 10 OS Version 2004 (Build 19041.572)

```
- Verified the STR from the description

Light mode:
![image](https://user-images.githubusercontent.com/38657976/99656601-1cf78d00-2a83-11eb-9198-69e3ce552d9c.png)

Dark mode:
![image](https://user-images.githubusercontent.com/38657976/99656761-4e705880-2a83-11eb-975e-7cafa32d7d66.png)
