### ISSUE TITLE
[Android] Opening and closing Privacy Reports flyout too quickly causes crash

### ISSUE THREAD

**Issue by intrnl** [brave/brave-browser#11731]
## Description 
Opening and closing Privacy Reports flyout too quickly causes a crash

## Steps to reproduce 

   1. Open a new tab
   2. Open the Privacy Reports flyout
   3. Quickly close it before the stats shows up

## Actual result 
Browser crash
https://streamable.com/ozgznn

## Expected result
Browser shouldn't crash

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Untested
- Can you reproduce this issue with the current Play Store Beta version? Untested
- Can you reproduce this issue with the current Play Store Nightly version? Yes, 1.16.17

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.16.17, still reproducible on 1.16.46

**Comment by srirambv** [comment]
I have seen this happen on espn.com as it keeps blocking one of the scripts and the counter keeps going up which causes the crash.

**Comment by intrnl** [comment]
Recent Nightly versions doesn't seem to cause this, closing.
