### ISSUE TITLE
Update stale git ref in ethereum-remote-client yarn.lock

### ISSUE THREAD

**Issue by marshall** [brave/brave-browser#11745]
## Description 
Doing a fresh `git clone` of brave/ethereum-remote-client and building updates the `yarn.lock` file with a new git hash for the `eth-hd-keyring` dependency 

## Steps to Reproduce

   1.  `git clone https://github.com/brave/ethereum-remote-client`
   2.  `yarn install`
   3. `git status`

## Actual result:
The `yarn.lock` lockfile has local changes from the build process

## Expected result:

`yarn.lock` is unchanged by a local build

**Comment by srirambv** [comment]
Marked as QA/No
