### ISSUE TITLE
Fix breakage on some sites that use addthis scripts

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#11744]
Some websites that use the `addthis_widget.js` script, e.g. https://www.rhmodern.com/catalog/product/product.jsp?productId=prod14970086&categoryId=cat7150028, do not function as expected.

This is due to an inconsistency between how `adblock-rust` and uBO handle redirect and important rules. More information on the discrepancy can be found [here](https://github.com/uBlockOrigin/uBlock-issues/issues/1224). This should be fixed by updating `adblock-rust`.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.16.46 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Ubuntu 18.04 LTS

Reproduced the issue on 1.15.x
![image](https://user-images.githubusercontent.com/34715963/94644885-ba87d900-02ea-11eb-9c41-da9f6da6b4e8.png)

Verified the test plan from https://github.com/brave/brave-core/pull/6658
![image](https://user-images.githubusercontent.com/34715963/94644955-e73bf080-02ea-11eb-8776-b8a5bc397069.png)

**Comment by srirambv** [comment]
Verification passed on the following device running 1.16.69 x64 build
- Verified image is loaded as expected

OnePlus 6T | Samsung Tab A
-- | --
<img width=900 src=https://user-images.githubusercontent.com/17010094/96248000-c938e600-0fa2-11eb-9756-d0b6df03d95c.png> | ![image](https://user-images.githubusercontent.com/17010094/96247989-c4743200-0fa2-11eb-87a6-17b60d602786.png)
