### ISSUE TITLE
add Brave Rewards information to chrome://version page

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1174]
## Description 
Per discussion in b-c triage meeting, we should add some Brave Rewards information to chrome://version page to assist with supporting users. Some items are:
- wallet `paymentId` (this is used for support when users have wallet issues)
- wallet status such as contribution in progress, etc (since this is not displayed on chrome://rewards page)

cc @davidtemkin @NejcZdovc @brave/legacy_qa for additional ideas on Rewards items to be displayed

**Comment by kjozwiak** [comment]
Maybe have a field that lets us know if the private key has been corrupted or not? Rather then having users check their keys and trying to explain what a corrupted key should look like, we could have something in `chrome://versions` that basically says:

* `rewards backup key: OK` or `rewards backup key: corrupted`

Unless of course, the use case changes for Rewards and this isn't valid anymore.

**Comment by LaurenWags** [comment]
It doesn't look like we're showing the Last Contributed Date (for Brave Auto Contribute) anywhere on Rewards page, maybe that's a candidate to show as well?

**Comment by davidtemkin** [comment]
I agree @LaurenWags -- that should go here as support info

**Comment by srirambv** [comment]
I would suggest adding the details to `About Brave` rather than `chrome://version` only because its relates more to how we request `About Brave` info. Also its easeir to do it from hamburger menu and `chrome://version` doesn't have an easy shortcut on the UI, unless we add a shortcut similar to Brave pages

**Comment by davidtemkin** [comment]
I generally agree, but If we do that @srirambv , we would need to hide it under a "support info" link, don't want to surface this info at the top level of "about Brave"

**Comment by kjozwiak** [comment]
I personally think we should keep `chrome://settings/help` (`About Brave`) as clean as possible as that's where users will be redirected when checking for updates. I'm not sure if it's a good idea to have a wall of text with a bunch of debugging information on that page. The update page should be as clean as possible IMO.

System information should always go into a single area. Asking users to grab information from `chrome://settings/help` (`About Brave`) & `chrome://version` doesn't make sense. Easier to head into one area like `chrome://version` and having everything there.

**Comment by bbondy** [comment]
See about:adblock for an example of a page that we added for some extra information for support.  Mainly to see if regional adblocking is in use or not.
We could do something similar.

**Comment by bsclifton** [comment]
@NejcZdovc @ryanml @jasonrsadler would we be able to get this in before 1.0? 😊

**Comment by NejcZdovc** [comment]
@bsclifton probably not

**Comment by davidtemkin** [comment]
We need to find a way to get this, or something like it, in before 1.0. We do not want to be live with millions of users on rewards with no clear way of supporting them. cc: @mrose17 as it is part of the reliability/diagnosability/supportability project.

**Comment by mrose17** [comment]
my goal is to work on this with @tmancey's help and to have it into the development traincycle with the other brave ads work that we are doing.

**Comment by emerick** [comment]
@mrose17 Just a heads up: @bbondy, @NejcZdovc, and I spoke and we thought it would make more sense to have a separate page for this called chrome://rewards-internals/ versus adding it to chrome://version. It will simplify development for us and Chrome already does this for things like chrome://sync-internals/ so there's precedent for this approach. Let me know what you think, but I'll head down that path for now.

**Comment by davidtemkin** [comment]
@emerick @bbondy @NejcZdovc I'd like to hear what support has to say, but it seems better to be able to send users to one destination and have them click on something to get the necessary info. We would then have one place to send people at the start of the diagnosis process. . 

e.g., adding a link at bottom like the current "get help with Brave" which could either show the necessary info inline or take them to the right page.

**Comment by NejcZdovc** [comment]
@davidtemkin we can always add link in `chrome://version` like `More detailed info about rewards`

**Comment by mrose17** [comment]
i think the issue is that making many changes to `chrome://version` is going to be a maintenance "issue". in contrast, having one link to a page that we completely control is a lot less error-prune and frustrating...

**Comment by davidtemkin** [comment]
This info needs a home base. See macOS  "About this Mac" for a reference point. 

Let's go with a link from About Brave (which is accessible via menu -- good)

**Comment by emerick** [comment]
Sounds good!

**Comment by bridiver** [comment]
@davidtemkin adding a link for this to `chrome://version` requires a lot of patching and doesn't seem necessary or even desirable really since it's designed for QA and other "advanced" users. Is it really necessary?

**Comment by bridiver** [comment]
if we want a link somewhere it makes much more sense to me to have it in the rewards UI and that doesn't require any patching

**Comment by davidtemkin** [comment]
@bridiver What's important isn't where it goes. What we need is diagnostic information that a user can share with us to diagnose problems with Brave Rewards , that can easily be found and copy/pasted without inordinate effort. It can go in the Rewards UI; we'd need to figure out where/how exactly.

**Comment by bbondy** [comment]
Let's split this PR in 2 so we can land the important part that everyone agrees on without further discussion. Then PR the rest for a second issue to discuss the 2 possibilities.

**Comment by NejcZdovc** [comment]
I agree. So let's remove link from `chrome://version` and create separate issue for it.

cc @emerick @kjozwiak @LaurenWags

**Comment by kjozwiak** [comment]
> I agree. So let's remove link from `chrome://version` and create separate issue for it.
> 
> cc @emerick @kjozwiak @LaurenWags

Sounds good 👍 Created https://github.com/brave/brave-browser/issues/3538.

**Comment by bridiver** [comment]
@davidtemkin my thought was just to move the link from `brave://version` to `brave://rewards`

**Comment by emerick** [comment]
The page is currently a static snapshot in time and doesn't dynamically update itself as data changes. Do we need to update dynamically or is a "snapshot" view acceptable? Another alternative could be a Refresh button, so it's obvious that the view is a snapshot.

**Comment by LaurenWags** [comment]
I think we do need some way to refresh this as users can restore wallets, so if the data is a snapshot it sounds like it could potentially be out of sync with what their actual wallet info is.

**Comment by kjozwiak** [comment]
Agreed with @LaurenWags. Making it dynamic is probably ideal. It will make support more complicated as we'll also need to make sure that the data that was given to us is actually the current state and not a snapshot of a previous state which might not be as useful. Could lead to confusion in terms of support.

I'm ok with having a "refresh" button if updating the information automatically is more difficult to implement. We can always ask users to hit the refresh button before submitting the data when they're receiving support. However, there's still a risk of users not listening and sharing data that was from an old Reward state if they don't hit that refresh button.

**Comment by NejcZdovc** [comment]
@emerick correct me if I am wrong, but doesn't data update if you reload a page? I think we don't need refresh button if that is the case.

**Comment by srirambv** [comment]
@NejcZdovc @emerick @bridiver  can't we have a `brave://rewards-internals` page for logging and other debug info which is dynamic? Personally i feel rewards page is cramped up as it is and probably not a wise idea to have anymore on that page

**Comment by emerick** [comment]
@NejcZdovc Strangely enough, the data on the page only updates if you create a new tab; pressing the browser Reload button isn't enough to initiate it. It's relatively easy for me to add a "Refresh" button to the page, so will do that for now and then we can think about making it more dynamic down the line.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1139
`brave://rewards-internals/` works fine
`brave://version/` does not link to `brave://rewards-internals/`. Logged https://github.com/brave/brave-browser/issues/3806
