### ISSUE TITLE
Hide "Passwords" entry in the "Safety check" section of the Settings UI.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#11741]
## Description 

Starting with Chromium 86, there is a "Safety Check" section in the Settings UI. One of the items in the section is "Passwords" which, to work, requires a connected user account. Because Brave doesn't have a connected user account the item needs to be hidden.

## Steps to Reproduce

   1. Open Brave
   2. Navigate to brave://settings/safetyCheck
   3. Click "Check now"
   4. See items in the results (one of them is "Passwords"). 

## Expected result:
   "Passwords" item is not shown.

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.16.20 (Nightly).

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.15.60 Chromium: 86.0.4240.42 (Official Build) dev (64-bit)
-- | --
Revision | 418ccfc2b69112bd79d5ffb38b533642e64e6af8-refs/branch-heads/4240@{#773}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/94123636-ab7bd380-fe71-11ea-97fe-5903147c7fdf.png)

**Comment by fmarier** [comment]
There's another piece of this at the bottom of `brave://setttings`:
![Screenshot from 2020-10-05 14-00-28](https://user-images.githubusercontent.com/167821/95131585-27e4a100-0713-11eb-84b0-324ddbec7919.png)
which needs to be modified because we don't currently offer any data breach notifications (though we want to in #12001).

I'd suggest the following:
> Brave can help keep you safe from malicious websites, bad extensions and more

**Comment by srirambv** [comment]
@fmarier logged https://github.com/brave/brave-browser/issues/12008 as suggestion. Since the issue is already fixed and verified should not be reopening the issue.
