### ISSUE TITLE
[Desktop] Learn more (on about page) should go to a more helpful support page

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#11746]
## Description 
`Learn more` link should go to a more helpful support page for Windows users
![image](https://user-images.githubusercontent.com/4733304/93390978-5f9eae00-f823-11ea-900f-b5584631b7c5.png)

## Steps to Reproduce

   1. Go to brave://settings/help
   2. Experience an error updating (??)
   3. Click the `Learn more` link

## Actual result:
It goes to https://community.brave.com?p=update_error

## Expected result:
It should go to https://support.brave.com/hc/en-us/articles/360042816611-Why-isn-t-Brave-updating-automatically-on-Windows-

**Comment by bsclifton** [comment]
I'll try to find a proper way to test this on Windows and macOS/Linux

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.16.54 Chromium: 86.0.4240.72 (Official Build) dev (64-bit)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified by closing the browser during update and immediately relaunching it.
Verified `Dowiedz się więcej` (`Learn more`) is shown

![image](https://user-images.githubusercontent.com/34715963/95314135-38bb2100-0891-11eb-876b-d3f50fdb8a4b.png)

Verified `Learn more` points to `https://support.brave.com/hc/en-us/articles/360042816611-Why-isn-t-Brave-updating-automatically-on-Windows-`
![image](https://user-images.githubusercontent.com/34715963/95314175-42dd1f80-0891-11eb-9612-6f2e870057be.png)
