### ISSUE TITLE
Branding issues in CR 86

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11757]
## Description 

The text "**You’ll still get Safe Browsing protection, where available, in other Brave services, like Gmail and Search"** needs to removed from `Safe Browsing` section in brave://settings/security. As brave doesn't use google services like gmail and serach

## Steps to Reproduce

   NA

## Actual result:

The text "You’ll still get Safe Browsing protection, where available, in other Brave services, like Gmail and Search" is displayed in `Safe Browsing` section in brave://settings/security.
![image](https://user-images.githubusercontent.com/38657976/93455858-854ab680-f8fa-11ea-9b54-90bf6d770436.png)

## Expected result:

The text "You’ll still get Safe Browsing protection, where available, in other Brave services, like Gmail and Search" needs to removed from `Safe Browsing` section in brave://settings/security. As brave doesn't use google services like gmail and serach
## Brave version (brave://version info)

Brave | 1.16.20 Chromium: 86.0.4240.30 (Official Build) nightly (64-bit)
-- | --
Revision | 09f50eb5535879364cf00e72653462a509ef6bdc-refs/branch-heads/4240@{#552}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @karenkliu @rebron @mkarolin

**Comment by mkarolin** [comment]
@rebron same as https://github.com/brave/brave-browser/issues/11345

**Comment by kjozwiak** [comment]
> @rebron same as #11345

Closing as duplicate as per the above.
