### ISSUE TITLE
Auto-contribute list should only contain included publishers

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#1175]
Count of excluded publishers should be a part of the state, and not filtered for on the client side

**Comment by diracdeltas** [comment]
what is sent in the fetch? (and what is the response)

**Comment by ryanml** [comment]
@rebron @diracdeltas sorry for the confusion, there was not a "fetch" involved with this one (no http requests/server calls). This was just an issue with the auto-contribute list grabbed from the native ledger containing both included/excluded publishers. I've updated the issue title.

cc: @NejcZdovc

**Comment by diracdeltas** [comment]
@ryanml thanks for clarifying!

**Comment by kjozwiak** [comment]
@ryanml is there anything QA can do here in terms of verification? There's not much information here in terms of cases/test plans that QA can follow. If there's nothing required here, can you please mark this as `QA/No`? If there's something that QA should verifying here, can you please add some test cases and add the `QA/Yes` label. Thanks!

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified test plan on Linux VM and works great
