### ISSUE TITLE
Permissions requests should be cancelled when closing a locked connection window 

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#11764]
Original video of the issue:
![web3-close-bug](https://user-images.githubusercontent.com/8732757/93569556-902b3880-f946-11ea-9f13-dd2ef0f028e4.gif)

## Test Plan
1. Setup Crypto Wallets
2. Lock the wallet
3. Navigate to a dapp such as `cryptokitties.co`
4. Click "Start" to connect your wallet
5. Close the popup window without entering your password

## Actual
6. You are unable to connect again, seeing errors in the web console

## Expected
7. You can open another connection window and connect after unlocking your wallet via the popup

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit) 
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Linux
Component | `1.0.16 dev`

- Verified permission request is only prompted once when closing a locked connection window
---------------------

Verification passed on 

Brave | 1.17.50 Chromium: 86.0.4240.111 (Official Build) dev (64-bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Windows 10 OS Version 1809 (Build 17763.1518)
Component | `1.0.16 dev`

- Verified permission request is only prompted once when closing a locked connection window

---------------------
Verification passed on 

Brave | 1.18.5 Chromium: 86.0.4240.111 (Official Build) nightly (x86_64)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | macOS Version 10.15.7 (Build 19H2)
Component | `1.0.16 dev`

- Verified permission request is only prompted once when closing a locked connection window
