### ISSUE TITLE
GH inline Tip button is broken on few GH pages

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11766]
## Description 

Regression of https://github.com/brave/brave-browser/issues/5040
GH inline Tip button is broken on few GH pages

## Steps to Reproduce

Pages that are broken are listed below:
 1. Tip button on stars tab of user profile - https://github.com/feross?tab=stars
 2. Tip button on commits > branch name - https://github.com/brave/brave-core/commits/
 3. Tip button on people page of org - https://github.com/orgs/brave/people
 4. Tip button on team members page - https://github.com/orgs/brave/teams/android/members

## Actual result:

GH inline Tip button is broken on few GH pages
![image](https://user-images.githubusercontent.com/38657976/93574725-64e03200-f9b6-11ea-842f-2abdd803e8ae.png)
![image](https://user-images.githubusercontent.com/38657976/93574796-79bcc580-f9b6-11ea-890e-3d5212989602.png)

## Expected result:
All GH pages should show Tip inline button

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.16.23 Chromium: 86.0.4240.30 (Official Build) nightly (64-bit)
-- | --
Revision | 09f50eb5535879364cf00e72653462a509ef6bdc-refs/branch-heads/4240@{#552}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes but not in 0.69.x
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by LaurenWags** [comment]
tip button was specifically removed from the org's people page: https://github.com/brave/brave-core/pull/5215

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.17.53 Chromium: 86.0.4240.111 (Official Build) dev (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

```
- Verified the STR from the description
- Logged https://github.com/brave/brave-browser/issues/12383

<details>
<summary>GH inline button on various GH pages</summary>

Tip button on stars tab of user profile - https://github.com/feross?tab=stars
![image](https://user-images.githubusercontent.com/38657976/97583630-2c079400-1a1d-11eb-894b-265e54c9a79d.png)

Tip button on commits > branch name - https://github.com/brave/brave-core/commits/
![image](https://user-images.githubusercontent.com/38657976/97583761-4c375300-1a1d-11eb-80c0-b7392d69e586.png)

Tip button on people page of org - https://github.com/orgs/brave/people
![image](https://user-images.githubusercontent.com/38657976/97583693-3b86dd00-1a1d-11eb-9aa5-7583b22317ab.png)

Tip button on team members page - https://github.com/orgs/brave/teams/android/members
![image](https://user-images.githubusercontent.com/38657976/97583847-6709c780-1a1d-11eb-8c1e-faa2f8f3a646.png)

Tip button the PR page
![image](https://user-images.githubusercontent.com/38657976/97584112-ae905380-1a1d-11eb-8ba2-260d980fdfa4.png)

Tip button on gists page
![image](https://user-images.githubusercontent.com/38657976/97585573-4b9fbc00-1a1f-11eb-9bd0-4da449eca24d.png)

* Verified tip banner showed `profile name on GitHub` if existed and `username on GitHub` if it did not
![image](https://user-images.githubusercontent.com/38657976/97586005-c36de680-1a1f-11eb-8df9-dcae4ad5f7a6.png)

![image](https://user-images.githubusercontent.com/38657976/97586089-df718800-1a1f-11eb-8e8b-49fcc2a512c8.png)

</details>
