### ISSUE TITLE
remove login flow from rewards if in "Disconnected" state - Follow up to #11528

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11760]
## Description 

As per https://github.com/brave/brave-browser/issues/11528, we removed the "Disconnected" login flow/state from `brave://rewards` but haven't removed it from the panel which should have also been removed.

## Steps to Reproduce

   1. Install a version with login flow (ex. 1.14.x) and enable Rewards
   2. Login with KYC'd uphold account
   3. Disconnect KYC account
   4. Click on `Disconnected` button via the rewards panel

You'll notice that the "Disconnected" state/flow was removed from `brave://rewards` as per https://github.com/brave/brave-browser/issues/11528.

## Actual result:

<img width="432" alt="Screen Shot 2020-09-17 at 12 50 41 PM" src="https://user-images.githubusercontent.com/2602313/93504491-8de5c180-f8e7-11ea-8bea-0581f74ec54c.png">

## Expected result:

The "Disconnected" state/flow should be removed. When a user selects/clicks on `Disconnect`, it should re-connect the user without displaying the login flow. See `brave://rewards` for correct behaviour.

## Reproduces how often: 

100% reproducible when using the above STR.

## Desktop Brave version:

```
Brave | 1.15.55 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | macOS Version 10.15.6 (Build 19G73)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @LaurenWags @rebron @NejcZdovc

**Comment by btlechowski** [comment]
I am able to reproduce when reconnecting through Rewards panel
I am not able to reproduce when reconnecting through `brave://rewards`


Brave | 1.15.56 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.15.11`

![image](https://user-images.githubusercontent.com/38657976/93853609-c6afdd00-fcd1-11ea-9db2-547fee5028e2.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.16.46 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the STR from the description
- Ensured that "Disconnected" login flow/state is been removed from the rewards panel
