### ISSUE TITLE
[Upstream opportunity] Disable AssistRankerActivity

### ISSUE THREAD

**Issue by Gyuyoung** [brave/brave-browser#11765]
Looks like Brave has been disabling to send any data to Google. As one of them, Brave has been disabling the assist ranker activity through **components-assist_ranker-ranker_url_fetcher.cc.patch**. So, IMHO, it would be good if we can add a command line switch to disable the feature instead of just returning "false".

**Comment by Gyuyoung** [comment]
File a new bug for this opportunity - https://crbug.com/1129771

**Comment by Gyuyoung** [comment]
I abandoned https://crbug.com/1129771 because reviewers were skeptical to add the switch. Instead I remove the patch file via overriding RankerURLFetcher::Request() - https://github.com/brave/brave-core/pull/7070

**Comment by bbondy** [comment]
PR seems to have been landed in 1.18.x so I adjusted this to 1.18.x.
