### ISSUE TITLE
Zoho CRM for Gmail extension not working

### ISSUE THREAD

**Issue by Dylan-86** [brave/brave-browser#11768]
## Description 
The Zoho CRM for GMail plugin does not work. 
Link: https://chrome.google.com/webstore/detail/zoho-crm-for-gmail/ojhlgnehlajjgpneocngnphjellkjgch

Once installed, you are asked to login from Gmail, but nothing happens.
It works perfectly in Chrome.

## Steps to Reproduce

   1. Install the plugin from the store
   2. Open Gmail if it does not open automatically
   3. Click on "Authenticate Google"

As you can see, nothing happens.

## Actual result:

![image](https://user-images.githubusercontent.com/58813956/93625559-73dcd980-f9e2-11ea-9e51-19aaf7fb7243.png)

## Expected result:

It should lead to Step 2 where you authorize Zoho

## Reproduces how often: 

It reproduces 100% of the times.

## Brave version (brave://version info)

Brave | 1.13.82 Chromium: 85.0.4183.83 (Build ufficiale) (a 64 bit)
-- | --
Revisione | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
Sistema operativo | Windows 10 OS Version 1909 (Build 18363.1082)
JavaScript | V8 8.5.210.20
Flash | (Disabilitata)
User-agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Riga di comando | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=PrefetchPrivacyChanges,WebUIDarkMode,MixedContentSiteSetting,PasswordImport,ReducedReferrerGranularity,DnsOverHttps,OmniboxContextMenuShowFullUrls,AutoupgradeMixedContent,PassiveMixedContentWarning,WinrtGeolocationImplementation --disable-features=TextFragmentAnchor,PrivacySettingsRedesign,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,SmsReceiver,TabHoverCards,VideoPlaybackQuality,AutofillServerCommunication,PasswordCheck,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --origin-trial-disabled-features=MeasureMemory
Percorso eseguibile | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Percorso profilo | C:\Users\danie\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Varianti | 5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes

- Can you reproduce this issue with the beta channel?
Not tested 

- Can you reproduce this issue with the dev channel?
Not tested 

- Can you reproduce this issue with the nightly channel?
Not tested 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

No, I Have it disabled by default on Gmail. 
I tried with both enabled and disabled. 

- Does the issue resolve itself when disabling Brave Rewards?
No

- Is the issue reproducible on the latest version of Chrome? 
No, on Chrome it works well!

## Miscellaneous Information:
Nothing else. No Zoho account is needed to reproduce this bug.

**Comment by bsclifton** [comment]
Thanks for the report @Dylan-86 - I think we have a solution

Can you please visit brave://settings/extensions and then enable the option `Allow Google login for extensions`?
![image](https://user-images.githubusercontent.com/4733304/93629970-06a75500-f99e-11ea-8c41-60ef9455a95d.png)

After doing this, you should be good to go! Let us know if this resolves the issue for you

**Comment by Dylan-86** [comment]
> Thanks for the report @Dylan-86 - I think we have a solution
> 
> Can you please visit brave://settings/extensions and then enable the option `Allow Google login for extensions`?
> ![image](https://user-images.githubusercontent.com/4733304/93629970-06a75500-f99e-11ea-8c41-60ef9455a95d.png)
> 
> After doing this, you should be good to go! Let us know if this resolves the issue for you



Yes that worked :) BUT, note: this setting is available only if I set Brave to be displayed in English. I had it in Italian and that setting does not exist in that language! 

Thanks anyway, solved!

**Comment by bsclifton** [comment]
cc: @jumde, RE: the comment about option missing in that language

**Comment by jumde** [comment]
@bsclifton - I think I missed the translation label here: https://github.com/brave/brave-core/pull/6516/files#diff-2fee9af70a1fee49a5195e76b1f45b28R656 - I just added the label - @rebron - can we request translations for the string?

**Comment by crickw** [comment]
@bsclifton I am experiencing a similar, if not the same, problem authorizing the Zoho CRM for the Gmail extension.
 Allow Google login for extensions is enabled.
However, the authentication fails with this message:

> Oops! Failed to authenticate Google. It seems like you chose a mismatched Gmail account for the current [Chrome People account.

<img width="404" alt="Screenshot 2024-01-23 at 2 23 29 PM" src="https://github.com/brave/brave-browser/assets/5818352/9a4a7eda-3de3-47e2-b447-6763129466fd">

Though this message points to a mismatch in the Chrome People account, the account IDs are not mismatched. 

This Zoho CRM for the Gmail extension works fine in Chrome while logged into the same Google Mail account. Logging into the actual Zoho CRM page works as well. 

Console shows the following:

<img width="783" alt="image" src="https://github.com/brave/brave-browser/assets/5818352/1a71af59-bf2f-44c3-9444-7cad68027312">

Any recommendations?
