### ISSUE TITLE
RewardsPublisher type should have normalized atts

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#1176]
Currently, the RewardsPublisher type contains three attributes for naming: `id, name, publisherKey`

In the case of a non-media publisher, this looks like:
`{id: 'brave.com', name: 'brave.com', publisherKey: 'brave.com'}`

In the case of a media publisher, this looks like:
`{id: 'youtube#channel:NFL', name: 'NFL', publisherKey: 'youtube#channel:NFL'}`

Three keys is unecessary, we should just have `name`, which stores the display name for the auto-contribute table, and `publisherKey` which contains the unique identifier for the publisher and can be used to dispatch CRUD actions against the publisher. `id` can be dropped.

**Comment by NejcZdovc** [comment]
this is not relevant anymore
