### ISSUE TITLE
lib/transifex.py should flag HTML tags

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#11767]
@bbondy suggested that https://github.com/brave/brave-core/blob/master/script/lib/transifex.py#L262 throw an error for any HTML tags that aren't `<a>` or `<b>`. for `a` tags, it should:

1. print the href so it can be manually validated
2. if `target=_blank`, it should throw an error if the tag is missing `rel='noopener noreferrer'`

**Comment by mkarolin** [comment]
The (incomplete?) list of tags that I currently see in string files:
`a`
`abbr`
`b`
`br`
`h4`
`li`
`ol`
`p`
`span`
`strong`
`ul`

Plus, some odd strings that are placed in angle brackets, like `<Type search term>` or `<Not Part Of Certificate>`

**Comment by bbondy** [comment]
@diracdeltas do you have a recommendation for how to handle strings like:
> Plus, some odd strings that are placed in angle brackets, like <Type search term> or <Not Part Of Certificate>

**Comment by diracdeltas** [comment]
what is the function of those odd string tags?

the other ones look fairly safe to me since they're mostly for formatting; we could warn on them instead of erroring.

**Comment by mkarolin** [comment]
I think the <> there are just part of the text. Maybe we just add them as exceptions as we encounter them.

`
        <message name="IDS_CERT_INFO_FIELD_NOT_PRESENT" desc="The text displayed in the certificate info dialog for a given field when the certificate does not contain that field">
          &lt;Not Part Of Certificate&gt;
        </message>
`

`
  <message name="IDS_EMPTY_KEYWORD_VALUE" desc="Shown in the location bar drop down when the user enters a string that matches a chrome keyword, but they haven't entered any text following the chrome keyword">
    &lt;Type search term&gt;
  </message>
`

**Comment by diracdeltas** [comment]
@mkarolin i think that's just rendered as text because usually HTML is inside `<ph>` tags.

**Comment by mkarolin** [comment]
As I recall we remove all child tags from `<ph>` tags when we download from Transifex and write out `.xtb` files. A lot of strings in Transifex already have `<ph>` tags without child tags. If we want to catch things inside `<ph>` tags it might be better to do this on upload.

**Comment by bbondy** [comment]
Maybe we can replace the < to some other similar character for the ones we don't recognize?
