### ISSUE TITLE
Ads shown are not being correctly counted/Estimated pending rewards not increasing

### ISSUE THREAD

**Issue by rabie1001** [brave/brave-browser#11775]
after updat to Version 1.14.81 I do not gain BAT from ads anymore. I can see the ads notifications appearing, I am even clicking them, but the overall count of "Ad notifications received this month" does not change (the ads are registered correctly in 7-day ads history) and no BAT has been gained.

![Untitled1](https://user-images.githubusercontent.com/34496411/93687130-5adb3380-fa89-11ea-8072-b481d209040c.jpg)
![Untitled2](https://user-images.githubusercontent.com/34496411/93687132-5c0c6080-fa89-11ea-8580-8fa97543bcc3.jpg)

**Comment by tmancey** [comment]
@rabie1001 Could you please show a screenshot with all ads history for the 19th September

**Comment by rabie1001** [comment]
the ads counter just start counting again and the Estimated pending rewards increasing, everything is back to normal now, sorry for the disturbance and thank you for your hard work

**Comment by tmancey** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/11952

**Comment by GerardoTBO** [comment]
@rabie1001 hi, i have the same problem and don't solve, i've just to wait or how can i fixed?, sorry and thanks for your time

**Comment by tmancey** [comment]
@rabie1001 @GerardoTBO please upgrade to 1.15.75 and if the problem persists please reach out to tmancey@brave.com if you are willing to screen-share
