### ISSUE TITLE
Option to disable Rewards, Wallets, and Widgets

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#11778]
## Description 
Some instances of Brave may be installed in environments where Brave Rewards, Crypto Wallets, NTP Widgets, and other elements of the browser are not appropriate (e.g. Computer Lab in a School, public library, etc.). The ability to control contextually inappropriate elements of these instances with a Group Policy ([as is the case with Tor](https://github.com/brave/brave-core/pull/3692)) would be ideal.

## Miscellaneous Information:
Users have limited control over these features today, via command-line arguments:

- `--disable-brave-rewards-extension` _Disables the Brave Rewards Extension_

**Comment by bridiver** [comment]
replace buildflags with feature flags for rewards (wallet buildflag is tied to extensions so it needs a feature flag and a buildflag

**Comment by marshall** [comment]
Issue to track in Crypto Wallets: #8742. Removing this from our project board

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/22029
