### ISSUE TITLE
[FEATURE REQUEST] Generate random password

### ISSUE THREAD

**Issue by Axilot** [brave/brave-browser#11774]
Hello there,
i find it very useful to add a feature that generates a random password for you when creating an account on a website. For example by right clicking and selecting something like "generate password". This would be very awesome to have. (Firefox has this feature which i'm missing) I would really appreciate it if someone adds this feature to brave. Thanks for reading :-)

**Comment by srirambv** [comment]
Dupe of https://github.com/brave/brave-browser/issues/4901
