### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by LucaTheHacker** [brave/brave-browser#11776]
## Description 

Brave is using too much CPU

## Steps to Reproduce

   1. Open a youtube video

## Actual result:

https://imgur.com/i2ARJ5k

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.14.81 Chromium: 85.0.4183.102 (Build ufficiale) (a 64 bit)

## Version/Channel Information:
- Can you reproduce this issue with the current release? y
- Can you reproduce this issue with the beta channel? y
- Can you reproduce this issue with the nightly channel? y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
Hi @LucaTheHacker 

From a clean restart of the browser:

1. In private window mode (no extensions enabled)
2. Playback a youtube clip
3. What does `More Tools/Task Manager` Show ? (Screenshot will be helpful)

**Comment by LucaTheHacker** [comment]
I did it, same exact problem.
![Screenshot_3](https://user-images.githubusercontent.com/45915503/93705343-b9052680-fb1c-11ea-9ef6-4cbe57adb9a8.png)

**Comment by ryanbr** [comment]
Have removed a suspect filter,

https://github.com/easylist/easylist/commit/a33c50c610e14211b7403e99fd5cc3afa304ae84

give it 24-48hrs

**Comment by ryanbr** [comment]
How is this looking now @LucaTheHacker  the performance okay?

**Comment by LucaTheHacker** [comment]
No
![Screenshot_1](https://user-images.githubusercontent.com/45915503/93845168-27262680-fca0-11ea-9c03-a65b21f7f0de.png)

**Comment by ryanbr** [comment]
Actually the new screenshot isn't as bad as the first.  Adjusting GPU Acceleration in `brave://settings` may help also.

Does private-window mode help (with no extensions), and how does is compare to Chrome?

**Comment by rebron** [comment]
Per the screenshots, looks like there was some improvement here. @LucaTheHacker Still experiencing high cpu usage? can you also update to our latest 1.16.68 and let us know.

**Comment by LucaTheHacker** [comment]
All good now
