### ISSUE TITLE
Fingerprint setting changes are not retained

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11786]
## Description 
Fingerprint setting changes are not retained

## Steps to reproduce 

   1. Install 1.16.28 nightly build or 1.15.54 beta build
   2. Visit any page and opens shields 
   3. Set FP to `Block all fingerprinting` and click done
   4. Wait for the page to reload and check the setting, changes are retained
   5. Change FP to `Block third party fingerprinting` and click done
   6. Wait for the page to reload and check the setting, resets to `Block all fingerprinting`
   7. Change FP to `Allow all fingerprinting` and click done
   8. Wait for the page to reload and checking the setting, retains `Allow all fingerprinting`

## Actual result 
![android-shields](https://user-images.githubusercontent.com/17010094/93766303-1dec7980-fc0e-11ea-886b-a7876184014b.gif)

## Expected result
Should retain the shields settings change

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version: 10
   
## Brave version
1.11.105 onwards

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @SergeyZhukovsky @anthonypkeane @deeppandya we should probably fix this one and get it uplifted.

**Comment by deeppandya** [comment]
This may be because of cosmetic filtering. @srirambv Is this a regression ?

**Comment by srirambv** [comment]
Not really. The issue is happening from 1.11.x where the simple shields went in. So something to do with the that

**Comment by diracdeltas** [comment]
we've also seen a similar report on desktop: #10790

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.15.69 x64 build
- Verified test plan from issue description
-------------
Verification passed on OnePlus 6T with Android 10 running 1.15.69 x64 build
- Verified test plan from issue description
