### ISSUE TITLE
High CPU Usage with Google Meet

### ISSUE THREAD

**Issue by Dylan-86** [brave/brave-browser#11784]
## Description 
Almost 50% of the CPU is taken when using Google Meet. Desktop Brave.
CPU: i7-8550U

## Steps to Reproduce

   1. Join a Google Meet
   2. Check the CPU
 

## Actual result:

![image](https://user-images.githubusercontent.com/58813956/93753373-5b4a0a80-fc00-11ea-9012-4cf3cc24f9c4.png)

## Reproduces how often: 
100% of the times, CPU goes between 30% and 60% for Google Meet

## Brave version (brave://version info)

Brave | 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Windows 10 OS Version 1909 (Build 18363.1082)
JavaScript | V8 8.5.210.20
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --disable-features=SafeBrowsingEnhancedProtection,PasswordCheck,AutofillServerCommunication,VideoPlaybackQuality,PrivacySettingsRedesign,NotificationTriggers,SmsReceiver,TabHoverCards,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,TextFragmentAnchor --enable-audio-service-sandbox --enable-dom-distiller --enable-features=LegacyTLSEnforced,OmniboxContextMenuShowFullUrls,DnsOverHttps,WinrtGeolocationImplementation,PassiveMixedContentWarning,AutoupgradeMixedContent,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,WebUIDarkMode,MixedContentSiteSetting --extension-content-verification=enforce_strict --extensions-install-verification=enforce --lso-url=https://no-thanks.invalid --no-pings --origin-trial-disabled-features=MeasureMemory --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=MixedContentSiteSetting,WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,PassiveMixedContentWarning,WinrtGeolocationImplementation,DnsOverHttps,OmniboxContextMenuShowFullUrls,LegacyTLSEnforced --disable-features=TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,TabHoverCards,SmsReceiver,NotificationTriggers,PrivacySettingsRedesign,PasswordCheck,AutofillServerCommunication,VideoPlaybackQuality,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\danie\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Not tried
- Can you reproduce this issue with the nightly channel? Not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome? N

**Comment by rebron** [comment]
@Dylan-86 Can you update to the latest 1.16.68 and see if you're still running into high cpu usage for Google Meet?

**Comment by Dylan-86** [comment]
@rebron  it seems to be fixed

**Comment by rebron** [comment]
Thanks @Dylan-86 for upgrading and checking. Will close this one out then.
