### ISSUE TITLE
Support different directories for gn_check and lint

### ISSUE THREAD

**Issue by yachtcaptain23** [brave/brave-browser#11799]
This issue will track the effort to add

```
.option('-C <build_dir>', 'build config (out/Debug, out/Release')
```

To different commands including lint and gn_check

**Comment by kjozwiak** [comment]
@yachtcaptain23 assuming this is a `QA/No` as there's nothing for QA to do here. Adding `QA/No` but please remove and add `QA/Yes` with STR/Cases if this needs to be checked 👍 Also moving the issue into the `1.16.x`
