### ISSUE TITLE
Can't login to SoundCloud using login with facebook/google/other

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1179]
Carried over from https://github.com/brave/browser-laptop/issues/15196
> @bsclifton 
> I tried it on dev version. I think there is some problem with `google` option there as well. I also noticed that `facebook` option didn't open the popup with one click.
> 
> [SoundCloud site](https://soundcloud.com)
> ![image](https://user-images.githubusercontent.com/18963158/45589395-9561e100-b942-11e8-9408-b728a09f1903.png)
> 
> upon clicking sigin in
> ![image](https://user-images.githubusercontent.com/18963158/45589406-a7438400-b942-11e8-8ba4-cb1aff60f4f4.png)
> 
> when trying to click google option, it doesn't respond. However, the facebook option opens a popup for me to put in credentials.
> This doesn't happen in other browsers for instance Mozilla.
> 
> edit: I made sure that I allow pop-ups from this website. Still not working

**Comment by frsh-evan** [comment]
if this is not a priority - can we suggest a music streaming service that brave prefers the methods in which authentication via the large tech companies?

**Comment by frsh-evan** [comment]
+1

**Comment by tomlowenthal** [comment]
Does the same thing happen with Shields down?

**Comment by ryanbr** [comment]
While from 2018, still tested signup and signin via google. Looks good. Closing @bsclifton
