### ISSUE TITLE
"TypeError: Cannot read property 'length' of undefined" when verifying wallet that belongs to unsupported region

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11790]
## Description 

When attempting to verify using an Uphold account that's using a region that isn't supported, the `brave://rewards` page will appear blank during the process and will display the following error in the browser console:

When attempting to verify using an Uphold account that's using a region that isn't supported, the `brave://rewards` page will appear blank during the process and will display the following error in the browser console:

```
TypeError: Cannot read property 'length' of undefined brave_rewards_page.bundle.js:29 
    at brave_rewards_page.bundle.js:3597
    at rm.renderPromos (brave_rewards_page.bundle.js:3597)
    at rm.render (brave_rewards_page.bundle.js:3597)
    at Eo (brave_rewards_page.bundle.js:29)
    at xo (brave_rewards_page.bundle.js:29)
    at To (brave_rewards_page.bundle.js:29)
    at Wa (brave_rewards_page.bundle.js:29)
    at qa (brave_rewards_page.bundle.js:29)
    at El (brave_rewards_page.bundle.js:29)
    at vl (brave_rewards_page.bundle.js:29)
ra @ brave_rewards_page.bundle.js:29
```

```
Uncaught TypeError: Cannot read property 'length' of undefined brave_rewards_page.bundle.js:29 
    at brave_rewards_page.bundle.js:3597
    at rm.renderPromos (brave_rewards_page.bundle.js:3597)
    at rm.render (brave_rewards_page.bundle.js:3597)
    at Eo (brave_rewards_page.bundle.js:29)
    at xo (brave_rewards_page.bundle.js:29)
    at To (brave_rewards_page.bundle.js:29)
    at Wa (brave_rewards_page.bundle.js:29)
    at qa (brave_rewards_page.bundle.js:29)
    at El (brave_rewards_page.bundle.js:29)
    at vl (brave_rewards_page.bundle.js:29)
```
<img width="1215" alt="Screen Shot 2020-09-21 at 3 00 29 PM" src="https://user-images.githubusercontent.com/2602313/93809411-3d3dd380-fc1b-11ea-9c69-fe7b4dc2aeff.png">

## Steps to Reproduce

   1. create an account that's in an unsupported region on the staging server (used NYC in this case)
   2. launch Brave on staging and accept/claim the UGP grant (~30 BAT)

```
kjozwiak@Kamils-MacBook-Pro ~ % /Applications/Brave\ Browser\ Dev.app/Contents/MacOS/Brave\ Browser\ Dev --args --enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6 --rewards=staging=true --brave-ads-staging
```

   3. once claimed, click on `Verify Wallet` and run through the process using the Uphold account that's using an unsupported region

Please ping me if you need the above account to reproduce the above issue.

## Actual result:

<img width="1705" alt="Screen Shot 2020-09-21 at 2 32 03 PM" src="https://user-images.githubusercontent.com/2602313/93806524-3dd46b00-fc17-11ea-82fb-5fe9aa466e70.png">

## Expected result:

<img width="1215" alt="Screen Shot 2020-09-21 at 2 36 37 PM" src="https://user-images.githubusercontent.com/2602313/93806904-e1be1680-fc17-11ea-9c66-f8a091792856.png">

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.16.28 Chromium: 86.0.4240.30 (Official Build) nightly (x86_64)
-- | --
Revision | 09f50eb5535879364cf00e72653462a509ef6bdc-refs/branch-heads/4240@{#552}
OS | macOS Version 10.15.6 (Build 19G73)
```

```
Brave | 1.15.56 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | macOS Version 10.15.6 (Build 19G73)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? **`Not reproducible`**
- Can you reproduce this issue with the beta channel? *`Reproducible`**
- Can you reproduce this issue with the nightly channel? *`Reproducible`**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @NejcZdovc @LaurenWags

**Comment by LaurenWags** [comment]
@NejcZdovc could this be related to https://github.com/brave/brave-browser/issues/11286 / https://github.com/brave/brave-core/pull/6511 since this doesn't reproduce in 1.14.x but does reproduce in 1.15.x / 1.16.x?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.15.65 Chromium: 86.0.4240.55 (Official Build) dev (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the STR from the description, created uphold account for an unsupported region New York and ensured that `BAT is currently not supported in your region...` message is displayed upon verifying an wallet via brave://rewards page

![image](https://user-images.githubusercontent.com/38657976/94551038-588b8d00-0272-11eb-9e72-2de92c214134.png)

- Crated uphold account for the supported region India/Karnataka and ensured that abe to login the uphold account successfully.
- Ensured there are no error logs `TypeError: Cannot read property 'length' of undefined brave_rewards_page` in console
