### ISSUE TITLE
CapitalOne.com doesn't load because of adblock

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1180]
Carried over from https://github.com/brave/browser-laptop/issues/15148
> 1. With shields enabled, visit https://www.capitalone.com
> 2. Notice totally blank screen
> 3. Use shields menu and pick `Allow ads and tracking` under `Ad Control`
> 4. Site works

**Comment by bsclifton** [comment]
Note: this behavior is similar to https://github.com/brave/brave-browser/issues/1016 and https://github.com/brave/brave-browser/issues/1023

**Comment by rebron** [comment]
Doesn't look like this is an issue anymore on Dell.com with shields up with current builds, tried with 58.x/59.x/60.x.
