### ISSUE TITLE
Re-enabling BAT logo position problem 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11801]
## Description 

BAT logo is cut if you toggle hide rewards button. It's fixed it you switch tabs for example.

## Steps to Reproduce

   1.  Enable rewards
   2. Disable rewards
   3. Go to brave://settings/appearance
   4. Click on hide rewards button (make sure it hides)
   5. Click on hide rewards button again

## Actual result:

Button appears again, but it's partially cut out
![image](https://user-images.githubusercontent.com/9574457/93863268-99f4c900-fcc3-11ea-81b2-131cdb89dd81.png)

## Expected result:
![image](https://user-images.githubusercontent.com/9574457/93863277-9e20e680-fcc3-11ea-8113-ab385244cd0e.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.16.46 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the STR from the description
- Ensured that enable and disable `Hide Brave Rewards button` doesn't change the BAT logo position
