### ISSUE TITLE
Filter out Vero's email tracker from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#11817]
The [Vero](https://www.getvero.com/) messaging platform uses a [`vero_id` query string parameter](https://help.getvero.com/articles/what-is-vero_id/) to annotate third-party URLs with "the unique ID of the user who has clicked the link."

The purpose for this is described in their documentation:

> Adding this parameter enables Vero’s Javascript library to automatically identify a user when they land on your site, even if they are not already identified. This enables cross-device tracking and ensures a more complete and accurate customer profile.

They do offer the option of removing that parameter from URLs and explain its effect:

> When disabling appending vero_id to your campaigns, Vero’s Javascript library will no longer automatically identify users when they click through from an email.

Therefore stripping out this parameter should have no webcompat implications.

**Comment by fmarier** [comment]
Here are some examples which can be found via Google:

- `https://www.deckofscarlet.com/log-in/register?utm_campaign=111918_blackfridaylaunch_nonsub&utm_medium=calendar&utm_source=news_email&vero_conv=kGnF6SYO5V3PbgXsIwwUNNSlWBCantgnVkvEntSFodpp9KFpEtU1XkYCSUxltJuvF-vHne1MoYngHSVmfEhhgv-9xgptCmn3&vero_id=85422`
- `https://monosnap.com/welcome?utm_term=Newsletter&utm_campaign=[cold%20%2B%20warm]%20-%20newsletter%20-%20120916&utm_medium=email&vero_conv=O9KWzIj7BNysHI2T7J1L_g81x55Zg-Plp2IFXHaQqgjN-LUS3EqpJA96okHkrmAx61aSrdscSPiraCHu_w1Fot9ygp2tCco8&vero_id=3492441&utm_source=vero&utm_content=control&__hstc=20629287.99a265337744294b740e0787aea508c4.1570320001226.1570320001227.1570320001228.1&__hssc=20629287.1.1570320001229&__hsfp=3733277192`
- `https://www.mailerlite.com/?utm_campaign=[cold+%2B+warm]+-+newsletter+-+120916&utm_medium=email&utm_term=Newsletter&__hstc=20629287.99a265337744294b740e0787aea508c4.1570320001238.1570320001239.1570320001240.1&__hssc=20629287.1.1570320001241&_ga=2.108145861.670349201.1555516136-933118289.1529345498&yt_video=PNrnO31OD5M&region=united-states&vero_conv=O9KWzIj7BNysHI2T7J1L_g81x55Zg-Plp2IFXHaQqgjN-LUS3EqpJA96okHkrmAx61aSrdscSPiraCHu_w1Fot9ygp2tCco8&vero_id=3492441&__hsfp=3733277192&utm_source=vero&utm_content=control`
- `https://www.brightcove.com/en/online-video-platform?utm_term=Newsletter&utm_campaign=[cold+%2B+warm+-+last+60]+-+newsletter+-+012916&utm_medium=email&vero_conv=O9KWzIj7BNysHI2T7JxO-eOelX_hAg8Ws1OR04J-KL7HZHjLFyTAm1bK7mPlbInhSiw-sAGUPpUqi9VQ24MXgELWp20pTUo%3D&vero_id=3368475&utm_content=control&utm_source=vero&__hstc=259582869.99a265337744294b740e0787aea508c4.1576108800148.1576108800149.1576108800150.1&__hssc=259582869.1.1576108800151&__hsfp=3969827736&_ga=2.250809862.1607566148.1585586557-1753121421.1568128919&hubs_signup-url=blog.hubspot.com/website/css-margin-vs-padding&hubs_signup-cta=blog-card__blog-link`
- `https://galaxystore.samsung.com/detail/com.vsco.cam.samsung?utm_term=Newsletter&utm_campaign=[cold+%2B+warm]+-+newsletter+-+120916&utm_medium=email&_ga=2.108145861.670349201.1555516136-933118289.1529345498&yt_video=pZl62ZJSNbc&region=united-states&vero_conv=O9KWzIj7BNysHI2T7J1L_g81x55Zg-Plp2IFXHaQqgjN-LUS3EqpJA96okHkrmAx61aSrdscSPiraCHu_w1Fot9ygp2tCco8&vero_id=3492441&utm_source=vero&utm_content=control&session_id=W_64a278a33667d5de901961be3c464b76`

It's pretty odd that the last 4 have the same value for `vero_id` and `vero_conv`. I couldn't find any indication of what might be contained in `vero_conv` (it doesn't return anything readable after base64-decoding it), but based on the name, I would guess it has to do with [conversion tracking](https://help.getvero.com/articles/conversion-tracking/).

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.15.63 Chromium: 86.0.4240.55 (Official Build) dev (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Ubuntu 18.04 LTS

The issues is still reproducible, it seems that the filtering does not work in general. Logged https://github.com/brave/brave-browser/issues/11924. Based on our process I mark this issue as verified.

![image](https://user-images.githubusercontent.com/34715963/94645299-c922c000-02eb-11eb-97ff-f56dda56a612.png)

**Comment by LaurenWags** [comment]
Marking as `release-notes/exclude` as issue still reproduces, please adjust if necessary cc @rebron

**Comment by fmarier** [comment]
> Marking as `release-notes/exclude` as issue still reproduces, please adjust if necessary cc @rebron

As I mentioned in https://github.com/brave/brave-browser/issues/11578#issuecomment-702948144, this is partially working and the remaining issue is tracked elsewhere.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.16.69 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/6684
---------------
Verification passed on OnePlus 6 with Android 10 running 1.16.69 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/6684
