### ISSUE TITLE
salesforce.com doesn't load because of adblock

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1182]
Carried over from https://github.com/brave/browser-laptop/issues/14807
> 1. With shields enabled, visit https://www.salesforce.com/campaign/mvp/
> 2. Notice totally blank screen
> 3. Use shields menu and pick `Allow ads and tracking` under `Ad Control`
> 4. Site works

**Comment by rebron** [comment]
Doesn't look like this is an issue anymore with url provided (salesforce.com...) with shields up with current builds, tried with 58.x/59.x/60.x.

**Comment by rebron** [comment]
Doesn't look like this is an issue anymore on Searss.com with shields up with current builds, tried with 58.x/59.x/60.x.
