### ISSUE TITLE
create new Sync section in settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1183]
## Description 
Create new Extensions section in Settings beneath Extensions and before Shield Settings section
Label section - 'Sync'
Label in sidebar - 'Sync'
Add item to: 'Manage, add or remove synced devices'
This will launch into the Brave Sync UI.

Display Device Name of device being synced and Last Activity.
See design.

## Design
![sync-screenshot](https://user-images.githubusercontent.com/5951041/45717344-83ed2480-bb4e-11e8-9165-b018b4134e71.png)

**Comment by bsclifton** [comment]
Should be similar to https://github.com/brave/brave-core/pull/436

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Some follow up issues: 
https://github.com/brave/brave-browser/issues/2592 
https://github.com/brave/brave-browser/issues/2593 
https://github.com/brave/brave-browser/issues/2594

**Comment by srirambv** [comment]
Thanks for logging the followup issues @btlechowski :+1:
