### ISSUE TITLE
Greaselion content script sometimes doesn't load until restarting browser

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#11837]
Create a `Greaselion.json` file like the following and a simple script that just prints `Hello, world!` to the console:

```
  {
    "urls": [
      "https://twitter.com/*",
      "https://*.twitter.com/*"
    ],
    "scripts": [
      "myscript.js"
    ]
  }
```

If you launch the browser clean (with no open pages) and then navigate to https://twitter.com/emerick, once in a while the content script will not load at all. This occurs maybe 1 in 10 or 1 in 20 times. In addition, no amount of refreshing the page or creating new tabs will cause the content script to load; the only recourse I've found is to restart the browser. I don't see any relevant error messages in the log or console when this occurs, unfortunately.

**Comment by emerick** [comment]
Actually, I can make this happen every time by adding some additional entries to `Greaselion.json`.

**Comment by LaurenWags** [comment]
Per internal discussions, this issue should be tested when Twitter tipping with Greaselion lands (projected to be 1.17.x). As such, I have logged a follow up issue (https://github.com/brave/brave-browser/issues/11998) for that milestone and will be marking this one as `QA/No`. Please adjust if needed.
