### ISSUE TITLE
WebGL not being blocked in workers

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#11839]
Noted in https://github.com/brave/brave-browser/issues/11368#issuecomment-694561609

**Comment by btlechowski** [comment]
@pilgrim-brave Could you include test plan for this issue?

**Comment by pes10k** [comment]
Hi @btlechowski, the test plan is to just make sure that all the values on the "WebGL Drawing" row on https://dev-pages.bravesoftware.com/farbling.html and https://dev-pages.brave.software/farbling.html match.

I believe @pilgrim-brave is working out some edge cases still but once he gives the 👍 , thats the test plan. Hope that helps!

**Comment by LaurenWags** [comment]
@pes10k looks like this isn't working as per https://github.com/brave/brave-browser/issues/11839#issuecomment-701522569 (note, sites were viewed with default shields/FP=Standard)

Do you want to check the sites to confirm they're set up correctly before I log a follow up issue?


Brave | 1.16.52 Chromium: 86.0.4240.68 (Official Build) dev (x86_64)
-- | --
Revision | ad72ee9aa8e15ed300df1238e76c7a8f4d686f97-refs/branch-heads/4240@{#1097}
OS | macOS Version 10.14.6 (Build 18G3020)

<img width="1201" alt="Screen Shot 2020-10-05 at 11 31 41 AM" src="https://user-images.githubusercontent.com/28145373/95099916-84899100-06fe-11eb-85a1-b1dbf56f1343.png">

labeling as `QA/Blocked` until the above is sorted

**Comment by pes10k** [comment]
Thanks @LaurenWags, the current tests are correct, so I think @pilgrim-brave will be needed to figure out the way forward here

**Comment by LaurenWags** [comment]
holding on logging a follow up until @pes10k is able to review https://github.com/brave/brave-browser/issues/11368#issuecomment-705069803

**Comment by LaurenWags** [comment]
Still seeing some issues with this - logged follow up issue https://github.com/brave/brave-browser/issues/12098

Going to mark this one as `QA/No` and `release-notes/exclude` since testing will be done with the above issue. Please let me know if there are any objections @rebron @pes10k .
