### ISSUE TITLE
Can't play videos in LinkedIn with shields up

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1184]
Carried over from https://github.com/brave/browser-laptop/issues/14663
> ### Steps to Reproduce
> 1. Login to LinkedIn
> 2. Click on play videos

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/embedded-videos-on-linkedin-feed-dont-work/34554

**Comment by mrzealot** [comment]
Works fine for me in 0.58.21 (it is also tagged as a legacy Muon issue), so I think this can be closed.

**Comment by bbondy** [comment]
Can't reproduce either. Closing.
