### ISSUE TITLE
[Desktop] rewards panel doesn't show creator specific information for Vimeo

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11840]
## Description 

Rewards panel does not show creator specific information for vimeo publishers. Subsequently, you are unable to tip specific Vimeo publishers as well.

This doesn't work on older versions where it used to (ex. 1.12.x as per https://github.com/brave/brave-browser/issues/9502#issuecomment-666704554) so it is likely there was a change on Vimeo's side.

## Steps to Reproduce

   1. Clean profile
   2. Enable Rewards, wait for publisher list indexes to be downloaded
   3. Visit a vimeo page (ex. vimeo.com/bravelaurenwags on staging)

## Actual result:

Vimeo publisher info is not shown in panel. Note, viewing the video from this page still seems to add the publisher to the AC list.
<img width="1195" alt="Screen Shot 2020-09-24 at 11 41 11 AM" src="https://user-images.githubusercontent.com/28145373/94167782-e7576e80-fe5a-11ea-94ad-795f86682e4b.png">

In the above, it should say "Lauren on Vimeo" (or similar)
Additionally, choosing one of the tip buttons does not bring up the publisher's banner, but shows the generic banner for a non-verified publisher.

## Expected result:
Vimeo publisher info should be shown in the panel.

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @brave/legacy_qa

**Comment by emerick** [comment]
Fixed by https://github.com/brave/brave-core/pull/6955

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.18.62 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6042)
```

Confirmed panel showed expected creator information for user and video URLs on Vimeo.

Testing was completed as part of https://github.com/brave/brave-browser/issues/11465 and testing notes can be found under https://github.com/brave/brave-browser/issues/11465#issuecomment-733749523

-------------
