### ISSUE TITLE
[Suggestion] Adding an option doing : "Select complete URL and Copy it to clipboard" (...similar as to "Copy and Go")

### ISSUE THREAD

**Issue by GUITERII** [brave/brave-browser#11856]
This requested feqture does not yet exist but would be a great help to copy past URL.

## Steps to Reproduce

   1. Bring Mouse cursor focus to any Brave website URL field displayed
   2. Right clic with mouse to display the list of options
  3.  Choose the new option :  "Select the full URL and copy it to the Clipboard"    (...just in 1 clic)
  4.  Latter, one can paste the saved Clipboard URL to any target you want to, such as a Sheet...or Chat Client input, etc..

## Expected result:
      Save on the repetitiv task for one to correctly select - from the first to the last caracter - any displayed URL from the Brave Browser...and past it latter properly to whereever one may need it to...

**Comment by dentistformyeye** [comment]
In the meantime, if the URL box is active (i.e. you can type in it) you can press Ctrl-A and right-click. Otherwise, you can simply right-click the URL box.

**Comment by rebron** [comment]
@GUITERII We have this already with "Copy link address" in the right click menu. 
Can you clarify what your suggested feature is? 

If there's some advanced saving of urls and copy and pasting elsewhere, might be better served via an extension.
