### ISSUE TITLE
userguides.tritondigital.com doesn't load properly because of adblock

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1185]
Carried over from https://github.com/brave/browser-laptop/issues/14689
> 1. With shields enabled, visit https://userguides.tritondigital.com/adv/a2xspecdsp/
> 2. Notice totally blank screen
> 3. Use shields menu and pick `Allow ads and tracking` under `Ad Control`
> 4. Site works

**Comment by ryanbr** [comment]
Issued is resolved
