### ISSUE TITLE
Implement user activity frequency capping

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#11858]
Implement user activity frequency capping as a pre-requisite for ad delivery timing

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.15.69 x64 build
- Verified ads is enabled when rewards is enabled
- Verified number of ads shows as per settings
- Verified ads is shown only when the browser is in use
- Verified view/click/landed/dismiss is logged correctly  
-----------------------------
Verification passed on Samsung Tab A with Android 10 running 1.15.69 x64 build
- Verified ads is enabled when rewards is enabled
- Verified number of ads shows as per settings
- Verified ads is shown only when the browser is in use
- Verified view/click/landed/dismiss is logged correctly
