### ISSUE TITLE
Improve dApp detection so that it's not triggered on web.archive.org (waybackmachine)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11865]
## Description 

window.ethereum prompts sometimes show up when they shouldn't.  This seems to happen on way back machine.

Likely the website in question is iterating through window and accessing every property on it. But it's strange because https://github.com/brave/brave-core/blob/master/components/brave_extension/extension/brave_extension/content_dapps.ts#L42 defines the object property as not enumerable (enumerable defaults to false)

We need to see what the site is doing exactly and then see what we can do to fix it.

## Steps to Reproduce

   1. Fresh profile
   2. Navigate to https://web.archive.org/web/20191202043852/https://brave.com/

## Actual result:

Setup Crypto Wallets infobar is shown

## Expected result:

No infobar should be shown

## Reproduces how often: 

Always on that link

**Comment by BrendanEich** [comment]
The enumerable attribute controls property visibility to for-in loops and similar base-level meta-object protocol (MOP) operations, but not to ES5 Object.getOwnPropertyDescriptors and similar MOP functions.

Best if web.archive.org didn't get the properties found via Object.getOwnPropertyDescriptor, especially ones where the property descriptor in the resulting array is an accessor (has get and possibly set methods). Accessors can have side effects. Glad this was fixed.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.17.61 Chromium: 86.0.4240.185 (Official Build) beta (x86_64)
-- | --
Revision | `37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified no dApp detection on `https://web.archive.org/web/20191202043852/https://brave.com/`

-------

Verification passed on 


Brave | 1.17.61 Chromium: 86.0.4240.185 (Official Build) beta (64-bit)
-- | --
Revision | `37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}`
OS | Linux

- Verified no dApp detection on `https://web.archive.org/web/20191202043852/https://brave.com/`

-------

Verification passed on 


Brave | 1.17.61 Chromium: 86.0.4240.185 (Official Build) beta (64-bit)
-- | --
Revision | `37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}`
OS | Windows 10 OS Version 1809 (Build 17763.1518)

- Verified no dApp detection on `https://web.archive.org/web/20191202043852/https://brave.com/`

**Comment by jonathansampson** [comment]
It looks like this issue may still exist on some domains. We had a user [reach out over Twitter](https://twitter.com/CMiksche/status/1430204970360578053) regarding Google Translate triggering this prompt. I was able to reproduce the issue fairly easily (sometimes one or two refreshes of the page were needed).

1. Navigate to https://translate.google.de/?sl=en&tl=en&text=%E2%88%AB
2. Note prompt to enable Crypto Wallets

It seems as though you have to navigate directly to a _results_ view, where the _string to be translated_ is present in the URL itself. It also doesn't appear to matter what the string is; in this case `∫` was provided by the user, but I was able to reproduce this with something like https://translate.google.de/?sl=auto&tl=en&text=morgen&op=translate too.

This doesn't appear to reproduce for all instances of Google Translate. For example, I could not reproduce the issue at https://translate.google.com/?sl=auto&tl=en&text=.&op=translate, but upon changing .com to .de, I was able to reproduce the issue.

@bbondy, can you also reproduce? (I did so in Nightly, v1.30.44).

**Comment by bbondy** [comment]
@jonathansampson pls post a new issue for that. I can reproduce  above.
Note that at the end of September we'll be deprecating this, but it may still be worth fixing it before that. 
https://github.com/brave/brave-browser/issues/17762
