### ISSUE TITLE
Add a Learn more link to the Setup Ethereum provider infobar

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11864]
## Description 

Add a learn more link on the infobar for the Ethereum provider pointing to a community page that describes information about what is going on and how to disable the infobar in settings.

## Steps to Reproduce

   1. Trigger the infobar on a Dapp like Crypto Kitties

## Actual result:
No learn more link

## Expected result:
Working learn more link

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.17.41 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.15.7 (Build 19H2)
```

* Verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/11864#issue-709369662
* ensured that clicking on `Learn more` opens https://support.brave.com/hc/en-us/articles/360034535452

<img width="1228" alt="Screen Shot 2020-10-19 at 11 53 24 PM" src="https://user-images.githubusercontent.com/2602313/96538464-94f54c00-1266-11eb-9474-9450416bd518.png">
