### ISSUE TITLE
Incorrect rendering of some sites

### ISSUE THREAD

**Issue by khalidchawtany** [brave/brave-browser#11869]
## Description 
On some sites the browser shows scrambles.

## Steps to Reproduce

   1. Just visit https://brave.com/latest/ for example and you will see it

## Version
`Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)`

![Kapture 2020-09-26 at 11 05 45](https://user-images.githubusercontent.com/1681606/94336016-6ded8680-ffe8-11ea-8c5b-d97addbed79b.gif)

**Comment by Dev-i-l** [comment]
Its working for me as of now 
![Uploading Screenshot (554).png…]()
![Uploading Screenshot (555).png…]()

**Comment by khalidchawtany** [comment]
![Screen Shot 2020-09-26 at 12 42 24 PM](https://user-images.githubusercontent.com/1681606/94337782-cd9e5e80-fff5-11ea-9098-3191c73f4ad8.png)


Resizing the window fixes parts of it in some sites.



![Screen Shot 2020-09-26 at 12 43 35 PM](https://user-images.githubusercontent.com/1681606/94337804-eb6bc380-fff5-11ea-9c06-19dfc5ea27e6.png)

**Comment by khalidchawtany** [comment]
It fixed itself. I don't know what happened.
