### ISSUE TITLE
Reddit comments and sidebar fail to load with Trackers & Ads blocking enabled

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#11879]
## Description
Having Tracker & Ads blocking enabled (both standard and aggressive modes) will break Reddit in numerous ways:
**When not logged in**, clicking into a post will pop-up a message saying `Something went wrong`.
**When logged in**, comments and sidebar fail to load and a `Something went wrong` message appears.

## Steps to Reproduce

   1. Make sure that Trackers & Ad blocking is enabled for `reddit.com`.
   2. Clear cookies for Reddit.
   3. Go to `reddit.com` and click into a post.
   4. Notice the `Something went wrong` message that pops up on the bottom of the screen.
   5. Login with your Reddit account.
   6. Notice that your subscribed subreddits fail to load in the Reddit sidebar
   7. Go to the comments section of any post with 1 or more comments.
   8. Notice that the comments do not load.

## Actual result:

**When not logged in:**
![image](https://user-images.githubusercontent.com/241316/94375301-9c8e5e80-00c7-11eb-9943-9ae7b94298f4.png)

**When logged in:**
![image](https://user-images.githubusercontent.com/241316/94375286-7bc60900-00c7-11eb-9460-0cdf827f47fe.png)

## Expected result:
**When not logged in**, `Something went wrong` should **not** appear.
**When logged in**, subscribed subreddits and post comments should load. `Something went wrong` should **not** appear.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave: 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
Revision: a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
OS: Windows 10 OS Version 2004 (Build 19041.508)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, because it does not block trackers and ads.

**Comment by urbenlegend** [comment]
Here's the Reddit thread where a bunch of people are also experiencing this issue: https://www.reddit.com/r/brave_browser/comments/j0tgl6/cant_load_reddit_comments_with_brave_shields_up/

**Comment by llacb47** [comment]
https://github.com/easylist/easylist/commit/a3c843b5a80c3a43e04761ba0f3eab9c3d08768a

**Comment by snowbound** [comment]
Same issue here on Brave Version 1.15.61 Chromium: 86.0.4240.42 (Official Build) beta (64-bit)

**Comment by ryanbr** [comment]
Fix will be automatically available in Brave in the next 24-48hrs. Temp option disable Ads and tracking.

@urbenlegend @snowbound

**Comment by urbenlegend** [comment]
I can confirm that the issue is now fixed. Reddit loads fine now.
