### ISSUE TITLE
Component Updates don't happen over proxy/VPN installed in browser

### ISSUE THREAD

**Issue by TontyTon** [brave/brave-browser#11876]
## Description 

Component Updates don't happen over proxy/VPN installed in browser. I installed a VPN extension and blocked all connections other than the VPN's using firewall. Now Components don't update.\
I see in connections logging app that browser try to connect directly to servers to update the components, rather than updating through the proxy/VPN installed.

## Steps to Reproduce

   1. Install any proxy/vpn **extension** from chrome webstore.
   2. Block all non proxy connections for brave.exe using firewall
   3. Go to brave://components/
   4. Click on 'Check for update' for any component.

## Actual result:

Status - Update Error

## Expected result:
Component should update if there is an update or show component up to date as status.

## Reproduces how often: 

Everytime

## Brave version (brave://version info)

Brave | 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
-- | --
Revision | a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
OS | Windows 10 OS Version 2004 (Build 19041.450)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

PS- Is there a way to disable automatic component updates?

**Comment by rebron** [comment]
cc: @jumde Can you assist with triaging this one?

**Comment by jumde** [comment]
@TontyTon - 

I'm not able to reproduce this on the release version: `1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)`. 

1. Which VPN extension are you using? 
2. Are there any specific components that you're not able to update? 
3. Could you also explain this step: `Block all non proxy connections for brave.exe using firewall` - Are you blocking connections from all binaries except brave.exe?

**Comment by TontyTon** [comment]
@jumde 
1. Any VPN Extension
2. All components
3. I only allow connections to proxy/VPN.

What I suggest is that component updates connections should be made through VPN/Proxy used (extension), instead of bypassing VPN.

**Comment by jumde** [comment]
Hi @TontyTon - I tried the steps to reproduce with OneTouchVPN extension on Windows with `1.18.70 Chromium: 87.0.4280.101`, but all components update without an error. If you could share the VPN extension that you're using that'll be helpful.

**Comment by TontyTon** [comment]
@jumde Have you blocked all connections other than required by Onetouch VPN for 'brave.exe'??

I don't think so.
As when you try to update components from brave://components/ browser try to connect to amazonaws servers, directly, request is not routed through VPN connection.
I tested on v1.18.70 Windows with OneTouchVPN extension still the component update request are sent directly, not routed through VPN.

To be clear I am NOT saying that component updates don't happen when using VPN, but I am saying that their request are not routed through the VPN.
So, if I block all connections(except required by VPN) for brave.exe using some firewall software, component updates will not happen.

**Comment by TontyTon** [comment]
Not fixed in v1.19.92

**Comment by bsclifton** [comment]
Closing as stale. Two different problems captured; seems the original issue (not updating) is not a problem but the most recent complaint is that component updates are not happening through VPN (happening with regular device?). If this happens in other browsers too (Chrome, Edge, etc) then that would be helpful to know

Windows does use Smart Multi-Homed Resolution to resolve DNS which means it can use other adapters (not the VPN) to resolve DNS. That could be what happened here... that "feature" can be turned off which may solve your complaint @TontyTon 
https://www.ghacks.net/2017/08/14/turn-off-smart-multi-homed-name-resolution-in-windows/
