### ISSUE TITLE
SpeedReader breakage on specific WSJ article

### ISSUE THREAD

**Issue by yokoffing** [brave/brave-browser#11877]
## Steps to Reproduce

   1. https://www.wsj.com/articles/weekly-jobless-claims-coronavirus-09-24-2020-11600889767
   2. Activate SpeedReader on Brave Dev.

![flags](https://user-images.githubusercontent.com/11689349/94368843-70b5ad80-00b4-11eb-8187-d2c61a5ac61a.png)

## Actual result:

![Screenshot 2020-09-27 111944](https://user-images.githubusercontent.com/11689349/94368758-f84eec80-00b3-11eb-9f0c-e936d8055651.png)

## Reproduces how often: 

Other WSJ articles load fine with speed reader. It seems that Speedreader isn't playing nice with charts / infographics.

Here's another article with a chart that breaks: https://www.wsj.com/articles/ipo-market-parties-like-its-1999-11601052419.

![breakage](https://user-images.githubusercontent.com/11689349/94368945-f9344e00-00b4-11eb-9d8e-75558b6671eb.png)

## Brave version (brave://version info)

Version 1.15.64 Chromium: 86.0.4240.55 (Official Build) dev (64-bit)

**Comment by rebron** [comment]
Will close with https://github.com/brave/brave-core/pull/8855

**Comment by iefremov** [comment]
can't reproduce anymore
