### ISSUE TITLE
[Desktop] Get to see background image when de-activate a button in the settings

### ISSUE THREAD

**Issue by rocketmagnet83** [brave/brave-browser#11887]
When i de-activate a button in the settings i see the background for a few seconds.

I'm on debian stable on my linux dual monitor and the brave stable version still has a few bugs related to multimonitor env.

**Comment by rebron** [comment]
Closing. Are you still having this issue with 1.17.75 and can you file using our issue template and post screenshots. It's difficult to address your issue with the detail you provided.
