### ISSUE TITLE
[Desktop] sometimes the publisher name isn't shown on the panel only "on Youtube" is shown

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11888]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/9133

Intermittently the publisher info is left off the panel and all you see is "on YouTube". I haven't been able to reproduce this but I do have a profile where this occurs.

## Steps to Reproduce

   1. Launch using provided profile (see me) - I launched with `/Applications/Brave\ Browser\ Nightly.app/Contents/MacOS/Brave\ Browser\ Nightly --args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --rewards=staging=true`
   2. Navigate to a verified publisher (youtube.com/user/JJDSampson) 
   3. Once page loads, you will see the verified checkmark on the BAT logo
   4. Open panel

note - reproduces with non-verified publisher as well, ex. youtube.com/user/gordonramsay

## Actual result:

Publisher name is missing from panel
<img width="1196" alt="Screen Shot 2020-09-28 at 11 24 10 AM" src="https://user-images.githubusercontent.com/28145373/94453402-9e672900-017e-11eb-955a-e0ccd71075b3.png">

## Expected result:
Publisher name should be displayed
<img width="1197" alt="Sampson generic YT favicon 1 16 x" src="https://user-images.githubusercontent.com/28145373/94453460-b179f900-017e-11eb-9b98-375d9e363d04.png">

## Reproduces how often: 

intermittent, haven't been able to reproduce without this profile (note, profile is relatively clean)

## Brave version (brave://version info)

```
Brave	1.16.42 Chromium: 86.0.4240.55 (Official Build) nightly (x86_64)
Revision	a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS	macOS Version 10.14.6 (Build 18G3020)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @emerick @brave/legacy_qa

**Comment by emerick** [comment]
For some reason, both problematic entries in the `publisher_info` table have a blank publisher name. Once that incorrect data is in the table we'll continue showing it whenever that publisher is requested. It's hard to say how we originally got a blank publisher name, but it's conceivable that we received some type of unexpected response from YouTube when we fetched the channel page.

To guard against that scenario, we should never send the publisher info when we have an invalid channel id, media id, or publisher name. Instead, we'll just show a generic panel with no publisher info. The next time the user shows the panel, we'll attempt the request again, only storing and displaying the publisher info on success.
