### ISSUE TITLE
Update Twitter Greaselion script to use locales directory for localizations

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#11890]
When https://github.com/brave/brave-core/pull/6683 is merged, update our Twitter Greaselion script to use the `locales_` directory for localizations. Currently, the text for our UI is hardcoded directly into the Twitter script.

**Comment by emerick** [comment]
This needs to be a Greaselion issue.

**Comment by LaurenWags** [comment]
@emerick since this one is marked `QA/Yes` could we get a test plan for this? if manual QA is not needed, let's label as `QA/No` 👍  labeling `QA/Blocked` for now until we sort this out.

**Comment by emerick** [comment]
@LaurenWags I updated the test plan in the PR, give me a holler if anything doesn't make sense with it.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.45 Chromium: 86.0.4240.99 (Official Build) dev (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6683. Note - each OS may have a slightly different method to getting Brave to display in a different language (as noted in the steps). Here are the steps I followed - modified from the PR after discussion with @emerick:

- Clean profile
- Launch browser
- Enable Rewards and restart browser
- Visit twitter.com/emerick 
- Verify that inline tips appear with US localizations

<img width="640" alt="English" src="https://user-images.githubusercontent.com/28145373/96896449-81f79d00-145b-11eb-8af1-d50bbba6e7aa.png">

- Locate the Greaselion `_locales` directory for Twitter (on macOS:  `⁨Library⁩ ▸ ⁨Application Support⁩ ▸ ⁨BraveSoftware⁩ ▸ ⁨Brave-Browser-Dev⁩ ▸ ⁨afalakplffnnnlkncjhbmahjfjhmlkal⁩ ▸ ⁨1.0.32⁩ ▸ ⁨1⁩ ▸ ⁨scripts⁩ ▸ ⁨brave_rewards⁩ ▸ ⁨publisher⁩ ▸ ⁨twitter⁩ ▸ ⁨_locales⁩`)
- Copy the `en_US` directory and rename `de`
- Edit the `message` fields in `de/messages.json` to distinguish them from US localizations.

<img width="371" alt="Screen Shot 2020-10-22 at 11 43 18 AM" src="https://user-images.githubusercontent.com/28145373/96896675-cbe08300-145b-11eb-9e75-29ab48345b5b.png">

- Open browser Settings
- Search for `Language`
- Click "Add Languages"
- Select "German - Deutsch" and click "Add"
- Click three dots on "German" and select "Move to top"
- Open OS settings, change OS language to German
- Relaunch Brave
- Visit twitter.com/emerick again
- Verify that inline tips appear with German localizations

<img width="631" alt="German" src="https://user-images.githubusercontent.com/28145373/96896751-e31f7080-145b-11eb-9afc-b4dbeca8dbc4.png">
