### ISSUE TITLE
Verify wallet text message is missing in BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11907]
## Description 

Verify wallet text message is missing in BR panel

## Steps to Reproduce

   1. Clean profile 1.16.43 staging env
   2. Enable rewards
   3. Click on BR panel and select `Verify Wallet`
   4. `You need to have minimum 25 BAT to create an Uphold account...` message is missing in BR panel

## Actual result:

You need to have minimum 25 BAT to create an Uphold account...` message is missing in BR panel
![image](https://user-images.githubusercontent.com/38657976/94549736-49a3db00-0270-11eb-9b16-e27895d3378a.png)

## Expected result:

![image](https://user-images.githubusercontent.com/38657976/94549895-85d73b80-0270-11eb-98aa-9f38f49831db.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.16.43 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.16.52 Chromium: 86.0.4240.68 (Official Build) dev (x86_64)
-- | --
Revision | ad72ee9aa8e15ed300df1238e76c7a8f4d686f97-refs/branch-heads/4240@{#1097}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified STR from description.
Verified test plan from https://github.com/brave/brave-core/pull/6739.
Confirmed opening the panel and clicking on `Verify Wallet` or `Add Funds` shows:
<img width="1194" alt="Screen Shot 2020-10-05 at 9 04 29 AM" src="https://user-images.githubusercontent.com/28145373/95083130-12a74c80-06ea-11eb-96a4-f220f596d1be.png">

Confirmed on brave://rewards page clicking on `Verify Wallet`, `Add Funds`, `WIthdraw Funds`, or `verify` link (footer) shows:
<img width="1197" alt="Screen Shot 2020-10-05 at 9 07 42 AM" src="https://user-images.githubusercontent.com/28145373/95083250-408c9100-06ea-11eb-8c51-0ffc8c36c1fa.png">

-------------
