### ISSUE TITLE
brave crashing when tapping on rewards icon when onboarding skipped

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11903]
## Description 

Brave will crash every single time when attempting to create a wallet once onboarding has been skipped.

## Steps to reproduce 

   1.  launch https://github.com/brave/brave-browser/releases/tag/v1.16.43
   2. once installed, click on the `Rewards` icon and skip onboarding
   3. once you've skipped onboarding, tap on the `Rewards` button again and you'll get an instant crash

## Actual result 

Brave currently crashing when attempting to create a new wallet once onboarding has been skipped.

## Expected result

Brave shouldn't be crashing when users attempt to create a new wallet.

## Issue reproduces how often 

100% reproducible when using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No, not reproducible`
- Can you reproduce this issue with the current Play Store Beta version? `No, not reproducible`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes, reproducible`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 10`
   
## Brave version

* Using `1.16.43 CR: 86.0.4240.55`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @NejcZdovc @srirambv @anthonypkeane @SergeyZhukovsky

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.66 x64 beta build
- Verified  no crash when following steps from issue description
------------
Verification passed on Samsung Tab A with Android 10 running 1.17.66 x64 beta build
- Verified  no crash when following steps from issue description
