### ISSUE TITLE
Page crashes while trying to upload photos on a facebook group

### ISSUE THREAD

**Issue by GUITERII** [brave/brave-browser#11914]
## Description 
Page crashes while trying to upload photos

## Steps to Reproduce
opening facebook classified public group-->

   1. adding new item text for sale
   2. trying to add one photo from the Modify option - popup window
   3. While adding a first photo uploaded from PC, popup window will crash

## Actual result:
see captures :
https://ibb.co/qRB7hM5
https://ibb.co/jWDnpMy

## Expected result:
normal upload and dispay in the fb image uploader...

## Reproduces how often: 
everytime, its not possible to load image using brave in that fb sales page: https://www.facebook.com/groups/locationgestion

## Brave version (brave://version info)
Version 1.14.84 Chromium: 85.0.4183.121 (Build officiel) (64 bits) - running on recent Linux Zorin 15

## Version/Channel Information:
not tested with others

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No it does not, same crash
- Does the issue resolve itself when disabling Brave Rewards? not tested
- using Firefox, image could be uploaded on the same website same Topic.

## Miscellaneous Information:
Firefox was used as a workaround for uploading/publishing photos

**Comment by kjozwiak** [comment]
@GUITERII mind checking `brave://crashes` and see if there's anything listed? It should look similar to the following:

<img width="469" alt="Screen Shot 2020-09-29 at 2 47 45 PM" src="https://user-images.githubusercontent.com/2602313/94602385-c760ea00-0262-11eb-8b59-8b7a075c9153.png">

You might need to submit the reports by clicking on `Send now` if you have `Automatically sends crash reports to Brave` disabled via `brave://settings`. Once you've submitted the reports and restarted Brave, mind sharing the `Crash Report ID:`? We'll be able to take a look and investigate on why the webview is crashing.

**Comment by GUITERII** [comment]
i had typed words "crash facebook upload pictures.." previously but nothing
had come up..
will run search again

Le mar. 29 sept. 2020 à 08:55, Kamil Jozwiak <notifications@github.com> a
écrit :

**Comment by kjozwiak** [comment]
> i had typed words "crash facebook upload pictures.." previously but nothing
> had come up..
> will run search again

You just need to go into `brave://crashes` via the URL which should have a list of recent crashes. Each crash has an associated `Crash Report ID`. If you go into `brave://crashes`  and see a list of crashes, can you share the `Crash Report ID` for the first ~5 crashes being listed?

**Comment by GUITERII** [comment]
Oh, I see what you meant : did run : brave://crashes but nothing is in here : Error().
beside, Brave did not crash itself, had other pages opened and fine with them.
Its the Popup window, where one can modify text of an exising item that closes...while brave is still working.
modif are not being registered in fb...
Same procedure does not pose problem in firefox

**Comment by GUITERII** [comment]
submiting again and will check right away what the crash pages says...

**Comment by GUITERII** [comment]
Confirmed ! Crash page returns Zero Error() after trying to a 110kb photo.

**Comment by GUITERII** [comment]
no error crash page capture :https://ibb.co/SJvPyyz

**Comment by GUITERII** [comment]
303/5000
Sending of error reports is disabled.
Crash reports are not available in Brave.

Errors (0)
  Display information for developers
No errors have been reported recently. Errors only appear here when error reporting is enabled.

**Comment by GUITERII** [comment]
activated auto report now, and retrying...tks

**Comment by GUITERII** [comment]
hmm... now activating the Auto error report...pictures uploaded succesfully.
So its the auto repport deactivation that does indeed creates the Crash !
is Brave spying on our photo uploads ?
:(

**Comment by kjozwiak** [comment]
> hmm... now activating the Auto error report...pictures uploaded succesfully.
> So its the auto repport deactivation that does indeed creates the Crash !
> is Brave spying on our photo uploads ?
> :(

Brave is definitely not spying in your uploads. Uploading images via FB and Brave's crash reporter are not related and have nothing to do with each other.

Just double checking, when you enable `Automatically sends crash reports to Brave`, the crash goes away and when you re-enable you can reproduce it again?

**Comment by themew** [comment]
I  can confirm that turning ON `Automatically sends crash reports to Brave` does in fact stop the 'aw snap' issue.  My friend who is a Brave convert (my suggestion) can finally post pictures to the Facebook group again.  Weird issue.
