### ISSUE TITLE
`Verify wallet` dropdown options are missing for unsupported region 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11915]
## Description 

`Verify wallet` dropdown options are missing for unsupported region 

## Steps to Reproduce

   1. Clean profile 1.14.x or 1.15.x or 1.16.x
   2. Enable rewards and claim UGP grants of 30 BAT
   3. Login to uphold using unsupported region credentials mentioned in https://bravesoftware.slack.com/archives/C0YL5KMA8/p1600465855004300?thread_ts=1600457317.001000&cid=C0YL5KMA8
   4. After getting the expected error message, click on `Verify wallet`
   5. `Verify wallet` dropdown options are missing for unsupported region 

## Actual result:

**settings page:**
![image](https://user-images.githubusercontent.com/38657976/94602409-711b9780-02b2-11eb-8c9b-b8ed7e351249.png)

**BR panel:**
![image](https://user-images.githubusercontent.com/38657976/94602444-7d9ff000-02b2-11eb-852a-21bf0d16406a.png)

## Expected result:
Dropdown options should be displayed as per the issue https://github.com/brave/brave-browser/issues/10023, Although I am not sure what is the expected behavior for unsupported regions

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.16.43 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron 

@NejcZdovc This issue was already found by @LaurenWags and she has already mentioned in the issue https://github.com/brave/brave-browser/issues/11908 - Please close the issue which I logged if the fix is going to be added in #11908

**Comment by btlechowski** [comment]
Reproduced on Ubuntu


Brave | 1.15.69 Chromium: 86.0.4240.55 (Official Build) (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Linux

**Comment by Miyayes** [comment]
I think this has been resolved and superseded by Uphold wallet state changes by Szilard, and the new Rewards panel from Kevin.
