### ISSUE TITLE
[Desktop] Implement new panel design

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11929]
design can be found here  https://www.figma.com/file/Zsc9KCXEg93XMOoFEHuBV3/Rewards-Everywhere--stopgap?node-id=0%3A1

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.18.62 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
Revision	0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS	macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/6890
Confirmed designs from https://www.figma.com/file/EDGI52tfWG1ggC9ZYFguXy/tipping-banner-2.0?node-id=489%3A9872 per PR description.

Confirmed able to set monthly tip by selecting "Set" from the panel

<details>
<summary>Screenshots</summary>
<img width="1196" alt="initial panel" src="https://user-images.githubusercontent.com/28145373/100278353-b8c94300-2f32-11eb-8947-96c0a48199e8.png">
<img width="1196" alt="set monthly tip" src="https://user-images.githubusercontent.com/28145373/100278357-ba930680-2f32-11eb-8da7-76a6f458695f.png">
<img width="1195" alt="monthly tip confirmation" src="https://user-images.githubusercontent.com/28145373/100278362-bbc43380-2f32-11eb-84f8-628869d40110.png">

</details>

Confirmed panel reflects the monthly tip amount I set

<details>
<summary>Screenshots</summary>
<img width="1188" alt="panel 1" src="https://user-images.githubusercontent.com/28145373/100278373-c1217e00-2f32-11eb-8907-cf97d40ab682.png">
<img width="419" alt="panel expanded" src="https://user-images.githubusercontent.com/28145373/100278386-c2eb4180-2f32-11eb-9470-a93f861ae9c0.png">

</details>

Select Change Amount from drop down and change the tip amount

<details>
<summary>Screenshots</summary>
<img width="1194" alt="select Change Amount" src="https://user-images.githubusercontent.com/28145373/100278403-c7175f00-2f32-11eb-98bf-277133603e42.png">

</details>

Confirm monthly tip amount is changed on panel and brave://rewards

<details>
<summary>Screenshots</summary>
<img width="401" alt="change shows on panel" src="https://user-images.githubusercontent.com/28145373/100278439-da2a2f00-2f32-11eb-8257-3004477d8c67.png">
<img width="650" alt="change shows on rewards page" src="https://user-images.githubusercontent.com/28145373/100278442-db5b5c00-2f32-11eb-9961-42c31dbe6801.png">

</details>

Select Cancel from drop down on panel

<details>
<summary>Screenshots</summary>
<img width="419" alt="panel expanded" src="https://user-images.githubusercontent.com/28145373/100278450-deeee300-2f32-11eb-9af6-d93373cef9d2.png">
<img width="1194" alt="select cancel" src="https://user-images.githubusercontent.com/28145373/100278454-e0201000-2f32-11eb-801c-804e163fc30b.png">

</details>

Cancel monthly tip

<details>
<summary>Screenshots</summary>
<img width="1197" alt="cancel on banner" src="https://user-images.githubusercontent.com/28145373/100278466-e57d5a80-2f32-11eb-9171-d829e1c85e3f.png">
<img width="651" alt="removed from rewards page" src="https://user-images.githubusercontent.com/28145373/100278472-e6ae8780-2f32-11eb-9dcd-1e5c77f2d8cc.png">
<img width="414" alt="panel returns to before" src="https://user-images.githubusercontent.com/28145373/100278474-e7dfb480-2f32-11eb-8a1d-d16c7f9ce10c.png">

</details>
