### ISSUE TITLE
Show explicit log message when ads are capped due to user activity

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#11923]
In https://github.com/brave/brave-core/pull/6703 user activity frequency capping was implemented.
However a generic log message is shown when ad is capped. It is hard for QA to debug what happens.

## Steps to Reproduce

   1. Clean profile on staging
   1. Enable rewards
   1. Wait till ads are initialized
   1. Trigger an ad

## Actual result:

A generic ad message is shown in the logs
`[ads_impl.cc(876)] Ad notification not shown: Not allowed based on history`

## Expected result:
An explicit message, for example:
`Ad notification not shown due to user activity frequency capping`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.16.46 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @tmancey

**Comment by tmancey** [comment]
Closing issue as wont fix. Discussed in DM.
