### ISSUE TITLE
Direct navigations are wrongly exempted from the query string filter

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#11924]
This is a regression introduced in 1.16.x. Not reproducible on 1.15.x, 1.14.x

## Steps to Reproduce

   1. Clean profile
   2. Open `https://brave.com/?dclid=1`

Another link with regressed parameters:
https://brave.com/?vero_id=1234&vero_conv=abc

Regressed parameters:
"fbclid", "gclid", "msclkid", "mc_eid",
"dclid",
"yclid",
"_hsenc", "__hssc", "__hstc", "__hsfp", "hsCtaTracking"

## Actual result:

`dclid=1` parameter is not filtered out
![image](https://user-images.githubusercontent.com/34715963/94644222-ff127500-02e8-11eb-8e98-2af3a622a0d8.png)

## Expected result:
`dclid=1` parameter is filtered out

![image](https://user-images.githubusercontent.com/34715963/94644522-d76fdc80-02e9-11eb-899b-40d58b81141a.png)

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

**Reproducible on** 

Brave | 1.16.46 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Linux

**Not reproducible on** 

Brave | 1.15.63 Chromium: 86.0.4240.55 (Official Build) dev (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Ubuntu 18.04 LTS

Brave | 1.14.84 Chromium: 85.0.4183.121 (Oficjalna wersja) (64-bitowa)
-- | --
Wersja | a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @fmarier @rebron @bsclifton

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.16.46`

**Comment by fmarier** [comment]
Thanks @GeetaSarvadnya and @btlechowski for catching this oversight in the tests I added. This is in fact a logic error which we will need to fix on Beta too.

**Comment by fmarier** [comment]
As mentioned in https://github.com/brave/brave-browser/issues/11930#issuecomment-703663031, in addition to copy/pasting the URL in the URL bar, choosing "Open the link in a private window" also lead to the query string not getting filtered.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.16.58 Chromium: 86.0.4240.75 (Official Build) dev (x86_64)
Revision	c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6741

Verified STR from description including all listed parameters.

------------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.16.69 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/6741
-------------
Verification passed on Samsung Tab A with Android 10 running 1.16.69 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/6741
