### ISSUE TITLE
restore wallet functionality does not support older 16 word wallets

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1193]
## Description 
Brave Payments on browser-laptop allows for wallets to be recovered with either the old 16 words or the newer 24 words. Brave Rewards only allows for the newer 24. Since the switch to 24 was done without user interaction/knowledge, it's possible some users do not know and only have the 16 words in their backup file. Once they move to brave-core, if they try to recover their wallet using these words it will not work for them.

## Steps to Reproduce

   1. Have backup words for a wallet with 16 words.
   2. Attempt to recover a wallet on Brave Rewards with 16 words. (currently you may encounter https://github.com/brave/brave-browser/issues/1171)

## Actual result:
Wallet recovery with 16 words fails

## Expected result:
Wallet would be recovered with 16 words. However, as it is in browser-laptop, after recovering the wallet with 16 words, when user goes to backup wallet, the 24 words should be displayed. This does create a disconnect for the user as their backup phrase is now different than what they entered, however we probably do want to promote the newer 24 words.

## Reproduces how often: 
easily

## Brave version (chrome://version info)
all Brave Rewards enabled versions

### Reproducible on current release:
no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
https://github.com/brave/browser-laptop/issues/14856#issuecomment-409111525
https://github.com/brave/browser-laptop/issues/13313#issuecomment-385819713
https://github.com/brave-intl/bat-client/pull/48

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

* Verified 16 word wallet is restored correctly with BAT in it
* Verified 24 word wallet is restored correctly with BAT in it
* Verified wrong words doesn't restore wallet and throws error

One observation, error doesn't go away when user tries to re-enter the recover code.

**Comment by shayanb** [comment]
Is this option removed from Brave 1.0.0 ? It seems that only 24 words recovery phrase is acceptable.

**Comment by LaurenWags** [comment]
@shayanb I was just able to import a 16 word Rewards wallet file as well as copy/paste the recovery words without issue using 1.0.0. Are you trying to do this on brave://rewards or brave://wallet? Are you seeing an error message? 


Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by shayanb** [comment]
Thanks @LaurenWags . I was using the restore wallet `brave://wallet` functionality, it worked with `brave://rewards`, although seems that the wallet is empty :-?

**Comment by LaurenWags** [comment]
@shayanb thanks for the confirmation. brave://wallet is for the crypto wallet, which is separate and not related to Brave Rewards at all. 

As for your wallet being empty when restoring, it's possible that it had grants which have since expired. We have not had grants in awhile I believe and we stopped doing 16 word wallets in favor of the 24 word wallets even longer ago, so this is my suspicion. Is this a wallet from a long time ago?

**Comment by shayanb** [comment]
Yes, probably early on when BAT was implemented in Brave. Anyhow thanks for the help. It's all good now :)
