### ISSUE TITLE
Cross-site tests are not working as expected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11930]
## Description 

Follow up of https://github.com/brave/brave-browser/issues/9020
Cross-site tests are not working as expected

## Steps to Reproduce

   1. Open https://fmarier.github.io/brave-testing/query-filter.html 
   2. Perform cross-site tests in the Private window tab (close all private windows in between each test case)
   3. In each case the `fbclid` parameter is present on the landing page.

## Actual result:

In each case the `fbclid` parameter is present on the landing page.
![image](https://user-images.githubusercontent.com/38657976/94667518-8c2aed80-032c-11eb-900b-30d30e0d12be.png)

## Expected result:
In all of these cases, the fbclid parameter should be missing from the landing page.

## Reproduces how often: 

Always
## Desktop Brave version:

Brave | 1.16.46 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa  @fmarier  @rebron

**Comment by btlechowski** [comment]
Likely dupe of https://github.com/brave/brave-browser/issues/11924

**Comment by fmarier** [comment]
I've just tested this on the following versions:
- Version 1.17.3 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
- Version 1.16.46 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
- Version 1.15.67 Chromium: 86.0.4240.55 (Official Build) beta (64-bit)
and the cross-site tests work fine for me in all cases.

Is this Windows-specific? Anything else I should do to reproduce?

**Comment by LaurenWags** [comment]
@fmarier reproduces for me using these steps:

**Comment by LaurenWags** [comment]
@fmarier reproduces for me using these steps:

1. Clean profile with 1.16.x
2. Open https://fmarier.github.io/brave-testing/query-filter.html in normal window
3. Choose a link from `Cross-site tests` section and right click on it
4. Choose "Open link in private window"
5. Private window opens with link
6. Look at URL bar --> tracking parameter is included 

If I do the following, then the tracking parameter is not included:

1. Clean profile with 1.16.x
2. Open https://fmarier.github.io/brave-testing/query-filter.html in private window
3. Choose a link from `Cross-site tests` section and click on it
4. Look at URL bar --> tracking parameter is included 

cc @GeetaSarvadnya to provide additional info

**Comment by GeetaSarvadnya** [comment]
![cross site testing](https://user-images.githubusercontent.com/38657976/95097927-ab21e900-074b-11eb-9908-74a136aa1e1d.gif)
cc: @fmarier

**Comment by LaurenWags** [comment]
@GeetaSarvadnya  does it reproduce if you click on the link instead of copy/paste the link address?

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Good catch, If I directly click on the link it works fine, issues arise only when copying the link and paste it in a new private tab

**Comment by LaurenWags** [comment]
thanks for checking @GeetaSarvadnya 

@fmarier hopefully the above comments help, please let us know if we can provide additional information.

**Comment by fmarier** [comment]
> Good catch, If I directly click on the link it works fine, issues arise only when copying the link and paste it in a new private tab

Thanks @LaurenWags and @GeetaSarvadnya. I just realized how the instructions on my test page were misleading. I've clarified that the test page itself should be opened in a private window.

This is indeed a duplicate of https://github.com/brave/brave-browser/issues/11924.

**Comment by LaurenWags** [comment]
awesome, thanks @fmarier 👍
