### ISSUE TITLE
[Desktop] some brave:// pages are missing the navigation bar - C86 regression

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11937]
## Description 

Certain pages like brave://rewards and brave://wallet have the navigation bar at the top of the page (along with settings, history, bookmarks, downloads) in 1.14.x/C85. 

This nav bar is missing with 1.15.x/C86 on brave specific pages (rewards and wallet). Other pages (settings, history, downloads, bookmarks) still have it. 

## Steps to Reproduce

   1. Using C86 version of 1.15.x open brave://settings, see nav bar at top
   2. Click on Rewards or Wallet from nav bar

## Actual result:

<img width="1197" alt="Screen Shot 2020-09-30 at 12 09 49 PM" src="https://user-images.githubusercontent.com/28145373/94711592-4bc07500-0316-11eb-8da4-1f9eeb197f64.png">

## Expected result:
<img width="1202" alt="Screen Shot 2020-09-30 at 12 09 12 PM" src="https://user-images.githubusercontent.com/28145373/94711601-4e22cf00-0316-11eb-92a6-a84c11047fa3.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.15.68 Chromium: 86.0.4240.55 (Official Build) dev (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a 1.14.x, yes 1.15.x
- Can you reproduce this issue with the beta channel? yes 1.16.x (1.16.47)
- Can you reproduce this issue with the nightly channel? yes, 1.17.x (1.17.3)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @mkarolin @bsclifton @rebron @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 1.16.46 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/94712137-56483200-0349-11eb-8153-b70eae4284f6.png)

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.15.65 Chromium: 86.0.4240.55`

![image](https://user-images.githubusercontent.com/38657976/94717521-15164900-036e-11eb-8aa3-5f75c6db6954.png)
![image](https://user-images.githubusercontent.com/38657976/94717535-1c3d5700-036e-11eb-932c-4e5251d7035f.png)
