### ISSUE TITLE
[Android] UI changes to address Userlytics feedback in mobile onboarding v2

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#11939]
## Description

A round of Userlytics tests for our new mobile onboarding yielded valuable feedback and surfaced UX issues. Implement minor UI changes to fix the issues.

### Search engine selection screen
Some people still conflate “search engine” with “browser”. Add more explanation on the search engine selection screen of why we’re letting them pick a default search engine.

![image](https://user-images.githubusercontent.com/2388823/95268757-ca248780-07ec-11eb-8aaa-8345cb0a7acf.png)

Smaller devices may require the SE list to scroll:

![image](https://user-images.githubusercontent.com/2388823/95268768-cf81d200-07ec-11eb-8ee3-56959f6f5388.png)

### Link Brave Shields to Privacy Reports
People could not find their way back to the “Privacy Reports” screen - nearly everyone tried to open Brave Shields when told to return to Privacy Reports. The connection is there in their head but the UI does not support the connection. Also, once finding their way to the new tab page again, they did not notice the 3-bars Privacy Reports icon in the top right corner. We should make the link between Brave Shields and Privacy Reports much clearer.

Add a link from Brave Shields directly to the detailed Privacy Reports screen.

![image](https://user-images.githubusercontent.com/2388823/94720995-0c8c2700-030a-11eb-8394-2bd168973ec8.png)

Remove 3-bars Privacy Reports icon and highlight the new stats widget during onboarding.

![image](https://user-images.githubusercontent.com/2388823/94751185-b5ec1080-033c-11eb-80a0-79beafe4dacc.png)

### Brave Shields text
A few people mentioned “...’Ads and creepy things blocked’” made them feel wary of the website. Also, this wording is a little out-of-line with our block-trackers-first stance. We should update this to “Trackers, ads, and more blocked”

![image](https://user-images.githubusercontent.com/2388823/94721327-96d48b00-030a-11eb-86b0-31c6d2b1f392.png)

### Bookmarking icon
Someone thought tapping Bookmark icon again would unbookmark the page; instead it took them to edit the bookmark. Let’s fulfill user’s expectations and un-bookmark the page when tapping on the Bookmark icon again.

## Assets
Figma: https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/?node-id=1253%3A0

**Comment by deeppandya** [comment]
@karenkliu Do we have the description for most common SEs?  The list we show on search engine onboarding, it depends on the region as well.

**Comment by karenkliu** [comment]
@deeppandya We don't - can I get a full list of SEs so we can come up with a short description for each?

**Comment by deeppandya** [comment]
@karenkliu android currently support google, DDG, DDG lite, Qwant, Bing, StartPage, Yahoo for SE onboarding. and i have a concern regarding how the UI would look in smaller screen as individual items would ttake more space.

**Comment by karenkliu** [comment]
@deeppandya For smaller screens we'll need to scroll the SE list. I'll mock it up

**Comment by karenkliu** [comment]
@deeppandya I added the search engine description text and small screen treatment.

**Comment by anthonypkeane** [comment]
> @karenkliu android currently support google, DDG, DDG lite, Qwant, Bing, StartPage, Yahoo for SE onboarding. and i have a concern regarding how the UI would look in smaller screen as individual items would ttake more space.

DDG lite was removed BTW

**Comment by kjozwiak** [comment]
Moving issue into https://github.com/brave/brave-browser/milestone/161 as https://github.com/brave/brave-core/pull/7513 landed in `master`.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.20.100 x64 build
- Verified UI changes are as per spec
- Verified Shields has a shortcut to view privacy report 
- Verified clicking on it opens up the privacy report page
- Verified disabling privacy report setting removes the entry from shields


SE Onboarding | Privacy stats info | Trackers & Ads blocked | Data Saved | Time Saved
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107214253-8c857480-6a01-11eb-941f-1c0d3357f495.png) | ![image](https://user-images.githubusercontent.com/17010094/107214306-a45cf880-6a01-11eb-8184-fce64f517cb1.png) | ![image](https://user-images.githubusercontent.com/17010094/107214321-a9ba4300-6a01-11eb-8e51-9cf93842fb40.png) | ![image](https://user-images.githubusercontent.com/17010094/107214406-c6567b00-6a01-11eb-8cc0-c2d5e5c5b289.png) | ![image](https://user-images.githubusercontent.com/17010094/107214418-c9516b80-6a01-11eb-897c-abf8a5222cda.png)

Trackers & Ads blocked(Re-tour) | Data Saved (Re-Tour) | Time Saved (Re-Tour) | View Privacy report(Shields) | No view privacy report (Shields)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107214468-dd956880-6a01-11eb-949b-711ff10064d8.png) | ![image](https://user-images.githubusercontent.com/17010094/107214492-e4bc7680-6a01-11eb-81dd-d924ec666a27.png) | ![image](https://user-images.githubusercontent.com/17010094/107214542-f0a83880-6a01-11eb-9df9-559d6b17e003.png) | ![image](https://user-images.githubusercontent.com/17010094/107214571-faca3700-6a01-11eb-87b4-296980b7c6e4.png) | ![image](https://user-images.githubusercontent.com/17010094/107214586-0158ae80-6a02-11eb-9409-cc539556bd9d.png)

---------------------
Verification passed on OnePlus 6T with Android 10 running 1.20.100 x64 build
- Verified UI changes are as per spec
- Verified Shields has a shortcut to view privacy report 
- Verified clicking on it opens up the privacy report page
- Verified disabling privacy report setting removes the entry from shields


SE Onboarding | Privacy stats info | Trackers & Ads blocked | Data Saved | Time Saved
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107215487-45987e80-6a03-11eb-9e38-5498111f8d32.png) | ![image](https://user-images.githubusercontent.com/17010094/107215541-5b0da880-6a03-11eb-9fbf-423bc24c7df8.png) | ![image](https://user-images.githubusercontent.com/17010094/107215583-6e207880-6a03-11eb-9eec-9cf3f497ead1.png) | ![image](https://user-images.githubusercontent.com/17010094/107215597-71b3ff80-6a03-11eb-9fa2-3806d73cf6a1.png) | ![image](https://user-images.githubusercontent.com/17010094/107215607-74165980-6a03-11eb-97e8-ef0a2f693866.png)

Trackers & Ads blocked(Re-tour) | Data Saved (Re-Tour) | Time Saved (Re-Tour) | View Privacy report(Shields) | No view privacy report (Shields)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107215684-8beddd80-6a03-11eb-9f7a-f45a9ab255c1.png) | ![image](https://user-images.githubusercontent.com/17010094/107215696-914b2800-6a03-11eb-809a-457243ada8b7.png) | ![image](https://user-images.githubusercontent.com/17010094/107215705-93ad8200-6a03-11eb-8ee5-ee7fc4c3b1e1.png) | ![image](https://user-images.githubusercontent.com/17010094/107215725-9a3bf980-6a03-11eb-9a63-c5b1ba0974fa.png) | ![image](https://user-images.githubusercontent.com/17010094/107215812-bcce1280-6a03-11eb-934e-e1dae9662287.png)
