### ISSUE TITLE
Update Brave Together widget new call URL

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#11949]
## Description 

We will no longer generate a 256bit random room name through widget and instead all calls will be started through a new url. The widget on NTP should be updated to reflect the new change.

## Steps to Reproduce

   1. Click "Start video call" from Brave Together widget on Nightly.

## Actual result:

URL redirects to https://together.brave.com/{roomId}

## Expected result:
Should redirect users to https://together.brave.com/widget vs old format https://together.brave.com/{roomId}

**Comment by kjozwiak** [comment]
@jamesmudgett seeing the following behaviour

* Click on `Start video call` via the NTP widget
* Opens new tab with https://together.brave.com/widget
* Redirects to https://together.brave.com/[roomId] after a few seconds

Example:

`https://together.brave.com/widget` --> `https://together.brave.com/v9fieWll3WmiQ7U1ERGTeJEiD28I7TyV_Xldvz_jZP4`

Assuming it's expected? Clicking on the widget doesn't automatically create unique room id but does after a redirect once the new tab has been opened.

**Comment by jamesmudgett** [comment]
Yes this was changed in https://github.com/brave/brave-browser/issues/11949

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.17.42 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.15.7 (Build 19H2)
```

* Verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/11949#issue-712941296 through https://github.com/brave/brave-browser/issues/11949#issuecomment-712578016.
