### ISSUE TITLE
Youtube video fullscreen fatal bug

### ISSUE THREAD

**Issue by Ranarrr** [brave/brave-browser#11940]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.17.3  Chromium: 86.0.4240.55
Operating System: Windows NT 10.0.19041

URL (if applicable) where crash occurred: 

Can you reproduce this crash?
Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go to any youtube video
2. Spam F for fullscreen/not fullscreen
3. Profit(?)
**seriously**, this crashed my PC, not just Brave.
Have confirmed, it does not crash (my pc nor Chrome) in Chrome.
It's usually when leaving fullscreen that it crashes, but I can't confirm it's always like that.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/4c1e1b00-25a8-2105-0000-000000000000

**Comment by ryanbr** [comment]
Hey, @Ranarrr 

Just looking into the report. Testing in the latest Nightly build `Version 1.17.13 Chromium: 86.0.4240.68`  (with or without hardware acceleration). Is this still an issue, as I wasn't able to reproduce the full screen crash.

1. Does disabling hardware acceleration help?
2. Does updating to the latest Brave nightly help?
3. Which GPU are you using?

**Comment by psyphernetik** [comment]
Hello @Ranarrr 

I also was unable to reproduce the full screen crash. I am using the regular release of the brave browser. Same suggestion as above maybe an OS upgrade or brave browser upgrade.

**Comment by Ranarrr** [comment]
Have not been able to reproduce this, my Brave version is now Version 1.17.16 Chromium: 86.0.4240.72 (Official Build) nightly (64-bit)

I had been stress-testing my GPU previously that day, I'm not sure if this will happen again, but I'll be sure to notify if it does, for now I'll run without hardware acceleration.

This had happened before this initial report, however it did not create a crash report (probably because my system crashed..). Hopefully it will next time (if there is a next time).
