### ISSUE TITLE
Minor cleanup needed for brave_wallet code

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11948]
- clang-format all code
- gn format all BUILD files
- Use pref_names instead of brave_wallet_pref_names

**Comment by srirambv** [comment]
@bbondy I guess this should be QA/No since its a dev-concern. Please add QA/Yes if it needs to be tested

**Comment by bbondy** [comment]
Yep looks like accidentally added both, QA/No for sure, thanks.
