### ISSUE TITLE
Google Funding warning sites not being block

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#11945]
## Description 
Visiting `https://www.geekzone.co.nz/` will show a yellow google funding bar:
(and other sites)

   1. Changes to ubo to remove site specific snippets  `+js(nostif, f.parentNode.removeChild(f), 100)`
   2. uBO made 2 changes: `#@#.div-gpt-ad` and `*##.div-gpt-ad:style(width:1px!important;height:1px!important;)`
   3. The  first filter prevent detection, the 2nd filter will hide blank elements

## Expected result:
Expect no google funding yellow bar

## Screenshot:
![googlefund](https://user-images.githubusercontent.com/1659004/94786235-312cef80-042d-11eb-89f5-cfb91c44d1b0.png)

## Brave version (brave://version info)
`Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

As a temp fix:
`##div[style*=" box-shadow: rgb(136, 136, 136) 0px 0px 12px; color: "]`

**Comment by ryanbr** [comment]
@antonok-edm

**Comment by rebron** [comment]
@ryanbr Is this fixed? Or a new issue with: 
![Screen Shot 2020-12-08 at 9 34 43 AM](https://user-images.githubusercontent.com/5951041/101519934-9ffc5c80-3938-11eb-8cc4-502c12ee3970.png)

**Comment by ryanbr** [comment]
@rebron  should be fixed. Just needs shields to be set to Aggressive I see

**Comment by ryanbr** [comment]
Further fixes came from this commit: https://github.com/brave/adblock-lists/pull/531
