### ISSUE TITLE
update Private Window icon

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1195]
## Description 
New icon to indicate Private Window mode in toolbar.

## Current Icon
![screen shot 2018-09-19 at 9 55 48 am](https://user-images.githubusercontent.com/5951041/45768647-55288a00-bbf2-11e8-882f-a75217cf9386.png)

**Comment by srirambv** [comment]
Dupe of https://github.com/brave/brave-browser/issues/738.  

#738 covers the text and icon replacement for private/incognito
