### ISSUE TITLE
YouTube Ads in Video Grid

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#11955]
### Description 

Ads are often displayed in the first video slot on the _Home_ page of youtube.com.

![image](https://user-images.githubusercontent.com/815158/94857536-3f601900-03f7-11eb-804c-d65d2aeebe9e.png)

While Brave's _aggressive_ mode is able to hide these, it leaves an empty container where the video element would have existed.

![image](https://user-images.githubusercontent.com/815158/94857870-cad9aa00-03f7-11eb-9f67-d97a2faee472.png)

## Steps to Reproduce

1. Go to youtube.com (logged-in)
2 Select _Home_ from the left

## Actual result:
User is often shown ad ad-result in the first video slot.

## Expected result:
User should be able to block these elements, without leaving an empty region on the page.

## Reproduces how often: 
Not always, but often.

## Desktop Brave version:
Testing in 1.14.84

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  TBD
- Can you reproduce this issue with the nightly channel? TBD

**Comment by ryanbr** [comment]
I mostly fixed this in  https://github.com/easylist/easylist/commit/7e39a57 which removed the advert people were complaining about, but didn't collapse the advert.

uBO callapses this element with `youtube.com##ytd-display-ad-renderer:upward(2)` inhttps://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt  @antonok-edm

**Comment by antonok-edm** [comment]
Will need support for procedural cosmetic filter implementations in both brave-core and adblock-rust.

**Comment by jcosentino** [comment]
I wanted to report that I am also experiencing this:
<img width="960" alt="youtube brave unhidden element" src="https://user-images.githubusercontent.com/1408654/115959586-e531bd00-a4da-11eb-8eb2-0f7547b4e6b4.png">

I tried adding this filter:
`youtube.com##ytd-display-ad-renderer:upward(2)`

But this was to no avail.

**Comment by nithinkodadhavadee** [comment]
I know you guys are still working on this, but just another update. I got this too, I didn't have this until now but I can see ads everywhere. Video ads, banners, everywhere on youtube.

![image](https://user-images.githubusercontent.com/50230678/132119993-946692a1-ab72-4835-814d-b689c0229d73.png)

![image](https://user-images.githubusercontent.com/50230678/132120009-a32968ce-df5a-441b-9971-95fbeca3ce94.png)


even in google search
![image](https://user-images.githubusercontent.com/50230678/132120023-3d1ea781-23c9-4075-b1ef-22a82b04286f.png)

**Comment by siferati** [comment]
Adding `youtube.com##ytd-display-ad-renderer` to the list of custom filters solved this issue for me.

**Comment by 0x802** [comment]
# how i can remove this ad !!
![image](https://user-images.githubusercontent.com/53880289/200383726-8c6522aa-eb03-4961-a690-e7e50d82f793.png)

------
The xpath for the ad is : 

```html
/html/body/ytd-app/div[1]/ytd-page-manager/ytd-browse/ytd-two-column-browse-results-renderer/div[1]/ytd-rich-grid-renderer/div[3]/ytd-ad-slot-renderer/div/ytd-page-top-ad-layout-renderer/div/ytd-video-masthead-ad-v3-renderer/div/div[2]/ytd-video-masthead-ad-primary-video-renderer/div[2]/a
```
