### ISSUE TITLE
[Widget] Missing translations for Bitcoin.com widget

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11963]
## Description 
 
Missing translations for Bitcoin.com widget

## Steps to Reproduce

   1. Set device locale to non-EN 
   2. Install nightly 
   3. Bitcoin.com widget has missing translations

## Actual result:

<img width="1055" alt="Screenshot 2020-10-02 at 08 39 06" src="https://user-images.githubusercontent.com/17010094/94901778-c7f0bf00-04b4-11eb-82d3-8c3791469ddf.png">

## Expected result:
All text should be translated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.17.7 Chromium: 86.0.4240.55 (Official Build) nightly (x86_64)
-- | --
Revision | `a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanml** [comment]
Closing this as Bitcoin.com is no longer a widget
