### ISSUE TITLE
Rework shields panel into simple view

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1196]
## Description
Show a "Simple view" on Shields which will be the global default view for all users. The colors and fonts should be the same as what already exists in the Shields panel.

## Design 
![shields simple 1](https://user-images.githubusercontent.com/2388823/59471950-9d778000-8df1-11e9-80fa-5ff74d320978.png)

![shields simple and advanced off](https://user-images.githubusercontent.com/2388823/59471956-a2d4ca80-8df1-11e9-810a-e8344ee1d3b2.png)

![shields simple 2](https://user-images.githubusercontent.com/2388823/59471981-c1d35c80-8df1-11e9-9b8e-9ad23cae7f7f.png)

## User Flows
![user flows - simple and advanced per site customizatiom](https://user-images.githubusercontent.com/2388823/59471991-c861d400-8df1-11e9-8c51-47531d6e6201.png)

Abtract link for more CSS and plain text: https://share.goabstract.com/346f8cac-0c8f-4ebf-b76f-716a92e6c05b

**Comment by tomlowenthal** [comment]
Karen is going to come through with some slightly-updated designs which mach the typeface weights and colors from #1956.

**Comment by tomlowenthal** [comment]
@karenkliu Can you verify the mockups and update as needed, then reassign to @cezaraugusto for implementation.

**Comment by karenkliu** [comment]
Updated!

**Comment by cezaraugusto** [comment]
hi @karenkliu, edit still shows the old date. maybe something went wrong with the update files?
<img width="429" alt="Screen Shot 2019-06-13 at 17 26 25" src="https://user-images.githubusercontent.com/4672033/59465065-69578b80-8e00-11e9-9bdf-8984e3effc27.png">

**Comment by karenkliu** [comment]
@cezaraugusto Hi Cezar, I checked it again - can you see my updates now?

**Comment by karenkliu** [comment]
Hi @cezaraugusto, thank you for creating a prototype of this issue at https://brave-ui-lut80zzvu.now.sh/?path=/story/feature-components-shields--panel.

Please see my feedback:

![simple view QA 1](https://user-images.githubusercontent.com/2388823/60300625-3b844380-98e4-11e9-856a-31612475ac86.png)

The main issue is that in the Simple view, when the user clicks "Learn more," they should get a read only list of what's blocked. This list matches 1 to 1 the settings that are on the Advanced view, but is read-only. 

Also, I exported the icon on the alert dialog for you:
[alert-message-o.zip](https://github.com/brave/brave-browser/files/3336635/alert-message-o.zip)

**Comment by karenkliu** [comment]
Hi @cezaraugusto, thanks for your updates. Please see additional design feedback below:

![simple view QA 2](https://user-images.githubusercontent.com/2388823/60470769-971d3c80-9c16-11e9-96c1-c600056e5493.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux

* Verified test plan from https://github.com/brave/brave-core/pull/2874
* Verified one time message is shown
![image](https://user-images.githubusercontent.com/17010094/63973550-fcf03e00-ca78-11e9-8734-f3fb2cd2ba43.png)
* Verified advance view is retained between pages after dismissing the notification
* Verified simple view is retained between pages if advance view is never clicked or changed in settings
