### ISSUE TITLE
Widget stack operations should be moved to their own reducer

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#11961]
In addition to having its own reducer file, widget manipulation triggered as a result of preferences changes should be handled when the `NEW_TAB_PREFERENCES_UPDATED` redux action fires, and not handled in the `componentDidUpdate` method of the `NewTab` component. There should be no regressions in behavior.

**Comment by bsclifton** [comment]
Updated milestone to be 1.18.x as this was closed with https://github.com/brave/brave-core/pull/6753 😄👌
