### ISSUE TITLE
Feature Request: Blank clean background on new tab

### ISSUE THREAD

**Issue by specter78** [brave/brave-browser#11962]
Disabling background image on desktop browser makes the new tab page have pink-purple gradient background. 

What I’m requesting is clean background like that of safari.

**Comment by srirambv** [comment]
Should be covered by https://github.com/brave/brave-browser/issues/353

**Comment by xmha97** [comment]
You can use it:
https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/15252 - see issue for updated designs (and subscribe if interested!)
