### ISSUE TITLE
remove cookie notification from url bar, redundant with Brave Shields

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1197]
## Description 
Remove cookie notification icon from url bar.

Cookie notification in url bar is redundant functionality with Brave Shields. 
And ability to manage cookies is available from the lock/site settings menu.

## Remove icon on left
![screen shot 2018-09-19 at 11 52 55 am](https://user-images.githubusercontent.com/5951041/45780588-bc563680-bc12-11e8-9661-7587106e3dd7.png)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified no cookie icon is shown in URL bar when Shields settings is different from global settings
* Verified blocking all cookies globally and then visiting a site doesn't show the cookie icon in URL bar
