### ISSUE TITLE
Bookmark and Sync Related Immediate Improvement required

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#11970]
## Description 

Feature request--->> ** Add sort by time in bookmarks**
Most Imp--->>**In pc brave version, in bookmark menu there is no way to select all bookmarks at once and delete or copy them.**

Most Imp--->>**Opened tabs not synced**

Immediate change required--->>**In menu > history > opened tab on another device shown. But want to open many of them in pc at once. Not possible right now.**

So add option in opened tab history to open all tabs from another device in this current device.

**Also add option :: Open in new tab in open tab history. Because in currently, in menu > history > opened tab on another device > when right cliked it opens that tab and exits setting. But i want to open them in background means i right click on tab and click open in new tab but it should not exit and open new tab rather open tab in background and still remains in same menu so that i can open multiple such tabs instead of everytime going to menu and repeating tedious steps**

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No not on chrome but may be on chromium

**Comment by rebron** [comment]
Closing. @tathastu871 Please use the template and one issue at a time with clearer specifics.
