### ISSUE TITLE
White flash on first loading of any page in Night Mode

### ISSUE THREAD

**Issue by jenabaivab** [brave/brave-browser#11985]
## Description 
There is a bright flash of light in night mode setting before a page is loaded causing issues with late night browsing

## Steps to reproduce 

   1. Open the browser
   2. Open any page

## Actual result 
A bright flash happens before the page is loaded

## Expected result
The screen should be dark till the page loads

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

Happens on all the channels
- Can you reproduce this issue with the current Play Store version? 
Yes
- Can you reproduce this issue with the current Play Store Beta version? 
Yes
- Can you reproduce this issue with the current Play Store Nightly version?
Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:10
   
## Brave version
1.14.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional information

I understand this is more than likely an issue with the chromium flag. A lot of other browsers have managed to fox this though like Chrome, Vivaldi, Samsung Internet even Kiwi. This basically negates the entire point of night mode browsing since it's impossible with the constant flashbangs.

**Comment by jenabaivab** [comment]
Any help here please?

**Comment by bsclifton** [comment]
cc: @deeppandya - not sure how easy this would be to solve

**Comment by jenabaivab** [comment]
@bsclifton this bug is now fixed in the latest nightly and dev builds after a chromium upgrade.

**Comment by bsclifton** [comment]
@jenabaivab awesome! Thanks for the update 😄 And apologies for not circling back to this sooner ☹️

**Comment by jenabaivab** [comment]
@bsclifton absolutely no need to explain.
Your time is valuable.

**Comment by mikael-lehmuskoski** [comment]
Any idea why I'm seeing this again on Android? Anyone else? Possible regression?
