### ISSUE TITLE
Add Bitcoin.com widget to the NTP

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#11982]
<img width="600" alt="Screen Shot 2020-09-22 at 11 15 57 AM" src="https://user-images.githubusercontent.com/8732757/93921154-03290c00-fcc5-11ea-958f-c1555f560e31.png">
<img width="600" alt="Screen Shot 2020-09-22 at 11 15 39 AM" src="https://user-images.githubusercontent.com/8732757/93921161-058b6600-fcc5-11ea-9cc4-5cb4832148f4.png">

Note the available regions: https://github.com/brave/brave-core/pull/6681/files#diff-99ab139e0e75cd3b8c853a30d3abb80aR14 (No US, Canada, India)

Test plan:
1. Fresh profile
2. Navigate to `brave://newTab`
3. Ensure Bitcoin.com is available behind the Binance widget on the NTP
4. Open up New Tab page dashboard settings, select 'More Cards'
5. Scroll to Bitcoin.com
6. Ensure that 'Hide' removes it from the stack, and that 'Add' adds it to the foreground
7. Ensure that default fiat currency is 'EURO'
8. Ensure that Fiat can be changed to CAD
9. Ensure that the primary currency can be changed to BTC
10. Ensure that the amount input can be changed to 100, and only acceptable numerical values, ex(1, 2, 3, 3.50, 200.50, 500)
11. Click `Buy`
12. Ensure it opens a new tab to: https://bitcoincom.moonpay.io/?currencyCode=btc&baseCurrencyCode=cad&baseCurrencyAmount=100
13. Ensure clicking on `Get the wallet here to get started` opens to: https://bitcoincom.moonpay.io/
14. Navigate to `brave://settings#newTab`
15. Ensure that Bitcoin.com can be shown/hidden

**Comment by ryanml** [comment]
Backfilled issue, closed in: https://github.com/brave/brave-core/pull/6681

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.15.70 Chromium: 86.0.4240.68 (Official Build) (64-bit)
-- | --
Revision | `ad72ee9aa8e15ed300df1238e76c7a8f4d686f97-refs/branch-heads/4240@{#1097}`
OS | Linux

- Verified `Bitcoin.com` widget is available on a clean install and is stacked behind Binance widget
![image](https://user-images.githubusercontent.com/17010094/95101289-e14e7100-0729-11eb-80e1-4b11b5e24272.png)

- Verified `Bitcoin.com` widget is available in more cards under dashboard setting and can be added or removed
![image](https://user-images.githubusercontent.com/17010094/95101330-eca19c80-0729-11eb-8f30-ac4daae1e73c.png)

- Verified EUR is the default currency selected
- Verified able to change default currency from `Bitcoin Cash (BCH)` to other values in the dropdown
![image](https://user-images.githubusercontent.com/17010094/95101403-0216c680-072a-11eb-94b4-5931ef40555d.png)

- Verified Fiat currency can be changed from EURO to other 
![image](https://user-images.githubusercontent.com/17010094/95101412-03e08a00-072a-11eb-9cc0-9c09bbc19c21.png)

- Verified `https://bitcoincom.moonpay.io/?currencyCode=eth&baseCurrencyCode=eur&baseCurrencyAmount=100.2` is loaded when clicked on Buy button after entering the fiat currency value
- Verified fiat amount input field only accepts whole values or decimal values and no string input is accepted
- Verified entering a single decimal value is rounded of to two decimal places on the landing page
- Verified clicking on the Buy button opens the landing page in a new tab
- Verified `Get the wallet here to get started` opens to: `https://bitcoincom.moonpay.io/`
- Verified `New Tab Page` menu under settings has `Bitcoin.com` entry 
![image](https://user-images.githubusercontent.com/17010094/95101668-528e2400-072a-11eb-93e6-662ebf727653.png)

- Verified the widget can be disabled by 
   - Widget menu
   - NTP Dashboard settings
   - NTP Menu settings (`brave://settings/newTab`)
- Verified for unsupported region there is no `Bitcoin.com` widget in

NTP | Dashboard settings | New Tab Page settings 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/95101875-97b25600-072a-11eb-88cf-f74398e000ff.png) | ![image](https://user-images.githubusercontent.com/17010094/95102000-bd3f5f80-072a-11eb-8c44-e594ea5f7680.png) | ![image](https://user-images.githubusercontent.com/17010094/95102044-cd573f00-072a-11eb-9ffc-f3c6bb2cd458.png)
