### ISSUE TITLE
Clicking on tab's top doesn't select it sometimes in a maximized window

### ISSUE THREAD

**Issue by ilyaigpetrov** [brave/brave-browser#11983]
## Description 

In a brave maximized window clicking on the very top of a tab doesn't select it sometimes.
On the gif attached you may see that tabs lose highlight while I keep the cursor at the top of the screen all the time.

## Steps to Reproduce

   1. Open brave in a maximized window with some tabs open (pinned or not).
   2. Move cursor to the very top of a tab, move it left or right slightly, see tab loses or gains highlights repeatedly.
   3. See that clicking a tab when it loses highlight doesn't select it.

## Actual result:

Tab is not selected on a click on its top.

## Expected result:

Tab must be selected on a click on its top.

## Reproduces how often: 

Every time I use Brave.

## Brave version (brave://version info)

Brave	1.16.48 Chromium: 86.0.4240.55 (Official Build) beta (64-bit)
Revision	a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS	Linux
JavaScript	V8 8.6.395.10
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.55 Safari/537.36
Command Line	/opt/brave.com/brave-beta/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,DnsOverHttps,OmniboxContextMenuShowFullUrls,LegacyTLSEnforced,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,PrefetchPrivacyChanges --disable-features=PrivacySettingsRedesign,NotificationTriggers,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,SmsReceiver,TabHoverCards,VideoPlaybackQuality,AutofillServerCommunication,PasswordCheck,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end
Executable Path	/opt/brave.com/brave-beta/brave
Profile Path	/home/ilyaigpetrov/.config/BraveSoftware/Brave-Browser-Beta/Default

## Version/Channel Information:

Tested and happens on beta channel.

- Can you reproduce this issue with the current release? 
No, no such problem in:
  Brave | 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
  Revision | a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
  OS | Linux
- Can you reproduce this issue with the beta channel?
Yes.
- Can you reproduce this issue with the nightly channel? 
Yes, reproducible on:
  Brave | 1.17.11 Chromium: 86.0.4240.68 (Official Build) nightly (64-bit)
  Revision | ad72ee9aa8e15ed300df1238e76c7a8f4d686f97-refs/branch-heads/4240@{#1097}
  OS | Linux

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

Not reproducible on:

Google Chrome | 85.0.4183.15 (Official Build) dev (64-bit)
Revision | 53db90617a040f373db04863f92240061be06d3d-refs/branch-heads/4183@{#221}
OS : Linux

## Miscellaneous Information:

Linux Mint 20 Xfce Edtition

## The Gif

![brave-tab-top-clicks](https://user-images.githubusercontent.com/1090811/94994964-83cfee00-058a-11eb-99b2-14ab9d4ec864.gif)

**Comment by Wobblystep** [comment]
Happens to me on Arch Linux as well now that i have updated from 1.14.something to Version 1.15.72.

**Comment by FrozenAlex** [comment]
I have the same issue on arch linux KDE on 1.15.72 Chromium: 86.0.4240.75 (Official Build)

**Comment by Wobblystep** [comment]
I was able to work around something similar, but for MATE panel, which also uses GTK3.
By adding "export GDK_CORE_DEVICE_EVENTS=1" to my bash profile ([https://github.com/mate-desktop/mate-panel/issues/940](url)) the edge flickering input problem was fixed there.

But it doesn't affect the Brave problem, even if I run the brave binary directly with that variable set in front.
Also tried with disabled sandboxing.

**Comment by ilyaigpetrov** [comment]
This bug is observed not only in Brave but also in Chromium:
> 86.0.4240.198 (Official Build) for Linux Mint (64-bit)
> Revision | d8a506935fc2273cfbac5e5b629d74917d9119c7-refs/branch-heads/4240@{#1431}
> OS | Linux

**Comment by ilyaigpetrov** [comment]
Seems to be fixed in: 
> 1.18.57 Chromium: 87.0.4280.66 (Official Build) beta (64-bit)
> Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
> OS | Linux

Please, reopen this issue if it becomes reproducible again in Brave Beta or Brave Nightly.
