### ISSUE TITLE
Typo in italian translation for privacy report

### ISSUE THREAD

**Issue by oidualc** [brave/brave-browser#11984]
## Steps to reproduce 

   1. With italian language selected open Settings
   2. Scroll to the Privacy Report section

## Actual result 
![image](https://user-images.githubusercontent.com/6648988/94998455-31a2c300-05b2-11eb-9198-7cc0927cef17.png)

## Expected result
Report Privacy is shown

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.17.3

**Comment by srirambv** [comment]
Translations are done https://www.transifex.com/brave/brave/. If you can sign up and fix it there we should be able to pull in the changes for a release

**Comment by oidualc** [comment]
Glad to help, I signed up to that link but I guess external occasional contributions are not accepted right? I requested to join the Brave team to fix this label.

**Comment by anthonypkeane** [comment]
@oidualc Thanks for reporting. I've updated the text to "Report Privacy" Can you confirm if this is correct or should it be something else? Thanks

**Comment by oidualc** [comment]
Yes, I confirm.

**Comment by anthonypkeane** [comment]
Thank you

**Comment by oidualc** [comment]
When will this be available in nightly? I see the issue is now closed but the string I see is still incorrect

**Comment by anthonypkeane** [comment]
Perhaps next week @oidualc please standby. Thanks
