### ISSUE TITLE
Rendering borked bspwm

### ISSUE THREAD

**Issue by crazymonkyyy** [brave/brave-browser#11988]
![2020-10-04-103129_831x805_scrot](https://user-images.githubusercontent.com/5334907/95021219-e37ed580-062c-11eb-924b-aac8a3ae74ab.png)

Rendering slightly broken

## Steps to Reproduce

   1.  Go to a js/video site
   2. Use the scroll wheel

## Reproduces how often: 
Frequently

## Brave version (brave://version info)

Brave | 1.14.84 Chromium: 85.0.4183.121 (Official Build) unknown (64-bit)
-- | --
Revision | a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
OS | Linux
JavaScript | V8 8.5.210.26
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=MixedContentSiteSetting,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,PrefetchPrivacyChanges,OmniboxContextMenuShowFullUrls,LegacyTLSEnforced,DnsOverHttps --disable-features=TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,PrivacySettingsRedesign,SafeBrowsingEnhancedProtection,TabHoverCards,SmsReceiver,VideoPlaybackQuality,AutofillServerCommunication,PasswordCheck --flag-switches-begin --flag-switches-end
Executable Path | /usr/lib/brave-bin/brave
Profile Path | /home/monkyyy/.config/BraveSoftware/Brave-Browser/Default

Using bspwm

**Comment by rebron** [comment]
@crazymonkyyy can you try with the latest 1.16.76 and wondering if toggling some parts of shields or hardware accelleration helps brave://settings/system

**Comment by rebron** [comment]
Closing as stale. @crazymonkyyy If you're still having issues please file a new issue. Latest version is 1.19.86
