### ISSUE TITLE
Write webtorrents to disk when done

### ISSUE THREAD

**Issue by tildelowengrimm** [brave/brave-browser#1199]
If I completely download a file with webtorrent and then restart my browser, I have to start over. That's not the best. When a torrent is finished downloading, it should probably be written to disk. That seems like a thing which'll be needed before someone can use the file for whatever they need that file for.

It seems reasonable to write the file to the same downloads folder that we put everything else in. This should probably be a default. It would also be reasonable to make this destination configurable — either for torrents on the whole, or for a specific torrent.

**Comment by levinobre** [comment]
Same situation here. Previously (Brave), WebTorrent saves the temp file in C:\tmp\webtorrent\. I think that Brave Dev/Beta should implement this option as done in Brave.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/torrent-client-in-brave/43474?u=eljuno

**Comment by Michaelmantion** [comment]
I would like to use brave browser but use torrents a lot.  Can we just disable braves built in torrent program some how?

**Comment by bsclifton** [comment]
@Michaelmantion yes - you can go to brave://settings and under `Extensions` you should be able to disable 😄 
<img width="704" alt="Screen Shot 2019-08-11 at 11 21 04 PM" src="https://user-images.githubusercontent.com/4733304/62848105-c354c000-bc8e-11e9-8118-9253b6f6413a.png">

**Comment by Michaelmantion** [comment]
Thanks

**Comment by jdezego** [comment]
This is over a year old and nothing has changed. It seems to be a glaring oversight that the file a torrent points to is not **SAVED** when I choose to download/save it, especially when the interface says **SAVE ALL FILES**. How is this not a top priority that gets fixed **TODAY**?!?

**Comment by bsclifton** [comment]
@rebron should we bump this up in priority? (P4?)

Definitely seems annoying that you can't choose where to save (and you have to know it was stored in temp folder). Almost makes this feature useless

**Comment by wojciechrak** [comment]
I'd even say, that it should write downloaded data to disk during all download process, not only when it's finished. Now if you close the tab/browser or page crashes ("Aw Snap!" - happened to me just now), you lose all progress. It would be nice if it behaved more like regular torrent client in this regard.

**Comment by lifeinchords** [comment]
+1 to @wojciechrak. ie, pause and resume

**Comment by Sowiedu** [comment]
How in the everliving f*** is this still an issue? I don't get it. What am I missing here? You add awesome features and this right here makes it 100% unusable. I'm a fairly adept user of torrents and IT in general and I was so happy having a way to just download a torrent without having to do anything additional. It could just work. And this two year old problem which is the single most important thing in a download itself, much more in a torrent is still open? Was this a design decision or is it in some way architecture related that this doesn't work as any sane person would expect it wo work? Don't get me wrong, I just downloaded a metric s***ton of data and lost it all. I may be ranting a bit, but I appreciate the work that goes into brave. I just do not understand how this issue persists til today. That's almost 2 years.

**Comment by charltonh** [comment]
This is still an issue.  Robbed me of some time and made me very angry.   Broken software for years?

**Comment by volkans80** [comment]
Very annoying...

**Comment by CRK1918** [comment]
This method is saved in your memory, what if the file you downloading is much larger than your computer’s internal memory?

**Comment by srirambv** [comment]
Closing in favour of #5563
