### ISSUE TITLE
remove URL/ID identifiers from reward logs for various publishers - follow up to #11795

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11992]
## Description 

Per #11795 some publisher info can still be seen in logs (launched via terminal as noted below, not available in the browser).

Visiting YT channels/publishers will produce the following logs which includes the channel ID as per the following:
```
[821:775:1005/092319.810726:INFO:CONSOLE(0)] "Refused to display 'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26feature%3Dpassive%26hl%3Den%26next%3D%252Fsignin_passive&hl=en&passive=true&service=youtube&uilel=3' in a frame because it set 'X-Frame-Options' to 'deny'.", source: https://www.youtube.com/channel/UCCs7AQEDwrHEc86r0NNXE_A/videos (0)
```

```
[821:775:1005/092323.184051:INFO:CONSOLE(0)] "The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/channel/UCCs7AQEDwrHEc86r0NNXE_A/videos (0)
```

Visiting Twitter pages/users will produce the following logs which includes the full URL of the page being visited as per the following:
```
[821:775:1005/092550.669785:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: https://twitter.com/bravelaurenwags (0)
```

## Steps to Reproduce
Launch Brave using the following switches via a terminal/CLI:

```
 --args --enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6
```

   1. Visit any TY channel and you'll notice the URL being logged with the channel's ID
   2. Visit Twitter and you'll notice the URL being logged with the full URL

## Actual result:

Logs provided above re: results. Certain websites are still logging URLs/ID's via the logs.

## Expected result:
Any identifying URLs/information should be removed from being dumped into the terminal/logs.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.16.52 Chromium: 86.0.4240.68 (Official Build) dev (x86_64)
-- | --
Revision | ad72ee9aa8e15ed300df1238e76c7a8f4d686f97-refs/branch-heads/4240@{#1097}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? yes
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @kjozwiak @rebron @NejcZdovc

**Comment by NejcZdovc** [comment]
@LaurenWags this are not rewards logs, this is something that chromium and other services will print out. We can close this one

**Comment by LaurenWags** [comment]
@kjozwiak you ok with this since you had logged the original issue?

**Comment by diracdeltas** [comment]
@LaurenWags does this happen when brave is launched without any special arguments?

**Comment by LaurenWags** [comment]
@diracdeltas I do not see those log messages when I launch via terminal with the following:
- `/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser` (no args at all)

But I can reproduce at least one of the YouTube messages when I use the logging parameters only (no specific rewards ones):
- `/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser --args --enable-logging=stderr`

```
[12034:775:1028/074042.575757:INFO:CONSOLE(0)] "The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/user/jjdsampson (0)
```

The other YouTube message from the description isn't showing with only the two args above however I can dig in further if you'd like, let me know what I can do to help.

**Comment by NejcZdovc** [comment]
you see this because you enabled chromium logging

**Comment by LaurenWags** [comment]
@NejcZdovc yes, understood. I only got the 1 message though and there are 3 that were still occurring. I'd imagine if I started turning on the other flags one by one I might get the other 2. Not sure if that's needed information.

**Comment by diracdeltas** [comment]
just to clarify, these are logs that appear in the terminal? (as opposed to rewards-internals logs)

**Comment by Miyayes** [comment]
@LaurenWags Old, but @diracdeltas is correct in her understanding, right?

>just to clarify, these are logs that appear in the terminal? (as opposed to rewards-internals logs)

If @diracdeltas thinks it's unproblematic in that case (and it is indeed the case), then we can close this out.

**Comment by LaurenWags** [comment]
@Miyayes iirc yes, from the terminal.

**Comment by Miyayes** [comment]
@diracdeltas given LaurenWags's confirmation, is this still an issue, or should we close this out as `wontfix`?
