### ISSUE TITLE
Only the top navigation bar is displayed on Rewards page

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#12004]
## Description 
Rewards page is broken.

## Steps to Reproduce

   1. Visit brave://rewards (with system locale set to United States and connected via a VPN to the US)
  
## Actual result:
<img width="1680" alt="Screen Shot 2020-10-05 at 12 02 40 PM" src="https://user-images.githubusercontent.com/4730197/95120611-b00e7a80-0702-11eb-8c07-9e1f5ea6051a.png">
<img width="864" alt="Screen Shot 2020-10-05 at 12 06 41 PM" src="https://user-images.githubusercontent.com/4730197/95121010-4478dd00-0703-11eb-8c42-0832300f5e64.png">

## Expected result:
Rewards page should be shown normally..

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Version 1.17.13

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel?  No
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:
It seems like the page is still broken for me after https://github.com/brave/brave-core/pull/6734 is merged.
cc @rebron @tmancey

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.17.28 Chromium: 86.0.4240.75 (Official Build) nightly (64-bit)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | Ubuntu 18.04 LTS


Verified test plan from https://github.com/brave/brave-core/pull/6776
![image](https://user-images.githubusercontent.com/34715963/96005036-5ada1380-0e3c-11eb-82b9-a54b5cb9a0d1.png)
![image](https://user-images.githubusercontent.com/34715963/96005434-ba382380-0e3c-11eb-8823-71349970d75b.png)
