### ISSUE TITLE
Change wording for Safety Check

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12008]
## Description 

@fmarier comment from https://github.com/brave/brave-browser/issues/11741#issuecomment-703887923

![Screenshot from 2020-10-05 14-00-28](https://user-images.githubusercontent.com/167821/95131585-27e4a100-0713-11eb-84b0-324ddbec7919.png)
which needs to be modified because we don't currently offer any data breach notifications (though we want to in #12001).

I'd suggest the following:
> Brave can help keep you safe from malicious websites, bad extensions and more

**Comment by rebron** [comment]
@0xedward Interested in grabbing this one too?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)


```
- Verified the description and test plan from https://github.com/brave/brave-core/pull/6892
- Issue isn't fixed logged follow up the issue  - https://github.com/brave/brave-browser/issues/12859
