### ISSUE TITLE
Unable to display https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.xhtml

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#12011]
## Description 
Get a blank webpage/unloaded page when opening `https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.xhtml` in Brave Release

## Steps to Reproduce

   1. Open `https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.xhtml`
   2. Nothing loads, Blank tab is shown.
   3. Browser console shows no error messages, or any details.

## Actual result:
Tab shows no title. Task manager shows Blank tabs (4 instances of this site)
![task-man](https://user-images.githubusercontent.com/1659004/95191276-05df4180-082d-11eb-9d59-0dbeee7b4a86.png)

## Expected result:
Show website.

## Reproduces how often: 
Eventually saw this

## Brave version (brave://version info)
`Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Not related to VPN, or shields.

Private window mode briefly worked, after a few page refreshes it now is blank.

Brave Beta worked fine, from what I see. Different Brave Release profile may show it.

Was also reported by @bkero

**Comment by coughingmouse** [comment]
Loads fine on my laptop (QubesOS/Debian 10) ¯\_(ツ)_/¯.

**Comment by rebron** [comment]
@ryanbr Tried this on Windows and macOS 1.18.70 release channel and looks like it's loading properly now. Ok to close?

**Comment by ryanbr** [comment]
Okay closing, seems fine here
