### ISSUE TITLE
[Android] password prompt shows Chrome graphic

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12018]
## Description 
When navigating to a site where you have a saved username/password, when you tap into one of the fields there is a prompt displayed which uses Chrome's image

## Steps to reproduce 

   1. Navigate to a site with a login page 
   2. Enter username/password and save this when prompted.
   3. Log out of site if necessary
   4. Navigate to site again
   5. Tap on username field

## Actual result 
![Screenshot_20201006-125221](https://user-images.githubusercontent.com/28145373/95235270-a0129b80-07d3-11eb-866f-04aef1c63271.jpg)

## Expected result
This is how it shows in 1.14.x and also how it shows if you swipe down on the prompt:
![Screenshot_20201006-130017](https://user-images.githubusercontent.com/28145373/95235817-11eae500-07d4-11eb-940f-885b1b622379.jpg)

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? no with 1.14.x
- Can you reproduce this issue with the current Play Store Beta version? yes with 1.15.x
- Can you reproduce this issue with the current Play Store Nightly version? yes with 1.17.x

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.15.71

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @anthonypkeane @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Brave v1.15.71 on Samsung Galaxy Tab S5e (Android 9.0)

![Screenshot_20201006-190641_Brave](https://user-images.githubusercontent.com/34715963/95236604-72474a00-0807-11eb-9305-e9302af9c5fa.jpg)

**Comment by GeetaSarvadnya** [comment]
Reproduced in ARM - 1.15.71 (Samsung Galaxy 5.1)
![Screenshot_2020-10-06-22-42-54](https://user-images.githubusercontent.com/38657976/95237226-8dc14d80-0825-11eb-923f-bc8f1617604c.png)

**Comment by LaurenWags** [comment]
similar to https://github.com/brave/brave-browser/issues/10008 on Desktop from 1.10.x

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.15.73 Bravex86.apk
- Verified STR from description
![Screenshot_20201007-183301](https://user-images.githubusercontent.com/28145373/95395045-b439c400-08cb-11eb-80cb-d5273743393d.jpg)

-----------
