### ISSUE TITLE
Shield icon is disabled when browser is newly launched

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#1202]
## Description 

Shield icon is disabled when browser is newly launched

## Steps to Reproduce

   1. Launch browser and create only one tab with `www.google.com`
   2. Change `On startup` setting to `Continue where you left off`
   3. Close browser
   4. Launch browser

## Actual result:

Shield icon is in disabled state

## Expected result:
Shield icon is in enabled state

## Reproduces how often: 

100% on MacOS

## Brave version (chrome://version info)

0.55.2 Chromium: 70.0.3538.16 (Developer Build) (64-bit)

### Reproducible on current release:

Yes, tested on MacOS

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Same as https://github.com/brave/brave-browser/issues/505?

**Comment by simonhong** [comment]
@srirambv Oh, this seems same scenario as https://github.com/brave/brave-browser/issues/505#issuecomment-417794950 describes

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
