### ISSUE TITLE
[Follow-up to #11996] Adjust margin so all currencies are listed properly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12028]
## Description 

[Follow-up to #11996] Adjust margin so all currencies are listed properly

## Actual result:

Margin can be upto `2.5px` so that other tokens `KRW`/`KWD`/`TWD` don't break
![image](https://user-images.githubusercontent.com/17010094/95289944-eb748a80-0863-11eb-824d-51053d20180d.png)

`KWD` breaks at 3px as well so having 2.5px fixes it for all
![image](https://user-images.githubusercontent.com/17010094/95289973-02b37800-0864-11eb-96b0-b2e039a319c3.png)

But having margin set to 2.5px causes other currencies like `IDL`/`ILS`/`JPY`/`JOD` to look odd
![image](https://user-images.githubusercontent.com/17010094/95290040-38f0f780-0864-11eb-8ada-7cd3ef2f0fae.png)

## Expected result:
Proper margins so that all currencies are listed correctly and dropdown arrow doesnt go on to next line

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.17.18 Chromium: 86.0.4240.72 (Official Build) nightly (x86_64)
-- | --
Revision | `581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}`
OS | macOS Version 10.15.7 (Build 19H2)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanml** [comment]
This was fixed via: https://github.com/brave/brave-core/pull/6804

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.17.61 Chromium: 86.0.4240.185 (Official Build) beta (64-Bit)
-- | --
Revision | `37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}`
OS | Linux

- Verified all currencies are listed properly

KRW | KWD | TWD
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/98662656-042eff00-2340-11eb-926c-976f2b39ac88.png) | ![image](https://user-images.githubusercontent.com/17010094/98662755-27f24500-2340-11eb-94ab-01385e395940.png) | ![image](https://user-images.githubusercontent.com/17010094/98662793-33457080-2340-11eb-8627-4f481a019a69.png)
---------

Verification passed on 

Brave | 1.17.61 Chromium: 86.0.4240.185 (Official Build) beta (64-Bit)
-- | --
Revision | `37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}`
OS | 

- Verified all currencies are listed properly

KRW | KWD | TWD
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/98663388-ef9f3680-2340-11eb-8a1f-16aff710cf06.png) | ![image](https://user-images.githubusercontent.com/17010094/98663427-ffb71600-2340-11eb-8622-47f147da4c58.png) | ![image](https://user-images.githubusercontent.com/17010094/98663464-0cd40500-2341-11eb-8b65-4dfa65ad0010.png)

---------

Verification passed on 

Brave | 1.17.61 Chromium: 86.0.4240.185 (Official Build) beta (x86_64)
-- | --
Revision | `37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified all currencies are listed properly

KRW | KWD | TWD
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/98661081-f0829900-233d-11eb-97bd-5dc61b5cc536.png) | ![image](https://user-images.githubusercontent.com/17010094/98661131-01cba580-233e-11eb-8bf6-c586ae5af672.png) | ![image](https://user-images.githubusercontent.com/17010094/98661021-e1035000-233d-11eb-84bd-d43469f4ce35.png)
