### ISSUE TITLE
Remote frames not farbling user agent properly

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#12020]
noted in https://github.com/brave/brave-browser/issues/9190#issuecomment-703932628

**Comment by pilgrim-brave** [comment]
example from https://dev-pages.bravesoftware.com/farbling.html (all hash values in User Agent row should match)

<img width="1015" alt="Screen Shot 2020-10-06 at 3 15 17 PM" src="https://user-images.githubusercontent.com/43750833/95249514-cb52b600-07e6-11eb-9ef3-ae61f8ea83e2.png">

**Comment by srirambv** [comment]
@pilgrim-brave can you please add OS labels to the issue

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.55 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified https://github.com/brave/brave-browser/issues/12020#issuecomment-704498076

Logged follow up issue https://github.com/brave/brave-browser/issues/12392 for the "Worker" column not matching the other values in that row.

<img width="1199" alt="strict 1" src="https://user-images.githubusercontent.com/28145373/97605983-a9afad80-19e5-11eb-951e-eb0409332adc.png">

-------------

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.17.66 x64 beta build
- Verified steps from https://github.com/brave/brave-browser/issues/12020#issuecomment-704498076

![image](https://user-images.githubusercontent.com/17010094/98841479-14c69e80-2440-11eb-9889-a8d0650e91b0.png) | ![image](https://user-images.githubusercontent.com/17010094/98841501-1a23e900-2440-11eb-820c-1704214b8248.png)
-- | --

- Encountered #12392
---------
Verification passed on OnePlus 6T with Android 10 running 1.17.66 x64 beta build
- Verified steps from https://github.com/brave/brave-browser/issues/12020#issuecomment-704498076

![image](https://user-images.githubusercontent.com/17010094/98841690-64a56580-2440-11eb-8763-c31cd3bdd3a2.png) | ![image](https://user-images.githubusercontent.com/17010094/98841703-6a02b000-2440-11eb-9892-1b0a96ed8f0f.png)
-- | --
