### ISSUE TITLE
Always Show Bookmarks Bar toggle not working in new windows

### ISSUE THREAD

**Issue by peterpicard** [brave/brave-browser#12024]
## Description 

Bookmarks bar toggle (View->Always Show Bookmarks Bar) does not work in second and subsequent browser windows, but keeps working on initial browser window.

## Steps to Reproduce

   1. Open Brave browser and make sure you have some bookmarks in the Bookmarks bar
   2. Enable feature "Always Show Bookmarks Bar" from View menu
   3. Open a new browser window (CTRL+N / CMD+N)
   4. Try to disable "Always Show Bookmarks Bar" from View menu in the new browser window

## Actual result:

Bookmarks Bar does not hide/show when trying to toggle it in the non initial browser window even though the tick is being toggled.

## Expected result:
The Bookmarks bar view toggle should work in all browser windows.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Revision | a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Haven't tested.
- Can you reproduce this issue with the dev channel?
Haven't tested.
- Can you reproduce this issue with the nightly channel?
Haven't tested.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome?
Yes.

**Comment by simonhong** [comment]
Hi @peterpicard , Did you see this in New Tab Page(NTP)?
If so, we have another option for Bookmark on NTP.
It's `Always show bookmarks on New Tab page` at brave://settings/appearance.
If this option is on, NTP always shows bookmark bar.

**Comment by rebron** [comment]
Closing. NTP is special cased with the `Always show bookmarks on New Tab page` setting.
