### ISSUE TITLE
Unable to login to origin.com 

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#12022]
## Description 
Unable to login to origin.com due to cookies

## Steps to Reproduce

   1. Open https://www.origin.com
   2. Click on Sign in (bottom left), new login window will open.
   3. Input user /pass details.
   4. Login fails

## Actual result:
Due to cookies used by ea.com (on origin.com) the login is unable to work:
![ea-login-fail](https://user-images.githubusercontent.com/1659004/95268182-4d98b400-0893-11eb-83c6-9c9728dad0f4.png)

## Expected result:
Allow user to login

## Reproduces how often: 
Easily, with cross-site cookies enabled

## Brave version (brave://version info)
`Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
![ea-origin-cookies](https://user-images.githubusercontent.com/1659004/95267941-d82ce380-0892-11eb-80cc-7837caf78920.png)

We need to allow `.ea.com` cookies on origin.com (which is an EA company site)

**Comment by ryanbr** [comment]
(With Ephemeral Storage enabled). Allow all cookies still needed, tested in Brave Nightly Version 1.30.23 Chromium: 92.0.4515.131 (Official Build) nightly (64-bit).

 ![origin-ea](https://user-images.githubusercontent.com/1659004/129652585-8c307da4-2022-41b8-9b27-21ca46ca2ef9.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.44.100 Chromium: 106.0.5249.61 (Official Build) (64-bit)
-- | --
Revision | 511755355844955cd3e264779baf0dd38212a4d0-refs/branch-heads/5249@{#569}
OS | Windows 11 Version 22H2 (Build 22621.521)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/12022#issue-716073158, ensured that I can login into `Origin` without any issues. I also had 2FA enabled and confirmed that was working as expected as well.

**Comment by Jiansarys** [comment]
I've been asking for this to be fixed in this sorry browser for over a year, and we still have the same issue many months later. What's the point of using Brave if I have to constantly launch Firtefox or VIvaldi in order to log into a lot of sites? if it weren't for BAT this bunk would have died long ago.

**Comment by ryanbr** [comment]
Apologies for the late fix, ea/origin mixing cookies makes it harder for Brave to fix esp blocking 3rd-party cookies. Every browser has some webcompat issues to a certain level (see webcompat.com), just requires time to investigate what the issue is, and the fix is needed. @Jiansarys
