### ISSUE TITLE
Clock format settings are not translated on NTP

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#12029]
Follow up to https://github.com/brave/brave-browser/issues/9038

## Steps to Reproduce

   1. Run Brave in Japanese locale (ja_JP)
   2. Click `Customize` on NTP
   3. Click `Clock`

## Actual result:

Clock format settings are not translated
![image](https://user-images.githubusercontent.com/34715963/95308290-00641480-088a-11eb-9d41-90f2df2a0b41.png)

## Expected result:
Clock format settings are translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.16.54 Chromium: 86.0.4240.72 (Official Build) dev (64-bit)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | Linux

cc @brave/legacy_qa @mkarolin

**Comment by mkarolin** [comment]
@btlechowski I believe you need min. `1.16.55`.

**Comment by btlechowski** [comment]
Yes. This is not reproducible on 1.17.18. Closing as fixed in 1.17.x

![image](https://user-images.githubusercontent.com/34715963/95309419-6ac98480-088b-11eb-88dd-9dad466b6c4d.png)

I will retest it on > 1.16.55

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.16.55 Chromium: 86.0.4240.72 (Official Build) dev (64-bit)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.

![image](https://user-images.githubusercontent.com/34715963/95347424-29ea6380-08bd-11eb-8b68-1f87591503ec.png)
