### ISSUE TITLE
Update puzzle icon for autoplay to an autoplay specific icon

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1203]
## Description 
Currently using puzzle icon with red x mark. Need an autoplay specific icon.

<img width="36" alt="screen shot 2018-09-19 at 11 26 15 pm" src="https://user-images.githubusercontent.com/5951041/45799754-6cec2680-bc63-11e8-8b37-2e5e40bef5c7.png">

## Related
https://github.com/brave/brave-browser/issues/699

**Comment by rossmoody** [comment]
How do we feel about adjusting the scope of this to updating permissions icons for default and blocked states? 
![image](https://user-images.githubusercontent.com/29072694/45910560-fe23e000-bdbe-11e8-9206-8e27d834c5ef.png)

I think these icons also live in site settings page though i'm unsure if they are all pulling from the same place.

**Comment by rebron** [comment]
looks like different icons on chrome://settings/content

**Comment by rossmoody** [comment]
yeah, i think those are generated by iron icons which pulls from a different place than the omnibox, so we should prob break those changes out into another issue, some of them might get or be partially resolved with clifton's settings updates

**Comment by petemill** [comment]
This issue seems to now have a broad scope for all ombnibox permission icons, but https://github.com/brave/brave-core/pull/548 is only addressing autoplay and the generic extension icon, right @rossmoody ?

**Comment by rossmoody** [comment]
@rebron @petemill yeah that was an ill conceived suggestion. I do think replacing that lineup is important but there is additional consideration, sizes, and places that a change like that needs to take into account. should open up a separate issue, i adjusted the scope of this back to the original

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

**Comment by kjozwiak** [comment]
@rossmoody quick question regarding our current icon set while using the dark theme. Is there plans to incorporate a while set of icons for the dark theme? They're pretty hard to see with the current set when using dark theme.. Example:

<img width="161" alt="screen shot 2018-10-11 at 12 49 35 am" src="https://user-images.githubusercontent.com/2602313/46781467-cb9b4200-ccef-11e8-8f5e-31ae0b04fe43.png">

**Comment by rossmoody** [comment]
I agree, Bookmark icons as well. Would like to switch the shield alert circle to purple in dark theme instances as well. There is a huge list of UI adjustments on the docket but shields/rewards are consuming all atm.

**Comment by kjozwiak** [comment]
@rossmoody sounds good! Appreciate the update. Guessing there's no need to create issues. Sounds like it's on the list of things to do 👍
