### ISSUE TITLE
Failing at the brave-core build script

### ISSUE THREAD

**Issue by pavlinpetrov** [brave/brave-browser#12047]
## Description 

Failing at the brave-core build script.

## Steps to Reproduce

   1. npm run init
   2. npm run build

## Actual result:

The init script runs successfully.
Once I try to run the build script, I get an error: ```ninja: build stopped: subcommand failed.``` 
Consecutive build attempts throw the same error, but earlier in the script.
I have attached my terminal logs for both attempts including the complete log (it's the same for both runs).

[build-1.txt](https://github.com/brave/brave-browser/files/5347103/build-1.txt)
[build-2.txt](https://github.com/brave/brave-browser/files/5347105/build-2.txt)
[complete-log.txt](https://github.com/brave/brave-browser/files/5347106/complete-log.txt)

## Expected result:

Successfully build and start the project.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Building from the source in the master branch.
Commit hash - e68b95a19e23d69b9453c805c59291c9e08f61aa

## Miscellaneous Information:

Running on Windows 10 with Visual Studio 2019 Community
[vsconfig.txt](https://github.com/brave/brave-browser/files/5347134/vsconfig.txt)

**Comment by bsclifton** [comment]
@pavlinpetrov if you haven't already, I'd suggest checking out the following docs to make sure you have pre-reqs installed properly https://github.com/brave/brave-browser/wiki/Windows-Development-Environment

Particularly important is the Windows SDK, which I think is now `10.1.19041.1`. You can also check out the Chromium docs on Windows https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#System-requirements
> You must have the version 10.0.19041 or higher Windows 10 SDK installed. This can be installed separately or by checking the appropriate box in the Visual Studio Installer.
>
> The SDK Debugging Tools must also be installed. If the Windows 10 SDK was installed via the Visual Studio installer, then they can be installed by going to: Control Panel → Programs → Programs and Features → Select the “Windows Software Development Kit” → Change → Change → Check “Debugging Tools For Windows” → Change. Or, you can download the standalone SDK installer and use it to install the Debugging Tools.

**Comment by pavlinpetrov** [comment]
@bsclifton I can confirm that I have the ```10.1.19041.1``` SDK installed and modified it to include the SDK Debugging Tools as well.

I've removed the ```10.0.18362.0.``` SDK previously required in the wiki.

I've also double-checked the wiki and the chromium docs and can confirm that:

- I meet the system requirements
- VS2019 >=16.0.0
- “Desktop development with C++” Workload
- “MFC/ATL support” Component - could not find the exact component, so I've installed "C++ MFC for latest v142 build tools (x86 & x64)" and "C++ ATL for latest v142 build tools(x86 & x64)" respectively
- Downloaded ```depot_tools``` and added the directory to my path
- Added ```DEPOT_TOOLS_WIN_TOOLCHAIN``` variable and set it to 0
- Added ```vs2019_install``` variable and set it to my the path of my VS2019 installation
- Successfully ran ```gclient``` and python.bat is above the rest
- Python 2.7

I hadn't mentioned that on one of my first attempts, the script threw an error that cl.exe is missing in my path variable.
Naturally, I've searched my VS2019 installation folder for the file and added the path of the first occurrence to the path variable and the error hadn't appeared again.

**Comment by qikdauie** [comment]
@pavlinpetrov you'll experience this issue if you are attempting to start building the project in any other shell besides cmd. Simply using cmd to start the build should fix the issue.

**Comment by pavlinpetrov** [comment]
> @pavlinpetrov you'll experience this issue if you are attempting to start building the project in any other shell besides cmd. Simply using cmd to start the build should fix the issue.

Thank you! Running the build in cmd solved the problem.
