### ISSUE TITLE
German translation for "Customize" to customize dashboard is truncated

### ISSUE THREAD

**Issue by ff2000** [brave/brave-browser#12044]
![Screenshot_20201008_093936](https://user-images.githubusercontent.com/1973708/95423706-3072ec80-094a-11eb-8daf-2fee859ff52a.png)

The issue is here:

https://github.com/brave/brave-core/blob/e2559f894b8afdf20f7cc0873618760b56036c70/components/resources/strings/brave_components_resources_de.xtb#L30

Instead of "Anpa" it should be "Anpassen"

**Comment by rebron** [comment]
@btlechowski When you get a chance can you check this one on 1.17.73?

**Comment by btlechowski** [comment]
Reproduced on all channels


Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Ubuntu 18.04 LTS

Brave | 1.18.62 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/100399289-74cd5f80-3052-11eb-8cc8-1375d05d1aae.png)

**Comment by btlechowski** [comment]
Still reproducible

Brave | 1.24.16 Chromium: 89.0.4389.105 (Official Build) nightly (64-bit)
-- | --
Revision | 14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/112365229-b3f57f80-8cd7-11eb-984c-f83fec9b4843.png)
![image](https://user-images.githubusercontent.com/34715963/112365097-890b2b80-8cd7-11eb-9546-7c152ff0eab3.png)

**Comment by btlechowski** [comment]
Still reproducible 

Brave | 1.40.19 Chromium: 101.0.4951.41 (Official Build) nightly (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/166330536-5e27bd8b-efdd-451e-894f-d953149fa1e7.png)

**Comment by btlechowski** [comment]
Still reproducible

Brave | 1.68.137 Chromium: 127.0.6533.100 (Official Build) (64-bit)
-- | --
Revision | 2c62ca4f207eb8f02406936d1e5a4b226ddcfd3a
OS | Linux



![image](https://github.com/user-attachments/assets/b3826f75-49ab-41df-85fc-3074a7b150df)

**Comment by rebron** [comment]
cc: @zenparsing @mkarolin

**Comment by mkarolin** [comment]
Updated translations in Transifex. Will pull it in with the 1.69.x release.

**Comment by kjozwiak** [comment]
The above requires `1.69.149` or higher for `1.69.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.149 Chromium: 128.0.6613.40 (Official Build) (x86_64)
-- | --
Revision | a6a137ec4f7f0b30e1d3940dbfcde72c32d35baa
OS | macOS Version 13.6.9 (Build 22G830)
```
