### ISSUE TITLE
Brave crashes my pc

### ISSUE THREAD

**Issue by Ranarrr** [brave/brave-browser#12042]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: **1.17.19**  Chromium: **86.0.4240.75**
Operating System: **Windows NT 10.0.19041**

**Can you reproduce this crash?**
No

**What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)**

Kind of many processes open in brave (many windows, but gathered), was scanning PC with Hitmanpro, while using bluestacks app, and that's when it froze.

This report was generated from the crash, and this is a similar crash report to #11940 where it crashed my PC in the same way, everything freezes, I can still move my mouse around (after a while it started lagging the cursor and then stopped completely).
Turning my monitors off and on reveals that one screen is not receiving input (primary screen).
No minidump generated by windows, as it doesn't actually get to the "We ran into a problem" BSOD screen.
I waited probably up to 2 hours before actually restarting my PC when this happened. I was hoping it would go to BSOD screen and gather info, but never did..

The reason I suspect it is Brave is because of the similar crash happening before, but then I was fullscreening/exiting many times on Youtube. Again #11940 was the previous.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/3a250000-b40e-3405-0000-000000000000

**Comment by rebron** [comment]
@Ranarrr Are you still experiencing a crash. Can you update to 1.17.73 and let us know? Were you on Beta channel?

**Comment by rebron** [comment]
cc: @iefremov Can you take a look at this crashid when you get a chance?

**Comment by iefremov** [comment]
@rebron Unfortunately the report is too old, we store crash dumps only for 30 days. Sorry :(

**Comment by Ranarrr** [comment]
I was not on beta, if I understood correctly.. Haven't gotten any crash like it since, I didn't see any response for a while so I forgot about this thread. 
I'm now on Version 1.19.43 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit), and haven't experienced any crashes like the one described here, which is good. I will definitely upload crashlog + make a thread here on github if some similar crash happens again, and reference this issue in the new thread.

**Comment by iefremov** [comment]
Thanks @Ranarrr , don't hesitate to ping us if something like that happens again
