### ISSUE TITLE
Can't modify top sites settings on new tab page

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#12041]
## Description 

Going to `Customize` on new tab page and clicking `Show Top Sites` or `Customize Top Sites` doesn't do anything ☹️ 
![image](https://user-images.githubusercontent.com/4733304/95398138-e2160d00-08b9-11eb-8deb-31bdfa6fdff3.png)

## Steps to Reproduce

   1. Open new tab
   2. Click `Customize` in bottom right
   3. Pick `Top Sites` in sidebar
   4. Try to toggle either `Show Top Sites` or `Customize Top Sites` 

## Actual result:
Nothing happens 😢 

## Expected result:
Clicking the toggles should actually toggle the settings 😄 

## Reproduces how often: 
100%

## Brave version (brave://version info)
Nightly (Version 1.17.19)

**Comment by bsclifton** [comment]
NOTE: works fine on new profile; just seems to be an issue with my existing profile. Need to understand why

**Comment by petemill** [comment]
The `InstantService` won't enable "most visited" when _Google_ is not the default search engine. I think that's the issue.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.17.40 Chromium: 86.0.4240.99 (Official Build) nightly (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Windows 10 OS Version 1903 (Build 18362.1082)

```
- Verified the STR from the description
- Verified on both clean and upgraded profile
- Verified clicking on toggle `Show Top Sites` or `Customize Top Sites` toggles the settings
![image](https://user-images.githubusercontent.com/38657976/96491481-ee0db180-125f-11eb-925f-d205689fa654.png)
