### ISSUE TITLE
[Desktop] Improve display of custom background images in tip dialog

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#12057]
## Description 

The new rewards tipping dialog uses a different aspect ratio for custom banner images, and when existing banner images are displayed within the new tip dialog, they are cropped and scaled to cover the available space. We should try to scale images with wide aspect ratios more gracefully.

Also, when custom backgrounds have a light color it can become difficult to read the white banner text.

**Comment by zenparsing** [comment]
After speaking with @codybanxs it was decided to leave the scaling as-is for now and add a missing linear gradient background to custom banner images to improve readability.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/6930

1.17.73:
<img width="1137" alt="1 17 x" src="https://user-images.githubusercontent.com/28145373/99845932-70c9ab00-2b43-11eb-8f01-33b6707cb644.png">

1.18.59:
<img width="1188" alt="1 18 x" src="https://user-images.githubusercontent.com/28145373/99845936-72936e80-2b43-11eb-9eeb-ee9e6a2024dc.png">

-------------
