### ISSUE TITLE
Can't see full screen videos on YouTube.

### ISSUE THREAD

**Issue by vokomod** [brave/brave-browser#12055]
## Description 
LENOVO t440p i5-4300U
Can't watch any video on youtube in full screen mode.

## Steps to Reproduce
1. Go to any video on youtube
2. Press "f" to full screen mode

## Actual result:
No full screen video( 
## Expected result:
Full screen video!

## Reproduces how often: 
Each video from 9pm Oct 8th, 2020

## Brave version (brave://version info)
Brave	1.15.72 Chromium: 86.0.4240.75 (Официальная сборка) (64 бит)
Версия	c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
ОС	Linux
JavaScript	V8 8.6.395.10
Flash	(отключено)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? <--No
- Does the issue resolve itself when disabling Brave Rewards? <-- No
- Is the issue reproducible on the latest version of Chrome? <--Don't know

**Comment by bsclifton** [comment]
@vokomod can you please try to disable hardware acceleration? I'm curious if that makes a difference. You can find/toggle it at brave://settings/system

**Comment by vokomod** [comment]
> @vokomod can you please try to disable hardware acceleration? I'm curious if that makes a difference. You can find/toggle it at brave://settings/system

It helped me, thanks a lot, Brian!

**Comment by vokomod** [comment]
If you can't watch youtube videos in full screen mode, try to disable hardware acceleration at brave://settings/system.
