### ISSUE TITLE
Make clock options display better with dark theme

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12061]
## Description 

Follow up from https://github.com/brave/brave-browser/issues/9038

When you open the Clock section on Customize Dashboard using dark theme, the text in the drop down (before expanding) is difficult to read. It might be better if this text was white instead of a medium gray color to offer better contrast.

Note, once you expand the drop down it's light (doesn't match the dark theme) so it's easier to read. Logged theme mismatch with https://github.com/brave/brave-browser/issues/12060

## Steps to Reproduce

   1. Be using dark theme
   2. On NTP open Customize Dashboard settings
   3. Click on Clock

## Actual result:

text on drop down (before expanding) is a bit dark IMO
<img width="1194" alt="Automatic" src="https://user-images.githubusercontent.com/28145373/95581479-1cd98b80-0a07-11eb-8736-464ffa3c1c5f.png">

## Expected result:
tweak text on drop down so it offers better contrast for easier reading

## Brave version (brave://version info)

Brave | 1.16.57 Chromium: 86.0.4240.75 (Official Build) dev (x86_64)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes, 1.16.x
- Can you reproduce this issue with the nightly channel? yes, 1.17.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @bsclifton @rebron

**Comment by LaurenWags** [comment]
This might be fixed if https://github.com/brave/brave-browser/issues/12060 is addressed, not sure so logged separately.

**Comment by rebron** [comment]
I'm seeing these as white on on 1.17.73, not medium gray.
![Screen Shot 2020-11-23 at 10 08 58 AM](https://user-images.githubusercontent.com/5951041/99998755-00ee3700-2d74-11eb-8545-97f384caa9a0.png)

**Comment by rebron** [comment]
screenshot above is darker than actual for some reason but it's the same color across all the different labels.

**Comment by mayralgr** [comment]
@rebron is this issue good to take? This issue is independent to #12060

**Comment by LaurenWags** [comment]
@rebron just to clarify, I meant the wording inside the Format box that says `Automatic (en-US)`, that seems dark to me and a little difficult to read. 

<img width="746" alt="Screen Shot 2020-12-08 at 9 51 00 AM" src="https://user-images.githubusercontent.com/28145373/101499303-1ac67700-393b-11eb-9a30-28b2661b9f38.png">

**Comment by bsclifton** [comment]
@mayralgr absolutely - all yours 😄 Let us know if you need any help

**Comment by mayralgr** [comment]
I had some trouble running the project locally, if I solve it I'll get back to it. For now I left it open in case anyone wants to work on it.

**Comment by BrennenC** [comment]
I was wondering if anyone was actively working on this issue. If not, could I be assigned to it? It would be my first issue here.

**Comment by mayralgr** [comment]
@BrennenC I don't think anyone is working in this issue, I will suggest you to install the project and make a pr

**Comment by faraz16iqbal** [comment]
Hey is this issue still open?

**Comment by bsclifton** [comment]
Hi folks - yup; issue is open, feel free to grab it 😄 Once you get past the local setup, it shouldn't be too hard

**Comment by imashish1705** [comment]
hey, this issue still open? 
I want to contribute

**Comment by Warkanlock** [comment]
Setting up the local env, if everything goes well I'll work on this! :D

**Comment by imashish1705** [comment]
Cloning into 'brave-browser'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exist
This message show so can you help me! how i fix this error

**Comment by Warkanlock** [comment]
I spot the issue but it's not related with brave-browser ui, in order to fixed here we would have to use some hacky thing, although it's related with brave-ui component (**Select** one precisely) so would be nice to modify this from the source library

Should I make a PR to **brave-ui** instead? @bsclifton

**Comment by Warkanlock** [comment]
I created a PR on **brave-ui**, which contains this change, just in case do we want to proceed with this. Otherwise would be ok to abandon and solve on **brave-browser** instead (which I don't recommend because the Select on **brave-browser** depends 100% within the library)

**Comment by Warkanlock** [comment]
I'm about to make a PR to use theme selection as reference for style the component. Works so far.

**Comment by Warkanlock** [comment]
Just in case I left here the PR associated with this issue on **brave-core**

https://github.com/brave/brave-core/pull/8172

**Comment by Warkanlock** [comment]
Did anyone review the PR yet? @LaurenWags @bsclifton

**Comment by Warkanlock** [comment]
No worries :100:

**Comment by coder-abdo** [comment]
is this issue still open?

**Comment by KSSaiTeja** [comment]
i am interested to contribute this, please assign me this

**Comment by Rakshit358** [comment]
Is this still open? Would like to contribute to it.

**Comment by BearerOP** [comment]
Is this issue still open to contribute ? Willing to contribute to it.

**Comment by rebron** [comment]
![Image](https://github.com/brave/brave-browser/assets/5951041/346d2393-4ee4-41c4-9938-51449f2eb0d6)

Closing. Fixed with a Nala update.
