### ISSUE TITLE
[Desktop] update brave://settings/newTab to include clock options

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12062]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/9038

NTP settings found in the Customize Dashboard popup are generally found under brave://settings/newTab as well. The new clock options should be added as well for consistency.

## Steps to Reproduce

   1. Navigate to brave://settings/newTab

## Actual result:

No dropdown for clock options
<img width="1196" alt="Screen Shot 2020-10-09 at 7 44 44 AM" src="https://user-images.githubusercontent.com/28145373/95582234-6080c500-0a08-11eb-87fb-ce01c685bc42.png">

## Expected result:
clock options available on Customize Dashboard should be available here as well
when an option is selected on brave://settings/newTab it should be reflected on NTP
when an option is selected on the Customize Dashboard modal it should be reflected in brave://settings/newTab

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.16.57 Chromium: 86.0.4240.75 (Official Build) dev (x86_64)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes, 1.16.x
- Can you reproduce this issue with the nightly channel? yes, 1.17.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @bsclifton @rebron

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows `10 x64 - 1.16.58`

**Comment by ryanml** [comment]
With the recent removal of granular NTP widget settings from `brave://settings`, we'll go ahead and close this one
