### ISSUE TITLE
[Desktop] optimize Clock drop down on Customize Dashboard settings for dark theme 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12060]
## Description 

Follow up from https://github.com/brave/brave-browser/issues/9038

When you're using dark theme/mode, the Clock dropdown is still light. Would be nice to have this match the rest of the dark theme.

## Steps to Reproduce

   1. Be in dark mode.
   2. On NTP, open Customize Dashboard settings
   3. Click on Clock
   4. Expand drop down on right side

## Actual result:

<img width="747" alt="Screen Shot 2020-10-09 at 7 43 08 AM" src="https://user-images.githubusercontent.com/28145373/95579937-77251d00-0a04-11eb-805e-38af88f66224.png">

## Expected result:
Would be nice if the drop down was also dark.

## Brave version (brave://version info)

Brave | 1.16.57 Chromium: 86.0.4240.75 (Official Build) dev (x86_64)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? not available
- Can you reproduce this issue with the beta channel? yes, 1.16.x
- Can you reproduce this issue with the nightly channel? yes, 1.17.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @bsclifton @rebron @kjozwiak

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.16.58`

![image](https://user-images.githubusercontent.com/38657976/95762321-2eeb5080-0ccb-11eb-8b1e-8b84988eb772.png)

**Comment by InokrayLeinad** [comment]
Hey guys :)
Looking for my first contribution ever and this one seems quite easy, I would love to dive in and help float the boat :)

**Comment by LaurenWags** [comment]
going to cc @karenkliu as there might be a design standard to use for this drop down.

**Comment by karenkliu** [comment]
Please use the dropdown component (comes with light/dark theme): https://www.figma.com/file/z9wmg2FCwuXx9FLbDo5avJ/Platform-UI-Brave-desktop?node-id=135%3A345

**Comment by aswathkk** [comment]
@karenkliu The Figma link that you shared is not accessible by me. Could you make it public?

**Comment by karenkliu** [comment]
@aswathkk Our designs in Figma is accessible to all Brave developers.

**Comment by anish-khanna** [comment]
If this is still open for community help, I'd like to help out. I'm also unsure of how exactly to get on the brave developer list so as to access the figma link if so.

**Comment by ForkInSpace** [comment]
@LaurenWags I'd be happy to jump in and help out if this is still relevant. 

I second that the designs aren't accessible or have been deleted -> 
<img width="477" alt="image" src="https://user-images.githubusercontent.com/11965778/193925291-63ed19a8-1097-414e-835e-937de4876037.png">

Any pointers as to how to access the designs?

**Comment by LaurenWags** [comment]
Hey @ForkInSpace - cc'ing @rebron or @bsclifton on this one for further guidance

**Comment by om-ray** [comment]
@LaurenWags I see this still hasn't been fixed, I'm new to the brave community and would like to start off by fixing this.

**Comment by bsclifton** [comment]
@om-ray sure - go for it 😄 The designs basically look like this:
![image](https://user-images.githubusercontent.com/4733304/222338470-9626413c-5b2c-4d5d-9edf-9ee0529a69e3.png)

If you dig around, you should be able to find light/dark styles. If not, maybe we can port this to Leo. @fallaciousreasoning may be able to help with that when you're ready 😄

**Comment by om-ray** [comment]
Great, I'll get started then!

**Comment by fallaciousreasoning** [comment]
I'm assigning this to @om-ray for now - just so we don't get into a situation where multiple people are working on it.

**Comment by om-ray** [comment]
@fallaciousreasoning Thank you! Sorry for the slow progress, I'm still figuring out the codebase.

**Comment by om-ray** [comment]
@fallaciousreasoning Whenever I try building with `npm run build -- Static` I get this error message:
```
> brave@1.51.0 build
> cd src/brave && npm run build -- Static


> brave-core@1.51.6 build
> node ./build/commands/scripts/commands.js build Static

internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/omray/Desktop/Brave/brave-browser/src/chrome/VERSION'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at checkVersionsMatch (/Users/omray/Desktop/Brave/brave-browser/src/brave/build/commands/lib/build.js:11:26)
    at Command.build (/Users/omray/Desktop/Brave/brave-browser/src/brave/build/commands/lib/build.js:24:3)
    at Command.listener (/Users/omray/Desktop/Brave/brave-browser/src/brave/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:400:28)
    at Command.parseArgs (/Users/omray/Desktop/Brave/brave-browser/src/brave/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/omray/Desktop/Brave/brave-browser/src/brave/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/omray/Desktop/Brave/brave-browser/src/brave/build/commands/scripts/commands.js:320:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/omray/Desktop/Brave/brave-browser/src/chrome/VERSION'
}
```

I'm not sure how to fix this, any help would be appreciated!

**Comment by fallaciousreasoning** [comment]
@om-ray have you run `npm run sync`? Also, if you just run `npm run build` (without static) it should do a component build, which should be a bit faster.

**Comment by fallaciousreasoning** [comment]
This should be fixed by https://github.com/brave/brave-core/pull/19401
