### ISSUE TITLE
add home button to access bookmarks

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#12077]
## Description 
in the home page can you add a button to go to bookmarks?
I frequently use bookmarks and opening the menu e then choosing the bookmarks option is annoying, mainly because the menu button is at the top of the screen, while my fingers are usually at the bottom.
the new button should also remember the last folder in the bookmarks, and reopen automatically in that folder.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
You can add the following as your custom home page. 
- `chrome-native://bookmarks/folder/1` - Opens bookmarks (with sync enabled) 
- `chrome-native://bookmarks/folder/2` - Opens other bookmarks
- `chrome-native://bookmarks/folder/3` - Opens mobile bookmarks

**Comment by tortino** [comment]
ok, thanks for the solution using custom home page. I'll try it.
