### ISSUE TITLE
On a private window, the "paste and search" function completely ignores the "search with ddg" option at the bottom and it just uses google

### ISSUE THREAD

**Issue by pitsi** [brave/brave-browser#12070]
## Description 
Please see this reddit thread for a simple animation.
https://old.reddit.com/r/brave_browser/comments/j82udg/using_paste_and_search_in_incognitomode_with/
I can fully reproduce the issue on my system, so I opened this report.

## Steps to Reproduce
   1. Select and copy a word or phrase from anywhere, NOT a url.
   2. Open a private window (ctrl+shift+n or menu > new private window).
   3. Enable the "search with duckduckgo" option at the bottom.
4. Right click on the address bar and select "paste and search".
5. Notice that the search is done in google and not in ddg.

## Actual result:
The search is done through google.

## Expected result:
The search should be done through ddg.

## Reproduces how often: 
Easily and everytime.

## Brave version (brave://version info)
Brave	1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)
Revision	c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{# 1149}
OS	Linux

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Probably
- Can you reproduce this issue with the nightly channel? Probably

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not applicable in chrome due to missing functionality.

## Miscellaneous Information:
I use google as my default search engine, in case it has something to do with it.
---edit
It seems there is a connection between the described behavior and the default search engine. Changing my default search engine to yahoo, bing or even startpage made the forementioned search through the one that was set as default.

**Comment by srirambv** [comment]
Seems like a regression of https://github.com/brave/brave-browser/issues/1037

**Comment by bsclifton** [comment]
cc: @simonhong

**Comment by pitsi** [comment]
Am I the only one that has the forementioned issue with the missing switch? I just checked with 1.31.88 and it is still missing.
If it is not fixed in the following releases, I will close this bug report because it simply no longer applies to the new versions of brave.

**Comment by pitsi** [comment]
1.32 was released earlier so I am closing this because it no longer applies (since 1.31).
If anyone knows a way to get the "search with ddg" toggle back, please post.
