### ISSUE TITLE
Stats retained on Tor windows

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1207]
## Description 

Stats retained on Tor windows

## Steps to Reproduce

   1. Open a Tor Window from profile 
   2. Visit few sites to add stats count
   3. Close the Tor window and relaunch a new one, stats from previous session is retained

## Actual result:

Stats retained on Tor windows

## Expected result:
Should not retain stats as Tor window is using guest profile which should lose all data after the window is closed

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows

### Reproducible on current release:

No as muon doesn't have a guest profile window 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bridiver @darkdh. Please move milestone if required

**Comment by rebron** [comment]
Closing, expected behavior
