### ISSUE TITLE
How to export .graphml file for a web page to generate page-graph 

### ISSUE THREAD

**Issue by arup008** [brave/brave-browser#12071]
I have followed this [link](https://github.com/brave/brave-browser/wiki/PageGraph) and built brave browser in the page-graph branch. But I could not find a way to export a web page as .graphml file to generate page-graph.

I have also found a community link where a person mentioned that he exported .graphhml file following the below procedure.
Right-click on the webpage => Inspect => Developer console window => Under element menu there is a [sub-menu page graph](https://drive.google.com/file/d/17lFn6aqho7b4xMy0uFZu2wj49zDvThzO/view?usp=sharing) => In page Graph sub menu there is button “Save full page graph” which exports a .graphml file.
But unfortunately, I don’t see any [sub-menu](https://drive.google.com/file/d/19VICetoZTfOr09E226vRcsmOlLpVED2F/view?usp=sharing) named page-graph under the element menu. Are there some settings that need to set to show the page-graph option? or the option is moved to another segment? 
I have noticed another thing when I go to inspect element and refresh a webpage, the contents of .graphml is shown in console log like this [picture.](https://drive.google.com/file/d/1geGQFo8VuZZjNxpNWbS3LdJOHCX5U-rG/view?usp=sharing)

## Brave version
Version 1.12.48 Chromium: 83.0.4103.116 (Developer Build) (64-bit)

## Other Additional Information:
My current branch is “page-graph”
Last commit of page-graph branch is:
9b948cad7ba1ee224c4e8843ab7c72d68891a14b --> Set brave-core to track page-graph branch
Last commit of chromium src:
faf34a95a93ff46eb36000dab45cf66e58048b0f --> Publish DEPS for 83.0.4103.116

Can anyone help me where I can find the page-graph option and then export a webpage as .graphml file?

**Comment by pes10k** [comment]
Thanks again for the issue @arup008 . I've followed up to your question in community and on the wiki.  I'm going to close this now, but please let me know in community if there are any further questions.  Thanks!

**Comment by pes10k** [comment]
https://community.brave.com/t/how-to-export-graphml-file-for-a-web-page-to-generate-page-graph/169563

**Comment by arup008** [comment]
Thanks for your reply.
But in pagegraph-crawl I am facing another problem. What I did is mentioned
below.
1) cloned  pagegraph-crawl
2) npm install
3) cd built
4)  ./run.js -b
/media/arup/Study_and_Others/Brave/brave-browser/src/out/Static/brave
-o /media/arup/Study_and_Others/Brave -u https://www.google.com/

running this command shows an error:
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory,
stat
'/media/arup/Study_and_Others/Brave/pagegraph-crawl/built/resources/shields-down-profile'

Did I do anything wrong? If not how can I solve this?

**Comment by pes10k** [comment]
Howdy @arup008 , it looks like you're just running from the `built` dir instead of the project root.  if you just run `./built/run.js -b
/media/arup/Study_and_Others/Brave/brave-browser/src/out/Static/brave
-o /media/arup/Study_and_Others/Brave -u https://www.google.com/`

this should work out.

However, i believe @antonok-edm also has suggestions / changes coming that might be needed if you're not on Mac (I build the profiles in there with Mac, and @antonok-edm has identified issues using a Mac profile on Linux)

**Comment by antonok-edm** [comment]
@arup008 I'd recommend manually setting up your own profile directories for any browser configurations you need, and pointing `pagegraph-crawl` to those - in particular, we've discovered that the profile directory itself doesn't appear to be fully cross-platform portable and may cause browser crashes on the wrong OS. This way you might also get to customize the profiles a bit better to your requirements.

We've been generating the profiles by passing a nonexistent `--profile-directory` argument to `brave`, tweaking `brave://settings` as necessary, and then exiting.

**Comment by arup008** [comment]
Thanks for your reply. It worked 😄
