### ISSUE TITLE
weird things going on on the screen. 

### ISSUE THREAD

**Issue by nithinkodadhavadee** [brave/brave-browser#12086]
## Description 

Every time I put my system to sleep without closing the brave window this happens
![Screenshot from 2020-09-17 14-27-48](https://user-images.githubusercontent.com/50230678/95720669-2a08ab80-0c8f-11eb-92a0-31f4c3161958.png)

when scrolled down
![Screenshot from 2020-09-17 14-27-56](https://user-images.githubusercontent.com/50230678/95720687-2ecd5f80-0c8f-11eb-9921-8f1c7f6e752f.png)

when scrolled back up
![Screenshot from 2020-09-17 14-28-00](https://user-images.githubusercontent.com/50230678/95720693-30972300-0c8f-11eb-9a88-5dd52883febb.png)

## Steps to Reproduce

   1. Don't close the tabs.
   2. put the laptop on sleep
   3. login back again

## Reproduces how often: 

Every time I put my laptop to sleep, and this is the case for a very long time.

## Brave version (brave://version info)

Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)
installed on Ubuntu 20.04 LTS

## Version/Channel Information:

I haven't seen this on the other devices

**Comment by TomAFrench** [comment]
I'm experiencing the same on Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit) with Ubuntu 18.04LTS

**Comment by rebron** [comment]
@TomAFrench @nithinkodadhavadee Are you guys using SNAP builds? Also, for your Fingerprinting settings are they set to Standard or do you have them set as strict? The setting to strict might cause what you're seeing.

**Comment by Marsevil** [comment]
Same on version 1.16.67 Chromium: 86.0.4240.111 (Build officiel) (64-bit) with Manjaro.

**Comment by nithinkodadhavadee** [comment]
@rebron I have no idea what you want so I googled it and figured this might be what you asked for, I'm not entirely sure though.

I just followed the installation guide on the [website](https://brave.com/linux/#debian-9-ubuntu-1404-and-mint-17), so I don't know if they were snap builds or not

I don't know if this is what you want regarding fingerprinting but as far as I know, it's set to standard 
![image](https://user-images.githubusercontent.com/50230678/98213012-77182e80-1f6a-11eb-80d6-7057b6e49432.png)

**Comment by TomAFrench** [comment]
I'm also on the standard fingerprint blocking setting. No snap builds.

**Comment by bsclifton** [comment]
Guessing this is a problem with hardware acceleration. I'd try giving that a toggle under brave://settings/system

**Comment by nithinkodadhavadee** [comment]
hardware acceleration is switched on.

**Comment by bsclifton** [comment]
@nithinkodadhavadee try turning that to off - let us know if that fixes the issue. It seems to be a major problem for Linux users in general (with Chromium and Brave)

**Comment by Marsevil** [comment]
@bsclifton It works for me thanks

**Comment by nithinkodadhavadee** [comment]
@bsclifton Yes it did work, thank you. last and final thing, I'm pretty new to GitHub so am I supposed to close this issue now or just let it be and you guys will look into it?

**Comment by bsclifton** [comment]
@nithinkodadhavadee lets keep it open; there's definitely an underlying problem that we need to detect and take action on. Can you share the info from brave://gpu (just hit the `Copy to clipboard`)

**Comment by LazyyCoder** [comment]
> @nithinkodadhavadee lets keep it open; there's definitely an underlying problem that we need to detect and take action on. Can you share the info from brave://gpu (just hit the `Copy to clipboard`)


Data exported | 2020-11-18T03:38:34.482Z
-- | --
Chrome version | Chrome/86.0.4240.198
Operating system | Linux 5.4.0-54-generic
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/d8a506935fc2273cfbac5e5b629d74917d9119c7/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/d8a506935fc2273cfbac5e5b629d74917d9119c7/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | fee4fc126724
2D graphics backend | Skia/86 b939c288f3d6479d88d1444fafbe7441d11348aa
Command Line | /opt/brave.com/brave/brave --disable-domain-reliability --disable-features=PrivacySettingsRedesign,VideoPlaybackQuality,NotificationTriggers,AutofillServerCommunication,PasswordCheck,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,SafeBrowsingEnhancedProtection,SmsReceiver,TabHoverCards --enable-dom-distiller --enable-features=OmniboxContextMenuShowFullUrls,DnsOverHttps,LegacyTLSEnforced,MixedContentSiteSetting,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --extension-content-verification=enforce_strict --extensions-install-verification=enforce --lso-url=https://no-thanks.invalid --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,WebUIDarkMode,PassiveMixedContentWarning,AutoupgradeMixedContent,OmniboxContextMenuShowFullUrls,DnsOverHttps,LegacyTLSEnforced,MixedContentSiteSetting --disable-features=TabHoverCards,SmsReceiver,SafeBrowsingEnhancedProtection,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,TextFragmentAnchor,PasswordCheck,AutofillServerCommunication,NotificationTriggers,VideoPlaybackQuality,PrivacySettingsRedesign --flag-switches-begin --enable-accelerated-video-decode --flag-switches-end

Hope this will help you, Log taken after disabling Hardware acceleration

**Comment by ryanbr** [comment]
@LazyyCoder  which GPU do you have? does switching from the open source drivers to official binaries (or vice-versa) help?

I

**Comment by nithinkodadhavadee** [comment]
@bsclifton this was the report I found
Data exported | 2020-11-19T03:29:35.905Z
-- | --
Chrome version | Chrome/86.0.4240.193
Operating system | Linux 5.4.0-53-generic
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/4b1dc838fc8d2b55f2147e7a642b20baf443da5c/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/4b1dc838fc8d2b55f2147e7a642b20baf443da5c/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | fee4fc126724
2D graphics backend | Skia/86 b939c288f3d6479d88d1444fafbe7441d11348aa
Command Line | /opt/brave.com/brave/brave --disable-domain-reliability --disable-features=PrivacySettingsRedesign,VideoPlaybackQuality,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,SmsReceiver,TabHoverCards,NotificationTriggers,AutofillServerCommunication,PasswordCheck,SafeBrowsingEnhancedProtection --enable-dom-distiller --enable-features=MixedContentSiteSetting,PrefetchPrivacyChanges,AutoupgradeMixedContent,PassiveMixedContentWarning,DnsOverHttps,LegacyTLSEnforced,OmniboxContextMenuShowFullUrls,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity --extension-content-verification=enforce_strict --extensions-install-verification=enforce --lso-url=https://no-thanks.invalid --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=ReducedReferrerGranularity,PasswordImport,WebUIDarkMode,PassiveMixedContentWarning,AutoupgradeMixedContent,PrefetchPrivacyChanges,OmniboxContextMenuShowFullUrls,LegacyTLSEnforced,DnsOverHttps,MixedContentSiteSetting --disable-features=SafeBrowsingEnhancedProtection,PasswordCheck,AutofillServerCommunication,NotificationTriggers,TabHoverCards,SmsReceiver,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,VideoPlaybackQuality,TextFragmentAnchor,PrivacySettingsRedesign --flag-switches-begin --flag-switches-end

and I also found this

# Driver Bug Workarounds
adjust_src_dst_region_for_blitframebuffer
clear_uniforms_before_first_program_use
decode_encode_srgb_for_generatemipmap
exit_on_context_lost
msaa_is_slow
scalarize_vec_and_mat_constructor_args
disabled_extension_GL_KHR_blend_equation_advanced
disabled_extension_GL_KHR_blend_equation_advanced_coherent
# Problems Detected
Protected video decoding with swap chain is for certain Intel and AMD GPUs on Windows: 1093625
Disabled Features: protected_video_decode
Clear uniforms before first program use on all platforms: 124764, 349137
Applied Workarounds: clear_uniforms_before_first_program_use
Always rewrite vec/mat constructors to be consistent: 398694
Applied Workarounds: scalarize_vec_and_mat_constructor_args
On Intel GPUs MSAA performance is not acceptable for GPU rasterization: 527565
Applied Workarounds: msaa_is_slow
adjust src/dst region if blitting pixels outside framebuffer on Linux Intel: 664740
Applied Workarounds: adjust_src_dst_region_for_blitframebuffer
Disable KHR_blend_equation_advanced until cc shaders are updated: 661715
Applied Workarounds: disable(GL_KHR_blend_equation_advanced), disable(GL_KHR_blend_equation_advanced_coherent)
Decode and Encode before generateMipmap for srgb format textures on Linux Mesa ANGLE path: 634519
Applied Workarounds: decode_encode_srgb_for_generatemipmap
Some drivers can't recover after OUT_OF_MEM and context lost: 893177
Applied Workarounds: exit_on_context_lost
Accelerated video decode has been disabled, either via blocklist, about:flags or the command line.
Disabled Features: video_decode

@ryanbr I guess I have a GTX 1050 I'm not sure.

**Comment by nithinkodadhavadee** [comment]
> @nithinkodadhavadee try turning that to off - let us know if that fixes the issue. It seems to be a major problem for Linux users in general (with Chromium and Brave)

@bsclifton turning off hardware acceleration solves the issue on youtube, but it causes the same issue on other sites. so I turned it back on, as of now there are no issues on youtube yet. I'll let you know if something else happens again.

**Comment by pes10k** [comment]
@nithinkodadhavadee just wanted to check, are you still seeing this? If not, i'll close out the issue.  Thanks!

**Comment by LazyyCoder** [comment]
> @nithinkodadhavadee just wanted to check, are you still seeing this? If not, i'll close out the issue.  Thanks!

It's fixed for me in Ubuntu 20.04

**Comment by TomAFrench** [comment]
Just wanted to chime in to say that I haven't experienced this in probably months at this point.

**Comment by pes10k** [comment]
Okie dokie then, im going to close it then, but can reopen if it comes back up for anyone.  Thanks all!
