### ISSUE TITLE
Browser Crash and scroll issue

### ISSUE THREAD

**Issue by nithinkodadhavadee** [brave/brave-browser#12081]
## Description 

The browser has started to crash a lot recently. Most noticed when using GitHub. Whenever I try changing directories from the link in this portion, brave crashes.
![current directory location](https://user-images.githubusercontent.com/50230678/95688687-8b962f00-0c29-11eb-81bd-7d2fcb76bf7b.png)
This thing is still crashing no matter which repo I am on.

After the browser crashes, I open it again and restore all the tabs I get this "Skip to Content" icon on the top left corner.
![icon](https://user-images.githubusercontent.com/50230678/95688722-cbf5ad00-0c29-11eb-9bce-75c0ca3b2287.png)
clicking that icon doesn't seem like it does anything.

It's not just that, I can't scroll through the pages using the arrow keys. Arrow keys act like the tab key, but worse. It goes through every element in the page. If I leave the page untouched, without touching the mouse or my laptop, the pages start scrolling by itself sometimes( again mostly noticed on Github pages, even on Youtube and Wikipedia). 
Sometimes if I try scrolling trough the scroller on the mouse, the page just crawls bake up no matter how much ever I try. Using the scroll bar fixes these issues but a refresh button or changing to a different tab gets this back again. 

And it is not even an old issue. I got this issue today morning, got fed up with this so much that I'm reporting this now. It's just today, and the browser has crashed like more than twenty times and I've seen the scrolling issue on almost every link I've opened.

## Expected result:
Not to crash and act normal.

## Brave version (brave://version info)

V1.15.72 installed on Ubuntu 20.04 LTS

## Version/Channel Information:

I have Brave installed on a Windows and an Android device and I haven't noticed this there

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Have no Idea
- Does the issue resolve itself when disabling Brave Rewards? 
Nope, tried and didn't work

**Comment by ryanbr** [comment]
Hey @nithinkodadhavadee  does opening in a new Brave profile help with this?

**Comment by nithinkodadhavadee** [comment]
I don't know what profiles are, I searched it and I was supposed to find it here 
![image](https://user-images.githubusercontent.com/50230678/96294277-bdccd580-1009-11eb-9731-68a3359b0477.png)
as mentioned in a [community post](https://community.brave.com/t/is-there-a-way-to-create-profiles-just-like-firefox-which-helps-to-maintain-more-privacy/42044) but couldn't find it

**Comment by rebron** [comment]
@nithinkodadhavadee Is this still happening for you with the latest 1.19.86? Also for creating a profile, in the application menu, there's an item that says 'Create a New Profile' and select that.

**Comment by nithinkodadhavadee** [comment]
@rebron, no the crashing stopped since I tried resolving the issue #12086, plus I recently tried doing something and ended up not able to boot the os, I also had no backups so I had to reinstall everything. So the crash report is currently empty. I haven't been facing the crash issue since I tried issue #12086. Plus the crash reporting is disabled, I taught it would be on by default so I should switch it on now. 

and I did figure out the creation of profile as soon as @ryanbr mentioned about it, I googled it and I don't know if it is because of creating more profiles or toggling off and on the hardware acceleration, the crashing has stopped since.

**Comment by rebron** [comment]
@nithinkodadhavadee Based on your last comment, I'm going to ahead and close this out. If you encounter this same issue again, we can go ahead and reopen this one or ok to file a new one. Thanks for toggling crash reports too, that will help if it happens again next time.
