### ISSUE TITLE
How can I disable HTTPS Everywhere?

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#12087]
## Description 
If you deactivate HTTPS EveryWhere in the settings, HTPPS Everywhere still appears under the components and in the task manager.

## Steps to Reproduce

   1. disable HTTPS Everywhre in the settings 
   2. 
   3. 

## Actual result:
HTPPS Everywhere still appears under the components and in the task manager.

## Expected result:
HTPPS Everywhere should not appear under the components and in the task manager.

## Reproduces how often: 
always

## Brave version (brave://version info)
Brave	1.15.72 Chromium: 86.0.4240.75 (Offizieller Build) (32-Bit)
Überarbeitung	c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
Betriebssystem	Windows 10 OS Version 1909 (Build 18363.592)

![components](https://user-images.githubusercontent.com/53431361/95728350-b5784180-0c7b-11eb-95ca-40c5ac8dbe9f.png)
![taskmanager](https://user-images.githubusercontent.com/53431361/95728416-c88b1180-0c7b-11eb-81a9-e45efee46f75.png)

**Comment by ACodingGenie** [comment]
Unless I'm misunderstanding something here, if you turn HTTPS everywhere off in settings then it's OFF. Just make sure this setting is toggled off and you should be good.
![image](https://user-images.githubusercontent.com/68975831/95748750-7ee4fb80-0c68-11eb-832d-88762a31d15c.png)

The component part has nothing to do with if its on or off. Brave shields tells you that like so:
![image](https://user-images.githubusercontent.com/68975831/95748800-96bc7f80-0c68-11eb-954c-721e65a4fb8a.png)

As long as its off in settings and Brave's shields tells you its off then its off. Components are a completely separate entity.
I'm not sure what you mean by HTTPS everywhere appears...
> in the task manager.
as I can't read that language and I don't think it displays in the Brave Task Manager regardless.
Cheers.

**Comment by Johann999** [comment]
You misunderstood something.
I don't want to change the shield settings
I want to remove HTTPS Everywhere from Brave.

**Comment by Johann999** [comment]
For me personally, the HTTPS Everywhere extension is of no use.
A few years ago this extension (maybe) made sense.
Nowadays I find HTTPS Everywhere redundant.

**Comment by ACodingGenie** [comment]
>I want to remove HTTPS Everywhere from Brave.

I see. I am not sure if this is possible without compiling your own modified source code of Brave without HTTPS everywhere. 

>For me personally, the HTTPS Everywhere extension is of no use.
I find HTTPS Everywhere redundant.

But, going back to the point I made earlier, if you just want it off (which is essentially what it seems like), then turning it off globally from Brave's settings does just that. 
Perhaps a developer can chime in and shed more light on this issue.

**Comment by dodieboy** [comment]
What is the name of the process of HTTPS Everywhere extension in the task manager cause i don't see it? If you are referring to Utility: Network Service, that is a task added by google chrome, it is not HTTPS Everywhere extension

**Comment by Johann999** [comment]
The HTTPS Everywhere extension is the task 'Erweiterung Brave'.

**Comment by bsclifton** [comment]
> Hey, what is the name of the process of HTTPS Everywhere extension in the task manager, cause i don't see it? If you are referring to Utility: Network Service, that is a task added by google chrome, it is not HTTPS Everywhere extension

I don't think it'll show HTTPS Everywhere as a process - there isn't a way to remove it. The next best thing would be to disable it via brave://settings/shields with the setting `Upgrade connections to HTTPS`
![image](https://user-images.githubusercontent.com/4733304/96410810-57c48780-119c-11eb-95df-845778e02346.png)

**Comment by jithinjks** [comment]
This is not good, the browser should show only that you are going to unencyrpted side but browser should not take decision that it si not going to load it!
