### ISSUE TITLE
There should be a way to get release notes (even if manually)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1209]
Requested via https://www.reddit.com/r/brave_browser/comments/9he5r9/are_patch_notes_for_dev_builds_made_available/

The ideal situation would be to update CHANGELOG.md in `brave-core` for what issues are fixed with a build ([similar to browser-laptop](https://github.com/brave/browser-laptop/blob/master/CHANGELOG.md))

However, it could take some time to create that automation. In the meantime, there should be a way to manually audit the changes. `brave-browser` does tag the builds which makes comparisons easier:
https://github.com/brave/brave-browser/compare/v0.55.4...v0.55.5

However, `brave-core` (and sub-components, like `brave-extension`) are not using tags, so there's not a clear way to tell what was fixed when

Another approach (instead of tagging), would be to create the milestones manually in GitHub (ex: `0.55.4` or `0.55.5`) and then manually assign the issues to those milestones

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/no-way-to-see-a-summary-of-updates-anymore/35839?u=eljuno

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/brave-beta-changelog/36285

**Comment by srirambv** [comment]
+1 from @reisraff via #1936

**Comment by bsclifton** [comment]
@srirambv do you think this is covered with your script?
https://github.com/brave/qa-resources/blob/master/changelog.py

**Comment by srirambv** [comment]
@bsclifton that script would just grab the issue titles and categorize it based on features. But wont be the polished version of it which @kjozwiak and @rebron  do it manually. If we are ok with just having the crude issue titles this script should do it
