### ISSUE TITLE
unable to tip from panel when disabling content-level tips

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12090]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/11997

If you disable content-level tips (ex. for Twitter), you can no longer tip that publisher type/platform from the panel.

## Steps to Reproduce

Scenario 1: clean profile
   1. Using 1.17.x, enable rewards
   2. Disable Twitter content-level tips (brave://rewards > Tips panel > open settings > uncheck Twitter)
   3. Navigate to a site like twitter.com/emerick
   4. Note in-line tip button is not displayed (this is expected)
   5. Open panel

Scenario 2: upgraded profile
   1. Using 1.16.x, enable rewards
   2. Disable Twitter content-level tips (brave://rewards > Tips panel > open settings > uncheck Twitter)
   3. Navigate to a site like twitter.com/emerick
   4. Note in-line tip button is not displayed (this is expected)
   5. Open panel, publisher info is displayed, you are able to tip
   6. Close and upgrade to 1.17.x
   7. Go to same site and open panel

## Actual result:

Unable to tip from panel:
<img width="932" alt="1 17 x" src="https://user-images.githubusercontent.com/28145373/95758072-f5d4c100-0c75-11eb-9692-23da092c9765.png">

## Expected result:
When content-level tips are disabled you should still be able to tip from the panel as you can in 1.16.x:
<img width="1000" alt="1 16 x" src="https://user-images.githubusercontent.com/28145373/95758081-f8371b00-0c75-11eb-9f7b-0d0069ccb3bd.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.25 Chromium: 86.0.4240.75 (Official Build) nightly (x86_64)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @emerick

**Comment by NejcZdovc** [comment]
@emerick probably we will need to use this variable dynamically and not set it as a pre condition, but use it as variable in the script, so that we can dynamically inject things in based on this condition

**Comment by petemill** [comment]
Injecting 2 scripts seems reasonable (as additive or exclusive depending on if there's overlap in logic, both should be easy with webpack). There would still be a precondition on the first, right? At least for rewards enabled in general.

**Comment by NejcZdovc** [comment]
@petemill there is no more rewards enabled :)

**Comment by LaurenWags** [comment]
Reproduces when disabling content-level tips for Reddit as well:

<img width="1219" alt="reproduce 12090 thread" src="https://user-images.githubusercontent.com/28145373/97219867-02dacf80-17a1-11eb-9acb-f18d85e0b75d.png">
<img width="1213" alt="Screen Shot 2020-10-26 at 3 35 42 PM" src="https://user-images.githubusercontent.com/28145373/97219870-040bfc80-17a1-11eb-816f-f7fdb3efa7cb.png">


Brave | 1.17.50 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)

**Comment by LaurenWags** [comment]
Requires an uplift, labeling as `QA/Blocked` until that is completed.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.17.62 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
Revision	37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS	macOS Version 10.14.6 (Build 18G6032)
```

Verified STR from description.
Verified test plan from https://github.com/brave/brave-core/pull/6889.

<details>
<summary>Reddit</summary>

Unchecked content level tips for Reddit:

<img width="663" alt="Reddit 1" src="https://user-images.githubusercontent.com/28145373/98387632-a6d53e00-201f-11eb-8c39-ce9b8c87407c.png">

Confirmed no content level tip icon on user page or subreddit pages:

<img width="1156" alt="Reddit 2" src="https://user-images.githubusercontent.com/28145373/98387639-a9d02e80-201f-11eb-9218-f3c377312bd5.png">
<img width="1149" alt="Reddit 3" src="https://user-images.githubusercontent.com/28145373/98387642-ab015b80-201f-11eb-8ed5-9065ace0a902.png">

Confirmed still able to tip from panel with content level tip icon disabled:

<img width="659" alt="Reddit 4" src="https://user-images.githubusercontent.com/28145373/98387652-ad63b580-201f-11eb-92a1-05a43d1022c3.png">

Confirmed setting retained on relaunch. 
Confirmed visiting the pages after relaunch still does not show content level tip icon.
Confirmed re-enabling content level tips (and refreshing page if open) shows the in-line tip icon again.

</details>
