### ISSUE TITLE
Fingerprinting 2.0: User Agent - follow up to 9190

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12097]
Per https://github.com/brave/brave-browser/issues/9190#issuecomment-707172886, https://github.com/brave/brave-browser/issues/9190 should be tested with 1.17.x when all of the code has landed.

### Test plan for both Desktop and Android (per https://github.com/brave/brave-browser/issues/9190#issuecomment-703932628):

per @pes10k comment:
i've added a user-agent row to https://dev-pages.brave.software/farbling.html

Things to check:
1. using an android device, hit the "generate fingerprints" button, then click on one of the hash values in that row and make sure that in the popup it says "android device" and not any particular device model
2. in "strict" blocking, you should get different fingerprints across top-level origins and sessions (there aren't a huge number of possible random values here, so if you see an identical fingerprint (for the user-agent row only), its worth checking on the [sibling page](https://dev-pages.bravesoftware.com/farbling.html) or on another session to see if you get another fingerprint then)

### Original issue description

This is a sub-issue of the larger fingerprint defense reorganization issue: #8787

### User Agent String
`NavigatorID.userAgent`

**default protections**:
- for devices with OS version numbers, always report `MAX(current minor version number, latest version number as of build)`
- (only for android) don't report device name in UA, only return "android device" (same as what DDG browser does)

**max protections**:
- return chrome default UA for each platform
- At end of UA, add [0, 5] additional whitespace characters, as determined by eTLD+1 seed (only for JS reflected value)

(other notes for future consideration)
In default mode, we could _probably_ get by safely with adding [0, 5] additional whitespace characters, as determined by eTLD+1 seed (only for JS reflected value), but for the first time out, lets be very very conservative with the UA and not make any "clever" changes like that.

Also, we could probably get by with adding [0, 3] additional whitespace characters between UA segments, but again, for the first change, lets be conservative.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.55 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified test plan from description

Using https://dev-pages.brave.software/farbling.html and https://dev-pages.bravesoftware.com/farbling.html, confirmed:

<details>
<summary>When FP = strict, the "User Agent" row has the same values in each column and the values differ between the two pages</summary>

<img width="1199" alt="strict 1" src="https://user-images.githubusercontent.com/28145373/97606556-4d995900-19e6-11eb-99a6-370ce9e7be54.png">

</details>

<details>
<summary>If I relaunch and generate fingerprints again, when FP = strict, the "User Agent" row values differ from previous session (values are not retained on each page per session). Note, issue description notes limited values so duplicate values are possible</summary>

<img width="1199" alt="strict relaunch" src="https://user-images.githubusercontent.com/28145373/97606566-4ffbb300-19e6-11eb-80eb-a107eb94853c.png">

</details>

Logged https://github.com/brave/brave-browser/issues/12392 as a follow up for the Worker column value not matching the other values in the User Agent row. Note, this value is the same as when FP = standard or shields are off.

<details>
<summary>FP=standard</summary>

<img width="1197" alt="standard" src="https://user-images.githubusercontent.com/28145373/97606827-9bae5c80-19e6-11eb-9042-6dd423cf3fa3.png">

</details>

<details>
<summary>Shields off</summary>

<img width="1201" alt="shields down" src="https://user-images.githubusercontent.com/28145373/97606834-9e10b680-19e6-11eb-845b-955442499d22.png">

</details>

-----------

**Comment by srirambv** [comment]
Removing Android label as a followup issue #12638 is  logged
