### ISSUE TITLE
Canvas FP values should be different when switching between standard and strict

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12106]
## Description 

Per discussion with @pes10k, if you change your FP shield setting from standard to strict, the Canvas FP values should not be the same between the two shield selections.

related issues: https://github.com/brave/brave-browser/issues/9186 (Canvas FP farbling issue) and https://github.com/brave/brave-browser/issues/12099 (Canvas Worker farbling issue)

## Steps to Reproduce

   1. Clean profile
   2. Visit https://dev-pages.bravesoftware.com/farbling.html and/or https://dev-pages.brave.software/farbling.html
   3. Note shield setting for FP (most likely standard)
   4. Generate Fingerprints on the sites
   5. Take a screenshot to note values for Canvas row
   6. Change shield FP setting to strict for sites
   7. Generate Fingerprints on the sites again
   

## Actual result:

Look at Canvas row - values are the same for both FP shield settings
1.16.x FP = standard
<img width="1204" alt="1 16 x standard FP Canvas2" src="https://user-images.githubusercontent.com/28145373/95855520-8bc82480-0d26-11eb-9031-9fb51c2e885a.png">

1.16.x FP = strict
<img width="1201" alt="1 16 x strict FP Canvas2" src="https://user-images.githubusercontent.com/28145373/95855525-8e2a7e80-0d26-11eb-9e2f-fbf242a458cb.png">

## Expected result:
Canvas row values should be different when choosing the other (standard or strict) FP selection

## Reproduces how often: 

easily

## Desktop Brave version:

Brave | 1.16.58 Chromium: 86.0.4240.75 (Official Build) dev (x86_64)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | macOS Version 10.14.6 (Build 18G3020)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 1.15.x
- Can you reproduce this issue with the beta channel? yes 1.16.x
- Can you reproduce this issue with the nightly channel? yes 1.17.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @pes10k @rebron

**Comment by pes10k** [comment]
Hi @LaurenWags are you still seeing this?  I believe it should be fixed now.  Can you verify when you have a chance?

**Comment by LaurenWags** [comment]
@pes10k appears fixed on latest Nightly 🎉 

```
Brave | 1.24.46 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 10.15.7 (Build 19H524)
```

Confirmed that Canvas FP values differ between the two pages once Fingerprints have been generated (columns 1 & 2 in table below).
Confirmed that Canvas FP values differ between standard/strict settings for the same page (rows 1 & 2 in table below).

FP = Standard | FP = Strict
----- | -----
<img width="1125" alt="bravesoftware - STD" src="https://user-images.githubusercontent.com/28145373/113571247-07bf6d00-95e4-11eb-8776-8fbd9e8c57e9.png"> | <img width="1123" alt="bravesoftware - strict" src="https://user-images.githubusercontent.com/28145373/113571256-0b52f400-95e4-11eb-9488-e1b890e936c2.png">
<img width="1124" alt="brave software - STD" src="https://user-images.githubusercontent.com/28145373/113571261-0d1cb780-95e4-11eb-82b9-1a75094b4e23.png"> | <img width="1125" alt="brave software - strict" src="https://user-images.githubusercontent.com/28145373/113571264-0e4de480-95e4-11eb-8c81-d1da8695c61d.png">

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.24.81 x64 build
- Verified Canvas FP value is different on both pages for pages for strict/standard settings

![image](https://user-images.githubusercontent.com/17010094/116696270-9774f300-a9b9-11eb-8538-bf0ff0bc7109.png) | ![image](https://user-images.githubusercontent.com/17010094/116696280-9cd23d80-a9b9-11eb-97b2-372b28e802f8.png)
-- | --
![image](https://user-images.githubusercontent.com/17010094/116696290-a065c480-a9b9-11eb-8a41-7773cdc1f6ab.png) | ![image](https://user-images.githubusercontent.com/17010094/116696305-a360b500-a9b9-11eb-8910-25ad571cde01.png)
