### ISSUE TITLE
Media publishers should appear in auto-contribute table

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#12107]
## Description 
All Rewards media publishers should appear in the auto-contribute table. Currently, we show YouTube publishers in the table and we have some hardcoded functionality to also show GitHub publishers there (which isn't currently working due to the Greaselion rearchitecture).

Instead of handling this in C++ code, it should be initiated in the individual Greaselion scripts. One idea is to have the Greaselion script track the visibility state of its containing tab:

- When the tab is made visible, it can save the current time in a variable
- When the tab is hidden, the script would calculate the duration (`now - timestamp`) and call `UpdateMediaDuration` with it

This would basically mimic what the Rewards tab helper is already doing.

## Steps to Reproduce

   1. Clean profile
   2. Enable Rewards auto-contribution
   3. Visit a Reddit user or any other Rewards media publisher
   4. Wait long enough for publisher to appear in a-c table (typically 8 seconds)

## Actual result:

Publisher does not appear in the a-c table, only the generic "reddit.com" appears

## Expected result:
Publisher should appear in the a-c table (e.g., "Emerick Rogul on Reddit")

## Reproduces how often: 

100%

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Will this apply to Twitter as well?

**Comment by emerick** [comment]
@LaurenWags Yes, I believe the idea is that all media publishers should appear in the a-c table once we have this in place.

**Comment by LaurenWags** [comment]
Verification in progress with 

```
Brave	1.19.76 Chromium: 87.0.4280.101 (Official Build) dev (x86_64)
Revision	9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS	macOS Version 10.15.7 (Build 19H15)
```

Used dev component version 1.0.40:
<img width="355" alt="Component" src="https://user-images.githubusercontent.com/28145373/103799135-af92c200-5018-11eb-9d60-fe53e7c2ff30.png">

Encountered and logged https://github.com/brave/brave-browser/issues/13391 - restart after enabling Rewards is required to get media publishers added to AC list. All testing below was done with this in mind.

1. Confirmed visiting a media publisher page (without playing a video on supported pages) like the below for minimum amount of time was added to AC list
https://twitter.com/emerick
https://www.twitch.tv/ilikeblueturtles (did not play a video)
https://vimeo.com/bravelaurenwags (did not play a video)
https://www.reddit.com/user/jsadler-brave/
https://github.com/laurenwags/
https://www.youtube.com/user/jjdsampson (did not play a video)

Confirmed auto contribute occurred successfully for all of the above by looking at brave://rewards-internals and monthly statement:

AC List | `brave://rewards-internals` | Monthly Statement
----- | ----- | -----
<img width="694" alt="AC list 1" src="https://user-images.githubusercontent.com/28145373/103799386-04ced380-5019-11eb-90b6-d294328aa445.png"> | <img width="1194" alt="AC internals 1" src="https://user-images.githubusercontent.com/28145373/103799210-cc2efa00-5018-11eb-91ac-51bcab8f3a17.png"> | <img width="949" alt="AC monthly stmt 1" src="https://user-images.githubusercontent.com/28145373/103799217-cd602700-5018-11eb-8d1e-9ef8803084e4.png">


2. Confirmed playing a video on below pages (for minimum amount of time) was added to AC list
https://www.twitch.tv/videos/344762635
https://vimeo.com/354953087
https://www.youtube.com/watch?v=uWKCm2GKVyE

Confirmed AC occurred successfully for all of the above by looking at brave://rewards-internals and monthly statement.

AC List | `brave://rewards-internals` | Monthly Statement
----- | ----- | -----
<img width="642" alt="AC list 2" src="https://user-images.githubusercontent.com/28145373/103799566-43648e00-5019-11eb-81d6-a2d5bf9cc29d.png"> | <img width="1193" alt="AC internals 2" src="https://user-images.githubusercontent.com/28145373/103799570-4495bb00-5019-11eb-8727-d29e5fa13881.png"> | <img width="944" alt="AC monthly stmt 2" src="https://user-images.githubusercontent.com/28145373/103799577-465f7e80-5019-11eb-9687-38afe8b57073.png">


3. Using a clean profile, unchecked 'Allow contribution to videos' in AC settings and visited all video links below for at least 30s. Confirmed media publishers (ex. Sampson on YouTube) were not added to AC list.
https://www.twitch.tv/videos/344762635
https://vimeo.com/354953087
https://www.youtube.com/watch?v=uWKCm2GKVyE

4. Using a clean profile, unchecked 'Allow contribution to videos' in AC settings and visited all media publisher types. No non-video media publishers (Twitter, Reddit, GitHub) were added to AC list. Logged https://github.com/brave/brave-browser/issues/13394.
https://twitter.com/emerick
https://www.twitch.tv/ilikeblueturtles (did not play a video)
https://vimeo.com/bravelaurenwags (did not play a video)
https://www.reddit.com/user/jsadler-brave/
https://github.com/laurenwags/
https://www.youtube.com/user/jjdsampson (did not play a video)

TBD:

5. Confirmed regular sites (non media publishers) still added to AC list and contribution works as expected.
