### ISSUE TITLE
Increase the tear-off-tab vertical threshold (or make configurable)

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1210]
Sometimes you're trying to re-order your tabs by dragging them horizontally and your pointer drifts just a little too far vertically, and — woops — now you've torn off the tab! This can be frustrating [👁 #942].

We could make this less frustrating for folks who don't want to tear off the tab by increasing the threshold before the tab tears off. Of course, this would come at the expense of making it just a little bit more work to tear off a tab when you *do* want to. Perhaps we could split the baby by adding a preference for how far you have to move a tab vertically before it detaches.

**Comment by rebron** [comment]
Tearing off tabs is too easy to do when a user might select a tab and just want to reorder a tab. 
1) There's no feedback when a tab tear is about to happen (no detachment feedback nor doesn't snap back to undo unwanted tab tear)
2) Selecting a tab and dragging it vertically up or down just a few pixels, tears off a tab.

Need some UE input.

**Comment by tristandegroof** [comment]
> Re-open?
> 
> Someone please fix this, it's driving us crazy ([+1 community feedback](https://community.brave.com/t/a-way-to-prevent-moving-a-tab-from-creating-a-new-window/328689)) The first issue for this has been created like 5 years ago...
> 
> Possible solutions:
> 
> 1. Increasing the treshold by 30 or more pixels on the Y axis (configurable)
> 2. Disabling the tear-off entirely in config
> 3. Do not tear-off until the user released the mouse button, like in Firefox (that's how it works in most apps, even text editors)

Fully agree- so annoying when a tab detaches if I want to select it and I happen to move my mouse or hold the button just a fraction....
