### ISSUE TITLE
Feature Request: Native Unstoppable Domains resolution

### ISSUE THREAD

**Issue by agnelvishal** [brave/brave-browser#12110]
#### Description 

Unstoppable Domains provides blockchain based domains. The official website of them is at https://unstoppabledomains.com 
Brave requires an [extension](https://unstoppabledomains.com/extension) to resolve Unstoppable Domains. 
It would be better if native support for Unstoppable Domains resolution is provided. 

#### Miscellaneous Information:
1. Opera provides inbuilt support for Unstoppable Domains resolution [Source](https://www.coindesk.com/operas-android-web-browser-adds-access-to-crypto-domains-for-80m-users)
2. Related  [Tweet]( https://twitter.com/BrendanEich/status/1248643274119634945?s=20) where Brendan Eich said they may consider adding this support.

**Comment by Xerosigma** [comment]
Alternative could be to bake the extension in or automatically install.

**Comment by thefallofbecause** [comment]
Support for .crypto domains is built-in now (has been for a while).

Other Unstoppable domains are not yet implemented, but being tracked in https://github.com/brave/brave-browser/issues/16125.

**Comment by yrliou** [comment]
We've supported this for a while now, recently we add L2 support too (https://github.com/brave/brave-browser/issues/22147) and support all domain registries under the Unstoppable Naming System (UNS), including the current .crypto, .x, .coin, .nft, .dao, .wallet, .888, .blockchain, and .bitcoin registries.
.zil is not supported and being tracked in [#16125](https://github.com/brave/brave-browser/issues/16125) as @thefallofbecause mentioned.
I'll close this issue as duplicate now.
