### ISSUE TITLE
Remove overarching error page (Crypto Wallets)

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12119]
Currently, in the case of certain JS errors, an error notice will overtake the entire application, with no clear path to resolution for the user. This was added upstream in https://github.com/MetaMask/metamask-extension/pull/7889

Well of course reports of errors should be taken seriously, users should still be able to access their recovery keys and other portions of the app, in the event one portion of it errors out. This diff should effectively be reverted. 

## Test Plan
1. Perform a general regression test, ensuring that this error page does not appear. (Alternatively, manually build the codebase with an error purposefully introduced, and ensure this page does not show)

**Comment by srirambv** [comment]
This is fixed on current release component `1.0.23`. Didnt see any issue while going over manual pass. Marking as QA/No and moving to release milestone
