### ISSUE TITLE
JS Errors in Crypto Wallets console

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12117]
## Test Plan #1
1. Lock Crypto Wallets
2. Open up the JS console on the lock page.

## Expected
No React related console errors

## Actual
<img width="548" alt="Screen Shot 2020-10-13 at 3 37 09 PM" src="https://user-images.githubusercontent.com/8732757/95923851-3bbf8100-0d6b-11eb-8497-c278ca1b1f58.png">

## Test Plan 2
1. Set up Crypto Wallets fresh
2. Do not back up seed phrase
3. Load main activity view

## Expected
No React related errors

## Actual
<img width="542" alt="Screen Shot 2020-10-13 at 3 36 50 PM" src="https://user-images.githubusercontent.com/8732757/95923891-509c1480-0d6b-11eb-8926-632808007023.png">

**Comment by ryanml** [comment]
Related upstream issue: https://github.com/MetaMask/metamask-extension/issues/9577

**Comment by srirambv** [comment]
This is fixed on current release component `1.0.23`.  Verified on all platforms to be working fine.
