### ISSUE TITLE
White flash when opening a new tab on Android

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#12112]
## Description 
When opening a new tab on Android, there is a quick white flash that appears before the page is rendered. While not a huge deal, for users who are sensitive to this type of "flash" it can be quite the headache. 

## Steps to reproduce 

   1. Open Brave on Android
   2. Open new tab
   3. Observe flash 

## Actual result 
NTP opens after white flash

## Expected result
No white flash

## Issue reproduces how often 
Every time

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Y
- Can you reproduce this issue with the current Play Store Beta version? Y
- Can you reproduce this issue with the current Play Store Nightly version? 

## Device details
   - Install type (ARM, x86): Waiting on user info
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
v1.15.73

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

User has shared a short recording of the behavior:
https://drive.google.com/file/d/14-JehxYtHPeFKopKiRBDuU3dmEmBjGCv/view
cc @samartnik

**Comment by bsclifton** [comment]
@Brave-Matt is this a dupe of https://github.com/brave/brave-browser/issues/11985?

**Comment by Brave-Matt** [comment]
Yep dupe of https://github.com/brave/brave-browser/issues/11985 -- closing this one.

**Comment by seccentral** [comment]
this is still a thing. [Version 1.40.113 Chromium: 103.0.5060.114 (Official Build) (64-bit)](https://brave.com/latest/)
