### ISSUE TITLE
Remove chrome-browser-net-net_error_tab_helper.cc.patch file

### ISSUE THREAD

**Issue by Gyuyoung** [brave/brave-browser#12121]
The patch file is to return false in NetErrorTabHelper::ProbesAllowed(). However, Brave has been disabling "embedder_support::kAlternateErrorPagesEnabled" pref. So, |resolve_errors_with_web_service_| should be false. So, it looks like we don't need to return a false using an unnecessary patch file.

```
---- a/chrome/browser/net/net_error_tab_helper.cc
-+++ b/chrome/browser/net/net_error_tab_helper.cc
@@ -201,6 +201,9 @@ void NetErrorTabHelper::InitializePref(WebContents* contents) {
 }
 
 bool NetErrorTabHelper::ProbesAllowed() const {
+#if defined(BRAVE_CHROMIUM_BUILD)
+  return false;
+#endif

  // TODO(juliatuttle): Disable on mobile?
  return *resolve_errors_with_web_service_;
}
```

**Comment by kjozwiak** [comment]
Removing/Closing the issue as per https://github.com/brave/brave-core/pull/6853#issuecomment-729314429.
