### ISSUE TITLE
[Desktop] Implement earn&give onboarding

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#12138]

**Comment by zenparsing** [comment]
Rewards onboarding tour will be implemented in #12459

**Comment by zenparsing** [comment]
Clarifying questions:

- What rule determines when the onboarding modal is displayed on the panel or on the rewards page?
  - Both Ads and AC disabled?
  - Is it tied to the first panel/page visit?
  - Do we need to store something in preferences to indicate that they've dismissed the modal?
- What rule determines when the onboarding form is displayed on the tip dialog?
  - Both Ads and AC disabled?
- What does clicking the "Start using Brave Rewards" button do?
  - Enable both AC and Ads?

**Comment by NejcZdovc** [comment]
> What rule determines when the onboarding modal is displayed on the panel or on the rewards page?
FIrst load of the panel/page. When user click on start or dismiss it we should not show it again. If user has already ads on we don't show this onboarding. For example if user sees this dialog in the panel and click dismiss or start when the go to tipping banner it should not be shown again.

> What does clicking the "Start using Brave Rewards" button do?
It enabled ads and ac

**Comment by zenparsing** [comment]
@NejcZdovc It seems like we'll need a pref to store whether the user has seen and interacted with the onboarding modal, unless you think there's a better way?

**Comment by NejcZdovc** [comment]
perf should work yes

**Comment by bbondy** [comment]
Could you add `release/blocking` if this is blocking the release? Otherwise remove from the milestone. Thank you.

**Comment by NejcZdovc** [comment]
label added

**Comment by GeetaSarvadnya** [comment]
Verification is inprogess

```

Brave | 1.18.68 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/7050

<details>
<summary>Rewards Panel (dismissing case)</summary>

</details>

**Comment by GeetaSarvadnya** [comment]
@zenparsing Test plan needs to update for the case "Inline tipping (dismissing case)"

>Open the rewards panel.
>Verify that the onboarding modal is not displayed.

In the above case, the onboarding modal should be displayed upon clicking on the BR panel, as rewards is not opt-in when the tipping banner is opened via inline Tip

**Comment by zenparsing** [comment]
@GeetaSarvadnya Thanks for pointing this out - the behavior was changed slightly in a subsequent PR (https://github.com/brave/brave-core/pull/7135). I'll fix the test plan.

**Comment by GeetaSarvadnya** [comment]
@zenparsing Awesome!!!. Thanks for the quick response.
