### ISSUE TITLE
'Managed by your organization' on fresh install

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#12137]
## Description 
Fresh OS+browser install, Brave claims to be managed by an organization + warns about remote changes (pics). The OS is Fedora 33

## Steps to Reproduce

   1. install brave per instructions on brave.com

## Actual result:
![Screenshot from 2020-10-14 13-04-00](https://user-images.githubusercontent.com/36133540/95980921-2d7e6d00-0e1e-11eb-83df-525cb06d3d64.png)
![Screenshot from 2020-10-14 13-06-21](https://user-images.githubusercontent.com/36133540/95980923-2eaf9a00-0e1e-11eb-8e6c-c42168b0c769.png)

## Expected result:
this shouldn't happen, I never had this problem before. I am not affiliated to any organization

## Reproduces how often: 
always

## Brave version (brave://version info)

Brave | 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | Linux
JavaScript | V8 8.6.395.10

**Comment by truthmonkey** [comment]
This is usually related to your Google account - have you added it to Brave to sync?

If you have a Google Apps account, ie you have a custom domain rather than just @gmail.com then it's considered a "managed organisation" even if you are the only account.

**Comment by pilsnerbeer** [comment]
I haven't added my Google account and I dont use sync with Brave. Also, I noticed today that chromium shows the same thing after installing it. Could it be Fedora-related?

**Comment by ukbeast** [comment]
Fresh install of Brave-beta.
Would any of these policies have anything to do with it?
![Screenshot_20201127_212700](https://user-images.githubusercontent.com/6401168/100485342-8ae12b80-30f7-11eb-8513-4cf132f59fd3.png)

**Comment by tibbsbrookside** [comment]
I have the same thing on Fedora 33. I don't use Google.

**Comment by bsclifton** [comment]
Thanks for sharing that @ukbeast - do you know where those policies are being pulled from? I've never tried to set group policy on Linux

**Comment by tibbsbrookside** [comment]
See the "Special consideration for Google Chrome" section in:
https://fedoramagazine.org/getting-set-up-with-fedora-project-services/

**Comment by simonhong** [comment]
@tibbsbrookside I think this issue is related with https://github.com/brave/brave-browser/issues/12426.
Can you check you have `/etc/chromium/policies/managed`?

**Comment by tibbsbrookside** [comment]
```
ls -al /etc/chromium/policies/managed
total 4
drwxr-xr-x. 1 root root 28 Nov  1 11:48 .
drwxr-xr-x. 1 root root 14 Oct 20 00:38 ..
lrwxrwxrwx. 1 root root 62 Nov  1 11:48 00_gssapi.json -> ../../../../usr/share/chromium/policies/managed/00_gssapi.json

cat /usr/share/chromium/policies/managed/00_gssapi.json
{
	"AuthServerWhitelist": "*.fedoraproject.org",
	"AuthNegotiateDelegateWhitelist": "*.fedoraproject.org"
}

rpm -qf /etc/chromium/policies/managed/
fedora-chromium-config-1.1-6.fc33.noarch

rpm -qf /usr/share/chromium/policies/managed/00_gssapi.json
fedora-chromium-config-1.1-6.fc33.noarch

rpm -ql fedora-chromium-config
/etc/chromium
/etc/chromium/policies
/etc/chromium/policies/managed
/etc/chromium/policies/managed/00_gssapi.json
/etc/opt/chrome
/etc/opt/chrome/policies
/etc/opt/chrome/policies/managed
/etc/opt/chrome/policies/managed/00_gssapi.json
/usr/lib/tmpfiles.d/fedora-chromium-config-tmpfiles.conf
/usr/share/chromium
/usr/share/chromium/extensions
/usr/share/chromium/extensions/hojggiaghnldpcknpbciehjcaoafceil.json
/usr/share/chromium/policies/managed/00_gssapi.json
/usr/share/google-chrome
/usr/share/google-chrome/extensions
/usr/share/google-chrome/extensions/hojggiaghnldpcknpbciehjcaoafceil.json
/usr/share/licenses/fedora-chromium-config
/usr/share/licenses/fedora-chromium-config/LICENSE
```

I don't use Chromium or Chrome, so I uninstalled the "fedora-chromium-config" package and now Brave no longer reports it is being “Managed by your organization” and there are no policies listed.

**Comment by simonhong** [comment]
@tibbsbrookside Thanks for checking! We should fix #12426

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.19.66 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Ubuntu 18.04 LTS

Reproduced the issue on 1.18.x
![image](https://user-images.githubusercontent.com/34715963/103012027-36d13780-453b-11eb-84a7-66f24f2c9f3a.png)

Verified test plan from https://github.com/brave/brave-browser/issues/12426

Verified that `/etc/chromium/policies/managed` has no effect on Brave.
![image](https://user-images.githubusercontent.com/34715963/103011926-0ee1d400-453b-11eb-919c-238a5b6207e0.png)

Verified when "TorDisabled": true in `/etc/brave/policies/managed`, Tor is disabled
Verified Brave is `Managed by your organization
![image](https://user-images.githubusercontent.com/34715963/103011176-c70e7d00-4539-11eb-858c-7bf5bc58bbf6.png)

Verified when "TorDisabled": false in `/etc/brave/policies/managed`, Tor is enabled
Verified Brave is `Managed by your organization
![image](https://user-images.githubusercontent.com/34715963/103011516-5c117600-453a-11eb-8770-fad1a61f1552.png)

**Comment by gabriellovate** [comment]
Is this fixed? I have the same issue on Fedora 34.

**Comment by simonhong** [comment]
@gabriellovate Can you check you have any policy json files in `/etc/brave/policies/managed/`?

**Comment by gabriellovate** [comment]
Checked, I don't even have a `brave/` folder under `/etc/`

**Comment by simonhong** [comment]
@gabriellovate hmm... it's strange. you are using latest version now?

**Comment by ukbeast** [comment]
This package creates a policy
https://src.fedoraproject.org/rpms/fedora-chromium-config
Removing this should 'fix' the issue for you,
SIdenote.
"It includes a GSSAPI configuration that enables access to many Fedora
Project services"

**Comment by simonhong** [comment]
@ukbeast well... brave doesn't refer chromium's policy files.

**Comment by gabriellovate** [comment]
I am on Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (64-bit)

**Comment by vbendel** [comment]
> Checked, I don't even have a `brave/` folder under `/etc/`

Just create the dirs and put the .json policy there. 
# mkdir -p /etc/brave/policies/managed/
