### ISSUE TITLE
[Android] Implement earn&give onboarding

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#12141]
Desktop UI for the panel as a reference https://www.figma.com/file/0dbMYs8Wp8W3RgrG1yTdki/RE-1.0?node-id=11%3A1

**Comment by NejcZdovc** [comment]
cc @jamesmudgett

**Comment by LaurenWags** [comment]
Verification in progress on LG Nexus 5 with Android 5.1 running 1.18.72 Bravearm.apk

Using https://www.figma.com/file/0dbMYs8Wp8W3RgrG1yTdki/RE-1.0?node-id=1555%3A0 for verification.

<details>
<summary>Entry Points - Rewards Panel - New User</summary>

Confirmed new user gets large onboarding UI when tapping on the panel | Confirmed clicking the "x" closes large onboarding UI and shows small onboarding UI: | Confirmed clicking on the "x" closes small onboarding UI and shows normal panel:
---------- | ---------- | ----------
![Screenshot_2020-12-14-16-21-52](https://user-images.githubusercontent.com/28145373/102137410-cb93b100-3e28-11eb-8219-553dd5c68e24.png) | ![Screenshot_2020-12-14-16-22-39](https://user-images.githubusercontent.com/28145373/102137416-ccc4de00-3e28-11eb-8125-c34d748e98e3.png) | ![Screenshot_2020-12-14-16-23-01](https://user-images.githubusercontent.com/28145373/102137422-ce8ea180-3e28-11eb-9f77-fd358201106c.png)

Confirmed "Terms of Service" link opens TOS.
Confirmed "Privacy Policy" link opens Privacy Policy.

Confirmed "Take a quick tour" opens onboarding tour (no settings slide) and does not enable Ads and AC.

Confirmed "Start using Brave Rewards" opens onboarding tour (with settings slide) and also enables Ads and AC.

</details>
