### ISSUE TITLE
Fails to show cert error on pinning test 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1214]
## Steps to Reproduce

   1. Go to https://pinning-test.badssl.com/

## Actual result:
The site was opened.
Cert error was not shown
Page is shown as secure
![image](https://user-images.githubusercontent.com/34715963/45839273-328e9200-bd14-11e8-98b1-879c5dc78ef8.png)

## Expected result:
Similar to Chrome:
![image](https://user-images.githubusercontent.com/34715963/45839466-b9dc0580-bd14-11e8-93aa-ef34a33c4357.png)

## Reproduces how often: 
always

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

### Reproducible on current release:
yes, same version

Found when testing #767.
cc @diracdeltas @jumde

**Comment by jumde** [comment]
See here: https://github.com/brave/brave-browser/issues/767#issuecomment-423366157

**Comment by btlechowski** [comment]
@jumde can I then close it as won't fix?

**Comment by btlechowski** [comment]
This is expected behavior. Closing.
