### ISSUE TITLE
 `Cycle through the most recently used tabs with Ctrl-Tab` under `brave://settings/appearance` is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#12149]
Follow up to https://github.com/brave/brave-browser/issues/913

## Steps to Reproduce

   1. Run Brave in Polish(PL) locale
   1. Open ` brave://settings/appearance`
   1. Check the translation for  `Cycle through the most recently used tabs with Ctrl-Tab`

## Actual result:

 `Cycle through the most recently used tabs with Ctrl-Tab` is not translated

![image](https://user-images.githubusercontent.com/34715963/96059826-34919380-0e8f-11eb-8e80-6f030665e8b6.png)
![image](https://user-images.githubusercontent.com/34715963/96059834-3a877480-0e8f-11eb-9fa3-2f760174c8c4.png)

## Expected result:
 `Cycle through the most recently used tabs with Ctrl-Tab` is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.17.32 Chromium: 86.0.4240.80 (Official Build) nightly (64-bit)
-- | --
Revision | 7ed88b53bda45a2d19efb4f8706dd6b6cad0d3af-refs/branch-heads/4240@{#1183}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @mkarolin @rebron

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.18.2`

![image](https://user-images.githubusercontent.com/38657976/96854817-8d59c100-1479-11eb-89ca-8bc1e01bbaee.png)

**Comment by btlechowski** [comment]
Fixed by https://github.com/brave/brave-browser/issues/12559

Verification passed on

Brave | 1.17.69 Chromium: 87.0.4280.60 (Official Build) (64-bit)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/99351636-5375b200-28a1-11eb-8672-691cb7548177.png)
