### ISSUE TITLE
no publisher info displayed in panel/tipping on GitHub not working with Greaselion

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12159]
## Description 

If I navigate to a GH page with rewards enabled the panel does not show any publisher info.

I saw the below in my terminal

```
[10609:775:1015/115352.859077:INFO:CONSOLE(1)] "Uncaught (in promise) Error: Profile API request failed: rate limit exceeded (403)", source: chrome-extension://eoceebklhjepohnakemchinmkdpbolgh/github.bundle.js (1)
```

## Steps to Reproduce

   1. Clean profile 1.17.34
   2. Enable Rewards
   3. Wait for everything to load (watch terminal)
   4. Visit a GH page like github.com/bsclifton

## Actual result:

No publisher info in panel
<img width="1192" alt="Screen Shot 2020-10-15 at 11 56 55 AM" src="https://user-images.githubusercontent.com/28145373/96156091-b066fc80-0ede-11eb-8e81-4f494998e94c.png">

## Expected result:
Publisher info to be shown in the panel including tipping buttons, etc

<img width="1193" alt="Screen Shot 2020-10-15 at 12 08 02 PM" src="https://user-images.githubusercontent.com/28145373/96156467-1a7fa180-0edf-11eb-88f7-d9db92842b76.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.34 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, 1.15.x
- Can you reproduce this issue with the beta channel? no, 1.16.x
- Can you reproduce this issue with the nightly channel? yes, 1.17.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @emerick

**Comment by emerick** [comment]
@LaurenWags Maybe due to being on a VPN at the time?

**Comment by LaurenWags** [comment]
@emerick unfortunately I don't think so, I very rarely use VPN.

**Comment by kjozwiak** [comment]
Removing `release/blocking` as this has been opened a while ago and hasn't been added into a milestone.

**Comment by Miyayes** [comment]
Does not reproduce anymore.
