### ISSUE TITLE
Implement wallet import/migration for existing users. Follow up to #24

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1215]
## Description 

Implement wallet import/migration for existing users. Follow up to #24  Current import only works for Bookmarks/Stats/Password/History/Cookies.

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

**Comment by kjozwiak** [comment]
We need to have a discussion to figure out what we're going to import from the muon in terms of payments.. Example:

* currently accepted grants
* current balance
* payments history reports
* ledger table
* payment settings (allow videos etc..)
* previously created crypto addresses (litcoin, ETH, BTC)

**Comment by bbondy** [comment]
I think as long as wallet is recoverable we shouldn't block 0.55.x on anything else. Reports can still be obtained for example in the old browser.  Let me know if you disagree or feel strongly, I'll put to 1.x for now.

**Comment by bbondy** [comment]
The only reason not to do #1 would be based on complexity. Do you have a way to do this in a reasonable timeframe?  Mainly keeping in mind that we need to upgrade users for 0.56.x timeline.

If we fall to #2 I would think allow overwrite if 0 balance or ask if they would like to proceed even know there's a balance.  I think a user could for example backup their wallet and restore to profile 2 and then legit want to replace profile 1's wallet. 

For #3 I think we should do this too, I think I seen some slack conversations for this, but please go ahead and do this if you get sign-off from product.

**Comment by mandar-brave** [comment]
@garrettr @NejcZdovc @evq 
Once the Muon users are upgraded, their reconcile dates will be changed. However, to ensure the dates are spread out evenly across the month (to ensure privacy for every user), the dates need to randomly spread from the time of upgrade from day 0 to day 30 for every upgrade at the client end itself.

**Comment by rebron** [comment]
@garrettr
For "3. Re-order the brave://welcome first-run flow so "Import bookmarks and settings" comes before "Enable Brave Rewards." This should reduce (but will not eliminate) the probability that a conflict will occur." 

This looks like a good solution.
@rossmoody put together a new simplified welcome flow to support this change.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/736

**Comment by btlechowski** [comment]
Verification Passed on

Brave | 0.57.17 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

Used STR from https://github.com/brave/brave-core/pull/736
When the wallet already exists in b-c, the import is aborted.
Also imported using `--upgrade-from-muon` flag

Verified import is canceled when Brave Payments in b-l are turned off
Verified that following settings were imported:
- Minimum page time before logging a visit
- Minimum visits for publisher relevancy
- Allow contributions to non-verified sites
- Allow contributions to videos
- Wallet (this includes Grants; attached to wallet by way of server query) Checked addresses in UI and ledger_state
- Monthly Budget
- Pinned sites (Tips) 
- Turning auto-contribute on/off based on ledger table and pinned sites
