### ISSUE TITLE
[Wallets] Unable to connect to the widget even after successful authentication 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12153]
## Description 

Unable to connect to the widget even after successful authentication 

## Steps to Reproduce

   1. Clean install 1.16.59 beta build
   2. Click on Connect on Binance widget in NTP
   3. Login to account make sure Email code and Authenticator code is requested
   4. Once successfully logged in widget doesn't show connected state as there is no browser authentication is done
   5. Clear browsing data and try to connect again, works fine

Note: May need to setup VPN to trigger Email code

## Actual result:

Note: May need to setup VPN to trigger Email code

## Expected result:
Should authenticate in the first go and should ask permission to allow browser to access data

## Reproduces how often: 

Easy. Was able to get into this state without having email code on Windows

## Brave version (brave://version info)

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (64-bit)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by rebron** [comment]
@srirambv to retest and see if this is still happening.

**Comment by srirambv** [comment]
Verified on 

Brave | 1.24.86 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | `e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}`
OS | Linux

Issue seems to be resolved. Hence closing the issue
