### ISSUE TITLE
Show all 31 supported assets, updated icons, back button to markets [Crypto.com]

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12152]
Per crypto.com's feedback:

* From the “View Markets” page, it should have a back button to take user back to “Initial Screen”
* On the “View Markets” (page with BTC, ETH, CRO) , it should actually show all 31 crypto 
 - https://api.crypto.com/v2/public/get-instruments (look for the _USDT ones)
* Use icons (currently missing CRO's icon)

<img width="300" alt="Screen Shot 2020-10-15 at 1 42 24 AM" src="https://user-images.githubusercontent.com/8732757/96102455-66086000-0e8b-11eb-888e-da9c250f22b1.png">

## Test Plan
1. Ensure 31 supported assets are show in the top movers view
2. Ensure each asset has an icon
3. Ensure that clicking on the new back arrow moves the user back to the index view, until they opt-in again

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Linux

<details>
<summary>Verified all 31 assets are listed</summary>

![image](https://user-images.githubusercontent.com/17010094/96885004-11ac4400-147a-11eb-8da5-700236b5d2f8.png)

</details>

<details>
<summary>Verified CRO uses correct icon</summary>

![image](https://user-images.githubusercontent.com/17010094/96885181-44563c80-147a-11eb-88d7-134ec5aece41.png)

</details>

<details>
<summary>Verified able to go back to pre-opt-in state from market view via back button</summary>

![lin-hide](https://user-images.githubusercontent.com/17010094/96888473-92b90a80-147d-11eb-8e85-b5f7f1c24b99.gif)

</details>

---------------
Verification passed on 

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Windows 10 OS Version 1809 (Build 17763.1518)

<details>
<summary>Verified all 31 assets are listed</summary>

![image](https://user-images.githubusercontent.com/17010094/96889106-2db1e480-147e-11eb-933c-4e0864f0db08.png)

</details>

<details>
<summary>Verified CRO uses correct icon</summary>

![image](https://user-images.githubusercontent.com/17010094/96889588-a5800f00-147e-11eb-8c46-07587e1e67e0.png)

</details>

<details>
<summary>Verified able to go back to pre-opt-in state from market view via back button</summary>

![win-back](https://user-images.githubusercontent.com/17010094/96889686-c183b080-147e-11eb-8f47-60b5067acaec.gif)

</details>
 
----------
Verification passed on

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | macOS Version 10.15.7 (Build 19H2)

<details>
<summary>Verified all 31 assets are listed</summary>

![image](https://user-images.githubusercontent.com/17010094/96889920-00196b00-147f-11eb-83b5-5dfff82ef79a.png)

</details>

<details>
<summary>Verified CRO uses correct icon</summary>

![image](https://user-images.githubusercontent.com/17010094/96890248-5edee480-147f-11eb-8ca3-ed5111494bed.png)

</details>

<details>
<summary>Verified able to go back to pre-opt-in state from market view via back button</summary>

![mac-back](https://user-images.githubusercontent.com/17010094/96891778-e5e08c80-1480-11eb-8661-3d0fd33b353d.gif)

</details>
