### ISSUE TITLE
MRU tab feature not switching to the correct tab

### ISSUE THREAD

**Issue by andconta** [brave/brave-browser#12157]
## Description 
I'm testing the feature introduced with 
https://github.com/brave/brave-core/pull/4671
https://github.com/brave/brave-browser/issues/913

## Steps to Reproduce

   1. Open 3 tabs. I will call them A, B and C from the left to the right
   2. Click in sequence A, B, C just to reset the tab order
   3. While on tab C, hold the Ctrl key, press Tab key 2 times and release Ctrl key. The selected tab should be tab A
   4. Hold the Ctrl key and press tab key once

## Actual result:
The selected tab is now B

## Expected result:
The selected tab should be tab C.
If you look at how other browsers or applications using the Most Recently Used cycling work, they set the items order
when the Ctrl key is released and not when the Tab key is pressed.
This means that the tab B shouldn't be a recently viewed tab because the ctrl key wasn't released on it, but we only passed through during navigation.

I've recorded a video here (The first browser is Firefox, second is Brave nightly 1.18.8): 
https://www.youtube.com/watch?v=WPKqNGYxzRs

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.17.32 Chromium: 86.0.4240.80 (Official Build) nightly (64-bit)
Revision | 7ed88b53bda45a2d19efb4f8706dd6b6cad0d3af-refs/branch-heads/4240@{#1183}
OS | Windows 10 OS Version 2004 (Build 19041.572)

## Version/Channel Information:
The functionality is not in stable channel yet
- Can you reproduce this issue with the current release? 
N/A
- Can you reproduce this issue with the beta channel? 
N/A
- Can you reproduce this issue with the nightly channel? 
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by bsclifton** [comment]
Just for a sanity check, @andconta - do you have `Cycle through the most recently used tabs with Ctrl-Tab`  enabled under brave://settings/appearance? It's disabled by default

I enabled this and tried your use-case and it worked exactly as you'd expect (selected tab A). Please let me know 😄

**Comment by andconta** [comment]
> 
> 
> Just for a sanity check, @andconta - do you have `Cycle through the most recently used tabs with Ctrl-Tab` enabled under brave://settings/appearance? It's disabled by default

Yes, the option is enabled

> I enabled this and tried your use-case and it worked exactly as you'd expect (selected tab A). Please let me know 😄

At the end of the process, the selected tab should be C and not B. Note that at step 3 you need to press and hold the ctrl key. At the end of the step 3 the ctrl key is released and the selected tab is tab A, as expected. 
But when I again press ctrl+tab I would expect to see the tab that was selected when the previous ctrl tab process **started**, so tab C, instead of the tab that was simply navigated through (tab B).
The tab queue is set by the release of the ctrl key instead of the visualization of the tab.

You can compare this behavior with Firefox, Opera or Vivaldi browser.
I can record a video if it helps.

**Comment by rebron** [comment]
@bsclifton I was able to reproduce via the str. I'm getting `tab b` and I should be getting `tab c` in the last step. Firefox shows the right behavior. 

cc: @guifel @simonhong

**Comment by rebron** [comment]
Closing as wontfix per last comment https://github.com/brave/brave-browser/issues/12157#issuecomment-745083396. We proceed with the right cycling order, it's just that Firefox's tab preview window is making it look like the cycling is incorrect.

**Comment by andconta** [comment]
> 
> 
> Closing as wontfix per last comment [#12157 (comment)](https://github.com/brave/brave-browser/issues/12157#issuecomment-745083396). We proceed with the right cycling order, it's just that Firefox's tab preview window is making it look like the cycling is incorrect.

Hey,  Rebron, I've checked other browsers (Vivaldi, Opera), and the behavior is the same as the one used by Firefox.
Also it's the same used by a number of IDEs (VS Code, Visual Studio for example), not sure the one implemented for Brave works as it should.
