### ISSUE TITLE
Estimated pending rewards was affected when clearing browser history

### ISSUE THREAD

**Issue by phr34k0** [brave/brave-browser#12166]
## Description 

Lame Browser Bug that eliminates all your past viewed ads when you cleared your browser history. Apparently my estimated 4 bat was gone after doing so now it became 0.4 bat instead. WTF?

## Steps to Reproduce

1. CTRL+SHIFT+DEL and clear all your past browser history
2. Close your browser for 5 minutes and reopen and view your browser rewards

10 viewed ads this month (used to get tons of ad pop ups before I ran my own PiHole DNS) and from 4 bat became 0.4

![image](https://user-images.githubusercontent.com/13272249/96188777-e2756e80-0f71-11eb-80f0-9cc0bd915e03.png)

**Comment by ACodingGenie** [comment]
Could not reproduce in Brave 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit) on Windows 10 2004 using steps provided.

**Comment by phr34k0** [comment]
> Welcome to Brave's GitHub repo!
> I could not reproduce in Brave 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit) on Windows 10 2004 using steps provided. Be sure to include all relevant information regarding Browser version, device OS etc. as depicted in the original template for proper support.
> Thanks.

Alright thanks, maybe it's just me, my laptop brave browser for using linux (on the latest stable brave build) and being in Asia. My mobile was able to receive 5 ads per hour just leaving the browser open and scouring the net but not the PC version. It's cool, I'm like whatever.. will just uninstall the browser since it's a time waster and default back to chrome

**Comment by bsclifton** [comment]
@phr34k0 what version of Brave are you using? Can you go to brave://version and paste some of that here? Thanks

**Comment by phr34k0** [comment]
> @phr34k0 what version of Brave are you using? Can you go to brave://version and paste some of that here? Thanks

Hey @bsclifton , here you go.

`

Brave | 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Linux
JavaScript | V8 8.6.395.13
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=PrefetchPrivacyChanges,ReducedReferrerGranularity,PasswordImport,MixedContentSiteSetting,LegacyTLSEnforced,OmniboxContextMenuShowFullUrls,DnsOverHttps,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning --disable-features=NotificationTriggers,PasswordCheck,AutofillServerCommunication,VideoPlaybackQuality,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,SmsReceiver,TabHoverCards,PrivacySettingsRedesign,SafeBrowsingEnhancedProtection --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/phr34kz/.config/BraveSoftware/Brave-Browser/Default

`

**Comment by tmancey** [comment]
@phr34k0 can you please provide the steps on how you deleted the history, i.e. manually from disk or using the built in browser history as to my knowledge ctrl-shift-delete does not delete browser history from within the browser and only from the file system. If this is the case I would not recommend to delete history from the file system for Brave.

**Comment by phr34k0** [comment]
> @phr34k0 can you please provide the steps on how you deleted the history, i.e. manually from disk or using the built in browser history as to my knowledge ctrl-shift-delete does not delete browser history from within the browser and only from the file system. If this is the case I would not recommend to delete history from the file system for Brave.

Noted and is ok, even with me not doing it to my 2nd computer the earnings I get now is terrible vs the first two months I used the browser. Now is merely peanuts of 0.8 no matter how much I surfed the web, before I could easily get 4.0 bat if not 8.0. I've already uninstalled the browser and default back to Chrome. You can close this issue.

**Comment by tmancey** [comment]
@phr34k0 Thank you
