### ISSUE TITLE
Facebook Messenger Unable to Log In on Browser

### ISSUE THREAD

**Issue by vipertongn** [brave/brave-browser#12162]
I tried to search for this, but it doesn't seem to populate on the search engine. In the github I tried to follow the issue back in July of last year, but the resolution was turning off shield, which didn't resolve the issue.

## Description 
The browser keeps on having me try to log into my account, but it would loop me to go to facebook and relog into facebook.  The messenger website doesn't work.  Tried to log in through facebook first, but that has no effect on the messenger.com page. Attempted to log in with shields down, no effect.

## Steps to Reproduce

   1. Log into messenger.com 
   2.  Messenger window is stuck in Looks like you need to log into facebook first

## Actual result:

![image](https://user-images.githubusercontent.com/22553172/96165484-8824d100-0ed1-11eb-9017-1d6703d92508.png)

## Reproduces how often: 
All the time

## Brave version (brave://version info)

Brave | 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | Windows 10 OS Version 1909 (Build 18363.1139)

## Version/Channel Information:
N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by diracdeltas** [comment]
are facebook logins allowed in brave://settings/socialBlocking ?

**Comment by vipertongn** [comment]
![image](https://user-images.githubusercontent.com/22553172/96321317-d9b08700-0fc9-11eb-8bd4-3e631b694a52.png)
yes they are
I'm also able to log into fb directly

**Comment by wsor4035** [comment]
I also had this issue, but solved it by going to messenger.com disabling the shield there, and then signing in, disabling from the verify your Facebook account page had no effect

**Comment by ryanbr** [comment]
I was able to replicate this in Chrome also @wsor4035 @vipertongn not a Brave specific issue from what I see

**Comment by vipertongn** [comment]
****Looks like its's been resolved! yaass, was browser issue indeed

**Comment by terraf0rmer** [comment]
The issue is not resolved for me. I made sure "Allow FB Logins..." was enabled, went to the main page of messenger.com, disabled shields and it is still not working. It stays stuck on the "Please Verify Your Facebook Account" page. Additionally, I do have uBlock Origin enabled, but not sure if that is causing an issue. Like someone above, I can log into the main Facebook site with no issue and can communicate in messenger through that.
