### ISSUE TITLE
clicking on the shields increases the brightness of the separators, borders and titles

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1216]
## Description 

When clicking on the Brave Shields, the tab separators, borders and titles will become a bit brighter making it look like the tab bar area is "blinking". When you click on the Brave Shields for the second time to dismiss the shields window, it will go back to the darker white.

## Steps to Reproduce

   1.  on macOS, launch `brave-browser-dev` and open ~10 random websites
   2. click on the brave shield and you'll notice that the tab bar borders/separators/titles become brighter so it appears as the entire tab bar is "blinking"

## Actual result:

![flickeringtabs](https://user-images.githubusercontent.com/2602313/45843632-18da5400-bcee-11e8-8f98-aabeb1ca74cc.gif)

## Reproduces how often: 

100% reproducible using STR mentioned above.

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

### Reproducible on current release:

Yes, currently reproducible on the following build which is the released version at this time:

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

### Additional Information

Reproduced by @LaurenWags on macOS. @srirambv couldn't reproduce this on Win 10, seems specific to macOS.

**Comment by kjozwiak** [comment]
Can't seem to reproduce this anymore with the following versions:

* `0.70.18 Chromium: 76.0.3809.72 (Official Build) nightly` - Couldn't reproduce
* `0.69.96 Chromium: 76.0.3809.62 (Official Build) dev` - Couldn't reproduce
* `0.68.113 Chromium: 76.0.3809.62 (Official Build)` - Couldn't reproduce
* `0.67.120 Chromium: 76.0.3809.72 (Official Build)` - Couldn't reproduce

@LaurenWags mind taking a quick look on your `macOS` when you have some time to see if this is still reproducible on your end? Thanks!

**Comment by LaurenWags** [comment]
I just tried with 

Brave | 0.69.94 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

Looks like it's not happening for what was originally showing in the gif above, but is happening for forward/backward/refresh buttons. Do you see that as well?
![1216](https://user-images.githubusercontent.com/28145373/62153280-38f57f00-b2d2-11e9-97f5-a791a27f253b.gif)

**Comment by kjozwiak** [comment]
@LaurenWags yup, noticed that on all the channels as well. You'll probably need to open a lot more tabs to reproduce https://github.com/brave/brave-browser/issues/1216#issue-362345979 as you'll need several tab separators.

Regarding the back/front and refresh button, assuming those become "inactive" whenever using drop downs like Rewards and Shields. Seeing the same thing happened with the light theme as well so this might be expected but we can definitely double check.

**Comment by LaurenWags** [comment]
oh, sorry, pulled the single tab out so there was less to look at. I can't reproduce originally reported issue with multiple tabs (still using 0.69.94):

![1216-tabs](https://user-images.githubusercontent.com/28145373/62158072-a3abb800-b2dc-11e9-88c3-e7a683e193ba.gif)

**Comment by kjozwiak** [comment]
Closing this off as I can't reproduce this anymore with the following build:

```
Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.3 (Build 19D76)
```

![Flash](https://user-images.githubusercontent.com/2602313/80181776-7c67ea00-85d3-11ea-8913-e97e4cf15b72.gif)
