### ISSUE TITLE
Rendering artifacts on WebGL/Webcanvas game Townstar

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#12167]
## Description 
Render issues on WebGL/Webcanvas game Townstar

## Steps to Reproduce

   1. Login to `https://app.gala.games/login?goto=%2F`
   2. Go to Games menu
   3. Play `Townstar`

## Actual result:
Rendering issues (with or without Hardware acceleration). See the blue `parallelograms` in screenshot

![farm-brave](https://user-images.githubusercontent.com/1659004/96196172-3b152d80-0fab-11eb-9544-3689e1c2f3ed.png)

## Expected result:
From Chrome: (see the "!" vs the blue boxs)
![farm-chrome](https://user-images.githubusercontent.com/1659004/96196215-54b67500-0fab-11eb-9402-b0f1dc0776bd.png)

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)` and `Version 1.17.32 Chromium: 86.0.4240.80 (Official Build) nightly (64-bit)`
Tested in Brave release, Beta and Nightly.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
was reported here: https://community.brave.com/t/beta-nightly-webgl-and-playcanvas-animation-bug-in-townstar/171662

![farm-brave-code](https://user-images.githubusercontent.com/1659004/96196284-829bb980-0fab-11eb-8c65-16425fe3e9bb.png)

Hardware acceleration made no differences, neither did Shields. Tested in Chrome Canary also, no issues.

**Comment by Brave-Matt** [comment]
Want to note that the game _does work and render without issue_ on macOS. Seems to only be Windows/Linux that have issues displaying the proper images.

**Comment by AerialJustice** [comment]
Problem is fixed in Nightly. Thanks team!

**Comment by bsclifton** [comment]
@ryanbr can you confirm in Nightly?

@pes10k was this likely fixed with https://github.com/brave/brave-core/pull/7026?

**Comment by ryanbr** [comment]
Game wasn't available to join (was time limited), @bsclifton  I'll try again later today/tomorrow.

**Comment by ryanbr** [comment]
Confirmed, fixed in Nightly. Artifacts no longer showing. @bsclifton  cc: @pes10k @Brave-Matt
