### ISSUE TITLE
Can't tip Github publisher when multiple contributers made commit

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#12175]
## Description 
When visiting the Github commits page for a project, if you attempt to tip a commit made by multiple authors it will fail. The message in the console shows `Uncaught (in promise) Error: Failed to parse DOM`.

## Steps to Reproduce

   1. Enable Rewards
   2. Visit https://github.com/zenparsing/zen-observable/commits/master or similar
   3. Find a commit with authored and committed messages, like "Kevin Smith authored and Kevin Smith committed"
   4. Tip the commit

## Actual result:

The tip dialog isn't displayed.

## Expected result:
Tip dialog should display as expected.

## Reproduces how often: 

100% of the time.

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by emerick** [comment]
Closing as this has been superseded by https://github.com/brave/brave-browser/issues/33783

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.87 Chromium: 120.0.6099.35 (Official Build) nightly (x86_64)
-- | --
Revision | e0cd7777fe0c2b5f4fe9e1bc27cedd1f87eac37f
OS | macOS Version 13.6.1 (Build 22G313)
```

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per discussion with @Miyayes
