### ISSUE TITLE
some versions of macOS do not show Brave icon after mounting dmg

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1217]
## Description 
Older versions of macOS (Sierra, El Capitan, Yosemite), do not show the Brave icon after the dmg file has been mounted.

## Steps to Reproduce

   1. On an older version of macOS (such as 10.12.6), download latest dmg file from GitHub (I used https://github.com/brave/brave-browser/releases/tag/v0.55.5). 
   2. Mount the dmg file. 

## Actual result:
Brave Browser Dev icon is not the branded one:
![screen shot 2018-09-20 at 5 10 39 pm](https://user-images.githubusercontent.com/28145373/45848383-2f87a780-bcfc-11e8-9751-c0bd0168a5ea.png)

## Expected result:
This is what you get when using 10.13.6:
<img width="448" alt="screen shot 2018-09-20 at 4 32 44 pm" src="https://user-images.githubusercontent.com/28145373/45848722-8c379200-bcfd-11e8-84b0-90f1e72b5074.png">

## Reproduces how often: 
Easily

## Brave version (chrome://version info)
I'm downloading 0.55.5.

### Reproducible on current release:
no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
@kjozwiak found that these versions reproduce the issue:
• `10.12.6 (Sierra)` - reproduced
• `10.11.6 (El Capitan)` - reproduced
• `10.10.5 (Yosemite)` - reproduced

Additionally, currently downloading from https://brave.com/download-dev/ downloads 0.55.3, which does **not** have this issue. 

Possible related issues:
https://github.com/brave/brave-browser/issues/1105
https://github.com/brave/brave-browser/issues/1101
https://github.com/brave/brave-core/pull/437

cc @rossmoody

**Comment by LaurenWags** [comment]
Verified passed on 10.12.6 x64

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

![screen shot 2018-09-27 at 3 38 11 pm](https://user-images.githubusercontent.com/28145373/46170339-7e3cc080-c26b-11e8-8b68-60efc9c3571a.png)

cc @kjozwiak to check older versions

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.10.5 x64` - **PASSED**

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
--|--
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

<img width="1208" alt="screen shot 2018-09-28 at 12 00 00 am" src="https://user-images.githubusercontent.com/2602313/46187505-ee6e3500-c2b1-11e8-9451-32d470eb530e.png">

Went through verification using the following build under `macOS 10.11.6 x64` - **PASSED**

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
--|--
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

<img width="1123" alt="screen shot 2018-09-28 at 12 07 28 am" src="https://user-images.githubusercontent.com/2602313/46187673-be736180-c2b2-11e8-8227-896e78fdda1a.png">

Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
--|--
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

<img width="1036" alt="screen shot 2018-09-28 at 12 10 16 am" src="https://user-images.githubusercontent.com/2602313/46187725-fb3f5880-c2b2-11e8-968b-c687413bac68.png">

**Comment by kjozwiak** [comment]
@bbondy @rebron looks like we're not supporting OSX 10.9.5. I'm assuming we inherited this from Chromium which is expected. However, even though it's not supported and the icon has a `X` over it, you can still move the application to wherever.

I personally don't think this is an issue because we can't really stop folks from moving a executable. but wanted to check with you guys. You can move it around, but won't be able to launch it.

<img width="1129" alt="screen shot 2018-09-27 at 11 33 49 pm" src="https://user-images.githubusercontent.com/2602313/46187811-74d74680-c2b3-11e8-9142-6236de962a83.png">

**Comment by bbondy** [comment]
Possible to compare to Chromium or Chrome?
