### ISSUE TITLE
Add QR code for iOS to scan

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#12176]

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.16.67 Chromium: 86.0.4240.111 (Official Build) (x86_64)
Revision	b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6878

- launched above using the following flags/switches:

```
--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --rewards=staging=true
```

- enabled rewards and noted the paymentId via the terminal/CLI as per the following:

```
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/brave
> Result: Success
> HTTP Code: 201
> Body: {"paymentId":"4979742b-d0b8-4ee1-923e-5e8d1e9dd1c7","walletProvider":{...............
```

- confirmed above `paymentId` matches brave://rewards-internals:

<img width="441" alt="internals-SS" src="https://user-images.githubusercontent.com/28145373/96878543-fb39c480-1448-11eb-9dd6-627a1f509bc5.png">

- on brave://rewards page, clicked on `QR Code` and confirmed it matches the above `paymentId`:

![QR1](https://user-images.githubusercontent.com/28145373/96878557-fe34b500-1448-11eb-82d0-dabf1927662f.png)

- confirmed clicking on `QR Cod`e opens the modal with the QR code
- confirmed clicking on X closes the modal without issues

- Confirmed QR code updates to expected paymentId when restoring a wallet via https://github.com/brave/brave-browser/issues/12232#issuecomment-714493156
