### ISSUE TITLE
[bugs] previous searches showing when clicking url bar

### ISSUE THREAD

**Issue by Sujan319** [brave/brave-browser#12188]
## Description 

Whenever tapping url bar it shows previous searches.if someone else have using my browser he/she can easily see my searches which is not good for privacy.also these searches i dont want to see everytime i click the url bar.please remove these.
## Steps to reproduce 

   1. Open brave
   2. Go to url bar & click
   3. See your previous searches listing below(provided you have done enough searches) or you can search multiple times then comeback and repeat process 1 and 2.

## Actual result 
![Screenshot_20201017-162523](https://user-images.githubusercontent.com/67813061/96335766-89ecc100-1098-11eb-80ab-773d8671c7a7.png)

## Expected result
![Screenshot_20201017-163849](https://user-images.githubusercontent.com/67813061/96335755-70e41000-1098-11eb-9c46-132f0a4b6e91.png)

## Issue reproduces how often 
Easily reproduced everytime.

These happening for only google search engine.if i make other search engine default then the listing of previous searches are not showing.

**Comment by srirambv** [comment]
cc: @SergeyZhukovsky

**Comment by anthonypkeane** [comment]
Hi @Sujan319 thanks for reporting. 
There is a setting in Google to disable search history that should help you. This isn't a bug on Brave.
