### ISSUE TITLE
 Google login buttons option crashes Brave on windows 10

### ISSUE THREAD

**Issue by ZOASR** [brave/brave-browser#12182]
## Description 
When trying to disable the "Allow google login buttons on third party sites"  under the "Social media blocking" section in brave settings Brave crashes and all its processes crash completely.

## Actual result:
![problem](https://user-images.githubusercontent.com/44146518/96321914-66356680-1017-11eb-9a85-2e2bb0be7258.gif)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave: 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
Revision: 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS: Windows 10 OS Version 1903 (Build 18362.30)

## Version/Channel Information:
I haven't tested this on the other channels but it happens on the official release channel

**Comment by ZOASR** [comment]
**Issue still not fixed in:**
Brave | 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --

**Comment by rebron** [comment]
@ZOASR When you get a chance can you go to brave://crashes/ send the report and paste the crash report ID in this issue?

**Comment by rebron** [comment]
cc: @iefremov

**Comment by ZOASR** [comment]
@rebron  I'm not if this is the crash id or not:
``Local Crash Context:	0906c5d3-202f-446f-a0ea-38c7d9e98d16``

**Comment by ZOASR** [comment]
Brave is updated again with a new chromium version and the issue is still not fixed:

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}

**Comment by iefremov** [comment]
Hi @ZOASR , do you have any more entries on `brave://crashes`?

**Comment by ZOASR** [comment]
@iefremov Unfortunatley i had automatic crash reports turned off, so i had to re-enable it manually and upload this specific report

**Comment by iefremov** [comment]
@ZOASR could you please reproduce a few more times and upload the reports? This one had corrupted stack so it is hard to extract anything useful

**Comment by ZOASR** [comment]
@iefremov will do, do i need to provide crash ID's for the newly produced ones?

**Comment by iefremov** [comment]
yep!

**Comment by ZOASR** [comment]
@iefremov Here are some new crash report ID's:
***
91090000-cfc2-4f05-0000-000000000000
8e090000-cfc2-4f05-0000-000000000000
8a090000-cfc2-4f05-0000-000000000000
89090000-cfc2-4f05-0000-000000000000
***

**Comment by iefremov** [comment]
Thanks @ZOASR ! These ones are terrific 
@bridiver JFYI 
https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3D%2289090000-cfc2-4f05-0000-000000000000%22%2C_deleted%3D0%2C(ver%2Cregex%2C%228%5B2%7C3%7C4%7C5%7C6%5D.*%22))&debug=(b8aa84,0,0)

**Comment by scottrbaxter** [comment]
Confirmed crash is happening on macOS Catalina 10.15.7 as well.

`Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (x86_64)`

**Comment by jumde** [comment]
@scottrbaxter - Could you please share the `Local Crash Context` for this crash-id in brave://crashes? Thanks!

**Comment by scottrbaxter** [comment]
@jumde I'd like to go over that info before submitting, but am not sure how to view exactly what's being sent. Could you point me to where in the docs I can read up on how to view it locally, before sending?

**Comment by ZOASR** [comment]
@scottrbaxter I'm not sure if this is the correct docs but i think this is how you view the contents of a crash:
[https://www.chromium.org/developers/crash-reports](url)

**Comment by scottrbaxter** [comment]
Thanks @ZOASR. As I'm seeing this crash on macOS, I did look through Crashpad, but don't see any files in `~/Library/Application\ Support/Chromium/Crashpad/completed`, as stated in the Crash Reports link you provided. I also quickly looked through Console.app, but don't see any Brave references around the time(s) that match up with the crashes I see in `brave://crashes/`. Seems strange that the crash report data would be this difficult to find... I would prefer to view what data is being submitted, prior to sending.

**Comment by scottrbaxter** [comment]
Hmm, tried replicating the crash again today, and am not experiencing it. I don't see a Brave.app update, confirmed I'm still on `Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (x86_64)`; macOS `10.15.7`. No changes with Brave (Chrome Web Store) Extensions installed... though I did reboot since the last time I replicated this issue, but not much else has changed since.

**Comment by ZOASR** [comment]
Issue is fixed in V1.17.73 without any mention in the release notes

**Comment by bridiver** [comment]
@ZOASR there is no mention in the release notes because we're not aware of any fix. Could be an upstream change or some other change that incidentally fixed it

**Comment by ZOASR** [comment]
> we're not aware of any fix. Could be an upstream change or some other change that incidentally fixed it

@bridiver I thought so , but we won't know if it is fixed or not until somone tries it on all platforms
