### ISSUE TITLE
My Newtab BraveRewards doesnt show earnings monthly, its been a month but still its 0.00

### ISSUE THREAD

**Issue by BroJenuel** [brave/brave-browser#12189]
## Description 

when I open brave, and shows this tab were I can see the brave rewards estimated earnings. Its been a month but doesn't show anything. It is still 0.00.

## Actual result:

![Screenshot 2020-10-18 205249](https://user-images.githubusercontent.com/31676163/96368060-35bf0b00-1184-11eb-938f-5ed9f14f6b61.png)

## Expected result:
It should show something, not 0.00 but at least greater than 0.00.

## Reproduces how often: 

This happens to me all the time.

## Brave version (brave://version info)

Brave	1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
Revision	002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS	Windows 10 OS Version 2004 (Build 19041.572)
JavaScript	V8 8.6.395.13
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=MixedContentSiteSetting,PrefetchPrivacyChanges,LegacyTLSEnforced,DnsOverHttps,OmniboxContextMenuShowFullUrls,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,PassiveMixedContentWarning,WinrtGeolocationImplementation --disable-features=PrivacySettingsRedesign,TextFragmentAnchor,NotificationTriggers,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,SmsReceiver,TabHoverCards,SafeBrowsingEnhancedProtection,VideoPlaybackQuality,AutofillServerCommunication,PasswordCheck --flag-switches-begin --flag-switches-end
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\jenue\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-4113a79e

**Comment by thefallofbecause** [comment]
If you go into your Rewards settings how many ad notifications does it say you have received? If you haven't received any ads in the month then zero would be the correct value for your estimated earnings.

**Comment by BroJenuel** [comment]
> If you go into your Rewards settings how many ad notifications does it say you have received? If you haven't received any ads in the month then zero would be the correct value for your estimated earnings.

![image](https://user-images.githubusercontent.com/31676163/96526743-0bb73700-12b1-11eb-91af-4875809a4650.png)

**Comment by thefallofbecause** [comment]
Click on the triangle BAT icon in the address bar, then click Rewards Settings. What number do you see under "Ad notifications received this month"?

The ads you receive from Brave appear as system notifications, and these are the ads you receive BAT for. You do not receive BAT for the ads & trackers that are blocked by the system.

**Comment by BroJenuel** [comment]
oh I see now,, thanks thanks, but may I ask what is the purpose of this then? bug?
![image](https://user-images.githubusercontent.com/31676163/96659942-e4c53780-137a-11eb-8b3a-809a5bebb30a.png)

**Comment by thefallofbecause** [comment]
The Brave Rewards widget is there by default on the new tab page. You can hide it if you want by clicking on the 3 dots then selecting Hide Brave Rewards.

**Comment by tmancey** [comment]
@BroJenuel Are you still experiencing this issue please? Thanks

**Comment by BroJenuel** [comment]
Hi, Yeah... I think there is a problem with the widget but it is fine now, I can see it here 
![image](https://user-images.githubusercontent.com/31676163/96803230-4b5f5980-143e-11eb-83d2-f8f4cee4229c.png)

**Comment by tmancey** [comment]
@BroJenuel if you could email me a screenshot of the widget and the brave://rewards screen to tmancey@brave.com I can investigate further, thanks

**Comment by BroJenuel** [comment]
> @BroJenuel if you could email me a screenshot of the widget and the brave://rewards screen to tmancey@brave.com I can investigate further, thanks

Sure thanks thanks, ill send it today,, 😊

**Comment by tmancey** [comment]
@BroJenuel Closing issue as resolved with 1.15.75 and issue due to ad inventory exceeding max.
