### ISSUE TITLE
chrome://flags/ shows that Hyperlink auditing is enabled

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1218]
## Steps to Reproduce

   1. Go to chrome://flags/
   2. Search for Hyperlink auditing

## Actual result:

According to #764 Hyperlink is disabled, but it is shown as enabled in chrome://flags/.
![image](https://user-images.githubusercontent.com/34715963/45849959-6679af80-bd34-11e8-870c-a3f99f80f61e.png)

## Expected result:
Hyperlink auditing should be disabled in chrome://flags/  to reflect reality

## Reproduces how often: 

always

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

cc @simonhong @jumde @diracdeltas

**Comment by rebron** [comment]
Not a dupe, display issue in chrome://flags

**Comment by rebron** [comment]
Closing. `brave://flags/#disable-hyperlink-auditing` no longer exists.
