### ISSUE TITLE
[Android] Tapping 'X' on Site settings pages doesn't do anything

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#12181]
## Description 
On Android, visiting any `Site Setting` page (ex. `Menu --> Settings --> Site settings --> Javascript`) and tapping the `x` on the top right of the page does not close out the menu as intended. Currently, the button is not functional and seems to do nothing. This happens for all pages inside `Site Settings`.

## Steps to reproduce 

   1. Launch Brave
   2. Visit  `Menu --> Settings --> Site settings --> Javascript` or some other Site Setting page
   3. Tap `x` on the top right

## Actual result 
Nothing happens.

## Expected result
Menu should close out.

## Issue reproduces how often 
Easily/every time.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
Yes
- Can you reproduce this issue with the current Play Store Beta version? 
Yes 
- Can you reproduce this issue with the current Play Store Nightly version?
Yes
## Device details
(Several)
   - Install type (ARM, x86): 
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 10
   
## Brave version
v1.15.73

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

### Additional information

![xnoworky](https://user-images.githubusercontent.com/3299098/96319550-d797f980-0fc4-11eb-884e-df3381993398.png)

**Comment by alexsafe** [comment]
Solved by https://github.com/brave/brave-core/pull/8372

**Comment by stephendonner** [comment]
Verified `FIXED` using Brave - Beta `1.24.76, Chromium 90.0.4430.85` on Android 9.

Steps:

1. Launched Brave
2. Tapped on the 3-dots menu, --> `Settings` --> `Site settings` --> `JavaScript`
3. Tapped `X` on the top right

Confirmed the Site Settings page closed, and I was returned to the new-tab page.

example | example | example
---------|----------|---------
![Screenshot_20210428-145712](https://user-images.githubusercontent.com/387249/116478196-906fa880-a832-11eb-8d4f-93daa12c9ba5.png) | ![Screenshot_20210428-145718](https://user-images.githubusercontent.com/387249/116478220-982f4d00-a832-11eb-8549-26fe2f002966.png) | ![Screenshot_20210428-145722](https://user-images.githubusercontent.com/387249/116478241-a0878800-a832-11eb-9447-561d3fae5e43.png)
