### ISSUE TITLE
Visiting https://auspost.com.au/shop/product/personalised-mug-30001517 causes tab crash

### ISSUE THREAD

**Issue by msbit** [brave/brave-browser#12191]
## Description

Visiting https://auspost.com.au/shop/product/personalised-mug-30001517 causes tab crash

## Steps to reproduce

   1. Visit https://auspost.com.au/shop/product/personalised-mug-30001517

## Actual result

![2020-10-19 16 41 19](https://user-images.githubusercontent.com/1694533/96406073-69547080-122a-11eb-9ebc-a025d8e2e4e9.png)

## Expected result

Page to load

## Issue reproduces how often

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
Yes

- Can you reproduce this issue with the current Play Store Beta version? 
Unsure

- Can you reproduce this issue with the current Play Store Nightly version?
Unsure

## Device details
   - Install type: ARM
   - Device type: Phone
   - Android version: 11 (Pixel 3, build number RP1A.201005.004)
   
## Brave version

Brave 1.15.73, Chromium 86.0.4240.75

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
No

- Does the issue resolve itself when disabling Brave Rewards?
Unsure

- Is the issue reproducible on the latest version of Chrome? 
Yes

### Additional information
Relevant logcat stuff seems to be:

```
F chromium: [FATAL:memory_linux.cc(37)] Out of memory.
E chromium: [1019/162913.202632:ERROR:process_memory_linux.cc(42)] open: No such file or directory (2)
...
E chromium: [1019/162914.047412:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)
E chromium: [1019/162914.048420:ERROR:ptrace_client.cc(378)] Broker Open: access denied
E chromium: [1019/162914.164489:ERROR:socket.cc(182)] incorrect payload size 0
E libc    : failed to connect to tombstoned: Operation not permitted
F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
F DEBUG   : Build fingerprint: 'google/blueline/blueline:11/RP1A.201005.004/6782484:user/release-keys'
F DEBUG   : Revision: 'MP1.0'
F DEBUG   : ABI: 'arm'
F DEBUG   : Timestamp: 2020-10-19 16:29:14+1100
F DEBUG   : pid: 16855, tid: 16895, name: essService0:105  >>> com.brave.browser:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:105 <<< 
F DEBUG   : uid: 90005
F DEBUG   : signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
F DEBUG   : Abort message: '[FATAL:memory_linux.cc(37)] Out of memory.
F DEBUG   : ' 
F DEBUG   :     r0  00000000  r1  00000000  r2  7fffffff  r3  00000000
F DEBUG   :     r4  db4f0f94  r5  db4f0f94  r6  c9166ea8  r7  f1c24b24
F DEBUG   :     r8  db4f13e4  r9  db4f13f0  r10 db4f13ec  r11 0000002a
F DEBUG   :     ip  db4f0f50  sp  db4f0f80  lr  f1c16c33  pc  c7363e7c
F DEBUG   :
F DEBUG   : backtrace:
F DEBUG   :       #00 pc 01af4e7c  /data/app/~~3eudX9eqfCoRlk1uv_kBFw==/com.brave.browser-GJPPxqOrDpMc0a1SQqYMWw==/base.apk!libmonochrome.so (offset 0x5570000) (BuildId: 1a773bc3e250c74b8a4a0937cfcc05a6807c1d52)
```

**Comment by kjozwiak** [comment]
@msbit does this still happen with the latest version from GPS? I tried reproducing the issue with `1.16.70 CR: 86.0.4240.111` but couldn't reproduce. Mind trying again if you have some time. Are you still seeing the issue?

**Comment by msbit** [comment]
Hey @kjozwiak, I can confirm that this page no longer crashes the tab under Brave 1.16.74 or Chrome 86.0.4240.185, so looks like this can be closed! Thanks for checking on the issue.

**Comment by bsclifton** [comment]
Thanks for confirming, @msbit 😄
