### ISSUE TITLE
Auto-contribute failing every month with "There was a problem processing your contribution."

### ISSUE THREAD

**Issue by mhatvan** [brave/brave-browser#12195]
## Description 

All the verified sites in my auto-contribution list don't seem to receive any BAT, including my own verified website and GitHub account. 

The auto-contribution fails on the day of payout with "There was a problem processing your contribution." without any further details and then displays the date for the payout of the next month.

BAT earned from watching ads work fine and get transfer to Uphold.

## Steps to Reproduce

   1. visit websites througout the month
   2. expect them to get auto-contributions
   3.  "There was a problem processing your contribution." on the day of payout

## Actual result:

No BAT are sent to verified sites

## Expected result:
Verified sites should receive BAT

## Reproduces how often: 

Every month

## Desktop Brave version:

1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
Linux

**Comment by mhatvan** [comment]
Update: Additionally, all the sites I viewed previously that were in the auto-contribute section disappear and I have to revisit them to show up again.

**Comment by hollons** [comment]
Thanks for reporting @mhatvan. When you have a moment, can you update to 1.17.73 and see if the issue persists?

**Comment by mhatvan** [comment]
I am using 1.17.73 currently and can report more on Dec 18, when the auto contribution occurs again!

**Comment by mhatvan** [comment]
@hollons Running Brave v1.18.70 and it still doesn't work. My wallet got randomly deactivated today (probaby due to paydate) and I had to reconnect it on Uphold.
Auto-contribute section lost all previous visited websites and no payout happened.
