### ISSUE TITLE
WebTorrent not loading due to "Unchecked runtime.lastError: Could not establish connection" error

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12196]
## Description 

Looks like WebTorrent has regressed in Nightly. Whenever clicking on a `.torrent` or `.magnet` link, you'll get a blank page with the following error in the browser console:

```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
brave_webtorrent.html:1 
```

## Steps to Reproduce

**`Case 1`**

   1. install the latest Nightly (`1.17.40 CR: 86.0.4240.99` in this case)
   2. attempt to use WebTorrent by clicking on `.torrent` or `.magnet` links via https://webtorrent.io/free-torrents

**`Case 2`**

   1. install the latest Nightly (`1.17.40 CR: 86.0.4240.99` in this case)
   2. attempt to load https://releases.ubuntu.com/20.04/ubuntu-20.04.1-desktop-amd64.iso.torrent

## Actual result:

<img width="1207" alt="Screen Shot 2020-10-19 at 12 55 29 PM" src="https://user-images.githubusercontent.com/2602313/96488285-bbd26480-120b-11eb-93c6-2b573ee476e1.png">

## Expected result:

<img width="1204" alt="Screen Shot 2020-10-19 at 1 05 31 PM" src="https://user-images.githubusercontent.com/2602313/96488407-f0462080-120b-11eb-8b4e-b5ed4e34c88d.png">

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.17.40 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.15.7 (Build 19H2)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel?  `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @bsclifton @feross @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on

Brave | 1.17.40 Chromium: 86.0.4240.99 (Official Build) nightly (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.17.40 Chromium: 86.0.4240.99 (Official Build) nightly (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Ubuntu 18.04

![image](https://user-images.githubusercontent.com/34715963/96488670-a1fe4500-123e-11eb-88ad-e6a3128eb5c8.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.17.42 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.15.7 (Build 19H2)
```

* Verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/12196#issue-724805514
* ensured that both `.torrent` & `.magnet` links worked without issues
* ensured that `Save All Files..` worked without any issues

**`.torrent`** | **`.magnet`**
--------------|----------------
<img width="1670" alt="Screen Shot 2020-10-20 at 12 04 16 AM" src="https://user-images.githubusercontent.com/2602313/96539202-890a8980-1268-11eb-8413-d12bb420b475.png"> | <img width="1667" alt="Screen Shot 2020-10-20 at 12 06 50 AM" src="https://user-images.githubusercontent.com/2602313/96539213-8f006a80-1268-11eb-93ab-cc9fe1811349.png">
