### ISSUE TITLE
Misplaced BAT logo

### ISSUE THREAD

**Issue by saberistic** [brave/brave-browser#12200]
## Description 
Noticed a BAT logo hanging in GH Access page of a repo on nightly.
![image](https://user-images.githubusercontent.com/4715448/96495850-72d3dd80-1216-11eb-90cc-35565971989d.png)

## Steps to Reproduce

   1. Visit Settings Tab of a repo
   2. Navigate to Manage Access page

## Expected result:
Asked @NejcZdovc shouldn't be there.

## Reproduces how often: 
Everytime

## Brave version (brave://version info)

Brave | 1.17.40 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.15.7 (Build 19H2)
JavaScript | V8 8.6.395.13
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36
Command Line | /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=PasswordImport,ReducedReferrerGranularity,MixedContentSiteSetting,AutoupgradeMixedContent,PassiveMixedContentWarning,PrefetchPrivacyChanges,GlobalPrivacyControl,WebUIDarkMode,LegacyTLSEnforced,OmniboxContextMenuShowFullUrls,DnsOverHttps --disable-features=AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,TextFragmentAnchor,VideoPlaybackQuality,SafeBrowsingEnhancedProtection,NotificationTriggers,AutofillServerCommunication,PasswordCheck,PrivacySettingsRedesign,SmsReceiver,TabHoverCards --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly
Profile Path | /Users/amirsaber/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Default

## Version/Channel Information:
Version 1.17.40 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)

**Comment by mkarolin** [comment]
I can no longer reproduce this with `1.48.29` (Nightly). 
@brave/qa-team, please advise if we can close this if no longer reproducible.
