### ISSUE TITLE
Educational in-product notification

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#12209]
## Description
Please search for the spec "Educational in-product notification" for details

The issue for iOS: https://github.com/brave/brave-ios/issues/2980

## Designs
![image](https://user-images.githubusercontent.com/2388823/105229608-10da8b00-5b19-11eb-9962-a8ad29b6f43b.png)

## Assets
Figma: https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/?node-id=1384%3A0

### Q/A
1. we have already released first pink orange tooltip. so in that case, should we reset the preference for the existing user or we shouldn't show it for existing user ? **Answer** : we shouldn't show it.
2. Should we show the tooltip if the shields panel is already opened ? **Answer** : We shouldn't show any tooltip if the shields panel is opened.
3. What should happen if the tooltip is visible and user changes the orientation ? **Answer** : Since orientation change reloads the page and user has already seen the tooltip, we should close the tooltip.
4. Should tooltip be closed on back button pressed ? **Answer** : Yes
5. Should tooltip be closed by tapping outside of the tooltip area ? **Answer** : Yes

### Notes
In case more than 1 condition is satisfied simultaneously, the notifications should be prioritised:
1. pink orange initial intro tooltip
2. Video ads blocked
3. 10+ trackers & ads
4. Connection encrypted
We only show the tooltips one at a time. so during the same app open session, user should see only one tooltip. and user should see any of the tooltips only once.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.100 x64 build
- Verified test plan from issue description
- Verified only one tooltip is shown at a time even when multiple conditions are met
- Verified tooltip is dismissed when orientation is changed
- Verified tooltip is dismissed when tapped outside the notification area
- Verified tooltip is dismissed when back button is pressed 

Ads/Trackers blocked (Pink-orange) | Video Ads blocked (Blue) | 10+ Trackers blocked (Blue) | Encrypted Connection (Blue)
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107219203-a8d8df80-6a08-11eb-91b3-89fca044f75e.png) | ![image](https://user-images.githubusercontent.com/17010094/107219218-ad04fd00-6a08-11eb-9c91-902abb4a5d65.png) | ![image](https://user-images.githubusercontent.com/17010094/107219230-b1c9b100-6a08-11eb-80e6-3fb13d927d7b.png) | ![image](https://user-images.githubusercontent.com/17010094/107219279-c1e19080-6a08-11eb-95ec-2aa4046c3441.png)

- Encountered #13892
-----------
Verification passed on Samsung Tab A with Android 10 running 1.20.100 x64 build
- Verified test plan from issue description
- Verified only one tooltip is shown at a time even when multiple conditions are met
- Verified tooltip is dismissed when orientation is changed
- Verified tooltip is dismissed when tapped outside the notification area
- Verified tooltip is dismissed when back button is pressed 

Ads/Trackers blocked (Pink-orange) | Video Ads blocked (Blue) | 10+ Trackers blocked (Blue) | Encrypted Connection (Blue)
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107220180-f570ea80-6a09-11eb-982a-24b455d3c2a2.png) | ![image](https://user-images.githubusercontent.com/17010094/107220220-fd308f00-6a09-11eb-8ab1-5fc46e4f27b4.png) | ![image](https://user-images.githubusercontent.com/17010094/107220233-015cac80-6a0a-11eb-8714-8b997f0b6338.png) | ![image](https://user-images.githubusercontent.com/17010094/107220304-18030380-6a0a-11eb-8f4c-277138b8644b.png)

- Encountered #13892
-----------
