### ISSUE TITLE
[Widget] Update widget to opt-in state in widget gallery to match other widgets

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12212]
## Description 

Update widget to opt-in state in widget gallery to match other widgets

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

Binance | Bitcoin.com | Gemini | Rewards | Crypto.com
-- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/96554754-df022000-12ae-11eb-810e-4fb680c4a0bd.png) | ![image](https://user-images.githubusercontent.com/17010094/96554771-e32e3d80-12ae-11eb-98eb-3316b751bd22.png) | ![image](https://user-images.githubusercontent.com/17010094/96554791-e7f2f180-12ae-11eb-8ed1-cf4947261232.png) | ![image](https://user-images.githubusercontent.com/17010094/96554804-ecb7a580-12ae-11eb-9a3f-4aa9e2a726a2.png) | ![image](https://user-images.githubusercontent.com/17010094/96554819-f17c5980-12ae-11eb-915e-e0d07f36b8d1.png)

## Expected result:
Should match all other widgets in the gallery

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.17.40 Chromium: 86.0.4240.99 (Official Build) nightly (64-bit)
-- | --
Revision | `002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}`
OS | Linux

# Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @ryanml

**Comment by ryanml** [comment]
Closing per weekly meeting discussion
