### ISSUE TITLE
Rewards Tip Floating Dialog

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#1221]
Web-ui dialog
- Similar to the certificate white popup when you click on Secure next to an https site.
- Can be fully customized with a webui content (html/js).
- Can specify location dynamically and can change it dynamically
- Support an api to dismiss it
- Can specify size
- Dismissed if the user clicks outside of it

<img width="655" alt="screen shot 2018-09-05 at 1 26 06 pm" src="https://user-images.githubusercontent.com/6786187/45856032-cf414600-bd8d-11e8-86f4-0efaea7dded2.png">
<img width="632" alt="screen shot 2018-09-05 at 1 26 10 pm" src="https://user-images.githubusercontent.com/6786187/45856037-d5cfbd80-bd8d-11e8-9f09-69d533386477.png">

**Comment by petemill** [comment]
Looks like there's two levels of API needed:

1. Open Popup for a tab. 
This is to enable direct donation to a site that is open in a tab.
Url: `chrome://donate`
Params needed: site origin
Invocation source: c++ (backend of an extension popup, or a menu)

2. Open Popup for a portion of WebContents.
This is to enable direct donation to a _user of_ a site that is open in a tab.
Url: `chrome://tip`
Params needed: site origin (twitter), content creator (e.g. twitter handle), DOM element (for position anchor)
Invocation source: Javascript, inside a content script

Therefore we can implement two levels of API:
## Static c++ (Donate and Tip)
`static DonationDialogController::Donate(WebContents* initiator)`
`static TipDialogController::Tip(WebContents* initiator, Rect element_bounds)`
- follows the pattern of [`PrintPreviewDialogController`](https://cs.chromium.org/chromium/src/chrome/browser/printing/print_preview_dialog_controller.cc?type=cs&sq=package:chromium&g=0&l=175)
- implements `ui::WebDialogDelegate`
- positions the dialog and handles opening and closing

## Javascript DOM (Tip)
`js: brave.rewards.showContentCreatorTipDialog(creatorName, element)`
- Instantiated from content script which modifies behavior of site's buttons (twitter like, facebook like, youtube ThumbsUp)
- Works loosely similar to Autofill - render receives command and calculates coordinates which are passed via IPC to browser client

**Comment by NejcZdovc** [comment]
@petemill for donate we need a lot more data. Will this data be fetched inside this dialog and we can use origin as to what data we need in the webui?

**Comment by petemill** [comment]
@NejcZdovc lots of data can be fetched from the `WebContents`, including origin. The WebUI can then have it's own API for actions and to fetch data from Rewards service. So I imagine everything you need unique to that invocation will be covered in the `WebContents` - do you agree with that?

**Comment by NejcZdovc** [comment]
yeah to get data from rewards service I only need origin. Based on that I can get all other data. Would it be possible to send in instead of origin publisher key? This way we don't need to calculate it from origin again?

**Comment by petemill** [comment]
@NejcZdovc that sounds possible if all triggers for the dialog know the Publisher Key. It is only the Rewards extension popup, and does that know it?

**Comment by NejcZdovc** [comment]
@petemill yeah they know that key. For other options you could always call rewards service that will return publisher key based on origin and then after that you trigger donate

**Comment by petemill** [comment]
Sure we can support both 👍. What about tipping @NejcZdovc? Will it be enough to have origin / publisherId and the site-specific creator name. E.g. twitter.com and @twitterusername ?

**Comment by NejcZdovc** [comment]
yup as long as we know to who this hear belong (twitter handler) we should be good

**Comment by petemill** [comment]
@rebron @mandar-brave please can we confirm which milestone we're currently targeting floating user tips, so I can prioritize work - is it still '1.0'?

**Comment by NejcZdovc** [comment]
@petemill it's targeted for 57 build

**Comment by petemill** [comment]
@NejcZdovc I'm going to unassign from myself for now since this can be achieved in the JS for the donate page. Whoever gets to this can call the dialog close JS after a timeout.

**Comment by petemill** [comment]
Just noting that we still don't have:
- A dialog which can:
  - Auto-size whilst being located in a specific position (though ConstrainedWebDialog is very close)
  - Have rounded borders via clipping the webview or via a transparent background, or a mix of native UI controls as well as the webview to achieve a similar look
  - Have custom shape (arrow pointing at popup anchor) via native UI controls
- An easy means of querying the DOM from the browser UI layer in order to get the dialog position, though this could be provided via JS content script.

**Comment by petemill** [comment]
[For Donate dialog I did use `ShowConstrainedWebDialogWithAutoResize`.](https://github.com/brave/brave-core/blob/master/browser/brave_rewards/donations_dialog.cc#L144) It's problems were:
- Could not overlay the rest of the content with a semi-transparent background (not a big priority though)
- Could not have it take 100% width of parent with auto-sized height
  - Can only give an autoresizing dialog **initial** min and max for both width and height, whereas we want to have a min and max for height, and a fixed width that **changes** on browser window resize. Whereas a non-auto-resize `ShowConstrainedWebDialog` can have its width and height changed at any time, but will not auto-resize. This fixed logic for _both_ width and height seems to go down to the render layer.
So for the Donate dialog, the main bug with this compromise only presents itself when resizing the browser window.

For the Tip dialog, we are considering using DOM injection for now, e.g. https://github.com/brave/brave-core/pull/1040

**Comment by petemill** [comment]
Just found an interesting precedent in blink for displaying an overlay on the webcontent which is native (and hence not part of the host DOM) but contains web content with a custom js api, as well as exactly the custom popup shape we're looking for: `InspectorOverlayPage`.

![image](https://user-images.githubusercontent.com/741836/51767752-22583c00-2093-11e9-9429-4f4ea508dc6e.png)

[InspectorOverlayAgent.cc](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/inspector/inspector_overlay_agent.cc?type=cs&q=%22InspectorOverlayPage%22&sq=package:chromium&g=0&l=950)
[InspectorOverlayPage.html](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/inspector/InspectorOverlayPage.html?type=cs&sq=package:chromium&g=0)

cc @simonhong @pilgrim-brave @davidtemkin 

(UX considerations aside)

**Comment by NejcZdovc** [comment]
closing as we implemented this in a different way
