### ISSUE TITLE
Click on twitter favicon in tipping banner redirects to an error page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12214]
## Description 

Click on twitter favicon in tipping banner redirects to an error page

## Steps to Reproduce

   1. Clean profile 1.17.x
   2. Enable rewards
   3. Open https://twitter.com/jonathansampson
   4. Open BR panel and click on `Send tip`
   5. Click on Twitter favicon in tipping banner

## Actual result:

Click on twitter favicon in tipping banner redirects to an error page
![image](https://user-images.githubusercontent.com/38657976/96583601-96705400-12fa-11eb-95e5-72ea85ed36b9.png)
![image](https://user-images.githubusercontent.com/38657976/96583624-a0925280-12fa-11eb-9743-b1ea01ac2e78.png)

## Expected result:
should not show any error message

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.17.42 Chromium: 86.0.4240.99 (Official Build) nightly (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Windows 10 OS Version 1903 (Build 18362.1082)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @NejcZdovc

**Comment by NejcZdovc** [comment]
this is not regression as the same thing happens for me on previous versions

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc I am getting an empty screen in Release channel 1.15.x

**Comment by NejcZdovc** [comment]
yes I get empty screen as well. Problem is that link that we get from server doesn't have https in front and because of that it will not open correctly. Checking with publisher team what to do

**Comment by zenparsing** [comment]
It seems reasonable to not display a social media link if the link is not a valid absolute URL. What do you think @NejcZdovc?

**Comment by NejcZdovc** [comment]
@zenparsing that would work yup. We should also fix it on publisher side

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the STR from the description
- Verified social media links are removed from tipping banners as per https://github.com/brave/brave-browser/issues/12214#issuecomment-713101865

![image](https://user-images.githubusercontent.com/38657976/99969538-9e6f5800-2dc0-11eb-9286-17985cd2e10c.png)
