### ISSUE TITLE
Can only log in to Google in private window

### ISSUE THREAD

**Issue by bwims** [brave/brave-browser#12215]
## Description 

Since today I can ONLY login to a google account in a PRIVATE window..  Any attempt in a normal tab results in "Something went wrong"

## Steps to Reproduce

   1. Open a google address in a tab
   2. sign in
   3. fail

## Actual result:

![sign1](https://user-images.githubusercontent.com/18516073/96593225-26a19f80-12e1-11eb-86b4-6cc3b492132f.jpg)
![sign2](https://user-images.githubusercontent.com/18516073/96593230-299c9000-12e1-11eb-9133-7addd39fd5db.jpg)
![sign3](https://user-images.githubusercontent.com/18516073/96593234-2bfeea00-12e1-11eb-92ff-7a7fb9d41751.jpg)

## Expected result:
What I get in a PRIVATE window.

![sign4](https://user-images.githubusercontent.com/18516073/96593246-302b0780-12e1-11eb-817e-a71b52a794c8.jpg)

## Reproduces how often: 

Every single time.

## Brave version (brave://version info)

Brave | 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Windows 10 OS Version 1903 (Build 18362.535)

## Version/Channel Information:

N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

I've tried disabling everything, all extensions, I don't use rewards, I can login fine with Chrome and MS Edge.

## Miscellaneous Information:

No idea!

**Comment by bwims** [comment]
As a last resort, I closed down my dozens of windows and dozens of tabs and rebooted.

Problem cleared.  But why?

**Comment by bsclifton** [comment]
@bwims did you have a Brave update pending? I believe there are circumstances which require you to exit/relaunch in order to pick up. That would be my guess. If that wasn't the problem, then my guess would be a lock (or similar) where the cookies are being written/read from?

Whatever the case, glad it's resolved - and thanks for the update 😄
