### ISSUE TITLE
Odd JavaScript Errors in Developer Tools

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#12217]
## Description 
Users observing the developer tools may see strange JavaScript errors, potentially unrelated to any of their own code. For example:

```console
VM91284:1 Uncaught TypeError: Cannot read property 'innerText' of null
    at <anonymous>:1:15
```

When the user clicks to examine the code which raised the exception, they see only the following:

```js
document.body.innerText
```

Alternatively, they may see the following:

```
TypeError: Cannot read property 'requestContent' of undefined
```

## Steps to Reproduce
Note: This issue is not very easy to reproduce; there definitely appears to be a race condition involved.
1. Navigate to https://sampson.codes/brave/bugs/innerText-of-null/
2. Open developer tools, and enable _break on exception_
3. Using CMD|Ctrl + R, refresh the page over and over until the page halts on an exception

## Actual result:
Exceptions are raised by code other than the user's.

## Expected result:
No exceptions are raised by any code other than the user's.

## Reproduces how often: 
Intermittent. Somewhat difficult to reproduce.

## Brave version (brave://version info)

Brave | 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
The test-URL above is not always quick to produce the error. @jonathansampson has another URL, which can be shared privately via Slack. If you're working on this, and would like a more consistent endpoint to test, please ping him.

**Comment by jonathansampson** [comment]
This code appears all throughout the Chromium codebase, but it looks like this particular instance is coming from an attempt to leverage the dom_distiller for page classification.

Source: [/browser/brave_ads/ads_tab_helper.cc](https://github.com/brave/brave-core/blob/0ff81df6d8577c397e49cb76d0e783b56e587ee0/browser/brave_ads/ads_tab_helper.cc#L76-L89)

```cpp
void AdsTabHelper::RunIsolatedJavaScript(
    content::RenderFrameHost* render_frame_host) {
  DCHECK(render_frame_host);

  dom_distiller::RunIsolatedJavaScript(
      render_frame_host, "new XMLSerializer().serializeToString(document)",
      base::BindOnce(&AdsTabHelper::OnJavaScriptHtmlResult,
                     weak_factory_.GetWeakPtr()));

  dom_distiller::RunIsolatedJavaScript(
      render_frame_host, "document.body.innerText",
      base::BindOnce(&AdsTabHelper::OnJavaScriptTextResult,
                     weak_factory_.GetWeakPtr()));
}
```

I suspect there is no `body` element at times, which causes the error. If this is the case, it may be appropriate to instead use optional chaining, like `document?.body?.innerText`.

**Comment by stephendonner** [comment]
Despite being unable to reproduce this using `1.15.75` (yet), I'm verifying using the inline testplan here, with build 

Brave | 1.26.47 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

At the very least:
1. the changes are inclusive and minimal
2. I can't reproduce the problem with this build, regardless, so we should be good

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-06-01 at 1 38 58 PM" src="https://user-images.githubusercontent.com/387249/120387417-c2b37080-c2de-11eb-965e-3bc27db5406f.png"> | <img width="1312" alt="Screen Shot 2021-06-01 at 1 39 04 PM" src="https://user-images.githubusercontent.com/387249/120387419-c34c0700-c2de-11eb-8bb0-e5b9528bf9b9.png">
