### ISSUE TITLE
Ads don't appear when browser not in use (Stable)

### ISSUE THREAD

**Issue by AkshayGaonkar19** [brave/brave-browser#12229]
## Steps to reproduce 

   1. Ads appear while browsing/using browser only. (Latest Version)
   2. No ads appear when not using browser.
   3. They don't even appear between 6 am to 9 pm.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Phone.
   - Android version: 9PKQ1.180904.001
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
Ads will only appear when we have the users' attention. This is working as expected. Thanks
