### ISSUE TITLE
Stopped getting ads after upgrading version

### ISSUE THREAD

**Issue by ibLeDy** [brave/brave-browser#12226]
## Description 

After upgrading to the latest version of Brave Browser i stopped getting ads. It happened before, and i fixed it by fully removing Brave and all it's files from the OS, in my case i'm using Linux and APT so i ran `sudo apt remove --purge brave-browser` and `rm -rf ~/.config/BraveSoftware/Brave-Browser` to fully remove it and then `sudo apt install brave-browser` to install it again, and i started getting ads again. A couple days ago i upgraded to `86.1.15.75` didn't got any ads since.

## Steps to Reproduce

   1. Upgrade version via APT
   2. Wait a couple days
   3. Get 0 ads

## Reproduces how often: 

Don't know when it started happening but i remember upgrading with every new version and getting ads without issues, that is a couple months back, maybe chromium 84 even.

## Brave version (brave://version info)

Brave | 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Linux 5.3.0-64-generic (Ubuntu 19.10)

**Comment by mattLLVW** [comment]
Same on Fedora.
Worst is "Show Sponsored Images" still show up but don't incease BAT balance.
Here is a relevant log on startup:
`[11762:11762:1020/225841.684279:ERROR:CONSOLE(1)] "Uncaught ReferenceError: brave_rewards is not defined", source: chrome://rewards/ (1)`

**Comment by rebron** [comment]
@ibLeDy Are you still seeing this issue on our latest 1.20.103 release?
cc: @tmancey

**Comment by tmancey** [comment]
@mattLLVW @ibLeDy would you be available for a screen-share so we can diagnose the issue, if so could you please email me direct at tmancey@brave.com with some available times (I am based in the United Kingdom) and I will send a Zoom meeting link. Thanks, Terry

**Comment by ibLeDy** [comment]
This issue is from a long time ago, I'm no using the same PC and I stopped using Brave a couple of months ago. 
I'm thinking about trying Brave again, and although I don't think it will face the same issue, I will gather some more info if I do.
