### ISSUE TITLE
Restore "Darken Websites" checkbox in themes setting

### ISSUE THREAD

**Issue by rodrigoswz** [brave/brave-browser#12235]
## Description 

In versions prior to Chromium v86 there was the `#darken-websites-checkbox-in-themes-setting` flag but unfortunately [it was removed by Google](https://www.androidpolice.com/2020/07/01/chrome-86-removes-the-last-remaining-website-forced-dark-mode-flag/). With this flag, it was possible for webpages to follow the system theme, so we had dark webpages only when Android Dark Mode was enabled.

## Steps to reproduce 

   1. Go to chrome://flags
   2. Search for #darken-websites-checkbox-in-themes-setting
   3. Note that the flag does not exist and consequently not even the checkbox in Themes setting

## Actual result 

Dark webpages do not respect device dark mode. "Darken Websites" checkbox does not exist in Brave Settings > Appearance > Theme > System default.

![image](https://user-images.githubusercontent.com/14058427/96657224-080acb00-1318-11eb-9692-f172477f75d6.png)

## Expected result

Dark webpages is activated only if the device's theme is in dark mode too. There should be a "Darken Websites" checkbox in Brave Settings > Appearance > Theme > System default.

![image](https://user-images.githubusercontent.com/14058427/96656783-fecd2e80-1316-11eb-8d03-d63e42360a0e.png)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version

Brave 1.15.75, Chromium 86.0.4240.99

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

### Additional information

+1 from Community: https://community.brave.com/t/save-the-dark-mode/144631

Fortunately [Bromite](https://github.com/bromite/bromite) has managed to keep this feature on current Chromium release, so maybe Brave can use the patch to do the same.

**Comment by srirambv** [comment]
You can enable the night mode switch under appearance which activates dark mode for web pages. 
![image](https://user-images.githubusercontent.com/17010094/96678817-61034f00-136a-11eb-98ac-b73eab4d9414.png)

**Comment by rodrigoswz** [comment]
Hey @srirambv, please reopen this issue, I know Night Mode switch and that's not what I explained here...

Night Mode switch simply activates the `#enable-force-dark` flag which forces all web content to use a dark theme, however this uses the dark theme all the time regardless of the theme of your device.

My issue is precisely this, I would like the flag `#darken-websites-checkbox-in-themes-setting` that was removed back in Brave so that the dark theme of the webcontents can be activated only when my device is in dark mode. As with Bromite, please install this and compare it with Brave if the question is still not understood.

**Comment by srirambv** [comment]
That option was not implemented by Brave but an experimental flag provided by Chromium which they have removed so we don't have control on the flags.

cc: @SergeyZhukovsky @samartnik  please reopen the issue if we want to re-implement this removed flag from Chromium.
