### ISSUE TITLE
QR code not being updated when restoring wallet

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12232]
## Description 

Original QR isn't being updated when restoring wallets via `brave://rewards`. Scanning the QR code will always display the original `paymentId` when the wallet was initially created.

## Steps to Reproduce

   1. launch `1.17.43 CR: 86.0.4240.99` via terminal (used staging in this case)
   2. create a wallet and note the `paymentId` via the terminal/CLI
   3. click on the `QR code` button and scan it with a mobile device (`paymentId` should match)
   4. restore another wallet via `brave://rewards` using `Restore` under the `Manage your wallet` modal.
   5. click on `QR code` and you'll notice that the first initial `paymentId` is being used
   6. refresh `brave://rewards` you'll notice that the first initial `paymentId` is being used
   7. restart the browser and you'll notice that the first initial `paymentId` is being used

## Actual result:

`QR code` should be using the correct `paymentId` when restoring wallets

## Expected result:

`QR code` is using the first initial `paymentId` and isn't being updated when restoring new wallets

## Reproduces how often: 

100% reproducible when using the above STR.

## Brave version (brave://version info)

```
Brave | 1.17.43 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.15.7 (Build 19H2)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `N/A`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @NejcZdovc @mandar-brave @rebron

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.16.67 Chromium: 86.0.4240.111 (Official Build) (x86_64)
Revision	b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS	macOS Version 10.14.6 (Build 18G3020)
```

- Verified test plan from description
- Confirmed restoring multiple wallets changes the QR code and matches `paymentId` under `brave://rewards-internals`
- Confirmed the QR code persists when: restarting browser, closing/re-opening `brave://rewards`, refreshing `brave://rewards`
- Encountered and logged https://github.com/brave/brave-browser/issues/12274
