### ISSUE TITLE
Improve DAU estimation quality in stats and p3a

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12233]
* **`PR`** --> https://github.com/brave/brave-core/pull/6660
* **`QA Cases`** --> https://github.com/brave/internal/issues/733 (please keep results within internal issue)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.69 
- Verification notes https://github.com/brave/internal/issues/733#issuecomment-728813800
