### ISSUE TITLE
Cast help link points to community.brave.com

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1223]
## Steps to Reproduce

   1. Right click on a page
   2. Click on `Cast`
   3. Choose `Cast tab`
   4. Click `No Cast destinations found. Need help?`

![image](https://user-images.githubusercontent.com/34715963/45865245-24289080-bd7d-11e8-8bf2-906aea5bff4d.png)

## Actual result:

Generic `https://community.brave.com/` is opened

## Expected result:
Page with actual help for Cast feature is opened

## Reproduces how often: 
always

## Brave version (chrome://version info)

 
Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

cc @yrliou @bridiver @kjozwiak 

Related to #377

**Comment by srirambv** [comment]
All support/learn more links are being redirected to https://community.brave.com/.
