### ISSUE TITLE
Default search should be versioned

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#12231]
## Description 
Right now, there's not a way to tell what the default search engine was when the user's profile was created.
If the default is changed, anyone who has not set the search engine explicitly will get the NEW default.

## Steps to Reproduce

   1. Fresh profile
   2. Take note of the default search engine Brave uses when searching on regular window/tabs (ex: Google)
   3. Have a developer update the code to change the default for that region (ex: Bing)

## Actual result:
It doesn't matter if person had been using the default. The new default will be used instead (ex: Bing). The only way the value is retained is when they have changed the default explicitly

## Expected result:
If user profile has existed for a while, the original provider for default search engine should be preserved (ex: Google in this case)

## Reproduces how often: 
100%

**Comment by LaurenWags** [comment]
Desktop can be tested via test plan in https://github.com/brave/brave-core/pull/7090, however pending Android specific test plan from @bsclifton 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from https://github.com/brave/brave-core/pull/7090 (some verification were done in https://github.com/brave/brave-browser/issues/12327)

Verified **Russia** on upgraded profile from 1.17.x
On 1.17.x google is default
![image](https://user-images.githubusercontent.com/34715963/101616423-a1e51f00-3a0f-11eb-8625-bdd02d91c0a7.png)
On 1.18.x google is default, but Yandex has been added to suggested list
![image](https://user-images.githubusercontent.com/34715963/101617140-8d555680-3a10-11eb-86ba-1c2e81612ed0.png)
