### ISSUE TITLE
navigator.userAgent farbling not applied in workers

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#12230]
![image](https://user-images.githubusercontent.com/43750833/96645552-ba329a80-12f8-11eb-9301-718310d879c2.png)

**Comment by GeetaSarvadnya** [comment]
@pilgrim-brave Can you please link the test plan?

**Comment by pilgrim-brave** [comment]
Test plan:

1. Visit https://dev-pages.brave.software/farbling.html
2. In Brave Shields panel, change Fingerprinting to "Allow all"
3. Click 'Generate fingerprints'
4. In 'User Agent' row, all columns should show the same hash value. Note this hash value for later step.
5. In Brave Shields panel, change Fingerprinting to "Blocked (strict)"
6. Refresh page
7. Click 'Generate fingerprints'
8. In 'User Agent' row, all columns should show the same hash value. This hash value should be different than the hash value in step 4.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the test plan from https://github.com/brave/brave-browser/issues/12230#issuecomment-740098380
- Verified that `User-Agent` row, all columns have the same hash value when Fingerprinting value is allowed in the shield
![image](https://user-images.githubusercontent.com/38657976/101441405-04bab580-393f-11eb-9a99-1f14c1361889.png)
- Verified that `User-Agent` row, all columns have the same hash value but different than the above step when Fingerprinting value is blocked and strict in the shield
![image](https://user-images.githubusercontent.com/38657976/101441484-2f0c7300-393f-11eb-84ae-2085675d6303.png)
