### ISSUE TITLE
Brave Ads may not be converted for duration of observation window

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12234]
## Description 

Brave Ads may not be converted for duration of observation window depending on user activity and ads history.

## Steps to Reproduce

   1. View an ad notification (which has a conversion)
   2. Wait for the ad notification to time out
   3. Trigger 700 thumbs up events on the 7-days ad history screen (use staging so you do not run out of unblinded tokens)
   4. Trigger the conversion from step 1

## Actual result:

Ad is not converted due to the ads history only storing 700 entries (enough for ~7 days depending on how many events are triggered)

## Expected result:
Ad should be converted for the duration of the observation window

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
Closing as issue was resolved by refactoring https://github.com/brave/brave-browser/issues/12486 where we moved ad event history from `client.json` to an `ad_events` database table

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.18.66 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from the description.
Verified that after 700 events on 7-day history page, the ad was converted.
