### ISSUE TITLE
Brave Nightly- Customize Dashboard layout issue

### ISSUE THREAD

**Issue by phoogm** [brave/brave-browser#12247]
## Description 

The cards displayed on the NTP Customize Dashboard are cut off at the right hand side by the vertical scrollbar.

## Steps to Reproduce

   1. Open a new tab page
   2. Click on Customize then click on More Cards
   3. Observe the layout issue

## Actual result:
<img width="730" alt="Brave Nightly More Cards Issue" src="https://user-images.githubusercontent.com/56597375/96700683-01b83580-1390-11eb-8d0c-2b832ceff934.png">

## Expected result:
The Customize Dashboard panel should have the correct size to display the card elements completely and the vertical scrollbar should be displayed with some padding next to second column of cards.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.17.43 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.16 (Build 20A5395g)

## Version/Channel Information:
- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Thanks for looking into, best regards.

**Comment by rebron** [comment]
@phoogm This should be fixed now, look. Can you take a look? Thanks for running Nightly too by the way. 
![Screen Shot 2021-02-12 at 8 47 28 AM](https://user-images.githubusercontent.com/5951041/107796650-f6a65e00-6d0e-11eb-97df-01f516bf9ed1.png)
