### ISSUE TITLE
reddit tipping banner taking ~5-8s to appear/display when using inline tipping under reddit

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12241]
## Description 

When clicking on the inline `BAT` icon on reddit, it takes the tipping banner anywhere between 5-8s to appear. Because of this delay, some users might think the UI isn't responsive/broken or click on the `BAT` several times which leads to multiple opened banners. We should improve performance if possible.

However, @NejcZdovc mentioned this delay is due to reaching out to the reddit API which sometimes takes a bit of time.

## Steps to Reproduce

   1. launch the latest Brave that includes Greaselion reddit via staging (`1.17.43 CR: 86.0.4240.99` in this case)
   2. enable rewards either through the rewards panel or `brave://rewards`
   3. visit https://www.reddit.com/user/jsadler-brave and click on the inline `BAT` icon

## Actual result:

![delay](https://user-images.githubusercontent.com/2602313/96680288-394cc080-1343-11eb-80f8-e9d3d289a15f.gif)

## Expected result:

Tipping banner shouldn't take ~5-8s to appear.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.17.43 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.15.7 (Build 19H2)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @mandar-brave @rebron @NejcZdovc @LaurenWags

**Comment by GeetaSarvadnya** [comment]
Verified using dev component for:

```
Brave Local Data Updater - Version: 1.0.695
```
Launched `1.44.177` using `--use-dev-goupdater-url` and ensured issue is fixed with the component `1.0.695` tipping banner appears quickly upon clicking on the inline tip icon in https://www.reddit.com/user/jsadler-brave
![Tipping banner](https://user-images.githubusercontent.com/38657976/213623879-c1e9aaa9-5c01-40f8-8000-74ef32bddce4.gif)
