### ISSUE TITLE
Looking for a better TAB contrast than the existing one

### ISSUE THREAD

**Issue by GUITERII** [brave/brave-browser#12249]
Hi,
    Just looking for to have a more noticeable way to locate the OPENED TAB using the dark theme.
Beside the original display - TOP RIGHT
3 other Design features would help greatly to locate the opened tab, 
in case that is the one you need to close...
At this moment, it is very hard to locate the opened TAB with Dark-Grey background from the other Black only bkgd !

Adding a bit of contrast will ease the dailly usage fo reveryone;
thanks 

See link to more contrasted Layouts suggested  >>> https://ibb.co/8xS8L9B

**Comment by karenkliu** [comment]
We have 2 upcoming issues related to this: #8576 and #2735. Let's wait for these to move through the release channels and re-evaluate afterwards if more contrast is necessary.

Thanks!
