### ISSUE TITLE
Videos on FoxBusiness.com don't play because of adblock

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1224]
Carried over from https://github.com/brave/browser-laptop/issues/3027

## Steps to reproduce
1. Visit https://video.foxbusiness.com/v/5068842750001/do-the-koch-brothers-own-the-gop-elites-/?#sp=show-clips
2. Try to play the video
3. Open the dev control; notice lots of errors
4. Using shields, allow ads
5. Page reloads and you should be able to play the video

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/902 which lists other sites as well where video playback fails due to adblocker
