### ISSUE TITLE
[Widget] Auto hide keyboard when preview conversion is selected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12246]
## Description 
Auto hide keyboard when preview conversion is selected

## Steps to reproduce 

   1. Connect to Binance widget
   2. Select convert
   3. Select token you want to convert and enter amount, popup keyboard shows up 
   4. Enter amount and click on preview conversion, keyboard remains open instead of being auto hidden

## Actual result 
Auto hide keyboard when preview conversion is selected

## Expected result
Keyboard should autohide when focus is changed from input field

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.17.43 Nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Fixed by https://github.com/brave/brave-core/pull/7031

**Comment by kjozwiak** [comment]
@srirambv found https://github.com/brave/brave-browser/issues/12693 when QAing the above. https://github.com/brave/brave-core/pull/7031 was merged via https://github.com/brave/brave-core/pull/7124 but https://github.com/brave/brave-browser/issues/12693 will need to be fixed and uplifted in another PR.

**Comment by srirambv** [comment]
Marking as QA/No as this is superseeded by #12693 and will be fixed in https://github.com/brave/brave-core/pull/7151
