### ISSUE TITLE
chrome://cast/ shows empty page

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1225]
## Steps to Reproduce

   1. Open `chrome://cast/`

IMPORTANT: This page is accessible through Cast Icon (located next to Brave Shield icon) -> Manage Cast Devices

![image](https://user-images.githubusercontent.com/34715963/45861868-59c67d00-bd6f-11e8-8344-b0f3d4c7a8f6.png)

## Actual result:

Empty page is shown
Terminal error:
`[10068:13160:0921/074535.542:ERROR:CONSOLE(0)] "Uncaught (in promise) Failed to load: src is not valid.", source: chrome://cast/ (0)`

## Expected result:
Similar to Chrome:
![image](https://user-images.githubusercontent.com/34715963/45862751-6cdb4c00-bd73-11e8-9224-ffed2d892249.png)

## Reproduces how often: 

always

## Brave version (chrome://version info)
Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

**Comment by srirambv** [comment]
Think this is invalid considering #763

cc: @bbondy

**Comment by bsclifton** [comment]
@srirambv that issue was closed saying:
> Closing this issue since there are sufficient requests from users for cast support.

So I do think it should be working. I believe this is something that may need API keys to work though

Not having this support may affect `webcompat`- for example: https://github.com/brave/brave-browser/issues/1227

**Comment by Brave-Matt** [comment]
+1 from Reddit: https://www.reddit.com/r/brave_browser/comments/9j4azn/chromecast_in_new_devbuild/

**Comment by Brave-Matt** [comment]
+ 1 from Community: https://community.brave.com/t/cast-not-finding-any-devices/31757/2

**Comment by srirambv** [comment]
This page isn't listed any more under chrome://chrome-url. @kjozwiak could you check if this shows up when you are casting on a device? Since you were the only one who was able to test #209. We can close this issue if it doesn't show up while screen cast is in progress. I don't see the page on Chrome as well

**Comment by btlechowski** [comment]
It seems to be fixed

Brave | 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

I had to enable the cast feature through settings.
`chrome://cast/` shows this page:
![image](https://user-images.githubusercontent.com/34715963/68239354-1d092400-000b-11ea-84ee-0919972b5738.png)
