### ISSUE TITLE
Update Startpage search to give attribution to Brave

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#12257]
## Description 
We currently offer StartPage in our list of "Default search engines" (visible on brave://settings/searchEngines)
![image](https://user-images.githubusercontent.com/4733304/96751524-26a5ac00-1382-11eb-8532-f939b98d9c5b.png)

The integration here is just using the Open Search provided parameters. We should update so that Brave can be attributed for the search.

Also - the branding should be `Startpage` and not `StartPage`

## Steps to Reproduce
   1. New profile
   2. Visit brave://settings/searchEngines and set Start Page as default engine
   3. Do a search for `cats` in the omnibox

## Actual result:
Search URL is in format like `https://www.startpage.com/do/dsearch?query=cats&cat=web&pl=opensearch`

## Expected result:
Search URL should be in the format like https://www.startpage.com/do/search?q=cats&segment=startpage.brave

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
```
- Verified the STR from the description

**New profile** 

**Existing profile**

- Installed older version `1.12.x` of brave and set the default search engine as `Startpage` and performed search `cats` and ensures that `pl=opensearch` in the search bar
![image](https://user-images.githubusercontent.com/38657976/97171285-37f01d80-17b3-11eb-878a-6cbc89b9fcd3.png)


- Ensured default search engine is showing as `StartPage` in `brave://settings/search`
![image](https://user-images.githubusercontent.com/38657976/97171250-20189980-17b3-11eb-8ef9-fe5695d7eadb.png)
