### ISSUE TITLE
P3A for New Tab Page

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#12267]
## Description 
Adding questions so that we can understand more about new tab page usage; specifically with regards to customizing and sponsored image display.

**Question 1**: (`Brave.NTP.NewTabsCreated`)
_On average, how many New Tab Pages did you create per day?_ 
```
0) 0 
1) 1 to 3
2) 4 to 8
3) 9 to 20
4) 21 to 50
5) 51 to 100
6) More than 100
```

**Question 2**: (`Brave.NTP.SponsoredImagesEnabled`)
_Is the sponsored new tab page option enabled?_
```
0) Disabled
1) Enabled
```

**Question 3**: (`Brave.NTP.SponsoredNewTabsCreated`)
_On average, how many of the New Tab Pages you saw per day were sponsored?_

**Answers**: 
```
0) 0%
1) > 0% and < 10%
2) 10% to < 20%
3) 20% to < 30%
4) 30% to < 40%
5) 40% to < 50%
6) 50% or more
```

**Question 4**: (`Brave.NTP.CustomizeUsageStatus`)
_On the New Tab Page, did you click the Customize Settings icon?_ 

**Answers**: 
```
0) No
1) Yes, but I didn't make any changes
2) Yes, and I did make a change
```

**Comment by kjozwiak** [comment]
@bsclifton mind checking to see if we're getting the correct data from the above questions on Nightly/BETA? If things look good, we can consider this as QA complete in spirit of saving some time. The above was also QA'd once via https://github.com/brave/brave-core/pull/6924#issuecomment-724459202 so it was checked.

**Comment by bsclifton** [comment]
@aekeus helped confirm we're seeing data on RELEASE (via release candidate) in DM 😄👍 Should be good to go!

**Comment by kjozwiak** [comment]
> @aekeus helped confirm we're seeing data on RELEASE (via release candidate) in DM 😄👍 Should be good to go!

As per above, @aekeus verified that we were getting data and everything looked correct. As per https://github.com/brave/brave-browser/issues/12267#issuecomment-726739760, adding `QA/No`. QA also made sure the above was working before we uplifted via https://github.com/brave/brave-core/pull/6924#issuecomment-724459202 so there was some verification 👍 Thanks again for the double check @aekeus and the help @bsclifton.
