### ISSUE TITLE
Crash in BraveContentSettingsAgentImpl

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#12268]
For QA: crash is reproduced by visiting https://www.dell.com/support/home/ru-ru/product-support/product/idrac9-lifecycle-controller-v4.x-series/docs and hard-reload (Cmd-Shift-R)

```
[ 00 ] <name omitted>
[ 01 ] <name omitted>
[ 02 ] content_settings::BraveContentSettingsAgentImpl::AllowScript(bool)
[ 03 ] blink::LocalDOMWindow::CanExecuteScripts(blink::ReasonForCallingCanExecuteScripts)
[ 04 ] blink::HTMLMediaElement::ShouldShowControls(blink::HTMLMediaElement::RecordMetricsBehavior) const
[ 05 ] blink::MediaControlsImpl::UpdateCSSClassFromState()
[ 06 ] blink::HTMLMediaElement::ContextDestroyed()
[ 07 ] blink::ExecutionContext::NotifyContextDestroyed()
[ 08 ] blink::LocalDOMWindow::FrameDestroyed()
[ 09 ] blink::LocalFrame::DetachImpl(blink::FrameDetachType)
[ 10 ] blink::Frame::Detach(blink::FrameDetachType)
[ 11 ] blink::Page::WillBeDestroyed()
[ 12 ] blink::WebViewImpl::Close()
[ 13 ] content::RenderViewImpl::Destroy()

```

https://brave.sp.backtrace.io/p/brave/debug?filters=(_deleted%3D0%2Cptype%3Drenderer%2C(ver%2Cregex%2C%228%5B5%7C6%7C7%7C8%7C9%5D.*%22))&fingerprint=22190b8f97b01300d5114c4977e24e6313ad884621a5da62411c4d3a8b211a56&debug=(b75f45,0,0)

**Comment by iefremov** [comment]
also 
```
[ 00 ] blink::SecurityOrigin::ToUrlOrigin() const
[ 01 ] blink::WebSecurityOrigin::operator url::Origin() const
[ 02 ] content_settings::BraveContentSettingsAgentImpl::AllowScript(bool)
[ 03 ] blink::LocalDOMWindow::CanExecuteScripts(blink::ReasonForCallingCanExecuteScripts)
[ 04 ] blink::HTMLMediaElement::ShouldShowControls(blink::HTMLMediaElement::RecordMetricsBehavior) const
[ 05 ] blink::MediaControlsImpl::UpdateCSSClassFromState()
[ 06 ] blink::HTMLMediaElement::ContextDestroyed()
[ 07 ] blink::ExecutionContext::NotifyContextDestroyed()
[ 08 ] blink::LocalDOMWindow::FrameDestroyed()
[ 09 ] blink::LocalFrame::DetachImpl(blink::FrameDetachType)
[ 10 ] blink::Frame::Detach(blink::FrameDetachType)
[ 11 ] blink::Page::WillBeDestroyed()
[ 12 ] blink::WebViewImpl::Close()
[ 13 ] content::RenderViewImpl::Destroy()
```
https://brave.sp.backtrace.io/p/brave/debug?filters=(_deleted%3D0%2Cptype%3Drenderer%2C(ver%2Cregex%2C%228%5B5%7C6%7C7%7C8%7C9%5D.*%22))&fingerprint=3e45066d2f1a26fcfe30ccf8832a984d0325e8d581977d3221711c165a32d591&debug=(b7686d,0,0)

and 
https://brave.sp.backtrace.io/p/brave/debug?filters=(_deleted%3D0%2Cptype%3Drenderer%2C(ver%2Cregex%2C%228%5B5%7C6%7C7%7C8%7C9%5D.*%22))&fingerprint=c3e113fa2a98d80133890c11553f888bafce8ba4c70204363a1df910d0dcdf03

**Comment by kjozwiak** [comment]
@iefremov added `OS/Android` as this is reproducible on `1.16.68 CR: 86.0.4240.111`.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 10` using `1.16.70 CR: 86.0.4240.111`

Reproduced the original issue using `1.16.68 CR: 86.0.4240.111`

* verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/6938#issue-508879118
* ensured that refreshing https://www.dell.com/support/home/ru-ru/product-support/product/idrac9-lifecycle-controller-v4.x-series/docs doesn't crash the browser on both mobile/desktop modes

Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 10` using `1.16.70 CR: 86.0.4240.111`

* verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/6938#issue-508879118
* ensured that refreshing https://www.dell.com/support/home/ru-ru/product-support/product/idrac9-lifecycle-controller-v4.x-series/docs doesn't crash the browser on both mobile/desktop modes
