### ISSUE TITLE
[Desktop] race condition with Greaselion and localizations

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12264]
## Description 

I noticed that the "Tip" text wasn't displaying next to the in-line BAT logo on twitter. When this happens, if you click on the in-line tip icon, sometimes (not always) nothing will happen (no tip banner opens).

Per discussion with @emerick there is a race condition with localizations that causes the text to not display properly. A browser restart fixes this.

## Steps to Reproduce

Unsure if the below will work 100% of the time:
   1. Clean profile
   2. Enable Rewards
   3. Navigate to a twitter page like twitter.com/brave
   4. Look at the tweets on the page.
   5. Click on icon.

## Actual result:

No "Tip" text next to the BAT logo and when you click on it, the banner may or may not open.
<img width="602" alt="1 17 x" src="https://user-images.githubusercontent.com/28145373/96765641-21f3ee80-13a8-11eb-879e-a987f0587f62.png">

## Expected result:
should say "Tip" and "Tip" should change to orange when hovered over. Should be able to click on the BAT logo/text and the tip banner should be displayed.
<img width="618" alt="Screen Shot 2020-10-21 at 2 16 46 PM" src="https://user-images.githubusercontent.com/28145373/96765584-1e606780-13a8-11eb-8997-74360a7d65ea.png">
<img width="602" alt="1 15 x" src="https://user-images.githubusercontent.com/28145373/96765617-202a2b00-13a8-11eb-95e3-030e70ae78f8.png">

## Reproduces how often: 

intermittent, race condition

## Brave version (brave://version info)

Brave | 1.17.45 Chromium: 86.0.4240.99 (Official Build) dev (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @emerick @NejcZdovc

**Comment by emerick** [comment]
We think this is caused by or related to this upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=83549.

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.18.2`

![image](https://user-images.githubusercontent.com/38657976/96849095-d22e2980-1472-11eb-84b2-28de67ca9d7b.png)

**Comment by LaurenWags** [comment]
Reproduces on Reddit as well:
<img width="1193" alt="Screen Shot 2020-10-28 at 9 44 07 AM" src="https://user-images.githubusercontent.com/28145373/97444969-1aca6480-1903-11eb-9f4b-7b2a5730d3ae.png">

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 1.17.59 Chromium: 86.0.4240.183 (Official Build) dev (64-bit)
-- | --
Revision | 0b568b034b8f7994697cb341eeca5979b84151cc-refs/branch-heads/4240@{#1374}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/98069162-6da1a000-1e5e-11eb-82b4-efe0b7c0caae.png)

Steps:
1. With rewards enabled, open `https://old.reddit.com/user/alex_the_brave` in a new tab

Note: Browser restart fixes the issue
Note: Page reload does not fix the issue

**Comment by LaurenWags** [comment]
This happens almost every time I open a GH page:
<img width="1187" alt="Screen Shot 2020-11-04 at 2 55 14 PM" src="https://user-images.githubusercontent.com/28145373/98161469-c8aeb380-1ead-11eb-8694-837b946dc230.png">

Close/reopen of the browser fixes it:
<img width="1201" alt="Screen Shot 2020-11-04 at 2 56 05 PM" src="https://user-images.githubusercontent.com/28145373/98161521-e11ece00-1ead-11eb-8855-e52a36eca027.png">

```
Brave | 1.17.60 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
-- | --
Revision | 37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS | macOS Version 10.14.6 (Build 18G6032)
```

**Comment by LaurenWags** [comment]
Removed `intermittent-issue` as this happens about 80-90% of the time for me. It's incredibly prevalent.

**Comment by emerick** [comment]
When this fails for me, it's due to the contents of the following directory being deleted: `C:\Users\emerick\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Extensions`.

**Comment by jonathansampson** [comment]
I often see _Failed to fetch user details for <username>: Missing auth headers_ as well. You can trigger this message by switching away from Twitter, and back. It's fairly easy to reproduce in my experience. This makes sense, since I am apparently also never able to actually trigger the `handleOnSendHeadersWebRequest` method either:
```js
const handleOnSendHeadersWebRequest = (mediaType: string, details: any) => {
  if (mediaType !== types.mediaType || !details || !details.requestHeaders) {
    return
  }
  if (auth.processRequestHeaders(details.requestHeaders)) {
    tipping.configure()
  }
}
```
That handler is registered successfully, but never called:
```js
webRequestHandlers.registerOnSendHeadersWebRequest(
  types.mediaType,
  types.sendHeadersUrls,
  types.sendHeadersExtra,
  handleOnSendHeadersWebRequest)
tabHandlers.registerOnUpdatedTab(types.mediaType, handleOnUpdatedTab)
```

**Comment by emerick** [comment]
@jonathansampson I've got a fix for the localizations bug teed up, I just need to clean it up and PR it (most likely in the morning at this point).

I have seen that Twitter error message, but I think it's probably unrelated to this. As long as tipping and the panel works correctly, it should be doing the right thing. It will often write out that message due to the timing of when we receive the auth cookie, but it's typically a benign message. It's weird if you're not seeing it triggered, though. Most of the publisher sites are split into two separate scripts (and soon three), so it could possibly be that only one is receiving that?

**Comment by jonathansampson** [comment]
@emerick Tipping isn't working when I see this error; clicking the inline tipping button raises the following:

```console
Failed to fetch tweet metadata for [object HTMLElement]: Error: Missing auth headers
    at api.ts:19
    at new Promise (<anonymous>)
    at sendAPIRequest (api.ts:11)
    at Module.getTweetDetails (api.ts:82)
    at getMediaMetaData (tipping.ts:22)
    at HTMLButtonElement.tipButton.onclick (tipping.ts:140)
```

**Comment by emerick** [comment]
@jonathansampson OK, gotcha - then it's definitely not what I was thinking. Do you mind creating a new issue with that info and the steps to repro that you mentioned earlier and we'll prioritize it? Thank you!

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.70 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/7141#issue-520580575

Opened multiple tabs w/ in-line tip buttons. Examples:
 - https://twitter.com/emerick, https://twitter.com/bravelaurenwags
 - https://github.com/brave/brave-browser/issues/12527 and other issue links
 - https://github.com/brave/brave-core/commits/master 
 - https://github.com/brave/brave-core/pull/7140 and other PR links
 - https://www.reddit.com/user/alex_the_brave, https://www.reddit.com/user/cryptojennie
 - https://old.reddit.com/ 
 - https://www.reddit.com/r/brave_browser/ and other subreddit links

Generally confirmed:
 - Navigating thru the various pages/page types above and confirming "Tip" text and button were displayed. 
 - Opening new pages via context menu and confirming when opening the page it loaded and the "Tip" text and button were displayed.
 - Closing tabs and reopening using cmd+shift+T. When tab is reopened and loaded the "Tip" text and button were displayed.
 - Leaving various pages as active and then close/reopen the browser. On relaunch pages generally showed the "Tip" text and button, except for Twitter pages. This is logged with https://github.com/brave/brave-browser/issues/11825. Reload fixes it. Also confirmed reloading a tab that was left over from previous session showed the "Tip" text and button once page loaded.

---------------
