### ISSUE TITLE
[CW] Update Deposit Ether page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12269]
## Description 

Update Deposit Ether page

## Steps to Reproduce

   1. Enable Crypto Wallets
   2. Go to Deposit ether

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/96860494-b7e85180-145a-11eb-8970-ecf80520bd01.png)

## Expected result:
Updated Deposit ether window

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.15.76 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit) 
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Linux
Component | `1.0.16 dev`

- Verified deposit ether page is updated 
![image](https://user-images.githubusercontent.com/17010094/97419277-c7a3e200-1901-11eb-9cf2-47308bbde969.png)

---------------------

Verification passed on 

Brave | 1.17.50 Chromium: 86.0.4240.111 (Official Build) dev (64-bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Windows 10 OS Version 1809 (Build 17763.1518)
Component | `1.0.16 dev`

- Verified deposit ether page is updated 
![image](https://user-images.githubusercontent.com/17010094/97419297-ca9ed280-1901-11eb-8426-ed0dc272b1b3.png)

---------------------
Verification passed on 

Brave | 1.18.5 Chromium: 86.0.4240.111 (Official Build) nightly (x86_64)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | macOS Version 10.15.7 (Build 19H2)
Component | `1.0.16 dev`

- Verified deposit ether page is updated 
![image](https://user-images.githubusercontent.com/17010094/97419299-cecaf000-1901-11eb-8e71-f181dd81b16a.png)

**Comment by Douglashdaniel** [comment]
Steps for testing:
In your development build choose “Main Ethereum Network” as your network.
1. Click “BUY” and then “Continue to Wyre” it should redirect to https://pay.testwyre.com/
2. Enter $1  for ETH amount.
3. Check authorize and then “Next”
4. Card number: 4111111111111111
5. Expiration: 10/23
6. Cvv: 123
7. SMS Verification: 000000
8. Bank Verification: 000000
