### ISSUE TITLE
[Widget] [Follow up #12092] Update Crypto.com widget card in gallery

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12266]
## Description 

 [Follow up #12092] Update Crypto.com widget card in gallery

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/96828718-0b917580-1430-11eb-9300-3b115a8d17c5.png)

## Expected result:
<img width="329" alt="crypto-com" src="https://user-images.githubusercontent.com/318119/96741202-2d82ed80-1387-11eb-8800-06c7681aaa7b.png">

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.17.43 Chromium: 86.0.4240.99 (Official Build) nightly (64-bit)
-- | --
Revision |` 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by stephendonner** [comment]
Verified on macOS (Big Sur) using 


Brave | 1.20.88 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

<img width="247" alt="Screen Shot 2021-01-25 at 6 28 20 PM" src="https://user-images.githubusercontent.com/387249/105791545-2695e900-5f3b-11eb-8365-74495b327a18.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-Bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Linux

- Verified test plan from https://github.com/brave/brave-core/pull/7397
![image](https://user-images.githubusercontent.com/17010094/107023731-f05c3300-679e-11eb-8fa9-8bf54d3c9263.png)
-------
Verification passed on

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-Bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Windows 10 OS Version 2009 (Build 19042.746)

- Verified test plan from https://github.com/brave/brave-core/pull/7397
![image](https://user-images.githubusercontent.com/17010094/107023854-1eda0e00-679f-11eb-98c9-7811b3a16079.png)
