### ISSUE TITLE
Allow users to enable Brave Rewards diagnostic logs to help diagnose issues

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12271]
Allow users to enable Brave Rewards diagnostic logs to help diagnose issues behind a multi click opt-in along with a warning about this may compromise the users privacy

**Comment by tmancey** [comment]
cc @diracdeltas

**Comment by diracdeltas** [comment]
@tmancey could you please write a short spec for what data will be collected in these logs? would be ideal to do this on a whitelist basis (only log fields that we know are probably safe to log)

**Comment by tmancey** [comment]
@diracdeltas sounds good, just got a few other priorities then I will do this. Thanks

**Comment by Miyayes** [comment]
This has been resolved and users can get logs in brave://rewards-internals > logs, and enable verbose mode optionally in brave://flags (disabled by default).
