### ISSUE TITLE
[Desktop] backup words no longer displayed in backup/restore modal

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12274]
## Description 

After you restore a wallet, the backup words should be displayed on the `Backup` tab of the Manage Your Wallet modal. This is happening with 1.15.x but not 1.16.x.

## Steps to Reproduce

   1. Clean profile, enable Rewards
   2. Restore a wallet with a balance (cannot be zero)
   3. Open Manage Your Wallet modal, go to Backup tab

## Actual result:

No backup words displayed
<img width="698" alt="Screen Shot 2020-10-22 at 8 43 42 AM" src="https://user-images.githubusercontent.com/28145373/96873812-6aacb580-1443-11eb-9cb5-bf871f679fd1.png">

Occurs for upgrade case as well.

## Expected result:
Backup words should be displayed as they are in 1.15.x
<img width="747" alt="Screen Shot 2020-10-22 at 8 40 38 AM" src="https://user-images.githubusercontent.com/28145373/96874010-a6e01600-1443-11eb-8e60-5698ffeb3b21.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G3020)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.15.x no, 1.16.x yes
- Can you reproduce this issue with the beta channel? 1.17.x yes
- Can you reproduce this issue with the nightly channel? 1.18.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @rebron @mandar-brave @kjozwiak

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.16.67 Chromium: 86.0.4240.111`

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 18.04

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

**Comment by NejcZdovc** [comment]
we remove the api in this PR https://github.com/brave/brave-core/pull/6627

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified STR from description and test plan from https://github.com/brave/brave-core/pull/6939

<img width="1199" alt="1 16 x" src="https://user-images.githubusercontent.com/28145373/97169240-1dd91f80-1760-11eb-8097-33053e536d64.png">

------------
