### ISSUE TITLE
Add P3A stats for Brave Ads response status codes per endpoint

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12272]

**Comment by tmancey** [comment]
cc @amirsaber @jsecretan

**Comment by moritzhaller** [comment]
@tmancey what level of resolution would we need? E.g. would it be enough to have a question like "How many non-2xx responses received from ad-endpoints last week" or do we want to know the frequency of individual error codes (200 vs. 400 etc.) in which case we would need multiple questions.

**Comment by tmancey** [comment]
@moritzhaller at a minimum I would say we would need 2xx, 3xx, 4xx and 5xx however individual error codes would be of more use. Thanks

**Comment by moritzhaller** [comment]
@tmancey can we enumerate all status codes we'd be interested in? We probably have to create one question per status code then

**Comment by tmancey** [comment]
@moritzhaller due to the amount of questions we should just have 1xx, 2xx, 3xx, 4xx and 5xx

**Comment by moritzhaller** [comment]
@tmancey at what resolution should we capture the counts? I think we can have at most 8 buckets per question. We could evenly space out between zero and an assumed max value, or have higher resolution at lower counts and be less precise at higher counts.

**Comment by tmancey** [comment]
Closed as stale
