### ISSUE TITLE
[Widget] Remove back button when in token graph view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12277]
## Description 

Two back buttons are shown when a token view is selected. Back button to token list can be missed as the back button to opt-in state is more obvious and can take back user to opt-in state instead of back to the token list

## Steps to Reproduce

   1. Open Crypto.com widget
   2. Enable market view and select a token
   3. Two back buttons are shown one on top which and next to token

## Actual result:

<img width="313" alt="Screenshot 2020-10-22 at 16 00 55" src="https://user-images.githubusercontent.com/17010094/96891032-28559980-1480-11eb-9722-67a26a9bfff3.png">

## Expected result:
Only have one back button on token graph view 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64 Bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Adding `release/blocking` and moved into the `1.16.x` milestone as we want this released with `1.16.x`.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 10 OS Version 1903 (Build 18362.1139)


```
- Reproduced the issue in `1.16.67`
![image](https://user-images.githubusercontent.com/38657976/97148723-9e644400-1791-11eb-8811-2b16a0bc7845.png)
- Upgraded profile to `1.16.78` and ensured there is only one back arrow in the token graph view
![image](https://user-images.githubusercontent.com/38657976/97148822-c18ef380-1791-11eb-8dc2-c4a8622ebb2f.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified back button is only shown in token list view and is hidden when token details is opened
![mac-widget](https://user-images.githubusercontent.com/17010094/97257384-a95cba00-180d-11eb-8980-202f170287c5.gif)

-----------
Verification passed on 

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64 bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Windows 10 OS Version 1809 (Build 17763.1518)

- Verified back button is only shown in token list view and is hidden when token details is opened
![win-widget](https://user-images.githubusercontent.com/17010094/97257501-0ce6e780-180e-11eb-8275-7d95b9ce1617.gif)

-------------
Verification passed on 

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64 bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Linux

- Verified back button is only shown in token list view and is hidden when token details is opened
![Uploading linux-widgegt.gif…]()
