### ISSUE TITLE
Unable to run videos from https://www.arte.tv/

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1227]
Carried over from https://github.com/brave/browser-laptop/issues/15218
> ### Description
> Unable to run videos from the site https://www.arte.tv/. Even after changing the shield settings the videos from this site are not playing. The black screen is displayed with text “casting failed to load”. When we turn down the shield the videos are running but the text “casting failed to load” is overlapping on the videos.
> 
> 
> ### Steps to Reproduce
>   1. Navigate to https://www.arte.tv/
>   2. Play videos
> 
> **Actual result:**
> Unable to run videos from the site https://www.arte.tv/. Even after changing the shield settings the videos from this site are not playing. The black screen is displayed with text “casting failed to load”. When we turn down the shield the videos are running but the text “casting failed to load” is overlapping on the videos.

When trying myself, I didn't see the text above... but the video didn't play. I did see blocked resources when opening the developer tools. The site might be trying to engage with Chromecast APIs (which we may not have installed / assigned an API key / etc)

**Comment by tomlowenthal** [comment]
Does the same thing happen with Shields down?

**Comment by bbondy** [comment]
Videos are playing fine for me. Closing.  Will re-open if more info is given.
