### ISSUE TITLE
Add Uphold Equities Card

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#12276]
Add the Uphold Equities Card.
Here the card design

![image](https://user-images.githubusercontent.com/35932307/96883834-af315480-1435-11eb-9506-4015c177a7bd.png)

Link: https://uphold.com/en/buy-fractional-shares/brave

Lets make it a priority to get this shipped.
@NejcZdovc @jenn-rhim

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.17.62 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
Revision	37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS	macOS Version 10.14.6 (Build 18G6032)
```

Verified tests performed under https://github.com/brave/brave-core/pull/6982#issuecomment-719148727

US (no promo) | KY (has promo)
-------------------------|-------------------------
<img width="332" alt="US" src="https://user-images.githubusercontent.com/28145373/98411412-fc234680-2043-11eb-8c26-69cf9946f463.png">  | <img width="372" alt="KY" src="https://user-images.githubusercontent.com/28145373/98411422-004f6400-2044-11eb-82b7-184e770af4ae.png">


* ensured that the equities uphold card wasn't being displayed when using `US` (United States), `DK` (Denmark) & `FR` (France)
* ensured that the equities uphold card was being correctly displayed when using `KY` (Cayman Islands), `NZ` (New Zealand), & `WS` (Samoa) - all available on the list from https://github.com/brave/brave-core/pull/6982/files#diff-6b6ed7044cbb83bc4e57c74f9d946505e033ec70915527c7d525351b0a4c8e48
* ensured that the equities uphold card is visible when refreshing/re-opening `brave://rewards`
* ensured that the equities uphold card is visible after restarting Brave several times
* ensured that clicking on `X` closes the promo and ensured that it's never visible again (refreshing/re-loading/restarting)
* ensured that clicking on the card opens a new tab and loads the following:
  * https://uphold.com/en/buy-fractional-shares/brave --> https://uphold.com/en/buy-fractional-shares

-------------------
