### ISSUE TITLE
Embedded peertube videos not working 

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#12283]
## Description 
`https://thinkmoult.com/how-to-install-blender-gimp-android.html` videos aren't showing

## Steps to Reproduce

   1. Open `https://thinkmoult.com/how-to-install-blender-gimp-android.html`
   2. Scroll down, embedded videos are blank
   3. Unable to play videos

## Actual result:
![thinkmoult1](https://user-images.githubusercontent.com/1659004/96927082-078a5400-1513-11eb-80be-84b591a5d5c4.png)
![thinkmoult22](https://user-images.githubusercontent.com/1659004/96927242-45877800-1513-11eb-8ee3-56fd5c7712e5.png)

## Expected result:
![thinkmoult2](https://user-images.githubusercontent.com/1659004/96927072-02c5a000-1513-11eb-88db-52c67b67e0fc.png)

Expect videos to show/playback

## Reproduces how often: 
Easily, with default shields.

## Brave version (brave://version info)
`Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Cookies are needed for `peertube.social` for the videos to show. So `Allowing all cookies` in shields will help.

Was reported: https://github.com/Chocobozzz/PeerTube/issues/3156

**Comment by rebelcode-xr** [comment]
We're promoting the use of more privacy friendly softwares like Brave and PeerTube to our users: it's a pity to see Brave breaking PeerTube. Users just think that our website is poorly made or they switch back to Chrome: please fix this asap! 🙏

**Comment by ryanbr** [comment]
`PeerTube v3 should work with brave`   from: https://github.com/Chocobozzz/PeerTube/issues/3156

Just confirmed it's now working. closing ticket.
