### ISSUE TITLE
Google reCAPTCHA has often problem when using Brave

### ISSUE THREAD

**Issue by bandi88** [brave/brave-browser#12289]
## Description 
I recently changed my browser from Chrome to Brave. After that change, the Google's reCAPTCHA is annying every time I encounter it: after clicking on "I am not robot" there come a captcha to solve. The reCAPTCHA is never ending, and refusing to validate me. Especially the "click verify once there are none left" is the most annoying: the new pictures (after finding and clicking one) load within 15-30 seconds (so extreme low); which I absolutely don't understand. Previously, on Chrome, the new pictures loaded in 1 sec for the captchas like "click verify once there are none left".

What can I do? I don't want to revert to Chrome. I want to stick with Brave. But for me also the browsing expreience is important.

## Steps to Reproduce

   1. Open a website which uses Google's reCAPTCHA.
   2. Click the checkbox "I am not robot".
   3. Try to solve the captcha.

## Actual result:
Most of times I need to solve 10-20 captchas to proceed (previous captchas' solutions are also correct, but even so the Google keeps sending me the new and new captcha). So, solving one single captcha, like before with Chrome, is not anymore enough to proceed. And the "click verify once there are none left" captchas has an extrem high loading/unfading time for the new pictures.
This problem seems to be related to Brave, because that problem does not come with Chrome or Firefox browsers. (I tested them both)
Turning off the Brave shield does not help. It seems, Google tries to punish us, Brave users!

## Expected result:
The reCAPTCHA should let me proceed after the checkbox "not robot" is checked. But even if not directly after, then at the latest when I solved the frist captcha.

## Reproduces how often: 
It comes every time, a reCAPTCHA is present on the website.

## Brave version (brave://version info)
Used the 1.15.72 version on Debian Linux 10 (64-bit).

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Don't know.
- Can you reproduce this issue with the nightly channel? Don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? No. The reCAPTCHA with the Chrome works fine.

**Comment by diracdeltas** [comment]
we've gotten multiple reports of this and are investigating it. it's strange that this happens even with shields off.

**Comment by ryanbr** [comment]
@bandi88 Had a report that private window mode works, can you confirm?

**Comment by bandi88** [comment]
> @bandi88 Had a report that private window mode works, can you confirm?

I tried it recently. Neither private window nor the private Tor window worked. reCAPTCHA was every time very problematic (like I wrote).

**Comment by ZachariahRosenberg** [comment]
Same problem. I've found that switching to the audio version of the recaptcha often works. 

To make sure it was specifically with Brave, I open up the following demo on Chrome, Safari, Firefox, Vivaldi - no issues: https://patrickhlauke.github.io/recaptcha/ (just a demo recaptcha site). All browsers passed immediately, whereas brave standard, brave private and brave tor all failed. Shields down, failed.

Audio recaptcha was fine.

**Comment by bandi88** [comment]
> Same problem. I've found that switching to the audio version of the recaptcha often works.
> 
> To make sure it was specifically with Brave, I open up the following demo on Chrome, Safari, Firefox, Vivaldi - no issues: https://patrickhlauke.github.io/recaptcha/ (just a demo recaptcha site). All browsers passed immediately, whereas brave standard, brave private and brave tor all failed. Shields down, failed.
> 
> Audio recaptcha was fine.

I have also problems with the audio reCAPTCHA with Brave: many times I have to solve 3-4 audio captchas, one is not enough for the Google's thing! 

I hope, soon we will get a solution for that. Because reCAPTCHA is too much popular, almost all websites are using it (many of them invisibile, like Paypal for example).

**Comment by snowbound** [comment]
MS edge on the left and Brave Beta on the right

https://1drv.ms/u/s!AjeWNAchT2Ixm493Ez9OHt1bozMtNQ?e=iQ47fz

**Comment by ohmnominal** [comment]
Not sure if it contributes anything but I wasn't having this issue until I cleared my cache/cookies for a non-Brave issue I was troubleshooting. Once I cleared those, I began having the captcha issue, along with most sites not remembering I'm logged in.

**Comment by bandi88** [comment]
> Not sure if it contributes anything but I wasn't having this issue until I cleared my cache/cookies for a non-Brave issue I was troubleshooting. Once I cleared those, I began having the captcha issue, along with most sites not remembering I'm logged in.

I think, that Google introduced something recently, which leads Brave to fail. I started using Brave on 11st October 2020, but only had the issue first on 13rd October. I did not delete anything. But fresh installation of Brave is of course as cleared cache. :)

**Comment by mhidro** [comment]
Had the same problem, it was finally resolved after allowing third party cookies and clearing all cookies.

**Comment by bandi88** [comment]
> 
> 
> Had the same problem, it was finally resolved after allowing third party cookies and clearing all cookies.

But is is not a final solution. In Firefox I can also use reCAPTCHA even in "strict mode" (where third-party cookies are not allowed). So, that issue seems related to the Brave browser.

**Comment by User5579** [comment]
Hello, I just wanted to add my comments. I am a new Brave user, migrating from Chrome. I see you are actively working on this issue, however Brave is unusable in its current state for a regular user. CAPTCHA's are appearing for near-every website in both standard and private browsing mode, and they often require 5-10 correct solutions before allowing the user to proceed. 

I have disabled all global shield settings, to no avail. 

I hope you all are able to resolve this! Love the browser so far but, as I mentioned, this does make the browser unusable.

**Comment by okidokiokami** [comment]
I just tested this in Nightly - I am still getting sluggish load times on the photos, but the reCAPTCHA verified me after one round (instead of 10 or so like I was experiencing in production).

**Comment by kjozwiak** [comment]
Labeling this as `QA/No` as this didn't fix the issue. However, we'll still uplift this into https://github.com/brave/brave-core/pull/6968  & https://github.com/brave/brave-core/pull/6969 as per earlier discussions. @pilgrim-brave will implement farbling for `navigator.deviceMemory` via https://github.com/brave/brave-core/pull/6964.

However, @bsclifton and others are still looking into fixing the above. Seems like Nightly was fixed once C87 landed last night so we're looking into what could have possibly fixed the problem so we can uplift into the appropriate channels and release a hotfix ASAP.

**Comment by bsclifton** [comment]
Marked as `release-notes/exclude` since this didn't fix the issue. New issue created with https://github.com/brave/brave-browser/issues/12359; fixed in master (1.18.x) with https://github.com/brave/brave-core/pull/6554 and fixed in 1.16 with https://github.com/brave/brave-core/pull/6993. 1.17.x will get the fix when Chromium 87 is uplifted

**Comment by kjozwiak** [comment]
@brave/legacy_qa because this didn't resolve the CAPTCHA issue, some of the cases mentioned via https://github.com/brave/brave-core/pull/6965#issue-510982570 are not valid for this particular issue. However, we'll need to check the following:

* `navigator.deviceMemory` should return a number via the browser console rather than `undefined`
* https://antoinevastel.com/bots/ and confirm that everything is green as per the screenshot https://github.com/brave/brave-core/pull/6965#issue-510982570.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.16.71 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.15.7 (Build 19H2)
```

* verified that `navigator.deviceMemory` returns a value rather than `undefined` due to the revert
* verified that `Result of Fp-scanner` under https://antoinevastel.com/bots/ appears green

**`navigator.deviceMemory`** | **`Fp-scanner results`**
-------------------------------|---------------------------
![Screen Shot 2020-11-02 at 9 17 36 PM](https://user-images.githubusercontent.com/2602313/97939809-dfdc8c80-1d59-11eb-87cb-a6f17d07a46d.png) | ![Screen Shot 2020-11-02 at 9 20 56 PM](https://user-images.githubusercontent.com/2602313/97939856-e2d77d00-1d59-11eb-8898-04a6480cb2f3.png)

**Comment by vanrijmenam** [comment]
Has this problem been fixed as I am experiencing the same problem on any website. I use the latest version of the Brave browser on the latest version of Mac OS. The same problem also happen on iOS.

**Comment by coswise** [comment]
I tried the stable, beta and nightly versions of the browsers and unfortunately, it seems that all of them are affected by the reCaptcha problem.  The browser version is V1.27.109 (July 27, 2021) and the issue is mainly with Google Search.
