### ISSUE TITLE
`QR Code for iOS Rewards users transferring BAT` is not translated in `brave://rewards`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#12282]
Follow up to https://github.com/brave/brave-browser/issues/12176. The new strings are not translated

## Steps to Reproduce

   1. Enable Rewards
   2. Open `brave://rewards`

## Actual result:

`QR Code for iOS Rewards users transferring BAT` is not translated
`QR Code` is not translated
![image](https://user-images.githubusercontent.com/34715963/96924363-d5e1a080-14b2-11eb-9d8f-3548970fd34e.png)
![image](https://user-images.githubusercontent.com/34715963/96924316-c6625780-14b2-11eb-8386-9678211ae2dd.png)

## Expected result:
`QR Code for iOS Rewards users transferring BAT` is translated
`QR Code` is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @mkarolin

**Comment by BAT-HMA** [comment]
the QR code not appearing in my brave://rewards
![BAT-not](https://user-images.githubusercontent.com/76077872/102287692-f6553680-3f08-11eb-80d5-729d0ea8b0b6.JPG)

thus, I have no way of transferring my BAT tokens from my iPhone.
very disappointing of Brave, will no longer be a User nor content creator.

**Comment by LaurenWags** [comment]
@BAT-HMA QR code to be implemented with https://github.com/brave/brave-browser/issues/13159. You'll want to follow that issue for the most current updates and target release.

**Comment by mukarimin** [comment]
https://publishers.basicattentiontoken.org/publishers/f3aa93d1-046c-4fb9-8fde-93b1e0b32761?token=5f17a255062f12bbea25a793b669e42868df378619502ef23f1005dfd9e7e1a7

**Comment by rebron** [comment]
@btlechowski Is this still an issue?

**Comment by btlechowski** [comment]
It is fixed

Verification passed on

Brave | 1.21.52 Chromium: 88.0.4324.152 (Official Build) dev (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/107811898-2f761f80-6d6f-11eb-9a41-a456f48272e0.png)
