### ISSUE TITLE
Wrong publisher in Rewards Panel on youtube

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#12281]
Sometimes previous publisher shows up in Rewards Panel

Note: This is a regression introduced in 1.16.x

## Steps to Reproduce

   1. Clean profile
   1. Enable Rewards on staging
   1. Open `https://www.youtube.com/channel/UCCs7AQEDwrHEc86r0NNXE_A`
   1. Open Rewards Panel
   1. Click Youtube logo on youtube page
   1. Click on a creators name that has a custom youtube URL (e.g. https://www.youtube.com/c/Mixes)
   1. Open Rewards Panel

Note: Best to check the recording
![wrong_publisher_info](https://user-images.githubusercontent.com/34715963/96915213-446c3180-14a6-11eb-82e3-31e80a06d553.gif)

Note: Proper publisher is shown after page reload

## Actual result:

Wrong publisher in Rewards Panel
![image](https://user-images.githubusercontent.com/34715963/96915160-36b6ac00-14a6-11eb-8b4f-7c91d971fd5c.png)

## Expected result:
Proper publisher in Rewards Panel

![image](https://user-images.githubusercontent.com/34715963/96915314-64035a00-14a6-11eb-995a-853284b483ee.png)

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

**Reproducible on**

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

Brave | 1.17.45 Chromium: 86.0.4240.99 (Official Build) dev (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Ubuntu 18.04 LTS

Brave | 1.18.5 Chromium: 86.0.4240.111 (Official Build) nightly (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

**Not reproducible on**

Brave | 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @NejcZdovc

**Comment by emerick** [comment]
I think this is happening when you go from a YouTube channel page to a custom YouTube URL. We saw something similar with YouTube user URLs during development. YouTube was updating the page on navigation, but certain DOM elements that we relied on for determining where we were (like scripts) remained the same and so were pointing to old data post-navigation. The fix is to always fetch custom URLs, just like we do user URLs.

**Comment by emerick** [comment]
Fix will be available in Greaselion `1.0.33`.

**Comment by kjozwiak** [comment]
@LaurenWags and myself ran through the above on staging as per https://github.com/brave/brave-site-specific-scripts/pull/23#issuecomment-716783675 & https://github.com/brave/brave-site-specific-scripts/pull/23#issuecomment-716786192. Pushing these changes live.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

`Brave Local Data Updater - Version: 1.0.33`
![image](https://user-images.githubusercontent.com/34715963/97227168-6252d280-17d5-11eb-8ab5-cd0ac6b6cf47.png)

Verified test plan from https://github.com/brave/brave-site-specific-scripts/pull/23

Verified proper publisher is shown for https://www.youtube.com/channel/UCCs7AQEDwrHEc86r0NNXE_A
![image](https://user-images.githubusercontent.com/34715963/97227255-81516480-17d5-11eb-92f8-f3482a428ad2.png)

Verified that after browsing youtube, proper publisher is shown for custom youtube url
![image](https://user-images.githubusercontent.com/34715963/97227489-d8573980-17d5-11eb-8645-dde880566401.png)
