### ISSUE TITLE
Ads switch remained enabled after resetting rewards

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12298]
## Description 

Found while testing https://github.com/brave/brave-core/pull/6915
Ads switch remained enabled after resetting rewards

## Steps to Reproduce

   1. Launch brave `1.18.8` 
   2. Open the rewards panel and click on `Rewards Settings`
   3. Enable both `Ads` and `Auto Contribute` switches in brave://rewards page
   4. Click on the gear icon and reset the rewards
   5. Once rewards is reset `Ads` switch is still enabled, sometimes `Sorry, Ads not yet available in your region` message is displayed, in this case, if we reload brave://rewards fixes the Ads switch issue, as well as the message, gets disappeared
   
**Note**: Refresh/reload brave://rewards fixes the issue.

## Actual result:

Ads switch remained enabled after resetting rewards
![image](https://user-images.githubusercontent.com/38657976/97038956-3e02b600-1589-11eb-83b7-ac02a3278b5a.png)

## Expected result:
Ads switch should be turned off after resetting rewards as the default state is OFF

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.8 Chromium: 86.0.4240.111 (Official Build) nightly (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @jsecretan @rebron

**Comment by tmancey** [comment]
@GeetaSarvadnya Can you please retest as when re-enabling Rewards, it is correct that ads is enabled. This is a part of Rewards Everywhere. Thanks
