### ISSUE TITLE
Bookmarks not importing properly from Firefox

### ISSUE THREAD

**Issue by fislysandi** [brave/brave-browser#12294]
## Steps to Reproduce

   1. import data from firefox
   2. wait a bit
   3. get this

## Actual result:
![Screenshot_41](https://user-images.githubusercontent.com/45166203/97001954-edb43580-1541-11eb-982d-2707d25f916a.png)

## Expected result:
all of the bookmarks displayed on the bar instead in the folders

## Reproduces how often: 
 i dont really know

## Brave version (brave://version info)
latest version

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yese

## Other Additional Information:

- no
- no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by bsclifton** [comment]
@fislysandi did you accidentally pick Chrome? Looking at your screenshot, it seems you had imported from there instead of Firefox

It's safe to try again - please let us know. Thanks 😄

**Comment by rebron** [comment]
@fislysandi are you able to import from html (file) from Firefox into Brave?
