### ISSUE TITLE
Hide token modal details not visible on dark theme [Crypto Wallets]

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12290]
## Description 
Hide token modal is broken on dark theme

## Steps to Reproduce
   1.  Add a custom ERC-20 token to your account (using dark theme)
   2. Click on the token in the account view
   3. Via the top-right menu, click "Hide token"

## Actual result:
<img width="1162" alt="Screen Shot 2020-10-23 at 1 49 14 AM" src="https://user-images.githubusercontent.com/8732757/96981443-7bf1d280-14d4-11eb-8e7f-d2c62144ecd2.png">

## Expected result:
<img width="1189" alt="Screen Shot 2020-10-23 at 1 47 40 AM" src="https://user-images.githubusercontent.com/8732757/96981517-7f855980-14d4-11eb-899d-3530af1847d9.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit) 
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Linux
Component | `1.0.16 dev`

- Verified hide token modal shows details on dark mode for custom tokens
![image](https://user-images.githubusercontent.com/17010094/97420133-d4750580-1902-11eb-9e6d-2dd424fa8dd2.png)

---------------------

Verification passed on 

Brave | 1.17.50 Chromium: 86.0.4240.111 (Official Build) dev (64-bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Windows 10 OS Version 1809 (Build 17763.1518)
Component | `1.0.16 dev`

- Verified hide token modal shows details on dark mode for custom tokens
![image](https://user-images.githubusercontent.com/17010094/97420157-df2f9a80-1902-11eb-8de4-9412a200f122.png)

---------------------
Verification passed on 

Brave | 1.18.5 Chromium: 86.0.4240.111 (Official Build) nightly (x86_64)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | macOS Version 10.15.7 (Build 19H2)
Component | `1.0.16 dev`

- Verified hide token modal shows details on dark mode for custom tokens
![image](https://user-images.githubusercontent.com/17010094/97420146-da6ae680-1902-11eb-8b18-e1f72ef8ceb1.png)
