### ISSUE TITLE
After resetting rewards `Your wallet` text is displayed instead of uphold login 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12299]
## Description 

Found while testing brave/brave-core#6915
After resetting rewards `Your wallet` text is displayed instead of uphold login 
## Steps to Reproduce

   1. Launch brave `1.18.8` 
   2. Open the rewards panel and click on `Rewards Settings`
   3. Enable both `Ads` and `Auto Contribute` switches in brave://rewards page
   4. Click on the gear icon and reset the rewards
   5. After resetting rewards `Your wallet` text is shown in both settings and rewards panel
   
**Note**: Reload brave://rewards will not fix the issue, but exit and re-launch browser will fix the issue

## Actual result:

After resetting rewards `Your wallet` text is displayed instead of uphold login 
![image](https://user-images.githubusercontent.com/38657976/97041325-06960880-158d-11eb-8893-862ea2fb4843.png)

## Expected result:
Verify wallet uphold login button should be displayed

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.8 Chromium: 86.0.4240.111 (Official Build) nightly (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

CC: @brave/legacy_qa @NejcZdovc @rebron

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.18.62 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
Revision	0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS	macOS Version 10.14.6 (Build 18G6042)
```

Verified STR from description.

-----------
