### ISSUE TITLE
Enable blocklist_extension_fetcher

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#12297]
Source here: https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/extensions/blocklist_state_fetcher.cc

Community reports:
- https://community.brave.com/t/brave-is-not-disabling-or-marking-extensions-that-have-been-removed-from-the-chrome-web-store-as-malware/112122
- https://community.brave.com/t/privacy-and-security-bug-brave-not-disabling-extensions-removed-from-the-chrome-web-store-as-malware-e-g-nano-defender/173533
- https://www.reddit.com/r/brave_browser/comments/jgifxa/privacy_and_security_bug_brave_not_disabling/

**Comment by fmarier** [comment]
Looks like https://github.com/brave/brave-browser/issues/4674 will be needed first since the Google endpoint is https://safebrowsing.google.com/safebrowsing/clientreport/crx-list-info which we don't currently have a proxy for.

**Comment by fmarier** [comment]
There's no easy way to test the extension blocking functionality, but it's covered somewhat by a unit test.

What I would suggest instead as a test plan is to ensure that we didn't break download protection:

1. Open https://testsafebrowsing.appspot.com/
2. Check that all links in the "Desktop Download Warnings" lead to blocked downloads.

**Comment by LaurenWags** [comment]
Verified using

```
Brave	1.21.64 Chromium: 88.0.4324.182 (Official Build) beta (x86_64)
Revision	73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS	macOS Version 10.15.7 (Build 19H512)
```

Verified test plan from https://github.com/brave/brave-browser/issues/12297#issuecomment-775376042. Confirmed all links under "Desktop Download Warnings" were blocked.

Example | Example
----- | -----
<img width="1008" alt="Screen Shot 2021-02-22 at 10 20 53 AM" src="https://user-images.githubusercontent.com/28145373/108729105-2f58eb00-74f8-11eb-9f5b-fa18fdf05d45.png"> | <img width="1137" alt="Screen Shot 2021-02-22 at 10 20 40 AM" src="https://user-images.githubusercontent.com/28145373/108729111-308a1800-74f8-11eb-808c-b43cc947faf2.png">
