### ISSUE TITLE
Are the Brave binaries proprietary?

### ISSUE THREAD

**Issue by resynth1943** [brave/brave-browser#12293]
I'd like to be sure you're not [attempting to dupe people like Microsoft](https://github.com/microsoft/vscode/pull/107805). 

So, are the binaries downloaded from the Brave website; the Brave Linux software repositories; and any other official sources licensed under an *open-source* license? Can I confirm this with yourselves here, please?

After reading the Terms and Conditions, this seems to be of interest:

> Brave Browser License
> The executable code version of the Brave browser is made available under the terms set forth below. Source code for parts of the Brave browser may be available for use under open source licenses and accessible via https://github.com/brave. Nothing in this Agreement will be construed to limit any rights granted under such open source licenses with respect to code specifically covered by such licenses.
>
> Subject to the terms hereof, Brave grants you a personal, non-exclusive license to install and use the executable code version of the Brave browser. Brave and its licensors shall retain all intellectual property rights in the Brave browser (and Service), except for the rights expressly granted in this Agreement. You may not remove or alter any trademark, or logo (collectively, “Marks”), copyright or other proprietary notice on the Brave browser. This license does not grant you any right to use Marks of Brave or its licensors. If you breach this Agreement, the above license and your right to use the Brave browser will terminate immediately and without notice. Upon termination, you must destroy all copies of the Brave browser.

Many thanks,
Resynth

**Comment by resynth1943** [comment]
As an addendum: do the official binaries contain proprietary software of any form?

**Comment by bsclifton** [comment]
All of the code for the browser is available under MPL 2.0:
https://github.com/brave/brave-browser/blob/master/LICENSE

A bit confused by your query, so apologies. Are you asking what is the license for the binaries? Because of things such as signing, the binaries must be (and will only be produced) by Brave Software. The licensing terms for "executable form" apply to make sure that source code is available when distributing (per MPL 2.0), which we always do.

cc: @fmarier @diracdeltas

**Comment by resynth1943** [comment]
I'm asking if *every CPU instruction* that runs in the Brave binary is open-source. I've been told you add some proprietary extensions are added to Brave in the official binaries. Is this true?

Thank you for your above message. 👍🏼

**Comment by bsclifton** [comment]
@resynth1943 in the stock released binary, I'm not aware of any proprietary code. You can view licenses for everything at brave://credits/

That said, users can opt-into installing Widevine to stream content on websites such as Netflix. We direct the user to the Google servers for this and that code is indeed proprietary. Installing this is completely optional. There may be other extensions which are not open source on Google Web Store, but we don't include any by default

**Comment by fmarier** [comment]
> I'm asking if _every CPU instruction_ that runs in the Brave binary is open-source. I've been told you add some proprietary extensions are added to Brave in the official binaries. Is this true?

Like @bsclifton said, we don't directly bundle proprietary code with Brave. To answer your question more fully though, I have to say that it depends on the rest of your environment and which websites you are visiting:
- Are you using a 100% open source operating system with free drivers? Brave, and any other browser, makes use of operating system functionalities and so ends up executing proprietary instructions on proprietary operating systems.
- Are you visiting websites which provide [non-free Javascript](https://www.fsf.org/campaigns/freejs)? If so, then Brave will execute that code and end up running proprietary code, unless you disable scripts for that website via Brave Shields.
- Did you install extensions with Brave that are not Open Source? If so, Brave will execute their proprietary code.
- Did you visit a site which requires DRM without disabling that option in Brave settings? If so, then Brave will download and install Widevine from Google.

**Comment by resynth1943** [comment]
Alright. Apologies for the... intricate questions. I was just making sure this isn't a scam operation; after Microsoft conned the open-source community, I've become increasingly suspicious of open-source products which are owned by companies.

> Are you using a 100% open source operating system with free drivers?

Sadly not, the Nouevau driver is unusable, and doesn't support True 4K.

> Did you install extensions with Brave that are not Open Source? If so, Brave will execute their proprietary code.

I actually don't have any [extensions](https://resynth1943.net/articles/uninstall-nano-defender-immediately/), I suggest you do the same 😉 

> Did you visit a site which requires DRM without disabling that option in Brave settings? If so, then Brave will download and install Widevine from Google.

I don't use Widevine, or any websites which interact with Widevine. I'd rather torrent than support a company using anti-freedom technologies.

**Comment by A-childs-encyclopedia** [comment]
Isn't the crypto stuff proprietary?

**Comment by fmarier** [comment]
> Isn't the crypto stuff proprietary?

If you're talking about BAT / Brave Rewards, all of the client code for that is Open Source. It's in <https://github.com/brave/brave-browser> / <https://github.com/brave/brave-core>.

**Comment by A-childs-encyclopedia** [comment]
what about brave search

**Comment by fmarier** [comment]
The Search backend source code is not public, but the web discovery project client is (https://github.com/brave/web-discovery-project).
