### ISSUE TITLE
Creation stamp should be set on restore

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#12306]
## Steps to Reproduce

   1. go to rewards page
   2. restore wallet
   3. go to internals page

## Actual result:

it says wallet was not created

## Expected result:
wallet should be shown

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6042)
```

Verified STR from description.

----------------
