### ISSUE TITLE
Publisher not obtained until rewards extension starts

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#12307]
We should probably move api's for GL from rewards extension into brave extension (shields extension) which is running all the time. This way publisher can be always saved from GL

**Comment by emerick** [comment]
Just noting here that we'll also need to start the process when you click on the tip button, per @NejcZdovc.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.18.61 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6042)
```

Testing completed with https://github.com/brave/brave-browser/issues/6462#issuecomment-732240577

----------
