### ISSUE TITLE
MyQ website navigation links don't respond

### ISSUE THREAD

**Issue by stshank** [brave/brave-browser#12309]
## Description 
Clicking menu items at https://www.myq.com/ don't work unless I lower shields.

## Steps to Reproduce

   1. Go to https://www.myq.com/
   2. Click navigation links, e.g. "support" or "MyQ App | Check Compatibility"

## Actual result:
nothing happens

## Expected result:
links open

## Reproduces how often: 
Always.

## Brave version (brave://version info)

Brave | 1.17.48 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.15.7 (Build 19H2)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Yes

- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by ryanbr** [comment]
Hey @stshank  Give it 24-48hrs. should be fixed. Will keep this open to confirm everything is working.

**Comment by ryanbr** [comment]
Everything working here, how its looking for you @stshank  ?

**Comment by stshank** [comment]
All working fine for me, thanks!

**Comment by ryanbr** [comment]
Thanks for confirming 👍
