### ISSUE TITLE
Canvas farbling doesn't happen in disconnected iframes

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#12303]

**Comment by GeetaSarvadnya** [comment]
@pilgrim-brave Can you please link the test plan?

**Comment by LaurenWags** [comment]
cc @pes10k on https://github.com/brave/brave-browser/issues/12303#issuecomment-739937805

**Comment by pilgrim-brave** [comment]
Test plan:

1. Visit https://canvasblocker.kkapsner.de/test/test.html
2. In Brave Shields panel, change Fingerprinting to "Allow all fingerprinting"

>>> Each test shows two hash values. For the purposes of this plan, only look at the second hash value of each test (after the "/")

>>> If any test shows an error like "Error while computing: Blocked a frame with origin "https://canvasblocker.kkapsner.de" from accessing a cross-origin frame." then refresh the page until the error message disappears.

3. Hash for "iFrame Test. Thanks to DocumentRoot.", "iFrame Test 2 - with URL", "iFrame Test 3 - violating SOP", "iFrame Test 4 - different access 1", "iFrame Test 5 - different access 2", and "iFrame Test 6 - different access 3" should all be the same value. Note this hash value.
4. In Brave Shields panel, change Fingerprinting to "Blocked (standard)"

>>> Again, if any test shows an error like "Error while computing: Blocked a frame with origin "https://canvasblocker.kkapsner.de" from accessing a cross-origin frame." then refresh the page until the error message disappears.

5. Hash for the six tests listed in step 3 should all be the same value, but it should be a different value than the hash seen in step 3.

**Comment by GeetaSarvadnya** [comment]
Verification is passed on

```

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the test plan from https://github.com/brave/brave-browser/issues/12303#issuecomment-740106581

`iFrame Test. Thanks to DocumentRoot`
![image](https://user-images.githubusercontent.com/38657976/101443743-24a0a800-3944-11eb-9f21-16a1a2263e19.png)

`iFrame Test 2 - with URL`
![image](https://user-images.githubusercontent.com/38657976/101443825-4732c100-3944-11eb-8283-9265edbce3b2.png)

`iFrame Test 3 - violating SOP`
![image](https://user-images.githubusercontent.com/38657976/101443904-65002600-3944-11eb-8722-12047d37b6f5.png)

`iFrame Test 4 - different access 1`
![image](https://user-images.githubusercontent.com/38657976/101443940-7812f600-3944-11eb-96cf-9277ed8fd132.png)

`iFrame Test 5 - different access 2`
![image](https://user-images.githubusercontent.com/38657976/101443995-924cd400-3944-11eb-9acf-32b7877a2494.png)

`iFrame Test 6 - different access 3`
![image](https://user-images.githubusercontent.com/38657976/101444036-a7c1fe00-3944-11eb-9d86-4acd5bb67b88.png)
