### ISSUE TITLE
[Desktop] incorrect favicon for old reddit on panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12301]
## Description 

If you visit a non-verified publisher on old.reddit.com and open the panel, the generic world icon displays. However, if you visit this same publisher on reddit.com, you get the generic reddit icon.

If the publisher is verified but does not have their own custom favicon (for the tipping banner), then they also get the generic world icon until you visit them on reddit.com.

Note, if the publisher has a custom favicon for the tipping banner, this is not an issue.

## Steps to Reproduce

   1. Clean profile, enable rewards (staging env)
   2. Visit a non-verified publisher like old.reddit.com/user/brave_w0ts0n (non-verified publisher) or old.reddit.com/user/jsadler-brave (verified publisher without a custom tipping banner favicon).
   3. Wait a few seconds (due to https://github.com/brave/brave-browser/issues/12241)
   4. Open panel.

## Actual result:

<img width="406" alt="old reddit brave_w0ts0n" src="https://user-images.githubusercontent.com/28145373/97044943-e2add500-1542-11eb-9534-07b2ae2913f5.png">

<img width="398" alt="Screen Shot 2020-10-23 at 3 13 34 PM" src="https://user-images.githubusercontent.com/28145373/97044955-e7728900-1542-11eb-9433-7468487a539d.png">

## Expected result:
<img width="408" alt="Screen Shot 2020-10-23 at 3 18 43 PM" src="https://user-images.githubusercontent.com/28145373/97045087-1ee13580-1543-11eb-8c96-b843e3000246.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.48 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes, reproduces on 1.15.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @emerick

**Comment by Miyayes** [comment]
Does not reproduce anymore with Rewards panel 2.0
