### ISSUE TITLE
AccountConsistencyMethod should default to disabled on Android

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#12319]
## Description 
Android defaults to `Mirror` as the account consistency method. This should be explicitly set to disabled till extensions are enabled on android.

## Steps to reproduce 

   1. Navigate to brave://signin-internals

## Actual result 
account consistency method is Mirror

## Expected result
account consistency method should be none

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.15.76

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by jumde** [comment]
Fix reverted - causes DCHECK failure - https://github.com/brave/brave-core/pull/7040

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.18.51 x64 beta build
- Verified `Account Consistency` is set to none
![image](https://user-images.githubusercontent.com/17010094/99278809-6d72ae80-2827-11eb-9b9d-5826573f33f5.png)
----------
Verification passed on Samsung Tab A with Android 10 running 1.18.51 x64 beta build
- Verified `Account Consistency` is set to none
![image](https://user-images.githubusercontent.com/17010094/99279111-c2162980-2827-11eb-9149-a4c6b0ec0563.png)
