### ISSUE TITLE
Google Maps trackpad zoom is oversensitive 

### ISSUE THREAD

**Issue by stshank** [brave/brave-browser#12310]
## Description 
Google Maps zoom is very twitchy with two-finger drag up and down on trackpad.

## Steps to Reproduce

   1. Open maps.google.com
   2. Zoom in or out by swiping two fingers up or down

## Actual result:
Map view jumps dramatically across several levels of zoom. 

## Expected result:
Map view gradually zooms in or out.

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 1.17.48 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.15.7 (Build 19H2)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
no

- Is the issue reproducible on the latest version of Chrome? 
no

## Miscellaneous Information:
Using the + and - buttons on the website interface is a workaround, though it loses zoom animation steps that Chrome shows during the zoom level transition.

**Comment by kjozwiak** [comment]
Running into the above as well. It becomes really painful to use `Google Maps`. Takes a lot of patience to actually get it zoomed to your desired view. I just started using Google Maps on mobile instead when I need to check something quickly.

Reproduced on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.18.10 Chromium: 86.0.4240.111 (Official Build) nightly (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.15.7 (Build 19H2)
```

Also seems to be happening on `Win 10 x64` when using the trackpad. However, when you use a mouse with a wheel, experience is pretty good.

**Comment by kjozwiak** [comment]
@rebron mind checking this on your `Win 10 x64` laptop? Do you get the same experience/results when using the trackpad?

**Comment by rebron** [comment]
@kjozwiak Same fast zoom on Windows. I'm actually missing a "slow streets" layer as well which is showing up in Chrome. There is a slower, smoother scrolling.

cc: @pes10k @pilgrim-brave Any ideas on this one? maps.google.com has a smoother/slower zoom in/out behavior via trackpad on Windows or macOS in comparison to us where it's a much more faster/extreme zoom.

**Comment by darkdh** [comment]
If you take a closer look on zoom factor of url address, Brave doesn't allow floating number and will force it to be integer. Ex, if you paste `https://www.google.com/maps/@37.7744444,-122.4115361,12.68z`, brave will force it to be `12z`
The reason we feel it is sensitive because Brave increase/decrease the factor by 1, while other browsers can do it by granular fraction

**Comment by fabricapo** [comment]
+1 on this one. It makes me consider going back to Google Chrome, sadly

**Comment by kaytwo** [comment]
Can y'all check whether GPU rendering is available on Google Maps? Switch to satellite view -> check the lower right hand corner for "3D Earth is not available" text. If the text is there, then you're using the tile based map rather than the vector/GPU based map which has far fewer features.

I think these complaints are all a symptom of a much more annoying problem, that Google Maps isn't serving the GPU accelerated version of the app to Brave. That feature enables fractional zoom, 3d buildings, and a lot of other QOL stuff.

**Comment by fabricapo** [comment]
Nope, I do not see the "3D Earth is not available" text when I switch to Satellite view. 

"Google Maps isn't serving the GPU accelerated version of the app to Brave" means it will never happen, or do you think there will be a trick to activate it? If the probability is low, I'll move back to Chrome (sadly)

**Comment by stshank** [comment]
I do see the "3D Earth not available" text on Brave. However, IIRC Safari
doesn't advertise GPU availability and it zooms in and out smoothly. (I
could be out of date re. Safari.)

>

**Comment by pes10k** [comment]
Hi @stshank @kaytwo and @fabricapo, i have a candidate for the issue here (looks like one of our WebGL related fingerprinting protections is getting applied w/o checking whether shields is at "default" or "max" protections).  Im working testing a fix now and hope to have a solution (or at least crossed off a potential cause) shortly.  Thanks all for your help!

**Comment by kaytwo** [comment]
Awesome! FYI I run www.google.com with shields down and am still seeing this issue. Feel free to ask for more info.

**Comment by pes10k** [comment]
@stshank @kaytwo and @fabricapo just a heads up that a fix for this is in nightly now, should be in the next nightly build, and will get uplifted to 1.17.  Thanks again for the reports and help!

**Comment by kaytwo** [comment]
Thanks! Fix works for bringing back GPU accelerated (vector maps, fractional zoom) maps, but Brave seems to not be getting the 3d version of satellite maps, even in nightly with shields down. I can definitely open a new issue for this, I dunno how many other people are having this issue.

**Comment by pes10k** [comment]
@kaytwo how can i test for that?  I can get a 3d version of google maps (nightly, macos build here, 1.18.43), though I dont know if its touching the GPU. Is there a place you're checking that explicitly says "3d accelerated" and it says no?  Or are you just not getting any 3d version at all?
<img width="812" alt="Screen Shot 2020-11-09 at 8 13 08 PM" src="https://user-images.githubusercontent.com/76526/98627028-0bb2c180-22c8-11eb-8854-b0f9753ae3ab.png">

Also, i know we had some issues a while back with GPU's not getting trigged on some linux machines (iirc, some chromium-side GPU code was only being turned on by Google's field-trials code, so was off for all Brave users).  I think we sorted that out, but if you're on linux that might be the issue.  If thats the case, can you let me know what you see at brave://gpu/ and I can make sure the right people see it?

Thanks again! :)

**Comment by kaytwo** [comment]
I figured it out. My Chrome install had logged me in to Google so it was picking up my "default to globe view" setting, but Brave Nightly didn't have that, and to get globe view you've got to click the little globe in the lower right hand corner. Everything works now, this is user error.

FWIW beta chrome://gpu and (beta & nightly) brave://gpu are bit for bit identical (however brave://gpu still sets the page title to chrome://gpu).

Thanks for following up!

**Comment by pes10k** [comment]
Phew! Thanks for letting me know @kaytwo , glad its sorted :)

**Comment by yamnitsky** [comment]
> Can y'all check whether GPU rendering is available on Google Maps? Switch to satellite view -> check the lower right hand corner for "3D Earth is not available" text. If the text is there, then you're using the tile based map rather than the vector/GPU based map which has far fewer features.
> 
> I think these complaints are all a symptom of a much more annoying problem, that Google Maps isn't serving the GPU accelerated version of the app to Brave. That feature enables fractional zoom, 3d buildings, and a lot of other QOL stuff.

My Google Maps is doing the weird zooming thing for the past few days, and I just checked and it says "3D Earth is not available". Shields are down for all google sites for me -- how do I fix this?

**Comment by kaytwo** [comment]
Are you on Beta or release channel? The fix for this issue is currently in nightly but not yet in Beta/Release.

**Comment by yamnitsky** [comment]
I believe I'm on the release channel, Version 1.16.75 Chromium: 86.0.4240.193 (Official Build) (x86_64)

**Comment by rebron** [comment]
Verified that zooming in and out is looking good for me, smoother scrolling as expected versus scrolling several levels on swipe up/down or pinch on:

Brave | 1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 11.0.1 (Build 20B29)

**Comment by stshank** [comment]
Ah, yes, now working for me as well on Brave dev channel.
________________________________

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.15.7 (Build 19H2)
```

Ensured that zooming in/out via the mouse/trackpad wasn't as sensitive as before.

**Comment by mattmodarres** [comment]
I'm still experiencing this issue with Brave 1.17.73 on Mac OS 11.0.1.

**Comment by pes10k** [comment]
@mattmodarres do you have strict / max fingerprinting protections?  If so, then this is not a bug; those are advertised as potentially breaking sites.

if you're seeing the issue in the default configuration, please let us know

**Comment by iatenothingbutriceforthreedays** [comment]
I am experiencing this same issue with Brave 1.43.89 on Mac OS 10.14.6. Scroll-to-zoom is way too sensitive and there's no smooth transition between zoom levels.
I have fingerprinting protections set to Standard, and disabling those makes no difference to the issue.

**Comment by pes10k** [comment]
@iatenothingbutriceforthreedays do you have other extensions installed?  I am testing with a similar setup and cannot reproduce once i let google maps full load.  Can you double check you can reproduce with no extensions enabled and all browser settings at default?

**Comment by pasolid** [comment]
I started experiencing the same issue after updating Brave to 1.45.134 on MacOS 12.5 Monterey.
Supper inconvenient. It's like I'm jumping from world view to closest view with hardly swiping on the trackpad (both magic pad and mac pad).

**Comment by pes10k** [comment]
@pasolid do you have fingerprinting protections in the default setting, or the aggressive setting?  If the latter, this is *(unfortunately) expected behavior. The choppy scrolling is what Google Maps does if you don't report information about your graphics card to Google

**Comment by tylerpharand** [comment]
In case it helps anyone, I recently started using the [ScrollMaps](https://chrome.google.com/webstore/detail/scrollmaps/jifommjndpnefcfplgnbhabocomgdjjg) extension to work around this issue. It uses a pinch gesture for zooming and is way less sensitive.

**Comment by NayamAmarshe** [comment]
Still an issue on Linux.

**Comment by pes10k** [comment]
If folks have aggressive fingerprinting protections enabled, this is not a bug, it’s expected behavior. If you have standard fingerprinting protections enabled, please confirm with the version and we’ll get it sorted. Thanks!On Jan 3, 2023, at 13:59, NayamAmarshe ***@***.***> wrote:﻿
Still an issue on Linux.

**Comment by NayamAmarshe** [comment]
> If folks have aggressive fingerprinting protections enabled, this is not a bug, it’s expected behavior. If you have standard fingerprinting protections enabled, please confirm with the version and we’ll get it sorted. Thanks!On Jan 3, 2023, at 13:59, NayamAmarshe ***@***.***> wrote:﻿ Still an issue on Linux. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

Ah thanks for the reply. I checked and yes, it indeed was set to 'block aggressive fingerprinting'. It's much smoother now. Thanks a lot! I'm on v1.46.144 btw.

**Comment by NayamAmarshe** [comment]
This problem has returned, not sure why. I'm on v1.52.126. Even after turning off shields, enabling/disabling HW acceleration, google maps zoom is jumpy.

I'm on Manjaro Wayland.

**Comment by kjozwiak** [comment]
> This problem has returned, not sure why. I'm on v1.52.126. Even after turning off shields, enabling/disabling HW acceleration, google maps zoom is jumpy.
> 
> I'm on Manjaro Wayland.

@NayamAmarshe mind creating a new issue (similar to this one) [here](https://github.com/brave/brave-browser/issues/new?assignees=&labels=OS%2FDesktop&projects=&template=desktop.md&title=). Once created, we'll see if we can reproduce/triage if needed.

**Comment by michaeltrollan** [comment]
For anyone who ends up in this issue and none of the other solutions are working, here is a short guide:

First, try going to Google Maps in an incognito window. (File > New Private Window). If the scrolling is smooth there, then likely it's a settings issue, and you might be seeing the "lite" version of Google Maps.

This YouTube video has 9 possible solutions. https://www.youtube.com/watch?v=n5skrIePo50

(For me, it was the 2nd solution that permanently fixed it in Brave.)

**Comment by mohith7548** [comment]
[https://www.google.com/maps?force=webgl](https://www.google.com/maps?force=webgl) worked for me.

**Comment by NayamAmarshe** [comment]
> https://www.google.com/maps?force=webgl worked for me.

Oh wow! Thank you, this works well! How did you find it?
