### ISSUE TITLE
"incorrect password" when attempting to log into Netflix

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12323]
## Description 

We've received several reports via https://community.brave.com/t/im-having-issue-logging-in-to-netflix/173535 that users are running into issues logging into Netflix. When logging in, Netflix will display a "Incorrect password" message even though it's the correct password. I've actually ran into the above issue several times on my `Win 10 x64` machine.

After ~15-20 login attempts, it finally worked. @rebron mentioned that clearing cache fixed his issue but it didn't work for me. After clearing cookies/entire cache, I still ran into the same issue.

Wondering if this is something on Netflix side? Message seems like they're having issues.

## Steps to Reproduce

   1. launch the latest brave (`1.16.68 CR: 86.0.4240.111` in this case)
   2. go to https://www.netflix.com and attempt to login

## Actual result:

![Screenshot 2020-10-26 131601](https://user-images.githubusercontent.com/2602313/97209719-0e26fe80-1793-11eb-9a76-d9b317869c25.jpg)

## Expected result:

Should be able to log into Netflix without any issues

## Reproduces how often: 

It really varies. But I can reproduce almost 100% on `Win x64`. Seems to be working fine on `macOS`.

## Brave version (brave://version info)

```
Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? - Can't seem to reproduce
- Can you reproduce this issue with the nightly channel? - Can't seem to reproduce

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by Ross-McCandless** [comment]
I'm using Windows 10. I was experiencing this issue and disabling the shields for Netflix.com fixed it for me.

**Comment by rebron** [comment]
Closing as stale and per this last comment. Re-open if still having issues.
