### ISSUE TITLE
[Android] Bytecode: move patches for ToolbarPhone to asm

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#12322]
As per code review suggestion https://github.com/brave/brave-core/pull/6554#discussion_r510318727
We need to move patches for ToolbarPhone to asm.

As a test plan: we should re-check that all UI elements in top and bottom toolbar did not regress (including different modes, such as overview, landscape etc.).

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.22.58 x64 build
- Verified bottom toolbar and top toolbar works as expected. 
- Ran into #14211 which is a known issue
