### ISSUE TITLE
Embedded "GIF" Videos Suppress Ad Notifications

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#12326]
## Description 

For performance and storage reasons, some popular sites use small videos in the place of GIFs. Presently, Brave considers them media and will not show an ad notification when a tab hosting this type of media is focused.

## Steps to Reproduce
1. Navigate to https://sampson.codes/brave/tests/ads/video-gifs.html
2. Click 'play'
3. Watch console debug output for idle-state indicator
4. Bring Brave out of idle state

## Actual result:
Brave chooses not to show an ad notification.

## Expected result:
GIF substitutes should not prevent ad notifications from being shown.

## Brave version (brave://version info)
Brave | 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 10 OS Version 2004 (Build 19041.572)

## Miscellaneous Information:
![image](https://user-images.githubusercontent.com/815158/97216853-6ad6e900-1794-11eb-88f7-7817aedd2d15.png)

**Comment by tmancey** [comment]
@jonathansampson There does not appear to be a way to detect the type of media that is playing.
