### ISSUE TITLE
Don't log rewards in incognito

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1232]
regular sites and media publishers

**Comment by bbondy** [comment]
Is this to a log file or just to console with LOG(ERROR)?

**Comment by NejcZdovc** [comment]
this is logging sites for auto contribute while in incognito. This is more of an tracking issue, need to double check that we don't track it. If we are we need to remove it

**Comment by NejcZdovc** [comment]
@jasonrsadler you should be able to create wallet no matter where you are. But on private and tor windows you should only see wallet summary and no publisher data should be shown/saved

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

* Verified sites visited in Private/Guest/Tor windows are not listed in auto contribute
* Issues needs verification once #1450  is fixed
