### ISSUE TITLE
Ubuntu Snap breaks U2F/FIDO authentication

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#12320]
A community member reports that YubiKeys are not working when using the Ubuntu snap: https://community.brave.com/t/yubikey-not-working-using-brave-on-ubuntu-20-04/168773/12

brave 1.15.76 82 latest/stable brave

**Comment by bsclifton** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/6782
