### ISSUE TITLE
tipping panel should also link to privacy policy

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#12334]
in brave://rewards/, we link to both the ToS and privacy policy (https://brave.com/privacy/#rewards). the tipping panel only links the ToS:

<img width="1116" alt="Screen Shot 2020-10-26 at 4 14 19 PM" src="https://user-images.githubusercontent.com/549654/97238442-ae3a5300-17a6-11eb-9ff7-a91b144af5cc.png">

for consistency, we should probably link to the privacy policy there as well.

cc @PrivacyMatters @mandar-brave

**Comment by PrivacyMatters** [comment]
It would perhaps be worth reconsidering what is the purpose of the "by proceeding you agree to the Terms of Service,"  in this context and which is aimed at the person seeking to tip. Tipping is only possible if a person has joined rewards AFAIK so a person would already have been presented with the statement "By clicking ‘Join Rewards’, you indicate that you have read and agree to the Terms of Service and Privacy Policy." 

It seems unwarranted to require people to agree again (and I don't believe anyone should be forced to agree to a privacy policy). If it is felt a statement is necessary (what value does it add in this context? what is the benefit to the individual? To Brave?) then I would recommend Brave considers a simple statement along the lines "Tipping is subject to our T&Cs and Privacy Policy"

https://brave.com/tips/#:~:text=When%20you%20visit%20Twitter%20in,Brave%20Rewards%20account%20within%20minutes. 

![image001](https://user-images.githubusercontent.com/41578351/97282951-336d4880-1837-11eb-895d-2ea7e6a1cc05.png)

**Comment by NejcZdovc** [comment]
@PrivacyMatters with version 1.18 we don't have join rewards as we introduced Rewards Everywhere

**Comment by PrivacyMatters** [comment]
> @PrivacyMatters with version 1.18 we don't have join rewards as we introduced Rewards Everywhere

The image I posted is from my wife's computer. That's her experience. No wallet. And s no additional identifier such as the wallet ID. 

So the image posted by Yan here https://github.com/brave/brave-browser/issues/12334#issue-729973197 is for current or planned experience. Isn't it the case that tipping will remain opt-in under Rewards Everywhere and if so, at that point people will need to agree.

Is there a revised flow of the customer experience for rewards everywhere - https://github.com/brave/security/issues/72

**Comment by NejcZdovc** [comment]
@PrivacyMatters we have this in Nightly, so probably not on your wife's computer. Tipping is not opt in, ads and ac is

**Comment by PrivacyMatters** [comment]
Thx @NejcZdovc have been using Nightly since your recommendation ;) I haven't noticed a difference .. but then I had already signed into Brave rewards. There are so many threads both on here and a on slack, that it's hard to keep track.

Are you able to point me to a document that sets out the new experience for those who at point of update had not joined Brave. For example, we currently say "If you switch on Brave Rewards you are assigned a “wallet” identifier by Uphold, our payments partner."

**Comment by NejcZdovc** [comment]
will send you link to RE spec via DM

**Comment by mandar-brave** [comment]
@diracdeltas @PrivacyMatters i don't agree with this issue at all; we need to inform users at a broad level - this issue will essentially promote not giving at all; we have agreed to adding things in our Uphold linkage and that should be it. We build features so that users can use them w/o being scared every 2 minutes. Lets create a meeting so we can discuss - from a product POV, this is overdoing it considering we already agreed to add the needed text to the Uphold connection.

**Comment by PrivacyMatters** [comment]
@mandar-brave I'm not sure what issue you're referring to, what it is people will be scared of or what is overdoing it.  In my comments above I referred to existing positions of Brave - for example, https://support.brave.com/hc/en-us/articles/360018123651-How-do-I-use-Brave-Rewards- and that need to be considered with regards changes to those documented positions and perceptions of Brave.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6972
- Verified ToS and PP in tipping banner from both BR panel and inline tipping banner
- Verified both clean and upgraded profile
**Verified pubs:**
![image](https://user-images.githubusercontent.com/38657976/100051038-d6b67b00-2e40-11eb-9294-2bac79b105f4.png)
**Nonverified pubs:**
![image](https://user-images.githubusercontent.com/38657976/100051140-2bf28c80-2e41-11eb-9728-7c7910b94f00.png)
**Twitter:**
![image](https://user-images.githubusercontent.com/38657976/100051180-42004d00-2e41-11eb-806b-f0744682db4f.png)
**Reddit:**
![image](https://user-images.githubusercontent.com/38657976/100051238-5e9c8500-2e41-11eb-818d-f30b32edd117.png)
**GH**
![image](https://user-images.githubusercontent.com/38657976/100051454-f39f7e00-2e41-11eb-98fc-2c61f91e3aa3.png)
**YT**
![image](https://user-images.githubusercontent.com/38657976/100053208-8c83c880-2e45-11eb-9125-81be518968f4.png)
**Twitch**
![image](https://user-images.githubusercontent.com/38657976/100053283-b63cef80-2e45-11eb-818c-8516d6fd9bd5.png)

**Comment by PrivacyMatters** [comment]
Thanks @GeetaSarvadnya I assume if someone doesn't want to tip they can just select the X and go to settings as normal to set a default ?

**Comment by LaurenWags** [comment]
Hi @PrivacyMatters, if you select the "x" on the banner, the banner is closed and you are returned to the site you were viewing. Let me know if you have any additional questions!
