### ISSUE TITLE
Brave Together widget should be supported in all regions

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12333]
Currently on Nightly, the Brave Together widget on the NTP is only available in the United States and Canada. This check should change and allow it to be enabled from anywhere.

## Test Plan
1. Run Brave with a fresh profile using a multitude of regions
2. Ensure Brave Together can be turned on via the NTP settings

**Comment by ryanml** [comment]
Merged, re-targed for `1.18`

**Comment by LaurenWags** [comment]
marking as `QA/Blocked` for now, pending additional info cc @rebron @kjozwiak
