### ISSUE TITLE
Playback video fails on https://fivethirtyeight.com/videos/fewer-undecided-voters-is-good-news-for-biden-in-the-midwest/ 

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#12339]
## Description 
Video shows blank on `https://fivethirtyeight.com/videos/fewer-undecided-voters-is-good-news-for-biden-in-the-midwest/`

## Steps to Reproduce

   1. With default of shields
   2. Video doesn't playback on `https://fivethirtyeight.com/videos/fewer-undecided-voters-is-good-news-for-biden-in-the-midwest/`

## Actual result:
![five30-blank](https://user-images.githubusercontent.com/1659004/97244622-0e400080-185e-11eb-9969-d5ddd802700d.png)

## Expected result:
![five30-working](https://user-images.githubusercontent.com/1659004/97244632-14ce7800-185e-11eb-8a11-6a260987efe0.png)

## Brave version (brave://version info)
`Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

2 Shields settings needed to fix this: Site trackers/ads and allow all cookies is affecting this site.

Was reported: https://community.brave.com/t/fivethirtyeight-com-broken/174334

**Comment by ryanbr** [comment]
Playback is broken due to local storage on `fivethirtyeight.abcnews.go.com` 
![fix-five1](https://user-images.githubusercontent.com/1659004/103328321-50cfc480-4abd-11eb-9f3c-c0c43ebad693.png)
![fix-five](https://user-images.githubusercontent.com/1659004/103328325-562d0f00-4abd-11eb-9bd1-c0ddea32f709.png)

**Comment by rebron** [comment]
@ryanbr This is working in nightly, broken in beta and release. Fixed due to Chromium 89?

Brave | 1.22.19 Chromium: 89.0.4389.40 (Official Build) nightly (arm64)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | macOS Version 11.1 (Build 20C69)

**Comment by ryanbr** [comment]
Looks fixed in Beta, enabling Enable Ephemeral Storage in brave://flags seem to fix it. @rebron

**Comment by rebron** [comment]
Closing per last comment.
