### ISSUE TITLE
Farble navigator.deviceMemory instead of blocking it

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#12348]
Currently we block `navigator.deviceMemory` unconditionally. Instead, proposal:

 - If shields is off globally or anti-fingerprinting is off for a site, return the true value
 - if anti-fingerprinting is default, and true value is at least `0.5`, return a valid value between `0.5` and the true value (see https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory for valid values)
   - if true value is `0.25`, return true value
 - if anti-fingerprinting is maximum, return any valid value

Choice of value is determined by domain key and session key, as with other farbled values.

**Comment by pilgrim-brave** [comment]
Test plan:

1. Visit https://dev-pages.bravesoftware.com/farbling.html and set Fingerprinting to "Allow all" in the Brave Shields panel.
2. Visit https://dev-pages.brave.software/farbling.html and set Fingerprinting to "Allow all" in the Brave Shields panel.
3. Click 'Generate fingerprints"
4. In the 'Device Memory' row, you should see four identical hash values. Note this value.
5. Visit https://dev-pages.bravesoftware.com/farbling.html and set Fingerprinting to "Block (standard)" in the Brave Shields panel.
6. Visit https://dev-pages.brave.software/farbling.html and set Fingerprinting to "Block (standard)" in the Brave Shields panel.
7. Click 'Generate fingerprints"
8. In the 'Device Memory' row, you should see four identical hash values. This value should be different from the value in step 4.
9. Visit https://dev-pages.bravesoftware.com/farbling.html and set Fingerprinting to "Block (strict)" in the Brave Shields panel.
10. Visit https://dev-pages.brave.software/farbling.html and set Fingerprinting to "Block (strict)" in the Brave Shields panel.
11. Click 'Generate fingerprints"
12. In the 'Device Memory' row, you should see four identical hash values. This value should be different from the value in step 4. (Do not compare it to the value in step 8.)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the test plan from https://github.com/brave/brave-browser/issues/12348#issuecomment-740209082

Fingerprinting to "Allow all"  - **Device Memory**

- Verified that the 'Device Memory' row has four identical hash values when Fingerprinting is set to "Allow all"

https://dev-pages.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/38657976/101446450-6253ff80-3949-11eb-9b20-773d511d6cdf.png) | ![image](https://user-images.githubusercontent.com/38657976/101446386-42244080-3949-11eb-96d1-73f3f705bb83.png)

Fingerprinting to "Block (standard)"  - **Device Memory**

- Verified that the 'Device Memory' row has four identical hash values, these values are different from the above values.

https://dev-pages.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/38657976/101446762-e3ab9200-3949-11eb-8779-8eff14cffb17.png) | ![image](https://user-images.githubusercontent.com/38657976/101446777-ec9c6380-3949-11eb-9558-b53172ceb8af.png)

Fingerprinting to "Block (strict)" - **Device Memory**

- Verified that the 'Device Memory' row has four identical hash values in each frame, these values are different from the test `Fingerprinting to "Allow all"  - **Device Memory**`

https://dev-pages.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/38657976/101447525-68e37680-394b-11eb-912f-6ef3aeb2afbd.png) | ![image](https://user-images.githubusercontent.com/38657976/101447556-7436a200-394b-11eb-9036-0d2506828092.png)
