### ISSUE TITLE
Startpage missing from onboarding

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12340]
## Description 

`Startpage` is missing from the onboarding modal in `1.16.x`. Should re-add as we now have https://github.com/brave/brave-browser/issues/12257.

## Steps to reproduce 

   1. launch `1.16.68 CR: 86.0.4240.111` on a new profile (current RC)
   2. tap on the URL bar which will trigger the search engine onboarding modal

## Actual result 

![Screenshot_20201026-213138_Brave](https://user-images.githubusercontent.com/2602313/97247057-3c2d3280-17d5-11eb-8d97-7db947b21c9c.jpg)

## Expected result

![Screenshot_20201026-215031_Brave](https://user-images.githubusercontent.com/2602313/97247226-a6de6e00-17d5-11eb-9016-cea412b3e962.jpg)

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 10`
   
## Brave version

* `1.16.68 CR: 86.0.4240.111`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @SergeyZhukovsky @anthonypkeane @bsclifton @srirambv

**Comment by srirambv** [comment]
This is broken on CR87 nightly  build 1.18.27 as well. May need to be fixed and uplifted. 

cc: @kjozwiak @bsclifton

**Comment by deeppandya** [comment]
Closing the issue in https://github.com/brave/brave-core/pull/7039

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.17.66 x64 beta build

OnePlus (Android 10) | Samsung Tab A (Android 10)
-- | --
![image](https://user-images.githubusercontent.com/17010094/98801021-1d4fb280-2409-11eb-8059-d9973c79fa37.png) | ![image](https://user-images.githubusercontent.com/17010094/98801104-39ebea80-2409-11eb-95d9-5f5953c13c43.png)
