### ISSUE TITLE
Transactions fail to load on rbcroyalbank.com

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12343]
## Description 

Transactions fail to load on rbcroyalbank.com

## Steps to Reproduce

   1. Login to account with Shields up
   2. Transactions details fail to load
   3. Disabe adblocker, loads transactions details

## Actual result:

Transactions fail to load . 

## Expected result:
Should load transactions details

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Windows 10 OS Version 2004 (Build 19041.572)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by ryanbr** [comment]
Hey @srirambv 

Can you paste the `ads and trackers` from shields?

**Comment by srirambv** [comment]
Closing this as it's fixed.
