### ISSUE TITLE
rewards currently only shows a maximum of 10 websites under auto-contribute

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1234]
## Description 

Rewards currently only shows a maximum of 10 websites via the auto-contribute table. Quickly debugged with @NejcZdovc and noticed that the `publisher_info_db` was listing all the visited websites, but `chrome://rewards/` was still showing only 10.

## Steps to Reproduce

   1. open `0.55.5 Chromium: 70.0.3538.16`
   2. enable `chrome://rewards/` and visit around ~20 websites/YT/Twitch channels
   3. you'll notice that only 10 websites/channels are being displayed at one time

## Actual result:

Only a maximum of 10 websites are being displayed under the auto-contribute table under `chrome://rewards/`.

## Expected result:

Users should see all the websites that they've visited under the auto-contribute table.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

### Reproducible on current release:

Yes, currently reproducible using `0.55.5 Chromium: 70.0.3538.16` which is the current live version.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

Verified test plan from https://github.com/brave/brave-core/pull/486
