### ISSUE TITLE
[Desktop] opening the rewards panel on a "permalink" from reddit does not show the expected creator info

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12357]
## Description 

If you are on a post on reddit such as https://old.reddit.com/r/brave_browser/comments/jjlo4j/open_in_tor_prompt_when_visiting_nyt/ and you open the panel, it shows the creator info for the person who authored the post. In this case, that is `tombstone2k`:
<img width="1192" alt="Screen Shot 2020-10-28 at 8 30 11 AM" src="https://user-images.githubusercontent.com/28145373/97436202-fb7a0a00-18f7-11eb-9aae-c5bbb4df452f.png">

If you then click on "permalink" for one of the comments or open the permalink in a new tab, ex https://old.reddit.com/r/brave_browser/comments/jjlo4j/open_in_tor_prompt_when_visiting_nyt/gadday7/, and then open the panel, I'd expect the panel to show info for who authored the comment but it still shows info for who authored the post, in this case `sgt_skinner`:
<img width="1193" alt="Screen Shot 2020-10-28 at 8 33 07 AM" src="https://user-images.githubusercontent.com/28145373/97436418-5b70b080-18f8-11eb-9adc-21fb40317444.png">

Note, on 1.16.x (no greaselion reddit tipping in this version) when you visit https://old.reddit.com/r/brave_browser/comments/jjlo4j/open_in_tor_prompt_when_visiting_nyt/, panel shows "reddit.com" not "tombstone2k on reddit". Similarly for visiting the permalink, panel shows "reddit.com".

## Steps to Reproduce

   1. Navigate to a post on reddit such as https://old.reddit.com/r/brave_browser/comments/jjlo4j/open_in_tor_prompt_when_visiting_nyt/
   2. Open panel, confirm panel shows creator info for who authored the post
   3. Find a comment and click on the permalink or open permalink in a new tab
   4. Open panel

## Actual result:

<img width="1193" alt="Screen Shot 2020-10-28 at 8 33 07 AM" src="https://user-images.githubusercontent.com/28145373/97436563-97a41100-18f8-11eb-91d9-76e785ccf04d.png">

## Expected result:
panel would show comment author info not original thread author's info

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.53 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a (no greaselion reddit tipping on 1.16.x)
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @emerick @NejcZdovc

**Comment by NejcZdovc** [comment]
this is right now expected as we only show main comment publisher. Let's see if we want to add support for this one as well

**Comment by Miyayes** [comment]
Users will use the inline tipping buttons, rather than getting poster.
