### ISSUE TITLE
Clicking on a text shows a flashing caret (text cursor)

### ISSUE THREAD

**Issue by georgeat8** [brave/brave-browser#12358]
## Description 

Whenever I click on a text, the caret shows up and goes away (acting similar as if any tag, element, component, etc. is an input) only if I refresh the page or actually go to an input/a text box.

## Steps to Reproduce

   1. Go on a page
   2. Click on a plain text
   3. The caret should show up

## Actual result:

You can see in the screenshots the caret (couldn't show that is flashing too tho):
[Screenshots](https://imgur.com/a/TPgaDoN)

## Expected result:
Not showing a caret when clicking on a text.

## Reproduces how often: 

For me it reproduces quite easily (as described in the steps above)

## Brave version (brave://version info)

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) unknown (64-bit)

## Version/Channel Information:

As I mainly use Linux, I tested with the 1.16.67 version and the caret shows up, but also tested with the latest stable version (1.16.68) on Windows and the same thing happens there.

**Comment by markdid** [comment]
I have this same problem. Drives me nuts haha

**Comment by 90umut** [comment]
I have this problem too. It happens not long ago. Did you find a solution  ?

**Comment by 90umut** [comment]
Hello, I found the issue. Just press F7. It will disable caret mode.

**Comment by georgeat8** [comment]
> Hello, I found the issue. Just press F7. It will disable caret mode.

Wow, that was an "unexpected" solution. Thanks a lot!

**Comment by abhiraj-kale** [comment]
> Hello, I found the issue. Just press F7. It will disable caret mode.

yes, this is a simple solution. If you have a secondary function with f7 (E.g. volume down) like i have, just press fn key and f7 together. i will disable caret mode 👍🏼
