### ISSUE TITLE
Enable customise top tiles hide it completely

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12354]
## Description 

Enable customise top tiles hide it completely

## Steps to Reproduce

   1. Upgrade to 1.18.12 nightly build
   2. Open NTP and go to dashboard settings
   3. Disable customise top tiles from settings, top tiles are disabled 

## Actual result:

![toptiles](https://user-images.githubusercontent.com/17010094/97397096-5bfd4d00-18e0-11eb-99f4-83ae5855c7af.gif)

## Expected result:
Should not hide tiles when customise is selected

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.18.12 Chromium: 86.0.4240.111 (Official Build) nightly (64-bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bsclifton

**Comment by bsclifton** [comment]
Diagnosed with @srirambv - I believe the root cause for this is that clear on exit is set for him

You can view the data that SHOULD be showing on custom links via brave://ntp-tiles-internals/ and this (along with brave://new-tab-page) is blank. When doing the add/edit tile issue (https://github.com/brave/brave-browser/issues/7493), we'll want to make sure that custom entries persist with clear on exit set

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.70 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/7105

Confirmed the `Customize Top Sites` toggle under the `Customization` modal as been removed:
<img width="734" alt="Screen Shot 2020-11-18 at 11 29 47 AM" src="https://user-images.githubusercontent.com/28145373/99558298-93b45d80-2991-11eb-8fc5-d01dd243cbc8.png">

Confirmed that `use_most_visited_tiles` is set as `true` under `brave://prefs-internals`:
<img width="1037" alt="Screen Shot 2020-11-18 at 11 29 24 AM" src="https://user-images.githubusercontent.com/28145373/99558404-afb7ff00-2991-11eb-9b83-50b09ac3b168.png">

-----------------
