### ISSUE TITLE
[Desktop] sometimes in-line tip button shows "twitterTipsIconLabel" text instead of "Tip"

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12350]
## Description 

Sometimes the in-line tip button displays "twitterTipsIconLabel" instead of "Tip" text (localized). 

I haven't been able to reproduce this but it has been reported internally and externally.

## Steps to Reproduce

TBD

## Actual result:

![twitter](https://user-images.githubusercontent.com/28145373/97351387-0f762b00-1868-11eb-9e43-39218ec5018c.png)

## Expected result:
<img width="67" alt="Screen Shot 2020-10-27 at 3 21 31 PM" src="https://user-images.githubusercontent.com/28145373/97351423-1b61ed00-1868-11eb-80b3-860519831072.png">

## Reproduces how often: 

unsure

## Brave version (brave://version info)

 unknown

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @emerick

**Comment by LaurenWags** [comment]
I've tried variations on the following without success:
1. Install older version (1.15.x), enable Rewards. Upgrade to 1.16.x (no Twitter greaselion tipping). Close/open twitter pages. Could not reproduce this issue but did reproduce https://github.com/brave/brave-browser/issues/12264.
2. Install older version (1.15.x), enable Rewards. Upgrade to 1.17.x (with Twitter greaselion tipping). Close/open twitter pages. Could not reproduce this issue but did reproduce https://github.com/brave/brave-browser/issues/12264.
3. Install 1.16.x and 1.17.x, enable Rewards. Open twitter page (like twitter.com/brave). Close/reopen browser several times to see if I could produce a race condition. Was unsuccessful but did reproduce already logged issue https://github.com/brave/brave-browser/issues/12264.
4. Repeat above cases using non-US, non-English locale & language.

**Comment by BrendanEich** [comment]
Dup of #12264 or same underlying cause?

**Comment by jonathansampson** [comment]
Users are seeing this in 1.16.68 (current Release at the time of this writing) [[1][1]][[2][2]].

[1]: https://twitter.com/FrenRight/status/1322291748945670146
[2]: https://twitter.com/ImGulgrim/status/1322343566254002177

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.70 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/7141#issue-520580575

Opened multiple tabs w/ in-line tip buttons. Examples:
 - https://twitter.com/emerick, https://twitter.com/bravelaurenwags
 - https://github.com/brave/brave-browser/issues/12527 and other issue links
 - https://github.com/brave/brave-core/commits/master 
 - https://github.com/brave/brave-core/pull/7140 and other PR links
 - https://www.reddit.com/user/alex_the_brave, https://www.reddit.com/user/cryptojennie
 - https://old.reddit.com/ 
 - https://www.reddit.com/r/brave_browser/ and other subreddit links

Generally confirmed:
 - Navigating thru the various pages/page types above and confirming "Tip" text and button were displayed. 
 - Opening new pages via context menu and confirming when opening the page it loaded and the "Tip" text and button were displayed.
 - Closing tabs and reopening using cmd+shift+T. When tab is reopened and loaded the "Tip" text and button were displayed.
 - Leaving various pages as active and then close/reopen the browser. On relaunch pages generally showed the "Tip" text and button, except for Twitter pages. This is logged with https://github.com/brave/brave-browser/issues/11825. Reload fixes it. Also confirmed reloading a tab that was left over from previous session showed the "Tip" text and button once page loaded.

---------------

**Comment by cryptojennie** [comment]
I'm still running into the `twitterTipsIconLabel` issue intermittently after updating to v1.17.73. 

Version info: v1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)
OS: MacOS Catalina 

![Screen Shot 2020-11-25 at 4 16 09 PM](https://user-images.githubusercontent.com/32344882/100289043-07340d00-2f46-11eb-9d6d-0989ca148f1c.jpg)

**Comment by LaurenWags** [comment]
QA process is to log a new issue once an issue is closed with a PR, so closing this one. We can track the new issue under https://github.com/brave/brave-browser/issues/12900.
