### ISSUE TITLE
Ubuntu 20.04 - middle click to paste selected text stopped working in Brave browser

### ISSUE THREAD

**Issue by DavidRedstone** [brave/brave-browser#12353]
Searched but didn't find an open issue for middle click to paste selected text

## Description 
Ubuntu 20.04 - middle click to paste selected text stopped working in Brave browser
This was working previously for all sites in Brave, and still works in other apps... and on some sites in Brave.

## Steps to Reproduce
Use Linux, select some text, middle click to paste it 
(no need to control-c copy and control-v paste -- this is a secondary copy paste functionality that is common on Linuxes)

## Actual result:
Doesn't paste selected text anymore

## Expected result:
Should paste whatever text was selected

## Reproduces how often: 
Now fails to work, including after running updates and rebooting.

## Brave version (brave://version info)
Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Linux (Ubuntu 20.04)

## Version/Channel Information:
I'm just using the standard Brave release (see above)

## Other Additional Information:
Playing with this more, it seems to work in the URL bar, but not within pages.
Brave shields on/off doesn't seem to affect it.
Strangely it works in gmail, and duckduckgo search, confluence cloud, but not for Slack and Jira cloud, nor Google search.

Just reiterating afaik this worked universally on my Ubuntu machines up until recently -- last few days.

## Miscellaneous Information:
I use this feature all day every day for my job, so it is really annoying that it stopped working for some sites in Brave..

Cheers

**Comment by dbart** [comment]
I am also hitting this bug. This functionality is part of my regular workflow, very much needed. 

### Brave version (brave://version info)
Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Linux (Ubuntu 20.04, Mate Desktop Env)

### Workaround
For now the only workaround seems to be using a different browser, so I've temporarily switched to Vivaldi where middle-click paste still works.

**Comment by DavidRedstone** [comment]
Today middle click paste appears to be working normally again. I hope it stays this way, and wonder what changed?

First reported on 1.16.68, and currently on 1.16.72

Brave	1.16.72 Chromium: 86.0.4240.183 (Official Build) (64-bit)
Revision	0b568b034b8f7994697cb341eeca5979b84151cc-refs/branch-heads/4240@{#1374}
OS	Linux  (Ubuntu 20.04, Gnome 3 Desktop Env)
JavaScript	V8 8.6.395.23

**Comment by bsclifton** [comment]
@dbart can you please try updating to see if this fixes you also?

**Comment by DavidRedstone** [comment]
fwiw - Still ok for me. I wonder what it was?

On this Brave version now:
Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)

**Comment by dbart** [comment]
Yes, middle click is working again for me after updating to the version below. Thank you!

Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)
