### ISSUE TITLE
Reload new incognito tab resets DDG search button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1235]
## Description 

Reload new incognito tab resets DDG search button

## Steps to Reproduce

   1. Clean install 0.55.5 
   2. Open an incognito window 
   3. Toggle DDG search, reload the new tab page, switch toggles back to off
   4. Do a search on DDG in incognito tab
   5. Open a new tab in incognito window, DDG is set as default search, reload new tab doesn't toggle the switch

## Actual result:

This is the same behaviour on all platforms until a search is done on DDG
![privatesearch1](https://user-images.githubusercontent.com/17010094/45885029-5806b480-bd83-11e8-9869-a97a7cd17c82.gif)

On Windows 10 DDG search fails making it impossible to use DDG and reload always resets the switch
![image](https://user-images.githubusercontent.com/17010094/45885059-694fc100-bd83-11e8-8e60-18c47c229e51.png)

## Expected result:
Once switch is enabled should be retained after page is reloaded

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.2 Chromium: 70.0.3538.16 (Official Build) (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | All

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

It also works the other way. Have DDG persist, open new private tab, turn DDG off and reload.
issue verified by @LaurenWags @kjozwiak on mac and @btlechowski on Windows 7

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified enabling DDG switch and reloading page didn't reset the setting
* Verified after enabling DDG button typing a search term showed `DuckDuckGo Search`
* Verified after disabling DDG button typing a search term showed `Google Search`
* Verified enabling DDG button is retained across private browsing session
* Verified enabling DDG button is retained across private tabs

**Comment by GeetaSarvadnya** [comment]
Do a search on DDG in Incognito window, click on browser back button is resetting the DDG switch.
![ddg switch reset](https://user-images.githubusercontent.com/38657976/46753453-8110ca00-ccdd-11e8-94f8-7fc1c812015c.gif)
