### ISSUE TITLE
previously visited websites being added into table after enabling rewards

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1236]
## Description 

When enabling `chrome://rewards`, you'll notice that the `auto-contribute` table is being populated by previously visited websites. This could lead to several privacy issues. Websites that have been visited after enabling rewards should be the only ones appearing in the table.

Example: I visited several personal/sketchy websites and didn't use PB/Incognito. I enable rewards and notice that these websites are now being listed in the table as well.

## Steps to Reproduce

   1. launch `0.55.5 Chromium: 70.0.3538.16` and visit ~5 websites
   2. enable rewards via `chrome://rewards`
   3. wait ~1min and you'll notice the table will be populated with those websites

## Actual result:

![rewardstableissue](https://user-images.githubusercontent.com/2602313/45887555-00b81280-bd8a-11e8-8018-46ec766015a5.gif)

## Expected result:

Websites/Publishers/Channels that have been previously visited shouldn't be populated into the `auto-contribute` table once `chrome://rewards` is enabled.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

### Reproducible on current release:

Yes, currently reproducible under `0.55.5 Chromium: 70.0.3538.16` which is the current live build.

**Comment by NejcZdovc** [comment]
this should be fixed by https://github.com/brave/brave-core/pull/419

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

Used test plan from https://github.com/brave/brave-core/pull/488
