### ISSUE TITLE
[Desktop] tipping banners do not show messaging for creators not being able to accept tips

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12362]
## Description 

In 1.16.x if a creator is verified but not KYC'd, the panel and tipping banners show messaging indicating this:

```
NOTE: This Brave Verified Creator has not yet configured their account to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed.Learn more.
```

In 1.17.x only the panel shows this message, the tip banners do not.

Probably due to https://github.com/brave/brave-browser/issues/11393

## Steps to Reproduce

   1. Clean profile 1.17.x (staging env), enable rewards
   2. Connect KYC'd uphold account
   3. Navigate to a Brave verified publisher who is not KYCd. ex. reddit.com/user/jsadler-brave, youtube.com/user/jjdsampson, duckduckgo.com

## Actual result:

Tip banners do not show expected message:
<img width="1193" alt="noKYC 1time" src="https://user-images.githubusercontent.com/28145373/97457461-2708ee80-1910-11eb-9107-196b463e9292.png">
<img width="1191" alt="noKYC recur" src="https://user-images.githubusercontent.com/28145373/97457468-283a1b80-1910-11eb-8e89-08140062ffc2.png">

## Expected result:
Tip banners should show same message as panel:
<img width="1197" alt="noKYC panel" src="https://user-images.githubusercontent.com/28145373/97457526-3851fb00-1910-11eb-8ef4-11934cd2588c.png">

For reference, this is what the banner looked like on 1.16.x:
<img width="1195" alt="1 16 x noKYC banner" src="https://user-images.githubusercontent.com/28145373/97457600-4869da80-1910-11eb-88a3-35fba254106a.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.17.53 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? not with 1.16.x
- Can you reproduce this issue with the beta channel? yes 1.17.x
- Can you reproduce this issue with the nightly channel? yes 1.18.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing @NejcZdovc

**Comment by zenparsing** [comment]
Possibly an issue with the logic in `showUnverifiedNotice` [here](https://github.com/brave/brave-core/blob/68d7ed18927ced0c21e0c8f76a2297a0e70d0060/components/brave_rewards/resources/tip/components/publisher_banner.tsx#L170)

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, this is available for testing in https://github.com/brave/brave-browser/releases/tag/v1.17.60

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.17.62 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
-- | --
Revision | 37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified STR from https://github.com/brave/brave-browser/issues/12362#issue-731551172 using staging env.
Verified scenarios outlined in https://github.com/brave/brave-core/pull/6983#issuecomment-721350495.

<details>
<summary>1. Visit non-verified creator with Uphold wallet connected</summary>

Visited non-verified creator (ex. google.com). Confirmed messaging on panel and in banners:
<img width="1630" alt="Screen Shot 2020-11-06 at 1 56 24 PM" src="https://user-images.githubusercontent.com/28145373/98404093-f889c280-2037-11eb-9ac6-68368225e2a1.png">
<img width="1627" alt="Screen Shot 2020-11-06 at 1 56 40 PM" src="https://user-images.githubusercontent.com/28145373/98404095-f9baef80-2037-11eb-84b0-28b934aa986a.png">

Tipped publisher and confirmed tip shows in Pending list:
<img width="962" alt="Screen Shot 2020-11-06 at 1 57 08 PM" src="https://user-images.githubusercontent.com/28145373/98404101-fd4e7680-2037-11eb-891e-35fb6ab212fe.png">

</details>

<details>
<summary>2. Visit verified, not KYC'd creator with Uphold wallet connected</summary>

Visited verified, non-KYC'd creators (ex. Duckduckgo.com, youtube.com/user/jjdsampson, reddit.com/user/alex_the_brave, etc). Confirmed messaging on panel and in banner:


Tipped publisher and confirmed tip shows in Pending list:


</details>

<details>
<summary>3. Visit verified, KYC'd creator with Uphold wallet connected</summary>

Visited verified, KYC'd creators (ex. github.com/laurenwags, twitter.com/emerick, 3zsistemi.si, etc). Confirmed no messaging on panel or on banner:


Tipped publisher and confirmed tip went thru:

</details>

<details>
<summary>4. Visit non-verified creator with anon wallet connected</summary>

Visited non-verified creators (ex. google.com, nytimes.com, buzzfeed.com, etc). Confirmed messaging on panel and in banner:


Tipped publisher and confirmed tip shows in Pending list:


</details>

<details>
<summary>5. Visit verified, not KYC'd creator with anon wallet connected</summary>

Visited verified, non-KYC'd creators (ex. Duckduckgo.com, youtube.com/user/jjdsampson, reddit.com/user/alex_the_brave, etc). Confirmed no messaging on panel or on banner:

Tipped publisher and confirmed tip went thru:


</details>

<details>
<summary>6. Visit verified, KYC'd creator with anon wallet connected</summary>

Visited verified, KYC'd creators (ex. github.com/laurenwags, twitter.com/emerick, 3zsistemi.si, etc). Confirmed no messaging on panel or on banner:

Tipped publisher and confirmed tip went thru:


</details>
