### ISSUE TITLE
Brave 1.16.68 on Mac is reporting that WebGL GLSL highp precision isn't supported

### ISSUE THREAD

**Issue by measuredweighed** [brave/brave-browser#12366]
## Description 
As of 1.16.68 Brave on a desktop Mac reports that high precision WebGL shader variables aren't supported. This has not been the case before this update. Chrome Version 86.0.4240.111 (Official Build) (x86_64) works without issue, along with Safari and Firefox. All report support for `highp` WebGL shader variables.

## Steps to Reproduce
The following Javascript will return false, where previously the correct result was returned.
```
const highp = gl.getShaderPrecisionFormat(gl.FRAGMENT_SHADER, gl.HIGH_FLOAT);
const highpSupported = highp.precision != 0;
if(!highpSupported) return false;
```

The call to `getShaderPrecisionFormat` returns:
```
WebGLShaderPrecisionFormat {rangeMin: 0, rangeMax: 0, precision: 0}
```

A visit to [https://webglreport.com/](https://webglreport.com/) in Brave reports under Fragment Shader that float/int precision = `mediump/lowp` whereas the latest Chrome correctly reports `highp/highp`. Interestingly, it looks like for a WebGL2 context Brave behaves correctly.

I'm a complete novice when it comes to the Brave codebase but a [recent commit](https://github.com/brave/brave-core/commit/03dcb99b04bdbe54faa99174651f4f410abae572#diff-bd0094799772690a8eaebcb68c8a89c9da20a2381584d9febe4adcc4566a94b4R69) by @pilgrim-brave may possibly be related? Apologies if this is totally unrelated.

## Actual result:
Brave reports that high precision WebGL shader variables aren't supported.

## Expected result:
Previously Brave has reported support correctly.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
Version 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64)

**Comment by devcrowley** [comment]
I want to confirm that this issue also affects Brave 1.16.68 on Windows 10.

**Comment by ben-mm** [comment]
FYI, I believe this is currently breaking the Autodesk Fusion 3D Viewer:

![fusion360black](https://user-images.githubusercontent.com/52332482/97754364-a2a3a080-1ab4-11eb-987b-b0b6173e4a30.jpg)

![console](https://user-images.githubusercontent.com/52332482/97754372-a59e9100-1ab4-11eb-8441-6759d369a311.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.15.7 (Build 19H2)
```

Visited https://webglreport.com and ensured that `float/int precision:` appears as `highp/highp` as per the following:

<img width="336" alt="Screen Shot 2020-11-16 at 11 45 40 PM" src="https://user-images.githubusercontent.com/2602313/99347840-73d84900-286e-11eb-8699-3e2c5fd8cfa3.png">

**Comment by Omiod** [comment]
Still not working ...
