### ISSUE TITLE
Video ad is shown as a broken video file

### ISSUE THREAD

**Issue by vedangwartikar** [brave/brave-browser#12364]
## Description 

Video ad is shown as a broken video file

## Steps to Reproduce

   1. Go to 9gag.com
   2. Broken video ad is displayed in between the content

## Actual result:

![image](https://user-images.githubusercontent.com/43764240/97476242-315cd400-1974-11eb-9085-6c5112b38759.png)

**Comment by rebron** [comment]
cc: @antonok-edm cosmetic filter issue? Possibly just hide the video ad instead of showing artifact?

**Comment by antonok-edm** [comment]
@rebron sounds about right.

cc @ryanbr

**Comment by ryanbr** [comment]
Okay, lets see how this goes.  @vedangwartikar @srirambv  @rebron  @antonok-edm 

https://github.com/easylist/easylist/commit/e12d81465e9a3605d8b5f969f2c3a673d9d5b41f  Give it 24-48hrs.

**Comment by ryanbr** [comment]
How is it looking @vedangwartikar  ? Safe to close ticket?

**Comment by srirambv** [comment]
Seems fixed on Android at least. Can wait till @vedangwartikar  confirms for desktop

**Comment by vedangwartikar** [comment]
Yes, I think it is fixed.
Attaching screenshot fyr
![image](https://user-images.githubusercontent.com/43764240/98335498-13a20580-202b-11eb-8a1d-05ea41c28300.png)

Thanks!
