### ISSUE TITLE
Update icon on tipping banner for unverified publisher

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12363]
## Description 

Update icon on tipping banner

## Steps to Reproduce

   1. Open tipping banner
   2. Unverified icon looks like close button
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/97466668-46694100-193b-11eb-8e83-b76571023737.png)

## Expected result:
Some icon that doesn't look like close button

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.18.14 Chromium: 86.0.4240.111 (Official Build) nightly (x86_64)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by zenparsing** [comment]
The verified checkmark should also be modified:

<img width="100" alt="tip_verified_check" src="https://user-images.githubusercontent.com/5995084/99819199-27fefb80-2b1d-11eb-9bfe-b8e81d7e850e.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.55 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the STR from the description

Unverified pubs:
![image](https://user-images.githubusercontent.com/38657976/101792556-d699c900-3b2a-11eb-9e29-07e44fb4a082.png)

Verified pubs:
![image](https://user-images.githubusercontent.com/38657976/101800021-cbe33200-3b32-11eb-9d41-b73561dfb94e.png)
