### ISSUE TITLE
Top sites are not re-added once all the top sites are removed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12378]
## Description 

Top sites are not re-added once all the top sites are removed

## Steps to Reproduce

   1. Clean profile 1.17.53
   2. Visit 4 to 5 sites 
   3. Make sure top sites are added in NTP's
   4. Remove all the top sites one by one by clicking on the `X` icon
   5. Make sure all the top sites are removed
   6. Re-visit all the sites opened in step 2 (I have visited all the sites min 10 times)
   7. Open an NTP observe no top sites are added
   8. Restart the browser and re-visit all the sites again, no top sites are re-added in NTP's
   
**Note**: Follow the same steps in `1.16.68` works fine, top sites are re-added.

## Actual result:

Top sites are not re-added once all the top sites are removed

## Expected result:
Top sites should be re-added

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.17.53 Chromium: 86.0.4240.111 (Official Build) dev (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bsclifton @rebron

**Comment by kjozwiak** [comment]
This might not be 100% fixed as per https://github.com/brave/brave-browser/issues/12739. Waiting on some info from @simonhong.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.70 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/7105

Confirmed the `Customize Top Sites` toggle under the `Customization` modal as been removed:
<img width="734" alt="Screen Shot 2020-11-18 at 11 29 47 AM" src="https://user-images.githubusercontent.com/28145373/99558298-93b45d80-2991-11eb-8fc5-d01dd243cbc8.png">

Confirmed that `use_most_visited_tiles` is set as `true` under `brave://prefs-internals`:
<img width="1037" alt="Screen Shot 2020-11-18 at 11 29 24 AM" src="https://user-images.githubusercontent.com/28145373/99558404-afb7ff00-2991-11eb-9b83-50b09ac3b168.png">

STR still reproduced for me, but this was mentioned by @kjozwiak in https://github.com/brave/brave-browser/issues/12378#issuecomment-729128197 and is covered by https://github.com/brave/brave-browser/issues/12739

-----------------
