### ISSUE TITLE
Crash if Omnibox search count exceeds 500 for P3A histogram

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12389]
## Description 

Crash if Omnibox search count exceeds 500 due to `std::lower_bound` returning a bucket between 0 and 7, where 7 is returned if the Omnibox count exceeds 500.

`UMA_HISTOGRAM_EXACT_LINEAR("Brave.Omnibox.SearchCount", answer, base::size(kIntervals));` only accounts for 7 buckets (0..6)

but we need:

`UMA_HISTOGRAM_EXACT_LINEAR("Brave.Omnibox.SearchCount", answer, base::size(kIntervals) + 1);` to account for 8 buckets (0..7)

## Steps to Reproduce

   1. Exceed Omnibox 500 search counts

## Actual result:

Browser crashes when submitting P3A histogram

## Expected result:
Browser should not crash when submitting P3A histogram

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Ye

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
<!--Any additional information, related issues, extra QA steps, configuration or data that might be necessary to reproduce the See https://github.com/brave/brave-core/pull/6981 for fix

https://brave.sp.backtrace.io/p/brave/triage?time=all&filters=((callstack%2Ccontains%2CHistogramChanged))&aggregations=((timestamp.received%2Crange)%2C(ver%2Cdistribution%2C3)%2C(guid%2Cunique)%2C(classifiers%2Chead))

**Comment by rebron** [comment]
@tmancey Can you add the crash report id in here so we can track this one down?

**Comment by iefremov** [comment]
1) The crash was specific to P2A
2) Histogram properly reports it's maximum possible value
