### ISSUE TITLE
Desktop mode toggle is broken

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#12382]
## Description 

Got several reports from users like that `for some reason the desktop site function seems to be broken. it worked fine before but now it just doesn't anymore. whenever I select desktop site mode it switched back to the mobile site either by refreshing the tab or even accessing another one please fix this as I prefer the desktop mode over the mobile mode`

## Steps to reproduce 

   1. Go to Settings->Site Settings and toggle Desktop mode

## Actual result 
Websites are not on desktop mode

## Expected result
Websites are on desktop mode

## Issue reproduces how often 
Always

## Version/Channel Information:

1.16.x

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Removed `release-notes/included` as https://github.com/brave/brave-browser/issues/11928 will be used for the notes. Basically the same issue.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.16.69 x64 build
- Verified enabling desktop mode in site settings enables the check box in the menu
- Verified enabling desktop mode and visiting a page loads the desktop page
- Verified pull-down reload on the desktop page doesn't revert to mobile page
- Verified setting is retained between relaunches and works correctly 
- Verified visiting a mobile page (`https://m.facebook.com`) and selecting desktop site from menu loads desktop page (`https://facebook.com`)
