### ISSUE TITLE
[Desktop] focus ring for toggles on Customize Dashboard still uses 2 colors

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12385]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/11439

Toggles on the Customize Desktop popup still have double border of white/orange.

## Steps to Reproduce

   1. Using 1.17.x w/ dark theme open NTP
   2. Open Customize Dashboard
   3. Find a section with toggles and tab to one or click on toggle

## Actual result:

![toggle double border](https://user-images.githubusercontent.com/28145373/97583738-a6102c80-19cd-11eb-872c-a87db9b0bab3.png)

## Expected result:
No white border, only orange

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.55 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 1.16.x
- Can you reproduce this issue with the beta channel? yes 1.17.x
- Can you reproduce this issue with the nightly channel? yes 1.18.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @karenkliu to confirm expectation

**Comment by karenkliu** [comment]
Expected result is correct.

**Comment by ryanml** [comment]
Fixed with: https://github.com/brave/brave-core/pull/7015

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.18.62 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
Revision	0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS	macOS Version 10.14.6 (Build 18G6042)
```

Verified STR from description.

<img width="746" alt="Screen Shot 2020-11-25 at 4 06 51 PM" src="https://user-images.githubusercontent.com/28145373/100281848-a0f4bd80-2f38-11eb-84e5-ebacf65f08d1.png">

---------------
