### ISSUE TITLE
[Desktop] scroll bars overlap widget cards in Customize Dashboard modal

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12381]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/11441

Once the spacing between cards was fixed with above issue, the scroll bars now overlap the display of the cards. Cards aren't obscured completely, but this could be tweaked to look better. 

## Steps to Reproduce

   1. Using 1.17.x open NTP
   2. Open Customize Dashboard
   3. Click on More Cards

## Actual result:

scroll bars overlap cards:
<img width="747" alt="1 17 x" src="https://user-images.githubusercontent.com/28145373/97574374-84a94380-19c1-11eb-801a-8893ab896684.png">

## Expected result:
Scroll bars do not overlap cards (below is 1.16.x which does not have spacing fix):
<img width="737" alt="1 16 x" src="https://user-images.githubusercontent.com/28145373/97574404-91c63280-19c1-11eb-9169-439aa329302c.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.55 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)

Brave | 1.18.17 Chromium: 87.0.4280.27 (Official Build) nightly (x86_64)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, not with 1.16.x
- Can you reproduce this issue with the beta channel? yes with 1.17.x
- Can you reproduce this issue with the nightly channel? yes with 1.18.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @karenkliu

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.17.55`

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/brave-core/pull/6192/

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)


```
- Verified the STR from the description
- Verified in both clean and upgraded profile
![image](https://user-images.githubusercontent.com/38657976/99956867-c654c080-2dac-11eb-9d79-947da842a87d.png)
![image](https://user-images.githubusercontent.com/38657976/99956894-d076bf00-2dac-11eb-9358-95e2ed0438d7.png)
