### ISSUE TITLE
Regional Adblock doesn't work on Linux, follow up for #41

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1238]
## Description 

Regional Adblock doesn't work on Linux, follow up for #41

## Steps to Reproduce

   1. Clean install 0.55.5 on Linux
   2. Set browser language to non English
   3. Open `chrome://adblock`, regional adblock shows as disabled

## Actual result:

On Linux having multiple languages, doesn't show option to `Display Brave in this language` 
![image](https://user-images.githubusercontent.com/17010094/45890986-61e3e400-bd92-11e8-8dc8-2158b5ce273b.png)

https://youtu.be/uXC0m_n3pOQ

## Expected result:
Should set non English language as default and regional adblock should be enabled

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Found while verifying #41
cc: @emerick @bbondy

**Comment by emerick** [comment]
@srirambv It seems that on Linux, this is controlled via the `LANGUAGE` environment variable (see https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/D6Eoeh0G9Y4 for the gory details).

When launching on Linux like this, I saw the expected settings in chrome://adblock:

```
LANGUAGE=fr_FR ./brave
```

**Comment by LaurenWags** [comment]
@bbondy nope, I'm good - @emerick responded with https://github.com/brave/brave-browser/issues/41#issuecomment-426073347

**Comment by srirambv** [comment]
I think this issue is easily solvable on Linux as well. Here's what i did
1. Add language packs from system settings
2. Change Language from settings and restart
3. Launch Brave and load adblock page, shows regional ad block enabled
![regional adblock](https://user-images.githubusercontent.com/17010094/46559735-35b28200-c8bf-11e8-981d-12fe54138ace.gif)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux
