### ISSUE TITLE
Browser crashes when changing internal cookie settings

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#12393]
## Description 

It's hard to tell exactly what is happening, but it has something to do with where exactly you click when changing internal cookie settings in `brave://settings/cookies`. The browser crashes when swapping between options, but there were several times where I was able to swap options without any crash. It seems more likely to occur if you click on the text directly (as opposed to clicking on the radio button itself). 

That said, it seems like once I produced the crash the first time, no matter where I would click the browser crashed. I think the selected language may also have an effect on this. I can reproduce this on both macOS and Windows 10 systems.

## Steps to Reproduce

   1. Launch Brave, go to `brave://settings/cookies`
   2. Switch from whatever setting you have currently to one of the other options (doesn't seem to matter which one).
   3. If the browser has not already crashed, try switching options by clicking on/near the _text of the setting_, rather than directly on the radio button.

## Actual result:

![browsercrash](https://user-images.githubusercontent.com/3299098/97606103-a6f48e80-19cc-11eb-988f-269afb9673a1.gif)

## Expected result:
No Crash.

## Reproduces how often: 

Easily/every time.

## Brave version (brave://version info)

v1.15.76 -- v1.16.68

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Community thread here:
https://community.brave.com/t/browser-crashing-when-clicking-on-block-all-third-party-cookies/172444/5

**Comment by rebron** [comment]
@Brave-Matt can you go to brave://crashes send the report and attach the id here.

**Comment by Brave-Matt** [comment]
Crash 1: `88dc32a1-4e5a-4fc0-a56c-c9c419e52a69`
Crash 2: `b1fbc0df-520a-4508-a65b-b85581c8b2e6`

**Comment by jeromebrenier** [comment]
I can confirm, Brave crashes when I change the cookie settings too.

**Comment by Brave-Matt** [comment]
User seeing very similar issue:
https://community.brave.com/t/brave-crashes-to-desktop-when-allowing-steam-cookie/176340/2

**Comment by andy4117** [comment]
This issue still exists under Version 1.16.72 Chromium: 86.0.4240.183 (Official Build) (64-Bit)

**Comment by ashdavies** [comment]
I'm getting this issue (or the same effect), from changing the cookie setting from the URL bar in Brave Beta `1.17.61`, seems to happen reliably for any site.

Crash: `a0e70200-cfc2-4f05-0000-000000000000`

![image](https://user-images.githubusercontent.com/1892070/98678443-e0c77c80-235e-11eb-828a-2e8bdc72525e.png)

**Comment by iefremov** [comment]
@Brave-Matt @ashdavies @andy4117 can anyone reproduce?

**Comment by iefremov** [comment]
stale
