### ISSUE TITLE
[Desktop] https://www.functionofbeauty.com/login-2020/ doesn't work with Shields

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#12394]
## Description 

Can't login to this ecommerce site in Brave, with Shields up OR down. However, it works without any problems in Chrome.

## Steps to Reproduce

   1. Go to https://www.functionofbeauty.com/login-2020/
   2. Fill in account login info
   3. See a CAPTCHA
   4. Continue filling in CAPTCHAs
   5. Finally, see a "Your login information cannot be verified." error message

## Actual result:

After clicking "CONTINUE", CAPTCHA appears:
<img width="1680" alt="Screen Shot 2020-10-29 at 10 57 28 AM" src="https://user-images.githubusercontent.com/2388823/97613898-7fa2bf00-19d6-11eb-850a-7379061e44c1.png">

After filling in 3+ different CAPTCHA, error message shows:
<img width="1680" alt="Screen Shot 2020-10-29 at 10 57 16 AM" src="https://user-images.githubusercontent.com/2388823/97613916-829daf80-19d6-11eb-9c2b-f366447bec8d.png">

## Expected result:
No CAPTCHA appears and account page shows after clicking "CONTINUE" to log in.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

All versions

## Version/Channel Information:

All chanenls

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?  N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
Closing. This should work now in latest release due to recaptcha fix.
