### ISSUE TITLE
Update the Default Browser Modal

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#12390]
## Description 
Please update the Default Browser call out on Android as per the design below. 

## Designs

Toast message: `Select Brave Browser and tap ‘Always’`
![image](https://user-images.githubusercontent.com/2388823/105763304-7dcf9580-5f0a-11eb-88e3-a035e70374ec.png)

## Assets
Figma: https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/?node-id=1369%3A18913

**Comment by deeppandya** [comment]
@AlexeyBarabash i will start looking into this issue. if you haven't started working on it.

**Comment by deeppandya** [comment]
@karenkliu @jamesmudgett UI in 2nd and 3rd are handled by the android system and the UI depends on android OS on the device.

**Comment by karenkliu** [comment]
@deeppandya I thought we were able to at least tweak the text a little though?

**Comment by deeppandya** [comment]
@karenkliu to keep the consistent, it doesn't allow to change anything on the dialog. i can try with custom UI but i think we should go with default android UI.

**Comment by deeppandya** [comment]
@karenkliu i am updating logic to show the modal based on below, 
New user - 2nd launch, then after 5 days
Existing user - next app launch, then after 5 days

**Comment by deeppandya** [comment]
one quick question : should we still keep the existing Toast and notification we have on android for default browser ?

**Comment by karenkliu** [comment]
☝️  Yes

**Comment by deeppandya** [comment]
Logic update : 
User would keep seeing the p3a modal until he/she clicks on continue and when user taps on continue, we set to show the default browser modal on the next app open. So It has no relation to app open count directly. And when user sees the first default browser modal, we set the 5 day timer and when we try to show the default browser modal again on day 5, we check if user has already set brave as default or not.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T running 1.20.98 x64 build
- Verified steps from https://github.com/brave/brave-browser/issues/12390#issuecomment-766484226
- Verified on a clean install default browser modal is shown on the second launch
- Verified the second prompt is shown after 5 days if not set as default
- Verified no prompt is shown on 10th day 
- Verified upgrading from GPS version first shows P3A opt-in message
- Verified on upgrade, the second launch shows the default browser modal
- Verified the second prompt is shown after 5 days if not set as default
- Verified selecting `Set as default browser` from the menu doesn't bring up the default browser modal. Just shows the browser list to select 

Dark Theme | Light Theme | Browser selection
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/106883946-96913580-66d8-11eb-895d-a7e2fad47b9e.png) | ![image](https://user-images.githubusercontent.com/17010094/106884012-af99e680-66d8-11eb-8491-815d350d727c.png) | ![image](https://user-images.githubusercontent.com/17010094/106884535-57171900-66d9-11eb-870d-1d9143e34e68.png)

-----------
Verification passed on Samsung Tab A running 1.20.98 x64 build
- Verified steps from https://github.com/brave/brave-browser/issues/12390#issuecomment-766484226
- Verified on a clean install default browser modal is shown on the second launch
- Verified the second prompt is shown after 5 days if not set as default
- Verified no prompt is shown on 10th day 
- Verified upgrading from GPS version first shows P3A opt-in message
- Verified on upgrade, the second launch shows the default browser modal
- Verified the second prompt is shown after 5 days if not set as default
- Verified selecting `Set as default browser` from the menu doesn't bring up the default browser modal. Just shows the browser list to select 

Dark Theme | Light Theme | Browser selection
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/106885718-eb35b000-66da-11eb-9c70-d0740ddaf4db.png) | ![image](https://user-images.githubusercontent.com/17010094/106885727-eec93700-66da-11eb-8b02-748b980a3296.png) | ![image](https://user-images.githubusercontent.com/17010094/106885741-f38deb00-66da-11eb-91c2-c42df3995663.png)

------
Logged follow-up issue(#13958) for missing translations

**Comment by karenkliu** [comment]
@anthonypkeane The layout for set Brave as default on Android tablets looks a bit funky; is it worth fixing in a followup?

**Comment by deeppandya** [comment]
@karenkliu @anthonypkeane i think we should start having spec for tablet if the UI is important for tablet users. because we mainly focus on phone UI so some changes would look weird for huge screens and for tablet UI, we would have to explicitly make changes in UI for tablet version. So if we different spec for both, it would be ideal.
