### ISSUE TITLE
sync QR code modal is missing warning text

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#12397]
There should be some text warning the user that the QR code is sensitive (so they don't take screenshots of it to send to us or other people):

<img width="512" alt="Screen Shot 2020-10-29 at 12 56 36 PM" src="https://user-images.githubusercontent.com/549654/97625822-3eb2a680-19e6-11eb-8d98-dd81421903ce.png">

It should basically be the same text that we show for the code words:

<img width="478" alt="Screen Shot 2020-10-29 at 12 56 50 PM" src="https://user-images.githubusercontent.com/549654/97625831-41ad9700-19e6-11eb-8747-d943548e38a0.png">

**Comment by diracdeltas** [comment]
@anthonypkeane turns out this is not necessary on android

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Reproduced issue in 1.17.x
![image](https://user-images.githubusercontent.com/38657976/100069333-a41b7b00-2e5e-11eb-928a-ef49ab97a491.png)

- Verified the description from the issue https://github.com/brave/brave-browser/issues/12397#issue-732616850
![image](https://user-images.githubusercontent.com/38657976/100069456-cb724800-2e5e-11eb-8034-c08191dce4ee.png)
