### ISSUE TITLE
save password prompt using Chrome's UI

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12398]
## Description 

Looks like the fix from https://github.com/brave/brave-browser/issues/10008 regressed on `C87` again. We'll need to remove the Chrome UI from the `Save Password` prompt/modal.

## Steps to Reproduce

   1. launch brave with C87 and load a website with login/credentials
   2. login and you'll notice that we're displaying Chrome's UI

## Actual result:

<img width="444" alt="Screen Shot 2020-10-29 at 1 49 01 PM" src="https://user-images.githubusercontent.com/2602313/97625247-a4ab2800-19fe-11eb-9015-0c526472c70a.png">

## Expected result:

<img width="406" alt="Screen Shot 2020-10-29 at 3 57 54 PM" src="https://user-images.githubusercontent.com/2602313/97625938-91e52300-19ff-11eb-80a7-8d60c46cbf33.png">

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.18.18 Chromium: 87.0.4280.27 (Official Build) nightly (x86_64)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | macOS Version 10.15.7 (Build 19H2)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No, specific to CR87`
- Can you reproduce this issue with the beta channel? `No, specific to CR87`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @mkarolin

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - Version 1.18.18 Chromium: 87.0.4280.27`

![image](https://user-images.githubusercontent.com/38657976/97660703-62362980-1a98-11eb-94a6-ee885e0a2330.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.63 Chromium: 87.0.4280.49 (Official Build) unknown (x86_64)
-- | --
Revision | f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified STR from description

<img width="348" alt="Screen Shot 2020-11-09 at 6 03 09 AM" src="https://user-images.githubusercontent.com/28145373/98533849-8bea1000-2251-11eb-9a8b-b88260e7476c.png">

-------------------
