### ISSUE TITLE
Whitespace left where advertisements used to be

### ISSUE THREAD

**Issue by chris122380** [brave/brave-browser#12405]
I did search for this issue but I could not find it listed. This is the first time I am posting a GitHub issue, I apologize if it is a duplicate. 

## Description
 large white space left behind after an advertisement has been removed. 

## Steps to reproduce 

   1. ksl.com articles
   2. Time
   3. Fox News 
Mostly seen in news articles but also seen in tech articles as well. 

## Actual result
![Screenshot_20201029-205813](https://user-images.githubusercontent.com/2205798/97655270-4f850b80-1a2a-11eb-9f13-c5782987b891.png)
![Screenshot_20201029-210000](https://user-images.githubusercontent.com/2205798/97655282-5744b000-1a2a-11eb-83c3-ac24f167cb7e.png)

## Expected result
One paragraph after the next with out the large gap of white space. 

## Version/Channel Information:
Release - 1.15.76
Beta - 1.17.54
Nightly - 1.18.18

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta Version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): Phone 
   - Android version: Android 10; moto g(7) power Build/QCOS30.85-18-3
   
## Brave version
1.15.76
1.17.54
1.18.18

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No (Chrome doesn't remove the advertisements) 

### Additional information
This issue can be seen with other ad blocking browsers.

**Comment by chris122380** [comment]
Sometimes the Advertisement text is also left with the Whitespace.
![Screenshot_20201101-095801](https://user-images.githubusercontent.com/2205798/97809221-f59e6480-1c28-11eb-9cbc-aa1023ed24f1.png)

**Comment by srirambv** [comment]
Should be fixed with https://github.com/brave/brave-browser/issues/9955. Closing in favour of https://github.com/brave/brave-browser/issues/9955
