### ISSUE TITLE
Make current BAT balance more distinguishable/readable in Tipping banner

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12408]
## Description 

With the current RE design, the BAT total via the rewards panel is pretty small making it a bit difficult to spot if you're a new user. If you have a high DPI screen/resolution, the text is even smaller. It takes your eyes a few seconds to scan that entire panel to spot what the current balance is. Should be more distinguishable/easier to spot.

## Steps to Reproduce

   1. launch brave and ensure that you have a balance (using `1.18.x` with RE)
   2. click on the BAT icon to open the rewards panel
   3. notice that the total is really small/hard to distinguish

## Actual result:

<img width="422" alt="Screen Shot 2020-10-20 at 3 18 00 PM" src="https://user-images.githubusercontent.com/2602313/97659795-46099c80-1a46-11eb-9d0e-b214e85f0cca.png">

## Expected result:

BAT total should be easier to spot/more distinguishable.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.18.19 Chromium: 87.0.4280.27 (Official Build) nightly (x86_64)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | macOS Version 10.15.7 (Build 19H2)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A as RE landed in 1.18.x`
- Can you reproduce this issue with the beta channel? `N/A as RE landed in 1.18.x`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @mandar-brave @rebron @NejcZdovc @LaurenWags

**Comment by Miyayes** [comment]
Superseded by tipping banner 3.0
