### ISSUE TITLE
promo cards under "brave://rewards" are not appearing initially on new profiles (requires refresh)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12406]
## Description 

Promo cards are not being loaded under `brave://rewards` when initially viewing `brave://rewards` on a new profile. Users need to either refresh `brave://rewards` or open another `brave://rewards` tab. Looks like this regressed with RE in `1.18.x`.

## Steps to Reproduce

   1. launch `1.18.x` with RE using US as the region  (`1.18.19 CR: 87.0.4280.27` in this case) 
   2. visit `brave://rewards`, you'll notice none of the promo cards loaded/are visible
   3. refresh `brave://rewards` and you'll notice that the promo cards are now visible

## Actual result:

![rewardsPromo](https://user-images.githubusercontent.com/2602313/97656279-73058180-1a3d-11eb-9311-e11348de9247.gif)

## Expected result:

Promo cards should be visible/loading when a user initially visits/loads `brave://rewards` for the first time.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.18.19 Chromium: 87.0.4280.27 (Official Build) nightly (x86_64)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | macOS Version 10.15.7 (Build 19H2)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No, only happens with RE`
- Can you reproduce this issue with the beta channel? `No, only happens with RE`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @mandar-brave @NejcZdovc @LaurenWags @rebron

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6042)
```

Verified STR from https://github.com/brave/brave-browser/issues/12406#issue-732851864
Verified with region = US to confirm TAP network card is displayed
Verified with region = Cayman Islands to confirm Uphold Equities card is displayed

--------------
