### ISSUE TITLE
Site hack for Twitter doesn't work

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1240]
## Description 

Site hack for Twitter doesn't work. Found while verifying #84 

## Steps to Reproduce

   1. Visit https://twitter.com/ in a new tab
   2. Enable Block script from Shields
   3. Shows JS blocked want to navigate to legacy site. Click yes does nothing.

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/45895237-a83f4000-bd9e-11e8-93c6-6f2057d4d3b6.png)

## Expected result:
Should load Twitter site even when script is blocked similar to muon 

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

### Reproducible on current release:

No. Block script loads the site correctly on b-l

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Verified this works as expected now 🎉
