### ISSUE TITLE
[Desktop] C87 regression - button shape

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12418]
## Description 

In some  places the button shape is not correct. See below for 2 examples of where buttons on a bubble are not the same shape as they were on 1.16.x/C86

## Steps to Reproduce

   1. Clean profile 1.18.x w/ C87
   2. Navigate to reddit.com --> look at bubble asking to Show Notifications
   3. Navigate to 3zsistemi.si --> look at bubble offering Google Translate installation

## Actual result:

Buttons are rectangular
<img width="627" alt="Screen Shot 2020-10-30 at 7 26 38 AM" src="https://user-images.githubusercontent.com/28145373/97700451-3f007f80-1a82-11eb-85ce-226bbbccc380.png">
<img width="373" alt="Screen Shot 2020-10-30 at 7 26 54 AM" src="https://user-images.githubusercontent.com/28145373/97700461-445dca00-1a82-11eb-8859-d7bafac0001f.png">

## Expected result:
Buttons to be pill shaped
<img width="367" alt="Screen Shot 2020-10-30 at 7 29 17 AM" src="https://user-images.githubusercontent.com/28145373/97700471-49227e00-1a82-11eb-9e40-912505b80b43.png">
<img width="381" alt="Screen Shot 2020-10-30 at 7 29 29 AM" src="https://user-images.githubusercontent.com/28145373/97700476-4a53ab00-1a82-11eb-8035-2cfea01a5eef.png">

## Brave version (brave://version info)

Brave | 1.18.18 Chromium: 87.0.4280.27 (Official Build) nightly (x86_64)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no 1.16.x
- Can you reproduce this issue with the beta channel? no 1.17.x
- Can you reproduce this issue with the nightly channel? yes 1.18.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @mkarolin @rebron

**Comment by GeetaSarvadnya** [comment]
button shape is not as per the brave brand. Pages which doesn't have the brave branded buttons are listed below:

Edit bookmarks buttons:
![image](https://user-images.githubusercontent.com/38657976/97703257-58cbb200-1ad6-11eb-83ef-c243449937bd.png)
![image](https://user-images.githubusercontent.com/38657976/97703338-77ca4400-1ad6-11eb-94a0-2cb72df351eb.png)

Cookies in Use:
![image](https://user-images.githubusercontent.com/38657976/97703412-96c8d600-1ad6-11eb-93b4-b121860f86b0.png)
![image](https://user-images.githubusercontent.com/38657976/97703471-b233e100-1ad6-11eb-8cce-70c90fe14f5f.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.63 Chromium: 87.0.4280.49 (Official Build) unknown (x86_64)
-- | --
Revision | f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified expected button shape on screens mentioned in https://github.com/brave/brave-browser/issues/12418#issue-733102691
<details>
<summary>Screenshots</summary>

<img width="527" alt="Screen Shot 2020-11-09 at 5 45 05 AM" src="https://user-images.githubusercontent.com/28145373/98531940-07968d80-224f-11eb-93d3-fe7f98b0a40c.png">
<img width="391" alt="Screen Shot 2020-11-09 at 5 45 24 AM" src="https://user-images.githubusercontent.com/28145373/98531942-08c7ba80-224f-11eb-83de-c2b217eae896.png">

</details>

Verified expected button shape on screens mentioned in https://github.com/brave/brave-browser/issues/12418#issuecomment-719516624
<details>
<summary>Screenshots</summary>

<img width="373" alt="Screen Shot 2020-11-09 at 5 45 48 AM" src="https://user-images.githubusercontent.com/28145373/98531995-19783080-224f-11eb-8905-0529f46123a7.png">
<img width="537" alt="Screen Shot 2020-11-09 at 5 46 03 AM" src="https://user-images.githubusercontent.com/28145373/98531999-1aa95d80-224f-11eb-9768-7bd818f1df5e.png">
<img width="485" alt="Screen Shot 2020-11-09 at 5 46 19 AM" src="https://user-images.githubusercontent.com/28145373/98532003-1bda8a80-224f-11eb-8c3e-dda15b73d18c.png">

</details>
