### ISSUE TITLE
Reader mode not working

### ISSUE THREAD

**Issue by specter78** [brave/brave-browser#12415]
## Description 
Even after enabling reader mode in brave flags, I am not able to use it on any website.

## Steps to Reproduce
Enable it in flags and try any website.

## Expected result:
Reader mode (text only)

## Reproduces how often: 
Every time

## Brave version (brave://version info)
1.16.68

## Version/Channel Information:
NA

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

**Comment by bsclifton** [comment]
Closing as this is a semi-known issue; there are only a few sites for which this works on

We do have an issue captured to fall back onto the "distill" feature which we had previously:
https://github.com/brave/brave-browser/issues/11994

There is an open PR that we just need to work through 😄 
https://github.com/brave/brave-core/pull/7137
