### ISSUE TITLE
Mobile page is shown in desktop mode when desktop site is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12419]
## Description 
Mobile page is shown in desktop mode when desktop site is disabled

## Steps to reproduce 

   1.  Open a new tab and select Desktop site from menu
   2. Visit `https://facebook.com` (type don't autocomplete or use topsite tile)
   3. Loads desktop page
   4. Pull down reload page, page changes to `https://m.facebook.com?ref...`
   5. Disable desktop site from menu, page reloads to mobile page
   6. Enable desktop site from menu again, mobile page reloads as desktop page

## Actual result 
https://bravesoftware.slack.com/archives/C0816QH3R/p1604059352278400?thread_ts=1604051379.277200&cid=C0816QH3R

## Expected result
Should load desktop page similar to Chrome

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Verification **PASSED** on both `Samsung S10+` on `Android 10` & `Samsung Galaxy Tablet A` on `Android 10` using `1.18.23 CR 87.0.4280.27`:

* verified the STR via https://github.com/brave/brave-core/pull/6984#issuecomment-719234292
* verified the STR via https://github.com/brave/brave-browser/issues/12419#issue-733171495
