### ISSUE TITLE
Ads panel stats are not shown when Ads switch is enabled

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12422]
## Description 

Ads panel stats are not shown when Ads switch is enabled

## Steps to Reproduce

   1. Clen profile 1.18.22
   2. Open BR panel and click on Rewards settings
   3. Enable `Ads` switch in brave://rewards page

Note: Reload brave://rewards fixes the issues

## Actual result:

Ads panel stats are not shown when Ads switch is enabled
![image](https://user-images.githubusercontent.com/38657976/97724558-119fea00-1af3-11eb-9102-a4f0cfcaec85.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/97724588-1cf31580-1af3-11eb-93fa-ea74e0611c26.png)

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.18.22 Chromium: 87.0.4280.27 (Official Build) nightly (64-bit)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @jsecretan

**Comment by NejcZdovc** [comment]
this is expected as we show onboarding text until you do some meaningful action or reload a site. Same goes with AC
