### ISSUE TITLE
Crypto Randomly Shows Up In Home Page When Disabled

### ISSUE THREAD

**Issue by resynth1943** [brave/brave-browser#12421]
## Description 

Even when Brave's cryptography additions are disabled, they randomly appear in the home page. This is undesired behaviour.

## Steps to Reproduce

   1. Disable crypto
   2. Crypto may show up in home page
   3. Yikes

## Actual result:

![image](https://user-images.githubusercontent.com/49915996/97720202-e5b74100-1abf-11eb-84d4-0dd80e7a2405.png)

## Expected result:

You respect the user's decision not to use the cryptography services.

## Reproduces how often: 

Random; this is unknown.

## Brave version (brave://version info)

- **Brave**: 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)
- **Revision**:  b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
- **OS**: Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

This appeared before logging into my PGP keyring with KDE. Perhaps that's the cause?

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by resynth1943** [comment]
With respect, you need to respect the user's decision here. If I have chosen not to use cryptography, I trust Brave will not query me any further. This feels like a game of Whack a Mole.

**Comment by bsclifton** [comment]
cc: @rebron @ryanml

**Comment by ryanml** [comment]
@resynth1943 hi there, just to clarify, when you say, "Crypto Disabled", what method are you using to do so? The two ways to disable the crypto.com widget are by navigating to `brave://settings/newTab` and unchecking `crypto.com`, or by going to `Customize` on the new tab page and hiding the widget there. I just want to determine if there is a bug in the current behavior, or as I suspect, given your wording of `cryptography additions`, you'd prefer things like this are auto-disabled. Thanks!

**Comment by resynth1943** [comment]
> @resynth1943 hi there, just to clarify, when you say, "Crypto Disabled", what method are you using to do so? The two ways to disable the crypto.com widget are by navigating to `brave://settings/newTab`

That was already checked when it showed up.

> or by going to `Customize` on the new tab page and hiding the widget there.

Well, when I went there (before, it was disabled), it re-enabled itself, so...

> I just want to determine if there is a bug in the current behavior

Correct. 😄 

> , or as I suspect, given your wording of `cryptography additions`, you'd prefer things like this are auto-disabled. Thanks!

Wishful thinking. Would love that too, but that's not at all the subject matter of this issue. 😉 
I'm talking about not re-enabling it when the user says "No, I *don't* want this!", as that would be utterly disrespectful to the user. Hope this is not intended behaviour, or I will be greatly disappointed with Brave as a whole.

If it helps, the Brave Rewards icon didn't reappear in the URL bar when this happened.

Thanks,
Synth

**Comment by ryanml** [comment]
@resynth1943 (see pictures) so at one point you saw this (crypto.com disabled)
<img width="694" alt="Screen Shot 2020-11-03 at 12 19 03 AM" src="https://user-images.githubusercontent.com/8732757/97958313-318d1300-1d6a-11eb-8d0c-7341cd44e49f.png">

Then without your own interaction, you saw this (crypto.com enabled)
<img width="760" alt="Screen Shot 2020-11-03 at 12 18 00 AM" src="https://user-images.githubusercontent.com/8732757/97958282-220dca00-1d6a-11eb-9520-7f3c7e0f5f5c.png">

**Comment by resynth1943** [comment]
Prior to it re-enabling itself, it was as is in the top screenshot (with *everything* disabled, however).

Then, when it re-enabled itself automatically, "More Cards" responded as such, with "Hide" under the crypto.com item. Might I reinforce that crypto.com was the *only* card to magically re-enable itself?

**Comment by rebron** [comment]
Closing this one off as fix will be addressed here: https://github.com/brave/brave-browser/issues/9616
Current promotion of new widgets (only 1 though, crypto.com example) puts us in this state where if someone hides widgets altogether, we show the new card anyway.
