### ISSUE TITLE
Change the directory path of admin policy on linux

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#12426]
Brought up by @simonhong in reviewing https://github.com/brave/brave-core/pull/6966. 
We currently are using `/etc/chromium/policies/managed` which is the default for chromium projects, we probably should change this to `/etc/brave/policies/managed`

STR:
1. Create `/etc/brave/policies/managed` directory
2. Create file (`/etc/brave/policies/managed/00_tor.json`) with  below content.
```
{
	"TorDisabled": false
}
```
3. Launch browser and check tor is disabled
4. Delete `/etc/brave/policies/managed` directory
5. Create `/etc/chromium/policies/managed` directory
6. Create file (`/etc/chromium/policies/managed/00_tor.json`) with  below content.
```
{
	"TorDisabled": false
}
```
7. Re-launch browser and check tor is enabled

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.19.66 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

Verified when "TorDisabled": true in `/etc/brave/policies/managed`, Tor is disabled
Verified Brave is `Managed by your organization
![image](https://user-images.githubusercontent.com/34715963/103011176-c70e7d00-4539-11eb-858c-7bf5bc58bbf6.png)

Verified when "TorDisabled": false in `/etc/brave/policies/managed`, Tor is enabled
Verified Brave is `Managed by your organization
![image](https://user-images.githubusercontent.com/34715963/103011516-5c117600-453a-11eb-8770-fad1a61f1552.png)

Verified that `/etc/chromium/policies/managed` has no effect on Brave.
![image](https://user-images.githubusercontent.com/34715963/103011926-0ee1d400-453b-11eb-919c-238a5b6207e0.png)
