### ISSUE TITLE
Turn on Ads and Auto contribute Tos and policy message isn't translated

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12427]
## Description 

Turn on Ads and Auto contribute Tos and policy message isn't translated

## Steps to Reproduce

   1. Set OS locale to France/Germany
   2. Open brave://rewards page
   

## Actual result:

Turn on Ads and Auto contribute Tos and policy message isn't translated
![image](https://user-images.githubusercontent.com/38657976/97731146-cc7fb600-1afa-11eb-9a5e-5945d119ee61.png)

## Expected result:

Turn on Ads and Auto contribute Tos and policy message should be translated
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.22 Chromium: 87.0.4280.27 (Official Build) nightly (64-bit)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @mkarolin

**Comment by NejcZdovc** [comment]
expected as we didn't order translations yet

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.19.85 Chromium: 88.0.4324.89 (Official Build) (64-bit)
-- | --
Revision | 4534be84786f5269fb52e9bf82643af61e2fedaf-refs/branch-heads/4324@{#1721}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

Polish
![image](https://user-images.githubusercontent.com/34715963/104956841-3d818c00-59cd-11eb-953c-e7330fe7d10c.png)

French
![image](https://user-images.githubusercontent.com/34715963/104956934-6ace3a00-59cd-11eb-8b9b-a690668becff.png)


German
![image](https://user-images.githubusercontent.com/34715963/104956986-8b968f80-59cd-11eb-917e-115951af9fa8.png)
