### ISSUE TITLE
Add Tor binary info to chrome://version

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1243]
Add Tor binary info to chrome://version

**Comment by rebron** [comment]
Available in chrome://components

**Comment by bsclifton** [comment]
![screen shot 2018-09-28 at 8 51 18 am](https://user-images.githubusercontent.com/4733304/46219274-c3a8ce80-c2fb-11e8-86c9-d83d20a04ff3.png)
Per our triage call, let's update the `Brave Tor Updater` version whenever we update the Tor binaries (so we can know that 1.0.0 means `0.3.4.8`)
cc: @riastradh-brave @diracdeltas @darkdh

**Comment by riastradh-brave** [comment]
We can get this from the control channel once that's ready, like we do in browser-laptop, but it's not going to get there by 0.55.
