### ISSUE TITLE
[Sync] - Deletes bookmarks but not deleted folders when there is a conflict.

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#12430]
## Description 

Bookmarks during a conflict are deleted from conflicting folders.

## Steps to Reproduce

1. On Desktop sync with mobile (Android or iOS)
2. Create a 2 folders on Desktop `"Test1"`, and `"Test2"`.
3. Add a website bookmark to `"Test2"`
4. Wait for it to sync.. Mobile now has `"Test1"` & `"Test2"` folders which is correct.
5. Delete `Test2` folder on Desktop.. at the same time: Move `Test2` folder into `Test1` folder on Mobile.

## Actual result:
- It throws a warning in console: `[warning:bookmark_remote_updates_handler.cc(694)] Conflict: USE_LOCAL` 
- All bookmarks inside the `Test2` folder are now deleted on both Desktop and Mobile, BUT the `Test2` folder itself is not deleted.

On Google Chrome, the `Test2` folder is deleted along with all the bookmarks in it on both Desktop & Mobile.

## Expected result:
- Not Sure what is expected.

## Reproduces how often: 

- Easily Reproduced

## Desktop Brave version:

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.15.7 (Build 19H2)
JavaScript | V8 8.6.395.17
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Command Line | ./Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --lso-url=https://no-thanks.invalid --enable-features=AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,WebUIDarkMode,LegacyTLSEnforced,OmniboxContextMenuShowFullUrls,DnsOverHttps,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=VideoPlaybackQuality,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,PrivacySettingsRedesign,AutofillServerCommunication,PasswordCheck,TabHoverCards,SmsReceiver,SafeBrowsingEnhancedProtection --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/brandon/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Android Device details:
   - Any

## iOS Device details:
   - iOS 1.15.x

## Version/Channel Information:

- All Channels

## Other Additional Information:

- N/A

## Miscellaneous Information:

https://i.imgur.com/luyv2WX.mp4

**Comment by btlechowski** [comment]
This is a known issue with sync v2: https://github.com/brave/brave-browser/issues/11156

@Brandon-T Can we close this as a dupe?
