### ISSUE TITLE
[Android] App occasionally crashes on nightly build

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#12431]
## Description 
App occasionally crashes on nightly build

## Steps to reproduce 

   1. Open and close application several times

## Actual result 
Crashes occasionally

## Expected result
Never crashes

## Issue reproduces how often 
Occasionally

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? no
- Can you reproduce this issue with the current Play Store Beta version? no
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.18.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.17.66 x64 beta build
- Verified steps from issue description
------------
Verification passed on Samsung Tab A with Android 10 running 1.17.66 x64 beta build
- Verified steps from issue description
