### ISSUE TITLE
Make P3A work on Android

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#12432]
Make P3A work on Android

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/6176 😄 (this is the core functionality)

There is also an issue for tracking UI change for P3A https://github.com/brave/brave-browser/issues/6688

**Comment by AlexeyBarabash** [comment]
Sorry, somehow I didn't found https://github.com/brave/brave-browser/issues/6176
