### ISSUE TITLE
Gear icon in brave://rewards settings page isn't functioning in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12444]
## Description 

Gear icon in brave://rewards settings page isn't functioning in an upgraded profile

## Steps to Reproduce

   1. Install 1.16.x nightly or 1.17.x nightly
   2. Enable rewards
   3. Upgrade profile to 1.18.25 nightly
   4. Click on the Gear icon on the rewards settings page,  `Manage your wallet` modal popup isn't opened

## Actual result:

![Gear icon not functioning - upgraded profile](https://user-images.githubusercontent.com/38657976/97805099-01fedd80-1c7a-11eb-91b9-6f0954d2c911.gif)

## Expected result:
Gear icon should open `Manage your wallet` modal popup

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.25 Chromium: 87.0.4280.40 (Official Build) nightly (64-bit)
-- | --
Revision | 349b9adbfb2784db684617c7731a57d1e61b3be0-refs/branch-heads/4280@{#863}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya do you see anything in console? What happens if you reload the page?

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Reload rewards page did not fix the issue. The console log is as below
![image](https://user-images.githubusercontent.com/38657976/97806369-5063aa80-1c81-11eb-9f68-14efb20ecafd.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified STR from the description
- Verified in both clean and upgraded profile
