### ISSUE TITLE
Feature Request: Subscribe adblock filters with url.

### ISSUE THREAD

**Issue by sys9kdr** [brave/brave-browser#12441]
## Description 

Brave for Android doesn't have support for filter-subscribing with URL.
uBlock Origin and other popular adblocker has this feature. It called custom (filter).
It is important for better adblocking and save bandwidth for mobile.

I found #8107 about Desktop.

## Device details

   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 10
   
## Brave version

Brave 1.57.76

### Additional information

Vivaldi for Android built-in have filter-subscribing options.

**Comment by pes10k** [comment]
Thank you for the issue!  We are working on this and hope to have something to announce shortly.  In the meantime though, i'm going to close this issue in favor of https://github.com/brave/brave-browser/issues/8107, which is where we're tracking that work
