### ISSUE TITLE
Map not showing on https://netmap.vodafone.de/cokart-client/index.html?lang=de&app=cokart_4x

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#12448]
## Description 
Opening page `https://netmap.vodafone.de/cokart-client/index.html?lang=de&app=cokart_4x` won't show map

## Steps to Reproduce

   1.  Opening https://netmap.vodafone.de/cokart-client/index.html?lang=de&app=cokart_4x
   2.  Shows blank page

## Actual result:
Showing blank page, showing no map.
![brave-map](https://user-images.githubusercontent.com/1659004/97828174-2ebefd80-1d2b-11eb-850e-bceb7f8be2e2.png)

## Expected result:
Expect map (From Chrome):
![chrome-map](https://user-images.githubusercontent.com/1659004/97828123-12bb5c00-1d2b-11eb-8820-89efb04b875a.png)

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Shields doesn't affect this:

**Brave:**
![brave-voda](https://user-images.githubusercontent.com/1659004/97827951-8ad55200-1d2a-11eb-898d-fe9b80f28ab4.png)
**Chrome:**
![chrome-voda](https://user-images.githubusercontent.com/1659004/97827962-90329c80-1d2a-11eb-8bfb-a64face204a0.png)

Original page: https://www.vodafone.de/hilfe/netzabdeckung.html  (Click to Zeig mir die Netzkarte)

**Comment by measuredweighed** [comment]
This is related to the [highp issue](https://github.com/brave/brave-browser/issues/12366) I logged here a few days ago.

**Comment by rebron** [comment]
Following str, verified this looks good on:

Brave | 1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 11.0.1 (Build 20B29)

![Screen Shot 2020-11-16 at 10 51 32 AM](https://user-images.githubusercontent.com/5951041/99295103-d6433200-27f9-11eb-9fbc-75ae6f3c8867.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.15.7 (Build 19H2)
```

Visited https://netmap.vodafone.de/cokart-client/index.html?lang=de&app=cokart_4x and ensured the map was loading as per the following:

<img width="938" alt="Screen Shot 2020-11-16 at 11 49 07 PM" src="https://user-images.githubusercontent.com/2602313/99347947-b732b780-286e-11eb-9b2f-efb45f52316b.png">
