### ISSUE TITLE
`Top site` setting isn't in sync between brave://settings/newTab and dashboard settings in NTP 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12458]
## Description 

`Top site` setting isn't in sync between brave://settings/newTab and dashboard settings in NTP 

## Steps to Reproduce

STR1:
   1. Clean profile 1.18.x
   2. Open NTP Dashboard settings
   3. Looks for `Topsites` settings (Topsites settings is ENABLED)
   4. Open brave://settings/newTab 
   5. Looks for `Topsites` settings (Topsites settings is DISABLED)
   
STR2:
 1. Clean profile 1.18.x
 2. Open brave://settings/newTab 
 3. Looks for `Topsites` settings (By default settings is DISABLED)
 4. Enable `Topsites` settings and restart the browser
 5. Setting reverted back to disabled

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/97882882-27f3b300-1d4a-11eb-8122-4ce5a17212af.png)

## Expected result:

All the settings in NTP and brave://settings/newTab should be in sync

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.27 Chromium: 87.0.4280.40 (Official Build) nightly (64-bit)
-- | --
Revision | 349b9adbfb2784db684617c7731a57d1e61b3be0-refs/branch-heads/4280@{#863}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton @karenkliu

**Comment by rebron** [comment]
Closing as wontfix in favor of https://github.com/brave/brave-browser/issues/12505 which will have a pointer from Settings to the New Tab page so we don't have these redundancies and overhead.

**Comment by rebron** [comment]
@GeetaSarvadnya Thanks for filing this one.
