### ISSUE TITLE
Clicking a link that causes a 307 redirect fails because content is blocked

### ISSUE THREAD

**Issue by capouch** [brave/brave-browser#1245]
## Description 

None of the links on http://www.lanewood.com/obituaries.htm resolve.

## Steps to Reproduce

   1. Load page linked above
   2. Click link
   3. Watch "reload" icon post "X" then quickly revert

## Actual result:
Links are dead other than above-described behavior of reload icon.

## Expected result:
Visit various pages linked to original page.

## Reproduces how often: 
Always.  Links work just fine in latest version of Chrome Beta.

## Brave version (chrome://version info)

0.55.6, Linux slackware-current (~14.2) running under VirtualBox

### Reproducible on current release:
No.  Links resolve correctly.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No.

- Is the issue reproducible on the latest version of Chrome? 
No.

**Comment by bsclifton** [comment]
Updated title after trying and reproducing the issue. When inspecting the network, here's what I see after clicking `Jackson Funeral Chapel Arrangements` for example (which doesn't load):
![screen shot 2018-09-27 at 11 24 07 pm](https://user-images.githubusercontent.com/4733304/46191574-e95ab700-c2ac-11e8-9d56-88681b29a9f0.png)

Immediately after clicking, the server sends a 307 response, which then triggers a new request which never resolves:
![screen shot 2018-09-27 at 11 30 35 pm](https://user-images.githubusercontent.com/4733304/46191756-83bafa80-c2ad-11e8-96c3-e82bd64999ad.png)

**Comment by capouch** [comment]
It works just fine now in 0.55.10!!

**Comment by bsclifton** [comment]
I'm not sure of the exact root cause, but I did find a way to make this work (which hints at the cause):
1. Visit https://www.jacksonfuneral.com/
2. Disable shields for this domain
3. Visit http://www.lanewood.com/obituaries.htm
4. Click the `Jackson Funeral Chapel Arrangements` link and it'll work just fine

**Comment by capouch** [comment]
Your followup is much appreciated, as well as your forensics!!
