### ISSUE TITLE
`New tab pages shows blank` settings propagated to all windows types including PT and TOR

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12456]
## Description 

`New tab pages shows blank` settings propagated to all windows types including PT and TOR

## Steps to Reproduce

   1. Clean profile 1.18.x
   2. Open brave://settings
   3. Change `New tab pages shows` settings to `Blank page`
   4. Open an NTP in a normal window ( NTP is blank as expected)
   5. Open a PT window and TOR tab window
   

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/97879166-abf76c00-1d45-11eb-81f3-44a1bb69f73a.png)
![image](https://user-images.githubusercontent.com/38657976/97879335-e103be80-1d45-11eb-93c4-abad3cd186f2.png)

## Expected result:
`New tab pages shows blank` settings should be applicable for Normal window types only as PT and TOR windows types have the custom background for NTP's

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.18.25 Chromium: 87.0.4280.40 (Official Build) nightly (64-bit)
-- | --
Revision | 349b9adbfb2784db684617c7731a57d1e61b3be0-refs/branch-heads/4280@{#863}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bsclifton @rebron @karenkliu

**Comment by karenkliu** [comment]
Correct, the `blank new tab page` option should only be for normal windows.

**Comment by rebron** [comment]
cc: @simonhong Can you take a look?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.57 Chromium: 87.0.4280.66 (Official Build) beta (64-bit)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | Windows 10 OS Version 2004 (Build 19041.572)

```
- Verified STR from the description and ensured blank new Tab page settings is applicable only for Normal window tabs 

**Normal window tabs:**
![image](https://user-images.githubusercontent.com/38657976/99653216-c425f580-2a7e-11eb-9f88-1c1177e8845b.png)

**Private window tabs**
![image](https://user-images.githubusercontent.com/38657976/99653298-dbfd7980-2a7e-11eb-97f7-6bd798facfec.png)

**TOR window tabs**
![image](https://user-images.githubusercontent.com/38657976/99653369-ed468600-2a7e-11eb-81ff-d6d7904da29f.png)

**Guest window tabs**
![image](https://user-images.githubusercontent.com/38657976/99653424-fd5e6580-2a7e-11eb-9675-53ca0a699be5.png)
