### ISSUE TITLE
Multiple clicks on `Open in Tor` open up multiple tabs with the same site instead of highlighting the same tab

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12455]
## Description 

Multiple clicks on `Open in Tor` open up multiple tabs with the same site instead of highlighting the same tab

## Steps to Reproduce

   1. Clean profile 1.17.x or 1.18.x 
   2. Open brave.com in a normal tab
   3. Click on the `Open in Tor` link in URL bar
   4. Brave.com opens up in a TOR tab window
   5. Repeat step 3 multiple times
   6. Multiple tabs are opened with the same site brave.com in the TOR window

## Actual result:

Multiple clicks on `Open in Tor` open up multiple tabs with the same site instead of highlighting the same tab

## Expected result:

Multiple clicks on `Open in Tor` should highlight the already opened tab with brave.com

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.25 Chromium: 87.0.4280.40 (Official Build) nightly (64-bit)
-- | --
Revision | 349b9adbfb2784db684617c7731a57d1e61b3be0-refs/branch-heads/4280@{#863}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? na
- Does the issue resolve itself when disabling Brave Rewards? na
- Is the issue reproducible on the latest version of Chrome? na

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron

**Comment by rebron** [comment]
@darkdh @karenkliu I think this should be the expected behavior  and maybe wontfix this one. So if clicking `Open in Tor` from a normal window, hitting that button multiple times will open a new tab in the `Tor window` of that same site versus grabbing focus of the initial tab that was opened.

**Comment by karenkliu** [comment]
@rebron sgtm

**Comment by darkdh** [comment]
@rebron It was intentional that make it new foreground tab per click. So I also prefer keeping it as it is right now.

**Comment by GeetaSarvadnya** [comment]
Thanks, @rebron @karenkliu and @darkdh - As per the above comments closing the issue as works as expected.
