### ISSUE TITLE
Browser leaks <canvas> fingerprint through iframes

### ISSUE THREAD

**Issue by frzsombor** [brave/brave-browser#12453]
## Description 
On Firefox, I am using a fingerprint blocking plugin called [CanvasBlocker](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/), which seems working pretty well. There is also a [test page](https://canvasblocker.kkapsner.de/test/) for that plugin. Using Firefox and the plugin, I always get "faked" fingerprint in all test cases, but it looks like Brave browser leaks the original fingerprint even in strict mode in some test cases. (I only checked the canvas tests)

## Steps to Reproduce
   1. Set fingerprint protection to standard or strict
   2. Navigate to https://canvasblocker.kkapsner.de/test/test.html
   3. iFrame Test 4, iFrame Test 5 and iFrame Test 6 leaks original fingerprint

## Actual result:
Original (equal to Google Chrome) fingerprint gets displayed in some cases.

## Expected result:
Same fake fingerprint in all test cases

## Reproduces how often: 
All the time

## Brave version (brave://version info)
Brave | 1.16.68 Chromium: 86.0.4240.111

**Comment by diracdeltas** [comment]
cc @pes10k

**Comment by pes10k** [comment]
This is already fixed :) https://github.com/brave/brave-core/pull/6941

**Comment by frzsombor** [comment]
I've downloaded and tried it with the (almost) latest, _Version 1.18.30 Chromium: 87.0.4280.40 (Official Build) nightly (x86_64)_ version, but experienced the same issues. 

![image](https://user-images.githubusercontent.com/7306657/98027449-fabc0900-1e0c-11eb-9a08-8f8a9df5cdeb.png)

**Comment by frzsombor** [comment]
@pes10k I've downloaded and tried it with the (almost) latest, _Version 1.18.30 Chromium: 87.0.4280.40 (Official Build) nightly (x86_64)_ version, but experienced the same issues. 

![image](https://user-images.githubusercontent.com/7306657/98028088-df053280-1e0d-11eb-895f-7b8597253bf4.png)

**Comment by frzsombor** [comment]
@pes10k I've downloaded and tried it with the (almost) latest, _Version 1.18.30 Chromium: 87.0.4280.40 (Official Build) nightly (x86_64)_ version, but experienced the same issues. 

![image](https://user-images.githubusercontent.com/7306657/98028088-df053280-1e0d-11eb-895f-7b8597253bf4.png)

**Comment by pes10k** [comment]
@frzsombor Ah, looks like there are still paths not covered.  Thank you very much for the bug report.  We'll get it sorted!

**Comment by stephendonner** [comment]
@goodov @pes10k for the testplan here, is it:

1. load https://canvasblocker.kkapsner.de/test/test.html
2. ensure that all hashes match?

That's what the original report says, just wanted to double-check 👍

**Comment by frzsombor** [comment]
For me, the last three test cases (_blob Test_, _offscreen Test_, _offscreen Worker Test_) are NOT the same as the other test cases above them in a fresh Chrome, but identical to each other. When I posted this issue I debugged the code of the website and I found that this is not a problem but a normal behaviour, however can't remember the reason for the difference. The problem was that the hashes starting with 'cd475...' were the same as I saw (and still see) in an original Chrome. I think the goal should be that all the test cases should be different from the ones that someone sees in a Chrome browser and they should be the same - except the last three, but those should be identical to each other. I hope this makes sense and thanks for your work.

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan, and comparing Chrome 

Google Chrome | 90.0.4430.85 (Official Build) (x86_64)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | macOS Version 11.2.3 (Build 20D91)

to both `Shields down` and `Shields up` behaviors on 

Brave | 1.25.33 Chromium: 90.0.4430.85 (Official Build) nightly (x86_64)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. load `https://canvasblocker.kkapsner.de/test/test.html` in Chrome and `Shields down` Brave
2. confirmed they have the same `Hash: 392ca3251952e526ce62c27e478e4a5d50d7417df441c761ec74cf7b1bd7a192 / 2ec58fab03d6b0c6782a0c44664577f666cbd1b4542a2c4b6f4cd9ceebe4b57a` values
3. switched `Shields up` and confirmed that Brave's hashes changed to ``Hash: 8006fe98c0587ea98bf5b16920630ec8d638550e187b445a9765f05f0a9d411b / f626a2480fedf5265962aff4f5de4ffde041a3259a4e9bd306dcc69c45390999`

Chrome vs. `Shields-down` Brave | Chrome vs. `Shields-up` Brave 👍 
--------------------------------|-------------------------------
<img width="1658" alt="Screen Shot 2021-04-21 at 12 34 57 PM" src="https://user-images.githubusercontent.com/387249/115611169-9b5c9300-a29e-11eb-9e7a-d76d4bf9d9c9.png"> | <img width="1652" alt="Screen Shot 2021-04-21 at 12 35 13 PM" src="https://user-images.githubusercontent.com/387249/115611178-9d265680-a29e-11eb-838b-e0c87f824b0d.png">
