### ISSUE TITLE
P3A buildflag cannot be set to false

### ISSUE THREAD

**Issue by freespeech4ever** [brave/brave-browser#12450]
## Description 
Compilation will fail on Windows/Linux/Mac if brave_p3a_enabled buildflag is set to false. Appears that only a few references in brave_browser_process_impl are not guarded. I am submitting a patch that allows it to build.

## Steps to Reproduce

   1. Set brave_p3a_enabled = false in components/p3a/buildflags.gni

## Actual result:
Fails due to undeclared identifiers.

## Expected result:
Successful build without P3A.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Latest.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by bsclifton** [comment]
Thanks for checking this out - P3A is a core piece of functionality which was only guarded as it didn't have an implementation on Android yet. This is being fixed when addressing https://github.com/brave/brave-browser/issues/6176 and the guards will be removed. My recommendation would be to patch this functionality out. The only place which is sending the data is `components\p3a\brave_p3a_service.cc` which you can patch to no-op
