### ISSUE TITLE
[Desktop] Rewards extension is registering duplicate listeners for Greaselion

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#12462]
## Description 

The rewards extension is registering multiple duplicate `webRequest` or `tabs` API listeners for Greaselion scripts. This is due to cleanup logic added to the port disconnect event handlers in https://github.com/brave/brave-core/pull/6889.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.20.88 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
Revision	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS	macOS Version 10.15.7 (Build 19H15)
```

Verified test plan from https://github.com/brave/brave-core/pull/7254

Confirmed able to open multiple tabs with various media publishers. 
Confirmed clicking between the tabs showed the expected publisher information in the panel.
Confirmed able to navigate to various media publishers within the same tab and the expected publisher information was shown in the panel. Coupled this with switching between tabs to confirm expected publisher information shown in the panel.
Confirmed able to close tabs and navigate to an existing tab with media publisher. Confirmed expected publisher information shown in the panel.

Confirmed able to tip media publishers.
Confirmed able to add media publishers to the Auto Contribute list.
Confirmed able to set up monthly contributions for media publishers.

One time Tip | Auto Contribute | Monthly Contribution
----- | ----- | -----
<img width="956" alt="1time tips" src="https://user-images.githubusercontent.com/28145373/105723264-96cd4c00-5ef4-11eb-9027-acb68766e162.png"> | <img width="701" alt="AC" src="https://user-images.githubusercontent.com/28145373/105723269-97fe7900-5ef4-11eb-802d-1e80f48cfcbc.png"> | <img width="949" alt="monthly tips" src="https://user-images.githubusercontent.com/28145373/105723275-992fa600-5ef4-11eb-9ff4-43763f3479a7.png">

Note, I encountered the following issues while testing:
- Restart required to get media publishers added to AC - https://github.com/brave/brave-browser/issues/13391
- Reddit takes a bit of time to get publisher info - https://github.com/brave/brave-browser/issues/12241
- GitHub favicon not shown on dark theme - https://github.com/brave/brave-browser/issues/12520
- "on YouTube" missing - https://github.com/brave/brave-browser/issues/13616
