### ISSUE TITLE
Display iOS QR Code feature once on Desktop when iOS v1.22 is released 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#12476]
## Description 

When iOS v1.22 is released and Rewards changes are implemented, we will then need to re-enable the QR code option on the desktop side (see https://github.com/brave/brave-browser/issues/12475).

cc @bsclifton 

## Miscellaneous Information:

Slack conversation concerning the issue:
https://bravesoftware.slack.com/archives/CKNHM4RTK/p1604089974029400

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/7053

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` on decision re: https://github.com/brave/brave-browser/issues/12872

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```

- Verified the description from the issue
- Verified QR Code option is shown on the brave://rewards page
![image](https://user-images.githubusercontent.com/38657976/101159860-1573de80-3654-11eb-960d-d130e819e22d.png)
- Additional testing on QR code is covered in https://github.com/brave/brave-browser/issues/12872#issuecomment-738737799
- Verified both clean and upgraded profiles

**Comment by bsclifton** [comment]
Removed milestone and marked as `wontfix` - we're hiding with https://github.com/brave/brave-browser/issues/13053
