### ISSUE TITLE
"Private" browser asks for identity documents, residential address, face photo and phone number? Okay.

### ISSUE THREAD

**Issue by keworr** [brave/brave-browser#12473]
The only way to verify the Brave-wallet for withdrawing cryptocurrency - use "uphold".

Uphold asks to upload a photo of face and identity document, full name, residential address, zip code, city, date of birth, phone number, and also asks for consent to send this biometric data for verification. What is this cringe, Brave?

![image](https://user-images.githubusercontent.com/47640060/97921322-35259780-1d74-11eb-8cb0-a3d66d871fb8.png)

![image](https://user-images.githubusercontent.com/47640060/97921968-28ee0a00-1d75-11eb-91d1-ff4a093350b4.png)

![image](https://user-images.githubusercontent.com/47640060/97921944-1ffd3880-1d75-11eb-9e03-9d61b502e1a7.png)

![image](https://user-images.githubusercontent.com/47640060/97921952-2390bf80-1d75-11eb-8eaa-92837598d45b.png)

**Comment by mandar-brave** [comment]
Dear @keworr Depositing currency in to Uphold needs KYC verification; like any regulation entity globally. Also, we are obligated to work according to OFAC rules as a registered business in the U.S. You can continue using Brave and Brave Rewards without needing to connect with Uphold.

**Comment by keworr** [comment]
And what problems can Brave have from getting into in illegal field? Most of your partners (i.e. most of your income) are companies like protonmail, which can easily pay with you in cryptocurrency.
And what problem, for example, relocate to Switzerland?

**Comment by mandar-brave** [comment]
If the issue is creating Utility with BAT, that is what we are working on as we speak. If the Q is about cashing out BAT, that needs to happen via a regulated entity. Different topics completely.

**Comment by keworr** [comment]
The issue is that you have invented analog a "digital yuan" or "crypto-ruble" that directly contradicts the idea of ​​privacy.

**Comment by keworr** [comment]
What is the problem with using normal platform to withdraw BAT? 
U.S. laws? You are a browser, why would you even be in a legal space?
