### ISSUE TITLE
Hide iOS QR Code function in Rewards Settings

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#12475]
## Description 

There is confusion surrounding the appearance of the iOS QR code transfer function in the Desktop version of Brave. Given that the feature is not actually operational at this time, the option should be hidden in the desktop version until the feature is actually working.

This will help avoid user confusion surrounding the feature, help avoid additional questions surrounding the feature and why it's being implemented (until the time is right to announce), and help reduce unnecessary support requests.

## Miscellaneous Information:

Slack conversation concerning the issue:
https://bravesoftware.slack.com/archives/CKNHM4RTK/p1604089974029400

**Comment by bsclifton** [comment]
This is hiding the work originally exposed with https://github.com/brave/brave-browser/issues/12176

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.16.72 Chromium: 86.0.4240.183 (Official Build) (x86_64)
-- | --
Revision | 0b568b034b8f7994697cb341eeca5979b84151cc-refs/branch-heads/4240@{#1374}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified test plan from https://github.com/brave/brave-core/pull/7020
Confirmed no QR code box on brave://rewards
Checked clean and upgrade (from `1.16.68`) profiles.

--------------
