### ISSUE TITLE
Provide a "Don't show again" button on the info bar 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12482]
## Description 

Feedback from @pes10k  friend on Crypto Setup info bar
```
I keep getting requests to start Crypto Wallets for Ethereum whenever I visit the New York Times in Brave.
I wouldn't mind being asked once, if there was a way I could say no and have it stick….
```

## Steps to Reproduce

   1. Clean profile
   2. Visit sites that support web3
   3. Keep getting setup CW info bar

## Actual result:

Keep getting prompted for setting up CW when web3 is detected but not setup 

## Expected result:
Have a `Don't ask again` button which sets to None for Ethereum provider in  `brave://settings/extensions`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.19.28 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | Linux

- Verified `Don't show again` button is shown when a Dapp is detected
![image](https://user-images.githubusercontent.com/17010094/100118843-1e073080-2e6e-11eb-8bc3-8333c8f90d41.png)
- Verified clicking on the `Don't show again` button sets `Ethereum provider for using Dapps` to `None`
- Verified upgrading from an older version where its sets to `None` doesn't show the info bar prompt

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.75 Chromium: 87.0.4280.88 (Official Build) (x86_64)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | macOS Version 10.15.7 (Build 19H15)
```

Verified STR from description
Verified items from https://github.com/brave/brave-core/pull/7162#issuecomment-733071678

Confirmed button shows on the info bar:
<img width="1034" alt="Screen Shot 2020-12-03 at 8 32 51 AM" src="https://user-images.githubusercontent.com/28145373/101024492-26342f80-3542-11eb-9d75-1ddb0535038f.png">

Confirmed clicking on the `Don't ask again` button sets `Ethereum provider for using Dapps` to `None`:
<img width="1033" alt="Screen Shot 2020-12-03 at 8 33 26 AM" src="https://user-images.githubusercontent.com/28145373/101024539-3ba95980-3542-11eb-8cb3-60edf800a28f.png">

Confirmed setting is retained on browser restart.

Installed 1.17.73. Set `Ethereum provider for using Dapps` to `None`. Upgraded to 1.17.75. Visited `cryptokitties.co`. Confirmed no info bar was displayed. 

-----------
