### ISSUE TITLE
Menu buttons alignment is wrong on CR87

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12483]
## Description 
Menu buttons alignment is wrong on CR87

## Steps to reproduce 

   1. Install 1.18.27 x64 nightly build
   2. Open menu
   3. Buttons are on the top of flyout menu rather than bottom 

## Result

Actual | Expected
-- | --
![image](https://user-images.githubusercontent.com/17010094/97953160-93b03d00-1d97-11eb-9789-a65a3cfa99c2.png) | ![image](https://user-images.githubusercontent.com/17010094/97953180-9dd23b80-1d97-11eb-991e-e4e28bbc483b.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.18.27

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Can't repro it all the time. Happened on upgrade once as well

**Comment by samartnik** [comment]
I wasn't able to reproduce, applied possible fix with proper default value for bottom toolbar

**Comment by srirambv** [comment]
Found the root cause of the issue. Happens when you disable bottom toolbar and skip on restarting browser. 
![menu](https://user-images.githubusercontent.com/17010094/98786914-b6290280-23f6-11eb-8474-93a77520e8a0.gif)

Reopening the issue and moving out of milestone. @samartnik please close the issue if you feel its invalid.

**Comment by srirambv** [comment]
This still isn't fixed. Menu buttons alignment is still off when disabling bottom toolbar but seems fixed for enabling

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 with Android 5.1 running 1.18.67 Bravearm.apk
- Verified STR from description
- Steps from https://github.com/brave/brave-browser/issues/12483#issuecomment-725279013 still reproduce the issue and are covered under follow up issue https://github.com/brave/brave-browser/issues/12926. Comments added to that issue. 

----------
