### ISSUE TITLE
Publisher info is not shown when rewards panel is opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12488]
## Description 
Publisher info is not shown when rewards panel is opened

## Steps to reproduce 

   1. Install nightly 1.18.27
   2. Visit any publisher page and click on rewards panel
   3. Skip rewards onboarding 
   4. Publisher info is not shown in the panel
   5. Open brave://rewards
   6. Go back to same publisher page from step 2 and open rewards panel, shows pub info

## Actual result 
https://youtu.be/qEURZ2-VeWo

## Expected result
Should show pub info when panel is opened

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.18.27

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by LaurenWags** [comment]
Encountered this with #12992 after taking the tour, publisher info is not shown in the panel.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravearm `1.18.71`
- Verified STR from the description and ensured that pubs info is shown in the BR panel

Screen 1| Screen 2 | Screen 3 | Screen 4
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/38657976/102074817-5a093200-3e2b-11eb-805b-899aa5da93bb.png) | ![image](https://user-images.githubusercontent.com/38657976/102074869-68efe480-3e2b-11eb-8f62-9ee82dddea9f.png) | ![image](https://user-images.githubusercontent.com/38657976/102074898-74dba680-3e2b-11eb-9ce3-133b796e5d0c.png) | ![image](https://user-images.githubusercontent.com/38657976/102074922-815fff00-3e2b-11eb-88ee-fcd06d25eb3a.png)
