### ISSUE TITLE
Browser crash when selecting data preferences in Sync 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12489]
## Description 
Browser crash when selecting data preferences in Sync 

## Steps to reproduce 

   1. Install 1.18.27 x64 build
   2. Enable Sync 
   3. Tap on `Data preferences`, browser crash

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/97975250-bd318e80-1dc0-11eb-9888-9e5cc9f0fdc2.png>

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by AlexeyBarabash** [comment]
I need to pick this commit https://github.com/brave/brave-core/pull/6976/commits/a675569f429e9e7c6dcaf024f0001798d675e86b

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.66 x64 beta build
- Verified no browser crash when selecting categories 
-------------
Verification passed on OnePlus 6T with Android 10 running 1.17.66 x64 beta build
- Verified no browser crash when selecting categories
