### ISSUE TITLE
Download notification continues forever

### ISSUE THREAD

**Issue by theoturner** [brave/brave-browser#12493]
## Description

File downloads on Android complete (as seen in file explorer) but the notification (with status 'Downloading...') continues forever. The notification cannot be dismissed, and it cannot be stopped by quitting the app; Brave must be force stopped in Settings.

## Steps to reproduce 

   1. Download a file.

## Actual result 

Download notification status never changes to complete, the notification cannot be dismissed and the notification never disappears.

## Expected result

Download notification status changes to complete once download is complete and can be dismissed.

## Issue reproduces how often 

Always, every download.

## Version/Channel Information:

Android Brave 1.16.70 (30 Oct 2020) from Play Store. Bug has been present in at least the version before this.

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version

1.16.70 (30 Oct 2020)

**Comment by davidlb** [comment]
Same here, running Android 8

**Comment by theoturner** [comment]
Bug still present in 1.16.76

**Comment by theoturner** [comment]
Bug still present in 1.17.72 - any word on this?

**Comment by theoturner** [comment]
This has now been fixed.
