### ISSUE TITLE
Sync categories should be renamed to Data preferences

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12490]
## Description 
Sync categories should be renamed to Data preferences

## Steps to reproduce 

   1. Install 1.18.27 x64 build
   2. Open Sync settings
  

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/97976143-2239b400-1dc2-11eb-9c7e-3cdb9b363136.png>

## Expected result
<img width=300 src=https://user-images.githubusercontent.com/17010094/97975944-cff89300-1dc1-11eb-9544-1d9b316e13ac.png>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.16.70

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @AlexeyBarabash 
Encountered #12489

**Comment by AlexeyBarabash** [comment]
@srirambv 
this is expected change agreed with design team (@jamesmudgett  and @bradleyrichter )

See https://github.com/brave/brave-core/pull/6732#issuecomment-714525359

**Comment by AlexeyBarabash** [comment]
Confirm I see the crash

**Comment by srirambv** [comment]
Based on https://github.com/brave/brave-core/pull/6732#issuecomment-714525359 think we can just rename this issue and use it to verify the text change for categories as I don't see any issue created for that. @AlexeyBarabash please let me know if there is a specific issue for the text change

**Comment by AlexeyBarabash** [comment]
@srirambv 
yes, there is not issue for design change, design was changed during returning delete buttons.
The idea to rename issue to link it to change is good.

**Comment by srirambv** [comment]
Fixed with https://github.com/brave/brave-core/pull/6732

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.18.51 64 beta build
- Verified categories is renamed to `Data Preferences`

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/99268303-e3254d00-281c-11eb-873d-2d954385dfeb.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/99268307-e6b8d400-281c-11eb-9cca-cb50ad0c015c.png>
