### ISSUE TITLE
Staging grants don't show up instantly when wallet is created

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12491]
## Description 
No grants on staging with Rewards everywhere on Android

## Steps to reproduce 

   1. Install 1.18.27 x64 nightly build
   2. Set rewards to staging
   3. No grants shown to claim
   4. Install a 1.17.x build and set rewards to staging, grant shows up and able to claim it

## Actual result 
No grants on staging with Rewards everywhere on Android

## Expected result
Should provide grants on staging

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.18.27 x64 build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by NejcZdovc** [comment]
@husobee @evq we removed limitation that you need to send paymentId to get grants. Any special use case for android/ios?

**Comment by srirambv** [comment]
The issue seems to be delay in getting grants. Eventually grants show up after enabling ads

**Comment by emerick** [comment]
@deeppandya Is this related to the promotions URL problem we saw on Android on staging yesterday?

**Comment by deeppandya** [comment]
@emerick yeah it's related. I will close it with comment.

**Comment by deeppandya** [comment]
This issue is fixed in https://github.com/brave/brave-core/pull/7378 sonclosing it now.

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 with Android 5.1 running 1.18.71 Bravearm.apk
* Using staging env, confirmed once large and small onboarding is "x"-d out, UGP grant shows in the UI to be claimed.
* Note, claiming grant causes a crash, logged with https://github.com/brave/brave-browser/issues/13150
