### ISSUE TITLE
[Desktop] Customize Dashboard > Cards "Hide" button in dark theme is not visible

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#12506]
## Description 

The Customize Dashboard > Cards "Hide" button in dark theme is hard to see.

## Steps to Reproduce

In dark theme:

   1. Go to a new tab page
   2. Click on "Customize"
   3. Go to "More Cards" section
   4. Hide a widget if none are already hidden
   5. See that the "Hide" button has the wrong color; it's not visible

## Actual result:

![image](https://user-images.githubusercontent.com/2388823/98037435-6764e280-1dd0-11eb-9779-6e7254b6f83c.png)

## Expected result:
"Hide" button is more lightly colored in dark theme.
![image](https://user-images.githubusercontent.com/2388823/98037566-9b400800-1dd0-11eb-9c93-093dc15de281.png)

Figma: https://www.figma.com/file/0pOzvvueMoeaCxKaVoU59Z/Widget-discovery?node-id=1921%3A22652

## Reproduces how often: 

Easily

## Brave version (brave://version info)

All versions

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards?  N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Reproduce the issue in 1.17.x
![image](https://user-images.githubusercontent.com/38657976/99967293-a8dc2280-2dbd-11eb-98ab-fad6cd472367.png)
- Verified the STR from the description and ensured `Hide` button color is visible in Dark mode in 1.18.x
![image](https://user-images.githubusercontent.com/38657976/99967396-d3c67680-2dbd-11eb-89c9-dc555d4ea9a5.png)
