### ISSUE TITLE
update NTP background images for 2020/2021

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#12508]
## Description 

Update NTP background images for 2020/2021

## Designs
<img width="606" alt="Screen Shot 2020-11-11 at 6 21 09 PM" src="https://user-images.githubusercontent.com/2388823/98887360-b226d000-244a-11eb-86a8-8e6153ca10fe.png">

## Assets
[AVIF in our GDrive](https://drive.google.com/open?id=10njiWh7VKvM38GMkWlE_6tDOKEFSnCPV&authuser=kliu%40brave.com&usp=drive_fs)

photo creds + links
[2020-10 photo attribution and license.pdf](https://github.com/brave/brave-browser/files/5527720/2020-10.photo.attribution.and.license.pdf)

## Test plan
Images should match those shown in our GDrive

**Comment by karenkliu** [comment]
@rebron This is ready for dev!

**Comment by rebron** [comment]
cc: @simonhong

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.68 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified that images shown in the NTP's matched with Gdrive images

<details>
<summary>Screenshots</summary>

</details>

**Comment by GeetaSarvadnya** [comment]
@simonhong As per the conversion here https://github.com/brave/brave-core/pull/7138#discussion_r523386572 @rebron suggested using brave community page after clicking on `Corwin Prescott's`, as of now it's credit's name is just label, not link in NTP

**Comment by LaurenWags** [comment]
@GeetaSarvadnya the 404 page for `Zane Lee` is logged with https://github.com/brave/brave-browser/issues/13207, thanks @okidokiokami 😄

**Comment by simonhong** [comment]
@GeetaSarvadnya Pushed https://github.com/brave/brave-core/pull/7522 for using community page as a credit link.
and it also fixes 404 page issue.

**Comment by kjozwiak** [comment]
@simonhong believe we still need to get `Corwin Prescott's` fixed as it's not pointing to anything as per @GeetaSarvadnya. @karenkliu do we have a website that we can use for Corwin?
