### ISSUE TITLE
crash when clicking on BAT panel after skipping onboarding

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12509]
## Description 

Brave will crash every time the BAT panel icon is tapped when onboarding has been skipped.

## Steps to reproduce 

   1. launch either `1.16.73 CR 86.0.4240.185` or `1.16.70 CR: 86.0.4240.111`
   2. skip/don't enable `Privacy Reporting`
   3. tap on BAT icon and skip the `Rewards` onboarding
   4. tap on the BAT icon and Brave will crash (this happens every time)

## Actual result 

Example of Brave crashing --> https://youtu.be/_yquqm4BiTw

## Expected result

Brave shouldn't be crashing.

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `No`
- Can you reproduce this issue with the current Play Store Nightly version? `No`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 10`
   
## Brave version

* `1.16.70 CR: 86.0.4240.111` - *Reproduced*
* `1.16.73 CR 86.0.4240.185` - *Reproduced*

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `No, if you enable/disable, still crashes`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @SergeyZhukovsky @aekeus @srirambv

**Comment by NejcZdovc** [comment]
fixed by https://github.com/brave/brave-core/pull/7051

**Comment by btlechowski** [comment]
Verification passed on Brave v1.16.74 on Samsung Galaxy Tab S5e (Android 9.0)

Reproduced the crash on 1.16.70
Verified no crash on v1.16.74. Verified 7 times.
