### ISSUE TITLE
Disable upgrade notification

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#12507]
## Description 
Disable notification on upgrade. We have users who receive it still, probably it was never hit as we don't show it after tap on it.
![Screenshot from 2020-11-03 16-06-19](https://user-images.githubusercontent.com/12011303/98040676-a6099580-1dee-11eb-83a5-98a266a1c291.png)

## Steps to reproduce 

   1. Install a fresh installation of Brave.
   2. Update it to a newer version.

## Actual result 
See the above notification.

## Expected result
No notification

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` on `Android 10` using `1.16.75 CR: 86.0.4240.193`

* ensured that upgrading from `1.16.74 CR: 86.0.4240.185` to `1.16.75 CR: 86.0.4240.193` didn't display the `Save Data Online` notification. Originally reproduced the issue via https://github.com/brave/brave-core/pull/7047#issuecomment-723644848.
