### ISSUE TITLE
[Desktop] Remove duplicate NTP controls from brave://settings/newTab

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#12505]
## Description
Currently, there is a lot of overhead with having duplicate NTP controls on both Customize Dashboard in NTP and brave://settings/newTab. Also having a copy of everything in settings is unsustainable since we're going to add more options to each Customize Dashboard section over time.

### brave://settings/newTab
Remove the redundant NTP controls from brave://settings, but include searchable keywords that brings the user to the NTP section. The NTP section will now re-direct users to the New Tab page with the "Customize Dashboard" panel open if they want to customize their new tab page. 

![image](https://user-images.githubusercontent.com/2388823/98580478-e052b700-2274-11eb-9768-3f900774b54b.png)

Hide the `Customize background images, sponsored...` string when the New tab page shows > Homepage or Blank page option is selected, just like how it currently works:

![image](https://user-images.githubusercontent.com/2388823/98034673-3d112600-1dcc-11eb-8a31-a5cad000f17e.png)

Update strings in brave://settings/newTab every time our default listed widgets change. 

### Turn off all widgets
Include a section at the bottom of Customize Dashboard > Cards to turn off all currently visible widgets. This does not prevent users from being notified of new widgets.

![image](https://user-images.githubusercontent.com/2388823/98037050-dd1c7e80-1dcf-11eb-8949-ede48ce4d66d.png)

Dark theme is supported: 
![image](https://user-images.githubusercontent.com/2388823/98037007-cece6280-1dcf-11eb-9d21-8b8e99ff5206.png)

## Assets
brave://settings/newTab Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/?node-id=61%3A7509
Turn off all widgets Figma: https://www.figma.com/file/0pOzvvueMoeaCxKaVoU59Z/?node-id=1880%3A22603

**Comment by rebron** [comment]
cc: @ryanml

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.19.73 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the STR from the description
