### ISSUE TITLE
AC/Recurring tip takes a while to go through 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12510]
## Description 
AC/Recurring tip doesn't go through

## Steps to reproduce 

   1. Install 1.18.27 nightly build
   2. Claim grants on staging
   3. Add sites to ac list 
   4. Set recurring tips to verified pubs
   5. Trigger AC manually
   6. Neither AC nor recurring tips go through balance remains same

## Actual result 
AC/Recurring tip doesn't go through

## Expected result
Should perform AC and send recurring tips when triggered

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.18.27 x64 nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
This again seems to be an issue with slow AC/Recurring tips being processed. @GeetaSarvadnya also ran into it on her device but comparatively the time it took to do ac/rec tip was much less

**Comment by NejcZdovc** [comment]
For sending tokens out we have random delays, so it can take sometime to go through

**Comment by milan-dell** [comment]
> 

>

**Comment by srirambv** [comment]
closed  based on previous comment
