### ISSUE TITLE
Linux Crash doesn't list in chrome://crashes. Navigating to chrome://crash shows error message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1251]
## Description 

Linux Crash doesn't list in `chrome://crashes`. Navigating to `chrome://crash` shows error message

## Steps to Reproduce

   1. Open a new tab and visit `chrome://crash`
   2. Open a new tab and visit `chromes://crashes/` nothings listed
   3. After a min the GTK crash message pops up

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/45901543-450ad900-bdb1-11e8-81f5-aaab628b76e7.png)

## Expected result:
Should list the crash on browser and send the report if its enabled in settings

## Reproduces how often: 

100%

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

### Reproducible on current release:

Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Follow up to #285 for Linux

**Comment by kjozwiak** [comment]
Went through the test case outlined in the PR using `Mint 19.1 x64 VM` and everything seems to be working. Once I enabled crash reporting via the `brave://settings`, I made sure that crashes where appearing under `brave://crashes` when crashing via:

* `brave://crash` and ensured that the crash was recorded under `brave://crashes` and was visible in stats.brave
* `chrome://gpucrash` and ensured that the crash was recorded under `brave://crashes` and was visible in stats.brave

However, there's one difference that I noticed. Under Windows/macOS, even if you have crash reporting disabled, the crashes are saved in `chrome://crashes` but are not sent. The user has the ability to send each one manually without needing to enable reporting. However, under Linux, if you have crash reporting disabled, crash reports will not be recorded in `brave://crashes`.

The other ting that's a bit confusing is that on Linux, the setting appears as:

```Automatically send usage statistics and crash reports to Brave Software```

However, on Windows and macOS, the setting appears as:

```Automatically send crash reports to Brave```

I'll create an issue re: the wording discrepancy. @rebron @bbondy thoughts on changing the crash behaviour so it matches macOS/Win? Or leaving it like this is fine?

**Comment by srirambv** [comment]
Verified the steps form test plan on Ubuntu (physical machine) and works great. Was also able to verify the crash report on [stats.brave](https://stats.brave.com/dashboard#crash/5c668a63d4a29a001f5ae4f3)
![image](https://user-images.githubusercontent.com/17010094/52850807-71493c80-313a-11e9-9761-adb9f8a6beef.png)

>Under Windows/macOS, even if you have crash reporting disabled, the crashes are saved in `chrome://crashes` but are not sent.

Agree with @kjozwiak behaviour is different compared to mac/Windows when crash reporting is disabled. Should be similar.

**Comment by kjozwiak** [comment]
@mkarolin it doesn't seem like the reports are being uploaded into stats.brave.com. They're appearing under `brave://crashes`, however it doesn't find anything under `stats.brave` when searching using the generated `crash id`. Example:

* launch `0.60.44 Chromium: 72.0.3626.109`
* enable crash reporting via `brave://settings` and restart the browser
* once restarted, crash using `brave://crash` or `chrome://gpucrash`

You'll see the following:

```
--2019-02-19 16:08:18--  https://laptop-updates.brave.com/1/bc-crashes
Resolving laptop-updates.brave.com (laptop-updates.brave.com)... 151.101.125.7
Connecting to laptop-updates.brave.com (laptop-updates.brave.com)|151.101.125.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16 [text/html]
Saving to: ‘/dev/fd/4’

     0K                  
 Crash dump id: 49e4d4f7cab8d55a
```

However, if you search `stats.brave` for `49e4d4f7cab8d55a`, you won't find the crash. Tried it a few times on two different linux machines with the same results. Platforms used:

* Mint 19.1 x64 (psychical machine) - didn't upload to stats.brave
* Ubuntu 18.04 x64 (VM) - didn't upload to stats.brave

Here are some of the crash reports that I was expecting to find under `stats.brave`:

* 1cfc6d359217fb1d
* 11b7fde0ca05667a
* 413719a15012e33b

**Comment by mkarolin** [comment]
@kjozwiak, @srirambv: regarding the difference in behavior between Win/Mac and Linux, that is likely because Win/Mac use Crashpad for crash handling and reporting, whereas Linux uses Breakpad. There's some code that indicates that there's an effort to transition Linux to Crashpad as well, but it hasn't happened yet (https://chromium.googlesource.com/crashpad/crashpad/+/HEAD/doc/status.md).

**Comment by kjozwiak** [comment]
@mkarolin awesome, sounds good 👍 

Regarding the above issue with crashes not being uploaded. @btlechowski confirmed that he's not seeing any crashes uploaded on Win 7. I tried Windows 10 x64 and getting the same results, not seeing any of the crashes appear in stats.brave. @LaurenWags mentioned that it's working for macOS. So we either regressed reporting in the past ~week or so or there's an issue with the server. I pinged @aekeus and he's going to take a look when he gets some time 👍 If the server side looks fine, I'll try getting a regression range.

**Comment by srirambv** [comment]
@kjozwiak the crash report id that i mentioned in https://github.com/brave/brave-browser/issues/1251#issuecomment-463989053 is still visible on stats.brave. However on the latest rc build when i force crash and generate the id(6fea8799f09804d3) that is not being uploaded to stats. So its either going into backlog and still not updated on stats or its broken after channel migration happened because  https://github.com/brave/brave-browser/issues/1251#issuecomment-463989053 was done when it was still on beta channel

**Comment by kjozwiak** [comment]
@srirambv yup, just waiting for a confirmation from @aekeus. Once we know that the servers are not having issues nor are backed up, we'll need go through a regression range and find out where reporting broke.
