### ISSUE TITLE
Playstation Store not loading buttons

### ISSUE THREAD

**Issue by seanarnold** [brave/brave-browser#12517]
## Description 

Playstation Store does not the 'pre-order' buttons on game pages.

## Steps to Reproduce

   1. Visit https://store.playstation.com/en-nz/product/EP9000-PPSA01417_00-MARVELSSMMDDE000
   2. Observe orange Pre order buttons are missing
   3. 

## Actual result:

![Screen Shot 2020-11-05 at 8 02 43 AM](https://user-images.githubusercontent.com/693929/98156887-5a193680-1f3d-11eb-9b80-426877561f6d.png)

## Expected result:
![Screen Shot 2020-11-05 at 8 02 56 AM](https://user-images.githubusercontent.com/693929/98156891-5c7b9080-1f3d-11eb-9fc0-6d4a2962ec3b.png)

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.15.6 (Build 19G73)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

Happens with shields down.

Works in Chrome:

Google Chrome | 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}

**Comment by ryanbr** [comment]
@seanarnold I just loaded the site, seemed okay here (no login required). Does it occur in private-window mode?

**Comment by rebron** [comment]
@seanarnold This looks like this is working. Can you take a look?
![Screen Shot 2021-02-16 at 9 13 49 AM](https://user-images.githubusercontent.com/5951041/108097704-58303a80-7037-11eb-91e3-d891052c19fc.png)

**Comment by seanarnold** [comment]
Confirmed working.
