### ISSUE TITLE
Add a flag behind QA preferences to speed up reconcile

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12512]
## Description 
Because of #12510, QA needs to spend time waiting for the random delay to trigger AC/Recurring tips. QA should have a flag behind preferences which when toggles does shorter reconcile wait time

## Steps to reproduce 

   1. Follow steps from #12510 

## Actual result 
Slow reconcile time

## Expected result
Make it faster with the toggle 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by Miyayes** [comment]
Closing this as resolved. See Lauren's comments above.
