### ISSUE TITLE
Heavy Audio distortion on some Videos

### ISSUE THREAD

**Issue by Anti-ctrl** [brave/brave-browser#12516]
## Description 

Sometimes the Audio on Youtube is really distorted for some Videos, with lots of crackling and screeching. Sounds like really bad clipping. (didnt test with other sites, except 3 hours of twitch w/o Problems.) 

## Steps to Reproduce

   1. Seems kinda random
   2. Skipping through a Playlist seems to trigger it faster.

## Actual result:

Sound is heavily distorted.

## Expected result:
Sound plays normal w/o Distorsion

## Reproduces how often: 

Seems random after some Videos. Sometimes nothing for hours and then it kicks in when it changes to the next Video.

## Brave version (brave://version info)

Brave | 1.16.72 Chromium: 86.0.4240.183 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 0b568b034b8f7994697cb341eeca5979b84151cc-refs/branch-heads/4240@{#1374}
Betriebssystem | Windows 10 OS Version 2009 (Build 19042.610)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

I have/had some Audioproblems with my Setup, as i´m running kinda old Hardware, with the newest Windows Version. It force Upgraded me tho and i only have Audio whenever i remove the Provided Audio Driver for my Device. Windows Drivers then kick in and the Device works flawlessly, except the weird audio issues in brave, as mentioned above. If more Infos are required, please let me know.

**Comment by ryanbr** [comment]
Hmm interesting, which sound card/device are you using?

Does testing in a new Brave profile help?  Not sure if it'll help but does disabling Hardware Acceleration in `brave://settings/system`  improve the situation?

**Comment by Anti-ctrl** [comment]
> Hmm interesting, which sound card/device are you using?
> 
> Does testing in a new Brave profile help? Not sure if it'll help but does disabling Hardware Acceleration in `brave://settings/system` improve the situation?

Thanks for the reply. I have done some more Testing and i think its just my fault. Its a Problem in Windows 10 2009, as its present in Google Chrome too. Didnt recognized it first, because its somewhat random. It also happens sometimes for Windows Sounds too. IDK if its because Brave is running in the Foreground, but i wouldnt guess so. I had trouble with Sound on this System since i got it.

ATM I´m using a Gigabyte G1 Assassin with onboard Audio. Thats what you get, if u purchase "Enthusiasm Hardware". No support whatsoever. I was in contact with Creative, as they provided the Audio Chip for the Board, but they say "talk to Gigabyte", because their driver doesnt work, but neither does Gigabytes. I guess thats well beyond this topic.

**Comment by ryanbr** [comment]
Example of a "Beep" distortion.  https://youtu.be/NFRttrENhmw?t=1401  (SFW)  Which also shows in Firefox/Chrome and Brave. Sometimes there is video/audio encoding bugs that occur, making unusual noises or video playback issues. 

If you have a sample video I can check, see if it occurs here.

**Comment by Anti-ctrl** [comment]
> Example of a "Beep" distortion. https://youtu.be/NFRttrENhmw?t=1401 (SFW) Which also shows in Firefox/Chrome and Brave. Sometimes there is video/audio encoding bugs that occur, making unusual noises or video playback issues.
> 
> If you have a sample video I can check, see if it occurs here.

Yeah, it sounds something like this, but it starts "slowly" and gets worse and worse, till you close the tab, but after that it takes just minutes to reappear instead of, sometimes, hours. I´m 70 Percent sure its a Problem with my Windows driver. If that happens again at some point, i will try and make a video. If its noticeable there, i will upload it. ATM i have limited time to do anything really. Thanks for the help offering!

**Comment by bsclifton** [comment]
@Anti-ctrl I'll close this issue for now - but maybe you can bookmark and come back here if you have more info (you can always re-open the issue and/or leave comments 😄). Thanks for helping diagnose the issue more

**Comment by Anti-ctrl** [comment]
So, I´m back again with more Information.
I´m now almost 95 Percent sure, that its the fault of Windows and the Driver it puts on here. Unfortunately i cant test another driver, as this machine is kinda old and something "special" in terms of Hardware.
Also its kinda difficult to trigger that Problem. I only have a Headset and i dont wanna fry it for a Video, tho thats also kinda problematic. I will try to make a Video in the next Days. There must be a Problem which is not only Windows related, as i dont have that in other Apps like Games or something.

Just imagine you go into VLC Media Player and crank the Volume in the Player to like 1000 Percent, but at the same time you lower the Output from within Windows. That Way the Music is the same Loudness, but it clipps really hard. Thats the Noise i can hear. It starts slowly but after ~10 Seconds it really hurts in the Ears.

**Comment by pbaykalov** [comment]
I have similar issue in Windows 11 and Brave is literally the only program which does this.
For me setting volume in browser to 50% helps the issue. Sounds like anything higher is artificial volume boost which clips data.

**Comment by pbaykalov** [comment]
I have similar issue in Windows 11 and Brave is literally the only program which does this.
Seeking the video 3 seconds back fixes the problem temporarily.
