### ISSUE TITLE
Whatsapp web is no longer working

### ISSUE THREAD

**Issue by nestorpastor** [brave/brave-browser#12513]
## Description 
i updated to the last version of brave. 
and now Whatsapp web is telling only some others browsers are available to use it, but brave is not on the list. 
probably this validation is coming from WhatsApp and not from brave, but just let you know.

## Steps to Reproduce

   1. open https://web.whatsapp.com/

## Actual result:
![image](https://user-images.githubusercontent.com/15873932/98115261-4e6a3900-1e85-11eb-9b7d-2fbe457da3e2.png)

## Expected result:
open whatsapp web

## Brave version (brave://version info)
Version 1.16.72 Chromium: 86.0.4240.183 (Official Build) (x86_64)

**Comment by debuxed** [comment]
Facing the same issue, WhatsApp is salty about open source and bloat-free browsers.

**Comment by ryanbr** [comment]
@nestorpastor Does it show up without a login? Also, does using Brave beta help?

**Comment by debuxed** [comment]
@nestorpastor I tried to re-install and it works for me now.

**Comment by t0m5k1** [comment]
I'm getting the same issue with the latest version too: 1.16.75 Chromium: 86.0.4240.193 (Official Build) (64-bit)
Difference is that it's request Chrome 60+

https://www.reddit.com/r/brave_browser/comments/jsvc7k/i_frequently_get_this_message_on_the_whatsapp/

**Comment by skinnisa** [comment]
Same issue here, brought from Reddit.

**Comment by rebron** [comment]
cc: @kjozwiak to double check on release and beta channel

**Comment by t0m5k1** [comment]
Latest update fixed this for me
Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)

**Comment by kjozwiak** [comment]
Been using WhatsApp Web on the following builds and haven't had any issue:

```
Brave | 1.19.39 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2009 (Build 19042.630)
```

````
Brave | 1.18.65 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2009 (Build 19042.630)
```

```
Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2009 (Build 19042.630)
```

Also tried on `macOS` and that worked as well.

> Latest update fixed this for me
> Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)

@debuxed @nestorpastor is it working for you guys as well or still having issues?

**Comment by kjozwiak** [comment]
Going to close this off as it seems to be working. @debuxed @nestorpastor if you're still experiencing the issue, please open a new issue 👍 Thanks again for filing.
