### ISSUE TITLE
BrowserGuestModeEnabled policy is ignored by Open Guest Window

### ISSUE THREAD

**Issue by edduv** [brave/brave-browser#12524]
On linux, if /etc/chromium/policies/managed/noguest.json contains

    { "BrowserGuestModeEnabled":false }

brave://policy/ indicates the policy is active, but it is ignored when I click "Open Guest Window".  Similarly, the menu option should probably also not be visible if policy indicates guest mode should not be allowed.

A guest window, among other things, lacks all extensions that would otherwise be loaded.

brave:version 1.16.72 Chromium: 86.0.4240.183 (Official Build) (64-bit)

**Comment by edduv** [comment]
I'd like to help fix this, but I am not familiar with Brave code.

It looks to me like the fix should be something like:

https://github.com/edduv/brave-core/commit/d3366ae847c7021f8abd30eca9e4c41a87689408

but with IsBrowserGuestModeEnabled() filled in.

**Comment by edduv** [comment]
I created a pull request that contains a fix for this issue: https://github.com/brave/brave-core/pull/7319 .  Any chance it'll be accepted sometime soon?

**Comment by edduv** [comment]
@bsclifton Any comments?  The patch is pretty small, and I think it fixes this issue.

**Comment by btlechowski** [comment]
Added `QA/Test-All-Platforms` since all platforms handle the policy differently.

**Comment by stephendonner** [comment]
Verified `FIXED` with great help from @simonhong 🙇  on `beta`, using:

Brave | 1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}

**Steps:**
1. in Terminal, I entered: `defaults write com.brave.Browser.beta BrowserGuestModeEnabled -bool false` and hit `return`
2. restarted macOS
3. launched Brave Beta

**Verified:**

**Open Guest Window is removed from the context menu:**

| After | Before |
|-------|-------|
<img width="983" alt="Screen Shot 2021-03-03 at 6 22 41 PM" src="https://user-images.githubusercontent.com/387249/109901510-136aed00-7c4e-11eb-826c-dcccdccdf37a.png"> | <img width="1314" alt="Screen Shot 2021-03-03 at 6 20 33 PM" src="https://user-images.githubusercontent.com/387249/109901903-a6a42280-7c4e-11eb-9f28-0d719c16789b.png">

`BrowserGuestModeEnabled` is set to `false` in `brave://policy`
![image](https://user-images.githubusercontent.com/387249/109901514-1534b080-7c4e-11eb-87b9-5b2914c79c15.png)
