### ISSUE TITLE
Fork upstream NTP as too much patches there

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#12521]
## Description 
We have too much patches in New Tab Page already. It would be better to fork it on that point as too much things are customised there for Brave.

**Comment by bsclifton** [comment]
Would love to review our implementation in more detail - with Desktop, it's not feasible to share the code as we use React and trying to shim this into the Polymer code would be a mess. The Chromium NTP has a LOT of handlers registered that it pulls in too ☹️ 

Using our own page cuts down the amount of items loading. But then on Desktop we ended up integrating with InstantService and tried to leverage some of the Chromium page as most of what is offered is super useful

Maybe next step would be that I could setup a meeting with folks where we can open the code and review it together 😄 I'd be happy to share the desktop experience too

**Comment by bsclifton** [comment]
Doesn't look like we can use `InstantService` or the `NewTabPageHandler` as those appear to be desktop only ☹️ 

Will need to look more at our existing implementation for NTP and see how we can leverage some of the Chromium parts without necessarily causing a rebase problem

**Comment by bsclifton** [comment]
Closing as stale - we can maybe address in https://github.com/brave/brave-browser/issues/13714
