### ISSUE TITLE
"Add to Brave" only appears in English

### ISSUE THREAD

**Issue by gabrc52** [brave/brave-browser#12526]
## Description 
On the Chrome web store, the "Add to Chrome" button says "Add to Brave instead". However, this only happens in the English language, and not in other languages. Other languages still say Chrome.

## Steps to Reproduce

   1. Open a Chrome extension on the Chrome web store

## Actual result:

"Add to Chrome" in non-English language

## Expected result:
"Add to Brave" in non-English language

## Reproduces how often: 

Easily reproduced

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
@gabrc52 Is this a dupe of https://github.com/brave/brave-browser/issues/10570?

**Comment by gabrc52** [comment]
Yes, except this talks about non English languages in general, explicitly
