### ISSUE TITLE
Always deny geolocation in Tor

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1252]
## Steps to Reproduce

   1. Open https://browserleaks.com/geo in Tor Window
   2. Click Allow when prompted for geolocation

## Actual result:

access to geolocation is granted

## Expected result:
Always deny geolocation access, even if Brave shields are turned off or user grants access.
Same as in browser-laptop

## Reproduces how often: 

always

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

### Reproducible on current release:

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

cc @darkdh @riastradh-brave

**Comment by bbondy** [comment]
I don't think that's the correct behaviour. Let me know @darkdh if you disagree.

**Comment by btlechowski** [comment]
@bbondy We had similar issue in browser-laptop for Tor
1. The prompt was not shown at all.
2. Geolocation permission was always denied.
https://github.com/brave/browser-laptop/issues/13447

![image](https://user-images.githubusercontent.com/34715963/46232770-8599c200-c370-11e8-9bd3-42099868da88.png)

If the expected behavior is different for brave-browser, then please ignore this message.

**Comment by riastradh-brave** [comment]
For reference, we ended up tracking this here: https://github.com/brave/brave-browser/issues/1353
