### ISSUE TITLE
[Desktop] GitHub favicon does not display on panel/rewards page when using dark theme

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12520]
## Description 

If your install is using the "dark" theme, the standard GitHub favicon will not display on the panel or in brave://rewards.

This is similar to #9030 which noted this for the NTP top site tiles. On that issue, there's a comment noting that GH favicons are theme-aware, https://github.com/brave/brave-browser/issues/9030#issuecomment-617863785. Logging this issue for Rewards as I didn't want to assume any work done with that issue would carry over to rewards pages.

## Steps to Reproduce

   1. Use dark theme and have rewards enabled
   2. Navigate to a GH publisher (non-verified is best so you get the default favicon)
   3. Open panel

## Actual result:

Looks like no favicon
<img width="1195" alt="Screen Shot 2020-11-04 at 2 50 04 PM" src="https://user-images.githubusercontent.com/28145373/98161005-0c54ed80-1ead-11eb-8099-d72a588cfb44.png">

## Expected result:
GH favicon to be displayed

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.17.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes, 1.16.x
- Can you reproduce this issue with the beta channel? yes, 1.17.x
- Can you reproduce this issue with the nightly channel? yes, 1.18.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
![image](https://github.com/brave/brave-browser/assets/11497541/589c0a31-d1ac-489d-b21e-81993bdd1683)



Brave | 1.51.118 Chromium: 113.0.5672.126 (Official Build) (x86_64)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
