### ISSUE TITLE
Bookmarks not removed when its moved into folder that is removed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12530]
## Description 

Bookmarks not removed when its moved into folder that is removed

## Steps to Reproduce

   1. Create a sync chain on iOS device A
   2. Join desktop device B to the sync chain
   3. Add a folder `Test` on device A
   4. Add a bookmark on device A under root folder (Mobile bookmark)
   5. Wait for device B to sync and make sure folder structure from Mobile is on Desktop under mobile bookmarks
   6. Move bookmark from step 4 inside the test folder on device A
   7. Simultaneously delete the test folder on device B
   8. Bookmark and folder is removed on device A
   9. Bookmark from step 4 which is sync'd on device B is retained 

## Actual result:

Confused either the bookmark from desktop should be removed or sync'd back to iOS device

## Expected result:
No dilema

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Device A: 

iPhone 7+ with iOS 14.1 running 1.21(20.11.02.20)

Device B

Brave | 1.17.58 Chromium: 86.0.4240.183 (Official Build) beta (64-bit)
-- | --
Revision | `0b568b034b8f7994697cb341eeca5979b84151cc-refs/branch-heads/4240@{#1374}`
OS | Linux

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Found while verifying https://github.com/brave/brave-ios/issues/2996

**Comment by Brandon-T** [comment]
Duplicate of: https://github.com/brave/brave-browser/issues/12430
