### ISSUE TITLE
[Desktop] no hover text for Tip button on Twitter

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12536]
## Description 

When you hover over the in-line tip button on Twitter there's no hover text (ex. "Send a tip" or similar). This hover text does appear for GitHub in-line tip buttons.

## Steps to Reproduce

   1. Have Rewards enabled
   2. Navigate to a twitter page (ex. twitter.com/emerick)
   3. Look for Tip button (note, if you don't see any text saying "Tip", you've encountered https://github.com/brave/brave-browser/issues/12264 and need to restart your browser)
   4. Hover over Tip button/text

## Actual result:

"Tip" changes to orange, but no hover text:
<img width="633" alt="no twitter tip hovertext" src="https://user-images.githubusercontent.com/28145373/98254311-22fd5200-1f4a-11eb-9a09-07d8de7160ed.png">

## Expected result:
Something similar to GH:
<img width="190" alt="GH issue and PR example" src="https://user-images.githubusercontent.com/28145373/98254330-27c20600-1f4a-11eb-9e6c-cd40a8d40437.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.62 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
-- | --
Revision | 37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes, 1.16.x
- Can you reproduce this issue with the beta channel? yes, 1.17.x
- Can you reproduce this issue with the nightly channel? yes, 1.18.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @emerick @NejcZdovc

**Comment by emerick** [comment]
I believe we were relying on Twitter's standard CSS and definitions for this, but they removed all of the hover text on their buttons from what I can tell. Not sure if we should also follow suit, especially given that the button already says "Tip".

**Comment by Miyayes** [comment]
@mkarolin Will just remove tooltips since there are issues on some sites where tooltips can't appear.
