### ISSUE TITLE
Command line to disable PDF extension doesn't work

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1253]
## Description 

Command line to disable PDF extension doesn't work

## Steps to Reproduce

   1. Launch a new profile from terminal by passing the command line argument to disable PDFJS `brave-browser --disable_pdfjs_extension`
   2. Open More tools->Extensions, PDFJS extension isn't listed but auto installs 
   3. Visit http://orimi.com/pdf-test.pdf, PDF file loads correctly even though command line mentions to disable PDFJS

## Actual result:

https://www.youtube.com/watch?v=md7XwN38a6Y

## Expected result:
Should disable PDFJS when launched with command line parameter

## Reproduces how often: 

100% on Linux and Windows

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux/Windows

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Found while verifying #335 
@brave/legacy_qa to verify on macOS

**Comment by bbondy** [comment]
you had a fresh profile when you tested this? I.e. the command line parameter only affects if it is not installed already and not if you previously had it installed.

**Comment by srirambv** [comment]
Yes on a clean profile. Issue recorded here https://www.youtube.com/watch?v=md7XwN38a6Y

**Comment by bbondy** [comment]
Moving to 1.x backlog, it's not a big deal. The flag is only for development anyway.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified PDF doesn't appear as an extension instead lists as a component under `brave://components`
