### ISSUE TITLE
[Desktop] hover text is slightly misaligned on starred repos page of GitHub

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12538]
## Description 

When you hover over the Tip button/text on the starred repos page of a user's GitHub profile, the hover text alignment is slightly off.

## Steps to Reproduce

   1. Have Rewards enabled, be logged in to GitHub
   2. Navigate to a user's starred repos page (ex. https://github.com/emerick?tab=stars)
   3. Look for Tip button (note, if you don't see any text saying "Tip", you've encountered https://github.com/brave/brave-browser/issues/12264 and need to restart your browser)
   4. Hover over Tip button/text 

## Actual result:

the ^ part of the hover text is pointing to empty space
<img width="889" alt="GH Tip hovertext" src="https://user-images.githubusercontent.com/28145373/98255960-ffd3a200-1f4b-11eb-849a-5e97d6532a99.png">

## Expected result:
aligned better like on issues/PR page:
<img width="190" alt="GH issue and PR example" src="https://user-images.githubusercontent.com/28145373/98255980-06fab000-1f4c-11eb-9877-df7c2c189a2b.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.62 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
-- | --
Revision | 37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 1.16.x
- Can you reproduce this issue with the beta channel? yes 1.17.x
- Can you reproduce this issue with the nightly channel? yes 1.18.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @NejcZdovc @emerick

**Comment by Miyayes** [comment]
Max will be removing these tooltips across the board for inline tip buttons.
