### ISSUE TITLE
Change text for RE onboarding

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#12532]
Change `I'm ready for Earn & Give` to `Start using Brave Rewards`

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the test plan https://github.com/brave/brave-core/pull/7071 and description from the issue https://github.com/brave/brave-browser/issues/12532#issue-736833767
- Verified the welcome page onboarding from various places and ensured text is shown as expected "Start using Brave Rewards"

**_Clean profile_**
**BR panel:**
![image](https://user-images.githubusercontent.com/38657976/100064412-83e8bd80-2e58-11eb-8dbf-1a4d483d3956.png)

**NTP:**
![image](https://user-images.githubusercontent.com/38657976/100064472-92cf7000-2e58-11eb-8254-069c70dbdc21.png)

**Reset rewards->Reload rewards settings page**
![image](https://user-images.githubusercontent.com/38657976/100064623-c90cef80-2e58-11eb-9e7b-79edd0cb42b7.png)

**Clean profile->Click on `Brave Rewards` from the hamburger menu**
![image](https://user-images.githubusercontent.com/38657976/100064772-f194e980-2e58-11eb-8433-4254195ceb39.png)

**_Upgraded profile_**
- Enable rewards in 1.17.x and upgrade profile to 1.18.x and ensured welcome page onboarding isn't shown in Panel, Rewards settings and NTP's.
- Clean profile 1.17.x and upgrade profile to 1.18.x and ensured welcome page onboarding is shown in Panel, Rewards settings and NTP's.
