### ISSUE TITLE
Brave nightly ////   I can't turn off (brave rewards) icon in address bar. please help! me!!!

### ISSUE THREAD

**Issue by tee4341** [brave/brave-browser#12533]
Brave nightly ////   I can't turn off (brave rewards) icon in address bar. please help! me!!!
I try anything !!! please helap me!!!

https://www.img.in.th/image/sIOOAl

!!!! option. is hide not use anything!!

https://www.img.in.th/images/b5c94f2845b6715a399aa437c9738517.jpg

**Comment by NejcZdovc** [comment]
cc @deeppandya

**Comment by deeppandya** [comment]
@NejcZdovc is this on nightly ?

**Comment by tee4341** [comment]
yes...!!!

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `Bravearm 1.20.26`
- Verified the test plan from https://github.com/brave/brave-core/pull/7292#issuecomment-737600145

<details>
<summary>Confirmed onboarding overlay/modal on panel</summary>

![Screenshot_2020-12-14-21-14-41](https://user-images.githubusercontent.com/38657976/102105666-b1bc9300-3e55-11eb-8d93-4a730fade514.png)
![Screenshot_2020-12-14-21-14-46](https://user-images.githubusercontent.com/38657976/102105677-b3865680-3e55-11eb-9ec3-f98519b7770b.png)
![Screenshot_2020-12-14-21-14-52](https://user-images.githubusercontent.com/38657976/102105683-b4b78380-3e55-11eb-99d7-265519b11942.png)
![Screenshot_2020-12-14-21-14-56](https://user-images.githubusercontent.com/38657976/102105685-b5e8b080-3e55-11eb-82ab-36633addef69.png)
![Screenshot_2020-12-14-21-14-58](https://user-images.githubusercontent.com/38657976/102105688-b6814700-3e55-11eb-99bc-f296f414ba63.png)
![Screenshot_2020-12-14-21-15-03](https://user-images.githubusercontent.com/38657976/102105692-b719dd80-3e55-11eb-9b7e-5e09d8623746.png)
![Screenshot_2020-12-14-21-15-08](https://user-images.githubusercontent.com/38657976/102105694-b719dd80-3e55-11eb-8373-01fd84bc901c.png)
![Screenshot_2020-12-14-21-15-13](https://user-images.githubusercontent.com/38657976/102105699-b7b27400-3e55-11eb-9755-54f5a03115a2.png)
![Screenshot_2020-12-14-21-15-19](https://user-images.githubusercontent.com/38657976/102105702-b84b0a80-3e55-11eb-8311-f5f595fea418.png)


</details>
