### ISSUE TITLE
[Desktop] some GitHub URLs missing from exclusion list

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12544]
## Description 

While testing https://github.com/brave/brave-browser/issues/11463 I found that some GH URLs are missing from the exclusion list (found here: https://github.com/brave/brave-site-specific-scripts/blob/master/scripts/brave_rewards/publisher/github/utils.ts#L57-L76)

If you visit one of these pages and open the panel, you see the summary view, not the publisher view. These excluded pages should show github.com as the publisher.

## Steps to Reproduce

   1. Have rewards enabled
   2. Navigate to a page like:
GitHub.com/features/code-review
github.com/security
github.com/collections
   3. Open panel

## Actual result:

<img width="1195" alt="missing - features" src="https://user-images.githubusercontent.com/28145373/98275249-754a6d00-1f62-11eb-9fe0-1edbb3d197a4.png">
<img width="1195" alt="missing-security" src="https://user-images.githubusercontent.com/28145373/98275255-75e30380-1f62-11eb-8790-c272c1b851bf.png">
<img width="1192" alt="missing-collections" src="https://user-images.githubusercontent.com/28145373/98275263-77143080-1f62-11eb-82dc-1100ac8af04e.png">

## Expected result:
Panel should show github.com: 
<img width="1194" alt="login" src="https://user-images.githubusercontent.com/28145373/98275297-7f6c6b80-1f62-11eb-8099-7c590c7c570c.png">

as it does for sites on this list:
<img width="538" alt="Screen Shot 2020-11-05 at 12 29 21 PM" src="https://user-images.githubusercontent.com/28145373/98275368-8d21f100-1f62-11eb-8708-d5f81d453009.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.62 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
-- | --
Revision | 37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a 1.16.x doesn't have the exclusion list from greaselion
- Can you reproduce this issue with the beta channel? yes 1.17.x
- Can you reproduce this issue with the nightly channel? yes 1.18.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @NejcZdovc @emerick

**Comment by Miyayes** [comment]
P5 since Github is currently disabled for Creators in any case.

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 12.5.1 (Build 21G83)
```

Verified STR and paths listed in https://github.com/brave/brave-browser/issues/12544#issue-737128519.
Verified panel showed as expected for listed paths:

github.com/features/code-review | github.com/security | github.com/collections
----- | ----- | -----
<img width="973" alt="1" src="https://user-images.githubusercontent.com/28145373/188165856-65d18a74-7801-46f4-8fbb-69b57a9d0674.png"> | <img width="959" alt="2" src="https://user-images.githubusercontent.com/28145373/188165857-a014319b-d432-4013-8e30-f2fcb70b0d19.png"> | <img width="949" alt="3" src="https://user-images.githubusercontent.com/28145373/188165858-6e6807e7-807c-4d78-8b52-374f6fdef5ab.png">

Also spot checked list of paths from https://github.com/brave/brave-site-specific-scripts/blob/master/scripts/brave_rewards/publisher/github/utils.ts#L40-L60 and confirmed panel was expected for those as well:

github.com/about | github.com/marketplace | github.com/team
----- | ----- | -----
<img width="958" alt="4" src="https://user-images.githubusercontent.com/28145373/188166144-e36d7438-8ada-4a29-bc7d-828029628ce4.png"> | <img width="958" alt="5" src="https://user-images.githubusercontent.com/28145373/188166145-3b3dcee6-6934-421b-aa92-d24b5ab82495.png"> | <img width="972" alt="6" src="https://user-images.githubusercontent.com/28145373/188166147-6569dc8b-5157-4d83-942f-fcce1f1b99d3.png">
