### ISSUE TITLE
Always block WebRTC in Tor

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1254]
## Steps to Reproduce

   1. Open https://diafygi.github.io/webrtc-ips/ in Tor Window

## Actual result:

IPs are leaked

## Expected result:
Always block webrtc in Tor, even if Brave shields are off. 
Similar to browser laptop.

## Reproduces how often: 

always

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

### Reproducible on current release:

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

cc @darkdh @riastradh-brave

**Comment by bbondy** [comment]
Moving to 1.x

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

* Verified with test plan from https://github.com/brave/brave-core/pull/545 (manual steps)
* Found https://github.com/brave/brave-browser/issues/1453 while testing
