### ISSUE TITLE
Deep-link to add widget promo tooltip

### ISSUE THREAD

**Issue by cacevedo222** [brave/brave-browser#12553]
## Description
Deep-link adding a widget from somewhere. 

## Designs
Two possible entry points brought up by sales - we should allow deep-linking to the "Add [widget]" promo tooltip from an ad notification or clicking the sponsored image logo. The promo tooltip allows the user to 1-click add the promoted widget if they still have empty slots in their widget stack. If they do not have any slots, the promo tooltip opens the widget gallery for them to hide another widget before adding the promoted one.

![Group 32](https://user-images.githubusercontent.com/2388823/99445126-03fbaa00-28d2-11eb-9165-faa0ab08cb94.png)

## Assets
Figma: https://www.figma.com/file/nhYNVIkVLB6qhA0nEQfzFk/?node-id=0%3A1

**Comment by bsclifton** [comment]
@cacevedo222 do you have more information about this? I'm guessing you'd like to be able to do something like:
brave://newtab/#widget-gallery (or similar)

What would the use-case be for this?

**Comment by cacevedo222** [comment]
@bsclifton We've had requests from Crypto.com to be able to run both push notifications and Sponsored Images advertising the widget. I have already requested that we be able to link to the new tab page, but as we get the widget gallery going, it would be helpful to also highlight widgets in the gallery as we sell them. When a widget is replaced on the new tab page, we can use this to highlight widgets purchased by clients.

**Comment by bsclifton** [comment]
Talked with @cacevedo222 - use-case is for deep linking a widget (from somewhere else) 👍

**Comment by karenkliu** [comment]
Designs added!

**Comment by lukemulks** [comment]
There are some additional use cases for this that have been discussed over the past 8 months, aside from the Widget use case. 

- Deeplink from Brave Ads to Crypto Wallets
- Deeplink from Brave Ads to Firewall+VPN 
- Deeplink from SI to brave://rewards opt-in 
- Conditional deeplink from brave.com pages (examples: firewall+vpn or Brave Together) to feature in Brave, for users that are already using Brave (send users to download Brave, if not using Brave)

Deeplink to Crypto Wallets from Brave Ads: 
- Increase retention
- Increase BAT utility (web3 BAT) 
- Provide easier onramp for web3 partners (gaming, decentralized exchanges, defi management, NFTs) from ads intended to generate demand. 

Deeplink to ARR Products from Brave Ads or Brave.com LPs
- Increase ARR revenue 
- Increase retention (Brave Together, for example, has +52M avg session durations from active users) 

Deeplink from SI to brave://rewards opt-in flow: 
- Increase revenue (Brave Ads users) 
- Increase retention (as additional Rewards features and utility options become available) 

LMK if this needs a separate issue that covers the above, but the ability to deeplink has been in high demand from Marketing and BD in addition to the Sales/widget need (which also has rev potential), and would love if we could get this attached to a release version so we can begin marketing with them and increasing our BAT growth potential, revenue and opt-in rates as a part of several initiatives that are currently underway, if possible. cc: @rebron @bsclifton

**Comment by bsclifton** [comment]
Closing as `wontfix`
