### ISSUE TITLE
Closing extra first tab in Tor Window before page loads in second tab causes Tor Window to close or crash

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#12552]
## Description 

When click a link, if you right click > open link in Tor, it opens a Tor window with 1 existing tab, and then the link starts opening in a 2nd tab. However, if you close the 1st tab before the page in the 2nd tab is loaded, the entire Tor Window closes unexpectedly. (Uncertain if this is a close or a crash.)

This pre-existing "first tab" has been described as a "spurious first tab" in other issues (see https://github.com/brave/brave-browser/issues/4299 and https://github.com/brave/brave-browser/issues/11611).

## Steps to Reproduce

   1. Right click on a link 
   2. Click open link in Tor Window
   3. Immediately close the existing first tab in the Tor Window (before the second tab loads the webpage for the original link)

## Version info: 

v1.16.68, MacOS 

## Community Reports

https://www.reddit.com/r/brave_browser/comments/jo2lwo/funny_tor_bug/

**Comment by bsclifton** [comment]
cc: @darkdh

**Comment by rebron** [comment]
@Miyayes On these types of reports, we need as much crash data as you can provide. So we need users to send their crash reports and post the crash id's in here so we can take a look.

**Comment by iefremov** [comment]
@Miyayes do normal (non-Tor) browser windows continue working? If is only Tor window that disappears, this is not a crash. Also, do you have anything on `chrome://crashes`?

**Comment by rebron** [comment]
Closing. Doesn't look like there's any more movement or more info on this issue. It looks like closing window behavior (and waiting for a Tor tab page to load) versus an actual crash.
