### ISSUE TITLE
Site shields settings are retained across Guest window sessions

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1255]
## Description 

While testing #376 , found site shields settings are retained across Guest window sessions

## Steps to Reproduce

   1. Launch a clean profile 
   2. Open a guest window and visit https://brianbondy.com/ and disable shields
   3. Close guest window and launch another guest window
   4. Visit https://brianbondy.com/ in the second guest window, site shields settings are retained but site still loads normally

## Actual result:

https://youtu.be/7p3_Fgefkuw

## Expected result:
Site shields settings should not be persistent across guest window sessions

## Reproduces how often: 

100%

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux/Windows

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Considering Guest windows to be private mode, it should not retain site shields settings across sessions
cc: @bridiver @darkdh

**Comment by tomlowenthal** [comment]
Looks fixed to me.

**Comment by kjozwiak** [comment]
@srirambv mind double checking to see if this has been fixed for you?
