### ISSUE TITLE
Impove testing of ephemeral storage

### ISSUE THREAD

**Issue by mrobinson** [brave/brave-browser#12550]
## Description 
In https://github.com/brave/brave-core/pull/6560#discussion_r513521838 @iefremov suggested some ideas for improved testing of ephemeral storage. This bug tracks adding those tests.

**Comment by mrobinson** [comment]
I'm closing this manually due to a typo in the original PR, which means auto-resolution did not work properly.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/7075

Thanks for adding appropriate tags / milestone, @mrobinson 😄👍
