### ISSUE TITLE
Brave Rewards info links

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1256]
## Description 
There are no links to Terms of Service, FAQ, or Uphold prior to or after enabling Brave Rewards. 

Prior to enabling Brave Payments in b-l, a user could easily access the Terms of Service, FAQ, and Uphold links. Additionally, after enabling Brave Payments these links were still accessible from the Payments Page. Brave Rewards does not currently have these links. We should link to the corresponding items so users can review the info prior to deciding to enable Brave Rewards as well as have them easily accessible after BR has been enabled.

## Steps to Reproduce
Using b-l (screenshots are from 0.24.0):
Launch Brave and Navigate to about:preferences#payments.
![screen shot 2018-09-24 at 10 25 08 am](https://user-images.githubusercontent.com/28145373/45961094-b930c100-bfeb-11e8-87ed-883d96fe0fcf.png)
1 and 4 open a new tab for https://brave.com/Payments_FAQ.html
2 opens a new tab for https://uphold.com/
3 opens a new tab for https://basicattentiontoken.org/contributor-terms-of-service/

![screen shot 2018-09-24 at 10 26 38 am](https://user-images.githubusercontent.com/28145373/45961344-42e08e80-bfec-11e8-8ddf-8bf660873ad2.png)
5 opens a new tab for https://brave.com/Payments_FAQ.html
6 opens a new tab for https://basicattentiontoken.org/contributor-terms-of-service/

![screen shot 2018-09-24 at 10 28 34 am](https://user-images.githubusercontent.com/28145373/45961375-5986e580-bfec-11e8-9136-4924f23f74ed.png)
7 opens a new tab for https://uphold.com/en/brave

## Actual result:
Brave Payments contains links to Terms of Service, FAQ, and Uphold

## Expected result:
Brave Rewards should contain links to Terms of Service, FAQ, and Uphold

## Reproduces how often: 
easily

## Brave version (chrome://version info)
all BR enabled versions

### Reproducible on current release:
no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Uphold and ToS links were specifically added to Brave Payments:
https://github.com/brave/browser-laptop/issues/11420
https://github.com/brave/browser-laptop/issues/11942
https://github.com/brave/browser-laptop/issues/11242

**Comment by LaurenWags** [comment]
after talking about this with @NejcZdovc last week, @davidtemkin could you review and decide if we want to implement this from a product perspective? Personally I think it's a good idea to give the user the necessary info prior to enabling BR (whether they read it or not). And then to keep the info close at hand after enabling the feature.

**Comment by davidtemkin** [comment]
@jenn-rhim I believe that all of the elements that @LaurenWags called out need to be added to Brave Rewards. Can you take a look and make the necessary additions? 

cc: @NejcZdovc @mandar-brave @bradleyrichter

**Comment by kjozwiak** [comment]
A good candidate for the `https://uphold.com/en/brave` link could be the bolded `Uphold` under the wallet summary. Example:

![screen shot 2018-10-03 at 5 55 37 pm](https://user-images.githubusercontent.com/2602313/46442797-e3dfef80-c738-11e8-8f39-5bef6d9d22ef.png)

**Comment by Miyayes** [comment]
_Terms of Service_ should be viewed as much higher priority than the other informational elements.

**Comment by NejcZdovc** [comment]
closing as this is not valid anymore
