### ISSUE TITLE
About the browser's bookmark bar

### ISSUE THREAD

**Issue by Passwww** [brave/brave-browser#12565]
Can the browser bookmark bar display multiple columns when there are too many bookmarks? This is a very practical and intuitive feature.

As shown in the image below，image from the internet
![e1a53e5718f7f021da64425bd3836f53_720w](https://user-images.githubusercontent.com/71248115/98431572-8aa1d180-20f1-11eb-84bc-d8c79416dd7d.jpg)

![7e826ba3d24c66d23d075da8b4f48288_720w](https://user-images.githubusercontent.com/71248115/98431577-9a211a80-20f1-11eb-8dff-7fd83c7ef37d.jpg)

**Comment by rebron** [comment]
Closing. Hi @Passwww can you use the issue template and for a feature request like this and possibly start at community.brave.com to help define your idea. When an idea or feature suggestion like this is filed we aren't able to act on it as it's too vague.
