### ISSUE TITLE
Offer a way to disable extensions toolbar menu

### ISSUE THREAD

**Issue by MacAppSuggestions** [brave/brave-browser#12579]
## Edited issue description
When user has lots of extensions (ex: more than 20) and resolution is high, the extensions toolbar menu is hard to navigate (lots of scrolling required - see below comments / pictures for more information)

## Original issue description
see https://community.brave.com/t/bring-back-brave-flags-extensions-toolbar-menu/177045 about chrome://flags/#extensions-toolbar-menu problem

**Comment by bsclifton** [comment]
@MacAppSuggestions there is a lot of commentary in https://bugs.chromium.org/p/chromium/issues/detail?id=1124878 and it's not entirely clear what you are asking for. Maybe you can help me understand so that I can characterize the issue better

Are you asking for a way to disable the extensions menu that shows next to hamburger button? So that the extensions always show in the toolbar next to each other? Sounds like complaint is that you have too many extensions to scroll through, you'd rather just click the extension button icon in the toolbar instead

The toggle you mentioned was removed from Chromium - so we would need to do new work to add this back in (at a minimum, find where it was removed and add that Chromium code back in via patches that we would need to maintain).

**Comment by MacAppSuggestions** [comment]
Hello thanks for answering. 
Here example of Edge Dev
![image](https://user-images.githubusercontent.com/72309421/98526589-39711980-227a-11eb-840b-480f12848fa2.png)
no chrome://flags/#extensions-toolbar-menu active but they still offer
![image](https://user-images.githubusercontent.com/72309421/98526669-51e13400-227a-11eb-8e9c-ed82469869a9.png)
now i already suggested to increase the 6xY to a 10-12xY like the old chrome or brave to Edge Devs, but i still prefer to have 6xY compared to a 1x100+ like new chrome/brave
![image](https://user-images.githubusercontent.com/72309421/98526863-95d43900-227a-11eb-89ef-12acd2eaf22d.png)
here for example on new chrome dev side by side version (which doesn't support chrome://flags/#extensions-toolbar-menu at all).

So in other points is not a chrome://flags/#extensions-toolbar-menu problem, but a box of extension problem. if you can still read the extension box is much better.

Here some reason why i don't like new extension bar:
https://bugs.chromium.org/p/chromium/issues/detail?id=1145664&hotlist_id=10052&sort=%20rank%20-ID%20milestone%20pri%20nextaction
https://k00.fr/chrome you can find a small video showing some point that doesn't work.
Now i use chrome, chrome canary and all brave version in chrome://flags/#extensions-toolbar-menu version and chrome dev/beta in not chrome://flags/#extensions-toolbar-menu. all the time i use these 2 browser i just a level of stress 10/10 due to the problem.

the problem is getting worse if you use the display 
![image](https://user-images.githubusercontent.com/72309421/98527394-43474c80-227b-11eb-8506-c263c5b5670a.png)
like i do for all my 10+ macs (due to my diopter of 10+, so to avoid getting worse, plus i still prefer to have big things even with a diopter of 0), you resize the windows to 
![image](https://user-images.githubusercontent.com/72309421/98527696-9faa6c00-227b-11eb-8d78-4f89e32c4358.png)

 or even the fact that i use 
![image](https://user-images.githubusercontent.com/72309421/98527590-81447080-227b-11eb-9861-173caf6f2a9a.png) so i can use 10+ mac apps around the browser (like bar/docks etc.)

Now the problem is influenced by such factors, but is available even if you use max size resolution, etc.

Here just some screenshot examples:
![image](https://user-images.githubusercontent.com/72309421/98528110-25c6b280-227c-11eb-9a9a-cbbab0ece01c.png)
but then 
![image](https://user-images.githubusercontent.com/72309421/98528149-34ad6500-227c-11eb-8ec8-7ba33833a40b.png)
in small size and still no way to access all other extensions (now excluding shortcuts)

This is the main reason why now i suggest chromium to implement other bars, like the bottom bar 
https://bugs.chromium.org/p/chromium/issues/detail?id=1146846
so that they can create buttons like merge windows, reload left, right, all, etc. so that i don't need to use extension anymore for such task. otherwise i always need to scroll 100km to find such extension, especially now that they separate it to
![image](https://user-images.githubusercontent.com/72309421/98528447-979efc00-227c-11eb-9985-7c67449fc629.png)
![image](https://user-images.githubusercontent.com/72309421/98528465-9e2d7380-227c-11eb-8df6-2b6944dc87fa.png)
![image](https://user-images.githubusercontent.com/72309421/98528481-a4bbeb00-227c-11eb-99e7-27be06752ebb.png)
which is a really pain

i suggested 
https://bugs.chromium.org/p/chromium/issues/detail?id=1130323
https://bugs.chromium.org/p/chromium/issues/detail?id=1130322
but they refused it

this 
![image](https://user-images.githubusercontent.com/72309421/98528748-067c5500-227d-11eb-9746-d208bd6016da.png)
is annoying too.


like i told chrome to manage extension via 
![image](https://user-images.githubusercontent.com/72309421/98528539-bbfad880-227c-11eb-9b84-617d3c414316.png) (like i did in the last years) is much much better, because the box is still active.

if an user doen't want to see the extension in the toolbar, he simply need to 
![image](https://user-images.githubusercontent.com/72309421/98528939-46433c80-227d-11eb-8665-5ed142440a68.png)

move search bar to the right, 
![image](https://user-images.githubusercontent.com/72309421/98528959-522efe80-227d-11eb-877d-bc97cd425c88.png)
![image](https://user-images.githubusercontent.com/72309421/98528972-565b1c00-227d-11eb-9e1d-8740980c30ed.png)
and add it 
![image](https://user-images.githubusercontent.com/72309421/98528991-5ce99380-227d-11eb-94d0-b0fee5770d51.png)
![image](https://user-images.githubusercontent.com/72309421/98529007-6246de00-227d-11eb-9596-7060af14462e.png)

i know that in the extension box there are extension i never click (like new tab to the right) but this can be fixed with right click hide from extension box, and not by adding a 

![image](https://user-images.githubusercontent.com/72309421/98529114-8c000500-227d-11eb-8b97-b2a730c6f1f6.png)

1x400 extension list.

now  i writing you that from chrome dev with 75 extension. i already see problem just by search 75 extension. if i really use such new function with brave / chrome and 200-400 extension like different my profiles own, it would be a nightmare. this is the reason why i use old chrome://flags/#extensions-toolbar-menu compatible version. 

if you have 20 extension, this problem is not fully visible because you can keep 21 extension in the toolbar (with my setting) before the problem starts. if you add 22, the first extension is already hidden by default, and you cannot quick click other 54 extension (due to the fact that there is no extension box and no search bar).

installation of extension is problematic too, see koofr video for example. i generally use  50+ profiles, if the installation takes so much already for few extension (and doesn't keep the order of installation too), it would be a second nightmare to open accounts. same for conflict problem between old ui and new ui. so hours i spend to configure the old ui are just waste in new ui, because they revert to 0 the setting. 

we need to remember other problems related to the amount of extension (which i didn't see in brave until now) like
https://bugs.chromium.org/p/chromium/issues/detail?id=1142197

or similar problem with new ui too, when the search bar increase the size by hiding the extensions.

if you need more example, a private session or videos i can send you that.

if something is not clear, just write it. wish you a good day. ciao

**Comment by MacAppSuggestions** [comment]
here some other example. before 
![image](https://user-images.githubusercontent.com/72309421/98531355-835cfe00-2280-11eb-9699-9ed7b028ddb8.png)
and after adding a new extension
![image](https://user-images.githubusercontent.com/72309421/98531424-996abe80-2280-11eb-9eb5-291afdd1d36d.png)
![image](https://user-images.githubusercontent.com/72309421/98531441-9ec80900-2280-11eb-9a8f-c3bcbb76754f.png)
so the limit of 21 like i told you before, otherwise i see problems.

PS: i know they remove it from bar, they just show us that for 1 sec. But the problem is still there because you need manual scroll and find such extension by pin it to the bar. so the problem is back again and the first extension is hidden again.

**Comment by MacAppSuggestions** [comment]
![image](https://user-images.githubusercontent.com/72309421/98532220-b489fe00-2281-11eb-90c1-67fab0f35af1.png) i move

![image](https://user-images.githubusercontent.com/72309421/98532244-bc49a280-2281-11eb-9038-aa2fca8c2581.png)
and  drop, and the extension is lost
![image](https://user-images.githubusercontent.com/72309421/98532280-c8cdfb00-2281-11eb-817e-07e38908d6cf.png)
you can see it because they add 
![image](https://user-images.githubusercontent.com/72309421/98532438-fadf5d00-2281-11eb-82eb-b0728a438ad6.png)
and remove what i moved

**Comment by MacAppSuggestions** [comment]
another alternative to edge is vivaldi (but vivaldi has a lot problems with extensions too, which i already submitted to devs)
![image](https://user-images.githubusercontent.com/72309421/98532915-9a045480-2282-11eb-9e4a-05f5fdc6dbf5.png)

so here the example of the box. just consider the box size, by skipping all other (like no extension possibility on the extension toolbar at the same time, etc).

**Comment by MacAppSuggestions** [comment]
such option are much better compared to 
![image](https://user-images.githubusercontent.com/72309421/98533216-f9626480-2282-11eb-8837-6bc2e659aa8d.png)
in opera,
![image](https://user-images.githubusercontent.com/72309421/98533263-05e6bd00-2283-11eb-97e5-72f38c0ad755.png)
in 360chrome
![image](https://user-images.githubusercontent.com/72309421/98533404-3b8ba600-2283-11eb-904f-d2b1deecca18.png)

in qq
etc.

i don't like such option, but are still better to new ui of chrome, you can still quick access extensions (even in small window size). such option are ok if you own few extension. for 50+ extension is a box the only solutions. without considering the pain of reordering such extension in a 1x100 list compared to a 10x10 box.

**Comment by bsclifton** [comment]
@MacAppSuggestions I edited the original post and also update issue title to try to accurately capture the problem in a small amount of words. Can you please take a look and see if this matches your complaint?

**Comment by MacAppSuggestions** [comment]
Hello
**and resolution is high** ... don't understand why you wrote that. 
![image](https://user-images.githubusercontent.com/72309421/98666754-c3d67d80-234d-11eb-865d-0ae657b72f4e.png)
is my monitor vs
![image](https://user-images.githubusercontent.com/72309421/98666801-d18c0300-234d-11eb-9974-3a588df65c70.png)
on the top right. 

is more a problem related to small window size, low display size, low resolution for bigger texts; but such points are only an optional points that worse the problem, which is available at high resolution 16 inch display full size window too (you simply have maybe 40 extension on the toolbar instead of 20, but you cannot access quickly all 60+ extensions); is the main concept of how they implemented the new button bar that doesn't work, and create problem during drag drop, installation, sync, etc.

i understand the end goal of google with such button, but they implemented it completely wrongly.

**Comment by MacAppSuggestions** [comment]
about the title **Offer a way to disable extensions toolbar menu**
you can offer this, or as i wrote about Edge, keep it removed but then you read the box of extension 10-12x Y (in Edge/Vivaldi style). I don't know how Edge devs do it, but if you use Edge, all problems that i wrote here and on chromium are not available at all

**Comment by MacAppSuggestions** [comment]
@bsclifton Today i tested a perfect configured template account in the new UI with 20 extension extension in the toolbar, then i merged this with an old account configured with old UI, and the result:
an account where all setting are lost, 0 extensions are pinned.

So the problem is not only using old account to new UI, where you lost extension, but even merging new with old UI account, because this new UI is so stupid that doesn't keep new UI setting by just unpin all extension available in the old account.

![image](https://user-images.githubusercontent.com/72309421/99021727-95c98700-2561-11eb-985f-ffae02b9667c.png)
 
This what i got after merging both accounts.

**Comment by rebron** [comment]
Closing in favor of #12721 where discussion/dev can resume.
