### ISSUE TITLE
hover over settings icon shows MISSING: adsTooltip

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1257]
## Description 
Hover over the settings icon in either Brave Auto-Contribute or Direct Donations panels on chrome://rewards shows `MISSING: adsTooltip`.

## Steps to Reproduce

   1. Enable BR if not already enabled.
   2. Hover over settings icon for Brave Auto-Contribute or Direct Donations panels.

## Actual result:
![screen shot 2018-09-24 at 11 40 03 am](https://user-images.githubusercontent.com/28145373/45962637-54776580-bfef-11e8-860c-248dd8f6d462.png)

![screen shot 2018-09-24 at 11 40 15 am](https://user-images.githubusercontent.com/28145373/45962641-56d9bf80-bfef-11e8-91aa-6152e6440128.png)

## Expected result:
Actual hovertext, not 'Missing' message.

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X

### Reproducible on current release:
n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by ryanml** [comment]
This issue is waiting on this PR in brave-ui: https://github.com/brave/brave-ui/pull/154

`adsTooltipTitle` was not the correct locale string to begin with, as it is for the brave auto-contribute settings, not ads.

Once brave-ui/pull/154 is merged and the package is updated, a version bump and locale update in `brave-core` will resolve this.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X
