### ISSUE TITLE
Brave Today news feed on the New Tab Page

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#12574]
## Description 
Introduce Brave Today - a privacy-focused feed of articles with on-device local-only personalization.

Privacy features:
- Every user downloads the same feed.
- Personalization options are on-device only and not sent anywhere outside the local browser.
- Network MITM observers will not be able to see which content is being viewed since images are all the same size (padded) and transmitted over HTTPS.

### When the OS is set to any english language region, Brave Today is on by default
   1. OS set to US
   2. Fresh profile
   3. Open NTP
   4. Brave Today is visible
   5. Brave Today is _on_ in the Customize dialog on the NTP

![image](https://user-images.githubusercontent.com/741836/98456938-1427c280-2137-11eb-8b70-898defe113cd.png)

### When the OS is set to any **non-**english language region, Brave Today is **off** by default
   1. OS set to France
   2. Fresh profile
   3. Open NTP
   4. Brave Today is _not_ visible
   5. Brave Today is _off_ in the Customize dialog on the NTP, but can successfully be turned off

![image](https://user-images.githubusercontent.com/741836/98456941-299cec80-2137-11eb-8ffd-08429b9fbba9.png)

### Handles no internet connection
   1. Fresh profile + any English OS region
   2. Disconnect from network (wireless or wired)
   3. 

![image](https://user-images.githubusercontent.com/741836/98456932-096d2d80-2137-11eb-851c-6ed49d32cbaf.png)

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the test plan mentioned in the description
- Verified that Brave Today is ON when OS is set to the English language
![image](https://user-images.githubusercontent.com/38657976/101381035-41a19080-38dc-11eb-8986-b7bcef79d44f.png)

**Comment by GeetaSarvadnya** [comment]
@petemill - when Wifi/Internet is OFF, launch brave isn't showing message as `Brave Today is experiencing some issues. Try again` instead, it shows spinner.

![image](https://user-images.githubusercontent.com/38657976/101622205-c3a8cb00-3a3c-11eb-983d-0ec7c1962e94.png)

**Comment by petemill** [comment]
@GeetaSarvadnya Eventually the spinner should go away and the message shown. It may be some minutes. Is that your experience?

**Comment by GeetaSarvadnya** [comment]
@petemill The message isn't shown even after ~15  mins. Logged https://github.com/brave/brave-browser/issues/13109

**Comment by rudolphos** [comment]
Suggestion - option to add custom RSS feeds.

**Comment by bsclifton** [comment]
@rudolphos subscribe to https://github.com/brave/brave-browser/issues/13095 for updates regarding custom RSS feed 😄
