### ISSUE TITLE
Cards layout bug of More Cards in NTP Customize Dashboard

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#12573]
## Description 

Cards in More cards are not aligned.

## Steps to Reproduce

   1. Click More cards of NTP Customized Dashboard
   2. Make sure all cards are not hidden
   3. Hide Binance widget

## Actual result:

![image](https://user-images.githubusercontent.com/6786187/98445930-e144f500-215d-11eb-8773-a254fc8c364a.png)

## Expected result:
Result of current beta.(1.17)
![image](https://user-images.githubusercontent.com/6786187/98445951-05a0d180-215e-11eb-8c82-aac4671c9d62.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.18.39 Chromium: 87.0.4280.49 (Official Build) unknown (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel?  No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/brave-core/pull/6192/

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.18.63 Chromium: 87.0.4280.67 (Official Build) beta (64-bit)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | Linux

- Verified card layout doesn't change when widgets are added/removed
![linux-addcards](https://user-images.githubusercontent.com/17010094/100415553-54ae9800-3074-11eb-8c75-bca5271d70f5.gif)

---------
Verification passed on 

Brave | 1.18.63 Chromium: 87.0.4280.67 (Official Build) beta (64-bit)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | Windows 10 OS Version 2009 (Build 19042.630)

- Verified card layout doesn't change when widgets are added/removed
![win-addcards](https://user-images.githubusercontent.com/17010094/100415579-6728d180-3074-11eb-9f13-ac4923f328f5.gif)

---------
Verification passed on 

Brave | 1.18.63 Chromium: 87.0.4280.67 (Official Build) beta (x86_64)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified card layout doesn't change when widgets are added/removed
![mac-addcards](https://user-images.githubusercontent.com/17010094/100415627-87589080-3074-11eb-95e3-f110dcc3a2b3.gif)
