### ISSUE TITLE
www.advanscene.com.  site is not show all picture. ...!!!!!!

### ISSUE THREAD

**Issue by tee4341** [brave/brave-browser#12581]
https://www.advanscene.com/

site is not show all picture. ...!!!!!!
[(................)](`url`)

https://www.img.in.th/image/svPqtu
https://www.img.in.th/image/svQEJY
https://www.img.in.th/image/svQ4q9

but.!!!! on Microsoft edge. (android)
https://www.img.in.th/image/svQhS2
https://www.img.in.th/image/svQpar
https://www.img.in.th/image/svQt2M

...........

**Comment by tee4341** [comment]
ok.we fix it can download new ver tomorrow 10 nov 2020.  (admin)

**Comment by bsclifton** [comment]
Closed as this looks great for me on Android
