### ISSUE TITLE
BAT not loading

### ISSUE THREAD

**Issue by FatSandwich** [brave/brave-browser#12580]
On the home page of brave it shows me that I have 1.480 BAT, but when I click on the brave rewards button in the corner it shows 0.00 BAT and 0.00 USD. This issue does not let me contribute, send or withdraw BAT. Please help, thanks in advance!

**Comment by hollons** [comment]
@FatSandwich - thanks for reporting and sorry for the delay! Is this still an issue for you? If so, can you email me at Steven@brave.com the Brave version that you're currently using as well as your Wallet ID? Thanks in advance!
