### ISSUE TITLE
brave reward disappeared

### ISSUE THREAD

**Issue by optimum-dulopin** [brave/brave-browser#12593]
hi,
In brave://rewards/ page, I was seeing "estimated pending rewards  14 bat" and it was saying "Next payment date 6 november",  but on november 6th, pending rewards went to 0 and Next payment date to 6 december. But I didnt received anything in my uphold card.

also as you can see in my "Brave Rewards Wallet Activity", it says "No activities yet…" for all month. 

![Screenshot from 2020-11-09 13-55-12](https://user-images.githubusercontent.com/3425731/98543822-5239f900-2293-11eb-820a-d00cc07e058a.png)

So it seems I have never received any of my brave rewards from ads. What is the problem ?

**Comment by FatSandwich** [comment]
I have the same issue the dashboard shows 1.605 BAT but when I check my wallet its 0.00 BAT

**Comment by tmancey** [comment]
@FatSandwich @optimum-dulopin I work on the ads team here at Brave, could you please reach out to me at tmancey@brave.com with your wallet id which can be found at brave://rewards

**Comment by FatSandwich** [comment]
Thanks :)

**Comment by cone-7** [comment]
@tmancey I have the same problem, what should I do?

**Comment by tmancey** [comment]
@cone-7 Can you please let me know if you have edited or deleted any state files such as client.json? If not, would you consider a screen-share to help diagnose the issue?

**Comment by cone-7** [comment]
I haven't edited anything and this is what I see 

![image](https://user-images.githubusercontent.com/9827488/100382925-46f40680-2fd1-11eb-8bc6-a324b90ab342.png)

![image](https://user-images.githubusercontent.com/9827488/100383028-7b67c280-2fd1-11eb-983a-3978ca0b8f4b.png)

**Comment by optimum-dulopin** [comment]
@tmancey any news ? 
where are our Bats ?

**Comment by tmancey** [comment]
@optimum-dulopin have you reached out via email (tmancey@brave.com) and willing to screen-share to help diagnose the issue? Thanks

**Comment by FatSandwich** [comment]
Yeah

**Comment by tmancey** [comment]
@FatSandwich @optimum-dulopin If you could send an email again to tmancey@brave.com and please make sure you mention your github user name to help. I will then reply with meeting details. Thanks

**Comment by tmancey** [comment]
@optimum-dulopin Your emails are being rejected when sent from tmancey@brave.com, please send an email from another email address if that helps. Thank you

**Comment by optimum-dulopin** [comment]
@tmancey message sent

**Comment by tmancey** [comment]
Closing issue as we have fixed a couple bugs in this area. If the issue occurs again please reopen this ticket.

**Comment by rizkhal** [comment]
i have this issue

**Comment by tmancey** [comment]
> i have this issue

Can you please let us know the browser version and operating system. Also if you could send a screenshot of brave://rewards to terry@brave.com with an explanation of the issue I can then help. Thanks

**Comment by AllInNVDA** [comment]
I'm having the same issue. I'm using brave 1.33.106 on ubuntu.
![image](https://user-images.githubusercontent.com/7636434/148625084-36f9a9e0-1a53-4ede-98f0-525f4a8167d9.png)
