### ISSUE TITLE
Add epsilon greedy bandit classifier for Brave Ads matching

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#12595]

**Comment by kjozwiak** [comment]
Labeling this as `QA/Yes` as https://github.com/brave/brave-core/pull/7484 has STR/cases outlined. Also moved this into https://github.com/brave/brave-browser/milestone/161 as it was merged into `master`.

@moritzhaller please change label to `QA/No` if there's nothing that QA can do here 👍

**Comment by moritzhaller** [comment]
@kjozwiak labelled as QA/No since tested as part of https://github.com/brave/brave-core/pull/7533
