### ISSUE TITLE
Add ephemeral storage support for `document.cookie`

### ISSUE THREAD

**Issue by mrobinson** [brave/brave-browser#12591]
`document.cookie` should provide ephemeral storage support when the ephemeral storage flag is enabled and cookies would otherwise be blocked.

**Comment by LaurenWags** [comment]
@mrobinson I don't think "1.18.x - Release #2" is the correct milestone if this was just merged to master. I believe "1.20.x - Nightly" would be appropriate. PR doesn't have a milestone though. cc @bsclifton for assistance on determining correct milestone for issue and PR 👍

**Comment by mrobinson** [comment]
@LaurenWags Oh, thanks for the heads up. You are probably right. I've adjusted the milestone for now.

**Comment by LaurenWags** [comment]
thanks @mrobinson 😄
