### ISSUE TITLE
[Desktop] 5th background image (yellow) isn't showing up on tip banner

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12596]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/11393

Per figma design in above issue, there should be 5 randomly used background images. 4/5 are showing up but the 5th (yellow) is not.

## Steps to Reproduce

   1. Have Rewards enabled
   2. Open a bunch of sites w/o custom tip banners and open tip banner on each

## Actual result:

the various background colors are used randomly, but yellow doesn't show up

## Expected result:
yellow should be used occasionally

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.63 Chromium: 87.0.4280.49 (Official Build) unknown (x86_64)
-- | --
Revision | f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a 1.16.x
- Can you reproduce this issue with the beta channel? yes 1.17.x
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.55 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the STR from the issue
![image](https://user-images.githubusercontent.com/38657976/101886259-3fcc1b80-3bc1-11eb-97b2-2ccfa90c89be.png)
![image](https://user-images.githubusercontent.com/38657976/101886289-48bced00-3bc1-11eb-9f88-3f56f1cb1dcb.png)
![image](https://user-images.githubusercontent.com/38657976/101886325-52465500-3bc1-11eb-9b67-27b37c83176f.png)
![image](https://user-images.githubusercontent.com/38657976/101886364-5ffbda80-3bc1-11eb-94c9-eab343c59d4e.png)
![image](https://user-images.githubusercontent.com/38657976/101886430-786bf500-3bc1-11eb-9d79-cb7de8c94be8.png)
