### ISSUE TITLE
BAT Wallet 0.00

### ISSUE THREAD

**Issue by FatSandwich** [brave/brave-browser#12594]
On the home page of brave it shows me that I have 1.480 BAT, but when I click on the brave rewards button in the corner it shows 0.00 BAT and 0.00 USD. This issue does not let me contribute, send or withdraw BAT. Am I doing something wrong?Please help, thanks in advance!

**Comment by tmancey** [comment]
@FatSandwich I am closing this issue as it is a duplicate of https://github.com/brave/brave-browser/issues/12593 where I have sent you a message
