### ISSUE TITLE
you can have my damn cookie! should be a browser setting

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#12597]
## Description 

![Screen Shot 2020-11-09 at 9 33 49 AM](https://user-images.githubusercontent.com/5951041/98576089-e776c680-226e-11eb-9ca1-925550b87c26.png)

## Design

[placeholder]

## Actual result:

User needs to interact with GDPR Cookie Consent Banners. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:
 n/a

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issue: #4303

**Comment by fmarier** [comment]
I don't know whether Elon is a Brave user, but regardless, I think we should implement a "No you can't have my damn cookie!" setting rather than the setting he's asking for :)

**Comment by rebron** [comment]
@fmarier I agree. I believe there's an extension that already addresses Elon's request.

**Comment by MacAppSuggestions** [comment]
Like i suggested to Google, Vivaldi, Edge and other chromium based Devs after reading your post @rebron , the extension that you need to implemented per default is
https://chrome.google.com/webstore/detail/consent-o-matic/mdjildafknihdffpkfmmpnpoiajfjnjd, which i install on all my profiles. i agree with Elon 1000%,  all such messages are simply so annoying

**Comment by cjwijtmans** [comment]
The whole law is unnecesary, its the browser that controls the cookies and whatnot, not the server.

**Comment by NumDeP** [comment]
Not to come across as someone from the valley but yeah let's just pretend like I never suggested the same thing, totally, like last year. Both of those features, like, God! :) - [Accepting cookie notifications of the same site is time consuming and annoying](https://github.com/brave/brave-browser/issues/9338)

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
+1

**Comment by ryanbr** [comment]
Closing ticket, GDPR/Cookie messages can be hidden in Annoyances or Easylist cookies via `brave://adblock`

**Comment by NumDeP** [comment]
@ryanbr There are two 'Annoyances' in that list which one do you mean, 'Fanboy Annoyances List' or '`uBlock Annoyances List (used with Fanboy Annoyances List)`'?

Did you also mean this one '`Easylist-Cookie List - Filter Obtrusive Cookie Notices`'? You give the impression that one or the other can be selected.
