### ISSUE TITLE
[Desktop] Brave Today publishers should be easily disabled

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#12608]
Design requirement to be able to click on any card's publisher and have a menu popup to disable that publisher.

![image](https://user-images.githubusercontent.com/741836/98634913-e4b0bb80-22d8-11eb-9e5a-857294cfdff8.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from the description
Verified clicking on publisher button shown `Disable Content` Menu
![image](https://user-images.githubusercontent.com/34715963/101636950-568d3980-3a2c-11eb-8eb8-713c231debb9.png)

Verified clicking that popup menu entry closes the popup.
Verified pressing escape closes the popup
Verified clicking outside of the popup closes the popup
Verified the content from given publisher is disabled
Verified clicking the popup menu entry, after a brief moment, the "Load New Content" blue "pill" button appears at the top of the Viewport
![image](https://user-images.githubusercontent.com/34715963/101637062-84727e00-3a2c-11eb-81ab-bba819f038c1.png)
Verified clicking refreshes the feed with the publisher's content removed.

Logged https://github.com/brave/brave-browser/issues/13112
