### ISSUE TITLE
Brave Today should use production URLS

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#12601]
When Brave Today production infrastructure is ready, we should update the URLS that the browser downloads the feed from (and change the allow-list URLs for network audit).

This is marked as a release blocker because we cannot release on the Release branch without using production infrastructure.

In the unlikely event the production infrastructure is not ready by the time release 1.18.x is ready for Release branch, then we should remove Brave Today.

**Comment by kjozwiak** [comment]
Closed as both https://github.com/brave/brave-core/pull/7302 & https://github.com/brave/brave-core/pull/7301 have been merged.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified description from the issue
![image](https://user-images.githubusercontent.com/38657976/101324508-640dbc80-3890-11eb-8610-24b43801b84f.png)
