### ISSUE TITLE
About page doesn't use correct channel name and icon

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#12606]
`unknown` channel name is used and grayed icon is displayed.
![image](https://user-images.githubusercontent.com/6786187/98612409-73542580-2337-11eb-9aa5-3b457162128f.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.68 Chromium: 87.0.4280.49 (Official Build) (x86_64)
-- | --
Revision | f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified description.

<img width="1197" alt="About page" src="https://user-images.githubusercontent.com/28145373/98995288-1d31de80-24ff-11eb-86ed-8d4c8fa6fcee.png">

cc @kjozwiak to check on Catalina
