### ISSUE TITLE
[Desktop] Improve rewards onboarding display frequency

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#12612]
## Description

Currently, the rewards onboarding UX is not displayed again if the user has dismissed the CTA (by clicking "Maybe later" or by closing the onboarding modal). We may want to display onboarding again after the user has dismissed the CTA. For example:

- Should onboarding be displayed in the tip dialog after the user has dismissed the CTA in the rewards panel?
- Should onboarding be displayed in rewards panel if the user has dismissed the CTA on the rewards page?
- Should there be some kind of "cool-down" to prevent re-showing the onboarding within a certain amount of time?

One option might be to have a global "cool-down" time, such that if the user dismisses the onboarding UX it will not reappear for a certain amount of time, regardless of entry point. After that time has elapsed, the onboarding UX would be displayed in any of the entry points again.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.47 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/7135
