### ISSUE TITLE
unexpected load of Tor extension, even if not used an Tor-Based Incognito Tab

### ISSUE THREAD

**Issue by xstable** [brave/brave-browser#12613]
## Description 
In Private / Incognito Mode, there are loaded files from Browser-Extensions, which don't depend at the page you opened in the Incognito-Tab.
Thats bad behavior, especially if you want to do a performance-test for a page.. no other files should be loaded at all, as only the files from the page I've opened!

It would be ok, if this extension is only loaded, if you activate the TOR-Based Incognito Mode, but not on the general one!

## Steps to Reproduce
   1.  Open Settings ⇒ `New private Tab`
   2. Open https://easy-car-service.de (or any other Page)
   3. Open DEV-Tools (F12)
   4. Open Tab: Performance and reload the page to get Performance-Results
   5. Inspect the Activity at the very beginning of the Page... there you found something like `content_cosmetic.bundle.js`:
![image](https://user-images.githubusercontent.com/1778068/98702886-3d389500-237b-11eb-990c-45a10d61877a.png)

After a little reserach, I figured out, that this seems to be the "TOR-Extension":

![image](https://user-images.githubusercontent.com/1778068/98703285-9f919580-237b-11eb-8d74-b6c136cb8f12.png)

## Actual result:
Some Extensions (at least the TOR-Profile) are loaded in Icognito-Mode. 

## Expected result:
Not any single extension should be loaded in "Private Incognito"-Mode

## Reproduces how often: 
Intermittent issue

## Brave version (brave://version info)

Brave | 1.16.67 Chromium: 86.0.4240.111 (Offizieller Build) unknown (64-Bit)
-- | --
Überarbeitung | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
Betriebssystem | Linux
JavaScript | V8 8.6.395.17
Flash | 32.0.0.445 /usr/lib/PepperFlash/libpepflashplayer.so
User-Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Befehlszeile | /usr/lib/brave/brave --no-default-browser-check --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --ppapi-flash-version=32.0.0.445 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=MixedContentSiteSetting,WebUIDarkMode,PrefetchPrivacyChanges,OmniboxContextMenuShowFullUrls,DnsOverHttps,LegacyTLSEnforced,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,PassiveMixedContentWarning --disable-features=VideoPlaybackQuality,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,PrivacySettingsRedesign,SmsReceiver,TabHoverCards,SafeBrowsingEnhancedProtection,AutofillServerCommunication,PasswordCheck --flag-switches-begin --flag-switches-end
Ausführbarer Pfad | /usr/lib/brave/brave
Profilpfad | /home/suther/.config/BraveSoftware/Brave-Browser/Default

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
**NO**
- Does the issue resolve itself when disabling Brave Rewards?  
**NO** (still have not activated it)
- Is the issue reproducible on the latest version of Chrome? 
**NO**, there it work like expected, means no additional files are loaded!

**Comment by diracdeltas** [comment]
i don't think this is necessarily coming from Tor since IIRC Tor makes a copy of that folder from the normal profile. I assume content_cosmetic.bundle.js is something we use for adblocking in both regular and Tor windows? cc @pes10k

**Comment by pes10k** [comment]
Yep! Just to second what @diracdeltas said, that code handles cosmetic filtering in Brave.  Its not related to Tor.  You can find the pre-built / bundled version of the code here https://github.com/brave/brave-core/blob/master/components/brave_extension/extension/brave_extension/content_cosmetic.ts

**Comment by xstable** [comment]
Ok, but why are this ticket closed? @pes10k 
Anyway -  if TOR or not -  it shouldn't appear in the Incognito-Tab at least.
It falsified the results of profiling and it shouldn't be active in Incognito-Mode because it is against the general Idea, what incognito-mode is for?!
