### ISSUE TITLE
Replace "Add Card" tab with sub-tab "Edit Cards"

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12625]
This is a sub issue under: https://github.com/brave/brave-browser/issues/9616
Specification: https://docs.google.com/document/d/14lWBt0QmHDfA2G7h0hUPxZ8mVUd008IZPQJJfRryC9U/edit#

(Note, this does not implement the full specification with notifications, only the "Edit Card" addition.

## Test Plan
1. Open up the NTP from a fresh profile
2. Confirm that "Edit Cards" appears under the widget stack
3. Confirm that clicking "Edit Cards" brings up the NTP settings focused on the Cards section
4. Confirm that when all of the widgets are hidden, "Edit Cards" disappears
5. Confirm that once a widget is added back from zero, "Edit Cards" re-appears

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Windows 10 OS Version 2009 (Build 19042.685)

- Verified test plan from issue description
![win-editcards](https://user-images.githubusercontent.com/17010094/103609774-7f62fa80-4f16-11eb-8d7e-ee7046d32748.gif)
-------
Verification passed on 

Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Linux

- Verified test plan from issue description
![linux-editcards](https://user-images.githubusercontent.com/17010094/103610105-36f80c80-4f17-11eb-8ce8-74b30b8aa722.gif)

--------
Verification passed on 

Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (x86_64)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified test plan from issue description 
![macOS](https://user-images.githubusercontent.com/17010094/103609692-504c8900-4f16-11eb-830e-f6c2f5b1640b.gif)
