### ISSUE TITLE
Latest version of Brave released on 4th of Nov, 2020 crashes frequently

### ISSUE THREAD

**Issue by pongraczi** [brave/brave-browser#12627]
## Description 
Latest version of the browser crasher for lot of people, reported on google play, too.  
In my case, I sent reports via the automatic report collector.  
It makes brave a very annoying and useless application, it is not possible to use it, due to that, when I try to open some articles, it crashes and lost all the open tabs/sites.

## Steps to reproduce 

   1. Start the browser
   2. Visit some sites, open some tabs
   3. Just do your usual business with the browser
   4. It crashes.

## Actual result 
Crash.

## Expected result
Do not crash.

## Issue reproduces how often 
If I use it, less than 5 minutes it will crash, seems random, but happens really frequently.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Absolutely.
- Can you reproduce this issue with the current Play Store Beta version? No idea, I do not use it.
- Can you reproduce this issue with the current Play Store Nightly version? No idea, I do not use it.

## Device details
   - Install type (ARM, x86):Arm
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Xiaomi whatever
   
## Brave version
released on 4th of November, 2020

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  No idea. Default is up, that is the point.
- Does the issue resolve itself when disabling Brave Rewards?  No idea. I usually disable rewards after installing brave.
- Is the issue reproducible on the latest version of Chrome?   No idea. I will not install and use other browser, sorry.

### Additional information

On play store, several Hungarian people reported these crashes.  
Here (github) I did not find any sign of this crash, there is no open tickets which describe this kind of issue.

**Comment by chris122380** [comment]
Still randomly crashing on Brave 1.16.76. when opening external links with Brave as the default browser. It's difficult to pinpoint because one link from the same web page will work just fine and then later will cause the browser to crash. Links from the following apps I have seen this issue with:
Google app
Google News
Edison Mail
Feedly Classic
Nine - Email & Calendar

Also see Brave Community discussions 
https://community.brave.com/t/opened-link-from-an-external-app-closes-brave-after-short-time-of-load

and

https://community.brave.com/t/brave-constantly-crashes-when-opening-links-from-other-apps

**Comment by chris122380** [comment]
Same issue on Brave 1.17.70

**Comment by bsclifton** [comment]
cc: @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
Most likely related to that issue https://github.com/brave/brave-browser/issues/12745. The update is coming, should be available at the end of this week.

**Comment by chris122380** [comment]
> Most likely related to that issue #12745. The update is coming, should be available at the end of this week.

I have been testing this on all the Brave preview 1.17.x release builds and still an issue. I'm willing to test this once a fix is available.

**Comment by chris122380** [comment]
Is still happening with release preview of Brave 1.17.73

**Comment by chris122380** [comment]
Same issue happening with Brave release preview  1.17.74

**Comment by chris122380** [comment]
Still crashes on Release Preview 1.18.70

**Comment by chris122380** [comment]
Brave release preview 1.18.71 crashed opening one of Braves own webpages when being opened from the Google news feed (from launcher). Webpage it crashed opening - https://brave.com/brave-today/

**Comment by chris122380** [comment]
@SergeyZhukovsky It has been about a month and Brave1.16.76 to Brave 1.18.75 is still unacceptably crashing when opening links from apps on Android.

**Comment by SergeyZhukovsky** [comment]
@chris122380 do you have certain steps how to replicate the crash? the brave-today doesn't crash on my devices on any channels. Do you have something like:
1. I opened this;
2. I did that;
3. I got a crash.
Or it just crashes randomly?

**Comment by chris122380** [comment]
@SergeyZhukovsky it is random when trying to open a link from the Google news feed or from email. It appears to be more common if Brave hasn't been loaded or used in a while. It will load the page and crash. If you open Brave you will see that the page did load. It doesn't care what webpage and has even done it loading Brave blog from an email. I'm thinking maybe it was fixed in one of the 1.19 nighties but waiting to test it further in one of the releases of 1.19.x. 

I haven't had this issue with any other chromium based browsers.

**Comment by chris122380** [comment]
I decided to do I clean fresh install of Brave 1.18.77. The first web page I tried to open from the Google News feed (and the first web page at all) and the page loaded to the end and then crashed the browser. Open the Brave browser then shows the page that loaded.

**Comment by chris122380** [comment]
This issue looks like it might have finally been resolved with Brave 1.18.78. I am still doing some testing on this and will also check with the Brave community.

**Comment by chris122380** [comment]
When moving from custom tabs to opening in Brave causes this same issue. I have temporarily disabled custom tabs to see if that will resolve it for now.

**Comment by chris122380** [comment]
Even with custom tabs disabled it now goes back to crashing when opening a link in Feedly.

**Comment by SergeyZhukovsky** [comment]
@chris122380 could you replicate it consistently? Could you please post exact steps here? cc @srirambv as well for incites.

**Comment by chris122380** [comment]
@SergeyZhukovsky @srirambv it is consistently random but always will happen within about 5 to 10 minutes. Open the news article from the Google feed or from Feedly the web page will load and then the browser will crash as soon as the page is done loading. If you open Brave it will open with the page that crashed it. It appears to be more consistent with custom tabs off but it will happen with it on or off. This has consistently been an issue from Brave 1.16.76 to

**Comment by SergeyZhukovsky** [comment]
Do you have Brave set as a default browser?

**Comment by chris122380** [comment]
Yes

**Comment by chris122380** [comment]
@SergeyZhukovsky Brave	1.19.83 release preview crashed even quicker. As soon as I clicked a Google news feed article Brave opened and then crashed. I opened Brave to see if it even did anything and there was the article. If there is a way to pull crash logs please let me know how and I'd be more than happy to add them.

**Comment by SergeyZhukovsky** [comment]
@chris122380 I'm going to take a closer look on that next week.

**Comment by chris122380** [comment]
@SergeyZhukovsky I am here to no longer be having this issue after resetting my phone. I decided to reset my phone due to low storage and other issues. It's possible that this crash issue could have been related to storage, upgrading from Android 9 to Android 10, or I could have been using the wrong APK build for my device from GitHub. Thank you for all the troubleshooting help on this issue. I have encouraged others in the community who have been having this issue to give feedback on this GitHub article. I would say if there are no additional comments from the community or other Brave developers then this issue has been resolved.

**Comment by chris122380** [comment]
@SergeyZhukovsky never mind I spoke too soon. After about 24 hours the next day I get the app crashing just as it did before. It first started with opening an AMP page from the Google feed and then again when using the Brave search widget.

**Comment by chris122380** [comment]
Just received the update to Brave 1.19.86 and still doing the same thing when opening a news article from the Google feed -https://www.theverge.com/platform/amp/2021/1/19/22238334/brave-browser-ipfs-peer-to-peer-decentralized-transfer-protocol-http-nodes.

Opened the page and crashed Brave.

**Comment by SergeyZhukovsky** [comment]
Hi @chris122380, unfortunately we cannot replicate that. I had a chance to look deeply on that today, but found nothing. Are you willing to provide you device's logs? It would be awesome if you are. So basically what you need to do is to start `adb` using steps below and crash it, collect logs and send to us:
1. enable USB debugging on your device https://www.howtogeek.com/129728/how-to-access-the-developer-options-menu-and-enable-usb-debugging-on-android-4.2/
2. do the following https://www.hexnode.com/mobile-device-management/help/obtain-android-device-logs-using-windows-and-mac/
3. upload logs to brave.com using that link https://upload-support.brave.com/. Pick rewards section there.
Thanks!

**Comment by chris122380** [comment]
> Hi @chris122380, unfortunately we cannot replicate that. I had a chance to look deeply on that today, but found nothing. Are you willing to provide you device's logs? It would be awesome if you are. So basically what you need to do is to start `adb` using steps below and crash it, collect logs and send to us:
> 
> 1. enable USB debugging on your device https://www.howtogeek.com/129728/how-to-access-the-developer-options-menu-and-enable-usb-debugging-on-android-4.2/
> 2. do the following https://www.hexnode.com/mobile-device-management/help/obtain-android-device-logs-using-windows-and-mac/
> 3. upload logs to brave.com using that link https://upload-support.brave.com/. Pick rewards section there.
>    Thanks!

I am being asked for a payment ID when trying to upload the log file but I don't know what that is or where to find it. 

Since I can only get it to happen randomly it took a while but did happen at the end of my log file but couldn't get it uploaded do to not knowing my payment ID.

**Comment by SergeyZhukovsky** [comment]
Sorry @chris122380 I should have been mentioned that. You can find it in `brave://rewards-internals`.

**Comment by chris122380** [comment]
> Sorry @chris122380 I should have mentioned that. You can find it in `brave://rewards-internals`.

I do not have a Bat wallet setup and do not see it in brave://rewards-internals

**Comment by SergeyZhukovsky** [comment]
Ok, just put a random UUID there, you can generate it there https://www.uuidgenerator.net/. It doesn't matter version1 or 4

**Comment by chris122380** [comment]
> Ok, just put a random UUID there, you can generate it there https://www.uuidgenerator.net/. It doesn't matter version1 or 4

Case #: ba953c08-1c3a-408a-a9f1-9db49f686022

Issue seems to happen less and less per update and more on wifi. I tried doing a second log today at work but couldn't get it to do it over cell service.  The randomness of this makes it difficult to log. Happens maybe 2-3 times in a 24 hour period.. Where older 1.18, 1.17, and 1.16 brave versions would do it multiple times an hour.

**Comment by SergeyZhukovsky** [comment]
Hi @chris122380 , thank you, I've got your logs, analysing them.

**Comment by kjozwiak** [comment]
@SergeyZhukovsky is there anything QA can do here in terms of verifications? I don't really see any STR/Cases other than browsing and making sure Brave isn't crashing. Is there a particular website that's causing the crashes? There's no STR in https://github.com/brave/brave-core/pull/7763 either. Do we label this as `QA/No` and just make sure `1.20.x` is stable when using it while we run through verifications/manual passes?

**Comment by SergeyZhukovsky** [comment]
@kjozwiak marked as `QA/No`

**Comment by SergeyZhukovsky** [comment]
@chris122380 that should have been resolved, thanks for the logs again. The fix should appear in the next Nightly update and in the next stable update as well. Would you mind to check is it fixed or not as we were not able to replicate it still. Thanks.

**Comment by chris122380** [comment]
I am currently running the latest stable version of Brave 1.19.88 (January 28th) and I don't appear to be having any issues. I'm not sure which stable version the patch is on but so far I'd say all is good.

**Comment by SergeyZhukovsky** [comment]
@chris122380 the fix is not there yet, it's just mean you cannot replicate it for some reason currently :).

**Comment by kjozwiak** [comment]
@chris122380 we just released `1.19.91 CR: 88.0.4324.146` a few hours ago which includes this fix. You should see the update soon as it's currently being phased at 1%. Let us know once you've received it if things improved.

**Comment by chris122380** [comment]
> @chris122380 we just released `1.19.91 CR: 88.0.4324.146` a few hours ago which includes this fix. You should see the update soon as it's currently being phased at 1%. Let us know once you've received it if things improved.

I have not yet received the update but I will keep you posted. If I find issues I'll try to get another bug report. It may take a week or so as I'm recovering from surgery.

**Comment by kjozwiak** [comment]
> > @chris122380 we just released `1.19.91 CR: 88.0.4324.146` a few hours ago which includes this fix. You should see the update soon as it's currently being phased at 1%. Let us know once you've received it if things improved.
> 
> I have not yet received the update but I will keep you posted. If I find issues I'll try to get another bug report. It may take a week or so as I'm recovering from surgery.

Sounds good! Thanks again for the report/help narrowing down the issue. Wishing you a speedy recovery!
