### ISSUE TITLE
Change my Tipping Banner, but not showing in publishers page.

### ISSUE THREAD

**Issue by BroJenuel** [brave/brave-browser#12624]
## Description 

Hi, The issue is when I log in to my publisher page. And then try to change the tipping banner but the tipping banner is not showing. It is only a whole back opacity is showing.

## Steps to Reproduce

   1. login to brave rewards
   2. click tipping banner

## Actual result:

This is the actual result.
![image](https://user-images.githubusercontent.com/31676163/98756866-589cb200-2406-11eb-9ab7-2955d25dbb9c.png)

## Expected result:
It should show the banner for me to be able to change images and stuff.

## Reproduces how often: 

everytime I click the Tipping Banner.

![image](https://user-images.githubusercontent.com/31676163/98757021-9994c680-2406-11eb-83f8-414f81fc429e.png)

## Brave version (brave://version info)

Brave	1.16.72 Chromium: 86.0.4240.183 (Official Build) (64-bit)
Revision	0b568b034b8f7994697cb341eeca5979b84151cc-refs/branch-heads/4240@{#1374}
OS	Windows 10 OS Version 2009 (Build 19042.572)
JavaScript	V8 8.6.395.23
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
Command Line	"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory=Default --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=ReducedReferrerGranularity,PasswordImport,MixedContentSiteSetting,WebUIDarkMode,PrefetchPrivacyChanges,LegacyTLSEnforced,DnsOverHttps,OmniboxContextMenuShowFullUrls,AutoupgradeMixedContent,PassiveMixedContentWarning,WinrtGeolocationImplementation --disable-features=TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,VideoPlaybackQuality,PrivacySettingsRedesign,SmsReceiver,TabHoverCards,AutofillServerCommunication,PasswordCheck,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end
Executable Path	C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\jenue\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-4113a79e

## Version/Channel Information:

- I am using the current release.
- This only happens in the https://publishers.basicattentiontoken.org/

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  Nope
- Does the issue resolve itself when disabling Brave Rewards? Nope
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by rebron** [comment]
@BroJenuel Are you still having this issue on the publisher's site? Custom banner working?

**Comment by hollons** [comment]
Hi @BroJenuel, if this is still an issue, please email at Steven@brave.com. Thanks!
