### ISSUE TITLE
Implement dynamic active studies for Brave Ads confirmations DTO

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#12626]
- Support multiple active studies by convention, e.g. all studies that contain `*BraveAds*` will be appended to confirmations
- Rename `experiment` to `studies` (plural)
- Convert dict to array to allow for multiple entries in the future
- Remove the `value` key

Example:
```
"studies" :  [
    {
        "name": "BraveAdsFooStudy",
        "group": "GroupA"
    },
    {
        "name": "BarStudyForBraveAds",
        "group": "GroupA"
    }
]
```

**Comment by LaurenWags** [comment]
@moritzhaller does this need manual QA? if so, can you please provide a test plan. If not, let's mark this one as `QA/No`.

**Comment by moritzhaller** [comment]
@LaurenWags I've put as `QA/No` as we have used downstream data successfully already. Unless @jsecretan or @tmancey think otherwise I think we are good.

**Comment by LaurenWags** [comment]
awesome, thanks @moritzhaller 😄
