### ISSUE TITLE
Crypto Wallets login issues when onboarding is not completed

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12622]
## Description 
This is related a bug that was previously fixed pre the v8 MetaMask rebase: https://github.com/brave/brave-browser/issues/6442

The crux of the issue is that if onboarding isn't marked as completed, login to the UI will not happen (It just gets rejected, no error)

## Steps to Reproduce
   1. Create a new wallet
   2. On the "Confirm your seed phrase" screen, close the tab or navigate elsewhere
   3. Go back to brave://wallet, enter your password

## Actual result:
Unlock page refreshes with no feedback

## Expected result:
You get logged in to your account when adding the correct password

## Reproduces how often: 
100%

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | Linux
Component | `1.0.17 dev`

- Verified steps from issue description 
![12622-linux](https://user-images.githubusercontent.com/17010094/100186693-66f6cd80-2ede-11eb-8e47-79d5aab33526.gif)

------
Verification passed on

Brave | 1.19.16 Chromium: 87.0.4280.66 (Official Build) nightly (64-bit)
-- | --
Revision | `fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}`
OS | Windows 10 OS Version 1809 (Build 17763.1577)
Component | `1.0.17 dev`

- Verified steps from issue description 
![12622-win](https://user-images.githubusercontent.com/17010094/100186781-9f96a700-2ede-11eb-918a-8819f3fc2799.gif)
---------

Verification passed on 

Brave | 1.18.56 Chromium: 87.0.4280.60 (Official Build) dev (x86_64)
-- | --
Revision | `12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}`
OS | macOS Version 10.15.7 (Build 19H2)
Component | `1.0.17 dev`

- Verified steps from issue description 
![12622-mac](https://user-images.githubusercontent.com/17010094/100186956-f56b4f00-2ede-11eb-9588-efb9d349c0ce.gif)
