### ISSUE TITLE
Left side of browser screen totally unresponsive (all pages) on Windows PC

### ISSUE THREAD

**Issue by cryptojennie** [brave/brave-browser#12621]
## Description 

Two Reddit users have reported experiencing total unresponsiveness on the left side of their browser screens, on all pages (e.g., cannot scroll, all buttons unclickable, left sidebar on YouTube completely missing/inaccessible in one case). 

Missing left sidebar on YouTube: 
![gnyu11j0kfy51](https://user-images.githubusercontent.com/32344882/98741800-4aee1a80-237b-11eb-8d78-7a506074cdc9.png)

## Steps to Reproduce
Unable to reproduce on Brave v1.16.72 desktop MacOS. 

## Brave version (brave://version info)

`/u/OneEyedGayboi`:
1. User appears to be on Wndows PC, general release (based on screenshot). Still waiting for version number: https://www.reddit.com/r/brave_browser/comments/jrmu14/help_not_able_to_access_left_sidebar_of_youtube_i/ 

`/u/satyatherobot`:
2. Waiting for platform/version number from this user: https://www.reddit.com/r/brave_browser/comments/jrp4u9/something_is_really_wrong_with_brave_the_left/ 

cc: @LaurenWags

**Comment by cryptojennie** [comment]
User `/u/OneEyedGayboi` followed up with additional information: 

- Version 1.16.72 Chromium: 86.4240.183
- User tried toggling Shields on/off to no avail 
- No left-side screen issues or extension issues in other browsers, only in Brave

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/brave_browser/comments/jsvl99/problem_with_youtube/

**Comment by rebron** [comment]
Is this still an issue? I'm not seeing this on Windows or macOS.
![Screen Shot 2021-03-01 at 10 58 05 AM](https://user-images.githubusercontent.com/5951041/109556243-6ba5c180-7a8b-11eb-9880-8a09a1a99cc1.png)
![Screen Shot 2021-03-01 at 10 57 55 AM](https://user-images.githubusercontent.com/5951041/109556247-6e081b80-7a8b-11eb-9dd3-7d124bf4cb84.png)

**Comment by LaurenWags** [comment]
I've never been able to reproduce @rebron. @brave/legacy_qa - have any of you experienced this?

**Comment by rebron** [comment]
@cryptojennie @Miyayes This might be an issue with one of the user's extensions.

**Comment by rebron** [comment]
Closing this one as stale. We haven't been able to reproduce this issue on any OS. 
@Miyayes If original reporters are still seeing this issue with 1.21.76, we can reopen.
