### ISSUE TITLE
BAT tipping icon appearing in header of GitHub issues table when checkbox selected

### ISSUE THREAD

**Issue by AlanBreck** [brave/brave-browser#12635]
## Description 

When viewing all issues on a GitHub repo (as a user able to edit issues), the BAT tipping icon appears in the table header when an issue checkbox is selected.

![Kapture 2020-11-11 at 09 56 20](https://user-images.githubusercontent.com/1199820/98830377-5b000b80-2408-11eb-89bd-e04debd64881.gif)

## Steps to Reproduce

   1. Log in to GitHub
   2. Navigate to a repo in which you have edit access for issues
   3. Navigate to the repo issues list
   4. Select an issue checkbox
   5. Note the BAT tipping icon in table header

## Actual result:

<img width="1539" alt="Screen Shot 2020-11-11 at 10 29 37 AM" src="https://user-images.githubusercontent.com/1199820/98830876-e5e10600-2408-11eb-9b71-8ccd282cb1bc.png">

## Expected result:
<img width="1639" alt="Screen Shot 2020-11-11 at 10 28 32 AM" src="https://user-images.githubusercontent.com/1199820/98830888-e9748d00-2408-11eb-990f-4260d0ad1035.png">

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)
`1.17.63 Chromium: 87.0.4280.49 (Official Build) unknown (x86_64)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? **NO**
- Can you reproduce this issue with the beta channel? **YES**
- Can you reproduce this issue with the nightly channel? **YES**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by mkarolin** [comment]
Unable to repro. Please reopen if it still happens.
