### ISSUE TITLE
Only allow known extensions to communicate with Brave extension

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#12631]
Follow up to https://github.com/brave/brave-core/pull/6978#discussion_r520830751. Only allow Brave Rewards and Greaselion extensions to communicate with the `onMessageExternal` listener in the Greaselion responder that lives in the Brave extension.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/7119
![image](https://user-images.githubusercontent.com/38657976/101156220-46e9ab80-364e-11eb-89fa-7313aaa7f681.png)
