### ISSUE TITLE
[Feature request] button to reload web page after javascript blocking / unblocking

### ISSUE THREAD

**Issue by fthx** [brave/brave-browser#12648]
## Description 

When I unblock JS in a website, Brave does not propose to reload this page to refresh it accordingly.

## Steps to Reproduce

   1. in settings, block JS
   2. visit a webpage using JS
   3. allow this site to use JS

## Actual result:

None.

## Expected result:

Reload button appears at the end of url bar, beside the Brave privacy icon
OR
Reload button appears in the JS settings popup

## Reproduces how often: 

Always.

## Brave version (brave://version info)

1.16.75 snap
Ubuntu 20.04

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by diracdeltas** [comment]
For me the page reloads automatically when you change any shield setting including script blocking

**Comment by fthx** [comment]
Including the JS shortcut here:
![image](https://user-images.githubusercontent.com/23138504/98993611-fc817d00-252e-11eb-9d8e-e1fc1482f453.png)
?

**Comment by diracdeltas** [comment]
@fthx ohhh i see, you mean the chromium noscript feature. FYI you can do this instead and it'll autoreload:

<img width="586" alt="Screen Shot 2020-11-12 at 12 48 38 PM" src="https://user-images.githubusercontent.com/549654/98994901-683ef800-24e5-11eb-90e6-f7b04ad3c209.png">

**Comment by fthx** [comment]
Yes that I know :-) .

Do you experience inconsistencies between both indicators? Test case:
1) go to a website using JS
2) disable script blocking using Brave panel (that is displayed in your post)
3) the script icon at the right of url bar is not updated (stay displayed with "JS blocked" title but JS unblocked in button-list!)
4) if you play with this icon you cannot change script blocking setting 

Well, it's messy here. :-)

**Comment by diracdeltas** [comment]
yeah, that's in https://github.com/brave/brave-browser/issues/199. maybe we should remove the chromium noscript icon instead of trying to sync it with the shields UI.

**Comment by fthx** [comment]
You're right, my BR is finally just a collateral damage of this duplicated feature in Brave.
So +1 for removing the noscript icon.
