### ISSUE TITLE
[Desktop] New Tab Page Wallpaper is no longer centered

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#12651]
## Description 

Wallpaper is left-aligned but should be centered

## Steps to Reproduce

   1. Wallappers On
   2. Open NTP
   3. Make window portrait aspect ratio

## Actual result:

Wallpaper is left aligned
![image](https://user-images.githubusercontent.com/741836/98868643-4f6f0d80-2425-11eb-9156-a8ee9f5ae5c1.png)

## Expected result:
Wallpaper is centered

![image](https://user-images.githubusercontent.com/741836/98868856-a83ea600-2425-11eb-8b94-2e6479b468df.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Only 1.18.48

## Version/Channel Information:

- Can you reproduce this issue with the current release?  No
- Can you reproduce this issue with the beta channel?  No
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)


```
- Verified STR from the description and ensured NTP wallpapers are centered
![image](https://user-images.githubusercontent.com/38657976/100057353-4468a400-2e4d-11eb-9394-c9e8d64a354e.png)
