### ISSUE TITLE
TOR not working with Multiple Profiles Active

### ISSUE THREAD

**Issue by whiteonion** [brave/brave-browser#12650]
## Description 
TOR not working with Multiple Profiles Active Simultaneously.
so the problem seems to be starting two simultanious TOR connections from two distinct profiles, using twho new private window with tor commands, while not closing any others. it seems that brave browser can only open one tor stream, and not two.

## Steps to Reproduce
1. register at least TWO Profiles. Lets call them profile1 and profile2
2. open profile1 (default) and start a new private window with tor within that profile
3. go to https://check.torproject.org/ and see if tor is working. it should be working
4. open profile2 while NOT closing profile1 windows and profile1 tor window
5. within profile2 start a new private window with tor
6. go to https://check.torproject.org/ and see if tor is working. it will not be working

## Actual result:
Tor not working

## Expected result:
Tor working

## Reproduces how often: 
Always

## Brave version (brave://version info)
Version 1.16.72 Chromium: 86.0.4240.183 (Official Build) (x86_64)

so, I guess it's pretty clear where to look to fix it. :)
Hope the devs get around and fix it quickly. 👍

**Comment by diracdeltas** [comment]
cc @darkdh

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.64 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/7069
- Testing is covered in https://github.com/brave/brave-browser/issues/12470#issuecomment-749421953
