### ISSUE TITLE
Brave Ads should not open the same target url for all creatives in a creative set

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12653]
## Description 

Brave Ads should not open the same target url for all creatives in a creative set. This issue regressed with https://github.com/brave/brave-browser/issues/10488 which was merged to 1.17.x

## Steps to Reproduce

   1. View and click more than one ad from the same creative set (configured with different target urls)

## Actual result:

Each ad opens the same target url

## Expected result:
Each ad should open the target url as defined in the creative

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes (1.17.x)
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.17.70 Chromium: 87.0.4280.60 (Official Build) (x86_64)
Revision	12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS	macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/internal/issues/735

Confirmed 1st ad shown:

```
[2159:775:1118/133934.392232:VERBOSE1:ads_impl.cc(1149)] Ad notification shown:
  uuid: 2fdc012f-8891-420e-8109-ed89f2240a8f
  creativeInstanceId: cd20cc5e-c125-44d0-82a3-75a6fee67704
  creativeSetId: 32439113-32d2-4b50-9497-405b7eedd1d5
  campaignId: dbd742cc-7bcf-47c8-aeed-5a8be10c7261
  category: untargeted
  title: travala
  body: travala
  targetUrl: https://www.travala.com/
```

Confirmed after clicking on the ad that the 1st landing page was `travala.com`

Confirmed 2nd ad shown:

```
[2159:775:1118/135327.048867:VERBOSE1:ads_impl.cc(1149)] Ad notification shown:
  uuid: 6382d742-4297-42d4-9c4e-d36671c5cfa7
  creativeInstanceId: 022c8846-80da-4c76-b099-c84391fca85f
  creativeSetId: 32439113-32d2-4b50-9497-405b7eedd1d5
  campaignId: dbd742cc-7bcf-47c8-aeed-5a8be10c7261
  category: untargeted
  title: brave
  body: brave
  targetUrl: https://www.brave.com/
```

Confirmed after clicking on the ad that the 2nd landing page was `brave.com`

Verified test plan from https://github.com/brave/brave-core/pull/7127#issue-519527345:
 - Confirmed generally ad notifications were served after upgrading from 1.16.x to 1.17.x
 - Confirmed generally ad notifications were served after upgrading from 1.15.x to 1.17.x

**Comment by LaurenWags** [comment]
changing to `release-notes/exclude` since this was a regression caused by https://github.com/brave/brave-browser/issues/10488 which was implemented in this milestone. cc @tmancey @rebron @kjozwiak - if you disagree let me know and we can re-add to the release notes.
