### ISSUE TITLE
Password disclaimer missing from create account flow [Crypto Wallets]

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12654]
## Description 
The password warning that appears under the first time import route should also appear for new account creation

## Steps to Reproduce
   1. Opt in to Crypto Wallets
   2. Select "Create"

## Actual result:
No disclaimer
<img width="773" alt="Screen Shot 2020-11-11 at 5 37 33 PM" src="https://user-images.githubusercontent.com/8732757/98880569-44c47080-2445-11eb-88b8-5113f75a9fb7.png">

## Expected result:
Should show disclaimer
<img width="771" alt="Screen Shot 2020-11-11 at 5 41 05 PM" src="https://user-images.githubusercontent.com/8732757/98880580-4b52e800-2445-11eb-94c8-fb3def964089.png">

## Reproduces how often: 
100%

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | Linux
Component | `1.0.17 dev`

- Verified password disclaimer is shown when a new wallet is created
![image](https://user-images.githubusercontent.com/17010094/100187149-601c8a80-2edf-11eb-8505-8c759a9f538c.png)
--------
Verification passed on

Brave | 1.19.16 Chromium: 87.0.4280.66 (Official Build) nightly (64-bit)
-- | --
Revision | `fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}`
OS | Windows 10 OS Version 1809 (Build 17763.1577)
Component | `1.0.17 dev`

- Verified password disclaimer is shown when a new wallet is created
![image](https://user-images.githubusercontent.com/17010094/100187244-a1ad3580-2edf-11eb-91ea-049042140768.png)
---------
Verification passed on 

Brave | 1.18.56 Chromium: 87.0.4280.60 (Official Build) dev (x86_64)
-- | --
Revision | `12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}`
OS | macOS Version 10.15.7 (Build 19H2)
Component | `1.0.17 dev`

- Verified password disclaimer is shown when a new wallet is created
![image](https://user-images.githubusercontent.com/17010094/100187267-ab369d80-2edf-11eb-8306-95e46389662b.png)
