### ISSUE TITLE
[Widget] Certain 5 letter tokens causes dropdown arrow to be on next line

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12669]
## Description 
Certain 5 letter tokens causes dropdown arrow to break

## Steps to reproduce 

   1. Connect to Binance widget
   2. Select  `ADXOLD` , `ANTOLD` or `PERLOLD` on convert screen
   3. Dropdown arrow goes to next line

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/98901764-38273300-24ac-11eb-9d94-0f930a250ed6.png)

## Expected result
No new line for dropdown arrow

## Issue reproduces how often 
Easy

## Brave version (brave://version info)

Brave | 1.16.75 Chromium: 86.0.4240.193 (Official Build) (64-bit)
-- | --
Revision | `4b1dc838fc8d2b55f2147e7a642b20baf443da5c-refs/branch-heads/4240@{#1411}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2009 (Build 19042.685)
```

**`ADXOLD`** | **`ANTOLD`** | **`PERLOLD`**
---------------|-----------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/103599707-c8458f80-4ed3-11eb-8601-0ff508e0e6dd.png) | ![image](https://user-images.githubusercontent.com/2602313/103599788-f62ad400-4ed3-11eb-8161-ec8500ee1475.png) | ![image](https://user-images.githubusercontent.com/2602313/103599838-0f338500-4ed4-11eb-831b-0b524f82a383.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Linux

- Verified dropdown is shown next to tokens with 5 letters

ADXOLD | ANTOLD | PERLOLD
-- | -- | --
![Screenshot from 2021-01-05 05-07-19](https://user-images.githubusercontent.com/17010094/103608977-a4566e00-4f14-11eb-990e-0f5859b083ab.png) | ![Screenshot from 2021-01-05 05-07-37](https://user-images.githubusercontent.com/17010094/103608984-aa4c4f00-4f14-11eb-8d71-427d2a988ca3.png) | ![Screenshot from 2021-01-05 05-07-50](https://user-images.githubusercontent.com/17010094/103608987-ac161280-4f14-11eb-9022-237721730240.png)

--------

Verification passed on 

Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (x86_64)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 10.15.7 (Build 19H2)

- Verified dropdown is shown next to tokens with 5 letters

ADXOLD | ANTOLD | PERLOLD
-- | -- | --
<img width="1312" alt="Screenshot 2021-01-05 at 05 04 36" src="https://user-images.githubusercontent.com/17010094/103608917-75d89300-4f14-11eb-8448-eb227bee2de5.png"> | <img width="1312" alt="Screenshot 2021-01-05 at 05 04 41" src="https://user-images.githubusercontent.com/17010094/103608931-80932800-4f14-11eb-8ee5-c1c0fbd80613.png"> | <img width="1312" alt="Screenshot 2021-01-05 at 05 04 52" src="https://user-images.githubusercontent.com/17010094/103608939-87ba3600-4f14-11eb-8bc1-b4e054c5b50a.png">
