### ISSUE TITLE
[Desktop] Rewards onboarding is not clear for existing users

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#12675]
## Description 

The current rewards onboarding UX does not explicitly tell the user that Ads and auto-contribute will be enabled. For currently opted-in Rewards users, the CTA text "Start using Brave Rewards" does not imply any additional action, and those users may be surprised to find out that their Rewards settings have been updated. Even more concerning, if auto-contribute is enabled for existing users that have chosen to turn off auto-contribute and ads, then they may be surprised when BAT funds are automatically withdrawn from their wallet.

## Solution ideas

- Adjust wording of onboarding modals.
- Do not show the onboarding experience to users that have enabled rewards in a previous version.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Testing is covered in https://github.com/brave/brave-browser/issues/12612#issuecomment-738105465
