### ISSUE TITLE
Set default browser first_run dialog on macOS and Linux

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#12679]
## Description 
We need to update the onboarding flow with:

- More aggressive pitch for set default browser for increased retention and engagement

## Design for MacOS

Enable the `first_run` dialog that comes with Chromium. This dialog shows _before_  the browser is launched. It comes with checkboxes for set default browser and send crash reports. Change the text to say 'private product analytics'.
![image](https://user-images.githubusercontent.com/2388823/105923614-7f27bd80-5ff1-11eb-8508-c22191192299.png)

## Assets
Figma: https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/?node-id=146%3A0

**Comment by diracdeltas** [comment]
@karenkliu same comment from https://github.com/brave/brave-browser/issues/12680#issuecomment-729895096 applies here

**Comment by karenkliu** [comment]
Removed Yahoo from the search engine slide.

**Comment by btlechowski** [comment]
Verification passed on `beta` channel

Brave | 1.21.47 Chromium: 88.0.4324.152 (Official Build) beta (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Linux

Verified first run dialog is shown
![image](https://user-images.githubusercontent.com/34715963/107959987-5bc6b180-6fa4-11eb-9d67-3e7dc4bf8a4c.png)
Verified on `beta` channel that the beta build was made default browser when `Set Brave as your default browser` is enabled
Verified default browser was not changed when `Set Brave as your default browser` is disabled
Verified automatic crash reporting is enabled when `Help improve Brave...` is enabled
Verified PPA is enabled when `Help improve Brave...` is enabled. 
![image](https://user-images.githubusercontent.com/34715963/107957180-857dd980-6fa0-11eb-8392-d069b7811367.png)
Verified automatic crash reporting is disabled when `Help improve Brave...` is disabled
Verified PPA is disabled when `Help improve Brave...` is disabled. Logged https://github.com/brave/brave-browser/issues/14160
![image](https://user-images.githubusercontent.com/34715963/107957599-1eacf000-6fa1-11eb-9962-772833dfdd83.png)


Verification passed on `dev` channel

Brave | 1.21.52 Chromium: 88.0.4324.152 (Official Build) dev (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Verified first run dialog is shown
![image](https://user-images.githubusercontent.com/34715963/107960299-bf50df00-6fa4-11eb-8046-ff34bdf94fab.png)
Verified on `dev` channel that the dev build was made default browser when `Set Brave as your default browser` is enabled
Verified default browser was not changed when `Set Brave as your default browser` is disabled
Verified automatic crash reporting is enabled when `Help improve Brave...` is enabled
Verified PPA is enabled when `Help improve Brave...` is enabled. 
![image](https://user-images.githubusercontent.com/34715963/107960416-e6a7ac00-6fa4-11eb-8772-1a3563e01d8a.png)
Verified automatic crash reporting is disabled when `Help improve Brave...` is disabled
Verified PPA is disabled when `Help improve Brave...` is disabled. Logged https://github.com/brave/brave-browser/issues/14160
![image](https://user-images.githubusercontent.com/34715963/107961354-130ff800-6fa6-11eb-99c5-2f700ccfc3bd.png)

Verification passed on `nightly` channel

Brave | 1.22.23 Chromium: 89.0.4389.48 (Official Build) nightly (64-bit)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | Ubuntu 18.04 LTS

Verified first run dialog is shown
![image](https://user-images.githubusercontent.com/34715963/107961810-ad703b80-6fa6-11eb-83f4-e5274aeef5a7.png)
Verified on `nightly` channel that the nightly build was made default browser when `Set Brave as your default browser` is enabled
Verified default browser was not changed when `Set Brave as your default browser` is disabled
Verified automatic crash reporting is enabled when `Help improve Brave...` is enabled
Verified PPA is enabled when `Help improve Brave...` is enabled. 
![image](https://user-images.githubusercontent.com/34715963/107962692-8cf4b100-6fa7-11eb-8196-c2ebbec3d749.png)
Verified automatic crash reporting is disabled when `Help improve Brave...` is disabled
Verified PPA is disabled when `Help improve Brave...` is disabled. Logged https://github.com/brave/brave-browser/issues/14160
![image](https://user-images.githubusercontent.com/34715963/107962794-adbd0680-6fa7-11eb-931b-a170c21bdc3c.png)

**Comment by btlechowski** [comment]
Set as `QA/Blocked` till we get a release build for 1.21.x

**Comment by btlechowski** [comment]
No longer `QA/Blocked` as we have a 1.21.x release build.

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/7700 with:

Brave | 1.21.68 Chromium: 89.0.4389.58 (Official Build) (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.2 (Build 20D80)

Confirmed first run dialog is shown:
<details>
<summary>screenshot</summary>
<img width="592" alt="109192237-d386a000-774b-11eb-91a1-c695b60ffd1e" src="https://user-images.githubusercontent.com/387249/109224360-b1ebdf80-7770-11eb-8c03-3fd2ec412bd2.png">
</details>

Confirmed when using `Release` channel that I was prompted about changing my default browser when "Set Brave as your default browser" was selected:
<details>
<summary>screenshot</summary>
<img width="372" alt="Screen Shot 2021-02-25 at 1 54 40 PM" src="https://user-images.githubusercontent.com/387249/109224687-26bf1980-7771-11eb-850d-2e24f4e76294.png">
</details>

Confirmed that `Release` build was made default browser when selected on OS-level prompt.
 
Confirmed automatic crash reporting is **enabled** when "Help improve Brave..." is selected.

Confirmed P3A is enabled by default in `brave://settings/privacy` 

<details>
<summary>screenshots</summary>
<img width="1312" alt="Screen Shot 2021-02-25 at 1 59 55 PM" src="https://user-images.githubusercontent.com/387249/109225210-d3999680-7771-11eb-8013-beab18bae0d5.png"><img src="https://user-images.githubusercontent.com/387249/109193081-db930f80-774c-11eb-963f-cebbb2e76271.png">
</details>

Confirmed I was not prompted about changing my default browser when `Set Brave as your default browser` is **not** selected.
Confirmed in the `Default browser` section in`brave://settings` that the `Make default` button exists and is clickable.
Confirmed automatic crash reporting is **disabled** when `Help improve Brave...` is **not** selected.
Confirmed P3A remains enabled, by default, in `brave://settings/privacy`

<details>
<summary>screenshots</summary>
<img width="592" alt="Screen Shot 2021-02-25 at 2 03 09 PM" src="https://user-images.githubusercontent.com/387249/109225948-db0d6f80-7772-11eb-9701-daa1b0e5fe6b.png"><img width="1312" alt="Screen Shot 2021-02-25 at 2 09 54 PM" src="https://user-images.githubusercontent.com/387249/109226197-33dd0800-7773-11eb-9336-20012294a011.png"><img width="1312" alt="Screen Shot 2021-02-25 at 2 03 25 PM" src="https://user-images.githubusercontent.com/387249/109225584-515da200-7772-11eb-8aed-cec40c890be3.png">
</details>

**Comment by pitsi** [comment]
I just upgraded to 1.21.x and I get the prompt ON EVERY LAUNCH. Shouldn't it be shown just once?
Debian testing/unstable x64 and x-www-browser (= the system wide setting for the default browser) is already set to brave
```
$ file /usr/bin/x-www-browser
/usr/bin/x-www-browser: symbolic link to /etc/alternatives/x-www-browser
$ file /etc/alternatives/x-www-browser
/etc/alternatives/x-www-browser: symbolic link to /usr/bin/brave-browser-stable
```
If there is a switch or a flag that can disble it, please tell me. Thank you in advance.

**Comment by matthieu-bt** [comment]
Same issue here, on Windows 10. I use Brave in private mode only. And since this morning, EVERY time I open it, I get the prompt.

**Comment by pitsi** [comment]
If someone openened a new issue report for that spammy prompt, let's continue our discussion there please.
I would open it, but I am too busy today with an rpi4 that... "misbehaves" :D

**Comment by pitsi** [comment]
After a full day of opening and closing brave dozens of times I noticed that the issue no longer happens, at least on my end, so I won't open the report I was saying.
