### ISSUE TITLE
[Desktop] Brave News article isn't in forward-history when navigating back to NTP

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#12674]
## Steps to Reproduce

   1. Open NTP
   2. Click through on a Brave Today article
   3. Go 'Back'

## Actual result:

Forward button is disabled

## Expected result:
Forward button is available and navigates to Brave Today article when clicked

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.19.2
1.18.51

## Version/Channel Information:

- Can you reproduce this issue with the current release?  N/A
- Can you reproduce this issue with the beta channel? Yes 1.18.51
- Can you reproduce this issue with the nightly channel? Yes 1.19.2

**Comment by srirambv** [comment]
+1 from @rebron via #13478

**Comment by stephendonner** [comment]
Can we pop-state here?

**Comment by LorenzoMinto** [comment]
Closing as stale. As we recently changed the default behaviour to open in a new tab.
