### ISSUE TITLE
npm run init errors

### ISSUE THREAD

**Issue by jafxdesign** [brave/brave-browser#12670]
I am new here; running "**npm run init**" gives the follwoing errors:

46 failed patches:
chrome/BUILD.gn
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/BUILD.gn:419
error: chrome/BUILD.gn: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/VERSION
  - Patch applied because: No corresponding .patchinfo file was found.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/VERSION:1
error: chrome/VERSION: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/BUILD.gn
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/BUILD.gn:234
error: chrome/android/BUILD.gn: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/chrome_java_sources.gni
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/chrome_java_sources.gni:1707
error: chrome/android/chrome_java_sources.gni: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/expectations/lint-suppressions.xml
  - Patch applied because: No corresponding .patchinfo file was found.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/expectations/lint-suppressions.xml:366
error: chrome/android/expectations/lint-suppressions.xml: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/java/AndroidManifest.xml
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/java/AndroidManifest.xml:158
error: chrome/android/java/AndroidManifest.xml: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/java/res/layout/custom_tabs_toolbar.xml
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/java/res/layout/custom_tabs_toolbar.xml:97
error: chrome/android/java/res/layout/custom_tabs_toolbar.xml: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/java/src/org/chromium/chrome/browser/ChromeTabbedActivity.java
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/java/src/org/chromium/chrome/browser/ChromeTabbedActivity.java:1440
error: chrome/android/java/src/org/chromium/chrome/browser/ChromeTabbedActivity.java: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/java/src/org/chromium/chrome/browser/sync/AndroidSyncSettings.java
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/java/src/org/chromium/chrome/browser/sync/AndroidSyncSettings.java:74
error: chrome/android/java/src/org/chromium/chrome/browser/sync/AndroidSyncSettings.java: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/java/src/org/chromium/chrome/browser/toolbar/ToolbarManager.java
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/java/src/org/chromium/chrome/browser/toolbar/ToolbarManager.java:308
error: chrome/android/java/src/org/chromium/chrome/browser/toolbar/ToolbarManager.java: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/java/src/org/chromium/chrome/browser/toolbar/bottom/BottomControlsCoordinator.java
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/java/src/org/chromium/chrome/browser/toolbar/bottom/BottomControlsCoordinator.java:103
error: chrome/android/java/src/org/chromium/chrome/browser/toolbar/bottom/BottomControlsCoordinator.java: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/java/src/org/chromium/chrome/browser/toolbar/top/ToolbarPhone.java
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/java/src/org/chromium/chrome/browser/toolbar/top/ToolbarPhone.java:88
error: chrome/android/java/src/org/chromium/chrome/browser/toolbar/top/ToolbarPhone.java: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/android/java/src/org/chromium/chrome/browser/ui/RootUiCoordinator.java
  - Patch applied because: No corresponding .patchinfo file was found.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/android/java/src/org/chromium/chrome/browser/ui/RootUiCoordinator.java:528
error: chrome/android/java/src/org/chromium/chrome/browser/ui/RootUiCoordinator.java: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/content_settings/host_content_settings_map_factory.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/content_settings/host_content_settings_map_factory.cc:86
error: chrome/browser/content_settings/host_content_settings_map_factory.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/extensions/api/webrtc_logging_private/webrtc_logging_private_api.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/extensions/api/webrtc_logging_private/webrtc_logging_private_api.cc:89
error: chrome/browser/extensions/api/webrtc_logging_private/webrtc_logging_private_api.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/notifications/notification_display_service_impl.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/notifications/notification_display_service_impl.cc:100
error: chrome/browser/notifications/notification_display_service_impl.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/profiles/profile_impl.h
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/profiles/profile_impl.h:171
error: chrome/browser/profiles/profile_impl.h: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/resources/extensions/BUILD.gn
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/resources/extensions/BUILD.gn:21
error: chrome/browser/resources/extensions/BUILD.gn: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/resources/settings/BUILD.gn
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/resources/settings/BUILD.gn:32
error: chrome/browser/resources/settings/BUILD.gn: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/resources/settings/privacy_page/personalization_options.html
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/resources/settings/privacy_page/personalization_options.html:46
error: chrome/browser/resources/settings/privacy_page/personalization_options.html: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/resources/settings/privacy_page/personalization_options.js
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/resources/settings/privacy_page/personalization_options.js:111
error: chrome/browser/resources/settings/privacy_page/personalization_options.js: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/resources/settings/privacy_page/privacy_page.html
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/resources/settings/privacy_page/privacy_page.html:323
error: chrome/browser/resources/settings/privacy_page/privacy_page.html: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/resources/settings/site_settings/site_details.html
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/resources/settings/site_settings/site_details.html:193
error: chrome/browser/resources/settings/site_settings/site_details.html: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/ui/BUILD.gn
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/ui/BUILD.gn:586
error: chrome/browser/ui/BUILD.gn: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/ui/android/appmenu/internal/java/src/org/chromium/chrome/browser/ui/appmenu/AppMenu.java
  - Patch applied because: No corresponding .patchinfo file was found.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/ui/android/appmenu/internal/java/src/org/chromium/chrome/browser/ui/appmenu/AppMenu.java:209
error: chrome/browser/ui/android/appmenu/internal/java/src/org/chromium/chrome/browser/ui/appmenu/AppMenu.java: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/ui/browser.h
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/ui/browser.h:677
error: chrome/browser/ui/browser.h: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/ui/views/bookmarks/bookmark_bubble_view.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/ui/views/bookmarks/bookmark_bubble_view.cc:227
error: chrome/browser/ui/views/bookmarks/bookmark_bubble_view.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/ui/views/extensions/extension_popup.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/ui/views/extensions/extension_popup.cc:68
error: chrome/browser/ui/views/extensions/extension_popup.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/ui/views/location_bar/location_bar_view.h
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/ui/views/location_bar/location_bar_view.h:227
error: chrome/browser/ui/views/location_bar/location_bar_view.h: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/browser/ui/views/permission_bubble/permission_prompt_bubble_view.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/browser/ui/views/permission_bubble/permission_prompt_bubble_view.cc:84
error: chrome/browser/ui/views/permission_bubble/permission_prompt_bubble_view.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
chrome/installer/mac/signing/signing.py
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: chrome/installer/mac/signing/signing.py:69
error: chrome/installer/mac/signing/signing.py: patch does not apply

---------------------------------------------------------------------------------------------------------------
components/browser_ui/site_settings/android/BUILD.gn
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: components/browser_ui/site_settings/android/BUILD.gn:213
error: components/browser_ui/site_settings/android/BUILD.gn: patch does not apply

---------------------------------------------------------------------------------------------------------------
components/infobars/core/infobar_delegate.h
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: components/infobars/core/infobar_delegate.h:169
error: components/infobars/core/infobar_delegate.h: patch does not apply

---------------------------------------------------------------------------------------------------------------
components/permissions/permission_request.h
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: components/permissions/permission_request.h:59
error: components/permissions/permission_request.h: patch does not apply

---------------------------------------------------------------------------------------------------------------
components/permissions/permission_uma_util.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: components/permissions/permission_uma_util.cc:644
error: components/permissions/permission_uma_util.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
components/sync_device_info/device_info.h
  - Patch applied because: No corresponding .patchinfo file was found.
  - Error - Program git exited with error code 1.
error: patch failed: components/sync_device_info/device_info.h:77
error: components/sync_device_info/device_info.h: patch does not apply

---------------------------------------------------------------------------------------------------------------
components/sync_device_info/device_info_sync_bridge.cc
  - Patch applied because: No corresponding .patchinfo file was found.
  - Error - Program git exited with error code 1.
error: patch failed: components/sync_device_info/device_info_sync_bridge.cc:173
error: components/sync_device_info/device_info_sync_bridge.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
components/vector_icons/vector_icons.gni
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: components/vector_icons/vector_icons.gni:42
error: components/vector_icons/vector_icons.gni: patch does not apply

---------------------------------------------------------------------------------------------------------------
content/browser/renderer_host/navigation_controller_impl.cc
  - Patch applied because: No corresponding .patchinfo file was found.
  - Error - Program git exited with error code 1.
error: content/browser/renderer_host/navigation_controller_impl.cc: No such file or directory

---------------------------------------------------------------------------------------------------------------
content/browser/renderer_host/navigation_request.cc
  - Patch applied because: No corresponding .patchinfo file was found.
  - Error - Program git exited with error code 1.
error: content/browser/renderer_host/navigation_request.cc: No such file or directory

---------------------------------------------------------------------------------------------------------------
extensions/browser/extension_event_histogram_value.h
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: extensions/browser/extension_event_histogram_value.h:483
error: extensions/browser/extension_event_histogram_value.h: patch does not apply

---------------------------------------------------------------------------------------------------------------
media/blink/key_system_config_selector.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: media/blink/key_system_config_selector.cc:908
error: media/blink/key_system_config_selector.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
third_party/blink/renderer/modules/BUILD.gn
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: third_party/blink/renderer/modules/BUILD.gn:166
error: third_party/blink/renderer/modules/BUILD.gn: patch does not apply

---------------------------------------------------------------------------------------------------------------
third_party/blink/renderer/modules/mediastream/media_devices.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: third_party/blink/renderer/modules/mediastream/media_devices.cc:353
error: third_party/blink/renderer/modules/mediastream/media_devices.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 1.
error: patch failed: third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc:3596
error: third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc: patch does not apply

---------------------------------------------------------------------------------------------------------------
tools/metrics/histograms/histograms_xml/histogram_suffixes_list.xml
  - Patch applied because: No corresponding .patchinfo file was found.
  - Error - Program git exited with error code 1.
error: tools/metrics/histograms/histograms_xml/histogram_suffixes_list.xml: No such file or directory

---------------------------------------------------------------------------------------------------------------
Done applying patches.
Exiting as not all patches were successful!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-core@1.18.43 sync: `node ./build/commands/scripts/sync.js "--init"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave-core@1.18.43 sync script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jafxdesign** [comment]
I used the new Mac OS to start the cloning afresh 

Done: git clone git@github.com:brave/brave-browser.git
Done: cd brave-browser
Done: npm install

When I run the following command I get a new error this time with progress
npm run init

Compiling ryu v1.0.5
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/user/WebProjects/strat/brave-browser/src/brave/build/rustup/0.1.5/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib"

etc.....

**Comment by bsclifton** [comment]
@jafxdesign you're going to want to update both `brave-browser` and `brave-core` to latest before running `npm run init`. The Chromium versions need to be the same in order for the patches we have to apply. You can check the Chromium version being used in `package.json` under `brave-browser` and verify this against what is being used in your `src/` directory

We do updates often, so it's quite easy to get out of date. The best approach would be to branch/fork both `brave-browser` and `brave-core` at the same time so that you don't need to rebase constantly (until you're finished with your patch or whatever you're working through - then you will want to rebase both)
