### ISSUE TITLE
[Widget] Dropdown order is changed everytime a token is selected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12689]
## Description 
Dropdown order is changed everytime a token is selected

## Steps to reproduce 

   1. Connect to Binance widget
   2. Select Convert view
   3. Select a token from dropdown, remember the other tokens position
   4. Select a second token from the previous view, order is changed

## Actual result 
Dropdown order is changed everytime a token is selected

## Expected result
Order of list items should remain same

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone/Tablet
   - Android version:10
   
## Brave version
1.17.68

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by deeppandya** [comment]
This issue is irrelevant as we removed the widget from NTP.
