### ISSUE TITLE
Reduce length of welcome experience

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#12680]
## Description 
We need to put import on the first screen, update the copy, and reduce length of onboarding to maximize user completion.

## Design for Windows, macOS, and Linux

The browser then launches with the welcome experience with improved ordering and consistent visuals.

![2021-08-31 17-33-16 2021-08-31 17_34_40](https://user-images.githubusercontent.com/2388823/131593218-b04fe1a3-cae4-484b-a0cc-138e135e0851.gif)

"privacy preserving product analytics" links to `https://brave.com/privacy-preserving-product-analytics-p3a/`
"Disable" links to `brave://settings/privacy`

## Assets
Figma: https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/?node-id=2101%3A405

**Comment by karenkliu** [comment]
@aekeus or @keur Can you advise if the above designs are feasible?

**Comment by simonhong** [comment]
AFAIK, making default with installer is difficult on Windows.
Because of this, I assume chrome download page also doesn't have `make default` checkbox.
Needs more advice from @bsclifton

**Comment by diracdeltas** [comment]
@karenkliu if a user doesn't download Brave from the download page (ex: they're directly sent a link to the installer, or they install it from github/etc.), will Brave behave as if none of those checkboxes were set?

**Comment by diracdeltas** [comment]
given my comment above, i don't think we should remove the p3a page from onboarding because not all Windows users are guaranteed to see the download page.

**Comment by bsclifton** [comment]
Windows doesn't have a first run welcome screen (including the `make default` checkbox) because Windows 10 doesn't let you change this via the code. As @simonhong found out, the download page for Chromium (similar to what is proposed above) has stats auto-checked and then that value is passed through to the mini-installer.  We could do that for the antifraud checkbox, but we can't touch default browser (best we can do is present the `Defaults` control panel app in Windows, which lets users change their default apps)

I'd personally prefer keeping the P3A pref where it's at. Another challenge would be propagating the checkbox values on this download page to macOS (which doesn't use mini_installer; not sure if we can pass anything through to PKG or DMG)

**Comment by diracdeltas** [comment]
@karenkliu can we update these designs to remove the referral checkbox? my understanding is that this won't ship anyway until after the referral program is shut down in 5 days.

**Comment by karenkliu** [comment]
For Windows, it sounds like the download page is not a good place for these checkboxes since it can't pass the `make default` checkbox and the user could install Brave from somewhere other than the download. 

For MacOS, we'll use the `first_run` dialog to show these checkboxes so there's no need to worry about passing it from the download page. The MacOS issue is here: https://github.com/brave/brave-browser/issues/12679

We may have to differentiate Windows and MacOS to optimize setting Brave as the default since they treat this action differently. Unfortunately for Windows, the only improvements we can make there is shortening the welcome experience (import on first slide, etc.) and the more aggressive 'set default browser' dialog on 2nd launch: https://github.com/brave/brave-browser/issues/12203

I've updated the designs above to reflect this.

**Comment by karenkliu** [comment]
@PrivacyMatters Rafael wanted your input on the updated P3A text in the Brave Shields slide. WDYT?
![image](https://user-images.githubusercontent.com/2388823/99729546-ef551880-2a6f-11eb-80db-39d49eaf3256.png)

**Comment by PrivacyMatters** [comment]
Hi @karenkliu I'm not certain what page the hyperlinked text leads to. But I've reviewed the section in the privacy policy over https://brave.com/privacy/browser/ and that links to  
![image](https://user-images.githubusercontent.com/41578351/99823314-24369d80-2b4c-11eb-8e12-fc4e4777f84a.png) 

This is probably too long but:
"We use completely anonymised privacy preserving product analytics to understand how the browser is used to help us improve it and better match the needs of our users. We genuinely don't want to know anything about you individually and the data is anonymous. You can turn off analytics in settings, Privacy and Security"

Hope that helps

pat

**Comment by karenkliu** [comment]
Thanks Pat!

The text is a bit long, here's what I got it shortened down to: 
![image](https://user-images.githubusercontent.com/2388823/99835057-e5d3bb00-2b18-11eb-800a-69035110bb4b.png)

We really shouldn't go longer than this as it's starting to make the fine print take up a bigger block than the main message of this slide - Brave Shields.

Let's keep linking to `https://brave.com/privacy-preserving-product-analytics-p3a/` as we did in the previous P3A notice since the Github wiki is kind of off-putting if you land there without being primed that the data is anonymised and Brave's reasons for collecting anonymised data.

**Comment by PrivacyMatters** [comment]
Hi Karen

Just a few comments. To me "Brave protects your privacy from Brave too" sends the wring message .. my privacy shouldn't need protecting from Brave given the privacy position on which the browser is built and promoted. I'd suggest losing that text unless user testing shows it has meaning for average users.

The reason suggested longer text, is that the use of 'analytics' is a competitive issue (& why Apple adopt an opt-in position though Firefox adopts opt-out https://support.mozilla.org/en-US/kb/share-data-mozilla-help-improve-firefox ) ... 

"We use anonymised privacy preserving product analytics to understand how the browser is used to help us improve it and make it better for our users. You can turn off analytics in settings, Privacy and Security"

Is that better?

**Comment by karenkliu** [comment]
Hi Pat - yes, this works much better, thanks! I've updated the designs.

**Comment by karenkliu** [comment]
Removed Yahoo from the search engine slide.

**Comment by rebron** [comment]
Closing as stale.
