### ISSUE TITLE
Card source and time duration should be aligned properly 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12688]
## Description 

Card source and time duration should be aligned properly 

## Steps to Reproduce

   1. Install nightly build
   2. Open Brave News
   3. Scroll till you find cards with a different title length

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/99059652-c677e380-2596-11eb-87ff-0ac03f9135d7.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/99059741-e14a5800-2596-11eb-8780-d55e1dca55a9.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.19.2 Chromium: 87.0.4280.49 (Official Build) nightly (64-bit)
-- | --
Revision | `f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @petemill @jamesmudgett @mattmcalister

**Comment by mattmcalister** [comment]
@nullhook we should get this merged and close it out
