### ISSUE TITLE
remove Bitcoin.com widget from NTP

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#12699]
## Description 

Remove Bitcoin.com from NTP card stack.

## Steps to Reproduce and Actual result:

See #11982

## Expected result:
Bitcoin.com should not appear on the NTP for new or existing users in all locales.

## Reproduces how often: 

n/a

## Brave version (brave://version info)

In 1.15.x and 1.16.x. Remove for Bitcoin.com for 1.17.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yess

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.17.70 Chromium: 87.0.4280.60 (Official Build) (64-bit)
-- | --
Revision | `12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}`
OS | Linux

- Verified BitCoin/Moonpay widget is removed from NTP card stack on clean install and upgrade
---------------
Verification passed on 

Brave | 1.17.70 Chromium: 87.0.4280.60 (Official Build) (64-bit)
-- | --
Revision | `12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}`
OS | Windows 10 OS Version 1809 (Build 17763.1518)

- Verified BitCoin/Moonpay widget is removed from NTP card stack on clean install and upgrade
---------------
Verification passed on 

Brave | 1.17.70 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | `12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified BitCoin/Moonpay widget is removed from NTP card stack on clean install and upgrade
------------

Need to reverify the NTP settings when https://github.com/brave/brave-browser/issues/12759 is fixed via https://github.com/brave/brave-core/pull/7183

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.17.71 Chromium: 87.0.4280.66 (Official Build) (64-bit)
-- | --
Revision | `fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}`
OS | Linux

- Verified BitCoin/Moonpay widget entry is removed from New Tab Page section under settings 
---------------
Verification passed on 

Brave | 1.17.71 Chromium: 87.0.4280.66 (Official Build) (64-bit)
-- | --
Revision | `fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}`
OS | Windows 10 OS Version 1809 (Build 17763.1518)

- Verified BitCoin/Moonpay widget entry is removed from New Tab Page section under settings 
---------------
Verification passed on 

Brave | 1.17.71 Chromium: 87.0.4280.66 (Official Build) (x86_64)
-- | --
Revision | `fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified BitCoin/Moonpay widget entry is removed from New Tab Page section under settings
