### ISSUE TITLE
[Widget] Incorrect state of widget

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12690]
## Description 
Incorrect state of widget

## Steps to reproduce 

   1. Install 1.17.68 build and connect to Binance
   2. Select Beta/Nightly during device authorisation screen       <img width=15 src=https://user-images.githubusercontent.com/17010094/99069779-ee6f4300-25a6-11eb-94ea-c3beac413f9a.png>

   3. Switches to Beta/Nightly and select `Always` 
   4. Switches to Beta/Nightly but browser crashes
   5. Uninstall Beta/Nightly whichever was selected in step 2
   6. Try to authorise the account on 1.17.68
   7. Keep the device idle for while with widget screen open 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/99070043-6fc6d580-25a7-11eb-9c6b-0a367de2ec2d.png)

## Expected result
Should either dismiss the widget if disconnected or even better should not disconnect the widget at all

## Issue reproduces how often 
No idea

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Maybe/Yes
- Can you reproduce this issue with the current Play Store Nightly version? Maybe/Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Tab A
   - Android version: 10
   
## Brave version
1.17.68 x64 RC build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@anthonypkeane @bbondy marking it as P1 and release blocking as selecting another browser for authentication would render the widget useless and cant be authorised. Believe the steps are accurate in which case this is a bad issue
cc: @ryanml

**Comment by deeppandya** [comment]
@srirambv i have fixed this issue by closing the bottom sheet if the binance widget is disconnected.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.70 x64 build
- Verified when no network is there the bottom sheet is dismissed and widget is disconnected
-----------
Verification passed on Samsung Tab A with Android 10 running 1.17.70 x64 build
- Verified when no network is there the bottom sheet is dismissed and widget is disconnected

**Comment by srirambv** [comment]
This issue is superseded by #12735  when caching will be introduced.
