### ISSUE TITLE
downloads bar should show the origin of the download

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#1269]
## Test plan
See https://github.com/brave/brave-core/pull/597

## Description
For parity with browser-laptop, when a file is downloaded it should show the origin of the download in the URL bar, preferably marking HTTP as insecure. https://github.com/brave/browser-laptop/issues/7468

**Comment by bsclifton** [comment]
Uplifted to 0.55.x 😄

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified scenarios from test plan: https://github.com/brave/brave-core/pull/597
* Scenario 3 did not produce desired results, logged https://github.com/brave/brave-browser/issues/1590 as follow up issue
