### ISSUE TITLE
Differentiate between Ad types on Ads History

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12692]
## Description 

Since NTP ads/SI are now counted in ad views (https://github.com/brave/brave-browser/issues/10488) and shown in the 7 day Ads History, it might be nice to differentiate between NTP SI views and the ad notification views. 

## Steps to Reproduce

   1. View NTP SI which is configured for ad views (w/ 1.17.68 launched with `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --rewards=staging=true --brave-ads-staging --use-dev-goupdater-url` for US locale)
   2. Confirm estimated pending rewards and ad notifications received this month increment as expected
   3. Open 7 day ad history

## Actual result:

Can't tell if ad viewed as an ad notification or NTP SI
<img width="951" alt="7 day view" src="https://user-images.githubusercontent.com/28145373/99091248-9f70e000-259d-11eb-8c83-5039f7cfb06e.png">

## Expected result:
Might be nice to tell between the different types of ad views

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.17.68 Chromium: 87.0.4280.49 (Official Build) (x86_64)
-- | --
Revision | f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS | macOS Version 10.14.6 (Build 18G6042)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @tmancey @jsecretan

**Comment by tmancey** [comment]
cc @codybanxs @Miyayes

**Comment by Miyayes** [comment]
Here are proposed labels per @lukemulks:

* Sponsored image
* Notification
* Display Ad

**Comment by tmancey** [comment]
Closing issue as stale, however making @Miyayes aware for future consideration
