### ISSUE TITLE
Refactor Rewards media publisher scripts to share common code

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#12698]
We should refactor the various Rewards media publisher Greaselion scripts to share more common code. For example, most of the `initScript` functions contain a lot of boiler plate that can be factored out into shared code. For another example, see comment made by @marshall here: https://github.com/brave/brave-site-specific-scripts/pull/28#discussion_r523123288

**Comment by Miyayes** [comment]
@emerick Is this still relevant? If not, you can "Close as not planned".

**Comment by emerick** [comment]
No, I'll close it out.
