### ISSUE TITLE
Facebook login button on Twitch.tv

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#12708]
## Description 
Blocking facebook login does not work on Twitch.tv

## Actual result:
![image](https://user-images.githubusercontent.com/19390797/99188013-21a60380-275a-11eb-9ff7-86b125f69fea.png)
![image](https://user-images.githubusercontent.com/19390797/99187832-2cac6400-2759-11eb-87f6-f99affa72885.png)

## Expected result:
facebook login button should be blocked.

## Reproduces how often: 
100%

## Brave version (brave://version info)
Version 1.18.41 Chromium: 87.0.4280.49 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ✔
- Can you reproduce this issue with the beta channel? ✔
- Can you reproduce this issue with the nightly channel? ✔

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ❌
- Does the issue resolve itself when disabling Brave Rewards? ❌
- Is the issue reproducible on the latest version of Chrome? ✔

**Comment by ryanbr** [comment]
Hey @TheAresjej  have you enabled `Facebook` in `brave://settings/shields` ? 

Can you also test in private window mode.

**Comment by TheAresjej** [comment]
Hi @ryanbr I don't really understand what you mean by enabled facebook in the shield settings. 😅 If I understand correctly, these settings work on a permission basis, so by turning them off, the buttons for logging in the pages should be blocked. 😄 - I checked in a private window and the effect is the same.

**Comment by bsclifton** [comment]
Similar to comment in https://github.com/brave/brave-browser/issues/12706 - is the Facebook button actually loading from facebook.com? You can check by opening the F12 dev tools and then going to network tab. You should see all the requests when you reload the page

**Comment by bsclifton** [comment]
OK I just verified on twitch.tv that this FB button is first party. ex: it's an SVG and div being served from twitch.tv, not facebook.com. We don't have a way to block this as there is not an automated way to block something like this ☹️

**Comment by TheAresjej** [comment]
What if we created a new list for brave adblock? 🤔
