### ISSUE TITLE
Facebook login button on GOG.COM

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#12706]
## Description 
Blocking facebook login does not work on gog.com

## Actual result:
![image](https://user-images.githubusercontent.com/19390797/99187818-169ea380-2759-11eb-8354-a960b33dfc6f.png)
![image](https://user-images.githubusercontent.com/19390797/99187832-2cac6400-2759-11eb-87f6-f99affa72885.png)

## Expected result:
facebook login button should be blocked.

## Reproduces how often: 
100%

## Brave version (brave://version info)
Version 1.18.41 Chromium: 87.0.4280.49 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ✔
- Can you reproduce this issue with the beta channel? ✔
- Can you reproduce this issue with the nightly channel? ✔

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ❌
- Does the issue resolve itself when disabling Brave Rewards? ❌
- Is the issue reproducible on the latest version of Chrome? ✔

**Comment by ryanbr** [comment]
Similar to the twitch issue. https://github.com/brave/brave-browser/issues/12708

If you're using Twitter, Facebook logins on any site. enable in `brave://settings/shields`

**Comment by TheAresjej** [comment]
The problem is that I don't use logging in through these services, that's why I disabled this option in the settings. Unfortunately, the login buttons are still available and in my opinion they shouldn't, because the description of their operation says that these options should be unlocked if someone uses them. 😋 @ryanbr

**Comment by bsclifton** [comment]
This is interesting - the buttons may show, but without the switch enabled I don't think it works. Because the screenshot shows the Facebook button being first party (ex: it's not loaded off facebook.com, is it?) I don't think there's a way to block showing it
