### ISSUE TITLE
CBS All Access showing anti-adblock warning

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#12705]
## Description 
Using the ad-supported version of CBS all access, will get a warning screen `https://www.cbs.com/`

## Steps to Reproduce

   1. Login to `cbs.com`
   2. Play back a video
   3. Wait 5-15 seconds, warning will show

## Actual result:

![image (5)](https://user-images.githubusercontent.com/1659004/99181727-453a6f80-2795-11eb-8b47-eeee6c5ef51a.png)

## Expected result:
Playback without issue.

## Brave version (brave://version info)
`Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
From uBO: https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L1934

Possibly related to `*$3p,script,redirect-rule=noopjs,domain=cbs.com`

**Comment by ryanbr** [comment]
@antonok-edm The anti-adblock doesn't show up in uBO, I'm guessing it is related to `*$3p,script,redirect-rule=noopjs,domain=cbs.com` in ubO/filters.txt

**Comment by bsclifton** [comment]
Verified this works great 😄👍
