### ISSUE TITLE
Misspelling on New Tab page

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#1271]
## Description 
One of the background images shows a picture of the French Senate. It is misspelled.

## Steps to Reproduce

   1. Create new tabs until image of the French Senate appears
   2. Note spelling in lower left

## Actual result:

Misspelled caption: "Paris: The Seant" 

## Expected result:

Expected text is "Paris: The Senate" 

## Reproduces how often: 
Any time that image is shown. 

## Brave version (chrome://version info)
0.55.6

### Reproducible on current release:
Yes, it does. This is a carry-over from browser-laptop.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

<img width="1189" alt="screen shot 2018-10-16 at 8 30 29 pm" src="https://user-images.githubusercontent.com/28145373/47054864-5a8ddb80-d182-11e8-844b-184006428050.png">
