### ISSUE TITLE
Ads does not reliably enable when activated from pop-up in rewards settings

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#12715]
## Description 
Ads does not reliably enable when activated from new opt-in pop-up in Preferences, see screen capture here: https://bravesoftware.slack.com/files/UM5GQEGBV/F01ECRT35V5/screen_recording_2020-11-16_at_09.45.24.mov

## Steps to Reproduce

   1. start latest Nightly with fresh profile
   2. go to rewards settings and click "Start using Brave rewards" 

## Actual result:

Ads switch not being enabled, but auto-contribute switch being enabled

## Expected result:
Ads switch being enabled, but auto-contribute switch being enabled

## Reproduces how often: 
intermittent on every 2nd to 3rd attempt

## Brave version (brave://version info)

Version 1.19.5 Chromium: 87.0.4280.49 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by zenparsing** [comment]
I believe that this issue is occurring because the ads service has not registered user pref listeners when the `kEnabled` ads pref is set to true as a result of the "Enable Rewards" button begin pressed.

- In `ads_service_impl.cc`, the `AdsServiceImpl` constructor calls `MaybeInitialize`, which performs `MigrateConfirmationsStateOnFileTaskRunner` on a separate task runner.
- When that task is complete, `AdsServiceImpl::Initialize` is called, which registers pref change listeners.
- If `AdsServiceImpl::SetEnabled` is called prior to `Initialize`, then the pref change will not be observed, and consequently `rewards_service_->CreateWallet` will not be called.

**Comment by btlechowski** [comment]
`QA/Blocked` as build > 1.18.68 is needed

**Comment by milan-dell** [comment]
0x8CAf09d760F807f6978508be11c0b14561cD6199
Sent from Yahoo Mail on Android 
 
  On št, dec 3, 2020 at 10:46, btlechowski<notifications@github.com> wrote:   



QA/Blocked as build > 1.18.68 is needed

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from https://github.com/brave/brave-core/pull/7276
Verified for Rewards Panel:
![image](https://user-images.githubusercontent.com/34715963/101598853-12347600-39f9-11eb-9346-2dc2ba844884.png)
![image](https://user-images.githubusercontent.com/34715963/101598882-1e203800-39f9-11eb-812b-a3f242b9dd98.png)
Verified for NTP:
![image](https://user-images.githubusercontent.com/34715963/101598958-3bed9d00-39f9-11eb-8fd6-4628c5a28ffd.png)
![image](https://user-images.githubusercontent.com/34715963/101598992-460f9b80-39f9-11eb-8dfa-96f165e62dce.png)
Verified for brave://rewards
![image](https://user-images.githubusercontent.com/34715963/101599055-64759700-39f9-11eb-9e0d-40054827136c.png)
![image](https://user-images.githubusercontent.com/34715963/101599081-71928600-39f9-11eb-9c05-6d92ae061e64.png)

Checked the logs for any errors
Verified on production and staging
