### ISSUE TITLE
Need text change for `Ad notifications received this month`

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12719]
## Description 

The text `Ad notifications received this month` needs to be renamed to `Ad received this month` 

As discussed with @tmancey For NTP SI we are not supposed to get Ad notification pop-ups in the browser as per the design, the text "notifications" may confuse the user hence this needs to be removed and rename the text to `Ad received this month` 

## Steps to Reproduce

 NA

## Actual result:

Need text change for `Ad notifications received this month`

## Expected result:

Remove "notifications" from  `Ad notifications received this month`
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.17.68 Chromium: 87.0.4280.49 (Official Build) (64-bit)
-- | --
Revision | f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @jsecretan @rebron

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 10` using `1.17.74 CR: 87.0.4280.67`

* ensured that `Ads received this month` is being used/displayed on a clean install
* ensured that  `Ads received this month` is being used after upgrading from `1.17.72 CR: 87.0.4280.66`

**`Clean Install`** | **`1.17.72 CR: 87.0.4280.66`** |  **`Updating to 1.17.74 CR: 87.0.4280.67`** |
-------------------|----------------------------------|------------------------------------------------|
![Screenshot_20201127-132840_Brave](https://user-images.githubusercontent.com/2602313/100478189-62860c80-30b8-11eb-8ff1-49ecb3f24ff0.jpg) | ![Screenshot_20201127-133651_Brave](https://user-images.githubusercontent.com/2602313/100478194-66b22a00-30b8-11eb-86a8-04246df256aa.jpg) | ![Screenshot_20201127-133734_Brave](https://user-images.githubusercontent.com/2602313/100478203-6b76de00-30b8-11eb-896f-201e342d8252.jpg)
