### ISSUE TITLE
poorly displayed web page perhaps due to the cosmetic filter

### ISSUE THREAD

**Issue by sviluppoSoftware** [brave/brave-browser#12710]
PLEASE USE THE TEMPLATE BELOW TO PROVIDE INFORMATION ABOUT THE ISSUE. 
INSUFFICIENT INFO WILL GET THE ISSUE CLOSED. IT WILL ONLY BE REOPENED AFTER SUFFICIENT INFO IS PROVIDED-->

## Description 

often a white space appears in the middle of the page, I tried to set adblock and fingerprint protection both at standard level then at aggressive level but the white space remains, the other settings I have kept default.

## Steps to Reproduce

   1. go to `https://www.3bmeteo.com/meteo/roma`
   2. choose the weather forecast of a next day (not the current one)
   3. click on the "ora per ora" button just below the number indicating the date of the chosen day
 

## Actual result:

white space appears in the middle of the page

## Expected result:
no white space should appears in the middle of the page

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave version: 1.16.75, 1.16.76, maybe earlier
OS version: Android 9
cpu 32bit

## Version/Channel Information:

stable chnnel, i don't know if appear on beta and nightly channels

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? i don't use Brave Rewards
- Is the issue reproducible on the latest version of Chrome? i don't know

## Miscellaneous Information:

![img](https://user-images.githubusercontent.com/14260912/99198023-30aaa700-2796-11eb-9dbe-552a4405cf9c.jpg)

**Comment by ryanbr** [comment]
Hey, @sviluppoSoftware  
Blank spaces are caused by lack of cosmetic/css filtering. We have open ticket for this. No ETA just yet

https://github.com/brave/brave-browser/issues/9955

**Comment by sviluppoSoftware** [comment]
> Hey, @sviluppoSoftware
> Blank spaces are caused by lack of cosmetic/css filtering. We have open ticket for this. No ETA just yet
> 
> #9955

Thank you for this info, if you prefer closed this issue it's ok for me.
