### ISSUE TITLE
Product listing not shown when adblock is enabled 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12712]
## Description 

Product listing not shown when adblock is enabled 

## Steps to Reproduce

   1. Visit `https://croma.com`
   2. Open any product category
   3. No product listing shown when adblock is enabled

## Actual result:

Adbblock (standard) Default | Adblock Off
-- | --
![image](https://user-images.githubusercontent.com/17010094/99217542-26a59a00-27d0-11eb-92ba-7fd7d61b6827.png) | ![image](https://user-images.githubusercontent.com/17010094/99217574-3cb35a80-27d0-11eb-84de-0acf7d6bee4b.png)

## Expected result:
List products without having to turn off adblocker

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.19.7 Chromium: 87.0.4280.60 (Official Build) nightly (64-bit)
-- | --
Revision | `12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/86af0a9ab8d61c73dae7eba07d514ce1aac33b02

Should help, will re-check this in 2 days to confirm

**Comment by srirambv** [comment]
This is fixed now
![image](https://user-images.githubusercontent.com/17010094/99504710-cea99780-2977-11eb-93b1-ffeb13120296.png)
