### ISSUE TITLE
Crash after update to macOS Big Sur.

### ISSUE THREAD

**Issue by cfjefferyhk** [brave/brave-browser#12711]
## Description 
Crash after update to macOS Big Sur.
Accidentally crashed when browsing.
Especially when trying to turn off the shields on and off.

## Steps to Reproduce
In my case, that will be hk.4px.com

   1. go to hk.4px.com
   2. tap on the brave icon in the Omnibox.
   3. turn off the shields by tapping the icon.

## Actual result:
Accidentally crashed.

## Expected result:
turn off the shields (ad blocks) and refresh the website.

## Reproduces how often: 
Every-time on hk.4px.com.

## Desktop Brave version:
Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (x86_64)

## Android Device details:
   - Install type (ARM, x86): 3.2 GHz 6-Core Intel Core i7
   - Device type (Phone, Tablet, Phablet): iMac (Retina 4K, 21.5-inch, 2019)

## Version/Channel Information:
current release.
don't know if the same issue appears on beta or nightly channel.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
A: no

- Does the issue resolve itself when disabling Brave Rewards? 
A: no

- Is the issue reproducible on the latest version of Chrome? 
A: chrome does not have brave shields.

<img width="475" alt="Screenshot 2020-11-16 at 13 33 51" src="https://user-images.githubusercontent.com/50868763/99216422-92a7f280-2810-11eb-962a-502e9640a39c.png">

**Comment by rebron** [comment]
I'm not seeing a crash with the following:

Brave | 1.18.51 Chromium: 87.0.4280.49 (Official Build) beta (x86_64)
-- | --
Revision | f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS | macOS Version 11.0.1 (Build 20B29)

or:

Brave | 1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 11.0.1 (Build 20B29)

**Comment by bsclifton** [comment]
Closing as stale since there haven't been any +1's or other reports

@cfjefferyhk if you're still using Brave, have you had any more crashes?
