### ISSUE TITLE
[Big Sur] Ad notifications are not auto-dismissed 

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#12725]
## Description 
Ad-notifications are not auto-dismissed. Need to explicitly click close to dismiss it.

## Steps to Reproduce
   1. Wait for an ad-notification
   2. Wait for the ad to be dismissed

## Actual result:
Does not dismiss

## Expected result:
Should dismiss without user interaction

## Reproduces how often: 
Intermittent

## Brave version (brave://version info)
1.16.76

## Version/Channel Information:
Stable/Release

**Comment by rebron** [comment]
cc: @tmancey

**Comment by jumde** [comment]
Just noticed that it takes ~2 mins for the notification to disappear, if this is expected feel free to close this issue. Thanks!

**Comment by tmancey** [comment]
@jumde This is expected, thanks I will close the issue
