### ISSUE TITLE
ScienceDirect.com freezing on Brave

### ISSUE THREAD

**Issue by HectorKroes** [brave/brave-browser#12722]
## Description 
Brave usually stop responding while browsing` https://www.sciencedirect.com/`, both on desktop and android cellphone - but in Firefox, Chrome and Edge it works just fine.

## Steps to Reproduce

   1. Access `https://www.sciencedirect.com/`
   2. Browse for a minute
   3. The site will then freeze and a message from Brave will appear

## Actual result:

![image](https://user-images.githubusercontent.com/62996060/99293089-e91d2d00-2820-11eb-8416-57f5faf264ec.png)

## Expected result:

No freezing when browsing the site.

## Reproduces how often: 

Easily reproducible for me, it has been happening for a few months almost every time I try accessing this site, and only in Brave.

## Desktop Brave version:

Brave | 1.16.76 Chromium: 86.0.4240.198 (Versão oficial) 64 bits
-- | --
Revisão | d8a506935fc2273cfbac5e5b629d74917d9119c7-refs/branch-heads/4240@{#1431}
SO | Windows 10 OS Version 2004 (Build 19041.630)
JavaScript | V8 8.6.395.25
Flash | 32.0.0.453 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_32_0_0_453.dll
Agente do usuário | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
Linha de comando | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=ReducedReferrerGranularity,PasswordImport,MixedContentSiteSetting,AutoupgradeMixedContent,PassiveMixedContentWarning,WinrtGeolocationImplementation,WebUIDarkMode,PrefetchPrivacyChanges,LegacyTLSEnforced,DnsOverHttps,OmniboxContextMenuShowFullUrls --disable-features=SafeBrowsingEnhancedProtection,TextFragmentAnchor,PrivacySettingsRedesign,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,NotificationTriggers,TabHoverCards,SmsReceiver,AutofillServerCommunication,PasswordCheck,VideoPlaybackQuality --flag-switches-begin --flag-switches-end
Caminho do executável | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Caminho de perfil | C:\Users\hecto\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variações | 5e3a236d-59e286d0

## Android Device details:
   - Install type: ARM
   - Device type: Phone
   - Android version: 9

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? The frequency diminishes, but it persists.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by ryanbr** [comment]
Can investigate, it'll be related to their port scanning of users.

**Comment by ryanbr** [comment]
It should be resolve on Brave Beta on the Desktop @HectorKroes   Still looking into options on mobile.

**Comment by ryanbr** [comment]
Give it 24-48hrs @HectorKroes performance on the site should be much better.

**Comment by ryanbr** [comment]
How is this looking @HectorKroes ? Also a fix coming into Brave Beta will also help with the performance.

**Comment by ryanbr** [comment]
Closing, seems to be working well, if it's not working re-open ticket @HectorKroes

**Comment by HectorKroes** [comment]
@ryanbr It's working much better now, thank you! 
And sorry for not responding earlier, I don't access GitHub that often.
