### ISSUE TITLE
top sites are not always re-added under "brave://newtab"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12739]
## Description 

Similar to #12378, sometimes websites are not being added to `Top Sites` under `brave://newtab`. However, you don't necessarily need to remove all the tiles before running into the issue. Simply removing a tile and attempting to load the same page again will more than often reproduce the issue.

Maybe this is expected? Perhaps there's some type of cool off period when you remove a website from top sites before it can get added again? @simonhong is there some type of mechanism where if you remove the website more than `[x]` amount of times, it won't get re-added?

## Steps to Reproduce

   1. launch  brave (`1.19.13 CR: 87.0.4280.60` in this instance)
   2. visit apple.com and brave.com in separate tabs
   3. remove one of them from `brave://newtab`
   4. load the one that you removed and open a new `brave://newtab`

If you repeat the above or similar combinations, you'll notice that sometimes the tile isn't being added.

## Actual result:

Example of issue occurring: https://drive.google.com/file/d/1YuBSTVIZksrSnH3x80MOnO55koWQSray/view?usp=sharing

## Expected result:

Websites should be added into `Top Sites` if there's still room under `brave://newtab`

## Reproduces how often: 

Pretty much 100% reproducible. Shouldn't take long to notice websites stop appearing under `brave://newtab`

## Brave version (brave://version info)

```
Brave | 1.19.13 Chromium: 87.0.4280.60 (Official Build) nightly (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.15.7 (Build 19H2)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @bsclifton @simonhong @rebron

**Comment by bsclifton** [comment]
I believe this is expected, @kjozwiak. Once you hit the top site tile, it won't show again. Other URLs from the same domain should populate though. If you can confirm this is the case we can close as `wontfix`. Only way to get back URL is to do the "restore all"

**Comment by rebron** [comment]
Closing as wontfix. Expected behavior when removing a site/page to not see it again. A clear of browsing data will reset top site behavior and will re-add a previously removed site/page too.

**Comment by kjozwiak** [comment]
BTW, for the above, sometimes they would appear, sometimes they wouldn't. So it's not a case of just "they won't appear after being removed" but more of "sometimes they'll re-appear after visiting the same link, sometimes they'll never appear again, sometimes they'll appear after a few days of missing".

Hoping the above gets resolved by https://github.com/brave/brave-browser/issues/7493.
