### ISSUE TITLE
unable to scroll

### ISSUE THREAD

**Issue by ristein** [brave/brave-browser#12734]
## Description 
I can't scroll after page finished loading on some websites: eg. vice.com, t-online.de

## Steps to reproduce 

   1. open one of those website
   2. 
   3. 

## Actual result 

no scrolling possible after loading
## Expected result
scrolling possible

## Issue reproduces how often 
easily

## Version/Channel Information:

only tested my version
- Can you reproduce this issue with the current Play Store version? //yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Oneplus 7 pro
   - Android version: 10, custom rom, rooted
   
## Brave version
Android Brave Version 1.16.76

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?   yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

when disabling shields, waiting for cookie-prompt and reenabling shields, problem is gone for that site

**Comment by ryanbr** [comment]
Hey @ristein 

I can investigate, does enabling Easylist Cookies in `brave://adblock` help?

**Comment by ristein** [comment]
@ryanbr 
yes, this fixes it.
can I keep this enabled?
![Screenshot_20201117-120522_Brave](https://user-images.githubusercontent.com/55446611/99382727-3ce55000-28cd-11eb-9a66-2137e4a880dd.png)

**Comment by ryanbr** [comment]
Sure @ristein   Which country are you testing from?

**Comment by ristein** [comment]
@ryanbr  I'm living in Germany

**Comment by ryanbr** [comment]
Thanks for the help @ristein It should work without needing Easylist Cookies. That said, you can still use Easylist Cookies. 

Will keep this open for the next few days to confirm.

**Comment by ristein** [comment]
thank you @ryanbr 
Do you mean, it will work after the next update?
It doesn't yet

**Comment by bsclifton** [comment]
@ristein yup! We upload new rules daily which the browser will fetch and update with 😄 Within 24 hours, a new version should roll out. Browser should check for updates periodically (every 30 mins?) but you can force the check by closing browser + re-opening

**Comment by ristein** [comment]
issue resolved. thank you
