### ISSUE TITLE
Google Earth Web black screen on macOS BigSur 11.0.1

### ISSUE THREAD

**Issue by camots** [brave/brave-browser#12731]
## Description 
In 1.16.72 under macOS 11.0.1 Big Sur, Google Earth Web page is not working -> black screen instead of globe showing up

## Steps to Reproduce

   1. open https://earth.google.com/web/@45.0599697,7.65921927,249.61635762a,3915.01063469d,35y,-127.39214196h,39.68034905t,0r
   
## Actual result:
Blank screen instead of globe showing up.

## Expected result:
The globe should be displayed!

## Reproduces how often: 

Can be reproduced 100%!

## Brave version (brave://version info)
Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? no

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? yes

**Comment by ryanbr** [comment]
Hey @camots  Fix is incoming to Brave Beta https://github.com/brave/brave-core/pull/7059

**Comment by MAXOUXAX** [comment]
Getting the same issue on Windows 👍

**Comment by rebron** [comment]
@MAXOUXAX and @camots Can you update to 1.17.73 and let us know if you're still having issues? We addressed this issue in 1.17.73.

**Comment by MAXOUXAX** [comment]
Seems like it's working again!
Thanks for the quick fix guys!

**Comment by rebron** [comment]
Closing per last comment.

**Comment by camots** [comment]
Yes it is working fine now!

Thank you very much.

 

Best regards
