### ISSUE TITLE
[Widget] Show network error message instead of disconnecting the widget

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12735]
## Description 
Its not ideal to always have the widget disconnected when there is no network. It would be more helpful if we just showed an error state for no network rather than disconnecting the widget altogether just because there is no network 

## Steps to reproduce 

   1. Connect to Binance widget
   2. Disconnect the network 
   3. Wait for 30sec, widget gets disconnected

## Actual result 
Widget disconnects if there is no network when 30sec ping happens

## Expected result
Have a network error state to indicate no network rather than disconnecting the widget

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.17.69/1.19.12

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc; @ryanml @jamesmudgett @anthonypkeane @bbondy

**Comment by deeppandya** [comment]
@srirambv what do we do for this scenario in desktop ?

**Comment by srirambv** [comment]
@deeppandya on desktop it does nothing. Data doesn't get refreshed, preview conversion fails with an error message. 
![image](https://user-images.githubusercontent.com/17010094/99472181-009f0780-2940-11eb-9bf0-855e3f50e02c.png)


Marking as release-blocking as per @jamesmudgett suggestion

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.71 x64 build
- Verified when the device is offline, tapping on the widget shows a connection error message
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99655007-0fc2aa00-2a53-11eb-9e18-78c63b23f2c4.png>

- Verified bottom sheet shows `Please check your network` message when the device is offline but the bottom sheet is opened
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99655087-2963f180-2a53-11eb-823d-33732bcc87be.png>
-----------------
Verification passed on Samsung Tab A with Android 10 running 1.17.71 x64 build
- Verified when the device is offline, tapping on the widget shows a connection error message
   <img width=400 src=https://user-images.githubusercontent.com/17010094/99657221-cc1d6f80-2a55-11eb-965e-67616f09ae89.png>

- Verified bottom sheet shows `Please check your network` message when the device is offline but the bottom sheet is opened
   <img width=400 src=https://user-images.githubusercontent.com/17010094/99657101-9d9f9480-2a55-11eb-9d6e-fadb098728e4.png>

**Comment by kjozwiak** [comment]
Adding `release-notes/exclude` as widgets went out via `1.17.x - Release #1`. Users weren't experiencing the above before.
