### ISSUE TITLE
[Widget] Add channel specific schema 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12758]
## Description 
Add channel specific schema 

## Steps to reproduce 

   1. Install Release/Beta/Nightly channels
   2. Connect to Binance widget on Nightly
   3. Shows other installed versions during authorisation view
   4. Select Beta/Release and select always, switches but never allows you to authorise nightly to connect to the widget
   5. Only way to connect is to uninstall other channels and try again

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/99519454-cfe3c000-2989-11eb-9866-105422e0ecbc.png>

## Expected result
Auto-authorise the correct channel when requested

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.17.70

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @bbondy @ryanml @deeppandya

**Comment by deeppandya** [comment]
@bbondy this issue is related to the conversation https://bravesoftware.slack.com/archives/CQUHQ0PM3/p1605827467429400. i feel it's important to address as we have several users on android with multiple brave applications.

**Comment by bbondy** [comment]
sounds good!

**Comment by deeppandya** [comment]
Closing this issue as it's irrelevant
