### ISSUE TITLE
Alt + Number to switch tabs on Windows

### ISSUE THREAD

**Issue by Azarattum** [brave/brave-browser#12765]
## Description 

When using Alt+[Number] combination browser tabs are not switching on Windows. I'm aware that you can do it with Ctrl, but it much less practical as it requires to move your hand further away. However, on Linux both Alt and Ctrl work perfectly fine in Brave. And lots of application supports Alt+Number switching in Windows. So, I don't get why it doesn't work properly.

## Steps to Reproduce

   1. Open Brave on Windows
   2. Open multiple tabs
   3. Try to switch with Alt+[Number]

## Actual result:

Nothing happens.

## Expected result:
Switching tabs to the appropriate number.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)
Revision | d8a506935fc2273cfbac5e5b629d74917d9119c7-refs/branch-heads/4240@{#1431}
OS | Windows 10 OS Version 1809 (Build 17763.1518)

**Comment by fallaciousreasoning** [comment]
Hey @Azarattum, does this still happen?

**Comment by fallaciousreasoning** [comment]
I'm going to close this as there's a workaround now, even though we aren't adding them by default @rebron

**Comment by Azarattum** [comment]
@fallaciousreasoning, thanks. I’m currently using my own workaround which is an [application aware keyboard remapper](https://github.com/houmain/keymapper) to simulate Ctrl keys when I push Alt in Brave. Also, you’ve said that they were deliberately not added. Is there any particular reason for that?

By the way, this complaint turned out to be pretty common, so I’ve even included the config for the program mentioned above in my custom windows build. [Here is the link](https://github.com/Azarattum/AbsoluteWindows/blob/339ca04f5895bb1d7298f92be58a9d660d8afe4c/Custom/Files/w11/x64/Windows/Keymapper/keymapper.conf#L70) in case somebody stumbles on this issue in the future.

**Comment by fallaciousreasoning** [comment]
I'm not sure - it actually comes from upstream Chromium. @rebron would you have any objections to adding the `Alt`+<0-9> shortcuts for changing tabs?
