### ISSUE TITLE
Refactor BraveRewards to use chrome::GetChannelName instead of brave::GetChannelName to remove layering violation

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12769]
`chrome::GetChannelName` should be passed to `RewardsServiceImpl` in the factory to eliminate this layering violation

**Comment by marshall** [comment]
Reference from an older PR: https://github.com/brave/brave-core/pull/5067#discussion_r526242544

**Comment by emerick** [comment]
@tmancey Is this issue still relevant? I can't find any reference to `GetChannelName` in the Rewards service anymore...

**Comment by tmancey** [comment]
@emerick Thanks. I will close this issue as brave::GetChannelName was moved when transitioning Confirmations from ledger to ads.
