### ISSUE TITLE
[Widgets] Add translations for Binance widget messages 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12767]
## Description 
Add translations for Binance widget messages 

## Actual result 
 <img width=400 src=https://user-images.githubusercontent.com/17010094/99521100-dffc9f00-298b-11eb-91f2-0f5f469185f5.png>

## Expected result
Should translate all text

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.17.70

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by rebron** [comment]
@srirambv to recheck if still an issue.

**Comment by srirambv** [comment]
Blocked on https://github.com/brave/brave-browser/issues/14805

**Comment by srirambv** [comment]
This is fixed on current release. Closing the issue
