### ISSUE TITLE
Different icon for file formats that open in Brave

### ISSUE THREAD

**Issue by luisfelipesdn12** [brave/brave-browser#12761]
## Description
File formats that open in Brave show as the same app icon, which is very confusing to the user. Update the file format icon with a Brave branded graphic that differs from the app icon.

Original description:
> Would be cool to have a different icon in the file manager when it's a PDF. This would make clear when the file is an HTML or a Brave Browser Shortcut and when the file is a PDF.

## Steps to Reproduce
1. Define the Brave as the main PDF opener.
2. Download some PDF file.
3. See that file on a file manager.

## Actual result:
The file icon is the same that would be at an HTML file or a Brave Browser shortcut.

![image](https://user-images.githubusercontent.com/2388823/100917259-c2e7c600-348b-11eb-9001-5556e0c41c43.png)

## Expected result:
All file formats that the user has set to open in Brave Browser shows as a different graphic:

![image](https://user-images.githubusercontent.com/2388823/100916821-23c2ce80-348b-11eb-9a66-e7f223a2bd67.png)

Figma: https://www.figma.com/file/rk2uCEox4s0q93HckXsEJ4/Illustrations-and-Device-Mockups?node-id=99%3A239

## Reproduces how often:
Easily reproduced.

## Brave version (brave://version info)
**Brave:** 1.16.76 Chromium: 86.0.4240.198 64 bits
**Revision:** d8a506935fc2273cfbac5e5b629d74917d9119c7-refs/branch-heads/4240@{#1431}
**SO:** Windows 10 OS Version 2004 (Build 19041.630)

**Comment by bsclifton** [comment]
This would be a great one to do; we could need to make icons for the .pdf handler. For example, Edge uses this for PDF (instead of the regular HTML icon). I think we'd need to register handlers for extensions we'd like an icon for (would need to look into that)
![image](https://user-images.githubusercontent.com/4733304/99707719-b148fc00-2a51-11eb-8b0d-c73e4c0c3a52.png)

cc: @karenkliu

**Comment by luisfelipesdn12** [comment]
### Look the Firefox approach:

![Firefox approach](https://i.imgur.com/jrQ3QUI.jpg)

### And in the Brave:

![Brave approach](https://i.imgur.com/oZv5k8M.jpg)

**Comment by karenkliu** [comment]
Design added!

**Comment by luisfelipesdn12** [comment]
Just a doubt: where in [**Brave Core**](https://github.com/brave/brave-core/) is defined the shortcut icon?

**Comment by bsclifton** [comment]
@luisfelipesdn12 I think they're located under https://github.com/brave/brave-core/tree/master/app/theme/brave (see `mac`, `win`, etc sub-directories)

**Comment by luisfelipesdn12** [comment]
> @luisfelipesdn12 I think they're located under https://github.com/brave/brave-core/tree/master/app/theme/brave (see `mac`, `win`, etc sub-directories)

Thank you! I was also trying to find the code where is defined the image for each extension.

**Comment by simonhong** [comment]
Documents about Windows default program - https://docs.microsoft.com/en-us/windows/win32/shell/default-programs

**Comment by simonhong** [comment]
@karenkliu I'm working on it now :)
I need another image file. Window's icon size should be 32x32.
and maybe we want to use different icon for different channel(stable, beta dev or nightly)?

**Comment by karenkliu** [comment]
@simonhong How's this for the 32x32 size? https://www.figma.com/file/rk2uCEox4s0q93HckXsEJ4/Illustrations-and-Device-Mockups?node-id=589%3A1220

I also updated the larger size so the shadow wouldn't be cut off when you export it: https://www.figma.com/file/rk2uCEox4s0q93HckXsEJ4/Illustrations-and-Device-Mockups?node-id=99%3A239

And I added icons for Release/Beta/Dev/Nightly!

**Comment by simonhong** [comment]
Added `OS/Windows` label because other platforms (macOS and linux) doesn't use default app's icon for file.

**Comment by luisfelipesdn12** [comment]
Awesome! Great work @karenkliu @simonhong I really appreciate :)
:tada:

**Comment by rebron** [comment]
@brave/legacy_qa Need an opinion/second look on icon clarity. Channel ones might be fuzzy on some resolutions.

**Comment by anudeep610** [comment]
Hello,
Is this feature added?
Because I don't see any change in the icon for pdf files

**Comment by simonhong** [comment]
@anudeep610 Which version/channel do you use?
This feature is currently available in beta channel(`1.28.x`).

**Comment by anudeep610** [comment]
@simonhong oh ok, I am using the latest stable version
By when can I see this update in the stable version?

**Comment by simonhong** [comment]
@anudeep610 According to our release schedule, `August 10, 2021` is target date.

**Comment by anudeep610** [comment]
@simonhong That's great 👍
Thanks for the info.

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.28.100 Chromium: 92.0.4515.115 (Official Build) beta (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Windows 10 OS Version 2009 (Build 22000.100)

Steps:
1. downloaded test `.svg` and `.pdf` files
2. confirmed they were set to `Microsoft Edge`
3. context-clicked the icons and chose `Properties`
4. set `Open With...` to `Brave Beta`
5. confirmed their icons changed to the new one
6. double-clicked each file to open
7. confirmed both files opened in `Brave Beta`
8. uninstalled `Brave Beta`
9. confirmed the file icons returned to their previous default opened of `Microsoft Edge`

example | example | example | example
----------|-----------|----------|----------
![pre-brave-icons](https://user-images.githubusercontent.com/387249/128085268-9125f6ed-e785-45c3-bcbd-f74f51e352e4.png) | ![brave-shortcut-icons](https://user-images.githubusercontent.com/387249/128085324-346e1223-c691-40b2-ba60-efabac6300a1.png) | ![icon-properties](https://user-images.githubusercontent.com/387249/128085542-6a5605c1-660e-46e4-bf54-65657c6016aa.png) | ![uninstalled-brave](https://user-images.githubusercontent.com/387249/128085330-61cf1fdf-a20e-4cfe-9930-b9961ac92b3f.png)

**Comment by Hachdog** [comment]
The 'alternative' icons for files opened with braves are very pixelated on my PC. Anything we can do to fix this?
![screenshot](https://user-images.githubusercontent.com/72262131/147857770-efb31da2-abbd-4434-bdbc-19e030020d0d.jpg)

**Comment by stephendonner** [comment]
> The 'alternative' icons for files opened with braves are very pixelated on my PC. Anything we can do to fix this? ![screenshot](https://user-images.githubusercontent.com/72262131/147857770-efb31da2-abbd-4434-bdbc-19e030020d0d.jpg)

Looks like they're lossy - please file a new issue and cross-reference it here; thanks!

**Comment by leguminosa** [comment]
my Brave version is very very recent, after 5 years or so from this thread, but why is my .pdf file still showing exactly same brave icons when set as default??

<img width="1884" height="928" alt="Image" src="https://github.com/user-attachments/assets/5372d660-6561-4f34-bb38-258bffe1adc0" />

before (set to firefox)

<img width="833" height="619" alt="Image" src="https://github.com/user-attachments/assets/3025e96e-97c7-4766-9c9c-e391d69d3029" />

after changed to brave

<img width="929" height="633" alt="Image" src="https://github.com/user-attachments/assets/5f4eacbe-9e60-4baa-aa66-2bf93aff50b9" />
