### ISSUE TITLE
disable Cache API in incognito/tor windows

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#12773]
for parity with Firefox. reported in https://hackerone.com/bugs?report_id=1034653&subject=brave.

note: i have not verified this on Android but presumably we want the behavior to be the same there.

**Comment by diracdeltas** [comment]
from @pes10k on slack:

> We could also, if i understand the issue correctly, just remove / farble / randomize navigator.storage.estimate too.  Then SW’s and the like could cache stuff as needed, without the global state risk navigator.storage.estimate introduces

**Comment by pes10k** [comment]
I think this can be closed and marked `closed/non-actionable`.  Firefox has re-implemented Cache API, and their concerns were around `navigator.storage.estimate` too, which are not addressed with @antonok-edm 's fix
