### ISSUE TITLE
Add link to Brave Together on New Tab Page

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#12776]
## Description 
On the NTP, there should be an icon for Brave Together
![image](https://user-images.githubusercontent.com/4733304/99595708-0e897280-29aa-11eb-8212-fee96c38967e.png)

This could be highlighted when new by using a flyout (see picture)

Clicking the link would open https://together.brave.com/widget in the same tab

cc: @jamesmudgett @jsecretan for anything I'm missing

**Comment by jamesmudgett** [comment]
[video-camera.svg.zip](https://github.com/brave/brave-browser/files/5563124/video-camera.svg.zip)

**Comment by petemill** [comment]
What are the rules for when the "flyout" appears? Or should it always appear until the user manually dismisses via the `X` icon?

**Comment by jsecretan** [comment]
Let's go with manual dismiss for now, thanks.

**Comment by petemill** [comment]
No p3a for the button click?

**Comment by jsecretan** [comment]
I wouldn't worry about it right now, we will have some basic info on conferences started from the Brave Together page.

**Comment by petemill** [comment]
Where should `Learn More` link to? The same https://together.brave.com/widget URL? I take it _not_ something like https://brave.com/privacy/browser/#brave-together...?

**Comment by jsecretan** [comment]
Hi @petemill let's just to go for https://www.brave.com/brave-together for now and I'll get it filled in before launch.

**Comment by petemill** [comment]
I merged https://github.com/brave/brave-core/pull/7532 but now realizing that maybe we don't want it to point to https://www.brave.com/brave-together since it's no longer has a "Learn More" link but a "Try it now" button. @jsecretan what do you think?

I've made https://github.com/brave/brave-core/pull/7548 which changes that button to point at the same https://together.brave.com/widget link. Let me know if you want to merge that, or an alternative.


![](https://user-images.githubusercontent.com/741836/103929181-c3e6c580-50d1-11eb-929f-78d431c9f4fd.gif)

**Comment by jsecretan** [comment]
Ah yes, please @petemill, let's just change that to the widget link now.  Thanks.

**Comment by LaurenWags** [comment]
@petemill @jsecretan @rebron what should QA follow for a test plan for this? I didn't see one in the PR - should we make sure that it looks like the screens on the PR or is there more to it? Marking as `QA/Blocked` until this is sorted 👍🏻

**Comment by jsecretan** [comment]
Sorry for the delay @LaurenWags but this is only tied to Beta/Nightly now right @petemill ?  If so, we can just do QA/No for now and revisit when we unmoor from nightly channels.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` and relabeling as `QA/No` due to https://github.com/brave/brave-browser/issues/13905 - please adjust if you disagree @rebron @bsclifton @kjozwiak
