### ISSUE TITLE
twitterTipsIconLabel displayed next to BAT icon in tweets in Twitter UI

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#12774]
## Description 

Occasionally, on the twitter website (twitter.com), a `twitterTipsIconLabel` will be displayed to the right of the BAT icon. A reload of the twitter website will fix the issue. It cannot be reproduced on demand, I don't know what causes it, but it happens from time to time.

## Steps to Reproduce

   1. Use twitter
   2. notice the `twitterTipsIconLabel` text to the right of the BAT icon

## Actual result:

This is a screenshot of the problem, it shows up just below someone's tweet:

![image](https://user-images.githubusercontent.com/6763301/99590325-6aec9200-29aa-11eb-9866-6abfda381d96.png)

## Reproduces how often: 

I don't know what exactly causes it to happen, I just notice it from time to time. Reloading the twitter website fixes it.

## Version/Channel Information:

Version 1.18.51 Chromium: 87.0.4280.49 (Official Build) beta (64-bit)

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? unsure
- Does the issue resolve itself when disabling Brave Rewards? Brave rewards is disabled (I don't use and have never enabled Brave rewards on this machine.)
- Is the issue reproducible on the latest version of Chrome? No

**Comment by LaurenWags** [comment]
hey @mbacchi 👋  this should be fixed with 1.18.56 and above per https://github.com/brave/brave-browser/issues/12350. Beta channel should get an update tomorrow with the fix. Let me know if it's still occurring for you once you get the update.

**Comment by mbacchi** [comment]
@LaurenWags I just noticed this again on the Beta channel:

`Version 1.18.63 Chromium: 87.0.4280.67 (Official Build) beta (64-bit)`

Here's a screenshot showing a tweet I posted yesterday for timeliness:

![image](https://user-images.githubusercontent.com/6763301/100762597-657f4680-33b1-11eb-82d3-412539e0d68c.png)

I have 2 Brave channels installed, but this is obviously related to the beta:

```
rpm -qa | grep brave
brave-browser-beta-1.18.63-1.x86_64
brave-keyring-1.8-1.noarch
brave-browser-1.17.73-1.x86_64
```

Feel free to reopen this if you like or the original #12350 if this can be substantiated in the wild.

**Comment by LaurenWags** [comment]
Unfortunately it seems as though the fix we put in place did not work. This one has been super difficult for me to reproduce/get any steps. If you happen to see a pattern please let us know - so far it's been reported on Twitter and Reddit, but GitHub could be affected as well. We're now tracking a fix with https://github.com/brave/brave-browser/issues/12900.

**Comment by mbacchi** [comment]
Thanks @LaurenWags, I figured that might be the case as I couldn't find any commonality as to when it occurred. I'll keep thinking about it and let you know in #12900.

**Comment by arunrajp96** [comment]
Same happens to me time to time !

**Comment by alexschrod** [comment]
![image](https://user-images.githubusercontent.com/767490/160531655-30f5423c-48b6-4028-a427-82908af725d3.png)
How is this marked as closed? It's still ongoing.

**Comment by LaurenWags** [comment]
@alexschrod we have a follow up issue - https://github.com/brave/brave-browser/issues/12900. Unfortunately this issue has been tough to reproduce on demand and is still being investigated for a fix.
