### ISSUE TITLE
[Desktop] Improved top site tiles on the New Tab Page

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12772]
Top site tiles on the New Tab Page were refactored as per https://github.com/brave/brave-core/pull/6584.

As a result, the following issues were resolved:
 - [Desktop] Top site behavior seems wrong / unpredictable. ([#11551](https://github.com/brave/brave-browser/issues/11551))
 - [Desktop] Top sites on New Tab Page are missing. ([#11500](https://github.com/brave/brave-browser/issues/11500))
 - Top/Pinned Sites Can't be Removed (Reappear after refresh). ([#9788](https://github.com/brave/brave-browser/issues/9788))
 - [Desktop] "Undo" delete of a top site tile does not restore the tile to its previous position. ([#9457](https://github.com/brave/brave-browser/issues/9457))

**Comment by SXMacdara** [comment]
@LaurenWags  I am hoping you are the right person to address about this. I guess I am unsure as to why this is closed. I have the latest version of Brave V1.17.73. Top Sites is not fixed. In this latest version you can't even pin or rearrange your Top Sites anymore. Whatever was done in the way of improvement didn't work. One of the problems overall was that pinned sites were disappearing.

**Comment by LaurenWags** [comment]
Hi @SXMacdara thanks for reaching out! So one of the changes with the group of issues referenced in the description above is that pinning tiles is no longer available. This is because we are working towards completely customizable top site tiles as part of https://github.com/brave/brave-browser/issues/7493. Unfortunately I don't have a set date for this functionality, but following that issue will provide additional information as it becomes available. Thanks!
