### ISSUE TITLE
Ephemeral storage should work when third-party cookies are blocked

### ISSUE THREAD

**Issue by mrobinson** [brave/brave-browser#12789]
Currently ephemeral storage is only used when third-party cookies are unblocked. This ticket addresses changing that behavior so that ephemeral storage is only used when:
 1. The ephemeral storage configuration flag is turned on.
 2. Ephemeral storage knows how to ephemerally store a particular type of storage.
 3. That storage is used in a third-party iframe.
 4. That storage would otherwise be blocked by storage settings (either through brave shield or via chromium content settings).

If any of these conditions is not true, ephemeral storage should not be used. If they are all true then storage should be allowed (unblocked) and the data stored should be given an ephemeral lifetime and be partitioned from non-ephemeral storage.

**Comment by stephendonner** [comment]
Verified **`FIXED`** using

Brave | 1.21.51 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2.1 (Build 20D74)

**Steps to verify:**

1. enabled ephemeral storage via `brave://flags`
<details>
<img width="1253" alt="enable-ephemeral" src="https://user-images.githubusercontent.com/387249/107806132-412dd780-6d1b-11eb-826f-27d6255da195.png">
</details>

2. loaded `https://dev-pages.brave.software/storage/ephemeral-storage.html`
3. clicked Start test
4. verified results matched Step 1: Initial Case example
<details>
<img width="1569" alt="step1" src="https://user-images.githubusercontent.com/387249/107805288-fcee0780-6d19-11eb-9570-d505aca6bd40.png">
</details>

5. clicked on `https://dev-pages.bravesoftware.com/storage/ephemeral-storage.html`
6. clicked Read Values
7. verified results matched Step 2: Remote Page, Same Session example
<details>
<img width="1194" alt="step2" src="https://user-images.githubusercontent.com/387249/107805897-ded4d700-6d1a-11eb-8536-b35764e7f626.png">
</details>

8. copied URL and opened new tab for `https://dev-pages.bravesoftware.com/storage/ephemeral-storage.html?storage-test=https%3A%2F%2Fdev-pages.brave.software%2Fstorage%2Fephemeral-storage.html%3A%3A0.11300688081960164&ephemeral-storage-setting=ON&cookie-blocking-setting=BLOCK_THIRD_PARTY`
9. verified results matched Step 3: Remote Page, New Session example
<details>
<img width="872" alt="step3" src="https://user-images.githubusercontent.com/387249/107805488-48a0b100-6d1a-11eb-97d9-c5edd19eb3a7.png">
</details>

10. clicked link in Step 4
11. clicked Read Values
12. verified results matched Step 4: This Page, Same Session Case example
<details>
<img width="951" alt="step4" src="https://user-images.githubusercontent.com/387249/107805348-198a3f80-6d1a-11eb-8f6b-53e772d15be0.png">
</details>

13. copied URL and opened new tab for `https://dev-pages.brave.software/storage/ephemeral-storage.html?storage-test=https%3A%2F%2Fdev-pages.brave.software%2Fstorage%2Fephemeral-storage.html%3A%3A0.11300688081960164&ephemeral-storage-setting=ON&cookie-blocking-setting=BLOCK_THIRD_PARTY`
14. clicked Read Values
15. verified results matched Step 5: This Page, Different Session
<details>
<img width="951" alt="step5" src="https://user-images.githubusercontent.com/387249/107805330-0ecfaa80-6d1a-11eb-85f5-e6f7d3c4b4ee.png">
</details>

16. closed all test tabs/windows but left unrelated tab/window open (do NOT quite Brave)
17. copied URL and opened new tab for `https://dev-pages.brave.software/storage/ephemeral-storage.html?storage-test=https%3A%2F%2Fdev-pages.brave.software%2Fstorage%2Fephemeral-storage.html%3A%3A0.11300688081960164&ephemeral-storage-setting=ON&cookie-blocking-setting=BLOCK_THIRD_PARTY`
18. clicked Read Values
19. verified results matched Step 6: New Page, Reset Session Case
<details>
<img width="1162" alt="step6" src="https://user-images.githubusercontent.com/387249/107805320-0aa38d00-6d1a-11eb-9ea9-6c885dbe0726.png">
</details>

20. clicked Reset Test
21. verified test values were reset
<details>
<img width="1277" alt="Screen Shot 2021-02-12 at 10 17 44 AM" src="https://user-images.githubusercontent.com/387249/107806337-94078f00-6d1b-11eb-9bdb-30e9b9b72251.png">
</details>

**Comment by srirambv** [comment]
Removing Android label as a follow up issue is logged #14437

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.71 x64 build
- Verified enabling Ephemeral storage flag and running through the test on `https://dev-pages.brave.software/storage/ephemeral-storage.html` worked as expected 
<details>
<summary>Step 1: Initial Case</summary>

![image](https://user-images.githubusercontent.com/17010094/109680585-8e5fd500-7b74-11eb-832e-6032c0ebef17.png)

</details>

<details>
<summary>Step 2: Remote Page, Same Session</summary>

![image](https://user-images.githubusercontent.com/17010094/109681393-53aa6c80-7b75-11eb-80d3-2397df78bbfe.png)

</details>

<details>
<summary>Step 3: Remote Page, New Session</summary>

![image](https://user-images.githubusercontent.com/17010094/109681368-4db48b80-7b75-11eb-8414-1b06b3290089.png)

</details>

<details>
<summary>Step 4: This Page, Same Session Case</summary>

![image](https://user-images.githubusercontent.com/17010094/109681635-94a28100-7b75-11eb-9388-e6faea553140.png)

</details>

<details>
<summary>Step 5: This Page, Different Session</summary>

![image](https://user-images.githubusercontent.com/17010094/109682186-15fa1380-7b76-11eb-8aa6-fe85a526659c.png)

</details>

<details>
<summary>Step 6: New Page, Reset Session Case</summary>

![image](https://user-images.githubusercontent.com/17010094/109682145-0b3f7e80-7b76-11eb-8e83-b814fb8ba561.png)

</details>

<details>
<summary>Step 7: Clean Up</summary>

![image](https://user-images.githubusercontent.com/17010094/109682224-1d212180-7b76-11eb-9a35-45808a686f4f.png)

</details>
