### ISSUE TITLE
Open any links from gmail or slack via Brave is causing the crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12785]
## Description 
Open any links from gmail or slack via Brave is causing the crash

## Steps to reproduce 

   1. Clean profile `1.17.71`
   2. Open link from Gmail or slack via Brave
   3. Brave crashes
  

## Actual result 
Crash

## Expected result
No crash

## Issue reproduces how often 

Always
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? **Yes** 1.18.57 CR 87.0.4280.66
- Can you reproduce this issue with the current Play Store Nightly version? **Yes** 1.19.16 CR 87.0.4280.66

## Device details
   - Install type (ARM, x86): ARM 5.1.1
   - Device type (Phone, Tablet, Phablet): Gionee 5.1
   - Android version: 5.1
## Brave version

1.17.71
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @anthonypkeane @SergeyZhukovsky @samartnik

**Comment by LaurenWags** [comment]
Reproduced on LG Nexus 5 with Android 5.1 running 1.17.71 Bravearm.apk. Doesn't matter if Brave is open in the background or not.

Steps:
1. Clean profile 1.17.71 (so Custom Tabs are enabled in settings)
2. Leave Brave open in background or not, doesn't matter
3. Open Slack
4. Find a link
5. Tap on it, when prompted to choose browser, I chose Brave
6. Link starts to open and then crash

Note, does not occur if I choose Chrome in step 5 instead.
Also, if in step 1 I go into Settings > Open tabs in Custom Tabs > toggle off, crash does not occur for me.

**Comment by LaurenWags** [comment]
Also reproduces on Asus Zenfone (x86) with Android 6.0 running 1.17.71 Bravex86.apk. Used same steps as above.

**Comment by btlechowski** [comment]
Does not crash on Brave v1.17.71 on Samsung Galaxy Tab S5e (Android 9.0)

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.17.72 Bravex86.apk
- Verified STR from description and from https://github.com/brave/brave-browser/issues/12785#issuecomment-730352801
- Confirmed no crash with default settings (Custom tabs on) and opening a link in a custom tab from Slack/Gmail
- Confirmed no crash when disabling Custom tabs and opening a link from Slack/Gmail

------------

Verification passed on LG Nexus 5 with Android 5.1 running 1.17.72 Bravearm.apk
- Verified STR from description and from https://github.com/brave/brave-browser/issues/12785#issuecomment-730352801
- Confirmed no crash with default settings (Custom tabs on) and opening a link in a custom tab from Slack
- Confirmed no crash when disabling Custom tabs and opening a link from Slack

----------
