### ISSUE TITLE
Open link in browser via custom tabs causes menu to show on top and bottom 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12784]
## Description 
Open link in browser via custom tabs causes menu to show on top and bottom 

## Steps to reproduce 

   1. Open a link in custom tab
   2. Open menu and click open link in browser
   3. Switches to browser, has both top and bottom menu

## Actual result 
https://bravesoftware.slack.com/archives/C0816QH3R/p1605787228433900
![customtabs](https://user-images.githubusercontent.com/17010094/99664205-bca32400-2a5f-11eb-85da-20e97f567398.gif)

## Expected result
Should not cause menu to show up in both places

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone 
   - Android version: 10
   
## Brave version
1.17.71

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by btlechowski** [comment]
Verification passed on Brave v1.17.74 on Samsung Galaxy Tab S5e (Android 9.0). 
- Verified that the issue does not reproduce on Tablet.
