### ISSUE TITLE
Autoplay will have ask prompt if global content setting is toggled

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#12795]
## Steps to Reproduce

   1. Visit `brave://settings/content/autoplay`
   2. Toggle the label from "Allowed"=>"Blocked" and then "Blocked"=>"Allowed
   3. Visit https://www.youtube.com/
   4. The prompt shows up

## Actual result:

<img width="317" alt="Screen Shot 2020-11-19 at 10 13 48" src="https://user-images.githubusercontent.com/11330831/99706496-01bf5a00-2a50-11eb-9446-243092cd281b.png">

## Expected result:
There shouldn't be any prompt when content setting can only be set to block or allow

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.61 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the STR from the description
