### ISSUE TITLE
Crash in plugins farbling

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#12797]
```
[ 00 ] brave::FarblePlugins(blink::DOMPluginArray*, blink::HeapVector<blink::Member<blink::DOMPlugin>, 0u>*)
[ 01 ] blink::DOMPluginArray::UpdatePluginData()
[ 02 ] blink::NavigatorPlugins::plugins(blink::LocalFrame*) const
[ 03 ] blink::(anonymous namespace)::PluginsAttributeGetCallback(v8::FunctionCallbackInfo<v8::Value> const&)
[ 04 ] Builtins_CallApiCallback
```

https://brave.sp.backtrace.io/p/brave/debug?time=all&filters=((callstack%2Ccontains%2Cbrave%3A%3AFarblePlugins))&debug=(bcafcd,0,0)

**Comment by pes10k** [comment]
Just checking, is this still an open issue @pilgrim-brave @iefremov ?

**Comment by iefremov** [comment]
yes, we have it in 89.1.24.11 https://brave.sp.backtrace.io/p/brave/explore?time=all&filters=((callstack%2Ccontains%2Cbrave%3A%3AFarblePlugins))&sort=(ver%2Chead%2Cdesc)&aggregations=((ver%2Chead)%2C(callstack%2Chead))&

**Comment by goodov** [comment]
looks like this is related https://github.com/brave/brave-core/pull/6472

**Comment by iefremov** [comment]
should be fixed here https://github.com/brave/brave-browser/issues/15145
