### ISSUE TITLE
Do not use ephemeral storage for third-party domains that block cookies with a domain override

### ISSUE THREAD

**Issue by mrobinson** [brave/brave-browser#12790]
In Chromium settings, it is possible to selectively block storage for specific domains. These domains should not be able to access ephemeral storage. This requires differentiating between storage that is blocked due to blocking third party cookies or storage that is blocked due to a domain override.

**Comment by pes10k** [comment]
@bridiver Is this good to close now?

**Comment by bridiver** [comment]
closed by https://github.com/brave/brave-core/pull/7647
