### ISSUE TITLE
Sometimes page loading bypasses Tor network

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#12800]
The page is loaded normally in Tor Window

This is not a regression

## Steps to Reproduce

1. Clean profile
1. Open Tor Window and immediately close it
1. Open Tor Window
1. Open check.torproject.org

Note: check the recording

![tor_fail](https://user-images.githubusercontent.com/34715963/99728390-acb82e00-2ab9-11eb-8775-1954ff69ec55.gif)

## Actual result:

Page bypasses Tor network
Page is loaded normally
![image](https://user-images.githubusercontent.com/34715963/99727854-d1f86c80-2ab8-11eb-8301-3523429f490c.png)

## Expected result:
Page is always loaded through Tor network

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Reproduced on

Brave | 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)
-- | --
Revision | d8a506935fc2273cfbac5e5b629d74917d9119c7-refs/branch-heads/4240@{#1431}
OS | Ubuntu 18.04 LTS
Tor | 1.0.12

Brave | 1.17.71 Chromium: 87.0.4280.66 (Official Build) (64-bit)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | Ubuntu 18.04 LTS
Tor | 1.0.12

Brave | 1.17.71 Chromium: 87.0.4280.66 (Official Build) (64-bit)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | Ubuntu 18.04 LTS
Tor | 1.0.15

cc @brave/legacy_qa @jumde @diracdeltas

**Comment by btlechowski** [comment]
Probably fixed by https://github.com/brave/brave-core/pull/7069
I was not able to reproduce on

Brave | 1.19.22 Chromium: 87.0.4280.66 (Official Build) nightly (64-bit)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | Ubuntu 18.04 LTS

Added it to 1.19.x milestone so it can be retested.

**Comment by LaurenWags** [comment]
Could not reproduce with below build and Tor dev component 1.0.15:

```
Brave | 1.19.24 Chromium: 87.0.4280.67 (Official Build) nightly (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6042)
```

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.55 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the STR from the description
