### ISSUE TITLE
[Android] App crashes when Tab Groups or Conditional Tab Strip are enabled

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#12809]
## Description 
App crashes when `Tab Groups` or `Conditional Tab Strip` are enabled from `brave://flags`. `Tab Groups` don't work with bottom toolbar, so in this case we just need to disable it. `Conditional Tab Strip` uses different bottom control and thus bottom toolbar should also be disabled.

## Steps to reproduce 

   1. Enable `Tab Groups` or `Conditional Tab Strip` from `brave://flags`.
   2. Exit app.
   3. Start app, it will crash.

## Actual result 
App crashes.

## Expected result
No crash and no bottom toolbar when `Tab Groups` or `Conditional Tab Strip` are enabled.

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet):
   - Android version: all
   
## Brave version
1.19.x, 1.18.x, 1.17.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.74  x64 build
- Verified enabling `Tab Groups` or `Conditional Tab Strip` from `brave://flags` doesn't crash the browser when relaunched
------------
Verification passed on Samsung Tab A with Android 10 running 1.17.74  x64 build
- Verified enabling `Tab Groups` or `Conditional Tab Strip` from `brave://flags` doesn't crash the browser when relaunched
