### ISSUE TITLE
Number formatting incorrect for Crypto.com widget

### ISSUE THREAD

**Issue by AlanBreck** [brave/brave-browser#12816]
## Description 

Number format is currently displaying for `en-IN` on details view.

## Steps to Reproduce

   1. Open Brave Beta
   2. Open new tab
   3. Focus Crypto.com widget
   4. Click through to details view on BTC
   5. Observe problem

## Actual result:

<img width="318" alt="Screen Shot 2020-11-20 at 12 54 55 PM" src="https://user-images.githubusercontent.com/1199820/99833112-9a78d700-2b2f-11eb-9763-0a4b078a6f07.png">

## Expected result:
<img width="321" alt="Screen Shot 2020-11-20 at 12 56 03 PM" src="https://user-images.githubusercontent.com/1199820/99833223-c2683a80-2b2f-11eb-8586-bcf8cada5da4.png">

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Linux

- Verified number formatting is as per expected design
![image](https://user-images.githubusercontent.com/17010094/103612057-86d8d280-4f1b-11eb-8f88-204c081fd5dc.png)
------
Verification passed on 

Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Windows 10 OS Version 2009 (Build 19042.685)

- Verified number formatting is as per expected design
![image](https://user-images.githubusercontent.com/17010094/103611743-cce16680-4f1a-11eb-8ab4-a68abee3f93e.png)
------
Verification passed on 

Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (x86_64)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified number formatting is as per expected design
![image](https://user-images.githubusercontent.com/17010094/103610485-3744d780-4f18-11eb-8c62-720b00f6a26c.png)
