### ISSUE TITLE
`VERIFY WALLET` button isn't functioning in the verify wallet modal popup.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12812]
## Description 

 `VERIFY WALLET` button isn't functioning in the verify wallet modal popup.

## Steps to Reproduce

   1. Clean profile `1.18.57` launch brave using staging flags
   2. Open an NTP 
   3. Click on the BR panel and observe the `Way to Go! Claim my Rewards` in the NTP
   4. Click on `Claim my Rewards` and clear the captcha test
   5. Click on BR panel and click on `X` in the `Earn Tokens & Give Back` in the panel
   6. Navigate to brave://rewards settings page by clicking on the `Rewards settings` in the BR panel
   7. Click on `Verify wallet` in the rewards settings page or BR panel
   8. Click on `VERIFY WALLET` button in the verify your wallet modal popup

## Actual result:

 `VERIFY WALLET` button isn't functioning in the verify wallet modal popup.

![image](https://user-images.githubusercontent.com/38657976/99806814-8dc2a600-2b64-11eb-8c97-f889f1ca88f7.png)

## Expected result:
`VERIFY WALLET` button should function in the verify wallet modal popup.

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.18.57 Chromium: 87.0.4280.66 (Official Build) beta (64-bit)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | Windows 10 OS Version 2004 (Build 19041.572)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

CC: @brave/legacy_qa @rebron @NejcZdovc @emerick @marshall

**Comment by emerick** [comment]
@zenparsing Looks like it could be related to onboarding, given that console error.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.65 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the STR from the description
