### ISSUE TITLE
Third-party HTTP images on HTTPS site don't get upgraded to HTTPS

### ISSUE THREAD

**Issue by dentistformyeye** [brave/brave-browser#12824]
## Description 

Third-party HTTP images embedded on an HTTPS site don't get upgraded, even though mixed content should be upgraded automatically.

## Steps to Reproduce

   1. Check brave://settings/content/insecureContent and verify that insecure content should be blocked.
![image](https://user-images.githubusercontent.com/51429646/99868053-17866980-2b8d-11eb-836e-ed1044de875e.png)

   2. Visit the website [https://www.eff.org/awards/pioneer/2008](https://www.eff.org/awards/pioneer/2008)
   3. Observe and click the location where a padlock should be in the omnibox.
   4. Hover the mouse cursor over an HTTP image displayed on the site and observe the lower left corner of the browser window. Click the image with shields off to confirm that visiting the image directly will happen through HTTPS.
   5. Click back to the first website. Turn shields back on. Click the Brave icon in the omnibox and click "Connections upgraded to HTTPS".

## Actual result:

Instead of a padlock, the browser displays a warning symbol and indicates that the page has HTTP images.
![image](https://user-images.githubusercontent.com/51429646/99867990-82837080-2b8c-11eb-8356-bc8df8a01bd4.png)

The images are linked as HTTP, but clicking one with shields down shows that they can be directly accessed using HTTPS.
![image](https://user-images.githubusercontent.com/51429646/99868025-cd9d8380-2b8c-11eb-86f9-8116545ab842.png)

![image](https://user-images.githubusercontent.com/51429646/99868221-86b08d80-2b8e-11eb-9eab-472ebe156511.png)

Brave still thinks the images have been upgraded to HTTPS.
![image](https://user-images.githubusercontent.com/51429646/99868043-fb82c800-2b8c-11eb-9f74-58c48302917a.png)

## Expected result:
The images are loaded through HTTPS. The omnibox displays the padlock. Clicking the padlock brings up the "Connection is secure" message.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.15.7 (Build 19H2)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Already disabled
- Is the issue reproducible on the latest version of Chrome? Haven't tried

## Miscellaneous Information:

I first encountered this on Brave version 1.15.76.

**Comment by ryanbr** [comment]
We rely on https everywhere for our rules. nothing specific for `eff.org`  But the reason why it's not showing as secure is due to the use of http:// still in use.

```
http://w2.eff.org/awards/pioneer/images/2008/pioneer08.gif
http://w2.eff.org/awards/pioneer/images/2008/tcho.gif
http://w2.eff.org/awards/pioneer/images/2008/mog.png
http://w2.eff.org/awards/pioneer/images/2008/threerings.png
http://w2.eff.org/awards/pioneer/images/2008/jibjab.png
http://eff.org/files/barracuda_logo.png
http://eff.org/files/atomic.logo_.jpg
```

I'll investigate with eff, see if they're aware of it.

**Comment by dentistformyeye** [comment]
My bad, I'd assumed that eff.org would be in the HTTPS Everywhere rules, but I should have checked. I've filed EFForg/https-everywhere#19798.

Since Brave accesses eff.org through HTTPS even with HTTPS Everywhere (both the Brave component and the extension) disabled, I'd expected mixed content to be [automatically upgraded](https://www.chromestatus.com/feature/4926989725073408). Is this a Chromium issue, then?

**Comment by diracdeltas** [comment]
cc @fmarier on the mixed content upgrade issue

**Comment by bsclifton** [comment]
I think this is a duplicate of https://github.com/brave/brave-browser/issues/10190

**Comment by dentistformyeye** [comment]
My bad, this does seem to be a duplicate.
