### ISSUE TITLE
brave://flags/#extensions-toolbar-menu missing in latest version

### ISSUE THREAD

**Issue by specter78** [brave/brave-browser#12823]
## Description 
`brave://flags/#extensions-toolbar-menu` flag is missing in latest version. (Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64))

I don't know whether it was removed by brave or chromium. But it was a nice feature to have.

Please add the feature.

**Comment by eljuno** [comment]
+1s from Community https://community.brave.com/t/extension-toolbar-menu-flag-missing-in-latest-build/182580?u=eljuno

**Comment by Sy0xFF** [comment]
+1

**Comment by bsclifton** [comment]
Thanks for the report; this was removed by Chromium. We have an issue captured which you can subscribe to asking for a way to re-add this functionality https://github.com/brave/brave-browser/issues/12721
