### ISSUE TITLE
Add support for media publishers in the panel

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1282]
## Steps to Reproduce

   1. go to youtube video
   2. open panel

## Actual result:

we display youtube as publisher

## Expected result:
we should display an actual publisher on the youtube and not youtube

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified with test plan from https://github.com/brave/brave-core/pull/699
* Encountered https://github.com/brave/brave-browser/issues/1814 when tried to test for Twitch

**Comment by kjozwiak** [comment]
@brave/legacy_qa have we worked with @evq to make sure that tips are actually going to the specified content creator on YT rather than YT itself?

**Comment by davidtemkin** [comment]
@kjozwiak Twitch has been separated out -- I didn't think this was on the table for .56. Going live with YT sooner is still a big improvement regardless.

**Comment by kjozwiak** [comment]
> @kjozwiak Twitch has been separated out -- I didn't think this was on the table for .56. Going live with YT sooner is still a big improvement regardless.

Thanks @davidtemkin! Agreed, having YT working is a big improvement. Just wanted to double check and make sure we were on the same page so there's no surprises once `0.56.x` goes out the door 👍

**Comment by jnki** [comment]
i have just updated to Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)

there is still no way to tip directly to publisher for me.

this is all that shows up in the panel:
![image](https://user-images.githubusercontent.com/17442109/48281874-ed532a80-e44f-11e8-955c-51ada2da0b10.png)

**Comment by NejcZdovc** [comment]
@jnki on which url?

**Comment by kjozwiak** [comment]
@jnki as @NejcZdovc mentioned, providing a URL would be super helpful so we can check and see if we can reproduce what you're seeing.

Are you seeing this on every YT channel? Does the same issue happen when you try it again in a new tab or window?

**Comment by jnki** [comment]
If I go to youtube.com, the panel looks like this:
![image](https://user-images.githubusercontent.com/17442109/48290393-a32b7280-e46a-11e8-9112-be6b6c69f156.png)

If I go to any youtube video, or a [any youtube channel,](https://www.youtube.com/user/kiwioni) the panel looks like this:

![image](https://user-images.githubusercontent.com/17442109/48290457-d79f2e80-e46a-11e8-9624-e8537fa7e28d.png)

**Comment by kjozwiak** [comment]
@jnki is `Brave Rewards` disabled by any chance? If you visit `chrome://rewards`, is the switch `Off`?

![screen shot 2018-11-09 at 5 16 44 pm](https://user-images.githubusercontent.com/2602313/48291125-45376480-e443-11e8-9170-d4267fee9f7a.png)

If it's `Off`, you'll need to enable Rewards and you should start seeing the channels listed under the `Brave Rewards` panel.

**Comment by jnki** [comment]
Yup, it is already enabled

**Comment by kjozwiak** [comment]
> Yup, it is already enabled

Is `auto-contribution` disabled under `brave://rewards`? If you enable it, can you see channels appearing under the `Rewards` panel?

**Comment by jnki** [comment]
Auto contribution is enabled, all the sites i've visited visited since the previous build are still there.
(infact, i cannot exclude those sites... but that's a whole other issue).

**Comment by jnki** [comment]
i backed up my user profile and tried with a new one.
everything seems to work fine with the clean profile.

any chance i could get it to work on my current profile? i'd hate to lose all my settings
