### ISSUE TITLE
Fix format error in Brave Stats

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#12831]
## Description 
We have an issue with format in brave stats and this issue should address it. 

## Actual result 
![Screenshot_20201120-225157_copy_1080x1351](https://user-images.githubusercontent.com/5146988/99883218-ed1bc700-2bf3-11eb-8643-cd49134eb5bf.jpg)

## Expected result
Should show correct values

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version: Release
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Removed ` QA/Yes` and added `QA/No` after speaking with @deeppandya. Looks like we need ~1-2GB of `Saved Data` for the issue to reproduce which is very difficult to get manually. @deeppandya confirmed that the fix worked after manually editing the values on a local build.
