### ISSUE TITLE
Add exclude/include option to the panel

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1283]
## Steps to Reproduce

   1. 
   2. 
   3. 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/47593366-21552880-d945-11e8-9aab-bd547a2ee984.png)
