### ISSUE TITLE
bug fix from play store logs

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#12834]
## Description 
We noticed couple of null pointer exception in the play store logs. This issues address it.
Below are the links : 
https://play.google.com/console/u/0/developers/7093250338202488249/app/4972971274345155806/vitals/crashes/bf0bdc53/details?installedFrom=PLAY_STORE&days=30&versionCode=411707211%2C411707221%2C411707226%2C411707223%2C411707220%2C411707210
https://play.google.com/console/u/0/developers/7093250338202488249/app/4972971274345155806/vitals/crashes/775303ed/details?installedFrom=PLAY_STORE&days=30&versionCode=411707211%2C411707221%2C411707226%2C411707223%2C411707220%2C411707210
https://play.google.com/console/u/0/developers/7093250338202488249/app/4972971274345155806/vitals/crashes/fdbdeaed/details?installedFrom=PLAY_STORE&days=30&versionCode=411707211%2C411707221%2C411707226%2C411707223%2C411707220%2C411707210

**Comment by deeppandya** [comment]
Fixed in https://github.com/brave/brave-core/pull/7225

**Comment by kjozwiak** [comment]
@deeppandya do you know when the crash was happening? Visiting websites? Interacting with rewards? Interacting with UI? We usually try adding any crash fixes into the release notes so need some context.

**Comment by deeppandya** [comment]
@kjozwiak these logs are from play store. So it may not crash for us. There may be some edge cases so I added a fix to avoid it as well.

**Comment by deeppandya** [comment]
There was one minor issue on some devices, when you open-close brave stats, it used to crash.

**Comment by kjozwiak** [comment]
Thanks @deeppandya, so something along the lines of the following should work for the release notes?

```
- Fixed crash when opening and closing Brave stats in certain cases
```

**Comment by deeppandya** [comment]
@kjozwiak may be you can just mention about stability in privacy reports. Or bug fixes in privacy report
