### ISSUE TITLE
With BG images off, there are only 4 visible top sites instead of 8

### ISSUE THREAD

**Issue by newuser-web** [brave/brave-browser#12837]
## Updated issue description (by @bsclifton)
Timeline
- Sponsored images was introduced in February this year ([code merged 4 Feb 2020 to old android-tabs repo](https://github.com/brave/browser-android-tabs/pull/2490)). This reduced number of top sites shown by default to 4. User could turn off background images and see the full 8
- Version 1.17 (made live on Google Play store 19 Nov 2020) made top sites into a widget style control (other options being NTP stats and Binance). Even with background images disabled, user can only see 4 (because of the widget style control limitation).

## Original issue description
I was having 8 frequently viewed websites on the screen when background image was turned off. Now after 1.17.72 update it is restricted to 4.

**Comment by bsclifton** [comment]
Reported incidents:
- [I hate this new widget. I don't use rewards or anything similar. Give me back my old homepage with just top sites. Damn.](https://www.reddit.com/r/brave_browser/comments/jxlqdh/i_hate_this_new_widget_i_dont_use_rewards_or/)
- [Brave did it again: Another update nobody asked for to generate negative feedback from frustrated users who will go ignored by Brave staff yet once again](https://www.reddit.com/r/brave_browser/comments/jyjpon/brave_did_it_again_another_update_nobody_asked/)
- [Does anyone have any idea about this crap Brave did with mobile?](https://www.reddit.com/r/brave_browser/comments/jz5cc0/does_anyone_have_any_idea_about_this_crap_brave/)
- [Your latest Android update is not good. I was having 8 most viewed sites previously when background image was turned off. Now it is restricted to 4.](https://twitter.com/jjha02726051/status/1330334963233787904?s=21)

**Comment by aaronsantamaria** [comment]
+1 
https://community.brave.com/t/hate-new-widget-for-top-sites/182427

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.17.74 x64 build
- Verified disabling bg images and widgets shows stats and 2 rows of toptiles
  <img widht=400 src=https://user-images.githubusercontent.com/17010094/100431732-7b7ac780-3090-11eb-8790-9cdb5c1c0e6b.png>

----------

Verification passed on OnePlus 6T with Android 10 running 1.17.74 x64 build
- Verified disabling bg images and widgets shows stats and 2 rows of toptiles
  <img widht=300 src=https://user-images.githubusercontent.com/17010094/100431749-7fa6e500-3090-11eb-9aa7-92ba9271636f.png>

**Comment by newuser-web** [comment]
I'm using version 1.17.74 but 8 top sites are not visible

**Comment by srirambv** [comment]
@newuser-web works fine. Maybe just takes a bit of time to get the list populated.
![image](https://user-images.githubusercontent.com/17010094/100586774-8da27300-32e7-11eb-9f50-30461de6c308.png)


How many do you see? Can you add a screenshot?

**Comment by newuser-web** [comment]
Only 4
![Screenshot_2020-11-30-14-31-52-381_com brave browser](https://user-images.githubusercontent.com/67158882/100589399-108ff180-3319-11eb-840f-5ea448318fad.jpg)

**Comment by srirambv** [comment]
@newuser-web You still have widgets enabled. You have to disable them to get 2 rows of tiles. Click on the 3 dot menu on widget and select remove widget make sure all of them are removed. Only then you will get full 8 tiles

**Comment by newuser-web** [comment]
Thanks

**Comment by l3ender** [comment]
I was able to get the top 8 sites showing after disabling background images, but as a new user to the browser it was not very intuitive to figure it out. I'm liking the browser, and look forward to future enhancements to add/customize widgets to give more flexibility on the new tab screen!
