### ISSUE TITLE
Fix failing test on Windows - BraveRewardsBrowserTest.ToggleAutoContribute

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1284]
Follow up from https://github.com/brave/brave-core/pull/465#pullrequestreview-157263236

**Comment by NejcZdovc** [comment]
if i am not mistaken @yrliou fixed all tests. If I am mistaken, please reopen

**Comment by jasonrsadler** [comment]
Reopening this as it is failing consistenly on Windows
