### ISSUE TITLE
`Earn Tokens & Give Back` modal popup is shown again in rewards settings page even after dismissing the modal from panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12848]
## Description 

Found while testing the PR https://github.com/brave/brave-core/pull/7210 in the nightly build 
`Earn Tokens & Give Back` modal popup is shown again in the rewards settings page even after dismissing the modal from the panel

## Steps to Reproduce

 1. Clean profile `1.19.27` launch brave using staging flags
 2. Open an NTP
 3. Click on the BR panel and observe the `Way to Go! Claim my Rewards` in the NTP
 4. Click on Claim my Rewards and clear the captcha test
 5. Click on BR panel and click on `X` in the `Earn Tokens & Give Back` in the panel
 6. Navigate to the brave://rewards settings page by clicking on the Rewards settings in the BR panel
 7. `Earn Tokens & Give Back` modal popup is shown again in the rewards settings page 

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/99938728-7535d400-2d8e-11eb-9f71-ad5695c723d7.png)

## Expected result:
`Earn Tokens & Give Back` modal popup should not be shown again in the rewards settings page 

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.19.27 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.572)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @zenparsing @emerick @marshall

**Comment by zenparsing** [comment]
This is expected behavior as of https://github.com/brave/brave-core/pull/7135 - the various onboarding entry points will track "onboarding dismissed" state independently.
