### ISSUE TITLE
www.advanscene.com  not show all pictures!!!

### ISSUE THREAD

**Issue by tee4341** [brave/brave-browser#12845]
www.advanscene.com  not show all pictures!!!
![GifMaker_lowquality11](https://user-images.githubusercontent.com/48321898/99910802-a7a9e780-2d22-11eb-8d1c-0d1312881d32.gif)

**Comment by ryanbr** [comment]
Hey @tee4341 

Just tested this.  (on a one-plus 6)
![Screenshot_20201123-230054](https://user-images.githubusercontent.com/1659004/99949889-a63ef480-2de0-11eb-86b6-c116e12a8c2d.jpg)

Images loaded okay, can you re-test with/without a vpn enabled also.

**Comment by tee4341** [comment]
it work fine come in from my link , but it not work com in google (I don't know anything,)
https://www.google.com/search?q=advancescen&oq=advan&aqs=chrome.0.69i59j69i57j69i61l3.7904j0j7&sourceid=chrome-mobile&ie=UTF-8

**Comment by dentistformyeye** [comment]
The images load properly when I access the website using HTTP. Here's what I see when I attempt to access the website using HTTPS.
![image](https://user-images.githubusercontent.com/51429646/100163757-60d40300-2e84-11eb-8f32-c340813b9c2a.png)


In the GIF that @tee4341 posted, the padlock flashes for a moment before the warning triangle appears, so I think Brave's HTTPS Everywhere upgrades any images served from the www.advanscene.com domain, such as the flag GIF ("real" image) that should be in the upper left. However, the website explicitly prohibits hotlinking when I attempt to directly access "real", first-party images and displays nothing when I attempt to directly access "fake" images regardless of whether I use HTTPS. I think the website mistakes the upgrade of first-party images to HTTPS for hotlinking. As for the image directly below the flag GIF, that's from a blocked third-party.


Directly accessing the flag GIF (HTTP). "Hotlinking" this works, oddly.
![image](https://user-images.githubusercontent.com/51429646/100164495-f9b74e00-2e85-11eb-980e-3d979a1e9644.png)

Attempting to directly access the flag GIF (HTTPS) causes a redirect
![image](https://user-images.githubusercontent.com/51429646/100164700-6af70100-2e86-11eb-850a-f64a1a313a9d.png)

"Fake" image (HTTPS) served from www.advanscene.com. Attempting to directly access the URL (HTTP or HTTPS) leads to a white screen (with no errors in the console).
![image](https://user-images.githubusercontent.com/51429646/100164181-5cf4b080-2e85-11eb-877e-5ee842ff2d6c.png)

**Comment by anthonypkeane** [comment]
Hi @tee4341 can you please re-check this on the latest version of Brave? Thanks

**Comment by dentistformyeye** [comment]
The images show up on HTTPS now. It was probably fixed as part of [#10190](https://github.com/brave/brave-browser/issues/10190#issuecomment-740360598).
