### ISSUE TITLE
Notify user when Brave Rewards user wallet verification exceeds linking limit

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#12855]
## Description 

Users can only link 4 browsers (Brave Rewards wallets) to a single Uphold account. This linking limit is a _lifetime_ limit, so even if previous browsers are disconnected or uninstalled, the slots have been consumed.

When a user tries to link a 5th, 6th, ... nth browser to their Uphold account, the server returns a specific error code indicating that the linking limit has already been exceeded, per @husobee. However, the Brave Rewards user interface currently does not react to this error message or indicate anything to the user, which often leads to confusion and support queries.

If a user has exceeded the linking limit, the wallet will still link to the browser (balances will still be queried from the Uphold account, Uphold-to-Uphold direct tips can still be made, etc.); **however, any existing BAT (virtual BAT) will not be transferred over to their Uphold account.** (This has led to many support requests, as the BAT appears "stuck" in the user's browser, and does not sync/transfer over to their Uphold account as they would expect.)

## Proposed Solution

When server returns this error, Brave Rewards UI should display a notice to the user telling them that their BAT will not be transferred over because they have exceeded the linking limit.

It would be ideal if this notice could persist, perhaps under a (?), so that it can be re-read by the user, and support can inquire into it if the user nevertheless files a support request. 

## Steps to Reproduce

   1. Have BAT in 5 or more browsers.
   2. Link all 5 browsers to a single Uphold account.
   3. Notice that the 5th browser's BAT doesn't transfer over to the Uphold account.
   4. Notice that no notice or error message is presented in the user interface. 

## Reproduces how often: 

100%

## Desktop Brave version:

All Brave versions up until this point.

**Comment by husobee** [comment]
Response Status Code 409 (Conflict) is indicative of a failed linking due to linking limit constraints on the following endpoints `/v3/wallet/<provider>/<payment id>/claim`

Where <provider> in "brave" or "uphold" and <payment id> is the user's wallet id.

**Comment by Miyayes** [comment]
+1 https://reddit.com/r/brave_browser/comments/k4b518/bat_stuck_in_wallet_never_available_in_uphold/ge9a2l5/?context=3

**Comment by tretasdolou** [comment]
may i suggest something?! u guys can reset the maximum number uphold account every year , then this can help avoid fraud and this things, and then every year if u change notebook or desktop or cellphone u can set up on your new devices , i think this suggestion is really good , think about it =) ty so much

**Comment by tretasdolou** [comment]
Hope this wallet maximum connection be ' fixed' soon and just let active wallet counting as connected the maximum can be 2 maximum connection wallet to receive the bats that go be amazing.

**Comment by Miyayes** [comment]
I think this is a subset of https://github.com/brave/brave-browser/issues/13151. So, I will close this one in favor of #13151, and adjust the latter's priority accordingly to P2 (as this is a P2).
