### ISSUE TITLE
Calling firebase functions fails with DOMException: Registration failed - push service error

### ISSUE THREAD

**Issue by rmcsharry** [brave/brave-browser#12850]
## Description 
Calling firebase functions fails with:

`DOMException: Registration failed - push service error`

## Steps to Reproduce

   1. Call any https firebase function
   2. Observe the error in the console

## Actual result:
The function is not called.

## Expected result:
The function is called.

## Reproduces how often: 
Every time we call any function.

## Brave version (brave://version info)

Brave | 1.16.76 Chromium: 86.0.4240.198 (Official Build) (x86_64)
-- | --
Revision | d8a506935fc2273cfbac5e5b629d74917d9119c7-refs/branch-heads/4240@{#1431}
OS | macOS Version 10.15.6 (Build 19G73)
JavaScript | V8 8.6.395.25
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

## Version/Channel Information:
I don't have other channels

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO - it works

## Miscellaneous Information:
Also works in Firefox.

**Comment by rebron** [comment]
@rmcsharry Can you go to brave://settings/privacy toggle this setting on 
<img width="706" alt="Screen Shot 2020-11-23 at 6 21 17 AM" src="https://user-images.githubusercontent.com/5951041/99973020-29fecf80-2d54-11eb-921a-f138bcb66d32.png">

Is it working for you after that?

**Comment by rebron** [comment]
Closing per last comment. Setting resolves this issue.
