### ISSUE TITLE
[Desktop] second Brave Rewards extension listed in Task Manager

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12858]
## Description 

Seems as though when you open the rewards panel a second Brave Rewards extension is listed in the Task Manager. This is not new with https://github.com/brave/brave-browser/issues/6462 and existed prior to making the extension non-persistent.

## Steps to Reproduce

   1. Clean profile
   2. Go to hamburger menu > More Tools > Task Manager
   3. Note that Brave Rewards extension is not listed
   4. Visit a site
   5. note that Brave Rewards extension is still not listed in Task Manager
   6. Click on BAT logo in URL bar --> two Brave Rewards Extension lines are in the Task Manager
   7. Close panel --> one goes away
   8. Reopen panel --> second Brave Rewards Extension gets listed again

## Actual result:

<img width="480" alt="Screen Shot 2020-11-23 at 11 36 57 AM" src="https://user-images.githubusercontent.com/28145373/99993715-10767b80-2d86-11eb-9b59-cf94e4ad5ce8.png">

## Expected result:
Just one Brave Rewards Extension in Task Manager

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6042)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 1.17.x 
- Can you reproduce this issue with the beta channel? yes 1.18.x
- Can you reproduce this issue with the nightly channel? yes 1.19.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by Miyayes** [comment]
Superseded by https://github.com/brave/brave-browser/issues/22423, which gets rid of extension.
