### ISSUE TITLE
Follow up of #12008 - Change wording for Safety Check

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12859]
## Description 

@fmarier comment from #11741 (comment)

## Steps to Reproduce

   1. Please refer #12008 and test plan https://github.com/brave/brave-core/pull/6892
    

## Actual result:

The updated text `Brave can help keep you safe from unsafe websites, bad extensions, and more` isn't shown for the Safety check 
![image](https://user-images.githubusercontent.com/38657976/99995186-07b29380-2de0-11eb-97b1-f11c2d616caa.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton @fmarier

**Comment by Saoiray** [comment]
@rebron I see you had movement here a bit ago. Not sure if should create a new issue or reply here, but wanted to point out an issue with current phrasing and setup for Safety Check UI.

If we go to `brave://settings/privacy` it will show `Safety Check` on the bottom. On mine, it mentioned something about Brave having password recommendations. 

![image](https://github.com/brave/brave-browser/assets/99627477/5e78f3c1-6991-4a87-9400-c9e76c3e81a3)

When I click on it, I'm taken to `brave://settings/safetyCheck` but then there's nothing said about passwords. 

![image](https://github.com/brave/brave-browser/assets/99627477/9e9355ac-2c72-41c1-aa38-d135b0c5ccf1)


I also want to point out that the links in the above screenshot need adjusted as well. For example:
![image](https://github.com/brave/brave-browser/assets/99627477/2fbbea36-91bb-42b7-854e-b4cefafded80)

Clicking on `Brave warns you` relays to https://support.brave.com/ which then redirected for me over to https://support.brave.com/hc/en-us  I would think it should go to a direct article.

In fact, all links on that page goes to that and doesn't actually show anything particular about what it's saying. 

![image](https://github.com/brave/brave-browser/assets/99627477/0f43ad23-317c-4815-8bd4-55d1b3b64c54)

**Comment by fmarier** [comment]
Closing since Safety Check has changed significantly in upstream Chromium. The warning from https://github.com/brave/brave-browser/issues/12859#issuecomment-2181636790 is tracked in https://github.com/brave/brave-browser/issues/39212.
