### ISSUE TITLE
Twitter like button is not blocked

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#12852]
## Description 
Twitter like button is not blocked on Github

## Steps to Reproduce

   1. open [link](https://github.com/Microsoft/microsoft-ui-xaml)
   2. scroll to description

## Actual result:
![image](https://user-images.githubusercontent.com/19390797/99958037-ea060f80-2d88-11eb-9bb0-0c7e118c4a42.png)

## Expected result:
the button should be blocked

## Reproduces how often: 
100%

## Brave version (brave://version info)
Version 1.19.26 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ✔
- Can you reproduce this issue with the beta channel? ✔
- Can you reproduce this issue with the nightly channel? ✔

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ❌
- Does the issue resolve itself when disabling Brave Rewards? ❌
- Is the issue reproducible on the latest version of Chrome? ⭕

**Comment by ryanbr** [comment]
We could wrap this in the https://github.com/brave/adblock-lists/issues/438

Which has more complete social item blocking
