### ISSUE TITLE
Total balance shows negative amount for a new wallet 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1285]
## Description 

Total balance shows negative amount 

## Steps to Reproduce

   1. Build from source and enable Rewards
   2. Claim Token grant should add 20 BAT to wallet (currently hardcoded to 10 BAT)
   3. Fund wallet with 10 BAT, Total wallet summary should show up as 30 BAT
   4. Set monthly budget to 15BAT
   5. Rewards summary shows Token Grant as 10 BAT (expected due to hardcoded value), Brave Auto-Contribute shows -10BAT (added funds to wallet), Total shows -5BAT (doesn't make sense considering wallet with added funds and hardcoded grant value should add up to 20BAT and monthly budget is set to 15 BAT) 

## Actual result:

Monthly budget - 15 BAT
Added Funds - 10BAT
Grant claimed - 20 BAT (hardcoded to 10BAT)
![image](https://user-images.githubusercontent.com/17010094/46089574-d6e16000-c17c-11e8-8548-41fa51ad8129.png)
Monthly budget - 10 BAT
Added Funds - 10BAT
Grant claimed - 20 BAT (hardcoded to 10BAT)
![image](https://user-images.githubusercontent.com/17010094/46089634-f2e50180-c17c-11e8-88c8-b2e4a7206ee5.png)

## Expected result:
Total should only show negative value if the combined value of Added funds + Grant claims is below the monthly budget. 

## Reproduces how often: 

Easy 

## Brave version (chrome://version info)

Brave | 0.55.2 Chromium: 70.0.3538.22 (Official Build) (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/46090091-f0cf7280-c17d-11e8-905f-c12d2d299853.png)

### Reproducible on current release:

N/A for b-l 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@brave/legacy_qa @jenn-rhim @alexwykoff @davidtemkin @NejcZdovc

**Comment by srirambv** [comment]
@kjozwiak @LaurenWags This scenario should be retested once https://github.com/brave/brave-browser/issues/948 is merged

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Total is no longer displayed in this panel
