### ISSUE TITLE
Cards toggle does not remember 

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#12863]
## Description 

The Cards toggle also doesn't seem to remember my last preference. If I hide Rewards, toggle off Cards, and toggle on Cards, it will still show Rewards even though it's supposed to remember that I've hidden it

## Steps to Reproduce

   1. Open a new tab page
   2. Click on "Customize"
   3. Click on "Cards"
   4. Hide any card
   5. Turn off "Cards" toggle and see all cards become hidden
   6. Turn on "Cards" toggle and see that the toggle does not remember I hid the card in step 4

## Actual result:

![cards toggle](https://user-images.githubusercontent.com/2388823/100023327-a1a31d80-2d99-11eb-931e-a11407cafc0e.gif)

## Expected result:
The toggle should show whatever cards were last visible before turning off the toggle.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Nightly Version 1.19.28 Chromium: 87.0.4280.67 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A 
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Bug from https://github.com/brave/brave-browser/issues/12505

**Comment by stephendonner** [comment]
Verified using the testplan provided in the Steps to Reproduce section, on 


Brave | 1.20.88 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

![issue-12863](https://user-images.githubusercontent.com/387249/105778860-1291bd80-5f22-11eb-832f-150e677acd5b.gif)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-Bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Linux

- Verified test plan from issue description

-------
Verification passed on

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-Bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Windows 10 OS Version 2009 (Build 19042.746)

- Verified test plan from issue description
