### ISSUE TITLE
iframe navigations with https upgrades and referrer blocking sometimes crash

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#1286]
## Description 
see https://github.com/brave/brave-core/pull/499 which sets the document.referrer to an empty string for now to avoid the crash

## Actual result:
no crash, but document.referrer is an empty string

## Expected result:
document.referrer should be the target domain

## Reproduces how often: 
Always on the second load (https upgrade is cached)

### Reproducible on current release:
Yes

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

* Verified reload page doesn't remove the iframe navigation
* Verified reloading page doesn't cause webview crash
