### ISSUE TITLE
Inline tip button is shown in Reddit/Twitter/GH even though tipping is disabled in Tips settings 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12870]
## Description 

Inline tip button is shown in Reddit/Twitter/GH even though tipping is disabled in Tips settings 
## Steps to Reproduce

   1. Clean profile 1.18.59 - launch brave with staging flag
   2. Enable rewards and claim UGP grants
   3. Disable all tip settings from `Tips settings`
   4. Open verified Twitter/GH/Reddit pubs and verify the Inline tip button is shown in Reddit/Twitter/GH 

## Actual result:

Inline tip button is shown in Reddit/Twitter/GH even though tipping is disabled in Tips settings 
Twitter:
![image](https://user-images.githubusercontent.com/38657976/100094521-2ddb4080-2e7f-11eb-94bf-4962a87a9d1a.png)

Reddit:
![image](https://user-images.githubusercontent.com/38657976/100094600-48adb500-2e7f-11eb-9813-7545c4eb79e2.png)

GH:
![image](https://user-images.githubusercontent.com/38657976/100094665-5e22df00-2e7f-11eb-8a3f-8ca4941b4b7e.png)

## Expected result:
Inline tip button should not be shown in Reddit/Twitter/GH when tipping is disabled in Tips settings 

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @NejcZdovc @zenparsing @emerick

**Comment by emerick** [comment]
We currently require a browser restart when changing the inline tipping settings.

**Comment by LaurenWags** [comment]
Occurs as a result of https://github.com/brave/brave-core/pull/6978.

@GeetaSarvadnya can you confirm browser restart resolves this per @emerick  comment in https://github.com/brave/brave-browser/issues/12870#issuecomment-732994642?

**Comment by GeetaSarvadnya** [comment]
@LaurenWags @emerick Restart browser fixes the issue, hence closing the issue. Thanks!

**Comment by GeetaSarvadnya** [comment]
As per the slack conversion, the issue is kept open https://bravesoftware.slack.com/archives/CB0KCRCQN/p1606226717465100?thread_ts=1606221529.464500&cid=CB0KCRCQN

**Comment by stgarf** [comment]
What the hay is all this tipping and crypto crap. Time to leave brave in the dust.

**Comment by kjozwiak** [comment]
@stgarf you can remove the tipping icons from Twitter/GitHub and Reddit using the following:

* go into brave://rewards
* scroll down to the "Tips" section
* click on "Tip Settings"
* disable the platforms you don't want
* restart browser

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot 2020-12-10 192244](https://user-images.githubusercontent.com/2602313/101846412-de537080-3b1e-11eb-9a1b-fb9650fd6ca7.png) | ![Screenshot 2020-12-10 192302](https://user-images.githubusercontent.com/2602313/101846421-e01d3400-3b1e-11eb-93b0-8024bd265b58.png)

If you want to disable rewards entirely, you can use the following:

* type in `brave://settings/?search=rewards` via the URL bar
* enable `Hide Brave Rewards button`

![Screenshot 2020-12-10 193734](https://user-images.githubusercontent.com/2602313/101846543-2ecace00-3b1f-11eb-94e6-bb2c48bec623.png)

**Comment by kjozwiak** [comment]
@rebron @bsclifton @marshall labeled this as `P2` as we should get it fixed. Users who don't want to see the tipping UI shouldn't need to restart. We didn't have time to address in `1.18.x - Release #1` but should fix this ASAP IMO.

**Comment by jonathansampson** [comment]
I did some light testing today with a fresh profile. I found that disabling the feature wouldn't immediately clear the button from Twitter (which is expected, per this issue). A restart of Brave was required. Following the restart, the buttons were no longer shown on Twitter.

At this point I re-enabled the feature, and refreshed Twitter--no tip buttons shown. Following the same steps, I restarted the browser and expected to see the tip buttons displayed. When Brave launched anew, there were still no tip buttons. It required a few refreshes of the page before buttons appeared.

**Comment by JoranDox** [comment]
Brave rewards has been turned off in my browser for months now, but I suddenly see tips buttons on twitter, here on github, etc. What gives?

**Comment by LaurenWags** [comment]
@jonathansampson was your twitter page the active tab/in focus when launching the browser? if so, I believe that's a known issue - see https://github.com/brave/brave-browser/issues/11825 cc @emerick for confirmation.

**Comment by jonathansampson** [comment]
@laurenwags It was. Thanks!

**Comment by Megawatt7** [comment]
Well goodbye to Brave browser. I will be downloading the copycat version without all this crazy bloatware. Good bye, GOOD RIDDANCE

**Comment by snowbound** [comment]
I feel if the Brave Rewards is disabled in the browser then do NOT enable any of new addons like tipping. Do not turn Brave into a cat and mouse game with your end-user who has no interest in Brave Rewards/BAT etc. I have to look at your subreddit to see how the heck to disable the annoying triangles that just mysteriously appeared one day.

**Comment by TheFeelTrain** [comment]
Even after a restart the tip buttons are not going away.

Version 1.18.77 Chromium: 87.0.4280.101 (Official Build)

**Comment by emerick** [comment]
Inline tipping is no longer shown if Rewards icon is hidden, per https://github.com/brave/brave-core/pull/7655.

This particular issue will now focus on surfacing a message to the user that toggling inline tipping requires a browser restart. This will most likely take the form of a small "Relaunch" button (similar to the current behavior when changing the language for the browser UI in brave://settings).

cc: @Miyayes @zenparsing @marshall

**Comment by emerick** [comment]
The remaining issue here was addressed in https://github.com/brave/brave-browser/issues/13341.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.31.50 Chromium: 94.0.4606.50 (Official Build) nightly (64-bit)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | Windows 10 Version 21H1 (Build 19043.1165)


```
