### ISSUE TITLE
PDF protected by cookie-based login does not load

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#1287]
## Description 
If you try to load a PDF on a website that requires a login, the PDF does not load. Sometimes, it asks for you to login again. If you try to login, the login dialog just pops up again (as if the login failed). If you cancel the login, the PDF fails to load, with a 401 error.

## Steps to Reproduce
   1. Go to a website that requires a login to access a PDF.
   2. Try to open the PDF file.

## Actual result:
Sometimes it shows the login dialog:
![](https://user-images.githubusercontent.com/19424103/46095454-37bf6700-c182-11e8-85ec-4182dbb3d493.png)
It always shows an error:
![](https://user-images.githubusercontent.com/19424103/46095498-4efe5480-c182-11e8-8d69-8c3f6c3b59a8.png)

## Expected result:
The PDF should load correctly.

## Reproduces how often: 
Always.

## Brave version (chrome://version info)
Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev(64-bit)
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X
JavaScript | V8 7.0.276.9
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36

### Reproducible on current release:
I don't think so.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No, Brave Shields cannot be disabled on a PDF page.
- Is the issue reproducible on the latest version of Chrome? No, because Chrome uses a different PDF extension.

**Comment by Brave-Matt** [comment]
+1's from Community:
https://community.brave.com/t/pdf-files-are-not-opening-with-brave-beta/34420

**Comment by Liunkae** [comment]
A workaround is to download the PDF with the PDF JS toolbar download button:
![](https://user-images.githubusercontent.com/19424103/46779688-83bfef00-ccde-11e8-8cca-859100cfe90c.png)

**Comment by srirambv** [comment]
+1 from @bitcoinuser via #1757 
Brave Browser Version 0.55.18 Chromium: 70.0.3538.67 (Versão oficial) 64 bits
OS: Ubuntu 64

PDF.js v2.0.673 (compilação: 31012570)
Mensagem: Missing PDF "https://pje.tjdft.jus.br/pje/downloadBinario.seam".

![captura de tela de 2018-10-20 17-48-16](https://user-images.githubusercontent.com/1178856/47260353-60d8cc00-d490-11e8-942f-a919f6432862.png)

**Comment by bsclifton** [comment]
Updated to 0.56.x after uplift request was approved by https://github.com/brave/brave-core/pull/780 and code was merged to 0.56.x 😄

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.10 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified with test plan from https://github.com/brave/brave-core/pull/780

**Comment by bitcoinuser** [comment]
I still reproduce this issue on Brave version: Versão 0.56.12 Chromium: 70.0.3538.77 (Versão oficial) 64 bits

**Comment by bbondy** [comment]
@bitcoinuser what are you seeing? I think you're likely seeing a separate version, possibly Linux only or  something like that?

**Comment by bitcoinuser** [comment]
I reported the issue here: https://github.com/brave/brave-browser/issues/2092

**Comment by bbondy** [comment]
Resetting QA flags for this issue because the implementation is a different fix for 0.58.x and beyond for this issue.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.14 x64` - **PASSED**

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
--- | ---
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Mac OS X

* logged in my personal banking account and ensured that I could view the PDF's without any issues
