### ISSUE TITLE
Have better wording about wallet or hide QR code message until wallet is created

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12872]
## Description 

If wallet is not created by enabling ads, QR code fails to load. There is no clear messaging that wallet is required for QR code to be generated. This needs to be handled better

## Steps to Reproduce

   1. Create a new browser profile
   2. Open rewards page and cancel onboarding
   3. Click on QR code button, shows loading message 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/100105953-d5e11180-2e5f-11eb-8178-1c0634b9224a.png)

## Expected result:
Have a clear message as to why QR code is not generated 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.18.57 Chromium: 87.0.4280.66 (Official Build) beta (64-bit)
-- | --
Revision | `fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA 
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/uplift-approvers this probably needs to be uplifted to 1.18.x and for iOS release

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the STR from the description and test plan from https://github.com/brave/brave-core/pull/7281

**`Case 1 - Skipping/dismissing "Earn Tokens & Give Back" modal`**

* ensured that `brave://rewards-internals` is empty on first launch when  `Earn Tokens & Give Back` modal is dismissed
* ensured that the QR code was created and visible once clicking on `QR code` after dismissing the `Earn Tokens & Give Back` modal
* ensured that `wallet.payment_id` gets created via `brave://rewards-internals` once `QR code` is pressed
* ensured the `paymentId` persists after several restarts while `ads` & `a-c` were disabled
* ensured that the `paymentId` retreived from the QR code matches `brave://rewards-internals`
* ensured that the same `paymentId` is being used when enabling `ads` & `a-c` via the toggles under `brave://rewards`
* ensured the `paymentId` persists after several restarts after both `ads` & `a-c` were enabled via `brave://rewards`

**`Case 2 - Clicking on "Earn Tokens & Give Back" modal`**

* ensured that the QR code is being created when clicking on `Earn Tokens & Give Back` and enabling `ads` & `a-c`
* ensured that the `paymentId` from the QR code matches `wallet.payment_id` via `brave://rewards-internals`
* ensured the above worked using the following entry points: `rewards panel`, `brave://rewards` and `brave://newtab`

**`Case 3 - Restoring Wallets`**

* ensured that the QR code displayed the correct `paymentId` when a wallet has been restored
* ensured the `paymentId` persists after several restarts after restoring
