### ISSUE TITLE
YouTube Homepage does not show up while logged in

### ISSUE THREAD

**Issue by ertugrulcetin** [brave/brave-browser#12878]
## Description 
YouTube homepage does not show up (loading components only shown) when I logged in to my Google account. If I logout everything seems fine. I also reset the settings and tried again. I attached the screen.

## Steps to Reproduce

   1. Open YouTube while your Google account is logged in.

## Actual result:

![Screen Shot 2020-11-24 at 22 51 44](https://user-images.githubusercontent.com/8271291/100144784-5a578280-2ea8-11eb-8b79-142686e3becb.png)

## Expected result:
To show video images and load the page properly.

## Reproduces how often: 
Every time

## Brave version (brave://version info)

Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6020)
JavaScript | V8 8.7.220.25
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
  No
- Does the issue resolve itself when disabling Brave Rewards? 
  No
- Is the issue reproducible on the latest version of Chrome? 
  Yes

**Comment by bsclifton** [comment]
@ertugrulcetin where are you physically located? are you using a VPN?

As this reproduces in Chrome, I don't think it's a problem with the software. I'd guess this is a network problem. I'd definitely recommend giving it some time and trying again. If YouTube has a way to get support (Twitter, etc) I'd suggest hitting them up with this information too
