### ISSUE TITLE
87.1.19.32 arm version - Crash upon open in Mac mini M1

### ISSUE THREAD

**Issue by fabrijp** [brave/brave-browser#12882]
## Description 

Crash upon open in Mac mini M1

## Steps to Reproduce

   1. Just open the app

## Actual result:

![image](https://user-images.githubusercontent.com/4961474/100177260-0fc01f80-2f15-11eb-9ad0-2a9c3622e9eb.png)

## Reproduces how often: 

Every time

## Brave version (brave://version info)

87.1.19.31 (119.31)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?

**Comment by fabrijp** [comment]
The newest version 87.1.19.32 arm version still crashing when trying to open it on a Mac with M1 chip.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/12819
