### ISSUE TITLE
Ad showing on Youtube (Android)

### ISSUE THREAD

**Issue by vedangwartikar** [brave/brave-browser#12889]
## Description 
Unclickable Ad is visible sometimes below YouTube videos. Easily reproducible (at least for me). Please take a look. Thanks

## Steps to reproduce 

   1. Open YouTube from Brave browser on Android
   2. Unclickable Ad is visible below the video

## Actual result 
![image](https://user-images.githubusercontent.com/43764240/100228084-259b0800-2f48-11eb-9746-279a90c334e0.png)

## Issue reproduces how often 
Intermittent issue. Observed for around 4/10 times while switching in between videos for testing this specific bug.

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone (OnePlus 7T)
   - Android version: 10
   
## Brave version
Latest Brave Version 1.17.72

**Comment by SergeyZhukovsky** [comment]
cc @ryanbr

**Comment by SergeyZhukovsky** [comment]
@vedangwartikar could you please tell us which country is that?

**Comment by vedangwartikar** [comment]
India

**Comment by ryanbr** [comment]
@vedangwartikar   is the bottom link, next to the signup? Or is it the video itself?

**Comment by vedangwartikar** [comment]
@ryanbr Yes, the link is next to the sign up button (included in the ad pop-up). It is not a part of the video

**Comment by ryanbr** [comment]
Thanks for the report @vedangwartikar 

We have a ticket for this already: https://github.com/brave/brave-browser/issues/9955

Which will resolve the whitespace issues on various sites, and including hiding those text ad elements on youtube.

**Comment by vedangwartikar** [comment]
@ryanbr Thanks for the update, I'll keep up with #9955

**Comment by hientpbank** [comment]
Ok
