### ISSUE TITLE
Can't open pine64.org

### ISSUE THREAD

**Issue by ravenclaw900** [brave/brave-browser#12881]
## Description 

Brave can't load `pine64.org`, instead showing that the connection was reset.

## Steps to Reproduce

   1. Try to visit `pine64.org`

## Actual result:

<img width="672" alt="Screen Shot 2020-11-24 at 4 40 47 PM" src="https://user-images.githubusercontent.com/50060110/100159913-43973880-2e74-11eb-9bc0-2d87e8469e0b.png">

## Expected result:
<img width="1200" alt="Screen Shot 2020-11-24 at 4 46 26 PM" src="https://user-images.githubusercontent.com/50060110/100160130-a1c41b80-2e74-11eb-8422-fdddfbb5b053.png">

## Reproduces how often: 

Easily reporoduced.

## Brave version (brave://version info)

Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | ~~macOS Version 10.13.6 (Build 17G14042)~~  macOS Version 10.14.6 (Build 18G6042)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the nightly channel? 
?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards?
No 
- Is the issue reproducible on the latest version of Chrome? 
Yes

## Miscellaneous Information:

The store, and all subdomains still load.  Works on Safari.

**Comment by ryanbr** [comment]
Hey @ravenclaw900  just tested this site, seems to load fine. Is it still an issue?

**Comment by ravenclaw900** [comment]
Yes, it is.

**Comment by ryanbr** [comment]
@ravenclaw900  which extensions do you have? also, does different Brave profile help? (test with Brave Beta build as an option)

**Comment by ravenclaw900** [comment]
The new profile / browser don't help.  I have Google Translate, Grammarly, MalwareBytes, MyBib, Stop Mod Reposts, TOS;DR, and WOT installed.

**Comment by ravenclaw900** [comment]
It now says `pine64.org took too long to respond`.  The bar at the bottom says `Establishing Secure Connection...` the whole time it tries to connect.

**Comment by ravenclaw900** [comment]
It fails on Firefox as well, so I think it's actually a problem with my setup.
