### ISSUE TITLE
Default brave shield pref settings - Basic UI

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1288]

**Comment by bbondy** [comment]
<img width="878" alt="screen shot 2018-09-26 at 1 53 57 pm" src="https://user-images.githubusercontent.com/831718/46099001-a527c380-c193-11e8-8f97-320e31c54592.png">

**Comment by srirambv** [comment]
This fails on 0.55.10. 
1. Setting `Allow ads and tracking` in global settings still blocks tracking scripts on shields
2. Changing shields settings to `Allow ads and tracking` sets count to 0 

Here's the steps recording https://youtu.be/l75ZWlgbySA

**Comment by bbondy** [comment]
@srirambv can you try with a fresh page load and not a reload? Same results?

**Comment by srirambv** [comment]
With new page load in a new tab still same result. 3 tracking scripts are still blocked even if global shield settings is set to Allow ads and tracking.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified global settings can be overridden from shields
* Verified global settings take effect on a page when loaded
