### ISSUE TITLE
Add statement of accounts changes for Brave Ads NTP widget

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12880]

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.55 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.630)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/7242
- Verified that `Ads received this month`, `Estimated Pending rewards` and `Next payment date` are displayed correctly after viewing an Ad
- Verified that `Ads received this month`, `Estimated Pending rewards` and `Next payment date` are retained correctly after browser restart
