### ISSUE TITLE
[Desktop] verified creator favicon is no longer correctly shown in the panel 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12891]
## Description 

In 1.17.x if you navigated to a creator page (ex. twitter.com/jonathansampson) with a clean profile, enabled rewards, and opened the panel, you saw the creator's custom favicon (where applicable). 

If you do this in 1.18.x, you see the generic favicon for the publisher.

## Steps to Reproduce

   1. Clean profile 1.18.x (no need to enable Rewards, RE has been implemented) on production env
   2. Navigate to twitter.com/jonathansampson
   3. Open panel, dismiss onboarding.

## Actual result:

generic twitter favicon is displayed
<img width="1192" alt="Screen Shot 2020-11-25 at 11 06 53 AM" src="https://user-images.githubusercontent.com/28145373/100253323-f4521600-2f0e-11eb-9e1f-0e91ff2d85e5.png">

## Expected result:
User's custom favicon as seen with 1.17.x:
<img width="1193" alt="Screen Shot 2020-11-25 at 11 06 34 AM" src="https://user-images.githubusercontent.com/28145373/100253358-ffa54180-2f0e-11eb-9c23-8a6bde9578d7.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.18.62 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6042)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, 1.17.x
- Can you reproduce this issue with the beta channel? yes 1.18.x
- Can you reproduce this issue with the nightly channel? yes 1.19.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @emerick

**Comment by emerick** [comment]
It looks like the first time you visit a verified Twitter user, we think they're unverified and thus just show the standard Twitter avatar. After that, visiting any other verified Twitter user works as expected.

So, for example visiting in this order with a clean profile, `brave` will have the correct avatar:

https://twitter.com/jonathansampson
https://twitter.com/brave

And visiting in this order with a clean profile, `jonathansampson` will have the correct avatar:

https://twitter.com/brave
https://twitter.com/jonathansampson

**Comment by emerick** [comment]
The triggering event seems to be dismissing or accepting the Rewards onboarding dialog. If you do that before visiting the first verified Twitter user, everything works as expected.

**Comment by zenparsing** [comment]
@emerick Is this still an issue in Nightly?

**Comment by emerick** [comment]
@zenparsing Yes, this is still an issue in the latest Nightly.

**Comment by emerick** [comment]
I think the issue here is that when we visit a Twitter page on a clean profile, we see that we're not connected and we call `StartProcess` to launch the ledger process. This ends up calling `LedgerImpl::StartServices` which (among other things) calls   `publisher()->SetPublisherServerListTimer()`. However, `StartServices` has no callback or other mechanism for notifying the caller when the services have fully started. This means that when we subsequently attempt to look up the publisher info for the Twitter user, there's nothing in the publisher list.

Not sure what the best way forward is here. At a minimum, we shouldn't try to look up publishers in the publisher list until it's actually saved.

**Comment by Miyayes** [comment]
Going to close this for now given we have the new Rewards panel 2.0 in v1.31.x. If this issue appears with new panel too, we can file again anew.
