### ISSUE TITLE
macOS system UI appearance within Brave should match Brave theme color

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#1289]
This applies to macOS 10.14 (Mojave) or later only.

Even if the Brave UI is set to the dark theme, system UI (context menus, dialog boxes, etc.) does not match the dark theme.

![](https://user-images.githubusercontent.com/19424103/46096733-933f2400-c185-11e8-98d9-83ab92b13f4f.png)
![](https://user-images.githubusercontent.com/19424103/46096749-a18d4000-c185-11e8-844d-f700228adc18.png)

The system UI appearance should match the Brave theme color setting:
![](https://user-images.githubusercontent.com/19424103/46096830-d13c4800-c185-11e8-8194-cc7cafeae631.png)

Note that this is the opposite of #1189. That issue is for Brave's theme to take the appearance of the system. This issue is for the system UI within Brave to take Brave's theme appearance.

To do this, set the NSAppearance of the shared NSApplication. Something like this:
```objc
if (theme == light) {
    NSApplication.sharedApplication.appearance = [NSAppearance appearanceNamed:NSAppearanceNameAqua];
} else if (theme == dark) {
    NSApplication.sharedApplication.appearance = [NSAppearance appearanceNamed:NSAppearanceNameDarkAqua];
}
```

**Comment by simonhong** [comment]
@bbondy @petemill Should we increase this priority also?

**Comment by Liunkae** [comment]
This is partially done. As of 0.62.24 dev, the system UI now matches the macOS theme appearance. This is a great improvement if your macOS and Brave theme settings match. In dark mode (macOS and Brave):

![](https://user-images.githubusercontent.com/19424103/53983201-5126f080-40dc-11e9-80a3-45e47ee5cf64.png)
![](https://user-images.githubusercontent.com/19424103/53983223-5b48ef00-40dc-11e9-9067-6bcd950d131d.png)

When brave/brave-core#1805 is implemented, the system UI will match the Brave theme appearance. This will improve the experience for users whose macOS and Brave theme settings do not match.

**Comment by LaurenWags** [comment]
@kjozwiak since you have Mojave could you test this one when you get the chance?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.3 x64` using the following build:

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

* Used both `Brave Colors: Dark` & `Brave Colors: Same as MacOS`

Examples:

<img width="436" alt="Screen Shot 2019-03-19 at 11 40 59 PM" src="https://user-images.githubusercontent.com/2602313/54657873-7edb4480-4aa1-11e9-8e3e-3e5b00490834.png">

<img width="393" alt="Screen Shot 2019-03-19 at 11 41 55 PM" src="https://user-images.githubusercontent.com/2602313/54657876-826ecb80-4aa1-11e9-8e62-24395973a8a3.png">

<img width="852" alt="Screen Shot 2019-03-19 at 11 44 20 PM" src="https://user-images.githubusercontent.com/2602313/54657890-87cc1600-4aa1-11e9-9b88-917b8557f497.png">

<img width="1229" alt="Screen Shot 2019-03-19 at 11 43 36 PM" src="https://user-images.githubusercontent.com/2602313/54657882-84d12580-4aa1-11e9-92aa-deeae244064c.png">

<img width="1029" alt="Screen Shot 2019-03-19 at 11 44 51 PM" src="https://user-images.githubusercontent.com/2602313/54657903-96b2c880-4aa1-11e9-81e7-c04ff8861705.png">
