### ISSUE TITLE
Auto-Contribute icon missing from Brave Rewards settings

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#12893]
## Description 

A-C icon is conspicuously missing from the A-C panel in Brave Rewards.

![image](https://user-images.githubusercontent.com/11497541/100260588-970e9280-2f17-11eb-9d87-e9b42ad1bcb3.png)

I've seen this in the past, so it might be a regression.

## Steps to Reproduce

   1. Open Brave Rewards settings
   2. Disable A-C

## Reproduces how often: 

100%

## Brave version (brave://version info)

Release channel: Version 1.17.73

**Comment by cryptojennie** [comment]
+1 
![Screen Shot 2020-11-25 at 12 34 01 PM](https://user-images.githubusercontent.com/32344882/100262711-8a3f6e00-2f1a-11eb-91a0-3c1ae2fb692b.jpg) 

**v1.17.73 MacOS**

**Comment by marshall** [comment]
this should be fixed in 1.18

**Comment by LaurenWags** [comment]
Issue in 1.18.x milestone: https://github.com/brave/brave-browser/issues/12423
