### ISSUE TITLE
Strange shields popup korean translation

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#12899]
It looks like translation is done for each words - `Shields UP for this site`
`Shields` -> `보호`  `UP`-> `위로`,  `for this site` -> `이 사이트를 위한`
and same for `Shields DOWN for this site`.
Translating word to word causes weird translation result because Korean and English uses different word order.

<img width="382" alt="스크린샷 2020-11-26 오전 10 19 20" src="https://user-images.githubusercontent.com/6786187/100297204-7efb4980-2fd1-11eb-9a74-b4037b3922d2.png">
<img width="381" alt="스크린샷 2020-11-26 오전 10 20 43" src="https://user-images.githubusercontent.com/6786187/100297209-815da380-2fd1-11eb-8c40-806c9b39960c.png">

**Comment by simonhong** [comment]
@mkarolin this one also :)

**Comment by simonhong** [comment]
transifix doesn't have `Shields UP for this site` sentense.
To give proper transation in ko, this popup should use one full sentense for l10n.

**Comment by simonhong** [comment]
I assume partial texts are assembled here because we use different style for `Up/Down` word in this sentence.
@petemill , Could we use one sentense instead of assembling and use current style? Or should we consider UI change?

**Comment by petemill** [comment]
Yes this is a very bad way of translating. We should be using tokens here.

**Comment by rebron** [comment]
cc: @nullhook To keep this in mind with the new Shields work.

**Comment by simonhong** [comment]
@rebron I think this issue will be fixed with shields v2 as one sentence is used. cc @nullhook
https://github.com/brave/brave-core/blob/master/components/brave_shields/resources/panel/components/main-panel/index.tsx#L11

**Comment by rebron** [comment]
@simonhong Can you check to see if we have this fixed now with v2 or do we need to wait to pull in translations for 1.38.x?

**Comment by simonhong** [comment]
@rebron Yes, needs 1.38.x translation. I think v2 will fix this issue.
<img width="403" alt="스크린샷 2022-03-17 오전 10 43 35" src="https://user-images.githubusercontent.com/6786187/158719930-d5803b98-088e-4444-bb53-1dc5a37e1b1d.png">

**Comment by simonhong** [comment]
This issue is fixed with current 1.38.x.

**Comment by simonhong** [comment]
Closed as this was fixed by shields v2.
