### ISSUE TITLE
After fixing an issue: Translation is missing at the Bookmark Context Menu

### ISSUE THREAD

**Issue by bastele7** [brave/brave-browser#12904]
Since the current builds of Brave the translation is missing in the context menu of the bookmarks (was translated at version 1.16.76). Issue was https://github.com/brave/brave-browser/issues/12844

Current builds
![Unbenannt](https://user-images.githubusercontent.com/74867100/100317488-ba3f4d80-2fbc-11eb-992e-0a912318c792.png)

Previous builds
![Unbenannt2](https://user-images.githubusercontent.com/74867100/100317540-d04d0e00-2fbc-11eb-8fd5-7e2d25ff8492.png)

**Comment by Furax-31** [comment]
Same problem in french.

**Comment by btlechowski** [comment]
`QA/Blocked` till we get a new build (> 1.18.69)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/101653911-2ea7d100-3a40-11eb-85c1-7e1e98df46eb.png)
![image](https://user-images.githubusercontent.com/34715963/101653770-faccab80-3a3f-11eb-996f-b9111db046bf.png)
![image](https://user-images.githubusercontent.com/34715963/101653841-13d55c80-3a40-11eb-8dc6-7f6053321ed7.png)
![image](https://user-images.githubusercontent.com/34715963/101653878-20f24b80-3a40-11eb-8954-736314770283.png)
