### ISSUE TITLE
Make a "stable" link to the latest dev version

### ISSUE THREAD

**Issue by Yardanico** [brave/brave-browser#1290]
Make a non-changing link to the latest dev version (.deb file) of the browser. This would help some distributions like Arch (it would be easy to create a PKGBUILD for AUR if link doesn't change). 

For example Google Chrome does this:
https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb always points to the latest google-chrome-dev build.

**Comment by srirambv** [comment]
cc: @RyanJarv @mbacchi
