### ISSUE TITLE
Prevent auto downloading & opening a PDF file on click 

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#12902]
## Description 
- Currently, when a user clicks a link to a PDF file, it'll be downloaded and opened in an associated app without confirming.
- For security reasons, some users want to prevent it

## Steps to reproduce 

   1. On Android, click https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
   2. 
   3. 

## Actual result 
It'll be downloaded and opened in a default PDF viewer app.

## Expected result
- Allow them to prevent it as an option menu

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan 1:
1. Without changing anything, click https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
2. Pdf should be opened automatically (same behavior as before)
Test plan 2:
1. Go to `Downloads` settings
2. Turn off `Automatically open when possible`
3. Click https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
4. Pdf file should be just downloaded, without opening

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.74 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/12902#issuecomment-755318958
------------
Verification passed on Samsung Tab A with Android 10 running 1.19.74 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/12902#issuecomment-755318958
