### ISSUE TITLE
New Tab won't load page (Google)

### ISSUE THREAD

**Issue by RugerSR9** [brave/brave-browser#12905]
## Description 
When you open a new tab and try to navigate to any Google page, it fails to do anything (infinite loading).

## Steps to Reproduce

   1. Open a new tab
   2. Type a search phrase or a google link
   3.  Page won't load

## Actual result:
Infinite loading

## Expected result:
Navigate to search query or web page

## Reproduces how often: 
Every single time.

## Brave version (brave://version info)
Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Idk
- Can you reproduce this issue with the nightly channel? Idk

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome? No

## More info
Opening dev tools fixes the issue temporarily.

**Comment by antwake** [comment]
same here on MacOS 10.15.7. Happens with the last version of Brave 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64). Browser is barely usable atm

**Comment by rebron** [comment]
@RugerSR9 @antwake We release 1.17.75 last Thursday? Can you try updating to that and see if you're still having issues. Pages just aren't loading?

**Comment by antwake** [comment]
Hi. Just upgraded and it works. 

Before that I found a workaround by removing  the https filter option in the Adguard app.

thank you!

**Comment by RugerSR9** [comment]
@rebron haven't faced the issue in a few days, seems it was solved. Thanks.
