### ISSUE TITLE
Custom ad notifications should respect browser theme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12910]
## Description 

Custom ad notification should respect browser theme 

## Steps to Reproduce

   1. Install nightly 
   2. Set browser theme to dark
   3. View an ad, doesn't respect browser theme

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/100356877-c2fb4800-2feb-11eb-9b32-fde862501142.png)

## Expected result:
Since its custom notification should respect the theme set by browser for ad notification

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.19.33 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @tmancey @yachtcaptain23

**Comment by tmancey** [comment]
Dark Theme:

<img width="368" alt="dark-theme-2" src="https://user-images.githubusercontent.com/1188719/101737807-470a0100-3abd-11eb-8025-8d5f00934d16.png">

**Comment by tmancey** [comment]
Closing as will discuss with design and implement as part of https://github.com/brave/brave-browser/issues/13132
