### ISSUE TITLE
Subtitles in a Youtube video will not show when in fullscreen mode.

### ISSUE THREAD

**Issue by anzorein** [brave/brave-browser#12911]
## Description 

Subtitles in a Youtube video will not show when in fullscreen mode.

## Steps to Reproduce

   1. Open a youtube video with Brave browser in Android
   2. Enable subtitles
   3. Enter full-screen mode

## Reproduces how often: 

Easily reproduced, happens every time I tried in different videos.

## Brave version (brave://version info)

Brave 1.17.72, Chromium 87.0.4280.66
OS: Android 10, Redmi note 7

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
A: No
- Does the issue resolve itself when disabling Brave Rewards?
A: No

## Miscellaneous Information:

I used to be able to press the home button and when the floating window with the video appeared, I pressed full screen from there and it fixed itself, but now that doesn't work and I haven't found any other way to make subtitles appear in full screen mode.

**Comment by ryanbr** [comment]
I just tested in Chrome and Firefox, I couldn't get the captions to work in fullscreen mode @anzorein   I don't think its a Brave specific issue

Tested using https://m.youtube.com/watch?v=nUyLnjgGyng  (Captions, English auto generated).

**Comment by anzorein** [comment]
You are right, I didn't think about trying it on other browsers, but Firefox didn't work for me either. I get the impression it's not scaling the full screen correctly and the bottom part of the video gets cut out including captions.

I'll close this since it's not an issue with Brave only, thanks for testing it out.
