### ISSUE TITLE
Brave Today Request for Daily Wire Source

### ISSUE THREAD

**Issue by MrWaste** [brave/brave-browser#12916]
## Description 

Please add Daily Wire to the list of sources.
https://www.dailywire.com/

**Comment by Dryader** [comment]
Could you please provide more details as to what you are requesting?

**Comment by MrWaste** [comment]
Add Daily Wire to the List:

![2020-12-03_141502](https://user-images.githubusercontent.com/49108816/101094897-f9980c00-3571-11eb-8750-1513d879bbd1.png)

**Comment by MrWaste** [comment]
@Dryader or @bsclifton I have been using brave since December of 2017. For many months I have been wanting to work with the brave team. Not for pay or anything - Free. I need the type of experiences that can only come from your team. You are all amazing. I try to pitch in as much as I can, however my reports/ issues usually wait about 1 month or more before someone can responded back. I would like to help out anywhere I can if you have anything available.

If you would like to contact me:
Don't want to put out my real email address, it gets forward to my real email. I can respond back through it. 
simplelogin-newsletter.pseudoaconitine@aleeas.com

**Comment by bsclifton** [comment]
cc: @mattmcalister

**Comment by MrWaste** [comment]
@bsclifton What is the progress of adding this and how likely? Its be so long...

**Comment by mattmcalister** [comment]
@MrWaste you can add RSS feeds from any publisher using the iOS app. RSS will be coming to desktop soon, too.

**Comment by JimBreton** [comment]
Does this need to even be open anymore or should it be closed in deference to 13095?
