### ISSUE TITLE
[Followup #12483] Menu buttons are not properly aligned when bottom toolbar is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12926]
## Description 
[Followup #12483] Menu buttons are not properly aligned when bottom toolbar is disabled

## Steps to reproduce 

   1. Install build
   2. Disable bottom toolbar and select later for relaunch
   3. Open menu, buttons are not aligned correctly 

## Actual result 
Menu buttons are not properly aligned when bottom toolbar is disabled

## Expected result
Should align properly 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.18.63

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by LaurenWags** [comment]
Per original issue, I can reproduce this with `1.18.67` on Beta, however using latest Nightly `1.19.43` it does not reproduce for me 👍 

Verification passed on LG Nexus 5 with Android 5.1 running 1.19.43 Bravearm.apk
