### ISSUE TITLE
Pass https://canyoublockit.com/extreme-test/

### ISSUE THREAD

**Issue by masterjg** [brave/brave-browser#12929]
## Steps to Reproduce

   1. Go to `https://canyoublockit.com/extreme-test/`
   2. Observe a lot of ads pass the test

## Expected result:
None of the ads and other nasties being executed in the test

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Setting shields to Aggressive, does it help? what ads are showing? @masterjg

**Comment by ryanbr** [comment]
Okay, lets see how this goes.

https://github.com/easylist/easylist/commit/759c282e5b2608f255979d11bb156d96805db68f

**Comment by masterjg** [comment]
Sorry for not responding earlier. Everything was at max
<img width="278" alt="canyoublockit" src="https://user-images.githubusercontent.com/11464772/100653111-95e2c880-3350-11eb-827b-21ee6d354850.png">
I am also using additional ublock origin plugin to completely block everything:
<img width="476" alt="ublock_origin" src="https://user-images.githubusercontent.com/11464772/100653343-ebb77080-3350-11eb-9efc-ea4f9e20c25b.png">
Combining both brave browser + ublock origin I get everything blocked, including popunders, hidden clicks, etc

**Comment by ryanbr** [comment]
Okay, re-review this.  Give it 24-48hrs. should resolve the popups (with uBO extension disabled)

**Comment by ryanbr** [comment]
Disabling uBO @masterjg   this should be now fixed, no popups seen. Can you confirm?

**Comment by ryanbr** [comment]
Closing ticket, site no longer generates popups. Re-open ticket @masterjg  if you have any issues.
