### ISSUE TITLE
Incorrect korean translation of brave stats in NTP

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#12924]
`saved`  is translated to `저장됨` but `저장됨` meaning is more close to `stored`.
Also `Bandwidth` is translated to `대역폭` but I think `데이터` would be better.
In Android, `데이터` is used. Android NTP uses `데이터 저장됨`.
For `Bandwidth saved`,  `데이터 절약됨` would be much better.

`Time saved` also has same. I think `절약됨` is more better for `saved` in this context.
Fro `Time saved`, `시간 절약됨` would be much better for delivering our behavior.

<img width="459" alt="스크린샷 2020-11-27 오후 5 55 40" src="https://user-images.githubusercontent.com/6786187/100430278-e8667f80-30d9-11eb-89b4-5735e34bd048.png">

**Comment by rebron** [comment]
cc: @mkarolin

**Comment by mkarolin** [comment]
@simonhong would you mind fixing on Transifex:
https://www.transifex.com/brave/brave/translate/#ko/$/156854277?q=text%3A'Time+saved'
https://www.transifex.com/brave/brave/translate/#ko/$/283247917?q=text%3A'Bandwidth+saved'

I fixed a couple but wasn't sure about some other occurrences. I can pull them down afterwards.

**Comment by simonhong** [comment]
@mkarolin Yup, I asked to join transifex today because my existing accounet seems not working now.
Will check after my join request is accepted.

**Comment by simonhong** [comment]
@mkarolin added some more fixes there.

**Comment by srirambv** [comment]
Issue not fixed on Android. #13790 logged as a followup.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.19.87 Chromium: 88.0.4324.96 (공식 빌드) (x86_64)
-- | --
개정 | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS 버전 10.15.7(빌드 19H15)
```

Confirmed updated translations on NTP for `Bandwidth saved` and `Time saved`

`1.19.86` | `1.19.87`
----- | -----
<img width="451" alt="1 19 86" src="https://user-images.githubusercontent.com/28145373/106009971-f6f3f780-6086-11eb-801c-b77b78df3cb2.png"> | <img width="436" alt="1 19 87" src="https://user-images.githubusercontent.com/28145373/106009981-f8252480-6086-11eb-9e41-ea26bd3be750.png">
