### ISSUE TITLE
Gateway is used for ipfs:// subresources despite feature flag setting

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#12931]
## Description 

If the IPFS feature flag is disabled (which is at the time of writing the default), ipfs:// subresources will redirect to the dweb.link gateway.

## Steps to Reproduce

   1. Go to brianbondy.com and right click on an image
   2. Change the `img` `src`'s attribute value to `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq//I/m/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_(454045).jpg`

## Actual result:

Image will laod

## Expected result:

Image should not load

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.16.x and above

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.19.82 Chromium: 88.0.4324.79 (Official Build) dev (x86_64)
-- | --
Revision | bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS | macOS Version 10.15.7 (Build 19H15)
```

Set "Enable IPFS" to "Disabled" on brave://flags and relaunched:
<img width="1035" alt="Screen Shot 2021-01-13 at 10 40 17 AM" src="https://user-images.githubusercontent.com/28145373/104474377-f25e1800-558b-11eb-9431-16545e8b6ebf.png">

Then followed STR from description. Confirmed image did not load:
<img width="1032" alt="Screen Shot 2021-01-13 at 10 40 53 AM" src="https://user-images.githubusercontent.com/28145373/104474400-f8ec8f80-558b-11eb-9251-806a28d804f1.png">
