### ISSUE TITLE
Brave 1.17 crashes frequently, in BraveStatsUpdater

### ISSUE THREAD

**Issue by dolney** [brave/brave-browser#12939]
## Description 
I built Brave 1.17.73 for linux and found that it crashes frequently. I had been using my own build of 1.16.76 and that was stable.

## Steps to Reproduce

   1. Build 1.17.73 for linux with **is_official_build=true**
   2. open the browser, navigate to any page and leave open 
   3. Brave crashes within 30 minutes

## Actual result:
Trace/breakpoint trap

## Reproduces how often: 
Easily reproduced, but takes about 30 minutes

## Brave version (brave://version info)
Built myself from source:
Brave	1.17.73 Chromium: 87.0.4280.67 (Official Build) unknown (64-bit)
Revision	0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS	Linux

## Version/Channel Information:
Did not try other builds but checked out latest git and source code looks the same so expect would have the same issue...see below comment for what I think is the problem.

## Other Additional Information:

Running brave through gdb I find the crash in this function in src/brave/browser/brave_stats/brave_stats_updater.cc:

 ```
GURL BraveStatsUpdater::BuildStatsEndpoint(const std::string& path) {
   auto stats_updater_url = GURL(usage_server_ + path);
#if defined(OFFICIAL_BUILD)
  CHECK(stats_updater_url.is_valid());
#endif
   return stats_updater_url;
 }
```
But it looks like stats_updater_url doesn't get set to anything valid, the build environment has brave_stats_updater_url="" by default.

Commenting out the CHECK gives me a stable browser, I have been running fine like that for days now. Not sure what the CHECK should do or what the consequences are from commenting that out.

**Comment by bsclifton** [comment]
@dolney this is on purpose, by design

We have specific API keys used for sending usage pings. If they're not present, we want the build to crash (so that we don't release it). The solution would be to either patch that out or don't build OFFICIAL_BUILD. There are signing problems you'll run into also

**Comment by dolney** [comment]
Thank you for your answer. Now I am worried about the signing problems you mention. Can I somehow get some API keys to build with so I don't have these problems?

**Comment by bsclifton** [comment]
@dolney the problems will happen if you run `npm run create_dist`, which is what we use to prep the final binaries. We can't share signing keys for obvious reasons. We only want the official build communicating with our API, so unfortunately we can't provide a key

**Comment by dolney** [comment]
Brian, thanks again for answering. I realize this is a closed bug, but still could use the advice from a dev...maybe one more question: is it better if I just build with is_official_build=false ? I don't know the chrome codebase really at all just that what I read on chromium dev pages is that official build "turns on many optimizations". What's your advice? Thanks again

**Comment by bsclifton** [comment]
@dolney I guess it depends on what your goal is. If you're wanting to run the browser everyday, then I'd keep `is_official_build=true` and then remove the CHECK that you've found (and others you may run into). You could always do a floating patch- basically fork (`dolney/brave-core`), commit your patch removing the CHECK (and other patches), and then rebase from upstream (`brave/brave-core`) periodically

**Comment by dolney** [comment]
I would like to work on getting a brave build script into the Gentoo Linux distribution. You probably know, it is a source-based distro, so users would be building brave from source. What do you recommend in that case? Do Gentoo users lose functionality like the stats counters because they are building from source?

**Comment by dolney** [comment]
Hmm, something I don't quite understand: since I commented out the CHECK above I don't have stats anymore. All counters show zero and remain that way. What am I missing?
