### ISSUE TITLE
🚨Danger: Brave seed restores only the first wallet and not all of them

### ISSUE THREAD

**Issue by victorelec14** [brave/brave-browser#12936]
## Description 

You cannot restore the Wallet through the Seed with all the wallets created within, only the main wallet is restored and all other accounts will be lost including the funds you have in them.

It also does not allow you to create a backup of the Seed of each of the accounts, but a single Backup of the main account.

## Steps to Reproduce

   1.  Create a wallet and save the seed
   2.  Create more accounts/wallet in this wallet
   3.  Go to a new Brave installation and Restore this seed 
   4. Now you have only the first wallet restore and you've lost the rest wallets and your funds ! 🔥

## Actual result:

Only the first wallet is restored

**Principal Wallet**
![image](https://user-images.githubusercontent.com/543450/100517418-acd7be00-318a-11eb-8d0e-b93070daceeb.png)

**After Restored in another Profile / Brave (Stable, Beta, Nightly)**
![image](https://user-images.githubusercontent.com/543450/100517449-db559900-318a-11eb-9f97-3d0362a1872e.png)

**Settings -- > Security --> Reveal Seed Phrase**  
It also gives you only the seed of the main wallet and not all
![image](https://user-images.githubusercontent.com/543450/100517623-28863a80-318c-11eb-8695-87d40771de75.png)

## Expected result:
Restored all wallet in my brave seed.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

W10 : Version 1.18.43 Chromium: 87.0.4280.49 (Official Build) (64-bit) (Restored Seeds in another Profile)

W10: Version 1.19.39 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)  (Restored Seeds)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  -- (no tested)
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No Tested (shoud no affected) 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

just create a wallet and save the seed, then inside create more wallets and finally import it into another profile or new installation of brave (Stable, Beta, Nightly)

The same happens if you do the backup after creating the accounts.

Of the new accounts it does not allow you to export the seed of each one of them, only the main one and I think that should change as well.

Thank you !

**Comment by srirambv** [comment]
This is as per design from upstream Metamask. Please refer to this for reference https://github.com/MetaMask/metamask-extension/issues/2887#issuecomment-356044165
