### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by cmanley** [brave/brave-browser#12938]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.17.73  Chromium: 87.0.4280.67
Operating System: Windows NT 10.0.19042

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Shutdown Windows.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/583b0000-cfc2-4f05-0000-000000000000

**Comment by rebron** [comment]
cc: @iefremov

**Comment by iefremov** [comment]
For some some reason it wasn't by backtrace :-/ Sorry, but cannot investigate
