### ISSUE TITLE
Crypto wallet infobar is shown for google calendar/gmail

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#12942]
`Version 1.18.63 Chromium: 87.0.4280.67 (Official Build) beta (x86_64)`

![image](https://user-images.githubusercontent.com/6786187/100608040-2f10df80-334f-11eb-8a6d-c9433ec56172.png)
<img width="772" alt="Screen Shot 2020-12-01 at 11 23 36 AM" src="https://user-images.githubusercontent.com/6786187/100689453-d7628a80-33c7-11eb-94a1-4e50bf667a8a.png">

**Comment by diracdeltas** [comment]
crypto wallets team is aware of the issue and i believe @ryanml has a fix coming

**Comment by ryanml** [comment]
There is a fix that has already landed providing a "Don't Ask Again" option to the infobar, but we're actually going to go ahead and remove the infobar completely, that should land this week

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/brave-core/pull/7342

**Comment by btlechowski** [comment]
`QA/Blocked` till we get a new build (> 1.18.69)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from the description
Crypto wallet bar is not shown
![image](https://user-images.githubusercontent.com/34715963/101638944-006dc580-3a2f-11eb-8f57-41c543a5375d.png)
![image](https://user-images.githubusercontent.com/34715963/101639076-285d2900-3a2f-11eb-8f61-c9727fcfbc2f.png)
