### ISSUE TITLE
Brave Ads custom ad notifications crash on macOS

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12945]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Subject says the crash issue appeared only for macOS hence labeled only macOS

**Comment by LaurenWags** [comment]
@tmancey @jsecretan since custom ad notifications were reverted from Beta with https://github.com/brave/brave-browser/issues/13004 should this issue still be labeled as `QA/Yes`? cc @rebron @kjozwiak

**Comment by tmancey** [comment]
@LaurenWags marked as QA/No as was tested as part of nightly, thanks
