### ISSUE TITLE
Import `promoCode` from `browser-laptop` when upgrading to brave-core

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1294]
## Description
With https://github.com/brave/brave-core/pull/428, the referral program was implemented on brave-core. As we move towards 1.0, we need to consider what happens when users are using the Muon based product (`browser-laptop`) and then upgrade

## Steps to reproduce
1. Install the Muon based browser from a referral link (installer name has referral code embedded)
2. Verify in the `session-store-1` that `promoCode` and `download_id` are set
3. (not implemented) check for updates and user is prompted to upgrade to brave-core
4. brave-core is installed; profile should be imported. `promoCode` and `download_id` need to be imported too and put into local_state

**Comment by btlechowski** [comment]
Verification Passed on 

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Windows 7 x64

Issue found: https://github.com/brave/brave-browser/issues/2344
