### ISSUE TITLE
Excessive Ubuntu CPU usage

### ISSUE THREAD

**Issue by zackees** [brave/brave-browser#12947]
## Description 

Heavy CPU usage Ubuntu 20.04.1 LTS

Regardless of what web page I open, brave uses 100% of the CPU, bringing my workstation to it's knees with just a few pages open.

## Steps to Reproduce

   1. Install Ubuntu 20.04.1 LTS
   2. Download and install the standard brave with standard options
   3. Open up a bunch of tabs to random web pages (and youtube)
   4. Run cmd top and see that brave processes are all at the top of the list

## Actual result:

Brave is consuming all CPU resources

## Expected result:

Brave should be consuming a reasonable amount of CPU resources.

## Reproduces how often: 

Easily reproduced, happens all the time.

## Brave version (brave://version info)

Brave Version 1.13.86
Ubuntu 20.04.1 LTS

## Version/Channel Information:

- Can you reproduce this issue with the nightly channel? 
--> Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

Didn't try.

**Comment by rebron** [comment]
@zackees Can you update to 1.17.75 and let us know if you're still having issues?

**Comment by zackees** [comment]
I'm not willing to install a custom version of brave. However I have the nightly already installed and it currently is at 1.19, is that good enough?

**Comment by zackees** [comment]
1.19 seems to behave a lot better on the CPU.

I'll just use the nightly now.

**Comment by zackees** [comment]
I'm tried 1.17.75 now and the performance problem remains.

Confirmed fixed in 1.19 and 1.20 though.

**Comment by rebron** [comment]
@zackees I'm going to go ahead close this one as current release version is 1.21.77 and you've reported this as confirmed fixed on 1.19.x and 1.20.x.

**Comment by oren-sarid** [comment]
I know this topic is closed, but I just installed brave 1.34.80 on Ubuntu (first install of brave ever) and the CPU is above 80% at all times, with htop showing brave as the main CPU consumer.
