### ISSUE TITLE
Still listed as Intel build in System Report

### ISSUE THREAD

**Issue by mrswitters** [brave/brave-browser#12948]
## Description 
I'm running the 1.19.31 nightly build. It's really slow, but that has been noted already. Is this supposed to be a universal build or one that will run under Rosetta? I was under the impression that it is Universal, but when I go to System Report > Applications, it is listed as an Intel build. 

## Brave version (brave://version info)
1.19.31 nightly build

**Comment by mrswitters** [comment]
Sorry, I realized I had downloaded the wrong build. I now have 1.19.41 ARM and it's working really well so far!

**Comment by bsclifton** [comment]
Thanks for the report @mrswitters - we have M1 support captured with https://github.com/brave/brave-browser/issues/12819 - I'll go ahead and close this as a duplicate 😄
