### ISSUE TITLE
Brave Ads notification close button hit area is too small

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12956]
## Steps to reproduce 

   1. View ad notification
   2. Click close `X` button

## Actual result 
Hit area is too small and does not follow Android UX guidelines

## Expected result
Hit area should follow Android UX guidelines

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by yachtcaptain23** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/13038
