### ISSUE TITLE
Display a warning when sending a token to its own address [Crypto Wallets]

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12959]
Currently, tokens can be freely sent to their own smart contract address with no warnings or stops. At the very least, a warning should be provided to users when attempting to make this transaction.

## Test Plan
1. Initiate a send transaction.
2. Enter `0x0d8775f648430679a709e98d2b0cb6250d2887ef` as the recipient (BAT Smart contract)
3. Select BAT as the asset to send

## Actual Result
No warning displayed

## Expected Result
Warning displayed

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.58 Chromium: 88.0.4315.7 (Official Build) nightly (x86_64)
-- | --
Revision | `9b020863b2987261f6dcd018c6b388041c035f98-refs/branch-heads/4315@{#15}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.19 Dev`

- Verified warning message is shown when sending token to contract address
- ![image](https://user-images.githubusercontent.com/17010094/103883780-8edc7200-50d5-11eb-939b-bf4ecb8f0331.png)

------
Verification passed on 


Brave | 1.19.74 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Linux
Component | `1.0.19 Dev`

- Verified warning message is shown when sending token to contract address
![image](https://user-images.githubusercontent.com/17010094/103883894-b59aa880-50d5-11eb-93e0-ecf872c09030.png)

-------
Verification passed on 

Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Windows 10 OS Version 2009 (Build 19042.685)
Component | `1.0.19 Dev`

- Verified warning message is shown when sending token to contract address
![image](https://user-images.githubusercontent.com/17010094/103884050-f1ce0900-50d5-11eb-8d0a-5946308350eb.png)
