### ISSUE TITLE
[Desktop] Widevine does not work on M1/macOS-arm64

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12950]
## Description 

Unable to play Widevine on M1 chip macOS, works on Intel macOS.

## Steps to Reproduce

   1. Clean profile
   2. Navigate to netflix
   3. Login, allow widevine install (widevine does not install, but this isn't obvious)
   4. Attempt to stream a show.

## Actual result:

![netflix](https://user-images.githubusercontent.com/28145373/100671098-e268dc80-332d-11eb-8a0b-9104a0a193b6.png)

and on brave://components:
<img width="362" alt="Screen Shot 2020-11-30 at 9 25 14 AM" src="https://user-images.githubusercontent.com/28145373/100671114-e7c62700-332d-11eb-9a39-ab1327bf1c74.png">

## Expected result:
Able to stream netflix

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.19.41 Chromium: 87.0.4280.67 (Official Build) nightly (arm64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 11.0.1 (Build 20B29)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes 1.19.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bsclifton @rebron

**Comment by bridiver** [comment]
https://github.com/brave/brave-browser/issues/13074
