### ISSUE TITLE
[Desktop] sometimes tips don't show in Tips panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12963]
## Description 

I noticed yesterday that sometimes when I made a one time tip it did not show in the Tips panel on brave://rewards. It did show in my summary and was deducted from my wallet balance, but the creator I tipped/amount was not shown in the panel.

## Steps to Reproduce

   1. Clean profile, staging env
   2. Dismiss any onboarding modal you encounter (panel, brave://rewards, tip banner)
   3. Claim UGP grant
   4. Navigate to a verified site (ex. laurenwags.github.io)
   5. Do a one time tip for the site

## Actual result:

Sometimes you will see the tip listed on brave://rewards in the Tips panel, sometimes you will not

## Expected result:
Successful one time tip should always be listed in the Tips panel

## Reproduces how often: 

intermittent

## Brave version (brave://version info)

1.18.66, 1.19.41

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure
- Can you reproduce this issue with the beta channel? yes 1.18.x
- Can you reproduce this issue with the nightly channel? yes 1.19.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @marshall @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced once in Windows 10 x64:

```

Brave | 1.18.66 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
