### ISSUE TITLE
Vimeo pubs info is not getting downloaded 1.18.68 onwards

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12968]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/6462
Vimeo pubs info is not getting downloaded 1.18.68 onwards

## Steps to Reproduce

   1. Clean profile 1.18.68 launch brave using staging flag
   2. Enable rewards via BR panel
   3. Claim UGP grants
   4. Open https://vimeo.com/willchristiansen or https://vimeo.com/bravelaurenwags in NTP
   5. Click on BR panel 
   6. Pubs info isn't displayed 

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/100778419-0232fa00-342d-11eb-8a83-813518e4e549.png)
![image](https://user-images.githubusercontent.com/38657976/100778469-0ced8f00-342d-11eb-92db-46fae340689f.png)

## Expected result:

Pubs info should be shown in BR panel
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.68 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @marshall @emerick @rebron

**Comment by emerick** [comment]
@GeetaSarvadnya Does a browser restart between steps 2 and 3 fix this for you?

**Comment by GeetaSarvadnya** [comment]
@emerick I have verified the issue again in `1.18.69`. Restart the browser did not fix the issue. The issue is still reproducible

**Comment by emerick** [comment]
Vimeo and Twitch are configured in `Greaselion.json` as requiring a minimum Brave version of `1.19`. From what I recall, they didn't make the cutoff for 1.18.

cc: @marshall

**Comment by LaurenWags** [comment]
Vimeo was working in 1.18.x and component version 1.0.38 per https://github.com/brave/brave-browser/issues/11465#issuecomment-733749523/

Could be related to updated component version 1.0.39?

**Comment by emerick** [comment]
@LaurenWags Yep, you're exactly right. When we added auto-contribution support to Greaselion, base Vimeo support was accidentally changed to target 1.19; only Vimeo a-c should target 1.19. This is the commit that did it: https://github.com/brave/brave-site-specific-scripts/commit/a9d8e63e05d0660868a2cda47f77b707010c3e16#diff-d8a0512d00370bd50bcfb84761c13fb01190e05f68b97785805735b6d9e0f19cL104. Will fix, thank you!

**Comment by emerick** [comment]
Fix will be in Greaselion `1.0.40`.

**Comment by kjozwiak** [comment]
**`Staging`** - Running through https://vimeo.com/bravelaurenwags and ensured that all the information is correctly being displayed via the panels as per the following:

**`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/103697856-80c01180-4f6e-11eb-926b-88c53c1c90b6.png) | ![image](https://user-images.githubusercontent.com/2602313/103698111-de545e00-4f6e-11eb-9ba3-ca2e05f32971.png) | ![image](https://user-images.githubusercontent.com/2602313/103698133-e6140280-4f6e-11eb-9902-43da2417546f.png)

**`Staging`** - Running through https://vimeo.com/willchristiansen and ensured that all the information is correctly being displayed via the panels as per the following:

**`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/103698582-89651780-4f6f-11eb-87cf-48dbc06b5b8f.png) | ![image](https://user-images.githubusercontent.com/2602313/103698650-a26dc880-4f6f-11eb-8111-cc9f9afb4b82.png) | ![image](https://user-images.githubusercontent.com/2602313/103698670-ab5e9a00-4f6f-11eb-9d94-362071e28ea5.png)

**`Production`** - Running through https://vimeo.com/willchristiansen and ensured that all the information is correctly being displayed via the panels as per the following:

**`Example`** | **`Example`** 
---------------|---------------
![image](https://user-images.githubusercontent.com/2602313/103698984-38a1ee80-4f70-11eb-8815-806057338275.png) | ![image](https://user-images.githubusercontent.com/2602313/103699001-40619300-4f70-11eb-84d0-5ec136a25191.png)

Also went through the following cases:

* ensured that you can tip both https://vimeo.com/bravelaurenwags & https://vimeo.com/willchristiansen
* ensured that you can set `Monthly Contributions` via the rewards panel
* ensured that the social media buttons under the https://vimeo.com/bravelaurenwags banner work as expected

**Comment by kjozwiak** [comment]
Only thing that I noticed is that visiting https://vimeo.com/willchristiansen doesn't always display the verified checkmark via the rewards panel. But a refresh always fixes the issue. @LaurenWags let me know if you run into the above as well.

**Comment by LaurenWags** [comment]
Can confirm I see the same as @kjozwiak in https://github.com/brave/brave-browser/issues/12968#issuecomment-754902274 on `staging`, however this does not occur on `production`.
