### ISSUE TITLE
[Desktop] missing bubble in URL bar to enable javascript

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12973]
## Description 

If you have scripts blocked on a site in the URL bar there's usually a bubble displayed/accessible for you to re-enable scripts. This is missing in 1.19.x

## Steps to Reproduce

   1. Clean install
   2. Navigate to blizzard.com
   3. Open shields and go to advanced view
   4. Toggle "Scripts blocked" to on

## Actual result:

No bubble in the URL bar:
<img width="1195" alt="Screen Shot 2020-12-01 at 3 21 39 PM" src="https://user-images.githubusercontent.com/28145373/100792867-4d2b1e00-33e9-11eb-8de3-a30f668e809f.png">

## Expected result:
Bubble in URL bar like in 1.18.x:
<img width="1193" alt="Screen Shot 2020-12-01 at 3 19 03 PM" src="https://user-images.githubusercontent.com/28145373/100792916-603dee00-33e9-11eb-865a-65e308b5bd1f.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.19.43 Chromium: 87.0.4280.67 (Official Build) nightly (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.15.7 (Build 19H15)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.17.x no
- Can you reproduce this issue with the beta channel? 1.18.x no
- Can you reproduce this issue with the nightly channel? 1.19.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by bsclifton** [comment]
I thought this was removed on purpose? cc: @diracdeltas

**Comment by LaurenWags** [comment]
If so, please close. Thanks! 😄

**Comment by diracdeltas** [comment]
@LaurenWags yep, we removed it on purpose.

**Comment by bsclifton** [comment]
Here we go - removed with https://github.com/brave/brave-core/pull/7148 😄

**Comment by LaurenWags** [comment]
perfect, thanks @bsclifton @diracdeltas!
