### ISSUE TITLE
remove line for Total from wallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1297]
## Description 
Per discussion it was decided to remove the line item for 'Total' from the current Rewards Summary display (to be renamed per https://github.com/brave/brave-browser/issues/1296).

This info is accessible from the Wallet panel/container on Brave Rewards Main Page as well as on the Brave Rewards Panel (accessible from BAT logo in URL bar).

![screen shot 2018-09-26 at 3 11 25 pm](https://user-images.githubusercontent.com/28145373/46103672-6b5cba00-c19f-11e8-9651-d55aac6868d9.png)

cc @davidtemkin @kjozwiak @srirambv @NejcZdovc @jenn-rhim @mandar-brave

**Comment by kjozwiak** [comment]
@LaurenWags mind adding some test cases into the original issue and adding the `QA/Test-Plan-Specified` label? Thanks!

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/46758552-19d22600-cc9b-11e8-8e59-143241e04622.png)
