### ISSUE TITLE
[Desktop] Brave Today p3a

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#12974]
```
Did you scroll down on the NTP and see Brave Today?
No
Yes

How many times did you start a new Brave Today session last week?
None
1 session
2 to 3 sessions
4 to 7 sessions
8 to 12 sessions
13 to 18 sessions
19 to 25 sessions
More than 25 sessions

What was the highest number of cards viewed in a Brave Today session?
None
1 card
2 to 4 cards
5 to 12 cards
11 to 20 cards
21 to 40 cards
41 to 80 cards
More than 80 cards

What was the highest number of cards clicked in a Brave Today session?
None
1 card
2 to 3 cards
4 to 6 cards
7 to 10 cards
11 to 15 cards
More than 15 cards
```

###     "Brave.Today.HasEverInteracted",
0. Fresh profile
1. Open NTP
2. Scroll down to see some Brave Today content
3. p3a metric should be `1`

###     "Brave.Today.WeeklySessionCount",
p3a metric should reflect the bucket (as above) of the amount of times Brave Today has been scrolled to.

###  "Brave.Today.WeeklyMaxCardViewsCount",
_Counts how many cards have been scrolled down to per session (i.e. scroll depth)_
0. Fresh Profile
1. Open NTP
2. Scroll down a little bit
--> Observe: p3a metric should show a lower bucket (described above) to describe the amount of cards viewed in this session
4. Start a new Brave Today session and scroll much further
--> Observe: p3a metric should now show a higher bucket
5. Start a new Brave Today session and only scroll a little amount
--> Observe: p3a metric should still be at the previous higher bucket

###  "Brave.Today.WeeklyMaxCardVisitsCount",
_Counts how many cards have been clicked per session (either clicking then going back then clicking another, or by cmd/ctrl-clicking more than 1)_
0. Fresh Profile
1. Open NTP
2. Click a Brave Today content card
--> Observe: p3a metric should show a lower bucket (described above) to describe the amount of cards viewed in this session
4. Start a new Brave Today session and click a card
--> Observe: p3a metric should still show the lower bucket as this is a new session and we've only clicked 1 card
5. Navigate back and click another card
--> Observe: p3a metric should now show a higher bucket
5. Repeat: Navigate back and click another card
--> Observe: p3a metric should now show an even higher bucket

**Comment by petemill** [comment]
Closed via https://github.com/brave/brave-core/pull/7245

**Comment by btlechowski** [comment]
Blocked this will get a new build (> 1.18.69)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2009 (Build 19042.630)
```

However, both `Brave.Today.WeeklyMaxCardViewsCount` & `Brave.Today.WeeklyMaxCardVisitsCount` are not working and will be addressed via https://github.com/brave/brave-browser/issues/13096 & https://github.com/brave/brave-browser/issues/13097.

**`Case "Brave.Today.HasEverInteracted"`**

* launched `1.18.70 CR: 87.0.4280.101`
* opened a NTP and scrolled down to view Brave Today
* checked `brave://local-state` and ensured that `Brave.Today.HasEverInteracted` is `1`

```
"Brave.Today.HasEverInteracted": {
   "sent": false,
   "value": "1"
```

**`Case "Brave.Today.WeeklySessionCount"`**

* launched `1.18.70 CR: 87.0.4280.101`

Initially visiting/scrolling Brave Today:

```
"Brave.Today.WeeklySessionCount": {
   "sent": false,
   "value": "1"
```

2-3 Brave Today visit/scrolls:

```
"Brave.Today.WeeklySessionCount": {
   "sent": false,
   "value": "2"
```

4-7 Brave Today visit/scrolls:

```
"Brave.Today.WeeklySessionCount": {
   "sent": false,
   "value": "3"
```

8-12 Brave Today visit/scroll:

```
"Brave.Today.WeeklySessionCount": {
   "sent": false,
   "value": "4"
```

13-18 Brave Today visit/scroll:

```
"Brave.Today.WeeklySessionCount": {
   "sent": false,
   "value": "5"
```

19-25 Brave Today visit/scroll:

```
"Brave.Today.WeeklySessionCount": {
   "sent": false,
   "value": "6"
```

25+ Brave Today visit/scroll:

```
"Brave.Today.WeeklySessionCount": {
   "sent": false,
   "value": "7"
```

**Comment by kjozwiak** [comment]
Both `Brave.Today.WeeklyMaxCardViewsCount` & `Brave.Today.WeeklyMaxCardVisitsCount` and will be address/QA'd via https://github.com/brave/brave-browser/issues/13097 & https://github.com/brave/brave-browser/issues/13096.
