### ISSUE TITLE
Should not redirect in IPFS network delegate when resolve method is disabled or IPFS is disabled

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#12978]
## Description 

Follow-up of https://github.com/brave/brave-core/pull/7194.
`OnBeforeURLRequest_IPFSRedirectWork` in `browser/net/ipfs_redirect_network_delegate_helper.cc` should check if IPFS resolve method and the feature itself is enabled or not before doing the redirect.

## Steps to Reproduce

   1. Set IPFS resolve method to disabled in settings
   2. Visit ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR

## Actual result:
URL is redirected to https://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi.ipfs.dweb.link/.

## Expected result:
URL should not be redirected.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)

Nightly

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
full test plan is specified in https://github.com/brave/brave-core/pull/7307

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.19.81 Chromium: 87.0.4280.141 (Official Build) dev (x86_64)
-- | --
Revision | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS | macOS Version 10.15.7 (Build 19H15)
```

Verified test plan from https://github.com/brave/brave-core/pull/7307#issue-530653760

<details>
<summary>Method to resolve IPFS resources=Gateway</summary>

Set "Method to resolve IPFS resources" to "Gateway" in settings:
<img width="1029" alt="Gateway" src="https://user-images.githubusercontent.com/28145373/104344763-9469fb80-54cb-11eb-8d6c-b089bb00110c.png">

Confirmed visiting provided URL, `ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`, in a Private window does not resolve:
<img width="1031" alt="Private-gateway" src="https://user-images.githubusercontent.com/28145373/104344776-9633bf00-54cb-11eb-81f0-c70b5fa30498.png">

Confirmed visiting provided URL, `ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`, in a Guest window does not resolve:
<img width="1026" alt="guest-gateway" src="https://user-images.githubusercontent.com/28145373/104344783-98961900-54cb-11eb-8960-3f273efacca1.png">

Confirmed visiting provided URL, `ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`, in a Tor window does not resolve:
<img width="1030" alt="Tor-gateway" src="https://user-images.githubusercontent.com/28145373/104344785-9a5fdc80-54cb-11eb-8fb2-b75e592383e8.png">

Confirmed visiting provided URL, `ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`, in a normal window does resolve using gateway URL, not ipfs:// scheme:
<img width="1030" alt="normal - gateway" src="https://user-images.githubusercontent.com/28145373/104344794-9c29a000-54cb-11eb-8ece-91de6a896b12.png">

</details>

<details>
<summary>Method to resolve IPFS resources=Disabled</summary>

Set "Method to resolve IPFS resources" to "Disabled" in settings:
<img width="1031" alt="Disabled" src="https://user-images.githubusercontent.com/28145373/104344805-9e8bfa00-54cb-11eb-8cb6-64c3b64a9fee.png">

Confirmed visiting provided URL, `ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`, in a normal window does not resolve:
<img width="1033" alt="normal-disabled" src="https://user-images.githubusercontent.com/28145373/104344810-a055bd80-54cb-11eb-8e0d-654c7d886725.png">

Also confirmed visiting provided URL in Private, Guest, and Tor windows does not resolve.

</details>
