### ISSUE TITLE
Yandex not being set as the default search engine in specific regions

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12979]
## Description 

Yandex should be the default search engine on clean/new installs in the following regions as per https://github.com/brave/brave-browser/issues/12327.

```
* Republic of Armenia (AM)
* Republic of Azerbaijan (AZ)
* Republic of Belarus (BY)
* Kyrgyz Republic (KG)
* Republic of Kazakhstan (KZ)
* Republic of Moldova (MD)
* Russian Federation (RU)
* Republic of Tajikistan (TJ)
* Turkmenistan (TM)
* Republic of Uzbekistan (UZ)
```

## Steps to reproduce 

   1. switch your language on your android device to one the regions mentioned above
   2. install & launch brave (used `1.19.43 CR: 87.0.4280.67` in this case)
   3. visit `Settings` and both `Standard Tab` & `Private Tab` should be set as `Yandex` and not `Google`

## Actual result 

Google is being set as the default search engine for the above regions instead of Yandex.

## Expected result

Yandex should be set as the default search engine for new installs in the regions mentioned via https://github.com/brave/brave-browser/issues/12327.

## Issue reproduces how often 

100% reproducible using the STR mentioned above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `N/A`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 2 XL` (Phone)
   - Android version: Android 11
   
## Brave version

* `1.19.43 CR: 87.0.4280.67`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @deeppandya @anthonypkeane

**Comment by bsclifton** [comment]
Marked as `release-notes/exclude` since we already have the parent issue for sharing Yandex in 10 regions as default 😄

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 with Android 5.1 running 1.18.70 Bravearm.apk

- Verified STR from description, confirmed `Yandex` on both Settings and selected via Onboarding
- Verified items from https://github.com/brave/brave-core/pull/7376#issuecomment-741524745 for Armenian and Russian.
- Confirmed that `Yandex` was selected as the default search engine for `Armenian` and `Russian` 
- Confirmed that updating from `1.17.75 CR: 87.0.4280.88` --> `1.18.70 Chromium: 87.0.4280.101` didn't replace the previous default SE with `Yandex`

**`Note:`** Some of these regions don't have any localization but I confirmed that:
 - `Yandex` is being set as the default
 - `Yandex` is available via the SE onboarding

#### **`Armenian`**
**`Onboarding`**| **`Settings`**| 
----------------|------------------
![Armenian Onboarding](https://user-images.githubusercontent.com/28145373/101640225-41011b00-39fe-11eb-9b74-10626d006552.png) | ![Armenian Settings](https://user-images.githubusercontent.com/28145373/101640239-465e6580-39fe-11eb-864e-42f960cd4051.png)

#### **`Russian`**
**`Onboarding`**| **`Settings`**| 
----------------|------------------
![Russian Onboarding](https://user-images.githubusercontent.com/28145373/101640260-4c544680-39fe-11eb-9788-1550be08f070.png) | ![Russian Settings](https://user-images.githubusercontent.com/28145373/101640272-4fe7cd80-39fe-11eb-852f-cf6ad64f3482.png)
