### ISSUE TITLE
Scrollbars no longer transparent on MacOS

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#12981]
## Description 

There are blocky scroll bars showing on MacOS instead of the mostly transparent uninvasive kind.

## Steps to Reproduce

   1. Go to page with scrolling
   2. 
   3. 

## Actual result:

Has a big ugly scroll bar

## Expected result:
Should be the type of scrollbar it used to be: transparent background, thin bar

## Reproduces how often: 

Everywhere

## Brave version (brave://version info)

```
1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)
--
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G103)
JavaScript | V8 8.7.220.25
Flash | 32.0.0.303 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SephReed** [comment]
This appears to be a MacOS issue

**Comment by bwoodruff** [comment]
Is this the same issue?
https://www.reddit.com/r/brave_browser/comments/knv8qi/scrollbars_dont_obey_dark_mode_on_macos/
