### ISSUE TITLE
Navigation Bar UI at the bottom should not be translucent when a Brave ad is visible

### ISSUE THREAD

**Issue by yachtcaptain23** [brave/brave-browser#12989]
![image](https://user-images.githubusercontent.com/8647607/116725464-c9289280-a996-11eb-824c-8f33b7539399.png)

Hard to see, but the bottom navigation bar is set to translucent at the bottom. I believe the window flags of the dialog are causing the bottom nav to be set to translucent when the window gets drawn. 

Currently the flags are `0x0182002a` for the window, and I would think having `wlp.flags &= ~WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION;` would fix this issue, but it doesn't seem to be clearing the flag.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.59 x64 Beta Build
- Verified bottom toolbar doesn't become translucent when custom ad notification is shown 

Light Mode | Dark Mode 
-- | --
![image](https://user-images.githubusercontent.com/17010094/121888098-7cfb9c80-cd0f-11eb-88b8-c78d4e5ce85b.png) | ![image](https://user-images.githubusercontent.com/17010094/121889129-c0a2d600-cd10-11eb-9210-67ff32b2d61a.png)
