### ISSUE TITLE
add partial month to Monthly Statement

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1298]
## Description 
Per discussion it was decided to add the current partial month to the Monthly Statement dropdown.

![screen shot 2018-09-26 at 3 26 36 pm](https://user-images.githubusercontent.com/28145373/46104137-9abff680-c1a0-11e8-8a75-6e4193ffaff0.png)

cc @davidtemkin @kjozwiak @srirambv @NejcZdovc @jenn-rhim @mandar-brave

**Comment by mandar-brave** [comment]
Issue fix will be pushed to 0.57 via https://github.com/brave/brave-browser/issues/930; same PR fix for both issues.

cc @NejcZdovc
