### ISSUE TITLE
Brave Ads crash querying database

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#12993]
## Steps to Reproduce

   1. Launch browser
   2. Delete `database.sqlite`
   3. View an ad

## Actual result:

Browser crashes

## Expected result:
Browser should not crash

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed on macOS using

```
Brave | 1.18.74 Chromium: 87.0.4280.101 (Official Build) (x86_64)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 10.15.7 (Build 19H15)
```

Verification notes can be found under https://github.com/brave/internal/issues/741#issuecomment-747458840
