### ISSUE TITLE
[Android] "Welcome to Brave Rewards" messaging always displayed on panel open will not go away

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12992]
## Description 
Every time I open the rewards panel I always get the "Welcome to Brave Rewards" screen below, even after taking the tour. It seems as though this screen can't be dismissed. As such, I can never see publisher info.

## Steps to reproduce 

   1. Clean install 1.18.x or 1.19.x
   2. Visit a site (ex. brave.com)
   3. Open rewards panel, see "Welcome to Brave Rewards" messaging/tour
   4. No way to dismiss this, so take the tour.
   5. At the end of the tour, no publisher info displayed on panel.
   6. Close and roepen panel.

## Actual result 
"Welcome to Brave Rewards" messaging is displayed again, it won't go away. Even if you enable Ads/AC from chrome://rewards, this still remains on the panel. 
![Screenshot_2020-12-02-11-07-52](https://user-images.githubusercontent.com/28145373/100898693-07289580-348f-11eb-8ab2-1a0c7f9639d7.png)

## Expected result
This messaging should not show every single time the panel is opened. Once is enough.

## Issue reproduces how often 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? no
- Can you reproduce this issue with the current Play Store Beta version? yes 1.18.67 Beta
- Can you reproduce this issue with the current Play Store Nightly version? Yes 1.19.43

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.18.67, 1.19.43

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? unable to disable BR
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @deeppandya @anthonypkeane @kjozwiak

**Comment by LaurenWags** [comment]
Closed via https://github.com/brave/brave-core/pull/7378

**Comment by GeetaSarvadnya** [comment]
Verification passed on Gonee s5 running `Bravearm 1.18.71`
- Verified the STR from the description
![Screenshot_2020-12-11-20-22-21](https://user-images.githubusercontent.com/38657976/101918707-ad8f3c00-3bef-11eb-940b-8676594da094.png)
![Screenshot_2020-12-11-20-25-33](https://user-images.githubusercontent.com/38657976/101918713-af58ff80-3bef-11eb-9aa8-59734f02011b.png)
![Screenshot_2020-12-11-20-25-52](https://user-images.githubusercontent.com/38657976/101918717-aff19600-3bef-11eb-9343-c7bb0d98cba4.png)
![Screenshot_2020-12-11-20-25-56](https://user-images.githubusercontent.com/38657976/101918719-b08a2c80-3bef-11eb-92a0-b2773607d518.png)
![Screenshot_2020-12-11-20-26-05](https://user-images.githubusercontent.com/38657976/101918720-b122c300-3bef-11eb-9ee6-2d4c1cf663ec.png)
