### ISSUE TITLE
Enable Safety Tips

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#12999]
## Description 
Safety Tips warnings are displayed for lookalike/phishing URLs

<img width="391" alt="Screen Shot 2020-12-02 at 10 15 11 AM" src="https://user-images.githubusercontent.com/1903815/100913950-4c48c980-3487-11eb-8a20-0095a56af5b4.png">

The components contains a protobuf of allowed domains to mitigate false positives of client-side heuristics.

**Comment by mherrmann** [comment]
At the moment, Safety Tips appears in brave://components as version `0.0.0.0` and stays this way forever. My fix for #8709. Will actually remove this zombie appearance of Safety Tips. But whoever implements this present issue to bring it back can simply look at my fix and remove Safety Tips from the list of blacklisted components.

**Comment by LaurenWags** [comment]
@fmarier looks like the UI is different than mentioned in https://github.com/brave/brave-core/pull/7521#issue-548597124, although it does match Chrome. Just want to confirm this is expected.

```
Brave | 1.20.87 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

```
Google Chrome | 88.0.4324.96 (Official Build) (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

Brave | Chrome
----- | -----
<img width="807" alt="Brave" src="https://user-images.githubusercontent.com/28145373/105523165-13211e80-5cac-11eb-8256-ab2c133bcae0.png"> | <img width="630" alt="Chrome" src="https://user-images.githubusercontent.com/28145373/105523168-14524b80-5cac-11eb-9fcb-4a1834778d22.png">

**Comment by fmarier** [comment]
Thanks @LaurenWags. I suspect I took my screenshot before the latest Chromium bump.

The fact that there is a popup at all means that the feature is working. :+1:

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.20.87 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

Verified test plan from https://github.com/brave/brave-core/pull/7521#issue-548597124

Confirmed `Certificate Error Assistant` and `Safety Tips` are listed on brave://components.
Confirmed after ~1 minute they each installed and got non-zero version numbers.

Certificate Error Assistant | Safety Tips
----- | -----
<img width="290" alt="cert err ast - installed" src="https://user-images.githubusercontent.com/28145373/105550839-e41ca400-5ccf-11eb-8458-5deaf08d27b5.png"> | <img width="294" alt="safety tips - installed" src="https://user-images.githubusercontent.com/28145373/105550843-e54dd100-5ccf-11eb-8465-aac509f5eea3.png">

Confirmed visiting https://badssl.com/test/safety-tips/ shows notification:
<img width="666" alt="Screen Shot 2021-01-22 at 4 31 20 PM" src="https://user-images.githubusercontent.com/28145373/105550939-044c6300-5cd0-11eb-9cf7-a504603f5f23.png">

-------------
