### ISSUE TITLE
Downloads take a while before finishing

### ISSUE THREAD

**Issue by ristein** [brave/brave-browser#12991]
## Description 

when downloading something it takes up to 10secs before the file is ready after the actual downloading is finished.

## Steps to Reproduce

   1. download something
   2. wait for the green bar to be finished
   3. stop the time before the file is in file explorer or until you can directly open it

## Expected result:
after green bar is finished, the file is ready to use

## Reproduces how often: 

time varies between 3 and ten seconds

## Brave version (brave://version info)

1.17.73

**Comment by Dryader** [comment]
If I recall correctly one of the reasons it might be taking time to open is Windows Security is scanning it and as such the speed of the scan is related to your CPU performance and is not related to Brave's performance .

**Comment by rebron** [comment]
@Dryader We don't have enough information to address this issue. Sounds like might be a system or 3rd party anti-virus check or something else? I'm not sure I would consider 10 seconds awhile. Several minutes is awhile and would be more troubling.

**Comment by Dryader** [comment]
> @Dryader We don't have enough information to address this issue. Sounds like might be a system or 3rd party anti-virus check or something else? I'm not sure I would consider 10 seconds awhile. Several minutes is awhile and would be more troubling.

@rebron I think you may have tagged me incorrectly?

**Comment by rebron** [comment]
@ristein We don't have enough information to address this issue. Sounds like might be a system or 3rd party anti-virus check or something else? I'm not sure I would consider 10 seconds awhile. Several minutes is awhile and would be more troubling.

Thanks @Dryader. Sorry about that and your comment I think is right. This is likely a Windows Security scan.

**Comment by ristein** [comment]
I'm sorry, for that little information.
I hoped for someone else stating also knowing this.
I guessed it wouldn't have to do with anything else besides the browser since if i close the browser in this process, the file will get deleted.
I'm running a Ryzen 2600 with 6/12 cores on 3.4GHz, so I thougt a small file with less than 3mb shouldn't cause Windows to scan it for few seconds.
How can I provide more information?

**Comment by bsclifton** [comment]
@ristein
- what version of Windows are you running?
- does this happen in other browsers?
- do you have the ability to turn off anti-virus software  / Windows Security scans (temporarily) to see if that is the issue?

Thanks for the assist @Dryader 😄

**Comment by ristein** [comment]
@bsclifton 
thank you all for your answers and time.
I just tested again on my PC with the Ryzen 2600 and the problem is gone.
I guess that 10sec delay was on my laptop once with a much weaker cpu.
So that delay seems to be the windows security scan, I will check that later when I have my laptop and will reply then.
Only strange that closing the browser in that time deletes the file.
Anyway sorry again for that little information

**Comment by bsclifton** [comment]
@ristein you're very welcome 😄 I'll go ahead and close the issue for now - but please report back if you see something again or if you have your laptop and try again
