### ISSUE TITLE
Privacy audit to create MVP list of things we should disable in Chromium

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13]
Emphasis on MVP for something we'd be able to release as 1.0. This should be similar to what we have privacy wise with Muon.  This is just a task for the audit itself.

**Comment by diracdeltas** [comment]
also:
- [ ] battery API
- [ ] webusb API
- [ ] bluetooth API
- [ ] 3rd party dynamic HSTS/expect-CT/HPKP
- [ ] navigator.credentials
- [ ] SharedArrayBuffer

**Comment by diracdeltas** [comment]
- [ ] disable inline extensions: https://developer.chrome.com/webstore/inline_installation

**Comment by diracdeltas** [comment]
Here's the default settings as of Developer Channel v0.53.0:
![screen shot 2018-07-30 at 7 53 27 pm](https://user-images.githubusercontent.com/549654/43434884-74c3b034-9432-11e8-829c-cfcac3737836.png)


- [ ] Consider disabling "Allow sites to check if you have payment methods saved"
