### ISSUE TITLE
Dapp detection, Crypto Wallets infobar, should be removed.

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#13009]
## Test Plan
1. Clean profile, Navigate to a dapp, such as `https://cryptokitties.co`
2. Ensure that the "Setup" infobar does not appear
3. Navigate to `brave://wallet`
4. Install and set up Crypto Wallets
5. Navigate to `brave://settings/extensions` and ensure provider is set to Crypto Wallets
6. Confirm "Ask" is no longer an option under provider
7. Navigate and connect to a dapp, ensure CW can interact with the dapp.

**Comment by bbondy** [comment]
Superseded by https://github.com/brave/brave-browser/issues/14018
