### ISSUE TITLE
[Android] add onboarding modal to chrome://rewards page

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13008]
## Description 
When you open the panel there is an onboarding modal/overlay (in 1.20.5, will be included in 1.18.x). 

This same overlay should be displayed when visiting chrome://rewards page.

## Steps to reproduce 

   1. Clean install
   2. Navigate to chrome://rewards page
 

## Actual result 
no onboarding modal

## Expected result
should see onboarding modal (ex. https://www.figma.com/file/0dbMYs8Wp8W3RgrG1yTdki/RE-1.0?node-id=1329%3A0)

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.18.x, 1.20.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards?n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information

cc @codybanxs @deeppandya @anthonypkeane

**Comment by LaurenWags** [comment]
Closed via https://github.com/brave/brave-core/pull/7378

**Comment by GeetaSarvadnya** [comment]
Verification passed on Gionee s5 running on `Bravearm 1.18.71`
- Verified STR from the description
![Screenshot_2020-12-11-22-10-15](https://user-images.githubusercontent.com/38657976/101930326-01088680-3bfe-11eb-82e1-60c3f0da1dae.png)
