### ISSUE TITLE
Brave Not Opening After Installation - UBUNTU 20.04

### ISSUE THREAD

**Issue by developeranaz** [brave/brave-browser#13003]
Brave doesn't opening.
In UBUNTU 20.04 Bionic
Want to use TOR help!

**Comment by Brave-Matt** [comment]
@developeranaz,
Thank you for reaching out. 
Since this is a support issue/request, would you mind posting this to our support [forum](https://community.brave.com) directly so we can better assist you? Feel free to tag me (@mattches) in your post and I'd be happy to help.
Thank you.
