### ISSUE TITLE
Update icons for macOS 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#13005]
## Description 

Update icons for macOS Big Sur similar to iOS/rounded square icons to be consistent with other apps on macOS

## Actual result:

![88846180-dcf65c80-d1aa-11ea-901b-67a113d40a5a](https://user-images.githubusercontent.com/5951041/100924521-99cc3300-3495-11eb-9ee5-58afefe86ae8.jpg)

## Expected result:
Icons should be a little larger than the previous round and have a white background.

<img width="992" alt="Screen Shot 2020-12-04 at 11 37 32 AM" src="https://user-images.githubusercontent.com/2388823/101207182-1a6d6980-3625-11eb-98fc-76a4ba6045a0.png">

Iconsets: https://drive.google.com/drive/folders/1jIDrXtv2tHNtlz4Qiqj4Lkbfb2ft9LIX?usp=drive_fs

## Reproduces how often: 

n/a

## Brave version (brave://version info)

Target for 1.19.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

First try with https://github.com/brave/brave-browser/issues/11002 but icons came out to small. Using this issue as follow-up.

**Comment by simonhong** [comment]
It would be good to have new icon for development build (grayed one)

**Comment by karenkliu** [comment]
@simonhong Designs added! I included the development build too.

**Comment by stephendonner** [comment]
This is looking good on macOS Big Sur (11.1 (20C69)), for the following icons:

- Brave Beta
- Brave Dev
- Brave Nightly

Still pending:

- Looks like we'll need a Release Preview/Release Candidate to verify on the Release channel
- Also need someone with a (self-built?) developer binary to show theirs, using Big Sur
- Probably a good idea for someone with Catalina to post theirs, as they shouldn't have changed there

**Comment by LaurenWags** [comment]
@stephendonner your Brave Nightly is old (1.19.x) - best to try on the latest Nightly from https://github.com/brave/brave-browser/releases. 

I noticed because your Nightly icon has a dark background whereas mine does not - and per the description each icon should have a white background. So, please give it another check on a updated Nightly. If you continue to have a dark background on your icon we'll want to follow up on that.

**Comment by LaurenWags** [comment]
Verified passed with the following versions using `macOS x64 Catalina`:

```
Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (x86_64)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | macOS Version 10.15.7 (Build 19H15)
```

```
Brave | 1.21.44 Chromium: 88.0.4324.146 (Official Build) beta (x86_64)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | macOS Version 10.15.7 (Build 19H15)
```

```
Brave | 1.21.45 Chromium: 88.0.4324.146 (Official Build) dev (x86_64)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | macOS Version 10.15.7 (Build 19H15)
```

```
Brave | 1.22.2 Chromium: 88.0.4324.146 (Official Build) nightly (x86_64)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | macOS Version 10.15.7 (Build 19H15)
```

<img width="324" alt="Screen Shot 2021-02-04 at 4 56 38 PM" src="https://user-images.githubusercontent.com/28145373/106960370-f9e78b80-6709-11eb-898e-e387485a1d48.png">

**Comment by andrewarchi** [comment]
I appreciate that this follows the design changes introduced by Chrome, but is there a flag to disable this? It is incongruous with the other icons in my dock and the white space bugs me. There are many common non-square icons: Firefox, VS Code, Messages, and many non-aligned icons including Mail, Notes, and Pages.

**Comment by zevrix** [comment]
Please give us an option to restore the original icon.

Brave's original icon is a masterpiece. There's no need to change anything. The new icon just looks as a mistake.

If you really just have to follow this shape while keeping an impressive icon, then this would be much better:

![brave-icon](https://user-images.githubusercontent.com/51013144/109080378-6bde3f80-76ce-11eb-8cb1-d85cf0a75aed.png)

**Comment by tre-dev** [comment]
I guess the look depends on the individual user, the icons next to it and possibly also the alignment of the dock. For me, the new version doesn't fit at all, it looks rather ugly tbh :/

![image](https://user-images.githubusercontent.com/59442299/109637032-8c821b80-7b4c-11eb-82a8-8c74447cec05.png)

**Comment by zevrix** [comment]
> For me, the new version doesn't fit at all, it looks rather ugly tbh :/

Absolutely. I love Brave but If they keep this icon, they also should change the name from **"Brave"** to **"Caged & Conquered"**.

**Comment by bsclifton** [comment]
cc: @bradleyrichter @karenkliu

**Comment by aparkerdavid** [comment]
Aesthetic debates over the squircle aside, this icon isn't *quite* right. It's a little too large, and the drop shadow is a little too deep. See: 
<img width="289" alt="Screen Shot 2021-03-13 at 1 29 03 PM" src="https://user-images.githubusercontent.com/6626101/111040353-a3ecbe80-8400-11eb-99a5-7a4def029ba9.png">
Apple publishes a template for Big-Sur-style icons, it should be possible to just drop in the Brave logo and get a pixel-perfect result.
