### ISSUE TITLE
Update brave-browser-releases logo

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#1301]
## Description 
Our update bot appears to be using a dated version of the Brave logo in the avatar. Just needs an update. The file in the comments is sized correctly to drop in. 
https://github.com/brave-browser-releases

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/29072694/46107088-50824980-c18f-11e8-90f7-7b7dfff10ed2.png)

**Comment by bbondy** [comment]
That github account seems to have no repos. Are you sure we use it?

**Comment by bbondy** [comment]
Also is it related to Brave core?

**Comment by rossmoody** [comment]
I only noticed it cause it seems to be the tiny icon that gets auto-used for our Github Core releases here: https://github.com/brave/brave-browser/releases
 
![image](https://user-images.githubusercontent.com/29072694/46187311-e2757980-c297-11e8-9eba-fa94a36c4340.png)

**Comment by bsclifton** [comment]
oh weird- I am not part of that org. I'm guessing @RyanJarv or @mbacchi may have access to this? Anyone with access would easily be able to update the image 😄

**Comment by mbacchi** [comment]
Yes, this is something @RyanJarv set up. I'm not sure I have access either.

**Comment by bbondy** [comment]
I don't see any repos created under that account though, do we actually use it for anything? In any case this is not a brave-browser issue so I'm closing this, it should be tracked maybe in brave/internal @rossmoody. Thanks.
