### ISSUE TITLE
Add Fanboy's Annoyance List in Brave Shield

### ISSUE THREAD

**Issue by Furax-31** [brave/brave-browser#13025]
## Description 

This list is present in uBlock but not Brave Shield

## Brave version (info found on brave://version)

Nightly 1.20.5

## Version/Channel Information:

All versions

## Miscellaneous Information:

Filter list : https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt

**Comment by Dryader** [comment]
Brave's blocking philosophy is to block non-privacy respecting ads and trackers. Newsletter popups for example are not considered to be non-privacy respecting. While you may consider them an annoyance as many others do, such as myself, others may not and is not the main point of Brave's blocking ideals.  Brave by default blocks trackers and ads, if you would like to use ublock origin with such a list you can download it on the chrome web store and enable it with ublock origin's settings.

**Comment by Furax-31** [comment]
Use uBlock when Brave has one built in?  You might as well stay on Firefox or Vivaldi ...

**Comment by Dryader** [comment]
> Use uBlock when Brave has one built in? You might as well stay on Firefox or Vivaldi ...
> And it's impossible use uBlock on Android.
> 
> It should at least be possible to add lists manually.

You did not specify your request was for android, as for adding lists manually they are planning to do that already for android as seen here: #12158
Also quoted from uBlock Origin's website itself: [https://ublockorigin.com/](url)
>uBlock Origin is not just an “ad blocker“, it's a wide-spectrum content blocker with CPU and memory efficiency as a primary feature.

**Comment by ryanbr** [comment]
Related: https://github.com/brave/adblock-lists/issues/438

**Comment by ryanbr** [comment]
Closing this, since https://github.com/brave/adblock-resources/pull/16  will cover it.
