### ISSUE TITLE
Autoplay blocked indicator is shown even though global autoplay settings is set to allowed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13027]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/10811
Autoplay blocked indicator is shown even though global autoplay settings is set to allowed

## Steps to Reproduce

   1. Clean profile `1.18.68`
   2. Open `brave://settings/content/autoplay` and set global autoplay settings to `Blocked`
   3. Open `https://www.escapistmagazine.com/v2/the-change-architect-is-a-free-glimpse-behind-the-scenes-of-a-tense-political-protest/` in a new tab and ensure autoplay blocked indicator is shown in the URL bar
   4. Navigate to `brave://settings/content/autoplay` and set global autoplay settings to `Allowed`
   5. Reload the `www.escapistmagazine.com` which is opened in step 3
   6. Autoplay blocked indicator is shown in the URL bar
   7. Open `brave://settings/clearBrowserData` and delete all-time browsing data
   8. Repeat step 5
   9. Autoplay blocked indicator is still shown in the URL bar
   

## Actual result:

Autoplay blocked indicator is shown even though global autoplay settings is set to allowed

## Expected result:
Autoplay blocked indicator should not be shown when global autoplay settings is set to allowed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.18.68 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @darkdh @pes10k @rebron

**Comment by darkdh** [comment]
did you see the ask prompt? if so it is actually the duped of https://github.com/brave/brave-browser/issues/12795

**Comment by darkdh** [comment]
could you open `Preference` file under your profile to see if there is a `"default_content_setting_values": {"autoplay":3}`?

**Comment by GeetaSarvadnya** [comment]
@darkdh I am seeing the ask prompt below when global autoplay is "Blocked" or "Allowed"
![image](https://user-images.githubusercontent.com/38657976/101592607-91837300-3a14-11eb-8322-701ef7047ba8.png)

**Comment by darkdh** [comment]
sorry I meant this prompt
<img width="359" alt="Screen Shot 2020-12-08 at 22 22 14" src="https://user-images.githubusercontent.com/11330831/101592893-dc18d700-39a3-11eb-9ca4-008b5b88b5c3.png">

**Comment by GeetaSarvadnya** [comment]
@darkdh I am seeing the `"default_content_setting_values":{"autoplay":2,"cookies":1}` in Preference file.

**Comment by GeetaSarvadnya** [comment]
@darkdh I am getting the Ask Promot on YT only when global autoplay is "Allowed"

![image](https://user-images.githubusercontent.com/38657976/101594448-af060c00-3a17-11eb-8e0f-317c7928d5ae.png)

**Comment by darkdh** [comment]
That is the bug of #12795

**Comment by darkdh** [comment]
And if you check `default_content_setting_values` again after exiting Brave, you will see `"autoplay": 3`

**Comment by GeetaSarvadnya** [comment]
Now I could see `"default_content_setting_values":{"autoplay":3,"cookies":1},` in Preference file. I am ging to close the issue as dup of #12795
