### ISSUE TITLE
Crypto.com widget unavailable in widget stack

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#13036]
Introduced by: https://github.com/brave/brave-core/pull/7253

## Description 
Crypto widget is unavailable in the widget stack/gallery

## Steps to Reproduce
   1. Clean profile in a crypto.com supported region
   2. Navigate to `brave://newtab`

## Actual result:
Crypto.com not in the default widget stack, not in the gallery

## Expected result:
Should be in the default widget stack, and in the gallery

## Reproduces how often: 
100%

## Brave version (brave://version info)
Nightly 1.20.6

- Can you reproduce this issue with the current release? 
No
- Can you reproduce this issue with the beta channel? 
No
- Can you reproduce this issue with the nightly channel? 
Yes

**Comment by stephendonner** [comment]
Verified using testplan given, on an en-US build + region, that opening the NTP shows the Crypto.com widget, in:


Brave | 1.20.88 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

<img width="1680" alt="Screenshot 2021-01-25 at 15 08 44" src="https://user-images.githubusercontent.com/387249/105777598-841c3c80-5f1f-11eb-924d-95ef21eada9e.png">
<img width="298" alt="Screenshot 2021-01-25 at 15 10 33" src="https://user-images.githubusercontent.com/387249/105777610-87afc380-5f1f-11eb-97bf-d5fcb683d920.png">
<img width="719" alt="Screenshot 2021-01-25 at 15 11 40" src="https://user-images.githubusercontent.com/387249/105777691-af069080-5f1f-11eb-9953-edf6261f5607.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Linux

- Verified Crypto.com widget is available in the stack 
![image](https://user-images.githubusercontent.com/17010094/107003143-38ba2780-6784-11eb-8f52-f571e4435c31.png)
- Verified able to view markets and graphs for tokens
![image](https://user-images.githubusercontent.com/17010094/107004094-b16db380-6785-11eb-825e-7dcc287d5b31.png)
- Verified able to Add/Remove via edit card settings 
![image](https://user-images.githubusercontent.com/17010094/107004366-16290e00-6786-11eb-9191-146667fbb304.png)
- Verified Crypto.com is not available for unsupported locales
![image](https://user-images.githubusercontent.com/17010094/107004577-67390200-6786-11eb-93d5-e883ede9d1c5.png)

---------
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Windows 10 OS Version 2009 (Build 19042.746)

- Verified Crypto.com widget is available in the stack 
![image](https://user-images.githubusercontent.com/17010094/107004654-80da4980-6786-11eb-9ad9-b17d5a32197a.png)
- Verified able to view markets and graphs for tokens
![image](https://user-images.githubusercontent.com/17010094/107004809-bd0daa00-6786-11eb-9bc4-8cbde379042d.png)

- Verified able to Add/Remove via edit card settings 
![image](https://user-images.githubusercontent.com/17010094/107004848-cb5bc600-6786-11eb-94e2-52d7df6db5b9.png)

- Verified Crypto.com is not available for unsupported locales
![image](https://user-images.githubusercontent.com/17010094/107006441-0828bc80-6789-11eb-873e-46aa7fa31848.png)
