### ISSUE TITLE
Blank White New Tab Page

### ISSUE THREAD

**Issue by okidokiokami** [brave/brave-browser#13039]
## Description 

Opening a NTP just gives a blank white page.

## Steps to Reproduce

   1. Restart Brave Nightly
   2. Open a new tab page

## Actual result:

White page.
![Screen Shot 2020-12-03 at 12 07 46 PM](https://user-images.githubusercontent.com/17419391/101092379-6b6e5680-356e-11eb-916c-099cf9036337.jpg)

## Expected result:
Background image with widgets displayed.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave | 1.20.7 Chromium: 87.0.4280.88 (Official Build) nightly (x86_64)
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | macOS Version 10.15.7 (Build 19H15)

## Version/Channel Information:

No

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by okidokiokami** [comment]
CC @rebron

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/brave-core/pull/7333

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
Revision	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS	macOS Version 10.15.7 (Build 19H15)
```

Verified STR from description with a clean profile.
Verified STR from description on an upgraded (from 1.19.82 Dev channel) profile.
Confirmed NTP is not blank.

<img width="1039" alt="Screen Shot 2021-01-20 at 11 47 15 AM" src="https://user-images.githubusercontent.com/28145373/105207215-42515780-5b15-11eb-9ae1-8f9f0c640bfd.png">
