### ISSUE TITLE
Migrate CONTENT_SETTING_ASK for Autoplay

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#13046]
Follow-up of https://github.com/brave/brave-browser/issues/12795

We used to have ASK content setting by default so if a user hasn't changed autoplay global setting, it will remain ASK even though we already changed default to ALLOW. And because of the bug we left changed default to ALLOW, a new user can still have ASK to be globally default and if the user once changed global setting to ALLOW before the fix for #12795 and hasn't changed the global setting after getting the fix for #12795.

So that is why we need to migrate and discard the ASK value for user and also remove ASK related code that is no longer used.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/7343

**1.18.68**

![image](https://user-images.githubusercontent.com/38657976/105176483-5152fc80-5b4b-11eb-9cee-906d30a68f44.png)

![image](https://user-images.githubusercontent.com/38657976/105176454-4a2bee80-5b4b-11eb-8333-7f9f1c32cf96.png)

Upgrade to **1.20.84**
![image](https://user-images.githubusercontent.com/38657976/105176628-7c3d5080-5b4b-11eb-9668-b6967e3b8553.png)
![image](https://user-images.githubusercontent.com/38657976/105176703-9414d480-5b4b-11eb-81ef-6c5a3b03c0ad.png)
![image](https://user-images.githubusercontent.com/38657976/105176791-bb6ba180-5b4b-11eb-936a-4568428cb2d5.png)
