### ISSUE TITLE
Update l10n (for 1.18.x release).

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#13040]
Download the latest l10n from Transifex.

Test plan:
Per prior @kjozwiak's instructions (#10735 (comment)):

@brave/legacy_qa should run through a few locals just to make sure that nothing obvious has regressed. Shouldn't spend too much time on this though.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave	1.18.70 Chromium: 87.0.4280.101 (ಅಧಿಕೃತವಾಗಿ ನಿರ್ಮಿಸಿ) (64-ಬಿಟ್)
ಪರಿಷ್ಕರಣೆ	9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS	Windows 10 OS Version 1809 (Build 17763.1637)

```

- Verified few areas like `NTP`, `Dashboard settings`, `Rewards and widgets`, `Shield settings`, `Hamburger menu items` etc translation in **Kannada**

`Brave Rewards`
![image](https://user-images.githubusercontent.com/38657976/101650829-658ede80-3a62-11eb-9caf-a0308473c7d0.png)
![image](https://user-images.githubusercontent.com/38657976/101650859-6d4e8300-3a62-11eb-9a56-b59efb01f7e3.png)
![image](https://user-images.githubusercontent.com/38657976/101650911-7b040880-3a62-11eb-86fd-1f032e3ed602.png)
![image](https://user-images.githubusercontent.com/38657976/101650980-90793280-3a62-11eb-984c-5901cc56e64d.png)
![image](https://user-images.githubusercontent.com/38657976/101651025-9bcc5e00-3a62-11eb-81cf-8630b317c9e7.png)
![image](https://user-images.githubusercontent.com/38657976/101651093-b272b500-3a62-11eb-85f9-39d06dd283e9.png)
![Uploading image.png…]()

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 with Android 5.1 running 1.18.70 Bravearm.apk
- Spot checked Settings, Widget, Rewards, NTP for French, German
- No obvious issues identified
- test plan from https://github.com/brave/brave-core/pull/7345 not applicable to Android
