### ISSUE TITLE
verified checkmark blends with default blue tipping banner

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13045]
## Description 

When using our default blue background via the tipping banner, the verification checkmark is hard to see/spot as it blends with the background. Maybe remove the blue background and add another colour that won't blend with the verified checkmark?

## Steps to Reproduce

   1. launch brave (`1.20.5 CR: 87.0.4280.67` in this case)
   2. initiate a tip and make sure you get the blue background for the tipping banner (might take a few attemtps)

## Actual result:

![Screenshot 2020-12-03 121503](https://user-images.githubusercontent.com/2602313/101119105-98dff200-35b8-11eb-85bb-717be13a9a66.png)

## Expected result:

Verified checkmark should be easier to see and shouldn't blend with the tipping background

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.20.5 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2009 (Build 19042.630)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @marshall @LaurenWags

**Comment by Miyayes** [comment]
@karenkliu Any thoughts on this? With the white border around the checkmark, I can see it. But maybe it is harder to see for others.

**Comment by Miyayes** [comment]
Superseded by banner 3.0
