### ISSUE TITLE
Streaming video crashes nvlddmkm driver

### ISSUE THREAD

**Issue by Genda1ph** [brave/brave-browser#13054]
## Description 

Streaming video randomly crashes display driver, producing multiple Display event 4101 "Display driver nvlddmkm stopped responding and has successfully recovered.", sometimes everything recovers after 2-3 flickers, other times it completely locks up the system. I suspect hardware acceleration causes the issue.

## Steps to Reproduce

Streaming video on Twitch or YouTube causes screen to flicker black 2-3 times. It can happen a couple times a day or work flawlessly for a few days, usually takes a couple hours.

## Brave version (brave://version info)

Brave: 1.17.75 Chromium: 87.0.4280.88 (Official Build) (64-bit)

Revision: 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}

OS: Windows 10 OS Version 2004 (Build 19041.630)

## Version/Channel Information:

Reproduced on current and previous stable versions. Haven't tested beta/nightly.

## Other Additional Information:

Reproduced with ANGLE graphics backend set to `Default` and `D3D11on12`. Testing OpenGL right now.

Disabling hardware acceleration *seems* to resolve the issue.

## Miscellaneous Information:

I am running up-to-date Windows 10 (2004), with RTX 3080 (driver 457.51).

Reproduced on current and previous versions of Nvidia drivers, including one that Windows 10 installed automatically after I swapped GPUs.

**Comment by Genda1ph** [comment]
OpenGL *seems* stable. but I will keep using it for a while, going to use a week without crashes as a benchmark of stability.

**Comment by Genda1ph** [comment]
...and it just crashed again with GPU acceleration disabled in options, while I was watching this video: https://youtu.be/PzmV84UOR2E?t=326 give or take a few seconds, which should not have been an issue.

On to testing a different browser!

**Comment by rebron** [comment]
@Genda1ph Can you send your crashes via brave://crashes and post your crash id in here?
cc: @iefremov

**Comment by Genda1ph** [comment]
Will do next time it happens (had reporting disabled), but I just got the same driver crash on Firefox viewing Twitch, so I should probably report this to either Nvidia or Microsoft. And I couldn't find any way to report anything to Nvidia.

I strongly suspect this is a software issue, as I only get it when streaming video via browser and not when playing games or stressing GPU.

If this is of any help, every driver crash produces 2 LiveKernelEvent log entries, one code 141 and one code 117 with a few seconds in between, exactly in this order.

**Comment by Genda1ph** [comment]
Update: driver crashed 4 times within 3 hours, but there's nothing to report in brave://crashes.

Browser itself keeps running, video quality drops though, and I have to reload the page to fix it, on Chrome some UI elements stop working as well: ![image](https://user-images.githubusercontent.com/3673402/101428892-54cb5500-390a-11eb-927b-55572ec7a5b1.png).

**Comment by Genda1ph** [comment]
And crashed again after I quit every other app that might have used GPU, save for DWM, with just Brave being up.

Removed Game Ready Driver with DDU and installed Studio, will see if this helps.

**Comment by Genda1ph** [comment]
...nope. Pretty sure this happens only with YouTube and Twitch. Finally found a way to file a ticket with Nvidia, will see where that gets me.

I suggest we put this on hold for now.

**Comment by Genda1ph** [comment]
Sorry for late reply, the issue was resolved by driver update to 460.79 (Game Ready).

**Comment by bsclifton** [comment]
Thanks for being persistent and keeping us updated @Genda1ph - glad you are sorted by updating drivers 😄
