### ISSUE TITLE
Hide iOS QR Code function in Rewards Settings

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#13053]
## Description 
The QR Code shown in Rewards settings will be used on iOS. While we finalize the solution for this (currently testing), we're going to hide the QR Code until it's 100% ready and all scenarios are tested.

For more information see:
https://github.com/brave/brave-ios/issues/3115

**Comment by btlechowski** [comment]
`QA/Blocked` till we get a new build (> 1.18.69)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified QR code is not shown in Rewards Settings

![image](https://user-images.githubusercontent.com/34715963/101637593-40cc4400-3a2d-11eb-9cec-35b2a2aa8f0d.png)

**Comment by dodieboy** [comment]
Brave ios have released the rewards qr code feature on the official ios release already. Will this commit be revert?

**Comment by bsclifton** [comment]
@dodieboy the complication we had run into has been resolved in our staging environment. We're working towards a new desktop release and should have a fix in Nightly tomorrow (Friday). We'll then propagate to Beta and issue a hotfix for the stable version 😄 

Thanks for your patience!

**Comment by bsclifton** [comment]
@dodieboy pull request created to re-show the QR code here 😄👍 
https://github.com/brave/brave-core/pull/7413
