### ISSUE TITLE
[Desktop] Brave Today should not fetch data until interacted with

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#13059]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from the description
Verified the content is fetched after scrolling down
![image](https://user-images.githubusercontent.com/34715963/101657303-01f5b880-3a44-11eb-88d5-81ed6c8a1159.png)
Verified the feed still updates to exclude or include the new publishers
