### ISSUE TITLE
Rewards Widget and Rewards Page Disagree on Rewards State

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#13052]
## Description 
We recently had a user report a _Brave Rewards Server is not responding_ message on the brave://rewards page. At the direction of Brave Support (me, specifically) the user disabled Rewards from within brave://rewards and re-enabled it after a few seconds. This did not resolve the error message.

After some time, the user opened a new tab page to find the Rewards widget inviting them to enable Brave Rewards (meanwhile, the brave://rewards page claimed the feature was already enabled, noting connection issues to the Rewards Server). When the user opted-in to Rewards from the New Tab Page, the message regarding connection issues was reportedly cleared.

From this feedback, it seems as though Brave is able to find itself in a state where the NTP Rewards widget and the Rewards page itself are able to disagree over which view should be displayed (enabled vs disabled).

## Steps to Reproduce
TBD

## Brave version (brave://version info)
1.17.73 (Windows 10)

## Miscellaneous Information:
It's not clear what put the browser into this state to begin with.

**Comment by Miyayes** [comment]
Can reopen if we observe this more recently.
