### ISSUE TITLE
[Android] Rewards onboarding fixes: String changes and Quick tour promo UI for existing users

### ISSUE THREAD

**Issue by codybanxs** [brave/brave-browser#13055]
## Description
We need to update the onboarding copy and add the promo banner for existing users 

## Expected result:
Any user who views the onboarding will see the string changes.
- Keep the name "Brave Private Ads" consistent throughout
- Reword the description for "What you can do with tokens"
- Update the title of "Wooohooo!" to "Woohoo, you're all set!" 

Users who have already opted-in to Rewards will be presented with the promo on next app open.
- Allows user who have previously opted-in to Rewards prior to onboarding to explore and discover.

## Assets
https://www.figma.com/file/0dbMYs8Wp8W3RgrG1yTdki/RE-1.0?node-id=541%3A19529
<img width="1095" alt="Screen Shot 2021-01-11 at 5 24 50 PM" src="https://user-images.githubusercontent.com/61210652/104257787-0f330800-5433-11eb-8e36-90ba6be21180.png">

https://www.figma.com/file/0dbMYs8Wp8W3RgrG1yTdki/RE-1.0?node-id=541%3A19529
<img width="713" alt="Screen Shot 2020-12-04 at 5 51 09 PM" src="https://user-images.githubusercontent.com/61210652/101230301-5cb09e00-3659-11eb-93ed-c85a105c59d8.png">

**Comment by codybanxs** [comment]
We will also be modifying the flow for users who take the tour without opting in. They will go through the onboarding but the mini-modal will not be displayed until 2nd+ app visit. 
<img width="1029" alt="Screen Shot 2021-01-11 at 10 13 41 AM" src="https://user-images.githubusercontent.com/61210652/104223494-8c8d5700-53f8-11eb-8cd1-6866ee887719.png">
<img width="869" alt="Screen Shot 2021-01-11 at 10 15 56 AM" src="https://user-images.githubusercontent.com/61210652/104223485-8a2afd00-53f8-11eb-8f5a-4d8a554655ab.png">

**Comment by deeppandya** [comment]
@codybanxs we should show the bootom banner UI for existing user only on the newTabPage right ?

**Comment by codybanxs** [comment]
@deeppandya yes that is correct!

**Comment by deeppandya** [comment]
> @deeppandya yes that is correct!

@Cody I am asking because for upgrade case, user might have url opened when he/she opens the app after the upgrade. So in that case we should avoid showing the UI right ? Or we should show it when use opens the first newtabpage after an upgrade and never after.

**Comment by codybanxs** [comment]
No no totally understand @deeppandya about the concern here. If a user has a url open and they upgrade, show the bottom banner UI on the first newtabpage after upgrade not on the url site.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.85 x64 Beta build
- Verified onboarding flow is as per specs

  <details>
  <Summary><b>Entry Points</b></Summary>

  <details>
  <summary><b>Rewards Panel</b></summary>
  
  https://user-images.githubusercontent.com/17010094/105706801-ed915080-5f09-11eb-85a5-a2b71dfe6ae8.mp4

  </details>
  <details>
  <summary><b>NTP SI</b></summary>

  https://user-images.githubusercontent.com/17010094/105706881-08fc5b80-5f0a-11eb-9989-558cac44c9fe.mp4

  </details>
  <details>
  <summary><b>Rewards Settings</b></summary>

  https://user-images.githubusercontent.com/17010094/105706995-2e896500-5f0a-11eb-8111-55325d16834d.mp4

  </details>
  </details>

  <details>
  <summary><b>Onboarding Flows</b></summary>

  <details>
  <summary><b>Quick Tour Onboarding</b></summary>

  https://user-images.githubusercontent.com/17010094/105709376-8d041280-5f0d-11eb-9d39-700569e14f54.mp4

  </details>
  <details>
  <summary><b>Opt-In Onboarding</b></summary>
  
  https://user-images.githubusercontent.com/17010094/105708190-faaf3f00-5f0b-11eb-8ade-7c81a2818306.mp4

  </details>
  <details>
  <summary><b>SI Onboarding</b></summary>

  https://user-images.githubusercontent.com/17010094/105709699-fbe16b80-5f0d-11eb-8b55-da4ccac7e0a7.mp4

  </details>
  <details>
  <summary><b>Upgrade Refresher</b></summary>
  
  https://user-images.githubusercontent.com/17010094/105708968-07806280-5f0d-11eb-84c6-d2510fdc6642.mp4

  </details>

  </details>
