### ISSUE TITLE
Aw, Snap! when trying to call an api from a component

### ISSUE THREAD

**Issue by Ahmed-Imam** [brave/brave-browser#13066]
## Description 
Getting Aw, Snap! error on windows when:
1. Trying to call an api using fetch/axios from the components ex: **brave-welcome.tsx**
2. Adding an image with url src `<img src='https://happy-season.com/dashboard/uploads_/cards_/2.jpg'/>` in the same file **brave-welcome.tsx**

<img width="1916" alt="Screen Shot 2020-12-07 at 2 55 31 PM" src="https://user-images.githubusercontent.com/20854551/101319278-b2c15380-389c-11eb-8a56-436a6b2fd70a.png">

**Comment by baselka** [comment]
I am having the same issue when ever I try calling an external api 
```
const response = fetch("https://jsonplaceholder.typicode.com/todos/1")
console.log(response)
```
@rebron can u confirm if this is a known issue ? and can you please suggest any workaround until your team pay attention to this. thanks @rebron

**Comment by bsclifton** [comment]
This is expected for WebUI pages. Basically, they're supposed to be communicating with registered handlers and are blocked from outbound calls

There's a great document about WebUI that you can find here:
https://chromium.googlesource.com/chromium/src/+/lkgr/docs/webui_explainer.md
