### ISSUE TITLE
reCAPTCHA Problem Again

### ISSUE THREAD

**Issue by 1John419** [brave/brave-browser#13063]
Please refer to reCAPTCHA Problem #12504 (https://github.com/brave/brave-browser/issues/12504).

While Version 1.16.72 appeared to fix this issue, since I updated to Version 1.17.75, the issue has returned. About the only way I can get past reCAPTCHA now is again reverting to the audio mode.

Appears that these repeated reCAPTCHA failures got me blacklisted on one site.

**Comment by rebron** [comment]
@1John419 Can you provide some more detail? Where are you seeing the reCAPTCHA issue.

**Comment by 1John419** [comment]
I've seen it on several sites. With 1.16.72, sites which I frequent only required clicking the "I'm not a robot" checkbox, no other challenge was presented. With 1.17.75, many sites fail at least three times (even though correct responses are given each time). Other sites continually failed until I switch to audio mode. That's the same behavior I was seeing prior to 1.16.72.

The site where I got blacklisted was while creating a new account on protectcovers.com.

I'll keep notes on other instances going forward.

**Comment by 1John419** [comment]
https://patrickhlauke.github.io/recaptcha/

Here's a test site. In Chrome, I can consistently pass the test in one or two attempts. In Brave, it consistently fails.

**Comment by Dryader** [comment]
@1John419 Just went to the website you linked and managed to do the recaptcha first try with both Fingerprinting and Ad/Tracker blocking both on strict and/or standard. Do you have any extensions installed in Brave such as Ublock Origin with maybe some custom filter lists? I have completed it with Privacy Badger installed as well so that extension shouldn't be an issue. I assume the reason for why it is failing is because of cookies or blocked network requests although I could be wrong.

**Comment by 1John419** [comment]
When I first observed this, the only extension installed was TabsPlus. Since then, I also installed Buster: Captcha Solver for Humans. I have observed over the last few days that the failure rate is decreasing. I'm not sure what's going on here. The reCAPTCHA behaviour itself is somewhat erratic also (the type of challenges presented varies). Perhaps it's me (the challenges with blurred images are often difficult to discern).

**Comment by Dryader** [comment]
@1John419 Could you try disabling/uninstalling Buster: Captcha Solver for Humans temporarily, and see if the issue persists out of curiosity. As well in terms of solving the captcha you could try doing the ones that say "Click verify once there are none left." As those do not require you to guess whether or not a few pixels of a traffic light counts or not.

**Comment by Dryader** [comment]
@1John419 As well TabsPlus is quite old, the last update was in 2013, could you try disabling/uninstalling that as well and try it out?

**Comment by 1John419** [comment]
Disabling both extension does not appear to have any effect. Beginning to conclude that it must be my error. The "Click verify once there are none left" variant seems new to me, and also the one which fails most often (perhaps I'm clicking verify before it's actually done presenting other images). The "If there are none, click skip" variant also seems new to me. Previously, I just remember encountering simple challenges that did not have these caveats in the header. Let's deem this 'problem exists between chair and keyboard'.
