### ISSUE TITLE
Brave ads appear underneath MacOS dock/menu bar and Windows taskbar

### ISSUE THREAD

**Issue by stshank** [brave/brave-browser#13065]
## Description 

Ads appear underneath the dock on MacOS Catalina and Big Sur when the dock is positioned on the right edge of the screen. 
Brave ads appear to low if the menubar is hidden.

Ads appear underneath the taskbar on Windows when the taskbar is positioned on the right edge of the screen.
## Steps to Reproduce

   1. Move dock to right edge of screen
   2. Wait for ad to appear

## Actual result:

![image](https://user-images.githubusercontent.com/16833251/101301759-109b6000-37f7-11eb-8ada-1169bc3e2e09.png)
Ad appears underneath the dock icons.

## Expected result:
Ad should appear on top of dock (or maybe flush with right edge of browser window?)

## Reproduces how often: 

Always

## Brave version (brave://version info)
Brave | 1.19.48 Chromium: 87.0.4280.88 (Official Build) dev (x86_64)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | macOS Version 11.0.1 (Build 20B29)
JavaScript | V8 8.7.220.29
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Command Line | /Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=AutoupgradeMixedContent,LegacyTLSEnforced,WebUIDarkMode,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges --disable-features=PrivacySettingsRedesign,AutofillServerCommunication,AutofillEnableAccountWalletStorage,TextFragmentAnchor,SmsReceiver,NotificationTriggers,PasswordCheck,NetworkTimeServiceQuerying,TabHoverCards,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection,AllowPopupsDuringPageUnload,VideoPlaybackQuality,IdleDetection --flag-switches-begin --flag-switches-end
-- | --

**Comment by btlechowski** [comment]
Based on the test plan from https://github.com/brave/brave-core/pull/7363, added `QA/Test-All-Platforms`

**Comment by stephendonner** [comment]
Hi @stshank!  If you wouldn't mind, could you let us know 1) screen resolution settings (default/scaled, etc.) 2) # of items in your dock, when you saw this issue?  And, anything else which might be pertinent in reproducing this issue?  I've tried on Big Sur 11.2.3 with various builds, but so far haven't triggered your specific scenario, and I'd like to be able to do so before confidently verifying the fix; thanks!

**Comment by tmancey** [comment]
@stephendonner If you could send a calendar event, or let me know when online and I can demonstrate the issue. Thanks, Terry

**Comment by stshank** [comment]
I haven't seen this issue since I initially reported it. Brave rolled back the approach for awhile, apparently. I can't recall if the new style of ads is back. (I use Brave stable more often these days.)
________________________________

**Comment by stephendonner** [comment]
@tmancey @stshank thanks, both of you; easily reproduced this bug using `nightly` version `1.23.33` on macOS `11.2.3`

<img width="1680" alt="Screen Shot 2021-03-26 at 9 06 48 AM" src="https://user-images.githubusercontent.com/387249/112660653-e6f05e00-8e12-11eb-82d1-b173051eddb9.png">

**Comment by stephendonner** [comment]
Verified `FIXED` on macOS Big Sur (`11.2.3`) using `beta` build 

Brave | 1.23.53 Chromium: 89.0.4389.105 (Official Build) beta (x86_64)
-- | --
Revision | 14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. clean profile
2. launched Brave using `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --rewards=staging=true`
3. set `Position on Screen` for the dock to {`Bottom` (default), `Left`, and `Right`}
4. opened a few new-tab pages
5. clicked on `Start using Rewards`
6. waited a bit
7. confirmed I received a Brave ad notification:
* at the appropriate location and position for each corresponding dock placement
* ads were not clipped behind any of the docks

| Bottom | Left | Right |
|---------|-----|------|
<img width="1680" alt="Screen Shot 2021-03-26 at 9 52 03 AM" src="https://user-images.githubusercontent.com/387249/112671585-9a5f4f80-8e1f-11eb-8572-85e6bb01db38.png"> | <img width="1679" alt="Screen Shot 2021-03-26 at 9 47 15 AM" src="https://user-images.githubusercontent.com/387249/112671532-89164300-8e1f-11eb-9689-3dbc06a50a9c.png"> | <img width="1680" alt="Screen Shot 2021-03-26 at 10 43 03 AM" src="https://user-images.githubusercontent.com/387249/112671962-21142c80-8e20-11eb-93c1-3d2a4507dab5.png">
