### ISSUE TITLE
Implement cosmetic filters

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#13070]
## Description 

We need a common solution for Android and desktop for that feature. The goal is to make it happen without using extensions.

## Steps to Reproduce

   1. Go to chicagotribune.com
   2. Observe an empty space on top of the webpage
![tempFileForShare_20201207-104118](https://user-images.githubusercontent.com/12011303/101371534-e1c5ce00-3878-11eb-885d-3e23b2085b36.jpg)
   3. 

## Expected result:
No empty space
![Screenshot from 2020-12-07 10-43-18](https://user-images.githubusercontent.com/12011303/101371693-0de14f00-3879-11eb-81b4-3eb6eda1e867.png)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@SergeyZhukovsky is there a test plan for this other than the STR?

**Comment by SergeyZhukovsky** [comment]
@pes10k @antonok-edm do we have any test plan for that from the original implementation?

**Comment by pes10k** [comment]
@antonok-edm will know more automated tests than me, but I have been snowballing manual / QA tests here:  https://dev-pages.brave.software/cosmetic-filtering/text-ads.html

Happy to add more if it'd be helpful

**Comment by antonok-edm** [comment]
@SergeyZhukovsky The original implementation was tracked at https://github.com/brave/brave-browser/issues/5381. There was a test plan there, although as far as I can see, the website in question has since been updated so that it no longer has the ad spot.

@LaurenWags the STR here is a pretty good test case though :smile:

**Comment by LaurenWags** [comment]
perfect, thanks all! just wanted to make sure QA tested this appropriately 😄

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.21.54 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 10.15.7 (Build 19H512)
```

Verified STR from description. Confirmed no empty space at the top:
<img width="1034" alt="chicagotribune" src="https://user-images.githubusercontent.com/28145373/107987480-1aca9f00-6f9c-11eb-8204-40f85d04f0f2.png">

Confirmed "Trackers & ads blocked" setting values on https://dev-pages.brave.software/cosmetic-filtering/text-ads.html:

Aggressive | Standard (default) | Allow all
----- | ----- | -----
<img width="1034" alt="Aggressive" src="https://user-images.githubusercontent.com/28145373/107987579-45b4f300-6f9c-11eb-85d7-6b12231c1db9.png"> | <img width="1037" alt="Standard-default" src="https://user-images.githubusercontent.com/28145373/107987587-46e62000-6f9c-11eb-9f15-3a108235b925.png"> | <img width="1035" alt="Allow All" src="https://user-images.githubusercontent.com/28145373/107987595-48174d00-6f9c-11eb-9606-e13459a75bc9.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.70 x64 build
- Verified steps from issue description
![image](https://user-images.githubusercontent.com/17010094/109467229-c8d94d00-7a62-11eb-9e56-330b869fb861.png)

- Verified steps on https://github.com/brave/brave-browser/issues/13070#issuecomment-779398924

Shields ON | Shields Off
-- | --
![image](https://user-images.githubusercontent.com/17010094/109467255-d42c7880-7a62-11eb-86d8-78ab0e65f9ad.png) | ![image](https://user-images.githubusercontent.com/17010094/109467267-d8f12c80-7a62-11eb-989b-9becd5533415.png)

---------
Verification passed on OnePlus 6T with Android 10 running 1.21.70 x64 build
- Verified steps from issue description
![image](https://user-images.githubusercontent.com/17010094/109467477-24a3d600-7a63-11eb-9ffa-ffb51a6cde92.png)

- Verified steps on https://github.com/brave/brave-browser/issues/13070#issuecomment-779398924

Shields ON | Shields Off
-- | --
![image](https://user-images.githubusercontent.com/17010094/109467491-279ec680-7a63-11eb-98de-509e33904f5c.png) | ![image](https://user-images.githubusercontent.com/17010094/109467501-2b324d80-7a63-11eb-9560-3498bb5a8d8f.png)
