### ISSUE TITLE
Google updater for widevine returns nothing for macos arm64

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#13074]
When attempting to fetch widevine, the google update server returns nothing for arm64 since there is currently no arm64 version available and Chrome bundles widevine. Since macos arm64 currently uses the x64 widevine lib (using Rosetta) we should temporarily change the arch in the request until Google fixes the updater issue

**Comment by bridiver** [comment]
QA - widevine should download for fresh arm64 install with no previous widevine download from intel-only binary in Application Support/BraveBrowser/...

**Comment by bridiver** [comment]
os.arch is still arm64

**Comment by kjozwiak** [comment]
Labeling this as **PASSED** as @rebron went through the above cases via the following:

* https://github.com/brave/brave-browser/issues/13313#issuecomment-751861035 - checked Universal `.dmg` & `.pkg` executables
* https://github.com/brave/brave-browser/issues/13313#issuecomment-751866579 - checked x64 `.dmg` & `.pkg` executables
