### ISSUE TITLE
Brave Rewards Invalid wallet for Android users

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#13088]
## Description 

Android users (may affect desktop too) on the community forums have reported their BAT balance has vanished

## Steps to Reproduce

   1.  No steps to reproduce

## Actual result:

Wallet is invalid

## Expected result:
Wallet should be valid

## Reproduces how often: 

No steps to reproduce

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@tmancey related to https://github.com/brave/brave-browser/issues/13026?

Do you know what channels, etc?
cc: @emerick

**Comment by tmancey** [comment]
Unlikely as this issue was a recent regression with rewards everywhere, thanks

**Comment by tmancey** [comment]
All I know right now is 1.16.x

**Comment by Miyayes** [comment]
Closing this for now as stale. Re-open if we have something more specific. I think a lot of this is due to wallet encryption, which is now gone.
