### ISSUE TITLE
Crypto Wallet: allow importing private key from metamask/MEW/etc

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#13083]
as described in https://github.com/brave/brave-browser/issues/9837#issuecomment-644477534, it should be feasible for Brave's implemention to support importing a private key (using a bip39 seed phrase) from another wallet. we will need to add a new code path for these users since they aren't deriving the key from a master seed (steps 5-7 in https://docs.google.com/document/d/1yYzn8ycq4GzKNrd9h-DHM9Yo7R8BUez-KUGkcd2kEFE/edit#heading=h.zh54ziq5w32).

**Comment by tauren** [comment]
As I mentioned in #9837, without have bidirectional support, you risk alienating smart contract developers. `HDWalletProvider` takes a mnemonic as input but does NOT work with the 24 words generated by Brave. So I'm forced to use Metamask/etc to generate my wallet.

**Comment by diracdeltas** [comment]
that's because the 24 word phrase generated by brave is a master key from which other independent keys are derived, not a wallet private key in itself. this is causing enough confusion that we should revert it to the metamask way. closing in favor of https://github.com/brave/brave-browser/issues/13245.

**Comment by gokujj** [comment]
what is the HD Derivation Path used atm ? and few month before?

I have issue : i created wallet few month before saved seed&password and my main adresse and now i trying restore my acount in brave wallet and its displaying different adress also same if i use metamask. funds still on my adress.
thanks

**Comment by aruialmeida** [comment]
Thanks for the answer bbondy.

I create the wallet in the "create" button in the image, and it gave me 24 words phrase.
And now i restore it in another computer in the "restore" button (in the image) and it accept the 24 word phrase but open a different address account!!!

appreciate some help.
![yt1 create restore](https://user-images.githubusercontent.com/29195394/116258733-1aedd480-a76d-11eb-8d9a-6737268b1812.JPG)

**Comment by aruialmeida** [comment]
Hi,
I create the wallet in the "create" button in the image, and it gave me 24 words phrase.
And now i restore it in another computer in the "restore" button (in the image) and it accept the 24 word phrase but open a different address account!!!

appreciate some help.
![Uploading yt1 create restore.JPG…]()

**Comment by diracdeltas** [comment]
@aruialmeida commented here: https://github.com/brave/brave-browser/issues/13245#issuecomment-827740886
