### ISSUE TITLE
Dependency issue with Rewards extensions API

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#13091]
@bridiver mentioned that there's a dependency issue with the Rewards extensions API:

```
11:59:23  In file included from gen/brave/common/extensions/api/generated_api_registration.cc:12:
11:59:23  In file included from ../../brave/browser/extensions/api/brave_rewards_api.h:14:
11:59:23  ../../brave/vendor/bat-native-ledger/include/bat/ledger/mojom_structs.h:13:10: fatal error: 'brave/vendor/bat-native-ledger/include/bat/ledger/public/interfaces/ledger.mojom.h' file not found
11:59:23  #include "brave/vendor/bat-native-ledger/include/bat/ledger/public/interfaces/ledger.mojom.h"
11:59:23           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:59:23  1 error generated.
```

This should be `#include "bat/ledger/mojom_structs.h` instead.

In addition, there's a missing dep in `//brave/common/extensions/api` but more importantly `//brave/common` should not have any dependencies on `//brave/browser`. We can potentially move the entire thing to `//brave/browser/extensions/api` if there's no real need for this to be in `//brave/common`.

**Comment by wknapik** [comment]
Also [here](https://ci.brave.com/job/brave-browser-build-macos-arm64/926/execution/node/70/log/#-62127691500f97e22-c981-4d1e-8d5b-6c0b7408d959).

**Comment by Miyayes** [comment]
This may no longer be relevant once we fully deprecate and remove the Rewards extension in favor of WebUI?
