### ISSUE TITLE
Brave tipping icons appear on Github Personal Access Token page (Brave Beta)

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#13090]
## Description 

When on Github's Personal Access Token [page](https://github.com/settings/tokens) (after logging into Github), the tip icon appears next to previously created tokens.

## Steps to Reproduce

   1. Login to Github
   2. Browse to https://github.com/settings/tokens 
   3. see the icons

## Actual result:

![image](https://user-images.githubusercontent.com/6763301/101506975-45accd00-3933-11eb-88b0-b22fd3450f01.png)

## Expected result:
Brave/BAT tip icons should only appear next to Github user names, tipping a personal access token seems a little strange to me.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Version 1.18.63 Chromium: 87.0.4280.67 (Official Build) beta (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not installed

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No 
- Is the issue reproducible on the latest version of Chrome? No

**Comment by emerick** [comment]
Unable to repro, please reopen if we continue to see this.

**Comment by mkarolin** [comment]
Unable to repro as well.
