### ISSUE TITLE
'Desktop site' Mode in Android, Zoomed-in when keyboard pops up and later it can't be scrolled or zoomed-out

### ISSUE THREAD

**Issue by developeranaz** [brave/brave-browser#13106]
'Desktop site' Mode in Android, Zoomed-in when keyboard pops up and later it can't be scrolled or zoomed-out
ie., i don't want it to Zooming-in when keyboard poping time

I had used many chromium browsers in Android But this issue is common in all of them. 
i found the issue in this website ssh.cloud.google.com  - in its  terminal section 
. I know this website originally for PC

**Comment by MrWaste** [comment]
Could you record on what is going? I want to make sure I understand this correct.

**Comment by developeranaz** [comment]
[https://developeranaz.pingme.workers.dev/0:/Bugs/test46.mp4?a=view](url)

**Comment by developeranaz** [comment]
> Could you record on what is going? I want to make sure I understand this correct.

![DIKJSD](https://user-images.githubusercontent.com/71500526/101624895-a70e9200-3a40-11eb-8bfe-82033b2ee5af.gif)

**Comment by developeranaz** [comment]
If it is a stupid question leave It, 
I thought no one will answer this question.

**Comment by MrWaste** [comment]
Thank you very much. Does this only happen with shell.google.com?

**Comment by MrWaste** [comment]
cc: @Dryader @bsclifton

**Comment by developeranaz** [comment]
> Thank you very much. Does this only happen with shell.google.com?

Yes
