### ISSUE TITLE
Unable to view video on imdb.com

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#13101]
## Description 
Open `https://www.imdb.com/video/vi886815769?playlistId=tt1568346&ref_=vp_rv_ap_0` Click play, nothing occurs and goes into an infinite loop.

## Steps to Reproduce

   1. Open `https://www.imdb.com/video/vi886815769?playlistId=tt1568346&ref_=vp_rv_ap_0`
   2. Click Play
   3. Nothing occurs.

## Actual result:
Should play video.

## Expected result:
Nothing plays.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
`Version 1.17.75 Chromium: 87.0.4280.88 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
I believe its a CNAME issue, attempted to resolve it by https://github.com/brave/adblock-lists/pull/526 & https://github.com/brave/adblock-lists/pull/528 with `@@||cloudfront.net^$domain=imdb.com|media-imdb.com` 

From what I understand the issue is related to `imdb-video.media-imdb.com`

```
;; ANSWER SECTION:
imdb-video.media-imdb.com.      669     IN      CNAME   d22ohr3ltkx6p.cloudfront.net.
d22ohr3ltkx6p.cloudfront.net.   60      IN      A       13.224.93.10
d22ohr3ltkx6p.cloudfront.net.   60      IN      A       13.224.93.84
d22ohr3ltkx6p.cloudfront.net.   60      IN      A       13.224.93.3
d22ohr3ltkx6p.cloudfront.net.   60      IN      A       13.224.93.116
```

![imdb-err](https://user-images.githubusercontent.com/1659004/101562456-55f4a300-3a2c-11eb-8bc3-0a3f5ed2e16b.png)

**Comment by ryanbr** [comment]
Just test `Version 1.15.45` Looks fine there

**Comment by ryanbr** [comment]
Okay, Tested some builds:

```
Nightly v.16.26           BAD
Nightly v1.16.23         Good
```

**Comment by antonok-edm** [comment]
Confirmed it's an `adblock-rust` issue caused by https://github.com/brave/adblock-rust/commit/77ecd45210ee42320712eeb03eede5a2420d9d8d. Exceptions are no longer checked when a redirect rule is matched.

Fix pushed in https://github.com/brave/adblock-rust/commit/3f4827f1e13a9324e16950180a1ff447d08fa107.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/103219628-41793b80-4944-11eb-809f-dd0fd20aa153.png)
![image](https://user-images.githubusercontent.com/38657976/103219709-7c7b6f00-4944-11eb-9e99-c56b0b10b8f2.png)

**Comment by kjozwiak** [comment]
Labeling as `OS/Android` as I can reproduce the issue using `1.18.75 CR: 87.0.4280.101` on a `Samsung S10+` running `Android 10`.

**Comment by kjozwiak** [comment]
Verification **PASSED** on  `Samsung S10+` running `Android 10` using 

* Reproduced the original issue as per https://github.com/brave/brave-browser/issues/13101#issuecomment-751933995. Once you click on the play button on the video mentioned via https://github.com/brave/brave-browser/issues/13101#issue-759917779, it starts skipping through the entire queue without playing any of the videos
* Ensured that the video mentioned via https://github.com/brave/brave-browser/issues/13101#issue-759917779 played without any issues.
