### ISSUE TITLE
Adding Brave News prominently in intro card title

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#13100]
## Description
Make a stronger connection between the feature name and introductory card on Brave Today.

## Design

<img width="913" alt="Screen Shot 2020-12-09 at 9 55 17 AM" src="https://user-images.githubusercontent.com/2388823/101667816-a6f0a100-3a04-11eb-9d50-a9e5c628fc0c.png">

## Assets
Figma: https://www.figma.com/file/wpjvatVQQvOtC96WaPCw86/?node-id=0%3A1

CC @karenkliu and @jamesmudgett for comment/review

**Comment by mattmcalister** [comment]
also change "every hour" to "throughout the day"

**Comment by karenkliu** [comment]
@mattmcalister Does a separate issue need to be filed for iOS? We should make the same text change on the intro card there too.

**Comment by bsclifton** [comment]
@bradleyrichter @karenkliu is this issue still needed? With opt-in, it looks like this (which does mention Brave News specifically)
![image](https://user-images.githubusercontent.com/4733304/121842863-0a9aa600-cc96-11eb-9bdd-6ee8dacacae7.png)

**Comment by karenkliu** [comment]
We can close this one. The opt-in card contains the updated text described in this issue.
