### ISSUE TITLE
brave stats in NTP cuts off the window

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13107]
## Description 

brave stats in NTP cuts off the window

## Steps to Reproduce

   1. Clean profile 1.18.x
   2. Open NTP
   3. Observe brave stats cuts off the window even though the vertical scroll bar at the top

**Note:** This issue is arising only for the 1st NTP, drag the vertical scroll bar down and up fixes the issue.

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/101601628-e5955400-3a22-11eb-9397-66b65c4e1dcd.png)

![image](https://user-images.githubusercontent.com/38657976/101602808-acf67a00-3a24-11eb-95c9-dd4b0f2bb85f.png)

## Expected result:
brave stats in NTP should not cut off the window

## Reproduces how often: 

Intermittent

## Brave version (brave://version info)

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @petemill @rebron @karenkliu 

@petemill I suspect this issue is arising due to the addition of Brave Today in NTP in 1.18.x. I might be wrong also

**Comment by karenkliu** [comment]
We also have this issue open to fix Brave Today / NTP responsiveness https://github.com/brave/brave-browser/issues/12700

**Comment by rebron** [comment]
@GeetaSarvadnya Can you check this one again? We maybe able to close this one out, I'm not able to reproduce and I'm not seeing additional reports.

cc: @Brave-Matt

**Comment by GeetaSarvadnya** [comment]
@rebron @karenkliu Verified in 1.23.x and 1.24.x. The issue isn't reproducible now, hence closing the issue.
