### ISSUE TITLE
Control Widevine Host Verification from brave-browser

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#1310]
from https://github.com/brave/brave-core/pull/510#issuecomment-424906315

> we should really control enable_cdm_host_verification from brave-browser by override the value or passing the new arg to control it.
Because developers often need to build Release build and we can't expect them to have signing script

**Comment by darkdh** [comment]
see `lib/config.js` in brave-browser to override build arg or pass a new one

if you need pass a new one, you need to declare it in `declare_args` before using it

**Comment by simonhong** [comment]
Will close this because widevine signing can be done only on buildbot.
Also, any kinds of release build on local machine can't sign because signing needs cert & key.
So, verification should be only enabled on buildbot.
