### ISSUE TITLE
Spotify Web Player gives 'Playback disabled' error

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#13108]
Spotify Web Player gives 'Playback disabled' error. I have 'Protected content' enabled in the browser settings. 

Device: Motorola One Power, Android 10.
Brave browser version: 1.17.75.
![Screenshot_20201209_141214](https://user-images.githubusercontent.com/74760664/101606040-eaf59d00-3a28-11eb-8ed5-71db33b85ee4.jpg)
![Screenshot_20201209_141158](https://user-images.githubusercontent.com/74760664/101606052-ee892400-3a28-11eb-99bc-4c3839e5e02b.jpg)

**Comment by Neon329** [comment]
Can someone at least tell me if Brave browser on Android supports DRM playback or is this a bug?

**Comment by Neon329** [comment]
I'm going back to Chrome because there's no answer if it is a bug or if Brave on Android isn't able to play DRM.

**Comment by SergeyZhukovsky** [comment]
@Neon329 could you check that in Chrome?

**Comment by Neon329** [comment]
@SergeyZhukovsky it works in Chrome.

**Comment by ryanbr** [comment]
Changing Brave Desktop UA, to the Brave mobile UA, wasn't able to get the error messge. It seems to be picking up another Brave quirk (or mix of UA/quirk) . Also tested in Firefox Desktop with Brave mobile UA.

Firefox mobile has the same issue, though without the warning. Just no playback either. They block access completely

Switching Useragents via desktop, I was able to change whether spotify would show the non-error error (like Firefox), or the mobile page.

Might be a good idea to reach out to Spotify on the reasons for the block

**Comment by krasi-georgiev** [comment]
Same issue, no playback on spotify from brave desktop

chrome works ok

**Comment by krasi-georgiev** [comment]
Here is a thread on the spotify forums
https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Web-Player-Doesn-t-work-for-Brave-browser/m-p/4653940/highlight/false#M60340

**Comment by immanishbainsla** [comment]
same issue
opens and lists songs on "open.spotify.com" when not signed in but after clicking it asks for sign in and after sign in it shows "web player disabled"

**Comment by harishraja1217** [comment]
I can't believe that no one found the answer. It's very simple. Just enable Widevine in your brave browser by following the instructions given by brave Support website - https://support.brave.com/hc/en-us/articles/360023851591-How-do-I-view-DRM-protected-content-

**Comment by wettestSheep** [comment]
Even after relaunch the desktop site doesn't seem to load ;(

**Comment by saithebuilder** [comment]
any update or fix? the issue is still present

**Comment by dericlima** [comment]
Got this issue today. Following @harishraja1217 suggestion I enabled Widevine and the issue was solved.

**Comment by StyraxBenzoin** [comment]
Nothing to add but to say I have the same issue on Android Brave 1.35.103,

**Comment by ActualDisaster2447** [comment]
This issue also affects me on Android 12 with Brave 1.38.119. Any updates?

**Comment by ryanbr** [comment]
Related to DRM: https://github.com/brave/brave-browser/issues/20241

**Comment by HarshPatel5940** [comment]
Can someone please say how fix this/enable wideline

**Comment by saithebuilder** [comment]
hey, the only "fix" i ever found was to use spotify on firefox android (with ublock origin installed) spotify mobile web allows fewer features than the desktop web version but its usable imo.

**Comment by HarshPatel5940** [comment]
Oh i see

**Comment by ratemisia** [comment]
Same issue on Firefox mobile now.

**Comment by bsclifton** [comment]
Widevine supported on Android now; also no comments in almost 1 year. Closing as stale

**Comment by MogofVal** [comment]
They are probably afraid you would listen for free with an ad blocker extension
