### ISSUE TITLE
Add Fanboy's Enhanced Tracking List into Brave Shield

### ISSUE THREAD

**Issue by Furax-31** [brave/brave-browser#13111]
## Description 

Fanboy's Enhanced Tracking List is missing in Brave Shield (This list is in uBlock Origin)

## Desktop Brave version:
Nightly 1.20.19

## Android Device details:
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Samsung A5 2017 - Android Pie
   - Android version: Nightly 1.20.19

## Version/Channel Information:
All versions

## Miscellaneous Information:
https://secure.fanboy.co.nz/enhancedstats.txt

**Comment by ryanbr** [comment]
No ETA, But I want to clean the list up before including it.

**Comment by ryanbr** [comment]
its in maintenance mode, most changes were uploaded to other lists. Won't be included.
