### ISSUE TITLE
Translations are missing for Brave Today settings in a non-English language 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13116]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/13040
Translations are missing for Brave Today settings in a non-English language 
## Steps to Reproduce

   1. Set OS locale to Kannada
   2. Launch brave with clean profile 1.18.70
   3. Open an NTP and turn ON Brave Today settings in the NTP dashboard settings popup
   
   

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/101664916-64fe4400-3a72-11eb-917d-7b3550766a37.png)

## Expected result:
Brave Today settings should be translated

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave	1.18.69 Chromium: 87.0.4280.88 (ಅಧಿಕೃತವಾಗಿ ನಿರ್ಮಿಸಿ) (64-ಬಿಟ್)
ಪರಿಷ್ಕರಣೆ	89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS	Windows 10 OS Version 1809 (Build 17763.1637)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mkarolin @brave/legacy_qa @petemill @rebron

**Comment by petemill** [comment]
Yes translations are missing for strings like "Show Brave Today" and the word `"Sources"`, but the categories and source names themselves come from the feed so they won't get translated.

**Comment by GeetaSarvadnya** [comment]
Marking the issue as invalid as per the above comments https://github.com/brave/brave-browser/issues/13116#issuecomment-741948741
