### ISSUE TITLE
[Desktop] Update Brave Rewards panel within welcome UI

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#13119]
The welcome UI should be updated with new designs for the Brave Rewards onboarding panel.

<img width="790" alt="Screen Shot 2020-12-09 at 1 11 27 PM" src="https://user-images.githubusercontent.com/5995084/101669547-132cce00-3a20-11eb-9327-a039ceb6678a.png">

When the user clicks the "Start Using Rewards" button, a new tab should open for the rewards settings page with ads and AC enabled.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.76 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/7467

**_Clean profile_**

- Verified that ToS and Privacy policy links provided in `Brave Rewards` slide-in brave://welcome
- Verified that the content and graphics of the slide is matching with the design mentioned in https://github.com/brave/brave-browser/issues/13119#issue-760557590
- Verified that ToS link redirects to https://basicattentiontoken.org/user-terms-of-service/
- Verified that Privacy Policy redirects to https://brave.com/privacy/browser/#rewards
- Click on `Start using Rewards` opens up brave://rewards/ page in a new tab with `Ads` and `Auto-Contribute` switches enabled
- Verified that Rewards onboarding modal is not displayed  once rewards is enabled via brave://welcome slide
![image](https://user-images.githubusercontent.com/38657976/103848278-00adbf00-50c8-11eb-9e7b-1215b1a8316f.png)

**_Upgrade profile_**
- Install 1.17.x dev build and upgrade to 1.19.x and navigate to Brave rewards in brave://welcome screen and ensured that rewards slide content and graphics is updated as the per the design mentioned in the description, click on  `Start using Rewards` opens up brave://rewards/ page in a new tab with `Ads` and `Auto-Contribute` switches enabled
- Install 1.17.x dev build and enable rewards via BR panel or NTP, upgrade to 1.19.x and navigate to Brave rewards in brave://welcome screen, click on `Start using Rewards`  button redirects to brave://rewards tab which is already opened in 1.17.x

**Comment by GeetaSarvadnya** [comment]
@zenparsing In a clean profile 1.19.x, If I enable rewards via NTP or BR panel and Turn OFF the `Ads` and `Auto-Contribute` switches in brave://rewards tab and then enable rewards via brave://welcome screen by clicking on `Start using rewards ` a new tab brave://rewards is opened up with  `Ads` and `Auto-Contribute` switches enabled, shouldn't it point to already opened brave://rewards tab?

**Comment by zenparsing** [comment]
@GeetaSarvadnya After we introduced rewards everywhere in 1.18 and removed the global rewards opt-in, the "Start using Rewards" buttons now just enable ads and AC. I think this is expected behavior, but cc @codybanxs for UX perspective.

**Comment by codybanxs** [comment]
If I am understanding this correctly @GeetaSarvadnya, the 2nd time you click "Start using Rewards" it should open up the rewards settings page with those settings turned on. Now I believe the logic that is baked in here is that it will automatically open the rewards settings page once you opt-in regardless of what other tabs are open prior to that interaction. I am not sure if we have a way to tell if the settings page is open or not and to just use the existing screen @zenparsing.
