### ISSUE TITLE
`Welcome to Brave` isn't not translated in non-English language

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13118]
## Description 

`Welcome to Brave` isn't not translated in non-English language

## Steps to Reproduce

   1. Set OS locale to Kannada
   2. Launch brave with clean profile 1.18.x
   3. `Welcome to Barve` is not translated to Kannada

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/101667730-b22fe500-3a75-11eb-83f3-86f48f0b97ad.png)

## Expected result:

`Welcome to Brave`  should be translated to Kannada
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave	1.18.69 Chromium: 87.0.4280.88 (ಅಧಿಕೃತವಾಗಿ ನಿರ್ಮಿಸಿ) (64-ಬಿಟ್)
ಪರಿಷ್ಕರಣೆ	89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS	Windows 10 OS Version 1809 (Build 17763.1637)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @brave/legacy_qa

**Comment by mkarolin** [comment]
@GeetaSarvadnya, is this a regression?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.20.84 Chromium: 88.0.4324.96 (ಅಧಿಕೃತವಾಗಿ ನಿರ್ಮಿಸಿ) dev (64-ಬಿಟ್)
-- | --
ಪರಿಷ್ಕರಣೆ | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)


```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/105163961-8c006900-5b3a-11eb-99b4-2d269b478082.png)
