### ISSUE TITLE
New tab page: Ad block stat count incrementally increases

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#1311]
## Description 

I've repro'd this issue a few times on Windows, but not 100% of the time. That said, I'm seeing it enough times to open an issue, in case anyone else reports it. 

On Brave Core, win10, I've noticed that in some instances, when I have a few tabs in a window, if I open a new tab, the ads blocked stat counter will continually increase while in view. 

The inactive tabs behind the new tab do not indicate any autoplay occurring, and I'm observing the ad block count increase in the new tab page. 

From a typical user POV, it seems like unexpected behavior, since it doesn't appear that other tabs are active, and autoplay is not running. 

## Steps to Reproduce

   1. Open brave core
   2. Load a few tabs from the same window with different web pages in each tab. 
   3. Open a new tab. In some instances, I'm observing the ad block count increase. 

## Actual result:

In some cases, I see the "ads blocked" brave stat count increase. 

## Expected result:
"ads blocked" count should remain static with all other inactive tabs in the background. 

## Reproduces how often: 

Intermittent. 

## Brave version (chrome://version info)

```

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
JavaScript | V8 7.0.276.9
Flash | (Disabled)

```
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Reproduced on Linux with only Chrome pages in background. Saw stats increment on its own but wasn't a running count just a few increments

**Comment by srirambv** [comment]
@Miyayes if you play any video on ESPN then you can see this consistently increase.  This is similar behaviour of https://github.com/brave/brave-browser/issues/426. The only difference being now it stops at `99+` instead of showing the actual count.

**Comment by Brave-Matt** [comment]
Had a user point out what @Miyayes mentioned above:
https://community.brave.com/t/bug-the-tracker-counter-on-new-tab-keep-running-suddenly/35813/4?u=mattches
Using this site: http://www.espncricinfo.com/

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/brave-browser-stats-skyrocketing-without-additional-browsing/35317

@rebron @bbondy we should probably fix this soon. There are several reports on this already both  internal and on community.

**Comment by bbondy** [comment]
Added this to Shields project, and upped it from P3 to P2 so it gets attention.

**Comment by bbondy** [comment]
I found this rule applied to allow similar domains on easyprivacy:
`@@||imrworldwide.com^*/ggce354.swf$domain=espn.go.com|espndeportes.com|espnfc.co.uk|espnfc.com|espnfc.com.au|espnfc.us|espnfcasia.com`

So I think we should just add another rule like this to our list:
`@@||imrworldwide.com^*/ggce354.swf$domain=espn.com|espncricinfo.com`

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

- Verified visiting http://espn.com and opening articles on the site didn't continuously increase the ad/tracker block count on NTP
- Verified `http://cdn-gl.imrworldwide.com/novms/js/2/ggcmb510.js` being continuously requested and  blocked does not increase the block count
- Verified visiting [this](http://www.espn.com/soccer/uefa-champions-league/775/blog/post/3725073/spurs-sneak-into-ucl-knockout-rounds-after-fighting-back-for-draw-at-barca) page and playing the video didn't continuously increase the ad/tracker block count on NTP
