### ISSUE TITLE
`Reset settings` is not translated under `brave://settings/reset`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#13121]
Follow up to: https://github.com/brave/brave-browser/issues/13040

## Steps to Reproduce

   1. Open `brave://settings/reset`
   1. Check if `Reset settings` is translated

## Actual result:

`Reset settings`  is not translated
![image](https://user-images.githubusercontent.com/34715963/101673515-90276a00-3a57-11eb-97a9-195a107a2240.png)

## Expected result:
`Reset settings`  is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.20.17 Chromium: 87.0.4280.88 (Official Build) nightly (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @mkarolin @rebron

**Comment by btlechowski** [comment]
This is a regression. 

Not reproducible on


Brave | 1.17.75 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/101675074-97e80e00-3a59-11eb-9bf2-7c263ec60823.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

rave | 1.19.76 Chromium: 87.0.4280.101 (ಅಧಿಕೃತವಾಗಿ ನಿರ್ಮಿಸಿ) dev (64-ಬಿಟ್)
-- | --
ಪರಿಷ್ಕರಣೆ | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified few locales and ensured that `Reset Settings` is translated

**_Kannada_**
![image](https://user-images.githubusercontent.com/38657976/103845982-3603de00-50c3-11eb-9c80-3030a6c48883.png)

**_Hindi_**
![image](https://user-images.githubusercontent.com/38657976/103846062-5e8bd800-50c3-11eb-9023-4f11ab22f2e7.png)

**Dutch _(Netherland)**_
![image](https://user-images.githubusercontent.com/38657976/103846245-ae6a9f00-50c3-11eb-8072-63408b0a0f10.png)
