### ISSUE TITLE
[BUG] To Many Tabs Open with opening & Closing the Window

### ISSUE THREAD

**Issue by MrWaste** [brave/brave-browser#13124]
## Description 

I found this weird glitch today.
I turned off all my monitors last night and the window was like this when I woke up. I started using my computer and found it.

Watch Video:
https://youtu.be/1tcjKt-wi2M

## Steps to Reproduce

   1. Open tons of tabs in full screen or at least more tabs that can fit in a large window
   2. Minimize the window so much it doesn't open
   3. The tabs can't fit in the screen 
   4. Bugs out

## Actual result:

https://youtu.be/1tcjKt-wi2M

## Reproduces how often: 

Once for me.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure, more than likely and no one does this ever..
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the DEV channel? YES
- Can you reproduce this issue with the nightly channel? YES

## Miscellaneous Information:

Watch Video:
https://youtu.be/1tcjKt-wi2M

**Comment by MrWaste** [comment]
I fixed it when trying to:
1. Open a new window
2. Stretch the screen really large, not full screen. I knew that wouldn't work..
3. Close the full tab window: ALL
4. Go to history Open the recent closed tabs open it all again
5. Flickered a bit and show up
6. Fixed

I think this will do this again in the future or maybe not.

**Comment by rebron** [comment]
Closing per last comment.
