### ISSUE TITLE
Implement new custom ad notification design

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#13132]
<img width="368" alt="dark-theme-2" src="https://user-images.githubusercontent.com/1188719/101738265-cac3ed80-3abd-11eb-86bb-e7d38d05c6a0.png">

**Comment by tmancey** [comment]
Discuss browser theme (light/dark), animations and overall design across desktop and mobile

**Comment by tmancey** [comment]
Related to https://github.com/brave/brave-browser/issues/12683

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```


<!--StartFragment-->
Brave | 1.26.50 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

<!--EndFragment-->

```
- Verified the test plan from https://github.com/brave/brave-core/pull/8377

Test ad notifications are shown
Test users are rewarded for viewing ads
Test ad notifications can be dragged on desktop
Test ad notifications are shown in the same position after restarting the browser on desktop only, i.e. after dragging an ad notification
Test ad notifications are shown correctly for dark mode
Test ad notifications are shown correctly for light mode

Confirmed custom Ad notifications are shown
![image](https://user-images.githubusercontent.com/38657976/121160886-1b988100-c86a-11eb-8e3e-63dd7554a5f5.png)

Confirmed users are rewarded for viewing ads
```
[11320:14312:0608/143904.884:VERBOSE1:confirmations.cc(248)] Successfully redeemed unblinded token with confirmation id 95b67c23-8f1a-4296-9c3d-0020f459e744, creative instance id 4983dc92-09fd-4e5c-94c3-616a4728c1d9 and view
[11320:14312:0608/143904.886:VERBOSE1:confirmations.cc(271)] Added 1 unblinded payment token with an estimated redemption value of 0.01 BAT, you now have 1 unblinded payment tokens
```

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy Tab version 10 running `Bravemonoarm64 1.26.56.apk`
Verified the test plan from https://github.com/brave/brave-core/pull/8377

- Confirmed custom AD notifications are served in Android
- Confirmed custom AD notification are shown correctly in Light mode
- Confirmed custom AD notification are shown correctly in Dark mode

Custom AD (system default) | Light Mode | Dark Mode
-------------------------------|---------------|--------------
