### ISSUE TITLE
Yahoo! mail detects ad-blocker, forces 15 second wait

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#13149]
## Description 

Yahoo! mail seems to be detecting Shields in Brave and forcing users to either disable their ad-blocker, or wait 15 seconds before they can use the site/access their email. No changes to settings seem to make much difference so we will likely need a full workaround for the site:
![image](https://user-images.githubusercontent.com/3299098/101812716-93127100-3ad0-11eb-9ec4-113fb675160d.png)
![image](https://user-images.githubusercontent.com/3299098/101812727-97d72500-3ad0-11eb-8576-c681e20afac1.png)

## Steps to Reproduce

   1. Have Brave and enjoy your privacy
   2. Visit Yahoo! mail
   3. Get blocked for 15 seconds before you can even access your account

## Reproduces how often: 

Every time.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

User reports:
https://www.reddit.com/r/brave_browser/comments/kadz9c/yahoo_mail_adblock_detector_not_blocked_by_brave/

**Comment by ryanbr** [comment]
Switching to Aggressive mode in Shields Ads/Trackers should resolve this.

Relevant fix https://github.com/uBlockOrigin/uAssets/pull/8276

**Comment by ryanbr** [comment]
Re-test in 24-48hrs. Let me know if there is any false positives

**Comment by rebron** [comment]
@ryanbr This looks fixed. Didn't encounter the screens above going through normal email actions in Yahoo!Mail

**Comment by ryanbr** [comment]
Confirmed everything is working, cc: @Brave-Matt
