### ISSUE TITLE
[Android] AC budget not set correctly from onboarding settings slide

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13148]
## Description 
When you join Rewards via onboarding modal and you see the settings slide, the AC budget selection is not being set correctly.

Note - if ads are not enabled by the time you get to this slide you won't see it. Per discussion with @deeppandya this is expected. 

## Steps to reproduce 

   1. Clean install 1.20.23
   2. Tap on BAT logo
   3. On the large onboarding modal, select "Start using Brave Rewards"
   4. Go thru the slides (not super fast, try to give ads a minute to start up)
   5. Once you get to the settings slide, select different values than the defaults for Ads and AC
   6. Complete the onboarding slides
   7. Go to chrome://rewards page

## Actual result 
Ads per hour setting is set correctly, AC budget is not. No matter what you select for AC budget it is set at 10 BAT

## Expected result
AC budget should be set per your selection

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? n/a
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.20.23

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information

cc @brave/legacy_qa @codybanxs @deeppandya

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `Bravearm 1.20.26`
- Verified that AC budget is set correctly from onboarding settings
Setup AC budget in the Onboarding flow

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 10` using `1.18.72 CR: 87.0.4280.101`

* verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/13148#issue-761434358 and ensured both `a-c` and `ads` were correctly being set
  * ensured that `5 BAT`, `15 BAT`, `25 BAT` and `50 BAT` were set to default under `brave://rewards` when selected
* ensured that restarting several times doesn't revert/lose state of the `a-c` & `ads` selections that were made during onboarding
* ensured that selecting different `a-c` options via `brave://rewards` after onboarding works as expected

Also ensured that the above cases worked via the following onboarding entry points:
* via the BAT icon as per https://github.com/brave/brave-browser/issues/13148#issue-761434358
* via tapping on the NTP SI for the first time when it appears
