### ISSUE TITLE
[Android] crash when claiming promotions

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13150]
## Description 
Crash when attempting to claim a promotion. 

## Steps to reproduce 

   1. Clean install 1.20.23
   2. Go to settings, enable Staging environment
   3. Relaunch when prompted
   4. Tap on BAT logo.
   5. "x" out of large and small onboarding UI
   6. UGP Grant notification is displayed.
   7. Tap on "Claim" button.

## Actual result 
Get spinner for a second, then Brave crashes

## Expected result
No crash, get grant as expected

## Issue reproduces how often 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? no
- Can you reproduce this issue with the current Play Store Beta version? n/a - beta crashes when tapping on BAT logo.
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information

cc @deeppandya @brave/legacy_qa

**Comment by kjozwiak** [comment]
@deeppandya we'll need to get this fixed QA won't be able to claim grants on staging and check tipping/a-c etc.. CCing @bsclifton @anthonypkeane.

**Comment by kjozwiak** [comment]
Closing this as it was fixed via https://github.com/brave/brave-core/pull/7411 and was merged into `1.19.x` & `1.18.x` via https://github.com/brave/brave-core/pull/7421 and https://github.com/brave/brave-core/pull/7423.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 10` using `1.18.72 CR: 87.0.4280.101`

* verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/13150#issue-761606585 and claimed a UGP grant several times without crashing
  * also claimed several UGP grants while the RE opt-in modal was visible via the rewards panel without crashes
