### ISSUE TITLE
M1 Mac Support

### ISSUE THREAD

**Issue by FatSandwich** [brave/brave-browser#13155]
Usually whenever I use Brave on my M1 Mac it works. But, now it has started to quit unexpectedly and has sometimes caused problems. I love this browser but I am currently using Safari because I cannot risk the work the is unsaved.

**Comment by kjozwiak** [comment]
We're in the process of getting M1 builds on release 👍 CCing @bsclifton @rebron as they've been close to the work and could probably give a better update.

**Comment by FatSandwich** [comment]
Great! By the way, is the Nightly Version supported for M1 Macs?

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/brave-browser/issues/12819

@FatSandwich yup- you can download any of our latest releases (look for Nightly) on https://github.com/brave/brave-browser/releases

Look for the `Brave-Browser-Nightly-arm64.dmg` - these should work great for you and it will auto update too 😄

**Comment by FatSandwich** [comment]
So, will all my data save in the Nightly Version like my BAT?

**Comment by mihaiplesa** [comment]
@FatSandwich both `x64` and `arm64` save data to the same location so it should work (just don't use them at the same time). Any other issues please report on https://github.com/brave/brave-browser/issues/12819

**Comment by FatSandwich** [comment]
Everything synced when I used a sync chain except for the BAT? Is there a fix for this?

**Comment by mihaiplesa** [comment]
https://github.com/brave/brave-browser/issues/11513

**Comment by FatSandwich** [comment]
Oh thanks!
