### ISSUE TITLE
Display iOS QR Code feature on Desktop

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#13159]
## Test plan
1. New profile
2. Visit brave://rewards/
3. Verify QR code button is showing
4. Follow steps in official help article https://support.brave.com/hc/en-us/articles/360052811072

## Description 
There was an issue with transfers between iOS and Desktop which has been identified and is being fixed. After this is resolved, we need to re-introduce the QR code

### History of QR code (for posterity)
1. Originally introduced with https://github.com/brave/brave-browser/issues/12176
1. Hidden with https://github.com/brave/brave-browser/issues/12475 because iOS side was not ready at the time
2. Shown again with https://github.com/brave/brave-browser/issues/12476, targeting the 1.18 release
3. Hidden after encountering an issue with https://github.com/brave/brave-browser/issues/13053 which shipped with 1.18

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.18.75 Chromium: 87.0.4280.101 (Official Build) (x86_64)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 10.15.7 (Build 19H15)
```

Verified the following:
1. Clean install, scan QR code and confirm it matches paymentId on brave://rewards-internals
2. Close/relaunch browser
3. Scan QR code and confirm it matches paymentId on brave://rewards-internals
4. Restore a wallet
5. Scan QR code and confirm it is updated and matches paymentId on brave://rewards-internals
6. Close/relaunch browser
7. Scan QR code and confirm it is updated and matches paymentId on brave://rewards-internals

Additionally, confirmed toggling ads on/off and AC on/off did not affect paymentId/QR code.

-----------------
