### ISSUE TITLE
reward payouts information via onboarding differs from rewards panel

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13158]
## Description 

Our current rewards onboarding flow mentions that users will be getting their rewards on the 5th of every month but once you've completed onboarding, the rewards panel mentions a different date at times. In this case, by the 6th. Seems like there's two conflicting messages.

## Steps to reproduce 

   1. launch a brave version that has RE onboarding (`1.20.23 CR: 88.0.4315.5` in this case)
   2. tap on the rewards icon and run through onboarding via `Start using Brave Rewards`
   3. notice the panel/screen that mentions payouts on the 5th of every month
   4. finish onboarding and you'll notice that the other UI mentions January 6th.

## Actual result 

**`Example`** | **`Example`**
---------------|----------------
![Screenshot_20201211-011647_Brave - Nightly](https://user-images.githubusercontent.com/2602313/101873099-57b98600-3b54-11eb-8e96-537e04625f80.jpg) | ![Screenshot_20201211-011325_Brave - Nightly](https://user-images.githubusercontent.com/2602313/101873111-5ab47680-3b54-11eb-97d0-269ea1118df5.jpg)

## Expected result

Those two dates should probably match or will confuse users.

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version?` Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 10`
   
## Brave version

* `1.20.23 CR: 88.0.4315.5`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

### Additional information

CCing @LaurenWags @deeppandya @codybanxs @bsclifton

**Comment by kjozwiak** [comment]
I wouldn't consider this a blocker but should clean this up sooner than later to avoid user confusion.

**Comment by kjozwiak** [comment]
Closing this as it was fixed via https://github.com/brave/brave-core/pull/7411 and was merged into `1.19.x` & `1.18.x` via https://github.com/brave/brave-core/pull/7421 and https://github.com/brave/brave-core/pull/7423.

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 with Android 5.1 running 1.18.72 Bravearm.apk

Confirmed onboarding and "Welcome to Brave Rewards" (ETA) UI both reflect the 5th:

Onboarding | After joining
---------- | ----------
![Screenshot_2020-12-14-17-13-31](https://user-images.githubusercontent.com/28145373/102155133-e9710e00-3e48-11eb-9ee8-8edd8b0862c9.png) | ![Screenshot_2020-12-14-17-33-03](https://user-images.githubusercontent.com/28145373/102155136-ebd36800-3e48-11eb-8e65-54c1a1138ffe.png)
