### ISSUE TITLE
Cannot access to a needed web page

### ISSUE THREAD

**Issue by angelog0** [brave/brave-browser#13165]
For now I have seen the issue on GNU/Linux and Windows 10 64 bit with Brave 1.18.70. The issue is similar (if not the same) I flagged [here](https://github.com/bromite/bromite/issues/464) about an year ago. 

There it was fixed as a fix for bug [#470](https://github.com/bromite/bromite/issues/470).

BTW, I find very annoying you at each **new release** add an icon (`Add card`, now) one has to hide...

**Comment by rebron** [comment]
@angelog0 Have you tried with shields down? When filing issues, can you use the issue template? What site were you on when you encountered the login issue.

**Comment by angelog0** [comment]
With the shields down it works: [brave-shield.tar.gz](https://github.com/brave/brave-browser/files/5697413/brave-shield.tar.gz)

**Comment by ryanbr** [comment]
So what is the site? Just a direct link is needed and what is broken on it @angelog0

**Comment by ryanbr** [comment]
Is this issue still applicable @angelog0 with the latest Brave version? If you can link to the site, we can investigate.
