### ISSUE TITLE
Option to pick active tab title font weight

### ISSUE THREAD

**Issue by rubenpoppe** [brave/brave-browser#13164]
## Description 
Active tab title now is in semibold instead of the previous regular.
![image](https://user-images.githubusercontent.com/6934044/101915076-6a1fd800-3bc5-11eb-8d82-656a30cb98be.png) 
I would like the option to pick the active tab title font weight.

## Steps to Reproduce

   1. Open a tab
   2. Be active on tab

## Actual result:
Active tab title in semibold

## Expected result:
Option to choose font weight (regular/semibold) in settings->appearance

## Reproduces how often: 
Standard behavior

## Brave version (brave://version info)
Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Not sure
- Can you reproduce this issue with the nightly channel? 
Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
No further info

**Comment by bamacyber** [comment]
@rubenpoppe so basically you want the ability to configure how bold the title of a new tab is? Right now, it is the default for whatever brave has it set at but you think it would be nice to have an option in settings to change how bold an active tabs title is?

**Comment by rubenpoppe** [comment]
@bamacyber yes it's basically that. It came to mind due to the recent change in Brave Version 1.18.70.

**Comment by bamacyber** [comment]
@rubenpoppe ok. Can you update me on the recent change you are referring to? I am new to contributing to this particular part of brave. Also, I started some discussion around your feature request so we could get the communities input 🙂 
https://community.brave.com/t/active-title-bold-weight-settings/187233

**Comment by rubenpoppe** [comment]
It was just the latest release (1.18.70). Release notes can be found on the [Brave Release Channel](https://community.brave.com/t/release-channel-1-18-70/186749). Issue around the topic is #8576.

**Comment by mariansam** [comment]
Maybe it's just my opinion, but I think the new design is ugly. It was the first thing that hit me when I updated Brave few days ago. I understand the reason and it may make sense that this would be the default. But I'd love to change this to the old design. Unfortunately I don't think Brave/Chromium has something like Firefox's `userChrome.css`/`userContent.css`, which would solve this...
![image](https://user-images.githubusercontent.com/33497067/102008948-6fe7fb80-3d34-11eb-9529-c5b8e17e843b.png)

**Comment by rubenpoppe** [comment]
It might get slightly better. Check out #13174.

**Comment by rebron** [comment]
@rubenpoppe We're going to close this one out as we're addressing the font-weight issue via #13174. For options to change font-weight, that's more appropriate as an extension.

@mariansam Thanks for your comment. We updated the design to make the tab you're on stand out more. We hid the [x] on the other tabs so you can see more of the page title for background tabs. Seeing all those [x] is redundant and a mouseover shows the [x]. Change and slight changes are tough some times especially for things we're used to, but I think what we changed is a better design in the long run.
