### ISSUE TITLE
Add adsEnabled to anonymous usage ping

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#13168]
## Description 

Add the param `adsEnabled:[1|0]` to the anonymous usage ping.

Related https://github.com/brave/security/issues/261

## Test Plan

Using Wireshark or Charles intercept the request to the laptop-updates server and ensure that `adsEnabled` is present.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.20.88 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/105795481-363e1d80-5f8d-11eb-962b-f1d05f238847.png)

**Comment by btlechowski** [comment]
While adsEnabled is added to the usage ping, it is always set to false. Logged https://github.com/brave/brave-browser/issues/13765.
