### ISSUE TITLE
Brave icon in About Brave looks blurry at high DPI and has a blue border around it

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1316]
## Description 

Brave icon in About Brave looks blurry at high DPI and has a blue border around it

## Steps to Reproduce

   1. Install Brave beta on Linux
   2. Visit About Brave from hamburger menu or navigating to chrome://settings/help
   3. Icon has a blue border around it and looks pixelated at 200% DPI

## Actual result:

At 100% DPI on Ubuntu
![image](https://user-images.githubusercontent.com/17010094/46152603-4f105a00-c23f-11e8-8911-ba7391ae1fec.png)
At 200% DPI 
![image](https://user-images.githubusercontent.com/17010094/46152561-3dc74d80-c23f-11e8-88b8-6cbbd87f593b.png)
App icon in general looks clear 
![image](https://user-images.githubusercontent.com/17010094/46152665-79621780-c23f-11e8-966a-c87398c13571.png)

## Expected result:
Should not be pixelated and should not have the blue border around it 

## Reproduces how often: 

Easy on Beta build

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rossmoody** [comment]
I'd like to investigate this but I don't have access to a Linux machine and I think it might be a styling reaction in the browser via CSS/Javascript going on here. For instance there is an easter egg related to that icon that triggers a spin if you click it. I have a hunch it's reacting poorly in some way on Linux machines. Any way to do a quick double check and just make sure there isn't some weird CSS styling reaction going on here? The pixelation makes sense. It's being served as a 32x32px png.

**Comment by srirambv** [comment]
The icon on the welcome screen also seems to have the border on Linux. This is only happening on the desktop and not on the VM
![image](https://user-images.githubusercontent.com/17010094/46685181-d5735700-cbc2-11e8-84f1-ebb7d508c063.png)

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/46691875-e5476700-cbd3-11e8-8b54-55973d355462.png)

**Comment by srirambv** [comment]
This seems to be fixed on latest release build and on beta. 
![screenshot from 2018-12-26 07-15-50](https://user-images.githubusercontent.com/17010094/50428523-5dbdea00-08de-11e9-933e-59b78db3d766.png)
