### ISSUE TITLE
NTP SI panel keeps re-appearing when revisiting the tab that initially displayed it

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13161]
## Description 

When you go back and view the original NTP SI tab, the modal will re-appear at the bottom even though it was already clicked and the rewards panel/onboarding was dismissed. You can repeat this several times.

## Steps to reproduce 

   1. launch a brave version that has RE onboarding (`1.20.23 CR: 88.0.4315.5` in this case)
   2. view several tabs so you get a NTP SI and tap on the panel at the bottom
   3. tap on the modal at the bottom which will open the rewards panel/onboarding flow
   4. dismiss the onboarding tour/flow and the `I'm In` modal
   5. open a new tab
   6. go back to the previous tab which should be the original NTP SI tab

You'll notice that the modal at the bottom will appear again and you can run through the entire rewards panel flow once again.

## Actual result 

Example of the issue occurring: https://youtu.be/jKObEfv5n6s

## Expected result

Once the modal is clicked on NTP SI, it should never re-appear again as per spec.

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version?` Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 10`
   
## Brave version

* `1.20.23 CR: 88.0.4315.5`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

### Additional information

CCing @LaurenWags @deeppandya @codybanxs @bsclifton

**Comment by deeppandya** [comment]
@kjozwiak @LaurenWags the condtions i have applied here is :
1. if user open first SI with out interactive with rewards panel or `chrome://rewards` settings, in that user hasn't seen new onboarding modal. so in this case user would see bottom sheet on SI and if user clicks on the banner it would open rewards panel with onboarding modal.
2. if user has seen new onboarding modal from rewards or `chrome://rewards` settings and hasn't enabled ads, then user won't see any banner on SI at all.
3. if user user enabled ads from any onboarding modal or from `chrome://rewards` settings, regardless of seeing the oboarding modal, user would see thebottom banner and if user clicks on the banner, it would open instructional page instead of opening the rewards page as user has already enabled ads.

**Comment by kjozwiak** [comment]
Closing this as it was fixed via https://github.com/brave/brave-core/pull/7411 and was merged into `1.19.x` & `1.18.x` via https://github.com/brave/brave-core/pull/7421 and https://github.com/brave/brave-core/pull/7423.

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `Samsung Galaxy S10+` running `Android 10` using `1.18.72 CR: 87.0.4280.101`
* Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 10` using `1.18.72 CR: 87.0.4280.101`

Went through the following STR/Cases for both devices mentioned above:

* verified that the original issue via https://github.com/brave/brave-browser/issues/13161#issue-762008524 wasn't reproducible
* ensured that tapping on the `NTP SI  Learn More` banner opens the rewards panel with the new RE opt-in onboarding if the user hasn't interacted with the rewards panel before
* ensured that the `NTP SI Learn More` banner wasn't being displayed if the user has interacted with the rewards panel/RE opt-in onboarding
* ensured that tapping on the `NTP SI Learn More` banner opens the modal with the NTP SI information and the ability to disable NTP SI if ads has been enabled
