### ISSUE TITLE
Autoplay blocked indicator shows up when media is not autoplayed

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#13167]
## Description 

Autoplay blocked indicator appears when there is a media element

## Steps to Reproduce

   1. Use fresh profile and make sure global autoplay setting is allowed and no entries in block list (brave://settings/content/autoplay)
   2. Visit https://www.imdb.com/title/tt1190634/?ref_=nv_sr_srsg_0
   3. There is no video being autoplayed
   4. Change the global autoplay setting to blocked
   5.  Visit https://www.imdb.com/title/tt1190634/?ref_=nv_sr_srsg_0
   6. Autoplay blocked indicator is the the top right of url bar even though there is nothing being autoplayed

## Actual result:

 Autoplay blocked indicator is the the top right of url bar even though there is nothing being autoplayed

## Expected result:
There should not be a autoplay blocked indicator when media is not autoplayed

## Reproduces how often: 

always

## Brave version (brave://version info)

1.18.70

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
yes
- Can you reproduce this issue with the beta channel? 
yes
- Can you reproduce this issue with the nightly channel? 
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.20.86 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified autoplay is enabled by default in `brave://settings/content/autoplay` and there is no entries in block list
![image](https://user-images.githubusercontent.com/34715963/105413380-504ac980-5c36-11eb-9062-11bed950058d.png)
Verified when autoplay is enabled there is no video autoplayed on `https://www.imdb.com/title/tt1190634/?ref_=nv_sr_srsg_0`
![image](https://user-images.githubusercontent.com/34715963/105413538-85efb280-5c36-11eb-918e-d1d5e8de020a.png)
Verified when autoplay is disabled there is no video autoplayed on `https://www.imdb.com/title/tt1190634/?ref_=nv_sr_srsg_0` and Autoplay blocked indicator is not shown
![image](https://user-images.githubusercontent.com/34715963/105413672-b9324180-5c36-11eb-823e-1a5024854057.png)

**Comment by stephendonner** [comment]
Verified using the testplan, on 

Brave | 1.20.88 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

When `autoplay` is set to `blocked`, I don't get the autoplay-blocked indicator on `https://www.imdb.com/title/tt1190634/?ref_=nv_sr_srsg_0`

<img width="1680" alt="Screen Shot 2021-01-25 at 2 49 06 PM" src="https://user-images.githubusercontent.com/387249/105775939-86c96280-5f1c-11eb-8c2c-5182b560dc39.png">


Also verified that I could reproduce the problem, pre-fix, using 

Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

<img width="1672" alt="Screen Shot 2021-01-25 at 2 42 01 PM" src="https://user-images.githubusercontent.com/387249/105775980-9a74c900-5f1c-11eb-8cac-ec053513be37.png">

@LaurenWags / @kjozwiak do we also want to verify on M1?

**Comment by kjozwiak** [comment]
For now we're only verifying issues on `Intel x64`. However, if we start noticing that we're getting regressions/reports that are only happening on `Arm x64` and not `Intel x64` we'll need to start checking on both. We do check and make sure that the different types of executables are working without issues and that upgrades retain data as per https://github.com/brave/brave-browser/issues/13577.
