### ISSUE TITLE
Click on `Take quick a tour` doesn't open up the onboarding flow in an upgraded profile 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13166]
## Description 
Click on `Take quick a tour` doesn't open up the onboarding flow in an upgraded profile 

## Steps to reproduce 

   1. Clean profile GPS version
   2. Upgrade to `1.18.71`
   3. Open brave://rewards
   4. Observe the onboarding flow
   5. Click on `Take quick a tour` doesn't open up the onboarding flow
   

## Actual result 
Click on `Take quick a tour` doesn't open up the onboarding flow in an upgraded profile 

## Expected result
Click on `Take quick a tour` should open up the onboarding flow in an upgraded profile 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): Gionee s5
   - Android version: 5.1.1
   
## Brave version

1.18.71
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @deeppandya @anthonypkeane

**Comment by LaurenWags** [comment]
Per discussion with @deeppandya no upgraded profiles (regardless of Rewards status prior to upgrade) should show onboarding.

**Comment by kjozwiak** [comment]
Closing this as it was fixed via https://github.com/brave/brave-core/pull/7411 and was merged into `1.19.x` & `1.18.x` via https://github.com/brave/brave-core/pull/7421 and https://github.com/brave/brave-core/pull/7423.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 10` using `1.18.72 CR: 87.0.4280.101`

Upgraded from `1.17.75 CR: 87.0.4280.88` to `1.18.72 CR: 87.0.4280.101` and ensured that the new opt-in modal/onboarding wasn't being displayed as per https://github.com/brave/brave-browser/issues/13166#issuecomment-743379228.

* ensured that tapping on the rewards panel didn't display the opt-in modal/onboarding flows
* ensured that `brave://rewards` didn't display the opt-in modal/onboarding flows
