### ISSUE TITLE
rewards panel being opened after 4 days even though it was viewed/dismissed via NTP SI entry point

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13160]
## Description 

If you view the rewards panel/onboarding through NTP SI, it will automatically re-open again on the fourth day. From my understanding, if a user has already viewed the panel by clicking on the rewards icon via the URL or NTP SI, it shouldn't be displayed on the fourth day.

## Steps to reproduce 

   1. launch a brave version that has RE onboarding (`1.20.23 CR: 88.0.4315.5` in this case)
   2. view several tabs so you get a NTP SI and tap on the panel at the bottom
   3. rewards panel should open at the top, dismiss onboarding and `I'm In` modals via the `X`
   4. close brave and move the system time +4 days
   5. launch brave and the rewards panel will automatically launch again

## Actual result 

Example of issue occurring: https://youtu.be/uNF8J6wI7dg

## Expected result

As per the spec and https://www.figma.com/file/0dbMYs8Wp8W3RgrG1yTdki/RE-1.0?node-id=541%3A19529, I believe the panel shouldn't be launching.

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version?` Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 10`
   
## Brave version

* `1.20.23 CR: 88.0.4315.5`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

### Additional information

CCing @LaurenWags @deeppandya @codybanxs @bsclifton

**Comment by kjozwiak** [comment]
Going to label this as `release/blocking` but I'll let @bsclifton & @LaurenWags make the call. Probably don't want to annoy users with panel popups.

**Comment by LaurenWags** [comment]
Also reproduces in the following case:

1. launch a brave version that has RE onboarding (1.18.71)
2. Tap on panel, "x" out of large onboarding UI. "x" out of small onboarding UI also
3. close brave and move the system time +4 days
4. launch brave and the rewards panel will automatically launch again

**Comment by kjozwiak** [comment]
Closing this as it was fixed via https://github.com/brave/brave-core/pull/7411 and was merged into `1.19.x` & `1.18.x` via https://github.com/brave/brave-core/pull/7421 and https://github.com/brave/brave-core/pull/7423.

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 with Android 5.1 running 1.18.72 Bravearm.apk

<details>
<summary>Scenario 1 - don't interact with BAT logo</summary>

1. Clean profile 1.18.x. Do not tap on BAT logo.
2. Close app, remove from memory. Advance Date/Time 24h.
3. Launch, do not tap on BAT logo. Observe panel does not open automatically.
4. Close app, remove from memory. Advance Date/Time 24h.
5. Launch, do not tap on BAT logo. Observe panel does not open automatically.
6. Close app, remove from memory. Advance Date/Time 24h.
7. Launch, do not tap on BAT logo. Observe panel does not open automatically.
8. Close app, remove from memory. Advance Date/Time 24h.
9. Launch.
10. Confirmed panel opens automatically and shows large onboarding UI.

</details>

<details>
<summary>Scenario 2 - interact with BAT logo</summary>
1. Clean profile 1.18.x. Tap on BAT logo. Dismiss large and small onboarding.
2. Close app, remove from memory. Advance Date/Time 4 days.
9. Launch.
10. Confirmed panel does not open automatically as the user has already interacted with it.

</details>
