### ISSUE TITLE
Brave News - classify news by country

### ISSUE THREAD

**Issue by Bundy01** [brave/brave-browser#13176]
Hi,

For Brave Today, I'm thinking of classifying the news by country. With a GitHub repository, everyone could enrich the URL database for example.

For Brave Rewards, it would be a good idea to reduce the level of donations. For example, 1, 5, 10, 15...BATs. Or a drop-down menu to choose the number of BATs per unit.

Regards.

**Comment by bsclifton** [comment]
Thanks for the suggestions @Bundy01 😄 We've actually taken care of your second request (RE: Brave Rewards). You should see custom tip amounts now, thanks to work by @zenparsing 

I updated the ticket to be Brave News specific and will add some tags to help triage this request

**Comment by mattmcalister** [comment]
We have some content classifier work coming up. A version of this idea will be addressed there. I'm going to close this issue.
