### ISSUE TITLE
Add visual feedback when installing IPFS

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13170]
This issue was broken out from @jessicaschilling's issue posted here: #13125

When installing IPFS from the infobar (the only way currently), there is no visual feedback .

Behind the scenes go-ipfs is downloaded (which may take time on slow network) and user will think "IPFS support is broken, because nothing happened"

Jessica suggested:
Fix: open brave://ipfs (in a new active tab) and display "installation" state (downloading, unpacking, starting). More details on this below.

But since that's a diagnostics page, I think that's not completely right. 
I think we could just reload the page with the local node URI and it will show the loading indicator at least.

**Comment by lidel** [comment]
I don't believe a regular "page load spinner" would be enough.

That creates a perception of "IPFS being slow" when in fact its Brave fetching and installing go-ipfs behind the scenes for the most of  the time.  There should be more clear messaging to the user why the very first load takes such long time.  


I'd argue opening `brave://ipfs` is way better: user not only learns what's going on, but also learns there is this diagnostic page for things related to "IPFS in Brave".

**Comment by jessicaschilling** [comment]
Completely agree with @lidel. If we can provide any visual artifacts to help this along, would be happy to.

**Comment by jessicaschilling** [comment]
@lidel @bbondy Below are some super quick inspect-element amends that could make a substantial, quick-win difference in the usability of this diagnostics page:

![image](https://user-images.githubusercontent.com/1507828/102560582-c8e6c500-408f-11eb-9fc3-81aa63b07f04.png)

The only changes here that would involve more than just a few CSS amends would be:
- Adding the "installing ... X%" in place of "IPFS is running"/"IPFS is not running"
- Graying out inactive/disabled items instead of just not displaying them

I hope this is useful. Also cross-posting in https://github.com/brave/brave-browser/issues/13173 since that issue deals with suggestions for improving the diagnostic page.

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` with the testplan from https://github.com/brave/brave-core/pull/8219 on build 

Brave | 1.23.39 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

### `Case 1:`
* install and launch a tool such as Apple's `Network Link Conditioner`
* new profile
* load `brave://ipfs`
* click `Install and start`
* let it begin installation, then select a few "poor" network-speed/error conditions (high latency, slow speed, high rate of packets dropped, etc.)
* confirm the progress % adjusts accordingly to your chosen network conditioning(s)
* switch to a "good" network-condition profile (such as `Wi-Fi` or slower `DSL`)
* confirm the progress % climbs up more quickly, and finishes installation

Confirmed installation finished and node started up, connected to peers successfully

![slow-ipfs](https://user-images.githubusercontent.com/387249/111237144-b1957600-85b1-11eb-86d0-122088c24f54.gif)

### `Case 2:`
* new profile
* load `brave://ipfs`
* click `Install and start`
* let it begin installation, then remove Ethernet cable
* wait a bit; confirm error message `An error occurred; please try to install the node again.` appears
* reconnect Ethernet cable
* click `Install and start` again (be patient so network link can be re-established)

Confirmed installation finished and node started up, connected to peers successfully

![ipfs-error](https://user-images.githubusercontent.com/387249/111237006-60858200-85b1-11eb-84d8-a0e31ca7e4af.gif)
