### ISSUE TITLE
Improvements for the IPFS diagnostics page brave://ipfs

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13173]
This issue was broken out from @jessicaschilling's issue posted here: #13125

## `brave://ipfs` diagnostic screen changes:

> ![2020-12-05--19-28-17](https://user-images.githubusercontent.com/157609/101260423-0e220300-3730-11eb-85d1-613bad314db5.png)

- [x] Start and stop button should only show when it is applicable (https://github.com/brave/brave-browser/issues/14115)
- [x]  Add `Restart` button (speeds up applying config changes)
- [x] If not installed, note "IPFS not installed" and button to install _and start_; other items should be grayed out to indicate missing functionality
- [x] Additionally, display the `Learn more about IPFS and privacy` link described above (placement/appearance TBD once we know whether this diagnostic page can be included with the rest of Brave settings UI)
- [x] Diagnostic page displays API address, but there is no way to open Web UI
    - Fix: when node is running, add a button that opens its Web UI (`http://127.0.0.1:{api-port}/webui`)
        - Display at same level of prominence as `Launch`/`Shut Down` button
        - Q: Text should be `My Node` to match IPFS Companion
        - Q: Button should be a different color to convey different function than `Launch`/`Shut Down` button — will be able to have better guidance on this once we know whether this diagnostic page can be included with the rest of Brave settings UI
- `Connected peers:` Add `(details)` link after peer count, linking to Peers screen in IPFS Web UI (`http://127.0.0.1:{api-port}/webui/#/peers`)

- [x] If the user has this diagnostic page open in one tab with their node stopped, and then starts their node from a different tab, this tab doesn't update unless it's reloaded. Can this be fixed?
- [x] When diagnostic page is opened on an empty profile (i.e. user has not yet been asked to enable IPFS support), there is no UI to start the node:
  > ![2020-12-05--19-24-19](https://user-images.githubusercontent.com/157609/101260424-0eba9980-3730-11eb-84ff-f7c9624027cb.png)
    - [x] Fix (this behavior is already specified earlier in this document): If not installed, note “IPFS not installed” and button to install _and start_; other items should be grayed out _but present_ to indicate missing functionality
    - [x] Additionally, display the `Learn more about IPFS and privacy` link described above (placement/appearance TBD once we know whether this diagnostic page can be included with the rest of Brave settings UI)

**Comment by jessicaschilling** [comment]
Some of the notes above hinged on the question about whether it was possible to include this content in the main Brave settings pages instead. Since that sounds like it's not the best way forward for now, suggesting some amendments to the checklist above for clarity:

- Replace `Daemon status` with `IPFS node status`
- Replace `Launched: true` with `Node is running` or `Node is not running`
- Buttons should read `Start` or `Stop` instead of `Launch` or `Shutdown` (think this was actually covered under #13169)
- `Learn more about IPFS and privacy` link (to https://support.brave.com/hc/en-us/sections/360010974932-InterPlanetary-File-System-IPFS-) should appear on its own line under the list of addresses, with some padding-top to separate it
- Button for `My node` should be a different color from the `Start` or `Stop` button - is there an existing visual style for this?

**Comment by jessicaschilling** [comment]
Note: please see https://github.com/brave/brave-browser/issues/13170#issuecomment-747797769 for a quick mockup that illustrates some of the above requests. Thanks!

**Comment by stephendonner** [comment]
Verified `FIXED` using `beta` and the inline test notes here, on 

Brave | 1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

`Start`, `Stop`, and `Restart` buttons were verified in https://github.com/brave/brave-browser/issues/14115

* default state, with 0'd out stats and empty paths:
<img width="1312" alt="Screen Shot 2021-03-03 at 9 15 17 AM" src="https://user-images.githubusercontent.com/387249/109844465-007dfb80-7c01-11eb-95be-9f0cc21fd7a7.png">

* after clicking `Install and start`:
<img width="1312" alt="Screen Shot 2021-03-03 at 9 17 11 AM" src="https://user-images.githubusercontent.com/387249/109844722-420ea680-7c01-11eb-807a-30236e216792.png">

* `My Node` button is same color as the rest of the button (which diverges from suggestion); filed https://github.com/brave/brave-browser/issues/14452

* Connected peers (`details`) link goes to http://127.0.0.1:45004/ipfs/bafybeianwe4vy7sprht5sm3hshvxjeqhwcmvbzq73u55sdhqngmohkjgs4/#/peers<img width="1312" alt="Screen Shot 2021-03-03 at 9 25 44 AM" src="https://user-images.githubusercontent.com/387249/109845907-79318780-7c02-11eb-83b7-fc684f9c22c1.png">

* `Learn more about IPFS and privacy` link points to https://support.brave.com/hc/en-us/sections/360010974932-InterPlanetary-File-System-IPFS-

* `My Node` opens http://127.0.0.1:45004/ipfs/bafybeianwe4vy7sprht5sm3hshvxjeqhwcmvbzq73u55sdhqngmohkjgs4/#/

<img width="1312" alt="Screen Shot 2021-03-03 at 9 17 48 AM" src="https://user-images.githubusercontent.com/387249/109844885-69fe0a00-7c01-11eb-8565-a90a08c3fa80.png">
