### ISSUE TITLE
Add a "Brave page" like indicator for IPFS schemes

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13172]
This issue was broken out from @jessicaschilling's issue posted here: #13125

<img width="142" alt="Screen Shot 2020-12-11 at 4 39 03 PM" src="https://user-images.githubusercontent.com/831718/101957454-76a92e00-3bcf-11eb-8f81-60c3986ff85d.png">

Other than looking at the address bar, it would be good to show when the user is using their local IPFS node via. aURL bar indicator similar to the Brave one.

Clicking on IPFS icon here could open `brave://ipfs` diagnostic page (or a better UI in the future).
A better UI would be a flyout view that has information about the connection.

**Comment by jessicaschilling** [comment]
+1 for a flyout view here! Content in the flyout could be something like ...

_Resources loaded over IPFS
One or more resources on this site were loaded using your IPFS node, which is currently connected to XX peers. Learn more
_

It's also important to consider that there may be cases in which a page might display both another informational icon - maybe a "secure padlock" and an IPFS cube, or the "Not Secure" message and an IPFS cube. There's an opportunity here to make a decision that will ultimately impact every browser 😊 in a way that the original addition of the "secure padlock" icon did ... so this is definitely worth some careful thought before implementing. Would be very happy to be more deeply involved here once you're ready to move this into your active list.

**Comment by spylogsster** [comment]
The first PR for the badge created https://github.com/brave/brave-core/pull/8234 and security review for this https://github.com/brave/security/issues/368

The dialog would change incrementally after with separate security issue

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` build 

| Brave    | 1.24.11 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64) |
| -------- | ------------------------------------------------------------ |
| Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534} |
| OS       | macOS Version 11.2.3 (Build 20D91)                           |


Checked:
1. shows up for both `ipfs` and `ipns` URLs: `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`, `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/`, `ipns://brantly.eth`, `ipns://en.wikipedia-on-ipfs.org`, on both dark and light themes

| Example | Example | Example | Example | Example | Example |
|---------|----------|----------|----------|---------|----------|
<img src="https://user-images.githubusercontent.com/387249/112052442-5fec6e80-8b10-11eb-8c2d-4e8014c83c29.png"> | <img src="https://user-images.githubusercontent.com/387249/112052460-637ff580-8b10-11eb-914a-f669d9ce1a51.png"> | <img src="https://user-images.githubusercontent.com/387249/112052461-637ff580-8b10-11eb-94b5-7f7d54f1d2c2.png"> | <img src="https://user-images.githubusercontent.com/387249/112052467-64188c00-8b10-11eb-8f22-37d6ab9f0c51.png"> | <img width="1312" alt="Screen Shot 2021-03-22 at 1 25 09 PM" src="https://user-images.githubusercontent.com/387249/112053889-261c6780-8b12-11eb-9101-609269e70279.png"> | <img width="1312" alt="Screen Shot 2021-03-22 at 1 25 28 PM" src="https://user-images.githubusercontent.com/387249/112053894-27e62b00-8b12-11eb-9d17-4a89b5f0249b.png">



2. shows up for interstitial-installation page

<img src="https://user-images.githubusercontent.com/387249/112052364-45b29080-8b10-11eb-9e36-5461c8fab8f4.gif">

3. **doesn't** show up for `brave://ipfs-internals` pages

| Example | Example |
|----------|---------|
<img width="865" alt="Screen Shot 2021-03-22 at 11 55 34 AM" src="https://user-images.githubusercontent.com/387249/112052438-5e22ab00-8b10-11eb-92bd-5818c854622d.png"> | <img width="865" alt="Screen Shot 2021-03-22 at 11 56 30 AM" src="https://user-images.githubusercontent.com/387249/112052448-611d9b80-8b10-11eb-8fe4-ace4a22e2f71.png">

4. **doesn't** show up for `https://en-wikipedia--on--ipfs-org.ipns.dweb.link/wiki/` and `https://en.wikipedia-on-ipfs.org/wiki/`

| Example | Example |
|----------|---------|
<img width="1573" alt="Screen Shot 2021-03-22 at 12 31 03 PM" src="https://user-images.githubusercontent.com/387249/112052350-43503680-8b10-11eb-8af3-adeba2592ef1.png"> | <img width="1573" alt="Screen Shot 2021-03-22 at 12 31 11 PM" src="https://user-images.githubusercontent.com/387249/112052372-46e3bd80-8b10-11eb-9062-8a0a86ddbf6b.png">
