### ISSUE TITLE
Brave Rewards Toggle Switch Not Showing Up

### ISSUE THREAD

**Issue by hfun77** [brave/brave-browser#13178]
## Description 
The toggle switch to turn on Brave Rewards is not showing up on my brave://rewards/ page.

## Steps to Reproduce
   1. Go to brave://rewards/.
   2. Attempt to turn on Brave Rewards.

## Actual result:
<img width="830" alt="Screen Shot 2020-12-12 at 10 33 25 AM" src="https://user-images.githubusercontent.com/31161022/101989431-df42ea00-3c65-11eb-9f3a-5ce25f53d2d4.png">

## Expected result:
Switch to turn on ads.

## Reproduces how often: 
Easily reproduced - always happens on brave://rewards.

## Brave version
Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 11.0.1 (Build 20B29)

## Miscellaneous Information:
I just installed Brave for the first time yesterday, that might have something to do with it.

**Comment by thefallofbecause** [comment]
There is no master toggle in that space. The toggle to turn on/off Rewards is the one just below which you already have turned on.

**Comment by hfun77** [comment]
Ok, I saw that there was supposed to be a switch there in a youtube video, thanks.

**Comment by bsclifton** [comment]
Versions 1.18 and higher don't show a master toggle; instead they have a toggle for ads / auto-contribute separately
