### ISSUE TITLE
decrease font-weight to medium=500 for focused tab follow up to #8576 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#13174]
## Description 

#8576 sought to improve tab contrast. The font-weight for the focused tab is semi-bold = 600 but should be reduced to medium = 500. 

## Steps to Reproduce

   1. Open browser and open a few tabs.
   2. Notice weighting on focused tab is semi-bold
 

## Actual result:

<img width="648" alt="Screen Shot 2020-12-11 at 2 24 42 PM" src="https://user-images.githubusercontent.com/5951041/101960594-a69b0600-3bbc-11eb-86d9-be6705b42d2e.png">

## Expected result:
Slightly less bold

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc: @karenkliu

**Comment by GeetaSarvadnya** [comment]
To test this we would need a new build that is greater than 1.19.76

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.19.78 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Ubuntu 18.04 LTS

Verified that the font is less bold in 1.19.x 
Dark mode
1.18.x
![image](https://user-images.githubusercontent.com/34715963/104010184-6a9f9480-51ac-11eb-8cd0-7c3974a67c6c.png)
1.19.x
![image](https://user-images.githubusercontent.com/34715963/104010264-83a84580-51ac-11eb-85c2-21e426627907.png)

Light mode
1.18.x
![image](https://user-images.githubusercontent.com/34715963/104010415-bce0b580-51ac-11eb-8fc7-b021476db1cf.png)
1.19.x
![image](https://user-images.githubusercontent.com/34715963/104010469-cff38580-51ac-11eb-815b-04eac19b8155.png)
