### ISSUE TITLE
Dynamically update settings page to add local node option when a local node is installed

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13171]
This issue was broken out from @jessicaschilling's issue posted here: #13125

If you load brave://settings/extensions in a tab and then install the the IPFS local node in another tab.  If you don't reload the settings page, then it shows a customized drop down list option. 

> After user is asked and chooses to "Enable IPFS", then the droplist includes a new item named "Customised".

~Instead we should dynamically add a Local option and not wait for the page to be reloaded to show the proper value.~

We'll instead always have a Local node option. When a user selects Local node, if it is not installed, we'll open a tab with this URI:
ipfs://bafkreigxbf77se2an2u6hmg2kxxbhmenetc7dzvkd3rl4m2orlobjvqcqq

**Comment by lidel** [comment]
I'd argue "Local (embedded go-ipfs)" should ALWAYS be on the list, and when user selects it, Brave should make a check if go-ipfs is installed, if not, install it and start it.

Without this, we have onboarding problem, because we assume user will enter `ipfs://cid`, while I'd argue its more likely that:
1. User learns Brave "supports IPFS natively"
2. User goes to _Settings_ and does not see option to start embedded node, the only option is a third-party gateway:
   > ![2020-12-17--15-28-25](https://user-images.githubusercontent.com/157609/102501330-9c29b200-407d-11eb-863d-b016deb79735.png)

**Comment by jessicaschilling** [comment]
Completely agree.

**Comment by bbondy** [comment]
That sounds good as an alternate way to install rather than when they visit an ipfs:// URL. 
We'll have to take this into account as part of the next set of work in the new year though.

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` build with the testplan from https://github.com/brave/brave-core/pull/8315

Brave | 1.24.26 Chromium: 90.0.4430.30 (Official Build) nightly (x86_64)
-- | --
Revision | 5674335ff855e43f3bccf8cfc29a779bdf0d067f-refs/branch-heads/4430@{#532}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1.  new profile
2. launched Brave
3. loaded `brave://ipfs-internals` to confirm IPFS local node was neither running nor installed
4. opened a new tab with `brave://settings/ipfs`
5. from`Method to resolve IPFS resources`, chose `Local node`
6. switched back over to `brave://ipfs-internals` tab and confirmed the installation and local-node initialization began and completed
7. loaded `ipns://brantly.eth` in a new tab and confirmed it loaded it over localhost (via Developer Tools' Network panel): `brantly.eth.ipns.localhost`

<img width="1312" alt="Screen Shot 2021-03-25 at 4 28 11 PM" src="https://user-images.githubusercontent.com/387249/112556325-30936700-8d87-11eb-9d61-920262ad3414.png">


![ipfs-local](https://user-images.githubusercontent.com/387249/112556185-dbefec00-8d86-11eb-815c-e48820cca83d.gif)
