### ISSUE TITLE
Default shields settings doesn't work as intended 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1317]
## Description 

While verifying #1288  found changing shields settings in preferences doesn't work as intended

## Steps to Reproduce

   1. Clean launch profile
   2. Visit dailymail.co.uk in a new tab, ensure ads/trackers are blocked
   3. Change default ad settings to `Allow all ads and trackers`
   4. Go back to dailymail.co.uk tab and reload, shields still shows 3 blocked items all tracking scripts
   5. Change back default ad settings to `Block ads and trackers`
   6. Reload dailymail.co.uk and toggle ad settings in shields, count show 0, page loads all tracking scripts and ads on the page

## Actual result:

https://youtu.be/l75ZWlgbySA

## Expected result:
Should work as intended setting is set

## Reproduces how often: 

Easy 

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows

### Reproducible on current release:

No b-l settings work as expected

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

#1288

**Comment by bbondy** [comment]
Pretty sure it was all working correctly except for just the ad-block setting, but that should be fixed with the latest merge.

**Comment by LaurenWags** [comment]
Verified passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

* Verified STR from description
