### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by EstebanJoseSantos** [brave/brave-browser#13179]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.18.70  Chromium: 87.0.4280.101
Operating System: Windows NT 10.0.18363

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Browser
2. Wait until it cash
3. It will happen within 1 minute

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/d5260000-f134-8705-0000-000000000000

**Comment by jthvai** [comment]
This also happens with:

Brave Version: 1.17.75
Operating System: Arch Linux (Up to date as of 2020-12-26 05:44 UTC)

When Brave is launched with `brave --debug`,  the following is displayed before Brave crashes:

```
/usr/bin/brave: line 29: 25367 Trace/breakpoint trap   (core dumped) /usr/lib/brave/brave $@ $SANDBOX_FLAG $PEPPER_FLASH_FLAG $USER_FLAGS
```
(All prior output is associated with the initial launch of the browser.)

**Comment by iefremov** [comment]
@EstebanJoseSantos please repoen if you still encounter this. The crashdump entry is dead by now, so we can't do anything atm
