### ISSUE TITLE
pre-roll ads not blocked on breitbart videos

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1318]
## Description 
Pre-roll ads are not being blocked on videos in breitbart articles. 

## Steps to Reproduce

   1. Clean profile, navigate to breitbart.
   2. Open a page with a video.
   3. Using default shields, attempt to view video. 

## Actual result:
Pre-roll ad observed. Changing FP to Block All does not change this.

## Expected result:
No pre-roll ad.

## Reproduces how often: 
easily

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

### Reproducible on current release:
pre-roll ad on video not observed on `0.24.0`

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Found while testing https://github.com/brave/brave-browser/issues/1111 
Issue is similar to https://github.com/brave/brave-browser/issues/1145 for pre-roll ads on YT videos.

cc @brave/legacy_qa  for verification on other platforms

**Comment by kjozwiak** [comment]
> cc @brave/legacy_qa for verification on other platforms

Managed to reproduce on all three platforms as well. It doesn't always happen, but the pre-roll ads are appearing often enough. Enabling `Block all Cookies` and `Block All Fingerprints` doesn't resolve the issue either.

* macOS 10.13.6 x64 - **Reproduced**
* Win 10 x64 - **Reproduced**
* Ubuntu 18.04 x64 - **Reproduced**

Example of the pre-roll ads:

<img width="701" alt="screen shot 2018-10-03 at 8 50 49 pm" src="https://user-images.githubusercontent.com/2602313/46447304-fd8c3180-c74e-11e8-8312-c8183045458a.png">

Used the following build:

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

**Comment by rebron** [comment]
@LaurenWags can you recheck if this is still an issue.

**Comment by LaurenWags** [comment]
@rebron yes, still occurs for me with 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

**Comment by kjozwiak** [comment]
Still reproducible under `Win 10 x64` as using the following build:

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

<img width="674" alt="screen shot 2018-10-16 at 5 44 58 pm" src="https://user-images.githubusercontent.com/2602313/47049456-5aceac80-d16b-11e8-99c7-77203ae9f7a3.png">

**Comment by ryanbr** [comment]
@LaurenWags  Should be resolved, can you re-check?

**Comment by LaurenWags** [comment]
@ryanbr appears fixed for me using below build

```
Brave | 1.17.55 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)
```

**Comment by ryanbr** [comment]
Cheers for confirming @LaurenWags
