### ISSUE TITLE
Multiple users reporting that HBO Max is broken, likely due to kVideoPlaybackQuality being disabled

### ISSUE THREAD

**Issue by nicolasff** [brave/brave-browser#13183]
## Description 
[HBO Max](https://hbomax.com/) no longer plays video. Several users are reporting hitting this issue [on Reddit](https://www.reddit.com/r/brave_browser/comments/kbzfp3/hbo_max_not_working_all_of_a_sudden/) as well as on [Brave forums](https://community.brave.com/t/hbomax-not-working-suddenly/187323/4).

## Steps to Reproduce

1. Log in to [HBO Max](https://hbomax.com/) on Brave 1.19.54
2. The page asks "Who is watching?". Click on a user name.
3. The web app loads, lists content to watch. Click on any title.
4. Select any episode of any series/film and click on the play button.
5. The page loads the video viewer with a loading indicator and gets stuck there. An error is logged in the console:
```
app.js:229 Uncaught (in promise) TypeError: this._htmlVideoElement.getVideoPlaybackQuality is not a function
    at i.<anonymous> (app.js:229)
    at app.js:229
    at Object.next (app.js:229)
    at app.js:229
    at new Promise (<anonymous>)
    at uo (app.js:229)
    at i.getState (app.js:229)
    at l.<anonymous> (app.js:225)
    at app.js:229
    at Object.next (app.js:229)
    at app.js:229
    at new Promise (<anonymous>)
    at uo (app.js:229)
    at l._onPlayerTimerUpdate (app.js:225)
    at i._onTick (app.js:225)
    at i.<anonymous> (app.js:222)
```
 

## Actual result:
The video never starts playing.

## Expected result:
Entertaining content.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Reproduced on Version 1.19.54 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)

## Version/Channel Information:

I've only tried the beta channel but I suspect this reproduces everywhere. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

## Miscellaneous Information:

https://github.com/brave/brave-browser/issues/8029 seems to show that `getVideoPlaybackQuality` was removed from Brave back in February as a follow-up to Chromium 80 being released. From what I am reading of the stack traced logged on the HBO Max page, it seems like their web app may have started using this API without checking if it's available. If this is indeed the issue it probably also means that users of Chrome < 80 who haven't upgraded since February would also be seeing this issue.

The removal in Brave was hardcoded so there is no easy way for me to try turning this feature back on.

/cc @fmarier and @mkarolin who created or are mentioned on the original Brave issue.

**Comment by ryanbr** [comment]
I can confirm, hbomax isn't working in Release, Beta or Nightly.

**Comment by nicolasff** [comment]
Here is a Tampermonkey script to re-add the missing function on `<video>` elements: https://gist.github.com/nicolasff/aab6141fde8c93ef2914e6200a9aece3.

HBO Max plays fine with it enabled.

It's pretty hacky because the page is constructed dynamically so I had to use the `MutationObserver` API to track when the `<video>` element was being injected, and then I attached a stubbed `getVideoPlaybackQuality` function on it.

It seems like the complete removal of a feature now supported by all browsers is likely to cause websites to break. Fingerprinting can be prevented by returning dummy values instead. In this particular case I would expect the number of dropped frames to be a way to track certain users. Brave could return 0 in all cases here, but of course that's a more involved change than just removing the feature entirely.

I hope Brave developers will consider replacing functions that could lead to fingerprinting with versions that return constant values, or random ones whenever appropriate. This would seem like a better way to do this than their blunt removal. Then again I'm not a browser developer, but hey. Please just think about it.

**Comment by rebron** [comment]
cc: @pes10k

**Comment by pes10k** [comment]
@fmarier can you say more about why this was removed?

**Comment by fmarier** [comment]
We should re-enable. It sounds like a potential fingerprinting vector, but if it leads to breakage, we should figure out a better way to mess with the fingerprint.

**Comment by pes10k** [comment]
I agree we should re-enable, but I'm curious about the fingerprinting vector. Whats the threat / concern here?

**Comment by bsclifton** [comment]
Created https://github.com/brave/brave-core/pull/7437 to re-enable

**Comment by mkarolin** [comment]
The feature can be re-enabled from the command line (`--enable-features=VideoPlaybackQuality`) for testing.

**Comment by bsclifton** [comment]
Thanks for sharing @mkarolin 😄 @ryanbr will give that a go soon and verify if that fixes. If so, we can accept https://github.com/brave/brave-core/pull/7437

**Comment by ryanbr** [comment]
Just tested HBO Max with `--enable-features=VideoPlaybackQuality`  can confirm video playback is working

**Comment by macp92** [comment]
> Just tested HBO Max with `--enable-features=VideoPlaybackQuality` can confirm video playback is working

How do you do this?

**Comment by nicolasff** [comment]
@macp92 [This Brave support article](https://support.brave.com/hc/en-us/articles/360044860011-How-Do-I-Use-Command-Line-Flags-in-Brave-) explains how to run Brave with custom command-line parameters.

**Comment by paulcpederson** [comment]
for mac folks you can enable this flag with:

```
open -na "Brave Browser" --args "--enable-features=VideoPlaybackQuality"
```

**Comment by ryanbr** [comment]
Confirmed 1.18.77rc works with HBO Max, tested before (1.18.75) and after (1.18.77). Playback now works

**Comment by kjozwiak** [comment]
Thanks @ryanbr 👍 Labeling this as passed as per https://github.com/brave/brave-browser/issues/13183#issuecomment-751881340. Unfortunately QA doesn't have an HBO account but the above was checked on `Windows` which is our biggest platform. Should be good enough for a verificaiton.

@LaurenWags @rebron we don't need to check `macOS` unless one of you has a HBO account.

**Comment by ryanbr** [comment]
Checked on MacOS also, Playback of the new release now works

**Comment by mattts1** [comment]
This issue has popped back up in 1.19.86.
