### ISSUE TITLE
both "Terms of Services" or "Privacy Policy" hard to tap via RE opt-in onboarding

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13198]
## Description 

It's very difficult to tap on either `Terms of Services` or `Privacy Policy`. You basically need to tap a bit above the text to get it to open. However, when you do manage to get it opened, it takes a few seconds to finally load. It should be a lot smoother/faster.

## Steps to reproduce 

   1. launch a version of brave that has the new RE opt-in onboarding (used `1.18.72 CR: 87.0.4280.101` in this case)
   2. tap on the rewards panel (should get the RE op-in onboarding modals)
   3. attempt to tap on `Terms of Services` or `Privacy Policy`

## Actual result 

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/102179247-d07e5200-3e74-11eb-9065-4168cf234702.jpg" width=300>
</p>

## Expected result

Should be a lot easier to tap on both of the `Terms of Services` or `Privacy Policy`

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No, currently on 1.17.x and this change is on 1.18.x)
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy S10+` (Phone)
   - Android version: `Android 10`
   
## Brave version

* `1.18.72 CR: 87.0.4280.101`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @deeppandya @bsclifton @anthonypkeane @codybanxs @LaurenWags @GeetaSarvadnya @btlechowski

**Comment by deeppandya** [comment]
@codybanxs @karenkliu @jamesmudgett what would be the suggested change here ?

**Comment by karenkliu** [comment]
Let's increase the line height and the make tap area larger for both links

**Comment by karenkliu** [comment]
Regarding load time - is there a way to load this in the background once the Rewards panel is open so that tapping it will show the content more quickly?

**Comment by deeppandya** [comment]
@karenkliu we open links in custom tab. so i don't think there is a way to preload the link.

**Comment by deeppandya** [comment]
@kjozwiak would it possible for you to verify it ? i updated it in https://github.com/brave/brave-core/pull/7580 but it didn't close the PR.

**Comment by codybanxs** [comment]
@deeppandya @kjozwiak I went ahead and tested it on Beta and looks like the line height was increased and links were easily tappable.

**Comment by kjozwiak** [comment]
> @kjozwiak would it possible for you to verify it ? i updated it in [brave/brave-core#7580](https://github.com/brave/brave-core/pull/7580) but it didn't close the PR.

Quickly checked using `1.25.73 Chromium: 91.0.4472.106`. I was able to tap and open `Terms of Services` & `Privacy Policy` pretty easily compared to before.
