### ISSUE TITLE
[Android] "Welcome to Brave Rewards" / ETA UI not shown on second app launch

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13195]
## Description 
After you start using Brave Rewards when you launch the app a second time and open the panel, you should see the "Welcome to Brave Rewards" UI with a message indicating the ETA of your first Ads payment. This UI is not showing.

See figma doc: https://www.figma.com/file/0dbMYs8Wp8W3RgrG1yTdki/RE-1.0?node-id=1555%3A0

## Steps to reproduce 

1. Clean install
1. Open panel, tap "Start using Brave Rewards"
1. Skip to end of onboarding tour, tap done
1. See below UI.
1. Don't "x" out of this.
1. Close panel.
1. Remove app from background memory.
1. Relaunch app.
1. Tap on panel.
--> do not see below UI as I was expecting per figma

## Actual result 
Normal panel is shown

## Expected result
<img width="473" alt="Screen Shot 2020-12-14 at 5 43 30 PM" src="https://user-images.githubusercontent.com/28145373/102149301-1b2fa800-3e3c-11eb-9883-d1ffdc141999.png">

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? yes 1.18.x
- Can you reproduce this issue with the current Play Store Nightly version? yes 1.20.28

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.18.72

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @codybanxs @deeppandya @brave/legacy_qa

**Comment by LaurenWags** [comment]
This functionality was working in 1.20.23 Nightly and no longer works in 1.20.28 Nightly cc @deeppandya

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/7447 was merged into `1.18.x` via https://github.com/brave/brave-core/pull/7438.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `Bravearm 1.18.73`
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/102298845-e9bbf700-3f77-11eb-950b-0dea9d637855.png)
