### ISSUE TITLE
Clickable sponsored image to advert. URL

### ISSUE THREAD

**Issue by codybanxs** [brave/brave-browser#13190]
## Description 
Allow users to click directly on the sponsored image to the advertisers URL. 

## Steps to Reproduce

   1. Sponsored image is displayed
   2. User clicks on the image itself
   3. Redirected to advertisers URL

## Brave version (brave://version info)
1.20.28 Chromium: 88.0.4315.5

<img width="1212" alt="Screen Shot 2020-12-14 at 11 59 02 AM" src="https://user-images.githubusercontent.com/61210652/102129160-c96b2b80-3e03-11eb-8b0c-5309bdd1ffd2.png">

**Comment by bradleyrichter** [comment]
Additional detail: Any click on the area of a widget (topsites, clock, widget cards, etc) will be received by the widget. Only the remaining area in NTP would click through to the URL of the advertiser.

**Comment by lukemulks** [comment]
Do we have a target release version for this item? Would it be possible for us to set one?

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (64-bit)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | Windows 10 OS Version 2009 (Build 21376.1)

Confirmed:

1. cursor-pointer changes to hand when hovered/resting over/on the sponsored image
2. the sponsored-image URL is displayed on the bottom left of the browser chrome when the hand pointer is active
2. clicking when in the above state loads the promoted URL in the current tab/window
3. widgets (Brave stats, site favorites/frequently used, Brave Rewards, Brave Together, crypto cards, clock, and all bottom links and icons) work, when clicked
4. Brave Today scrolling still works, regardless of pointer position & state (pointer vs hand) on the tab
5. context-clicking the image while in hand-pointer state copies the URL to the clipboard
6. all tab-opening options (`Open link in...` `new tab`, `new window`, `private window`, and `private window with Tor` work as expected
7. hovering over the sponsored-image attribution dynamically shows an open-page icon which loads the URL in the current tab, when clicked
8. a tooltip/titletip is shown with a call to action to visit the page, specifying the destination URL (top-level)

![sushi](https://user-images.githubusercontent.com/387249/118193540-b8e3cf00-b3fc-11eb-8955-1b1d04a911bd.png)

**Comment by kjozwiak** [comment]
Removing `release-notes/include` as this was reverted via https://github.com/brave/brave-browser/issues/16351.
