### ISSUE TITLE
Refresh Brave News feeds after customizations

### ISSUE THREAD

**Issue by FutureLearnSole** [brave/brave-browser#13196]
## Description 
Suggestion to refresh Browser Tab after clicked 'X' Customize Dashboard 

## Steps to Reproduce

   1. New Tab
   2. Customize, Customize, Customize e.g **Brave Today**
   3. Click 'X' Customize Dashboard Feature Body
   4. Immediate Scroll w/o Tab refresh
   5. _Psyduck?_

## Expected result:
The ungrateful punks of 2020 expects modified feed to kick in right away...

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave		1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
Revision	9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS		Windows 10 OS Version 2004 (Build 19041.685)

## Version/Channel Information:
- Reproduced on current release only,

**Comment by FutureLearnSole** [comment]
https://github.com/brave/brave-core/pull/6192

**Comment by mattmcalister** [comment]
@srirambv or @stephendonner can you confirm this was resolved?

**Comment by srirambv** [comment]
This is working now. 

https://user-images.githubusercontent.com/17010094/157243951-b9941b03-2867-4908-a9a7-852b40d75786.mov
