### ISSUE TITLE
NTP is causing higher CPU / GPU usage

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#13194]
## Description 

Multiple reports from users that the New Tab Page is causing persistently higher CPU usage either in
- The Tab's process
- The Browser's GPU process
- (macOS) WindowServer process

This seems to be as a result of introducing Brave Today and more specifically the "hint" arrow pointing down to scroll, since turning the feature off immediately removes the extra CPU usage.

## Steps to Reproduce

on macOS
   1. Open NTP
   2. Enable Brave Today if not enabled
   3. Open Brave's Task Manager

## Actual result:

High CPU (relative to normal, percentage is different for everyone, depending on hardware)

## Expected result:
Same CPU usage as without Brave Today enabled.

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.18.70

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by FutureLearnSole** [comment]
Ungrateful Brave End User 2020 here, just saying that if not for that scroll down arrow, NF given. Ciao.

Paying last respects to its jiggly,

**Comment by FutureLearnSole** [comment]
https://github.com/brave/brave-browser/issues/13196#issuecomment-745022646

**Comment by LaurenWags** [comment]
Verified passed on macOS using

```
Brave | 1.18.74 Chromium: 87.0.4280.101 (Official Build) (x86_64)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 10.15.7 (Build 19H15)
```

* ensured that the "arrow down" animation was removed from NTP
* ensured that scrolling through Brave Today works without any issues
* ensured that there's an improvement in performance once the animation was removed

**`With Animation using 1.18.70`** | **`Without Animation using 1.18.74`**
------------------------|---------------------------
<img width="497" alt="1 18 70 BT enabled" src="https://user-images.githubusercontent.com/28145373/102490311-a7a8b900-403c-11eb-80a6-0832836c68c7.png"> | <img width="495" alt="1 18 74 BT enabled" src="https://user-images.githubusercontent.com/28145373/102490322-abd4d680-403c-11eb-902d-dd5409a37482.png">
