### ISSUE TITLE
Rewards popup doesn't show translated strings

### ISSUE THREAD

**Issue by cniweb** [brave/brave-browser#13199]
## Description 
Rewards extension popup doesn't display translated strings.

## Steps to Reproduce

   1.  Open rewards popup

## Actual result:
Below is the result with german locale:
<img width="375" alt="Bildschirmfoto 2020-12-15 um 08 52 25" src="https://user-images.githubusercontent.com/2334906/102186792-6f29a380-3eb3-11eb-9513-2941eeca7245.png">

## Expected result:
German strings

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.18.70 Chromium: 87.0.4280.101 (Offizieller Build) (x86_64)
Überarbeitung | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
Betriebssystem | macOS Version 11.0.1 (Build 20B50)
User-Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36
Pfad zur ausführbaren Datei | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

**Comment by mkarolin** [comment]
Thank you for filing the issue @cniweb. If you have a moment to check, is there a folder with your locale under `/Applications/Brave\ Browser.app/Contents/Frameworks/Brave\ Browser\ Framework.framework/Versions/87.1.18.70/Resources/brave_rewards/_locales/`, and if so, does it contain a `messages.json` file?

**Comment by Brave-Matt** [comment]
Users on Community are reporting this same behavior:
https://community.brave.com/t/i18n-appearing-everywhere-in-my-wallet-reward-tab-really-wierd-please-help/187734/8

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.77 Chromium: 87.0.4280.101 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
Betriebssystem | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the STR from the description
Settings page:
![image](https://user-images.githubusercontent.com/38657976/103218808-1db4f600-4942-11eb-95ab-aee7beb0892f.png)
![image](https://user-images.githubusercontent.com/38657976/103218907-51901b80-4942-11eb-8095-2fc77a09fd2a.png)


BR panel:
![image](https://user-images.githubusercontent.com/38657976/103218829-29a0b800-4942-11eb-84b7-5299e9cc45a8.png)
![image](https://user-images.githubusercontent.com/38657976/103218886-4806b380-4942-11eb-875b-4b852d42653f.png)

**Comment by cniweb** [comment]
Thanks 👍
