### ISSUE TITLE
Update Photographer Credit Link for Zane Lee

### ISSUE THREAD

**Issue by okidokiokami** [brave/brave-browser#13207]
## Description 

One of our photographer links is broken (he changed his username on Unsplash)

## Steps to Reproduce

   1. Open NTPs until you find the succulent image
   2. Click on photographer's name (Zane Lee)

## Actual result:

404 page

## Expected result:
Open's an actual link to photographer's portfolio.
`https://unsplash.com/@zane404`

## Reproduces how often: 

Always

## Brave version (brave://version info)

Nightly & Beta

## Version/Channel Information:

- Can you reproduce this issue with the current release? No - photos not rolled out yet
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Please update Zane Lee's photographer credit link to `https://unsplash.com/@zane404` (He took a 0 out of his username)

**Comment by LaurenWags** [comment]
cc @rebron

**Comment by rebron** [comment]
cc: @petemill Can you take a look?

**Comment by LaurenWags** [comment]
@rebron do we want this as part of 1.19.x with the new tab page images?

**Comment by kjozwiak** [comment]
> @rebron do we want this fixed as part of 1.19.x with the new tab page images?

Probably a good idea as we'll be going through https://github.com/brave/brave-browser/issues/12508 and can quickly check if the above was fixed as well 👍 @rebron do we have resources to get this fixed quickly for `1.19.x`?

**Comment by simonhong** [comment]
Pushed PR(https://github.com/brave/brave-core/pull/7522) for this.
PR just set brave community link as a credit link. let me know it's ok. cc @rebron

**Comment by kjozwiak** [comment]
@simonhong proper link should be `https://unsplash.com/@zane404` as per https://github.com/brave/brave-browser/issues/13207#issue-768191073. Looks like you've created https://github.com/brave/brave-core/pull/7528.

I'm going to deny https://github.com/brave/brave-core/pull/7527 and wait till we get an uplift for https://github.com/brave/brave-core/pull/7528 which uses the correct link 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.78 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)


```
- Ensured that the image shown in the NTP matched with the Gdrive image
![image](https://user-images.githubusercontent.com/38657976/103901921-cf60dd80-511f-11eb-9108-bc39bb17a256.png)

- Ensured that clicking on the credit opens the website https://unsplash.com/@zane404
![image](https://user-images.githubusercontent.com/38657976/103901692-78f39f00-511f-11eb-98c6-862ac333642e.png)
