### ISSUE TITLE
[Android] rewards onboarding UI shown on chrome://rewards page on x86 devices

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13202]
## Description 
On x86 devices chrome://rewards page does not resolve as we don't support rewards on x86 devices. However, on 1.18.72 if you manually navigate to this page you can get the onboarding UI and join Rewards thru it. You won't be able to see the rewards page UI however you will get ads and not be able to turn them off. 

A second scenario was added below, if you install 1.18.x and then open it 4 days later, the rewards panel shows but shouldn't since Rewards aren't' supported with x86. 

## Steps to reproduce 

Scenario 1:
   1. Clean install 1.18.72
   2. Navigate to chrome://rewards

## Actual result 
See onboarding UI, able to join rewards thru it
![Screenshot_20201215-103008](https://user-images.githubusercontent.com/28145373/102236907-0d246a80-3ec2-11eb-8094-f6ca9d72043b.jpg)

## Expected result
same as 1.17.x, page should not resolve
![Screenshot_20201215-103021](https://user-images.githubusercontent.com/28145373/102236917-101f5b00-3ec2-11eb-8858-7f2b505f230b.jpg)

Scenario 2:
   1. Clean install 1.18.72
   2. Launch app, then close and remove from memory
   3. Advance date on your device by 4 days
   4. Relaunch app
   5. Panel is open but shouldn't be since it's not accessible on x86 due to no support for rewards

## Actual result 
panel opens on launch:

## Expected result
panel should not open
![Screenshot_20201219-132858](https://user-images.githubusercontent.com/28145373/102256703-b165db80-3ed9-11eb-84cb-7ceccdb95e80.jpg)

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version?  yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): x86
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information

cc @deeppandya @bsclifton @anthonypkeane

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/7439 was merged into `1.18.x` via https://github.com/brave/brave-core/pull/7445.

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.18.73 Bravex86.apk
- Verified scenario 1 from STR. Confirmed onboarding is not displayed on chrome://rewards page
- Verified scenario 2 from STR. Confirmed when launching the app 4 days after install the rewards panel is not displayed on launch.
![rewardspage](https://user-images.githubusercontent.com/28145373/102349789-e1f95400-3f71-11eb-9392-fcc2977238d2.png)
