### ISSUE TITLE
cr88 followup: Brave toolbar buttons (Bookmark, Speedreader) don't work.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#13203]
STR:

1. Start Brave Nightly (1.20.XX).
2. Navigate to a site (e.g. cnn.com)
3. Click Bookmark button on the toolbar

Expected result:
Bookmark bubble shows

Actual result:
Nothing happens.

Same with the speed reader button.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.1 x64` using the following build:

```
Brave | 1.19.83 Chromium: 88.0.4324.79 (Official Build) (x86_64)
--- | ---
Revision | bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS | macOS Version 11.1 (Build 20C69)
```

**`Bookmarks via Toolbar`**

* Verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/13203#issue-767827792

**`Bookmark Toolbar URL`** | **`Bookmark Modal`** | 
-------------------------------|------------------------------------
<img width="502" alt="Screen Shot 2021-01-14 at 12 33 18 AM" src="https://user-images.githubusercontent.com/2602313/104550879-c0889800-5603-11eb-9124-f8fa0a1770e0.png"> | <img width="1212" alt="Screen Shot 2021-01-14 at 12 33 34 AM" src="https://user-images.githubusercontent.com/2602313/104550894-cc745a00-5603-11eb-8393-42f936b7b920.png">

**`Speedreader via Toolbar`**

* enabled `speedreader` via `brave://flags/#brave-speedreader`
* ensured that clicking on it enabled the feature without any issues
* visited https://www.bloomberg.com and selected an article
* ensured that the article was loaded in reader mode

Example:

<img width="1658" alt="Screen Shot 2021-01-14 at 12 41 01 AM" src="https://user-images.githubusercontent.com/2602313/104551054-1eb57b00-5604-11eb-9f2c-84b47f21560b.png">
