### ISSUE TITLE
Shields icon turns gray and stops working

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#13204]
## Description 

Shield icon goes gray after a  days use of Brave browser (continious use without closing) and stopps working (opening)

Unable to open shields icon once it goes gray, it's dead

## Steps to Reproduce

   1. Use brave browser for a full day without closing it
   2. Check shields icon opens as normal over that period

## Actual result:

![image](https://user-images.githubusercontent.com/75579566/102259508-197ee680-3f07-11eb-9112-da7fbfed4845.png)

## Reproduces how often: 

Happens after a days use, many hours later 

## Brave version (brave://version info)

Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)

Linux Cinnamon desktop environment 5.4 kernel

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by exapsy** [comment]
Same, I disabled all extensions and it's still gray. When I click on it, it's like its stuck on the "onclick" background, as a gray background is stuck behind.
![image](https://user-images.githubusercontent.com/9019120/104465153-69130980-55bc-11eb-8d61-4207e93a2ffd.png)

Brave Version - Version 1.18.77 Chromium: 87.0.4280.101 (Official Build) unknown (64-bit)
5.10.2-2-MANJARO

**Comment by bsclifton** [comment]
Closing as there isn't enough information here to reproduce the issue

@exapsy if you have steps which we can follow to reproduce, please share here and I can reopen the issue 😄

**Comment by exapsy** [comment]
> Closing as there isn't enough information here to reproduce the issue
> 
> @exapsy if you have steps which we can follow to reproduce, please share here and I can reopen the issue 😄 

Thanks for responding! 😁 The bug from my part was fixed after a restart (I don't restart much 😅). So, it must be a little bit difficult to reproduce I suppose.
