### ISSUE TITLE
[Android] Remove "Hide Brave Rewards Icon" setting from x86

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13201]
## Description 
Android x86 devices do not support Brave Rewards so the setting "Hide Brave Rewards Icon" should not be available on x86 devices. 

Setting was not in 1.17.75 but is available with 1.18.72.

## Steps to reproduce 

   1. Clean install 1.18.72
   2. Tap on 3 dots menu, select Settings
   3. Under Display, tap Appearance

## Actual result 
See `Hide Brave Rewards Icon` setting:
![1 18 x](https://user-images.githubusercontent.com/28145373/102226172-1576a880-3eb6-11eb-8bbc-954413257172.png)

## Expected result
The `Hide Brave Rewards Icon` setting should not be available like in 1.17.75:
![1 17 x](https://user-images.githubusercontent.com/28145373/102226180-18719900-3eb6-11eb-93eb-b032c33903ee.png)

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? no
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): x86
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.18.72

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information

cc @deeppandya @anthonypkeane @bsclifton

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/7439 was merged into `1.18.x` via https://github.com/brave/brave-core/pull/7445.

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.18.73 Bravex86.apk
- Verified STR from description, confirmed `Hide Brave Rewards Icon` setting is not visible on x86 device.

![setting](https://user-images.githubusercontent.com/28145373/102349285-1a4c6280-3f71-11eb-844a-9b692cdb79ec.png)
