### ISSUE TITLE
Brave Freezes The Whole OS

### ISSUE THREAD

**Issue by GCS7** [brave/brave-browser#13214]
## Description 

The issue randomly happens when I use Brave (Mostly after ~15 min. of usage). My mouse can still move but nothing else works. When I try to kill brave from terminal it doesn't work and I need to restart my PC to make it usable again.

## Steps to Reproduce

   1. Open Brave and start using it.
   2. After some time OS will freeze
   

## Actual result:

OS (Manjaro) becomes unusable.

## Expected result:
Keep using the browser normally, in a stable way.

## Reproduces how often: 

Approx. after 15 minutes of usage.

## Brave version (info found on brave://version)

1.16.67 Chromium: 86.0.4240.111 (Official Build)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No 
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I had the same issue a month ago and after I re-installed Brave it appeared to be fixed, but now it started again.

**Comment by resynth1943** [comment]
I used to have this, too. Have you tried hopping between TTY 1 and 3? That normally unfreezes things for me, after a few minutes.

**Comment by bhavik2936** [comment]
Can you please give information about your RAM size and its usage over brave.

Also check for any heavy RAM usage script running during web surfing.

**Comment by GCS7** [comment]
Thank you for your replies. I distro-hopped because of some multiple issues with Manjaro and now I am using Kubuntu. Brave is now working properly. 
Btw I had 8 GB ram and Brave's ram usage was normal, ~2 GB.

**Comment by rebron** [comment]
@GCS7 Are we ok to close this one?

**Comment by GCS7** [comment]
> @GCS7 Are we ok to close this one?

Yes, again thank you for the replies.

**Comment by rebron** [comment]
Closing.
