### ISSUE TITLE
Ads per hour frequency cap incorrectly limits based on adsPerHour not adsPerDay

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#13215]
## Description 

ads frequency cap per hour is using the ads per hour value (5) instead of the ads per day value (20). This bug might result in under delivery of ads.

## Steps to Reproduce

   1. change ads per day in the UI to 2
   2. view more than 2 ads in a given day
   3. try and trigger an ad in the 2nd hour

## Actual result:

ad notification is not delivered due to an incorrect cap which is using ads per hour UI setting

## Expected result:
ad notification should be delivered up to the correct cap of 20

## Reproduces how often: 

easily reproduced

## Brave version (info found on brave://version)

introduced in 1.18.x

## Version/Channel Information:

Nightly, Beta and Release

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.74 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the STR from the description
Set `Maximum number of ads displayed` to `2` in ads panel.
- Ensured that 1st AD is received immediately, waited for 30 mins and ensured the second AD is received, waited for another 30 mins and ensured 3rd AD is received in the second hour.

Ads panel | History
-- | --
![image](https://user-images.githubusercontent.com/38657976/102492262-6f829400-4097-11eb-970e-983b1f99b6aa.png) | ![image](https://user-images.githubusercontent.com/38657976/102492295-7ad5bf80-4097-11eb-8413-d1434980b8a4.png)

**Comment by andrewmclagan** [comment]
i mean... id be happy if this remained unresolved.



:-)
