### ISSUE TITLE
Allow devs to see component extensions in chrome://extensions

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#1321]
By default, component extensions are not shown in chrome://extensions.
It might be useful to have an option for developers to enable this for debugging component extensions.

**Comment by kjozwiak** [comment]
@yrliou is this related to `--show-component-extension-options` or is this strictly for builds from source?

**Comment by yrliou** [comment]
@kjozwiak This enables dev to pass this arg for `npm start`, which would actually mapped to --show-component-extension-options command line switch.
We're able to specify --show-component-extension-options when running the executable from command line with or without this PR.

**Comment by kjozwiak** [comment]
Gotcha, thanks @yrliou 👍
