### ISSUE TITLE
Brave tips icon still showing up on Reddit & Twitter web

### ISSUE THREAD

**Issue by snowbound** [brave/brave-browser#13223]
## Description 
Brave Tip icon still showing up on Reddit & Twitter web UI even after disabling

## Steps to Reproduce

   1. Under TIPS under brave://rewards/ clicked on the 3 horz lines in upper right corner and all 3 options were unchecked
   2. 
   3. 

## Actual result:
Brave triangle tips icon still shows up

## Expected result:
There should be no Brave triangle tip icons on Twitter, Reddit etc

## Desktop Brave version:
Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?  no idea
- Can you reproduce this issue with the nightly channel? no idea

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? REwards is disabled 
- Is the issue reproducible on the latest version of Chrome?  NO

**Comment by resynth1943** [comment]
Related: https://github.com/brave/brave-browser/issues/13222

**Comment by snowbound** [comment]
Can someone remove the OS/Android tag as it's an error.

**Comment by emerick** [comment]
@snowbound On the 20H2 system, can you re-confirm that all of the tipping options are disabled, close Brave, verify that there are no other running Brave processes (rebooting the system might be safest here, if possible), and then check if you still see the tipping buttons?

**Comment by snowbound** [comment]
I have done that and for NOW it is behaving itself. I thought it was disabled before but the tip icons were showing up after a short while.

**Comment by rebron** [comment]
@snowbound Based on the last comment I'm going to go ahead and close this one out. Please reopen if you're still running into this one.

**Comment by pmalerts** [comment]
This is still a problem. Win10 latest.

**Comment by eka** [comment]
Same here

**Comment by bsclifton** [comment]
@pmalerts @eka have you tried closing/re-opening Brave after disabling tips? That should fix things up
