### ISSUE TITLE
Wallet verification on Desktop and Android should parity one another

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#13220]
## Description
_Note: This issue was carried over from [internal support repo](https://github.com/brave/bat-support/issues/70), as requested by @marshall._

“Verify wallet” flow is inconsistent between Android and desktop, and messaging/UX regarding the 25 BAT minimum can be improved. Below is a description of the current flow when pressing “verify wallet”:

**Desktop flow:**
- If the user **has a verified/KYCd Uphold account already**, they only can simply go to `Verify wallet --> Login` and log into their Uphold account using standard Uphold flow, and then the wallet will be verified.
- If the user **has not yet created an uphold account/has not verified/KYCd it**, they can no longer access this flow from the browser without the 25BAT minimum requirement. 
   - However, if that user simply creates and verifies an Uphold account first, they can return to `Verify wallet` and login to their Uphold account _without_ meeting that 25BAT requirement. 

**Android flow:**
If a user, _with or without a verified Uphold account_:
- Taps `verify wallet` option in Brave Rewards panel -- if they **do not have 25BAT minimum** in their browser wallet, they will receive a notification that 25BAT is required in order to verify/link their Android wallet with Uphold.
- Taps `verify wallet` option in Brave Rewards panel -- if they **have** 25BAT minimum requirement, they are then taken to the Uphold signup/login flow.

Android users have a rigid restriction to wallet verification (**must have 25 BAT**) whereas Desktop users see more of a "suggestion" rather than facing a real restriction. This discrepancy can be confusing to users, especially now that Desktop users also receive “25 BAT minimum” messaging. 

We do not want to impose a strict 25 BAT minimum because some users will want to restore existing Uphold accounts for legitimate reasons (e.g., backup/restore). However, we also do not want to encourage users with less than 25 BAT to sign up with Uphold.

-------
### Proposed changes

**Proposal 1 - Changing messaging on pop-up, and make it consistent on both Desktop and Android platforms**
**Change messaging text to:**

> A 25 BAT minimum is needed to verify this browser wallet with a new Uphold account.
> 
> If you already have a verified Uphold account, use the login option to link it to your wallet.
> 
> Note: Your transactions will be visible to Uphold once you authorize; for instance, they will be able to see the recipient and amount of your tips.
> 

**Change Android notification to match messaging/notification in Desktop and display “Login” option** 

This will, at minimum, keep parity between platforms and also make it more clear that we are referring specifically to users who are new/do not have a current verified Uphold account. Additionally, it would allow Android users to have a reliable way to “backup” their BAT should something happen to their device. 

Both platforms would display the same pop-up/messaging:
![image](https://user-images.githubusercontent.com/3299098/99008106-659acd80-24fa-11eb-9cc5-25f6b0f31d6c.png)

Proposal 2:

1. Move the “login” button to the Backup & Restore area of Brave Rewards settings (and rename the button to “Restore verified wallet (Uphold)”). 
2. Keep 25 BAT minimum messaging.

![image](https://user-images.githubusercontent.com/3299098/99007917-050b9080-24fa-11eb-9f2b-8c324d845fc0.png)

This retains users’ ability to restore an existing Uphold account for backup/restore reasons, while discouraging new users from creating/linking new Uphold accounts if they have less than 25 BAT. This recasts the “login” button as a backup/restore functionality, and keeps the messaging clear.

A combination of both of proposals is another possibility (change messaging text and move UI items as described in proposal 2).

**Comment by Brave-Matt** [comment]
Another good example of this:
https://community.brave.com/t/sinc-desktop-wallet-macbook-and-mobil-wallet-android/190736/2

**Comment by Miyayes** [comment]
Exact report of this issue: +1 https://www.reddit.com/r/brave_browser/comments/kuf6zw/verify_wallet/

**Comment by bsclifton** [comment]
Bigger problem here:
- User may have Uphold created + have lots of BAT
- User can't link account on Desktop / Android unless they have 25 BAT

Root problem (for showing notification) is to avoiding new signs up for people that don't already have an account
@Miyayes should we allow people that have account already to sign in? (not new sign ups unless 25+ BAT)

**Comment by Miyayes** [comment]
I believe this would affect `OS/Android`, since Android is missing the "login" button that already exists on desktop. The solution @Brave-Matt is suggesting is that we add the same "login" button on Android (which currently does not exist on Android) in order to bring Android up to parity with desktop. 

I agree that the login button should also exist on Android, in the same way it exists on desktop.

@jenn-rhim also confirmed on Nov 13, 2020 that the dialog boxes should be the same on both platforms: i.e., that both Android and desktop should have the "login" option as dekstop does. It should look like this (from Jenn): 

![image](https://user-images.githubusercontent.com/11497541/104750631-5dd9ee00-5722-11eb-9839-8c0b0dcbb80c.png)

@bsclifton @SergeyZhukovsky

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/kvbbtx/link_uphold_on_mobile_app/gj89se2

**Comment by Miyayes** [comment]
+1 No ability to backup/restore: https://old.reddit.com/r/BATProject/comments/l3xinc/what_happens_to_bat_if_i_uninstall_brave_apk/

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/l8lrmz/moving_bat_from_my_phone_to_my_desktop_brave/gmtkx8i/?context=3

**Comment by Miyayes** [comment]
+1 https://old.reddit.com/r/BATProject/comments/l8lrmz/moving_bat_from_my_phone_to_my_desktop_brave/gn4wb8g/?context=3

**Comment by Miyayes** [comment]
cc: @brave/android

**Comment by deeppandya** [comment]
> I believe this would affect `OS/Android`, since Android is missing the "login" button that already exists on desktop. The solution @Brave-Matt is suggesting is that we add the same "login" button on Android (which currently does not exist on Android) in order to bring Android up to parity with desktop.
> 
> I agree that the login button should also exist on Android, in the same way it exists on desktop.
> 
> @jenn-rhim also confirmed on Nov 13, 2020 that the dialog boxes should be the same on both platforms: i.e., that both Android and desktop should have the "login" option as desktop does. It should look like this (from Jenn):
> 
> ![image](https://user-images.githubusercontent.com/11497541/104750631-5dd9ee00-5722-11eb-9839-8c0b0dcbb80c.png)
> 
> @bsclifton @SergeyZhukovsky

@jenn-rhim @Miyayes i think i can follow this UI. Do you have any concerns ? what should happen when user clicks on login ?

**Comment by Miyayes** [comment]
"Login" on desktop sends them here (some numbers were redacted). cc: @deeppandya It should send them to the same URL/flow! 

https://uphold.com/authorize/123456788938927112redacted?scope=accounts:read%20accounts:write%20cards:read%20cards:write%20user:read%20transactions:deposit%20transactions:read%20transactions:transfer:application%20transactions:transfer:others&intention=login&state=23412412DFEWREDACTED

**Comment by deeppandya** [comment]
Thanks @Miyayes I will update it.

**Comment by binocry** [comment]
So any news?

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/m5rauq/is_there_no_way_to_connect_my_wallets_on_my_phone/

**Comment by deeppandya** [comment]
> @deeppandya @zenparsing what are the desktop and android test plans for this issue? Adding `QA/Blocked` until we have a test plan for both.
@LaurenWags I am adding the test plan for android.

**Comment by srirambv** [comment]
@deeppandya  can you confirm this is sufficient for Android https://github.com/brave/brave-browser/issues/15196#issuecomment-842069175? If there are any other cases to be verified please mention in the test plan and I will retest #15196

**Comment by LaurenWags** [comment]
cc @zenparsing for desktop test plan. Is desktop testing needed for this issue?

**Comment by LaurenWags** [comment]
@deeppandya did you make any desktop changes? wondering if I can remove the `OS/Desktop` label if no changes were made.

**Comment by deeppandya** [comment]
> @deeppandya did you make any desktop changes? wondering if I can remove the `OS/Desktop` label if no changes were made.
> 

@LaurenWags I haven't updated anything for desktop. I have added login flow for Android only.

**Comment by LaurenWags** [comment]
thanks @deeppandya. Per discussion in the desktop planning mtg (5/18), I'm removing the `OS/Desktop` label then - lmk if you feel differently @zenparsing @rebron @kjozwiak

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.60 x64 Beta Build
- Verified clicking on Verify wallet brings up the new modal
- Verified modal mentions about min 15 BAT
- Verified able to login to Uphold wallet even if there is no/low balance
- Verified able to connect to an existing Uphold wallet account on Android 
- Verified if the balance is more than 15 BAT clicking on verify wallet doesn't bring the new info modal 
---------
Verification passed on Samsung Tab A with Android 10 running 1.25.60 x64 Beta Build
- Verified clicking on Verify wallet brings up the new modal
- Verified modal mentions about min 15 BAT
- Verified able to login to Uphold wallet even if there is no/low balance
- Verified able to connect to an existing Uphold wallet account on Android 
- Verified if the balance is more than 15 BAT clicking on verify wallet doesn't bring the new info modal 
- Logged #15775 for tablet UI

OnePlus 6T  | Samsung Tab A
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/118446019-0f942600-b6e7-11eb-9e1a-e7ec460c5b67.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/118446081-1f136f00-b6e7-11eb-99ab-86b73640dc4d.png>


- Additional scenarios can be found here https://github.com/brave/brave-browser/issues/15055#issuecomment-842117692
