### ISSUE TITLE
Onion addresses spawn new tor private window

### ISSUE THREAD

**Issue by taperj** [brave/brave-browser#13236]
Onion addresses spawn new tor private window even if a proxy that has access to tor is being used in the main window.

## Steps to Reproduce

   1. Set search engine to duckduckgo's .onion address and set as default search engine. 
   2. Search from the address bar.
   3. Brave spawns new private window with Tor instead of using it's current window which is not good behavior.
   4. Users having "normal" proxies that access Tor as a segment from within the "normal" proxy cannot use onion addresses anymore from the browser non-private window (ie. - using a squid proxy that is aware and has a stub to Tor from within).
   5. This, in one step, has rendered the browser fairly useless for customized advanced consolidated privacy.

## Actual result:

New private window with Tor is spawned

## Expected result:

usage of the "normal" squid proxy configured and letting that proxy handle the dns resolutionand routing to .onion(or not).
Brave should not override and spawn a new Tor window solely based on domain extension, it should use the proxy configured.

## Reproduces how often: 

Happens every time.

## Brave version (info found on brave://version)

Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)

problem reproduced on windows and linux, this (bad) behavior has been introduced in the last couple releases I believe.

- Can you reproduce this issue with the current release?
-yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
 No
- Does the issue resolve itself when disabling Brave Rewards?
 No

**Comment by diracdeltas** [comment]
does this happen if you turn off the onion redirect setting in brave://settings/?search=onion?

**Comment by taperj** [comment]
@diracdeltas Thanks for the reply!

> does this happen if you turn off the onion redirect setting in brave://settings/?search=onion?

Yes, it still happens with the onion redirect setting disabled. I've toggled it on and off and it exhibits this same behavior both ways.

**Comment by diracdeltas** [comment]
^ cc @darkdh

**Comment by darkdh** [comment]
that setting is effective for `onion-location` header auto redirect currently, I will make .onion address redirect to check that setting too.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.20.87 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

Reproduced the issue using `1.19.86`.
Verified test plan from https://github.com/brave/brave-core/pull/7517.
Confirmed if "Automatically redirect .onion sites" is off, visiting `https://brave5t5rjjg3s6k.onion/` in a normal window does not open a Tor window.
Confirmed if "Automatically redirect .onion sites" is on, visiting `https://brave5t5rjjg3s6k.onion/` in a normal window does open a Tor window.

------------------
