### ISSUE TITLE
Tie the query filter to Shields status

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#13242]
As suggested in https://github.com/brave/brave-browser/issues/4239#issuecomment-618588628 and https://github.com/brave/brave-browser/issues/4239#issuecomment-747474207, we could tie the query filter to whether or not Shields are enabled on the destination URL.

This would enable web developers to test their trackers without needing another browser, and it would make it possible to add more generic-looking query parameters (e.g. #8975).

**Comment by stephendonner** [comment]
Verified `FIXED` using `beta` and the testplan in https://github.com/brave/brave-core/pull/7968 with 

Brave | 1.22.49 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)


1. Open https://brave.com/?fbclid=1234 in a new tab.
2. Check that the fbclid query parameter is missing from the URL bar.
<img width="1551" alt="Screen Shot 2021-03-02 at 5 00 56 PM" src="https://user-images.githubusercontent.com/387249/109736231-e567a900-7b78-11eb-9732-74428e2d6dd4.png">

3. Turn Shields OFF for brave.com.
4. Open https://brave.com/?fbclid=5678 in a new tab.
5. Check that the fbclid query parameter is present in the URL bar.
<img width="1489" alt="Screen Shot 2021-03-02 at 4 55 21 PM" src="https://user-images.githubusercontent.com/387249/109736011-915cc480-7b78-11eb-9697-43da39ab23ed.png">

6. Turn Shields ON for brave.com.
7. Open https://brave.com/?__s=abcd in a new tab.
8. Check that the __s query parameter is missing from the URL bar.
<img width="1415" alt="Screen Shot 2021-03-02 at 4 54 55 PM" src="https://user-images.githubusercontent.com/387249/109735991-8a35b680-7b78-11eb-8e9a-297704b29f5f.png">
