### ISSUE TITLE
Cookie issues on Wirecutter/NYtimes

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#13241]
## Description 
Comments won't show on `https://www.nytimes.com/wirecutter/gifts/gifts-for-mother-in-law/` in Brave 

## Steps to Reproduce

   1. Open `https://www.nytimes.com/wirecutter/gifts/gifts-for-mother-in-law/`
   2. Scroll down to bottom, expect comments
   3. Shields has no affect
   4. Re-test by opening a new wirecutter tab

## Actual result:
![wirecutter-cookies](https://user-images.githubusercontent.com/1659004/102547198-b7e49500-411d-11eb-9051-447c3df501e2.png)

## Expected result:
Show embedded discuss comments

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
`Allowing all cookies` doesn't affect it, regardless of the message.

Further investigation, clearing the specific cookie `nyt-purr` on load allows the discuss embedded to show.

**Comment by ryanbr** [comment]
Was reported: https://community.brave.com/t/wirecutter-nytimes-comments-are-disabled/187773/8

**Comment by rebron** [comment]
@ryanbr This looks ok to close. Looks good to me on the url provided and on another wirecutter page. 

Brave | 1.20.78 Chromium: 88.0.4324.79 (Official Build) beta (arm64)
-- | --
Revision | bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS | macOS Version 11.1 (Build 20C69)
