### ISSUE TITLE
Shields not showing blocked items for Twitter

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#13265]
## Description 
Brave not showing more blocked items on twitter.com. We're blocking `twitter.com/i/jot` and `twitter.com/1.1/jot/client_event.json` (xml requests) in Easyprivacy, which should show up in Shields.

## Steps to Reproduce

   1. Login into twitter
   2. Scroll down a bit
   3. Check Shields Ads/Trackers

## Actual result:
![image (1)](https://user-images.githubusercontent.com/1659004/102727995-2af44280-438e-11eb-83bf-b97c286d916e.png)

## Expected result:
Expect shields to report we're blocking  `twitter.com/i/jot` and `twitter.com/1.1/jot/client_event.json`

## Brave version (brave://version info)
`Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
We should be blocking `twitter.com/i/jot` and `twitter.com/1.1/jot/client_event.json` (xml requests), and showing up in shields.

Items are blocked in Easyprivacy.

**Comment by ryanbr** [comment]
Was reported: https://www.reddit.com/r/brave_browser/comments/kgr98e/why_is_brave_shield_not_blocking_anything_on/

**Comment by antonok-edm** [comment]
Appears to be related to https://github.com/brave/brave-browser/issues/13781
