### ISSUE TITLE
First click on AD notification will not open AD in a view mode

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13268]
## Description 

First click on AD notification will not open AD in a view mode

## Steps to Reproduce

   1. Clean profile 1.20.x staging environment
   2. Enable rewards
   3. View an AD (I have received `This is a test` untargeted ad for region `IN`)
   4. Click on AD notification to view an AD
   5. AD isn't displayed in VIEW mode
   6. Repeat step 4,  AD isn't displayed in VIEW mode
   7. Repeat step 4, AD is displayed in the view mode
   
**Note**: Please note that this issue is happening only with a few AD's. The same Ad `This is a Test` opens up in view mode in a single click in a rel version `1.18.x`

## Actual result:

The first click on AD notification will not open AD in a view mode

## Expected result:
Click on AD notification should open the AD in a view mode

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.20.40 Chromium: 88.0.4315.5 (Official Build) nightly (64-bit)
-- | --
Revision | d2abe4588adaeb0d66aa0a0106675be1dff12c64-refs/branch-heads/4315@{#11}
OS | Windows 10 OS Version 2004 (Build 19041.685)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? na
- Does the issue resolve itself when disabling Brave Rewards? na
- Is the issue reproducible on the latest version of Chrome? na

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @tmancey

**Comment by tmancey** [comment]
@GeetaSarvadnya Please click on the text and let me know if this fixes the issue

**Comment by GeetaSarvadnya** [comment]
If I click on the text `this is a text` in the AD's notification, ads opens up in view mode in 1st click itself 
Closing the issue as Dup of https://github.com/brave/brave-browser/issues/13137
