### ISSUE TITLE
G..P..S..

### ISSUE THREAD

**Issue by htttito** [brave/brave-browser#13269]
Sorry brave-browser team but:
Brave stands for : **don't invade your privacy**,
and you must download it on G..P..S.., and for synchronise you must activate G..P..S..?
That doesn't go together!
Just my opinion, you can think about it.
PS: For me that's an issue.

**Comment by bsclifton** [comment]
@htttito do you have more information? The browser itself shouldn't be asking for GPS. Some sites (such as maps.google.com, etc) will ask for this

**Comment by bsclifton** [comment]
ah - sorry; you mean Google Play store

I don't think we'll be removing this from Google Play store. Will let @anthonypkeane comment
