### ISSUE TITLE
Add ipfs: and ipns: protocol associations

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#13266]
## Description 
Brave should register with the host OS as a handler for ipfs: and ipns: URIs.

## Steps to Reproduce
   * (On Windows): Press Win+R, type `ipfs://bafkreigcnxudvpojjfwncmauociy5q46zsq46oe66cxbyzie3imabuoege`, and press Enter
   * (On macOS): Open the Terminal, and type `open ipfs://bafkreigcnxudvpojjfwncmauociy5q46zsq46oe66cxbyzie3imabuoege`, and press Enter.
   * (On Linux): Open a shell and type `xdg-open ipfs://bafkreigcnxudvpojjfwncmauociy5q46zsq46oe66cxbyzie3imabuoege`

## Expected result:
Brave should open and display a page with the word “PASS” on it.

## Actual result:
Variations on an error saying no app can open the link.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
87.1.19.62

## Version/Channel Information:
Beta

## Miscellaneous Information:
* On Linux, append `MimeType=x-scheme-handler/ipfs;MimeType=x-scheme-handler/ipns;` to `MimeType=` in the Brave.desktop file.
* On macOS, append `ipfs:` and `ipns:` to the `CFBundleURLSchemes` array in `Info.plist`. 
* On Windows, add the missing schemes through Microsoft’s convoluted registry process.

**Comment by ingokeck** [comment]
Please note that this is not the correct URI syntax. There should not be a '//' in the URI if the resource is just an IPFS hash like in this case. Please see https://github.com/brave/brave-browser/issues/13677 for details.

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` using the steps to reproduce given in the original comment, with:

Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

<img width="1193" alt="Screen Shot 2021-02-22 at 2 17 34 PM" src="https://user-images.githubusercontent.com/387249/108777913-6e4b6880-7519-11eb-84ae-ca27a680f0f8.png">


Note also, as already mentioned, that https://github.com/brave/brave-browser/issues/13677 is open for correcting the URI(s).
