### ISSUE TITLE
Brave browser doesn't open some websites

### ISSUE THREAD

**Issue by foaudkajj** [brave/brave-browser#13261]
## Description 

Brave sometimes doesn't open some websites totally or open them after Emptying cache and hard reload.
For example, I couldn't open the following website https://www.zubizu.com/ . Although it can be opened on chrome. It stucks on the landing page.

## Steps to Reproduce

Open the mentioned website to reproduce the issue.

## Actual result:

The website stucks on the landing page.
![image](https://user-images.githubusercontent.com/9152599/102695240-fe79e280-4236-11eb-8430-052adf741154.png)

## Expected result:
The expected result is to be able to surf the website not stucking on the landing page.

## Version/Channel Information:

![image](https://user-images.githubusercontent.com/9152599/102695188-ca9ebd00-4236-11eb-99db-3cc92896915e.png)

![image](https://user-images.githubusercontent.com/9152599/102695206-d8ecd900-4236-11eb-8cd2-03e2658a6469.png)

**Comment by thefallofbecause** [comment]
You need to allow ads & trackers on zubizu for it to load. The page is badly programmed and is relying on the existence of Google tracking code that is not loaded when Brave blocks Google Analytics.

**Comment by ryanbr** [comment]
Apologies for missing this @thefallofbecause   Have rolled out a fix for this site. Give it 24-48hrs, any questions let me know

https://github.com/easylist/easylist/commit/b3dc53d64c46ccbea869c5434adabdddfad7045f

**Comment by ryanbr** [comment]
@foaudkajj should be fixed, can you confirm?

**Comment by rebron** [comment]
@ryanbr This looks good/fixed, tested on 1.23.71.

**Comment by ryanbr** [comment]
Closing, considered fixed. Any issues related to this, we can reopen

**Comment by foaudkajj** [comment]
Sorry for the late response. Yes, it's working now.
