### ISSUE TITLE
youtube crash after claiming the token grant

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1326]
**IMPORTANT: The current workaround for this issue is to disable Brave Rewards**

## Steps to Reproduce

   1. Clean profile
   2. Enable rewards
   3. Claim the grant
   4. Browser youtube(search/watch videos)

Note: The issue is random but easily reproducible

![1326_fail](https://user-images.githubusercontent.com/34715963/46196027-38810600-c306-11e8-9857-ac6feeb7b873.gif)

For reference here are the steps used in the recording:
   1. Clean profile
   2. Enable rewards
   3. Claim the grant
   4. Open `youtube.com` in new tab
   5. Search for `bart` in youtube search
   6. Click on `bart baker`

## Actual result:

Crash
Crash link: https://stats.brave.com/dashboard#crash/5bad34ae101f57001ebaca68
Crash report ID: 2f99acab89ff4b73 
Local Crash ID: af5c42c4-36db-49fa-93f1-08ccd8bc3287
Crash dmp: [Win10_5bad34ae101f57001ebaca68.zip](https://github.com/brave/brave-browser/files/2427326/Win10_5bad34ae101f57001ebaca68.zip)
Win 10 Crash provided by @srirambv .

[Win7_a215e857-ca96-420e-9531-f34c5cc94849.zip](https://github.com/brave/brave-browser/files/2427325/Win7_a215e857-ca96-420e-9531-f34c5cc94849.zip)
Blocked on uploading crashes on Win7: https://github.com/brave/brave-browser/issues/1188

## Expected result:
No crash

## Reproduces how often: 

easily reproducible, but needs to browser youtube a bit.

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows 7

### Reproducible on current release:

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows 7

Reproduced by @srirambv 

cc @brave/legacy_qa @bbondy

**Comment by NejcZdovc** [comment]
@btlechowski could you please add exact steps, it's not crashing for me with those steps

**Comment by NejcZdovc** [comment]
also is this limited to only windows?

**Comment by NejcZdovc** [comment]
is this limited to youtube or the same things happens when you visit a regular site?

**Comment by srirambv** [comment]
@Miyayes reported issues from community on #1327 
>+3 reproductions of this in the community (Windows).
 >Some users replicated 1326 quite identically.

**Comment by bbondy** [comment]
This needs a local crash ID that was uploaded please.

**Comment by btlechowski** [comment]
@NejcZdovc Unfortunately, there is no reliable STR. It is a random issue, but it is easily reproducible.

I have reported this issue on Windows 7, but @srirambv reproduced on Windows 10. Also community reports that it is happening on Windows.

@LaurenWags @kjozwiak Can you check Mac?
I have checked Ubuntu 17.10 and it does not crash. @srirambv can you check on your linux machine?

@bbondy updated main issue with crash dmps

**Comment by btlechowski** [comment]
Also randomly reproduced on twitch.tv 
Crash dmp:
[Win7_twitch_02d97cdb-456e-4039-b915-39453a40b726.zip](https://github.com/brave/brave-browser/files/2427455/Win7_twitch_02d97cdb-456e-4039-b915-39453a40b726.zip)

Steps to Reproduce
1. Clean profile
2. Enable rewards
3. Claim the grant
4. Go to twitch.tv
5. Play stream on the main page.
![1326_fail2](https://user-images.githubusercontent.com/34715963/46198431-bf38e180-c30c-11e8-834e-7466383ac5f3.gif)

**Comment by srirambv** [comment]
@bbondy local crash id's for the crash
![image](https://user-images.githubusercontent.com/17010094/46209621-4f225f80-c2fc-11e8-81ba-78fa319db1cd.png)

**Comment by kjozwiak** [comment]
> Sorry but in my case Rewards was never enabled yet every time I start Brave up on WIndows7 I get "brave api keys are missing. Some functionality of brave will be disabled" this was a clean install which simply imported my Chrome data in.

This will be resolved by https://github.com/brave/brave-browser/issues/1152

> I then added Chrome store extensions into the browser.

Can you reproduce this reliably with a specific extensions? If you have exact steps to reproduce, we can take a look and see if it's the same crash or something completely different.

**Comment by snowbound** [comment]
If memory serves me the extension adding did not influence the crash it was on that I did a clean install, imported my Chrome data and then added extensions. That is all I did before I saw the "brave api keys are missing. Some functionality of brave will be disabled"

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Windows 7
