### ISSUE TITLE
CR88- Javascript content block is empty in brave://settings/content/javascript

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13271]
## Description 

CR88- Javascript content block is empty in brave://settings/content/javascript

## Steps to Reproduce

   1. Clean profile 1.20.x CR 88
   2. Open brave://settings/content/javascript
   3. There are no `Add` buttons to block and allow sites

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/102793220-9ca0b080-43cf-11eb-8949-f4dc9a56dccf.png)

## Expected result:

![image](https://user-images.githubusercontent.com/38657976/102793301-b4783480-43cf-11eb-9e62-4327b6890438.png)

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.20.40 Chromium: 88.0.4315.5 (Official Build) nightly (64-bit)
-- | --
Revision | d2abe4588adaeb0d66aa0a0106675be1dff12c64-refs/branch-heads/4315@{#11}
OS | Windows 10 OS Version 2004 (Build 19041.685)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.1 x64` using the following build:

```
Brave | 1.19.83 Chromium: 88.0.4324.79 (Official Build) (x86_64)
--- | ---
Revision | bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS | macOS Version 11.1 (Build 20C69)
```

* Verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/13271#issue-772257244
* Verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/7571#issuecomment-759728854
* ensured that upgrading from `1.18.78 CR: 87.0.4280.141` to `1.19.83 CR: 88.0.4324.79` didn't lose state/cause issues

**`Default`** | **`Blocked`** | **`Allow`**
--------------|----------------|---------------
<img width="1219" alt="Screen Shot 2021-01-13 at 10 10 35 PM" src="https://user-images.githubusercontent.com/2602313/104540151-e5254580-55ec-11eb-9cce-98e835cdcdc8.png"> | <img width="1217" alt="Screen Shot 2021-01-13 at 10 10 53 PM" src="https://user-images.githubusercontent.com/2602313/104540161-e8b8cc80-55ec-11eb-8e6e-3f068ffaf1ec.png"> | <img width="1221" alt="Screen Shot 2021-01-13 at 10 12 31 PM" src="https://user-images.githubusercontent.com/2602313/104540170-ece4ea00-55ec-11eb-9a16-38aadaaa6795.png">
