### ISSUE TITLE
Javascript-blocked-sign "< >" is missing - macOS

### ISSUE THREAD

**Issue by GraOrigin** [brave/brave-browser#13272]
## Description 
Noticed since a few beta release versions, the Javascript-blocked-sign "< >" is missing in the urlbar. Only the sign for blocked images remains to be displayed on the right of the urlbar. In settings both are blocked by default.

## Brave version (brave://version info)
Version 1.19.62 Chromium: 87.0.4280.101 (Offizieller Build) beta (x86_64)

**Comment by diracdeltas** [comment]
this was removed in #199 because the icon controls weren't fully functional. we could consider adding some kind of badge to the brave shield to show if scripts are blocked.
