### ISSUE TITLE
Updated pre-populated search engine list

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#13283]
## Description 
Small update to the engines we show by default
- Add Ecosia as an option for some markets: 
    - USA (US)
    - UK (GB)
    - France (FR)
    - Germany (DE)
    - Netherlands (NL)
    - Belgium (BE)
    - Switzerland (CH)
    - Sweden (SE)
- Remove Yahoo as an option (originally added with https://github.com/brave/brave-browser/issues/10890)

## Test plan
TBD

**Comment by kjozwiak** [comment]
#### **`Case 1`** - Verify changes in the `Default search engines` list

**`USA`** | **`USA`** | **`USA`** | **`USA`**
-----------|-----------|-----------|-----------
<img width="680" alt="Screen Shot 2021-01-13 at 10 33 12 PM" src="https://user-images.githubusercontent.com/2602313/104541371-83b2a600-55ef-11eb-8ffa-d2b86774f848.png"> | <img width="1212" alt="Screen Shot 2021-01-13 at 10 30 39 PM" src="https://user-images.githubusercontent.com/2602313/104541377-87462d00-55ef-11eb-9320-ba71a44d81ea.png"> | <img width="1222" alt="Screen Shot 2021-01-13 at 10 30 54 PM" src="https://user-images.githubusercontent.com/2602313/104541390-8b724a80-55ef-11eb-9abd-71f02a17483f.png"> | <img width="1216" alt="Screen Shot 2021-01-13 at 10 31 03 PM" src="https://user-images.githubusercontent.com/2602313/104541404-90cf9500-55ef-11eb-9fdf-b7b2f61c5914.png">

**`UK`** | **`UK`** | **`UK`** | **`UK`**
---------|---------|---------|---------
<img width="684" alt="Screenshot 2021-01-13 at 22 36 38" src="https://user-images.githubusercontent.com/2602313/104541655-0b001980-55f0-11eb-99e5-f2c9194ff977.png"> | <img width="1218" alt="Screenshot 2021-01-13 at 22 36 50" src="https://user-images.githubusercontent.com/2602313/104541664-0f2c3700-55f0-11eb-9328-21f12f7eabf4.png"> | <img width="1222" alt="Screenshot 2021-01-13 at 22 37 04" src="https://user-images.githubusercontent.com/2602313/104541673-14898180-55f0-11eb-8742-e877e9701dca.png"> | <img width="1216" alt="Screen Shot 2021-01-13 at 10 31 03 PM" src="https://user-images.githubusercontent.com/2602313/104541683-1fdcad00-55f0-11eb-893e-121faed360dc.png">

**`Canada`** | **`Canada`** | **`Canada`** | **`Canada`**
---------|---------|---------|---------
<img width="685" alt="Screen Shot 2021-01-13 at 10 41 04 PM" src="https://user-images.githubusercontent.com/2602313/104541992-b3ae7900-55f0-11eb-9293-98341d38ee71.png"> | <img width="1216" alt="Screen Shot 2021-01-13 at 10 41 21 PM" src="https://user-images.githubusercontent.com/2602313/104541997-b6a96980-55f0-11eb-8fcd-88aac50f7ca7.png"> | <img width="1219" alt="Screen Shot 2021-01-13 at 10 41 35 PM" src="https://user-images.githubusercontent.com/2602313/104542007-bad58700-55f0-11eb-91e6-7dfcee4f6efa.png"> | <img width="1218" alt="Screen Shot 2021-01-13 at 10 41 42 PM" src="https://user-images.githubusercontent.com/2602313/104542016-bf01a480-55f0-11eb-8bc8-639fa54cb434.png">

**`Note:`** Ecosia shouldn't be appearing in Canada as it's not a supported region as per https://github.com/brave/brave-browser/issues/13283#issue-773296193

**`France` (Default Quant)`** | **`France` (Default Quant)`** | **`France` (Default Quant)** | **`France` (Default Quant)`**
-------------|---------------|-------------------------------|--------------
<img width="694" alt="Screenshot 2021-01-13 at 22 45 18" src="https://user-images.githubusercontent.com/2602313/104542242-24ee2c00-55f1-11eb-959a-f86c1f44419a.png"> | <img width="1218" alt="Screenshot 2021-01-13 at 22 44 29" src="https://user-images.githubusercontent.com/2602313/104542255-2a4b7680-55f1-11eb-8aad-bce9f9200a25.png"> | <img width="1220" alt="Screenshot 2021-01-13 at 22 44 44" src="https://user-images.githubusercontent.com/2602313/104542267-2f102a80-55f1-11eb-98b9-72f9b7843882.png"> | <img width="1220" alt="Screenshot 2021-01-13 at 22 44 53" src="https://user-images.githubusercontent.com/2602313/104542277-333c4800-55f1-11eb-864b-b58138442d22.png">

**`Note:`** ensured that `Qwant` was still the default search engine in `France`

**`Germany` (Default DDG)`** | **`Germany` (Default DDG)`** | **`Germany` (Default DDG)** | **`Germany` (Default DDG)`**
----------------|-----------------|-----------------------------------|--------------
<img width="689" alt="Screenshot 2021-01-13 at 22 47 23" src="https://user-images.githubusercontent.com/2602313/104542674-ff155700-55f1-11eb-8156-13a1cbd1b00f.png"> | <img width="1220" alt="Screenshot 2021-01-13 at 22 48 24" src="https://user-images.githubusercontent.com/2602313/104542688-05a3ce80-55f2-11eb-9d8d-dad28a029c9e.png"> | <img width="1219" alt="Screenshot 2021-01-13 at 22 48 36" src="https://user-images.githubusercontent.com/2602313/104542699-09cfec00-55f2-11eb-9c74-3c60cbc430cf.png"> | <img width="1221" alt="Screenshot 2021-01-13 at 22 48 44" src="https://user-images.githubusercontent.com/2602313/104542708-0e94a000-55f2-11eb-90ba-1cce442d93f7.png">

**`Note:`** ensured that `DDG` was still the default search engine in `Germany`

**`Netherlands`** | **`Netherlands`** | **`Netherlands`** | **`Netherlands`**
----------------|-----------------|---------------------------|--------------
<img width="700" alt="Screenshot 2021-01-13 at 22 54 51" src="https://user-images.githubusercontent.com/2602313/104542962-8236ad00-55f2-11eb-932f-223a9fb234f7.png"> | <img width="1208" alt="Screenshot 2021-01-13 at 22 54 45" src="https://user-images.githubusercontent.com/2602313/104542968-85319d80-55f2-11eb-9370-9a398dfd9ea1.png"> | <img width="1216" alt="Screenshot 2021-01-13 at 22 55 06" src="https://user-images.githubusercontent.com/2602313/104542984-895dbb00-55f2-11eb-8899-1f3a8c397d7a.png"> | <img width="1217" alt="Screenshot 2021-01-13 at 22 55 12" src="https://user-images.githubusercontent.com/2602313/104542996-8e226f00-55f2-11eb-8f47-851d8ebfe3b1.png">

**`Belgium`** | **`Belgium`** | **`Belgium`** | **`Belgium`**
----------------|-----------------|---------------------------|--------------
<img width="691" alt="Screenshot 2021-01-13 at 23 45 29" src="https://user-images.githubusercontent.com/2602313/104546257-c8433f00-55f9-11eb-9c41-fd5d04431676.png"> | <img width="1217" alt="Screenshot 2021-01-13 at 23 45 57" src="https://user-images.githubusercontent.com/2602313/104546260-caa59900-55f9-11eb-8df4-029ee4902ccb.png"> | <img width="1227" alt="Screenshot 2021-01-13 at 23 46 11" src="https://user-images.githubusercontent.com/2602313/104546276-d09b7a00-55f9-11eb-8bfa-c322d63da6da.png"> | <img width="1222" alt="Screenshot 2021-01-13 at 23 46 17" src="https://user-images.githubusercontent.com/2602313/104546288-d5f8c480-55f9-11eb-8fef-13439e110ec7.png">

**`Switzerland`** | **`Switzerland`** | **`Switzerland`** | **`Switzerland`**
----------------|-----------------|---------------------------|--------------
<img width="695" alt="Screenshot 2021-01-13 at 23 49 31" src="https://user-images.githubusercontent.com/2602313/104546482-499ad180-55fa-11eb-87f8-14666dda20e9.png"> | <img width="1216" alt="Screenshot 2021-01-13 at 23 49 44" src="https://user-images.githubusercontent.com/2602313/104546487-4d2e5880-55fa-11eb-8c21-f158cfdefd56.png"> | <img width="1215" alt="Screenshot 2021-01-13 at 23 50 08" src="https://user-images.githubusercontent.com/2602313/104546496-528ba300-55fa-11eb-9898-76df254b6421.png"> | <img width="1211" alt="Screenshot 2021-01-13 at 23 50 14" src="https://user-images.githubusercontent.com/2602313/104546504-56b7c080-55fa-11eb-91fc-4f1539c36b79.png">

**`Sweden`** | **`Sweden`** | **`Sweden`** | **`Sweden`**
----------------|-----------------|---------------------------|--------------
<img width="684" alt="Screenshot 2021-01-13 at 23 54 11" src="https://user-images.githubusercontent.com/2602313/104546744-e2315180-55fa-11eb-8ceb-b6fc8dc0ee35.png"> | <img width="1214" alt="Screenshot 2021-01-13 at 23 54 31" src="https://user-images.githubusercontent.com/2602313/104546754-e5c4d880-55fa-11eb-8804-61fa926d03d0.png"> | <img width="1219" alt="Screenshot 2021-01-13 at 23 54 46" src="https://user-images.githubusercontent.com/2602313/104546766-ebbab980-55fa-11eb-8ac1-5e7323321b12.png"> | <img width="1217" alt="Screenshot 2021-01-13 at 23 54 53" src="https://user-images.githubusercontent.com/2602313/104546781-f412f480-55fa-11eb-8e7c-fe6abf226ea9.png">

#### **`Case 2`** - Verify folks w/ Yahoo set don't lose their setting

**`Case 1 - Canada`**

* downloaded `1.18.78 CR: 87.0.4280.141` and set the default SE as `Startpage`
* upgraded to `1.19.83 CR: 88.0.4324.79` and ensured that `Startpage` was still set as the default SE
  * checked both `brave://settings/search` & `brave://settings/searchEngines`
* ensured that `Ecosia` wasn't being listed under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that `Yahoo` was removed from both `brave://settings/search` & `brave://settings/searchEngines`

**`Case 2 - USA`**

* downloaded `1.18.78 CR: 87.0.4280.141` and set the default SE as `Yahoo`
* upgraded to `1.19.83 CR: 88.0.4324.79` and ensured that `Yahoo` was still set as the default SE
  * checked both `brave://settings/search` & `brave://settings/searchEngines`
* ensured that `Ecosia` was being listed under `brave://settings/search` & `brave://settings/searchEngines`
* * ensured that `Yahoo` wasn't being removed from both `brave://settings/search` & `brave://settings/searchEngines`

**`Case 3 - France`**

* downloaded `1.20.65 CR: 88.0.4324.51` and set the default SE as `Qwant` (Default)
* upgraded to `1.20.73 CR: 88.0.4324.79` and ensured that `Qwant` was still set as the default SE
  * checked both `brave://settings/search` & `brave://settings/searchEngines`
* ensured that `Ecosia` was being listed under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that `Yahoo` was removed from both `brave://settings/search` & `brave://settings/searchEngines`

#### **`Case 3`** - Verify the Ecosia referral IDs used are correct

Searched via the omnibox when `Ecosia` was set as the default search engine and ensured that `tt=e8eb07a6` as per https://github.com/brave/internal/wiki/Search-engine-integrations

* https://www.ecosia.org/search?tt=e8eb07a6&q={brave+software}
* https://www.ecosia.org/search?tt=e8eb07a6&q={BAT+token}

Ensured that directly going to `Ecosia` and initiating a search doesn't use the referral code as per the following:

* https://www.ecosia.org/search?q=Brave+software
* https://www.ecosia.org/search?q=BAT+token

**Comment by kjozwiak** [comment]
Found https://github.com/brave/brave-browser/issues/13568 during QAing with @srirambv, We'll get this fixed and uplifted but in the meantime, can finish the remaining cases 👍 Once https://github.com/brave/brave-browser/issues/13568 has been fixed, we can quickly check if `{ }` are removed. Shouldn't block QA on the above cases.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.83 x64 build

**Scenario 1** - Verify changes in the `Default search engines list`
- Verified Ecosia is present Search engine onboarding list and listed in `Standard tab` search engine list and `Private Tab` search engine list

USA (Onboarding) | USA (Standard Tab SE list) | USA (Private Tab SE list)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/104569896-2e0ae780-5649-11eb-8219-5ba67cb19b82.png) | ![image](https://user-images.githubusercontent.com/17010094/104569912-33683200-5649-11eb-8f2f-077eceec7177.png) | ![image](https://user-images.githubusercontent.com/17010094/104569936-3a8f4000-5649-11eb-9103-ce3e2dd09245.png)

France (Onboarding) | France (Standard Tab SE list) | France (Private Tab SE list)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/104571168-b047db80-564a-11eb-90f2-0f55d3658249.png) | ![image](https://user-images.githubusercontent.com/17010094/104571134-a7efa080-564a-11eb-8b94-474c1dc91af8.png) | ![image](https://user-images.githubusercontent.com/17010094/104571120-a45c1980-564a-11eb-8fd3-dc9b3764a981.png)

Belgium (Onboarding) | Belgium (Standard Tab SE list) | Belgium (Private Tab SE list)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/104571051-93130d00-564a-11eb-9dc8-bb622f375340.png) | ![image](https://user-images.githubusercontent.com/17010094/104571076-9ad2b180-564a-11eb-9d2e-3beb279794f0.png) | ![image](https://user-images.githubusercontent.com/17010094/104571066-a1612900-564a-11eb-9a36-5c509842ab13.png)

- Verified Ecosia is not listed for default search engine for unsupported regions like Japan

Japan (Onboarding) | Japan (Standard Tab SE list) | Japan (Private Tab SE list)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/104571274-cce41380-564a-11eb-9924-8d640bed0b7c.png) | ![image](https://user-images.githubusercontent.com/17010094/104571248-c786c900-564a-11eb-92f2-3629c4335438.png) | ![image](https://user-images.githubusercontent.com/17010094/104571240-c3f34200-564a-11eb-9757-e09b95b465f1.png)

**Scenario 2** - Verify folks w/ Yahoo set don't lose their setting
- Verified installing 1.18.78 and setting Yahoo as default and upgrading to 1.19.83 retains Yahoo as default SE
- Verified setting Yahoo as default on 1.18.78 and upgrading to 1.19.83 adds Ecosia to the list of default SE
- Verified setting Yahoo as default on 1.18.78 and upgrading to 1.19.83 and changing default to Ecosia doesn't lose Yahoo from the list

**Scenario 3** - Verify the Ecosia referral IDs used are correct
- Verified searching via URL bar with Ecosia set as default SE, `tt=42b8ae98` is appended to the search URL
![image](https://user-images.githubusercontent.com/17010094/104570011-4f6bd380-5649-11eb-8ba5-32619b24cca7.png)
- Verified visiting `https://ecosia.org` and performing a search doesn't append the refcode
![image](https://user-images.githubusercontent.com/17010094/104570027-54308780-5649-11eb-9cc6-534633812c7c.png)

-------
Verification passed on Samsung Tab A with Android 10 running 1.19.83 x64 build

**Scenario 1** - Verify changes in the `Default search engines list`
- Verified Ecosia is present Search engine onboarding list and listed in `Standard tab` search engine list and `Private Tab` search engine list

USA (Onboarding) | USA (Standard Tab SE list) | USA (Private Tab SE list)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/104578989-4d0e7700-5653-11eb-89d6-7224566f7d0c.png) | ![image](https://user-images.githubusercontent.com/17010094/104579000-50096780-5653-11eb-88ae-9651281a288d.png) | ![image](https://user-images.githubusercontent.com/17010094/104579008-526bc180-5653-11eb-96d5-a5b78f424608.png)

France (Onboarding) | France (Standard Tab SE list) | France (Private Tab SE list)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/104579042-5d265680-5653-11eb-996a-887dce76a990.png) | ![image](https://user-images.githubusercontent.com/17010094/104579048-60214700-5653-11eb-981e-9a6222b8a0b6.png) | ![image](https://user-images.githubusercontent.com/17010094/104579056-6283a100-5653-11eb-8334-da5b4b74e49b.png)

Belgium (Onboarding) | Belgium (Standard Tab SE list) | Belgium (Private Tab SE list)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/104579019-5566b200-5653-11eb-9359-d91b0f0e6291.png) | ![image](https://user-images.githubusercontent.com/17010094/104579026-57c90c00-5653-11eb-8b88-966a3ddb890a.png) | ![image](https://user-images.githubusercontent.com/17010094/104579032-5a2b6600-5653-11eb-8287-95a9172ee08e.png)

- Verified Ecosia is not listed for default search engine for unsupported regions like Japan

Japan (Onboarding) | Japan (Standard Tab SE list) | Japan (Private Tab SE list)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/104578900-2fd9a880-5653-11eb-8fa2-9fff80cb69e3.png) | ![image](https://user-images.githubusercontent.com/17010094/104578891-2c462180-5653-11eb-9f40-d86849698eaf.png) | ![image](https://user-images.githubusercontent.com/17010094/104578867-281a0400-5653-11eb-85c9-3a67203bdd9b.png)

**Scenario 2** - Verify folks w/ Yahoo set don't lose their setting
- Verified installing 1.18.78 and setting Yahoo as default and upgrading to 1.19.83 retains Yahoo as default SE
- Verified setting Yahoo as default on 1.18.78 and upgrading to 1.19.83 adds Ecosia to the list of default SE
- Verified setting Yahoo as default on 1.18.78 and upgrading to 1.19.83 and changing default to Ecosia doesn't lose Yahoo from the list

**Scenario 3** - Verify the Ecosia referral IDs used are correct
- Verified searching via URL bar with Ecosia set as default SE, `tt=42b8ae98` is appended to the search URL
![image](https://user-images.githubusercontent.com/17010094/104578853-23ede680-5653-11eb-996a-9881c93483d2.png)

- Verified visiting `https://ecosia.org` and performing a search doesn't append the refcode
![image](https://user-images.githubusercontent.com/17010094/104578837-1e909c00-5653-11eb-9f51-f36e2fd3c769.png)
