### ISSUE TITLE
Add ability to specify brave-core commit in config.js

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#1328]
Currently we have the ability to specify a brave-core tag, such as:

```
      "brave-core": {
        "dir": "src/brave",
        "tag": "v0.56.1",
        "repository": {
          "url": "https://github.com/brave/brave-core.git"
        }
      }
```

We should allow commits as well, something like:

```
"commit": "a096348c00e7f99cba3f551616e841d9e14c53af",
```

This enables our CI workflow in which we don't tag a commit until after it has been built, but still gives us the ability to pin a build to a commit (requested for changelog generation for example.)

**Comment by kjozwiak** [comment]
Marking this as `QA/No` as there seems like there's nothing QA can do here. If someone feels differently or if there's something that needs checked, please add a test plan/cases and change the labels from `QA/No` to `QA/Yes`. Thanks!
