### ISSUE TITLE
Not getting ad notification for NTP SI although the AD's history is listed in brave://rewards

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13287]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/12946

Not getting ad notification for NTP SI although the AD's history is listed in brave://rewards
## Steps to Reproduce

   1. Clean install 1.19.x
   2. Enable Rewards 
   3. View an NTP SI.
   4. Not getting Ad notification 
   5. Navigate to brave://rewards and reload the page Ad is listed in the Ads history page
   
## Actual result:

Ads panel:
![image](https://user-images.githubusercontent.com/38657976/102974009-ccf96380-4523-11eb-8a52-376a6ba59a07.png)

Ads history:
![image](https://user-images.githubusercontent.com/38657976/102973950-b2bf8580-4523-11eb-9572-0b7b9dc582c7.png)

## Expected result:
Should receive Ad notification

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.19.66 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @moritzhaller @jsecretan

**Comment by tmancey** [comment]
@GeetaSarvadnya It is correct that you are not receiving an ad notification. NTP ads are shown in the NTP.
