### ISSUE TITLE
Navigating back by swiping left on a MacBook doesn't work on some webpages

### ISSUE THREAD

**Issue by dschuessler** [brave/brave-browser#13294]
## Description 

Navigating back by swiping left on a MacBook doesn't work on some webpages.

## Steps to Reproduce

   1. Visit https://chrome.google.com/webstore/category/extensions with a MacBook.
   2. Click on an extension.
   3. Try to navigate back by placing two fingers on your trackpad and swiping left.

## Actual result:

Nothing happens.

## Expected result:

Brave navigates back to https://chrome.google.com/webstore/category/extensions

## Reproduces how often: 

Approx. 1% of pages. Another one I noticed is https://onymos.com/. Google for Onymos, visit the page and try to navigate back per swiping. Doesn't work.

## Brave version (info found on brave://version)

Brave | 1.18.75 Chromium: 87.0.4280.101 (Offizieller Build) (x86_64)
-- | --
Überarbeitung | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
Betriebssystem | macOS Version 10.14.6 (Build 18G7016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Yes.
- Can you reproduce this issue with the dev channel? Yes.
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome?  Yes.

**Comment by rebron** [comment]
I'm not able to reproduce this. On the two example sites provided I was able to swipe with two finger left or right to go forward or back.
