### ISSUE TITLE
No binaries for aarch64 linux?

### ISSUE THREAD

**Issue by L-as** [brave/brave-browser#13297]
On the releases page there are aarch64 builds for a variety of platforms, except standard Linux! Does Brave support aarch64 GNU/Linux? And if it does, is it possible to have builds for them on the releases page? I would probably be the only user of Brave on this platform, so it might not make sense economically.

**Comment by jsbase** [comment]
ur mit the only one. We need Brave for our Raspberry pie

**Comment by bsclifton** [comment]
@L-as unfortunately, we don't support it. Maybe we can revisit if this becomes more popular
