### ISSUE TITLE
Phishing detection sometimes misses urls from Phishfort

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#13296]
## Description 
In addition to the general list of malicious crypto related domains, (https://mainnet-infura-api.brave.com/blacklist) we also take in to consideration additional coverage from Phishfort (https://mainnet-infura-api.brave.com/phishfort)

Urls from the phishfort endpoint are not always correctly leading to the phishing detection splash page.

## Test Plan
1. Install Crypto Wallets
2. Ensure Provider is set to 'Crypto Wallets'
3. Navigate to a legitimate URL, such as cryptokitties.co, ensure no phishing warning
4. Navigate to `http://yearnapp.finance/` (general list), ensure phishing warning is shown
5. Navigate `http://www.internetbadguys.com/` (phishfort, ensure phishing warning is shown

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.19.74 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Linux
Component | `1.0.19 Dev`

- Verified test plan from https://github.com/brave/brave-browser/issues/13296#issue-774686000
- Verified network call to `https://mainnet-infura-api.brave.com/phishfort` is sent when a phishing site is loaded with CW process running
<img width="1147" alt="Screenshot 2021-01-07 at 10 22 14" src="https://user-images.githubusercontent.com/17010094/103881597-93ebf200-50d2-11eb-82b2-845cd65304a4.png">

-------
Verification passed on 

Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Windows 10 OS Version 2009 (Build 19042.685)
Component | `1.0.19 Dev`

- Verified test plan from https://github.com/brave/brave-browser/issues/13296#issue-774686000
- Verified network call to `https://mainnet-infura-api.brave.com/phishfort` is sent when a phishing site is loaded with CW process running
<img width="1044" alt="Screenshot 2021-01-07 at 04 59 00" src="https://user-images.githubusercontent.com/17010094/103881699-b67e0b00-50d2-11eb-961f-bb68ac698dc6.png">

------

Verification passed on 

Brave | 1.20.58 Chromium: 88.0.4315.7 (Official Build) nightly (x86_64)
-- | --
Revision | `9b020863b2987261f6dcd018c6b388041c035f98-refs/branch-heads/4315@{#15}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.19 Dev`

- Verified test plan from https://github.com/brave/brave-browser/issues/13296#issue-774686000
- Verified network call to `https://mainnet-infura-api.brave.com/phishfort` is sent when a phishing site is loaded with CW process running
<img width="1312" alt="Screenshot 2021-01-07 at 10 21 29" src="https://user-images.githubusercontent.com/17010094/103881785-d44b7000-50d2-11eb-9812-410f945cdf0f.png">
