### ISSUE TITLE
Windows 10 Blue screen error while using brave for 10 hours

### ISSUE THREAD

**Issue by Airbus5717** [brave/brave-browser#13291]
## Description 

I get a blue screen windows error then it shuts down after using brave for 10+ hours and mostly simple websites
using Windows 10 
i7 cpu
16 GB ram 
4 GB VRAM 
and it says that VIDEO_MEMORY_MANAGEMENT_INTERNAL (blue windows error screen)
## Steps to Reproduce

   1. using windows 10 
   2. open a few tabs and keep brave browser open for 10-12+ hours 
   3. after that error screen comes

## Brave version (info found on brave://version)

Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)

**Comment by rebron** [comment]
Hi @Airbus5717 Is this battery related? 10+ hours and then your machine shuts down. I'm not sure this is an issue we can act on without additional specifics.

**Comment by kjozwiak** [comment]
@Airbus5717 the other thing that you can check is `brave://crashes` to see if there's anything logged there. But a blue screen is usually an OS crash so not sure if we'll get any useful information out of  `brave://crashes`.

Can you check the browsers `Task Manager` after ~7-8hrs of running Brave in your case to see if there's maybe a memory leak and a certain process is hogging/taking a lot of resources? You can view the `Task Manager` via `Settings Menu` -> `More Tools` -> `Task Manager`.

**Comment by Airbus5717** [comment]
> Hi @Airbus5717 Is this battery related? 10+ hours and then your machine shuts down. I'm not sure this is an issue we can act on without additional specifics.

Nope 
the laptop is on power

**Comment by Airbus5717** [comment]
> @Airbus5717 the other thing that you can check is `brave://crashes` to see if there's anything logged there. But a blue screen is usually an OS crash so not sure if we'll get any useful information out of `brave://crashes`.
> 
> Can you check the browsers `Task Manager` after ~7-8hrs of running Brave in your case to see if there's maybe a memory leak and a certain process is hogging/taking a lot of resources? You can view the `Task Manager` via `Settings Menu` -> `More Tools` -> `Task Manager`.

mostly 7-8 hours but sometimes less maybe 3 
depends on my activity
