### ISSUE TITLE
Brave installed through snapd doesn't recognize ledger.

### ISSUE THREAD

**Issue by BlackTurtle123** [brave/brave-browser#13299]
I am running brave with snapd on arch linux.
brave              1.18.75          91     latest/stable  brave       -

When I connect my ledger, it is not detected.
When using the ledger in chromium it is detected by websites.

**Comment by bsclifton** [comment]
cc; @fmarier 

There are a few known issues relating to snap; for example:
- [U2F not working in Snap distribution](https://github.com/brave/brave-browser/issues/6782)
- [[Desktop] Webcam not working on ubuntu ](https://github.com/brave/brave-browser/issues/9451)

**Comment by BlackTurtle123** [comment]
Some extra info manually allowed removable-media, u2f-devices, didn't make a difference

**Comment by fmarier** [comment]
Is the Chromium snap package that works using the [upstream snapcraft config](https://source.chromium.org/chromium/chromium/src/+/master:chrome/installer/linux/snap/snapcraft.yaml.in)?

We recently re-synced the upstream config into the Brave one (https://github.com/brave/brave-browser-snap/pull/14) and so I'm suprised 1.18.75 isn't working.

**Comment by BlackTurtle123** [comment]
Hello!
I don't run chromium through snap.
Just through normal aur package.


Op di 29 dec. 2020 01:13 schreef Francois Marier <notifications@github.com>:

**Comment by fmarier** [comment]
In that case, you might want to try the `brave-bin` AUR package.

**Comment by BlackTurtle123** [comment]
This works indeed.
Only issue is that all my data is inside the snap brave browser now.
Is there a migration path?

**Comment by mihaiplesa** [comment]
@BlackTurtle123 this describes where Brave stores data https://community.brave.com/t/where-does-brave-store-its-data-files/53830

**Comment by BlackTurtle123** [comment]
Ok,
workaround worked with the aur package.
Thanks guys
