### ISSUE TITLE
Changelog not available!

### ISSUE THREAD

**Issue by voiceofvraja** [brave/brave-browser#13295]
Please mention all the changes/updates/fixes under the platform heading in github releases otherwise what is th point of beta, is it for the user to find out what are fixed and changed or is it more efficient for the user to check if he can read what is new or changed in the update, I think it should be mentioned under the platform heading for both the beta/nightly/dev in android and windows...

![image](https://user-images.githubusercontent.com/50140643/103177893-4be3f880-48a4-11eb-85db-add601dbf96a.png)

**Comment by bsclifton** [comment]
Changelog available here:
https://github.com/brave/brave-browser/blob/master/CHANGELOG_ANDROID.md

Important features are called out in the Google Play store text. @anthonypkeane @SergeyZhukovsky is there a way to link to release notes from the text shown in play store?

**Comment by SergeyZhukovsky** [comment]
nope, we don't have, it's a good idea to add it.

**Comment by voiceofvraja** [comment]
Please mention all the changes/updates/fixes under the platform heading in github releases otherwise what is th point of beta, is it for the user to find out what are fixed and changed or is it more efficient for the user to check if he can read what is new or changed in the update, I think it should be mentioned under the platform heading for both the beta/nightly/dev in android and windows...

![image](https://user-images.githubusercontent.com/50140643/103177893-4be3f880-48a4-11eb-85db-add601dbf96a.png)

**Comment by voiceofvraja** [comment]
How are we going to know what is in this https://github.com/brave/brave-browser/releases/tag/v1.19.70

**Comment by bsclifton** [comment]
@voiceofvraja the release notes are prepared at time when it goes to release channel

**Comment by voiceofvraja** [comment]
But it won't take much time to add those to the other versions, if more users want you can just poll about it, it is not a big deal but rest your choice.

**Comment by kjozwiak** [comment]
> But it won't take much time to add those to the other versions, if more users want you can just poll about it, it is not a big deal but rest your choice. @bsclifton

It actually does take a bit of time to get those prepared as either @LaurenWags or myself need to go through the issue, and convert it to something that users will understand. For example:

* Release notes before being formatted --> https://github.com/brave/brave-browser/issues/13099
* Formatted and pushed into the CHANGELOG --> https://github.com/brave/brave-browser/pull/13140/files

Doing the above for every single new version is not sustainable. If you're curious re: what's landing in a channel, you can always use the following to see which PRs have landed. Each PR is also associated with a GH issue that you can take a look at. Example:

* `master` --> https://github.com/brave/brave-core/commits/master
* `BETA` --> https://github.com/brave/brave-core/commits/1.19.x

As per the above, notes for the "Release" channel can be found via the following:

* https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md
* https://github.com/brave/brave-browser/blob/master/CHANGELOG_ANDROID.md

**Comment by voiceofvraja** [comment]
#13099 I think these are just fine,  you could just include this little '#12345' in the release under platform,  it's supposed to be for other than stable so it's good enough

**Comment by kjozwiak** [comment]
> #13099 I think these are just fine, you could just include this little '#12345' in the release under platform, it's supposed to be for other than stable so it's good enough

Definitely appreciate the feedback but at this time, we won't be adding release notes for every build. As mentioned above, it should be really easy to check what's coming down the pipeline by checking https://github.com/brave/brave-core/ as mentioned via https://github.com/brave/brave-browser/issues/13295#issuecomment-754405116.

You can also take a look at the milestones via https://github.com/brave/brave-browser/milestones to see what's being fixed/added into each milestone.
