### ISSUE TITLE
307 internal redirects to go-updater.brave.com still send network requests to Google

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#1330]
In chrome://net-internals, there are requests to Google domains such as `https://clients2.google.com/service/update2/crx?os=mac&arch=x64&os_arch=x86_64&nacl_arch=x86-64&prod=chromiumcrx&prodchannel=beta&prodversion=70.0.55.10&lang=en-US&acceptformat=crx2,crx3&x=id%3Doemmndcbldboiebfnladdacbdfmadadm%26v%3D0.0.0.0%26installedby%3Dpolicy%26uc%26ping%3Dr%253D-1%2526e%253D1` which show a response of 307 (internal redirect) to `Location: https://go-updater.brave.com/extensions?os=mac&arch=x64&os_arch=x86_64&nacl_arch=x86-64&prod=chromiumcrx&prodchannel=beta&prodversion=70.0.55.10&lang=en-US&acceptformat=crx2,crx3&x=id%3Doemmndcbldboiebfnladdacbdfmadadm%26v%3D0.0.0.0%26installedby%3Dpolicy%26uc%26ping%3Dr%253D-1%2526e%253D1`, which is expected

Since these are 307's, I would expect no network request to the original `clients2.google.com` URL. however this appears to not be the case.

STR:
1. download wireshark for your platform
2. follow the steps in https://jimshaver.net/2015/02/11/decrypting-tls-browser-traffic-with-wireshark-the-easy-way/ to log the TLS session keys for Brave and import the keyfile into wireshark.
3. close brave, delete the profile directory.
4. start a wireshark capture and then start Brave
5. stop the capture after about 20s. look for requests with destination `172.217.164.110` (the IP for clients2.google.com)
6. inspect the decrypted SSL data for these requests with protocol http2. you should see one that looks like this:
<img width="1218" alt="screen shot 2018-09-27 at 3 35 46 pm" src="https://user-images.githubusercontent.com/549654/46178747-e9d35d80-c26c-11e8-9f42-451a211fd0a7.png">

**Comment by bbondy** [comment]
I think this is expected because we don't support the extension from our server, we redirect the user to request it from Google.  We could perhaps proxy the request instead?  If you can setup a proxy we can use a different host name here.

**Comment by diracdeltas** [comment]
Yup, I think this request makes sense. I saw some other ones with the same behavior (network traffic to $DOMAIN even though it returns 307 to the go-updater) such as `https://update.googleapis.com/service/update2`

**Comment by bbondy** [comment]
Yep these are both expected and both go to our server first:
https://clients2.google.com/service/update2/crx
https://update.googleapis.com/service/update2

**Comment by bbondy** [comment]
Here's the code for these 2:
https://github.com/brave/brave-core/blob/d07cb3eb3266b66ea4660dfe2609489a7777e1b0/browser/net/brave_common_static_redirect_network_delegate_helper.cc#L20

**Comment by bbondy** [comment]
And the go-update server code here:
https://github.com/brave/go-update/blob/494de186d34890cc9fd40c511b54fbe3aa987109/controller/controller.go#L153

https://github.com/brave/go-update/blob/494de186d34890cc9fd40c511b54fbe3aa987109/controller/controller.go#L210

**Comment by diracdeltas** [comment]
thx, closing for now

**Comment by kjozwiak** [comment]
@diracdeltas, labelled this as `QA/Yes` as it included some STR. Seems like something we should verify on the three platforms, but if you disagree, please mark this as `QA/No`. Thanks!

**Comment by kjozwiak** [comment]
Thanks for taking a look @diracdeltas! Labelled as `QA/No` 👍
