### ISSUE TITLE
Empty IPFS cache missing from Delete browsing data dialog

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#13302]
## Steps to Reproduce
   1. Browse some ipfs://hashes
   2. Go to brave://settings/clearBrowserData
   3. Delete the browsing cache using the dioalog.

## Expected result:
It should garbage collect the IPFS repository. [More details](https://www.ctrl.blog/entry/brave-ipfs.html).

## Actual result:
IPFS data remains in the IPFS repo/cache on disk.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
1.19.67

## Version/Channel Information:
Beta only.

## Other Additional Information:
Issuing a call to run the IPFS garbage collector should do the trick.

**Comment by diracdeltas** [comment]
this is a great idea; cc @yrliou

**Comment by diracdeltas** [comment]
should this be an extra switch or just be cleared whenever the user selects clear cache? i'm slightly prefer the latter.

**Comment by da2x** [comment]
I can’t see any reason to make it a separate option. However, it might be good to change the string to say something like "Clear browsing and IPFS caches," but only when IPFS is enabled.

**Comment by yrliou** [comment]
<img width="508" alt="Screen Shot 2021-01-12 at 4 23 10 PM" src="https://user-images.githubusercontent.com/4730197/104392124-48807c00-54f6-11eb-9ff1-57af8fcbec43.png">

Note that these options chromium support could be deleted for a specific time range, but it is not something `ipfs repo gc` command supports, I think for now we'll just run `ipfs repo gc` when `Cached images and files` option is selected which will purge the whole cache expect for pinned files and won't support time-ranged deletion.

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/7578

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.1 x64` using the following build:

```
Brave | 1.19.85 Chromium: 88.0.4324.89 (Official Build) (x86_64)
--- | ---
Revision | 4534be84786f5269fb52e9bf82643af61e2fedaf-refs/branch-heads/4324@{#1721}
OS | macOS Version 11.1 (Build 20C69)
```

* loaded https://dweb.link/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR and enabled `IPFS`
* ensured that `Method to resolve IPFS resources` is set as `Local Node` under `brave://settings/extensions`
* ensured that the local node was running via `brave://ipfs`
* changed directories via `cd ~/Library/Application\ Support/BraveSoftware/Brave-Browser/nljcddpbnaianmglkpkneakjaapinabi/1.0.3/`

```
kjozwiak@Kamils-MacBook-Pro 1.0.3 % ./go-ipfs_v0.7.0_darwin-amd64 --api=/ip4/127.0.0.1/tcp/45005 repo stat
NumObjects: 28
RepoSize:   53568
StorageMax: 1000000000
RepoPath:   /Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/brave_ipfs
Version:    fs-repo@10
```

* opened `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html` and waited till the entire website loaded

```
kjozwiak@Kamils-MacBook-Pro 1.0.3 % ./go-ipfs_v0.7.0_darwin-amd64 --api=/ip4/127.0.0.1/tcp/45005 repo stat
NumObjects: 348
RepoSize:   3493272
StorageMax: 1000000000
RepoPath:   /Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/brave_ipfs
Version:    fs-repo@10
```

* cleared data via `brave://settings/clearBrowserData` and ensured that `Cached images and files` was not selected

<img width="573" alt="Screen Shot 2021-01-18 at 5 25 09 PM" src="https://user-images.githubusercontent.com/2602313/104972660-618aa080-59c0-11eb-8a93-9780e512820b.png">

```
kjozwiak@Kamils-MacBook-Pro 1.0.3 % ./go-ipfs_v0.7.0_darwin-amd64 --api=/ip4/127.0.0.1/tcp/45005 repo stat
NumObjects: 348
RepoSize:   3493272
StorageMax: 1000000000
RepoPath:   /Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/brave_ipfs
Version:    fs-repo@10
```

* cleared data via `brave://settings/clearBrowserData` and ensured that `Cached images and files` was selected this time around

<img width="602" alt="Screen Shot 2021-01-18 at 5 25 14 PM" src="https://user-images.githubusercontent.com/2602313/104972689-76673400-59c0-11eb-9284-a714c0eef629.png">

```
kjozwiak@Kamils-MacBook-Pro 1.0.3 % ./go-ipfs_v0.7.0_darwin-amd64 --api=/ip4/127.0.0.1/tcp/45005 repo stat
NumObjects: 13
RepoSize:   60667
StorageMax: 1000000000
RepoPath:   /Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/brave_ipfs
Version:    fs-repo@10
```

* opened `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html` and waited till the entire website loaded

```
kjozwiak@Kamils-MacBook-Pro 1.0.3 % ./go-ipfs_v0.7.0_darwin-amd64 --api=/ip4/127.0.0.1/tcp/45005 repo stat
NumObjects: 329
RepoSize:   3442996
StorageMax: 1000000000
RepoPath:   /Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/brave_ipfs
Version:    fs-repo@10
```

* went into `brave://settings/clearBrowserData` and selecting `Cached images and files` under the `On Exit` tab
* closed the browser and waiting ~20s
* re-launched the browser
* went into `brave://ipfs` and loaded the local node by selecting `Start`
* waited till the node connected to several peers

<img width="575" alt="Screen Shot 2021-01-18 at 5 27 29 PM" src="https://user-images.githubusercontent.com/2602313/104972718-8e3eb800-59c0-11eb-8404-c842e05bb93c.png">

```
kjozwiak@Kamils-MacBook-Pro 1.0.3 % ./go-ipfs_v0.7.0_darwin-amd64 --api=/ip4/127.0.0.1/tcp/45005 repo stat
NumObjects: 13
RepoSize:   70273
StorageMax: 1000000000
RepoPath:   /Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/brave_ipfs
Version:    fs-repo@10
```
