### ISSUE TITLE
acrhive.is domain shows unsupported browser

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13304]
## Description 

As per https://github.com/brave/brave-browser/issues/11517#issuecomment-748766097, the community is reporting that this is still occurring. Example --> https://twitter.com/ArthurFrDent/status/1340883521661898753

## Steps to reproduce 

   1. launch brave and visit acrhive.is

## Actual result 

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/103173753-151dcc00-482b-11eb-9d0e-75d31d8dbb46.jpg" width=300>
</p>

## Expected result

`arhive.is` should be loading without any issues

## Issue reproduces how often 

I'm not 100% sure as this was reported externally by the community. @ryanbr mentioned that he reproduced.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `not 100% sure`
- Can you reproduce this issue with the current Play Store Beta version? `not 100% sure`
- Can you reproduce this issue with the current Play Store Nightly version? `not 100% sure`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 10`
   
## Brave version

@ryanbr mentioned that it's reproducible on Nightly and the current release.

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @SergeyZhukovsky @ryanbr @srirambv

**Comment by kjozwiak** [comment]
BTW, this seems to be working for me on my `Samsung S10+` running `Android 10`. I checked using the following builds:

**`1.18.75 CR: 87.0.4280.101`** | **`1.19.67 CR: 87.0.4280.101`** | **`1.20.47 CR: 88.0.4315.7`**
----------------------------------|-----------------------------------|-----------------------------------
![Screenshot_20201227-101233_Brave](https://user-images.githubusercontent.com/2602313/103174113-80689d80-482d-11eb-9cb9-6bc082a07656.jpg) | ![Screenshot_20201227-102054_Brave - Nightly](https://user-images.githubusercontent.com/2602313/103174172-f836c800-482d-11eb-9588-b34d35195dec.jpg) | ![Screenshot_20201227-102054_Brave - Nightly](https://user-images.githubusercontent.com/2602313/103174127-95ddc780-482d-11eb-8384-16db651647b1.jpg)

@ryanbr can you still reproduce the above?

**Comment by ryanbr** [comment]
Okay, closing. Seems to be working for me now. Not sure what caused it (again)
