### ISSUE TITLE
Auto Updates

### ISSUE THREAD

**Issue by jesperbakhandskemager** [brave/brave-browser#13309]
I believe there should be an option to disable auto-updates, and as team members have previously stated, this currently isn't an option because of security, while this might be a rational excuse for non-technical people, you could create an option in "brave://flags" where you could have "Auto Updates:      Enabled" by default and allow people who want to actually go in there and disable it if they want.

This seems to me to be the best option since only those who could go in there could change it, would know about use flags and they should be educated enough to know about the security implications of running out-dated software.

**Comment by Hazbelll** [comment]
+1, this is especially useful to control for those of us who have to resort to using slow or metered data connections, where auto-updates cannot be tolerated.

**Comment by bsclifton** [comment]
Thanks for the suggestion; for tracking purposes, we already have this captured with https://github.com/brave/brave-browser/issues/5576.  I gave a +1 on your behalf (subscribe for updates or feel free to comment). Will close this issue as a duplicate
