### ISSUE TITLE
Do not suggest a Wayback Machine lookup if the 404 is from Wayback Machine itself

### ISSUE THREAD

**Issue by nicolasff** [brave/brave-browser#13306]
## Description 

Upon receiving a 404 for a page lookup, Brave helpfully suggests looking for an archived copy of that page on [Wayback Machine](https://web.archive.org/web/). But if you are already reading a page from Wayback Machine – maybe found using this feature – and click on a link that it hasn't archived, the website shows a 404 page saying that they haven't archived that URL.

When this happens, Brave offers to look for it on Wayback Machine, which would be a lookup of a cached version of the (non-existent) cached page.

## Steps to Reproduce

   1. Open an archived page in Wayback Machine, either by using the website directly or the Brave feature. [This link](https://web.archive.org/web/20150210000854/http://bigstory.ap.org/article/4bfb4eae689b4766a2624b677a661630/new-england-parts-new-york-ready-another-big-storm) can be used as an example for the purpose of demonstrating the issue.
   2. On the archived page, click on a few links. Some will have been indexed by the Internet Archive, but not all. If using the page linked above, click on the the article titled *London mayor touts life sciences in visit to Massachusetts*, which points to [this page](https://web.archive.org/web/20150210000854/http://bigstory.ap.org/article/2aa3854270c546e4b5f9b1d27b0f8c98/london-mayor-touts-life-sciences-visit-massachusetts).
   3. Wayback Machine has *not* archived this particular page, so it returns a 404.
   4. Brave detects the 404 response code and suggests looking for an archived copy of the page on Wayback Machine, even though the page that failed to load was from Wayback Machine itself.

## Actual result:

Brave suggests looking on Wayback Machine for an archived copy of a missing Wayback Machine page.

Screenshot below shows:
1. Brave Shields being disabled
2. The 404 from `web.archive.org` which triggered the Wayback Machine Lookup feature
3. The Wayback Machine banner and "Check for saved version" button
4. The Wayback Machine page saying they "haven't archived that URL"

![image](https://user-images.githubusercontent.com/7276/103178862-9ed59580-483b-11eb-8b6f-78d4825c3c57.png)

## Expected result:

The suggestion banner should not be displayed on Wayback Machine itself.
404s from `web.archive.org` should not trigger the feature.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Reproduces on:
1. `1.19.67 Chromium: 87.0.4280.101 (Official Build) beta (x86_64)` on macOS Big Sur
2. `1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)` on Windows 10 Pro

## Version/Channel Information:

- Can you reproduce this issue with the current release? **YES**
- Can you reproduce this issue with the beta channel? **YES**
- Can you reproduce this issue with the nightly channel? **not tested**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **NO**
- Does the issue resolve itself when disabling Brave Rewards? **NO** 
- Is the issue reproducible on the latest version of Chrome? **N/A** – Chrome does not offer this feature.

**Comment by ryanml** [comment]
Thanks for filing @nicolasff! I've posted a fix for this issue

**Comment by nicolasff** [comment]
@ryanml awesome, thanks for the fix! That was quick :-)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.20.86 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

Verified test plan from the description, Used URL: https://web.archive.org/web/20150210000854/http://bigstory.ap.org/article/2aa3854270c546e4b5f9b1d27b0f8c98/london-mayor-touts-life-sciences-visit-massachusetts

Reproduced the issue on 1.19.x. 
![image](https://user-images.githubusercontent.com/34715963/105414261-8b99c800-5c37-11eb-829f-9b0ea663cd0d.png)

Verified on 1.20.x. Wayback Machine banner is not shown.
![image](https://user-images.githubusercontent.com/34715963/105414433-c69bfb80-5c37-11eb-96e9-15890b503796.png)
