### ISSUE TITLE
YouTube videos linked from Google searches open in YouTube app instead of Brave

### ISSUE THREAD

**Issue by pdg137** [brave/brave-browser#13310]
## Description 
With the Brave app configured to open YouTube videos in-browser, video links returned in Google searches still open in the YouTube app.

## Steps to reproduce 

   1. Enable "Video playback in Brave".
   2. In the app settings for the YouTube app, set "Open supported links" to "Don't allow app to open links". 
   3. Verify that normal YouTube links, such as [this one](https://www.youtube.com/watch?v=0S0B3hnOh-U) open in the browser.
   3. Do a Google search that returns videos results such as [spacex youtube](https://www.google.com/search?q=spacex+youtube).
   4. Tap one of the YouTube results.

## Actual result 

The YouTube app opens with the video despite being disabled in multiple ways. I can't find any way to prevent Brave from opening the YouTube app.

## Expected result

It should play the video in Brave. I should have some control over Brave diverting my clicks to other apps on my phone.

## Issue reproduces how often 

Easily reproduced.

## Version/Channel Information:

Tested on version 1.18.75 from the Play Store app

## Device details
Google Pixel 3 XL with Android 11.

## Brave version
1.18.75

## Website problems only

The issue is reproducible on the latest version of Chrome.

**Comment by anthonypkeane** [comment]
Hi @pdg137 
There is an option in Site Settings to enable Video playback in Brave. Do you have this enabled?

**Comment by pdg137** [comment]
Yes, that was Step 1 in my steps to reproduce above, and videos played fine on the YouTube mobile website.

BUT, this has now started working for me (on version 1.22.69).

So, unless someone else can reproduce, maybe it's fixed now?

**Comment by anthonypkeane** [comment]
ok, thanks for following up. I'll close this but please re-open if you encounter it again.

**Comment by pdg137** [comment]
It's happening again on 1.34.80, exactly as described. There's something about Google search results that diverts my clicks to the YouTube app (and other apps) without my permission.

By the way, in a private tab it works correctly, not sending my click to the app.

**Comment by pdg137** [comment]
I think it might have to do with "intents". Here is an example link that opens the YouTube app without permission or any way to disable it:

[intent://TeVbYCIFVa8/#Intent;scheme=vnd.youtube;package=com.google.android.youtube;end;](https://tinyurl.com/n5dw497t)

(I used a URL shortener there to get the link to work in GitHub.)

**Comment by pdg137** [comment]
Here is a corresponding bug report in Chromium:

https://bugs.chromium.org/p/chromium/issues/detail?id=668729

They have it marked WontFix. Seems like an opportunity for Brave to distinguish itself by not allowing sites to open random apps without user permission.

**Comment by pdg137** [comment]
Refiled this with a more clear description as #20593.
