### ISSUE TITLE
Import from Chromium version of Microsoft Edge

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#13334]
## Description 
Currently, the import screen (brave://settings/importData) does show Microsoft Edge but this is the older non-Chromium version

## Steps to Reproduce

   1. Have a profile in Chromium version of Microsoft Edge
   2. Visit brave://settings/importData
   2. Try to import profile

## Actual result:
Profile not detected / shown in drop down

## Expected result:
Profile should be detected / shown in profile

**Comment by rebron** [comment]
Wait for upstream fix? 
cc: @simonhong Idea for level of effort on this one?

**Comment by georgir** [comment]
In the mean time I think you should remove the Edge option (or at least label it appropriately) so as to not mislead users. Importing 2 year old data (from before Edge got updated) that users did not even know is still kept around instead of their current data leaves a very bad first impression.

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` until https://github.com/brave/brave-core/pull/14137 is uplifted to 1.42.x

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-browser/issues/24002 has been uplifted to 1.42.x and is available in `1.42.67` and higher.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 11 Version 21H2 (Build 22000.795)
```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.42.82 Chromium: 104.0.5112.69 (Official Build) (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```

**_Clean profile_**

**_Upgrade profile_**

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 


Prerequisite:  Create profiles in Microsoft Edge
<Details>

Profile 1

history|bookmarks|extensions
----|----|----

Profile 2

bookmarks|history
---|---


</details>

#### <summary>Case 1: `Microsoft Edge (Chromium)` Profile 1- Import from clicking  `Import bookmarks now...` link on the bookmarks bar </summary> - `PENDING` </summary>
<Details>

1. Install 1.42.80
2. launch Brave
3. click `Skip welcome tour`
4. click `Import bookmarks now...`in the bookmarks bar
5. confirmed Microsoft Edge option displayed in the `Import bookmarks and settings` modal drop down
6. Select `Microsoft Edge Profile 1`
7. keep default selections 
    - `Browsing history`
    - `Favorites/Bookmarks`
    - `Saved passwords`
    - `Extensions`
11. click import
12. confirmation modal `Your bookmarks and settings are ready` is displayed as it's existing functionality
13. click Done
14. confirmed `Favorites/Bookmarks` shown in the `bookmarks bar` and `brave://settings/bookmarks`
15. confirmed   `Extensions` is imported and shown `brave://extensions`
16. confirmed `Browsing history` is imported and shown `brave://history`
17. confirmed `Saved passwords` shown in `brave://settings/passwords`
18. clicked on a bookmark  (`bbc.com`) and the site is loaded

Step 4|Step 5|Step 6 & 7|Step 13|Step 15|Step16|Step 17|Step 17
------|------|------|------|------|------|-----|-------


</details>

#### <summary>Case 2: `Microsoft Edge (Chromium)` Profile 2 -  Import from `Hamburger menu` - `PENDING`  </summary>
<Details>

1. new profile
2. launch Brave
3. click `Hamburger menu`
4. click `Bookmarks`>>`Import bookmarks and settings`
5. confirmed both profiles `Microsoft Edge Profile 1` and `Microsoft Edge Profile 2` options displayed in the `Import bookmarks and settings` modal 
6. select `Microsoft Edge Profile 2`
8. import only `Favorites/Bookmarks` option
9. click `Import` 
10. click `Done`
11. confirmed bookmarks shown in the `bookmarks bar` and `brave://settings/bookmarks`
12. confirmed bookmarks displayed in `Hamburger menu`>>`Bookmarks` 

Step 3&4|Step 5|Step 6& 7|Step 10|Step 11
------|------|-------|------|------


</details>

#### <summary>Case 4:  Multiple profiles - Import both `Microsoft Edge (Chromium)` profiles  - `PENDING` </summary>
<Details>

1. new profile
2. launch Brave
3. click `Skip welcome tour`
4. click `Import bookmarks now...`in the bookmarks bar
5. Select `Microsoft Edge Profile 1` and import `Favorites/Bookmarks` and `Extensions` from the `Import bookmarks and settings` modal
6. Click `import`
7. Click `Done`
8. Confirmed `Favorites/Bookmarks` and `Extensions` successfully imported
9. import `Microsoft Edge Profile 2` 
10. select `Browsing History` and `Favorites/Bookmarks` and click `import`
11. confirmed `Browsing History` and `Favorites/Bookmarks` are successfully imported 
12.  `Favorites/Bookmarks` for second profile displayed as a folder in the bookmarks bar

Step 4|Step 5|Step 8|Step 9&10|Step 11
-----|------|------|------|------


</details>

#### <summary>Case 5: Import from `Chrome` and `Microsoft Edge (Chromium)` - `PENDING` </summary>
<Details>

1. new profile
2. launch Brave
3. click `Import bookmarks now...`in the bookmarks bar
4. Select `Chrome Person 1` from the `Import bookmarks and settings` modal
5.  keep default selections `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions`
6. Click `Import` and click `Done`
7. Confirmed successful import of  `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions`
8. Go to `brave://settings/getStarted` and click   `Import bookmarks and settings`
9.  Select `Microsoft Edge Profile 2` from the `Import bookmarks and settings` modal
10. Select `Browsing history`, `Favorites/Bookmarks`
11. click `Import` and click `Done`
12. confirmed successful import of `Browsing history`, `Favorites/Bookmarks` 
13. `Imported from Micr....` folder shown in the in the bookmarks bar for imported bookmarks

Step 4|Step 7|Step 8|Step 10|Step 12
------|------|------|-------|-------


</details>

#### <summary>Case 6: Bookmarks imported from `Microsoft Edge (Chromium)` should `Sync` between profiles - `PENDING` </summary>
<Details>

#### Verified on two profiles on the same desktop:
* Profile 1 
* create another profile `profile 2-sync`

**Profile 1 **
1. new profile
2. launch Brave
3. click `Import bookmarks now...`in the bookmarks bar
4. select `Microsoft Edge Profile 1` from `Import bookmarks and settings modal
5. keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` and complete import
6. confirmed successful import of  `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions`
7. click on the "hamburger" menu, and then `Sync`
8. click on `Start a new Sync Chain`
9. click on `Computer`
10. copy the codewords
11. under `Sync Settings`, click on the `Sync everything'

Step 5|Step6|Step10|Step 11
-------|--------|------|-----


**profile 2-sync**

1. go to profile 2-sync
2. click on the "hamburger" menu, and then `Sync`
3. click `I have a Sync Code`
4. enter/paste the codewords from `Profile 1`
5. click `Confirm`
6. click `OK`
7. under `Sync Settings`, click on the `Sync everything` toggle
8. Confirmed `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` synced successfully


Step 5& 6 |Step 7
----|----


</details>

#### <summary>Case 7:  Upgrade `1.41.96`--->`1.42.80` - `PENDING` </summary>
<Details>

1. install 1.41.96
2. launch Brave
3. click `Import bookmarks now` in the bookmarks bar
4. select `Chrome` in the `Import bookmarks and settings`
5. keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` and complete import 
6. confirmed successful import of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions`
7. close the browser
8. install 1.42.80
9. relaunch Brave
10. `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` are retained
11. go to `Hamburger menu`>>`Bookmarks`>>`Import bookmarks and settings`
12. confirmed Microsoft Edge profile 1 & Profile 2 are listed in the `Import bookmarks and settings`
13. select `Microsoft Edge Profile1` 
14. keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` and complete import
15. successfully imported from `Microsoft Edge (Chromium)`

Step 1|Step 5|Step 6|Step 8|Step 11|Step 12|Step 14|Step 15
-----|------|------|------|------|------|------|-------


</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.42.84 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	Linux
```
