### ISSUE TITLE
i18n showing just placeholders (screenshot)

### ISSUE THREAD

**Issue by nikita-fuchs** [brave/brave-browser#13330]
## Description 
Instead of text, I see just  i18n place holders 

## Steps to Reproduce
Download and install Brave on german MacOS 10.15.7 Catalina

   1.  Open Brave
   2. See: 
 
![image](https://user-images.githubusercontent.com/11761828/103319568-8ed3d680-4a32-11eb-8b1d-b92bb48d759a.png)

## Actual result:
See screenshot

## Expected result:
Proper titles

## Reproduces how often: 
On Launch after install

## Brave version (brave://version info)
Brave	1.18.75 Chromium: 87.0.4280.101 (Offizieller Build) (x86_64)
Überarbeitung	9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
Betriebssystem	macOS Version 10.15.7 (Build 19H15)
JavaScript	V8 8.7.220.29
Flash	(Deaktiviert)
User-Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36
Befehlszeile	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser -psn_0_1151257 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,WebUIDarkMode,AutoupgradeMixedContent,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=AutofillServerCommunication,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,VideoPlaybackQuality,SmsReceiver,NotificationTriggers,PasswordCheck,NetworkTimeServiceQuerying,TabHoverCards,PrivacySettingsRedesign,IdleDetection,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end
Pfad zur ausführbaren Datei	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profilpfad	/Users/XXX/Library/Application Support/BraveSoftware/Brave-Browser/Default

**Comment by bsclifton** [comment]
Thanks for the report @nikita-fuchs - this is something we have captured with https://github.com/brave/brave-browser/issues/13199 and have recently fixed with https://github.com/brave/brave-core/pull/7486

Our latest release 1.18.77 should have the issue fixed if you wanted to check for updates 😄
