### ISSUE TITLE
Brave does not launch on Manjaro Linux

### ISSUE THREAD

**Issue by reach4bawer** [brave/brave-browser#13347]
## Description 

Brave would not launch on Manjaro Linux. I have installed Linux via AUR. I am on version 1.17.75.-1.  
When I try to launch it via the GUI I get no prompt or windows. When I launch via CLI I get the following error - 

```
error: could not register 'archlinuxfr' database (database already registered)
/usr/lib/brave/brave: error while loading shared libraries: libre2.so.8: cannot open shared object file: No such file or directory
```

When I fixed it by the following command - 

`sudo ln -s /usr/lib/libre2.so /usr/lib/libre2.so.8`

I ran into -

```
error: could not register 'archlinuxfr' database (database already registered)
/usr/lib/brave/brave: symbol lookup error: /usr/lib/brave/brave: undefined symbol: _ZN3re23RE23Arg12parse_stringEPKcmPv
```

## Steps to Reproduce

Not sure how would one reproduce it.

## Actual result:

Brave does not launch.

## Expected result:
Brave would launch but it does not.

## Brave version (brave://version info)

```
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	20.2
Codename:	Nibia

Brave Version: 1.17.75-1
Repository: AUR
```

**Comment by Mikesco3** [comment]
same issue here... 
/usr/lib/brave/brave: error while loading shared libraries: libre2.so.8: cannot open shared object file: No such file or directory

so I copied temporarily **libre2.so.8*** from a btrfs snapshot to **/usr/lib** and  now brave seems to work ok

**Comment by reach4bawer** [comment]
@Mikesco3  Would it be possible for you to share the file?

**Comment by Mikesco3** [comment]
try first to run a search for the files on your own system 
 **find / -iname "libre2.so.8*"**

If you can't find them here are the files
[libre2.so.8.tar.gz](https://github.com/brave/brave-browser/files/5759172/libre2.so.8.tar.gz)
_while it's not a good idea to download random files from the internet_ 

you have to unpack the files by running `tar xzf libre2.so.8.tar.gz` then once extracted, copy over copied over **libre2.so.8** and **libre2.so.8.0.0** tp **/usr/lib**

**Comment by Mikesco3** [comment]
> @Mikesco3 Would it be possible for you to share the file?

I found an official source for the file you are looking for
https://archlinux.pkgs.org/rolling/archlinux-core-x86_64/pcre2-10.36-1-x86_64.pkg.tar.zst.html
if you extract the package with the archive manager you'll find the **libre2.so.8** files you need to copy over to **/usr/lib**

**Comment by Mikesco3** [comment]
**Update** make sure you have installed the [brave-bin](https://aur.archlinux.org/packages/brave-bin/) package from AUR and **NOT** [brave](https://aur.archlinux.org/packages/brave/) as the later has been flagged **out of date**

**Comment by reach4bawer** [comment]
Removing the brave from my system and installing brave-bin fixed the problem for me. Thank you for your help @Mikesco3

**Comment by bsclifton** [comment]
Huge thanks for the assist, @Mikesco3 😄👍  And thanks for confirming that got you sorted @reach4bawer
