### ISSUE TITLE
Hide in-line tipping buttons for users who've already hidden the BAT / Brave Rewards icon

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#13341]
## Description 

In a recent update, in-line tipping buttons were made to appear by default in Brave. For users who had already disabled the BAT/Brave Rewards icon in their browser, in-line tip buttons should not have appeared, as those users had already expressed a desire to opt out of Brave Rewards-related features.

Additionally, disabling in-line tipping buttons for these users was made more difficult by the fact that they could not access the Brave Rewards settings page via the usual method: namely, clicking on the very BAT/Brave Rewards icon that they had already hidden.

## Proposed solution

For users who have already disabled the BAT/Brave Rewards icon, roll back and hide the in-line tipping buttons. 

(Any other expressions of opting out equivalent to disabling the BAT/Brave Rewards icon should also be considered.) 

## Related discussion

https://github.com/brave/brave-browser/issues/13222

Some similar reports on Reddit.

**Comment by resynth1943** [comment]
So, let's say someone creates a new Brave profile. Judging by the premise of this issue, the advertisements would still be enabled.

What would happen if they then went on to disable the Rewards icon *after* this feature was enabled? I'm presuming this aspect hasn't been considered; in that case, perhaps it would be wise to have a tete-a-tete with the Rewards Settings to disable this option too?

Any feedback / opinions on this?

**Comment by Miyayes** [comment]
@resynth1943, when you say "new profile" do you mean just a new profile for an existing user, or do you mean a brand new user who's downloaded Brave for the first time?

@emerick I think if a user disables the Brave Rewards/BAT icon, in-line tipping buttons should also be hidden. It should be considered a full opt-out. It would cause the same problem again if they went and disabled the Brave Rewards/BAT icon _before_ going into brave://rewards Tipping settings and disabling the in-line tips.

**Comment by resynth1943** [comment]
@Miyayes aren't they the same thing though? Both avenues lead to a fresh profile, so in theory they should emit the same results. I meant both. :slightly_smiling_face:

**Comment by Miyayes** [comment]
@resynth1943 Just to clarify: a decision was made to have tipping buttons appear by _default_ on a new installation of Brave. It is a gateway to help new users find and learn about Brave Rewards. However, the buttons should not have appeared for users who have already chosen to hide the Brave Rewards (BAT) icon in the URL bar (which is equivalent to an explicit expression of opting out).

Two things to note:

1. The Brave Rewards master on/off toggle doesn't exist anymore, so it's kind of anachronistic to speak of "Brave Rewards is disabled". Only individual components in BR have an on/off toggle now (like Brave Ads, which is off by default).

2. Brave Rewards was always off by default since the beginning. So, speaking of "users who had Brave Rewards disabled" needs to be broken out into two categories: (i) those who enabled Brave Rewards once in their life and then turned it off, and (ii) those who never enabled it from the beginning. (Third category are the folks who hid the Brave Rewards icon in the URL bar.)

Category (i) should probably have the tipping buttons hidden too. However, not sure how feasible it would be to go back and try to track those state changes.

Category (ii) fall under the intentional design choice that was made to have the tip buttons appear.

Category (iii) are the ones directly addressed in this issue, and the tip icons should be hidden for them and shouldn't have appeared from the beginning. 

It seems like a fresh profile (not new installation) might fall under (i) or (iii), but I think a fresh profile should be really just that: a fresh profile that doesn't carry over any preferences or settings from other, previous profiles.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.20.93 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/7655

<details>
<summary>Inline tip for Twitter</summary>

</details>
