### ISSUE TITLE
The macOS "Downloads" folder icon is not updated with the latest download

### ISSUE THREAD

**Issue by Kwadz** [brave/brave-browser#13355]
## Description 
When I download a file with Safari, le "Downloads" folder icon in the Dock is updated with the latest download.

## Steps to Reproduce

   1. Download any file on Internet, for example an image

## Actual result:
The "Downloads" folder icon in the Dock didn't change and does not contain a link to the downloaded image.

## Expected result:
The "Downloads" folder icon in the Dock should be updated and contain a link to the downloaded image.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.18.77 Chromium: 87.0.4280.101 (Official Build) (x86_64)

**Comment by rebron** [comment]
@Kwadz Same behavior when you're downloading a file in Chrome into the Downloads folder?

**Comment by Kwadz** [comment]
You're right @rebron, I should have started there. Same behaviour with Chrome, and same with Safari. Therefore it's not Brave related.
