### ISSUE TITLE
Disable custom ad notifications in release and beta builds

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#13363]
It has been decided that we use custom ad notifications for nightly builds and native ad notifications for release/beta while we improve the user experience

Custom ad notifications were originally added in https://github.com/brave/brave-core/pull/6728

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.20.86 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/105417253-a2421e00-5c3b-11eb-954a-f0406af9a37a.png)

Verification passed on
Brave | 1.20.85 Chromium: 88.0.4324.96 (Official Build) beta (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/105417803-6c516980-5c3c-11eb-97be-11959d3f68c2.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.20.98 x64 beta build

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/106886934-5f248800-66dc-11eb-8510-37904fae96d0.png> | <img width=405 src=https://user-images.githubusercontent.com/17010094/106886894-52a02f80-66dc-11eb-8e27-d16f98c470e9.png>
