### ISSUE TITLE
Tabs reloading

### ISSUE THREAD

**Issue by FatBirdie** [brave/brave-browser#13361]
## Description 

Tabs which have been left for a while unloads, and reloads when they are clicked.

## Steps to Reproduce

   1. leave tab alone for a while
   2. click tab

## Expected result:

Tabs to stay loaded at all time after a link has been opened.

## Reproduces how often: 

Happens all the time since a few days back now.

## Brave version (brave://version info)

1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-bit)
--
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Linux

**Comment by rebron** [comment]
Hi @FatBirdie We'll leave this open for a little but you'll need to provide significantly more information for us to be able to do anything with this issue. 

What do you mean by a tab "unloading"? What specific websites are you talking about? Is there a session timeout that's happening here with those sites?

**Comment by FatBirdie** [comment]
Hi reborn
Any tab with a loaded website, pinned or unpinned. If I leave them for a while (havent checked for how long, but its a matter of hours) and go to the tab again, the tab loads the content of the URL as if it was never loaded. This seems to happen to all websites (even my own, where I know there are no timeouts or javascript that reloads or anything similar).

**Comment by joejoejo** [comment]
This also happens on the beta and dev as well and has been happening for a while. It is tab reloading it is not website specific. If left unattended for a while when coming back the tab contents are blank and reload take like a minute or so. even if you try to load something else or reload the page it still is blank for a minute or so.

**Comment by kjozwiak** [comment]
@FatBirdie @joejoejo just curious if you guys have been experiencing this for a while or is this something that just started happening recently? Believe this due to Chromium tab discarding feature that helps improve the memory footprint of Chromium. There's also brave://discards where it displays a lost of all the opened tabs and what state they're currently in re: being loaded or not. I believe there was a flag that controlled his behavior via `brave;//flags` but sounds like it was removed in one of the CR bumps. CCing @bsclifton @mkarolin as they might have more information re: tab discarding.

**Comment by joejoejo** [comment]
this has been happing for a while now but it has gotten worse recently

**Comment by FatBirdie** [comment]
@kjozwiak this just started happening like a few days ago, may be a week at its most.

brave://discards returns a black page, nothing on it.

**Comment by kjozwiak** [comment]
> @kjozwiak this just started happening like a few days ago, may be a week at its most.
> 
> brave://discards returns a black page, nothing on it.

Might have been fixed in Chromium 88 which is planned to be released in `1.19.x` which is going out Jan 12th, 2020.

**Comment by ianchanning** [comment]
> @FatBirdie @joejoejo just curious if you guys have been experiencing this for a while or is this something that just started happening recently? Believe this due to Chromium tab discarding feature that helps improve the memory footprint of Chromium. There's also brave://discards where it displays a lost of all the opened tabs and what state they're currently in re: being loaded or not. I believe there was a flag that controlled his behavior via `brave;//flags` but sounds like it was removed in one of the CR bumps. CCing @bsclifton @mkarolin as they might have more information re: tab discarding.

Yes - this makes sense, Chromium is trying to lower it's memory footprint. But it's very frustrating, one tab I do have is a pomodoro timer that needs to keep running - but after 12 minutes the tab gets unloaded and the timer stops.

It also breaks a lot of Single Page Applications that keep getting unloaded and have to re-login

**Comment by ianchanning** [comment]
https://developers.google.com/web/updates/2015/09/tab-discarding

**Comment by FatBirdie** [comment]
I can also confirm that Chromium is acting the same way.

@ianchanning, I agree, its very frustrating and it really makes no sense to me. For example, website that uses sessions, or websites that don't use GET for URLs, eg for searches get screwed.

**Comment by bsclifton** [comment]
brave://discards should be working in latest version of 1.19 and newer 😄 (not on release channel yet). From this screen, you can toggle each tab and whether it should be auto-discardable

The tab discarding behavior is just a part of Chromium. I think as you visit other sites and resources are needed, it'll unload other tabs. If the tab is doing something which indicates to Chromium that it's active, it shouldn't be unloaded. Curious if there are some JavaScript calls the site can make to keep itself active

**Comment by ianchanning** [comment]
Yes - I think that this isn't anything Brave can fix and any issues should be raised against the Chrome / Chromium browser

**Comment by ianchanning** [comment]
Note that my `brave://discards` is blank and I don't know why.

![Screenshot from 2021-01-18 17-32-37](https://user-images.githubusercontent.com/233318/104941520-77459900-59b3-11eb-8d3f-0865b6c79863.png)

**Comment by FatBirdie** [comment]
mine to

**Comment by kjozwiak** [comment]
@ianchanning @FatBirdie not being able to see `brave://discard` was fixed in `1.19.86 CR: 88.0.4324.96` via https://github.com/brave/brave-browser/issues/10451. Are you guys still having issues with `1.19.86 CR: 88.0.4324.96`? If so, what platforms are you on? Is this the release channel? Or perhaps BETA or Nightly?

**Comment by ianchanning** [comment]
@kjozwiak ah, thankyou. I'm on Version 1.18.77 Chromium: 87.0.4280.101 which is the Fedora official Brave build

**Comment by kjozwiak** [comment]
> @kjozwiak ah, thankyou. I'm on Version 1.18.77 Chromium: 87.0.4280.101 which is the Fedora official Brave build

no worries! We had a release yesterday so `1.19.88 CR: 88.0.4324.96` is the latest version right now. Double checked and made sure that `brave://discards` was working as well 👍 

![image](https://user-images.githubusercontent.com/2602313/106308433-ae773e00-622e-11eb-8894-204085717e6b.png)

Should be working in `Linux` as well.

**Comment by ianchanning** [comment]
@kjozwiak awesome, thank you, yes just updated, it works now.

**Comment by omperus** [comment]
Started having this issue with the latest version (Version 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)), tabs constantly reload when I click them after a few minutes, I already checked brave://discards and it says "Discard Count: 0" on all open tabs.

This **NEVER** happened before this update, is there any way to disable tab discarding? Thanks.

I'm on W10 64-bit with 16GB of RAM.
