### ISSUE TITLE
Brave News 'reset sources' function should be hidden when Brave News is toggled off

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#13364]
## Description 

When Brave Today is toggled off, 'Reset Brave Today sources' should be hidden. This function is not relevant since the user has already indicated they don't want to see any sources by toggling off Brave Today.

## Steps to Reproduce

   1. Go to a new tab page
   2. Click 'Customize'
   3. Click 'Brave Today'
   4. Toggle off Brave Today
   5. See that 'Reset Brave Today sources' still shows

## Actual result:

<img width="749" alt="Screen Shot 2021-01-04 at 10 02 15 AM" src="https://user-images.githubusercontent.com/2388823/103564933-3eb2a500-4e74-11eb-86f6-c2c123995bf9.png">

## Expected result:
'Reset Brave Today sources' is hidden

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.20.58 Chromium: 88.0.4315.7 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by mattmcalister** [comment]
Resolved with Settings UX upgrade. Closing.
