### ISSUE TITLE
Ability to Disable Entire Category

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#13362]
## Description 
If users are not interested in a Brave Today category (e.g. _Home_), they must click into that category, and disable each individual default feed source if they wish to disable the entire category.

## Design
Add a toggle to disable an entire category.

![image](https://user-images.githubusercontent.com/2388823/103570899-c7ced980-4e7e-11eb-8551-030277bf238c.png)

## Reproduces how often: 
Always.

## Brave version (brave://version info)
1.18.77

## Other Additional Information:
Originally suggested by a user on Twitter: https://twitter.com/realAlexBalan/status/1346102944660381703

**Comment by rebron** [comment]
cc: @mattmcalister @karenkliu

**Comment by karenkliu** [comment]
Designs added!

**Comment by mattmcalister** [comment]
cc: @petemill

**Comment by mattmcalister** [comment]
Completed with the Settings upgrade. Closing now.
