### ISSUE TITLE
Uphold links out of date

### ISSUE THREAD

**Issue by Greigh** [brave/brave-browser#13378]
## Description 
All Uphold links are out of date with the new version of the Dashboard as it has come out of beta. 

## Steps to Reproduce
1. Click any of the links meant to bring you to your Uphold account/Dashboard. 
2. It will bring you to the old version Dashboard. 

## Actual result:
It brings you to the old Dashboard.

## Expected result:
Brings you to the new version of Uphold Dashboard. 

## Reproduces how often: 
It happens every time. 

## Brave version (brave://version info)
Version 1.18.77 Chromium: 87.0.4280.101 (Official Build) (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

**Comment by kjozwiak** [comment]
CCing @LaurenWags @marshall @rebron @miyayes I'm not sure what the current plan is but we'll probably want to start pointing to the new Uphold design if it's officially released/out of BETA. Probably needs some coordination with Uphold.

**Comment by bsclifton** [comment]
@Miyayes do you know if this is still an issue?

**Comment by Greigh** [comment]
> @Miyayes do you know if this is still an issue?

It is still an issue. When you click "Add funds", "Withdrawal", or any of the links to Uphold, it brings you to the old Uphold site.

**Comment by Miyayes** [comment]
Will be superseded by https://github.com/brave/brave-browser/issues/23793, since this is the only place where we actually link to somewhere that isn't the general dashboard on Uphold.
