### ISSUE TITLE
[Desktop] Add rewards setup panel to onboarding tour

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#13379]
The setup panel should allow the user to adjust the "ads per day" and "monthly AC amount" settings: 

<img width="390" alt="Screen Shot 2021-01-05 at 4 43 12 PM" src="https://user-images.githubusercontent.com/5995084/103703215-21b1cb00-4f75-11eb-860d-941f9a69bfd2.png">

The panel should only be displayed after the user has opted-in by clicking the "Start Using Rewards" button. It should not be displayed if the user is simply previewing the tour or viewing the tour again after enabling rewards.

**Comment by LaurenWags** [comment]
Verified using

```
Brave	1.21.54 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
Revision	6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS	macOS Version 10.15.7 (Build 19H512)
```

Verified test plan from https://github.com/brave/brave-core/pull/7525

<details>
<summary>Rewards Panel</summary>

Confirmed quick tour does not contain settings slide.
Confirmed tour shown after clicking on "Start using Brave Rewards" does contain settings slide.
Confirmed able to modify the selections on the settings slide.
Confirmed selections are reflected on brave://rewards page.

Setting slide with default values | Updated settings via slide | Selections retained on brave://rewards
----- | ----- | -----
<img width="1033" alt="panel - default" src="https://user-images.githubusercontent.com/28145373/107986442-0dacb080-6f9a-11eb-919a-3a96336de568.png"> | <img width="405" alt="panel - update settings" src="https://user-images.githubusercontent.com/28145373/107986446-0edddd80-6f9a-11eb-9821-183fc28fd4e0.png"> | <img width="1023" alt="panel - settings" src="https://user-images.githubusercontent.com/28145373/107986447-10a7a100-6f9a-11eb-870a-063aba58d39d.png">

</details>


<details>
<summary>Rewards page</summary>

Confirmed quick tour does not contain settings slide.
Confirmed tour shown after clicking on "Start using Brave Rewards" does contain settings slide.
Confirmed able to modify the selections on the settings slide.
Confirmed selections are reflected on brave://rewards page.

Setting slide with default values | Updated settings via slide | Selections retained on brave://rewards
----- | ----- | -----
<img width="735" alt="page-default" src="https://user-images.githubusercontent.com/28145373/107986461-17ceaf00-6f9a-11eb-9ba7-edb757b2732e.png"> | <img width="729" alt="page - update settings" src="https://user-images.githubusercontent.com/28145373/107986463-18ffdc00-6f9a-11eb-9f2f-70e63ad191bc.png"> | <img width="1022" alt="page-settings" src="https://user-images.githubusercontent.com/28145373/107986467-1a310900-6f9a-11eb-9949-d911f605bfde.png">

</details>


<details>
<summary>Tip Dialog</summary>

Confirmed quick tour does not contain settings slide.
Confirmed tour shown after clicking on "Start using Brave Rewards" does contain settings slide.
Confirmed able to modify the selections on the settings slide.
Confirmed selections are reflected on brave://rewards page.

Setting slide with default values | Updated settings via slide | Selections retained on brave://rewards
----- | ----- | -----
<img width="1027" alt="tip-default" src="https://user-images.githubusercontent.com/28145373/107986478-1ef5bd00-6f9a-11eb-9d63-9c4a1ba41f2b.png"> | <img width="1031" alt="tip-update settings" src="https://user-images.githubusercontent.com/28145373/107986480-2026ea00-6f9a-11eb-96f1-199de2dc77c6.png"> | <img width="1035" alt="tip-settings" src="https://user-images.githubusercontent.com/28145373/107986483-21581700-6f9a-11eb-8242-2a200ffdeefb.png">

</details>
