### ISSUE TITLE
Update Privacy Policy link for Rewards

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13373]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/13119 for uplift to 1.19.x

Privacy Policy link on brave://welcome opens a new tab with specified link `https://brave.com/privacy/browser/#rewards` as expected, however this link should probably be `https://brave.com/privacy/browser/#brave-rewards` in order to permalink to the Rewards section of the page.

Additionally, if we change this on brave://welcome, we probably want to change this on the onboarding modals from panel, brave://rewards, tip banner, etc as well. Need a complete list of places where this link is shown.

Note - added `OS/Android` tag as Android links to Privacy Policy as well for onboarding.

cc @zenparsing @deeppandya @marshall  

## Steps to Reproduce

Desktop
   1. Clean install or navigate to brave://welcome
   2. Go to last slide of welcome page
   3. Click on Privacy Policy link
   4. New tab is opened with `https://brave.com/privacy/browser/#rewards` URL, but this doesn't link to Rewards section
   5. Other - check other areas where this link shows (panel onboarding, brave://rewards, tip banner, other?) and see the same.

Android
1. Clean install
2. Click on panel or navigate to chrome://rewards
3. Tap on Privacy Policy link
4. New tab is opened with `https://brave.com/privacy/browser/#rewards` URL, but this doesn't link to Rewards section
5. Other - check other areas where this link shows

## Actual result:

New tab is opened with `https://brave.com/privacy/browser/#rewards` URL, but this doesn't link to Rewards section

## Expected result:
New tab is opened with `https://brave.com/privacy/browser/#brave-rewards` URL which links to Rewards section

## Reproduces how often: 

easily

## Desktop Brave version:

1.18.x, 1.19.x, 1.20.x (desktop)
1.18.x (Android)

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 1.18.x
- Can you reproduce this issue with the beta channel? yes 1.19.x
- Can you reproduce this issue with the nightly channel? yes 1.20.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@AlanBreck fixed the above server side so I'll close this off and move it into `1.19.x` so it can get checked 👍

**Comment by LaurenWags** [comment]
Confirmed server side update using Nightly build below. Will check again on 1.19.x.

```
Brave | 1.20.60 Chromium: 88.0.4315.7 (Official Build) nightly (x86_64)
-- | --
Revision | 9b020863b2987261f6dcd018c6b388041c035f98-refs/branch-heads/4315@{#15}
OS | macOS Version 10.15.7 (Build 19H15)
```

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.74 x64 beta build and 1.20.60 x64 nightly build
- Verified clicking on privacy policy link on BR panel or rewards page opens up `https://brave.com/privacy/browser/#rewards` and jumps to rewards section
---------
Verification passed on Samsung Tab A with Android 10 running 1.19.74 x64 beta build and 1.20.60 x64 nightly build
- Verified clicking on privacy policy link on BR panel or rewards page opens up `https://brave.com/privacy/browser/#rewards` and jumps to rewards section
