### ISSUE TITLE
Brave doesn't open (as simple as that)

### ISSUE THREAD

**Issue by sujay1844** [brave/brave-browser#13383]
I have attached the error log [here](https://github.com/brave/brave-browser/files/5774589/brave-error.log).

Sorry for not following the issue template. But my error isn't that elaborate to explain. Brave doesn't open.
I run Manjaro-gnome. My system information is [here](https://github.com/brave/brave-browser/files/5774596/Sys-info.txt).

Please let me know if you want anymore information about the issue.

**Comment by cristicretu** [comment]
What version and where have you downloaded Brave from?

Try installing it using the official instructions: https://brave.com/linux/#release-channel-installation

**Comment by sujay1844** [comment]
Brave version= 1.18.77
I installed the "brave-bin" package from the AUR. 
[This](https://github.com/brave/brave-browser/issues/13323) is why I installed the brave-bin package instead instead of the normal one

**Comment by sujay1844** [comment]
Oh I didn't know that Brave in the official Manjaro repository. Ok, I'll try that for a few days and close tihs issue if the problem is resolved.

**Comment by sujay1844** [comment]
@cristicretu Nope the package in Manjaro repo has the same error.

```[24563:24563:0107/162350.369723:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[24566:24572:0107/162350.388886:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[24536:24536:0107/162350.453194:ERROR:cmd_buffer_helper.cc(141)] ContextResult::kFatalFailure: CommandBufferHelper::AllocateRingBuffer() failed
[24566:24572:0107/162351.897607:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
/usr/bin/brave: line 27: 24536 Aborted                 (core dumped) /usr/lib/brave/brave "$@" $SANDBOX_FLAG $PEPPER_FLASH_FLAG $USER_FLAGS
```

**Comment by cristicretu** [comment]
Try running Brave using an empty profile: 

$`mkdir $HOME/BraveTemp`
$`brave-browser-stable --user-data-dir=$HOME/BraveTemp`

and make sure you installed the _release_ version.

**Comment by rebron** [comment]
@sujay1844 Were you able to get this working per @cristicretu last comment?

**Comment by sujay1844** [comment]
Yep @cristicretu comment did the job
