### ISSUE TITLE
Shouldn't show SE onboarding with url

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#13392]
## Description 
SE onboarding should not show up when we have url in the search bar. it should show up only on the empty NTP.

## Steps to reproduce 

   1. From settings, click on Brave Rewards 
   2. brave://rewards page would show up
   3. and click on search bar

## Actual result 
https://slack-files.com/T04PX1BU8-F01JTRUKD16-fd07c6783a

## Expected result
Shouldn't show SE onboarding with url 

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): both
   - Device type (Phone, Tablet, Phablet): all devices
   - Android version: android 10
   
## Brave version
1.20 nightly

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.20.85 x64 beta build
- Verified SE onboarding is not shown when the URL bar is pre-populated
- Verified SE onboarding is shown only when user taps on URL bar 

https://user-images.githubusercontent.com/17010094/105697455-7acda880-5efc-11eb-8211-1d8df2ab88b7.mp4

-------
Verification passed on OnePlus 6T with Android 10 running 1.20.85 x64 beta build
- Verified SE onboarding is not shown when the URL bar is pre-populated
- Verified SE onboarding is shown only when user taps on URL bar 

https://user-images.githubusercontent.com/17010094/105697476-81f4b680-5efc-11eb-87eb-43f0574ce9de.mp4
