### ISSUE TITLE
Fix the wording on the BR widget

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#13397]
## Description 

Incorrect wordings on the widget in nightly.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/4369856/103805044-de546c80-5007-11eb-8c0c-fc4376b8a155.png)

## Expected result:
1. Change 'Get paid' to 'Earn rewards'
2. Change "Brave Ads" to "Brave Private Ads"
2. Change 'By clicking rewardsWidgetEarnAndGive, you agree to...' to 'By proceeding, you agree to...'

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@zenparsing when you get a chance can you take a look?

**Comment by rebron** [comment]
related to: #8361

**Comment by zenparsing** [comment]
@jenn-rhim What should the full text of the title be?

Perhaps this?

```
Earn rewards for viewing this sponsored background image.
```

**Comment by zenparsing** [comment]
@jenn-rhim I was able to put together the following quick fix:

<img width="296" alt="Screen Shot 2021-02-02 at 12 18 51 PM" src="https://user-images.githubusercontent.com/5995084/106638265-afbbaa00-6551-11eb-9a9d-9508739a7d1e.png">

The wording of the terms of service links match the wording elsewhere in the widget. If we want to change it to "By proceeding, ..." the fix will take a bit longer.

Let me know if this works.

**Comment by zenparsing** [comment]
TOS text will be normalized in a followup: #13936.

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.21.47 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2 (Build 20D64)

Checked that @jenn-rhim's suggestions are in, with the exception of the Terms of Service text, which will be addressed in https://github.com/brave/brave-browser/issues/13936:
1. "Get paid to view..." -> "Earn rewards for viewing..."
2. "Turn on Brave Ads" -> "Turn on Brave Private Ads"


<img width="307" alt="Screen Shot 2021-02-08 at 5 05 52 PM" src="https://user-images.githubusercontent.com/387249/107301372-3845b900-6a30-11eb-94bf-79705fd70b2c.png">
