### ISSUE TITLE
Update styles in Shields panel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1339]
Update Shields UI to match brave-core styling.

## Design
Shields Up View
![2dfab5b9-3790-4ff0-8cf4-29e869884112](https://user-images.githubusercontent.com/5951041/46704128-6e639b80-cbde-11e8-8e47-2ec024ff605e.png)

Shields Down View 
![75d22077-7b46-4d0e-9d82-acc908dec024](https://user-images.githubusercontent.com/5951041/46316041-db928380-c583-11e8-9422-21390d3ff094.png)

## Description
For Shields Up View, match design above with shields toggle on.
Label ‘Shields Up for this site’ with text below
‘If a site appears broken, try shields down’

Display favicon if available and first party domain name
Display total items blocked 

Display 'Ads and trackers blocked' with toggle
Display number of items blocked
Toggle is Default on

Display '3rd-party cookies blocked' with drop down
Display number of items blocked
Drop down menu items:
‘3rd-party cookies blocked’ (default)
‘All cookies blocked'
‘Allow all cookies’

Display '3rd-party scripts blocked' with drop down
Display number of items blocked
Drop down menu items:
‘3rd-party scripts blocked’ (default)
‘All scripts blocked'
‘Allow all scripts’

Display '3rd-party device recognition attempts blocked' (this is fingerprinting) with drop down
Display number of items blocked
Drop down menu items:
‘3rd-party device recognition attempts blocked’ (default)
‘All device recognition attempts blocked'
‘Allow all device recognition attempts’

Display number of ‘Connections encrypted’

Link to Global Shield defaults with icon
chrome://settings/shields

For Shields Down View - Second screenshot
Shields toggle off with label 'Shields Down for this site'

Display favicon and first party domain name
Display shield ! alert icon with text:
‘You’re browsing this site without any privacy and security protections.’
Link to Global Shield defaults with icon
chrome://settings/shields

**Comment by srirambv** [comment]
@rebron `If a site appears broken, try turning this off` text doesn't make sense when shields is already off. Should probably just hide that text when shields is turned off?

**Comment by rebron** [comment]
@srirambv Let me get the screenshot updated to remove that text. I didn't have it defined in the initial issue.

**Comment by rebron** [comment]
@srirambv I updated the screenshot. Should be accurate now.

**Comment by bbondy** [comment]
Moving redesigned shields to 1.0 but if it's done and tested I have no problem moving it back to 0.55.x. I hope we can do that but I don't want to introduce slippage risk for the rest which was spec'ed on time, so until that is the case it will live in 1.0.

**Comment by rebron** [comment]
Updated screenshot and issue description.

**Comment by tomlowenthal** [comment]
Here's the updated specification for this feature. Please QA against the spec. 
https://docs.google.com/document/d/16hoEp7TcFLg4dolIPOzswzTKms6aDeDxm-jSXuVAZvc/edit#

And here's the working design spec (click for larger).
![shields repaint 1](https://user-images.githubusercontent.com/639937/47758277-866f8d80-dc67-11e8-887d-dfe333f9a796.png)

**Comment by srirambv** [comment]
Verification Passed on

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux 

Shields up
![image](https://user-images.githubusercontent.com/17010094/47921814-e5ade780-de8b-11e8-8c9e-6f2a167e30d9.png)
Shields down
![image](https://user-images.githubusercontent.com/17010094/47921841-f0687c80-de8b-11e8-9a62-226db61622df.png)
