### ISSUE TITLE
Headless support

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#134]
Run with `src/out/Release/brave.exe  --headless --remote-debugging-port=9222 https://www.brave.com`
Access  `http://localhost:9222/` from different browser instance.
Then, click inspectable link
Result: below message is shown
```
404 Not Found
The resource could not be found.
```

**Comment by simonhong** [comment]
Latest version works file.

**Comment by bbondy** [comment]
Awesome, thanks for checking!
