### ISSUE TITLE
We need 1:1 equivalents for each of these links somewhere on Brave

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1341]
We need a 1:1 mapping for each of these URLs to our own page which has equivalent information.

https://chromium.googlesource.com/chromium/src.git/+/master/chrome/common/url_constants.cc

Currently every link in this list is just simply going to the root of community.brave.com.

I think probably using a page on Brave community would be best.
Or else something like @mbacchi 's documentation.

We need product team help for this writing.
CC @BrendanEich @davidtemkin @tomlowenthal @bradleyrichter

**Comment by srirambv** [comment]
+1 for having support links on readthedocs rather than community page.

**Comment by rebron** [comment]
@tomlowenthal, @Brave-Matt will have some ideas as to where these pages can land as he's putting the support pages together.

**Comment by w0ts0n** [comment]
I've scheduled a meeting for Tuesday to kick start this.

**Comment by yrliou** [comment]
Below sites are also replaced with community.brave.com but are not listed in url_constants.cc.
```
// The URL for when the user clicks "learn more" on the mixed scripting page
// icon bubble.
const char kInsecureScriptHelpUrl[] =
    "https://support.google.com/chrome/?p=unauthenticated";
```
Bookmark help page
https://support.google.com/chrome/?p=bookmarks

Note: There are also pages related to cast were replaced by brave/brave-core/pull/239, but I'm not sure we'll provide docs for cast support, ping me for these urls if needed.

**Comment by bbondy** [comment]
For the most part, fixed in https://github.com/brave/brave-core/pull/643

For anything incremental we can just post individual issues.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

* Verification passed based on #1603
