### ISSUE TITLE
Enable crowd-deny

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#13426]
## Description 
Crowd deny is in the list of blacklisted components: https://github.com/brave/brave-core/blob/5709a5804cf3c0f3f96e6c250fcb34c666d75717/chromium_src/components/component_updater/component_installer.cc#L26 - We should enable it.

More details here: https://github.com/brave/brave-browser/wiki/Brave-Components

**Comment by mherrmann** [comment]
Tested in Nightly 1.20.76 on Linux that the component appears:

![image](https://user-images.githubusercontent.com/1076393/104453290-7ae8b280-55a4-11eb-972f-bd5c5c6cea48.png)

**Comment by LaurenWags** [comment]
@jumde @mherrmann should this issue be included in the release notes for 1.20.x? if so, please add `release-notes/include` label. If not, please add `release-notes/exclude` label. Thanks!

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
Revision	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS	macOS Version 10.15.7 (Build 19H15)
```

Verified test plan from https://github.com/brave/brave-core/pull/7559

<details>
<summary>Clean profile</summary>

Confirmed `Crowd Deny` is listed on brave://components as `0.0.0.0` on clean profile.
Confirmed after ~1 minute component was installed and updated version was reflected.

Example | Example
----- | -----
<img width="286" alt="Crowd Deny - installed - clean" src="https://user-images.githubusercontent.com/28145373/105205426-42505800-5b13-11eb-91ac-0dde2363bf87.png"> | <img width="278" alt="Crowd Deny - initial - clean" src="https://user-images.githubusercontent.com/28145373/105205429-43818500-5b13-11eb-912f-5760d0c9bc55.png">

</details>

<details>
<summary>Upgraded profile</summary>

Installed 1.19.82 (Dev) and confirmed `Crowd Deny` is listed on brave://components as `0.0.0.0`.
After ~1 minute component showed Update Error.
Updated to 1.20.84 (Dev).
Confirmed `Crowd Deny` is listed on brave://components as `0.0.0.0`.
Confirmed after ~1 minute component was installed and updated version was reflected.

Example 1.19.x | Example 1.19.x | Example 1.20.x | Example 1.20.x
----- | ----- | ----- | -----
<img width="286" alt="CD new 1 19 x" src="https://user-images.githubusercontent.com/28145373/105205550-62801700-5b13-11eb-989c-db4c331a382a.png"> | <img width="283" alt="CD - error - 1 19 x" src="https://user-images.githubusercontent.com/28145373/105205557-63b14400-5b13-11eb-8a50-07c212c06eac.png"> | <img width="294" alt="CD - New - 1 20 x" src="https://user-images.githubusercontent.com/28145373/105205560-64e27100-5b13-11eb-9d7a-685320a68e4f.png"> | <img width="269" alt="Screen Shot 2021-01-20 at 11 29 35 AM" src="https://user-images.githubusercontent.com/28145373/105205569-66139e00-5b13-11eb-8fde-b972a0c49505.png">

</details>

**Comment by mherrmann** [comment]
I've added the `release-notes/include` label. Sorry for the trouble @LaurenWags.

**Comment by LaurenWags** [comment]
thanks @mherrmann! I didn't want to make any assumptions 👍🏻
