### ISSUE TITLE
MS office extension is inactive on brave

### ISSUE THREAD

**Issue by SungHwan-J** [brave/brave-browser#13424]
## Description 
the ms office extension is not working on brave(only linux version, working properly on windows) with "This extension may have been corrupted" message.

## Steps to Reproduce

   1. add office extension(https://chrome.google.com/webstore/detail/office/ndjpnladcallmjemlbaebfadecfhkepb) from webstore.

## Actual result:
the extension was inactive with "This extension may have been corrupted" message and repair function also did not work.

## Expected result:
the extension is active.

## Reproduces how often: 
always

## Brave version (brave://version info)

Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) unknown (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Linux

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome? 
yes, but other chrome-based browsers(vivaldi, chromium-87.0.4280.141) are woking properly with the office extension

## Miscellaneous Information:
tested on arch linux and ubuntu 20.04

**Comment by SungHwan-J** [comment]
the extension is work.

**Comment by kjozwiak** [comment]
Thanks @SungHwan-J 👍 Just curious, what ended up being the resolution?

**Comment by SungHwan-J** [comment]
Chrome webstore suddely showed pop-up message like "this extesion is inactivated by chrome?? or webstore??" (sorry, I can't remember whole message) and provided a option to active the extension.
