### ISSUE TITLE
Choosing 1 ad per hour in UI actually shows 2 ads per hour

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#13422]
## Description 

Choosing 1 ad per hour in UI actually shows 2 ads per hour and throws an exception for debug builds

## Steps to Reproduce

   1. Set maximum ads per hour to 1 in the Rewards UI
   2. View 2 ads

## Actual result:

2 ads can be viewed per hour

## Expected result:
Only 1 ads should be shown per hour

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by stephendonner** [comment]
Hi @tmancey as this appears to be a client-side change, should we test with both `staging` & `production`, i.e.:

Staging:
`--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true`

Production:
`--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-debug`

Thanks!

**Comment by tmancey** [comment]
@stephendonner Testing with only one of these environments would be fine.

**Comment by stephendonner** [comment]
Verified on macOS using the inline testplan here, on


Brave | 1.20.90 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

<img width="936" alt="Screen Shot 2021-01-27 at 12 23 53 PM" src="https://user-images.githubusercontent.com/387249/106044512-ae433b00-6094-11eb-8e40-9e88b1fa755d.png">

I launched Dev with `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5`, went into `brave://rewards` to change 
 "Maximum number of ads displayed" to "1 ad per hour", got an ad, then set the system clock ahead by 45 minutes, waited the duration (while browsing/testing), and only received a single ad.
