### ISSUE TITLE
Rewards onboarding double overlay fix

### ISSUE THREAD

**Issue by codybanxs** [brave/brave-browser#13423]
## Description 
Currently if a user opens the rewards panel and dismisses the global overlay, a smaller opt-in UI is then also triggered underneath it to expose the same messaging again. 

## Steps to Reproduce

   1. Open a clean browser install or upgrade with Rewards off
   2. Tap the Rewards panel to see the global Rewards opt-in overlay
   3. Dismiss the overlay and you will see a second dialog box with almost the same messaging
   4. Closing that dialog will then show the full panel

## Actual result:
<img width="1201" alt="Screen Shot 2021-01-07 at 10 34 26 AM" src="https://user-images.githubusercontent.com/61210652/103930668-f7c2ea80-50d3-11eb-869d-aaebfccb5863.png">

## Expected result:
<img width="1455" alt="Screen Shot 2021-01-07 at 10 03 02 AM" src="https://user-images.githubusercontent.com/61210652/103930682-fc879e80-50d3-11eb-8c0c-8ea736c64243.png">

## Android Device details:
   - Install type (ARM, x86): Arm
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version: Nightly 1.20.60

**Comment by deeppandya** [comment]
@anthonypkeane @bsclifton where should we land this ? it's merged to 1.20 for now.

**Comment by bsclifton** [comment]
@deeppandya I think 1.20 works - we're pretty close to verifying 1.19
cc: @kjozwiak @LaurenWags just in case we did want this in 1.19

**Comment by LaurenWags** [comment]
1.20.x sounds good to me 👍🏻

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.85 x64 beta build
- Verified second onboarding overlay is not shown when the global onboarding is dismissed 

https://user-images.githubusercontent.com/17010094/105689465-b5cade80-5ef2-11eb-9bae-c6b9c4dd4d26.mp4


----------
Verification passed on Samsung Tab A with Android 10 running 1.20.85 x64 beta build
- Verified second onboarding overlay is not shown when the global onboarding is dismissed 

https://user-images.githubusercontent.com/17010094/105689582-d72bca80-5ef2-11eb-8360-4c9589bbe194.mp4
