### ISSUE TITLE
High memory consumption from Crypto Wallets

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#13438]
## Steps to Reproduce
   1. Clean profile, install crypto wallets
   2. Pre account creation, import, note relatively low memory usage of the Crypto Wallets extension (<=100mb)
   3. Create an account

## Actual result:
   4. On the seed phrase recovery screen, note the very high memory usage (>=550mb)
   5. Note the continued high memory usage while using the extension, with spikes up after unlocking
![image (1)](https://user-images.githubusercontent.com/8732757/104033447-c5c18f00-518c-11eb-8d80-09321b35cfba.png)

## Expected result:
Much more reasonable memory usage
<img width="815" alt="Screen Shot 2021-01-07 at 8 18 13 PM" src="https://user-images.githubusercontent.com/8732757/104033517-da9e2280-518c-11eb-8b46-96ac6111c5d0.png">    

## Reproduces how often: 
100%

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.89 Chromium: 88.0.4324.96 (Official Build) beta (64-bit)
-- | --
Revision | `68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}`
OS | Linux
Component | `1.0.22 Dev`

- Verified memory usage is low compared to before
![image](https://user-images.githubusercontent.com/17010094/105885565-35df6a00-6001-11eb-8ee2-edc61e4cf34c.png)

-----
Verification passed on 

Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2009 (Build 19042.746)
Component | `1.0.22 Dev`

- Verified memory usage is low compared to before
![image](https://user-images.githubusercontent.com/17010094/105884870-53600400-6000-11eb-98ae-3b989ff95be0.png)

--------
Verification passed on 

Brave | 1.21.21 Chromium: 88.0.4324.96 (Official Build) nightly (x86_64)
-- | --
Revision | `68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.22 Dev`

- Verified memory usage is low compared to before
![image](https://user-images.githubusercontent.com/17010094/105886199-01b87900-6002-11eb-80fc-af69738d055a.png)
-------

Logged #13774 as a follow-up for investigation
