### ISSUE TITLE
Drop "default" brave shield content setting to avoid confusion and NOTREACHED().

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#13445]
Since we don't have any global toggles for brave shield, the corresponding content setting matching *,* shouldn't exist. And if it exists, it is safe to erase it.

**Comment by LaurenWags** [comment]
@iefremov @bsclifton what should QA follow for a test plan for this one? Marking as `QA/Blocked` until this is decided 👍🏻

**Comment by iefremov** [comment]
@LaurenWags I reckon this is QA/No, since we migrated normally

**Comment by iefremov** [comment]
btw it is in 1.19.x

**Comment by LaurenWags** [comment]
gotcha, thanks @iefremov 

fyi @kjozwiak

**Comment by bsclifton** [comment]
Updated milestone to 1.19 the first release, since this was part of Chromium 88 😄
