### ISSUE TITLE
Update NTP background images for 2020/2021

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#13447]
## Description 

Update NTP background images for 2020/2021

## Designs
<img width="606" alt="Screen Shot 2020-11-11 at 6 21 09 PM" src="https://user-images.githubusercontent.com/2388823/98887360-b226d000-244a-11eb-86a8-8e6153ca10fe.png">

## Assets
[WEBP in our GDrive](https://drive.google.com/drive/folders/11pvUJSMgcY2JPUCVIqxpqASPNqGuT4kx)

photo creds + links
[2020-10 photo attribution and license.pdf](https://github.com/brave/brave-browser/files/5527720/2020-10.photo.attribution.and.license.pdf)

## Test plan
Images should match those shown in our GDrive

**Comment by deeppandya** [comment]
@anthonypkeane @bsclifton where should we land this ? it's merged to 1.20 for now.

**Comment by anthonypkeane** [comment]
Lets discuss with @kjozwiak tomorrow on the triage.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.20 x64 Beta build
- Verified new NTP images are loaded on each new tab
- Verified image credit link opens when tapped on photo credit
- Logged #13717 for missing credit for `Corwin Prescott`

  <details>
  <Summary>Screenshots</summary>

  Spence Moore (Ocean) | Spencer Moore (Lake) | Spencer Moore (Fern) | Spencer Moore (Desert) | Andrea Benz
  -- | -- | -- | -- | --
  ![image](https://user-images.githubusercontent.com/17010094/105474898-b1a28500-5c96-11eb-9244-72c0189ef375.png) | ![image](https://user-images.githubusercontent.com/17010094/105474877-a9e2e080-5c96-11eb-9756-26c475f29ba9.png) | ![image](https://user-images.githubusercontent.com/17010094/105474856-a18aa580-5c96-11eb-9bcd-97a0cd4ad308.png) | ![image](https://user-images.githubusercontent.com/17010094/105474841-9afc2e00-5c96-11eb-858b-897fee49425f.png) | ![image](https://user-images.githubusercontent.com/17010094/105475186-047c3c80-5c97-11eb-8f20-0f39f4e5eee5.png)

  Corvin Prescott (Olympic) | Corvin Prescott (Crestone) | Corvin Prescott (Canyon) | Corvin Prescott (Beach) | Su San Lee
  -- | -- | -- | -- | --
  ![image](https://user-images.githubusercontent.com/17010094/105475417-44432400-5c97-11eb-94ce-29aa9b8f4a3c.png) | ![image](https://user-images.githubusercontent.com/17010094/105475388-3a212580-5c97-11eb-9690-947cdc6af4d0.png) | ![image](https://user-images.githubusercontent.com/17010094/105475345-2d043680-5c97-11eb-8f26-0e3bcf247124.png) | ![image](https://user-images.githubusercontent.com/17010094/105475264-15c54900-5c97-11eb-8715-2bb2818b12fb.png) | ![image](https://user-images.githubusercontent.com/17010094/105475040-d7c82500-5c96-11eb-988f-054f54222c58.png)

  Dylan Malval (Sea) | Dylan Malval (Alps) | Sora Sango | Alex Plesovskich | Zane Lee
  -- | --| -- | -- | -- 
  ![image](https://user-images.githubusercontent.com/17010094/105475597-6e94e180-5c97-11eb-8cdd-665fb4cee8dc.png) | ![image](https://user-images.githubusercontent.com/17010094/105475560-650b7980-5c97-11eb-9fde-8f367182ff35.png) | ![image](https://user-images.githubusercontent.com/17010094/105473973-a4d16180-5c95-11eb-8dda-113a984f5067.png) | ![image](https://user-images.githubusercontent.com/17010094/105475096-e7476e00-5c96-11eb-9554-22389c790f61.png) | ![image](https://user-images.githubusercontent.com/17010094/105475061-ddbe0600-5c96-11eb-958f-e98e733936b2.png)
