### ISSUE TITLE
Flags indicated new update to chromium. 141 is not what I'm using? 

### ISSUE THREAD

**Issue by Hamburger6** [brave/brave-browser#13453]
He

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by eljuno** [comment]
Check the Chromium version via `brave:version` or Menu > Settings > About Brave.

Version shown on flags page is Chromium + Brave version. e.g. `87.1.18.77` mean Chromium 87.x.x.x and Brave 1.18.77

**Comment by Hamburger6** [comment]
Thanks for the reply. I'm good but why would chrome flags say that on its page?  I updated the webkit on my phone 2 days ago.?
