### ISSUE TITLE
Use different port for tor process in different channels

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#1345]
It uses [9050](https://github.com/brave/brave-core/blob/03772115c9995b04dba1ce37b9c88f0dc59c31a8/browser/tor/tor_profile_service.cc#L29) for all channels for now. 
And we have to avoid conflicts with ports in [browser-laptop](https://github.com/brave/browser-laptop/blob/faff16aa129bbfcc26d0c93ec2e35ade32086f66/app/channel.js#L66)

**Comment by darkdh** [comment]
use `version_info::chrome::GetChannel()` to detect which channel you are currently built with and register different port for `tor::prefs::kTorProxyString`

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux


```
Oct 11 13:56:15.905 [notice] Tor 0.3.3.8 (git-99f9816efa08ab83) running on Linux with Libevent 2.1.8-stable, OpenSSL 1.0.2o, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Oct 11 13:56:15.905 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Oct 11 13:56:15.905 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Oct 11 13:56:15.909 [notice] Scheduler type KIST has been enabled.
Oct 11 13:56:15.909 [notice] Opening Socks listener on 127.0.0.1:9360
Oct 11 13:56:15.909 [notice] Opening Control listener on 127.0.0.1:0
Oct 11 13:56:15.909 [notice] Control listener listening on port 42069.
```
