### ISSUE TITLE
Privacy report color issue on dark theme

### ISSUE THREAD

**Issue by georapbox** [brave/brave-browser#13455]
## Description 

When opening Privacy Report panel with dark theme enabled (browser's theme se to dark manually while the OS theme is set to light), the color of the blocked trackers/ads list is dark on dark background, therefore not readable.

## Steps to reproduce 

   1. Set OS theme to light
   2. Set browser's theme to dark
   3. Open a new tab page
   4. Tap on Privacy stats widget to open the Privacy report panel

## Actual result 

The color of the trackers/ads list is dark on a dark background.

![Screenshot_20210109-212251](https://user-images.githubusercontent.com/6596039/104109627-8e5ff900-52d8-11eb-904f-c5005659ff06.png)

## Expected result

The color of the trackers/ads list should be light to have adequate contrast with the dark background.

## Issue reproduces how often 

Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? **YES**
- Can you reproduce this issue with the current Play Store Beta version? **YES**
- Can you reproduce this issue with the current Play Store Nightly version? **YES**

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone Motorola One (XT1941-4)
   - Android version: 10
   
## Brave version
- Brave 1.18.77
- Brave - Nightly 1.20.68

### Additional information

To reproduce the issue, the Privacy Report must be enabled in Settings and Privacy Stats must be enabled on the widget that sits on the New Tab Page.

**Comment by srirambv** [comment]
Can't repro it on current PlayStore build
<img width=250 src=https://user-images.githubusercontent.com/17010094/104285148-15fd6180-54ab-11eb-9fb2-e5d97e98c731.png>

Is the browser theme set to dark manually or is it system default?

**Comment by georapbox** [comment]
The browser's theme is set to dark manually, while the OS theme is set to light. If I set the browser's theme to follow the OS theme then it works as expected. Sorry for this omission in my description; updating now.

**Comment by georapbox** [comment]
I just found out that the opposite is happening if you set the browser's theme to light and the OS theme to dark. Text becomes light on ight background.

![Screenshot_20210112-102725](https://user-images.githubusercontent.com/6596039/104289011-48b25480-54c1-11eb-8a7d-a11ee06e2c85.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using Android 9, Google Pixel XL, arm64 with Brave `1.25.51`

Steps:
1. set Android theme via `Settings` > `Display` > `Advanced` > `Device theme` to `Dark`
2. set Brave's theme to `Light` via `Settings` > `Appearance` > `Theme` > `(o) Dark`
3. opened `buzzfeed.com` and tapped on `View full Privacy Report ->`
4. confirmed the text under `Websites`, and `Trackers` were legible
5. repeated the above with the other permutations of `Dark` and `Light` with each, both OS and Brave

example | example 
---------|---------
![Screenshot_20210505-152701](https://user-images.githubusercontent.com/387249/117218410-ec4cab00-adb7-11eb-8a7a-924757023945.png) | ![Screenshot_20210505-152906](https://user-images.githubusercontent.com/387249/117218412-ece54180-adb7-11eb-87eb-62f85d3465fc.png)
