### ISSUE TITLE
Too much lag on Trisquel 8.0

### ISSUE THREAD

**Issue by AirSThib** [brave/brave-browser#13458]
Hey !

I really like the Brave browser but, because I installed it today, I noticed much lag, too much. So I don't know how to reduce it. I'm on Trisquel 8.0 Flidas using GNOME 3.0.

Thanks.

**Comment by ryanbr** [comment]
Hi @AirSThib 

I haven't tested this, but I see a newer version [9.0 LTS is available](https://trisquel.info/en/download). 

If you update Trisquel and ensure you're using the latest version of Brave `Version 1.18.78` installed

**Comment by bsclifton** [comment]
@AirSThib do you have more information? Are you seeing lag on particular websites? or is the UI itself slow? More info appreciated 😄

**Comment by AirSThib** [comment]
No, I don't know why, but for 1 week I don't have bugs now. No particular websites was. Only when I changed the size of the window, the browser was inupdating without hide/show.

**Comment by bsclifton** [comment]
OK interesting- I'm going to close this issue for now... but @AirSThib please re-open if you experience the problem again and have some steps we can follow to try and reproduce. Thanks 😄
