### ISSUE TITLE
Can't share screen in Google Meet

### ISSUE THREAD

**Issue by LorisTecnology** [brave/brave-browser#13469]
## Description 
I can't share my screen in Google meet

## Steps to Reproduce

   1. Open a Google meet
   2. Click the "screen share"

## Actual result:
"screen share is not supported"

## Expected result:
Screen been shared

## Reproduces how often: 
Everytime

## Brave version (brave://version info)
Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (a 64 bit)

**Comment by wslyvh** [comment]
I have the same issue.

Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)
MacOS Big Sur version 11.1 (20C69)

![image](https://user-images.githubusercontent.com/25974464/104218362-eb74bf80-543c-11eb-98bc-80aa0160f290.png)

**Comment by LorisTecnology** [comment]
I've found out how to make it work
Go in Extensions and enable Hangouts

**Comment by bsclifton** [comment]
Thanks for sharing what worked for you @LorisTecnology - can you try this too, @wslyvh?

**Comment by wslyvh** [comment]
Not sure which extension to enable. 
Do you mean to install/enable this Hangout extension? https://chrome.google.com/webstore/detail/google-hangouts/nckgahadagoaajjgafhacjanaoiihapd

**Comment by LorisTecnology** [comment]
![image](https://user-images.githubusercontent.com/63395247/104431439-2c2d1f80-5588-11eb-9a2b-919597605f22.png)
Is under settings

**Comment by wslyvh** [comment]
Cool. That works for me as well! Thanks
