### ISSUE TITLE
Implement promoted content ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#13468]

**Comment by btlechowski** [comment]
`QA/Blocked` till problem with staging env is resolved

**Comment by btlechowski** [comment]
Removed `QA/Blocked` as the staging env issue has been resolved

**Comment by LaurenWags** [comment]
Per discussion with @jsecretan , testing of this will be basic checks. I have also marked as `release-notes/exclude` for now. cc @rebron @kjozwiak

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.21.70 Chromium: 89.0.4389.69 (Official Build) (64-bit)
-- | --
Revision | 6df9174a477a0bea2118cb4669954d517be16104-refs/branch-heads/4389@{#1332}
OS | Ubuntu 18.04 LTS

Verification is done in https://github.com/brave/brave-browser/issues/13695#issuecomment-788301193
