### ISSUE TITLE
IPFS resolve type of disabled should disable

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13472]
## Steps to Reproduce

   1. Navigate to brave://settings/?search=ipfs
   2. Set the Method to resolve IPFS resources to Disabled

## Actual result:

It loads ipfs:// scheme resources through the gateway

## Expected result:

It should not load ipfs:// scheme resources

## Reproduces how often: 

Always

## Desktop Brave version:

All where IPFS is available (1.19.x and up)

## Version/Channel Information:

1.19.x and up

**Comment by yrliou** [comment]
Close this one as this has been resolved by uplifting https://github.com/brave/brave-core/pull/7307.
Original issue: https://github.com/brave/brave-browser/issues/12978.
