### ISSUE TITLE
unable to open custom ads on Windows Surface

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13477]
## Description 

If you use a Windows Surface device you will be unable to open a custom ad by tapping on it. I tried tapping on the title, on the body, pretty much any place that was not the "x" to dismiss the ad. Although tapping on the "x" to dismiss the ad does work. 

Doesn't matter if I used the stylus or my finger, I was unable to open the ad. 

## Steps to Reproduce

   1. Install Nightly on Windows Surface device
   2. Enable ads
   3. Browse until you get an ad
   4. Try tapping on the ad/using stylus

## Actual result:

Unable to open the ad from the custom notification no matter where you tap with your finger or stylus.

## Expected result:
Able to open the ad

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.20.72

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a 
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @lukemulks @tmancey

**Comment by tmancey** [comment]
@LaurenWags, @lukemulks has confirmed this is now working as expected. Thanks

**Comment by LaurenWags** [comment]
@tmancey since this can't be tested on Beta/Dev with 1.21.x as custom ads are tied to Nightly, should it be checked on Nightly 1.22.x or should it be changed to `QA/No`?

**Comment by tmancey** [comment]
@LaurenWags Ah yes this should be checked on nightly as custom ads are locked to nightly for now

**Comment by LaurenWags** [comment]
I can only open the custom ads on the Windows Surface if I use the trackpad. Using my finger or the stylus doesn't open the ad when touched/tapped on. However, as before, tapping/touching the "x" closes the ad.

Used 1.22.25 Nightly on Windows Surface w/ Win 10 Home.

@lukemulks can you confirm if tapping the stylus or your finger to open the ad works?

**Comment by tmancey** [comment]
Blocked as likely fixed by https://github.com/brave/brave-browser/issues/13137

**Comment by tmancey** [comment]
Closing issue as will be fixed by https://github.com/brave/brave-browser/issues/13137
