### ISSUE TITLE
Github inline tipping buton is removed/re-added when checkbox is clicked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13470]
## Description 

GH inline tipping buton is removed when content state is change even though there is no page reload

## Steps to Reproduce

   1. Open any issue with checkbox on GH
   2. Ensure Tip button is shown for the content creator(issue author)
   3. Click on any checkbox to change the state, tip button is removed and readded even though page is not reloaded

## Actual result:

https://user-images.githubusercontent.com/17010094/104184983-3a563100-540c-11eb-9dac-74099b79d746.mp4

## Expected result:
Content change should not remove/readd the tip button. Should just show the inline tip button for the issue creator

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)
-- | --
Revision | `9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @zenparsing @emerick @brave/legacy_qa

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build & component:

```
Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2009 (Build 19042.746)
```

![image](https://user-images.githubusercontent.com/2602313/105946492-5f19ed80-6035-11eb-960e-5248c99c3eef.png)

#### `Test Case 1` (default settings)

* launched `1.19.86 CR: 88.0.4324.96` and didn't enable ads/AC (default settings when launching a new profile)
* visited https://github.com/brave/brave-browser/issues/13785 & selected/deselected several checkboxes and ensured that the `Tip` icon didn't disappear/re-appear
* ensured that clicking the `Tip` icon after checking/deselecting several checkboxes launched the correct banner

**`Example`** | **`Example`**
---------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/105946655-adc78780-6035-11eb-9d6e-9315311e1530.png) | ![image](https://user-images.githubusercontent.com/2602313/105946730-d0f23700-6035-11eb-994f-3ebca304f62f.png)

#### `Test Case 2` (Logged into KYC/Verified account)

* launched `1.19.86 CR: 88.0.4324.96` and logged into my Uphold KYC/Verified account
* visited https://github.com/brave/brave-browser/issues/13785 & selected/deselected several checkboxes and ensured that the `Tip` icon didn't disappear/re-appear
* ensured that clicking the `Tip` icon after checking/deselecting several checkboxes launched the correct banner
* ensured that tipping worked as expected

**`Example`** | **`Example`** | **`Example`**
---------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/105947110-88874900-6036-11eb-99be-a38951c77ad7.png) | ![image](https://user-images.githubusercontent.com/2602313/105947173-a5bc1780-6036-11eb-9d5f-27092a244b81.png) | ![image](https://user-images.githubusercontent.com/2602313/105947222-c2584f80-6036-11eb-8d7a-a8fde3a809ff.png)

#### `Test Case 3` (upgrading components)

* launched `1.19.86 CR: 88.0.4324.96` and didn't enable ads/AC (default settings when launching a new profile)
* ensured that `Brave Local Data Updater - Version: 1.0.41` was being used

![image](https://user-images.githubusercontent.com/2602313/105947486-2ed34e80-6037-11eb-95c9-fa41d746db0f.png)

* visited https://github.com/brave/brave-browser/issues/13785 & selected/deselected several checkboxes and reproduced the original issue as per https://github.com/brave/brave-browser/issues/13470#issue-783350781.
* launched Brave is  `1.19.86 CR: 88.0.4324.96` using `--use-dev-goupdater-url` and ensured `Brave Local Data Updater` was updated to `Version: 1.0.44`

![image](https://user-images.githubusercontent.com/2602313/105947777-bae57600-6037-11eb-82e6-069a811cc5e5.png)

* visited https://github.com/brave/brave-browser/issues/13785 and ensured that the original issue wasn't reproducible

**Comment by kjozwiak** [comment]
@emerick there's still some issues with the above. After a few selects/deselects, you'll get the following:

![image](https://user-images.githubusercontent.com/2602313/105947864-f08a5f00-6037-11eb-91a8-20466a2af592.png)

The Twitter button starts disappearing after a few selects/deselects. Doesn't seem like this was fixed :(

**Comment by LaurenWags** [comment]
@emerick I reproduced @kjozwiak comment from https://github.com/brave/brave-browser/issues/13470#issuecomment-768045064 - page refresh fixes it. Definitely sounds like https://github.com/brave/brave-browser/issues/12900 as we previously discussed 👍🏻
