### ISSUE TITLE
Move browser/brave_cosmetic_resources_tab_helper.cc to components

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#13473]
## Description 

Move it there as it more belongs to components

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bridiver** [comment]
no longer relevant
