### ISSUE TITLE
Rewards onboarding string changes

### ISSUE THREAD

**Issue by codybanxs** [brave/brave-browser#13488]
## Description 
Any user who views the onboarding will see the string changes.

- Keep the name "Brave Private Ads" consistent throughout
- Reword the description for "What you can do with tokens"
- Update the title of "Wooohooo!" to "Woohoo, you're all set!"

## Assets:
<img width="1105" alt="Screen Shot 2021-01-11 at 5 40 02 PM" src="https://user-images.githubusercontent.com/61210652/104258324-26262a00-5434-11eb-87cd-e04c8ae146c7.png">
https://www.figma.com/file/0dbMYs8Wp8W3RgrG1yTdki/RE-1.0?node-id=99%3A0

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` per discussion with @codybanxs (updates to figma coming for QA to check against).

**Comment by codybanxs** [comment]
Rewards settings onboarding 'wideview' with the current copy + changes addressed in the issue details above. 
![wide view onboarding slides@3x](https://user-images.githubusercontent.com/61210652/106318738-335d5a00-6225-11eb-9139-5a0104470609.png)

**Comment by LaurenWags** [comment]
Update - confirming wide and narrow view text/image expectations with @codybanxs - will unblock QA once we sort this out 👍🏻

**Comment by codybanxs** [comment]
Following up with the large format onboarding above, **the panel view screens below supersedes the original text changes 
 with updated title strings.**
<img width="1418" alt="Screen Shot 2021-02-01 at 12 41 04 PM" src="https://user-images.githubusercontent.com/61210652/106516101-70c32100-648b-11eb-9a69-de9835d7724d.png">

**Comment by LaurenWags** [comment]
Note - question mark missing on 3rd slide in https://github.com/brave/brave-browser/issues/13488#issuecomment-770003770, logged https://github.com/brave/brave-browser/issues/13876 for this. 
Also, per discussion with @codybanxs on the final slide of the tour in 1.20.x there is a comma in the title "Woohoo, you're all set!" that is not in the designs (https://github.com/brave/brave-browser/issues/13488#issuecomment-770003770). This is ok and the comma should be included.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.20.96 Chromium: 88.0.4324.96 (Official Build) beta (x86_64)
Revision	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS	macOS Version 10.15.7 (Build 19H15)
```

Verified as part of https://github.com/brave/brave-browser/issues/12459#issuecomment-771863129

------------
