### ISSUE TITLE
Follow up issue for P3A

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#13486]
## Description 
This is the follow up issue of https://github.com/brave/brave-browser/issues/12723 to make p3a enabled by default.

## Test plan
P3A should be enabled for new users and existing user if user dismisses the full screen modal.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.100 x64 build
- Verified on a clean install, P3A is enabled by default 
- Verified unchecking P3A and background the app disables the setting
- Verified on an upgrade profile user is prompted for P3A right after install-launch
- Verified P3A is enabled by default for upgrade profile as well
---------
Verification passed on Samsung Tab A with Android 10 running 1.20.100 x64 build
- Verified on a clean install, P3A is enabled by default 
- Verified unchecking P3A and background the app disables the setting
- Verified on an upgrade profile user is prompted for P3A right after install-launch
- Verified P3A is enabled by default for upgrade profile as well
