### ISSUE TITLE
Cannot edit word documents online in sharepoint interface

### ISSUE THREAD

**Issue by coinzdude** [brave/brave-browser#13483]
## Description 
Brave Nightly, Windows 10, editing word doc online in sharepoint, crashes sharepoint page. Brave Release is fine.

![image](https://user-images.githubusercontent.com/58857646/104232818-de48d800-541e-11eb-9b94-a9b6580bc540.png)

JS errors in browser:
`
Failed to load resource: the server responded with a status of 400 ()
webshell.suite.office.com/api/theme/tenant?useDarkMode=undefined:1 Failed to load resource: the server responded with a status of 400 ()
wordeditorframe.aspx?ui=en-US&rs=en-US&wopisrc=https%3A%2F%2Fpmgnet.sharepoint.com%2Fsites%2FProduct%2F_vti_bin%2Fwopi.ashx%2Ffiles%2F53d2042113664ff1b84191e66992f26e&wdenableroaming=1&mscc=1&hid=DB53A09F-30FD-0000-9026-87E6B9AA4E5C&wdorigin=Other&jsapi=1&jsapiver=v1&newsession=1&corrid=b64c25c4-0dac-46bc-8f17-216ddfb7185a&usid=b64c25c4-0dac-46bc-8f17-216ddfb7185a&sftc=1&instantedit=1&wopicomplete=1&wdredirectionreason=Unified_SingleFlush&rct=Medium&ctp=LeastProtected:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
VM11:37 TypeError: Cannot read property 'message' of null
    at <anonymous>:27:31
window.console.error @ VM11:37
lq @ WordEditor.js:680
(anonymous) @ MicrosoftAjax.js:5
wac_bna @ WordEditor.js:754
lq @ WordEditor.js:752
(anonymous) @ MicrosoftAjax.js:5
error (async)
wac_uia @ WordEditor.js:749
wac_6f @ WordEditor.js:537
Type.initializeBase @ MicrosoftAjax.js:5
wac_Cv @ WordEditor.js:2910
Type.initializeBase @ MicrosoftAjax.js:5
wac_IFb @ WordEditor.js:6386
Type.initializeBase @ MicrosoftAjax.js:5
wac_6O @ WordEditor.js:6745
Oa @ WordEditor.js:6752
Hc @ WordEditor.js:2861
Hc @ WordEditor.js:6361
window.WordEditor.App.wac_M.Ba @ WordEditor.js:6683
(anonymous) @ wordeditorframe.aspx?ui=en-US&rs=en-US&wopisrc=https%3A%2F%2Fpmgnet.sharepoint.com%2Fsites%2FProduct%2F_vti_bin%2Fwopi.ashx%2Ffiles%2F53d2042113664ff1b84191e66992f26e&wdenableroaming=1&mscc=1&hid=DB53A09F-30FD-0000-9026-87E6B9AA4E5C&wdorigin=Other&jsapi=1&jsapiver=v1&newsession=1&corrid=b64c25c4-0dac-46bc-8f17-216ddfb7185a&usid=b64c25c4-0dac-46bc-8f17-216ddfb7185a&sftc=1&instantedit=1&wopicomplete=1&wdredirectionreason=Unified_SingleFlush&rct=Medium&ctp=LeastProtected:23
setTimeout (async)
initApp @ wordeditorframe.aspx?ui=en-US&rs=en-US&wopisrc=https%3A%2F%2Fpmgnet.sharepoint.com%2Fsites%2FProduct%2F_vti_bin%2Fwopi.ashx%2Ffiles%2F53d2042113664ff1b84191e66992f26e&wdenableroaming=1&mscc=1&hid=DB53A09F-30FD-0000-9026-87E6B9AA4E5C&wdorigin=Other&jsapi=1&jsapiver=v1&newsession=1&corrid=b64c25c4-0dac-46bc-8f17-216ddfb7185a&usid=b64c25c4-0dac-46bc-8f17-216ddfb7185a&sftc=1&instantedit=1&wopicomplete=1&wdredirectionreason=Unified_SingleFlush&rct=Medium&ctp=LeastProtected:23
pageInit @ wordeditorframe.aspx?ui=en-US&rs=en-US&wopisrc=https%3A%2F%2Fpmgnet.sharepoint.com%2Fsites%2FProduct%2F_vti_bin%2Fwopi.ashx%2Ffiles%2F53d2042113664ff1b84191e66992f26e&wdenableroaming=1&mscc=1&hid=DB53A09F-30FD-0000-9026-87E6B9AA4E5C&wdorigin=Other&jsapi=1&jsapiver=v1&newsession=1&corrid=b64c25c4-0dac-46bc-8f17-216ddfb7185a&usid=b64c25c4-0dac-46bc-8f17-216ddfb7185a&sftc=1&instantedit=1&wopicomplete=1&wdredirectionreason=Unified_SingleFlush&rct=Medium&ctp=LeastProtected:24
(anonymous) @ MicrosoftAjax.js:5
_raiseInit @ MicrosoftAjax.js:5
initialize @ MicrosoftAjax.js:5
(anonymous) @ WordEditor.js:7750
WordEditor.box4.dll1.js:3331 Uncaught (in promise) null
(anonymous) @ WordEditor.box4.dll1.js:3331
(anonymous) @ WordEditor.box4.dll1.js:373
(anonymous) @ WordEditor.js:4080
wac_rG @ WordEditor.js:4070
wac_heb @ WordEditor.js:4080
wac_ieb @ WordEditor.js:4080
wac_jeb @ WordEditor.js:4080
wac_keb @ WordEditor.js:4080
(anonymous) @ WordEditor.js:4081
(anonymous) @ WordEditor.js:379
xl @ WordEditor.js:719
Af @ WordEditor.js:379
Af @ WordEditor.js:4090
wac_leb @ WordEditor.js:4081
wac_61b @ WordEditor.box4.dll1.js:72
wac_B4b @ WordEditor.box4.dll1.js:373
(anonymous) @ WordEditor.box4.dll1.js:3330
wac_VDc @ WordEditor.box4.dll1.js:3330
wac_TDc @ WordEditor.box4.dll1.js:3329
(anonymous) @ WordEditor.box4.dll1.js:3335
qp @ WordEditor.js:192
wac_Iba @ WordEditor.js:193
H @ WordEditor.js:188
(anonymous) @ WordEditor.box4.dll1.js:3334
qp @ WordEditor.js:192
wac_Iba @ WordEditor.js:193
H @ WordEditor.js:188
(anonymous) @ WordEditor.box4.dll1.js:3335
qp @ WordEditor.js:192
wac_Iba @ WordEditor.js:193
H @ WordEditor.js:188
(anonymous) @ WordEditor.box4.dll1.js:3336
qp @ WordEditor.js:192
wac_Iba @ WordEditor.js:193
H @ WordEditor.js:188
xb @ WordEditor.box4.dll1.js:3334
c @ WordEditor.js:1404
wac_dxa @ WordEditor.js:1404
wac_exa @ WordEditor.js:1405
(anonymous) @ WordEditor.js:1406
jy @ WordEditor.js:1201
(anonymous) @ MicrosoftAjax.js:5
vQa @ WordEditor.js:719
wac_9ta @ WordEditor.js:1214
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
oc @ WordEditor.js:1206
wac_Soa @ WordEditor.js:881
wac_Woa @ WordEditor.js:881
zca @ WordEditor.js:870
(anonymous) @ MicrosoftAjax.js:5
(anonymous) @ MicrosoftAjax.js:5
completed @ MicrosoftAjax.js:5
_onReadyStateChange @ MicrosoftAjax.js:5
XMLHttpRequest.send (async)
executeRequest @ MicrosoftAjax.js:5
executeRequest @ MicrosoftAjax.js:5
invoke @ MicrosoftAjax.js:5
ME @ WordEditor.js:869
wac_Noa @ WordEditor.js:887
Ch @ WordEditor.js:865
wac_AEa @ WordEditor.js:1942
MVc @ WordEditor.js:1939
dZb @ WordEditor.js:21
(anonymous) @ MicrosoftAjax.js:5
(anonymous) @ WordEditor.js:24
setTimeout (async)
wac_Aaa @ WordEditor.js:24
wac_Baa @ WordEditor.js:22
pJd @ WordEditor.js:21
wac_Aea @ WordEditor.js:386
wac_Wea @ WordEditor.js:398
vDa @ WordEditor.js:3351
(anonymous) @ MicrosoftAjax.js:5
jy @ WordEditor.js:1201
(anonymous) @ MicrosoftAjax.js:5
vQa @ WordEditor.js:719
wac_9ta @ WordEditor.js:1214
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
setTimeout (async)
wac_4ta @ WordEditor.js:1204
wac_rk @ WordEditor.js:1213
jy @ WordEditor.js:1208
(anonymous) @ MicrosoftAjax.js:5
Show 16 more frames
VM5059:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at _eventHandler (wachostwebpack.js:2)
_eventHandler @ wachostwebpack.js:2
OfficeExtensionManager.aspx?-24d5fcc7_-18b9604_1610395748743:80 Uncaught ReferenceError: _spBodyOnLoadFunctionNames is not defined
    at OfficeExtensionManager.aspx?-24d5fcc7_-18b9604_1610395748743:80
(anonymous) @ OfficeExtensionManager.aspx?-24d5fcc7_-18b9604_1610395748743:80
VM5085:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at _eventHandler (wachostwebpack.js:2)
_eventHandler @ wachostwebpack.js:2
suiteux.shell.tokenfactoryiframe.3532d5e47b6c96d9d21c.js:16 GET https://webshell.suite.office.com/api/theme/tenant?useDarkMode=undefined 400
`

## Steps to Reproduce
With Brave Nightly, Windows, from a sharepoint web site, browse to a MS Word document and use Sharepoint's built in document editor (in browser). 
The page will crash with error above and js errors thrown as well.  

## Actual result:
Screenshot above, JS errors above

## Expected result:
Document should load in browser, Brave release is fine.

## Reproduces how often: 
On demand

## Brave version (brave://version info)
Brave | 1.20.70 Chromium: 88.0.4324.79 (Official Build) nightly (64-bit)
-- | --
Revision | bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS | Windows 10 OS Version 2004 (Build 21286.1000)

## Version/Channel Information:
Only breaks on nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
 
- Does the issue resolve itself when disabling Brave Rewards? 
No

- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
If needed, I can try to share a document to be edited, privately.  Please contact me if needed.

**Comment by rebron** [comment]
@coinzdude Is this still an issue for you on Brave Nightly, it's on version 1.25.x now? You're not seeing this problem in the release version correct which is 1.23.71?

**Comment by coinzdude** [comment]
It's working! Thanks! 

Closing
