### ISSUE TITLE
Entire browser very blurry

### ISSUE THREAD

**Issue by josephgchdid** [brave/brave-browser#13496]
Updated radeon graphics driver to version 20.11.2, restarded my laptop, launched the browser and the enitre window became blurry, before the update the browser was working well, i dont know if its related or not, dont know how to fix the issue

![Screenshot 2021-01-12 134055](https://user-images.githubusercontent.com/69150939/104322573-c9874580-54ed-11eb-9e1e-d873b0693b9d.jpg)

**Comment by josephgchdid** [comment]
found the issue, for some reason radeon registered the browser as a game (???) and set the graphics to ultra low, setting them to ultra high seems to fix the issue

**Comment by bsclifton** [comment]
@josephgchdid perfect! Glad you were able to get sorted. Thanks for following up with what fixed the issue for you
