### ISSUE TITLE
Brave Talk onboarding modal persists on all new tabs unless dismissed via close button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13492]
## Description 

With new onboarding for Brave Together, the onboarding modal is only dismissed when you click on the `X` button. Even if you click on the together shortcut and start a video call and then open a second new tab Brave Together onboarding is still shown

## Steps to Reproduce

   1. Update to 1.20.73 to get Brave together onboarding on an NTP
   2. Click on the together button to start a video call
   3. Open a new tab, still keeps showing Brave Together onboarding and covers Rewards widget 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/104284330-bf435800-54a9-11eb-978f-4cfcdd9ddab3.png)

## Expected result:
Should dismiss onboarding if user clicks and starts a video call or navigates to a new tab

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.20.73 Chromium: 88.0.4324.79 (Official Build) nightly (64-bit)
-- | --
Revision | `bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA 
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @petemill @bsclifton

**Comment by karenkliu** [comment]
Thank you for filing this!

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.28.103 Chromium: 92.0.4515.131 (Official Build) (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/9616

**_Only shows after 3 days_**

now | after 3 days
-----|------------

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` until we get Brave Talk enabled on `main` (staging) via Griffin. After it's enabled on staging, QA will be able to run through the above verification. Once we get closer to Brave Talk release date, we'll push the same change into `production`.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-variations/pull/93 was merged into `main` (Griffin staging).

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

```

- ensured that Brave Talk widget was enabled via NTP on main (staging) after launching brave via the following:
`brave.exe --variations-server-url=https://variations.bravesoftware.com/seed`
- ensured that `BraveTalkStudy` is enabled via brave://version/?show-variations-cmd
![image](https://user-images.githubusercontent.com/38657976/128813325-096f0aa8-fa7a-41d1-a2df-f94f40aa6ae5.png)

- Verified the test plan from https://github.com/brave/brave-core/pull/9616
- ensured that the `BraveTalk` onboarding modal is shown in NTP when OS system clock is forwarded to 3days

now | after 3 days
-----|---------------
![image](https://user-images.githubusercontent.com/38657976/128813555-9d18444d-0894-4a08-890c-138e3857f27c.png) | ![image](https://user-images.githubusercontent.com/38657976/128813691-80a79cfe-78c3-4bdc-b70d-bc20e762244f.png)
