### ISSUE TITLE
Pull down reload changes monthly contribution page to tips page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13509]
## Description 
Pull down reload changes monthly contribution page to tips page

## Steps to reproduce 

   1. Visit `brave://rewards`
   2. Scroll down to Contribution details
   3. Pull down reload the page, switches to Tips 
   4. Go back page URL remains at `brave://rewards` but navigates back to Contribution
   5. Repeat same on Tips, navigates back to contribution with `brave://rewards` in URL

## Actual result 

https://user-images.githubusercontent.com/17010094/104344762-7d400380-54f5-11eb-895c-9a305c25a538.mp4

## Expected result
Page navigation should be proper and go back to previous page irrespective of being reloaded 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by anthonypkeane** [comment]
Updated Rewards UI should solve this.
