### ISSUE TITLE
Protect migration of Shields settings from unregistered preferences

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#13508]
## Description 

As suggested by @iefremov on Slack, it would be good to add some extra checking in `BravePrefProvider` to see if the name of the preference being migrated has been actually registered before going ahead with the logic implemented in `MigrateShieldsSettingsFromResourceIdsForOneType()`, otherwise we would get a crash as soon as we attempted to create an `prefs::ScopedDictionaryPrefUpdate` with the name found.

We already added protection for `"fingerprinting"` in `MigrateShieldsSettingsFromResourceIds()`, so this is unlikely to happen unless someone maliciously managed to modified the user preferences to inject an unregistered name in there, but still worth adding this extra check just in case anyway.

## Steps to Reproduce

1. Make sure Brave is not running
2. Manually modify your user preferences (e.g. `Default/Preferences`), maybe on a temporary profile, and add a new entry like the one below inside the `profile.content_settings.exceptions.plugins` dictionary:
```
  "profile": {
    [...]
    "content_settings": {
      "exceptions": {
        [...]
        "plugins": {
          "www.not-really-an-existing-url.com,*": {
            "expiration": "0",
            "last_modified": "13252624815101884",
            "model": 0,
            "per_resource": {
              "unknown_setting": 1
            }
          },
   [...]
```
3. Try to run Brave

## Actual result:
Brave crashes on startup with an error like the following one:
```
[1273689:1273689:0112/173326.587131:68451040682:FATAL:pref_service.cc(546)] Check failed: false. Trying to get an unregistered pref: profile.content_settings.exceptions.unknown_setting
```

## Expected result:
Brave runs just fine (i.e. no crashes)

## Reproduces how often: 
Always

## Brave version (info found on brave://version)
Brave 1.20.65 (based on Chromium Chromium 88.0.4324.51)

## Version/Channel Information:
- Currently reproducible on the nightly channel only

**Comment by iefremov** [comment]
@mariospr @rebron Just wanted to double-check: this marked as 1.20.x Beta, but the beta branch actually doesn't have the fix. Should we uplift?

**Comment by mariospr** [comment]
@iefremov I believe that this patch needs to be uplifted to 1.19.x and 1.20.x, but I'd rather loop in @mkarolin who knows better than me.

**Comment by kjozwiak** [comment]
@brave/legacy_qa you can create your own preference file using https://github.com/brave/brave-browser/issues/13508#issue-784397470 or use the one I already created via https://github.com/brave/brave-core/pull/7570#issuecomment-761118832.

Quick note, the `Preference` file from https://github.com/brave/brave-browser/issues/13508#issue-784397470 also includes the issue from https://github.com/brave/brave-browser/issues/13443.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.1 x64` using the following build:

```
Brave | 1.19.85 Chromium: 88.0.4324.89 (Official Build) (x86_64)
--- | ---
Revision | 4534be84786f5269fb52e9bf82643af61e2fedaf-refs/branch-heads/4324@{#1721}
OS | macOS Version 11.1 (Build 20C69)
```

* reproduced the crash using `1.21.3 CR: 88.0.4324.87` with the preference file from https://github.com/brave/brave-core/pull/7570#issuecomment-761118832
* verified that `1.19.85 CR: 88.0.4324.89` doesn't crash when upgrading from `1.18.78 CR: 87.0.4280.141` using the preference file from https://github.com/brave/brave-core/pull/7570#issuecomment-761118832.
