### ISSUE TITLE
Crypto Wallet/Greaselion should not be allowed to run on Private/Tor windows by default

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13506]
## Description 

Greaselion shouldn't have an option for `Allow in Private` under extension details since Rewards doesn't work on Private / Tor / Guest windows. Similarly Crypto Wallet should not be allowed to run in Private / Tor / Guest as well

## Steps to Reproduce

Greaselion
   1. Launch nightly with `--show-component-extenstion-options` 
   2. Open brave://extensions and go to details for any greaselion 
   3. `Allow in Private` option is available and enabled by default

Crypto Wallet
   1. Launch nightly with `--show-component-extenstion-options` 
   2. Open brave://wallet and install component 
   3. Go to brave://extensions and go to details for Crypto Wallet Component
   3. `Allow in Private` option is available and enabled by default

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/104337787-c3916480-54ed-11eb-9034-a343bd389769.png)

## Expected result:
Greaselion shouldn't have an option for `Allow in private` since Rewards isn't going to work on Private / Tor / Guest windows. Crypto Wallet shouldn't have `Allow in private` mode enabled by default

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.20.73 Chromium: 88.0.4324.79 (Official Build) nightly (64-bit)
-- | --
Revision | `bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by diracdeltas** [comment]
not sure if https://github.com/brave/brave-browser/issues/13279 is related, but would be good to fix that issue as well

**Comment by darkdh** [comment]
@diracdeltas #13279 will also be fixed

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Linux

- Verified Greaselion extensions don't have a `Allow in private` option
![image](https://user-images.githubusercontent.com/17010094/107024243-afb0e980-679f-11eb-84ff-02deef8c1585.png)
- Verified CryptoWallet extension has `Allow in private` disabled by default
![image](https://user-images.githubusercontent.com/17010094/107025612-9610a180-67a1-11eb-8d43-a1f000016ea2.png)
- Verified enabling `Allow in private` works as expected 
![image](https://user-images.githubusercontent.com/17010094/107025405-50ec6f80-67a1-11eb-8fa0-80121a1309ce.png)

---------
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Windows 10 OS Version 2009 (Build 19042.746)

- Verified Greaselion extensions don't have a `Allow in private` option
![image](https://user-images.githubusercontent.com/17010094/107028386-66639880-67a5-11eb-9ce0-ce0d0cd5139a.png)

- Verified CryptoWallet extension has `Allow in private` disabled by default
![image](https://user-images.githubusercontent.com/17010094/107028832-002b4580-67a6-11eb-9f13-f311686086ec.png)

- Verified enabling `Allow in private` works as expected 
![image](https://user-images.githubusercontent.com/17010094/107028961-2bae3000-67a6-11eb-9ece-9414d9dcc23c.png)


---------
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (x86_64)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | macOS Version 10.15.7 (Build 19H114)

- Verified Greaselion extensions don't have a `Allow in private` option
![image](https://user-images.githubusercontent.com/17010094/107026448-9d847a80-67a2-11eb-9aa7-aed80a034508.png)

- Verified CryptoWallet extension has `Allow in private` disabled by default
![image](https://user-images.githubusercontent.com/17010094/107026516-b856ef00-67a2-11eb-9dfd-c0e948fd1ea6.png)

- Verified enabling `Allow in private` works as expected 
![image](https://user-images.githubusercontent.com/17010094/107028254-374d2700-67a5-11eb-98a7-14d99d65c332.png)
