### ISSUE TITLE
Brave Talk tooltip isn't shown correctly

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13513]
## Description 

Brave Talk tooltip isn't shown correctly

## Steps to Reproduce

   1. Clean or upgraded profile 1.20.x nightly
   2. Open NTP 
   3. Verify the tooltips from the bottom right corner of the NTP

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/104354606-73d38d00-552f-11eb-9a2b-0bfa7d421843.png)

## Expected result:
The tooltip should be shown as `Brave Talk`

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.20.73 Chromium: 88.0.4324.79 (Official Build) nightly (64-bit)
-- | --
Revision | bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS | Windows 10 OS Version 2004 (Build 19041.685)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @karenkliu @rebron

**Comment by NumDeP** [comment]
You missed the `Together` label.

**Comment by nullhook** [comment]
This has been fixed here: https://github.com/brave/brave-core/pull/9307

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.28.51 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

```
- Verified STR from the description and ensured Brave Talk tooltip is shown correctly
![image](https://user-images.githubusercontent.com/38657976/124453693-401e4500-dda5-11eb-8939-a35b52e1bd41.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.28.51 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

```
- Verified the STR gfrom the description and ensured Brave Talk tooltip is shown correctly
![image](https://user-images.githubusercontent.com/38657976/124469878-8a5cf180-ddb8-11eb-9380-bfd47c6a440c.png)
