### ISSUE TITLE
Crash when trying to update Brave

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#13518]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.20.70  Chromium: 88.0.4324.79
Operating System: Windows NT 10.0.19042

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. I was on Nightly version 1.20
2. I checked for updates by visiting brave://settings/help
3. Update started to download
4. Usually, you'd be prompted to restart... but this never happened. It just crashed

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/400d0200-2a70-9005-0000-000000000000

**Comment by bsclifton** [comment]
May be Chromium 88 related? Not sure
cc: @mkarolin @iefremov @mariospr

**Comment by iefremov** [comment]
I guess we cannot do that much about it without any hints (i.e. stacktrace). Chrome has this problem as well...

**Comment by bsclifton** [comment]
OK will close and re-open if I'm able to have this happen again. No use in keeping open if there's not enough info to debug ☹️
