### ISSUE TITLE
Show a warning that some sites don't work over Tor

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1351]
## Description 

Show a warning that some sites don't work over Tor

## Steps to Reproduce

   1. Open Tor Window
   2. Visit a site and open shields
   3. No warning message that some sites dont work over Tor

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46246228-5adb5800-c3c8-11e8-8be8-4812b9258409.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/46246234-75adcc80-c3c8-11e8-9ac4-20894abd95f9.png)

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | All

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
moving to 1.x

**Comment by tomlowenthal** [comment]
This functionality is covered by the new tab page for Privacy Windows with Tor. I don't think we should target a separate Shields edit for this.
