### ISSUE TITLE
Update regions for search engine integrations

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#13511]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/13283
- [x] Add Ecosia for the following regions:
    - [x] Austria (AT)
    - [x] Denmark (DK)
    - [x] Luxembourg (LU)
    - [x] Norway (NO)
    - [x] Ireland (IE)
    - [x] Australia (AU)
    - [x] Spain (ES)
    - [x] Greece (GR)
    - [x] Italy (IT)
    - [x] Hungary (HU)
    - [x] Portugal (PT)
    - [x] Canada (CA)
    - [x] Finland (FI)
- [ ] Update wiki (https://github.com/brave/internal/wiki/Search-engine-integrations)

### Verify changes in the `Default search engines` list
1. Set locale to one of the supported locales (see list above)- for example CA
2. New profile
3. Launch Brave, go through onboarding to search engine step. Verify:
    - _Ecosia_ shows in list (should be towards the end)
4. Open brave://settings/searchEngines in a new tab. Verify:
    - _Ecosia_ shows in list (should be towards the end)

### Verify the Ecosia referral IDs used are correct
1. Do a search (on Android/Desktop) using Ecosia
2. Verify `tt=` part of URL fragment matches referral code shown in https://github.com/brave/internal/wiki/Search-engine-integrations

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.21.21 Chromium: 88.0.4324.96 (Official Build) nightly (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2009 (Build 19042.746)
```

Went through the following with the new regions motioned via https://github.com/brave/brave-browser/issues/13511#issue-784431631:

* ensured that `Yahoo` was removed and `Ecosia` was being added via the following area's:
  * `brave://welcome`, `brave://settings/search` & `brave://settings/searchEngines`
* ensured `Ecosia` uses the following formatting via `brave://settings/searchEngines`
  * `https://www.ecosia.org/search?tt=e8eb07a6&q=%s`
* ensured that `tt=e8eb07a6` is being appended to search queries from the omnibox/URL bar
* ensured `tt=e8eb07a6` isn't being appended if you're doing a search via `https://www.ecosia.org`
* ensured that you can set `Ecosia` as the default via the following:
  * `brave://welcome`, `brave://settings/search` & `brave://settings/searchEngines`

### `Clean Install`

<details>
<summary><b>Austria</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105526156-06062e80-5cb0-11eb-9f93-a306daa27382.png) | ![image](https://user-images.githubusercontent.com/2602313/105526256-233afd00-5cb0-11eb-9a1b-c22b86e3a837.png) | ![image](https://user-images.githubusercontent.com/2602313/105526303-36e66380-5cb0-11eb-8315-a24ebec7828a.png) | ![image](https://user-images.githubusercontent.com/2602313/105526325-406fcb80-5cb0-11eb-9d0b-26669ca2acba.png) | ![image](https://user-images.githubusercontent.com/2602313/105527190-5fbb2880-5cb1-11eb-8d0a-ec687874a18d.png)
</details>

<details>
<summary><b>Ireland</b></summary>

Ensured that `DDG` was the default search engine as per the following:

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105526438-6ac18900-5cb0-11eb-8fe6-09e59e6caafa.png) | ![image](https://user-images.githubusercontent.com/2602313/105526479-7a40d200-5cb0-11eb-949e-0f312e495fac.png) | ![image](https://user-images.githubusercontent.com/2602313/105526516-89278480-5cb0-11eb-885c-c4a219393205.png) | ![image](https://user-images.githubusercontent.com/2602313/105526539-917fbf80-5cb0-11eb-977a-be41bce005b6.png) | ![image](https://user-images.githubusercontent.com/2602313/105527075-3b5f4c00-5cb1-11eb-9371-8ab8e7ae8201.png)

</details>

<details>
<summary><b>Denmark</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105526682-bb38e680-5cb0-11eb-8663-53e3de9fb380.png) | ![image](https://user-images.githubusercontent.com/2602313/105526729-c8ee6c00-5cb0-11eb-9648-76459238c47c.png) | ![image](https://user-images.githubusercontent.com/2602313/105526769-d7d51e80-5cb0-11eb-9693-4dedaf305e02.png) | ![image](https://user-images.githubusercontent.com/2602313/105526813-e4597700-5cb0-11eb-95a6-67d4d93317e3.png)| ![image](https://user-images.githubusercontent.com/2602313/105526902-03f09f80-5cb1-11eb-9e92-f5839aecb489.png)
</details>

<details>
<summary><b>Luxembourg</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105527276-79f50680-5cb1-11eb-9bc3-797e1280dac1.png) | ![image](https://user-images.githubusercontent.com/2602313/105527316-89744f80-5cb1-11eb-8dfe-13ec184856f1.png) | ![image](https://user-images.githubusercontent.com/2602313/105527366-9a24c580-5cb1-11eb-8d5a-b0d4af937ef5.png) | ![image](https://user-images.githubusercontent.com/2602313/105527392-a4df5a80-5cb1-11eb-95c0-3ea8846bbf04.png) | ![image](https://user-images.githubusercontent.com/2602313/105527432-b3c60d00-5cb1-11eb-943f-ae2d260d9f79.png)
</details>

<details>
<summary><b>Norway</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105529041-cb05fa00-5cb3-11eb-95bf-fa2dcb3d5bd6.png) | ![image](https://user-images.githubusercontent.com/2602313/105529071-d822e900-5cb3-11eb-8d1a-df34b4cc244a.png) | ![image](https://user-images.githubusercontent.com/2602313/105529099-e5d86e80-5cb3-11eb-9397-8fb26c94759f.png) | ![image](https://user-images.githubusercontent.com/2602313/105529144-f688e480-5cb3-11eb-8a62-f1f473a7d669.png) | ![image](https://user-images.githubusercontent.com/2602313/105529175-043e6a00-5cb4-11eb-91b3-c0568de169c4.png)
</details>

<details>
<summary><b>Australia</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105541159-589e1580-5cc5-11eb-8d96-80c653e66fbd.png) | ![image](https://user-images.githubusercontent.com/2602313/105541174-605dba00-5cc5-11eb-846a-1809d722da27.png) | ![image](https://user-images.githubusercontent.com/2602313/105541216-70759980-5cc5-11eb-9516-115af200074f.png) | ![image](https://user-images.githubusercontent.com/2602313/105541240-7a979800-5cc5-11eb-86b7-2c31c7b1274b.png) | ![image](https://user-images.githubusercontent.com/2602313/105541280-86835a00-5cc5-11eb-9332-020666f3e70e.png)
</details>

<details>
<summary><b>Spain</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105541342-9bf88400-5cc5-11eb-9971-7f0c8b22b615.png) | ![image](https://user-images.githubusercontent.com/2602313/105541469-cf3b1300-5cc5-11eb-943c-2825643d53c4.png) | ![image](https://user-images.githubusercontent.com/2602313/105541518-de21c580-5cc5-11eb-9737-bd4984d01de9.png) | ![image](https://user-images.githubusercontent.com/2602313/105541540-e7ab2d80-5cc5-11eb-9283-819881f7bfac.png) | ![image](https://user-images.githubusercontent.com/2602313/105541585-fdb8ee00-5cc5-11eb-8fca-a29f3423cb77.png)
</details>

<details>
<summary><b>Greece</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105542359-3907ec80-5cc7-11eb-86b5-5a0091fa225a.png) | ![image](https://user-images.githubusercontent.com/2602313/105542387-4329eb00-5cc7-11eb-9e14-9ad5b5358ed6.png) | ![image](https://user-images.githubusercontent.com/2602313/105542417-4f15ad00-5cc7-11eb-8882-7e8f726eb6f4.png) | ![image](https://user-images.githubusercontent.com/2602313/105542442-589f1500-5cc7-11eb-8590-b36d9fc12803.png) | ![image](https://user-images.githubusercontent.com/2602313/105542521-710f2f80-5cc7-11eb-972f-aab3a3eac345.png)
</details>

<details>
<summary><b>Italy</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105543067-94d27580-5cc7-11eb-9283-d47c610e31f7.png) | ![image](https://user-images.githubusercontent.com/2602313/105543214-9d2ab080-5cc7-11eb-8fa4-afd5a07b8f53.png) | ![image](https://user-images.githubusercontent.com/2602313/105543326-a9af0900-5cc7-11eb-89a5-d97bfa7b0263.png) | ![image](https://user-images.githubusercontent.com/2602313/105543364-b4699e00-5cc7-11eb-94dd-9f592023fc4c.png) | ![image](https://user-images.githubusercontent.com/2602313/105543425-c4817d80-5cc7-11eb-97a4-30c4dc4f406d.png)
</details>

<details>
<summary><b>Hungary</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105543547-ed097780-5cc7-11eb-8635-064e691566f8.png) | ![image](https://user-images.githubusercontent.com/2602313/105543568-f98dd000-5cc7-11eb-9daa-d2d9e34ad804.png) | ![image](https://user-images.githubusercontent.com/2602313/105543616-08748280-5cc8-11eb-8a40-f6f6807de2e5.png) | ![image](https://user-images.githubusercontent.com/2602313/105545725-6dc97300-5cca-11eb-93e0-75077411de5f.png)
</details>

<details>
<summary><b>Portugal</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105546040-d7498180-5cca-11eb-9fd5-e128d246eaa5.png) | ![image](https://user-images.githubusercontent.com/2602313/105546061-e16b8000-5cca-11eb-9111-c917dc8b9e3e.png) | ![image](https://user-images.githubusercontent.com/2602313/105546100-f0eac900-5cca-11eb-99a8-ca4d1b75e046.png) | ![image](https://user-images.githubusercontent.com/2602313/105546126-f9db9a80-5cca-11eb-8916-f0c972f9f430.png) | ![image](https://user-images.githubusercontent.com/2602313/105546155-05c75c80-5ccb-11eb-9f16-6d041e36d433.png)
</details>

<details>
<summary><b>Canada</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105546247-242d5800-5ccb-11eb-9734-4baabab26d47.png) | ![image](https://user-images.githubusercontent.com/2602313/105546284-30191a00-5ccb-11eb-9724-d625279422f8.png) | ![image](https://user-images.githubusercontent.com/2602313/105546336-3ad3af00-5ccb-11eb-987f-b8469ea49f1b.png) | ![image](https://user-images.githubusercontent.com/2602313/105546354-41fabd00-5ccb-11eb-99ff-832ed00b260d.png) | ![image](https://user-images.githubusercontent.com/2602313/105546391-52ab3300-5ccb-11eb-9bc2-2b54d2bc2eda.png)
</details>

<details>
<summary><b>Finland</b></summary>

**`Region`** | **`Onboarding`** | **`Search Settings`** | **`Search Settings`** | **`Search`** 
-------------|---------------------|------------------------|------------------------|---------------
![image](https://user-images.githubusercontent.com/2602313/105546433-622a7c00-5ccb-11eb-934f-832b0616067f.png) | ![image](https://user-images.githubusercontent.com/2602313/105547036-11675300-5ccc-11eb-9a64-7604a5da7e51.png) | ![image](https://user-images.githubusercontent.com/2602313/105547071-1d531500-5ccc-11eb-8098-40b055200248.png) | ![image](https://user-images.githubusercontent.com/2602313/105547095-2643e680-5ccc-11eb-8b49-b62ad78c30f7.png) | ![image](https://user-images.githubusercontent.com/2602313/105547194-407dc480-5ccc-11eb-949d-c1bbc0770774.png)
</details>

**Comment by kjozwiak** [comment]
@brave/legacy_qa because the above was already checked on every region on `Win 10 x64` via https://github.com/brave/brave-core/pull/7622#issuecomment-765688658, let's just run through a few regions on each platform rather than running through the entire list on every platform.

**`Group 1:`**:

* Italy (IT)
* Canada (CA)
* Denmark (DK)
* Greece (GR)

**`Group 2:`**:

* Austria (AT)
* Norway (NO)
* Ireland (IE)
* Spain (ES)
* Portugal (PT)

**`Group 3:`**:

* Finland (FI)
* Australia (AU)
* Luxembourg (LU)
* Hungary (HU)

Please split the three groups between `Win 10 x64`, `Linux` & `macOS` 👍 @srirambv re: `Android`, we can probably just run through two groups. Once for `ARM (Phone`) and the other `ARM (Tablet)`.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.19.87 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)

```
<details>
<summary>Italy</summary>

</details>

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.87 x64 build
- Verified `Yahoo` is removed from the list of SE during onboarding and from list of default SE
- Verified `Ecosia` is available as an option in SE onboarding
- Verified `tt=42b8ae98` is appended to query string as part of referral
- Verified referral code is added on both Standard and Private tabs
- Verified visiting `https://ecosia.org` doesn't append any referral code to URL
- Verified on the following locales

  <details>
    <summary><b>Italy (IT)</b></summary>
    
   Onboarding | Standard Tab | Private Tab
    -- | -- | --
   ![image](https://user-images.githubusercontent.com/17010094/105994384-78578400-609f-11eb-90df-254bf7da34a8.png) | ![image](https://user-images.githubusercontent.com/17010094/105994406-7f7e9200-609f-11eb-93be-fda8366a239b.png) | ![image](https://user-images.githubusercontent.com/17010094/105994435-86a5a000-609f-11eb-8cdc-0b03667bb387.png)

  </details>
 
  <details>
    <summary><b>Canada (CA)</b></summary>
    
   Onboarding | Standard Tab | Private Tab
    -- | -- | --
   ![image](https://user-images.githubusercontent.com/17010094/105994273-5d850f80-609f-11eb-8630-70e1753c8ad7.png) | ![image](https://user-images.githubusercontent.com/17010094/105994294-61b12d00-609f-11eb-88ff-60ba400c25ba.png) | ![image](https://user-images.githubusercontent.com/17010094/105994324-67a70e00-609f-11eb-8a30-eac0a368a757.png)

  </details>
  
  <details>
    <summary><b>Denmark (DK)</b></summary>
    
   Onboarding | Standard Tab | Private Tab
    -- | -- | --
   ![image](https://user-images.githubusercontent.com/17010094/105994473-902f0800-609f-11eb-8068-6f385eb9574c.png) | ![image](https://user-images.githubusercontent.com/17010094/105994488-9624e900-609f-11eb-9cad-32df2e5ac769.png) | ![image](https://user-images.githubusercontent.com/17010094/105994512-9de48d80-609f-11eb-8348-44b43c2d079d.png)

  </details>
  
  <details>
    <summary><b>Greece (GR)</b></summary>
    
   Onboarding | Standard Tab | Private Tab
    -- | -- | --
   ![image](https://user-images.githubusercontent.com/17010094/105994555-ab017c80-609f-11eb-92ea-f98eea4c0a1c.png) | ![image](https://user-images.githubusercontent.com/17010094/105994572-b05ec700-609f-11eb-84f2-0927622643d3.png) | ![image](https://user-images.githubusercontent.com/17010094/105994587-b5bc1180-609f-11eb-8cda-7dcb54c80f00.png)

  </details>
  
  <details>
    <summary><b>Austria (AT)</b></summary>
    
   Onboarding | Standard Tab | Private Tab
    -- | -- | --
   ![image](https://user-images.githubusercontent.com/17010094/105994611-be144c80-609f-11eb-8399-40d29bf1cc29.png) | ![image](https://user-images.githubusercontent.com/17010094/105994621-c40a2d80-609f-11eb-9bd3-92d0fba4b24e.png) | ![image](https://user-images.githubusercontent.com/17010094/105994635-ca98a500-609f-11eb-8454-7aa39cd69e2f.png)

  </details>
  
  <details>
    <summary><b>Norway (NO)</b></summary>
    
   Onboarding | Standard Tab | Private Tab
    -- | -- | --
   ![image](https://user-images.githubusercontent.com/17010094/105994657-d3897680-609f-11eb-89c3-85086520cb64.png) | ![image](https://user-images.githubusercontent.com/17010094/105994674-da17ee00-609f-11eb-8845-7a09cba7d416.png) | ![image](https://user-images.githubusercontent.com/17010094/105994686-e00dcf00-609f-11eb-99ac-35abb77f0ac5.png)

  </details>
  
  <details>
    <summary><b>Ireland (IE)</b></summary>
   - Note: Ireland doesn't show SE Onboarding as DDG is set as default and at the top of the SE list 
    
   Default List | Standard Tab | Private Tab
    -- | -- | --
   ![image](https://user-images.githubusercontent.com/17010094/105994722-ec922780-609f-11eb-85fa-819758751586.png) | ![image](https://user-images.githubusercontent.com/17010094/105994742-f2880880-609f-11eb-896a-8cd4e7173919.png) | ![image](https://user-images.githubusercontent.com/17010094/105994771-f87de980-609f-11eb-8362-ab234c499720.png)

   </details>
