### ISSUE TITLE
Add IPFS repo stats to brave://ipfs page

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13528]
Add IPFS repo stats to brave://ipfs page, something like:

```
NumObjects: 838
RepoSize:   32340835
StorageMax: 1000000000
RepoPath:   /Users/bbondy/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/brave_ipfs
Version:    fs-repo@10
```

You can run this manually to get the data:
`./go-ipfs_v0.7.0_darwin-amd64 --api=/ip4/127.0.0.1/tcp/45004 repo stat`
But see below for how to get it through the API port like we do for getting the address config that we display on that same page.

That way when you clear cache for example, you can see it got lower.

**Comment by yrliou** [comment]
HTTP API reference: https://docs.ipfs.io/reference/http/api/#api-v0-repo-stat, we could use `IpfsService::CreateURLLoader` to use HTTP API to retrieve the result.
See `IpfsService::GetAddressesConfig` & `IpfsService::OnGetAddressesConfig` for reference.

**Comment by stephendonner** [comment]
Verified **`FIXED`** using inline testcase on 

Brave | 1.21.51 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2.1 (Build 20D74)

<img width="1279" alt="Screen Shot 2021-02-14 at 2 58 15 PM" src="https://user-images.githubusercontent.com/387249/107891751-7e3dc980-6ed5-11eb-89e7-201b18ebc9ff.png">
<img width="1279" alt="Screen Shot 2021-02-14 at 2 58 53 PM" src="https://user-images.githubusercontent.com/387249/107891755-80078d00-6ed5-11eb-8d93-4d4ea15005e3.png">

Checked and verified that reloading the tab updates:
* connected peers
* objects
* size
