### ISSUE TITLE
[Android] Fix shields settings migration

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#13522]
## Description 
Migration doesn't work for Android.

## Steps to reproduce 

   1. Install current version from Play Store
   2. Change shields settings for any web site
   3. Upgrade to the latest nightly version
   4. Settings for that web site were reset

## Actual result 
Settings for web site are reset

## Expected result
Settings for web site are preserved

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.20.74

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.84 x64 build
- Verified changing site shields setting in older version and upgrading to 1.19.84 retains the site-specific settings
----------
Verification passed on Samsung Tab A with Android 10 running 1.19.84 x64 build
- Verified changing site shields setting in older version and upgrading to 1.19.84 retains the site-specific settings
