### ISSUE TITLE
Bookmarks icons are low resolution.

### ISSUE THREAD

**Issue by us** [brave/brave-browser#13529]
## Description 
Bookmarks icons appears in low resolution.

## Actual result:
Brave result:
<img width="194" alt="Screen Shot 2021-01-13 at 04 45 28" src="https://user-images.githubusercontent.com/22618852/104395630-2ae4fe00-555a-11eb-8df8-352b35b8a218.png">

Also in brave://bookmarks
![image](https://user-images.githubusercontent.com/22618852/104396242-5e745800-555b-11eb-947d-b4a004ef1644.png)

Also in new tab last used:
<img width="362" alt="Screen Shot 2021-01-13 at 04 58 53" src="https://user-images.githubusercontent.com/22618852/104396644-1f92d200-555c-11eb-9751-49497de86a74.png">

## Expected result:
Chrome result:
<img width="200" alt="Screen Shot 2021-01-13 at 04 50 07" src="https://user-images.githubusercontent.com/22618852/104395923-d0986d00-555a-11eb-95bc-d4e309320097.png">

## Brave version
Brave 1.18.78

Macbook Pro 13 (Intel)
macOS Big Sur  11.1

- Is the issue reproducible on the latest version of Chrome? 
It doesn't look like that

**Comment by bsclifton** [comment]
We have an issue captured for updating the top site tiles image quality:
https://github.com/brave/brave-browser/issues/480

This is a good issue capturing the quality of the icons shown. I'm not sure how we diverge from Chrome/Chromium here (icons look same to me). Needs more investigtation

**Comment by us** [comment]
`icons look same to me` I think issue in there! 
I don't now but you need to increase icons size. It looks really uncomfortable on my screen.
