### ISSUE TITLE
Tor does not work on ARM MacOS Apple Silicon

### ISSUE THREAD

**Issue by paulmillr** [brave/brave-browser#13521]
## Description 

This only affects MacOS on ARM64.

Tor lists "status: disconnected" when you launch tor window.

If Brave is launched from terminal, the output is such:

```
[4963:771:0112/221753.300180:ERROR:brave_new_tab_message_handler.cc(196)] Ads service is not initialized!
[4963:771:0112/221753.421653:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Not available in Tor/incognito/guest profile", source: chrome://newtab/ (0)
[4963:771:0112/221753.422358:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Not available in Tor/incognito/guest profile", source: chrome://newtab/ (0)
```

## Steps to Reproduce

   1. Launch Brave 
   2. Launch Incognito with Tor
   3. See status: disconnected and nothing is changed

## Actual result:

Tor is running

## Expected result:

Tor does not run

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.18.78 and latest nightly as per today

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

No

**Comment by bsclifton** [comment]
I think we'll need to put a new macOS Universal executable together for this
cc: @mihaiplesa @jumde

**Comment by jumde** [comment]
@bsclifton @paulmillr - The work is being tracked here: https://github.com/brave/tor_build_scripts/issues/54

**Comment by jumde** [comment]
@paulmillr - tor v1.0.14 (see brave://components) should work on ARM MacOS. Let us know if you are running into any issues.

**Comment by paulmillr** [comment]
@jumde I don't see Tor in brave components.

**Comment by paulmillr** [comment]
Using Version 1.20.110 - Don't think it was updated.

**Comment by jumde** [comment]
@paulmillr - The tor component is only downloaded after the `Tor Window` is opened, can you try:

1.  Opening the tor window `File` > `New Private Window with Tor`
2. Verify that the `Tor component` shows up in `brave://components` after refresh
3. In the `New Tab` confirm that the `Tor Status` updates to `Connected` in a few seconds.

Let me know if you are still running into any issues.

**Comment by paulmillr** [comment]
It works. Thank you.
