### ISSUE TITLE
IPFS config: lower the ConnMgr.HighWater and LowWater limits

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#13525]
The default  (`ConnMgr.LowWater`=`600` and `HighWater`=`900`) are bit too high for desktop use. Those are aimed at server use.
Desktop users may experience issues if they are connected to a LAN managed by inexpensive consumer routers (some models crash when 1k of connections is passed). 

IPFS Desktop has been running for years with  (`LowWater`=`50 `and `HighWater`=`300`) 
and I suggest Brave sets the same values after `ipfs init` as it decreases the risk of crashing LAN for users. 

cc @bbondy @yrliou

**Comment by LaurenWags** [comment]
Will need a new build to test on 1.19.x, `QA/Blocked` for now.

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.19.84 Chromium: 88.0.4324.87 (Official Build) (x86_64)
-- | --
Revision | dd01ff8f58c65af81127ad5c105c79d5b571d8f3-refs/branch-heads/4324@{#1702}
OS | macOS Version 10.15.7 (Build 19H15)
```

Verified test plan from https://github.com/brave/brave-core/pull/7577#issue-553838765

Using a clean profile, visited `ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR` to trigger IPFS infobar.
Installed IPFS from infobar.
Opened `~/Library/Application Support/BraveSoftware/Brave-Browser/brave_ipfs/config` file.

<img width="769" alt="Screen Shot 2021-01-15 at 7 49 00 AM" src="https://user-images.githubusercontent.com/28145373/104729487-7e944a80-5706-11eb-86ff-edbcd3b5e517.png">

Confirmed updated config values of `LowWater=50` and `HighWater=300`.

<img width="271" alt="Screen Shot 2021-01-15 at 7 49 39 AM" src="https://user-images.githubusercontent.com/28145373/104729494-82c06800-5706-11eb-9a3d-881977ae852e.png">

Spot checked able to load ipfs:// and ipns:// URLs without issue.
