### ISSUE TITLE
Text/content cuts off the widget in the new tab page 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13537]
## Description 
Text/content cuts off the widget in the new tab page 

## Steps to reproduce 

   1. Clean or upgraded profile 1.20.74
   2. Click on `Continue` on P3A onboarding screen
   3. Open a NTP
   4. Text/content cuts off the widget in the new tab page 

## Actual result 
![image](https://user-images.githubusercontent.com/38657976/104427137-e896dd80-55a8-11eb-92b6-93edeea5d55b.png)
![image](https://user-images.githubusercontent.com/38657976/104427202-f9dfea00-55a8-11eb-9853-f20af4f77ac4.png)
![image](https://user-images.githubusercontent.com/38657976/104427282-12e89b00-55a9-11eb-8aff-c13b09a0ced7.png)

## Expected result

![Screenshot_2021-01-13-13-39-50](https://user-images.githubusercontent.com/38657976/104427353-23007a80-55a9-11eb-9abd-77123c880fe8.png)
![Screenshot_2021-01-13-13-49-37](https://user-images.githubusercontent.com/38657976/104427365-27c52e80-55a9-11eb-9bda-2dab873a2910.png)
![Screenshot_2021-01-13-13-49-40](https://user-images.githubusercontent.com/38657976/104427373-28f65b80-55a9-11eb-9ed0-a8c9e8f4699c.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy j3 version 5.1.1
   - Android version: 5.1.1
   
## Brave version

1.20.74
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? na
- Does the issue resolve itself when disabling Brave Rewards? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional information

cc: @brave/legacy_qa @deeppandya @samartnik @SergeyZhukovsky

**Comment by kjozwiak** [comment]
Closing as I believe this was fixed by https://github.com/brave/brave-core/pull/7590. @srirambv @GeetaSarvadnya please re-open if that's not the case 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `Bravearm 1.20.98`
![Screenshot_2021-02-04-17-53-12](https://user-images.githubusercontent.com/38657976/106892467-1f789300-6712-11eb-8be0-439bc4e362d9.png)
![Screenshot_2021-02-04-17-53-22](https://user-images.githubusercontent.com/38657976/106892481-230c1a00-6712-11eb-85f2-e74436fcbbe3.png)
![Screenshot_2021-02-04-17-53-25](https://user-images.githubusercontent.com/38657976/106892486-243d4700-6712-11eb-9302-4e0fce9b708d.png)
