### ISSUE TITLE
Change Sync Data preferences to Sync Options

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13530]
## Description 
Change Sync Data preferences to Sync Options

## Steps to reproduce 

   1. Create a new sync chain
   2. Shows `Data Pregerences`

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/104403365-4b0fbf80-5550-11eb-8439-7aa3931a3ade.png>

## Expected result
Rename `Data Preferences` to `Sync Options`

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.64.95 
Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/13530#issue-784758891
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Data Preferences` was renamed to `Sync Options`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/73cfe560-2fc8-4f86-b81c-1e7b4eb13013) | ![2](https://github.com/brave/brave-browser/assets/128532965/d03121a9-4731-4394-af8d-20ac6c5d8200) |
