### ISSUE TITLE
Qwant appearing twice under "Standard Tab" & "Private Tab" after upgrading

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13531]
## Description 

When upgrading from `1.20.65 CR: 88.0.4324.51` to `1.20.74 CR: 88.0.4324.79` while using `France`, Yahoo will correctly be removed but Qwant appears twice.

## Steps to reproduce 

   1. install `1.20.65 CR: 88.0.4324.51` (keep Qwant as the default SE)
   2. update to `1.20.74 CR: 88.0.4324.79` and notice Qwant listed twice under both `Standard Tab` & `Private Tab`

## Actual result 

**`Example`** | **`Example`**
---------------|----------------
![Screenshot_20210112-225520_Brave - Nightly](https://user-images.githubusercontent.com/2602313/104405288-9d3dea00-552a-11eb-957b-3ca06d63e82b.jpg) | ![Screenshot_20210112-225526_Brave - Nightly](https://user-images.githubusercontent.com/2602313/104405316-ae86f680-552a-11eb-9c73-216273319911.jpg)

## Expected result

**`Example`** | **`Example`**
---------------|----------------
![Screenshot_20210112-213202_Brave - Nightly](https://user-images.githubusercontent.com/2602313/104399010-d7ed5580-551d-11eb-8f46-769a700eb49c.jpg) | ![Screenshot_20210112-213207_Brave - Nightly](https://user-images.githubusercontent.com/2602313/104402362-171ea500-5524-11eb-8120-fce3c132ec7e.jpg)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 10`
   
## Brave version

* `1.20.74 CR: 88.0.4324.79`

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @deeppandya @srirambv

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.85 x64 build
- Verified upgrading from 1.18.78 to 1.19.85 doesn't list Qwant twice when its set as default during onboarding in 1.18.78
- Verified Yahoo is removed from SE list upon upgrade

Standard Tab SE | Private tab SE
-- | --
![image](https://user-images.githubusercontent.com/17010094/104882709-6cf7b080-595b-11eb-8f72-fbf48536dac2.png) | ![image](https://user-images.githubusercontent.com/17010094/104882730-77b24580-595b-11eb-8cac-b429c16ef871.png)

------------
Verification passed on Samsung Tab A with Android 10 running 1.19.85 x64 build
- Verified upgrading from 1.18.78 to 1.19.85 doesn't list Qwant twice when its set as default during onboarding in 1.18.78
- Verified Yahoo is removed from SE list upon upgrade

Standard Tab SE | Private tab SE
-- | --
![image](https://user-images.githubusercontent.com/17010094/104882764-88fb5200-595b-11eb-993e-b2915c9b244a.png) | ![image](https://user-images.githubusercontent.com/17010094/104882786-91ec2380-595b-11eb-9bf8-d6868b602dea.png)
