### ISSUE TITLE
Geolocation prompt is not blocked on Tor Windows

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1353]
## Description 

Geolocation prompt is not blocked on Tor Windows

## Steps to Reproduce

   1. Open a Tor Window
   2. Visit https://browserleaks.com/geo
   3. Location prompt bubble is shown 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46246334-fcaf7480-c3c9-11e8-8c32-c69f4e48b4af.png)

## Expected result:
Location prompt should be blocked by default on Tor tabs/Windows

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | All

### Reproducible on current release:

B-l blocks the request by default

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @diracdeltas @tomlowenthal  to change blocking label if required and change milestone

**Comment by bbondy** [comment]
For me a prompt is expected.
I will move to 1.x but I'd like a discussion for why it should not allow it at all.

**Comment by diracdeltas** [comment]
@bbondy IIRC the issue was that that the geolocation code in Chromium leaks the true IP of the user, which goes against Tor's purpose. so in b-l-b we auto-denied geolocation requests. cc @bridiver

**Comment by bbondy** [comment]
I'm aware that `getCurrentPosition` can use the Tor exit node IP to determine a fuzzier location (which isn't hidden anyway) but I don't think it exposes the user's true IP or anything like that.

**Comment by bbondy** [comment]
I'd like for a real threat to be determined precisely, or at least explained before we pull it up from the backlog.

**Comment by bbondy** [comment]
Talked about it on Slack, BrianJ mentioned that it uses the system request context for the request, so it doesn't use Tor currently.

**Comment by riastradh-brave** [comment]
For parity with browser-laptop it would be prudent to err on the side of blocking this, but as long as the geolocation query doesn't go through without explicit permission I don't think we need to make this a release blocker.  If this hasn't been addressed by then, I will take a closer look at this next week when I get back from the Tor meeting to make sure that a mere geolocation request from the site (navigator.geolocation.getCurrentPosition -- any other vectors I'm missing?) can't trigger leaks in the browser.

**Comment by riastradh-brave** [comment]
Correction: on discussion with yan, I realize it is imprudent to allow the browser to perform geolocation queries without a clearer message that the geolocation is determined by a non-Tor connection, if such a message can be usefully conveyed at all.  So this should remain a release blocker.

**Comment by yrliou** [comment]
QA note: test plan specified in https://github.com/brave/brave-core/pull/571

**Comment by emerick** [comment]
@yrliou Reverted and reopened due to build problem on Windows:

```
FAILED: vr_ui.dll vr_ui.dll.lib vr_ui.dll.pdb
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /IMPLIB:./vr_ui.dll.lib /DLL /OUT:./vr_ui.dll /PDB:./vr_ui.dll.pdb @./vr_ui.dll.rsp
lld-link: error: undefined symbol: ?kProfileUsingTor@prefs@tor@@3QBDB
>>> referenced by C:\brave-browser\src\brave\components\content_settings\core\browser\brave_host_content_settings_map.cc:26
>>>               obj/brave/components/content_settings/core/browser/browser/brave_host_content_settings_map.obj:(??0BraveHostContentSettingsMap@@QEAA@PEAVPrefService@@_N111@Z)
>>> referenced by C:\brave-browser\src\brave\components\content_settings\core\browser\brave_host_content_settings_map.cc:26
>>>               obj/brave/components/content_settings/core/browser/browser/brave_host_content_settings_map.obj:(??0BraveHostContentSettingsMap@@QEAA@PEAVPrefService@@_N111@Z)
```

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

* Verified no location prompt shown on Tor Window with shields up/down
