### ISSUE TITLE
Follow up of PR #7565 - P3A info bar isn't shown for the existing user

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13539]
## Description 
Found while testing the PR  https://github.com/brave/brave-core/pull/7565
P3A info bar isn't shown for the existing user

## Steps to reproduce 

STR 1: 

   1. Clean profile `1.19.2` nightly build
   2. Enable rewards and open a few sites
   3. Upgrade profile to `1.20.74` nightly
   4. After installing 1.20.74, the initial welcome screen for P3A is displayed with a P3A checkbox
   5. Uncheck the checkbox
   6. Browse for 5- 10 mins, P3A info bar isn't shown, restart the browser and browse for few min P3A infobar isn't shown
   
STR 2:

  1. Clean profile `1.19.2` nightly build
  2. upgrade profile to `1.20.74`
  3. After app launch, the initial welcome screen for P3A is displayed (don't take any action on this screen)
  4. Background the brave app
  5. Relaunch the app, NTP is opened and browse for a few mins 
  6. P3A infobar isn't shown
  
## Actual result 

P3A info bar isn't shown for the existing user
## Expected result
For the existing users who don't have P3A enabled, the infobar about P3A should be shown

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.20.74
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @deeppandya @SergeyZhukovsky @anthonypkeane @bsclifton

**Comment by deeppandya** [comment]
We decided not to show any infobar for existing user as the new welcome screen serves the purpose. @karenkliu @anthonypkeane

**Comment by GeetaSarvadnya** [comment]
As per the comments https://github.com/brave/brave-browser/issues/12723#issue-744089839 the infobar should be shown. Please edit the design/spec.

**Comment by karenkliu** [comment]
Sorry - it was a copy/pasted typo. The new set of full-screen P3A designs should replace the current P3A banner. I updated the original Github issue.
