### ISSUE TITLE
HTTPS Everywhere upgrades are retained even when shields is turned off 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13533]
## Description 

HTTPS Everywhere upgrades are retained even when shields is turned off 

## Steps to Reproduce

   1. Clean install nightly build
   2. Visit `http://https-everywhere.badssl.com`
   3. Auto upgrades to `https://https-everywhere.badssl.com`
   4. Turn off shields
   5. Delete URL on the same tab and manually type `http://https-everywhere.badssl.com` still upgrade to `https://https-everywhere.badssl.com`

## Expected result:
Should not upgrade to https when shields is turned off which implies HTTPS upgrades should not happen for that domain

## Reproduces how often: 

Easy

## Desktop Brave version:

All

## Android Device details:
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Related issue #13232 
cc: @fmarier @diracdeltas @brave/legacy_qa

**Comment by kjozwiak** [comment]
BTW, running into this all the time as well. It seems like Brave is upgrading websites from `HTTP` --> `HTTPS` even though the `HTTPS Everywhere` is disabled via shields or shields are completely disabled. Example:

* install `1.19.84 CR: 88.0.4324.87` using https://github.com/brave/brave-browser/releases/v1.19.84
* visit http://https-everywhere.badssl.com (auto upgraded as expected)
* disable shields completely and open a new tab
* within the new tab, load http://https-everywhere.badssl.com (still auto upgraded)

**Comment by kjozwiak** [comment]
Related to https://github.com/brave/brave-browser/issues/13604 after speaking with @iefremov 👍 Going to label this as `release/blocking` which will be addressed by the PR that will also fix https://github.com/brave/brave-browser/issues/13604.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.85 x64 build
- Verified steps from issue description and HTTPS is not working when disabled via Shields

https://user-images.githubusercontent.com/17010094/104894924-2ca12e00-596d-11eb-8133-1645de2dbf24.mp4

-----------
Verification passed on Samsung Tab A with Android 10 running 1.19.85 x64 build
- Verified steps from issue description and HTTPS is not working when disabled via Shields

 https://user-images.githubusercontent.com/17010094/104895028-48a4cf80-596d-11eb-8129-7bb8a462be09.mp4
