### ISSUE TITLE
Toolbar customization options, drag-and-drop tools.

### ISSUE THREAD

**Issue by rpgmaniac** [brave/brave-browser#13548]
Plz add the option to customize the toolbar in any way we want, add a window full of tools that we could choose to place on the toolbar in any position we like, for example the option to add a 'Zoom Control' tool or a 'Full Screen' tool etc, this I think is basic stuff that it's of outmost importance & any browser must have those options, customization is everything when you are using a browser, lack of customization options is the most common reason for someone to ditch a browser & choose something else instead.

Example: https://i.ibb.co/WDPLFT0/2021-01-13-200334.png

**Comment by bsclifton** [comment]
I think you had double reported on accident; other issue captured with https://github.com/brave/brave-browser/issues/13526

Closing as this particular issue is captured with [The UI should allow for advanced customization](https://github.com/brave/brave-browser/issues/774). You can subscribe to that issue for updates as well as to leave comments/feedback
