### ISSUE TITLE
buttons on interstitial page do not work

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13544]
## Description 

Found while testing https://github.com/brave/brave-core/pull/6782#test-plan

The "Advanced" and "Proceed with Public Gateway" buttons do not work on 1.19.82. They did work on 1.19.81 (Chromium 87). Chromium 88 was added to 1.19.82, so possibly an issue related to that.

## Steps to Reproduce

based on https://github.com/brave/brave-core/pull/6782#test-plan
   1. Clean profile 1.19.82
   2. Visit a page like https://dweb.link/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html and enable IPFS from infobar.
   3. Go to brave://settings/extensions and confirm "Method to resolve IPFS resources" is Local Node and the "IPFS public gateway fallback" switch is off.
   4. turn off your network and visit ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
   5. Get interstitial page
   6. Try clicking "Advanced", nothing happens.
   7. Re-enable network
   8. Try clicking "Advanced" and "Proceed with Public Gateway", neither work.

## Actual result:

Clicking on "Advanced" and "Proceed with Public Gateway" do nothing.

## Expected result:
"Advanced" should show more info and "Proceed with Public Gateway" should load the page using public gateway. Additionally, the "IPFS public gateway fallback" switch should be on in brave://settings/extensions

## Reproduces how often: 

easily on 1.19.82

## Brave version (brave://version info)

Brave	1.19.82 Chromium: 88.0.4324.79 (Official Build) dev (x86_64)
Revision	bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS	macOS Version 10.15.7 (Build 19H15)

Brave | 1.20.76 Chromium: 88.0.4324.79 (Official Build) nightly (x86_64)
-- | --
Revision | bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS | macOS Version 10.15.7 (Build 19H15)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes 1.19.x
- Can you reproduce this issue with the nightly channel? yes, 1.20.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @yrliou

**Comment by LaurenWags** [comment]
Will need a new build to test on 1.19.x, `QA/Blocked` until we have this uplifted.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.19.84 Chromium: 88.0.4324.87 (Official Build) (64-bit)
-- | --
Revision | dd01ff8f58c65af81127ad5c105c79d5b571d8f3-refs/branch-heads/4324@{#1702}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

Verified interstitial page is shown
![image](https://user-images.githubusercontent.com/34715963/104724431-fa0af180-5730-11eb-899a-b14a9ed2882c.png)

Verified clicking `Advanced` works:
![image](https://user-images.githubusercontent.com/34715963/104724644-43f3d780-5731-11eb-86a8-6be4cdd1c8f2.png)

Verified `Proceed with Public Gateway` works:
![image](https://user-images.githubusercontent.com/34715963/104727492-b1096c00-5735-11eb-9ba4-db179b630afa.png)

Verified `IPFS public gateway fallback` is changed to enabled in `brave://settings/extensions`
![image](https://user-images.githubusercontent.com/34715963/104730072-acdf4d80-5739-11eb-8ddc-e4a9a36a145c.png)

Verified after enabling network connection, all worked as expected:
![image](https://user-images.githubusercontent.com/34715963/104727331-70a9ee00-5735-11eb-8cb3-d9c48b8069cf.png)

Logged https://github.com/brave/brave-browser/issues/13599
