### ISSUE TITLE
Brave.Rewards.AdsState is returning an invalid response value in the initial profile load

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13546]
## Description 
Found while testing https://github.com/brave/brave-core/pull/7566#issuecomment-759483440
Brave.Rewards.AdsState is returning an invalid response value in the initial profile load

## Steps to reproduce 

   1. Clean profile 1.20.74
   2. Click on Continue on the P3A welcome screen
   3. Skip/close the remaining onboarding flow
   4. Open brave://local-state file in NTP
   5. `Brave.Rewards.AdsState` stats response value is displayed as `4` when the wallet is not created and ads are not enabled

## Actual result 
`Brave.Rewards.AdsState` is returning response value `4` (Wallet created, ads enabled, then disabled, while Brave Rewards remains on)

## Expected result
`Brave.Rewards.AdsState`  response value should be `0` on the initial profile load when the wallet is  not created

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.20.74

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @bsclifton

**Comment by emerick** [comment]
@GeetaSarvadnya Can you explain what Step 2 in the STR means? I don't think I've ever seen a P3A welcome screen. Thanks!

**Comment by emerick** [comment]
@GeetaSarvadnya Oh wait, I didn't realize that this is for Android. Probably a screen in the onboarding?

**Comment by emerick** [comment]
Can't repro on Android. Following the STR, no `Brave.Rewards.AdsState` key is created at all. This is expected at the moment, as Rewards has not yet been enabled in the flow and due to Rewards Everywhere changes we're not correctly tracking "Rewards Disabled" and "Wallet not created" states correctly.

**Comment by GeetaSarvadnya** [comment]
>@GeetaSarvadnya Oh wait, I didn't realize that this is for Android. Probably a screen in the onboarding? 

Yes, it's in P3A onboarding on Android
![image](https://user-images.githubusercontent.com/38657976/117318720-4fb60600-aea8-11eb-827a-a8a1b0e370cf.png)


@emerick The issue is reproducible in version `1.20.74`, this is the 1st version when P3A is landed and tested on Android for the 1st time. As you mentioned issue isn't reproducible in the current version or GPS version (1.23.76) as the stats `Brave.Rewards.AdsState` is been removed from the brave://local-state. 

**1.20.74 - Issue is reproducible**
![image](https://user-images.githubusercontent.com/38657976/117318355-f948c780-aea7-11eb-9988-53da7c088938.png)

**1.23.76 - Issue isn't reproducible**
![image](https://user-images.githubusercontent.com/38657976/117319528-00bca080-aea9-11eb-808d-e6eb69ddb170.png)

**Comment by GeetaSarvadnya** [comment]
Based on https://github.com/brave/brave-browser/issues/13546#issuecomment-820440975 and https://github.com/brave/brave-browser/issues/13546#issuecomment-833589929 marking the issue as invalid as it's not reproducible in current versions
