### ISSUE TITLE
Search in Google action increases a lot context menu width.

### ISSUE THREAD

**Issue by dlagg** [brave/brave-browser#13542]
## Description 

When you select text and open contextual menu with right click, the _Search with Google_ action expand the width of the menu depending of the size of the selected string. If you want to go other actions like text highlighter, the distance of mouse travel is considerable. It would be grate if this text appends the _..._ with less characters and so the width of the menu decreases.

## Steps to Reproduce

   1. Select long string in any webpage.
   2. Open the context menu (right click on the selection)
   3. Try to move the mouse to another extension action (with submenues).

## Actual result:

![image](https://user-images.githubusercontent.com/44321931/104442767-d3648380-5595-11eb-9513-f5572fa389b7.png)

## Expected result:
Less menu maximum width.

## Reproduces how often: 

Easily Reproduced.

## Brave version (brave://version info)

Brave | 1.18.78 Chromium: 87.0.4280.141 (Build oficial) (64 bits)
-- | --
Revisión | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS | Windows 10 OS Version 1909 (Build 18363.1256)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
I don't know
- Can you reproduce this issue with the nightly channel? 
I don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
I don't know

**Comment by rebron** [comment]
@dlagg I don't think this is something we'll fix. If we minimize this menu, someone else will file a new issue to expand the menu back to what it was. Further, this seems to only affect you because of the extension you're using. This change would alter the menu for everybody. Hope that explanation helps.
