### ISSUE TITLE
P3A welcome screen content isn't translated in other locales 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13541]
## Description 
P3A welcome screen content isn't translated in other locales 

## Steps to reproduce 

   1. Set the device languages to Deutsch (Germany)
   2. Install the brave app `1.20.74`
   3. After the app launch, P3A welcome screen content isn't translated to  Deutsch (Germany)
   4. P3A welcome screen content isn't translated in other locales 

## Actual result 
P3A welcome screen content isn't translated in other locales 
![image](https://user-images.githubusercontent.com/38657976/104448340-0709d280-55c3-11eb-8424-10b579d7a64e.png)

## Expected result
P3A welcome screen content should be translated in other locales 

## Issue reproduces how often 
Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.20.74
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane

**Comment by anthonypkeane** [comment]
@GeetaSarvadnya can you please re-check this one and open if needed? Thanks

**Comment by anthonypkeane** [comment]
Tested and seems to no longer be an issue

**Comment by GeetaSarvadnya** [comment]
The issue is fixed and working fine. P3A welcome screen is translated in Germany and other locales. 

Verification passed on Samsung Galaxy J3 version 5.1.1 `Bravearm 1.20.107.apk`
