### ISSUE TITLE
User can't edit script settings set by shields from settings ui or page bubble info with existing user data

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#1354]
After fixing https://github.com/brave/brave-browser/issues/232, user can edit script settings set by shields with fresh user data.

With existing user data, user only can edit after user changes from shields because settings by extension is cleared when shields set is called. That means newly changed setting value is stored to user preference and equivalent setting values in content setting store is deleted. This enables user able to edit shield settings.

Need to find a way to make user be able to edit always regardless of changing current settings or not.

**Comment by bbondy** [comment]
Since this is only a small amount of users, I think we can just have a workaround of change the setting to flush it out and close this.
