### ISSUE TITLE
Follow up of PR #7565  - Initial P3A welcome screen isn't shown after app relaunch when the user hasn't interacted with P3A screen

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13540]
## Description 

Follow up of PR #7565 - Initial P3A welcome screen isn't shown after app relaunch when the user hasn't interacted with P3A screen #13540

## Steps to reproduce 

   1. Clean profile 1.20.74
   2. After the brave app launch, background the app when the initial P3A welcome screen is shown
   3. Relaunch the app
   4. After the relaunch, NTP is shown instead of the initial P3A welcome screen

## Actual result 
 Initial P3A welcome screen isn't shown after app relaunch when the user hasn't interacted with P3A screen

## Expected result
 Initial P3A welcome screen should be shown after app relaunch when user hasn't interacted with P3A screen

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.20.74
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @deeppandya @SergeyZhukovsky @bsclifton

**Comment by deeppandya** [comment]
This is expected as we don't show the welcome screen again, if user has seen the welcome screen previously. It would be annoying for user to see the full screen welcome screen again and that's why probably user would remove the app from background in the first place. @karenkliu @anthonypkeane

**Comment by karenkliu** [comment]
If user sees the P3A welcome screen and relaunches the app without doing anything, we take it as their consent for P3A because they did not un-check the P3A box. There is no need to show the P3A welcome screen again after re-launch; this UI is shown only once.
