### ISSUE TITLE
Add a way to manually trigger garbage collection from brave://ipfs

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13554]
See the implementation notes from: https://github.com/brave/brave-browser/issues/13528
It would be similar, this would allow people to trigger garbage collection when they want to.

**Comment by LaurenWags** [comment]
@spylogsster @bbondy I am getting the below error, not sure if this is expected. 

<img width="637" alt="Screen Shot 2021-03-04 at 10 53 54 AM" src="https://user-images.githubusercontent.com/28145373/109991301-34782000-7cd8-11eb-994e-cf720358f693.png">

Generally I can't seem to get anything but the above error. STR I am using are:

1. Clean profile with 1.22.51
2. Visit an ipfs:// url such as `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
3. Join from the page shown, wait until expected ipfs url loads
4. Open a new tab and visit brave://ipfs - see info in Repo Stats populated
5. Click on `Perform a garbage collection sweep` --> get above error

Are these steps correct? I was expecting that at least `Objects` and `Size` under Repo Stats would decrease, but that's not occurring. Is there some other test plan I should be following instead - if so, could you please provide it? Thanks.

**Comment by stephendonner** [comment]
@LaurenWags thanks for adding QA/Blocked, and sorry I didn't add it when filing https://github.com/brave/brave-browser/issues/14355, which covers your issue, at least in part.

**Comment by LaurenWags** [comment]
np @stephendonner 👍🏻 will leave as Blocked until we confirm the test plan.

**Comment by spylogsster** [comment]
@LaurenWags we found the reason here https://github.com/brave/brave-browser/issues/14355#issuecomment-794027226

**Comment by LaurenWags** [comment]
thanks @spylogsster, I made a note of that suggestion on the follow up issue so we can incorporate that when we test the follow up issue.

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.22.55 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 10.15.7 (Build 19H524)
```

As per https://github.com/brave/brave-browser/issues/13554#issuecomment-790725164 and https://github.com/brave/brave-browser/issues/13554#issuecomment-790917871 garbage collection does not work due to https://github.com/brave/brave-browser/issues/14355#issuecomment-794027226.

Follow up issue https://github.com/brave/brave-browser/issues/14355 logged by @stephendonner, testing will be performed with that issue once it is resolved.

----------------
