### ISSUE TITLE
`Automatically send completely private product analytics to Brave`  isn't unchecked in the browser settings when the P3A checkbox is unchecked in welcome screen

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13551]
## Description 
`Automatically send completely private product analytics to Brave`  isn't unchecked in the browser settings when the P3A checkbox is unchecked in the welcome screen

## Steps to reproduce 

   1. Clean profile 1.20.74
   2. After app launch, P3A welcome screen is shown - uncheck the checkbox
   3. Background the app
   4. Relaunch the app
   5. Navigate to settings>advanced>privacy and verify that the checkbox is unchecked `Automatically send completely private product analytics to Brave` 
    

## Actual result 
`Automatically send completely private product analytics to Brave`  isn't unchecked in the browser settings
    

## Expected result
`Automatically send completely private product analytics to Brave` needs to be unchecked when P3A is checkbox is unchecked in the welcome screen
    

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.20.74
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/legacy_qa @deeppandya @SergeyZhukovsky 

For additional details please refer https://bravesoftware.slack.com/archives/C0816QH3R/p1610549113268900?thread_ts=1610542547.265900&cid=C0816QH3R

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.100 x64 build
- Verified steps from issue description
- ------
Verification passed on Samsung Tab A with Android 10 running 1.20.100 x64 build
- Verified steps from issue description
