### ISSUE TITLE
npm audit_deps is not catching some advisories

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#13562]
it should fail currently but passes

**Comment by diracdeltas** [comment]
@kjozwiak not sure whether to mark this QA/yes or QA/no. this doesn't introduce any new changes, but there is some risk of UI regressions since some npm dependencies were upgraded. in particular i would recommend making sure that stats show up correct on the NTP and that all tipping buttons work.

**Comment by kjozwiak** [comment]
We'll label this as `QA/Yes` so we can double check the affected area's you mentioned above 👍 `1.21.x` will be a major Chromium release as we're bumping from `C88` --> `C89` so QA will be running through full regression passes which checks the above areas as well. @diracdeltas does this affect `Android` as well? Assuming both share the same dependencies as they're on the same code base. If so, mind adding the `OS/Android` label?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.21.59 Chromium: 88.0.4324.182 (Official Build) beta (x86_64)
-- | --
Revision | 73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS | macOS Version 10.15.7 (Build 19H512)
```

Verified suggested areas from https://github.com/brave/brave-browser/issues/13562#issuecomment-761086738.
Confirmed in-line tip buttons for Twitter, GitHub, Reddit worked as expected. 
Confirmed tips were deducted from wallet balance and recorded appropriately on brave://rewards page.
Confirmed NTP stats displayed as expected.

<details>
<summary>Screenshots</summary>

Twitter | GitHub | Reddit
----- | ----- | -----
<img width="1197" alt="Twitter" src="https://user-images.githubusercontent.com/28145373/108408961-a7bb6580-71f3-11eb-9997-531a3721c52f.png"> | <img width="1197" alt="GitHub" src="https://user-images.githubusercontent.com/28145373/108408962-a8ec9280-71f3-11eb-914d-01994ee3badf.png"> | <img width="1194" alt="Reddit" src="https://user-images.githubusercontent.com/28145373/108408968-aa1dbf80-71f3-11eb-9096-081db1754a8c.png">

brave://rewards wallet panel | Tips panel
----- | -----
<img width="411" alt="Screen Shot 2021-02-18 at 2 11 09 PM" src="https://user-images.githubusercontent.com/28145373/108409047-bbff6280-71f3-11eb-9af5-464d9235917b.png"> | <img width="648" alt="Screen Shot 2021-02-18 at 2 11 15 PM" src="https://user-images.githubusercontent.com/28145373/108409052-bc97f900-71f3-11eb-9e24-789ff56139e4.png">

NTP Stats
<img width="1195" alt="Screen Shot 2021-02-18 at 2 13 02 PM" src="https://user-images.githubusercontent.com/28145373/108409079-c6216100-71f3-11eb-9435-a2bbce9af9ac.png">

</details>
