### ISSUE TITLE
remove "{ }" from Ecosia search query

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13568]
## Description 

We're currently using `https://www.ecosia.org/search?tt=e8eb07a6&q={%s}` instead of `https://www.ecosia.org/search?tt=e8eb07a6&q=%s` which results in search terms appearing in `{ }`. Example: `{under armour}`.

## Steps to Reproduce

   1. install `1.19.83 CR: 88.0.4324.79`
   2.  set the default SE to `ecosia` via `brave://settings/search`
   3. using the omni box, perform a search

## Actual result:

![image](https://user-images.githubusercontent.com/2602313/104560607-1cf3b380-5614-11eb-9220-2ffaa830a9fa.png)

## Expected result:

![image](https://user-images.githubusercontent.com/2602313/104560634-2715b200-5614-11eb-9107-4c95428ac688.png)

## Reproduces how often: 

100% reproducible when using the STR mentioned above.

## Desktop Brave version:

```
Brave | 1.19.83 Chromium: 88.0.4324.79 (Official Build) (64-bit)
-- | --
Revision | bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS | Windows 10 OS Version 2009 (Build 19042.746)
```

## Android Device details:
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10_`
   - Android version: `Android 10`

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No` (only `1.19.x` and not `1.18.x`)
- Can you reproduce this issue with the beta channel?  `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @bsclifton @srirambv @rebron @janypiotrowski

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 1.19.83 Chromium: 88.0.4324.79 (Official Build) (64-bit)
-- | --
Revision | bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/104597027-18abb280-5675-11eb-8e54-34671e70cb4c.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.19.84 x64 build
- Verified `{ }` isn't added to query string
--------
Verification passed on OnePlus 6T with Android 10 running 1.19.84 x64 build
- Verified `{ }` isn't added to query string
