### ISSUE TITLE
npm run audit_deps shows rust error locally

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#13563]
`npm run audit_deps` when run locally fails due to RUSTSEC-2021-0003 (Upgrade to >=0.6.14, <1.0.0 OR >=1.6.1)

it seems to be passing in CI though. cc @mihaiplesa @antonok-edm

**Comment by antonok-edm** [comment]
@diracdeltas can you verify whether or not that's still the case after https://github.com/brave/brave-core/pull/7574 was merged?

**Comment by mihaiplesa** [comment]
Also let me know if we need to rebuild and update https://github.com/brave/brave-core/blob/master/script/rust_deps_config.py#L9

**Comment by diracdeltas** [comment]
@antonok-edm i did run it locally on master with that PR merged already

**Comment by diracdeltas** [comment]
this was an issue on my end. sorry for the false alarm!
