### ISSUE TITLE
White space

### ISSUE THREAD

**Issue by Bhooty** [brave/brave-browser#13570]
## Steps to reproduce 

   1. Go to m.bdnews24.com on mobile
   2. Check at top

## Actual result 
![Screenshot_20210114-184502_Brave](https://user-images.githubusercontent.com/46019727/104592816-fb88db00-5698-11eb-970f-b93b845e6090.jpg)

## Expected result
There should be no whitespace like when adguard extension is used

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:
 all

- Can you reproduce this issue with the current Play Store version? 
- yes
- Can you reproduce this issue with the current Play Store Beta version? 
- don't know
- Can you reproduce this issue with the current Play Store Nightly version?
- don't know

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 9.0
   
## Brave version
1.18.78

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- no
- Does the issue resolve itself when disabling Brave Rewards?
- no
- Is the issue reproducible on the latest version of Chrome?

**Comment by Bhooty** [comment]
Same with theverge.com

![Screenshot_20210114-190649_Brave](https://user-images.githubusercontent.com/46019727/104594726-c5992600-569b-11eb-8cb1-80556306538c.jpg)

**Comment by ryanbr** [comment]
@Bhooty   https://github.com/brave/brave-browser/issues/13070 & https://github.com/brave/brave-core/pull/6735

I'll close this, when cosmetic filtering lands in Android it'll fix the whitespace issues.

**Comment by Bhooty** [comment]
> @Bhooty #13070 & [brave/brave-core#6735](https://github.com/brave/brave-core/pull/6735)
> 
> I'll close this, when cosmetic filtering lands in Android it'll fix the whitespace issues.

thought it arrived but why can't i enable scripts blocking globally in android? is that not available or I am missing something :)

**Comment by ryanbr** [comment]
Not available, the script blocking on android (compared to desktop) isn't quite featureful
