### ISSUE TITLE
Greaselion makes excessive calls to Twitter API

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#13578]
## Description 
Per @jonathansampson:

Greaselion generates thousands of requests to Twitter's API, resulting in rate-limiting and excessive resource usage.

## Steps to Reproduce

1. Launching a new profile
2. Navigate from the welcome screen to https://twitter.com/brave/status/794221010484502528

## Actual result:
Greaselion calls Twitter API until it's rate limited.

## Expected result:
Greaselion shouldn't make excessive calls to the Twitter API.

## Reproduces how often: 

Seems intermittent.

## Brave version (brave://version info)

Nightly.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by jonathansampson** [comment]
Worth noting too that these calls appear to come in 2's. One with the `x-guest-token` header, and one without. Those calls which lack this header are immediately rejected, if I'm not mistaken. Those which contain it are permitted. That is, until we have exhausted the number of API requests we are permitted to make. In this scenario, Brave tends to issue anywhere between 700 to 1.5K calls before ceasing.
