### ISSUE TITLE
When Autoplay is off, certain interactions with video player halts playback

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#13586]
## Description 

When the `Autoplay` permission is set to `Block` (manually or by default), any interaction with a video player (ex Youtube), such as changing the volume of the video or sometimes jumping forward/backward to certain points in the video will cause the player to halt playback. The user then needs to start the video again manually. Note that this happens every time you go to adjust/interact with the player, not just the first time.

## Steps to Reproduce

   1. In Brave v1.18.78 or higher, visit YouTube.com
   2. Select a video to play and ensure that `Autoplay` is `Blocked` for YouTube, or that you select `Block` when prompted.
   3. Start to stream the selected video.
   4. In the player, attempt to change the playback volume and observe playback halted.

## Actual result:

Playback stops after interaction:
https://imgur.com/a/tAGdCLs

## Expected result:
Playback should only be halted on first load (since `Autoplay` = `Blocked`) or if the user pauses the video directly -- not when adjusting video settings.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

User thread:
https://community.brave.com/t/audio-stops-when-adjusting-volume-level/196109
cc @darkdh

**Comment by SevilleCode** [comment]
I have noticed a similar issue with audio elements on the Wikimedia Commons website. If autoplay is set to Blocked, the audio files will not play at all, even after the user tries to play them manually. If autoplay is set to Allowed, then users can play the audio files normally.

**Comment by Brave-Matt** [comment]
+1 Community:
https://community.brave.com/t/adjusting-volume-stops-video-playback/210613/2

**Comment by Brave-Matt** [comment]
+1 Community:
https://community.brave.com/t/videos-pause-upon-adjust-the-volume/234588/5

**Comment by rebron** [comment]
+1 from https://github.com/brave/brave-browser/issues/16102 with a specific use case for Twitch.tv

STR:

1. Turn off AutoPlay globally in the browser settings
2. Go to https://www.twitch.tv/ and open any online twitch.tv stream in current or new tab (doesn't matter)
3. Stream is paused and muted by default
4. Click play button at the bottom left of the Player to start the stream
5. Video starts playing muted
6. Click mute/unmute button at the bottom left of the Player to unmute the stream
7. Stream pauses itself while still being muted
8. To actually unmute and play it you need to first unmute it while paused and then click the play button at.

**Comment by ardunster** [comment]
I also have this problem both on Windows 10 at work (my current device, Version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit) ) and on my OSX Catalina device at home (don't have version handy for that one). It's pretty annoying.  I haven't noticed the behavior with other situations but it definitely occurs when adjusting volume on YouTube videos which makes it quite tricky to finely adjust volume on a playing video.

**Comment by KevinSource0** [comment]
+1 from community https://community.brave.com/t/videos-pause-upon-changing-volume/188456 and https://community.brave.com/t/blocking-autoplay-on-youtube-causes-volume-adjust-to-pause-playback/190196.
It's been reported since December 2020, still seeing it (currently on latest version of Brave: Version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (x86_64), OS: Mac 10.15.7).

**Comment by mnhrsngh** [comment]
+1 I just switched to using Brave, and this bug is really making me reconsider... the fix cannot be so difficult, any reason this is still unresolved half a year later?

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/when-auto-play-is-turned-off-changing-the-volume-stops-the-playback/267629/3

**Comment by joel-williams** [comment]
+1 still happening, Windows 10, v1.27.111

**Comment by pefopi** [comment]
+1 on Brave V1.31.88 - Windows 10 21H1, Build 19043.1320

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/changing-volume-stops-videos-from-playing/308239/2

**Comment by Canowyrms** [comment]
Just giving Brave browser a try now, thought I was going crazy having YouTube videos pause every time I used scroll-wheel to adjust volume.

Temporary workaround working (so far*) for me:
- Allow autoplay in Brave's settings
- Use [AutoplayStopper](https://chrome.google.com/webstore/detail/autoplaystopper/ejddcgojdblidajhngkogefpkknnebdh?hl=en) Chrome extension

Stupid, but it works.

**Comment by jbruchon** [comment]
I have to be honest, I'm pretty shocked that this isn't fixed and it's been a bug for over a year, plus "assigned" for 4 months. It's extremely annoying that merely adjusting the volume control STOPS the video.

**Comment by Brave-Matt** [comment]
Still seeing reports of this cc @rebron 
https://community.brave.com/t/youtube-clips-will-stop-when-i-set-a-new-volume/342988/2

**Comment by KipThorne** [comment]
Same problem here on Windows 10.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.61 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.43.61`
2. launched Brave
3. loaded `youtube.com`
4. selected `https://www.youtube.com/watch?v=jfKfPfyJRdk`
5. streamed the above, first confirming `autoplay=blocked`
6. tweaked volume and other controls while video/audio was playing

Confirmed video/audio playback didn't stop:

`autoplay=blocked` | uninterrupted YouTube playback
---------------------|--------------------------------
<img width="1122" alt="Screen Shot 2022-08-08 at 4 38 51 PM" src="https://user-images.githubusercontent.com/387249/183533106-23dc7489-9360-4542-827e-e79d8158d4b9.png"> | <img width="1074" alt="Screen Shot 2022-08-08 at 4 40 22 PM" src="https://user-images.githubusercontent.com/387249/183533114-2ed9a499-b2b3-4b7c-99df-a4360e021661.png">


Also double-checked on `https://commons.wikimedia.org/wiki/Main_Page`

<img width="1074" alt="Screen Shot 2022-08-08 at 4 40 16 PM" src="https://user-images.githubusercontent.com/387249/183533063-27cee39b-ef8a-47a0-86ac-b71872c1a440.png">

**Comment by stephendonner** [comment]
It appears Twitch.tv still has the problem mentioned in https://github.com/brave/brave-browser/issues/13586#issuecomment-850554886

**Comment by LaurenWags** [comment]
> It appears Twitch.tv still has the problem mentioned in [#13586 (comment)](https://github.com/brave/brave-browser/issues/13586#issuecomment-850554886)

@stephendonner is there a follow up for this? if not, can you please log? Thanks!

**Comment by stephendonner** [comment]
> > It appears Twitch.tv still has the problem mentioned in [#13586 (comment)](https://github.com/brave/brave-browser/issues/13586#issuecomment-850554886)
> 
> @stephendonner is there a follow up for this? if not, can you please log? Thanks!

Filed https://github.com/brave/brave-browser/issues/24556 👍
