### ISSUE TITLE
Add "I don't care about cookies" filter list into Brave Shield

### ISSUE THREAD

**Issue by Furax-31** [brave/brave-browser#13585]
## Description 

There are far too many cookie pop-ups on European sites, this filters list solves the problem.

## Desktop Brave version:
 Nightly 1.21.2

## Android Device details:
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10

## Miscellaneous Information:

List: `https://www.i-dont-care-about-cookies.eu/abp/`

Even with the list "Easylist-Cookie List - Filter Obtrusive Cookie Notices", the pop-ups are not blocked.

Example: This affects a lot of sites.
![1](https://user-images.githubusercontent.com/61207108/104646512-d1431780-56b0-11eb-8eea-c2379bf44b28.png)

**Comment by ryanbr** [comment]
Cosmetic blocking is limited on Android, (so it'll still show regardless)

But this can be blocked https://github.com/easylist/easylist/commit/f164a19426a57599b8779e9a050be5d186e9a0bd

**Comment by Furax-31** [comment]
The problem is also present on PC.  Vivaldi's built-in blocker does not have this problem.

**Comment by ryanbr** [comment]
Because we can manage the list better, since its used by us and the uBO community.

**Comment by Furax-31** [comment]
The fact of not being able to add the lists that one wants is very restrictive.

**Comment by ryanbr** [comment]
We have an open ticket for manually adding lists https://github.com/brave/brave-browser/issues/8107  & https://github.com/brave/brave-browser/issues/8838. 

Closing ticket, since Apkmirror Issue is resolved. Any missing cookie messages do create a new ticket.
