### ISSUE TITLE
Crash Report: Braves crashes when Google Meet accesses camera and microphone

### ISSUE THREAD

**Issue by mikol** [brave/brave-browser#13581]
Brave Version: 1.18.78  Chromium: 87.0.4280.141
Operating System: Mac OS X 10.15.7

URL (if applicable) where crash occurred: https://meet.google.com/xxx-xxxx-xxx

Can you reproduce this crash? Yes, 100% of the time.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open a Google Meet video conference
2. When prompted (if you haven’t already) grant access to camera and microphone
3. Brave crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/352c0000-604d-b505-0000-000000000000

**Comment by mikol** [comment]
This equally a problem when Brave’s shields are up or down.

This is not a problem with:

  - Chrome—Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
  - Firefox—Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0
  - Safari—Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15

**Comment by bsclifton** [comment]
@mikol can you go to brave://settings/extensions and enable Google Hangouts? I am curious if this fixes the problem for you

**Comment by mikol** [comment]
@bsclifton I will do that tomorrow and let you know how it goes (note that meet was working with Brave for me yesterday)

**Comment by mikol** [comment]
@bsclifton That seems to have done the trick. It looked like that setting was enabled already. But I disabled it, and was able to reproduce the crash. After enabling it again, I can no longer reproduce the crash. Thanks for your help, and sorry for the delay in additional information.

**Comment by bsclifton** [comment]
@mikol awesome - thanks! 😄 Good to know that you can reproduce a crash. Can you visit brave://crashes and send the crash report? There will be a long report GUID too which (if you share here) we can look into the root cause

**Comment by mikol** [comment]
Sorry, @bsclifton — Now that I have toggled the Hangouts switch a couple of times, I am no longer able to reproduce the crash. The crash ID for my initial report is above (Crash ID: crash/352c0000-604d-b505-0000-000000000000). I hope that helps you find the issue.
