### ISSUE TITLE
Inastgram embedded images fail to load with blocking enabled

### ISSUE THREAD

**Issue by cyberfunk** [brave/brave-browser#13597]
I can't see Instagram images with trackers/blocking enabled in Brave browser. The first image is with blocking enabled and the second with blocking disabled. How do I allow embedded Instagram photos to show while blocking other unwanted ads/trackers?

![1](https://user-images.githubusercontent.com/12664589/104723536-3b28e480-56e4-11eb-81ac-c9ffb8f991a1.jpg)
![2](https://user-images.githubusercontent.com/12664589/104723543-3e23d500-56e4-11eb-81a9-28877afdc5de.jpg)

**Comment by ryanbr** [comment]
Thanks for the report, have investigated and found a fix. Give it 24-48hrs. should be fixed automatically

@cyberfunk

**Comment by cyberfunk** [comment]
Same issue in iOS mobile app as well

**Comment by ryanbr** [comment]
Will be fix in Ios next week, (may need a restart of browser)

**Comment by cyberfunk** [comment]
Great thanks!

**Comment by cyberfunk** [comment]
It's fixed. Thanks again!
