### ISSUE TITLE
Custom Brave ad notifications should not be shown on Dev channel builds

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#13592]
## Steps to Reproduce

   1. Install Dev channel build

## Actual result:

Custom ad notifications are shown

## Expected result:
Native ad notifications should be shown

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.20.85 Chromium: 88.0.4324.96 (Official Build) beta (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

```
Brave | 1.20.87 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

```
Brave | 1.21.20 Chromium: 88.0.4324.96 (Official Build) nightly (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

Confirmed `Beta` and `Dev` versions use system notifications.
Confirmed `Nightly` version uses custom notifications.

Beta | Dev | Nightly
----- | ----- | -----
<img width="1121" alt="Beta" src="https://user-images.githubusercontent.com/28145373/105499626-c4658b80-5c8f-11eb-9413-a1ec22700ee2.png"> | <img width="1200" alt="Dev" src="https://user-images.githubusercontent.com/28145373/105499632-c596b880-5c8f-11eb-9837-152db2fdb2f5.png"> | <img width="1155" alt="Nightly" src="https://user-images.githubusercontent.com/28145373/105499635-c62f4f00-5c8f-11eb-8609-9044de6fb3a3.png">

-----------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.100 x64 build
- Verified 1.20.x branch doesn't have custom Brave ad notification
![image](https://user-images.githubusercontent.com/17010094/107212251-948fe500-69fe-11eb-8e1f-444dc4fba2d3.png)

--------- 
Verification passed on Samsung Tab A with Android 10 running 1.20.100 x64 build
- Verified 1.20.x branch doesn't have custom Brave ad notification
![image](https://user-images.githubusercontent.com/17010094/107212388-cbfe9180-69fe-11eb-8703-7c36e23d2579.png)
