### ISSUE TITLE
Add setting to toggle visibility of Bookmark button in the URL bar

### ISSUE THREAD

**Issue by nerdyman** [brave/brave-browser#13598]
## Description 

It's easy to accidentally click the bookmark button in the URL bar as it's positioned between the refresh button and the URL input - resulting in unwanted bookmarks. Also, some people don't use the native browser bookmarks at all so this button is not always of use.

![image](https://user-images.githubusercontent.com/4908432/104725284-c5476c00-5729-11eb-9cff-d41677c90623.png)

Ideally, there should be an Appearance setting for "Show Bookmark button" which works similarly to the  "Show Home button" setting.

![image](https://user-images.githubusercontent.com/4908432/104726001-cfb63580-572a-11eb-8a4c-1ea878a46463.png)

## Steps to Reproduce

   1. Have poor hand-eye-coordination
   2. Accidentally click bookmark button instead of URL input or refresh button
   3. Unwanted bookmark saved

## Reproduces how often: 

I do this multiple times per week.

## Brave version (brave://version info)

Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) unknown (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Linux
JavaScript | V8 8.7.220.29

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel?    Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

- Related ticket: https://github.com/brave/brave-browser/issues/774
- Related comment: https://github.com/brave/brave-browser/issues/774#issuecomment-760664719
- [Community thread](https://community.brave.com/t/is-there-a-way-to-move-the-bookmarks-button-to-where-it-is-in-chrome/48785/12)

P.S. Thanks for all the amazing work on Brave!

**Comment by sirius-c** [comment]
see also #12052

**Comment by GEHORC** [comment]
> see also #12052

I would a 1000 times support this over just making an on/off toggle.
Put the thing to the right side of the address bar and don't drown the issue in a wider sea of "advanced UI customizations".
It's actually "make or break" thing for me.
There have been calls for returning the bookmark button to an intuitive place here too:
https://community.brave.com/t/is-there-a-way-to-move-the-bookmarks-button-to-where-it-is-in-chrome/48785
This post is from 01 May 2019.

**Comment by nerdyman** [comment]
Thanks for resolving this @fallaciousreasoning 🙌

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.40.68 Chromium: 102.0.5005.50 (Official Build) beta (x86_64)
-- | --
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | macOS Version 12.5 (Build 21G5027d)

#### Confirmed:
* in a new profile, `Show bookmarks button` is toggled `ON`, and the `Bookmark this tab` button is visible
* toggling `Show bookmarks button` to `OFF` works, and the bookmark button is removed from the toolbar
* toggling `Show bookmarks button` back to `ON` works, and the bookmark button is visible on the toolbar
* upgrading from `1.39.111` -> `1.40.68`, `Show bookmarks button` is toggled to `ON` and the bookmarks button is shown
* toggling `Show bookmarks button` to`ON`/`OFF` in the upgraded profile works
* preference/bookmark icon state persists correctly between Brave restarts

`Show bookmarks button` `ON` | `Show bookmarks button` `OFF`
---------------------------------|---------------------------------
<img width="1312" alt="Screen Shot 2022-05-24 at 5 20 55 PM" src="https://user-images.githubusercontent.com/387249/170153956-e2515d73-1e44-4bb7-9392-c1a71bd643cb.png"> | <img width="1312" alt="Screen Shot 2022-05-24 at 5 21 02 PM" src="https://user-images.githubusercontent.com/387249/170153985-3aeb2cfc-62a4-4159-804e-69c2b8999c91.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```
#### Confirmed:
* in a new profile, `Show bookmarks button` is toggled `ON`, and the `Bookmark this tab` button is visible
* toggling `Show bookmarks button` to `OFF` works, and the bookmark button is removed from the toolbar
* toggling `Show bookmarks button` back to `ON` works, and the bookmark button is visible on the toolbar
* upgrading from `1.39.111` -> `1.40.68`, `Show bookmarks button` is toggled to `ON` and the bookmarks button is shown
* toggling `Show bookmarks button` to`ON`/`OFF` in the upgraded profile works
* preference/bookmark icon state persists correctly between Brave restarts

`Show bookmarks button` `ON` | `Show bookmarks button` `OFF`
---------------------------------|---------------------------------
<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/171306450-a08ddf34-a36b-4a08-82f3-00246434dfb3.png">|<img width="930" alt="image" src="https://user-images.githubusercontent.com/98358127/171306408-2bb9bf15-c17e-4995-9e3f-36737552ed5a.png">
