### ISSUE TITLE
An empty widget stack still shows all the widget data 

### ISSUE THREAD

**Issue by kdejaeger** [brave/brave-browser#13594]
When disabling all 3 window stacks. Instead of a blanc page, the page shows data from 'top sites' and 'privacy stats'.
See video: https://photos.app.goo.gl/NyDC5MPumats1ewS8
Release: 8 jan 2021

**Comment by srirambv** [comment]
That is expected behaviour. Currently there is no way to disable everything and just have a blank tab. 

cc: @jamesmudgett @anthonypkeane

**Comment by deeppandya** [comment]
Closing this issue as it's irrelevant
