### ISSUE TITLE
Bug: Settings -> New Tab Page -> Top Sites toggle is always off on page init

### ISSUE THREAD

**Issue by kdejaeger** [brave/brave-browser#13595]
Whether the option is on of off, if you open brave://settings/, the toggle will appear to be initialized 'off'.

So internally it's on, in the GUI it appears off.

Version: 1.18.78

**Comment by rebron** [comment]
Closing as no longer valid. We're directing this setting/toggle to the 'Customize' one on the New Tab page itself. The redundancy in Settings didn't make sense.
