### ISSUE TITLE
Brave Ads should only convert for the last touch

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#13596]
When running consecutive push campaigns for an advertiser and both campaigns have an attribution window, only the last touch should attribute

**Comment by lukemulks** [comment]
I think there's some care we should put into this one. 

View-through conversions could be from a combination of SI and push campaigns, and if both attribute, it indicates the user saw both ads and ended up at the viewthrough conversion destination (assuming that both creatives were assigned to sets with the same conversion reporting. 

I'd agree that last touch should be a factor for clickthrough conversions, but would hold off on this for viewthrough. 

Would categorize this at a lower priority than some of the other items right now.

**Comment by tmancey** [comment]
Discussed with @lukemulks and closing as won't fix, Thanks
