### ISSUE TITLE
Monthly Contribution Statement dropdown always shows latest month, even when another month is selected

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#13590]
## Description 

In Monthly Contribution Statements, the dropdown list always stays visually stuck on the most recent month, even after selecting a different month. (Underlying data appears to change to the selected month, however.)

## Steps to Reproduce

Go to brave://rewards, Monthly Contribution Statements. Choose a previous month. Observe how the dropdown itself continues to display the latest month and does not visually show the selected month.

## Expected result:

Should show selected month.

## Reproduces how often: 

100% of the time. Reproduced by @pes10k and @Miyayes.

## Brave version (brave://version info)

Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)

![image](https://user-images.githubusercontent.com/11497541/104672914-a48e0080-56ae-11eb-8364-9c5cf0316a34.png)

Even after a previous month is selected and the dropdown collapses, January 2021 (or latest month at that time) is always shown.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.21.52 Chromium: 88.0.4324.152 (Official Build) dev (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 10.15.7 (Build 19H512)
```

Verified test plan from https://github.com/brave/brave-core/pull/7615.
Encountered and logged https://github.com/brave/brave-browser/issues/14159 while testing.

Feb 2021 | Jan 2021 | Dec 2020
----- | ----- | -----
<img width="956" alt="Screen Shot 2021-02-15 at 9 28 19 AM" src="https://user-images.githubusercontent.com/28145373/107958557-2f913d80-6f70-11eb-9512-0e2dc91d5db7.png"> | <img width="945" alt="Screen Shot 2021-02-15 at 9 28 26 AM" src="https://user-images.githubusercontent.com/28145373/107958562-30c26a80-6f70-11eb-973d-9c2e205f7857.png"> | <img width="942" alt="Screen Shot 2021-02-15 at 9 28 34 AM" src="https://user-images.githubusercontent.com/28145373/107958565-31f39780-6f70-11eb-944e-5dff8e483ca4.png">

--------------
