### ISSUE TITLE
Google meet screen share fails

### ISSUE THREAD

**Issue by rafi-gemhar-vineti** [brave/brave-browser#13591]
## Description 
Google meet screen share fails

## Steps to Reproduce

   1. Open any meeting on google meet.
   2. Select present now 
   3. Gets a popup occurs with an error message message

## Actual result:

When screen sharing for the first time:
<img width="502" alt="Screenshot 2021-01-15 at 9 18 48 AM" src="https://user-images.githubusercontent.com/75755979/104679094-e8b2ec80-5712-11eb-8b01-82a35e45db99.png">
When screen sharing for the second time in the same session:
<img width="431" alt="Screenshot 2021-01-15 at 9 19 09 AM" src="https://user-images.githubusercontent.com/75755979/104679096-ea7cb000-5712-11eb-85ab-05c81c33127e.png">

## Expected result:
Should be able to present the screen

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave	1.20.79 Chromium: 88.0.4324.79 (Official Build) dev (x86_64)
Revision	bd1e9353659b2491dac971226a973ca3b5684a14-refs/branch-heads/4324@{#1520}
OS	macOS Version 11.1 (Build 20C69)
JavaScript	V8 8.8.278
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.79 Safari/537.36
Command Line	/Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=AutofillEnableAccountWalletStorage,TextFragmentAnchor,WebOTP,NotificationTriggers,PasswordCheck,NetworkTimeServiceQuerying,TabHoverCards,AutofillServerCommunication,IdleDetection,PrivacySettingsRedesign,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev
Profile Path	/Users/rafi/Library/Application Support/BraveSoftware/Brave-Browser-Dev/Profile 5

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Happens only in developer edition(latest update as of 15th-Jan-2021)
- Can you reproduce this issue with the beta channel? 
This issue does not happen in the latest brave browser(without the dev edition)
- Can you reproduce this issue with the nightly channel? 
No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

Console error logs:
[meet.google.com-1610682258737.log](https://github.com/brave/brave-browser/files/5818316/meet.google.com-1610682258737.log)

**Comment by bsclifton** [comment]
@rafi-gemhar-vineti can you please visit brave://settings/extensions and enable Hangouts?  That should fix the problem 😄 

Previously reported with https://github.com/brave/brave-browser/issues/13469. Closing this issue as a dupe
