### ISSUE TITLE
Question: ungoogled-chromium instead of vanilla chromium?

### ISSUE THREAD

**Issue by Nezteb** [brave/brave-browser#1359]
There was a conversation on Reddit about Brave being insecure because of Electron/Chromium reliance: https://www.reddit.com/r/privacytoolsIO/comments/9jn3de/please_dont_recommend_use_brave/

Also see: https://github.com/Eloston/ungoogled-chromium

Does the Brave team agree with these concerns or specifically address them via muon development or Brave itself?

Also see:
* https://github.com/brave/muon/issues/650
* https://github.com/brave/browser-laptop/issues/15248

**Comment by bsclifton** [comment]
See response here: https://github.com/brave/browser-laptop/issues/15248#issuecomment-425766116
