### ISSUE TITLE
Include Linux Packages into Fastly's edge cache CDN

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#1360]
Have you searched for similar issues? Yes. Carrying on from [No CDN use for download brave packages](https://github.com/brave/browser-laptop/issues/14956) created by @posix4e and I'm almost positive he uses OpenSuse.

## Description 
Downloading and updating Linux packages takes far too long. 

## Steps to Reproduce
   1. Download or Update any version of Brave in Linux.

## Actual result:
   1. More often than none, I get speed of 65-100 KiB/s on most of the updates.
   2. Another user from the Asia Pacific region reported waiting 50 minutes to download the latest brave-core beta version. The person is yet to respond whether it was on a Linux distro but it's quite likely that it is. (Will update if incorrect) UPDATE: It wasn't.

## Expected result:
It should be in the MB/s speeds at the very least. Most users on a greater gigabit network expect it to be much more faster though.

## Reproduces how often: 
More often than none.

## Brave version (chrome://version info)
Irrelevant.

### Reproducible on current release:
Yes.

### Additional Information
I've got one additional questions.
 1. I think it's understood that the Linux packages were and are left out of Fastly's CDN, seeing as you already provide the service for Windows and MacOS, why was Linux left out it in the first place when it should be as simple as including those packages (he says) into to Fastly's edge cache CDN?

**Comment by rebron** [comment]
Is this still valid @mbacchi ?

**Comment by NumDeP** [comment]
In my last update I received the update at a rate of 1.7 MiB/s, so quite fast. I don't whether the packages were added to the CDN but it's more efficient than what I used to previously encounter.

**Comment by mbacchi** [comment]
Closing as we haven't heard of any other issues with the CDN. If you still encounter this problem let me know.

**Comment by yadunut** [comment]
Hi there, I'm facing the same issue with slow download speeds on linux. 
OS: Arch Linux
Region: Singapore
Package: https://aur.archlinux.org/packages/brave-bin/
![image](https://user-images.githubusercontent.com/16850285/83343145-23ede000-a329-11ea-99d5-2b9d22b16172.png)

**Comment by mbacchi** [comment]
We do not provide Arch Linux packages. This is not our repository, you'll have to talk to the owner of that package.
