### ISSUE TITLE
(Regression) Insecure content coming from 127.0.0.1:<port> is being blocked by Shields.

### ISSUE THREAD

**Issue by jnicholls** [brave/brave-browser#13606]
## Description 
Several releases ago—I am uncertain when exactly, but as recently as November 2020—Brave operated with the same behavior as Chromium with regard to allowing insecure content at an `http://127.0.0.1:<port>` origin when on a secure site. The latest release as of this writing, however, now blocks these requests and differs from Chrome's behavior. I am certain it is Shield's "Tracker & ad blocking" feature as the culprit, because disabling it returns to the original behavior.

## Steps to Reproduce

   1. Author a simple HTTP webserver running on http://127.0.0.1:3000, and host a path `/image.png` that loads any old image, perhaps a 1x1 pixel.
   2. Author a simple HTML site that loads `<img src="http://127.0.0.1:3000/image.png" />`, and host it at an HTTPS address.

## Actual result:
Brave Shields will block the image from loading. Disable the "Tracking & ad blocking" and Brave will then load the image successfully.

## Expected result:
Brave Shields to have parity with Chrome with regards to insecure content being loaded on the loopback interface.

## Reproduces how often: 
Every time since a particular release in the recent past.

## Brave version (brave://version info)
Brave | 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)
Revision | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS | macOS Version 11.1 (Build 20C69)

## Version/Channel Information:

- Can you reproduce this issue with the current release? I've only tried on the current release.
- Can you reproduce this issue with the beta channel? Do not know, but I suspect yes.
- Can you reproduce this issue with the nightly channel? Do not know, but I suspect yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes, if entirely disables or if "Tracking & ad blocking" is disabled.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? No.

## Miscellaneous Information:
I would encourage that this behavior be reverted to match that of Chrome, Firefox, and (in the case of `<img />` resources) Safari. These browsers treat insecure content coming from `http://127.0.0.1` as safe and will not block it, as of 4-5 years ago. Some products actually require this behavior in order to function properly. If there was a particular motivation for starting to block this content, I would love to be linked to that information. Thanks in advance.

**Comment by ryanbr** [comment]
Hi @jnicholls   the change was intentional due to privacy concerns about websites using localhost requests, the easy option would be to just disable ads/trackers in shields on the site you're using.

**Comment by pbadenski** [comment]
@ryanbr could you elaborate on this? As far as I understand W3 spec on this - 127.0.0.1 is considered secure.

**Comment by JakobJingleheimer** [comment]
@ryanbr did you consider applying this to only sites that are not themselves localhost?
