### ISSUE TITLE
disabling shields still shows blocked count, ads still blocked

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13604]
## Description 

Found by @iefremov 

Disabling shields shows non-zero blocked count, ads still blocked.

## Steps to Reproduce

   1. Navigate to cnn.com (may be redirected to edition.cnn.com, this is ok)
   2. Disable shields
   3. Shields still shows non-zero blocked count
   4. Navigating to an article, ads are still blocked

## Actual result:

Note non-zero count on shields, ads still blocked:
<img width="1034" alt="Screen Shot 2021-01-15 at 11 34 52 AM" src="https://user-images.githubusercontent.com/28145373/104753254-b959ab00-5725-11eb-8b3b-567045b0d23a.png">

## Expected result:
No count should be shown on shields and ads should be allowed (screenshot from 1.18.78):
<img width="1033" alt="Screen Shot 2021-01-15 at 11 35 46 AM" src="https://user-images.githubusercontent.com/28145373/104753333-d4c4b600-5725-11eb-8bcf-8cc1d9af2f8b.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.19.x, 1.20.x, 1.21.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.18.x no, 1.19.x yes
- Can you reproduce this issue with the beta channel? yes 1.20.x
- Can you reproduce this issue with the nightly channel? yes 1.21.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @rebron @brave/legacy_qa

**Comment by rebron** [comment]
Looks good on Windows and macOS universal M1, checked on cnn.com (and a few other websites turning shields on/off):

Brave | 1.21.7 Chromium: 88.0.4324.87 (Official Build) nightly (arm64)
-- | --
Revision | dd01ff8f58c65af81127ad5c105c79d5b571d8f3-refs/branch-heads/4324@{#1702}
OS | macOS Version 11.1 (Build 20C69)

<img width="1277" alt="Screen Shot 2021-01-16 at 6 24 19 PM" src="https://user-images.githubusercontent.com/5951041/104829515-7a148280-5829-11eb-92b8-8930404f5a44.png">

**Comment by kjozwiak** [comment]
awesome, thanks 👍 I also went through checks on Nightly via https://github.com/brave/brave-core/pull/7623#issuecomment-761841956. @brave/legacy_qa with this issue, it's important that we make sure that shields is still working as expected.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.19.85 Chromium: 88.0.4324.89 (Official Build) (64-bit)
-- | --
Revision | 4534be84786f5269fb52e9bf82643af61e2fedaf-refs/branch-heads/4324@{#1721}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

* verified that the shield icon is disabled/turns grey and doesn't display the blocking count when disabled
* verified that the shield icon is correctly displaying the number of blocked ads when enabled
* verified that ads weren't being displayed under `www.google.com` when `Trackers & ads blocked (aggressive)` was enabled
* verified that ads are being blocked on various websites when `Trackers & ads blocked (standard)` has been selected (Default)
* verified that selecting `Allow all trackers & ads` disabled ad blocking and ads start appearing on various websites
* verified that `Scripts blocked` was working correctly under https://www.blizzard.com/en-us

Shields enabled:
![image](https://user-images.githubusercontent.com/34715963/104955358-6d7b6000-59ca-11eb-8dc0-2cd927aa2a1f.png)

Shield disabled
![image](https://user-images.githubusercontent.com/34715963/104955453-926fd300-59ca-11eb-860c-14f9b454252f.png)

Encountered https://github.com/brave/brave-browser/issues/13635
