### ISSUE TITLE
Enable DNS over HTTPS UI on Linux

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#13617]
While Chromium has not yet [enabled DoH for Linux](https://bugs.chromium.org/p/chromium/issues/detail?id=1127671#c5) (presumably due to the fact that the [async resolver is disabled](https://docs.google.com/document/d/15Ss0OaJeb-T3g2RMwgikHvsC0CPKd-MLeGeetv1wYY4/edit#heading=h.xwlpjeb6ykdu) on that platform), it appears that Edge has enabled it:
https://pbs.twimg.com/media/ErkfCXVXEAA-zmN?format=jpg&name=large

I have confirmed that we could also expose the UI in Brave and it does appear to work, at least using the Cloudflare resolver explicitly and checking <https://1.1.1.1/help>.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.21.52 Chromium: 88.0.4324.152 (Official Build) dev (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/7660

![image](https://user-images.githubusercontent.com/34715963/107813497-c8596a80-6d70-11eb-93eb-fa422e9b350a.png)


Encountered https://github.com/brave/brave-browser/issues/12443
