### ISSUE TITLE
[Desktop] Brave News - publisher card title has incorrect font

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#13610]
## Incorrect
![image](https://user-images.githubusercontent.com/741836/104766069-cb841b00-571e-11eb-9c76-7b8537574828.png)
![image](https://user-images.githubusercontent.com/741836/104766056-c7f09400-571e-11eb-950c-b13019ef89fb.png)

## Correct
![image](https://user-images.githubusercontent.com/741836/104766101-d76fdd00-571e-11eb-9ae2-67ebeb692659.png)

Incorrect as of  1.21.2

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.28.74 Chromium: 92.0.4515.93 (Official Build) nightly (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Show Brave News`
6. scrolled down through content and took note of fonts with protruding stems (like `y`, `g`, etc.)

example | example
--------|----------
<img width="1792" alt="Screen Shot 2021-07-12 at 3 02 08 PM" src="https://user-images.githubusercontent.com/387249/125361897-db259a80-e322-11eb-9ce4-cd297f7378b1.png"> | <img width="1792" alt="Screen Shot 2021-07-12 at 3 02 38 PM" src="https://user-images.githubusercontent.com/387249/125361969-f690a580-e322-11eb-9030-43c88f8d098f.png">
