### ISSUE TITLE
Add a setting to automatically redirect for DNSLink

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13611]
Similar to this setting, we should have a setting to automatically redirect for DNSLink:
<img width="679" alt="Screen Shot 2021-01-15 at 1 19 50 PM" src="https://user-images.githubusercontent.com/831718/104770276-532d5200-573e-11eb-8b7f-469b1be15c3c.png">

Related issue:
https://github.com/brave/brave-browser/issues/13609

Feature name:
Automatically redirect to IPFS pages via DNSLink when possible

Description:
Automatically uses DNSLink to navigate to an IPFS version of a website when possible

We should also link DNSLink to this https://docs.ipfs.io/concepts/dnslink/  in the setting descriptions.

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` on `macOS` using build 

Brave | 1.23.31 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)


as part of verification for/in https://github.com/brave/brave-browser/issues/13609#issuecomment-796269225

**Comment by LaurenWags** [comment]
Changed label from `release-notes/include` to `release-notes/exclude` as this will be covered under https://github.com/brave/brave-browser/issues/13609 in the notes.
