### ISSUE TITLE
Brave Browser flickering

### ISSUE THREAD

**Issue by Kryptoxic** [brave/brave-browser#13618]
## Description 
Whenever I have a game in the background on borderless windowed mode, brave and chrome will start flickering whenever I scroll the page or type something. I use borderless windowed mode in my games because I have a dual monitor setup. I tried to set it to fullscreen mode and the flickering does go away but it's not ideal in my case due to the dual monitor. I have also tested other browsers like Firefox and there is no flickering on that browser. It seems that the issue only exists on chromium based browsers.

## Steps to Reproduce

   1.  Open a game in borderless windowed mode
   2.  Go to any webpage on brave and scroll or type
   3.  Screen should flicker

## Actual result:
I couldn't embed the gif so here's the link instead.

https://i.imgur.com/VW4tA8k.mp4
https://i.imgur.com/pA2VJU0.mp4

## Expected result:

No flickering occurs when scrolling or typing with a borderless windowed game in the background

## Reproduces how often: 
Easily reproduced. This issue has been reported quite recently in the r/brave_browser subreddit.

https://www.reddit.com/r/brave_browser/comments/kxbrdc/display_flickers_in_brave/

## Brave version (brave://version info)

Brave: 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)
Revision: 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS: Windows 10 OS Version 2009 (Build 19042.746)
JavaScript: V8 8.7.220.31
Flash: (Disabled)
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Command Line: "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,WinrtGeolocationImplementation,AutoupgradeMixedContent,LegacyTLSEnforced,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=AutofillServerCommunication,NotificationTriggers,SmsReceiver,TabHoverCards,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,TextFragmentAnchor,PrivacySettingsRedesign,IdleDetection,NetworkTimeServiceQuerying,PasswordCheck,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end
Executable Path: C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path: C:\Users\ryanc\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

## Version/Channel Information:
Tested this on both beta and nightly and it also occurs on those channels.

## Other Additional Information:
Enabling and disabling shields does not affect it. I have tested this with chrome and it does occur on that browser as well which makes me think that it might be a chromium issue. I tested firefox and sure enough, it does not flicker.

**Comment by ryanbr** [comment]
Does disabling hardware acceleration in `brave://settings/system` help?

**Comment by Kryptoxic** [comment]
Yes it does help but it makes the scrolling choppy because I'm using a high refresh rate monitor. I did some research and it might be due to the latest nvidia drivers 461.09. I'll try downgrading to the previous drivers to try when I get back to my computer later.

You could try to replicate this issue to see if it really is due to the nvidia driver but from what I read on r/nvidia and the nvidia forums, people are experiencing flickering even with youtube.

**Comment by ryanbr** [comment]
Did changing nvidia drivers help @Kryptoxic ? I know some integrated graphics drivers, and older graphic drivers (in Linux and Windows) can cause issues

**Comment by Kryptoxic** [comment]
Ah yes forgot to reply to you @ryanbr . I downgraded the drivers back to the previous version and it seems to have solved the flickering. At this point, I'm not sure if it has to do with the nvidia drivers or chromium.

**Comment by ryanbr** [comment]
I would look into the nvidia forums, but test either beta drivers or every official driver going forward too see if its fixed in future.  Thanks for following it up.

@Kryptoxic

**Comment by Kryptoxic** [comment]
Hey @ryanbr , there seems to be a hotfix driver on nvidia's website. Linking it for anyone else that happens to chance upon this issue.

https://nvidia.custhelp.com/app/answers/detail/a_id/5152/kw/hotfix

**Comment by fusionneur** [comment]
I am also experiencing broswer flickering/dissapearing parts of the browser whenever I have a game (in borderless or extended maximized window) in behind and browser focused.
 This started happening in this month.

**Comment by condoatlanta** [comment]
Had this happen on an LG big-screen TV we use with a home-built media center while using Brave. Software updates brought up an Nvidia Driver. Updated to the new Nvidia driver today and appears to solve the issue.

**Comment by fusionneur** [comment]
Haven't happened for me in a while as well..
