### ISSUE TITLE
Background images of the new tab should be cached or optimized

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1361]
Carried over from https://github.com/brave/browser-laptop/issues/6503

The caching aspect is likely already fixed (meaning users should properly cache the images once they're loaded once, something that was broke in browser-laptop)- but we can also consider packaging these with the browser (so that no outbound connection is made)

> ## Updated plan, per @petemill 
> - have hard-coded property in wallpaper JSON that specifies if image is bundled. 
> - In browser process, start a download process when all intensive tasks have completed (perhaps when initial windows have loaded) that downloads the other images. (or if we want to be more polite, perhaps only download 1 new image every time a new tab page is opened...?)
> - store in state which images have been downloaded, verify that they are on disk (or just find which images have been downloaded by looking in 'wallpaper' dir, and don't save to session-store).
> - new tab page reads from wallpaper json but only selects a random item from filtered list where item === bundled or item === downloaded

**Comment by rebron** [comment]
Everything is changed to be local.

**Comment by kelna** [comment]
So wallpapers could be a little bit of bigger resolution and less compression maybe? :)

**Comment by TKList** [comment]
How about a way to turn off the image altogether?

**Comment by merqrial** [comment]
@TKList There is an option on the bottom right in the latest version.
