### ISSUE TITLE
"on YouTube" missing for YT creators on panel, AC list, tips lists

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13616]
## Description 

When opening the rewards panel while on a YT creator page, panel should say something like "<creator> on YouTube". The "on YouTube" part is missing. 

Other creator types "on GitHub", "on Reddit", etc are working as expected.

Reproduces on 1.18.x, 1.19.x, 1.21.x. Maybe related to a Greaselion update?

## Steps to Reproduce

   1. Clean profile (panel info gets cached and is not currently cleared - see https://github.com/brave/brave-browser/issues/6059, so if you visited a page before it will show correctly) 
   2. Click on panel and join Rewards
   3. Navigate to youtube.com/user/jjdsampson
   4. Once page loads, open panel

## Actual result:

"on YouTube" is missing
<img width="407" alt="Screen Shot 2021-01-15 at 4 49 55 PM" src="https://user-images.githubusercontent.com/28145373/104782552-621dff80-5752-11eb-8c5e-6650f87c06ea.png">

If you tip or add to AC list, name will be incorrect here as well.

## Expected result:
show "on YouTube" after creator's name

## Reproduces how often: 

 easily

## Brave version (brave://version info)

Brave | 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)
-- | --
Revision | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS | macOS Version 10.15.7 (Build 19H15)

Brave | 1.19.84 Chromium: 88.0.4324.87 (Official Build) (x86_64)
-- | --
Revision | dd01ff8f58c65af81127ad5c105c79d5b571d8f3-refs/branch-heads/4324@{#1702}
OS | macOS Version 10.15.7 (Build 19H15)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @rebron @emerick @zenparsing @brave/legacy_qa

**Comment by emerick** [comment]
I believe we need to pass in the media type here:

https://github.com/brave/brave-site-specific-scripts/blob/master/scripts/brave_rewards/publisher/youtube/publisherInfo.ts#L213

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

#### `Test Case 1` (New Profile/Logged into KYC/Verified account)

**`Panel`** | **`AC list`** | **`Monthly Contribution`** | **`Tip`**
------------|--------------|------------------------------|-------------
![image](https://user-images.githubusercontent.com/2602313/105949962-912e4e00-603b-11eb-9c77-2fd39cc8eb89.png) | ![image](https://user-images.githubusercontent.com/2602313/105950178-f3874e80-603b-11eb-854e-2d0c8e93a327.png) | ![image](https://user-images.githubusercontent.com/2602313/105950315-29c4ce00-603c-11eb-9233-f1e1ce49681c.png) | ![image](https://user-images.githubusercontent.com/2602313/105950326-2e898200-603c-11eb-961f-522398cc6caa.png)

#### `Test Case 2` (New Profile/Not logged into Uphold)

![image](https://user-images.githubusercontent.com/2602313/105950611-ae175100-603c-11eb-88ec-ee1757f9aad6.png)

**Comment by kjozwiak** [comment]
@emerick looks like the above is still occurring if you upgrade from `1.0.41` --> `1.0.44` and you were already in the above state. Example:

![image](https://user-images.githubusercontent.com/2602313/105951761-8d4ffb00-603e-11eb-8556-86ae627d1d90.png)

@LaurenWags are you seeing the same issue? STR:

* launch `1.19.86 CR: 88.0.4324.96` and log into a KYC/Verified account
* preproduce the original issue and add https://youtube.com/user/jjdsampson into the AC list
* update to `1.0.44` using `--use-dev-goupdater-url`

**Comment by LaurenWags** [comment]
@kjozwiak you will still see this issue on upgrade afaik bc the panel info is cached and never expires unfortunately. Issue for that is captured here: https://github.com/brave/brave-browser/issues/6059

**Comment by emerick** [comment]
Yep, @LaurenWags is right it's the caching issue.

**Comment by kjozwiak** [comment]
awesome, thanks @LaurenWags 👍 In that case, the above looks good in `Win 10 x64`.
