### ISSUE TITLE
installing brave breaks video playback in all browsers

### ISSUE THREAD

**Issue by FrozenVoid** [brave/brave-browser#13619]
## Description 

mx linux 19, installing brave 87 from https://brave-browser-apt-release.s3.brave.com 
 breaks video playback in all browsers(both based on firefox,chrome). webm& youtube videos stall with loading circle, directly viewing webm file allows to scroll
to specific frame but videos refuse to play.

Uninstalling brave and brave-keyring fixed the problem.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

Videos don't play

## Expected result:
Video playback.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards?
No 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@FrozenVoid Our latest version is 1.23.87. Can you update to that latest version and let us know if you're still having this issue?
