### ISSUE TITLE
Some https pages cause brave to half-crash when NSS < 3.26, with no user-perceivable feedback

### ISSUE THREAD

**Issue by acli** [brave/brave-browser#13623]
## Description 
On old versions of Ubuntu (close to 14.04), the system NSS is < 3.26. It seems that on these systems brave will run, will work on http pages, but on *some* https pages (including Brave’s official support pages) it will leave itself stuck in a half-crashed state where the UI continues to run but the network engine stops working. The UI provides no indication that it has half-crashed except for a spinning wheel that doesn’t go away.

## Steps to Reproduce

   1. Find an old Ubuntu. 14.04 will probably work (15.10 definitely works).
   2. Install brave using the official instructions.
   3. Run brave
   4. Open some http pages to verify it works
   5. Open https pages until it half-crashes as described above; Brave’s support site should trigger this

## Actual result:
- Spinning wheel that doesn’t go away
- Log messages on terminal that include:

    FATAL:nss_util.cc(147)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
    ERROR:network_service_instance_impl.cc(286)] Network service crashed, restarting service.

## Expected result:
There are a range of possible expected results, including:
- Brave recovers from the NSS < 3.26 condition and the spinning wheel goes away
- The UI shows some visual indication that the network service has crashed due to NSS < 3.26
- The website includes a note saying that while brave will run on versions of Ubuntu close to 14.04, the browser will not run without some system tweaks

## Reproduces how often: 
Hard to tell since I have only one working install of Ubuntu, but based on what’s happening this is likely always reproducible on old versions of Ubuntu

## Brave version (brave://version info)

Brave | 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)
-- | --
Revision | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Will verify later if needed
- Can you reproduce this issue with the nightly channel? Will verify later if needed

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? Will verify later if needed

## Miscellaneous Information:
On my system my workaround is to use LD_LIBRARY_PATH so that brave finds an NSS ≥ 3.26 from Firefox Nightly.

I think the main problem here is that there is no indication of failure in the UI. The user has to peek into the terminal to even realize the a problem is not going away, but because of the large number of log messages in the terminal the user might miss the relevant error messages.

**Comment by fmarier** [comment]
Thanks for reporting this problem and providing all of these details. It is a very strange problem indeed.

We've updated our Linux installation page to bring the minimum Ubuntu version to 16.04: https://brave.com/linux/

Given that support for this version of Ubuntu [ended two years ago](https://wiki.ubuntu.com/Releases), we would strongly urge users to upgrade to Ubuntu 20.04 (or 18.04 at least) so that they can continue to get security updates.
