### ISSUE TITLE
https://static1.brave.com/ Uses Google 404 Page

### ISSUE THREAD

**Issue by rhclayto** [brave/brave-browser#13629]
## Description 
The domain https://static1.brave.com/ uses a Google 404 error page.

## Steps to Reproduce

   1. Browse to https://static1.brave.com/ .

## Actual result:
Google 404 error page is served from Fastly CDN IP address.

![image](https://user-images.githubusercontent.com/13597641/104854613-f7d99c00-58c4-11eb-819e-15342e0690fb.png)

## Expected result:
A Brave 404 error page is served on 404 errors.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Newest release.

Brave | 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)
Revision | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}

## Version/Channel Information:
Release.

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? Didn't try.
- Can you reproduce this issue with the nightly channel? Didn't try.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not applicable.

## Miscellaneous Information:
```bash
# curl --head static1.brave.com
HTTP/1.1 301 Moved Permanently
Server: Varnish
Retry-After: 0
Location: https://www.gstatic.com/
Content-Length: 0
Accept-Ranges: bytes
Date: Sun, 17 Jan 2021 22:16:27 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-sea4431-SEA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1610921787.192109,VS0,VE0
```

What's up with that?

**Comment by jonathansampson** [comment]
That domain is a proxy to gstatic.com; it isn't meant for direct navigation. Instead, resources are requested from that endpoint. For instance, when you setup Brave on a new Windows machine, the browser calls out to [https://static1.brave.com/…/plugins_win.json](https://static1.brave.com/chrome/config/plugins_3/plugins_win.json) for the retrieval of security information regarding supported plugins. The URL varies by platform; here's the corresponding code in Chromium: [plugins_resource_service.cc](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/plugins/plugins_resource_service.cc;drc=235fc62b909c81b7cd8c8b9433e399b28cdaaa05;l=59) I hope this helps!
