### ISSUE TITLE
marriot.com does not load with shields up

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#1362]
www.marriott.com does not load with shields up in the default configuration.  

Results in an empty grey page

## Brave version (chrome://version info)
Version 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)

### Website problems only:  
Lowering shields causes the page to load correctly

**Comment by snyderp** [comment]
<img width="1602" alt="screen shot 2018-09-30 at 10 37 04 pm" src="https://user-images.githubusercontent.com/76526/46271418-5f575c00-c501-11e8-80a4-c4b9661217f5.png">

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows
