### ISSUE TITLE
100% CPU when running speedtest or viewing a long video

### ISSUE THREAD

**Issue by PaulB47** [brave/brave-browser#13624]
## Description 

Running ookla speedtest causes 100% CPU.

## Steps to Reproduce

   1. Open Brave with a few tabs
   2. Use 1 tab to get to ookla speedtest site, start the test.
   3. A few seconds into download test, CPU (measured by Conky or MX Linux "Task Manager") goes to 100%
   4. Browser task manager freezes so is not useful
   5. After download test finishes, CPU goes down and system becomes functional again OR speedtest site issues a "Download test error".

## Actual result:

As above. Also, if viewing a video, this occurs now and then in an unpredictable fashion. Of course, the video stops for a while, usually about 15 seconds.

## Reproduces how often: 

Reproduced on my machine reliably.

## Brave version (info found on brave://version)

Brave | 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)
-- | --
Revision | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS | Linux

## Version/Channel Information:

Unknown
- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?
- All of above are unknown.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
All of above are unknown. However the problem also exists with the Dissenter Browser. I have been seeing this for a few months now. I have wondered if the transfer is happening using PIO rather than DMA. This does not occur on my system when using the Firefox browser.

## Miscellaneous Information:

The following might have an effect:
High internet capacity (I have seen 500Mbps using Firefox)
MX Linux 19.3 patito feo
Slow system (Dell Inspiron One 2330, with i3 processor; OR Asus i5 laptop)
Either wifi or ethernet 10/100/1000
I am booting from a USB3.0 flash drive
brave://flags/#brave-adblock-cosmetic-filtering is enabled

**Comment by ryanbr** [comment]
Speedtest will spawn several websocket requests to attempt to saturate the bandwidth, for lower end systems cpu usage will increase by quite a bit. I did check out  (IP address is VPN, so actual speed is much slower)

![speedtest](https://user-images.githubusercontent.com/1659004/105117942-463fa280-5b32-11eb-8ca9-1ceea944c12b.gif)

**Comment by PaulB47** [comment]
I'm wondering what the CPU is doing. It doesn't take much to set up a DMA I think. It just concerns me that this should fail so ungracefully, since Firefox doesn't. Should Brave (or some process thereof) be set at a lower priority, so the computer doesn't lock up? I can still move my cursor when this happens, but can't even switch browser tabs.

If I'm not mistaken, an HD video needs only about 5Mb/s, and there are just two streams in my home at most (when not running speedtest). If too much data is being shoved down the pipe, isn't there some handshake to simply throttle it down some?

I'm only dwelling on speedtest because it drives things to 100% right away, every time; while watching a video, you have to wait some.

**Comment by ryanbr** [comment]
I could see not-so-modern hardware , speedtest and its spawning websocket requests to easily drive up CPU to 90-100% without too much issue. 

The video playback issue would be different, depending on the CPU/GPU older systems may struggle to playback 1080p or better. Assuming it youtube, you could install https://chrome.google.com/webstore/detail/h264ify/aleakchihdccplidncghkekgioiakgal?hl=en which may improve playback (also test with hardware acceleration disabled/enabled with this extension)

**Comment by ryanbr** [comment]
Any update @PaulB47  ? Does the extension  and/or newly release Brave 1.19.86 help?

**Comment by PaulB47** [comment]
It's a little hard to say, since I got frustrated with the Inspiron One and retired it, in favor of the slightly faster Asus Q302L. Speedtest.net still goes up to 100% and stays there, finally giving a "Download test error", so that looks about the same.

On the other hand, watching a video from viki.com, rather than the long periods stuck at 100% and halting the video for 20 seconds, I see a rare spike now and then, but mostly the CPU meter stays reasonable, and the video never stops. There are still times when things go a bit unresponsive (e.g. temporarily unable to change tabs) but that doesn't matter so much for watching videos.

Youtube videos were never much of a problem that I can recall.

Sorry if this information is not much of a controlled experiment. At least now I don't have to run Firefox to see a video. This problem does suggest a need to check out performance of slow machines, and comparisons with how such machines running other browsers handle it. I will "close with comment", I hope that is all right.
