### ISSUE TITLE
Background video playback doesn't work on certain websites (Android)

### ISSUE THREAD

**Issue by binarweb** [brave/brave-browser#13626]
## Description

Updating "Brave Private Browser: Fast, secure web browser" from Google Play to the latest version  breaks completely the background video playback.

## Steps to reproduce

   1. Use an older version on Brave (1.5.2 in my case) and the background video playback works (e.g. YouTube) ~80% of the time
   2. Update the app to the latest version from Google Play (1.18.78) and the background video playback is broken

## Actual result

As stated above.

## Expected result

As stated above.

## Issue reproduces how often

Always.

## Version/Channel Information:

As stated above.

## Device details

Samsung phone with Android 8.1.0
   
## Brave version

As stated above.

### Additional information

- the older version of Brave required a refresh of the webpage to have a functional background video playback  
- the latest version no longer has a background video playback, no matter what I do (refreshing the webpage or switching to desktop version)
- while, on YouTube, the background video playback is broken, for some other websites it works (e.g. SoundCloud)

**Comment by binarweb** [comment]
The problem was solved by updating the browser.
This issue can be closed.

**Comment by srirambv** [comment]
Closing based on previous comment
