### ISSUE TITLE
Update l10n for cr88 - 1.19.x release.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#13628]
Download the latest l10n from Transifex.

Test plan:
Per prior @kjozwiak's instructions (#10735 (comment)):

@brave/legacy_qa should run through a few locals just to make sure that nothing obvious has regressed. Shouldn't spend too much time on this though

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.85 x64 build
- Verified on multiple languages and no regressions
----------
Verification passed on Samsung Tab A with Android 10 running 1.19.85 x64 build
- Verified on multiple languages and no regressions

**Comment by kjozwiak** [comment]
Thanks @srirambv 👍 Going to label this as `QA/No` as https://github.com/brave/brave-browser/issues/13639 will be included in the next build. There has been no QA done via desktop so we'll just finish verifications via https://github.com/brave/brave-browser/issues/13639.
