### ISSUE TITLE
`Include in Auto-contribute` toggle is hidden on some locales

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#13634]
This is a regression introduced in 1.18.x. Not reproducible in 1.17.x

The `Include in Auto-contribute`  toggle is hidden in Polish (PL) locale

## Steps to Reproduce

1. Clean profile
1. Run Brave in Polish(PL) locale
1. Enable Rewards
1. Open `3zsistemi.si`
1. Open Rewards Panel

## Actual result:

The `Include in Auto-contribute`  toggle is hidden
![image](https://user-images.githubusercontent.com/34715963/104903807-c58d7480-5980-11eb-8fb6-81dbce43379f.png)

## Expected result:
The `Include in Auto-contribute`  toggle is shown
![image](https://user-images.githubusercontent.com/34715963/104904873-f6ba7480-5981-11eb-9769-e67293514000.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

**Reproducible on**

Brave | 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Ubuntu 18.04 LTS

Brave | 1.19.85 Chromium: 88.0.4324.89 (Official Build) (64-bit)
-- | --
Revision | 4534be84786f5269fb52e9bf82643af61e2fedaf-refs/branch-heads/4324@{#1721}
OS | Ubuntu 18.04 LTS

Brave | 1.20.81 Chromium: 88.0.4324.87 (Oficjalna wersja) dev (64-bitowa)
-- | --
Wersja | dd01ff8f58c65af81127ad5c105c79d5b571d8f3-refs/branch-heads/4324@{#1702}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.21.7 Chromium: 88.0.4324.87 (Oficjalna wersja) nightly (64-bitowa)
-- | --
Wersja | dd01ff8f58c65af81127ad5c105c79d5b571d8f3-refs/branch-heads/4324@{#1702}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24544)

**Not reproducible on**

Brave | 1.17.75 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @brave/legacy_qa @rebron @emerick @zenparsing

**Comment by emerick** [comment]
It seems like the label text isn't reflowing and instead obscures the toggle button.

**Comment by zenparsing** [comment]
@emerick Good call -  should be a small CSS fix.

**Comment by stephendonner** [comment]
Verified `FIXED` using the steps to reproduce from this Issue, on


Brave | 1.21.47 Chromium: 88.0.4324.152 (Oficjalna wersja) beta (x86_64)
-- | --
Wersja | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
System operacyjny | macOS Wersja 11.2 (kompilacja 20D64)

<img width="1195" alt="Zrzut ekranu 2021-02-8 o 4 32 59 PM" src="https://user-images.githubusercontent.com/387249/107299085-873d1f80-6a2b-11eb-9085-cc5437103583.png">
