### ISSUE TITLE
Merge Dissenter Browser features with Brave

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [brave/brave-browser#13632]
https://dissenter.com

It may sound crazy, but I would like to see an IPFS connected comment section for every website on the internet with brave. The idea is really interesting. Possible connections with the BAT ecosystem too.

Sorry if this is not an issue, I just want to get some inspiration out.

**Comment by BrendanEich** [comment]
See https://twitter.com/BraveSampson/status/1350685642846572546.

Brave is not merging anything from an abandoned, badly made, negligently under-maintained fork.

We also don't impose, or optionally embed, any identity system on users: not Google's and certainly not Gab's. Subjective shared-world comments systems for users who want them sound good and should be built as extensions. Start your own in a fresh repo. One-world social comments create the same kind of dystopian weapon as other social networks constitute. Brave is not a social network.

**Comment by hp8wvvvgnj6asjm7** [comment]
Well, fully agree on identity systems, which I didn't mention exactly. 
My point is that comment sections all over the web have been closed, censored and manipulated. This is where 
The dystopian scenario is already here: see disqus.
A more open alternative would be great. And if it can be made less centralized using IPFS too.

Of course it would already be great to have it as an extension.
I didn't mean to merge the codebase, but rather bring the option of an open commenting system into the browser, may it be as an extension or plugin.
