### ISSUE TITLE
Saved Credit card info modal shows Sign in to Chrome

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1363]
## Description 

Reported by @johnnyryan ,Saved Credit card info modal shows Sign in to Chrome

## Steps to Reproduce

   1. Enter credit card details on a page
   2. Click on save prompt 
   3. Shows sign in to Chrome 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46290412-c9035480-c559-11e8-94ff-8c0da52b2469.png)

## Expected result:
Should not show Sign in to Chrome message

## Reproduces how often: 

Easy 

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | All

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy for milestone prioritization

**Comment by rebron** [comment]
@srirambv I think this will launch with airbnb. 
Does this help https://stackoverflow.com/questions/7223168/how-to-trigger-autofill-in-google-chrome/41965106#41965106

**Comment by hferreiro** [comment]
@bbondy in this case, I cannot just modify the strings involved. The dialog is created with a `BubbleSyncPromoView` which needs a format string and another string which will be linked to the Google sign in: https://cs.chromium.org/chromium/src/chrome/browser/ui/views/autofill/save_card_manage_cards_bubble_views.cc?l=56

I guess we can delete or replace the dialog completely.

**Comment by bbondy** [comment]
I think you can use a chromium_src override to just change the string that is used to another one from our own grd in src/brave using #define / #undef

**Comment by hferreiro** [comment]
Just modifying the strings is not enough. `IDS_AUTOFILL_SIGNIN_PROMO_MESSAGE_DICE_DISABLED` is supposed to contain a placeholder and `IDS_AUTOFILL_SIGNIN_PROMO_LINK_DICE_DISABLED` needs to be a non-empty string to be styled as a link.

**Comment by hferreiro** [comment]
Sorry, the issue was closed when pushing to a fork. Btw, I used `src/components/test/data/autofill/credit_card_upload_form_address_and_cc.html` to test this issue.
