### ISSUE TITLE
Update l10n for cr88 - 1.19.x release, Part II.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#13639]
Follow-up to #13628 

Pull down finished l10n strings that weren't available at the time of the initial pull.

This only affects Romanian l10n strings.

Test plan:
Per prior @kjozwiak's instructions (#10735 (comment)):

@brave/legacy_qa should run through a few locals just to make sure that nothing obvious has regressed. Shouldn't spend too much time on this though

**Comment by kjozwiak** [comment]
Waiting on new `1.19.x` build that will include `88.0.4324.96` 👍

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)


```


<details>
<summary>Romanian</summary>

- Verified few areas like NTP, Dashboard settings, rewards and Binance panel, Shield settings, Hamburger menu items etc translation in Romanian
**welcome screen**
![image](https://user-images.githubusercontent.com/38657976/105034270-3d41c900-5a7f-11eb-880b-7add626e4bb4.png)
![image](https://user-images.githubusercontent.com/38657976/105034357-5e0a1e80-5a7f-11eb-8123-988bc253a9e3.png)
![image](https://user-images.githubusercontent.com/38657976/105034374-65312c80-5a7f-11eb-94b6-81fb6cf183c1.png)
![image](https://user-images.githubusercontent.com/38657976/105034391-6bbfa400-5a7f-11eb-86ec-0ca33fdf372c.png)
![image](https://user-images.githubusercontent.com/38657976/105034417-74b07580-5a7f-11eb-9e62-c8c42dc249d4.png)

**Rewards and panel**
![image](https://user-images.githubusercontent.com/38657976/105034475-8a259f80-5a7f-11eb-9873-8761e62a5ebd.png)
![image](https://user-images.githubusercontent.com/38657976/105034525-9a3d7f00-5a7f-11eb-80b6-6fe009ad06c7.png)
![image](https://user-images.githubusercontent.com/38657976/105034561-a7f30480-5a7f-11eb-9f18-293ed24c86e8.png)
![image](https://user-images.githubusercontent.com/38657976/105034584-b2150300-5a7f-11eb-82d9-ded5d4cf25e9.png)
![image](https://user-images.githubusercontent.com/38657976/105034602-b9d4a780-5a7f-11eb-890d-f6fe8f6d17d3.png)
![image](https://user-images.githubusercontent.com/38657976/105034643-c6590000-5a7f-11eb-88ca-55a44066c72c.png)
![image](https://user-images.githubusercontent.com/38657976/105034717-df61b100-5a7f-11eb-9a12-73204cd794be.png)
![image](https://user-images.githubusercontent.com/38657976/105034745-e8eb1900-5a7f-11eb-9408-c94faf792ff6.png)
![image](https://user-images.githubusercontent.com/38657976/105034845-189a2100-5a80-11eb-8d15-ee396842b3b8.png)


</details>
