### ISSUE TITLE
Remove `deep-freeze-node` dependency: the project is no longer installable on mac arm

### ISSUE THREAD

**Issue by Kwadz** [brave/brave-browser#13631]
I can't install the project. Steps to reproduce the issue:

```
git clone git@github.com:brave/brave-browser.git
cd brave-browser
npm install
cd src
rm -rf brave # otherwise error "directory already exists", BTW that should be mentioned in the doc
cd ..
npm run init
```

And I get:  
```
    fatal: repository 'undefined' does not exist
```

It seems the function [`getNPMConfig`](https://github.com/brave/brave-browser/blob/a2ff0345c662cd2add684688af6e5c7f598ef7e8/lib/util.js#L4) relies on env vars that are obviously not present on my system. But there is no mention about it in the Brave installation procedure.

What's wrong here?

Just in case, I mention that I'm on macOS 10.14.6 (Mojave).

**Comment by Aragar199** [comment]
I also encountered the same issue. Problem is that the path to the repository url is broken.

There is a string replacement that is making `-` into `_` at https://github.com/brave/brave-browser/blob/master/lib/util.js#L5

So when brave-browser goes looking for `brave-core` in package.json, it can never find it because the key is changed to `brave_core` and it ends up `undefined`

You can change it to `brave_core` in https://github.com/brave/brave-browser/blob/master/package.json#L38

That fixes it there, but then it breaks in brave-core which has its own `getNPMConfig` that does **not** do the same string replacement to change `-`. So it scans for `brave-core` but never finds it because it is `brave_core` now.

You can then change at https://github.com/brave/brave-core/blob/master/build/commands/lib/config.js#L77
`brave-core` to `brave_core` so when it scans for the repo url it can find it because it is now `brave_core` in brave-browser/package.json.

Then change the repo url and branch name to point to the brave-core version that has this change:

![Screen Shot 2021-01-19 at 8 45 30 AM](https://user-images.githubusercontent.com/14187644/105067037-2f1a8b00-5a34-11eb-87d1-fc538946a668.png)

I was able to install using these steps, but it's a patch job and should probably have a real fix instead.

**Comment by Aragar199** [comment]
Fix is here https://github.com/brave/brave-browser/pull/14089/files, pending review. I didn't see anything else using that util.getNPMConfig so I figured it would be safe to just remove the string replacement and added a check if the src/brave folder already exists.

**Comment by bsclifton** [comment]
hmm - I'm not running into any problems here on Windows. If you're seeing this, my first guess would be that you don't have Node LTS installed (we may have problems if you use latest version of Node.js)

The folder is `src/brave` so there shouldn't be any problem with `-` or `_`

**Comment by ShivanKaul** [comment]
FWIW, I ran into the same issue on a Mac Pro 10.15.7 (+ the issue of an installation failing requiring me to go and explicitly `rm -rf src/brave`)

**Comment by bridiver** [comment]
@Kwadz `npm run init` only tries to create src/brave if the `src/brave/.git` doesn't exist. If these are the only steps you have done
```
git clone git@github.com:brave/brave-browser.git
cd brave-browser
npm install
```
then `src/brave` would not exist

**Comment by Kwadz** [comment]
Thanks @bridiver, in that case I think [this section](https://github.com/brave/brave-browser/blob/master/README.md#clone-and-initialize-the-repo) of the documentation should be updated:

```
git clone git@github.com:brave/brave-browser.git
cd brave-browser
npm install

# this takes 30-45 minutes to run
# the Chromium source is downloaded which has a large history
npm run init
```

It does not even match with [this section](https://github.com/brave/brave-browser/blob/master/CONTRIBUTING.md#making-changes):

```
# root where project is cloned
cd ~/brave-browser/
git remote add bsclifton git@github.com:bsclifton/brave-browser.git
git fetch bsclifton
# root for the `brave-core` repo
cd src/brave
git remote add bsclifton git@github.com:bsclifton/brave-core.git
git fetch bsclifton
```

I think the process in the documentation should be consistent and unified.

**Comment by bridiver** [comment]
Not sure where that came from cc @bsclifton, I’ll check out the PR change and make sure all the docs are current either this weekend or first thing Monday

**Comment by bsclifton** [comment]
@Kwadz that part can look confusing, but it's correct. I believe I understand the disconnect

Basically, all you need to do is run `npm run init` and `src/brave` will be setup for you.

However- if you're actively making changes in a fork, you'll need to add YOUR remote to the `src/brave` repo. Only Brave employees have access to push to brave/brave-core - so you'll need to push to your fork. I hope that makes sense.

**Comment by bridiver** [comment]
@bsclifton I reopened because there is still an outstanding issue with the npm config

**Comment by bridiver** [comment]
@Aragar199 I'm not able to reproduce the issue. Can you provide info on node, npm and OS version. https://github.com/brave/brave-browser/pull/14089 breaks the install for me.

**Comment by Kwadz** [comment]
I think the documentation should be clarified.

> However- if you're actively making changes in a fork, you'll need to add YOUR remote to the src/brave repo. Only Brave employees have access to push to brave/brave-core - so you'll need to push to your fork if you're hoping to submit a pull request. I hope that makes sense. If you're not needing to submit a PR, you can skip the Making changes section

You seem to tell the section [Clone and initialize the repo](https://github.com/brave/brave-browser/blob/master/README.md#clone-and-initialize-the-repo) is for Brave employees and the section [Making change](https://github.com/brave/brave-browser/blob/master/CONTRIBUTING.md#making-changes) for contributors.

If there is a **different procedure** for Brave employees and a for contributors, that **should be mentioned**.

> Basically, all you need to do is run npm run init and src/brave will be setup for you.

This `npm run init` is not even mentioned in the section [Making change](https://github.com/brave/brave-browser/blob/master/CONTRIBUTING.md#making-changes). I think all the steps of the procedure should be mentioned in this section, or at least with a link to the proper section to build the project.

My two cents about the doc:

For example in the section [Clone and initialize the repo](https://github.com/brave/brave-browser/blob/master/README.md#clone-and-initialize-the-repo), "Clone and initialize the repo" for what? It's not clear that part is not for contributing, may be we should mention something not to confuse with this section.

Also, the section [Making change](https://github.com/brave/brave-browser/blob/master/CONTRIBUTING.md#making-changes) does not mention anything about `npm run init`. So, it's not complete and the reader think we should go to [Clone and initialize the repo](https://github.com/brave/brave-browser/blob/master/README.md#clone-and-initialize-the-repo) to continue the setup.

I'd also update in [Making change](https://github.com/brave/brave-browser/blob/master/CONTRIBUTING.md#making-changes):
> Once you've cloned the repo to your computer, you're ready to start making edits!
to
> Once you've cloned your fork to your computer, you're ready to start making edits!

Hope my new eyes can help to clarify the doc and therefore make it easier for new contributors.

**Comment by Aragar199** [comment]
@bridiver Thanks for following up on this. Before I submitted the PR to fix, I checked it on my Windows laptop as well and saw the same issue with the repo url showing up unidentified. However, I just checked the master branch on Mac and Windows and there is no longer an issue. I don't have anything to follow up on if @Kwadz is also no longer seeing an issue.

**Comment by bsclifton** [comment]
@Kwadz there's only a different procedure if you make edits to the code. Everyone has read access to the repo, but creating branches on the remote and pushing to the remote is limited to employees

**Comment by bridiver** [comment]
I agree that all the setup instructions should be together so we’ll reorganize things a little bit

**Comment by Kwadz** [comment]
> creating branches on the remote and pushing to the remote is limited to employees.

@bsclifton, you already explained it, thanks but this is not the point. The problem, IMHO, is the contributor guide is not clear in addition to be incomplete. I guess you didn't see what I wanted to point out. I think it's important for a project installation not to be difficult for new contributors. Anyway, I can create a specific issue about this, not to pollute this one with too much extrapolation 🙂 

@Aragar199, about the [Clone and initialize the repo section](https://github.com/brave/brave-browser/blob/master/README.md#clone-and-initialize-the-repo), I tested again the following:

```
$ git clone git@github.com:brave/brave-browser.git
Cloning into 'brave-browser'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 33841 (delta 10), reused 15 (delta 7), pack-reused 33818
Receiving objects: 100% (33841/33841), 15.34 MiB | 1001.00 KiB/s, done.
Resolving deltas: 100% (23393/23393), done.
$ cd brave-browser
$ npm install

added 28 packages, and audited 28 packages in 3s

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 7.0.15 -> 7.5.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.5.4
npm notice Run npm install -g npm@7.5.4 to update!
npm notice
$ cd src
$ rm -rf brave # otherwise error "directory already exists", BTW that should be mentioned in the doc
$ cd ..
$ npm run init

> brave@1.22.39 init
> node ./scripts/init.js

Performing initial checkout of brave-core
Cloning brave-core [undefined] into /Users/myuser/Code/test/brave-browser/src/brave...
------------------------------------------------------------------------------------------------------------------------------------------------------
/Users/myuser/Code/test/brave-browser/src/brave
> git clone  .

fatal: repository 'undefined' does not exist

npm ERR! code 1
npm ERR! path /Users/myuser/Code/test/brave-browser
npm ERR! command failed
npm ERR! command sh -c node ./scripts/init.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2021-02-22T10_43_01_075Z-debug.log
```

I also tested with exactly [the steps from the doc](https://github.com/brave/brave-browser/blob/master/README.md#clone-and-initialize-the-repo) (without removing the brave dir):

```
$ git clone git@github.com:brave/brave-browser.git
Cloning into 'brave-browser'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 33841 (delta 10), reused 15 (delta 7), pack-reused 33818
Receiving objects: 100% (33841/33841), 15.34 MiB | 765.00 KiB/s, done.
Resolving deltas: 100% (23393/23393), done.
$ cd brave-browser
$ npm install

added 28 packages, and audited 28 packages in 2s

found 0 vulnerabilities
$ npm run init

> brave@1.22.39 init
> node ./scripts/init.js

Performing initial checkout of brave-core
Cloning brave-core [undefined] into /Users/myuser/Code/test/brave-browser/src/brave...
------------------------------------------------------------------------------------------------------------------------------------------------------
/Users/myuser/Code/test/brave-browser/src/brave
> git clone  .

fatal: repository 'undefined' does not exist

npm ERR! code 1
npm ERR! path /Users/myuser/Code/test/brave-browser
npm ERR! command failed
npm ERR! command sh -c node ./scripts/init.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2021-02-22T11_50_06_743Z-debug.log
```

**Comment by Aragar199** [comment]
Thank you for confirming @Kwadz I just checked and was able to reproduce again. Realized that it was skipping trying to clone in to the folder since it checks if the `.git` file is already present in `src/brave`. I changed the name of the folder to a random one `brave23` so that it would try to clone in to a new directory and got the error again:

```
$ npm run init

> brave@1.22.14 init
> node ./scripts/init.js

Performing initial checkout of brave-core
Cloning brave-core [undefined] into /Users/myuser/brave-browser/src/brave23...
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/Users/myuser/brave-browser/src/brave23
> git clone  .

fatal: repository 'undefined' does not exist

npm ERR! code 1
npm ERR! path /Users/myuser/brave-browser
npm ERR! command failed
npm ERR! command sh -c node ./scripts/init.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2021-02-22T20_32_47_994Z-debug.log

**Comment by Aragar199** [comment]
@bridiver - 
macOS Catalina Version 10.15.7
node v15.8.0
npm 7.5.0

**Comment by bsclifton** [comment]
@Aragar199 you're going to want to install the LTS version of Node.js, which should be 14.x

**Comment by Aragar199** [comment]
Yep, that's it! I installed node 12 and it works fine. Still throws an error if the directory `src/brave/` already exists due to a failed installation but it's much more verbose so I'm inclined to just nuke my PR and call it. My bad, @bsclifton, you mentioned this near the beginning of this thread!

**Comment by bridiver** [comment]
@bsclifton the problem is likely the npm version because I blieve that is what converts the config to env vars, but presumably downgrading to node 14 will also take care of npm. There must be a change in how they are converted to env vars

**Comment by Aragar199** [comment]
node v12.20.2
npm 6.14.11

**Comment by bridiver** [comment]
yep, npm 6.x should work correctly because that is what I have locally

**Comment by Kwadz** [comment]
Tested with node v14.15.5 here (latest LTS), and it works. @bsclifton was right from the beginning and I also missed it  🤦‍♂️ 

Thank you guys!

**Comment by wknapik** [comment]
Apparently only npm 6 will work (at least for me on Linux). That's not on the wiki and there's no error message that would give the user a hint.

**Comment by emerick** [comment]
Ran into this one myself on Windows today. While debugging something else, I had run `npm install -g npm@latest` and ended up with npm `7.6.3`. Reverting to npm `6.14.11` fixed it for me.

**Comment by bridiver** [comment]
The documentation specifies node LTS which has npm 6

**Comment by bridiver** [comment]
so actually I'm going to re-open the ticket, but I want to clarify that the issue (for now) is just updating documentation to specify npm 6.x just so there is no confusion about node lts vs npm version

**Comment by wknapik** [comment]
The node package does not necessarily come with npm.
```
% pacman -Ql nodejs-lts-fermium|grep npm
%
```

**Comment by jtrag** [comment]
> I also encountered the same issue. Problem is that the path to the repository url is broken.
> 
> There is a string replacement that is making `-` into `_` at https://github.com/brave/brave-browser/blob/master/lib/util.js#L5
> 
> So when brave-browser goes looking for `brave-core` in package.json, it can never find it because the key is changed to `brave_core` and it ends up `undefined`
> 
> You can change it to `brave_core` in https://github.com/brave/brave-browser/blob/master/package.json#L38
> 
> That fixes it there, but then it breaks in brave-core which has its own `getNPMConfig` that does **not** do the same string replacement to change `-`. So it scans for `brave-core` but never finds it because it is `brave_core` now.
> 
> You can then change at https://github.com/brave/brave-core/blob/master/build/commands/lib/config.js#L77
> `brave-core` to `brave_core` so when it scans for the repo url it can find it because it is now `brave_core` in brave-browser/package.json.
> 
> Then change the repo url and branch name to point to the brave-core version that has this change:
> 
> ![Screen Shot 2021-01-19 at 8 45 30 AM](https://user-images.githubusercontent.com/14187644/105067037-2f1a8b00-5a34-11eb-87d1-fc538946a668.png)
> 
> I was able to install using these steps, but it's a patch job and should probably have a real fix instead.

I changed brave-core to brave_core in the package.json that is in the main "brave-browser" directory and that alone fixed the issue.  FYI I'm on MacOS.

**Comment by bridiver** [comment]
@jtrag if you are experiencing this problem you are using the wrong version of npm - https://github.com/brave/brave-browser/issues/13631#issuecomment-797611763

**Comment by jtrag** [comment]
> @jtrag if you are experiencing this problem you are using the wrong version of npm - [#13631 (comment)](https://github.com/brave/brave-browser/issues/13631#issuecomment-797611763)

Thanks for the tip!  When I get a chance I'll try that and see if it helps.

**Comment by dhouck** [comment]
Trying to read this, it looks like everything works if, and only if, I use an outdated version of NPM?  Or were there other changes I also needed to make?

**Comment by bridiver** [comment]
I don’t know that I’d call LTS “outdated”, but otherwise yes :)

**Comment by CatsMeow492** [comment]
This issue alone is enough to make most on being a contributor.

   git clone <yourForkURL>
   cd brave-browser
   npm install

And that's the last part of this that makes any sense.  Now we get to downgrade your dev environment so from now on you can only contribute to brave.

    brew install node@12
    npm install npm@6.14.11 -g

now edit your package.json file

    >>package.json 

    "brave_core": {
        "dir": "src/brave",
        "branch": "master",
        "repository": {
          "url": "<your fork url>"
        }

Next

    npm run init

finally

    cd ...
    rm brave-browser
    npm update

never look at this repo again.

**Comment by bridiver** [comment]
I use nvm which allows me to easily switch node versions. We are actively looking at ways to remove this local dependency.

**Comment by himansh-gjr** [comment]
Hey I have followed the same instruction that @CatsMeow492 gave, but I am getting this error.

<img width="820" alt="Screenshot 2021-10-18 at 9 11 13 PM" src="https://user-images.githubusercontent.com/77732259/137764311-49216adb-7922-4227-a69e-74e1bffd2425.png">

I am using macbook air M1 ( macOS version 11.5.2)

**Comment by petemill** [comment]
https://github.com/anatoliygatt/deep-freeze-node/issues/10

**Comment by bridiver** [comment]
also @himansh-gjr just fyi we don't yet have official support for building on arm yet (arm builds are currently done on x64 just like for other platforms), but it sounds like @petemill may have it working soon.

**Comment by bridiver** [comment]
Looks like an upstream error from gclient runhooks and might be intermittent. Did you try more than once?

**Comment by himansh-gjr** [comment]
I re-run `npm run init` after removing `deep-freeze-node`

**Comment by bridiver** [comment]
@himansh-gjr see https://github.com/brave/brave-core/pull/10795

**Comment by mihaiplesa** [comment]
@himansh-gjr how is it looking now?

**Comment by MaazBinMusa** [comment]
@Aragar199 @bsclifton I still got the issue

Windows 10 Education
Node v16.13.0 (LTS)
Npm 8.1.3

I removed the replace - with _ line in utils and have starting the init.

**Comment by bsclifton** [comment]
For folks running into this issue with newer NPM - I created an issue and am tracking here (subscribe for updates):
https://github.com/brave/brave-browser/issues/19398

**Comment by mohanamisra** [comment]
> [@Kwadz](https://github.com/Kwadz) `npm run init` only tries to create src/brave if the `src/brave/.git` doesn't exist. If these are the only steps you have done
> 
> ```
> git clone git@github.com:brave/brave-browser.git
> cd brave-browser
> npm install
> ```
> 
> then `src/brave` would not exist

In that case, what is the correct way to go about trying to set up the project locally?
