### ISSUE TITLE
Update Crypto Wallets icon

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13642]
[crypto-wallet-icon.zip](https://github.com/brave/brave-browser/files/5832471/crypto-wallet-icon.zip)

From the Ethereum one to the new one.

<img width="241" alt="Screen Shot 2021-01-18 at 4 30 52 PM" src="https://user-images.githubusercontent.com/831718/104964524-8a07a000-59aa-11eb-9014-c6c3d0285867.png">

cc @jamesmudgett @ryanml

**Comment by ryanml** [comment]
Cool, I can make this update

**Comment by ryanml** [comment]
This will be the issue for implementation, root issue that this addresses is: https://github.com/brave/brave-browser/issues/11342

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.85 Chromium: 88.0.4324.96 (Official Build) beta (64-bit)
-- | --
Revision | `68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}`
OS | Linux
Component | `1.0.22 Dev`

- Verified Crypto Wallet icon is updated on the page and on the browser action button
![image](https://user-images.githubusercontent.com/17010094/105845968-6dcfb880-5fd3-11eb-96f0-56ce820eda9f.png)

-------
Verification passed on 

Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | `68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}`
OS | Windows 10 OS Version 2009 (Build 19042.746)
Component | `1.0.22 Dev`

- Verified Crypto Wallet icon is updated on the page and on the browser action button
![image](https://user-images.githubusercontent.com/17010094/105859371-577e2880-5fe4-11eb-9ee3-330cb8b9d0c8.png)

-------
Verification passed on 

Brave | 1.21.18 Chromium: 88.0.4324.96 (Official Build) nightly (x86_64)
-- | --
Revision | `68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.22 Dev`

- Verified Crypto Wallet icon is updated on the page and on the browser action button
![image](https://user-images.githubusercontent.com/17010094/105859723-c491be00-5fe4-11eb-8d35-3b1b17fda30f.png)
------

Logged followup issue #13770
