### ISSUE TITLE
`Earn Tokens` on Welcome page is not translated in Polish locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#13649]
Follow up to https://github.com/brave/brave-browser/issues/13437

## Steps to Reproduce

1. Clean profile
1. Run Brave in Polish (PL) locale
1. On Welcome UI (brave://welcome), open Rewards onboarding 

Note: it is translated in German locale

## Actual result:

`Earn Tokens` on Welcome page is not translated
Polish
![image](https://user-images.githubusercontent.com/34715963/104957363-4faffa00-59ce-11eb-9815-9c4ef711c5b2.png)

## Expected result:
`Earn Tokens` on Welcome page is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.19.85 Chromium: 88.0.4324.89 (Official Build) (64-bit)
-- | --
Revision | 4534be84786f5269fb52e9bf82643af61e2fedaf-refs/branch-heads/4324@{#1721}
OS | Ubuntu 18.04 LTS

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @mkarolin @brave/legacy_qa @rebron

**Comment by mkarolin** [comment]
@btlechowski, it appears to have been missed because of the formatting of the string:
<pre>
&lt;ph name=\"BEGIN_BOLD\"&gt;$1&lt;/ph&gt;Earn tokens&lt;ph name=\"END_BOLD\"&gt;$2&lt;/ph&gt; poprzez oglądanie Brave Private Ads oraz automatyczne wspieranie twórców treści.
</pre>

We have a similar string without formatting where `Earn tokens` was translated as `Zarabiaj tokeny`. If I use that, does the sentence below make sense?

`Zarabiaj tokeny poprzez oglądanie Brave Private Ads oraz automatyczne wspieranie twórców treści.`

**Comment by btlechowski** [comment]
@mkarolin `Zarabiaj tokeny` is the right translations and fits the sentence.

Also the text in Polish suggests that you can earn tokens by automatically supporting the content creators. I think we need to make the text in English more obvious so that the translators won't get confused. I will log another issue.

**Comment by mkarolin** [comment]
@btlechowski, the other string is translated as: `Zarabiaj tokeny, oglądając reklamy z poszanowaniem prywatności i automatycznie wspieraj ulubione strony oraz twórców treści.` Is this a more precise translation?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.87 Chromium: 88.0.4324.96 (Oficjalna wersja) (64-bitowa)
-- | --
Wersja | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
System operacyjny | Windows 10 OS Version 2004 (Build 19041.746)

```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/105985958-3ab82280-60c2-11eb-94e4-b29fb4012fb7.png)
