### ISSUE TITLE
Use full page explainer for unconfigured ipfs:// loads instead of loading content with an infobar

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13655]
## Description
For new IPFS users that load ipfs:// or ipns:// URLs, show a webui page that gives an explainer instead of loading content through a gateway with an infobar.

The infobar is pretty packed, and we'd rather not use the gateway by default without user consent. 

We currently load the content + have this infobar:
<img width="625" alt="Screen Shot 2021-01-19 at 9 53 36 AM" src="https://user-images.githubusercontent.com/831718/105052226-a30d6100-5a3d-11eb-915a-9a4edd028eb5.png">

Instead we should show a full page webui explainer page. If the user goes in settings and selects `Ask` we'd just show this page again.

## Designs
![image](https://user-images.githubusercontent.com/2388823/105257501-c539d880-5b3c-11eb-9ae8-cee336c5e445.png)

- Learn more link goes to [https://support.brave.com/hc/en-us/sections/360010974932-InterPlanetary-File-System-IPFS-](url)
- Settings links goes to [brave://settings](url), scrolled to the IPFS section

When the user clicks "Use local node", show a loading spinner to indicate the node is being installed before redirecting to the requested content:
![image](https://user-images.githubusercontent.com/2388823/107271387-00734d00-6a01-11eb-8d5d-038012870f4d.png)

![image](https://user-images.githubusercontent.com/2388823/107271419-0cf7a580-6a01-11eb-9ff6-7110fb98da85.png)

## Assets
Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/?node-id=94%3A7772

**Comment by PrivacyMatters** [comment]
That's very helpful

**Comment by jessicaschilling** [comment]
Commenting to follow this issue - and would be happy to help with language etc when you start working on this one, particularly so we can be sure to remain consistent with other IPFS tools like Companion. Thanks! 🙏

**Comment by lidel** [comment]
Yes! Quick thought:

We should account for [tyranny of small decisions](https://en.wikipedia.org/wiki/Tyranny_of_small_decisions) and if we want true decentralization, we should promote running local nodes.
Perhaps we reorder options so that the local node is the first one + the option has slight tint/color accent to indicate "pick this for best outcome"?

**Comment by karenkliu** [comment]
Designs added!

**Comment by bbondy** [comment]
Awesome work, thank you @karenkliu!

**Comment by jessicaschilling** [comment]
This is awesome! Would love to request a few text changes just for consistency with IPFS-land in general?
- In the explanatory graf, `InterPlanetary File System (IPFS) is the public network` -> `IPFS (InterPlanetary File System) is the public network`
- First option text: `and content you're requesting` -> `and any content you're requesting`
- First option text: `Content is verified` -> `Content you request over IPFS is verified` and `before being served.` -> `before being served to you.`
- Second option text: `from everyone else` -> `from potential third-party observers`
- Second option text: `The operator is responsible for serving you the correct requested content.` -> `The gateway operator is responsible for ensuring that the content served to you over a gateway is the content you requested.`
- Second option text: `to the public network` -> `to the public IPFS network`

**Comment by jessicaschilling** [comment]
Also - @autonome, would appreciate your eyes on this as well. Thanks!

**Comment by ryanml** [comment]
Front end work will pushed to this branch: https://github.com/brave/brave-core/tree/feature-13655 cc: @spylogsster

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` on macOS Big Sur (11.2.1) with:


Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

![ipfs-install-new](https://user-images.githubusercontent.com/387249/108779786-47dafc80-751c-11eb-8288-385adb628758.gif)
<img width="1202" alt="Screen Shot 2021-02-22 at 2 37 14 PM" src="https://user-images.githubusercontent.com/387249/108779787-48739300-751c-11eb-891c-1c9a81e8b704.png">

Verified that the links go to the correct URLs, that `brave://settings/ipfs` options are present and work, and that the text from https://github.com/brave/brave-browser/issues/13655#issuecomment-763946365 was updated and reflected in the UI.

The spinner on the "Installing..." orange button isn't present; will file a new bug for that and cross-reference it here.
