### ISSUE TITLE
Support cosmetic filters in AdBlocker on android

### ISSUE THREAD

**Issue by DiAnTTA** [brave/brave-browser#13651]
### Description 
Ad Blocker on android ignore cosmetic filters.

### Actual result 
<details><summary>Screenshot</summary>

![IMG_20210119_155423](https://user-images.githubusercontent.com/74956696/105011625-c0f3b980-5a6f-11eb-95ab-7ee3c7bdde91.jpg)
</details>

### Expected result
‌Enforce cosmetic filters in AdBlocker on android.

**Comment by ryanbr** [comment]
Closing ticket @DiAnTTA  we're aware of this https://github.com/brave/brave-browser/issues/9955 , and it'll be coming this year.
