### ISSUE TITLE
"Show Brave News" toggle on Customize Dashboard is not translated

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13653]
## Description 

"Show Brave Today" toggle on Customize Dashboard modal is not translated.

## Steps to Reproduce

   1. Open NTP for language other than English (ex. Romanian, French)
   2. Open Customize Dashboard modal
   3. Click on Brave Today

## Actual result:

Romanian | French
----- | -----
<img width="750" alt="Romanian" src="https://user-images.githubusercontent.com/28145373/105046873-9e45ae80-5a37-11eb-95b3-b1da3b5099c2.png"> | <img width="748" alt="French" src="https://user-images.githubusercontent.com/28145373/105046877-9f76db80-5a37-11eb-9e90-921de8f9a309.png">

## Expected result:
Toggle text to be translated

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.18.78 Chromium: 87.0.4280.141 (Versiune oficială) (x86_64)
-- | --
Versiune | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
Sistem de operare | macOS Versiune 10.15.7 (Build 19H15)

Brave | 1.19.86 Chromium: 88.0.4324.96 (Versiune oficială) (x86_64)
-- | --
Versiune | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
Sistem de operare | macOS Versiune 10.15.7 (Build 19H15)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 1.18.x and 1.19.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@brave/legacy_qa this should be ready to retest - translations were ordered with Chromium 88

**Comment by mattmcalister** [comment]
Product brand names are not generally translated. Closing this issue.

**Comment by rebron** [comment]
Closing as stale with new design. Can you re-open @LaurenWags if still an issue with the new design. cc: @stephendonner
