### ISSUE TITLE
Receive misspelled in "Welcome to Brave Rewards!" tour on Android

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#13668]
## Description 

In the flyout panel for Brave Rewards on Android, "receive" is misspelled as "recieve," in "After you recieve your first ads payout..."

## Steps to reproduce 

   1.  Launch Brave Nightly on Android
   2.  Click on the Brave Rewards icon
   3.  In the flyout panel, look for the spelling of "receive."

## Actual result 

"After you recieve your first ads payout you can come back and tip this creator!"

![IMG_4401](https://user-images.githubusercontent.com/387249/105115696-22bb2000-5a7e-11eb-89db-af084b99503e.jpg)

## Expected result

"After you receive your first ads payout you can come back and tip this creator!"

## Issue reproduces how often 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
No.
- Can you reproduce this issue with the current Play Store Beta version? 
No.
- Can you reproduce this issue with the current Play Store Nightly version?
Yes.

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version

Nightly 1.21.12, Chromium 88.0.4234.96

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.21.69 x64 build

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/109310231-2c356600-783c-11eb-8e6a-443d5ca98728.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/109310291-3c4d4580-783c-11eb-90ba-1f292f0dd245.png>
