### ISSUE TITLE
Custom startup args missing

### ISSUE THREAD

**Issue by Dreaming-Codes** [brave/brave-browser#13667]
## Description 
I realy like some brave features but i hate the integrated adblock and so i want to set this custom startup arg --disable-brave-extension to disable it.
I understand that you don't want to give a direct option to completely disable the adblock but at least give an option for advanced users.

**Comment by antonok-edm** [comment]
@Dreaming-Codes you can disable the built-in adblocker completely using the controls in brave://settings/shields. Are these insufficient for your use-case?
