### ISSUE TITLE
Crash in `AccountReconcilor::StartReconcile` on close of Brave

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#13662]
## Description 
Crash seen in Backtrace - it's been around for a while, we just didn't file an issue. I experienced this today

Example crash reports:
- https://brave.sp.backtrace.io/p/brave/debug?filters=(_deleted%3D0%2Cver%3D%2288.1.19.86%22)&fingerprint=80d1b0ed543679bc018320c8882da2d369ef1e26471592c98d9230ecfd423c0a&debug=(c1d2b8,0,0)
- https://brave.sp.backtrace.io/p/brave/debug?filters=(_deleted%3D0%2C_rxid%3Dd7a90000-604d-b505-0000-000000000000)&fingerprint=dd00d070a6b39442bfbe72ff71468d234e9e87e5c9a391e16242466b004415c2&debug=(c1d48d,0,0)

```
[ 00 ] AccountReconcilor::StartReconcile()
[ 01 ] AccountReconcilor::UnblockReconcile()
[ 02 ] AccountReconcilor::Lock::~Lock()
[ 03 ] DiceResponseHandler::~DiceResponseHandler()
[ 04 ] DiceResponseHandler::~DiceResponseHandler()
[ 05 ] KeyedServiceFactory::Disassociate(void*)
[ 06 ] KeyedServiceFactory::ContextDestroyed(void*)
[ 07 ] DependencyManager::PerformInterlockedTwoPhaseShutdown(DependencyManager*, void*, DependencyManager*, void*)
[ 08 ] ProfileImpl::~ProfileImpl()
[ 09 ] <name omitted>
[ 10 ] ProfileDestroyer::DestroyRegularProfileNow(Profile*)
[ 11 ] ProfileDestroyer::DestroyProfileWhenAppropriate(Profile*)
[ 12 ] std::__1::unique_ptr<ProfileManager::ProfileInfo, std::__1::default_delete<ProfileManager::ProfileInfo> >::~unique_ptr()
[ 13 ] std::__1::__tree<std::__1::__value_type<base::FilePath, std::__1::unique_ptr<ProfileManager::ProfileInfo, std::__1::default_delete<ProfileManager::ProfileInfo> > >, std::__1::__map_value_compare<base::FilePath, std::__1::__value_type<base::FilePath, std::__1::unique_ptr<ProfileManager::ProfileInfo, std::__1::default_delete<ProfileManager::ProfileInfo> > >, std::__1::less<base::FilePath>, true>, std::__1::allocator<std::__1::__value_type<base::FilePath, std::__1::unique_ptr<ProfileManager::ProfileInfo, std::__1::default_delete<ProfileManager::ProfileInfo> > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<base::FilePath, std::__1::unique_ptr<ProfileManager::ProfileInfo, std::__1::default_delete<ProfileManager::ProfileInfo> > >, void*>*)
[ 14 ] ProfileManager::~ProfileManager()
[ 15 ] BraveProfileManager::~BraveProfileManager()
[ 16 ] <name omitted>
[ 17 ] BrowserProcessImpl::StartTearDown()
[ 18 ] ChromeBrowserMainParts::PostMainMessageLoopRun()
[ 19 ] content::BrowserMainLoop::ShutdownThreadsAndCleanUp()
[ 20 ] content::BrowserMainRunnerImpl::Shutdown()
[ 21 ] content::BrowserMain(content::MainFunctionParams const&)
[ 22 ] content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams&, bool)
[ 23 ] content::ContentMainRunnerImpl::Run(bool)
[ 24 ] content::RunContentProcess(content::ContentMainParams const&, content::ContentMainRunner*)
[ 25 ] content::ContentMain(content::ContentMainParams const&)
[ 26 ] ChromeMain
[ 27 ] main
[ 28 ] 0x7fff20329631
[ 29 ] 0x7fff20329631
```

## Steps to Reproduce
These are steps I did when I saw it today. Maybe we can reduce these to see if there is a more direct way to reproduce
   1. Installed Brave (new profile); use like regular
   2. Updated Brave to latest version
   3. Visit brave://settings/extensions and enabled `Allow Google login for extensions`
   4. Installed an extension with Google login (ex: Google Calendar) and logged in
   5. It went to google.com, showed me as logged in
   6. Exited browser. Didn't notice anything weird happen on close

## Actual result:
When relaunching, it may show that tabs were lost (with a restore button). If this happens, the crash was experienced when closing Brave (step 5 above).

Subsequent opening and closing of the app works fine. Maybe this is a timing issue?

## Expected result:
No crash should happen

## Reproduces how often: 
Intermittent issue / hard to repro

**Comment by bsclifton** [comment]
cc: @iefremov

**Comment by iefremov** [comment]
Apparently, this is an upstream crash, see https://bugs.chromium.org/p/chromium/issues/detail?id=967603#c24
