### ISSUE TITLE
Brave Dev crashing all the time.

### ISSUE THREAD

**Issue by levinobre** [brave/brave-browser#1367]
## Description 
After install Brave Beta, Brave Dev became impossible to use because it's crashing all the time after load a website. Unfortunately, I can't use Brave Beta because we don't have the import option between Brave Dev and Brave Beta (#1357) yet.

UPDATE: I've noted that it's start occurring after the latest Windows 10 update.

## Steps to Reproduce

   1. Open Brave Dev;
   2. Access any URL;
   3. Brave Dev closes immediately.

## Actual result:
Brave Dev crash after access any URL. Still impossible to use.

## Expected result:
Brave Dev to work normally, loading all websites.

## Reproduces how often: 
All the time.

## Brave version (chrome://version info)
Brave: 0.56.1 Chromium: 70.0.3538.22 (Official Build) dev (64-bit)
Revision: ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS: Windows
JavaScript: V8 7.0.276.15
Flash: 31.0.0.108

### Reproducible on current release:
Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by bbondy** [comment]
I think this is fixed in 0.56.2, could you confirm?  If not I'll re-open.
