### ISSUE TITLE
(Linux Mint 20.1 Xfce Edition) Tabs remain after re-opening Brave, even when History was configured to delete everything on exit

### ISSUE THREAD

**Issue by palaciodaniel** [brave/brave-browser#13671]
## Description 

I was using Brave on my previous Linux Mint (Cinnamon) installation, and it deleted all tabs when exiting the browser, as it was configured to do so on the Clear Browsing Data section. However, this is not happening under Linux Mint Xfce edition; the tabs that I didn't manually close remained there when I re-opened the browser. Brave is "remembering" them.

## Steps to Reproduce

   1. (As a pre-requisite, on the Clear Browsing Data section everything should be ticked on the "On exit" tab).
   2. Don't close any tab and press the X button on the upper right to close the browser.
   3. Re-open Brave.

## Actual result:

The bug is totally clear on the following [YouTube video](https://youtu.be/im0zg2WRO0Y).

## Expected result:

No tabs should appear at all when I re-open Brave.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Linux

## Miscellaneous Information:

As expressed before, this didn't happen with Linux Mint Cinnamon Edition.

**Comment by diracdeltas** [comment]
does this happen with chrome too? cc @fmarier

**Comment by fmarier** [comment]
I'm surprised there's a difference between Mint and XFCE here, but there are known problems with this "clear-on-exit" feature, see https://github.com/brave/brave-browser/issues/3673 and https://github.com/brave/brave-browser/issues/3549.

**Comment by fmarier** [comment]
What setting do you have here?
![Screenshot from 2021-01-25 14-42-08](https://user-images.githubusercontent.com/167821/105775600-e8d59800-5f1b-11eb-8c76-28c7f2ed1f5b.png)

If you have the browser set to "continue where you left off", then that's not compatible with clearing data on exit since this option is specifically designed to reopen the tabs you had when you exited.

**Comment by fmarier** [comment]
In my testing (Ubuntu 20.04, i3 window manager), the tabs come back when I have clear-on-exit + "Continue where you left off", but they don't come back (and everything is cleared correctly) if I use "Open the New Tab page" instead.

**Comment by palaciodaniel** [comment]
I changed the option to "Open the New Tab page" and now it works as expected. It's weird though, because I didn't have to select that when I was using the previous distro. 

Still, I think everything should be deleted when you select all the options on the "On Exit" tab. It should be prioritized instead of the "On start-up" section, otherwise it will lead to confusion.

Thanks for your reply.
