### ISSUE TITLE
`Sorry! Ads are not yet available in your region` message is shown after resetting rewards multiple times.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13676]
## Description 

`Sorry! Ads are not yet available in your region` message is shown after resetting rewards multiple times.
## Steps to Reproduce

   1. Clean profile 1.20.x
   2. Enable rewards via NTP
   3. Navigate to the rewards settings page
   4. Reset rewards via gear icon
   5. Reload brave://rewards page
   6. Reset rewards again
   7. `Sorry! Ads are not yet available in your region` message is shown
   8. Repeat the step 5 and 6

**Note:** REload brave://rewards fixes the issue, the message gets disappeared 
## Actual result:

`Sorry! Ads are not yet available in your region` message is shown 
![image](https://user-images.githubusercontent.com/38657976/105166370-66c12a00-5b3d-11eb-961f-693078f31199.png)

## Expected result:
`Sorry! Ads are not yet available in your region` message should not be shown when ads are supported

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @rebron

**Comment by tmancey** [comment]
@GeetaSarvadnya moved to Rewards as when resetting Rewards I would expect the user to have to go through the "Start using Brave Rewards" onboarding process again.

**Comment by Miyayes** [comment]
I think this should be superseded by https://github.com/brave/brave-browser/issues/25275 right?
