### ISSUE TITLE
Bad merge re-disabled kVideoPlaybackQuality on 1.19.x branch.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#13679]
kVideoPlaybackQuality was removed from disabled features list to fix https://github.com/brave/brave-browser/issues/13183.

The fix was uplifted to 1.19.x branch by https://github.com/brave/brave-core/pull/7451. However, a later uplift of Chromium 88 changes in https://github.com/brave/brave-core/pull/7518 incorrectly reverted the change.

QA:
Please, retest with the same plan as in the original issue (#13183).

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/7667 was merged into `1.19.x` as per https://github.com/brave/brave-browser/issues/13679#ref-pullrequest-790048899.
