### ISSUE TITLE
Refactor settings for IPFS into its own section

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13682]
Add a local node option:
<img width="1212" alt="Screen Shot 2021-01-20 at 11 13 51 AM" src="https://user-images.githubusercontent.com/831718/105203025-9d348000-5b10-11eb-9700-cd4c78ce4791.png">

**Comment by jessicaschilling** [comment]
LGTM! But what happened to this section?
![image](https://user-images.githubusercontent.com/1507828/105232529-beec3200-5b25-11eb-9f2d-6129469301b6.png)

**Comment by bbondy** [comment]
Yep! All the settings will still be there, the above image is just for reference for how it will look overall.

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` on macOS Big Sur (11.2.1) with 

Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

<img width="1307" alt="Screen Shot 2021-02-22 at 2 50 16 PM" src="https://user-images.githubusercontent.com/387249/108781225-6a6e1500-751e-11eb-99da-42e8bdea07f0.png">

Tested and verified that the settings generally work (i.e. I didn't go too deeply), while testing other IPFS issues.
