### ISSUE TITLE
Support IPFS gateway method first on Android

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13683]
Let's add support for IPFS via gateway to Android.

We would show this page on the first IPFS load:
https://github.com/brave/brave-browser/issues/13655

But without the local node option to start.

**Comment by lidel** [comment]
:+1:  (cc @autonome)
Ubiquitous support for resolution of `ipfs://` and `ipns://` URIs (even if its only via a customizable gateway) is very important for us

**Comment by bbondy** [comment]
Re-opening because of a warning causing an error on Android. I'll fix then re-land.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.24.76, Chromium 90.0.4430.85` on Android 9, Google Pixel XL, arm64.

Steps:

1.  new profile/install
2. loaded `ipns://brantly.eth`
3. confirmed I got the interstitial page
4. tapped on `Use public gateway`
5. confirmed the page loaded after a brief DNS lookup (and error page, expected for now - we've fixed that on desktop, I believe)
6. new profile/install (again)
6. load `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
7. tapped on `Use public gateway`
8. confirmed the page loaded after a brief DNS lookup (and error page, expected for now - we've fixed that on desktop, I believe)

example | example | example | example
---------|---------|----------|---------
![Screenshot_20210429-110859](https://user-images.githubusercontent.com/387249/116607498-e69e2380-a8e6-11eb-83a2-8d2d726229ef.png) | ![Screenshot_20210429-110908](https://user-images.githubusercontent.com/387249/116607500-e7cf5080-a8e6-11eb-8f93-983938a520e7.png) | ![Screenshot_20210429-112800](https://user-images.githubusercontent.com/387249/116607501-e867e700-a8e6-11eb-9c7c-a100f55dfd53.png) | ![Screenshot_20210429-112810](https://user-images.githubusercontent.com/387249/116607502-e9007d80-a8e6-11eb-8406-adea1be17f4e.png)
