### ISSUE TITLE
"backup" should be "back up" in "Backup tab of Manage Your Wallet flyout

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#13686]
## Steps to Reproduce

   1.  Click on the Brave Rewards icon
   2.  Click on the Rewards Settings text
   3.  Click on the settings wheel/icon

## Actual result:

"The funds in your Brave wallet are virtual and not required to backup."

<img width="1074" alt="Screen Shot 2021-01-20 at 9 47 23 AM" src="https://user-images.githubusercontent.com/387249/105225392-58f6af00-5b13-11eb-9d79-7570a0cbe33d.png">

## Expected result:

"The funds in your Brave wallet are virtual and not required to back up."

## Reproduces how often: 
Text string, so 100%

## Brave version (brave://version info)

1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:
https://grammarist.com/usage/back-up-backup/

**Comment by stephendonner** [comment]
Compare with the Restore tab, which has "back up" correctly.
<img width="1074" alt="Screen Shot 2021-01-20 at 9 47 29 AM" src="https://user-images.githubusercontent.com/387249/105225842-08338600-5b14-11eb-8033-95a4f5450c76.png">

**Comment by sebuelias** [comment]
Can I try to pick this issue up?
I am new and trying to learn, if it is ok

**Comment by stephendonner** [comment]
> Can I try to pick this issue up?
> I am new and trying to learn, if it is ok

Hello @sebuelias; sure, welcome to the project - I'll assign it to you.

**Comment by sebuelias** [comment]
hi ,
@stephendonner I am actually new and learning, can you give me some pointers or guidance as to how to solve this?
I am learning and if this seems unprofessional of me, please do let me know.

**Comment by stephendonner** [comment]
@sebuelias a great place to start would be to search the codebase for that portion of the string we want to change, so begin with https://github.com/brave/brave-core/search?p=1&q=or+backup+your+current+wallet and see which file(s) you'd need to change, relevant to this bug.

**Comment by deepxcode** [comment]
If this issue hasn't be resolved yet, @stephendonner  Can I take this issue? I am new to open source but would love to contribute to Brave Browser.

**Comment by sebuelias** [comment]
Hi @stephendonner 
Apologies for the delay, but I have tried to fix this issue and raised the PR.

**Comment by swarup4741** [comment]
hi @stephendonner … is this issue resolved ? if not then can u assign it to me ?

**Comment by stephendonner** [comment]
> hi @stephendonner … is this issue resolved ? if not then can u assign it to me ?

Hi; no, it's still open, and @sebuelias has a patch which needs review.  Thanks for looking!  Feel free to grab some unassigned `good-first-issue` issues.

**Comment by rolewest** [comment]
Hello! I'm also new to open source contributing and I have completed this issue, I believe.

I realized the issue needs to be changed in the brave core, correct?
I have not pushed the changes as I'm not sure if I need approval first?

Thank you.
