### ISSUE TITLE
[Desktop] Rewards tour does not have enough margin in rewards panel

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#13685]
## Description 

The rewards tour, when displayed in the rewards panel when there are no panel notifications, does not have quite enough margin on the top and bottom.

<img width="393" alt="Screen Shot 2021-01-20 at 12 48 38 PM" src="https://user-images.githubusercontent.com/5995084/105214421-f7880d80-5b1d-11eb-8fcd-e0e20f9ce874.png">

**Comment by stephendonner** [comment]
Verified FIXED using 

Brave | 1.21.44 Chromium: 88.0.4324.146 (Official Build) beta (x86_64)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | macOS Version 11.2 (Build 20D64)

Followed the testplan from https://github.com/brave/brave-core/pull/7677, and additionally resized the browser's viewport to constrain the panel flyout, which still enforced its margin padding nicely (2nd screenshot).
<summary>
screenshots:
</summary>
<details>

![image](https://user-images.githubusercontent.com/387249/107294964-49d49400-6a23-11eb-9928-f61074a79505.png)
![image](https://user-images.githubusercontent.com/387249/107294965-4a6d2a80-6a23-11eb-9dae-e11fa880a946.png)

</details>
