### ISSUE TITLE
Consolidate Crypto Wallets IPFS setting with Brave's setting

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13689]
The [Crypto Wallets extension](https://github.com/brave/ethereum-remote-client) currently makes use of its own IPFS setting to specify which gateway to use.

<img width="516" alt="Screen Shot 2021-01-20 at 3 34 57 PM" src="https://user-images.githubusercontent.com/831718/105231545-0fb75700-5b35-11eb-9e7f-e4c4542de0e0.png">

Since we [just released native IPFS support in Brave](https://www.google.com/search?q=brave+ipfs&oq=brave+ipfs), we should not need a setting for this anymore. We can just use `ipfs://<cid>` and Brave will handle it correctly.

You can test with an ENS load which would normally redirect to the configured Crypto Wallets IPFS gateway here: `http://matoken.eth` or another example `http://brantly.eth/`. This is changing soon, but please note that Crypto Wallets is lazilly loaded right now, and we only resolve ENS right now if the extension is loaded. So you can load the extension by going to brave://wallet (and if it's the first time create a wallet).  After doing that you can load `http://matoken.eth` or `http://brantly.eth/` and it will redirect you to the configured Crypto Wallets gateway.

We can remove the UI referenced in the image above and instead of using a gateway that's configured in Crypto Wallets, just use an `ipfs://` URI if the user is using a modern Brave which has IPFS support.   Since some users may be using an old version of Brave, we don't know if the version they're using has IPFS support yet.  

For checking if Brave has support for IPFS, we should check if it's available via:

```
// Checks if a feature flag is enabled
chrome.ipfs.getIPFSEnabled((enabled: boolean) => {})
```

Note that the API will not be available right now with a side-loaded Crypto Wallets extension because we don't expose this API yet to the Crypto Wallets extension. So when you're testing locally with a side loaded extension, you'll see `chrome.ipfs` isn't available.  When things are loaded as components, which we do on the normal flow, `chrome.ipfs` will be available. You can see this by enabling dev mode in brave://extensions and then right clicking on the Crypto Wallets browser action popup and inspecting the view, then typing `chrome.ipfs` in the console.

To make `chrome.ipfs` available to Brave, you'll need a custom build of Brave.

Developer instructions for building Brave can be found here: https://github.com/brave/brave-browser/blob/master/README.md

The change to Brave is very small to make this API available to the Crypto Wallets extension for when it is side loaded.

You'll need to add a whitelist entry with this value: `21070F3D60711361C1210B870439BE49B5D995F4` to `src/brave/common/extensions/api/_ipfs_api_features.json`
You'll need to compile Brave manually (this takes several hours) and run it, then go to chrome://extension, turn on Developer mode, and load from the Crypto Wallets build you made.

To do this issue, you'll need to make changes to brave-core (which is on Github at brave/brave-core) which is located in `src/brave` of the `src/brave-browser` clone and create a pull request for that to `brave/brave-core`. 

You'll also need to make a pull request to ethereum-remote-client (which is on Github at brave/ethereum-remote-client).

Please make sure ethereum-remote-client tests still pass after the changes, and adding an extra test is appreciated.

If someone is using an old version of Brave and `chrome.ipfs` is not available,  but is using this newer extension, we should use the existing setting of Crypto Wallets or `dweb.link` if no existing setting is available.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)
-- | --
Revision | `62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}`
OS | Linux
Component | `1.0.26 Dev`

- Verified IPFS option has been removed from Advanced settings
- Verified ENS support works as expected. Typing in brantly.eth in Send auto resolves the address

Before update | After update
-- | --
![image](https://user-images.githubusercontent.com/17010094/112142802-f1221a80-8bce-11eb-95f0-0a733dfe0b3a.png) | ![image](https://user-images.githubusercontent.com/17010094/112142454-896bcf80-8bce-11eb-8a55-5eb85ae1e2ed.png)

-------
Verification passed on

Brave | 1.22.62 Chromium: 89.0.4389.90 (Official Build) beta (64-bit)
-- | --
Revision | `62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}`
OS | Windows 10 OS Version 2009 (Build 19042.867)
Component | `1.0.26 Dev`

- Verified IPFS option has been removed from Advanced settings
- Verified ENS support works as expected. Typing in brantly.eth in Send auto resolves the address

Before update | After update
-- | --
![image](https://user-images.githubusercontent.com/17010094/112142268-40b41680-8bce-11eb-83ba-fdeba992e2d1.png) | ![image](https://user-images.githubusercontent.com/17010094/112142070-0b0f2d80-8bce-11eb-9e59-cccec95bc34a.png)
-------
Verification passed on 

Brave | 1.24.8 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | `62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.26 Dev`

- Verified IPFS option has been removed from Advanced settings
- Verified ENS support works as expected. Typing in brantly.eth in Send auto resolves the address

Before update | After update
-- | --
![image](https://user-images.githubusercontent.com/17010094/112141597-5d9c1a00-8bcd-11eb-9562-160a2fa5a3fd.png) | ![image](https://user-images.githubusercontent.com/17010094/112141754-9a681100-8bcd-11eb-817d-7030db5f2abd.png)
