### ISSUE TITLE
brave://settings sidenav accessibility and Brave design system light/dark theming, icons, typography

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13688]
Edit/Note: @kliu to tighten up this issue to cover Theming, Typography, and Side Nav. Other issues will be covered in https://github.com/brave/brave-browser/issues/16621 

## Description
Settings is not using latest design system light/dark theme colors, typography, and icons.

## Designs

Improve the accessibility of the sidenav by using interaction states from the design system.
![image](https://user-images.githubusercontent.com/2388823/130659575-479b6c5a-23c0-4b8a-bc07-b3798835cb9e.png)

Bring the settings page in line with the Brave design system:
-update all typography to Poppins
-update icons with ones from our Brave icon library
-update dark theme colors
-remove shadows from the cards

![image](https://user-images.githubusercontent.com/2388823/130659592-d3978461-daea-445a-900e-2406a148b987.png)

## Assets
Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/?node-id=359%3A9749

**Comment by karenkliu** [comment]
Designs added!

**Comment by bbondy** [comment]
I think IPFS and Crypto Wallets should be close together and in the same section. Did you want them both in Additional Settings @karenkliu ?

**Comment by karenkliu** [comment]
@rebron Do you want to bump Crypto Wallets up above IPFS?

**Comment by rebron** [comment]
Closing as stale in favor of https://github.com/brave/brave-browser/issues/24216 which was fixed in 1.44.x.
