### ISSUE TITLE
New Tab Page Branded Logo is hidden when content has to scroll

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#13694]
## Description 
When the New Tab Page has so many widgets that cause the window to scroll to see more content, the Branded Logo, which is fixed to the footer area, is also hidden by an overflow of content.

![image](https://user-images.githubusercontent.com/741836/105286674-a30b7f00-5b6b-11eb-873a-abec4dfd0209.png)

**Comment by petemill** [comment]
Closed via https://github.com/brave/brave-browser/issues/13694

**Comment by kjozwiak** [comment]
Cases/Example of what needs to be verified can be found via https://github.com/brave/brave-core/pull/7614#issuecomment-767944763.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.19.87 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

* ensured that the sponsored NTP logo doesn't go below the fold when reducing the size of the browser window
* ensured that https://github.com/brave/brave-core/pull/7614#pullrequestreview-570697970 wasn't occurring when using Brave Today

![image](https://user-images.githubusercontent.com/34715963/106016906-3b4fb980-60c0-11eb-8081-9d5cd7d9e936.png)
![image](https://user-images.githubusercontent.com/34715963/106017051-58848800-60c0-11eb-9750-df9f8633ce68.png)
![image](https://user-images.githubusercontent.com/34715963/106017004-4dc9f300-60c0-11eb-8b55-37737259e77e.png)
