### ISSUE TITLE
Canvas farbling does not take into account the entire canvas

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#13690]
As noticed by @iefremov, the canvas farbling algorithm only takes into account a fraction of the total canvas, which could potentially provide access to all of the original canvas if a determined attacker scripted around it. (This is currently theoretical.)

**Comment by LaurenWags** [comment]
@pilgrim-brave @pes10k please advise if this issue should be marked `QA/Yes` and provide a test plan if so. If not, please label `QA/No`.

**Comment by pilgrim-brave** [comment]
This is adequately covered by automated tests.
