### ISSUE TITLE
Website crashes Brave.

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#13698]
## Description 
Website crashes Brave.

## Steps to Reproduce
   1.  `www.computerbase.de `
   2.  Brave display Website and exit
   3. 

## Actual result:
Crash.

## Expected result:
Display Website.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave	1.19.86 Chromium: 88.0.4324.96 (Offizieller Build) (32-Bit)
Überarbeitung	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
Betriebssystem	Windows 10 OS Version 1909 (Build 18363.592)

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?
  Yes 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
  No

**Comment by ryanbr** [comment]
No issues here, it does launch a gdpr consent check at the start.

Try testing in private window mode, also any filters enabled in `brave://adblock` ?

**Comment by Johann999** [comment]
This issue exists on several PCs with Brave Version 1.19.86:
  1. www.computerbase.de
  2. anwser the gdpr consent check
  3. select 'Downloads' in the top bar
  4. scroll down --> Crash
  
This issue does not exist under Brave Version 1.18.78 (tested on several PCs).

This issue does not exist under Chrome, Chromium and other Chromium-based browser.

**Comment by Johann999** [comment]
Very often Brave Version 1.19.86 crashes also on community.brave.com.

No crash-report will be created. brave://crashes is empty.

For every crash one item will be added in the file debug.log:
[0124/145012.135:ERROR:filesystem_win.cc(129)] GetFileAttributes C:\Users\xxxxx\AppData\Local\BraveSoftware\Brave-Browser\User Data\Crashpad\attachments\e08dbb1d-4f6b-4dc4-a490-254e75ac5c65: Das System kann den angegebenen Pfad nicht finden. (0x3)
[0124/145644.312:ERROR:filesystem_win.cc(129)] GetFileAttributes C:\Users\xxxxx\AppData\Local\BraveSoftware\Brave-Browser\User Data\Crashpad\attachments\721ea37a-fbcd-48cf-b748-46ef849ea3e6: Das System kann den angegebenen Pfad nicht finden. (0x3)
