### ISSUE TITLE
(Rewards staging)Trying to verify publisher/creator status on facebook.com returns HTTP 403

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#13709]
## Description 
Using the Brave Rewards staging environment, attempting to verify publisher/creator status for `facebook.com` returns an `HTTP 403` 

## Steps to Reproduce

   1.  Using a clean profile, launch Dev with `/Applications/Brave\ Browser\ Dev.app/Contents/MacOS/Brave\ Browser\ Dev --args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-debug --rewards=staging=true`
   2.  Load `facebook.com` 
   3.  Click on the BAT Rewards icon in the URL bar, skip the tour, click Done
   4. Click the BAT Rewards icon again, and click Refresh Status

## Actual result:
<img width="1201" alt="Screen Shot 2021-01-21 at 3 25 22 PM" src="https://user-images.githubusercontent.com/387249/105424840-f4178380-5bfc-11eb-9423-78360d967615.png">

From the logs:
`
[2896:775:0121/152459.449127:VERBOSE5:ledger_impl.cc(133)] 
[ REQUEST ]
> URL: https://pcdn.bravesoftware.com/publishers/prefixes/3119
> Method: UrlMethod::GET
[2896:775:0121/152459.589693:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://pcdn.bravesoftware.com/publishers/prefixes/3119
> Result: Failure
> HTTP Code: 403
> Body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5BA6BC3BD5B63D15</RequestId><HostId>B4+9wbjYMSH7hYMAtZbNT8nJH6pq5oNkL8TRdY0rw9GIniHxJUKkK0RyvEDdJvKfhLBxQTrSAaU=</HostId></Error>
`
## Expected result:

When launched _**without**_ `--rewards=staging=true`, we should see:

`[3012:775:0121/152754.297881:VERBOSE5:ledger_impl.cc(133)] 
[ REQUEST ]
> URL: https://pcdn.brave.com/publishers/prefixes/3119
> Method: UrlMethod::GET
[3012:775:0121/152754.406343:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://pcdn.brave.com/publishers/prefixes/3119
> Result: Success
> HTTP Code: 200
> Body: 
[3012:775:0121/152754.406574:VERBOSE1:database_server_publisher_banner.cc(43)] Empty publisher banner data, skipping insert`

## Reproduces how often: 

100% reproducible using the staging environment.

## Brave version (brave://version info)

Brave | 1.20.86 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by dlipeles** [comment]
Publishers channel list is a bit out of my domain, but in working on the bitFlyer integration I noticed that channels that havn't been verified will return a 403. This is because they do not have a site_banner_lookup in the creators database, and therefore no entry in the pCDN. cc @stephendonner @jumde @yachtcaptain23
