### ISSUE TITLE
Travis CI unit tests failing on brave-core master

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#1370]
Failing with: 

<img width="899" alt="screen shot 2018-10-01 at 11 10 49 am" src="https://user-images.githubusercontent.com/8732757/46307943-2d7bdf00-c56d-11e8-9877-47e199a2796c.png">

**Comment by yrliou** [comment]
Put in 0.55.x milestone because tests are failing in 0.55.x and 0.55.x too.
