### ISSUE TITLE
Feature request: make "Private" label in private window less obvious

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#13704]
## Description 

We added explicit labels as well as different coloring to our Private Window and Private Window with Tor to distinguish it from normal windows. However, users have requested for a more minimal "Private" label for privacy purposes.

>Designers of Brave, will it be possible to get rid of the word "Private" on top of the window (and just keep the sunglasses icon) in the next feature update? This is to save space and also to prevent people at the back from seeing I am browsing in private mode.

Reddit: https://www.reddit.com/r/brave_browser/comments/l21t0d/designers_of_brave_will_it_be_possible_to_get_rid/

## Designs
Use only the private icon after the new window loads, and hide the text. (3 second delay)

**Comment by LorisTecnology** [comment]
i would suggest to put only the "private" icon

**Comment by stephendonner** [comment]
@nullhook I don't see the 3-second delay; was that part discussed elsewhere, and skipped?  (TBH, I don't know precisely what it means, either.)

**Comment by nullhook** [comment]
We chose not to opt-in for the delay functionality.

**Comment by LaurenWags** [comment]
@nullhook can the issue be updated with what is expected so QA can properly test this one? There's no test plan in the PR, so being clear in the description will help us test this one.

**Comment by nullhook** [comment]
Added more info

**Comment by stephendonner** [comment]
> Added more info

Thanks for doing so; just one more thing to add when verifying, is that we should also check that the `Private Window` count dynamically updates:

![13704-1](https://user-images.githubusercontent.com/387249/146272019-029b4364-6fa1-4d5e-85a6-23b32c7536c4.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Steps:
1. new profile
2. launched Brave
3. clicked on the "hamburger" menu and chose `New Private window`
4. confirmed the sunglasses icon is without the `Private` label
5. opened and closed Private Windows and confirmed they update their count dynamically
6. clicked on the "hamburger" menu and chose `New private window with Tor`
7. filed https://github.com/brave/brave-browser/issues/20118 for the removal of `Private with` from `Private with Tor` label on the button

Private Window | Private Window with Tor | dynamic window count
------------------|----------------------------|-----------------
![13704-2](https://user-images.githubusercontent.com/387249/146273758-1bf06f24-f351-4da5-960d-ed26a257e758.png) | ![13704-3](https://user-images.githubusercontent.com/387249/146273766-bc12dfa2-b9fa-49b8-8c7b-566357219c56.png) | ![13704-1](https://user-images.githubusercontent.com/387249/146273898-fa66db53-e384-4234-ad77-050c7827dd31.png)
