### ISSUE TITLE
[Desktop] Update BAP UI

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#13701]
See https://github.com/brave/internal/issues/747.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.20.104 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Windows 10 OS Version 2004 (Build 19041.804)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/7698

**Scenario 1: Non-JP Regions**

**Scenario 2: JP Regions**

-	Ensured BAP popup does not appear in new tab page as wallet balance is zero 
 ![image](https://user-images.githubusercontent.com/38657976/108218273-7c386c80-715a-11eb-86b2-59fe2d911411.png)
-	Ensured able to claim grants from BR panel and promotion value appeared in the wallet balance
![image](https://user-images.githubusercontent.com/38657976/108218328-8a868880-715a-11eb-9545-9c869a601b5c.png)
![image](https://user-images.githubusercontent.com/38657976/108218351-8fe3d300-715a-11eb-885f-addf9d520bbf.png)
-	Ensured BAP popup appeared in the NTP
![image](https://user-images.githubusercontent.com/38657976/108218433-a5f19380-715a-11eb-86c1-8462f3d96041.png)
-	Ensured BAP popup doesn’t appear in NTP once the BAP popup is closed
-

**Comment by kjozwiak** [comment]
Moving this into `1.22.x` as the BAP work is being reverted via https://github.com/brave/brave-core/pull/8088. Once we have more information next week, we'll re-revert https://github.com/brave/brave-core/pull/8088 and move everything back into `1.21.x` and release `1.21.x - Release #2`.

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Windows 10 OS Version 2004 (Build 19041.804)

```

Verified the test plan from https://github.com/brave/brave-core/pull/7698

<details>
<summary>Scenario 1: Non-JP Regions</summary>

- Ensured that users can claim the UGP grants
- Ensured that promotion value is displayed in the wallet balance
- Ensured there is no BAP popup display in the NTP
- Ensured that user can send one-time tip/recurring tip to regular pubs
- Ensured that user can send one-time tip/recurring tip to media pubs
- Ensured one-time tips displayed under the Tips panel 
- Ensured recurring tips displayed under the Monthly Contributions
- Verified that pubs can be added to the AC table
- Ensured that tips sent to nonverified pubs are  stored in the pending contribution table

</details>

<details>
<summary>Scenario 2: JP Regions</summary>

</details>
