### ISSUE TITLE
Cross-site trackers blocked for GET on /api/log with some query parameters

### ISSUE THREAD

**Issue by kevinlefur** [brave/brave-browser#13707]
## Description 
When performing an AJAX call on `/api/log` with any query parameter (even `api/log?`), the request get blocked as a cross-site tracker. Using `logs` instead of `log` does not trigger any blocking mechanism.
You can also trigger this blocking mechanism by injecting a script in the HTML page.

## Steps to Reproduce
   1. Create a simple HTML page containing a `<script type="text/javascript" src="/api/log?"></script>` tag
   2. Access the page in Brave with shields up
   3. The call to this endpoint is blocked

## Actual result:
![image](https://user-images.githubusercontent.com/70568580/105417341-c1d94680-5c3b-11eb-8aef-d763a4f5ed4b.png)

## Expected result:
The call goes through and reaches the server.

## Reproduces how often: 
Systematic

## Brave version (brave://version info)
**Brave**  1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
**Revision**  68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
**OS** Windows 10 OS Version 2004 (Build 19041.746)

## Version/Channel Information:
- Can you reproduce this issue with the current release?  **Yes**
- Can you reproduce this issue with the beta channel?  **Not tested**
- Can you reproduce this issue with the nightly channel?  **Not tested**

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? **Yes**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **No**

## Miscellaneous Information:
N/A

**Comment by ryanbr** [comment]
Hi @kevinlefur 

Correct, `/api/log?` is blocked (see: https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L848)

The other potential issue, we block localhost 3rd-party request, which show up in your shileds.

If you have a legit issue with /api/log? and a way to replicate the problem, I'm happy to look at it.

**Comment by kevinlefur** [comment]
Hi @ryanbr,

Thanks for the link to easylist, this will come in handy. When designing APIs for enterprise applications, we usually don't think about such generic filter lists. Calls to `/api/v1/metrics` or `/api/log` could very well point to legitimate statistics endpoints for e.g. reading audit logs.

I can live with `/api/logs?` in my current usecase (my API naming convention is the only thing hurt), but I'm wondering what your suggestion would be on legacy APIs. In most cases, allow-listing the domain/endpoint wouldn't help as custom domains are widely used (so allow-listing requests would have to be made by each customer).

**Comment by ryanbr** [comment]
In Easyprivacy,  Due to privacy issues, we'll block event/debug/metric/collector/telemetry logging which these filters  `/api/v1/metrics` or `/api/log` fall into it. Is there a more privacy conscious, an alterative option you can fall back on @kevinlefur

**Comment by kevinlefur** [comment]
Audit logging is required for compliancy. In my example, I'm tracking changes to database objects, and centralizing these changes in a simple Log concept. To display the list of logs (which can be filtered), I was performing a GET request on `/api/log?withSomeQueryParams`. I'm falling back on `/api/logs?withSomeQueryParams`, but it wouldn't make sense to rename the concept at the API level, as this really is a log, but every tracked change is done backend-side.

That's why my endpoint will keep a name which semantic might indicate a privacy-related tracking mechanism, while there is no personal data sent in the process. I will keep an eye on the easylist/easyprivacy lists in the future anyway.

My only concern was that this API pattern looks very common and could be used for legitimate usecases. If you think the benefits outweigh this inconvenience, we can close this issue.
