### ISSUE TITLE
Brave News: promoted content should cycle through items

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#13712]
## Description 

If a user only views 20 cards each session, they might only see the same promoted item. Whilst this is also true of the main feed content, that content might move more quickly than the promoted content which we force to go in to a specific place and sort by date.

Perhaps we should mark items as having been viewed within the last X days (7?) and prefer un-viewed promoted items.

**Comment by mattmcalister** [comment]
No longer relevant. Closing this issue.
