### ISSUE TITLE
[](url)https://mainnet-infura-api.brave.com/phishfort

### ISSUE THREAD

**Issue by Fhiltyphil88** [brave/brave-browser#13710]
[](url)https://mainnet-infura-api.brave.com/phishfort

__Originally posted by @Fhiltyphil88 in https://github.com/brave/brave-browser/issues/13412#issuecomment-760640496__

**Comment by Fhiltyphil88** [comment]
Yello

**Comment by srirambv** [comment]
Please reopen issue with details
