### ISSUE TITLE
Image credit missing for Corwin Prescott

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13717]
## Description 
Image credit missing for Corwin Prescott

## Steps to reproduce 

   1. Install 1.21.20 beta build
   2. Open tab with images from `Corwin Prescott`
   3. Tap on image credit doesn't navigate to photographers page

## Actual result 
Image credit missing for Corwin Prescott

## Expected result
Should load photographers page when image credit is clicked

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.21.20 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by deeppandya** [comment]
@srirambv @karenkliu is this issue still relevant ?

**Comment by karenkliu** [comment]
Corwin did not provide a link, so what is implemented is correct.
