### ISSUE TITLE
Bug: ipfs:// drops query and hash parts 

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#13722]
To reproduce have IPFS enabled and local node is running.

### #fragment

  - enter `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html#Emerging_artist` via address bar
    - :broken_heart:  it loads, but does not jump to `#Emerging_artist` header, and the fragment is also removed from address bar

This makes it impossible for people to link to specific sections of documents

### ?query=params

- `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/I/m/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_(454045).jpg?filename=test.jpg&download=true`
  - :broken_heart: query parameters are not forwarded to the gateway, which in turns produces gateway response missing  `Content-Disposition` header

This makes it impossible to create a link which triggers download instead of having file rendered in browser.

@autonome @bbondy I think we want to fix both, but lmk if there is a reason to keep current behavior.

**Comment by bbondy** [comment]
Nice find!

**Comment by yrliou** [comment]
With https://github.com/brave/brave-core/pull/7693, we won't drop query parameters anymore, but currently we get `Content-Disposition: inline; filename*=UTF-8''test.jpg` instead of attachment for ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/I/m/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_(454045).jpg?filename=test.jpg&download=true, so brave won't open a download dialog but only renders it in the browser.
This is because https://github.com/ipfs/go-ipfs/pull/7677 is merged after go-ipfs 0.7.0 release which brave is currently using.

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/7693

**Comment by stephendonner** [comment]
Verified `**FIXED**` by following the testplan in https://github.com/brave/brave-core/pull/7693 using 

Brave | 1.21.50 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2.1 (Build 20D74)

**Setup:** I first had to install the [IPFS Companion](https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch), then click "Enable IPFS" when prompted by the extension

**Steps:**

1. Visited `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html#Emerging_artist`, which jumped to the "Emerging artist" section of the article.
<img width="835" alt="Screen Shot 2021-02-10 at 5 14 57 PM" src="https://user-images.githubusercontent.com/387249/107593173-98209900-6bc3-11eb-8d45-7757924ba205.png">

2. Opened a new tab, and opened developer tools's Network tab.
3. Visited `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/I/m/Vincent_van_Gogh_-Self-Portrait-Google_Art_Project(454045).jpg?filename=test.jpg&download=true`; `filename=test.jpg&download=true` should be kept in the address bar.
4. Examined the network response using developer tools's Network tab, and saw `Content-Disposition: inline; filename*=UTF-8''test.jpg` in the header, as below.



<img width="1070" alt="Screen Shot 2021-02-10 at 5 05 16 PM" src="https://user-images.githubusercontent.com/387249/107592636-56dbb980-6bc2-11eb-8500-23a3942d5113.png">

**Comment by autonome** [comment]
👋🏼 @stephendonner 😁

**Comment by stephendonner** [comment]
> 👋🏼 @stephendonner 😁

Small 🌎 ; fancy meeting you here!  Brought a smile to my face to know another awesome Mozillian was "at the other end." <3
