### ISSUE TITLE
Add UI on brave://ipfs for tweaking Datastore.StorageMax

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#13720]
Brave v1.19 ships with `StorageMax` set to `1GB` by default:

```
	"Datastore": {
		"GCPeriod": "1h",
		"StorageGCWatermark": 90,
		"StorageMax": "1GB"
```

I've been asked by multiple users how to increase this limit.

Right now they need to:
1. go to http://127.0.0.1:45001/webui → _Settings_ OR find the config file on the disk
2. change the `StorageMax` value and save the config
3. restart the node to apply the config change

I suggest we improve this common operation by adding two UI on the `brave://ipfs` (or proposed `brave://settings/ipfs`) page:
- `<input type="number" ` that defines the number of GB read from the config file
- "Apply" button that updates value in config + restarts the node.

cc @autonome @jessicaschilling @bbondy

**Comment by bbondy** [comment]
I think maybe in the chrome://settings page in its new section will be better, but ++ on the option.

**Comment by jessicaschilling** [comment]
Makes sense to me.
