### ISSUE TITLE
Support IPFS Address Selections for Context Menu Navigation

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#13729]
## Description 
When a user highlights and right-clicks URLs and URIs, Brave offers them a _Go to…_ context-menu option. This is only the case for schemes marked as "Web Safe". Since Brave is natively able to navigate to `ipfs://` addresses, it may be worth considering support for IPFS schemes as well.

## Steps to Reproduce
1. Select this address `https://brave.com/`
2. Right-click the selection
3. Select this address `ipfs://brave/`
4. Right-click the selection

## Actual result:
A _Go to …_ option appears for the first scheme, but not for the latter.

## Brave version (brave://version info)
1.19.86

## Miscellaneous Information:
See [child_process_security_policy_impl.cc](https://source.chromium.org/chromium/chromium/src/+/master:content/browser/child_process_security_policy_impl.cc;l=774?q=IsWebSafeScheme&ss=chromium%2Fchromium%2Fsrc) and [url_constants.cc](https://source.chromium.org/chromium/chromium/src/+/master:url/url_constants.cc;drc=57959538d5a46b41a6a6ed649fa266bafdd19dd7;l=31).

**Comment by bbondy** [comment]
@jonathansampson this seems to be working already for me...

<img width="558" alt="Screen Shot 2021-03-17 at 5 07 01 PM" src="https://user-images.githubusercontent.com/831718/111538535-32d04280-8743-11eb-8b4a-19bc72c42b1a.png">


Maybe it got fixed from another issue? Or am I misunderstanding?

**Comment by jonathansampson** [comment]
Just tested in Nightly, and it looks good on my end as well!
