### ISSUE TITLE
Gemini Balance is Incorrect

### ISSUE THREAD

**Issue by cliffordh** [brave/brave-browser#13728]
<!-- Have you searched for similar issues? Before submitting this issue, please check the open issues and add a note before logging a new issue. 

## Description 
Gemini balance in browser does not match actual value.

## Steps to Reproduce
Add funds to Gemini via checking

## Actual result:
Brave shows double the actual USD value of the portfolio.

## Expected result:
Show actual value of Gemini portfolio.

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (arm64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

## Version/Channel Information:
Have not tried

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? Have not tried
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
n/a

**Comment by rebron** [comment]
Closing as not actionable. Please visit for future issues https://community.brave.com/c/support-and-troubleshooting/48 or use the issue template when filing new issues. We can't act on such little information.
