### ISSUE TITLE
Missing option to allow access to file URLs in PDFJS

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#1372]
## Description 
In Brave Beta/Dev, the PDFJS config options are incomplete. In the "Details" section of the extension, the option to "Allow access to file URLs" option is missing. Setting this allows the browser to find/display pdf files stored locally in-browser.

When testing this on Chrome, navigating to the details section shows this option here:
![image 1](https://user-images.githubusercontent.com/3299098/46309757-2f946c80-c572-11e8-91a9-e417a8ab8981.png)

Without this option available, all locally stored pdf files display in browser like so:
![image](https://user-images.githubusercontent.com/3299098/46309820-67031900-c572-11e8-9806-2afcf826cf5f.png)

## Steps to Reproduce

N/A

## Actual result:
N/A

## Expected result:
N/A

## Reproduces how often: 
Always

## Brave version (chrome://version info)
Version 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
One (of many) user report of this behavior:
https://www.reddit.com/r/brave_browser/comments/9jghrb/brave_beta_now_available/e6zelyo/?context=3&utm_content=context&utm_medium=message&utm_source=reddit&utm_name=frontpage

**Comment by LaurenWags** [comment]
Verified passed with:

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified per https://github.com/brave/brave-core/pull/596 that PDF.js does not display in `chrome://extensions` but only displays in `chrome://components`
