### ISSUE TITLE
No longer receiving ads

### ISSUE THREAD

**Issue by cyberfunk** [brave/brave-browser#13734]
I turned off state level ad targeting thinking I would receive a wider variety of advertisements and since then I no longer receive any ads. I toggled state level ads back on and still am not receiving ads. Has that feature been disabled? Is there anything I can do to troubleshoot or verify that ads are still coming through?

macOS Catalina 10.15.7
Lates Brave release as of Jan 22nd 2021

**Comment by rebron** [comment]
@cyberfunk Is it right to assume you're in the US if you were toggling state level ads? Are your notifications on macOS set up properly, just want to make sure you didn't inadvertently stopped ads from coming through via a notification pref change.

cc: @tmancey

**Comment by cyberfunk** [comment]
Hi rebron. I didn't change anything with macOS notifications. All I did was toggle off the state level option and I'm not even sure if that was the cause. I think it may have been one of the latest updates to the browser that did it. Maybe I'll try downgrading and see if that fixes it.

**Comment by cyberfunk** [comment]
> @cyberfunk Is it right to assume you're in the US if you were toggling state level ads? Are your notifications on macOS set up properly, just want to make sure you didn't inadvertently stopped ads from coming through via a notification pref change.
> 
> cc: @tmancey

My last ad received was on January 20th 2021. How do I find the Brave version that was released around that date and install it?

**Comment by cyberfunk** [comment]
Never-mind I combed through the release pages back to the last official release 1.18.78.

**Comment by tmancey** [comment]
@cyberfunk Would you be happy to have a screen-share so we can investigate? If so, can you please reach out to me via tmancey@brave.com. Thanks, Terry

**Comment by cyberfunk** [comment]
Btw how do I disable autoupdate so I can see if it's a version issue?

**Comment by cyberfunk** [comment]
> @cyberfunk Would you be happy to have a screen-share so we can investigate? If so, can you please reach out to me via [tmancey@brave.com](mailto:tmancey@brave.com). Thanks, Terry

I think it may be my VPN. The crazy thing is that it has been working with VPN up until 5 days ago. I just turned off the VPN and the first ad just came through. Has Brave been updated to reject ads for users with VPN enabled? I use PIA if that helps.

**Comment by tmancey** [comment]
That is great news. VPN can affect ads and have done for a while. I will pass this on to the team for future consideration. Thanks

**Comment by cyberfunk** [comment]
> That is great news. VPN can affect ads and have done for a while. I will pass this on to the team for future consideration. Thanks

That still 

> That is great news. VPN can affect ads and have done for a while. I will pass this on to the team for future consideration. Thanks

That VPN can affect ads still does not explain this. Why would Brave work flawlessly with VPN and then 5 days ago cease delivery of ads altogether? Also the takeaway from this cannot be that a VPN must be disabled to receive ads on Brave. I will continue to experiment and see if I can sort out the root cause and report back if and when I find the catalyst.

**Comment by tmancey** [comment]
Hi

The reason you would have seen ads is you would have still had tokens from before the VPN was enabled, and once these were used up ads would stop if no more tokens could be generated. Right now VPNs will block token generation.

Thank you,
Terry

mobile 07454 469694 | email terry.mancey@icloud.com

**Comment by cyberfunk** [comment]
> Hi The reason you would have seen ads is you would have still had tokens from before the VPN was enabled, and once these were used up ads would stop if no more tokens could be generated. Right now VPNs will block token generation. Thank you, Terry mobile 07454 469694 | email terry.mancey@icloud.com
> […](#)

My VPN has always been enabled from Braves inception on my system. So all tokens were generated with VPN enabled and it has never been disabled until just now when I ran the test. So it was Brave+VPN=Tokens until 5 days ago and then I messed with the location based ads setting and ads stopped even after reverting that setting. I'm going to do a reboot and see if that has any affect.

**Comment by tmancey** [comment]
Hi

VPN rules change from time to time within our internal architecture to work on ways to reduce fraud. I would recommend reaching out on the community with regards to VPN use and send me a link to the post so I can escalate to the right team to help here.

Thank you,
Terry

mobile 07454 469694 | email terry.mancey@icloud.com

**Comment by cyberfunk** [comment]
Ok. FYI ads are now working with VPN after a reboot. I think toggling that location based ads setting threw Brave off. I'm not going to touch those settings ever again🤣 Thanks for your input and feedback.
