### ISSUE TITLE
Public content settings are not inherited by private window

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1373]
## Description
Public content settings are not inherited by private window. I believe these values are initialized with https://github.com/brave/brave-core/blob/master/components/content_settings/core/browser/brave_host_content_settings_map.cc, but because the extension has it's `incognito` property set to `split`, it may not be able to directly access the `regular` scoped content_settings. More investigation is needed

Problem was exposed when fixing https://github.com/brave/brave-browser/issues/1198

Per https://github.com/brave/brave-browser/issues/1721 - if no public settings exist for a given site, private window should inherit the global setting

### Private window inheriting from existing public content setting
   1. Open a new regular tab and visit https://dailymail.co.uk
   2. Using shields icon, disable shields
   3. Open a new private window
   4. Visit https://dailymail.co.uk in that private window
### Private window inheriting from global settings
   1. Change your global settings to be adblock off, fingerprint protection off
   2. Open a new private window
   3. Visit a site you've never been to before

## Actual result:
- For daily mail example, Shields are UP in private window
- For global settings example, global settings are not inherited

## Expected result:
Shields should be DOWN in the private window...  because the session content_settings should inherit from the regular content_settings

## Reproduces how often: 
100%

## Brave version (chrome://version info)
Current master (https://github.com/brave/brave-core/commit/cacede984208d04897970fef1c14ce020e1568f6)

**Comment by bsclifton** [comment]
cc: @bbondy for triage (I picked 1.0, but we may want to fix before then)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

* Verified STR from description
