### ISSUE TITLE
If you hover over the Settings, History, or Bookmark shortcut icons in the footer of the NewTab page, the hover effect displays `chrome://pathName` rather than `brave://pathName`

### ISSUE THREAD

**Issue by steviecs** [brave/brave-browser#13731]
## Description 
If you hover over the Settings, History, or Bookmark shortcut icons in the footer of the NewTab page, the hover effect displays `chrome://pathName` rather than `brave://pathName`

## Steps to Reproduce
   1. Open a new tab
   2. Hover over the Settings, History, or Bookmark Icon in the bottom right hand corner
   3. Note the hover effect results in `chrome://pathname` being visible in the bottom left hand corner of the window

## Actual result:
![image](https://user-images.githubusercontent.com/8968771/105561593-ff85b000-5ccb-11eb-9b39-66ff17835bd7.png)

## Expected result:
The hover effect should display `brave://pathName`

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (x86_64)

**Comment by simonhong** [comment]
@steviecs Duplicated with https://github.com/brave/brave-browser/issues/2566.
Thanks for reporting.

**Comment by steviecs** [comment]
> @steviecs Duplicated with #2566.
> Thanks for reporting.

Of course - I submitted a PR for it as well - https://github.com/brave/brave-core/pull/7684

**Comment by simonhong** [comment]
@steviecs Left some comments on it :)

**Comment by steviecs** [comment]
@simonhong thanks! I'll take a look :)
