### ISSUE TITLE
Cannot download Brave Browser on new Mac M1 - Varnish Error 503

### ISSUE THREAD

**Issue by porteron** [brave/brave-browser#13730]
There was an issue reported by a user when trying to download the Brave Browser on a new MacBook Pro with M1 chip.

Reporting here. Varnish Error 503

<img width="841" alt="Screen Shot 2021-01-22 at 3 51 24 PM" src="https://user-images.githubusercontent.com/16027973/105560777-b0d71680-5cc9-11eb-978b-d846af504d55.png">

**Comment by rebron** [comment]
@porteron Still an issue with that user?
