### ISSUE TITLE
Replace graphics on RE onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13749]
## Description 
Replace graphics on RE onboarding

## Steps to reproduce 

   1. Clean install 1.20.85 x64 beta build
   2. Go through RE onboarding
   3. Graphics has some junk characters 

## Actual result 

Garbled You | Arrow not visible
-- | --
![image](https://user-images.githubusercontent.com/17010094/105699265-fa5c7700-5efe-11eb-8c5f-cfb7279e8cea.png) | <img width=200 src=https://user-images.githubusercontent.com/17010094/105699306-0a745680-5eff-11eb-9ced-05a93f2a4fca.png>

## Expected result
As per
![image](https://user-images.githubusercontent.com/61210652/104257787-0f330800-5433-11eb-8e36-90ba6be21180.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version: 10
   
## Brave version
1.20.85 Beta Build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @codybanxs 
Follow up to #13055

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.90 x64 build
- Verified the graphics on first and fifth screens are replaced according to the new spec
- Verified other images on the welcome tour are not affected
 
![image](https://user-images.githubusercontent.com/17010094/106742491-0342fc00-6615-11eb-8ef6-a363bc6d9334.png) | ![image](https://user-images.githubusercontent.com/17010094/106742518-0b9b3700-6615-11eb-910a-ac1c011d2ea8.png)
-- | --

-------------
Verification passed on Samsung Tab A with Android 10 running 1.19.90 x64 build
- Verified the graphics on first and fifth screens are replaced according to the new spec
- Verified other images on the welcome tour are not affected
 
![image](https://user-images.githubusercontent.com/17010094/106743117-db07cd00-6615-11eb-9902-b0176d2c2f64.png) | ![image](https://user-images.githubusercontent.com/17010094/106743153-e6f38f00-6615-11eb-8034-98198b0e0c86.png)
-- | --

**Comment by kjozwiak** [comment]
Currently happening in `1.19.88 CR: 88.0.4324.96` so adding `release-notes/include` as the issue was already user facing.
