### ISSUE TITLE
Adblock rules should apply to HTTP subresources of an IPFS page

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13742]
## Description 

Applying adblock rules to IPFS doesn't work well because CIDs will often have path based fragments that are used in ABP filter syntax.  However it should apply to HTTP(S) subresources of an IPFS page.

This issue should be fixed after: https://github.com/brave/brave-browser/issues/10220

## Steps to Reproduce

   1. Navigate to an IPFS page and open up the JS console
   2. Type in this script:
```
var script = document.CreateElement('script')
script.src = 'https://brianbondy.com/static/js/analytics.js'
document.body.appendElement(script)
```
   3. The resource should be blocked. 

## Actual result:

The resource is not blocked.

## Expected result:

The resource should be blocked and the block count should increase by 1.

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.21.x and below (all before this is fixed)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel?  yes

**Comment by stephendonner** [comment]
Verified **`FIXED`** using 

Brave | 1.21.51 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2.1 (Build 20D74)

With the inline testcase, on 

Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}

the script resource isn't blocked.  It **_is_** using `1.21.51`, with the following message:

`GET https://brianbondy.com/static/js/analytics.js net::ERR_BLOCKED_BY_CLIENT`

<img width="1608" alt="Screen Shot 2021-02-12 at 10 34 56 PM" src="https://user-images.githubusercontent.com/387249/107844698-a967d200-6d8a-11eb-93ef-143f4def115c.png">
