### ISSUE TITLE
PDFs downloading automatically and not prompting the save location

### ISSUE THREAD

**Issue by prashanthwagle** [brave/brave-browser#13743]
## Description 
I have set my download settings to "ask before download". This works correctly with all types of files except PDF. While downloading PDF files (not opening them) for the first time, the "Save As" prompt will appear. But subsequent downloads of PDF files won't prompt for the location of download and instead will automatically download the files to the Downloads folder.
Issue noticed in Windows 10 v2004 and Pop OS/Ubuntu 20.04. This happens regardless of the "Download PDFs instead of opening" option set or unset.

## Steps to Reproduce

   1. Enable the "Ask where to save each file before downloading" option in the settings.
   2. Download a PDF file. A prompt will appear.
   3. Download another PDF file (Or the same pdf again). A prompt won't appear, instead it will be saved to the Downloads folder
   4. To reset this behavior, restart the browser session

## Actual result:
Except for the first time in the browser session, all PDFs being downloaded automatically without asking for the download location. This is observed only in PDF files.

## Expected result:
A prompt should appear which asks for the download location of the file, regardless of the type of file being downloaded.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave: 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
Revision: 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS: Windows 10 OS Version 2009 (Build 19042.746)

**Comment by GeetaSarvadnya** [comment]
@prashanthwagle Unable to reproduce the issue in `Windows 10 x64 - 1.19.86`. Are you seeing this issue in a clean profile or upgraded profile? also, are there any extensions installed?
![13743](https://user-images.githubusercontent.com/38657976/105676366-6dbab480-5f10-11eb-88fe-aab00b5a73fa.gif)

**Comment by prashanthwagle** [comment]
Please try downloading direct PDFs, like a Gmail attachment or from an S3 bucket or so.

**Comment by GeetaSarvadnya** [comment]
@prashanthwagle I have tried downloading PDF's from gmail, I am getting a save location prompt each time I download PDF.
Can you share the recorded file?

**Comment by prashanthwagle** [comment]
Update: Issue isn't present in Linux (Ubuntu, 20.04).
I shall be closing the issue now and if in case I observe the issue on my windows machine, I shall reopen it.
Thanks for the help!
