### ISSUE TITLE
IPFS with local node has Shields UI not available

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13741]
## Description 

Clicking on the Brave shields when loading a top level IPFS URI does nothing. It also shows up as disabled. 

## Steps to Reproduce

   1. Setup Brave to use an IPFS local node
   2. Navigate to ipfs://bafybeie6yrq55dxvnp3bzkyh7l6e4udfqqvtpoebkxaomqsylb7sbsf2ae/
   

## Actual result:

Shields panel is always disabled

## Expected result:

Shields panel should be enabled.

## Brave version (brave://version info)

1.21.x and below (all versions up until it is fixed)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel?  yes

**Comment by stephendonner** [comment]
Verified **`FIXED`** using the inline test plan here, with 

Brave | 1.21.55 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2.1 (Build 20D74)

1. Setup Brave to use an IPFS local node
<img width="682" alt="Screen Shot 2021-02-16 at 10 34 02 AM" src="https://user-images.githubusercontent.com/387249/108106797-4785c180-7043-11eb-9fbb-244d3340b296.png">

2. Navigate to `ipfs://QmUoGhtHGFExwC3Amd8tqYD7T6LczSRchpRe5wPwtaXodC` (Note the output of the add command above might have given a different CID If you have an extra space or anything like that in your file)
3. Check your console and it should have some text
<img width="986" alt="Screen Shot 2021-02-16 at 10 32 55 AM" src="https://user-images.githubusercontent.com/387249/108106517-e65dee00-7042-11eb-884b-8e34d6aa4e59.png">
4. Turn on script blocking, and on the next reload the console should not display anything
<img width="1282" alt="Screen Shot 2021-02-16 at 10 33 26 AM" src="https://user-images.githubusercontent.com/387249/108106522-e827b180-7042-11eb-820a-c7006b46985b.png">
5. Turn off global shields and the script blocking should display again
<img width="1282" alt="Screen Shot 2021-02-16 at 10 38 41 AM" src="https://user-images.githubusercontent.com/387249/108106715-2cb34d00-7043-11eb-9e46-6edd70e22699.png">
