### ISSUE TITLE
Apple ID Login not working

### ISSUE THREAD

**Issue by teepmbyse** [brave/brave-browser#13747]
## Description 

Logging into an Apple account through any Webapp (e.g. TickTick) doesn't work.

## Steps to Reproduce

   1. Visit any website that requires you to log in using an Apple account (e.g. https://ticktick.com/signin)
   2. Press "Apple"
   3. Insert email and password, click on the arrow to continue
   4. Press Continue 

## Actual result:

It's loading for half a second but nothing changes.

## Expected result:
Login should be completed and successful.

## Reproduces how often: 

Easily reproduced. Happens every time.

## Brave version (brave://version info)

V1.19.86

## Version/Channel Information:

I don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- No

**Comment by rebron** [comment]
cc: @jumde @LaurenWags I just tried this on TikTok with my Apple ID login and I couldn't reproduce on 1.20.85.

**Comment by rebron** [comment]
I was able to login to `TickTick` (as well as TikTok). 
<img width="824" alt="Screen Shot 2021-01-27 at 5 33 44 PM" src="https://user-images.githubusercontent.com/5951041/106077130-d303d680-60c5-11eb-81de-1070db8483a4.png">

I do run into a device check though and have to enter another code as a second factor. Did you run into Apple's device check? @teepmbyse

**Comment by LaurenWags** [comment]
I was unable to reproduce - I used `1.19.88` to successfully login to the site using my apple id. I did encounter the apple device check @rebron mentioned.

**Comment by teepmbyse** [comment]
It worked now, after trying a few times in a row.
