### ISSUE TITLE
Websites can't open in the same tab

### ISSUE THREAD

**Issue by giwrgosmant** [brave/brave-browser#13740]
## Description 
On the latest Stable Build Version 1.19.86 whenever I try to open a link website without being default browser Brave in the same tab, I can't. If I long press on the link and open it in a new tab it works. Check [this video](https://mega.nz/file/zolnzS6Q#D7TFLB-j_SLCVi-0Iaga27cWaUiUzpL61YX0BgY7inU) I've recorded to completely understand what I am talking about.

## Steps to reproduce 

   1. Open Brave without set it as default and have Github app installed.
   2. Search: github brave browser.
   3. Tap on website of github.

## Actual result 
Does not open the website.

## Expected result
It should open the website.

## Issue reproduces how often 
Always present, easily to reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARMx64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.19.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional information

As I said in description check [this video](https://mega.nz/file/zolnzS6Q#D7TFLB-j_SLCVi-0Iaga27cWaUiUzpL61YX0BgY7inU) I've recorded to completely understand it.

**Comment by srirambv** [comment]
Whats the default browser set to? 

cc: @samartnik @SergeyZhukovsky

**Comment by giwrgosmant** [comment]
> 
> 
> Whats the default browser set to?
> 
> cc: @samartnik @SergeyZhukovsky

Haven't set any default browser. I like to choose.

**Comment by giwrgosmant** [comment]
Now I am able to reproduce the issue on the latest Beta and Nightly as well.

**Comment by giwrgosmant** [comment]
@srirambv @samartnik @SergeyZhukovsky 
Any progress update about this issue? It's started to become really annoying....affects my browsing in Brave daily and should be in priority.
After some tests I noticed it's somehow related with the default browser. I haven't set any default browser as I said, I prefer to choose every time with which app I will open the links. It was fine in previous versions before v1.19.86.
Please take a look.

**Comment by giwrgosmant** [comment]
It seems to be fixed on the latest Nightly 1.23.5.

**Comment by giwrgosmant** [comment]
In the latest stable version Brave 1.21.74 issue is fixed.
Thanks 👍
