### ISSUE TITLE
Unable to watch later youtube videos from 3rd-party sites.

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#13748]
## Description 
Visiting https://www.theverge.com/2019/2/3/18209861/super-bowl-liii-twilight-zone-jordan-peele-cbs-all-access-watch  clicking on the "watch later" icon doesn't do anything.
Was reported: https://www.reddit.com/r/brave_browser/comments/l46elm/has_anyone_found_a_fix_for_the_embedded_youtube/

## Steps to Reproduce

   0. Ensure you are logged into youtube already.
   1. Visit https://www.theverge.com/2019/2/3/18209861/super-bowl-liii-twilight-zone-jordan-peele-cbs-all-access-watch
   2. On the top youtube video, click on "watch later" icon.
   3. Nothing occurs. (check your watch later on youtube icon)

## Actual result:
Unable to watch later on youtube videos.

## Expected result:
Allow user to watch later on embedded 3rd-party youtube videos.

## Reproduces how often: 
Easily, with shields on (and cross-site cookies  enabled)

## Brave version (brave://version info)
`Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `Yes, Allow Cookies is needed.`
- Is the issue reproducible on the latest version of Chrome? No.

## Miscellaneous Information:

A Number of youtube cookies are blocked in Brave:
![youtube-cook](https://user-images.githubusercontent.com/1659004/105680178-3ff75f00-5f54-11eb-838a-c15e08eb52c1.png)

The specific cookie causing the issue is labelled `__Secure-3PSID`. Removing this cookie will specifically break the hover to show your name.  Changing the value of `__Secure-3PSID` will cause dialog/window to come up, seems to be a UUID.

Unsure what that other cookie elements are being used. If it 

Cookies blocked when not logged into youtube:
![youtube-cook2](https://user-images.githubusercontent.com/1659004/105682488-61a61580-5f57-11eb-87de-2909f0e315df.png)

**Comment by ryanbr** [comment]
@pes10k  thoughts on this?

**Comment by pes10k** [comment]
This is fixed by https://github.com/brave/brave-browser/issues/8514 (along with many other features that rely on storage in third party frames).  Right now you can enable the feature in Brave Nightly, and enabling Ephemeral Storage in brave://flags. The feature should be enabled by default in Brave 1.21 (once it goes through Beta testing).

Hope that helps!  I'm going to close this action since its solved by https://github.com/brave/brave-browser/issues/8514 but please follow up if i've missed anything.  Thanks for the report!
