### ISSUE TITLE
Missing scroll bar from https://talk.collegeconfidential.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#13759]
## Description 
Visiting various links on `https://talk.collegeconfidential.com/` Scroll bar disappears.

## Steps to Reproduce

   1. Open `https://talk.collegeconfidential.com/`
   2. Click on various links
   3. Scroll bar disappears

## Actual result:

![talkcoll](https://user-images.githubusercontent.com/1659004/105783926-8bede680-5fdc-11eb-8864-7dec2d4bcbaa.png)

## Expected result:
Expect a scroll bar

## Reproduces how often: 

Easily with shields enabled.

## Brave version (brave://version info)
`Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Seems to be a GDPR issue, Still investigating which list causing this.

`https://ccpa-service.sp-prod.net/ccpa/consent/9434/display-dns?requestUUID=`
`https://ccpa-notice.sp-prod.net/?message_id=413872`

**Comment by ryanbr** [comment]
Will keep this open, to ensure fix is rolled out and confirmed. Will re-check in 2-3 days.

**Comment by rebron** [comment]
@ryanbr Looks like we can close this one. Scrollbars are appearing for me.

**Comment by ryanbr** [comment]
Okay, closed.
