### ISSUE TITLE
PDFJS not installed by default

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1375]
## Description 
@GeetaSarvadnya and myself have run into an issue where PDFJS is not being installed for us with clean profiles. I noticed that the last time it appears to have been installed by default was with version 0.54.4. From 0.55.1 onward it is not installed by default for me. (unsure if @GeetaSarvadnya sees the same) I'm using macOS 10.12.6

## Steps to Reproduce
  1. Use `rm -rf ~/Library/Application\ Support/BraveSoftware` and `rm -rf ~/Library/Caches/BraveSoftware` to remove any existing Brave data
  2. Delete app from Applications folder and delete existing .dmg file.
  3. Download 0.55.1 or later.

## Actual result:
PDFJS is not installed by default
![0551-nopdfjs](https://user-images.githubusercontent.com/28145373/46313977-4a2d0c80-c597-11e8-854b-3af1f0c64669.gif)

## Expected result:
PDFJS installed by default
![0544-pdfjs](https://user-images.githubusercontent.com/28145373/46313985-50bb8400-c597-11e8-9148-7861ac1b6b2d.gif)

## Reproduces how often: 
easily

## Brave version (chrome://version info)
Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? n/a
- Does it reproduce on browser-laptop? n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @GeetaSarvadnya @srirambv who also experienced the issue however @kjozwiak did not.

**Comment by bsclifton** [comment]
@LaurenWags I think this is expected, right? If you launch Brave via the command line, you can use the following argument to show "built in" extensions: `--show-component-extension-options`

ex:
`/Applications/Brave-Browser-Dev.app/Contents/MacOS/Brave\ Browser\ Dev --show-component-extension-options`

cc: @yrliou

**Comment by LaurenWags** [comment]
@kjozwiak were you launching via command line with the argument when you saw PDFJS installed?

**Comment by yrliou** [comment]
PDF Viewer should show without that argument.

**Comment by bsclifton** [comment]
woah- it's showing the `Chromium PDF Viewer?!

**Comment by yrliou** [comment]
@bsclifton They're two different extensions, I think PDFJS (PDF Viewer) should be shown without the argument, which I could see that it is there in my Brave-Browser-Dev.

**Comment by bsclifton** [comment]
@yrliou correct- I remember seeing that too. But I don't think we want `Chromium PDF Viewer` being loaded right? IIRC, including it increases the surface for vulnerabilities

cc: @diracdeltas

**Comment by yrliou** [comment]
@bsclifton In my Brave-Browser-Dev, it is not enabled. @LaurenWags saw as enabled might probably be related to this issue.

**Comment by bbondy** [comment]
@LaurenWags Chromium PDF Viewer we can probably blacklist, pls branch off another issue for that with STR with the args @bsclifton mentioned.

@LaurenWags for this one, can you check if you have a firewall blocking 
https://go-updater.brave.com/extensions by chance?

**Comment by bbondy** [comment]
Or can you completely disable your firewall temporarily to try to narrow down the problem?

**Comment by LaurenWags** [comment]
@bbondy disabling my firewall does not appear to help. I can get PDFJS by downloading version 0.54.4 but if I clear my profile and then try using version 0.55.1 or later PDFJS does not download.

**Comment by kjozwiak** [comment]
@GeetaSarvadnya & @srirambv ran into the same thing under Win 10 and mentioned that they didn't see `PDFJS` being listed under `chrome://extensions` after initially starting `brave-core`. However, I haven't personally ran into this before.

@bbondy I don't think it's a firewall issue as @LaurenWags & @srirambv have had the `PDFJS` before as they verified a few issues. @LaurenWags confirmed that `Little Snitch` has also been disabled since the Ethereum work.

Could this be a network issue? When we're fetching `PDFJS` on startup, could it be possible that there's some kind of network error/timeout which prevents `PDFJS` from being installed? Would debugging with `Wireshark` help?

**Comment by GeetaSarvadnya** [comment]
@bbondy:  As @LaurenWags @kjozwiak  mentioned I ran into the same issue on Windows 10. I have tried uninstalling brave completely by deleting both Executable file folder and profile folders. But issue did not resolve, also i observed one thing there is no "Extension" folder in the profile folder path.
![pdfjs issue on windows 10](https://user-images.githubusercontent.com/38657976/46348068-584c5d00-c66b-11e8-8c41-8cf21c81e043.gif)

**Comment by srirambv** [comment]
I can reproduce this on clean profile for Beta and Dev on Windows. No PDF extension shown on `chrome://extensions`. Linux however for Beta shows the blank page momentarily before loading PDF extension. Linux Dev build shows instantly. This is happening on the same network for both Windows and Linux and default firewall settings on Windows.

**Comment by bbondy** [comment]
QA notes, when testing it won't show up in about:extensions anymore, only in about:components. And file access will now work.

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified with https://github.com/brave/brave-browser/issues/1375#issuecomment-428455030
* Verified able to open several PDFs without issue
![screen shot 2018-10-12 at 5 30 04 pm](https://user-images.githubusercontent.com/28145373/46895006-8f2d2a80-ce44-11e8-83c5-e0d326d1f855.png)
