### ISSUE TITLE
Brave Does Not Support WebGL

### ISSUE THREAD

**Issue by MrTeeXD** [brave/brave-browser#13757]
## Description 
There is a Twitch Interactive Web-Based game called StreamRaiders and for some reason, when I try to access the site, the site says that Brave does not support WebGL.

## Steps to Reproduce

   1. Go to https://www.streamraiders.com/game/
   2. Log in with your Twitch Account

## Actual result:

The result bring up this error message:
![brave_7QnhU81jRb](https://user-images.githubusercontent.com/37266538/105778845-dab46580-5f75-11eb-9c8b-1a2468bfceb4.png)

## Expected result:
I expected that I can access the site easily without having to deal with this problem

## Reproduces how often: 

This was easily reproduced everytime you visited StreamRaiders

## Brave version (brave://version info)

1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?: Yes
- Can you reproduce this issue with the beta channel?: Yes
- Can you reproduce this issue with the nightly channel?: Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by thefallofbecause** [comment]
Brave & Chrome both definitely support WebGL, so it sounds more like a graphics driver or system issue.

What happens when you visit [https://get.webgl.org/](https://get.webgl.org/)?

**Comment by MrTeeXD** [comment]
It says that its disabled but my GPU Drivers are up to date. I wonder what effect it will have if I enable the Hardware Acceleration support in Brave

**Comment by MrTeeXD** [comment]
Oh what the hell. Apparently, disabling the GPU Acceleration inside Brave breaks the WebGL Supports. I re-enabled it and it works now. In other browsers such as Opera GX, this was not an issue

**Comment by rebron** [comment]
@MrTeeXD Sounds like it's working with that setting? I'm going to go ahead and close this one out.

**Comment by thefallofbecause** [comment]
@IwateKyle Have you checked that hardware acceleration is turned on in Brave?

**Comment by IwateKyle** [comment]
> @IwateKyle Have you checked that hardware acceleration is turned on in Brave?

Thanks, I didn't know how to do it before.  But, since you mentioned it, I tried to find it again (hardware acceleration setting) and found it.  That did the trick.  I found this message just after I started using Chrome again.  I'm glad I found this message, though.  I just unsynced chrome and I'm back on Brave.  Thanks again.
