### ISSUE TITLE
Windows Release Build Error

### ISSUE THREAD

**Issue by Ahmed-Imam** [brave/brave-browser#13750]
## Steps to Reproduce

   1. git clone https://github.com/brave/brave-browser.git
   2. npm install
   3. npm run init 
   4. npm run build Release

## Error
<img width="1082" alt="Screen Shot 2021-01-25 at 9 39 21 PM" src="https://user-images.githubusercontent.com/20854551/105717560-3e7d6500-5f5b-11eb-9c41-ae44a4698713.png">

## Brave version
  "version": "1.21.25"

**Comment by yattin** [comment]
you can see components/brave_sync/BUILD.gn line 11

if (is_official_build) { assert(brave_sync_endpoint != "") }

by default ,brave_sync_endpoint  is empty

**Comment by bsclifton** [comment]
This is expected; there are a few other variables that will error out like this too

Official build is meant to be what we build at Brave Software and distribute (Chromium uses this in a somewhat similar fashion)

You can create an `.npmrc` (either local to the `brave-browser` folder or global to your profile) and set the variable to a fake URL. Sync won't work though (same with other variables expecting to be set)
