### ISSUE TITLE
entered gateway address not retained in "Set IPFS gateway" modal

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13751]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/11563

When the "IPFS public gateway address" setting is modified in brave://settings/extensions, it shows on the settings page. However, if you click the Change button again, your updated URL is not shown in the Set IPFS gateway box, the default URL is shown

## Steps to Reproduce

   1. Open brave://settings/extensions
   2. Click the Change button for "IPFS public gateway address"
   3. Enter a different gateway (ex. `https://cf-ipfs.com`)
   4. Click Submit.
   5. See updated URL on settings page.
   6. Click Change button again.

## Actual result:

Default URL is shown, not what you entered:
<img width="1021" alt="Screen Shot 2021-01-25 at 12 55 04 PM" src="https://user-images.githubusercontent.com/28145373/105746105-08b18f80-5f0d-11eb-9ac2-6fff77d3fec6.png">

## Expected result:
I expected the gateway URL I entered to be shown on the Set IPFS gateway popup.

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.20.88 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a 1.19.x
- Can you reproduce this issue with the beta channel? yes 1.20.x
- Can you reproduce this issue with the nightly channel? yes 1.21.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @bbondy @yrliou

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build with the inline steps to reproduce 

Brave | 1.23.39 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}

Steps:

1.  Opened `brave://settings/extensions`
2.  Click the `Change` button for "IPFS public gateway address"
3.  Entered a different gateway (`https://cf-ipfs.com`)
4.  Clicked `Submit`
5.  Saw updated URL on settings page.
6.  Clicked `Change` button again.

Verified that after clicking on the `Change` button again in step 6, the URL (`https://cf-ipfs.com`) I entered in step 3 persisted.

![ipfs-gateway](https://user-images.githubusercontent.com/387249/111228104-e64d0180-85a0-11eb-996e-60dd76b855b5.gif)
