### ISSUE TITLE
{{numitems}} in brave://rewards instead of the actual number in Polish locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#13764]
Reproduces for One time tips and Monthly contributions

## Steps to Reproduce

1. Clean install
1. Run Brave in Polish (PL) locale
1. Join rewards
1. Tip at least 6 verified publishers
1. Open `brave://rewards`

## Actual result:

Tips and Monthly contributions have `{{numitems}}` instead of the actual number
![image](https://user-images.githubusercontent.com/34715963/105792829-5a4b3000-5f88-11eb-872a-20f2ba1f8de3.png)
![image](https://user-images.githubusercontent.com/34715963/105792789-47d0f680-5f88-11eb-89b6-0b99776b2127.png)
![image](https://user-images.githubusercontent.com/34715963/105792809-4ef80480-5f88-11eb-9911-6634df81d153.png)

## Expected result:
The actual number like in English locale
![image](https://user-images.githubusercontent.com/34715963/105792894-751da480-5f88-11eb-9f13-e716bc191f54.png)

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.20.88 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

Brave | 1.21.26 Chromium: 88.0.4324.96 (Oficjalna wersja) nightly (64-bitowa)
-- | --
Wersja | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
System operacyjny | Linux

Brave | 1.19.86 Chromium: 88.0.4324.96 (Oficjalna wersja) (64-bitowa)
-- | --
Wersja | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
System operacyjny | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @rebron @mkarolin @brave/legacy_qa

**Comment by emerick** [comment]
Seems like it should be named `{{numItems}}` not `{{numitems}}`. Not sure how the wrong capitalization got into the Polish .xtb file (it's the only occurence of that capitalization in our entire repo).

**Comment by mkarolin** [comment]
The case was incorrectly changed in Transifex during l10n. Corrected it in Transifex: https://www.transifex.com/brave/brave/translate/#pl/$/156854308?q=text%3A{{numitems}}

**Comment by emerick** [comment]
Thanks @mkarolin!

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Windows 10 OS Version 2009 (Build 19042.844)
```

Verified using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/13764#issue-793881242.

![Zrzut ekranu 2021-03-10 214127](https://user-images.githubusercontent.com/2602313/110728039-50088c80-81ea-11eb-833c-0031bd3892d5.png)
