### ISSUE TITLE
Missing icons for Hardware wallet on create wallet screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13769]
## Description 

Missing icons for Hardware wallet on create wallet screen

## Steps to Reproduce

   1. Install dev component `1.0.22`
   2. Hardware wallet icons are missing
   3. Text/button alignment is off for both Ledger and Trezor 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/105846460-1f6ee980-5fd4-11eb-861d-223427c4d13c.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/105846375-0108ee00-5fd4-11eb-909d-a0c09531e420.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Ethereum Component `1.0.22` Dev

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Seems to be intermittent issue

**Comment by bbondy** [comment]
When you say > Install dev component 1.0.22
do you mean when you side load from a local build? Or do you mean using a staging build?

**Comment by srirambv** [comment]
Closing the issue for now. Unable to repro the issue anymore. 

> Do you mean when you side load from a local build? Or do you mean using a staging build?

This was done using staging build not side load
