### ISSUE TITLE
Video Background playback stopped working again

### ISSUE THREAD

**Issue by brasscupcakes** [brave/brave-browser#13763]
## Description 
Video Background playback no longer works in the Android App on Youtube or other sites. 

## Steps to reproduce 

   1. Play a Video
   2. Multitask or switch tabs
   3. Video Instantly stops despite background playback enabled in settings. I saw the old thread where it said to put a desktop shortcut to Youtube. This didn't work for me (and I watch videos on other sites besides Youtube).

## Actual result 
No Video No Sound

## Expected result
Video and sound

## Issue reproduces how often 
No steps to reproduce 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes.
- Can you reproduce this issue with the current Play Store Beta version? I don't know. I stopped using the Beta Version.
- Can you reproduce this issue with the current Play Store Nightly version? I don't know.

## Device details
   - Install type (ARM, x86): Android
   - Device type (Phone, Tablet, Phablet):LG ThinQ V35 but it is the same on every Android device I own (four out of four)
   - Android version: Android 10
   
## Brave version
Brave 1.19.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? I uninstalled Chrome on all my devices.

### Additional information

Just a comment. I love Brave and appreciate all your hard work but it would be better if you didn't lock threads on supposedly resolved issues so quickly. Thank you.

**Comment by aviegdown** [comment]
it's hard to reproduce but i found that it could be because we messed up with brave shield too much, fixed by just relaunch brave browser.

**Comment by SergeyZhukovsky** [comment]
@brasscupcakes @aviegdown were you able to replicate it more than once? Maybe there are some certain steps? I cannot replicate it on my side. Also could you please check dev tools(https://developers.google.com/web/tools/chrome-devtools/remote-debugging) if you manage to replicate it? You will need to click on `inspect` of the YT webpage and pick Console there. There has to be some error or something. Thanks

**Comment by fgfgffggg** [comment]
> @brasscupcakes @aviegdown were you able to replicate it more than once? Maybe there are some certain steps? I cannot replicate it on my side. Also could you please check dev tools(https://developers.google.com/web/tools/chrome-devtools/remote-debugging) if you manage to replicate it? You will need to click on `inspect` of the YT webpage and pick Console there. There has to be some error or something. Thanks

@SergeyZhukovsky i found the problem. This is because of m.youtube.com shortcut.

So, how to reproduce :

- go to m.youtube.com
-  open menu > add to home screen
- close brave from recent apps
- open youtube from the shortcut, then play some video

**Comment by SergeyZhukovsky** [comment]
It doesn't stop for me using the steps above

**Comment by SergeyZhukovsky** [comment]
closing as cannot replicate it. We will reopen a new issue if see it happens
