### ISSUE TITLE
PDF loaded using pdfium when PDFJS isn't downloaded 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1376]
## Description 

PDF loaded using pdfium when PDFJS isn't downloaded 

## Steps to Reproduce

   1. Clean profile on Beta , open `chrome://extensions`, no PDFJS installed (#1375)
   2. Visit http://orimi.com/pdf-test.pdf, PDF is loaded in the tab, 
   3. Right click on PDF and inspect, shows 
```
<embed id="plugin" type="application/x-google-chrome-pdf" src="http://orimi.com/pdf-test.pdf" stream-url="blob:chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/55285240-5879-4950-96fe-2c7afe71af08" 
```

## Actual result:

PDF is loaded in a tab even if browser fails to install PDFJS at start

## Expected result:
Should not use `PDFIUM` to load PDF files when PDFJS is not installed/disabled

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy

**Comment by LaurenWags** [comment]
Verified using 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

* Verified when PDFJS is not installed, unable to view PDFs (prompted for download)
* Verified https://github.com/brave/brave-browser/issues/1386#issuecomment-426115090 also
