### ISSUE TITLE
Update wallet icon on top bar 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13770]
## Description 

Update wallet icon on top bar 

## Steps to Reproduce

   1. Install 1.0.22 dev component
   2. Wallet icon is changed on Page and browser action button
   3. Wallet icon is not changed on top bar 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/105847318-5eea0580-5fd5-11eb-90b5-1f4ff3fd175d.png)
![image](https://user-images.githubusercontent.com/17010094/105860144-2fdb9000-5fe5-11eb-8af7-3283314191d9.png)

## Expected result:
Should change icon everywhere

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Component: `1.0.22 Dev`
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by jamesmudgett** [comment]
[crypto-wallet-19.svg.zip](https://github.com/brave/brave-browser/files/5874905/crypto-wallet-19.svg.zip)

**Comment by ryanml** [comment]
OS: MacOS
Build: 1.0.26

Verified that the navigation bar within `brave://wallet` has the updated icon
<img width="1168" alt="Screen Shot 2021-02-12 at 10 36 03 AM" src="https://user-images.githubusercontent.com/8732757/107802122-2dd03b80-6d1e-11eb-9202-543774149e51.png">
