### ISSUE TITLE
Exiting brave://adblock crashes webview

### ISSUE THREAD

**Issue by Maxime-J** [brave/brave-browser#13775]
Brave Version: 1.19.86  Chromium: 88.0.4324.96
Operating System: Windows NT 10.0.19042

URL (if applicable) where crash occurred:
brave://adblock
Can you reproduce this crash?
yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go to brave://adblock, either via URL bar or menu
2. From that tab, go to any other website
=> RESULT_CODE_KILLED_BAD_MESSAGE crash

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/aa360100-604d-b505-0000-000000000000

**Comment by kjozwiak** [comment]
Thanks for the report @Maxime-J 👍 I managed to reproduce the issue using the following build:

```
Brave | 1.21.28 Chromium: 88.0.4324.96 (Official Build) nightly (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2009 (Build 19042.746)
```

### `STR/Case`

* launch Brave and visit `brave://adblock`
* in the same tab, visit another website (https://videocardz.com in this case)

Example:

![image](https://user-images.githubusercontent.com/2602313/105897785-9f05b400-5fe6-11eb-81e9-7a9382f592f1.png)

**Comment by ryanbr** [comment]
cc: @antonok-edm

**Comment by antonok-edm** [comment]
Also able to reproduce in Release and Nightly.

I see this error in the console when the crash occurs:
```
[ERROR:bad_message.cc(26)] Terminating renderer for bad IPC message, reason 193
```

**Comment by iefremov** [comment]
Example dump (the browser process only does `DumpWithoutCrashing`, while renderer crashes, but there is no renderer dump) 
https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3D%2282460000-9cc8-c705-0000-000000000000%22%2C(ver%2Cregex%2C%228%5B5%7C6%7C7%7C8%7C9%5D.*%22)%2Cptype%3Dbrowser)&fingerprint=d0ac1d11f0319c90f64afc2a70d9f4d939a8f626de16505956bda322e48e1878&debug=(c2b2c7,0,0)

```
[ 00 ] crash_reporter::DumpWithoutCrashing()
[ 01 ] base::debug::DumpWithoutCrashing()
[ 02 ] content::RenderProcessHostImpl::ShutdownForBadMessage(content::RenderProcessHost::CrashReportMode)
[ 03 ] BraveAdblockUI::CustomizeWebUIProperties(content::RenderFrameHost*)
[ 04 ] BraveAdblockUI::UpdateWebUIProperties()
[ 05 ] content::WebContentsImpl::RenderViewReady(content::RenderViewHost*)
[ 06 ] content::(anonymous namespace)::RenderProcessHostIsReadyObserver::CallTask()
```

@simonhong I think calling `UpdateWebUIProperties()` as we do now is not 100% correct. And given that the only implementaiton is `BraveAdblockUI` and it is buggy, maybe we can just simplify and remove `UpdateWebUIProperties()`?

**Comment by simonhong** [comment]
@rebron How about disable stats showing in adblock page?
This crash comes from updating blocked stats in adblock page. I think it's redundant because NTP shows same number.

**Comment by iefremov** [comment]
Thanks @simonhong :)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.20.101 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/7811

Reproduced on 1.19.92:
![image](https://user-images.githubusercontent.com/34715963/107298379-8a5cfd80-6a75-11eb-8544-4fb2232a9f96.png)

Verified no crash on 1.20.101
![image](https://user-images.githubusercontent.com/34715963/107298515-dd36b500-6a75-11eb-9ca4-86215a7841ae.png)
![image](https://user-images.githubusercontent.com/34715963/107298820-664dec00-6a76-11eb-9147-bde09b778585.png)
