### ISSUE TITLE
Reduce Ethereum JSON RPC API calls for token list

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13777]
This issue is for our Crypto Wallets (MetaMask fork) at https://github.com/brave/ethereum-remote-client

Our Infura usage is too high.

Infura shows us this breakdown by method calls:
<img width="785" alt="Screen Shot 2021-01-26 at 3 33 41 PM" src="https://user-images.githubusercontent.com/831718/105901857-e6427380-5feb-11eb-859c-5dfa5c9163e5.png">

When you load brave://wallet and login you will see that having that tab open does a lot of Infura calls.

If you add some logging here:
`ethereum-remote-client/node_modules/eth-json-rpc-infura/src/index.js`

For `fetchUrl` you will see that when a token is added, we’re doing several calls to the contract address every few seconds.
You can see this in about://extensions in the background page dev tools. 

In particular we auto-add BAT, so you can see the calls are made for BAT even when that tab is not active.
You can see via looking at the parameters for the calls has the BAT contract address.

I assume maybe these calls are to get the token balance?

Please make the following changes:
1. Find out why these calls are made.
2. Lower the frequency of these calls to reduce Infura usage.
3. Only make these calls when the tab is active or the browser pane is open.

**Comment by ryanml** [comment]
Verification passed on 

--  | --
OS | MacOS
Component | `1.0.26 Dev`

- Verified that no token calls are made when the browser is not in focus, and that they start again appropriately when refocused. Accurate balances and prices are still maintained
![image](https://user-images.githubusercontent.com/8732757/107801896-e944a000-6d1d-11eb-8f5a-528e60ded043.pngg)
