### ISSUE TITLE
Fix adblocking regression for requests made by Service Workers

### ISSUE THREAD

**Issue by kdzwinel** [brave/brave-browser#13781]
## Description 
Resource that should be blocked, according to the custom filters, doesn't get blocked when requested by a service worker.

## Steps to Reproduce
   1.  Go to brave://adblock/
   2. Add `||bad.third-party.site^` to the 'Custom Filters' textarea
   3. Go to https://privacy-test-pages.glitch.me/privacy-protections/request-blocking/
   4. Click "start the test" button

## Actual result:
"serviceworker-fetch" test is green meaning that request to `https://bad.third-party.site/privacy-protections/request-blocking/block-me/fetch.json?serviceworker-…` has been successfully made. This can be additionally verified using DevTools:

<img width="654" alt="not-blocked" src="https://user-images.githubusercontent.com/985504/105919926-bf5d5f00-6036-11eb-8bea-76b646a27403.png">

## Expected result:
All tests should be gray meaning that all requests to `bad.third-party.site` failed to load.

## Brave version (brave://version info)

Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (x86_64)
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

## Miscellaneous Information:

I haven't verified if this issue only affects custom filters or if it's a more general gap that also affects the default protections.

**Comment by antonok-edm** [comment]
Thanks for the report @kdzwinel and good find. I verified that this also affects the default protections; will work on getting a fix in soon.

**Comment by LaurenWags** [comment]
Verified using

```
Brave	1.21.64 Chromium: 88.0.4324.182 (Official Build) beta (x86_64)
Revision	73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS	macOS Version 10.15.7 (Build 19H512)
```

Verified test plan from https://github.com/brave/brave-core/pull/7910

Custom Filters | Default Filters
----- | -----
<img width="857" alt="1" src="https://user-images.githubusercontent.com/28145373/108717972-e733cb80-74eb-11eb-9d8f-9584c3290031.png"> | <img width="1199" alt="3" src="https://user-images.githubusercontent.com/28145373/108717974-e864f880-74eb-11eb-8f75-a896f2bb7b28.png">
<img width="1032" alt="2" src="https://user-images.githubusercontent.com/28145373/108717984-ec911600-74eb-11eb-9b29-455521bc7954.png"> | <img width="1197" alt="4" src="https://user-images.githubusercontent.com/28145373/108717986-edc24300-74eb-11eb-8f92-6aca78847f97.png">

-------------
