### ISSUE TITLE
Only allow whitelisted protocols in tor mode

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1378]
https://github.com/brave/browser-laptop/issues/14664
https://github.com/brave/browser-laptop/pull/14665

**Comment by diracdeltas** [comment]
I just remembered this led to an easy IP proxy bypass on MacOS, so it should be marked as release blocking.

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/583

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/583
