### ISSUE TITLE
Incorrect Korean translation of brave stats in NTP [Followup to #12924]

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13790]
## Description 
Incorrect Korean translation of brave stats in NTP [Followup to #12924]

## Steps to reproduce 

   1. Install 1.19.87 build
   2. NTP Translations are not correct

## Actual result 

https://user-images.githubusercontent.com/17010094/105979137-3c1a2880-608b-11eb-8262-f33cc4a63368.mp4

## Expected result
Fixed translations

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version: 10
   
## Brave version
1.19.87

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @rebron @simonhong @kjozwiak

**Comment by simonhong** [comment]
Updated in transifex. cc @mkarolin

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.88 x64 build
- Verified translations for `Bandwidth saved` and `Time saved` are updated

1.19.86 | 1.19.88
-- | --
![image](https://user-images.githubusercontent.com/17010094/106128844-a6000400-6157-11eb-9a6d-d903e9dc6cd6.png) | ![image](https://user-images.githubusercontent.com/17010094/106128932-ba440100-6157-11eb-91f9-fc1234245816.png)
