### ISSUE TITLE
Feature request - resolve Decentralized Identifiers in the Brave Browser

### ISSUE THREAD

**Issue by jonnycrunch** [brave/brave-browser#13799]
The Decentralized Identifier (DID) specification is rapidly become a real spec and close to Candidate Recommendation.  It would be great to see [DID resolution](https://w3c.github.io/did-core/#resolution) happen natively in the browser!

**Comment by jumde** [comment]
cc: @pes10k @orspetol

**Comment by orspetol** [comment]
Thank you for the message. We currently don't have any plans to implement the spec. Some of the use cases seem interesting, so we may revisit in the future, but in general the spec is large, and so we don't currently think the potential short-to-medium-term benefit to Brave users is large enough for us to implement. That said, we'll be sure to publicly announce if that changes.
