### ISSUE TITLE
Add remove to auto-contribute table

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1379]
We need to add remove for top five sites as well in auto contribute section in Rewards

![image](https://user-images.githubusercontent.com/9574457/46319160-e05c3500-c58d-11e8-8d40-7552f944e779.png)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified  remove `X` is shown next to the publishers when there are 5 or less publishers listed
