### ISSUE TITLE
Deprecate BAP modal

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#13798]
This issue is to notify users in japan about the deprecation of BAP. 

Main issue : https://github.com/brave/internal/issues/747
Design spec : https://www.figma.com/file/9Pn7htrOeZsbOJ2NcxtxvR/bitFlyer-Promo?node-id=206%3A0 

### Note on timing
1. Tooltip or dialog should appear if user's balance is non zero.
2. When user opens the app for the first time and if the balnace is non zero, it should show tooltip or dialog and set next tooltip or dialog show date to 3 days. so when user open the app again after 3 days or later, user should see the tooltip or dialog again. 

Tooltip should be shown till march 6, 2021 and from march 6 to march 13 user should see dialog directly.

**Comment by kjozwiak** [comment]
Moving this into [1.20.x - Release #3](https://github.com/brave/brave-browser/milestone/176) as [1.20.x - Release #2](https://github.com/brave/brave-browser/milestone/173) will be the `1.20.x` Android release as it won't go out on `Feb 9th` due to translations missing.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.104 x64 build
- Verified steps from issue description

<details>
<summary><b>Scenario 1: Non-JP region</b></summary>

- Verified able to claim promotions 
- Verified no BAP modal is shown
- Verified no BAP alert is shown when device date is set to 3 Mar 2021
- Verified no BAP alert is shown when device date is set to 14 Mar 2021
- Verified wallet balance doesn't change or resets to zero when device date is set to 14 Mar 2021

![image](https://user-images.githubusercontent.com/17010094/108203232-1a581280-711a-11eb-8bd0-484b3acaf1cb.png) | ![image](https://user-images.githubusercontent.com/17010094/108203242-1d530300-711a-11eb-93b0-524e9f9ad17e.png) | ![image](https://user-images.githubusercontent.com/17010094/108203251-204df380-711a-11eb-89f7-236f3ee9b4e6.png)
-- | -- | --


</details>
<details>
<summary><b>Scenario 2: JP region</b></summary>

- Verified setting device locale to JP shows and clean install(1.20.103) with 0 BAP balance doesn't show any BAP deprecation modal
- Verified able to claim grant and wallet balance updates
- Verified upgrading to 1.20.104 with a wallet balance shows the deprecation modal upon launch
- Verified modal shows up again when the device date is moved ahead by 3 days
- Verified clicking on learn more brings up a bigger modal with details 
- Verified tapping outside the tooltip closes it 
- Verified clicking only on `OK` closes the BAP info modal and not tapping outside the modal 
- Verified moving device date ahead by 3 days until Mar 6th, keeps showing both tooltip and modal
- Verified moving device date to 6 Mar shows only the BAP alert not the tooltip on Rewards
- Verified moving device date to 13 Mar doesn't show BAP alert or tooltip and wallet balance is reset to 0
- Verified when device date/time is set to Mar 12 11.59PM, keeping the browser active with a wallet balance is reset to 0 without having to restart the browser

![image](https://user-images.githubusercontent.com/17010094/108202636-563ea800-7119-11eb-89b7-3bb92f370290.png) | ![image](https://user-images.githubusercontent.com/17010094/108200406-57baa100-7116-11eb-9fe6-aa7962c2dc2c.png) | ![image](https://user-images.githubusercontent.com/17010094/108202680-69517800-7119-11eb-803d-71e27a83ea48.png) | ![image](https://user-images.githubusercontent.com/17010094/108202849-a0278e00-7119-11eb-809e-e98956ef1bab.png) | ![image](https://user-images.githubusercontent.com/17010094/108202867-a6b60580-7119-11eb-9e3a-536ecf611d78.png)|
-- | -- | -- | -- | --

</details>

**Comment by kjozwiak** [comment]
Moving this into `1.22.x` as the BAP work is being reverted via https://github.com/brave/brave-core/pull/8088. Once we have more information next week, we'll re-revert https://github.com/brave/brave-core/pull/8088 and move everything back into `1.21.x` and release `1.21.x - Release #2`.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.21.76 x64 build
- Verified BAP notice is shown daily 

<details>
<summary><b>Case 1 - Japan region</b></summary>

- Verified setting device locale to JP shows and clean install(1.21.74) with 0 BAP balance doesn't show any BAP deprecation modal
- Verified able to claim grant and wallet balance updates
- Verified upgrading to 1.21.76 shows BAP deprecation notice if the wallet already had a balance in 1.21.74(GPS build)
- Verified modal shows up again when the device date is moved ahead by 1 day
- Verified clicking only on OK closes the BAP info modal and not tapping outside the modal
- Verified moving device date to 13 Mar doesn't show BAP alert and wallet balance is reset to 0
- Verified when device date/time is set to Mar 12 11.59PM, keeping the browser active with a wallet balance is reset to 0 without having to restart the browser

![image](https://user-images.githubusercontent.com/17010094/110764729-50853f80-824b-11eb-9ce6-211cc8c24dad.png) | ![image](https://user-images.githubusercontent.com/17010094/110764755-58dd7a80-824b-11eb-8698-fe3530f1b0e5.png)
-- | --

</details>

<details>
<summary><b>Case 2 - non-Japan region</b></summary>

- Verified able to claim promotions
- Verified no BAP modal is shown
- Verified moving date ahead doesn't show any BAP modal
- Verified moving date to March 13 doesn't reset wallet balance to 0 but instead retains the grant balance

![image](https://user-images.githubusercontent.com/17010094/110765005-9e9a4300-824b-11eb-85ee-fec0eba7c446.png) | ![image](https://user-images.githubusercontent.com/17010094/110764962-93dfae00-824b-11eb-9164-9b01d0aa688f.png)
-- | --

</details>

------------
Verification passed on OnePlus 6T with Android 10 running 1.21.76 x64 build
- Verified BAP notice is shown daily 

<details>
<summary><b>Case 1 - Japan region</b></summary>

- Verified setting device locale to JP shows and clean install(1.21.74) with 0 BAP balance doesn't show any BAP deprecation modal
- Verified able to claim grant and wallet balance updates
- Verified upgrading to 1.21.76 shows BAP deprecation notice if the wallet already had a balance in 1.21.74(GPS build)
- Verified modal shows up again when the device date is moved ahead by 1 day
- Verified clicking only on OK closes the BAP info modal and not tapping outside the modal
- Verified moving device date to 13 Mar doesn't show BAP alert and wallet balance is reset to 0
- Verified when device date/time is set to Mar 12 11.59PM, keeping the browser active with a wallet balance is reset to 0 without having to restart the browser
 
![image](https://user-images.githubusercontent.com/17010094/110765789-7101c980-824c-11eb-811d-b11c579e8232.png) | ![image](https://user-images.githubusercontent.com/17010094/110765860-81b23f80-824c-11eb-8806-0168e0a0f541.png)
-- | --

</details>

<details>
<summary><b>Case 2 - non-Japan region</b></summary>

- Verified able to claim promotions
- Verified no BAP modal is shown
- Verified moving date ahead doesn't show any BAP modal
- Verified moving date to March 13 doesn't reset wallet balance to 0 but instead retains the grant balance

![image](https://user-images.githubusercontent.com/17010094/110765978-9b538700-824c-11eb-8fa0-ee1a56a6301f.png) | ![image](https://user-images.githubusercontent.com/17010094/110765922-90005b80-824c-11eb-9ccb-7900965c2ad9.png)
-- | --

</details>
