### ISSUE TITLE
Update text colour on onboarding to not make it look like a hyperlink

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13800]
## Description 
Update text colour on onboarding to not make it look like a hyperlink

## Steps to reproduce 

   1. Go through RE onboarding by opting in
   2. Go to the slide that allows to set monthly budget
   3. `You can change this later.` message looks like an hyperlink but isn't

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/106030278-edd64b00-60c5-11eb-93e8-6d4afd5baa07.png)

## Expected result
Just text shouldn't look like a hyperlink

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.20.89

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by codybanxs** [comment]
Here is the updated string color for the text! 
<img width="378" alt="Screen Shot 2021-01-27 at 10 15 19 AM" src="https://user-images.githubusercontent.com/61210652/106036711-86e77080-608a-11eb-9d84-54ff94b75e60.png">

**Comment by deeppandya** [comment]
@codybanxs can you add cheanges for https://bravesoftware.slack.com/archives/C0816QH3R/p1611576288027100 and https://bravesoftware.slack.com/archives/C0816QH3R/p1611572924020300 as well ?

**Comment by kjozwiak** [comment]
> @codybanxs can you add cheanges for https://bravesoftware.slack.com/archives/C0816QH3R/p1611576288027100 and https://bravesoftware.slack.com/archives/C0816QH3R/p1611572924020300 as well ?

Adding screens for context for QA/others looking at this issue. This should also fix a few translation alignment issues as well. Screens @srirambv 👍 

**`Example`** | **`Example`**
---------------|---------------
![Screenshot_20210125-115947](https://user-images.githubusercontent.com/2602313/106645129-f2818000-6559-11eb-8fc7-9ee3a22dec2d.jpg) | ![Screenshot_20210125-120018](https://user-images.githubusercontent.com/2602313/106645136-f57c7080-6559-11eb-8515-b9da7e331be5.jpg)

**Comment by codybanxs** [comment]
I spoke with @deeppandya and this color change will be reflected in 1.21 as it was missed for 1.20. This is not a blocking issue so we can keep going and I will bring this up again when 1.21 arrives. cc: @kjozwiak

**Comment by kjozwiak** [comment]
Adding `release-notes/include` as this is an issue on release which is being fixed so it's user facing.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.19.90 x64 build
- Verified text colour doesn't look like a hyperlink
- Encountered #13911

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/106745120-929dde80-6618-11eb-89a6-addb3e32b7a7.png> | <img width=405 src=https://user-images.githubusercontent.com/17010094/106745087-8ade3a00-6618-11eb-8e25-e539f1f833ed.png>

**Comment by kjozwiak** [comment]
Currently happening in `1.19.88 CR: 88.0.4324.96` so adding `release-notes/include` as the issue was already user facing.
