### ISSUE TITLE
Porn Hub Video problems... Beta, Dev, Nightly

### ISSUE THREAD

**Issue by MrWaste** [brave/brave-browser#13805]
## Description 

I used Tor with the Beta Brave.

## Steps to Reproduce

   1.  Tor
   2.  Pornhub.com
   3. Any Video

## Actual result:

![](https://user-images.githubusercontent.com/49108816/104769972-f8d3c780-5724-11eb-9032-e204ad8f9c58.png)

![](https://user-images.githubusercontent.com/49108816/105467402-82662680-5c4a-11eb-9148-a050da1f2d6b.png)

## Reproduces how often: 

Every time

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel? YES
- Can you reproduce this issue with the nightly channel? YES

1. On the sheild turn on aggressive for the block list.
2. Go to pornhub.com
3. Videos don't load.

**Comment by MrWaste** [comment]
I tried Linux with Beta, Dev, Nightly. It doesn't seem to have problem. Its only on windows 10.

**Comment by ryanbr** [comment]
Tested this (from NZ), no VPN. and visiting `pornhub.com` via Tor, worked fine here. Can you re-test with/without a VPN (if being used) @MrWaste

**Comment by binocry** [comment]
I tested using private tab with tor no problem, latest stable Version 1.19.88

**Comment by MrWaste** [comment]
1. On the sheild turn on aggressive for the block list.
2. Go to pornhub.com
3. Videos don't load.

**Comment by ryanbr** [comment]
(Images Heavily Obfuscated ) Tested in Brave Beta, shields=Aggressive. Video's played fine:

https://secure.fanboy.co.nz/gif/pornhub-tor2.gif

**Comment by MrWaste** [comment]
Brave has fixed it, not sure when.
