### ISSUE TITLE
Feature Request: Ad Blocking via Element Picker (like uBlock Origin)

### ISSUE THREAD

**Issue by 8227846265** [brave/brave-browser#13808]
## Description 
Please include a feature to improve the ad blocking by providing an element picker similar to [uBlock Origin](https://github.com/gorhill/uBlock/wiki/Element-picker)

The current setup of "**Right Click > Brave > Block Element via Selector**" is not very user-friendly when you want to block persistent ads or basically wants to block something from appearing again once you revisit a website. The element picker like uBlock Origin can provide a preview of what is going to be blocked. On Brave Browser, blocking via selector is always going blind wherein you can only see what is blocked after the fact.

If ever that you want to revert a single block you have made. You have to CLEAR ALL CSS Rules, what if the user has made several CSS rules blocking?

Additionally, the clear rules options are **TOO CLOSE** to the Block Element via Selector so one **MISCLICK** can **DELETE** all block elements that a user already created either from the site or everything!

It would be better to include to a UI where users can check their user-created filters.

**Comment by antonok-edm** [comment]
@8227846265 https://github.com/brave/brave-core/pull/8156 will be released in 1.23.x (currently in Beta), which puts all the rules added this way into the brave://adblock page and removes the `Clear CSS Rule` options entirely. I think that addresses all of your secondary concerns here, at least.

I'll leave this issue open to track the element picker feature, which definitely still needs some attention :smile:

**Comment by MrWaste** [comment]
Thank you for adding this, saves me time!
