### ISSUE TITLE
Fix race condition in Brave Rewards panel that results in inconsistent UI ("Your wallet" vs verify wallet)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#13801]
## Description 

In the Brave Rewards dropdown panel, sometimes the panel will display "Your wallet" text, and sometimes it will display "Verify wallet" (or "Wallet verified"). It is inconsistent, and according to some investigation, is due to a race condition in the code. 

In no case should it show the "Your wallet" text. The panel should always show "Verify wallet" (or "Verified wallet" if the user is already verified). The "Your wallet" text should be removed, and the race condition should be fixed.

**Your wallet** case (incorrect):
![image](https://user-images.githubusercontent.com/11497541/106038733-4b5a9f80-60a6-11eb-971c-bcbedc48e41f.png)

**Verify wallet** case (correct):
![image](https://user-images.githubusercontent.com/11497541/106038766-57466180-60a6-11eb-868e-dabf78023c1b.png)

## Steps to Reproduce

1. Open the Brave Rewards panel
2. Observe that sometimes it shows one or the other

## Reproduces how often: 

Depends on race condition. 

## Version

Happens as late as v1.19.

**Comment by emerick** [comment]
@Miyayes It seems that `Your wallet` is meant to be shown when users only have access to an anonymous wallet, which is determined by country code and is currently limited to Japan:

```
const std::vector<std::string> kOnlyAnonWalletCountries = {
  "JP"  // ID: 19024
};
```

So I'm assuming we would still want to allow for this condition (but of course get rid of the race condition)? Let me know either way.

**Comment by emerick** [comment]
The onboarding modal is also not displayed when this occurs.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.23.25 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 10.15.7 (Build 19H524)
```

Verified test plan from https://github.com/brave/brave-core/pull/8113.
Verified STR from description.
Tried test plan steps ~15x to reproduce the issue using `1.21.74` and was unable to reproduce.
Tried test plan steps ~15x on 1.23.x and did not see the race condition.
