### ISSUE TITLE
Stop adding sponsored features

### ISSUE THREAD

**Issue by misolori** [brave/brave-browser#13807]
![image](https://user-images.githubusercontent.com/35271042/106096680-de1d2d80-60ea-11eb-8de3-779deaee2f35.png)

Why is it that every few months a new "sponsored" feature appears? Did anyone ask for this? This feels like you are pushing your users away and is the anti-thesis of what Brave stands for. I'm getting tired of having to dodge these features and will end up leaving the app.

**Comment by bradleyrichter** [comment]
@misolori Sorry you are finding some of these new features frustrating. We welcome any feedback you have that can help us steer the product in the best direction possible.

We have been working on various new additions that help us monetize the product and thus helps us continue to build it. We stand by our promise to protect user privacy as our #1 feature. Our recent changes to Brave Rewards on iOS are funneling more ad revenue share to creators. Sponsored image revenue on Android and Desktop is shared with users who choose to opt in to Brave Rewards.

We will always make it possible to hide or remove these optional features and retain your preferences through continuous updates. 

Please do let us know what else we can do to improve your experience.

**Comment by rebron** [comment]
Hi @misolori. You can turn off sponsored images by selecting Customize and toggling the switch. We also introduced sponsored images via a dialog where users can turn off the feature, but we understand those maybe overlooked. 

<img width="724" alt="Screen Shot 2021-01-27 at 10 32 08 PM" src="https://user-images.githubusercontent.com/5951041/106099600-c8f6cd80-60ef-11eb-803a-8225a6f06e46.png">
