### ISSUE TITLE
Browser crash when trying to toggle Home button with bottom bar disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13809]
## Description 
Browser crash when trying to toggle Home button with bottom bar disabled

## Steps to reproduce 

   1. Install playstore build
   2. Disable bottom toolbar, relaunch home button is missing
   3. Toggle Home button from settings, browser crash

## Actual result 

https://user-images.githubusercontent.com/17010094/106099150-1f84fb80-6132-11eb-9799-c4bc45206a47.mp4

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.19.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
cc: @samartnik @SergeyZhukovsky

**Comment by kjozwiak** [comment]
Nice find @srirambv 👍

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.19.90 x64 build
- Verified no browser crash when bottom toolbar is disabled
- Verified no option for home button under controls is shown when bottom toolbar is disabled
  <img width=300 src=https://user-images.githubusercontent.com/17010094/106743985-017a3800-6617-11eb-8728-3c0c13abbc17.png>
