### ISSUE TITLE
Spelling mistake.

### ISSUE THREAD

**Issue by aquiso** [brave/brave-browser#13814]
**Description of the issue:**
In Lithuanian language, when you open "Naujas privatus langas su Tor", you get a Tor window, but there is a spelling mistake: "Privatusd". It shoud be : "Privatus"

<strong>Steps to Reproduce (add as many as necessary):
1.</strong> Launch Brave
<strong>2.</strong> Set Lithuanian language, to see error.
<strong>3.</strong> Open "Naujas privatus langas su Tor" 

<strong>Actual Result (gifs and screenshots are welcome!):</strong>
[image|552x266](upload://2FT3zVqTaTab2xZSndfma6NaljZ.png)  Instead of "Privatus" you get "Privatusd"

**Expected ** <strong>Result:</strong>"Privatus"

<strong>Reproduces how often:</strong>
Always

<strong>Brave Version(See the About Brave page in the main menu):</strong>
Brave release - v1.19.86

<strong>Reproducible on current live release (yes/no):</strong>
Yes

**Additional information:**
I'm using Windows 10.

**Comment by diedp1rat3** [comment]
Screenshot : 
![image](https://user-images.githubusercontent.com/59450620/106141843-65b17d80-6179-11eb-9d77-16da5fe3446d.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.26.67 Chromium: 91.0.4472.114 (Oficialiai pagaminta) (64 bitų)
-- | --
Peržiūrėtas ir pataisytas leidimas | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

```
- Verified the STR from the description and ensured "Privatus" is shown in Private with Tor window and hamburger menu
![image](https://user-images.githubusercontent.com/38657976/122898804-cfb90200-d368-11eb-9811-790824b6f343.png)
![image](https://user-images.githubusercontent.com/38657976/122898866-e0697800-d368-11eb-9558-7dd518c014dc.png)
