### ISSUE TITLE
[hackerone] Tor Onion-Location issue

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#13828]
https://hackerone.com/reports/1089995

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.20.97 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/7747

**Open in Tor (Header is invalid)**
![image](https://user-images.githubusercontent.com/34715963/106611307-1c41a380-6568-11eb-9119-a66a89f77d1c.png)

**Automatically Tor redirect (Header is invalid)**
![image](https://user-images.githubusercontent.com/34715963/106611551-67f44d00-6568-11eb-8d80-3f2a18d73747.png)
![image](https://user-images.githubusercontent.com/34715963/106611623-7cd0e080-6568-11eb-9dae-03ffb63895bb.png)

**Open in Tor (HTTP host)**
![image](https://user-images.githubusercontent.com/34715963/106611718-95d99180-6568-11eb-8f35-204b514716f9.png)

**Automatically Tor redirect (HTTP host)**
![image](https://user-images.githubusercontent.com/34715963/106611843-b86baa80-6568-11eb-97c2-9d594f282896.png)
![image](https://user-images.githubusercontent.com/34715963/106611917-cd483e00-6568-11eb-8bce-24e985ef56d8.png)
