### ISSUE TITLE
pressing on "Private" crashes brave while using private tabs when "#enable-new-profile-picker" has been enabled

### ISSUE THREAD

**Issue by LUC18fknU7P** [brave/brave-browser#13822]
## Description 

pressing the button described in the image below crashes brave and causes all tabs to close instantly
![image](https://user-images.githubusercontent.com/31454692/106202453-a5508780-61c2-11eb-8b3d-fc5ee0b9b81e.png)

## Steps to Reproduce

   1. Open private tab
   2. Press the "Private" button
   3. The browser should crash.

## Actual result:

N/A

## Expected result:
Browser resumes operation as expected

## Reproduces how often: 

Every time the button is pressed

## Brave version (brave://version info)

Name | Value
-- | --
Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Presumably not.

## Miscellaneous Information:

`#enable-profiles-ui-revamp` is enabled on **brave://flags**

**Comment by bridiver** [comment]
I can't repro on current release or nightly, can you try updating?

**Comment by tero-dev** [comment]
> I can't repro on current release or nightly, can you try updating?

Did you enable `#enable-profiles-ui-revamp`? others are also crashing with it enabled

**Comment by wsor4035** [comment]
also crashes when `#enable-new-profile-picker` is enabled, https://github.com/brave/brave-browser/issues/13102#issuecomment-769538909

**Comment by kjozwiak** [comment]
As per the above, you'll need to enable `#enable-profiles-ui-revamp` via `brave://flags`. STR:

* launch brave and enable `#enable-profiles-ui-revamp` via `brave://flags` (restart)
* open a new private tab and click on the `Private` tab profile picker

You'll get the following crash:

```
[ 00 ] ui::ThemedVectorIcon::GetImageSkia(ui::NativeTheme const *)
[ 01 ] views::View::GetNativeTheme()
[ 02 ] views::ThemedVectorIconBackground::Paint(gfx::Canvas *,views::View *)
[ 03 ] views::View::OnPaintBackground(gfx::Canvas *)
[ 04 ] SkCanvas::clipRect(SkRect const &,SkClipOp,bool)
[ 05 ] SkNoDrawCanvas::SkNoDrawCanvas(int,int)
[ 06 ] views::View::OnPaint(gfx::Canvas *)
[ 07 ] ui::PaintRecorder::PaintRecorder(ui::PaintContext const &,gfx::Size const &,float,float,ui::PaintCache *)
[ 08 ] views::View::Paint(views::PaintInfo const &)
[ 09 ] RtlFreeHeap
[ 10 ] 0x5400000120
[ 11 ] RtlUnwindEx
[ 12 ] RtlUnwindEx
```

**Comment by tero-dev** [comment]
I've recently also crashed by pressing "Allow" on consent popups e.g. push notifications

**Comment by mariospr** [comment]
I just managed to reproduce this by enabling `#enable-new-profile-picker` on a built-from-sources Brave off the `master` branch, but can't get the crash anymore on the `cr92` branch, could this have been fixed upstream?
