### ISSUE TITLE
Fingerprinting protection does not work in tor-mode 

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1382]
STR:
1. Navigate to `https://browserleaks.com/canvas` in tor mode
2. Switch to `Block All Fingerpriting` in Fingerprinting protection
2. Reload and canvas fingerprinting still works

Version:
`0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)`

**Comment by yrliou** [comment]
Same cause as https://github.com/brave/brave-browser/issues/1381, closing this one.
