### ISSUE TITLE
Feature request: Enbale tab bar (tablet mode) independently of display DPI

### ISSUE THREAD

**Issue by IndubitablyLeft** [brave/brave-browser#13821]
Currently the only way to enable the tab bar found on tablets and desktop browsers is to alter the global DPI settings to fool the app into believeing it is running on a tablet, which has the unfortunate side effect of also altering every other app.

**Comment by rebron** [comment]
@IndubitablyLeft I invite you to visit https://community.brave.com/c/brave-feature-requests/57 for future feature requests.
