### ISSUE TITLE
Treat .onion addresses as a secure context for JS cryptography

### ISSUE THREAD

**Issue by ProofOfKeags** [brave/brave-browser#13834]
Right now, when doing http to a .onion address the browser crypto API's won't work due to not believing it is a secure context. However onion url's are self authenticating and end to end encrypted meaning that this should not be the case.

**Comment by fullmetalengineer** [comment]
This would be great to have fixed, it's impairing my ability to use some software in Brave that I have to go to the Tor browser for. I'd rather just use Brave if possible.

**Comment by rebron** [comment]
cc: @darkdh Can you take a look?

**Comment by jaredduggan** [comment]
I would really appreciate this update!

**Comment by diracdeltas** [comment]
we should treat it as a secure context in general (according to the w3c definition) if we do this

**Comment by jaredduggan** [comment]
Thanks for following back up. Would love to see this change implemented!

**Comment by ProofOfKeags** [comment]
Checking in on this. Does the Brave team have an estimate on when this can get implemented? I imagine it is a rather small change that needs to be made.

**Comment by ProofOfKeags** [comment]
I see the tag here is a "good first issue". What is the high level approach that needs to be taken in order to get this in. Where is this check currently implemented in the codebase?

**Comment by kejsitake** [comment]
Hi! Is this the same as #1135 that @riastradh-brave worked on? Is the brave-core patch a fix to both?  I would be happy to pick it up, but I am unsure about the current status of any blockers?

**Comment by ProofOfKeags** [comment]
I can't comment about the equivalence of brave/brave-core#2421 but a fix to #1135 is almost certainly going to fix this issue implicitly and would satisfy the original request.

**Comment by fmarier** [comment]
As @ProofOfKeags has pointed out, #1135 will fix this. I don't see a reason to special-case JS crypto. We should treat `.onion` as a secure context [like Tor Browser](https://searchfox.org/mozilla-central/search?q=.onion&case=true&path=).
