### ISSUE TITLE
Add additional padding to new tab "+" button

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#13835]
## Description 
Tabs, specifically the close button, and the "new tab" button are close together and could use additional padding/separation to improve closing a tab or selecting a new tab by mistake. 

Other browsers like Chrome and Yandex have slightly bigger padding and separation between buttons.

## Steps to Reproduce and Actual Result:
Noticeable with a new window and notice spacing between a tab's close button and the new tab icon.

![image__2_](https://user-images.githubusercontent.com/5951041/106305264-50882d80-6211-11eb-93ca-71d932ae6020.png)

## Expected result:
[placeholder for design] @karenkliu 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a 
- Is the issue reproducible on the latest version of Chrome? no

**Comment by bsclifton** [comment]
Added missing milestone

**Comment by stephendonner** [comment]
Verified using inline testplan on 

Brave | 1.21.44 Chromium: 88.0.4324.146 (Official Build) beta (x86_64)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | macOS Version 11.2 (Build 20D64)

In addition to the increased horizontal margin padding between `tab-close (X)` and `open new tab (+)`, I checked:
* hover states
* click states

|  `1.19.92`  |  `1.21.44`  |
|----------- |----------- |
|  ![image](https://user-images.githubusercontent.com/387249/107280346-1850ce00-6a0d-11eb-866c-17f5d4e8cc6e.png) | ![image](https://user-images.githubusercontent.com/387249/107279529-01f64280-6a0c-11eb-8d20-37ecd6e29f92.png)
