### ISSUE TITLE
Style private windows with Tor purple like regular private windows

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1383]
## Test plan
See https://github.com/brave/brave-core/pull/546

## Description
Right now, windows with Tor have default Chrome. Instead, they should use the same purple styling as regular private windows.

**Comment by bbondy** [comment]
@petemill browser_->profile()->IsTorProfile()

**Comment by petemill** [comment]
Test plan on PR https://github.com/brave/brave-core/pull/546

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/46744797-2b6ff980-ccac-11e8-8521-f95599cc6222.png)
