### ISSUE TITLE
List PeerID and AgentVersion in brave://ipfs

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13839]
Per Lidel, it would be useful to list the PeerID and AgentVersion from the API.
https://docs.ipfs.io/reference/http/api/#api-v0-id

PeerID is ID from there

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.21.50 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2.1 (Build 20D74)

Steps:

1. Installed `IPFS Companion` (https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch)
2. Clicked "Enable IPFS" as instructed by the extension
3. Loaded `brave://ipfs`
4. Verified that both `PeerID` and `Version` were present, with sane values, under "Node info"

<img width="906" alt="Screen Shot 2021-02-10 at 4 30 56 PM" src="https://user-images.githubusercontent.com/387249/107590662-89cf7e80-6bbd-11eb-9a35-84aac15123a6.png">
