### ISSUE TITLE
Feature - Remake the download bar layout

### ISSUE THREAD

**Issue by dave90dave** [brave/brave-browser#13848]
## Description 

When you download a file from the internet, the download bar pops up (at the bottom of the screen).
This is a bit outdated and lacking features.

## Steps to Reproduce

   1. Download a file from the internet
   2. The download bar shows up
   3. Open the context menu of the file you just downloaded.

## Actual result:

![image](https://user-images.githubusercontent.com/7985017/106355273-21e48280-62f7-11eb-9496-3096aa546df8.png)

It shows the download bar.
You can't manage your downloaded files that easy.

## Expected result:
Add the following functions in the context menu:
- Move a download file to the trash bin.
- Copy the download link (where you downloaded the file from).
- Move the file to another destination.
- Rename the filename

And please hide the Cancel button, when the file already finished downloading.

## Brave version (info found on brave://version)

1.19.88

**Comment by srirambv** [comment]
Closing in favour of #1638
