### ISSUE TITLE
Brave crash on Nightly version

### ISSUE THREAD

**Issue by Applewubs** [brave/brave-browser#13844]
## Description 
Crash on startup once, and will keep doing it, looked for crash on debug. Already updated browser and it keeps crashing.

## Steps to Reproduce

   1. Open Browser 
   2. Crash

## Actual result:
Crash without doing a thing

## Expected result:
Open and see lobby

## Reproduces how often: 
Everytime.

## Brave version (brave://version info)
1.21.35 Chromium: 88.0.4324.96 (Build oficial) nightly (64 bits)

## Version/Channel Information:
Nightly

## Other Additional Information:

-CAN'T DO ANYTHING

## Miscellaneous Information:
Debug: [0925/024259.403:ERROR:settings.cc(326)] Settings version is not 1

**Comment by Furax-31** [comment]
Same problem, impossible to launch, crash after 3 seconds.

**Comment by DarioArzaba** [comment]
In Windows OS and with version 88.1.21.35

**Comment by Zmoi6** [comment]
Same problem.

Thanks for your fix DarioArzaba. It worked well for me.

**Comment by dissentience** [comment]
same problem. fix above did not work for me.

**Comment by Applewubs** [comment]
Alright, i tried deleting one by one the files DarioArzaba told, and by deleting the file "LocalState" it stopped crashing, but if i restore the file it will crash again, dunno what's that file but it gives problems like no tomorrow. Thanks for the help DarioArzaba!

> In Windows OS and with version 88.1.21.35.
> 
> Edit: I temporarily fixed it by deleting Last Browser, Local State and Last Version files from C:\Users\USER\AppData\Local\BraveSoftware\Brave-Browser-Nightly\User Data and History, Cookies and Bookmarks files from C:\Users\USER\AppData\Local\BraveSoftware\Brave-Browser-Nightly\User Data\Default
> 
> Edit 2: Restored the files I deleted and the browser stopped crashing without any info loss.

**Comment by Applewubs** [comment]
##Update
I can't really move the settings, i tried abandoning the sync chain or moving data there and it keeps restarting to the config i had before, any other options works fine, i think maybe something's happening there?

**Comment by lxwulf** [comment]
> In Windows OS and with version 88.1.21.35.
> 
> Edit: I temporarily fixed it by deleting Last Browser, Local State and Last Version files from C:\Users\USER\AppData\Local\BraveSoftware\Brave-Browser-Nightly\User Data and History, Cookies and Bookmarks files from C:\Users\USER\AppData\Local\BraveSoftware\Brave-Browser-Nightly\User Data\Default
> 
> Edit 2: Restored the files I deleted and the browser stopped crashing without any info loss.

Yeah, that works but on my installation it stills crash after a longer time maybe after 10min. It repeats I can start it again and then after a while it crashes again...

**Comment by kjozwiak** [comment]
Thanks for the report. I created https://github.com/brave/brave-browser/issues/13858 which has a bit more info and a workaround for now. I'll close this as a duplicate but please feel free to share more information via https://github.com/brave/brave-browser/issues/13858 👍 We'll try getting this fixed ASAP.

Workaround for now is to launch Nightly via the terminal/command line using the following:

```
brave.exe --brave-stats-updater-server="https://laptop-updates.brave.com"
```
