### ISSUE TITLE
"Tor" label on private windows with Tor

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1384]
Instead of the people menu or the incognito hat-and-glasses, Tor windows should have the same simple "Tor" label as Muon tabs with Tor.

**Comment by bbondy** [comment]
Could you take a screenshot of what you mean?

**Comment by petemill** [comment]
Test plan on PR https://github.com/brave/brave-core/pull/547

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/46744094-b4863100-ccaa-11e8-8c23-603056794727.png)
