### ISSUE TITLE
Feature - Add a opt-out checkbox on the welcome tour, to disable private product analysis

### ISSUE THREAD

**Issue by dave90dave** [brave/brave-browser#13845]
## Steps to Reproduce

   1. Open Brave after a fresh installation
   2. Go trough the welcome tour. (go to the tab about private product analysis)
   3. Replace the text about private product analysis, with a visible opt-out checkbox.

## Actual result:
It shows information how to disable private product analysis

## Expected result:
It should show a opt-out checkbox, to directly be able to change the private product analysis setting, without having to open settings.

## Brave version (info found on brave://version)

1.19.88 and above

**Comment by rebron** [comment]
cc: @karenkliu dupe?

**Comment by karenkliu** [comment]
@rebron Not a dupe, but changes to P3A opt-in  are being decided at Tuesday's meeting. We should close this for now.

**Comment by karenkliu** [comment]
This should have been fixed with https://github.com/brave/brave-browser/issues/14183# - the P3A checkbox is now the very first thing a user sees before even using the browser.
