### ISSUE TITLE
Brave Nightly opening and closing instantly after.

### ISSUE THREAD

**Issue by skygamer125** [brave/brave-browser#13842]
## Description 

Brave was working just fine, did the new update, it was working still, and then stopped out of nowhere, not letting me open it again...

## Steps to Reproduce

   1. open brave nightly
   2. waiting 1 sec
   3. seeing it close again

## Expected result:
https://prnt.sc/xu87m6 opens, closes. sometimes loads fully, sometimes doesnt, but always closes after 1 second or 2

## Reproduces how often: 

all times, doesnt stay open 

## Brave version (brave://version info)

https://prnt.sc/xu84d1

## Version/Channel Information:

- Can you reproduce this issue with the current release?  no
- Can you reproduce this issue with the beta channel?  no
- Can you reproduce this issue with the nightly channel?  yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  no
- Does the issue resolve itself when disabling Brave Rewards?  no
- Is the issue reproducible on the latest version of Chrome?  no

**Comment by gruber123** [comment]
Same issue since Nightly v1.21.35 2 or 3 versions backward, It closes immediately without showing window, or closes after some very little time (seconds), check also with clean user data

**Comment by AndreasReschGFX** [comment]
Same here. This morning Brave Nightly opens and immediately closes again. Windows 10 64-Bit.

**Comment by roeizavida** [comment]
Same here. Reinstalling an older release of Brave Nightly isn't working as well.

**Comment by kjozwiak** [comment]
Thanks for the report. I created https://github.com/brave/brave-browser/issues/13858 which has a bit more info and a workaround for now. I'll close this as a duplicate but please feel free to share more information via https://github.com/brave/brave-browser/issues/13858 👍 We'll try getting this fixed ASAP.

Workaround for now is to launch Nightly via the terminal/command line using the following:

```
brave.exe --brave-stats-updater-server="https://laptop-updates.brave.com"
```
