### ISSUE TITLE
nightly crashing due to "brave_stats::BraveStatsUpdater::BuildStatsEndpoint"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13858]
## Description 

Nightly is currently crashing every few seconds after startup or after a few minutes. I have a brand new profile that crashes every ~5min but I also have a profile that crashes every ~1-2 seconds after startup making it almost impossible to use.

We're also getting several reports from the community as per the following:

* https://github.com/brave/brave-browser/issues/13856
* https://github.com/brave/brave-browser/issues/13844
* https://github.com/brave/brave-browser/issues/13842

@bsclifton also ran into the above issue on his machine and reported the crash via `#crashes` in Slack.

Here's a quick preview of the Stack Full stack can be downloaded via the following:
* [crashStack.txt](https://github.com/brave/brave-browser/files/5899512/crashStack.txt)

```
[ 00 ] brave_stats::BraveStatsUpdater::BuildStatsEndpoint(std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> > const &)
[ 01 ] std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> >::basic_string<nullptr_t>
[ 02 ] brave_stats::BraveStatsUpdater::SendServerPing()
[ 03 ] std::__1::__tree<std::__1::__value_type<Profile::OTRProfileID,std::__1::unique_ptr<Profile,std::__1::default_delete<Profile> > >,std::__1::__map_value_compare<Profile::OTRProfileID,std::__1::__value_type<Profile::OTRProfileID,std::__1::unique_ptr<Profile,std::__1::default_delete<Profile> > >,std::__1::less<Profile::OTRPro
```

Crash ID's from @kjozwiak:

* 4d2a0000-9cc8-c705-0000-000000000000
* 4c2a0000-9cc8-c705-0000-000000000000
* 4a2a0000-9cc8-c705-0000-000000000000
* 102a0000-9cc8-c705-0000-000000000000

Crash ID's from @bsclifton:

* a01f0000-9cc8-c705-0000-000000000000
* a51f0000-9cc8-c705-0000-000000000000
* a61f0000-9cc8-c705-0000-000000000000
* a71f0000-9cc8-c705-0000-000000000000
* a81f0000-9cc8-c705-0000-000000000000
* a91f0000-9cc8-c705-0000-000000000000

## Steps to Reproduce

   1. launch `1.21.35 CR: 88.0.4324.96`
   2. login into a few websites (GH/Gmail in my case) and wait ~10min or so
   3. eventually Nightly will crash

I have a profile saved that basically crashes after startup as well so it makes it impossible to use Brave on Nightly.

## Actual result:

Nightly crashing pretty often which makes it impossible to use

## Expected result:

Nightly shouldn't be crashing.

## Reproduces how often: 

So far I've managed to reproduce the crash on three different clean profiles after ~20min of usage.

## Brave version (brave://version info)

```
Brave | 1.21.35 Chromium: 88.0.4324.96 (Official Build) nightly (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2009 (Build 19042.746)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `I'm not 100% sure if this occurring on Release`
- Can you reproduce this issue with the beta channel? `I'm not 100% sure if this occurring on BETA`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @bsclifton @rebron @bbondy @aekeus @brave/legacy_qa @keur

**Comment by kjozwiak** [comment]
Workaround for now is to launch Nightly via the terminal/command line using the following:

```
brave.exe --brave-stats-updater-server="https://laptop-updates.brave.com"
```

**Comment by thinginyourmind** [comment]
There is no issue on release build (Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)), but nightly indeed crashes after 1-2 seconds, at least when using on windows 10. The workaround shown above works, indeed.

**Comment by gruber123** [comment]
I'm again updated to Nightly v1.21.35 from Nightly v1.21.31 and browser isn't crushing (I haven't used workaround through terminal yet). My system windows 7

**Comment by Bushido1** [comment]
> Workaround for now is to launch Nightly via the terminal/command line using the following:
> 
> ```
> brave.exe --brave-stats-updater-server="https://laptop-updates.brave.com"
> ```

How to launch Nightly via the terminal/command line?
Inserting "C:\Program Files\BraveSoftware\Brave-Browser-Nightly\Application\brave.exe -brave-stats-updater-server="https://laptop-updates.brave.com"" to the command line did not work as attached.

![image](https://user-images.githubusercontent.com/11409601/106384535-026f5780-63d4-11eb-8731-4b10b54c72da.png)

**Comment by kjozwiak** [comment]
@Bushido1 I would do the following:

* `cd "C:\Program Files\BraveSoftware\Brave-Browser-Nightly\Application\"`
* launch brave using `brave.exe --brave-stats-updater-server="https://laptop-updates.brave.com"`

**Comment by 141** [comment]
Tabs are crashing with a Status_Access_Violation error code on Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit).
Basically the say way, some tabs open, and eventually the tab you are on will crash.

**Comment by Jezkook** [comment]
@kjozwiak 

> "C:\Program Files\BraveSoftware\Brave-Browser-Nightly\Application\brave.exe" --brave-stats-updater-server="https://laptop-updates.brave.com"
> ```

This worked for me, thanks

**Comment by sujal05** [comment]
> Workaround for now is to launch Nightly via the terminal/command line using the following:
> 
> ```
> brave.exe --brave-stats-updater-server="https://laptop-updates.brave.com"
> ```

To get around this without using the command line or cmd, you can make a shortcut of nightly on desktop or anywhere you like and then open up the properties.

Change the target to the given workaround by @kjozwiak, it is a quite good and simple workaround for the case.

**Comment by kjozwiak** [comment]
We also released https://github.com/brave/brave-browser/releases/tag/v1.21.36 that had a quick fix as per https://github.com/brave/brave-core/pull/7753. That should have resolved the issue 👍 We're also working on a longer term solution as per https://github.com/brave/brave-core/pull/7754. We'll adjust our process so this doesn't happen.

**Comment by bsclifton** [comment]
Update to `QA/No` and removed test plan after code was updated to check in build rather than at runtime

**Comment by 141** [comment]
The latest Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (64-bit), seems to have fixed the tab crashing error for me. 
Version 1.19.88 was the only errored version it seems in the release versions.

**Comment by pein0saga** [comment]
Still has this issue in v1.48.75
