### ISSUE TITLE
Can't start or restart Brave Nightly

### ISSUE THREAD

**Issue by rednag** [brave/brave-browser#13856]
## Description 
In the morning I've wanted to start my Brave browser but it always quits after a few seconds.

## Steps to Reproduce
   1. Start Brave Nightly
   2. Quits automatically

## Expected result:
Brave starts.

## Brave version (info found on brave://version)
How can I check it, when it quits before I'm able to enter something in the address bar?

**Comment by Amos-999** [comment]
The same with you.

**Comment by kjozwiak** [comment]
Thanks for the report @rednag & @Amos-999. I created https://github.com/brave/brave-browser/issues/13858 which has a bit more info and a workaround for now. I'll close this as a duplicate but please feel free to share more information via https://github.com/brave/brave-browser/issues/13858 👍 We'll try getting this fixed ASAP.
