### ISSUE TITLE
Support you

### ISSUE THREAD

**Issue by Sky2883** [brave/brave-browser#13850]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Sky2883** [comment]
brave

**Comment by Sky2883** [comment]
Support  you

**Comment by kjozwiak** [comment]
If you're having issues or have a feature request, please make sure you provide some more information. Closing the above as it's basically empty.
