### ISSUE TITLE
Feature request: Option to have Download button instead of download toolbar

### ISSUE THREAD

**Issue by oxdead** [brave/brave-browser#13857]
It could be much more practical to have an option to show Download button at top right corner where extensions and options menu live, instead of showing whole Download Toolbar below.

So if someone likes toolbar they can have toolbar by default, but if someone, like me wants to have just small button instead of whole toolbar, they can go to options and switch option: "Show download button instead of download toolbar".

Download Toolbar is very big and everytime i download files, i click below to hide that toolbar.
Everytime i need to look for downloaded files after 5-60 minutes, i need to go through a loophole OptionsMenu->Downloads and then handle a downloaded file in separate tab. It's inconvenient, slow and annoying process.

It's much faster and more convenient just to click a button at the top right corner of browser, (right before Options menu button) and manage downloaded files in popped up tooltip. 

Benefits: 
-No need for big toolbars obstructing a site view
-No need for useless clicks to hide toolbar everytime you downloaded a file
-No need to go through menus and separate windows just to handle a downloaded file later.

I'm using currently:
Windows 10 x64 20H2
Brave: Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)

Thanks!

**Comment by srirambv** [comment]
Closing in favour of #1638

**Comment by NextDev65** [comment]
reopen please, this a separate issue
