### ISSUE TITLE
Brave with Tor crashes immediately after clicking on Address Bar

### ISSUE THREAD

**Issue by adrijeet** [brave/brave-browser#13868]
## Description 
Brave with Tor Crashes immediately after clicking on Address Bar

## Steps to Reproduce

   1. Open Brave Browser with Tor
   2. Click on Address Bar (Windows v20H2)
   3. Browser crashes

## Actual result:

Immediate crash on click on Address Bar on Brave with Tor without restarting. Have to manually restart Brave again.

## Expected result:
Tor should work without crashing.

## Version/Channel Information: Release channel only

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Did not try
- Can you reproduce this issue with the nightly channel? Did not try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by ceoadlw** [comment]
There are 13 of them. I am pasting the latest one only: ebfd7c3d-9480-4eb6-a9ed-1fc54eff7754. Please let me know if you would like me to upload the others too. All the crashes are due to the Brave with Tor address bar click only.

**Comment by rebron** [comment]
cc: @iefremov @darkdh When you guys get a chance can you take a look?

**Comment by iefremov** [comment]
many thanks @ceoadlw for reporting this

**Comment by iefremov** [comment]
internal link to our internal crash handler
https://brave.sp.backtrace.io/p/brave/debug?filters=((callstack%2Ccontains%2CTorWindowSearchEngineProviderService))&debug=(c2e1bb,0,0)

**Comment by iefremov** [comment]
Closing this in favor of https://github.com/brave/brave-browser/issues/15140
@adrijeet do you have any extensions installed? Any of them enabled for incognito windows?
