### ISSUE TITLE
unclear compile error in windows

### ISSUE THREAD

**Issue by beppe9000** [brave/brave-browser#13861]
## Description 
I tried following the docs but I am having an issue with compiling brave on windows (Server 2016)

## Steps to Reproduce

Not sure about this, I probably missed something.

After cloning I followed from [here](https://github.com/brave/brave-browser/wiki/Windows-Development-Environment) and made sure to be running `node`, `npm`, `yarn`, `python`. I also had previously installed both visual studio 2017 and visual studio 2019.

Then I proceeded to update the windows development kit to the recommended version.

I also prepared a separate volume (`B:\`) for brave repo's content in order to shorten path length (rather than clutter `C:\`)

Then i did the following to start the building

1. `npm install`
2. `npm run init`
3. `npm run build` -> fails

## Actual result:

It looks like it fails to erase a file's content.

![image](https://user-images.githubusercontent.com/6625123/106383084-157a2b80-63c4-11eb-9305-5c21b8729958.png)

- [📄 2021-01-31T02_34_40_808Z-debug.log](https://github.com/brave/brave-browser/files/5899994/2021-01-31T02_34_40_808Z-debug.log)
- [📄 2021-01-31T02_34_40_748Z-debug.log](https://github.com/brave/brave-browser/files/5899995/2021-01-31T02_34_40_748Z-debug.log)

## Expected result:
`Compiled successfully ?`

**Comment by bsclifton** [comment]
Sorry for the massive amount of time it's taken to respond ☹️ But looking at the above and at the logs, I don't see enough information to troubleshoot unfortunately. You shared you did check https://github.com/brave/brave-browser/wiki/Windows-Development-Environment and ensure you have pre-requisites setup which is great

I would retry and then it would be useful to see all of the output from the console. The logs from npm (which were attached) don't have the full build history. If I was on the terminal, I would want to scroll up to see what the prior lines were basically
