### ISSUE TITLE
blacklist Chromium PDF Viewer

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1386]
## Description 
Per https://github.com/brave/brave-browser/issues/1375#issuecomment-426088648 Chromium PDF Viewer should be blacklisted.

## Steps to Reproduce

   1. Remove any profile data.
   2. Launch beta version with`/Applications/Brave\ Browser\ Beta.app/Contents/MacOS/Brave\ Browser\ Beta --show-component-extension-options`
   3. Navigate to chrome://extensions

## Actual result:
Chromium PDF Viewer is displayed
![screen shot 2018-10-01 at 5 47 41 pm](https://user-images.githubusercontent.com/28145373/46321641-83bf4100-c5b2-11e8-985d-c482b5857896.png)

## Expected result:
Chromium PDF Viewer should not be used

## Reproduces how often: 
easily

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? n/a
- Does it reproduce on browser-laptop? n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
https://github.com/brave/brave-browser/issues/1375
https://github.com/brave/brave-browser/issues/1376

**Comment by bbondy** [comment]
Note when QA'ing this, it will show in the list but you can't turn it on. It will be blacklisted / turned off.

**Comment by kjozwiak** [comment]
Thanks for the quick fix @bbondy 👍

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

* per https://github.com/brave/brave-browser/issues/1386#issuecomment-426115090 verified that Chromium PDF Viewer is displayed in the list but is unable to be turned on
![screen shot 2018-10-08 at 2 37 54 pm](https://user-images.githubusercontent.com/28145373/46627276-ef039880-cb07-11e8-8bc9-e555d731b66d.png)
