### ISSUE TITLE
"Add to home screen" not working

### ISSUE THREAD

**Issue by leobel96** [brave/brave-browser#13860]
## Description 

When trying to install a website as PWA (web.dev for example) it doesn't work

## Steps to reproduce 

   1. Go to https://web.dev/
   2. Click "Add to home screen"
   3. Wait for the "Install" message

## Actual result 

The "install app" message appears ![install_app.png](https://user-images.githubusercontent.com/19806799/106382458-a8609900-63b7-11eb-815a-bbd6dc163471.png) and also the "adding web.dev ..." ![Screenshot_20210131-111304.png](https://user-images.githubusercontent.com/19806799/106382503-f2497f00-63b7-11eb-8e15-0e74349aa5b6.png) but nothing more: the app isn't added to the home screen.

## Expected result
The app is added to the home screen

## Issue reproduces how often 
It always happens

## Version/Channel Information:

Tested only with the stable channel

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Not tested
- Can you reproduce this issue with the current Play Store Nightly version? Not tested

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.19.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not tested

**Comment by srirambv** [comment]
Seems to work just fine. What device are you trying this on?

https://user-images.githubusercontent.com/17010094/106847370-ab54d580-66a6-11eb-834c-8ae5671e23d0.mp4

**Comment by leobel96** [comment]
A reboot solved the issue. I think I can close it now.

**Comment by srirambv** [comment]
Thanks for the update. Will close the issue
