### ISSUE TITLE
Don't receive any email notifications

### ISSUE THREAD

**Issue by hilmiwicak** [brave/brave-browser#13867]
I just started using brave for my main browser. But recently I got a notifications issue. I usually receives notifications from websites like web.whatsapp.com and web notification test (bennish.net). But when it comes to email services I don't receive any notifications. I've turned on email notifications on gmail and ymail, turned on the notification permission on mail.google.com, also turned on notifications for brave browser on windows notifications & actions settings, but I don't receive any notifications from neither of them.

Help me please. I really like brave and I'm not planning to change to other browsers.

**Comment by rebron** [comment]
hi @hilmiwicak. 
Can you take a look at your setting here -> brave://settings/content/notifications and see if Gmail and Ymail are added there?
cc: @Brave-Matt

**Comment by rebron** [comment]
hi @hilmiwicak Are you still not getting email notifications from Gmail or Ymail?

**Comment by hilmiwicak** [comment]
Sorry for the late reply.

> Can you take a look at your setting here -> brave://settings/content/notifications and see if Gmail and Ymail are added there?

Both Gmail and Ymail are there.
```
https://mail.google.com:443
https://mail.yahoo.com:443
```
Notification, Javascript, and Images are the only thing that are allowed on both of these sites. The rest are either block or ask.
