### ISSUE TITLE
missing question mark on one of the onboarding tour screens

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13876]
## Description 

On the onboarding tour slide titled "When do you receive rewards", there should be a question mark at the end of this title per https://github.com/brave/brave-browser/issues/13488#issuecomment-770003770. Note, this applies to both narrow (from panel) and wide (from brave://rewards) views as it is missing in both.

Per discussion with @codybanxs this question mark should be added.

## Steps to Reproduce

   1. Open either narrow or wide onboarding tour
   2. Go to the third slide/screen

## Actual result:

question mark at the end of the title is missing:
<img width="728" alt="wide3" src="https://user-images.githubusercontent.com/28145373/106516046-855fe300-64a4-11eb-8d48-e1ee133cab8a.png">

## Expected result:
Should read "When do you receive rewards?" per https://github.com/brave/brave-browser/issues/13488#issuecomment-770003770

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.20.95 Chromium: 88.0.4324.96 (Official Build) beta (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)

Brave | 1.21.36 Chromium: 88.0.4324.96 (Official Build) nightly (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H15)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a not available in 1.19.x
- Can you reproduce this issue with the beta channel? yes 1.20.x
- Can you reproduce this issue with the nightly channel? yes 1.21.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @codybanxs @brave/legacy_qa @rebron

**Comment by btlechowski** [comment]
Reproduced on

Brave | 1.20.97 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

In Polish locale.

![image](https://user-images.githubusercontent.com/34715963/106813308-1aafd280-6671-11eb-838e-78a0586c82d7.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.24.46 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 10.15.7 (Build 19H524)
```

Verified STR from description.

Narrow view | Wide view
----- | -----
<img width="1064" alt="Screen Shot 2021-04-05 at 8 58 27 AM" src="https://user-images.githubusercontent.com/28145373/113576277-40b00f80-95ed-11eb-9990-07830c53cd59.png"> | <img width="724" alt="Screen Shot 2021-04-05 at 8 58 43 AM" src="https://user-images.githubusercontent.com/28145373/113576280-4279d300-95ed-11eb-9d9c-e99aeaad3412.png">
