### ISSUE TITLE
Allow Brave to Handle Searches from Windows Shell and Cortana

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#13875]
## Description 
Even when Brave is the default browser, the user may still find themselves unintentionally using Microsoft Edge. This is because searches from the start menu and elsewhere in Windows open results in Microsoft Edge, rather than in the user's preferred browser.

## Steps to Reproduce
1. Set Brave as your default browser on Windows 10
2. Press the Windows Key
3. Type "brave deviations from chromium"
4. Press Enter

## Actual result:
Results are opened in Microsoft Edge.

## Expected result:
Results are opened in Brave (if Brave is the default browser).

## Reproduces how often: 
Always.

## Brave version (brave://version info)
1.19.88

## Miscellaneous Information:

Note: The "Command" portion is caused by Windows thinking "deviations from chromium" should be passed as arguments to the "brave" executable. As such, selecting that option opens 3 new tabs in Brave (i.e. `/deviations`, `/from`, `/chromium`), which is clearly not the intended result, and is wholly unrelated to this issue :)

![image](https://user-images.githubusercontent.com/815158/106510078-12e70700-6494-11eb-80cc-644370b8aeb8.png)

**Comment by jonathansampson** [comment]
From another thread, the https://github.com/da2x/EdgeDeflector has tackled this issue in the past. It registers itself as the handler for the `microsoft-edge:` protocol, and then passes the received URL to the shell for execution. The shell will then open it in whichever app is registered to handle HTTP/HTTPS.

**Comment by bsclifton** [comment]
This would be a great one to do- we'd need to make it an option (under `System` maybe?) in settings defaulted to false. When toggled, it could update the registry.  The hardest part would be the parsing of the `microsoft-edge:` if we didn't consider using an existing library (like EdgeDeflector)

**Comment by lukemulks** [comment]
+1 for this. 

Any time I click on a "Help" or "Help from web" link within the Windows OS, I'm navigated directly via Edge (even though Brave is set as my default browser). 

Interestingly enough, the navigation is to an `https` destination, which technically is the default protocol that Brave should be handling when Brave is set as the default browser. 

It also appears to be very difficult to manually change this within the OS, as the only applications Microsoft surfaces as available to set as the default for the edge-related protocols is Microsoft Edge, or an option to select another app from the Microsoft Store, which does not include Brave.

**Comment by simonhong** [comment]
When brave is set as a default app for `microsoft-edge` protocol via control panel ,
![image](https://user-images.githubusercontent.com/6786187/129667667-327bcd9c-d49b-4723-a178-1d026b70dc9f.png)

additional command line args are passed like below. Brave browser needs to fetch url and load it.
```
microsoft-edge:?launchContext1=Microsoft.Windows.Cortana_cw5n1h2txyewy&url=https%3A%2F%2Fwww.bing.com%2Fsearch%3Fq%3Dtest%26form%3DWNSGPH%26qs%3DSW%26cvid%3D935e77bf08484a92a230ddb119a8e594%26pq%3Dtest%26cc%3DKR%26setlang%3Den-US%26nclid%3D9896661371B25E91DFE2753D62351D4A%26ts%3D1629177294875%26nclidts%3D1629177294%26tsms%3D875%26wsso%3DModerate
```

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/9778 with build

Brave | 1.30.44 Chromium: 93.0.4577.51 (Official Build) nightly (64-bit)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | Windows 10 OS Version 2009 (Build 22000.160)

## Steps:

### Test 1 - from chrome uninstall process
1.  Set Brave as a default app for `microsoft-edge` protocol
2.  Install Chrome and then uninstall
3.  Check uninstall survey page is loaded in Brave

![chrome-uninstall](https://user-images.githubusercontent.com/387249/130679284-cf706244-7523-484c-b796-79fdc3b3d1c0.png)


### Test 2 - search from windows task bar

1.  Set Brave as a default app for `microsoft-edge` protocol
2.  Searched  from Windows taskbar.
3.  Check Bing search URL is loaded in brave
4.  Search another keyword from windows taskbar
5.  Check another tab is created and new tab loads Bing search URL

example | example | example
---------|----------|---------
![cortana-search](https://user-images.githubusercontent.com/387249/130679625-f48438e7-e492-48fa-922a-388b1947129b.png) | ![brave-default-search](https://user-images.githubusercontent.com/387249/130679618-29df58e4-3ac5-4c63-8238-edf4d54023b8.png) | ![brave-search](https://user-images.githubusercontent.com/387249/130679621-53c871d0-ebf7-497f-903a-c6808a2ff4e9.png)

### Test 3 - uninstall
1.  Set Brave as a default app for `microsoft-edge` protocol
2.  Uninstall Brave
3.  Search any keyword from Windows taskbar
4.  Check Windows asks users to set default app for `microsoft-edge` protocol again

example | example
---------|---------
![non-chrome-web-results-cortana](https://user-images.githubusercontent.com/387249/130679912-302f6209-f3ce-441c-be51-7b9cff87399e.png) | ![ms-edge-file-association-dialog](https://user-images.githubusercontent.com/387249/130679910-54086074-d785-40ae-b792-f01986163796.png)
