### ISSUE TITLE
Improve handling of address bar display for IPFS and IPNS

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13872]
Currently `http://test.com.ipns.localhost:8000` shows in the address address bar as `ipns://test.com`.
However test.com is neither a valid CID nor a DNSLink resolution.

There's also a problem that people that run their own local node, want to retain `ipfs://` in their URL bar, but they can't set it as the default gateway.

Currently, we only update the address bar to retain `ipfs://` and `ipns://` when the user is using the configured Brave node and it is localhost.  

We should change this to only keep `ipfs://` and `ipns://` when the address being loaded when:
i) Using the Brave node and the port matches the Brave node's port.
ii) Using the public node and the port matches the public node, and it is localhost. (Currently we don't do this, so this is new)

This means that something that is not running a gateway that is configured in Brave will not retain `ipfs://` anymore like it does with an example local server like `http://test.com.ipns.localhost:8000`

# Test cases:

## Test case 1: Non configured localhost should never show as IPFS
1) Create an entry in your hosts file pointing to 127.0.0.1 for `test.com.ipns.localhost`
2) Load `http://test.com.ipns.localhost:8000`, it should retain that address

## Test case 2: Public gateway 
1) Install IPFS Desktop and it should be started on port 8080
2) Load `http://127.0.0.1:8080/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS`. It should load the content but retain the `https://dweb.link/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS` URL in the address bar.
3) Set your public gateway to `http://127.0.0.1:8080` in settings. And also set Brave to use this public gateway when resolving IPFS URIs.
4) Load `https://dweb.link/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS`. It should update to an `ipfs://` URI.

## Test case 3: 
1) Set Brave to use the local node
2) Load `ipns://brantly.eth`
3) It should retain `ipns://brantly.eth` in the address bar.
4) Load `http://brantly.eth.ipns.localhost:48081/`
4) It should retain `ipns://brantly.eth` in the address bar.

**Comment by lidel** [comment]
Two nits regarding "Test case 2"
- When user enters custom public gateway Brave should always replace raw IP  (`127.0.0.1`) with `localhost`, as that enables subdomains and origin isolation. Raw IP can't have subdomains and all content roots share the same origin, which we don't want in browser.
- Did you mean:
  ```diff
  - retain the https://dweb.link/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS URL in the address bar
  + retain the https://localhost:8080/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS URL in the address bar
  ``` 
  ?
  (spoofing address of public Origin looks like a bug)

**Comment by stephendonner** [comment]
Verified `FIXED` on `beta` using 

Brave | 1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

Verified the inline testcases, and filed https://github.com/brave/brave-browser/issues/14499 about the IPFS URI (`localhost` vs `127.0.0.1`) mismatch.

## Test case 1: Non configured localhost should never show as IPFS

1. Create an entry in your hosts file pointing to 127.0.0.1 for `test.com.ipns.localhost`
2. Load `http://test.com.ipns.localhost:8000`, it should retain that address

<img width="980" alt="Screen Shot 2021-03-03 at 3 50 38 PM" src="https://user-images.githubusercontent.com/387249/109888372-3d191980-7c38-11eb-943f-f9121c2fb7b2.png">

## Test case 2: Public gateway

1. Install IPFS Desktop and it should be started on port 8080
2. Load `http://127.0.0.1:8080/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS`. It should load the content but retain the `https://dweb.link/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS` URL in the address bar.
3. Set your public gateway to `http://127.0.0.1:8080` in settings. And also set Brave to use this public gateway when resolving IPFS URIs.
4. Load `https://dweb.link/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS`. It should update to an `ipfs://` URI.

<img width="1110" alt="Screen Shot 2021-03-04 at 11 26 50 AM" src="https://user-images.githubusercontent.com/387249/110172220-aa9c8580-7db1-11eb-9e42-9e1e582480e6.png">
<img width="1127" alt="Screen Shot 2021-03-04 at 11 49 48 AM" src="https://user-images.githubusercontent.com/387249/110172221-ab351c00-7db1-11eb-91f0-267a1ed63318.png">
<img width="1387" alt="Screen Shot 2021-03-04 at 11 49 52 AM" src="https://user-images.githubusercontent.com/387249/110172224-ab351c00-7db1-11eb-976c-aff7075af988.png">

## Test case 3:

1. Set Brave to use the local node
2. Load `ipns://brantly.eth`
3. It should retain `ipns://brantly.eth` in the address bar.
4. Load `http://brantly.eth.ipns.localhost:48081/` (NOTE: I had to change this to be port `48083` to match)
5. It should retain `ipns://brantly.eth` in the address bar.

![ipns-host](https://user-images.githubusercontent.com/387249/110174182-98701680-7db4-11eb-8cfa-df8e7dbd54c2.gif)

**Comment by LaurenWags** [comment]
Adding `QA/Test-All-Platforms` since this issue also has the `security` label
