### ISSUE TITLE
Ads aren't visible even when shields are off

### ISSUE THREAD

**Issue by lemonnuggets** [brave/brave-browser#13870]
## Description 

On certain sites, I might wanna support them by viewing the ads. When I turn off shields I expect the ads to be visible but in a most of the sites I still can't see any ads.

## Steps to Reproduce

   1.  Go to https://www.keybr.com/
   2.  Turn off shields and allow all trackers and ads 

## Actual result:

![image](https://user-images.githubusercontent.com/63046776/106465956-b3ebb700-64c0-11eb-962b-b87dfc59b027.png)

## Expected result:
I would expect the ads to be visible. Also I did try clearing the cache but that made no difference.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 1909 (Build 18363.1316)

## Version/Channel Information:

Haven't checked this on any other builds.
- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No.

- Does the issue resolve itself when disabling Brave Rewards? 
- No.

- Is the issue reproducible on the latest version of Chrome? 
- No.

**Comment by ryanbr** [comment]
Hi, I couldn't reproduce (tested in private window mode) in Brave release. Unless there is something blocking doubleclick?

![keybr](https://user-images.githubusercontent.com/1659004/106545971-3f238600-656f-11eb-840c-66c128b02942.gif)

**Comment by lemonnuggets** [comment]
Umm I don't really understand what you mean by "blocking doubleclick". Could you clarify and is there anything I can do on my end to resolve this?

**Comment by ryanbr** [comment]
Suggesting if there was another program, application/or vpn or device blocking ads, also testing on another computer? or try Brave in private window mode. @lemonnuggets

**Comment by lemonnuggets** [comment]
Okay so it turns out that I had modified the hosts file at some point and forgot about it. Sorry and thanks for the patience.
