### ISSUE TITLE
Set P3A enabled for existing users

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#13871]
## Description 
This is the follow up issue of https://github.com/brave/brave-browser/issues/12723 to make p3a enabled for existing users.

## Test plan
P3A should be enabled for existing user when the modal for P3A is shown.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.100 x64 build
- Verified P3A opt-in onboarding is enabled by default on upgrade. 
- Verified clicking on continue enables settings to send P3A metrics
- Verified without clicking on continue in P3A onboarding, backgrounding app and relaunching set P3A metrics to be sent
----------
Verification passed on Samsung Tab A with Android 10 running 1.20.100 x64 build
- Verified P3A opt-in onboarding is enabled by default on upgrade. 
- Verified clicking on continue enables settings to send P3A metrics
- Verified without clicking on continue in P3A onboarding, backgrounding app and relaunching set P3A metrics to be sent
