### ISSUE TITLE
Even more strict on address bar for IPNS

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13874]
This issue #13872 makes it so we only use ipns:// and ipfs:// for configured gateways.

This issue https://github.com/brave/brave-browser/issues/13873 is for being more strict for `ipfs://`.

For IPNS, once we have DNSLink, we should only replace when there's a valid CID and when DNSLink has no information for the name being used.

**Comment by stephendonner** [comment]
@spylogsster mind adding a test plan for this and https://github.com/brave/brave-browser/issues/13873?  Thanks!

**Comment by spylogsster** [comment]
@stephendonner same as here https://github.com/brave/brave-browser/issues/13873#issuecomment-808141079

**Comment by stephendonner** [comment]
@lidel do you have any (additional) testcases to help me verify this (in addition to https://github.com/brave/brave-browser/issues/13873)?  Thanks!

**Comment by lidel** [comment]
You mean for DNSLink names other than `brantly.eth` from https://github.com/brave/brave-browser/issues/13873#issuecomment-808141079?

- This should succeed and redirect to ipns:// (has DNSLink)
   ` http://en.wikipedia-on-ipfs.org.ipns.localhost:[node port]/#/`
- This should fail and not redirect to ipns://  (no DNSLink)
  `http://google.com.ipns.localhost:[node port]/#/`

**Comment by stephendonner** [comment]
Verified `PASSED` with 

Brave | 1.24.50 Chromium: 90.0.4430.51 (Official Build) nightly (x86_64)
-- | --
Revision | 32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. loaded `http://en.wikipedia-on-ipfs.org.ipns.localhost:48081/` and redirected to `http://en.wikipedia-on-ipfs.org.ipns.localhost:48081/wiki`; clicked on `Open using IPFS` and got `ipns://en.wikipedia-on-ipfs.org/wiki`
2. loaded `http://google.com.ipns.localhost:48081` and got expected `ipfs resolve -r /ipns/google.com/: could not resolve name` error


<img width="1049" alt="Screen Shot 2021-04-06 at 11 37 35 AM" src="https://user-images.githubusercontent.com/387249/113761804-bc34be00-96cc-11eb-985a-4a1445180f6d.png">
<img width="1049" alt="Screen Shot 2021-04-06 at 11 37 30 AM" src="https://user-images.githubusercontent.com/387249/113761805-bccd5480-96cc-11eb-936b-71a759036feb.png">
<img width="938" alt="Screen Shot 2021-04-06 at 11 37 24 AM" src="https://user-images.githubusercontent.com/387249/113761794-ba6afa80-96cc-11eb-83cb-396256fe00b7.png">
