### ISSUE TITLE
Menu items & keyboard shortcuts to launch private windows with Tor

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1387]
Two changes need to be made to the UI for launching private windows with Tor:
- [ ] Instead of being launched from the People menu, Private Windows with Tor should be launched from a menu item named "New Private Window with Tor" in all the same places that the "New Private Window" menu item appears.
- [ ] Additionally, the "New Private Window with Tor" should have the keyboard shortcut `Ctrl + Alt + N` / `Cmd + Opt + N`.

The Incognito window menu item exists in three places:
1. the File menu
2. the three-dots menu in the top right of the browser
3. the three-dots / alternate click menu on items in the bookmarks manager

**Comment by bbondy** [comment]
> The menu item "New Incognito Window" should be renamed to "New Private Window", everywhere it appears.

Renaming for Incognito will be done here:
https://github.com/brave/brave-browser/issues/738

**Comment by riastradh-brave** [comment]
- [ ] Change `New Tor Window` to `New Private Window with Tor` or similar.

**Comment by riastradh-brave** [comment]
PR ready for review now: https://github.com/brave/brave-core/pull/605

Caveats:
- 'New private window with Tor' does not always create a new one -- it switches to an existing one if there is one.  In that window, 'New window' will open a new private window with Tor.
- If you do 'Open link in private window with Tor' when there is no such window open, it will create two tabs, one of which is left at about:newtab.

Neither of these is critical, so I figured it's better to make progress on getting the baseline functionality merged before worrying about these details.

**Comment by riastradh-brave** [comment]
PR actually addresses the whole issue including keyboard shortcut now: fb73c75eeafa87aa035e55ff84d97f02d7a1fc16

**Comment by riastradh-brave** [comment]
The key sequence Ctrl-Alt-N is apparently problematic in Chromium on Windows, as is Ctrl-Alt-anythingelse.  So, we need to find an alternative.

(I wonder what Emacs does on Windows, when every third keyboard command is control-meta-something?)

**Comment by darkdh** [comment]
https://chromium.googlesource.com/chromium/src/+/458236cb920e35864c7983b2b7e9c301a29edde9/chrome/browser/ui/views/accelerator_table.cc#22

**Comment by tomlowenthal** [comment]
If the way to create a new private window with Tor from an existing one is the "New Window" menu option, then that menu option needs to be renamed to "New Private Window with Tor" with the same keyboard shortcut when within an existing private window with Tor. I understand that we made the technical decision to implement this as a separate user profile. But nobody using their browser needs to understand that. All they need is for it to feel the same as regular private windows.

**Comment by riastradh-brave** [comment]
Correction: brave/brave-core#605 did not update the File menu on macOS.

**Comment by bbondy** [comment]
@riastradh-brave could you leave this one closed and rename it and then post a new one with the remaining items? Typically if some part is fixed it's best to post a new issue for the remaining issues.

**Comment by riastradh-brave** [comment]
Superseded by https://github.com/brave/brave-browser/issues/1627.
