### ISSUE TITLE
Decouple RPill from Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#13889]
Decouple RPill to allow requirements outside of Brave Ads to check for RPill or BPill

**Comment by btlechowski** [comment]
`QA/Blocked` asked @tmancey re RPill and BPill

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.22.53 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Ubuntu 18.04 LTS

Verified in https://github.com/brave/internal/issues/751#issuecomment-791909642

**Comment by btlechowski** [comment]
Added `QA/Test-All-Platforms`. Seems to be related to https://github.com/brave/brave-browser/issues/14232.
