### ISSUE TITLE
Disable AdBlockServiceTest.CosmeticFilteringProtect1p temporarily

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#13887]
Will be enabled with fix for https://github.com/brave/brave-browser/issues/13882

**Comment by bsclifton** [comment]
@pes10k @simonhong @antonok-edm is this issue still applicable? Two PRs were created but both closed:
- https://github.com/brave/brave-core/pull/7777
- https://github.com/brave/brave-core/pull/7779

Not sure if there was a proper fix... I think this is Windows and only intermittent?

**Comment by pes10k** [comment]
Sadly, its still needed.  Im working on another approach that i hope will address the Windows issue.

Though when looking at this last night more, the worrying part is that Windows is doing the right thing, and the other platforms shouldn't be passing.  Im really baffled, but hopefully my (incoming) rewrite with set things… re-right (har har)
