### ISSUE TITLE
"Brave Web Store" in brave://apps

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#13881]
If I open `brave://apps`, I see a tile for the non-existent **Brave** Web Store:
![Screenshot from 2021-02-01 16-29-27](https://user-images.githubusercontent.com/167821/106535253-ab888180-64aa-11eb-839b-e08fe80e0120.png)
and a link in the footer of the same page:
![Screenshot from 2021-02-01 16-30-39](https://user-images.githubusercontent.com/167821/106535325-df63a700-64aa-11eb-95f7-728f1054bab9.png)

## Brave version (brave://version info)

```
Brave	1.21.36 Chromium: 88.0.4324.96 (Official Build) nightly (64-bit)
Revision	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS	Linux
```

**Comment by rebron** [comment]
I'm not seeing this on Windows or macOS strangely enough in 1.19.x or 1.21.42

**Comment by bsclifton** [comment]
Shows for me on Windows (Nightly; 1.21.42). It's hardcoded into there - you can also see it on brave://new-tab-page

On our new tab page, we have a check to explicitly remove this:
https://github.com/brave/brave-core/blob/54603a0626bfb8ac374aba99e27c4192960c27c3/browser/ui/webui/new_tab_page/instant_service_message_handler.cc#L34-L36

**Comment by bsclifton** [comment]
@simonhong I think you recently fixed this when doing the top sites work, right? It's not showing up anymore under brave://apps 😄

**Comment by simonhong** [comment]
@bsclifton yes it's fixed by https://github.com/brave/brave-core/pull/7859/files#diff-3814b2ac1912127b98976d12107ad701113cf010e44bbcde74d1822ba9377377R251.
 It's not visible anymore since `1.23.x` Closed.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.23.25 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)

Verified that the `Brave Web Store` no longer appears in `nightly` via `brave://apps`

<img width="1785" alt="Screen Shot 2021-03-09 at 5 01 43 PM" src="https://user-images.githubusercontent.com/387249/110559539-3fc4b480-80f9-11eb-83e6-456e60f2d584.png">
