### ISSUE TITLE
Cant go to any Settings which have submenus

### ISSUE THREAD

**Issue by lxwulf** [brave/brave-browser#13888]
## Description 

I want to look shortly to my bookmarks over the hamburger menu, but I can't select any of my Bookmarks because it is in a submenu and my mouse courser stays with the selection on the main window.

## Steps to Reproduce

   1. Click on the Hamburger Menu
   2. Try to go to a setting which have sub menus

## Actual result:

Selection is flickering around...

## Expected result:
I can select the sub menus

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.21.37 Chromium: 88.0.4324.96 (Official Build) nightly (64-bit)
68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Don't know...
- Can you reproduce this issue with the beta channel?
- Don't know...
- Can you reproduce this issue with the nightly channel?
- Yes!

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome?
- Don't know...

**Comment by rebron** [comment]
@lxwulf Can you provide specifics about your distribution?

**Comment by lxwulf** [comment]
![Screenshot_20210208_145006](https://user-images.githubusercontent.com/44492381/107228684-39211f80-6a1d-11eb-9ed4-29566439b700.jpg)

When you need more information just ask me 😊

**Comment by fmarier** [comment]
That's odd, we've never had a similar report from Fedora/KDE before.

Here are a few things that would be helpful to try in order to see if we can narrow the problem down further:
- try on your machine using the GNOME desktop environment
- try installing Chrome to see if the issue exists there too

**Comment by lxwulf** [comment]
My system was broke after an upgrade, so I did a reinstallation and changed to gnome desktop, the default one, which came with fedora (33). For me so far is it now working again.

Thank you too for any help!

**Comment by fmarier** [comment]
Thanks for the update. We'll close the report for now. Feel free to reopen if you encounter that problem again.
