### ISSUE TITLE
Connection encrypted educational modal isn't aligned below shields

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13892]
## Description 
Connection encrypted educational modal isn't aligned below shields

## Steps to reproduce 

   1. Install 1.21.38 x6 nightly build
   2. Visit a page that has HTTPS upgrade
   3. See the modal 

## Actual result 

Landscape | Portrait
-- | --
![image](https://user-images.githubusercontent.com/17010094/106596017-59983800-654c-11eb-809b-9df739bc8f3b.png) | ![image](https://user-images.githubusercontent.com/17010094/106595995-5309c080-654c-11eb-8fa4-82410defc80a.png)

## Expected result
Should be like other modals which are below the shields

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.21.38

### Website problems only- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @karenkliu @deeppandya

**Comment by deeppandya** [comment]
![Screenshot_20210204-113202](https://user-images.githubusercontent.com/5146988/106924246-e2de7480-66dc-11eb-858d-8af0f3ed9be7.png)
![Screenshot_20210204-113342](https://user-images.githubusercontent.com/5146988/106924248-e3770b00-66dc-11eb-82e5-e13633b47cb3.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.102 x64 build
- Verified all the tooltips are properly aligned below Shields in both portrait and landscape orientation

**Portrait**

![image](https://user-images.githubusercontent.com/17010094/107349486-2f042d00-6ac0-11eb-9d13-5bb634a9c22b.png) | ![image](https://user-images.githubusercontent.com/17010094/107349499-34fa0e00-6ac0-11eb-9649-ffac455a3bf4.png) | ![image](https://user-images.githubusercontent.com/17010094/107349533-3deadf80-6ac0-11eb-9786-f50fce5e97db.png) | ![image](https://user-images.githubusercontent.com/17010094/107349543-417e6680-6ac0-11eb-978b-e5307d7eb87f.png)
-- | -- | -- | --

**Landscape**

![image](https://user-images.githubusercontent.com/17010094/107349600-522edc80-6ac0-11eb-8b04-bd8cb67141ed.png) | ![image](https://user-images.githubusercontent.com/17010094/107349615-55c26380-6ac0-11eb-8353-532a600e9743.png) | ![image](https://user-images.githubusercontent.com/17010094/107349639-5c50db00-6ac0-11eb-9004-bdb6c98a08d8.png) | ![image](https://user-images.githubusercontent.com/17010094/107349648-5f4bcb80-6ac0-11eb-93fb-a65c54f0d1e7.png)
-- | -- | -- | --

------------

Verification passed on Samsung Tab A with Android 10 running 1.20.102 x64 build
- Verified all the tooltips are properly aligned below Shields in both portrait and landscape orientation

**Portrait**

![image](https://user-images.githubusercontent.com/17010094/107350921-ec435480-6ac1-11eb-9d55-a04dd8124dbd.png) | ![image](https://user-images.githubusercontent.com/17010094/107350904-e6e60a00-6ac1-11eb-9faa-c420f74db108.png) | ![image](https://user-images.githubusercontent.com/17010094/107350885-e2215600-6ac1-11eb-8d7e-cb94bc1d6eb3.png) | ![image](https://user-images.githubusercontent.com/17010094/107350854-d9c91b00-6ac1-11eb-8b6d-386cf6ddb76b.png)
-- | -- | -- | --

**Landscape**

![image](https://user-images.githubusercontent.com/17010094/107350820-d2097680-6ac1-11eb-8ae7-0faedd468df8.png) | ![image](https://user-images.githubusercontent.com/17010094/107350802-cc139580-6ac1-11eb-99ed-b9da093dc8b2.png) | ![image](https://user-images.githubusercontent.com/17010094/107350795-c918a500-6ac1-11eb-85d9-b21c77c125e6.png) | ![image](https://user-images.githubusercontent.com/17010094/107350783-c5851e00-6ac1-11eb-95f4-3c884c786fab.png)
-- | -- | -- | --

**Comment by karenkliu** [comment]
@deeppandya Is there any way we can center the icon with the text in the tooltip? 

![image](https://user-images.githubusercontent.com/2388823/107696614-0a968500-6c67-11eb-8add-ec149ea191ef.png)
