### ISSUE TITLE
Fix unsafe use of base::Unretained

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#13890]
Investigate use of base::Unretained

* Why wrong use of base::Unretained is bad?

Calling a callback bound to an unretained pointer, that points to a destroyed object results in a browser crash. Crashes significantly hit users retention, our reputation and thus, our market share.

Moreover, such crashes are very hard to identify and fix. Often they happen on shutdown, and prevent the browser from saving it's data to disk correctly, leading to another (sometimes, infinite)crash during startup.

* When base::Unretained is safe?

If a posted callback is canceled before the bound object dies. E.g. binding an unretained pointer to a callback for timer or url loader that our object owns

**Comment by iefremov** [comment]
@tmancey I think we've covered everything in https://github.com/brave/brave-browser/issues/14172, otherwise please reopen
