### ISSUE TITLE
Cast dialog isn't appearing on https://gem.cbc.ca/live/channel/ottawa

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#13898]
## Description 
No way to cast video from https://gem.cbc.ca/live/channel/ottawa. Chrome works ok with it.

## Steps to reproduce 

   1. Go to https://gem.cbc.ca/live/channel/ottawa
   2. Click play
   3. Tap a cast icon 
![Screenshot from 2021-02-01 22-47-03](https://user-images.githubusercontent.com/12011303/106615910-efc36280-653a-11eb-92ab-cedbcf27d542.png)

## Actual result 
Nothing happens

## Expected result
A dialog with supported devices has to be appeared

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Related https://github.com/easylist/easylist/commit/8fcdabde77b4d666372ce8a63833f3949a5be0a4

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.71 x64 build
- Verified cast icon is shown on the video player
- Verified tapping on the cast icon looks for devices 

![image](https://user-images.githubusercontent.com/17010094/109616712-68fba880-7b2d-11eb-809b-308586fc91b3.png) | ![image](https://user-images.githubusercontent.com/17010094/109616735-6ef18980-7b2d-11eb-9adf-5dc604ec3a73.png)
-- | --

-----------
Verification passed on Samsung Tab A with Android 10 running 1.21.71 x64 build
- Verified cast icon is shown on the video player
- Verified tapping on the cast icon looks for devices 

![image](https://user-images.githubusercontent.com/17010094/109616654-597c5f80-7b2d-11eb-9bad-779fff2dd749.png) | ![image](https://user-images.githubusercontent.com/17010094/109616675-5f724080-7b2d-11eb-8c28-b16ce637dee9.png)
-- | --
