### ISSUE TITLE
Educational modals don't show up on page load sometimes

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13894]
## Description 
Educational modals doesn't show up on page load sometimes

## Steps to reproduce 

   1. Install 1.21.38 x64 nightly build
   2. Visit `https://m.youtube.com`
   3. Sometimes loading the page loads the educational modal but sometimes only shows up when a video is loaded

## Actual result 

Video load | Page load
-- | --
![image](https://user-images.githubusercontent.com/17010094/106604408-830a9100-6557-11eb-97fd-2e656570478b.png) | ![image](https://user-images.githubusercontent.com/17010094/106604427-8b62cc00-6557-11eb-8f65-707007b33355.png)

## Expected result
Should be consistent

## Issue reproduces how often 
Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.21.38

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @karenkliu

**Comment by deeppandya** [comment]
@srirambv is this issue still relevant ? We discussed about it here : https://bravesoftware.slack.com/archives/C0816QH3R/p1612266714095400?thread_ts=1612266714.095400&cid=C0816QH3R

**Comment by srirambv** [comment]
No this can be closed as expected behaiour based on discussion at https://bravesoftware.slack.com/archives/C0816QH3R/p1612266714095400?thread_ts=1612266714.095400&cid=C0816QH3R
