### ISSUE TITLE
Revise icon for Brave internal pages

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#1390]
## Description 
Our internal pages utilize the Brave lion logo but on Dark theme the lion is reversed and takes on the dreaded tiny face aesthetic. This just needs updated to a full color lion in both instances. 

![image](https://user-images.githubusercontent.com/29072694/46331586-6e0b4500-c5cd-11e8-9490-730a74618625.png)

## Steps to Reproduce

   1. Go to settings
   2. Look at the sad tiny face lion.
   3. Feel shame

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/46752409-1fc00b00-cc8b-11e8-9922-fc3f7b4e9ee7.png)
