### ISSUE TITLE
Crash in Greaselion service on shutdown

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#13906]
This crash is pretty serious and pretty popular on backtrace. Looks like it was introduced with https://github.com/brave/brave-core/pull/7141/files

we shouldn't modify `extension_dirs_` on task runner, because the service might be already dead.

There is also another threading problem, but possible not related to this crash: we shouldn't use a pointer to rules on taskrunner, because they are can be modifyed (or destoryed) on another thread, e.g. when another version of component is downloaded.

https://brave.sp.backtrace.io/p/brave/triage?filters=((callstack%2Ccontains%2COnTaskRunner)%2C(ver%2Cregex%2C%228%5B7%7C8%7C9%5D.*%22)%2Cptype%3Dbrowser)&aggregations=((guid%2Cunique)%2C(classifiers%2Chead))

```
[ 02 ] std::__terminate(void (*)())
[ 03 ] __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)
[ 04 ] __cxa_throw
[ 05 ] std::__1::__throw_length_error(char const*)
[ 06 ] std::__1::__vector_base_common<true>::__throw_length_error() const
[ 07 ] void std::__1::vector<base::ScopedTempDir, std::__1::allocator<base::ScopedTempDir> >::__push_back_slow_path<base::ScopedTempDir>(base::ScopedTempDir&&)
[ 08 ] (anonymous namespace)::ConvertGreaselionRuleToExtensionOnTaskRunner(greaselion::GreaselionRule*, base::FilePath const&, std::__1::vector<base::ScopedTempDir, std::__1::allocator<base::ScopedTempDir> >*)
[ 09 ] base::internal::Invoker<base::internal::BindState<scoped_refptr<extensions::Extension> (*)(greaselion::GreaselionRule*, base::FilePath const&, std::__1::vector<base::ScopedTempDir, std::__1::allocator<base::ScopedTempDir> >*), greaselion::GreaselionRule*, base::FilePath, std::__1::vector<base::ScopedTempDir, std::__1::allocator<base::ScopedTempDir> >*>, scoped_refptr<extensions::Extension> ()>::RunOnce(base::internal::BindStateBase*)

```

**Comment by iefremov** [comment]
cc @emerick @pilgrim-brave 
cc @rebron @bsclifton for triage

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.20.101 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Unable to reproduce the crash using `1.19.92` (Release Channel). 

Verified test plan from https://github.com/brave/brave-core/pull/7800#issue-567000232 with Twitter, Reddit, and GitHub pages. Confirmed no crash observed.

Executed test plan ~15x without seeing any crashes.

**Comment by kjozwiak** [comment]
@btlechowski this was merged ~4hrs ago so we'll need another RC which I'm going to start shortly. The issue was intermittent so it's hard to reproduce. Mind running through it again quickly once we get new builds?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.20.102 Chromium: 88.0.4324.152 (Official Build) (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 10.15.7 (Build 19H512)
```

Unable to reproduce the crash using `1.19.92` (Release Channel). Attempted test plan from https://github.com/brave/brave-core/pull/7800#issue-567000232 with Twitter, Reddit, and GitHub pages.

Verified test plan from https://github.com/brave/brave-core/pull/7800#issue-567000232 with Twitter, Reddit, and GitHub pages. Confirmed no crash observed or listed in brave://crashes. 

Executed test plan ~15x without seeing any crashes.
