### ISSUE TITLE
Tab Groups forces Bottom Bar to be disabled

### ISSUE THREAD

**Issue by rodrigoswz** [brave/brave-browser#13904]
## Description 
Tab Groups is a great chromium feature that can be enabled in `chrome://flags`, and is [currently being enabled automatically in Chrome](https://www.androidpolice.com/2021/01/30/google-is-rolling-out-grid-view-and-tab-groups-for-chrome-on-android/
).

![Tab Groups in Chrome. Source: Android Police](https://www.androidpolice.com/wp-content/uploads/2021/01/29/Chrome-Tab-Grouping-1.gif)

Unfortunately, when enable this in Brave, you are no longer able to use the bottom bar. It will always be disabled, even if you try to enable it again in settings. The only way to get bottom bar again is to disabling Tab Groups related flags.

## Steps to reproduce 
   1. Go to `brave://flags`
   2. Enable the flags
      - `#enable-tab-grid-layout`
      - `#enable-tab-to-gts-animation`
      - `#enable-tab-groups`
      - `#enable-tab-groups-continuation`
      - `#enable-tab-groups-ui-improvements`
   3. Restart Brave twice to make sure the changes have been applied

## Actual result 

Tab Groups works fine, but now Brave's bottom bar is disabled
https://i.imgur.com/nZsedFc.png
https://i.imgur.com/Y8POR1K.png

## Expected result
Enable Tab Groups without losing Brave's bottom bar

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.21.38

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
This is a known issue with bottom toolbar and the flag. 

cc: @jamesmudgett to come up with a new design for this when tab grouping becomes the default. @samartnik

**Comment by LesterCovax** [comment]
There appears to be a larger issue surrounding grid view, tab groups, and the bottom toolbar.

1. Enabling bottom toolbar breaks grid view and tab groups, as this thread highlights.
2. Grid view and tab groups are co-dependent to a worrisome degree. It's to the point where you can disable all flags for either 'grid view' or 'tab groups', but as long as one of those is enabled, both will become enabled.
3. Due to the previous point, it's not possible to enable the bottom toolbar alongside 'grid view', nor disable the bottom toolbar and enable 'grid view' without 'tab groups'.
4. Minor point, but some settings for 'grid view' simply don't work.

I'd be willing to sacrifice the bottom bar to have grid view and tab groups, but not without a way to disable the persistent tab group bar, or the default behavior of adding new tabs to the current group.
I haven't tested this behavior in chromium (only on Brave on Android v1.20.103), so I can't deduce if this spiderweb of issues is Brave or Chromium-based.

**Comment by samartnik** [comment]
New look with both Tab Groups and bottom toolbar enabled
![device-2021-03-11-124632](https://user-images.githubusercontent.com/30602739/110859567-9c56d980-8289-11eb-96e2-80c01d82328c.png)
![device-2021-03-11-124646](https://user-images.githubusercontent.com/30602739/110859587-a11b8d80-8289-11eb-8ee9-135a8880c9e1.png)

**Comment by samartnik** [comment]
Test plan:
1. Go to `brave://flags`.
2. Enable `Tab Groups` and `Tab Grid` features and restart twice to apply changes.
3. Make sure both bottom controls are visible when necessary (when tabs are grouped).
4. Make sure bottom toolbar behaves as before when tabs are not grouped.
5. Make sure Tab Groups work as before when bottom toolbar is disabled (should be 1 to 1 with Chromium).

**Comment by cognifloyd** [comment]
I wish the tab group bar was above the address bar. Then I could have the brave bottom bar, and tab groups.

Btw, I have tab grid layout enabled and the bottom bar still works. Only tab groups causes the issue.


Version details:

Brave | 1.21.74 Chromium: 89.0.4389.72 (Official Build) (32-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Android 11; Pixel 4a Build/RQ2A.210305.006

**Comment by rodrigoswz** [comment]
I think the best UI/UX for this would be Brave to use Bottom Address Bar, just as it already exists in Firefox, Vivaldi and Kiwi.

This saves space on the screen, giving more space for the website content.

See the result in the test above, now we have 3 browser bars: Address bar, toolbar and group bar. The website that really matters is getting tighter and tighter to use.

However, at the same time, toolbar is great for one-handed use. So, bottom address bar would solve both problems.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.68 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/13904#issuecomment-797074754
- Verified with flags enabled able to group tabs 
- Verified bottom toolbar works fine when tabs are grouped
- Verified able to close tabs from tab group without going to tab tray
- Verified able to reopen closed tab from group via undo button
- Verified bottom toolbar swipe works to switch tabs. Swiping happens within tab group and between tab groups
- Verified when swipe using bottom toolbar, coming out of tab group hides the tab group bar as well
- Verified tab group works on private tab as well
