### ISSUE TITLE
[Android] "skip" button/text misaligned via rewards onboarding

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13909]
## Description 

Currently the "Skip" button and "Lets take a quick tour" text/button are not aligned. It appears like the "Skip" button is being shifted to the right and the "Lets take a quick tour" is shifted to the left. @srirambv originally reported the issue on Slack which was supposed to be fixed via https://github.com/brave/brave-core/pull/7764 which didn't occur as per https://github.com/brave/brave-core/pull/7764#issuecomment-771972829.

## Steps to reproduce 

   1. launch `1.21.39 CR: 88.0.4324.96`
   2. run through the rewards onboarding

## Actual result 

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot_20210202-162137_Brave - Nightly](https://user-images.githubusercontent.com/2602313/106666206-4b124680-6575-11eb-95c6-04c08be65b7a.jpg) | ![Screenshot_20210202-133743_Brave - Nightly](https://user-images.githubusercontent.com/2602313/106666215-4e0d3700-6575-11eb-867a-feaf060db717.jpg)

## Expected result

Both the "Skip" and "Lets take a quick tour" text/button should be centered.

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 11`
   
## Brave version

* `1.21.39 CR: 88.0.4324.96` - **Reproduced**
* `1.19.88 CR: 88.0.4324.96` - **Reproduced**

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @codybanxs @deeppandya @srirambv

**Comment by deeppandya** [comment]
@kjozwiak @codybanxs we see the issue in the alignment because we add drawable to the right of the text and in the example above, it seems like the translated text doesn't fit properly and that's why we see more padding between text and drawable. any suggestion to resolve this @codybanxs @karenkliu @jamesmudgett ?

**Comment by kjozwiak** [comment]
@deeppandya seems like it's still a bit misaligned. The `Skip` button and the above text don't seem to be aligned so it makes it appear like the either the text or the skip button is shifted to the right. Examples:

**`1.28.60 Chromium: 91.0.4472.124 English`** | **`1.26.74 Chromium: 91.0.4472.124 German`**
---------------------------------------------------|----------------------------------------------------
![Screenshot_20210707-163455_Brave](https://user-images.githubusercontent.com/2602313/124827850-86f67100-df44-11eb-9e24-001276ffeab0.jpg) | ![Screenshot_20210707-165020_Brave](https://user-images.githubusercontent.com/2602313/124827861-89f16180-df44-11eb-8e51-a22beb4727c1.jpg)

**`1.26.74 Chromium: 92.0.4515.81 English`** | **`1.26.74 Chromium: 92.0.4515.81 German`**
---------------------------------------------------|----------------------------------------------------
![Screenshot_20210707-170725_Brave - Nightly](https://user-images.githubusercontent.com/2602313/124829039-12bccd00-df46-11eb-9a5c-3d3e8def9a4a.jpg) | ![Screenshot_20210707-170506_Brave - Nightly](https://user-images.githubusercontent.com/2602313/124829054-16505400-df46-11eb-9569-ed2d7fecf33c.jpg)

**Comment by Miyayes** [comment]
Will be superseded by new onboarding.
