### ISSUE TITLE
New Tab Page Brave Together link and prompt should only show on nightly

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#13905]
...and for regions where Brave Together is supported.

Follow-up to the feature introduced in https://github.com/brave/brave-browser/issues/12776

**Comment by kjozwiak** [comment]
@brave/legacy_qa once this lands and we do channel migrations, we should get both `1.20.x` & `1.21.x` to make sure that Brave Together is only available on `1.22.x` (Nightly).

**Comment by LaurenWags** [comment]
Per https://github.com/brave/brave-browser/issues/13905#issuecomment-772093483 marking as `QA/blocked` until channel migrations are done so we can check across all versions.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | Windows 10 OS Version 2004 (Build 19041.746)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/7787 and description from https://github.com/brave/brave-browser/issues/12776#issue-746073013

**Nightly channel - 1.22.6**
- Ensured that brave together link and the prompt is shown in New Tab Page in the nightly build **ONLY**
![image](https://user-images.githubusercontent.com/38657976/107206945-b5b7fc00-6a25-11eb-861d-341556cfcf1c.png)
![image](https://user-images.githubusercontent.com/38657976/107206740-725d8d80-6a25-11eb-8310-a22d71c25fa9.png)

**Dev channel - 1.21.45**
![image](https://user-images.githubusercontent.com/38657976/107207095-e5670400-6a25-11eb-8684-6038c96fe71e.png)

**Dev channel - 1.21.44**
![image](https://user-images.githubusercontent.com/38657976/107207203-0af40d80-6a26-11eb-8886-d3853e82e0be.png)

**Release channel - 1.20.100**
![image](https://user-images.githubusercontent.com/38657976/107207327-324ada80-6a26-11eb-803e-f50208732eac.png)
