### ISSUE TITLE
changing text from dark to light grey via ads/ac selection panel

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#13911]
## Description 

We fixed the issue re: the text appearing as a hyperlink via https://github.com/brave/brave-browser/issues/13800. However, rather than using the light grey text that was mentioned via https://github.com/brave/brave-browser/issues/13800#issuecomment-768485092, we're using basic/black text which blends into everything else on that particular onboarding panel.

## Steps to reproduce 

   1. launch `1.21.39 CR: 88.0.4324.96`
   2. run through the rewards onboarding and navigate to the panel where you pick number of ads/ac amount.

## Actual result 

![Screenshot_20210202-150839_Brave - Nightly](https://user-images.githubusercontent.com/2602313/106659893-53668380-656d-11eb-963f-f5fe8ad1341d.jpg)

## Expected result

Should look as per https://github.com/brave/brave-browser/issues/13800#issuecomment-768485092:

<img width="378" alt="Screen Shot 2021-01-27 at 10 15 19 AM" src="https://user-images.githubusercontent.com/61210652/106036711-86e77080-608a-11eb-9d84-54ff94b75e60.png">

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Will be introduced into `1.19.x` via https://github.com/brave/brave-core/pull/7764
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 11`
   
## Brave version

* `1.21.39 CR: 88.0.4324.96` - **Reproduced**

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @codybanxs @deeppandya @srirambv

**Comment by deeppandya** [comment]
![Screenshot_20210204-170834](https://user-images.githubusercontent.com/5146988/106961482-a37b4c80-670b-11eb-8bc8-6f4d1b511943.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.23.63 x64 beta build
- Verified as per https://github.com/brave/brave-browser/issues/13911#issuecomment-773635539

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/113825913-784bc280-9779-11eb-961f-d9d86d8297db.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/113825863-6538f280-9779-11eb-9077-5514201ac2aa.png>
