### ISSUE TITLE
Spotify Web Player Unable to Play Content

### ISSUE THREAD

**Issue by jhreis** [brave/brave-browser#1391]
## Description 

When attempting to use [spotify's web player](https://open.spotify.com), a message appears, linking to their support site:

![spotify_web_player](https://user-images.githubusercontent.com/2781690/46350592-18618780-c623-11e8-8662-6c5b5d8fe41f.png)

Following their Chrome instructions on their support site:

![enable_the_web_player_-_spotify](https://user-images.githubusercontent.com/2781690/46350806-b5242500-c623-11e8-8ad5-4308138a5b34.png)

Protected Content was already enabled on my machine:

![settings](https://user-images.githubusercontent.com/2781690/46350831-c0775080-c623-11e8-92e4-c7bfd0c424d2.png)

## Steps to Reproduce

   1. Go to: https://open.spotify.com
   2. Login
   3. Follow Spotify's instructions to enable player (see description)

## Actual result:

Unable to get around their 'error' message.

## Expected result:

The ability to get into the online player and play audio.

## Reproduces how often: 

100%

## Brave version (chrome://version info)

ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Beta
- Does it reproduce on browser-laptop? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by LaurenWags** [comment]
@jhreis did changing Cookie Control to 'Allow All Cookies' allow you to listen via the web?

**Comment by Brave-Matt** [comment]
I'm a little late to the party here but has this not been addressed?
I'm able to login to Spotify web player without issue. I always have been. Shields up in panel and defaults:
![image](https://user-images.githubusercontent.com/3299098/47932391-c95f7a00-de8e-11e8-9e08-08f1ab34e0dc.png)
![image](https://user-images.githubusercontent.com/3299098/47932408-d2504b80-de8e-11e8-89f7-e971f7c4b993.png)

**Comment by eljuno** [comment]
So, I encounter this issue and _able_ to make it work. Somehow the Widevine notification not showing @ `open.spotify.com`

STR:
- Open `spotify.com`
- There you should see Widevine notification
- Install and run Widevine
- Open `open.spotify.com`
- It working. :)

**Comment by Jacalz** [comment]
Really want to the see this fixed too, fairly annoying 😅 
Thanks for the workaround though @eljuno 👍

**Comment by DOSputin** [comment]
@Jacalz,   @eljuno's solution is not really a work around.   Really just a dependency of spotify that isn't bundled with Brave, that if you want to use the web player you must install.   Maybe this info should be added to a Spotify section of the Brave wiki?

**Comment by MarkOSullivan94** [comment]
Thanks for posting a solution @eljuno! 

Is there anything which can be done from the Brave browser to notify the user why it might be not working once they're on https://open.spotify.com/* ? For example an notification if they haven't enabled the Widevine plugin?

**Comment by goodies4uall** [comment]
Widevine setting was not enabled by default anymore:
![image](https://user-images.githubusercontent.com/842778/75298406-6373d000-5800-11ea-979e-5e5a33ac677d.png)

**Comment by Kartereo** [comment]
Just tried this and spotify is still not working on brave. I am not turning off trackers or device recognition so that their shitty programming can work.

**Comment by kjozwiak** [comment]
@Kartereo have you enabled Widevine? I just checked using the following build which is the latest released and everything seemed to be working using the default shield settings:

```
Brave | 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
```

Once I visited http://spotify.com, you should get something similar to the following:

<img width="966" alt="Screen Shot 2020-03-30 at 3 03 12 AM" src="https://user-images.githubusercontent.com/2602313/77884561-4ed98c00-7233-11ea-97ff-02408ea6b67f.png">

Once Widevine was installed, I would able to play music using the default shield settings after refreshing http://spotify.com.

**Comment by Kartereo** [comment]
@kjozwiak It just needed a refresh 🤦🏻‍♂️

**Comment by kjozwiak** [comment]
> @kjozwiak It just needed a refresh 🤦🏻‍♂️

Awesome, glad it worked 👍 I'm going to close this off as Spotify seems like it's working with the default shield settings once Widevine has been installed. If anyone is still having issues, please feel to re-open or if you can't re-open, create a new issue.

**Comment by davy79** [comment]
Well for what it's worth...

got the pop-up for wide-vine... enabled it.... dropped all shields... refresh... restart....
nothing seems to get the player going :-(

**Comment by davy79** [comment]
ah crap... never mind... I had the "protected content" toggle off in settings... :-S

sorry for the noise...

**Comment by Sadique785** [comment]
### **🎵 How to Fix Spotify Web Player Not Working on Brave**

If Spotify keeps asking you to download the app instead of playing in Brave browser, the issue is usually due to DRM (Widevine) not being enabled.

### ✅ Steps to fix:

- Open Brave and go to:  `
- Look for “Widevine” and enable it.
 (Spotify requires Widevine DRM for playback.)

- Restart Brave and open Spotify Web Player


<img width="1919" height="936" alt="Image" src="https://github.com/user-attachments/assets/01c98b04-73c6-4c1a-b635-ca079acafeac" />

`
