### ISSUE TITLE
brave://new-tab-page opens the chromium new tab page

### ISSUE THREAD

**Issue by sloshyyy** [brave/brave-browser#13910]
## Description 
brave://new-tab-page directs to the chromium new tab page instead of the brave one.

## Steps to Reproduce

   1. Open brave
   2. Navigate to brave://new-tab-page

## Actual result:
The chromium new tab page appears

## Expected result:
The brave new tab page appears

## Reproduces how often: 
Easily reproducable

## Brave version (brave://version info)

Brave | 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Linux

## Version/Channel Information:
I did not test on beta/nightly channels.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
This is expected behavior on Chrome

**Comment by bsclifton** [comment]
@rebron should we make this page resolve the same as brave://newtab?

It is useful to compare with the Chromium one - but then there are problems like https://github.com/brave/brave-browser/issues/10676

**Comment by rebron** [comment]
We should just remove brave://new-tab-page in #10676, not sure redirecting brave://new-tab-page gets us anything. 
Definitely has been useful to have though to compare against our own implementation.

**Comment by rebron** [comment]
Going to close this one as a wontfix/duplicate in that we wontfix a redirect but we will remove the page in #10676
