### ISSUE TITLE
Brave not awaiting Promises in Console/Snippets

### ISSUE THREAD

**Issue by stephencweiss** [brave/brave-browser#13916]
## Description 

When using DevTools, I am trying to use a Promise chain to await a response, but all I get is `Promise{<pending>}`

## Steps to Reproduce

   1. Open DevTools
   2. Type the following
       ```javascript
       navigator.getInstalledRelatedApps().then(res => console.log(res))
       ```
   3. You will see a `Promise{<pending>}` instead of the actual awaited result. 
   4. Compare the result in Chrome

## Actual result:

![Screen Shot 2021-02-02 at 6 42 09 PM](https://user-images.githubusercontent.com/39878535/106681558-5cb01a00-6586-11eb-8cd0-ac5335a5c6ce.png)

## Expected result:
The promise should await.

## Reproduces how often: 

every time I've tried.

## Brave version (brave://version info)

```

Brave | 1.19.88 Chromium: 88.0.4324.96 (Official Build) (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 10.15.7 (Build 19H114)
JavaScript | V8 8.8.278.14
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=AutoupgradeMixedContent,LegacyTLSEnforced,WebUIDarkMode,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges --disable-features=AutofillEnableAccountWalletStorage,TabHoverCards,TextFragmentAnchor,PasswordCheck,NetworkTimeServiceQuerying,WebOTP,NotificationTriggers,IdleDetection,AutofillServerCommunication,PrivacySettingsRedesign,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/stephen.weiss/Library/Application Support/BraveSoftware/Brave-Browser/Default
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? haven't tried
- Can you reproduce this issue with the nightly channel? haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?  I don't think I have Rewards enabled?
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
@stephencweiss Looks like you still have shields up in your mock? Can you try with shields down and see if it's working for you.

<img width="1274" alt="Screen Shot 2021-02-05 at 1 18 20 PM" src="https://user-images.githubusercontent.com/5951041/107090328-e3e2d500-67b4-11eb-827a-6f2f0f51f1fc.png">

**Comment by stephencweiss** [comment]
@rebron, looks like I'm still getting the same thing?

![Screen Shot 2021-02-07 at 3 26 36 PM](https://user-images.githubusercontent.com/39878535/107159957-ee3dd400-6958-11eb-9077-cf74591e9a9a.png)

Am I missing something?

Thanks!
