### ISSUE TITLE
Privacy stats onboarding is not shown on first tab when P3A opt-in is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13926]
## Description 
Privacy stats onboarding is not shown on first tab when P3A opt-in is disabled

## Steps to reproduce 

   1. Install 1.21.96 x64 build
   2. Background app when P3A opt-in is shown
   3. Relaunch browser, no Privacy stats onboarding is shown
   4. Open a new tab, privacy stats onboarding is shown

## Actual result 
Stats onboarding is not shown if app is backgrounded on install launch

## Expected result
Probably show the onboarding when app is brought back in focus rather than waiting for a new tab to be opened

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.20.96

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by deeppandya** [comment]
@srirambv this should not be an issue with updated P3A modal and set brave as default broswer modal behaviour. can you verify and close this issue ?

**Comment by bsclifton** [comment]
@deeppandya would this still be an issue after https://github.com/brave/brave-core/pull/7825?

**Comment by deeppandya** [comment]
yea @bsclifton because we needed to update P3A modal update behaviour for set as default browser modal and with the revert above, this would be still an issue. I can create a fix for thsi issue only and add it for 1.20.x

**Comment by deeppandya** [comment]
According to the previous behaviour, if user has seen the P3A modal once, we shouldn't show them and if you put the app in background after seeing the modal, it won't show it again.

**Comment by deeppandya** [comment]
@srirambv can you verify this issue for 1.20 as we decided to include set brave as default browser in 1.20 ? CC @bsclifton
