### ISSUE TITLE
shields show as disabled after clearing browsing data from 'All time'

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1392]
## Description 
When you clear browsing data with the time range of 'All Time' and go back to an opened tab, or open a new tab, the shields show as disabled but still appear to function (badge count of blocked items is still displayed). Refresh of page does not resolve the issue, you must close and reopen Brave to get the shield icon to be orange again. Other time ranges do not seem to have this issue currently.

## Steps to Reproduce

   1. Clean profile with 0.55.10
   2. Visit some sites (I used brianbondy.com and nytimes.com)
   3. Click on 3 dots menu > More Tools > Clear Browsing Data.
   4. Click on Advanced.
   5. Change time range to 'All Time'
   6. Select items to clear.
   7. Click Clear data.
   8. Go back to one of the opened tabs. Or open a new tab and visit a site.

## Actual result:
Shield icon looks disabled, but displays the badge count. Clicking on the shields shows that they are enabled.
![shields](https://user-images.githubusercontent.com/28145373/46351667-e7368680-c625-11e8-92a7-6d03bfad4024.gif)

## Expected result:
Shields icon should not show as disabled.

## Reproduces how often: 
Easily

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes
- Does it reproduce on browser-laptop? n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Similar to https://github.com/brave/brave-browser/issues/505
Reproduced by @srirambv on Windows

**Comment by srirambv** [comment]
Only happens when you select `All Time` from clear history popup. If you retain `Last hour` and clear issue doesn't reproduce.

**Comment by tomlowenthal** [comment]
Hey @LaurenWags this might be fixed now. Could you re-test?

**Comment by LaurenWags** [comment]
@tomlowenthal can confirm this appears to be fixed with

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta(64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X
