### ISSUE TITLE
Home button option missing from Tablets

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13931]
## Description 
Home button option missing from Tablets

## Steps to reproduce 

   1. Install 1.19.90 x64 build
   2. Go to Settings
   3. No option for Home button under Controls

Actual result | Expected result
-- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/106744384-9a10b800-6617-11eb-97bf-b6ee1d4fc66f.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/106744403-9da43f00-6617-11eb-8077-98555d37e707.png>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):Tablet
   - Android version: 10
   
## Brave version
1.19.90

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by GeetaSarvadnya** [comment]
Reproduced in Samsung Galaxy Tablet version 10 - Brave 1.19.90

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.19.91 x64 build
- Verified Home button option is still there under controls in menu
- Verified disabling and re-enabling home button doesn't cause any crash
- Verified tapping home button loads the set page 
- Verified upgrading from GPS version and selecting home button doesn't cause any crash

https://user-images.githubusercontent.com/17010094/106862456-10b4c080-66bf-11eb-9aa0-7657802461e3.mp4

--------------
Verification passed on OnePlus 6T with Android 10 running 1.19.91 x64 build
- Verified home button works as expected on ARM device
- Verified disabling bottom toolbar hides home button menu under controls 
- Verified clicking on home button laods the home page and doesn't crash
