### ISSUE TITLE
Add a Media Router option for cast on Android

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#13933]
## Description 
We want to mimic what we have on desktop for cast functionality. It's off by default, but on Android we don't have such an option Media Router, we have to add it somewhere in the menu
![Screenshot from 2021-02-02 11-07-45](https://user-images.githubusercontent.com/12011303/106772001-937d4300-660d-11eb-8d2c-4ee88aa3c9f0.png)
and set it off be default as it's always on currently.

## Steps to reproduce 
   1. Install a fresh version of Brave.
   2. Go to a website and open a video that can be casted https://gem.cbc.ca/live/channel/ottawa (perhaps need to be a VPN targeted to Canada if you are outside)
   3. Click a cast button

## Actual result 
   1. There is no a Media Router option.
   2. Cast is allowed by default.

## Expected result
   1. There is a Media Router option.
   2. Cast is not allowed by default.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by anthonypkeane** [comment]
@jumde @bsclifton can you please determine if we should have this setting on Android?

If Yes, we can add it to the new menu https://github.com/brave/brave-browser/issues/7487

**Comment by jumde** [comment]
sgtm

**Comment by anthonypkeane** [comment]
@karenkliu can you suggest a place for this in the new menu?

@alexsafe if doable, can you add follow up and add this while working on the menu?

Thanks

**Comment by bsclifton** [comment]
This toggle has been removed; Chromecast enabled by default on Android. I'm not sure if this makes sense or is possible to disable on Android

See https://github.com/brave/security/issues/574 for more info

**Comment by arijoon** [comment]
> This toggle has been removed; Chromecast enabled by default on Android. I'm not sure if this makes sense or is possible to disable on Android
> 
> See https://github.com/brave/security/issues/574 for more info

I understand the issue is old, but is there a reason even the option was removed on android? (the link leads to 404)

**Comment by bsclifton** [comment]
@arijoon as far as I know there never was a toggle on Android (only on Desktop). Are you saying it used to be there?

When I mentioned it's enabled by default on Android I mean at the OS level

**Comment by arijoon** [comment]
> @arijoon as far as I know there never was a toggle on Android (only on Desktop). Are you saying it used to be there?
> 
> When I mentioned it's enabled by default on Android I mean at the OS level

Thanks, I misunderstood then and assumed there was a toggle but then removed due to a security issue.
