### ISSUE TITLE
[Desktop] Normalize Rewards TOS text

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#13936]
The Rewards TOS text differs in various places. On the NTP, it is `By clicking [button text], ...`, whereas on the onboarding UI it is `By proceeding, ...`. Update all occurrences of the Rewards TOS to match `By proceeding, ...`.

cc @jenn-rhim

**Comment by mkarolin** [comment]
This looks to have been fixed already:

<img src='https://user-images.githubusercontent.com/41635752/212418637-da5c17b1-86f8-4b32-834e-ec907f79e0c8.jpg' width='40%'/>
