### ISSUE TITLE
Session restore can have tabs that don't restore in this particular case

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13932]
Very similar to https://github.com/brave/brave-browser/issues/13519 but posting with slightly different steps which still doesn't work right after https://github.com/brave/brave-browser/issues/13519 is fixed.

## Description 

If you have multiple ipfs:// or ipns:// URLs open in the background (with 1 being active), usually at least one of them will not load and will show the interstitial page when selected. Note, you don't actually need to use the public gateway, just refreshing the page will show the content. 

## Steps to Reproduce

pre-req: have IPFS installed
   1. open the following 3 ipfs/ipns pages such as: `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`, `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/`, `ipns://k2k4r8oj77eqrr4018u3qjk2byycrz4pmxyodaruuqv4zvph6foed004/`
   3. Select the middle tab
   4. Relaunch
   5. While the active IPFS tab is loading, click the other 2.

## Actual result:

Usually at least one of the tab titles will show "IPFS Not Connected". Clicking on one of these shows the interstitial page.

Example where 1 tab did not connect after relaunch:
<img width="1032" alt="1 not connected" src="https://user-images.githubusercontent.com/28145373/104364290-693fd600-54e4-11eb-9edf-29279e112937.png">

## Expected result:
ipfs should connect for all applicable pages

## Reproduces how often: 

not 100%, but occurred fairly often, about 85% reproducible

## Brave version (brave://version info)

Brave | 1.19.81 Chromium: 87.0.4280.141 (Official Build) dev (x86_64)
-- | --
Revision | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS | macOS Version 10.15.7 (Build 19H15)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @LaurenWags

**Comment by stephendonner** [comment]
The issue still reproduces in 

Brave | 1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

New issue for that (rather than reopening) is https://github.com/brave/brave-browser/issues/14328, so adding QA Pass - macOS for this one (as per team's process).

**Comment by LaurenWags** [comment]
removing `release-notes/include` and adding `release-notes/exclude` as issue is still occurring per follow up issue logged by @stephendonner
