### ISSUE TITLE
Private window's search provider don't use normal windows' when prefs is turned off

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#1393]
## Description 

When alternative search engine prefs turned off, private window uses normal window's search engine provider.

When user changes provider from settings, private window should use it if this prefs turned off after private profile is created.

## Steps to Reproduce

   1. Launch browser
   2. Open private window and turn off ddg
   3. Change search engine provider from settings
   4. Check private windows' search engine provider is same with normal windows'

## Actual result:

Private windows' search engine provider isn't changed

## Expected result:
Private windows' should use same provider with normal windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7
