### ISSUE TITLE
Poor text visibility when hovering over account address [Crypto Wallets, Dark Theme]

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#13944]
## Steps to Reproduce
   1. Enable dark theme in `brave://settings`
   2. Set up Crypto Wallets, login, head to `brave://wallet`
   3. Hover over the account name in the index view to copy

## Actual result:
<img width="920" alt="Screen Shot 2021-02-03 at 2 39 41 PM" src="https://user-images.githubusercontent.com/8732757/106813662-8755ad80-662e-11eb-8f7f-9b7d9b78cd2f.png">

## Expected result:
<img width="674" alt="Screen Shot 2021-02-03 at 2 42 41 PM" src="https://user-images.githubusercontent.com/8732757/106813665-89b80780-662e-11eb-8b6e-6eebf14c6420.png">

## Reproduces how often: 
100%

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.92 Chromium: 88.0.4324.96 (Official Build) beta (64-bit)
--  | --
Revision | `68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}`
OS | Linux
Component | `1.0.23 Dev`


- Verified text is visible when browser theme is set to dark![image](https://user-images.githubusercontent.com/17010094/107332099-9cf22980-6aab-11eb-85ef-ed8ca91b31e4.png)
---------
Verification passed on

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Windows 10 OS Version 2009 (Build 19042.746)
Component | `1.0.23 Dev`

- Verified text is visible when browser theme is set to dark![image](https://user-images.githubusercontent.com/17010094/107332148-b09d9000-6aab-11eb-8c1c-8ff82b2b8638.png)
---------
Verification passed on

Brave | 1.22.6 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
-- | --
Revision | `2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.23 Dev`

- Verified text is visible when browser theme is set to dark
![image](https://user-images.githubusercontent.com/17010094/107332168-bbf0bb80-6aab-11eb-9853-d46b52e05587.png)
