### ISSUE TITLE
Show 'X' (close) button on small tabs on macOS

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#13946]
## Description 

Currently, hover to show the 'X' button on inactive tabs is disabled on narrow browser widths even when individual tabs still have a lot of room to display the button. This is causing unnecessary friction and usability issues for users who find they have to click on an inactive tab before being able to close it. 

## Steps to Reproduce

   1. Open up several tabs in a browser
   2. Make the browser width narrower
   3. See that hovering on an inactive tab does not display the 'X' button anymore even though there is enough space to show it

## Actual result:

'X' button stops appearing at this tab width:

<img width="96" alt="Screen Shot 2021-02-03 at 4 45 06 PM" src="https://user-images.githubusercontent.com/2388823/106828623-6ba6d300-663f-11eb-9277-bce272073673.png">

## Expected result:
Show 'X' button on hover until tab width is equal to the favicon + the close button. 
![image](https://user-images.githubusercontent.com/2388823/106829195-83cb2200-6640-11eb-889a-689eea130729.png)

Narrower than that, don't show the 'X' button on hovering an inactive tab.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

all channels/versions

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards?  N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by nullhook** [comment]
> Show 'X' button on hover until tab width is equal to the favicon + the close button

with alert indicator now moving next to the favicon here: https://github.com/brave/brave-browser/issues/16860 

this doesn't take into consideration the alert indicators. currently the constraint is: `kMinimumContentsWidthForCloseButtons = 68` anything below the value won't show the close button.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/9445

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.29.12 Chromium: 92.0.4515.101 (Official Build) nightly (x86_64)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | macOS Version 11.4 (Build 20F71)

Steps:

1. opened up several tabs in a browser
2. made the browser width narrower
3. saw that hovering on an inactive tab, before the fix, does not display the 'X' button anymore even though there is enough space to show it (easiest to put the browsers side-by-side)

Confirmed that, after the fix, there's an `x` button to the right of the favicon

before | after
-------|------
<img width="775" alt="Screen Shot 2021-07-20 at 4 35 50 PM" src="https://user-images.githubusercontent.com/387249/126408331-b580d4d0-8efe-47de-ba20-1b8a55182a31.png"> | <img width="771" alt="Screen Shot 2021-07-20 at 4 33 10 PM" src="https://user-images.githubusercontent.com/387249/126408371-f6eaf808-4770-4492-a3f7-d500ed65d1bd.png">
