### ISSUE TITLE
Ad search results are not hidden

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#13947]
## Description 

We don't hide Ad search results in cosmetic filters when aggressive mode is on in adblock

## Steps to Reproduce

   1. Go to duckduckgo.com
   2. Search for example for `samsung galaxy tab`
   3. Observe Ad search results
![Screenshot from 2021-02-03 21-33-56](https://user-images.githubusercontent.com/12011303/106836648-90af3c00-6667-11eb-96be-4eca36e34b1b.png)
   4. Turn on `Trackers & ads blocked (aggresive)` in shields

## Actual result:

Observe Ad search results

## Expected result:
There are no Ad search results

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified using the inline testplan, on

Brave | 1.22.6 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | macOS Version 11.2 (Build 20D64)

Steps:
1. load `duckduckgo.com`
2. search for `samsung galaxy tab`
3. confirm ads still display with default Shields settings
4. choose `Trackers & ads blocked (aggressive)` from Shields settings
5. repeat steps 1 & 2
6. verify ads disappear, and counter for `Trackers & ads blocked (aggressive)` doesn't increment

![image](https://user-images.githubusercontent.com/387249/107272014-ea19c100-6a01-11eb-863c-f7830ea0c37a.png)

![image](https://user-images.githubusercontent.com/387249/107272003-e84ffd80-6a01-11eb-9ac1-a1141664f0fa.png)

**Comment by srirambv** [comment]
@SergeyZhukovsky is this issue specific to Desktop or needs to be tested on Android as well?

**Comment by SergeyZhukovsky** [comment]
@srirambv it's desktop specific only. We don't have aggressive mode in shields for Android currently.

**Comment by kjozwiak** [comment]
@stephendonner we're going to need to QA this again in `1.21.x` as @SergeyZhukovsky requested uplifts via https://github.com/brave/brave-core/pull/7829/. I'll use your Nightly verifications https://github.com/brave/brave-browser/issues/13947#issuecomment-775402403 for the uplift as we usually always check the PRs on Nightly before uplifting. Looks like it's working 👍

**Comment by kjozwiak** [comment]
Merged into `1.21.x` via as per https://github.com/brave/brave-core/pull/7829#pullrequestreview-586181908.

**Comment by stephendonner** [comment]
@kjozwiak thanks, and apologies for prematurely marking, then.

Verified `FIXED` again using `1.21.50` with the inline testplan:


Brave | 1.21.50 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2.1 (Build 20D74)

<img width="927" alt="Screen Shot 2021-02-10 at 11 17 33 AM" src="https://user-images.githubusercontent.com/387249/107560132-d43b0600-6b91-11eb-970d-dfb340253a30.png">
<img width="927" alt="Screen Shot 2021-02-10 at 11 17 49 AM" src="https://user-images.githubusercontent.com/387249/107560135-d604c980-6b91-11eb-9863-10f174a1b1a5.png">
