### ISSUE TITLE
Sometimes the rewards tour is initialized twice

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#13945]
This happens after user takes the tour through `Take a quick tour` and after the tour clicks `Start using Brave Rewards`

Note: the second tour can be skipped

## Steps to Reproduce

1. Clean profile
1. Open Rewards Panel
1. Click `Take a quick tour`
1. Go through the tour
1. Click `Start using Brave Rewards`

## Actual result:

The tour is initiated again
![rewards tour](https://user-images.githubusercontent.com/34715963/106823229-d9bfba00-6680-11eb-836a-ece80d07387d.gif)

## Expected result:
The tour is not initiated again

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.20.97 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

cc @zenparsing @rebron @brave/legacy_qa

**Comment by LaurenWags** [comment]
cc @codybanxs

**Comment by codybanxs** [comment]
I will create a new issue but in this case if a user goes through 'take a tour' and immediately goes through the 'Start using Brave Rewards' we should only show the last two slides that setup a users Rewards preferences for the second time.

**Comment by zenparsing** [comment]
Thanks @codybanxs ! No need to create a new issue, we can just use this one to track.
