### ISSUE TITLE
Make ddg search engine provider enable in guest window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#1394]
## Description 

DDG setting doesn't work in guest window

## Steps to Reproduce

   1. Open guest window
   2. Turn on ddg in ntp
   3. Check ddg is used

## Actual result:

ddg isn't used

## Expected result:
search engine provider should be ddg when ddg prefs is turned on

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7
