### ISSUE TITLE
Slow and unresponsive new tab

### ISSUE THREAD

**Issue by lazabalint** [brave/brave-browser#13941]
After opening a new tab in Brave, typing an URL into the URL bar it shows empty URL bar and doesn't load the page.

   1. Have several (~10) tabs already open in Brave (not hardware issue, no problems in Chrome)
   2. Hit Control + T
   3. start typing as soon as the cursor (automatically) reaches the url bar 
   4. hit enter

## Actual result:
nothing happens. url bar blank, no new page loaded
you have to retype the url and hit enter again

## Expected result:
open the url

## Reproduces how often: 
Often

## Brave version
1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
@lazabalint do you have more information about your setup? Which OS/version are you running? 

If you're on a newer macOS M1 machine, I'd try to download a newer copy to ensure you're using the arm64 version

**Comment by lazabalint** [comment]
> @lazabalint do you have more information about your setup? Which OS/version are you running?

Issue still presists.
OS: Windows 10 1909 18363.1440
Brave: Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)

> 
> If you're on a newer macOS M1 machine, I'd try to download a newer copy to ensure you're using the arm64 version
> 

> I've tried on macOS and Windows and haven't been able to reproduce. Do you have new tab configured to open a specific site? or just default behavior?

This is the default behavior

**Comment by jgdhs27** [comment]
I had a similar problem that seemed to be caused by using hardware acceleration with radeon graphics cards. https://www.reddit.com/r/Amd/comments/f8uw1w/psa_to_anyone_having_problems_with_hardware/ might be what you need.

**Comment by lazabalint** [comment]
hi,
it seems, that the latest update fixed this, thank you.
I messed a bit with the settings, @jgdhs27 mentioned (thank you), without success. for now switched back to defaults and it works (after ~1 hour of testing)

**Comment by lazabalint** [comment]
Nevermind, it's back again... 

Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-bit)

**Comment by rotigithub** [comment]
Same issue here both on my mac and my pc. 
Latest Brave on both machine.

**Comment by lazabalint** [comment]
Issue fixed - but I don't know exactly how.
@jgdhs27 was right, this should be a Radeon issue. 
I've bought a new monitor, and messed up some settings, so I removed the drivers (and related programs) with AMD Cleanup Utility. 

After that (and after more restarts...), Windows Update automatically (re?)installed Driver Update - _Advanced Micro Devices - MEDIA - 11/16/2017 - 12:00:00 AM - 10.0.1.6._

And the issue is gone.

**Comment by yasirroni** [comment]
> I removed the drivers (and related programs) with AMD Cleanup Utility.
> 
> After that (and after more restarts...), Windows Update automatically (re?)installed Driver Update - _Advanced Micro Devices - MEDIA - 11/16/2017 - 12:00:00 AM - 10.0.1.6._
> 
> And the issue is gone.

I can confirm that this is worked! Now, Brave become more responsive to.
