### ISSUE TITLE
[Followup to #12390] Translations missing for default browser modal 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13958]
## Description 
[Followup to #12390] Translations missing for default browser modal 

## Steps to reproduce 

   1. Set locale to Deutch
   2. Clean install 1.20.98 and trigger default browser modal
   3. Text is not translated

## Actual result 
Default browser modal shows in English for non-EN locales

## Expected result
Translated strings

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.20.98

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc; @mkarolin @anthonypkeane @kjozwiak

**Comment by bsclifton** [comment]
Moved to 1.21 - we'll be able to submit/pull translations with Chromium 89 in 1.21 😄 We can keep issue open until we do the order

**Comment by bsclifton** [comment]
Closing - going to remove this feature from 1.20. For 1.21, we will order translations so this should be sorted 👍

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.102 x64 build
- Verified default browser onboarding is translated 

**Japanese**

![image](https://user-images.githubusercontent.com/17010094/107353087-8b694b80-6ac4-11eb-87a8-75ad326d5665.png) | ![image](https://user-images.githubusercontent.com/17010094/107353101-902dff80-6ac4-11eb-9da9-5568f3a3ee07.png) | ![image](https://user-images.githubusercontent.com/17010094/107353109-92905980-6ac4-11eb-9762-1efb02a41c53.png)
-- | -- | --

**French**

![image](https://user-images.githubusercontent.com/17010094/107353226-b5227280-6ac4-11eb-84f1-a1bf511e8663.png) | ![image](https://user-images.githubusercontent.com/17010094/107353242-bbb0ea00-6ac4-11eb-9870-c6461ba270c0.png) | ![image](https://user-images.githubusercontent.com/17010094/107353251-bfdd0780-6ac4-11eb-9d58-56294464caf5.png)
-- | -- | --

**German**

![image](https://user-images.githubusercontent.com/17010094/107353161-a340cf80-6ac4-11eb-82f6-6d05764c3f97.png) | ![image](https://user-images.githubusercontent.com/17010094/107353186-ab007400-6ac4-11eb-8d55-47e95d5d2945.png) | ![image](https://user-images.githubusercontent.com/17010094/107353177-a8058380-6ac4-11eb-8a35-d5ccf4b3d142.png)
-- | -- | --

--------
Verification passed on Samsung Tab A with Android 10 running 1.20.102 x64 build
- Verified default browser onboarding is translated 

**Spanish**

![image](https://user-images.githubusercontent.com/17010094/107354302-e51e4580-6ac5-11eb-94e1-76e714df788d.png) | ![image](https://user-images.githubusercontent.com/17010094/107354315-e8b1cc80-6ac5-11eb-9c39-3419c926a244.png) | ![image](https://user-images.githubusercontent.com/17010094/107354321-eb142680-6ac5-11eb-9225-78f15a135193.png)
-- | -- | --

**Korean**

![image](https://user-images.githubusercontent.com/17010094/107354353-f49d8e80-6ac5-11eb-9c74-423e3acaf5b7.png) | ![image](https://user-images.githubusercontent.com/17010094/107354367-f9fad900-6ac5-11eb-8708-f240c27218fb.png) | ![image](https://user-images.githubusercontent.com/17010094/107354379-fcf5c980-6ac5-11eb-8cb8-d792aff52f0c.png)
-- | -- | --
