### ISSUE TITLE
Google ads not blocked and cannot block with custom filters

### ISSUE THREAD

**Issue by forgetso** [brave/brave-browser#1395]
## Description 
Google paid for ads continue to appear in search

## Steps to Reproduce
   1. Visit Google
   2. do a search
   3. ads are displayed
   4. create a filter to block them 
```
##.ads-ad
##div[aria-label^="Ad"]
##tads
```
   5. ads are still not blocked

## Expected result:
Ads will be blocked

## Reproduces how often: 
Every search

## Brave version (chrome://version info)
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by rebron** [comment]
Fixed in brave-core. There's a cosmetic filter using right click to address this issue.
