### ISSUE TITLE
YouTube embedded link triggers crypto wallet

### ISSUE THREAD

**Issue by NightProwler-dc** [brave/brave-browser#13956]
## Description 

When I paste an embed youtube link in the url bar and launch it, brave's crypto wallet pops up asking me whether to start it. 
I found it suspicious because the link was from an email. I then tried any youtube link but found that it always triggered the crypto wallet.

## Steps to Reproduce

   1. Find a youtube video and copy its link, e.g. https://www.youtube.com/watch?v=rokGy0huYEA
   2. Copy its code
   3. paste the embed link in brave url and go : https://www.youtube.com/embed/rokGy0huYEA

## Actual result:
Crypto wallet would pop up and ask to start

## Expected result:
Crypto wallet should not pop up in this case.

## Desktop Brave version:

V1.19.88

**Comment by bsclifton** [comment]
Reproduced - thanks for sharing 😄 
![image](https://user-images.githubusercontent.com/4733304/107002221-bd368700-673f-11eb-85a9-98c77fc2e6b0.png)

I'm curious if there's a web3 element being exposed? or why it shows
cc: @bbondy

**Comment by bbondy** [comment]
Only for embed sub-paths I guess right? We're going to remove this detection completely soon.

**Comment by bbondy** [comment]
This will be fixed by: https://github.com/brave/brave-browser/issues/14018

**Comment by bbondy** [comment]
Closing in favor of #14018
