### ISSUE TITLE
brave not blocking ads on arch linux

### ISSUE THREAD

**Issue by jedi2610** [brave/brave-browser#13959]
## Description 

brave not blocking ads on linux after updating to `Version 1.19.90 Chromium: 88.0.4324.146 (Official Build) unknown (64-bit)` on linux despite the ad blocker being turned on.

## Steps to Reproduce

go to youtube or any other site with ads and brave doesn't block them

## Brave version (brave://version info)

`Version 1.19.90 Chromium: 88.0.4324.146 (Official Build) unknown (64-bit)` linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes

the irony:
![image](https://user-images.githubusercontent.com/30691152/106912157-c49e6600-6728-11eb-896b-32f43ced9869.png)

**Comment by bsclifton** [comment]
There are a few reasons this might be happening. Can you check a few things @jedi2610?

1. If you visit brave://components/, you should see `Brave Ad Block Updater` and it should have a value that isn't 0.0.0.0. You can click update if needed

2. If that doesn't help, you can enable regional filters. Visit brave://adblock/ and add the list for your region

3. If neither of those work, I would check the arch-linux package you're on. There are two: one is from source (this won't work; I think package is `brave`) and the other is repackaging the Linux installs we do (this will work; I think package is `brave-bin`).

**Comment by jedi2610** [comment]
well the version is 
`Brave Ad Block Updater - Version: 1.0.836
Status - Component not updated` so it's not `0.0.0.0`. and i'm currently using the `brave-bin` package from `AUR` so i don't think that's an issue too. can you point me to the list of filters?

**Comment by jedi2610** [comment]
it magically started working today. and now the page looks like this. idk what's happening smh
![image](https://user-images.githubusercontent.com/30691152/107024710-6330d280-67ce-11eb-8d1f-12558165e328.png)

**Comment by bsclifton** [comment]
Interesting - maybe it just took a while to download the blocking list?

Let me know how it goes over the next few days. I'll close this ticket for now - but if you experience problems again, please share here and I can re-open it
