### ISSUE TITLE
Github "Tip" tooltip not showing on mouse over

### ISSUE THREAD

**Issue by georapbox** [brave/brave-browser#13957]
## Description 
When placing the mouse cursor over the "Tip" button located under the contributions grid of a user's profile, a tooltip with label "Send a tip should appear". Instead only the arrow of the tooltip appears, the tooltip itself seems to be hidden behind another element.

![bat_tooltip](https://user-images.githubusercontent.com/6596039/106884346-e0364c00-66e9-11eb-8c45-cbdea9831fc8.gif)

## Steps to Reproduce
   1. Navigate to a Github user's profile
   2. Place your mouse cursor over the "Tip" button under the contributions grid

## Actual result:
The tooltip with label "Send a tip" is hidden behind another element.

## Expected result:
The tooltip should be visible to the user.

## Reproduces how often: 
Always

## Brave version (brave://version info)

Version 1.19.90  Chromium: 88.0.4324.146 (Official Build)  (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by JFrankfurt** [comment]
Another related github BAT icon issue: 

![image](https://user-images.githubusercontent.com/5773490/108130368-8c2e4e80-707d-11eb-816b-f77549433fdd.png)

**Comment by georapbox** [comment]
Also, `Uncaught (in promise) Error: Failed to parse DOM` exception is thrown when clicking on the "Tip" button.

![Screenshot 2021-03-12 at 3 28 03 PM](https://user-images.githubusercontent.com/6596039/110946633-c79ffe00-8347-11eb-9cbe-b9ebece548ff.png)

**Comment by emerick** [comment]
I'm not able to repro this, if we're still seeing this problem please update with a new set of repro steps - thank you!

**Comment by LaurenWags** [comment]
Verified using dev component for:

```
Brave Local Data Updater - Version: 1.0.601
```

Tip button no longer displays in this area:

<img width="746" alt="Screen Shot 2022-08-04 at 11 35 32 AM" src="https://user-images.githubusercontent.com/28145373/182887967-5e1fc343-5b96-4c15-8a25-18a3022d0097.png">

Confirmed spot checking other areas where Tip button does display on GH pages that it shows the tooltip as expected:

Example | Example
-- | --
<img width="815" alt="Screen Shot 2022-08-04 at 11 37 42 AM" src="https://user-images.githubusercontent.com/28145373/182888331-95e916ef-d873-40c0-b01d-6bf247ca990c.png"> | <img width="836" alt="Screen Shot 2022-08-04 at 11 38 31 AM" src="https://user-images.githubusercontent.com/28145373/182888475-5b7b7461-c643-4a48-be28-8690b0e2dbb8.png">
