### ISSUE TITLE
Only fetch publisher list when rewards enabled

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1397]
## Steps to Reproduce

   1. clean profile
   2. start browser with verbose enabled

## Actual result:

publisher list is fetched

## Expected result:
nothing should happen

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@NejcZdovc in the absence of verbose mode, is it sufficient to launch Brave with clean profile, use Little Snitch to ensure publishers.basicattentiontoken.org is not called, and then enable Brave Rewards and see that publishers.basicattentiontoken.org is then called (similar to https://github.com/brave/brave-browser/issues/972#issuecomment-430391390)
