### ISSUE TITLE
Missing translations for educational modals

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13988]
## Description 
Missing translations for educational modals

## Steps to reproduce 

   1. Set device locale to non-EN region
   2. Install 1.20.x build
   3. Trigger educational modals, shows in English instead of device locale 

## Actual result 
Educational modals are not translated

## Expected result
Educational modals should be translated

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.20.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @mkarolin @anthonypkeane @bsclifton @kjozwiak

**Comment by bsclifton** [comment]
We should be able to close this once we get the translations back for 1.20 - I'll put into milestone even though we're waiting for Transifex

**Comment by kjozwiak** [comment]
Going to close this off as per https://github.com/brave/brave-browser/issues/13988#issuecomment-773819924. Once we get builds with translations, we'll run through the above and ensure that it's translated.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.102 x64 build
- Verified educational tooltips are translated

**French**

![image](https://user-images.githubusercontent.com/17010094/107380825-23c3f800-6ae6-11eb-88fe-219d8580a380.png) | ![image](https://user-images.githubusercontent.com/17010094/107380849-2a526f80-6ae6-11eb-9fdd-f9be0e77fdfc.png) | ![image](https://user-images.githubusercontent.com/17010094/107380873-2f172380-6ae6-11eb-856b-3b91e3f930bf.png) | ![image](https://user-images.githubusercontent.com/17010094/107380885-32121400-6ae6-11eb-8f54-99b0d52b93ff.png)
-- | -- | -- | --

**German**

![image](https://user-images.githubusercontent.com/17010094/107380957-40f8c680-6ae6-11eb-8436-a90b30d21706.png) | ![image](https://user-images.githubusercontent.com/17010094/107380998-4c4bf200-6ae6-11eb-9ade-02a4c962a0b3.png) | ![image](https://user-images.githubusercontent.com/17010094/107381007-50780f80-6ae6-11eb-8d8f-f95459ebbb37.png) | ![image](https://user-images.githubusercontent.com/17010094/107381024-54a42d00-6ae6-11eb-82ac-773e99b6359b.png)
-- | -- | -- | --

---------
Verification passed on Samsung Tab A with Android 10 running 1.20.102 x64 build
- Verified educational tooltips are translated

**Japanese**

![image](https://user-images.githubusercontent.com/17010094/107383151-9d5ce580-6ae8-11eb-9cc9-4f9152344b9d.png) | ![image](https://user-images.githubusercontent.com/17010094/107383177-a5b52080-6ae8-11eb-9105-766db5d58660.png) | ![image](https://user-images.githubusercontent.com/17010094/107383197-abab0180-6ae8-11eb-8163-cdff06bd1920.png) | ![image](https://user-images.githubusercontent.com/17010094/107383212-af3e8880-6ae8-11eb-8383-ffedd56e9101.png)
-- | -- | -- | --

**Spanish**

![image](https://user-images.githubusercontent.com/17010094/107383260-bb2a4a80-6ae8-11eb-88c6-5ee7fdbbc810.png) | ![image](https://user-images.githubusercontent.com/17010094/107383272-bfeefe80-6ae8-11eb-8fb0-0cfe032de7a4.png) | ![image](https://user-images.githubusercontent.com/17010094/107383306-c8473980-6ae8-11eb-9c25-49e4b0d7edb5.png) | ![image](https://user-images.githubusercontent.com/17010094/107383327-cbdac080-6ae8-11eb-9dd6-41d38a8cf33a.png)
-- | -- | -- | --
