### ISSUE TITLE
Link VPN stats with Brave Stats on the NTP

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#13983]
## Description 

Please see GDrive "Brave VPN on iOS  - V2" for more info.

Add the ability to link the VPN blocked trackers to the NTP Stats

- [ ] Develop design
- [ ] Implement
- [ ] QA

Please upload final screenshots here once dev completed to aid QA

Linked to: https://github.com/brave/brave-ios/issues/3264

**Comment by bsclifton** [comment]
Closing as stale - but cc: @mattmcalister as this is a cool idea 😄 

Guardian has some stats available via API where we can get a count of items THEY have blocked (at the network level). @anthonypkeane can share more info on that. We could supplement the stats on NTP potentially.
