### ISSUE TITLE
Don't show default browser prompt if other brave channel is already set as a default

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#13980]
If stable channel is already default browser, other channel should not display default browser prompt.

**Comment by kjozwiak** [comment]
@simonhong does this include `Win`? Or is this specifically for `macOS` & `Linux`? If it's for all platforms, we can remove the `OS/Linux` & `OS/macOS` labels and just keep `OS/Desktop` so it gets checked on all three.

**Comment by simonhong** [comment]
@kjozwiak This PR is only for mac/linux because we already have cross channel checking logic for Windows.

**Comment by btlechowski** [comment]
`QA/Blocked` as we also need `release` channel build

**Comment by btlechowski** [comment]
No longer `QA/Blocked` as we have a 1.21.x release build.

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.21.68 Chromium: 89.0.4389.58 (Official Build) (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.2 (Build 20D80)

Verified the testplan from https://github.com/brave/brave-core/pull/7841.

Verified default-browser prompt is **not** shown when:
* Brave `release` is the default browser, launching `beta`, `dev`, `nightly`
* Brave `nightly`, `dev`, or `beta` is the default browser, launching `release` 

Verified default-browser prompt **is** shown when:
* Firefox is the default browser
* Chrome is the default browser
* Safari is the default browser

I also verified that when other Brave channels are set as default, the `Make default` button shows up in `release`, `brave://settings/` as it should.

<img width="829" alt="Screen Shot 2021-02-25 at 12 20 16 PM" src="https://user-images.githubusercontent.com/387249/109212272-29ffd880-7764-11eb-870a-eb5f2a935b18.png">
