### ISSUE TITLE
Add VPN Enabled Notification

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#13985]
## Description 

Please see GDrive "Brave VPN on iOS - V2" for more info.

Add VPN Enabled Notification

Notification

> Brave Firewall + VPN
> VPN is running in the background

Please upload final screenshots here once dev completed to aid QA

**Comment by srirambv** [comment]
Closing as the associated PR is merged https://github.com/brave/brave-core/pull/9874
