### ISSUE TITLE
Battery api should return constant result

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#1398]
## Test plan
See https://github.com/brave/brave-core/pull/567

## Description
We current disable the battery api, but that breaks some sites and if anything it is worse for privacy than fixing the value to 100%

**Comment by jumde** [comment]
After discussion with @tomlowenthal  - 

- This API has been deprecated in most browsers including Firefox, Safari and Edge. See here: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getBattery

- Fixing the value to 100% might have additional side-effects like sites running computationally intensive tasks if the battery is @ 100%.

**Comment by bridiver** [comment]
I don't care what value we use as long as we do something that doesn't break sites that try to use it because they think it's Chrome

**Comment by jumde** [comment]
Working on it, given that some extensions will also break on disabling this api. Going with 50 for now.

**Comment by bsclifton** [comment]
Uplifted to 0.55.x

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified steps from test plan on https://github.com/brave/brave-core/pull/567
![screen shot 2018-10-15 at 8 06 52 pm](https://user-images.githubusercontent.com/28145373/46986853-84ca9500-d0bf-11e8-984a-22af6b6a57f2.png)

**Comment by ksenginew** [comment]
brave is currently showing this result
