### ISSUE TITLE
Add VPN off "Timer"

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#13984]
## Description 

Please see GDrive "Brave VPN on iOS - V2" for more info.

Add the ability set a timer once a user turns off the VPN.

- [ ]  Develop design
- [ ]  Implement
- [ ]  QA

Please upload final screenshots here once dev completed to aid QA

Linked to: https://github.com/brave/brave-ios/issues/3265

**Comment by deeppandya** [comment]
Closing the issue as it's already done here : https://github.com/brave/brave-core/pull/21042
