### ISSUE TITLE
 Full-page onboarding modal is shown in 1.20.100 when 1.19.x is upgraded to 1.20.x with Ads OFF and AC ON

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13994]
## Description 

 Full-page onboarding modal is shown in 1.20.100 when 1.19.x is upgraded to 1.20.x with Ads OFF and AC ON

## Steps to Reproduce

   1. Install `1.19.90`
   2. Open the BR panel and click on `Start using Brave Rewards`
   3. Disable Ads on brave://rewards page and make sure AC is ON
   3. Update to `1.20.100`
   4. Open panel --> no onboarding (as expected)
   5. Navigate to brave://rewards page -->  full-page onboarding modal is shown in brave://rewards page instead of Rewards page with Ads OFF and AC ON as before upgrade is shown
  
## Actual result:

 Full-page onboarding modal is shown in 1.20.100 when 1.19.x is upgraded to 1.20.x with Ads OFF and AC ON
## Expected result:
Regular Rewards page with Ads OFF and AC ON should be shown after upgrade

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | Windows 10 OS Version 2004 (Build 19041.746)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @codybanxs @zenparsing @brave/legacy_qa

**Comment by zenparsing** [comment]
@codybanxs A fairly simple fix for 1.20.x would be to not show onboarding in this case if they have AC enabled. Would that be acceptable?

**Comment by LaurenWags** [comment]
cc @rebron on this one as well - not sure if release blocker for 1.20.x.

**Comment by Miyayes** [comment]
@GeetaSarvadnya Was this specific to upgrade from 1.19 to 1.20? If so, we can close it out.
