### ISSUE TITLE
Decrease height of download bar by showing source on hover

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#14007]
## Description 

Users are complaining about the download bar being too tall. Download may be integrated into sidebar in the future, but do a short term quick fix by only showing the source on hover.

## Steps to Reproduce

   1. Download anything
   2. See download appear in download bar
   3. Note the height

## Actual result:

![image](https://user-images.githubusercontent.com/2388823/107080182-c35f4e80-67a5-11eb-9112-70e700699bc8.png)

## Expected result:
Do not show the source by default: 
![image](https://user-images.githubusercontent.com/2388823/107079961-754a4b00-67a5-11eb-848d-29a68e47b4ce.png)

Show the only source on hover (source replaces the title):
![image](https://user-images.githubusercontent.com/2388823/107080122-ad518e00-67a5-11eb-8fe8-82a815d024bb.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

All versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by diracdeltas** [comment]
can this be merged into #1638 ?

**Comment by karenkliu** [comment]
Yes, good call. Let's close this as a dupe of #1638. I added the designs to that issue.
