### ISSUE TITLE
Poor text visibility in custom network warning [Crypto Wallets, Dark Theme]

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#14004]
## Steps to Reproduce
   1. Enable dark theme in `brave://settings`
   2. Set up Crypto Wallets, login, head to `brave://wallet`, navigate to network settings
   3. Hit `Add Network`

## Actual result:
<img width="1105" alt="Screen Shot 2021-02-05 at 9 55 15 AM" src="https://user-images.githubusercontent.com/8732757/107064253-8b054380-6798-11eb-92cb-6a436c6e70f6.png">

## Expected result:
<img width="1014" alt="Screen Shot 2021-02-05 at 9 53 25 AM" src="https://user-images.githubusercontent.com/8732757/107064270-8f316100-6798-11eb-89ee-7ea5978bdf2d.png">

## Reproduces how often: 
100%

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.92 Chromium: 88.0.4324.96 (Official Build) beta (64-bit)
--  | --
Revision | `68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}`
OS | Linux
Component | `1.0.23 Dev`

- Verified text is visible when browser theme is set to dark
![image](https://user-images.githubusercontent.com/17010094/107328411-9319f780-6aa6-11eb-96fa-3fb06088289d.png)
---------
Verification passed on

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Windows 10 OS Version 2009 (Build 19042.746)
Component | `1.0.23 Dev`

- Verified text is visible when browser theme is set to dark
![image](https://user-images.githubusercontent.com/17010094/107329087-93ff5900-6aa7-11eb-82b0-454a28ef90b7.png)
---------
Verification passed on

Brave | 1.22.6 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.23 Dev`

- Verified text is visible when browser theme is set to dark
![image](https://user-images.githubusercontent.com/17010094/107329637-53eca600-6aa8-11eb-8fc7-8133a8a9f48b.png)
