### ISSUE TITLE
webtorrent page goes blank and displays "loading..." when switching to another application

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1400]
## Description 

When switching context from Brave to another application, you'll notice that the webtorrent page will go completely blank and will only display `Loading....`. Once you switch back to Brave as the active application, the entire screen is re-painted.

## Steps to Reproduce

   1. launch either the latest `beta` or `dev`
   2. load https://webtorrent.io/torrents/big-buck-bunny.torrent in a new tab
   3. open Chrome and start switching back and forth between Chrome & Brave

You'll notice once you switch over to Chrome, the entire webtorrent page goes blank with only `Loading..` appearing.

## Actual result:

![loadingissue](https://user-images.githubusercontent.com/2602313/46374207-28e32380-c65e-11e8-985b-e6f230e06de2.gif)

<img width="1157" alt="screen shot 2018-10-02 at 3 25 04 pm" src="https://user-images.githubusercontent.com/2602313/46374508-d9512780-c65e-11e8-807b-6d132e4097bc.png">

## Expected result:

When switching between Brave and other applications, the `webtorrent` tab shouldn't go completely blank and display `Loading..`.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Currently reproducible on both `dev` and `beta` builds.

Brave | 0.56.1 Chromium: 70.0.3538.22 (Official Build) dev (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

- Does it reproduce on browser-laptop? 

Nope, this isn't reproducible under `0.24.0` which is the current `muon` live build.

### Additional Information

* @srirambv couldn't reproduce this under Win 10
* @btlechowski couldn't reproduce this under Win 7
* @LaurenWags also managed to reproduce this on macOS 10.12.6

**Comment by LaurenWags** [comment]
Verified passed on `macOS x64 10.12.6`

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta(64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified STR from description
cc @kjozwiak to verify on his macOS version as well
