### ISSUE TITLE
Youtube ads seen in Beta and Nightly

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#14013]
## Description 
Ads and cosmetics showing on youtube `https://www.youtube.com/watch?v=4glyJxHUfmw`  

## Steps to Reproduce

   1.  Load `https://www.youtube.com/watch?v=4glyJxHUfmw` in Beta/Nightly   (Shields standard or Aggressive)
   2. Refresh a few times
   3. Ads seen, also cosmetics not loading.

## Actual result:

![yt-issue](https://user-images.githubusercontent.com/1659004/107112539-4a531a80-68bd-11eb-959f-c4788e273aa3.png)

## Expected result:
Expect no ads, apply snippets and cosmetics.

## Reproduces how often: 

Seems to Easy in Beta and Nightly.

## Version/Channel Information:
   
Tested on `Version 1.22.6 Chromium: 89.0.4389.40 (Official Build) nightly (64-bit)`
`Version 1.21.44 Chromium: 88.0.4324.146 (Official Build) beta (64-bit)`

- Can you reproduce this issue with the current release?  No.
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
`Ephemeral Storage` makes no difference, no issues in Current Brave release. Shields standard or Aggressive makes no difference

cc: @antonok-edm

**Comment by ryanbr** [comment]
Also reported: https://community.brave.com/t/youtube-ads-in-video/202832

**Comment by ryanbr** [comment]
Some dissecting of Beta channel:

```
    Beta v1.20.85            Good
    Beta v1.20.89            Bad
```

**Comment by bsclifton** [comment]
Closing as a duplicate in favor of https://github.com/brave/brave-browser/issues/14073
