### ISSUE TITLE
Brave crashes trying to claim rewards

### ISSUE THREAD

**Issue by Sord1d** [brave/brave-browser#14016]
## Description 

When I try to claim the rewards on my Android phone brave shows the following message:

[https://sordiddev.eu/cloud/index.php/core/preview?fileId=1666&x=1920&y=1080&a=true](https://sordiddev.eu/cloud/index.php/core/preview?fileId=1666&x=1920&y=1080&a=true)

Shortly afterwards Brave crashes.

## Steps to reproduce 

   1. Click on the BAT icon in the address bar
   2. Click on claim
 

## Actual result 

The app crashes

## Expected result

Claiming the reward

## Issue reproduces how often 

It happens every time to me

## Version/Channel Information:

I am able to reproduce this issue with the Play Store version.
I'm not able to test it with either the beta version or the nightly version due to lacking pending rewards

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: HavocOS based on Android 10 without Google Play Services
   
//Edit: I've tested it with MicroG installed - same issue
   
## Brave version
 Brave 1.19.88
 //Edit: Same issue with Brave 1.19.92

### Additional information
Crash log:
time: 1612630707620
msg: Native crash: Segmentation fault
stacktrace: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/treble_arm64_bvN/phhgsi_arm64_ab:10/QQ3A.200705.002/200709:userdebug/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2021-02-06 17:58:27+0100
pid: 10010, tid: 10010, name: m.brave.browser  >>> com.brave.browser <<<
uid: 10223
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
Cause: null pointer dereference
    r0  ff7f1f38  r1  00000006  r2  ff7f1f08  r3  00000000
    r4  00000000  r5  ff7f1f38  r6  ff7f1f34  r7  ba993980
    r8  ff7f1f38  r9  ff7f1f70  r10 00000000  r11 bc017fc8
    ip  ead8bd14  sp  ff7f1ec8  lr  bd88c48b  pc  bca09cd6

backtrace:
      #00 pc 00b7ccd6  /data/app/com.brave.browser-yiA7Hp1Pu1NN9JFX0flN0g==/base.apk!libmonochrome.so (offset 0x5788000) (BuildId: 90f475b79c1041ac760c8f6e35a42a205b078693)

**Comment by agates** [comment]
Also getting this on GrapheneOS on Pixel 4a.

Brave 1.20.108

**Comment by ckyle6300** [comment]
Just has the same problem occur this month on GrapheneOS. I downloaded brave using the Aurora Store.

Brave version 1.20.108.412010820

**Comment by tsopanid** [comment]
Same on LineageOS.
Also downloades using Aurora Store.
MicroG instead of GAPPS.

**Comment by bloatmode** [comment]
Same on LineageOS for microG 17.1. using Brave 1.20.108. I also don't have Google Play Services and use microG instead (version 0.2.17.204714).

**Comment by tsopanid** [comment]
Still have the same issue.
Tried several updates, now on Brave version 1.22.71.

**Comment by Sord1d** [comment]
I tried to do some troubleshooting today.
I flashed an updated version of Havoc OS including Google Play services on my device.
Then I updated Brave via the Google Play Store.
Still having the same issue, so maybe not Google Play related ?
My phone is still rooted, might that cause the problem?

**Comment by iefremov** [comment]
cc @bsclifton @SergeyZhukovsky

**Comment by iefremov** [comment]
seems dupe https://github.com/brave/brave-browser/issues/15344
