### ISSUE TITLE
Video does not play

### ISSUE THREAD

**Issue by fukaki** [brave/brave-browser#14014]
I was able to watch GYAO movies before the Brave browser update
but I can no longer watch them in 1.19.92
Even if I disable the ad cut
I can't watch it. Is it a configuration issue?

Sherlock Holmes(GYAO!)
`https://gyao.yahoo.co.jp/episode/%E3%82%B7%E3%83%A3%E3%83%BC%E3%83%AD%E3%83%83%E3%82%AF%E3%83%BB%E3%83%9B%E3%83%BC%E3%83%A0%E3%82%BA%E3%80%80%E3%80%90%E5%AD%97%E5%B9%95%E7%89%88%E3%80%91/5fffff79-3b1e-4848-bd95-02f1ab8409c0`

Brave	1.19.92 Chromium: 88.0.4324.152 (Official Build) （64 bit）
change history	6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS	Windows 10 OS Version 1909 (Build 18363.1316)
JavaScript	V8 8.8.278.15
User agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36

Command line	"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,LegacyTLSEnforced,WinrtGeolocationImplementation,AutoupgradeMixedContent,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=TextFragmentAnchor,IdleDetection,AutofillServerCommunication,NetworkTimeServiceQuerying,PasswordCheck,AutofillEnableAccountWalletStorage,TabHoverCards,WebOTP,NotificationTriggers,PrivacySettingsRedesign,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end
Executable path	C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile path	C:\Users\fukaki\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

**Comment by MakerLiwei** [comment]
True, Brave has issues by reading movies. I reinstalled it on another laptop yesterday and I didn't get the issue anymore.
All movies were cut by a black screen between pictures.

But now, i can't reatore my existing wallet from seed. :-(

**Comment by rebron** [comment]
None of the videos on Yahoo! Japan seem to be working. Looks like running into the same issue in Chrome. 
`https://gyao.yahoo.co.jp/`

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Using a Japanese IP, checking in Brave, Brave Beta, Chrome and Firefox. None of the videos were able to be played. It seems to be serverside issue. Checking with another list author to confirm.

**Comment by fukaki** [comment]
The video viewing deadline was until the end of February.
I can watch it now.
I would like to express my appreciation for following.
