### ISSUE TITLE
Problem with my wallet

### ISSUE THREAD

**Issue by Mariiin9** [brave/brave-browser#14022]
## Description 
I got BATs for 3 months but only this month's BATs appear in my rewards tab of the Brave browser.

## Actual result:
![image](https://user-images.githubusercontent.com/78685329/107145359-38b35680-6941-11eb-813b-4f52590a559a.png)

**Comment by hollons** [comment]
Hi @Mariiin9, if this is still an issue for you please submit a ticket here - https://support.brave.com/hc/en-us/requests/new. 

Thanks!
