### ISSUE TITLE
Don't get my Tokens in Feb

### ISSUE THREAD

**Issue by LorisTecnology** [brave/brave-browser#14021]
## Description 
I Don't get my Tokens in Feb

## Actual result:
Tokens aren't in my wallet yet
## Expected result:
Tokens should got transfered to my Brave wallet

## Reproduces how often: 
this month
![image](https://user-images.githubusercontent.com/63395247/107144370-0c94d700-693b-11eb-8c24-c310d74b8413.png)
![image](https://user-images.githubusercontent.com/63395247/107144374-128ab800-693b-11eb-8dd5-6a51496001c4.png)

**Comment by thefallofbecause** [comment]
Payout is still in progress. You can follow it to see when everything is finished [here](https://community.brave.com/t/february-brave-ads-payout-status/202783).

**Comment by LorisTecnology** [comment]
Tokens successfully went to my Uphold wallet
