### ISSUE TITLE
Print dialog uses Google account for Cloud Print

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1402]
When I go to print in Brave and attempt to pick a printer, I'm shown printers that are shared with my Google account and I'm offered the option to save the image to my Google Drive instead of printing. This uses the account currently logged into Google, even though I haven't (and shouldn't be able to) log into the browser itself.

Instead, the browser should never show info about Google accounts, never connect to Google, and otherwise not display any Google-ish integration.

<img width="1000" alt="screen shot 2018-10-02 at 3 19 15 pm" src="https://user-images.githubusercontent.com/639937/46380397-f1bd4400-c656-11e8-85d2-cf703edf8499.png">

<img width="1000" alt="screen shot 2018-10-02 at 3 24 22 pm" src="https://user-images.githubusercontent.com/639937/46380508-65f7e780-c657-11e8-8b03-b41515618385.png">

**Comment by jumde** [comment]
<img width="849" alt="screen shot 2018-10-04 at 2 26 53 pm" src="https://user-images.githubusercontent.com/1903815/46504172-f5310680-c7e1-11e8-8a79-015f48c43412.png">

`Adding Printers` navigates to `Google Cloud Print`.

**Comment by petemill** [comment]
## Test plans from duplicates

### Fresh profile (not signed in to accounts.google.com)
   1. Open any page and press <kbd>Ctrl</kbd>+<kbd>P</kbd>
   2. Brings up the print dialogue
   3. Click on Change to select available printers
   4. Device page shows Cloud print and has a sign in button which tries to connect to `no-thanks.invalid` 

### Already signed in to a Google website

- Visit print preview
- Change printer
- Expected: signed-in google accounts do not show in a list

**Comment by petemill** [comment]
## Comparison whilst signed-in to google.com

### Before
![image](https://user-images.githubusercontent.com/741836/46967938-dbf04b80-d066-11e8-93d6-d44322f7a7d7.png)


### After
![image](https://user-images.githubusercontent.com/741836/46967967-f296a280-d066-11e8-91a0-ccd470278755.png)

**Comment by petemill** [comment]
@jumde I can't replicate your addition to this issue for `chrome://devices` at https://github.com/brave/brave-browser/issues/1402#issuecomment-427176545? Can you confirm and post as separate issue, if it's still present? Thanks

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified signed-in google accounts isn't listed
* Verified connected cloud printers isn't listed
* Verified "Save to Google Drive" printer isn't listed
* Verified "Save to PDF" is listed

![image](https://user-images.githubusercontent.com/17010094/47059487-97180200-d197-11e8-8e26-dc0d8b600189.png)
