### ISSUE TITLE
Update l10n for Android for 1.20.x

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#14039]
Get the latest l10n for Android for 1.20.x release.

**Test plan:**

Selectively verify l10n for the following strings:

<pre>
* Select Brave Browser and tap 'Always'
* We detected that you have Brave Sync enabled, however your system sync is turned off and will not allow Brave to sync. Press to open settings
* Don't show again
* Trackers & ads blocked on this page.
* Brave Shields just protected your privacy.
* Ads are blocked while watching videos on this website.
* Videos without ads use less data.
* 10+ trackers &amp; ads blocked on this page.
* Brave Shields protects your online privacy on every site.
* Your connection is now encrypted.
* If available, Brave upgrades you to a secure connection automatically.
* After you receive your first ads payout you can come back and tip this creator!
* Open all links with Brave to protect your privacy
* Brave Shields blocks trackers &amp; ads, saves data, and saves you time on every site you visit.
* Set Brave as default
* Brave Rewards in Japan is switching to a new system!
* Please use your BAP by March 13th. After that, BAP will be discontinued.
* The tipping feature will be unavailable from March 13th until April 13th. All BAPs will be discontinued by April 13th. Please use your BAP by March 13th. Any BAP remaining in your Brave browser after March 13th cannot be held or transferred by you or Brave, and will be lost. A new and improved system awaits!
</pre>

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/7868 & https://github.com/brave/brave-core/pull/7868 were merged.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.102 x64 build
- Verified strings are translated 
- https://github.com/brave/brave-browser/issues/13988#issuecomment-776009942
- https://github.com/brave/brave-browser/issues/13958#issuecomment-775856409
- ---------
Verification passed on Samsung Tab A with Android 10 running 1.20.102 x64 build
- Verified strings are translated 
- https://github.com/brave/brave-browser/issues/13988#issuecomment-776009942
- https://github.com/brave/brave-browser/issues/13958#issuecomment-775856409
