### ISSUE TITLE
Google OAuth Problem Logging in when Shields are Up

### ISSUE THREAD

**Issue by jamesmortensen** [brave/brave-browser#1403]
## Steps to Reproduce

   1.  Go to Pinterest
   2. Try to Login with Google Oauth
   3.  Observe that a blank popup window appears and you cannot login

## Actual result:

<img width="1023" alt="screen shot 2018-10-03 at 1 01 16 pm" src="https://user-images.githubusercontent.com/1315816/46396454-1a077a00-c70d-11e8-9d04-cf7cf1dd280d.png">

I observe there is some problem related to CORS.  Why does this not work in Brave but does in other browsers?

## Expected result:
The expected result is that I should be logged into Pinterest.  Note that the same thing happens on other sites where I use Google Oauth.  I don't remember them at the moment but can update this ticket as I discover them.

## Reproduces how often: 

Easily reproduced, at least for me.

## Brave version (chrome://version info)

It says the chrome://version url is invalid.  But here is what I got from the About section:

Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Not sure
- Does it reproduce on browser-laptop?  Not sure what this means as it says that is an old repo....

## Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? YES! It works in this case if I lower the shields.
- Is the issue reproducible on the latest version of Chrome?  No. Chrome works without issues.

### Additional Information

Unrelated, but Whatsapp has trouble loading in Brave sometimes.  It says it can't connect to the Internet even though it's connected.  I see websocket error messages in the console logs and lowering the shields does NOT help.

**Comment by srirambv** [comment]
This repository is for the new [Brave-Browser](https://brave.com/download-beta). Looks like the issue you are reporting is for browser-laptop which will be deprecated soon. You can download the latest [brave beta](https://brave.com/download-beta) and verify if this issue is fixed.
