### ISSUE TITLE
Rpill Brave Ads

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#14036]
Summary of the issue can be found via https://github.com/brave-intl/bat-reputation/issues/192. Just a heads up to @brave/legacy_qa, we don't have access to that repo so we'll just need to follow the STR/cases mentioned below. Should have been tagged in a Slack thread as well that has some more context.

### STR/Test Cases:

Can be found via https://github.com/brave/brave-core/pull/7446#issue-540636302

**Comment by kjozwiak** [comment]
@brave/legacy_qa verification notes should go into https://github.com/brave/internal/issues/751.

**Comment by kjozwiak** [comment]
Added QA/verification notes via https://github.com/brave/internal/issues/751#issuecomment-775623679.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.20.101 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Windows 10 OS Version 2004 (Build 19041.746)

```
- Verified the issue via https://github.com/brave/internal/issues/751#issuecomment-775734983
