### ISSUE TITLE
Privacy stats onboarding covers the bottom half of the stats widget

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14034]
## Description 
Privacy stats onboarding covers the bottom half of the stats widget

## Steps to reproduce 

   1. Install 1.20.100 
   2. View privacy stats onboarding
   3. covers the bottom part of the stats widget

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/107216654-fbb09800-6a04-11eb-84db-d47ffbf36c18.png>

## Expected result
Should probably not cover the stats window 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.20.100

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Issue on bigger screen phone so would probably be worse on small screen phones
Found while testing #11939

**Comment by deeppandya** [comment]
@srirambv @bsclifton  i think we can close this issue based on the discussion here : https://bravesoftware.slack.com/archives/C0816QH3R/p1612785691187800

**Comment by bsclifton** [comment]
Per discussion on Slack, this is expected behavior
