### ISSUE TITLE
Tapping on Bookmark doesn't remove it 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14033]
## Description 
[Follow up to #11939] As per the issue description 

> Bookmarking icon
> Someone thought tapping Bookmark icon again would unbookmark the page; instead it took them to edit the bookmark. Let’s fulfill user’s expectations and un-bookmark the page when tapping on the Bookmark icon again.

This still doesn't work. Tapping on bookmark icon again brings up the edit modal rather than removing the bookmark

## Steps to reproduce 

   1. Install 1.20.100 
   2. Visit a page and add it as bookmark
   3. Tap the bookmark icon again, brings up edit bookmark instead of removing it

## Actual result 
Tapping on bookmark button doesn't remove it

## Expected result
Should remove it as it was one of the user feedback that was to be implemented

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.20.100

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @karenkliu @deeppandya @anthonypkeane

**Comment by deeppandya** [comment]
@samartnik @SergeyZhukovsky this issue seems to be the regression as BookarkUtils got updated here : https://chromium-review.googlesource.com/c/chromium/src/+/2548686

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.102 x64 build
- Verified tapping on bookmark removes the bookmark
- Verified able to edit and delete the bookmark
- Verified no crash when tapping on bookmark button to add/remove bookmark

https://user-images.githubusercontent.com/17010094/107348272-b486dd80-6abe-11eb-93c3-3bc35e36ed28.mp4


--------
Verification passed on Samsung Tab A with Android 10 running 1.20.102 x64 build
- Verified tapping on bookmark removes the bookmark
- Verified able to edit and delete the bookmark
- Verified no crash when tapping on bookmark button to add/remove bookmark

https://user-images.githubusercontent.com/17010094/107348438-ea2bc680-6abe-11eb-8c11-db4de025d4c2.mp4
