### ISSUE TITLE
Sometimes tooltips get stacked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14040]
## Description 
Sometimes tooltips get stacked

## Steps to reproduce 

   1. Install 1.22.8
   2. Change orientation to landscape
   3. Visit amazon.com (type in do not use autocomplete)
   4. Wait for a few seconds tooltips stack up

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/107260686-48f92d80-6a36-11eb-9ffd-2fd428e41ac0.png)

## Expected result
Should not stackup 

## Issue reproduces how often 
NA

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.22.8

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

### Additional information

Was using VPN so not sure if VPN caused it

**Comment by deeppandya** [comment]
@srirambv @bsclifton this issue would be fixed in https://github.com/brave/brave-browser/issues/13995 as it's happening because of the time we show the tooltips.

**Comment by kjozwiak** [comment]
> @srirambv @bsclifton this issue would be fixed in #13995 as it's happening because of the time we show the tooltips.

Closing as this should be resolved by https://github.com/brave/brave-core/pull/7862 as per the above.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.102 x64 build
- Verified tooltips don't stack up 
- -------
Verification passed on Samsung Tab A with Android 10 running 1.20.102 x64 build
- Verified tooltips don't stack up
