### ISSUE TITLE
Enhance Tor process cleanup with __OwningControllerProcess and TAKEOWNERSHIP

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#14044]
We currently rely on cleaning orphaned Tor process by pidFile when launching the new Tor process

And we can prevent orphaned Tor process by launching Tor with option `__OwningControllerProcess` plus utility process pid and when control connection established send `TAKEOWNERSHIP` so no matter how we crash Brave browser process or kill utility process, there shouldn't be any orphaned Tor process left
https://github.com/torproject/torspec/blob/d3a4dadac149c2be162344a6c2286653b8ac3753/control-spec.txt#L1525

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build

Brave | 1.23.23 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.3 (Build 20D91)

Verified both test cases from the plan in https://github.com/brave/brave-core/pull/7927:

**Case 1: Browser process crashed**

1. Open Tor window
2. Make sure tor-* process is running, the process name is platform dependent.
3. In normal window, type `chrome://inducebrowsercrashforrealz/` in URL bar
4. Browser should crash and tor-* process should no longer exist

<details>
<summary>screencast</summary>
<img src="https://user-images.githubusercontent.com/387249/110402136-b0070380-802f-11eb-8e8e-ed25be8cbf6a.gif">
</details>

**Case 2: Kill Tor launcher utility process**

1. Open Tor window
2. Make sure tor-* process is running, the process name is platform dependent and remember its pid
3. Open Task Manager in Brave
4. Kill Tor Launcher
5. A new tor-* process should be spawned which should have different pid than step 2
6. Enter `https://brave5t5rjjg3s6k.onion/` in URL bar
7. The onion site should be loaded normally
8. Close Tor window and tor-* process should no longer exist
9. 

<details>
<summary>screencast</summary>
<img src="https://user-images.githubusercontent.com/387249/110402726-c1044480-8030-11eb-949b-d293de4f76cf.gif">
</details>

**Comment by stephendonner** [comment]
Hi @darkdh - do you think this should be tested on all supported desktop platforms?  If so, we can add the `QA/Test-all-platforms` tag; thanks!

**Comment by darkdh** [comment]
yep, we should test it on all desktop platforms
