### ISSUE TITLE
Hotfix for GHSA-c2xw-px2x-pr65

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14043]

**Comment by ryanml** [comment]
Verified that switching networks still works correctly by sending transactions on Ropsten, Rinkeby, and Mainnet. Verified custom network addition works:
<img width="1084" alt="Screen Shot 2021-02-12 at 10 41 30 AM" src="https://user-images.githubusercontent.com/8732757/107802729-f746f080-6d1e-11eb-9a58-3cb5e1c53b16.png">
