### ISSUE TITLE
Sync code should be empty when Brave can't use OSCrypt to decrypt sync seed

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#14046]
## Description 

Root cause
https://github.com/brave/brave-core/blob/ff38812fd7e099c52b9d31af7b7476c68330679b/components/sync/driver/brave_sync_profile_sync_service.cc#L55
https://github.com/brave/brave-core/blob/ff38812fd7e099c52b9d31af7b7476c68330679b/components/brave_sync/brave_sync_prefs.cc#L113

## Steps to Reproduce

   1. Create sync chain and exit Brave
   2. Lock `login` in keychain on macOS
   3. Launch Brave and refuse to enter password to unlock keychain
   4. Click "View sync code" in sync page

## Actual result:

Sync code would be a newly generated sync code every time you refresh sync page and click "View sync code"

## Expected result:
Sync code should be empty

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome?  n/a

**Comment by AlexeyBarabash** [comment]
These merged PRs handle the issue
[Sync warn keyring locked #14224](https://github.com/brave/brave-core/pull/14224)
[Propose clear data and re-join sync chain when impossible to decrypt the sync seed #16117](https://github.com/brave/brave-core/pull/16117)

So I am closing the current.
