### ISSUE TITLE
 Schedule builds and tests for each PR commit and each commit to master.

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1405]
Schedule builds and tests for each PR commit and each commit to master.

I think these builds should be "debounced per branch", so that it's impossible to have a growing queue forever for any single queue. 

That means that not every commit on master for example will be built, but that we will build as fast as possible.

**Comment by mihaiplesa** [comment]
Currently looking at Jenkins pipelines as a way to implement this https://go.cloudbees.com/docs/cloudbees-documentation/cje-user-guide/index.html#github-branch-source

**Comment by mihaiplesa** [comment]
Added the following Jenkins jobs:
https://staging.ci.brave.com/view/ci/job/brave-browser-build-master/
https://staging.ci.brave.com/view/ci/job/brave-browser-build-pr/view/change-requests/
https://staging.ci.brave.com/view/ci/job/brave-core-build-pr/view/change-requests/
