### ISSUE TITLE
STOP THAT GIF! (Conference T-Shirt Template)

### ISSUE THREAD

**Issue by supersexy** [brave/brave-browser#14056]
Brave on Linux. I can not stop GIFs playing.

Test on giphy.com or any gif collection site.

This is such a great feature to FORCE (presidential big letters!) gif playback on users - I feel like we are in 1998 now with such a great problem from the past. It is like the beginning of the internet times. 

I tried to install all gif stopper extensions I could find, no change, gifs still playing. Google Animation Policy, Stop Gif, not much more to be found nowadays. 

Yes, of course I set autoplay to stop for all sites - it even shows me the autoplay setting is "not autoplay" but still it does autoplay.

Only ublock origin as additional extension, but no change if activated or not.

Brave is an interesting project - but please prioritize these extremely basic things... thanks! I know, you did not invent all that horrible mess we have with HTML, JavaScript and all the animation image formats... but, hmm, wait a minute.... well... hmmm... OK, maybe this is bad karma hitting you hard, Brendan? Or is it a secret plan to make us all really watch all the GIFs?

It has to stop. Meanwhile, back to Firefox...

**Comment by rebron** [comment]
Closing. This functionality is available as extensions for example: https://chrome.google.com/webstore/detail/gif-blocker/ahkidgegbmbnggcnmejhobepkaphkfhl?hl=en
