### ISSUE TITLE
`epsilon_greedy_bandit_arms` isn't displaying expected values for Brave Ads time out

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14054]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/13395
epsilon_greedy_bandit_arms isn't displaying expected values for Ads Time out
## Steps to Reproduce

   1. Clean profile 1.20.x launch brave using the cmd line provided in test plan https://github.com/brave/brave-core/pull/7533#issue-550917989
   2. Enable rewards
   3. View an AD, Don't take any action on the Ads notification wait until Ads timeout
   4. Open the Preference file from the profile folder
   5. `Pull` value is displayed as `0` and `value` is displayed as `1.0` which is incorrect
   
## Actual result:

`Pull` value is displayed as `0` and `value` is displayed as `1.0` which is incorrect

Please note this is just an example issue is happening for all the segments not only for `military`
```
,\"military\":{\"pulls\":0,\"segment\":\"military\",\"value\":1.0},
```

## Expected result:
the timeout should be treated exactly the same as dismiss, the vaues should be `pull` = 1 and `value` = 0.0

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.20.101 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Windows 10 OS Version 2004 (Build 19041.746)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @moritzhaller @jsecretan @rebron

**Comment by tmancey** [comment]
@GeetaSarvadnya We cannot reproduce this issue, can you please retest. Thanks

**Comment by GeetaSarvadnya** [comment]
@tmancey Just tested the issue again issue is still reproducible in 1.25.x . Please let me know if you need more details.

```
Brave | 1.25.57 Chromium: 90.0.4430.93 (Official Build) beta (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2004 (Build 19041.985)

```

**Comment by btlechowski** [comment]
@tmancey still reproducible on 

Brave | 1.42.74 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Ubuntu 18.04 LTS



![image](https://user-images.githubusercontent.com/34715963/180246764-a0810474-a97f-4d66-9af7-ad28274c8030.png)


Since there is no PR associated I will reopen the issue and move it out of 1.42.x milestone

**Comment by tmancey** [comment]
@btlechowski, we found https://github.com/brave/brave-browser/issues/23978, which would be the cause of this issue. @aseren is working on a fix. @aseren can you please move this issue back to QA once you have resolved 23978. Thanks
