### ISSUE TITLE
PDF downloaded TWICE when first viewing in Browser and then downloading

### ISSUE THREAD

**Issue by supersexy** [brave/brave-browser#14057]
Seems like a little thing, but do this on big PDFs on a bad connection and it will make you cry because you are wasting so much time that you could spend with your lover... the PDF viewed in the browser is already on my machine - why are you downloading it again? Go and test with 

https://psref.lenovo.com/syspool/Sys/i_pdf/psref500.pdf

This very small Asian company ventures in very slow pdf generator test servers, they do a lot to make the download simulate extremely bad conditions - with this project you can see the download painfully start again after clicking the download button of the PDF viewer - on my endpoint more than five minutes! Haha, this company is also building real hardware that simulates really slow computers... well, ok, I am distracting (because distracted by another pdf download). Time wasting in action. You feel how painful it is to waste other peoples time? Good demonstration!

This waste of human time must stop - we need more time for spreading LOVE!

**Comment by rebron** [comment]
Hi @supersexy You can go to brave://settings/content/pdfDocuments?search=pdf and turn on this setting if you want to download pdfs instead of viewing first. We are viewing the .pdf and caching but not downloading/saving the file to your system.
