### ISSUE TITLE
Click on `Additional settings` isn't expanding/collapsing the settings in brave://settings/safetyCheck page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14065]
## Description 

Click on `Additional settings` isn't expanding/collapsing the settings in brave://settings/safetyCheck page

## Steps to Reproduce

   1. Clean or upgraded profile 1.22.x
   2. Open brave://settings/safetyCheck page
   3. Click on `Additional settings`
   4. Click on `Additional settings` isn't expanding/collapsing the settings in brave://settings/safetyCheck page

## Actual result:

Click on `Additional settings` isn't expanding/collapsing the settings in brave://settings/safetyCheck page
![Additional settings](https://user-images.githubusercontent.com/38657976/107389446-ca2af000-6b1c-11eb-8778-1c5836fab935.gif)

## Expected result:
Click on `Additional settings` should expanding/collapsing the settings in brave://settings/safetyCheck page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.22.9 Chromium: 89.0.4389.40 (Official Build) nightly (64-bit)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | Windows 10 OS Version 2004 (Build 19041.746)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bbondy

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build 

Brave | 1.22.34 Chromium: 89.0.4389.48 (Official Build) nightly (x86_64)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | macOS Version 11.2.1 (Build 20D74)

Steps:
1. opened `brave://settings/safetyCheck`
2. clicked on the triangle to the right of the `Additional settings` link, center-bottom
3. verified that the panel can be expanded/collapsed, and is collapsed, by default
![additional-settings](https://user-images.githubusercontent.com/387249/108427316-d33d5080-71f1-11eb-9430-b87456e4f320.gif)
