### ISSUE TITLE
Wallet gets disabled on subsequent restarts now that it installs as an extension and not a component

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14068]
## Description 

After you install the wallet, and then restart, the wallet extension is disabled.
I think we need to whitelist it somewhere. 

I think it was introduced by this issue: https://github.com/brave/brave-browser/issues/13279

<img width="454" alt="Screen Shot 2021-02-09 at 11 14 21 AM" src="https://user-images.githubusercontent.com/831718/107394532-fec18c00-6ac9-11eb-8423-f191cbe0f83b.png">

## Steps to Reproduce

   1. Fresh profile
   2. Go to brave://wallet and install the extension
   3. Go to settings and turn on the setting "Load Crypto Wallets on startup"
   4. Restart
   5. Go to about://extensions

## Actual result:
<img width="354" alt="Screen Shot 2021-02-09 at 11 26 24 AM" src="https://user-images.githubusercontent.com/831718/107394834-4516eb00-6aca-11eb-8370-32cb2c1fdaa6.png">

## Expected result:
It should allow the extension to be loaded.

## Reproduces how often: 
Always as long as you're using a fresh profile that installed originally as an extension.

## Brave version (brave://version info)
1.20.x

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel?  yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | `6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}`
OS | Linux

- Verified upgrading from 1.19.92 to 1.20.100 caused the issue
- Verified disabling CW at startup still allowed to load the CW and login on 1.20.100
- Verified upgrading to 1.20.103 fixes the issue 
- Verified upgrading from 1.19.92 to 1.20.103 doesn't cause any issue with loading/login to CW when CW is not set to load on startup
- Verified upgrading from 1.19.92 to 1.20.103 with CW set to load on startup doesn't cause any issue with CW
-----------
Verification passed on 

Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | `6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}`
OS | Windows 10 OS Version 2009 (Build 19042.746)

- Verified upgrading from 1.19.92 to 1.20.100 caused the issue
- Verified disabling CW at startup still allowed to load the CW and login on 1.20.100
- Verified upgrading to 1.20.103 fixes the issue
- Verified upgrading from 1.19.92 to 1.20.103 doesn't cause any issue with loading/login to CW when CW is not set to load on startup
- Verified upgrading from 1.19.92 to 1.20.103 with CW set to load on startup doesn't cause any issue with CW
-----------
Verification passed on

Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)
-- | --
Revision | `6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}`
OS | macOS Version 10.15.7 (Build 19H114)

- Verified upgrading from 1.19.92 to 1.20.100 caused the issue
- Verified disabling CW at startup still allowed to load the CW and login on 1.20.100
- Verified upgrading to 1.20.103 fixes the issue 
- Verified upgrading from 1.19.92 to 1.20.103 doesn't cause any issue with loading/login to CW when CW is not set to load on startup
- Verified upgrading from 1.19.92 to 1.20.103 with CW set to load on startup doesn't cause any issue with CW
--------
Logged followup issues #14082, #14083
