### ISSUE TITLE
Move Brave Wallet into its own settings section

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14069]
## Description

The extensions section of brave://settings is overused and cluttered. This issue is to move Crypto Wallets out into its own section.

## Designs

Ignore the Tor parts of the image, they are tracked by https://github.com/brave/brave-browser/issues/13688
![image](https://user-images.githubusercontent.com/2388823/106826083-09e46a00-663b-11eb-962c-74a544ae9a90.png)

## Assets
Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/?node-id=359%3A9749

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.22.55 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Windows 10 OS Version 2009 (Build 19042.804)

- Verified test plan from https://github.com/brave/brave-core/pull/7895
- Verified enabling `Load Crypto Wallet at startup` loads the process upon browser launch
 
<details>
<summary>Wallet</summary>

![image](https://user-images.githubusercontent.com/17010094/110638838-ef0b9500-81a6-11eb-8386-dc72c71f47b9.png) | ![image](https://user-images.githubusercontent.com/17010094/110639357-896bd880-81a7-11eb-9220-8bbc855f7835.png)
-- | --

</details>

------
Verification passed on 

Brave | 1.22.55 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Linux

- Verified test plan from https://github.com/brave/brave-core/pull/7895
- Verified enabling `Load Crypto Wallet at startup` loads the process upon browser launch
 
<details>
<summary>Wallet</summary>

![image](https://user-images.githubusercontent.com/17010094/110642703-2b40f480-81ab-11eb-81b3-f1dfcccfbd43.png) | ![image](https://user-images.githubusercontent.com/17010094/110642869-5deaed00-81ab-11eb-9c88-4d59e8471e76.png)
-- | --

</details>

----------
Verification passed on 

Brave | 1.22.55 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | macOS Version 10.15.7 (Build 19H114

- Verified test plan from https://github.com/brave/brave-core/pull/7895
- Verified enabling `Load Crypto Wallet at startup` loads the process upon browser launch
 
<details>
<summary>Wallet</summary>

![image](https://user-images.githubusercontent.com/17010094/110642970-7955f800-81ab-11eb-885b-099160ede3c4.png) | ![image](https://user-images.githubusercontent.com/17010094/110643166-b5895880-81ab-11eb-9646-616ace818e95.png)
-- | --
</details>

--------
Logged #14619 as a follow up
