### ISSUE TITLE
Settings sidebar doesn't have shortcuts for `Sync`, `New Tab Page`, `Shields`, and  `Social Media Blocking` in 1.22.x

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14062]
## Description 

Settings sidebar doesn't have shortcuts for `Sync`, `New Tab Page`, `Shields`, and  `Social Media Blocking` in 1.22.x

## Steps to Reproduce

   1. Clean or upgraded profile 1.22.x
   2. Navigate to brave://settings
   3. Settings sidebar doesn't have shortcuts for `Sync`, `New Tab Page`, `Shields`, and  `Social Media Blocking` in 1.22.x

## Actual result:

Settings sidebar doesn't have shortcuts for `Sync`, `New Tab Page`, `Shields`, and  `Social Media Blocking` in 1.22.x
![image (9)](https://user-images.githubusercontent.com/38657976/107388557-f98d2d00-6b1b-11eb-9242-4b4375efb6be.png)

## Expected result:
Settings sidebar should have shortcuts for `Sync`, `New Tab Page`, `Shields`, and  `Social Media Blocking` in 1.22.x

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.22.9 Chromium: 89.0.4389.40 (Official Build) nightly (64-bit)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | Windows 10 OS Version 2004 (Build 19041.746)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bbondy

**Comment by stephendonner** [comment]
Verified `FIXED` in `nightly` using the testplan from https://github.com/brave/brave-core/pull/7895                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with

Brave | 1.22.34 Chromium: 89.0.4389.48 (Official Build) nightly (x86_64)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | macOS Version 11.2.1 (Build 20D74)

Steps:
1. made sure the `Settings` sections are back from brave/brave-browser#14062
2. made sure the crypto wallets (`brave://settings/wallet`) settings still work
3. made sure things are ordered correctly:
`New Tab Page`
`Sync`
`Shields`
`Social media blocking`
...
`Wallet Settings` (sic)
<img width="1338" alt="Screen Shot 2021-02-18 at 2 59 36 PM" src="https://user-images.githubusercontent.com/387249/108432923-fe2ba280-71f9-11eb-8efc-683a1eb8860b.png">
<img width="1338" alt="Screen Shot 2021-02-18 at 2 59 46 PM" src="https://user-images.githubusercontent.com/387249/108432929-fff56600-71f9-11eb-88d5-c55fdff5f287.png">

4. checked both `dark` and `light` themes

<img width="1117" alt="Screen Shot 2021-02-18 at 2 39 48 PM" src="https://user-images.githubusercontent.com/387249/108432437-32529380-71f9-11eb-9673-407df171d161.png">
<img width="1117" alt="Screen Shot 2021-02-18 at 2 54 54 PM" src="https://user-images.githubusercontent.com/387249/108432629-8b222c00-71f9-11eb-9408-20f89082e711.png">
