### ISSUE TITLE
Configure Brave Ads next payment date from variations seed

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#14067]

**Comment by btlechowski** [comment]
`QA/Blocked` as the issue has no test plan.

**Comment by kjozwiak** [comment]
> At this time we just need to make sure the next payment date matches previously releases, i.e. 5th or 6th depending on timezone. We will test the seed when we need to make a change.

@tmancey added the above case via https://github.com/brave/brave-core/pull/7894. For now, we just need to make sure that the payment date matches the previous release after upgrading.

**Comment by srirambv** [comment]
Verification passed on One Plus 6T with Android 10 running 1.22.58 x64 beta build
- Verified next payment date matches previous release
- Logged #14683 which is a known issue
-----------
Verification passed on Samsung Tab A with Android 10 running 1.22.58 x64 beta build
- Verified next payment date matches previous release
- Encountered #14683 which is a known issue

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.22.58 Chromium: 89.0.4389.86 (Official Build) beta (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Ubuntu 18.04 LTS

Verified next payment date matches previous release
Verified test plan from https://github.com/brave/internal/issues/759
Verified the date was changed to 2nd:
![image](https://user-images.githubusercontent.com/34715963/111978195-f1a1af00-8b03-11eb-82b4-25bdb0b25220.png)
