### ISSUE TITLE
`Trackers & Ads Blocked` on NTP is cropped in Polish (PL) locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14075]
## Steps to reproduce 

   1. Open NTP is Polish locale

## Actual result 
`Trackers & Ads Blocked` on NTP is cropped in Polish (PL) locale
![image](https://user-images.githubusercontent.com/34715963/107415536-c8106380-6b13-11eb-8004-9a3e0717da5b.png)
![Screenshot_20210209-200634_Brave](https://user-images.githubusercontent.com/34715963/107415576-d2caf880-6b13-11eb-9990-7aa5dd069fd2.jpg)

## Expected result
`Trackers & Ads Blocked` on NTP is not cropped 

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet):Tablet
   - Android version: 9.0
   
## Brave version
Brave v1.20.102 on Samsung Galaxy Tab S5e (Android 9.0)

cc @SergeyZhukovsky @deeppandya @samartnik @brave/legacy_qa

**Comment by deeppandya** [comment]
@jamesmudgett should i add scroll in text ? what do you suggest ?

**Comment by TheAresjej** [comment]
> @jamesmudgett should i add scroll in text ? what do you suggest ?

**translation can be changed to:**  _Zablokowanych reklam_ 😋

**Comment by deeppandya** [comment]
@btlechowski would you please check this issue if it's still relevant ?

**Comment by btlechowski** [comment]
Verification passed on Brave v1.48.151 on Lenovo TB-8506FS (Android 11.0)

No longer reproducible.

![image](https://user-images.githubusercontent.com/34715963/216692679-10aaef41-5323-43f0-8536-1f34ad5dd737.png)
![image](https://user-images.githubusercontent.com/34715963/216692810-466ce1fa-1605-4e1b-8acd-cc0f4d7e1047.png)
