### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by zashkvarr11** [brave/brave-browser#14079]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.19.92  Chromium: 88.0.4324.152
Operating System: Windows NT 10.0.19042

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/7c420000-5c00-d105-0000-000000000000

**Comment by iefremov** [comment]
the backtrace entry is dead. @zashkvarr11 please file a new issue if you ever encounter this again
