### ISSUE TITLE
[Android] Don't show default browser prompt if other brave channel is already set as a default

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#14078]
Currently we show set brave as default browser in all channels i.e. release, beta and nightly. So this issue is to set the behaviour If brave's any channel is already set as a default browser, the other installs should not show any options for default browser.
For context, related issue for desktop : https://github.com/brave/brave-browser/issues/13980

**Note** : 
Whenever we install any app with an intent of being a web browser, android system resets the default selection. So let's say if nightly was already a default browser, and if you install beta, android system would reset the default selection as it considers that we are installing new browser because we are not happy with previous selection.

**Comment by srirambv** [comment]
> So this issue is to show set brave as default modal only on release channel;.

@deeppandya should it only show for Release channel or similar to desktop it should not prompt if one of the channel is set as default?

**Comment by deeppandya** [comment]
> > So this issue is to show set brave as default modal only on release channel;.
> 
> @deeppandya should it only show for Release channel or similar to desktop it should not prompt if one of the channel is set as default?

@srirambv i have updated the issue to be in sync with desktop implementation.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.68 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/7955

https://user-images.githubusercontent.com/17010094/109181755-32680b80-7784-11eb-9dee-f19a527eee36.mp4

-----------
Verification passed on OnePlus 6T with Android 10 running 1.21.68 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/7955

https://user-images.githubusercontent.com/17010094/109181990-6fcc9900-7784-11eb-9228-0488d228adf1.mp4
