### ISSUE TITLE
both ad & skip ad overlay not being blocked YouTube

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#14073]
## Description 

When viewing YT, you'll notice that sometimes the `ads` and `skip ad` overlays are being displayed even though Brave has blocked the ad from being displayed. As per @SergeyZhukovsky, this currently only affects `1.22.x` (Nightly) & `1.21.x` (BETA) channels. However, this should get fixed before `1.21.x` hits the release channel so labeling this as `release/blocking`.

## Steps to Reproduce

   1. launch brave and visit https://www.youtube.com (used `1.22.9 CR: 89.0.4389.40` in this case)
   2. view several clips and eventually you'll see the `ads` & `skip ad` overlay even though ads are being blocked

## Actual result:

![Screenshot 2021-02-05 043800](https://user-images.githubusercontent.com/2602313/107409925-a5ae2400-6ada-11eb-9da2-7f5b4d25f66e.png)

## Expected result:

Brave shouldn't be displaying the overlays and should be playing content right away.

## Reproduces how often: 

It's hard to say but happens pretty often in Nightly for me.

## Desktop Brave version:

```
Brave | 1.22.9 Chromium: 89.0.4389.40 (Official Build) nightly (64-bit)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | Windows 10 OS Version 2009 (Build 19042.746)
```

## Android Device details:
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 11`

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No` (N/A as per @SergeyZhukovsky)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @bsclifton @SergeyZhukovsky @BrendanEich @srirambv

**Comment by SergeyZhukovsky** [comment]
I used that video and able to consistently replicate the ads problem https://www.youtube.com/watch?v=xXMW9VNMPT4&feature=youtu.be

**Comment by stephendonner** [comment]
Verified `FIXED` on macOS 11.2.1 (Big Sur); I left `YouTube` playing all morning long (while logged out, with Shields up), and didn't see this crop up, using 

Brave | 1.21.62 Chromium: 88.0.4324.182 (Official Build) beta (x86_64)
-- | --
Revision | 73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS | macOS Version 11.2.1 (Build 20D74)

**Comment by stephendonner** [comment]
Apologies; looks like I missed the use-case of logged-in, regular (i.e. no "YouTube Premium") account, which is now covered by https://github.com/brave/brave-browser/issues/14359, I believe.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.70 x64 build
- Verified no ads shown on YT videos
- Verified no ad overlay is shown 
- Verified https://github.com/brave/brave-browser/issues/14073#issuecomment-776908579 as well and didn't see any ad
- Verified no ads shown with/without sign in to YT 
------------
Verification passed on Samsung Tab A with Android 10 running 1.21.70 x64 build
- Verified no ads shown on YT videos
- Verified no ad overlay is shown 
- Verified https://github.com/brave/brave-browser/issues/14073#issuecomment-776908579 as well and didn't see any ad
- Verified no ads shown with/without sign in to YT
