### ISSUE TITLE
wallet extension missing description and appears as "MSG_appDescription"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#14070]
## Description 

Looks like we're missing the description for the wallet extension and are showing `MSG_appDescription` instead. We should probably be adding a description into the extension.

## Steps to Reproduce

   1. launch brave and visit `brave://wallet` (`1.20.102 CR: 88.0.4324.152` in this case)
   2. click on `I understand` and wait till the wallet is installed/laoded
   3. visit `brave://extensions` and notice the missing description

## Actual result:

![image](https://user-images.githubusercontent.com/2602313/107396969-40533680-6acc-11eb-8f02-26e1ae4bda65.png)

![image](https://user-images.githubusercontent.com/2602313/107397037-506b1600-6acc-11eb-895e-7775c28af950.png)

## Expected result:

We should be adding some type of description string so there's context for users re: what the extension is for.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.20.102 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Windows 10 OS Version 2009 (Build 19042.746)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (never appearing in brave://extensions)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by srirambv** [comment]
This was an issue on Muon as well. This is not just limited to Crypto Wallet but also for Shields for App Name
![image](https://user-images.githubusercontent.com/17010094/107516421-4e748600-6ba4-11eb-8a35-b04b94077dc0.png)

**Comment by ryanml** [comment]
OS: MacOS
Component Version: 1.0.26 dev

The description has been removed
<img width="445" alt="Screen Shot 2021-02-12 at 10 49 31 AM" src="https://user-images.githubusercontent.com/8732757/107803610-1003d600-6d20-11eb-8649-2cec0d462c69.png">
