### ISSUE TITLE
"Show All" tap target needs more vertical padding

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14088]
## Description 

The "Show All" link which appears for 6 or more Auto-Contribute sites in `chrome://rewards/contribute` is a hard tap target to hit, due to very minimal padding between it and the bottom toolbar.

## Steps to reproduce 

   1.  new profile, enable Rewards (& Auto-Contribute with it, by default)
   2.  browse 6 or more sites for at least 8 seconds each
   3.  open `chrome://rewards/contribute`
   4.  swipe down
   5.  try to tap the "Show All" link

## Actual result 

It's a bit hard for me to accurately tap the "Show All" target link, due to missing vertical padding between it and the bottom toolbar.

## Expected result

Should be a little more room in-between the bottom toolbar and the "Show All" target link.

## Issue reproduces how often 

100%?  Depends on size of your finger, and accuracy :-)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? **yes**
- Can you reproduce this issue with the current Play Store Beta version? **yes**
- Can you reproduce this issue with the current Play Store Nightly version? **yes**

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone; Google Pixel 1 XL
   - Android version: 9.0
   
## Brave version

Brave Nightly `1.22.13`, Chromium 89.0.4389.40

![view all text needs padding](https://user-images.githubusercontent.com/387249/107545401-16f3e280-6b80-11eb-82b8-730f457f582c.png)

/cc @karenkliu since it's in a similar vein as https://github.com/brave/brave-browser/issues/13835

**Comment by karenkliu** [comment]
cc @jamesmudgett

**Comment by karenkliu** [comment]
@deeppandya Is there any way you can add a bit of bottom padding to this link?

**Comment by deeppandya** [comment]
@karenkliu we still have this page in javascript and it would be resolved when we have native UI for rewards settings page. Can we wait till then ? or should i update ?

**Comment by karenkliu** [comment]
If the native UI is coming soon we can probably just wait until then.

**Comment by bsclifton** [comment]
> If the native UI is coming soon we can probably just wait until then.

Perfect! Will be trying to get this prioritized ASAP. Likely we'll have an owner in March 😄

**Comment by Miyayes** [comment]
Fixed by new Rewards page changes.
