### ISSUE TITLE
Rename QA Preference for Clarity

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#14095]
## Description 
We currently have a QA preference on Android called "[enable vlog for rewards](https://github.com/brave/brave-core/blob/80e31db3398a4f1ce5b81d081b0b8e1f7d1f9030/android/java/res/xml/qa_preferences.xml#L38)," which can sound a bit confusing. It sounds as though a user could _enable a video-blog for additional rewards_, and was interpreted as such by [a user on twitter](https://twitter.com/iamujjwaladitya/status/1359559724534927366).

I propose "Verbose Logs for Ad-Rewards," as a replacement. This avoids semantic confusion, and keeps the string no longer than the current longest label "Maximize Initial Ads Number," at 28 characters.

## Brave version
1.19.92

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.22.54 beta build
- Verified test plan from https://github.com/brave/brave-core/pull/7922
----------
Verification passed on OnePlus 6T with Android 10 running 1.22.54 beta build
- Verified test plan from https://github.com/brave/brave-core/pull/7922
