### ISSUE TITLE
BAP cutoff date isn't correctly detected

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14092]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/13701 / https://github.com/brave/brave-core/pull/7698

Unable to claim staging UGP grant when in Japan region.

## Steps to Reproduce

   1. Clean profile on Nightly w/ region = Japan and staging env
   2. Click on Rewards icon and enable Rewards
   3. No UGP grant.

## Actual result:

No UGP grant is offered. See the below in logs:

```
[7846:775:0210/113532.139689:VERBOSE1:promotion.cc(113)] Fetch promotions disabled for BAP migration
```

## Expected result:
Since date has not been met, UGP grant should be available

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.22.16 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | macOS Version 10.15.7 (Build 19H512)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa @zenparsing @Miyayes

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.22.19 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | macOS Version 10.15.7 (Build 19H512)
```

Verified STR from description.
Confirmed able to get BAP UGP grant on staging env:

English | Japanese
----- | -----
<img width="1199" alt="Screen Shot 2021-02-11 at 10 38 48" src="https://user-images.githubusercontent.com/28145373/107660081-dcf51000-6c55-11eb-89d6-6a0337ae4e2f.png"> | <img width="1193" alt="スクリーンショット 2021-02-11 10 43 51" src="https://user-images.githubusercontent.com/28145373/107660288-175ead00-6c56-11eb-880f-452286557f65.png">

**Comment by kjozwiak** [comment]
Going to need to recheck this quickly we uplift it into `1.21.x` 👍 Removing `QA Pass-macOS` so it doesn't get missed.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.104 x64 build
- Verified steps from issue description
- Verified able to get BAP UGP grant on staging environment
----------
Verification passed on Samsung Tab A with Android 10 running 1.20.104 x64 build
- Verified steps from issue description
- Verified able to get BAP UGP grant on staging environment


OnePlus 6T | Samsung Tab A
-- | --
![image](https://user-images.githubusercontent.com/17010094/108196639-3d31f900-7111-11eb-9cf6-ebdbdfa27d89.png) | ![Screenshot_20210217-111153_Brave](https://user-images.githubusercontent.com/17010094/108196610-33a89100-7111-11eb-944f-1f790b420379.jpg)

**Comment by kjozwiak** [comment]
Moving this into `1.22.x` as the BAP work is being reverted via https://github.com/brave/brave-core/pull/8088. Once we have more information next week, we'll re-revert https://github.com/brave/brave-core/pull/8088 and move everything back into `1.21.x` and release `1.21.x - Release #2`.

**Comment by srirambv** [comment]
```
   [ RESPONSE - OnRequest ]
    > Url: https://grant.rewards.bravesoftware.com/v1/promotions/962abffd-4952-40cd-b90d-05868e233828/claims/c8a0d23e-0e5b-45f2-a554-546bb2172dd6
    > Result: Success
    > HTTP Code: 200
```
