### ISSUE TITLE
Support Unstoppable Domains via DoH behind a feature flag

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#14099]
Support the name resolution of unstoppable domains via https://resolver.unstoppable.io/dns-query endpoint when the feature is enabled in brave://flags and user set the resolve method to public DoH server.

### Settings
<img width="711" alt="settings" src="https://user-images.githubusercontent.com/4730197/107584521-73232a80-6bb1-11eb-9ac0-c1a099c20ae6.png">

Under brave://settings/extensions, a new dropdown box setting for unstoppable domain resolution will be added, and the default value will be “Ask”.

### Onboarding
<img width="1051" alt="interstitial" src="https://user-images.githubusercontent.com/4730197/107584529-76b6b180-6bb1-11eb-9b65-f9c2ee145296.png">

(Above screenshot is an initial version of the interstitial page, it will be updated to match design spec.)
When the unstoppable domain resolution setting is “Ask”, an interstitial page will be shown when users try to visit .crypto domains for users to opt in. If users choose to proceed, the setting will be changed to “Public DNS over HTTPS server”, and the page will be reloaded and resolved using the DNS gateway, future navigations to .crypto domains will be resolved using the same DNS gateway. If users click “Don’t ask again”, the setting will be set to disabled.

### DNS gateway
When a user input an address with a known TLD from unstoppable domains (ex: .crypto domains) in the browser URL bar, the domain name will be resolved through a DNS gateway which supports the resolution of unstoppable domains. Brave will use https://resolver.unstoppable.io/dns-query endpoint provided by Unstoppable Domains, which is a proxy to https://eth.resolver.cloudflare-eth.com/dns-query, as the DNS gateway. It will be responsible for making calls to Ethereum smart contracts using the Ethereum JSON RPC to resolve the address. This DNS gateway will be added into the browser's DNS over HTTPS providers, but will only be used for resolving known TLD from Unstoppable Domains. Because this method requires DNS over HTTPS support, we will not resolve Unstoppable Domains if DoH is disabled either by user or by policy regardless of the value of user setting for Unstoppable Domain resolution.
Using DNS gateway is a simpler method which could be used by default for all our users without introducing overhead of making calls to Ethereum, and is using the protocols (HTTP, DNS) which are well supported by the browser. However, it does come with a downside that the decentralization is decreased due to the introduction of the hosted DNS gateway, so in the future we will also provide the option to resolve via ethereum directly to users.

### Recognizing TLDs from unstoppable domains
In order to make URLs with known TLDs from unstoppable domains to be categorized as URL when users input them in the location bar, we will treat these TLDs as known TLDs from the public suffix list. With this, the first entry in the dropdown list will be URL as shown below.
<img width="626" alt="Screen Shot 2021-02-10 at 3 09 16 PM" src="https://user-images.githubusercontent.com/4730197/107584794-f6dd1700-6bb1-11eb-8896-3a8357d71aef.png">

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` with the testplan from https://github.com/brave/brave-core/pull/7702 on


Brave | 1.23.19 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)


1. Open Brave and visit `brave.crypto`, it should show error page saying `This site can’t be reached`.
<details>
<summary>screenshot</summary>
<img width="1312" alt="Screen Shot 2021-03-04 at 2 51 36 PM" src="https://user-images.githubusercontent.com/387249/110041657-4ae2a380-7cf9-11eb-9a63-e488086a7ca4.png">
</details>

2. Go to settings, search for unstoppable, there should be no unstoppable domains resolve method setting.

<details>
<summary>screenshot</summary>
<img width="1312" alt="Screen Shot 2021-03-04 at 2 54 09 PM" src="https://user-images.githubusercontent.com/387249/110041751-80878c80-7cf9-11eb-8caa-4a6005e314cb.png">
</details>

3. Go to `brave://flags` and search for unstoppable and enable the feature flag.

<details>
<summary>screenshot</summary>
<img width="1016" alt="Screen Shot 2021-03-04 at 2 55 13 PM" src="https://user-images.githubusercontent.com/387249/110041888-b462b200-7cf9-11eb-9e41-ab23ab6b2b0a.png">
</details>

4. Restart browser and go to `brave.crypto` should now should the interstitial for users to opt-in unstoppable domains support.

<details>
<summary>screenshot</summary>
<img width="1134" alt="Screen Shot 2021-03-04 at 2 56 19 PM" src="https://user-images.githubusercontent.com/387249/110041963-d6f4cb00-7cf9-11eb-8f5b-665af05560d7.png">
</details>

5. Click Disable, should now see site can't be reached and `Method to resolve unstoppable domains` in `brave://settings` should now be `Disabled`.

<details>
<summary>screenshots</summary>
<img width="1134" alt="Screen Shot 2021-03-04 at 2 57 51 PM" src="https://user-images.githubusercontent.com/387249/110042068-0d324a80-7cfa-11eb-9cbd-9a9801289cbe.png"> | <img width="1134" alt="Screen Shot 2021-03-04 at 2 59 19 PM" src="https://user-images.githubusercontent.com/387249/110042193-42d73380-7cfa-11eb-8774-3c0be6dba392.png">
</details>

6. Change the resolve method setting back to ask and visit `brave.crypto` again.

<details>
<summary>screenshot</summary>
<img width="1134" alt="Screen Shot 2021-03-04 at 2 59 33 PM" src="https://user-images.githubusercontent.com/387249/110042195-436fca00-7cfa-11eb-94a8-85991e48b8f4.png">
</details>

7. Opt-in interstitial should be shown again, and this time click `Proceed using Cloudflare server`.
8. Page should be loaded now. (Note that there will be a brief moment that it is showing site is not reached while the page is loading, this is a known and will be addressed in a new issue.)

<details>
<summary>screenshot</summary>
<img width="1007" alt="Screen Shot 2021-03-04 at 3 01 52 PM" src="https://user-images.githubusercontent.com/387249/110042392-934e9100-7cfa-11eb-86e3-a60d2ee64555.png">
</details>

9. `Method to resolve unstoppable domains` in `brave://settings` should now be `Public DNS over HTTP server`.

<details>
<summary>screenshot</summary>
<img width="1788" alt="Screen Shot 2021-03-04 at 3 03 02 PM" src="https://user-images.githubusercontent.com/387249/110042523-bed17b80-7cfa-11eb-8367-1e7157baf692.png">
</details>

10. Open a new tab and visit `brad.crypto`, page should be loaded normally without any interstitial pages.  

<details>
<summary>screenshot</summary>
<img width="1788" alt="Screen Shot 2021-03-04 at 3 03 39 PM" src="https://user-images.githubusercontent.com/387249/110042575-d3ae0f00-7cfa-11eb-82f3-65d0d096273b.png">
</details>

Additionally, I filed https://github.com/brave/brave-browser/issues/14478 for the cropped `Public DNS over HTTPS serv` text in the select widget.
