### ISSUE TITLE
target packages notification/error in discover on kubuntu

### ISSUE THREAD

**Issue by kinghat** [brave/brave-browser#1409]
## Description 

target package notifications in discover on kubuntu stable:

## Steps to Reproduce

   1. have chrome stable installed
   2. install brave beta
   3. launch discover

## Actual result:

![image](https://user-images.githubusercontent.com/16073360/46430106-b3cf2700-c70d-11e8-9951-b791e63d7ffd.png)

## Expected result:
no target package notifications in discover?

## Reproduces how often: 

easily reproduced. every times

## Brave version (chrome://version info)

Version 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
reproducible on beta
- Does it reproduce on browser-laptop? 
no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @mbacchi can this be moved to devops repo?
