### ISSUE TITLE
Ads popping in over third party programs

### ISSUE THREAD

**Issue by WriterDad** [brave/brave-browser#14093]
New Brave user here, on a PC laptop running Windows 8.1.

I LOVE the idea of the BAT rewards, but found out recently that the ads from Brave pop up over top of other active third party programs. I was working in a word processor while Brave was idle in the background, and was surprised to see a Brave ad appear in the bottom right corner, on top of my work.

Would there be any way to only have ads pop in when Brave is actively being used, or alternately, to at least not pop up on top of other programs?

I appreciate that you don't want users getting credit for ads that they aren't actually seeing, but I wouldn't be seeing an ad in another browser that's running in the background. If users are meant to get credit for paying attention to ads, then as with other browsers, that attention shouldn't be expected when the browser isn't being used.

Perhaps the simplest solution, albeit not perfect, could be to somehow only count BAT-accumulating time when a user is actively using the browser? If I'm scrolling through a webpage or typing on a webpage or clicking on a webpage or a video is running, etc., it would suggest I'm using Brave and the BAT time should count then. Whereas if no tabs have any active participation by me and if no stream is running, it would be a safe bet that I'm not actively using Brave, and the time could stop until there's an action taken within Brave browser tabs.

I'm sure there are plenty of more elegant, nuanced ways to go about solving the issue.

For now, because I can't afford the distraction of browser ads popping up even when I'm not actively using the browser (which is a time I'd certainly not expect to get credited with seeing ads), and because I'm on and off Brave enough through the day that it would be a pain to turn the Ads toggle on and off every time I've got to (for instance) check something quickly, I've just turned off the ads completely. The downside to that option is then I'm getting no credit for seeing ads in the time I AM using in Brave, which is of course the point of the BAT system.

I'm hoping there can be some resolution to this.

Thanks for your time and consideration.

**Comment by tmancey** [comment]
@WriterDad Can you please maximize the window to full-screen and let me know if ads still appear. Ads should not appear in full-screen mode.

**Comment by WriterDad** [comment]
Sorry, I'm unsure which window you wanted me to maximize to full screen.

The issue initially came up when I had Brave running (full screen) in the background while I was using a word processor (at full screen size) in the foreground.

Thanks for your continued work on the issue!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tmancey** [comment]
@WriterDad Would you be willing to screen-share so we can help diagnose the issue, as we are unable to reproduce. Thank you, Terry
