### ISSUE TITLE
Implement build CI for creating builds and running tests

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#141]
TODO: Add milestones and timelines for them as sub-items.

- [x] Manually trigger macOS builds
- [x] Manually trigger Windows builds
- [x] Manually trigger Linux builds
- [x] Allow tests to be run using a CI build
- [ ] Schedule builds and tests for each PR commit and each commit to master

**Comment by bbondy** [comment]
@mbacchi can you give a recap of where we're at with this? I think you guys made some progress with tests at the SF devops get together.

**Comment by bbondy** [comment]
Closing this in favour of: https://github.com/brave/brave-browser/issues/1405

**Comment by kjozwiak** [comment]
Marking this as `QA/No` as there's nothing QA can do here. @bbondy please change if you feel there's something QA can do here in terms of manual verification.
