### ISSUE TITLE
Downloading components updates directly from Google through Window's BITS

### ISSUE THREAD

**Issue by fusionneur** [brave/brave-browser#14105]
On Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)

[BITS](https://docs.microsoft.com/en-us/windows/win32/bits/about-bits) is downloading components updates (chrome://components) directly from google. Is this the right approach? How to disable this update check?

**Comment by fusionneur** [comment]
Also port 80 is being used

**Comment by fusionneur** [comment]
Aren't here some privacy/security concerns?

**Comment by bsclifton** [comment]
@fusionneur all of the items downloading from brave://components should be proxied - you are reporting that you see this go directly to Google?

Which components? It should always be going to our update servers and then (for non-Brave components) be proxied

**Comment by fusionneur** [comment]
Eg. BITS trying to connect to 142.250.186.176 (google domain)

 nslookup 142.250.186.176
176.186.250.142.in-addr.arpa    name = fra24s08-in-f16.1e100.net.

**Comment by fusionneur** [comment]
below a list of the endpoints svchost is connecting to:

172.217.22.196 - www.google.com (+port 80!)
82.76.79.81 - r6.sn-gqn-vu2e.gvt1.com (+port 80!)
142.250.185.80, 142.250.186.176 - storage.googleapis.com
216.58.212.142 - play.google.com (+port 80!)

Besides 443, port 80 is also used!

**Comment by fusionneur** [comment]
Just a headsup that the browser continues to search for component updates through svchost/bits daily (including on port 80). I would suggest to increase the priority since the privacy is affected

**Comment by bsclifton** [comment]
@fusionneur do you have more information about your OS? What build are you using? (ex: if Linux, are you using community supported Arch Linux version? or official Brave version? or Official Brave Snap if on Ubuntu?)

More info should help us narrow this down. Unofficial builds will not use the proxy and will go directly out
cc: @jumde

**Comment by Mexicool** [comment]
https://www.google.com/doodles/halloween-global-candy-cup-2015

**Comment by fusionneur** [comment]
> @fusionneur do you have more information about your OS? What build are you using? (ex: if Linux, are you using community supported Arch Linux version? or official Brave version? or Official Brave Snap if on Ubuntu?)
> 
> More info should help us narrow this down. Unofficial builds will not use the proxy and will go directly out
> cc: @jumde

Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)
Windows 10

**Comment by ShivanKaul** [comment]
Hey @fusionneur, we're taking a look at this. From an initial dekko it seems like if background downloads are enabled on Windows, a BITS downloader is used; we should proxy whichever URLs are being used by BackgroundDownloader: https://source.chromium.org/chromium/chromium/src/+/main:components/update_client/crx_downloader_factory.cc;l=39;drc=2507e0d8b56f6c1b1fb53280d9453a93cee69cfa

**Comment by fusionneur** [comment]
Leakage is still plaguing on Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by fusionneur** [comment]
Still on Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit)... bump?

**Comment by ShivanKaul** [comment]
@fusionneur do you still see the behaviour if you disable BITS or set it to Manual instead of Automatic system-wide?
@bsclifton I don't have a Windows build handy but a simple short-term fix might just be to disable BITS, since anecdotally it doesn't look like there is a perceivable difference? `ConfiguratorImpl::EnabledBackgroundDownloader()` in browser/component_updater/brave_component_updater_configurator.cc

**Comment by fusionneur** [comment]
wouldn't disabling BITS, disable windows updates as well ?

**Comment by ShivanKaul** [comment]
Yes, not recommending you do that permanently (though you could set it to manually prompt).

**Comment by fusionneur** [comment]
i set it on manual for the following next days to see which is going to be the behavior. in any case this is just a workaround, and brave should proxy these requests on its own without relying on bits

**Comment by fusionneur** [comment]
Coincidence happen to have some windows updates right now. I disabled bits, and they were still downloaded through windows update service. So I suppose the workaround is valid.
Running now on windows 11 21H2 22000.318

**Comment by fusionneur** [comment]
Update: Unfortunatelly BITS set on manual/disabled result in components not being updated at all (Status - Update error) as seen under brave://components/

Eg.:
![image](https://user-images.githubusercontent.com/7840350/146804283-d57e839c-745d-41e6-b8bd-e44c9133ed9b.png)

These components should update without relying on BITS.

**Comment by fusionneur** [comment]
How comes a P2 stays untouched for a year... really makes me wonder

**Comment by ShivanKaul** [comment]
@fusionneur there's a bunch of Brave specific components that are shipped to the browser from our servers. I'm confused how you're getting those (e.g. Brave Local Data Updater) if you're going directly to Google servers.

**Comment by fusionneur** [comment]
some of the components (those starting with "Brave" i think) are downloading from brave specific server and some others from google servers (through bits) as my firewall shows. Did i get your question right?

**Comment by ShivanKaul** [comment]
Yeah. I see.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.88 Chromium: 98.0.4758.87 (Official Build) dev (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1466)

Steps:
1. installed `1.36.64`
2. opened Powershell and ran the following: `While(1) { Clear-Host; Get-BitsTransfer; Start-Sleep -s 3; }`
3. launched Brave
4. opened `brave://components`
5. waited ~8 minutes (taking note of the state of Powershell's output)
6. confirmed I saw an entry for the `Chrome Component Updater`

![14105-1](https://user-images.githubusercontent.com/387249/153041772-c0b6458b-02b8-4a95-90be-a4a0ec85d77b.png)

7. quit Brave
8. uninstalled `1.36.64`
9. installed `1.36.88`
10. launched Brave
11. repeated steps 2-5

Confirmed I never saw `Chrome Component Updater` at any time while `brave://components` was downloading updates

example | example
----------|----------
![14105-2](https://user-images.githubusercontent.com/387249/153042485-b2629476-217d-42e3-8c78-aed7e8c8bec8.png)

**Comment by bridiver** [comment]
I'm really struggling to see how that could be happening or why it would be any different with the bits downloader. The standard downloader and the windows bits downloader both implement the same interface and `BeginDownload` gets called on it with the same url. Nothing is hardcoded in the background downloader except the job name `const wchar_t kJobName[] = L"Chrome Component Updater";`
If it's using the wrong url for the background downloader then it would also be using the wrong url for the regular downloader unless windows caches the url by job name or something weird like that.

```
scoped_refptr<CrxDownloader> CrxDownloaderFactoryChromium::MakeCrxDownloader(
    bool background_download_enabled) const {
  scoped_refptr<CrxDownloader> url_fetcher_downloader =
      base::MakeRefCounted<UrlFetcherDownloader>(nullptr,
                                                 network_fetcher_factory_);
#if BUILDFLAG(IS_WIN)
  // If background downloads are allowed, then apply the BITS service
  // background downloader first.
  if (background_download_enabled) {
    return base::MakeRefCounted<BackgroundDownloader>(url_fetcher_downloader);
  }
#endif

  return url_fetcher_downloader;
}
```

**Comment by bridiver** [comment]
Apparently we are redirecting to our updater in the network stack to handle widevine which has to go to google per the licensing agreement which explains why it doesn't use the correct url when it downloads through the OS

**Comment by mkarolin** [comment]
@fusionneur, unfortunately I was unable to reproduce with 1.45.127. 
Was this with a new profile or an existing one? Do you have any extensions installed? Also, do you have Chrome installed by any chance?
cc: @brave/qa-team to see if you can reproduce.

**Comment by mkarolin** [comment]
Thanks for digging into it @fusionneur.

It might be worth for us to patch https://source.chromium.org/chromium/chromium/src/+/main:components/update_client/background_downloader_win.cc;l=113 to be "Brave Component Updater", so it would be easily distinguishable from various Chromium embedders.
