### ISSUE TITLE
Brave Crypto Wallet out of sync 

### ISSUE THREAD

**Issue by tcarrijo** [brave/brave-browser#14106]
## Description 
The problem started this week and the Brave Crypto Wallet is not in sync with the Ethereum blockchain. Wallet balance outdated/ not sync.

Not only that, when we access some websites3, it is unable to update the information or display the information correctly.

And confirming that the problem does not happen with Metamask … only with Brave Crypto Wallet. Even with Metamask inside Brave.
So there is a problem with Brave’s implementation of the wallet.

## Steps to Reproduce

   1. Just open any web3 website
   2. Do a Ethereum transaction
   3. Check you ETH wallet balance and compare it with etherscan.com
   4. Sometimes, not often, if you restart the browser it sync again

## Actual result:

Wallet not in sync with the blockchain.

## Expected result:
Wallet should be in sync with the blockchain.

## Reproduces how often: 

Other users reporting the problem in the forum: https://community.brave.com/t/brave-crypto-wallet-problem/204773

## Brave version (brave://version info)

Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tried
- Can you reproduce this issue with the nightly channel? Not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Dupe of https://github.com/brave/brave-browser/issues/14091? Can you please reconfirm if you are still running into it? Can you check console for any errors?

**Comment by tcarrijo** [comment]
Yes, still running into the problem. Web3 pages not showing up to date information when browsing using Brave.. but with Metamask is all fine.

Console shows this:

![image](https://user-images.githubusercontent.com/64757730/107657588-0ddc4180-6c64-11eb-8094-b1246e4ee720.png)

**Comment by tcarrijo** [comment]
> Dupe of #14091? Can you please reconfirm if you are still running into it? Can you check console for any errors?

#14091 is about the Wallet balance only.

But we are having two issues here, the Wallet balance out of sync, and most important and critical issue is: the Web3 websites not showing up to date information when browsing with the Brave. (found it in various sites, but two that I checked now was https://homora.alphafinance.io/status and https://app.badger.finance/ )

**Comment by srirambv** [comment]
cc: @bbondy @marshall

**Comment by bbondy** [comment]
There was an issue with the Infura side of things yesterday (some entitlements were accidentally dropped) that they fixed. It might have taken some time to propagate. If you’re still experiencing issues though, could you give me exact steps? I did a transaction and it’s showing up with balance changes.

You can click the background page in chrome://extensions (with devtools option on in that same page) and send a screenshot of any errors on that console?

**Comment by tcarrijo** [comment]
This page https://homora.alphafinance.io/status
Show a collum with rewards that are constant updated. With Chrome , If i reload the page I see the updates in sync with the blockchain. But with Brave it does not show the current value, even with Ctrl+F5

**Comment by bbondy** [comment]
We disabled some recent caching, can you try again now?

**Comment by bbondy** [comment]
I could reproduce and I think it works now for me.

**Comment by tcarrijo** [comment]
> We disabled some recent caching, can you try again now?

YES!! Now it is working again.

Glad to use Brave once again... thanks!

**Comment by tcarrijo** [comment]
> I could reproduce and I think it works now for me.

Thanks! It now works fine.
