### ISSUE TITLE
[Android] Update icons in the main menu

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#14109]
## Description 
We need updated menu icons in the main menu.
![device-2021-02-11-121944](https://user-images.githubusercontent.com/30602739/107675108-b50da880-6c65-11eb-8459-8de7b90c312b.png)

## Expected result
![image](https://user-images.githubusercontent.com/2388823/107686462-1cbdf680-6c5a-11eb-8a99-a655f55c0b39.png)
#14113 

## Assets
Figma: https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/?node-id=0%3A1

**Comment by samartnik** [comment]
cc @jamesmudgett

**Comment by samartnik** [comment]
@karenkliu we have 2 more items when page is loaded `Find in page` and `Add to Home screen`. Not sure if we want new icons for them.

![device-2021-02-18-141811](https://user-images.githubusercontent.com/30602739/108409447-3f20b880-71f4-11eb-9777-f0e416faa39b.png)

**Comment by samartnik** [comment]
Test plan:
1. Enable `Android tabbed app overflow menu icons` in `brave://flags` (not required on cr90 and later).
2. Make sure that icons match expected result from the first post.

**Comment by karenkliu** [comment]
@deeppandya Can you use these two icons for "Find in page" and "Add to home screen"?

![image](https://user-images.githubusercontent.com/2388823/108454854-07c90080-7222-11eb-8b2f-6af4c8af3af6.png)

**Comment by samartnik** [comment]
I'll update these 2

**Comment by deeppandya** [comment]
Thanks @samartnik for updating it.

**Comment by rodrigoswz** [comment]
Just a detail, if enable `brave://flags/#tabbed-app-overflow-menu-regroup` the _Downloads_ and _Bookmarks_ icons are no longer the new ones added.

![Screenshot_20210219-125144.png](https://user-images.githubusercontent.com/14058427/108528616-5cb45780-72b2-11eb-958c-7cc7e6d9b76d.png)

**Comment by samartnik** [comment]
Thank you for pointing out @rodrigoswz

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.22.54 x64 beta build
- Verified icons are up-to-date as per https://github.com/brave/brave-browser/issues/14109#issuecomment-781795823

New Tab | On Page | Tab Tray
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/110456679-c2ca1880-80c1-11eb-801a-0e0334d8d7d7.png) | ![image](https://user-images.githubusercontent.com/17010094/110456728-cfe70780-80c1-11eb-8e75-ae8f189ce1be.png) | ![image](https://user-images.githubusercontent.com/17010094/110456746-d4abbb80-80c1-11eb-91ba-30af2c9da976.png)

-------
Verification passed on OnePlus 6T with Android 10 running 1.22.54 x64 beta build
- Verified icons are up-to-date as per https://github.com/brave/brave-browser/issues/14109#issuecomment-781795823

**Bottom bar enabled**

New Tab  | On Page | Tab Tray
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/110456924-03c22d00-80c2-11eb-841d-fb846ace947a.png) | ![image](https://user-images.githubusercontent.com/17010094/110456966-0fadef00-80c2-11eb-9696-fad276e72a4b.png) | ![image](https://user-images.githubusercontent.com/17010094/110456948-0a50a480-80c2-11eb-9bed-a4fbdd3b8a22.png)

**Bottom bar disabled**

New Tab  | On Page | Tab Tray
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/110457010-19375700-80c2-11eb-9520-3b3a57785bd6.png) | ![image](https://user-images.githubusercontent.com/17010094/110457033-1d637480-80c2-11eb-833e-95417f88af93.png) | ![image](https://user-images.githubusercontent.com/17010094/110457045-218f9200-80c2-11eb-917c-8846774f3dae.png)

------
Logged #14588 as a follow up suggestion
