### ISSUE TITLE
Unable to search settings in 1.22.x via `Search settings` in brave://settings/

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14101]
## Description 

Unable to search settings in 1.22.x via `Search settings` in brave://settings/

## Steps to Reproduce

   1. Clean or upgraded profile 1.22.x
   2. Search any settings (e.g password or security) via `Search settings` in brave://settings/
   3. Search result is not shown 
   
**Note**: Ctl+F opens up Omnibox search popup in the URL bar in brave://settings - which is incorrect

## Actual result:

Unable to search settings in 1.22.x via `Search settings` in brave://settings/

**1.22.x**
Ctl+F opens up Omnibox search popup in the URL bar in brave://settings - which is incorrect
![image](https://user-images.githubusercontent.com/38657976/107612172-a9bd7b80-6c6b-11eb-8f3e-53701e5c31e7.png)

Search via `Search settings` doesn't highlight the search settings in brave://settings page
![image](https://user-images.githubusercontent.com/38657976/107612303-f5702500-6c6b-11eb-8f5a-6a4a35601fd3.png)

**1.20.103**
Ctl+F opens up `Search settings` bar in brave://settings 
![image](https://user-images.githubusercontent.com/38657976/107612373-20f30f80-6c6c-11eb-9393-d7a46705a2ce.png)

Search via `Search settings` highlights the search settings in brave://settings page
![image](https://user-images.githubusercontent.com/38657976/107612398-2ea89500-6c6c-11eb-946e-2abb9baf47f7.png)

## Expected result:
should be able to seach settings via `Serach settings` in brave://settings/

Search via `Search settings` should highlight the search settings in brave://settings page
![image](https://user-images.githubusercontent.com/38657976/107612122-8f839d80-6c6b-11eb-9dfb-76399e34c308.png)

## Reproduces how often: 

easy

## Brave version (brave://version info)

Brave | 1.22.16 Chromium: 89.0.4389.40 (Official Build) nightly (64-bit)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | Windows 10 OS Version 2004 (Build 19041.746)
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron @bbondy @bsclifton

**Comment by bbondy** [comment]
This was the same error in the console as a previous fix that @mkarolin did. 
I verified it is working with this build: Version 1.22.22 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` using 

Brave | 1.22.34 Chromium: 89.0.4389.48 (Official Build) nightly (x86_64)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | macOS Version 11.2.1 (Build 20D74)


Steps:
1. opened `Settings` and did `command + f` to open "Search settings"
<img width="1167" alt="Screen Shot 2021-02-18 at 1 49 46 PM" src="https://user-images.githubusercontent.com/387249/108426113-34642480-71f0-11eb-9ce3-e9ed58a37e97.png">

2. searched for various strings (such as `ipfs`) and confirmed they matched and highlighted, in-page
<img width="1167" alt="Screen Shot 2021-02-18 at 1 52 00 PM" src="https://user-images.githubusercontent.com/387249/108426329-7ee5a100-71f0-11eb-8aaf-e1f7249e8887.png">
