### ISSUE TITLE
BAP popup can overlap rewards panel in certain cases

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14108]
## Description 

Found while testing https://github.com/brave/brave-core/pull/7698

Sometimes the BAP popup can overlap the rewards panel.

## Steps to Reproduce

   1. Clean profile, region = Japan, staging environment
   2. Opened NTP
   3. Opened Rewards panel, dismissed onboarding modal
   4. Claimed UGP grant
   5. Completed captcha
   6. Waited a few seconds (for grant to process), then closed "It's your lucky day" overlay.
   7. Clicked elsewhere so Brave was not in focus
   8. Then the BAP popup displayed overlapping the rewards panel

## Actual result:

<img width="1200" alt="Screen Shot 2021-02-11 at 12 04 30" src="https://user-images.githubusercontent.com/28145373/107674580-197c3800-6c65-11eb-9a8d-2ed8dad67ddc.png">

## Expected result:
No overlay. Or, per suggestion of @Miyayes an "x" or close button.

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.22.19 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
Revision	2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS	macOS Version 10.15.7 (Build 19H512)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing @Miyayes @brave/legacy_qa

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.22.22 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | macOS Version 10.15.7 (Build 19H512)
```

Verified STR from description.
Confirmed no overlapping popup/panel observed.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave	1.20.104 Chromium: 88.0.4324.152 (Official Build) （64 ビット）
変更履歴	6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS	Windows 10 OS Version 1809 (Build 17763.1637)
```
- Verified the STR from the description
- Confirmed no overlapping popup/panel observed.
![image](https://user-images.githubusercontent.com/38657976/108203766-f5c75f00-7148-11eb-8e05-657c085e4ae1.png)

**Comment by kjozwiak** [comment]
Moving this into `1.22.x` as the BAP work is being reverted via https://github.com/brave/brave-core/pull/8088. Once we have more information next week, we'll re-revert https://github.com/brave/brave-core/pull/8088 and move everything back into `1.21.x` and release `1.21.x - Release #2`.

**Comment by kjozwiak** [comment]
Labeling this as `QA/No` as the case re: the tooltip being displayed isn't valid as per https://github.com/brave/internal/issues/747#issuecomment-761233483. The above tooltip stops being displayed ~a week before March 13th. Seeing as March 13th is in ~2 days, this isn't valid anymore.
