### ISSUE TITLE
BAP popup and alert need Japanese translations

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14117]
## Description 

Found while testing https://github.com/brave/brave-core/pull/7698

The BAP popup and alert display in English even if the OS language is Japanese.

## Steps to Reproduce

   1. Have OS set to Japan/Japanese
   2. Trigger BAP popup and/or BAP alert

## Actual result:

English text for both:
<img width="1196" alt="J4" src="https://user-images.githubusercontent.com/28145373/107702165-d67f8c00-6c87-11eb-823f-6b7634615e28.png">
<img width="1193" alt="J5" src="https://user-images.githubusercontent.com/28145373/107702169-d7b0b900-6c87-11eb-82ff-8b0bec672b58.png">

## Expected result:
Japanese translations for that text

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.22.19 Chromium: 89.0.4389.40 (Official Build) nightly （x86_64）
-- | --
変更履歴 | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | macOS バージョン10.15.7（ビルド19H512）

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing @bsclifton @Miyayes @brave/legacy_qa

**Comment by LaurenWags** [comment]
Android also needs translations. Below screenshots are from `1.22.22`:

Tooltip | Modal
----- | -----
![tooltip-portrait](https://user-images.githubusercontent.com/28145373/107821207-0b541780-6d4a-11eb-913c-0414208bfdb9.png) | ![modal-portrait](https://user-images.githubusercontent.com/28145373/107821211-0c854480-6d4a-11eb-9b80-1b25825a371c.png)

**Comment by Miyayes** [comment]
@deeppandya If language is Japanese, these are the translated strings:

**Little Tooltip** 

Brave Rewards in Japan is switching to a new system! Please use your BAP by March 13th. After that, BAP will be discontinued. 

[Learn more]

日本でのBrave Rewardsが新システムに移行します！
お持ちのBATポイント(BAP)は、3月13日までにご使用ください。BAPはそれ以降に廃止されます。

[詳しくはこちら］

**Full dialog box:**

Brave Rewards in Japan is switching to a new system! 

The tipping feature will be unavailable from March 13th until April 13th. All BAPs will be discontinued by April 13th. Please use your BAP by March 13th. Any BAP remaining in your Brave browser after March 13th cannot be held or transferred by you or Brave, and will be lost.

A new and improved system awaits!

日本でのBrave Rewardsが新システムに移行します！

3月13日から4月13日チップを送る機能が停止されます。すべてのBATポイント(BAP)は4月13日に廃止されます。
お持ちのBAPは、3月13日までにご使用ください。3月13日以降にBraveブラウザ上に残っているBAPについては、ユーザーもBraveも保持・移転をできず、消失されます。

改良された新システムへの移行をご期待ください！

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/7949 was merged into `1.21.x`

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave	1.20.104 Chromium: 88.0.4324.152 (Official Build) （64 ビット）
変更履歴	6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS	Windows 10 OS Version 1809 (Build 17763.1637)
```
- Verified the STR from the description.
![image](https://user-images.githubusercontent.com/38657976/108204154-738b6a80-7149-11eb-99f0-a90fcff71135.png)
![image](https://user-images.githubusercontent.com/38657976/108204179-7c7c3c00-7149-11eb-9912-a141c66e7aa1.png)

**Comment by srirambv** [comment]
Removing `OS/Android` label and logged Android specific issue #14220 since the translations are not pulled into Android.

**Comment by kjozwiak** [comment]
Moving this into `1.22.x` as the BAP work is being reverted via https://github.com/brave/brave-core/pull/8088. Once we have more information next week, we'll re-revert https://github.com/brave/brave-core/pull/8088 and move everything back into `1.21.x` and release `1.21.x - Release #2`.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Windows 10 OS Version 2009 (Build 19042.844)
```

* Verified via https://github.com/brave/brave-browser/issues/14572#issuecomment-796421998. Ensured that the translations mentioned via https://github.com/brave/internal/issues/756#issue-824795329 are being used. Found https://github.com/brave/internal/issues/756#issuecomment-796417618 but not a blocker.
