### ISSUE TITLE
crash can occur when clicking on the rewards icon (particularly if BAP popup is displayed)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14110]
## Description 

Found while testing https://github.com/brave/brave-core/pull/7698

Sometimes tapping on the rewards icon in the URL bar crashes the browser. I've only encountered it so far when the BAP popup is overlapping the rewards panel (https://github.com/brave/brave-browser/issues/14108). 

## Steps to Reproduce

   1. Clean profile, region = Japan, staging environment
   2. Opened NTP
   3. Opened Rewards panel, dismissed onboarding modal
   4. Claimed UGP grant
   5. Completed captcha
   6. Waited a few seconds (for grant to process), then closed "It's your lucky day" overlay.
   7. Clicked elsewhere so Brave was not in focus
   8. Then the BAP popup displayed overlapping the rewards panel
   9. Click on the rewards icon in the URL bar

## Actual result:

Brave crashes, crash report ID: `42120000-f138-da05-0000-000000000000`

## Expected result:
No crash, I believe without the BAP popup clicking on that icon would close the rewards panel

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.22.19 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
Revision	2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS	macOS Version 10.15.7 (Build 19H512)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing @Miyayes @brave/legacy_qa

**Comment by zenparsing** [comment]
For background, both this issue and #14108 occur because `BraveActionViewController::TriggerPopupWithUrl` does not hide currently visible popups.

`BraveActionViewController` is an override of chromium's `ExtensionActionViewController` that overrides `TriggerPopupWithUrl`. In the chromium version there's a call to:

```cpp
extensions_container_->HideActivePopup();
```

which does not exist in the overridden version.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.22.22 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | macOS Version 10.15.7 (Build 19H512)
```

Verified STR from description.
No overlapping popup/panel was observed. No crash observed when
- clicking on Rewards logo when panel is displayed
- clicking on Rewards logo when BAP popup is displayed
- clicking on "Learn more" on BAP popup

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave	1.20.104 Chromium: 88.0.4324.152 (Official Build) （64 ビット）
変更履歴	6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS	Windows 10 OS Version 1809 (Build 17763.1637)
```
- Verified the STR from the description and ensured there is no crash when clicking on the rewards icon
![image](https://user-images.githubusercontent.com/38657976/108202006-851f4300-7146-11eb-9bc9-51da4baddd1d.png)
![image](https://user-images.githubusercontent.com/38657976/108202085-9cf6c700-7146-11eb-9540-3202cbedba9b.png)

**Comment by GeetaSarvadnya** [comment]
@zenparsing I don't see the `Learn More` link in BAP popup - Is this expected?

![image](https://user-images.githubusercontent.com/38657976/108208336-ec40f580-714e-11eb-97db-85e5e0ffe30b.png)

**Comment by kjozwiak** [comment]
Moving this into `1.22.x` as the BAP work is being reverted via https://github.com/brave/brave-core/pull/8088. Once we have more information next week, we'll re-revert https://github.com/brave/brave-core/pull/8088 and move everything back into `1.21.x` and release `1.21.x - Release #2`.

**Comment by kjozwiak** [comment]
As per https://github.com/brave/internal/issues/747#issuecomment-761233483, the tooltip won't be appearing as we're basically ~2 days before March 13th hits. As per the specification, the tooltip stops appearing a week before March 13th. So a lot of the above cases aren't valid anymore re: using the tooltip.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.23.31 Chromium: 89.0.4389.86 (Official Build) nightly (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Windows 10 OS Version 2009 (Build 19042.844)
```

* ensured that you can claim a grant without any issues
* ensured that clicking on the `rewards` icon once you've claimed the grant doesn't crash Brave
* ensured that clicking on the `rewards` icon when the warning modal is opened via the NTP doesn't crash Brave
* ensured that clicking on the `rewards` icon when March 13th hits and balance appears as `0.00` doesn't crash Brave
