### ISSUE TITLE
Pages/Tabs Stuck in Offline Mode

### ISSUE THREAD

**Issue by norsehealer** [brave/brave-browser#14118]
## Description 
Tabs will, what seems like at random, switch to Offline mode and there's no direct nor easy method to stop the function.  I honestly don't want offline mode at all.  i'm tracking a package and my page is hard stuck on Feb 9th information.

## Steps to reproduce 

   1.  open DHL to track a package
   2. refresh 2 days to get updates
   3. tab becomes offline without input/prompt from user
   4. can't fix the function by refresh, tapping the "offline" area or nothing
   5. i swiped a few tabs (swipe on the lower bar) and i see all non-google pages are now in "offline" mode.

## Actual result 
  1. page is locked without a clear method to stop the function.
  2. no option to remove the "offline" function, in an "always connected/always on internet" (honestly this would have been great during dial-up times)

## Expected result
1. refresh the page to stop the "offline" function OR
2.  tap the "offline" text in the URL bar, tap "load live page" (or some wording as such).

## Issue reproduces how often 
intermittent issue. When it happens, i can't revert the option. I have to copy the URL, close the tab, open a new tab, paste the URL.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes, its the version i have
- Can you reproduce this issue with the current Play Store Beta version? i dont use beta versions
- Can you reproduce this issue with the current Play Store Nightly version? i dont use nightly versions

## Device details
   - Install type (ARM, x86): Android (was via Play Store)
   - Device type (Phone, Tablet, Phablet): Google Pixel 3a
   - Android version: 11
   
## Brave version
1. 1.19.92
2. Chromium 88.0.4324.152

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? no change.
- Does the issue resolve itself when disabling Brave Rewards? not sure, they aren't enabled.
- Is the issue reproducible on the latest version of Chrome?  i dont use chrome.

### Additional information
  I haven't found a direct method to reproduce the problem.  I leave a tab open, use the browser by opening new tabs, closing some, opening more. then I go back to track my package and it's in offline mode.  this isn't the first time it's happened and I *thought* i fixed it but apparently not.  i really hate the function and just want it off, unless i *hit* the "download copy".

I read a bug report from last year, where the user didn't update their brave. however this isn't the case for me.  I checked my other tabs after reading that thread and noticed all non-google sites were switched to "offline". So now i have to close the tab and reopen it.

you dont understand how frustrated and mad i am that the app (probably a chrome thing) can do this without a clear way to undo it.  "refresh" should be the smartest method to undo it but that doesn't work.

on the DHL site, i removed the last letter of the tracker, hit enter on the URL bar. get an error page. add the last letter back, hit submit, then i see the Offline page again.  i mean, holy fuck, that can't the correct function of the feature.

**Site Settings**
Ask to download is on.

**ADDITIONAL info**
https://support.google.com/chrome/thread/78738916?hl=en   this mentions it could be tied to googleVPN. and I am having problems with that. i have to reboot my phone regularly to get email specific to the VPN having problems.

but it is a problem that *I* can't tell the app to fetch a new version of it.

**Comment by norsehealer** [comment]
well, just read I have to tap and hold Offline to get the app to refresh. that isn't intuitive to me.  i bet i read this last time i had the issue and already forgot about it.

a request to offer a fix via the tap Offline too.

**Comment by srirambv** [comment]
I don't think you need to tap and hold the offline button. If the device is connected to network you can either pull down refresh to load the page or quit and relaunch the brave which triggers a page load.

**Comment by norsehealer** [comment]
problem is when i refresh it doesn't get a new copy.  the VPN is stuck and it doesn't get corrected until i restart the phone or the stop/start the VPN. 

i wrote all of that above thinking it was a Brave problem but it's an issue with my phone. I should write to google to get the VPN service fixed.

I'll close the issue now because it isn't specific to Brave.
