### ISSUE TITLE
Change permission UI on Android to enable / expose "permission until X" ability

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#14128]
This issue is follow up work for #14126

This issue is specifically to track the design and implementation of UI for brave-android, to enable / expose the new capabilities defined in #14126

**Comment by deeppandya** [comment]
In android, we can't change the permission UI android system provides. and we have to use the default android system UI for runtime permissions. and the options we get on the permission it depends on android OS version.

**Comment by iefremov** [comment]
@deeppandya Can you elaborate more? Do you mean that dialogs shown by the browser on, say, https://permission.site/ do depend on Android UIs?

**Comment by deeppandya** [comment]
@iefremov  we can update below UI, 
![Screenshot_20210316-205221](https://user-images.githubusercontent.com/5146988/111398513-02809980-869a-11eb-894a-a9055da771eb.png)
But UI below, we can't update as it's from the android system and the options differs in different OS. Below UI is from android 11, 
![Screenshot_20210316-205231](https://user-images.githubusercontent.com/5146988/111398614-2fcd4780-869a-11eb-9c7c-77e848139b7b.png)
Below UI is from android 10,
![Screenshot_20210316-210009](https://user-images.githubusercontent.com/5146988/111398990-c7cb3100-869a-11eb-99a7-a777abb7566b.png)
Below is the UI from android 7.1.2,
![Screenshot_20210316-210304](https://user-images.githubusercontent.com/5146988/111399133-1aa4e880-869b-11eb-9870-b1135a866efb.png)

**Comment by iefremov** [comment]
gotcha, thanks @deeppandya - this was basically my understanding as well

**Comment by goodov** [comment]
@karenkliu I'm currently adding this into Android UI, made a quick demo. Can you take a look please? wdyt?

https://user-images.githubusercontent.com/5928869/113881367-91d72380-97e6-11eb-8078-112bc3eff307.mp4

**Comment by deeppandya** [comment]
@goodov how would it work with default android permissions ?

**Comment by karenkliu** [comment]
@goodov Can we use the radio button selection on Android instead of a dropdown interaction? Radio buttons seem more mobile-friendly and suitable for this kind of Android dialog.

**Comment by goodov** [comment]
> how would it work with default android permissions ?

@deeppandya you mean those dialogs that Android OS shows to the user? they will be the same, we don't touch them.

@karenkliu thanks! Yeah, you're right, will try radio buttons, but I'm worried if the dialog will be too big in this case. Good catch about "Give permission:" text!

**Comment by deeppandya** [comment]
> > how would it work with default android permissions ?
> 
> @deeppandya you mean those dialogs that Android OS shows to the user? they will be the same, we don't touch them.
> 
> @karenkliu thanks! Yeah, you're right, will try radio buttons, but I'm worried if the dialog will be too big in this case. Good catch about "Give permission:" text!

Okay but in that case, wouldn't it be confusing for users ? Because on this dialog user allow to use location for 24 hours but in the app it would be enabled once user allows it.

**Comment by goodov** [comment]
> Okay but in that case, wouldn't it be confusing for users ? Because on this dialog user allow to use location for 24 hours but in the app it would be enabled once user allows it.

I think in the first dialog the user should see that the permission is for the app ```Brave```, and in the second is for the website ```browserleaks.com```. For me it's quite clear. Maybe people from UX/UI can comment more on this.

**Comment by goodov** [comment]
@karenkliu take a look? Maybe you can make a design mock for this if we're not quite there yet?

https://user-images.githubusercontent.com/5928869/114048157-805c4d00-98b4-11eb-9915-e16b0a60d0f9.mp4

**Comment by karenkliu** [comment]
@goodov This looks good to me 👍 According to Deep different Android OS supports different permission lifetimes. So we should make sure the dialog permission options match what is supported by the OS.

**Comment by goodov** [comment]
This is currently in `nightly`. An uplift to `1.24.x` will be created after "origin-based permission lifetime support" uplift is merged (https://github.com/brave/brave-core/pull/8585).

**Comment by goodov** [comment]
Uplift PR is created, but we need some testing on `nightly` so we can be safe to uplift it.
https://github.com/brave/brave-core/pull/8639

**Comment by stephendonner** [comment]
> Uplift PR is created, but we need some testing on `nightly` so we can be safe to uplift it.
> [brave/brave-core#8639](https://github.com/brave/brave-core/pull/8639)

I'll grab this tomorrow; just verified desktop's https://github.com/brave/brave-browser/issues/14126 on macOS-Intel 🥳

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on OnePlus 6T with Android 10 running 1.24.81 x64 build</summary>

### Time Based checks

<details>
<summary>20 Sec timer - Allow (Camera + Microphone)</summary>
<br>

- Verified passing argument to set permission timer to 20 sec shows up as an option
- Verified selecting 20 sec option and allow enables the Camera + Microphone on the site and system notification shows up
- Verified site is added under allow list for both Camera + Microphone
- Verified after 20 sec the site permissions are removed automatically
- Verified reloading the page and selecting Camera on the page triggers the permission prompt again

20 Sec option | Select 20 sec timer | Site requesting permission | Site added to allow list 
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/116682083-b6698a00-a9a5-11eb-9eaf-c215404c44e8.png) | ![image](https://user-images.githubusercontent.com/17010094/116682096-b9fd1100-a9a5-11eb-84ed-923ca8e0dc89.png) | ![image](https://user-images.githubusercontent.com/17010094/116682187-d436ef00-a9a5-11eb-9725-df4f5906a61c.png) | ![image](https://user-images.githubusercontent.com/17010094/116682161-cbdeb400-a9a5-11eb-866c-11156c2a9bb8.png)


</details>

<details>
<summary>20 Sec timer - Block Forever (Camera + Microphone)</summary>
<br>

- Verified setting permission to `Block Forever` adds an entry under blocked list for the site
  <img width=300 src=https://user-images.githubusercontent.com/17010094/116681675-304d4380-a9a5-11eb-8401-4fd4233e30e5.png>

</details>
<hr>

### Origin-based cases

<details>
<summary>Origin-based behaviour, multiple tabs (Location)</summary>
<br>

- Verified visiting `browserleaks.com/geo` triggers permission prompt
- Verified selecting `Until I close this page` and select allow sets the permission for the page and detects location
- Verified visiting permission.site on a second tab and selecting location triggers prompt
- Verified selecting `Block Forever` adds the site to blocked list
- Verified site settings shows both sites under allowed/blocked respectively
- Verified closing `browserleaks.com/geo` tab resets the site permission from site settings
- Verified revisiting the page on a new tab triggers the prompt again

</details>

<hr>

### 24-hour / 1-week cases

<details>
<summary>23 hrs test </summary>
<br>

- Verified allowing permission on a site for 24hrs works fine
- Verified restarting the browser and loading the page doesn't trigger permission prompt
- Verified moving device date ahead to 23hrs and reloading the page/opening in a new tab doesn't trigger the permission prompt

</details>
<details>
<summary>25 hrs test </summary>
<br>

- Verified allowing permission on a site for 24hrs works fine
- Verified restarting the browser and loading the page doesn't trigger permission prompt
- Verified moving device date ahead to 25hrs and reloading the page/opening in a new tab trigger the permission prompt

</details>
<details>
<summary>6 Days 12hrs test </summary>
<br>

- Verified allowing permission on a site for 1 week works fine
- Verified restarting the browser and loading the page doesn't trigger permission prompt
- Verified moving device date ahead to 6 days & 12 hrs ahead and reloading the page/opening in a new tab doesn't trigger the permission prompt

</details>
<details>
<summary>8 days Test</summary>
<br>

- Verified allowing permission on a site for 1 week works fine
- Verified restarting the browser and loading the page doesn't trigger permission prompt
- Verified moving device date ahead to 8days and reloading the page/opening in a new tab trigger the permission prompt

</details>

### Allow/Block forever cases
<hr />
<details>
<summary>Allow forever (Location)</summary>
<br>

- Verified selecting location on `https://permission.site` triggers permission prompt
- Verified able to set the permission to `forever`
- Verified reloading the page doesn't trigger the prompt
- Verified site settings adds the site to allow list
- Verified moving device date ahead by a month and revisiting the page in a new tab doesn't trigger the notification

</details>
<details>
<summary>Block Forever (Notifications)</summary>
<br>

- Verified selecting location on `https://permission.site` triggers permission prompt
- Verified able to set the permission to `Block Forever`
- Verified site settings adds the site to block list 
- Verified moving device date ahead by a month and revisiting the page in a new tab doesn't trigger the notification

</details>

<hr>

### Consecutive-revocation cases

<details>
<summary>10 sec repeat permission</summary>
<br>

- Verified launching with command line `--permission-lifetime-test-seconds=10` shows 10 sec option in permission prompt
- Verified setting the prompt for 10 sec on `https://permission.site` works
- Opening a new tab and visiting `https://browserleaks.com/geo` triggers the prompt and set it to 10 sec option
- Wait for 10sec and navigate back to permission site via bottom toolbar swipe prompts again to set permission
- Swipe back to browserleaks tab prompts on that page as well

</details>


### Private tab test

<details>
<summary>Permission on private tabs</summary>
<br>

- Verified permission prompt shows up on private tab as well
- Verified setting persmisson forever works on private tab
- Verified closing the private tab and opening a new one and visiting the same page triggers the permission prompt
- Verified during an active session, setting permisson on private tab is only valid for the session
- Verified during an active session, setting permission forever and opening the same page on normal tab still prompts for permission setting

</details>

- Verified clearing site setting via clear data resets all permissions set on any page

</details>

----------------------------

<details>
<summary>Verification passed on Samsung Tab A with Android 10 running 1.24.81 x64 build</summary>

### Time Based checks

<details>
<summary>20 Sec timer - Allow (Camera + Microphone)</summary>
<br>

- Verified passing argument to set permission timer to 20 sec shows up as an option
- Verified selecting 20 sec option and allow enables the Camera + Microphone on the site and system notification shows up
- Verified site is added under allow list for both Camera + Microphone
- Verified after 20 sec the site permissions are removed automatically
- Verified reloading the page and selecting Camera on the page triggers the permission prompt again

20 Sec option | Select 20 sec timer | Site requesting permission | Site added to allow list 
-- | -- | -- | --


</details>

<details>
<summary>20 Sec timer - Block Forever (Camera + Microphone)</summary>
<br>

- Verified setting permission to `Block Forever` adds an entry under blocked list for the site
  <img width=300 src=>

</details>

<hr>

### Origin-based cases

<details>
<summary>Origin-based behaviour, multiple tabs (Location)</summary>
<br>

- Verified visiting `browserleaks.com/geo` triggers permission prompt
- Verified selecting `Until I close this page` and select allow sets the permission for the page and detects location
- Verified visiting permission.site on a second tab and selecting location triggers prompt
- Verified selecting `Block Forever` adds the site to blocked list
- Verified site settings shows both sites under allowed/blocked respectively
- Verified closing `browserleaks.com/geo` tab resets the site permission from site settings
- Verified revisiting the page on a new tab triggers the prompt again

</details>

<hr>

### 24-hour / 1-week cases

<details>
<summary>23 hrs test </summary>
<br>

- Verified allowing permission on a site for 24hrs works fine
- Verified restarting the browser and loading the page doesn't trigger permission prompt
- Verified moving device date ahead to 23hrs and reloading the page/opening in a new tab doesn't trigger the permission prompt

</details>
<details>
<summary>25 hrs test </summary>
<br>

- Verified allowing permission on a site for 24hrs works fine
- Verified restarting the browser and loading the page doesn't trigger permission prompt
- Verified moving device date ahead to 25hrs and reloading the page/opening in a new tab trigger the permission prompt

</details>
<details>
<summary>6 Days 12hrs test </summary>
<br>

- Verified allowing permission on a site for 1 week works fine
- Verified restarting the browser and loading the page doesn't trigger permission prompt
- Verified moving device date ahead to 6 days & 12 hrs ahead and reloading the page/opening in a new tab doesn't trigger the permission prompt

</details>
<details>
<summary>8 days Test</summary>
<br>

- Verified allowing permission on a site for 1 week works fine
- Verified restarting the browser and loading the page doesn't trigger permission prompt
- Verified moving device date ahead to 8days and reloading the page/opening in a new tab trigger the permission prompt

</details>

### Allow/Block forever cases
<hr />
<details>
<summary>Allow forever (Location)</summary>
<br>

- Verified selecting location on `https://permission.site` triggers permission prompt
- Verified able to set the permission to `forever`
- Verified reloading the page doesn't trigger the prompt
- Verified site settings adds the site to allow list
- Verified moving device date ahead by a month and revisiting the page in a new tab doesn't trigger the notification

</details>
<details>
<summary>Block Forever (Notifications)</summary>
<br>

- Verified selecting location on `https://permission.site` triggers permission prompt
- Verified able to set the permission to `Block Forever`
- Verified site settings adds the site to block list 
- Verified moving device date ahead by a month and revisiting the page in a new tab doesn't trigger the notification

</details>

<hr>

### Consecutive-revocation cases

<details>
<summary>10 sec repeat permission</summary>
<br>

- Verified launching with command line `--permission-lifetime-test-seconds=10` shows 10 sec option in permission prompt
- Verified setting the prompt for 10 sec on `https://permission.site` works
- Opening a new tab and visiting `https://browserleaks.com/geo` triggers the prompt and set it to 10 sec option
- Wait for 10sec and navigate back to permission site via bottom toolbar swipe prompts again to set permission
- Swipe back to browserleaks tab prompts on that page as well

</details>


### Private tab test

<details>
<summary>Permission on private tabs</summary>
<br>

- Verified permission prompt shows up on private tab as well
- Verified setting persmisson forever works on private tab
- Verified closing the private tab and opening a new one and visiting the same page triggers the permission prompt
- Verified during an active session, setting permisson on private tab is only valid for the session
- Verified during an active session, setting permission forever and opening the same page on normal tab still prompts for permission setting

</details>

- Verified clearing site setting via clear data resets all permissions set on any page

</details>
