### ISSUE TITLE
Add selected state to the IPFS icon in settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14125]
## Description 

IPFS icon on settings page looks dull

## Steps to Reproduce

   1. Install 1.22.19 x64 build
   2. Open Settings page
   3. Check IPFS icon when not selected
   4. Check IPFS icon when `brave://settings/ipfs` is selected
   5. No change in icon. Looks dull

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/107726119-d9a66680-6cdf-11eb-83b2-c4b44f39547c.png)

## Expected result:
Icon should be highlighted when the setting is selected similar to other ones

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.22.19 Chromium: 89.0.4389.40 (Official Build) nightly (64-bit)
-- | --
Revision | `2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}`
OS | Windows 10 OS Version 2009 (Build 19042.804)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by rebron** [comment]
IPFS icon in normal state could also be brightened up. Icon looks like it's in a disabled state compared to the other icons.

**Comment by karenkliu** [comment]
We are addressing updated icons and colors in light/dark theme in this issue https://github.com/brave/brave-browser/issues/13688

Closing as dupe
