### ISSUE TITLE
brave://adblock crashes browser after interaction from multiple tabs

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#14123]
Using the following steps, I can get a 100% reproducible crash:

- Open brave://adblock in a new tab
- Open brave://adblock in a second new tab
- Enable any filter list in the first tab
- Enable the same filter list in the second tab

Ideally, toggling a filter list would update _all_ open brave://adblock tabs, like how it works with brave://settings. At the very least, it should not crash the entire browser.

Crash occurs at:
```
[FATAL:ad_block_regional_service_manager.cc(181)] Check failed: it != regional_services_.end().
```

**Comment by iefremov** [comment]
people encounter it in the wild https://brave.sp.backtrace.io/p/brave/explore?time=month&filters=((callstack.functions%2Ccontains%2CBraveComponent)%2C_deleted%3D0%2C(ver%2Cregex%2C%2290%7C91.*%22)%2Cptype%3Dbrowser)&aggregations=((channel%2Cdistribution)%2C(ver%2Cmax)%2C(ver%2Cmin)%2C(ver%2Cdistribution%2C3)%2C(callstack%2Chead))&

```
[ 00 ] brave_component_updater::BraveComponent::Unregister()
[ 01 ] brave_component_updater::BraveComponent::Unregister()
[ 02 ] brave_shields::AdBlockRegionalServiceManager::EnableFilterList(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)
[ 03 ] (anonymous namespace)::AdblockDOMHandler::HandleEnableFilterList(base::ListValue const*)
[ 04 ] content::mojom::WebUIHostStubDispatch::Accept(content::mojom::WebUIHost*, mojo::Message*)

```

**Comment by goodov** [comment]
it currently crashes in a slightly different way https://github.com/brave/brave-browser/issues/31561

**Comment by kjozwiak** [comment]
The above requires `1.57.52` or higher for `1.57.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using the following version(s):

```
Brave	1.57.53 Chromium: 116.0.5845.114 (Official Build) (64-bit) 
Revision	b7a154dc9e27b02528cb2cfc8010d8edf1e35571
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified STR in https://github.com/brave/brave-browser/issues/14123#issue-806877760
- Verified that browser does not crash when using same filter lists in `brave://adblock` on multiple tabs

First Tab | Second Tab | Tab View
-|-|-
![Screenshot 2023-08-23 at 12 19 34 PM](https://github.com/brave/brave-browser/assets/17885425/0133f21e-a76b-4dd1-9a5b-943ab033f002) | ![Screenshot 2023-08-23 at 12 19 38 PM](https://github.com/brave/brave-browser/assets/17885425/a4de2ae5-bba8-433b-a9af-a210265d86d2) | ![Screenshot 2023-08-23 at 12 19 43 PM](https://github.com/brave/brave-browser/assets/17885425/90948ee6-4fac-4d2c-bf4c-15395ab5e26a)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using the following version(s):

```
Brave	1.57.53 Chromium: 116.0.5845.114 (Official Build) (64-bit) 
Revision	b7a154dc9e27b02528cb2cfc8010d8edf1e35571
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified STR in https://github.com/brave/brave-browser/issues/14123#issue-806877760
- Verified that browser does not crash when applying the same filter lists in `brave://adblock` on multiple tabs

![Screenshot 2023-08-23 at 12 30 01 PM](https://github.com/brave/brave-browser/assets/17885425/25b2fa43-01df-472c-817d-d0932b489268)
