### ISSUE TITLE
Everything flicker since last update.

### ISSUE THREAD

**Issue by Ayfri** [brave/brave-browser#14139]
## Description 

I don't know why but since the last version everything flicker, sometimes it's just part of the screens when scrolling, or when changing tabs, sometimes part of the screen which remains when changing tabs (and disappear a few seconds after), and sometimes this happens a lot for a few seconds making the Browser unusable during that time.

## Steps to Reproduce

Start brave.
Just change tabs and see a lot of elements or just part of the screen flickering and staying between tab changes.

## Actual result:

Everything is broken.

## Expected result:
No flickering.

## Reproduces how often: 

All the time.

## Brave version (brave://version info)

Version 1.20.103 Chromium: 88.0.4324.152 (Build officiel) (64 bits)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

I don't know how to change the channel.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards? 
No.
- Is the issue reproducible on the latest version of Chrome? 
No.

## Miscellaneous Information:

I have the latest NVidia Drivers and the latest beta and this Windows version:
Edition: Windows 10 Family
Version: 20H2
Installed on: ‎30/‎08/‎2020
OS Version: 19042.804
Experience: Windows Feature Experience Pack 120.2212.2020.0

**Comment by nickallevato** [comment]
Same. I held off updating to latest for unknown reasons. When I updated, this started.

Disabling Hardware Acceleration 'fixes' the issue.
ALSO PLEASE NOTE:

I am running multipl GPUs. I am running latest nvidia consumer drivers.
I run a geforce and a quadro gpu.

THIS DOES NOT HAPPEN ON MY SECONDARY GPU / QUADRO GPU!

I suspect this has something to do with how Brave allocates hardware acceleration. 
Notice:
 - Video decode occurs on primary GPU.
 - Video is actually played back on secondary GPU. Secondary GPU is not using video decode 
- Copy function has 1-2% load (likely for decoded video send to second GPU

I run the latest Windows 10 Pro version: 2004
Ryzen CPU  3800x 
Asus x570 mobo
Let me know what else you need

**Comment by nickallevato** [comment]
update: The EXACT  SAME THING happens with VMWare Workstation. So this looks like an issue with NVIDIA driver more than Brave. I will try rolling back driver.

**Comment by nickallevato** [comment]
update: rolling back Nvidia driver fixed issue in Vmware and Brave.

WORKS: 461.09-desktop-win10-64bit-international-dch-whql.exe

DOES NOT WORK: 461.40-desktop-win10-64bit-international-nsd-dch-whql.exe

**Comment by nickallevato** [comment]
Update from the update:

THIS IS THE WORKING NVIDIA DRIVER VERSION: 460.89-desktop-win10-64bit-international-dch-whql.exe

Everything is broken in all of 461.XX

@Ayfri try rolling back nvidia drivers to 460.XX series.

**Comment by Goldman1337** [comment]
happening to me in 465.89

**Comment by rebron** [comment]
Hi @Ayfri Still having issues with our latest version 1.24.82? 
brave://settings/system If you toggle hardware acceleration off that does help. 

Also, if you can paste your data from brave://gpu that would help us out.

**Comment by Ayfri** [comment]
Hi, no everything is good for now !

**Comment by rebron** [comment]
Closing per last comment. Looks like we're all good now. Thanks @Ayfri
