### ISSUE TITLE
Sync Settings doesnt take effect and deletes fromself

### ISSUE THREAD

**Issue by lxwulf** [brave/brave-browser#14131]
## Description 

When I set up my sync settings it doesn't take effect. Also, when I relaunch brave the settings are gone and nothing would be synced....

## Steps to Reproduce

   1. Install Brave Browser Nightly
   2. Set Sync Feature on
   3. Set up your sync settings
   4. Relaunch Brave
   5. Settings are gone

## Actual result:

Sync settings are not saved and turned off

## Expected result:
Sync settings should be saved and active

## Reproduces how often: 

Very Easy

## Brave version (brave://version info)

Brave 1.22.19 Chromium: 89.0.4389.40 (Official Build) nightly (64-bit)
Revision 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
I don't know
- Can you reproduce this issue with the beta channel? 
I don't know
- Can you reproduce this issue with the nightly channel? 
Yes!

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
I don't know

**Comment by rebron** [comment]
@btlechowski Have you run into this one? 
cc: @AlexeyBarabash

**Comment by btlechowski** [comment]
I was not able to reproduce the issue on:

Brave | 1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Linux

The sync settings were saved and loaded after restart.

@lxwulf Does it happen like on the screenshot below? 
![image](https://user-images.githubusercontent.com/34715963/109818178-ff65c200-7c32-11eb-8a3e-7c8b0d61986c.png)
It happens when sync fails to connect to sync server (e.g. no internet). If internet is back then sync should recover.

**Comment by lxwulf** [comment]
In my case the problem appears only on one Windows machine of my own. But I would try it out in a couple of hours (hopefully) again. When it doesn't work I try to record it. On my other Windows Machine, Linux and my Phone (Android, BB-Beta) it works flawless. On my main computer it doesn't work as said I trying to investigate more for you.

**Comment by yasharya2901** [comment]
I am having this problem of can't leaving the sync chain. It also cannot sync my phone's password and bookmarks and it is becoming more and more annoying to use Brave as my browser.

**Comment by rebron** [comment]
@lxwulf Are you still having issues on your Windows machine?

**Comment by lxwulf** [comment]
Sadly yes, still can't leave this sync chain. Maybe I misunderstand the feature. All other Devices are off the sync chain. There is only my Desktop Computer left. My other three devices, my Android Phone (Android 11), Linux (Fedora 34) and my Surface (W10 20H4) are working together but not my Desktop PC. I want to have it in the Sync Chain of my other three devices. But for that i need to leave my sync chain right?

Greets LxWulf

**Comment by lxwulf** [comment]
Is there really no possibility how I or better say we can fix this? I would be very happy to sync my settings and also my bookmarks...

I also don't really want to reinstall the browser...but I think I need to at the end....

Greets LxWulf

**Comment by lxwulf** [comment]
I reinstalled it, and now it works, also I changed from nightly to stable...

Thank you anyway for trying to help!

Greets LxWulf
