### ISSUE TITLE
brave://welcome modal has an 8px border around it

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#14137]
## Description 
White 8px border is added to brave://welcome 

Noticed on `1.22.22` by @LaurenWags ; was not present on `1.22.19`.

Suspected PR that broke this:
https://github.com/brave/brave-core/pull/7919

## Steps to Reproduce

   1. Install 1.22.22
   2. Visit brave://welcome

## Actual result:
![image](https://user-images.githubusercontent.com/4733304/107825178-8829c600-6d37-11eb-9a27-672911d00a0f.png)

## Expected result:
No white 8 pixel border

## Reproduces how often: 
100%

## Brave version (brave://version info)
`1.22.22` 

## Version/Channel Information:
Nightly

- Can you reproduce this issue with the current release? n
- Can you reproduce this issue with the beta channel? n
- Can you reproduce this issue with the nightly channel? y

**Comment by Miyayes** [comment]
Seems to extend beyond brave://welcome. CSS seems borked on all other interfaces as well (e.g., brave://rewards).

**Comment by GeetaSarvadnya** [comment]
This issue is happening for brave://wallet also

![image](https://user-images.githubusercontent.com/38657976/107924107-72670b80-6f98-11eb-89d0-adaa8328c0b4.png)

**Comment by LaurenWags** [comment]
@GeetaSarvadnya try a newer Nightly like 1.22.24

**Comment by GeetaSarvadnya** [comment]
Working fine in `Windows 10 x64 - Version 1.22.25 Chromium: 89.0.4389.48`

**brave://welcome**
![image](https://user-images.githubusercontent.com/38657976/108023548-c03b4c80-7048-11eb-8813-bf8a90893d95.png)

**brave://rewards**
![image](https://user-images.githubusercontent.com/38657976/108023591-dd701b00-7048-11eb-8627-0360ad4e6952.png)

**brave://wallet**
![image](https://user-images.githubusercontent.com/38657976/108023572-ce896880-7048-11eb-8c0c-8c8b814b6569.png)

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` using 

Brave | 1.22.34 Chromium: 89.0.4389.48 (Official Build) nightly (x86_64)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | macOS Version 11.2.1 (Build 20D74)

I checked dark and light versions of `brave://welcome`, as well as `brave://rewards` and `brave://wallet` panels.

<details>
<summary>
Screenshots:
</summary>
<img width="1015" alt="Screen Shot 2021-02-18 at 2 29 42 PM" src="https://user-images.githubusercontent.com/387249/108430486-4a74e380-71f6-11eb-9637-3a602176e614.png">
<img width="1015" alt="Screen Shot 2021-02-18 at 2 29 56 PM" src="https://user-images.githubusercontent.com/387249/108430497-4e086a80-71f6-11eb-8389-4a71b8700151.png">
<img width="1367" alt="Screen Shot 2021-02-18 at 2 30 17 PM" src="https://user-images.githubusercontent.com/387249/108430495-4d6fd400-71f6-11eb-84fe-3e3a327ffd87.png">
<img width="1441" alt="Screen Shot 2021-02-18 at 2 30 42 PM" src="https://user-images.githubusercontent.com/387249/108430494-4c3ea700-71f6-11eb-8feb-822074f9b129.png">
</details>
