### ISSUE TITLE
BAP modal issues

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14136]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/13798

Two issues found with the BAP modal (not tooltip)
1. unable to scroll BAP modal when in landscape mode (possibly only show modal in portrait mode --> https://bravesoftware.slack.com/archives/C0816QH3R/p1613161177249100?thread_ts=1613160945.247600&cid=C0816QH3R)
2. Styling of the modal looks a bit odd (large white bar at the top which is not in original issue design)

## Steps to reproduce 

   1. Set device to Japan/Japanese
   2. Install `1.22.22` Nightly, enable staging env for Rewards
   3. Relaunch
   4. Tap on Rewards icon, dismiss onboarding
   5. Claim UGP grant
   6. Close app
   7. Advance date by 3 days
   8. Orient device to be landscape
   9. Launch Nightly
   10. On tooltip, tap Learn More

## Actual result 
Modal is displayed, can't scroll
![modal-landscape](https://user-images.githubusercontent.com/28145373/107819428-283b1b80-6d47-11eb-94e7-bf7ba6432363.png)

## Expected result
Able to scroll in modal (if we keep it in this view). Layout should more closely match original in https://github.com/brave/brave-browser/issues/13798#issue-795249774

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? n/a
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 5.1
   
## Brave version
1.22.22

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @deeppandya @codybanxs @Miyayes @brave/legacy_qa

**Comment by Miyayes** [comment]
@deeppandya is it easy to remove the white space in this case? And can you use `overflow: scroll` for the text?

**Comment by deeppandya** [comment]
> @deeppandya is it easy to remove the white space in this case? And can you use `overflow: scroll` for the text? 
> 
> 

@Miyayes for sure. I will update it in the issue.

**Comment by kjozwiak** [comment]
@Miyayes @deeppandya assuming we want this in `1.20.x` for the BAP release so I moved it into https://github.com/brave/brave-browser/milestone/173 and labelling it as a `release/blocking`. If we don't care about getting this into the `1.20.x - Release #2` and are fine with this going into `1.21.x`, please remove it from the millstone.

**Comment by srirambv** [comment]
This is an issue on bigger screen device as well. If orientation is set to landscape the modal shows full text but the <kbd>Ok</kbd> is not shown 
<img width=800 src=https://user-images.githubusercontent.com/17010094/107952457-b1459300-6f91-11eb-81eb-7e93186864e7.png>

**Comment by Miyayes** [comment]
@deeppandya Is there a way for them to click out of this modal if "OK" is not visible in landscape?

**Comment by kjozwiak** [comment]
Moving this into `1.22.x` as the BAP work is being reverted via https://github.com/brave/brave-core/pull/8088. Once we have more information next week, we'll re-revert https://github.com/brave/brave-core/pull/8088 and move everything back into `1.21.x` and release `1.21.x - Release #2`.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.21.76 x64 build
- Verified browser orientation is force changed to portrait when the modal is shown

https://user-images.githubusercontent.com/17010094/110787931-dc0bca00-8265-11eb-856f-371ab17b5d64.mp4

------------
Verification passed on OnePlus 6T with Android 10 running 1.21.76 x64 build
- Verified browser orientation is force changed to portrait when the modal is shown

https://user-images.githubusercontent.com/17010094/110788001-f3e34e00-8265-11eb-84bf-e28da6926e97.mp4
