### ISSUE TITLE
brave://settings has two Widevine settings and it's not obvious what they do

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#14130]
### Install happy path
1. Fresh profile
2. Visit brave://settings and verify `Widevine` is disabled
3. Visit Netflix, login, and watch something
4. Verify you see a prompt
5. Accept the prompt / install Widevine
6. Visit brave://settings and verify `Widevine` is enabled

### Deny prompt path
1. Fresh profile
2. Visit brave://settings and verify `Widevine` is disabled
3. Visit Netflix, login, and watch something
4. Verify you see a prompt
5. Tick the `Never show this again` box and deny access
6. Verify video doesn't load
7. Refresh page or visit another video
8. Verify prompt not shown again
9. Visit brave://settings and manually enable `Widevine` 
10. Visit another video and verify it plays as expected (no prompt)

## Description 
Discovered by @GeetaSarvadnya:
![image](https://user-images.githubusercontent.com/4733304/107741769-a7d2d700-6cc2-11eb-8311-37d4feb9902c.png)

With the recent addition of `Enable Widevine` by @simonhong with https://github.com/brave/brave-core/pull/7554, there are now two toggles:
- One is toggling whether or not to show a prompt when Widevine is requested to be used
- One is toggling whether Widevine is actively installed or not (if disabled, it will uninstall the binaries)

A few ways to resolve:
1. Only show one of these
2. Find a better way to reword or rephrase each setting

**Comment by bsclifton** [comment]
Per Slack discussion https://bravesoftware.slack.com/archives/C7VLGSR55/p1612981235355800?thread_ts=1612956954.340600&cid=C7VLGSR55

I think we can probably remove the `Ask when a site wants to install Widevine on your computer` setting. **We just need to choose what to do in that case when a user visits a Widevine site and has Widevine disabled**
1. Should we still show the prompt to them?
2. If not and they forgot they disabled - how would they know we're respecting their preference and they aren't experiencing a bug (should we show a visual indicator? this might already be present for Widevine items)

**Comment by karenkliu** [comment]
We should keep showing the Widevine prompt unless they have clicked on "Don't show again" checkbox in the prompt.

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` on macOS Big Sur (11.2.1) with 

Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

<details>
<summary>
Install happy path
</summary>

* Fresh profile
* Visit `brave://settings` and verify Widevine is disabled
<img width="1213" alt="Screen Shot 2021-02-22 at 5 07 23 PM" src="https://user-images.githubusercontent.com/387249/108790595-f50c3f80-7531-11eb-845b-46bdbc5e902c.png">
* Visit Netflix, log in, and watch something
* Verify you see a prompt
<img width="1012" alt="Screen Shot 2021-02-22 at 5 08 19 PM" src="https://user-images.githubusercontent.com/387249/108790508-b9717580-7531-11eb-911a-a62382e2c1c3.png">
* Accept the prompt / install Widevine
* Visit `brave://settings` and verify Widevine is enabled
</details>

<details>
<summary>
Deny-prompt path
</summary>

* Fresh profile
* Visit `brave://settings` and verify Widevine is disabled
* Visit Netflix, log in, and watch something
* Verify you see a prompt
* Tick the `Don't ask again` box and deny access by clicking `Block`
<img width="979" alt="Screen Shot 2021-02-22 at 5 12 09 PM" src="https://user-images.githubusercontent.com/387249/108790904-aa3ef780-7532-11eb-9cc4-772120d0853e.png">

* Verify video doesn't load
<img width="979" alt="Screen Shot 2021-02-22 at 5 12 35 PM" src="https://user-images.githubusercontent.com/387249/108790900-aa3ef780-7532-11eb-9838-a7937ed001ee.png">

* Refresh page or visit another video

* Verify prompt not shown again

* Visit `brave://settings` and manually enable Widevine
<img width="979" alt="Screen Shot 2021-02-22 at 5 13 12 PM" src="https://user-images.githubusercontent.com/387249/108790899-aa3ef780-7532-11eb-8e2c-5100bd3935d3.png">
* Visit another video and verify it plays as expected (no prompt)

<img width="979" alt="Screen Shot 2021-02-22 at 5 13 19 PM" src="https://user-images.githubusercontent.com/387249/108790896-a9a66100-7532-11eb-867f-88c824d3d5c2.png">
</details>
