### ISSUE TITLE
Missing blocked script on academy.com and marshalls.com

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#14140]
## Description 
Brave adblock on picking up tracker on `https://www.academy.com/` and `https://www.marshalls.com/`

## Steps to Reproduce

   1. Visit `https://www.marshalls.com/us/store/index.jsp` or `https://www.academy.com/`
   2. Expect the following url to be blocked: `https://www.marshalls.com/staticweb/4dff6f6f757ti2576415b5ab9227f7a1f` or `https://www.academy.com/webcontent/4c20cad4ui1706edd36f4f0f35bf2a`
   3. Not blocked in Brave shields.

## Actual result:
Script not being blocked

## Expected result:
Expect script to be blocked

## Reproduces how often: 
Easily 

## Brave version (brave://version info)
`Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc: @antonok-edm   
Easyprivacy uses: 
`/^https?:\/\/www\.marshalls\.com\/staticweb\/[a-z0-9]{20,}/$script,xmlhttprequest,domain=marshalls.com`

Guessing is a regex parsing issue.

A few other sites are using similar regex: from https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_specific.txt#L2656

`/^https?:\/\/www\.macys\.com\/clientlibs\/[a-z0-9]{20,}/$script,xmlhttprequest,domain=macys.com`
`/^https?:\/\/www\.sierra\.com\/resource\/[a-z0-9]{20,}/$script,xmlhttprequest,domain=sierra.com`
`/^https?:\/\/www\.staples\.com\/yuolsoiifpm\/[a-z0-9]{20,}/$script,xmlhttprequest,domain=staples.com`
`/^https?:\/\/www\.usbank\.com\/webcontent\/[a-z0-9]{20,}/$script,xmlhttprequest,domain=usbank.com`

**Comment by antonok-edm** [comment]
@ryanbr good find, should be fully fixed by https://github.com/brave/brave-core-crx-packager/pull/204 without needing any additional browser updates

**Comment by antonok-edm** [comment]
Should be solved as of `1.0.850` of the adblock DAT
