### ISSUE TITLE
No way to delete a Crypto Wallet account

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#14141]
## Description 
There appears to be no way to delete a Brave created crypto wallet account. Even going to Settings -> Contacts -> My Wallet Accounts -> Edit doesn't show a delete option.

## Steps to Reproduce
1. Create a Crypto Wallet account using Brave.
2. Create a second crypto wallet account.
3. Notice that there's no way to delete either account.

## Actual result:
![image](https://user-images.githubusercontent.com/241316/107840380-26815000-6d67-11eb-8f42-4e1027e640e3.png)

## Expected result:
There should be some option to delete individual accounts. When all accounts have been deleted, the extension should once again show the introduction page where they ask whether you want to create a local wallet or add Trezor hardware wallets.

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by urbenlegend** [comment]
Appears to be a resurfacing of this issue: https://github.com/brave/brave-browser/issues/10999

**Comment by srirambv** [comment]
#10999 was specific to not showing delete account option so its not a resurfacing issue.

As for deleting individual account there is no such option even on MetaMask. Here's a sample screenshot of multiple accounts listed 
![image](https://user-images.githubusercontent.com/17010094/107912271-21362800-6f56-11eb-91c1-7c2e07e135c3.png)


This is probably a feature that we may have to introduce in Brave Crypto Wallet 

cc: @bbondy @rebron

**Comment by srirambv** [comment]
from @unpaid via https://github.com/brave/brave-browser/issues/10999#issuecomment-780787367

> Hello, I am using Brave Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit) on Windows 10 Pro Version 20H2 (OS Build 19042.804) and am having the same issue, however it seems I can get the delete button to appear by making the account appear as a contact, though the button does nothing other than delete the contact. I am unsure if this functionality is intentional or not, or perhaps another bug altogether, but I encountered it while trying to delete the wallet. The steps I used to reproduce this is as follows:
> 1. Go to brave://wallet/
> 2. Click on your profile avatar
> 3. Click on Settings
> 4. Click on Contacts
> 5. Click on My Wallet Accounts
> 6. Select the wallet you want to delete
> 7. Click Edit
> 8. Click Save
> 9. Click on Contacts
> 10. Select the wallet you want to do delete
> 11. Click Edit
> 
> ![Screenshot 2021-02-18 043129](https://user-images.githubusercontent.com/35709143/108253804-e88c8d80-71a5-11eb-8670-d03e72f0671b.png)

**Comment by Mansarde** [comment]
@srirambv 
> As for deleting individual account there is no such option even on MetaMask.

Do you know if it is at least possible to delete some files in the Brave profile folder in order to reset the wallet back to its initial state (i.e. when there were no wallets yet)?

**Comment by sas84-HeavyHitR** [comment]
Hey Team,

Any updates on when we can expect this functionality to be available? Are there any workarounds, hacks, or actual availability of this feature in a beta or nightly release? What are the stumbling blocks at play as things sit today?

**Comment by bbondy** [comment]
We're working on a new wallet now that you'll be able to disable if you want to.  The old one will be by default disabled when that is released.

What you can do though to effectively disable Crypto Wallets is to go to brave://settings/wallet and set the Dapp provider to None (or if you have MetaMask installed set it to that).
And make sure "Load Crypto Wallets on startup" is turned off. 

Then no wallet code will be loaded.

**Comment by bbondy** [comment]
Not at this time, but we're working on a new wallet now that will allow this functionality.

**Comment by AdrianPowery2000** [comment]
<img width="641" alt="Screen Shot 2021-05-12 at 12 52 14 PM" src="https://user-images.githubusercontent.com/83601310/118021604-0d198100-b321-11eb-8f54-493022e99431.png">
+1

**Comment by anishp55** [comment]
hey friends, what is the status of this?  do we need to uninstall brave to delete a wallet?

**Comment by srirambv** [comment]
Crypto Wallet is not replace with Brave Wallet which can be reset completely. If you are on older deprecated Crypto Wallet you should be able to migrate to the new Brave Wallet. Closing this issue as a wontfix.

**Comment by anishp55** [comment]
@srirambv this is not true.  i am not able to remove either wallet completely unless i uninstall brave and clean up after it.  there needs to be away to completely delete *both* wallets.  this is important for people that are upgrading and dont want to loose all of there settings etc.

**Comment by bbondy** [comment]
Re-opening until we have some good steps for how to purge the old Crypto Wallets. 
For the new wallet you can do it in brave://settings/wallet with the Reset option.

**Comment by LeaTex** [comment]
still waiting for this feature.

**Comment by bbondy** [comment]
I believe this issue is just about removing a single account and not the whole extension.
We're not planning to update the deprecated Crypto Wallets extension. 
We recommend migrating to the new Brave Wallet which has a large team working on it.

If there are people wondering how to purge the old extensions completely...
I.e. if you'd like to completely remove any trace of Crypto Wallets then you can:

Close Brave.
Move ~/Library/Application\ Support/BraveSoftware/Brave-Browser/odbfpeeihdkbihmopkbjmoonfanlbfcl/ to a new location (backup)
Open Brave.
Go to brave://settings/wallet and change the default wallet setting to Brave Wallet (Prefer extensions) or None

**Comment by LeaTex** [comment]
Exactly, this issue is just about removing a single account. How can I do that?

It's a feature request, why did you close it?

**Comment by bbondy** [comment]
Because the old Crytpo Wallets extension is no longer supported, we don't work on it and will not in the future.
There's a similar issue for the new wallet that we do work on being tracked here:
https://github.com/brave/brave-browser/issues/19761
