### ISSUE TITLE
Block `Cookie set by JavaScript should not be sent over HTTP`

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#14149]
## Description 
When visiting `https://browseraudit.com/` We get one critical issue related to Cookies over http
 
## Steps to Reproduce

   1. Open `https://browseraudit.com/`
   2. Let it complete it run
   3. End of the benchmark run, it will show scores, with one "Critical". (See Screenshot below)
  
## Actual result:

![browseraudit1](https://user-images.githubusercontent.com/1659004/107874194-adc3f480-6f1c-11eb-80db-6b049412cf2d.png)
![browseraudit](https://user-images.githubusercontent.com/1659004/107874199-b7e5f300-6f1c-11eb-854e-3963a7719904.png)

## Expected result:
Block `Cookie set by JavaScript should not be sent over HTTP`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)
`Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Issue was discussed on Twitter, I've created this report to detail the issue

**Firefox passes test (Denys js setting cookies via http)**
![firefox-browser-audit](https://user-images.githubusercontent.com/1659004/107874532-27f57880-6f1f-11eb-8663-468aacd0c816.png)
**Chrome:** 
![chrome-browser-audit](https://user-images.githubusercontent.com/1659004/107874557-507d7280-6f1f-11eb-84cb-07810ad5242a.png)

cc: @pes10k

**Comment by pes10k** [comment]
Thanks for the heads up on this @ryanbr!  Let me see if i can figure out whats going on here…

**Comment by pes10k** [comment]
So turns out this is a test bug.  Chromium automatically upgrades the request to HTTPS, which causes the cookie to be sent (bc its now HTTPS) which confuses the test (which doesn't expect the upgrade and so doesn't expect the cookie).  Firefox seems to not upgrade the request, which is what causes the test to be green for them.

Thanks for flagging this though, i was pretty nervous by the issue, so it was good to dig in and figure out what was going on :)
