### ISSUE TITLE
clicking the "FAQ" link within "Add Funds" should open a new tab 

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1414]
## Description 

When viewing the `Add funds to your Brave wallet` under `chrome://rewards/`, clicking on the FAQ link will open the page within the same tab which is a bit annoying. If a new user wants to quickly read through the FAQ's, they'll need to navigate back to `chrome://rewards/` in a new tab.

## Steps to Reproduce

   1. launch b-c on either `0.54.x` (currently `dev`) or `0.55.x` (currently `beta`)
   2. visit `chrome://rewards/` and enable rewards
   3. once enabled, click on `Add Funds`
   4. click on `FAQ` at the bottom of the page

## Actual result:

The FAQ page loads within the same tab. A user that wants to read the FAQ and switch back and forth will either need to use the navigation buttons or open a new tab and navigate back to `chrome://rewards/`.

## Expected result:

The FAQ page should open in a new tab.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds?

Happens on both of the following build:

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

Brave | 0.56.1 Chromium: 70.0.3538.22 (Official Build) dev (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

- Does it reproduce on browser-laptop? 

N/A - However, links like this always opened in new tabs under `about:preferences#payments` when using b-l.

**Comment by Bad-Science** [comment]
Opened https://github.com/brave/brave-ui/pull/188.

Thanks for the good labeling.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - PASSED

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X
