### ISSUE TITLE
Enable Widevine setting is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14144]
Follow up from https://github.com/brave/brave-browser/issues/2791

## Steps to Reproduce

1. Run Brave in Polish (PL) locale
1. Open brave://settings/extensions
1. Check `Enable Widevine`

## Actual result:

`Enable Widevine` setting is not translated
`Enable Widevine` description is not translated
![image](https://user-images.githubusercontent.com/34715963/107854950-bd114800-6e1f-11eb-9c5b-08cf727d3f73.png)
![image](https://user-images.githubusercontent.com/34715963/107854716-1f694900-6e1e-11eb-8f37-94b2bd2222a8.png)

## Expected result:
`Enable Widevine` setting is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.21.52 Chromium: 88.0.4324.152 (Official Build) dev (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Brave | 1.22.23 Chromium: 89.0.4389.48 (Oficjalna wersja) nightly (64-bitowa)
-- | --
Wersja | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
System operacyjny | Linux

cc @brave/legacy_qa @mkarolin @rebron

**Comment by btlechowski** [comment]
In 1.21.65, the string changed again.
![image](https://user-images.githubusercontent.com/34715963/109156754-81f10c00-7771-11eb-8cd1-18b7050d4e16.png)

**Comment by rebron** [comment]
cc: @mkarolin Should be addressed with the next l10n pull.

**Comment by mkarolin** [comment]
Correct. @btlechowski, please re-test once https://github.com/brave/brave-browser/issues/14369 has been closed.

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/14369#issuecomment-788195579, moving issue into https://github.com/brave/brave-browser/milestone/167 now that https://github.com/brave/brave-core/pull/8093 was merged into `1.22.x` and `1.21.x` via https://github.com/brave/brave-core/pull/8096 & https://github.com/brave/brave-core/pull/8097.

@brave/legacy_qa if it's still an issue, please re-open and remove it from the milestone as there was no code associated with the issues so we can just re-open then and decide if it's release blocking or not.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.21.71 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Ubuntu 18.04 LTS


Polish locale
![image](https://user-images.githubusercontent.com/34715963/109638427-4c239d00-7b4e-11eb-94a2-9446427c3285.png)
