### ISSUE TITLE
HTTP subresources on ipfs are blocked even when Shields are disabled

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14147]
Follow up to https://github.com/brave/brave-browser/issues/13742. The resources are blocked, even when Shields are disabled

## Steps to Reproduce

1. Clean profile
1. Open `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
1. Enable IPFS to use local node
1. Open `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html` in a new tab
1. Disable Shields
1. Open console
1. Paste:
```
var script = document.createElement('script')
script.src = 'https://brianbondy.com/static/js/analytics.js'
document.body.appendChild(script)
```

## Actual result:

HTTP subresources on ipfs are blocked when Shields are disabled
![image](https://user-images.githubusercontent.com/34715963/107863540-86562480-6e55-11eb-9c91-4ca638809ed4.png)

After waiting 60seconds, next to disabled Shields icon, `1` is shown
![image](https://user-images.githubusercontent.com/34715963/107946481-5e6bdb80-6f91-11eb-81d2-52a820771a1e.png)

## Expected result:
HTTP subresources on ipfs are not blocked when Shields are disabled

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.21.52 Chromium: 88.0.4324.152 (Official Build) dev (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Brave | 1.22.23 Chromium: 89.0.4389.48 (Official Build) nightly (64-bit)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | Linux

cc @brave/legacy_qa @rebron @bbondy

**Comment by bbondy** [comment]
Just tried this and did not reproduce, it loads the resource when shields are disabled for me.

**Comment by btlechowski** [comment]
Just reproduced it on Windows on latest nightly

Brave | 1.22.22 Chromium: 89.0.4389.40 (Oficjalna wersja) nightly (64-bitowa)
-- | --
Wersja | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24544)

I disabled Shields and the element was still blocked, it even shows that it blocked 1 element:
![image](https://user-images.githubusercontent.com/34715963/107946481-5e6bdb80-6f91-11eb-81d2-52a820771a1e.png)
![image](https://user-images.githubusercontent.com/34715963/107946144-e69db100-6f90-11eb-9b7e-fafb92700548.png)

@bbondy What system and what Brave version have you tried?

**Comment by LaurenWags** [comment]
Reproduces on `macOS x64 10.15.7`:

```
Brave | 1.22.24 Chromium: 89.0.4389.48 (Official Build) nightly (x86_64)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | macOS Version 10.15.7 (Build 19H512)
```

Used STR from the description on a clean profile:
<img width="1034" alt="Screen Shot 2021-02-15 at 8 21 47 AM" src="https://user-images.githubusercontent.com/28145373/107951914-0ddf8880-6f67-11eb-9813-95cc1186abb7.png">
<img width="1037" alt="Screen Shot 2021-02-15 at 8 21 12 AM" src="https://user-images.githubusercontent.com/28145373/107951918-0f10b580-6f67-11eb-8eac-9478e22f9002.png">

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in Windows 10 x64 - `Version 1.22.22 Chromium: 89.0.4389.40`

**Comment by bbondy** [comment]
I can reproduce, thanks.

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build 

Brave | 1.23.19 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

## Verification steps


1. Clean profile
1. Open `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
1. Enable IPFS to use local node
1. Open `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html` in a new tab
1. Disable Shields
1. Open console
1. Paste:
```
var script = document.createElement('script')
script.src = 'https://brianbondy.com/static/js/analytics.js'
document.body.appendChild(script)
```

Verified that there are no blocked IPFS elements when Shields are down:

<img width="1312" alt="Screen Shot 2021-03-04 at 3 36 21 PM" src="https://user-images.githubusercontent.com/387249/110045466-8c764d00-7cff-11eb-9a03-415921764b96.png">
