### ISSUE TITLE
Auto-Contribute Issues - entire uphold account balance (not just BAT earnt browsing) sent to Brave

### ISSUE THREAD

**Issue by qldps** [brave/brave-browser#14151]
## Description 
Please refund this amount (8.75 BAT). I had the auto-contribute function turned off
I am asking for a Refund as the transaction was unauthorized. Transaction is attached as a .jpg file. Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (64-bit)

Sincerely,

Tristan Currie
qldps@hotmail.com

## Steps to Reproduce
   1. Open brave browser
   2. Click the brave rewards icon (Triangle)
   3. Under Settings scroll to auto-contribute to confirm it is turned OFF. It was.
   4. Cry, your BAT balance is gone 

## Actual result:
   1. Login in to uphold.com
   2. Click on portfolio
   3. Click on BAT (Basic attention Token)
   4. Cry, your entire BAT balance (not just what you earnt browsing but extra funds you converted into BAT) is gone 

## Expected result:
Refund see attached image for details:

![BAT](https://user-images.githubusercontent.com/20813826/107884001-5da15e00-6f2d-11eb-8d7f-579c02c5eb22.jpeg)

## Reproduces how often: 
Has happened twice - on the monthly rewards date for January 2021 and February 2021

## Desktop Brave version:
Version 1.19.92

## Windows 10 Device details:
   - System type: 64-bit operating system, x64-based processor
   - OS: Build 19042.804
   - Edition: Windows 10 Pro version 20H2 Installed on 29/‎05/‎2020 (Current info - after incident occurred)

## Version/Channel Information:
Both PC and android mobile app affected

**Comment by 8064r7** [comment]
Just saw this occur as well.  Logged into my Brave on a device running the linux version which is only sporadically used. An update appears to have turned back on Auto-contribute which I always turn off on initial setup of this browser (I also sync all my settings to maintain this off across all devices). Why even if the default for this is set to on does it even have the capability to perform a transaction from this wallet back to Brave or to anywhere if there are no contributors identified in the settings to contribute to?

How are you going to sell that your web3 wallet is trustworthy if a third party entity is allowed to on my behalf make decisions & perform txns I did not authorize? 

I guess it is time to ensure that all my BAT immediately is taken out of wallet and off chain (too bad that Gwei at this time makes this basically an insolvent transaction.

![BAT sent back to Brave - Unauthorized TXN](https://user-images.githubusercontent.com/10158791/107888949-72520780-6ed5-11eb-9fc0-36f89c521696.png)

**Comment by Chtiadrien** [comment]
Same thing happened to me a few minutes ago. Half my wallet disappear because auto-contribe decide to turn on...

![image](https://user-images.githubusercontent.com/15209405/107955762-74cc6400-6f9e-11eb-8e24-4ba152128e1c.png)

I'll empty my wallet as soon as possible now to prevent that.

**Comment by Miyayes** [comment]
Hi everyone @Chtiadrien @8064r7 @qldps, I want to first check some of the common user errors with Auto-Contribute, in case they apply in your cases:

Please note that Auto-Contribute is enabled by default when you start using Brave Rewards. You will have to manually disable Auto-Contribute in order for it to be off. **This applies to all additional devices and user profiles, including those in the same Brave installation. For example, when you start using Brave Rewards on a 2nd device or in another user profile, your Brave Rewards settings (such as whether Auto-Contribute is on/off) are not synced automatically. Therefore, Auto-Contribute will be enabled by default on your 2nd device or user profile unless you manually turn it off.**

If you multiple verified devices, Auto-Contribute will draw from the shared BAT balance in your Uphold account. Therefore, only checking your one of your devices or user profiles to see whether Auto-Contribute is enabled would not be sufficient.

### Example of multiple user profiles:

<img src="https://user-images.githubusercontent.com/11497541/115649286-0afd6d00-a2f5-11eb-9acd-f9f726ffb1c4.png" width=300>

**Comment by Chtiadrien** [comment]
Hello,

I have Brave installed on my desktop computer and my phone. I have a single profile on both of them. Auto-contribute was off until February 2021 when it turned on without me changing it. Auto-contribute was off since March 2020.
