### ISSUE TITLE
Monthly Statement has next month's date as default

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14159]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/13590

When I open the monthly contribution statement, it shows next month's date (March 2021) as the default. Should show this month, Feb 2021.

## Steps to Reproduce

   1. Have a profile with several months worth of rewards data
   2. Open monthly statement

## Actual result:

date defaults to next month:

Example | Example
----- | -----
<img width="950" alt="Screen Shot 2021-02-15 at 9 25 09 AM" src="https://user-images.githubusercontent.com/28145373/107958312-d3c6b480-6f6f-11eb-9ad8-cd6d3985773c.png"> | <img width="948" alt="Screen Shot 2021-02-15 at 9 25 23 AM" src="https://user-images.githubusercontent.com/28145373/107958315-d4f7e180-6f6f-11eb-9452-274724724b60.png">

## Expected result:
should default to current month

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.21.52 Chromium: 88.0.4324.152 (Official Build) dev (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 10.15.7 (Build 19H512)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing @Miyayes @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
The issue isn't reproducible in `Windows 10 x64 - 1.21.62`
![image](https://user-images.githubusercontent.com/38657976/108734470-83de8380-7555-11eb-814d-75a803e3ec13.png)

**Comment by LaurenWags** [comment]
No longer reproduces for me

```
Brave | 1.23.59 Chromium: 89.0.4389.114 (Official Build) dev (x86_64)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | macOS Version 10.15.7 (Build 19H524)
```

<img width="950" alt="Screen Shot 2021-04-05 at 8 54 35 AM" src="https://user-images.githubusercontent.com/28145373/113619827-77a31700-9627-11eb-9dc4-772866b52686.png">
