### ISSUE TITLE
crash in setting (Profile name and icon) when cllick more in images

### ISSUE THREAD

**Issue by Sajadkiani** [brave/brave-browser#14157]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
@Sajadkiani Did you see same crash https://github.com/brave/brave-browser/issues/13762?
