### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by CrunchButtsteak** [brave/brave-browser#14153]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.20.103  Chromium: 88.0.4324.152
Operating System: Windows NT 10.0.19041

URL (if applicable) where crash occurred:

Can you reproduce this crash? 
No

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.Not entirely sure. The browser will be running fine and then randomly crash.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/18200000-f138-da05-0000-000000000000

**Comment by iefremov** [comment]
@CrunchButtsteak did it happen during shutdown? Or just normal browsing? Unfortunately the callstack is not very informative.

**Comment by iefremov** [comment]
not actionable :(
