### ISSUE TITLE
Default download location is different on CR 89

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14169]
## Description 
Default download location is different on CR 89

## Steps to reproduce 

   1. Install 1.22.27 x64 nightly build
   2. Open Downloads in settings
   3. Download location is different for CR89

## Actual result 

1.20.103 | 1.22.27
-- | --
![image](https://user-images.githubusercontent.com/17010094/108038210-7ba4b680-7032-11eb-890d-399b99e6460e.png) | ![image](https://user-images.githubusercontent.com/17010094/108038245-84958800-7032-11eb-8d95-5885bb4b9763.png)

## Expected result
Not sure 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
    - Android version: 10
   
## Brave version
122.27 x64 nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik @mkarolin @anthonypkeane

**Comment by samartnik** [comment]
We didn't change here anything, @srirambv is it the same behavior in Chrome?

**Comment by samartnik** [comment]
It is the same in Chrome, so not sure of any change is required here
![device-2021-02-16-153253](https://user-images.githubusercontent.com/30602739/108118393-4cab3680-706c-11eb-96a7-3dd0c8199077.png)

**Comment by srirambv** [comment]
Sounds good. Will close the issue as invalid as its the same on upstream as well
