### ISSUE TITLE
Remove Check password section from settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14165]
## Description 
Remove Check password section from settings

## Steps to reproduce 

   1. Install 1.22.24 x64 build
   2. Open Settings -> Passwords
   3. New entry for `Check Passwords` is available

## Actual result 

https://user-images.githubusercontent.com/17010094/108035349-bdcbf900-702e-11eb-8174-e2ed1588887c.mp4

## Expected result
Not sure if its supposed to be listed 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.22.24 x64 Nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik @mkarolin

**Comment by samartnik** [comment]
Yes, we need to remove this

**Comment by srirambv** [comment]
Verification passed on the following devices with Android 10 running 1.21.68 x64 build

OnePlus 6T | Samsung Tab A
-- | --
<img width=300 src=(https://user-images.githubusercontent.com/17010094/109178789-23cc2500-7781-11eb-9a27-131d86834707.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/109179293-a6ed7b00-7781-11eb-9224-0d51f73737d2.png>
