### ISSUE TITLE
First run dialog is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14163]
Follow up to https://github.com/brave/brave-browser/issues/12679

## Steps to Reproduce

   1. Clean install
   2. Run Brave in Polish locale

## Actual result:

Some strings are not translated
![image](https://user-images.githubusercontent.com/34715963/107965556-f88c4d80-6faa-11eb-95f9-9c84ece1d84e.png)

## Expected result:
All strings are translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.21.52 Chromium: 88.0.4324.152 (Official Build) dev (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Brave | 1.22.23 Chromium: 89.0.4389.48 (Official Build) nightly (64-bit)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @mkarolin

**Comment by karenkliu** [comment]
We need to use this text from https://github.com/brave/brave-browser/issues/14183  for translations

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/14369#issuecomment-788195579, moving issue into https://github.com/brave/brave-browser/milestone/167 now that https://github.com/brave/brave-core/pull/8093 was merged into `1.22.x` and `1.21.x` via https://github.com/brave/brave-core/pull/8096 & https://github.com/brave/brave-core/pull/8097.

@brave/legacy_qa if it's still an issue, please re-open and remove it from the milestone as there was no code associated with the issues so we can just re-open then and decide if it's release blocking or not.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.21.71 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Ubuntu 18.04 LTS

Polish PL locale
![image](https://user-images.githubusercontent.com/34715963/109644194-762c8d80-7b55-11eb-8bae-0db76d770611.png)
