### ISSUE TITLE
Automatic PPA is enabled when it was disabled on first run dialog

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14160]
Follow up to https://github.com/brave/brave-browser/issues/12679.
The dialog states:
```
Help improve Brave by sending crash reports and completely anonymised, private product analytics.
```
![image](https://user-images.githubusercontent.com/34715963/107959360-9c71fb00-6fa3-11eb-8edd-4823063e69a2.png)

Yet `Automatically send completely private product analytics to Brave` is enabled in `brave://settings/privacy`.
@karenkliu is this expected?

The figma in https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/?node-id=146%3A0 states that only `Help improve Brave's features and performance` is to be disabled or enabled based on the toggle state. 

## Steps to Reproduce

   1. Clean profile
   1. Run Browser
   1. Disable `Help improve Brave by sending crash reports and completely anonymised, private product analytics.`
   1. Open `brave://settings/privacy`

Note: `Help improve Brave's features and performance` is properly disabled

## Actual result:

`Automatically send completely private product analytics to Brave` is enabled in `brave://settings/privacy`
![image](https://user-images.githubusercontent.com/34715963/107958684-aa734c00-6fa2-11eb-9e6a-a0d35aa43381.png)

## Expected result:
`Automatically send completely private product analytics to Brave` is disabled in `brave://settings/privacy`

## Reproduces how often: 

100% repro

## Brave version (brave://version info)

Brave | 1.21.47 Chromium: 88.0.4324.152 (Official Build) beta (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Brave | 1.21.52 Chromium: 88.0.4324.152 (Official Build) dev (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Ubuntu 18.04 LTS

Brave | 1.22.23 Chromium: 89.0.4389.48 (Official Build) nightly (64-bit)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @karenkliu @rebron

**Comment by btlechowski** [comment]
@simonhong This issue will fixed when https://github.com/brave/brave-browser/issues/14183 will be implemented.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-browser/releases/tag/v1.21.68 is available

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.21.68 Chromium: 89.0.4389.58 (Official Build) (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

See https://github.com/brave/brave-browser/issues/14183#issuecomment-786078883 for full steps and screenshots, which apply here.

Verified:
* P3A and crash-reporting prefs are split out, separately
* in the first-run modal dialog, `Help improve Brave by automatically sending crash reports` is unchecked by default, and has no bearing on the below:
* `Automatically send completely private product analytics to Brave` is checked by default in `brave://settings/privacy` - this is opt-out
