### ISSUE TITLE
NFC options in site settings is missing

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14168]
## Description 
NFC options in site settings is missing

## Steps to reproduce 

   1. Install 1.22.27 x64 nightly build
   2. Open site settings
   3. NFC option is missing

## Actual result 

1.20.103 | 1.22.27
-- | --
![image](https://user-images.githubusercontent.com/17010094/108037574-b2c69800-7031-11eb-9e5e-258bc3845590.png) | ![image](https://user-images.githubusercontent.com/17010094/108037764-f3beac80-7031-11eb-9984-3d7ff314e09b.png)

## Expected result
Should probably retain the setting

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.22.27 x64 nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik @anthonypkeane

**Comment by samartnik** [comment]
@mkarolin you disabled it a while ago https://github.com/brave/brave-core/commit/56a42472c5b43d644e94ec848a540eed2dafd367
do you remember the reasoning behind it?

**Comment by mkarolin** [comment]
@samartnik the security team said that WebNFC feature should be disabled. cc: @pj, @fmarier

**Comment by mkarolin** [comment]
@samartnik, besides disabling the feature, I also disabled it in blink here https://github.com/brave/brave-core/pull/7460/commits/6b1b45fd35f871dc011fc0d0bc5bf4eb53caac26.

**Comment by samartnik** [comment]
@anthonypkeane I suppose this is not an issue, since we intentionally disabled WebNFC?

**Comment by samartnik** [comment]
Closing as we disable WebNFC intentionally

**Comment by srirambv** [comment]
Marking issue as invalid based on https://github.com/brave/brave-browser/issues/14168#issuecomment-827011770. Also removing it from milestone
