### ISSUE TITLE
click on `Enable IPFS` is redirected to `Choose default apps by protocol windows settings`

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14161]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/14147
click on `Enable IPFS` is redirected to `Choose default apps by protocol windows settings`
## Steps to Reproduce

   1.  Clean profile
   2. Open `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
   3. Enable IPFS to use local node
   
## Actual result:

click on `Enable IPFS` is redirected to `Choose default apps by protocol windows settings`
![image](https://user-images.githubusercontent.com/38657976/107956453-326a4d80-6fc5-11eb-9915-0ab62262e39c.png)

![Enable IPFS redirection](https://user-images.githubusercontent.com/38657976/107962518-1074c900-6fcd-11eb-9423-3a0d6dee6d58.gif)

## Expected result:
Should not redirect to any windows settings

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.22.22 Chromium: 89.0.4389.40 (Official Build) nightly (64-bit)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | Windows 10 OS Version 2004 (Build 19041.804)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bbondy @rebron 

Please note issue isn't reproducible for @LaurenWags in macOS and @btlechowski in Windows 7

Looks like a Windows 10 x64 specific issue

**Comment by spylogsster** [comment]
In order to setup protocol handlers we rely on chromium implementation. In case of win10 it shows Windows UI Settings to allow user to choose protocol handlers from the list. After short discussion with @bbondy we decided leave it as is but add Brave to the list of apps. @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment]
@spylogsster I have selected IPFS Brave Nightly from the protocol handler settings, I didn't get this setting popup again when I `Enable IPFS`.  I didn't face this issue while testing IPFS on released version 1.20.x. I am seeing this issue only in 1.22.x.

![image](https://user-images.githubusercontent.com/38657976/108063048-aa497e00-7080-11eb-86c2-d0d230e63f32.png)

**Comment by spylogsster** [comment]
yes  @GeetaSarvadnya it appears only once if Brave is not default protocol handler here, otherwise it will not be shown.

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` using 

Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

![ipfs-redirect](https://user-images.githubusercontent.com/387249/108767753-acda2680-750b-11eb-98d2-e74453401fe8.gif)
