### ISSUE TITLE
Privacy settings order is different in CR89

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14167]
## Description 
Privacy settings order is different in CR89

## Steps to reproduce 

   1. Install 1.22.27 x64 nightly build
   2. Open Privacy and security settings
   3. Order of the setting is changed

## Actual result 

1.20.103 | 1.22.27
-- | --
![image](https://user-images.githubusercontent.com/17010094/108036768-8eb68700-7030-11eb-9c02-c08b217fa870.png) | ![image](https://user-images.githubusercontent.com/17010094/108036780-937b3b00-7030-11eb-9a0d-b7d2b300c736.png)

## Expected result
Not sure if the order should be changed or kept it as is 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.22.27 x64 nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @anthonypkeane @SergeyZhukovsky @samartnik

**Comment by samartnik** [comment]
Yes, they reordered it in upstream, I'll fix it.

**Comment by samartnik** [comment]
I didn't change order on Chromium's side, just moved all our settings to the end. Now it looks like this
![device-2021-02-16-152439](https://user-images.githubusercontent.com/30602739/108118027-c2fb6900-706b-11eb-96c4-0eae945408fd.png)
![device-2021-02-16-152456](https://user-images.githubusercontent.com/30602739/108118044-c5f65980-706b-11eb-9781-001933456f95.png)
![device-2021-02-16-152504](https://user-images.githubusercontent.com/30602739/108118057-cb53a400-706b-11eb-92af-06099cab6763.png)

**Comment by srirambv** [comment]
@samartnik @bsclifton  should we get #6831done with this reorder? 

cc: @anthonypkeane

**Comment by samartnik** [comment]
I believe #6831 is a separate issue as it's not related to changes in upstream. This one just adjusts our code to their changes.

**Comment by srirambv** [comment]
Verification passed on the following devices with Android 10 running 1.21.68 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/14167#issuecomment-780099126

OnePlus 6T | Samsung Tab A 
-- | --
<img width=175 src=https://user-images.githubusercontent.com/17010094/109179947-51659e00-7782-11eb-885d-e5fd2fa06953.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/109179979-575b7f00-7782-11eb-88ba-d8327f158b84.png>
