### ISSUE TITLE
Update stats periodically after a node is started

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14178]
Continuing off of the work in:
https://github.com/brave/brave-core/pull/7948

After a node is started, the stats won't refresh until you reload the page. 
If the current page is open and it is active, we should refresh the stats periodically, maybe every 1s.
I think this would be done in componentDidMount with a `setInterval` and `clearInterval` when the page is closing.

**Comment by stephendonner** [comment]
Verified `FIXED` in `1.22.34` on `macOS Big Sure (11.2.1)` with 


Brave | 1.22.34 Chromium: 89.0.4389.48 (Official Build) nightly (x86_64)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | macOS Version 11.2.1 (Build 20D74)

Steps:
1. open `brave://ipfs`, click `Install and start`
<img width="960" alt="Screen Shot 2021-02-18 at 2 13 18 PM" src="https://user-images.githubusercontent.com/387249/108429023-4fd12e80-71f4-11eb-8919-7225dc04d04e.png">

2. verified stats about connected peers should be updated in runtime without reloading the page
3. clicked `stop` button, confirmed stats dropped to zero (as well as `Addresses` and `Node info`) and weren't updated until node relaunch, by clicking `start`
4. clicked `restart` button, confirmed stats dropped to zero (and `Addresses` and `Node info` were nulled out, then re-populated upon node restart

![refresh-ipfs-stats](https://user-images.githubusercontent.com/387249/108428726-dd604e80-71f3-11eb-9342-62b24701dc9b.gif)
