### ISSUE TITLE
`Customize sync` settings are not respected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14175]
## Description 

`Customize sync` settings are not respected
## Steps to Reproduce

   1. Clean install
   2. Create a standalone sync using code words
   3. Click `Manage your synced devices` and esnured standalone sync chain is created with one device
   4. Ensured `Customize sync` is selected by default under `Sync Settings`
   5. Select `Sync everything` from `Sync Settings`
   6. Reload the page brave://settings/braveSync/setup
   7. Select `Customize sync` and observe all the sync data settings are selected
  
## Actual result:

`Customize sync` settings are not respected
![image](https://user-images.githubusercontent.com/38657976/108061766-ca783d80-707e-11eb-8853-7af450fc07dc.png)

## Expected result:
After selecting `Customize sync` settings, the settings should be reverted back to default customize settings
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.22.25 Chromium: 89.0.4389.48 (Official Build) nightly (64-bit)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | Windows 10 OS Version 2004 (Build 19041.804)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @AlexeyBarabash

**Comment by rebron** [comment]
@GeetaSarvadnya I think this might be wontfix, seems like proper behavior. 

Per your steps to reproduce, if a user is going back to `customize sync` it doesn't necessarily mean we should go back to the default settings of `customize sync`. As a user, if I selected `sync everything` and went back to `customize sync`, at the `customize sync` screen is where I'd want to now be able to unselect the items I don't want. 

@karenkliu Can you take a look? My comment make sense or disagree?

**Comment by rebron** [comment]
cc: @jsecretan

**Comment by jsecretan** [comment]
Yeah I agree @rebron, if @karenkliu is OK I'm good to close this out.

**Comment by karenkliu** [comment]
@rebron @jsecretan Yes, agree.
