### ISSUE TITLE
Typo: "Setup Crypo Wallets" button should read "Set up Crypto Wallets"

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14179]
## Description 
"Setup Crypto Wallets" infobar button should read "Set up Crypto Wallets"

## Steps to Reproduce

   1.  New profile
   2. Load `https://homora.alphafinance.io`
   3. In the infobar popup, look at the spelling of the button "Setup Crypto Wallets" (setup = noun or past participle; set up is a phrasal verb)

## Actual result:

<img width="876" alt="Screen Shot 2021-02-16 at 9 32 23 AM" src="https://user-images.githubusercontent.com/387249/108099826-f1605080-7039-11eb-9757-a9a6be599860.png">

## Expected result:

Should read "Set up Crypto Wallets"
## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.22.22 Chromium: 89.0.4389.40 (Official Build) nightly (x86_64)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS | macOS Version 11.2.1 (Build 20D74)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by bbondy** [comment]
The plan is to reimplement this as a native wallet that doesn't require an extension install, so this infobar will go away. So therefore I'm deprioritizing this.

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build 

Brave | 1.23.41 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

<img width="1312" alt="Screen Shot 2021-03-16 at 9 38 11 AM" src="https://user-images.githubusercontent.com/387249/111346384-6627aa00-863b-11eb-9e9f-49748f999829.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.23.58 Chromium: 89.0.4389.114 (Official Build) beta (64-bit)
-- | --
Revision | `1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}`
OS | Windows 10 OS Version 2009 (Build 19042.867)

![image](https://user-images.githubusercontent.com/17010094/113700962-6877a400-96cf-11eb-88ce-0baba14ef4b2.png)

---------
Verification passed on 

Brave | 1.23.58 Chromium: 89.0.4389.114 (Official Build) beta (64-bit)
-- | --
Revision | `1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}`
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/113701228-c86e4a80-96cf-11eb-8413-4d4e80af4661.png)
