### ISSUE TITLE
Onion pages are opened in Normal Windows 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14188]
After clicking `Open in Tor`, the onion page is opened in Normal Window

## Steps to Reproduce

Steps:
1. Clean install
2. Open Tor window and wait for initialization
3. In normal Window open brave.com
4. Click Open in Tor

![tor_onion_page](https://user-images.githubusercontent.com/34715963/108114364-fef8f300-7098-11eb-9e36-fd81f49f0c23.gif)

## Actual result:

The onion page is opened in normal window
![image](https://user-images.githubusercontent.com/34715963/108114411-0ae4b500-7099-11eb-90dc-e0972a599796.png)

## Expected result:
The onion page is opened in tor window

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.22.26 Chromium: 89.0.4389.48 (Official Build) nightly (64-bit)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @jumde @diracdeltas

**Comment by rebron** [comment]
cc: @darkdh

**Comment by LaurenWags** [comment]
Could not reproduce on the following versions on `macOS x64 10.15.7`

**`Release`**
```
Brave | 1.20.108 Chromium: 88.0.4324.182 (Official Build) (x86_64)
-- | --
Revision | 73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS | macOS Version 10.15.7 (Build 19H512)
```

**`Beta`**
```
Brave | 1.21.65 Chromium: 88.0.4324.182 (Official Build) beta (x86_64)
-- | --
Revision | 73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS | macOS Version 10.15.7 (Build 19H512)
```

**`Nightly`**
```
Brave | 1.22.42 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 10.15.7 (Build 19H512)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.23.25 Chromium: 89.0.4389.86 (Official Build) nightly (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Ubuntu 18.04 LTS


Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/110567402-c2795e00-8151-11eb-8595-305e0e4edaa9.png)
![image](https://user-images.githubusercontent.com/34715963/110567421-c7d6a880-8151-11eb-99fe-7ba88770ad8c.png)
