### ISSUE TITLE
Split out P3A checkbox from first run dialog on macOS and Linux

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#14183]
## Description 

Currently, the first run dialog contains a checkbox that combines P3A and crash reporting consent:
![image](https://user-images.githubusercontent.com/2388823/108102815-ec9d9b80-703d-11eb-939d-aa5a5252c439.png)

After discussing with the security/privacy/data team about privacy concerns around crash reporting and the longterm vision of obtaining P3A consent, we have decided to separate it out from the crash reports checkbox. 

## Designs
Separate out P3A from the crash reports checkbox and make sure crash reports is unchecked. Uplift this change for the 1.21x/Mar 2nd release:
![image](https://user-images.githubusercontent.com/2388823/108103865-5f5b4680-703f-11eb-815e-447d0f134f15.png)

## Assets
Figma: https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/Desktop-Onboarding?node-id=1340%3A999

**Comment by rebron** [comment]
@simonhong Text update when you get a chance. We'll want to get this uplifted to into 1.21.x

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` label, https://github.com/brave/brave-browser/releases/tag/v1.21.68 is available

**Comment by stephendonner** [comment]
Verification **PASSED** on `macOS 11.1 x64` using the following build:


Brave | 1.21.68 Chromium: 89.0.4389.58 (Official Build) (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)



### **`Test Case #1`** (leaving crash report unchecked)

* launched `1.21.68 Chromium: 89.0.4389.58` and ensured that `Help improve Brave by automatically sending crash reports` was not being selected by default 
* ensured that `Automatically send completely private product analytics to Brave` was enabled via `brave://settings/privacy`
* ensured that `Help improve Brave's features and performance` was disabled
* crashed Brave via `brave://crash` and ensured that the crash report appeared under `brave://crashes` but wasn't submitted
* ensured that restarting Brave didn't submit the crash report via `brave://crashes`
* ensured that clicking on `Send now` under `brave://crashes` sends the crash report to BackTrace
* ensured that P3A is working/being updated via `brave://local-state`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
<img width="592" alt="Screen Shot 2021-02-25 at 9 09 54 AM" src="https://user-images.githubusercontent.com/387249/109192237-d386a000-774b-11eb-91a1-c695b60ffd1e.png"> | <img width="1312" alt="Screen Shot 2021-02-25 at 9 12 24 AM" src="https://user-images.githubusercontent.com/387249/109192275-dd100800-774b-11eb-8aa3-e73ac13e0820.png"> | <img width="1198" alt="Screen Shot 2021-02-25 at 9 13 10 AM" src="https://user-images.githubusercontent.com/387249/109192292-e4cfac80-774b-11eb-8f96-314932875216.png">


### **`Test Case #2`** (enabled crash reporting)

* launched `1.21.68 Chromium: 89.0.4389.58` and ensured that `Help improve Brave by automatically sending crash reports` was not being selected by default 
* selected  `Help improve Brave by automatically sending crash reports` and clicked on `Start Brave`
* ensured that `Automatically send completely private product analytics to Brave` was enabled via `brave://settings/privacy`
* ensured that `Help improve Brave's features and performance` was enabled via `brave://settings/privacy`
* crashed Brave via `brave://crash` and ensured that the crash report appeared under `brave://crashes` and was automatically submitted
* ensured that P3A is working/being updated via `brave://local-state`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
<img width="592" alt="Screen Shot 2021-02-25 at 9 34 01 AM" src="https://user-images.githubusercontent.com/387249/109193059-d5049800-774c-11eb-8e65-92f69b9f693e.png"> | <img width="1312" alt="Screen Shot 2021-02-25 at 9 34 41 AM" src="https://user-images.githubusercontent.com/387249/109193081-db930f80-774c-11eb-963f-cebbb2e76271.png"> | <img width="1195" alt="Screen Shot 2021-02-25 at 9 35 06 AM" src="https://user-images.githubusercontent.com/387249/109193109-e2218700-774c-11eb-86d3-328bbdd1fc55.png">


### **`Test Case #3`** (Onboarding)

* ensured that clicking on `completely private product analytics` opens the following:
  * https://brave.com/privacy-preserving-product-analytics-p3a/
* ensured that `Settings` opens `brave://settings/privacy`

<img width="1312" alt="Screen Shot 2021-02-25 at 9 37 40 AM" src="https://user-images.githubusercontent.com/387249/109193389-290f7c80-774d-11eb-8b71-da695c6a7d6f.png">
