### ISSUE TITLE
Improve key handling of Debian packages

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#14184]
We should revisit how we distribute our Debian packages to align with more modern best practices:

- https://wiki.debian.org/DebianRepository/UseThirdParty
- https://michael-prokop.at/blog/2021/02/16/how-to-properly-use-3rd-party-debian-repository-signing-keys-with-apt/

The main advantages will be that the Brave repository and signing key would be restricted to the `brave-*` packages.

**Comment by fmarier** [comment]
Apt is [planning to switch away from GPG](https://wiki.debian.org/Teams/Apt/Spec/AptSign) and apt-key is [deprecated and slated to be removed](https://blog.jak-linux.org/2021/02/18/apt-2.2/). This means that our [installation instructions](https://brave.com/linux/#debian-9-ubuntu-1404-and-mint-17) will stop working.

**Comment by dotneutron** [comment]
It's cool seeing this open here. `apt-key`'s deprecation has been bugging me since I noticed it last year.

Is this a good alternative for the meantime?
```bash
$ curl -fsSL https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo gpg --dearmor -o /usr/share/keyrings/brave-browser-release-keyring.gpg
$ echo "deb [arch=amd64 signed-by=/usr/share/keyrings/brave-browser-release-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
```

**Comment by wknapik** [comment]
@fmarier can you take a look at https://github.com/brave/brave-com/pull/259?

**Comment by wknapik** [comment]
Covered by https://github.com/brave/brave-com/pull/261 and https://github.com/brave/brave-release/pull/24 (both merged).
This should be closed when the changes are live.

**Comment by mihaiplesa** [comment]
It's up at brave.com/linux now.
