### ISSUE TITLE
Tabbing through content item with space below its source focuses empty content, and in the wrong order

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14197]
## Description 
Tabbing through content item with space below its source focuses empty content block, and in the wrong order

## Steps to Reproduce

   1.  launch {`nightly`, `dev`, `beta`, `release`}
   2.  open the new-tab page
   3.  press and hold Tab down until you get to a set of side-by-side articles, one with bottom padding after its source attribution
   4. tab again, notice the focus ring/line beneath the source
   5. try also shift+tab to "walk" the accessibility elements in reverse, and notice too the odd focus-ordering of elements

## Actual result:
<img src="https://user-images.githubusercontent.com/387249/108151178-fbf70600-708a-11eb-8ad2-d6485615d939.gif">

<img width="983" alt="Screen Shot 2021-02-16 at 7 15 50 PM" src="https://user-images.githubusercontent.com/387249/108151934-b4717980-708c-11eb-84fa-09f9e3a5074d.png">

The first `tab` to the content panel focuses the line/space below the source/attribution, then goes back up to the source itself, which is the inverse of what I'd expect, ordering-wise

## Expected result:
Looks like, comparing with other panels, it should only focus on the source/attribution (NBC News, Engadget, New York Times, etc.), then jump to the next content item

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.22.28 Chromium: 89.0.4389.48 (Official Build) nightly (x86_64)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | macOS Version 11.2.1 (Build 20D74)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by mattmcalister** [comment]
This will be resolved with the front end UX upgrade. Leaving this issue open for now as a reminder to check for it.

**Comment by LorenzoMinto** [comment]
@stephendonner can we close?

**Comment by stephendonner** [comment]
> @stephendonner can we close?

We can; I can always file a new issue against `v2` if it occurs.
