### ISSUE TITLE
Investigate cookie issues on ubisoft.com shop

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#14192]
## Description 
Blocking cookies on  `ubisoft.com/ubi.com` causes endless redirects

## Steps to Reproduce

   1. Login to `https://www.ubisoft.com/`
   2. From the home page, click on `Shop now`
   3. Opens new tab, with endless cookies

## Actual result:
Caused `Too many redirects` when opening the shop

## Expected result:
Let user use the ubisoft shop, without cookie exceptions

## Reproduces how often: 

Was able to reproduce easily

## Brave version (brave://version info)
Custom Brave Nightly build (with ubisoft cookies exceptions disabled)

- Can you reproduce this issue with the nightly channel? (Custom nightly build, with ubisoft cookies exceptions disabled)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
`Enable Ephemeral Storage` was enabled
and `ubi.com/ubisoft.com` cookie exceptions disabled in https://github.com/brave/brave-core/blob/master/chromium_src/components/content_settings/core/common/cookie_settings_base.cc#L46
![brave-nightly-noubi3](https://user-images.githubusercontent.com/1659004/108125257-1671c380-710d-11eb-818c-a34c803705d6.png)

**Comment by ryanbr** [comment]
With a new build, was managed to visit the store without issue. How ever, when logged in with user/pass on `ubisoft.com`, the attempting to buy a game on `store.ubi.com`, it didn't see the previous user/pass. 

1. Login with `ubisoft.com`
2. Then from the profile (top right), visit store
3. find a game to purchase, add to cart, and visit checkout.
4. requires another login.    <-- this didn't occur in the current Brave version (when we allowed ubisoft.com cookies on ubi.com)

**Comment by pes10k** [comment]
@ryanbr just to make sure I understand, is it correct that, with a current, ephemeral storage enabled build, you were able to log in and do whatever was needed just fine, but that the equivalent of "stay logged in" didn't work?  As long as you were able to accomplish what you needed to (even if it required an additional login) i think this is fine to close.

**Comment by ryanbr** [comment]
Correct, with Ephemeral Storage I was able to login, and then visit the store (different url) without erroring. If a additional ubi login needed for purchasing, I'll adjust the PR to remove ubi also.
