### ISSUE TITLE
Implement software updates

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#142]
- [ ]  Implement software update server
- [ ] Support multi channel releases
- [x] Implement client side software updates for macOS
- [x] Implement client side software updates for Windows
- [ ] Create documentation for server and client update process

**Comment by RyanJarv** [comment]
Sorry for the lack of updates here.

Currently focusing on implementing the client side in an effort to reduce risk of building any infrastructure we won't need.

OSX client status:
* @simonhong has the initial sparkle implementation in https://github.com/brave/brave-core/pull/91
* Working on some testing and automation in https://github.com/RyanJarv/updater currently

Windows client status:
* Working on the getting the build environment set up. Have been making progress but have run into plenty of issues here.
* Working on a packer/vagrant config so this can be handed off easily and will pull in people once I have that working

Crash reports:
What https://github.com/crystalnix/omaha provides for this is fairly simple and is meant to integrate with other services for search and indexing. I don't believe there's much of a reason to migrate from what we have currently as apart of this project and may make sense to look into using integrating with other services like Sentry directly (they recently added support for crashpad dumps).

Software update server:
Going to be working on this after we're making progress on the implementations but looked into this a bit and ran into issues with the production config that is available in https://github.com/crystalnix/omaha. Wanted to come back to that and evaluate if we want to do something different there, not too worried about this being a risk right now though.

**Comment by bbondy** [comment]
Thanks for the updates @RyanJarv , I pinged Aubrey and Matt O. about helping with the crash reporting.

**Comment by RyanJarv** [comment]
@bbondy, @simonhong has https://github.com/brave/brave-core/pull/91 ready to be merged with updates disabled.

There are some outstanding issues but sec has given the ok as long as we take care of them before we enable updates (https://github.com/brave/internal/issues/274).

**Comment by RyanJarv** [comment]
Closing this in favor of https://github.com/brave/brave-browser/issues/179 for the client implementation and https://github.com/brave/omaha-server/issues/1 for the server side.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Installed 0.55.5 via instructions on https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
* Ran `sudo apt update` once 0.55.6 was availabe
* Ran `sudo apt upgrade` prompted to upgrade brave
![image](https://user-images.githubusercontent.com/17010094/45896495-4bde1f80-bda2-11e8-802c-6c2efb7fdc6f.png)
