### ISSUE TITLE
"Grants" button should be dynamic and should only appear when the wallet has grants

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1420]
## Description 

The `Grants` button is currently static and is always visible even when there's no grants. This button should be dynamic and should only appear when the wallet has grants. The `Grants` button should only be visible in the following scenarios:

* user accepts a grant
* user imports a wallet that already has accepted grant(s)

The `Grant` button should disappear whenever the grants are already used and the list is blank.

## Steps to Reproduce

   1.  launch `0.55.10 Chromium: 70.0.3538.22`
   2. enable rewards via `chrome://rewards`
   3. you'll notice that the `Grants` button is visible even though you cannot interact with it

## Actual result:

![screen shot 2018-10-03 at 7 44 48 pm](https://user-images.githubusercontent.com/2602313/46449883-6037fa00-c75c-11e8-80e7-50a04115d698.png)

## Expected result:

The `Grants` button should be dynamic and should appear only when there's grants associated with the wallet being used.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

**Comment by LaurenWags** [comment]
@NejcZdovc is this sufficient for a test plan:
1. Enable Rewards. Verify grants button is not displayed. Claim a grant. Verify grants button does display.
2. Restore a wallet without any grants in it. Verify Grants button does not display.
3. Restore a wallet with grants in it. Verify Grants button does display.

**Comment by NejcZdovc** [comment]
@LaurenWags perfect plan
