### ISSUE TITLE
Changing orientation doesn't show bottom toolbar 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14211]
## Description 
Changing orientation doesn't show bottom toolbar 

## Steps to reproduce 

   1. Launch browser in landscape mode
   2. Visit a page in landscape mode
   3. Rotate to portrait 
   4. Bottom toolbar is missing, menu and tab count shows up on top
   5. Rotate to landscape and back to portrait, bottom toolbar shows up 

## Actual result 

https://user-images.githubusercontent.com/17010094/108166750-86bc1d00-70ec-11eb-9008-a15588c9aec0.mp4

## Expected result
Should not hide bottom toolbar when orientation is changed

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.20.103

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik

**Comment by samartnik** [comment]
Seems to be not reproducible on my devices. @srirambv did you do anything else prior to these steps?

**Comment by srirambv** [comment]
@samartnik no specific steps you can try the following which repro's 90% of the time

- Clean install any build (do not launch)
- Change device orientation to landscape
- Launch Brave in landscape orientation
- Visit a page 
- Change orientation to portrait 
- Bottom toolbar is missing 
- Change to landscape and back to portrait shows bottom toolbar

Here's a recording on PlayStore version (Do not the onboarding modals force rotation so closing them and showing. It even happens with P3A onboarding is shown)

https://user-images.githubusercontent.com/17010094/108313948-07445180-71b1-11eb-8bbb-5df4d8dec907.mp4

**Comment by Revenrof** [comment]
@samartnik regarding bottom toolbar orientation, I got "bottom toolbar" thingy in landscape mode IF, I open "tabs switcher". 

In NTP landscape mode the bottom toolbar shown in split second and then puff. Gone. 

But, IF the tab is used to open any url (including "chrome://what-do-I-call-this-?") the bottom toolbar is shown.

- tab opening "https://brave.com" :
![Screenshot_20210219-063631](https://user-images.githubusercontent.com/28621428/108435955-18f32b00-727d-11eb-9901-f5af730803a8.png)

- tab opening "chrome://version" :
![Screenshot_20210219-065046](https://user-images.githubusercontent.com/28621428/108436916-e813f580-727e-11eb-920f-466b39b7b6a1.png)

- tab opening "about:blank" :
![Screenshot_20210219-070041](https://user-images.githubusercontent.com/28621428/108437582-37a6f100-7280-11eb-963f-901110ca3205.png)

However, none of them ( the buttons) is working. Is it supposed to be like this? Do I need to open new issue?

**Comment by samartnik** [comment]
@Revenrof it is not expected behavior as bottom toolbar shouldn't be visible in landscape mode. Yes, please open new issue as this one is different.

**Comment by srirambv** [comment]
Unable to repro the issue on nightly/beta/release. Closing the issue for now as invalid. Will reopen if I can get it to reproduce
