### ISSUE TITLE
Remove patches/chrome-browser-net-net_error_tab_helper.cc.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14219]
## Description 

The purpose of this patch is to disable DNS probing whenever a page fails to load with a DNS-related error, which seems to be the main reason for NetErrorTabHelper existence. The other use of an instance of this class is from `chrome/browser/offline_pages/offline_page_utils.cc`, where it's retrieved from the WebContents to determine whether a download button should be shown from an error page:
```c++
bool OfflinePageUtils::IsShowingDownloadButtonInErrorPage(
    content::WebContents* web_contents) {
  chrome_browser_net::NetErrorTabHelper* tab_helper =
      chrome_browser_net::NetErrorTabHelper::FromWebContents(web_contents);
  return tab_helper && tab_helper->is_showing_download_button_in_error_page();
}
```
However, this relies on `NetErrorTabHelper::is_showing_download_button_in_error_page()`, which is only defined if chromium is built with `enable_offline_pages = true`, which is not the case for Brave.

Therefore, it should be possible to drop this patch by simply avoiding the instantiation of `NetErrorTabHelper` and getting it added to the relevant  `WebContents` in the first place.

## Desktop Brave version:

Brave 1.22.28 (Chromium 89.0.4389.48)

## Miscellaneous Information:

For **QA purposes**: this cleanup touched code added to fix bug https://github.com/brave/brave-browser/issues/3249, so please make sure behaviour remains the same (there's a test plan specified in that issue).

**Comment by mariospr** [comment]
For **QA purposes**: this cleanup touched code added to fix bug https://github.com/brave/brave-browser/issues/3249, so please make sure behaviour remains the same (there's a test plan specified in that issue).

**Comment by LaurenWags** [comment]
@mariospr looks like the issue you referenced, https://github.com/brave/brave-browser/issues/3249, is only a Windows issue. Is it appropriate to change this issue from Android/Desktop to Windows only?

**Comment by mariospr** [comment]
> @mariospr looks like the issue you referenced, #3249, is only a Windows issue. Is it appropriate to change this issue from Android/Desktop to Windows only?

Yes, sorry for the confusion (it was my fault for not properly setting the tags). Please do move it to Windows-only, thanks!

**Comment by LaurenWags** [comment]
thanks for confirming @mariospr - I will make the updates 👍🏻

**Comment by GeetaSarvadnya** [comment]
@mariospr when I open `dklfjdkafjdkafj.com` in Normal/Private/Guest/Tor windows, I am getting the same message for `Normal`, `Private` and `Guest` windows - Is this expected?

**Normal/Private/Guest**
![image](https://user-images.githubusercontent.com/38657976/110115519-33c8b200-7ddc-11eb-8cbc-d11eb9ae9fbf.png)

**Private with Tor**
![image](https://user-images.githubusercontent.com/38657976/110115676-6ecae580-7ddc-11eb-9e3a-a01d81164355.png)

**Comment by mariospr** [comment]
@GeetaSarvadnya It is possible that things have changed upstream since https://github.com/brave/brave-browser/issues/3249 got reported (2 years ago) and perhaps the expectation is now the same. Unfortunately, I'm not very familiar with the original motivation, so we'd probably be better off asking @jumde as the original reporter or @diracdeltas as the person who implemented the PRs there.

I'm sorry QA'ing this is a bit confusing, I've tried to make sure we don't overlook any change of behaviour after dropping this change but what the expected behaviour *now* should be is not entirely clear to me either.

**Comment by GeetaSarvadnya** [comment]
@jumde I have followed the test plan from https://github.com/brave/brave-browser/issues/3249#issue-407345589 and I am getting the results mentioned in https://github.com/brave/brave-browser/issues/14219#issuecomment-791389881 - Could you please look into this and let us know what is expected out of this issue?

**Comment by jumde** [comment]
@GeetaSarvadnya - https://github.com/brave/brave-browser/issues/3249#issue-407345589 is a OS/Windows specific issue. Can you check if you can reproduce these steps on windows?

**Comment by GeetaSarvadnya** [comment]
@jumde Yes, This is the windows specific issue. Yes I can reproduce the issue in 1.22x on windows 10 x64- I am not getting `Windows Network Diagnostic` when I follow the steps from https://github.com/brave/brave-browser/issues/3249#issue-407345589

Regular tab:
![image](https://user-images.githubusercontent.com/38657976/110578031-e062b500-8189-11eb-8144-fc7c683e7de1.png)

**Comment by jumde** [comment]
that's good!

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.22.56 Chromium: 89.0.4389.72 (Official Build) dev (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Windows 10 OS Version 2004 (Build 19041.804)

```
- Verified the STR from https://github.com/brave/brave-browser/issues/3249#issue-407345589 and ensured that `Running Windows Network Diagnostics` isn't shown in Regular, Private and Tor window tabs (Confirmed with @jumde )

Regular window tab:
![image](https://user-images.githubusercontent.com/38657976/110578487-f3c25000-818a-11eb-95d8-0f3cfa40e071.png)

Private window tab:
![image](https://user-images.githubusercontent.com/38657976/110578504-fe7ce500-818a-11eb-9bc1-3ab6c58420be.png)

Tor window tab:
![image](https://user-images.githubusercontent.com/38657976/110578524-089ee380-818b-11eb-9d20-e8014e709b22.png)
