### ISSUE TITLE
Brave nightly build `Bravearm 1.22.30.apk` is crashing

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14212]
## Description 
Brave nightly build `Bravearm 1.22.30.apk` is crashing

## Steps to reproduce 

   1. Install `Bravearm.apk` - 1.22.30
   2. Launch brave
   3. Brave is crashing

## Actual result 
Brave crash

## Expected result

should not be any crash
## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.22.30

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? na
- Does the issue resolve itself when disabling Brave Rewards?na
- Is the issue reproducible on the latest version of Chrome? na

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @samartnik @deeppandya @anthonypkeane

**Comment by srirambv** [comment]
Reproduced on OnePlus 6T with Android 10 as well. Crash on launch

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.22.51 x64 beta build 
- Verified no crash on launch
-------
Verification passed on Samsung Tab A with Android 10 running 1.22.51 x64 beta build 
- Verified no crash on launch
