### ISSUE TITLE
Crash in settings_overridden_params::GetSearchOverriddenParams

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#14218]
```
[ 00 ] settings_overridden_params::GetSearchOverriddenParams(Profile*)
[ 01 ] extensions::MaybeShowExtensionControlledSearchNotification(content::WebContents*, AutocompleteMatchType::Type)
[ 02 ] OmniboxEditModel::OpenMatch(AutocompleteMatch, WindowOpenDisposition, GURL const&, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&, unsigned long, base::TimeTicks)
[ 03 ] OmniboxView::OpenMatch(AutocompleteMatch const&, WindowOpenDisposition, GURL const&, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&, unsigned long, base::TimeTicks)
[ 04 ] OmniboxEditModel::AcceptInput(WindowOpenDisposition, base::TimeTicks)
[ 05 ] OmniboxViewViews::HandleKeyEvent(views::Textfield*, ui::KeyEvent const&)
[ 06 ] views::Textfield::OnKeyPressed(ui::KeyEvent const&)
[ 07 ] non-virtual thunk to views::View::OnKeyEvent(ui::KeyEvent*)
[ 08 ] ui::EventDispatcher::ProcessEvent(ui::EventTarget*, ui::Event*)
[ 09 ] ui::EventDispatcherDelegate::DispatchEvent(ui::EventTarget*, ui::Event*)
[ 10 ] ui::EventProcessor::OnEventFromSource(ui::Event*)
[ 11 ] ui::EventSource::SendEventToSinkFromRewriter(ui::Event const*, ui::EventRewriter const*)
[ 12 ] views::Widget::OnKeyEvent(ui::KeyEvent*)
[ 13 ] non-virtual thunk to views::NativeWidgetMac::DispatchKeyEventPostIME(ui::KeyEvent*)
```

https://brave.sp.backtrace.io/p/brave/triage?filters=((callstack.functions%2Ccontains%2CGetSearchOverriddenParams)%2Cptype%3Dbrowser)&aggregations=((channel%2Cdistribution%2C3)%2C(ptype%2Chead)%2C(uname.sysname%2Cdistribution%2C3))

**Comment by iefremov** [comment]
maybe related to https://github.com/brave/brave-browser/issues/15140

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8626 with build

Brave | 1.26.24 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

I confirmed both the functionality is correct, as well as -- more importantly for this issue -- that I didn't have any crashes 👍 

Steps:
1. new profile, launched Brave
2. installed Ecosia extension from `https://chrome.google.com/webstore/detail/ecosia-the-search-engine/eedlgdlajadkbbjoobobefphmfkcchfk/related`
3. confirmed Normal window's default search provider was Ecosia
4. opened a New Private Window and confirmed Ecosia is the default search provider
5. toggled DuckDuckGo button to `On` and confirmed search provider is still Ecosia
6. toggled DuckDuckGo button to `Off` and confirmed search provider is still Ecosia
7. went to `brave://extensions`, clicked on `Details` for Ecosia extension, and toggled `Allow in private` repeatedly
8. confirmed changing `Allow in private` option doesn't affect private window's search provider - still used Ecosia
9. disabled Ecosia extension via its `Details` page from `brave://extensions` and confirmed normal and private windows both use default search provider - Google, in my case
10. toggled DuckDuckGo button to `On` in New Private Window tab and confirmed search provider is changed to DuckDuckGo

example | example | example | example | example | example | example | example
---------|---------|-----------|---------|---------|----------|---------|----------
<img width="1130" alt="Screen Shot 2021-05-18 at 1 19 30 PM" src="https://user-images.githubusercontent.com/387249/118719376-4482a480-b7dd-11eb-9f2b-eff7568b40d7.png"> | <img width="1130" alt="Screen Shot 2021-05-18 at 1 19 45 PM" src="https://user-images.githubusercontent.com/387249/118719383-464c6800-b7dd-11eb-93b7-4bf7e6b48ad3.png"> | <img width="1130" alt="Screen Shot 2021-05-18 at 1 20 05 PM" src="https://user-images.githubusercontent.com/387249/118719388-48162b80-b7dd-11eb-8cdf-4d46035825ed.png"> | <img width="1130" alt="Screen Shot 2021-05-18 at 1 20 52 PM" src="https://user-images.githubusercontent.com/387249/118719390-49475880-b7dd-11eb-9268-f2b7037f18a6.png"> | <img width="1130" alt="Screen Shot 2021-05-18 at 1 21 14 PM" src="https://user-images.githubusercontent.com/387249/118719393-49dfef00-b7dd-11eb-9da0-656d69766c73.png"> | <img width="1130" alt="Screen Shot 2021-05-18 at 1 21 32 PM" src="https://user-images.githubusercontent.com/387249/118719395-4a788580-b7dd-11eb-902a-d41298c14c6a.png"> | <img width="1130" alt="Screen Shot 2021-05-18 at 1 21 48 PM" src="https://user-images.githubusercontent.com/387249/118719396-4b111c00-b7dd-11eb-8da6-618b2e6da05f.png"> | <img width="1130" alt="Screen Shot 2021-05-18 at 1 21 58 PM" src="https://user-images.githubusercontent.com/387249/118719399-4ba9b280-b7dd-11eb-879e-add7a46ed902.png">

**Comment by LaurenWags** [comment]
Testing https://github.com/brave/brave-core/pull/8626 will cover the following issues:
- https://github.com/brave/brave-browser/issues/15224 
- https://github.com/brave/brave-browser/issues/10601
- https://github.com/brave/brave-browser/issues/14218 (this issue)
