### ISSUE TITLE
Ability to disable preview window

### ISSUE THREAD

**Issue by vpetersson** [brave/brave-browser#1421]
## Description 

I recently using Brave as my primary browser. It works well in general (so good job). There is however one thing that drives me nuts, and that is the tab preview feature. I can imagine it being helpful for some, but for me it is just a massive problem as I often accidentally leave the curser over one tab and then it pops up a preview window of another tab while I'm either reading or typing.

## Steps to Reproduce

   1. Open two or more tabs
   2. Start reading in tab 3
   3. Hover the mouse over tab 2

## Actual result:

The preview takes over the screen.

## Expected result:

An option to disable said feature. 

## Reproduces how often: 

Multiple times daily.

## Brave version (chrome://version info)

0.24.0

**Comment by bbondy** [comment]
@vpetersson pls consider upgrading to the beta:
https://brave.com/download-beta

It's not on release channel yet but this version doesn't even have that feature.

**Comment by bbondy** [comment]
Closing since this was meant for https://github.com/brave/browser-laptop which will be deprecated in a couple weeks.
