### ISSUE TITLE
"Your connection is not private" should allow a workaround

### ISSUE THREAD

**Issue by 097115** [brave/brave-browser#14216]
## Description 

When encountering a privacy error, a user should be allowed to proceed anyway. May be this option to allow proceeding should be first enabled in settings or flags but it still must exist.

Brave:
https://i.imgur.com/pdYLL8x.png

Firefox:
https://i.imgur.com/GFYbrmg.png

## Version info:

Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | OS X Version 10.11.6 (Build 15G22010)

**Comment by ryanbr** [comment]
The warning in Brave is the same warning message is in Chrome. Not sure if we need to change it.  (Testing the example `https://flibusta.is/`)

@097115

**Comment by 097115** [comment]
@ryanbr Thanks for your reply!

Unfortunately, don't have Chrome installed. But are you telling that with Chrome you really can't proceed to such sites, too? I mean, it's sort of embarrassing for a user being unable to make their educated choice.

**Comment by ryanbr** [comment]
How could the error message be improved, maybe a sample screenshot?

**Comment by 097115** [comment]
@ryanbr Didn't I provide one? :)

On the [Firefox pic](https://i.imgur.com/GFYbrmg.png) you can notice that despite having an error, you can still proceed to the website. Yes, there will be **possible** risks but they are on you and you are taking your educated decision.

Until recently, Brave (and Chrome) had the same opportunity. Now, Brave just informs the user about the error, and there's nothing one can do, users simply are forced to obey.

**Comment by ryanbr** [comment]
`When encountering a privacy error, a user should be allowed to proceed anyway. May be this option to allow proceeding should be first enabled in settings or flags but it still must exist.`

You can proceed, there is a link provided. Clicking on `Advanced` button then clicking on `Proceed to....(url)`  The only real difference between Brave and Firefox here, is Firefox will use a button and we use a text link. 

![brave-htps-process](https://user-images.githubusercontent.com/1659004/108501129-b0a45800-7315-11eb-97b4-6574aa173150.png)

**Comment by 097115** [comment]
@ryanbr 

But I don't have this `Proceed to flibusta.is (unsafe)` link! I swear :) (And yes, it's exactly what I'm looking for.)

Here's another pic, and note that the scrollbar is at the very bottom, there's nothing more there:

![](https://i.imgur.com/MVQWA2O.png)

Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64) (and it says it's up to date).

**Comment by 097115** [comment]
@ryanbr

As of version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (x86_64), it's still has **no** `Proceed to....(url)` link.

![](https://i.imgur.com/f2SNqQE.png)

@rebron 

No, it **doesn't repros for me on Chrome**, since Chrome seems to have this link:

![](https://i.imgur.com/RaKSHJJ.jpg)

So, it would be great if you guys indeed could update/check your Brave, and confirm this issue.

**Comment by alinposho** [comment]
+1 to getting this fixed: I too do not have the option to `Proceed to ... (unsafe)` link in the `Advanced` section. 

### Version Info
---
Brave Version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (64-bit)
OS: Linux Mint 20 Cinnamon 4.6.7, Linux Kernel: 5.4.0-66-generic

**Comment by 097115** [comment]
@ryanbr 

I just noticed that the same URL (same search request) returns different errors in Normal and Private (without Tor) windows. And Private indeed has the `proceed to` link, while Normal still doesn't (Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64))

Normal:
![](https://i.imgur.com/IudLHoZ.png)
Private:
![](https://i.imgur.com/m76LpRN.png)

So, may be that's the culprit then?

**Comment by rebron** [comment]
`https://flibusta.is/` Seems to have their cert error resolved. 

Need to verify if this is still an issue with this error interstitial with another example.

**Comment by rebron** [comment]
Closing. Please re-open if still not seeing the links to proceed.

Links do appear in Normal window. Tested on latest release channel. 

Brave | 1.24.85 Chromium: 90.0.4430.212 (Official Build) (arm64)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | macOS Version 11.3 (Build 20E232)

<img width="1312" alt="screen_shot_2021-05-07_at_4 07 07_pm" src="https://user-images.githubusercontent.com/5951041/118316298-804efe80-b4ab-11eb-9160-4f9137760450.png">

**Comment by knightian** [comment]
Please reopen,

When we access something hosting with self signed certificates, so for example an OpenWRT router or any consumer modem/routers web GUI accessed over HTTPS, Brave does not allow for me to proceed past the warning.

I have to switch to use literally any other browser except Brave to login and configure settings on the router etc.

Screenshot attached:

![image](https://user-images.githubusercontent.com/72685601/119220041-c8b19080-bb2b-11eb-9950-d7f8b6432cde.png)

**Comment by ryanbr** [comment]
Does it occur in Chrome also?

**Comment by knightian** [comment]
> Does it occur in Chrome also?

Don't use chrome, won't use chrome.

It occurs in Brave, and needs to be fixed in Brave.

**Comment by ryanbr** [comment]
If its a Chrome issue, it should be reported there also. Not saying you permanently need to use Chrome, gives us guidance on how to resolve this.

**Comment by Ashtonian** [comment]
Please reopen - this happens with self signed certificates. This is crucial for technical workflows, for example I cannot setup my newly installed esxi server through brave. 

The error message should also be clearer - in the case of self signed certificates, the connection is indeed encrypted aka private - but it cannot be validated or trusted. 

Additionally, site settings -> "display insecure content" has no impact. 

![image](https://user-images.githubusercontent.com/4212452/123587127-6f342580-d7ab-11eb-9953-c8586408ebfd.png)

**Comment by Ashtonian** [comment]
clicking in the window and typing `thisisunsafe` should work adds the site to the exception list

**Comment by knightian** [comment]
> clicking in the window and typing `thisisunsafe` should work adds the site to the exception list

And indeed it does. Thanks!

**Comment by HyperCrowd** [comment]
> clicking in the window and typing `thisisunsafe` should work, it adds the site to the exception list

Is there any way to make this ridiculously arcane and otherwise impossible-to-discover feature more readily available for web developers somehow?

**Comment by DeserranoJorden** [comment]
This still does not have a workaround....

**Comment by vvzvlad** [comment]
I maintain. I run a lot of docker applications on my server and some of them run on https internally without a domain. It can't get a signed certificate and doesn't need to. But because of the brave browser, I just can't accept that security is now my concern and just work like I can do in chrome, safari and so on. Terrible!!! Fix this!

**Comment by NiclasPe** [comment]
I feel the pain. Im a System-Administrator and want to use my new MacBook Pro with Brave, because its my preferred Browser. But with this Bug, it is not really usable for that.

Im looking forward to hear from the Brave Team to fix it.

**Comment by ryanbr** [comment]
A "fix" like this isn't a Brave issue, should be addressed in chromium. For security we wouldn't override this.

ref: https://bugs.chromium.org/p/chromium/issues/detail?id=1095820

**Comment by NiclasPe** [comment]
Ok thanks, i will report it there to.

> A "fix" like this isn't a Brave issue, should be addressed in chromium. For security we wouldn't override this.
> 
> ref: https://bugs.chromium.org/p/chromium/issues/detail?id=1095820

OK, thanks for the quick Answer. I will report it there to.

**Comment by knightian** [comment]
> I feel the pain. Im a System-Administrator and want to use my new MacBook Pro with Brave, because its my preferred Browser. But with this Bug, it is not really usable for that.
> 
> Im looking forward to hear from the Brave Team to fix it.

The “thisisunsafe” command allows us to override and is an acceptable workaround in my opinion. I think that the “thisisunsafe” command does need to be made known to the user better then it is today however.

**Comment by NiclasPe** [comment]
> > I feel the pain. Im a System-Administrator and want to use my new MacBook Pro with Brave, because its my preferred Browser. But with this Bug, it is not really usable for that.
> > Im looking forward to hear from the Brave Team to fix it.
> 
> The “thisisunsafe” command allows us to override and is an acceptable workaround in my opinion. I think that the “thisisunsafe” command does need to be made known to the user better then it is today however.

Did I have to write this on my keyboard or in the browser console?

**Comment by knightian** [comment]
> > > I feel the pain. Im a System-Administrator and want to use my new MacBook Pro with Brave, because its my preferred Browser. But with this Bug, it is not really usable for that.
> > > Im looking forward to hear from the Brave Team to fix it.
> > 
> > 
> > The “thisisunsafe” command allows us to override and is an acceptable workaround in my opinion. I think that the “thisisunsafe” command does need to be made known to the user better then it is today however.
> 
> Did I have to write this on my keyboard or in the browser console?

Click the page and just type "thisisunsafe" you won't see it typing the characters anywhere but it auto detects it and proceeds to the site.

**Comment by vvzvlad** [comment]
> For security we wouldn't override this.

Adding a "go anyway" button, as it was in the original version before the chromium team fixed it, does not affect security in any way: the user is still shown a message about an invalid certificate, they just stop being forced to write weird spells in the browser console. All you need to do is add a "go anyway, I understand the risks" button

**Comment by NiclasPe** [comment]
Since i try this Tipp, the button appears on my Mac. 
Thanks for help!


> The above key worked, but I had no knowledge of it until after I found the solution myself ( I had inspected the page and searched for "ignore" and then on the second occurrence I saw a relevant script there, I copied what was inside the if
> 
> ```
>   sendCommand(SecurityInterstitialCommandId.CMD_PROCEED);
> ```
> 
> pasted into the console and it allowed my local website!
> 
> But then I came across this last comments ( thank you very much ) and that also works.

**Comment by Dedger** [comment]
Hello, I have found an alternative approach to downloading the file
Actualy, I just copy the download link and send it to my telegram "Saved massage". After this action, I see the following situation:
![image](https://user-images.githubusercontent.com/37668847/221879587-5aa908b6-e02a-4179-9aac-89fb40ae7ac1.png)
