### ISSUE TITLE
Remove chrome link from "chrome://flags"

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1422]
## Description 
Dev channel link under "Chrome://flags" is redirecting to chrome download page. Dev channel link needs to removed from the chrome flags page.

## Steps to Reproduce

   1. Open Brave beta 
   2. Navigate to "Chrome://flags"
   3. Click on "dev channel" link

## Actual result:
dev channel link is redirecting to "Download Chrome for Windows" page. 

## Expected result:
dev channel link needs to be removed from the chrome://flags page

## Reproduces how often: 
Always

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? NA
- Does it reproduce on browser-laptop? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
cc @bbondy

**Comment by kjozwiak** [comment]
Nice catch @GeetaSarvadnya 👍BTW, this is only reproducible on the `0.55.x` and not `0.56.2`.

* `0.56.2 Chromium: 70.0.3538.35` - not reproducible/link seems to be removed from the top
* `0.55.11 Chromium: 70.0.3538.35` - Reproducible

**Comment by kjozwiak** [comment]
Quick example if the issue @GeetaSarvadnya mentioned above:

<img width="777" alt="screen shot 2018-12-18 at 2 29 25 pm" src="https://user-images.githubusercontent.com/2602313/50178224-eaaae700-02d1-11e9-9e75-66341b149d16.png">

Used the following build:

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

**Comment by jonathansampson** [comment]
Still an issue. Came here after noticing it myself.

**Comment by rebron** [comment]
This is still showing on release channel: 0.61.51 Chromium: 73.0.3683.75
Interested in cool new Chrome features? Try our beta channel.

and beta channel: 0.62.25 Chromium: 73.0.3683.67 
Interested in cool new Chrome features? Try our dev channel

**Comment by rebron** [comment]
We can just hide the whole line for all channels but especially for release channel.
If we do keep in beta channel link should be: https://brave.com/download-beta/
and for dev channel should be: https://brave.com/download-dev/

Although dev channel doesn't have the text at all.

**Comment by ConvexPolygon** [comment]
This is also an issue in the following:

Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 2004 (Build 19569.1000)

**Comment by ConvexPolygon** [comment]
> We can just hide the whole line for all channels but especially for release channel.
> If we do keep in beta channel link should be: https://brave.com/download-beta/
> and for dev channel should be: https://brave.com/download-dev/
> 
> Although dev channel doesn't have the text at all.

I agree. Instead of removing it, we should just point it to the brave website.

**Comment by bsclifton** [comment]
Re-opening after revert was done with https://github.com/brave/brave-core/pull/5521
cc: @simonhong

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/82853811-f824c180-9f06-11ea-8b03-2d3bf298db2d.png)

**Comment by simonhong** [comment]
@btlechowski This issue is not for linux. Originally, flags page in linux doesn't have dev channel link in beta release and beta channel link in stable release. Only mac/windows has channel link.
```
#if defined(OS_WIN) || defined(OS_MACOSX) || defined(OS_CHROMEOS)
  version_info::Channel channel = chrome::GetChannel();
  results.SetBoolean(
      flags_ui::kShowBetaChannelPromotion,
      channel == version_info::Channel::STABLE && !deprecated_features_only_);
  results.SetBoolean(
      flags_ui::kShowDevChannelPromotion,
      channel == version_info::Channel::BETA && !deprecated_features_only_);
#else
  results.SetBoolean(flags_ui::kShowBetaChannelPromotion, false);
  results.SetBoolean(flags_ui::kShowDevChannelPromotion, false);
#endif
```

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Reproduce the issue in 1.9.x, click on `beta channel` in chrome://flags is redirecting to download chrome page
- Verified the STR from the description
- Verified that `dev channel` link is not shown in chrome://flags page
![image](https://user-images.githubusercontent.com/38657976/82888703-4d90bb00-9f67-11ea-881a-01242a901700.png)

**Comment by simonhong** [comment]
@GeetaSarvadnya My PR that resolves this issues is https://github.com/brave/brave-core/pull/4601.
That PR replaced chrome branding and chrome link with brave branding and brave link instead of removing chrome link. This issue should be updated.

And, chrome link was only visible by stable and beta release.
In stable release, `Interested in cool new Brave features? Try our beta channel.` will be used.
In beta release, `Interested in cool new Brave features? Try our dev channel.`.
And other channel (dev/nightly) don't have this link.

**Comment by simonhong** [comment]
Description and issue title are updated.

**Comment by btlechowski** [comment]
Deleted `QA Pass-Win64` as based on https://github.com/brave/brave-browser/issues/1422#issuecomment-633948229 this issue needs to be tested on `Beta` and `Release` channels.

**Comment by LaurenWags** [comment]
Verification in progress

Nightly:

```
Brave | 1.11.28 Chromium: 81.0.4044.138 (Official Build) nightly (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Per https://github.com/brave/brave-browser/issues/1422#issuecomment-633948229, confirmed brave://flags on Nightly does not have the link mentioned:
<img width="1193" alt="Screen Shot 2020-05-27 at 10 18 50 AM" src="https://user-images.githubusercontent.com/28145373/83032304-a7df5980-a003-11ea-9ae1-379b16c3c77f.png">

Dev:

```
Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Per https://github.com/brave/brave-browser/issues/1422#issuecomment-633948229, confirmed brave://flags on Dev does not have the link mentioned:
<img width="1195" alt="Screen Shot 2020-05-27 at 10 22 39 AM" src="https://user-images.githubusercontent.com/28145373/83032604-0dcbe100-a004-11ea-958f-d1b2148cd284.png">

Beta:

```
Brave | 1.10.73 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Per https://github.com/brave/brave-browser/issues/1422#issuecomment-633948229, confirmed brave://flags on Beta does have the link mentioned:
<img width="1454" alt="Screen Shot 2020-05-27 at 10 24 18 AM" src="https://user-images.githubusercontent.com/28145373/83032870-626f5c00-a004-11ea-8941-1b9802da9fe4.png">

However, link is pointing to https://brave.com/download-beta/ but I'm already using Beta. We should perhaps use another link for this - either Dev (as the link text says) or Nightly. Logged follow up issue for this: https://github.com/brave/brave-browser/issues/9968

Release:

TBD once 1.10.x moves to Release Channel.
