### ISSUE TITLE
Missing translations for BAP deprecation tooltip and modal 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14220]
## Description 
#14117 fixed translations on desktop. We need the same translations for Android as well.

## Steps to reproduce 

   1. Install 1.20.104 in Japanese locale
   2. Trigger BAP deprecation modals
   3. None of them are translated

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/108204661-fd244380-711b-11eb-8987-c3237ba8f627.png) | ![image](https://user-images.githubusercontent.com/17010094/108204669-001f3400-711c-11eb-9e92-d0872e39bf39.png)
-- | --

## Expected result
Translated strings

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.20.104

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/7983

**Comment by kjozwiak** [comment]
Moving this into `1.22.x` as the BAP work is being reverted via https://github.com/brave/brave-core/pull/8088. Once we have more information next week, we'll re-revert https://github.com/brave/brave-core/pull/8088 and move everything back into `1.21.x` and release `1.21.x - Release #2`.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.21.76 x64 build
- Verified test plan from https://github.com/brave/internal/issues/756#issue-824795329 which has the updated translations

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/110766581-39dfe800-824d-11eb-9937-d675ad8e5284.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/110766744-685dc300-824d-11eb-8b4b-9024f541f8a5.png>
