### ISSUE TITLE
Remove patches/chrome-browser-search_engines-template_url_service_factory.cc.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14221]
## Description 

The purpose of this patch is to call `chrome::GetBrowserContextOwnInstanceInIncognito()` instead of `chrome::GetBrowserContextRedirectedInIncognito()` from `TemplateURLServiceFactory::GetBrowserContextToUse()` for Brave, which is something that can be achieved via a chromium_src override instead now that we're getting rid of the `BRAVE_CHROMIUM_BUILD` flag everywhere (see https://github.com/brave/brave-browser/issues/12740).

## Desktop Brave version:

Brave 1.22.28 (Chromium 89.0.4389.48)

**Comment by mariospr** [comment]
For QA purposes: this cleanup touched code added to implement feature #61, so please make sure such feature continues to work.

Associated PR for extra info (e.g. Test Plan): brave/brave-core#310

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
Revision	3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS	macOS Version 10.15.7 (Build 19H512)
```

Clean profile:

<details>
<summary>Private Window</summary>

- Confirmed DDG toggle is shown on Private NTP, defaults to OFF
- Confirmed not changing this option uses (default) Google search on Private window of clean profile
- Confirmed if I change the default (normal) SE from Google to another SE like Ecosia, and open a Private window, without changing DDG toggle, Ecosia is used for search
- Confirmed when DDG is toggled to ON in Private window, DDG is used for search

</details>

<details>
<summary>Guest Window</summary>

- Confirmed DDG toggle is shown on Guest NTP, defaults to OFF
- Confirmed not changing this option uses (default) Google search on Guest window of clean profile
- Confirmed if I change the default (normal) SE from Google to another SE like Ecosia, and open a Guest window, without changing DDG toggle, Google is used for search (this matches 1.21.x behavior and is expected per https://github.com/brave/brave-browser/issues/6470#issuecomment-542349123)
- Confirmed when DDG is toggled to ON in Guest window, DDG is used for search

</details>

Upgrade profile:

<details>
<summary>Private Window</summary>

- Set DDG toggle to ON in Private window of 1.21.73. Upgraded to 1.22.x. 
- Confirmed DDG toggle remained set to ON when opening Private window in 1.22.x.
- Confirmed searching in Private window used DDG.

</details>

<details>
<summary>Guest Window</summary>

- Set DDG toggle to ON in Guest window of 1.21.73. Upgraded to 1.22.x. 
- Confirmed DDG toggle remained set to ON when opening Guest window in 1.22.x.
- Confirmed searching in Guest window used DDG.

</details>

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.22.58 x64 Beta build
- Verified setting a new SE via onboarding also sets it for private tabs
- Verified keeping default SE via onboarding retains Google as default for private tabs
- Verified opening the first Private tab prompts for DDG message if SE is default or anything else apart from DDG
- Verified clicking on the DDG message in private tab brings up the modal
- Verified able to set DDG as default for private tabs via the modal
- Verified quit and restart browser retains the setting
-----------
Verification passed on Samsung Tab A with Android 10 running 1.22.58 x64 Beta build
- Verified setting a new SE via onboarding also sets it for private tabs
- Verified keeping default SE via onboarding retains Google as default for private tabs
- Verified opening the first Private tab prompts for DDG message if SE is default or anything else apart from DDG
- Verified clicking on the DDG message in private tab brings up the modal
- Verified able to set DDG as default for private tabs via the modal
- Verified quit and restart browser retains the setting
