### ISSUE TITLE
Forward errors from component updater to ipfs observers

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#14229]
## Description 

Continuing off of the work in: https://github.com/brave/brave-core/pull/7918#issuecomment-780742809

## Steps to Reproduce

   1. Clean profile
   2. Navigate to ipfs:// url to see interstitial page
   3. Click by local node button
   4. Disconnect internet cable

## Actual result:

it hangs with "Installing" and never gives an error state 

## Expected result:
Expected result that error will be forwarded to the page

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
no
- Can you reproduce this issue with the beta channel? 
no
- Can you reproduce this issue with the nightly channel? 
no
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `FIXED` using `beta` and the inline testplan here, with 

Brave | 1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)




1. Clean profile
2. Navigate to `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html` URL to see interstitial page
3. Click `Use a local node` button
4. After the button text changes status to `Installing...`, disconnect internet cable / disable Wi-Fi

<img width="1247" alt="Screen Shot 2021-03-03 at 10 27 11 AM" src="https://user-images.githubusercontent.com/387249/109853752-1bee0400-7c0b-11eb-84a8-74def830d2fc.png">

5. Wait until the # of attempts has counted down/been exceeded



<img width="1312" alt="Screen Shot 2021-03-03 at 10 13 33 AM" src="https://user-images.githubusercontent.com/387249/109852356-8a31c700-7c09-11eb-9550-d0cdf1ce6a29.png">

6. Reconnect ethernet cable / Wi-Fi
7. Click the `Try again` button

Also tried, and verified:

8. Repeat steps 1-4
9. While the retry countdown happens, reconnect ethernet cable / Wi-Fi
10. Confirmed that installation finishes and ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html automatically loads

![waiting-ipfs](https://user-images.githubusercontent.com/387249/109853755-1c869a80-7c0b-11eb-8aba-2ae3355b9787.gif)
