### ISSUE TITLE
Remove patches/chrome-browser-profiles-profile_io_data.cc.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14238]
## Description 

The idea of this patch is simply to make sure that the `brave://` scheme gets considered by `ProfileIOData::IsHandledProtocol()` along with other schemes, but we can achieve the same goal just using chromium_src overrides, so let's do that instead.

## Desktop Brave version:
Brave 1.22.28 (Chromium 89.0.4389.48)

## Miscellaneous Information:

For **QA purposes**: this cleanup touched code added to fix bugs https://github.com/brave/brave-browser/issues/2861 and https://github.com/brave/brave-browser/issues/2849, so please make sure behaviour remains the same.

There is a test plan in the associated PR in https://github.com/brave/brave-core/pull/1196

**Comment by mariospr** [comment]
## Miscellaneous Information:

For **QA purposes**: this cleanup touched code added to fix bugs https://github.com/brave/brave-browser/issues/2861 and https://github.com/brave/brave-browser/issues/2849, so please make sure behaviour remains the same.

There is a test plan in the associated PR in https://github.com/brave/brave-core/pull/1196

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/1196 with 

Brave | 1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

Test 1:
Navigate to `https://world_languages.gitlab.io/bravepoc/`
Click link
Check `brave://settings` is not loaded in new tab.

Confirmed that `example.com` opened in a new tab, instead

<img width="1046" alt="Screen Shot 2021-03-04 at 10 06 41 AM" src="https://user-images.githubusercontent.com/387249/110009319-b0bb3500-7cd1-11eb-8870-fbc318039ea3.png">


Test 2:

Navigate to `brave://welcome`
Move to Change your search engine page in welcome page
Click Settings button
Check settings page is opened in new tab

The above testcase was for previous UI; I instead used the 3rd page in `brave://welcome`, which has Settings linked, as shown here.

Verified that it opened `chrome://settings/privacy` in a new tab.

| Step 1 | Step 2 |
|-------|--------|
<img width="1046" alt="Screen Shot 2021-03-04 at 10 12 17 AM" src="https://user-images.githubusercontent.com/387249/110009832-68504700-7cd2-11eb-8cb0-c9df597516a2.png"> | <img width="1208" alt="Screen Shot 2021-03-04 at 10 19 04 AM" src="https://user-images.githubusercontent.com/387249/110010578-4d320700-7cd3-11eb-91e9-5de32b91e69e.png">


Test 3:

Open `brave://settings`
Right click on `brave://sync
Check Save Link As... is disabled

I confirmed via #brave-core in Slack that this is also outdated UI; @simonhong confirmed that the new test is actually to make sure that `Save Link As...` is *enabled* for a corresponding `chrome://` link.

Verified that right-clicking and choosing `Save Link As...` for `chrome://settings/braveSync` resulted in the following dialog.

| Step 1 | Step 2 |
|-------|--------|
<img width="1090" alt="Screen Shot 2021-03-04 at 10 18 19 AM" src="https://user-images.githubusercontent.com/387249/110010282-f88e8c00-7cd2-11eb-9050-13e7a86e07a9.png"> | <img width="1208" alt="Screen Shot 2021-03-04 at 10 17 16 AM" src="https://user-images.githubusercontent.com/387249/110010278-f7f5f580-7cd2-11eb-8e15-4733dcbab335.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.22.54 x64 beta build
- Verified test plan 1 from https://github.com/brave/brave-core/pull/1196
- Verified clicking on the link doesn't open settings instead loads example.com in a new tab
----------
Verification passed on Samsung Tab A with Android 10 running 1.22.54 x64 beta build
- Verified test plan 1 from https://github.com/brave/brave-core/pull/1196
- Verified clicking on the link doesn't open settings instead loads example.com in a new tab
