### ISSUE TITLE
Cert Errors interstitial page links to Google Support pages

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14237]
## Description 

Cert Errors interstitial page links to Google Support pages

## Steps to Reproduce

   1. Load any cert error pages like https://untrusted-root.badssl.com/
   2. Shows interstitial page
   3. Learn more on the info links to chrome-error://chromewebdata/# which redirects to `https://support.google.com/chrome/answer/6098869`

## Actual result:

Cert Errors interstitial page links to Google Support pages

## Expected result:
Should redirect to specific articles on `https://support.brave.com/`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.22.31 Chromium: 89.0.4389.48 (Official Build) nightly (64-bit)
-- | --
Revision | `0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Looks like this was not fixed as part of #212 or was done but then regressed down the line. @rebron @bsclifton @bbondy @mkarolin we should prioritize this one and have it fixed before channel migration. Tagging @hollons @Brave-Matt to have the support links ready for this.

**Comment by rebron** [comment]
cc: @Brave-Matt Can we get a similar article to our support site?

**Comment by mkarolin** [comment]
@Brave-Matt @hollons ping ☝️

**Comment by Brave-Matt** [comment]
@mkarolin @rebron we certainly can -- is it safe to assume that all the error codes/messages will apply to us as well? So I'm mostly able to just copy the info over?

**Comment by mkarolin** [comment]
@Brave-Matt yes, all the same error codes would apply to us.

**Comment by Brave-Matt** [comment]
Got it -- can have this up soon 👍

**Comment by Brave-Matt** [comment]
Sorry for the delay -- this doc is up and ready to be viewed. Link here:
https://support.brave.com/hc/en-us/articles/360059254971

**Comment by mkarolin** [comment]
Looks like Safe Browsing interstitial page also has a `Learn more` link that redirects to a different article (namely `https://support.google.com/chrome/answer/99020`). 
STR:
1. Load a safe browsing test page (like https://testsafebrowsing.appspot.com/s/phishing.html)
2. Shows interstitial page
3. Learn more on the info links to chrome-error://chromewebdata/# which redirects to `https://support.google.com/chrome/answer/99020`

cc: @Brave-Matt do we already have a page similar to this one?

cc: @rebron @jumde There is also a couple of links if you click on `Details` button that take you to `Google` to see the site status or report Safe Browsing error. I am not sure if anything needs to be done to those.

**Comment by mkarolin** [comment]
Ping @Brave-Matt ☝️

**Comment by rebron** [comment]
> cc: @rebron @jumde There is also a couple of links if you click on `Details` button that take you to `Google` to see the site status or report Safe Browsing error. I am not sure if anything needs to be done to those.

The links in details seems fine to me. Feature should still be branded Google Safe Browsing and links out to this service looks right.

**Comment by Brave-Matt** [comment]
I've been slacking on this doc and I apologize. I'll get something up for us to link to this week but it is on the board:
https://github.com/brave/support/issues/1047

**Comment by bsclifton** [comment]
Closing as stale. Per above comment, linking to Google is OK in this context as the interstitial is being presented via Google's Safe Browsing service
