### ISSUE TITLE
Tab titles disappear and only show on hover

### ISSUE THREAD

**Issue by startswithaj** [brave/brave-browser#14233]
## Description 
Tab titles don't appear on some tabs unless you hover over the mouse.

## Steps to Reproduce
It seems to happen all the time to me - when I first restart the browser the titles work but eventually disappear. I wish I could provide more information - I can't tell what triggers it.

## Actual result:

<img width="1039" alt="Screen Shot 2021-02-18 at 12 18 49" src="https://user-images.githubusercontent.com/3658522/108295616-b863df80-71e3-11eb-9b5f-6b46c0d16c06.png">

With mouse hovering over tab:
<img width="1045" alt="Screen Shot 2021-02-18 at 12 18 54" src="https://user-images.githubusercontent.com/3658522/108295630-bd289380-71e3-11eb-94ef-ed5f771db670.png">

## Expected result:
To have all tab titles display.

## Reproduces how often: 

Every time i use the browser.

## Brave version (brave://version info)
Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (arm64)

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
- No

**Comment by rebron** [comment]
@startswithaj Can you go here: brave://settings/system and toggle off Hardware acceleration? I'm wondering if that could be causing it. Could also be a lazy tab load issue which we'll need to investigate.

**Comment by startswithaj** [comment]
@rebron thanks for your reply. I've turned of hardware acceleration and I will monitor and report back. I don't think it is a lazy loading issue because if I switch to the tab the title shows and the content is there, if I then switch back to another tab the title disappears.

**Comment by startswithaj** [comment]
Looks like turning off hardware acceleration has fixed the issue. Many thanks. I did put the version I'm running in the report but I am running it on an M1.

**Comment by bsclifton** [comment]
Thanks for reporting back @startswithaj - I'll close this issue and dupe this to https://github.com/brave/brave-browser/issues/3471

The consequence would be that any calls which would usually be handled by video card (ex: WebGL, graphics calls, the window rendering itself) will be done in software, which may cause CPU to be a bit higher. Usually, it isn't noticeable - but there are some more intense sites and situations (having lots of tabs open, doing CPU intensive tasks on your machine outside the browser) where it becomes clearly noticeable

Many times updating the driver will help. If possible, it's always better to have HA enabled. Likely you'll also see this problem in Chrome / Chromium

**Comment by rebron** [comment]
cc: @LaurenWags and @iefremov To keep an eye out for this one too. Tab titles disappearing and looks like an Apple M1 hardware acceleration issue.
