### ISSUE TITLE
Interstitial page points to Enhanced protection which isn't available 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14235]
## Description 

Interstitial page points to Enhanced protection which isn't available 

## Steps to Reproduce

   1. Load any cert error pages like `https://untrusted-root.badssl.com/`
   2. Shows interstitial page 
   3. Info box has a hyper link for `To get Brave’s highest level of security, turn on enhanced protection` which links to `chrome-error://chromewebdata/#` which deep links into settings `brave://settings/security?q=enhanced` which is not available in Brave

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/108319515-69a15000-71b9-11eb-8bbf-09f40c4b79db.png)

## Expected result:
Remove all entries for non-existent settings

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.22.31 Chromium: 89.0.4389.48 (Official Build) nightly (64-bit)
-- | --
Revision | `0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mkarolin @jumde @rebron

**Comment by srirambv** [comment]
Logged  #14237 for Google support links which seems to be an issue on current release builds as well. Also updated the issue to only mention the missing settings

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` using 

Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

Verified that the "turn on enhanced protection" message in the interstitial page is now removed.

<img width="1312" alt="Screen Shot 2021-02-22 at 12 30 15 PM" src="https://user-images.githubusercontent.com/387249/108766470-0ccfcd80-750a-11eb-9a2d-797ffbbf35c1.png">
