### ISSUE TITLE
Integrate Processor Arch into stats ping

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#14232]
Have brave_stats send processor architecture and make use of the API exposed in https://github.com/brave/brave-core/pull/7954 if ads are enabled.

**Comment by btlechowski** [comment]
Added `QA/Test-All-Platforms` different platforms may have different ways of obtaining arch.

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

1. clean profile, launched Brave
2. enabled Ads via `Start using Rewards` button
3. let time (48 hours) elapse
4. launched Charles Proxy
5. re-launched Brave
6. examined network traffic from `https://laptop-updates.brave.com`

Verified that `&arch=X86_64` is appended to the usage ping here: `https://laptop-updates.brave.com/1/usage/brave-core?platform=osx-bc&channel=beta&version=1.22.51&daily=true&weekly=false&monthly=false&first=false&woi=2021-03-01&dtoi=2021-03-03&ref=BRV001&adsEnabled=true&arch=x86_64`

<img width="1675" alt="Screen Shot 2021-03-05 at 12 36 25 PM" src="https://user-images.githubusercontent.com/387249/109870082-865c6f80-7c1e-11eb-99f9-2ddd4906081f.png">

**Comment by kjozwiak** [comment]
@brave/legacy_qa there's additional STR/Cases that we'll need to run through via https://github.com/brave/internal/issues/755. Please add the verifications for those cases inside https://github.com/brave/internal/issues/755 similar to what we did with https://github.com/brave/internal/issues/751#issuecomment-775734983 👍
