### ISSUE TITLE
Large Files in the File system?

### ISSUE THREAD

**Issue by mendel3** [brave/brave-browser#1423]
## Description 
I was looking through my computer's drive in WinDirStat to try and free up some space. and noticed two large files located in C:\Users\[redacted]\AppData\Roaming\brave\File System\001\p\00
I cannot open them with 7-zip, so I assume that they aren't archives. I'm not sure if this belongs in brave-browser or brave-core because I have Brave, Brave Dev, and Brave Beta installed on my computer.
I am running Windows 10 version 1803, and newest versions of all of the browsers.

## Steps to Reproduce
   1. Go to %appdata%\brave\File System\001\p\00
   2. There are two large files named 00000000 and 00000001

## Actual result:
![rsmk9yw](https://user-images.githubusercontent.com/15878726/46484573-b1022e00-c802-11e8-8245-eff957ff973e.png)
A screenshot of the folder in question

## Expected result:
N/A

## Reproduces how often: 
N/A

## Brave version (chrome://version info)
Brave Beta:

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows

Brave Dev:

Brave | 0.56.1 Chromium: 70.0.3538.22 (Official Build) dev (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows

Brave:
 Brave: 0.23.205 
V8: 6.9.427.22 
rev: 81396b3a6454480382ffc476a8b8590fec73717e 
Muon: 8.1.4 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.92

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Not Sure
- Does it reproduce on browser-laptop? 
Not Sure

**Comment by srirambv** [comment]
This one looks like for muon browser. This repo is for brave-browser-beta/dev only.
