### ISSUE TITLE
l18N text shown for all labels on BAT button dropdown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1424]
## Description 

l18N text shown for all labels on BAT button dropdown

## Steps to Reproduce

   1. Upgrade to 0.55.11
   2. Enable Brave Rewards
   3. BAT dropdown has `l18N` for all labels

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46489018-50f39380-c7d2-11e8-8002-54f5ab278046.png)
![image](https://user-images.githubusercontent.com/17010094/46484876-a2972080-c7c8-11e8-8d7c-19d99f9fa76e.png)

## Expected result:
Should not show `l18N` for any lables

## Reproduces how often: 

100%

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? NA
- Does it reproduce on browser-laptop? N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@bridiver could you please check why it's not loading language file on windows. Thank you

**Comment by LaurenWags** [comment]
Could not reproduce on macOS using


Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

**Comment by NejcZdovc** [comment]
done in https://github.com/brave/brave-core/pull/459/commits/6037502b62f2be265d0d1d7b8077ef5e628ac4f0 and https://github.com/brave/brave-core/pull/459/commits/5111c94b951e9dfecda7c6b1e4f465129a646535

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64


![image](https://user-images.githubusercontent.com/34715963/47166850-5f2acf00-d2fd-11e8-8ac5-97f0bc88b147.png)

![image](https://user-images.githubusercontent.com/34715963/47166877-723d9f00-d2fd-11e8-9d3b-9ba2cb028b9b.png)

![image](https://user-images.githubusercontent.com/34715963/47166971-add86900-d2fd-11e8-9245-640e03bb8131.png)
