### ISSUE TITLE
cosmetic filtering doesn't handle vetted search engines correctly if they have subdomains

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#14248]
Currently we do not apply cosmetic filtering to privacy respecting ads on search partners in the default setting (we still hide then in the aggressive mode).  However, the check for "is this a vetted search engine" page fails incorrectly for search engine subdomain pages.

For example, currently cosmetic filtering is default off for https://startpage.com/sp/search (this is expected).  However, its default on for startpage subdomains (e.g., https://www.startpage.com/sp/search).  The same is true for all the [expected, vetted domains](https://github.com/brave/brave-core/blob/f557c0eb6b9a0f169343d06000f2aa81cb242335/components/cosmetic_filters/renderer/cosmetic_filters_js_handler.cc#L28).

**Comment by SergeyZhukovsky** [comment]
Created a follow up to cover that functionality with tests https://github.com/brave/brave-browser/issues/14259

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` until uplift is completed

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as this was uplifted via https://github.com/brave/brave-core/pull/8014 👍

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.21.65 Chromium: 88.0.4324.182 (Official Build) beta (x86_64)
Revision	73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS	macOS Version 10.15.7 (Build 19H512)
```

Verified test plan from https://github.com/brave/brave-core/pull/8011#issue-576567783 and https://github.com/brave/brave-core/pull/8011#issuecomment-783811335 with different examples.

**`Example - Under Armour`**
Standard | Aggressive
----- | -----
<img width="1200" alt="Standard-1 21 65-under armour" src="https://user-images.githubusercontent.com/28145373/108860493-3cd7a900-75bc-11eb-896d-0d5a478eff77.png"> | <img width="1198" alt="Aggressive-1 21 65-under armour" src="https://user-images.githubusercontent.com/28145373/108860497-3d703f80-75bc-11eb-989b-018df4fd5fa9.png">

**`Example - Windows`**
Standard | Aggressive
----- | -----
<img width="1197" alt="Standard-1 21 65-windows" src="https://user-images.githubusercontent.com/28145373/108860518-42cd8a00-75bc-11eb-94fd-2c5c46d37117.png"> | <img width="1198" alt="Aggressive-1 21 65-windows" src="https://user-images.githubusercontent.com/28145373/108860520-43feb700-75bc-11eb-995c-471df6380abd.png">

------------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.68 x64 build
- Verified first part ads are listed when search for specific terms
- Verified clicking on the ad loads a new tab that loads google.com result and then redirects to the first party page
-----------
Verification passed on Samsung Tab A with Android 10 running 1.21.68 x64 build
- Verified first part ads are listed when search for specific terms
- Verified clicking on the ad loads a new tab that loads google.com result and then redirects to the first party page

OnePlus 6T | Samsung Tab A
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/109276060-7521f600-780d-11eb-92f4-50c19664c35b.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/109276047-6f2c1500-780d-11eb-87b1-d9c6f94af703.png>
