### ISSUE TITLE
"Ask where to save files" toggle broken.

### ISSUE THREAD

**Issue by Revenrof** [brave/brave-browser#14246]
## Description 
"Ask where to save files" toggle can't be turn ON. it keep back to OFF state after leaving "Downloads" settings.

## Steps to reproduce 

   1. Open Settings.
   2. Open Downloads.
   3. Toggle ON "Ask where to save files".

## Actual result 
Toggle back to off state after leaving "Downloads" settings. I did attached a video (see below)

## Expected result
Toggle should be ON.

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Aye
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? N/A

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 8.10
   
## Brave version
1.20.103 (412010323)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

# #

https://user-images.githubusercontent.com/28621428/108430130-7aae9780-7273-11eb-808c-30ee884c323e.mp4

**Comment by Brave-Matt** [comment]
Community report:
https://community.brave.com/t/ask-where-to-save-files-toggle-not-working/240088/4

Worth mentioning that I can reproduce this issue as well. cc @SergeyZhukovsky

**Comment by anthonypkeane** [comment]
https://bravesoftware.slack.com/archives/C0816QH3R/p1622236899168300?thread_ts=1622220698.167700&cid=C0816QH3R

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.63 x64 build
- Verified steps from issue description

https://user-images.githubusercontent.com/17010094/122355068-7fe1d180-cf49-11eb-97ab-c25f83e552ed.mp4


-----------
Verification passed on Samsung Tab A with Android 10 running 1.26.63 x64 build
- Verified steps from issue description

https://user-images.githubusercontent.com/17010094/122355000-6e002e80-cf49-11eb-990f-e9617b5d0450.mp4
