### ISSUE TITLE
I cannot connect my Uphold account in Creators Page?

### ISSUE THREAD

**Issue by BroJenuel** [brave/brave-browser#14249]
## Steps to Reproduce

   1. Log In to Brave Reqards Page
   2. Connect to Uphold

## Actual result:

This shows up: translation missing: en.payment.connection.uphold_connections.edit.uphold_error
![image](https://user-images.githubusercontent.com/31676163/108449415-6c29a580-729e-11eb-915c-9837d511d0c4.png)

## Expected result:
I should be able to connect to my uphold..

## Brave version (brave://version info)

Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Windows 10 OS Version 2009 (Build 19042.804)
JavaScript | V8 8.8.278.15
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,SafetyTip,WinrtGeolocationImplementation,PrefetchPrivacyChanges,WebUIDarkMode,LegacyTLSEnforced --disable-features=AutofillEnableAccountWalletStorage,IdleDetection,AutofillServerCommunication,TextFragmentAnchor,NetworkTimeServiceQuerying,LangClientHintHeader,PasswordCheck,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,PrivacySettingsRedesign,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection,DirectSockets,WebOTP,NotificationTriggers,TabHoverCards --flag-switches-begin --flag-switches-end https://us04web.zoom.us/j/2454154225?pwd=Y3N3OWNMdkJvdlc2REc5LzE0N3ZnUT09
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Admin\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? **I am using the current release.**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? **Im using the latest stable version of brave.**

**Comment by hollons** [comment]
Hi @BroJenuel - sorry for the delay here. What country are you based in?

**Comment by BroJenuel** [comment]
Oh, I'm sorry not to close this one.. It was successfully connected after maybe 24hours, I think because of an update... But thanks for the reply :).

I am from Philippines.

![image](https://user-images.githubusercontent.com/31676163/109582054-68b4da80-7b38-11eb-80ea-625ac039e17f.png)

**Comment by hollons** [comment]
@BroJenuel great to hear! I'll go ahead and close.
