### ISSUE TITLE
WebTorrent: Add progress bar visualization 

### ISSUE THREAD

**Issue by axcap** [brave/brave-browser#14244]
## Steps to Reproduce
   <a id="step1"></a>1. Open any torrent-/magnet-link (e.g. [https://webtorrent.io/torrents/big-buck-bunny.torrent](https://webtorrent.io/torrents/big-buck-bunny.torrent)).
   2. Press "Start Torrent" button.
   3. Proceed to only see textual representation of the download progress.

## Actual result:
Example output using **big-buck-bunny.torrent** file provided in [Step 1](#step1).

![image](https://user-images.githubusercontent.com/1700426/108392874-689d0c80-7213-11eb-80f2-77ed89b4f7e4.png)

## Expected result:
![image](https://user-images.githubusercontent.com/1700426/108394756-5b811d00-7215-11eb-9b85-65c94eb76896.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Name | Version
-- | --
Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Linux

**cc**: @bsclifton @rebron @mkarolin feel free to comment your thoughts or provide design guidelines!

**Comment by axcap** [comment]
Hi @feross i just found out you were working on a similar [issue](https://github.com/brave/brave-browser/issues/5402). Any idea why it is not merged, is it still under development perhaps?

**Comment by feross** [comment]
@axcap Yes, that issue is the proper place to track the redesign of the WebTorrent UI. The work on that stalled, but I'm in the process of resuming it. You can follow along in that issue.
