### ISSUE TITLE
Safe Browsing download protection is flaky

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#14245]
Testing the Desktop Download Warnings on https://testsafebrowsing.appspot.com/ in Beta 1.21.55, the downloads get blocked some of the time, but not always.

**Comment by kjozwiak** [comment]
Running into the above as well on the current `1.20.x` (Release) & the current `1.22.x` (Nightly) builds:

* **`1.22.34 CR: 89.0.4389.48`** - **Reproduced**
* **`1.20.103 CR: 88.0.4324.152`** - **Reproduced**

STR:

* visit https://testsafebrowsing.appspot.com
* ensure `https://safebrowsing.brave.com` pulled the needed files under the following directory: 
   * `BraveSoftware\Brave-Browser-Nightly\User Data\Safe Browsing`
* click on a few of the links under `Desktop Download Warnings` and you'll see that sometimes the files get downloaded without warning users

### **`Examples:`**

You can see several files where downloaded without giving the user a warning:

![issue1](https://user-images.githubusercontent.com/2602313/108409972-d7b73880-71f4-11eb-8f2e-6858b39d21b9.png)

**Comment by fmarier** [comment]
Seems to be resolved now. This was due to server-side changes on Google's end.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
-- | --
Revision | 31b458a18f133db9203eb5a5dd6552de0716dda3-refs/branch-heads/4324_182@{#6}
OS | Windows 10 OS Version 2009 (Build 19042.844)
```

@fmarier went through this just as a double check, definitely working compared to before. Getting alerted every time when downloading from the `Desktop Download Warnings` section under https://testsafebrowsing.appspot.com/ 👍
