### ISSUE TITLE
Upgrade Chromium from 70.0.3538.35 to 70.0.3538.45

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1425]

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - PASSED

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X
