### ISSUE TITLE
[Android] Bottom toolbar appears in landscape mode

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#14254]
@samartnik regarding bottom toolbar orientation, I got "bottom toolbar" thingy in landscape mode IF, I open "tabs switcher". 

In NTP landscape mode the bottom toolbar shown in split second and then puff. Gone. 

But, IF the tab is used to open any url (including "chrome://what-do-I-call-this-?") the bottom toolbar is shown.

- tab opening "https://brave.com" :
![Screenshot_20210219-063631](https://user-images.githubusercontent.com/28621428/108435955-18f32b00-727d-11eb-9901-f5af730803a8.png)

- tab opening "chrome://version" :
![Screenshot_20210219-065046](https://user-images.githubusercontent.com/28621428/108436916-e813f580-727e-11eb-920f-466b39b7b6a1.png)

- tab opening "about:blank" :
![Screenshot_20210219-070041](https://user-images.githubusercontent.com/28621428/108437582-37a6f100-7280-11eb-963f-901110ca3205.png)

However, none of them ( the buttons) is working. Is it supposed to be like this? Do I need to open new issue?

_Originally posted by @Revenrof in https://github.com/brave/brave-browser/issues/14211#issuecomment-781714978_

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.22.58 x64 beta build
- Verified steps from https://github.com/brave/brave-browser/issues/14254#issue-812092603
- Verified no bottom toolbar is shown on landscape mode
