### ISSUE TITLE
.onion request in regular window should also avoid DNS leakage

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#14261]
#13527 fixed the issue of .onion leaking DNS in Tor windows, but the issue should also be fixed in regular windows because users may accidentally enter a .onion in a regular window instead of a Tor window. this happens regardless of whether the 'Automatically redirect .onion' option is selected.

STR:
1. disable DoH (makes it easier to see requests in wireshark)
2. open wireshark and filter by DNS
3. open a regular tab and navigate to facebookcorewwwi.onion
4. you see DNS requests in wireshark

expected behavior: brave should block DNS if it sees a top-level navigation to a .onion URL both when the 'Automatically redirect .onion'  is on and when it is off.

**Comment by fmarier** [comment]
For reference, this is mentioned in [RFC7686](https://tools.ietf.org/html/rfc7686#section-4).

Here's Firefox test case for it: https://searchfox.org/mozilla-central/source/netwerk/test/unit/test_dns_onion.js

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.22.43 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

**Auto redirect off**

* Start Wireshark and filter for dns.
* disable DoH in `brave://settings/security` (makes it easier to see requests in Wireshark)
* Open a normal window and type `https://brave5t5rjjg3s6k.onion/` in the URL bar.
* Confirm that you get an error page and that the .onion didn't result in a DNS lookup.
<img width="1680" alt="Screen Shot 2021-02-23 at 2 21 47 PM" src="https://user-images.githubusercontent.com/387249/108916926-d070a000-75e3-11eb-9148-a23d1e4dd3e8.png">

* There should be a "Open in Tor" button
* Click it and confirm that it opens `https://brave5t5rjjg3s6k.onion/` in Tor window
* Go back to the tab of step 2 and type `https://brave5t5rjjg3s6k.com/` in the URL bar.
"Open in Tor" button should be clear
<img width="1675" alt="Screen Shot 2021-02-23 at 2 23 20 PM" src="https://user-images.githubusercontent.com/387249/108916923-cf3f7300-75e3-11eb-9313-45187e62ffa5.png">

**Auto redirect on**
* Start Wireshark and filter for dns.
* disable DoH in `brave://settings/security` (makes it easier to see requests in Wireshark)
* Go to `brave://settings/extensions` and turn on Automatically redirect .onion sites
* Open a normal window and type `https://brave5t5rjjg3s6k.onion/` in the URL bar.
* Confirm that you get an error page and that the .onion didn't result in a DNS lookup.
* Tor window should be opened automatically with https://brave5t5rjjg3s6k.onion/
<img width="1676" alt="Screen Shot 2021-02-23 at 2 19 49 PM" src="https://user-images.githubusercontent.com/387249/108916929-d070a000-75e3-11eb-9176-fc217bf9d432.png">

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
-- | --
Revision | 31b458a18f133db9203eb5a5dd6552de0716dda3-refs/branch-heads/4324_182@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.804)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/8040#issue-578027432
- Verified the test plan from https://github.com/brave/brave-core/pull/7713#issue-562159331
