### ISSUE TITLE
Move P3A and crash reporting to Get Started section in brave://settings

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#14269]
## Description 

Currently, P3A and crash reporting is buried in Privacy and Security. As part of the longer term vision for P3A and informing users of it, we want to surface it in the Get Started section, give it a clearer label and make it easier for users to find.

## Steps to Reproduce

   1. Go to brave://settings
   2. scroll down to Privacy and Security
   3. Have a hard time finding the crash reporting or P3A items

## Actual result:

<img width="712" alt="Screen Shot 2021-02-19 at 4 50 55 PM" src="https://user-images.githubusercontent.com/2388823/108576478-a6149f00-72d2-11eb-93f3-d3e89c1497f4.png">

## Expected result:
![image](https://user-images.githubusercontent.com/2388823/116756580-33eec380-a9c1-11eb-8ad4-b29b248a1a5e.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

All versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Follow up to https://github.com/brave/brave-browser/issues/14183

Related to https://github.com/brave/brave-browser/issues/12680

**Comment by fmarier** [comment]
There are also two more types of data collection that are lacking an opt-out:
- variation server (requested in https://github.com/brave/brave-browser/issues/15711)
- Ads-related user studies (e.g. https://github.com/brave/security/issues/439)

Perhaps it makes sense to have a data collection sub-section like Firefox:
![Screenshot from 2021-05-11 14-00-37](https://user-images.githubusercontent.com/167821/117884418-73d76580-b261-11eb-8887-d01cdb8a30da.png)

**Comment by diracdeltas** [comment]
I think usage pings should also be moved to here once it's implemented. (#16378) 

The entire Security and Privacy section of settings should also be moved so it's not behind the drop-down on the sidebar. If needed we can switch it with the Safety Check menu item which isn't very important.

**Comment by rebron** [comment]
@karenkliu Need an update design for the usage ping setting under Automatic Crash Reporting.

**Comment by diracdeltas** [comment]
i started a discussion in slack about whether this is even necessary if https://github.com/brave/brave-browser/issues/16470 is done

**Comment by rebron** [comment]
Closing as stale, we'll keep P3A and crash reporting under Privacy and Security setting but move that section up. We'll continue that work in #16470
