### ISSUE TITLE
Count of ads blocked in desktop should have option to disable the count

### ISSUE THREAD

**Issue by vrindavan** [brave/brave-browser#14260]
## Description 

I think this might get closed pretty soon but the main point is on windows desktop currently the brave icon in the address bar shows number of ads blocked on top of the icon but in Android it does not show that instead it only has the brave icon highlighted so the suggestion is to add an option like that in desktop too where either remove the number of ads blocked and put it in the details when the user clicks the icon for further details about the blocking on the present page or add an option for the user to decide whether they want to see the number of ads blocked on the icon or hide it into the details.

**Comment by rebron** [comment]
hi @vrindavan There's already a setting to hide ad block count. brave://settings/shields
That should take care of it. `Show the number of blocked items on the Shields icon`

**Comment by vrindavan** [comment]
Oh, sorry I did not get it at first. Thanks.
@rebron
