### ISSUE TITLE
"New Tor Connection For This Site" is capitalized weirdly

### ISSUE THREAD

**Issue by wyatt400** [brave/brave-browser#14270]
"New Tor Connection For This Site" on the Desktop Brave Browser is capitalized weirdly. All of the other menu items are capitalized in a different format.

Steps to reproduce:
1. Open the Brave Browser on Desktop
2. Open a New TOR Window
3. Click the Menu Icon

Actual: "New Tor Connection For This Site" shows.

Expected: "New Tor connection for this site" shows.

Reproduces how often?
Always reproduces.

Brave version: 1.20.103
Chromium version: 88.0.4324.152

Happens on all channels and versions.

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards?  **No**
- Is the issue reproducible on the latest version of Chrome?  **No (because Chrome doesn't have TOR)**

**Comment by bsclifton** [comment]
cc: @rebron @bradleyrichter we were using the title casing across the board - should we update this?

**Comment by rebron** [comment]
We've been moving to sentence casing in settings, we should make change here too.
cc: @karenkliu

**Comment by karenkliu** [comment]
Right, the title casing is from Apple. On desktop we've been moving to all sentence casing. iOS has made the choice to stick with title casing since mobile designs adhere more strictly to the OS styling.

**Comment by stephendonner** [comment]
Verified `FIXED` on `beta` using 

Brave | 1.22.49 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

Verified the string is "New Tor connection for this site"

<img width="935" alt="Screen Shot 2021-03-02 at 2 59 42 PM" src="https://user-images.githubusercontent.com/387249/109726687-fc51cf80-7b67-11eb-8f6e-90a7591ba2fe.png">
