### ISSUE TITLE
Google Doubleclick ads not blocked on Core but blocked on Muon (orlandosentinel.com)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#1428]
**Issue:** 3rd party programmatic ads from Google not being blocked on Brave-core. Example: https://orlandosentinel.com. However, these ads are all blocked on the Muon browser. (Discovered by Brad Flora.)

Shields count (items blocked) on Muon 2-4x higher than on Core shields.

Example of advertisement coming through on Core: ![image](https://user-images.githubusercontent.com/11497541/46491001-57781000-c7be-11e8-88f7-cdea62a05f3e.png)

**Comment by bbondy** [comment]
https://orlandosentinel.com seems down, is there another site?

**Comment by bbondy** [comment]
https://www.orlandosentinel.com works

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows
