### ISSUE TITLE
Inaccessible in poor connection

### ISSUE THREAD

**Issue by jmsj777** [brave/brave-browser#14287]
## Description 

The brave browser on android make my phone almost crash when in poor connection (i.e. the mobile network is only E), It keeps reloading the start page and it takes some time to even be able to close it

## Steps to Reproduce

   1. Have a mobile connection in"E", not 4g, not 3g, but E
   2. Just open the browser

## Actual result:

The start page keeps refreshing

## Expected result:

Just open the browser, even though the connection is poor, it should be possible to access it, slow, but possible.

## Reproduces how often: 

Every time I try with the same connection

## Brave version (info found on brave://version)

Brave version 1.20.103, Chromium 88.0.4324.152
Android version 9.0, S40 Build/P00610

**Comment by anthonypkeane** [comment]
Thanks for reporting @jmsj777  - I'm going to close this as if you are on Edge there is not much we can do to to help the browser work faster.
