### ISSUE TITLE
IPFS link called from command line don't load in Brave window

### ISSUE THREAD

**Issue by Szczerbo** [brave/brave-browser#14283]
## Description 
When trying to call ipfs link from commad line on Windows(don't know how its behave on onther systems) it only opens new Brave window but with no content.

## Steps to Reproduce
   1. Fire command (from command prompt) -> "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html

## Actual result:
Brave window will appear but with no contet

## Expected result:
New Brave window with ipfs content loaded

## Reproduces how often: 
Easy to reproduce - its permanent

## Brave version (info found on brave://version)
Version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (64-bit)

**Comment by Szczerbo** [comment]
Found workaround for this specific case.

According to IPFS docs, If You have installed and active IPFS Node, You can simply call ipfs resources as http link - web browser will redirect You to requested resource.

Sample command (Windows cmd) - just paste it and hit "Enter":
"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" http://bafybeicgmdpvw4duutrmdxl4a7gc52sxyuk7nz5gby77afwdteh3jc5bqa.ipfs.localhost:8080/wiki/Mars.html

**Comment by spylogsster** [comment]
it works for me in last nightly, @Szczerbo could you please recheck?

**Comment by Szczerbo** [comment]
> it works for me in last nightly, @Szczerbo could you please recheck?

did double check right now, and still have this same problem. Few days ago did some  on clean install of Brave also on VM with fresh Windows installation and brave, and had this same problem.

**Comment by spylogsster** [comment]
@Szczerbo could you share screenshot of your brave://settings/ipfs ?

**Comment by Szczerbo** [comment]
> @Szczerbo could you share screenshot of your brave://settings/ipfs ?

ofc. -> here is .png https://file.io/8XSJEaYmS2dX

**Comment by spylogsster** [comment]
@Szczerbo it says file deleted

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.24.65 Chromium: 90.0.4430.72 (Official Build) dev (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Windows 10 OS Version 2004 (Build 19041.867)

```
- Verified the STR from the description and ensured IPFS link called from cmd line opens up brave with IPFS content
