### ISSUE TITLE
Unable to login to Instagram

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#14289]
## Description 
Unable to login to instagram.com

## Steps to Reproduce

   1. Open `https://www.instagram.com`
   2. Click on `Log in with Facebook`
   3. Enter your Facebook user details.
   4. When it attempts to load, it will show a blank, white page.

## Actual result:
![instag](https://user-images.githubusercontent.com/1659004/108705035-a67e9580-7571-11eb-9e97-9f8eacc43651.png)

## Expected result:
Allow user to login too Instagram without changing shield Settings

## Reproduces how often: 

Easily

## Brave version (brave://version info)
`Version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes (Allow Cookies)

## Miscellaneous Information:
Enabling `Ephemeral Storage` didn't fix the issue here.

**Comment by ryanbr** [comment]
Further testing in exceptions on `cookie_settings_base.cc`  Allowing cookies between `instagram.com` and `facebook.com`. No blocked facebook cookies in shields after this change

White screen still shows on: `https://www.instagram.com/accounts/signup/`  But if you refresh signup page the user is presented with "Continue with Facebook username", and then the user can continue using instagram.

![insta1](https://user-images.githubusercontent.com/1659004/108779958-93e57a00-75cc-11eb-8896-13f805267df5.png)
![insta2](https://user-images.githubusercontent.com/1659004/108779968-98aa2e00-75cc-11eb-9c44-a8d5137a6772.png)

**Comment by pes10k** [comment]
@ryanbr short term can we add an instagram <-> facebook cookie exceptions to solve this, and then create a follow up issue to dig into further?

**Comment by lxwulf** [comment]
I have the same problem, have the login screen, but it reloads after press the enter key, can't type in the 2FA!

**Comment by lxwulf** [comment]
I can log in again on the newest nightly version so for me, it is solved.

Greets

LxWulf

**Comment by ryanbr** [comment]
Further investigation of the "Blank page" after login issue. Not actually a Brave issue. Was able to reproduce in both Firefox and Chrome (Clearing cookies, uBO disabled/enabled made difference) Seems to an issue on their side. @pes10k 

![firefox-chrome](https://user-images.githubusercontent.com/1659004/111065932-37b5ac00-8521-11eb-9a3b-6a1ca071fef7.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` build on `instagram.com`

Brave | 1.24.14 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

Used the following steps:

1. loaded `instagram.com`
2. clicked on `Log in with Facebook`
3. logged in using `Facebook` credentials
4. was redirected back to `instagram.com`, where I now had a logged-in session
5. verified that cookies for `instagram.com` and `facebook.com` were set

| Example | Example | Example | Example | 
|----------|---------|----------|----------|
<img width="1367" alt="Screen Shot 2021-03-23 at 1 52 55 PM" src="https://user-images.githubusercontent.com/387249/112217172-8fb67780-8bdf-11eb-92aa-4c5a1f5fa87e.png"> | <img width="1367" alt="Screen Shot 2021-03-23 at 1 53 35 PM" src="https://user-images.githubusercontent.com/387249/112217190-9513c200-8bdf-11eb-8f16-9cd22b1554a1.png">  | <img width="1367" alt="Screen Shot 2021-03-23 at 1 53 49 PM" src="https://user-images.githubusercontent.com/387249/112217186-93e29500-8bdf-11eb-8633-bd6849a2e237.png"> | <img width="1367" alt="Screen Shot 2021-03-23 at 1 54 13 PM" src="https://user-images.githubusercontent.com/387249/112217183-92b16800-8bdf-11eb-8325-891381d61e6f.png">
