### ISSUE TITLE
Inline tips on GH doesn't show translated text when page content is updated

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14292]
## Description 

Inline tips on GH doesn't show translated text when page content is updated

## Steps to Reproduce

   1. Visit any GH page with rewards enabled
   2. Update title/update issue content to trigger page update reload
   3. Tips button doesn't show `Tip` instead shows untranslated text
   4. Reload the page fixes the issue 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/108722103-aa32fd80-751a-11eb-8172-bb5fc4ffe5fa.png)

## Expected result:
Never stop showing text even when there is a page reload trigger

## Reproduces how often: 

Somewhat easy when it repro's

## Brave version (brave://version info)

Brave | 1.20.108 Chromium: 88.0.4324.182 (Official Build) (64-bit)
-- | --
Revision | `73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Probably
- Can you reproduce this issue with the nightly channel? Probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/rewards @brave/legacy_qa

**Comment by emerick** [comment]
Let's retest this please, it should be fixed due to recent Greaselion changes.

**Comment by LaurenWags** [comment]
Verified using dev component for:

```
Brave Local Data Updater - Version: 1.0.601
```

This was fixed previously with https://github.com/brave/brave-browser/issues/12900.

Executed GH test case from https://github.com/brave/brave-browser/issues/12900#issuecomment-1100167370 to confirm still working as expected.
