### ISSUE TITLE
Rainmeter Extension Broken

### ISSUE THREAD

**Issue by unillama15** [brave/brave-browser#14293]
## Description:
Rainmeter's NowPlaying Companion extracts info on websites like youtube to help in the functioning of visualiser based desktop skins. Brave's privacy features break the proper functioning of this extension:
Link to extension: https://chrome.google.com/webstore/detail/webnowplaying-companion/jfakgfcdgpghbbefmdfjkbdlibjgnbli?hl=en
GitHub Rep of extension: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension
## Steps to Reproduce
   1.  Install the above extension.
   2. Set up any visualiser (eg. Monstercat Visualiser)
   3. Use website like YouTube to see song info on desktop.

## Actual result:
The extension is unable to extract data from the website and doesn't display anything.

## Expected result:
The companion must display Now Playing data correctly.
(Works on all other Chromium browsers)

## Reproduces how often: 
Consistent

## Brave version (brave://version info)

Brave | 1.20.108 Chromium: 88.0.4324.182 (Official Build) (64-bit)
-- | --
Revision | 73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS | Windows 10 OS Version 2009 (Build 19042.804)

## Version/Channel Information:
Consistent in all channels.

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Tried to disable Brave Shields on even on the media websites such as YouTube while playing media and it still does not work as intended.

**Comment by rebron** [comment]
@unillama15 Can you file this same issue here: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues

**Comment by unillama15** [comment]
The issue has been fixed with an Extension update

**Comment by ryanbr** [comment]
Thanks for update @unillama15
