### ISSUE TITLE
Cosmetic Filters don't apply custom rules

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#14294]
## Description 

Original problem is described here https://www.reddit.com/r/brave_browser/comments/lnwon9/brave_native_adblocker_custom_cosmetic_filters/

## Steps to Reproduce

   1. Go to brave://adblock
   2. Add that rule there `reddit.com##div`
   3. Go to reddit.com

## Actual result:

The page is not blank

## Expected result:
The page is blank

## Reproduces how often: 

Always

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

Reproduces on Nightly/Beta only

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
labeling as `QA/Blocked` until uplift is completed

**Comment by SergeyZhukovsky** [comment]
reopened as it's still a problem

**Comment by LaurenWags** [comment]
removing `QA/Blocked` as this should be available for testing in https://github.com/brave/brave-browser/releases/tag/v1.21.68

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.21.68 Chromium: 89.0.4389.58 (Official Build) (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 10.15.7 (Build 19H512)
```

* ensured that adding/removing `reddit.com##div` worked as expected

**`Without Custom Filter`** | **`Without Custom Filter`**
---------------|----------------
<img width="1009" alt="adblock-nofilter" src="https://user-images.githubusercontent.com/28145373/109161571-36c10400-7745-11eb-9bbf-4cead9baa7d7.png"> | <img width="1006" alt="reddit-nofilter" src="https://user-images.githubusercontent.com/28145373/109161573-37f23100-7745-11eb-91d3-a0167533299e.png">

**`With Custom Filter`** | **`With Custom Filter`**
---------------|----------------
<img width="1004" alt="adblock-filter" src="https://user-images.githubusercontent.com/28145373/109161590-3de81200-7745-11eb-8dc5-76501cd7bdf9.png"> | <img width="1007" alt="reddit-filter" src="https://user-images.githubusercontent.com/28145373/109161595-3f193f00-7745-11eb-8c77-8d60f64db5b9.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.70 x64 build
- Verified custom rules work as expected for cosmetic filters

No custom filter | Reddit.com without custom filter
-- | --
![image](https://user-images.githubusercontent.com/17010094/109465309-e22cca00-7a5f-11eb-9bb9-3f9829f0df7e.png) | ![image](https://user-images.githubusercontent.com/17010094/109465316-e527ba80-7a5f-11eb-81a4-7d782fe68386.png)

Custom filter | Reddit.com with custom filter
-- | --
![image](https://user-images.githubusercontent.com/17010094/109465328-ea850500-7a5f-11eb-8f23-06e8cdfe7c18.png) | ![image](https://user-images.githubusercontent.com/17010094/109465340-efe24f80-7a5f-11eb-9482-01f46ae2cadb.png)

------------
Verification passed on Samsung Tab A with Android 10 running 1.21.70 x64 build
- Verified custom rules work as expected for cosmetic filters

No custom filter | Reddit.com without custom filter
-- | --
![image](https://user-images.githubusercontent.com/17010094/109465739-8b73c000-7a60-11eb-8c9f-c88c6d08776a.png) | ![image](https://user-images.githubusercontent.com/17010094/109465751-8e6eb080-7a60-11eb-885a-181476e849f5.png)

Custom filter | Reddit.com with custom filter
-- | --
![image](https://user-images.githubusercontent.com/17010094/109465761-929ace00-7a60-11eb-9dcf-806ecb0def9d.png) | ![image](https://user-images.githubusercontent.com/17010094/109465769-96c6eb80-7a60-11eb-9e1b-00234b4e959d.png)
