### ISSUE TITLE
Googletagservices is blocked instead of mocked

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1430]
Tracking protection gets to it first.

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified https://www.googletagservices.com/tag/js/gpt.js directed me to:
![screen shot 2018-10-13 at 5 41 55 pm](https://user-images.githubusercontent.com/28145373/46910261-4c845480-cf0f-11e8-8409-0ebb6e276289.png)
