### ISSUE TITLE
hotmail - outlook live stops working

### ISSUE THREAD

**Issue by rajinder-yadav** [brave/brave-browser#14304]
## Description 

open session of hotmail will stop working, the page goes blank on tab switch to it. when i close the tab and open a new session, tab indicator keeps spinning for 1 min+ and either fails or loads hotmail page slowly.

hitting refresh doesn't help

checked with firefox, load immediately

## Steps to Reproduce

   1. log into hotmail online
   2. leave tab open 
   3. switch back to it once in a while

## Actual result:

at odd times the page becomes blank when switching to the tab

close tab, open new session, page hangs while loading

## Expected result:

page loads quickly

## Reproduces how often: 

has happened multiple times, not sure what causes the issues. unable to make it happen on demand.

i suggest do a few refresh and not when it gets sluggish loading and look into why

## Brave version (brave://version info)

Version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (64-bit)

running on linux opensuse tumbleweed

**Comment by rajinder-yadav** [comment]
![snap-27](https://user-images.githubusercontent.com/439226/110034535-93558d80-7d08-11eb-9084-c9aaee9fcd0e.png)

**Comment by rebron** [comment]
Hi @rajinder-yadav Are you still having this issue with our latest 1.24.82?

**Comment by rajinder-yadav** [comment]
let me get back to you in a few days, i do notice i have this version installed

**Comment by rajinder-yadav** [comment]
Hi I am closing this off, looks like the problem is fixed, I haven't seen issues wit hotmail hanging.

**Comment by ryanbr** [comment]
Thanks for the update @rajinder-yadav

**Comment by rebron** [comment]
@rajinder-yadav Is this happening to you with any other web sites/apps?

**Comment by rajinder-yadav** [comment]
This only happens with outlook.live and I notice just the past few days it's taking even longer to sign- in. I just checked using Chromium and I was able to login right away.

**Comment by joneldiablo** [comment]
outlook allow have many sessions open, but, when I try to change account  brave close the tab and I can't change account, needs close the other session to see the second as unique

**Comment by rajinder-yadav** [comment]
FYI the problem I was seeing has been resolved, going to close this off.

@joneldiablo can you please open a new ticket, your problem is different than the one I described and I don't want this to be a free for all.
