### ISSUE TITLE
Crashes when stopping ipfs node via brave://ipfs

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14300]
## Steps to Reproduce

   1.  new profile, launch Nightly
   2.  load `brave://ipfs`
   3.  click Install and start
   4.  wait until the daemon starts and stats populate
   5. click Stop

## Actual result:

Crashes: https://share.backtrace.io/api/share/a8DTR0MVpaWZHopyejGc53

![ipfs-crash](https://user-images.githubusercontent.com/387249/108761822-2ec65180-7504-11eb-80af-9b10d67f5bcc.gif)

From the console:

```
generating ED25519 keypair...done
peer identity: 12D3KooWHuTc3ZPhtrmjZSvwKPF9BhDyhQDCbuUfuY491FAm19Ro
initializing IPFS node at /Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/brave_ipfs
to get started, enter:

	ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme

Error: daemon not running
Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
Swarm listening on /ip4/10.0.0.38/tcp/44002
Swarm listening on /ip4/127.0.0.1/tcp/44002
Swarm listening on /ip6/::1/tcp/44002
Swarm listening on /p2p-circuit
Swarm announcing /ip4/10.0.0.38/tcp/44002
Swarm announcing /ip4/127.0.0.1/tcp/44002
Swarm announcing /ip6/::1/tcp/44002
API server listening on /ip4/127.0.0.1/tcp/45002
WebUI: http://127.0.0.1:45002/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/48081
Daemon is ready
[28175:775:0222/114554.978103:ERROR:CONSOLE(0)] "Unrecognized Content-Security-Policy directive 'defaultframe-ancestors'.
", source: chrome://ipfs/ (0)

Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
[0222/114558.644501:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5)
zsh: segmentation fault  ./Brave\ Browser\ Nightly --args --enable-logging=stderr  --brave-ads-staging
```

## Expected result:

Node stopped, no crash

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

**Comment by iefremov** [comment]
There is a better stack https://brave.sp.backtrace.io/p/brave/debug?filters=(_deleted%3D0%2C_rxid%3D%2258310000-ab7a-e305-0000-000000000000%22%2C(ver%2Cregex%2C%2288%7C89%7C90.*%22)%2Cptype%3Dbrowser)&fingerprint=4c19615fefc9198ca8774bee50360bac739242ac9cf50d03fa9d3d6fa60e2ac4&debug=(c3708a,0,0)

**Comment by iefremov** [comment]
```
[ 00 ] ipfs::IpfsService::GetConnectedPeers(base::OnceCallback<void (bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)>)
[ 01 ] IPFSDOMHandler::HandleGetConnectedPeers(base::ListValue const*)
[ 02 ] content::mojom::WebUIHostStubDispatch::Accept(content::mojom::WebUIHost*, mojo::Message*)
[ 03 ] mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*)
[ 04 ] IPC::(anonymous namespace)::ChannelAssociatedGroupController::AcceptOnProxyThread(mojo::Message)

```

**Comment by stephendonner** [comment]
Verified `FIXED` on `beta` using the inline steps to reproduce, on

Brave | 1.22.49 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)
