### ISSUE TITLE
Missing translations for onboarding modal on first launch

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14309]
## Description 

Missing translations for onboarding modal on first launch

## Steps to Reproduce

   1. Set locale to France (FR)
   2. Install 1.21.65 x64 beta build
   3. Launch browser, trigger onboarding modal that is not translated

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/108821250-3abe1c00-75b5-11eb-9043-70cd7e4f3ce6.png)

## Expected result:
Translated strings when locale is not EN

## Reproduces how often: 

Easy 
## Brave version (brave://version info)

Brave | 1.21.62 Chromium: 88.0.4324.182 (Official Build) beta (64-bit)
-- | --
Revision | `73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @mkarolin

**Comment by btlechowski** [comment]
Dupe of https://github.com/brave/brave-browser/issues/14163

**Comment by srirambv** [comment]
Thanks for linking @btlechowski . Closing as dupe of #14163
