### ISSUE TITLE
Private, Tor, Guest windows are missing image

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14312]
## Description 

Found by @simonhong 

Private, Tor, Guest windows are missing the image.

Does not reproduce in 1.22.28, but does reproduce in 1.22.34, 1.22.37, etc.

## Steps to Reproduce

   1. Install 1.22.28, open Private, Tor, Guest windows. See expected image.
   2. Upgrade to newer version.
   3. Open Private, Tor, Guest windows.

## Actual result:

Private | Tor | Guest
----- | ----- | -----
<img width="1033" alt="Screen Shot 2021-02-23 at 8 38 02 AM" src="https://user-images.githubusercontent.com/28145373/108852208-4e688300-75b3-11eb-8468-14c4e4ca2038.png"> | <img width="1035" alt="Screen Shot 2021-02-23 at 8 37 51 AM" src="https://user-images.githubusercontent.com/28145373/108852214-4f99b000-75b3-11eb-914d-cca31fc65302.png"> | <img width="1035" alt="Screen Shot 2021-02-23 at 8 38 16 AM" src="https://user-images.githubusercontent.com/28145373/108852219-50324680-75b3-11eb-9d02-c4b189586058.png">

## Expected result:
Private | Tor | Guest
----- | ----- | -----
<img width="1033" alt="Screen Shot 2021-02-23 at 8 47 49 AM" src="https://user-images.githubusercontent.com/28145373/108852754-fe3df080-75b3-11eb-9e5e-db18f7c1d15e.png"> | <img width="1036" alt="Screen Shot 2021-02-23 at 8 48 01 AM" src="https://user-images.githubusercontent.com/28145373/108852762-0007b400-75b4-11eb-84a4-49895d0f4c3c.png"> | <img width="1034" alt="Screen Shot 2021-02-23 at 8 48 17 AM" src="https://user-images.githubusercontent.com/28145373/108852768-00a04a80-75b4-11eb-95d9-26491cc51bb2.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.22.28 CR: 89.0.4389.48 --> does not reproduce
1.22.34 CR: 89.0.4389.48 --> does reproduce
1.22.37 CR: 89.0.4389.58 --> does reproduce

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, 1.20.x
- Can you reproduce this issue with the beta channel? no, 1.21.x
- Can you reproduce this issue with the nightly channel? certain versions of 1.22.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa

**Comment by kjozwiak** [comment]
We'll want this one uplifted into `1.21.x` after we today's channel migrations.

**Comment by kjozwiak** [comment]
We'll want this one uplifted into `1.21.x` after we today's channel migrations.

**Comment by mkarolin** [comment]
Version 1.22.29 is already broken. Reverting https://github.com/brave/brave-core/pull/7967 (https://github.com/brave/brave-core/commit/8dc5ce7f1259f2e1b395c9781076323ef9813a65) fixes it. cc: @petemill @mihaiplesa

**Comment by bsclifton** [comment]
Nice find @mkarolin 😄 I'll submit a PR real quick

**Comment by bsclifton** [comment]
Manually reverted in `master` and in `1.22.x`. Problem shouldn't be in 1.21.x as https://github.com/brave/brave-core/pull/7967 landed in 1.22.x 👍

**Comment by stephendonner** [comment]
Verified `FIXED` on `beta` using 

Brave | 1.22.49 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

Confirmed there are no missing images, and that `Tor` still initializes properly in `New Private Window with Tor`

Private | Tor | Guest
----- | ----- | -----
<img width="1321" alt="Screen Shot 2021-03-02 at 2 46 40 PM" src="https://user-images.githubusercontent.com/387249/109726012-d5df6480-7b66-11eb-8256-e5e064985731.png"> | <img width="1321" alt="Screen Shot 2021-03-02 at 2 46 26 PM" src="https://user-images.githubusercontent.com/387249/109726037-e099f980-7b66-11eb-866a-5b645398e471.png"> | <img width="1321" alt="Screen Shot 2021-03-02 at 2 49 20 PM" src="https://user-images.githubusercontent.com/387249/109725997-d0821a00-7b66-11eb-9507-1101e8395ff8.png">
