### ISSUE TITLE
Allow refreshing status for verified publishers

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#14313]
## Description 
The Rewards panel currently shows a "Refresh Status" link for unverified publishers, which allows a user to check if the publisher is verified and (if so) update the publisher info on the client.

However, we ran into a situation with bitFlyer where a verified publisher was later disconnected from Creators. This meant that the publisher still looked appeared to be verified on the client, yet the user had no means available to refresh the client status (and the client publisher info is cached for some period of time).

We should address this by showing the "Refresh Status" link for unverified and verified publishers.

## Steps to Reproduce

   1. Visit a verified publisher
   2. Open the Rewards panel

## Actual result:

No "Refresh Status" link in the panel.

## Expected result:
The "Refresh Status" link should appear in the panel regardless of the verified/unverified state of the publisher.

## Reproduces how often: 

Easily reproduced.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.23.23 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.3 (Build 20D91)

Tested on verified and unverified creators, respectively:

**Verified**
* `https://laurenwags.github.io/`
* `https://www.github.com/laurenwags`
* `duckduckgo.com`
* `youtube.com/jjdsampson`
* `reddit.com/u/alex_the_brave`
* `3zsistemi.si`
* `https://vimeo.com/bravelaurenwags`

**Unverified**
* `https://stephendonner.wordpress.com/`
* `cnn.com`
* `msnbc.com`
* `microsoft.com`

**Test plan:**

* Clean profile
* Start browser (I used `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging  --rewards=staging=true`)
* Enable Rewards
* Visit a verified publisher
* Verify that `Refresh Status` link appears for verified publisher
<img width="1607" alt="Screen Shot 2021-03-08 at 6 06 02 PM" src="https://user-images.githubusercontent.com/387249/110408791-03cb1a00-803b-11eb-8a3c-3b881ef30f23.png">

* Verify via logs that clicking `Refresh Status` calls the server to retrieve the latest data for the given publisher

```
[2269:775:0308/182918.824697:VERBOSE5:ledger_impl.cc(139)] 
[ REQUEST ]
> URL: https://pcdn.bravesoftware.com/publishers/prefixes/c04d
> Method: UrlMethod::GET
[2269:775:0308/182919.131805:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://pcdn.bravesoftware.com/publishers/prefixes/c04d
> Result: Success
> HTTP Code: 200
```

* Verify that `Refresh Status` link continues to appear and work for unverified publishers as well
![image](https://user-images.githubusercontent.com/387249/110408796-0594dd80-803b-11eb-8633-c5a0846dff14.png)
```
[2269:775:0308/182838.309821:VERBOSE5:ledger_impl.cc(139)] 
[ REQUEST ]
> URL: https://pcdn.bravesoftware.com/publishers/prefixes/ad8a
> Method: UrlMethod::GET
[2269:775:0308/182838.311690:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://pcdn.bravesoftware.com/publishers/prefixes/ad8a
> Result: Success
> HTTP Code: 200
> Body: 
[2269:775:0308/182838.311778:VERBOSE1:database_server_publisher_banner.cc(43)] Empty publisher banner data, skipping insert
```
