### ISSUE TITLE
Integrate with BAP reporting endpoint

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#14315]

**Comment by kjozwiak** [comment]
Pending `1.21.x` uplift via https://github.com/brave/brave-core/pull/8178.

**Comment by LaurenWags** [comment]
Per discussion in Rewards meeting today, this will only be checked on Windows once uplifted to 1.21.x.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Windows 10 OS Version 2004 (Build 19041.804)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/8054
