### ISSUE TITLE
make sure we have necessary fixes from Ungoogled Chromium

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#1431]
People often ask how Brave compares to https://github.com/Eloston/ungoogled-chromium. This is a tracking issue to go through all the patches and options set in https://github.com/Eloston/ungoogled-chromium and make sure we have any that should be applied to Brave.

**Comment by rht** [comment]
I had gone through the [inox-patchset](https://github.com/gcarq/inox-patchset) (which is also applied in ungoogled-chromium) to find the mapping with the existing patches.

1. [ ] Fix building without safebrowsing.
2. [ ] Fix building without reporting.
3. [ ] Disable autofill download manager.
4. [x] Disable google url tracker. https://github.com/brave/brave-core/commit/d49d88eb3588873b94109f1a3562db25cc9545b1
5. [ ] Disable default extensions.
6. [ ] Modify default prefs. Some of them have been set in browser/brave_profile_prefs.cc, excpet for: kOfferTranslateEnabled, kBackgroundModeEnabled, kAutofillEnabled, kBuiltInDnsClientEnabled, kSignInPromoShowOnFirstRunAllowed, kCloudPrintConnectNewPrinters, kLocalDiscoveryNotificationsEnabled, kSafeBrowsingEnabled, kCredentialsEnableService, kCredentialsEnableAutosignin have yet to be disabled. kSignInPromoUserSkipped has yet to be enabled.
7. [ ] Disable web resource service. https://github.com/brave/brave-core/blob/master/patches/chrome-browser-plugins-plugins_resource_service.cc.patch
8. [ ] Restore classic ntp.
9. [ ] Disable google ipv6 probes.
10. [x] Disable gcm status check. https://github.com/brave/brave-core/blob/master/patches/components-gcm_driver-gcm_client_impl.cc.patch
11. [x] Add ddg. https://github.com/brave/brave-core/blob/master/components/search_engines/brave_prepopulated_engines.cc
12. [x] Branding. N/A
13. [ ] Disable missing key warning.
14. [x] Disable translation language fetch. https://github.com/brave/brave-core/blob/master/patches/components-translate-core-browser-translate_url_fetcher.cc.patch
15. [ ] Disable update pings.
16. [ ] Add `-fPIE` compilation flag. Not google-specific but helps to harden the binary.
17. [ ] Disable new avatar menu. Not sure if required.
18. [x] Disable first run behavior. https://github.com/brave/brave-core/blob/master/patches/chrome-browser-ui-startup-startup_tab_provider.cc.patch
19. [ ] Disable battery status service. Not sure why this should be disabled
20. [x] Launcher branding. N/A
21. [ ] Disable RLZ. RLZ is an identifier on where Chrome was downloaded and its installation week.

Other than disabling cloud print, patches 8 and 9, in particular, probably should be applied soon.

**Comment by pilgrim-brave** [comment]
3 Autofill download manager is disabled by modifying the command line in https://github.com/brave/brave-core/blob/master/app/brave_main_delegate.cc

**Comment by pilgrim-brave** [comment]
15 Disable update pings ... Brave implements its own configurator in https://github.com/brave/brave-core/blob/master/browser/component_updater/brave_component_updater_configurator.cc

**Comment by pilgrim-brave** [comment]
8 Restore classic ntp ... Brave implements its own new tab page, see for example https://github.com/brave/brave-core/blob/master/browser/ui/webui/brave_new_tab_ui.cc and related files

**Comment by pilgrim-brave** [comment]
19 Disable battery API ... this was originally disabled in https://github.com/brave/brave-core/pull/114 and is still disabled, although the code looks different now. See https://github.com/brave/brave-core/blob/master/chromium_src/third_party/blink/renderer/modules/battery/battery_manager.cc for latest code.

**Comment by vordenken** [comment]
> 19 Disable battery API ... this was originally disabled in [brave/brave-core#114](https://github.com/brave/brave-core/pull/114) and is still disabled, although the code looks different now. See https://github.com/brave/brave-core/blob/master/chromium_src/third_party/blink/renderer/modules/battery/battery_manager.cc for latest code.

I tested my fingerprint using brave with https://amiunique.org/fp and the site can still access the battery api? 
This is what the site reports back:
<img width="725" alt="grafik" src="https://user-images.githubusercontent.com/62395860/91549830-dbde5980-e927-11ea-82e5-c85816d92177.png">

I would love to use brave as my main browser but this and a lot of other stuff is really weird to me. A "privacy-browser" should lock down these fingerprinting options as good as possible. For example, why can a website read my installed addons? Makes a lot of users unique just by this. 
Other fingerprinting apis that are not necessary and disabled in firefox by default:
- Keyboard layout
- Connection
(Probably more but I'm no expert)

Safari also just gives default values back for stuff like fonts, which would also be a great idea.

**Comment by pes10k** [comment]
I'm going to close this out as non-actionable for the time being, and since its been quiet for about 1.5 years, and since all of the mentioned issues in the comments have been addressed. If more things come up we should grab or align w/ Ungoogled Chromium on though, lets open up more issues for them specifically
