### ISSUE TITLE
Unsafe use of base::Unretained when deleting log files in Rewards service

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#14316]
@bridiver mentioned that there are a few instances of unsafe uses of `base::Unretained(this)` and other practices in the Rewards service:

1. In `RewardsServiceImpl::OnStopLedgerForCompleteReset`, we should post a task to clear the log with a bound `WeakPtr` and then perform the `PostTaskAndReplyWithResult`. Since they execute in the order posted, it's safe to do this.
2. The use of `base::Unretained(this)` in `ClearDiagnosticLog` is also unsafe.
3. `DeleteLogTaskRunner` should be an anonymous method, pass the diagnostic log as a file path not a `base::Path` to avoid lifetime issues.
4. `LoadDiagnosticLogOnFileTaskRunner` should be an anonymous method, pass the diagnostic log as a file path not a `base::Path` to avoid lifetime issues.
5. `RewardsServiceImpl` needs a sequence checker for its task runner methods.
6. ~Use `CancelableTaskTracker` with `ledger_database_` to cancel tasks and then call `DeleteSoon`.~ This will be handled via a separate issue on the advice of @bridiver.

From @iefremov:

> there is one more Unretained in RewardsServiceImpl::FetchFavIcon, and it seems we should add DependsOn to the factory code to properly depend on BitmapFetcherService

**Comment by iefremov** [comment]
Also double-check this trace , it should be fixed with the PR
https://brave.sp.backtrace.io/p/brave/debug?filters=(ptype%3Dbrowser)&fingerprint=245c29284152700d80e58257619438d44b03cf358b559af056cf13d527bfaa1e&debug=(c3d346,0,0)

```
[ 00 ] perfetto::PosixSharedMemory::start() const
[ 01 ] (anonymous namespace)::TipMessageHandler::GetShareURLCallback(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
[ 02 ] brave_rewards::RewardsServiceImpl::OnLoadDiagnosticLogOnFileTaskRunner(base::OnceCallback<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
[ 03 ] base::internal::Invoker<base::internal::BindState<void (media::InMemoryVideoDecodeStatsDBImpl::*)(base::OnceCallback<void (bool)>, media::VideoDecodeStatsDB*), base::WeakPtr<media::InMemoryVideoDecodeStatsDBImpl>, base::OnceCallback<void (bool)> >, void (media::VideoDecodeStatsDB*)>::RunOnce(base::internal::BindStateBase*, media::VideoDecodeStatsDB*)
[ 04 ] bat_ledger::mojom::BatLedger_GetShareURL_ForwardToCallback::Accept(mojo::Message*)

```

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` build with the testplan from https://github.com/brave/brave-core/pull/8123.

### Verify that reset works

1.   Clean profile
2.   Started browser with `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile_interval=5,persist-logs=true`
3.   Visited `brave://rewards`
4.   Opted-in to Rewards
5.   Claimed grant of `30.000 BAT`
6.   Visited a verified publisher (`https://twitter.com/bravelaurenwags`) and tipped `5.000 BAT`
7.   Went to wallet settings
8.   Performed a reset
9.   Closed the browser
10.  Verified that reset worked as expected:

Confirmed:
* both Ads and Auto-Contribute were toggled to `Off`
* log was reset (started over with new wallet) - both on-disk as well as in `brave://rewards-internals`
* the `30.000 BAT` token grant was re-issued

![reset-rewards](https://user-images.githubusercontent.com/387249/113054561-66a56200-915e-11eb-9d5f-870618562936.gif)


### Verify that logs are trimmed as expected

1.    Made sure that `Rewards.log` is close to 10,485,760 bytes in size (thx again to @emerick for providing that test file!); dropped it into my `Preferences` / `Default` folder
2.    Started browser with `--rewards=persist-logs=true`
3.    Visited `brave://rewards`
4.    Performed actions to generate enough logs that `Rewards.log` exceeds 10,485,760 bytes in size
5.    Ensured that the log is trimmed back to 20,000 lines (not bytes!)
6.    Closed the browser

| Rewards.log (huge) | Rewards.log (pared down) |
|----------|---------|
<img width="1775" alt="Screen Shot 2021-03-30 at 1 37 47 PM" src="https://user-images.githubusercontent.com/387249/113053544-3a3d1600-915d-11eb-812c-812484f21dc1.png"> | <img width="1775" alt="Screen Shot 2021-03-30 at 12 49 05 PM" src="https://user-images.githubusercontent.com/387249/113050430-addd2400-9159-11eb-861b-be76b7fc2af9.png">

### Verify brave://rewards-internals "Logs" tab

1.   Visited `brave://rewards-internals`
2.   Went to `Logs` tab
3.   Pressed `Refresh` and verified that appropriate logs were displayed
4.   Ensured that `Download File` worked as expected

Also verified:
* `Automatically refresh every 5 seconds` worked
* `Clear` button reset logging of `Rewards.log` both on-disk and in the UI
* `Refresh` (as above) manually refreshed the log
* `Download full log` prompted me to save the log as `brave_rewards_log.txt`; size and contents were correct

| Clear | `brave_rewards_log.txt` |
|----------|---------|
<img width="1312" alt="Screen Shot 2021-03-30 at 1 02 36 PM" src="https://user-images.githubusercontent.com/387249/113050428-addd2400-9159-11eb-99d4-cc240837b85e.png"> | <img width="1312" alt="Screen Shot 2021-03-30 at 12 46 01 PM" src="https://user-images.githubusercontent.com/387249/113050432-ae75ba80-9159-11eb-912f-a57e7cd326e1.png">
