### ISSUE TITLE
Feature: Total Cookie Protection

### ISSUE THREAD

**Issue by mogwai** [brave/brave-browser#14324]
Firefox have just added a great new Total Cookie Protection [feature](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) which mentions **Brave** at the bottom. 

I've noticed that blocking all cookies doesn't always protect me, why does google try to log me in on medium.com for example?

![image](https://user-images.githubusercontent.com/5440566/108901145-6a4f4180-7612-11eb-9f4e-797bf2d550a7.png)

Would a individual cookie jar for each site solve this issue? 

Does Brave intend to implement this feature?

**Comment by diracdeltas** [comment]
try disabling "enable google logins" in brave://settings/socialBlocking if you haven't already

**Comment by mogwai** [comment]
That worked thanks.
