### ISSUE TITLE
Open port detected if shield is enabled

### ISSUE THREAD

**Issue by fluguy007** [brave/brave-browser#14332]
Thanks for resolved DNS issue but one of issue is still there. When brave shield is on then open ports detected but if shield is off then everything is fine. I checked it on ‘whatleaks.com’. Please resolve this issue.

https://community.brave.com/t/open-port-issue-if-shield-is-enable/209765

**Comment by diracdeltas** [comment]
regular window or tor window? what operating system/version? 

on macOS i get the same result regardless of shields

**Comment by fluguy007** [comment]
regular and tor windows both. windows 10 pro latest build.
![With Shield](https://user-images.githubusercontent.com/79571119/109107382-d12c4200-775b-11eb-9976-2146557322d6.jpg)
![without shield](https://user-images.githubusercontent.com/79571119/109107391-d4273280-775b-11eb-8ac6-284b9ecbccef.jpg)

**Comment by fluguy007** [comment]
Now found that it's maybe tracker issue. I tried with brave shield on with "trackers and ads blocked" "aggressive/standard' then open port detected and if I allow all trackers and ads then everything is fine.

**Comment by diracdeltas** [comment]
^ @ryanbr any thoughts?

**Comment by ryanbr** [comment]
@fluguy007   Just tested this, all ports were blocked from scanning.  I get one open port when I allow shields (RDP in my case).

Can you retest again with shields UP, and paste or screenshot the blocked items from shields also?

![whatleaks](https://user-images.githubusercontent.com/1659004/109720543-1abed600-7c0f-11eb-9af8-fdf92395ca37.png)

**Comment by fluguy007** [comment]
@ryanbr I checked it again and same issue. I tried with windows fresh install and face same issue. I also checked my younger brother pc and there is same issue. Sometimes showing no port detection (very very rare case) but if clean cookies and cache then it showing again.
![Screenshot_7](https://user-images.githubusercontent.com/79571119/109772652-72b60680-7c28-11eb-862d-e5cbf7fb66c0.jpg)
![Screenshot_8](https://user-images.githubusercontent.com/79571119/109772660-75b0f700-7c28-11eb-855f-bc7aaa2ee5bd.jpg)

**Comment by ryanbr** [comment]
Okay https://github.com/brave/adblock-lists/pull/576   should stop it. give it 24-48hrs.

**Comment by ryanbr** [comment]
Testing in the latest build 1.21.74, Looking much better @fluguy007  Can you confirm?

**Comment by fluguy007** [comment]
after this update, brave block everything if shield is enabled {aggressive/standard mode} but allow all tracker/ads looking good. Testing with adblocker it's not good
![brave](https://user-images.githubusercontent.com/79571119/110295838-c99e5000-801b-11eb-924c-9031c1350f11.jpg)

**Comment by ryanbr** [comment]
Too mitigate the checks, I just nulled the checks. Its Brave specific fixes, not applicable to other browsers/extensions

**Comment by ryanbr** [comment]
Given the port detection (and other detection) is no longer a thing from this site, safe to close this now.

**Comment by fluguy007** [comment]
I/we used this site for checking for any leakage When using proxy/residential proxy or socks proxy. But now can't check this with this site.

**Comment by ryanbr** [comment]
Just disable shields on the site
