### ISSUE TITLE
Update default favicon

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#1433]
Follow-up from https://github.com/brave/brave-core/pull/548

I believe these require PNGs, e.g. https://cs.chromium.org/chromium/src/ui/resources/default_100_percent/common/default_favicon_64.png?dr&g=0

Will have to figure out how either to redirect the `IDR_DEFAULT_FAVICON` grit resource to point to our pngs, or copy files from brave to chromium src before that is generated

**Comment by rossmoody** [comment]
I don't know if maybe this one is worth updating to point to the .icon file to escape instances like this: 
![image](https://user-images.githubusercontent.com/29072694/46686156-4a876200-cbac-11e8-9a64-4c87f023d445.png)
