### ISSUE TITLE
Remove chrome-install_static-install_util.cc.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14334]
## Description 

This patch only enables a section of the code via `OFFICIAL_BUILD` **and** adapts the expected channel name for `version_info::Channel::CANARY` to `"nightly"` instead, being both changes in the `GetChromeChannel()` helper function.

Turns out that the entire implementation of this `GetChromeChannelName() -> version_info::Channel` resolution hasn't changed for ages with the exception of [when the very same code got moved from `channel_info_win.cc` into `chrome/install_static/install_util.cc`](https://codereview.chromium.org/2799013002/), so I think we could simply provide our own implementation of `GetChromeChannel()` method in a chromium_src override and get rid of yet another patch.

## Desktop Brave version:
Brave 1.23.1  (Chromium 89.0.4389.58)

## Miscellaneous Information:

See test plan from the attached PR for dev-only testing to verify this change doesn't break things.

**Comment by btlechowski** [comment]
@mariospr It seems that the test plan involves a dev-only testing, yet this issue has a `QA/Yes` label. Did you mean to set it to `QA/No`?

**Comment by mariospr** [comment]
@btlechowski You're right on that this is dev-only testing on that it's basically about running some tests locally, but I thought even then QA/Yes should be used. It seems to me now that I was wrong (i.e. looks like QA/Yes should only be used for testing user-facing behaviour?) so I guess QA/No is more correct. Thanks for bringing this up!
