### ISSUE TITLE
Brave overwrites document.adoptedStyleSheets

### ISSUE THREAD

**Issue by Artur-** [brave/brave-browser#14333]
## Description 
When you load a document that adds something to `document.adoptedStyleSheets`, Brave will remove that and replace it with Brave's own `content_cosmetic.cosmeticStyleSheet`

## Steps to Reproduce
```
<html>
<head>
<script> 
const sheet = new CSSStyleSheet();
sheet.replaceSync(`
span { color: blue }
`);

document.adoptedStyleSheets = [sheet, ...document.adoptedStyleSheets];

</script>          
<body>              
<span>I should be blue</span>
</body
```

Live version at https://artur.app.fi/brave-styles.html

## Actual result:
Text is black

## Expected result:
Text is blue

## Reproduces how often: 
Always

## Desktop Brave version:

1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Caused by overwriting document.adoptedStyleSheets instead of appending

**Comment by Haprog** [comment]
Issue happens only with Brave Shields tracker & ad blocking. When disabling shields or selecting "Allow all trackers & ands" (keeping other shields at defaults) it works correctly.

**Comment by diracdeltas** [comment]
^ cc @pes10k @SergeyZhukovsky 

thanks for opening a PR

**Comment by SergeyZhukovsky** [comment]
as @diracdeltas mentioned, thanks for the PR @Artur- , however I created a new one as wanted to include couple small check fixes as well. And our CI doesn't run on PRs from forks and I see some lint failures in long strings in your version. But thank you for doing it anyways, I'm going to close your PR in favour of this one https://github.com/brave/brave-core/pull/8081

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` until uplift is completed.

**Comment by kjozwiak** [comment]
Uplifted both https://github.com/brave/brave-core/pull/8089 & https://github.com/brave/brave-core/pull/8090. Should be in the next `1.21.x` RC 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.21.71 x64 build
- Verified steps from issue description

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/109625333-1f17c000-7b37-11eb-830f-b2be92563311.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/109625356-28089180-7b37-11eb-8ae3-644fae99b3d6.png>
