### ISSUE TITLE
Remove chrome-common-chrome_content_client_constants.cc.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14338]
## Description 

This patch could be removed in favour of chromium_src overrides to redefine the values for the constants we're interested in.

## Desktop Brave version:

Brave 1.23.1 (Chromium 89.0.4389.58)

## Miscellaneous Information:
This removal references a patch initially introduced with https://github.com/brave/brave-core/pull/2342

**Comment by stephendonner** [comment]
Verified `PASSED` with the testplan from https://github.com/brave/brave-core/pull/2342, using `nightly` build


Brave | 1.23.19 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

### Test fix for [brave/brave-browser#3694](https://github.com/brave/brave-browser/issues/3694)

1. Go to https://docs.google.com and login
2. Create a new Google Sheets document
3. Type some values in there
4. Pick File => Print from the Google apps menu (not the browser menu)
5. Try to print document
6. Document should actually print (you should not be prompted to save as PDF)

**NOTE:** Same behavior on `1.21.73 Chromium: 89.0.4389.72 (Official Build) (x86_64)`; this looks to be https://github.com/brave/brave-browser/issues/11913

<img width="1312" alt="Screen Shot 2021-03-04 at 4 43 34 PM" src="https://user-images.githubusercontent.com/387249/110051437-b719d300-7d0a-11eb-99bf-c9282a62e412.png">



### Test fix for [brave/brave-browser#884](https://github.com/brave/brave-browser/issues/884)

1. Go to http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.144.7135&rep=rep1&type=pdf
2. Document should load properly

<img width="1312" alt="Screen Shot 2021-03-04 at 4 45 42 PM" src="https://user-images.githubusercontent.com/387249/110051446-bd0fb400-7d0a-11eb-9509-7dcf25461478.png">



### Test fix for [brave/brave-browser#4424](https://github.com/brave/brave-browser/issues/4424)

1. Go to `http://pdfkit.org/demo/browser.html`
2. Document on right hand side should load properly

<img width="1312" alt="Screen Shot 2021-03-04 at 4 46 00 PM" src="https://user-images.githubusercontent.com/387249/110051445-bc771d80-7d0a-11eb-8464-a899086abc1e.png">



### Embed test (possible fix for [brave/brave-browser#3119](https://github.com/brave/brave-browser/issues/3119))

1. Go to `https://pdfobject.com/examples/detection.html`
2. Message `This browser supports inline PDFs` should be shown (green color)

<img width="1312" alt="Screen Shot 2021-03-04 at 4 45 33 PM" src="https://user-images.githubusercontent.com/387249/110051447-bda84a80-7d0a-11eb-8b4f-02f795d00728.png">



### Test that PDF.js is still installable

1. Go to `https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm`
2. Verify that you can install PDF.js
3. Verify that PDF.js puts a browser action button in the extension area
4. Verify that PDF.js shows in `brave://extensions`
5. Open a PDF document and verify PDF.js is used

<img width="1312" alt="Screen Shot 2021-03-04 at 4 47 07 PM" src="https://user-images.githubusercontent.com/387249/110051443-bbde8700-7d0a-11eb-8e66-35d15349d843.png">

<img width="1312" alt="Screen Shot 2021-03-04 at 4 48 12 PM" src="https://user-images.githubusercontent.com/387249/110051442-bb45f080-7d0a-11eb-9ea8-d8dc2239a211.png">


<img width="1312" alt="Screen Shot 2021-03-04 at 4 48 41 PM" src="https://user-images.githubusercontent.com/387249/110051439-b8e39680-7d0a-11eb-9b41-b00e0e079a19.png">



### Test that PDF.js does not show

1. Have an existing profile BEFORE testing this. Make sure PDF.js works
2. Upgrade to a build with this fix
3. Launch Brave from the command line with `--show-component-extension-options`
4. Verify PDF.js does **NOT** show in `brave://extensions`

<img width="1422" alt="Screen Shot 2021-03-04 at 5 22 39 PM" src="https://user-images.githubusercontent.com/387249/110053519-6d32ec00-7d0e-11eb-8014-3ab74ffb68b2.png">


5. Verify PDF.js does **NOT** show in `brave://components`

<img width="1312" alt="Screen Shot 2021-03-04 at 5 22 19 PM" src="https://user-images.githubusercontent.com/387249/110053495-61472a00-7d0e-11eb-9716-852bf3a40717.png">

**Comment by srirambv** [comment]
Removing `OS/Android` label as PDF is handled natively in Android and `chrome://extensions` doesn't resolve as extension support is not available on Android
