### ISSUE TITLE
Remove extensions-common-manifest_url_handlers.cc.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14343]
## Description 

This patch could be removed in favour of a chromium_src override to redefine `ManifestURL::GetWebStoreURL()` into a method that unconditionally returns an empty `GURL`

## Desktop Brave version:

Brave 1.23.1 (Chromium 89.0.4389.58)

## Miscellaneous Information:

This removal references a patch initially introduced with https://github.com/brave/brave-core/pull/215

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8065


Brave | 1.23.23 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.3 (Build 20D91)

Verified that the PDF Viewer extension is bundled and not attributed to the Chrome Web Store, when launching with:

`--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --rewards=staging=true --show-component-extension-options`

<img width="1607" alt="Screen Shot 2021-03-08 at 7 34 25 PM" src="https://user-images.githubusercontent.com/387249/110414872-abe5e080-8045-11eb-8ab2-242032f6c06b.png">

**Comment by srirambv** [comment]
Removing `OS/Android` label as PDF is handled natively in Android and `chrome://extensions` doesn't resolve as extension support is not available on Android
