### ISSUE TITLE
Toolbar icon refinement

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#1434]
Update toolbar icons to match refined alignment and style
- back
- forward
- refresh
- home
- security chip locks
- bookmark
- find-in-page
- avatar default icon
- menu button

### Old
![image](https://user-images.githubusercontent.com/741836/46509283-a93c8c80-c7f6-11e8-8ca6-f969ce1b0a9b.png)

### New
![image](https://user-images.githubusercontent.com/741836/46509314-cd986900-c7f6-11e8-9700-dc124a3414c7.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/46751421-8132aa80-cc88-11e8-9f8d-aa5e56ac721c.png)
