### ISSUE TITLE
[Crypto Wallet] Add support of Crypto Name Service (CNS) from Unstoppable Domains

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#14349]
## Description 
Adding support to resolve .crypto addresses and fixing our support of resolving .eth addresses in our crypto wallet.

## Steps to Reproduce

   1. Open brave://wallet and click `Send` to show `Add Recipient`.
   2. Input brave.crypto
   3. Input test.eth

## Expected result:
Address should be resolved in step 2 and 3.

**Comment by yrliou** [comment]
Resolved by https://github.com/brave/ethereum-remote-client/pull/221

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.22.49 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Linux
Component | `1.0.25 Dev`

- Verified test plan from issue description

brave.crypto | test.eth | brantly.eth
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/110281780-3fcb9400-7fd5-11eb-9148-2b5307d3f33d.png) | ![image](https://user-images.githubusercontent.com/17010094/110281806-4a862900-7fd5-11eb-83a7-7972b16b5e98.png) | ![image](https://user-images.githubusercontent.com/17010094/110281822-5376fa80-7fd5-11eb-9a16-c6ad17cf0231.png)

Errors

![image](https://user-images.githubusercontent.com/17010094/110281863-64277080-7fd5-11eb-8949-cf122c3c5d31.png) | ![image](https://user-images.githubusercontent.com/17010094/110281879-6c7fab80-7fd5-11eb-85b3-323c6ba1c227.png) | ![image](https://user-images.githubusercontent.com/17010094/110297352-49f88d00-7feb-11eb-8c6f-ace38f9be10e.png)
-- | -- | --

-----------------
Verification passed on 


Brave | 1.23.21 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.25 Dev`

- Verified test plan from issue description

brave.crypto | test.eth | brantly.eth
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/110296421-3b5da600-7fea-11eb-8059-8155f571657a.png) | ![image](https://user-images.githubusercontent.com/17010094/110296612-6e079e80-7fea-11eb-963e-a94302fe1173.png) | ![image](https://user-images.githubusercontent.com/17010094/110296677-8081d800-7fea-11eb-9bfc-488c7a268a1d.png)


Errors

![image](https://user-images.githubusercontent.com/17010094/110296801-a4451e00-7fea-11eb-8c9c-df7689afebf0.png) | ![image](https://user-images.githubusercontent.com/17010094/110296826-adce8600-7fea-11eb-9c4a-d40b2e72d7ba.png) | ![image](https://user-images.githubusercontent.com/17010094/110296967-da829d80-7fea-11eb-9c3b-2a37c98ff229.png)
-- | -- | -- 

---------
Verification passed on 

Brave | 1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Windows 10 OS Version 2009 (Build 19042.804)
Component | `1.0.25 Dev`


- Verified test plan from issue description

brave.crypto | test.eth | brantly.eth
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/110297957-e753c100-7feb-11eb-8567-b117e5f9f7b9.png) | ![image](https://user-images.githubusercontent.com/17010094/110298305-5fba8200-7fec-11eb-9860-546f5a2aa72f.png) | ![image](https://user-images.githubusercontent.com/17010094/110298352-6c3eda80-7fec-11eb-8e2b-636622f1eb1a.png)

Errors

![image](https://user-images.githubusercontent.com/17010094/110298607-ac05c200-7fec-11eb-8a7d-0dc566a1bf72.png) | ![image](https://user-images.githubusercontent.com/17010094/110298497-91cbe400-7fec-11eb-8e95-96cb025310f5.png) | ![image](https://user-images.githubusercontent.com/17010094/110298564-a4461d80-7fec-11eb-9494-0152c61dfb0b.png)
-- | -- | --
