### ISSUE TITLE
"Wallet Settings" and "IPFS Settings" headings/entries should just be "Wallet" and "IPFS"

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14348]
## Description 
Settings: "Wallet Settings" and "IPFS Settings" headings/entries should just be "Wallet" and "IPFS"

## Steps to Reproduce

   1.  new profile
   2.  load `brave://settings`
   3.  look at the side panel, under the Settings heading
   4.  note "Wallet Settings" and "IPFS Settings" entries

## Actual result:

<img width="1312" alt="Screen Shot 2021-02-24 at 10 58 07 AM" src="https://user-images.githubusercontent.com/387249/109051522-79c0a000-768f-11eb-9643-f5be6172a23b.png">
<img width="1312" alt="Screen Shot 2021-02-24 at 10 58 23 AM" src="https://user-images.githubusercontent.com/387249/109051535-7c22fa00-768f-11eb-8d4b-737e2a9bc222.png">
<img width="1312" alt="Screen Shot 2021-02-24 at 10 58 21 AM" src="https://user-images.githubusercontent.com/387249/109051538-7cbb9080-768f-11eb-9164-a8ee888b4591.png">

## Expected result:

According to precedent, @karenkliu and @rebron, these should just read "Wallet" and "IPFS"

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.23.2 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@bbondy Can you grab this one? Minor fix.

**Comment by stephendonner** [comment]
I know this wasn't QA/Yes, but I wanted the satisfaction of verifying my bug :-)

Verified `FIXED` using `nightly` build


Brave | 1.23.19 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

Confirmed that the settings headings for Wallet and IPFS read as `Wallet` and `IPFS`, respectively 👍 

<img width="1312" alt="Screen Shot 2021-03-04 at 4 01 25 PM" src="https://user-images.githubusercontent.com/387249/110047522-e4628300-7d02-11eb-87ff-f2ee030beb24.png">

**Comment by bbondy** [comment]
@stephendonner I actually forgot to add either label but was reminded to do so. It's added as QA/Yes now.
