### ISSUE TITLE
Greyed out “Skip Ad” in a lower right corner on YT videos

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#14359]
## Description 

There is a grayed out "Skip Ad" in a lower right corner on some cases on YT video

## Steps to Reproduce

   1. Most likely you will need to sign in to YT to replicate it
   2. Open a video link https://www.youtube.com/watch?v=xXMW9VNMPT4
   3. Make sure it plays and pick some other video from a right panel
   4. Make sure second video plays, click Back arrow on a browser panel to come back to the first video

## Actual result:

There is a grayed out "Skip Ad" in a lower right corner
![Screenshot from 2021-02-23 18-01-10](https://user-images.githubusercontent.com/12011303/109105316-af02d780-76fb-11eb-969d-bee42451ef6b.png)

## Expected result:
There is no a grayed out "Skip Ad"

## Reproduces how often: 

Easily

## Desktop Brave version:

1.21.x and above

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `FIXED` using the inline steps to reproduce, with the following build:

Brave | 1.21.69 Chromium: 89.0.4389.69 (Official Build) (x86_64)
-- | --
Revision | 6df9174a477a0bea2118cb4669954d517be16104-refs/branch-heads/4389@{#1332}
OS | macOS Version 11.2.2 (Build 20D80)

1. Signed in to non-Premium YouTube account
2. Opened https://www.youtube.com/watch?v=xXMW9VNMPT4
3. Made sure it plays and picked another video from the right panel
4. Made sure second video played, clicked Back arrow on a browser panel to come back to the first video

Verified I didn't get any ad overlay/skip button

![youtube-release](https://user-images.githubusercontent.com/387249/109330104-2c1f7100-7810-11eb-8dfd-55f3c9b7ec23.gif)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.70 x64 build
- Verified no greyed out "Skip Ad" shown on back navigation to a video
- Verified no ad shown with/without signing into Account
- Verified no ads shown on random videos loaded 
-----------
Verification passed on Samsung Tab A with Android 10 running 1.21.70 x64 build
- Verified no greyed out "Skip Ad" shown on back navigation to a video
- Verified no ad shown with/without signing into Account
- Verified no ads shown on random videos loaded
