### ISSUE TITLE
Garbage collection error: Unexpected data after root element - follow up to #13554

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14355]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/13554.

Performing a garbage-collection sweep via the button on `brave://ipfs` throws `"Garbage collection error: Line: 2, column: 1, Unexpected data after root element."`

## Steps to Reproduce

   1.  new profile, launch Brave nightly
   2.  load `brave://ipfs`
   3.  click `Install and start`
   4.  wait for the daemon/node to start
   5.  now click `Perform a garbage collection sweep`

## Actual result:

Throws "Garbage collection error: Line: 2, column: 1, Unexpected data after root element" error

![garbage-error](https://user-images.githubusercontent.com/387249/109093951-17d35b00-76ce-11eb-8104-a3c9593e2e8d.gif)

## Brave version (brave://version info)

Brave | 1.23.2 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

cc: @bbondy @spylogsster

**Comment by stephendonner** [comment]
@spylogsster @bbondy this error blocks the feature (and us, from testing), given https://github.com/brave/brave-browser/issues/13554, should we take a look at this soon-ish?  Thanks!

**Comment by spylogsster** [comment]
we got wrong formatted json from ipfs node like:
```
{"Key":{"/":"QmXt3rz4ykJvhJgwfNxYFVLMwAytfjmbjvPUNShaxJYPBQ"}}
{"Key":{"/":"bafkreibj4y5wretuqo5lhwxpojhorky7bcy774zpaewwxvg2xh6yhjuzqe"}}
{"Key":{"/":"Qmb1mDMEz9GTR7nMG7LUQYkZo5W8hfFJ85L1cGFhtmBe74"}}
{"Key":{"/":"QmPm9DAhdu5WM9TpjvKGDA7NPqzidWU39Zcn45YhpSqyVk"}}
{"Key":{"/":"bafkreihfciluj2fegbev7r6avpcmz65s74665gxme7x6h2sitbwcujcyy4"}}
{"Key":{"/":"QmauAa72b712PvGGBAnsYB8vhq2UHKFrqWJpDz8cfG1HZ8"}}
{"Key":{"/":"bafkreicnz3clraadqv3pw232khlwq32ae6ih5ir7b5xyvdblrxcnhxjurm"}}
{"Key":{"/":"QmSUv7Qd5x17etRS77mwKC1USTAYZ4Ch5n98J4ZY6s62gL"}}
{"Key":{"/":"bafkreibgppv54cvn4fg6yhzdqkmxtkst6nhqzvoitkdhjq4ufli6admpmq"}}
```

**Comment by LaurenWags** [comment]
@brave/legacy_qa when retesting this the steps from https://github.com/brave/brave-browser/issues/13554#issuecomment-790725164 can also be used. However, per @spylogsster in https://github.com/brave/brave-browser/issues/13554#issuecomment-794071778 we should visit additional sites to increase storage usage prior to running garbage collection.

**Comment by lidel** [comment]
One can browse `ipns://en.wikipedia-on-ipfs.org` – it has some images which will increase storage. 

@spylogsster I believe  the streaming response is valid (we use [newline-delimited JSON (NDJSON)](https://en.wikipedia.org/wiki/JSON_streaming#Line-delimited_JSON_2) notation), it is our docs at https://docs.ipfs.io/reference/http/api/#api-v0-repo-gc  that need to be improved to indicate streaming response is the default:
- `quiet` is opt-in (disabled by default) so we stream line for each GC'd CID  (this is why NDJSON is the default)
- `stream-errors` is opt-in (disabled by default), so there is no `Error`

I think you may want to enable `stream-errors`  and if you don't want to deal with NDJSON flip `quiet` too.

**Comment by spylogsster** [comment]
as discussed with @lidel the response code is enough for us and we should not alert about json parsing errors, added PR about it

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.23.33 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)

Steps to verify:
1. Clean profile with `1.23.33`
2. Visit an `ipfs://` URL such as `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
3. Click around a bunch on `ipns://en.wikipedia-on-ipfs.org/wiki/` - I garnered over 2000 objects
4. Open a new tab and visit `brave://ipfs` - see info in Repo Stats populated

Verified:
* Upon clicking `Perform a garbage collection` that the # of objects went down to `13`, and Size went to `558129`, from originally `Objects: 2048` and `Size: 24673336`
* There were no garbage-collection error messages

| Before garbage collection | After garbage collection |
|---------------------------|-------------------------|
<img width="657" alt="Screen Shot 2021-03-11 at 5 41 39 PM" src="https://user-images.githubusercontent.com/387249/110879540-06737c80-8292-11eb-94c7-da667f0dfee7.png"> | <img width="657" alt="Screen Shot 2021-03-11 at 5 42 17 PM" src="https://user-images.githubusercontent.com/387249/110879544-07a4a980-8292-11eb-8268-1ecd3700c953.png">

![garbage-collection](https://user-images.githubusercontent.com/387249/110879763-60744200-8292-11eb-919a-57e009c9c47e.gif)
