### ISSUE TITLE
Tweet ID Number Used in Suggested Tweet Text

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#14358]
This happened to me just now in v1.21.65 (presently Brave Beta):

> ![image](https://user-images.githubusercontent.com/815158/109101269-0a2cce00-76ec-11eb-8cb4-87daa0763ecf.png)

From https://twitter.com/kentcdodds/status/1364736650555756544, I scrolled down to the following and clicked _Tip_:

> ![image](https://user-images.githubusercontent.com/815158/109101409-3fd1b700-76ec-11eb-835b-c50dc017da1e.png)

The tipping banner did not show any issue with displaying the publisher's username:

> ![image](https://user-images.githubusercontent.com/815158/109101464-5d068580-76ec-11eb-8752-fa0f45c489ab.png)

_Originally posted by @jonathansampson in https://github.com/brave/brave-browser/issues/8265#issuecomment-785569253_

**Comment by LaurenWags** [comment]
@jonathansampson what is the `Brave Local Data Updater` component version? cc @emerick @zenparsing

**Comment by emerick** [comment]
At a quick glance, I think we're falling into the second condition in this block from https://github.com/brave/brave-core/blob/f7ee3e162129586597571a7661d95e2664c462ac/components/brave_rewards/resources/tip/lib/host.ts#L261-L266

```
if (dialogArgs.mediaMetaData.mediaType === 'twitter') {
  name = '@' + dialogArgs.mediaMetaData.publisherName
  postId = dialogArgs.mediaMetaData.postId
} else if (publisherInfo.provider === 'twitter' && dialogArgs.url) {
  name = '@' + dialogArgs.url.replace(/^.*\//, '')
}
```

Will need a little more investigation to figure out exactly why that's happening.

**Comment by jonathansampson** [comment]
@LaurenWags Sorry for not seeing your question sooner; currently my component is at 1.0.42.

**Comment by jonathansampson** [comment]
Still appears to be an issue. Encountered it today, repeatedly in version 1.34.80.

Steps:

1. Visit https://twitter.com/elguilhermee/status/1480608161702817793
2. Begin tipping process via ⟁ icon to the right of the address bar.
 a. If the rewards panel hasn't yet loaded the publisher name (showing twitter.com instead), try again in a few seconds.
3. Click _Send Tip_
4. Select amount
5. Click _Send Tip_
6. Click _Tweet about your support_

![image](https://user-images.githubusercontent.com/815158/148828011-bfc7c831-3d82-4b69-bf9b-5c5494208656.png)

![image](https://user-images.githubusercontent.com/815158/148828098-d88e8d15-8e76-4ede-817e-b25ec91ed214.png)

![image](https://user-images.githubusercontent.com/815158/148828170-c408d473-8f27-4684-9370-a13e9a30a06f.png)

![image](https://user-images.githubusercontent.com/815158/148827270-48e5c5ae-18c1-4c0c-bfb6-e4f4bab641b6.png)

**Comment by jonathansampson** [comment]
Still seeing the following error in my console too:

```
twitterBase.bundle.js:1 Failed to fetch user details for elguilhermee: Missing auth headers
```

Related:

- https://github.com/brave/brave-browser/issues/12744
- https://github.com/brave/brave-browser/issues/14342

**Comment by jonathansampson** [comment]
No repro for me either. Closing.
