### ISSUE TITLE
Brave can not import bookmarks in Edge, though promoting success

### ISSUE THREAD

**Issue by LayneInNL** [brave/brave-browser#14352]
## Description 

I use "import bookmarks now" to import my bookmarks in Edge. Though promoting success, I can not see any imported bookmarks. 

## Steps to Reproduce

   1. Click "Import bookmarks and settings" in settings
   2. Choose "Microsoft Edge"
   3. Check "Favourites/Bookmarks"
   4. Click "Import"

## Actual result:

No bookmark is imported, Though I have a number of bookmarks in Edge.
![image](https://user-images.githubusercontent.com/46805380/109066945-203b8e00-76ee-11eb-99e8-68b453c72da8.png)

## Expected result:

Bookmarks is imported.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
-- | --
Revision | 31b458a18f133db9203eb5a5dd6552de0716dda3-refs/branch-heads/4324_182@{#6}
OS | Windows 10 OS Version 1909 (Build 18363.1379)

## Miscellaneous Information:

Edge Version: Version 88.0.705.74 (Official build) (64-bit)
It does work with exported file from Edge.

**Comment by bsclifton** [comment]
This should be fixed now - the Edge version showing in the importer was the OLD Edge ("Spartan").  We added Chromium Edge with https://github.com/brave/brave-browser/issues/13334
