### ISSUE TITLE
Shields not functional on private window until focus is changed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1437]
## Description 

Shields not functional on private window until focus is changed

## Steps to Reproduce

   1. Install/upgrade 0.55.11
   2. Open a private tab and load a page
   3. Click shields button, doesn't work 
   4. Switch focus to normal tab/other app and switch back to Private window, shields get enabled

## Actual result:

https://youtu.be/FR0FaHis_7M

## Expected result:
Shields should always work on Private window

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes issue on Dev/Beta
- Does it reproduce on browser-laptop? N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
I'll take a look this issue next week. I recently worked on similar area.

**Comment by bbondy** [comment]
Noticed this in the chrome extension API docs:
```
onStartup
Fired when a profile that has this extension installed first starts up. This event is not fired when an incognito profile is started, even if this extension is operating in 'split' incognito mode.
```

**Comment by bbondy** [comment]
I don't think you can create a second window within the same incognito profile, so that is the exact event we need to fire for us in incognito. Or find another way.  But at least that explains it.

**Comment by bbondy** [comment]
chrome.windows.onCreated doesn't get called for the first window

**Comment by bbondy** [comment]
Upstream issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=258036

**Comment by bbondy** [comment]
I think a hack that would work is to have an interval that checks for new windows that it doesn't know about.
