### ISSUE TITLE
Google Search Quick Info gets blocked by Share Buttons

### ISSUE THREAD

**Issue by MySurmise** [brave/brave-browser#14374]
## Steps to Reproduce

   1. Search any big Name or Company...
   2. look on the right
   3. be annoyed and go on Wikipedia because the Google Info and Pictures can't load and get blocked by Social Network Buttons

## Actual result:

![image](https://user-images.githubusercontent.com/70728036/109249301-bc958b80-77e7-11eb-9f0e-f4e45693ce6e.png)

I can't see anything

## Expected result:

I should see Google Quick Info Page

## Reproduces how often: 

Every time I use the Google Search for similar Search requests

## Brave version (brave://version info)

Brave | 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
-- | --
Revision | 31b458a18f133db9203eb5a5dd6552de0716dda3-refs/branch-heads/4324_182@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.804)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@MySurmise Do you have another extension enabled that might be blocking those results? 

Default settings for Brave show the result below but even changing to aggressive mode or turning on the social network settings (shouldn't effect the results) shows the below results.

![Screen Shot 2021-03-01 at 9 44 43 AM](https://user-images.githubusercontent.com/5951041/109536604-c848b280-7a72-11eb-82cd-16cf3224935d.png)

**Comment by MySurmise** [comment]
Strangely it works now for 3 days in a row without doing anything. Closing.
