### ISSUE TITLE
Missing translations for Sync informer

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14376]
## Description 
Missing translations for Sync informer

## Steps to reproduce 

   1. Set locale to Japanese
   2. Follow steps from https://github.com/brave/brave-core/pull/731
   3. Sync informer message isn't translated

## Actual result 

![image](https://user-images.githubusercontent.com/17010094/109264012-2ddf3980-77fc-11eb-87be-795b5ccb4b9d.png) | ![image](https://user-images.githubusercontent.com/17010094/109264025-32a3ed80-77fc-11eb-9c46-573672d01a40.png)
-- | --

## Expected result
All translated text

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.23.7

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
@srirambv closing this off as https://github.com/brave/brave-core/pull/8093 landed in `1.21.x` via https://github.com/brave/brave-core/pull/8097. If it's still an issue, just re-open and move it out of the milestone. We can decide if it's a blocker at that point.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.71 x64 build
- Verified sync informer modal text is translated
- **Japan**

Tab message | Sync settings
-- | --
![image](https://user-images.githubusercontent.com/17010094/109615441-d1498a80-7b2b-11eb-9ee7-3a999451d744.png) | ![image](https://user-images.githubusercontent.com/17010094/109615471-d8709880-7b2b-11eb-987b-cee212461d56.png)

- **Russian**

Tab message | Sync settings
-- | --
![image](https://user-images.githubusercontent.com/17010094/109615570-f8a05780-7b2b-11eb-8fcf-91f629401988.png) | ![image](https://user-images.githubusercontent.com/17010094/109615581-fccc7500-7b2b-11eb-917d-556b7c30ffb7.png)

-------
Verification passed on Samsung Tab A with Android 10 running 1.21.71 x64 build
- Verified sync informer modal text is translated
- **French**

Tab message | Sync settings
-- | --
![image](https://user-images.githubusercontent.com/17010094/109615595-02c25600-7b2c-11eb-9051-d2c340051bad.png) | ![image](https://user-images.githubusercontent.com/17010094/109615610-06ee7380-7b2c-11eb-928d-4529e52cf81c.png)

- **German**

Tab message | Sync settings
-- | --
![image](https://user-images.githubusercontent.com/17010094/109615625-0c4bbe00-7b2c-11eb-9ca7-d34ef9d2a0ce.png) | ![image](https://user-images.githubusercontent.com/17010094/109615635-0f46ae80-7b2c-11eb-8f3a-d0b919d39506.png)
