### ISSUE TITLE
Can't run Release version of Brave on MacOS

### ISSUE THREAD

**Issue by rainiera** [brave/brave-browser#14388]
## Steps to Reproduce

1. Clone and initialize repo per README: `npm install`, `npm run init`
2. set `brave_sync_endpoint` and `brave_stats_updater_url` variables to fake URLs in `.npmrc` (as recommended [here](https://github.com/brave/brave-browser/issues/13750))
3. `npm run build Release`
4. `./src/out/Component/Brave\ Browser\ Development.app/Contents/MacOS/Brave\ Browser\ Development`

## Actual result:

`[1]    <pid> trace trap`

## Expected result:

fast, fully-linked Brave build (default component build runs fine, but more slowly)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

"version": "1.23.8"

## Miscellaneous Information:

- Using `MacOSX11.3.sdk`, macOS Big Sur (11.1)

**Comment by rainiera** [comment]
I used `lldb` to narrow down the issue to an assertion that `kVariationsServerURL` exists (found [here](https://github.com/brave/brave-core/blob/fb0120a221b60a3819f404a632d2584bcc03c2bd/app/brave_main_delegate.cc#L197)). Further validated by some extra steps done in the arch linux build of brave: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brave#n229

So the resolution is just to also define `brave_variations_server_url` in your `.npmrc`.

**Comment by bsclifton** [comment]
Will be fixed with https://github.com/brave/brave-core/pull/7468
