### ISSUE TITLE
Start to add a swap UI to Crypto Wallets extension

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14383]
This issue is to add a new option named "Swap" next to our existing 2 options for Buy and Send
<img width="358" alt="Screen Shot 2021-02-26 at 12 19 18 PM" src="https://user-images.githubusercontent.com/831718/109332982-dc9b6e00-782c-11eb-80ab-bc89420eebe1.png">

When the user clicks it, it should go to a new view, that shows 2 drop downs:

From:
[text box][drop down]

To:
[drop down]

[ Swap ]

The drop downs will be filled with the different assets available to swap.
You can hard code both drop downs with a list of 20 or so assets, both drop downs containing the same.

# Getting setup and technical information:

- You do not need to build Brave for this task.
- You will need to `git clone` this repo https://github.com/brave/ethereum-remote-client/
- You will need to use node v10, you can install `nvm` to make it easy to switch between node versions
- You will need to install `yarn` package manager which works like `npm`
- After you clone `ethereum-remote-client` to build you need to run `yarn install` and `yarn run dev:brave`. The second command will hang forever and wait for changes. It does this so it can live reload the extension when in development for certain types of changes.  
- You will use a fresh profile of Brave and go to about://extensions and turn on "Developer mode" checkbox on the top right. 
- You will "Load unpacked" from chrome://extensions and select the dev extension you built which will be in the `ethereum-remote-client` dist/brave folder.
- You will need to command+c or ctrl+c in the terminal that had `yarn run dev:brave` as you make changes and restart that command. Not all types of changes live reload.

**Comment by jasonrsadler** [comment]
@bbondy I'd like to put in a PR for this but the issue as written reads like a challenge. Is this something that you plan to merge or is this for other purposes?

**Comment by bbondy** [comment]
Closing this since it was a hack day project for a candidate. We'll post a new issue to track swaps soon.
