### ISSUE TITLE
Shields tooltip shows when shields is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14380]
## Description 
Shields tooltip shows when shields is disabled

## Steps to reproduce 

   1. Visit a page and disable shields
   2. Visit a new page on the same tab
   3. Before the second site loads navigate back to site from step 1
   4. Shields tooltip shows on the first site even when site is disabled

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/109311079-3c9a1080-783d-11eb-917f-38c113736d8b.png)

## Expected result
No tooltip if site is disabled

## Issue reproduces how often 
Easy only if you are quick in navigating back 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Maybe
- Can you reproduce this issue with the current Play Store Beta version? Maybe
- Can you reproduce this issue with the current Play Store Nightly version? Maybe

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.21.69

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya

**Comment by anthonypkeane** [comment]
Can you please recheck @srirambv? Thanks

**Comment by srirambv** [comment]
Haven't seen this issue in a long time. Closing as stale
