### ISSUE TITLE
make it more clear in new tab text that Brave with Tor != Tor Browser

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#14385]
There seems to be a common misconception that Brave's windows with Tor connectivity are supposed to be equivalent to Tor Browser, when in reality the threat model is pretty different. We launched the feature as a way for users to circumvent censorship and hide their true IP from websites and non-determined network observers, not nation-state attackers. 

We state clearly in https://support.brave.com/hc/en-us/articles/360018121491 (linked from the new tab page) that "If your personal safety depends on remaining anonymous, we highly recommend using Tor Browser instead of Brave Tor windows." However this information should not require an extra link click to find out, given that many people think that "browser window with a Tor proxy" is synonymous with "Tor browser". 

Suggestion:

Heading: "Private Window with Tor Connectivity"
Text below heading: `Brave never remembers what you do in a Private Window, but regular Private Windows do not hide your IP address. With Tor connectivity, your IP address is hidden from the sites you visit. However, if your personal safety depends on remaining anonymous, we recommend using Tor Browser instead.`

Lower heading: "This Private Window is more private with Tor Connectivity" /  "Make this Private Window more private with Tor Connectivity" 
Text below heading: `Using Private Windows only changes what Brave does on your device — it doesn't change anyone else's behavior. Tor hides your IP address from the sites you visit and makes it somewhat more difficult, but not impossible,  for your ISP or employer to see what sites you are visiting. Open a Private Window with Tor from the menu, or with ⌥⌘N.`

**Comment by diracdeltas** [comment]
@karenkliu any suggestions to my text? i think we should do this pretty quick given that there's no easy fix for #14262 without waiting on chromium.

**Comment by BrendanEich** [comment]
Suggest "somewhat" over "slightly", but it's all a matter of cost. I think "somewhat" is more neutral. Thanks.

**Comment by diracdeltas** [comment]
thanks, text updated!

**Comment by karenkliu** [comment]
@BrendanEich @diracdeltas Here's what this text might look like with our current Private Window with Tor design: 
![image](https://user-images.githubusercontent.com/2388823/109353015-a2cc6680-7830-11eb-9068-cf2a6a577712.png)

I took the liberty of culling a tiny bit of the text to fit in the space. LMK what you think.

Also, eventually we do want to refresh the design for Private Window/Private Window with maybe more search bar prominence, less text, and greater perceived clarity of what the two types of window hide/doesn't hide. This is what that might look like with this text update:
![image](https://user-images.githubusercontent.com/2388823/109353499-50d81080-7831-11eb-9868-b8caa5887941.png)
^^^ This future design is still in concept phase and needs more feedback. Just putting it here to give you a heads up.

**Comment by diracdeltas** [comment]
@karenkliu thanks, this looks good to me

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.22.55 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 10.15.7 (Build 19H524)
```

Verified text from https://github.com/brave/brave-core/pull/8091#pullrequestreview-601054582 and https://github.com/brave/brave-core/pull/8091#issuecomment-792991588.

**`Private Window`**

1.21.74 | 1.22.55
----- | -----
<img width="1312" alt="1 21 74 Private" src="https://user-images.githubusercontent.com/28145373/110484452-aa093500-80b8-11eb-85fb-d90e7cefe566.png"> | <img width="1290" alt="1 22 x Private" src="https://user-images.githubusercontent.com/28145373/110484463-abd2f880-80b8-11eb-97b9-f670489503f0.png">

Also confirmed the "Learn more" link at the top of the page and the "Learn more about Tor in Brave" buttons navigated to support.brave.com pages with additional information. 

**`Tor Window`**

1.21.74 | 1.22.55
----- | -----
<img width="1314" alt="1 21 74 Tor" src="https://user-images.githubusercontent.com/28145373/110484485-afff1600-80b8-11eb-8503-27fd9306b0ed.png"> | <img width="1301" alt="1 22 x Tor" src="https://user-images.githubusercontent.com/28145373/110484489-b1304300-80b8-11eb-9660-4ec9730c0918.png">

Also confirmed the "Learn more" link at the top of the page and the "Learn more about Tor in Brave" buttons navigated to support.brave.com pages with additional information. 

**`Guest Window`**

1.21.74 | 1.22.55
----- | -----
<img width="1257" alt="1 21 74 Guest" src="https://user-images.githubusercontent.com/28145373/110484502-b4c3ca00-80b8-11eb-8290-794a0032d557.png"> | <img width="1197" alt="1 22 x Guest" src="https://user-images.githubusercontent.com/28145373/110484506-b5f4f700-80b8-11eb-9e46-3b1ba1079b19.png">

Also confirmed the "Learn more" link at the top of the page and the "Learn more about Tor in Brave" buttons navigated to support.brave.com pages with additional information.
