### ISSUE TITLE
Raw RSS feed from promoted content linked to in Rewards' 7-day Ads History

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14384]
## Description 

Raw RSS feed linked to in Rewards' 7-day Ads History for Brave Today promoted-content ads

## Steps to Reproduce

   1. new profile, launch Brave
   2. click the BAT icon, click Start using Rewards
   3. open a new-tab page
   4. scroll down to a promoted-content ad, click on it
   5. open `brave://rewards`
   6. click on 7-day Ads History
   7. click on the ad's entry (https://www.etoro.com/news-and-analysis/crypto/feed/ in my case)

## Actual result:
The user sees the raw, unstyled RSS feed

<img width="885" alt="Screen Shot 2021-02-26 at 10 12 00 AM" src="https://user-images.githubusercontent.com/387249/109338424-1c595a00-781b-11eb-9fe5-20b719c96452.png">

<img width="885" alt="Screen Shot 2021-02-26 at 10 10 38 AM" src="https://user-images.githubusercontent.com/387249/109338304-ee741580-781a-11eb-826c-e807901c14b6.png">

## Expected result:
If possible, pretty-printed RSS feed is presented to the user

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.21.69 Chromium: 89.0.4389.69 (Official Build) (x86_64)
-- | --
Revision | 6df9174a477a0bea2118cb4669954d517be16104-refs/branch-heads/4389@{#1332}
OS | macOS Version 11.2.2 (Build 20D80)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
If we address this by pointing to the canonical domain, let's be sure to also test/verify that we figure out sources like Gala Games, which are hosted on third-party platforms like medium.com - https://medium.com/feed/@gogalagames as a feed example for that.

**Comment by tmancey** [comment]
Closing issue as an admin should set the target URL to the required domain within the brave ads admin area.
