### ISSUE TITLE
Sync payment methods/autofill

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#14391]
## Description 
Is there any plan in the future to synchronise payment methods?

I miss also integration of Google Pay in the Brave Browser.

**Comment by AlexeyBarabash** [comment]
Right now if you are logged in into your Google account in either desktop or Android Brave Browser, you can use Google Pay. 

Sync does synchronization of credit cards if the option `Addresses and more`/`Addresses, payment info, etc.` is chosen.

So I close this issue.
