### ISSUE TITLE
"Open in Tor" doesn't work on Linux if a Tor window is already open (affects stable and beta, but not nightly)

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#14395]
## Description 

The "Open in Tor" button doesn't open a new tab in an existing Tor window when clicked.
If there is no existing Tor window, one will be opened successfully, as expected.
While reporting this, I realized it's fixed in nightly, but figured maybe it would still be useful to report.
Feel free to close right away.

## Steps to Reproduce

   1. Execute: brave --user-data-dir="$(mktemp -d)" brave5t5rjjg3s6k.onion
   2. The page says:
 
brave5t5rjjg3s6k.onion is blocked
Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

   3. (Is the message above expected? It seems like it could be improved)
   4. Open a Tor window
   5. Click "Open in Tor" in the regular window
   6. Nothing happens (although i3 indicates that there's activity in the Tor window, but there's no apparent visual change

## Actual result:

A tab in the Tor window is not opened.

## Expected result:
A new tab in the Tor window.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
-- | --
Revision | 31b458a18f133db9203eb5a5dd6552de0716dda3-refs/branch-heads/4324_182@{#6}
OS | Linux
JavaScript | V8 8.8.278.17
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --user-data-dir=/tmp/tmp.tHNFXfPw5c --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,SafetyTip,AutoupgradeMixedContent,LegacyTLSEnforced,DnsOverHttps,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=AutofillEnableAccountWalletStorage,AutofillServerCommunication,DirectSockets,TextFragmentAnchor,IdleDetection,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,TabHoverCards,PasswordCheck,LangClientHintHeader,NetworkTimeServiceQuerying,SafeBrowsingEnhancedProtection,SignedExchangeSubresourcePrefetch,PrivacySettingsRedesign,NotificationTriggers,WebOTP --flag-switches-begin --flag-switches-end brave5t5rjjg3s6k.onion
Executable Path | /usr/lib/brave-bin/brave
Profile Path | /tmp/tmp.tHNFXfPw5c/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the nightly channel? 
No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

## Miscellaneous Information:

```console
% pacman -Q brave-bin
brave-bin 1:1.20.110-1
% brave --version
Brave Browser 88.1.20.110 
% pacman -Q brave-beta-bin
brave-beta-bin 1.22.47-1
% brave-beta --version
Brave Browser 89.1.22.47 beta
% pacman -Q brave-nightly-bin
brave-nightly-bin 1.23.8-1
% brave-nightly --version
Brave Browser 89.1.23.8 nightly
%
```

**Comment by wknapik** [comment]
Also, if I go to brave.com in a regular window, then open a Tor window and then click "Open in Tor" in the regular window, a new tab is opened in the regular window, with the onion address in the address bar and the ERR_BLOCKED_BY_CLIENT message (the Tor window is unaffected).

This also appears to be fixed in nightly.

**Comment by darkdh** [comment]
Yes, it’s a dupe
