### ISSUE TITLE
Be able to receive BAT grants in Crypto wallet

### ISSUE THREAD

**Issue by sramek5** [brave/brave-browser#14390]
## Description 
I do not understand why user need validate Crypto wallet for his BAT with Uphold.
There would be much better option to use simply native Brave Crypto Wallet (in browser?).

## Tips for Feature:
   1. Getting our BAT right to Brave Crypto Wallet.
   2. Synchronise Brave Crypto Wallet through all synchronised devices (mobiles/tablets included).
   3. Add possibility to use security key for 2-Step Verification of Brave Crypto Wallet (that would work only in PC, unfortunately not on mobile - related to #7756)
   
Thanks for consideration.

**Comment by bsclifton** [comment]
I believe all the funds need to go through a licensed custodian unfortunately (for legal reasons)
cc: @bbondy for comment

**Comment by bbondy** [comment]
We're looking to add peer to peer tipping which would allow tipping from brave://wallet directly to any other address that a publisher configures.

For things paid for rewards though, it needs to go through a licensed custodian like Clifton said.

**Comment by namelessperson0** [comment]
> I believe all the funds need to go through a licensed custodian unfortunately (for legal reasons)
> cc: @bbondy for comment

Could https://www.proofofhumanity.id be sufficient for kyc?

**Comment by bbondy** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/15253
