### ISSUE TITLE
brave closes its self when ever i open it and unistalling and reinstalling dosent work

### ISSUE THREAD

**Issue by bruh12333** [brave/brave-browser#14394]
## Description 
when ever I try to open brave it will always close its self immediately as soon as I open it and I have tried thing that other people have use and they don't work 

## Steps to Reproduce
   1. open brave
   2. it closes
   3. tries to unistall then reinstall
   4. does it all over agian

## Reproduces how often: 
every time i open the brave browser

## Brave version (brave://version info)
latest version, windows 10, x64

## Version/Channel Information:
- Can you reproduce this issue with the current release? 
- yes
- Can you reproduce this issue with the beta channel? 
- havent tried
- Can you reproduce this issue with the nightly channel? 
- havent tried

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? 
- not able to get to it in time when it opens cause it closes so fast
- Does the issue resolve itself when disabling Brave Rewards? 
- not able to get to it in time when it opens cause it closes so fast
- Is the issue reproducible on the latest version of Chrome? 
- no

**Comment by bsclifton** [comment]
Hi @bruh12333 - have you tried starting from command line? Do you have any other information (anything show in Event Viewer)? Are you running anti-virus software? What do you mean by "I have tried thing that other people have use and they don't work"

**Comment by rebron** [comment]
cc: @Brave-Matt Can you help with this one? We need some more info here.

**Comment by Brave-Matt** [comment]
@bruh12333,
Can you please go to the following link and fill out the request form with as much information as possible and I will personally assist you from there? Please include your Github username in the subject line of the request so I know that it is you.
https://support.brave.com/hc/en-us/requests/new

Thank you.

**Comment by rebron** [comment]
Wondering if this is related: #10501

**Comment by iefremov** [comment]
@rebron there are few different startup crashes that may be related.

**Comment by dekay7** [comment]
### Issue: 
For me, there are times after quitting Brave and reopening it, it just closes itself. I try to open it again and it quits again and it does not stop. I ensure that all Brave tasks are stopped and closed in the Activity Monitor, then try again, yet to no avail. The only fix that I have is completely restarting my machine. 

**Platform:** macOS
### Temporary Solution: 
Restarting the device.

**Comment by iefremov** [comment]
@dekay7 thanks for the report! do you have anything on `brave://crashes` ?

**Comment by dekay7** [comment]
Crash ID: 642a0000-bef0-f505-0000-000000000000

**Comment by iefremov** [comment]
@dekay7 many thanks for the report, this is https://github.com/brave/brave-browser/issues/14407, we are looking into it.
