### ISSUE TITLE
Consider allowing newer node.js engine

### ISSUE THREAD

**Issue by humphd** [brave/brave-browser#144]
I wanted to build and try brave-browser, but ran into an issue right away:

```json
  "engines": {
    "node": "^8.9.2",
    "npm": "^5.5.1"
}
```

I'm on `v9.10.1`.  So I removed the `"engines"` block from `package.json` and everything built and fine.  It's possible that it worked for me, but will break something I didn't test.  However, if not, allowing devs to use newer node would allow more people to work on this without having to tinker with their env.

**Comment by bbondy** [comment]
I'd be ok with removing this if you or someone else PRs.
