### ISSUE TITLE
Deleted publisher gets added back when the site is revisited

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1440]
## Description 

While testing #1379, found that deleted publisher gets added back when the site is revisited

## Steps to Reproduce

   1. Enable Brave Rewards on `0.55.11`
   2. Visit https://brianbondy.com for min time ensure its added to the list
   3. Visit https://clifton.io for min time ensure its added to the list as well
   4. Delete brianbondy.com from the list 
   5. Visit https://brianbondy.com/ in a new tab for the min time, gets added back to the list

## Actual result:

Deleted publisher gets added back when the site is revisited

## Expected result:
Should show the deleted list and removing it from there and visiting the site should add it back to the list

## Reproduces how often: 

Easy 

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Yes
- Does it reproduce on browser-laptop? No. B-l doesn't add back the site to list unless its removed from the deleted site list

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @LaurenWags @kjozwiak @NejcZdovc

**Comment by LaurenWags** [comment]
Reproduced on macOS with 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta(64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified STR from description
