### ISSUE TITLE
Cleanup P3A clent code / get rid of PROCHLO ?

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#14408]
Initially, the P3A system was designed to utilise PROCHLO for additional privacy, however PROCHLO backend seems abandoned and P3A flies as is. We should consider removing PROCHLO bits from the client side to drop unused legacy and craft better pings (e.g. drop ascii string -> protobuf -> base64 conversion).

**Comment by iefremov** [comment]
cc @too4words @keur @porteron

**Comment by iefremov** [comment]
looking forward for resurrecting PROCHLO, reopen if PROCHLO is not in production in 2022 :)

**Comment by stephendonner** [comment]
@iefremov / @rillian: can you help QA by providing a test plan we can run & maybe key off of?  Thanks!

**Comment by rillian** [comment]
My understanding is that this is just changing internal code paths for P3A message generation, so observable behaviour should be the same, or at least similar. Helpful QA might be:

- Verify (e.g. with a network monitor) that the same P3A message contents are sent for a particular profile.
- Verify that metadata tags are still stripped appropriately: On linux the browser should not report a referral code, a browser installed in a minority locale (Singapore? Nigeria? New Zealand?) should not report a region, and so on.

**Comment by LaurenWags** [comment]
Labelling `QA/Blocked` until discussion in https://bravesoftware.slack.com/archives/CDNJ9SVUL/p1637170701059200 is resolved

**Comment by rillian** [comment]
Unblocking and setting `QA/No` based on discussions. It would be helpful to have some spot testing of what the browser is sending, but data coming into the backend looks similar, so I think we can defer QA until #15967 is complete.

**Comment by LaurenWags** [comment]
Sounds good @rillian - will proceed with this unless we hear differently from @iefremov 👍🏻

**Comment by GeetaSarvadnya** [comment]
Performed a spot check on the client-side and ensured things are working as expected and nothing is regressed.
