### ISSUE TITLE
Side bar keeps showing up even when video enters full screen mode  

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14402]
## Description 

Side bar keeps showing up even when video enters full screen mode  

## Steps to Reproduce

   1. Enable sidebar flag from `brave:flags`
   2. Set side bar to show always
   3. Open a video link and enter full screen
   4. Side bar keeps showing on full screen video 

## Actual result:

Side bar shows on full screen videos

## Expected result:
`Always show` side bar should only be on browser normal view. If you enter a video to fullscreen should hide sidebar and not distract video viewing

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.23.5 Chromium: 89.0.4389.58 (Official Build) nightly (64-bit)
-- | --
Revision | `1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @karenkliu

**Comment by stephendonner** [comment]
Verified `FIXED` using the inline steps to reproduce, on `nightly` build 

Brave | 1.25.11 Chromium: 90.0.4430.61 (Official Build) nightly (x86_64)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | macOS Version 11.2.3 (Build 20D91)


Steps
1. enabled sidebar flag from `brave:flags`
2. set side bar to `show always`
3. opened a video link from hbomax.com and clicked `View` | `Enter Full Screen`
4. maximized video via the HBO Max on-screen controls

Confirmed there's no sidebar present after entering full-screen mode


video with sidebar | full-screen mode, no sidebar 
|------------------|------------------------------
<img width="945" alt="Screen Shot 2021-04-12 at 4 15 44 PM" src="https://user-images.githubusercontent.com/387249/114474372-f01b5200-9baa-11eb-862b-e3c84024b617.png"> | ![Screen Shot 2021-04-12 at 4 16 07 PM](https://user-images.githubusercontent.com/387249/114474371-ef82bb80-9baa-11eb-8d71-5b55790d9ad1.png)
