### ISSUE TITLE
Follow up of #14359 - Greyed out “Skip Ad” in a lower right corner on YT videos

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14403]
## Description 

There is a grayed out "Skip Ad" in a lower right corner on some cases on YT video

## Steps to Reproduce

   1. Clean profile 1.21.70
   2. Follow STR from #14359
   
## Actual result:

There is a grayed out "Skip Ad" in a lower right corner when the back button is clicked on the 2nd video
![image](https://user-images.githubusercontent.com/38657976/109475457-bf200b80-7a9b-11eb-9a70-78a512150428.png)

## Expected result:
There is no a grayed out "Skip Ad"

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.21.70 Chromium: 89.0.4389.69 (Official Build) (64-bit)
-- | --
Revision | 6df9174a477a0bea2118cb4669954d517be16104-refs/branch-heads/4389@{#1332}
OS | Windows 10 OS Version 2004 (Build 19041.804)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @SergeyZhukovsky @rebron 

I can reproduce the issue consistently on windows. This could be windows specific issue as I see it's working for @srirambv and @StephenBass on Android and macOS platforms.

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on `1.20.110` also

![image](https://user-images.githubusercontent.com/38657976/109509125-94977800-7ac6-11eb-804d-27bb1e3c117f.png)

**Comment by SergeyZhukovsky** [comment]
I was able to replicate only a first time on Windows. After that I tried bunch of times and no luck. I think it's a general problem in blocking in our old and new implementation. As I see it on `1.20.x` sometimes as well which uses extension for that. I would propose to observe what people have and jump on it right away if we see significant number of reports. Upstream ublock also receive reports from people from time to time
![Screenshot from 2021-02-25 22-24-48](https://user-images.githubusercontent.com/12011303/109510801-6d15c080-7a70-11eb-91d4-3e923f330239.png)

**Comment by rebron** [comment]
cc: @ryanbr and @antonok-edm

**Comment by ryanbr** [comment]
Just as a follow up to the comment above, it was more of a guess by gwarser.

> And these "prefetch" filters - I was just guessing - they will break YT dynamic player loading and force whole page to be reloaded every time user click on video thumbnail.

**Comment by ryanbr** [comment]
Many changes to YT since this was lodged. Its safe to close.
