### ISSUE TITLE
Changing profile image to first image crashes Brave

### ISSUE THREAD

**Issue by JasonTheAdams** [brave/brave-browser#14411]
## Description 
I have two profiles and I wanted to change the original profile's image. But I found, quite consistently, that selecting the first image crashes Brave. Selecting any other image than the first works fine.

## Steps to Reproduce

   1. Click Profiles > Edit...
   2. Select the first profile image
   3. Crash

## Actual result:

![bug in action](https://p179.p0.n0.cdn.getcloudapp.com/items/04uJvwPm/ec110956-df05-4161-ac56-55b650da3291.gif?v=6d0afd4aabc349e970c591162cd1fda3)

## Expected result:
It should just select the image without issues.

## Reproduces how often: 
This crashes every time. It's completely consistent for me.

## Brave version (brave://version info)
Brave | 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64)
-- | --
Revision | 31b458a18f133db9203eb5a5dd6552de0716dda3-refs/branch-heads/4324_182@{#6}
OS | macOS Version 11.2 (Build 20D64)
JavaScript | V8 8.8.278.17
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,SafetyTip,AutoupgradeMixedContent,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,PrefetchPrivacyChanges --disable-features=AutofillEnableAccountWalletStorage,TabHoverCards,IdleDetection,DirectSockets,AutofillServerCommunication,LangClientHintHeader,NetworkTimeServiceQuerying,PasswordCheck,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,WebOTP,NotificationTriggers,TextFragmentAnchor,SafeBrowsingEnhancedProtection,SignedExchangeSubresourcePrefetch,PrivacySettingsRedesign --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/jasonadams/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Have not tested
- Can you reproduce this issue with the nightly channel? Have not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
I was able to confirm this crash. Selecting a profile image for profile 1 that's the not first one and then selecting the first one again repros the crash. After the crash, the first profile image is kept.

cc: @simonhong 

Brave | 1.20.110 Chromium: 88.0.4324.192 (Official Build) (arm64)
-- | --
Revision | 31b458a18f133db9203eb5a5dd6552de0716dda3-refs/branch-heads/4324_182@{#6}
OS | macOS Version 11.2.2 (Build 20D80)

**Comment by iefremov** [comment]
@rebron should be fixed here https://github.com/brave/brave-browser/issues/13762, can you re-check?

**Comment by iefremov** [comment]
@JasonTheAdams it should be fixed now
