### ISSUE TITLE
Set "rewards enabled" pref when the user opts-in to Rewards

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#14414]
We currently do not set the "brave.rewards.enabled" pref when the user opts-in to Rewards. Instead, we set more granular flags and rely on those values. For future flexibility, we should go back to using this flag to record the opt-in state of the user.

**Comment by stephendonner** [comment]
Thanks for filing, @zenparsing; is this partly what's going on in https://github.com/brave/brave-browser/issues/14413?
