### ISSUE TITLE
"Include in Auto-Contribute" pref not working for Greaselion-enabled publishers

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14413]
## Description 
"Include in Auto-Contribute" pref auto-toggles to OFF after first flipping OFF to ON, then dismissing panel.

## Steps to Reproduce

   1. new profile, launch Brave with `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5`
   2. click "Skip welcome tour"
   3. click "Start using Rewards"
   4. click "Claim my Rewards"
   5. pass the reCaptcha challenge
   6. load `https://twitter.com/bravelaurenwags`
   7. click on the BAT icon in the URL bar
   8. notice that "Include in Auto-Contribute" is toggled **ON**
   9. toggle it from **ON** to **OFF**
   9. dismiss the Rewards panel
   10. click on the BAT icon in the URL bar again
   11. now click to toggle from **OFF** to **ON**, dismiss the panel
   11. reopen the panel now, and notice that "Include in Auto-Contribute" self-toggles to **OFF**

## Actual result:

"Include in Auto-Contribute" auto-toggles back to **OFF**, and the following exception is dumped in the console:

`
[19807:775:0301/110936.784322:WARNING:CONSOLE(1)] "Received external message from a sender who is not allowed to send messages to this background. Origin: chrome-extension://jidkidbbcafjabdphckchenhfomhnfma, URL: chrome-extension://jidkidbbcafjabdphckchenhfomhnfma/brave_rewards_panel.html", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
`

![twitter-tipping](https://user-images.githubusercontent.com/387249/109545698-0a2b2600-7a7e-11eb-8cc9-ac9011e4d09d.gif)

## Expected result:

"Include in Auto-Contribute" should be **ON**, as the ON/OFF preference for "Include in Auto-Contribute" should persist between panel openings/closings.

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.21.70 Chromium: 89.0.4389.69 (Official Build) (x86_64)
-- | --
Revision | 6df9174a477a0bea2118cb4669954d517be16104-refs/branch-heads/4389@{#1332}
OS | macOS Version 11.2.2 (Build 20D80)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes (`1.20.110`)
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

cc: @emerick @LaurenWags

**Comment by LaurenWags** [comment]
cc @zenparsing

**Comment by zenparsing** [comment]
Thanks @stephendonner for the very detailed description - will look into it!

**Comment by emerick** [comment]
@stephendonner I'm not able to repro on master. Are you still seeing this in the latest nightly? I think I followed your steps pretty exactly, but let me know!

**Comment by stephendonner** [comment]
@emerick yup, I can still reproduce this with 

Brave | 1.23.23 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.3 (Build 20D91)

![14413](https://user-images.githubusercontent.com/387249/110394203-e25d3480-8020-11eb-9c23-cc3d941598f6.gif)

**Comment by emerick** [comment]
@stephendonner Nice, I can repro following what you did in that GIF. Will investigate, thanks.

**Comment by stephendonner** [comment]
Verified `PASSED` using my original steps to reproduce, here, on `nightly` build


Brave | 1.24.11 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

Verified that Rewards/ auto-contribute pref state persisted correctly between panel dismisses, and even new-tab page loads.

![rewards-toggle](https://user-images.githubusercontent.com/387249/112042433-ba7fcd80-8b04-11eb-94fc-04dc119b57ac.gif)
