### ISSUE TITLE
Skip initialization of referral system for the default referral code

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#14428]
## Test plan
See https://github.com/brave/brave-core/pull/8103

## Background
Originally added in https://github.com/brave/brave-core/pull/1982 (to address https://github.com/brave/brave-browser/issues/2547), Brave will default to promo code `BRV001`.

We have since sunset the referral program (see https://brave.com/referral-program-update/) except for a few specific cases. For more information on how the referral program works please see https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes

## Description 
We should skip initialization of the referral system for the default code (`BRV001`)

**Comment by kjozwiak** [comment]
As per conversation with @BrendanEich @bsclifton and others, we'll want to get this into `1.21.x`. Adding `release/blocking`.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Windows 10 OS Version 2004 (Build 19041.804)

```
- Verified using `Charles Proxy` that I can no longer see the `referral_code:` `BRV001` section in a JSON blob under `initalize`, `nonua`, as I can, with release build `1.20.110`, for the host `https://laptop-updates.brave.com/`.
- Verified that the `BRV001` referral was being used in `brave://local-state`

|  `1.20.110` | `1.21.73` | Referral/promo code via brave://local-state (`1.21.73)
|--------|-------|-------|

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.73 x64 build
- Verified able to see the referral id under `nonua` on 1.20.108 build
![image](https://user-images.githubusercontent.com/17010094/109789018-ce23cc80-7c07-11eb-93a3-10a8f312a078.png)
- Verified `/promo/initialize/nonua` wasn't called on startup when running 1.21.73
![image](https://user-images.githubusercontent.com/17010094/109791171-0cba8680-7c0a-11eb-8e1a-bb613b4a6cff.png)
- Verified `brave://local-state` contains `BRV001` for referral code even when `/promo/initialize/nonua` is removed
![image](https://user-images.githubusercontent.com/17010094/109790569-75553380-7c09-11eb-8b32-a5d4fe7c1ce9.png)
- Verified `download_id` is not present in `brave://local-state` via the referral header
![image](https://user-images.githubusercontent.com/17010094/109790584-7a19e780-7c09-11eb-9556-b558a9cc4513.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Windows 10 OS Version 2004 (Build 19041.804)


```

- Verified using `Charles Proxy` that I can no longer see the `referral_code:` `BRV001` section in a JSON blob under `initalize`, `nonua`, as I can, with release build `1.20.110`, for the host `https://laptop-updates.brave.com/`.

- Verified that the `BRV001` referral was being used in `brave://local-state`

| `1.20.110` | `1.21.73` | Referral/promo code via brave://local-state `1.21.73`
|--------|-------|-------|
