### ISSUE TITLE
Add ability to easily turn off/on promoted content ads

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14422]
Follow up to: #13695.

Right now there is no easy way to turn on/off promoted content ads
User must go to `Customize -> Brave Partners` and turn off each partner.

![image](https://user-images.githubusercontent.com/34715963/109559983-a9323b00-7adb-11eb-9c9c-0fc5381e21f1.png)
![image](https://user-images.githubusercontent.com/34715963/109560597-5d33c600-7adc-11eb-8fa4-22a24fd4d859.png)

## Steps to Reproduce

1. Clean profile
1. Run Brave in US locale with ads staging server and dev feed server
1. View a feed
1. Click `Customize` in the bottom-right corner

## Actual result:

no easy way to turn on/off promoted content ads

## Expected result:
promoted content ads toggle is present

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.21.70 Chromium: 89.0.4389.69 (Official Build) (64-bit)
-- | --
Revision | 6df9174a477a0bea2118cb4669954d517be16104-refs/branch-heads/4389@{#1332}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @tmancey @petemill @jsecretan

**Comment by btlechowski** [comment]
Adding @mattmcalister to the conversation.

**Comment by mattmcalister** [comment]
This is no longer relevant. Closing.
