### ISSUE TITLE
Remove Brave from Help improve security on the web safe browsing setting

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14430]
## Description 
Remove Brave from Help improve security on the web safe browsing setting

## Steps to reproduce 

   1. Install 1.23.10 nightly
   2. Open Settings -> Privacy and Security -> Safe Browsing -> Standard protection
   3. Help improve security on the web contains Brave wording which should be removed as Brave doesn't collect any safebrowsing data

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/109637687-08786580-7b45-11eb-806a-2e8e2cf9e2ce.png)

## Expected result
No brave branding where Brave doesn't collect any data

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.23.9/1.22.45

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/android @brave/sec-team

**Comment by fmarier** [comment]
In fact, we should make sure that this option is removed entirely. We don't want users accidentally sending browsing data to Google by enabling this.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.22.62 x64 beta build

https://user-images.githubusercontent.com/17010094/111344828-a3f4f480-8674-11eb-9b64-2c3aeb5adc61.mp4

---------------
Verification passed on Samsung Tab A with Android 10 running 1.22.62 x64 beta build

https://user-images.githubusercontent.com/17010094/111346338-08fd1a00-8676-11eb-98bd-65a2128c7830.mp4
