### ISSUE TITLE
Amazon Prime Music Not Working

### ISSUE THREAD

**Issue by jonathanfrawley** [brave/brave-browser#14438]
## Description 
When I go to Amazon Prime Music I get an error message saying:
```
Update Chrome
We have upgraded and this browser version is no longer supported. Please update your browser.
```

## Steps to Reproduce

   1. Go to https://music.amazon.co.uk/
   2. Login

## Actual result:
![screen](https://user-images.githubusercontent.com/221395/109704341-68dfc500-7b8e-11eb-941d-60502776ffc0.png)

## Expected result:
A logged in page with all of my music there.

## Brave version (brave://version info)

Brave | 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
-- | --
Revision | 31b458a18f133db9203eb5a5dd6552de0716dda3-refs/branch-heads/4324_182@{#6}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? I think this is what I am on
- Can you reproduce this issue with the beta channel? Have not tried
- Can you reproduce this issue with the nightly channel? Have not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? I don't know how to do this.
- Is the issue reproducible on the latest version of Chrome? Have not tried.

**Comment by ryanbr** [comment]
Just tested this in Windows, had no issues logging in, 2FA via Amazon, then logged in to amazon music and was able to playback.

Is Widevine enable in `brave://settings/shields` ?

**Comment by jonathanfrawley** [comment]
Widevine was enabled, yes. It is however working again, I guess Amazon Music changed something on their end.

**Comment by jonathanfrawley** [comment]
Ah, I spoke too soon. This is happening again today, screenshot of widevine being enabled:
file:///home/jmf/Pictures/Screenshot%20from%202021-03-04%2015-34-29.png

**Comment by ryanbr** [comment]
Hey is this still an issue @jonathanfrawley  ?

Tested in current Brave and Brave Beta (today)

https://gif.fanboy.co.nz/gif/amazon-music.gif

**Comment by jonathanfrawley** [comment]
Looks to be working again consistently. I'll close this for now and if I can repro again consistently I will reopen.
