### ISSUE TITLE
Embeded Vimeo breaks without third-party cookie

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#1443]
## Description 
When a Vimeo video is embeded on a third-party domain, users are unable to view the video due to third-party cookie blocking. In order to view the video you must first _Allow All Cookies_, or lower shields entirely.

## Steps to Reproduce
1. Navigate to https://www.instructables.com/class/Mold-Making-Casting-Class/

## Actual result:
Vimeo video is not playable.

## Expected result:
Video should be playable.

## Reproduces how often: 
Always (as long as third-party cookies are blocked)

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Windows
JavaScript | V8 7.0.276.21
Flash | 31.0.0.108 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_31_0_0_108.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.35 Safari/537.36

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
When permitted, the player.vimeo.com document sets a cookie with a single key/value pair, which looks something like this:

    vuid:pl590458525.1004426671

**Comment by ryanbr** [comment]
@jonathansampson Seems safe to close, video playback is fixed.
