### ISSUE TITLE
Brave crashes on launch on Hackintosh MacOS 10.15.7

### ISSUE THREAD

**Issue by Sayuki0x** [brave/brave-browser#14439]
## Description 
Hello, I have a MacOS 10.15.7 installation that is a Hackintosh machine. It does not start, and immediately throws an exception.

## Steps to Reproduce
1. install brave on a hackintosh catalina machine
2. launch the browser

## Actual result:

![image](https://user-images.githubusercontent.com/35851667/109715679-2ce23b00-7b61-11eb-8922-532bfed2dc5a.png)

error_trace: https://pastebin.com/UNGmuQuL

## Expected result:
The browser launches normally

## Reproduces how often: 
Every time

## Version/Channel Information:

- Can you reproduce this issue with the current release?  **yes** 
- Can you reproduce this issue with the beta channel?  **yes**
- Can you reproduce this issue with the nightly channel? **yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **no**
- Does the issue resolve itself when disabling Brave Rewards? **no**
- Is the issue reproducible on the latest version of Chrome? **no**

## Miscellaneous Information:
```
                    'c.          ender@Connors-iMac.local 
                 ,xNMM.          ------------------------ 
               .OMMMMo           OS: macOS Catalina 10.15.7 19H15 x86_64 
               OMMM0,            Host: Hackintosh (SMBIOS: iMac15,1) 
     .;loddo:' loolloddol;.      Kernel: 19.6.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 2 days, 18 hours, 32 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 124 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.7.1 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2560x1440, 2560x1440 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: Apple_Terminal 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: SourceCodePro-Regular 
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i7-4790K (8) @ 4.00GHz 
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Radeon Pro WX 4100 
       .cooc,.    .,coo:.        Memory: 13163MiB / 32768MiB 
       ```

**Comment by bsclifton** [comment]
Closing as `wontfix`
