### ISSUE TITLE
Default browser message is not wrapped in certain locales

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14431]
## Description 

Default browser message is not wrapped in German locale

## Actual result:

default browser message is not wrapped in German locale
![image](https://user-images.githubusercontent.com/38657976/109642922-8d7d7200-7b79-11eb-9894-7e8b5290de6a.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/109643050-b998f300-7b79-11eb-968a-b4d5bb388fba.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.21.71 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Windows 10 OS Version 2004 (Build 19041.804)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @simonhong @rebron

**Comment by LaurenWags** [comment]
Also able to reproduce with Spanish (Spain):

<img width="2049" alt="Spanish-Spain" src="https://user-images.githubusercontent.com/28145373/109657098-1f15c100-7b33-11eb-953c-222d28bb8573.png">

Additionally, it looks like Japanese might not be entirely correct either (the message is on 2 lines, not 3):
<img width="2047" alt="Japanese" src="https://user-images.githubusercontent.com/28145373/109657150-2c32b000-7b33-11eb-8a1e-8872cd0ee031.png">

Other languages (like French) are fine.

```
Brave | 1.21.71 Chromium: 89.0.4389.72 (Official Build) (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 10.15.7 (Build 19H512)
```

@rebron not sure if there's an easy way to figure out which languages are affected in Transifex, rather than trial and error.

**Comment by simonhong** [comment]
@LaurenWags The format is determined by grd file like below for `US`.
As you can see, sentence is separated to 3 lines.
I think translated sentences should also be sperated into multiple lines.
Or, controlling it by adjusting dialog's width.(but it's hard to position sentences exactly to design)
<img width="956" alt="Screen Shot 2021-03-02 at 10 52 46 PM" src="https://user-images.githubusercontent.com/6786187/109658570-190ef700-7baa-11eb-9101-6ca880ed8f7f.png">
https://github.com/brave/brave-core/pull/7716/files#diff-6314ab9f5910c0e3dd53f8ac6bf09b584020abe6790abe7ebcdacc5756c5d5f9R936

**Comment by LaurenWags** [comment]
gotcha, thanks for this info @simonhong - makes sense what is happening then 👍🏻

**Comment by simonhong** [comment]
@LaurenWags I think we should use fixed width dialog because  translated length is vary and some lanuage would be fit with more than 3 lines.

**Comment by LaurenWags** [comment]
sgtm @simonhong - will let @rebron comment as well.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Windows 10 OS Version 2004 (Build 19041.804)


```
