### ISSUE TITLE
Fix crash when fetching Rewards Widget estimated earnings

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#14447]
## Description 

Fix crash when fetching Rewards Widget estimated earnings. Only reproduced on Windows, however the issue can occur on macOS, Linux and Android.

## Steps to Reproduce

   1. Fresh installation
   2. Open/close new tabs

## Actual result:

Ads service is restarted (see console logs)

## Expected result:
Ads service should not be restarted

## Reproduces how often: 

Intermittent issue. Reproduced on Windows

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
@kjozwiak After further thoughts, yes can we just run a basic verification test to make sure an ad appears.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Windows 10 OS Version 2004 (Build 19041.804)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/8114

**Confirm Rewards Widget estimated earnings are updated after a fresh install**

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.76 x64 build
- Verified no crash when viewing an ad and reloading NTP
- No checked done for rewards widget as its not available for Android
----------
Verification passed on Samsung Tab A with Android 10 running 1.21.76 x64 build
- Verified no crash when viewing an ad and reloading NTP
- No checked done for rewards widget as its not available for Android
