### ISSUE TITLE
Bug: Joplin extension 127.0.0.0:port/ping fetch calls always return net::ERR_BLOCKED_BY_CLIENT log messages

### ISSUE THREAD

**Issue by rwperrott** [brave/brave-browser#14445]
## Description 
After several days of using the [Joplin](https://github.com/laurent22/joplin) extension successfully in Brave, it suddenly became unable to test for the main Joplin application's clipper service port on 127.0.0.1 (e.g. address 127.0.0.1:41184/ping) , because the fetch() API calls now always fail with net::ERR_BLOCKED_BY_CLIENT; this is very annoying, and the uselessly terse error message is useless for identifying which extension or browser feature triggered the block or even why!

It is possible that a recent update for Brave, maybe Window 10, included some breaking change.

This is also annoying for page requests issues, when I have to guess which extension or browser feature decided to block an address, because again, the page tools console log has the same uselessly terse log message.

## Steps to Reproduce

   1. Open a new page tab type "127.0.0.1:41184/ping", and I see "JoplinClipperServer" displayed.
   2. Enable extensions developer mode.
   3. Disable all extensions except for Joplin.
   4. Select a page tab for an external rendered page.
   5. Left-Click on Joplin icon.
   6. Joplin icon popup shows "not_found Service status: Not found [Help]".
   7. Right-click on Joplin icon and select "Inspect pop-up", see useless net::ERR_BLOCKED_BY_CLIENT messages in developer console log, for speculative fetch requests, for several ports, which are useless for identifying which extension or browser feature triggered the block or even why!

The difference between 1 and 7/8 results doesn't make sense!

## Expected result:
The plugin fetch() API calls to 127.0.0.1 are not blocked, or at least the console log messages tells me which extension or browser feature blocked the fetch() call, maybe even why, so that I can look to remove the block.

## Reproduces how often: 
Always now.

## Brave version (brave://version info)
Platform: Windows
OS specifics: Window 10 Profession 64-bit, 20H2 service pack.
Brave: v1.20.110

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tried
- Can you reproduce this issue with the nightly channel? Not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Disabled already
- Is the issue reproducible on the latest version of Chrome? Not tried
 
## Miscellaneous Information:
The React source code for the Joplin extension can be found at https://github.com/laurent22/joplin/tree/dev/packages/app-clipper/popup/src , the service search code is in the bridge.js file.

**Comment by rwperrott** [comment]
I added the same plugins to the latest build of SRWare Iron 64-bit (a locked down Chrome), and the Joplin extension works, so something seems iffy with the Brave Browser.

**Comment by ryanbr** [comment]
For security, we block external requests to 127.0.0.1/localhost to Brave by default. Disabling Ads/Trackers in shields will work around it

**Comment by rwperrott** [comment]
This breaks an important protection feature.
Hopefully an extension option to allow localhost access, possibly for a port range, can be added, because I doubt that the "Joplin" clipper extension will be the last one using a local server.

**Comment by Stealthbird97** [comment]
> For security, we block external requests to 127.0.0.1/localhost to Brave by default. Disabling Ads/Trackers in shields will work around it

Yeah sorry. They better fix this or give me some other option, I'm switching browser in the meantime.

**Comment by Kilill** [comment]
The same issue for the Enpass Password Manger : https://community.brave.com/t/brave-shield-blocking-enpass-extension/212460
Must say this was an ill thought out feature, it should at the least have had an option to turn this blocking off, and ideally an option to white list ports and or extensions.

Haven't tested it but if 127.0.0.1 is completely  blocked that means that running a local webserver and trying to contact it is out of the question ? me thinks  some developers will be a bit miffed about that....

**Comment by StefanLobbenmeier** [comment]
Also affects the Kee Password manager

**Comment by StefanLobbenmeier** [comment]
https://github.com/brave/brave-browser/releases/tag/v1.21.70 might not have this issue yet, so I am going to try it.

**Comment by StefanLobbenmeier** [comment]
That one also had the issue, trying https://github.com/brave/brave-browser/releases/tag/v1.20.108 next.

**Comment by StefanLobbenmeier** [comment]
https://github.com/brave/brave-browser/releases/tag/v1.20.108 does not have the issue for Kee.

**Comment by noahphex** [comment]
Definitely blocking the use of the Kee Password extension.

**Comment by Kilill** [comment]
working in 1.21.74. 
Naively tried down grading to 1.20.108 by downloading installing that version, but seems that is not the proper way to do it, about says 1.21.74 but Enpass as well as Keepass now works

**Comment by noahphex** [comment]
Confirmed working again in 1.21.74.

**Comment by rwperrott** [comment]
Thanks for fixing this.
