### ISSUE TITLE
brave://ipfs shows an empty page on nightly

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#14443]
## Description 

brave://ipfs shows an empty page on nightly

## Steps to Reproduce

   1. Visit brave://ipfs

## Actual result:

Empty page is shown with console error.
<img width="937" alt="Screen Shot 2021-03-02 at 3 06 18 PM" src="https://user-images.githubusercontent.com/4730197/109727261-de389f00-7b68-11eb-8681-735b95ab53de.png">

## Expected result:
Should display page normally.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` using 

Brave | 1.23.15 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

I also did a quick check to make sure installation and `Start`, `Stop`, `Restart`, and `My Node` worked.

<img width="1217" alt="Screen Shot 2021-03-03 at 10 46 31 AM" src="https://user-images.githubusercontent.com/387249/109855986-d121bb80-7c0d-11eb-9978-8893541101f5.png">
<img width="1312" alt="Screen Shot 2021-03-03 at 10 46 45 AM" src="https://user-images.githubusercontent.com/387249/109855990-d1ba5200-7c0d-11eb-9418-e6d3e9a07da5.png">
