### ISSUE TITLE
The application has failed to start because its side-by-side configuration is incorrect

### ISSUE THREAD

**Issue by comodoro** [brave/brave-browser#1444]
Have you searched for similar issues? Before submitting this issue, please check the open issues and add a note before logging a new issue. 

Yes

## Description
Brave downladed as zip archive fails to start on my Windows 10 with the above error message

## Steps to Reproduce
   1. Download Brave for Windows zipped binaries from https://github.com/brave/brave-browser/releases/download/v0.56.2/brave-v0.56.2-win32-x64.zip
   2. Extract the archive and run the executable, probably should be on relatively recently installed Windows

## Actual result:
Error dialog **The application has failed to start because its side-by-side configuration is incorrect** is shown

## Expected result:
Brave should start

## Reproduces how often: 
Easily reproduced

## Brave version (chrome://version info)
Brave 0.56.2
Brave 0.55.11

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Yes/Yes
- Does it reproduce on browser-laptop? 
Cannot find browser-laptop Windows zipped executable binary

### Website problems only:  
N/A

### Additional Information
System event log:
```
Activation context generation failed for "C:\Programs\brave\brave.exe". Dependent Assembly 70.0.56.2,language="&#x2a;",type="win32",version="70.0.56.2" could not be found. Please use sxstrace.exe for detailed diagnosis.
```
No other applications behave this way on my system. To theorize, might this be a dependency issue fixable by installing some redistributable libraries? In any case, an average user should not have to do that

OS is Win10 Pro 1809 build 17763.1

**Comment by srirambv** [comment]
You need to download 
`BraveBrowserDevSetup32.exe` or `BraveBrowserDevSetup64.exe` for Dev 
`BraveBrowserBetaSetup32.exe` or `BraveBrowserBetaSetup64.exe` for Beta 
depending on your OS (64bit or 32bit). This will download the actual setup and install it.

Even though the zip file contains executable its not the one you need to run the browser.

**Comment by comodoro** [comment]
I gather there is no portable version then. So the zip file is there because...?

**Comment by comodoro** [comment]
OK, thanks. Just in my opinion having generically named zip among releases is misleading

**Comment by vampyren** [comment]
I totally agree with @comodoro on the naming. I also downloaded thinking this is a portable version. And the error does not make any sense either. 
Hoping for a portable and offline installer in the future.
