### ISSUE TITLE
Stop node if switched from local node to another option

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#14450]
Stop node if switched from local node to another option

## Steps to Reproduce

   1. Select local node in settings
   2. Visit ipfs:// url
   3. Check the node is launched
   4. Select gateway in settings, close settings tab
   5. Check the node is stopped

## Actual result:

Local node stays launched

## Expected result:
Local node is stopped

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan here on `nightly` build 

Brave | 1.24.35 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1. Opened `brave://settings` and selected `Local node` from `Method to resolve IPFS resources`
2. Loaded `brave://ipfs-internals`
3. Verified the node is launched
4. Selected `Gateway` in `brave://settings` for `Method to resolve IPFS resources`
5. Verified the node was stopped

![ipfs-gateway-stop](https://user-images.githubusercontent.com/387249/113061239-9b1d1c00-9166-11eb-903f-3ddfa036860e.gif)
