### ISSUE TITLE
IPFS: My Node button should be a different color from Start/Stop/Restart buttons

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14452]
## Description 
IPFS: My Node button should be a different color from Start/Stop/Restart buttons

## Steps to Reproduce

   1.  new profile, launch Brave
   2.  load `brave://ipfs`
   3.  click the `Install and start` button
   4.  note the color of the `My Node` button

## Actual result:

`My Node` is the same blueish color as the `Start`/`Stop`/`Restart` buttons.

<img width="1312" alt="Screen Shot 2021-03-03 at 9 32 08 AM" src="https://user-images.githubusercontent.com/387249/109846751-58b5fd00-7c03-11eb-8029-a117e65a6e4e.png">

## Expected result:

According to https://github.com/brave/brave-browser/issues/13173#issuecomment-743484871, the button color for `My Node` should be different from the `Start`/`Stop`/`Restart` buttons

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.22.51 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc: @jessicaschilling @spylogsster @karenkliu - probably Karen has UI insight, here?

**Comment by karenkliu** [comment]
This should use our shared frontend button component:

![image](https://user-images.githubusercontent.com/2388823/110039395-fee22f80-7cf5-11eb-8811-3f9fc10fa071.png)

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.25.2 Chromium: 90.0.4430.51 (Official Build) nightly (x86_64)
-- | --
Revision | 32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}
OS | macOS Version 11.2.3 (Build 20D91)

Looks just like the mockup from @karenkliu in https://github.com/brave/brave-browser/issues/14452#issuecomment-790990036

<img width="1782" alt="Screen Shot 2021-04-07 at 3 53 08 PM" src="https://user-images.githubusercontent.com/387249/113944659-c1bc0200-97b9-11eb-8980-c39f5c9bbb91.png">
