### ISSUE TITLE
Unable to detect Tor mode via JavaScript Image() load

### ISSUE THREAD

**Issue by the-rocinante** [brave/brave-browser#14466]
## Description 

I have a web-page accessible over both clearnet (over https) and Tor, and am trying to detect whether the client's browser supports Tor. This is accomplished by loading a JavaScript Image() from the hidden service address if the window.location.hostname is the clearnet address. By using the Image() load vs onerror event handlers it can therefore be possible to detect if the browser supports Tor.

However doing this in Brave (as opposed to Tor Browser, causes error "Failed to load resource: net::ERR_NAME_NOT_RESOLVED" due to trying to load an insecure resource (http; within an https page), which Brave then erroneously attempts to upgrade to https.

## Steps to Reproduce

   1. Setup a web-page and image accessible via both Tor hidden service and via clearnet (with https).
   2. Include the following JavaScript snippet (replacing `${torHiddenServiceAddress}/some.png` with the correct .onion address path to the image.

...<script>  (new Image ()).src = `${torHiddenServiceAddress}/some.png`; </script>...
 

   3. Browse to the web-page's clearnet address using Brave browser in Tor mode with developer console open.
   4. Note the error, indicating lack of success loading the image.

## Actual result:

The (new Image()).onerror() is triggered, and an error "Failed to load resource: net::ERR_NAME_NOT_RESOLVED" is output to the console.

## Expected result:

As per Tor Browser, the (new Image()).load() is triggered, and no error occurs.

## Reproduces how often: 

Consistently.

## Brave version (brave://version info)

Brave | 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Linux
JavaScript | V8 8.9.255.20

**Comment by diracdeltas** [comment]
does Tor browser treat `.onion` as a secure context? we currently don't, but there is an open issue: #13834 

in the meantime, you might be able to workaround this by loading an image from an https hidden service, such as https://brave5t5rjjg3s6k.onion/

**Comment by the-rocinante** [comment]
> does Tor browser treat .onion as a secure context?

So it would seem based on the lack of any associated warnings/errors.

Thanks for the proposed work-around. If I can find the right image that may suffice as a kluge. Hopefully LetsEncrypt starts offering certs for .onion too now that it's been officially approved, since this is currently problematic for every browser which doesn't explicitly have built-in Tor support.

**Comment by fmarier** [comment]
Let's close this as a "duplicate" of https://github.com/brave/brave-browser/issues/1135 since that's the underlying issue causing this problem in Brave.
