### ISSUE TITLE
UI glitch when try to close a page

### ISSUE THREAD

**Issue by LorisTecnology** [brave/brave-browser#14464]
## Description 

When i click to close a page the top bar glitch and then the page get closed

## Steps to Reproduce

   1. Open a page
   2. Close it

## Actual result:

Top bar page glitch

## Expected result:
Page close without glitch

## Reproduces how often: 

Always

## Brave version (brave://version info)

V1.21.73 (Mar 3, 2021)

**Comment by rebron** [comment]
Hi @LorisTecnology Are you still seeing this issue on 1.24.82. Also, we'll need a lot more detail/specifics not sure what you mean by glitch wha you're experiencing. The more details the better including operating system, example pages, etc.

**Comment by rebron** [comment]
Closing per last comment. Thanks @LorisTecnology
