### ISSUE TITLE
Cosmetic filtering does not work on MacOS 10.15 (Implemented cosmetic filters. (#13070)

### ISSUE THREAD

**Issue by AlexLog** [brave/brave-browser#14468]
## Description 
Cosmetic filtering does not work (MacOS 10.15.7, Brave Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (x86_64))

## Steps to Reproduce
The same as for issue #13070
   1. Go to chicagotribune.com
   2. Observe an empty space on top of the webpage
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/5529233/109990044-6d67c300-7cdf-11eb-9f43-46e697e4dfdd.png)

## Expected result:
![image](https://user-images.githubusercontent.com/5529233/109990082-72c50d80-7cdf-11eb-96c0-d4404c89153c.png)

## Brave version (brave://version info)

Brave | 1.21.73 Chromium: 89.0.4389.72 (Official Build) (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 10.15.7 (Build 19H524)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
This should be resolved with https://github.com/brave/brave-core/pull/8152  Also, using both uBO and shields may cause some issues.

**Comment by AlexLog** [comment]
uBO was installed after the issue was discovered, just to show 'Expected result'

**Comment by AlexLog** [comment]
[https://www.bbc.com/russian](url)  may be a more interesting example. There are wide empty lines not marked as 'Advertisement.' uBO removes them as well.'
