### ISSUE TITLE
Tor window stuck in disconnected state while Tor circuit is established

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#14461]
Sometimes we can see circuit established before we open control channel, in that case we will not able to use Tor if we don't close and reopen a new Tor window.
When that happens, we can see this behavior from tor log
```
...
[notice] Bootstrapped 100% (done): Done
...
[notice] New control connection opened from 127.0.0.1.
```

STR is very simple:
1. Open Tor window
2. Relaunch Brave
3. Repeat step 1-2 until see that behavior
4. When it happens, check tor log in brave://tor-internals/, we can see the above scenario

**Comment by btlechowski** [comment]
Each platform uses different tor binary. Best to check on all platforms. Added `QA/Test-All-Platforms`

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.23.28 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
Revision	0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS	macOS Version 10.15.7 (Build 19H524)
```

Attempted to reproduce the issue ~15x using STR from description with 1.21.74, but was unsuccessful.

Ran thru STR from description using 1.23.x ~15x and did not encounter the issue as described. 

------------------
