### ISSUE TITLE
Update to v1.21.73 breaks some extensions

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#14473]
## Description 

Many users are reporting broken extensions that were previously working just fine after updating to version 1.21.73. Note that most of these extensions seem to have some relation to passwords and/or the browser reading/writing data from the device to the browser. Additionally, users are reporting that the extensions are still working as intended in Chrome/Edge/Other Chromium browsers. 
cc @rebron @jumde @ryanbr 
## Brave version (brave://version info)

```
Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)
```

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

User threads:
https://community.brave.com/t/brave-version-1-21-73-chromium-89-0-4389-72-on-mac-breaks-enpass/212242/9
https://community.brave.com/t/avast-password-down-after-1-21-brave-update/212277
https://community.brave.com/t/xdm-doesnt-work-after-updating-brave-browser/212260

Images:
![image](https://user-images.githubusercontent.com/3299098/110007245-54571600-7ccf-11eb-988e-0ca76be5612f.png)
![image](https://user-images.githubusercontent.com/3299098/110007266-58833380-7ccf-11eb-9cd7-8883ce3f5833.png)

**Comment by Brave-Matt** [comment]
User reporting Pushbullet also broken:
https://community.brave.com/t/pushbullet-extension-broke-today/212653

**Comment by Brave-Matt** [comment]
Another user reporting "Mooltipass" broken:
https://community.brave.com/t/brave-v1-21-73-does-not-work-with-mooltipass-extention-anymore/212667

**Comment by Brave-Matt** [comment]
☝️ To reiterate what I mentioned in the description, it seems like most if not all of these apps have a desktop "companion" application that is now not being detected. Notice the errors reported in the images:
![image](https://user-images.githubusercontent.com/3299098/110012238-312f6500-7cd5-11eb-90d8-95fd0e715ac8.png)
![image](https://user-images.githubusercontent.com/3299098/110012904-e235ff80-7cd5-11eb-8e92-6304967bea6b.png)
![image](https://user-images.githubusercontent.com/3299098/110013086-0f82ad80-7cd6-11eb-84d2-ada75fbaffa6.png)

**Comment by Varusal** [comment]
Same issues with the KeePass brave extensions.
[](https://community.brave.com/t/keepass-extensions-doesnt-work/210488)

**Comment by Creyox** [comment]
Can confirm, the Kee Extension for KeePass is broken. Turns out the Trackers & Ads blocking in Brave Shield somehow blocks the database communicating to the plugin. When I switch
![image](https://user-images.githubusercontent.com/54220297/110018641-c65b4980-7d27-11eb-86e1-54d19a0dd7b7.png)
to
![image](https://user-images.githubusercontent.com/54220297/110018688-d5da9280-7d27-11eb-9309-57f47abc8bd0.png)
the connection is established right away. Strangely this setting is reset after a restart and not saved.

**Comment by Varusal** [comment]
> Can confirm, the Kee Extension for KeePass is broken. Turns out the Trackers & Ads blocking in Brave Shield somehow blocks the database communicating to the plugin. When I switch
> ![image](https://user-images.githubusercontent.com/54220297/110018641-c65b4980-7d27-11eb-86e1-54d19a0dd7b7.png)
> to
> ![image](https://user-images.githubusercontent.com/54220297/110018688-d5da9280-7d27-11eb-9309-57f47abc8bd0.png)
> the connection is established right away. Strangely this setting is reset after a restart and not saved.

Can confirm that it works with **Trackers & ads blocking** on **disabled**.
Makes Brave Shield literally useless if you use a KeePass extension.

Hopefully that will get fixed soon.

**Comment by Creyox** [comment]
Does this setting turn back on your browser after a restart? On mine it's reset to "Standard" after one.

**Comment by Varusal** [comment]
> Does this setting turn back on your browser after a restart? On mine it's reset to "Standard" after one.

Yeah, does also happen to me. This update broke a lot of stuff according to the brave community.

**Comment by beatschubser** [comment]
> User reporting Pushbullet also broken:
> https://community.brave.com/t/pushbullet-extension-broke-today/212653

The Pushbullet-addon ist broken for me as well. Disabling Ad-blocking globally fixes the issue. Disabling Ad-blocking for api.pushbullet.com doesn't help, although this is the endpoint for all requests.

![2021-03-04_22h30_02](https://user-images.githubusercontent.com/9355283/110033211-6372ae00-7d39-11eb-89eb-ba81457840b3.png)

**Comment by legolasdimir** [comment]
i tried that and pushpullet started working for a minute then it stopped again. so it might be more than that.

**Comment by naikel** [comment]
I hope this issues would make the developers realize how important is a downgrade and a "disable auto-updates" feature.

The workarounds are:

1.- Disable adblocked and install uBlock in the meantime.
2.- Use another browser while this is fixed.

But I don't think people can actually live typing 32 random chars passwords or copy/pasting them from another app.  I know I can't.

**Comment by Varusal** [comment]
Solution:

1. brave://adblock
2. add this line
![image](https://user-images.githubusercontent.com/10616926/110111589-de2ae000-7db0-11eb-8ef1-f0f64f4bdb57.png)

Now the extensions works perfectly fine.

**Comment by beatschubser** [comment]
> Solution:
> 
> 1. brave://adblock
> 2. add this line
>    ![image](https://user-images.githubusercontent.com/10616926/110111589-de2ae000-7db0-11eb-8ef1-f0f64f4bdb57.png)
> 
> Now the extensions works perfectly fine.

I was googling "Brave whitelist" yesterday and couldn't find this for the life of me. Are there no side-effects with the rule?

**Comment by legolasdimir** [comment]
So I've heard some people say keepass is not working? I'm using keepassxc and that seems to be fine. I'd recommend taking a look at it as an alternative or possible workaround. It uses the same database format. The big difference is it does not support cloud sync natively so you have use something else to sync files.

**Comment by Creyox** [comment]
> > Solution:
> > 
> > 1. brave://adblock
> > 2. add this line
> >    ![image](https://user-images.githubusercontent.com/10616926/110111589-de2ae000-7db0-11eb-8ef1-f0f64f4bdb57.png)
> > 
> > Now the extensions works perfectly fine.
> 
> I was googling "Brave whitelist" yesterday and couldn't find this for the life of me. Are there no side-effects with the rule?
> 
> Edit: Not working here, even after a restart.

Try using 127.0.0.1 instead of localhost, this seems to work for me

**Comment by beatschubser** [comment]
> Try using [127.0.0.1](http://127.0.0.1) instead of localhost, this seems to work for me

That doesn't work either. Here's what it looks like on my machine:

`||localhost^$important,third-party
||127.*^$important,third-party
||[::1]^$important,third-party
||192.168.*^$important,third-party
@@127.0.0.1`

 Gotta wait for the official fix.

**Comment by Varusal** [comment]
> > Try using [127.0.0.1](http://127.0.0.1) instead of localhost, this seems to work for me
> 
> That doesn't work either. Here's what it looks like on my machine:
> 
> ||localhost^$important,third-party
> ||127._^$important,third-party ||[::1]^$important,third-party ||192.168._^$important,third-party
> @@127.0.0.1
> 
> Gotta wait for the official fix.

Yeah, I've read that it doesn't work for some. Weird.

**Comment by Varusal** [comment]
So it seems that KeePassHttp (plugin for KeePass) with KeePass Helper extension (browser) work with that @@localhost rule.
KeePassRPC does apparently not work.
https://community.brave.com/t/keepass-extensions-doesnt-work/210488/12

**Comment by beatschubser** [comment]
> So it seems that KeePassHttp (plugin for KeePass) with KeePass Helper extension (browser) work with that @@localhost rule.
> KeePassRPC does apparently not work.
> https://community.brave.com/t/keepass-extensions-doesnt-work/210488/12

Ok, it seems you have to whitelist the (Sub-)Domains for the failing addon-requests, in case of Pushbullet:

@@*.pushbullet.com

That is working fine. If you can't wait for the fix, open the dev tools for the broken Addon, check the network-tab for blocked requests and add those to the whitelist.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
Revision	3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS	Linux
```

Reproduced original issue with Enpass using `1.21.73`:

Example | Example
----- | -----
<img width="770" alt="1 21 73 looking" src="https://user-images.githubusercontent.com/28145373/110224326-81aaec00-7ea8-11eb-9005-96114a30cbc8.png"> | <img width="769" alt="1 21 73 error" src="https://user-images.githubusercontent.com/28145373/110224327-82dc1900-7ea8-11eb-94d2-8991f67fdc71.png">

Confirmed when using `1.21.74` (for the first time with Enpass) I was prompted to allow to connect:

<img width="389" alt="1 21 74 prompt" src="https://user-images.githubusercontent.com/28145373/110224336-a010e780-7ea8-11eb-800d-dc5d87546277.png">

After allowing this and linking via passcode I was able to access existing logins as well as create new ones.

Ex: Navigate to a site where I have a login saved. Click in username field. Right click and select Enpass from context menu. I am prompted to enter my master password as below. Once I do, the helper window shows my login. Selecting it populates my info and I am logged in as expected.

Example | Example
----- | -----
<img width="382" alt="Screen Shot 2021-03-06 at 6 17 50 PM" src="https://user-images.githubusercontent.com/28145373/110224404-54ab0900-7ea9-11eb-935f-40d2914b7660.png"> | <img width="371" alt="Screen Shot 2021-03-06 at 6 24 04 PM" src="https://user-images.githubusercontent.com/28145373/110224405-5674cc80-7ea9-11eb-854b-e8fd498ba2d0.png">

**Comment by beatschubser** [comment]
Confirmed that Pushbullet is working again with Version 1.21.74. Thank you!

**Comment by LaurenWags** [comment]
Thanks for the confirmation @beatschubser 😄
