### ISSUE TITLE
Add ENS support

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#14477]
Support the name resolution of ethereum name service (ENS) via https://resolver.cloudflare-eth.com/dns-query endpoint when the feature is enabled in brave://flags and user set the resolve method to public DoH server.
This issue is to support the same as we have for unstoppable domains in https://github.com/brave/brave-browser/issues/14099 for ENS, and for .eth TLDs only.

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` with the testplan from https://github.com/brave/brave-core/pull/8125 on build

| Brave    | 1.23.23 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64) |
| -------- | ------------------------------------------------------------ |
| Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393} |
| OS       | macOS Version 11.2.3 (Build 20D91)                           |


1. Open Brave and visit `brantly.eth`, it should show error page saying `This site can’t be reached`.
<details>
<summary>screenshot</summary>
<img width="1312" alt="Screen Shot 2021-03-08 at 2 28 14 PM" src="https://user-images.githubusercontent.com/387249/110390253-8becf780-801a-11eb-8fcb-e65e628f9d10.png">
</details>



2. Go to settings, search for ens, there should be no ens domains resolve method setting.

<details>
<summary>screenshot</summary>
<img width="1312" alt="Screen Shot 2021-03-08 at 2 29 13 PM" src="https://user-images.githubusercontent.com/387249/110390377-bfc81d00-801a-11eb-8abc-ee087d2a626c.png">
</details>


3. Go to `brave://flags` and search for unstoppable and enable the feature flag.

<details>
<summary>screenshot</summary>
<img width="1199" alt="Screen Shot 2021-03-08 at 2 29 45 PM" src="https://user-images.githubusercontent.com/387249/110390428-d40c1a00-801a-11eb-9598-f16616237113.png">
</details>


4. Restart browser and go to `brantly.eth` should now should the interstitial for users to opt-in unstoppable domains support.

<details>
<summary>screenshot</summary>
<img width="1312" alt="Screen Shot 2021-03-08 at 2 31 40 PM" src="https://user-images.githubusercontent.com/387249/110390795-5e547e00-801b-11eb-9ca5-233bb9bf9e6e.png">

</details>


5. Click Disable, should now see site can't be reached and `Method to resolve unstoppable domains` in `brave://settings` should now be `Disabled`.

<details>
<summary>screenshots</summary>
<img width="1312" alt="Screen Shot 2021-03-08 at 2 31 51 PM" src="https://user-images.githubusercontent.com/387249/110390604-1897b580-801b-11eb-821d-148f4911e0dd.png">
<img width="1312" alt="Screen Shot 2021-03-08 at 2 32 07 PM" src="https://user-images.githubusercontent.com/387249/110390605-19304c00-801b-11eb-9754-84a0ab2aca80.png">

</details>


6. Change the resolve method setting back to ask and visit `brantly.eth` again.

<details>
<summary>screenshot</summary>

<img width="1312" alt="Screen Shot 2021-03-08 at 2 35 01 PM" src="https://user-images.githubusercontent.com/387249/110390896-893ed200-801b-11eb-8237-1543d96f8e92.png">

</details>


7. Opt-in interstitial should be shown again, and this time click `Proceed using Cloudflare server`.
8. Page should be loaded now. (Note that there will be a brief moment that it is showing site is not reached while the page is loading, this is a known and will be addressed in a new issue.)

<details>
<summary>screenshot</summary>
<img width="1312" alt="Screen Shot 2021-03-08 at 2 35 20 PM" src="https://user-images.githubusercontent.com/387249/110390893-893ed200-801b-11eb-8097-88bfb2b7a192.png">

</details>

9. `Method to resolve Ethereum Name Services (ENS)` in `brave://settings` should now be `Public DNS over HTTP server`.

<details>
<summary>screenshot</summary>
  <img width="1312" alt="Screen Shot 2021-03-08 at 2 37 06 PM" src="https://user-images.githubusercontent.com/387249/110391051-c905b980-801b-11eb-82e2-3cbd8b5f8d6e.png">


</details>

10. Open a new tab and visit `brantly.eth`, page should be loaded normally without any interstitial pages.  

<details>
<summary>screenshot</summary>
<img src="https://user-images.githubusercontent.com/387249/110390893-893ed200-801b-11eb-8097-88bfb2b7a192.png">
</details>

Additionally, I filed https://github.com/brave/brave-browser/issues/14478 for the cropped `Public DNS over HTTPS serv` text in the select widget.

**Comment by zackees** [comment]
Hey I just tried to visit https://resolver.cloudflare-eth.com/dns-query and I got the following error, is this a problem?

![image](https://user-images.githubusercontent.com/6856673/164070307-f4d40198-c1a8-4d5c-903c-734ca1adc151.png)

**Comment by ana585** [comment]
STARBUCKS™
SHARED PLANET™
You and Starbucks. It's bigger than coffee.
Hand Dryer
Using these energy-efficient hand
dryers reduces paper towel
consumption.XLERATOR
EXCEL DRYER
