### ISSUE TITLE
Repository not signed, can't re-add the repository key

### ISSUE THREAD

**Issue by kpuljek** [brave/brave-browser#1447]
## Similar issues

Yes, found some in the brave-laptop repository, but no actual solutions.

## Description 

When trying to update my system, I get an error telling me that the Brave repository isn't signed and will be disabled.

```
E: Failed to fetch https://brave-browser-apt-beta.s3.brave.com/dists/bionic/InRelease  403  Forbidden [IP: 151.101.114.217 443]
E: The repository 'https://brave-browser-apt-beta.s3.brave.com bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

## Steps to Reproduce

   1. Installed Brave Beta and used it for a while
   2. It updated a few days ago
   3. Now the repository doesn't work, and I can't even re-add it because the key url from the curl command  says "Access denied" whenever I try to access it.

## Actual result:

Can't update, can't upgrade, can't reinstall.

## Expected result:

Brave should update normally.

## Reproduces how often: 
Every time.

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Didn't try all of the versions, but I suppose it will happen for every repo using the https://brave-browser-apt-dev.s3.brave.com/brave-core-nightly.asc key.

- Does it reproduce on browser-laptop? 

Don't know. Probably would happen for all repositories signed with the brave-core-nightly.asc key.

**Comment by DocWicking** [comment]
According to [this community forum thread](https://community.brave.com/t/repository-not-signed/34229/3), the responsible team "is aware and working on it".

**Comment by kpuljek** [comment]
Oh, great! When I last wanted to check brave community, it wasn't working either. Thanks for the information

**Comment by ddrager** [comment]
https://brave-browser-apt-beta.s3.brave.com/brave-core-nightly.asc, the gpg key, is giving Access Denied error from S3

**Comment by ddrager** [comment]
This key is available again so this appears to be resolved.

**Comment by nmschulte-aviture** [comment]
I am still having this issue on Debian Sid.

Both sets of instructions fail with the same issue:
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#ubuntu-16-04
https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md

As well, Debian should be properly listed as a heading in the `installing-brave` document...

**Comment by cjt243** [comment]
I am also seeing this issue, trying both sets of instructions from @nmschulte-aviture. On Ubuntu 18-04.

**Comment by lidel** [comment]
I believe this can be solved by updating instructions at https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux. 
IT has old repos, and Debian moved to new stable name some time ago.

Below

```diff
- deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ trusty main
+ deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ buster main
```

**Comment by fmarier** [comment]
This is a very old issue and I believe the Linux repos are working quite well now.

If you are still running into problems, please file a new issue and we will investigate.
