### ISSUE TITLE
'Public DNS over HTTP server" text in Settings select widget is cropped

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14478]
## Description 
`Public DNS over HTTP server` text in Settings select widget is cropped

## Steps to Reproduce

   1.  go to `brave://flags`
   2.  search for "unstoppable"
   3.  choose "Enabled"
   4. restart Brave
   5. load `brave.crypto`, and click `Proceed using Cloudflare server`
   6. go to `brave://settings` and under Method to resolve unstoppable domains" choose "Public DNS over HTTPS server"
   7. click to dismiss the select widget, and notice the length/appearance of the text

## Actual result:

Even with a full-width, 2880x1800 display, the preference text is cropped, and reads `Public DNS over HTTPS serv`

<img width="1788" alt="Screen Shot 2021-03-04 at 3 03 02 PM" src="https://user-images.githubusercontent.com/387249/110042523-bed17b80-7cfa-11eb-8367-1e7157baf692.png">

<img width="694" alt="Screen Shot 2021-03-04 at 3 25 44 PM" src="https://user-images.githubusercontent.com/387249/110044411-efff7b00-7cfd-11eb-8529-824c1ed7cafd.png">

## Expected result:

Text should either be cropped with an ellipsis "..." or some other shorter text/titletip.

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @karenkliu @yrliou

**Comment by karenkliu** [comment]
This needs to be swapped out with our standardized dropdown component.

**Comment by yrliou** [comment]
I believe this is not an issue anymore after https://github.com/brave/brave-core/pull/8317 is merged.
Closing here, please reopen if it is still reproducible.

**Comment by stephendonner** [comment]
Verified; the string is now `DNS over HTTPS` so fits much better into the `<select>` widget, in English, with more room for l10n.


Brave | 1.24.26 Chromium: 90.0.4430.30 (Official Build) nightly (x86_64)
-- | --
Revision | 5674335ff855e43f3bccf8cfc29a779bdf0d067f-refs/branch-heads/4430@{#532}
OS | macOS Version 11.2.3 (Build 20D91)

<img width="1684" alt="Screen Shot 2021-03-25 at 4 02 09 PM" src="https://user-images.githubusercontent.com/387249/112554446-8e25b480-8d83-11eb-880e-53a1898984fa.png">
