### ISSUE TITLE
Improve support for generic Rewards wallet providers

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#14470]
The Rewards bF prototype improved support for generic external wallet providers. In preparation for additional wallet providers, let's bring over those changes.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.23.58 Chromium: 89.0.4389.114 (Official Build) beta (x86_64)
Revision	1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS	macOS Version 10.15.7 (Build 19H524)
```

Verified test plan from https://github.com/brave/brave-core/pull/8129#issue-585088560

<details>
<summary>Confirmed able to connect Uphold wallet</summary>

<img width="405" alt="WalletSS" src="https://user-images.githubusercontent.com/28145373/113448318-9b692180-93c9-11eb-928a-6251942de584.png">

</details>

<details>
<summary>Confirmed able to do a one time tip to a KYC'd creator</summary>

Example | Example
----- | -----
<img width="651" alt="KYC 1time tip 2" src="https://user-images.githubusercontent.com/28145373/113448336-a0c66c00-93c9-11eb-8578-c0ad0d173ab3.png"> | <img width="451" alt="KYC 1time tip 1" src="https://user-images.githubusercontent.com/28145373/113448342-a2902f80-93c9-11eb-9104-c3ea287c2740.png">

</details>

<details>
<summary>Confirmed one time tip to a verified, non KYC'd creator goes to pending list</summary>

Example | Example 
----- | ----- 
<img width="968" alt="non KYC 1time tip 2" src="https://user-images.githubusercontent.com/28145373/113448353-ac199780-93c9-11eb-8518-ed6abbcc04bb.png"> | <img width="426" alt="non KYC 1time tip 3" src="https://user-images.githubusercontent.com/28145373/113448357-afad1e80-93c9-11eb-8b0a-69c4544217bc.png">

</details>

<details>
<summary>Confirmed monthly tip to a KYC'd creator</summary>

Example | Example
----- | ----- 
<img width="661" alt="Monthly tips" src="https://user-images.githubusercontent.com/28145373/113448398-c489b200-93c9-11eb-869f-19ad91ea1e72.png"> | <img width="470" alt="KYC monthly tip 3" src="https://user-images.githubusercontent.com/28145373/113448409-c94e6600-93c9-11eb-898d-d65344151f09.png">

</details>

<details>
<summary>Confirmed monthly tip to a verified, non KYC'd creator goes to pending list</summary>

Example | Example | Example
----- | ----- | -----
<img width="661" alt="Monthly tips" src="https://user-images.githubusercontent.com/28145373/113448435-d53a2800-93c9-11eb-9a1a-4a3c2fd64db5.png"> | <img width="953" alt="pending tips" src="https://user-images.githubusercontent.com/28145373/113448440-d8351880-93c9-11eb-8e68-9be2d7a1bdca.png"> | <img width="450" alt="non KYC monthly tip 3" src="https://user-images.githubusercontent.com/28145373/113448445-da977280-93c9-11eb-8115-af326836bee0.png">

</details>

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.69 x64 build

<details>
<summary>Verified test plan from <a href=https://github.com/brave/brave-core/pull/8129#issue-585088560>brave-core/pull/8129 (comment)</a></summary>
<br>
<details>
<summary>Confirmed able to connect Uphold wallet</summary>

![image](https://user-images.githubusercontent.com/17010094/114395617-809a6800-9b94-11eb-953b-0a418e6f170f.png)

</details>

<details>
<summary>Confirmed able to do a one time tip to a KYC'd creator</summary>

![image](https://user-images.githubusercontent.com/17010094/114395639-88f2a300-9b94-11eb-9d78-784958374348.png) | ![image](https://user-images.githubusercontent.com/17010094/114395650-8d1ec080-9b94-11eb-930d-072897316eaf.png)
-- | --
</details>

<details>
<summary>Confirmed one time tip to a verified, non KYC'd fails</summary>

![image](https://user-images.githubusercontent.com/17010094/114395704-9ad44600-9b94-11eb-892a-f66f6a04fdd5.png)

</details>

<details>
<summary>Confirmed monthly tip to a KYC'd creator</summary>

![image](https://user-images.githubusercontent.com/17010094/114396182-2a79f480-9b95-11eb-92db-181bd3a1ffd3.png) | ![image](https://user-images.githubusercontent.com/17010094/114403774-fdc9db00-9b9c-11eb-8348-64b8c7a48c36.png)
-- | --

</details>

<details>
<summary>Confirmed monthly tip to a verified, non KYC'd fails</summary>

![image](https://user-images.githubusercontent.com/17010094/114396182-2a79f480-9b95-11eb-92db-181bd3a1ffd3.png) | ![image](https://user-images.githubusercontent.com/17010094/114403841-0b7f6080-9b9d-11eb-8759-fd9ff85ac48b.png) 
-- | --

</details>

<details>
<summary>Confirmed able to do an auto contribute</summary>

![image](https://user-images.githubusercontent.com/17010094/114403540-cc510f80-9b9c-11eb-9227-0785b349a60f.png)| ![image](https://user-images.githubusercontent.com/17010094/114404000-34075a80-9b9d-11eb-8ddd-ddab00659c67.png)
-- | --
</details>

<details>
<summary>Confirmed able to disconnect from Uphold</summary>

![image](https://user-images.githubusercontent.com/17010094/114395736-a0ca2700-9b94-11eb-88fb-d0a7378b53fe.png)

</details>
</details>

---------------
Verification passed on Samsung Tab A with Android 10 running 1.23.69 x64 build

<details>
<summary>Verified test plan from <a href=https://github.com/brave/brave-core/pull/8129#issue-585088560>brave-core/pull/8129 (comment)</a></summary>
<br>
<details>
<summary>Confirmed able to connect Uphold wallet</summary>

![image](https://user-images.githubusercontent.com/17010094/114402791-15ed2a80-9b9c-11eb-8eac-769d2a231474.png)

</details>

<details>
<summary>Confirmed able to do a one time tip to a KYC'd creator</summary>

![image](https://user-images.githubusercontent.com/17010094/114402722-07067800-9b9c-11eb-99d8-b575c7c98aae.png)

</details>

<details>
<summary>Confirmed one time tip to a verified, non KYC'd fails</summary>

![image](https://user-images.githubusercontent.com/17010094/114402722-07067800-9b9c-11eb-99d8-b575c7c98aae.png)

</details>

<details>
<summary>Confirmed monthly tip to a KYC'd creator</summary>

![image](https://user-images.githubusercontent.com/17010094/114402669-f81fc580-9b9b-11eb-9a46-fabf9bc47717.png)

</details>

<details>
<summary>Confirmed monthly tip to a verified, non KYC'd fails</summary>

![image](https://user-images.githubusercontent.com/17010094/114402669-f81fc580-9b9b-11eb-9a46-fabf9bc47717.png)


</details>

<details>
<summary>Confirmed able to do an auto contribute</summary>

![image](https://user-images.githubusercontent.com/17010094/114402639-f0f8b780-9b9b-11eb-9a9f-9ee40952e9b0.png)

</details>

<details>
<summary>Confirmed able to disconnect from Uphold</summary>

![image](https://user-images.githubusercontent.com/17010094/114402791-15ed2a80-9b9c-11eb-8eac-769d2a231474.png)

</details>
</details>
