### ISSUE TITLE
Add site button is not shown by default. Only shows when hovered over

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14480]
## Description 

Add site button is not shown by default. Only shows when hovered over

## Steps to Reproduce

   1. Install nightly
   2. Set toptiles to be favourites
   3. No Add site button is shown until you hover under the stats 

## Actual result:

https://user-images.githubusercontent.com/17010094/110063999-266fe100-7d64-11eb-8574-c6f90b13a82a.mp4

## Expected result:
Should show the add site by default so user knows its there rather than letting the user guess where it will be 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.23.19 Chromium: 89.0.4389.72 (Official Build) nightly (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @rebron @karenkliu

**Comment by stephendonner** [comment]
Verified `PASSED` on `nightly` using build 

Brave | 1.23.25 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)

Verified that when Favorites is selected under Show Top Sites, the Add site icon and text appears when there aren't any sites shown (and when there are, as before).

| Example | Example |
|----------|---------|
<img width="1607" alt="Screen Shot 2021-03-09 at 10 53 02 AM" src="https://user-images.githubusercontent.com/387249/110522458-c495db00-80c5-11eb-8adf-91caa2e50f75.png"> | <img width="1607" alt="Screen Shot 2021-03-09 at 10 51 08 AM" src="https://user-images.githubusercontent.com/387249/110522455-c3fd4480-80c5-11eb-8299-fa5058900f6f.png">
