### ISSUE TITLE
Update wallet icon in settings list to match with sidebar and top navigation 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14489]
## Description 

Update wallet icon in settings list to match with sidebar and top navigation 

## Steps to Reproduce

   1. Install Beta/Nightly build 
   2. Open settings
   3. Wallet uses old icon

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/110088787-351ebe00-7d8d-11eb-9828-65ff9ef24a99.png)

## Expected result:
Same icon everywhere

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.22.49 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Linux

Brave | 1.23.19 Chromium: 89.0.4389.72 (Official Build) nightly (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by rebron** [comment]
Related to: #13688 
cc: @karenkliu

**Comment by rebron** [comment]
Closing as stale. Both toolbar and sidebar are using current and correct wallet icon.
