### ISSUE TITLE
Content of Care.com page is not displayed due to Ad Blockers

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1448]
## Description 

Issue is reported by community:
https://community.brave.com/t/issues-with-care-com-page/34352/2

Content of Care.com page is not displayed due to Ad Blockers. If we select "Allow Ads and Trackers" from shield settings, the content of the page is loading properly

## Steps to Reproduce

   1. Launch brave
   2. Open care.com
   3. Observe that, the spinning circles in the page

## Actual result:
Content of Care.com page is not displayed due to Ad Blockers
![care com content loading issue](https://user-images.githubusercontent.com/38657976/46604090-ad2c1f80-cb12-11e8-941f-9819073eccdb.gif)

## Expected result:
Content of the page should load without changing shield settings

## Reproduces how often: 
Always

## Brave version (chrome://version info)
Brave	0.56.2 Chromium: 70.0.3538.35 (Official Build) dev (64-bit) 
Revision	28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS	Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? -Yes
- Does it reproduce on browser-laptop? -Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - Yes
- Is the issue reproducible on the latest version of Chrome? - No

### Additional Information
@bbondy 
Please note that issue is working fine on latest version of Chrome:
Google Chrome Version 70.0.3538.45 (Official Build) beta (64-bit)

On Chrome 69 version its behaving same as brave:
Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by ryanbr** [comment]
@GeetaSarvadnya  Just reviewing this, seems to be okay. Safe to close ticket?

**Comment by antonok-edm** [comment]
@ryanbr it looks good to me as well.

@GeetaSarvadnya feel free to re-open if you still see the issue.
