### ISSUE TITLE
Newly added site doesn't fetch favicon until the site is visited 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14481]
## Description 

Newly added site doesn't fetch favicon until the site is visited 

## Steps to Reproduce

   1. Install 1.23.19
   2. Add a new favourite and enter `slashdot.org` for URL, no favicon is shown for the tile
   3. Type in slashdot.org in a new tab/same tab and wait till page loads
   4. Open a new tab, Slashdot favourite still doesn't have a favicon even though you visited the page
   5. Click on the favourite added in step 2, page loads
   6. Open a new tab, Slashdot favourite now has a favicon

## Actual result:

Newly added site doesn't fetch favicon until the site is visited 

## Expected result:
Should fetch site favicon when a site is added/visited by typing the URL

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.23.19 Chromium: 89.0.4389.72 (Official Build) nightly (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @karenkliu @simonhong @bsclifton

**Comment by rebron** [comment]
cc: @fmarier Just in case but I don't think there'd be any favicon privacy related issues here. I'm leaning towards wontfix on this one though. Somewhat of a corner case and favicon does show upon site visit and refresh of new tab page.

**Comment by fmarier** [comment]
Seems to be an upstream bug.

Before visiting:
![Screenshot from 2021-03-05 17-45-22](https://user-images.githubusercontent.com/167821/110190927-a6d12900-7dda-11eb-898d-9f8d89f552a5.png)
After visiting:
![Screenshot from 2021-03-05 17-45-36](https://user-images.githubusercontent.com/167821/110190928-a769bf80-7dda-11eb-843f-78009058778a.png)

**Comment by waveman777** [comment]
I'm not sure if this is related, but I noticed that when I reopen Brave's last session, all the tab favicons are gone. They only lead again when I visit the site. Very annoying.

**Comment by bsclifton** [comment]
Closing as `wontfix`. As noted above, upstream has this too. If the favicons were fetched on launch, the sites hosting the favicons can detect the user has them bookmarked (if they didn't visit the page).
