### ISSUE TITLE
[CW] Wallet crashes while component is updating 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14498]
## Description 

[CW] Wallet crashes while component is updating 

## Steps to Reproduce

- Install Dev component 1.0.23 and create a wallet
- Launch browser with --use-dev-goupdater-url
- Login/Unlock to CW account while component updates in background
- Lock account and import wallet from welcome back screen
- Use drip caution abandon festival order clown oven regular absorb evidence crew where to import account
- Wait for a couple of mins and then CW tab crashes
- Restart browser no crash

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/110143402-22c57400-7dcf-11eb-82ed-ad3d4c037ca9.png)

## Expected result:
No extension crash

## Reproduces how often: 

Highly intermittent issue. I saw it happen twice

## Brave version (brave://version info)

Brave | 1.22.49 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision |` 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Maybe, I didn't see extension crash
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Maybe, I didn't see extension crash

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by iefremov** [comment]
@srirambv do you have anything on `brave://crashes`?

**Comment by srirambv** [comment]
nope i didn't check for crashes and not able to repro on the same profile. Will try to get logs if I run into the issue again

**Comment by srirambv** [comment]
Closing the issue as I have not been able to repro the issue for a while now.
