### ISSUE TITLE
[Android] Crash on closing tab with Tab Groups enabled

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#14491]
## Description 
There is a crash on closing tab with Tab Groups enabled.

## Steps to reproduce 

   1. Go to `brave://flags`
   2. Enable Tab Groups and relaunch app twice to apply changes.
   3. Try to close tab, it will crash.

## Actual result 
Crash

## Expected result
No crash

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.21.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using the following build:

```
1.21.74 CR: 89.0.4389.72
```

* reproduced the original issue via `1.21.73 CR: 89.0.4389.72` by enabling `Tab Groups` as per the STR/Cases from https://github.com/brave/brave-browser/issues/14491#issue-823056897
* enabled  `Tab Groups` via `brave://flags` using `1.21.73 CR: 89.0.4389.72` and ensured that updating to `1.21.74 CR: 89.0.4389.72` fixes the crash
* enabled `Tab Groups` via `brave://flags` on a new `1.21.74 CR: 89.0.4389.72` install and ensured Brave wasn't crashing when closing tabs.

**Comment by kjozwiak** [comment]
Couldn't reproduce the above using a tablet using `1.21.73 CR: 89.0.4389.72`. Looks like `Tab Groups` under `brave://flags` specifically mentions this is a phone feature. Adding `android-phone-specific`.
