### ISSUE TITLE
IPFS URI should be loaded over localhost, not 127.0.0.1

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14499]
## Description 
IPFS URI should be loaded over `localhost`, not `127.0.0.1`

## Steps to Reproduce

1. Install IPFS Desktop and it should be started on port 8080
2. Load `http://127.0.0.1:8080/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS`. It should load the content but retain the `https://localhost/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS` URI in the address bar.

## Actual result:

The URI is `http://127.0.0.1:8080/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS`

<img width="1170" alt="Screen Shot 2021-03-05 at 8 23 36 AM" src="https://user-images.githubusercontent.com/387249/110143650-4c10e080-7d8c-11eb-9b70-a1d7eaffd08a.png">

## Expected result:

According to https://github.com/brave/brave-browser/issues/13872#issuecomment-772122425, the URI should be https://localhost/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS, with `localhost` rather than `127.0.0.1`

## Brave version (brave://version info)

Brave | 1.23.19 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc: @spylogsster @lidel

**Comment by lidel** [comment]
This is a sensible request and a security fix (raw IP can't have subdomains, so it won't provide origin isolation).
IPFS Companion enforces use of `localhost` by default, because that is the only way to provide origin isolation per CID.

**Comment by spylogsster** [comment]
@lidel I added replacement 127.0.0.1 to localhost for default gateway. If we setup the public gateway to http://127.0.0.1:8080/, the url will be converted to localhost, but the address bar finally will retain `ipfs://bafybeiddzzce2l4stkz6fotj7hugeyehtv3kobcku2jvrakgpiqgx4j6fe/ `

**Comment by stephendonner** [comment]
Verified `FIXED` using `beta` build with the testplan from https://github.com/brave/brave-core/pull/8263

Brave | 1.23.43 Chromium: 89.0.4389.90 (Official Build) beta (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. Install IPFS Desktop and it should be started on port 8080
2. Setup public gateway to `http://127.0.0.1:8080/`
3. Load `http://127.0.0.1:8080/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS`
4. It should load the content but retain the `ipfs://bafybeiddzzce2l4stkz6fotj7hugeyehtv3kobcku2jvrakgpiqgx4j6fe/`

Verified when I loaded `http://127.0.0.1:8080/ipfs/QmV4FVfWRG4hJJKUsS1aU9MK85HYFJtuCmYAj8HetS8qMS` that it redirected to/retained `pfs://bafybeiddzzce2l4stkz6fotj7hugeyehtv3kobcku2jvrakgpiqgx4j6fe/` in the URL bar.

![ipfs-gateway](https://user-images.githubusercontent.com/387249/111500827-a5203300-8701-11eb-8912-74dbc464e4ba.gif)
