### ISSUE TITLE
Shut off Open Search additions to "Other search engines" by default

### ISSUE THREAD

**Issue by posita** [brave/brave-browser#14496]
As I browse, additional entries are silently inserted into `Other search engines` periodically. There is no notice that I can see. As far as I can tell, I have no opportunity to consent to this settings manipulation. As a user, even after reasonable inquiry, I have no idea that this is happening, much less how, or how to stop it.

Users should be empowered to turn this off, and I would argue it should be off by default. I should not have to manually and continually poll brave://settings/searchEngines to "discover" new or reappearing entires only to have to manually remove (and re-remove) them.

---

_Also originally reported with this issue:_ ~Despite_ me deleting them every single time I notice their presence, Bing and Google are re-added to my `Default search engines` list. I haven't done enough testing to figure out what triggers this (i.e., whether it's upgrading Brave, relaunching it, or navigating to certain pages, etc.), but it keeps happening. This is disturbing, since I've signaled an intent that they should not appear. They should only come back if I signal intent to restore the default settings or add them explicitly.~ _UPDATE: I will file a separate issue to track this when I observe it again and can provide more details._

**Comment by diracdeltas** [comment]
cc @bsclifton - not sure how much if any of this is intentional

**Comment by posita** [comment]
Following up with some additional investigation. I recently visited Home Depot and discovered that visit resulted in this addition to my search engines:

![screenshot](https://user-images.githubusercontent.com/222581/110869659-7da81100-8290-11eb-9e71-1f648d4a44cc.png)

There are six characters after the `?` in the URL which I have redacted. I don't know whether they are a tracking ID or what their purpose is. Due to the width of my screen, those six characters were not visible to me in the brave://settings/searchEngines screen. I had to click on the vertical ellipsis to expose that URL (and capture the attached screenshot).

This is disconcerting, since it's not super crazy for me to type something like `site.dom coupon code` or something similar into my nav bar. In _**this**_ case, because of this clandestine addition, if I used that pattern with `homedepot.com`, I would not only be directed to searching their site (which would be annoying and confusing), but I _**also**_ may be being tracked in the process (which I would emphatically not want).

**Comment by posita** [comment]
> … - not sure how much if any of this is intentional

I'm not sure intention matters here. This seems like an attack surface that needs to go away. At the very least, it needs to involve user consent before modifying state. In **_addition_**, I would strongly advocate for users to be able to turn this off entirely (and have that be the default).

Although, I may have misunderstood your comment. Are you saying this isn't behavior intended by Brave developers (and may be inherited from the underlying Chromium implementation)?

**Comment by bsclifton** [comment]
@posita this behavior is inherited from Chromium - to be clear, it's not something we added. It's Chromium's search integration using the Open Search spec. You'll notice the same behavior in Chromium or Chrome

Any web page (home depot, etc) that exposes a search will be detected and add itself under the `Other search engines`. The intention is that users can find one they like and then easily make it the default without having to click `Add` and put together the URL themselves (with the `%s` in it)

You bring up a good point - this behavior should be optional. We can absolutely put a toggle around this behavior and stop this from happening when disabled. I can help you reword the original top post, if that captures your concern? Please let us know 😄 

@rebron @diracdeltas if this was a toggle, what would you think about having this disabled by default?

**Comment by bsclifton** [comment]
@posita quick follow up on the first question (apologies I missed that). With the `Default search engines` list, this is rebuilt on occasion. This behavior is also inherited from Chromium - I'd need to check the logic to be extra sure, but I believe it will rebuild these entries when a new profile is created OR when the list is updated (ex: new entry added). However, I didn't realize that it's adding it back - that is definitely a bug. If you can confirm that I can make a separate issue to track that

**Comment by posita** [comment]
> … However, I didn't realize that it's adding it back - that is definitely a bug. If you can confirm that I can make a separate issue to track that

The truth is that it's something I've observed, but not carefully, so I'm not super confident about when it it occurs. Let me watch out for it, and if I see it again, and I know it's not one of the cases you mentioned, I'll file a separate issue to track that.

**Comment by posita** [comment]
> …
> 
> You bring up a good point - this behavior should be optional. We can absolutely put a toggle around this behavior and stop this from happening when disabled. I can help you reword the original top post, if that captures your concern? Please let us know 😄
> 
> @rebron @diracdeltas if this was a toggle, what would you think about having this disabled by default?

@bsclifton, I tweaked the title and the original top post. Let me know if it concisely captures what you'd like. I can edit further, if desired.

**Comment by diracdeltas** [comment]
> @rebron @diracdeltas if this was a toggle, what would you think about having this disabled by default?

@bsclifton that seems fine to me. i've only used this feature once and my sense is that most users don't know it exists.

**Comment by bsclifton** [comment]
Original post looks great, @posita 😄 Thanks for taking the time to explain clearly and update

I marked this with privacy label as this also gives clues to browsing history (I believe these persist even after clearing history).

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.44 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:
1. clean profile
2. loaded `brave://settings/search`
3. verified that the new `Index other search engines` preference is showing and is turned OFF by default
4. visited a few sites (`amazon.com`, `homedepot.com`, `bestbuy.com`) and searched
5. verified they **DO NOT** show up under `Other search engines` on `brave://settings/searchEngines`
6. visited `brave://settings/search`
7. enabled the `Index other search engines` setting
8. visited sites from step 4
9. verified now the sites **DO** show up under `Other search engines` on `brave://settings/searchEngines`

Steps 1-5 | Steps 6-9
----------|-----------
<img width="1312" alt="Screen Shot 2021-08-24 at 9 57 35 AM" src="https://user-images.githubusercontent.com/387249/130663689-d8cec8a9-5ac0-4c1d-a7c6-84c5d36a5420.png"> | <img width="1312" alt="Screen Shot 2021-08-24 at 10 35 00 AM" src="https://user-images.githubusercontent.com/387249/130663726-f2c19602-5e7d-45fd-80db-792020a7e6bc.png">

**Comment by Madis0** [comment]
You might want to mark #867 as fixed as well.

**Comment by bsclifton** [comment]
@Madis0 thanks! Closed the other as a duplicate 😄

**Comment by UjCbFwtBayFM** [comment]
> Or are you saying that you regularly install from scratch weekly and the way you populate the 30+ search engines you use is by surfing to those sites after installing? If I've described that accurately, I'd definitely look into Brave's sync feature as @bsclifton suggests. That will help you out a _lot_. It will also help address all the _other_ settings you typically have to work through for each installation (e.g., extensions, bookmarks, privacy settings, etc.).

I don't use Sync. I tried it once, but it didn't (and I think it still doesn't) include Rewards and didn't work properly (didn't sync things that were supposed to be synced and adding unknown devices to it over time).

**Comment by posita** [comment]
> I tried it once, but it didn't (and I think it still doesn't) include Rewards and didn't work properly (didn't sync things that were supposed to be synced and adding unknown devices to it over time).

If you haven't already, you might consider filing those as separate issues. It sounds like if those were addressed, it would largely get you where you need to go? Not sure. This conversation feels a bit like a moving target, although it sounds like @bsclifton is trying his best to translate from your needs as a user to the specific things that might need to be addressed on the application side.

**Comment by UjCbFwtBayFM** [comment]
> If you haven't already, you might consider filing those as separate issues. It sounds like if those were addressed, it would largely get you where you need to go? Not sure. This conversation feels a bit like a moving target, although it sounds like @bsclifton is trying his best to translate from your needs as a user to the specific things that might need to be addressed on the application side.

I guess I could, but it'd loose the exposure they have here.

**Comment by AJolly** [comment]
Is there a group policy or registry setting I can set to automatically keep this on? Or better yet, to add a default search (kagi) to my browser?

**Comment by bridiver** [comment]
@AJolly I just stumbled across this because I didn't know what the toggle did in prefs and I agree this seems strange to disable by default. Seems ok to have an option to disable it, but I don't know why we would disable by default. @diracdeltas @ShivanKaul ?

**Comment by bridiver** [comment]
Also separately I think we should change the wording on this because I had no idea what it did. Maybe "Disable adding search engines discovered through OpenSearch protocol"

**Comment by posita** [comment]
> Is there a group policy or registry setting I can set to automatically keep this on? Or better yet, to add a default search (kagi) to my browser?

@AJolly, this (closed) issue is not about default search engines. It's about websites silently installing their own search engines when users merely visit those websites.

> ... I agree this seems strange to disable by default. Seems ok to have an option to disable it, but I don't know why we would disable by default. ...

Because enabling it means that arbitrary websites can silently insert their own "search engines" to intercept user queries and do goodness-knows-what with them. This feature means that just by visiting a website, Brave will automatically and silently modify the paths by which user searches are performed. That's not only a violation of user agency, it's a security risk. @bsclifton does an excellent job of highlighting this in his https://github.com/brave/brave-browser/issues/14496#issuecomment-951592493.

A core tenet of security is to fail/default closed. (As an aside, enabled-by-default is how Cisco has provided the world with literally millions of devices ripe for being abused as DoS farms. See [Security Now #1054](https://www.grc.com/sn/sn-1054.pdf).) If _**you**_ want that behavior in _**your**_ browser, _**you**_ can turn it on in the settings without subjecting every single other Brave user to exposure. The only reason I can think of to want it on-by-default is if you or constituencies you care about want to start inserting your search interceptor into _**everyone else's**_ browser.

> ... I think we should change the wording on this because I had no idea what it did. Maybe "Disable adding search engines discovered through OpenSearch protocol"

It sounds like this would have to be done upstream in Chrome, since that's the source of this "feature". Maybe file an issue with that project and submit a PR to clarify the language?

**Comment by bridiver** [comment]
> Because enabling it means that arbitrary websites can silently insert their own "search engines" to intercept user queries and do goodness-knows-what with them. This feature means that just by visiting a website, Brave will automatically and silently modify the paths by which user searches are performed

I don't believe this is an accurate description. The sites are added to the list of other search engines, but the sites cannot intercept anything. They only receive search queries you direct to them and they are inactive by default so the only thing this toggle prevents is adding them to a list in settings of sites that you can activate if you wish. Even if you activate them, they only receive queries that you direct to them by using the shortcut (defaults to the domain) and then type search keywords you want to send. This is also very obvious in the urlbar so I don't see any privacy concerns here, but I'll let @diracdeltas and @ShivanKaul weight in

<img width="698" height="161" alt="Image" src="https://github.com/user-attachments/assets/77ec0b86-d251-4d2d-a805-56c18106ec73" />

<img width="296" height="38" alt="Image" src="https://github.com/user-attachments/assets/9ee1620e-e014-4a3b-818d-9a9878fc7820" />

**Comment by bridiver** [comment]
This is actually a really nice feature imo and while I don't necessarily see any issue with having a toggle to disable automatically adding them to the list, it seems purely cosmetic and I don't see any issues here that would justify deviating from the chromium default value

**Comment by bsclifton** [comment]
@bridiver the problem was when you have this enabled by default and you accumulate a decent sized browsing history.

You'll eventually end up with a hundred or so "search engines" for sites you visit. You may clear history, but a person can look at these engines discovered and get a decent idea of the ecommerce, blog sites, etc that you visit.  

As mentioned, these OpenSearch discovered engines also had an interception point in the omnibox. They can be considered a source there and the person can arrow up/down to choose searching with that engine. Let's say you're sharing your screen and you (or someone using your computer) had visited a website `offensive-link.com` (or something like that) which had an OpenSearch manifest.  Now, as you type `restaurant in arizona` in your omnibox, everyone watching your screen share will see this domain that you had visited once as a choice you can arrow down and select (`restaurant in arizona - offensive-link.com`).

Originally, the ask was done here for "should this be off by default?" where @diracdeltas responded
https://github.com/brave/brave-browser/issues/14496#issuecomment-797733599

**Comment by bsclifton** [comment]
I think we can remove this functionality now - the behavior it's guarding is obsolete.

Google themselves confirmed they removed this functionality here:
https://x.com/googlechrome/status/1504858912692084745

Upstream tracked the problem with https://issues.chromium.org/issues/40088547 - but I didn't see any CLs linked where it was removed. Comment 92 captures:
> No manual test required because the technical changes have already been verified. chrome://settings/searchEngines was redesigned. Engines are no longer activated automatically. The user can dig in and activate selected engines if desired, but they're inactive when added, and tucked under a group header so the active engines are easy to see and work with.

Ultimately closed as `Fixed`.

**Comment by bridiver** [comment]
I see, so I guess upstream functionality has changed since this was added. This started from me trying to figure out what this was because the text was unclear and once I tracked it down it seemed a bit odd, but I guess it made more sense at the time it was added
