### ISSUE TITLE
Implement referrer and cookie blocking

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#145]
- [x] Enhance brave-extension to make the cookie control drop down work
- [x] Implement the default blocking rules for each
- [x] Implement exceptions for `cookieExceptions` and `refererExceptions` per [this](https://github.com/brave/browser-laptop/blob/master/js/data/siteHacks.js#L28).

**Comment by bbondy** [comment]
QA notes:
For referrer make sure we mask to same site referrer for iframes loaded in a parent page. Also for links clicked from an https site to an https site.
For cookie blocking, there's a couple issues open, so pls only post new ones if new.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified searching for whatismyreferer on google and opening the site shows same domain as HTTP referrer
