### ISSUE TITLE
Brave creates a new profile, "Profile 1"

### ISSUE THREAD

**Issue by MahdiNazemi** [brave/brave-browser#14504]
## Description 

Every once in a while, Brave creates a new profile, "Profile 1". After removing the profile, it comes back after a few hours.

## Steps to Reproduce

I am not sure when such a profile is created but I suspect it is related to private browsing.

## Reproduces how often: 

Every few hours.

## Brave version (brave://version info)

Brave | 1.21.73 Chromium: 89.0.4389.72 (Official Build) (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 10.15.7 (Build 19H524)

I have been experiencing this issue on older versions too.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel?  I do not know.
- Can you reproduce this issue with the nightly channel?  I do not know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards?  No.
- Is the issue reproducible on the latest version of Chrome? I do not know.

## Miscellaneous Information:
I have seen this issue on the Brave forum and elsewhere (which go back to 2019), e.g.:
[https://community.brave.com/t/new-profile-magically-created/117479](https://community.brave.com/t/new-profile-magically-created/117479)
[https://www.reddit.com/r/brave_browser/comments/hu6bgh/brave_creates_a_new_user_profile_several_times_a/](https://www.reddit.com/r/brave_browser/comments/hu6bgh/brave_creates_a_new_user_profile_several_times_a/)
[https://www.reddit.com/r/brave_browser/comments/btoibq/how_do_i_stop_person_1_profile_from_creating/](https://www.reddit.com/r/brave_browser/comments/btoibq/how_do_i_stop_person_1_profile_from_creating/)

**Comment by bsclifton** [comment]
+1 from https://twitter.com/sergeybedritsky/status/1372308967691522049
> Brave keeps creating Person 1 profile, while I have multiple other named profiles, that I actually use. Don't remember such behaviour in Chrome

Confirmed with the following steps:
1. New profile (never used before)
2. Use hamburger menu => `Create a new Profile`
3. Name your profile (ex: `Brian`)
4. Go to profile manager (ex: profile icon, click gear next to `Other profiles`)
    ![image](https://user-images.githubusercontent.com/4733304/111584487-27007280-877b-11eb-8dc9-48e0994e244a.png)
5. Click the almost invisible `...` in the top right of `Profile 1` and pick `Remove profile`
    ![image](https://user-images.githubusercontent.com/4733304/111584602-4bf4e580-877b-11eb-9600-233e29f36c4b.png)
6. Profile gets deleted 🎉 
7. Close Brave and re-open
8. Profile is re-added 🙀

**Comment by bsclifton** [comment]
Dug around our issue log some more and found the original report of this bug - will close this issue as a duplicate

Please subscribe to https://github.com/brave/brave-browser/issues/4599 for updates!
