### ISSUE TITLE
Brave Rewards offers opting in during private or tor session

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#1450]
## Description 
This is concerning the availability of Rewards during private or tor sessions. 

Currently, in private/tor, a user can go to the rewards page through the menu and see the opt-in screen. The opt-in button is clickable but does not active rewards in tor/private mode. 

If a user has already created a wallet and is in private/tor mode, going to the rewards screen shows the opt-in screen. button is clickable but no action is taken.

If a user has not create a wallet and uses the rewards panel in private/tor to "Join Now", a wallet is created (somewhere, it does not appear the state files are pushed to the Default folder). This process repeats in the other private or tor side. (i. e. This can be done in tor and then again in private mode, however only the private panel create will create a wallet that is linked to the Default profile

STRs below for clarity

## Steps to Reproduce

   1. Open Brave with clean profile.
   2. Open private window and go to rewards through menu
   3. The rewards screen shows the opt-in page and cannot be bypassed

-

   1. Open Brave with clean profile and enable rewards.
   2. Open private window and go to rewards through menu
   3. The rewards screen shows the opt-in page and cannot be bypassed

-

   1. Open Brave with clean profile and enable rewards.
   2. Open tor window and go to rewards through menu
   3. The rewards screen shows the opt-in page and cannot be bypassed

-

   1. Open Brave with clean profile.
   2. Open private window and click on rewards extension panel.
   3. Click "Join Now" on the rewards extension panel
   4. Try to go to rewards through menu
   5. The rewards screen shows the opt-in page and cannot be bypassed
   6. Go to rewards screen through a non-private/non-tor window
   7. Notice the wallet was successfully created from the private window's Rewards panel

-

   1. Open Brave with clean profile.
   2. Open tor window and click on rewards extension panel.
   3. Click "Join Now" on the rewards extension panel (if console is open, take note of the paymentid)
   4. Try to go to rewards through menu
   5. The rewards screen shows the opt-in page and cannot be bypassed
   6. Go to rewards screen through a non-private/non-tor window
   7. The opt-in screen is shown
   8. Close Brave completely and reopen
   9. Go to Rewards, Opt In page is shown
   10. Open tor window and click on Rewards panel and note that wallet summary is displayed
   11. Open rewards in non-private window and Opt-in to Rewards
   12. A new wallet separate from the tor-wallet is created (if console is open take note that this will be a different paymentid)
   13. Closing and reopening Brave and open regular rewards and the tor rewards panel indicates that two wallets have been created. (There is still a question of where the state files for the tor created wallet go)

@davidtemkin @mandar-brave What has the discussion been on the availability of Rewards windows in private/tor mode? Currently we have verified that we are not tracking any sites for rewards purposes (i.e. not listing sites in auto-contribute etc), however there seems to be some inconsistency in the private and tor modes. Currently can't get to the rewards screen but we can access some wallet properties in the rewards panel. 

Ultimately, the question is, should rewards screens be working properly in private/tor windows or should they be disabled from users during private/tor sessions?

## Reproduces how often: 
always

## Brave version (chrome://version info)
57.1

### Reproducible on current release: YES
- Does it reproduce on brave-browser dev/beta builds? YES
- Does it reproduce on browser-laptop? NA

### Website problems only:  NA
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Discovered during https://github.com/brave/brave-browser/issues/1232

**Comment by mandar-brave** [comment]
On any of the private-tab or Tor sessions;
For GA - remove the Brave logo from the chrome to prevent user engagement 
For v1.0 - remove all BR/Ads panel settings from the hamburger menu (OK to leave it as is for GA if it cant be done in that timeframe)

**Comment by davidtemkin** [comment]
is anything beyond "don't count attention while in Tor mode" really needed?

**Comment by srirambv** [comment]
@jasonrsadler does this issue resolve the steps recorded here https://drive.google.com/file/d/1qa3Cv-WwE_wPXJxhaakhT6tKOrq39BY4/view?usp=sharing ?

**Comment by jasonrsadler** [comment]
Yes. That illustrates the STRs

**Comment by NumDeP** [comment]
Has nobody here wanted to add a site to the rewards/contribution page whilst on Tor? I have many a time on Muon and even still new to beta but Core as well.

I was about create a topic titled 'BAT widget in Tor should at least allow a user to include a site to Rewards/contribution page more quickly' but didn't due to the above 1484 - it seems inefficient for users to reopen the exact site again and wait for the minimum time and relevancy every time you want to contribute to page whilst on Tor.

I think enabling the BAT widget to allow one simple function of including just the site without the analytics seems appropriate in terms of efficiency. This way I can simple click inclusion into contributions if I ever reformatted system, uninstalled apps and other situations after I installed Brave again.

**Comment by mandar-brave** [comment]
@tomlowenthal please review comment ^

**Comment by mandar-brave** [comment]
We will tackle this once Brave Rewards stabilizes.

**Comment by NejcZdovc** [comment]
closing as this is not possible anymore. If you click on rewards item in the menu in private window, you are redirected to regular window
