### ISSUE TITLE
follow-up to #12203 reduce dialog frequency to display twice

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#14502]
## Description 
Default browser dialog prompt frequency is 2nd, 3rd, 4th, 8th and 20th launches. This is too frequent and 2nd, 4th, and 8th dialog prompts should be removed.

## Steps to Reproduce
See test plan:
brave/brave-core#7716

## Expected result:
Only show prompt at 3rd and 20th browser open.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)
Brave | 1.21.73

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related: #12203

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
Revision	3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS	Linux
```

Verified test plan from https://github.com/brave/brave-core/pull/8150.

Confirmed when Brave is not the default I am shown the default browser dialog on 3rd and 20th launches.
Confirmed when Brave is the default I am not shown the default browser dialog on the 3rd and 20th launches.
