### ISSUE TITLE
Two duplicate "Entertainment" feeds in Brave News; one misspelled

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14509]
## Steps to Reproduce

   1.  set your OS language to Japanese
   2.  load Brave News by scrolling in the new-tab page
   3.  find the "customize" (in Kanji) button, click it
   4. scroll through the content-feed choices

## Actual result:

There are two "Entertainment" feeds; one misspelled as `Entertaiment`, and the other correctly spelled.  Both appear to have identical sources listed within.

<img width="892" alt="スクリーンショット 2021-03-05 午後2 56 02" src="https://user-images.githubusercontent.com/387249/110183221-408cdc00-7dc3-11eb-8d83-bff19514b119.png">

<img width="892" alt="スクリーンショット 2021-03-05 午後2 56 16" src="https://user-images.githubusercontent.com/387249/110183195-31a62980-7dc3-11eb-9ece-028e35e12b5b.png">

## Expected result:

Only one correctly spelled "Entertainment" feed present.

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.23.21 Chromium: 89.0.4389.72 (Official Build) nightly （x86_64）
-- | --
変更履歴 | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS バージョン11.2.2（ビルド20D80）

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

**Comment by mattmcalister** [comment]
Resolved. Closing issues.
