### ISSUE TITLE
Rename brave://ipfs to brave://ipfs-internals

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14500]
brave://ipfs should not be used for primary IPFS UI, and just for diagnostics.

This issue is to:
1) Rename brave://ipfs to brave://ipfs-internals
2) Redirect navigations to brave://ipfs to brave://ipfs-internals

Dev note:

You can do the redirect like the win10 redirect below
```
// [static]
bool BraveContentBrowserClient::HandleURLOverrideRewrite(GURL* url,
    content::BrowserContext* browser_context) {

  if (url->host() == chrome::kChromeUISyncHost) {
    GURL::Replacements replacements;
    replacements.SetHostStr(chrome::kChromeUISettingsHost);
    replacements.SetPathStr(kBraveSyncPath);
    *url = url->ReplaceComponents(replacements);
    return true;
  }

  // no special win10 welcome page
  if (url->host() == chrome::kChromeUIWelcomeHost) {
    *url = GURL(chrome::kChromeUIWelcomeURL);
    return true;
  }

```

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.23.43 Chromium: 89.0.4389.90 (Official Build) beta (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 10.15.7 (Build 19H524)
```

Verified test plan from https://github.com/brave/brave-core/pull/8217#issue-590742094
Confirmed navigation to brave://ipfs is redirected to brave://ipfs-internals
Confirmed able to directly navigate to brave://ipfs-internals

<img width="1034" alt="Screen Shot 2021-03-17 at 9 11 41 AM" src="https://user-images.githubusercontent.com/28145373/111472889-cdf3f880-8700-11eb-8ba6-11d795de0401.png">

--------------------
