### ISSUE TITLE
Repository name is not displayed properly on GitHub

### ISSUE THREAD

**Issue by muhfaris** [brave/brave-browser#14515]
## Description 

The repository name in Github not properly in normal mode, when I try to use private mode is no problem.

## Steps to Reproduce

I don't know what happens.

## Actual result:

![image](https://user-images.githubusercontent.com/16787866/110190314-3d423080-7e55-11eb-8372-2d62a2b6ad07.png)

## Expected result:
![image](https://user-images.githubusercontent.com/16787866/110190364-7ed2db80-7e55-11eb-8f71-d3eb2410d957.png)

## Brave version (brave://version info)

v 1.21.73

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
yes, but still a problem

- Does the issue resolve itself when disabling Brave Rewards? 
yes, but still a problem

- Is the issue reproducible on the latest version of Chrome? 
yes, no problem with the latest version of Chrome 

## Miscellaneous Information:

What have I done?
- I have tried to clear cache/data for Github
- I have tried to clear cache/data browser
- I have tried to clear the CSS of the Github site

But, the problem still.

**Comment by bsclifton** [comment]
@muhfaris I ran into this myself - this is almost certainly an extension issue. Can you please share what extensions you have enabled? Do you have a translation one enabled? You can troubleshoot by visiting brave://extensions and disabling one-by-one

**Comment by muhfaris** [comment]
@bsclifton thanks for your replay,
You right, the issue in extenstion [Lingvanex - Translator and Dictionary](https://chrome.google.com/webstore/detail/lingvanex-translator-and/kdamfjkjgaidaigdfelkpgdnbigclccc?hl=en)
solved with disable the extension

**Comment by bsclifton** [comment]
Perfect! Thanks @muhfaris - that's the same extension I ran into problems with. It also has the same problem in Chrome unfortunately (and likely Edge/others)
