### ISSUE TITLE
Moving Unstoppable Domains & ENS resolve settings into wallet settings

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#14516]
They're currently under Extensions, might makes more sense in wallet settings.
https://github.com/brave/brave-core/pull/8125#discussion_r588818862

**Comment by rebron** [comment]
cc: @karenkliu

**Comment by bbondy** [comment]
@rebron @karenkliu How about a new DNS category after IPFS?

We currently have these 2 settings:
<img width="677" alt="Screen Shot 2021-03-13 at 7 33 44 PM" src="https://user-images.githubusercontent.com/831718/111053590-0eb6ed80-8433-11eb-961f-029fcfba6c6e.png">

We'll also likely have another setting for Handshake.
And then also a 4th option which asks which provider (if any) to use for resolving non-ICANN TLDs.

**Comment by karenkliu** [comment]
@bbondy Maybe under Wallet? Have to be wary of being too granular and adding too many sections that don't have much content. Let's think about broader themes these could fit under.

**Comment by bbondy** [comment]
OK sounds good, I think it's a better fit than under extensions at least 👍

**Comment by ShivanKaul** [comment]
Let's make sure the ENS L2 resolution setting (in-dev) also gets migrated when this is worked on. We'll also need to update documentation (https://github.com/brave/brave-browser/wiki/ENS-offchain-lookup, or wherever that moves)

**Comment by supermassive** [comment]
Now we have four rows related to domain resolution in brave://settings/extensions
![image](https://user-images.githubusercontent.com/168356/205881634-f92106de-9f41-4ba2-baa4-da2b25268d0b.png)
and this issue blocks sec review https://github.com/brave/security/issues/1099#issuecomment-1335733756

Can we choose a new location for them?
1) Move them to Wallet section.
2) 1 + rename Wallet to smth like Wallet and Web3
3) Move them to a new Web3 section.

@bbondy @bradleyrichter @aguscruiz @ShivanKaul

**Comment by bbondy** [comment]
I think we should have a web3 settings page and then have different sections, one for wallet, one for decentralized DNS, one for IPFS, etc.

**Comment by bradleyrichter** [comment]
Mockup for a merger
![image](https://user-images.githubusercontent.com/13509546/206008137-8041b4b6-7c11-4e05-a4f4-06a43c5f29db.png)

**Comment by ShivanKaul** [comment]
+1

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit) 
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [brave/brave-core#16290](https://github.com/brave/brave-core/pull/16290)
- Verified UD, ENS & SNS are moved under `Web3 -> Web3 Domains`
- Verified still able to navigate to Wallet networks and enable/disable network
- Verified navigation to `Ipfs peers` and `Ipns keys` still work as expected
- Verified disable policy works as expected

https://user-images.githubusercontent.com/17010094/214093013-74f69ec2-63d4-4aa7-8093-bbdb4fe7503c.mp4

---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16290](https://github.com/brave/brave-core/pull/16290)
- Verified UD, ENS & SNS are moved under `Web3 -> Web3 Domains`
- Verified still able to navigate to Wallet networks and enable/disable network
- Verified navigation to `Ipfs peers` and `Ipns keys` still work as expected
- Verified disable policy works as expected

https://user-images.githubusercontent.com/17010094/214093114-7fb2c35d-623d-4721-901d-9662fefd0128.mp4

---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16290](https://github.com/brave/brave-core/pull/16290)
- Verified UD, ENS & SNS are moved under `Web3 -> Web3 Domains`
- Verified still able to navigate to Wallet networks and enable/disable network
- Verified navigation to `Ipfs peers` and `Ipns keys` still work as expected
- Verified disable policy works as expected

https://user-images.githubusercontent.com/17010094/214093516-9515f3a2-8b9c-4d26-9e00-258a9621c646.mov
