### ISSUE TITLE
The Tor daemon can get into a bad state and break Tor windows

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#14518]
I collected a browser profile from a user on Mac Catalina 10.15.7 who is unable to use Tor windows in 1.21.73. All he sees in `brave://tor-internals` is:
```
Mar 04 09:28:01.000 [notice] Tor 0.4.5.6 opening new log file.
Mar 04 09:28:01.248 [notice] We compiled with OpenSSL 1010109f: OpenSSL 1.1.1i  8 Dec 2020 and we are running with OpenSSL 1010109f: 1.1.1i. These two versions should be binary compatible.
Mar 04 09:28:01.254 [notice] Tor 0.4.5.6 running on Darwin with Libevent 2.1.11-stable, OpenSSL 1.1.1i, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Mar 04 09:28:01.254 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Mar 04 09:28:01.254 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Mar 04 09:28:01.263 [notice] Opening Socks listener on 127.0.0.1:0
Mar 04 09:28:01.264 [notice] Socks listener listening on port 56449.
Mar 04 09:28:01.264 [notice] Opened Socks listener connection (ready) on 127.0.0.1:56449
Mar 04 09:28:01.264 [notice] Opening Control listener on 127.0.0.1:0
Mar 04 09:28:01.264 [notice] Control listener listening on port 56450.
Mar 04 09:28:01.264 [notice] Opened Control listener connection (ready) on 127.0.0.1:56450
Mar 04 09:28:01.000 [notice] Bootstrapped 0% (starting): Starting
Mar 04 09:28:02.000 [notice] Starting with guard context "default"
Mar 04 09:28:02.000 [notice] New control connection opened from 127.0.0.1.
Mar 04 09:28:02.000 [notice] Catching signal TERM, exiting cleanly.
```

@darkdh took a look and found that it is affected by some states in the `tor/data` folder. The circuit cannot be established and gets stuck in the bootstrapping phase at 0%. After deleting the folder, it returns to normal.

We can't clear the `tor/data` directory on startup because it would cause long delays in creating new Tor circuits, but perhaps we can clear that directory on **update**.

Right now, users can't recover from this state without blowing away their profile. If we could fix these problems automatically for them on update, then the recovery would be automatic, at the cost of longer circuit creation for everyone (only after an update though).

**Comment by btlechowski** [comment]
`QA/Blocked` till we get the data needed to perform verification.

**Comment by btlechowski** [comment]
Removed `QA/Blocked` as the data has been shared

**Comment by stephendonner** [comment]
**Verified `PASSED`** using the testplan from https://github.com/brave/brave-core/pull/8714 with build 

Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

### Steps:

#### Initialization stuck

<details>

1. obtained the profile with the bad tor state from @fmarier 
2. copied the tor/data from step 1 to user_data_dir to replace the original one
3. opened a new Tor window and experienced the stuck initialization (`disconnected` state) and saw the tip message
4. closed Tor window and went to `brave://settings/extensions`, disabled Tor, then re-enabled it again
5. opened a new Tor window
6. tor status should be connected after initiating complete

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1056" alt="Screen Shot 2021-05-28 at 10 33 43 AM" src="https://user-images.githubusercontent.com/387249/120024210-b314ee80-bfa3-11eb-8430-679d055a0e78.png"> | <img width="1056" alt="Screen Shot 2021-05-28 at 10 34 13 AM" src="https://user-images.githubusercontent.com/387249/120024217-b3ad8500-bfa3-11eb-8df6-1cd67bcdaaa9.png"> | <img width="1056" alt="Screen Shot 2021-05-28 at 10 34 10 AM" src="https://user-images.githubusercontent.com/387249/120024215-b3ad8500-bfa3-11eb-8c9f-94e5c3e502f3.png"> | <img width="1071" alt="Screen Shot 2021-05-28 at 11 00 49 AM" src="https://user-images.githubusercontent.com/387249/120024429-0d15b400-bfa4-11eb-979d-a85e705d7260.png"> | <img width="1056" alt="Screen Shot 2021-05-28 at 10 35 19 AM" src="https://user-images.githubusercontent.com/387249/120024218-b4461b80-bfa3-11eb-93d6-dca8165b2f10.png">
</details>

#### Prompt

<details>

1. disabled Wi-Fi (for simulating persistent disconnected state of Tor)
2. opened a new Tor window
3. saw Tor status was disconnected and confirmed I saw a tip prompting me to disable and re-enable Tor
4. clicked on the link, which went to `brave://settings/extensions`
5. turned Wi-Fi back on and returned to the Tor window
6. confirmed when I reconnected, the tip went away and `connected` displayed

example | example | example
---------|---------|----------
<img width="1678" alt="Screen Shot 2021-05-28 at 11 07 47 AM" src="https://user-images.githubusercontent.com/387249/120025405-7c3fd800-bfa5-11eb-88fb-8fac9866507c.png"> | <img width="1680" alt="Screen Shot 2021-05-28 at 11 10 48 AM" src="https://user-images.githubusercontent.com/387249/120025489-98437980-bfa5-11eb-8be8-331aaaed521d.png"> | <img width="1680" alt="Screen Shot 2021-05-28 at 11 08 27 AM" src="https://user-images.githubusercontent.com/387249/120025485-97aae300-bfa5-11eb-9d2c-5f71a68da0bd.png">

</details>

#### Disable Tor

<details>

1. opened a Tor window and made sure user_data_dir had `tor/data` and `tor/watch` files
2. went to `brave://settings/extensions` and disabled Tor via the toggle
3. confirmed the `tor` folder in user_data_dir was empty

example | example
---------|---------
<img width="1678" alt="Screen Shot 2021-05-28 at 10 46 00 AM" src="https://user-images.githubusercontent.com/387249/120023296-73013c00-bfa2-11eb-9018-65bf92cb6f08.png"> | <img width="1679" alt="Screen Shot 2021-05-28 at 10 46 16 AM" src="https://user-images.githubusercontent.com/387249/120023301-7399d280-bfa2-11eb-8e78-7edca66c8ffe.png">

</details>

**Comment by LaurenWags** [comment]
Updated to `release-notes/exclude` after discussing with @darkdh 👍🏻
