### ISSUE TITLE
Latest update ( 1.21.23 ) breaks the AD blocking feature

### ISSUE THREAD

**Issue by fabrijp** [brave/brave-browser#14514]
Latest update ( 1.21.23 ) breaks the AD blocking feature. Any blocked content doesn't hold upon page refresh. Tested on Mac mini M1 with universal public release.

**Comment by ryanbr** [comment]
What issue are you having @fabrijp Is there a specific page having issues?

**Comment by fabrijp** [comment]
> What issue are you having @fabrijp Is there a specific page having issues?

This page:
https://auctions.yahoo.co.jp/

Blocking any element by right click selecting it only works till a page refresh. I have experienced this in past nightly versions and now the current nightly version works as expected.

**Comment by ryanbr** [comment]
Just tested in the newer release (Windows / 1.21.24) and blocking the element was instant for me, no refresh needed.

Does the slightly newer release help? @fabrijp

**Comment by fabrijp** [comment]
Thats correct @ryanbr. 1.21.24 fixed the issue :)
