### ISSUE TITLE
"Hide Brave Rewards" toggle doesn't work after using Private window

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#14531]
@iefremov reported the following:

> I've installed fresh beta and it seems "Hide Brave Rewards toggle" is by default on, while the icon is shown

![image](https://user-images.githubusercontent.com/5033691/110213237-27406a00-7e6d-11eb-9181-562235c8b10d.png)

**Comment by iefremov** [comment]
STR:
1) fresh install
2) open chrome://settings, toggle "Hide Brave Rewards Toggle" -> it hides the rewards icon as expected
3) open an incognito window
4) repeat step (2) -> toggling the switch has no effect
5) close an incognito window
6) repeat step (2) -> toggling the switch has no effect

https://user-images.githubusercontent.com/3109556/110317061-2dd20b80-803e-11eb-9ef8-974556190613.mp4

**Comment by stephendonner** [comment]
Verified `PASSED` using latest `nightly` build and the inline testplan.

First, made sure I could reproduce the bug, using 

Brave | 1.23.53 Chromium: 89.0.4389.105 (Official Build) beta (x86_64)
-- | --
Revision | 14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS | macOS Version 11.2.3 (Build 20D91)

<details>
<summary>mini screencast</summary>
![rewards-hide-bug](https://user-images.githubusercontent.com/387249/112695047-a3ace400-8e40-11eb-81fe-6eae170a87d7.gif)
</details>

Then, verified, using


Brave | 1.24.29 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)

![rewards-toggle-fixed](https://user-images.githubusercontent.com/387249/112695286-09996b80-8e41-11eb-8cfa-abf87004f0f4.gif)
