### ISSUE TITLE
Text change from BAP to BAT

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#14554]
This issue is to revert changes in text from BAP to BAT for japan region.

QA note : 
Verify that all balances should show BAT instead of BAP for japan region.

**Comment by kjozwiak** [comment]
Adding missing milestone. This landed into `master` via `1.25.x` as per https://github.com/brave/brave-core/pull/8175#event-4600033252.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.65 x64 build

<details>
<summary>Verified test plan from <a href=https://github.com/brave/brave-core/pull/8775>brave/brave-core#8775</a></summary>
<br>

- Verified grants is shown for JP locale
- Verified able to claim grants
- Verified wallet updates with UGP grant
- Verified no mention of BAP Tokens or BAP on rewards panel/onboarding/rewards page/rewards internals page
- Verified able to perform an one-time tip
- Verified able to set a recurring tip
- Verified able to perform a contribution
- Verified no entry for Verify wallet on BR Panel

![image](https://user-images.githubusercontent.com/17010094/119098069-5a76ac00-ba0d-11eb-9300-f9af63b9cb4a.png) | ![image](https://user-images.githubusercontent.com/17010094/119098109-64001400-ba0d-11eb-81a7-183ab917475c.png) | ![image](https://user-images.githubusercontent.com/17010094/119098333-9f024780-ba0d-11eb-938e-f73f0e07e5b2.png) | ![image](https://user-images.githubusercontent.com/17010094/119098385-ad506380-ba0d-11eb-9e7b-11b25cce5980.png) | ![image](https://user-images.githubusercontent.com/17010094/119098410-b5a89e80-ba0d-11eb-871c-83662a04e8cb.png)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/119098468-c822d800-ba0d-11eb-9dd8-31f7b6794703.png) | ![image](https://user-images.githubusercontent.com/17010094/119098510-d1ac4000-ba0d-11eb-9b22-794b5a983468.png) | ![image](https://user-images.githubusercontent.com/17010094/119098548-d83ab780-ba0d-11eb-8265-b7074d647a83.png) | ![image](https://user-images.githubusercontent.com/17010094/119098583-df61c580-ba0d-11eb-8255-6ee312745b8f.png) | ![image](https://user-images.githubusercontent.com/17010094/119098601-e4267980-ba0d-11eb-8c53-105d11300e94.png)
![image](https://user-images.githubusercontent.com/17010094/119098616-e8529700-ba0d-11eb-8c5c-fe6846ab7ee0.png) | ![image](https://user-images.githubusercontent.com/17010094/119098692-fd2f2a80-ba0d-11eb-9452-76678fe2b09b.png) | ![image](https://user-images.githubusercontent.com/17010094/119098707-04eecf00-ba0e-11eb-86ee-816a43f41a48.png) | ![image](https://user-images.githubusercontent.com/17010094/119098736-0e783700-ba0e-11eb-921e-c688558908c5.png) | ![image](https://user-images.githubusercontent.com/17010094/119098801-23ed6100-ba0e-11eb-9ee1-29b02116cb98.png) | ![image](https://user-images.githubusercontent.com/17010094/119099008-5bf4a400-ba0e-11eb-8d0a-111200480318.png)
![image](https://user-images.githubusercontent.com/17010094/119099145-7fb7ea00-ba0e-11eb-8af5-17a0357f25a9.png)


</details>

--------
Verification passed on Samsung Tab A with Android 10 running 1.25.65 x64 build

<details>
<summary>Verified test plan from <a href=https://github.com/brave/brave-core/pull/8775>brave/brave-core#8775</a></summary>
<br>

- Verified grants is shown for JP locale
- Verified able to claim grants
- Verified wallet updates with UGP grant
- Verified no mention of BAP Tokens or BAP on rewards panel/onboarding/rewards page/rewards internals page
- Verified able to perform an one-time tip
- Verified able to set a recurring tip
- Verified able to perform a contribution
- Verified no entry for Verify wallet on BR Panel

![image](https://user-images.githubusercontent.com/17010094/119104993-cf99af80-ba14-11eb-881a-38050544d60c.png)| ![image](https://user-images.githubusercontent.com/17010094/119105088-e6d89d00-ba14-11eb-8c0b-5d6944430546.png)| ![image](https://user-images.githubusercontent.com/17010094/119105706-81d17700-ba15-11eb-833d-bbe1c01e80a7.png)|![image](https://user-images.githubusercontent.com/17010094/119105729-8a29b200-ba15-11eb-9c79-2711e89ddc49.png)
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/119105762-931a8380-ba15-11eb-904e-d102c80e21ee.png) | ![image](https://user-images.githubusercontent.com/17010094/119105776-96ae0a80-ba15-11eb-8cab-953d1555cc66.png) | ![image](https://user-images.githubusercontent.com/17010094/119105804-9e6daf00-ba15-11eb-9aef-46d3fbd1031f.png) | ![image](https://user-images.githubusercontent.com/17010094/119105823-a1689f80-ba15-11eb-8ab3-9589176d747e.png)
![image](https://user-images.githubusercontent.com/17010094/119105839-a594bd00-ba15-11eb-92e0-4632e7cf4ae3.png) | ![image](https://user-images.githubusercontent.com/17010094/119105861-aa597100-ba15-11eb-934c-b7dfb0509a3d.png) | ![image](https://user-images.githubusercontent.com/17010094/119105935-b9d8ba00-ba15-11eb-8639-88c1bef8f7b2.png)| ![image](https://user-images.githubusercontent.com/17010094/119105981-c3fab880-ba15-11eb-8903-6f84ab356565.png)
![image](https://user-images.githubusercontent.com/17010094/119106002-c8bf6c80-ba15-11eb-9426-564a3bfb2670.png) | ![image](https://user-images.githubusercontent.com/17010094/119106026-cd842080-ba15-11eb-8888-6e0c54dd9999.png) | ![image](https://user-images.githubusercontent.com/17010094/119106248-0d4b0800-ba16-11eb-9b4a-91799fa411f1.png) | ![image](https://user-images.githubusercontent.com/17010094/119106455-484d3b80-ba16-11eb-887a-16c2f3bb1ae7.png)

</details>
