### ISSUE TITLE
Android orbot conflict

### ISSUE THREAD

**Issue by cthulhubuddha** [brave/brave-browser#1456]
## Description 
Android Brave Browser conflicts w/ default Orbot Tor ports, unclear how to modify ports in Android Brave Browser

## Steps to Reproduce

   1. Install Orbot
   2. Install/open Brave
   3. Start Orbot (logs will show unable to connect to default ports)

Disabling Brave allows orbot to function normally. Looking for workaround, either on orbot side or brave side. I run orbot in vpn for other apps.

**Comment by srirambv** [comment]
Wrong repo. Please track it here https://github.com/brave/browser-android-tabs/issues/765
