### ISSUE TITLE
Update BAP translations

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14572]
## Description 

BAP popup/modal translations have been updated, see https://github.com/brave/internal/issues/756

Updated translations should be in Transifex per above issue, this is a placeholder so QA verifies them.

## Steps to Reproduce

   1. Trigger BAP modal
   2. Confirm English and Japanese text.

cc @Miyayes @kjozwiak @rebron @bsclifton

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Windows 10 OS Version 2009 (Build 19042.844)
```

Verified the STR/Case outlined via https://github.com/brave/brave-browser/issues/14572#issue-824852471 and ensured that the translations mentioned via https://github.com/brave/internal/issues/756#issue-824795329 are being used. Found https://github.com/brave/internal/issues/756#issuecomment-796417618 but not a blocker.

**`English`** | **`Japanese`**
--------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/110732514-51d64e00-81f2-11eb-81f3-30a5343a8fe6.png)  | ![japanModal](https://user-images.githubusercontent.com/2602313/110732506-4aaf4000-81f2-11eb-9356-d8a4a3b69978.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.21.76 x64 build
- Verified test plan from https://github.com/brave/internal/issues/756#issue-824795329

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/110766581-39dfe800-824d-11eb-9937-d675ad8e5284.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/110766744-685dc300-824d-11eb-8b4b-9024f541f8a5.png>
