### ISSUE TITLE
Add list of well known chains to the local data files updater

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14574]
We would allow to update this list periodically independent of browser updates.  
This list will be used to implement `wallet_addEthereumChain` from EIP 3085.  
We'll want to cross check what the user enters to make sure it is valid and to make sure the user isn't susceptible to replay attacks via networks re-using chain IDs.

https://chainid.network/chains.json

**Comment by darkdh** [comment]
Also for Solana
https://github.com/solana-labs/token-list/blob/main/src/tokens/solana.tokenlist.json
