### ISSUE TITLE
Change BAP notice frequency to daily

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#14570]
## Description

BAP notices currently show once every 3 days until March 13, 2021. However, given the closeness to March 13th, it would be good to increase the frequency for users.

## Solution

Increase frequency to daily.

**Comment by LaurenWags** [comment]
Verified using

```
Brave	1.23.28 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
Revision	0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS	macOS Version 10.15.7 (Build 19H524)
```

<details>
<summary>Scenario 1: Non JP region</summary>

1. Have region set to something other than Japan (I used US)
1. Install above build
1. Enable Rewards, do not claim UGP grant
1. Navigate to NTP --> Confirm no BAP alert shown on NTP
1. Close NTP
1. Close/relaunch
1. Open NTP --> Confirm no BAP alert shown on NTP
1. Claim UGP grant, wait for balance to update
1. Open NTP --> Confirm no BAP alert shown on NTP
1. Close NTPs
1. Close browser
1. Advance clock by 1 day
1. Relaunch browser
1. Open NTP --> Confirm no BAP alert shown on NTP
1. Close NTPs
1. Close browser
1. Set clock to March 13th, confirm no BAP alert shown and BAT balance is not 0 (should be amount of UGP grant)

<img width="1195" alt="non-JP region" src="https://user-images.githubusercontent.com/28145373/110654247-f96c6580-818b-11eb-845e-549ca19dc9a4.png">

</details>

<details>
<summary>Scenario 2: JP Region</summary>

1. Have region set to Japan
1. Install above build
1. Enable Rewards, do not claim UGP grant
1. Navigate to NTP --> Confirm no BAP alert shown on NTP
1. Close NTP
1. Close/relaunch
1. Open NTP --> Confirm no BAP alert shown on NTP
1. Claim UGP grant, wait for balance to update
1. Open NTP --> Confirm BAP alert shown on NTP
1. Do not interact with alert, open another NTP --> BAP alert still shown
1. Close NTPs
1. Close/relaunch browser
1. Open NTP --> Confirm BAP alert shown on NTP
1. Click "x" button --> BAP alert closed
1. Open another NTP --> no BAP alert shown
1. Close NTPs
1. Close browser
1. Advance clock by 1 day
1. Relaunch browser
1. Open NTP --> BAP alert shown on NTP
1. Click OK button on alert --> BAP alert closed
1. Open NTP --> no BAP alert shown
1. Close NTPs
1. Close browser
1. Check each day until March 13th to confirm BAP alert shown on NTP
1. On March 13th, confirm no BAP alert shown and BAP balance is 0 in UI

English text for BAP alert | Japanese text for BAP alert
----- | -----
<img width="467" alt="English" src="https://user-images.githubusercontent.com/28145373/110654316-06895480-818c-11eb-965e-8af19ff08b2e.png"> | <img width="450" alt="Japanese" src="https://user-images.githubusercontent.com/28145373/110654322-07ba8180-818c-11eb-8292-6fa2a72bbcd6.png">

</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | Windows 10 OS Version 2009 (Build 19042.844)
```

<details>
<summary>Case 1 - non-Japan region</summary>

1. Have region set to something other than Japan (I used `Canada`)
1. Install above build
1. Enable Rewards, do not claim UGP grant
1. Navigate to NTP --> Confirm no BAP alert shown on NTP
1. Close NTP
1. Close/relaunch
1. Open NTP --> Confirm no BAP alert shown on NTP
1. Claim UGP grant, wait for balance to update
1. Open NTP --> Confirm no BAP alert shown on NTP
1. Close NTPs
1. Close browser
1. Advance clock by 1 day
1. Relaunch browser
1. Open NTP --> Confirm no BAP alert shown on NTP
1. Close NTPs
1. Close browser
1. Set clock to March 13th, confirm no BAP alert shown and BAT balance is not 0 (should be amount of UGP grant)

**`Example 1`** | **`Example 1`**
-----------------|-------------------
![image](https://user-images.githubusercontent.com/2602313/110739678-a633fa80-81ff-11eb-85b5-ee74cd6b32c9.png) | ![image](https://user-images.githubusercontent.com/2602313/110739874-02971a00-8200-11eb-8da0-7ebf2e42b720.png)

</details>

<details>
<summary>Case 2 - Japan region</summary>

1. Have region set to Japan
1. Install above build, navigate to Dev Options, enable Staging Env for Rewards and relaunch as prompted
1. After relaunch, skip onboarding prompt, tap on Rewards logo, enable Rewards, do not claim UGP grant
1. Navigate to NTP --> Confirm no BAP alert shown on NTP
1. Close NTP
1. Close/relaunch
1. Open NTP --> Confirm no BAP alert shown on NTP
1. Claim UGP grant, wait for balance to update (known issue that you need to close/open panel several times to get balance to show)
1. Close/relaunch browser --> Confirm BAP alert shown
1. Tap "OK" button --> BAP alert closed
1. Open another NTP --> no BAP alert shown
1. Close browser
1. Advance clock by 1 day
1. Relaunch browser
1. Open NTP --> BAP alert shown on NTP
1. Tap OK button on alert --> BAP alert closed
1. Open NTP --> no BAP alert shown
1. Close NTPs
1. Close browser
1. Check each day until March 13th to confirm BAP alert shown on NTP
1. On March 13th, confirm no BAP alert shown and BAP balance is 0 in UI

**`Japan BAP Alert (English)`** | **`State on March 13th`**
---------------------------------|------------------------------
![image](https://user-images.githubusercontent.com/2602313/110740061-63265700-8200-11eb-80e4-7b6869370885.png) | ![image](https://user-images.githubusercontent.com/2602313/110740187-9b2d9a00-8200-11eb-9e82-fd74a53f2135.png)

**`Japan BAP Alert`** | **`State on March 13th`**
---------------------------------|------------------------------
![alertJapan](https://user-images.githubusercontent.com/2602313/110674211-ab615d00-819f-11eb-9235-18d80ec75a35.png) | ![zeroBalance13Japan](https://user-images.githubusercontent.com/2602313/110674216-adc3b700-819f-11eb-9368-efbb03aef3eb.png)

 </details>

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.21.76 x64 build
- Verified BAP notice is shown daily 

<details>
<summary><b>Case 1 - Japan region</b></summary>

1. Have region set to Japan
2. Install above build, navigate to Dev Options, enable Staging Env for Rewards and relaunch as prompted
3. After relaunch, skip onboarding prompt, tap on Rewards logo, enable Rewards, do not claim UGP grant
4. Navigate to NTP --> Confirm no BAP alert shown on NTP
5. Close NTP
6. Close/relaunch
7. Open NTP --> Confirm no BAP alert shown on NTP
8. Claim UGP grant, wait for balance to update (known issue that you need to close/open panel several times to get balance to show)
9. Close/relaunch browser --> Confirm BAP alert shown
10. Tap "OK" button --> BAP alert closed
11. Open another NTP --> no BAP alert shown
12. Close browser
13. Advance clock by 1 day
14. Relaunch browser
15. Open NTP --> BAP alert shown on NTP
16. Tap OK button on alert --> BAP alert closed
17. Open NTP --> no BAP alert shown
18. Close NTPs
19. Close browser
20. Check each day until March 13th to confirm BAP alert shown on NTP
21. On March 13th, confirm no BAP alert shown and BAP balance is 0 in UI

March 11 | March13
-- | --
![image](https://user-images.githubusercontent.com/17010094/110764729-50853f80-824b-11eb-9ce6-211cc8c24dad.png) | ![image](https://user-images.githubusercontent.com/17010094/110764755-58dd7a80-824b-11eb-8698-fe3530f1b0e5.png)

</details>

<details>
<summary><b>Case 2 - non-Japan region</b></summary>

1. Have region set to something other than Japan (I used `Canada`)
2. Install above build
3. Enable Rewards, do not claim UGP grant
4. Navigate to NTP --> Confirm no BAP alert shown on NTP
5. Close NTP
6. Close/relaunch
7. Open NTP --> Confirm no BAP alert shown on NTP
8. Claim UGP grant, wait for balance to update
9. Open NTP --> Confirm no BAP alert shown on NTP
10. Close NTPs
11. Close browser
12. Advance clock by 1 day
13. Relaunch browser
14. Open NTP --> Confirm no BAP alert shown on NTP
15. Close NTPs
16. Close browser
17. Set clock to March 13th, confirm no BAP alert shown and BAT balance is not 0 (should be amount of UGP grant)

March 11 | March 13
-- | --
![image](https://user-images.githubusercontent.com/17010094/110765005-9e9a4300-824b-11eb-85ee-fec0eba7c446.png) | ![image](https://user-images.githubusercontent.com/17010094/110764962-93dfae00-824b-11eb-9164-9b01d0aa688f.png)

</details>

------------
Verification passed on OnePlus 6T with Android 10 running 1.21.76 x64 build
- Verified BAP notice is shown daily 

<details>
<summary><b>Case 1 - Japan region</b></summary>

- Have region set to Japan
- Install above build, navigate to Dev Options, enable Staging Env for Rewards and relaunch as prompted
- After relaunch, skip onboarding prompt, tap on Rewards logo, enable Rewards, do not claim UGP grant
- Navigate to NTP --> Confirm no BAP alert shown on NTP
- Close NTP
- Close/relaunch
- Open NTP --> Confirm no BAP alert shown on NTP
- Claim UGP grant, wait for balance to update (known issue that you need to close/open panel several times to get balance to show)
- Close/relaunch browser --> Confirm BAP alert shown
- Tap "OK" button --> BAP alert closed
- Open another NTP --> no BAP alert shown
- Close browser
- Advance clock by 1 day
- Relaunch browser
- Open NTP --> BAP alert shown on NTP
- Tap OK button on alert --> BAP alert closed
- Open NTP --> no BAP alert shown
- Close NTPs
- Close browser
- Check each day until March 13th to confirm BAP alert shown on NTP
- On March 13th, confirm no BAP alert shown and BAP balance is 0 in UI

March 11 | March 13
-- | --
![image](https://user-images.githubusercontent.com/17010094/110765789-7101c980-824c-11eb-811d-b11c579e8232.png) | ![image](https://user-images.githubusercontent.com/17010094/110765860-81b23f80-824c-11eb-8806-0168e0a0f541.png)

</details>

<details>
<summary><b>Case 2 - non-Japan region</b></summary>

- Have region set to something other than Japan (I used `Canada`)
- Install above build
- Enable Rewards, do not claim UGP grant
- Navigate to NTP --> Confirm no BAP alert shown on NTP
- Close NTP
- Close/relaunch
- Open NTP --> Confirm no BAP alert shown on NTP
- Claim UGP grant, wait for balance to update
- Open NTP --> Confirm no BAP alert shown on NTP
- Close NTPs
- Close browser
- Advance clock by 1 day
- Relaunch browser
- Open NTP --> Confirm no BAP alert shown on NTP
- Close NTPs
- Close browser
- Set clock to March 13th, confirm no BAP alert shown and BAT balance is not 0 (should be amount of UGP grant)

March 11 | March 13
-- | --
![image](https://user-images.githubusercontent.com/17010094/110765978-9b538700-824c-11eb-8fa0-ee1a56a6301f.png) | ![image](https://user-images.githubusercontent.com/17010094/110765922-90005b80-824c-11eb-9ccb-7900965c2ad9.png)

</details>
