### ISSUE TITLE
chrome:// urls should display as brave://

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#1458]
It may be too much work to redirect all chrome:// urls to brave:// and have the appropriate handlers and checks still work reliable.

Luckily, the ToolbarModel provides GetURLForDisplay which can be overridden so that brave:// displays most of the time (until the URL is edited).

When paired with https://github.com/brave/brave-browser/issues/810 this should cover quite a bit of the requirement to support brave:// URLs without confusing the users about the chromium-based core.

Test plan:
## Displays brave:// url
- Clean Profile
- Launch browser
- Welcome page should be open with `brave://welcome` as the address in LocationBar

## Edits chrome:// url
- Open settings
- Settings page should be open with `brave://` prefix in LocationBar
- Edit the url by focusing in the LocationBar and moving the cursor or adding text
- LocationBar text should have chrome:// prefix

## Copies chrome:// url
- Open settings
- Settings page should be open with `brave://` prefix in LocationBar
- Right-click the LocationBar text and select 'Copy'
- Clipboard text should have chrome:// prefix

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/46986613-57c9b280-d0be-11e8-8d62-feb241532abb.png)
