### ISSUE TITLE
stats and referrals call ProfileManager::GetPrimaryUserProfile without waiting for profile initialization to complete

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#14594]
Early initialization of the profiles could cause a wide range of problems and it's not clear what issues it may or may not be causing now, but it's clearly a problem that needs to be addressed

QA should check regular and referral pings for correctness

**Comment by LaurenWags** [comment]
Verification in progress using

```
Brave | 1.21.77 Chromium: 89.0.4389.90 (Official Build) (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 10.15.7 (Build 19H524)
```

As per https://github.com/brave/brave-browser/issues/14594#issue-826313459, basically ensured that usage & referral pings are still working as per the following:

#### **`Usage pings`**

**`initial launch`** | **`30 days after install`** | **`Ads enabled`**
--------------------|-------------------------------------|-----------------------------------
<img width="1278" alt="initial launch" src="https://user-images.githubusercontent.com/28145373/111163961-f6022100-8573-11eb-9d2c-b46dd52b118e.png"> | <img width="1279" alt="30 days after install" src="https://user-images.githubusercontent.com/28145373/111163970-f7cbe480-8573-11eb-87d5-9d484ee8242c.png"> | <img width="1279" alt="Ads Enabled" src="https://user-images.githubusercontent.com/28145373/111163974-f8fd1180-8573-11eb-997b-1e4123bdcb35.png">


#### **`Referral pings`**

**`initial launch`** | **`24hrs after install`** | **`30 days after install`** | **`30 days event complete`** | **`90 days after install`**
--------------------|-------------------------------------|-----------------------------------|------------------------|-----------------
<img width="1277" alt="referral - initial launch" src="https://user-images.githubusercontent.com/28145373/111164014-01ede300-8574-11eb-9bed-17799f5c9ecb.png"> | <img width="1277" alt="referral - 24h after install" src="https://user-images.githubusercontent.com/28145373/111164020-031f1000-8574-11eb-9056-b146e69025ad.png"> | <img width="1278" alt="referral - 30d after install" src="https://user-images.githubusercontent.com/28145373/111164025-04503d00-8574-11eb-82b2-809756d31865.png"> | TBD | <img width="1270" alt="referral-90d after install" src="https://user-images.githubusercontent.com/28145373/111164040-0914f100-8574-11eb-8ba4-cf019500caad.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.77 x64 build
- Verified usage pings are still working as expected

Initial Launch | 30 Days after install | Ads enabled
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/111179729-42655500-85a4-11eb-9d45-3af437c0b616.png) | ![image](https://user-images.githubusercontent.com/17010094/111180082-9708d000-85a4-11eb-9350-75598be6d332.png) | ![image](https://user-images.githubusercontent.com/17010094/111180477-fb2b9400-85a4-11eb-92b6-692cecbeb8f2.png)
