### ISSUE TITLE
Add support for Rewards bitFlyer external wallets

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#14591]

**Comment by LaurenWags** [comment]
Verifications completed over multiple versions, but most recently using:

```
Brave	1.24.81 Chromium: 90.0.4430.93 (Official Build) (x86_64)
Revision	4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS	macOS Version 10.15.7 (Build 19H1030)
```

Test notes, screenshots, and issues found during testing are listed under https://github.com/brave/internal/issues/765#issuecomment-824362121

------------
