### ISSUE TITLE
Add Site should probably read Add site in new-tab page's Favorites

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14596]
## Description 
Add Site should probably read Add site in new-tab page's Favorites

## Steps to Reproduce

   1.  open the new-tab page
   2. click `Customize`
   3. choose `Top Sites` from the left
   4. choose `Favorites`
   5. dismiss the dialog
   6. hover to the right of the `Add site` button
   7. click on the ellipsis
   8. note the capitalization of `Add Site`

## Actual result:

It reads `Add Site` (upper-case)

<img width="1607" alt="Screen Shot 2021-03-09 at 11 14 11 AM" src="https://user-images.githubusercontent.com/387249/110524975-e8a6eb80-80c8-11eb-8960-986ee8c0057a.png">

## Expected result:

`Add site` (lower-case)

## Brave version (brave://version info)

Brave | 1.22.55 Chromium: 89.0.4389.72 (Official Build) beta (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by akshat-rawat** [comment]
Hi, I would like the work on the issue.
Acc. to me the cause of the issue is in `brave-core/components/resources/brave_components_strings.grd`

**Comment by stephendonner** [comment]
Assigning to you @akshat-rawat; thanks for taking a look!

**Comment by akshat-rawat** [comment]
@stephendonner, I have made the necessary changes and opened a [PR](https://github.com/brave/brave-core/pull/9306) for the same.

**Comment by stephendonner** [comment]
> @stephendonner, I have made the necessary changes and opened a [PR](https://github.com/brave/brave-core/pull/9306) for the same.

Thanks for fixing; reviewed and merged!

**Comment by stephendonner** [comment]
Verified `FIXED` using the inline testplan with build 


Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)



Steps:

1. open the new-tab page
2. click `Customize`
3. choose `Top Sites` from the left
4. choose `Favorites`
5. dismiss the dialog
6. hover to the right of the `Add site` button
7. click on the ellipsis `...`

Confirmed it now reads `Add site`

<img width="1158" alt="Screen Shot 2021-07-06 at 4 47 24 PM" src="https://user-images.githubusercontent.com/387249/124679777-f3f10480-de79-11eb-9654-91c9b86b5914.png">
