### ISSUE TITLE
Add ability to import From Google Chrome Beta

### ISSUE THREAD

**Issue by sethpeace** [brave/brave-browser#14609]
## Description 

I just got Brave Browser and noticed that I couldn't transfer my data from Google Chrome Beta. I should be able to!

## Steps to Reproduce

   1. Get Google Chrome Beta and set it up
   2. Go to "brave://settings/importData" in Brave Browser
   3. Click the dropdown. Google Chrome Beta isn't in the list.

## Actual result:

Google Chrome Beta isn't in the list of browsers to transfer from.

## Expected result:
Google Chrome Beta is in the list of browsers to transfer from.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
Brave	1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
Revision	3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A (Can't transfer from Chrome to Chrome)

**Comment by srirambv** [comment]
Similar to #1357

cc: @rebron

**Comment by rebron** [comment]
cc: @kjozwiak Need more investigation on this one. Profiles should showed up but not necessarily showing which channel.

**Comment by sethpeace** [comment]
The profiles do not show up at all.

**Comment by srirambv** [comment]
@rebron  if am not wrong this is an issue with Chromium and not just Brave. Chrome Dev doesn't even recognise Chrome release channel. Here's a screenshot of Chrome Dev build
![image](https://user-images.githubusercontent.com/17010094/111461581-48c70e80-8715-11eb-883a-5b131d03990f.png)

**Comment by kjozwiak** [comment]
So it looks like Brave only adds Chrome/Canary into `Import Data` but isn't finding `Chrome Beta` & `Chrome Dev`. Examples:

Installed Version:

* `89.0.4389.82 (Official Build) (64-bit) (cohort: Stable)`
* `90.0.4430.19 (Official Build) beta (64-bit) (cohort: Beta)`
* `91.0.4442.4 (Official Build) dev (64-bit) (cohort: Dev)`
* `91.0.4449.0 (Official Build) canary (64-bit) (cohort: Clang-64)`

What Brave is finding via `brave://settings/importData`:

**`Example`** | **`Example`**
---------------|----------------
![import2](https://user-images.githubusercontent.com/2602313/111498414-4f0aba00-8718-11eb-921c-66bf6cec5d1e.png) | ![import1](https://user-images.githubusercontent.com/2602313/111498835-b3c61480-8718-11eb-934f-0850911d2579.png)

Regarding what @srirambv mentioned above, that's related to #1357 re: Chromium not finding other channels. The above is an about Brave not finding another browser, specifically `Chrome Beta` & `Chrome Dev`.

Looks like `Edge` & `Firefox` also have issues finding other browsers:

**`Edge`** | **`Firefox`**
------------|--------------
![image](https://user-images.githubusercontent.com/2602313/111499177-0d2e4380-8719-11eb-8e02-74e59b9bd1f9.png) | ![image](https://user-images.githubusercontent.com/2602313/111499608-8037ba00-8719-11eb-8967-aabaeaad7ae9.png)

* Edge - not finding Brave, Chrome Beta, Chrome Dev & Chrome Canary
* Firefox - not finding Brave & Chrome Dev

**Comment by kjozwiak** [comment]
@bsclifton @rebron should we maybe move this to a `P3` as we want users to have a seamless experience when migrating from other browsers? Maybe `Chrome BETA` doesn't have the userbase as Chrome but assuming it's still pretty big. Either way, I'm fine with `P4` but figured we might want to get this fixed sooner than later as part of user retention efforts 👍

**Comment by bsclifton** [comment]
Confirmed this is still an issue; Canary and Stable channel both import just fine

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.45.77 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)

### Pre-requisite Steps:
`Google Chrome Beta` installed, seeded the following two profiles:
* Unique User 1
* Unique User 2

Both of which have 1 (or more):
* bookmarks
* extensions
* history
* passwords

Case 1: `brave://welcome` import
<details>

### Steps:
1. installed `1.45.77`
2. launched Brave
3. clicked `Let's go ->`
4. selected `Chrome Beta Unique User 1`
5. clicked on `Import`
6. clicked `Done` 

#### Confirmed the following were successfully imported:
* bookmarks
* extensions
* history
* passwords

#### `Unique User 1`

`bookmarks` | `extensions` | `history` | `passwords`
-------------|---------------|----------|-------------
<img width="1312" alt="Screen Shot 2022-09-28 at 3 57 39 PM" src="https://user-images.githubusercontent.com/387249/192877189-9a3116a6-49a8-467a-b1f7-761f88ee585e.png"> | <img width="1312" alt="Screen Shot 2022-09-28 at 3 57 55 PM" src="https://user-images.githubusercontent.com/387249/192877108-76d5a422-f24f-4772-853f-ae1ded432266.png"> | <img width="1312" alt="Screen Shot 2022-09-28 at 3 57 28 PM" src="https://user-images.githubusercontent.com/387249/192877469-6787ec9d-c10d-472d-b31b-b3490e3a075a.png"> | <img width="1312" alt="Screen Shot 2022-09-28 at 3 57 00 PM" src="https://user-images.githubusercontent.com/387249/192877533-63c6889d-2a87-4bc4-8248-5570675138c0.png">

#### `Unique User 2`

`bookmarks` | `extensions` | `history` | `passwords`
-------------|---------------|----------|-------------
<img width="1312" alt="Screen Shot 2022-09-28 at 4 24 42 PM" src="https://user-images.githubusercontent.com/387249/192881665-684b1e5f-73ca-4930-8d2c-aed788d2d231.png"> | <img width="1312" alt="Screen Shot 2022-09-28 at 4 25 03 PM" src="https://user-images.githubusercontent.com/387249/192882405-27c9d3dc-4316-46d0-b4e9-708abddf60ad.png"> | <img width="1312" alt="Screen Shot 2022-09-28 at 4 24 24 PM" src="https://user-images.githubusercontent.com/387249/192882615-b70f5021-6a62-4f74-a73b-33d26eb3b8a9.png"> | <img width="1312" alt="Screen Shot 2022-09-28 at 4 31 25 PM" src="https://user-images.githubusercontent.com/387249/192882839-21b648b2-2c43-4f28-9ae5-6c3e3015630c.png">






</details>

Case 2: `Brave` -> `Import Bookmarks and Settings...`
<details>

</details>



Case 3: Main menu -> `Bookmarks` -> `Import Bookmarks and Settings...`
<details>

</details>



Case 4: `brave://settings/importData`
<details>

</details>

**Comment by LaurenWags** [comment]
@stephendonner @MadhaviSeelam let's be sure to check this one on Windows and macOS 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```

Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

### Prerequisite Steps:
<details>

`Google Chrome Beta` installed, seeded the following two profiles:
* `Person 1`  - 
    - bookmarks/favorites
    - extensions
    - browsing history
    - saved passwords
* `Person 2`
    - bookmarks/favorites
    - extensions
    - browsing history

</details>

Case 1: Multiple profiles - `brave://welcome` import - `PASSED`
<details>

### Steps:
1. installed `1.45.84`
2. launched Brave
3. clicked `Let's go ->`
4. selected `Chrome Beta Person 1`
5. clicked on `Import`
6. clicked `Done` 

#### Confirmed the following were successfully imported:
* bookmarks/favorites
* extensions
* browsing history
* saved passwords

#### `Person 1`

`step 3` |`step 4`|`bookmarks` | `extensions` | `browsing history` | `saved passwords`
-------------|---------------|----------|-------------|--------|---------
<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/193948780-438fb753-3ffe-43b7-be98-bf7098c509f6.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/193948818-6e85fe23-35f8-46d6-ab19-19f746f3c6c2.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/193949133-f01a0a80-77f0-4f47-967b-3f5a8be54ea1.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/193949191-c9b095be-4548-4bc7-b722-6a7375019ee1.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/193949217-25302ef4-01b6-4975-89b1-8659cf116525.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/193949693-f1eb5885-c4e1-4b7c-b6b7-dd03ba77fea1.png">

#### `Person 2`

`step 4`|`bookmarks`|`browsing history`|`saved passwords`
---|---|---|---
<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/193949495-9c650010-ea46-4d5a-8709-1878203592af.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/193949524-44503d3f-11d9-4b06-973b-68ecab6fe2f2.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/193949569-fcd6b9ea-7f2f-4aa3-91f0-9a6e15ad763d.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/193949608-e96a0791-87a0-41d6-b6ac-017a7591e820.png">
