### ISSUE TITLE
Some users are not seeing NTP Sponsored Images 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#14608]
## Description 

Users on Community are reporting that NTP SI do not appear. I have tested and confirmed:
- Users are updated to the latest Brave version
- Users are updated to the latest component version of NTP SI (also tried force update). 
- SI do not appear in new browser profile either
- Sponsored images toggle in Settings UI is toggled "on"

Users appear to be using Windows 10, Kubuntu 20.04 and Kubuntu 21.04 ( so far). I've asked users to confirm their locale as well.

## Brave version (brave://version info)

Version 1.21.74 Chromium: 89.0.4389.72 (Official Build) (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A 
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Original thread here:
https://community.brave.com/t/no-sponsored-image-on-the-forth-new-tab/215129/13
Internal conversation thread here: https://bravesoftware.slack.com/archives/CB0KCRCQN/p1615321540255300

**Comment by rebron** [comment]
cc: @jsecretan Might be campaign or region specific.

**Comment by tmancey** [comment]
Closing issue as discussed with @Brave-Matt and during screen shares this has been due to users region not supported NTP SI rewards
