### ISSUE TITLE
Unclickable brave shields

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [brave/brave-browser#14604]
## Description 
I can't open the brave shields popup on local webpages. It just turns grey, and then nothing happens, even if I click it again. 

## Steps to Reproduce

   1.  Go to a local page (like the new tab page, any chrome page, even files).
   2.  Click on the brave shields icon
   3.  The only way to get back to normal is to go to an online website, and then click it.

## Actual result:
Get's greyed out as if it's been activated, but the popup doesn't show up.

## Expected result:
At least make it not get greyed out.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)

1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit) 

Windows 10 OS Version 2004 (Build 19041.804)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 
- Can you reproduce this issue with the beta channel? not tried
- Can you reproduce this issue with the nightly channel?  not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? I think so

## Miscellaneous Information:

**Comment by ryanbr** [comment]
@ego-lay-atman-bay Only time I see a grey shields is on main page, and `brave://`  pages.

Is there a sample page causing issues?

**Comment by ToaKraka** [comment]
> @ego-lay-atman-bay Only time I see a grey shields is on main page, and `brave://` pages.
> 
> Is there a sample page causing issues?

Steps to reproduce:

1. Download an HTML file to your Desktop.

2. Open the HTML file in Brave.

3. Attempt to click on the Brave shield.

**Comment by rebron** [comment]
@ego-lay-atman-bay @ToaKraka This works as expected. For those type of pages, Brave Shields isn't applicable so there's nothing to change.

**Comment by ToaKraka** [comment]
> For those type of pages, Brave Shields isn't applicable

There are situations where a person might want to enable Javascript on a local file without being forced to change the browser's default "Block scripts" toggle in brave://settings/shields.
