### ISSUE TITLE
Implement Rewards UI 2.0 for Rewards 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#14602]
## Description 

This is part of the Rewards UI/UX overhaul effort. This work will endure as it will _not_ be replaced with the upcoming unified wallets work. (The new card look better coheres with the unified wallet.)

### Related

Estimated pending rewards counter should reset monthly: https://github.com/brave/brave-browser/issues/15005

### Current Design

<img src="https://user-images.githubusercontent.com/11497541/110531592-c1144b00-80e9-11eb-83de-b9b96889411b.png" width=200px>

### New Design

See design spec.

cc: @jenn-rhim

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.31.73 Chromium: 94.0.4606.71 (Official Build) beta (x86_64)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | macOS Version 10.15.7 (Build 19H1417)
```

Verified test plan from https://github.com/brave/brave-core/pull/9883#issue-981456162

<details>
<summary>Functional differences from previous UI - In Progress</summary>

1. Publisher verification status notice scenarios can be found under https://github.com/brave/brave-browser/issues/18341#issuecomment-933506070. This covers the appropriate notice being displayed for various publisher verification statuses, the notice being displayed on over on the panel, the notice being shown on the tipping banner, and confirming that the tip goes through or is sent to "Pending" list  when appropriate. This is for anon, Uphold, bitFlyer, and Gemini user wallets.

2. Confirmed "BAT arriving soon" msg has been added to panel/wallet card. Confirmed the value displaying for this message is the same in all places (panel, NTP, brave://rewards):

Panel - Summary View | Panel - Publisher View | NTP Widget | brave://rewards page
----- | ----- | ----- | -----
<img width="1447" alt="panel-summary view" src="https://user-images.githubusercontent.com/28145373/136219157-2f464a31-9ec8-4bc2-9dce-355bd2a8b9ea.png"> | <img width="423" alt="panel-pub view" src="https://user-images.githubusercontent.com/28145373/136219177-f501aca9-2158-431d-9ff2-d87c5a73cbfb.png"> | <img width="308" alt="NTP" src="https://user-images.githubusercontent.com/28145373/136219205-3a854cc2-6ad4-4657-b534-6181e0d42967.png"> | <img width="1092" alt="rewards page" src="https://user-images.githubusercontent.com/28145373/136219223-b9dffe07-e8da-4caa-a5f8-821c7f156a9c.png">


</details>
