### ISSUE TITLE
Remove / Disable "Make a Call From" Chromium dialog

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#14601]
When you click on a phone number, Chromium now asks if you'd like to use "Brave Sync" to call from your android device.  This text / messaging doesn't make sense in Brave; we don't include this "call from" feature in Brave Sync.  This issue is to remove the dialog / feature for the time being

<img width="336" alt="screen_shot_2021-03-08_at_4 33 26_pm" src="https://user-images.githubusercontent.com/76526/110528283-9a501780-80dd-11eb-88e5-789e095d7831.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.25.18 Chromium: 90.0.4430.72 (Official Build) nightly (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/8454

![image](https://user-images.githubusercontent.com/34715963/114912634-84421f00-9e20-11eb-8e7e-8da067a361b2.png)
