### ISSUE TITLE
Fix threading problems in Rewards Service

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#14616]
see `rewards_service_impl.cc`
* There are invalid uses of `base::Unreatined` (see methods related to diagnostics log)
* `RewardsServiceImpl::RunDBTransaction` binds a raw pointer to the database. The database is properly destroyed in the service destructor using `DeleteSoon`, but it also could happen at any moment when `Reset()` is called, so needs double-checking
* There is a related crash https://github.com/brave/brave-browser/issues/14564

**Comment by iefremov** [comment]
cc @emerick @bridiver

**Comment by emerick** [comment]
@iefremov Is this a dupe of https://github.com/brave/brave-browser/issues/14316?

**Comment by iefremov** [comment]
indeed, I wasn't aware that @bridiver already filed this

**Comment by goodov** [comment]
Fixed:
https://github.com/brave/brave-browser/issues/15234
https://github.com/brave/brave-browser/issues/15231

To fix:
https://github.com/brave/brave-browser/issues/15235
https://github.com/brave/brave-browser/issues/15309
