### ISSUE TITLE
Cryptowallet info bar points to Extensions instead of Wallet settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14619]
## Description 

Cryptowallet info bar points to Extensions instead of Wallet settings

## Steps to Reproduce

   1. Install 1.22.49 beta build
   2. Visit Cryptokitties.com and trigger first install info bar
   3. Create CW and close browser
   4. Restart the browser and load cryptokitties.co to trigger CW info bar that has settings button
   5. Click on settings load `brave://settings/extensions` instead of `brave://settings/wallet`

## Actual result:

https://user-images.githubusercontent.com/17010094/110641454-f1232300-81a9-11eb-9005-e1dea2662197.mov

## Expected result:
Should load `brave://settings/wallet` and not extensions

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.22.49 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes but expected as change is in for 1.22.x
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` using the inline steps to reproduce/verify, with

Brave | 1.23.35 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)



`Settings` now correctly points to `brave://settings/wallet`.

![cryptowallet](https://user-images.githubusercontent.com/387249/110974181-1bdcbb00-8313-11eb-8dee-30a2b0597525.gif)
