### ISSUE TITLE
Customize setting is not visible when you scroll down Brave Today feed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14611]
## Description 

Customize setting is not visible when you scroll down Brave Today feed

## Steps to Reproduce

   1. Open a new tab
   2. Scroll down Brave Today feed
   3. Customize button is not visible but still clickable 

## Actual result:

https://user-images.githubusercontent.com/17010094/110574465-0d48a500-8155-11eb-97e6-e9c3e52ea5d3.mp4

## Expected result:
Show customize button and not let users guess the position

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | `3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa to test on other platforms, cc: @rebron @mattmcalister

**Comment by mattmcalister** [comment]
cc @petemill @karenkliu

**Comment by mattmcalister** [comment]
@srirambv can you confirm this is no longer relevant?

**Comment by srirambv** [comment]
Verified on current master on all platforms. This is no longer an issue. Closing the issue as invalid
