### ISSUE TITLE
Latest version of brave is generating clipped urls on copy

### ISSUE THREAD

**Issue by laymonk** [brave/brave-browser#14636]
## Steps to Reproduce

   1.  Visit any website
   2. Put the mouse in the address bar (and it's selected) and copy
   3. Paste the copied address to discover that you have copied:

## Actual result:

copied url from address bar is:   **domain.com/path/to/file**

## Expected result:
copied url from address bar should be: **https://www.domain.com/path/to/file** 

## Reproduces how often: 

100% of the time

## Brave version (brave://version info)

**1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)**

## Version/Channel Information:

- Can you reproduce this issue with the current release?   **Yes**
- Can you reproduce this issue with the beta channel?  **Haven't tried**
- Can you reproduce this issue with the nightly channel?  **Haven't tried**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  **Has nothing to do with shields**
- Does the issue resolve itself when disabling Brave Rewards? **Has nothing to do with rewards**
- Is the issue reproducible on the latest version of Chrome?  **Doesn't happen in any other browser**

## Miscellaneous Information:

One can work around this by lingering on the address bar until the whole string is exposed ... or double-clicking and then reselecting all. All rather inconvenient for someone who relies on address copying as a fundamental aspect of my notes keeping (writing short notes and attaching links in tools like zotero take less space than clipping whole documents )

What was the big idea about this 'feature' anyways?  ... or it is an oversight and bug? 

Thank you for making Brave ... it's an awesome browser ... first thing I install in any host or VM where browsers are allowed.

**Comment by rebron** [comment]
@laymonk What's copied is the full path and you can see that on the paste. There's an option to `always show full urls`. 
It's possible we revisit whether `always show full urls` is the default.

**Comment by laymonk** [comment]
@rebron, million thanks ... I am happy to have to set that option ... just didn't realise it was there.  Well done to you guys.
