### ISSUE TITLE
BAT tokens suddenly disappeared

### ISSUE THREAD

**Issue by YuriiStaryk** [brave/brave-browser#14635]
Hi, Brave Team!
I just noticed that my BAT tokens disappeared from my account.
Could you please take a look and restore my tokens!

I'm using the same email for Brave and Uphold.
So, please have a look and restore my balance.

Thanks!

**Comment by bsclifton** [comment]
cc: @hollons

**Comment by hollons** [comment]
Thanks @bsclifton for tagging. 

Hi @YuriiStaryk, thanks for reporting! Can you send the following information to Steven@brave.com and I can help to troubleshoot from there: 

* Copy/paste your Wallet ID (found on `brave://rewards-internals`) 
* Your OS and Brave version (first three lines in `brave://version`)
* A screenshot of your Rewards panel in `Settings --> Brave Rewards`. 

This will help to speed up the troubleshooting. Thank you in advance!
