### ISSUE TITLE
update pinset to include new letsencrypt intermediates

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#14637]
https://github.com/brave/brave-core/blob/master/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc#L296 is out of date according to https://letsencrypt.org/certificates/. we need to add R3LetsEncrypt and R4LetsEncrypt, probably DSTRootCAX3 as well

everything except Starfield and Amazon certs are already in https://source.chromium.org/chromium/chromium/src/+/master:net/http/transport_security_state_static.pins, so we should probably read them from that file instead of duplicating them in our code.

once we are sure the desktop pinset is correct, we should add automation to iOS to pull from the same list.

**Comment by diracdeltas** [comment]
marking as p2 since this indicates something might be wrong with the way desktop pinning works

**Comment by bsclifton** [comment]
I don't think we need to add letsencrypt anymore as we've gone back to using GlobalSign for signing

But we do need to make sure cert pinning itself works and that the R3 CA is added to the pin list

**Comment by evq** [comment]
LE is still used on `grant.rewards.brave.com`

**Comment by evq** [comment]
any updates here?

**Comment by jumde** [comment]
No updates so far, following up with the team on slack to figure out the next steps here.

**Comment by fmarier** [comment]
These hosts don't resolve anymore and should therefore be removed:

      { "name": "download.brave.com", "mode": "force-https", "policy": "custom", "pins": "brave"},
      { "name": "sync.brave.com", "mode": "force-https", "policy": "custom", "pins": "brave"},
      { "name": "sync-staging.brave.com", "policy": "custom", "mode": "force-https", "pins": "brave"},
      { "name": "ledger.mercury.basicattentiontoken.org", "policy": "custom", "mode": "force-https", "pins": "brave"},
      { "name": "ledger-staging.mercury.basicattentiontoken.org", "policy": "custom", "mode": "force-https", "pins": "brave"},
      { "name": "ledger.rewards.brave.software", "policy": "custom", "mode": "force-https", "pins": "brave"},
      { "name": "balance.mercury.basicattentiontoken.org", "policy": "custom", "mode": "force-https", "pins": "brave"},
      { "name": "balance-staging.mercury.basicattentiontoken.org", "policy": "custom", "mode": "force-https", "pins": "brave"},
      { "name": "balance.rewards.brave.software", "policy": "custom", "mode": "force-https", "pins": "brave"},
      { "name": "publishers-distro.basicattentiontoken.org", "policy": "custom", "mode": "force-https", "pins": "brave"},
      { "name": "publishers-staging-distro.basicattentiontoken.org", "policy": "custom", "mode": "force-https", "pins": "brave"},
      { "name": "creators-distro.brave.software", "policy": "custom", "mode": "force-https", "pins": "brave"},

**Comment by fmarier** [comment]
> we need to add R3LetsEncrypt and R4LetsEncrypt, probably DSTRootCAX3 as well

Couldn't we simply pin to ISRG Root X1 and ISRG Root X2?

**Comment by fmarier** [comment]
I went through all of the domains in https://github.com/brave/brave-core/blob/9387d5245732180bbe0006003dee767d5b0afc09/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc#L310-L343 and https://github.com/brave/brave-browser/issues/2949#issuecomment-825248452 and verified that they all use these three root CAs:
- Amazon
- GlobalSign GCC R3 DV TLS CA 2020
- R3 (Let's Encrypt)

**Comment by fmarier** [comment]
I don't believe our pins are enforced. If I add Brave Today hostnames (both backed by Amazon certs) with only one Let's Encrypt root enabled:
```
@@ -294,15 +294,15 @@ bool ParseJSON(base::StringPiece json,
       {
         "name": "brave",
         "static_spki_hashes": [
-          "AmazonRootCA1",
-          "AmazonRootCA2",
-          "AmazonRootCA3",
-          "AmazonRootCA4",
-          "StarfieldG2",
-          "GlobalSignRootCA",
-          "GlobalSignRootCA_R2",
-          "GlobalSignRootCA_R3",
-          "LetsEncryptAuthorityPrimary_X1_X3",
+          // "AmazonRootCA1",
+          // "AmazonRootCA2",
+          // "AmazonRootCA3",
+          // "AmazonRootCA4",
+          // "StarfieldG2",
+          // "GlobalSignRootCA",
+          // "GlobalSignRootCA_R2",
+          // "GlobalSignRootCA_R3",
+          // "LetsEncryptAuthorityPrimary_X1_X3",
           "LetsEncryptAuthorityBackup_X2_X4"
         ]
       }
@@ -318,6 +318,8 @@ bool ParseJSON(base::StringPiece json,
       { "name": "sync-v2.bravesoftware.com", "policy": "custom", "mode": "force-https", "pins": >
       { "name": "sync-v2.brave.software", "policy": "custom", "mode": "force-https", "pins": "br>
       { "name": "p3a.brave.com", "policy": "custom", "mode": "force-https", "pins": "brave"},
+      { "name": "pcdn.brave.com", "policy": "custom", "mode": "force-https", "pins": "brave"},
+      { "name": "brave-today-cdn.brave.com", "policy": "custom", "mode": "force-https", "pins": >
       { "name": "p3a.bravesoftware.com", "policy": "custom", "mode": "force-https", "pins": "bra>
       { "name": "p3a-dev.bravesoftware.com", "policy": "custom", "mode": "force-https", "pins": >
 
```
I'm able to browse the feed just fine.
