### ISSUE TITLE
Interstitial pages are missing (i) icon and have unreadable white text on light gray button

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14633]
## Description 
Interstitial pages are missing (i) icon and have unreadable white text on light gray button

## Steps to Reproduce

   1.  new profile
   2.  search for `unstoppable` or `decentralized`
   2.  flip `Enable decentralized DNS` to `Enabled`
   3.  relaunch
   4.  load `brave.crypto`
   5.  look at the resulting interstitial page; apologies if this is the new material design, and I just missed it?

## Actual result:

<img width="871" alt="Screen Shot 2021-03-10 at 5 35 29 PM" src="https://user-images.githubusercontent.com/387249/110722419-0ce8f200-81c7-11eb-9c69-93030665a1fe.png">

1. There's no (i) icon
2. The button text is very hard to read against the light gray button color

## Expected result:
<img width="1134" alt="110041963-d6f4cb00-7cf9-11eb-8f5b-665af05560d7" src="https://user-images.githubusercontent.com/387249/110722490-330e9200-81c7-11eb-9ec2-27134c36abdf.png">

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.23.31 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

Again, apologies, @karenkliu if I missed this; still catching up with material design/Figma assets/flow.  Also, cc: @yrliou as a heads-up, on the off chance I caught a bug

**Comment by yrliou** [comment]
probably regressed from chromium upgrade, I'll check.

**Comment by yrliou** [comment]
Ugh, it was missing when I did a refactor when adding DNS support, will open a PR for it. Thanks for the report.

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build

Brave | 1.23.35 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)

Tested both light and dark themes

| Light (ENS) | Light (Unstoppable) | Dark (ENS) | Dark (Unstoppable) |
|------|------|--------|------|
<img width="846" alt="Screen Shot 2021-03-12 at 8 24 30 AM" src="https://user-images.githubusercontent.com/387249/110968608-98b86680-830c-11eb-80cc-6298ffe160ce.png"> | <img width="840" alt="Screen Shot 2021-03-12 at 8 24 33 AM" src="https://user-images.githubusercontent.com/387249/110968616-9bb35700-830c-11eb-8dea-6579781aa0d5.png"> | <img width="846" alt="Screen Shot 2021-03-12 at 8 24 59 AM" src="https://user-images.githubusercontent.com/387249/110968615-9b1ac080-830c-11eb-8e1e-d6dffdeb5462.png"> | <img width="1006" alt="Screen Shot 2021-03-12 at 8 25 07 AM" src="https://user-images.githubusercontent.com/387249/110968611-9a822a00-830c-11eb-95a8-e415d85d44e4.png">
