### ISSUE TITLE
Chrome.send should be domain specific

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1463]
We should prefix chrome send command.

`chrome.send('createWalletRequested', [])` -> `chrome.send('brave_rewards.createWalletRequested', [])`

**Comment by jasonrsadler** [comment]
cc @bbondy @NejcZdovc Does this apply to other things other than rewards?

**Comment by bbondy** [comment]
was this closed intentionally?

**Comment by jasonrsadler** [comment]
It got closed from merge but I reopened with question

**Comment by NejcZdovc** [comment]
I created this only for rewards. If we want to have this all across let's open another issue
