### ISSUE TITLE
Incorrect text on Rewards reset modal

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#14630]
Incorrect text is appearing on the Rewards page reset modal:

<img width="606" alt="Screen Shot 2021-03-10 at 3 10 26 PM" src="https://user-images.githubusercontent.com/5995084/110691239-e8831a80-81b2-11eb-9d00-ff01728859ac.png">

The text should read `30 BAT`.

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` build with the testplan from https://github.com/brave/brave-core/pull/8210

Brave | 1.23.36 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. Opened the browser with a clean profile.
2. Opened the Rewards panel and accepted the UGP grant.
3. Navigated to the rewards page and clicked on the Settings "gear" icon.

<img width="972" alt="Screen Shot 2021-03-12 at 12 48 53 PM" src="https://user-images.githubusercontent.com/387249/110997247-fe6b1980-8331-11eb-8047-e4bc0ff708bf.png">

4. Selected the "Reset" tab.
5. Verified that `30 BAT` was displayed.

<img width="972" alt="Screen Shot 2021-03-12 at 12 48 50 PM" src="https://user-images.githubusercontent.com/387249/110997158-d976a680-8331-11eb-83bf-663123b954e1.png">
