### ISSUE TITLE
Linux Arm64 npm run init fails

### ISSUE THREAD

**Issue by coreybruce** [brave/brave-browser#14639]
Running ```npm run init``` fails and gives an error on Manjaro Arm64

```
npm run init

> brave@1.23.32 init
> node ./scripts/init.js

Performing initial checkout of brave-core
Cloning brave-core [undefined] into /home/corey/Stuff/brave-browser/src/brave...
-------------------------------------------------------------------------------
/home/corey/Stuff/brave-browser/src/brave
> git clone  .

fatal: repository 'undefined' does not exist

npm ERR! code 1
npm ERR! path /home/corey/Stuff/brave-browser
npm ERR! command failed
npm ERR! command sh -c node ./scripts/init.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/corey/.npm/_logs/2021-03-11T06_26_49_392Z-debug.log
[corey@manjaro-pi brave-browser]$ npm install

up to date, audited 29 packages in 8s

found 0 vulnerabilities
[corey@manjaro-pi brave-browser]$ npm run init

> brave@1.23.32 init
> node ./scripts/init.js

Performing initial checkout of brave-core
Cloning brave-core [undefined] into /home/corey/Stuff/brave-browser/src/brave...
node:internal/fs/utils:323
    throw err;
    ^

Error: EEXIST: file already exists, mkdir '/home/corey/Stuff/brave-browser/src/brave'
    at Object.mkdirSync (node:fs:1024:3)
    at Object.<anonymous> (/home/corey/Stuff/brave-browser/scripts/init.js:19:6)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -17,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: '/home/corey/Stuff/brave-browser/src/brave'
}
npm ERR! code 1
npm ERR! path /home/corey/Stuff/brave-browser
npm ERR! command failed
npm ERR! command sh -c node ./scripts/init.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/corey/.npm/_logs/2021-03-11T06_31_43_841Z-debug.log
```

## Brave version (brave://version info)
Brave version: 1.23.32

**Comment by coreybruce** [comment]
@mihaiplesa I will do some tests on my Raspberry pi 4

**Comment by coreybruce** [comment]
Still having issues, does anyone want the logs?

**Comment by coreybruce** [comment]
> @coreybruce try with changes from this branch [brave/brave-core#6927](https://github.com/brave/brave-core/pull/6927)

What is the branch called exactly sorry?

**Comment by mihaiplesa** [comment]
@coreybruce mplesa-linux-arm64

**Comment by coreybruce** [comment]
Seems like the branch no longer exists, I checked on Braves branches and it says it doesn't exist and did git checkout and it said ```did not match any file(s) known to git``` it did weirdly work before on my original clone of the repo but I ran into a similar error when doing ```npm run init``` so I thought that maybe doing it on a fresh clone would be better but now the branch no longer exists

**Comment by mihaiplesa** [comment]
Correct, the branch is in brave-core so you just have to pin it in https://github.com/brave/brave-browser/blob/master/package.json#L242

**Comment by coreybruce** [comment]
How do I do that exactly?

**Comment by mihaiplesa** [comment]
Just replace `master` with `mplesa-linux-arm64`.

**Comment by coreybruce** [comment]
Ok thanks for letting me know, I'll get back to you with any feedback!

**Comment by coreybruce** [comment]
Ok so I ran through the instructions again but ran into a issue after changing master to mplesa-linux-arm64v on package.json

```
[corey@manjaro-pi brave-browser]$ npm run init

> brave@1.25.23 init
> node ./scripts/init.js

Performing initial checkout of brave-core
Cloning brave-core [undefined] into /home/corey/Stuff/projects/brave-browser/src/brave...
-------------------------------------------------------------------------------
/home/corey/Stuff/projects/brave-browser/src/brave
> git clone  .

fatal: repository 'undefined' does not exist
```

**Comment by fmarier** [comment]
@coreybruce You might be running into this problem: https://github.com/brave/brave-browser/issues/13631 (i.e. using the wrong version of NPM)

**Comment by coreybruce** [comment]
Ahh I see so it doesn't support the latest npm and needs the older version like 6.14.11 for example? will this also be fixed?

**Comment by mihaiplesa** [comment]
@coreybruce things should be in a better place now and we're also looking at upgrading to newer node and npm.

**Comment by coreybruce** [comment]
> @coreybruce things should be in a better place now and we're also looking at upgrading to newer node and npm.

Great news!

**Comment by bsclifton** [comment]
Thanks for the report @coreybruce 😄 I'm de-duping reports of this issue and have it tracked with https://github.com/brave/brave-browser/issues/19398 in case you wanted to subscribe 😄

**Comment by coreybruce** [comment]
> Thanks for the report @coreybruce smile I'm de-duping reports of this issue and have it tracked with #19398 in case you wanted to subscribe smile

always glad to help out and thanks for the update! :smile:
