### ISSUE TITLE
south park episode southpark.cc.com not working

### ISSUE THREAD

**Issue by bruhdev1290** [brave/brave-browser#14649]
## Description 

   1. go to https://southpark.cc.com/episodes/0ncw71/south-park-south-parq-vaccination-special-season-24-ep-2
   2.  and try to play it 
   3. and it will say service unavailable 

## Reproduces how often: 
 easy to reproduce no steps required

## Brave version (brave://version info)
 

1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
--

3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
--

Windows 10 OS Version 2009 (Build 19042.867)
--

## Version/Channel Information:
 it happens to the stable beta and nightly channel

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes and no ads are able to play however the episode is unable to play when the brave shield is disabled
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no 
- Is the issue reproducible on the latest version of Chrome? no, it works on chrome fine

**Comment by ryanbr** [comment]
Hey @bruhdev1290 

Just tested this, no issues here.  Would update to 1.21.76, But also check that `brave://settings/?search=widevine` is enabled.

Video played fine (US IP), if you're using a VPN this may affect video playback also.

**Comment by bruhdev1290** [comment]
@ryanbr I updated to 1.21.76 and enabled widevine and I'm not using a VPN still having the problem

**Comment by ryanbr** [comment]
Try in Private window mode, also trying in new Brave profile. Just re-tested now: https://gif.fanboy.co.nz/gif/southpark.gif
