### ISSUE TITLE
Brave processes opened with `--field_trial_handle`

### ISSUE THREAD

**Issue by nkh** [brave/brave-browser#14640]
Enough!

![Screenshot_20210311_111332](https://user-images.githubusercontent.com/45409/110773457-0dcc6300-825d-11eb-988e-51752495dde5.png)

**Comment by diracdeltas** [comment]
@moritzhaller @iefremov is this expected?

**Comment by iefremov** [comment]
Hi @nkh , can you share your concerns about it?

@diracdeltas yes, this switch has always been around

**Comment by bsclifton** [comment]
Please note these are NOT Google field trials. The variations shown in brave://version are Brave specific variations

@iefremov what is the command line to disable? `--disable-field-trial-config`?

**Comment by iefremov** [comment]
@bsclifton, that one only disables "testing" field trial config that we never use. One can disable fetching the seed by specifying fake variations url, like `--variations-server-url=http://localhost/`

**Comment by iefremov** [comment]
but note that, as I've mentioned, it has nothing to do with the presence of `--field-trial-handle`

**Comment by wknapik** [comment]
I'm guessing, given that the screenshot is from `htop` (rather than plain `ps`, or `pgrep`), @nkh might be attributing the large number of processes and high cpu/memory consumption to the field trials. Can anyone comment on that?

**Comment by nkh** [comment]
my concern is that I can't work when the browser uses all resources and
pushed code to the swap

I discovered this last year when my GPU fan got wild

I just left my box untouched all night, none of my applications running
(well vim), there can be other processes from the distro of course, and
only field-trials running, this morning I had 2 GB less memory. this
doesn't happen when no field-trials are running

Don't get me wrong, I am happy to help with resources for testing, when I
not working

**Comment by iefremov** [comment]
@nkh memory hogging basically has nothing to do with field trials. What you see in `htop` is a bunch of Renderer processes that are spawned for handling tabs of your browser. This is how any Chromium-based browser works (including Chrome itself).

There are known problems with GPU in Chromium and its forks (including Brave): sometimes the GPU process can consume a pretty lot of memory/CPU (when running using a certain combo of GPU/OS/driver/browser version). Typically, disabling `Use hardware acceleration when available` in `chrome://settings` helps to workaround. Sometimes, just updating browser to a newer version solves the issue

**Comment by nkh** [comment]
Are you kidding me or yourself?

![Screenshot_20210316_233353](https://user-images.githubusercontent.com/45409/111388883-5dbd8680-86b0-11eb-8fe6-d884c4fbddc8.png)

**Comment by nkh** [comment]
and the browser had an update yesterday

**Comment by nkh** [comment]
![Screenshot_20210323_111600](https://user-images.githubusercontent.com/45409/112131116-7c001680-8bc9-11eb-87b5-30b09540fa38.png)
![Screenshot_20210323_111458](https://user-images.githubusercontent.com/45409/112131118-7c98ad00-8bc9-11eb-8986-1e9731ebeba1.png)

**Comment by Trawets** [comment]
Apparently still not solved.   I've the same issue, it's running my GPU at a mad pace.  I've tried using the "--disable-field-trial-config" but when I check the command line in the process viewer it shows that it's added another switch to enable it as well which seems to override my setting.  Is Brave-browser doing crypto mining using my PC?  because its sure running at a high rate!  I will stop using Brave for now, since I want to control what runs on my machine...

**Comment by nkh** [comment]
@bsclifton this ticket is from march, I understand that development is complicated but not hogging someone else's resource without his consent can't be that difficult.

unfortunately I don't recomment brave anymore to people who ask
https://www.reddit.com/r/browsers/comments/oa2lx2/best_browser_2021/

**Comment by nkh** [comment]
@bsclifton 

You are still hogging my resources without my consent, are you going to do anything about this?

![screenshot_2021-12-09_14-22-13](https://user-images.githubusercontent.com/45409/145414643-24d47114-7f22-4dcc-a343-2daa03c4d633.png)

**Comment by bsclifton** [comment]
Closing as there isn't a problem with original complaint. There are duplicate reports for the CPU usage - I'll close in favor of https://github.com/brave/brave-browser/issues/21630

**Comment by darkworks** [comment]
> Apparently still not solved. I've the same issue, it's running my GPU at a mad pace. I've tried using the "--disable-field-trial-config" but when I check the command line in the process viewer it shows that it's added another switch to enable it as well which seems to override my setting. Is Brave-browser doing crypto mining using my PC? because its sure running at a high rate! I will stop using Brave for now, since I want to control what runs on my machine...
> 
> There is no point having an open source browser if you guys can run random code as a field trial any time without my consent or knowledge.

hmmmm in my tests all chromium based browsers have high cpu usage issue on linux , i had issue even with firefox too it use high cpu when there is canvas graphics type page is loaded . there is need of some low cpu usage browser. these big browsers are cancer
