### ISSUE TITLE
Some svgs are wrongly/not displayed in Brave

### ISSUE THREAD

**Issue by ValdoGhafoor** [brave/brave-browser#14647]
## Description 
When displayed as <svg> tags, some svgs are not wrongly displayed/not displayed at all.
Tried in chrome and it works.

## Steps to Reproduce
   1.  Open brave
   2. Navigate to https://jsfiddle.net/yoswkzaj/

## Actual result:

Only one SVG is displayed (I added a working one for comparison)

## Expected result:

Three working SVGs

## Reproduces how often: 
I don't know what is causing the bug but on 100 of my icons, 8 are not working in Brave.

## Brave version (brave://version info)

1.21.74 Chromium: 89.0.4389.72 (Official Build) (arm64)
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.3 (Build 20D91)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
   No
- Does the issue resolve itself when disabling Brave Rewards? 
   No
- Is the issue reproducible on the latest version of Chrome? 
   No

## Additional

It seems to be partially working in some situations, like here
https://jsfiddle.net/v5prwy1e/

**Comment by rebron** [comment]
![Screen Shot 2021-05-14 at 1 12 43 PM](https://user-images.githubusercontent.com/5951041/118324075-69fa7000-b4b6-11eb-8093-84c3f91826cd.png)
@ValdoGhafoor Looks like with shields down, this is working?

**Comment by rebron** [comment]
@ryanbr Shields down as the appropriate workaround/fix for this?

**Comment by ryanbr** [comment]
Has it been modified since? I'm getting all 3 icons in Brave @rebron  @ValdoGhafoor

**Comment by ValdoGhafoor** [comment]
It has been fixed since yes
