### ISSUE TITLE
Debug build crashes when starting Rewards from the NTP widget

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#14642]
While debugging https://github.com/brave/brave-browser/issues/14413, I noticed that starting Rewards from the NTP widget was causing a crash. The issue is that the NTP widget directly enables auto-contribution and ads, but no check is made to ensure that the ledger process is started/initialized. Since the auto-contribution function records P3A stats that involve database queries, we crash as we can't locate the relevant table.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.23.40 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 10.15.7 (Build 19H524)
```

Verified test plan from https://github.com/brave/brave-core/pull/8220 ~5x (issue only occurred on debug build, not on release build). 
- Used staging env and confirmed UGP grant message shown on widget.
- Confirmed Ads and AC enabled on brave://rewards.

Verified able to join Rewards from panel, brave://welcome, and brave://rewards as well.
- Used staging env and confirmed UGP grant message shown on panel and brave://rewards as appropriate.
- Confirmed Ads and AC enabled on brave://rewards.
