### ISSUE TITLE
[Android] Rewards panel looks weird on a page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14646]
## Description 
Rewards panel looks weird on a page

## Steps to reproduce 

   1. Clean install 1.21.76
   2. Open a page 
   3. Set wallet to staging 
   4. Relaunch and click on panel, panel layout looks weird due to publisher info 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/110820115-b5aa5680-8286-11eb-8218-d4c5122d6bfb.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/110820143-be9b2800-8286-11eb-984b-794918110942.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Most likely YES
- Can you reproduce this issue with the current Play Store Beta version? Most likely YES
- Can you reproduce this issue with the current Play Store Nightly version? Most likely YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version:10
   
## Brave version
1.21.76

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya

**Comment by Miyayes** [comment]
Going to close this out as this will be superseded in 1.35 with the new panel design.
