### ISSUE TITLE
Closing a tab in browser window also closes an app window

### ISSUE THREAD

**Issue by derekantrican** [brave/brave-browser#14659]
## Description 
Closing a tab in a normal browser window will also close an app browser window if it is open

Screenshot:
![braveTabIssue](https://user-images.githubusercontent.com/1558019/110872771-4bdd7d00-8285-11eb-905e-6794199d26cf.gif)

## Steps to Reproduce
1. Open Brave along with a couple tabs
2. Start a command similar to the following: C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe --app=https://hulu.com
3. Close a tab in the first window
4. Notice that the app window also closes

## Expected result:

App window should stay open

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Windows 10 OS Version 1909 (Build 18363.1440)
JavaScript | V8 8.9.255.20
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --no-startup-window /prefetch:5 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,SafetyTip,WinrtGeolocationImplementation --disable-features=AutofillEnableAccountWalletStorage,DirectSockets,IdleDetection,AutofillServerCommunication,LangClientHintHeader,NetworkTimeServiceQuerying,PasswordCheck,TextFragmentAnchor,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,NotificationTriggers,WebOTP,PrivacySettingsRedesign,TabHoverCards,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end --enable-features=WinrtGeolocationImplementation,SafetyTip,AutoupgradeMixedContent,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,WebUIDarkMode,LegacyTLSEnforced --disable-features=SafeBrowsingEnhancedProtectionMessageInInterstitials,SafeBrowsingEnhancedProtection,SignedExchangeSubresourcePrefetch,TabHoverCards,PrivacySettingsRedesign,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,TextFragmentAnchor,WebOTP,NotificationTriggers,NetworkTimeServiceQuerying,LangClientHintHeader,PasswordCheck,IdleDetection,AutofillServerCommunication,DirectSockets,AutofillEnableAccountWalletStorage --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\derek\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

**Comment by rebron** [comment]
cc: @kjozwiak Can you see if you can reproduce this when you get a chance? I tried on Windows and 1.24.85 following the STRs and could reproduce. 

@derekantrican I'm wondering if this has something to do with any extensions you might have installed?

**Comment by derekantrican** [comment]
Not sure. I haven't seen it for a long time. I did actually see it recently (after not seeing it for a long time), but Brave was out of date so I just updated

**Comment by kjozwiak** [comment]
@rebron couldn't reproduce it on `Win 10 x64` either using the following build:

```
Brave | 1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit)
--- | ---
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Windows 10 OS Version 2009 (Build 19042.964)
```

Basically used the same STR @derekantrican mentioned via https://github.com/brave/brave-browser/issues/14659#issue-829636381:

* opened `1.24.85 Chromium: 90.0.4430.212` via a new profile/install
* opened ~5 different tabs
* launched `C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe --app=https://hulu.com` via `Run`
* closed several of the tabs and the Hulu app stayed opened

**Comment by kjozwiak** [comment]
@derekantrican please re-open a new issue if you start seeing this again 👍
