### ISSUE TITLE
Add 5px margin bottom on NTPSI logo.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#14652]
## Description 

Add 5px margin bottom on the publisher logo for NTPSI
![image](https://user-images.githubusercontent.com/318119/110844309-e088b080-826e-11eb-8ed9-2e9020bf6cae.png) so we can avoid this tight hugging.

## Steps to reproduce 

   Needs cases where NTPSI logo is using full size.

## Actual result 

Can see image above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@jamesmudgett 
![Screenshot_20210312-120754](https://user-images.githubusercontent.com/5146988/110973803-b77a2580-832b-11eb-9783-444ee7ef654c.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.23.63 x63 beta build

- Verified from https://github.com/brave/brave-browser/issues/14652#issuecomment-797628613

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/113735250-fbc2d080-96f3-11eb-9e37-6d51a2bfb6b4.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/113735307-0aa98300-96f4-11eb-8e8f-1bf0a67c6d5c.png>
