### ISSUE TITLE
macOS users stuck in bad Sync state

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#14655]
## Description 

Users report that Sync was working until recently. While it appears to be setup correctly, the Sync data types section is being reset every time the user navigates away from the Sync settings page. Whether using the `Sync everything` option or toggling individual data types, after navigating away and back to the page, these settings are reset.

Further, the `Leave Sync chain` button is also un-responsive, leaving users in bad state that they cannot seem to reset. 

cc @AlexeyBarabash 
## Brave version (brave://version info)

Version 1.21.74 Chromium: 89.0.4389.72 (Official Build) (x86_64)

## Version/Channel Information:

I cannot personally reproduce this issue -- both users appear to be using Brave stable.

## Miscellaneous Information:

Original user thread: https://community.brave.com/t/sync-settings-dont-persist-on-mac/215813 
One user left some console information showing what happens when `Sync everything` option is used and what happens when toggling individual items:
```
Uncaught TypeError: Cannot read property 'appsSynced' of undefined
    at HTMLElement.handleSyncAllDataTypesChanged_ (shared.rollup.js:2949)
    at HTMLElement.onSyncDataRadioSelectionChanged_ (shared.rollup.js:2949)
    at HTMLElement.handler (polymer_bundled.min.js:1)
    at dispatchNotifyEvent (polymer_bundled.min.js:1)
    at Object.runNotifyEffect [as fn] (polymer_bundled.min.js:1)
    at runEffectsForProperty (polymer_bundled.min.js:1)
    at runNotifyEffects (polymer_bundled.min.js:1)
    at HTMLElement._propertiesChanged (polymer_bundled.min.js:1)
    at HTMLElement._flushProperties (polymer_bundled.min.js:1)
    at HTMLElement._flushProperties (polymer_bundled.min.js:1)
handleSyncAllDataTypesChanged_ @ shared.rollup.js:2949
onSyncDataRadioSelectionChanged_ @ shared.rollup.js:2949
handler @ polymer_bundled.min.js:1
dispatchNotifyEvent @ polymer_bundled.min.js:1
runNotifyEffect @ polymer_bundled.min.js:1
runEffectsForProperty @ polymer_bundled.min.js:1
runNotifyEffects @ polymer_bundled.min.js:1
_propertiesChanged @ polymer_bundled.min.js:1
_flushProperties @ polymer_bundled.min.js:1
_flushProperties @ polymer_bundled.min.js:1
_invalidateProperties @ polymer_bundled.min.js:1
_setProperty @ polymer_bundled.min.js:1
Object.defineProperty.set @ polymer_bundled.min.js:1
select_ @ shared.rollup.js:2574
onClick_ @ shared.rollup.js:2574
handler @ polymer_bundled.min.js:1
```
```
shared.rollup.js:58 Uncaught Error: Assertion failed
    at assert (shared.rollup.js:58)
    at HTMLElement.onSingleSyncDataTypeChanged_ (shared.rollup.js:2949)
    at HTMLElement.handler (polymer_bundled.min.js:1)
    at HTMLElement.fire (polymer_bundled.min.js:1)
    at HTMLElement.toggleState_ (shared.rollup.js:1654)
    at HTMLElement.onClick_ (shared.rollup.js:1654)
    at HTMLElement.handler (polymer_bundled.min.js:1)
assert @ shared.rollup.js:58
onSingleSyncDataTypeChanged_ @ shared.rollup.js:2949
handler @ polymer_bundled.min.js:1
fire @ polymer_bundled.min.js:1
toggleState_ @ shared.rollup.js:1654
onClick_ @ shared.rollup.js:1654
handler @ polymer_bundled.min.js:1
```

**Comment by jonyo** [comment]
To be clear, the second error happens when you toggle one of the individual sync options like `Apps`, it is not part of what happens when you click `Sync Everything`.  I gave both errors since they were significantly different depending on which thing you are clicking on, just in case it helped. 😄

**Comment by czettnersandor** [comment]
I have the same error on Linux and I can't make sync working at all. My version:
Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)

**Comment by pcantalupo** [comment]
Sync used to work for me until recently. Not sure what has changed.  I'm on Mac Catalina 10.15.7 and using the most recent version of Brave 1.31.88.   I tried to leave the Sync Chain but when I restart Brave I'm still in the same sync chain.

Isn't there a way to completely remove Sync and then set it up again?

**Comment by tomocrafter** [comment]
I have same error on Windows 10 Version 21H1 (Build 19043.1288) | 1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
Closing as stale - there is an ongoing issue. See https://github.com/brave/brave-browser/issues/35042 for more info. Folks affected above could have history enabled and maybe that was hitting the limit. More info in other issue
