### ISSUE TITLE
rewards and other custom chrome:// pages need favicon

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1466]
## Description 
Custom chrome:// pages need favicons. For pages like Rewards, which is included in the on-boarding flow, this should be done sooner rather than later, it looks bad without a favicon.

## Steps to Reproduce

   1. Navigate to chrome://rewards or chrome://adblock

## Actual result:
No favicon:
<img width="554" alt="screen shot 2018-10-09 at 7 36 57 am" src="https://user-images.githubusercontent.com/28145373/46666960-23be3100-cb96-11e8-8468-1f0c2b9036f6.png">

## Expected result:
Custom pages should have favicon like welcome page.

## Reproduces how often: 
easy

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes
- Does it reproduce on browser-laptop? n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Similar to https://github.com/brave/brave-browser/issues/1278 but that issue is specific to Task Manager.

**Comment by srirambv** [comment]
Action items from @davidtemkin 
>We should create new favicons (most obviously visible in tabs, but also potentially in bookmarks, etc) for pages like:
>
>-- Rewards (currently a generic document icon)
>-- Settings (currently the Chrome-default icon)
>
>I assume there are others.
>
>It looks like we already have such an icon for brave://welcome, which is great.

**Comment by NejcZdovc** [comment]
fixes in https://github.com/brave/brave-core/pull/756

**Comment by LaurenWags** [comment]
@rossmoody @NejcZdovc could one of you add a test plan for this issue please?

**Comment by NejcZdovc** [comment]
@LaurenWags test plan is quite simple. Go to rewards setting page and make sure that settings tab has rewards logo as favicon

![image](https://user-images.githubusercontent.com/9574457/50365050-113b7d00-0573-11e9-8485-4706fa6ac06d.png)

**Comment by LaurenWags** [comment]
thanks @NejcZdovc ! Wasn't sure if other pages were included with this issue as well.

**Comment by rossmoody** [comment]
Yeah maybe the scope of this one could be just for the rewards favico. We have a similar issue with a larger collection that might need revisited soon: https://github.com/brave/brave-browser/issues/1278

**Comment by GeetaSarvadnya** [comment]
Verification pased on 


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

- Verified the STR mentioned in the description
![image](https://user-images.githubusercontent.com/38657976/50477218-5affe980-09f1-11e9-823e-a6969d2b5025.png)
- Favicon for welcome page is missing (Logged new issue #2747)
