### ISSUE TITLE
Auto-excluded publishers need information for Rewards Panel

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#1467]
## Description 
Auto-excluded publishers need information displayed on Rewards panel. Currently, auto-excluded publishers do not retain any data to display. Need to capture this information but not log duration or list in auto-contribute

## Steps to Reproduce

   1. Visit auto-excluded site with Rewards enabled
   2. Open rewards panel

## Actual result:

Standard wallet summary is shown

## Expected result:
Site favicon and site specific contribution information

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
closed in https://github.com/brave/brave-core/pull/590

**Comment by jasonrsadler** [comment]
@NejcZdovc @LaurenWags Addressed via Slack

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified with steps from Test Plan and several sites provided via slack
