### ISSUE TITLE
[Linux] Brave does not respect system light/dark theme

### ISSUE THREAD

**Issue by matfantinel** [brave/brave-browser#14685]
## Description 
On a Linux system, Brave has its own controls for light/dark mode, but it does not respect the system's overall theme. If the option to use the "Gtk" theme is chosen, the Brave UI does respect the dark mode, however it doesn't set the `prefers-color-scheme` media query. This is a bug inherited from Chromium, and is being tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=998903

I know this should be fixed upstream, but Google doesn't seem to care about it enough to justify the effort. One of the latest comments mentions a patch that a user has made, which solves the issue. The patch can be seen [here](https://github.com/qcasey/chromium-patches/blob/main/patches/gtk-dark-mode-switch-fix.patch) in case a similar solution is intended.

## Steps to Reproduce

   1. Open Brave on a Linux system with light theme enabled
   2. Open a website that supports `prefers-color-scheme` query, such as DuckDuckGo
   3. Change system theme to dark mode
   4. Website does not change theme

## Actual result:

This is how Brave and other Chromium browsers behave (left), and how Firefox does (right). Note how in Chromium, the page content doesn't change
![before](https://user-images.githubusercontent.com/24247035/110957053-04f59300-832a-11eb-8b8a-25d70ef24ff9.gif)

## Expected result:

Brave/Chromium (left), Firefox (right)

![after](https://user-images.githubusercontent.com/24247035/110957064-0757ed00-832a-11eb-87bb-748a7f89ba4a.gif)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Haven't tried, but no reason to believe it doesn't happen there

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not related
- Does the issue resolve itself when disabling Brave Rewards? Not related
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:

Latest versions of Ubuntu have a quick Light/Dark mode toggle so it should be really easy to test

**Comment by NumDeP** [comment]
It works alright for me on openSuse, with 'GTK+' and 'Classic'.

**Comment by matfantinel** [comment]
> It works alright for me on openSuse, with 'GTK+' and 'Classic'.

Would you mind sharing what DE and themes you are using?

**Comment by NumDeP** [comment]
DE - Tumbleweed, Colours - Dark, Theme - Classic

I don't know why you mentioned themes in the plural but I did used to have it on Breeze Dark and I think the system naturally changes this for the browser and naturally the sites follow if they have the dark viewing feature, though I'm not to sure.

**Comment by matfantinel** [comment]
@NumDeP hmm I assume the DE is KDE Plasma, Tumbleweed being the distro.

Maybe this detection works on KDE then? I tested on both GNOME (Ubuntu, PopOS) and Pantheon (elementary OS)

**Comment by jmbuhr** [comment]
I can confirm this issue on my system (pop-os / ubuntu). While you can set the theme to `GTK+`, which matches the system theme for the window and titlebar, the actual brave colors only have the options `Light` and `Dark` and not `match system theme` as available on windows and MacOS.
![image](https://user-images.githubusercontent.com/17450586/113669927-bb902d80-96b4-11eb-8855-44031217ca94.png)

**Comment by juligreen** [comment]
Would it be possible to change the theme on the command line with a script?
You could then use something like [darkman](https://gitlab.com/WhyNotHugo/darkman/)

**Comment by dima2306** [comment]
The same is on Fedora34/Cinnamon DE. If I have a classic theme in brave nothing changes when switching to the dark mode. When used GTK+ only the window changes. Is there any chance to respect system preferences? Firefox handles this well.

**Comment by harpreetsb** [comment]
this is a very annoying bug, hope they fix it soon

**Comment by wknapik** [comment]
Works for me on a fresh profile (`brave --user-data-dir="$(mktemp -d)"&`) with the `Brave colors: Dark` setting on up-to-date Arch Linux running `Brave Browser 93.1.29.81` via `brave-bin 1:1.29.81-1`.

Keep in mind that after recent privacy improvements the setting `Trackers & ads blocked (aggressive)` will prevent the dark theme from being requested from the site.

**Comment by esjarc** [comment]
@wknapik The issue was supposed to be about Brave not following the **system**'s theme setting. It is working correctly when manually switching between light and dark theme in Brave's settings.

Some people use [tools](https://extensions.gnome.org/extension/2236/) to automatically change the system theme depending on the time of day. Brave/Chromium is one of the few applications left not following this choice. Firefox on all operating systems and Chromium browsers on Android/macOS/Windows already support this functionality.

There's also an [upstream (Chromium) issue](https://bugs.chromium.org/p/chromium/issues/detail?id=998903) about this. GNOME (libadwaita) is in the process of [implementing](https://gitlab.gnome.org/Teams/Design/settings-mockups/-/issues/27) an official system-wide dark mode. Maybe it would make sense to implement the functionality in Brave by utilizing the upcoming preference in GNOME 42 (not sure about how this will work with KDE/Qt)?

**Comment by wknapik** [comment]
@esjarc ah, I see. So this is about adding the `match system theme` option on Linux?

**Comment by esjarc** [comment]
@wknapik Exactly! (Brave is currently only offering a dark and a light theme, but no option to follow the system theme on Linux.)

**Comment by wknapik** [comment]
@esjarc judging from the `Chromium/waiting upstream` label on this issue, we'll have to wait for an upstream fix.

**Comment by 0xc0000007b** [comment]
> @esjarc judging from the `Chromium/waiting upstream` label on this issue, we'll have to wait for an upstream fix.

That's their own fault then for switching from Muon and putting an Achilles heel into this product. DDG broswer right around the corner. And LibreWolf is a thing as well.

**Comment by satrinity402** [comment]
Still an issue for me. Running Pop OS 21.10

**Comment by hasufell** [comment]
Yeah, end users don't care how you maintain your browser, what libraries etc. you use. They care about the end product. If you don't have the manpower/knowledge to maintain a fork or contribute patches upstream, then that seems like a problematic situation. This reminds me of the Tor projects firefox fork.

**Comment by macdabby** [comment]
still broken for me also, debian bookworm with gnome 42

**Comment by GNUKalashnikov** [comment]
Still Broken for me, Arch Linux, Gnome 42.3, Running Wayland

**Comment by faloi** [comment]
Still broken for me too:

```
OS: Pop!_OS 22.04 LTS x86_64
DE: GNOME 42.1
```

**Comment by waldyrious** [comment]
Quoting @meduzen's [comment](https://github.com/brave/brave-browser/issues/21420#issuecomment-1383484266) from the corresponding issue for Android, in case it helps others who are tracking this issue:

> this [...] is linked to fingerprinting (see https://github.com/brave/brave-core/pull/9735).

> the flag to opt-out of this restriction is at `brave://flags/#brave-dark-mode-block`.

**Comment by N1vBruno** [comment]
> Quoting @meduzen's [comment](https://github.com/brave/brave-browser/issues/21420#issuecomment-1383484266) from the corresponding issue for Android, in case it helps others who are tracking this issue:
> 
> > this [...] is linked to fingerprinting (see [brave/brave-core#9735](https://github.com/brave/brave-core/pull/9735)).
> 
> > the flag to opt-out of this restriction is at `brave://flags/#brave-dark-mode-block`.

It's not the same issue as reported [above](#issuecomment-928968980). It's not related to fingerprint protection but an upstream bug.

**Comment by waldyrious** [comment]
Oh! Apologies for the confusion then! 😅

**Comment by wout** [comment]
Still broken here too.

elementary OS 7 (based on Ubuntu 22.04).

**Comment by Okanda** [comment]
Any news about that?

**Comment by phaalonso** [comment]
Still broken in PopOs and Fedora. In fedora I need to click on use gtk each time that I change to light or dark mode

**Comment by crstmkt** [comment]
Confirm for fedora 37. Cant set to follow system settings.

**Comment by Okanda** [comment]
OK, it works. It respects the GTK theme but not the "prefer-light" or "prefer-dark" option of the theme. 
It makes the Gnome's "Dark mode" option useless.

**Comment by rc2dev** [comment]
Chromium 113.0.5672.126 on Fedora already respects my system theme.
![Chromium](https://github.com/brave/brave-browser/assets/4497566/a69e9e09-e376-4e0e-a273-a83d760da86e)

**Comment by GoldenGlimpse** [comment]
Every time i restart Brave, the theme is white. I always have to go to Settings > Appearance > Brave colors (it is set to dark as default), but have to hit light and then back to dark so it takes on the dark theme. Pretty annoying. 
Using Classic Theme, not gtk since i don't like it and some pages show in white on gtk.

Linux Mint 21.1 (Vera), Ubuntu 22.04 jammy
Brave Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (64-bit)

**Comment by Alanzphy** [comment]
@GoldenGlimpse I have the same problem, apparently it started to happen after the 1.52 update of brave where they added vertical tabs
Arch Linux 6.3.5-arch1-1
Brave Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (64-bit)

**Comment by GoldenGlimpse** [comment]
@Alanzphy That did the trick. Thanks.

**Comment by waldyrious** [comment]
As far as I can tell, Brave v1.52.117 (released May 31, 2023) was the version that [bumped](https://github.com/brave/brave-browser/issues/30679) Chromium [from 113.0.5672.126 to 114.0.5735.90](https://chromium.googlesource.com/chromium/src/+log/113.0.5672.126..114.0.5735.90?pretty=fuller&n=1000), thus bringing the system-based dark mode switching support discussed in [Chromium bug #998903](https://bugs.chromium.org/p/chromium/issues/detail?id=998903).

I can confirm this version of Brave respects my system theme (I'm on Ubuntu 22.04, if that matters). I don't see the issue described above, of Brave always starting in light mode. I mean, the option in `Settings > Appearance > Brave colors` is set to "Light", but the UI still respects the system theme if I switch to dark mode system-wide. Shouldn't this issue be closed? Or is there anything else missing (maybe a new "system" option in the `Settings > Appearance > Brave colors` dropdown)?

**Comment by brunolpsousa** [comment]
> Shouldn't this issue be closed? Or is there anything else missing (maybe a new "system" option in the `Settings > Appearance > Brave colors` dropdown)?

The "System" option is missing from the `Brave colors`, just like the Windows (and Mac, I guess) version.

For me, Brave always starts using the "always dark" or "always light" setting, but follows the system if I change the system theme manually (I'm using GNOME 44.2 with Arch). It's not good now as it is, it should have a "System" option.

Idk, maybe [brave_dark_mode_utils_linux.cc](https://github.com/brave/brave-core/blob/master/browser/themes/brave_dark_mode_utils_linux.cc) needs some changes?

**Comment by Lazerbeak12345** [comment]
I notice some people are saying it was fixed at some point - but the last time I saw it working was 2019 or so (I had been using Firefox from 2020-2022). It didn't work even before the vertical tabs feature. Test case: set [search.brave.com](https://search.brave.com) theme to "follow system", set brave theme to "dark". Brave search page is light theme-d.

OS: Fedora Linux 38 (Workstation Edition) x86_64
Host: 4180BV1 (ThinkPad T420)
Kernel: 6.3.11-200.fc38.x86_64
Brave (though as I said it's been broken for a very long time): Brave Browser 114.1.52.130

**Comment by StefanTT** [comment]
For me (Gnome on Arch) it was fixed for several weeks / some months. Recent versions broke it again. It is working on Chromium btw.

**Comment by cmm** [comment]
Brave indeed does not respect `/org/gnome/desktop/interface/color-scheme` any more, or at least this preference does not propagate to sites.

I'm not sure which version of Brave broke this, but it definitely used to work right after Brave rebased on Chromium 114, and it still works in Chromium itself.

**Comment by brunolpsousa** [comment]
> Brave indeed does not respect `/org/gnome/desktop/interface/color-scheme` any more, or at least this preference does not propagate to sites.
> 
> I'm not sure which version of Brave broke this, but it definitely used to work right after Brave rebased on Chromium 114, and it still works in Chromium itself.

[PR 19000](https://github.com/brave/brave-core/pull/19000) implemented changes to prevent system theme from affecting the Brave theme.

The "waiting upstream" label should be removed as it is now solely up to the Brave team.

**Comment by StefanTT** [comment]
Too bad that there is no option to honor the system theme. I have a hotkey that changes between light and dark mode for the desktop to switch between day and evening/night.

**Comment by popy2k14** [comment]
I am using an mint applet to change between system light an dark theme and also expected that there is an option in brave to follow the system theme. Which it sadly does not. Chrome has the option in 116.0.5845.180.

Any chance to get that back?

**Comment by cmm** [comment]
I wonder just how low-priority Linux desktop is for Brave.  Unprovoked and unexplained regressions like this seem borderline insulting really.

I mean, how hard would it be to just roll back the change that caused this (#19000.  I honestly cannot parse what that change was even supposed to fix -- neither from its linked issue nor from the PR text)?  Is there some decision-making disfunction involved?  What can users do about this, apart from bumping this issue (which evidently helps not at all)?

**Comment by Lazerbeak12345** [comment]
Arguably we could just move to librewolf or some other privacy browser. I've been thinking about it for awhile considering every single aspect of automatic theming works in nearly every single other browser on Linux, we aren't really forced to use brave.

**Comment by MartinNowak** [comment]
> I wonder just how low-priority Linux desktop is for Brave. Unprovoked and unexplained regressions like this seem borderline insulting really.

It was a slightly [simplified/misunderstood bugfix](https://github.com/brave/brave-core/pull/18922), other [users had complained](https://github.com/brave/brave-browser/issues/30766) that their brave theme now follows the linux system theme, despite a different selection in Brave's settings.
The maintainers have [already acknowledged](https://github.com/brave/brave-core/pull/18922#issuecomment-1713316346) the mishap.

Let's keep a [healthy discussion](https://tylercipriani.com/blog/2023/01/15/entitlement-burnout-and-toxicity/) @cmm.

**Comment by cmm** [comment]
> > I wonder just how low-priority Linux desktop is for Brave. Unprovoked and unexplained regressions like this seem borderline insulting really.
> 
> Let's keep a [healthy discussion](https://tylercipriani.com/blog/2023/01/15/entitlement-burnout-and-toxicity/) @cmm.

I do apologize for my poor choice of words, how about s/seem borderline insulting/are extremely disappointing/.  Still, the picture as seen from this end is: this ticket still has incorrect tags (it is not waiting for upstream); there are several dups that are not merged with it or closed; the developer said they will "should consider" fixing the regression.  All that does not inspire much confidence!

[ To forestall the predictable "how dare you, the product is free!": if there were an option to pay for Brave, I absolutely would.  Brave fills my needs pretty much exactly, namely "follows Chromium so no random incompatibilities, first-class privacy and ad-blocking features, Linux and Android support, sync".  I have no idea why there is no normal payment option instead of (or in addition to) all the crypto silliness. ]

**Comment by SlowNicoFish** [comment]
This seems to be the case as of now. The internal brave sites change colors on Gnome 45 Wayland with gtk theme but the sites i visit does not recognize dark/light mode.
[brave.webm](https://github.com/brave/brave-browser/assets/19305293/4ebb7847-acfa-4945-9e9b-7d439699323c)

**Comment by archerallstars** [comment]
Chrome respects system them on my GNOME 45, but Brave doesn't. I doubt this issue is related to Chromium upstream. 

There's also a thread requesting this on the community forum: https://community.brave.com/t/brave-colors-should-be-able-to-change-with-linux-system-gtk-theme/282224/6

**Comment by Lazerbeak12345** [comment]
Thank you so much! I once I get this update I can test if it fixed a few associated issues 😊

**Comment by kjozwiak** [comment]
The above requires `1.61.93` or higher for `1.61.x` verification 👍

**Comment by rebron** [comment]
Latest release 1.61.100 has this fix.

**Comment by brunolpsousa** [comment]
> > Latest release 1.61.100 has this fix.
> 
> Can verify, Brave's Chrome does now sync with the system. However, webpages (when set to match system theme), like [search.brave.com](https://search.brave.com) **do not**. Should this be reported separately?
> 
> Happens on both GNOME and KDE, both X11 and Wayland. Does not (under any combination) happen on Firefox (so it's not a bug with the website).
> 
> My workaround for the last few years has been to use webpage-specific settings when possible, the Stylus extension when that isn't possible, and suffer from blindingly bright screens otherwise. Many webpages that have dark themes don't have settings for it and also don't have a Stylus sheet for them either.

It's working fine for me on Arch with GNOME 45 Wayland, flatpak version (but I have tested the nightly from AUR and it also worked as expected).

Does this also happen for you if using the default Adwaita theme and a fresh Brave profile? Since the fix worked for me and for the Brave devs, it should be something related with your system and/or configurations.

PS: Thanks for the Brave team for implementing this for us Linux users! ^-^

**Comment by Lazerbeak12345** [comment]
Ah. That might be related. I'm not running a sandboxed version.

On Fedora I'm using the `.rpm` (through `dnf`)

On Funtoo I'm using `www-client/brave-bin`

**Comment by Lazerbeak12345** [comment]
Edit, at a glance, a fresh profile does work.

I still think this is a bug though - since I'd have to lose all my settings, bookmarks, extensions, and passwords to be able to fix it.

**Comment by SlowNicoFish** [comment]
Can confirm it works on EndeavourOS with https://aur.archlinux.org/packages/brave-bin

**Comment by nandorholozsnyak** [comment]
:rocket: Waiting for this for years. Works on Pop!_OS 22.04 LTS x86_64 GNOME 42.5 .

**Comment by ahydronous** [comment]
It is working for me with "Classic", but choosing "GTK" keeps Brave stuck in the light theme, even when forcing it to "Dark".

**Comment by madhums** [comment]
Not working! Re-open please!!

**Comment by Lazerbeak12345** [comment]
@madhums open a new issue please

**Comment by kjozwiak** [comment]
> Not working! Re-open please!!

As per the comment via https://github.com/brave/brave-browser/issues/14685#issuecomment-1860643715, please open a new issue if you're still having issues and include as much information as possible. You can create a new issue via [here](https://github.com/brave/brave-browser/issues/new?assignees=&labels=OS%2FDesktop&projects=&template=desktop.md&title=).

**Comment by madhums** [comment]
Ok, so I uninstalled the flatpak version of brave, added the rpm repo and installed via that. It seems to work this way. So not sure what's really going on.

**Comment by quazar-omega** [comment]
@madhums The Flatpak is behaving correctly for me on Fedora 40 Kinoite, it changes the theme live, based on the system

**Comment by b-hayes** [comment]
So this is resolved? fresh install on Ubuntu, and I'm having this problem. How can I fix?
