### ISSUE TITLE
Css not rendered correctly

### ISSUE THREAD

**Issue by darklight147** [brave/brave-browser#14688]
## Description 

Github css or https://github.com/org/{someorganisation}/people not rendered correctly 
![image](https://user-images.githubusercontent.com/39389636/110974086-6b94a400-835e-11eb-9056-6a475b12e373.png)

## Steps to Reproduce

visit https://github.com/org/{someorganisation}/people

Change someorganisation with an organisation you belong to so you can see the people in it

## Actual result:

Miss rendered Css look picture above

## Reproduces how often: 

Always,

## Brave version (brave://version info)

1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? didnt try
- Can you reproduce this issue with the nightly channel? didnt try
- I tested on firefox and opera and it rendered correctly but not on brave

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by darklight147** [comment]
Closed cz when i disabled the tip button from brave://rewards on github it fixed the css, i guess cz brave was adding that "tip" button to the css

**Comment by bsclifton** [comment]
cc: @emerick

**Comment by emerick** [comment]
Looks similar to https://github.com/brave/brave-browser/issues/9024, which was pre-Greaselion. The fix then was to just remove tip buttons from the people page, but maybe we can handle this a little better now. It seems to me that this is occurring to people who have admin privileges in the given org (perhaps you could confirm @darklight147?)

**Comment by darklight147** [comment]
@emerick yes exactly, in my case it happened on an organization under my name
