### ISSUE TITLE
Fix Linter issues

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#14689]
## Description 

```
Applying patches:..All patch apply done.
There were 2 Chromium code patch updates to apply.
1 successful patches:
build/toolchain/win/setup_toolchain.py
  - Patch applied because: The target file was modified since the patch was last applied.
-------------------------------
1 failed patches:
C:\work\brave-browser\src\brave\patches\components-component_updater-component_updater_service.h.patch
  - Patch applied because: The .patch file was modified since last applied.
  - Error - Program git exited with error code 128.
error: corrupt patch at line 6
```

` ERROR: /home/ubuntu/workspace/pr-brave-browser-tor_controlport_str_overflow-pre-init/components/ipfs_ui/components/uninstalledView.tsx:30:5 - if statements must be braced`
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by spylogsster** [comment]
merged

**Comment by emerick** [comment]
Line 6 in this file also needs the leading space. Basically every blank line requires the space.
