### ISSUE TITLE
russian translation of "Blank page" wrong

### ISSUE THREAD

**Issue by stanislavvv** [brave/brave-browser#14692]
## Description 

In brave://settings/newTab "Blank page" translate as "Страница бланка" and its wrong.

## Steps to Reproduce

1. Setup russian language in brave browser
2. Open brave://settings/newTab
3. Click to dropdown for available new tab options
4. See "Страница бланка" in third line

## Actual result:

"Страница бланка" (translated back as "form page") in dropdown

## Expected result:

"Пустая страница" (translated back as "blank page"/"empty page") in dropdown

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 1.21.74 Chromium: 89.0.4389.72 (Официальная сборка) (64 бит)
-- | --
Версия | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
ОС | Linux
JavaScript | V8 8.9.255.20
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36
Командная строка | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,SafetyTip,LegacyTLSEnforced,DnsOverHttps --disable-features=AutofillEnableAccountWalletStorage,AutofillServerCommunication,DirectSockets,IdleDetection,TextFragmentAnchor,WebOTP,NotificationTriggers,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,TabHoverCards,NetworkTimeServiceQuerying,LangClientHintHeader,PrivacySettingsRedesign,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection,SafeBrowsingEnhancedProtectionMessageInInterstitials --flag-switches-begin --allow-insecure-localhost --flag-switches-end
Путь к исполняемому файлу | /opt/brave.com/brave/brave
Путь к профилю | /home/stas/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

it can be reproduced in any release at now, because:
https://github.com/brave/brave-core/blob/master/app/resources/brave_generated_resources_ru.xtb#L50

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 

Does not resolve

- Is the issue reproducible on the latest version of Chrome? 

Does not reproduce in chrome

P.S. I don't understand, how this [resources](https://github.com/brave/brave-core/blob/master/app/resources/brave_generated_resources_ru.xtb#L50)  generated, so can't create pull request. Sorry.

**Comment by rebron** [comment]
cc: @mkarolin

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.22.66 Chromium: 89.0.4389.90 (Официальная сборка) (64 бит)
-- | --
Версия | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
ОС | Windows 10 OS Version 2004 (Build 19041.867)

```
-  Verified the STR from the description and ensured "Пустая страница" (translated back as "blank page"/"empty page") in dropdown
![image](https://user-images.githubusercontent.com/38657976/111977960-61766080-8b29-11eb-8d67-d0199fee0454.png)
