### ISSUE TITLE
Dev builds not updated

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#14691]
where is a new build of Brave dev build. it looks liek the beta build has been updated a bunch of times over the last week and and it looks like dev build only got updated one and it is not even on the newest chrome 89 build either?

**Comment by rebron** [comment]
Hi @joejoejo This is our build schedule. https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#current-build-schedule

Dev builds should be all good to go. There are times we run into issues and we have to delay publishing.
