### ISSUE TITLE
New provider type and handling for experimental wallet feature flag

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14690]
When the native wallet feature flag is on:
<img width="750" alt="Screen Shot 2021-03-12 at 3 10 40 PM" src="https://user-images.githubusercontent.com/831718/110993476-58c1a580-8345-11eb-9378-eb7db9d54649.png">

When the native wallet feature flag is off:
<img width="699" alt="Screen Shot 2021-03-12 at 3 14 05 PM" src="https://user-images.githubusercontent.com/831718/110993697-9a525080-8345-11eb-9e39-b66c7a93988e.png">

In both cases if MetaMask is installed it will show MetaMask too.

No matter what the flag

 shows, we update the hamburger menu to say Wallet:
<img width="360" alt="Screen Shot 2021-03-12 at 3 46 07 PM" src="https://user-images.githubusercontent.com/831718/110996610-28c8d100-834a-11eb-9b04-4b8ebf575853.png">

# Disable Dapp detection

When MetaMask is not installed, to suggest that a user installs our Crypto Wallets extension when they use a Dapp, we currently run a script on every page to check if it accesses `window.ethereum`. If it does, then we used to show an infobar to ask the user if they want to install our Crypto Wallets extension.

We also use this Dapp detection to prompt the user to load a previously installed lazily loaded extension.

Both of these methods will be disabled when the feature flag mentioned above is on. There will be no Dapp detection.  All sites will have window.ethereum exposed (when it is implemented in the experimental flag, being tracked in a different issue).

# Disable lazy loading

To avoid extra process overhead from the Crypto Wallets extension, we used to lazily load the Crypto Wallets extension on the first load of brave://wallet.

The new native wallet will not have overhead, so all of these extra complications can go away.

We would also show an infobar to suggest lazily loading the Crypto Wallets extension via the Dapp detection mentioned above.  This infobar and detection will be removed. 

In brave://settings/wallet we currently have a checkbox setting for “Load Crypto Wallets on startup”.  If the feature flag is on we’ll instead show “Load deprecated Crypto Wallets extension on startup”. 

# Setting for Ethereum provider for using Dapps

The setting for Ethereum provider for using Dapps (`kBraveWalletWeb3Provider`) will remain in settings whether or not the feature flag is on. Users may still want to select between the old Extension (until they migrate), MetaMask, the new Brave Wallet, or other future wallets options we might add here later.

The new Brave Wallet option will only appear when the feature flag is on.

The new provider types will be: 
`BraveWalletWeb3ProviderTypes { ASK, NONE, CRYPTO_WALLETS, METAMASK, BRAVE_WALLET };`

`BRAVE_WALLET` will be the new default, and ASK will no longer be an option.

# chrome.braveWallet API

We have a `chrome.braveWallet` API that is exposed to the Brave wallet. No changes are expected at this time except for handling the new brave wallet provider type. We’ll eventually deprecate this API.

## Test cases:

With the the native wallet feature disabled (which is also the default for now):
- Fresh profile, loading crypto kitties should still show the infobar to install the extension
- Lazy loading the extension should still work the same, off by default but can be controlled by the lazy load wallet setting.  Test with the lazy load wallet setting on and off.
- MetaMask should be added above None when it is installed
- window.web3 should be available on all sites when the wallet is loaded
- Options for which Dapp provider to use should be listed as per the screenshot in the issue.
- Hamburger menu item should change from Crypto Wallets to Wallet (this one ignores the flag)

With the native wallet feature flag enabled:
- Fresh profile loading crypto kitties should not show an infobar 
- window.web3 should not be available unless a page provides its own
- Options for which Dapp provider to use should be listed as per the screenshot in the issue.
- Selecting the deprecated wallet should work like before.
- Hamburger menu item should change from Crypto Wallets to Wallet

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.23.68 Chromium: 90.0.4430.51 (Official Build) (64-bit)
-- | --
Revision | `32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}`
OS | Windows 10 OS Version 2009 (Build 19042.867)

<details> 
<summary>Verified test plan from <a href=https://github.com/brave/brave-browser/issues/14690#issue-830382149>#14690 (comment)</a></summary>

- Verified irrespective of the flag state menu shows `Wallet`

Flag Enabled | Flag Disabled
-- | --
![image](https://user-images.githubusercontent.com/17010094/114150196-ad8c1800-9913-11eb-8183-3e53df9709f5.png) | ![image](https://user-images.githubusercontent.com/17010094/114150391-e926e200-9913-11eb-9d0e-b64defa665cd.png)

- Verified when flag is enabled Dapp provider selection shows deprecated Crypto Wallet option

Flag enabled | Flag disabled
-- | --
![image](https://user-images.githubusercontent.com/17010094/114151051-a285b780-9914-11eb-968f-2c82f61571d3.png) | ![image](https://user-images.githubusercontent.com/17010094/114151168-c1844980-9914-11eb-84ce-fd1e407bfb3f.png)

Flag enabled with MetaMask | Flag disabled with MetaMask
-- | --
![image](https://user-images.githubusercontent.com/17010094/114151828-73bc1100-9915-11eb-813c-33f1de7b82b3.png) | ![image](https://user-images.githubusercontent.com/17010094/114151892-86cee100-9915-11eb-9111-75acc6833589.png)

- Verified when flag is enabled visiting Cryptokitties.co doesn't show inforbar
- Verified when flag is disabled visiting Cryptokitties.co shows infobar
![image](https://user-images.githubusercontent.com/17010094/114163655-59d4fb00-9922-11eb-9541-02d0fef0ac4c.png)

- Verified window.web3 should not be available unless a page provides its own
![image](https://user-images.githubusercontent.com/17010094/114171174-d0c2c180-992b-11eb-9984-f08089b49eda.png)

- Verified window.web3 works with flag disabled and Dapp provider set to Crypto Wallet
![image](https://user-images.githubusercontent.com/17010094/114163227-d915ff00-9921-11eb-94b0-f3de94a1ae6f.png)

</details>

----------

Verification passed on 

Brave | 1.23.68 Chromium: 90.0.4430.51 (Official Build) (64-bit)
-- | --
Revision | `32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}`
OS | Linux

<details> 
<summary>Verified test plan from <a href=https://github.com/brave/brave-browser/issues/14690#issue-830382149>#14690 (comment)</a></summary>

- Verified irrespective of the flag state menu shows `Wallet`

Flag Enabled | Flag Disabled
-- | --
![image](https://user-images.githubusercontent.com/17010094/114172767-036db980-992e-11eb-9a7e-c04fc2ad43a5.png) | ![image](https://user-images.githubusercontent.com/17010094/114172728-f2bd4380-992d-11eb-922c-ce719b68ddf1.png)

- Verified when flag is enabled Dapp provider selection shows deprecated Crypto Wallet option

Flag enabled | Flag disabled
-- | --
![image](https://user-images.githubusercontent.com/17010094/114173001-58a9cb00-992e-11eb-86fd-0b568d86f6fa.png) | ![image](https://user-images.githubusercontent.com/17010094/114173167-9e669380-992e-11eb-93a9-5da098f7d43c.png)

Flag enabled with MetaMask | Flag disabled with MetaMask
-- | --
![image](https://user-images.githubusercontent.com/17010094/114173442-1634be00-992f-11eb-854f-d098ed820de9.png) | ![image](https://user-images.githubusercontent.com/17010094/114173385-00bf9400-992f-11eb-8644-1e3c28207034.png)

- Verified when flag is enabled visiting Cryptokitties.co doesn't show inforbar
- Verified when flag is disabled visiting Cryptokitties.co shows infobar
![image](https://user-images.githubusercontent.com/17010094/114174271-4c267200-9930-11eb-8e84-8a918efc4a3d.png)

- Verified window.web3 should not be available unless a page provides its own
![image](https://user-images.githubusercontent.com/17010094/114177187-04094e80-9934-11eb-8982-ea4ab886c5b2.png)

- Verified window.web3 works with flag disabled and Dapp provider set to Crypto Wallet
![image](https://user-images.githubusercontent.com/17010094/114177544-72e6a780-9934-11eb-8cd5-6c2016967b6a.png)

</details>

----------
Verification passed on 

Brave | 1.23.68 Chromium: 90.0.4430.51 (Official Build) (x86_64)
-- | --
Revision | `32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}`
OS | macOS Version 10.15.7 (Build 19H114)

<details> 
<summary>Verified test plan from <a href=https://github.com/brave/brave-browser/issues/14690#issue-830382149>#14690 (comment)</a></summary>

- Verified irrespective of the flag state menu shows `Wallet`

Flag Enabled | Flag Disabled
-- | --
<img width="1440" alt="Screenshot 2021-04-09 at 13 32 56" src="https://user-images.githubusercontent.com/17010094/114184301-97468200-993c-11eb-97c7-e860cda686f6.png"> | <img width="1440" alt="Screenshot 2021-04-09 at 13 31 57" src="https://user-images.githubusercontent.com/17010094/114184261-8990fc80-993c-11eb-9eb3-e2a8b2a56d28.png">

- Verified when flag is enabled Dapp provider selection shows deprecated Crypto Wallet option

Flag enabled | Flag disabled
-- | --
<img width="1440" alt="Screenshot 2021-04-09 at 13 33 54" src="https://user-images.githubusercontent.com/17010094/114184356-a4fc0780-993c-11eb-984a-06ccc497bbcd.png"> | <img width="1440" alt="Screenshot 2021-04-09 at 13 35 50" src="https://user-images.githubusercontent.com/17010094/114184434-b8a76e00-993c-11eb-92a5-ff6392e6729e.png">

Flag enabled with MetaMask | Flag disabled with MetaMask
-- | --
<img width="1440" alt="Screenshot 2021-04-09 at 13 47 24" src="https://user-images.githubusercontent.com/17010094/114184847-ed1b2a00-993c-11eb-9a31-6324671c8b78.png"> | <img width="1440" alt="Screenshot 2021-04-09 at 13 46 27" src="https://user-images.githubusercontent.com/17010094/114184744-d2e14c00-993c-11eb-871d-30d5ed799c6a.png">

- Verified when flag is enabled visiting Cryptokitties.co doesn't show inforbar
- Verified when flag is disabled visiting Cryptokitties.co shows infobar
<img width="1440" alt="Screenshot 2021-04-09 at 13 54 21" src="https://user-images.githubusercontent.com/17010094/114184901-ff956380-993c-11eb-8ad2-44206e875d7f.png">

- Verified window.web3 should not be available unless a page provides its own
<img width="1440" alt="Screenshot 2021-04-09 at 13 56 58" src="https://user-images.githubusercontent.com/17010094/114185003-1dfb5f00-993d-11eb-844f-26c53da78141.png">

- Verified window.web3 works with flag disabled and Dapp provider set to Crypto Wallet
<img width="1440" alt="Screenshot 2021-04-09 at 13 55 29" src="https://user-images.githubusercontent.com/17010094/114184953-0d4ae900-993d-11eb-8c88-7d3636fcc190.png">

</details>

-----------

Verification passed on the following devices running 1.23.68 x64 build
- Verified able to enable flag via `brave://flags`
- Verified no browser crash when visiting cryptokitties.co when flag is enabled

OnePlus 6T (Android 10 ) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/114193151-25733600-9946-11eb-8d90-2775f200c2c8.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/114195074-0e354800-9948-11eb-8a78-eb45d0c64f19.png>
