### ISSUE TITLE
ProcessSyncChanges failed on ChangeType ACTION_DELETE

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#14702]
## Description 

 
In brave://sync-internals I see this error:

Search Engines | 55 | 55 | Error: ProcessSyncChanges@../../components/search_engines/template_url_service.cc:1043, datatype error was encountered: ProcessSyncChanges failed on ChangeType ACTION_DELETE | Failed
-- | -- | -- | -- | --

It's started appearing a few days ago, maybe after brave was upgraded to a new release.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Brave version (info found on brave://version)

1.21.76 Chromium: 89.0.4389.86 (Build ufficiale) (a 64 bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@tortino Are you still seeing this error with our latest 1.25.68 version?

**Comment by jsecretan** [comment]
Hi @tortino just wanted to ping again to see if you are still seeing this

**Comment by jsecretan** [comment]
Ok great, thanks
