### ISSUE TITLE
Shortcuts should be easy to remember, simpler & numbered

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#14704]
Have you searched for similar issues? Yes.
 
## Description 
I'm sorry to say but 'Ctrl+x' - 'Ctrl+Shift+x' - 'Alt+Shift+x' is too much for me to remember in terms of shortcuts.

I often spend a good 5 seconds opening the Customize and control Brave menu - the thing with the three lines just skimming from top to bottom looking for and scrolling to Extensions and Settings as well as other things and I've been using Brave for quite sometime now. Truth be told I only seem to remember the shortcut for Print and I never use it; I personally don't think the current shortcut keys are helpful even though they're supposed to be shortcuts.

I propose that in addition to the above shortcut keys that the team also implement 'Ctrl+[Number]' and also allow it to be changed in the menu itself with users only being able to change the number. I was originally thinking that numbers 1 to 9 only be available once, then I figured perhaps it may be good if double digits can also be entered, so 'Ctrl+1+1' and that shortcut is presented once you let go of the keys on the keyboard, so you would hold Ctrl and press 1 twice and letting go would direct you. If you don't like that at all, could you still please consider the numbers 1 to 9. I not asking that you replace the configuration for those places but have both options and sort of present like a highlighted figure that those places can be pressed on the far right '[Ctrl+1-9]' and this would appear discreetly so as not to lengthen or enlarge the text in the Menu.

In addition if brave://settings/extensions & brave://extensions/pages are still to be segregated it would be ideal to find those places more quicker with closer shortcuts if you know what I mean. Right now there isn't a shortcut for either but pressing 'Ctrl+8' & 'Ctrl+9' per user choice of course would be better.
 
Furthermore, I honestly think a numbered shortcut way would actually be a shortcut and would give the the team and us as users the flexibility to configure these shortcuts to our most preferred places now and in the future i.e 'Ctrl+1-5' would be an easier reach for our fingers to frequented places and other digits can be modified to head to other Brave features where shortcuts aren't currently available or aren't even planned such as together.brave.com & the new brave://wallet

I don't know how much room Brave has to modify the menu on the top right essentially to take on my approach of implementing a configurable box within the menu itself but for the time being, to implement something more rapidly rather than looking into this later-on, I'd appreciate it if just under Settings or above it, if there was a 'Shortcuts' button, so above 'Report a Broken Site' and it would open page identical to brave://adblock/ except brave://shortcuts and have a list of pre-configured shortcuts

[Ctrl+0] brave://bookmarks
[Ctrl+1] Private Window
[Ctrl+2] Private with Tor 
[Ctrl+3] Downloads 
[Ctrl+4] Sync
[Ctrl+5] Dark / Light mode
[Ctrl+6] Speedreader
[Ctrl+7] Pocket/Instapaper/Evernote
[Ctrl+8] talk.brave.com
[Ctrl+9] brave://history
[Ctrl+1+1] brave://rewards
[Ctrl+2+2] brave://wallet
[Ctrl+3+3] brave://extensions/pages
[Ctrl+4+4] brave://settings/extensions

Thanks

**Comment by rebron** [comment]
@NumDeP This may be more appropriate as an extension.

**Comment by NumDeP** [comment]
No way man! The idea is to reduce memory consumption and effort. Having a separate extension and bloating up the extension bar further for such a simple idea i.e easy to grasp, easy to change, easy to implement; it shouldn't be too difficult.

I honestly don't know how on earth people remember all the different kinds of shortcuts that already exists. For brave to differentiate itself from Google's Chrome it has to do something like this. Okay may be not exactly like the way I describe above (though I can't think of a more feasible shortcut) but certainly something better than adopting what Google implemented and the little extra which Brave has implemented and may continue to add along the way. Please remove the extension label and slap a P3 on it

I don't want this to be another extension request and I don't want to come across as rude but do you reckon we can hold a vote on it in community.brave? If it comes near to a figure which you stipulate, slap a P3 and discuss it with the team further. If it doesn't come no where near, forget about it altogether.

**Comment by fallaciousreasoning** [comment]
Hey @NumDeP it's not exactly what you asked for but we're working on making it possible to configure Keyboard Shortcuts at the moment. Do you think that would fix your issue?

**Comment by NumDeP** [comment]
Hi @fallaciousreasoning to be quite frank with you, other than using brave's private page on and off, I haven't really been using the typical Brave window because the user experience I feel had and has been neglected for quite sometime.

I'm not sure what you want me to say because I wasn't having an issue per say but wanted to suggest, in my opinion, a better way for regular users of Brave to effectively use Brave more quickly.

**Comment by bsclifton** [comment]
Keyboard shortcuts are customizable now (thanks @fallaciousreasoning)

You can visit brave://settings/system/shortcuts

I'll close issue and we can create another one if there's something specific. Overall feedback in this issue has been acknowledged by @rebron above 👍
