### ISSUE TITLE
Unblocked CNAME on https://firstlutherancc.org/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#14700]
## Description 
Opening `https://firstlutherancc.org/` shows no blocked items. (plausible cname)

## Steps to Reproduce

   1. Visiting `https://firstlutherancc.org/`  and `https://markosaric.com/` showing no blocked items
   2. Expecting blocked items in Dev-tools or shields
   3. 

## Actual result:

![firstluth-shields](https://user-images.githubusercontent.com/1659004/111053998-b7199000-84cd-11eb-8821-0cde6863f768.png)

## Expected result:
Expect plausible CNAME to be blocked

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
`Version 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@antonok-edm 

![firstlutherancc-log](https://user-images.githubusercontent.com/1659004/111053876-7705dd80-84cc-11eb-90ee-47215c8396e8.png)

From Firefox/uBO:
Non blocked item via devtools:
![ff-cname](https://user-images.githubusercontent.com/1659004/111053923-f7c4d980-84cc-11eb-91f8-435496f58bb4.png)

I have added some filters into Easyprivacy, which may affect this
https://github.com/easylist/easylist/commit/136240efa313e48a5182b21be782ca4dcd66188e

and today, https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_specific_cname.txt#L8

**Comment by ryanbr** [comment]
While we have `||plausible.io^$third-party` in Easyprivacy, I also attempted to add `||custom.plausible.io^` into brave://adblock didn't block the cname.

**Comment by antonok-edm** [comment]
Should be fixed by https://github.com/brave/brave-browser/issues/14755
