### ISSUE TITLE
Add ability to buy in Crypto Wallets using Wyre

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14701]
Using the Buy button in Crypto Wallets should allow you to use Wyre to buy crypto currency.
@Douglashdaniel could you please add the information for how to test in this issue?

**Comment by bbondy** [comment]
Fixed via https://github.com/brave/ethereum-remote-client/pull/228

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)
-- | --
Revision | `62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}`
OS | Linux
Component | `1.0.26 Dev`

- Verified able to connect to Wyre Test net and purchase ETH 
- Verified once transaction was successful ETH balance updated on Kovan testnet

Connect to Wyre | Successful Transaction | Deposit on Kovan Testnet
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/112107660-24e94a00-8ba7-11eb-98db-93455789fa7d.png) | ![image](https://user-images.githubusercontent.com/17010094/112107969-8b6e6800-8ba7-11eb-8c74-59ec23ca78c7.png) | ![image](https://user-images.githubusercontent.com/17010094/112108250-d8ead500-8ba7-11eb-8578-0e589f512cac.png)

----------

Verification passed on

Brave | 1.22.62 Chromium: 89.0.4389.90 (Official Build) beta (64-bit)
-- | --
Revision | `62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}`
OS | Windows 10 OS Version 2009 (Build 19042.867)
Component | `1.0.26 Dev`

- Verified able to connect to Wyre Test net and purchase ETH 
- Verified once transaction was successful ETH balance updated on Kovan testnet

Connect to Wyre | Successful Transaction | Deposit on Kovan Testnet
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/112107048-5f061c00-8ba6-11eb-993c-0d7fd507572f.png) | ![image](https://user-images.githubusercontent.com/17010094/112106997-5281c380-8ba6-11eb-8c7f-93a549361664.png) | ![image](https://user-images.githubusercontent.com/17010094/112107182-878e1600-8ba6-11eb-9b18-95fd6ac3f0b0.png)

---------
Verification passed on 


Brave | 1.24.8 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | `62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.26 Dev`

- Verified able to connect to Wyre Test net and purchase ETH 
- Verified once transaction was successful ETH balance updated on Kovan testnet

Connect to Wyre | Successful Transaction | Deposit on Kovan Testnet
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/112106108-231e8700-8ba5-11eb-9dff-8c058f447a55.png) | ![image](https://user-images.githubusercontent.com/17010094/112106048-0f732080-8ba5-11eb-9ca4-8088c3be35c2.png) | ![image](https://user-images.githubusercontent.com/17010094/112106077-18fc8880-8ba5-11eb-923e-0c51cf6a9fff.png)
