### ISSUE TITLE
Add Trezor keyring support to new wallet 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14706]
https://wiki.trezor.io/Developers_guide
https://wiki.trezor.io/Developers_guide:Running_Trezor_Connect_on_localhost

**Comment by spylogsster** [comment]
1) We will create a new webui chrome://trezor-bridge
- This will never be shown to the user(or anywhere in the UI) and will be used only as a sandbox to load the trezor library.
- The page which contains the library will be loaded form the browser resources.
- The library will create an iframe and load another page(from our resources as well) that will have our extra script to override window.fetch.
- `trezor-connect` communicates with iframe via postMessage and there is code to add/remove iframe via parent window calls, for this we need to disable ShouldDenyXFrameOptions for this page.
     -  It looks quite safe considering all of this :
           - all content on both pages is loaded from our browser resources
           - it doesn’t load external scripts or content,
           - it is never shown to the user,
           - the page is separated form others and contains only the library itself.
     -  There is only one external request from the page to http://127.0.0.1:21325/, to the Trezor Suite port. I will redefine fetch and send this request from c++ part.
2) Create a C++ controller which will create a webcontents inside itself and load chrome://trezor-bridge webui to communicate with it via api.
3) Keep this TrezorController inside the KeyringController to communicate with Trezor from brave://wallet page and panel.
