### ISSUE TITLE
Add support for wallet_addEthereumChain  (EIP 3085) to new wallet 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14707]
This issue tracks the back-end of EIP 3085 and to connect the UI to real functionality.

See https://eips.ethereum.org/EIPS/eip-3085

EVM compatible chains can be suggested by pages for adding alternate chains such as Binance Smart Chain, L2s such as Polygon, Arbitrum, Optimism, and side chains such as SKALE, xDAI.  Not all of these chains need to have a native currency of ETH, for example Binance Smart Chain has a native symbol of BNB.

Note that we will preload some chains and L2s to avoid phishing attempts from a page wanting to add another network. 

This is the current implementation on MetaMask: https://consensys.net/blog/metamask/connect-users-to-layer-2-networks-with-the-metamask-custom-networks-api/

A page can specify the following fields: 
NetworkName, NetworkURL, ChainID, CurrencySymbol

A list of known EVM networks can be found here: https://chainid.network/ we’ll make a subset of this list as our officially supported list.

We’ll give a UI warning if a page is requesting something to be added that’s not in that list.

**Comment by spylogsster** [comment]
Some issues to be done in next PRs before closing this one
https://github.com/brave/brave-browser/issues/17640
https://github.com/brave/brave-browser/issues/17639
https://github.com/brave/brave-browser/issues/17637
