### ISSUE TITLE
Brave leaves a blue rectangle on my screen that won't go away even after quitting Brave

### ISSUE THREAD

**Issue by ijt** [brave/brave-browser#14710]
## Description 

I must have entered some magic key combo in Brave because now every time I open it, it puts a blue rectangle on my screen that won't go away even after I exit Brave. Couldn't this be something to opt into explicitly for whoever needs this?

## Steps to Reproduce

   1. Open Brave
   2. Accidentally enter the secret key combo or something

## Actual result:

<img width="581" alt="Screen Shot 2021-03-14 at 7 42 52 PM" src="https://user-images.githubusercontent.com/15530/111093291-26a77380-84fe-11eb-9f08-4c33b68436b0.png">

## Expected result:

A normal browsing experience with no blue rectangle haunting me.

## Reproduces how often: 

I have no idea how to reproduce this.

## Brave version (brave://version info)
1.21.76 Chromium: 89.0.4389.86 (Official Build) (x86_64)

0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}

macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:
I'd have to stumble onto that again.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No.

- Does the issue resolve itself when disabling Brave Rewards? 
I'm not sure how to do that, and I don't think it's related. Seems more like some sort of accessibility thing.

- Is the issue reproducible on the latest version of Chrome? 
I don't know how to reproduce it.

## Miscellaneous Information:
N/A.

**Comment by ijt** [comment]
This is so bad that I will probably not be using Brave until it is fixed or I find a workaround for it.

**Comment by ijt** [comment]
Update: the problem went away after restarting the computer a second time. Anyway, I'd still like to have a default of no blue rectangles ever.

**Comment by bsclifton** [comment]
@ijt this is definitely not a known "feature" of any kind? Do you have Chrome or any other Chromium based browser installed? If they're doing this too, I can help create a Chromium bug report

**Comment by ijt** [comment]
I have Chrome, and I went back to that briefly while this was happening.
However, I haven't yet seen it on Chrome. If I do I'd be happy to follow up
with a report.

**Comment by bsclifton** [comment]
@ijt OK thanks 👍 Did you have to do anything for this to happen? Or did you simply use Brave and exit (and it did this?)

Your original post mentions secret key combo? Just want to make sure I'm not missing something. Do you have any global shortcut apps or something installed?

**Comment by ijt** [comment]
I think I pressed some keys. I don't think I simply used Brave and exited.

I don't think it's a global shortcut app because the rectangle came back
when I opened Brave up again, though now it has gone away after rebooting
my system.

**Comment by rebron** [comment]
@ijt I'm going to close this one off. Looks like this got corrected after a reboot per your last comment and I believe this is a macOS issue.
