### ISSUE TITLE
Yubi Keys do not work  on Ubuntu 20

### ISSUE THREAD

**Issue by summitt** [brave/brave-browser#14712]
## Description 
Yubi Keys do not work on  Ubuntu 20.04.2 LTS. I've tried the older yubi key and the new NFC enabled yubi keys. The browser has the drop down that asks me to insert the security key and will disappear after i press the button but does not seem to transfer the authentication. 

## Steps to Reproduce

   1. Go to any site that supports yubi keys( i tried at least 4 with the same result)
   2. Enter the USB yubi key
   3. press the button
   4. notice that nothing happens

## Actual result:

The drop down disappears and i am not authenticated

## Expected result:
I get authenticated

## Reproduces how often: 

every time

## Brave version (brave://version info)

Version 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? not tried
- Can you reproduce this issue with the nightly channel? not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no, works perfectly on chrome Version 89.0.4389.72 (Official Build) (64-bit)

## Miscellaneous Information:

none

**Comment by bsclifton** [comment]
Hi @summitt - did you install via the Ubuntu Snap? If so that is a known issue which we have tracked with https://github.com/brave/brave-browser/issues/6782

**Comment by bkero** [comment]
As a data point, I just tested using my Yubikey 5 on my Ubuntu 20.10 desktop. I tried with Firefox 85.0.1 and the latest Brave stable with fresh profiles. I tested by loading https://yubico.com/genuine and authorizing that site to access my key. I also logged in to Github to type this message by using it as my 2nd factor.

Using the `brave` snap however, caused the same symptoms that the reporter experienced: The U2F token is detected and challenged (with the popup). When the token is touched, the popup goes away but a failure status is shown.

**Comment by wknapik** [comment]
@bkero the snap issue should be fixed by running `sudo snap connect brave:u2f-devices` (won't be needed in the future, but for now it is).

**Comment by wknapik** [comment]
@bkero confirmed that `sudo snap connect brave:u2f-devices` fixes the issue with the snap package.

So we have confirmation that Brave works on Ubuntu 20 with both distro packages and snaps.

**Comment by summitt** [comment]
yes i'm using the snap package. Thanks for the info. I'll try the suggestions above

**Comment by wknapik** [comment]
Hey @summitt. Is this working for you now?

**Comment by wknapik** [comment]
Starting with the next Brave snap update, the `u2f-devices` plug will autoconnect and users will no longer need to manually execute `sudo snap connect brave:u2f-devices`.

**Comment by summitt** [comment]
@wknapik Yes, installing via apt-get fixed the issue.

**Comment by wknapik** [comment]
@summitt you should be able to use the snap package, if you prefer. Currently, you'd have to run `sudo snap connect brave:u2f-devices` in a terminal every time you start the snap, to make your Yubikey work, but after the next Brave snap release that should no longer be needed.

Should we close this issue?

**Comment by wknapik** [comment]
After the new snap package release a few minutes ago, the `u2f-devices` plug is autoconnected, as expected.

This change will kick in automatically on all systems, as `snap refresh` is run automatically (this happens multiple times a day by default, can be forced manually by calling `sudo snap refresh`, or just `sudo snap refresh brave`).

This confirms that it's no longer necessary to run `sudo snap connect brave:u2f-devices` to make u2f devices work with the Brave snap.

However, the device needs to be (re)connected after the Brave snap is started. This also affects the Chromium snap, but not the Firefox snap. Will track this in #6782.

**Comment by bsclifton** [comment]
Nice work, @wknapik! 😄
