### ISSUE TITLE
brave crashes when enabling/initializing rewards

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#14720]
## Description 

Brave crashes when enabling rewards or running through the rewards onboarding. This doesn't happen in `1.22.60 CR: 89.0.4389.86`.

## Steps to reproduce 

**`Test Case #1`**

   1. launch `1.23.36 CR: 89.0.4389.86`
   2. tap on the rewards panel and click on `Start using Brave Rewards` (wait ~5s and Brave will crash)

**`Test Case #2`**

   1. launch `1.23.36 CR: 89.0.4389.86`
   2. tap on the rewards panel and click on `X` to dismiss the onboarding panel
   3. tap on `Settings` via the rewards panel
   4. enable ads (wait ~5s and Brave will crash)

## Actual result 

Brave crashes when enabling/initializing rewards for the first time.

## Expected result

Brave shouldn't be crashing when enabling/initializing rewards for the first time.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `No` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+ (Phone)`
   - Android version: `Android 11`
   
## Brave version

* `1.23.36 CR: 89.0.4389.86` - **Reproduced**
* `1.23.15 CR: 89.0.4389.72` - **Reproduced**

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @tmancey @rebron @SergeyZhukovsky @bsclifton @zenparsing @brave/legacy_qa

**Comment by srirambv** [comment]
Reproduced the crash on 1.23.9 as well

**Comment by bsclifton** [comment]
cc: @deeppandya

**Comment by deeppandya** [comment]
@kjozwiak @bsclifton @srirambv  i noticed it couple of days back on nightly and it's only on nightly as it was an issue in custom ad notification. it's fixed here https://github.com/brave/brave-core/pull/8235 so next nightly build will fix it.

**Comment by bsclifton** [comment]
@deeppandya awesome, thanks! 😄 I was just thinking https://github.com/brave/brave-core/pull/8220 might help also (hard to tell without seeing the crash)

**Comment by rebron** [comment]
Closed.

**Comment by kjozwiak** [comment]
Edited https://github.com/brave/brave-core/pull/8235 and added this issue to the resolve list.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.63 x64 beta build
- Verified no crash when enabling rewards via onboarding
- Verified no crash when enabling rewards ads via settings  
----------
Verification passed on Samsung Tab A  with Android 10 running 1.23.63 x64 beta build
- Verified no crash when enabling rewards via onboarding
- Verified no crash when enabling rewards ads via settings
