### ISSUE TITLE
NTP Rewards widget should not enable AC for users that have turned AC off

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#14735]
## Description 

Currently, the NTP rewards widget will show an onboarding CTA if the user has not enabled ads, or if the user has disabled Ads. When the user clicks the button, both Ads and AC are enabled. This can lead to confusion for users that have explicitly disabled AC in the past.

## Steps to Reproduce

   1. Start the browser with a clean profile
   2. Navigate to `brave://rewards` and click "Start using Rewards".
   3. Disable AC.
   4. Disable Ads
   5. Open a new tab
   6. On the NTP, click the "Start using Rewards" button
   7. Navigate to `brave://rewards`

## Actual result:

AC is enabled.

## Expected result:

AC is not enabled.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.24.46 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
Revision	e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS	macOS Version 10.15.7 (Build 19H524)
```

Verified test plan from https://github.com/brave/brave-core/pull/8273#issue-594220103

<details>
<summary>Scenario 1 - Existing user, no Uphold</summary>

Installed 1.24.46 using staging env.
Enabled Rewards from panel.
Navigated to brave://rewards and disabled both Ads and AC.
Opened NTP.
Clicked "Start Using Rewards" from Rewards widget.
Navigated to brave://rewards.
Confirmed only Ads enabled, AC not enabled.
Closed/relaunched browser.
Confirmed still only Ads enabled, AC not enabled.

</details>

<details>
<summary>Scenario 2 - Existing user with Uphold</summary>

Installed 1.24.46 using staging env.
Enabled Rewards from NTP.
Connected KYC'd Uphold wallet.
Disable both Ads and AC.
Opened NTP.
Clicked "Start Using Rewards" from Rewards widget.
Navigated to brave://rewards.
Confirmed only Ads enabled, AC not enabled.
Closed/relaunched browser.
Confirmed still only Ads enabled, AC not enabled.

</details>

<details>
<summary>Scenario 3 - Upgrade profile with non-zero balance, no Uphold</summary>

Install 1.23.x using staging env.
Enable Rewards from panel.
Claim UGP grant.
Navigate to brave://rewards and disable both Ads and AC.
Confirm NTP offers to "Start using Rewards".
Close 1.23.x.
"Upgrade" to 1.24.x (renamed profile folder, launch with 1.24.x).
Open NTP, select "Start using Rewards" from widget.
Navigate to brave://rewards.
Confirm only Ads enabled, not AC.
Closed/relaunched browser.
Confirmed still only Ads enabled, AC not enabled.

</details>

<details>
<summary>Scenario 4 - Upgrade profile with non-zero balance with Uphold</summary>

Install 1.23.x using staging env.
Enable Rewards from panel.
Connect KYC'd Uphold wallet.
Navigate to brave://rewards and disable both Ads and AC.
Confirm NTP offers to "Start using Rewards".
Close 1.23.x.
"Upgrade" to 1.24.x (renamed profile folder, launch with 1.24.x).
Open NTP, select "Start using Rewards" from widget.
Navigate to brave://rewards.
Confirm only Ads enabled, not AC.
Closed/relaunched browser.
Confirmed still only Ads enabled, AC not enabled.

</details>

<details>
<summary>Scenario 5 - Upgrade profile with zero balance, no Uphold</summary>

Install 1.23.x using staging env.
Enable Rewards from panel.
Do not claim UGP grant.
Navigate to brave://rewards and disable both Ads and AC.
Confirm NTP offers to "Start using Rewards".
Close 1.23.x.
"Upgrade" to 1.24.x (renamed profile folder, launch with 1.24.x).
Open NTP, select "Start using Rewards" from widget.
Navigate to brave://rewards.
Confirm both Ads and AC enabled as per https://github.com/brave/brave-core/pull/8273#issue-594220103.
Closed/relaunched browser.
Confirmed both Ads and AC enabled.

</details>

<details>
<summary>Scenario 6 - Upgrade profile with zero balance with Uphold</summary>

Install 1.23.x using staging env.
Enable Rewards from panel.
Connect KYC'd Uphold wallet that has zero BAT in Brave Browser card.
Navigate to brave://rewards and disable both Ads and AC.
Confirm NTP offers to "Start using Rewards".
Close 1.23.x.
"Upgrade" to 1.24.x (renamed profile folder, launch with 1.24.x).
Open NTP, select "Start using Rewards" from widget.
Navigate to brave://rewards.
Confirm both Ads and AC enabled as per https://github.com/brave/brave-core/pull/8273#issue-594220103.
Closed/relaunched browser.
Confirmed both Ads and AC enabled.

</details>
