### ISSUE TITLE
Display messed up since upgrade to latest version

### ISSUE THREAD

**Issue by fewerjunk** [brave/brave-browser#14734]
## Steps to Reproduce

   1.  blenderartists.org
 
(Just one example)

## Actual result:

![47A210F5-1214-4A34-BF6C-D197D6E27CEE](https://user-images.githubusercontent.com/70761456/111172443-0eb60b00-8563-11eb-9afb-a4cc5b10d7ce.png)

## Expected result:

Not that.
## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 1.21.76 Chromium: 89.0.4389.86 (Official Build) (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)
JavaScript | V8 8.9.255.20
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.86 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried. 
- Can you reproduce this issue with the nightly channel?  Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Haven't tried.
- Does the issue resolve itself when disabling Brave Rewards? Haven't tried.
- Is the issue reproducible on the latest version of Chrome? No idea.

## Miscellaneous Information:

![image](https://user-images.githubusercontent.com/70761456/111173484-ec70bd00-8563-11eb-9867-691210ba6283.png)

**Comment by rebron** [comment]
@fewerjunk Does disabling Hardware acceleration fix this? brave://settings/system

**Comment by fewerjunk** [comment]
> @fewerjunk Does disabling Hardware acceleration fix this? brave://settings/system

Yes, it does.

**Comment by bsclifton** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/3471
