### ISSUE TITLE
If client database says promotion is OVER but server says it is not, then set the promotion to ACTIVE 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#14741]
## Description 

Implement a fix such that if the client DB says that a promotion is `OVER`, but the server says it not, then set the promotion back to `ACTIVE`.

This will improve resilience and clear up some cases users are experiencing. 

cc: @evq @zenparsing

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8268 with `nightly` build 

Brave | 1.24.35 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)


Steps:
1. Started the browser with a clean profile pointed to staging: `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile_interval=5,persist-logs=true`
2. Clicked the Rewards icon to initialize rewards and download a UGP promotion (but did *not* yet claim it).
3. Closed the browser.
4. Opened the rewards database in `DB Browser for SQLite` and viewed the contents of the `promotions` table. Found the promotion record corresponding to the UGP and set the status field to `5`; clicked `Write changes` then `Close database`.

| publisher_info_db, claim status `0` | publisher_info_db, claim status `5` |
|----------------------------|-----------------------------|
<img width="1789" alt="Screen Shot 2021-03-30 at 1 54 30 PM" src="https://user-images.githubusercontent.com/387249/113056297-77ef6e00-9160-11eb-9906-3bfadf976427.png"> | <img width="1789" alt="Screen Shot 2021-03-30 at 2 04 06 PM" src="https://user-images.githubusercontent.com/387249/113056612-d9174180-9160-11eb-82a5-e0399e70129a.png">

I also removed `"promotion_last_fetch_stamp":"1617137167",` from `Preferences` in `Default` so the server would re-issue the promotional grant.

5. Started the browser.
6. Navigated to `brave://rewards`.
7. Verifed that the UGP promotion can be claimed.

| UGP grant available | UGP grant claimed | `brave://rewards` |
|---------------------|--------------------|-------------------|
<img width="1446" alt="Screen Shot 2021-03-30 at 2 15 27 PM" src="https://user-images.githubusercontent.com/387249/113057948-88a0e380-9162-11eb-8cae-74adcca9b89d.png"> | <img width="1374" alt="Screen Shot 2021-03-30 at 2 15 56 PM" src="https://user-images.githubusercontent.com/387249/113057951-89397a00-9162-11eb-972f-c1796a932fac.png"> | <img width="1446" alt="Screen Shot 2021-03-30 at 2 16 07 PM" src="https://user-images.githubusercontent.com/387249/113057952-89397a00-9162-11eb-9614-53ef146ae837.png">
