### ISSUE TITLE
Fingerprinting 2.0: User Agent - follow up to #12638

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#14740]
We have some reports of the Android device info reappearing in the Android UA, w/ or w/o farbling.

This issue is to i) correct the regression if it can be reproduced, and ii) add / correct the tests so we can catch any future possible regressions faster in the future

![image](https://user-images.githubusercontent.com/76526/111190181-d6bfbf80-8584-11eb-8529-7eaf6eaa575d.png)
(see "pixel 4a (5G)" in the UA below

**Comment by srirambv** [comment]
+1 from @ristein via #15103

**Comment by srirambv** [comment]
+1 from @Brave-Matt via #15322.

@pes10k @pilgrim-brave issue is missing milestone. Since its already landed on nightly need to decide which milestone this will go in.

cc: @rebron @bbondy

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.23.73 x64 build
- Verified steps from issue description

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/115753376-0dae9f80-a393-11eb-9ceb-3e4408e811ee.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/115753402-130bea00-a393-11eb-9863-b1b4e7176fc3.png>
