### ISSUE TITLE
[Android] Visiting some websites offers to "Show simplified view" for page, even when the option is disabled

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#14749]
## Description 
For certain pages and/or under certain conditions, users are asked if they want to view a "Simplified view" for the page, even if that option is disabled in `Settings --> Accessibility`. While the conditions required make it a rare occurrence, it is worth mentioning, given that if the option is not selected/enabled, you should not be offered the option at all.

## Steps to reproduce 

1. Make sure Settings > Accessibility > Simplified view for web pages (Offer to show articles in simplified view, when supported) = disabled
2. Make sure menu > Desktop site = disabled
3. Visit https://ibkr.info/node/3290 3
## Actual result 
Offer to `Show simplified page` appears

## Expected result
`Show simplified page` offer should not appear.

## Issue reproduces how often 
Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Brave version
v1.21.76

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

User reports:
https://community.brave.com/t/x-buttons-not-functional-design-and-features-how-to-make-brave-even-more-revolutionary/171930/5

Additional steps to reproduce on a different website (taken from user directly):

> 1. set Settings > Accessibility > Simplified view for webpages = disabled
> 2. close all Private tabs (if you have any)
> 5. open new Private tab
> 6. (this has the same effect as clearing site data for this purpose)
> 8. make sure: menu > Desktop site = disabled
> 10. visit https://en.wikipedia.org/wiki/Auction_theory (it’ll redirect to mobile version)
> 14. Scroll to bottom, tap “Desktop” hyperlink
> 16. In the first paragraph of the article, tap “market failure” hyperlink
> 18. You should see the “Show simplified view” bar when the “market failure” page loads (if not, try going through to a couple more articles). The bar isn’t supposed to be presented to the user since you disabled it in step 1 above. Therefore, it’s a bug. :slight_smile: Now if you tap Back, the bar will appear on previous article also.

**Comment by srirambv** [comment]
Seems to be an upstream issue. I see it happen on Chrome as well 
![image](https://user-images.githubusercontent.com/17010094/111251678-9ce3cd00-8607-11eb-8b2f-5c5c4d95b715.png)

**Comment by anthonypkeane** [comment]
Hi @srirambv can you please recheck this when you get a moment

**Comment by jeromebrenier** [comment]
Hi,
I confirm this problem, with brave 1.38.113 when visiting forum.hardware.fr for example. This is very annoying.

**Comment by stephendonner** [comment]
## Verified `PASSED` using Brave 1.43.74, Chromium 104.0.5112.102

First reproduced the issue with current release, using the steps to reproduce here: https://github.com/brave/brave-browser/issues/14749#issue-832149480.

### Confirmed fix with 1.43.74

`release` | `1.43.74`
----------|----------
![Screenshot_20220818-090051](https://user-images.githubusercontent.com/387249/185442108-e3fe1867-dd1a-4554-ac07-8f3f47016e2e.png) | ![Screenshot_20220818-090022](https://user-images.githubusercontent.com/387249/185442159-c3be37b1-6849-4176-b68b-51d588ea53af.png)
