### ISSUE TITLE
Icons of files and folders NOT showing when downloading files

### ISSUE THREAD

**Issue by antnh6** [brave/brave-browser#1474]
## Description 

When I download a .pdf file, a window shows up to allow me to select where I want to save the file. However none of the icons for any folder or file in this window are visible. 

## Steps to Reproduce

   1. Try downloading a .pdf file to prompt open a window for storage selection

## Actual result:
![brave_icons](https://user-images.githubusercontent.com/12288545/46708919-198c4900-cc0f-11e8-8665-d955ff1d744c.png)

## Reproduces how often: 

Easily reproduced

## Brave version (chrome://version info)

Name | Version
-- | --
Brave | 0.24.0
V8 | 6.9.427.23
rev | f657f15
Muon | 8.1.6
OS Release | 4.10.0-42-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Comment by srirambv** [comment]
This repository is for Brave Browser only. This would not be fixed on the browser-laptop as we are moving from muon to new Brave Browser. You can download the beta version of Brave Browser from https://brave.com/download-beta/.
