### ISSUE TITLE
[Desktop] Customize window on NTP appears transparent in Nightly (v1.23.36)

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#14754]
## Description 

cc @petemill 
Font appears and buttons still function but the window itself is transparent as shown below:
![image](https://user-images.githubusercontent.com/3299098/111242775-10142180-85bd-11eb-9916-8f297f1636df.png)

## Steps to Reproduce

   1. Launch Nightly v1.23.36
   2. Click `Customize` on NTP

## Reproduces how often: 

Always

## Brave version (brave://version info)

```
v1.23.36 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.23.43 Chromium: 89.0.4389.90 (Official Build) beta (x86_64)
Revision	62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS	macOS Version 10.15.7 (Build 19H524)
```

Reproduced the issue using `1.23.42` with both light and dark themes:

Light | Dark
----- | -----
<img width="1121" alt="1 23 42-light" src="https://user-images.githubusercontent.com/28145373/111471702-8caf1900-86ff-11eb-94e1-1dee5661c8a2.png"> | <img width="1035" alt="1 23 42-dark" src="https://user-images.githubusercontent.com/28145373/111471705-8de04600-86ff-11eb-924e-1d6b3e5b8a0a.png">

Verified the STR from the description on `1.23.43` using both light and dark themes:

Light | Dark
----- | -----
<img width="1050" alt="1 23 43-light" src="https://user-images.githubusercontent.com/28145373/111471721-93d62700-86ff-11eb-94e1-43cfc568311d.png"> | <img width="1049" alt="1 23 43-dark" src="https://user-images.githubusercontent.com/28145373/111471733-959fea80-86ff-11eb-8072-0e2baff2b3f3.png">

However, encountered and logged https://github.com/brave/brave-browser/issues/14785 for the "Customize Dashboard" text on the popup not being very visible on dark theme (text should be white as it was in 1.22.x, instead it's dark on both dark/light themes).
