### ISSUE TITLE
Incognito in upgrade message in Polish locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14750]
## Steps to Reproduce

   1. Run Brave in Polish locale
   1. Open `brave://settings/help`
   1. Upgrade Brave

## Actual result:

`Okna incognito`
![image](https://user-images.githubusercontent.com/34715963/111221825-4a8cb700-85db-11eb-877f-ec2b06b1646f.png)
![image](https://user-images.githubusercontent.com/34715963/110854944-f8375780-82b5-11eb-90a8-41c71ca97f86.png)

## Expected result:
`Prywatne okna`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @mkarolin

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.22.66 Chromium: 89.0.4389.90 (Official Build) (64-bit)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | Windows 10 OS Version 2004 (Build 19041.867)

```
- Verified the description from the issue, the issue isn't fixed hence logged a follow-up issue https://github.com/brave/brave-browser/issues/14863
