### ISSUE TITLE
Specify resolver source breaks CNAME adblocking

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#14755]
Caused by https://github.com/brave/brave-core/pull/7731 for fixing DoH leak
And the resolver only checks local cache for CNAME request and we will only get `DNS_CACHE_MISS` error for empty cache on Linux reported by @antonok-edm but it did resolved for me on macos after clearing dns cache

**Comment by darkdh** [comment]
after 
```
@@ -84,7 +86,7 @@ void ShouldBlockAdOnTaskRunner(std::shared_ptr<BraveRequestInfo> ctx,
     const GURL canonical_url = ctx->request_url.ReplaceComponents(replacements);
     g_brave_browser_process->ad_block_service()->ShouldStartRequest(
-        ctx->request_url, ctx->resource_type, source_host, &did_match_rule,
+        canonical_url, ctx->resource_type, source_host, &did_match_rule,
         &did_match_exception, &did_match_important, &ctx->mock_data_url);
   }
```
is landed and uplifted to release.
We should test on different platforms to figure out what still doesn't work
and disable CNAME adblocking when DoH is enabled on those platforms

**Comment by LaurenWags** [comment]
labelling as `QA/Blocked` until this is uplifted

**Comment by kjozwiak** [comment]
Uplifted via https://github.com/brave/brave-core/pull/8287#pullrequestreview-616096599 & https://github.com/brave/brave-core/pull/8288#pullrequestreview-616096694.

**Comment by stephendonner** [comment]
Verification **`PASSED`** on macOS Big Sur using the following build:

```
Brave	1.22.65 Chromium: 89.0.4389.90 (Official Build) (x86_64)
Revision	62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS	macOS Version 11.2.3 (Build 20D91)
```
### **`No DoH leak`**

**`Prerequisite`**: Followed https://wiki.wireshark.org/TLS and set up environment

Using the STR mentioned via https://github.com/brave/brave-core/pull/8279#issue-595061704, ensured that there weren't any `DNS` queries leaked when visiting `https://tools.ietf.org`:

<img width="1679" alt="Screen Shot 2021-03-19 at 8 32 40 AM" src="https://user-images.githubusercontent.com/387249/111804953-cf9ef700-888d-11eb-8e70-88a7193d50d6.png">

### **`CNAME adblock`**

**`DoH disabled`**

| **`Disabled`**                                               | **`Without filters`**                                        | **`Filters applied`**                                        |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| <img src="https://user-images.githubusercontent.com/387249/111805979-bf3b4c00-888e-11eb-885e-0fd62755097b.png"> | <img src="https://user-images.githubusercontent.com/387249/111805701-7f746480-888e-11eb-94d8-2645bf8ccbd5.png"> | <img src="https://user-images.githubusercontent.com/387249/111805950-b8143e00-888e-11eb-973c-52ea4f7ca789.png"> |

**`DoH automatic`**

| **`Automatic`**                                              | **`Without filters`**                                        | **`Filters applied`**                                        |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| <img width="1312" alt="Screen Shot 2021-03-19 at 8 42 31 AM" src="https://user-images.githubusercontent.com/387249/111806297-13dec700-888f-11eb-9786-50bf509aae5b.png"> | <img width="1312" alt="Screen Shot 2021-03-19 at 8 43 16 AM" src="https://user-images.githubusercontent.com/387249/111806650-6fa95000-888f-11eb-858e-e75a2e10fdf2.png"> | <img width="1312" alt="Screen Shot 2021-03-19 at 8 44 57 AM" src="https://user-images.githubusercontent.com/387249/111806653-7041e680-888f-11eb-9a20-b9cbb45c7fdf.png"> |

**`Cloudflare`**

| **`Cloudflare`**                                             | **`Without filters`**                                        | **`Filters applied`**                                        |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| <img width="1312" alt="Screen Shot 2021-03-19 at 8 47 07 AM" src="https://user-images.githubusercontent.com/387249/111806921-b5feaf00-888f-11eb-8efe-87b207dc6621.png"> | <img width="1312" alt="Screen Shot 2021-03-19 at 8 48 00 AM" src="https://user-images.githubusercontent.com/387249/111807131-dfb7d600-888f-11eb-8d40-a9e927984f8f.png"> | <img width="1312" alt="Screen Shot 2021-03-19 at 8 46 35 AM" src="https://user-images.githubusercontent.com/387249/111806925-b6974580-888f-11eb-88b5-5ca2a69fdb9e.png"> |

**NextDNS**

| **`NextDNS`**                                                | **`Without filters`**                                        | **`Filters applied`**                                        |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| <img width="1312" alt="Screen Shot 2021-03-19 at 8 49 49 AM" src="https://user-images.githubusercontent.com/387249/111807498-39b89b80-8890-11eb-854a-4d02d06c17fc.png"> | <img width="1312" alt="Screen Shot 2021-03-19 at 8 49 58 AM" src="https://user-images.githubusercontent.com/387249/111807503-3ae9c880-8890-11eb-8b51-7ff9521ce4ce.png"> | <img width="1312" alt="Screen Shot 2021-03-19 at 8 50 47 AM" src="https://user-images.githubusercontent.com/387249/111807501-3a513200-8890-11eb-8af6-598a07be472a.png"> |

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.22.66 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/8279

<details>
<summary>DoH Automatic</summary>

https://user-images.githubusercontent.com/17010094/111959537-809fce80-8ae6-11eb-8a55-d74d1260e316.mp4


</details>
<details>
<summary>DoH OpenDNS</summary>

https://user-images.githubusercontent.com/17010094/111961043-6bc43a80-8ae8-11eb-8c83-be40e53c9929.mp4


</details>
<details>
<summary>DoH CloudFlare</summary>

https://user-images.githubusercontent.com/17010094/111961280-c52c6980-8ae8-11eb-93d1-515ce89c9148.mp4


</details>

--------
Verification passed on Samsung Tab A with Android 10 running 1.22.66 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/8279

<details>
<summary>DoH Automatic</summary>

https://user-images.githubusercontent.com/17010094/111979599-2c541900-8afd-11eb-8bb7-4f7b2b418310.mp4

</details>
<details>
<summary>DoH OpenDNS</summary>

https://user-images.githubusercontent.com/17010094/111980719-9c16d380-8afe-11eb-9207-4b7f2df9c032.mp4

</details>
<details>
<summary>DoH CloudFlare</summary>

https://user-images.githubusercontent.com/17010094/111981255-56a6d600-8aff-11eb-8cef-9ba38fc4d8f9.mp4


</details>

**Comment by bsclifton** [comment]
Moving to 1.23 after manually reverting from 1.22.x with https://github.com/brave/brave-core/commit/f20e8ba35f798ee3a8206512705d7b708e67c090

The fix for this appears to be causing https://github.com/brave/brave-browser/issues/14721 on all channels
