### ISSUE TITLE
Fix regression in CNAME uncloaking

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#14756]
[This change](https://github.com/brave/brave-core/commit/bd1a6e9430789b6577838137eb356f8f22b1ea89#diff-0986ef9872f15c706dc15f78ee8ef549348a10918b13d126e4483261d7171853R85) accidentally modified a URL involved in CNAME uncloaking, causing uncloaked results to be ignored.

There may be some additional platform-specific issues with the DNS resolvers that prevent this change from working, but those are captured in https://github.com/brave/brave-browser/issues/14755.

**Comment by kjozwiak** [comment]
This only fixes `Android` & `macOS` as per the labels. `Win x64` & `Linux` are still displaying `1` after adding the custom filter in `brave://adblock` and will be addressed in a follow up issue.

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8262 on build 

Brave | 1.23.43 Chromium: 89.0.4389.90 (Official Build) beta (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. visited `https://pushbullet.com` (there should be 1 request being blocked)
<img width="938" alt="Screen Shot 2021-03-17 at 1 29 43 PM" src="https://user-images.githubusercontent.com/387249/111534449-3bb21b80-8725-11eb-9aed-6ef37828c87a.png">

2. added the following custom filer via `brave://adblock`
```
||stripecdn.map.fastly.net^$important
||d2rhbqunra2aep.cloudfront.net^$important
```
<img width="938" alt="Screen Shot 2021-03-17 at 1 27 47 PM" src="https://user-images.githubusercontent.com/387249/111534480-440a5680-8725-11eb-85a4-18def6780a08.png">


3. opened new tab
4. visited `https://pushbullet.com` (there should be 2 requests blocked)
<img width="938" alt="Screen Shot 2021-03-17 at 1 27 38 PM" src="https://user-images.githubusercontent.com/387249/111534401-2f2dc300-8725-11eb-9e14-abd0180ff4f3.png">

**Comment by kjozwiak** [comment]
Also verified on `Win x64` on Nightly via https://github.com/brave/brave-core/pull/8262#issuecomment-801436246. The remaining part of this will be fixed via https://github.com/brave/brave-core/pull/8279 which will also be uplifted.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.22.66 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/8262

Before custom filters | Custom Filters | Post custom filters
--|--|--
![image](https://user-images.githubusercontent.com/17010094/111950633-7972c380-8ada-11eb-95ae-996c39d3a6cc.png) | ![image](https://user-images.githubusercontent.com/17010094/111950649-8099d180-8ada-11eb-9726-45845c29d7ee.png) | ![image](https://user-images.githubusercontent.com/17010094/111950677-8b546680-8ada-11eb-9475-17741516ed9f.png)

---------
Verification passed on Samsung Tab A with Android 10 running 1.22.66 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/8262

Before custom filters | Custom Filters | Post custom filters
--|--|--
![image](https://user-images.githubusercontent.com/17010094/111951275-5ac0fc80-8adb-11eb-9959-7bccbcd20524.png) | ![image](https://user-images.githubusercontent.com/17010094/111951300-6280a100-8adb-11eb-89f1-0906dd00f43f.png) | ![image](https://user-images.githubusercontent.com/17010094/111951313-690f1880-8adb-11eb-996a-498b9e2d4142.png)
