### ISSUE TITLE
Add import to IPFS context menu which pins content

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14769]
When using the local node, add a context menu for IPFS

It should have submenu items for these same cases that IPFS companion has:
https://github.com/ipfs-shipyard/ipfs-companion/blob/39e01f1e4dc3479a8479849c800f164be4a17c81/add-on/_locales/en/messages.json#L154

- IPFS
  - This page
  - Selected Image
  - Selected Video
  - Selected Audio
  - Linked Content (right clicking on a link)
  - Selected Text (right clicking on selected text)

After pinning open the IPFS page for imports and copy shareable link to clipboard

**Comment by sanderpick** [comment]
Hello! I added a related issue regarding remote pinning services: https://github.com/brave/brave-browser/issues/14879

**Comment by lidel** [comment]
Details TBD, but if we want to follow Companion UX, starting point would be user flow like this:
- add to ipfs without pinning  (via `ipfs add --pin=false`)
- copy reference to MFS to preserve filename and enable GUI for management (`ipfs cp /ipfs{cid} /brave-imports/timestamp/filename` )
- copy shareable link to clipboard
- open `127.0.0.1:{api-port}/#/files/brave-imports/timestamp/`  in a new tab, so user can do additional management 

The main idea being all imports are places under MFS dir like  `/brave-imports` so user can get back to them later and reuse ipfs-webui for file management (renaming, moving, pinning/unpinning)

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan in https://github.com/brave/brave-core/pull/8422 with build


Brave | 1.25.28 Chromium: 90.0.4430.72 (Official Build) nightly (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1. `This page`: - loaded `http://en.wikipedia-on-ipfs.org.ipns.localhost:48081/wiki/`
2. right-clicked and selected `Import to IPFS > This page` verified shareable  `https://bafybeid6bkv5kfjcjg6b2qvkah5ynq53difvzn3m53bacla5jygv75kdri.ipfs.dweb.link/?filename=en.wikipedia-on-ipfs.org.ipns.localhost` was copied to the clipboard and added to my local IPFS store
3. `Selected image`: - loaded `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/`
4. right-clicked and selected `Import to IPFS > This image`; verified shareable 
`https://dweb.link/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR?filename=bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi.ipfs.localhost` was copied to the clipboard and added to my local IPFS store
5. `Selected video`: loaded `https://www.learningcontainer.com/mp4-sample-video-files-download/`
6. right-clicked and selected `Import to IPFS > Selected video`; verified shareable `https://dweb.link/ipfs/QmTv2Tx9XQeLrvg8rs9LCCih6FrHt2mXs3LVBt23ZD7eE7?filename=sample-mp4-file.mp4` was copied to the clipboard and added to my local IPFS store
7. `Selected audio`: - loaded `https://archive.org/download/lp_the-dark-side-of-the-moon_pink-floyd/disc1/01.02.%20Breathe_sample.mp3`
8. right-clicked on the sample MP3 file, chose `Import to IPFS > Selected audio`; verified shareable `https://dweb.link/ipfs/QmT9EL9qE9JZiyK2z2cNzPxo7AHiTZ3brVKbe8PdZhZkqm?filename=01.02.+Breathe_sample.mp3` was copied to the clipboard and added to my local IPFS store
9. `Linked content`: - loaded `https://archive.org/details/Night.Of.The.Living.Dead_1080p` then from `MP3` on the right-hand side, I selected `DVD9`; 
10. right-clicked on the expanded file `https://archive.org/download/Night.Of.The.Living.Dead_1080p/NightOfTheLivingDead_DVD9.mp3` and chose `Import to IPFS > Linked content`; verified shareable `https://dweb.link/ipfs/Qmf1Eu6t5akZ4RYubtnxUviSMH3U6P4S597jLPUoRjsKN8?filename=NightOfTheLivingDead_DVD9.mp3` was copied to the clipboard and added to my local IPFS store
11. `Selected text`: - loaded `https://www.lipsum.com/` and selected the 1st paragraph's text
12. right-clicked and chose `Import to IPFS > Selected text`; verified shareable link `https://dweb.link/ipfs/QmR7bm2wMUrjbM8nWqo6yagPzfXYH8CEfkEqiS7zBqK7Cw?filename=www.lipsum.com_13828526949295533255`
13. repeated the above, and verified I got the `IPFS import partial complete` message notification
14. `Different text, same lipsum.com page`: loaded `https://www.lipsum.com/` and selected the 2nd paragraph's text
15. right-clicked and chose `Import to IPFS > Selected text`; verified shareable link `https://dweb.link/ipfs/QmSeeBaua38kEjRpdjiJmkPjHw45xg337ehBj8BRh3B4R7?filename=www.lipsum.com_4612201308639394218`

<img width="1312" alt="Screen Shot 2021-04-20 at 4 37 16 PM" src="https://user-images.githubusercontent.com/387249/115477763-80841300-a1f9-11eb-8192-fd3bf8e61145.png">
