### ISSUE TITLE
Prevent empty selectors from being migrated from legacy cosmetic filters

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#14763]
Followup to https://github.com/brave/brave-browser/issues/9581

As visible in https://github.com/brave/brave-browser/issues/9581#issuecomment-797745287, migrating the legacy cosmetic filtering implementation to the `brave://adblock` "Custom filters" box results in some invalid rules that have no CSS selector.

This appears to be caused by the logic for retrieving the selector from `window.prompt` - a fallback to an empty string is used, even though no rule should be generated if an empty selector is passed, or if the prompt is closed rather than submitted.

This should be fixed by updating the prompt to `trim` whitespace from the selector, and only adding the rule if it is non-empty. Additionally, any filters migrated from the legacy implementation should be ignored if the selector is blank.

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8270 with `nightly` build 

Brave | 1.24.5 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

**Verified the following cases:**

### Migration

Using a *previous* browser version (`1.21.77`):

1. Visit `brave://adblock` in a new tab
2. Add some text of your choice to the "Custom filters" box

<img width="960" alt="Screen Shot 2021-03-18 at 4 48 02 PM" src="https://user-images.githubusercontent.com/387249/111711832-c5d3b000-8809-11eb-9e7e-a914bcd33cd4.png">

I added

```
SupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidocious

1234567890
foo
facebook.com
https://www.cnn.com
!@#$%^&*()_+
```

1. Visit a website of your choice (`aol.com`, `twitch.tv`, and `sfgate.com`)
2. Right-click on a page element of your choice
3. Select "Brave > Block element via selector"
4. Confirm the block
5. Repeat steps 3-6 a few times to block a variety of items through the legacy system. Block multiple items on the same page at least once.  Keep track of what is being blocked. **Be sure to close the prompt window, press cancel, or just press OK with an empty rule each at least once.**


| `aol.com` (1.21.77) | `twitch.tv` (1.21.77) | `sfgate.com` (1.21.77) |
|--------------------------|----------------------------|--------------------------|
| <img width="1770" alt="Screen Shot 2021-03-18 at 4 29 17 PM" src="https://user-images.githubusercontent.com/387249/111711749-a0df3d00-8809-11eb-902e-d131ef1b078d.png"> | <img width="1771" alt="Screen Shot 2021-03-18 at 4 19 24 PM" src="https://user-images.githubusercontent.com/387249/111711754-a2106a00-8809-11eb-834f-d33d2d103caa.png"> | <img width="1770" alt="Screen Shot 2021-03-18 at 4 21 08 PM" src="https://user-images.githubusercontent.com/387249/111711751-a177d380-8809-11eb-881b-5d0edfb11abb.png"> |

Then, testing the same profile *after* the version upgrade:

1. Visit `brave://adblock` in a new tab
2. Verify that any text previously added to the "Custom filters" box is still present
3. Verify that new lines have been added to the "Custom filters" box,  including one corresponding to each item previously blocked using the  right click menu, **and that no rules were generated that are empty after the `##`**

**Verified there are no empty filter-rule sets in `brave://adblock`**

<img width="1448" alt="Screen Shot 2021-03-18 at 5 22 06 PM" src="https://user-images.githubusercontent.com/387249/111714250-8065b180-880e-11eb-813a-a7513dec55f9.png">

4. Revisit some of the websites and confirm that any previously blocked items are still hidden

**Verified that previously blocked elements are still blocked**

| aol.com (1.24.5)                                             | twitch.tv (1.24.5)                                           | `sfgate.com` (1.24.5)                                        |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| <img width="1770" alt="Screen Shot 2021-03-18 at 4 30 33 PM" src="https://user-images.githubusercontent.com/387249/111711744-9fae1000-8809-11eb-80d9-e01b3cfedfca.png"> | <img width="1770" alt="Screen Shot 2021-03-18 at 4 30 42 PM" src="https://user-images.githubusercontent.com/387249/111711739-9f157980-8809-11eb-99ac-34d12bce94bc.png"> | <img width="1770" alt="Screen Shot 2021-03-18 at 4 21 08 PM" src="https://user-images.githubusercontent.com/387249/111711751-a177d380-8809-11eb-881b-5d0edfb11abb.png"> |

### Adding new filters

Just on `1.24.5`:

1. Visit a website of your choice (`cnn.com`)
2. Right-click on a page element of your choice
3. Select "Brave > Block element via selector"
4. Confirm the block
5. Verify that the blocked item is hidden, and remains hidden after a page refresh
6. Reopen or refresh `brave://adblock` and verify that a new line has been added corresponding to the newly blocked item
7. Repeat steps 1-6 at least one more time
8. **Repeat steps 1-6 for each of the following, and ensure that \*no\* new lines are created in brave://adblock: closing the prompt window,  pressing cancel on the prompt window, and pressing OK with an empty rule in the prompt window**

**Verified there are no empty filter-rule sets  in `brave://adblock`**

| `cnn.com` (blocking content / empty selectors)               | `brave://adblock` filter set                                 |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| <img src="https://user-images.githubusercontent.com/387249/111711736-9d4bb600-8809-11eb-8dd0-738e7dec6e7c.gif"> | <img width="1447" alt="Screen Shot 2021-03-18 at 4 41 41 PM" src="https://user-images.githubusercontent.com/387249/111711733-9c1a8900-8809-11eb-99a8-bf1e1bcfdce5.png"> |


**Reference images (no blocked items)**

| `aol.com`                                                    | `twitch.tv`                                                  | `sfgate.com`                                                 | `cnn.com`|
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |--------------------------------|
| <img width="1770" alt="Screen Shot 2021-03-18 at 4 16 31 PM" src="https://user-images.githubusercontent.com/387249/111711755-a2a90080-8809-11eb-8ed3-ec721b46d733.png"> | <img width="1771" alt="Screen Shot 2021-03-18 at 4 16 00 PM" src="https://user-images.githubusercontent.com/387249/111711726-98870200-8809-11eb-9aac-392545502a88.png"> | <img width="1792" alt="Screen Shot 2021-03-18 at 4 55 44 PM" src="https://user-images.githubusercontent.com/387249/111712416-d0427980-880a-11eb-986c-ead0ab701df2.png"> | <img width="993" alt="Screen Shot 2021-03-18 at 5 28 52 PM" src="https://user-images.githubusercontent.com/387249/111714698-755f5100-880f-11eb-8a17-8e8b443860e5.png">
