### ISSUE TITLE
Tab grouping UI is wrong

### ISSUE THREAD

**Issue by Stephcraft** [brave/brave-browser#14765]
## Description 

The new tab group feature has UI problems. The group name label is not rounded corner and it is not spaced properly with the grouped tabs. The grouped border of the selected tab in the group is bigger than all other tabs. I've attached an image of what it looks like vs what it looks like in chrome (great ui design)

## Steps to Reproduce

   1. Open a couple tabs
   2. Right click on a tab > Add tab to group
   3. Give a name to the group

## Actual result:

![image](https://user-images.githubusercontent.com/23728346/111372695-5a56da80-8671-11eb-923a-e99d8b2475b5.png)

## Expected result:
![image](https://user-images.githubusercontent.com/23728346/111372807-807c7a80-8671-11eb-839e-1439a649aadc.png)

## Reproduces how often: 

Always reproduced

## Brave version

1.21.77

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **Yes**
- Can you reproduce this issue with the nightly channel? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **No, It looks good on chrome**

## Miscellaneous Information:

None

**Comment by not-a-dev-stein** [comment]
Having the same issue here. I have used Ungoogled Chromium for a while before coming back to Brave yesterday, so it really weirded me out why this visual stuff was happening. 

The best I'm able to do to deal with this for now is adding a space before and after the tab group name to have a little more proper spacing to the title.

**Comment by karenkliu** [comment]
@rebron No design mockups required; this is a feature fully ported over from Chromium and it should look like the expected result posted in the issue.

**Comment by jdsimcoe** [comment]
I've noticed this same border clipping issue (but only on system light mode). On dark mode the Tab Group stroke appears more standard:

![image](https://user-images.githubusercontent.com/275617/123131135-435b1d80-d402-11eb-9aad-2c3b5fe3e014.png)

**Comment by NeuronSooup** [comment]
I wonder if this 2 year old issues has been resolved yet? Oh that is right, it hasn't. Nevermind, I guess injecting Ads in Brave Search is more important

**Comment by jdsimcoe** [comment]
@NeuronSooup looks visually resolved to me 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/275617/225105029-1c336ff7-3a6d-4810-ba56-0b6ba1989531.png">

**Comment by Stephcraft** [comment]
> @NeuronSooup looks visually resolved to me <img alt="image" width="682" src="https://user-images.githubusercontent.com/275617/225105029-1c336ff7-3a6d-4810-ba56-0b6ba1989531.png">

That's true, some progress has been made, but there are still 3 mistakes:

**1.** In this case, everything is good, but perhaps we could have even more rounded corners for the label, so it stays consistent with the empty circle design:
![image](https://user-images.githubusercontent.com/23728346/225108657-fd4b7605-df75-476a-b65e-ba5881ed8ca4.png)

![image](https://user-images.githubusercontent.com/23728346/225108981-5f4180da-9689-4745-9764-b06d6f956959.png)

**2.** When the window is maximized or/and the first tab of the group is selected, the edges touch:
![image](https://user-images.githubusercontent.com/23728346/225109358-7bf2f54b-b613-4415-afb2-805d9d173b26.png)

**3.** When the last tab of the group is selected, the border is no longer rounded at the end (Like in your case):
![image](https://user-images.githubusercontent.com/23728346/225109652-ef6093e5-7872-40b8-b485-a9a36b02d344.png)

vs

![image](https://user-images.githubusercontent.com/23728346/225109709-1265409b-d818-49cd-a26b-e8b477419f89.png)

**Comment by jdsimcoe** [comment]
ah yeah that's weird

**Comment by Stephcraft** [comment]
Let's goooo!!
![image](https://github.com/brave/brave-browser/assets/23728346/e51e91c6-f087-41fb-9ba5-eb79b73ef33e)
