### ISSUE TITLE
Add ability to prove IPNS content ownership with libp2p-key

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14774]
Placeholder for integrating with rewards for IPFS.

- If a website is opened via DNSLink, use their domain info to allow tips to that creator's content.
- Allow users to "prove" they own certain IPNS content using their libp2p-key. They would basically add content they own and prove they own it in the creators site.

**Comment by bbondy** [comment]
@lidel do you have an idea on how this could be implemented? Maybe first manually how it could work via command line?

**Comment by lidel** [comment]
DNSLink is easy – if user already gets credited for `https://example.com`, Brave should do the same for `ipns://example.com`

The second one, assuming IPNS is used for publishing as drafted in https://github.com/brave/brave-browser/issues/14770#issuecomment-814483381,  Brave could read user's keys via `ipfs key list -l`, a command that lists private key names along with pubkey address used in IPNS. 

This should be enough to "prove" they are publishers,  Brave could also include some unique `/.well-known/../file` inside the published website as additional check.

**Comment by lidel** [comment]
https://github.com/ipfs/kubo/issues/10230 will make signing arbitrary bytes with IPNS key easier (removing the need for exporting the key and signing with external code)

**Comment by lidel** [comment]
`ipfs key sign|verify` RPC commands are in Kubo 0.25.0-rc1 and will be shipped in 0.25 ([release notes](https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.25.md#commands-ipfs-key-sign-and-ipfs-key-verify)) 

This allows confirming key ownership in offline mode, without having to do online IPNS publishing and resolution dance.
