### ISSUE TITLE
Add ability to publish a webpage to IPFS

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14770]
This is a placeholder to add  the ability to recursively publish a website to IPFS. 

Perhaps this will pin content of the current page, subresources, and some depth of links automatically.

**Comment by bbondy** [comment]
@lidel do you have an idea on how this could be implemented?

**Comment by lidel** [comment]
Depends on if you want to publish immutable snapshot (`ipfs://`), or want to have an address that can track updates (`ipns://`).

Former is easy, you `ipfs add --cid-version 1 -rw <dir>`  to recursively add a directory to IPFS and you get CID of the root directory in return. It can be loaded via `ipfs://{cid}`

The latter is the same, but additionally you need to have a mutable pointer to an immutable snapshot at  `/ipfs/{cid}` that you can update over time. 

Right now we have two ways of creating such pointers:
- [DNSLink](https://docs.ipfs.io/concepts/dnslink/) – requires publishing DNS TXT record with IPFS concent path under some DNS name
  - Regular users won't have own domains, so this could work only if Brave takes care of publishing and updating  TXT record for subdomains under your  control, like `ipns://<somename>.brave-sites.com` 
- [IPNS](https://docs.ipfs.io/concepts/ipns/) - built-in cryptographic solution provided  by IPFS node (independent of DNS).
  Broad strokes of potential integration:
  - Brave could provide UI for generating unique publishing keys  via `ipfs key` commands. Each website would have own key and can be loaded via `ipns://{libp2p-key}` like `ipns://k51qzi5uqu5dgutdk6i1ynyzgkqngpha5xpgia3a5qqp4jsh0u4csozksxel2r`
  - Publishing a CID under a key is  `ipfs name publish --key={key} --ipns-base=base36 /ipfs/{cid}`
  - Sidenote: 
     - Most likely want to enable [ipns over pubsub](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipns-pubsub) for improved publishing/resolution performance

**Comment by spylogsster** [comment]
Created PR without p2p-key management because we need to clarify how it should look for users from the product side

**Comment by stephendonner** [comment]
I started testing & verifying this using the testplan at https://github.com/brave/brave-core/pull/8561 (where 3/5 cases are fine), but ran into https://github.com/brave/brave-browser/issues/15634 - I'll wait for that to be resolved before coming back to fully verify this.

**Comment by LaurenWags** [comment]
@stephendonner is this issue blocked by https://github.com/brave/brave-browser/issues/15634? if so, we should have this as `QA/Blocked`, but if it can continue to be tested, might be a good idea to shake out anything else.

**Comment by stephendonner** [comment]
> @stephendonner is this issue blocked by #15634? if so, we should have this as `QA/Blocked`, but if it can continue to be tested, might be a good idea to shake out anything else.

Not totally blocked by that behavior (which I've since been told is expected via Chromium's, which we inherit), thanks for asking for clarification; the real problem, I think, is https://github.com/brave/brave-browser/issues/15935, which @spylogsster is looking into.  I'll mark it `QA/Blocked` for that reason, and revisit soon 👍

**Comment by stephendonner** [comment]
Removed `QA/Blocked` - https://github.com/brave/brave-browser/issues/15935 stemmed from a regression in https://github.com/brave/brave-browser/issues/15422, so we'll get https://github.com/brave/brave-browser/issues/16020 tested in `nightly` and then uplifted to `1.26.x` - nothing for `1.25.x` should be needed from any of those.

Running through the tests for this now 👍

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8561 on build

| Brave    | 1.25.65 Chromium: 91.0.4472.57 (Official Build) (x86_64)     |
| -------- | ------------------------------------------------------------ |
| Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6} |
| OS       | macOS Version 11.3.1 (Build 20E241)                          |

### Check various cases when you have ongoing downloads and you do the import for a web page, it should not appear on the shelf with others

<summary>
<details>

Steps:

1. loaded `https://www.leaseweb.com/platform/network` and downloaded a 10,000 mb file (`http://mirror.sfo12.us.leaseweb.net/speedtest/10000mb.bin`), so I could test sharing while downloads were still ongoing
2. loaded `cnn.com`
3. chose `File` | `Save Page As...`
4. clicked `Save`
5. clicked on the "hamburger" menu and chose `IPFS` -> `Share Local Folder Using IPFS`
6. browsed to the CNN directory and clicked `OK`

Confirmed I only saw the original CNN page being saved to Downloads, not when IPFS sharing

</details>

### Check that downloaded pages are not visible in the download history

<summary>
<details>

Steps:

1. loaded `https://en.wikipedia.org/wiki/Vincent_van_Gogh`
2. chose `File` | `Save Page As...`
3. clicked `Save`
4. clicked on the "hamburger" menu and chose `IPFS` -> `Share Local File Using IPFS`
5. browsed to the Vincent_van_Gosh - Wikipedia.html` file and clicked `OK`

Confirmed that only the Wikipedia page I saved locally to share later via IPFS showed up in the Downloads window

<img width="1749" alt="Screen Shot 2021-05-21 at 10 15 51 AM" src="https://user-images.githubusercontent.com/387249/119176938-83ed0300-ba20-11eb-9a97-6a81bda39f77.png">
</details>

### Check that the tab does not crash if downloading is in progress

Confirmed no crashes while testing

### Check imported files have same content as originals

<summary>
<details>

Steps:
1. loaded `https://ia801003.us.archive.org/26/items/1941themaltesefalconelhalconmaltesjohnhuston/1941%20-%20The%20Maltese%20Falcon%20-%20El%20halc%C3%B3n%20malt%C3%A9s%20-%20John%20Huston%20-%20VOSE.ogv`
2. chose `File` | `Save Page As...` and saved to Desktop
3. clicked on the "hamburger" menu and chose `Share Local File using IPFS`
4. waited
5. confirmed I got a shareable link copied to my clipboard, and a system notification - link is `https://dweb.link/ipfs/QmXxxrEnnqNgXMyAqNUZ4vhqugXmgfbSHJo3yp8tzReTvF`
6. confirmed after clicking the folder name, I was able to watch The Maltese Falcon

<img width="1749" alt="Screen Shot 2021-05-21 at 10 51 31 AM" src="https://user-images.githubusercontent.com/387249/119178943-30c87f80-ba23-11eb-8fb4-b9cbbf95f30d.png">
</details>


### Check imported pages open correctly by shareable link

<summary>
<details>

Steps:

1. loaded `https://en.wikipedia.org/wiki/Vincent_van_Gogh`
2. chose `File` | `Save Page As...` and clicked `Save`
3. clicked on the "hamburger" menu on the browser toolbar and chose `Share Local File Using IPFS`
4. browsed to `Vincent_van_Gogh - Wikipedia.html` and clicked `Open`
5. confirmed I got a shareable IPFS link copied to my clipboard, and a system notification - link is `https://dweb.link/ipfs/QmX9YryCrJjvP4xBqVv5yEVexjm9CHpuhtrVqWapxHz6iR?filename=Vincent+van+Gogh+-+Wikipedia.html`
6. copied and pasted the link in a new tab and pressed `return` to open
7. compared the output of the IPFS-shared file to the locally-saved one
8. confirmed the content and layout is mostly the same (IPFS version looks better, actually)

<img width="1673" alt="Screen Shot 2021-05-21 at 10 15 17 AM" src="https://user-images.githubusercontent.com/387249/119177074-a848df80-ba20-11eb-87ab-123a4c74a6cc.png">
</details>


@spylogsster @bbondy @lidel do you think this needs to be tested on all platforms, or is this abstracted/modular enough to be expected to work on macOS, Windows, and Linux?  Thanks!

**Comment by lidel** [comment]
@stephendonner  I am not familiar with Chromium internals to tell if this is abstracted away, but there is a potential diff around each OS having code paths for opening the file/dir picker GUI. Everything else should be the same.
