### ISSUE TITLE
Add IPFS gateway support for iOS

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14775]
This is a placeholder to add gateway support for iOS

**Comment by stephendonner** [comment]
@spylogsster can we get an iOS-specific test plan?  I'd like to work that into https://github.com/brave/brave-browser/wiki/IPFS-Features (as Android seems to have more-explicit support, we can't simply use its cases verbatim).  Thanks!

**Comment by spylogsster** [comment]
afaik it is not implemented for iOS yet, in this issue just need to check that overall ipfs works on desktop and android via localnode as usual
