### ISSUE TITLE
Add ability to read and manage cache

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14772]
This is a placeholder for when a user is using the local node. They should be able to read and manage their cache.

Lidel says:

> (it is posible to list all CIDs per root via ipfs refs -r and then manually remove each block via ipfs block rm but that will be ridiculously expensive for bigger trees, and won't account for a block being used in pinned trees, i think. so safer to wait for GC v2)

**Comment by lidel** [comment]
- blocks in local datastore can be listed via `ipfs refs local` (this includes ephemeral cache, low level pins and things in MFS)
  - not sure how useful this is, those are blocks without any context 
- repo stats can be read via `ipfs stats repo -H`
