### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined error when trying to select convert on Binance Widget

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14778]
## Description 

Cannot read property 'toLowerCase' of undefined error when trying to select convert on Binance Widget

## Steps to Reproduce

   1. Connect to Binance widget
   2. Click on convert tab
   3. Click on To conversion dropdown list, NTP carshes with error 
Note: No balance required to repro the issue. Happens on account connected with balance or a new connection

## Actual result:

https://user-images.githubusercontent.com/17010094/111417028-efdb8400-86dc-11eb-9eec-8e4982d2d766.mov

## Expected result:
No error or NTP crash

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64 Bit)
-- | --
Revision | `62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?  Most possibly yes
- Can you reproduce this issue with the nightly channel? Most possibly yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@rebron  please remove from NTP project board if its not relevant

**Comment by srirambv** [comment]
This seems to be fixed now. Disconnecting and reconnecting the widget works fine after the format revert from Binance

**Comment by bbondy** [comment]
closing since Binance fixed their endpoint.
