### ISSUE TITLE
Unable to play video on https://www.bt.com/sport/watch/live-now/bt-sport-3

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#14784]
## Description 
Visiting website, `https://www.bt.com/sport/watch/live-now/bt-sport-3` will generate an error.

## Steps to Reproduce

   1. Open `https://www.bt.com/sport/watch/live-now/bt-sport-3`
   2. No video playback 
   3. 

## Actual result:

<img width="989" alt="screen_shot_2021-03-16_at_3 07 33_pm" src="https://user-images.githubusercontent.com/1659004/111466940-c37d4180-8788-11eb-97cc-09866de6fea3.png">

## Expected result:
Expect video playback.

## Reproduces how often: 
Easily, with default shields

## Brave version (brave://version info)
`Version 1.22.58 Chromium: 89.0.4389.86 (Official Build) beta (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Confirmed Ephemeral Storage doesn't help here.  Allowing all cookies in shields will fix it.
Allowing cookies for `btsport-utils-prod.akamaized.net` allows playback
![bt-cookies](https://user-images.githubusercontent.com/1659004/111467416-4900f180-8789-11eb-8778-e1aae4c42642.png)

**Comment by ryanbr** [comment]
Investigating a possible fix.

**Comment by ryanbr** [comment]
Is now working, fixed via https://github.com/easylist/easylist/commit/f44220b3175cb43f5cfaa56483eeb165505709a5

**Comment by btlechowski** [comment]
@ryanbr Please add `QA/Yes` or `QA/No` to this issue. I also noticed that the content is behind a subscription so if you want QA to check it, then we need access.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.22.66 Chromium: 89.0.4389.90 (Official Build) (64-bit)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | Ubuntu 18.04 LTS

The error reported in OP is no longer shown

![image](https://user-images.githubusercontent.com/34715963/111990595-b27b5a00-8b13-11eb-8565-4621ae2fb467.png)
