### ISSUE TITLE
Refactor speedreader readability backend

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#14787]
Speedreader has two backends. The backend currently deployed on nightly uses [adblock-rs](https://github.com/brave/adblock-rust) and rewrites adblock rules into [lolhtml](https://github.com/cloudflare/lol-html) rules. There is a separate backend that implements an incomplete version of the Readability.js algorithm that is not yet reachable from the browser, but we want to move to it.

- [x] Move the DOM to https://github.com/kuchiki-rs/kuchiki as the `RcDom` shipped with `html5ever` [has no stability guarantees](https://github.com/servo/html5ever/issues/385)
- [x] Implement the entire Readability algorithm. 
- [x] Rework existing implementations to get rid of tree data structures

**Comment by rebron** [comment]
Reminder to add milestone once issue is fixed/closed. We only add milestone to open issues on rare occasions near release time for p1/p2 issues.
