### ISSUE TITLE
Remove third_party-crashpad-crashpad-client-settings.cc.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14789]
## Description 

This patch could be removed in favour of a chromium_src override redefining the `Settings::GetClientID()` method into something that uses the original implementation from upstream and simply resets the memory of `client_id` before returning when needed.

## Brave version (brave://version info)

Brave 1.24.2 (Chromium 89.0.4389.90)

## Miscellaneous Information:

This removal references a patch initially introduced with https://github.com/brave/brave-browser/issues/8865

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8278 with `nightly` build:

Brave | 1.24.29 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. triggered a crash via `brave://crash`
2. went to `brave://crashes` and ensured the crash was sent (crash ID is `4e160000-0c88-1106-0000-000000000000`)
3. looked up the crash ID on our backtrace instance
4. found my way to the `Debug` tab
5. from there, clicked on `Attributes`
6. checked value of `guid`

Got:

`guid` `00000000-0000-0000-0000-000000000000`

| Example | Example | Example |
|---------|----------|----------|
<img width="905" alt="Screen Shot 2021-03-26 at 2 07 23 PM" src="https://user-images.githubusercontent.com/387249/112693309-a954fa80-8e3d-11eb-8a66-209fdf96698f.png"> | <img width="994" alt="Screen Shot 2021-03-26 at 2 07 18 PM" src="https://user-images.githubusercontent.com/387249/112693310-a954fa80-8e3d-11eb-897b-3cb81f6c6b17.png"> | <img width="1792" alt="Screen Shot 2021-03-26 at 2 06 09 PM" src="https://user-images.githubusercontent.com/387249/112693313-a954fa80-8e3d-11eb-812f-29aceefd32c4.png">
