### ISSUE TITLE
[Desktop] Customize Dashboard modal window heading text not visible in dark theme - follow up to 14754

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14785]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/14754

While using dark theme, the "Customize Dashboard" text on the modal is not very visible. In 1.22.x this text is white when using dark theme. 

## Steps to Reproduce

   1. Using 1.23.43 or 1.24.1, open NTP with dark theme
   2. Click on Customize in lower right corner
   3. Customize Dashboard modal displays

## Actual result:

"Customize Dashboard" text is not visible in dark theme, but is visible in light theme

`1.23.43` Dark | `1.23.43` Light
----- | -----
<img width="1049" alt="1 23 43-dark" src="https://user-images.githubusercontent.com/28145373/111470638-73f23380-86fe-11eb-8175-5bda355d4026.png"> | <img width="1050" alt="1 23 43-light" src="https://user-images.githubusercontent.com/28145373/111470650-75bbf700-86fe-11eb-9e10-55d47bc96c71.png">

also occurs on `1.24.1` versions:

`1.24.1` Dark | `1.24.1` Light
----- | -----
<img width="1035" alt="1 24 1-dark" src="https://user-images.githubusercontent.com/28145373/111470723-8bc9b780-86fe-11eb-9738-aa58abc76c32.png"> | <img width="1036" alt="1 24 1-light" src="https://user-images.githubusercontent.com/28145373/111470731-8d937b00-86fe-11eb-87f4-d594e71cab8b.png">

## Expected result:

"Customize Dashboard" text should be visible on both light and dark themes as it is on 1.22.x:

`1.22.63` Dark | `1.22.63` Light
----- | -----
<img width="1145" alt="1 22 63-dark" src="https://user-images.githubusercontent.com/28145373/111470794-9ab06a00-86fe-11eb-9d8e-a79df21f6cad.png"> | <img width="1149" alt="1 22 63-light" src="https://user-images.githubusercontent.com/28145373/111470799-9be19700-86fe-11eb-9be9-7297c335c74c.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.23.43 Chromium: 89.0.4389.90 (Official Build) beta (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 10.15.7 (Build 19H524)

Brave | 1.24.1 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 10.15.7 (Build 19H524)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.21.x no, 1.22.x no
- Can you reproduce this issue with the beta channel? 1.23.x yes
- Can you reproduce this issue with the nightly channel? 1.24.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @rebron @petemill @bsclifton @brave/legacy_qa

**Comment by bsclifton** [comment]
It's possible this regressed with https://github.com/brave/brave-core/pull/8120
cc: @petemill

**Comment by simonhong** [comment]
This issue was fixed by @ryanml  but I can't assign him to this issue.
So, assigned me instead.

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.26.6 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:
1. Using both the `dark` and `light` themes, open the new-tab page
2. Click on `Customize` in lower right corner
3. The `Customize Dashboard` modal displays
4. Confirm that the text is readable against its background

dark | light
-----|-----
<img width="1312" alt="Screen Shot 2021-05-03 at 6 00 50 PM" src="https://user-images.githubusercontent.com/387249/116950476-f34daf00-ac39-11eb-854c-39e616cd60bc.png"> | <img width="1312" alt="Screen Shot 2021-05-03 at 6 01 01 PM" src="https://user-images.githubusercontent.com/387249/116950477-f3e64580-ac39-11eb-8dc8-ee2df747a4f7.png">
