### ISSUE TITLE
Publish full variation names on brave://version and allow to opt-out

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#14780]
For now, brave://version shows some hashed data instead of real variation names (if they exist). We can show full names and a browser-wide preference to opt-out of receiving variations.

**Comment by iefremov** [comment]
Edited this issue to only mention full names instead of hashes. For the opt-out toggle on Desktop filed a new one https://github.com/brave/brave-browser/issues/15711

**Comment by stephendonner** [comment]
Verified `FIXED` using the steps from https://github.com/brave/brave-core/pull/8699, and build

Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (64-bit)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | Windows 10 OS Version 2009 (Build 21376.1)

Steps:
1. clean profile
2. launch Brave
3. restart Brave
4. open `brave://version`
5. look at the bottom **`Variations:`** section

Confirmed that my `brave://version` page shows the following (without cryptic hash values):

**Variations:** `AdvertiserSplitTestStudy:GroupB`
                        `EphemeralStorageStudy:Enabled`
                        `PermissionLifetimeStudy:Enabled`

![variations](https://user-images.githubusercontent.com/387249/118187931-83d37e80-b3f4-11eb-857d-f49f5a9def87.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.26.46 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/8699

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/120276654-e230a600-c2aa-11eb-9483-018777d4f463.png> | ![image](https://user-images.githubusercontent.com/17010094/120276692-ee1c6800-c2aa-11eb-94dd-4e144a6e2727.png)
