### ISSUE TITLE
Add support for `$csp` filter rules

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#14792]
Easylist contains some rules with `$csp` options. These are useful as a last-resort when other more fine-grained blocking approaches are insufficient, and are implemented by modifying the `Content-Security-Policy` response headers from a document or subdocument request.

More details about the semantics of these options can be found on the uBlock Origin wiki and the AdGuard knowledgebase:
- https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#csp
- https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#csp-modifier

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/8281
Verified the scripts were blocked:
```
Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' <URL> *.hcaptcha.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

![image](https://user-images.githubusercontent.com/34715963/114935660-bdd45380-9e3b-11eb-88c0-3d18af9fdcc2.png)

**Comment by stephendonner** [comment]
@btlechowski is that the correct user-agent (`1.23.71`), as this is in the `1.25.x` milestone?

**Comment by btlechowski** [comment]
Right, silly mistake. Fixed.
