### ISSUE TITLE
Active tab hidden after closing other tabs on a tab page

### ISSUE THREAD

**Issue by lyndsysimon** [brave/brave-browser#148]
### Description
When closing several tabs (using "Close other Tabs" or "Close tabs to the left") results in the active tab being hidden

### Steps to Reproduce
1. Open 21 tabs.
2. On the 21st tab - the first tab on the second tab page - click "Close other Tabs". 

**Actual result:**
<img width="165" alt="screen shot 2018-04-05 at 10 46 56 am" src="https://user-images.githubusercontent.com/131414/38376896-44259718-38bf-11e8-819b-1a9bea826343.png">

**Expected result:**
![image](https://user-images.githubusercontent.com/131414/38376933-50f93d82-38bf-11e8-96b2-be49c8b85510.png)

**Reproduces how often:**
This behavior occurs every time, and is easily replicable

### Brave Version

**about:brave info:** 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
Yes

### Additional Information
I presume the solution here would be to perform an additional check to verify the tab page the currently active tab is on, then selecting it as active after closing other tabs.

**Comment by bbondy** [comment]
Moved to browser-laptop:
https://github.com/brave/browser-laptop/issues/14342
