### ISSUE TITLE
Add rounded corners to macOS/Linux custom ad notifications

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#14809]

**Comment by tmancey** [comment]
Resolved as part of #13132, please test as part of the new custom ad notifications

**Comment by stephendonner** [comment]
Verified `PASSED` on `macOS` using 

Brave | 1.26.7 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3.1 (Build 20E241)

and compared to:

Brave | 1.25.43 Chromium: 90.0.4430.85 (Official Build) nightly (x86_64)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:

1. new profile
2. launched with `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5`
3. clicked through the Welcome page
4. enabled Rewards
5. opened a few new-tab pages
6. waited
7. confirmed I got the system notification for ads

rounded, ads staging | rounded, ads prod | square, ads staging | square, ads prod
---------|----------|---------|----------
<img width="370" alt="Screen Shot 2021-05-05 at 1 20 00 PM" src="https://user-images.githubusercontent.com/387249/117206001-2bbecb80-ada7-11eb-97a5-de14b59cee6e.png"> | <img width="370" alt="Screen Shot 2021-05-05 at 1 24 05 PM" src="https://user-images.githubusercontent.com/387249/117206002-2bbecb80-ada7-11eb-8ea1-cb429651b7d9.png"> | <img width="390" alt="Screen Shot 2021-05-05 at 1 33 52 PM" src="https://user-images.githubusercontent.com/387249/117206004-2c576200-ada7-11eb-9893-ca81aa8f9e58.png"> | <img width="390" alt="Screen Shot 2021-05-05 at 1 37 07 PM" src="https://user-images.githubusercontent.com/387249/117206006-2c576200-ada7-11eb-9c3b-d5007abcd585.png">
