### ISSUE TITLE
The new "squircle" macOS icon is slightly off.

### ISSUE THREAD

**Issue by aparkerdavid** [brave/brave-browser#14801]
## Description
It's a little too large, and the drop shadow is a little too deep. See:
<img width="289" alt="111040353-a3ecbe80-8400-11eb-99a5-7a4def029ba9" src="https://user-images.githubusercontent.com/6626101/111561501-ef89ca00-876a-11eb-92c3-3985bae7810b.png">
No reason to eyeball-and-tweak this; Apple publishes a template for Big-Sur-style icons. It should be possible to just drop in the logo and get a pixel-perfect result. I'd be happy to do it myself, if I had access to the assets for the various alt-icons.

**Comment by bsclifton** [comment]
cc: @karenkliu @bradleyrichter

**Comment by rebron** [comment]
How we have the current logo is the size we want. Always happy to review proposals though.

**Comment by aparkerdavid** [comment]
Just to be clear: I'm not proposing that the Brave logo be resized relative to the squircle, I'm proposing that the squircle be resized and its drop shadow modified to match other Big-Sur-style icons.

![comparison](https://user-images.githubusercontent.com/6626101/111857085-93a77880-8905-11eb-95a3-0964c19cc659.png)

The Brave icon on the left is the one currently in use, the one on the right is an alternate I made using the [template](https://developer.apple.com/design/resources/#macos-apps) provided by Apple. If the mismatch is intentional, I propose that it be reconsidered; it's pretty noticeable in a dock full of squircles, and looks sloppy.

Like I said, I'd be happy to do the grunt work and put in a PR, I would need the assets for the dev, beta, etc. alternate logos.

**Comment by rebron** [comment]
@karenkliu I'll defer to you on this one.

My personal dock is full of squircles. 

![Screen Shot 2021-04-19 at 5 20 48 PM](https://user-images.githubusercontent.com/5951041/115318995-b9f24b00-a133-11eb-88aa-c6fa306ecab5.png)

**Comment by karenkliu** [comment]
The slightly larger icon and shadow was an intentional design choice.

Originally, we did use the Apple template for Big Sur icons. However, other apps, even ones that did the new squircle shape, didn't conform like we did - resulting in our app icon looking kinda puny in comparison. Take a look at Zoom, any of the Adobe app icons, any icon that didn't do the squircle shape, or even some Apple icons that didn't get the new treatment like Contacts and TextEdit. They are all bigger than the default Bir Sure app icon template provided by Apple. So after the first iteration where we followed the guidelines, in our second iteration we deviated from the guidelines on purpose to prevent our icon from looking too small in the dock relative to other icons.

**Comment by dchest** [comment]
Sorry for bringing this up again, but can you take another look at this issue? Now that many apps are updated to match Apple's HIG, maybe the icon can be brought back to the standard size? Additionally, the shadow is too large compared to native icons.

https://user-images.githubusercontent.com/52677/226204236-0333160d-e518-4a28-bfe7-40230168142c.mov


Contact and TextEdit are not really larger if you consider items that are inside the squircle:

<img width="438" alt="app-icon-layout-guides_2x" src="https://user-images.githubusercontent.com/52677/226204124-e4d4b215-0b9c-4f86-b35c-783464bcb2ad.png">

**Comment by bradleyrichter** [comment]
@aguscruiz Now that we have Leo, we should be able to properly address this and roll out updates into releases as time permits.

**Comment by simonhong** [comment]
@LaurenWags It's just resized a little bit and all channel's icons are changed..

**Comment by LaurenWags** [comment]
Thanks @simonhong.

Will do Nightly/Beta testing now and hold on the Release channel testing until we get an RC.

**Comment by aguscruiz** [comment]
@simonhong @LaurenWags is this already in Nightly? I can see the Nightly icon is perfect now, and the beta is slightly bigger 

Nightly: 1.52.23
Beta: 1.47
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/15734630/231204067-eed79056-bdd6-47dc-a440-b60bb83ae825.png">

**Comment by LaurenWags** [comment]
@aguscruiz definitely update your Beta please 😄 

Yes - expected to be in version 1.51.x and higher. So Nightly and Beta should both have the changes. Release won't have them until early May.

**Comment by LaurenWags** [comment]
Verification in progress on macOS x64/Intel

<details>
<summary>Nightly Channel - PASSED</summary>

Installed 1.51.67 and launched (version before this change).
Grabbed screenshot of icon in macOS dock.
Installed 1.51.68 and launched (version with this changed).
Grabbed screenshot of icon in macOS dock.
Compared the icons per PR.

1.51.67 | 1.51.68 | 1.51.67 vs 1.51.68
--- | --- | ---
<img width="74" alt="1 51 67" src="https://user-images.githubusercontent.com/28145373/231208091-77b17002-3662-40b5-b4f7-4d5fb8b824aa.png"> | <img width="75" alt="1 51 68" src="https://user-images.githubusercontent.com/28145373/231208093-ca99eb50-ac43-4e65-a7f6-39f967631512.png"> | <img width="140" alt="1 51 Nightly both" src="https://user-images.githubusercontent.com/28145373/231208193-e0d88acb-834c-4247-a570-19301f35543e.png">

</details>

**Comment by LaurenWags** [comment]
Awesome, thanks for the additional confirmation @aguscruiz, appreciate it 😄

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.106 Chromium: 113.0.5672.53 (Official Build) (x86_64)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | macOS Version 11.7.6 (Build 20G1231)

Release channel - `PASSED`

Installed `1.51.106` and launched (version with this change).
Grabbed screenshot of icon in macOS dock.
Compared the icons per PR.

`1.50.121` | `1.51.106` | `1.50.121 vs. 1.51.106`
-----------|-----------|----------------------
. | <img width="76" alt="Screen Shot 2023-04-27 at 10 10 02 AM" src="https://user-images.githubusercontent.com/387249/234939571-49473329-f42f-41b8-b185-3531c369544c.png"> | .


---

## Verified `PASSED` using 

Release channel - `PASSED`

Installed `1.51.106` and launched (version with this change).
Grabbed screenshot of icon in macOS dock.
Compared the icons per PR.

`1.50.121` | `1.51.106` | `1.50.121 vs. 1.51.106`
-----------|-----------|----------------------
