### ISSUE TITLE
Add deep link for add funds

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1480]
When user clicks on Add funds in rewards panel, we should open new tab with deep link to add funds dialog, so that it's opened automatically for the user

**Comment by NejcZdovc** [comment]
Link in panel should be like `chrome://rewards/#add-funds`. Then we need to add handler in settings page (JS) which will detect anchor and open appropriate modal.

**Comment by jasonrsadler** [comment]
There is currently a warning being thrown when click 'Add Funds' on pageWallet:

```
[9666:775:1107/214631.615971:ERROR:CONSOLE(26444)] "Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
```

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/834
