### ISSUE TITLE
Implement custom ad notification fade in/out transition

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#14811]

**Comment by tmancey** [comment]
Resolved as part of #13132, please test as part of the new custom ad notifications

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.26.50 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Ubuntu 18.04 LTS

Verified fade in and fade out animations
![14811](https://user-images.githubusercontent.com/34715963/120841287-9bbd9e80-c56b-11eb-94f6-e03afb9a1f7d.gif)

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy Tab version 10 running brave Beta build `Bravemonoarm64 1.26.56.apk`
- Ads fade in/out animation is not shown - Logged a follow-up issue https://github.com/brave/brave-browser/issues/16400
