### ISSUE TITLE
Allow the end user to move/reposition custom ad notifications

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#14813]

**Comment by tmancey** [comment]
Resolved as part of #13132, please test as part of the new custom ad notifications

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.26.50 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Ubuntu 18.04 LTS

Verified able to move the custom ad notification
![image](https://user-images.githubusercontent.com/34715963/120686081-e6beaf80-c4a0-11eb-98c5-b255036f1b68.png)
Verified the position is retained for the next ad, even after browser restart
![image](https://user-images.githubusercontent.com/34715963/120686463-461cbf80-c4a1-11eb-9299-b9545e0a2efb.png)
