### ISSUE TITLE
Remove chrome-browser-browsing_data-chrome_browsing_data_remover_delegate_factory.cc.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14819]
## Description 

This patch could be removed in favour of a chromium_src override that would define its own version of `ChromeBrowsingDataRemoverDelegateFactory::BuildServiceInstanceFor()` to simply return an instance of `BraveBrowsingDataRemoverDelegate()`, instead of patching the original method from upstream (which doesn't do anything else other than returning an instance of `ChromeBrowsingDataRemoverDelegate`).

## Brave version (brave://version info)

Brave 1.24.2 (Chromium 89.0.4389.90)

## Miscellaneous Information:

This removal references a patch initially introduced with https://github.com/brave/brave-browser/issues/8231 (and later modified for https://github.com/brave/brave-browser/issues/8826) so please use the test plan detailed in https://github.com/brave/brave-core/pull/4624 for QA purposes (i.e. check that things continue to work).

**Comment by mariospr** [comment]
Closing as per review comments in the associated PR

**Comment by stephendonner** [comment]
Verified `PASSED` using testplans from both https://github.com/brave/brave-browser/issues/8231 and https://github.com/brave/brave-browser/issues/8826

Brave | 1.24.65 Chromium: 90.0.4430.72 (Official Build) dev (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

Confirmed that the UI reads `Site and Shields Settings` in `brave://settings/clearBrowserData`

Steps:
1. Launched Brave with a new profile
2. Loaded `brave.com` and changed `Cross-site cookies blocked` to `Cookies blocked` via the Shields panel
3. Launched the Clear Browsing data dialog via `brave://settings/clearBrowserData`
4. Confirmed that Site Settings has `1 Site` as a label with the `Last hour` time range
5. Clicked the `Clear data` button and checked that the label is now `None`
6. Loaded `brave.com` and confirmed that `Cross-site cookies blocked` is now restored as the default in the Shields settings

example | example | example | example
---------|---------|----------|---------
<img width="1312" alt="Screen Shot 2021-04-15 at 2 23 36 PM" src="https://user-images.githubusercontent.com/387249/114940244-6233a700-9df6-11eb-9b57-ed9c7d35e00f.png"> |<img width="1312" alt="Screen Shot 2021-04-15 at 2 14 13 PM" src="https://user-images.githubusercontent.com/387249/114940356-9313dc00-9df6-11eb-98a5-c83b7fc1d17a.png"> | <img width="1312" alt="Screen Shot 2021-04-15 at 2 14 57 PM" src="https://user-images.githubusercontent.com/387249/114940374-9ad38080-9df6-11eb-85d7-1857fbb47134.png"> | <img width="1312" alt="Screen Shot 2021-04-15 at 2 15 28 PM" src="https://user-images.githubusercontent.com/387249/114940389-a1fa8e80-9df6-11eb-857b-5c78e8fbe181.png">
