### ISSUE TITLE
Remove chrome-browser-importer-profile_writer.h.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14817]
## Description 

This patch could be removed in favour of a chromium_src override that would add the new `AddCreditCard()` method into place using the already existing `AddAutofillFormDataEntries()` method as leverage.

## Brave version (brave://version info)

Brave 1.24.2 (Chromium 89.0.4389.90)

## Miscellaneous Information:

This removal references a patch initially introduced with https://github.com/brave/brave-browser/issues/8329 so please use either the "Expected results" section of the issue's description or the test plan detailed in https://github.com/brave/brave-core/pull/5582 for QA purposes (i.e. check that things continue to work).

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8292 with `nightly` build

Brave | 1.24.12 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

### Test 1

* Launched `Chrome` and verified there was no payment method specified in `Chrome` -> `Import Bookmarks and Settings...`
* Launched `Brave` -> `Import Bookmarks and Settings...` and verified payment methods option is hidden

| Chrome, showing empty Payments | Brave, Import dialog showing no Payment option |
|----------|---------|
<img width="930" alt="Screen Shot 2021-03-22 at 3 43 49 PM" src="https://user-images.githubusercontent.com/387249/112067527-6df8ba00-8b25-11eb-9c6a-f361c09b1fbe.png"> | <img width="1019" alt="Screen Shot 2021-03-22 at 3 36 02 PM" src="https://user-images.githubusercontent.com/387249/112067412-4144a280-8b25-11eb-8067-a61ecc049687.png">

### Test 2

* Launched `Chrome` and input an Amazon VISA payment method
* Launched `Brave` and loaded the `Import` dialog and verfied payment methods option was visible
* Started import via `Brave` -> `Import Bookmarks and Settings...` and checked `Chrome's` payment method was imported

| VISA card in Chrome's Payments | Import options showing Payment | macOS Keychain dialog | Importing into Brave | Successful import in Payments |
|----------|---------|----------|---------|----------|
<img width="819" alt="Screen Shot 2021-03-22 at 3 37 23 PM" src="https://user-images.githubusercontent.com/387249/112067431-4570c000-8b25-11eb-8c1f-2808365b30ab.png"> | <img width="1019" alt="Screen Shot 2021-03-22 at 3 37 42 PM" src="https://user-images.githubusercontent.com/387249/112067427-44d82980-8b25-11eb-91d1-0c8d8c615a60.png"> | <img width="546" alt="Screen Shot 2021-03-22 at 3 37 48 PM" src="https://user-images.githubusercontent.com/387249/112067423-443f9300-8b25-11eb-976a-8096ab531d7d.png"> | <img width="1019" alt="Screen Shot 2021-03-22 at 3 37 53 PM" src="https://user-images.githubusercontent.com/387249/112067421-43a6fc80-8b25-11eb-9f19-1ff41046680b.png"> | <img width="906" alt="Screen Shot 2021-03-22 at 3 38 33 PM" src="https://user-images.githubusercontent.com/387249/112067420-43a6fc80-8b25-11eb-8ae3-f56f8c247add.png">
