### ISSUE TITLE
Implement custom ad notification dark mode

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#14810]

**Comment by tmancey** [comment]
Resolved as part of https://github.com/brave/brave-browser/issues/13132, please test as part of the new custom ad notifications

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.26.50 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Ubuntu 18.04 LTS

Custom ads notification does not respect dark mode on Linux. Logged https://github.com/brave/brave-browser/issues/16234
![image](https://user-images.githubusercontent.com/34715963/120702392-4ffbee00-c4b4-11eb-8132-cc6244054c65.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy Tab version 10 running `Bravemonoarm64 1.26.56.apk`
Verified the test plan from https://github.com/brave/brave-core/pull/8377
- Confirmed custom AD notifications are served in Android
- Confirmed custom AD notification are shown correctly in Light mode
- Confirmed custom AD notification are shown correctly in Dark mode
- Encountered https://github.com/brave/brave-browser/issues/16350

 Light mode | Dark mode
--------------|-------------
![Screenshot_20210610-232233_Brave - Beta](https://user-images.githubusercontent.com/38657976/121573981-73d6ab00-ca43-11eb-97ee-4a56417a6427.jpg) | ![Screenshot_20210610-225018_Brave - Beta](https://user-images.githubusercontent.com/38657976/121574000-7a652280-ca43-11eb-8469-7454b38bbea4.jpg)
