### ISSUE TITLE
adblocker-update

### ISSUE THREAD

**Issue by dodona2** [brave/brave-browser#14818]
## Description 

since today (2021-March-18) a adblocker-update alert box appears frequently despite I have no adblocker installed. Whats going on here?

## Steps to Reproduce

   1. visit for example https://kinox.cloud/
   2. do nothing
   3. a adblocker-update alert box appears despite no adblocker installed

## Actual result:

https://abload.de/img/screenshotfrom2021-03cgjxq.png

## Expected result:
no a adblocker-update alert box 

## Reproduces how often: 

on some sites

## Brave version (brave://version info)

Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- with current fedora release yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- yes
- Does the issue resolve itself when disabling Brave Rewards? 
- no
- Is the issue reproducible on the latest version of Chrome? 
YES with Chromium Version 88.0.4324.182 (Developer Build) Fedora Project (64-bit)

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Hey, just checked the site @dodona2  No obvious popups,    

https://gif.fanboy.co.nz/gif/kinoxto.gif

Ensure you update `Brave Ad Block Updater - Version: 1.0.879 (or better)` in `brave://components`

**Comment by dodona2** [comment]
> brave://components

Brave Ad Block Updater - Version: 1.0.879
Status - Component not updated

**Comment by ryanbr** [comment]
I made some ad adserver addtions, if you force an update too 1.0.880. Does it help? @dodona2

**Comment by rebron** [comment]
@dodona2 Wanted to check if you're still seeing the pop-up? Our latest Brave version now is 1.25.68 and Brave Ad Block Updater - Version: 1.0.956

**Comment by ryanbr** [comment]
Safe to close @dodona2 ? I thought the popups wasn't resolved. but it seems fine now
