### ISSUE TITLE
Reset Brave Rewards data link should auto-select Reset tab in Manage Your Wallet panel

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14815]
## Description 
Reset Brave Rewards data link should auto-select Reset tab in Manage Your Wallet panel

## Steps to Reproduce

   1. load `brave://settings/clearBrowserData`
   2. click on `Reset Brave Rewards data...` (`chrome://rewards/#manage-wallet`)
   3. this invokes the `Manage Your Wallet` panel

## Actual result:

<img width="1359" alt="Screen Shot 2021-03-18 at 9 47 39 AM" src="https://user-images.githubusercontent.com/387249/111664439-ff3afa00-87ce-11eb-8973-bdd456aa67f6.png">

## Expected result:

Should select the `Reset` tab of the `Manage Your Wallet` panel

<img width="1359" alt="Screen Shot 2021-03-18 at 9 48 19 AM" src="https://user-images.githubusercontent.com/387249/111664557-209be600-87cf-11eb-9b55-ed2c04780c14.png">

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.24.4 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

**Comment by himansh-gjr** [comment]
Hii, I would love to work on this. This is my first time to Open source.

**Comment by himansh-gjr** [comment]
@stephendonner @Miyayes  can you please assign to me.

**Comment by stephendonner** [comment]
> @stephendonner @Miyayes can you please assign to me.

Sure; done, thanks!  If for some reason you're unable to work on it, please let us know so we can unassign it.

**Comment by omkarg01** [comment]
@stephendonner @Miyayes If this issue is still open. I would like to work on it.

**Comment by stephendonner** [comment]
> @stephendonner @Miyayes If this issue is still open. I would like to work on it.

Unsure if it's still open; @himansh-gjr are you still working on this?  If not, mind unassigning it, so we can reasssign to @omkarg01 ?  Thanks!
