### ISSUE TITLE
Failed contribution notification

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1481]
If something goes wrong with donation, user should be notified about that via panel notification.

**Comment by NejcZdovc** [comment]
closing as it will be addressed in this issue https://github.com/brave/brave-browser/issues/1483

**Comment by NejcZdovc** [comment]
blocked on https://github.com/brave/brave-browser/issues/1483

**Comment by NejcZdovc** [comment]
done in https://github.com/brave-intl/bat-native-ledger/pull/175

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

* See notes here https://github.com/brave/brave-browser/issues/1483#issuecomment-443013687 as test plan from https://github.com/brave/brave-core/pull/890 covers both issues.
