### ISSUE TITLE
Collapse frames with blocked content

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#14825]
uBlock Origin has some code that causes frames whose sources are blocked to be collapsed.

It appears that this works by generating a randomized alphanumeric string on each page load and adding it as an attribute to each blocked `iframe` element, and also injecting a CSS rule designed to block any element with that attribute.

e.g. when loading the following HTML:
```html
<html>
    <body>
        <iframe src="https://1-1ads.com/test.html"></iframe>
        <iframe src="https://101com.com/test.html"></iframe>
    </body>
</html>
```

With default Brave Shields configuration, the frames show a broken page (or suspicious document warning on 1.23.x with [this PR](https://github.com/brave/brave-core/pull/7952)).

When loading in uBlock Origin, the frames are invisible. When inspecting the page in the devtools console, the same random attribute is assigned to both (ex. `<iframe src="https://101com.com/test.html" tr5x7y7vs>`), and a `[tr5x7y7vs] { display: none !important; }` stylesheet is added to the page.

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan at https://github.com/brave/brave-core/pull/9144 with 

Brave | 1.28.20 Chromium: 91.0.4472.114 (Official Build) nightly (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)

Pre-requisite:
1. saved HTML locally from the 1st snippet in https://github.com/brave/brave-core/pull/9144 as `issue14825-testcase.html`
2. `mkdir issue14825`
3. `cd issue14825`
4. `mv ~/Desktop/issue14825-testcase.html .`
5. from /Users/stephendonner/Desktop/issue14825
stephendonner@Stephens-MacBook-Pro issue14825 % `python3 -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::1 - - [22/Jun/2021 10:50:22] "GET /issue14825-testcase.html HTTP/1.1" 200 -`


Steps:
1. loaded `http://localhost:8000/issue14825-testcase.html` with default Shields
2. confirmed only the `example.com` iframe loaded
3. set `Allow all trackers & ads` in Shields, and reloaded `http://localhost:8000/issue14825-testcase.html`
4. confirmed only the 2nd and 3rd frames -- `123freeavatars.com` and `example.com` -- loaded
5. via `brave://flags`, set `#brave-adblock-collapse-blocked-elements` to `Disabled` and relaunched Brave
6. confirmed I saw 3 `<iframe>s` but only `example.com` loaded its content

Steps 1 & 2 | Steps 3 & 4 | Steps 5 & 6
------------|-------------|-------------
<img width="1094" alt="Screen Shot 2021-06-22 at 10 53 01 AM" src="https://user-images.githubusercontent.com/387249/122985630-44814180-d353-11eb-9c34-2f84a964c79f.png"> | <img width="1778" alt="Screen Shot 2021-06-22 at 12 21 13 PM" src="https://user-images.githubusercontent.com/387249/122986479-5ca59080-d354-11eb-937b-c95567aa14e6.png"> | <img width="1626" alt="Screen Shot 2021-06-22 at 10 54 44 AM" src="https://user-images.githubusercontent.com/387249/122985690-5531b780-d353-11eb-92c2-e8bbecb54d78.png">

**Comment by srirambv** [comment]
Verification passed on Oppo R5 with Android 11 running 1.28.99 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/9144
- Verified with Adblock set to default(standard)/strict, only one frame is shown
- Verified disabling ad block shows all three iframes
- Verified with shields set to standard/strict, disabling `#brave-adblock-collapse-blocked-elements`, all three iframes are shown

![image](https://user-images.githubusercontent.com/17010094/128043510-1729ed3f-3dd5-47cc-ab07-9885efed4475.png) | ![image](https://user-images.githubusercontent.com/17010094/128043529-cc7704dd-56f2-4165-ac02-110a50f0039c.png)
-- | --

-----------
Verification passed on Oppo R5 with Android 11 running 1.28.99 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/9144
- Verified with Adblock set to default(standard)/strict, only one frame is shown
- Verified disabling ad block shows all three iframes
- Verified with shields set to standard/strict, disabling `#brave-adblock-collapse-blocked-elements`, all three iframes are shown

![image](https://user-images.githubusercontent.com/17010094/128042429-6d33459b-0d58-47c9-9627-d53e30e904a6.png) | ![image](https://user-images.githubusercontent.com/17010094/128043452-c6109790-bfeb-43a0-8bf7-13ab275d538e.png)
-- | --
