### ISSUE TITLE
Add notification counter

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1482]
We should show notification counter on BAT logo in the url bar. Data should be retrieved from notifications service https://github.com/brave/brave-core/pull/581.

![image](https://user-images.githubusercontent.com/9574457/46730477-8d1e6c80-cc88-11e8-8d7b-15a9ef0e9338.png)

**Comment by mkarolin** [comment]
@rossmoody, the current implementation of the badge is a bit different from the look in the issue's description (the badge doesn't overlap the icon):

![notifications](https://user-images.githubusercontent.com/41635752/46986194-05879200-d0bc-11e8-9450-bca9fd198efd.jpg)
 
Does this need to change and if so, how?

**Comment by rossmoody** [comment]
That screengrab looks like it might have come from an Android mockup which has differed a bit from the desktop toolbar UI we implemented. This doesn't appear to me to be an issue and there are upcoming adjustments to this section specifically including making the icons bigger in this space which will likely close that gap a bit. Do want to tag @petemill in here though just to make sure that's formatting correctly. I can tell this is Windows but the numbers might be a smidge low.

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

- Verified counter on Notification 
- Issue needs to be verified again once #1619 is fixed
