### ISSUE TITLE
Top-level document blocking modal should not be applied to iframes

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#14826]
The "suspicious site ahead" modal should not be rendered in iframes that are blocked - the "Proceed" and "Go back" buttons do not do anything, and filter lists are not designed to block "potentially useful" frames.

![image](https://user-images.githubusercontent.com/22821309/111705773-9c218580-8817-11eb-9675-d63fa13be257.png)

Eventually, these should be [hidden](https://github.com/brave/brave-browser/issues/14825), but in the meantime it's better to render them with the less-conspicuous "broken document" page that is default in Chromium (and was the behavior before top-level-document blocking was implemented).

**Comment by ryanbr** [comment]
Shouldn't block $third-party either, which could cause a quite a few false positives. (uBO parity)

![third-party](https://user-images.githubusercontent.com/1659004/111867653-53fe9080-89da-11eb-9bb9-84ab2345aaca.png)

`https://t.myvisualiq.net/click_pixel?et=c&ago=212&ao=546&aca=71700000079900483&si=-2&ci=-2&pi=-2&ad=58700006712595232&sv1=92700060738722924&advt=-2&chnl=-2&vndr=1195&sz=6583&u=Cj0KCQjwutaCBhDfARIsAJHWnHsiNkwZDWLZOyZzfYNBG34i_P7ZlsBnTsxbAumgOfkEnqliqLQvgGsaAtiJEALw_wcB&red=https://www.bestbuy.com/site/samsung-27-4-cu-ft-side-by-side-refrigerator-stainless-steel/6397576.p?skuId=6397576&ref=212&loc=1&ref=212&loc=1&gclsrc=ds`

(Changed to $script and $image): https://github.com/easylist/easylist/commit/1da86a19962b573b76fe863030c7f2430fbae9fa

**Comment by antonok-edm** [comment]
@ryanbr I suspect that block is from a different filter; none of the other sites nearby in the list from https://github.com/easylist/easylist/commit/1da86a19962b573b76fe863030c7f2430fbae9fa are causing the same modal.

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.24.47 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1. loaded `https://apps.facebook.com/wordswithfriends` with Shields down
2. loaded `speedtest.net` with Shields down

| facebook.com - fixed | speedtest.net - fixed | facebook.com - before | speedtest.net - before |
|----------|---------|----------|----------|
<img width="1792" alt="Screen Shot 2021-04-05 at 11 02 24 AM" src="https://user-images.githubusercontent.com/387249/113608002-ca1c0d80-95fe-11eb-9edd-5f8d60aff9f3.png"> | <img width="1792" alt="Screen Shot 2021-04-05 at 10 55 16 AM" src="https://user-images.githubusercontent.com/387249/113607419-0864fd00-95fe-11eb-917b-9cc1a3769325.png"> | <img src="https://user-images.githubusercontent.com/387249/113607808-86290880-95fe-11eb-8abd-9a494e8c9ea9.png"> | <img width="1545" alt="Screen Shot 2021-04-05 at 11 03 42 AM" src="https://user-images.githubusercontent.com/387249/113607901-a8228b00-95fe-11eb-8a3f-36488de369d4.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.70 x64 build

Facebook.com | Speetest.net
-- | --
![image](https://user-images.githubusercontent.com/17010094/114702445-fed54680-9d1b-11eb-97a1-6ac7e0da9cd3.png) | ![image](https://user-images.githubusercontent.com/17010094/114703016-af434a80-9d1c-11eb-83c2-14512385b44e.png)

-------
Verification passed on Samsung Tab A with Android 10 running 1.23.70 x64 build

Facebook.com | Speetest.net
-- | --
![image](https://user-images.githubusercontent.com/17010094/114703982-f2ea8400-9d1d-11eb-89c9-bf78f633f5fd.png) | ![image](https://user-images.githubusercontent.com/17010094/114703839-c20a4f00-9d1d-11eb-8d88-1176ba4e33f6.png)
