### ISSUE TITLE
Frequently visited sites lose favicon when switched from favourites

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14828]
## Steps to Reproduce

- Set data to be cleared on exit(maybe not relevant)
- Add some sites to top tiles via frequency
- Switch to manual favourites
- Toptile menu -> Show frequently visited
- Frequent sites Toptiles don't have favicons

## Actual result:

Frequently visited sites lose favicon when switched from favourites

## Expected result:
Favourites/Frequent sites in top tiles should never lose favicons

## Reproduces how often: 

Somewhat Easy

## Brave version (brave://version info)

Brave | 1.23.41 Chromium: 89.0.4389.90 (Official Build) nightly (64-bit)
-- | --
Revision | `62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@stephendonner was able to repro it on his macOS. May have a simpler step to repro
cc: @rebron @bsclifton

**Comment by stephendonner** [comment]
I *could* definitely reproduce this, but haven't-yet figured out the minimal steps to get back into this state, sorry; I'll keep trying!

<img width="1312" alt="Screen Shot 2021-03-17 at 8 51 12 PM" src="https://user-images.githubusercontent.com/387249/112074071-a226a780-8b32-11eb-8e9e-b624743ffb26.png">

When it did happen, for me, I was unable to ever re-populate/refresh the favicons for the particular sites, regardless of directly loading them via the URL bar, or clicking on the Top Site's favicon for them, and/or both methods :-(
