### ISSUE TITLE
Use new Uphold sandbox URL

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#14824]
The new URL should look like `https://wallet-sandbox.uphold.com/...`

The original message from Uphold:

> You are being reached out to as you are an API partner of Uphold and have an authorized Sandbox account.
> This is a friendly notification that if you are testing in the Uphold Sandbox, please make sure to use the new sandbox URL from 
> now on: http://wallet-sandbox.uphold.com/. In particular, this means that the OAuth authorization URL should be changed
> from `https://sandbox.uphold.com/` to `https://wallet-sandbox.uphold.com/`.

Note: Per Uphold, this does not affect the REST API endpoint (`api-sandbox.uphold.com`).

**Comment by emerick** [comment]
I switched over to use the new sandbox URL in a local build, but the "Withdraw Funds" link takes me to a blank page. Uphold is aware of this issue and is working on a fix as of 4/8/21.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.25.19 Chromium: 90.0.4430.72 (Official Build) nightly (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)


Steps:

1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
3. claimed UGP BAT grant
4. verified Uphold wallet and confirmed that this uses the correct URL (https://wallet-sandbox.uphold.com/...)
5. verified that "Add funds" took me to the correct page with the Brave card in the "To" field
6. verified that "Withdraw funds" took me to the correct page with the Brave card in the "From" field
7. verified that visiting the Uphold dashboard worked as expected

example | example | example | example | example | example | example | example | example
---------|---------|----------|----------|---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2021-04-15 at 4 31 33 PM" src="https://user-images.githubusercontent.com/387249/114951063-32da6580-9e09-11eb-961e-a006cb48ffab.png"> | <img width="1312" alt="Screen Shot 2021-04-15 at 4 31 39 PM" src="https://user-images.githubusercontent.com/387249/114951076-3a017380-9e09-11eb-969f-1e70432db0b7.png"> | <img width="1312" alt="Screen Shot 2021-04-15 at 4 31 44 PM" src="https://user-images.githubusercontent.com/387249/114951079-3cfc6400-9e09-11eb-94a7-069823fcd83d.png"> | <img width="1312" alt="Screen Shot 2021-04-15 at 4 32 27 PM" src="https://user-images.githubusercontent.com/387249/114951085-3ec62780-9e09-11eb-93fc-37ab6cb13da0.png"> | <img width="1251" alt="Screen Shot 2021-04-15 at 4 32 59 PM" src="https://user-images.githubusercontent.com/387249/114951091-3ff75480-9e09-11eb-814e-80f54c8748f6.png"> | <img width="1251" alt="Screen Shot 2021-04-15 at 4 33 31 PM" src="https://user-images.githubusercontent.com/387249/114951092-408feb00-9e09-11eb-8f7f-f56f58efb5b9.png"> | <img width="1251" alt="Screen Shot 2021-04-15 at 4 34 32 PM" src="https://user-images.githubusercontent.com/387249/114951095-41c11800-9e09-11eb-9073-d45d309e320e.png"> | <img width="1151" alt="Screen Shot 2021-04-15 at 4 35 53 PM" src="https://user-images.githubusercontent.com/387249/114951101-42f24500-9e09-11eb-990d-55a0c0916fd4.png"> | <img width="1251" alt="Screen Shot 2021-04-15 at 4 35 12 PM" src="https://user-images.githubusercontent.com/387249/114951097-4259ae80-9e09-11eb-8d07-420a1f09509d.png">
