### ISSUE TITLE
Remove patches/chrome-browser-extensions-extension_management.cc.patch

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14820]
## Description 

This patch could be removed in favour of a chromium_src override that would define its own version of `ExtensionManagementFactory::BuildServiceInstanceFor()` to simply return an instance of `BraveExtensionManagement`, instead of patching the original method from upstream (which doesn't do anything much more than returning an instance of `ExtensionManagement`).

## Brave version (brave://version info)

Brave 1.24.2 (Chromium 89.0.4389.90)

## Miscellaneous Information:

This removal references a patch initially introduced with https://github.com/brave/brave-browser/issues/196 but there is no test plan detailed neither there nor in the the associated PR at https://github.com/brave/brave-core/pull/106, so please contact @bbondy for suggestions on how to make sure that things keep working as expected after this removal when doing QA, thanks.

**Comment by mariospr** [comment]
Closing as per review comments in the associated PR

**Comment by stephendonner** [comment]
@bbondy per https://github.com/brave/brave-browser/issues/14820#issue-835131630 do you -- or someone you can tag -- have a workable test plan to share for us?  Thanks in advance!

**Comment by mariospr** [comment]
> @bbondy per [#14820 (comment)](https://github.com/brave/brave-browser/issues/14820#issue-835131630) do you -- or someone you can tag -- have a workable test plan to share for us? Thanks in advance!

Oops! So sorry but this doesn't need testing because in the end the proposed approach in the PR was rejected and nothing got applied. Updating tags to QA/No now...
