### ISSUE TITLE
[hackerone] wayback machine URL encoding

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#14843]
https://hackerone.com/reports/1130619

**Comment by stephendonner** [comment]
Verified PASSED using the testplan from https://github.com/brave/brave-core/pull/8311 on build 

Brave | 1.24.26 Chromium: 90.0.4430.30 (Official Build) nightly (x86_64)
-- | --
Revision | 5674335ff855e43f3bccf8cfc29a779bdf0d067f-refs/branch-heads/4430@{#532}
OS | macOS Version 11.2.3 (Build 20D91)


Steps:

1. Loaded `https://en.wikipedia.org/wiki/1960%E2%80%9361_UE_Lleida_season?&timestamp=20160101`
2. Pressed `Check for saved version` button
3. Checked and verified that `https://web.archive.org/web/20210315191803/https://en.wikipedia.org/wiki/1960%E2%80%9361_UE_Lleida_season` is loaded

<img width="1064" alt="Screen Shot 2021-03-25 at 9 51 09 AM" src="https://user-images.githubusercontent.com/387249/112511931-1db17000-8d50-11eb-910e-1fefa2315416.png">
<img width="1064" alt="Screen Shot 2021-03-25 at 9 52 00 AM" src="https://user-images.githubusercontent.com/387249/112511943-1f7b3380-8d50-11eb-8875-bbecbdd7dc94.png">
<img src="https://user-images.githubusercontent.com/387249/112511948-20ac6080-8d50-11eb-81e9-e3017e3b2ecf.gif">
