### ISSUE TITLE
Log to rewards-internals log whenever user presses "refresh status" 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#14842]
## Description 

Whenever a user presses "refresh status" on a Creator channel (whether verified or unverified), log the request in `brave://rewards-internals` logs. The log should contain, in addition to the usual metadata, the following info: 

- [ ] Exact endpoint URL called out to (presumably PCDN URL)
- [ ] Response from the server (at minimum success/error)
- [ ] If possible: Whether there was any update to the state or properties of the refreshed channel, and if so, which values were updated.

**Comment by diracdeltas** [comment]
@Miyayes just confirming, is logging still disabled unless the user passes a command line flag?

**Comment by zenparsing** [comment]
For background, we originally logged this information and it was removed at some point with the idea that logging would be enabled by default (without a command line argument). We should probably have a discussion about whether we want to eventually enable logging by default or not.

**Comment by Miyayes** [comment]
Yes, logging is still disabled unless a user passes a command line flag as of Mar 24, 2021.

As for this issue, we got to the bottom of why `refresh status` was not working. It was a local caching issue. This was a request to add additional logging to help get to the bottom of that issue, and won't be required anymore!
