### ISSUE TITLE
Disable BAT icon in url bar in private/tor window

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1484]
We need to disable BAT icon in url bat when user is in private or tor window.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified passed via test plan in https://github.com/brave/brave-core/pull/615 - BAT icon is disabled in Guest, Private, and Tor windows.
