### ISSUE TITLE
Rewards panel doesn't list IPFS links fully in panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14841]
## Description 

Rewards panel doens't list IPFS links fully in panel

## Steps to Reproduce

   1. Enable Rewards
   2. Use public gateway for IPFS and visit any IPFS link
   3. Open rewards panel, site name isn't shown fully

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/111798466-ff67f200-88c1-11eb-970f-33f499d44872.png)

## Expected result:
Should show the page name correclty

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)
-- | --
Revision | `62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bbondy

**Comment by emerick** [comment]
I think this goes beyond a display problem. I'm not positive how we want to handle this long-term, but since the current publisher architecture is domain-focused I would suggest for now that we not show anything in the Rewards panel for IPFS links.

cc: @bbondy

**Comment by bbondy** [comment]
Let's go with what @emerick suggested for now please @spylogsster.

So for anything that is IPFS we'd just show this like it does for chrome/brave/about pages:
<img width="377" alt="Screen Shot 2021-04-06 at 3 13 02 PM" src="https://user-images.githubusercontent.com/831718/113765727-a59d5f80-96ea-11eb-8afb-8c45ba135e76.png">

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build 

Brave | 1.25.11 Chromium: 90.0.4430.61 (Official Build) nightly (x86_64)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | macOS Version 11.2.3 (Build 20D91)

Loaded the following:
* `ipfs:QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme`
* `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
* `ipfs://QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Tokyo_National_Museum.html`
* `ipns://brantly.eth`
* `https://wikipedia-on-ipfs.org`

Confirmed the tip UI only shows up for the `https://wikipedia-on-ipfs.org` page; not for any of the `ipfs://` / `ipns://` links.

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="945" alt="Screen Shot 2021-04-12 at 4 28 21 PM" src="https://user-images.githubusercontent.com/387249/114475207-ac294c80-9bac-11eb-934f-c45410338136.png"> | <img width="945" alt="Screen Shot 2021-04-12 at 4 26 17 PM" src="https://user-images.githubusercontent.com/387249/114475209-acc1e300-9bac-11eb-85e6-c28537803a9c.png"> | <img width="945" alt="Screen Shot 2021-04-12 at 4 25 52 PM" src="https://user-images.githubusercontent.com/387249/114475212-acc1e300-9bac-11eb-8126-4d0ad9a08e12.png"> | <img width="945" alt="Screen Shot 2021-04-12 at 4 24 28 PM" src="https://user-images.githubusercontent.com/387249/114475215-ad5a7980-9bac-11eb-8ce1-3bdb9c21603a.png"> |  <img width="945" alt="Screen Shot 2021-04-12 at 4 26 34 PM" src="https://user-images.githubusercontent.com/387249/114475208-ac294c80-9bac-11eb-8cc4-e99c6a9d33ad.png">
