### ISSUE TITLE
[Android] Tab Groups occasionally visible when second to last tab is closed

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#14847]
## Description 
Tab Groups occasionally visible when second to last tab is closed.
![issue](https://user-images.githubusercontent.com/30602739/111841108-d2243f80-88d3-11eb-923b-0bbf2fd6ce68.png)

## Steps to reproduce 

   1. Open 2 tabs in 1 tab group.
   2. Close the second tab.
   3. Occasionally tab groups controls remains visible.

## Actual result 
Occasionally tab groups controls remains visible.

## Expected result
Tab groups controls disappear.

## Issue reproduces how often 
Occasionally

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
Nightly

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.24.76, Chromium 90.0.4430.85` on Android 9, Pixel XL, arm64.

Confirmed after trying multiple times that I never saw the tab-group controls persist, after closing the 2nd tab.

example | example | example
---------|---------|----------
![Screenshot_20210429-161710](https://user-images.githubusercontent.com/387249/116629858-0e04e880-a907-11eb-8bc6-ad537f72780c.png) | ![Screenshot_20210429-161725](https://user-images.githubusercontent.com/387249/116629860-0e9d7f00-a907-11eb-8594-2ac58a5185f9.png) | ![Screenshot_20210429-161645](https://user-images.githubusercontent.com/387249/116629853-09d8cb00-a907-11eb-91ac-16cdbc26f3c2.png)
