### ISSUE TITLE
More visible widgets on new tab page

### ISSUE THREAD

**Issue by SlowNicoFish** [brave/brave-browser#14853]
## Description 

More widgets on the new tab page would be a great addition because it would give a better overview when starting Brave instead of having to scroll trough widgets.
Preferable implementation would be the look of the new tab UI from IOS where the stats shows at the top and top sites below them.

## Actual result 
 
![image](https://user-images.githubusercontent.com/19305293/111890620-56b5b180-89eb-11eb-9cd5-5aba2ed9aab8.png)

## Expected result
Something like this:
![image](https://user-images.githubusercontent.com/19305293/111890623-646b3700-89eb-11eb-96c9-fb7924a099eb.png)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): OnePlus 8T
   - Android version: 11
   
## Brave version
1.22.65

**Comment by fysiks1** [comment]
That is how it used to look but for some reason when they added this widget concept, they made the new tab page nearly useless.  I also had something like 10 sites listed and now I'm only seeing 4 which is a joke.

**Comment by bsclifton** [comment]
cc: @anthonypkeane @jamesmudgett

**Comment by anthonypkeane** [comment]
Hi, we only plan to have one widget space but will work to add more options to that widget space in time. And, we'll also fix the 4 bookmark issue.
