### ISSUE TITLE
Vertical bars shown on % bar graph on autocontribute list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1485]
## Description 

Vertical bars shown on % bar graph on autocontribute list

## Steps to Reproduce

   1. Add 7-8 sites to auto contribute list
   2. Click on show all 
   3. Popup window shows % breakdown. Has White vertical bars on the % bar graph

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46743481-25abf100-cc77-11e8-8a25-db0f5e3fbdcd.png)

## Expected result:
Bar graph should not contain white bars

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

 
Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes
- Does it reproduce on browser-laptop? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Issue reproduced on mac by @LaurenWags

**Comment by GeetaSarvadnya** [comment]
Issue is reproducible on Windows 10

![image](https://user-images.githubusercontent.com/38657976/46756330-d1d7f100-cce4-11e8-8fb3-08bae25f6243.png)

**Comment by NejcZdovc** [comment]
this is by design, so that X is clearly visible as an action
