### ISSUE TITLE
Download [Status Bar] Improvement

### ISSUE THREAD

**Issue by Carandiru0** [brave/brave-browser#14852]
Thank you for your time.

## Description 
When a download is started, visibly the user see's a item popup in the [status bar] area of the canvas. A suggested improvement would be to rethink gui presentation for this particular dated item.
Show the current bitrate (ie. Mbps) as the first item.
Show the end of the url for location as the second item.
Shade the background as to indicate the progress of the file download.
Simple yet effective gui improvement with minimal change. (in regards to code changes needed to support improvement).

## Steps to Reproduce

   1.  MBps
   2.  /thisishowwedoit/filedownload.zip
   3. background shading progressing to right as download continues to complete.
   4. Maybe flash momentarily upon completion.

## Actual result:
Nice color theme, but that's stretching it.

## Expected result:
Modern usability improvement.

## Reproduces how often: 
Every download.

## Brave version (brave://version info)
Latest.

## Version/Channel Information:
All.

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
All Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
N/A.

## Miscellaneous Information:
I think it would be a rewarding improvement and a small change for the developer to implement.

**Comment by srirambv** [comment]
Closing in favour of #1638
