### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#14858]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.24.8  Chromium: 89.0.4389.90
Operating System: Windows NT 10.0.19041

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Launch brave nightly on Win10
2. open NTP and wait less than 1 mins. then crashed
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e0250000-4a4d-0806-0000-000000000000

**Comment by GeetaSarvadnya** [comment]
@simonhong Issue isn't reproducible in `Windows 10 x64 - Nightly build 1.24.8`

**Comment by simonhong** [comment]
@GeetaSarvadnya I also can't repro this with clean profile.
It is possible that my profile is corrupted. I'll reopen when I can see this again.
