### ISSUE TITLE
Dropdown choices for `Method to resolve Unstoppable Domains` are not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14866]
Follow up to https://github.com/brave/brave-browser/issues/14488

## Steps to Reproduce

   1. Run Brave in Polish (PL) locale
   2. Open `brave://settings/extensions`

## Actual result:

Dropdown choices for `Method to resolve Unstoppable Domains` are not translated
Dropdown choices for `Method to resolve Ethereum Name Service (ENS)` are not translated
![image](https://user-images.githubusercontent.com/34715963/111982162-eb620180-8b08-11eb-8c6b-1cc041a4e8d6.png)

## Expected result:
Dropdown choices are translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.22.66 Chromium: 89.0.4389.90 (Official Build) (64-bit)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @yrliou @rebron @mkarolin

**Comment by GeetaSarvadnya** [comment]
@btlechowski dup of #https://github.com/brave/brave-browser/issues/14862
