### ISSUE TITLE
Private tab info has Tor in lowercase

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1486]
## Description 

Private tab info has Tor in lowercase

## Steps to Reproduce

   1. Open a private tab in 0.55.12
   2. Tor is in lowercase (see screenshot below)
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46745185-94d71480-cc7a-11e8-9e52-23a9f817fda0.png)

## Expected result:
Should be similar to b-l 
![image](https://user-images.githubusercontent.com/17010094/46745377-eda6ad00-cc7a-11e8-80ac-7f141dcdc0a3.png)

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Yes on both Dev and Beta
- Does it reproduce on browser-laptop? No 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Not reproducible on Windows 7.
![image](https://user-images.githubusercontent.com/34715963/46745735-f369b600-ccad-11e8-9456-07f9fa6a2ff4.png)

Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7

**Comment by srirambv** [comment]
@btlechowski what about in Private tab?

**Comment by btlechowski** [comment]
Reproduced on Windows 7. Also visible in guest window.

Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/46746737-fa91c380-ccaf-11e8-9f32-6eec2e51ed44.png)

**Comment by tomlowenthal** [comment]
The current new tab pages for these windows are placeholders which we're replacing with whole new designs.

**Comment by tomlowenthal** [comment]
→ #1507
