### ISSUE TITLE
BAT gone

### ISSUE THREAD

**Issue by zioloprime** [brave/brave-browser#14877]
Hello i have'nt used Brave Browser for a long time because of phone swap i had auto contribution disabled now i wanted to take look on my wallet but i was prompted for a update after update all my BAT got auto contributed
![Screenshot_2021-03-22-19-36-29](https://user-images.githubusercontent.com/77926373/112063537-d6fe2300-8b61-11eb-98b5-0435ba23249d.png)
![Screenshot_2021-03-22-19-36-33](https://user-images.githubusercontent.com/77926373/112063540-d82f5000-8b61-11eb-8a67-a11a16754978.png)
![Screenshot_2021-03-22-13-59-20](https://user-images.githubusercontent.com/77926373/112063543-d8c7e680-8b61-11eb-89c9-d3c471484533.png)

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by hollons** [comment]
Hi @zioloprime, thanks for reporting! Can you send me an email at Steven@brave.com with the email linked to your account? 

Thanks in advance!
