### ISSUE TITLE
Command lines don't work on Brave Android

### ISSUE THREAD

**Issue by dreammjow** [brave/brave-browser#14876]
## Description 
Command lines don't work on Brave Android for rooted devices. I haven't tested the non-root method yet

## Steps to reproduce 

   1. Make `chrome-command-line` file  in `/data/local/`
   2. Open `chrome-command-line` with a text editor and add some flags, like: `--enable-features=SplitCacheByNetworkIsolationKey`
   3. Open Brave Browser, go to `brave://version` and there is no `--enable-features=SplitCacheByNetworkIsolationKey` in **Command Line** section

## Actual result 
Starts with `--disable-fre`

![brave](https://user-images.githubusercontent.com/50238852/112050951-47e51100-8b49-11eb-8637-d633d79e6cfb.png)

## Expected result
It should start with `--enable-features=SplitCacheByNetworkIsolationKey` (The screenshot is taken from Bromite).

![bromite](https://user-images.githubusercontent.com/50238852/112050997-52070f80-8b49-11eb-9537-287f299a5c92.png)

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 11 (Rooted)
   
## Brave version
``` 1.24.8 Chromium: 89.0.4389.90 (Official Build) canary ```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Works fine on Chrome

**Comment by srirambv** [comment]
cc: @brave/android

**Comment by AlexeyBarabash** [comment]
This is true, we replaced with handy way for QA team in developer options, this is intended to be used by QA team only. 

Self-built instance of the browser supports this.

Sorry, we will not change that.
