### ISSUE TITLE
Brave Shields icon background is white in Private tabs

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14875]
This is a regression.

## Steps to reproduce 

   1. Clean install
   2. Open Private Tab

## Actual result 
Brave Shields icon background is white
![image](https://user-images.githubusercontent.com/34715963/112041960-431f5d80-8b47-11eb-921f-8f81740c9993.png)
![20210322_180211](https://user-images.githubusercontent.com/34715963/112042141-78c44680-8b47-11eb-8fae-6d9c9cf87516.jpg)
![20210322_180226](https://user-images.githubusercontent.com/34715963/112042288-a3160400-8b47-11eb-88de-19a307bc4513.jpg)

## Expected result
Brave Shields icon background is the same as the rest of the theme

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):Tablet
   - Android version:10
   
## Brave version
Brave v1.22.66 on Samsung Galaxy Tab S5e (Android 10.0)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.22.68 x64 build
![Android Tab Shields](https://user-images.githubusercontent.com/17010094/112295023-65ba8f00-8c8b-11eb-9229-bee9d5613f9a.jpg)
