### ISSUE TITLE
Update URL bar icon flyout text for IPFS local node connections

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#14889]
When an ipfs:// page is loaded (only when we display ipfs:// and ipns:// in the URL bar and have the IPFS icon), then we want to update the flyout under the URL bar icon text as well.

Update this flyout from:
<img width="324" alt="Screen Shot 2021-03-23 at 9 24 54 AM" src="https://user-images.githubusercontent.com/831718/112153433-a2b65100-8bb9-11eb-8f8e-e61419ddac85.png">

To this, but apply the text changes to the new look below:
![image](https://user-images.githubusercontent.com/2388823/112186943-d9429a80-8bbe-11eb-918b-2de2b704fc8d.png)

It's ok to not have the exclamation icon, i.e. keep the same normal styling that is already there for now.

Text changes from the new design:

This content was loaded over the IPFS protocol

InterPlanetary File System (IPFS) is a public network for peer-to-peer data storage and delivery.  You can learn more about Brave's integration or configure your IPFS settings at any time.

Security review: https://github.com/brave/security/issues/384

**Comment by spylogsster** [comment]
Final variant 
![image](https://user-images.githubusercontent.com/2965009/112877481-7b86e480-90cf-11eb-8d19-7b3412f87a05.png)

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.24.47 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)

URLs used were:
* `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
* `ipfs:QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme`
* `ipns://en.wikipedia-on-ipfs.org/wiki/Tokyo_National_Museum.html`
* `ipns://brantly.eth`

| Example | Example | Example | Example | Example | Example | Example | Example |
|---------|-----------|----------|---------|---------|-----------|----------|---------|
<img width="1312" alt="Screen Shot 2021-04-05 at 3 43 49 PM" src="https://user-images.githubusercontent.com/387249/113635676-e8493400-9625-11eb-96c3-69c4928ac83d.png"> | <img width="1312" alt="Screen Shot 2021-04-05 at 3 43 44 PM" src="https://user-images.githubusercontent.com/387249/113635677-e8493400-9625-11eb-9ce3-ca9f9d66213c.png"> | <img width="1312" alt="Screen Shot 2021-04-05 at 3 43 37 PM" src="https://user-images.githubusercontent.com/387249/113635679-e8e1ca80-9625-11eb-84f8-d0a2804bad30.png"> | <img width="1312" alt="Screen Shot 2021-04-05 at 3 43 28 PM" src="https://user-images.githubusercontent.com/387249/113635681-e8e1ca80-9625-11eb-9c41-d5a3f48ac807.png"> | <img width="1312" alt="Screen Shot 2021-04-05 at 3 42 05 PM" src="https://user-images.githubusercontent.com/387249/113635673-e7b09d80-9625-11eb-926e-0e777092d23d.png"> | <img width="1312" alt="Screen Shot 2021-04-05 at 3 43 15 PM" src="https://user-images.githubusercontent.com/387249/113635684-e97a6100-9625-11eb-85e4-ae45a5fdd3b0.png"> | <img width="1312" alt="Screen Shot 2021-04-05 at 3 42 51 PM" src="https://user-images.githubusercontent.com/387249/113635685-e97a6100-9625-11eb-93ee-302003b1c354.png"> | <img width="1312" alt="Screen Shot 2021-04-05 at 3 42 22 PM" src="https://user-images.githubusercontent.com/387249/113635686-ea12f780-9625-11eb-9232-ddd3734af804.png">
