### ISSUE TITLE
Dev tools very slow to open (Beta / Nightly)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#14880]
## Description 
Trying to open the dev tools on Nightly takes a really long time to open on Windows

For example, if you push F12 to open for a page, it takes 28 seconds for this to show on my machine. Loading the contents of the dev tools takes another 5 seconds to load ☹️ 

## Steps to Reproduce
   1. Be on Nightly on Windows
   2. Visit a website
   3. Press F12 or right click => Inspect

## Actual result:
It appears like nothing happens; but if you wait long enough, EVENTUALLY it'll open the tools

## Expected result:
Dev tools should open immediately

## Reproduces how often: 
All the time

## Brave version (brave://version info)

Brave | 1.24.8 Chromium: 89.0.4389.90 (Official Build) nightly (64-bit)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | Windows 10 OS Version 2009 (Build 19042.867)

## Version/Channel Information:
Nightly

- Can you reproduce this issue with the current release? N
- Can you reproduce this issue with the beta channel? N
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? N

**Comment by qngapparat** [comment]
Also happens on Mac: #14721

**Comment by technocapeman** [comment]
As per my experience, this has also happened on the current release v1.22.66 as well.

**Comment by bsclifton** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/14721

**Comment by bsclifton** [comment]
Re-opening to track this problem on Beta / Nightly

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.22.70 Chromium: 89.0.4389.105 (Official Build) (arm64)
Revision	14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS	macOS Version 11.2.3 (Build 20D91)
```

Verified STR from description.
Verified test plan from https://github.com/brave/brave-core/pull/8336#issue-599165037.

Opened dev tools from multiple places:
- keyboard shortcut (cmd+opt+i)
- right click > Inspect
- hamburger menu (More Tools > Developer Tools)
- macOS menu bar (View > Developer > Developer Tools)

Dev tools opened instantly in each of the above cases.

----------------
