### ISSUE TITLE
Fix SwitchToTorProfileIncognitoEnabled browser test

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#14902]
## Description 

Starting with Chromium 91, this test will **crash on dcheck-enabled builds** (e.g. Component, Debug) when attempting to install the `"Trivial Test Extension Not Allow Incognito"` extension while on incognito mode, because of some recent changes in extensions/browser/extension_util.cc , as [part of CL 2651385](https://chromium-review.googlesource.com/c/chromium/src/+/2651385/39/extensions/browser/extension_util.cc), that are causing a `DCHECK` to be hit in `SetCorsOriginAccessListForExtensionHelper()`:
```c++
void SetCorsOriginAccessListForExtensionHelper(
    const std::vector<content::BrowserContext*>& browser_contexts,
    const Extension& extension,
    std::vector<network::mojom::CorsOriginPatternPtr> allow_patterns,
    std::vector<network::mojom::CorsOriginPatternPtr> block_patterns,
    base::OnceClosure closure) {
  auto barrier_closure =
      BarrierClosure(browser_contexts.size(), std::move(closure));
  for (content::BrowserContext* browser_context : browser_contexts) {
    // SetCorsOriginAccessListForExtensionHelper should only affect an incognito
    // profile if the extension is actually allowed to run in an incognito
    // profile (not just by the extension manifest, but also by user
    // preferences).
    if (browser_context->IsOffTheRecord()) {
      // TODO(lukasza): Change to util::IsIncognitoEnabled if possible.  This
      // fails today in All/IncognitoCommandsApiTest.IncognitoMode/0 apparently
      // because ExtensionPrefs::IsIncognitoEnabled return `false` and
      // ExtensionPrefs::SetIsIncognitoEnabled(..., true) is never called.
      DCHECK(IncognitoInfo::IsIncognitoAllowed(&extension));   <------------- THIS CAUSES THE CRASH
    }
    content::CorsOriginPatternSetter::Set(
        browser_context, extension.origin(), mojo::Clone(allow_patterns),
        mojo::Clone(block_patterns), barrier_closure);
  }
}
```
Before [CL 2651385](https://chromium-review.googlesource.com/c/chromium/src/+/2651385), this `DCHECK` already existed but the difference is that `SetCorsOriginAccessListForExtensionHelper()`  did receive one single `BrowserContext*` instead of a list of contexts. And for some reason whatever context got previously passed to this function as a result of installing that `"Trivial Test Extension Not Allow Incognito"` extension, was not an "Off The Record" profile, and thus it didn't crash... but it does crash now.

As suggested by @darkdh , we're disabling the last part of the `TorProfileManagerExtensionTest.SwitchToTorProfileIncognitoEnabled` in the `cr91` for now, and filing this ticket to track down the correct fix for this issue.

## Brave version (brave://version info)

Any Chromium 91 based version of Brave or newer.

**Comment by darkdh** [comment]
Caused by `GetAllRelatedProfiles` from https://chromium-review.googlesource.com/c/chromium/src/+/2651385

**Comment by kjozwiak** [comment]
Removing milestones. Open issues should only be added into milestones if they're `release/blocking`. Once an issue is fixed, it should be closed and moved into the milestone where the PR landed. If an uplift is required, the @brave/uplift-approvers team will move the issue into the appropriate milestone.

**Comment by mariospr** [comment]
Closing as invalid/won't fix as per comment https://github.com/brave/brave-core/pull/8307#discussion_r622445136
