### ISSUE TITLE
Use compile-time vars for rewards Uphold settings

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#14900]
Uphold settings used by `bat-native-ledger` should be specified using compile-time variables.

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.24 (beta)` with the testplan from https://github.com/brave/brave-core/pull/8380


Steps:
1. Started browser with `./Brave\ Browser\ Beta --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
2. Verified wallet and ensured that there were no errors (after enabling Rewards and accepting UGP grant)
3. Ensured that we connected to Uphold's staging server (`https://wallet-sandbox.uphold.com/authorize/...`)
4. Started browser with `./Brave\ Browser\ Beta --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-debug --rewards=staging=false,reconcile-interval=4`
5. Verified wallet and ensured that there were no errors
6. Ensured that we connected to Uphold's production server

example | example | example | example | example | example | example | example | example | example | example
---------|----------|----------|---------|---------|----------|----------|---------|----------|---------|----------
<img width="903" alt="Screen Shot 2021-04-20 at 1 48 15 PM" src="https://user-images.githubusercontent.com/387249/115467035-bddea580-a1e5-11eb-82c1-abb6b06661cd.png"> | <img width="903" alt="Screen Shot 2021-04-20 at 1 48 29 PM" src="https://user-images.githubusercontent.com/387249/115467037-be773c00-a1e5-11eb-8277-6d65afee247f.png"> | <img width="903" alt="Screen Shot 2021-04-20 at 1 48 36 PM" src="https://user-images.githubusercontent.com/387249/115467038-bf0fd280-a1e5-11eb-8a24-c678dcf642e4.png"> | <img width="1361" alt="Screen Shot 2021-04-20 at 1 49 15 PM" src="https://user-images.githubusercontent.com/387249/115467039-bf0fd280-a1e5-11eb-9d6b-20758fdb27f9.png"> | <img width="1361" alt="Screen Shot 2021-04-20 at 1 49 28 PM" src="https://user-images.githubusercontent.com/387249/115467041-bfa86900-a1e5-11eb-9cc5-101ec509d2a0.png"> | <img width="1202" alt="Screen Shot 2021-04-20 at 1 55 29 PM" src="https://user-images.githubusercontent.com/387249/115467042-bfa86900-a1e5-11eb-951a-c6116f741079.png"> | <img width="1361" alt="Screen Shot 2021-04-20 at 1 55 50 PM" src="https://user-images.githubusercontent.com/387249/115467043-bfa86900-a1e5-11eb-9cfc-ca84ea06e5c2.png"> | <img width="1312" alt="Screen Shot 2021-04-20 at 1 58 40 PM" src="https://user-images.githubusercontent.com/387249/115467044-c040ff80-a1e5-11eb-85b2-d1396929bade.png"> | <img width="1312" alt="Screen Shot 2021-04-20 at 2 30 13 PM" src="https://user-images.githubusercontent.com/387249/115467046-c040ff80-a1e5-11eb-80d3-11f80f698e2b.png"> | <img width="1312" alt="Screen Shot 2021-04-20 at 2 30 24 PM" src="https://user-images.githubusercontent.com/387249/115467048-c0d99600-a1e5-11eb-9266-400016806064.png"> | <img width="1312" alt="Screen Shot 2021-04-20 at 2 30 32 PM" src="https://user-images.githubusercontent.com/387249/115467052-c1722c80-a1e5-11eb-926c-73678e53aa1f.png">

**Comment by kjozwiak** [comment]
QA we'll only be able to check the `Staging` case on `Android` as there's no way for us to get a production grant so we can meet the 15 BAT limitation before creating an Uphold account. However, we need to wait till we get the RC uploaded by @SergeyZhukovsky into the BETA program as claiming grants doesn't work when you upload the `aab` via the internal sharing tool. Once we get the new RC, we'll ask @SergeyZhukovsky to upload and should be able to QA this quickly.
