### ISSUE TITLE
New Private Window with TOR doesn't work. Tor doesn't get initialised. Always disconnected.

### ISSUE THREAD

**Issue by anmdotdev** [brave/brave-browser#14901]
## Description 

Tor status is always disconnected. It use to show initialising earlier and get connected, but seems like the initialisation is not getting triggered for some reason. I never see the "Initialising... %" message anymore.

## Steps to Reproduce

   1. Click on New Private Tab with Tor
   2. Tor doesn't initialise

## Actual result:

Tor status is always Disconnected.

<img width="515" alt="Screenshot 2021-03-24 at 12 52 25 AM" src="https://user-images.githubusercontent.com/36692003/112206005-70e5ce80-8c3b-11eb-9fb8-07790f66efdf.png">

## Expected result:
Tor connection should initialise

## Reproduces how often: 
Always reproduced.

## Brave version (brave://version info)

Brave | 1.21.77 Chromium: 89.0.4389.90 (Official Build) (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)
JavaScript | V8 8.9.255.20
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip,WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=AutofillEnableAccountWalletStorage,SafeBrowsingEnhancedProtection,AutofillServerCommunication,TextFragmentAnchor,DirectSockets,SignedExchangeSubresourcePrefetch,NetworkTimeServiceQuerying,LangClientHintHeader,PrivacySettingsRedesign,NotificationTriggers,WebOTP,IdleDetection,SafeBrowsingEnhancedProtectionMessageInInterstitials,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,TabHoverCards --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/anmolmahatpurkar/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations | 7146a73c-3d47f4f4

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes

- Can you reproduce this issue with the beta channel? 
Didn't check

- Can you reproduce this issue with the nightly channel? 
Didn't check

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No

- Does the issue resolve itself when disabling Brave Rewards? 
No

- Is the issue reproducible on the latest version of Chrome? 
NA

## Miscellaneous Information:

It used to work a couple of days ago. Not sure about the exact version where this started happening.

**Comment by darkdh** [comment]
This is fixed in https://github.com/brave/brave-core/pull/8119
cc @kjozwiak @rebron

**Comment by rebron** [comment]
Closing, duping to https://github.com/brave/brave-browser/issues/14461.
@anmdotdev Fix is on the way in 1.23.x coming in release on April 13th. If you have a moment, would you be able to check in `https://brave.com/download-beta/` if the fix is working for you
