### ISSUE TITLE
"Suspicious site ahead" blocked-content warning message appears for ads

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14911]
## Description 
"Suspicious site ahead" blocked-content warning message appears for ads

## Steps to Reproduce

   1. new profile (not necessary, but a good idea, for default settings)
   2. load `https://apps.facebook.com/wordswithfriends`
   3. log in using `Facebook` credentials
   4. wait for page to load
   5. click on the Shields icon in the URL bar and disable Shields

## Actual result:

<img width="1791" alt="Screen Shot 2021-03-23 at 7 39 47 PM" src="https://user-images.githubusercontent.com/387249/112246305-ad033a00-8c0f-11eb-928a-dca994d3aaf9.png">

## Expected result:
<img width="1791" alt="Screen Shot 2021-03-23 at 7 37 54 PM" src="https://user-images.githubusercontent.com/387249/112246370-c6a48180-8c0f-11eb-9538-aa56ded0344b.png">

## Reproduces how often: 
100%

## Brave version (brave://version info)

Reproduces in:

Brave | 1.24.14 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

(and current `beta` and `dev` channels)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc/ @ryanbr @antonok-edm @pes10k (sorry for casting the net wide)

**Comment by antonok-edm** [comment]
cc @pilgrim-brave as well

**Comment by stephendonner** [comment]
Regression range is:

**Broken:**

Brave | 1.23.21 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.3 (Build 20D91)



**Fine:**
Brave | 1.23.20 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.3 (Build 20D91)

**Comment by ryanbr** [comment]
Does hiding this element, adding to the `brave://adblock` make a difference @stephendonner 

```
###zap-300-4
##div[id^="zap-buyNoAds-"]
###wwf-nav_left_native_ads
##.with_native_ads
```

**Comment by stephendonner** [comment]
@ryanbr unforutnately, nope (seems to neither help nor hurt)

<img width="1680" alt="Screen Shot 2021-03-25 at 10 18 22 AM" src="https://user-images.githubusercontent.com/387249/112515459-851cef00-8d53-11eb-8d75-39d9e54e4e1f.png">

**Comment by stephendonner** [comment]
@rebron would you be able to help find an owner for this?  🙏

**Comment by pes10k** [comment]
I believe @antonok-edm and @pilgrim-brave are handling this here: https://github.com/brave/brave-browser/issues/14826

**Comment by rebron** [comment]
@stephendonner Looks like we can just dupe to #14826
