### ISSUE TITLE
[Android] Crash in cardview mode

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#14919]
## Description 
There is a crash in cardview mode

## Steps to reproduce 

   1. close all tabs
   2. open brave.com
   3. open habr.com
   4. exit browser
   5. launch browser
   6. press cardview button
   7. press on the most far tab

## Actual result 
Crash

## Expected result
No crash

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 10` using the following build:

```
1.22.69 CR: 89.0.4389.105
```

**`Note:`** even though this issue didn't originally occur in Tablet's, went through and made sure that opening/dismissing and switching between tabs didn't regress

* ensured that opening new tabs worked without any issues
* ensured that switching between several tabs after initially launching Brave worked without any issues
* ensured that switching between several tabs after restarting Brave several times worked without any issues
* ensured that closing a tab and selecting `Undo` worked without any issues

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline test here; was able to consistently switch between all tabs in and out of cardview, without crashing, using my `Google Pixel XL` on `Android 9` with build: 

```
Brave	1.22.69 Chromium: 89.0.4389.105 (Official Build) (32-bit)
Revision	14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS	Android 9; Pixel XL Build/PQ2A.190305.002
```
