### ISSUE TITLE
Text is squashed

### ISSUE THREAD

**Issue by KarlVogel** [brave/brave-browser#14918]
## Description 
Some sites have a rendering issue where text is overlapped / squashed.

## Steps to Reproduce

   1. open https://cryptowat.ch/charts/KRAKEN:BTC-USD
   2. Select the "Analysis" drop down and enter "MACD"
   3. A chart will be added to the view with the title text of the chart unreadable as it overlaps itself

## Actual result:

![Screenshot from 2021-03-24 11-09-58](https://user-images.githubusercontent.com/4101575/112293944-fa74bb00-8c92-11eb-98ed-2c317a3a72c5.png)

## Expected result:

![Screenshot from 2021-03-24 11-11-54](https://user-images.githubusercontent.com/4101575/112293987-03fe2300-8c93-11eb-9e48-d638c23170eb.png)

## Reproduces how often: 

100% reproducible.

## Brave version (brave://version info)

Brave: 1.22.67 Chromium: 89.0.4389.90 (Official Build) unknown (64-bit)
Revision:  62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS: Linux

Using the version from flatpak:
```
Name                                                Application ID                                                  Version                       Branch             Origin                   Installation
Brave Browser                                       com.brave.Browser                                               1.20.103                      beta               flathub-beta             system
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? Not tried
- Can you reproduce this issue with the nightly channel? Not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not tried/installed

## Miscellaneous Information:

No additional information

**Comment by antonok-edm** [comment]
@KarlVogel this is a fairly common occurrence if you're browsing with the "strict" fingerprinting protection setting in Shields, and is actually expected (the option mentions it may break sites).

Are you seeing this behavior without that setting enabled?

**Comment by KarlVogel** [comment]
@antonok-edm indeed, seems to be caused by the "strict" fingerprint option. Changing it to standard fixes it (and also other sites I was having the problem with, like Google Sheets)

**Comment by antonok-edm** [comment]
Excellent; everything appears to be working as intended then :smile:
