### ISSUE TITLE
google chat crashing when moving standalone app window

### ISSUE THREAD

**Issue by karthik-krishnan** [brave/brave-browser#14924]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.22.67  Chromium: 89.0.4389.90
Operating System: Mac OS X 11.2.3

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. I had a Google Chat standalone app setup.
2. Simply try to move the standalone app window
3. Brave standalone window vanishes and i see a crash message in the Mac System Log like below 
com.apple.xpc.launchd[1] (application.com.brave.Browser.app.chfbpgnooceecdoohagngmjnndbbaeip.74597149.74597158[29739]): Service exited due to SIGABRT

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/40000000-0c88-1106-0000-000000000000

**Comment by rebron** [comment]
cc: @iefremov for prioritization, might be an issue generally with Apps.

**Comment by kjozwiak** [comment]
Crash linked via [BackTrace](https://brave.sp.backtrace.io/p/brave/triage?filters=(_rxid%3D%2240000000-0c88-1106-0000-000000000000%22)&aggregations=((fingerprint%3Bissues%3Binvariants%2Chead)%2C(fingerprint%3Bissues%3Btags%2Chead)%2C(fingerprint%3Bissues%3Bticket%2Chead)%2C(fingerprint%3Bissues%3Bassignee%2Chead)%2C(fingerprint%3Bissues%3Bstate%2Chead)%2C(fingerprint%3Bfirst_seen%2Chead)%2C(callstack%2Chead)%2C(timestamp%2Cbin%2C32)%2C(timestamp%2Crange)%2C(uname.sysname%2Cdistribution%2C3)%2C(ver%2Cmax)%2C(ver%2Cmin)%2C(guid%2Cunique)%2C(classifiers%2Chead))&fingerprint=0000000000000000000000000000000000000000000000000000000000000486&similarity=false):

```
[ 00 ] <name omitted>
[ 01 ] <name omitted>
[ 02 ] LoadLocalState_ChromiumImpl(ChromeFeatureListCreator*, bool)
[ 03 ] LoadLocalState(ChromeFeatureListCreator*, bool)
[ 04 ] ChromeMainDelegate::PostEarlyInitialization(bool)
[ 05 ] content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams&, bool)
[ 06 ] content::ContentMainRunnerImpl::Run(bool)
[ 07 ] content::RunContentProcess(content::ContentMainParams const&, content::ContentMainRunner*)
[ 08 ] content::ContentMain(content::ContentMainParams const&)
[ 09 ] ChromeMain
[ 10 ] main
[ 11 ] 0x7fff20337621
[ 12 ] 0x7fff20337621
```

**Comment by iefremov** [comment]
thanks @karthik-krishnan this is super important, we are working on a fix

**Comment by karthik-krishnan** [comment]
Hi, @rebron Any updates on this issue?  Is there a fix branch? I am happy to test it and report my findings.

**Comment by karthik-krishnan** [comment]
I think I found the pattern.  If I disable the "Automatic Window Snapping" option in BettertouchTool, the problem goes away.

**Comment by iefremov** [comment]
Thanks @karthik-krishnan , the problem turned out to be non-trivial, it is on my list

**Comment by iefremov** [comment]
dupe https://github.com/brave/brave-browser/issues/7205
