### ISSUE TITLE
crash when accessing background tabs

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#14921]
## Description 
Brave crashes when trying to access background (not active, but already opened) tabs. 

Occurs on clean and upgrade profiles. Also, happened on both ARM (Android 5.1) and x86 (Android 6) devices.

## Steps to reproduce 

   1. Clean install 1.22.68
   2. Open several tabs w/ sites (I had 6)
   3. Close and remove from background
   4. Relaunch browser
   5. Tap on tab tray icon and choose a different tab (any tab but active one)

Also reproduces on an upgraded profile.

## Actual result 
Brave crashes (on x86 I get "Unfortunately Brave stopped" message but on ARM Brave just closes w/o message)

## Expected result
Tab opens

## Issue reproduces how often 
 100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? no, 1.21.x, yes with 1.22.x
- Can you reproduce this issue with the current Play Store Beta version? unsure
- Can you reproduce this issue with the current Play Store Nightly version? unsure

## Device details
   - Install type (ARM, x86): both
   - Device type (Phone, Tablet, Phablet): all
   - Android version: Android 5.1 (ARM), Android 6 (x86)
   
## Brave version

1.22.68

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @SergeyZhukovsky @samartnik @brave/legacy_qa

**Comment by samartnik** [comment]
This will be fixed in the context of this issue https://github.com/brave/brave-browser/issues/14919

**Comment by GeetaSarvadnya** [comment]
Not reproduced in `Android Tablet 10  - Brave 1.22.68`

**Comment by kjozwiak** [comment]
Closing as this was merged into `1.22.x` via https://github.com/brave/brave-core/pull/8344. Basically the same issue as https://github.com/brave/brave-browser/issues/14919 and can be verified at the same time.

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.22.69 Bravex86.apk

- Verified STR from description on clean and upgrade profiles
- Confirmed no crash when accessing background tabs
