### ISSUE TITLE
Twitch VODs aren't displaying in Auto Contribute panel correctly

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1492]
## Description 
If you visit a Twitch VOD, it is not being displayed in the Auto Contribute panel correctly. Each VOD is listed individually instead of under one creator.

## Steps to Reproduce

   1. Enable rewards if not already enabled.
   2. Navigate to twitch user video page (I used https://www.twitch.tv/adam13531/videos/all)
   3. Play a video
   4. Wait a bit of time, go back to Rewards page
   5. VOD is listed.
   6. Go back to video
   7. Click on another VOD by same creator.
   8. Wait a bit of time, go back to Rewards page

## Actual result:
VODs are listed individually instead of grouped under one creator as they were on b-l:
![screen shot 2018-10-10 at 2 05 49 pm](https://user-images.githubusercontent.com/28145373/46756489-995cf680-cc95-11e8-903f-bbe2784dfad4.png)

## Expected result:
VODs for same creator should be listed once. So in the above example they should be grouped under something like `adam13531 on Twitch`

## Reproduces how often: 
easy

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes
- Does it reproduce on browser-laptop? no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
reproduced by by @kjozwiak on macOS

**Comment by LaurenWags** [comment]
cc @NejcZdovc not sure if we can get this into 0.55.x. if we don't, I don't know how contributions will go with multiple VODs listed for same creator.

**Comment by srirambv** [comment]
Happens only when it has non-English characters in name 

![image](https://user-images.githubusercontent.com/17010094/46756741-2738e180-cc96-11e8-8c9d-06e1ca4411b0.png)

**Comment by LaurenWags** [comment]
@srirambv were the bottom 3 VODs or live? live streams display as expected.

**Comment by srirambv** [comment]
@LaurenWags yes all the 4 listed ones are live streams. The one with `hanryang1125` is the tab which has the Korean characters.

**Comment by NejcZdovc** [comment]
@srirambv hanryang1125 is vod and not live stream as far as I can tell. Did it switch to vod maybe?

**Comment by srirambv** [comment]
@NejcZdovc sorry my bad. Yes hanryan1125 is a vod.

**Comment by NejcZdovc** [comment]
based on that I already have a fix for this in another PR

**Comment by kjozwiak** [comment]
@srirambv I don't think it's related to non-english characters being in the name... I can reproduce this with a brand new profile using the following VOD:

* https://www.twitch.tv/videos/319210868

The title of the video is `Let us GAME` and the users name is "Ninja" which are all english characters. However, playing the above video still displays the following:

<img width="572" alt="screen shot 2018-10-10 at 2 17 23 pm" src="https://user-images.githubusercontent.com/2602313/46757129-39ffe600-cc97-11e8-85e0-d9c25fd68de2.png">

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified STR in description
* Verified test plan in https://github.com/brave/brave-core/pull/555
