### ISSUE TITLE
Brave://ipfs appears blank

### ISSUE THREAD

**Issue by youssef20031** [brave/brave-browser#14923]
## Description 

after update to 1.22.67 Brave://ipfs now appears blank. Also I have tried reinstalling brave but to no avail
## Steps to Reproduce
I don't know how it happened

## Actual result:

![Screenshot 2021-03-24 160031](https://user-images.githubusercontent.com/43968405/112323120-26576700-8cba-11eb-98f2-5f9ca89430c6.png)

## Expected result:
Normal brave window

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.22.67 Chromium: 89.0.4389.90 (Official Build) (64-bit)
--
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | Windows 10 OS Version 2009 (Build 19042.870)

- Can you reproduce this issue with the current release? 
- yes
- Can you reproduce this issue with the beta channel?  
- N\A
- Can you reproduce this issue with the nightly channel? 
- N\A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  
- NO
- Does the issue resolve itself when disabling Brave Rewards? 
- Unrelated
- Is the issue reproducible on the latest version of Chrome? 
- No

**Comment by bsclifton** [comment]
cc: @yrliou @spylogsster

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/8365 with `nightly` build


Brave | 1.24.34 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1. load `brave://ipfs-internals/`
2. open Developer Tools
3. choose `Application`
4. under `Storage`, `Local Storage`, find `chrome://ipfs-internals`
5. verify there's current data under the `ipfs-data` key
6. context-click and choose `Delete`
7. click away, come back
8. verify that both the key `ipfs-data` and its Value return


| Example | Example | Example |
|----------|---------|-----------|
<img width="1535" alt="Screen Shot 2021-03-30 at 10 43 13 AM" src="https://user-images.githubusercontent.com/387249/113033338-c5121680-9145-11eb-9a76-b00ee99a6900.png"> | <img width="1414" alt="Screen Shot 2021-03-30 at 10 43 28 AM" src="https://user-images.githubusercontent.com/387249/113033355-c8a59d80-9145-11eb-809d-e7bb04cba39f.png"> | <img width="1535" alt="Screen Shot 2021-03-30 at 10 43 37 AM" src="https://user-images.githubusercontent.com/387249/113033345-c6dbda00-9145-11eb-8e93-eb34aab6b9fb.png">
