### ISSUE TITLE
Re-enable rewards-internals logging with sensitive information removed

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#14926]
## Description 

`brave://rewards-internals` logs were disabled in the past for further privacy and security review. Right now, users are being told by support to use a command line flag to enable logging in the browser in order to submit their logs for bug investigation. This is a much heavier ask for users. 

- [ ] Review and remove sensitive or unnecessary information from rewards-internals logs

@tmancey

**Comment by pes10k** [comment]
I'm removing the privacy label here, since this isn't a bug or privacy feature to review.  However, when it's ready for review or similar, feel free to either ping me, or file a security and privacy review and we can review then

**Comment by Miyayes** [comment]
**COMPLETE**

https://github.com/brave/brave-browser/issues/15500

https://github.com/brave/brave-browser/issues/15661
