### ISSUE TITLE
Add ability to Unlink old/unused devices from "slot" OR some form multi device wallet sync

### ISSUE THREAD

**Issue by Nparte777** [brave/brave-browser#14927]
## Description 
Device limit of 4 does really limits user on shifting to new device/system.
Hopping PCs/distros and formatting not being tolerated is not very acceptable since i have been wanting to reformat my harddrive and have to hold off becuase not only i am not which deivcies are using the "slot" to be careful , i also don't know how to unlink the wallet to the browser/instance.
Does future brave sync alllow mitigation of this issue which users are facing? 

## Steps to Reproduce
Hit Device Limit of 4

## Actual result:
As mentioned 5th device BAT won't be credited to uphold.

## Expected result:
Some form of sync BAT sync mechanism or ability to unlink the wallets

## Reproduces how often: 
100%

## Brave version (brave://version info)

1.22.67 Chromium: 89.0.4389.90 (Official Build) (64-bit)

## Version/Channel Information:
V1.22.67 Stable

## Miscellaneous Information:
Only possible workaround seems to be deleteing uphold account everytime limit is "hit" (by manually guessing/counting) and Creating another uphold account
->self tipping which is also flaggable to move to valid "slot" device is also risky

**Comment by enxio27** [comment]
Please clarify as to WHO (Brave or Uphold) has imposed the 4-device limit.

**Comment by elnator** [comment]
This seriously needs to be addressed.  It's a major issue.   It would also be nice if we could choose other exchanges that support BAT instead.  Uphold is awful.  Would much prefer Coinbase.

**Comment by Accenter** [comment]
When I asked uphold support about this, they said I should take it with the brave team. It seema like uphold and brave is blaming each other and bo one is taking responsibility. Can we get a clarification on this matter? Its veen too long with this shit and nothing is happening, very frustrating.

**Comment by Miyayes** [comment]
> Please clarify as to WHO (Brave or Uphold) has imposed the 4-device limit.

Brave imposes the 4-device limit.

**Comment by Miyayes** [comment]
> This seriously needs to be addressed. It's a major issue. It would also be nice if we could choose other exchanges that support BAT instead. Uphold is awful. Would much prefer Coinbase.

You get 4 slots with every custodian. So, with Gemini super close to releasing, you will get another 4 slots with Gemini.

**Comment by drcdev** [comment]
> > This seriously needs to be addressed. It's a major issue. It would also be nice if we could choose other exchanges that support BAT instead. Uphold is awful. Would much prefer Coinbase.
> 
> You get 4 slots with every custodian. So, with Gemini super close to releasing, you will get another 4 slots with Gemini.

This doesn't address the issue though. Many people have several devices and will replace them on an ongoing basis. This will effectively lock everyone out over time and switching custodians to continue earning rewards is highly undesirable.

**Comment by bsclifton** [comment]
The ultimate experience (IMO) would be to have some kind of interface where users can control which ones are "authorized".

Even a basic one like in iTunes which just has an authorize / deauthorize:
![image](https://user-images.githubusercontent.com/4733304/130735441-16352c4a-1804-43ad-b5d6-ab021021493e.png)

@Miyayes as a starting point, what do you think about the ability to deauthorize/authorize wallet. If full, we can propose to the user to kick out the oldest authorization

**Comment by xMovingTargetx** [comment]
> > This seriously needs to be addressed. It's a major issue. It would also be nice if we could choose other exchanges that support BAT instead. Uphold is awful. Would much prefer Coinbase.
> 
> You get 4 slots with every custodian. So, with Gemini super close to releasing, you will get another 4 slots with Gemini.

That is great and all. But Gemini doesn't operate all over the world. I cant use it in Germany. And also, Just throw bats on multiple custodians shouldn't be the solution. People don't want multiple places to manage their stuff. 
The arbitrary device limit has to go. Or we need a way to clear old devices.  This should be fixed. This will get out of control at some point when more and more people are hitting the limits and start complaining.

**Comment by MuffyOne** [comment]
It seems that the 4 device limit is even buggy (probably devices are registered multiple times if something went wrong?) I have only 2 devices linked and I always get back "device limit reached" when I try to add my Android phone. Seeing what is going on in the Brave community I'm not the only one. And now I'm planning to change my laptop and is absurd I cannot disconnect my old one before verifying the new one.

**Comment by vincemarsters** [comment]
Really need this - I long ago hit the Uphold limit and already have 3 devices on my Gemini wallet. Now I need to reinstall this laptop and I am stuck between using the last Gemini slot before Android integration comes along or having another device generating BAT that I cannot send to a custodian.

If I could at least send BAT to another BAT address linked to a Brave install then I would only need a single custodian link.

**Comment by Miyayes** [comment]
Actively working on this. You can track progress here: https://github.com/brave/brave-browser/issues/18572
