### ISSUE TITLE
[FR] Redirect bookmarks button on new tab page to open bookmarks

### ISSUE THREAD

**Issue by DevinCharles** [brave/brave-browser#14949]
# Feature Request

On Android App, latest stable.

Whenever I have a new tab page open, often I want to go to my bookmarks to open one of them. I assumed the bookmarks button on the bottom Toolbar would bring me here, but instead bookmarks the new tab page, something I couldn’t ever see being necessary, or the desired intent, by anyone.

Is it possible to redirect this button to open bookmarks on the new tab page?

**Comment by rebron** [comment]
cc: @SergeyZhukovsky and @anthonypkeane to triage.

**Comment by DevinCharles** [comment]
I assume this could happen [here](https://github.com/brave/brave-core/blob/d6fa69c4e76d460adbb220759fa0ec848866b3ad/android/java/org/chromium/chrome/browser/toolbar/bottom/BookmarksButton.java#L62-L74):

```public void updateBookmarkButton(boolean isBookmarked, boolean editingAllowed) {
        if (isBookmarked) {
            setImageResource(R.drawable.btn_bookmark_fill);
            ApiCompatibilityUtils.setImageTintList(this, AppCompatResources.getColorStateList(getContext(), R.color.blue_mode_tint));
            setContentDescription(getContext().getString(R.string.edit_bookmark));
        } else {
            setImageResource(R.drawable.btn_bookmark);
            ApiCompatibilityUtils.setImageTintList(this, mCurrentTint);
            setContentDescription(
                    getContext().getString(R.string.accessibility_menu_bookmark));
        }
        setEnabled(editingAllowed);
    }```

The only java I know though is the kind I drink in the morning...

**Comment by tortino** [comment]
Hello, I use the current behaviour all the time while browsing, so to me this feature is necessary, and it's one of the reasons I use brave (no other browser can do this). So please don't remove this functionality.

**Comment by DevinCharles** [comment]
@tortino you frequently bookmark the new tab page? I'm really interested in your use case here.

**Comment by tortino** [comment]
I'm not bookmarking the NTP. I'm using the bookmarks button on the bottom toolbar to bookmark every page I'm interested in.
This button is always visible while I browse and I use it all the time.
I probably didn't pay attention and I completely ignored that you were talking specifically of the NTP, sorry.

**Comment by bsclifton** [comment]
Should have been fixed with https://github.com/brave/brave-core/pull/16484 - thanks to @NikharPandya for the report
