### ISSUE TITLE
Rename `Learn More` to `Learn more` to maintain consistency across the browser

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14944]
## Description 

Rename `Learn More` to Learn more` to maintain consistency across the browser

## Steps to Reproduce

   1. Open brave 1.24.25
   2. Navigate to brave://settings/ipfs
   3. Look for 1st IPFS setting which has the `Lean More` link mentioned

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/112423671-1b9fdf00-8d59-11eb-89e9-ebe19e031773.png)

## Expected result:

Should be `Learn more` 
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.24.19 Chromium: 90.0.4430.30 (Official Build) nightly (64-bit)
-- | --
Revision | 5674335ff855e43f3bccf8cfc29a779bdf0d067f-refs/branch-heads/4430@{#532}
OS | Windows 10 OS Version 2004 (Build 19041.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @karenkliu @brave/legacy_qa @rebron

**Comment by Ayushsunny** [comment]
I would like to fix this issue.

**Comment by srirambv** [comment]
@Ayushsunny  this should be easy fix. Please check the below ones and give it a try

https://github.com/brave/brave-core/blob/18ac489ccde11b5e8675d6d6a9c316c890e617c4/app/resources/brave_generated_resources_en-GB.xtb#L177

https://github.com/brave/brave-core/blob/de13afc020baddfaf0ce2b2aecd24fff4d25696f/app/brave_generated_resources.grd#L740

**Comment by gordod26** [comment]
I'll also give it a shot for my first issue if @Ayyushsunny doesn't get to it.

**Comment by Ayushsunny** [comment]
> I'll also give it a shot for my first issue if @Ayyushsunny doesn't get to it.

I am Working on it now.

**Comment by Ayushsunny** [comment]
@srirambv please check it sir if there is any conflict or not with my easy https://github.com/brave/brave-core/pull/8529#issue-614750425

**Comment by Ayushsunny** [comment]
Hello @srirambv Sir, Can you please ask them to review as I've done this time correctly https://github.com/brave/brave-core/pull/8535#issue-615269762

**Comment by srirambv** [comment]
This is fixed by https://github.com/brave/brave-core/pull/8535

**Comment by stephendonner** [comment]
Nice catch, @GeetaSarvadnya, and thanks for the fix, @Ayushsunny!

Verified `FIXED` using 

Brave | 1.25.46 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3 (Build 20E232)

Steps:
1. loaded `brave://settings/ipfs`
2. looked at the `Learn more` text and confirmed spelling/case

<img width="1312" alt="Screen Shot 2021-04-28 at 4 38 01 PM" src="https://user-images.githubusercontent.com/387249/116485529-47beec00-a840-11eb-959a-d2d223c9def8.png">
