### ISSUE TITLE
Disable FLoC in Brave

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#14942]
Currently Brave disables the FLoC component.  However there is other FLoC functionality shipped in Chromium (behind origin trials).  We should disable FLoC completely in Brave, including:

1. FLoC client-side determinations of cohorts
2. Any reporting of FLoC cohort determinations to Google (or otherwise) servers (i.e., the reporting used for k-anonymity cohort protections)
3. FLoC JS methods (i.e. `document.interestCohort`)
4. Any UI related to the FloC permission (i.e., `interest-cohort`)

**Comment by iefremov** [comment]
@pes10k 
can you please provide more details on "Any UI related to the FloC permission (i.e., interest-cohort)" - I haven't spotted any related UIs

**Comment by pes10k** [comment]
Sounds good, if there is no UI, then happy for that part to be a NOOP.

The explainer doc just says there is there will be a new permission, and so the request was to disable any UI (for example, any content setting control) related to that permission.  But if that doesn't exist, then, even easier!

**Comment by kjozwiak** [comment]
Adding this into the `1.25.x` as it landed via https://github.com/brave/brave-core/pull/8468.

**Comment by ElijahLynn** [comment]
For those wondering what FLoC is like I was:
* Federated Learning of Cohorts (FLoC)
* https://github.com/WICG/floc
* https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build 

Brave | 1.25.11 Chromium: 90.0.4430.61 (Official Build) nightly (x86_64)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | macOS Version 11.2.3 (Build 20D91)

Using the steps from https://github.com/brave/brave-core/pull/8468:
1. went to `brave://components` and ensured there's no *Federated Learning of Cohorts* component
<img width="945" alt="Screen Shot 2021-04-12 at 4 09 04 PM" src="https://user-images.githubusercontent.com/387249/114473679-8b132c80-9ba9-11eb-969e-8bdfb8ffb2d8.png">
2. opened the devtools console, typed `document.interestCohort()` and confirmed that I got an error:
<img width="945" alt="Screen Shot 2021-04-12 at 4 07 15 PM" src="https://user-images.githubusercontent.com/387249/114473677-8b132c80-9ba9-11eb-8d6c-c7718d7cc9ec.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.51 x64 Beta build
- Verified test plan from https://github.com/brave/brave-core/pull/8468

<img width=500 src=https://user-images.githubusercontent.com/17010094/117810847-ca3fa680-b257-11eb-834e-64cceab329b7.png> | <img width=1200 src=https://user-images.githubusercontent.com/17010094/117810744-aed49b80-b257-11eb-90bc-79ac1d67d15d.png>
-- | --

------------

Verification passed on Samsung Tab A with Android 10 running 1.25.51 x64 Beta build
- Verified test plan from https://github.com/brave/brave-core/pull/8468

<img width=600 src=https://user-images.githubusercontent.com/17010094/117811977-1ccd9280-b259-11eb-8714-be4e28cba174.png> | ![image](https://user-images.githubusercontent.com/17010094/117811579-9f098700-b258-11eb-892c-ce1732caff2a.png)
-- | --

**Comment by dentistformyeye** [comment]
A yellow warning shows up in the browser console when I go to https://web.archive.org/. I'm not sure whether this means there's still something that could be removed or whether this message is supposed to appear.
`Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.`
If it doesn't appear at first, refreshing the page might make it show up.

On a page archived on the Wayback Machine such as [this](https://web.archive.org/web/20210528213034/https://chromereleases.googleblog.com/), the yellow warning can show up twice.

I'm on Brave version 1.25.68 (Chromium: 91.0.4472.77).

**Comment by pes10k** [comment]
Hi @dentistformyeye , thanks for the comment, but what you're seeing isn't a bug, its as intended.

Brave removes all FLoC support in the browser.  This also removes support for understanding the "disable FLoC" header, which is why you're seeing the message you're seeing in the console.  Or, put differently, since Brave doesn't support FLoC, it also doesn't support the "disable FLoC" command.  So, you can safely disregard this message, knowing that FLoC isn't enabled.

Hope that helps!
