### ISSUE TITLE
Bookmarks screen does not display properly in Sidebar

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#14950]
## Description 
Bookmarks are not being displayed in the sidebar view.

Reported [on Twitter](https://twitter.com/PGriffinFC/status/1375082355417825283).

## Steps to Reproduce
1. Enable Sidebar, if it is not already (brave://flags)
2. Create a few bookmarks
3. Open Bookmarks view from Sidebar

## Actual result:
No bookmarks are displayed.

![image](https://user-images.githubusercontent.com/815158/112494203-d2e42800-8d50-11eb-87fa-956aad90c4db.png)

## Expected result:
Bookmarks should be displayed.

![image](https://user-images.githubusercontent.com/2388823/117051600-94d11100-accb-11eb-944b-2be84d60f446.png)

## Reproduces how often: 
Always.

## Brave version (brave://version info)
1.24.19

**Comment by karenkliu** [comment]
This issue https://github.com/brave/brave-browser/issues/14980 captures some P1 issues for sidebar; it mentions bookmarks.

**Comment by jonathansampson** [comment]
Closing in favor of #14980. Thanks, @karenkliu!

**Comment by simonhong** [comment]
Re-opened to use as a sub issue of https://github.com/brave/brave-browser/issues/14980

**Comment by simonhong** [comment]
It seems chrome.bookmarks extension api doesn't work for bookmarks in sidebar panel.

**Comment by stephendonner** [comment]
## Verified `PASSED` using the inline testplan with build 


Brave | 1.30.24 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 12.0 (Build 21A5294g)

### Steps:
1. new profile
2. launched Brave
3. loaded `brave://flags` and enabled `Sidebar`
4. clicked on the `Bookmarks` icon in the Sidebar
5. tested visually with both `light` and `dark` colors.

Confirmed I saw my loaded bookmarks and folders.


example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2021-08-16 at 5 15 30 PM" src="https://user-images.githubusercontent.com/387249/129645391-30e9e886-fc05-40b9-a27a-0f06c5ef6bc6.png"> | <img width="1770" alt="Screen Shot 2021-08-16 at 5 24 00 PM" src="https://user-images.githubusercontent.com/387249/129645424-210baec7-1fee-4dd1-abc5-e62f9b97dc2c.png"> | <img width="1770" alt="Screen Shot 2021-08-16 at 5 28 03 PM" src="https://user-images.githubusercontent.com/387249/129645432-574a2b8e-da8f-4e31-a069-9a2a2f9ce826.png"> | <img width="1770" alt="Screen Shot 2021-08-16 at 5 29 53 PM" src="https://user-images.githubusercontent.com/387249/129645433-5ac39d8f-9075-4f75-99c6-8d6ea8e4306e.png">



NOTE: just a reminder (as @simonhong notes) that this UI is not yet responsive...

**Comment by tortino** [comment]
sorry but in the screenshots I cannot see the bookmarks, only the folders.
I was expecting to see the bookmarks too in the sidebar.

**Comment by simonhong** [comment]
@tortino You're right. Sidebar shares bookmarks manager page with tab now and it's not responsive design yet.
Due to that reason, sidebar can only show left part of bookmarks manager. It's folder list.
and you can see some page's favicons at the right side of sidebar in the screen shot.
We will handle this issue separately.

**Comment by simonhong** [comment]
This issue is not valid for current sidebar as sidebar uses different bookmarks page.
