### ISSUE TITLE
Allow user to specify speedreader backend

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#14959]
Add a command line switch `--speedreader-backend=[streaming|heuristics]` so that @pes10k and @rebron can give nightly feedback on the separate backends. If not specified, it will default to `streaming`, which preserves the existing behavior of speedreader.

**Comment by pes10k** [comment]
Terrific!  @keur to just make sure i understand correctly, is this right:

- streaming: use the list, and if the list is silent about the URL, wait until the page has loaded and then classify
- heuristics: use the list, and if the list is silent about the URL, buffer the page, classify, and either present the speedreader version, or the standard page

**Comment by keur** [comment]
> * streaming: use the list, and if the list is silent about the URL, wait until the page has loaded and then classify

Streaming uses [this list](https://github.com/brave-experiments/SpeedReader/blob/master/data/SpeedReaderConfig.json). Each domain + path has adblock rules that are used to rewrite the page. This doesn't use classification or the Arc90 algorithm. This is how Speedreader is currently is deployed on nightly and beta with no changes. 

> * heuristics: use the list, and if the list is silent about the URL, buffer the page, classify, and either present the speedreader version, or the standard page

No list. Classify everything, then use Arc90 if the page is classified as readable. https://github.com/brave/brave-core/pull/8349 adds some (very important) missing pieces to our implementation of Arc90. Since the classification can cause a delayed paint, that's why we guard this one behind the flag (for now). I have some ideas for how to get around this, but we can focus on that once we are super happy with the results.

**Comment by pes10k** [comment]
Gotcha, thanks for clarifying.  Could you change the names to something more descriptive then?

Maybe `list`, `classify` (and if there is such an option, `list-and-classify`)?
