### ISSUE TITLE
Windows 10: Brave Wasn't working properly.

### ISSUE THREAD

**Issue by CaptainCrumb999RobloxYT** [brave/brave-browser#14951]
Brave (for some reason) wasn't working properly: All sites said they were unsecure and the page was entirely blank.

Reinstalling the program help the issue, but I think the reason was:

1. Windows 10 is unstable.
    Refer to this Video: https://youtu.be/8dtCc1E3t5M
2. Brave might have been having a problem.

This seems like a bug.

**Comment by rebron** [comment]
Closing. We need more specifics. Also wondering if there's an issue with your clock/date on your OS. That might be causing some of the unsecure pages/notifications that you might be seeing. 

When filing issues, can you use the issue template and add as much detail as possible. 
https://github.com/brave/brave-browser/issues/new/choose

**Comment by CaptainCrumb999RobloxYT** [comment]
I don't think there is an issue with my clock or date on my OS. I synced my Date/Time 3 days ago, but this issue happened yesterday. Also, in that video he said that Windows 7 is more stable than Windows 10. I don't count an OS being unsupported when, well it ends support (for example: E.S.U 3 ends same date as Windows 8.1 EOS) I count it when Not Just security updates are unsupported, but PROGRAMS, too.
