### ISSUE TITLE
can't accept grants due to "statusCode":400,"error":"Bad Request","message":"Invalid request R1"

### ISSUE THREAD

**Issue by doctord919** [brave/brave-browser#14952]
## Description 

No ads

## Steps to Reproduce

   1. uninstall brave & remove"..\AppData\Local\BraveSoftware\Brave-Browser"
   2. install brave & run brave

## Actual result:

req:
GET https://ads-serve.brave.com/v1/confirmation/token/8f343431-8b12-4818-a9af-272350c0ce8b?nonce=5ed48ce2-881d-4be2-a3d4-e321d62125ce HTTP/1.1
Host: ads-serve.brave.com
Connection: keep-alive
Sec-Fetch-Site: none
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

resp:
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Length: 20
Content-Type: application/json; charset=utf-8
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
Date: Thu, 25 Mar 2021 13:45:05 GMT
Via: 1.1 varnish
X-Served-By: cache-ams21065-AMS
X-Cache: MISS
X-Cache-Hits: 0

"Invalid Request R1"

4k-picture
[https://c.radikal.ru/c12/2103/44/89773c21d9ea.jpg](url)

## Expected result:
Users should be able to accept grants without any issues.

## Reproduces how often: 

1. My current system Win10 LTSC 1809 Build 17763.1757 - 100%
2. I remove my work hdd and setup new ssd and install Win10 Pro H2 ... 24 Mar 21 Brave get ads, today(25Mar) Brave get 'Invalid Request R1' - 100%
3. I put the program on my father's laptop and everything is fine so far. - 0%
## Brave version (brave://version info)

Brave | 1.22.67 Chromium: 89.0.4389.90 (Официальная сборка) (64 бит)
-- | --
Версия | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards?n/a 
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

A couple of weeks ago, I noticed that the program stopped receiving ads and the balance stopped changing. On March 24, I checked the internet using fiddler and made sure that it is.

**Comment by bsclifton** [comment]
cc: @tmancey

**Comment by tmancey** [comment]
@doctord919 Can you please visit brave://rewards-internals and email your payment id to tmancey@brave.com (please do not post this payment id here. Thanks

**Comment by tmancey** [comment]
@doctord919 Please try now. Your wallet was flagged and has now been cleared.

**Comment by hihouhou** [comment]
what does this error mean ?

**Comment by tmancey** [comment]
After checking with the server team this was just a server issue. Thanks

**Comment by hihouhou** [comment]
so solved for everybody ? really ?
`  Response Status Code: 400
  Response: "Invalid Request R1"`
I won't be paid because not solved ...

**Comment by tmancey** [comment]
This was an issue for @doctord919 that has been resolved. @hihouhou if you could please reach out to the support team for help with your wallet. Thank you, Terry

**Comment by hihouhou** [comment]
https://community.brave.com/t/not-accumulating-bat-anymore/225137/12?u=hihouhou

**Comment by hihouhou** [comment]
@tmancey, nobody is able to solved my problem so github is the good place, have I to open a new ticket or will you do the job on this one ?

**Comment by doctord919** [comment]
> 
> 
> @tmancey, nobody is able to solved my problem so github is the good place, have I to open a new ticket or will you do the job on this one ?
1)  vpn(proxy) off or use a vpn(proxy) in your country
2) rename "..\AppData\Local\BraveSoftware\Brave-Browser" for ex. "..\AppData\Local\BraveSoftware\Brave-Browser.1"
Check out the new **_Release_** version brave and create new wallet ... If the problem is gone, then everything is fine, rename the directory "..\AppData\Local\BraveSoftware\Brave-Browser" to "..\AppData\Local\BraveSoftware\Brave-Browser.2" and "..\AppData\Local\BraveSoftware\Brave-Browser.1" to "..\AppData\Local\BraveSoftware\Brave-Browser". Run brave and Withdraw the money. Delete "..\AppData\Local\BraveSoftware\Brave-Browser". Rename "..\AppData\Local\BraveSoftware\Brave-Browser.2" to "..\AppData\Local\BraveSoftware\Brave-Browser" and work with the new directory and the new wallet.

**Comment by hihouhou** [comment]
Hello,
is it the Terry's tips ?
Seems weird, it's an issue from  server side.

**Comment by ancho85** [comment]
https://community.brave.com/t/not-accumulating-bat-anymore/225137/23

**Comment by tmancey** [comment]
@ancho85 this issue is closed. Please raise a new issue on the community boards with the required information. Thank you
