### ISSUE TITLE
site : my.lwv.org issue : voter guide search utility does not work

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#1496]
## Description 
When attempting to use the voter guide search utility, the actual results do not show.

## Steps to Reproduce
   1.  Visit https://my.lwv.org/texas/voters-guide
   2.  Enter an address (ex. 10509 Marfa Drive, Austin, TX)
   3.  Choose 'Austin' from the dropdown

## Actual result:
The search utility gives an option to list over 9000 races.

## Expected result:
The language selection dropdown should appear. 
After selecting 'English' the list of races should appear.

## Reproduces how often: 
Constantly

## Brave version (chrome://version info)
0.55.12

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
Yes, but only if shields up.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by ryanbr** [comment]
Site has changed, closing due to age.
