### ISSUE TITLE
tor mode privacy

### ISSUE THREAD

**Issue by av100** [brave/brave-browser#14965]
cant install addons to change timezone and user agent

**Comment by rebron** [comment]
@av100 Can you go to brave://extensions/ and click on the extensions you want to use in private/tor and enable the toggle below? Does that work for you?

![screenshot_2021-03-26_132538](https://user-images.githubusercontent.com/5951041/112670125-bcf06900-8e1d-11eb-8ae0-0bacb715f562.png)

**Comment by av100** [comment]
works afrer update 

but the function of hiding the timezone is better to make the standard TOR mode function
