### ISSUE TITLE
Rewards process still runs even when Rewards isn't in use or enabled

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#14964]
## Description 

It appears that there is no way to stop the Rewards process from running or restarting itself, despite features not being used/disabled. If I disable all rewards features/components, I still see the process running — if I end the process, a couple seconds later it starts a new one.

From @bsclifton, bug appears to be related to `prefs::kEnabled`:

> Basically the bug seems like we shouldn't check the deprecated prefs::kEnabled value - or rather, maybe we should update code to
> 1. set the value as false once everything is turned off
> 2. set the value as true as soon as any one "rewards" item is toggled on 

## Steps to Reproduce

1. Disable Ads (Settings --> Rewards Ads --> )
2. Disable AC (Settings --> Rewards --> Auto-contribute )
3. Hide Rewards icon 
4. Open browser task manager, observe Rewards process running.
5. End the process, wait a few seconds, observe new Rewards process has started.
6. End the process again, close the browser, relaunch and check task manager, observe rewards process still running

## Reproduces how often: 

Always

## Brave version (brave://version info)

`Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (x86_64)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Internal convo:
https://bravesoftware.slack.com/archives/CB0KCRCQN/p1616705380095300

**Comment by bsclifton** [comment]
Should be partially solved with https://github.com/brave/brave-core/pull/8273 😄

**Comment by bsclifton** [comment]
We closed this a while back- let's re-open if there are still specific cases 😄
