### ISSUE TITLE
Add a a button to go to brave://adblock/ in the right click menu and maybe change 'Brave' name.

### ISSUE THREAD

**Issue by HGhostRevisionist88** [brave/brave-browser#14978]
Following brave/brave-core#8156 and #14945

Then I would like to suggest a button in the menu to go to brave://adblock/ page so people who only used the old deprecated adblock feature will be able to access the rules without problem and getting lost because the "clear css" button that was removed.
I know when #8838 happens (if it is still a thing) could make things easier for some people to find where the rules are, it will be more intuitive for sure, because right now adblock page being accessible only through the 'hamburger' menu I know it is not so much for some people.

Also like the title says, maybe a change on the Brave right click menu could also be good, so reflects more it is about the adblock feature instead of being a general "Brave" that can be used for anything, unless there are plans to add more stuff to the menu that have nothing to do with Brave's adblocker, why not rename it to Brave Adblock or Brave Shields if there is more plans to add shield settings to it?

**Comment by bsclifton** [comment]
cc: @rebron @karenkliu

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.24.47 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1. loaded `cnn.com` in a single tab
2. right-clicked on the page, and chose `Brave` -> `Manage custom filters`
3. confirmed I was taken to `brave://adblock/` in a new tab
4. loaded `cnn.com` in a tab; in a 2nd tab, opened `brave://adblock/`
5. switched back to `cnn.com` tab and chose `Brave` -> `Manage custom filters`
6. confirmed I was taken back to the open `brave://adblock` tab
7. loaded `brave://adblock/` in a single tab
8. right-clicked on the page, and chose `Brave` -> `Manage custom filters`
9. confirmed I remained on `brave://adblock` in the current tab

**Comment by kjozwiak** [comment]
Added `QA/Test-All-Platforms` as right click context menu's usually differ between different platforms.
