### ISSUE TITLE
Document windows installers available flags

### ISSUE THREAD

**Issue by jaysonsantos** [brave/brave-browser#14971]
## Description 
I'd like to know what are the possible command-line flags for the installer, I am trying to update an installation recipe for brave on scoop, and the zipped files are not signed so I wanted to use the installers but I cannot find what kind of installer it is and its flags.

## Steps to Reproduce
installer.exe /?
installer.exe /help
won't print anything

## Actual result:
nothing on the command line, the installer keeps going

## Expected result:
information about the install flags

## Brave version (brave://version info)

Brave | 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)
Revision | 14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS | Windows 10 OS Version 2009 (Build 19042.870)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel?  yes

## Miscellaneous Information:
If you just point out what installer framework you are using it should also be ok.
Thanks in advance

**Comment by rebron** [comment]
cc: @mihaiplesa Any help with this one?

**Comment by mihaiplesa** [comment]
@mherrmann is looking into a few related things but there's some info on:
https://github.com/brave/brave-browser/issues/6240
https://github.com/brave/brave-browser/issues/9418

I'll create wiki page to capture.

**Comment by mherrmann** [comment]
A good default assumption is that Brave installers on Windows support the same command line arguments as Chrome's.

**Comment by mihaiplesa** [comment]
Trying to find their docs for that but nothing so far.

**Comment by Brave-Matt** [comment]
@mherrmann is correct. Further, we've listed them on our [Help Center for reference](https://support.brave.com/hc/en-us/articles/360044860011-How-Do-I-Use-Command-Line-Flags-in-Brave-).

**Comment by mihaiplesa** [comment]
@Brave-Matt those ar run-time, not sure we have for install time (options for the installer).

Partly present at https://github.com/google/omaha/blob/master/doc/UsingOmaha.md

**Comment by mherrmann** [comment]
Brave's installers on Windows are [Tagged Meta Installers](https://github.com/google/omaha/blob/master/doc/TaggedMetainstallers.md). Their command-line parsing logic is implemented [here](https://github.com/brave/omaha/blob/cd2499ce23b2f8c532e1c504adf41d3e946780d2/omaha/mi_exe_stub/mi.cc#L212-L221).

**Comment by jaysonsantos** [comment]
Hey there @mherrmann sute thing, this can be closed

**Comment by mherrmann** [comment]
Thank you for me know @jaysonsantos !

**Comment by bsclifton** [comment]
@mherrmann anything we should add to https://github.com/brave/brave-browser/wiki/Brave-omaha?

**Comment by mherrmann** [comment]
@bsclifton @mihaiplesa and I considered the same question. There's nothing that can be added easily. It would require going through Omaha's C++ code, seeing what flags might be there, reading the code to find out what they do and potentially trying it. We decided to leave it at that if @jaysonsantos' questions were answered.
