### ISSUE TITLE
Some message patterns are not correctly replaced on the tip dialog

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#14972]
## Description 

Some message patterns are not being correctly replaced on the tip dialog.

![tip-message-1](https://user-images.githubusercontent.com/5995084/112646715-27090e00-8e1e-11eb-9052-2a909a6df6c3.png)

![tip-message-2](https://user-images.githubusercontent.com/5995084/112646755-30927600-8e1e-11eb-8517-e4fc6361049e.png)

**Comment by GeetaSarvadnya** [comment]
@zenparsing I had drafted the issue partially, I have added the issue which has more info. Hence closing this as dup of https://github.com/brave/brave-browser/issues/14973
