### ISSUE TITLE
CR90 - Currency and User placeholders are empty in Tipping banner

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14973]
## Description 

Currency and User placeholders are empty in Tipping banner

## Steps to Reproduce

   1. Open Brave `1.24.26`
   2. Enable rewards
   3. Open https://vimeo.com/bravelaurenwags
   4. Open the tipping banner
   5. Click on the `Send a tip` button
   6. Open https://twitter.com/bravelaurenwags in a new tab
   7. Click on the inline tip for any of the tweets on twitter
   8. [User] place holder is empty in tipping banner

## Actual result:

[Currency] place holder is empty
![image (12)](https://user-images.githubusercontent.com/38657976/112647697-ca820f00-8e6e-11eb-91f0-9d626009d71b.png)

[User] place holder is empty in tipping banner
![image (13)](https://user-images.githubusercontent.com/38657976/112647722-d077f000-8e6e-11eb-885b-298e247129ce.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.24.26 Chromium: 90.0.4430.30 (Official Build) nightly (64-bit)
-- | --
Revision | 5674335ff855e43f3bccf8cfc29a779bdf0d067f-refs/branch-heads/4430@{#532}
OS | Windows 10 OS Version 2004 (Build 19041.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @zenparsing @emerick

**Comment by GeetaSarvadnya** [comment]
@zenparsing Just curious to know if this issue arising due to CR90?

**Comment by zenparsing** [comment]
@GeetaSarvadnya That's correct - the message patterns were updated in CR90, but we missed one place where we are still expecting the old patterns.

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` build with the inline testplan here, on 

Brave | 1.24.32 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. Opened Brave 1.24.32
2. Enabled rewards (Didn't claim UGP grants)
3. Opened `https://vimeo.com/bravelaurenwags`
4. Opened the tipping banner
5. Clicked on the `Send a tip` button
6. Not enough [[currency]] message is shown

Verified this is now fixed

<img width="1312" alt="Screen Shot 2021-03-29 at 11 24 38 AM" src="https://user-images.githubusercontent.com/387249/112882119-66836480-9081-11eb-9abc-46ade03017c9.png">



7. Opened `https://twitter.com/bravelaurenwags` in a new tab
8. Clicked on the inline tip for any of the tweets on twitter
9. [User] place holder is empty in tipping banner

Verified this is now fixed

<img width="1312" alt="Screen Shot 2021-03-29 at 11 17 35 AM" src="https://user-images.githubusercontent.com/387249/112881820-0260a080-9081-11eb-9be0-b2e3c9488572.png">
