### ISSUE TITLE
Uphold is SCAM why dont use other methods? give alternatives please, uphold sucks.

### ISSUE THREAD

**Issue by skarmiglione** [brave/brave-browser#14984]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by waltercool** [comment]
Making a PR offering options it's better than just whining... do you have any proof about your scam claims?

**Comment by bsclifton** [comment]
@brave/rewards-support can help with any specific problems

Closing ticket as this is not actionable as-is. There will be some other providers available in the future. Stay tuned
