### ISSUE TITLE
Little Blue Tick Not Present Alongside BAT Icon - Linux Mint 19.3

### ISSUE THREAD

**Issue by wavesurf432** [brave/brave-browser#14986]
## Description 
Hello there - writing this in regards to the BAT/Brave Rewards icon to the right of the Brave Shields icon. 

The little blue tick that indicates if someone is verified with Brave Rewards hasn't been present on/beside the BAT icon for many months now (at least 3-6 months). To check if someone is verified you have to manually click the rewards icon; and If the person is verified, the blue tick usually appears as normal after refreshing the page. 

The original behaviour reappears after closing Brave.

## Steps to Reproduce

   1. Open Brave in Linux Mint 19.3
   2. Visit a website or channel that's verified with Brave Rewards.
  

## Actual result:

The Brave Rewards icon doesn't display the little blue tick when viewing a verified website/channel e.t.c.

## Expected result:
The Brave Rewards icon displays the little blue tick when viewing a verified website/channel e.t.c.

## Reproduces how often: 

Everytime.

## Brave version (brave://version info)

Brave | 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)
-- | --
Revision | 14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes.
- Can you reproduce this issue with the beta channel? 
- Don't know.
- Can you reproduce this issue with the nightly channel? 
- Don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No.
- Does the issue resolve itself when disabling Brave Rewards? 
- No.
- Is the issue reproducible on the latest version of Chrome? 
- Don't know.

## Miscellaneous Information:

OS: Linux Mint 19.3 (Cinnamon 4.4.8)

I can't remember exactly when I first noticed the issue, but I'm fairly sure it's been happening for atleast 3-6 months.

**Comment by wavesurf432** [comment]
Hello again, 

I just noticed this behaviour only happens when Brave Rewards is enabled, and Auto-contribute is disabled. With auto-contribute enabled the issue resolves itself. It would be nice if this same behaviour happened with auto-contribute disabled. 

For example there could be a website/person that you'd like to tip, but they aren't currently verified with Brave. With the current behaviour you have to click the BAT icon everytime you're on their website/channel to check; it would be a lot nicer to simply just glance at the BAT icon to check if they've verified since your last visit to their website/channel e.t.c.

This behaviour would help people who don't use auto-contribute, but do use the tip feature.

**Comment by Miyayes** [comment]
This sounds like this issue https://github.com/brave/brave-browser/issues/19650? Will close this out in favor of that issue, and also add your comment (which is very helpful investigation) into that issue.

**Comment by wavesurf432** [comment]
Little blue tick is now showing with Brave Rewards enabled, and Auto-Contribute disabled.

Thanks!
