### ISSUE TITLE
Images in fb posts are not clearly visible until zoomed in

### ISSUE THREAD

**Issue by newuser-web** [brave/brave-browser#14982]
## Description 
In other browser like Duckduckgo browser Facebook website is showing maximised images. But in brave images are not clearly visible until you click on it.

## Steps to reproduce 

   1.  Use facebook website in Duckduck go browser and in brave browser. You will notice the difference. In duckduckgo browser visibility is better.
   2. Or use brave version 1.20.x 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version: 10
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

This issue got automatically resolved in brave version 1.20.x but after 1.21.x update it is impacting the facebook website browsing experience again.

**Comment by newuser-web** [comment]
![IMG_201](https://user-images.githubusercontent.com/67158882/112712645-e3ce9e00-8ef6-11eb-9611-10bfac5e4489.jpg)
![IMG_20](https://user-images.githubusercontent.com/67158882/112712649-e7622500-8ef6-11eb-97d5-08eb1257d7cc.jpg)

**Comment by newuser-web** [comment]
Is it going to take time? In 1.20.x it got resolved.

**Comment by newuser-web** [comment]
Website visibility was better in version 1.20.x. Have a look @SergeyZhukovsky

**Comment by newuser-web** [comment]
This issue has been resolved after 1.23.74 update. Are you already working on this? @srirambv

**Comment by newuser-web** [comment]
Images are clearly visible after 1.23.74 update. Are you working on it? @srirambv

**Comment by newuser-web** [comment]
@srirambv Images are clearly visible after 1.23.74 update. Is your team working on it?

**Comment by srirambv** [comment]
cc: @anthonypkeane to proritize

**Comment by anthonypkeane** [comment]
This is related to the images that were used and not an issue with the app.

**Comment by newuser-web** [comment]
Issue is with the brave browser. Not having any problem on any other browser. Even on some older version of brave visibility is better. I have added the screenshot of the same post on two different versions of brave.
