### ISSUE TITLE
[hackerone] wayback machine callback

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#14991]
https://hackerone.com/reports/1139284

cc: @diracdeltas

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan in https://github.com/brave/brave-core/pull/8376 on build 

Brave | 1.24.53 Chromium: 90.0.4430.51 (Official Build) nightly (x86_64)
-- | --
Revision | 32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}
OS | macOS Version 11.2.3 (Build 20D91)

![wayback](https://user-images.githubusercontent.com/387249/113922892-b73f3f80-979c-11eb-8f91-5cc05db5ea15.gif)


(Verified I *could* reproduce the problem on 

Brave | 1.23.66 Chromium: 89.0.4389.114 (Official Build) beta (x86_64)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | macOS Version 11.2.3 (Build 20D91))

![wayback-beta](https://user-images.githubusercontent.com/387249/113922992-da69ef00-979c-11eb-92df-fbb60bca51cc.gif)
