### ISSUE TITLE
A lot of token issues and ads issues

### ISSUE THREAD

**Issue by LorisTecnology** [brave/brave-browser#14990]
## Description 
I didn’t recevied my tokens from March
I’ve updated and already done al the good stuff the Brave members have suggested but still no tokens
Not to mention i don’t recieve anymore tokens even though i recieve ads

i have a verifed account and the latest version

what should i do?

## Brave version (brave://version info)
1.22.70 Chromium: 89.0.4389.105 (Build ufficiale) (a 64 bit)

**Comment by hollons** [comment]
Hi @LorisTecnology, thanks for reporting here. Please see my reply to your DM on Community. Thank you.
