### ISSUE TITLE
Remove `CW` and `IPFS` settings from the Guest window settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14998]
## Description 

CW and IPFS settings can't be enabled or access from the Guest window  hence remove `CW` and `IPFS` settings from the Guest window settings
## Steps to Reproduce

NA

## Actual result:

![image (17)](https://user-images.githubusercontent.com/38657976/112834649-ddd2eb80-90b5-11eb-968a-6cf086932914.png)

## Expected result:

Remove `CW` and `IPFS` settings from the Guest window settings
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.24.29 Chromium: 90.0.4430.41 (Official Build) nightly (64-bit)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | Windows 10 OS Version 2004 (Build 19041.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bbondy 

Please refer slack thread for additional details https://bravesoftware.slack.com/archives/C7VLGSR55/p1617014853246400

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.24.53 Chromium: 90.0.4430.51 (Official Build) nightly (x86_64)
-- | --
Revision | 32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}
OS | macOS Version 11.2.3 (Build 20D91)

Steps to verify:
1. from a regular tab/window, clicked on hamburger menu
2. clicked on `Open Guest Window` option
3. opened `brave://settings`
4. scrolled down

Confirmed there are no `IPFS` nor `Crypto Wallet` settings panels present in `Guest Window` mode.

<img width="1424" alt="Screen Shot 2021-04-07 at 1 03 56 PM" src="https://user-images.githubusercontent.com/387249/113927459-5f0b3c00-97a2-11eb-879d-97bf1a192d3c.png">
