### ISSUE TITLE
Click on Brave Rewards is causing the brave crash in the Guest window

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14995]
## Description 

Click on Brave Rewards is causing the brave crash in the Guest window

## Steps to Reproduce

   1. Open 1.24.x or 1.22.x
   2. Open a Guest window
   3. Click on settings (from the hamburger menu in the Guest window)
   4. Click on `Brave Rewards` header
   5. Brave crashes

## Actual result:

Brave Crash
![Brave Rewards header_Brave crash](https://user-images.githubusercontent.com/38657976/112828651-a102f680-90ad-11eb-9c04-c67943afda11.gif)

**1.22.x**

Uploaded Crash Report ID: | 9a280000-0c88-1106-0000-000000000000
-- | --
Upload Time: | Monday, March 29, 2021 at 3:09:43 PM

**1.24.x**

Uploaded Crash Report ID: | a3280000-0c88-1106-0000-000000000000
-- | --
Upload Time: | Monday, March 29, 2021 at 3:17:10 PM

## Expected result:
No crash

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.24.29 Chromium: 90.0.4430.41 (Official Build) nightly (64-bit)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | Windows 10 OS Version 2004 (Build 19041.867)

Brave | 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)
-- | --
Revision | 14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS | Windows 10 OS Version 2004 (Build 19041.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @iccub @emerick @rebron @zenparsing

**Comment by emerick** [comment]
Haven't been able to repro yet. Backtrace indicates that it's crashing with `EXCEPTION_ACCESS_VIOLATION_READ` when calling the following in `BraveRewardsPageUI::BraveRewardsPageUI`:

```
handler->Init();
```

**Comment by emerick** [comment]
OK, so we're dying in `RewardsDOMHandler::Init` because `brave_rewards::RewardsServiceFactory::GetForProfile(profile)` returns a `nullptr` for a guest page. But that's supposed to happen because Rewards isn't supported in guest pages.

The deeper question here is why the settings page is opening within a guest page. I thought it would redirect to a regular profile and open there. That's how this works in Chrome.

**Comment by LaurenWags** [comment]
Updated issue labels/milestone per discussion with @emerick 👍🏻
