### ISSUE TITLE
site : theatlantic.com issue : page errors due to redirects

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#1499]
## Description 
Visiting theatlantic.com directly works, but visiting via an external link does not.

## Steps to Reproduce
   1.  Vist https://news.ycombinator.com/item?id=18186458
   2.  Click on the link to the article

## Actual result:
The page does not load and displays an error message.

## Expected result:
The page should load.

## Reproduces how often: 
Constantly

## Brave version (chrome://version info)
0.55.12

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by Brave-Matt** [comment]
+1 from Community https://github.com/brave/brave-browser/issues/1499
Issue isn't specific to any one site I don't think. Here's a list of additional sites I've seen this behavior reported on (will add to this as I find them):

- [ ] atlantic.com
- [ ] twitter.com
- [ ] gmail.com

**Comment by ryanbr** [comment]
@alexwykoff Seems to be okay now, if you can confirm?

**Comment by ryanbr** [comment]
Closing, Site has changed. no longer applicable.
