### ISSUE TITLE
Possible to unbookmark same topsite's tile more than once

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1500]
## Steps to Reproduce

1. Go to youtube.com and make sure that it was added to topsite's tiles (repeat if needed) in new tab
2. Go to https://www.youtube.com and bookmark the page
3. Go to https://www.youtube.com/watch?v=wJUTAsJvhb4 and bookmark the page
4. Open a new tab
5. Keep unbookmarking youtube.com tile till it is marked as not bookmarked

## Actual result:

All bookmarks sharing the same domain will be deleted one by one.
https://www.youtube.com bookmark is deleted
https://www.youtube.com/watch?v=wJUTAsJvhb4 bookmark is deleted

![tile_fail](https://user-images.githubusercontent.com/34715963/46760826-5faae080-ccd3-11e8-8080-5d59a96219e4.gif)

## Expected result:
Only https://www.youtube.com bookmark is deleted.

## Reproduces how often: 

always

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7

cc @GeetaSarvadnya @kjozwiak @srirambv @LaurenWags @cezaraugusto @bsclifton 

Found when testing https://github.com/brave/brave-browser/issues/558

**Comment by bsclifton** [comment]
Closing - bookmarking was removed from NTP tiles
