### ISSUE TITLE
Android referrals not initializing correctly

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#15009]
## Description 

Referrals is not initializing on Android release. Some devices are returning a network changed error when talking to the laptop updates server. Also in https://github.com/brave/brave-core/pull/8274 the timestamp persisting logic is not correct on Android messing with confirmations.

## Steps to reproduce 

   1. Get a clean build of brave from a referral link (from a whitelisted referrer)
   2.  Open the browser
   3. navigate to `brave://local-state`

## Actual result 

There is no `download_id`

## Expected result

There should be a `download_id`.

## Issue reproduces how often 
Often on Android devices, always reproduces on the Android Simulator.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
Y
- Can you reproduce this issue with the current Play Store Beta version?
Y
- Can you reproduce this issue with the current Play Store Nightly version?
Y

### Test Plan

Go through the regular referral flow on Android, including confirmation.

**Comment by kjozwiak** [comment]
Labeling as `QA/No` as verifications will be completed via https://github.com/brave/brave-browser/issues/15034 which is basically the same issue as per @keur.
