### ISSUE TITLE
Users are unable to interact with Rewards panel/verify buttons

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#15002]
## Description 

Users in NY are unable to verify their wallets with Uphold, however, they should still be able to interact with the Rewards panel buttons. I am seeing reports of users in NY who are confused because these buttons are unresponsive for them. The only common denominator between all of them is that they are all located in NY. The issue appears to be on our end (UI).

## Steps to Reproduce

   1. Live in NY
   2. Attempt to verify and/or use Rewards panel buttons

## Actual result:

Nothing happens.

## Expected result:
I believe they should be taken to a promo page of some kind (since they're not and can't KYC given state restrictions).

## Reproduces how often: 

Always.

## Brave version (brave://version info)

`Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (x86_64)`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Threads:
https://community.brave.com/t/problem-with-verify-wallet-button/220057/13
https://community.brave.com/t/nothing-happens-after-clicking-on-buttons-under-rewards-settings/185490

**Comment by Brave-Matt** [comment]
This may also not be specific to NY users -- have some additional reports coming in on Community:
https://community.brave.com/t/brave-verify-wallet-withdraw-funds-links-not-working/217418/7

**Comment by Brave-Matt** [comment]
More users are now reporting this -- can we get some extra eyes here?
cc @Miyayes @rebron @jenn-rhim

**Comment by Miyayes** [comment]
When users encounter this, ask users if they see any errors in the JS console (right click > inspect).

**Comment by Miyayes** [comment]
This issue can be reproduced when no Rewards wallet has been created yet. Users can check this in brave://rewards-internals. It will say "Wallet was not yet created". No clear errors in the JS console upon clicking the "Verify wallet" button.

![image](https://user-images.githubusercontent.com/11497541/113876950-3b39fd00-9786-11eb-8a53-f7752049348f.png)

Are there cases where this occurs when a wallet _does_ exist?

**Comment by ErraticallyRndm** [comment]
Using the link above (brave://rewards-internals) I do indeed get the message stating that 'Wallet was not yet created'. It then goes on to list my BAT tokens that I've accrued over the last year.

Presumably I should have a wallet if I have BAT tokens?

**Comment by Miyayes** [comment]
> Using the link above (brave://rewards-internals) I do indeed get the message stating that 'Wallet was not yet created'. It then goes on to list my BAT tokens that I've accrued over the last year.
> 
> Presumably I should have a wallet if I have BAT tokens?

I think it could be https://github.com/brave/brave-browser/issues/15214. That is, it can't decrypt your wallet, so it might be thinking "wallet not yet generated". 

Are you on MacOS? If you are, then you'll need to allow / type in your password to allow the OS keychain/encryption. On Windows, I'm not sure what the equivalent is.

**Comment by wqu1995** [comment]
@Miyayes 
I'm the author who posted this [thread](https://community.brave.com/t/problem-with-verify-wallet-button/220057/13).
No error was reported in the console when I click any of the reward panel buttons. 
Also, when checking with rewards-internals, I do see wallet info and balance info(assuming they are valid), but external wallet info reports with "No wallet"

**Comment by jhib175** [comment]
I have a similar experience to wqu1995 above.

In the JS console, it looks like the only error/warning on my rewards settings page is this:

“polymer_bundled.min.js:1 Could not find style data in module named br-shared-style
stylesFromModule @ polymer_bundled.min.js:1”

Also, checking my wallet info through brave://rewards-internals shows
“Key info seed: Valid” as well as a wallet payment ID and a 12/2018 creation date.
Then it shows the current rewards balance data.
Then
“External wallet info
Wallet status: No wallet”

**Comment by Miyayes** [comment]
@wqu1995 I strongly recommend taking a look at this issue I filed here: https://github.com/brave/brave-browser/issues/15214 @jhib175

**Comment by wqu1995** [comment]
I think the Windows equivalent of OS keychain is Credential Manager, but I'm not sure how I can grant permission to Brave using it. Also, how can I access the reward log you mentioned in #15214 ? If you are talking about the logs tab in reward-internals, I'm not seeing anything there and the "Download full log" button doesn't do anything.

**Comment by iamcraigsnedeker** [comment]
I've been having this problem for quite some time now; I've never been able to transfer BAT to uphold for as long as I've had Brave. I've attached the errors that the inspector pulled. 

On the brave://rewards-internals page, I have **_Wallet status: No wallet_**. I do have an uphold wallet, which is connected to Brave on Uphold's end, but I can't connect it on Brave's end. 

![shot_210510_170108](https://user-images.githubusercontent.com/62191490/117724449-c1949500-b1b1-11eb-9baa-2aba4fd3bb8c.png)

**Comment by Miyayes** [comment]
> I've been having this problem for quite some time now; I've never been able to transfer BAT to uphold for as long as I've had Brave. I've attached the errors that the inspector pulled.
> 
> On the brave://rewards-internals page, I have **_Wallet status: No wallet_**. I do have an uphold wallet, which is connected to Brave on Uphold's end, but I can't connect it on Brave's end. @iamcraigsnedeker 

See this issue: https://github.com/brave/brave-browser/issues/15214

**Comment by Miyayes** [comment]
Not related to users being in NY. From what we understand, this is due to wallet decryption issues, which will be resolved as of 1.31 and forward. User should be able to interact so long as they can see a wallet payment ID in brave://rewards-internals.
