### ISSUE TITLE
Disable sharing-qr-code-generator feature.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#15008]
Per @rebron, this feature should be disabled by default in Brave.

Steps to reproduce:

1. Start Brave browser
2. Navigate to any website (e.g. brave.com)
3. Click inside the location bar
4. An action icon shows up in the location bar. When clicked a bubble with QR code shows up.
![image](https://user-images.githubusercontent.com/41635752/112907369-b7b04a00-90bb-11eb-99a9-278a4477bbc4.png)

Expected behavior:
* No action icon shows up in the step 4 above.

**Comment by rodrigoswz** [comment]
Why? This is a great chromium feature

**Comment by dentistformyeye** [comment]
@rodrigoswz I don't know about specific privacy/security problems, but the feature is unnecessary. If you use [DuckDuckGo](https://duckduckgo.com/), search for ```qr <paste URL here>```: [example](https://duckduckgo.com/?q=qr%20https://github.com/brave/brave-browser/issues/15008).

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.23.66 Chromium: 89.0.4389.114 (Official Build) beta (x86_64)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | macOS Version 11.2.3 (Build 20D91)

Verified using the inline testplan here that there is no longer a QR-code generator icon in the URL bar, upon focus/click.

**Comment by siltentassasin** [comment]
Why removing this feature, I see no disadvantages ... I found this feature realy comfortable

**Comment by NathanaelA** [comment]
@rebron @mkarolin  - Can you give a good or security reason to actually remove this feature?

**Comment by rodrigoswz** [comment]
I would also like to know, does this use Google servers or anything similar to generate qrcodes?

I used it a lot, now I will have to look for some extension (or use the DuckDuckGo flag mentioned above).

Which doesn't make sense for me since it was something native to Chromium...

**Comment by rebron** [comment]
If you'd like to add this function into the url bar, you can do it here: brave://flags/#sharing-qr-code-generator
This type of feature is why we built extensions into the browser, to allow whatever feature user's want while doing our best to maintain some UI/UE discipline to appeal to the majority of our users.

With that said, we can evaluate whether to surface/highlight this feature makes sense down the road and evaluate its current placement/prominence. For the time being, the flag or an extension are your workarounds.

@rodrigoswz FLoC is also native to Chromium and we removed that as a recent example items we remove/neutralize.

**Comment by NathanaelA** [comment]
@rebron - Thanks, I've had the QR flag active since it was a early field test, and it still wasn't showing up -- which is why I started digging into what happened it.   Do you know if a recent update recently fixed the flag to work again, because it is showing in my URL bar now (Yay!) and it wasn't 6 days ago...

**Comment by bsclifton** [comment]
Opened up a security/privacy review so we can evaluate this - thanks for your patience and feedback all 😄 If that looks clean, we can re-enable. There is still a branding issue - but @jonathansampson has a potential fix we can do for the dino that shows up

**Comment by bsclifton** [comment]
OK folks - our next Nightly will have this feature re-enabled 😄 (merged with https://github.com/brave/brave-core/pull/8825)

Next step would be to "Bravify" it if we get the chance 😛 The dino isn't all that bad though

**Comment by soodmax** [comment]
I still do not see this feature in brave. Is this now enabled? It was really useful. How do I get it in brave now?

**Comment by stephendonner** [comment]
> I still do not see this feature in brave. Is this now enabled? It was really useful. How do I get it in brave now?

@soodmax it can be found in the `nightly` build, available here: https://brave.com/download-nightly/

**Comment by Amariithynar** [comment]
How in the everloving crap do I re-disable this annoying function?

**Comment by rodrigoswz** [comment]
> How in the everloving crap do I re-disable this annoying function? 

Seriously? What's the problem with just not using it?

If you don't click on this little icon, you'll never know it exists.

**Comment by Amariithynar** [comment]
> > How in the everloving crap do I re-disable this annoying function?
> 
> Seriously? What's the problem with just not using it?
> 
> If you don't click on this little icon, you'll never know it exists.

I don't care about the icon in the URL bar that much; however, having it shoved in my face in the right-click context menu every single time, moreover with it having its own separate section to even further bloat it? THAT I have serious issue with. 
Shown ![here](https://user-images.githubusercontent.com/22435375/123681018-e7800280-d80e-11eb-96d3-e6c6af690bba.png) with no extensions; with extensions, especially those used frequently like Form History Control or UBlock element blocker or such, it gets much worse.

It may not seem like much to you, but it's a fair amount of space that I now have to accomodate with every right-click context menu usage, and even moreso it's extra space that forces the menu to open upwards further away from the bottom of the screen than before.

**Comment by NathanaelA** [comment]
@Amariithynar - Not sure why it has a right mouse context, can't say I've ever noticed it.  But I can understand your annoyance with it.    I don't use the context menu as often.  

I would open a new bug report for either removing the option in the context menu, or adding a new setting to enable/disable it in whole as the `flags` option seems to be gone now...    If you know programming, then adding a PR to remove the context option would probably be fastest method to get back to your "normal".

**Comment by Amariithynar** [comment]
@NathanaelA I'm not a programmer myself, unfortunately, and know nothing about fiddling with the context menu at all, either. I'll try opening a new issue referencing this one.
