### ISSUE TITLE
Add Custom Tipping Amount feature (Phase 1)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15006]
## Description

Custom tipping amounts allows users to manually specify how much they would like to tip a Creator. The custom tipping amount option will be in addition to the default suggested tipping amounts. 

Please refer to full feature specification.

**Comment by LaurenWags** [comment]
@zenparsing @Miyayes is there a spec and test plan for this issue? marking as `QA/Blocked` until this is sorted.

**Comment by Miyayes** [comment]
Shared spec with the team. Let me know if anything else is needed!

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.25.60 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

```

**Comment by srirambv** [comment]
@deeppandya  if am not wrong this is not yet available on Android. Can we have a new issue created for Android and remove the label from this one?

**Comment by srirambv** [comment]
Follow up  issue https://github.com/brave/brave-browser/issues/16021 logged for Android and removing label from this one
