### ISSUE TITLE
Option to allow localhost connections to a site

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#15004]
## Description 
We're blocking 127.0.0.1 by default via shields, some sites need access to localhost/127.0.0.1 to work correctly, we should have an easy option to allow a user to enable this.

## Steps to Reproduce

   1. Example of a request. https://community.brave.com/t/specific-filter-whitelist-application/223212
   2. Fix to allow `@@||127.0.0.1^$domain=crust.network` as a work around

## Reproduces how often: 
Localhost blocked here: https://github.com/brave/adblock-lists/blob/master/brave-lists/brave-specific.txt

Some sites need access to localhost/127.0.0.1, we should have an option to allow a user to enable this

## Desktop Brave version:
`Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)`

## Android Device details:
Affect Android/Desktop, due to shields.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes

## Miscellaneous Information:
Either a shield option, or a separate option to allow 127.0.0.1 on a specific site.

**Comment by fmarier** [comment]
Duple of #11733 which is already assigned.

**Comment by ShivanKaul** [comment]
I'm not able to repro this on https://apps.crust.network/#/storage/files, the site just loads forever with or without the adblock exception rule.
