### ISSUE TITLE
enabling Rewards from panel should have waiter message when opting in

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1502]
## Description 
Similar to issue reported in https://github.com/brave/brave-browser/issues/1099. If you are using a fresh profile and you click on the BAT logo and are prompted to join Brave Rewards, when you click 'Join Rewards' there is a lag. It would be helpful if this had a similar waiter message as when opting in from `chrome://rewards`. I'm not sure if the exact same one is appropriate, users might not know what 'creating wallet' means here.

## Steps to Reproduce

   1. Clean profile.
   2. Click on BAT logo in URL bar.
   3. On Brave Rewards panel click on JOIN REWARDS

## Actual result:
Note lag, doesn't seem like anything is happening.
![panel](https://user-images.githubusercontent.com/28145373/46762420-00ce7280-cca5-11e8-9398-a2b265224f5a.gif)

## Expected result:
Waiter message similar to when opting in from `chrome://rewards` page

## Reproduces how often: 
easily

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes
- Does it reproduce on browser-laptop? n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @NejcZdovc @jenn-rhim

**Comment by srirambv** [comment]
Reproduced on Linux as well

**Comment by GeetaSarvadnya** [comment]
The referenced issue #1838 is still reproducible on Dev Build version 0.57.3.
![1838](https://user-images.githubusercontent.com/38657976/47559830-2f4e7d80-d934-11e8-98a8-73d1675b90df.gif)

**Comment by NejcZdovc** [comment]
#1838 was not included in 0.57.3

**Comment by kjozwiak** [comment]
Waiting for #1838 to be fixed as it's reproducible under `0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)` as well. Once #1838 has been resolved, this can be verified as well.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta(64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

![screen shot 2018-10-31 at 4 47 54 pm](https://user-images.githubusercontent.com/28145373/47817781-ef6d0900-dd2c-11e8-9405-82a0afec075a.png)
