### ISSUE TITLE
Show a notification when user has exceeded wallet linking limit

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15028]
## Description 

When the user connects an Uphold external wallet to Rewards, but they are unable to link the wallet because they have exceeded the linking limit, we should display a notification in the rewards panel.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.24.66 Chromium: 90.0.4430.72 (Official Build) beta (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Windows 10 OS Version 2009 (Build 19042.928)
```

### **`Limit Reached Cases (Production)`**

* verified the STR/cases outlined via https://github.com/brave/brave-core/pull/8391#issue-604237700
* ensured that connecting to a wallet that exceeds the linking limit correctly displays the notification via the rewards panel
* ensured that clicking on `X` dismisses the notification without any issues
* ensured that clicking on `Learn More` opens https://support.brave.com/hc/en-us/articles/360056508071 in a new tab
* ensured that once the notification is dismissed via `X` or `Learn More`, it doesn't re-appear after restoring the browser
* ensured that `device_limit_reached` is being recorded within the `Event logs` tab via `brave://rewards-internals`
* ensured that `device_limit_reached` is being recorded in `publisher_info_db` via the `event_log` table

**`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------
![Screenshot 2021-04-19 231442](https://user-images.githubusercontent.com/2602313/115335027-69e2ab00-a16a-11eb-8fd4-ade999def828.png) | ![Screenshot 2021-04-19 231722](https://user-images.githubusercontent.com/2602313/115335031-6d763200-a16a-11eb-8177-187a52443795.png) | ![Screenshot 2021-04-19 232220](https://user-images.githubusercontent.com/2602313/115335048-7535d680-a16a-11eb-876a-2d4172f7d0bf.png)

### **`Limit NOT Reached Cases (Staging)`**

* ensured that the notification isn't displayed when logging into an account that hasn't reached the limitations of 4 devices
* ensured that `device_limit_reached` isn't being added/displayed in the `Event logs` tab via `brave://rewards-internals`
* ensured that `device_limit_reached` isn't being recorded in `publisher_info_db` via the `event_log` table
* ensured that you can drain the BAT from Brave to Uphold without any issues

```
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v2/suggestions/claim
> Result: Success
> HTTP Code: 200
> Body: {"drainId":"17ee8cff-aa4a-4539-988d-e97543034c87"}
```

![Screenshot 2021-04-20 000558](https://user-images.githubusercontent.com/2602313/115336258-d8c10380-a16c-11eb-97ee-1d09e3c4bff2.png)

**Comment by kjozwiak** [comment]
@Miyayes @zenparsing should we display the warning every single time a user disconnected/re-connects the same wallet? I don't think it makes sense to keep displaying it. Maybe we can display it the first ~3-4 times and stop after that? Just a thought as it might annoy users but at the same time, I guess it makes sure that a user remembers that they've hit the limit.

@Miyayes thoughts?

Quick Example:

![Screenshot 2021-04-19 233752](https://user-images.githubusercontent.com/2602313/115336405-2b022480-a16d-11eb-9fef-a80d58af6ba6.png)

**Comment by Miyayes** [comment]
I would like to tell the user every single time they attempt to verify/re-verify over the linking limit that they've exceeded the linking limit. So, we can keep the current behavior. Thanks!
