### ISSUE TITLE
Extension verification options not matching Chromium on Linux

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#15024]
## Test plan
See https://github.com/brave/brave-core/pull/8392

## Description 
Creating based on conversations / troubleshooting which took place in https://github.com/brave/brave-browser/issues/2457 

Basically, problem involves installing an extension which is signed but not in Chrome Web Store.
- Installing this component is not possible on macOS / Windows in Chromium. We properly match that behavior 👍 
- However, Chromium on Linux *WILL* allow you to install. We are not allowing ☹️ Therefore not matching Chromium

## Steps to Reproduce
- See https://github.com/brave/brave-browser/issues/2457#issuecomment-807960531 for detailed steps
- https://github.com/brave/brave-browser/issues/2457#issuecomment-808395005 also has notes for Linux
- Test plan TBD

## Actual result:
We don't match Chromium behavior

## Expected result:
We should match Chromium behavior

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.24.32 Chromium: 90.0.4430.41 (Official Build) nightly (64-bit)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | Windows 10 OS Version 2009 (Build 19042.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome? N

**Comment by bsclifton** [comment]
Originally reported by folks in https://github.com/brave/brave-browser/issues/5761 - apologies for not finding that (and creating this new issue). You can view lots of reports of the problem there from folks

**Comment by btlechowski** [comment]
The test plan from https://github.com/brave/brave-core/pull/8392 involves all platforms. Added `QA/Test-All-Platforms` label.

**Comment by stephendonner** [comment]
Verified `PASSED` using slightly modified steps (checked with @bsclifton) from https://github.com/brave/brave-core/pull/8392 on

Brave | 1.25.60 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:

1. New profile (macOS or Windows); launch Brave
2. Downloaded [chromium-cleaner](https://github.com/afliw/chromium-cleaner)
3. Visited `brave://extensions`
4. Dragged the `chromium-cleaner.crx` extension from desktop onto the `chrome://extensions` page
5. Verified extension shows in `brave://extensions` as disabled (shows warning; you can't enable). 
6. Repeated steps 4-6 while toggled in `Developer mode`; confirmed same (disabled) result

regular brave://extensions | Developer mode brave://extensions
--------------------------|-------------------------------------
<img width="1098" alt="Screen Shot 2021-05-17 at 12 34 23 PM" src="https://user-images.githubusercontent.com/387249/118546150-66602680-b70c-11eb-87dc-ca353374b89b.png"> | <img width="1098" alt="Screen Shot 2021-05-17 at 12 32 43 PM" src="https://user-images.githubusercontent.com/387249/118545981-30bb3d80-b70c-11eb-8258-a6934875ab4e.png">

**Comment by LaurenWags** [comment]
Changing `release-notes/include` to `release-notes/exclude` since Linux still does not work as expected and a follow up issue is logged (Unable to install self-signed extension when developer mode is off on Linux #15956).
