### ISSUE TITLE
Truncate decimals for whole numbers in tipping amounts in tipping banner/UI

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15022]
## Description

Enforce the following logic in the tipping UI in order to better display various amounts of BAT:

1. In the tipping banner, if the value is a whole number (e.g., `1.00 BAT`, `5.00 BAT`, `10.00 BAT`), then truncate the decimals so that the number appears as `1 BAT`, `5 BAT`, `10 BAT`. 
2. Otherwise, display the decimals (e.g., `0.25 BAT`, `1.75 BAT`, etc.)

<img src="https://user-images.githubusercontent.com/11497541/113024533-dadb0800-9154-11eb-9f8e-16d2ab37bceb.png" width=400px>

Per design team @jenn-rhim.

**Comment by Miyayes** [comment]
Related: https://github.com/brave/brave-browser/issues/15050

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.24.65 Chromium: 90.0.4430.72 (Official Build) dev (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Windows 10 OS Version 2004 (Build 19041.928)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/8404

<details>
<summary>One-time tips with fractional custom tipping amount</summary>

</details>

**Comment by srirambv** [comment]
Removing Android label as Android specific issue is logged #15618
