### ISSUE TITLE
Cloudflare endless looping due fingerprinting

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#15039]
## Description 
Visiting the `http://chaingames.io/` caused an endless loop for the user

## Steps to Reproduce

   1. Open `http://chaingames.io/`
   2. Expect Cloudflare to redirect
   3. (according to user, didn't redirect)

## Actual result:

![d5af81cb6b7c85b50a3cd68f1fbca3f65a763553_2_690x431](https://user-images.githubusercontent.com/1659004/113126709-6a2b0d00-9274-11eb-966d-7bd87c4f78fe.png)

## Expected result:
Allow cloudflare to work correct (redirect correctly, and not loop)

## Reproduces how often: 

I wasn't able to reproduce, was reported via the forums.

## Brave version (brave://version info)
`Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (x86_64)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes, (Fingerprinting)
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Reported here: https://community.brave.com/t/brave-browser-stuck-on-cloudflare-loop/224513/

I wasn't able to reproduce this, but logged ticket for followup/confirmation 
![5b1be1a02b2ee163a46b04675c2806c7e2f219c8](https://user-images.githubusercontent.com/1659004/113127565-6350ca00-9275-11eb-87b0-32edac0ccf17.jpeg)
![bcdf2ccb791afea13bb94f96e81f52a02722398f](https://user-images.githubusercontent.com/1659004/113127573-651a8d80-9275-11eb-9e87-24c81bf4958c.jpeg)

**Comment by ryanbr** [comment]
cc: @pes10k

**Comment by pes10k** [comment]
I've reached out to CF to see if we can work things out with them.  @ryanbr, could you follow up in the community thread and let them know that we're trying to work things out with Cloudflare?

**Comment by chewy917** [comment]
@underdeveloped

**Comment by 12626267** [comment]
strange behaviour cloudflare has. Notorious things they are upto. In brave we trust. fix the internet it will.

**Comment by pes10k** [comment]
Cloudflare says they've addressed, and I can't reproduce this anymore (I was on Wednesday).  I'm going to close, though if anyone is still seeing this issue, please reopen and let me know.  Thanks!

**Comment by chewy917** [comment]
@underdeveloped

**Comment by TAKEYE01** [comment]
Hello I am the person who reported this issue (Tannerk08) I want to thank you guys for resolving this problem. It now is fixed and works! Thank you guys for all the time you put in to make Brave better for the people!

**Comment by dimon222** [comment]
Still happens on Android client.

**Comment by pes10k** [comment]
thank you for letting me know @dimon222 , let me loop back with Cloudflare and see if they have any more information.

**Comment by pes10k** [comment]
@dimon222 can you confirm whether you're using the default or aggressive level fingerprinting protections?

**Comment by dimon222** [comment]
`standard`. Only if I put "Allow all fingerprints" the page is able to pass cloudflare's challenge.

**Comment by leoschet** [comment]
I still have this issue on https://www.coingecko.com/en

**Comment by pes10k** [comment]
Thank you for the clarification @dimon222 and @leoschet , i will follow up with cloudflare again and see if I can get this sorted out.  Than you again for reporting the issue and for your patience

**Comment by pes10k** [comment]
@dimon222 and @leoschet , I was wondering if you each could let me know what UA string you're browsing with.  Cloudflare has told me that would help them sort things out.

If you need a convenient place to get your UA, https://www.whatismybrowser.com/detect/what-is-my-user-agent can be handy

thanks for any help you can provide!

**Comment by dimon222** [comment]
@pes10k 
```
Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
```

**Comment by bryanvaz** [comment]
> I still have this issue, same as dimon222, I only get throught by allowing all fingerprints. I'm using it on Mac v1.22.71

Can confirm this. Happens across all Cloudflare DDoS protected sites, including Gitlab's signin page.

Allowing all fingerprinting (or of course shields down) allows the CF check to pass.

Cheers,
Bryan

**Comment by pes10k** [comment]
Just to follow up here, I have an ongoing discussion with Cloudflare folks to sort this out.  I hope to have more news to share shortly, but we're working on it aggressively

**Comment by tainium** [comment]
Just another user reporting in.  Having this issue on Linux client but disabling fingerprinting/shields doesn't fix it for me.

**Comment by LaurenWags** [comment]
Verified passed on

```
Brave | 1.23.73 Chromium: 90.0.4430.85 (Official Build) (x86_64)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | macOS Version 10.15.7 (Build 19H524)
```

Verified STR from description. Confirmed I was redirected as expected.

<img width="1075" alt="1 23 73" src="https://user-images.githubusercontent.com/28145373/115739270-c658ec80-a35b-11eb-9f22-8c52e6a80235.png">

---------------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.73 x64 build
- Verified test plan from issue description 

https://user-images.githubusercontent.com/17010094/115751324-0090b100-a391-11eb-9403-07ee3bec4063.mp4

-----------
Verification passed on Samsung Tab A with Android 10 running 1.23.73 x64 build
- Verified test plan from issue description 

https://user-images.githubusercontent.com/17010094/115751605-3fbf0200-a391-11eb-96d1-cc7bc7b3324d.mp4

**Comment by kjkent** [comment]
Hi there,

I've been having issues with Brave Browser (1.38.111) on Linux (Fedora Workstation 35 & 36) not being able to pass DDOS protection pages including Cloudflare's. After completing the Cloudflare CAPTCHA, a long delay precedes a 403 error in DevTools.

This issue is not present using Brave on Windows, nor using Firefox on Linux.

**Comment by pes10k** [comment]
@kjkent do you have fingerprinting settings at default or aggressive? Are you using a VPN or Tor mode or something similar that'd cause you to be visiting from a IP that might get differently classified by CF?

@srirambv, if you have a chance, could you see if you're able to recreate?

**Comment by kjkent** [comment]
@pes10k, I typically have fingerprinting at default, but the issue persists even when Brave Shields are down. I'm not running a VPN nor using Tor mode. I originally thought it might be due to me visiting from Linux instead of Windows but, after installing Firefox on Fedora, I was able to get through the DDOS check.

**Comment by pes10k** [comment]
Thank you for the follow up information.  Two more questions if you don't
mind:

1. If you feel comfortable sharing, what country / geo are you connecting
from?
2. If you feel comfortable sharing, what URL(s) are you seeing the issue on?

Thanks!

**Comment by kjkent** [comment]
My apologies for the slow reply, @pes10k.

I'm connecting from the UK. I'd be happy to share the URLs I'm seeing the issue on, but it actually seems the issue has resolved. I recall that cloudflare.com itself inaccessible, but, I've just successfully accessed the website. In addition, https://sportsbikeshop.co.uk actually showed the DDOS protection screen for a second before redirecting successfully. 

Good news from a practicality standpoint, but perhaps not for issue reproduction! I shall get in touch, though, if I see it again.

Thanks for your assistance with this.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
I have the same issue across all Cloudflare protected websites.
Using Version 1.44.112 Chromium: 106.0.5249.119 (Offizieller Build) (64-Bit)
Any advise on how to actually be able to visit those websites?

**Comment by pes10k** [comment]
are you connecting through a VPN or Tor mode? Are you in default shields configurations?  If the answers are no, no and yes, @ryanbr may be able to help debug

**Comment by evilvampire16** [comment]
Hi there
I can't pass Cloudflare, have tried some websites and all are the same
other browsers are working just fine and not even asking me to verify myself and it just shows Cloudflare's page and auto verifies, and BOOM, I'm in. but I got stuck on a look of verifying using Brave v1.45.127 Windows, I'm using VPN and have tried both shield on(default config)/off nothing changes.

**Comment by LesskarrWolfe** [comment]
hello there not sure if this topic is still being monitored  but i been encountering this same issue on cloudflare protected sites well namely one in particular. https://www.fanfiction.net/  im not sure why but i can use the site fine in a regular private window but not in non private window. and not sure if its just the way the people who run that site have there settings set or something specific with cloudflare. its not major issue for me anymore since i realized it works fine in the private browser window. but would like to see if i can get it working in the non private browser window if possible.
