### ISSUE TITLE
DNS Leak appears with HTTP Proxy

### ISSUE THREAD

**Issue by githuber4687** [brave/brave-browser#15038]
## Steps to Reproduce

   1.  Connect a HTTP Proxy in system settings
   2.  Visit https://browserleaks.com/ip
   3.  Test DNS Leak

## Actual result:

![image](https://user-images.githubusercontent.com/81681296/113122305-130e4380-9246-11eb-860f-cdac56cd05ad.png)

## Expected result(from Edge Browser):
![image](https://user-images.githubusercontent.com/81681296/113122354-20c3c900-9246-11eb-98e0-12af06e4e272.png)

## Reproduces how often: 

Every Time/Always

## Brave version (brave://version info)

Brave | 1.22.70 Chromium: 89.0.4389.105

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
 Yes
- Can you reproduce this issue with the beta channel? 
 Yes
- Can you reproduce this issue with the nightly channel? 
 Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
  No
- Does the issue resolve itself when disabling Brave Rewards? 
  No
- Is the issue reproducible on the latest version of Chrome? 
  No (even Firefox)

**Comment by hollons** [comment]
Hi @githuber4687, thanks for reporting. Do you see the same leak in chrome? Do you have DNS over HTTPS enabled? Thanks in advance.

**Comment by diracdeltas** [comment]
do you have the same DNS over HTTPS settings in Brave and Chrome? you can see your DoH settings in brave://settings/security?search=dns

<img width="688" alt="Screen Shot 2021-03-31 at 9 56 37 AM" src="https://user-images.githubusercontent.com/549654/113183374-cc4e2880-9208-11eb-9889-fe7f9267c9a3.png">

**Comment by githuber4687** [comment]
> Hi @githuber4687, thanks for reporting. Do you see the same leak in chrome? Do you have DNS over HTTPS enabled? Thanks in advance.

Chrome does NOT have the same DNS leak issue. I have enabled DoH with my current service provider option.

**Comment by githuber4687** [comment]
> do you have the same DNS over HTTPS settings in Brave and Chrome? you can see your DoH settings in brave://settings/security?search=dns
> 
> <img alt="Screen Shot 2021-03-31 at 9 56 37 AM" width="688" src="https://user-images.githubusercontent.com/549654/113183374-cc4e2880-9208-11eb-9889-fe7f9267c9a3.png">

Chrome does NOT have the same DNS leak issue. I have enabled DoH with my current service provider option. Thanks for your timely help.

**Comment by fmarier** [comment]
Could you try with Secure DNS explicitly disabled? That's the configuration that Chrome uses since they [haven't rolled out DoH to Linux users yet](https://docs.google.com/document/d/1zAdSK393IznaLKQ0ItOmwLBy59fIq9ydxBRJQX-2ntQ/edit#heading=h.7nki9mck5t64) due to incompatibilities with some setups.

**Comment by githuber4687** [comment]
> Could you try with Secure DNS explicitly disabled? That's the configuration that Chrome uses since they [haven't rolled out DoH to Linux users yet](https://docs.google.com/document/d/1zAdSK393IznaLKQ0ItOmwLBy59fIq9ydxBRJQX-2ntQ/edit#heading=h.7nki9mck5t64) due to incompatibilities with some setups.

Thanks for your suggestion. However, the issue still exists. After switch it off, the test on Brave Browser still shows my real DNS rather than the DNS configured on my proxy sever.

**Comment by githuber4687** [comment]
@fmarier With the help of wireshark, I found that with HTTP Proxy, Brave Browser still sends DNS queries to the DNS sever that set in my router (local DHCP sever). Maybe this is the cause. Thanks for your timely help.

**Comment by diracdeltas** [comment]
cc @antonok-edm in case this may have been fixed recently with the changes to cname adblocking

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.34.76 Chromium: 97.0.4692.56 (Official Build) beta (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)



Steps:
1. new profile
2. find and use a SOCKS5 proxy server from the list at `https://geonode.com/free-proxy-list`
3. load `dnsleaktest.com`
4. click on `Standard test`
5. wait
6. confirm your DNS resolvers aren't found and listed; instead, it should show the server's IPs

<img width="1253" alt="Screen Shot 2021-12-28 at 4 31 51 PM" src="https://user-images.githubusercontent.com/387249/147619786-a54852e9-9dfc-447d-b27f-0c6f9fb7705f.png">

------

Verified `PASSED` using 


Brave | 1.34.76 Chromium: 97.0.4692.56 (Official Build) (64-bit)
--|--
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Linux


Steps:
1. new profile
2. find and use a SOCKS5 proxy server from the list at `https://geonode.com/free-proxy-list`
3. load `dnsleaktest.com`
4. click on `Standard test`
5. wait
6. confirm your DNS resolvers aren't found and listed; instead, it should show the server's IPs

<img width="1253" alt="Screen Shot 2021-12-28 at 4 31 51 PM" src="https://user-images.githubusercontent.com/387249/147619854-b77ba7f1-ca86-4615-b33e-a765e82193a5.png">

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.34.78 Chromium: 97.0.4692.71 (Official Build) (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 21H2 (Build 19044.1415)

```

There are two ways to test this issue on Windows. 

1. Setting the socks5 proxy at the app level
2. Setting the socks5 proxy in the Internet Options ->Connections->LAN settings->Proxy Server->Advanced->Proxy Settings-> set socks 5 proxy servers
