### ISSUE TITLE
Add RETRY_ON_NETWORK_CHANGE to referrals and stats

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#15034]
## Description 
Followup to https://github.com/brave/brave-browser/issues/15009. This will affect confirmations and custom headers. We also add the flag to stats requests because that may be affected too, as they ping the same host.

## Steps to Reproduce

Boot the browser and custom headers and finalization may not occur on Android due to a network change

## Reproduces how often: 
Always on simulator, often on actual device

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Y
- Can you reproduce this issue with the beta channel?
Y
- Can you reproduce this issue with the dev channel?
Y
- Can you reproduce this issue with the nightly channel?
Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using the following build:

* ensured that `download_id` appears under `brave://local-state`
* ensured that the `headers` are appearing under `brave://local-state`
* ensured that `stats` are appearing under `brave://local-state`
* ensure that `"promo_code": "WWK708"` is correctly being used

<details>
<summary>Logs/Data from brave://local-state</summary>

```
"referral": {
         "download_id": "c60077e1-5419-401c-a2d4-5bc4719c03dc",
         "headers": [ {
            "cookieNames": [  ],
            "domains": [ "eaff.com", "stg.eaff.com" ],
            "expiration": 31536000000.0,
            "headers": {
               "X-Brave-Partner": "eaff"
            }
         }, {
            "cookieNames": [  ],
            "domains": [ "sandbox.uphold.com", "api-sandbox.uphold.com", "uphold.com", "api.uphold.com" ],
            "expiration": 31536000000.0,
            "headers": {
               "X-Brave-Partner": "uphold"
            }
         } ],
         "initialization": true,
         "promo_code": "WWK708"
      },
      "referral_android_first_run_timestamp": "13261720590372766",
      "stats": {
         "first_check_made": true,
         "last_check_month": 3,
         "last_check_woy": 13,
         "last_check_ymd": "2021-03-31",
         "threshold_query": "https://laptop-updates.brave.com/1/usage/brave-core-threshold?platform=android-bc&channel=release&version=1.22.71&daily=true&weekly=true&monthly=true&first=true&woi=2021-03-29&dtoi=2021-03-31&ref=WWK708&adsEnabled=false&arch=",
         "week_of_installation": "2021-03-29"
      }
```
</details>
