### ISSUE TITLE
frequent "blocked by extension" error page

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#15047]
repros in Beta (1.23.51) but not Stable so appears to be a recent regression, possibly related to #14134. Also does not repro in Chrome with uBlock installed.

STR:
1. go to https://go.dowjones.com/managepreferences?utm_campaign=Approved_PROMO_20210330_WSJ%20Industry%20Events_WSJ%20RC%20Forum_Biden%20Email_HTML_Email%20B&utm_medium=email&utm_source=Eloqua&elqTrackId=1bd0f252de144d49bf5237cf29c610fa&elq=c3c3a8fecb9943fc9ab1e50d72983d11&elqaid=6923&elqat=1&elqCampaignId=4931
2. enter any email
3. check the 'unsubscribe' box at the bottom and submit

Result:
<img width="559" alt="Screen Shot 2021-03-31 at 10 17 25 AM" src="https://user-images.githubusercontent.com/549654/113185406-454e7f80-920b-11eb-9c10-e92dad29a18a.png">

Expected result:
https://s716031822.t.eloqua.com/e/DefaultFormSubmitConfirmation.aspx should load correctly

**Comment by diracdeltas** [comment]
this seems to be happening fairly frequently in beta. ex: https://bravesoftware.slack.com/archives/C2FQMN4AD/p1616797559085900, https://bravesoftware.slack.com/archives/C3GNZANPR/p1617133973035600?thread_ts=1617125499.033600&cid=C3GNZANPR, and https://bravesoftware.slack.com/archives/C3GNZANPR/p1617194521052200?thread_ts=1617125499.033600&cid=C3GNZANPR.

i encountered it on 50% of emails i tried to unsubcribe from this morning. in one case, reloading the page made the error go away.

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` until this is uplifted to 1.23.x

**Comment by kjozwiak** [comment]
@diracdeltas @pes10k @antonok-edm is this specific to `desktop` or does it need to be verified on `android` as well?

**Comment by pes10k** [comment]
I saw it on desktop frequently, i do not know if it showed up on Android (though i expect it did bc of the implementation).  @antonok-edm since you did the fix, maybe you can confirm?

**Comment by antonok-edm** [comment]
@kjozwiak this has occurred on Android as well.

**Comment by kjozwiak** [comment]
Thanks 👍 Added `OS/Android` so this gets checked on android. I also added both `QA/Test-All-Device-Types` & `QA/Test-All-Platform` as this is something we'll probably want to check on all platforms.

**Comment by antonok-edm** [comment]
This shouldn't need any testing on iOS, but otherwise that sounds good :+1:

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Andriod 10 running 1.23.66 x64 Beta build
- Verified test plan from https://github.com/brave/brave-core/pull/8402
- Verified test plan from issue description
- Verified disabling/enabling `#brave-domain-block` doesn't affect page load from test plan

  <details>
  <summary>Screenshots</summary>

   ![image](https://user-images.githubusercontent.com/17010094/113856507-40ed0e00-9799-11eb-8981-905d9c4fe87d.png) | ![image](https://user-images.githubusercontent.com/17010094/113856520-45192b80-9799-11eb-81dc-fc66f0274a1d.png)
   -- | --

  </details>
------------------
Verification passed on Samsung Tab A with Andriod 10 running 1.23.66 x64 Beta build
- Verified test plan from https://github.com/brave/brave-core/pull/8402
- Verified test plan from issue description
- Verified disabling/enabling `#brave-domain-block` doesn't affect page load from test plan

  <details>
  <summary>Screenshots</summary>
   
   ![image](https://user-images.githubusercontent.com/17010094/113871211-91b93280-97aa-11eb-99e9-7bf69e1b102c.png) | ![image](https://user-images.githubusercontent.com/17010094/113871242-9aaa0400-97aa-11eb-8ca5-5a4d7140a648.png)
   -- | --

  </details>
