### ISSUE TITLE
[CRITICAL] Rendering issues, dead pixels, can't see tabs and images

### ISSUE THREAD

**Issue by changyeamoon** [brave/brave-browser#15040]
## Description 

With the latest update, my Brave Browser has not been displaying certain images, text, tabs, bookmarks, etc. It seems like a rendering issue because I occasionally see dead pixels. 

## Steps to Reproduce

   1. Open Brave browser Version 1.22.70 (arm64) with Mac Mini M1 Big Sur
   2. 
   3. 

## Actual result:

I can't even see the template lol

![Screen Shot 2021-03-31 at 10 30 43 AM](https://user-images.githubusercontent.com/30943398/113161731-a9be0e80-920c-11eb-8698-f4a9ff97e2b3.png)

## Expected result:
The normal Brave Browser

## Reproduces how often: 

Every-time I open Brave

## Brave version (brave://version info)

Brave | 1.22.70 Chromium: 89.0.4389.105 (Official Build) (arm64)
-- | --
Revision | 14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS | macOS Version 11.2.3 (Build 20D91)
JavaScript | V8 8.9.255.20
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,SafetyTip,AutoupgradeMixedContent,WebUIDarkMode,LegacyTLSEnforced --disable-features=AutofillEnableAccountWalletStorage,IdleDetection,AutofillServerCommunication,TextFragmentAnchor,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,SafeBrowsingEnhancedProtection,SignedExchangeSubresourcePrefetch,PrivacySettingsRedesign,NotificationTriggers,WebOTP,DirectSockets,TabHoverCards,LangClientHintHeader,NetworkTimeServiceQuerying,SafeBrowsingEnhancedProtectionMessageInInterstitials --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/changmoon/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations | 7146a73c-3f4a17df

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by chewy917** [comment]
@underdeveloped

**Comment by changyeamoon** [comment]
halp me plox

**Comment by bsclifton** [comment]
@changyeamoon can you please turn OFF hardware acceleration under brave://settings/system?

**Comment by changyeamoon** [comment]
Thank you @bsclifton that did the trick! I'm sorry I couldn't find that duplicate- used the wrong search terms

**Comment by bsclifton** [comment]
@changyeamoon not a problem - just mentioning a duplicate for our purposes 😄 Super glad it worked!
