### ISSUE TITLE
Expiry of JS cookie is capped at 6 months instead of 7 days

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#15048]
In #3443, we capped the lifetime of cookies set in JS to 7 days and all other cookies to 6 months. Right now, JS cookies are capped at 6 months when tested using the test plan on https://github.com/brave/brave-core/pull/1905.

I'm not sure when this regression was introduced.

## Steps to Reproduce

   1. Open <https://fmarier.github.io/brave-testing/document-cookie.html>.
   2. Click on *Normal cookie using `Max-Age`*.
   3. Open the *Application* tab in the devtools.
   4. Click on *Storage*, then *Cookies* in the sidebar.
   5. Click on `https://fmarier.github.io` and look at the expiry column.
   6. Open `brave://settings/cookies/detail?site=fmarier.github.io` and check the expiry there too.

## Actual result:
The expiry is now + 6 months.

## Expected result:
The expiry should be now + 7 days.

## Reproduces how often: 
Always

## Brave version (brave://version info)
```
Brave	1.23.51 Chromium: 89.0.4389.105 (Official Build) beta (64-bit)
Revision	14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS	Linux
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.77 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.77`
2. launched Brave
3. opened `https://fmarier.github.io/brave-testing/document-cookie.html`
4. clicked on Normal cookie using Max-Age
opened the `Application` tab in the devtools
click on Storage, then Cookies in the sidebar
click on https://fmarier.github.io and look at the expiry column
opened `brave://settings/cookies/detail?site=fmarier.github.io` and checked the expiry there too



#### Confirmed the expiry date is now correctly set to `October 7, 2022`, which is +7 _***days***_ (not ***_months_***) ahead

`https://fmarier.github.io/brave-testing/document-cookie.html` | `brave://settings/cookies/detail?site=fmarier.github.io`
------|-----------------
<img width="1367" alt="Screen Shot 2022-09-30 at 8 46 07 AM" src="https://user-images.githubusercontent.com/387249/193273828-6d54ea9f-4867-41cd-9a1b-13cd9e334342.png"> | <img width="1483" alt="Screen Shot 2022-09-30 at 8 51 21 AM" src="https://user-images.githubusercontent.com/387249/193273840-e624a09a-6f0d-453d-99ab-e4912bc825d5.png">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

### Steps:

Test Case 1:  client-side cookies (7-day limit) - `PASSED`
<details>

1. installed `1.45.84`
2. launched Brave
3. opened `https://fmarier.github.io/brave-testing/document-cookie.html`
4. clicked on Normal cookie using Max-Age
    - opened the `Application` tab in the devtools
    - click on Storage, then Cookies in the sidebar
    - click on https://fmarier.github.io and look at the expiry column
    - opened `brave://settings/cookies/detail?site=fmarier.github.io` and checked the expiry there too

Confirmed the expiry date is now correctly set to October 10, 2022, which is +7 days 
step 3|step 4
----|----
<img width="942" alt="image" src="https://user-images.githubusercontent.com/98358127/193669274-11c973a7-d66a-4dfb-8186-5f359755e50a.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/193669408-b9731fe2-36e8-4d20-91fc-fce2f18278fc.png">

</details>

Test Case  2: server-side cookies (6-month limit) -  `PASSED`
<details>

Case 1: test 1 - `https://fmarier.org/document-cookie/set-cookie1.html` - `PASSED`
<details>

1. new profile 
2. launch Brave
3. visit https://fmarier.org/document-cookie/set-cookie1.html
      - opened the `Application` tab in the devtools
      - click on Storage, then Cookies in the sidebar
      - click on https://fmarier.org and look at the expiry column
      - opened `brave://settings/cookies/detail?site=fmarier.org` and checked the expiry there too

Confirmed the expiry date is now correctly set to April 01, 2023, (which is 6-month limit) 

step 3c|step3d
----|----
<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/193674711-a56e29aa-6c63-482c-8da7-f826f128043a.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/193674778-af3bfecf-887c-4333-856a-10e4e452c37e.png">

</details>

Case 2: test 2 -  `https://fmarier.org/document-cookie/set-cookie2.html` - `PASSED`
<details>

1. continue from Case 1
2. visit https://fmarier.org/document-cookie/set-cookie2.html in a new tab
      - opened the `Application` tab in the devtools
      - click on Storage, then Cookies in the sidebar
      - click on https://fmarier.org and look at the expiry column
      - opened `brave://settings/cookies/detail?site=fmarier.org` and checked the expiry there too

Confirmed the expiry date is now correctly set to April 01, 2023, (which is 6-month limit) 

step 2c|step2d
----|----
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/193677326-94a43504-6364-4792-b572-d3e5fe624398.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/193677392-38563a06-3200-4f41-8ff4-bfae915f9328.png">

</details>

Case 3: test 3 - `https://fmarier.org/document-cookie/set-cookie3.html` - `PASSED`
<details>

1. continue from Case 2
2. visit https://fmarier.org/document-cookie/set-cookie3.html in a new tab
      - opened the `Application` tab in the devtools
      - click on Storage, then Cookies in the sidebar
      - click on https://fmarier.org and look at the expiry column
      - opened `brave://settings/cookies/detail?site=fmarier.org` and checked the expiry there too

Confirmed the expiry date is now correctly set to April 01, 2023, (which is 6-month limit) 

step 2c|step2d
----|----
<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/193677935-6f5cbfef-55d6-46b8-a827-7d24705f10e7.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/193678027-c0e381a7-cb90-449d-b510-ccf4ea263a2e.png">

</details>

Case 4: test 4  - `https://fmarier.org/document-cookie/set-cookie4.html` 
<details>

1. continue from Case 3
2. visit https://fmarier.org/document-cookie/set-cookie4.html in a new tab
      - opened the `Application` tab in the devtools
      - click on Storage, then Cookies in the sidebar
      - click on https://fmarier.org and look at the expiry column
      - opened `brave://settings/cookies/detail?site=fmarier.org` and checked the expiry there too

Confirmed the expiry date is now correctly set to October 5, 2022

step 2c|step2d
----|----
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/193678592-5ce5b6e6-9d79-4c44-bf8f-86db817a538e.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/193679236-7e3e5c5a-a316-4dd2-a5c2-40ce42dd7164.png">

</details>
</details>
