### ISSUE TITLE
Tipping UI should be able to handle values with or without decimal points

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15050]
## Description 

Default tipping amounts can be changed asynchronously server-side, and then are fetched by the client (browser). Currently, the tipping amounts defined in the JSON response from the server endpoint uses whole numbers like: `1, 5, 10` with no decimal points. However, we want to be able to use numbers like `0.25` with decimal points as well. 

The client should be able to handle both cases: whole numbers `1` without decimal points, and numbers with decimals such as `1.75`, or `1.00`. 

## Solution

Ensure that the tipping UI and banner expects and can handle non-integer values.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.24.81 Chromium: 90.0.4430.93 (Official Build) (x86_64)
Revision	4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS	macOS Version 10.15.7 (Build 19H1030)
```

Per discussion with @miyayes, QA is only testing this with the default banners and not creator selected tip amounts from the creators website.

<details>
<summary>One-time tip with fractional default tipping amount - Anon Wallet</summary>

Confirmed UI showed fractional tipping amounts correctly
Confirmed fractional tip was successful when using an anon (VG BAT funded) wallet

One time tip banner | One time tip success message | Tips panel | Wallet Summary | brave://rewards-internals
----- | ----- | ----- | ----- | -----
<img width="1194" alt="1time tip banner" src="https://user-images.githubusercontent.com/28145373/116734685-91801180-a9bb-11eb-8401-43af8bf85ad8.png"> | <img width="1194" alt="1time tip success" src="https://user-images.githubusercontent.com/28145373/116734691-92b13e80-a9bb-11eb-83ab-595eec61d7c6.png"> | <img width="654" alt="tips panel" src="https://user-images.githubusercontent.com/28145373/116734695-93e26b80-a9bb-11eb-8a4e-364c5ab0c7d5.png"> | <img width="396" alt="wallet summary" src="https://user-images.githubusercontent.com/28145373/116734701-947b0200-a9bb-11eb-9162-306c25ee8ce5.png"> | <img width="450" alt="internals" src="https://user-images.githubusercontent.com/28145373/116734705-95ac2f00-a9bb-11eb-8bde-21a40bf1f3a8.png">

Logs
```
[4753:775:0430/134541.345786:VERBOSE1:contribution.cc(373)] Creating contribution for wallet type blinded (amount: 1.25, type: RewardsType::ONE_TIME_TIP)
[4753:775:0430/134541.350687:VERBOSE1:contribution.cc(90)] Queue timer set for 10 s
[4753:775:0430/134541.356965:VERBOSE5:ledger_impl.cc(144)] 
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v1/suggestions
> Method: UrlMethod::POST
> Content: {"credentials":[{"publicKey":"6AphTvx13IgxVRG1nljV2ql1Y7yGUol6yrVMhEP85wI=","signature":"UyJDLYMCTh4GyeSVjjLvHgMfYXoar/c4oP9PW/4qYewDzmk/b143o5ZRaNHp8vdqtH9jEoAKs8yb8QyPG6Y0AQ==","t":"jhFL/zzhUPn66XfnLAMHK8L7n6riLnED+75Cu7+2w3Q8nhp9J3QiHDjNfQD41SOGeS8/guU/zJUysn0r04/LuA=="},{"publicKey":"6AphTvx13IgxVRG1nljV2ql1Y7yGUol6yrVMhEP85wI=","signature":"NF1TJstrBqJQJacA/7f4mmFAgrI8QjdaYlOxqIh1s9ogUdAI7tvETVW7V7iDzGZzBKmZqPW+zCVXsmlSb9uqsg==","t":"yx5mAZAb2UHyvWuVlXPBRycxuJnZC5F5b9HZUqKSusmgZP+8Equ6nlS1l+ljIX0bLJqr+0DLG3PrQ8nipXMybg=="},{"publicKey":"6AphTvx13IgxVRG1nljV2ql1Y7yGUol6yrVMhEP85wI=","signature":"0otDr8SMu1IsTlBtk4FX6Vsh15bdQqt1xhhuYWjsbJSrLF6/EUpUMnx+Wjgx7gFh82LTX1yOR/KxVFH8g9isiQ==","t":"Co2UguXxd6iVL/YkSys0LH+9oxiiOQUVKw0XHio4BKx7ArH7HdS1+jg02iBUXieaeRlrTwkYFnJXh+i9e79bPA=="},{"publicKey":"6AphTvx13IgxVRG1nljV2ql1Y7yGUol6yrVMhEP85wI=","signature":"dnabKPTh7tRV4E/9SgsawQMSAFffo9CDYuHrkfhr8bewYHq1g8kZEbCDz8sw2B6JScEAjUpNOViwCyfqNaTHaQ==","t":"8dtdzqw2YKLjiFlXZQXhBGXvjTlJCvc0j20IGfElKTyFDh7h5yn4Im/0VaTUig2+l6yo/dqJueoUbsmrr8Q/FA=="},{"publicKey":"6AphTvx13IgxVRG1nljV2ql1Y7yGUol6yrVMhEP85wI=","signature":"NMZwiJTt+hYZJeryNhTgN79pd55dbZy4pU8IZ/XbLBJ6VwxrgdDrtJ10AnvkyOdSXZRxGgrIg+S9o45NyiKZ4w==","t":"+ZI7x9PNw8WFuSOZwrYGWrstGOQXBjdFMBxmpH7DRT0QprCU6ADmKqxvlj+cxXTuHmrAb6VKH24RMK5vjIIK/g=="}],"suggestion":"eyJjaGFubmVsIjoiZHVja2R1Y2tnby5jb20iLCJ0eXBlIjoib25lb2ZmLXRpcCJ9"}
> Content Type: application/json; charset=utf-8
[4753:775:0430/134541.964325:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v1/suggestions
> Result: Success
> HTTP Code: 200
> Body: 
```

</details>

**Comment by stephendonner** [comment]
Per discussion with @deeppandya, fractional-tipping UI isn't yet available on Android; filed https://github.com/brave/brave-browser/issues/15618 and am removing `OS/Android` as it doesn't apply right now.
