### ISSUE TITLE
Reduce Uphold minimum BAT user wallet verification requirement to 15 BAT 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15055]
## Description 

Currently, users need to have 25 BAT to verify their user wallet with Uphold. 

Uphold has approved lowering the verification threshold to 15 BAT as of March 31, 2021.

## Solution

Reduce all relevant wallet verification gating logic to a 15 BAT threshold.

**Comment by CloggyAbroad** [comment]
It looks like the text hasn't been updated in all locations

![image](https://user-images.githubusercontent.com/27993294/115062955-d77ca600-9ee2-11eb-93c5-523b7445bf05.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8453

Brave | 1.25.33 Chromium: 90.0.4430.85 (Official Build) nightly (x86_64)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. launched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
2. clicked `Start using Rewards` and confirmed UGP token grant of `30.000 BAT`
3. loaded `https://www.github.com/laurenwags`, and clicked on the BAT icon
4. clicked `Send a tip...`
5. chose `20 BAT` and clicked `Send Tip`
6. BAT balance was now `10.000 BAT`
7. clicked on the BAT icon again and clicked `Verify Wallet`
8. confirmed that the text about minimum BAT to create an Uphold account read `15 BAT`
9. loaded `brave://rewards` and clicked on the `Verify Wallet` link
10. confirmed also that the text there about minimum BAT to create an Uphold account read `15 BAT`
11. from both entry-points, I clicked on the orange `Login` button and was taken to Uphold's sandbox (`https://wallet-sandbox.uphold.com/`)
12. verified I could log in to Uphold, but my wallet wasn't verified

### Scenario: User has more than 15 BAT (Rewards panel)
1. launched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
2. clicked `Start using Rewards` and confirmed UGP token grant of `30.000 BAT`
3. clicked on the BAT icon again and clicked `Verify Wallet`
4. clicked on the orange `Login` button and was taken to Uphold's sandbox (`https://wallet-sandbox.uphold.com/`)
5. verified I could log in to Uphold, and my wallet was verified

### Scenario: User has more than 15 BAT (`brave://rewards` page)
1. launched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
2. clicked `Start using Rewards` and confirmed UGP token grant of `30.000 BAT`
3. loaded `brave://rewards` and clicked on the `Verify Wallet` link
4. clicked on the orange `Login` button and was taken to Uphold's sandbox (`https://wallet-sandbox.uphold.com/`)
5. verified I could log in to Uphold, and my wallet was verified


example | example | example | example | example | example | example | example
---------|----------|---------|----------|----------|---------|---------|----------
<img width="1792" alt="Screen Shot 2021-04-21 at 10 20 25 AM" src="https://user-images.githubusercontent.com/387249/115596684-3c425280-a28d-11eb-960a-63acf125ee51.png"> | <img width="1792" alt="Screen Shot 2021-04-21 at 10 20 31 AM" src="https://user-images.githubusercontent.com/387249/115596686-3cdae900-a28d-11eb-8299-9c63604e67d2.png"> | <img width="1792" alt="Screen Shot 2021-04-21 at 10 20 38 AM" src="https://user-images.githubusercontent.com/387249/115596688-3d737f80-a28d-11eb-8dfb-88fe497e9c9e.png"> | <img width="1312" alt="Screen Shot 2021-04-21 at 10 35 29 AM" src="https://user-images.githubusercontent.com/387249/115596978-95aa8180-a28d-11eb-970b-e01484aef943.png"> | <img width="1312" alt="Screen Shot 2021-04-21 at 10 35 43 AM" src="https://user-images.githubusercontent.com/387249/115596982-96dbae80-a28d-11eb-9698-b5e0db887cac.png"> | <img width="1312" alt="Screen Shot 2021-04-21 at 10 36 00 AM" src="https://user-images.githubusercontent.com/387249/115596984-96dbae80-a28d-11eb-9a16-8b7523e8c5a3.png"> | <img width="1312" alt="Screen Shot 2021-04-21 at 10 36 34 AM" src="https://user-images.githubusercontent.com/387249/115596987-97744500-a28d-11eb-89c9-124aebbcbc36.png"> | <img width="1312" alt="Screen Shot 2021-04-21 at 10 36 54 AM" src="https://user-images.githubusercontent.com/387249/115596992-97744500-a28d-11eb-8ce8-d21528e665f6.png">

**Comment by stephendonner** [comment]
@CloggyAbroad can you still reproduce this with a `nightly` build (https://brave.com/download-nightly/), against the staging environment, following my steps?  Thanks!

**Comment by CloggyAbroad** [comment]
@stephendonner the steps you describe are to verify the limit has been reduced to 15 BAT. I have no doubt this works. What I highlighted is that if you have less than 15 BAT in your rewards wallet (0.25 in my case) and you press the Rewards Logo in the address bar, followed by the Verify Wallet button, a text box pops up saying you need 25 BAT to verify. If I do the same from the brave://reward page a text box pops up saying I need 15 BAT to verify. This is what I showed in the picture I uploaded. This is still the case now (1.25.33)

**Comment by AdityaSher** [comment]
Is this live on android as well? ( Can't see it on my end)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.60 x64 Beta Build

<details>
<summary>Scenario 1 : User has less than 15 BAT (rewards panel)</summary>
<br>

- Verified when wallet has less than 15 BAT the info modal is shown when clicked on `Verify Wallet`
- Verified text clearly mentions min balance of 15 BAT
- Verified Login button is shown below the min balance message
- Verified clicking that opens Uphold page to connect existing wallet
- Verified able to successfully connect existing wallet and balance updates accordingly even when wallet balance is below the min threshold value

https://user-images.githubusercontent.com/17010094/118453498-335b6a00-b6ef-11eb-9502-10748d458831.mp4

</details>

<details>
<summary>Scenario 2 : User has exactly 15 BAT (rewards panel)</summary>
<br>

- Verified when wallet has exact 15 BAT and clicks on `Verify Wallet` on rewards panel, no info message is shown 
- Verified clicking on Verify Wallet opens up uphold page
- Verified able to successfully connect existing wallet and balance updates accordingly 

https://user-images.githubusercontent.com/17010094/118454102-e62bc800-b6ef-11eb-8f3e-59f150b3f817.mp4

</details>

<details>
<summary>Scenario 3: User has more than 15 BAT (rewards panel)</summary>
<br>

- Verified when wallet balance is more than 15BAT clicking on verify wallet doesn't show info modal
- Verified able to successfully connect to existing Uphold account and balance updates accordingly

https://user-images.githubusercontent.com/17010094/118454160-f80d6b00-b6ef-11eb-9984-00f22254f182.mp4

</details>

------------
Verification passed on OnePlus 6T with Android 10 running 1.25.60 x64 Beta Build

<details>
<summary>Scenario 1 : User has less than 15 BAT (rewards panel)</summary>
<br>

- Verified when wallet has less than 15 BAT the info modal is shown when clicked on `Verify Wallet`
- Verified text clearly mentions min balance of 15 BAT
- Verified Login button is shown below the min balance message
- Verified clicking that opens Uphold page to connect existing wallet
- Verified able to successfully connect existing wallet and balance updates accordingly even when wallet balance is below the min threshold value

![image](https://user-images.githubusercontent.com/17010094/118454243-0e1b2b80-b6f0-11eb-87f1-2201fdb1585f.png)

</details>

<details>
<summary>Scenario 2 : User has exactly 15 BAT (rewards panel)</summary>
<br>

- Verified when wallet has exact 15 BAT and clicks on `Verify Wallet` on rewards panel, no info message is shown 
- Verified clicking on Verify Wallet opens up uphold page
- Verified able to successfully connect existing wallet and balance updates accordingly 

</details>

<details>
<summary>Scenario 3: User has more than 15 BAT (rewards panel)</summary>
<br>

- Verified when wallet balance is more than 15BAT clicking on verify wallet doesn't show info modal
- Verified able to successfully connect to existing Uphold account and balance updates accordingly

</details>
