### ISSUE TITLE
Investigate 64-bit Option on Android

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#15063]
## Description 
From the March 11, 2021 Chromium announcement:

> For those of you who picked up the latest Android devices (Android Q+ and 8GB+ of RAM), we’ve rebuilt Chrome as a 64-bit binary, giving you a more stable Chrome that is up to 8.5% faster to load pages and 28% smoother when it comes to scrolling and input latency.

Source: https://blog.chromium.org/2021/03/advanced-memory-management-and-more.html

**Comment by kjozwiak** [comment]
STR:

* install `1.24.x` using `aab` on a `arm64` device
* visit `brave://version` and ensure that you see `x64`

Example:

![Screenshot 2021-05-06 133445](https://user-images.githubusercontent.com/2602313/117341308-f29e5e00-ae6f-11eb-95ba-74083927138e.png)
