### ISSUE TITLE
Notification problem for some web sites

### ISSUE THREAD

**Issue by pckolog1** [brave/brave-browser#15062]
## Description 

On Mac OS last version and brave last version, this two sites notifications doesn’t work.

99designs.com 
Outlook.com email
I try this sites with Vivaldi, chrome, and edge. They are all working.

## Steps to Reproduce

   1. I enabled notifications.
   2. Disabled or enabled ads protection.
   3. Disable all extensions, new user profile.
   4. Nothing worked.
   5. When I check console when I press the enable notf. button on 99designs, I get this message on console:
   `bugsnag.js:2424 Browser Enable error DOMException: Registration failed - push service error undefined
e._config.enabledBreadcrumbTypes.console.<computed> @ bugsnag.js:2424`

## Actual result:

No notifications

## Expected result:
Sites can send notifications

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.22.70 Chromium: 89.0.4389.105 (Resmi Derleme) (x86_64)

## Version/Channel Information:

no notifications neither.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- NO
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- no. Chrome has notifications without any problem

**Comment by snowbound** [comment]
I have noticed this on YouTube. I repeatedly enabled notifications for Youtube.com to reload the page and whenever Brave is restarted the notifications setting for YouTube.com has reset back to Default (Ask). Using Version 1.23.58 Chromium: 89.0.4389.114 (Official Build) beta (64-bit) on Windows10 here. Have verified and none of the cookie deletions options are set.

**Comment by bsclifton** [comment]
@pckolog1 can you please visit brave://settings/privacy and then enable `Use Google services for push messaging`? This requires a browser restart, but it should fix the problem you are seeing. Let us know 😄 
![image](https://user-images.githubusercontent.com/4733304/113817330-08aee680-972b-11eb-9756-630637232e58.png)

**Comment by pckolog1** [comment]
> @pckolog1 can you please visit brave://settings/privacy and then enable `Use Google services for push messaging`? This requires a browser restart, but it should fix the problem you are seeing. Let us know 😄
> ![image](https://user-images.githubusercontent.com/4733304/113817330-08aee680-972b-11eb-9756-630637232e58.png)
> 
> Some push notifications are using Google Cloud Messaging (GCM) and we disable that by default (for privacy reasons)

Yes, thank you. This worked!

**Comment by wbobeirne** [comment]
Is there any efforts underway for Brave to offer a privacy-conscious default out of the box instead of outright disabling this? It's very hard to provide users instructions on how to go into their settings and check this, because there's no reliable way to detect they're using Brave.
