### ISSUE TITLE
Replace new tab pages for Private Windows with and without Tor

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1507]
In which @rossmoody is making the designs, @tomlowenthal is writing the text, with @riastradh-brave to implement.

**Comment by bbondy** [comment]
Is there a mockup of what this task is that we can put in here?
Only a couple working days left until the freeze, thanks!

**Comment by rossmoody** [comment]
These are the latest designs for this initiative. @davidtemkin didn't seem to have any objections today but just wanted to make sure we had the finalized copy from @tomlowenthal which we can finesse once it's built. 
![tor](https://user-images.githubusercontent.com/29072694/46850366-86871680-cda8-11e8-98f1-77b0ca23dfeb.png)
![private window](https://user-images.githubusercontent.com/29072694/46850367-871fad00-cda8-11e8-9c0c-de1938150ec5.png)
![qwant layout](https://user-images.githubusercontent.com/29072694/46850364-86871680-cda8-11e8-98f1-0946fd82fa1d.png)
![responsive layout](https://user-images.githubusercontent.com/29072694/46850365-86871680-cda8-11e8-854f-3f7999040dd6.png)

**Comment by bbondy** [comment]
I suspect we need @cezaraugusto's help here if we're to make this task in time (he might already be working on it, not sure).

**Comment by bbondy** [comment]
Fairly sure this isn't making it in by the freeze tomorrow morning, so moving to the 1.0 project.

**Comment by bbondy** [comment]
Didn't realize there was activity in this, no problem moving back if we make the cut.

**Comment by rossmoody** [comment]
I think this is still on track to make it. @cezaraugusto has a better handle on status but we're on it and progress seems positive.

**Comment by tomlowenthal** [comment]
QA: note the following changes from the designs in this issue:

**Comment by tomlowenthal** [comment]
QA: note the following changes from the designs in this issue:
- Final text is in [this doc](https://docs.google.com/document/d/1-LvUwonWwXiFJvw1MjLt9fsCWktEiKiEM7cZ-UN6uPQ), not the mockups
- Learn more overlay has been replaced with links to the knowledge base
- For this revision, all browsers get the DDG version, there's no impl of the DDG-free one

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* All support links to correct article on KB
* Tor window `More info` is missing which is mentioned in the document but not implemented. cc: @tomlowenthal to confirm if this needs to be tracked in a new issue? 
![image](https://user-images.githubusercontent.com/17010094/47058484-3edf0100-d193-11e8-9248-a06eb0438e6a.png)

**Comment by kjozwiak** [comment]
> Tor window More info is missing which is mentioned in the document but not implemented. cc: @tomlowenthal to confirm if this needs to be tracked in a new issue?

@tomlowenthal as @srirambv mentioned above, the mockup from https://github.com/brave/brave-browser/issues/1507#issuecomment-429212976 doesn't display the `Learn more` under the `THIS IS A Private Window with Tor` section but the https://docs.google.com/document/d/1-LvUwonWwXiFJvw1MjLt9fsCWktEiKiEM7cZ-UN6uPQ document mentions that there should be a `[Learn more]` underneath. Let us know which one is correct and we'll create a new issue if `Learn more` should have been there.

**Comment by rossmoody** [comment]
Yeah that was an intentional omission I made on the fly cause the screens were needed so quickly. Too many big learn more buttons all over the page and in Windows with Tor it would have made it two big purple buttons going to the same article.. The Private Window learn more button was adjusted to a link inline with the copy as well instead of a big button (we could probably follow suit in Tor windows but I'd like to sit with it for a bit).
