### ISSUE TITLE
auto contribute amount of 1 BAT has odd behavior

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15071]
## Description 

When my AC is set to 1 BAT I'm seeing that the contributions listed on brave://rewards-internals look odd and add up to be over 1 BAT. If I change this value to 2 BAT, I don't see the same problem.

## Steps to Reproduce

General steps are:
   1. Clean profile, use staging env (launched with `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5`)
   2. Enable Rewards, claim UGP grant
   3. Make sure AC is set to 1 BAT
   4. Visit 2-3 verified sites
   5. Wait for AC to process
   6. Look at brave://rewards-internals

## Actual result:

Examples with 2 and 3 sites for AC:
<img width="1150" alt="Screen Shot 2021-04-01 at 10 59 15 AM" src="https://user-images.githubusercontent.com/28145373/113315269-17d10700-92db-11eb-81d1-d1350a08bc85.png">
<img width="945" alt="Screen Shot 2021-04-01 at 11 10 05 AM" src="https://user-images.githubusercontent.com/28145373/113315276-19023400-92db-11eb-8c38-5bfd93238ed8.png">

## Expected result:
AC should not contribute over 1 BAT

## Reproduces how often: 

initially it was easy to reproduce, now it seems intermittent at best

## Brave version (brave://version info)

Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | macOS Version 10.15.7 (Build 19H524)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.22.71 yes, 1.22.70 no
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @emerick @zenparsing @brave/legacy_qa @rebron

**Comment by btlechowski** [comment]
I was unable to reproduce on

Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/113323493-4f10d980-9316-11eb-9d9f-ed070d6c9916.png)

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in `Windows 10 x64 - 1.22.71`

![image](https://user-images.githubusercontent.com/38657976/113328099-6b723d80-9339-11eb-9b97-5519a2316a39.png)

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.23.68 Chromium: 90.0.4430.51 (Official Build) (64-bit)
-- | --
Revision | 32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}
OS | Windows 10 OS Version 2004 (Build 19041.867)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/8436#issue-609096576

_**Auto Contribution via Rewards BAT (Staging)**_

<details>
<summary>AC amount 1 BAT with a single creator</summary>

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------

</details>
