### ISSUE TITLE
Bundle fallback Tor binary so it doesn't *have* to be downloaded at first run

### ISSUE THREAD

**Issue by tildelowengrimm** [brave/brave-browser#1508]
Currently the Tor binary is downloaded at first run. If you download the Brave installer and then move to a slow/censored connection before first run, this could be a hassle. It also means that Tor won't work if our infrastructure goes down or if someone blocks connections to Brave.

Instead, we should bundle a Tor binary with the download so that Tor is usable from the first run.

**Comment by rebron** [comment]
need more discussion for this one.

**Comment by bsclifton** [comment]
Closing as stale; let's re-open if we want to consider a separate bundled download (ex: brave.com/download-with-tor or something like this). We definitely can't bundle with the default download itself
