### ISSUE TITLE
Android bundle builds

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#15087]
Android apk builds are too large to upload to Google Play sometimes. Investigate building bundles instead to solve the problem.

**Comment by kjozwiak** [comment]
QA will run through https://github.com/brave/brave-browser/issues/15562, https://github.com/brave/brave-browser/issues/15563 & https://github.com/brave/brave-browser/issues/15561 using `aab` builds once we get the `1.24.x` RC's created.
