### ISSUE TITLE
[Android] Brave Shields causes page crash

### ISSUE THREAD

**Issue by Occhioverde** [brave/brave-browser#15088]
## Description 
In the latest version of Brave Nightly on the Play Store, Brave Shields causes several pages to crash.
Unfortunately, since Brave for Android does not show blocked elements within a specific site, I was unable to determine which tracker is the cause of the crash.
In any case, it is not possible to solve the problem by reducing the protections (i.e. by enabling either only cookies or only fingerprinting; it is necessary to disable the protection as a whole).

## Steps to reproduce 

   1. Open one of the websistes listed in the "Additional information" section
   2. Wait for the website to load and make sure that Brave Shields is enabled
   3. Notice the "Oh, snap" page

## Actual result 
The "Oh, snap" page is shown instead of the actual website:
![Screenshot_20210402-154317.jpg](https://user-images.githubusercontent.com/18429412/113420765-2b0ed000-93ca-11eb-9327-f1517c048fad.jpg)

## Expected result
The web page should be loaded without problems.

## Issue reproduces how often 
It only appears on certain websites (see the "Additional information" section for a non-exhaustive list)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Not tested
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM (HiSilicon Kirin 659)
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 8.0.0.340
   
## Brave version
Latest affected: Brave Nightly 1.24.41 with Chromium 90.0.4430.41

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

**Some examples of websites affected by the problem (I will add new elements as soon as I find them):**
- https://mail.google.com
- https://www.tgcom24.mediaset.it
- https://istitutoliberale.it

**Comment by Furax-31** [comment]
Same problem :

https://www.puregamemedia.fr/new-world/new-world-cles-alpha-fermee-nda-date-duree-et-horaire-de-lancement/

**Comment by srirambv** [comment]
Possibly related to #15085

**Comment by Occhioverde** [comment]
> Possibly related to #15085

Yes, it's possible: the tab also crashes when visiting IMDB.
In contrast to the Issue mentioned, however, I was also able to cause the problem in a normal tab and by opening a title page (e.g. this one: https://m.imdb.com/title/tt4574334/).
By the way, I noticed that the problem does not occur on the new version of the site (accessible via the "Check it out" link at the top left).

**Comment by srirambv** [comment]
Webview crashes on normal tab as well. Added a recording here https://github.com/brave/brave-browser/issues/15085#issuecomment-813155021.

Going to close this issue and add details in #15085 so things can be tracked in a single place
