### ISSUE TITLE
Storybook: Create Wallet Page Layout and Concept Tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#15098]
## Description 
Create the wallet page layout and add to concept in storybook for the Crypto Wallet Prototype.

![Screen Shot 2021-04-02 at 1 55 09 PM](https://user-images.githubusercontent.com/40611140/113449443-10812a80-93bb-11eb-8978-5e9a778b4cce.png)

You can find the specs for this component in Figma / Desktop Crypto Wallets.

Add the component too storybook with mock data for testing.

## Expected result:

Component should be visible and functional in Storybook

**Comment by TheFlute07** [comment]
Maybe the [CoinmarketCap API ](https://coinmarketcap.com/api/) can help for that.
![image](https://user-images.githubusercontent.com/81828658/113481966-c40e1b80-949c-11eb-8d33-0e02520c69e3.png)
