### ISSUE TITLE
Only apply top level domain blocking in aggressive mode, by default

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#15095]
Currently, when top level domain blocking is enabled, its applied regardless of other shields settings.  This issue is to have top level domain blocking be applied in the "aggressive" tracker blocking configuration.

Note: this may be changed in the v2 version of the feature, where we have the ability to automatically follow / debounce well known tracking URLs

**Comment by kjozwiak** [comment]
We'll use https://github.com/brave/brave-browser/issues/15242 for verifications 👍

**Comment by LaurenWags** [comment]
changing to `release-notes/include` per discussion with @rebron and @kjozwiak
