### ISSUE TITLE
[Android] Brave reveal specific Android device model in User-Agent string

### ISSUE THREAD

**Issue by sviluppoSoftware** [brave/brave-browser#15103]
## Description 

the patch that prevented revealing specific Android device model no longer works

## Steps to Reproduce

   1. go to https://browserleaks.com/ip
   2. scroll down to HTTP Headers section 
   3. in User-Agent string you can see the Android device model in use

## Actual result:

User-Agent string show  specific Android device model 

## Expected result:
User-Agent string don't show  specific Android device model 

## Reproduces how often: 

always

## Brave version (info found on brave://version)

1.22.69 and above, maybe earlier versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? i dont' know
- Can you reproduce this issue with the dev channel? i dont' know
- Can you reproduce this issue with the nightly channel?  i dont' know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome?  i dont' know

**Comment by ristein** [comment]
what a great privacy browser!

**Comment by sviluppoSoftware** [comment]
what a helpful comment!

**Comment by srirambv** [comment]
This is fixed as part of #14740. It will probably land soon on a channel and get released. Thanks for the report
