### ISSUE TITLE
Make brave beta and edge snaps public

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#15108]
#### Description 
I'm a user that tend to use multiple browsers due use cases additional to profiles (profiles sometimes annoying because they may get opened as unexpected or unexpected different profiles on next launch) but different browsers are perfect solution. Other hand **beta and edge are contain newer features and security improvements so it's better than to use another stable** chromium fork and able to **report bugs to brave** early then has benefit for both users and maintainers :)

I saw brave has published stable, beta and edge versions on snap store and we cannot see other versions for search except stable https://github.com/brave/brave-browser/issues/11184#issuecomment-703443195

![image](https://user-images.githubusercontent.com/81799342/113520598-607c0f00-95be-11eb-8861-df4c517a4059.png)

#### Request
I thought to open new issue because several users have commented and requested it but no action has taken, Make brave beta and edge snaps public

**Comment by IniUe** [comment]
https://github.com/brave/brave-browser/issues/1007

**Comment by rebron** [comment]
cc: @wknapik

**Comment by bsclifton** [comment]
This is live here:
https://github.com/brave/brave-browser-snap/

There are different branches for the different versions
