### ISSUE TITLE
Brave Can't Download On Windows 7 VM (security vulnerability)

### ISSUE THREAD

**Issue by CaptainCrumb999RobloxYT** [brave/brave-browser#15100]
Hello,

So Recently When I Installed My LEGAL Copy Of Windows 7 and downloaded Chrome, then I set Google Chrome up and then TRIED to install brave, but said this:

https://imgur.com/d8negSx

But It Said That I can't visit it right now (because it uses HSTS)

It said it's temporary, so I may have to wait a while.

P.S.

I didn't want to make a hackerone account just for this so I used github.

P.S.S.

I typed this on that same VM I screenshoted.

**Comment by jonathansampson** [comment]
@CaptainCrumb999RobloxYT What do you see in the _Advanced_ view?

**Comment by diracdeltas** [comment]
do you have any kind of software installed (antivirus for instance) that might affect TLS connections?

**Comment by CaptainCrumb999RobloxYT** [comment]
"laptop-updates.brave.com normally uses encryption to protect your information. When Google Chrome tried to connect to laptop-updates.brave.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be laptop-updates.brave.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit laptop-updates.brave.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later."


I also don't have any antivirus installed, all I have is Windows Defender.

*please note that my host machine has brave installed, and all I installed on this machine is chrome, the 3d maze screensaver, and a wallpaper that i thought was hd but wasn't (also my host machine's wallpaper, but its drag and drop.)*

The Last Time I Installed Brave on a computer was yesterday, on a Windows 8.1 HP Stream 8.

**Comment by rebron** [comment]
@CaptainCrumb999RobloxYT Can you try adding https:// to laptop-updates.brave.com and see if that works?
cc: @mihaiplesa

**Comment by mihaiplesa** [comment]
Yes, a screenshot of the certificate details would help.

**Comment by CaptainCrumb999RobloxYT** [comment]
(host machine) Ok, I'll go do that.

**Comment by CaptainCrumb999RobloxYT** [comment]
(guest machine) Didn't work. it backslashes "https"
Are there any other ways I can do this?

**Comment by CaptainCrumb999RobloxYT** [comment]
Oh Yeah, Forgot the Screenshot.

**Comment by CaptainCrumb999RobloxYT** [comment]
https://imgur.com/CqCXZMo

**Comment by bsclifton** [comment]
@CaptainCrumb999RobloxYT what version of Chrome / Edge are you trying with?

**Comment by CaptainCrumb999RobloxYT** [comment]
> @CaptainCrumb999RobloxYT what version of Chrome / Edge are you trying with?

I'm using the latest version of Chrome: (Google Chrome 89)

I also haven't downloaded Edge, because I don't like MS Edge.

**Comment by bsclifton** [comment]
Closing as there hasn't been an update in a while. 

Let's re-open if there is more information.  We did run into an issue with Omaha recently (Sep 21) but that would only affect new installs and potentially updates... not downloads from the website itself
