### ISSUE TITLE
Brave Shield not working on Google.com

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#15106]
## Description 
Brave Shield shows some google.com top ads. plz check the screenshot.

## Steps to Reproduce

   1.  Enable Brave shield
   2.  Search in google.com
   3. Example search term : thar car
   4. Go to 2nd page if no ad on first page results. Or use a new profile. 

## Actual result:
![2021-04-02_12-16-05](https://user-images.githubusercontent.com/46480489/113500125-30d6f380-9539-11eb-9c67-bc1338dee194.jpg)
![Screenshot 2021-04-04 114836](https://user-images.githubusercontent.com/46480489/113500464-c96e7300-953b-11eb-8421-01997783e9be.png)

## Expected result:
Without google top ad result

## Reproduces how often: 
Easily reproduced, [ based on search term and advertiser]

## Brave version (brave://version info)

Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Windows 10 OS Version 2009 (Build 19042.870)
JavaScript | V8 8.9.255.24
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --disable-features=SignedExchangeSubresourcePrefetch,DirectSockets,TextFragmentAnchor,AutofillServerCommunication,SafeBrowsingEnhancedProtectionMessageInInterstitials,IdleDetection,AutofillEnableAccountWalletStorage,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,LangClientHintHeader,NetworkTimeServiceQuerying,WebOTP,NotificationTriggers,TabHoverCards,PrivacySettingsRedesign,SafeBrowsingEnhancedProtection --enable-dom-distiller --enable-features=LegacyTLSEnforced,WebUIDarkMode,SafetyTip,WinrtGeolocationImplementation,AutoupgradeMixedContent,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --extension-content-verification=enforce_strict --extensions-install-verification=enforce --lso-url=https://no-thanks.invalid --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --variations-server-url=https://variations.brave.com/seed --enable-features=ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,SafetyTip,WinrtGeolocationImplementation,AutoupgradeMixedContent,WebUIDarkMode,LegacyTLSEnforced --disable-features=SafeBrowsingEnhancedProtection,PrivacySettingsRedesign,TabHoverCards,NotificationTriggers,WebOTP,NetworkTimeServiceQuerying,LangClientHintHeader,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,IdleDetection,AutofillServerCommunication,SafeBrowsingEnhancedProtectionMessageInInterstitials,TextFragmentAnchor,AutofillEnableAccountWalletStorage,DirectSockets,SignedExchangeSubresourcePrefetch --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\MANIKANDAN\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 7146a73c-3f4a17df

## Version/Channel Information:
Not tested

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?  Not tested
- Can you reproduce this issue with the nightly channel? not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not applicable
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? Not tested

**Comment by rebron** [comment]
@manikandancode Can you set to aggressive mode and see if that works for you?
cc: @srirambv I'm not seeing these ads, maybe regional.

**Comment by srirambv** [comment]
Nope not seeing them as well. Also I don't see the shields count go up so high for second page on search results

**Comment by ryanbr** [comment]
Aggressive mode should help @manikandancode

**Comment by manikandancode** [comment]
Yes maybe regional. check below proof.

![ad_proof](https://user-images.githubusercontent.com/46480489/113817541-1e0c2b00-9794-11eb-9e89-4eeb4f25d919.gif)

Ads are not showing on Aggressive mode. but it should work on brave default standard mode. 
Or Brave work with google to show ads (Acceptable Ads program) !!!???

![maruthi](https://user-images.githubusercontent.com/46480489/113817803-85c27600-9794-11eb-8513-d0965fe34daf.gif)

**Comment by ryanbr** [comment]
Thanks for the gifs @manikandancode 

1p ads on google in shields=standard this is expected. We offered aggressive mode to avoid this (for people who want complex blocking).  

The fix is to enable Aggressive mode on google  or can be set globally in `brave://settings/shields`

**Comment by manikandancode** [comment]
Now 4 ads on google in shields=standard .  Block these ads in default mode. or make aggressive as default.
![2021-08-31 07%3a44%3a46 050152161](https://user-images.githubusercontent.com/46480489/131547606-86a1dccb-9c53-4101-bf9d-248edf7945db.gif)
