### ISSUE TITLE
Loading desktop version of this site shows local node button on Android

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15118]
## Description 
Hide IPFS interstitial page when loading an IPFS URI for the first time

## Steps to reproduce 

   1. Clean install 1.24.43 nightly build
   2. Load `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
   3. Brings up interstitial page to use public gateway
   4. Load desktop page for the same interstitial page from menu
   5. Brings up setting up local node (fails to install)
   6. Select public gateway, loads `https://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq.ipfs.dweb.link/wiki/Vincent_van_Gogh.html`

## Actual result 

https://user-images.githubusercontent.com/17010094/113575892-7f0df480-9616-11eb-9bc6-752872478ca2.mp4

## Expected result
Should not show the IPFS Interstitial page but instead load the page if IPFS setting is enabled in Privacy

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.24.43

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @bbondy @spylogsster @SergeyZhukovsky

**Comment by stephendonner** [comment]
Verified `PASSED` using Android 9 on a Google Pixel XL, arm64, with Brave `1.25.51, Chromium 90.0.4430.93`

Steps:

1.  clean-installed `1.25.51` build
2.  loaded `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
3.  brought up interstitial page to use public gateway
4.  loaded desktop page for the same interstitial page from menu
5.  confirmed no `Use a local node` option appeared
6.  selected `Use a public gateway`, loaded `https://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq.ipfs.dweb.link/wiki/Vincent_van_Gogh.html` without issue, on both desktop and mobile views


example | example | example | example
---------|----------|---------|----------
![Screenshot_20210505-145030](https://user-images.githubusercontent.com/387249/117214603-fbc8f580-adb1-11eb-98b0-2706b8ba888c.png) | ![Screenshot_20210505-145052](https://user-images.githubusercontent.com/387249/117214604-fc618c00-adb1-11eb-94f2-fe66f311141d.png) | ![Screenshot_20210505-145105](https://user-images.githubusercontent.com/387249/117214606-fc618c00-adb1-11eb-9a1b-dd3ea82724dd.png) | ![Screenshot_20210505-145114](https://user-images.githubusercontent.com/387249/117214609-fc618c00-adb1-11eb-8bb6-9942a1acbc97.png)
