### ISSUE TITLE
Non-removable sites under "Sites that can always use cookies"

### ISSUE THREAD

**Issue by pitsi** [brave/brave-browser#15122]
## Description 
I was looking for a way to remove that new, annoying popup message on youtube and I came accross this 
https://old.reddit.com/r/uBlockOrigin/comments/ma7ikl/is_it_possible_to_block_google_consent_redirect/gt4ojr0/

So I headed to brave://settings/cookies > "sites that can never use cookies" to add the stuff mentioned in the howto. And I noticed I already have four sites under "sites that can always use cookies": noip, xda, a local one (192.168.1.x) and one that I can't mention. I pressed the recycle bin icon next to them to delete them, but nothing happened.
If it helps, I have set brave to block third party cookies. 

## Steps to Reproduce
   1. Go to brave://settings/cookies
   2. Scroll down to sites that can always use cookies.
   3. If there is any, click the recycle bin icon next to it to delete it.

## Actual result:
Nothing is deleted!

## Expected result:
Sites should be deleted from that list when the recycle bin icon is pressed.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
```
Brave	1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
Revision	1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS	Linux

```

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No idea, not using it.
- Can you reproduce this issue with the nightly channel? No idea, not using it.

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Debian testing/unstable x64, brave 1.22.71. Deletion works fine when you click the recycle bin for "sites that can never use cookies".

**Comment by ryanbr** [comment]
Blocking `||consent.google.com^` in brave://adblock may help, but it'll break youtube comments (and probably other things

**Comment by ryanbr** [comment]
Same as this? https://github.com/brave/brave-browser/issues/15082

**Comment by pitsi** [comment]
Well, no, it is not the same as the other issue. In fact, the only thing that is common between the two is my reference to `consent.google.com`, nothing more.
I have not mentioned adblocking anywhere and NONE of the 4 urls that I mentioned have to do anything with google. Can you please reopen it?

**Comment by pitsi** [comment]
Screenshots from brave and chromium, under the same menu, to make my point clear.

Chromium 89.0.4389.114, under windows 7 x64, greek locale
![1](https://user-images.githubusercontent.com/5880037/113718304-2eb99400-96f5-11eb-9b8e-4da4fe94d621.png)

Brave 1.22.71, under linux x64, english locale
![2021-04-06-155619_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/113718479-59a3e800-96f5-11eb-9aa6-d0e1726d4778.png)

I intentionally put the same sites at the same place, because my chromium in windows also had no sites in there. The recycle bin button works as it should on chromium, but does not work in brave as I mentioned above. Thus I corrected the "does it reproduce in chrome" above to no.
It has nothing to do with google and what is mentioned in ubo's reddit, it is only related to brave.

**Comment by pitsi** [comment]
Nothing changed after yesterdays upgrade to 1.22.72.
Since my issue was closed as duplicate, although it is not, I will keep spamming the report until it gets "magically" solved one day after some random update (hopefully).

**Comment by pitsi** [comment]
Same thing in 1.23.71. I thought the major upgrade to chromium 90.x would fix it, but no.

**Comment by pitsi** [comment]
Same thing in 1.23.73.

**Comment by pitsi** [comment]
Same thing in 1.23.75.

**Comment by pitsi** [comment]
Same thing in 1.24.82.

**Comment by bsclifton** [comment]
Re-opened as the issue is still happening

@pitsi reading through prior comments; basically the sites shown... nothing happens when you click the trash can?

**Comment by pitsi** [comment]
I will. Thanks for mentioning the correct duplicate issue, because what I describe has nothing to do with issue 15082.
