### ISSUE TITLE
Open in a new tab group  is the only option on long press context menu

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15120]
## Description 
Open in a new tab group is the only option on long press context menu

## Steps to reproduce 

   1. Open a web page in a new tab
   2. Long press on a link to open context menu
   3. Only has `Open in a new tab group`

## Actual result 
Open in a new tab group is the only option on long press context menu

## Expected result
Should still show option to open links in new tabs rather than grouping it together

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.24.43

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? Yes same behaviour in Chrome as well

### Additional information

cc: @samartnik @SergeyZhukovsky

**Comment by HunterMeyer** [comment]
Here's a screenshot.

![Screenshot_20210416-185309_Brave](https://user-images.githubusercontent.com/4690516/115091257-0ac03480-9ee5-11eb-96c3-7e4a68705825.jpg)

**Comment by HunterMeyer** [comment]
I disabled each of these flags to get this issue resolved and to remove the tab "grid" layout:
- chrome://flags/#tabbed-app-overflow-menu-icons
- chrome://flags/#enable-tab-grid-layout
- chrome://flags/#enable-tab-groups
- chrome://flags/#enable-tab-groups-continuation
- chrome://flags/#enable-tab-groups-ui-improvements

**Comment by vroomik** [comment]
Brave 1.34 on Chromium 97.0.4 on Android 11
It's even **worse** now as flag - 
chrome://flags/#enable-tab-groups 
 _doesn't exist anymore_
Whilst searching for "tab group" in chrome://flags/ only those are available:
chrome://flags/#enable-tab-groups-continuation  
chrome://flags/#enable-tab-grid-layout   
Really annoying behaviour. Solution? Add "open new tab" in context menu after long press

**Comment by samartnik** [comment]
PR caused issues, needs to be re-done

**Comment by Uni-verse** [comment]
Verification **PASSED** on release branch `1.36.105, Chromium 99.0.4844.45`
Device: `Samsung Galaxy S21` | `Android 12` | `ARM`

- Able to open link in new tab from context menu
- All context menu items are functional

1 | 2
-|-
![Screen Shot 2022-02-24 at 2 37 04 PM](https://user-images.githubusercontent.com/17885425/155619530-577cb2a6-0c1b-4079-8884-ca5360fcc512.png) | ![Screen Shot 2022-02-24 at 2 39 26 PM](https://user-images.githubusercontent.com/17885425/155619531-2265fec7-194d-4d4b-a4c2-c701a52c4507.png)
