### ISSUE TITLE
DNS_PROBE_POSSIBLE

### ISSUE THREAD

**Issue by jimrs** [brave/brave-browser#15125]
## Description 

I can't for the end of me find out anything more about this. Whatever site I try to reach, it always says "this site can't be reached" with an errror DNS_PROBE_POSSIBLE. For e.g. google.com it also says "google.com’s DNS address could not be found. Diagnosing the problem.". Firefox work, qutebrowser works, pinging 8.8.8.8 works, pinging google.com works, chatting on Messenger (desktop app) works, but browsing sites doesn't.
I tried disabling extensions, resetting settings to defaults, completely wiping the application and reinstalling 3 times, but it doesn't help (somehow, Brave still remembers my open sites through those reinstalls??).
If I find out IP adress of google.com through the dig command for example, and paste that adress into Brave, it will instantly change to google.com and the DNS_PROBE_POSSIBLE error.
I don't know if it is related, but I flushed dns cache recently, changed the hostname of my PC too. But again, other browser works.

## Steps to Reproduce

   1.  ???
   2.  ???
   3.  ???

## Actual result:

![image](https://user-images.githubusercontent.com/15998217/113600957-08d2b780-9641-11eb-840f-f2838a62d5c3.png)

## Expected result:
Actually being able to browse.

## Reproduces how often: 

???

## Brave version (brave://version info)

```
Brave	1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)
Revision	1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS	macOS Version 10.14.6 (Build 18G8022)
JavaScript	V8 8.9.255.24
User agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser -psn_0_12229545 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PasswordImport,ReducedReferrerGranularity,WebUIDarkMode,SafetyTip,AutoupgradeMixedContent,PrefetchPrivacyChanges,LegacyTLSEnforced --disable-features=TextFragmentAnchor,TabHoverCards,AutofillServerCommunication,DirectSockets,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,AutofillEnableAccountWalletStorage,WebOTP,NotificationTriggers,LangClientHintHeader,NetworkTimeServiceQuerying,SafeBrowsingEnhancedProtection,SignedExchangeSubresourcePrefetch,PrivacySettingsRedesign,IdleDetection,SafeBrowsingEnhancedProtectionMessageInInterstitials --flag-switches-begin --load-media-router-component-extension=0 --flag-switches-end
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/jim/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations	7146a73c-3f4a17df
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Don't know.
- Can you reproduce this issue with the beta channel? Don't know.
- Can you reproduce this issue with the nightly channel? Don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? Don't know.

**Comment by jimrs** [comment]
nvm fixed it

**Comment by KamuelaFranco** [comment]
> nvm fixed it

Haha, great, _how_ did you fix it?

**Comment by Killdozer666** [comment]
> 

Tried this, but it didn’t work. Same as OP.
Fresh install of Brave 1.34.81 On Ubuntu 20.04.3

**Comment by Killdozer666** [comment]
> > nvm fixed it
> 
> Haha, great, _how_ did you fix it?
> 
> **Update:** I've managed to fix it by playing with `Settings -> Privacy and security -> Security -> Use secure DNS`. Try toggling that on and off and changing the service provider you use.

I tried this, but It didn't work.  Brave will give the same error no matter the address.

All other browsers and applications connect without a problem.

This is a fresh install of 20.04.3  I guess I have to install Firefox, I cant wast more time of this, i got work to do.

Thanks for the suggestion.

**Comment by HansBambel** [comment]
> > nvm fixed it
> 
> Haha, great, _how_ did you fix it?
> 
> **Update:** I've managed to fix it by playing with `Settings -> Privacy and security -> Security -> Use secure DNS`. Try toggling that on and off and changing the service provider you use.

This worked for me when changing to Cloudflare DNS server

**Comment by Mariosyian** [comment]
> > nvm fixed it
> 
> Haha, great, _how_ did you fix it?
> 
> **Update:** I've managed to fix it by playing with `Settings -> Privacy and security -> Security -> Use secure DNS`. Try toggling that on and off and changing the service provider you use.

I tried this and originally did not work. Tried it again (simply toggle off then back on), but this time loaded the website by pressing Ctrl + Shift + R to fetch it fresh (i.e. tell Brave to not use the cached version).

**Comment by rashmitpankhania** [comment]
I did reset the settings and worked
Settings -> Reset Settings

**Comment by mrmetaverse** [comment]
hm... I am a linux user (Arch) and I found the only way to make it work was to turn on my VPN (ProtonVPN is the one I am using now) at the system level (not using a browser plugin). 

I don't know why it fixed it but it did.

**Comment by AhmadAliShinwari** [comment]
Solution: 
Settings -> Privacy and security -> Security -> Use secure DNS ->on/off ->on -> with [custome] -> cloudflare(1.1.1.1).

**Comment by jimrs** [comment]
> Solution: Settings -> Privacy and security -> Security -> Use secure DNS ->on/off ->on -> with [custome] -> cloudflare(1.1.1.1).

cloudflare is disgusting tho, use quad9

**Comment by hexxone** [comment]
Issue still persists....
I have a Adguard Home instance running in my LAN.
I set the DNS Serve rfor the whole LAN using DHCP.
In MacOs in the network, the DNS server shows up correctly.
When using `nslookup my.local.server` in the terminal it works normally and returns `Address: 192.168.1.2`

But for some cursed reason, Brave simply cannot find this DNS Address. I will always get `DNS_PROBE_POSSIBLE ` even though it _should_ be found. I have Secure DNS disabled, but therre isnt even a way to check which DNS is using exactly it seems?

Verry annoying.....

**Comment by Natez868** [comment]
> Issue still persists.... I have a Adguard Home instance running in my LAN. I set the DNS Serve rfor the whole LAN using DHCP. In MacOs in the network, the DNS server shows up correctly. When using `nslookup my.local.server` in the terminal it works normally and returns `Address: 192.168.1.2`
> 
> But for some cursed reason, Brave simply cannot find this DNS Address. I will always get `DNS_PROBE_POSSIBLE ` even though it _should_ be found. I have Secure DNS disabled, but therre isnt even a way to check which DNS is using exactly it seems?
> 
> Verry annoying.....

MY FIX!!!

I installed a fresh Linux Mint and installed the Brave Browser using software manager had this is where I had this annoying issue. I uninstalled Brave Browser from the software manager and then reinstalled it using the command on Brave website 

curl -fsS https://dl.brave.com/install.sh | sh    

and this is how I got it to work

None of the other stuff I tried worked for me. Hope this works, let me know if it did.

**Comment by kerall117** [comment]
This ended up being the same issue for me as for @Natez868. I must have installed Brave from the Discover app, which used a snap package. After removing that and installing the apt package the issue was immediately resolved.
