### ISSUE TITLE
BAT disappeared

### ISSUE THREAD

**Issue by MGT410** [brave/brave-browser#15128]
## Description 
<My monthly brave rewards didn't show up in my wallet after clicking the claim button. It's not in my wallet and there is no indication I even confirmed it.>

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by hollons** [comment]
Hi @MGT410, what OS and Brave version are you on? If you're on Android by chance, does your device pass Safetynet? You can test here: https://play.google.com/store/apps/details?id=org.freeandroidtools.safetynettest&hl=en_US&gl=US.
