### ISSUE TITLE
hard refresh of Tor tab usually does not get new IP

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1512]
## Description 
Found while testing 'New circuit' from https://github.com/brave/brave-browser/issues/1270#issuecomment-425646598 Most of the time when doing a hard refresh of Tor tab a new IP is not fetched. However, 'New Tor Identity' works each time.

## Steps to Reproduce

   1. Open Tor window.
   2. Navigate to check.torproject.org or whatsmyip.org
   3. Do hard refresh of the page --> IP may or may not change
   4. Repeat step 3 a few times. --> IP does not change
   5. Open a new tab in Tor window. Navigate to same site. --> same IP is displayed.

## Actual result:
IP generally does not change. If you use 'New Tor Identity' you will get a new IP each time.

## Expected result:
New IP without having to use 'New Tor Identity'.

## Reproduces how often: 
fairly easily, but sometimes IP does change.

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes
- Does it reproduce on browser-laptop? no, hard refresh on 0.25.0 generates new IP

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Reproduced by @srirambv

**Comment by tomlowenthal** [comment]
This functionality hasn't been implemented yet: #1137 is the open issue for this work.
