### ISSUE TITLE
Apply brave design to native UI toolkit

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15133]
https://github.com/brave/brave-core/pull/8253#pullrequestreview-628050132

- Checkbox https://www.figma.com/file/z9wmg2FCwuXx9FLbDo5avJ/Platform-UI-Brave-desktop?node-id=105%3A244
- Buttons https://www.figma.com/file/z9wmg2FCwuXx9FLbDo5avJ/Platform-UI-Brave-desktop?node-id=1011%3A0

and more such as radio buttons

**Comment by rebron** [comment]
Closing as stale.
