### ISSUE TITLE
Enable re-ordering of sidebar items

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15135]
This is sub issue of https://github.com/brave/brave-browser/issues/14980

Enable sidebar feature via brave://flags
Re-orders item by drag and drop.
Re-ordering in one browser window is synced with other browser windows. but active item is not synced.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.25.46 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3 (Build 20E232)

Confirmed I was able to:

1.  enable the `Sidebar` feature via `brave://flags`
2. drag and drop all Sidebar items except for the `+`, which remained in place
3. see item reordering in real time, across tabs, after the drag event finished
4. open an item and still re-arrange other items via drag and drop, without affecting the other tab, nor the current tab, but updates to the ordering still worked
5. add an item (`GitHub`) to the Sidebar and have it both appear on the other tab, as well as drag and drop-rearrange successfully

![sidebar-reordering](https://user-images.githubusercontent.com/387249/116482825-c87ae980-a83a-11eb-9399-6ac36b365379.gif)
