### ISSUE TITLE
allowing users to change default search engine for Tor Window

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1513]
## Description 

We currently set DDG as the default search engine for `Tor Window` but don't give the user the capability to switch the default search engine. If you pick another search engine from the list, it will just switch back to DDG and won't accept the users change.

## Steps to Reproduce

   1.  launch brave and open a new Tor Window via `Profile menu` -> `Open Tor Window`
   2.  once opened, click on `Search preferences`
   3.  attempt to pick something else from the `Search engine used in the address bar`
   4. Go into `chrome://settings/searchEngines` and attempt to make another engine the default

## Actual result:

![defaultsearch](https://user-images.githubusercontent.com/2602313/46778566-45c4ca00-cce2-11e8-843d-edda01a8861e.gif)

## Expected result:

Users should be able to change their default search engines under Tor and shouldn't be forced to use DDG which is set as default.

## Reproduces how often: 

100% reproducible when going through the above STR.

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, currently reproducible with both `dev` and `beta` builds:

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

Brave | 0.56.2 Chromium: 70.0.3538.35 (Official Build) dev (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

- Does it reproduce on browser-laptop?

Nope, different implementation in b-l. Used Tor tabs rather than a Tor Window.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified search engine list is shown in Tor windows under settings
* Verified changing search engine sets the new search engine as default search engine
* Verified the change is retained across new Tor windows that are opened

**Comment by TheGrave** [comment]
Version 1.58.135 on Linux. Both search engines set to DuckDuckGo in settings. When I open a Tor window Brave search engine is opened instead. Regression?
