### ISSUE TITLE
Cosmetic filter not work 

### ISSUE THREAD

**Issue by Furax-31** [brave/brave-browser#15148]
## Description  
Cosmetic filter not work on website

## Issue reproduces how often  
Go to https://www.passeportsante.net/huiles-vegetales-g152/Fiche.aspx?doc=hydrater-levres-huiles-vegetales

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
Nightly 1.24.49

![Screenshot_20210406-180857_Brave_-_Nightly](https://user-images.githubusercontent.com/61207108/113742711-308a5400-9703-11eb-844c-d1d71d9f1d37.png)
![Screenshot_20210406-180848_Brave_-_Nightly](https://user-images.githubusercontent.com/61207108/113742718-31bb8100-9703-11eb-9e66-55b42398865b.png)
![Screenshot_20210406-180839_Brave_-_Nightly](https://user-images.githubusercontent.com/61207108/113742722-32541780-9703-11eb-8d13-ea504cd932d7.png)

**Comment by ryanbr** [comment]
Thanks for the report, just submitted a PR. Waiting on approval.

https://github.com/AdguardTeam/AdguardFilters/pull/79667

Also enable `AdGuard Français` in `brave://adblock`

**Comment by ryanbr** [comment]
Give it 24-48hrs. Also enable AdGuard Français in `brave://adblock` will keep ticket open to confirm

**Comment by Furax-31** [comment]
I'll keep you posted in 24-48hrs @ryanbr

**Comment by Furax-31** [comment]
@ryanbr A cosmetic filter is still missing at the top of the web page.

![Screenshot_20210408-072518_Brave_-_Nightly](https://user-images.githubusercontent.com/61207108/113972949-d17c2a80-983b-11eb-9f95-d54862ca2338.png)

**Comment by Furax-31** [comment]
@ryanbr  Problem solved
