### ISSUE TITLE
Support Unstoppable Domains and ENS on Android

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#15159]
## Description 
Enable the support of Unstoppable Domains and ENS via DoH on Android.
For Unstoppable Domains, we will also support resolving domains with IPFS records via Ethereum network.

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from the description, on Brave Beta `1.24.76, Chromium 90.0.4430.85` on Google Pixel XL, Android 9, arm64.

example | example | example | example | example | example | example | example | example | example | example | example
---------|---------|----------|----------|---------|----------|---------|----------|---------|----------|---------|---------
![Screenshot_20210429-095631](https://user-images.githubusercontent.com/387249/116591023-3ffc5780-a8d3-11eb-9cc7-eb2264017a59.png) | ![Screenshot_20210429-095652](https://user-images.githubusercontent.com/387249/116591024-4094ee00-a8d3-11eb-84b4-6123d9ed8474.png) | ![Screenshot_20210429-095704](https://user-images.githubusercontent.com/387249/116591025-412d8480-a8d3-11eb-8853-0537271abf4a.png) | ![Screenshot_20210429-095727](https://user-images.githubusercontent.com/387249/116591027-412d8480-a8d3-11eb-85f0-901e86ce3d06.png) | ![Screenshot_20210429-095732](https://user-images.githubusercontent.com/387249/116591028-41c61b00-a8d3-11eb-9c33-0c6d40804a75.png) | ![Screenshot_20210429-095757](https://user-images.githubusercontent.com/387249/116591029-41c61b00-a8d3-11eb-8372-742cd7d25d2b.png) | ![Screenshot_20210429-095831](https://user-images.githubusercontent.com/387249/116591031-425eb180-a8d3-11eb-8d06-c19fa5f4227d.png) | ![Screenshot_20210429-100111](https://user-images.githubusercontent.com/387249/116591033-42f74800-a8d3-11eb-8a1c-63b82c27aac7.png) | ![Screenshot_20210429-100148](https://user-images.githubusercontent.com/387249/116591035-42f74800-a8d3-11eb-9988-caa6844118d9.png) | ![Screenshot_20210429-100202](https://user-images.githubusercontent.com/387249/116591039-42f74800-a8d3-11eb-9558-82b091d89aaf.png) | ![Screenshot_20210429-100243](https://user-images.githubusercontent.com/387249/116591040-438fde80-a8d3-11eb-8c36-894d23414cb6.png) | ![Screenshot_20210429-100253](https://user-images.githubusercontent.com/387249/116591042-438fde80-a8d3-11eb-8728-4bcf088008c0.png)
