### ISSUE TITLE
Remove DDG UA

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#15156]
After talking with DDG, @lukemulks has confirmed that we no longer need to send DDG a custom, "includes Brave" UA.

This issue is to remove the DDG UA special case.

**Comment by lukemulks** [comment]
+1 

bumping this up for visibility

**Comment by pes10k** [comment]
Sounds good, will work with @ShivanKaul to get this sorted.  Thanks @lukemulks !

**Comment by ShivanKaul** [comment]
Just FYI, I've created a PR to remove the code that adds "Brave" to the UA string for Netflix and DDG that I'll be merging in soon. 

**Before:**
![image](https://user-images.githubusercontent.com/5284154/131393257-eb12f109-419c-4cd9-895c-ec751f907c8c.png)

**After:**
![image](https://user-images.githubusercontent.com/5284154/131393679-26e7fb14-4851-42ec-86c6-12efaafcccc8.png)

**Comment by anthonypkeane** [comment]
Does iOS need to implement this also @pes10k ?

**Comment by pes10k** [comment]
I dont know if iOS is currently sending it, but if it is, we should stop :)

**Comment by pes10k** [comment]
I dont see anything like that in the iOS code base, but iOS team would know better

**Comment by stephendonner** [comment]
**Verified `PASSED`** using 


Brave | 1.31.28 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 12.0 (Build 21A5506j)

## Steps:
1. clean profile
2. launched Brave
3. opened Developer Tools, Network tab
4. loaded `duckduckgo.com` and `netflix.com`
5. examined the HTTP request's user-agent string for both

Confirmed `"Brave"` as a string in UAs has been removed:

### With fix (`nightly`):

duckduckgo.com | netflix.com
------------------|-----------
<img width="1312" alt="Screen Shot 2021-09-08 at 6 47 17 PM" src="https://user-images.githubusercontent.com/387249/132608986-6a645c19-58d2-4832-9b53-5a95dd7675a8.png"> | <img width="1312" alt="Screen Shot 2021-09-08 at 6 47 03 PM" src="https://user-images.githubusercontent.com/387249/132609008-11c8499b-c05a-49cb-91e1-45353c35b07b.png">

### Without fix (`beta`):

duckduckgo.com | netflix.com
------------------|------------
<img width="1792" alt="Screen Shot 2021-09-08 at 6 44 56 PM" src="https://user-images.githubusercontent.com/387249/132609046-872388f5-5c91-4eab-94c5-3ab00c0b4084.png"> | <img width="1792" alt="Screen Shot 2021-09-08 at 6 45 29 PM" src="https://user-images.githubusercontent.com/387249/132609076-798f4bf7-769d-4836-84ec-cf8d2812304c.png">

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.31.67 x64 beta build
- Verified Brave UA is removed

DDG | Netflix
-- | --
![image](https://user-images.githubusercontent.com/17010094/135992189-ab171d66-d4dd-40f6-9162-29e995a3509f.png) | ![image](https://user-images.githubusercontent.com/17010094/135992441-f2477883-5489-44da-bf46-9bc309f86caa.png)

--------------
Verification passed on Oppo Reno 5 with Android 11 running 1.31.67 x64 beta build
- Verified Brave UA is removed

DDG | Netflix
-- | --
![image](https://user-images.githubusercontent.com/17010094/135992666-6b50cee6-6a6a-45cd-825d-40ab8863a14e.png) | ![image](https://user-images.githubusercontent.com/17010094/135992733-ab680dc3-5b15-4083-a336-a097741378ed.png)
