### ISSUE TITLE
Support resolution of unstoppable domains with IPFS records via Ethereum

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#15158]
## Description 
This issue is to track adding support of resolution of unstoppable domains with IPFS records via Ethereum network directly.
We'll be calling ProxyReader.GetMany from Unstoppable Domains to retrieve IPFS records and redirect to the target IPFS URI.
After that, IPFS support in Brave will take over the rest.

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8456 on build

Brave | 1.25.22 Chromium: 90.0.4430.72 (Official Build) nightly (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. Went to settings, opened drop-down of ENS resolve method settings, and verified it did NOT have Ethereum.
2. Changed the resolve method of Unstoppable Domains to `Ethereum`
3. Went to `brave://settings/ipfs`, set the `Method to resolve` to `Gateway`
4. Visited `brave.crypto` and confirmed the URL `https://bafybeid6rntsjiydicxj5cnmnqonbvwv35lrjgd6dngskptra3oa2otxxm.ipfs.dweb.link/` was loaded via IPFS 

example | example | example
---------|---------|---------
<img width="1103" alt="Screen Shot 2021-04-16 at 12 32 54 PM" src="https://user-images.githubusercontent.com/387249/115076188-0aa64180-9eb1-11eb-996e-a7c9ef84647c.png"> | <img width="1103" alt="Screen Shot 2021-04-16 at 12 33 16 PM" src="https://user-images.githubusercontent.com/387249/115076277-33c6d200-9eb1-11eb-9bf1-a748d7026e59.png"> | <img width="1217" alt="Screen Shot 2021-04-16 at 12 34 14 PM" src="https://user-images.githubusercontent.com/387249/115076314-3f19fd80-9eb1-11eb-8654-47a727257ade.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.25.53 Chromium: 90.0.4430.93 (Official Build) beta (64-bit)
-- | --
Revision | `4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}`
OS | Windows 10 OS Version 2009 (Build 19042.867)

- Verified Ethereum is an option under Unstoppable Domain resolution 
![image](https://user-images.githubusercontent.com/17010094/117274762-464f7e00-ae55-11eb-9064-1c33fa756ea7.png)
- Verified ENS doesn't have an entry for Ethereum in dropdown
![image](https://user-images.githubusercontent.com/17010094/117275050-8ca4dd00-ae55-11eb-8251-c29ec5b27ecd.png)
- Verified setting UD to resolve via Ethereum and setting IPFS to gateway loads the page using IPFS Public gateway(dweb.link)

![image](https://user-images.githubusercontent.com/17010094/117275118-a0504380-ae55-11eb-85bd-16a92c06dc92.png) | ![image](https://user-images.githubusercontent.com/17010094/117275282-c8d83d80-ae55-11eb-96c0-a36edede05f1.png)
-- | --

----------

Verification passed on 

Brave | 1.25.53 Chromium: 90.0.4430.93 (Official Build) beta (64-bit)
-- | --
Revision | `4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}`
OS | Linux

- Verified Ethereum is an option under Unstoppable Domain resolution 
![image](https://user-images.githubusercontent.com/17010094/117277136-78fa7600-ae57-11eb-817b-444a41542dd2.png)

- Verified ENS doesn't have an entry for Ethereum in dropdown
![image](https://user-images.githubusercontent.com/17010094/117277180-84e63800-ae57-11eb-9297-1cb9279be605.png)

- Verified setting UD to resolve via Ethereum and setting IPFS to gateway loads the page using IPFS Public gateway(dweb.link)

![image](https://user-images.githubusercontent.com/17010094/117277224-90396380-ae57-11eb-8184-09a51488e71c.png) | ![image](https://user-images.githubusercontent.com/17010094/117277356-b6f79a00-ae57-11eb-8406-e7771294b20e.png)
-- | --
