### ISSUE TITLE
study_filtering.cc logs are missing in release

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#15162]
Follow up to https://github.com/brave/brave-browser/issues/14613

The test plan from https://github.com/brave/brave-core/pull/8216 requires to `Verify in logs that study loaded correctly with [10210:775:0313/084147.162484:VERBOSE1:study_filtering.cc(346)] Kept study AdvertiserSplitTestingStudy`.
The log message is never shown.

## Steps to Reproduce

   1. Follow `Notification ad - GroupA` from https://github.com/brave/internal/issues/762

## Actual result:

study_filtering.cc logs are missing

## Expected result:
study_filtering.cc logs are present
Example from test plan https://github.com/brave/brave-core/pull/8216
```
[10210:775:0313/084147.162484:VERBOSE1:study_filtering.cc(346)] Kept study AdvertiserSplitTestingStudy
```

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.23.63 Chromium: 89.0.4389.114 (Official Build) beta (64-bit)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Ubuntu 18.04 LTS

cc @moritzhaller @tmancey @jsecretan @brave/legacy_qa

**Comment by moritzhaller** [comment]
I've noticed these logs are not showing on release builds. Maybe @iefremov can help?

**Comment by iefremov** [comment]
yeah this is expected, since those are debug logs

**Comment by tmancey** [comment]
Closing issue as working as expected
