### ISSUE TITLE
Rewards panel it's now always showing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1517]
## Test Plan

https://github.com/brave/brave-core/pull/705

## Description 

Sometime that you click on the bat logo in the url you get wallet summary (tab is not recognized as site) and sometimes you get can't mount error. 

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

* went through https://github.com/brave/brave-core/pull/705
* enabled rewards via `brave://rewards`, visited several websites and ensured that `Reward Summary` is being displayed
* enabled rewards by clicking on the `BAT` icon under the URL bar, visited several websites and ensured that `Reward Summary` is being displayed

![rewardsummary](https://user-images.githubusercontent.com/2602313/47327268-8bff1f00-d63a-11e8-9682-418bd88156de.gif)

![rewardsummary2](https://user-images.githubusercontent.com/2602313/47327311-c5378f00-d63a-11e8-9070-d9162038a789.gif)
