### ISSUE TITLE
Brave crashes after closing the Ad notification window

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15173]
## Description 

Brave crashes after closing the Ad notification window
## Steps to Reproduce

   1. Clean profile 1.24.52
   2. Enable rewards
   3. View an Ad
   4. Close the Ad notification window 
   [Note: In `1.22.71` Ad notification popup is shown when Ad is triggered but in `1.24.52` Ad notification browser window is shown, after clicking on the browser close `x` icon on Ad window, keep brave idle for ~2 mins after that brave crashes]

![image](https://user-images.githubusercontent.com/38657976/113880408-1753d700-97d9-11eb-8981-cf99ca2aaf95.png)

## Actual result:

![Brave crash nightly build](https://user-images.githubusercontent.com/38657976/113881110-c09acd00-97d9-11eb-90e1-abb7bdeaccbc.gif)

Brave crash
Uploaded Crash Report ID:	a83a0000-f4c3-1a06-0000-000000000000
Upload Time:	Wednesday, April 7, 2021 at 5:58:39 PM

## Expected result:

Should not be any crash

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.24.52 Chromium: 90.0.4430.51 (Official Build) nightly (64-bit)
-- | --
Revision | 32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}
OS | Windows 10 OS Version 2004 (Build 19041.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @rebron @jsecretan

**Comment by LaurenWags** [comment]
@tmancey is this related to custom ad notifications?

**Comment by tmancey** [comment]
@LaurenWags This is due to custom ad notifications and will be fixed by https://github.com/brave/brave-core/pull/8377

**Comment by LaurenWags** [comment]
thanks! wanted to be sure this wasn't something we needed to worry about for 1.23.x release 👍🏻

**Comment by tmancey** [comment]
Closing as will be fixed by https://github.com/brave/brave-browser/issues/13132 which is due to be merged very soon
