### ISSUE TITLE
Brave crashes when clicking on a select/dropdown box.

### ISSUE THREAD

**Issue by dev** [brave/brave-browser#15172]
## Description 

Brave freezes when clicking on a select box.

## Steps to Reproduce

   1.  Click on a selectbox

## Actual result:

https://user-images.githubusercontent.com/12158001/113852426-d8a02b80-979c-11eb-93f3-810674bcc808.mp4

## Expected result:
No crash

## Reproduces how often: 

Doesn't happen on all websites.

## Brave version (brave://version info)

Brave | 1.22.71 Chromium: 89.0.4389.114 (Officiële build) (64-bits)
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Windows 10 OS Version 1909 (Build 18363.1379)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Solution: update to latest beta of Chrome
https://answers.microsoft.com/en-us/microsoftedge/forum/all/edge-lags-freezes-on-website-dropdown-menus/5c7262e8-b20a-466c-ac93-6569138807a9?page=2

**Comment by rebron** [comment]
@dev Looks like this is resolved with a later chromium 89 update as it's not reproducible in Nightly channel. Should be resolved in https://github.com/brave/brave-browser/releases/tag/v1.23.71 available later today in release channel.

**Comment by dev** [comment]
@rebron just updated to 1.23.71 and seems to be fixed. Thanks!
