### ISSUE TITLE
Investigate scripts being used to block video from loading with default Shields settings

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#1518]
## Description 

Some websites block video playback with Shields enabled set to default settings. I've seen this reported for different websites but this domain seems prominent:
https://www.reddit.com/r/brave_browser/comments/9mcsfx/pornhub_videos_wont_load_on_brave_dev/
Playback is blocked until ads/tracking are allowed or shields disabled.

## Steps to Reproduce

   1. Visit pornhub.com
   2. Attempt to watch any video with Shields up and set to default

## Actual result:

Playback is blocked, black screen is displayed.
Probably no screenshots on this one.

## Expected result:
Video should play

## Reproduces how often: 

Easily reproduced

## Brave version (chrome://version info)

Dev: v0.56.2
Beta: v0.55.12
### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? Surprisingly, no.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes - Allow Ads also works
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
Closing in favour of #902 which lists other sites as well which block video playback on default shields settings and adblock in specific. Please add sites to that list in future so that its easy to track

**Comment by Brave-Matt** [comment]
@srirambv perfect, thank you. Didn't see this issue, appreciate the heads up.
