### ISSUE TITLE
Open bookmark section when the bottom navigation button is pressed for long time

### ISSUE THREAD

**Issue by NikharPandya** [brave/brave-browser#15184]
## Description 
 I frequently need to bookmark sites from my mobile in different folders and subfolders, but every time when I need to change the bookmark folder or subfolder I need to press the edit bookmark button and then select the folder.

 So I would like to have a long-press feature on the bottom navigation bookmark button that would open a bookmark section where I can change and select folders, I have an image attached of the **" bottom navigation bookmark button"** 

![Screenshot_20210407-174454_Brave](https://user-images.githubusercontent.com/70164257/113940791-08b2f300-97cc-11eb-949b-93b6b129a922.jpg)

The expected result should look like the following 

https://user-images.githubusercontent.com/70164257/114224878-a4b13b80-993f-11eb-92c5-28704483062f.mp4

## Device details
   - Device type: Samsung S20 FE
   - Android version: 11
   
## Brave version
   -Brave:1.22.71
   -Chromium: 89.0.4389.114

**Comment by NikharPandya** [comment]
Thank you for your consideration and assignment of the feature.

**Comment by NikharPandya** [comment]
@bsclifton 
I think [this](https://github.com/brave/brave-core/commit/47ae8ce8ed47a52ca6417a490fa86cc23f44970c) commit  resolved this issue and [#14949](https://github.com/brave/brave-browser/issues/14949 )

**Comment by bsclifton** [comment]
Thanks @NikharPandya 😄 ! I'll go ahead and close this as fixed by https://github.com/brave/brave-core/pull/16484
