### ISSUE TITLE
PDF.js should NOT be shown in brave://extensions when launched with --show-component-extension-options

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15185]
## Description 
PDF.js should NOT be shown in `brave://extensions` when launched with `--show-component-extension-options`

(Sorry!) I missed this, apparently, when verifying https://github.com/brave/brave-browser/issues/14338 (with the testcase in https://github.com/brave/brave-core/pull/8061)

## Steps to Reproduce

1. Go to `https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm`
2. Verify that you can install `PDF.js`
3. Verify that `PDF.js` puts a browser action button in the extension area
4. Verify that `PDF.js` shows in `brave://extensions`
5. Open a PDF document and verify `PDF.js` is used
6. Launch Brave from the command line with `--show-component-extension-options`
7. Load `brave://extensions`
8. Look for the `PDF Viewer` / `PDF.js` extension (shouldn't be there)

## Actual result:

<img width="1677" alt="Screen Shot 2021-04-07 at 3 14 20 PM" src="https://user-images.githubusercontent.com/387249/113941480-03e24500-97b4-11eb-94fc-d65735085ca7.png">

## Expected result:

There should be no `PDF.js` / `PDF Viewer` extensions visible in `brave://extensions`, when launched with `--show-component-extension-options`

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.25.2 Chromium: 90.0.4430.51 (Official Build) nightly (x86_64)
-- | --
Revision | 32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

/cc @kjozwiak @mariospr @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.23.65`
![image](https://user-images.githubusercontent.com/38657976/113971390-507e5c80-9856-11eb-9417-1f76c9ac6500.png)

**Comment by simonhong** [comment]
@stephendonner I think this is expected behavior. With `--show-component-extension-options`, `brave://extensions` page shows all installed extensions(extensions from webstore and component extensions like wallet.

**Comment by bsclifton** [comment]
@simonhong is exactly right; any installed extensions will show here

Had me doing a double take as we used to package PDF.js with the browser (and it was hidden by default) and I thought something regressed! 😂 Read your tests steps and this is working as designed. You can try the same steps in Chrome

**Comment by kjozwiak** [comment]
> @stephendonner if you were using test plan from https://github.com/brave/brave-core/pull/2342 you'll want to ignore anything mentioning PDF.js as we removed that from packaging. It's treated the same as any regular extension now

That's where the confusion occurred. I was running through Linux and noticed that I can still see the PDF Viewer we installed via `brave://extensions` while running Brave with `--show-component-extension-options`. The test case basically mentioned that we shouldn't be visible which was strange but figured it was an issue. @stephendonner confirmed he was seeing the same thing.

Thanks for clearing it up @simonhong & @bsclifton 👍

**Comment by GeetaSarvadnya** [comment]
@simonhong Test plan for `Test that PDF.js does not show` needs to be corrected in https://github.com/brave/brave-core/pull/2342
(Step 4: Verify PDF.js does not show in brave://extensions)

**Comment by bsclifton** [comment]
@GeetaSarvadnya the test plan shown was from a PR 3 years ago; maybe the right thing to do would have been to copy the test plan and edit instead of linking to the old test plan in https://github.com/brave/brave-core/pull/8061
