### ISSUE TITLE
There's an ad on my new tab page

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#15190]
There is no quick and easy "stop showing ads". 
Further, it's replaced the welcoming beautiful photography that was once there.  This is completely and utterly unacceptable way of taking advantage of users.  Someone should be fired over this.

If there was a simple, quick, obvious way to disable this, it'd be fine.  But you're a browser that blocks ads, and this is so absurdly out of line it's ridiculous.  Seriously, fire the person(s) who came up with this.  They don't belong at your company.  They are the bug, the failed logic, and the anti pattern.
 
![Screenshot_20210407-211116](https://user-images.githubusercontent.com/14002040/113963090-360c9a80-97e6-11eb-9c01-582f94fcf7be.png)

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Hi @SephReed - thanks for the feedback

Sponsored images have been a feature for over a year on all platforms. One will show every 4 images loaded. You can read more about it here:
https://brave.com/sponsored-images-now-available-on-all-brave-platforms/

You can turn this OFF by going to Settings > New Tab Page > Show Sponsored Images
