### ISSUE TITLE
Verify wallet panel appears on Rewards onboarding tour

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15194]
## Description 

The verify wallet panel is currently appearing in the rewards onboarding tour even when the bF feature flag disabled.

## Steps to Reproduce

   1. Open browser with a clean JP profile using the rewards staging
   2. Open the rewards panel
   3. Click "Start using Brave Rewards"
   4. Navigate through onboarding tour

## Actual result:

The verify wallet panel is displayed after the last tour step.

## Expected result:

The verify wallet panel should not be displayed.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.25.19 Chromium: 90.0.4430.72 (Official Build) nightly （x86_64）
-- | --
変更履歴 | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS バージョン11.2.3（ビルド20D91）

Steps:
1. changed OS region and language to Japan and Japanese, respectively
2. clean profile in Brave
3. launched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
4. clicked on the BAT icon
5. navigated through the Rewards-onboarding tour

Confirmed I didn't see the bitFlyer slide tacked on to the end, as I did in https://github.com/brave/brave-browser/issues/14693.

<img width="1312" alt="スクリーンショット 2021-04-15 16 23 34" src="https://user-images.githubusercontent.com/387249/114949969-fd347d00-9e06-11eb-922a-7ca94b7182fd.png">


![no-last-slide](https://user-images.githubusercontent.com/387249/114949867-c8282a80-9e06-11eb-99ae-330afbbd0f83.gif)
