### ISSUE TITLE
when you click tip on twitter the pop up does not show up.

### ISSUE THREAD

**Issue by masterbruce99** [brave/brave-browser#15193]
## Description 
when you click tip on twitter the tip window does not show up.

## Steps to Reproduce

   1. open twitter.com
   2. click the tip triangle button
   3. window sometimes and sometimes does not show up.

## Actual result:
 the pop window  sometimes does not show up.

## Brave version (brave://version info)

1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)

## Version/Channel Information:

only tested on twitter.com
- Can you reproduce this issue with the current release? did not try, I heard that the new one is still buggy and has more issues.
- Can you reproduce this issue with the beta channel? did not try
- Can you reproduce this issue with the nightly channel? did not try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? did not try
- Is the issue reproducible on the latest version of Chrome? yes

**Comment by Miyayes** [comment]
If you wait up to 10-30 seconds, does it show up eventually? Want to verify whether it's a slowness issue (known), or a never issue.

**Comment by Miyayes** [comment]
Should be resolved with https://github.com/brave/brave-browser/issues/14602.
