### ISSUE TITLE
No toggle button for javascript in site setting.

### ISSUE THREAD

**Issue by Techguyprivate** [brave/brave-browser#1519]
## Description 

There is no toggle button for javascript in site setting. It seems the default option is being the javascript being turn off. You have to manually turn on javascript for each website in the brave shield. Then it shows in site setting as allowed.

## Steps to Reproduce

   1. Go to setting.
   2. Content setting.
   3. Javascript.

## Actual result:

There is not a recommended toggle option to allow javascript by default .

## Expected result:
There should be a toggle option to allow or block javascript globally.

## Reproduces how often: 

Yes. Easily reproduced.
## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows
JavaScript | V8 7.0.276.25
Flash | 31.0.0.108 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_31_0_0_108.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.45 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser-Beta\Application\brave.exe" --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor --flag-switches-begin --autoplay-policy=document-user-activation-required --disable-device-discovery-notifications --blink-settings=disallowFetchForDocWrittenScriptsInMainFrame=true --enable-gpu-appcontainer --force-gpu-rasterization --enable-oop-rasterization --site-per-process --enable-zero-copy --gpu-rasterization-msaa-sample-count=16 --ignore-gpu-blacklist --reduced-referrer-granularity --save-previous-document-resources=onload --show-saved-copy=primary --v8-cache-options=code --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService,Av1Decoder,BloatedRendererDetection,BlockTabUnders,DisallowUnsafeHttpDownloads,ExperimentalProductivityFeatures,FontCacheScaling,FramebustingNeedsSameOriginOrUserGesture,GuestViewCrossProcessFrames,LayoutNG,LazyFrameLoading,LazyImageLoading,PWAFullCodeCache,PdfIsolation,PictureInPicture,RecurrentInterstitialFeature,ServiceWorkerScriptFullCodeCache,UseSurfaceLayerForVideo,UseSurfaceLayerForVideoMS,V8ContextSnapshot,WebRTC-H264WithOpenH264FFmpeg,top-document-isolation --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser-Beta\Application\brave.exe
Profile Path | C:\Users\anama\AppData\Local\BraveSoftware\Brave-Browser-Beta\User Data\Default

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes.
- Does it reproduce on browser-laptop? 
No.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes.
- Is the issue reproducible on the latest version of Chrome? 
No.
![brave untitled](https://user-images.githubusercontent.com/43615747/46785705-1fbf1a00-cd22-11e8-8248-bbd638c22ca8.jpg)

**Comment by srirambv** [comment]
Javascript is managed under Global Shields settings. Javascript under Content only lists the allow/block list now 
![image](https://user-images.githubusercontent.com/17010094/46803501-38cdc800-cd2e-11e8-85c0-c07716d1a5f1.png)

**Comment by Techguyprivate** [comment]
Weird behaviour. I am sending you a gif ,please look at it.

1. I have disabled script blocking in Brave default shield in chrome://setting. 

2. In chrome://setting , go to content setting ,then javascript toggle option showing disabled. 

3 .Also, there is no toggle button in all site content setting.

4. I have to enable javascript on every site manually through the brave shield right of url bar.

5. Then it showed of in javascript setting in chrome:// setting , content setting as allowed.
![brave](https://user-images.githubusercontent.com/43615747/46815847-435a8280-cd6b-11e8-913f-105153221dde.gif)

**Comment by Techguyprivate** [comment]
Same thing also in both brave dv and beta built on brave core ( not brave browser laptop built on muon,modifeid electron)

**Comment by srirambv** [comment]
Did you have Javascript disabled in content settings before the previous update was available?

**Comment by srirambv** [comment]
Reopening for discussion

**Comment by Techguyprivate** [comment]
I can't say definitely. But may be ,yes. Same weird behaviour in linux snap install, normal brave ( not snap) , both in dev & beta on linux mint, windows 7, ubuntu, debian. Problem still persists even after uninstalling & then installing for snap version , normal version & in microsoft windows too. Also ,videos in mega sync, dropbox, nextcloud,  google drive , pornhub, imdb not playing.Thanks .

**Comment by srirambv** [comment]
@Techguyprivate  On Linux you will have to manually remove the profile folder otherwise even after reinstalling the same settings will remain as the same profile will be used. Can you try the following steps on Windows 
1. Open `%userprofile%/AppData/Local/BraveSoftware/`
2. Rename `Brave-Browser-Beta` folder to `Brave-Browser-Beta_old`
3. Rename `Brave-Browser-Dev` folder to `Brave-Browser-Dev_old`
4. Launch Brave-Beta. You should have a new profile
5. Verify the Javascript setting under content shows as `Allowed` on the new profile
6. Verify Global shields settings has `Script Blocking` is set to disabled
7. Verify you can load sites normally 

Please follow these steps to backup your profile on Linux (**Not snap version**)
1. Rename Beta profile folder with the following command  `mv ~/.config/BraveSoftware/Brave-Browser-
Beta ~/.config/BraveSoftware/Brave-Browser-Beta_old` 
2. Rename Dev profile folder with the following command  `mv ~/.config/BraveSoftware/Brave-Browser-Dev ~/.config/BraveSoftware/Brave-Browser-Dev_old` 
3. Follow the same steps from step 4 onward from above

I think this is a conflict with you profile with having javascript blocked under content settings and after the update this feature was removed so its causing the issue. Should work fine on the new profile

**Comment by Techguyprivate** [comment]
Solved . Yes,you are spot on right. I used to disable javascript often. You are right. I did exactly what you said. Used some cleaner app like iobit uninstaller,revo uninstaller on windows though.. Everything is working fine now. Every version on every  os .Thanks.

**Comment by srirambv** [comment]
Perfect. Thanks for the confirmation. Closing the issue for now.

**Comment by Techguyprivate** [comment]
I will keep an eye on it whether the setting is getting carried on after updating to future versions.
