### ISSUE TITLE
[hackerone] wayback machine URL parameter bypass

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#15197]
see Slack or https://hackerone.com/reports/1157892 for details.

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` with the test plan from https://github.com/brave/brave-core/pull/8487, build used was 

Brave | 1.25.11 Chromium: 90.0.4430.61 (Official Build) nightly (x86_64)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1. loaded `https://brave.com/hackerone/?lkasjdf=asldjflakjsf&%63allback=%7B%22archived_snapshots%22%3A%7B%22closest%22%3A%7B%22url%22%3A%22https%3A%2F%2Fexample.com%2Ffavicon.ico%22%7D%7D%7D%2F%2F`
2. clicked on `Check for saved version` orange button
3. confirmed I remained on the same URL as in step 1

<img width="1001" alt="Screen Shot 2021-04-12 at 4 40 44 PM" src="https://user-images.githubusercontent.com/387249/114475919-1db5ca80-9bae-11eb-8314-5c0b9cd2c011.png">
<img width="1001" alt="Screen Shot 2021-04-12 at 4 40 50 PM" src="https://user-images.githubusercontent.com/387249/114475923-1e4e6100-9bae-11eb-8de3-190c3e9a437b.png">
