### ISSUE TITLE
March Rewards Payout Far Below What Was Earned

### ISSUE THREAD

**Issue by cyberfunk** [brave/brave-browser#15191]
## Description 

I keep a running tally of accumulated Brave rewards at CoinGecko. The way I get my running total is I add my current Uphold BAT balance to the current rewards earned as reported in the Brave tab. My March payout was around 2 BAT to my Uphold account when it should have been over 5 BAT. Are there any uphold transfer fees or other deductions levied against the total Brave rewards earned each month? 

## Steps to Reproduce

   1. Use Brave
   2. Accumulate Rewards in BAT
   3. Lose rewards at payout

## Brave version (brave://version info)

Latest Stable Build

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by cyberfunk** [comment]
When I click on "View monthly statement for details the results for every month that I've been using Brave shows zeroes everywhere. So there is no accountability or record of ads viewed or rewards earned other than the arbitrary total that brave decides to transfer to Uphold? Something  seems very wrong about this. Where can I view my FULL ads viewed history along with the payout amount per ad? Please see attached zero totals from each month. 


![Screen Shot 2021-04-08 at 5 04 47 AM](https://user-images.githubusercontent.com/12664589/114023644-fd8db080-9827-11eb-9eba-2343eee8720e.png)
![Screen Shot 2021-04-08 at 5 04 32 AM](https://user-images.githubusercontent.com/12664589/114023652-febedd80-9827-11eb-8123-863f8bbada2e.png)
![Screen Shot 2021-04-08 at 5 04 20 AM](https://user-images.githubusercontent.com/12664589/114023655-ff577400-9827-11eb-8333-16957678c0ee.png)
![Screen Shot 2021-04-08 at 5 04 06 AM](https://user-images.githubusercontent.com/12664589/114023658-fff00a80-9827-11eb-9771-749ada40e2dc.png)

**Comment by cyberfunk** [comment]
Here is a snapshot from my Uphold account. You can see the obvious discrepancy in rewards earned between the March 8th payout (Feb rewards earned) and the April 8th payout (March reward earned). The April 8th payout (March rewards earned) is far below what I actually earned. Where are my rewards going?

![Screen Shot 2021-04-08 at 5 10 32 AM](https://user-images.githubusercontent.com/12664589/114024784-4f830600-9829-11eb-906c-132799d5d43b.png)

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by hollons** [comment]
Hi @cyberfunk, thanks for reaching out. Payments for this month are still processing, and are often sent in small intervals. You can track this months payments progress on this thread - https://community.brave.com/t/april-2021-brave-ads-payout-status/227151. If you haven't received the fully expected amount of BAT once payments have completed processing please let us know. We can dig in then to see what might have happened. Thank you.

**Comment by cyberfunk** [comment]
@hollons Thanks so much for these insights and tips! Can you tell me where I can go to track my rewards earned history since the browser does not seem to keep an accurate report? For example with a wallet on the blockchain you can go to Etherscan and see each and every transaction for that wallet address in and out. I feel a bit left in the dark not being able to keep and verify a detailed and complete history of brave rewards earned beyond my own manual tally at CoinGecko.

**Comment by bsclifton** [comment]
Closing as response has been made here and no action for our codebase 😄 
Feel free to continue conversation or follow up in the community.brave.com link. Thanks!

**Comment by cyberfunk** [comment]
> Closing as response has been made here and no action for our codebase 😄
> Feel free to continue conversation or follow up in the community.brave.com link. Thanks!

Hi Clifton I still have not received full Brave rewards for March and the internal machinations of the Brave browser are still broken. In addition I can't get any of my earnings history by clicking "View monthly statements for details" The drop down for each consecutive month displays zeros for all values. Is this a known issue? Please see attached video.

https://user-images.githubusercontent.com/12664589/115928036-540b0980-a43a-11eb-901e-cdd8d500abca.mov

**Comment by Miyayes** [comment]
> > Closing as response has been made here and no action for our codebase 😄
> > Feel free to continue conversation or follow up in the community.brave.com link. Thanks!
> 
> Hi Clifton I still have not received full Brave rewards for March and the internal machinations of the Brave browser are still broken. In addition I can't get any of my earnings history by clicking "View monthly statements for details" The drop down for each consecutive month displays zeros for all values. Is this a known issue? Please see attached video.

The 0.0 in monthly statements is known, and will actually be resolved in the near future (not just saying that; I held a meeting about it): https://github.com/brave/brave-browser/issues/9211

Which falls under this overarching fix: https://github.com/brave/brave-browser/issues/15320

> I still have not received full Brave rewards for March and the internal machinations of the Brave browser are still broken

It looks like your estimated pending rewards is 0.770, which seems reasonable and normal. It's worth noting that each payout on the 5th will miss about 1 week's worth of ad earnings, which is expected. However, if the divergence is really high, like 12 BAT pending but only getting paid out 1 BAT (which it doesn't seem to be in your case), then that's another known issue which is also being resolved soon.

**Comment by cyberfunk** [comment]
Hi Miyayes,
Thanks for your quick reply. That pending 0.770 is for the month of April. I'm referring to the missing BAT from March. I was keeping a tally on CoinGecko of my total rewards between what had been paid in my Uphold account and what had been reported and accrued in the browser tab. When it came time for my payout that payout was FAR below my tally by about 3 BAT or so which is a considerable amount if you keep in mind the fractional rewards paid with each ad view. I'm not sure if you have access to my earnings each month but if you simply compare march to Jan and Feb you'll see the March amount is way under and my activity has not lessened in the browser. Again my running tally included what was reported day by day ad by ad in the browser and what had already been paid to my Uphold account.
