### ISSUE TITLE
[Android] Reduce Uphold minimum BAT user wallet verification requirement to 15 BAT on Android

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15196]
### Android

Currently, users need to have 25 BAT to verify their user wallet with Uphold. Uphold has approved lowering the verification threshold to 15 BAT as of March 31, 2021.

_This issue has been resolved on desktop, but is being broken out separately for Android for development reasons._

## Solution

Reduce all relevant wallet verification gating logic to a 15 BAT threshold.

**Comment by lubosz** [comment]
Why does Android require BAT at all to login to your existing wallet? I was able to use "Verify Wallet" on PC to login into an exisiting Uphold account. While on Android, I switched to a new Phone and need to grind 25 BAT to be able to login into my old Uphold account.

In general I am a bit disappointed that Brave has an internal wallet (Metamask), which can't interact with the rewards without Uphold.

**Comment by Miyayes** [comment]
> Why does Android require BAT at all to login to your existing wallet? I was able to use "Verify Wallet" on PC to login into an exisiting Uphold account. While on Android, I switched to a new Phone and need to grind 25 BAT to be able to login into my old Uphold account.

This is solved with https://github.com/brave/brave-browser/issues/13220, which should be landing in v1.25.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.60 x64 Beta Build
- Verified clicking on Verify wallet brings up the new modal
- Verified modal mentions about min 15 BAT
- Verified able to login to Uphold wallet even if there is no/low balance
- Verified able to connect to an existing Uphold wallet account on Android 
- Verified if the balance is more than 15 BAT clicking on verify wallet doesn't bring the new info modal 
---------
Verification passed on Samsung Tab A with Android 10 running 1.25.60 x64 Beta Build
- Verified clicking on Verify wallet brings up the new modal
- Verified modal mentions about min 15 BAT
- Verified able to login to Uphold wallet even if there is no/low balance
- Verified able to connect to an existing Uphold wallet account on Android 
- Verified if the balance is more than 15 BAT clicking on verify wallet doesn't bring the new info modal 
- Logged #15775 for tablet UI

OnePlus 6T  | Samsung Tab A
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/118446019-0f942600-b6e7-11eb-9e1a-e7ec460c5b67.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/118446081-1f136f00-b6e7-11eb-99ab-86b73640dc4d.png>
