### ISSUE TITLE
Need string grd file corresponding to google_chrome_strings.grd

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#152]
Chrome has two versions of string grd file - google_chrome_strings.grd and chromium_strings.grd.
google_chrome is for official build(chrome brand) and the other is unofficial build.

We also need two versions of string grd file because un-official build(brave_strings.grd) omits some strings like below.
```
<message name="IDS_INBOUND_MDNS_RULE_NAME_BETA" desc="Unused in Brave builds" translateable="false">
</message>
```
We need to revisit `//chrome/app:google_chrome_strings`, `//chrome/app:chromium_strings` and `chrome/install/util::generate_strings action' when we have official version of strings grd file.

**Comment by bbondy** [comment]
I think we will probably not enable `GOOGLE_CHROME_BUILD` so closing for now. Let's re-open if we find the need.
