### ISSUE TITLE
[Feature Request] Match look to original Chrome

### ISSUE THREAD

**Issue by Brawaru** [brave/brave-browser#15209]
## Description 

Brave looks clean, but unfortunately, changes to the design of elements like tabs might be less convenient and accessible.

## Steps to Reproduce

1. Open Google Chrome browser
2. Open Brave browser
3. Open multiple tabs in both browsers
4. Compare designs

## Actual result:

- Brave tabs have a smaller hit zone, requiring more mouse movement to the tab bar (pretty sure that's okay with many folks, so if that stayed an option ‘Compact mode’, that'd be great).
- Brave ‘New Tab’ button has a ridiculously small hit zone, so the cursor has to be placed strictly above the ‘+’ sign.
- Brave also doesn't match Windows OS colour, making the window's top frame bright grey-ish or contrast black when a dark theme is used.
- On top of that, in Brave contrast ratio for inactive tabs is very small that which makes text blur and disappear for some people like me. This might be due to two issues: the font is thin and the colour is either grey or semi-transparent.

<p align=center><img src="https://user-images.githubusercontent.com/10401817/114179890-db875180-993f-11eb-8ef9-fe059597ac59.png" alt="Screenshot of the tabs bar in Brave browser"></p>
<p align=center><i>Current look of the Brave tabs.</i></p>

## Expected result:

- Tabs would have a similar touch zone (padding, size) to vanilla Chromium.
- If Brave's intent was to remove roundness from the ‘New Tab’ button, consider matching it to Firefox design (example below).
- Windows OS title bar colour is used.
- Active tabs still marked by background (as is currently), but preferably do not change text boldness.
- Inactive tabs do not have the background (as is currently), their colour is white or black depending on the title foreground colour (to have a great contrast ratio), they do not change the thickness of the font.

<p align=center><img src="https://user-images.githubusercontent.com/10401817/114179276-1046d900-993f-11eb-8965-c790cff101e8.png" alt="Screenshot of the tabs bar in Chromium browser"></p>

<p align=center><img src="https://user-images.githubusercontent.com/10401817/114183208-b72d7400-9943-11eb-8fff-e4f8de49e8cc.png" alt="Screenshot of the tabs bar in Firefox browser"></p>

<p align=center><i>Look of the Chromium and Firefox tabs for comparison.</i></p>

## Alternative solutions

One could argue that this can be fixed by using themes from the Chrome Store, but this isn't the case. While themes do improve the look of the vanilla Chromium browser, they still look bad in Brave.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Field | Value
-- | --
Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Windows 10 OS Version 2009 (Build 19042.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **Yes**
- Can you reproduce this issue with the nightly channel? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **No**

## Miscellaneous Information:

×

**Comment by bsclifton** [comment]
cc: @rebron @karenkliu on usability concerns

**Comment by bsclifton** [comment]
Closing as `wontfix` - but appropriate folks have been notified with your notes and impact on usability

**Comment by Brawaru** [comment]
Well, I hope to see some changes in the future, because for now Brave seems very unusable for me [at least] compared to all other browsers (themes, dark mode, etc don't really do much) :( Thanks for listening and forwarding this, though!
