### ISSUE TITLE
There appear to be dead links in the brave/brave-core PR template

### ISSUE THREAD

**Issue by jbmagination** [brave/brave-browser#15203]
## Description 

When making a pull request in `brave/brave-core`, some links are dead. Specifically, these two checkboxes:
- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description

These links go to `brave/handbook` and `brave/security` respectively, both of which do not exist, or at the very least are not public repositories. 

If they don't exist, then this has gone unnoticed for at least 2 months. If they're not public, this might be a bit confusing for people who are making pull requests and are not a part of the team.

**Comment by bsclifton** [comment]
@jbmagination those are private repos - you're right, it is confusing. Maybe we should put those under an `Employee` section of the template?

cc: @diracdeltas @fmarier

**Comment by fmarier** [comment]
We should be able to move the handbook section to the public wiki. I don't think there's anything secret about it.

The link to the security review form would need to be labelled `(Brave staff only)` since that repo is private.

**Comment by jbmagination** [comment]
Any updates?

**Comment by juls** [comment]
I'd also be happy to hear about an update

**Comment by fmarier** [comment]
Apologies for the delay. I've just moved this info to the public wiki: https://github.com/brave/brave-browser/wiki/Security-reviews

The links in the PR template should be working now.

**Comment by jbmagination** [comment]
No worries about the delay!

Yes, your PR resolves this issue in `brave/brave-browser`, thank you! Will make a matching PR in `brave/brave-core` as this exists there as well
