### ISSUE TITLE
How to Disable Private Browsing on MacOS

### ISSUE THREAD

**Issue by bigspike13** [brave/brave-browser#15202]
I'd like to know how to disable private browsing on Brave browser on macOS, I've seen tips by using terminal for other browsers but I'm not sure how to transfer that over to Brave.

**Comment by bsclifton** [comment]
Hi @bigspike13 

You can disable private windows by the following:
```
defaults write com.brave.Browser IncognitoModeAvailability -integer 1
```

This *should* disable Tor also; if it doesn't, you can add a policy for that too:
```
defaults write com.brave.Browser TorDisabled -integer 1
```

You should then be able to verify this in-browser via brave://policy

More info here:
https://github.com/brave/brave-browser/issues/5902

cc: @Brave-Matt - I know we have group policy captured for Windows; we might want to update to have a better article for macOS 😄 
https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy

NOTE: `com.brave.Browser` is for Brave on Release channel. Beta and Nightly will have different IDs

**Comment by daweth** [comment]
NOTE: 

to disable tor, you should try this if the above doesn't work.

`defaults write com.brave.Browser TorDisabled -boolean true`
