### ISSUE TITLE
[Desktop] Search icon/button in Brave Help Center is not clickable

### ISSUE THREAD

**Issue by bilaalukis** [brave/brave-browser#15204]
## Description 

The "Search glass" icon within Brave Help Center cannot be clicked to activate the search action. Also, once the screen is resized to a smaller screen, the "Search glass" icon cannot be used and its alignment within the search bar is not centered.

## Steps to Reproduce

   1. Open Brave browser.
   2. Navigate to [https://support.brave.com/hc/en-us](url)
   3. Insert any search field and try clicking on the "Search glass icon". Notice that although the orange part around the icon can be clicked the "Search glass" itself cannot be clicked.
  
![Screen Shot 2021-04-09 at 12 15 47](https://user-images.githubusercontent.com/73635058/114128078-86930d80-9936-11eb-9148-ca6fc8c631ef.png)

   4. Next, resize the screen to a smaller size and notice that a "search glass" icon is not center-aligned in the search bar.
   
![Screen Shot 2021-04-09 at 12 12 35](https://user-images.githubusercontent.com/73635058/114128410-41231000-9937-11eb-9ced-b52565537563.png)

## Actual result:

1. Search glass icon cannot be clicked
2. Search glass icon is not center-aligned on smaller screens

## Expected result:
1. I expect that regardless of the screen size, the glass icon can be clicked.
2. On a smaller screen, I expect the glass icon to be center-aligned within the search bar.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | macOS Version 11.2.3 (Build 20D91)
JavaScript | V8 8.9.255.24
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip,WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=PrivacySettingsRedesign,AutofillServerCommunication,TextFragmentAnchor,LangClientHintHeader,NetworkTimeServiceQuerying,WebOTP,NotificationTriggers,DirectSockets,AutofillEnableAccountWalletStorage,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,TabHoverCards,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection,IdleDetection,SafeBrowsingEnhancedProtectionMessageInInterstitials --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/frotwil/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations | 7146a73c-3f4a17df

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Thanks for the report @bilaalukis - if you click outside of the magnifying glass it works as expected. I passed this on to our support team and we'll work on a fix 😄 

As this isn't related to the browser itself and I have also passed onto the team, I'll mark this issue as closed
