### ISSUE TITLE
(Linux) Problems with sudo apt

### ISSUE THREAD

**Issue by yardent-was-taken** [brave/brave-browser#15219]
## Description 

When I go on my terminal and run sudo apt, it gives me 4 errors:
E: Conflicting values set for option Signed-By regarding source https://brave-browser-apt-release.s3.brave.com/ stable: /usr/share/keyrings/brave-browser-archive-keyring.gpg != 
E: The list of sources could not be read.
E: Conflicting values set for option Signed-By regarding source https://brave-browser-apt-release.s3.brave.com/ stable: /usr/share/keyrings/brave-browser-archive-keyring.gpg != 
E: The list of sources could not be read.
and the command won't run.
## What I did
I ran the commands in the instructions at https://brave.com/linux/ 
## Actual result:

I can't reproduce this error because I'm stuck with this problem.

## Expected result:
Brave is successfully installed

## Reproduces how often: 

I'm not sure.
## Version/Channel Information:

I am trying to install Stable

## Miscellaneous Information:

I am currently using Feren OS to install Brave

**Comment by bsclifton** [comment]
cc: @wknapik @fmarier

**Comment by fmarier** [comment]
Can you tell us the contents of `/etc/apt/sources.list.d/brave-browser-release.list`?

**Comment by yardent-was-taken** [comment]
@fmarier These are the contents of brave-browser-release.list
deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main

**Comment by fmarier** [comment]
Thank @yardent-was-taken, that looks right. Does the `brave-browser-archive-keyring.gpg` exist on your disk at that location?

What versions of `apt` and `dpkg` do you have? You can find out using:
```
dpkg -l apt
dpkg -l dpkg
```

**Comment by fmarier** [comment]
One more thing, I assume you get that error message when you run `sudo apt update`. Is that right?

If you comment out (by prepending it with the character `#`) the one and only line in `/etc/apt/sources.list.d/brave-browser-release.list` and try `sudo apt update`, does it make the message go away?

**Comment by fmarier** [comment]
I just installed the latest version of FerenOS from https://ferenos.weebly.com/ in a virtual machine and followed our [official installation instructions](https://brave.com/linux/#debian-9-ubuntu-1604-and-mint-18). Everything went as expected and Brave works fine on that distribution.

**Comment by yardent-was-taken** [comment]
No I didn't get the error when running sudo apt update. It showed two errors:
I got the results
E: Conflicting values set for option Signed-By regarding source https://brave-browser-apt-release.s3.brave.com/ stable: /usr/share/keyrings/brave-browser-archive-keyring.gpg != 
E: The list of sources could not be read.
When running sudo apt update

**Comment by fmarier** [comment]
@yardent-was-taken What files do you have in `/etc/apt/sources.list.d/`?

You can find out by running:
```
ls /etc/apt/sources.list.d/
```

**Comment by yardent-was-taken** [comment]
additional-repositories.list     iridium-browser.list
brave-browser-nightly.list       linux-mint.list
brave-browser-release.list       microsoft-edge-dev.list
brave.list                       nilarimogard-webupd8-focal.list
dropbox.list                     nodesource.list
expandrive.list                  opera-developer.list
feren-os.list                    opera-stable.list
feren-os-neon.list               riot-im.list
google-chrome.list               vivaldi.list
google-chrome-unstable.list      vivaldi-snapshot.list
google-earth-pro.list            vscode.list
graphics-drivers-ppa-focal.list  waterfox.list
insync.list                      yandex-browser-beta.list

**Comment by fmarier** [comment]
I see, you have a few Brave repos in here. Here's what I would suggest:

1. Delete all brave repositories: `sudo rm /etc/apt/sources.list.d/brave*`
2. Go through the [installation instructions](https://brave.com/linux/#debian-9-ubuntu-1604-and-mint-18Y) again.

**Comment by yardent-was-taken** [comment]
Your suggestions worked. I have decided to install Brave on the Snap Store though.
Thank you!
