### ISSUE TITLE
Brave logo missing in staging-only verified-creator Rewards popup

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15218]
## Description 
Brave logo missing in staging-only verified-creator Rewards popup

## Steps to Reproduce

   1. new profile, launch using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
   2. click `Start Brave`
   3. load `brave.com`
   4. click on the BAT icon in the URL bar
   5. click `Start using Brave Rewards`
   6. skip through the Rewards-onboarding tour and click `Done`
   7. click `Skip for now`
   8. click `Done`
   9. click again on the BAT icon in the URL bar
   10. click on `Send a tip...`
   11. look at the resulting Rewards panel 

## Actual result:

It's missing the `Brave` logo

<img width="1312" alt="Screen Shot 2021-04-09 at 6 38 38 PM" src="https://user-images.githubusercontent.com/387249/114254214-e43d4f00-9962-11eb-9cd4-bb34d8fd208a.png">

## Expected result:

The `Brave` verified-creator logo should be present

<img width="1312" alt="Screen Shot 2021-04-09 at 5 12 14 PM" src="https://user-images.githubusercontent.com/387249/114254228-f919e280-9962-11eb-995b-38d020946208.png">

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.23.69 Chromium: 90.0.4430.61 (Official Build) (x86_64)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? no

/cc @brave/legacy_qa team @emerick @zenparsing

**Comment by stephendonner** [comment]
So, this is a Rewards `staging` vs. `production`-environment ("vs." `development`) issue; it works on:

Production: `./Brave\ Browser --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6`

Development: `./Brave\ Browser --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-development --brave-ads-debug --rewards=development=true`

But is broken using the Rewards `staging` environment:

`./Brave\ Browser --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true`

/cc @Miyayes for help checking on the icon on staging for brave.com

**Comment by bsclifton** [comment]
Closing as this is not an issue with the code - we can follow up with icon offline 😄
