### ISSUE TITLE
Favicon is not shown

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1521]
## Description 

When watching twitch videos, publisher icon is not shown until you reload rewards page

## Steps to Reproduce

   1. clean profile
   2. enable rewards
   3. go to twitch in a new window and watch a video (VOD)
   4. rewards settings page has missing favicon

## Actual result:

Publisher has missing favicon. When you reload settings page, favicon is displayed correctly

## Expected result:
Favicon should be display correctly immediately 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows 10
- Verified test plan mentioned in https://github.com/brave/brave-core/pull/888
- Verified pavicon shown for verified twitch pubs
![image](https://user-images.githubusercontent.com/38657976/52441350-60029d80-2b46-11e9-99c6-efbf5bce6b1f.png)
- logged issue for pubs name missing in Thank you rewards banner https://github.com/brave/brave-browser/issues/3265
