### ISSUE TITLE
Other profiles popup contains a "Show on startup" checkbox that doesn't do anything

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15212]
## Description 

There's a "Show on startup" checkbox on the profile popup/other profiles popup that appears to be new with C90 (doesn't show in 1.22.x with C89). 

This checkbox doesn't seem to do anything though and is checked by default. I'd guess that checkbox means to show the profile window on startup, but that is not happening whether the checkbox is selected or not. Maybe that checkbox means something else?

<img width="1024" alt="Screen Shot 2021-04-09 at 2 57 46 PM" src="https://user-images.githubusercontent.com/28145373/114229872-68350e00-9946-11eb-8039-f2a0caf5a822.png">

## Steps to Reproduce

   1. Clean profile 1.23.x
   2. Create a second profile
   3. Open profile menu and select the gear icon next to Other profiles
   4. On this window you will see the checkbox
   5. Restart Brave

## Actual result:

Profile window not shown on startup

## Expected result:
Expected to see that window, but maybe that's an incorrect expectation. If that is what should happen, maybe we want this unchecked by default.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave	1.23.69 Chromium: 90.0.4430.61 (Official Build) (64-bit)
Revision	dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS	Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?  1.22.x n/a, 1.23.x yes
- Can you reproduce this issue with the beta channel? 1.24.x yes
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa @mkarolin

**Comment by stephendonner** [comment]
Confirming I saw the same on both `1.23.69` RC on `macOS 11.2.3` and then `nightly`, `beta`, and `1.23.69` RC on `Windows 10`, using:
1. `Brave 1.23.69` `Chromium: 90.0.4430.61 (Official Build) (x86_64) dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
macOS Version 11.2.3 (Build 20D91)` and `nightly` build
2. `Brave 1.25.7` `Chromium: 90.0.4430.61 (Official Build) nightly (64-bit)
Revision dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS Windows 10 OS Version 2009 (Build 21354.1)` as well as `beta`
3. `Brave 1.24.55` `Chromium: 90.0.4430.51 (Official Build) beta (64-bit)
Revision 32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}
OS Windows 10 OS Version 2009 (Build 21354.1)` and `1.23.69` RC
4. `Brave 1.23.69` `Chromium: 90.0.4430.61 (Official Build) (64-bit)
Revision dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS Windows 10 OS Version 2009 (Build 21354.1)`

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build 

Brave | 1.25.11 Chromium: 90.0.4430.61 (Official Build) nightly (x86_64)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | macOS Version 11.2.3 (Build 20D91)

Followed the inline steps from Lauren, and confirmed the `Show on startup` checkbox is no longer present.

<img width="1136" alt="Screen Shot 2021-04-12 at 3 56 54 PM" src="https://user-images.githubusercontent.com/387249/114473089-64082b00-9ba8-11eb-8bb2-73c0a7070f25.png">

@mkarolin @kjozwiak did we want to uplift this fix to `1.23.x` or just let it ride the trains?

**Comment by mkarolin** [comment]
@stephendonner: on slack it was decided to only uplift to 1.24.x
