### ISSUE TITLE
crash when searching via private window while having SE extension set as `Allow in private`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#15224]
## Description 

When you have a SE extension installed and have set it as `Allow in Private`, searching for a term via private mode will crash the entire browser. Similar to the issue that was fixed via https://github.com/brave/brave-browser/issues/15140.

* Uploaded crash report ID:	`d5250000-9cfd-2306-0000-000000000000`
* Uploaded crash report ID:	`d4250000-9cfd-2306-0000-000000000000`
* Uploaded crash report ID:	`d3250000-9cfd-2306-0000-000000000000`

## Steps to Reproduce

   1. download https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg/related?hl=en
   2. go into `brave://extensions` and set DDG Privacy Essentials as `Allow in private` by clicking `Details`
   3. open a private window and type in `test test` and click `enter` to start the search
   4. instant crash

## Actual result:

Brave instantly crashes.

## Expected result:

Brave shouldn't be crashing.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.23.69 Chromium: 90.0.4430.61 (Official Build) (64-bit)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | Windows 10 OS Version 2009 (Build 19042.906)
```

```
Brave | 1.25.8 Chromium: 90.0.4430.61 (Official Build) nightly (64-bit)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | Windows 10 OS Version 2009 (Build 19042.906)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes` 
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @bsclifton @simonhong @brave/legacy_qa

**Comment by bsclifton** [comment]
Likely related to https://github.com/brave/brave-browser/issues/10601 and https://github.com/brave/brave-browser/issues/10549

**Comment by kjozwiak** [comment]
This isn't a new regression, @simonhong mentioned that he can reproduce the crash in `1.22.x` and I also managed to reproduce using the following build:

```
Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Windows 10 OS Version 2009 (Build 19042.906)
```

Probably not a `release/blocking` as it's already on `Release`, but something we should probably fix sooner than later as crashes are never good.

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in `Windows 10 x64`

```

Brave | 1.23.70 Chromium: 90.0.4430.70 (Official Build) (64-bit)
-- | --
Revision | 3954de7175366f3b7edca576f140dfa273e6b5ae-refs/branch-heads/4430@{#1210}
OS | Windows 10 OS Version 2004 (Build 19041.867)


```

**Comment by stephendonner** [comment]
Verified `FIXED` using the inline testplan with build 

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:

1. downloaded and installed DuckDuckGo Privacy Essentials from `https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg/related?hl=en`
2. went into `brave://extensions`, clicked on `Details` for DDG Privacy Essentials, and toggled `Allow in private` to `On`
3. opened `File` -> `New Private Window` and type in `test test` and click `enter/return` to start the search
4. confirmed I no longer crash (tried 10x); instead, I got the search-results page, as expected

step 1 | step 2 | step 3 | step 4
---------|----------|---------|---------
<img width="1714" alt="Screen Shot 2021-05-17 at 3 37 04 PM" src="https://user-images.githubusercontent.com/387249/118565133-797ff000-b726-11eb-8e6a-8920a7bbc5f4.png"> | <img width="1714" alt="Screen Shot 2021-05-17 at 3 37 52 PM" src="https://user-images.githubusercontent.com/387249/118565137-7b49b380-b726-11eb-81dd-0bd23cd6b59b.png"> | <img width="1714" alt="Screen Shot 2021-05-17 at 3 38 08 PM" src="https://user-images.githubusercontent.com/387249/118565141-7c7ae080-b726-11eb-85ba-c14739933273.png"> | <img width="1714" alt="Screen Shot 2021-05-17 at 3 38 12 PM" src="https://user-images.githubusercontent.com/387249/118565147-7d137700-b726-11eb-9525-7a363293e2d4.png">

**Comment by btlechowski** [comment]
Added `QA/Test-All-Platforms` as Tor is using different binaries for each platform

**Comment by LaurenWags** [comment]
Testing https://github.com/brave/brave-core/pull/8626 will cover the following issues:
- https://github.com/brave/brave-browser/issues/15224 (this issue)
- https://github.com/brave/brave-browser/issues/10601
- https://github.com/brave/brave-browser/issues/14218
