### ISSUE TITLE
The Customise button covers the bottom right control icons

### ISSUE THREAD

**Issue by Dzheky** [brave/brave-browser#15221]
I have not found similar issue

## Description 
The `Customise` button covers the bottom right icons when you scroll down and up.
![2021-04-11 12 27 23](https://user-images.githubusercontent.com/10736974/114302511-4d3ad900-9ac1-11eb-9f9b-10d032393fd1.gif)

## Steps to Reproduce

   1. Open new tab
   2. Scroll down until the `Customise` button appears in bottom right corner.
   3. Scroll up again until the `Customise` button disappears and try to click settings icon in the bottom right corner.

## Actual result:
Customise dashboard opens.

## Expected result:
Open settings.

## Reproduces how often: 
All the time.

## Brave version (brave://version info)
Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)

- Can you reproduce this issue with the current release? 
  Yes
- Can you reproduce this issue with the beta channel?
  Yes
- Can you reproduce this issue with the nightly channel? 
  Yes

**Comment by Dzheky** [comment]
I will try to fix this if you don't mind

**Comment by Dzheky** [comment]
Can somebody review my PR for this, please?

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.26.47 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

I installed `1.22.71` to understand the issue, and once I did:

Steps:
1. new profile
2. opened a new-tab page
3. scrolled down
4. opted in to Brave News
5. scrolled back up
6. clicked on each of the icons alongside the `Customize` link, and ensured they opened `Settings`, `Bookmarks`, and `History`, respectively

example | example | example
---------|----------|----------
<img width="1312" alt="Screen Shot 2021-06-01 at 1 05 48 PM" src="https://user-images.githubusercontent.com/387249/120383780-25eed400-c2da-11eb-8793-da392771c560.png"> | <img width="1312" alt="Screen Shot 2021-06-01 at 1 05 38 PM" src="https://user-images.githubusercontent.com/387249/120383775-238c7a00-c2da-11eb-864c-90579f451adc.png"> | <img width="1312" alt="Screen Shot 2021-06-01 at 1 05 28 PM" src="https://user-images.githubusercontent.com/387249/120383754-1f605c80-c2da-11eb-8d66-79c716cd0445.png">
