### ISSUE TITLE
Sometimes user activity score is not increasing for kClickedBackOrForwardNavigationButtons  events

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#15225]
Some kClickedBackOrForwardNavigationButtons events are not processed for ads user activity 

## Steps to Reproduce

Follow steps from `User Activity - Custom values - kClickedBackOrForwardNavigationButtons` from https://github.com/brave/internal/issues/763

## Actual result:

Some navigation events are processed. Some are ignored.

## Expected result:
All navigation events are processed

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.23.63 Chromium: 89.0.4389.114 (Official Build) beta (64-bit)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @tmancey @moritzhaller @jsecretan

**Comment by tmancey** [comment]
Discussed with @btlechowski and working as expected. Thanks
