### ISSUE TITLE
Multiple kClickedLink events are fired after clicking a link 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#15226]
Clicking a link fires multiple `kClickedLink`  events for ads user activity 

## Steps to Reproduce

Follow steps from `User Activity - Custom values - kClickedLink` from https://github.com/brave/internal/issues/763

## Actual result:

Multiple kClickedLink events are fired after clicking a link 

```
[14073:14073:0412/060925.342962:VERBOSE6:user_activity.cc(41)] Triggered event: 06 (10:2:3600 s)
[14073:14073:0412/060928.195867:VERBOSE6:user_activity.cc(41)] Triggered event: 06 (20:2:3600 s)
[14073:14073:0412/060929.577509:VERBOSE6:user_activity.cc(41)] Triggered event: 06 (30:2:3600 s)
```

## Expected result:
One kClickedLink event per clicked link 

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.23.63 Chromium: 89.0.4389.114 (Official Build) beta (64-bit)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @tmancey @moritzhaller @jsecretan

**Comment by tmancey** [comment]
Closing issue as working as expected. @btlechowski I have DM'd you to discuss further. Thanks
