### ISSUE TITLE
Improve Disconnected Brave Rewards wallet state: disconnect wallet on backend, return to 'verify wallet' state

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15237]
## Test Plan
Specified here: https://github.com/brave/brave-core/pull/8872

## Description 

When a user presses `Disconnect`, their wallet is currently not disconnected from their Uphold account on the backend. As a result, we continue to pay out to their Uphold account even when they are in a disconnected state. Per https://github.com/brave-intl/bat-go/issues/712, we should no longer do this. However, some client changes need to be made.

## Solution 

**The new disconnected state should work as follows:**

1. When user presses `Disconnect` explicitly, hit the appropriate disconnection API endpoint that will disconnect the wallet on the backend. (See relevant API spec, per @husobee.) 
2. When user presses `Disconnect` explicitly, return their wallet to the "Verify wallet" state. 
3. When the user's access token expires, then they will remain in the `Disconnected` state
4. When the user's access token expires, they will not be disconnected on the backend (do not hit the disconnect API endpoint)

## Steps to Reproduce

   1. Verify wallet
   2. Disconnect wallet
   3. Notice that on the 5th, your ads earnings payout will continue to be send to Uphold

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.27.78 Chromium: 91.0.4472.114 (Official Build) beta (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 10.15.7 (Build 19H1217)
```

Verified the "Uphold" test plan from https://github.com/brave/brave-core/pull/8872. Note, at various points I confirmed the linking slots and `depositId` with @husobee to confirm that they were as expected on the staging server.

Verified scenario 1A from https://github.com/brave/internal/issues/774#issuecomment-856063731. Encountered https://github.com/brave/brave-browser/issues/16468#issuecomment-868788992. The UI was not as expected however the wallet was not able to be re-linked on the server, which is what we wanted to confirm.

Verified scenario 1B from https://github.com/brave/internal/issues/774#issuecomment-856063731. Encountered https://github.com/brave/brave-browser/issues/16468#issuecomment-868788992. The UI was not as expected however the wallet was not able to be re-linked on the server, which is what we wanted to confirm.

Scenario 2 from https://github.com/brave/internal/issues/774#issuecomment-856063731 was generally confirmed as part of the "Uphold" test plan listed on PR. 

Scenario 3 from https://github.com/brave/internal/issues/774#issue-909688720 was spot checked but will be fully verified as part of https://github.com/brave/brave-browser/issues/14629. Details of what was checked can be found under https://github.com/brave/internal/issues/774#issuecomment-868797645.


TBD:
Verify "bitFlyer" test plan from https://github.com/brave/brave-core/pull/8872.

--------------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.27.87 x64 build
- Verified Uphold part of the test plan from brave/brave-core#8872. 
- Verified linking slots worked as expected. @husobee confirmed it as well.
- Verified scenario 1A from brave/internal#774 (comment). 
- Verified that the wallet was not able to be re-linked on the server @husobee confirmed it
