### ISSUE TITLE
Fix base::Unretained/thread issues in MonitorChild usages

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#15235]
```IpfsServiceImpl::MonitorChild``` and ```TorLauncherImpl::MonitorChild``` both use same logic with a dedicated thread to monitor a child process lifetime. This logic directly use a class pointer and its members from the wrong thread which can lead to thread issues and possible memory corruption when the underlying process is terminated.
One of the possible solution is to replace a direct callback run with a callback run posted on the original thread.

https://github.com/brave/brave-core/blob/v1.23.55/components/services/ipfs/ipfs_service_impl.cc#L239
https://github.com/brave/brave-core/blob/v1.23.55/components/services/tor/tor_launcher_impl.cc#L184

**Comment by iefremov** [comment]
Possibly related crash

```
[ 00 ] base::internal::BindState<base::OnceCallback<void (ContentSetting)>,ContentSetting>::Create<base::OnceCallback<void (ContentSetting)>,ContentSetting &>
[ 01 ] _tailMerge_esent.dll
[ 02 ] base::ThreadTaskRunnerHandle::Get()
[ 03 ] ipfs::IpfsServiceImpl::MonitorChild()
[ 04 ] _tailMerge_esent.dll
[ 05 ] base::debug::ScopedTaskRunActivity::ScopedTaskRunActivity(void const *,base::PendingTask const &)
[ 06 ] mojo::SimpleWatcher::ArmOrNotify()
[ 07 ] base::ThreadLocalStorage::Slot::Set(void *)
[ 08 ] mojo::Connector::PostDispatchNextMessageFromPipe()
[ 09 ] _tailMerge_esent.dll
[ 10 ] base::TaskAnnotator::RunTask(char const *,base::PendingTask *)
[ 11 ] ipfs::IpfsServiceImpl::Launch(mojo::StructPtr<ipfs::mojom::IpfsConfig>,base::OnceCallback<void >)

```

https://brave.sp.backtrace.io/p/brave/debug?filters=(_deleted%3D0%2C(callstack.functions%2Ccontains%2CMonitorChild))&debug=(c52606,0,0)
