### ISSUE TITLE
Pull in l10n fixes for 1.23.x release.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#15241]
Follow up to #14956

Download the latest l10n from Transifex.

Test plan:

@brave/legacy_qa should run through a few locals just to make sure that nothing obvious has regressed. Shouldn't spend too much time on this though.

**Comment by kjozwiak** [comment]
Labeling as `QA/No` as QA will run through `l10n` via https://github.com/brave/brave-browser/issues/14956 when `1.25.14 C: 90.0.4430.70` is ready which will also cover this issue.
