### ISSUE TITLE
Brave Rewards UI 2.0 (Desktop)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#15245]
## Description 
Parent project for tracking a potential Brave Rewards UI refresh (2.0) on Desktop

For specific issues, please check out this label:
https://github.com/brave/brave-browser/labels/rewards-ui-2.0

**Comment by bsclifton** [comment]
cc: @jenn-rhim and @karenkliu in case you wanted to help ID and label potential issues with `rewards-ui-2.0` label 😄

**Comment by hvjufg** [comment]
I have a bad feeling about this.

**Comment by karenkliu** [comment]
@codybanxs ☝️ See Brian's note about `rewards-ui-2.0` label above.

**Comment by Miyayes** [comment]
Closing out this tracker issue as we have the label, and we've shipped major pieces of this (such as the new Rewards panel).
