### ISSUE TITLE
top level domain blocking enabled with `Standard` blocking - follow up to `#15095`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#15242]
## Description 

As per https://github.com/brave/brave-browser/issues/15095, we should be disabling top level domain blocking in `Standard` mode and should only be blocking when a user has selected `Aggressive` via the Brave Shields settings.

## Steps to Reproduce

   1. launch Nightly (`1.25.10 Chromium: 90.0.4430.61` used in this case)
   2. visit either  `1-1ads.com`, `actionsplash.com` or `pub.chez.com`
   3. you'll notice that the `interstitial` page is being displayed which means top level domain blocking is occurring

## Actual result:

Top level domain blocking is occurring even when `Standard` is selected as the default shields setting.

## Expected result:

Top level domain blocking should be disabled on `Standard` and only enabled when a user has selected `Aggressive` mode.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.25.10 Chromium: 90.0.4430.61 (Official Build) nightly (64-bit)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | Windows 10 OS Version 2009 (Build 19042.906)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (being disabled via https://github.com/brave/brave-core/pull/8507
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @bsclifton @brave/legacy_qa @pes10k @pilgrim-brave

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.24.65 Chromium: 90.0.4430.72 (Official Build) dev (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. launched Brave
2. loaded `1-1ads.com1`, `actionsplash.com`, `pub.chez.com` with default Shields setting `Trackers & ads blocked (standard)`
3. confirmed I was able to load (or at least DNS-lookup, in the case of `1-1ads.com`) the sites without seeing the interstitial/blocking page, for each
4. loaded `1-1ads.com1`, `actionsplash.com`, `pub.chez.com` aggressive-mode Shields setting `Trackers & ads blocked (aggressive)`
5. confirmed I got the interstitial blocked page, for each

example | example | example | example | example | example 
---------|---------|----------|---------|----------|---------|
<img width="1312" alt="Screen Shot 2021-04-15 at 12 15 58 PM" src="https://user-images.githubusercontent.com/387249/114925763-5d65f780-9de4-11eb-8301-1bb1ca87e025.png"> | <img width="1312" alt="actionsplash.com" src="https://user-images.githubusercontent.com/387249/114924060-65249c80-9de2-11eb-9987-357a81f92222.png"> | <img width="1312" alt="pub.chez.com" src="https://user-images.githubusercontent.com/387249/114924039-60f87f00-9de2-11eb-83ec-64ade4f5ef2d.png"> | <img width="1312" alt="Screen Shot 2021-04-15 at 12 19 41 PM" src="https://user-images.githubusercontent.com/387249/114926224-f39a1d80-9de4-11eb-85a5-1f437a41ec0c.png">| <img width="1312" alt="Screen Shot 2021-04-15 at 12 15 34 PM" src="https://user-images.githubusercontent.com/387249/114925974-a28a2980-9de4-11eb-85d2-4a4b854c16fd.png"> | <img width="1312" alt="pub.chez.com (blocked)" src="https://user-images.githubusercontent.com/387249/114924062-65bd3300-9de2-11eb-91b7-d1b1ac2f5a62.png">

**Comment by stephendonner** [comment]
Verified `PASSED` on Android 9 using Brave `1.24.76, Chromium 90.0.4430.85`, Google Pixel, arm64.

Confirmed that loading `1-1ads.com`, `actionsplash.com` and `pub.chez.com` with Shields' defaults (since no aggressive mode yet on Android) didn't load the interstitial blocking page.

example | example | example
---------|----------|---------
![Screenshot (Apr 29, 2021 10_57_06 AM)](https://user-images.githubusercontent.com/387249/116597582-a173f480-a8da-11eb-95f2-0dc17d2fb265.png) | ![Screenshot (Apr 29, 2021 10_57_40 AM)](https://user-images.githubusercontent.com/387249/116597585-a33db800-a8da-11eb-9cf8-a1f99ff42cc6.png) | ![Screenshot_20210429-105817](https://user-images.githubusercontent.com/387249/116597588-a33db800-a8da-11eb-99fc-1a9badf9b0dd.png)

**Comment by LaurenWags** [comment]
changing to `release-notes/exclude` per discussion with @rebron and @kjozwiak
