### ISSUE TITLE
Tabs UI layout problem

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15254]
## Description 

Brave:
![image](https://user-images.githubusercontent.com/2965009/114494721-80967880-9c25-11eb-82ce-d6959c3df4b5.png)

Chrome:
![image](https://user-images.githubusercontent.com/2965009/114494741-88561d00-9c25-11eb-80d7-0cd3bad7b654.png)

in Brave tab title, separator and close button have different horizontal axes, it looks like a bug

**Comment by rebron** [comment]
Closing as wontfix. This design choice was deliberate.
cc: @karenkliu Reopen if you want to revisit.
