### ISSUE TITLE
Minor typos in remove-device dialog prompt text

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15251]
## Description 
Minor typos in remove-device dialog prompt text

## Steps to Reproduce

   1.  on (desktop) deviceA, load `brave://settings/braveSync/setup`
   2.  click on the `Start a new Sync Chain` button
   2.  click `OK`
   3.  on another machine, deviceB, join the sync chain either via QR code (mobile) or by manually entering and pairing with the pass-phrase (desktop)
   4.  back on deviceA, load `brave://settings/braveSync/setup` and click on the (x) to remove deviceB
   5.  look at the resulting dialog prompt

## Actual result:

The prompt text reads `Are you sure you want to delete selected device from sync chain?`

<img width="1149" alt="Screen Shot 2021-04-09 at 11 33 02 AM" src="https://user-images.githubusercontent.com/387249/114471489-96fcef80-9ba5-11eb-948f-ceb4644dd297.png">

## Expected result:
The prompt should read `Are you sure you want to remove the selected device from the sync chain?`

Suggestions:
1. Add "the" before "selected device"
2. Add "the" before "sync chain?"
3. Change delete to remove, to match the Remove column heading

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.25.10 Chromium: 90.0.4430.61 (Official Build) nightly (x86_64)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

**Comment by rahulsnkr** [comment]
Can I take this up?

**Comment by stephendonner** [comment]
Verified `FIXED` using `nightly` build 

Brave | 1.25.46 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3 (Build 20E232)

<img width="1714" alt="Screen Shot 2021-04-27 at 3 39 08 PM" src="https://user-images.githubusercontent.com/387249/116321460-f5fa6100-a76e-11eb-82a7-4ccd3ab26d05.png">


Confirmed the text now says `Are you sure you want to remove the selected device from the sync chain?`

Thanks again for the fix, @rahulsnkr! 👍  (And for reviewing and landing, @AlexeyBarabash!)
