### ISSUE TITLE
Check logic for wallet with `setSafetynetCheckFailed`

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#15256]
## Description 
`getSafetynetCheckFailed` is called (ex: https://github.com/brave/brave-core/blob/a02f47951f169e74e025e9de1254cd12eadfb096/android/java/org/chromium/chrome/browser/toolbar/top/BraveToolbarLayout.java#L280) but I think we need to check Safetynet before creating a wallet and then capture result of the check (calling `setSafetynetCheckFailed`)

More information here:
https://bravesoftware.slack.com/archives/C0816QH3R/p1611763298052200?thread_ts=1611761467.045800&cid=C0816QH3R

**Comment by Miyayes** [comment]
1. During initial wallet generation, check SafetyNet. If fail, disable ads (but rest of Rewards initializes as normal). 
2. Whenever user touches Brave Ads toggle, show error modal that says: "Sorry, Brave Ads is not supported on your device."

cc: @jsecretan @deeppandya

**Comment by enxio27** [comment]
Brave Rewards should NOT depend on a (privacy-invading) Google service such as SafetyNet.
