### ISSUE TITLE
custom background for NTP

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#15252]
## Description 

On the new tab page, expose settings to allow users to customize the new tab page with colors, gradients, Brave wallpapers, or their own images that they upload. 

## Design and UX
Prototype link: https://www.figma.com/proto/FMuS3IZbzqzQTyRHz42Oix/Desktop-NTP?node-id=1016%3A90&viewport=607%2C480%2C0.1668190062046051&scaling=min-zoom&page-id=1016%3A89

![prototype](https://user-images.githubusercontent.com/2388823/114618748-94120580-9c5e-11eb-878b-683c12921353.gif)

The new feature includes a set of solid colors for users to choose from:

![image](https://user-images.githubusercontent.com/2388823/114616915-4c8a7a00-9c5c-11eb-84c8-2620c28f883c.png)

The new feature includes a set of gradients for users to choose from:

![image](https://user-images.githubusercontent.com/2388823/114616828-32509c00-9c5c-11eb-9506-70553d1e7f22.png)

### Sponsored images toggle

The sponsored images toggle is at the top level under Customize Dashboard > Background images. Users are able to have sponsored images on/off independently of whether they have their own uploaded background, a Brave background, solid color, or gradient background selected. When the user has Brave Ads off, it will prompt them to "Start using Rewards". 

![image](https://user-images.githubusercontent.com/2388823/114618955-d63b4700-9c5e-11eb-90c4-31611d7b832a.png)

Once clicked, the Rewards onboarding tutorial will show. 

![image](https://user-images.githubusercontent.com/2388823/114619070-fec34100-9c5e-11eb-9021-3ee6c1c922e5.png)

When the user visits the sponsored images toggle again, the "Start using Rewards" button will be hidden and it will inform them that they are earning tokens for seeing sponsored images.

![image](https://user-images.githubusercontent.com/2388823/114618987-e0f5dc00-9c5e-11eb-8956-1083f2022e37.png)

### Dark theme

Dark theme is supported: 

![image](https://user-images.githubusercontent.com/2388823/114619436-6b3e4000-9c5f-11eb-9345-68b62ee20969.png)

![image](https://user-images.githubusercontent.com/2388823/114619444-6e393080-9c5f-11eb-9a16-1e25ffb05d99.png)

## Assets
Figma: https://www.figma.com/file/FMuS3IZbzqzQTyRHz42Oix/?node-id=900%3A32768

Some interaction states are not included in the above Figma file because they use our shared Brave button and toggle components. Refer to the component documentation. 

- Buttons: https://www.figma.com/file/z9wmg2FCwuXx9FLbDo5avJ/Platform-UI-Brave-desktop?node-id=1011%3A0
- Toggles: https://www.figma.com/file/z9wmg2FCwuXx9FLbDo5avJ/Platform-UI-Brave-desktop?node-id=1051%3A128

## Sub tasks

- [x] [Use custom images for background](https://github.com/brave/brave-browser/issues/19640)
- [x] Use custom solid/gradient colors for background
- [x] Improve sponsored images toggle option
- [x] Support multiple custom images uploading and shuffle randomly(https://github.com/brave/brave-browser/issues/25761)

**Comment by bsclifton** [comment]
If we share a design here, we can probably close out https://github.com/brave/brave-browser/issues/5838 and https://github.com/brave/brave-browser/issues/11962

Main tracking issue for NTP requests can be found here: https://github.com/brave/brave-browser/issues/353

**Comment by karenkliu** [comment]
Designs added!

**Comment by StefanLobbenmeier** [comment]
You did not mention chrome plugins that provide a custom background in your description, is that intentionally not included or will that automatically work with one of the options anyway?

**Comment by edkazcarlson** [comment]
Are the figma links not working for anyone else? I get file not found errors when I try to access them

**Comment by StefanLobbenmeier** [comment]
I also get 

```
File not found

Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.
```

**Comment by AgentAdam12** [comment]
I also can't access the figma links.

**Comment by Whatever2810** [comment]
Till when is it supposed to arrive ??

**Comment by saaries** [comment]
Still waiting for this NTP feature :)

**Comment by Vignesh-Ganesan-008** [comment]
> Still waiting for this NTP feature :)

Ya, me too :)

**Comment by soumya997** [comment]
waiting for this NTP feature. Hope it will come soon.

**Comment by DrainBamage33** [comment]
When is it expected to be released?

**Comment by Uriegas** [comment]
@DrainBamage33 I think is today: [https://brave.com/latest/](https://brave.com/latest/)

**Comment by pythonmaxi** [comment]
> @DrainBamage33 I think is today: https://brave.com/latest/

On the latest brave nightly release (v1.32.39), this does not seem to be implemented...

**Comment by christophehad** [comment]
In the meantime, could you point where in the html/js start page source code you set the background image?

**Comment by indig0F10w** [comment]
> On the new tab page, expose settings to allow users to customize the new tab page with colors, gradients, Brave wallpapers, or their own images that they upload.

Anything but a plain dark new tab, am I right?

I know this is now extremely annoying to Brave devs but almost two years have passed since I know about users requesting a simple, no image, no gradient, plain dark NTP.

I ain't no UI designer but gradients as backgrounds have gone extinct like twenty years ago and you can see why by the examples given as "Gradient tests". Make a poll among Brave devs/users to see who, if anyone, uses gradients as NTP or as background anywhere. None of the other mainstream browsers uses them, no decent web page uses them but for some reason Brave wants to resurrect them.

You go into so much effort on these gradients, sponsored images and the simplest black page background doesn't exist.

I also wonder why are the devs refusing to answer multiple questions about where does Brave save these prefs so users can manually edit the purple gradient and replace it with custom color.

**Comment by simonhong** [comment]
> In the meantime, could you point where in the html/js start page source code you set the background image?

Hello @christophehad,

Regarding to background image url, two different parts are related.
The one is webui part below. WebUI renders background image by using image src provided from browser process.
https://github.com/brave/brave-core/blob/master/components/brave_new_tab_ui/containers/newTab/index.tsx#L95 

Below is where background image data is passed to webui (renderer).
https://github.com/brave/brave-core/blob/master/browser/ui/webui/new_tab_page/brave_new_tab_message_handler.cc#L587

Sorry for late but hope this helps.

**Comment by simonhong** [comment]
> Anything but a plain dark new tab, am I right?

@indig0F10w , we have blank NTP option. In the dark theme, NTP is just empty dark page.
But, maybe below option is not exactly what you want?
![image](https://user-images.githubusercontent.com/6786187/146768015-d17187a9-371e-4fdb-89ad-5fe17bf4ef39.png)

**Comment by indig0F10w** [comment]
Hello, sry for late response. That blank page is the way to go, I don't know how I missed that option. I believe it wasn't always there? It is bizzare to think that this background cannot be implemented on dashboard page instead of gradients for like two+ years now.

As for not responding to prefs questions I didn't mean you personally, I've just came about a lot of not answered questions about the same thing because I also wanted to know how and where can gradients be eliminated manually until somekind of update resolves this.

Thanks.

P.S. Happy New year to everybody.

**Comment by mjesusoj** [comment]
This idea seems very good, I hope the team implements in the future 🤯

**Comment by kerryj89** [comment]
Trying out Brave browser for the first time and I'm a bit mystified why we can't change the background color yet, but otherwise the browser has been good to me! I think in the future you should go for more subtle defaults; I understand the color you chose was to strengthen your branding cohesion but the colors are so vibrant I feel like I'm getting punched in the face with it on each new tab especially at night.  I hope this gets implemented soon, thanks!

**Comment by addycb** [comment]
Please fix team this is important QOL feature :D

**Comment by bsclifton** [comment]
Kudos to @simonhong for working on this and having a pull request ready for review! 😄 

Folks wanting to follow along can check it out here:
https://github.com/brave/brave-core/pull/11622

We'll need to do our code review and security/privacy review - but the feature is code complete

**Comment by mikewesten** [comment]
Do it. Default new start page is unusable with that rainbow sherbet vomit for a background. #000000 or bust

**Comment by indig0F10w** [comment]
> Is this still not going to happen?

M8, it's like asking Brave devs what color should be used as dark color theme. Most of the world and every other browser will say black or some version of black. Brave devs will say #343546 so you have to install black theme for a browser which followed system theme before "redesign".

**Comment by nichita-pasecinic** [comment]
Waiting for 6 months for this feature :))
any estimations ?

**Comment by simonhong** [comment]
@nichita-pasecinic First part (https://github.com/brave/brave-browser/issues/19640) will be released first and it's in beta now.

**Comment by nichita-pasecinic** [comment]
@simonhong thanks a lot ))

**Comment by mjesusoj** [comment]
Is in the version beta of the Navigator Brave? I downloaded this morning jaja

**Comment by simonhong** [comment]
> Is in the version beta of the Navigator Brave? I downloaded this morning jaja

Yes, current beta (v1.37.77). You can configure your image as a background in the below NTP customize option.
<img width="748" alt="image" src="https://user-images.githubusercontent.com/6786187/156373580-6e92659a-8cde-4f61-bcee-1b66477e8383.png">

**Comment by mjesusoj** [comment]
Yes I just install the version beta and I use this option, looks very nice. My congratulations 🎉🎉

**Comment by aednichols** [comment]
Oh man do I have lucky timing, I just started using Brave this week and this is the only part I didn't like. Thank you devs!

**Comment by weeebdev** [comment]
I guess should also consider to add custom unsplash collection urls @simonhong @rebron

**Comment by petemill** [comment]
As an aside, I see in the design we have an ability to select a specific brave background and turn off the "random" backgrounds. @rebron @aguscruiz what should we do if the user has chosen one of Brave's current packaged backgrounds specifically and then we update the package of backgrounds. At that point we will no longer have the previous set of jpgs locally on the user's machine. Should we, e.g. revert to showing random brave backgrounds from the new set?

**Comment by mjesusoj** [comment]
I think the other option, the user can select an album with the options, when spend 10 min, automatic select other one. What are you think?

**Comment by rebron** [comment]
> As an aside, I see in the design we have an ability to select a specific brave background and turn off the "random" backgrounds. @rebron @aguscruiz what should we do if the user has chosen one of Brave's current packaged backgrounds specifically and then we update the package of backgrounds. At that point we will no longer have the previous set of jpgs locally on the user's machine. Should we, e.g. revert to showing random brave backgrounds from the new set?

This becomes troublesome. Easy to say revert to showing random Brave backgrounds but the ideal is to keep their selected image. Is there a way to save that selected background locally? Otherwise, I don't know if we give users the ability to choose a selected background image without storing it.

**Comment by sangwoo108** [comment]
> Is there a way to save that selected background locally?

Yeah, I believe it's possible. If we can keep brave backgrounds not to have expiring date, we can copy and keep the selected background as long as a user wants. Then brave background component can be updated without hurting it.

**Comment by sangwoo108** [comment]
> > Is there a way to save that selected background locally?
> 
> Yeah, I believe it's possible. If we can keep brave backgrounds not to have expiring date, we can copy and keep the selected background as long as a user wants. Then brave background component can be updated without hurting it.

I was looking into this, but unfortunately, things were more difficult than I expected. Not only the image, but also the metadata should be backed up. So, I would prefer the easy way: revert to random background, but I think it's up to you, @rebron . What do you think about this? Just like we talked today, reverting it to random background and giving users the raw files so that they can use it as custom background is enough?

**Comment by rebron** [comment]
Revert to random background image and we can post older images on community that folks can upload as they please.

**Comment by sangwoo108** [comment]
Can we consider "Showing reward onboarding tutorial on NTP, not bubble anchored to reward button toolbar" as another task? As we have a reward widget and I guess that also should show reward tutorial on NTP too?

**Comment by sangwoo108** [comment]
Hi, @rebron @aguscruiz ! I'm looking around our code to plan `Support multiple custom images uploading and shuffle randomly`. I wonder how many custom images can be added. Is there specific number in your mind?

**Comment by rebron** [comment]
Closing as complete with https://github.com/brave/brave-browser/issues/25761 done.
