### ISSUE TITLE
Fingerprinting v3: Dark Mode detection

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#15265]
New CSS features allow sites to determine if your OS or environment is configured for Dark Mode (or similar names).  See [CSS Media Queries Level 5](https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-color-scheme)

We should disable this detection for users wanting the highest level of fingerprinting protection ("strict").

**default protections**: no changes
**max protections**: always report that the user prefers "light"

**Comment by stephendonner** [comment]
@ShivanKaul @pes10k when you get a chance, can you add a testcase/testplan to https://github.com/brave/brave-core/pull/8832?  Thanks!

**Comment by pes10k** [comment]
No problem, here ya go: https://dev-pages.brave.software/fingerprinting/strict-mode.html

The values for the strict mode row should accurately report whether the system has dark mode enabled with default fingerprinting protections, and should always report "dark mode not detected" (regardless of system settings) in strict mode

**Comment by stephendonner** [comment]
**Verified `PASSED`** using 

Brave | 1.27.65 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

**Steps:**
1. enabled Dark mode via System Preferences -> General -> Appearance
2. loaded `https://dev-pages.brave.software/fingerprinting/strict-mode.html`
3. clicked on `Generate Values`
4. clicked on `This Frame`, `Local Frame` and `Remote Frame` hash values
5. confirmed `detected dark mode` displayed for `Shields off`/`Allow all fingerprinting`, and `standard fingerprinting` settings
6. confirmed `dark mode not detected` displayed for `strict fingerprinting` setting
7. repeated the above for `https://dev-pages.bravesoftware.com/fingerprinting/strict-mode.html`


`https://dev-pages.brave.software/fingerprinting/strict-mode.html`

standard fingerprinting | strict fingerprinting
-----------------------|-------------
<img width="1769" alt="Screen Shot 2021-06-15 at 10 36 49 AM" src="https://user-images.githubusercontent.com/387249/122098705-066da600-cdc6-11eb-9c1c-7c35750917dd.png"> | <img width="1769" alt="Screen Shot 2021-06-15 at 10 37 17 AM" src="https://user-images.githubusercontent.com/387249/122098718-08376980-cdc6-11eb-8593-a11d995990b4.png">

`https://dev-pages.bravesoftware.com/fingerprinting/strict-mode.html`

standard fingerprinting | strict fingerprinting
------------------------|------------
<img width="1769" alt="Screen Shot 2021-06-15 at 10 36 12 AM" src="https://user-images.githubusercontent.com/387249/122098962-52b8e600-cdc6-11eb-88e5-e9aa61e611a0.png"> | <img width="1769" alt="Screen Shot 2021-06-15 at 10 36 24 AM" src="https://user-images.githubusercontent.com/387249/122098963-53517c80-cdc6-11eb-82f2-410caa435b88.png">

**Comment by TheCultLeader666** [comment]
I don't know how others feel, but personally I would not appreciate this feature. Detecting dark mode seems like an overall good thing, as a site can adjust to your preferences, and serve the right favicon for best visibility. It's one of the reasons I don't use Firefox's RFP (That and the timezone spoofing), and it doesn't seem like it's that big of a deal. Sure, it can factor in to your fingerprint. But it's a binary measurement, on or off, and from what I've seen, it's fairly 50/50. If you're faking everything else, this seems like something you can let slide, as, by itself, it provides very little fingerprintable surface.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.27.75 x64 Beta build
- Verified dark mode is detected when fingerprint is set to standard
- Verified dark mode is not detected when fingerprint is set to strict
- Verified setting theme to dark manually works fine 
- Verified setting device theme to dark and browser theme to use system default, sets browser to dark theme and dark theme recognition works fine as expected

`https://dev-pages.bravesoftware.com/fingerprinting/strict-mode.html`
Fingerprint (Strict) | Fingerprint (Standard)
-- |--
![image](https://user-images.githubusercontent.com/17010094/123123802-095c3c80-d43f-11eb-9852-f3a9d91810f4.png) | ![image](https://user-images.githubusercontent.com/17010094/123123749-fd707a80-d43e-11eb-8a01-8e1ab32ee43e.png)


`https://dev-pages.brave.software/fingerprinting/strict-mode.html`
Fingerprint (Strict) | Fingerprint (Standard)
-- |--
![image](https://user-images.githubusercontent.com/17010094/123119050-1545ff80-d43b-11eb-9a19-c6e9101edcd8.png) | ![image](https://user-images.githubusercontent.com/17010094/123119071-1b3be080-d43b-11eb-9d43-62b7879b7471.png)

---------
Verification passed on Samsung Tab A with Android 10 running 1.27.75 x64 Beta build
- Verified dark mode is detected when fingerprint is set to standard
- Verified dark mode is not detected when fingerprint is set to strict
- Verified setting theme to dark manually works fine 
- Verified setting device theme to dark and browser theme to use system default, sets browser to dark theme and dark theme recognition works fine as expected

`https://dev-pages.bravesoftware.com/fingerprinting/strict-mode.html`
Fingerprint (Strict) | Fingerprint (Standard)
-- |--
![image](https://user-images.githubusercontent.com/17010094/123123575-d74ada80-d43e-11eb-913b-822a7af62ae5.png) | ![image](https://user-images.githubusercontent.com/17010094/123123605-ddd95200-d43e-11eb-8093-eafddc8ee83e.png)

`https://dev-pages.brave.software/fingerprinting/strict-mode.html`
Fingerprint (Strict) | Fingerprint (Standard)
-- |--
![image](https://user-images.githubusercontent.com/17010094/123123531-ce5a0900-d43e-11eb-82d2-9bcf6200c24f.png) | ![image](https://user-images.githubusercontent.com/17010094/123123505-cac68200-d43e-11eb-8b42-8e290dd780b6.png)
