### ISSUE TITLE
Uphold 25 BAT minimum modal triggering in bitFlyer flow

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#15264]
@Miyayes encountered an issue where he was testing the bitFlyer flow, but he received an error modal about the Uphold 25 BAT minimum. After some investigation, @zenparsing noticed that if the claim endpoint returns a `404`  it's converted into `NOT_FOUND` and can accidentally trigger the modal. This may not be the issue we're seeing, but it is one way that it could happen so best to fix it.

### Steps to Reproduce

1. Generate a wallet ID while connected to production 
2. Relaunch the browser in staging mode
3. Go through the verify wallet process (which will correctly go against staging servers)
4. Note that everything works until you're redirected back to to the brave://rewards page, where it will fail and show the Uphold error

Presumably, underlying issue is that the wallet ID is not found, since that wallet ID is in the production db and not in the staging db.

**Comment by emerick** [comment]
@Miyayes Our original fix for this addresses the new STR as well, so I'll close this out. One thing to note, however, is that an error like this drops us into a modal that only offers a "Try again" option. In a scenario like this, trying again isn't going to fix anything. We should have another option in there to dismiss the modal.

**Comment by Miyayes** [comment]
Thanks @emerick. I also just filed: https://github.com/brave/brave-browser/issues/15338 regarding the close button! I remember being sent in loops because there was no close button ;)

**Comment by stephendonner** [comment]
Using 

Brave | 1.25.28 Chromium: 90.0.4430.72 (Official Build) nightly (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

I did the following:

1. launched with `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6`
2. enabled Rewards
3. confirmed via `brave://rewards-internals` that I had a local wallet created
4. launched with `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
5. clicked on `verify wallet` in `brave://rewards`
6. logged in to Uphold on staging (`https://wallet-sandbox.uphold.com/`)
7. was returned successfully to `brave://rewards`
8. confirmed that my original wallet is now verified

example | example | example | example
--------|-----------|---------|---------
<img width="1312" alt="Screen Shot 2021-04-20 at 3 11 57 PM" src="https://user-images.githubusercontent.com/387249/115470766-ac000100-a1eb-11eb-85ce-192a57f98208.png"> | <img width="1312" alt="Screen Shot 2021-04-20 at 3 12 20 PM" src="https://user-images.githubusercontent.com/387249/115470767-ac989780-a1eb-11eb-8bd4-042d49603982.png"> | <img width="1312" alt="Screen Shot 2021-04-20 at 3 12 43 PM" src="https://user-images.githubusercontent.com/387249/115470769-ad312e00-a1eb-11eb-82d9-355788dcc96d.png"> | <img width="1312" alt="Screen Shot 2021-04-20 at 3 12 55 PM" src="https://user-images.githubusercontent.com/387249/115470770-ad312e00-a1eb-11eb-9f64-0703ce6a8b74.png">


@emerick @Miyayes is this correct?  Should I be seeing the error above, instead?  Did this need to be tested with the `bitFlyer` feature flag enabled, instead?  Sorry and thanks!

**Comment by stephendonner** [comment]
Am currently "correctly" testing this with:
a) Japan region specified in macOS
b) Japanese language set
c) bitFlyer feature flag enabled

Am still seeing two-factor auth challenge on login, which @Miyayes will ask the bitFlyer folks to remove, hopefully tonight, so this can be retested tomorrow, in which case I'll update all of the above steps with corrections 👍
