### ISSUE TITLE
Upgrade from Chromium 89.0.4389.114 to Chromium 89.0.4389.128 (1.22.x).

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#15270]
Minor Chromium bump.

https://chromium.googlesource.com/chromium/src/+log/89.0.4389.114..89.0.4389.128?pretty=fuller&n=10000

QA tests:

Check branding items
Check for version bump

Additional checks:

No specific code changes in Brave (only line number changes in patches).

**Comment by LaurenWags** [comment]
Closing issue as this was merged via https://github.com/brave/brave-browser/pull/15271 and https://github.com/brave/brave-core/pull/8531

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.22.72 Chromium: 89.0.4389.128 (Official Build) (64-bit)
-- | --
Revision | 6d949d51e94419a5014d249141019d8bffc75f69-refs/branch-heads/4389@{#1640}
OS | Windows 10 OS Version 2004 (Build 19041.867)

```
![image](https://user-images.githubusercontent.com/38657976/114711260-61463b00-9d4c-11eb-9f71-1e6953f2ca59.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.22.72 x64 build

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/114723460-93e33a00-9d32-11eb-9452-b0e2bb26da80.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/114723542-a5c4dd00-9d32-11eb-8f4f-13075b02125d.png>
