### ISSUE TITLE
Disable and enable Fingerprint settings sets it to strict mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15288]
## Description 
Disable and enable Fingerprint settings sets it to strict mode

## Steps to reproduce 

   1. Clean install 1.22.71
   2. Visit a page and check shields for FP, set to standard
   3. Disable FP from global settings
   4. Check the FP settings in shields, set to allow all
   5. Enable FP from global settings 
   6. Visit a new page in a new tab, FP in set to strict
   
## Actual result 

https://user-images.githubusercontent.com/17010094/114726748-9004e700-9d35-11eb-8d42-06a640a9fb00.mp4

## Expected result
Enabling FP should set it to standard and not strict

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.22.71

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya  @samartnik @anthonypkeane

**Comment by anthonypkeane** [comment]
Can you please retest @srirambv

**Comment by srirambv** [comment]
This is fixed now. Verified on 1.28.105 current release. The settings panel is changed which fixed the issue.
