### ISSUE TITLE
Tor Status disconnected constantly

### ISSUE THREAD

**Issue by Legendhidde** [brave/brave-browser#15284]
## Description 
Every time I open a private window with TOR in the Brave browser it shows "Tor Status: Disconnected". Cannot load any webpages at all using the TOR private window.

## Steps to Reproduce
   1. Open new private window with TOR
   2. Problem.

## Actual result:
Tor Status: Disconnected

## Expected result:
Tor Status: Initializing
OR
Tor Status: Connected

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Windows 10 OS Version 2009 (Build 19042.928)

## Version/Channel Information:
Happens on the current release. Haven't tested beta or nightlies.

## Other Additional Information:
Issues is resolved once after deleting the data folder from "C:/Users/currentuser/AppData/Local/BraveSoftware/Brave-Browser/User Data/tor"

Comes back immediately after closing the private window with Tor.

Tor log says this:
Apr 14 13:17:57.000 [notice] Tor 0.4.5.7 opening new log file.
Apr 14 13:17:57.432 [notice] We compiled with OpenSSL 101010bf: OpenSSL 1.1.1k  25 Mar 2021 and we are running with OpenSSL 101010bf: 1.1.1k. These two versions should be binary compatible.
Apr 14 13:17:57.436 [notice] Tor 0.4.5.7 running on Windows 8 [or later] with Libevent 2.1.11-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Apr 14 13:17:57.436 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Apr 14 13:17:57.436 [notice] Configuration file "C:\nonexistent" not present, using reasonable defaults.
Apr 14 13:17:57.436 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\89.1.22.71\<default>. Is this what you wanted?
Apr 14 13:17:57.437 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\89.1.22.71\<default>. Is this what you wanted?
Apr 14 13:17:57.437 [notice] Opening Socks listener on 127.0.0.1:0
Apr 14 13:17:57.438 [notice] Socks listener listening on port 62791.
Apr 14 13:17:57.438 [notice] Opened Socks listener connection (ready) on 127.0.0.1:62791
Apr 14 13:17:57.438 [notice] Opening Control listener on 127.0.0.1:0
Apr 14 13:17:57.438 [notice] Control listener listening on port 62792.
Apr 14 13:17:57.438 [notice] Opened Control listener connection (ready) on 127.0.0.1:62792
Apr 14 13:17:57.000 [notice] Bootstrapped 0% (starting): Starting
Apr 14 13:17:57.000 [notice] Starting with guard context "default"
Apr 14 13:17:58.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Apr 14 13:17:58.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Apr 14 13:17:58.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Apr 14 13:17:58.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Apr 14 13:17:58.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Apr 14 13:17:58.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Apr 14 13:17:58.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Apr 14 13:17:59.000 [notice] Bootstrapped 100% (done): Done
Apr 14 13:17:59.000 [notice] New control connection opened from 127.0.0.1.

## Miscellaneous Information:
I have multiple network adapters for my VPN and game controller wireless dongle that might interfere.

**Comment by rebron** [comment]
@Legendhidde We just updated to 1.23.71. Can you update to that and let me know if you're still having issues. Can you also look at brave://components and tell me what you have under Brave Tor Client Update version

**Comment by Legendhidde** [comment]
> @Legendhidde We just updated to 1.23.71. Can you update to that and let me know if you're still having issues. Can you also look at brave://components and tell me what you have under Brave Tor Client Update version

The update fixed it! Must have been because the fix to orphan processes, 14044

**Comment by rebron** [comment]
Closing per last comment. Thanks for letting us know @Legendhidde
