### ISSUE TITLE
Using Bat/brave ad Network in my game

### ISSUE THREAD

**Issue by navidalvee** [brave/brave-browser#15283]
Hello,

Currently, I am developing a Free-to-play game
is it possible to get Brave/BAT advertisement network in my game
to show ads to the players and get rewards in crypto

**Comment by hollons** [comment]
Hi @navidalvee, thanks for writing in. Brave's ad ecosystem is currently only available within the browser. If you'd like to learn more please check out Community.brave.com. Thanks!
