### ISSUE TITLE
Two new tab events are triggered when a new tab is opened

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15285]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/14045

 `Opened a new tab with id` is triggered twice when a new tab is opened

## Steps to Reproduce

   1. Clean profile 1.23.x
   2. Follow the test steps for the case `User Activity - Default values - Threshold - not reached` in https://github.com/brave/internal/issues/763
   3. Follow the steps till enabling rewards (step 8)
   4. Open a new tab by clicking on `+` icon
   5. Watch the logs 
   6. Two new tab events are triggered `Opened a new tab with id 7` and `Opened a new tab with id 5`

## Actual result:

Two new tab events are triggered `Opened a new tab with id 7` and `Opened a new tab with id 5`

## Expected result:

Only one new tab event should be triggered
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.23.70 Chromium: 90.0.4430.70 (Official Build) (64-bit)
-- | --
Revision | 3954de7175366f3b7edca576f140dfa273e6b5ae-refs/branch-heads/4430@{#1210}
OS | Windows 10 OS Version 2004 (Build 19041.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @moritzhaller @jsecretan

**Comment by btlechowski** [comment]
Not reproducible on Linux

Brave | 1.23.69 Chromium: 90.0.4430.61 (Official Build) (64-bit)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | Ubuntu 18.04 LTS

**Comment by tmancey** [comment]
Closing as working as expected as two different tabs were opened. One from rewards and another when you manually typed the url. Thanks

**Comment by GeetaSarvadnya** [comment]
@tmancey I have opened only one new tab. I have enabled rewards from BR panel but I haven't clicked on rewards settings to open the rewards tab. I have just clicked on `+` new tab icon and which triggered two new tab events with diff ids. The issue was reproducible only for Windows. I will provide the recorded file shortly.

**Comment by GeetaSarvadnya** [comment]
@tmancey Please find the recorded file, I can reproduce the issue consistently in windows, after enabling rewards, I am not clicking on `Rewards setting` in the BR panel hence there is no tab which has brave://rewards page. After enabling rewards I am just clicking on `+` icon a new tab is opened but two events are triggered in the log:
`Opened a new tab with id 5` and `Opened a new tab with id 7` which is wrong as I have opened only one new tab.


https://drive.google.com/file/d/1qTv7IHa3C4ShQcCN9OwsKU09Q1gRu-zx/view?usp=sharing

**Comment by tmancey** [comment]
@GeetaSarvadnya This is working as expected as on the video I only see the 2nd "Opened a new tab with id" appear when you open the About page.
