### ISSUE TITLE
iframe with src="about:blank" is not shown

### ISSUE THREAD

**Issue by jorisdebock** [brave/brave-browser#15286]
## Description 
iframe with src="about:blank" is set to display:none when brave shield is up

## Steps to Reproduce

   1. Have a page with 
```
<iframe src="about:blank"></iframe>
```
   2.  Have Brave shield up

## Actual result:
![image](https://user-images.githubusercontent.com/10253291/114717259-2be22300-9d35-11eb-913d-9e7d047c699e.png)

## Expected result:
Not set display:none for an iframe with src="about:blank"

## Reproduces how often: 
always

## Brave version (brave://version info)
```
Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Windows 10 OS Version 2009 (Build 19042.804)
```

**Comment by ryanbr** [comment]
Hey, this is fixed in upstream, removed filter. give 24-48hrs. @jorisdebock

**Comment by jorisdebock** [comment]
👍 working again
```
Brave | 1.22.72 Chromium: 89.0.4389.128 (Official Build) (64-bit)
Revision | 6d949d51e94419a5014d249141019d8bffc75f69-refs/branch-heads/4389@{#1640}
```
