### ISSUE TITLE
Reddit Tip button is incorrectly positioned

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#15287]
## Description 

The Rewards "Tip" button is formatted incorrectly when visiting reddit.com. Possibly related to https://github.com/brave/brave-browser/issues/9556.

## Steps to Reproduce

   1. Visit reddit.com

## Actual result:

"Tip" button is incorrectly formatted:

![image](https://user-images.githubusercontent.com/5033691/114727837-8dda6280-9d0c-11eb-91f5-ad0945a46ab9.png)

## Expected result:
Tip button is correctly formatted, appearing between `Save` and `...` buttons.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Current `master`.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.27.108 Chromium: 92.0.4515.107 (Official Build) (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 10.15.7 (Build 19H1217)
```

and dev component version `1.0.48`.

Reproduced the issue with prod component version `1.0.42`.
Confirmed when using `1.0.48` the Tip button is spaced correctly on comments I've authored when logged in to Reddit.

`1.0.42` | `1.0.48`
----- | -----
<img width="1233" alt="15287-prod" src="https://user-images.githubusercontent.com/28145373/126997149-dccca53a-910a-4138-9f40-a5b3be2de38c.png"> | <img width="1228" alt="15287-dev" src="https://user-images.githubusercontent.com/28145373/126997157-c1d9db2c-826a-40dc-9f28-6f71fa5a1115.png">
