### ISSUE TITLE
Support branding_path_component

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#153]
Currently, only `brave` brand name is used and some places uses unofficial brand name in temporarily.
Instead of changing it locally, use global `brand_path_component` for our official/unofficial build.
Brand would be `brave` and `brave-dev` or `brave-development`.

**Comment by simonhong** [comment]
@bbondy I think this can be moved to backlog because we did this by copying branding resource by script.

**Comment by kjozwiak** [comment]
Closing the above as it's labelled as `closed/stale` so there's no need for the above to stay opened.
