### ISSUE TITLE
Don't do DNS lookups for CNAME decloaking for adblock for already-blocked requests

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#15302]
Brave looks up CNAME information for all requests so that we can make blocking decisions on the entire CNAME chain (when relevant).  Currently the CNAME / DNS information is fetched before making any blocking decisions. This results in unnecessary DNS calls when we can make a blocking determination from the initial URL (or at least earlier on before reaching the end of a CNAME chain).

We should optimize our CNAME decloaking, and prevent non-useful DNS requests, by waiting to fetch CNAME records until we need them (i.e., we shouldn't do any checks when we can make a blocking determination from the initial, or middle of the CNAME chain, URL and host information).

**Comment by stephendonner** [comment]
Verified `PASSED` on macOS for the first two testcases from https://github.com/brave/brave-core/pull/8704 using build 

Brave | 1.26.24 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:

### DoH off

1. follow the section Using the (Pre)-Master-Secret to set up SSLKEYLOGFILE (`https://wiki.wireshark.org/TLS#Using_the_.28Pre.29-Master-Secret`)
2. After Wireshark is capturing traffic, use the dns filter
3. new profile, launch Brave
4. go to `brave://settings/security` and set `Use secure DNS` via the toggle to `off`
5. open Tor window
6. navigate to `https://tools.ietf.org`
7. after site loaded, stop Wireshark capturing
8. there shouldn't be any DNS query or DoH query for `tools.ietf.org`

**confirmed there were no CNAME / DNS lookups for `tools.ietf.org` in Wireshark**

<summary><summary>
<details>screenshots

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-05-18 at 3 43 20 PM" src="https://user-images.githubusercontent.com/387249/118734040-60dd0c00-b7f2-11eb-8272-1e40792e98f8.png"> | <img width="1415" alt="Screen Shot 2021-05-18 at 3 41 54 PM" src="https://user-images.githubusercontent.com/387249/118733393-068f7b80-b7f1-11eb-8032-ae3904c6b487.png">
</details>

### DoH enabled

1. follow the section Using the (Pre)-Master-Secret to set up SSLKEYLOGFILE (`https://wiki.wireshark.org/TLS#Using_the_.28Pre.29-Master-Secret`)
2. after Wireshark is capturing traffic, use the dns filter
3. new profile, launch Brave
4. go to `brave://settings/security` and make sure `Use secure DNS` is toggled to `on` and `With Cloudflare (1.1.1.1)` is checked
5. open Tor window
6. navigate to `https://tools.ietf.org`
7. after site finishes loading, stop Wireshark capturing
8. there shouldn't be any DNS query or DoH query for `tools.ietf.org`

**confirmed there were no CNAME / DNS lookups for `tools.ietf.org` in Wireshark**

<summary><summary>
<details>screenshots

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-05-18 at 3 43 14 PM" src="https://user-images.githubusercontent.com/387249/118733892-13609f00-b7f2-11eb-8734-60c8de4a820c.png"> | <img width="1407" alt="Screen Shot 2021-05-18 at 3 45 44 PM" src="https://user-images.githubusercontent.com/387249/118733290-dd6eeb00-b7f0-11eb-96da-a65ef9bf246a.png"> 
</details>

### MacRumors.com / googletagmanager
I filed https://github.com/brave/brave-browser/issues/15953 for macOS-specific behavior; Windows 10 is working fine, but I haven't checked Linux.

/cc @brave/legacy_qa

**Comment by srirambv** [comment]
Verification done on OnePlus 6T with Android 10 running 1.26.63 x64 build
- Encountered https://github.com/brave/brave-browser/issues/15953#issuecomment-864793277

Removing Android label as the Tor windows is not possible on Android. 

cc: @antonok-edm @pes10k
