### ISSUE TITLE
Non thread-safe PostTasks in AdBlockBaseService

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#15309]
`AdBlockBaseService` and corresponding classes are created and stored as `unique_ptr`s, but used from different threads. The proper way is to store them as `scoped_refptr` and take reference every time a task need to be run on a different sequence.

same behavior can be found in this files:
```
brave/components/brave_shields/browser/ad_block_base_service.cc
brave/components/brave_shields/browser/ad_block_custom_filters_service.cc
brave/components/brave_shields/browser/ad_block_regional_service_manager.cc
brave/components/cosmetic_filters/browser/cosmetic_filters_resources.cc
```

**Comment by antonok-edm** [comment]
I believe this is no longer relevant - @goodov could you take another look when you get a chance?

**Comment by goodov** [comment]
I think most issues was fixed with this PR https://github.com/brave/brave-core/pull/10994.
