### ISSUE TITLE
https://diafygi.github.io/webrtc-ips/ leaks ip address when `Block all fingerprinting protection` is ON

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15313]
## Description 
https://diafygi.github.io/webrtc-ips/ leaks ip address when `Block all fingerprinting protection` is ON

## Steps to reproduce 

   1. Clean profile 1.23.x
   2. Open https://diafygi.github.io/webrtc-ips in a new tab
   3. Observe that IP Address is shown
   4. Open shield and turn ON `Block all fingerprinting protection` FP settings

## Actual result 
https://diafygi.github.io/webrtc-ips/ leaks ip address when `Block all fingerprinting protection` is ON

## Expected result
https://diafygi.github.io/webrtc-ips/ shouldn't leak the IP Address

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Not sure
- Can you reproduce this issue with the current Play Store Nightly version? Yes in 1.25.18

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version: Samsung galaxy Tab 10
   
## Brave version
1.23.71

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @samartnik

**Comment by ryanbr** [comment]
From Brave Beta (new profile) I'm not seeing an IP address @GeetaSarvadnya 

![diafy](https://user-images.githubusercontent.com/1659004/114861625-9aaca280-9e41-11eb-8538-05a9c8d30815.png)

**Comment by srirambv** [comment]
Repro'd on OnePlus 6T with Android 10 runnin 1.23.71 x64 build

**Comment by anthonypkeane** [comment]
Linked to https://github.com/brave/brave-browser/issues/7487

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.73 x64 build
- Verified test plan from issue description

https://user-images.githubusercontent.com/17010094/115752752-51ed7000-a392-11eb-8783-29a8c639a75f.mp4

--------
Verification passed on Samsung Tab A with Android 10 running 1.23.73 x64 build
- Verified test plan from issue description

https://user-images.githubusercontent.com/17010094/115752862-6d587b00-a392-11eb-9224-7a88f56e4e7c.mp4
