### ISSUE TITLE
Rework options interface for ledger service

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#15324]
There are several functions in `RewardsServiceImpl` to allow the ledger service to retrieve various options (e.g., `GetStringOption`, `GetIntOption`, etc.). @bridiver pointed out that this is wasteful as it involves making synchronous IPC calls to the browser process just to retrieve constant values.

In chatting with @zenparsing, we were thinking it'd be better to just pass these options to the ledger service on startup (perhaps as a parameter to `mojom::BatLedgerService::Create`).

**Comment by bridiver** [comment]
the few values that are actually in there are constants so just include them where you need them

**Comment by Miyayes** [comment]
@szilardszaloki Is this still an issue now that you've made Rewards architecture changes in 1.52.x?

**Comment by szilardszaloki** [comment]
I didn't know we have an issue for that, nice! And no, it could have been closed by https://github.com/brave/brave-core/pull/18047. Closing now. 🙂
