### ISSUE TITLE
Html5 Canvas Web Font Alignment is off

### ISSUE THREAD

**Issue by shumiyao** [brave/brave-browser#15326]
## Description 

Web Font in Html5 Canvas Alignment (of games developed using Phaser Js library) is off only in Brave (Mac Desktop v. 1.23.71) while there is not any problem in Chrome, Firefox and Safari. Is this a known problem?

## Steps to Reproduce

The html5 canvas game showing the problem can be found at https://game.cuckooparrot.com/bonus-jackpot/

#### Brave Version 1.23.71 (Mac desktop)
<img width="489" alt="Brave Version 1 23 71" src="https://user-images.githubusercontent.com/50849841/114947101-6a1a3800-9e44-11eb-99ae-9a98c913ea23.png">

#### Chrome Version 89.0.4389.128 (Mac desktop)
<img width="550" alt="Chrome Version 89 0 4389 128" src="https://user-images.githubusercontent.com/50849841/114947153-7e5e3500-9e44-11eb-9f88-c5f255fb9f06.png">

#### Safari Version 14.0.3 (Mac desktop)
<img width="535" alt="Safari Version 14 0 3" src="https://user-images.githubusercontent.com/50849841/114947170-88803380-9e44-11eb-8cb2-e162c0700257.png">

 #### Firefox 85.0 (Mac desktop)
<img width="560" alt="Firefox 85 0" src="https://user-images.githubusercontent.com/50849841/114947203-9afa6d00-9e44-11eb-9925-f13578139cb5.png">

## Reproduces how often: 

Always.

## Brave version (brave://version info)

<details>
<summary>Brave Version 1.23.71 Stable (Mac desktop)</summary>

```
Brave	1.23.71 Chromium: 90.0.4430.72 (Official Build) (x86_64)
Revision	b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS	macOS Version 11.2.3 (Build 20D91)
JavaScript	V8 9.0.257.17
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PrefetchPrivacyChanges,SafetyTip,AutoupgradeMixedContent,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,LegacyTLSEnforced --disable-features=AutofillServerCommunication,TextFragmentAnchor,AutofillEnableAccountWalletStorage,IdleDetection,SafeBrowsingEnhancedProtectionMessageInInterstitials,TabHoverCards,DirectSockets,SharingQRCodeGenerator,NetworkTimeServiceQuerying,LangClientHintHeader,NotificationTriggers,WebOTP,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,BraveDomainBlock --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/shu/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations	7146a73c-3f4a17df
```
</details>

**Comment by Ayushsunny** [comment]
Hello @shumiyao Can I fix this ?

**Comment by shumiyao** [comment]
@Ayushsunny 

The program uses a library called PahserJS.

I will today make a small sample program to demonstrate the problem.

**Comment by rebron** [comment]
cc: @pilgrim-brave Farbling issue?

**Comment by pilgrim-brave** [comment]
That Brave Community post from January 2019 is obsolete; Brave's privacy protection around HTML5 APIs is now significantly more advanced than block/don't block. However, I agree that there is a real, Brave-specific bug here.

**Comment by TheCultLeader666** [comment]
I would not consider this a problem, I would consider it a feature. This is to protect against canvas fingerprinting, and it can be disabled in settings. Of course canvas elements will look buggy, as the data is given a false value by brave. I don't understand the problem here.

**Comment by shumiyao** [comment]
I could find a forum thread referring to `privacy.resistFingerprinting`

According to Telinc1 in [the thread](https://phaser.discourse.group/t/text-aligment-bug-on-linux/9145/7):

>This is a shot in the dark, but it might be worth investigating. I’ve seen browsers, often Brave, but maybe also Firefox (with privacy.resistFingerprinting enabled?) that intentionally break font rendering due to privacy concerns. If this guess is correct, I don’t think there’s anything you can do about it short of changing the browser settings.

**Comment by TheCultLeader666** [comment]
Canvas elements are vulnerable to fingerprinting. Brave prevents this by reporting a false/random value. This can be disabled in settings. I don't understand what the problem here is, or how it can be considered a problem at all.

**Comment by shumiyao** [comment]
Will post this issue to the forum to let people know about this issue.

Maybe developers can add a prompt in those html5 game pages telling Brave users to disable the protection or,

In the thread [samme](https://phaser.discourse.group/t/text-aligment-bug-on-linux/9145/7) suggests a workaround for PhaserJs (using the Text Metrics).

I have tried [the sample](http://labs.phaser.io/edit.html?src=src/game%20objects%5Ctext%5Ctext%20metrics.js) and I see that the sample does not have the problem.
