### ISSUE TITLE
[Android] Device/user information leaking when tested

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#15322]
## Description 
Android build of the app is leaking browser and device info when tested. ipleak.net (for example) was able to pull pretty much everything about my device and/or location. Appears to be a regression of:
https://github.com/brave/brave-browser/issues/12638

Images are from Nightly build but issue seems to be present on Beta and stable as well:
![image](https://user-images.githubusercontent.com/3299098/114928634-abc8c580-9de7-11eb-8163-a4229d9aeab1.png)

## Steps to reproduce 

   1. Visit ipleak.net or similar site on Brave Android
   2. Run test

## Actual result 
Device and user info is leaked.

## Expected result
Information should not leak.

## Issue reproduces how often 
Easily/always

## Version/Channel Information:

v1.22.71
- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

### Additional information

User report of the issue:
https://community.brave.com/t/phone-model-leaking-in-brave/233082/7

**Comment by srirambv** [comment]
Fixed as part of #14740

**Comment by srirambv** [comment]
Verification passed on the following devices with Android 10 running 1.23.73 x64 build
- Verified no device info is leaked

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/115749699-46e51080-a38f-11eb-8ad8-5854e59d24ea.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/115749685-42205c80-a38f-11eb-891e-cb6b1f8efa7b.png>

**Comment by kjozwiak** [comment]
We'll use https://github.com/brave/brave-browser/issues/15372 for the release notes as it's basically the same issue.
