### ISSUE TITLE
Add "Close" button in Brave Rewards wallet verification error modal 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15338]
## Description

In our Brave Rewards error modal (particularly when wallet verification fails), no "close" button is present. The user can only "Try again", in which case they are sent into a loop (unless they close out of the tab).

![image](https://user-images.githubusercontent.com/11497541/115053931-a6ce4980-9ead-11eb-9dcb-9e47ab03bbab.png)

## Solution

Add a close button that dismisses the modal. **Update:** Specifically, add an `x` button in the top right corner, per design team.

**Comment by Miyayes** [comment]
Design team (Cody) says to just add an `x` in the top right corner.

**Comment by stephendonner** [comment]
Verified `PASSED` using the steps and testplan from https://github.com/brave/brave-browser/issues/15264

Brave | 1.25.46 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3 (Build 20E232)

Steps:
1.  set my macOS region to Japan, language to Japanese, restarted the OS
2. launched Brave and enabled Rewards via the NTP page
3. relaunched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
4. via `brave://flags`, set `Enable bitFlyer for Brave Rewards` to `Enabled`, and restarted using the commandline, above
5. clicked on the Japanese-text equivalent of `Verify Wallet`
6. confirmed I was taken to the bitFlyer staging environment
7. clicked on the blue/purple button (not pictured, sorry!)
8. received an error message
9. confirmed that there was a (x) widget at the top right, and that clicking on it closed the error-message popup, and returned me to `brave://rewards` 

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="スクリーンショット 2021-04-27 16 03 46" src="https://user-images.githubusercontent.com/387249/116324200-89826080-a774-11eb-87dc-744eb2c8c586.png"> | <img width="1312" alt="スクリーンショット 2021-04-27 16 03 53" src="https://user-images.githubusercontent.com/387249/116324201-8b4c2400-a774-11eb-9619-d1b0ba125b74.png"> | <img width="1312" alt="スクリーンショット 2021-04-27 16 04 19" src="https://user-images.githubusercontent.com/387249/116324203-8d15e780-a774-11eb-8a9e-0acd3fc0cfe0.png"> | <img width="1312" alt="スクリーンショット 2021-04-27 16 05 13" src="https://user-images.githubusercontent.com/387249/116324204-8dae7e00-a774-11eb-87b2-a008f9453c28.png"> | <img width="1312" alt="スクリーンショット 2021-04-27 16 15 11" src="https://user-images.githubusercontent.com/387249/116324207-8e471480-a774-11eb-82c1-1ddac554f3ba.png">

**Comment by LaurenWags** [comment]
Close button is present, but is not working - see https://github.com/brave/brave-browser/issues/15963#issuecomment-844099577

```
Brave | 1.25.64 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;beta&nbsp;（x86_64）
-- | --
変更履歴 | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | macOS バージョン10.15.7（ビルド19H1030）
```
