### ISSUE TITLE
Add Brave Ads panel content and summary in BRewards Settings page

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#1533]
## Description 

The attached are the finalized Ads container content and the setting. Ads settings current contains only one control - **ad notification hourly frequency**.

![screen shot 2018-10-09 at 11 13 52 pm](https://user-images.githubusercontent.com/4369856/46828601-6af02180-cd50-11e8-98dc-1b709a4a2460.png)

![screen shot 2018-10-09 at 11 14 04 pm](https://user-images.githubusercontent.com/4369856/46828612-72172f80-cd50-11e8-9fe4-dcf690025788.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
done in https://github.com/brave/brave-core/pull/999

**Comment by LaurenWags** [comment]
@jenn-rhim can you help with a test plan for this one? Unsure what we should be looking at on 0.59.x specifically.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

Based on https://github.com/brave/brave-browser/issues/1533#issuecomment-452987982, Ads settings page:
![image](https://user-images.githubusercontent.com/34715963/51350341-36ef6f80-1aa8-11e9-90d2-572164352af7.png)

**Comment by srirambv** [comment]
Marking issue as Windows/Mac only as ads is not supported on Linux for now
