### ISSUE TITLE
Suspicious brave.exee.exe

### ISSUE THREAD

**Issue by RapahelS** [brave/brave-browser#15348]
## Description 
I was using the Brave Browser on Windows 10 and got a suspicious Windows Defender Firewall Message.
![Screenshot](https://i.imgur.com/S42m7Ob.png)

It asked me to give it network access. 
application name: brave.exee.exe
by unknown company

I followed the file path "C:\Program Files\BraveSoftware\Brave-Browser\Application" and there haven't been any brave.exee.exe file.

What should I do now?

**Comment by Dryader** [comment]
Maybe try reinstalling brave and check the file path to see if that exe is still there? I checked my file folder and its just brave.exe

**Comment by rebron** [comment]
@RapahelS Did you inadvertently edit the file name. It should just be brave.exe. Probably best to re-install.

**Comment by RapahelS** [comment]
I checked the path and there I can only find the brave.exe and no brave.exee.exe like shown in the message.

**Comment by rebron** [comment]
@RapahelS Going to close this one out. I looked like brave.exee.exe isn't on your machine any longer.

**Comment by RapahelS** [comment]
I got the same message agian, while browsing with brave.
Could this be some kind of virus?
![brave](https://user-images.githubusercontent.com/71974856/128597880-b2947a20-6a83-4958-a7a7-3ec3a0a93024.png)

**Comment by rebron** [comment]
Did you download Brave from https://brave.com/?
Can you see find any instances of brave.exee.exe anywhere via Windows Explorer?

You shouldn't be seeing a brave.exee.exe. That's not us.

**Comment by RapahelS** [comment]
I downloaded brave from the official website (as far as I know).
I reinstalled brave and let you know if it happen again.

I could find  multiple instances of “Brave Browser“ and one instance of “BraveSoftware Update (32 Bit)”

**Comment by ageneric** [comment]
Still appears to be an issue, again with the 'brave.exee.exe' file not on my machine. Occurred with Brave open.

![image](https://github.com/brave/brave-browser/assets/55108448/48038b6a-02ce-434b-a13a-0a5ab92bd7be)

**Comment by RapahelS** [comment]
Since my first report of it, I had this issue multiple times on different devices.
This is definitely an issue that should be investigated because it seems very strange.

**Comment by 7eon8** [comment]
Still an issue, can't say I recall ever seeing RapahelS & ageneric's windows security alert popup, also highly doubt I'd have been fooled into allowing access to such a file name, but I just checked my data usage per app (in last 30 days) and brave.exee.exe (27.59GB) is right below the genuine brave.exe (198GB) which is a pretty odd ratio, wondering what it could have downloaded/uploaded. Anyone been able to remove/stop or even find the file? The data usage details shows brave.exee.exe was in the same directory as the real brave '\brave\bravesoftware\brave-browser-beta\application' at some point but it's not there now 😢
