### ISSUE TITLE
Remove BAP UI and bitFlyer feature flag

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15342]
With the 1.25 release, we will no longer need BAP-to-BAT transition logic and user interface elements. These should be removed. In addition, we can remove all BAP-related code and the bitFlyer feature flag.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.27.78 Chromium: 91.0.4472.114 (Official Build) beta （x86_64）
変更履歴	4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS	macOS バージョン10.15.7（ビルド19H1217）
```

<details>
<summary>Clean profile - PASSED</summary

Verified test plan from PR - https://github.com/brave/brave-core/pull/8953#issue-655253994 
Confirmed bitFlyer flag is not shown on brave://flags
Confirmed able to successfully link a bitFlyer KYC account
Confirmed able to tip successfully after linking bF wallet

brave://flags | bF wallet linked
----- | -----
<img width="1197" alt="cleanprofile-bF flag" src="https://user-images.githubusercontent.com/28145373/123327538-84d5f080-d508-11eb-8764-b93c7963449e.png"> | <img width="1200" alt="clean profile-tip" src="https://user-images.githubusercontent.com/28145373/123327543-86071d80-d508-11eb-9b2c-5eadc47a7d0a.png">

</details>


<details>
<summary>Upgrade profile 1 - PASSED</summary>

Using 1.26.x w/ Japan region, Rewards not enabled created a profile
Upgraded to 1.27.x
Confirmed after upgrade from 1.26.x I can enable rewards, connect BF wallet and tip
Confirmed brave://flags does not show the bitFlyer flag

</details>

<details>
<summary>Upgrade profile 2 - PASSED</summary>

Using 1.26.x w/ Japan region, created a profile
Enabled Rewards but did not connect bF wallet
Upgraded to 1.27.x
Confirmed after upgrade from 1.26.x I can connect BF wallet and tip
Confirmed brave://flags does not show the bitFlyer flag

</details>

<details>
<summary>Upgrade profile 3 - PASSED</summary>

Using 1.26.x w/ Japan region, created a profile
Enabled Rewards and connected bF wallet
Upgraded to 1.27.x
Confirmed after upgrade from 1.26.x I can tip using bF wallet
Confirmed brave://flags does not show the bitFlyer flag

</details>
