### ISSUE TITLE
Pull preliminary Japanese l10n for 1.24.x release.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#15341]
Get Japanese l10n from Transifex for strings modified for 1.24.x release.

**Comment by LaurenWags** [comment]
Generally with `1.24.75` BAT is not being shown correctly (is displaying BAP instead). This is occurring in pretty much all areas when region = Japan and language = Japanese. This is not happening with 1.25.x.

When these translations get uplifted to 1.24.x, QA needs to (at a minimum) confirm the following areas are correctly showing BAT when bF is enabled, language = Japanese, and region = Japan:
- brave://rewards
- rewards panel
- NTP widget
- one time and monthly tip banners (confirm BAT Points is removed also)
- monthly statement
- set up a monthly tip and view this tip on the rewards panel

cc @Miyayes @mkarolin
