### ISSUE TITLE
Cannot view IPFS companion via IPNS

### ISSUE THREAD

**Issue by jayschwa** [brave/brave-browser#15352]
## Description 

The IPFS companion dashboard (where you go after clicking "My Node" in the extension popup) can be viewed over HTTP but gives the following error via IPNS:
```
ipfs resolve -r /ipns/127.0.0.1:45005/ipfs/bafybeianwe4vy7sprht5sm3hshvxjeqhwcmvbzq73u55sdhqngmohkjgs4/: not a valid proquint string
```

## Steps to Reproduce

   1. Use IPFS local node (in Brave settings).
   2. Enable IPFS companion (in Brave settings).
   3. Open IPFS companion popup.
   4. Click "My Node" to open companion dashboard.
   5. Click "Open using IPFS" pill button in URL bar.
       - This seems to happen automatically if "Automatically redirect via DNSLink" is enabled in Brave Settings.

## Actual result:

```
ipfs resolve -r /ipns/127.0.0.1:45005/ipfs/bafybeianwe4vy7sprht5sm3hshvxjeqhwcmvbzq73u55sdhqngmohkjgs4/: not a valid proquint string
```

## Expected result:

No error.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

<details>
<summary>Brave | 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)</summary>

```
Brave | 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Linux
JavaScript | V8 9.0.257.17
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=AutoupgradeMixedContent,SafetyTip,DnsOverHttps,LegacyTLSEnforced,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,PrefetchPrivacyChanges --disable-features=AutofillEnableAccountWalletStorage,AutofillServerCommunication,SafeBrowsingEnhancedProtectionMessageInInterstitials,TextFragmentAnchor,BraveDomainBlock,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,IdleDetection,TabHoverCards,DirectSockets,SharingQRCodeGenerator,NetworkTimeServiceQuerying,LangClientHintHeader,NotificationTriggers,WebOTP,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/jayschwa/.config/BraveSoftware/Brave-Browser/Default
Variations | 7146a73c-3f4a17df
```
</details>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel?

Haven't tried other channel beyond stable.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

Not applicable.

**Comment by stephendonner** [comment]
Thanks for flagging this @jayschwa - see also https://github.com/brave/brave-browser/issues/15718 /cc @lidel

**Comment by jayschwa** [comment]
The error no longer occurs for me, so I am going to close this issue. #15718 is still applicable though.
