### ISSUE TITLE
High CPU Usage On Youtube

### ISSUE THREAD

**Issue by pckolog1** [brave/brave-browser#15354]
## Description 

After updating to 1.23.71 Chromium: 90.0.4430.72 (Resmi Derleme) (x86_64) Sürümü when I watch youtube videos CPU and GPU usage is very high even %150. And fans go crazy, temp reaches to 90C

## Steps to Reproduce

   1. Watch any youtube videos
   2. 
   3. 

## Actual result:

fans go crazy, temp reaches to 90C
## Expected result:
No fan noise

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.23.71 Chromium: 90.0.4430.72

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- No

## Miscellaneous Information:

MacBook Pro 2019 13" lastest OSx

**Comment by ryanbr** [comment]
1. Clear the cookies/cache for youtube, then relogin in
2. How many extensions do you have? (Try in private mode, with no extensions)
3. Also test with Hardware Acceleration enabled or disabled? (via `brave://settings/system`

**Comment by mpaunovic** [comment]
On brave://media-internals instead of MojoVideoDecoder it's Ffmpegvideodecoder. It it looks like hardware acceleration is broken again, surprise surprise. Probably Chromium 90 update is to blame. See here...

https://teddit.net/r/brave_browser/comments/msp5g7/hardware_acceleration_on_linux/

**Comment by pckolog1** [comment]
> Hey @pckolog1
> 
> 1. Clear the cookies/cache for youtube, then relogin in
> 2. How many extensions do you have? (Try in private mode, with no extensions)
> 3. Also test with Hardware Acceleration enabled or disabled? (via `brave://settings/system`
> 4. Also try lowering the youtube playback resolution (Does CPU usage change if using 720p or maybe 1080p)
> 5. Monitor `≡/More Tools/Task Manager` during the testing, to see how each tab uses CPU

None of them worked, and I want to mention this again: the problem begun after the last update, everything else is same and I never had this problem before this update.

**Comment by mpaunovic** [comment]
Downgraded to version 1.22.72 and everything works fine now. The problem is definitely with the latest update (1.23.71).

**Comment by pckolog1** [comment]
> Downgraded to version 1.22.72 and everything works fine now. The problem is definitely with the latest update (1.23.71).

Is that the only way? How can I downgrade on mac os?

**Comment by mpaunovic** [comment]
Unfortunately, it's the only way that I know of. I'm sorry I can't be of more help to you, I've been using Linux exclusively for the past two decades. But I'm sure you'll manage, there are a lot of good resources online.

Best of luck.

**Comment by mpaunovic** [comment]
Unfortunately, it's the only way that I know of. I'm sorry I can't be of more help to you, I've been using Linux exclusively for a long time now. But I'm sure you'll manage, hopefully there are a lot of good resources online.

Best of luck.

**Comment by pckolog1** [comment]
Still no solution...

**Comment by mpaunovic** [comment]
FWIW, hardware acceleration is working again in (vanilla) Chromium 90.0.4430.212 and all the Chromium based browsers, all of them but Brave.

**Comment by bbmak0** [comment]
I am experiencing the same issue too. Whenever I scroll on youtube, the cpu is running hot.

**Comment by rebron** [comment]
@pckolog1 @mpaunovic Still having issues with the latest 1.26.77, latest Chromium version is 91.0.4472.164

Those extensions shouldn't be

**Comment by mpaunovic** [comment]
> I am experiencing the same issue too. Whenever I **scroll** on youtube, the cpu is running hot. I only have Bitwarden and Adblocker extensions turn on.

Perhaps disabling "smooth scrolling" in brave://flags will help.

**Comment by mpaunovic** [comment]
For anyone still having this issue I was able to fix it by installing "ubuntu-restricted-extras".

`sudo apt update && sudo apt install ubuntu-restricted-extras`

Yay, hardware acceleration is working again in Brave!

**Comment by rebron** [comment]
@pckolog1 Our latest 1.27.111. Still running into this issue?

**Comment by Andycodesforyou** [comment]
Can this issue be closed now that we are in version 1.52.122?

Tried duplicating issue on Mac(2016) 15" Monterey and did not find excessive cpu usage (oscillated between 2-10% increase). 

@pckolog1

**Comment by kk-dev7** [comment]
alright so i found out that the faster i play a video on youtube (i use enhancer for youtube extension) the higher the cpu usage is

**Comment by Andycodesforyou** [comment]
By how much? comp stats?

**Comment by kk-dev7** [comment]
like from 10% up to 60%
