### ISSUE TITLE
YouTube no videos are displayed 

### ISSUE THREAD

**Issue by deon42** [brave/brave-browser#15369]
## Description 
As of today YouTube displays no information if shield is up. If you disable the shield it works fine.

## Steps to Reproduce
Open www.youtube.com

## Actual result:
See attached screenshot.

## Reproduces how often: 
every time, close browser and retry, same result

## Brave version (info found on brave://version)
Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? not confirmed
- Can you reproduce this issue with the dev channel? not confirmed
- Can you reproduce this issue with the nightly channel? not confirmed

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? not confirmed
- Is the issue reproducible on the latest version of Chrome? checked, but did not find any current report

**Comment by ryanbr** [comment]
No screenshot attached @deon42 

But no issues with youtube with any of the Brave builds, can you test in private window mode with no extensions enabled

**Comment by Tonev** [comment]
Click on the Shields icon when you open YouTube, and make sure "Scripts blocked" is **disabled**.

**Comment by deon42** [comment]
@Tonev thank you, that was the issue.

**Comment by deon42** [comment]
![Screenshot 2021-04-19 121202](https://user-images.githubusercontent.com/36193016/115256038-29197080-a12f-11eb-990d-815a62ec59e3.png)

@rebron not sure way it did not attach.

**Comment by deon42** [comment]
The scripting enable fixed the issue. Thank you very much to all that replied.
