### ISSUE TITLE
Fix handling of Rewards disabled state for various P3A questions

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#15374]
## Description 

Due to recent changes to Rewards, the "Rewards disabled" bucket for several of our P3A questions is never triggered correctly.

## Steps to Reproduce

   1. Clean profile
   2. Visit brave://rewards
   3. Wait 10-20 seconds and check `Brave.Rewards.AutoContributionsState.2` in brave://local-state
   4. Enable Rewards
   5. Wait 10-20 seconds and check `Brave.Rewards.AutoContributionsState.2` in brave://local-state
   6. Disable Rewards (i.e., turn off Ads and Auto-Contribute)
   7. Wait 10-20 seconds and check `Brave.Rewards.AutoContributionsState.2` in brave://local-state

## Actual result:

Step 3 - `Brave.Rewards.AutoContributionsState.2` not set at all
Step 5 - `Brave.Rewards.AutoContributionsState.2` set to `3`
Step 7 - `Brave.Rewards.AutoContributionsState.2` set to `2`

## Expected result:

Step 3 - `Brave.Rewards.AutoContributionsState.2` set to `1`
Step 5 - `Brave.Rewards.AutoContributionsState.2` set to `3`
Step 7 - `Brave.Rewards.AutoContributionsState.2` set to `1`

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Current `master`.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with build 

Brave | 1.25.34 Chromium: 90.0.4430.85 (Official Build) nightly (x86_64)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. Clean profile
2. Visited `brave://rewards`
3. Waited 10-20 seconds and checked `Brave.Rewards.AutoContributionsState.2` in `brave://local-state`
4. Enabled Rewards
5. Waited 10-20 seconds and checked `Brave.Rewards.AutoContributionsState.2` in `brave://local-state`
6. Disabled Rewards (i.e., turned off Ads and Auto-Contribute)
7. Waited 10-20 seconds and checked `Brave.Rewards.AutoContributionsState.2` in `brave://local-state`

step 3 | enabled Rewards | step 5 | disable Rewards | step 7 
-------|------------------|--------|-----------------|-------
<img width="898" alt="Screen Shot 2021-04-21 at 2 58 48 PM" src="https://user-images.githubusercontent.com/387249/115627002-28a9e280-a2b3-11eb-895f-1464eeabd576.png"> | <img width="1359" alt="Screen Shot 2021-04-21 at 2 59 29 PM" src="https://user-images.githubusercontent.com/387249/115627014-2cd60000-a2b3-11eb-9835-e56d121d07ad.png"> | <img width="898" alt="Screen Shot 2021-04-21 at 2 59 15 PM" src="https://user-images.githubusercontent.com/387249/115627007-2a73a600-a2b3-11eb-944c-3fb1ab24a1a5.png"> | <img width="1359" alt="Screen Shot 2021-04-21 at 2 59 37 PM" src="https://user-images.githubusercontent.com/387249/115627016-2e072d00-a2b3-11eb-8d59-e3b72c618361.png"> | <img width="1359" alt="Screen Shot 2021-04-21 at 2 59 46 PM" src="https://user-images.githubusercontent.com/387249/115627021-2f385a00-a2b3-11eb-99c3-e06b33af3d3e.png">
