### ISSUE TITLE
Rewards onboarding tour images are blank after verifying wallet

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15370]
## Description 

If "Start using Rewards" is clicked immediately after connecting to an external wallet provider without reloading the page, the images in the rewards onboarding tour are blank.

## Steps to Reproduce

   1. With a clean profile, go to `brave://rewards` and click "Verify Wallet"
   2. Login with the wallet provider
   3. Wait for redirection back to `brave://rewards` and authorization to complete successfully.
   4. Click "Start using Rewards"

## Actual result:

Images in the rewards onboarding tour are not displayed.

## Expected result:

Images in the rewards onboarding tour should be displayed.

**Comment by Miyayes** [comment]
Resolved as we no longer allow you to verify Rewards without enabling Rewards first.
