### ISSUE TITLE
Question-mark icon in connect-permissions dialog goes to top-level Brave Support website, instead of a specific article

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15376]
## Description 

Question-mark icon in connect-permissions dialog goes to top-level Brave Support website, instead of a specific article

## Steps to Reproduce

   1.  load `https://permission.site/`
   2.  click on `HID` or `USB`
   3.  in the resulting dialog, click on the (?) icon, bottom left

## Actual result:

Goes to `https://support.brave.com/hc/en-us`

<img width="1083" alt="Screen Shot 2021-04-19 at 4 32 13 PM" src="https://user-images.githubusercontent.com/387249/115316067-74cb1a80-a12d-11eb-91dc-f5d170df2aa2.png">
<img width="1083" alt="Screen Shot 2021-04-19 at 4 32 15 PM" src="https://user-images.githubusercontent.com/387249/115316070-77c60b00-a12d-11eb-87fb-c18e6e99aaaa.png">

## Expected result:

Not sure; should this go to `https://github.com/brave/brave-browser/wiki/Web-API-Permissions` which is the placeholder in the `Learn more` text for the dialog from https://github.com/brave/brave-browser/issues/14126 and https://github.com/brave/brave-browser/issues/14127?  Or somewhere else, within the Brave Support site?

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.24.66 Chromium: 90.0.4430.72 (Official Build) beta (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

/cc @karenkliu for suggestions/directions, and @goodov @pes10k for same/visibility

**Comment by goodov** [comment]
yep, we can guide users to `https://github.com/brave/brave-browser/wiki/Web-API-Permissions`, I think it's fine. Chrome also appends a permission type string to the webpage address. We can also do this to guide users to the exact anchor on our webpage (for example: `https://github.com/brave/brave-browser/wiki/Web-API-Permissions#webusb`).

**Comment by srirambv** [comment]
This is actually an issue on most of the help buttons on both Android and Desktop. We have never deep linked the help button to any of the specific articles if am not wrong.

**Comment by Ayushsunny** [comment]
> This is actually an issue on most of the help buttons on both Android and Desktop. We have never deep linked the help button to any of the specific articles if am not wrong.

Hello @srirambv do you think that I can work on this ?

**Comment by rebron** [comment]
@Ayushsunny If you'd like to work on this, that would be great. Link would be here: 
https://github.com/brave/brave-browser/wiki/Web-API-Permissions

**Comment by rebron** [comment]
cc: @Brave-Matt

**Comment by Ayushsunny** [comment]
> @Ayushsunny If you'd like to work on this, that would be great. Link would be here:
> https://github.com/brave/brave-browser/wiki/Web-API-Permissions

There are many links present at the same time and I couldn't understand what exact link should use for that button
@rebron ?

**Comment by stephendonner** [comment]
> > @Ayushsunny If you'd like to work on this, that would be great. Link would be here:
> > https://github.com/brave/brave-browser/wiki/Web-API-Permissions
> 
> There are many links present at the same time and I couldn't understand what exact link should use for that button
> @rebron ?

I believe just that top-level link for now; no need (yet) for the specific anchor tags for each capability, though we might/probably will do that later.

**Comment by Ayushsunny** [comment]
Hello @stephendonner I am not able to find permission.site page in `brave-core` ,
can you please help me with the code base where exactly I'm going to replace the link

**Comment by Ayushsunny** [comment]
@stephendonner , @rebron ping ?

**Comment by stephendonner** [comment]
Sorry @Ayushsunny I don't actually know, myself, offhand; I do know it'll be in https://github.com/brave/brave-core.  Perhaps @bsclifton or @goodov wouldn't mind helping you find it quicker than I?

**Comment by goodov** [comment]
@Ayushsunny hey! Try to find it yourself, it might be tricky, but it's a good skill to exercise. You need to find where in the code the browser creates this dialog, so you can search for files/classes that contain words like `permission`, `dialog`, `view`, `ui`.
The other option is try to find the current URL the browser opens when you click the question-mark icon and reverse search places in code where it's used.

**Comment by niharika412** [comment]
Hi @Ayushsunny ,Are you working on this? I would like to take it up.

**Comment by Ayushsunny** [comment]
> Hi @Ayushsunny ,Are you working on this? I would like to take it up.

Hey @niharika412, yeah you can pick this as I'm not working on this issue.

**Comment by nilanshu96** [comment]
@stephendonner @rebron I've made the necessary changes

**Comment by stephendonner** [comment]
> @stephendonner @rebron I've made the necessary changes

thanks!  I've flagged @goodov for the review.

**Comment by nilanshu96** [comment]
Thank You @stephendonner. Brave is an amazing browser and I'd be happy to contribute more in the future.

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan here with build 

Brave | 1.27.62 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. loaded `https://permission.site/`
3. clicked on `HID`
4. in the resulting dialog, clicked on the `(?)` icon, bottom left
5. confirmed link went to `https://github.com/brave/brave-browser/wiki/Web-API-Permissions`

Also tested `USB` - couldn't get `Bluetooth` and `Serial` to work, on `permission.site`

example | example
---------|---------
<img width="1082" alt="Screen Shot 2021-06-14 at 12 28 21 PM" src="https://user-images.githubusercontent.com/387249/121948899-b2eb5180-cd0c-11eb-953f-5ba1aaef37e5.png"> | <img width="1082" alt="Screen Shot 2021-06-14 at 12 28 28 PM" src="https://user-images.githubusercontent.com/387249/121948900-b383e800-cd0c-11eb-85aa-094c0e7af03a.png">
