### ISSUE TITLE
Use the current context instead of the browser context for backup result API

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#15377]
- Tor window should use Tor
- Proxy should use a proxy https://developer.chrome.com/docs/extensions/reference/proxy/

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.2.3 x64` using the following build:

```
Brave | 1.23.73 Chromium: 90.0.4430.85 (Official Build) (x86_64)
--- | ---
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | macOS Version 11.2.3 (Build 20D91)
```

* verification notes can be found via https://github.com/brave/internal/issues/766#issuecomment-824977136.
