### ISSUE TITLE
[Android] Support Unstoppable Domains via Ethereum

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#15373]
Support resolving domains with IPFS records via Ethereum network.

**Comment by yrliou** [comment]
Fixed by https://github.com/brave/brave-browser/issues/15373

**Comment by stephendonner** [comment]
Verified `PASSED` on Android 9.0 using a Google Pixel, arm64, on Brave `1.25.51, Chromium 90.0.4430.93`

Steps:

1. Went to `Settings` > `Privacy & Security` > `Unstoppable Domains` and chose `Ethereum` under `Resolve Method`
2. Loaded `brave.crypto`, and confirmed the page loaded as `https://bafybeid6rntsjiydicxj5cnmnqonbvwv35lrjgd6dngskptra3oa2otxxm.ipfs.dweb.link/` without issue

example | example
---------|---------
![Screenshot_20210505-143619](https://user-images.githubusercontent.com/387249/117213040-f23e8e00-adaf-11eb-9837-9fa815f89f73.png) | ![Screenshot_20210505-143647](https://user-images.githubusercontent.com/387249/117213042-f2d72480-adaf-11eb-9e35-0bfe291f3f86.png)
