### ISSUE TITLE
IPFS interstitial page content and button gets clipped when the Developer Tools panel is open

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15375]
## Description 

IPFS interstitial page content gets clipped when the Developer Tools panel is open

## Steps to Reproduce

   1.  new profile
   2.  open the Developer Tools
   3.  load `ipfs://en.wikipedia-on-ipfs.org`
   4.  look at the text and button below the orange `Use a local node` button

## Actual result:

<img width="1792" alt="Screen Shot 2021-04-19 at 4 05 32 PM" src="https://user-images.githubusercontent.com/387249/115314196-93c7ad80-a129-11eb-966f-331d218ce4ef.png">

## Expected result:

The page should scroll instead of having content cut off.

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.24.66 Chromium: 90.0.4430.72 (Official Build) beta (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

/cc:ing @karenkliu in case she has suggestions

**Comment by karenkliu** [comment]
The page should scroll if viewport height is smaller than the content height.

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (x86_64)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

Confirmed that resizing and constraining the window size with/without the Developer Tools panel, doesn't result in the splitting/clipping of the content, as before.

<img width="765" alt="Screen Shot 2021-05-12 at 11 45 11 AM" src="https://user-images.githubusercontent.com/387249/118032601-b4e08000-b31c-11eb-8d2f-f5b421886324.png">
