### ISSUE TITLE
Remove HTTP User-Agent farbling

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#15372]
Brave's initial implementation of farbling the User-Agent string sent with HTTP requests has proven to be difficult to maintain (subtle changes upstream have lead to regressions that are difficult to debug). With C90's effective freezing of the Mac OS X version string (to `10.5.7`, for compatibility reasons), our implementation will provide ever smaller privacy benefits over time.

**Comment by stephendonner** [comment]
@pilgrim-brave would you please drop a test plan we can follow over in https://github.com/brave/brave-core/pull/8562?  Thanks! /cc @pes10k since I see you were also working on abating this with Cloudflare.

Also looping in @brave/legacy_qa

**Comment by kjozwiak** [comment]
Talked to @pes10k earlier via the uplift thread. Labeling this as `QA/No` as the checks will be done via https://github.com/brave/brave-browser/issues/15039, https://github.com/brave/brave-browser/issues/15322 & https://github.com/brave/brave-browser/issues/14740. @pes10k let me know if that sounds right or if there's anything else that we need to check for this one.
