### ISSUE TITLE
Please Add VPN functionality

### ISSUE THREAD

**Issue by justshivam** [brave/brave-browser#15385]
## Description 
Many sites are blocked in my region. So, I tried to access those sites using tor but the site was blocked on tor for security reasons.

## Steps to Reproduce

   1. Open TOR Window.
   2. Try to visit 1377x.to

## Actual result:
![Screenshot 2021-04-20 181049](https://user-images.githubusercontent.com/59390818/115397702-02793980-a204-11eb-914a-8f76c33de7e2.png)

## Expected result:
The should open normally.

## Reproduces how often: 
Everytime.

## Brave version (brave://version info)

Brave | 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Windows 10 OS Version 2009 (Build 19042.928)

**Comment by tathastu871** [comment]
Just like opera vpn. 
If vpn is not poosible to add in brave. Add functionality to use temporary free proxies to visit the site

**Comment by bsclifton** [comment]
@justshivam @tathastu871 we have a VPN implementation in the works - you can follow https://github.com/brave/brave-browser/issues/15804 for the latest info 😄
