### ISSUE TITLE
Wrong text for default browser dialog in Polish 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#15387]
follow up to https://github.com/brave/brave-browser/issues/14469

### Scenario One - Not now (button)

1. Set Chrome/FF as the default browser
2. Clean profile 
3. launch Brave in Polish locale (PL)
4. uncheck `Ustaw Brave jako domyślną przeglądarkę`
5. click the `OK` button
6. create a new tab 
7. shut down and relaunch Brave 
8. shut down and relaunch Brave (3rd)

## Actual result:

Text in the dialog is all wrong
![image](https://user-images.githubusercontent.com/34715963/115406229-4281f180-a1ef-11eb-8401-52ee22d0c48d.png)

## Expected result:
Just like in English, should be:
```
Ustaw Brave jako domyślną przeglądarkę

Przeglądaj sieć szybciej - do sześciu razy szybciej na największych portalach informacyjnych.
```

![image](https://user-images.githubusercontent.com/34715963/115406408-6d6c4580-a1ef-11eb-9382-c20a3c67c259.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.24.66 Chromium: 90.0.4430.72 (Official Build) beta (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Ubuntu 18.04 LTS

cc @mkarolin @rebron

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.24.82 Chromium: 90.0.4430.93 (Oficjalna wersja) (x86_64)
-- | --
Wersja | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
System operacyjny | macOS Wersja 10.15.7 (kompilacja 19H1030)
```

Verified STR from description.

<img width="1034" alt="Zrzut ekranu 2021-05-3 o 10 28 56" src="https://user-images.githubusercontent.com/28145373/116889404-823ad700-abfa-11eb-8062-32874d9371cb.png">
