### ISSUE TITLE
Brave Nightly fails to resolve DNS for some websites

### ISSUE THREAD

**Issue by RockyBukake** [brave/brave-browser#15391]
## Description 

Browser won't resolve DNS for certain websites

## Steps to Reproduce

   1. Input URL (i.e bin.privacytools.io )

## Actual result:

![Screenshot from 2021-04-20 16-43-19](https://user-images.githubusercontent.com/35773324/115425517-98f32e00-a1f7-11eb-8f85-828ade6d9d88.png)

## Expected result:
It displaying the website

## Reproduces how often: 

Everytime

## Brave version (brave://version info)

1.25.25 Chromium: 90.0.4430.72 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- No, works fine
- Can you reproduce this issue with the beta channel? 
- No, works fine
- Can you reproduce this issue with the nightly channel? 
- Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- Didn't test but probably not

**Comment by RockyBukake** [comment]
I have updated the Browser to version( 1.25.28 Chromium: 90.0.4430.72 (Official Build) nightly (64-bit) ), the issue still persists

**Comment by ryanbr** [comment]
- Do you have a VPN installed?  (Disable if you can)
- Try in private window mode, no extensions enabled
- What does `ping bin.privacytools.io` show?

**Comment by RockyBukake** [comment]
> * Do you have a VPN installed?  (Disable if you can)
> * Try in private window mode, no extensions enabled
> * What does `ping bin.privacytools.io` show? (via the command line)

- No
- Done that, made sure all extensions were disabled, exact same result
- Works has expected since all other versions of Brave (Beta and Default release) already resolve it without problem
![Screenshot from 2021-04-21 12-51-52](https://user-images.githubusercontent.com/35773324/115549337-723d0200-a2a0-11eb-8091-fb50f5dd29bb.png)

**Comment by RockyBukake** [comment]
Another website that also fails to resolve sometimes is cock.li, after refreshing the page 2-3 times it works, this behavior does not happen with Brave Beta or Default release, does Brave Nightly mess around with DNS requests ? 
![Screenshot from 2021-04-22 22-26-34](https://user-images.githubusercontent.com/35773324/115787293-def7ef80-a3b9-11eb-9330-feef02137609.png)

**Comment by RockyBukake** [comment]
Okay, i think I've found the issue, after disabling secure DNS it no no-longer has any problem resolving DNS, bin.privacytools.io works without a problem now. 

![Screenshot from 2021-04-22 22-42-28](https://user-images.githubusercontent.com/35773324/115788849-1e274000-a3bc-11eb-82a9-c946291d6655.png)

I'm gonna close this issue in 24 hours if no one else replies to it.

**Comment by ryanbr** [comment]
As a last step, does the other DNS providers work? I briefly tried cloudflare's DNS without any issues.

**Comment by RockyBukake** [comment]
Negative, tested with all providers, clearing DNS cache in between the tests, all failed to resolve bin.privacytools.io, cleared it once more and disabled "Secure DNS" and it worked like expected, so I can confirm that on my machine having "Secure DNS" enabled was the problem and with that will close this issue.
