### ISSUE TITLE
Brave freezing Ubuntu 20.04 the black screen

### ISSUE THREAD

**Issue by Doctor-blob** [brave/brave-browser#15393]
## Description 

When I browse with Brave it crashes my entire system and what I mean by that is that it freezes my screen en then my screen goes black and I can't do anything not even go to the command Line. I think it's caused by me watching a youtube video but the interval when it happens is seemingly at random.
I tried the nightly channel, the beta channel and the normal channel but every time it's the same.
I disabled hardware accelleration and tried --no-xshm but neither worked.

I have a Lenovo Thinkpad 330s with a ryzen 5 2500u with vega graphics.

Edit: I switched to chromium and the issue still persists so I think it's a problem with chromium. And It doesnt't crash reliably because It sometimes crashes on startup, and sometimes 3 hours into browsing. 

## Steps to Reproduce
   1. Install Brave or chromium on Ubuntu 20.04
   2. Browse normally (often freezes while watching a Youtube video)

## Expected result:
The screen will freeze then go black.

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Brave | 1.25.25 Chromium: 90.0.4430.72 (Official Build) nightly (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Linux
JavaScript | V8 9.0.257.17
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Command Line | /opt/brave.com/brave-nightly/brave --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,WebUIDarkMode,AutoupgradeMixedContent,SafetyTip,LegacyTLSEnforced,DnsOverHttps --disable-features=AutofillEnableAccountWalletStorage,InterestCohortAPIOriginTrial,AutofillServerCommunication,InterestCohortFeaturePolicy,IdleDetection,NetworkTimeServiceQuerying,LangClientHintHeader,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,FlocIdComputedEventLogging,SignedExchangeSubresourcePrefetch,NotificationTriggers,WebOTP,EnableProfilePickerOnStartup,DirectSockets,SharingQRCodeGenerator,TabHoverCards,TextFragmentAnchor,SafeBrowsingEnhancedProtection,FederatedLearningOfCohorts,FlocIdSortingLshBasedComputation,SafeBrowsingEnhancedProtectionMessageInInterstitials --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave-nightly/brave
Profile Path | /home/jetze/.config/BraveSoftware/Brave-Browser-Nightly/Default
Variations | 7146a73c-3f4a17df

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? Already disabled
- Is the issue reproducible on the latest version of Chrome? No but I didn't test long

**Comment by ryanbr** [comment]
Hey @Doctor-blob   does disabling Hardware Accelleration via `brave://settings/system` help?

**Comment by Doctor-blob** [comment]
> Hey @Doctor-blob does disabling Hardware Accelleration via `brave://settings/system` help?

Sadly No I tried it and It worked for a day and the the problem came back

**Comment by bsclifton** [comment]
@Doctor-blob there are a few flags you might try toggling:
- brave://flags/#enable-skia-renderer (try enabling)
- brave://flags/#enable-vulkan (try disabling)

**Comment by rebron** [comment]
@Doctor-blob Can you update to the latest 1.28.105 and let us know if you're still running into this issue?

**Comment by Doctor-blob** [comment]
Sorry I can't comment on this anymore because I switched to windows 11 a while ago.
