### ISSUE TITLE
Add setting for tab groups

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#15394]
## Description 
Slack: https://bravesoftware.slack.com/archives/DCLU7012P/p1618935977006400

In Settings->Appearance please add a setting to enable/disable Tab Groups

**Title**
Enable Tab Groups

Default = On

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.73 x64 build
- Verified new setting for tab groups is available under Settings -> Appearance
- Verified enable/disable setting triggers restart prompt
- Verified disabling setting doesn't show tab groups or allow tabs to be grouped via context menu
- Verified enabling setting allows grouping of tabs via context menu

https://user-images.githubusercontent.com/17010094/115747372-1bf9bd00-a38d-11eb-95e7-d47e47567c25.mp4

-------------
Logged issue for setting available in Tablet #15450

**Comment by kjozwiak** [comment]
We'll QA the above via https://github.com/brave/brave-browser/issues/15453 for `1.23.x - Release #3`. However, we'll use this one for the release notes 👍
