### ISSUE TITLE
crash when searching via Tor while `Fallback` has been enabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#15406]
## Description 

When searching via Tor with `Fallback` enabled, the browser will crash.

* Uploaded crash report ID: `274b0000-ff38-2d06-0000-000000000000`
* Uploaded crash report ID :`264b0000-ff38-2d06-0000-000000000000`

## Steps to Reproduce

* STR can be found via https://github.com/brave/internal/issues/766#issuecomment-823878826

## Actual result:

Brave crashes when searching via Tor with `Fallback` enabled.

## Expected result:

Brave shouldn't crash.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.25.31 Chromium: 90.0.4430.72 (Official Build) nightly (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Windows 10 OS Version 2009 (Build 19042.928)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @bbondy @SergeyZhukovsky

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | Ubuntu 18.04 LTS

Verified in https://github.com/brave/internal/issues/766#issuecomment-824979063
