### ISSUE TITLE
Browser relaunches twice when tab group setting is enabled/disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15402]
## Description 
Browser relaunches twice when tab group setting is enabled/disabled

## Steps to reproduce 

   1. Install 1.25.31 x64 nightly build
   2. Change Enable tab groups settings
   3. Triggers relaunch
   4. Select relaunch causes browser to close and open twice 

## Actual result 

https://user-images.githubusercontent.com/17010094/115499098-b90e0600-a266-11eb-8f24-84c815d043e6.mp4

## Expected result
Only one restart

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  NA
- Can you reproduce this issue with the current Play Store Beta version?  NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.25.31 x64 nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik @SergeyZhukovsky

**Comment by samartnik** [comment]
This is expected as feature is not applied after 1 restart. Same happens in Chrome when enabling/disabling feature from `chrome://flags`

**Comment by anthonypkeane** [comment]
Fixed by upstream
