### ISSUE TITLE
enable ephemeral storage keepalive by default

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#15415]

**Comment by pes10k** [comment]
For QA test plan, I've added some tests to https://dev-pages.brave.software/storage/keep-alive.html

If there are any questions, just let me know!

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.25.51 Chromium: 90.0.4430.93 (Official Build) beta (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:

1. new profile
2. load `brave://flags` and enable both `Enable Ephemeral Storage` and `Ephemeral Storage Keep Alive`
3. restart / relaunch Brave
4. load `https://dev-pages.brave.software/storage/keep-alive.html`
5. click on the `Start test` button beneath `Should "Keep Alive" Test`
6. wait for the test to finish and return you to the original page
7. ensure the results for this frame, local frame, and remote frame read `set`
8. click on the `Reset tests` button at the bottom
9. click on the `Start test` button beneath the `Should Not "Keep Alive" Test`
10. wait for the test to finish and return you to the original page
11. ensure the results for this frame and local frame read `set`, and remote frame reads `empty`

repeat 1-11 using `https://dev-pages.bravesoftware.com/storage/keep-alive.html`


Should keep-alive, `brave.software` | Should _NOT_ keep-alive, `brave.software` | Should keep-alive, `bravesoftware.com `| Should _NOT_ keep-alive, `bravesoftware.com`
---------|----------|---------|----------
<img width="1134" alt="Screen Shot 2021-05-05 at 12 52 03 PM" src="https://user-images.githubusercontent.com/387249/117201345-66be0080-ada1-11eb-875e-ac9d7564b919.png"> | <img width="1134" alt="Screen Shot 2021-05-05 at 12 51 38 PM" src="https://user-images.githubusercontent.com/387249/117201343-66256a00-ada1-11eb-952c-05ef1c5ec4e3.png">  | <img width="1134" alt="Screen Shot 2021-05-05 at 12 54 26 PM" src="https://user-images.githubusercontent.com/387249/117201445-81907500-ada1-11eb-90a2-0413e84748aa.png"> | <img width="1134" alt="Screen Shot 2021-05-05 at 12 55 08 PM" src="https://user-images.githubusercontent.com/387249/117201448-82290b80-ada1-11eb-9912-150b1432a9e4.png">

**Comment by srirambv** [comment]
Removing `OS/Android` label as this is not working on Android. Follow-up issue #15646 is logged which is Android specific
