### ISSUE TITLE
Add Fullscreen and Next buttons to  Picture-in-Picture on Desktop

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15416]
## Description 

Would be great and usefull to add fullscreen button to this window, my pattern is to move this window to a separate monitor and make it fullscreen and click Next sometimes

![image](https://user-images.githubusercontent.com/2965009/115592094-7f2b1700-a2db-11eb-87c2-45746e0231a7.png)

**Comment by spylogsster** [comment]
https://github.com/brave/brave-browser/issues/24836

**Comment by sangwoo108** [comment]
Follow-up issue : https://github.com/brave/brave-browser/issues/35721
