### ISSUE TITLE
Rewards error logged repeatedly on private new tab page

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15417]
## Description 

In a private browser context, the new tab page will repeatedly log the following error:

```
"Unchecked runtime.lastError: Rewards service is not initialized", source: chrome://newtab/ (0)
```

## Steps to Reproduce

   1. Open a new private window.
   2. Open developer tools and select the console tab.
   3. Wait 30 seconds.

## Actual result:

Every 30 seconds a rewards error is logged.

## Expected result:

An error should not be logged.

**Comment by stephendonner** [comment]
Verified `PASSED` using `nightly` build 

Brave | 1.25.46 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3 (Build 20E232)

<img width="1756" alt="Screen Shot 2021-04-27 at 3 43 28 PM" src="https://user-images.githubusercontent.com/387249/116321734-78832080-a76f-11eb-9970-6ff1ba3a0f31.png">


Confirmed the Rewards error from https://github.com/brave/brave-browser/issues/15417#issue-864116782 is no longer  spamming the console's Error tab.
