### ISSUE TITLE
rewards panel and tip banner messaging mismatch in certain cases

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15424]
## Description 

In the anon wallet state (only Rewards BAT present, no KYC wallet connected), in certain cases the rewards panel and tip banners have conflicting/mismatched messaging.

## Steps to Reproduce

Scenario 1 - US region
   1. Clean profile, staging environment
   2. Enable Rewards, claim UGP grant
   3. Navigate to nike.com (unverified publisher), ddg (connected publisher), and laurenwags.github.io (Uphold KYC publisher)
   4. Open panel and tip banner for each
   5. In all of these cases the panel and banner messaging match (tips not allowed to Nike, are allowed to the other two)
   6. Now visit batcommunity.org (bF KYC publisher)
   7. Open panel and tip banner
   8. Panel indicates that this publisher cannot be tipped, but tip banner doesn't display this messaging
   9. In this case, the panel is wrong and should not be displaying any messaging. The tip banner is correct. In fact, if you tip this publisher the tip gets deducted from balance and is reflected in UI.

Unverified Publisher | Connected Publisher | Uphold Publisher | bF Publisher
----- | ----- | ----- | -----
<img width="1199" alt="US-unverified-pub" src="https://user-images.githubusercontent.com/28145373/115616166-dc17d480-a2bd-11eb-88b0-d5c87238dafe.png"> | <img width="1193" alt="US-connected-pub" src="https://user-images.githubusercontent.com/28145373/115616173-dde19800-a2bd-11eb-961b-0bebbec67a7c.png"> | <img width="1191" alt="US-Uphold-pub" src="https://user-images.githubusercontent.com/28145373/115616178-dfab5b80-a2bd-11eb-852c-325fd6875f91.png"> | <img width="1191" alt="US-bF-pub" src="https://user-images.githubusercontent.com/28145373/115616183-e0dc8880-a2bd-11eb-8f3a-807bddf8063d.png">

Scenario 2 - JP region
   1. Clean profile, staging environment
   2. Enable Rewards, claim UGP grant
   3. Navigate to nike.com (unverified publisher), ddg (connected publisher), and batcommunity.org (bF KYC publisher)
   4. Open panel and tip banner for each
   5. In all of these cases the panel and banner messaging match (tips not allowed to Nike, are allowed to the other two)
   6. Now visit laurenwags.github.io (Uphold KYC publisher)
   7. Open panel and tip banner
   8. Panel indicates that this publisher cannot be tipped, but tip banner doesn't display this messaging
   9. In this case, the panel is wrong and should not be displaying any messaging. The tip banner is correct. In fact, if you tip this publisher the tip gets deducted from balance and is reflected in UI.

Unverified Publisher | Connected Publisher | Uphold Publisher | bF Publisher
----- | ----- | ----- | -----
<img width="1192" alt="JP-unverified-pub" src="https://user-images.githubusercontent.com/28145373/115616214-ee920e00-a2bd-11eb-8726-63d604ab5d89.png"> | <img width="1194" alt="JP-connected-pub" src="https://user-images.githubusercontent.com/28145373/115616216-f0f46800-a2bd-11eb-955b-de5625d3c911.png"> | <img width="1193" alt="JP-Uphold-pub" src="https://user-images.githubusercontent.com/28145373/115616220-f2259500-a2bd-11eb-842f-9f8fa1a6c76d.png"> | <img width="1191" alt="JP-bF-pub" src="https://user-images.githubusercontent.com/28145373/115616223-f356c200-a2bd-11eb-88d2-a809b566619b.png">

## Actual result:

Panel and tip banner messaging mismatch (panel is incorrectly showing the messaging, tip banner is correctly not showing messaging)

## Expected result:

No mismatch, both panel and tip banner should be consistent with messaging

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.24.70 Chromium: 90.0.4430.72 (Official Build) beta (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 10.15.7 (Build 19H524)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.23.x n/a
- Can you reproduce this issue with the beta channel? 1.24.x yes
- Can you reproduce this issue with the nightly channel? 1.25.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing @emerick

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 1.24.x

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.24.83 Chromium: 90.0.4430.93 (Official Build) (x86_64)
Revision	4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS	macOS Version 10.15.7 (Build 19H1030)
```

Verified STR from description and additional scenarios listed below.

<details>
<summary>Scenarios</summary>

**Scenario 1 - US region w/ anon wallet**

Confirmed correct messaging in anon wallet case for the 4 publisher types below.

Unverified Publisher | Connected Publisher | Uphold Publisher | bF Publisher
----- | ----- | ----- | -----
<img width="1340" alt="Screen Shot 2021-05-07 at 3 25 41 PM" src="https://user-images.githubusercontent.com/28145373/117499099-bc80dd00-af48-11eb-9541-cb4524fe4545.png"> | <img width="1336" alt="Screen Shot 2021-05-07 at 3 25 55 PM" src="https://user-images.githubusercontent.com/28145373/117499101-bdb20a00-af48-11eb-8bd7-1d6a6a0ba9a2.png"> | <img width="1341" alt="Screen Shot 2021-05-07 at 3 26 11 PM" src="https://user-images.githubusercontent.com/28145373/117499104-be4aa080-af48-11eb-8c1f-63240b83d0a9.png"> | <img width="1344" alt="Screen Shot 2021-05-07 at 3 26 27 PM" src="https://user-images.githubusercontent.com/28145373/117499106-bf7bcd80-af48-11eb-9e32-20fa099fb305.png">

Confirmed tips to connected, Uphold KYC, and bF KYC were allowed, tip to unverified were sent to Pending

Pending List | Tips | Wallet panel
----- | ----- | -----
<img width="957" alt="Screen Shot 2021-05-07 at 3 26 52 PM" src="https://user-images.githubusercontent.com/28145373/117499126-c571ae80-af48-11eb-9762-18c98fe63de6.png"> | <img width="648" alt="Screen Shot 2021-05-07 at 3 26 59 PM" src="https://user-images.githubusercontent.com/28145373/117499130-c6a2db80-af48-11eb-8950-7ff4643dfc10.png"> | <img width="404" alt="Screen Shot 2021-05-07 at 3 27 06 PM" src="https://user-images.githubusercontent.com/28145373/117499133-c7d40880-af48-11eb-83cc-23b57036c89b.png">

</details>

----------------------
