### ISSUE TITLE
Allow users to use p2p-keys to publish content

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15422]
## Description 

- Add a new block to the IPFS Settings to manage p2p-keys:
![image](https://user-images.githubusercontent.com/2965009/117131679-6a09ba00-adaa-11eb-869d-294877081cb0.png)

- the self item would be the default key shown as disabled which you can’t remove
- In the context menus add a submenu to select existing key or a new one, if new one selected the user will be navigated to the settings page keys management block
- if no keys selected the content will be published to IPFS only, otherwise to IPNS 
![image](https://user-images.githubusercontent.com/2965009/117622685-92fbc780-b17b-11eb-9e65-c209a1691c61.png)

**Comment by spylogsster** [comment]
related issues https://github.com/brave/brave-browser/issues/14774 and https://github.com/brave/brave-browser/issues/14770

**Comment by rebron** [comment]
@karenkliu Are you ok with this location in the menu? 
https://user-images.githubusercontent.com/2965009/117155058-1fe20200-adc5-11eb-897f-8556a49616f6.png

Possibly move options to More Tools section.

More Tools >
---
 Share local file using IPFS >
 Share local folder using IPFS >
---
Clear Browsing Data...
Task Manager

**Comment by karenkliu** [comment]
@rebron  Have it as a top-line item in the menu makes it easier to find, so I think this is fine. However it doesn't make sense that it gets its own section. I would think of it as an additional browser feature and put it underneath Sync without a divider line.

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan in https://github.com/brave/brave-core/pull/8706 with build 

Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

Partially verified (majority of publishing files/folders) via https://github.com/brave/brave-browser/issues/16020#issuecomment-849881172, which covers the following:
* Check publishing for all IPFS import local menu items:  folder or file
* If publishing was successful the IPNS link should be copied

### Publishing new content over old one for same key should be successful

<details>

Steps:

1. new profile, launch Brave
2. load `ipns://brantly.eth`
3. click `Use a local node`
4. load `wikipedia.org`
5. `File | Save Page As...` and click `Save`
6. load `brave://settings/ipfs/keys`
7. click `Add`
8. type `newkey` and click `Generate`
9. click on the "hamburger" menu and choose `IPFS -> Share Local File Using IPFS`
10. choose `newkey` from the flyout
11. browse to `Wikipedia.html` and click `Open`
12. wait
13. paste the link copied to the clipboard into a new tab, and load it
14. wait
15. confirm you can load the page over IPNS
16. click on the "hamburger" menu and choose `IPFS -> Share Local File Using IPFS`
17. choose `newkey` from the flyout
18. browse to `Wikipedia.html` and click `Open`
19. wait
20. paste the link copied to the clipboard into a new tab, and load it
21. wait
22. confirm you can load the page over IPNS
23. load `brave://ipfs-internals/`
24. click on `My Node`
25. click on `Files`
26. click on `brave-imports`
27. click on the date-stamped directory
28. ensure there is only one copy of the same file, and that is has the same filesize

example | example | example | example | example
---------|---------|----------|----------|---------
<img width="1138" alt="Screen Shot 2021-05-27 at 3 53 48 PM" src="https://user-images.githubusercontent.com/387249/119906828-d2f4d580-bf03-11eb-8398-e46a8e21b383.png"> | <img width="1417" alt="Screen Shot 2021-05-27 at 3 54 03 PM" src="https://user-images.githubusercontent.com/387249/119906830-d38d6c00-bf03-11eb-8732-ddf192b10e74.png"> | <img width="1138" alt="Screen Shot 2021-05-27 at 3 56 08 PM" src="https://user-images.githubusercontent.com/387249/119906948-19e2cb00-bf04-11eb-892a-cd7733f152e4.png"> | <img width="1128" alt="Screen Shot 2021-05-27 at 3 25 31 PM" src="https://user-images.githubusercontent.com/387249/119906698-8dd0a380-bf03-11eb-9e23-417be3e4fa96.png"> | <img width="1128" alt="Screen Shot 2021-05-27 at 3 28 27 PM" src="https://user-images.githubusercontent.com/387249/119906700-8e693a00-bf03-11eb-832f-37bc81cb13fa.png">

</details>

### If the IPFS node is stopped or keys are not available, the to-be-published items should not be added

<details>

Steps:

1. new profile, launch Brave
2. load `ipns://brantly.eth`
3. click `Use a local node`
4. load `wikipedia.org`
5. `File | Save Page As...` and click `Save`
6. load `brave://settings/ipfs/keys`
7. click `Add`
8. type `newkey` and click `Generate`
9. load `brave://ipfs-internals/`
10. click on the "hamburger" menu and choose `IPFS -> Share Local File Using IPFS`
11. choose `newkey` from the flyout
12. browse to `Wikipedia.html` and click `Open`
13. click the `Stop` button on `brave://ipfs-internals/`
14. wait a couple minutes
15. confirm `Wikipedia.html` wasn't added, you didn't get a system-level notification, and there's no link for it in your clipboard
16. click `Start`
17. click `My Node`
18. click on `Files`
19. click on `brave-imports`
20. click on the date-stamped directory
21. confirm you see `Wikipedia.html` 
22. paste the link from your clipboard, and confirm you see the Wikipedia page

example | example | example | example | example | example
---------|----------|----------|--------|----------|---------
<img width="859" alt="Screen Shot 2021-05-27 at 4 01 04 PM" src="https://user-images.githubusercontent.com/387249/119907705-b8236080-bf05-11eb-9b70-73e5db23a531.png"> | <img width="1205" alt="Screen Shot 2021-05-27 at 4 01 12 PM" src="https://user-images.githubusercontent.com/387249/119907706-b8bbf700-bf05-11eb-94ae-5e06acd5ca7d.png"> | <img width="859" alt="Screen Shot 2021-05-27 at 4 01 32 PM" src="https://user-images.githubusercontent.com/387249/119907707-b8bbf700-bf05-11eb-8c55-0cfc1a5f49c2.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 4 07 23 PM" src="https://user-images.githubusercontent.com/387249/119907709-b9548d80-bf05-11eb-8921-19fa3beba2d1.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 4 07 18 PM" src="https://user-images.githubusercontent.com/387249/119907708-b9548d80-bf05-11eb-97bb-aaeb1052b5bc.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 4 10 09 PM" src="https://user-images.githubusercontent.com/387249/119907858-13ede980-bf06-11eb-87c3-fd6fb0845f13.png">

</details>
