### ISSUE TITLE
Basemark Web 3.0 shows problems running multiple tests . tested on chrome and edge same issue

### ISSUE THREAD

**Issue by tlong25** [brave/brave-browser#15421]
## Description 

Basemark Web 3.0 shows problems running multiple tests on chrome and edge.

## Steps to Reproduce

   1. updated all for edge and chrome and windows
   2. ran test again
   3. same issues 

## Actual result:

Basemark Web 3.0 shows problems running multiple tests

score of 167.77
## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing. @tlong25 We need this issue to be better formed. I'm not sure what you're expecting the fix is. Possibly contact the website as it looks all browsers are effected.
