### ISSUE TITLE
remove AC from Monthly Statement (JP region)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15427]
## Description 

Since AC is not available in JP region, should remove it from Monthly Statement in two places:
1. the summary at the top
2. the table at the bottom

## Steps to Reproduce

   1. Clean profile 1.24.x, staging env, JP region
   2. Enable Rewards, enable bF
   3. Claim UGP grant
   4. Do a tip
   5. Open Monthly Statement

## Actual result:

AC shown

<img width="946" alt="Screen Shot 2021-04-21 at 4 16 21 PM" src="https://user-images.githubusercontent.com/28145373/115618028-21d59c80-a2c0-11eb-9081-03631de02be3.png">

## Expected result:

No AC shown on statement

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.24.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.23.x n/a
- Can you reproduce this issue with the beta channel? 1.24.x yes
- Can you reproduce this issue with the nightly channel? 1.25.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing @emerick

**Comment by Miyayes** [comment]
For simplicity, we should just comment out the Auto-Contribute line in the Monthly Statements while A-C is not available in the JP region. cc: @zenparsing

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.24.83 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/117441490-b7666280-af35-11eb-819a-5df0eb70d667.png)
