### ISSUE TITLE
"Manage Your Wallet" modal messaging in JP region

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15420]
## Description 

Regardless of bF flag status, bF is mentioned on the "Manage Your Wallet" modal. Should only be mentioned when flag is enabled (currently not default).

## Steps to Reproduce

pre-req: have OS set to Japan
   1. Clean profile, staging env
   2. Enable Rewards
   3. Open Manage Your Wallet modal

## Actual result:

<img width="694" alt="Screen Shot 2021-04-21 at 14 55 50" src="https://user-images.githubusercontent.com/28145373/115608920-dff32900-a2b4-11eb-84f5-c3cff009a49f.png">

## Expected result:
If flag= disabled (currently default), no mention of bF on this page.

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.24.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.23.x mentions Uphold which is also wrong
- Can you reproduce this issue with the beta channel? 1.24.x yes
- Can you reproduce this issue with the nightly channel? 1.25.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing @emerick

**Comment by Miyayes** [comment]
I consider this a `wontfix`, since flag disabled state will not be the standard, and is only a temporary state.

**Comment by LaurenWags** [comment]
Per discussion with @zenparsing QA needs to check that the "If you'd like to..." text is removed from this screen.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.24.83 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2004 (Build 19041.928)

```
