### ISSUE TITLE
Tip button should not appear on Github profile page

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15432]
## Description 

~Tip button in github's profile page doesn't work~
Tip button should not appear on Github profile page

## Steps to Reproduce

   1. Load github's user profile page

## Actual result:

![image](https://user-images.githubusercontent.com/6786187/115636615-47f34f00-a349-11eb-8936-a877ee2516a4.png)

## Expected result:
No "Tip" button is injected on the profile page

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by emerick** [comment]
That tip button shouldn't appear there at all. It seems like the rule for inserting the tip button on the "stars" tab is too broad.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.27.108 Chromium: 92.0.4515.107 (Official Build) (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 10.15.7 (Build 19H1217)
```

and dev component version `1.0.48`.

Reproduced the issue with prod component version `1.0.42`.
Confirmed when using `1.0.48` the Tip button is not shown on a GitHub profile page in the following cases:
* Rewards is not enabled (has never been enabled)
* Rewards is enabled and GitHub content-level tipping is enabled
* Rewards is enabled and GitHub content-level tipping is disabled

`1.0.42` | `1.0.48`
----- | -----
<img width="1199" alt="15432-prod" src="https://user-images.githubusercontent.com/28145373/126994523-96a2e3e1-61dc-494b-825c-88f0797ea804.png"> | <img width="1196" alt="15432-dev" src="https://user-images.githubusercontent.com/28145373/126994530-2aadf9fb-68a9-4781-a127-4a3c0cfec5d1.png">
