### ISSUE TITLE
Request is incorrectly treated as third-party due to CNAME uncloaking

### ISSUE THREAD

**Issue by 3dyd** [brave/brave-browser#15443]
## Description 
All first-party requests on https://es.listerine.com/ are getting blocked leaving this site non-functional.

## Steps to Reproduce
Brave with default settings. Just open https://es.listerine.com/

## Actual result:
Broken site:
![ss](https://user-images.githubusercontent.com/31128519/115698302-24420000-a36d-11eb-9dc1-a24103ca0143.png)

## Expected result:
Site functions normally.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
```
Brave | 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Windows 10 OS Version 2004 (Build 19041.928)
```

## Version/Channel Information:
- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `Yes`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `No`

## Miscellaneous Information:

Uncloaked CNAME for `es.listerine.com` is `nva-as-cluster10-1.lb.onelink-translations.com`.

Per brave/brave-core#8262, for any sub-request to `es.listerine.com`, the method  `AdBlockBaseService::ShouldStartRequest` is now given `url=nva-as-cluster10-1.lb.onelink-translations.com` and `tab_host=es.listerine.com`. So it treats such requests as third-party, although initial URL, if uncloaked, points to the same location.

Combo finishes EasyPrivacy with [the following line](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt#L1691):
```
||onelink-translations.com^$third-party
```
Although this line is a bit questionable, it would not make a problem if sub-requests to the initial URL host name were not treated as third-party due to CNAME uncloaking.

**Comment by 3dyd** [comment]
Well, I have read conversations uBlockOrigin/uBlock-issues#909 and uBlockOrigin/uBlock-issues#1062, and now I am not so sure whether this can be considered as a bug or a feature. Nevertheless, the mentioned site (and I suppose all other sites powered by onelink-translations.com) does not work now.

**Comment by ryanbr** [comment]
Removed the filter, seems to be only used as a cname for other domains

https://github.com/easylist/easylist/commit/9bd98fa9849b52ab2b0f8551fe47cb5796e4772f

Give it 24-48hrs @3dyd

**Comment by 3dyd** [comment]
It works now. Thank you.

**Comment by ryanbr** [comment]
Cheers @3dyd  Thanks for the confirmation
