### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by BrendanEich** [brave/brave-browser#15449]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.25.33  Chromium: 90.0.4430.85
Operating System: Mac OS X 11.2.3

URL (if applicable) where crash occurred:

I loaded my brave search onboarding link (private so will provide via another channel) into nightly, saw presenting credentials, went Back to the onboarding link, crashed.

Can you reproduce this crash?

No.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. See above
2. 
****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ca090000-3573-3606-0000-000000000000

**Comment by rebron** [comment]
@iefremov When you get a chance, can you take a look?

**Comment by keur** [comment]
@rebron I think this is a dup of https://github.com/brave/brave-browser/issues/15445. Just waiting to hear back from Brendan.

**Comment by iefremov** [comment]
yes, this a dupe
