### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by BrendanEich** [brave/brave-browser#15457]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.25.33  Chromium: 90.0.4430.85
Operating System: Mac OS X 11.2.3

URL (if applicable) where crash occurred:
Probable dup of #15445.

Can you reproduce this crash?
No.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Tab switching, which reloaded unloaded-since-restart pages, not sure what triggered crash.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/2f0c0000-3573-3606-0000-000000000000

**Comment by iefremov** [comment]
dupe https://github.com/brave/brave-browser/issues/15445
