### ISSUE TITLE
[Follow up to #15394] Add setting for tab groups

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15453]
## Description 
Slack: https://bravesoftware.slack.com/archives/DCLU7012P/p1618935977006400

In Settings->Appearance please add a setting to enable/disable Tab Groups

**Title**
Enable Tab Groups

Default = On

### Test Plan
- Verify enable/disable tab group triggers restart
- Verify enabling tab group shows context menu option to group tabs
- Verify disabling tab group doesn't show context menu option to group tabs
- Verify disabling tab group disables tab grouping in tab tray

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.74 x64 build

- Verified enable/disable tab group triggers restart
- Verified enabling tab group shows context menu option to group tabs
- Verified disabling tab group doesn't show context menu option to group tabs
- Verified disabling tab group disables tab grouping in tab tray
- Verified tab grouping works with normal / private tabs

https://user-images.githubusercontent.com/17010094/115833350-da5c2700-a40b-11eb-8277-619cb4fd1aa7.mp4

--------
Verification passed on Samsung Tab A with Android 10 running 1.23.74 x64 build
- Verified Tablet doesn't have a tab group settings

https://user-images.githubusercontent.com/17010094/115833951-8e5db200-a40c-11eb-8aa1-e2768460d6ab.MP4

**Comment by iyx** [comment]
> Verify disabling tab group doesn't show context menu option to group tabs
In my case, only re-enabling (relaunch) and re-disabling (relaunch) "Tab Groups" made context menu option go away.
