### ISSUE TITLE
Change an option text in the permissions lifetime dialog

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#15459]
Change lifetime option text to "until I close this **site**" in permissions lifetime dialog.
![image](https://user-images.githubusercontent.com/5928869/115842036-a0107b00-a447-11eb-88af-f33a0bf31e56.png)

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` as this would require uplift to 1.24.x

**Comment by goodov** [comment]
The order for translations was already placed, so the uplift didn't make it to `1.24.x`. Changed the milestone to `1.25.x`.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.25.46 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3 (Build 20E232)



The dialog now reads `Give permission until I close this site`

<img width="1714" alt="Screen Shot 2021-04-27 at 3 47 22 PM" src="https://user-images.githubusercontent.com/387249/116321993-00692a80-a770-11eb-9db2-c31c2dc7fbe6.png">

**Comment by stephendonner** [comment]
Verified `PASSED` on Android 9 on a Google Pixel, arm64, using Brave `1.25.51, Chromium 90.0.4430.93`

Steps:

1. enabled the `Permission Lifetime` feature flag via `brave://flags`
2. restarted
3. loaded `permission.site`
4. tapped on `Camera`
5. read the invoked dialog
6. confirmed it reads `Give permission until I close this site`

example | example
---------|---------
![Screenshot_20210505-150319](https://user-images.githubusercontent.com/387249/117215764-8e1dc900-adb3-11eb-8bb3-6c17a26fd82a.png) | ![Screenshot_20210505-150343](https://user-images.githubusercontent.com/387249/117215766-8eb65f80-adb3-11eb-97e3-239a9c533441.png)
