### ISSUE TITLE
"Estimated pending rewards" temporarily reset to zero while the payments server endpoint returns non HTTP_OK status response codes

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#15460]
## Description 

"Estimated pending rewards" temporarily reset to zero while the payments server endpoint returns non HTTP_OK status response codes

## Steps to Reproduce

   1. Join Rewards
   2. View some ads
   3. Redeem unblinded payment tokens (by fast-forwarding the system clock)
   4. Quit the browser
   5. Rewrite status response code for `GET /v1/confirmation/payment/{payment_id}` to return a non 200 OK response.
   6. Launch the browser
   7. Visit brave://rewards (also check NTP Rewards widget)

## Actual result:

"Estimated rewards pending" at brave://rewards and the NTP Rewards widget are reset to zero. "Estimated rewards pending" will correct itself after the server responds with a `200 OK`.

## Expected result:
"Estimated rewards pending" should use the cached value from `ads_service/confirmations.json`.

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by JanHadari** [comment]
Jan12345

**Comment by JanHadari** [comment]
Jan123456

**Comment by JanHadari** [comment]
Děkuju

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2004 (Build 19041.928)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/8630
