### ISSUE TITLE
Popups being generated on http://sh.st/4XsNw

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#15461]
## Description 
Clicking on the `http://sh.st/4XsNw` will generate popups

## Steps to Reproduce

   1.  Click on `http://sh.st/4XsNw`
   2. Click on any of the empty space on the site
   3. popups are generated

## Actual result:

Top screen (Man Screen), Bottom Screen (popup ad window)
![shorte](https://user-images.githubusercontent.com/1659004/115873878-96166880-a497-11eb-9c97-9c54320cfed6.png)

## Expected result:
Expect to block this, like uBO. Prevent the adscript and popup from working.

## Reproduces how often: 

Easily

## Brave version (brave://version info)
`Version 1.25.33 Chromium: 90.0.4430.85 (Official Build) nightly (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Miscellaneous Information:
Related uBO filters: which aren't applied. Aggressive mode has no affect.
```
sh.st##+js(acis, Math, zfgloaded)
@@||sh.st^$ghide
```
Popups are generated from these scripts (these domains will change)
`http://go.onclasrv.com/apu.php?zoneid=1543391`  does an instant redirect to `https://cobalten.com/apu.php?zoneid=1543391` which `sh.st##+js(acis, Math, zfgloaded)` should counter. In an iframe.

**Comment by antonok-edm** [comment]
Appears to be fixed
