### ISSUE TITLE
Brave Ads anti-targeting - ads are not blocked with eTLD+1 site in resource file

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#15467]
Follow up to **Implement Brave Ads anti-targeting** #14224

The ads are not blocked when the sites is resource file are declared eTLD+1.
Example `nytimes.com`:
```
{"locale": "us", "version": 1, "timestamp": "2021-04-21 18:02:28", "sites": {"c7e7a381-4c74-4dd9-9b6d-4edf9330454b": ["nytimes.com", "wsj.com"]}}
```

IMPORTANT: sites declared as full URL are blocked: `https://www.nytimes.com/`

## Steps to Reproduce

1. Follow **Notification ad - eTLD+1 anti-targeting site - prevent ad** from https://github.com/brave/internal/issues/767

## Actual result:

Ad is shown

## Expected result:
Ad is not shown
```
[exclusion_rule_util.h(26)] creativeSetId c7e7a381-4c74-4dd9-9b6d-4edf9330454b excluded as user has previously visited an anti-targeting site
```

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.24.70 Chromium: 90.0.4430.72 (Official Build) beta (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @moritzhaller @tmancey @jsecretan

**Comment by moritzhaller** [comment]
@btlechowski very good spot, but I think it's ok to leave as is we just need to make sure to add the scheme to the lists. I will make a note on the spreadsheet. wdty? cc @iambrianfung

**Comment by btlechowski** [comment]
@moritzhaller Sounds good.
