### ISSUE TITLE
[Webcompat] Qatar Airways

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1546]
## Description 
https://www.qatarairways.com/en-us/homepage.html does not render correctly on brave

## Steps to Reproduce
   1. Navigate to https://www.qatarairways.com/en-us/homepage.html

## Actual result:
<img width="1274" alt="screen shot 2018-10-11 at 4 24 48 pm" src="https://user-images.githubusercontent.com/1903815/46839328-3e4d0180-cd72-11e8-8572-5bc24ed10731.png">

## Expected result:
Should be rendered correctly.

## Reproduces how often: 
100%

## Brave version (chrome://version info)
`0.56.2 Chromium: 70.0.3538.35 (Official Build) dev (64-bit)`

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by bbondy** [comment]
@jumde could you try with 0.55.14?

**Comment by jumde** [comment]
Fixed with 0.55.14
