### ISSUE TITLE
[Follow up to #15453] Dynamically detect disable option for Tab Groups

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#15463]
## Description 
In order to avoid future possible breakages of `Enable Tab Groups` preference, we should dynamically detect disable option.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan:
Just double check that `Enable Tab Groups` and `Enable "Night Mode" (Experimental)` options work.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.75 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/15463#issuecomment-825688989
- Verified on default install tab group is enabled but doesn't work until the browser is restarted once
- Verified toggle tab groups/night mode prompts for restart
- Verified when restart is selected from the prompt the browser restarts twice for the settings to work
- Verified disabling tab groups and restarting twice doesn't show tab grid layout for tabs overview
- Verified settings work on both normal and private tabs
- Verified enable/disable setting and selecting later doesn't change the behaviour only affects after the browser is manually restarted
--------
Verification passed on Samsung Tab A with Android 10 running 1.23.75 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/15463#issuecomment-825688989
- Verified no setting for tabs group under Settings-> Appearance
- Verified toggle night mode prompts restart
- Verified selecting later doesn't set tabs to dark view until restart
- Verified restarting after enabling toggle sets webview to dark mode
