### ISSUE TITLE
Enabling chromium's reader mode in about:flags does not work

### ISSUE THREAD

**Issue by dapherino** [brave/brave-browser#15464]
## Description 

Enabling (#enable-reader-mode) flag does not work. The reason I want to do this is because speedreader is not finished yet, and does not work on most sites I want to use it on. 

## Steps to Reproduce

   1. Enable #enable-reader-mode in about:flags
   2. Go on a news site article (example: nytimes.com)

## Actual result:

Reader mode does not show up, unlike in chromium (also with the flag manually enabled). As shown in the screenshot. 

![Screenshot 2021-04-23 101540](https://user-images.githubusercontent.com/55215353/115884440-e8667380-a41c-11eb-8df0-3c58fefd8afa.jpg)

## Expected result:
Chromium's reader mode should show up.

## Reproduces how often: 

Every time on an article where chromium would show it.

## Brave version (info found on brave://version)

Brave | 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | Windows 10 OS Version 2009 (Build 19042.928)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? haven't checked
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by daphnei-mee** [comment]
It also does not show up in the hamburger menu, unlike chromium where it does.

**Comment by MetotoSakamoto** [comment]
No icon at all here with flatpak version too

**Comment by dentistformyeye** [comment]
In MacOS, it's in the top menu: View > Enter Reader Mode.
![image](https://user-images.githubusercontent.com/51429646/116172273-6dc97c80-a6d8-11eb-80c9-4f6e7c2d9318.png)

It only seems to work on some pages, though. (It used to be possible to enable reader mode on all pages, but reader mode now seems to work only on pages that the browser thinks are articles.)

**Comment by illtellyoulater** [comment]
Can confirm. 
No signs of "reader-mode" after enabling the flag and relaunching the browser...

**Comment by rebron** [comment]
Closing. Chromium's reader mode is available as subset of Speedreader and available via: brave://flags/#brave-speedreader to turn by everybody or enabled and rolled out to some users by default via the SpeedreaderReleaseStudy. https://griffin.brave.com/ You can see if you're in that study by looking at brave://versions

See https://github.com/brave/brave-browser/issues/11994 as what we're working on next.
