### ISSUE TITLE
[Brave Browser Bug] Some Videos can be played on Chrome, but NOT on Brave 

### ISSUE THREAD

**Issue by daming-lu** [brave/brave-browser#15479]
I filed the [original issue](https://github.com/brave-intl/publishers/issues/3191) in the wrong repo. Moving it here:

This issue might not belong to this repo. Feel free to move it to the browser repo. Basically, I noticed that for famous video websites like Bilibili (NASDAQ: BILI), the videos on it can be played on Chrome but not on Brave. Others like YouTube, are good.

https://www.bilibili.com/video/BV1ti4y1K7uw

Really hope this bug can be fixed so that I don't need to switch back to Chrome 😄

Here is how it works on Chrome (no problem)

![111211](https://user-images.githubusercontent.com/5635322/115934797-bbc75180-a446-11eb-94fe-14c95b0e6954.png)

But on Brave, it keeps loading forever.

**Comment by ryanbr** [comment]
Hey @daming-lu I just tested this, no issues with playback here, and skipped through video. What actually happens?  

https://gif.fanboy.co.nz/gif/billi.gif

**Comment by daming-lu** [comment]
Hey, @ryanbr ! Thanks for the prompt reply. Yes, I opened it on Brave incognito and it worked fine. Seems like an extension had blocked the playback. The weird thing is that Brave and Chrome have the same settings and extensions. But Chrome works fine but not Brave. I guess it might be an issue from some extension, which was only tested on Chrome.
