### ISSUE TITLE
Add theming functionality in onboarding process

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#1547]
## Description 
We need to add the ability to preview themes without leaving the onboarding experience. The below GIF is an example of the intended functionality of this screen. Atleast initially, we will only swap between Light and Dark themes. If a user doesn't commit to dark before proceeding, it reverts to light theme. Clicking confirm auto advances to next panel. 

![unnamed](https://user-images.githubusercontent.com/29072694/46841046-a9023b00-cd7a-11e8-9f59-dc3c626530c0.gif)

**Comment by rebron** [comment]
Closing. Wonfix since we're picking up default theme based on OS choice.
