### ISSUE TITLE
promo slide needs image for panel view

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15475]
## Description 

The promo slide needs to show the image from wide view, will have to scroll on the panel view to see image fully. Per @codybanxs there should also be a scroll bar shown to indicate this to the user.

See discussion in https://bravesoftware.slack.com/archives/G01EN0GPH5Z/p1619205181053300 and images in thread also

## Steps to Reproduce

   1. View JP region rewards onboarding tour from panel
   2. View final slide

## Actual result:

no image

## Expected result:
image from wide view [figma doc](https://www.figma.com/file/9Pn7htrOeZsbOJ2NcxtxvR/bitFlyer?node-id=407%3A0) should be shown

note - it should look like the (not implemented) Android view of this slide + a scroll bar

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.24.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.23.x n/a
- Can you reproduce this issue with the beta channel? 1.24.x yes
- Can you reproduce this issue with the nightly channel? 1.25.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing @emerick @codybanxs

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.24.77`

**Comment by zenparsing** [comment]
Closing per consensus to not show the promo image on the rewards panel; the "learn more" link is sufficient.
