### ISSUE TITLE
Brave doesn't show Ads on Arch Linux

### ISSUE THREAD

**Issue by rudyon** [brave/brave-browser#15472]
## Description 

Brave browser shows ads on Windows but does not on Linux

## Steps to Reproduce

- Install the brave-bin package from the AUR.
- Enable Brave Rewards.
## Actual result:

Brave Rewards never sends Ad notifications.
## Expected result:
Brave Rewards sends Ad notifications.
## Reproduces how often: 

Unkonwn.
## Brave version (brave://version info)

1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No 
- Is the issue reproducible on the latest version of Chrome? No

**Comment by bsclifton** [comment]
possibly related https://github.com/brave/brave-browser/issues/13866
