### ISSUE TITLE
verify wallet modal doesn't display nicely in Japanese

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15478]
## Description 

Some text is hidden behind a button on the "Verify Wallet" modal when language = Japanese. I'm not sure how much though.

## Steps to Reproduce

   1. Have language = Japanese, region = Japan
   2. Trigger verify wallet modal

## Actual result:

Some text is hidden behind a button:

<img width="614" alt="スクリーンショット 2021-04-23 16 34 40" src="https://user-images.githubusercontent.com/28145373/115927037-d2bf7100-a451-11eb-82a2-410118cf472e.png">

## Expected result:
All text should be visible

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.24.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.23.x n/a
- Can you reproduce this issue with the beta channel? 1.24.x yes
- Can you reproduce this issue with the nightly channel? 1.25.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing @emerick

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Windows 10 x64  - 1.24.81`

**Comment by Miyayes** [comment]
Superseded by new verify wallet modal.
