### ISSUE TITLE
Log 'onClick' event on Auto-Contribute toggle into Rewards log or event log to check for human interaction

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15476]
## Description 

Currently we log when A-C is enabled or disabled in the brave://rewards-internals event logs. **However,** it doesn't tell us whether this was triggered by software, or if it was triggered by human touch. In order to determine whether it was human, we can log whether the actual A-C toggle in brave://rewards was clicked or pressed by a human (onClick event).

## Solution

1. Listen for onClick event on the actual A-C toggle in brave://rewards
2. Log this to event log (and Rewards log?)

**Comment by zenparsing** [comment]
Per @LaurenWags , we should probably also log the location of the button that was clicked.

**Comment by Miyayes** [comment]
Closing, especially with https://github.com/brave/brave-browser/issues/38678#issuecomment-2181116412
