### ISSUE TITLE
Crash Report - open brave crash.

### ISSUE THREAD

**Issue by lucianomunoz** [brave/brave-browser#15474]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.23.73  Chromium: 90.0.4430.85
Operating System: Windows NT 10.0.19042

Can you reproduce this crash?
Yes, constantly, cant seem to use brave anymore, as of this morning.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
Open brave
press G and instantly crashes, if i start typing with other letters and then press G it doesnt crash right away, 
go to any website youtube, twitter, gmail i get an instant crash;

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c4130000-3573-3606-0000-000000000000

**Comment by iefremov** [comment]
Not actionable without any additional info
