### ISSUE TITLE
add default search engine functionality to onboarding process

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#1548]
A new part of the onboarding process is the ability to set a default search engine. This requires a little conditional prep for what we present in what regions. This is likely already taken care of in Chromium code for settings but we need to link it up to this dropdown. 

![image](https://user-images.githubusercontent.com/29072694/46841268-bff55d00-cd7b-11e8-9d55-0aee2e8660ff.png)

**Comment by rebron** [comment]
cc: @bsclifton and @mkarolin

**Comment by lukemulks** [comment]
+1 from Reddit. https://www.reddit.com/r/BATProject/comments/9pdu7u/duckduckgo_as_the_default_search_engine/
Personal +1 (or +1000).

**Comment by srirambv** [comment]
Verification passed on 


Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

* Verified able to choose any of the available SE from the dropdown list
* Verified selected SE is set as default in settings
![image](https://user-images.githubusercontent.com/17010094/62138902-777d4080-b2b6-11e9-9276-25a6c146ab12.png)

@rossmoody @rebron @imptrx could we eliminate the `Set Default` button and just use the dropdrown to trigger the set default button action? This reduces one more click that you have to go through in the onboarding screen. Whichever option is selected should automatically set it in settings

**Comment by kjozwiak** [comment]
> @rossmoody @rebron @imptrx could we eliminate the Set Default button and just use the dropdrown to trigger the set default button action? This reduces one more click that you have to go through in the onboarding screen. Whichever option is selected should automatically set it in settings

I would suggest the same thing with the "Theme" section under `0.70.18 Chromium: 76.0.3809.72 (Official Build) nightly`. Changing between the theming option automatically applies the change without the need to click on `Confirm`. Example:

<img width="700" alt="Screen Shot 2019-07-30 at 12 00 36 PM" src="https://user-images.githubusercontent.com/2602313/62145631-caa8c080-b2c1-11e9-9d61-3f61cba1ff2c.png">

@rossmoody @rebron @imptrx thoughts? Should we open a new issue so we can discuss possibly removing the `Set default` & `Confirm` buttons?

**Comment by rebron** [comment]
We want to keep those buttons since set default and confirm also act as next buttons. Otherwise, selecting just from the drop down and then moving users to the next screen would feel too abrupt an action, especially so on theme choice for example. @rossmoody to confirm though.

**Comment by rossmoody** [comment]
That’s the idea but @petemill brought up a similar concern and under the hood I believe the setting is set when the drop down is changed not on button click so though I don’t think we can assume advancing on first selection is right maybe the “next” button to could serve as the confirm

**Comment by srirambv** [comment]
> We want to keep those buttons since set default and confirm also act as next buttons.  

Seems redundant as there is the next button as well
![image](https://user-images.githubusercontent.com/17010094/62147161-f7aaa280-b2c4-11e9-9dba-89ca0f2b2ae9.png)

**Comment by kjozwiak** [comment]
yup, as @srirambv & @rossmoody mentioned, switching the setting via the drop down boxes changes the setting and doesn't move the user to the next screen unless they click on `Next ->` or one of the `bubbles` that indicate where you are in the onboarding process.

Both `Set default` for search engines & `Confirm` for themes are basically second `Next` buttons.

**Comment by srirambv** [comment]
Also confirm theme seems to open up setting page. Since its a drop-down should probably have the same behaviour as SE and not really switch to the settings page. That can probably be discussed on a different issue

**Comment by kjozwiak** [comment]
> Also confirm theme seems to open up setting page. Since its a drop-down should probably have the same behaviour as SE and not really switch to the settings page. That can probably be discussed on a different issue

That's being addressed in `0.70.x` via https://github.com/brave/brave-browser/issues/4992. Already merged. Double checked with `0.70.18 CR: 76.0.3809.72` and it works as expected 👍

**Comment by rossmoody** [comment]
Well, there was thought for this that I think should be considered which is the user can’t assume that their search engine changed without a confirm button. So I’d vote for that to stay. “Next“ is to advance the screen in cases where a user doesn’t want to make a decision. In the case of themes the user can see their theme change in real time so that’s the confirmation. I personally still think giving the user a place to feel like the decision is confirmed is strong but in the case of themes it could be adjusted. Future ui had the next button removed as well so I think we should be mindful of changes.
