### ISSUE TITLE
Brave not removing tracking parameters from URLs

### ISSUE THREAD

**Issue by Dryader** [brave/brave-browser#15486]
## Description 

Brave not removing tracking parameters from URLs

## Steps to Reproduce

   1. Go to this URL as an example [https://www.reddit.com/r/starcitizen/comments/mvg1ep/yet_another_video_loading_the_roc_into_the_nomad/?utm_medium=android_app&utm_source=share](https://www.reddit.com/r/starcitizen/comments/mvg1ep/yet_another_video_loading_the_roc_into_the_nomad/?utm_medium=android_app&utm_source=share)
   2. Look at the URL bar
   3. 
## Actual result:

URL in search bar is [https://www.reddit.com/r/starcitizen/comments/mvg1ep/yet_another_video_loading_the_roc_into_the_nomad/?utm_medium=android_app&utm_source=share](https://www.reddit.com/r/starcitizen/comments/mvg1ep/yet_another_video_loading_the_roc_into_the_nomad/?utm_medium=android_app&utm_source=share)

## Expected result:
URL should show in search bar [https://www.reddit.com/r/starcitizen/comments/mvg1ep/yet_another_video_loading_the_roc_into_the_nomad/](https://www.reddit.com/r/starcitizen/comments/mvg1ep/yet_another_video_loading_the_roc_into_the_nomad/)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | Windows 10 OS Version 2009 (Build 19042.928)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
 
This extension seems to fix the issue. [https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk](https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk)

**Comment by Dryader** [comment]
Not sure entirely if Brave is actually supposed to strip these parameters from urls, let me know if I messed up.

**Comment by ryanbr** [comment]
Related: https://github.com/brave/adblock-rust/issues/166

Still a work in progress, and dependent on other privacy fixes (like URL rewriting).
cc: @antonok-edm 

Closing this report
