### ISSUE TITLE
Users can link their wallet without opting into Rewards

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#15481]
## Description 
Opting out of Rewards by clicking the X doesn't appear to disable all Rewards functionality.

Perhaps the easiest fix is to remove the X.

## Steps to Reproduce

   1. Start Brave with a new profile.
   2. Skip the onboarding.
   3. Click on the BAT icon.
   4. Click the X to decline the Rewards opt-in.
   5. Close the Rewards popup.
   6. Click the BAT icon again.

## Actual result:
![Screenshot from 2021-04-23 18-39-17](https://user-images.githubusercontent.com/167821/115943164-39995600-a463-11eb-84d4-71465004328a.png)

The links are all clickable.

## Expected result:
![Screenshot from 2021-04-23 18-38-05](https://user-images.githubusercontent.com/167821/115943158-300fee00-a463-11eb-9378-cc16af713eca.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
```
Brave | 1.25.16 Chromium: 90.0.4430.70 (Official Build) nightly (64-bit)
Revision | 3954de7175366f3b7edca576f140dfa273e6b5ae-refs/branch-heads/4430@{#1210}
OS | Linux
```

**Comment by Miyayes** [comment]
Resolved. Rewards panel components no longer accessible before opting into Brave Rewards.
