### ISSUE TITLE
Building from scratch

### ISSUE THREAD

**Issue by ArquenElanor** [brave/brave-browser#15487]
Description
I am a new Brave user but I've experienced SIGSEGV tab crashes and I'm trying to get more information from the core dump. I decided to try and compile a debug version.
I followed the build instructions and initially I ran into issue #13631, edited the package.json, ran into a variant of issue #11147, edited the .gconfig file to include brave core, although I don't understand the setup enough how this is created incorrectly.
I have the latest versions of nodejs & npm if that's relevant.

## Steps to Reproduce
{Fresh suse tumbleweed install}
   1.  npm run init  -> { edit package.json }

fatal: repository 'undefined' does not exist

   2.  #issue 11147 (namely Error: Invalid .gclient file)

Error: Invalid .gclient file. Solution is incomplete: {'managed': False, 'name': 'src/brave'}
null
null
null
null

   3.  edit .glient file to include brave core

  {
    "managed": False,
    "name": "src/brave",
    "url": "https://github.com/brave/brave-core.git"
  }

## Actual result:
Still issues with the rust compilation, but  work in progress

## Expected result:
A working debug version of brave

## Reproduces how often: 
Always

## Brave version (brave://version info)
Current

**Comment by bsclifton** [comment]
You'll definitely want to be using node.js LTS version with NPM 6 😄

**Comment by ArquenElanor** [comment]
Thanks for the replies guys. I am somewhat confused now though. @lele0108 Do you mean npm version 6 ?. If I install that one of the dependencies is nodejs 6 ..
@bsclifton The current LTS version of nodejs seems to be 14, if I understand correctly (which has npm 7).
I'm obviously missing something here, do I need to install npm & node separately ?.

I appreciate your time.

**Comment by lele0108** [comment]
@ArquenElanor Yeah, npm version 6. This version works for me: `npm install -g npm@6.14.13`

Node 14 LTS uses npm 6. node 16 lts will be the first version to bundle with npm 7. See: https://github.com/nodejs/node/discussions/37689

I believe the issue is caused by a breaking (undocumented?) change / bugfix in npm 7 that causes the `config` property in `package.json` to be parsed and stored differently in the env variables. Hence causing the undefined (and other issues that rely on fields in the `package.json`. Something to do with the `-/_` change.

@bsclifton Perhaps this is something that can be patched?

**Comment by ArquenElanor** [comment]
@lele0108 Thanks bro, works a treat now. Not sure if you want to do anything about the docs or patch the npm 7 issue but I'm happy now. I'll close this.

**Comment by MaazBinMusa** [comment]
Using 18.04 ubuntu
Node 16.13
npm 8.1.0

> gclient sync --reset --nohooks --revision src/brave@7b0ee787889b6e4f7e0af3cf051ac6ad773438d8 --revision src@refs/tags/96.0.4664.35 --force --with_tags --with_branch_heads --upstream
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Error: Invalid .gclient file. Solution is incomplete: {'managed': False, 'name': 'src/brave'}

I only changed the package.json file brave-core to brave_core
