### ISSUE TITLE
Several errors when launching Brave on Ubuntu 20.04, fresh installation

### ISSUE THREAD

**Issue by Dylan-86** [brave/brave-browser#15499]
## Description 
From terminal, launching Brave:

```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
libGL error: pci id for fd 24: 8086:9a49, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
libGL error: pci id for fd 24: 8086:9a49, driver (null)
libGL error: unable to load driver: iris_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: iris
[13063:13063:0426/175257.325597:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[13153:13153:0426/175257.347094:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
[13035:13050:0426/175304.617000:ERROR:udev_watcher.cc(97)] Failed to begin udev enumeration.
```

Brave actually opens, but it takes approx 10 seconds to start (at least a cold start, if I pkill brave and launch it again, I get the same set of errors but Brave starts in 2-3 seconds).

## Steps to Reproduce
This happens every time.

   1. Open Terminal
   2. type "brave"
   3. That's it

## Actual result:

See above

## Expected result:
No errors, fasted startup

## Reproduces how often: 

100% of the times on my machine.

## Brave version (info found on brave://version)

Brave	1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
Revision	5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS	Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Yes, and with the previous too
- 
- Can you reproduce this issue with the beta channel?
- Haven't tried
- Can you reproduce this issue with the dev channel?
- Haven't tried
- Can you reproduce this issue with the nightly channel?
- Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- no
-
- Does the issue resolve itself when disabling Brave Rewards?
- no
- 
- Is the issue reproducible on the latest version of Chrome? 

When launching google-chrome from console I get this

```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[14670:14670:0426/180258.705037:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.



```
## Miscellaneous Information:

N/A

**Comment by rebron** [comment]
cc: @mihaiplesa

**Comment by wknapik** [comment]
Hey @Dylan-86,

The first issue with canberra-gtk-module would likely be resolved by running
```
sudo apt install --reinstall libcanberra-gtk-module libcanberra-gtk3-module
```
Before we dig deeper into the GL issue - you're not running this in a VM, or a container, or as a snap package, or anything of this sort, correct? And your OS is fully 64-bit, no mixing of 32 and 64-bit packages?

Please post the output of:
```
LIBGL_DEBUG=verbose glxinfo 
```

**Comment by Dylan-86** [comment]
> Hey @Dylan-86,
> 
> The first issue with canberra-gtk-module would likely be resolved by running
> 
> ```
> sudo apt install --reinstall libcanberra-gtk-module libcanberra-gtk3-module
> ```
> 
> The other error message says iris_dri.so can't be loaded. On my system, this file is provided by the `mesa` package. You could try installing the relevant package and see if that solves the problem. A quick check suggests
> 
> ```
> sudo apt install libglu1-mesa
> ```
> 
> might do the trick.
> 
> Before we dig deeper into the GL issue - you're not running this in a VM, or a container, or as a snap package, or anything of this sort, correct? And your OS is fully 64-bit, no mixing of 32 and 64-bit packages?
> 
> Please post the output of:
> 
> ```
> LIBGL_DEBUG=verbose glxinfo 
> ```

Thank you.

Solved. 
1. I was using Snap in fact. I tried your command but still got the same error.
2. Removed snap and installed the "normal version": works like a charm.
Thanks!
