### ISSUE TITLE
Bug: Crunchyroll's Video Player Not Working

### ISSUE THREAD

**Issue by 8227846265** [brave/brave-browser#15493]
## Description 
Streaming anime on Crunchyroll on Brave Browser doesn't work. The video player doesn't appear on Brave while other browsers works just fine.

I already disabled all extensions and even accessed it via Incognito. Nothing worked.

## Steps to Reproduce

   1. Go to: https://www.crunchyroll.com/86-eighty-six/episode-1-undertaker-811078 or any anime episode.
   2. Wait for the website to load
   

## Actual result:

Video Player Doesn't Appear
![image](https://user-images.githubusercontent.com/66582769/116033599-4e106500-a694-11eb-8637-87a908ee785f.png)

## Expected result:
Video Player should appear

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

- Brave Browser Version 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
- Windows 10 x64

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes

- Can you reproduce this issue with the beta channel? 
Haven't tried.

- Can you reproduce this issue with the nightly channel? 
Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No

- Does the issue resolve itself when disabling Brave Rewards? 
No

- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by rebron** [comment]
cc: @Brave-Matt @ryanbr Can you take a look?

**Comment by ryanbr** [comment]
Tested in Brave release, Beta and Nightly. The video load fine (with a preroll advert) @8227846265   does it still occur in private window mode?

**Comment by 8227846265** [comment]
Hi everyone, it seems a false-positive. I am using ControlD on my Secure DNS settings, and it seems it's the DNS blocking the player from loading.

**Comment by 8227846265** [comment]
Note:

- Disabling Secure DNS (with ControlD DNS) temporarily and re-enabling it fixes the issue.
