### ISSUE TITLE
Cannot disable brave rewards after the latest update

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#15492]
##  Description: 

After the latest Android update, with the updated tab menu, there is no way to disable brave rewards

## Steps to reproduce 

   1. Turn off the brave rewards icon
   2. On a tab, tap the (...) icon
   3. Verify that brave rewards still show up there

##  Actual result 

![Screenshot_20210425-144219_Brave.png](https://user-images.githubusercontent.com/2473545/116003544-c3b4fc00-a5d4-11eb-9f97-228c59994dc4.png)

## expected results:

There should be a way to completely disable unwanted features. I moved away from chrome because of unwanted features that cannot be disabled. I can easily move to another browser as well.

**Comment by Miyayes** [comment]
You can disable all Rewards features if you've already enabled it in brave://rewards, and you can hide the BAT icon in the URL bar via brave://settings. Thanks.
