### ISSUE TITLE
Re-applying patches causes patch error in content_settings.mojom

### ISSUE THREAD

**Issue by garrettr** [brave/brave-browser#155]
### Description

Running `apply-patches.py` multiple times results in `src/components/content_settings/core/common/content_settings.mojom` getting patched incorrectly, which causes the build to fail.

### Steps to Reproduce

In root of brave-browser repository:

1. ​Get the latest source: `yarn run sync --all`. This will apply patches the first time.
2. `tail src/components/content_settings/core/common/content_settings.mojom`
    1. Note there is just one `};` at the end of the file.
3. `yarn run sync --run_hooks`. This applies patches the second time.
    1. Note that content_settings.mojom is not listed as "already patched" in the output from apply-patches.py.
4. `tail src/components/content_settings/core/common/content_settings.mojom`
    1. Note that there are not two trailing "};"'s at the end of the file.
5. yarn build
    1. Will fail with error about unexpected "};"

**Actual result:**

```
[13/1357] ACTION //components/content_settings/core/common:mojo_bindings_shared__generator(//build/toolchain/mac:clang_x64)
FAILED: gen/components/content_settings/core/common/content_settings.mojom-shared-internal.h gen/components/content_settings/core/common/content_settings.mojom-shared.cc gen/components/content_settings/core/common/content_settings.mojom-shared.h 
python ../../mojo/public/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs generate ../../components/content_settings/core/common/content_settings.mojom -d ../../ -I ../../ -o gen --bytecode_path gen/mojo/public/tools/bindings --scrambled_message_id_salt_path ../../chrome/VERSION --allow_native_structs --generate_non_variant_code -g c++ --depfile gen/components/content_settings/core/common/mojo_bindings_shared__generator_content_settings.d --depfile_target gen/components/content_settings/core/common/content_settings.mojom-shared-internal.h
../../components/content_settings/core/common/content_settings.mojom:77: Error: Unexpected '}':
};
```

**Expected result:**

Successful build without errors. 

**Reproduces how often:**

100% after re-applying patches.

**Comment by garrettr** [comment]
This appears to be a bug in the `python-patch` script used by `apply-patches.py` to apply patches. I am able to reproduce by running `python-patch` only for the affected patch file:

    python src/brave/vendor/python-patch/patch.py --directory src/. --quiet src/brave/patches/components-content_settings-core-common-content_settings.mojom.patch

Every invocation of this command results in an additional trailing "};" line being added at the end of `content_settings.mojom`.

Other patch application tools, e.g. `git apply`, do not exhibit the same behavior. `git apply` applies the patch correctly to an unmodified `content_settings.mojom`, and subsequent invocations report "patch failed" and do not make further modifications to `content_settings.mojom`.

Possibly the same as this upstream bug: https://github.com/techtonik/python-patch/issues/55.

**Comment by fmarier** [comment]
I just ran into this problem too. It now affects three different files:

- `chrome/browser/resources/settings/page_visibility.html`
- `chrome/browser/resources/settings/site_settings/pdf_documents.js`
- `components/content_settings/core/common/content_settings.mojom`

Here's another way to reproduce the problem. In a brave-browser repo, start by sync'ing:

    npm run sync -- --all

then look at the patches that were applied automatically to `src/`:

    cd src/
    git diff > ~/before-apply-patches.patch

Now, apply the patches again:

    cd ..
    npm run apply_patches

and look at what changed:

    cd src
    git diff > ~/after-apply-patches.patch
    interdiff ~/before-apply-patches.patch ~/after-apply-patches.patch

Right now, this gives me the following:

```
diff -u b/chrome/browser/resources/settings/page_visibility.html b/chrome/browser/resources/settings/page_visibility.html
--- b/chrome/browser/resources/settings/page_visibility.html
+++ b/chrome/browser/resources/settings/page_visibility.html
@@ -4,0 +5 @@
+<script src="brave_page_visibility.js"></script>
diff -u b/chrome/browser/resources/settings/site_settings/pdf_documents.js b/chrome/browser/resources/settings/site_settings/pdf_documents.js
--- b/chrome/browser/resources/settings/site_settings/pdf_documents.js
+++ b/chrome/browser/resources/settings/site_settings/pdf_documents.js
@@ -28,0 +29,8 @@
+  /** @override */
+  ready: function () {
+    if (loadTimeData.getBoolean('isPdfjsDisabled')) {
+      this.$.toggle.disabled = true;
+      this.$.toggle.checked = true;
+    }
+  },
+});
diff -u b/components/content_settings/core/common/content_settings.mojom b/components/content_settings/core/common/content_settings.mojom
--- b/components/content_settings/core/common/content_settings.mojom
+++ b/components/content_settings/core/common/content_settings.mojom
@@ -78,0 +79,2 @@
+  array<ContentSettingPatternSource> brave_shields_rules;
+};
```

whereas this should really be a no-op.
