### ISSUE TITLE
tab groups don't work on new profiles even though enabled by default

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#15506]
## Description 

When launching Brave for the first time, you'll notice that `Tab Groups` are not working by default even though they're enabled by default via `Appearance` in `Settings`. You'll basically need to disable/restart/enable/restart to get them working. @srirambv reproduced the issue as well.

## Steps to reproduce 

   1. launch `1.25.42 Chromium: 90.0.4430.85`
   2. you'll notice that `Tab Groups` are not working despite being enabled by default
   3. go into `Appearances` under `Settings` and disable/enable `Tab Groups`

Once you've restarted, they'll start working as expected.

## Actual result 

`Tab Groups` are not working when launching Brave for the first time despite being enabled by default

## Expected result

Tab Groups should work as soon as Brave is launched for the first time as it's enabled by default.

## Issue reproduces how often 

100% reproducible using the above STR.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 11`
   
## Brave version

* `1.25.42 Chromium: 90.0.4430.85` - **Reproduced**
* `1.23.74 Chromium: 90.0.4430.85` - **Reproduced**

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @SergeyZhukovsky @samartnik @srirambv @bsclifton @anthonypkeane

**Comment by kjozwiak** [comment]
Discussed with @samartnik @SergeyZhukovsky and @srirambv. This is a known issue and also happens in Chrome. You'll basically need to restart the browser twice before being able to use Tab Groups. We'll wait for an upstream fix.

**Comment by samartnik** [comment]
This was fixed in the upstream.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave Beta `1.32.94, Chromium 95.0.4638.69` on Android 9, using a Google Pixel XL.

Steps:
1. fresh install
2. loaded `Settings` -> `Appearance` and confirmed `Enable Tab Groups` is set to `On`
3. opened `abcnews.com`, `bbcnews.com`, and `cbsnews.com` in separate tabs
4. tapped on the `[3]` in the bottom toolbar
5. tapped on the vertical 3-dots menu item
6. tapped `Group tabs`
7. selected all tabs and tapped `Group`

Confirmed all 3 tabs were grouped together.

example | example | example | example | example
---------|----------|---------|----------|---------
![Screenshot_20211108-121537](https://user-images.githubusercontent.com/387249/140812501-156af2dc-9af4-4c16-96bf-5ab06d884566.png) | ![Screenshot_20211108-121548](https://user-images.githubusercontent.com/387249/140812503-dd3172f4-bf08-48f8-a336-0ac02f7ce4d5.png) | ![Screenshot_20211108-121601](https://user-images.githubusercontent.com/387249/140812506-3ea9f19a-968a-4349-b9f0-325726b6c515.png) | ![Screenshot_20211108-121613](https://user-images.githubusercontent.com/387249/140812509-fe31db11-88c3-469f-ae9c-40d64a5e3460.png) | ![Screenshot_20211108-121625](https://user-images.githubusercontent.com/387249/140812510-3ab907d4-31e4-48ce-89d1-75382d123cbc.png)

**Comment by btlechowski** [comment]
No applicable to Tablet.
