### ISSUE TITLE
Crashed when dragging enters into sidebar web panel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15505]
Crashed when dragging enters into sidebar webpanel. Only happen on macOS.

## Steps to Reproduce

   1. Enable sidebar feature via brave://flags and re-launch
   2. Load brave.com in a new tab
   3. Click sidebar's brave together panel
   4. Dragging brave.com tab's site info (security icon in omnibox) into sidebar web panel

## Actual result:

Crashed

## Expected result:
Not crashed

## Version/Channel Information:

- Can you reproduce this issue with the current release? NO
- Can you reproduce this issue with the beta channel? NO
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Marking as `QA/Blocked` until we get Sidebar merged into the `1.25.x` branch.

**Comment by LaurenWags** [comment]
@rebron to confirm, but I think sidebar is behind a flag - so I think we should be able to test this one.

**Comment by simonhong** [comment]
@LaurenWags Yes, sidebar is behind a flag and that flag is only available for nightly. it's not available for beta/stable yet.

**Comment by LaurenWags** [comment]
per discussion with @simonhong @rebron @stephendonner this can be tested on Nightly

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.26.21 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 10.15.7 (Build 19H1030)
```

Verified STR from description. Confirmed no crash was observed.
