### ISSUE TITLE
Brave crashes after clicking on the share icon in the shield 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15507]
## Description 

Brave crashes after clicking on the share icon in the shield 
## Steps to reproduce 

   1. Open 1.25.28 nightly build
   2. Open a site
   3. Click on the shield icon 
   4. Click on the share icon 

## Actual result 
Brave crashes after clicking on the share icon in the shield 

## Expected result
Should not be any crash

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy J3 
   - Android version: 5.1.1
   
## Brave version

1.25.28
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane

**Comment by kjozwiak** [comment]
Removing the `1.25.x` milestone and the `release/blocking` label after discussing with @SergeyZhukovsky & @bsclifton. We don't have a lot of users that are currently on `Android <7` so we'll let this ride the trains. When we release `1.25.x` and notice this is becoming a problem, we can get it uplifted into a `1.25.x` HF.

**Comment by anthonypkeane** [comment]
@GeetaSarvadnya this should be on nightly in the next day or so. Thanks

**Comment by srirambv** [comment]
@alexsafe can you please create uplifts for this to 1.26.x once @GeetaSarvadnya verifies the issue on nightly and updates the https://github.com/brave/brave-core/pull/8808.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.27.75 x64 build
- Verified no crash when share icon from shields is selected
-------------
Verification passed on Samsung Tab A with Android 10 running 1.27.75 x64 build
- Verified no crash when share icon from shields is selected
