### ISSUE TITLE
Log Rewards errors by default

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15500]
Currently, the rewards log must be enabled using a command-line flag. When enabled, it will log at "verbose" level, which includes URL responses and other arbitrary data. In order to provide a better experience for diagnosing rewards issues:

- We should log at the "error" level by default. Current call sites that log errors should be audited and modified so that they do  not log arbitrary data at the "error" level.
- We should create a feature flag that will enable "verbose" logging.

**Comment by diracdeltas** [comment]
cc @PrivacyMatters. can we ensure that the errors don't include full URLs, PII, or sensitive info like tokens?

for the feature flag, we should include something in the description that tells users that sensitive information may be written to disk if they turn this flag on.

**Comment by PrivacyMatters** [comment]
Flags in 'Experiments' brave://flags have 3 settings: default, enabled, disabled.  What does the 'Default' setting do? What is its purpose?

Will the the proposed flag be set to disabled?  As per @diracdeltas what is the proposal re logging of URLs, ads viewed etc that may impact privacy if disclosed to Brave?

**Comment by kjozwiak** [comment]
@brave/legacy_qa we won't be able to verify the above until we get https://github.com/brave/brave-browser/issues/15924 fixed and uplifted into `1.25.x`.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, this should be available for testing in https://github.com/brave/brave-browser/releases/tag/v1.25.64

**Comment by kjozwiak** [comment]
https://github.com/brave/brave-core/pull/8841 has been fixed and merged so the above can now be checked on `Android` once we new `1.25.x` builds. CCing @srirambv.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.66 x64 build
- Verified only error logs are captured when flag is disabled
- Verified full logs are captured when flag is enabled
- Verified Clear/Refresh/Auto-Refresh/Download logs works correctly for both error logs and full logs

Error logs (Flag not set) | Full Logs (Flag enabled)
-- | --
![image](https://user-images.githubusercontent.com/17010094/119456745-e43ab800-bd32-11eb-9ced-f8cc73165553.png) | ![image](https://user-images.githubusercontent.com/17010094/119456803-f0267a00-bd32-11eb-9903-bb3c2cfceabf.png)

-------------
Verification passed on Samsung Tab A with Android 10 running 1.25.66 x64 build
- Verified only error logs are captured when flag is disabled
- Verified full logs are captured when flag is enabled
- Verified Clear/Refresh/Auto-Refresh/Download logs works correctly for both error logs and full logs
 
Error logs (Flag not set) | Full Logs (Flag enabled)
-- | --
![image](https://user-images.githubusercontent.com/17010094/119457612-c588f100-bd33-11eb-822c-5136907443ae.png) | ![image](https://user-images.githubusercontent.com/17010094/119457635-cde12c00-bd33-11eb-906d-92c883ba9a78.png)
