### ISSUE TITLE
Update Startpage icon

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#15515]
### Description: 
We reference Startpage during onboarding and also in our settings. They have provided us with a new icon

**Actual result:** 
![image](https://user-images.githubusercontent.com/4733304/116280676-cbdc7b00-a73d-11eb-9ec9-c09acf4e89ce.png)
https://github.com/brave/brave-core/blob/master/android/java/res/drawable-hdpi/search_engine_startpage.png
https://github.com/brave/brave-core/blob/master/android/java/res/drawable-xhdpi/search_engine_startpage.png
https://github.com/brave/brave-core/blob/master/android/java/res/drawable-xxhdpi/search_engine_startpage.png

**Expected result:**
![image](https://user-images.githubusercontent.com/4733304/116280624-ba936e80-a73d-11eb-88f7-beb3b5b065a3.png)

### Additional Information
Updated images per @jamesmudgett 
[startpage-android.zip](https://github.com/brave/brave-browser/files/6386246/startpage-android.zip)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.60 x64 Beta Build
- Verified icon is shown properly

https://user-images.githubusercontent.com/17010094/118443243-92b37d00-b6e3-11eb-8008-0684de4d1f81.mp4

--------
Verification passed on Samsung Tab A with Android 10 running 1.25.60 x64 Beta Build
- Verified icon is shown properly

https://user-images.githubusercontent.com/17010094/118442943-2df82280-b6e3-11eb-9db1-eb791f8457de.mp4
