### ISSUE TITLE
YouTube redirects to mobile site on Desktop

### ISSUE THREAD

**Issue by cjduncana** [brave/brave-browser#15513]
## Description 
If you visit YouTube on Brave (tried in Safari w/ no problems), you get redirected to the mobile site. The odd thing is that in incognito mode, it correctly shows you the desktop site. It even redirects you to the desktop site if you input a mobile address.

## Steps to Reproduce
   1.  Enter www.youtube.com into the address bar

## Actual result:
You end up on the mobile website instead of the desktop website
![Screen Shot 2021-04-27 at 12 32 25 PM](https://user-images.githubusercontent.com/1977082/116278586-3f858480-a74c-11eb-822e-b11d2411741d.png)

## Expected result:
I expected to end up on the desktop site
![Screen Shot 2021-04-27 at 12 34 28 PM](https://user-images.githubusercontent.com/1977082/116278890-88d5d400-a74c-11eb-8721-dd1225a75dad.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

| Property | Value |
| --- | --- |
| Brave           | 1.23.73 Chromium: 90.0.4430.85 (Official Build) (x86_64) |
| Revision      | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311} |
| OS               | macOS Version 10.15.7 (Build 19H524) |
| JavaScript  | V8 9.0.257.19 |
| User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 |

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
  - No
- Does the issue resolve itself when disabling Brave Rewards? 
  - Don't know
- Is the issue reproducible on the latest version of Chrome? 
  - Don't know

## Miscellaneous Information:
I tried disabling cache and Empty Cache and Hard Reload on YouTube, but it didn't change anything.

**Comment by ryanbr** [comment]
When testing mobile UA on desktop, this occur. The easiest fix is to clear the youtube cookies and manually type `www.youtube.com` to avoid any autocorrect to `m.youtube.com` @cjduncana

**Comment by cjduncana** [comment]
I see. I had to clear YouTube's cookies and not its cache 👌🏻
Thanks 🙌🏻
