### ISSUE TITLE
Google Earth

### ISSUE THREAD

**Issue by Joseph-Christman** [brave/brave-browser#1551]
## Description 

Google Earth doesn't seem to load in Brave. The loading screen will show, but nothing ever loads. In Chrome, it loads pretty quickly.
## Steps to Reproduce
   1. Go to https://earth.google.com/web/
   2. Wait.
   3. 

## Actual result:
The loading screen shows, but nothing ever loads.

## Expected result:
In Chrome, the files will load in about a fraction of a second, and text underneath the loading bar will show progress.

## Reproduces how often: 
It's easily and consistently reproducible.

## Brave version (chrome://version info)

Brave | 0.56.2 Chromium: 70.0.3538.35 (Official Build) dev(64-bit)
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

### Reproducible on current release:
It's reproducible in both the dev build and the stable build.

### Website problems only:  
Turning off the shield does not help. The problem is not reproducible on the latest Chrome.

### Additional Information
This problem has been observed on Solus Linux and Ubuntu.

**Comment by scmart** [comment]
+1

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/google-earth-doesnt-work/42628

**Comment by bencefr** [comment]
+1

Also doesn't work and probably related:
- Google Maps 3D view when zoomed out
- Google Photos showing panorama image

**Comment by ChildishGiant** [comment]
Also replicated on nightly on Windows

**Comment by Jonany** [comment]
+1
Replicated on Windows 10 with Brave version 0.61.52, Chromium: 73.0.3683.86

**Comment by bsclifton** [comment]
Possibly related: https://github.com/brave/brave-browser/issues/3519

If using NaCl is needed for these to work as expected, it'll be a `wontfix`

**Comment by yhbautista** [comment]
+1

Replicated on Windows 10 with Brave version 0.62.51, Chromium 64-bit version 73.0.3683.103 

If it's not being fixed, can it be marked and noted?

**Comment by BoostedDampi** [comment]
+1
Replicated on Windows 10 Version 0.62.51 Chromium: 73.0.3683.103

**Comment by bsclifton** [comment]
Closing as `wontfix`. I believe this is because we don't include NaCl (reported with https://github.com/brave/brave-browser/issues/3519)

An effort should be made soon to replace this with a native client (was scheduled for Q2 of this year). See more details at:
https://developer.chrome.com/native-client/migration

**Comment by rebron** [comment]
Updated, Google Earth built with Web Assembly. 
https://earth.google.com/web/?beta=1

You should be able to run Google Earth now in Brave.

**Comment by Mhowser** [comment]
@rebron that URL does not work. This is the error found in the Inspector console:
![image](https://user-images.githubusercontent.com/24195572/66700508-ece99200-eca5-11e9-9a10-518553adc75e.png)
However, changing the `Device Recognition attempts`in Brave Shields to either cross-site or allowed works:
![image](https://user-images.githubusercontent.com/24195572/66700566-7a2ce680-eca6-11e9-910e-3041fbda18e8.png)

**Comment by szaimen** [comment]
Actually it doesn't work in my experience also when disabling the shields completely.

**Comment by rebron** [comment]
@szaimen Can you file a new issue and provide as much detail as possible (brave, version, os, etc) https://earth.google.com/web/?beta=1 and with the latest versions of Brave across channels, it's looking like it's working correctly.

**Comment by szaimen** [comment]
No, it is working.
Sry haven't seen the link https://earth.google.com/web/?beta=1

**Comment by oo-00** [comment]
@rebron the link now just redirects to standard google earth url. No matter what I try, it just redirects or at least changes the window location. And is not working.

**Comment by deunix-educ** [comment]
Digital fingerprint configuration: do not support strict mode, choose normal or None

**Comment by oo-00** [comment]
Seems to be fixed in the newest version of brave. I didn't need to change any settings.
