### ISSUE TITLE
Update Crypto Wallets Support Contact Info 

### ISSUE THREAD

**Issue by aaronsantamaria** [brave/brave-browser#15519]
## Description 

After creating a new crypto wallet you will see a completion/congratulations message. support@ is listed as an email to contact for help. That email is not active. It would be best to change that to point users to Community's Wallet category https://community.brave.com/c/support-and-troubleshooting/wallet/131

## Steps to Reproduce

   1. Go to brave://wallet/
   3. Create a New Local Wallet
   2. Run through the steps
   3. Completion/congratulations message will appear showing contact info

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.26.64 Chromium: 91.0.4472.114 (Official Build) (x86_64)
-- | --
Revision | `4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.30 Dev`

- Verified support contact info is updated to `https://community.brave.com/c/support-and-troubleshooting/wallet/131`

https://user-images.githubusercontent.com/17010094/122886345-ca8f8f00-d337-11eb-880d-c909fa879d2b.mov

-------------
Verification passed on 

Brave | 1.27.69 Chromium: 91.0.4472.106 (Official Build) beta (64-bit)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | Windows 10 OS Version 2009 (Build 19042.1052)
Component | `1.0.30 Dev`

- Verified support contact info is updated to `https://community.brave.com/c/support-and-troubleshooting/wallet/131`

https://user-images.githubusercontent.com/17010094/122892115-06792300-d33d-11eb-947d-e67fb2b7008b.mp4

---------
Verification passed on

Brave | 1.28.17 Chromium: 91.0.4472.114 (Official Build) nightly (64-bit)
-- | --
Revision | `4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}`
OS | Linux
Component | `1.0.30 Dev`

- Verified support contact info is updated to `https://community.brave.com/c/support-and-troubleshooting/wallet/131`

https://user-images.githubusercontent.com/17010094/122886939-4db0e500-d338-11eb-87bc-e907b42a144d.mp4
