### ISSUE TITLE
--permission-lifetime-test-seconds=20 doesn't appear to work on Android nightly builds

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15523]
## Description 
`--permission-lifetime-test-seconds=20` doesn't appear to work on Android nightly builds

## Steps to Reproduce

   1.  launch `nightly` on Android
   2. enable `Permission Lifetimes` via `brave://flags`
   3. open `Settings` > `Developer Options` > `QA Preferences`
   4. enter the code (ping me on Slack if you don't have it)
   5. input `--permission-lifetime-test-seconds=20` into the `Enter Command Line string` textfield
   6. tap `OK`
   7. tap on `RELAUNCH NOW`
   8. open `https://permission.site`
   9. tap on `Camera + Microphone`
   10. look at the radio-button options under `Give permission`

## Actual result:

There's no `20 seconds` option to choose from amongst the radio buttons for `Give permission`

example | example | example
---------|----------|---------
![Screenshot_20210427-145940](https://user-images.githubusercontent.com/387249/116319057-afa30300-a76a-11eb-8a76-9d4e40ad3501.png) | ![Screenshot_20210427-145954](https://user-images.githubusercontent.com/387249/116319062-b0d43000-a76a-11eb-86a2-b87d120a9041.png) | ![Screenshot (Apr 27, 2021 3 10 53 PM)](https://user-images.githubusercontent.com/387249/116319157-dc571a80-a76a-11eb-9296-75ad0f485d04.png)

## Expected result:

There should be a `20 seconds` option below `forever`, as there is on desktop

<img width="1312" alt="Screen Shot 2021-04-27 at 3 07 57 PM" src="https://user-images.githubusercontent.com/387249/116319237-04467e00-a76b-11eb-930c-c45873c6f563.png">

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave - `Nightly 1.25.42, Chromium 90.0.4430.85` on `Android 9`

@goodov @deeppandya am I doing this right?  Thanks in advance for looking! 👍

**Comment by goodov** [comment]
This cmdline stub mechanism ignores the first parameter if `qa_vlog_rewards` is not enabled. This is not specific to `permission-lifetime-test-seconds`, any parameter will be ignored. To test things you can use this: `--a --permission-lifetime-test-seconds=10`.

**Comment by goodov** [comment]
Created to fix this behavior. https://github.com/brave/brave-browser/issues/15540
