### ISSUE TITLE
Notification and navigation bar remain in full screen video

### ISSUE THREAD

**Issue by theoturner** [brave/brave-browser#15522]
## Description
On Android, the notification and navigation bar remain in full screen video as of 1.23.74

## Steps to reproduce

 1. Put a video in full screen.

## Actual result

Notification and navigation bar remain during full screen video.

## Expected result

Notification and navigation bar are hidden during full screen video.

## Issue reproduces how often

Always.

## Version/Channel Information:

1.23.74 (current Play Store version)

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
 
1.23.74

**Comment by theoturner** [comment]
<!-- Have you searched for similar issues? Before submitting this issue, please check the open issues and add a note before logging a new issue. 

PLEASE USE THE 

## Description
On Android, the notification and navigation bar remain in full screen video as of 1.23.74

## Steps to reproduce

 1. Put a video in full screen.

## Actual result

Notification and navigation bar remain during full screen video.

## Expected result

Notification and navigation bar are hidden during full screen video.

## Issue reproduces how often

Always.

## Version/Channel Information:

1.23.74 (current Play Store version)

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
 
1.23.74

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/hide-the-back-home-buttons-below-brave/246231/6

**Comment by anthonypkeane** [comment]
Hi @theoturner @Brave-Matt  - we tested this on a Samsung 10 and a ew other devices and it worked ok. There maybe some Android OS settings that are forcing the system bar to persist. Did you try looking in Android settings?
