### ISSUE TITLE
On first boot for Japan region, have a tab pre-opened to a specific webpage

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15526]
## Description

When a user boots up the browser for the first time in Japan, another background tab (not focused, and not interacting with the brave://welcome experience) can already be opened to a certain webpage/URL.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.25.64 Chromium: 90.0.4430.212 (Official Build) beta （x86_64）
変更履歴	e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS	macOS バージョン10.15.7（ビルド19H1030）
```

Verified scenarios listed in https://github.com/brave/brave-core/pull/8686#issuecomment-840583532

<details>
<summary>Scenario 1 - clean profile Japan region</summary>

Verified test plan from https://github.com/brave/brave-core/pull/8686.
Confirmed brave://welcome was opened and active tab.
Confirmed https://brave.com/ja/users-bitflyer/ was opened in background tab.
Confirmed if brave://welcome and the blog page are closed and a new tab is opened, when browser is relaunched another background tab with the blog is not opened.
Confirmed if brave://welcome is closed and the blog page is opened, when the browser is relaunched another background tab with the blog is not opened.

Additional testing done with https://github.com/brave/brave-browser/issues/15794.

</details>

<details>
<summary>Scenario 2 - clean profile non-Japan region</summary>

Used US for non-Japan region.

Confirmed on clean install no secondary (background) tab was opened with blog.
Closed and relaunched several times, confirmed no additional tab was opened.

</details>

<details>
<summary>Scenario 3 - upgrade profile Japan region</summary>

Installed 1.24.85 and visited a few sites.
Closed 1.24.85.
Renamed profile to `Brave-Browser-Beta`.
Launched with 1.25.x.
Confirmed no background tab w/ the blog was opened.
Closed/reopened several times.
Confirmed no background tab w/ the blog was opened.

</details>

<details>
<summary>Scenario 4 - upgrade profile non-Japan region</summary>

Used US for non-Japan region.

Installed 1.24.85 and visited a few sites.
Closed 1.24.85.
Renamed profile to `Brave-Browser-Beta`.
Launched with 1.25.x.
Confirmed no background tab w/ the blog was opened.
Closed/reopened several times.
Confirmed no background tab w/ the blog was opened.

</details>
