### ISSUE TITLE
Brave wallet corrupts Brave wallet balance after linking to uphold. Brave wallet no longer has correct balance.

### ISSUE THREAD

**Issue by bakedmuffinman** [brave/brave-browser#15525]
I have searched this issue and cannot find a resolve. Most issues appear to be BAT missing from uphold balance. this is not that. 
This is Bat missing from Brave wallet balance after syncing to uphold. im missing over 160 BAT.

## Description 
Synced brave wallet to uphold. BAT disappeared from brave wallet. un synced from uphold. BAT still missing from Brave wallet. Recovered wallet. BAT still misssing from brave wallet.

I can see these two lines in :brave://rewards-internals event logs tab

04/09/2021, 11:38:39 AM | promotion_claimed | 163.000000-- | -- | --

after a recovery I get this

04/10/2021, 06:54:26 PM | promotion_corrupted_migrated2 | 1-- | -- | --

I have tried recovery twice.

Brave | 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | Windows 10 OS Version 2009 (Build 19042.928)

**Comment by Mubelotix** [comment]
Well, I was more lucky than you since 5 BAT were added to my wallet

**Comment by bsclifton** [comment]
@bakedmuffinman @Mubelotix if you weren't already able to solve this, I'd like to ask if you can connect and login to Uphold. Once in there, you'll see the cards available to you. We are expecting an Uphold card named `Brave Browser` - you can transfer the BAT to that card and it should show up

**Comment by Miyayes** [comment]
This means the BAT transfer to your Uphold account is stuck for some reason or another. We can look into it with your Wallet Payment ID in brave://rewards-internals (general info). This is more of a general support issue that we handle quite often. You can feel free to email me at christopher at brave dot com with your Wallet Payment ID as well. Will close this issue as it's more of a support ticket.
