### ISSUE TITLE
[Android] Artefacts of YouTube full-screen videos

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#15548]
## Description 
Occasionally there are artefacts of YouTube full-screen videos

![Screenshot_20210427-100348_Brave](https://user-images.githubusercontent.com/30602739/116455712-65d02080-a82f-11eb-9035-800a3eb6e82e.jpg)

## Steps to reproduce 

   1. Start any YouTube video
   2. Go to full screen mode
   3. Sometimes it requires to repeat it several times to reproduce. Sometimes  it's not reproducible.

## Actual result 
See screenshot above

## Expected result
No artefacts

## Issue reproduces how often 
Sometimes

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `No`
- Can you reproduce this issue with the current Play Store Nightly version? `No`

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version

Stable version only

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `No`

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/8667 was merged and `1.23.76 Chromium: 90.0.4430.93` was started.

**Comment by SergeyZhukovsky** [comment]
1.23.76 works as expected on my device where I could replicate it on a previous version
![Screenshot_20210428-221929_Brave](https://user-images.githubusercontent.com/12011303/116495046-2675f400-a870-11eb-8ac7-3ee1739c2f2d.jpg)

**Comment by srirambv** [comment]
Marking as QA Pass based on previous comment. Thanks for the verification @SergeyZhukovsky
