### ISSUE TITLE
[Canvas] Tooltips and chart legends are not rendered properly

### ISSUE THREAD

**Issue by felsd** [brave/brave-browser#15542]
## Description 
Tooltips and chart legends, for example `chart.js` but also others are not rendered properly.

## Steps to Reproduce

   1. Visit [https://www.chartjs.org/docs/latest/samples/bar/horizontal.html](https://www.chartjs.org/docs/latest/samples/bar/horizontal.html)
   2. Mouseover any bar in the chart, or look at the legend on the right
   3. Texts are not readable

## Actual result:
[Chart.JS example screenshot](https://ibb.co/cvNyfDz)
[TradingView screenshot](https://ibb.co/c3WtNDY)

## Expected result:
Tooltips and chart legends are readable.

## Brave version (brave://version info)
```
Brave: 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
Revision: 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS: Linux
JavaScript: V8 9.0.257.19
```

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No, everything ok using Chromium.

## Miscellaneous Information:
Linux `5.11.14-arch1-1` with `dwm` window manager, `brave-bin` from the AUR.

**Comment by rebron** [comment]
@felsd Are you still encountering this issue with the latest 1.27.109 Chromium: 92.0.4515.115?
Looks like per your steps to reproduce the text looks correct now.

**Comment by felsd** [comment]
> @felsd Are you still encountering this issue with the latest 1.27.109 Chromium: 92.0.4515.115?
> Looks like per your steps to reproduce the text looks correct now.

I couldn't test `1.27.109` yet, I'm using the brave-bin AUR which wasn't updated yet because of an incompatibility issue with `systemd-resolved`.
But I'm looking forward to testing it soon. Were you able to reproduce the issues I'm encountering in prior versions?

**Comment by felsd** [comment]
@rebron I was able to test with `1.27.111 Chromium: 92.0.4515.131 (Official Build) (64-bit)` now, but the rendering issues still persist.
![2021-08-06_12-21](https://user-images.githubusercontent.com/42386423/128460014-7a33cd23-22fe-4be5-9c67-211816f46975.png)

**Comment by matias-pg** [comment]
This is an old [issue](https://github.com/chartjs/Chart.js/issues/6197) that happens when Fingerprinting blocking is in Strict mode. Changing it to Standard on the page should fix this.

**Comment by felsd** [comment]
> This is an old [issue](https://github.com/chartjs/Chart.js/issues/6197) that happens when Fingerprinting blocking is in Strict mode. Changing it to Standard on the page should fix this.

Thanks, that was it! Totally forgot aobut that setting.
