### ISSUE TITLE
Update bitFlyer promo image and add Learn More link

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15549]
## Description

The image displayed on the Rewards onboarding tour "verify wallet" panel should be updated to the latest version provided by bitFlyer. In addition, the verify wallet panel should have a "Learn more" sentence with a link below the gray notice area.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.26.6 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:

### Rewards Panel

1. Started the browser with a clean profile, while set to JP region, staging environment
2. Went to `brave://flags` and set `bitflyer for Brave Rewards` to `Enabled`
3. Relaunched the browser
4. Clicked the Rewards icon
5. Clicked `Start using Rewards`
6. Advanced through the tour
7. Verified that the last panel contains the bitFlyer "Verify Wallet" CTA
8. Verified that the `Learn more` link was displayed below the gray notice area
9. Verified that the `Learn more` link, when clicked, opened a new tab pointed to `https://brave.com/ja/users-bitflyer/`
10. Verified that no image was displayed

enabled bitFlyer flag | Verify your wallet slide | https://brave.com/ja/users-bitflyer/
---------|---------|----------
<img width="1312" alt="スクリーンショット 2021-05-03 15 33 03" src="https://user-images.githubusercontent.com/387249/116942487-8b419d80-ac26-11eb-90cd-1168e53589fb.png"> | <img width="1312" alt="スクリーンショット 2021-05-03 15 33 22" src="https://user-images.githubusercontent.com/387249/116942493-8d0b6100-ac26-11eb-8af8-d3080af51a2f.png"> | <img width="1312" alt="スクリーンショット 2021-05-03 15 33 40" src="https://user-images.githubusercontent.com/387249/116942500-8f6dbb00-ac26-11eb-9a10-3c4525205fd4.png">


### Rewards Page

1. Started the browser with a clean profile, JP region, staging environment
2. Went to `brave://flags` and set `bitflyer for Brave Rewards` to `Enabled`
3. Relaunched the browser
4. Went to `brave://rewards`
5. Clicked `Start using Rewards`
6. Advanced through the tour
7. Verified that the last panel contained the bitFlyer `Verify Wallet` CTA
8. Verified that the `Learn more` link is displayed below the gray notice area
9. Verified that the `Learn more` link, when clicked, opens a new tab pointed to `https://brave.com/ja/users-bitflyer/`
10. Verified that the promo image is displayed
11. Verified that the promo image, when clicked, opened a new tab pointed to: `https://bitflyer.com/static/lp03/?ns=display_brave_bf_brave&utm_source=brave&utm_medium=display&utm_campaign=bf_brave&utm_term=202104&utm_content=`

enabled bitFlyer flag | Learn more link | Promo image link | bitFlyer promo landing page
---------|---------|----------|---------
<img width="1312" alt="スクリーンショット 2021-05-03 15 33 03" src="https://user-images.githubusercontent.com/387249/116942487-8b419d80-ac26-11eb-90cd-1168e53589fb.png"> | <img width="1312" alt="スクリーンショット 2021-05-03 15 36 00" src="https://user-images.githubusercontent.com/387249/116942608-c643d100-ac26-11eb-9184-fef9b96dfa6d.png"> | <img width="1312" alt="スクリーンショット 2021-05-03 15 36 18" src="https://user-images.githubusercontent.com/387249/116942610-c6dc6780-ac26-11eb-8e1f-96dc419c4e8d.png"> |  <img width="1312" alt="スクリーンショット 2021-05-03 15 36 34" src="https://user-images.githubusercontent.com/387249/116942612-c6dc6780-ac26-11eb-9b32-8b44e1445d32.png">
