### ISSUE TITLE
[FEATURE] Tip - Account for Brave users

### ISSUE THREAD

**Issue by z3xddd** [brave/brave-browser#15541]
Hello Brave team,

I have a suggestion for one feature where Brave users can create an account and save their settings online.

Today this type of configuration is active in browsers such as Firefox and Chrome.

I think it would be interesting, since today if we have a problem with the machine, let's say that we lost the settings made in the brave and also the favorites that we had configured in it.

Do you have this in the backlog?

**Comment by ParthaSarathiChakraborty** [comment]
Yes its quite a good idea. Saving your settings online according to your needs is beneficial when changing the machine.

**Comment by Miyayes** [comment]
This should already be the case with Brave Sync. Use Brave Sync and keep your sync code. If you lose your computer or get a new one, you can put in your sync code on your new machine.

**Comment by z3xddd** [comment]
Can you explane more about this?

**Comment by cahalpin** [comment]
> Can you explane more about this?

https://support.brave.com/hc/en-us/categories/360001330932-Sync should provide the information about what Brave Sync does and how it works.

**Comment by z3xddd** [comment]
Thank you guys!
