### ISSUE TITLE
Migrate BraveViewHostMsg_* legacy IPC messages to mojo

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#15546]
## Description 

These two messages are the [only ones present in the `common/render_messages.h` file](https://github.com/brave/brave-core/blob/master/common/render_messages.h), and also the reason why we define a "random" value for `IPC_MESSAGE_START` in that file, and they could/should be migrated to mojo so let's do that.

Relevant documentation:
https://chromium.googlesource.com/chromium/src/+/master/docs/mojo_ipc_conversion.md

## Miscellaneous Information:

See [Test plan on the associated PR](https://github.com/brave/brave-core/pull/8671) for QA

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8671 with build

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:

1. opened Brave and went to `Settings` > `Shields`
2. clicked to toggle the `Block Scripts` option to `On`
3. loaded `https://coveryourtracks.eff.org` then opened the Brave Shields panel on the address bar
4. confirmed it blocked 3 JavaScript files:
* `coveryourtracks.eff.org/static/dist/jquery.072e2bed.js`
* `coveryourtracks.eff.org/static/dist/tooltip.5795369c.js`
* `coveryourtracks.eff.org/static/front.js`

example | example
---------|---------
<img width="1714" alt="Screen Shot 2021-05-17 at 3 26 26 PM" src="https://user-images.githubusercontent.com/387249/118564345-01fd9100-b725-11eb-9d92-0f5d7f04cc46.png"> | <img width="1714" alt="Screen Shot 2021-05-17 at 3 26 57 PM" src="https://user-images.githubusercontent.com/387249/118564373-03c75480-b725-11eb-87d3-b444baf6b2bd.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.46 x64 Beta build
- Verified no JS is loaded when script blocking is enabled globally

<details>
<summary>With Script blocked </summary>

<img width=350 src=https://user-images.githubusercontent.com/17010094/120471647-dae9c500-c39c-11eb-8c3d-ed4234836862.png> | !<img width=1200 src=https://user-images.githubusercontent.com/17010094/120471371-88a8a400-c39c-11eb-9840-645b01e75ef5.png> 
-- | --

</details>
<details>
<summary>With script unblocked</summary>

<img width=350 src=https://user-images.githubusercontent.com/17010094/120471611-d0c7c680-c39c-11eb-8946-1f0c0d568852.png>| <img width=1200 src=https://user-images.githubusercontent.com/17010094/120471409-96f6c000-c39c-11eb-87b1-39a80bf94118.png>
-- | --

</details>

---------------

Verification passed on Samsung Tab A with Android 10 running 1.26.46 x64 Beta build
- Verified no JS is loaded when script blocking is enabled globally

<details>
<summary>With Script blocked </summary>

<img width=500 src=https://user-images.githubusercontent.com/17010094/120472294-9dd20280-c39d-11eb-8545-fdfa6df04b71.png> | !<img width=1200 src=https://user-images.githubusercontent.com/17010094/120472188-7e3ada00-c39d-11eb-848e-55fe2aaa872a.png> 
-- | --

</details>
<details>
<summary>With script unblocked</summary>

<img width=500 src=https://user-images.githubusercontent.com/17010094/120472275-9874b800-c39d-11eb-849d-327c615abb99.png>| <img width=1200 src=https://user-images.githubusercontent.com/17010094/120472143-711deb00-c39d-11eb-8f9b-c9e659ba5e82.png>
-- | --

</details>
