### ISSUE TITLE
Restore Android command line handler and fix QA prefs first parameter handling

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#15540]
We [implemented](https://github.com/brave/brave-browser/issues/11088) a QA interface to ease browser testing process, but the [default](https://www.chromium.org/developers/how-tos/run-chromium-with-flags) Android Chromium logic to stub command line doesn't work now.

It would be great to restore Chromium logic and keep the QA interface so they can be used together.

Also currently the QA interface doesn't add `_` as a first parameter which leads to the first parameter being ignored. [Here](https://github.com/brave/brave-browser/issues/15523#issuecomment-828231634) are some details.

**Comment by goodov** [comment]
QA here is quite simple. We just need to make sure the QA command line dialog works and the verbose AD logs switch also works without issues. And if we set a parameter via QA dialog, it's applied without prepending `_` first. So `--permission-lifetime-test-seconds=20` should work without issues.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.24.81 x64 build
- Verified command line args work as expected
----------
Verification passed on Samsung Tab A with Android 10 running 1.24.81 x64 build
- Verified command line args work as expected
