### ISSUE TITLE
Add show wallet button to Wallet settings

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#15550]
Add a show wallet button to Wallet settings.
It should be on by default as long as the chrome://flags feature is enabled for the native wallet.
If the wallet button is hidden and the panel is show, the panel should be anchored to the app menu (hamburger menu)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.26.43 Chromium: 91.0.4472.77 (Official Build) beta (64-bit)
-- | --
Revision | `1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}`
OS | Linux

- Verified enabling `brave://flags/#native-brave-wallet` enables the option under `brave://settings/wallet`
- Verified setting is enabled by default and wallet icon is shown on toolbar
- Verified toggle hides/show the wallet icon in toolbar


![image](https://user-images.githubusercontent.com/17010094/120157144-98808680-c1ea-11eb-9738-5011e79ecd39.png)

-------
Verification passed on 

Brave | 1.26.43 Chromium: 91.0.4472.77 (Official Build) beta (64-bit)
-- | --
Revision | `1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}`
OS | Windows 10 OS Version 2009 (Build 19042.985)

- Verified enabling `brave://flags/#native-brave-wallet` enables the option under `brave://settings/wallet`
- Verified setting is enabled by default and wallet icon is shown on toolbar
- Verified toggle hides/show the wallet icon in toolbar

![image](https://user-images.githubusercontent.com/17010094/120157519-03ca5880-c1eb-11eb-926a-25370002d389.png)

---------

Verification passed on 

Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | `1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}`
OS | macOS Version 10.15.7 (Build 19H114)

- Verified enabling `brave://flags/#native-brave-wallet` enables the option under `brave://settings/wallet`
- Verified setting is enabled by default and wallet icon is shown on toolbar
- Verified toggle hides/show the wallet icon in toolbar

![image](https://user-images.githubusercontent.com/17010094/120158219-c87c5980-c1eb-11eb-82d1-ffd207fffa28.png)
