### ISSUE TITLE
Beta/Dev build UI issues on Manjaro/Arch Linux 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#1555]
## Description 

I've been getting reports on Community of Manjaro and Arch Linux users using Brave that encounter a bug in the Shields dropdown:
![image](https://user-images.githubusercontent.com/3299098/46890281-1d8cb680-ce1b-11e8-9f07-6d766125aa58.png)
So far it looks like this is specific to the Shields panel dropdown/extension. The issue has persisted across updates, first report of this was at Beta launch.

## Steps to Reproduce

   1. Install Brave Beta/Dev on Manjaro/Arch Linux machine
   2. Try to open Shields panel

## Actual result:

Shields panel displays incorrectly - no visible text

## Expected result:
Shields panel should display properly.

## Reproduces how often: 

Easily

## Brave version (chrome://version info)

All Beta/Dev builds released so far

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Original posts:
https://community.brave.com/t/text-color-sometimes-renders-white-in-pages-and-always-in-the-brave-button/34687/2
https://community.brave.com/t/brave-shield-ui-bug/33570/3

A couple more screenshots:
![image](https://user-images.githubusercontent.com/3299098/46890498-e8cd2f00-ce1b-11e8-844b-6d85e2fcd67d.png)
![image](https://user-images.githubusercontent.com/3299098/46890544-05696700-ce1c-11e8-8d46-d40582a3a5b5.png)

**Comment by enderger** [comment]
Ill screenshot pastebin when I get home

**Comment by enderger** [comment]
Or it’s pamac-based installation(I use pamac on normal arch, and pamac is the package management gui on Manjaro, so unless another method of install was used on Manjaro to replicate this, it may be the issue)

**Comment by AtjonTV** [comment]
I got the same issues

I only tested beta 0.55.6, beta 0.55.13 and dev 0.56.3 and all have the same issue

Extended OS details:

```
Distribution: elemetary OS
Distribution Version: 0.4.1 Loki
Base Distribution: Ubuntu 16.04.5
Kernel: Linux 4.15.0-36-generic
```

![screenshot from 2018-10-14 10 53 00](https://user-images.githubusercontent.com/24845056/46914530-7c7b3880-cf9f-11e8-8dec-dde7e463f85f.png)

**Comment by enderger** [comment]
Or did you loose network for any reason at any time during the install

**Comment by enderger** [comment]
Could be that a part of the data that is missing from running from pamac installation is missing in your doenload

**Comment by enderger** [comment]
Can someone with a working copy of the latest beta shoot me a checksum, we could compare

**Comment by enderger** [comment]
To the checksum in the aur or one generated on download

Sha256 or another could be good

**Comment by AtjonTV** [comment]
This is the sha256 hash of a freshly downloaded copy:

`e4955451a11aa1c9bd58457bf0926e7a39c184ced017049024bb135e369cd0cd`

This is the file i downloaded: [brave-v0.55.14-linux-x64.zip](https://github.com/brave/brave-browser/releases/download/v0.55.14/brave-v0.55.14-linux-x64.zip)

That version also has the same issues.

**Comment by cdfa** [comment]
Updated to v0.56.7 and there is still no text.

**Comment by simonorono** [comment]
This bug is still present in version 0.56.15 (installed via [this AUR package](https://aur.archlinux.org/packages/brave-bin)).

Tested on Manjaro Linux x86_64
Linux version 4.19.2

![screenshot_20181123_131423](https://user-images.githubusercontent.com/12176276/48955042-5f347500-ef22-11e8-817a-dbcf49cac5ab.png)

**Comment by Brave-Matt** [comment]
+1 from Community, thanksgiving update:
https://community.brave.com/t/brave-shield-ui-bug/33570/48?u=mattches

**Comment by simonhong** [comment]
Rewards popup also has same issue.
The difference between shields and rewards popup is rewards popup displays `i18n: xxx` when translated message isn't available. shields does nothing.
<img width="445" alt="screen shot 2019-02-18 at 15 05 46" src="https://user-images.githubusercontent.com/6786187/52932257-7ef8ff00-3392-11e9-9ef1-48d9bcd59e01.png">

`i18n: xxxx` is displayed in rewards because `chrome.i18n.getMessage()` returns null.
```
export const getMessage = (message: string, substitutions?: string[]): string => {
  if (chrome.i18n) {
    let translated = chrome.i18n.getMessage(message, substitutions)

    if (translated) {
      return translated
    } else {
      return `i18n: ${message}`
    }
  }

  return `i18n missing: ${message}`
}
```

**Comment by simonhong** [comment]
Related docs: https://developer.chrome.com/extensions/i18n

**Comment by simonhong** [comment]
Found the reason. Zip file didn't include extension's locale files.
They are in `out/Release/resources/`.

**Comment by srirambv** [comment]
Verification passed on 

![image](https://user-images.githubusercontent.com/17010094/56216336-3fb3fb00-602f-11e9-9508-93a679a1ec7b.png)


Note: The package I built kept failing so used the AUR package available for beta to test
