### ISSUE TITLE
Need to define the minimum width and margin for the Rewards pages for the desktop

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#1556]
## Description 

Feature components of Brave Rewards-- Ads, Contributions, Tips module, are responsive indefinitely that the content display gets broken below a certain window size.
![screen shot 2018-10-12 at 2 15 39 pm](https://user-images.githubusercontent.com/4369856/46895776-ad882b80-ce2e-11e8-9f11-6d5116c57a1f.png)

Please define the minimum width to 1024, which will preserve the content as well as keeping the margins for the page.
 
![image](https://user-images.githubusercontent.com/4369856/46895827-f93ad500-ce2e-11e8-9af9-43b1b7ef9c04.png)

## Steps to Reproduce

   1.  
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows
