### ISSUE TITLE
Allow users to rotate keys

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15568]
Add ability to rotate self key via ipfs key rotate on IPNS keys management page in settings as a privacy feature to "Rotate Peer Identity (PeerID)`
ipfs key rotate -o self.old.FOO may improve UX a bit (FOO could be lat 4 characters of old key)

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.28.46 Chromium: 92.0.4515.70 (Official Build) nightly (x86_64)
-- | --
Revision | 2df01a82398e62190b2aae01aaad7ca3d47aba01-refs/branch-heads/4515@{#923}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. clean profile
2. launched Brave
3. loaded `ipns://brantly.eth`
4. clicked `Use a local node`
5. went to `brave://ipfs-internals/`
6. clicked on `Manage PeerID and IPNS Keys`
7. confirmed I was taken to `brave://settings/ipfs/keys`
8. clicked on the rotate icon to the right of the `self` key
9. entered `rotatedKey` and clicked `Rotate`
10. confirmed `self` key regenerated with a new value
11. confirmed `rotatedKey` appeared on manual window reload
12. confirmed the `rotatedKey` and `self` appeared on the `IPFS > Share Local File Using IPFS` and `IPFS > Share Local Folder Using IPFS` flyout menus


example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2021-07-01 at 4 51 08 PM" src="https://user-images.githubusercontent.com/387249/124201689-8154e300-da8d-11eb-87d5-9345e5bdd1f5.png"> | <img width="1312" alt="Screen Shot 2021-07-01 at 4 51 34 PM" src="https://user-images.githubusercontent.com/387249/124201690-81ed7980-da8d-11eb-8bc6-ff770884b51f.png"> | <img width="1591" alt="Screen Shot 2021-07-01 at 4 55 15 PM" src="https://user-images.githubusercontent.com/387249/124201691-81ed7980-da8d-11eb-93a8-16135e646e6d.png">
