### ISSUE TITLE
Allow users to add IPFS peer servers

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15567]
Allow users to enter the peers to the config 
https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#peering

**Comment by lidel** [comment]
When it comes to UX, you may have the best luck with a single input  that takes a string and extracts `ID` and `Addrs` from it.

Usually, user will just copy a single address in form of (could be any of those):
-  `/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ` 
- `/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ`
- `QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ` and adds it to peers.

To keep things simple:
- split at `/p2p/` (if present), and put the first part in `Addrs` and the second one in `ID`. 
- if no `/p2p` is present, just assume its `ID`.

**Comment by spylogsster** [comment]
for compatibility reasons decided to add 1 as a valid prefix if it is preceded with /p2p/ in order to validate PeerIDs like 
`/ip4/46.21.210.45/udp/14406/quic/p2p/12D3KooWBdmLJjhpgJ9KZgLM3f894ff9xyBfPvPjFNn7MKJpyrC2`

**Comment by stephendonner** [comment]
@spylogsster mind adding a step-by-step testplan with instructions for a two-machine setup (running the same build, I presume) with the 2nd machine's ports changed appropriately, to test?

I tried to get this working by changing the port via the `Settings` page available after clicking `My Node` in `brave://ipfs-internals`, but it didn't seem to stick, even after restarting IPFS, so wasn't sure how to test this.

<img width="1515" alt="Screen Shot 2021-06-07 at 6 21 24 PM" src="https://user-images.githubusercontent.com/387249/121107732-4e387000-c7bd-11eb-985d-4e6027e21b5f.png">

**Comment by spylogsster** [comment]
@stephendonner added steps, please disable "Method to resolve Unstoppable Domains" and "Method to resolve Ethereum Name Service (ENS)" and "Redirect IPFS resources to the configured IPFS gateway" options in settings, while https://github.com/brave/brave-core/pull/9031/files is not merged,  then node status page will be loaded successfully

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.27.78 Chromium: 91.0.4472.114 (Official Build) beta (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)

Pre-requisite (to make it easier):
`machine1`: macbook pro (running `1.27.x` with `Gateway` port `48083`)
`machine2`: Windows desktop (running `1.28.x`, with `Gateway` port `48081`)

**Steps** (do 1-4 on both `machine1` and `machine2`)
1. clean profile
2. load `ipns://brantly.eth`
3. click on `Use a local node`
4. load `brave://ipfs-internals`
5. note/copy the `Peer ID` on `machine2`
6. note the `Gateway` path/port
7. on `machine1`, go to `brave://settings/ipfs/peers`
8. click `Add`
9. enter `/ip4/127.0.0.1/tcp/48081/quic/p2p/12D3KooWQt6ndYjevTTtgVFwKUeZYaU5aFtnogrLKgjvgZiRBT3m`
10. click `Submit`
11. restart both IPFS nodes
12. load `brave://ipfs-internals`
13. click on `My Node`
14. click on `Peers`
15. confirm on `machine1` you see an entry for `Local Network` with the matching `Peer ID` of the one you entered from `machine2`, above (in this case, it's `12D3KooWQt6ndYjevTTtgVFwKUeZYaU5aFtnogrLKgjvgZiRBT3m` which is cropped in the UI as `123D...BT3m`
16. confirm on `machine1` you see an entry for a`bootstrap node` under the `Notes` column; this `Peer ID` comes from the list in the `Settings` of IPFS, found from clicking `My Node` on`brave://ipfs-internals`.  In my screenshots, it's `QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ` represented as `QmaC...uvuJ`.

machine1 - `brave://settings/ipfs/peers` | machine1 - My Node |  machine1 - Peers | bootstrap node from Settings
---------------------|----------------|--------------------------------------------|-------------------------------
<img width="1596" alt="Screen Shot 2021-06-24 at 1 11 39 PM" src="https://user-images.githubusercontent.com/387249/123334176-906ceb80-d4f7-11eb-99a0-57e4762b97cb.png"> |  <img width="1743" alt="Screen Shot 2021-06-24 at 2 19 41 PM" src="https://user-images.githubusercontent.com/387249/123333958-408e2480-d4f7-11eb-9edc-0e5e47b61038.png"> | <img width="1596" alt="Screen Shot 2021-06-24 at 1 09 56 PM" src="https://user-images.githubusercontent.com/387249/123333978-484dc900-d4f7-11eb-94d6-8964d04b691f.png"> | <img width="1253" alt="Screen Shot 2021-06-24 at 3 00 47 PM" src="https://user-images.githubusercontent.com/387249/123338226-4d157b80-d4fd-11eb-8fdc-e68c67515c18.png">


machine2 - My Node | machine2 - Peers | 
-----------------------|-------------------
![windows-node-status](https://user-images.githubusercontent.com/387249/123335265-10e01c00-d4f9-11eb-96b1-d2fbfa027fdd.png) | ![windows-peers](https://user-images.githubusercontent.com/387249/123335268-1178b280-d4f9-11eb-9698-18577b517fc8.png)
