### ISSUE TITLE
Middle click/scroll function doesn't work with Linux version

### ISSUE THREAD

**Issue by NOVATechnocrat** [brave/brave-browser#15576]
Description:

- The middle button does not activate scrolling which is present in other browsers including Chromium, Firefox, Chrome etc.

To reproduce:

- Install Linux
- Install Brave
- Middle click

Expected result:

- When I use the middle scroll wheel key, expected behavior is engaging the scroll function so I may click and drag upward or downward to scroll. This is not happening and I'm not seeing the customary scroll icon either.

Reproduces how often: 

- Every time

Version:

- Brave version (brave://version info)
- Release Notes V1.23.75 (Apr 28, 2021)

Other Additional Information:

Linux Pop OS 20,10

uname -a                                                                                               127 ↵
Linux deadbeefcafe 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC  x86_64 x86_64 x86_64 GNU/Linux

**Comment by NOVATechnocrat** [comment]
Actually, I don't see that behavior on Chrome. Middle button doesn't work there either. :L

**Comment by ryanbr** [comment]
The middle cllick options could be configurable in the X11/mouse settings, have you look there? @NOVATechnocrat

**Comment by NOVATechnocrat** [comment]
Apparently this function is only available on Firefox. It's called autoscroll and required a Chrome extension to enable it. This scroll function by the extension in Brave is choppy. I'd love native integration. Does no one else use this?

More about Autoscroll:

https://askubuntu.com/questions/908/firefox-middle-mouse-button-scroll

Extension:

https://chrome.google.com/webstore/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan/related

**Comment by N1vBruno** [comment]
There is a flag for this:

`--enable-blink-features=MiddleClickAutoscroll`

It's working fine for me. Could this be turned into an option config (especially removing the warning)?

[Source](https://askubuntu.com/a/1419189)

**Comment by NicolasGoeddel** [comment]
> There is a flag for this:
> 
> `--enable-blink-features=MiddleClickAutoscroll`
> 
> It's working fine for me. Could this be turned into an option config (especially removing the warning)?
> 
> [Source](https://askubuntu.com/a/1419189)

Wow, thank you. I just installed Brave and immediately missed the middle click auto scroll feature. I don't understand that annoying warning when using this command line flag but it seems to work flawlessly.

By the way: There are a lot of auto closed community posts about this missing feature:
- https://community.brave.com/t/i-want-middle-click-and-drag-to-scroll/220233
- https://community.brave.com/t/how-to-enable-scrolling-when-clicking-the-mouse-wheel-in-brave/84161
- https://community.brave.com/t/why-cant-i-scroll-by-pressing-the-mouse-wheel-at-linux/441257
- ...

So please, we need this!

**Comment by RobotoSkunk** [comment]
I think this would be a really good feature for Brave, I vote to implement this as an option in configuration!

**Comment by agowa** [comment]
If brave is ran with the `--enable-blink-features=MiddleClickAutoscroll` commandline argument the middle click scroll works. It works, even though brave will show a warning about it being unsupported on launch...

**Comment by Philippe734** [comment]
Thanks for the tips to use the commandline argument. I guess, before 2035 Brave will enable this feature.

**Comment by sangwoo108** [comment]
FYI, this issue is closed as duplicated. But the original issue is resolved. We added "MiddelButtonAutoscroll" option to `brave://flags`

**Comment by agowa** [comment]
@sangwoo108 Is it planned to add this option to the normal options page in the future, or is a separate ticket needed for that?

Basically enabling that feature will cause brave to have the same behavior on Linux as it already has on Windows. Therefore it probably should be a bit more accessible to normal users than just `brave://flags`. Also other browser like e.g. firefox have it in the UI, so brave would also not be the first one to show such an option to show a settings option for enabling the Middle Button Autoscroll also on Linux.

The main issue for why it is not enabled by default is that it overlaps with another function. But that is hardly a reason to keep it out of normal users and the regular settings page. What do you think?

**Comment by sangwoo108** [comment]
Hi @agowa ! Yes it is. As for now, we are checking if there is no more regression by enabling it. So your feedback will be really helpful. https://github.com/brave/brave-browser/issues/959#issuecomment-1922791478

**Comment by Lamby777** [comment]
> FYI, this issue is closed as duplicated. But the original issue is resolved. We added "MiddelButtonAutoscroll" option to `brave://flags`

It's not there... I'm on `v1.62.156`, updated last night. Is it only in the beta channel rn?

**Comment by sangwoo108** [comment]
> It's not there... I'm on v1.62.156, updated last night. Is it only in the beta channel rn?

It should be only in the Nightly channel.

**Comment by Lamby777** [comment]
> > It's not there... I'm on v1.62.156, updated last night. Is it only in the beta channel rn?
> 
> It should be only in the Nightly channel.

yea mb i saw the milestone thing above your comment like immediately after posting that which is why i deleted it but ig github notifications are what they are

**Comment by lukaskretzschmer** [comment]
OMG, can't wait for the official release of this!

**Comment by bsclifton** [comment]
@lukaskretzschmer official release will be 1.64 and that is planned for March 19th 😄 It's now on Beta

**Comment by ghostersk** [comment]
Hello Everyone, I have just checked it again today, and now it is available in the chrome://flags
Previously you had to put it to the shortcut, but now it can be neabled in flags and no more popups on brave start.
Also there is universal Dark mode for all sites... AMAZING!!!!!!!!
![Screenshot_20240422_055729](https://github.com/brave/brave-browser/assets/68815071/80808b3d-4ec7-48f0-bf85-4aa560066678)

**Comment by mat926** [comment]
I was having the same issue as well, and the feature flag worked for me. Why was it disabled by default?
