### ISSUE TITLE
Investigate whether Easylist Cookies be a default list

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#15575]
## Description 
Vivaldi is blocking consent/cookie/gdpr warning by default, should we also follow suit and block consent messages by default

https://www.forbes.com/sites/barrycollins/2021/04/29/vivaldi-browser-kills-irritating-cookie-pop-ups/?utm_term=Carrie

Currently we have Easylist Cookie as an optional list via `brave://adblock` Should we follow Vivaldi by making it default. 

### Possible Issues (Applicable to Vivaldi also)

- It won't prevent every consent messages (google, youtube etc), 
- May cause some false positives if the consent message disables the scrollbar (can be worked around)
- Any legal/gdpr issues? or complaints by businesses wanting to display the consent messages.
- If a user wants to disable the cookie filter, won't be able too.

**Comment by Yuki2718** [comment]
> * May cause some false positives if the consent message disables the scrollbar (can be worked around)

Not only scrolling issues. It's not so rare blocking cookie manager plugins such as `cookiebot.com` or `cookielaw.org` breaks a page, or a generic cosmetic filter hides other contents.

**Comment by ryanbr** [comment]
In cases like that it can be worked around, we have many tools available to avoid issues @Yuki2718  (exceptions, a snippet or cosmetic)

**Comment by Yuki2718** [comment]
That's a perspective from filter author, not from user. Search on Twitter and you'll find single FP can be enough for a user to switch blocker/browser, and also majority of user never report issues. Cookie consents are not as annoying as ads nor as privacy-invasive as tracker.

**Comment by ryanbr** [comment]
I'll close this ticket, we'll relook at implementing this later, mature the cookie list a bit more
