### ISSUE TITLE
Windows fails to recognize Brave+IPFS

### ISSUE THREAD

**Issue by darkwater4213** [brave/brave-browser#15574]
## Description 
Windows doesn't recognize Brave as an IPFS protocol handler

## Steps to Reproduce

   1.  On Windows 10, go to Settings > Apps > Default Apps
   2. At the bottom, click on "Set defaults by App"
   3. Click on Brave, then on Manage
   4. Scroll down. When you attempt to add Brave as an IPFS handler, it doesn't show up.
## Expected result:
Windows recognizes Brave as an IPFS handler and allows you to open `.ipfs` files in Brave
## Actual result:
Windows doesn't recognize Brave

## Brave version (I tried to make it look nice but couldn't sorry about that)
| Brave | 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit) |
| Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348} |
| OS | Windows 10 OS Version 2004 (Build 19041.928) |
| JavaScript | V8 9.0.257.23 |
| User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 |
Command Line | "C:\Users\darkw\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,AutoupgradeMixedContent,SafetyTip,WinrtGeolocationImplementation,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,LegacyTLSEnforced --disable-features=AutofillEnableAccountWalletStorage,TextFragmentAnchor,AutofillServerCommunication,SharingQRCodeGenerator,DirectSockets,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,TabHoverCards,IdleDetection,SafeBrowsingEnhancedProtectionMessageInInterstitials,NotificationTriggers,WebOTP,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection,LangClientHintHeader,NetworkTimeServiceQuerying,BraveDomainBlock --flag-switches-begin --flag-switches-end
Executable Path	C:\Users\darkw\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\darkw\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	fd27979-1108a9da
7146a73c-3f4a17df

**Comment by lidel** [comment]
We don't have `.ipfs` file extension, we do have `ipfs://` URI scheme support.

@darkwater4213  why you expect `.ipfs` file extension means anything?  What was your expectation?

AFAIK it was just an old idea proposed in https://github.com/ipfs/ipfs-companion/issues/641, but was never  implemented because `https://dweb.link/ipfs/{cid}` is a better way of sharing IPFS links.

**Comment by darkwater4213** [comment]
Oh, so it was an idea for a file that never got implemented for some reason? Or am I just confused?

**Comment by lidel** [comment]
@darkwater4213  This was never a thing. Where did you get this idea from? :)

**Comment by darkwater4213** [comment]
> @darkwater4213 This was never a thing, never implemented. Where did you get this idea from? :)

To be honest, I saw the letters `ipfs` and jumped to (wrong) conclusions (haha). Sorry!
