### ISSUE TITLE
incorrectly seeing BAP in some places

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15581]
## Description 

In some places BAP is still being shown, should be BAT.

## Steps to Reproduce

   1. Clean profile 1.24.x, Japan region and language, staging env
   2. Enable bF in flags, relaunch
   3. Enable Rewards
   4. Look at Rewards UI. Some places BAT is shown, others BAP is shown.

## Actual result:

Places where BAP has been seen so far:
- Rewards panel wallet balance
- Monthly tip amount drop down on rewards panel

Example | Example
----- | -----
<img width="1309" alt="BAP1" src="https://user-images.githubusercontent.com/28145373/116698452-67fec000-a992-11eb-963d-31836615024f.png"> | <img width="398" alt="BAP2" src="https://user-images.githubusercontent.com/28145373/116698454-692fed00-a992-11eb-8214-e46999773969.png">

## Expected result:
 BAT in all places

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.24.81 Chromium: 90.0.4430.93 (Official Build) （x86_64）
-- | --
変更履歴 | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS バージョン10.15.7（ビルド19H1030）

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a 1.23.x, yes 1.24.x
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the nightly channel? no, not on 1.26.x (thanks @GeetaSarvadnya for checking!)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @mkarolin

**Comment by GeetaSarvadnya** [comment]
Reproducible in `Windows 10 x64 - 1.24.81`
![image](https://user-images.githubusercontent.com/38657976/116699163-e1be9a00-a9e2-11eb-87ca-12f634a7f3f9.png)

**Comment by LaurenWags** [comment]
Should be fixed by https://github.com/brave/brave-core/pull/8681

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.24.82 Chromium: 90.0.4430.93 (Official Build) （x86_64）
-- | --
変更履歴 | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS バージョン10.15.7（ビルド19H1030）
```

Verified STR from description

<details>
<summary>Screenshots</summary>

Example | Example | Example
----- | ----- | -----
<img width="398" alt="1" src="https://user-images.githubusercontent.com/28145373/116915027-80ccd700-ac19-11eb-90e2-44c2703ddc89.png"> | <img width="395" alt="2" src="https://user-images.githubusercontent.com/28145373/116915030-81656d80-ac19-11eb-9cf7-94f2740677d3.png"> | <img width="398" alt="3" src="https://user-images.githubusercontent.com/28145373/116915034-82969a80-ac19-11eb-9b27-87c81f8b0715.png">

</details>
