### ISSUE TITLE
I tried installing SQL on my Ubuntu software and it messd up my operating system, the maximise, minimize and close is visible shows but the signs (x, -) isnt showing. Also, I am unable to open my files. anytime i click on files, it just blinks and doesnt open. please help. I need to access my files for my project.

### ISSUE THREAD

**Issue by Lotachi-ekwunife** [brave/brave-browser#15585]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Brave-Matt** [comment]
@Lotachi-ekwunife,
Thank you for reaching out to us. I would like to to assist you with this issue, but it would be best if we move the conversation to our support forum so we can best assist you. We typically use Github for bigger, less granular/individual issues. 

Please post you issue on our Community forum and tag me directly (@mattches) and I'd be more than happy to assist. Thank you.
