### ISSUE TITLE
`brave://memories` link in `brave://about`doesn't work

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15582]
## Description 

`brave://memories` link in `brave://about`doesn't work

## Steps to Reproduce

   1.  load `brave://about/`
   2. enable the feature flag via `brave://flags` 
   3. click on `chrome://memories`, which redirects internally to `brave://memories/`

## Actual result:

Broken internal link

example | example | example
---------|---------|----------
<img width="1116" alt="Screen Shot 2021-04-30 at 8 19 06 AM" src="https://user-images.githubusercontent.com/387249/116716872-1e5fa680-a98d-11eb-957a-fed6fce4ccbe.png"> | <img width="1537" alt="Screen Shot 2021-04-30 at 11 13 32 AM" src="https://user-images.githubusercontent.com/387249/116737013-87ebaf00-a9a5-11eb-9dbb-0c2270028eb1.png"> | <img width="1116" alt="Screen Shot 2021-04-30 at 8 18 38 AM" src="https://user-images.githubusercontent.com/387249/116716863-1b64b600-a98d-11eb-8338-840968885850.png">

## Expected result:

Working link, or for it to be removed

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.24.81 Chromium: 90.0.4430.93 (Official Build) (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3 (Build 20E232)

**Comment by bsclifton** [comment]
@stephendonner can you try enabling brave://flags/#memories and then seeing if it works?

More info here:
https://www.ghacks.net/2021/04/24/google-is-working-on-a-new-browsing-history-interface-called-memories-in-chrome/

**Comment by stephendonner** [comment]
@bsclifton shortly after @rebron told me it requires a flag, in Slack, I amended the steps and screenshots here to reflect that I re-tested with that feature flag enabled.  Confirming that it still isn't displaying anything for me with 

Brave | 1.26.6 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3.1 (Build 20E241)

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.56 Chromium: 93.0.4577.58 (Official Build) beta (x86_64)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:
1. new profile
2. launched Brave
3. opened `brave://about`
4. looked for `brave://memories`

Confirmed that `brave://memories` is now removed from `brave://about`; however it's still present in `brave://flags`

<img width="1774" alt="Screen Shot 2021-08-30 at 2 33 29 PM" src="https://user-images.githubusercontent.com/387249/131408978-80ac1bab-e944-441d-896d-1b636c2f71f6.png">

@goodov should we also remove the two memories items in brave://flags, in a separate issue?

example | example | example
---------|----------|----------
<img width="1774" alt="Screen Shot 2021-08-30 at 2 34 06 PM" src="https://user-images.githubusercontent.com/387249/131409288-16be84ae-2054-4324-8b64-35a44bca8657.png"> | <img width="1774" alt="Screen Shot 2021-08-30 at 2 37 24 PM" src="https://user-images.githubusercontent.com/387249/131409293-17e9e538-3fdb-448a-818b-3a3fe64090ee.png"> | <img width="1774" alt="Screen Shot 2021-08-30 at 2 37 32 PM" src="https://user-images.githubusercontent.com/387249/131409295-3eeb71ae-1e9e-493e-ade9-79439d94ccce.png">

**Comment by goodov** [comment]
> @goodov should we also remove the two memories items in brave://flags, in a separate issue?

why not, let's clean up this.
