### ISSUE TITLE
Add Sign in with Apple to sync.

### ISSUE THREAD

**Issue by Dr-Sauce** [brave/brave-browser#15589]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:
![image](https://user-images.githubusercontent.com/82555878/116801431-fd41b600-ab44-11eb-9382-395587b1eecb.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing. Apple IDs can already be stored and synced via the existing password manager and sync service.
