### ISSUE TITLE
Add Reading List in Brave

### ISSUE THREAD

**Issue by phoogm** [brave/brave-browser#15583]
## Description 
As a user I would like to see the option in the Settings / Appearance section to enable or disable the Reading List option (brave://flags - Reading list) so I can save web page articles (offline) without the need to save it as a bookmark and track read versus unread status.

## Steps to Reproduce
   1. Go to brave://flags
   2. Enable Reading List
   3. Observe the Reading List button to appear in the bookmarks bar behind a separator
   4. Currently the description mentions that clicking the bookmarks icon would work but as far as i can see only right-clicking on the tab would allow to add a page to the Reading List.

## Actual result:

<img width="460" alt="Brave Reading List" src="https://user-images.githubusercontent.com/56597375/116730511-df5f3e80-a9e8-11eb-8e6c-53e842c4f8f6.png">
<img width="430" alt="Reading list tab" src="https://user-images.githubusercontent.com/56597375/116733362-4b8f7180-a9ec-11eb-8fb8-f5802202ca32.png">

## Expected result:
User can enable or disable the Reading List option in the Settings / Appearance section
Reading list follows the Brave styling in stead of the current Chromium styling.
Description accurately states that the user should right-click on a tab to add the current page to the reading list.

<img width="681" alt="Reading List Proposal" src="https://user-images.githubusercontent.com/56597375/116731366-e3d82700-a9e9-11eb-8c86-28e41b8df334.png">

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.23.75 Chromium: 90.0.4430.93 (Official Build) (arm64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3 (Build 20E232)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Potentially a feature to enable or add to the mobile versions as well.

Thanks much for looking into, best regards.

**Comment by rebron** [comment]
cc: @karenkliu @bradleyrichter Thoughts?

**Comment by bsclifton** [comment]
Closing as this is now implemented 😄 Kudos to @petemill for integrating this with https://github.com/brave/brave-core/pull/13769
