### ISSUE TITLE
Getting the wrong RGB values from canvas pixel data

### ISSUE THREAD

**Issue by ivanbacher** [brave/brave-browser#15580]
## Description 
Drawing shapes on HTML5 canvas. Assign each shape a different RGB color. Get pixel data using `ctx.getImageData()`. RGB values do not correspond to the ones assigned to the shapes.

Please see stack-overflow post: https://stackoverflow.com/questions/67331124/getting-the-wrong-rgb-values-from-canvas-pixel-data

## Steps to Reproduce
Please see stack-overflow post: https://stackoverflow.com/questions/67331124/getting-the-wrong-rgb-values-from-canvas-pixel-data

## Actual result:
RGB values of pixels do not correspond to values when drawing shapes.

## Expected result:
RGB values should be the same.

## Brave version (brave://version info)
Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (x86_64)

**Comment by rebron** [comment]
Closing. This works as expected with our default fingerprinting options which are set to blocked (standard). If you set your shields setting to allow all fingerprinting you should have matching RGB values.
