### ISSUE TITLE
Implement more sidebar show options - On mouseover and On click 

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15592]
This is subissue of https://github.com/brave/brave-browser/issues/14980
Currently, only `Always` and `Never` options are supported from `Show Sidebar`.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:
1. enabled `Sidebar` via its feature flag in `brave://flags`
2. opened a new-tab page
3. moused-over to the left margin, and clicked on the sidebar icon, to display the sidebar
4. context-clicked the sidebar menu, and chose `On mouseover`
5. moused-over to the left margin, and confirmed the sidebar displayed
6. moused away from the sidebar, and confirmed it became hidden again
7. also confirmed that selecting an option such as Brave Together or History from the sidebar popped it open, until I explicitly closed it again with a click on its icon


![sidebar-options](https://user-images.githubusercontent.com/387249/118567948-9e2a9680-b72b-11eb-8aee-4dcd5efd40d0.gif)

**Comment by simonhong** [comment]
`On click` option is not valid anymore.
