### ISSUE TITLE
Enable PKP in brave-core

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#156]
Navigate to: https://pinning-test.badssl.com/

<img width="1163" alt="screen shot 2018-04-10 at 11 05 00 am" src="https://user-images.githubusercontent.com/1903815/38575008-26f0fe1e-3caf-11e8-85b1-4051d1944b69.png">

**Comment by bbondy** [comment]
@diracdeltas is HPKP still a thing?
https://raymii.org/s/blog/Chrome_68_is_deprecating_HPKP.html

**Comment by diracdeltas** [comment]
@bbondy this issue is specifically for static PKP which is very much still a thing (but dynamic HPKP via the HTTP header is deprecated_

**Comment by jumde** [comment]
Dupe: https://github.com/brave/brave-browser/issues/767
