### ISSUE TITLE
Do not set AC pref to off for Android users in Japan

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15601]
Follow-up to https://github.com/brave/brave-browser/issues/15444

https://github.com/brave/brave-core/pull/8618 added a state migration which set the AC enabled flag to `false` for all Japan-region users. This migration should only be applied to desktop, and not Android.

**Comment by LaurenWags** [comment]
Per discussion with @zenparsing this revert was also applied to desktop in the upgrade case, but the revert has not yet been applied to desktop clean profile case. Added `OS/Desktop` label to reflect this.
