### ISSUE TITLE
New Ads Auth Refresh Flow

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#15600]
https://github.com/brave/internal/issues/769

**Comment by LaurenWags** [comment]
@brave/legacy_qa  before starting work on this ping @kjozwiak to discuss test plan

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build:

```
Brave | 1.31.86 Chromium: 95.0.4638.50 (Official Build) (64-bit)
-- | --
Revision | 3e9db37693d0cf8e31a89fbcf50401ae91125cef-refs/branch-heads/4638@{#816}
OS | Windows 11 Version 21H2 (Build 22000.258)
```

Verification notes can be found via https://github.com/brave/internal/issues/769#issuecomment-946388708
