### ISSUE TITLE
Crypto.com widget displays wrong price

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15605]
User reported that VeChain price is invalid ($0).
![image](https://user-images.githubusercontent.com/6786187/116949789-2df92b00-acbe-11eb-8b08-bee95db3b25e.png)
https://www.reddit.com/r/brave_browser/comments/n3w85h/vechain_price_always_reads_000_on_dashboard/

**Comment by srirambv** [comment]
Requires a new Beta Build for testing as the PR merged after the last beta build

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.25.62 Chromium: 90.0.4430.212&nbsp;(Official Build) beta (64-bit)
-- | --
Revision | `e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}`
OS | Linux

- Verified token value is shown on both list and details view

![image](https://user-images.githubusercontent.com/17010094/118631857-cf58a480-b7c7-11eb-9bb3-4dc28551468c.png) | ![image](https://user-images.githubusercontent.com/17010094/118631823-c5cf3c80-b7c7-11eb-90d6-a007d8d1ff1a.png)
-- | --

---------
Verification passed on 

Brave | 1.25.62 Chromium: 90.0.4430.212&nbsp;(Official Build) beta (64-bit)
-- | --
Revision | `e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}`
OS | Windows 10 OS Version 2009 (Build 19042.985)

- Verified token value is shown on both list and details view

![image](https://user-images.githubusercontent.com/17010094/118630834-d03d0680-b7c6-11eb-8b14-ae7aa8ca650d.png) | ![image](https://user-images.githubusercontent.com/17010094/118630729-b7345580-b7c6-11eb-8981-424388fc880d.png)
-- | --

---------
Verification passed on 

Brave | 1.25.62 Chromium: 90.0.4430.212&nbsp;(Official Build) beta (x86_64)
-- | --
Revision | `e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}`
OS | macOS Version 10.15.7 (Build 19H114)

- Verified token value is shown on both list and details view

![image](https://user-images.githubusercontent.com/17010094/118631316-45a8d700-b7c7-11eb-839e-d8ab1ab856bd.png) | ![image](https://user-images.githubusercontent.com/17010094/118631253-36298e00-b7c7-11eb-95ac-a150407574a4.png)
-- | --
