### ISSUE TITLE
Flickering while watching videos.

### ISSUE THREAD

**Issue by EfraMP** [brave/brave-browser#15604]
## Description 

While watching videos, they start to flicker randomly. It is more common when they are on full screen. I already checked my GPU drivers and everything seems normal, but I may be wrong. I also tried to reproduce the issue in other Chromium-based browsers, like Edge or Chrome itself, but the issue is only in Brave.

## Steps to Reproduce

   1.  Open a video webpage. (In my example I used  [this one](https://www.youtube.com/watch?v=ohpHY8m54Hc))
   2.  If it's necesary, enable full screen.

## Actual result:

The video starts to flicker. [Here](https://imgur.com/a/bAKjVlc) is a good example.

## Expected result:

The videos shouldn't flicker.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave: 1.23.75 Chromium: 90.0.4430.93 (Build oficial) (64 bits)
Revision:  4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS: Windows 10 OS Version 2009 (Build 19042.964)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

I don't use other channels.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?   No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?    No

## Miscellaneous Information:

Brave is using a NVIDIA GeForce GTX 1650 GPU.

**Comment by ryanbr** [comment]
hey @EfraMP  Couple of things we can try,

- Clearing cookies/cache for youtube, and test in private window.
- Also disabling GPU Acceleration via `brave://settings/system`
- Updating GPU drivers

**Comment by EfraMP** [comment]
I disabled the harware acceleration and it worked! Thanks!
