### ISSUE TITLE
Autocomplete does not default to brave://xyz as URL

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#1560]
Whilst brave://xyz URLs work (they redirect to chrome://xyz), the default action in the LocationBar on typing such a url results in a search query.

A scheme classifier was implemented in https://github.com/brave/brave-core/pull/164 which specifies brave:// as a URL, but it is not loaded as part of the actual chrome omnibox UI.

Test plan:
1. Type brave://settings in LocationBar
2. Press enter
Observed: Sent to a search URL with "brave://settings" as query
Expected: Sent to `brave://settings` URL (right now this displays `chrome://settings` which is ok, but will change as of https://github.com/brave/brave-browser/issues/1458)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified steps from description
