### ISSUE TITLE
Change permissions lifetime UI to make relationship between "block" and the dropdown clearer

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#15603]
The current permissions dialog is unclear about how the "block" button interacts with the times in the dropdown.

@karenkliu suggested one of the attached, with both look 👍 to me

![image](https://user-images.githubusercontent.com/76526/116947710-16309100-ac43-11eb-856f-7476266c871e.png)
![image (1)](https://user-images.githubusercontent.com/76526/116947712-16c92780-ac43-11eb-99da-edf45aa57ef6.png)

**Note** That while updating the designs, please also make sure the "until i close this page" text is changed to "until i close this site”/

Related feedback and suggestion from @bridiver https://github.com/brave/brave-browser/issues/14127#issuecomment-831572712

> @karenkliu I got this permission prompt for the first time and was really confused by it. I showed it to @bbondy and he assumed "Forever" was a mistake. I definitely don't feel like it's clear that the dropdown only applies to "Allow", but until @pes10k pointed me to this ticket (I didn't find anything in the original #14126) I had no idea if the @bbondy was right or if "Forever" was correct and the UI was just confusing.

**Comment by kjozwiak** [comment]
Moving this back into the `1.26.x` milestone as this isn't `release/blocking` and landed in `master` only which is `1.26.x`. Once this is uplifted via https://github.com/brave/brave-core/pull/8733, it will be moved into the `1.25.x` milestone.

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on Samsung Tab A with Android 10 running 1.25.57 x64 Beta Build</summary>
<br>

- Verified `"until i close this page"` text is changed to `"until i close this site”`

<details>
<summary>Allow Tests</summary>
<h4>5 seconds</h4>

- Verified passing command line args `--permission-lifetime-test-seconds=5` adds an entry to the permission popup
- Verified selecting 5 seconds and selecting Allow sets the permission for the page
- Verified clicking site info shows permission that is set to allow
- Verified after 5 secs the permission is removed and not showed under site details

![image](https://user-images.githubusercontent.com/17010094/117949599-30850180-b30a-11eb-8ced-d12f3c9df02d.png) | ![image](https://user-images.githubusercontent.com/17010094/117949731-55797480-b30a-11eb-8030-5ad874629b6f.png)
-- | --

<h4>until I close this site</h4>

- Verified selecting location and `until I close this site` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified opening a new tab and loading the same site still shows the permission set to allow 
- Verified closing the second tab from pervious step doesn't reset permission on the first tab
- Verified when all tabs for the site is closed and reopened in a new tab prompts for permission again
 
<h4>for 24 hours </h4>

- Verified selecting location and `for 24 hours` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified moving device time ahead by 23 hrs and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 25 hrs and loading the page again and selecting location does prompt for permission
 

<h4>for 1 week</h4>

- Verified selecting location and `for 1 week` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified moving device time ahead by 6 days and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 8 days and loading the page again and selecting location does prompt for permission

<h4>forever</h4>

- Verified selecting location and `forever` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified moving device time ahead by 2 weeks and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 2 months and loading the page again and selecting location doesn'the prompt for permission

 
</details>

<details>
<summary>Block Tests</summary>
<h4>5 seconds</h4>

- Verified passing command line args `--permission-lifetime-test-seconds=5` adds an entry to the permission popup
- Verified selecting 5 seconds and selecting `Block` sets the permission for the page
- Verified clicking site info shows permission that is set to block
- Verified after 5 secs the permission is removed and not showed under site details

![image](https://user-images.githubusercontent.com/17010094/117949561-26630300-b30a-11eb-9938-871ef8800a10.png) | ![image](https://user-images.githubusercontent.com/17010094/117949526-1e0ac800-b30a-11eb-94e9-8d75246cb7c0.png)
 -- | --


<h4>until I close this site</h4>

- Verified selecting location and `until I close this site` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified opening a new tab and loading the same site still shows the permission set to block 
- Verified closing the second tab from pervious step doesn't reset permission on the first tab
- Verified when all tabs for the site is closed and reopened in a new tab prompts for permission again
 
<h4>for 24 hours</h4>

- Verified selecting location and `for 24 hours` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified moving device time ahead by 23 hrs and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 25 hrs and loading the page again and selecting location does prompt for permission
 

<h4>for 1 week</h4>

- Verified selecting location and `for 1 week` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified moving device time ahead by 6 days and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 8 days and loading the page again and selecting location does prompt for permission

<h4>forever</h4>

- Verified selecting location and `forever` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified moving device time ahead by 2 weeks and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 2 months and loading the page again and selecting location doesn'the prompt for permission

 
</details>


</details>

-------------
<details>
<summary>Verification passed on OnePlus 6T with Android 10 running 1.25.57 x64 Beta Build</summary>
<br>

- Verified `"until i close this page"` text is changed to `"until i close this site”`

<details>
<summary>Allow Tests</summary>
<h4>5 seconds</h4>

- Verified passing command line args `--permission-lifetime-test-seconds=5` adds an entry to the permission popup
- Verified selecting 5 seconds and selecting Allow sets the permission for the page
- Verified clicking site info shows permission that is set to allow
- Verified after 5 secs the permission is removed and not showed under site details

![image](https://user-images.githubusercontent.com/17010094/117949195-c5d3c600-b309-11eb-8c2f-069dcdadcff1.png) | ![image](https://user-images.githubusercontent.com/17010094/117949142-b81e4080-b309-11eb-91c4-6d2e566d063b.png)
 -- | --

<h4>until I close this site</h4>

- Verified selecting location and `until I close this site` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified opening a new tab and loading the same site still shows the permission set to allow 
- Verified closing the second tab from pervious step doesn't reset permission on the first tab
- Verified when all tabs for the site is closed and reopened in a new tab prompts for permission again
 
<h4>for 24 hours </h4>

- Verified selecting location and `for 24 hours` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified moving device time ahead by 23 hrs and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 25 hrs and loading the page again and selecting location does prompt for permission
 

<h4>for 1 week</h4>

- Verified selecting location and `for 1 week` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified moving device time ahead by 6 days and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 8 days and loading the page again and selecting location does prompt for permission

<h4>forever</h4>

- Verified selecting location and `forever` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified moving device time ahead by 2 weeks and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 2 months and loading the page again and selecting location doesn'the prompt for permission

 
</details>

<details>
<summary>Block Tests</summary>
<h4>5 seconds</h4>

- Verified passing command line args `--permission-lifetime-test-seconds=5` adds an entry to the permission popup
- Verified selecting 5 seconds and selecting `Block` sets the permission for the page
- Verified clicking site info shows permission that is set to block
- Verified after 5 secs the permission is removed and not showed under site details

![image](https://user-images.githubusercontent.com/17010094/117949280-dedc7700-b309-11eb-8296-bfa9a46cc69b.png) | ![image](https://user-images.githubusercontent.com/17010094/117949302-e3a12b00-b309-11eb-8a13-4133df5ac24f.png)
-- | --


<h4>until I close this site</h4>

- Verified selecting location and `until I close this site` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified opening a new tab and loading the same site still shows the permission set to block 
- Verified closing the second tab from pervious step doesn't reset permission on the first tab
- Verified when all tabs for the site is closed and reopened in a new tab prompts for permission again
 
<h4>for 24 hours</h4>

- Verified selecting location and `for 24 hours` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified moving device time ahead by 23 hrs and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 25 hrs and loading the page again and selecting location does prompt for permission
 

<h4>for 1 week</h4>

- Verified selecting location and `for 1 week` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified moving device time ahead by 6 days and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 8 days and loading the page again and selecting location does prompt for permission

<h4>forever</h4>

- Verified selecting location and `forever` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified moving device time ahead by 2 weeks and loading the page again and selecting location doesn't prompt for permission 
- Verified moving device time ahead by 2 months and loading the page again and selecting location doesn'the prompt for permission

 
</details>

</details>

**Comment by stephendonner** [comment]
Verification passed on 

Brave | 1.25.60 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | macOS Version 11.3.1 (Build 20E241)

- Verified `until i close this page` text is changed to `until i close this site`
- For all tests, enabled `Permission Lifetime` via `brave://flags`

<details>
<summary>Allow Tests</summary>
<h4>5 seconds</h4>

- Verified passing command line args `--permission-lifetime-test-seconds=5` adds an entry to the permission popup
- Verified selecting 5 seconds and selecting Allow sets the permission for the page
- Verified clicking site info shows permission that is set to allow
- Verified after 5 secs the permission is removed and not showed under site details

example | example | example
---------|---------|----------
<img width="1312" alt="Screen Shot 2021-05-17 at 11 10 02 AM" src="https://user-images.githubusercontent.com/387249/118540668-aa036200-b705-11eb-911a-4b9116ce4dd8.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 11 10 08 AM" src="https://user-images.githubusercontent.com/387249/118540682-abcd2580-b705-11eb-8046-ef24d0498bdf.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 11 10 51 AM" src="https://user-images.githubusercontent.com/387249/118540692-ac65bc00-b705-11eb-85be-b96192fde82c.png">


<h4>until I close this site</h4>

- Verified selecting location and `until I close this site` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified opening a new tab and loading the same site still shows the permission set to allow 
- Verified closing the second tab from pervious step doesn't reset permission on the first tab
- Verified when all tabs for the site is closed and reopened in a new tab prompts for permission again
 
<h4>for 24 hours </h4>

- Verified selecting location and `for 24 hours` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified moving laptop time ahead by 23 hrs and loading the page again and selecting location doesn't prompt for permission 
- Verified moving laptop time ahead by 25 hrs and loading the page again and selecting location does prompt for permission
 

<h4>for 1 week</h4>

- Verified selecting location and `for 1 week` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified moving laptop time ahead by 6 days and loading the page again and selecting location doesn't prompt for permission 
- Verified moving laptop time ahead by 8 days and loading the page again and selecting location does prompt for permission

<h4>forever</h4>

- Verified selecting location and `forever` and selecting allow sets permission on the site
- Verified clicking site info shows permission that is set to allow
- Verified moving laptop time ahead by 2 weeks and loading the page again and selecting location doesn't prompt for permission 
- Verified moving laptop time ahead by 2 months and loading the page again and selecting location doesn'the prompt for permission

 
</details>

<details>
<summary>Block Tests</summary>
<h4>5 seconds</h4>

- Verified passing command line args `--permission-lifetime-test-seconds=5` adds an entry to the permission popup
- Verified selecting 5 seconds and selecting `Block` sets the permission for the page
- Verified clicking site info shows permission that is set to block
- Verified after 5 secs the permission is removed and not showed under site details

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2021-05-17 at 11 32 48 AM" src="https://user-images.githubusercontent.com/387249/118541193-4a598680-b706-11eb-9758-027d4bc62741.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 11 32 52 AM" src="https://user-images.githubusercontent.com/387249/118541194-4af21d00-b706-11eb-8323-2ccb6ee2b30a.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 11 33 05 AM" src="https://user-images.githubusercontent.com/387249/118541197-4af21d00-b706-11eb-86d8-ae6be2c2326e.png">


<h4>until I close this site</h4>

- Verified selecting location and `until I close this site` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified opening a new tab and loading the same site still shows the permission set to block 
- Verified closing the second tab from previous step doesn't reset permission on the first tab
- Verified when all tabs for the site is closed and reopened in a new tab prompts for permission again
 
<h4>for 24 hours</h4>

- Verified selecting location and `for 24 hours` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified moving laptop time ahead by 23 hrs and loading the page again and selecting location doesn't prompt for permission 
- Verified moving laptop time ahead by 25 hrs and loading the page again and selecting location does prompt for permission
 

<h4>for 1 week</h4>

- Verified selecting location and `for 1 week` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified moving laptop time ahead by 6 days and loading the page again and selecting location doesn't prompt for permission 
- Verified moving laptop time ahead by 8 days and loading the page again and selecting location does prompt for permission

<h4>forever</h4>

- Verified selecting location and `forever` and selecting block sets permission on the site
- Verified clicking site info shows permission that is set to block
- Verified moving laptop time ahead by 2 weeks and loading the page again and selecting location doesn't prompt for permission 
- Verified moving laptop time ahead by 2 months and loading the page again and selecting location doesn't prompt for permission

 
</details>


</details>
