### ISSUE TITLE
[Android] Implement fractional tipping amounts (e.g. 1.25 BAT) on Android

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15618]
## Description 
Implement fractional tipping amounts (e.g. 1.25 BAT) on Android (found while testing https://github.com/brave/brave-browser/issues/15050)

## Steps to reproduce 

   1.  clean profile
   2.  launch Brave
   3.  go to About > Settings > Developer Options > QA Preferences
   4. enter the QA code
   5. toggle `Use Rewards staging server` to `On`
   6. relaunch Brave
   7. enabled Rewards
   8. load `3zsistemi.si`
   9. tap on the BAT icon in the URL bar
   10. take note of the default tipping values 

## Actual result 

[`1.000 BAT` ] [`5.000 BAT`] [`10.000 BAT`]

<img width=300 src=https://user-images.githubusercontent.com/387249/117062314-2ba3ca80-acd8-11eb-85be-f6ce60c9d008.png>

## Expected result

To match desktop, they should be -- for 3zsistemi.si at this time, on staging -- 1.25 BAT, for example

[`1.25 BAT` ] [`5 BAT`] [`10.5 BAT`]

<img width="1312" alt="Screen Shot 2021-05-04 at 12 43 05 PM" src="https://user-images.githubusercontent.com/387249/117062446-4c6c2000-acd8-11eb-87ff-9254d09b3dc7.png">

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): Pixel XL
   - Android version: 9.0
   
## Brave version

Brave `1.24.82, Chromium 90.0.4430.93`

/cc @deeppandya @zenparsing

**Comment by Miyayes** [comment]
I believe this is because the values are currently hardcoded on Android and aren't fetched. Will probably be solved with https://github.com/brave/brave-browser/issues/17070

**Comment by Miyayes** [comment]
Going to close this in favor of https://github.com/brave/brave-browser/issues/17070, since this is a subset of https://github.com/brave/brave-browser/issues/17070.
