### ISSUE TITLE
Notify User of OS-Suppressed Notifications

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#15617]
## Description 

Brave Notifications may be prevented from displaying by OS-level configurations like _Focus Assist_ or _Do Not Disturb_. When this is the case, user's should be made aware that Ad Notifications are being prevented.

## Actual result:

Ad Notifications may be blocked, with no clear reason to the user.

## Expected result:

User's should be notified when ads are enabled, but suppressed. One approach would be to place a small notification/warning on the Rewards page informing the user that DND/Focus Assist is enabled, and preventing notifications:

![image](https://user-images.githubusercontent.com/815158/117053367-79bbcc80-acde-11eb-83a4-26c683a05f82.png)

## Brave version (brave://version info)

1.23.75

**Comment by tmancey** [comment]
Closing issue as superseded by custom ad notifications

**Comment by tmancey** [comment]
Reopening after talking with @jonathansampson

**Comment by tmancey** [comment]
Great idea. However, we are transitioning from system to custom push notifications.
