### ISSUE TITLE
Add Reader Mode capability to Brave desktop

### ISSUE THREAD

**Issue by phoogm** [brave/brave-browser#15616]
## Description 

As a user i would like to be able to switch to the reader mode for reading articles in the Brave browser without distractions and either via an icon in the address bar (preferred) or via a settings menu item (less preferred) or both be able to switch between regular mode (reader mode off) and reader mode. This feature is build into Chromium since version 75 and is also available in Safari and Firefox.

## Steps to Reproduce

   1. Go to brave://flags
   2. Enable the flag called #enable-reader-mode
   3. Observe the feature does not become available

## Actual result:

<img width="746" alt="Flags Reader Mode" src="https://user-images.githubusercontent.com/56597375/117043753-ee5a2f80-ad0d-11eb-8ca9-8f701148fc92.png">

## Expected result:
The address bar shows an icon if a site supports the reader view and can be used to toggle between on and off for the Reader Mode, also in the settings menu an option enter Reader Mode becomes available.
<img width="291" alt="Reader mode menu options" src="https://user-images.githubusercontent.com/56597375/117043768-f2864d00-ad0d-11eb-85c7-ce39e6537989.png">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.23.75 Chromium: 90.0.4430.93 (Official Build) (arm64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3.1 (Build 20E241)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Thanks for looking into, best regards.

**Comment by rebron** [comment]
hi @phoogm 

Chromium's reader mode is available as subset of Speedreader and available via: brave://flags/#brave-speedreader to turn by everybody or enabled and rolled out to some users by default via the SpeedreaderReleaseStudy. https://griffin.brave.com/ You can see if you're in that study by looking at brave://versions

This is in the latest 1.28.105. You should be able to use either the Reader mode by itself or turn on Speedreader mode so pages that are readable will load automatically.

Let us know what you think here: https://community.brave.com/t/speedreader-feedback/273822/3

See #11994 as to what we're working on next.

Closing.
