### ISSUE TITLE
Find icon on URL bar overlaps on Shields

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1561]
## Description 

Find icon on URL bar overlaps on Shields

## Steps to Reproduce

   1. Launch a new profile on 0.55.13
   2. Visit a site in a new tab and open search using keyboard shortcut(Ctrl+F)
   3. Search icon on URL bar is overlapping on Shields button
   4. Click on the URL bar, find icon jumps into the URL bar 

## Actual result:

![search](https://user-images.githubusercontent.com/17010094/46898985-1df97180-ce5c-11e8-8e0b-6a77e0b90b1c.gif)

## Expected result:
Should not overlap 

## Reproduces how often: 

Easily reproduced on Linux

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Yes happens on Beta
- Does it reproduce on browser-laptop? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Icon is not even visible when Light theme is set
Creates a empty space when search is dismissed with cookie and autoplay icons are also there 
![search1](https://user-images.githubusercontent.com/17010094/46899074-171f2e80-ce5d-11e8-8a21-450577f5d67a.gif)
cc: @brave/legacy_qa

**Comment by srirambv** [comment]
@petemill and @snyderp reproduced on mac. Issue doesn't reproduce on 0.55.12

**Comment by GeetaSarvadnya** [comment]
Issue is reproducible on Windows as well - 0.55.13 version
