### ISSUE TITLE
Startpage icon too large size during onboarding

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#15611]
The new startpage icon is larger than others, see below:
![screen](https://user-images.githubusercontent.com/6406743/117003396-5724b600-acd4-11eb-8b60-2a61656a599f.png)

Only happening on Nightly, likely caused by brave/brave-core/pull/8656.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.60 x64 Beta Build
- Verified icon is shown properly

https://user-images.githubusercontent.com/17010094/118443243-92b37d00-b6e3-11eb-8008-0684de4d1f81.mp4

--------
Verification passed on Samsung Tab A with Android 10 running 1.25.60 x64 Beta Build
- Verified icon is shown properly

https://user-images.githubusercontent.com/17010094/118442943-2df82280-b6e3-11eb-9db1-eb791f8457de.mp4
