### ISSUE TITLE
Reposition Brave Ads custom ad notification to top-right of screen on Windows

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#15614]

**Comment by GeetaSarvadnya** [comment]
@tmancey Needs a small clarification on the issue. This issue is the same as #15624? Also, I could see the P3A label, is this related to P3A? Please provide the test plan in the issue

**Comment by tmancey** [comment]
@GeetaSarvadnya This is now superseded by https://github.com/brave/brave-browser/issues/15624. Thanks

**Comment by GeetaSarvadnya** [comment]
@tmancey Can you provide the test plan, please? The description of the issue says `Reposition Brave Ads custom ad notification to top-right of screen on Windows` this verification is already covered in https://github.com/brave/brave-browser/issues/15624#issuecomment-854966538

**Comment by tmancey** [comment]
@GeetaSarvadnya Just need to confirm the default position of custom ad notifications on Windows is positioned top-right. Thanks

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```


<!--StartFragment-->
Brave | 1.26.50 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

<!--EndFragment-->


```
- Confirmed that the default position of custom ad notifications on Windows are positioned top-right
![image](https://user-images.githubusercontent.com/38657976/121157729-69f85080-c867-11eb-9a48-dcec85aff0fb.png)

- Confirmed the default ad notification timeout for custom ad notifications on Windows is 120 seconds

```
[11320:14312:0608/143903.841:VERBOSE1:ad_notification_serving.cc(105)] Ad notification delivered:
  uuid: 939d423f-bf91-420e-ab69-8a32fa7d5799
  creativeInstanceId: 4983dc92-09fd-4e5c-94c3-616a4728c1d9
  creativeSetId: 5bdeab83-048f-48a7-9602-a1092ded123c
  campaignId: 63010037-c230-40db-b41a-3127619b88e4
  advertiserId: 8d2f4191-b76e-4369-8983-3d9ff551c5ad
  segment: untargeted
  title: This is a test
  body: This is a test
  targetUrl: https://www.brave.com
[11320:14312:0608/143903.843:VERBOSE3:ad_notification_event_viewed.cc(24)] Viewed ad notification with uuid 939d423f-bf91-420e-ab69-8a32fa7d5799 and creative instance id 4983dc92-09fd-4e5c-94c3-616a4728c1d9
[11320:14312:0608/143903.844:VERBOSE1:confirmations.cc(89)] Confirming view ad for creative instance id 4983dc92-09fd-4e5c-94c3-616a4728c1d9
```

Confirmed ad timeout and was hidden after 2 minutes

```
[11320:14312:0608/143903.841:VERBOSE1:ads_service_impl.cc(1819)] Timeout ad notification with uuid 939d423f-bf91-420e-ab69-8a32fa7d5799 in 120 seconds
```
