### ISSUE TITLE
Flash is not recognized on Linux

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1562]
## Description 

Flash is not recognized on Linux

## Steps to Reproduce

   1. Install Flash on Linux
   2. Install Brave Beta and visit homestarrunner.com/main1.html
   3. Right click on Flash placeholder, no option to `Run flash this time` in context menu

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46899168-09b67400-ce5e-11e8-9b62-581e58e02813.png)
![image](https://user-images.githubusercontent.com/17010094/46899159-f1465980-ce5d-11e8-9c77-52a4e78a04d7.png)

## Expected result:
Should show context menu option to run flash 

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
  Yes on both Dev and Beta
- Does it reproduce on browser-laptop? 
  No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Flash runs on chrome with the same flash player that is installed
![image](https://user-images.githubusercontent.com/17010094/46899184-37032200-ce5e-11e8-9650-ed34f002a925.png)
Issue reproduced by @yrliou 
cc: @brave/legacy_qa @diracdeltas @riastradh-brave

**Comment by ikus060** [comment]
I have the same problem. The only solution I found to workaround this problem is by running:
`brave-browser --ppapi-flash-path=/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so --ppapi-flash-version=32.0.0.114`

See https://community.brave.com/t/flash-player-not-working-on-linux-debian/43004/6

**Comment by AlexanderAmelkin** [comment]
@ikus060, this solution doesn't work for me on Linux Mint 18.3 Sylvia and Brave 0.68.132 Chromium: 76.0.3809.132. I have the standard `adobe-flashplugin` package installed, it provides flash player version 32.0.0.238, but changing 114 to 238 in your solution doesn't help, flash plugin is not listed among `chrome://components` and doesn't start on flash sites, even though enabled in per-site settings.

**Comment by braveflash** [comment]
> @ikus060, this solution doesn't work for me on Linux Mint 18.3 Sylvia and Brave 0.68.132 Chromium: 76.0.3809.132. I have the standard `adobe-flashplugin` package installed, it provides flash player version 32.0.0.238, but changing 114 to 238 in your solution doesn't help, flash plugin is not listed among `chrome://components` and doesn't start on flash sites, even though enabled in per-site settings.
> 
> Oh, and of course I symlinked /usr/lib/adobe-flashplugin to /usr/lib/pepperflashplugin-nonfree
> That didn't help either.

This worked perfectly for me on Mint 20.

sudo apt-get install pepperflashplugin-nonfree
sudo update-pepperflashplugin-nonfree --install
sudo sed -i -e '/Exec=\/usr\/bin\/brave-browser/s/$/ --ppapi-flash-path=\/usr\/lib\/pepperflashplugin-nonfree\/libpepflashplayer.so --ppapi-flash-version=32.0.0.344 /' /usr/share/applications/brave-browser.desktop

**Comment by projectintel-anon** [comment]
Update: the above command does not work, gives __sed: -e expression #1, char 8: unknown command: `u'__

**Comment by ryanbr** [comment]
Safe to close @srirambv (since flash is now removed)

**Comment by srirambv** [comment]
Yes can close it out
