### ISSUE TITLE
Auto discardable toggled on after relaunch

### ISSUE THREAD

**Issue by johnathan-codes** [brave/brave-browser#15626]
## Description 

After setting some tab in brave://discards/ auto discardable to "off" and restarting Brave, all tabs are reset to auto discardable on.

## Steps to Reproduce

   1. Open brave://discards/
   2. Set tab auto discardable off
   3. Relaunch Brave browser

## Actual result:
Tab is set to be discarded.

## Expected result:
Tab is set to not be discarded.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2009 (Build 19042.928)

**Comment by rebron** [comment]
@johnathan-codes brave://discards is an internal page that's meant for diagnostics and testing not as an end-user feature. 
https://chrome.google.com/webstore/detail/auto-tab-discard/jhnleheckmknfcgijgkadoemagpecfol?hl=en or another extension might be more useful for the time being.

We are looking into this feature more though: https://github.com/brave/brave-browser/issues/17453
