### ISSUE TITLE
Pending verifications/Release Notes from 1.24.x Release #1

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15620]
Current list of issues that have been fixed/resolved in [`1.24.x Release #1`](https://github.com/brave/brave-browser/milestone/186) but haven't been verified by QA:

- none

Current list of issues that were `release-notes/include` but not added into the `1.24.x Release #1` release notes and should be included in the notes for `1.24.x Release #2`

- Added bitFlyer two-way wallets for Japan. ([#14591](https://github.com/brave/brave-browser/issues/14591))
- Added support for time limits for web API permissions. ([#14126](https://github.com/brave/brave-browser/issues/14126))

**Comment by srirambv** [comment]
These 3 issues need to be tested on Android 

- Update l10n for 1.24.x release (Chromium 90). - #15514
- Use compile-time vars for rewards Uphold settings - #14900
- If client database says promotion is OVER but server says it is not, then set the promotion to ACTIVE - #14741

**Comment by LaurenWags** [comment]
Per discussion with @rebron and @kjozwiak, 

- Added bitFlyer two-way wallets for Japan. ([#14591](https://github.com/brave/brave-browser/issues/14591))
- Added support for time limits for web API permissions. ([#14126](https://github.com/brave/brave-browser/issues/14126))

will not be included in the release notes for this hotfix.

**Comment by kjozwiak** [comment]
> These 3 issues need to be tested on Android
> 
> * Update l10n for 1.24.x release (Chromium 90). - #15514
> * Use compile-time vars for rewards Uphold settings - #14900
> * If client database says promotion is OVER but server says it is not, then set the promotion to ACTIVE - #14741

Created https://github.com/brave/brave-browser/issues/15726 for `Android` 👍 #14741 won't be verified as per https://github.com/brave/brave-browser/issues/14741#issuecomment-837173226.
