### ISSUE TITLE
Captcha loads to Fail

### ISSUE THREAD

**Issue by howdyAnkit** [brave/brave-browser#15629]
## Description 

The Captcha Fails to load on the Brave Browser when Brave shields is enabled by disabling that we get the Captcha

## Steps to Reproduce

   1.  Go to Facebook.developerscom
   2. Create and app Fill the Form
   3.  Prove you are not a robot (❌ Captcha Fails)

## Actual result:

![CaptchaFailBrave](https://user-images.githubusercontent.com/40737659/117138056-2aea6180-adc8-11eb-9413-987d135525db.PNG)

Captcha Success on the Different Browser Edge
![CaptchaSuccs](https://user-images.githubusercontent.com/40737659/117138186-4b1a2080-adc8-11eb-9bb0-1f35291346c8.PNG)

## Expected result:
The Captcha Should be Loaded 

## Reproduces how often: 

Tried more than twice with disabling extension but have Same Behaviour

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? Not Tried
- Can you reproduce this issue with the nightly channel? Not Tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not Sure

**Comment by ryanbr** [comment]
Test with:
1. https://patrickhlauke.github.io/recaptcha/
2. https://www.google.com/recaptcha/api2/demo

Had no issues, can you test with the above recaptcha demos @howdyAnkit

**Comment by howdyAnkit** [comment]
Hey @ryanbr Thanks for Mentioning
if you compare the below attached Image with the previous test Image above.
Brave Shield is treating it like as an Add in my opinion. 

where as the Link you provided for reference has no brave shield blocking on the same.
In my Opinion the Brave shield is blocking the captcha considering as an Ad.
 
![captcha2](https://user-images.githubusercontent.com/40737659/117435004-fce15a80-af4a-11eb-86d1-2bdec0007a26.PNG)
![captcha](https://user-images.githubusercontent.com/40737659/117435053-09fe4980-af4b-11eb-9a03-c02901f54959.PNG)

**Comment by ryanbr** [comment]
If we are blocking captcha as an Advert, check shields "Ads and trackers" in the url bar. It'll show the blocked items there. @howdyAnkit 

Did the recaptcha tests work as intended?

**Comment by howdyAnkit** [comment]
Yeah Exactly Disabling the Shield the Captcha seems to be working Fine.

**Comment by ryanbr** [comment]
Which shield setting is causing it?

**Comment by howdyAnkit** [comment]
It's the **Brave Shield** @ryanbr situated inside the URL bar beside Brave Rewards.

**Comment by ryanbr** [comment]
Expand the shield icon, disabling which option (Ads/Trackers or Cookies, or fingerprinting) is the fix?

**Comment by howdyAnkit** [comment]
Allow all trackers and ands is the fix

![test](https://user-images.githubusercontent.com/40737659/117534504-5743ef00-b00f-11eb-826d-1267b01b6805.PNG)

**Comment by ryanbr** [comment]
Ah great, can you copy the blocked items (when ads/trackers is enabled), and paste the url's here

**Comment by ryanbr** [comment]
Any adblock filters enabled in `brave://adblock` ? @howdyAnkit

**Comment by howdyAnkit** [comment]
Hey Ryan Find the attached link for Links blocked. 
And no not any other adblock filters enabled I am attaching an Image to that as well below

https://pastebin.com/RpYbHFaC

![adblock](https://user-images.githubusercontent.com/40737659/117560773-544c0b80-b0ae-11eb-9b60-0f391422589a.PNG)
