### ISSUE TITLE
Failing to create wallet needs proper error and chance to retry

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#1563]
## Description 
If an internet connection is not available or there is a server issue, trying to create a wallet will go to a white page with a failed to create wallet error.

When a connection is restored, navigating to chrome://rewards shows the error and does not give another change to create wallet

## Steps to Reproduce

   1. Start Brave with clean profile
   2. Disable internet connection
   3. Try to enable rewards
   4. Observe error message
   5. Close Brave and reenable internet connection
   6. Reopen Brave and go to chrome://rewards

## Actual result:

Error message about wallet creation failed persists and doesn't give user a chance to create wallet

## Expected result:
Opt-in screen should show appropriate error and allow retry to wallet creation

## Reproduces how often: 

always

## Brave version (chrome://version info)

Brave | 0.57.1 Chromium: 70.0.3538.54 (Developer Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? tested on Dev
- Does it reproduce on browser-laptop? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by daubaris** [comment]
I'd like to take this!

**Comment by rebron** [comment]
@NejcZdovc is this fixed with a recent PR?

**Comment by NejcZdovc** [comment]
yes it was fixed with https://github.com/brave/brave-browser/issues/1687
