### ISSUE TITLE
Switch to Android Bundle on 1.24.x

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#15633]
Android Bundle format has already been enabled on beta and nightly. Now we consider it ready to land on stable.

Also fixes #15063.

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/8713 has been merged.

**Comment by kjozwiak** [comment]
Labeling this as `QA/No` as we'll run through https://github.com/brave/brave-browser/issues/15562, https://github.com/brave/brave-browser/issues/15563 & https://github.com/brave/brave-browser/issues/15561 using `aab` builds once we get the `1.24.x` RC's created.
