### ISSUE TITLE
sometimes unable to close/dismiss rewards panel notifications

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15639]
## Description 

Reported via https://bravesoftware.slack.com/archives/CB0KCRCQN/p1620237251397200

Sometimes notifications on the rewards panel have a close/"x" button, but clicking on it doesn't do anything, so the notification(s) can never be closed.

## Steps to Reproduce

Unknown at this time

## Actual result:

Notification(s) will not close

## Expected result:
Notification(s) should close

## Reproduces how often: 

unknown

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing @emerick @brave/legacy_qa

**Comment by Miyayes** [comment]
Should be resolved with the new rewards panel 2.0.
