### ISSUE TITLE
Translation Update - 1.24.x Japanese

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15632]
## Description 

Include translations for the "Learn more" sentence on the bF verify slide of rewards onboarding tour.

cc @Miyayes to provide Japanese translations for comparison

## Steps to Reproduce

   1. Confirm "Learn more" sentence of bF verify slide is translated when language = Japanese and region = Japan.

Discussion per https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1620224428204500?thread_ts=1620224334.203900&cid=CHGKGMHDJ

See also more info as to what is required in https://github.com/brave/brave-core/pull/8710#issue-630619902 and https://github.com/brave/brave-core/pull/8709#issue-630619866

cc @brave/legacy_qa @mkarolin

**Comment by Miyayes** [comment]
**English:** Learn more about how to link your Brave browser with your bitFlyer account.
 
**Japanese:** BraveブラウザとbitFlyerアカウントの連携方法について詳しくはこちら

The 詳しくはこちら part at the end is the hyperlink.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.24.83 Chromium: 90.0.4430.93 (Official Build) (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 10.15.7 (Build 19H1030)
```

<details>
<summary>English</summary>

Confirmed expected wording for English for panel and brave://rewards onboarding tours.
Confirmed "Learn more" links to https://brave.com/ja/users-bitflyer/ as per https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1620229207206700?thread_ts=1620224334.203900&cid=CHGKGMHDJ.

Panel | brave://rewards
----- | -----
<img width="398" alt="English - panel view" src="https://user-images.githubusercontent.com/28145373/117462265-7d3c9700-af1c-11eb-87f2-983a8f7406d5.png"> | <img width="426" alt="English - wide view" src="https://user-images.githubusercontent.com/28145373/117462270-7e6dc400-af1c-11eb-8532-648eef37daf0.png">

</details>

<details>
<summary>Japanese</summary>

Confirmed expected translations for Japanese for panel and brave://rewards onboarding tours.
Confirmed "詳しくはこちら" links to https://brave.com/ja/users-bitflyer/ as per https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1620229207206700?thread_ts=1620224334.203900&cid=CHGKGMHDJ.

Panel | brave://rewards
----- | -----
<img width="401" alt="JAPANESE - panel view" src="https://user-images.githubusercontent.com/28145373/117462303-862d6880-af1c-11eb-88bd-ae482c3367d3.png"> | ![Japanese - wide view 2](https://user-images.githubusercontent.com/28145373/117462311-875e9580-af1c-11eb-9965-83c8600b0de4.png)

</details>
