### ISSUE TITLE
Enable bitFlyer feature by default

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15631]
In 1.24 HF2 we would like to enable the bitFlyer feature flag by default.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.24.83 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Ubuntu 18.04 LTS

Verified bitFlyer feature flag is set to Enabled by default. 
![image](https://user-images.githubusercontent.com/34715963/117443345-4eccb500-af38-11eb-8164-ed6dbea1aca9.png)
