### ISSUE TITLE
IPFS-imported Wikipedia page is missing its images

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15634]
## Description 

IPFS-imported Wikipedia page is missing its images.

Found while testing https://github.com/brave/brave-browser/issues/14770

## Steps to Reproduce

   1.  load `ipns://brantly.eth` to get the interstitial IPFS page
   2. click on `Use a local node`
   3. go to `wikipedia.org`
   4. right-click the page and choose `Import to IPFS` > `This page` from the context menu
   5. you should get a link similar to `https://bafybeih7ugvikad7eyqoa4pi6vo7xvbh627eac2oduxxut6etqu7x4mxf4.ipfs.dweb.link/?filename=www.wikipedia.org`
   6. look at the resulting page

## Actual result:

The IPFS-imported Wikipedia page is missing its images

<img width="1312" alt="Screen Shot 2021-05-05 at 9 48 55 AM" src="https://user-images.githubusercontent.com/387249/117179258-cb6c6180-ad87-11eb-800d-297926a82542.png">

## Expected result:
<img width="1482" alt="Screen Shot 2021-05-05 at 9 44 21 AM" src="https://user-images.githubusercontent.com/387249/117179295-d58e6000-ad87-11eb-85e5-345b60ef98f4.png">

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.25.51 Chromium: 90.0.4430.93 (Official Build) beta (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3.1 (Build 20E241)

/cc @spylogsster

**Comment by stephendonner** [comment]
Can also confirm:

1) shows up fine when I share this link via Slack, and open on another machine, but the bottom icons do not (they are also not in the import directory)
2) the Wikipedia globe image/logo is in the imported directory

example | example | example
---------|---------|----------
![ipfs-wikimedia](https://user-images.githubusercontent.com/387249/117180493-16d33f80-ad89-11eb-8e42-4a61b27e96a0.png) | <img width="1725" alt="Screen Shot 2021-05-05 at 9 59 26 AM" src="https://user-images.githubusercontent.com/387249/117180172-bf34d400-ad88-11eb-82da-9eb0e208d0a3.png"> | <img width="1725" alt="Screen Shot 2021-05-05 at 9 59 34 AM" src="https://user-images.githubusercontent.com/387249/117180174-bfcd6a80-ad88-11eb-9bce-bff8d0a3d1b8.png">

**Comment by stephendonner** [comment]
Hey @spylogsster - mind taking a look and seeing if we can get a fix for this into `1.25.x`, via an uplift?

**Comment by spylogsster** [comment]
@stephendonner this is how chromium page saving works, it is tricky to fix, maybe in future

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
