### ISSUE TITLE
Remote frame is set on ephemeral-storage should-not-keep-alive test; should be empty

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15646]
## Description 
Remote frame is set on ephemeral-storage should-not-keep-alive test; should be empty.

Found while testing https://github.com/brave/brave-browser/issues/15415 as a follow-up to desktop, where it works fine.

## Steps to reproduce 

1. new profile
2. load `brave://flags` and enable both `Enable Ephemeral Storage` and `Ephemeral Storage Keep Alive`
3. restart / relaunch Brave
4. load `https://dev-pages.brave.software/storage/keep-alive.html`
5. click on the `Start test` button beneath the `Should Not "Keep Alive" Test`
6. wait for the test to finish and return you to the original page
7. per the test, under `Current storage state`, the results for `This frame` and `Local frame` read `set`, and `Remote frame` should read `empty`

## Actual result 

`Remote frame` reads `set`

example | example
---------|----------
![Screenshot_20210505-142817](https://user-images.githubusercontent.com/387249/117211920-7b54c580-adae-11eb-9f03-ebae7177608a.png) | ![Screenshot_20210505-142805](https://user-images.githubusercontent.com/387249/117211918-7b54c580-adae-11eb-98e9-f850b9f9ab7e.png)

## Expected result

`Remote frame` reads `empty`

## Issue reproduces how often 
100%

## Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): Google Pixel
   - Android version: 9.0
   
## Brave version

`1.25.51, Chromium 90.0.4430.93`

/cc @pes10k and @bridiver

**Comment by bridiver** [comment]
I'm pretty confident this is a general issue and not specific to keepalive. Can you run through the non-keepalive ephemeral storage tests?

**Comment by bridiver** [comment]
@stephendonner have you checked the non-keepalive tests with keepalive disabled? I don't think this is a keepalive issue, I think it's a regression on android

**Comment by stephendonner** [comment]
> @stephendonner have you checked the non-keepalive tests with keepalive disabled? I don't think this is a keepalive issue, I think it's a regression on android

Sorry for the delay in responding.

With `Enable Ephemeral Storage` set to `Enabled` and `Ephemeral Storage Keep Alive` set to `Disabled`, I see steps 2-6 all look identical to step 2.


feature flags | steps 2-6 results
---------|----------------------
![Screenshot_20210511-154634](https://user-images.githubusercontent.com/387249/117894069-6b3a5b80-b270-11eb-88f3-7e7acdb07c2f.png) | ![Screenshot_20210511-153503](https://user-images.githubusercontent.com/387249/117894066-6aa1c500-b270-11eb-800c-7de7efce96bb.png) |

**Comment by bridiver** [comment]
To provide a little more detail on this, the issue is not related to keep alive. The problem is that the session storage used for ephemeral local storage remained cached in the renderer even after the namespace was deleted in the browser process. It stayed cached across different domains and links and was only purged when typing a url into the urlbar

**Comment by bridiver** [comment]
also this issue exists in current release 1.24.x

**Comment by kjozwiak** [comment]
@brave/legacy_qa we'll need to run through https://dev-pages.brave.software/storage/index.html to make sure everything is still working as expected as per https://github.com/brave/brave-core/pull/8804#issuecomment-842740806. I updated the STR via https://github.com/brave/brave-browser/issues/15646#issue-876866787 to also mention that a full pass should be done as per @bridiver via Slack.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.24.86 x64 build

<details>
<summary>Verified steps from test case mentioned in issue description</summary>

Step 1 | Step 2 | Step 3 | Step 4 | Step 5 | Step 6
-- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/118972933-06b28700-b969-11eb-96fc-ee962cf01c5f.png) | ![image](https://user-images.githubusercontent.com/17010094/118972949-0c0fd180-b969-11eb-9466-1f7d7e26c045.png) | ![image](https://user-images.githubusercontent.com/17010094/118972962-10d48580-b969-11eb-9803-2da6bab117f3.png) | ![image](https://user-images.githubusercontent.com/17010094/118972977-14680c80-b969-11eb-9beb-73a6c095e007.png) | ![image](https://user-images.githubusercontent.com/17010094/118972994-17fb9380-b969-11eb-890a-2ffcfec6bf49.png) | ![image](https://user-images.githubusercontent.com/17010094/118973007-1cc04780-b969-11eb-8592-e639ddaf8670.png)

</details>

----------
Verification passed on OnePlus 6T with Android 10 running 1.24.86 x64 build

<details>
<summary>Verified steps from test case mentioned in issue description</summary>

Step 1 | Step 2 | Step 3 | Step 4 | Step 5 | Step 6
-- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/118972048-049bf880-b968-11eb-9ede-bbfd2dfcd136.png) | ![image](https://user-images.githubusercontent.com/17010094/118972065-09f94300-b968-11eb-964a-17688b18487c.png) | ![image](https://user-images.githubusercontent.com/17010094/118972078-0f568d80-b968-11eb-99c7-5ec8c0aadf35.png) | ![image](https://user-images.githubusercontent.com/17010094/118972101-14b3d800-b968-11eb-91f7-a9a67f4d3dde.png) | ![image](https://user-images.githubusercontent.com/17010094/118972126-1da4a980-b968-11eb-9e73-3f1a02940af0.png) | ![image](https://user-images.githubusercontent.com/17010094/118972147-25fce480-b968-11eb-956e-fbae895ffaaa.png)


</details>
