### ISSUE TITLE
Error in installing Brave beta

### ISSUE THREAD

**Issue by hemlok89** [brave/brave-browser#1564]
Hello, I tried to install the latest beta build of 1.0 version after trying out the dev build of Sep 6. But it is giving me an error as following.

https://i.imgur.com/RcJIji9.png

**Comment by srirambv** [comment]
Which setup did you run and the OS details. Please use the template to fill details. Just one line statement without any details will not help in resolving any issues.

**Comment by kjozwiak** [comment]
Thanks for the report @hemlok89! There's a known issue that we're currently looking into regarding installations failing on Win x86 machines. You can follow the progress in https://github.com/brave/brave-browser/issues/1606. Going to close the issue as a duplicate.

@hemlok89 a quick workaround for now is to keep trying to install it until it works. Eventually the installation should work. I know it's not ideal, but we're hoping to get this fixed soon!

**Comment by simonhong** [comment]
@hemlok89 I think below step will work for installing beta.
1. Install stable brave
2. Uninstall if you don't want to use stable brave (it's optional)
3. Install beta brave

Thanks for reporting!
