### ISSUE TITLE
Auto-Contribute entries sometimes contain 'on YouTube' text twice

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1565]
## Description 
Some Auto-Contribute table entries contain text text of 'on YouTube' twice.

## Steps to Reproduce

   1. Be sure Rewards are enabled.
   2. Visit some youtube videos. --> Verify they are added to the table.
   3. Visit a site with an embedded YouTube video. --> Verify it is added to the table.

## Actual result:
View table, some videos have 'on YouTube' text twice:
![screen shot 2018-10-13 at 4 12 14 pm](https://user-images.githubusercontent.com/28145373/46909661-11305880-cf04-11e8-902e-31f71c05138e.png)

## Expected result:
Should not have this text twice

## Reproduces how often: 
easily

## Brave version (chrome://version info)

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes, reproduced on Beta
- Does it reproduce on browser-laptop? no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Found while testing https://github.com/brave/brave-browser/issues/986

**Comment by NejcZdovc** [comment]
I think this was fixed with media panel. Let's retest when https://github.com/brave/brave-core/pull/699 lands
