### ISSUE TITLE
Youtube Commentary Section Laggs

### ISSUE THREAD

**Issue by forest-cat** [brave/brave-browser#15655]
## Description 

So one day i opened Brave Browser and went to the Youtube.de page. I clicked on a Video and startet looking i looked also through the comments and then the whole Youtube website startet lagging even the Video stopped and then was back with 144p. The CPU ussage suddenly goes to 25% and not the ordinary 2%

## Steps to Reproduce

   1. Open Brave and go to Youtube.de
   2. Click on a random Video make sure it has some comments
   3. Scroll to the Commantary Section of Youtube

## Actual result:

The whole page starts to lag and sometimes even the Video stops and changes its quality down to 144p or something like that

## Expected result:
Just normal Loading of this Section and no Lagging or Video Quality Changes

## Reproduces how often: 

On every Video with a little bit more comments

## Brave version (brave://version info)

1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-Bit)
4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
Windows 10 OS Version 2009 (Build 19042.928)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel? 
- Not installed and never tried
- Can you reproduce this issue with the nightly channel? 
- Not installed and never tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No, it keeps lagging
- Does the issue resolve itself when disabling Brave Rewards? 
- I am not using Brave Rewards so, no
- Is the issue reproducible on the latest version of Chrome? 
- No, its running perfectly on Chrome
## Miscellaneous Information:

Also tried with the Linux Version, same Problem. Disabled all Addons, same Problem. Used Addons: NoScript and UBlock Origin loaded from the Chrome Webstore. Tried Updating buts already the newest Version.

**Comment by ryanbr** [comment]
If you're using uBO Origin, disable shields Ads/trackers via `brave://settings` also I would disable NoScript (since that can be problematic on some/most sites) @forest-cat

**Comment by forest-cat** [comment]
> If you're using uBO Origin, disable shields Ads/trackers via `brave://settings` also I would disable NoScript (since that can be problematic on some/most sites) @forest-cat

I already told that i disabled all Addons and Brave Shield but the Error was still there.

**Comment by ryanbr** [comment]
If you have a VPN, try re-refresh the page from another location / in private window mode also.

Not specific to Brave, but looking through other users issues on /r/youtube, comments issues are quite common https://old.reddit.com/r/youtube/search?q=comments&restrict_sr=on&sort=new&t=week

**Comment by forest-cat** [comment]
I don't know how i've changed nothing but the Error fixed itself, i looked also on reddit but no one seemed to have the same problem. Because the Error is no longer existing it seems to have no reason to try it out with vpn. Maybe a pc restart fixed it or it was an update, if you don't answer or have some questions in some hours i will close this issue

**Comment by ryanbr** [comment]
Good to see it's resolved. From historical comment issues on youtube its all serverside issues.
