### ISSUE TITLE
Let us move the Brave Shield button to Extensions tab.

### ISSUE THREAD

**Issue by Dr-Sauce** [brave/brave-browser#15668]
## Steps to Reproduce

   1. No one likes a lion staring at you all the time.
   2. It's taking up the home button, add bookmark button space.
   3. 

## Actual result:

![Picture1](https://user-images.githubusercontent.com/82555878/117386830-8892c100-af22-11eb-93d2-4553ffd19ea4.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Shields isn't an extension, but actually built into Brave. @Dr-Sauce

**Comment by Dr-Sauce** [comment]
Then can't Brave allow us to hide it somewhere else or allow us to customize the icon?

**Comment by ryanbr** [comment]
Not my call, but hiding the shields icon seems counter intuitive. If a user forgets they disabled the icon, and then blame brave for potential breakages.

Shields icon doesn't take up much space. Shields makes Brave.

**Comment by Dr-Sauce** [comment]
Ok, Thanks :)

**Comment by abstract-arrow** [comment]
When the address bar is spanned all the way to the end the brave shield icon should be next to the extension's icon with a proper margin.
If there no way to disable the icon at least it should be properly placed in the address bar.

![brave_shield_placement](https://user-images.githubusercontent.com/61705762/117712397-84e49000-b1e9-11eb-9177-24ca28eb0b92.png)

**Comment by bsclifton** [comment]
cc: @rebron on above ^^
