### ISSUE TITLE
Add aggressive mode option in shields

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#15666]
## Description 
The work in https://github.com/brave/brave-browser/issues/7487 adds support in settings for aggressive mode, however we are missing the option to enable aggressive mode in shields. Please add this option.

@karenkliu for a design

cc @pes10k

**Comment by karenkliu** [comment]
This is a dupe of https://github.com/brave/brave-browser/issues/9831#issuecomment-786804751
