### ISSUE TITLE
Brave Shield leaves blank space.

### ISSUE THREAD

**Issue by Dr-Sauce** [brave/brave-browser#15669]
## Steps to Reproduce

   1. "Requests to the server have been blocked by an extension."
   2. 
   3. 

## Actual result:

Site: https://www.naver.com/

![image](https://user-images.githubusercontent.com/82555878/117388246-5fbffb00-af25-11eb-96da-216cd0a4d7bd.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Hey @Dr-Sauce 

Add the following into `brave://adblock`

```
naver.com###veta_top
naver.com###veta_branding
naver.com##.banner_area
```

**Comment by Dr-Sauce** [comment]
TYSM 😍😍

**Comment by ryanbr** [comment]
Fix will land for Brave in the next 24-48hrs @Dr-Sauce

**Comment by Dr-Sauce** [comment]
It's broken again.
-----Original Message-----

**Comment by Dr-Sauce** [comment]
I followed the method you told me. And it's worked great. But suddenly the "Requests to the server have been blocked by an extension." boxes are appearing again :(

**Comment by ryanbr** [comment]
ensure the filters are enabled in `brave://adblock` (as shown as the gif below) and shields `Ads/Tracking` is enabled.

Re-checked: https://gif.fanboy.co.nz/gif/naver-block.gif

Seems to be working well.

**Comment by Dr-Sauce** [comment]
Ah, now it's working again. Thanks.
