### ISSUE TITLE
IPFS Settings page doesnt work

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15665]
## Description 

Many errors in console
![image](https://user-images.githubusercontent.com/2965009/117359201-be528e00-aebf-11eb-8b17-7d6d3f57b4ab.png)

## Actual result:

IPFS Settings page doesnt work

## Expected result:
IPFS Settings page works 

## Reproduces how often: 

easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by wyatt400** [comment]
Works for me, can you get us your **brave://version** information?

**Comment by wyatt400** [comment]
![image](https://user-images.githubusercontent.com/54185618/117361831-fe395700-ae66-11eb-815c-836b0142d86d.png)
