### ISSUE TITLE
Remove request body details from Rewards verbose logging

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#15661]
Some URL requests that are made in `bat-native-ledger` should not have their request body logged at the verbose logging level, and should be logged instead at a higher level. Audit the code for URL request body logging and increase the logging level as necessary.

**Comment by kjozwiak** [comment]
@brave/legacy_qa we won't be able to verify the above until we get https://github.com/brave/brave-browser/issues/15924 fixed and uplifted into `1.25.x`.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, this should be available to test on https://github.com/brave/brave-browser/releases/tag/v1.25.64

**Comment by stephendonner** [comment]
Verified `PASSED` using https://github.com/brave/brave-core/pull/8767 with build 

Brave | 1.25.64 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:
1. new profile, launched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5`
2. enabled `Enabled Rewards Verbose Logging` via `brave://flags`
3. went to `brave://rewards` and clicked on `Verify Wallet`
4. authorized Uphold
5. logged in to Uphold
6. went to `brave://rewards-internals` and clicked `Refresh` to populate logs
7. searched for both `oauth` and `token` just to be sure
8. confirmed neither were present, together - just `tokens` for the grant process
9. downloaded the logs via the `Download` button and repeated steps 6 & 7

example | example | example
---------|---------|----------
<img width="1081" alt="Screen Shot 2021-05-19 at 9 43 11 AM" src="https://user-images.githubusercontent.com/387249/118852665-d47d2880-b887-11eb-80f3-9f406cc79046.png"> | <img width="1317" alt="Screen Shot 2021-05-19 at 9 45 20 AM" src="https://user-images.githubusercontent.com/387249/118852668-d515bf00-b887-11eb-897f-66064b3a8aca.png"> | <img width="1081" alt="Screen Shot 2021-05-19 at 9 46 03 AM" src="https://user-images.githubusercontent.com/387249/118852670-d515bf00-b887-11eb-961c-85c157654ead.png">

**Comment by srirambv** [comment]
Removing `OS/Android` label as there is a follow up issue logged for it #15924

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.66 x64 build
- Verified the test plan from brave/brave-core#8767
- Verified clicking on Refresh correctly populates the empty text field with the log
- Verified clicking on Download log works fine and logs file is downloaded. Logged #16061 as a follow up
- Verified `*.uphold.com/oauth2/token` dont appear anywhere within the log after connecting to an Uphold account
- Verified no entry for `oauth2` & `oauth2/token` in the log file
------------
Verification passed on Samsung Tab A with Android 10 running 1.25.66 x64 build
- Verified the test plan from brave/brave-core#8767
- Verified clicking on Refresh correctly populates the empty text field with the log
- Verified clicking on Download log works fine and logs file is downloaded. Logged #16061 as a follow up
- Verified `*.uphold.com/oauth2/token` dont appear anywhere within the log after connecting to an Uphold account
- Verified no entry for `oauth2` & `oauth2/token` in the log file
