### ISSUE TITLE
Add Brave Search as an alternative search

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#15663]
## Test plan
(for iOS, see https://github.com/brave/brave-ios/issues/3745)
### Onboarding experience (Desktop)
1. Fresh profile
2. Upon launching Brave, welcome screen will show
3. Navigate to fourth screen (Set default search engine)
    a. (US and Canada) Brave should show as an option in the dropdown
    b. (not US or Canada) Brave should not be in the dropdown

### Onboarding experience (Android)
TBD

## Search engines screen (all platforms)
1. Fresh profile
2. Launch Brave and go to settings
3. Under settings, pick `Search engines`
4. In settings pick `Manage search engines`
5. Brave should show under `Default search engines` area. Go ahead and choose it as default
6. Do a search in omnibox and verify search is going to search.brave.com SERP

## Autocomplete suggestions test (all platforms)
1. Fresh profile
2. Launch Brave and go to settings
3. Under settings, pick `Privacy and security`
4. Set the toggle for `Autocomplete searches and URLs` to true
5. Perform steps above (`Search engines screen (all platforms)`) to set Brave search as default
6. Type in the omnibox. Try something like `how do i` and verify autocomplete results are being shown

## Description 
We recently announced having a search (https://brave.com/brave-search/) and this issue is intended to capture adding this to the browser as an alternate search. It would be in the `Default search engines` list in brave://settings/searchEngines

Because this search is currently limited (https://brave.com/search/ is currently waitlist'ing folks; team is in Beta phase), we should put this behind a flag in brave://flags. When disabled (default setting) it wouldn't show search in `Default search engines` list. If true (user needs to set manually) then it will.

When we're ready to expand search to a larger audience we can change the value of this using Griffin or just remove the flag

**Comment by kjozwiak** [comment]
@brave/legacy_qa I've also added a bunch of more test cases that we ran via `iOS` that should also be checked via `Android` & `Desktop`. Please find them via https://github.com/brave/brave-core/pull/8966#issuecomment-864696937. Combination of what @bsclifton provided via https://github.com/brave/brave-browser/issues/15663#issue-877807321 and what was checked via `iOS`.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.26.65 Chromium: 91.0.4472.114 (Official Build) (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)

### `Onboarding/Setting Test Cases`

- ensured that Brave Search beta is only displayed under brave://welcome onboarding for Canada & USA
  - ensured that `Japan`, `German` & `France` weren't displaying `Brave Search beta` via search onboarding
- ensured that `Brave Search beta` appears via `brave://settings/search` & `brave://settings/searchEngines` for all regions
- ensured that the `query` URL appears as https://search.brave.com/search?q=%s&source=desktop under `brave://settings/searchEngines`

Japan onboarding | Germany onboarding | France onboarding | USA & Canada onboarding
------------------|-----------------------|--------------------|---------------------------
<img width="1197" alt="スクリーンショット 2021-06-21 10 53 20" src="https://user-images.githubusercontent.com/387249/122816747-fb19ef00-d28b-11eb-9b19-7c8781705f1c.png"> | <img width="1196" alt="Bildschirmfoto 2021-06-21 um 11 01 31" src="https://user-images.githubusercontent.com/387249/122816800-079e4780-d28c-11eb-8a04-cb6a2cc5ed29.png"> | <img width="1198" alt="Capture d’écran 2021-06-21 à 11 05 17" src="https://user-images.githubusercontent.com/387249/122816839-12f17300-d28c-11eb-95b4-723a6703ec00.png"> | <img width="759" alt="Screen Shot 2021-06-21 at 10 26 39 AM" src="https://user-images.githubusercontent.com/387249/122816929-269cd980-d28c-11eb-9299-d8606179bb6c.png">

Japan SE settings | Germany SE settings | France SE settings | USA & Canada settings
-------------------|----------------------|--------------------|------------------------
<img width="1198" alt="スクリーンショット 2021-06-21 10 54 23" src="https://user-images.githubusercontent.com/387249/122817102-606de000-d28c-11eb-8508-430717eeab73.png"> | <img width="1197" alt="Bildschirmfoto 2021-06-21 um 11 00 57" src="https://user-images.githubusercontent.com/387249/122817135-69f74800-d28c-11eb-8392-3428facea9ba.png"> | <img width="1199" alt="Capture d’écran 2021-06-21 à 11 05 33" src="https://user-images.githubusercontent.com/387249/122817167-7380b000-d28c-11eb-97c3-91733efd26a9.png"> | <img width="1199" alt="Screen Shot 2021-06-21 at 11 08 59 AM" src="https://user-images.githubusercontent.com/387249/122817228-83988f80-d28c-11eb-8c41-ca8eb07c12ae.png">

### `URL Query Test Cases`

- ensured that the correct query URL is being used when `Brave Search beta` is the default search engine:

  - `omnibox` --> https://search.brave.com/search?q=brave&source=desktop
  - `https://search.brave.com` --> https://search.brave.com/search?q=basic+attention+token
<img width="1312" alt="Screen Shot 2021-06-21 at 11 11 41 AM" src="https://user-images.githubusercontent.com/387249/122817423-ba6ea580-d28c-11eb-9ea8-67bf0f479378.png">

### `Default Callback Test Cases`

**Test Case 1:** (Setting as default via page)

- install `1.26.65 Chromium: 91.0.4472.114 (Official Build) (x86_64)`
- don't run through the search onboarding and leave `Google` as the default browser
- login into `https://search-dev.brave.com`
- search for `Brave Browser` via the text field
- click on the `Set default` button via the default modal within `https://search-dev.brave.com`
- you should see the button turn from `Set default` --> `Done` and disappear
- check and ensure `https://search-dev.brave.com` is set as the default via brave://settings/search

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2021-06-21 at 11 16 43 AM" src="https://user-images.githubusercontent.com/387249/122817671-0f122080-d28d-11eb-95df-1c8b00ac16f8.png"> | <img width="1312" alt="Screen Shot 2021-06-21 at 11 17 09 AM" src="https://user-images.githubusercontent.com/387249/122817674-10dbe400-d28d-11eb-893e-68a07c9480c8.png"> | <img width="1312" alt="Screen Shot 2021-06-21 at 11 17 17 AM" src="https://user-images.githubusercontent.com/387249/122817677-120d1100-d28d-11eb-8e20-69dac37ae245.png">

**Test Case 2:** (Private Browsing)

- install `1.26.65 Chromium: 91.0.4472.114 (Official Build) (x86_64)`
- don't run through the search onboarding and leave `Google` as the default browser
- launch open * login into `https://search-dev.brave.com` via `Private Browsing`
- search for `Basic Attention Token` via the text field
- shouldn't see any Brave Search `Default` modals

<img width="1312" alt="Screen Shot 2021-06-21 at 11 23 05 AM" src="https://user-images.githubusercontent.com/387249/122817810-41238280-d28d-11eb-8bca-6f2424b52eaa.png">

**Test Case 3:** (Default modal retries per session)

- install `1.26.65 Chromium: 91.0.4472.114 (Official Build) (x86_64)`
- don't run through the search onboarding and leave `Google` as the default browser
- login into `https://search-dev.brave.com`
- search for `Brave Browser` via the text field
- the `default` modal should appear
- refresh the page two times (should see the `default` modal appear
- refresh again and you shouldn't see the `default` modal appear for this session
- open a new tab, open `https://search-dev.brave.com` and try another search (shouldn't see any more modals for this session)

As per the above, this checks to make sure that the `Default` modal only appears three times per session.

**Test Case 4:** (Maximum 10 retries)

- install `1.26.65 Chromium: 91.0.4472.114 (Official Build) (x86_64)`
- don't run through the search onboarding and leave `Google` as the default browser
- login into `https://search-dev.brave.com`
- search for `Brave Browser` via the text field
- the `default` modal should appear
- refresh the page two times (should see the `default` modal appear
- refresh again and you shouldn't see the `default` modal appear for this session
- open a new tab, open `https://search-dev.brave.com` and try another search (shouldn't see any more modals for this session)
- close Brave and move the time forward by 24hrs

Repeat the above. The basic logic for the above is that on desktop/android, we should only see `3 modals` per session per day to a maximum of 10 in a span of four days.

**Test Case 5:** (Setting Brave Search as default via onboarding)

- install `1.26.65 Chromium: 91.0.4472.114 (Official Build) (x86_64)`
- Set `Brave Search beta` as the default SE via `brave://welcome`
- login into `https://search-dev.brave.com`
- search for `Brave Browser` via the text field
- ensure that the `default` modal isn't being displayed

**Test Case 6:** (Setting Brave Search as default via `brave://settings/search`)

- install `1.26.65 Chromium: 91.0.4472.114 (Official Build) (x86_64)`
- Set `Brave Search beta` as the default SE via `brave://settings/search`
- login into `https://search-dev.brave.com`
- search for `Brave Browser` via the text field
- ensure that the `default` modal isn't being displayed

### `Fallback Test Cases`

- ensured that the `Enable Google Fallback mixing` appears when searching for terms like `brave 123 456 789`
- ensured that tapping on ```Dismiss``` correctly closes the ```Enable Google Fallback mixing``` card
  - ensured that it re-appears when another term that needs `fallback` is used
- ensured that `Learn more.` opens https://search.brave.com/help/google-fallback
- ensured that `https://www.google.com` isn't being contact when `fallback` is disabled
- ensured that `https://www.google.com` is being contact once `fallback` has been enabled

example | example | example
---------|----------|---------
<img width="1763" alt="Screen Shot 2021-06-21 at 12 42 10 PM" src="https://user-images.githubusercontent.com/387249/122818670-5a78fe80-d28e-11eb-990e-ffacafb1c886.png"> | <img width="1658" alt="Screen Shot 2021-06-22 at 11 45 28 AM" src="https://user-images.githubusercontent.com/387249/122818814-81373500-d28e-11eb-8f0d-95aeb0f5b5a1.png"> | <img width="1655" alt="Screen Shot 2021-06-22 at 11 45 46 AM" src="https://user-images.githubusercontent.com/387249/122818824-8300f880-d28e-11eb-9970-4ae92f90383b.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.65 x64 build

### `On-boarding`
- Verified Brave Search beta is on shown in SE onboarding screen only for US and Canada
- Verified Brave Search beta is shown second on the list during onboarding
- Verified Brave Search beta is not listed for other locales for SE onboarding
- Verified selecting Brave Search beta during onboarding sets Brave search as default for both normal and private tabs

### `Search Engine Setting`
- Verified Brave Search beta is shown second on the list in search engine selection screen
- Verified selecting Brave Search beta from the SE list sets it as default
- Verified able to set Brave Search beta as default for both normal and private tabs from search engine selection screen
- Verified upgrading from 1.25.x to 1.26.65 adds Brave Search beta to the list at the bottom

### `URL Tests`
- Verified setting Brave Search beta as default and doing a search from omnibox adds `&source=android` to the query URL
Ex: `https://search.brave.com/?q=test&source=android`
- Verified performing a search on the search page doesn't append any `&source=android` to the query URL

### `Default Callback`
**Case 1: via Search page** 
- Install 1.26.65 
- Select URL bar to trigger SE onboarding
- Select continue so Google is set as default for both normal and private tab
- Visit `https://search.brave.com` and perform a search
- Click on `Set as default`and wait for the modal to change to `Done` and then auto-dismiss
- Verified Brave Search beta is set as default for normal mode only and not for private mode

**Case 2: via Search Page on Private tab**
- Install 1.26.65 
- Select URL bar to trigger SE onboarding
- Select continue so Google is set as default for both normal and private tab
- Visit `https://search.brave.com` and perform a search in private tab
- Verified no `Set as default` modal is shown on SERP
- Verified search engines settings remain same as before in settings

**Case 3: Default modal retries**
- Install 1.26.65 
- Select URL bar to trigger SE onboarding
- Select continue so Google is set as default for both normal and private tab
- Visit `https://search.brave.com` and perform a search
- `Set as default` modal should be shown 
- Reload the page two times, modal should still be shown
- Reload the page a third time, modal should be removed
- Open a new tab and perform a search on `search.brave.com`, no default modal is shown
- Clear browsing data and try again, still no default modal is shown

**Case 4: Default modal retries (max 10)**
- Install 1.26.65 
- Select URL bar to trigger SE onboarding
- Select continue so Google is set as default for both normal and private tab
- Visit `https://search.brave.com` and perform a search
- `Set as default` modal should be shown 
- Reload the page two times, modal should still be shown
- Reload the page a third time, modal should be removed
- Open a new tab and perform a search on `search.brave.com`, no default modal is shown
- Close browser and move device time by 24hr
- Search again on `search.brave.com`, default modal should be shown

### `Fallback Test Cases`
- Verified `Enable Google Fallback mixing` shows up when searching for term like `brave 123 456`
- Verified tapping on `Dismiss` hides the fallback modal
- Verified modal reappears every time a weird search term is used like above
- Verified `Learn more.` opens `https://search.brave.com/help/google-fallback`
- Verified `https://www.google.com` isn't being contact when fallback is disabled
- Verified `https://www.google.com` is being contact once fallback has been enabled

[image](https://user-images.githubusercontent.com/17010094/122912794-a0969680-d350-11eb-888a-c5656e58f1ad.png) | ![image](https://user-images.githubusercontent.com/17010094/122912768-98d6f200-d350-11eb-98fc-e504e331654f.png)
-- | -- 

-----------
Verification passed on OnePlus 6T with Android 10 running 1.26.65 x64 build

### `On-boarding`
- Verified Brave Search beta is on shown in SE onboarding screen only for US and Canada
- Verified Brave Search beta is shown second on the list during onboarding
- Verified Brave Search beta is not listed for other locales for SE onboarding
- Verified selecting Brave Search beta during onboarding sets Brave search as default for both normal and private tabs

### `Search Engine Setting`
- Verified Brave Search beta is shown second on the list in search engine selection screen
- Verified selecting Brave Search beta from the SE list sets it as default
- Verified able to set Brave Search beta as default for both normal and private tabs from search engine selection screen
- Verified upgrading from 1.25.x to 1.26.65 adds Brave Search beta to the list at the bottom

### `URL Tests`
- Verified setting Brave Search beta as default and doing a search from omnibox adds `&source=android` to the query URL
Ex: `https://search.brave.com/?q=test&source=android`
- Verified performing a search on the search page doesn't append any `&source=android` to the query URL

### `Default Callback`
**Case 1: via Search page** 
- Install 1.26.65 
- Select URL bar to trigger SE onboarding
- Select continue so Google is set as default for both normal and private tab
- Visit `https://search.brave.com` and perform a search
- Click on `Set as default`and wait for the modal to change to `Done` and then auto-dismiss
- Verified Brave Search beta is set as default for normal mode only and not for private mode

**Case 2: via Search Page on Private tab**
- Install 1.26.65 
- Select URL bar to trigger SE onboarding
- Select continue so Google is set as default for both normal and private tab
- Visit `https://search.brave.com` and perform a search in private tab
- Verified no `Set as default` modal is shown on SERP
- Verified search engines settings remain same as before in settings

**Case 3: Default modal retries**
- Install 1.26.65 
- Select URL bar to trigger SE onboarding
- Select continue so Google is set as default for both normal and private tab
- Visit `https://search.brave.com` and perform a search
- `Set as default` modal should be shown 
- Reload the page two times, modal should still be shown
- Reload the page a third time, modal should be removed
- Open a new tab and perform a search on `search.brave.com`, no default modal is shown
- Clear browsing data and try again, still no default modal is shown

**Case 4: Default modal retries (max 10)**
- Install 1.26.65 
- Select URL bar to trigger SE onboarding
- Select continue so Google is set as default for both normal and private tab
- Visit `https://search.brave.com` and perform a search
- `Set as default` modal should be shown 
- Reload the page two times, modal should still be shown
- Reload the page a third time, modal should be removed
- Open a new tab and perform a search on `search.brave.com`, no default modal is shown
- Close browser and move device time by 24hr
- Search again on `search.brave.com`, default modal should be shown

### `Fallback Test Cases`
- Verified `Enable Google Fallback mixing` shows up when searching for term like `brave 123 456`
- Verified tapping on `Dismiss` hides the fallback modal
- Verified modal reappears every time a weird search term is used like above
- Verified `Learn more.` opens `https://search.brave.com/help/google-fallback`
- Verified `https://www.google.com` isn't being contact when fallback is disabled
- Verified `https://www.google.com` is being contact once fallback has been enabled
