### ISSUE TITLE
Surface setting to enable/disable automatic tab discarding

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#15664]
## Description 

Many users have brought this up since I've been here. The auto-discard feature is great for saving memory and some users will never even notice that it exists. Others, however, are constantly reminded after the tab they were using/working is refreshed and form data/work/etc is lost.

The only way to adjust tab discarding settings is via `brave://discards` and even there, you can only disable the feature _per tab_ , _per session_ -- so the next time you open the browser you will have to repeat this process. I propose we surface this option into our settings so users can easily enable/disable this feature to suit their preferences.
![image](https://user-images.githubusercontent.com/3299098/117348443-0db4a200-ae5f-11eb-8fa6-e302518f251a.png)

Nice report/write up from a user on the issue:
https://community.brave.com/t/killing-inactive-tabs/243281

**Comment by yuryrodrigues** [comment]
This feature is very important!
There are tabs  that cannot be discarded, but I don't always have to keep it active.

**Comment by rebron** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/17453

**Comment by Cymes82** [comment]
This is NOT a duplicate. The request #17453 is the exact opposite of the issue #15664 

Some tabs cannot and shouldn't be discarded as they contain important user information - right now the only work-around is to manually mark them as non-discardable EVERY time you start working on your tabs on Brave. What I would like to request is to give users the ability to disable this feature.

**Comment by beigexperience** [comment]
I can not believe this still isn't an option I can toggle without having to install dodgy browser extensions.

**Comment by crogonint** [comment]
This may be a duplicate request of this one:
https://github.com/brave/brave-browser/issues/17453

That said, I ABSOLUTELY agree that this should have been patched back to it's previous functionality YEARS ago. AT least give us a toggle to turn it off, geez!

**Comment by SlugFiller** [comment]
While marking it as a duplicate of #17453 was technically incorrect, closing it is retroactively correct, since the setting requested now exists under `System` - `Memory` - `Memory Saver`. You can turn it off globally, or per-site.

**Comment by crogonint** [comment]
Well, a white list to keep the cache for certain websites is a start. Can we get an icon to toggle on, to add websites from the toolbar, instead of digging in to the menu every time we want to add something?
