### ISSUE TITLE
tab search button has weird hover/press effect

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15670]
![image](https://user-images.githubusercontent.com/6786187/117394853-e37fe480-af31-11eb-8c72-d65b67232fa4.png)

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (64-bit)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | Windows 10 OS Version 2009 (Build 21376.1)

Confirmed that on hover, in both `light` and `dark`-color modes, the hover effect is without the extra glyph/circle.

light | dark
------|------
![tab-hover-light](https://user-images.githubusercontent.com/387249/118033546-ca09de80-b31d-11eb-8498-c3d3cafd8408.png) | ![tab-hover-dark](https://user-images.githubusercontent.com/387249/118033545-c9714800-b31d-11eb-8fd7-97ddc9e097a8.png)
