### ISSUE TITLE
IPNS keys management page doesn't work

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15673]
blank page instead of keys management ui

**Comment by stephendonner** [comment]
@spylogsster could you please provide us with a testplan?  Thanks!  Marking `QA/Blocked` and `QA/Test-Plan-Required` just until you're able to provide that.

**Comment by spylogsster** [comment]
@stephendonner done

**Comment by stephendonner** [comment]
Verified `FIXED`  using 

Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (64-bit)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | Windows 10 OS Version 2009 (Build 21376.1)

Confirmed:
1. can load `brave://settings/ipfs/keys`
2. after clicking `Start node`, I get a key named `self` under `Keys available for publishing`
3. I am able to add and delete new keys

example | example | example | example
----------|-----------|-----------|----------
<img width="1505" alt="initial-keys" src="https://user-images.githubusercontent.com/387249/118186182-479f1e80-b3f2-11eb-9c96-92863651140b.png"> | ![default-key](https://user-images.githubusercontent.com/387249/118186066-250d0580-b3f2-11eb-93c6-66bc9b361309.png) | ![ipns-keys](https://user-images.githubusercontent.com/387249/118185705-b334bc00-b3f1-11eb-9b66-f0e5851157e9.png) | ![delete-newkey](https://user-images.githubusercontent.com/387249/118186220-5554a400-b3f2-11eb-9d31-887934863f64.png)
