### ISSUE TITLE
tip banner rewards onboarding tour issues

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15676]
## Description 

Rewards onboarding tour via tip banner doesn't match the others (from panel and brave://rewards). 

## Steps to Reproduce

   1. Clean profile, Japan region, if not enabled by default, enable bF.
   2. Navigate to a twitter page or other page with in-line tip button
   3. Click on on-line tip button
   4. On the tip banner, select Start using Brave Rewards
   5. View onboarding tour

## Actual result:

AC slide is present
Settings slide is present
no bF slide

## Expected result:
no AC slide
no Settings slide
bF slide should be present

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.24.83 Chromium: 90.0.4430.93 (Official Build) （x86_64）
-- | --
変更履歴 | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS バージョン10.15.7（ビルド19H1030）
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes (may need to enable bF via flags)
- Can you reproduce this issue with the nightly channel? yes (may need to enable bF via flags)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing @emerick @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.24.84 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2004 (Build 19041.928)

```
- Verified the STR from the description

<details>
<summary>Clean profile</summary>

- Confirmed AC slide is not shown in the banner rewards onboarding tour
- Confirmed settings slide is not shown in the banner rewards onboarding tour
- Confirmed bF slide is shown in the banner rewards onboarding tour

Example | Example | Example | Example | Example | Example | Example | Example
----------|-----------|----------|-----------|-----------|----------|-----------|---------
![image](https://user-images.githubusercontent.com/38657976/117791678-32968400-b268-11eb-9535-bce25e1a67f0.png) | ![image](https://user-images.githubusercontent.com/38657976/117791747-4215cd00-b268-11eb-8ea2-292f7e43dd17.png) | ![image](https://user-images.githubusercontent.com/38657976/117792155-a769be00-b268-11eb-8c68-2ec092ce9985.png) | ![image](https://user-images.githubusercontent.com/38657976/117792272-c36d5f80-b268-11eb-9ffc-f623356ee8f8.png) | ![image](https://user-images.githubusercontent.com/38657976/117792500-f6afee80-b268-11eb-9866-7bb84a3a3677.png) | ![image](https://user-images.githubusercontent.com/38657976/117792615-121af980-b269-11eb-9af1-ec0370073859.png) | ![image](https://user-images.githubusercontent.com/38657976/117792715-2c54d780-b269-11eb-8e74-b0e8a3424b17.png) | ![image](https://user-images.githubusercontent.com/38657976/117792819-468eb580-b269-11eb-8d2e-9dc9e681a272.png)

</details>
