### ISSUE TITLE
i18n packaging not working for Linux

### ISSUE THREAD

**Issue by AtjonTV** [brave/brave-browser#1567]
## Description 

I just downloaded a new copy of Brave 0.55.13 and it seems to have issues loading i18n strings.

## Steps to Reproduce

   1. Download `brave-v0.55.13-linux-x64`
   2. Extract it
   3. Start the browser
   4. Open the brave rewards menu besides the URL bar

## Actual result:

`i18n: welcomeHeaderTwo`

## Expected result:
The header text

## Reproduces how often: 

More then 5 times

## Brave version (chrome://version info)

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) unknown(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

Extended OS details:

```
Distribution: elemetary OS
Distribution Version: 0.4.1 Loki
Base Distribution: Ubuntu 16.04.5
Kernel: Linux 4.15.0-36-generic
```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes
- Does it reproduce on browser-laptop? 
no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
I guess 70.0 is latest so yes

### Additional Information

![screenshot from 2018-10-14 10 28 31](https://user-images.githubusercontent.com/24845056/46914394-302ef900-cf9d-11e8-9243-4b3e43d62fc7.png)

**Comment by AtjonTV** [comment]
I am now going to test with 0.56.3 to see if the same issue occurs.

**Comment by AtjonTV** [comment]
Brave | 0.56.3 Chromium: 70.0.3538.45 (Official Build) unknown(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

![screenshot from 2018-10-14 10 44 57](https://user-images.githubusercontent.com/24845056/46914454-35d90e80-cf9e-11e8-9d61-faf81a7d262f.png)

**Comment by NejcZdovc** [comment]
cc @bbondy this appears to be a problem on linux as well. Will https://github.com/brave/brave-core/pull/604 fix it for linux as well?

**Comment by AtjonTV** [comment]
System Language is English and Brave Language is also English

Changing the Brave Language to German does not change the Language at all :thinking:

**Comment by bbondy** [comment]
The last fix was definitely only for Wibdows, I'll check it out. Note some more work needs to be done to actually add the diff languages, but I'll do just the i18n label fix here.

**Comment by srirambv** [comment]
>Changing the Brave Language to German does not change the Language at all 

You need to do the following for browser language to change on Linux
- Add language packs from system settings
- Change Language from settings and restart
- Add preferred language in Browser and relaunch (Available languages might not be completely translated)

_**Please open a new issue if that doesn't work. Better to track one item per issue rather than combining multiple**_
