### ISSUE TITLE
Brave Rewards displaying wrong Reddit usernames

### ISSUE THREAD

**Issue by meejle** [brave/brave-browser#15687]
## Description 

I signed up to Brave Rewards Creator and claimed my Reddit account (among other social media accounts and websites that I own). I also submitted custom banners for each site/social media profile.

When trying to test this on Reddit (e.g., to see if the verified "tick" would appear on my profile page, whether my custom tip message would appear, etc.), I noticed various issues with usernames.

1. Somehow, my Brave browser has got itself hung up on one particular Redditor, u/thinsoldier. It doesn't matter whose profile page I visit, if I click the Brave Rewards icon (in the address bar), it shows "thinsoldier on Reddit". Here's a screenshot of it happening on u/Brave_Support's profile page (https://www.reddit.com/user/Brave_Support/):

<img width="1440" alt="Screenshot 2021-05-07 at 18 21 59" src="https://user-images.githubusercontent.com/35422415/117486145-2c02c680-af61-11eb-9c7a-80679cdd23da.png">

Clicking "Send a Tip..." also shows u/thinsoldier as the recipient of the tip:

<img width="1440" alt="Screenshot 2021-05-07 at 18 25 21" src="https://user-images.githubusercontent.com/35422415/117486520-ab909580-af61-11eb-9a67-d483feb81938.png">

But wait, it gets even weirder! Clicking the inline "Tip" buttons on Reddit seems to confuse things even more. Trying to tip on one of u/Brave_Support's comments, shows "thinsoldier on Reddit", but then correctly displays the username underneath as "u/Brave_Support". Also notice how it then shows a snippet of "thinsoldier's post" underneath:

<img width="1440" alt="Screenshot 2021-05-07 at 18 30 42" src="https://user-images.githubusercontent.com/35422415/117487006-5d2fc680-af62-11eb-9060-4d5112776601.png">

And weirder still: if I go to my _own_ Reddit user page (I'm u/meejle -- remember that, it'll be important in a second) and click one of the inline "Tip" buttons... I get... brace yourself... "thinsoldier on Reddit"... and then underneath, "u/mikeleewrites"! 

<img width="1440" alt="Screenshot 2021-05-07 at 18 34 38" src="https://user-images.githubusercontent.com/35422415/117488006-c3691900-af63-11eb-9851-cd07f8cce53e.png">

Strangely enough, there _is_ a u/Mikeleewrites (with a capital "M") on Reddit, but he _isn't_ me. I only have one Reddit account, and it's always been u/meejle. _**HOWEVER:**_ My _Twitter_ username _is_ @mikeleewrites (with a small "m"). I've claimed that Twitter account on my Brave Rewards Creator profile, so I can only imagine that's where Brave browser is somehow "finding" the "mikeleewrites" (with a small "m") username?

Yeah, sorry if you have to read this three or four times to make sense of it. I did my best.

I've tried clearing my history and cache, quitting and re-launching Brave, and rebooting (because why the heck not), but nothing has made a difference.

Strangely enough, using the old Reddit (e.g., https://old.reddit.com/user/meejle, https://old.reddit.com/user/Brave_Support) does seem to help the browser get over its obsession with u/thinsoldier (here it is correctly identifying u/Brave_Support):

<img width="1440" alt="Screenshot 2021-05-07 at 18 48 37" src="https://user-images.githubusercontent.com/35422415/117488971-e811c080-af64-11eb-84be-6bb92dc35107.png">

But it doesn't fix the other problem I'm having -- here it is correctly identifying the fact I'm a Brave Verified Creator, but wrongly referring to me as "mikeleewrites on Reddit" again:

<img width="1440" alt="Screenshot 2021-05-07 at 18 49 45" src="https://user-images.githubusercontent.com/35422415/117489148-2effb600-af65-11eb-8d9f-00894179ce76.png">

## Steps to Reproduce

   1. Visit https://www.reddit.com/user/meejle
   2. Click the Brave Rewards icon in the address bar

## Actual result:

Brave Rewards shows incorrect/unrelated Reddit usernames, and/or usernames seemingly pulled from elsewhere.

## Expected result:
Brave Rewards always shows the correct Reddit usernames.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.24.82 Chromium: 90.0.4430.93 (Official Build) (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3.1 (Build 20E241)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No (nor when disabling AdGuard)
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

N/A

**Comment by VictorieeMan** [comment]
I can confirm that I get the exact same problem independently of your instance. This happened before I found your GitHub issue here, and the description you have given fits my problem perfectly. In other words it replicates.

Just out of interest, have you connected a Twitter account to your Reddit account as well? Because in my case it seems like Brave Rewards try to use my Twitter handle as my Reddit Handle. (But I can't verify the coincidence.)

- https://www.reddit.com/r/brave_browser/comments/n7itxd/brave_rewards_for_reddit_refer_to_the_wrong/
- https://www.reddit.com/r/BATProject/comments/n9ri2e/brave_rewards_for_reddit_refer_to_the_wrong/

**Comment by VictorieeMan** [comment]
Yes I have linked the twitter as well, things over at twitters does work fine though. I've only experienced problems with Brave Rewards over at Reddit.

Interesting suggestion @meejle, I tried it out and got the same result as you mentioned (Clicking other profiles to tip them) and got the following results:

1. Clicking u/TheVictorieeMan (Tip, myself): https://u.pcloud.link/publink/show?code=XZnldeXZlkhtWbJKhDfSU0aOUN3ylXIQwFNk
2. Clicking u/meejle (Tipping @meejle): https://u.pcloud.link/publink/show?code=XZDCdeXZxFUal85IBEzg95AXVJyNYLnLSm4X
3. Clicking a random thrid party user: https://u.pcloud.link/publink/show?code=XZyKdeXZ8gQeYdserJ4hfI5b07skPBMvuVmV

Notice the differences between the results in each case. The first does differ from the second two, although all of them generate the wrong result.
- All three cases says "VictorieeMan on Reddit", that's wrong for all the cases.
- All three cases says "Note: This creator... [has not signed up to Brave Rewards]".
- Case 1. mentions u/VictorieeMan, but ought to be u/TheVictorieeMan
- Case 2 and 3, mentions the correct u/[handles] for both users (you and the random third party I tried this on.)

This seems to be the same thing you mentioned. Thanks for suggesting me to check the same.

**Comment by LaurenWags** [comment]
cc @brave/rewards-client 

also, I logged https://github.com/brave/brave-browser/issues/12302 which may or may not be related.

**Comment by VictorieeMan** [comment]
> 
> 
> > This error only seems to happen if I am logged into reddit when I am trying to tip. When I log out the correct reddit username appears in the tipping panel.
> 
> @CloggyAbroad Interesting! Yep, once I logged out, it at least got the _users_ right... although it still shows mine and @VictorieeMan's Twitter usernames.
> 
> Running more scenarios (because I liked how @VictorieeMan did it 😃):
> 
> **Logged out, visiting https://www.reddit.com/user/TheVictorieeMan**
> Shows "u/VictorieeMan" (correct user but incorrectly displays his Twitter username)
> 
> **Logged out, visiting https://www.reddit.com/user/meejle**
> Shows "u/mikeleewrites" (correct user but incorrectly displays my Twitter username)
> 
> **Logged in, visiting https://www.reddit.com/user/TheVictorieeMan**
> Shows "u/thinsoldier" (incorrect user)
> 
> **Logged in, visiting https://www.reddit.com/user/meejle**
> Shows "u/thinsoldier" (incorrect user)

Interesting @meejle, that your logged in visit get the "u/thinsoldier" when visiting me but when visiting logged out you get "u/VictorieeMan". Judging from that you get the same result as me when logged out but a local result when logged in.

And as for your similar issue @LaurenWags, it seems related in the results but the #12302 issue does for some reason have a much longer list of steps to replicate the problem. It's also from October 2020, has there been new releases since then, and if does it replicate on the latest release? Maybe it's gone worse judging from our short list of replicating the problem - haha.

**Comment by francois-rozet** [comment]
The problem likely comes from this file

https://github.com/brave/brave-core/blob/1cb5818aa0b70666c6aeea5ea9c06cc4e712171a/vendor/bat-native-ledger/src/bat/ledger/internal/legacy/media/reddit.cc

which has a few methods to detect users, like

https://github.com/brave/brave-core/blob/1cb5818aa0b70666c6aeea5ea9c06cc4e712171a/vendor/bat-native-ledger/src/bat/ledger/internal/legacy/media/reddit.cc#L139

https://github.com/brave/brave-core/blob/1cb5818aa0b70666c6aeea5ea9c06cc4e712171a/vendor/bat-native-ledger/src/bat/ledger/internal/legacy/media/reddit.cc#L155

It should not be too hard to test each of them, but I don't know how to compile these files 😞

**Comment by McKenneddy** [comment]
So brave recognises me as Fallengreg on reddit (should be Jjauso) ...and i have never had any name remotely close to that ...hope the issue gets fixed

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/nvyn97/why_is_there_someone_elses_username_when_i_click/

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/nwkwi2/brave_rewards_creators_links_my_reddit_profile_to/

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.27.108 Chromium: 92.0.4515.107 (Official Build) (x86_64)
Revision	87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS	macOS Version 10.15.7 (Build 19H1217)
```

and dev component `1.0.48`.

Verified both test plans from https://github.com/brave/brave-site-specific-scripts/pull/59#issue-668431665.
Confirmed I saw the correct Reddit user information whether I was logged in or not from panel, tip banner, and in-line tip banner.

Examples (Logged in):
Example | Example | Example | Example
----- | ----- | ----- | -----
<img width="1246" alt="Example1" src="https://user-images.githubusercontent.com/28145373/127014927-5106febe-2760-4e33-8c76-82782251c001.png"> | <img width="1243" alt="Example2" src="https://user-images.githubusercontent.com/28145373/127014933-921e8fb7-f755-4ed9-915e-4cf0a7080ccb.png"> | <img width="1241" alt="Example3" src="https://user-images.githubusercontent.com/28145373/127014938-6f46c02b-12d5-4bb1-88f4-992dfd21a331.png"> | <img width="1238" alt="Example4" src="https://user-images.githubusercontent.com/28145373/127014945-e74c27e3-dad3-4557-b8a5-b0aafc341aad.png">

**Comment by LaurenWags** [comment]
@VictorieeMan has your Reddit username ever been `VictorieeMan` or was it always `TheVictorieeMan`?

**Comment by VictorieeMan** [comment]
@LaurenWags I have never changed my Reddit username from TheVictorieeMan. My theory is that the brave rewards confuses the Reddit name with the twitter handle associated with the Reddit account, which isn't good. The original thread opener [@meejle) hinted about this:

"Strangely enough, there is a u/Mikeleewrites (with a capital "M") on Reddit, but he isn't me. I only have one Reddit account, and it's always been u/meejle. HOWEVER: My Twitter username is @mikeleewrites (with a small "m"). I've claimed that Twitter account on my Brave Rewards Creator profile, so I can only imagine that's where Brave browser is somehow "finding" the "mikeleewrites" (with a small "m") username?"

And the same goes for my account. It looks like it takes the twitter username and presents is in the form of a Reddit username with "u/" instead of "@" making things even more confusing.
