### ISSUE TITLE
Update token list for Crypto Wallets extension

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#15688]
Update token list dependency for brave/ethereum-remote-client.

I noticed we are missing some tokens that MetaMask has like Aave a-tokens.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.26.64 Chromium: 91.0.4472.114 (Official Build) (x86_64)
-- | --
Revision | `4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.30 Dev`

- Verified AAVE wrapped tokens exist in the Assets list. Ex: `aDAI`, `aWETH`, `aTUSD`

![image](https://user-images.githubusercontent.com/17010094/122877720-d165d400-d32e-11eb-82da-1362714d042c.png) | ![image](https://user-images.githubusercontent.com/17010094/122878570-cf504500-d32f-11eb-9811-fc18975a8a81.png)
-- | --

- Verified token upgrades are available. Ex: REPv2 and REP both listed in the token list.
![image](https://user-images.githubusercontent.com/17010094/122878981-44bc1580-d330-11eb-9ed5-21f742dd8a82.png)

- Verified `REN` token formerly known as "Republic Protocol" is renamed to "Republic Token".
![image](https://user-images.githubusercontent.com/17010094/122879269-9d8bae00-d330-11eb-89e0-d5da48c3726d.png)

- Verified deprecated token `EOS` is longer available in the token list
![image](https://user-images.githubusercontent.com/17010094/122879916-57831a00-d331-11eb-877e-b61d53600e78.png)

- Verified `FKX` contract address is changed to `0x16484d73Ac08d2355F466d448D2b79D2039F6EBB`

https://user-images.githubusercontent.com/17010094/122880357-d4ae8f00-d331-11eb-8e7c-e94fc6173dde.mov

-------------
Verification passed on 

Brave | 1.27.69 Chromium: 91.0.4472.106 (Official Build) beta (64-bit)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | Windows 10 OS Version 2009 (Build 19042.1052)
Component | `1.0.30 Dev`


- Verified AAVE wrapped tokens exist in the Assets list. Ex: `aDAI`, `aWETH`, `aTUSD`

![image](https://user-images.githubusercontent.com/17010094/122881523-27d51180-d333-11eb-9537-ccb66d65d817.png) | ![image](https://user-images.githubusercontent.com/17010094/122881603-3de2d200-d333-11eb-9200-871a9e6a705b.png)
-- | --

- Verified token upgrades are available. Ex: REPv2 and REP both listed in the token list.
![image](https://user-images.githubusercontent.com/17010094/122881883-87332180-d333-11eb-9bd2-64eb48f259a3.png)

- Verified `REN` token formerly known as "Republic Protocol" is renamed to "Republic Token".
![image](https://user-images.githubusercontent.com/17010094/122881948-974b0100-d333-11eb-906e-dee37bbe6534.png)

- Verified deprecated token `EOS` is longer available in the token list
![image](https://user-images.githubusercontent.com/17010094/122882189-d6795200-d333-11eb-8239-9a99208c0023.png)

- Verified `FKX` contract address is changed to `0x16484d73Ac08d2355F466d448D2b79D2039F6EBB`

https://user-images.githubusercontent.com/17010094/122882777-7040ff00-d334-11eb-9623-ab5844fa1c9d.mov

---------
Verification passed on

Brave | 1.28.17 Chromium: 91.0.4472.114 (Official Build) nightly (64-bit)
-- | --
Revision | `4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}`
OS | Linux
Component | `1.0.30 Dev`


- Verified AAVE wrapped tokens exist in the Assets list. Ex: `aDAI`, `aWETH`, `aTUSD`

![image](https://user-images.githubusercontent.com/17010094/122883168-d4fc5980-d334-11eb-8fdd-2301e6ee4298.png) | ![image](https://user-images.githubusercontent.com/17010094/122883426-17be3180-d335-11eb-8430-4f4bcd911594.png)
-- | --

- Verified token upgrades are available. Ex: REPv2 and REP both listed in the token list.
![image](https://user-images.githubusercontent.com/17010094/122883535-38868700-d335-11eb-8b70-6db7c82b0b54.png)

- Verified `REN` token formerly known as "Republic Protocol" is renamed to "Republic Token".
![image](https://user-images.githubusercontent.com/17010094/122883677-56ec8280-d335-11eb-918c-4c36e6c4a659.png)

- Verified deprecated token `EOS` is longer available in the token list
![image](https://user-images.githubusercontent.com/17010094/122883820-75eb1480-d335-11eb-96ee-7b78814d1c16.png)

- Verified `FKX` contract address is changed to `0x16484d73Ac08d2355F466d448D2b79D2039F6EBB`

https://user-images.githubusercontent.com/17010094/122884314-ebef7b80-d335-11eb-8b9f-602adc514443.mp4
