### ISSUE TITLE
Auto-Contribute is set to off after onboarding from tip panel

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15686]
## Description 
Auto-Contribute is set to off after onboarding from tip panel; might be related to/fallout from https://github.com/brave/brave-browser/issues/14735?

## Steps to Reproduce

(Sorry, still trying to whittle this down to minimal steps, but wanted to get this filed for the sake of time.)

1. launch with staging flags: `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5`
2. load `twitter.com/bravelaurenwags`
3. click the BAT icon
4. take the tour
5. accept the UGP grant
6. new-tab page a bunch of times (not necessary, just what I did)
7. click on `Start using Rewards`
8. open `brave://rewards`
9. notice that `Auto-Contribute` is toggled to `Off`
 

## Actual result:

<img width="1312" alt="Screen Shot 2021-05-07 at 9 54 19 AM" src="https://user-images.githubusercontent.com/387249/117484547-0f906b00-af1c-11eb-8139-e0a3cac63e40.png">

## Expected result:

Auto-Contribute should be set to `On`/enabled

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.24.83 Chromium: 90.0.4430.93 (Official Build) (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | macOS Version 11.3.1 (Build 20E241)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel?

/cc @zenparsing @emerick

**Comment by zenparsing** [comment]
I think the crucial step is accepting the UGP grant *before* you opt-in. In https://github.com/brave/brave-core/pull/8273 we made a change so that if you have a non-zero balance, then AC will not automatically be turned on. The intention there is to protect users from having their BAT spent inadvertently.

cc @Miyayes on whether we want to change the behavior here.
