### ISSUE TITLE
Increase the maximum number of Brave Rewards wallet instances can be linked to a crypto custodian account

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#15699]
Increase the maximum number of Brave Rewards wallet instances can be linked to a uphold account (crypto custodian account ). Current limit is 4.  this is not enough for most users (at least for me. using 6 instances. 2 windows 10 ( work and Home), 1 windows 7, 2 Linux (work and home) and 1 android)
Also do not count disconnected from the custodial account (after some time) or uninstalled brave instances.

**Comment by Miyayes** [comment]
We have existing plans for this (and some other issues logged for it at this time).
