### ISSUE TITLE
Brave Rewards counter

### ISSUE THREAD

**Issue by Nicola-Sergio** [brave/brave-browser#15691]
## Reward counter
Not always, but sometimes when the browser is started the counter shows distorted figures of the real rewards generated. This situation (sometimes) resolves itself after a few minutes. Sometimes to forcibly refresh the rewards counter you need to refresh the page many times and it doesn't always work.
## Brave Ads
Unfortunately, the setting for how often the ads are sent is not respected. Many times you don't get advertisements for hours.

**Comment by Nicola-Sergio** [comment]
I hope that these issues are at best resolved.

**Comment by Miyayes** [comment]
>Unfortunately, the setting for how often the ads are sent is not respected. Many times you don't get advertisements for hours.

To be sure: the "ads per hour" is a **maximum**, and not a minimum. So, even if you get 0 ads in an hour, that is logically consistent with an "**up to** 5 ads" setting!

**Comment by Miyayes** [comment]
>Not always, but sometimes when the browser is started the counter shows distorted figures of the real rewards generated. This situation (sometimes) resolves itself after a few minutes. Sometimes to forcibly refresh the rewards counter you need to refresh the page many times and it doesn't always work.

I believe this should be resolved with:

https://github.com/brave/brave-browser/issues/15460

**Comment by rebron** [comment]
Fixed with #15460 in version 1.23.x. We can reopen if still encountering the issue.
