### ISSUE TITLE
Brave minimizing when clicking the back button

### ISSUE THREAD

**Issue by Hoosier3** [brave/brave-browser#15695]
## Description 

Minimizing or changing tabs while on a webpage and resuming your tab will minimize Brave when clicking the back button.

## Steps to reproduce 

   1. Open Brave
   2. Go to any webpage
   3. Minimize or change tabs

## Actual result 

When resuming the webpage and you click the back button, Brave will minimize.

## Expected result

To go back to the search engine's page.

## Issue reproduces how often 

100% of the time.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM 64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 10
   
## Brave version

Brave 1.23.76

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by CplBDJ** [comment]
This bug, or feature is still present in 1.26.77 on Android 11.

**Comment by srirambv** [comment]
Could one you record the behaviour? I am unable to repro it. Also please mention the device that you are using could be device specific as well

**Comment by CplBDJ** [comment]
Sorry, I totally spaced it, but I found that:
[Settings -> Accessibility -> Simplified view for web pages] is checked the behavior occurs. I found this by using a different phone, that worked as expected, to check all the settings.

**Comment by anthonypkeane** [comment]
Doesn't look like we have an issue here given this seems to be expected behavior
