### ISSUE TITLE
unable to play udemy  videos

### ISSUE THREAD

**Issue by rajinder-yadav** [brave/brave-browser#15693]
## Description 

videos from udemy no longer play

## Steps to Reproduce

   1. log into udemy
   2. play a video

## Actual result:

video does not play

## Expected result:

video plays

## Brave version (brave://version info)

Brave | 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Linux
JavaScript | V8 9.0.257.23
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=ReducedReferrerGranularity,PasswordImport,WebUIDarkMode,PrefetchPrivacyChanges,DnsOverHttps,LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip --disable-features=IdleDetection,AutofillEnableAccountWalletStorage,SharingQRCodeGenerator,DirectSockets,SignedExchangeSubresourcePrefetch,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,TextFragmentAnchor,EnableProfilePickerOnStartup,TabHoverCards,WebOTP,NotificationTriggers,LangClientHintHeader,NetworkTimeServiceQuerying,SafeBrowsingEnhancedProtection,AutofillServerCommunication,SafeBrowsingEnhancedProtectionMessageInInterstitials --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/yadav/.config/BraveSoftware/Brave-Browser/Default
Variations | 7146a73c-3f4a17df

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? no

**Comment by rajinder-yadav** [comment]
![snap-40](https://user-images.githubusercontent.com/439226/117518977-d4b82280-af6f-11eb-8844-bc6ba397efe4.png)

**Comment by rajinder-yadav** [comment]
my guess is this problem showed up no less than a week ago

**Comment by ryanbr** [comment]
Hey I've tested this previously in https://github.com/brave/brave-browser/issues/15110, and widevine is now a requirement

Can you clear cookies/and relogin and ensure widevine is enabled? @rajinder-yadav

**Comment by rajinder-yadav** [comment]
Perfect, that fixed my problem, thanks!
