### ISSUE TITLE
Save as type *.html *.mhtml problem

### ISSUE THREAD

**Issue by salehif** [brave/brave-browser#15696]
## Description 
if I tries to save page "Save as..." the "save as type" shows incorrect extension

![2021-05-08_042434](https://user-images.githubusercontent.com/23007602/117521368-18357f80-afb6-11eb-8e11-f440884426bd.jpg)

## Actual result:
Save as type shows incorrect extension

## Expected result:
show correct extension

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-bit)
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2004 (Build 19041.928)

**Comment by ryanbr** [comment]
Just tested this, am I doing this correct? cycling between "Save as type"  option changes the file name here. Should be no difference between Brave and Chrome here @salehif 

![saveas](https://user-images.githubusercontent.com/1659004/117560024-42825c80-b0de-11eb-9a4d-18658d39b08f.gif)

**Comment by salehif** [comment]
need 

> Just tested this, am I doing this correct? cycling between "Save as type" option changes the file name here. Should be no difference between Brave and Chrome here @salehif
> 
> ![saveas](https://user-images.githubusercontent.com/1659004/117560024-42825c80-b0de-11eb-9a4d-18658d39b08f.gif)

so weird, I just tried again and it's now fixed!

maybe this related to OS more than browser

anyways, this issue will be closed.

**Comment by ryanbr** [comment]
Thanks for the update @salehif
