### ISSUE TITLE
Site with mixed active content should be marked insecure

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#157]
<img width="1045" alt="screen shot 2018-04-10 at 11 11 26 am" src="https://user-images.githubusercontent.com/1903815/38575376-20548dd6-3cb0-11e8-90e2-e4190b9280e8.png">

Repro URL: https://mixed-script.badssl.com/

**Comment by jumde** [comment]
This happens because unsafe scripts on secure domains are blocked by default. If the unsafe scripts are allowed the warning message is displayed. This is behaving as expected. 

<img width="1125" alt="screen shot 2018-08-20 at 3 56 36 pm" src="https://user-images.githubusercontent.com/1903815/44371020-af1e1e80-a491-11e8-990f-da14adf98435.png">

<img width="994" alt="screen shot 2018-08-20 at 3 58 09 pm" src="https://user-images.githubusercontent.com/1903815/44371058-de349000-a491-11e8-9e5e-ffb2dcb73a9b.png">

cc: @bbondy

**Comment by bbondy** [comment]
Ah, good find.Thanks
