### ISSUE TITLE
current tab frozen after sleep

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#15703]
## Description 

after my windows 10 pc goes to sleep  and I wake it up then the current brave tab is frozen.
I can unfreeze it by changing tab.
it started happening a few release ago, before it was running perfectly.

## Steps to Reproduce

   1.  open brave
   2. let the pc go in sleep mode
   3. wake it up

## Actual result:

the current tab is frozen (page doesn't scroll)

## Expected result:
tab should be working normally.

## Reproduces how often: 

always.

## Brave version (brave://version info)

Versione 1.24.82 Chromium: 90.0.4430.93 (Build ufficiale) (a 64 bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tortino** [comment]
happens to other people too:
https://www.reddit.com/r/brave_browser/comments/n7zxud/freezing_after_sleep_mode/

**Comment by ryanbr** [comment]
Does changing GPU Acceleration in `brave://settings/system`  help here?  Also does Chrome do the same thing? @tortino

**Comment by rebron** [comment]
Closing. Fixed with Chromium 91 per https://bugs.chromium.org/p/chromium/issues/detail?id=1189281 Latest 1.28.105 is on Chromium 92.0.4515.131
