### ISSUE TITLE
Anti-adblock on slate.com showing.

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#15702]
## Description 
`Slate.com` showing anti-adblock (using tinypass)

## Steps to Reproduce

   1. Open `slate.com` then open a few articles.
   2. Expect no anti-adblock
   3. 

## Actual result:

![slate com](https://user-images.githubusercontent.com/1659004/117558503-22e53700-b0d2-11eb-9da7-9c55207a4363.png)

## Expected result:
No anti-adblock

## Reproduces how often: 
Easily.

## Desktop Brave version:
`Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-bit)`

## Android Device details:
   - Install type (ARM, x86):   Arm
   - Device type (Phone, Tablet, Phablet): Phone, One plus 6
   - Android version: 10

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:
Reported: https://old.reddit.com/r/brave_browser/comments/n81kdf/slatecom_does_not_like_that_i_am_using_brave_and/

2 potentials fixes, 1 works in Brave other doesn't. related this PR: https://github.com/uBlockOrigin/uAssets/pull/9060

Works in Brave: `||tinypass.com^$domain=slate.com`
Doesn't work in Brave `slate.com##+js(aeld, error, Adblocker)`

Seems to be bug ^ @antonok-edm

**Comment by uBlock-user** [comment]
Does  `slate.com##+js(aeld, error)` work ?

**Comment by ryanbr** [comment]
Thanks for the suggestion, `slate.com##+js(aeld, error)` doesn't work either

**Comment by ryanbr** [comment]
Anti-adblock no longer seen, closing ticket.
