### ISSUE TITLE
Brave Tor CLI Argument doesn't works

### ISSUE THREAD

**Issue by Minecodes** [brave/brave-browser#15700]
I tried on my PC to make an Tor shortcut for Brave, but the argument `--tor` doesn't works anymore.

I'm using Windows 10 newest version and Brave newest version with 64bit on an Intel Processor

I tried it with:

- `brave --incognito --tor`
- `brave --tor`
- `brave --tor --incognito`

**Comment by rebron** [comment]
Fixed with https://github.com/brave/brave-browser/issues/15700 and will be available in 1.29.x
