### ISSUE TITLE
PC / Brave laggs on full screen website

### ISSUE THREAD

**Issue by UndercoverNL** [brave/brave-browser#15701]
## Description 
When any site on full screen (F11) Brave, and my full pc is lagging enormously. It is not an hardware isue since my CPU is running at 12% (i9-10900k) and my GPU is running at 6%

## Steps to Reproduce

   1. Press F11 on any site
   2. start and stay moving your mouse
   3. you will see it become lagging within 10 to 20 seconds

## Actual result:
Whole PC + Brave lagging

## Expected result:
A clean, not lagging PC when on full screen

## Reproduces how often: 
No steps to reproduce

## Brave version (brave://version info)
<html>
<body>

Brave | 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-bit)
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2009 (Build 19042.928)

## Version/Channel Information:
Hapens on every site

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? ?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:
/

**Comment by ryanbr** [comment]
As a test, can you try in private window mode, and open youtube in fullscreen? (and test in 720p/1080p/1440p/etc) does it matter resolution.  Which extensions do you have installed? @UndercoverNL

**Comment by UndercoverNL** [comment]
The issue seems to be disipeard after a simple PC restart. Since today its not lagging anymore.
