### ISSUE TITLE
Crashed while using search.brave.com

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15707]
Reported by @jonathansampson 

brave://settings/search says default search provider is `Google`.
and preferences file says `search.brave.com` is set to `default_search_provider_data`.
Brave search was set as a default provider before.
and crash happened when tried to open a private window.

https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3Db6aa2600-16ed-4806-0000-000000000000)&fingerprint=6373f5fb2c49057743f8f8645b4185c0f9608f7c99e2ce159891f299d3b2e642&debug=(eca415,0,0)

```
1 TemplateURLData::TemplateURLData
  ‎C:\jenkins\x64-release\src\components\search_engines\template_url_data.cc:50
2 TemplateURL::TemplateURL
‎  C:\jenkins\x64-release\src\components\search_engines\template_url.cc:1337
3 SearchEngineProviderService::ChangeToNormalWindowSearchEngineProvider
‎  C:\jenkins\x64-release\src\brave\browser\search_engines\search_engine_provider_service.cc:74
```

**Comment by iefremov** [comment]
@Miyayes also reproduced it https://bravesoftware.slack.com/archives/C01826CM3J9/p1621006367035300

**Comment by iefremov** [comment]
dupe https://github.com/brave/brave-browser/issues/16069
