### ISSUE TITLE
New tab page customization

### ISSUE THREAD

**Issue by MrinmoyHaloi** [brave/brave-browser#15704]
It would be great If we can set a url for the new tab page.

**Comment by Dr-Sauce** [comment]
Check [this](https://www.reddit.com/r/brave_browser/comments/mt9vf7/change_new_tab_wallpaper_2021/)
![image](https://user-images.githubusercontent.com/82555878/117736480-a3bb4480-b232-11eb-97c0-78b37f31f18c.png)

**Comment by bsclifton** [comment]
Thanks for the assist, @Dr-Sauce 😄 You absolutely can change this under appearance in settings (as shown above)
