### ISSUE TITLE
Add setting to allow opt-out of Griffin variations

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#15711]
## Description
we should add a global toggle to preferences below the P3A preference, that would allow a user to opt-out of receiving new variations from griffin backend. This should not affect the variations master preference in https://github.com/brave/brave-browser/issues/15229

## Designs
This toggle should be located in brave://settings/privacy under the P3A option (for now). 

![image](https://user-images.githubusercontent.com/2388823/119871044-ea699980-bed6-11eb-9f3b-924e28996849.png)

**Comment by ShivanKaul** [comment]
Given that we're also planning to run user studies where we collect user data through Griffin (https://github.com/brave/security/issues/439), perhaps this user preference could read 
**Allow staged roll-outs, feature testing and user studies**
_This anonymized info helps Brave improve security and performance of current and future features._
?
We don't currently have any preferences related to user studies and ISTM that if the user studies we run are going to be based on Griffin, then this would be a good place to control that. It would be even better if we can let users see and opt-out of specific Griffin studies, kinda like Firefox allows via their `about:studies`.

**Comment by iefremov** [comment]
closing as mostly dupe of https://github.com/brave/brave-browser/issues/36295 where the discussion actually happens
