### ISSUE TITLE
IPFS badge on built-in ipfs-webui

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#15718]
Brave 1.26.7 displays "Open using IPFS" badge when `/webui` is opened via the API port:

> ![2021-05-10--18-11-54](https://user-images.githubusercontent.com/157609/117690847-931bb780-b1bb-11eb-88a1-6aec90dad35b.png)

This introduces confusing behavior, because when the user clicks on the badge, the same CID is loaded  from the Gateway port, which has different Origin than the API port, which in turn asks user to safelist new Origin by setting CORS headers on their go-ipfs node.

I believe the better UX is if  the badge is not be displayed when the URL comes from the same origin as API port exposed by go-ipfs.

**Comment by lidel** [comment]
FYSA in addition to the UX problem described above, this is also impacted by the bug described in https://github.com/brave/brave-browser/issues/16115

@spylogsster I still think the best course of action here is to now show badge on URLs coming from the API port.

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/8980 with build 

Brave | 1.27.37 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.5 (Build 20G5023d)

Steps:

1. clean profile
2. launched Brave
3. loaded `ipns://brantly.eth`
4. clicked on `Use a local node`
5. waited for configuration to finish
6. loaded `brave://ipfs-internals/`
7. clicked on `My Node`
8. confirmed on the resulting `http://127.0.0.1:45002/ipfs/bafybeianwe4vy7sprht5sm3hshvxjeqhwcmvbzq73u55sdhqngmohkjgs4/#/` page:

* no `Open using IPFS` badge in the URL bar
* no context-menu option to import the page to IPFS

<img width="948" alt="Screen Shot 2021-06-02 at 7 40 35 PM" src="https://user-images.githubusercontent.com/387249/120578751-2a4ee600-c3db-11eb-9d95-7779404ac874.png">
