### ISSUE TITLE
Brave back button occasionally doesn't go to the previous page

### ISSUE THREAD

**Issue by manningb** [brave/brave-browser#15716]
## Description 
Sometimes when I press the back button it does not go to the previous page but stays on the current page.

## Steps to Reproduce

   1. Go to a webpage, then click on a link to go to the next page
   2. Press the back button
   3. This may or may not result in the page actually going to the previous page

## Expected result:
Back button results in going to the previous webpage in that tab.

## Reproduces how often: 
This is an Intermittent issue and only happens occasionally.

## Brave version (brave://version info)
Brave | 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2009 (Build 19042.928)

## Version/Channel Information:
I haven't tested this issue on other versions or channels.

**Comment by seanarnold** [comment]
I raised this here too https://github.com/brave/brave-browser/issues/15645.

**Comment by rebron** [comment]
Hi @manningb Can you provide an example of the page where you're having this issue? Sometimes it's the way the page is built due to some of its features or method of authentication that makes going backward the wrong result you're expecting.

**Comment by bsclifton** [comment]
Unfortunately, there's not enough information here to troubleshoot. @manningb please re-open if you have more information. Ex: was this the back button on your mouse? or you are clicking the back button and it's not working?

I'll definitely take a look at https://github.com/brave/brave-browser/issues/15645 (back button on mouse not working)

**Comment by Havasiz** [comment]
> ## Description
> Sometimes when I press the back button it does not go to the previous page but stays on the current page.
> 
> ## Steps to Reproduce
> 1. Go to a webpage, then click on a link to go to the next page
> 2. Press the back button
> 3. This may or may not result in the page actually going to the previous page
> 
> ## Expected result:
> Back button results in going to the previous webpage in that tab.
> 
> ## Reproduces how often:
> This is an Intermittent issue and only happens occasionally.
> 
> ## Brave version (brave://version info)
> Brave	1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)
> Revision	4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
> OS	Windows 10 OS Version 2009 (Build 19042.928)
> ## Version/Channel Information:
> I haven't tested this issue on other versions or channels.

Hey, did you find a solution? I have the same problem and it's annoying...

**Comment by Serek16** [comment]
Same here. And it happens quite frequently

**Comment by cmditch** [comment]
I experience this issue on github.com quite often. Usually when I'm looking at an issue or PR and hit back to go to the repo homepage.
