### ISSUE TITLE
Show 'Add to sidebar' menu bubble on hovered over item add button

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15713]
Sub issue of https://github.com/brave/brave-browser/issues/14980
`Add to sidebar` menu bubble is visible when button is clicked now.
Change to show it when hovered over that button

**Comment by simonhong** [comment]
@karenkliu Sorry, maybe I asked before but forgot. We want to show menu bubble only on hover?
Or showing on hover several times and show it on click?

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8769 with build 

Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (64-bit)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | Windows 10 OS Version 2009 (Build 21376.1)

Steps:
1. launched Brave with a clean profile
2.  enabled `Enable Sidebar` feature flag via `brave://flags` and relaunched
3.  loaded www.brave.com
4.  hovered over the `+` add button
5.  added `brave.com` to the sidebar
6.  hovered over the `brave.com` favicon and saw its tooltip
7.  removed `brave.com` from the sidebar

Confirmed:

* tooltip on mouse hover displays page title
* ability to add current tab to Sidebar panel via mouse-hover and click
* ability to remove selected (via context-click) site from Sidebar panel

![sidebar-bubble](https://user-images.githubusercontent.com/387249/118190385-e4b08600-b3f7-11eb-808c-7ca3b84039d2.gif)
