### ISSUE TITLE
Double separator line when you can "send to Google phone"

### ISSUE THREAD

**Issue by xopez** [brave/brave-browser#15714]
## Description 
Hi, if you connect the sync to an android, you can use the "send to google phone" feature. This shows 2 separators in the right click menu under that.
I don't know the condition for the feature since it didn't show up right away

## Steps to Reproduce

   1. Add sync between Desktop and Android
   2. Right click on any page
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/28950736/117655287-27275800-b197-11eb-8ead-bede094d9d1d.png)

## Expected result:
only one seperator without the empty space in that

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.24.82 Chromium: 90.0.4430.93 64-Bit

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No (already disabled)**
- Is the issue reproducible on the latest version of Chrome? **Yes**

**Comment by AlexeyBarabash** [comment]
On Chrome the next menu item is `Create QR code for this page` which is cut in Brave.

**Comment by stephendonner** [comment]
This happens on desktop, too, but isn't always broken.  It depends on the content for the context-menu invocation.

broken | works
--------|--------
![broken-desktop](https://user-images.githubusercontent.com/387249/118195712-9489f180-b400-11eb-92f3-037a940c532d.png) | ![not-always-broken](https://user-images.githubusercontent.com/387249/118195617-660c1680-b400-11eb-8b1c-8e7a1bc14dd7.png)

**Comment by AlexeyBarabash** [comment]
Now (1.27.4)  I see the space between two separators is supposed to correspond the Chrome `Translate to English` menu item.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.20 Chromium: 91.0.4472.114 (Official Build) nightly (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. set up Sync chain view `brave://settings/braveSync`
2. join chain using either desktop Brave or iOS/Android Brave
3. on desktop, context-click on any page
4. look at the context-menu options

Confirmed it's now:
```
-----------------------------
Send to Your Devices >
Create QR code for this Page
-----------------------------
```

<img width="1342" alt="Screen Shot 2021-06-22 at 9 56 02 AM" src="https://user-images.githubusercontent.com/387249/122969283-51953500-d341-11eb-9dd6-b4a8fe04c12b.png">
