### ISSUE TITLE
Change shield settings is causing the browser crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1574]
## Description 
Change shield settings is causing the browser crash

**Note**: Issue is reproducible on both 0.55.13 Brave beta and 0.56.4 Dev channels

## Steps to Reproduce

   1. Launch Brave with clean profile from CLI
   2. Open youtube.com
   3. Play any video
   4. Change shield settings

## Actual result:
Change shield settings is causing the browser crash

Brave Dev - 0.56.4
Crash ID: 6748b9628ef390d4
Crash Report: https://stats.brave.com/dashboard#crash/5bc3fb4294412c001e07e50a
![0 56 4_change shield settings crashes the browser](https://user-images.githubusercontent.com/38657976/46926852-27e3c600-d050-11e8-8c3c-c0648cda9cc0.gif)

Brave beta -0.55.13
Crash ID: 4e71818e0b949c79
Crash Report:https://stats.brave.com/dashboard#crash/5bc3fb9594412c001e07e78b

Console Error:
Segmentation Fault
![image](https://user-images.githubusercontent.com/38657976/46926981-dc7de780-d050-11e8-82ad-f1e3182f27dc.png)

## Expected result:
Should not be any crash

## Reproduces how often: 
Always

## Brave version (chrome://version info)
Brave | 0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified with STR from description, no crash was observed with several attempts
