### ISSUE TITLE
Cannot locate Brave shortcut after update

### ISSUE THREAD

**Issue by lukeansell** [brave/brave-browser#15744]
## Description 

After an update I no longer have the Desktop shortcut nor can I find it if I search for it.

## Steps to Reproduce

   1.  Update
   2.  Unable to locate shortcut

## Actual result:

Cannot locate Brave shortcut

## Expected result:
Brave shortcut on my desktop where it was before.

## Reproduces how often: 

Has happened after the last two updates

## Brave version (brave://version info)

Brave | 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-bit)
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2009 (Build 19042.928)
JavaScript | V8 9.0.257.23

**Comment by rebron** [comment]
@lukeansell Do you have something installed that's cleaning up Desktop shortcuts or is it that you can't find the Brave shortcut? Can you create a new shortcut for Brave and let us know if it disappears again upon upgrade. Should be under Program Files/BraveSoftware/Brave-Browser/Application and then right click to create a shortcut to place one on your desktop. 

Our latest version is Brave 1.28.106.
