### ISSUE TITLE
ENS should have another option for Ethereum like Unstoppable Domains does

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#15751]
We currently don't have an Ethereum option for ENS, we should add one like Unstoppable Domains has:
<img width="687" alt="Screen Shot 2021-05-11 at 10 23 17 AM" src="https://user-images.githubusercontent.com/831718/117831862-fbfa4280-b242-11eb-94be-4fc09499e4f2.png">

**Comment by stephendonner** [comment]
@spylogsster @yrliou I'm unable to get this working on either `1.27.x` or `1.28.x`; have any tips?  Also, any other ones to try besides the list on `https://etherscan.io/enslookup`?  Thanks!

Steps:
1. new profile
2. launch Brave
3. load `brave://settings/extensions`
4. for `Method to resolve Ethereum Name Service (ENS)` choose `Ethereum`
5. open a new tab
6. load `http://blocktimer.dappstar.eth/`

I've tried with and without `Use secure DNS` in `brave://settings/security` flipped `On`.  This 

Setting `QA/Blocked` for now.

**Comment by spylogsster** [comment]
@stephendonner thank you, created new issue https://github.com/brave/brave-browser/issues/16655

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.27.101 Chromium: 91.0.4472.124 (Official Build) beta (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launched Brave
3. loaded `brave://settings/extensions` and chose `Ethereum` for `Method to resolve Ethereum Name Service (ENS)`
4. loaded the following domains: `blocktimer.dappstar.eth`, `brantly.eth`, `matoken.eth`, `ethhub.eth`
5. confirmed they resolved and loaded a page

`blocktimer.dappstar.eth` | `brantly.eth` | `matoken.eth` | `ethhub.eth`
---------------------------|-------------|----------------|-------------
<img width="1312" alt="Screen Shot 2021-07-12 at 3 30 53 PM" src="https://user-images.githubusercontent.com/387249/125364396-3d809a00-e327-11eb-8e86-a03e1cedd3b8.png"> | <img width="1312" alt="Screen Shot 2021-07-12 at 3 39 25 PM" src="https://user-images.githubusercontent.com/387249/125364572-98b28c80-e327-11eb-8850-db73dae860da.png"> | <img width="1312" alt="Screen Shot 2021-07-12 at 3 40 02 PM" src="https://user-images.githubusercontent.com/387249/125364608-a700a880-e327-11eb-916a-66c5d18b5384.png"> | <img width="1312" alt="Screen Shot 2021-07-12 at 3 40 22 PM" src="https://user-images.githubusercontent.com/387249/125364641-b253d400-e327-11eb-96f0-9873e5f353c3.png">
