### ISSUE TITLE
Unstoppable Domains IPFS for local gateway should show ipfs://

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#15750]
When Unstoppable Domains is set to resolve via Ethereum, and the local gateway is in use, we resolve to an IPFS URI like: 
http://bafybeihihoci7ocqupvuda3ldpiy5zvjctgybg32jxpppplkstdwtq7dhi.ipfs.localhost:48081/

<img width="678" alt="Screen Shot 2021-05-11 at 10 21 19 AM" src="https://user-images.githubusercontent.com/831718/117831520-a3c34080-b242-11eb-89e5-b832322b9fd9.png">

Instead we should show ipfs://<cid> in that case.

**Comment by lidel** [comment]
How does Ethereum resolution work? If it is using https://resolver.unstoppable.io/dns-query or https://eth.resolver.cloudflare-eth.com/dns-query then we will be able to keep `ipns://` when  go-ipfs 0.9.0 ships (https://github.com/brave/brave-browser/issues/15749#issuecomment-838955191)

**Comment by yrliou** [comment]
@lidel Currently it calls Unstoppable Domains smart contract via eth_call when visiting *.crypto, if there's IPFS content hash record existed, we'll redirect to ipfs://{CID}.

**Comment by lidel** [comment]
@yrliou is Brave running own Ethereum light client, or is the `eth_call` delegated to some infra in the cloud?

**Comment by yrliou** [comment]
@lidel currently we do eth_call via Infura.

**Comment by lidel** [comment]
Ack. In that case we need to wait for go-ipfs 0.9.0, and we will be able to show `ipns://*.crypto`

**Comment by spylogsster** [comment]
0.7.0 shows DNS error for me when I navigate to "brad.crypto" (UD set as Ethereum)
0.9.0-rc1 navigates to http://bafybeihihoci7ocqupvuda3ldpiy5zvjctgybg32jxpppplkstdwtq7dhi.ipfs.localhost:48081/

**Comment by lidel** [comment]
We should start work towards supporting `.crypto` over DoH resolver in 0.9.0+
UX is better, and you don't decrease security in any way (resolution is delegated to a third party in both cases, but using DoH for name resolution keeps `ipns://brad.crypto` in address bar.

**Comment by spylogsster** [comment]
the DNS error with 0.7.0 works fine on another computer, it navigates me to ipfs://bafybeihihoci7ocqupvuda3ldpiy5zvjctgybg32jxpppplkstdwtq7dhi/ (brad.crypto + UD set as Ethereum + ipfs as local node)  @lidel @bbondy

**Comment by lidel** [comment]
Note that the behavior with 0.7.0 is pointing the user at a static snapshot  – the user may not understand this is an immutable version, and if they bookmark `ipfs://` URI they will get stuck with this version of  the website forever.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.27.56 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. loaded `ipns://brantly.eth`
3. clicked on `Use a local node`
4. set `Method to resolve Unstoppable Domains` to `Ethereum` via `brave://settings/extensions`
5. loaded `brad.crypto`
6. confirmed I was redirected to `ipfs://bafybeihihoci7ocqupvuda3ldpiy5zvjctgybg32jxpppplkstdwtq7dhi/`

example | example | example
---------|----------|---------
<img width="1513" alt="Screen Shot 2021-06-10 at 9 56 04 AM" src="https://user-images.githubusercontent.com/387249/121568242-59191d80-c9d4-11eb-80ad-9ce7a8397f10.png"> | <img width="1112" alt="Screen Shot 2021-06-10 at 9 54 39 AM" src="https://user-images.githubusercontent.com/387249/121568235-55859680-c9d4-11eb-9c83-55f474aa14f4.png"> | <img width="1513" alt="Screen Shot 2021-06-10 at 9 55 47 AM" src="https://user-images.githubusercontent.com/387249/121568240-574f5a00-c9d4-11eb-8b5c-24605726a253.png">
