### ISSUE TITLE
Remove redundant classes for import

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15758]
After refactoring from https://github.com/brave/brave-core/pull/8771 we do not need anymore dedicated classes.

Removed File/Text/Directory import classes, use base class instead
Move blob creation to network utilities
Avoid of base::Uretained

**Comment by stephendonner** [comment]
Marking as `QA/Blocked` until https://github.com/brave/brave-browser/issues/15935 is verified fixed.

**Comment by stephendonner** [comment]
> Marking as `QA/Blocked` until #15935 is verified fixed.

I conflated issues; this is working just fine, sorry!

### Verified `PASSED` using 

Brave | 1.26.30 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

## Steps:
### Image
* loaded `* ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/`
* right-clicked and chose `Import to IPFS` -> `Selected image`
### Text
* loaded `https://www.lipsum.com/` and scrolled down to the first lorem ipsum paragraph
* selected it and chose `Import to IPFS` -> `Selected text`
### Link
* loaded `https://archive.org/web/`
* right-clicked on the Wayback Machine logo and choose `Import to IPFS` -> `Linked content`
### Video
* loaded `https://upload.wikimedia.org/wikipedia/commons/7/79/Big_Buck_Bunny_small.ogv`
* right-clicked on the video and choose `Import to IPFS` -> `Selected video`
### File
* loaded `https://www.leaseweb.com/platform/network`
* scrolled down to a 10MB file from a mirror, right-clicked on it and chose `Import to IPFS` -> Linked content`


example | example | example | example | example | example | example
---------|----------|---------|----------|---------|----------|---------
<img width="1792" alt="Screen Shot 2021-05-19 at 3 25 03 PM" src="https://user-images.githubusercontent.com/387249/118892921-7d427c80-b8b6-11eb-9922-a178a6ac6f8d.png"> | <img width="1792" alt="Screen Shot 2021-05-19 at 2 57 09 PM" src="https://user-images.githubusercontent.com/387249/118892958-8af80200-b8b6-11eb-8d36-621ae50b30c0.png"> | <img width="1792" alt="Screen Shot 2021-05-19 at 3 07 31 PM" src="https://user-images.githubusercontent.com/387249/118892996-98ad8780-b8b6-11eb-8b80-e843782a832a.png"> | <img width="1680" alt="Screen Shot 2021-05-19 at 3 12 48 PM" src="https://user-images.githubusercontent.com/387249/118893037-a8c56700-b8b6-11eb-82ef-f79a6597c6b4.png"> | <img width="1792" alt="Screen Shot 2021-05-19 at 3 34 26 PM" src="https://user-images.githubusercontent.com/387249/118893801-e8d91980-b8b7-11eb-9682-cd6972dfd103.png"> | <img width="1792" alt="Screen Shot 2021-05-19 at 3 34 31 PM" src="https://user-images.githubusercontent.com/387249/118893832-f7273580-b8b7-11eb-9861-e3e404e7f448.png"> | <img width="1792" alt="Screen Shot 2021-05-19 at 3 44 40 PM" src="https://user-images.githubusercontent.com/387249/118894486-31450700-b8b9-11eb-8b85-9aa0f5900ae4.png">

Image: `https://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi.ipfs.dweb.link/?filename=bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi.ipfs.localhost`
Text: `https://bafybeibjhmwnw2s47sr6xij2xj7thr7u7d3c2v7ckxecvvewolwha6zr3q.ipfs.dweb.link/?filename=www.lipsum.com_13828526949295533255`
Link: `https://bafybeiavuq4ixeuay3rprg4mb2ydlzmdb3qb3lbjt6b2od5hsiomy65gnq.ipfs.dweb.link/?filename=archive.org
Webpage: https://bafybeieorrkovrjqdxv24xrvigpotqjljlytwxzubsl6tmh5ejf4fmlqa4.ipfs.dweb.link/?filename=www.wikipedia.org`
Video: `https://dweb.link/ipfs/QmaNvPDRmgT3xs7E5B9MQoZLxrqMtjfDnWnFrHHhyPzC9i?filename=Big_Buck_Bunny_small.ogv`
File: `https://dweb.link/ipfs/QmZAjR7E1qB4nD5T55F95thMLn2fG5C8tpUB2FMnVhS8Nn?filename=10mb.bin`
