### ISSUE TITLE
Embedded iframe webview crash on Tor windows

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1575]
## Description 
Due to Ad blockers, a iframe is getting crashed while playing YT video in Tor window. If we select "Allow Ads and Tracking" web page crash is removed automatically. In b-l Tor tabs, this issue is not reproducible.

## Steps to Reproduce

   1.  Launch Brave with clean profile
   2.  Open Tor window
   3.  Open youtube.com
   4. Play a video

Please note that, this issue is not coming for all the videos, few videos where i have seen the issue are listed below:
https://www.youtube.com/watch?v=cqyziA30whE
https://www.youtube.com/watch?v=ywDp5r7ofek
https://www.youtube.com/watch?v=1fVwoquZuU4
## Actual result:
Embedded iframe webview crash on Tor windows

![image](https://user-images.githubusercontent.com/38657976/46928849-29b28700-d05a-11e8-9c80-db7bb04b06c2.png)

## Expected result:
Should not be any iframe web view crash

## Reproduces how often: 
Easy

## Brave version (chrome://version info)

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by srirambv** [comment]
@bbondy I think that's a suggested video ad iframe that is getting crashed. Ideally should be blocked. 
I don't see the iframe all the time on Tor tabs. 
![image](https://user-images.githubusercontent.com/17010094/46951546-4e0c6480-d056-11e8-9545-3cbb788279e2.png)

**Comment by GeetaSarvadnya** [comment]
When you open youtube.com on Tor windows iframe is getting crashed - Version 0.55.18

![image](https://user-images.githubusercontent.com/38657976/47186022-d76cb100-d34c-11e8-97fd-aa9beda803c9.png)

**Comment by kjozwiak** [comment]
Some more information: this doesn't always happen. When you change your Tor exit node a few times, sometimes the banner will appear without any issues. Maybe it has something to do with the exit node/local you've connected to and which first party ad is being loaded from YT?

**Comment by GeetaSarvadnya** [comment]
Looks like the issue is fixed. Unable to Reproduce the issue on below versions:
 
`0.63.48` - Not reproducible
`0.64.60` - Not reproducible
`0.66.24` - Not reproducible
`0.65.74` - Not reproducible
