### ISSUE TITLE
Update chromium to  90.0.4430.212	

### ISSUE THREAD

**Issue by Area51Kacz** [brave/brave-browser#15762]
## Description 
Could we update to Chromium 90.0.4430.212 _(brave its still on .93)_
--

<br class="Apple-interchange-newline">

## Steps to Reproduce

just update it to 90.0.4430.212	

## Version/Channel Information:

Stable

**Comment by bsclifton** [comment]
@Area51Kacz yup - we're already working on it 😄 Closing this as a duplicate of https://github.com/brave/brave-browser/issues/15725
