### ISSUE TITLE
Refactor: Simplify network delegate helpers by having a single request_url

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1576]
Instead of having a new_url and a request_url, some of the logic would be more simple and less error prone if we had only one. 

We could also store the original_request_url so we know if it was changed or not in each network delegate helper.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

* Verified general use of browser doesn't cause any crash
