### ISSUE TITLE
Sidebar is hidden during the item re-ordering

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15765]
When `show sidebar option` is `on click` or `on mouseover`, sidebar is hidden during the item re-ordering.
During the re-ordering, sidebar should not be hidden.

**Comment by stephendonner** [comment]
Verified `FIXED` via steps 1-7 over in https://github.com/brave/brave-browser/issues/15766#issuecomment-842676059, using 

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | Windows&nbsp;10 OS Version 2009 (Build 21382.1)
