### ISSUE TITLE
Sidebar is hidden when related bubbles are still visible

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15766]
With `on mouseover` or `on click` options,  sidebar gets hidden after mouse goes out from sidebar
even if sidebar item add bubble is visible.
Sidebar should be visible when sidebar initiated bubbles are still displayed regardless of show options.

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/8781 with build

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | Windows&nbsp;10 OS Version 2009 (Build 21382.1)

Steps:

1. enabled `Sidebar` flag via `brave://flags` and re-launched
2. context-clicked on Sidebar and selected `On mouseover` sidebar show option
3. re-ordered a few items via drag and drop, and confirmed sidebar UI was not hidden
4. loaded `www.brave.com`
5. moused-over to the sidebar Add to Sidebar infobubble, with `brave.com` URL in it
6. mouse goes out from sidebar ui after add item menu bubble is shown
7. confirmed sidebar UI was not hidden
8. clicked on the webpage to dismiss `Add to Sidebar` bubble
9. confirmed sidebar UI was hidden after `Add to Sidebar` menu bubble was hidden

step 3 | step 7 | step 9
---------|----------|---------
![sidebar-not-hidden](https://user-images.githubusercontent.com/387249/118562645-f3fa4100-b721-11eb-8b6f-162d8af0d351.png) | ![sidebar-mouseover](https://user-images.githubusercontent.com/387249/118562679-02485d00-b722-11eb-85a6-7f7f70d93407.png) | ![sidebar-hidden](https://user-images.githubusercontent.com/387249/118562678-01afc680-b722-11eb-9a40-c452bf2f1655.png)
