### ISSUE TITLE
Two different checkboxes for P3A in settings

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#15761]
We appear to have two different checkboxes in `brave://settings/privacy` related to usage data (i.e. P3A):
![Screenshot from 2021-05-11 14-08-40](https://user-images.githubusercontent.com/167821/117885299-8b631e00-b262-11eb-93c1-d6eee48f884e.png)

The first one defaults to ON, the second one defaults to OFF.

I think the second one might be just for crash reports? If so, then we should change the text so that it's clear that it's just about crash reports.

**Comment by bsclifton** [comment]
@fmarier that is correct - the 2nd one should just be crash reports. We should definitely update 😄

**Comment by karenkliu** [comment]
We're already tracking cleaning up the P3A opt-in and crash reporting in this issue: https://github.com/brave/brave-browser/issues/14269 

That issue shows text cleaned up and moving the two options to the "Get Started" section so it's easier for users to find.
