### ISSUE TITLE
Missing translations for new Rewards login message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15772]
## Description 
Missing translations for new Rewards login message

## Steps to reproduce 

   1. Set locale to a non-EN region
   2. Clean install 1.25.57 Beta Build
   3. Click on Rewards button and click on `Verify Wallet`
   4. Text is not translated

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/117973533-7058e280-b324-11eb-8f88-15cfe2b90753.png)

## Expected result
Translated text

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.25.57 x64 beta Build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Miyayes

**Comment by deeppandya** [comment]
@srirambv  is this issue relevant ? Should i look into it ?

**Comment by srirambv** [comment]
Sorry for the delay missed the notification but this is fixed now
![image](https://user-images.githubusercontent.com/17010094/143252415-7d986fa4-8b0c-4efa-b3bc-58dde73112e3.png)
