### ISSUE TITLE
Won't show Verified Creator status for Github creators if Private Browsing (Incognito) is launched first

### ISSUE THREAD

**Issue by sgornick** [brave/brave-browser#15776]
## Description 
Normally, when I load a GitHub profile page, I can click the Brave Rewards triangle to bring up the creator's Brave Creator's profile info (i.e., name, status -- "Not yet verified" / "Brave Verified Creator", option to Send A Tip, etc.).  I get different behavior depending on whether I had launched Brave in Private mode (New Incognito Window) first before launching Brave in normal mode (New Window).

Simply having Brave running in Incognito mode first seems to interfere for the normal (non-Incognito) Brave browser window that is launched later, and then in that normal Brave browser windo, no Brave Creator's info will appear -- at least not for a GitHub profile.

## Steps to Reproduce

   1. Launch Brave in Private mode (right-click on Brave launcher icon, select New Incognito Windows).
   2. Launch another Brave browser (right-click on Brave launcher icon, select New Window).
   3. Enter in the Address bar: https://github.com/brave  (or URL for any Github account profile)
   4. Click on Brave Rewards triangle.

## Actual result:
No Brave Creator info.
![2021-05-12_07-55](https://user-images.githubusercontent.com/24884/117978520-94ea9580-b2f7-11eb-87dd-abd7346a5ab8.png)

## Expected result:
Brave Creator info.
![2021-05-12_07-57](https://user-images.githubusercontent.com/24884/117978661-bcd9f900-b2f7-11eb-97d2-d0ce97a088aa.png)
(I was able to obtain this image by closing both Brave browser windows, and then launching ONLY  Brave once, and in normal mode (right-click on Brave launcher icon, select New Window).

## Reproduces how often: 
Consistently

## Brave version (brave://version info)
Brave | 1.24.84 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Linux

## Miscellaneous Information:
I tried the same thing with a Twitter account, and am not seeing creator info at all. But then in troubleshooting the Github issue, there was at least once where I saw creator info for the Twitter account.  So I don't know whether to combine the Brave Creator info for a Twitter profile (intermittent), with what I'm reporting for this Github Issue. But wanted to mention that as well in case is useful in troubleshooting.  It's plausible any fix for the issue showing for the Github profile would also remedy the issue I am having also when showing for a Twitter profile.

**Comment by Miyayes** [comment]
Check if this persists even after Rewards panel 2.0 https://github.com/brave/brave-browser/issues/14602.

**Comment by sgornick** [comment]
I haven't monitored this issue since reporting it (in Brave v1.24.84).

Today, checking using Brave v1.30.87, I cannot get the issue to recur.

So if Rewards panel 2.0 is first getting merged in v1.31.x, this would have been fixed prior to Rewards panel 2.0 (or, at least, I do not have an explanation as to why this was occurring consistently with v1.24.84 but now cannot get the problem to recur with v1.30.87 ).

So I am closing this issue, with this comment.
