### ISSUE TITLE
`npm run pylint` uses pylint from PATH instead of depot_tools

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#15778]
Currently, `npm run pylint` triggers a bash shell script to run pylint.

This
* doesn't work on windows locally 
* uses pylint from PATH, which on CI results in invoking python3's version of pylint.

**Comment by kjozwiak** [comment]
Adding missing `1.27.x` milestone as this landed in `master` which is on `1.27.x` via https://github.com/brave/brave-core/commit/5f5c81251f43d190020fc8d2bc3d902bba03e494.
