### ISSUE TITLE
Crash at BraveRenderViewContextMenu::BuildIPFSMenu

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#15785]
https://brave.sp.backtrace.io/p/brave/explore?time=month&filters=((callstack.functions%2Ccontains%2CBraveRenderViewContextMenu)%2C_deleted%3D0%2C(ver%2Cregex%2C%2290.*%22)%2Cptype%3Dbrowser)&aggregations=((channel%2Cdistribution%2C3)%2C(ver%2Cdistribution%2C3)%2C(callstack%2Chead))&

```
[ 00 ] std::__1::vector<ui::SimpleMenuModel::Item, std::__1::allocator<ui::SimpleMenuModel::Item> >::__swap_out_circular_buffer(std::__1::__split_buffer<ui::SimpleMenuModel::Item, std::__1::allocator<ui::SimpleMenuModel::Item>&>&, ui::SimpleMenuModel::Item*)
[ 01 ] std::__1::vector<ui::SimpleMenuModel::Item, std::__1::allocator<ui::SimpleMenuModel::Item> >::insert(std::__1::__wrap_iter<ui::SimpleMenuModel::Item const*>, ui::SimpleMenuModel::Item&&)
[ 02 ] ui::SimpleMenuModel::InsertItemAt(int, int, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&)
[ 03 ] ui::SimpleMenuModel::InsertItemWithStringIdAt(int, int, int)
[ 04 ] BraveRenderViewContextMenu::BuildIPFSMenu()
[ 05 ] BraveRenderViewContextMenu::InitMenu()
[ 06 ] RenderViewContextMenuBase::Init()
[ 07 ] ChromeWebContentsViewDelegateMac::BuildMenu(content::WebContents*, content::ContextMenuParams const&)
[ 08 ] ChromeWebContentsViewDelegateMac::ShowContextMenu(content::RenderFrameHost*, content::ContextMenuParams const&)
[ 09 ] content::WebContentsImpl::ShowContextMenu(content::RenderFrameHost*, mojo::PendingAssociatedRemote<blink::mojom::ContextMenuClient>, content::ContextMenuParams const&)
[ 10 ] content::RenderFrameHostImpl::ShowContextMenu(mojo::PendingAssociatedRemote<blink::mojom::ContextMenuClient>, blink::UntrustworthyContextMenuParams const&)

```

**Comment by iefremov** [comment]
cc @spylogsster @bbondy

**Comment by bbondy** [comment]
If this is beyond Nightly we'll want to uplift this one to wherever the fix is needed to btw @spylogsster

**Comment by goodov** [comment]
might be fixed:
https://github.com/brave/brave-core/commit/2c992fda0c22c07f258a97541fcbd13421ebffd0#diff-98e5cd23cdc68113dd56309d734c30615eee2597d8fe699ff51d0637262dfce6R240-R241

**Comment by iefremov** [comment]
> might be fixed:
brave/brave-core@2c992fd#diff-98e5cd23cdc68113dd56309d734c30615eee2597d8fe699ff51d0637262dfce6R240-R241

great, thanks @goodov 

It seems it is easily reproducible by (1) install IPFS, configure local node (2) open devtools (3) select any text and right-click. 
I reproed in current Beta, so we may want to uplift (cc @bbondy )
