### ISSUE TITLE
chrome.downloads.download fails around filename determination

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#15781]
## Description 
The `chrome.downloads.download` method doesn't appear to work as expected in Brave.

## Steps to Reproduce
Create a new directory with the following files:

manifest.json

```js
{
    "name": "chrome.downloads.download test",
    "version": "0.0.0.1",
    "manifest_version": 3,
    "permissions": [
        "downloads"
    ],
    "background": {
        "service_worker": "background.js"
    }
}
```

background.js

```js
chrome.runtime.onInstalled.addListener(() => {
    const url = "https://brave.com/static-assets/images/brave-og.png";
    chrome.downloads.download({ url }, downloadId => {
        console.log(`Download ID is ${downloadId}`);
    });
});
```

Navigate to brave://extensions/ and enable _Developer Mode_. Then select _Load unpacked_, and find the extension directory with the contents above.

## Actual result:
Nothing happens. No download is initiated, but a download ID is generated and returned.

Brave Nightly 1.26.11
![brave-downloads](https://user-images.githubusercontent.com/815158/117991437-aa65bc80-b303-11eb-856b-7155859affe5.gif)

## Expected result:
A download should automatically be initiated when the extension is loaded, or refreshed. Clicking the "service worker" link should also reveal a generated download ID in the console.

Chrome Canary 92.0.4505.0
![chrome-downloads](https://user-images.githubusercontent.com/815158/117990988-46db8f00-b303-11eb-8e59-61589d563d15.gif)

## Reproduces how often: 
Consistently.

## Brave version (brave://version info)
1.26.11

## Version/Channel Information:
- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:
By hooking into the downloads lifecycle events, we can see that Brave stops around filename determination, whereas Chrome resolves a full path and filename and proceeds with the download:

```js
chrome.downloads.onCreated.addListener( item => {
    console.log( "onCreated", item );
});

chrome.downloads.onChanged.addListener( item => {
    console.log( "onChanged", item );
});

chrome.downloads.onDeterminingFilename.addListener( item => {
    console.log( "onDeterminingFilename", item );
});

chrome.downloads.onErased.addListener( item => {
    console.log( "onErased", item );
});
```

![image](https://user-images.githubusercontent.com/815158/117991922-1ba56f80-b304-11eb-90ea-86309dc986a0.png)

![image](https://user-images.githubusercontent.com/815158/117992166-527b8580-b304-11eb-8f9d-1a2a52770261.png)

**Comment by jonathansampson** [comment]
@rebron No change in v1.33.10.

**Comment by jonathansampson** [comment]
This appears to be working in version 1.44.105 Chromium: 106.0.5249.91 (Official Build) (64-bit)!

**Comment by SecretShell** [comment]
I was using Brave v1.39.111
I had to turn off "Ask where to save each file before downloading"

![image](https://github.com/brave/brave-browser/assets/98637285/495eba52-0f40-45f2-83f9-599b5cdcd9c7)
