### ISSUE TITLE
Brave Ads crash in `brave_ads::RunDBTransactionOnFileTaskRunner`

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#15783]
Similar to https://github.com/brave/brave-browser/issues/15779

https://brave.sp.backtrace.io/p/brave/debug?time=month&filters=((callstack.functions%2Ccontains%2CRunDBTransactionOnFileTaskRunner)%2C_deleted%3D0%2C(ver%2Cregex%2C%2290%7C91.*%22)%2Cptype%3Dbrowser)&debug=(%221090445%22,0,0)

```
[ 00 ] chrome_sqlite3_file_control
[ 01 ] <name omitted>
[ 02 ] <name omitted>
[ 03 ] <name omitted>
[ 04 ] <name omitted>
[ 05 ] <name omitted>
[ 06 ] <name omitted>
[ 07 ] brave_ads::RunDBTransactionOnFileTaskRunner(mojo::StructPtr<ads_database::mojom::DBTransaction>, ads::Database*)
[ 08 ] base::internal::Invoker<base::internal::BindState<mojo::StructPtr<ads_database::mojom::DBCommandResponse> (*)(mojo::StructPtr<ads_database::mojom::DBTransaction>, ads::Database*), mojo::StructPtr<ads_database::mojom::DBTransaction>, ads::Database*>, mojo::StructPtr<ads_database::mojom::DBCommandResponse> ()>::RunOnce(base::internal::BindStateBase*)
[ 09 ] void base::internal::ReturnAsParamAdapter<mojo::StructPtr<ads_database::mojom::DBCommandResponse> >(base::OnceCallback<mojo::StructPtr<ads_database::mojom::DBCommandResponse> ()>, std::__1::unique_ptr<mojo::StructPtr<ads_database::mojom::DBCommandResponse>, std::__1::default_delete<mojo::StructPtr<ads_database::mojom::DBCommandResponse> > >*)
[ 10 ] base::internal::Invoker<base::internal::BindState<void (*)(base::OnceCallback<mojo::StructPtr<ads_database::mojom::DBCommandResponse> ()>, std::__1::unique_ptr<mojo::StructPtr<ads_database::mojom::DBCommandResponse>, std::__1::default_delete<mojo::StructPtr<ads_database::mojom::DBCommandResponse> > >*), base::OnceCallback<mojo::StructPtr<ads_database::mojom::DBCommandResponse> ()>, std::__1::unique_ptr<mojo::StructPtr<ads_database::mojom::DBCommandResponse>, std::__1::default_delete<mojo::StructPtr<ads_database::mojom::DBCommandResponse> > >*>, void ()>::RunOnce(base::internal::BindStateBase*)
[ 11 ] base::(anonymous namespace)::PostTaskAndReplyRelay::RunTaskAndPostReply(base::(anonymous namespace)::PostTaskAndReplyRelay)

```

**Comment by iefremov** [comment]
cc @tmancey @emerick @zenparsing

**Comment by stephendonner** [comment]
**Verified `PASSED`** using 


Brave | 1.30.45 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 11.5.2 (Build 20G95)

### Steps:
* clean profile
* launched Brave
* opened a new-tab page
* opened `brave://rewards` and clicked on `Start using Rewards`
* checked for `Successfully initialized ads` message in Logs

Confirmed `[11588:259:0824/150900.613336:VERBOSE1:ads_impl.cc(621)] Successfully initialized ads`

* Turned off then turned Ads back on, from settings

**Shut down:**

`[11588:259:0824/151648.806022:VERBOSE1:ads_service_impl.cc(1839)] P2A histograms suspended`
`[11588:259:0824/151648.806099:VERBOSE1:ads_service_impl.cc(714)] Shutting down ads
[11588:259:0824/151648.809461:VERBOSE1:ads_service_impl.cc(730)] Successfully shutdown ads`

**Re-enabled ads:**

`[11588:259:0824/151815.095791:VERBOSE3:client.cc(547)] Loading client state
[11588:259:0824/151815.096346:VERBOSE3:client.cc(572)] Successfully loaded client state
[11588:259:0824/151815.096401:VERBOSE3:confirmations_state.cc(68)] Loading confirmations state
[11588:259:0824/151815.097259:VERBOSE3:confirmations_state.cc(88)] Successfully loaded confirmations state
[11588:259:0824/151815.097315:VERBOSE3:ad_notifications.cc(398)] Loading ad notifications state
[11588:259:0824/151815.097831:VERBOSE3:ad_notifications.cc(423)] Successfully loaded ad notifications state
[11588:259:0824/151815.097882:VERBOSE1:ads_impl.cc(621)] Successfully initialized ads`

* checked for another `Successfully initialized ads` appearing in Logs

Confirmed `[11588:259:0824/151054.342432:VERBOSE1:ads_impl.cc(621)] Successfully initialized ads`

Didn't observe any hangs or crashes.

**Comment by btlechowski** [comment]
Best to test the crash on all platforms
