### ISSUE TITLE
[Android] Hide Tab Groups bottom controls in scrolling mode

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#15789]
## Description 
When bottom controls are disappeared on scrolling web page, we shouldn't show Tab Groups controls when click `Open in new tab in group` from context menu.

## Steps to reproduce 

   1. Go to some scrollable web site (like cnn.com).
   2. Scroll it down till bottom controls disappear.
   3. `Open in new tab in group` from context menu on any link.

## Actual result 
Tab Groups controls are visible.

## Expected result
Tab Groups controls are not visible.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 126.46 x64 Beta build
- Verified test plan from issue description
- Verified opening a new tab in group when bottom toolbar is hidden, doesn't show the tab group bar or bottom toolbar
