### ISSUE TITLE
Ads control center: "I'm a Brave Rewards user, let me disable specific ad units" (feature request)

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#15792]
## Description 

Currently, if I want to earn from Sponsored Images, I have to enable all ad units on brave://rewards. 

We've received several reports from users that would like to still be able to earn from SI, but would prefer not to receive push notification ads. 

Ideally, if we could provide some finer grained ad unit level options for users to disable/enable each ad unit from brave://rewards, that would resolve. 

For example, I *can* enable Ads, and then disable Sponsored Images. 

But, I *cannot* enable Ads, and disable notifications (allowing me to only earn from Sponsored Images). 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Assigning to @Miyayes for Rewards backlog - cc: @jsecretan @bsclifton @BrendanEich for visibility.

**Comment by Miyayes** [comment]
We could add some toggles here: 
![image](https://user-images.githubusercontent.com/11497541/118020380-03474c00-b328-11eb-8e40-cfb11e9131e8.png)

**Comment by bsclifton** [comment]
@Miyayes I think @lukemulks is referring the the ad type; so right now, we just have notifications and sponsored images. But we could potentially have more (and I could be missing one). Maybe NTP sponsored image setting should be there in the same area?

Related issues:
https://github.com/brave/brave-browser/issues/11889
https://github.com/brave/brave-browser/issues/11018

**Comment by Miyayes** [comment]
I was imagining something like 2 checkboxes or toggles in the Ads Settings panel:

- [ ] Brave Ads push notifications
- [ ] New Tab Page sponsored images

"New Tab Page sponsored images" toggle would be tied to the setting here too: 
![image](https://user-images.githubusercontent.com/11497541/118037695-309df500-b33c-11eb-915c-2841c7f0caee.png)

**Comment by Miyayes** [comment]
Updates: Users can now disable notification ads but retain sponsored images by making the ad frequency for notifications 0 per hour.

However, we should still introduce a central place where all the toggles for all the possible ad units appear, and users can easily toggle them on or off. cc: @minkyeongshin to think about.

**Comment by Miyayes** [comment]
**This will be implemented via this https://github.com/brave/brave-browser/issues/30637.** Exciting!

**Comment by lukemulks** [comment]
Excellent work with getting this tuned up and shipped. Far exceeds initial expectations in the latest version. ♥️
