### ISSUE TITLE
Add FTX widget

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#15790]
## Description 

Add FTX as a widget to the New Tab page to allow for viewing markets and trading crypto on the FTX platform.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on  macOS</summary>
<br>

Verified using the following build

Brave | 1.26.64 Chromium: 91.0.4472.114&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | `4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}`
OS | macOS Version 10.15.7 (Build 19H114)

**Clean Install**
- Verified on a clean install, FTX widget is shown and is at the last position
![image](https://user-images.githubusercontent.com/17010094/122725271-b7fc5380-d26c-11eb-950e-6c53e77e48b9.png)

- Verified spinner is shown when widget is being initialized
![image](https://user-images.githubusercontent.com/17010094/122728982-943b0c80-d270-11eb-974b-091f4b5661ed.png)

- Verified after widget initializes, defaults to `.us` 
![image](https://user-images.githubusercontent.com/17010094/122725357-cfd3d780-d26c-11eb-8978-2341476afa72.png)

- Verified `View future markets` loads the market view and adds a back button next to widget menu
![image](https://user-images.githubusercontent.com/17010094/122726200-aebfb680-d26d-11eb-9730-281177935fdd.png)

- Verified able to connect to widget successfully
![image](https://user-images.githubusercontent.com/17010094/122724358-c26a1d80-d26b-11eb-825e-b7509c20849e.png)

- Verified summary view is hidden by default. Clicking on the show/hide button shows the balance and tokens list
![image](https://user-images.githubusercontent.com/17010094/122726675-21c92d00-d26e-11eb-9fc1-32444e10cf3f.png)

- Verified convert tab lists all available tokens with balance that can be used to converted 
![image](https://user-images.githubusercontent.com/17010094/122726987-753b7b00-d26e-11eb-8bec-4cabcacc131c.png)

- Verified selecting a token shows market asset details
![image](https://user-images.githubusercontent.com/17010094/122727338-d7947b80-d26e-11eb-8c2c-4eda373d65ad.png)

- Verified sad smiley is shown in market details view when network is not able to fetch the value
![image](https://user-images.githubusercontent.com/17010094/122727509-00b50c00-d26f-11eb-8d97-aa2fb2df7281.png)

- Verified when quote is loading the spinner icon is shown
![image](https://user-images.githubusercontent.com/17010094/122728296-e4fe3580-d26f-11eb-9f70-df43cb13180e.png)

- Verified quote is shown before confirmation of converting assets
![image](https://user-images.githubusercontent.com/17010094/122727953-820c9e80-d26f-11eb-9509-7c6fc4ec973c.png)

- Verified upon successful conversion confirmation message is shown
![image](https://user-images.githubusercontent.com/17010094/122728511-1f67d280-d270-11eb-9165-110780891dd5.png)

- Verified new assets are automatically added in summary view when a successful conversion is done

- Verified when there is no balance convert tab & summary tab shows message to add funds

![image](https://user-images.githubusercontent.com/17010094/122728782-5f2eba00-d270-11eb-80e9-f06ad71d72b3.png) | ![image](https://user-images.githubusercontent.com/17010094/122739399-d8330f00-d27a-11eb-8de1-db8a43937df7.png)
-- | --

- Verified when network disconnects and try to convert an asset from quote, shows zero balance message
![image](https://user-images.githubusercontent.com/17010094/122733099-c5b5d700-d274-11eb-942e-3fe493174698.png)

- Verified disconnecting the widget works via widget menu 
- Verified after disconnect widget goes back to default state and defaults to `.us`
- Verified click on connect tries to re-authenticate
- Verified able to disconnect the widget by hiding the widget either via menu or via edit cards window
- Verified when quote expires, widget goes back to convert view
- Verified widget auto-updates every 30sec. 
- Verified when widget is authenticated and network disconnected, summary shows zero balance message, reconnecting to network after 30sec auto updates the widget and shows the balance 
- Verified widget is not shown on both clean install or upgrade for countries mentioned in https://github.com/brave/brave-core/blob/1995c8073ea0bac88db06d788f7b648bd19b6dd0/components/ftx/browser/regions.h#L15

**Upgrade**
- Verified if cards are disabled, upon upgrade FTX widget is not shown
- Verified if any of the cards are enabled on NTP, FTX widget is also shown and is at the back of the stack

- Encountered #16530
</details>

-----------

<details>
<summary>Verification passed on Linux</summary>
<br>

Verified using the following build

Brave | 1.26.64 Chromium: 91.0.4472.114&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | `4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}`
OS | Linux

**Clean Install**
- Verified on a clean install, FTX widget is shown and is at the last position
![image](https://user-images.githubusercontent.com/17010094/122735605-19292480-d277-11eb-8bf8-cc69db88c8cd.png)

- Verified spinner is shown when widget is being initialized
![image](https://user-images.githubusercontent.com/17010094/122736324-d156cd00-d277-11eb-83f9-aca8130c983f.png)

- Verified after widget initializes, defaults to `.us` 
![image](https://user-images.githubusercontent.com/17010094/122736082-8ccb3180-d277-11eb-973a-1bbbc7dcc4f1.png)

- Verified `View future markets` loads the market view and adds a back button next to widget menu
![image](https://user-images.githubusercontent.com/17010094/122736324-d156cd00-d277-11eb-83f9-aca8130c983f.png)

- Verified able to connect to widget successfully
![image](https://user-images.githubusercontent.com/17010094/122736969-7a9dc300-d278-11eb-956a-15839a4ae4c0.png)

- Verified summary view is hidden by default. Clicking on the show/hide button shows the balance and tokens list
![image](https://user-images.githubusercontent.com/17010094/122737427-eda73980-d278-11eb-9204-3d7d0bb69739.png)

- Verified convert tab lists all available tokens with balance that can be used to converted 
![image](https://user-images.githubusercontent.com/17010094/122737583-17f8f700-d279-11eb-848c-98270dd5c0b6.png)

- Verified selecting a token shows market asset details
![image](https://user-images.githubusercontent.com/17010094/122737716-4080f100-d279-11eb-87a3-deb328bd10f1.png)

- Verified sad smiley is shown in market details view when network is not able to fetch the value
![image](https://user-images.githubusercontent.com/17010094/122737807-55f61b00-d279-11eb-9242-6f0431f8ffe2.png)

- Verified when quote is loading the spinner icon is shown
![image](https://user-images.githubusercontent.com/17010094/122738172-a3728800-d279-11eb-9593-50126cacd553.png)

- Verified quote is shown before confirmation of converting assets
![image](https://user-images.githubusercontent.com/17010094/122738323-cac95500-d279-11eb-9eee-1bdad4aca6b7.png)

- Verified upon successful conversion confirmation message is shown
![image](https://user-images.githubusercontent.com/17010094/122738774-33183680-d27a-11eb-85c7-274abc0af19b.png)

- Verified new assets are automatically added in summary view when a successful conversion is done

- Verified when there is no balance convert tab & summary tab shows message to add funds

![image](https://user-images.githubusercontent.com/17010094/122739001-6e1a6a00-d27a-11eb-855f-a87487b87100.png) | ![image](https://user-images.githubusercontent.com/17010094/122739045-7d011c80-d27a-11eb-995c-7e9b50558265.png)
-- | --

- Verified when network disconnects and try to convert an asset from quote, shows zero balance message
![image](https://user-images.githubusercontent.com/17010094/122739001-6e1a6a00-d27a-11eb-855f-a87487b87100.png)


- Verified disconnecting the widget works via widget menu 
- Verified after disconnect widget goes back to default state and defaults to `.us`
- Verified click on connect tries to re-authenticate
- Verified able to disconnect the widget by hiding the widget either via menu or via edit cards window
- Verified when quote expires, widget goes back to convert view
- Verified widget auto-updates every 30sec. 
- Verified when widget is authenticated and network disconnected, summary shows zero balance message, reconnecting to network after 30sec auto updates the widget and shows the balance 
- Verified widget is not shown on both clean install or upgrade for countries mentioned in https://github.com/brave/brave-core/blob/1995c8073ea0bac88db06d788f7b648bd19b6dd0/components/ftx/browser/regions.h#L15

**Upgrade**
- Verified if cards are disabled, upon upgrade FTX widget is not shown
- Verified if any of the cards are enabled on NTP, FTX widget is also shown and is at the back of the stack

- Encountered #16530
</details>

-----------

<details>
<summary>Verification passed on Windows 10</summary>
<br>

Verified using the following build

Brave | 1.26.64 Chromium: 91.0.4472.114&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | `4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}`
OS | Windows 10 OS Version 2009 (Build 19042.1052)

**Clean Install**
- Verified on a clean install, FTX widget is shown and is at the last position
![image](https://user-images.githubusercontent.com/17010094/122741535-f568dd00-d27c-11eb-95ab-1e4943049e77.png)

- Verified spinner is shown when widget is being initialized
![image](https://user-images.githubusercontent.com/17010094/122741684-1a5d5000-d27d-11eb-83b3-b0fa7ad0e765.png)

- Verified after widget initializes, defaults to `.us` 
![image](https://user-images.githubusercontent.com/17010094/122741426-db2eff00-d27c-11eb-932f-15c0744d328b.png)

- Verified `View future markets` loads the market view and adds a back button next to widget menu
![image](https://user-images.githubusercontent.com/17010094/122741793-39f47880-d27d-11eb-95a2-c250187c2e69.png)

- Verified able to connect to widget successfully
![image](https://user-images.githubusercontent.com/17010094/122742007-72945200-d27d-11eb-9f90-4f1332d9a240.png)

- Verified summary view is hidden by default. Clicking on the show/hide button shows the balance and tokens list
![image](https://user-images.githubusercontent.com/17010094/122742166-95266b00-d27d-11eb-82a5-238e281b9458.png)

- Verified convert tab lists all available tokens with balance that can be used to converted 
![image](https://user-images.githubusercontent.com/17010094/122742253-a96a6800-d27d-11eb-9623-6b33dd4a7e39.png)

- Verified selecting a token shows market asset details
![image](https://user-images.githubusercontent.com/17010094/122742385-cb63ea80-d27d-11eb-938c-27061c20e753.png)

- Verified sad smiley is shown in market details view when network is not able to fetch the value
![image](https://user-images.githubusercontent.com/17010094/122742533-f3534e00-d27d-11eb-854d-6c83cd4a2539.png)

- Verified when quote is loading the spinner icon is shown
![image](https://user-images.githubusercontent.com/17010094/122761816-8c8d5f00-d294-11eb-90bb-d32c0fddd5e6.png)

- Verified quote is shown before confirmation of converting assets
![image](https://user-images.githubusercontent.com/17010094/122761915-ac248780-d294-11eb-9859-0cdecd44671f.png)

- Verified upon successful conversion confirmation message is shown
![image](https://user-images.githubusercontent.com/17010094/122761989-c3637500-d294-11eb-881d-2158f1fcd6f2.png)

- Verified new assets are automatically added in summary view when a successful conversion is done

- Verified when there is no balance convert tab and summary tab shows message to add funds
- 
![image](https://user-images.githubusercontent.com/17010094/122762170-f0178c80-d294-11eb-8aae-c6f24413b66a.png) | ![image](https://user-images.githubusercontent.com/17010094/122762246-06254d00-d295-11eb-8ea4-f59144411008.png)
-- | --

- Verified when network disconnects and try to convert an asset from quote, shows zero balance message
![image](https://user-images.githubusercontent.com/17010094/122762504-4ab0e880-d295-11eb-9499-698dc0550b3b.png)

- Verified disconnecting the widget works via widget menu 
- Verified after disconnect widget goes back to default state and defaults to `.us`
- Verified click on connect tries to re-authenticate
- Verified able to disconnect the widget by hiding the widget either via menu or via edit cards window
- Verified when quote expires, widget goes back to convert view
- Verified widget auto-updates every 30sec. 
- Verified when widget is authenticated and network disconnected, summary shows zero balance message, reconnecting to network after 30sec auto updates the widget and shows the balance 
- Verified widget is not shown on both clean install or upgrade for countries mentioned in https://github.com/brave/brave-core/blob/1995c8073ea0bac88db06d788f7b648bd19b6dd0/components/ftx/browser/regions.h#L15

**Upgrade**
- Verified if cards are disabled, upon upgrade FTX widget is not shown
- Verified if any of the cards are enabled on NTP, FTX widget is also shown and is at the back of the stack

- Encountered #16530
</details>
