### ISSUE TITLE
Brave crashes frequently

### ISSUE THREAD

**Issue by Sh1d0w** [brave/brave-browser#1579]
I am currently using dev build 0.56.4

While I use it for a daily usage, I find that it crashes frequently. This also was happening on 0.56.2. 

I wasn't able to observe a pattern that reproduces it 100% - sometimes when I have 7-8 tabs open, and open a new one, type google.com then type a search string and hit enter it crashes.

Sometimes when I close a lot of tabs with CMD+W again crashes.

If I can provide some useful information like log files or stack traces which does not have sensitive information let me know I will do in order to help to identify the issue.

It is very annoying btw, as it occurs constantly.

**Comment by NejcZdovc** [comment]
@Sh1d0w could this one be the same https://github.com/brave/brave-browser/issues/1442?

**Comment by Sh1d0w** [comment]
@NejcZdovc I don't think it is the same as it crashes after I've opened google.com and hit search inside the google's input search par inside the page, not in the address bar.

Also crashed several times when I've been closing multiple tabs with CMD+W

**Comment by NejcZdovc** [comment]
oh it's inside google search, yeah this one seams different. Could you please send us some crash reports (chrome://crashes)?

Please past `Uploaded Crash Report ID` in this issue so that we can know exactly which one is related to this issue. Thank you

**Comment by Sh1d0w** [comment]
@NejcZdovc Sure, here are the most recent ones:

Local Crash ID 13e74d6d-0f08-49b4-bd20-ebb71d239272
Crash report captured on Monday, 15 October 2018 at 12:38:23 (upload requested by user, not yet uploaded)

Local Crash ID 97266974-e1fd-42c7-8a98-68a0720bb47a
Crash report captured on Monday, 15 October 2018 at 11:37:31 (upload requested by user, not yet uploaded)

Local Crash ID 30110cda-b0af-4084-81b2-f363814debcc
Crash report captured on Monday, 15 October 2018 at 06:46:59 (upload requested by user, not yet uploaded)

Local Crash ID 04344366-f476-4e3e-be3e-9fccd8ce0ed7
Crash report captured on Sunday, 14 October 2018 at 18:55:15 (upload requested by user, not yet uploaded)

**Comment by Sh1d0w** [comment]
@NejcZdovc 

No problems.

Here are the report ids:

Uploaded Crash Report ID 3d4f796ace2e353e (Local Crash ID: 13e74d6d-0f08-49b4-bd20-ebb71d239272)
Crash report captured on Monday, 15 October 2018 at 12:38:23, uploaded on Monday, 15 October 2018 at 13:27:40

Provide additional details.

Uploaded Crash Report ID 71d99ba5e5fd10ff (Local Crash ID: 97266974-e1fd-42c7-8a98-68a0720bb47a)
Crash report captured on Monday, 15 October 2018 at 11:37:31, uploaded on Monday, 15 October 2018 at 13:27:41

Provide additional details.

Uploaded Crash Report ID 70947b12ec53d64d (Local Crash ID: 30110cda-b0af-4084-81b2-f363814debcc)
Crash report captured on Monday, 15 October 2018 at 06:46:59, uploaded on Monday, 15 October 2018 at 13:27:40

Provide additional details.

Uploaded Crash Report ID 2fb80ef5efd2af1a (Local Crash ID: 04344366-f476-4e3e-be3e-9fccd8ce0ed7)
Crash report captured on Sunday, 14 October 2018 at 18:55:15, uploaded on Monday, 15 October 2018 at 13:27:40

Provide additional details.

**Comment by jmahhh** [comment]
Same:

Uploaded Crash Report ID f5a338f109e2a579 (Local Crash ID: 1a730ec2-09e0-4fd2-b8fc-b84015a45260)
Crash report captured on Monday, 15 October 2018 at 21:57:49, uploaded on Monday, 15 October 2018 at 22:13:53

Provide additional details.

Uploaded Crash Report ID aecc01ae65e6be04 (Local Crash ID: 6acc3d69-aead-4cbe-8d45-ecdf4bae66f5)
Crash report captured on Monday, 15 October 2018 at 19:32:30, uploaded on Monday, 15 October 2018 at 22:13:54

Provide additional details.

Uploaded Crash Report ID e45d7fc0189b70e0 (Local Crash ID: fc7ad972-0be7-4299-86d9-81016780c496)
Crash report captured on Monday, 15 October 2018 at 19:17:45, uploaded on Monday, 15 October 2018 at 22:13:52

Provide additional details.

Uploaded Crash Report ID 927c5b67eef8718a (Local Crash ID: 66a5ddab-21aa-4a64-84f8-19268f3ad088)
Crash report captured on Saturday, 13 October 2018 at 11:15:41, uploaded on Monday, 15 October 2018 at 22:13:51

Provide additional details.

**Comment by dustinaux** [comment]
Although I've had other pages randomly crash I can consistently produce an immediate crash on 0.56.4 by going to https://www.google.com/finance and viewing any stock quote, whether by search or clicking one in my "watchlist."

Doing the same in incognito mode does not crash though. So it may be related to the user data somehow.

Local Crash ID 509fb069-ef4b-4791-b772-41b5918dc0d3

**Comment by wowsuchnamaste** [comment]
Closing tabs with either ctrl+w or clicking the tab's x crashes brave _if the tab has loaded a google page_. So far, I've experienced this exclusively with gmail and google calendar. I'm on On version 0.56.4, Ubuntu 18.04 4.15.0 x86_64. Have not tried incognito mode.

**Comment by bbondy** [comment]
Please try again with 0.55.14 beta or  0.56.5 (not yet released) dev. I think it should be fixed.
