### ISSUE TITLE
Text change for Unstoppable Domains support and not just ENS in wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#15797]
Please change ENS here to domain since we support ENS and Unstoppable Domains there now.

<img width="1930" alt="Crypto+Wallets+2021-04-17+02-35-55" src="https://user-images.githubusercontent.com/831718/118034394-ef0b4b00-b337-11eb-98e5-ddb457ffa58e.png">

cc @onyb

**Comment by onyb** [comment]
Draft PR available in https://github.com/brave/ethereum-remote-client/pull/238. Needs a rebase before merging, once https://github.com/brave/ethereum-remote-client/pull/236 goes in.

By the way, we should probably follow up with Unstoppable Domains to indicate that Brave supports it natively.

<p align="center">
  <img width="640" src="https://user-images.githubusercontent.com/3684187/118118785-ae6e0900-b3ed-11eb-9b02-e6388c722f68.png">
</p>

**Comment by bbondy** [comment]
Looks like it's already updated. I think they were probably just waiting for today's press

<img width="865" alt="Screen Shot 2021-05-13 at 9 51 14 AM" src="https://user-images.githubusercontent.com/831718/118135234-c5eac900-b3d0-11eb-810e-6f05ebbd2bcf.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)
-- | --
Revision | `af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}`
OS | Windows 10 OS Version 2009 (Build 19042.1052)
Component | `1.0.29 Dev`

- Verified ENS is replaced by domain
![image](https://user-images.githubusercontent.com/17010094/122388808-26d56600-cf68-11eb-81b2-39f2406e9170.png)

------

Verification passed on 

Brave | 1.27.69 Chromium: 91.0.4472.106 (Official Build) beta (64-bit)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | Linux
Component | `1.0.29 Dev`

- Verified ENS is replaced by domain
![image](https://user-images.githubusercontent.com/17010094/122390354-ce06cd00-cf69-11eb-8918-ff6782e7d6d4.png)

------

Verification passed on 

Brave | 1.27.62 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | `af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.29 Dev`

- Verified ENS is replaced by domain
![image](https://user-images.githubusercontent.com/17010094/122389885-520c8500-cf69-11eb-8412-b106a9cbcffe.png)
