### ISSUE TITLE
tab hover cards with C91

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15795]
## Description 

Noticed on Nightly with C91 version that I have tab hover cards again. 

I think Windows on current release has these, but macOS does not. 

@rebron also noted that the flag present on C90 builds (`brave://flags/#tab-hover-cards`) is not available on C91 builds.

## Steps to Reproduce

   1. Clean profile 1.26.18 (or C91 version)
   2. Hover over tab
   3. See hover card like below

## Actual result:

<img width="1037" alt="Screen Shot 2021-05-12 at 14 56 18" src="https://user-images.githubusercontent.com/28145373/118029599-50c8b680-b332-11eb-8e5b-497e4416d96e.png">

## Expected result:

no hover card

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (x86_64)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | macOS Version 10.15.7 (Build 19H1030)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa

**Comment by bsclifton** [comment]
Let's keep these in place - @rebron has suggested maybe capturing a setting where folks can turn this off

**Comment by ask1234560** [comment]
Hello, i am facing the same issue.
The version is `1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)`
Distro `Arch linux`
I had disabled the following flags also.
```
omnibox-refined-focus-state
tab-hover-card-images
```
No effect, how to solve the issue.

![Screenshot_from_2021-05-31_21:21:39](https://user-images.githubusercontent.com/25929911/120217685-58ef8400-c256-11eb-8c82-93f6e582b2b0.png)

**Comment by bsclifton** [comment]
@ask1234560 can you please subscribe to https://github.com/brave/brave-browser/issues/9906 for updates? You can leave a comment there too. Thanks! 😄
