### ISSUE TITLE
Missing tooltip for sidebar icon when in (show) on-click mode for Sidebar

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15806]
## Description 

Missing tooltip for sidebar icon when in (show) on-click mode for Sidebar

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. set `brave://flags/#sidebar` to `Enabled` and restart
   4. mouse over to the Sidebar panel on the left
   5. context-click an empty region and choose `On click` from `Show Sidebar`
   6. mouse over again to the now-hidden Sidebar panel, and hover over the window icon

## Actual result:

There's no tooltip

![no-tooltip](https://user-images.githubusercontent.com/387249/118049820-29beb480-b333-11eb-9818-445d5b7df202.gif)

## Expected result:
There should be a tooltip, on hover

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (x86_64)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

/cc @simonhong @karenkliu

**Comment by simonhong** [comment]
@stephendonner Can you check again? First tooltip is shown in some delay(maybe 1s).
I can see tooltips on hover with nightly(on mac/Win10)

**Comment by stephendonner** [comment]
> @stephendonner Can you check again? First tooltip is shown in some delay(maybe 1s).
> I can see tooltips on hover with nightly(on mac/Win10)

@simonhong I see tooltips for Brave Together, Crypto Wallets, History, Downloads, Settings, etc.   Just not the Sidebar icon itself, which only appears centered in that black bar.

![this-guy](https://user-images.githubusercontent.com/387249/118170163-a35fac80-b3de-11eb-861e-42801e03612a.png)

**Comment by simonhong** [comment]
> > @stephendonner Can you check again? First tooltip is shown in some delay(maybe 1s).
> > I can see tooltips on hover with nightly(on mac/Win10)
> 
> @simonhong I see tooltips for Brave Together, Crypto Wallets, History, Downloads, Settings, etc. Just not the Sidebar icon itself, which only appears centered in that black bar.
> 
> ![this-guy](https://user-images.githubusercontent.com/387249/118170163-a35fac80-b3de-11eb-861e-42801e03612a.png)

@karenkliu can you give tooltip string for this show on click area?

**Comment by karenkliu** [comment]
@simonhong `Show sidebar`

**Comment by stephendonner** [comment]
Verified `PASSED` with 

Brave | 1.26.24 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:

1. new profile
2. launch Brave
3. set brave://flags/#sidebar to Enabled and restart
4. mouse over to the Sidebar panel on the left
5. context-click an empty region and choose On click from Show Sidebar
6. mouse over again to the now-hidden Sidebar panel, and hover over the window icon

Confirmed the tooltip is present and reads `Show sidebar`

<img width="331" alt="Screen Shot 2021-05-18 at 11 21 30 AM" src="https://user-images.githubusercontent.com/387249/118703814-5bb89680-b7cb-11eb-85be-e931c068e642.png">

**Comment by simonhong** [comment]
Not valid issue as we don't use `On click` option anymore.
