### ISSUE TITLE
Rewards should be sync even without Uphold account

### ISSUE THREAD

**Issue by RupeshBhandari** [brave/brave-browser#15819]
## Description 

Currently the rewards that have been accumulated in another device isn't synced on the other without Uphold which required like 25 BAT which can be a bummer for some people!

## Steps to Reproduce

   1.  Accumulate reward in one device
   2.  Add it to sync chain in another device
   3.  Check whether the rewards is synced

## Actual result:

The rewards isn't displayed

## Expected result:
The rewards should be synced automatically when devices is added to the sync chain

## Reproduces how often: 

Everytime

## Brave version (brave://version info)

1.24.84 Chromium: 90.0.4430.93 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
  - Yes
- Can you reproduce this issue with the beta channel? 
  - Yes
- Can you reproduce this issue with the nightly channel? 
  - Yes
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
  - No
- Does the issue resolve itself when disabling Brave Rewards? 
  - No
- Is the issue reproducible on the latest version of Chrome? 
   - No
## Miscellaneous Information:

The reward doesn't sync when a device is added to the sync chain

**Comment by Miyayes** [comment]
Thanks for the issue! Some notes:

1. Uphold is now 15 BAT minimum;
2. Gemini is now released in v1.29.76+, and **no BAT minimum required**

We will create a separate issue to add Rewards data to Brave Sync. It's something we plan to do!
