### ISSUE TITLE
Missing translation is IPFS menu

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#15811]
`Share local folder using IPFS` under `Hamburger Menu -> IPFS` is not translated

## Steps to Reproduce

   1. Run Brave in Polish (PL) locale
   1. Enable ipfs
   1. Restart the browser
   1. Open  `Hamburger Menu -> IPFS`

## Actual result:

`Share local folder using IPFS` under `Hamburger Menu -> IPFS` is not translated
![image](https://user-images.githubusercontent.com/34715963/118058176-e6456400-b38d-11eb-9243-00343e3a0fb9.png)

## Expected result:
`Share local folder using IPFS` under `Hamburger Menu -> IPFS` is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.25.59 Chromium: 90.0.4430.212 (Official Build) beta (64-bit)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Ubuntu 18.04 LTS

cc @mkarolin @spylogsster @brave/legacy_qa

**Comment by kjozwiak** [comment]
Closing this as https://github.com/brave/brave-core/pull/8913 was merged into both `1.26.x` & `1.25.x` via https://github.com/brave/brave-core/pull/8918 & https://github.com/brave/brave-core/pull/8919.
