### ISSUE TITLE
Ads are blocked forever after ads limits (per hour or per day) are reached

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#15814]
Follow up to https://github.com/brave/brave-browser/issues/9805

When an ads limit is reached, user will never see an ad, even when the limit should have expired already. Browser restart does not fix this issue.
The user will not see ads ever again

## Steps to Reproduce

1. Follow steps from **Brave Ads maximum new tab page ads per hour - 1 per hour - limit expired** from https://github.com/brave/internal/issues/759

Note: also reproduced for Notification ads
Note: reproducible also with default values for limits

## Actual result:

Ads are blocked forever. 
The limit does not expire
Browser restart does not fix this issue

Logs:
```
[4691:4691:0513/062212.689391:VERBOSE2:permission_rule_util.cc(23)] You have exceeded the allowed new tab page ads per hour
[4691:4691:0513/062212.689825:VERBOSE1:new_tab_page_ad.cc(120)] New tab page ad: Not allowed
```

## Expected result:
Ad is shown after limit expires

## Reproduces how often: 

100% reproduction rate

## Brave version (brave://version info)

Reproduced on 

Brave | 1.25.59 Chromium: 90.0.4430.212 (Official Build) beta (64-bit)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Ubuntu 18.04 LTS

Reproduced on 

Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (64-bit)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | Ubuntu 18.04 LTS

Not reproducible on 

Brave | 1.24.84 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Ubuntu 18.04 LTS

cc @jsecretan @tmancey @moritzhaller @brave/legacy_qa

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` as this is waiting on an uplift to 1.25.x.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, this should be available to test in https://github.com/brave/brave-browser/releases/tag/v1.25.64

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.25.64 Chromium: 90.0.4430.212 (Official Build) beta (x86_64)
Revision	e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS	macOS Version 10.15.7 (Build 19H1030)
```

Executed selected scenarios from https://github.com/brave/internal/issues/759 listed below.

Verified `Brave Ads maximum new tab page ads per hour - 1 per hour - limit expired`

<details>
Verified 1st ad is shown:

```
[29324:775:0519/113514.880897:VERBOSE6:new_tab_page_ad_event_viewed.cc(32)] Successfully logged new tab page ad viewed event
```

Verified next ad is blocked:

```
[29324:775:0519/113632.969004:VERBOSE2:permission_rule_util.cc(23)] You have exceeded the allowed new tab page ads per hour
[29324:775:0519/113632.969081:VERBOSE1:new_tab_page_ad.cc(120)] New tab page ad: Not allowed
```

After 1h, verified ads are shown again:
```
[29409:775:0519/123821.124381:VERBOSE6:new_tab_page_ad_event_viewed.cc(32)] Successfully logged new tab page ad viewed event
```

</details>


Verified `Brave Ads maximum ad notifications per day - multiple profiles - 1 per day - limit expired`

<details>
Verified 1st ad is shown:

```
[29951:775:0519/135930.348671:VERBOSE1:ad_notification_serving.cc(105)] Ad notification delivered:
  uuid: 37c2b222-d007-46f1-8924-83b07434f2c9
  creativeInstanceId: 54592ab6-5a8e-42e6-8e11-9e9c04e9eecb
  creativeSetId: c7e7a381-4c74-4dd9-9b6d-4edf9330454b
  campaignId: 0d01425b-c970-4a25-b2d0-ccf748cfaf6e
  advertiserId: ecbcc833-8b1d-4867-98f7-ad2341396ce8
  segment: untargeted
  title: Ad2 - same set
  body: Ad2 - same set
  targetUrl: https://youtube.com
```

Verified next ad is blocked:

```
[29951:775:0519/140128.016935:VERBOSE2:permission_rule_util.cc(23)] You have exceeded the allowed ads per day
[29951:775:0519/140128.017080:VERBOSE1:ad_notification_serving.cc(150)] Ad notification not served: Not allowed
[29951:775:0519/140128.017153:VERBOSE1:ad_notification_serving.cc(91)] Ad notification not delivered
```

After 24h, verified ads are shown again:

```
[30078:775:0520/140451.232846:VERBOSE1:ad_notification_serving.cc(105)] Ad notification delivered:
  uuid: 3b935459-622d-44cd-b4bf-230fb2206351
  creativeInstanceId: 5b4cb3f4-5285-4597-87c5-3082fe37938a
  creativeSetId: c7e7a381-4c74-4dd9-9b6d-4edf9330454b
  campaignId: 0d01425b-c970-4a25-b2d0-ccf748cfaf6e
  advertiserId: ecbcc833-8b1d-4867-98f7-ad2341396ce8
  segment: untargeted
  title: Ad1 - same set
  body: Ad1 - same set
  targetUrl: https://youtube.com
```

</details>

<details>
<summary>TBD</summary>

Verified `Brave Ads maximum new tab page ads per day - multiple profiles - 1 per day - limit expired`
<details>

Verified 1st ad is shown:

```
TBD
```

Verified next ad is blocked in 2nd profile:
```
TBD
```


After 24h, verified ads are shown again:

```
TBD
```

</details>
</details>
