### ISSUE TITLE
Stop associating Brave with the ftp protocol

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#15812]
Chromium [removed ftp support from the codebase in M91](https://chromestatus.com/feature/6246151319715840), but it is still included in the [desktop shortcut on Linux](https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/common/desktop.template;l=114;drc=647f8ae0c1121822643c73af87986d9591e669a4) and so it gets used when opening ftp URLs:

    xdg-mime query default x-scheme-handler/ftp

Upstream meta-bug: https://bugs.chromium.org/p/chromium/issues/detail?id=333943

**Comment by fmarier** [comment]
I have filed a bug upstream for this: https://bugs.chromium.org/p/chromium/issues/detail?id=1210977

**Comment by fmarier** [comment]
Merged into M92: https://chromium.googlesource.com/chromium/src/+/a3ab59c808b58d126b6ca5fd588516c203ffa436

**Comment by btlechowski** [comment]
Added `QA/Blocked` till we get a release build.

**Comment by LaurenWags** [comment]
Removed `QA/Blocked`, release preview version is available: https://github.com/brave/brave-browser/releases/tag/v1.26.63

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.26.63 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | Ubuntu 20 LTS

Verified that after Ubuntu 20 installation, `Firefox` is associated with the protocols:
![image](https://user-images.githubusercontent.com/34715963/122558384-4dfe6700-d03e-11eb-87fa-8bc3f1b0c9a9.png)
Verified that after installing Brave 1.26.x (release channel) and restarting the system, `Brave` is not associated with the protocols
![image](https://user-images.githubusercontent.com/34715963/122560177-93bc2f00-d040-11eb-9bd0-e0a02297715b.png)

**Comment by mowny** [comment]
This is also still a problem on windows.
![image](https://user-images.githubusercontent.com/25304296/216317124-8989e0b5-dc0b-409f-a3fd-d820e7e6d1ff.png)
[Version 1.47.186 Chromium: 109.0.5414.119 (Offizieller Build) (64-Bit)](https://brave.com/latest/)
