### ISSUE TITLE
Video fails to load on D Tube due to CORS policy

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1581]
## Description 

While verifying https://github.com/brave/brave-core/pull/599/ found that video fails to load on D Tube due to CORS policy

## Steps to Reproduce

   1. Clean profile 0.55.13
   2. Load any video on https://d.tube
   3. Shows a blank area on video player

## Actual result:

![screenshot from 2018-10-15 11-11-51](https://user-images.githubusercontent.com/17010094/46959900-2d023e80-d06b-11e8-91ef-22141dc09412.png)

## Expected result:
Should load the video

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes, disable shields loads the video and autoplays 
- Is the issue reproducible on the latest version of Chrome?

**Comment by iefremov** [comment]
Should be fixed together with #2252

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

checked https://d.tube
![image](https://user-images.githubusercontent.com/34715963/50929128-c10e5700-145c-11e9-8e67-c729ecf385cc.png)

checked https://www.brighteon.com/
![image](https://user-images.githubusercontent.com/34715963/50929057-9de3a780-145c-11e9-9988-ba2eae26f67e.png)
