### ISSUE TITLE
Implement Brave VPN on macOS

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#15810]
## Description 
Part of parent issue https://github.com/brave/brave-browser/issues/15804

The goal here would be to create an implementation in `brave-core` which handles VPN on macOS. Each OS can provide an OS specific implementation for a "VPN Service".

This would need the ability to:
- Create a VPN connection with the OS. 
- Update a connection (if details change)
- Connect to the VPN
- Disconnect from the VPN
- Remove the VPN connection from the OS

We should be able to do an implementation similar to [what was done on iOS](https://github.com/brave/brave-ios/pull/2740). Also see files in https://github.com/brave/brave-ios/tree/development/Client/Frontend/BraveVPN (@iccub lead the implementation on iOS)

**Comment by simonhong** [comment]
Add `BraveVPNConnectionManager` implementation with Guardian's https://github.com/brave/GuardianConnect

**Comment by simonhong** [comment]
Whenever application tries to configure VPN configuration via `NEVPNManager` api, macOS asks to user with below popup.
<img width="271" alt="Screen Shot 2021-06-28 at 4 06 01 PM" src="https://user-images.githubusercontent.com/6786187/123594788-1906c700-d82b-11eb-82f1-5d3ea729c233.png">

If `Don't Allow` is clicked, vpn creating process stops.
If `Allow` is clicked, user have to type password again via below popup.
<img width="360" alt="Screen Shot 2021-06-28 at 4 11 18 PM" src="https://user-images.githubusercontent.com/6786187/123595209-9c281d00-d82b-11eb-8933-335dd60c60c1.png">
After inserting proper password, vpn is connected.
