### ISSUE TITLE
Ephemeral Storage Keep Alive doesn't respect the flag 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15815]
## Description 

Ephemeral Storage Keep Alive doesn't respect the flag 

## Steps to Reproduce

   1. Clean install 1.26.11 x64 nightly desktop build
   2. Enable only `brave://flags/#brave-ephemeral-storage` 
   3. **Do not enable `brave://flags/#brave-ephemeral-storage-keep-alive` let it be default**
   4. Restart browser and visit `https://dev-pages.brave.software/storage/keep-alive.html` and run through both the tests
   5. Results are same as expected even though the keep-alive flag is not enabled which is supposed to control the behaviour

## Actual result:

Ephemeral Storage Keep Alive doesn't respect the flag 

## Expected result:
Ephemeral Storage Keep Alive should be controlled by the flag 

## Reproduces how often: 

Easy

## Desktop Brave version:

Brave | 1.26.11 Chromium: 90.0.4430.93 (Official Build) nightly (64-bit)
-- | --
Revision | `4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

On Android, the `Should not Keep-Alive Test` fails as the remote frame doesn't set value as empty for which #15646 is logged

cc: @pes10k @bridiver

**Comment by kjozwiak** [comment]
@brave/legacy_qa we'll need to run through all the cases under https://dev-pages.brave.software/storage/index.html and ensure everything is still working as expected as requested by @bridiver via Slack. Example: https://github.com/brave/brave-core/pull/8787#issuecomment-842750460.
