### ISSUE TITLE
IPFS sub menu is not shown in the main app menu until browser is restarted

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15822]
## Description 

IPFS sub menu is not shown in the main app menu until browser is restarted

## Steps to Reproduce

   1. Clean profile 1.25.x
   2. Enable IPFS local node
   3. Click on main menu settings
   4. IPFS sub menu is not shown in the main app menu

## Actual result:

IPFS sub menu is not shown in the main app menu after enabling IPFS

**Before browser restart:**
![image](https://user-images.githubusercontent.com/38657976/118098137-2a1d8500-b3f1-11eb-9cef-0a3bb48afe74.png)

**After browser restart:**
![image](https://user-images.githubusercontent.com/38657976/118098213-402b4580-b3f1-11eb-9e84-ffeab742c105.png)

## Expected result:
IPFS sub menu should be shown in the main app menu after enabling IPFS

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.25.57 Chromium: 90.0.4430.93 (Official Build) beta (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2004 (Build 19041.985)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @spylogsster

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | Windows&nbsp;10 OS Version 2009 (Build 21382.1)

Steps:
1. new profile
2. loaded `ipns://brantly.eth`
3. chose `Use local node`
4. waited for installation to finish
5. confirmed that top-level `IPFS` menu item with sub-menus was usable

example | example
---------|---------
![interstitial](https://user-images.githubusercontent.com/387249/118549022-c86e5b00-b70f-11eb-950d-9740f468fdbb.png) | ![ipfs-menu](https://user-images.githubusercontent.com/387249/118549047-d0c69600-b70f-11eb-80c8-d61da16b7727.png)
