### ISSUE TITLE
Empty spaces on https://download.pixelexperience.org/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#15820]
## Description 
Visit `https://download.pixelexperience.org/` or `https://blog.pixelexperience.org/` will show plenty of blank/empty spaces

## Steps to Reproduce

   1. enable `chrome://flags/#brave-adblock-cosmetic-filtering-native`
   2.  Visit `https://download.pixelexperience.org/` or `https://blog.pixelexperience.org/`
   3.  Plenty of empty space
   4. Aggressive Ads/trackers makes no difference

## Actual result:

![pixel-spaces](https://user-images.githubusercontent.com/1659004/118096159-1b50c580-b425-11eb-9d5d-756d05ab3e62.png)

## Expected result:
![pixel-spaces2](https://user-images.githubusercontent.com/1659004/118096591-ab8f0a80-b425-11eb-84c1-fd3759af3bf5.png)

## Reproduces how often: 
Easily with Native Cosmetic filtering

## Version/Channel Information:
`Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-bit)`

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

Applicable to Native cometic filtering enabled via brave://flags  Also site uses `BlockAdBlock" which may/maynot be causing this

**Comment by antonok-edm** [comment]
@ryanbr I'm no longer able to reproduce this issue - were there any filters updated in the meantime, or should this just be closed?

**Comment by ryanbr** [comment]
Looks fine now,  closing.
