### ISSUE TITLE
Ads shouldn't stay on for too long

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#15836]
## Description 

I don't purposefully use the browser for Rewards thus I've set to show only 1 Ad per hour, that being said I don't know whether it's just for Linux users but Ads can can be distracting like pop-ups on Internet Explorer (remember that) they just simply don't go off an I don't like how it just remains there unless you move your attention away just to close it.

Ad banners should go off per users set time so they can eventually click on it or make it easy on us by giving a selection of how long a tab should remain open because right now it honestly is coming across as distracting.

**Comment by tmancey** [comment]
@NumDeP Ads currently timeout after 2 minutes. We will be running some tests with different timeout durations. What timeout duration would you possibly like to see? Thanks

**Comment by tmancey** [comment]
Adding field trials to test 1 minute (25% of users), 30 seconds (25% of users) and 15 seconds (25% of users) and default (25% of users). The default is 2 minutes. This field trial is on desktop for the nightly channel

**Comment by tmancey** [comment]
Closing. as resolved by https://github.com/brave/brave-variations/pull/166

**Comment by NumDeP** [comment]
HI @tmancey do you know this issue is still apparent? I also noticed that ads still remain open after you exist/close the browser. I recently tested to see how long an add remain on the desktop screen and I don't think it would go away unless you manually close it because it went for 5 minutes straight before I closed it.

I should state that I'm finding this issue in Linux.
