### ISSUE TITLE
Change Cloudflare Privacy Policy interstitial link

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#15831]
Change Cloudflare Privacy Policy interstitial link from:
https://www.cloudflare.com/en-ca/privacypolicy/ 

to:
 https://developers.cloudflare.com/1.1.1.1/privacy/public-dns-resolver

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.26.30 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

### Steps:
1. new profile, launched Brave
2. loaded `brad.crypto`
3. checked the text and link for `privacy policy`

Confirmed link is to `https://developers.cloudflare.com/1.1.1.1/privacy/public-dns-resolver`

<img width="1192" alt="Screen Shot 2021-05-19 at 10 47 56 AM" src="https://user-images.githubusercontent.com/387249/118860164-eb277d80-b88f-11eb-99d5-ecf3e35f38a0.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.46 x64 Beta build
- Verified `Privacy Policy` on Cloudflare interstitial link points to `https://developers.cloudflare.com/1.1.1.1/privacy/public-dns-resolver`

https://user-images.githubusercontent.com/17010094/120316897-da3a2b80-c2d5-11eb-8087-47f568cc2da0.mp4

-----------
Verification passed on Samsung Tab Awith Android 10 running 1.26.46 x64 Beta build
- Verified `Privacy Policy` on Cloudflare interstitial link points to `https://developers.cloudflare.com/1.1.1.1/privacy/public-dns-resolver`

https://user-images.githubusercontent.com/17010094/120316863-cc84a600-c2d5-11eb-990f-d08290b152e4.mp4
