### ISSUE TITLE
Can't Open a link in new background tab by "Ctrl + Click a link", it'll automatically close in a few seconds

### ISSUE THREAD

**Issue by GeeSko** [brave/brave-browser#15839]
it'll automatically close in a few seconds

**Comment by bsclifton** [comment]
@GeeSko do you have an example? This sounds like it might be a problem with a specific site. It's definitely working - middle click and ctrl click are used by folks all the time

**Comment by GeeSko** [comment]
Thanks, now it works. I just restarted the browser.
