### ISSUE TITLE
Setup your IPNS keys should read Set up your IPNS keys

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15845]
## Description 

Setup your IPNS keys should read Set up your IPNS keys

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `ipns://brantly.eth`
   4. click on `Use a local node`
   5. wait
   6. load `brave://settings/ipfs/keys`
   7. look at the spelling of `Setup your IPNS keys` 

## Actual result:

<img width="1505" alt="Screen Shot 2021-05-13 at 1 34 00 PM" src="https://user-images.githubusercontent.com/387249/118184366-19204400-b3f0-11eb-8c2d-eceedc80b3dd.png">

## Expected result:
Should read `Set up your IPNS keys` (transitive verb vs. noun)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.26.18 Chromium: 91.0.4472.38 (Official Build) nightly (x86_64)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

**Comment by SayarB** [comment]
it seems that it is problem only in macOS. I have a windows pc and the IPFS tab does not contain a key tab.
Cannot reproduce issue.

**Comment by stephendonner** [comment]
### Verified `FIXED` using 

Brave | 1.26.30 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

### Steps:

1. new profile
2. launch Brave
3. load `ipns://brantly.eth`
4. click on Use a local node
5. wait
6. load `brave://settings/ipfs/keys`

Confirmed it now reads `Set up your IPNS keys`

<img width="1088" alt="Screen Shot 2021-05-19 at 10 43 18 AM" src="https://user-images.githubusercontent.com/387249/118859544-35f4c580-b88f-11eb-8179-93e2ec0fea4d.png">
