### ISSUE TITLE
Performance Issue: Opening Private Windows Takes Too Long

### ISSUE THREAD

**Issue by 8227846265** [brave/brave-browser#15857]
## Description 
Whenever opening a Private Window. It will take at least 1 second to have it usable. 

While its whiteout. You can't search, if you do. It will just return to the Private Window's New Tab.

Note:

- My computer has good hardware specs since it's built as a gaming desktop, so I don't have any problems on browsing performance issue on other browsers. Only applies to Brave Browser.

## Steps to Reproduce

   1. Open a Private Window on Brave Browser
   
## Screenshot
Note: This loading speed still applies on a fresh installed Brave Browser with default settings and no extensions.
![205 - UCrZjx1VHl](https://user-images.githubusercontent.com/66582769/118264915-06d70080-b4eb-11eb-9945-0aae040a96b2.gif)

## Actual result:
Brave Browser's Private Window loads too long for at least 1 second

## Expected result:
It should load below 1 second so once opened. The user can browse immediately.

## Reproduces how often: 
Every time Private Windows is opened

## Brave version (brave://version info)
Version 1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit)

## Version/Channel Information:

- [X] Can you reproduce this issue with the current release?

Didn't try sadly:
- [ ] Can you reproduce this issue with the beta channel?
- [ ] Can you reproduce this issue with the nightly channel?

## Other Additional Information:

No, to all three below:
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by 8227846265** [comment]
It seems an update to the AMD CPU driver fixes the issue. Closing this now.

**Comment by ryanbr** [comment]
Reported https://community.brave.com/t/brave-browsers-performance-issue/253126/2
