### ISSUE TITLE
Video buffering stops on 2 monitors

### ISSUE THREAD

**Issue by OLoKo64** [brave/brave-browser#15858]
## Steps to Reproduce

   1. Open any YouTube video on Brave.
   2. Open a second video on another tab on the other monitor.
   3. The 2 videos will stop buffering and not play smoothly. 

## Actual result:

When the 2 videos start, both of them will stop buffering and stop. If 1 video is paused the other will reload and work as intended.
This is not limited to YouTube, any streaming service seems to been affected.

## Expected result:
The 2 videos are supposed to run fine, without one interfering with the other.

## Reproduces how often: 

This is achieved 100% of the times.

## Brave version (brave://version info)

Current stable build.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel? 
- Not tested
- Can you reproduce this issue with the nightly channel? 
- Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- Not tested on Chrome but it does't happen on Firefox.

**Comment by ryanbr** [comment]
Can test this, is this Windows or Linux/Mac builds?

Can you test in private window mode, also test by changing resolution say 720p for each video.

**Comment by OLoKo64** [comment]
> Can test this, is this Windows or Linux/Mac builds?
Currently I can only test this on my Windows machine, on my Linux I cannot connect 2 monitors.

> Can you test in private window mode, also test by changing resolution say 720p for each video.
Yes, this occurs the in same way, no change.

My PC specifications:
Ryzen 2700X
GTX 1060
16GB of RAM
Windows Build 19042.985

Video of this bug occurring:
https://youtu.be/lDCCsuuxTec

**Comment by OLoKo64** [comment]
I recorded another video with the console open and the nerd statistics enabled:
https://youtu.be/N-9-zGdnv0o

**Comment by ryanbr** [comment]
From my testing, running 2 videos (side by side).  https://www.youtube.com/watch?v=9Wjh5-B2g2c

I know youtube has been testing new ways to push ads, is still an issue? Running youtube side-by-side should be no different from dual monitors. @OLoKo64

**Comment by OLoKo64** [comment]
> Running youtube side-by-side should be no different from dual monitors.

Exactly this is what I find more intriguing, there should be no difference, but if they are on different windows that happens.

This been happening for a couple of months by now, and still is. When tested with Edge (the other Chromium that I have) this does not occur.

This is not a YouTube isolated issue, any video player that I open on both monitors, have the same effect, it doesn't need to be from the same site either, for example, if I am watching a video on Twitch and open a video on  Reddit, the same happens.

From my research on the web no one seems to have this issue, which is strange and  that's why I came here.

Is there a way to log the activity of the browser so I can look or even send to you guys to analyse?

**Comment by ryanbr** [comment]
What does the console (F12) say, compared to Chrome

**Comment by OLoKo64** [comment]
I just find the fix for the issue, on "brave://flags/" under "Choose ANGLE graphics backend" I switched from default to OpenGL that fixed 100% of the issue, after that I notice that either OpenGL or D3D11on12 works.

Recently on my notebook I've been experiencing some black screen flashes and this fixed too.

**Comment by bsclifton** [comment]
@OLoKo64 thanks for the update and sharing what fixed it for you! I'll close this issue out
