### ISSUE TITLE
When installer encounters an error, it goes to an invalid `Help` page

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1585]
## Description 
Help button is shown during installer failure. However, when clicked it doesn't go to a working URL

## Steps to Reproduce

   1. Download the Brave Beta installer on Windows from https://brave.com/download-beta
   2. Open command line; navigate to directory where installer was downloaded to
   3. Launch installer and pass invalid arguments. Ex: `BraveBrowserBetaSetup.exe /q`

## Actual result:
It navigated to https://updates.bravesoftware.com/support/installer/?hl=&product=&error=0x80040c01&extra_code=0&guver=1.3.101.0&m=0&os=10.0.17134.345&sp=&iid=&brand=&source=gethelp
![screen shot 2018-10-15 at 9 17 38 am](https://user-images.githubusercontent.com/4733304/46963777-603cd180-d05b-11e8-86d6-00ffc2e7294d.png)

## Expected result:
It should go to a working URL

## Reproduces how often: 
100%

## Brave version (chrome://version info)
Latest Beta (55.13)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? y
- Does it reproduce on browser-laptop? n

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by bbondy** [comment]
I think Simon fixed this in https://github.com/brave/omaha/pull/6 and I told @mbacchi so he knows about it.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

Help points to https://support.brave.com
