### ISSUE TITLE
Investigate the new set default browser modal being shown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15862]
## Description 
Investigate the new set default browser modal being shown

## Steps to reproduce 
TBA

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/118285649-9966a800-b4c9-11eb-9fef-f04cf6f6b868.png>

## Expected result
Not sure 

## Issue reproduces how often 
Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.26.18 x64 Nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya

**Comment by srirambv** [comment]
Not sure about steps but I ran into this again today after updating Nightly build. May be not having a default browser is the key?

- Install older nightly build
- Install Beta build via GPS
- Update Nightly via GPS update to latest
- Uninstall and reinstall Beta build (via GPS)
- Close all instances of browsers via app list
- Launch Nightly shows the screen similar to the one posted in issue

**Comment by deeppandya** [comment]
Irrelevant issue at this time.
