### ISSUE TITLE
Revert Japan-specific promo card in Brave Rewards settings page

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#15861]
The promotional card was originally added here https://github.com/brave/brave-browser/issues/15551, but it was ultimately decided to stop this promotion.

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.26.30 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

## Steps:

### Japan region

1. new profile
2. started browser with `--rewards=countryid=19024` flag to set countryid to Japan, `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5 --rewards=countryid=19024`
3. opened `brave://rewards`
4. ensured that no Japan-specific promo card appeared in the Rewards panel

### US region

1. new profile
2. started browser with `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5`
3. opened `brave://rewards`
4. ensured that no Japan-specific promo card appeared in the Rewards panel

Japan region | US region
-------------|-----------
<img width="1312" alt="スクリーンショット 2021-05-19 12 08 40" src="https://user-images.githubusercontent.com/387249/118871496-7c045600-b89c-11eb-97be-8477ced98a44.png"> | <img width="1312" alt="Screen Shot 2021-05-19 at 12 19 48 PM" src="https://user-images.githubusercontent.com/387249/118871605-91798000-b89c-11eb-9d4d-f7173bf8ddfc.png">
