### ISSUE TITLE
Remove setting to toggle privacy sandbox

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#15871]
## Description 
Setting to enable privacy sandbox is available in chromium starting CR92: https://github.com/chromium/chromium/commit/02829f41aedc5cc6ebcc98d12eb8879ae58db024

This should not be available to Brave users.

**Comment by rebron** [comment]
cc: @mkarolin

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.74 Chromium: 92.0.4515.93 (Official Build) nightly (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 11.4 (Build 20F71)



Steps:
1. new profile
2. launched Brave
3. opened `brave://settings/privacy`

Confirmed there's no `Privacy Sandbox` UI, as there is in Chrome Beta.

example | example
---------|---------
<img width="1783" alt="Screen Shot 2021-07-12 at 3 15 27 PM" src="https://user-images.githubusercontent.com/387249/125362820-66536000-e324-11eb-9724-4cca9013942f.png"> | <img width="1792" alt="Screen Shot 2021-07-12 at 3 15 41 PM" src="https://user-images.githubusercontent.com/387249/125362827-681d2380-e324-11eb-858f-e7ae47cb85a7.png">

Will re-verify once it's uplifted to `1.27.x`

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 10.15.7 (Build 19H1217)
```

- Verified STR from https://github.com/brave/brave-browser/issues/15871#issuecomment-878636621
- Confirmed no "Privacy Sandbox" option under brave://settings/privacy
- Confirmed searching settings for "Privacy Sandbox" does not yield any results

Example | Example
----- | -----
<img width="1242" alt="Privacy" src="https://user-images.githubusercontent.com/28145373/125810325-e7a24b4d-0b04-4a38-b8b0-4088a8ebc16c.png"> | <img width="1243" alt="Search Privacy Sandbox" src="https://user-images.githubusercontent.com/28145373/125810328-46c31d14-5442-4aff-97a1-3a066badb232.png">

**Comment by srirambv** [comment]
Removing Android label as this setting is not applicable to Android. Also discussed with @jumde
