### ISSUE TITLE
Change rewards onboarding image in Japan #2

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15873]
## Description

In the Rewards onboarding tour **in Japan only,** swap out the image and ensure the image links out to the correct link. (@Miyayes or @soi-tnk have assets.)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.25.65 Chromium: 91.0.4472.57 (Official Build) (x86_64)
Revision	e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS	macOS Version 10.15.7 (Build 19H1030)
```

Confirmed expected image on the bitFlyer slide of rewards onboarding tour.
Confirmed image links to expected URL.

<details>

`https://bitflyer.com/static/lp03/?ns=display_brave_bf_brave&utm_source=brave&utm_medium=display&utm_campaign=bf_brave&utm_term=202104&utm_content=`

<img width="1066" alt="スクリーンショット 2021-05-21 13 43 16" src="https://user-images.githubusercontent.com/28145373/119178156-5497bf80-ba3b-11eb-829d-17dca1247e28.png">

<img width="738" alt="スクリーンショット 2021-05-21 13 42 08" src="https://user-images.githubusercontent.com/28145373/119178141-4fd30b80-ba3b-11eb-8786-2087d08cfff0.png">

</details>
