### ISSUE TITLE
Consolidate pinsets across platforms

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#15874]
Right now pinsets are only enabled on Desktop and are [part of the brave-core C++ code](https://github.com/brave/brave-core/blob/master/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc). We should split that out of the C++ code (e.g. JSON file) to help with the [iOS implementation](https://github.com/brave/brave-ios/issues/3406) and with [monitoring](https://github.com/brave-intl/bsg-cluster/issues/419).

**Comment by diracdeltas** [comment]
Discussed in security confab

* @fmarier to add separators to https://github.com/brave/brave-core/blob/master/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc to make it easier to parse start/end of the certs list
* https://github.com/brave/brave-core/blob/master/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc will then be used as the source of truth for iOS (via bootstrap script) and monitoring
