### ISSUE TITLE
Follow up of #15055 - Verify wallet modal popup isn't shown after clicking on "Verify wallet" via BR panel when the wallet balance is less than 25 BAT

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15889]
## Description 

Follow up of #15055 
Verify wallet modal popup isn't shown after clicking on "Verify wallet" via BR panel when the wallet balance is less than 25 BAT
## Steps to Reproduce

Scenarios 1:

   1. Clean profile `1.25.60`, enable rewards and claim UGP grants 
   2. Open a verified pub and send 6 BAT to a verified pubs 
   3. Make sure wallet balance is less than 25 BAT
   4. Click on "Verify wallet" in BR panel 
   5. Uphold Authorize page is displayed instead on Verify Wallet modal popup

Scenarios 2:

   1. Clean profile `1.25.60`, enable rewards and claim UGP grants 
   2. Open a verified pub and send 15 BAT to a verified pubs 
   3. Make sure wallet balance is equals to 15 BAT
   4. Click on "Verify wallet" in BR panel 
   5. Uphold Authorize page is displayed instead on Verify Wallet modal popup

**Note**: Please note, if wallet balance is 30 BAT click on Verify wallet via BR panel opens up "Verify wallet" modal popup, issue is arising only when wallet balance is less than 25 BAT and equals to 15 BAT 

## Actual result:

Click on "Verify wallet" in BR panel is redirecting to Uphold Authorize page

## Expected result:

Click on "Verify wallet" in BR panel should opens up "Verify wallet" modal popup
![image](https://user-images.githubusercontent.com/38657976/118471851-d038fa00-b725-11eb-9bcb-e5e9bd32a916.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.25.60 Chromium: 90.0.4430.212 (Official Build) beta (64-bit)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Windows 10 OS Version 2004 (Build 19041.985)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @zenparsing @emerick @rebron

**Comment by LaurenWags** [comment]
cc @Miyayes as this does not occur on 1.24.x so this is a regression. Please advise on if this is needed to be fixed for 1.25.x.

**Comment by LaurenWags** [comment]
Additionally, on 1.25.x, if you click on "Verify Wallet" from brave://rewards page, you get the modal. But clicking on "Verify Wallet" from the panel does not show this.

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` until this is uplifted to 1.25.x

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.25.65 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

```
Verified the STR from https://github.com/brave/brave-browser/issues/15889#issue-893081761

<details>
<summary>Scenario 1: wallet balance is 24 BAT</summary>

- Confirmed that the `Verify wallet` modal popup is displayed upon clicking on Verify wallet via BR panel

**Wallet balance 24 BAT** | **Click Verify wallet via BR panel** | **Verify wallet modal popup** | **uphold authorization** 
----------------------------|----------------------------------------|-----------------------------------|-------------------------

</details>
