### ISSUE TITLE
Autofill doesn't work in Tor windows

### ISSUE THREAD

**Issue by antikmozib** [brave/brave-browser#15884]
## Description

Autofill doesn't work in Tor windows with extensions like Bitwarden/Lastpass etc.

## Steps to Reproduce

   1. Open a Tor window
   2. Use an extension to autofill usernames/passwords

## Actual result:

Nothing happens

## Expected result:

Should fill in details

## Reproduces how often:

Easily reproduced 

## Brave version (brave://version info)

Version 1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit)

**Comment by srirambv** [comment]
Have you enabled `Allow in private` option from the extensions settings?

**Comment by antikmozib** [comment]
Yes, I enabled the `Allow in private` setting for the extensions that are causing this issue.
