### ISSUE TITLE
Custom ad notifications do not correctly render the shadow on Linux

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15886]
## Description 

Ads on nightly has a background overlay

## Steps to Reproduce

   1. View an ad on nightly on Linux build 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/118427538-5d983200-b6c5-11eb-8523-0233ec82265a.png) | ![image](https://user-images.githubusercontent.com/17010094/118436148-2bdc9680-b6d8-11eb-95ba-cacc16ad65ac.png)
-- | --

## Expected result:
No background for custom ads

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.26.21 Chromium: 91.0.4472.57 (Official Build) nightly (64-bit)
-- | --
Revision | `e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}`
OS | Linux
Desktop | Gnome 

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @tmancey

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.29.60 Chromium: 92.0.4515.131 (Official Build) beta (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Ubuntu 20

Verified custom ads design changed (no rounded corners). No weird shadows.

<details>

Verified light theme
![image](https://user-images.githubusercontent.com/34715963/129783692-32ada8f3-41ca-4449-a14e-30212d3885bd.png)

Verified dark theme
![image](https://user-images.githubusercontent.com/34715963/129783758-44da87fe-6be7-4903-8131-5f0f49ddbebf.png)

tested on:
![image](https://user-images.githubusercontent.com/34715963/129783795-98612029-bb1e-455e-b8b5-86b0b2c4db0b.png)

</details>
