### ISSUE TITLE
Fingerprinting 3.0: WebGL Debugging Followups

### ISSUE THREAD

**Issue by xsvanc06** [brave/brave-browser#15882]
@xsvanc06 pointed out two fingerprinting improvements that would be good to make, regarding WebGL extension information.  These changes would only be made in strict mode.

- Change `getSupportedExtensions` to return `["WEBGL_debug_renderer_info"]` instead of `null`. This would be a web compat improvement, not a privacy improvement
- Change `getExtension` to return NULL for all values except `WEBGL_debug_renderer_info`

## Original message

I've been testing WebGLRenderingContext.getSupportedExtensions() with farbling level _maximum_ and I get _null_ as return value, but I was expecting [array](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getSupportedExtensions). I looked at some tests in Brave and they are checking for _null_, so I guess it's intentional, may be related to #3326

And then WebGLRenderingContext.getExtension() should return bottom value at maximum level (I am guessing _null_) according to #9188, but I get same results on farbling level _maximum_ and _disabled_. Wouldn't fingerprinting script just check for all possible extensions? 

I am running Version 1.24.84 Chromium: 90.0.4430.93 (Official Build) (64-bit)

**Comment by pes10k** [comment]
Thank you for the issue @xsvanc06 !

> I've been testing WebGLRenderingContext.getSupportedExtensions() with farbling level maximum and I get null as return value, but I was expecting array. I looked at some tests in Brave and they are checking for null, so I guess it's intentional, may be related to #3326

Good point, we should return an empty array here, good catch.

> And then WebGLRenderingContext.getExtension() should return bottom value at maximum level (I am guessing null) according to #9188, but I get same results on farbling level maximum and disabled. Wouldn't fingerprinting script just check for all possible extensions?

This is a good point too, thanks!  I'm going to repurpose this issue to cover those changes.  Thank you very much for catching them!

**Comment by stephendonner** [comment]
@pes10k @pilgrim-brave - can we please get a testplan attached to https://github.com/brave/brave-core/pull/8831?  Thanks!

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8831 on test sites `https://dev-pages.brave.software/fingerprinting/strict-mode.html` and `https://dev-pages.bravesoftware.com/fingerprinting/strict-mode.html` with build 

Brave | 1.27.48 Chromium: 91.0.4472.88&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 109e9cd038b94a631aea7d40ee3d56c1278f2597-refs/branch-heads/4472@{#1385}
OS | macOS Version 11.4 (Build 20F71)

Steps:

1. new profile
2. loaded `https://dev-pages.brave.software/fingerprinting/strict-mode.html` and `https://dev-pages.bravesoftware.com/fingerprinting/strict-mode.html`
3. disabled Shields
4. clicked `Generate values`
5. clicked on the hashes for `WebGL - getSupportedExtensions`
6. confirmed they returned values for the above, on both pages

Repeated the above, with the following shields configurations:

**Shields off**

dev-pages.brave.software | dev-pages.bravesoftware.com
---------------------------|-------------------------------
<img width="1770" alt="Screen Shot 2021-06-08 at 2 01 58 PM" src="https://user-images.githubusercontent.com/387249/121259042-78913880-c864-11eb-8c8c-b4af0d0e8ea5.png"> | <img width="1770" alt="Screen Shot 2021-06-08 at 2 04 24 PM" src="https://user-images.githubusercontent.com/387249/121259045-7929cf00-c864-11eb-8976-10c247499f40.png">

**Shields on, fingerprinting standard**

dev-pages.brave.software | dev-pages.bravesoftware.com
---------------------------|-------------------------------
<img width="1770" alt="Screen Shot 2021-06-08 at 2 11 46 PM" src="https://user-images.githubusercontent.com/387249/121259628-31f00e00-c865-11eb-954e-19706bfa4aba.png"> | <img width="1770" alt="Screen Shot 2021-06-08 at 2 12 03 PM" src="https://user-images.githubusercontent.com/387249/121259631-3288a480-c865-11eb-9d71-24c32082c07e.png">

**Shields on, fingerprinting strict**

dev-pages.brave.software | dev-pages.bravesoftware.com
---------------------------|-------------------------------
<img width="1770" alt="Screen Shot 2021-06-08 at 2 06 06 PM" src="https://user-images.githubusercontent.com/387249/121259515-14bb3f80-c865-11eb-8ee3-657a14e881c8.png"> | <img width="1770" alt="Screen Shot 2021-06-08 at 2 06 17 PM" src="https://user-images.githubusercontent.com/387249/121259517-14bb3f80-c865-11eb-8acf-b5f6bdde11d6.png">

**All configurations have the same output for the following:**

WebGL - getExtension("WEBGL_debug_renderer_info")

dev-pages.brave.software | dev-pages.bravesoftware.com
---------------------------|-------------------------------
<img width="1770" alt="Screen Shot 2021-06-08 at 2 32 20 PM" src="https://user-images.githubusercontent.com/387249/121260881-c870ff00-c866-11eb-95ca-f08e7bea47e1.png"> | <img width="1770" alt="Screen Shot 2021-06-08 at 2 32 42 PM" src="https://user-images.githubusercontent.com/387249/121260886-c9099580-c866-11eb-8b48-38c294593c2f.png">

WebGL - getExtension("WEBGL_lose_context")

dev-pages.brave.software | dev-pages.bravesoftware.com
---------------------------|-------------------------------
<img width="1770" alt="Screen Shot 2021-06-08 at 2 32 25 PM" src="https://user-images.githubusercontent.com/387249/121260976-eb031800-c866-11eb-823a-2b6beaf8fb0b.png"> | <img width="1770" alt="Screen Shot 2021-06-08 at 2 31 46 PM" src="https://user-images.githubusercontent.com/387249/121260972-ea6a8180-c866-11eb-9941-96c5ca730c8e.png">
