### ISSUE TITLE
Items blocked via CSS selector loads before getting blocked again

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1588]
## Description 

Items blocked via CSS selector loads before getting blocked again

## Steps to Reproduce

   1. Clean profile on 0.55.13
   2. Visit any site which shows a banner item on each visit
   3. Block it via right click CSS selector
   4. Close the tab and visit the site again, blocked item loads correctly and then gets blocked again

## Actual result:

![blockitem](https://user-images.githubusercontent.com/17010094/46971392-d0fae280-d089-11e8-80b7-ce6405efedda.gif)

## Expected result:
Should not load item once its blocked via CSS selector

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Not seen this issue on the older builds
@brave/legacy_qa to verify it on other platfroms

**Comment by LaurenWags** [comment]
Reproduced on `macOS 10.12.6 x64` using

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

**Comment by kjozwiak** [comment]
Reproduced using `Win 10 x64` with the following build:

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

**Comment by bsclifton** [comment]
Closing as `wontfix` - we have a new cosmetic filter in place. I created https://github.com/brave/brave-browser/issues/8914 to track removing this older version
