### ISSUE TITLE
Cant use google services, errror 400

### ISSUE THREAD

**Issue by MarcosSouza2004** [brave/brave-browser#15896]
## Actual result:

![image](https://user-images.githubusercontent.com/76596575/118490276-268d4500-b6f4-11eb-9407-33c2a7f759b0.png)

## Brave version (brave://version info)
 latest (stable) > 1.24.85

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I use 1.1.1.1 DoH, in other browsers work fine

**Comment by ryanbr** [comment]
Can you test without DoH enabled? @MarcosSouza2004

**Comment by MarcosSouza2004** [comment]
> Can you test without DoH enabled? @MarcosSouza2004

i tryed: disable 1111, disable DoH, enable DoT, remove cloudflare dns from my windows, reinstall brave > nothing works, still returns error 400

**Comment by ryanbr** [comment]
A few suggestions:
https://www.howtogeek.com/359267/what-is-a-400-bad-request-error-and-how-can-i-fix-it/
https://www.technipages.com/fix-google-chrome-bad-request-error-400

Clearing Cache, cookies, disable all extensions, 
`brave://net-internals/#dns`  -> `Clear host cache`
`chrome://net-internals/#sockets` -> `Select Close idle sockets, and click Flush socket pools`

Would test in private window mode, or failing that just start a new Brave profile.

**Comment by MarcosSouza2004** [comment]
after do the 2 and 3 all return to normality, thansk 

Just one more thing, please add the option to change background
