### ISSUE TITLE
Change bF hostname to .com 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15897]
## Description

Currently hostname is .jp; should change to .com.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.25.65 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/8826

<details>
<summary>JP region</summary>

</details>

<details>
<summary>IN region</summary>

</details>
