### ISSUE TITLE
Integrate Sparkle to brave-core on MacOS

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#159]
## Background
Updates is through `appcasting` 

Basic setup: https://sparkle-project.org/documentation/
Customization: https://sparkle-project.org/documentation/customization/

## Tasks
- [x] Add gn configuration for linking
- [x] Initialize SUUpdater during the browser startup

FYI: @RyanJarv

**Comment by simonhong** [comment]
To integrate, sparkle framework should be added to repo.
Where is the proper place to add in our repo?

**Comment by simonhong** [comment]
Almost finished initial integration - https://github.com/brave/brave-core/pull/91.
When update test is finished on both side(client and server), I think update should be done in background instead of explicit trigger by menu. Current implementation would be merged when `brave/sparkle` repo is ready to use.

Also, crash is happened with latest Sparkle(1.19.0). I assume that Chromium's [-[BrowserWinowController windowDidBecomeMain:]](https://cs.chromium.org/chromium/src/chrome/browser/ui/cocoa/browser_window_controller.mm?type=cs&q=windowDidBecomeMain&sq=package:chromium&l=615) is called on non-main thread.
I saw the Sparkle's in the related [change log](https://github.com/sparkle-project/Sparkle/releases/tag/1.19.0) - `Note: some delegate methods may be called on non-main thread now`. I assume that this change might be the cause of this crash.(Not sure, need to check their source code).

I'll investigate this crash later when window client test is done because we can update test with 1.18.1.

**Comment by RyanJarv** [comment]
Replaced https://github.com/brave/Sparkle with a forked copy of sparkle and set master to 1.18.1. You should be able to fork and make a PR for that now.
