### ISSUE TITLE
Re-enable sharing-qr-code-generator feature

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#15900]
## Test plan
1. Start Brave browser
2. Navigate to any website (e.g. brave.com)
3. Click inside the location bar
4. An action icon shows up in the location bar. When clicked a bubble with QR code shows up.

## Description 
QR code sharing disabled with https://github.com/brave/brave-browser/issues/15008 in browser version 1.23

Security review for this feature was recently done and was approved:
https://github.com/brave/security/issues/450

No calls are being made to Google (or elsewhere) to generate the code OR for the URL generated (ex: it's not using a redirect link)

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with build 

Brave | 1.26.24 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:
1. new profile, started Brave
2. loaded `brave.com`
3. clicked inside the location bar
4. clicked on the windows-looking QR code icon, to the left of the Brave Shield icon
5. confirmed that scanning the QR code loaded `brave.com`
6. confirmed that scanning the downloaded PNG of the QR code took me to `brave.com`
7. changed the prepopulated URL to `https://www.mozilla.org/en-US/404`, confirmed that the QR-code image updated
8. scanned the new QR code, both inline and downloaded, and confirmed it took me to the newly-inputted URL (`https://www.mozilla.org/en-US/404`)

example | example | brave.com QR code | example | mozilla.org/en-US/404 QR code
---------|----------|---------|---------|----------
<img width="1634" alt="Screen Shot 2021-05-18 at 2 03 44 PM" src="https://user-images.githubusercontent.com/387249/118723542-67638780-b7e2-11eb-9b69-b70457befb70.png"> | <img width="1748" alt="Screen Shot 2021-05-18 at 2 03 49 PM" src="https://user-images.githubusercontent.com/387249/118723549-6af70e80-b7e2-11eb-9389-7763dfd71d72.png"> | ![qrcode_brave com](https://user-images.githubusercontent.com/387249/118723765-a4c81500-b7e2-11eb-92db-90f205b35b79.png) | <img width="1748" alt="Screen Shot 2021-05-18 at 2 08 48 PM" src="https://user-images.githubusercontent.com/387249/118723796-b0b3d700-b7e2-11eb-9cc4-655b5ba62941.png"> | ![qrcode_www mozilla org-404](https://user-images.githubusercontent.com/387249/118723935-da6cfe00-b7e2-11eb-968a-cca746d15c14.png)
