### ISSUE TITLE
Android 1.24.x can't retrieve Referral codes from google play services

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#15903]
## Description 
Android 1.24.x can't retrieve Referral codes from google play services. According to @samartnik, this is due to a change in the abb format.

## Steps to reproduce 

   1. Uninstall Brave from Android. 
   2. Navigate to brave.com/?ref=TVT141 in Chrome or some other browser
   3. Use the link to download brave
   4. Check `brave://local-state`

## Actual result 
`download_id` missing. `referral_code` is `BRV001` (default)

## Expected result

`download_id` should be present. `referral_code` should be `TVT141`

## Issue reproduces how often 
Always

## Version/Channel Information:

1.24.x

- Can you reproduce this issue with the current Play Store version? 
y
- Can you reproduce this issue with the current Play Store Beta version?
n/a 
- Can you reproduce this issue with the current Play Store Nightly version?
n/a
## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.24.85

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using `1.24.86 Chromium: 90.0.4430.212`

```
"referral": {
         "download_id": "e93fb9f7-2d1e-41e4-b573-f1490ed4140c",
         "headers": [ {
            "cookieNames": [  ],
            "domains": [ "eaff.com", "stg.eaff.com" ],
            "expiration": 31536000000.0,
            "headers": {
               "X-Brave-Partner": "eaff"
            }
         }, {
            "cookieNames": [  ],
            "domains": [ "sandbox.uphold.com", "api-sandbox.uphold.com", "uphold.com", "api.uphold.com" ],
            "expiration": 31536000000.0,
            "headers": {
               "X-Brave-Partner": "uphold"
            }
         }, {
            "cookieNames": [  ],
            "domains": [ "www.grammarly.com", "grammarly.com", "static.grammarly.com", "gnar.grammarly.com" ],
            "expiration": 31536000000.0,
            "headers": {
               "X-Brave-Partner": "grammarly"
            }
         } ],
         "initialization": true,
         "promo_code": "TVT141"
      },
      "referral_android_first_run_timestamp": "13265978169564063",
      "stats": {
         "first_check_made": true,
         "last_check_month": 5,
         "last_check_woy": 20,
         "last_check_ymd": "2021-05-20",
         "threshold_query": "https://laptop-updates.brave.com/1/usage/brave-core-threshold?platform=android-bc&channel=release&version=1.24.86&daily=true&weekly=true&monthly=true&first=true&woi=2021-05-17&dtoi=2021-05-20&ref=TVT141&adsEnabled=false&arch=",
         "week_of_installation": "2021-05-17"
      }
```

![Screenshot_20210520-055639_Brave](https://user-images.githubusercontent.com/2602313/118960064-e666d600-b930-11eb-8a8a-89d1c154d293.jpg)
