### ISSUE TITLE
Implement 1p Ephemeral Storage Functionality (functionality)

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#15906]
It would be useful to be able to have Brave visit a site where 1p-storage was ephemeral, in the same way 3p storage is currently by default.

The functionality described here is not intended to cover the settings and options Brave would expose to users (that might or might not change), only to describe the needed underlying capabilities.  How 1p ephemeral storage capabilities could be exposed to users, or deployed to benefit users, is covered in other issues (e.g., https://github.com/brave/brave-browser/issues/15097, https://github.com/brave/brave-browser/issues/15018, etc)

### This would include the following necessary functionality:
- "1p ephemeral storage sessions" are at site granularity
- DOM storage and cookies in a "1p ephemeral storage session" would be cleared as soon as there have been no top level documents open for the site, for more than <keep alive> seconds
- Other `NetworkIsolationKey` partitioned storage (HTTP cache, service workers, network cache, etc) would be similarly partitioned 

### Nice to have:
- "1p ephemeral storage sessions" are isolated from the site's normal storage area.  This means that I should be able to have example.org open in a tab using a standard shields configuration, then open a new example.org tab in "1p ephemeral storage" mode, and that storage set in the "1p ephemeral storage" session would be independent of the standard example.org tab
- Similarly, you could have two different, independent "1p ephemeral storage sessions" at the same time, with the same site, both of which would be independent of standard 1p storage
- "1p ephemeral storage session" tabs taint each other, using sessionStorage logic.  So if I open a example.org in a "1p ephemeral storage session", and then i open another top level document in the same site from that document, both tabs see the same "1p ephemeral storage area".  (This might seem obvious, but I imagine it gets tricky when you could have 2 or more separate  "1p ephemeral storage sessions" with the same site.)

**Comment by bridiver** [comment]
"Nice to have" is kind of a problem because I'm not sure what needs to be validated here or what happens to those things if we only implement part of this and do the rest later. Can we either create sub-tickets for this that exactly match the functionality in each PR or narrow down exactly what we are/have implemented?

**Comment by stephendonner** [comment]
### Verified `PASSED` using

Brave | 1.32.74 Chromium: 95.0.4638.54 (Official Build) dev (x86_64)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | macOS Version 11.6 (Build 20G165)

#### Steps:
1. new profile
2. launched Brave
3. enabled `First Party Ephemeral Storage` feature via `brave://flags`
4. added `[*.]yandex.com to `Always clear cookies when windows are closed`, in `brave://settings/cookies`
5. opened `https://yandex.com/internet` 5x (5 tabs)
6. noted the value of `Content` for the above
7. closed all tabs and windows (but not Brave)
8. opened `https://yandex.com/internet` in a single tab
9. noted the value of `Content` for the above

Confirmed `Content` is different for the 1) group of 5 tabs with the same URL 2) same URL in a single tab


example | example
---------|---------
<img width="1748" alt="Screen Shot 2021-10-19 at 3 55 15 PM" src="https://user-images.githubusercontent.com/387249/138002171-d7b860e7-03f1-4cce-abf6-bd65a27f0295.png"> | <img width="1770" alt="Screen Shot 2021-10-19 at 3 56 07 PM" src="https://user-images.githubusercontent.com/387249/138002196-bb4c738a-ad34-4a8c-ae50-fd74318b8783.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.32.77 Chromium: 95.0.4638.54 (Official Build) dev (x86_64)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. new profile
2. launch Brave
3. added `[*.]yandex.com` to `Always clear cookies when windows are closed`, in `brave://settings/cookies`
4. loaded `yandex.com/internet` in 5 new tabs
5. noted the value for `yandexuid` was `83902131634853864`, across all 5 tabs
6. closed all tabs (but NOT the browser)
7. loaded `yandex.com/internet` again in a single tab
8. noted the value for `yandexuid` was `3676166601634853957`

example | example | example | example
---------|---------|----------|---------
<img width="1312" alt="Screen Shot 2021-10-21 at 2 56 02 PM" src="https://user-images.githubusercontent.com/387249/138364024-528c93f9-7f96-465b-8ca2-777265b49ff2.png"> | <img width="1312" alt="Screen Shot 2021-10-21 at 3 05 30 PM" src="https://user-images.githubusercontent.com/387249/138364028-b12afafd-5cb7-4e4c-b40a-413434bac584.png"> | <img width="1312" alt="Screen Shot 2021-10-21 at 3 05 36 PM" src="https://user-images.githubusercontent.com/387249/138364029-8adb97ef-358f-4a46-a4d1-2a14a4d65288.png"> | <img width="1312" alt="Screen Shot 2021-10-21 at 3 06 04 PM" src="https://user-images.githubusercontent.com/387249/138364031-e3979dff-dfcb-43a7-989c-277db36594dc.png">

**Comment by stephendonner** [comment]
@goodov: I've tried to find the Android corollary, here, but so far am not finding it.

I'm not seeing a place where we can add the exception, noted in step 3, above, "added `[*.]yandex.com` to `Always clear cookies when windows are closed`, in `brave://settings/cookies`"

We have "Close tabs on exit," but that's for browser-session behavior, as is `Clear data on exit.`

**Comment by goodov** [comment]
> @goodov: I've tried to find the Android corollary, here, but so far am not finding it.
> 
> I'm not seeing a place where we can add the exception, noted in step 3, above, "added `[*.]yandex.com` to `Always clear cookies when windows are closed`, in `brave://settings/cookies`"
> 
> We have "Close tabs on exit," but that's for browser-session behavior, as is `Clear data on exit.`

Huh, you're right. This option is not available on Android, but it's just a UI limitation, under the hood it should work. I guess we have to add this setting then.

**Comment by stephendonner** [comment]
> > @goodov: I've tried to find the Android corollary, here, but so far am not finding it.
> > I'm not seeing a place where we can add the exception, noted in step 3, above, "added `[*.]yandex.com` to `Always clear cookies when windows are closed`, in `brave://settings/cookies`"
> > We have "Close tabs on exit," but that's for browser-session behavior, as is `Clear data on exit.`
> 
> Huh, you're right. This option is not available on Android, but it's just a UI limitation, under the hood it should work. I guess we have to add this setting then.

Filed https://github.com/brave/brave-browser/issues/19476 to address this (which might/probably depends on another issue).
