### ISSUE TITLE
Disable Live Caption feature for now

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#15902]
We need investigate more to address https://github.com/brave/brave-browser/issues/15864, but for now let's turn off the feature so that the UI doesn't show up since the feature doesn't work in Brave.

QA:
Test the original STRs in the issue above to make sure there is no live caption toggle in the media console

**Comment by srirambv** [comment]
Removing Android label as there is `Live Caption` flag in `chrome://flags` and no media control in toolbar.
![image](https://user-images.githubusercontent.com/17010094/119096187-2ac6a480-ba0b-11eb-81c0-0f7c2a0a2ae4.png)

**Comment by xplshn** [comment]
4 years later. Will we get this very important accessibility feature back?
