### ISSUE TITLE
Importing index_files directory of IPFS-imported page times out

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15907]
## Description 

Importing index_files directory of IPFS-imported page times out

(This is edge case, I know, but wanted to get it logged, all the same.)

## Steps to Reproduce

   1. new profile
   2. load `ipns://brantly.eth`
   3. choose `Use a local node` on the interstitial page
   4. load `https://www.wikipedia.org`
   5. context-click page and choose `Import to IPFS` -> `This page`
   6. load `brave://ipfs-internals`
   7. click on `My Node`
   8. click on `Files` and then the `brave-imports` directory
   9. navigate through to the `index_files` directory
   10. now, context-click the page and choose `Import to IPFS` -> `This page` again
   11. wait a long time

## Actual result:

After some time, we get a `504 Gateway Time-out`

<img width="1707" alt="Screen Shot 2021-05-17 at 2 25 05 PM" src="https://user-images.githubusercontent.com/387249/118558877-14bf9800-b71c-11eb-8ba4-e22630bd6a8e.png">

## Expected result:

Not sure what should happen, exactly, as this is pretty edge-case.  But it should either work, or fail sooner, I'd think

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.25.60 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | macOS Version 11.3.1 (Build 20E241)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

**Comment by spylogsster** [comment]
blocked imports form api origins

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplans, both inline, here, and from https://github.com/brave/brave-core/pull/8980, with build 

Brave | 1.27.37 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.5 (Build 20G5023d)

Steps:

1. new profile
2. load `ipns://brantly.eth`
3. choose Use a local node on the interstitial page
4. load `https://www.wikipedia.org`
5. context-click page and choose `Import to IPFS` -> This page`
6. load `brave://ipfs-internals`
7. click on `My Node`
8. click on Files and then the `brave-imports` directory
9. navigate through to the `index_files` directory
10. context-clicked the page and confirmed the `Import to IPFS` -> `This page` option isn't present any longer

<img width="1592" alt="Screen Shot 2021-06-02 at 7 50 00 PM" src="https://user-images.githubusercontent.com/387249/120579368-3e471780-c3dc-11eb-9245-ad2c5ddccea1.png">
