### ISSUE TITLE
Suggestion: Detection area for show "On mouseover" is too wide

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#15913]
## Description 

When set to `On mouseover` I found myself accidentally activating sidebar when trying to access content on the left side of the page. Typically happens when sites have nav/menus on left side of the screen, but also for Youtube's web player (video below).

## Steps to Reproduce

   1. Set sidebar to `On mouseover`
   2. Visit sites with left-aligned content (ex youtube, reddit, wikipedia)
   3. Observe the potential for sidebar to interrupt your action

## Actual result:

Video -- note that I'm doing this slowly to illustrate, but this happened a several times in earnest before filing this:

https://user-images.githubusercontent.com/3299098/118575395-38dea180-b73b-11eb-84e8-a2cb7e2da8d2.mov

## Reproduces how often: 

Easily

## Brave version (brave://version info)

1.26

**Comment by simonhong** [comment]
cc @karenkliu I think it would be fine to use more narrower detect area.

**Comment by karenkliu** [comment]
@simonhong sounds good to me!

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.27.10 Chromium: 91.0.4472.70&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | fe095368270a32c92959403754bf6fd357dd9953-refs/branch-heads/4472@{#1172}
OS | macOS Version 11.3.1 (Build 20E241)

![sidebar-width](https://user-images.githubusercontent.com/387249/119205902-73ec1800-ba4e-11eb-978d-ef8120539560.gif)


This worked really well for me; would love your feedback of course, @Brave-Matt - thanks for flagging and filing this! 👍
