### ISSUE TITLE
`#brave-rewards-verbose-logging` missing from Android - follow up to `#15661`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#15924]
## Description 

We're missing the `#brave-rewards-verbose-logging` on `Android`. This should have been added via https://github.com/brave/brave-core/pull/8767. We'll need to get this fixed so @brave/rewards-support has the necessary tools to support users having issues with rewards.

## Steps to reproduce 

   1. launch brave (`1.26.21 Chromium: 91.0.4472.57` in this case)
   2. go into `brave://flags` and search for `verbose`
   3. notice that `#brave-rewards-verbose-logging` is missing

## Actual result 

Missing  `#brave-rewards-verbose-logging` from `brave://flags`

## Expected result

Should add ` #brave-rewards-verbose-logging` into `brave://flags` as per https://github.com/brave/brave-core/pull/8767.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `N/A`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 11`
   
## Brave version

Using ``1.26.21 Chromium: 91.0.4472.57`

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @rebron @zenparsing @LaurenWags @srirambv @bsclifton @Miyayes

**Comment by kjozwiak** [comment]
Related to https://github.com/brave/brave-core/pull/8598 & https://github.com/brave/brave-core/pull/8767. Can verify the following three issues at the same time:

* https://github.com/brave/brave-browser/issues/15500
* https://github.com/brave/brave-browser/issues/15661

**Comment by srirambv** [comment]
Verification passed on following devices running 1.25.66 x64 build
- Verified flag is available under chrome://flags
- Verified enabling the flag prompts for restart
- Verified after enabling the flag logs are captured under chrome://rewards-internals

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/119454651-ad63a280-bd30-11eb-873d-fe5b422e16b0.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/119454667-b2c0ed00-bd30-11eb-8cc5-0928613541c2.png>
