### ISSUE TITLE
Brave News should require hard opt-in

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#15926]
Previously it was deemed ok to not require an explicit opt-in for Brave News' remote network fetch because:

1. It waited for user interaction with the feature before making any network requests. In other words, it did not request data for the feature if the user did not actively use it, whether it was already on for that user's region or not.
2. The network requests use Brave's Private CDN, meaning no identity or behaviorally-identifiable information is transmitted. Every user requests the same feed, and the specific article images are all padded to be the same size.

However, in the interests of caution we want to require the users to explicitly opt-in to the feature, including the privacy policy, before making any network requests.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

### Migration - have previously used Brave Today in `1.25.68`

<details>

Steps:

1. new profile, launch `1.25.68`
2. open a new-tab page
3. click on `Customize`
4. click on `Brave Today`
5. ensure `Show Brave Today` is defaulted to `On`
6. scroll down and view a few sheets worth of Brave Today articles
7. quit Brave
8. save profile off
9. install `1.26.43`
10. rename original profile to Brave-Browser-Beta
11. launch `1.26.43`
12. open a new-tab page
13. scroll down
14. confirm you get shown a panel with `Show Brave News` and `No thanks`
15. click on `No thanks`
16. confirm the panel is dismissed, and Brave News doesn't display
17. click on `Customize`
18. click on `Brave News`
19. click the toggle for `Show Brave News` to `On`
20. click the `X` to dismiss the dialog
21. scroll down
22. confirm you see the panel again
23. this time, click on `Show Brave News`
24. confirm Brave News' content now displays

example | example | example | example | example | example
---------|---------|----------|----------|---------|----------
<img width="1056" alt="Screen Shot 2021-05-27 at 2 41 20 PM" src="https://user-images.githubusercontent.com/387249/119901257-8789f980-befa-11eb-8a3d-80a91478679f.png"> | <img width="1056" alt="Screen Shot 2021-05-27 at 2 41 27 PM" src="https://user-images.githubusercontent.com/387249/119901258-88229000-befa-11eb-936e-eebee30e4cb2.png"> | <img width="1056" alt="Screen Shot 2021-05-27 at 2 42 57 PM" src="https://user-images.githubusercontent.com/387249/119901259-88229000-befa-11eb-8043-3bde79d90956.png"> | <img width="1056" alt="Screen Shot 2021-05-27 at 2 43 06 PM" src="https://user-images.githubusercontent.com/387249/119901260-88bb2680-befa-11eb-8ab6-0901b65ce5f9.png"> | <img width="1056" alt="Screen Shot 2021-05-27 at 2 43 13 PM" src="https://user-images.githubusercontent.com/387249/119901262-88bb2680-befa-11eb-8b67-4cd4d4405e1b.png"> | <img width="1056" alt="Screen Shot 2021-05-27 at 2 43 28 PM" src="https://user-images.githubusercontent.com/387249/119901263-8953bd00-befa-11eb-9fd8-9bae711237b2.png"> | <img width="1056" alt="Screen Shot 2021-05-27 at 2 43 34 PM" src="https://user-images.githubusercontent.com/387249/119901266-89ec5380-befa-11eb-90d3-a69c55edbf83.png">

</details>

### Migration - have NOT previously used Brave Today in `1.25.68`

<details>

Steps:

1. new profile, launch `1.25.68`
2. open a new-tab page
3. click on `Customize`
4. click on `Brave Today`
5. ensure `Show Brave Today` is defaulted to `On`
6. do **NOT** scroll down
7. quit Brave
8. save profile off
9. install `1.26.43`
10. rename original profile to Brave-Browser-Beta
11. launch `1.26.43`
12. open a new-tab page
13. scroll down
14. confirm you get shown a panel with `Show Brave News` and `No thanks`
15. click on `No thanks`
16. confirm the panel is dismissed, and Brave News doesn't display
17. click on `Customize`
18. click on `Brave News`
19. click the toggle for `Show Brave News` to `On`
20. click the `X` to dismiss the dialog
21. scroll down
22. confirm you see the panel again
23. this time, click on `Show Brave News`
24. confirm Brave News' content now displays

example | example | example | example | example | example
---------|----------|---------|----------|---------|----------
<img width="1312" alt="Screen Shot 2021-05-27 at 2 53 49 PM" src="https://user-images.githubusercontent.com/387249/119902332-f025a600-befb-11eb-8654-e352ac1ae815.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 2 54 33 PM" src="https://user-images.githubusercontent.com/387249/119902334-f0be3c80-befb-11eb-9247-cd7e693765b2.png">
<img width="1312" alt="Screen Shot 2021-05-27 at 2 54 54 PM" src="https://user-images.githubusercontent.com/387249/119902338-f156d300-befb-11eb-9bbc-6e5d79530ea2.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 2 55 01 PM" src="https://user-images.githubusercontent.com/387249/119902352-f582f080-befb-11eb-92e1-2e76c358afe3.png">
<img width="1312" alt="Screen Shot 2021-05-27 at 2 55 21 PM" src="https://user-images.githubusercontent.com/387249/119902354-f74cb400-befb-11eb-9980-51d2e8b155fd.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 2 55 34 PM" src="https://user-images.githubusercontent.com/387249/119902360-f9167780-befb-11eb-90a7-6ebae884634a.png">

</details>

### New profile - `1.26.43`

<details>

1. new profile, launch `1.26.43`
2. open a new-tab page
3. click on `Customize`
4. click on `Brave Today`
5. ensure `Show Brave Today` is defaulted to `On`
6. scroll down
7. confirm you get shown a panel with `Show Brave News` and `No thanks`
8. click on `No thanks`
9. confirm the panel is dismissed, and Brave News doesn't display
10. click on `Customize`
11. click on `Brave News`
12. click the toggle for `Show Brave News` to `On`
13. click the X to dismiss the dialog
14. scroll down
15. confirm you see the panel again
16. this time, click on `Show Brave News`
17. confirm Brave News' content now displays

example | example | example | example | example
---------|---------|----------|----------|---------
<img width="1106" alt="Screen Shot 2021-05-27 at 3 01 25 PM" src="https://user-images.githubusercontent.com/387249/119902948-c8830d80-befc-11eb-99d4-04185df669d0.png"> | <img width="1106" alt="Screen Shot 2021-05-27 at 3 01 30 PM" src="https://user-images.githubusercontent.com/387249/119902950-c91ba400-befc-11eb-8841-c14e1d49bfee.png"> | <img width="1106" alt="Screen Shot 2021-05-27 at 3 01 37 PM" src="https://user-images.githubusercontent.com/387249/119902951-c9b43a80-befc-11eb-8d72-e5fee4d5bbd9.png"> | <img width="1106" alt="Screen Shot 2021-05-27 at 3 01 57 PM" src="https://user-images.githubusercontent.com/387249/119902952-c9b43a80-befc-11eb-886a-7ee24ae42f36.png"> | <img width="1106" alt="Screen Shot 2021-05-27 at 3 08 01 PM" src="https://user-images.githubusercontent.com/387249/119903284-5ced7000-befd-11eb-9433-67df5a2c3c19.png">


</details>


Filed https://github.com/brave/brave-browser/issues/15977 for the Brave News source list showing `0` in the `Customize Dashboard`'s `Brave News` panel, when not-yet opted in.
