### ISSUE TITLE
Brave Today should be renamed Brave News in the UI

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#15925]
All UI mentions for Brave Today should be renamed to Brave News.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.26.30 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

Checked the following places:

`Scroll for Brave News` call to action | `Brave News` in both description and button text for opt-in | `Customize Dashboard` widget header link and header | `Reset Brave News sources` link and dialog text
---------|---------|-----------|---------
<img width="1312" alt="Screen Shot 2021-05-19 at 12 23 48 PM" src="https://user-images.githubusercontent.com/387249/118877151-ed470780-b8a2-11eb-9f17-7af98e0206e9.png"> | <img width="1312" alt="Screen Shot 2021-05-19 at 12 24 46 PM" src="https://user-images.githubusercontent.com/387249/118877152-eddf9e00-b8a2-11eb-87a8-735e2d00a7fa.png"> | <img width="1312" alt="Screen Shot 2021-05-19 at 12 25 13 PM" src="https://user-images.githubusercontent.com/387249/118877153-ee783480-b8a2-11eb-9107-669011eac474.png"> | <img width="1312" alt="Screen Shot 2021-05-19 at 12 29 26 PM" src="https://user-images.githubusercontent.com/387249/118877155-ee783480-b8a2-11eb-9b95-e04847a885b3.png">

Filed https://github.com/brave/brave-browser/issues/15975 to cover the Brave News error page text, as a follow-up.
