### ISSUE TITLE
New Tab Page icons are outdated

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#1593]
## Muon
![image](https://user-images.githubusercontent.com/741836/46975815-7dce6300-d07c-11e8-9324-188ad9281665.png)

## Brave-Core
![image](https://user-images.githubusercontent.com/741836/46975825-845cda80-d07c-11e8-89b7-938ee0fee5c5.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

* Verified new tab page icons match those on screenshots from https://github.com/brave/brave-core/pull/1091
![screen shot 2019-02-05 at 4 21 30 pm](https://user-images.githubusercontent.com/28145373/52305064-325cff00-2962-11e9-9d8d-f317577f80d9.png)
