### ISSUE TITLE
Back button is not properly aligned on FTX widget

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15930]
## Description 

Back button is not properly aligned on FTX widget

## Steps to Reproduce

   1. Install/Update to 1.26.22 Nightly build
   2. Open FTX widget and open futures market
   3. Back button is centre aligned rather than next to widget menu

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/118645807-4ea1a480-b7d7-11eb-817f-5a728b55601a.png)

## Expected result:
Similar to Crypto.com widget

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --
Revision | `e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA 
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @simonhong @petemill

**Comment by simonhong** [comment]
Fixed by https://github.com/brave/brave-core/pull/8947

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.26.63 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | macOS Version 10.15.7 (Build 19H114)

- Verified back button is properly aligned 

https://user-images.githubusercontent.com/17010094/122435989-5f893580-cf90-11eb-9c0c-b5fa94c292df.mov

---------
Verification passed on 

Brave | 1.26.63 Chromium: 91.0.4472.106 (Official Build) (64-bit)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | Linux

- Verified back button is properly aligned

https://user-images.githubusercontent.com/17010094/122435828-3d8fb300-cf90-11eb-8b73-f87a22d04c99.mov

---------
Verification passed on 

Brave | 1.26.63 Chromium: 91.0.4472.106 (Official Build) (64-bit)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | Windows 10 OS Version 2009 (Build 19042.1052)

- Verified back button is properly aligned

https://user-images.githubusercontent.com/17010094/122435688-1df88a80-cf90-11eb-8287-71be3a927f9a.mov
