### ISSUE TITLE
Share local file/dir using IPFS does not work on desktop

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#15935]
## Description + Steps to Reproduce

Clicking on the menu item does nothing:

![2021-05-18--16-16-30](https://user-images.githubusercontent.com/157609/118667589-705d5480-b7f4-11eb-82b6-071ad7aeb686.png)

## Actual result:

Nothing happens, no error in console

## Expected result:

File/dir picker is opened?

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Nightly v1.26.22 for Linux (`brave-browser-nightly-1.26.22-linux-amd64`)

```

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;unknown&nbsp;(64-bit)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | Linux
JavaScript | V8&nbsp;9.1.269.28
User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.57 Safari/537.36
Command Line | /home/lidel/project/ipfs-companion/vendor/brave-browser-nightly-1.26.22-linux-amd64/brave --user-data-dir=/home/lidel/TODO/BRAVE-go-ipfs-7-to-9-test --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,AutoupgradeMixedContent,SafetyTip,DnsOverHttps,LegacyTLSEnforced,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=IdleDetection,LangClientHintHeader,NetworkTimeServiceQuerying,AutofillServerCommunication,SharingQRCodeGenerator,DirectSockets,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,WebOTP,NotificationTriggers,InterestCohortFeaturePolicy,FlocIdComputedEventLogging,FederatedLearningOfCohorts,TextFragmentAnchor,AutofillEnableAccountWalletStorage,InterestCohortAPIOriginTrial,FirstPartySets,SignedExchangeSubresourcePrefetch,TabHoverCards,EnableProfilePickerOnStartup --flag-switches-begin --flag-switches-end
Executable Path | /home/lidel/project/ipfs-companion/vendor/brave-browser-nightly-1.26.22-linux-amd64/brave
Profile Path | /home/lidel/TODO/BRAVE-go-ipfs-7-to-9-test/Default
```

**Comment by stephendonner** [comment]
Thanks for filing, @lidel - same on macOS and Windows 10, both latest `nightly` builds of `1.26.x`

**Comment by stephendonner** [comment]
@spylogsster can you please take a look, as fixing this will unblock further testing/verifications; thanks!

**Comment by stephendonner** [comment]
@bridiver I think https://github.com/brave/brave-core/pull/8888 has the wrong issue # in its commit message, as this is/should be fixed by https://github.com/brave/brave-core/pull/8856 instead, no?

**Comment by stephendonner** [comment]
**Verified `FIXED`** on `nightly` with the testplan from https://github.com/brave/brave-core/pull/8856 using build 

Brave | 1.27.10 Chromium: 91.0.4472.70&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | fe095368270a32c92959403754bf6fd357dd9953-refs/branch-heads/4472@{#1172}
OS | macOS Version 11.5 (Build 20G5023d)

### Confirm that IPFS item is not visible in main app menu if IPFS daemon is not launched

#### Steps:

1. new profile
2. load `ipns://brantly.eth` to trigger interstitial page
3. click on `Use a local node`
4. confirm the IPFS daemon is running via `brave://ipfs-internals`
5. click on the "hamburger" menu in the browser toolbar, and choose `IPFS`
6. choose `Share Local File Using IPFS` and confirm it invokes a file picker
7. click `Cancel`
8. choose `Share Local Folder Using IPFS` and confirm it invokes a directory picker
9. click `Cancel`
10. load `brave://ipfs-internals/` and click `Stop`
11. click again on the "hamburger" menu in the browser toolbar, and confirm the `IPFS` menu is now gone

example | example
---------|---------
<img width="1585" alt="Screen Shot 2021-05-22 at 9 31 11 AM" src="https://user-images.githubusercontent.com/387249/119234036-8d3da480-bae0-11eb-8e68-cd7ae4d67cc8.png"> | <img width="1585" alt="Screen Shot 2021-05-22 at 9 31 17 AM" src="https://user-images.githubusercontent.com/387249/119234041-8f076800-bae0-11eb-966f-daf66c771d53.png">


### Pinning with IPFS keys works as expected

#### Steps:

1. new profile
2. load `ipns://brantly.eth` to trigger interstitial page
3. click on `Use a local node`
4. confirm the IPFS daemon is running via `brave://ipfs-internals`
5. click on the "hamburger" menu in the browser toolbar, and choose `IPFS`
6. open `brave://settings/ipfs/keys` and click `Add`
7. type `newkey1` and click `Generate`
8. load `https://shipitsquirrel.github.io/images/ship%20it%20squirrel.png` and save it
9. click on the "hamburger" menu again and choose `IPFS` -> `Share Local File Using IPFS` -> `newkey1`
10. wait (can take a while, just be patient)
11. confirmed got link with hash: `https://dweb.link/ipns/k51qzi5uqu5dl39f66wz9q1687iizxyhlsb9m23z75p6fpoxrykss373wt5434?filename=ship+it+squirrel.png`
12. compared hash from step 11 with hash from the key generated for `newkey1` in step 7, via `brave://settings/ipfs/keys`
13. repeated steps 9-12, but with a saved directory of files, and ensured it's signed when published

example | example | example | example
---------|---------|----------|---------
<img width="1672" alt="Screen Shot 2021-05-21 at 11 52 20 PM" src="https://user-images.githubusercontent.com/387249/119233888-e0fbbe00-badf-11eb-89f6-e58eb003dcdc.png"> | <img width="1672" alt="Screen Shot 2021-05-21 at 11 53 12 PM" src="https://user-images.githubusercontent.com/387249/119233892-e35e1800-badf-11eb-900c-d4b105b182ed.png"> | <img width="1672" alt="Screen Shot 2021-05-21 at 11 53 47 PM" src="https://user-images.githubusercontent.com/387249/119233896-e5c07200-badf-11eb-9ff5-58b32c6652b2.png"> | <img width="1379" alt="Screen Shot 2021-05-21 at 11 55 29 PM" src="https://user-images.githubusercontent.com/387249/119233898-e6590880-badf-11eb-950a-90c0348678ca.png">

Filed https://github.com/brave/brave-browser/issues/16039 and https://github.com/brave/brave-browser/issues/16040 while testing.
