### ISSUE TITLE
brave constantly crashes

### ISSUE THREAD

**Issue by thegreatyellow67** [brave/brave-browser#15932]
Hi, I'm using Brave Browser in an Archlabs Linux machine with Openbox, linux kernel 5.10.37-1-lts.

Today Brave suddenly refuses to be stable, I've tried to delete BraveSoftware folder in .config and .cache, I've tried all the avaliable versions in the AUR repository (brave-bin, brave-beta-bin, brave-nightly-bin), but nothing, after 10/15 seconds the app refuses to work and crashes! I've tried to run it from browser and the message is:

(brave:55716): Gtk-WARNING **: 14:54:47.814: Theme parsing error: gtk.css:10771:9: 'spacing' is not a valid property name
[55752:55752:0518/145448.282190:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[55716:55716:0518/145448.967034:ERROR:profile_attributes_storage.cc(548)] Failed to PNG encode the image.
Segmentation fault (core dumped)

I've also tried to tun brave from terminal with option --no-xshm, but same error:

(brave:56975): Gtk-WARNING **: 14:56:12.764: Theme parsing error: gtk.css:10771:9: 'spacing' is not a valid property name
[57008:57008:0518/145613.255289:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[56975:56975:0518/145613.882090:ERROR:profile_attributes_storage.cc(548)] Failed to PNG encode the image.
Segmentation fault (core dumped)

Can anyone tell me how to fix this? I used the browser until yesterday, then maybe an update broke my browser?

**Comment by thegreatyellow67** [comment]
Very strange, I'm sorry, but after about half an a hour Brave seems to work again! No crashes...what?!?!?!? So confused...

**Comment by ryanbr** [comment]
Hey, I would toggle Hardware Acceleration via `brave://settings/extensions`  if it occurs again @thegreatyellow67

**Comment by thegreatyellow67** [comment]
Thanks for your reply. I have been using brave browser for a very long time, in various linux distributions, but I have never had problems like I did today. Now everything is working properly.
