### ISSUE TITLE
Sidebar "+" button hover state won't go away

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#15945]
## Description 

The "+" add button now shows the add menu hover correctly, but the hover color doesn't go away. It seems to reset though if you hide the sidebar and show it again.

## Steps to Reproduce

   1. Hover over the "+" button
   2. Add menu shows
   3. Hover off / click off the menu; see that the hover color doesn't go away

## Actual result:

![2021-05-18 09-29-17 2021-05-18 09_29_38](https://user-images.githubusercontent.com/2388823/118692097-936d1180-b7be-11eb-9b7a-56d3354bd6d4.gif)

## Expected result:
Hover color should go away

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.26.22 Chromium: 91.0.4472.57 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release?   no
- Can you reproduce this issue with the beta channel?  no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/8877 with build

Brave | 1.27.10 Chromium: 91.0.4472.70&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | fe095368270a32c92959403754bf6fd357dd9953-refs/branch-heads/4472@{#1172}
OS | macOS Version 11.3.1 (Build 20E241)

The sidebar's "+" button state now correctly shows the hover state as active and inactive, as appropriate.

![hover-state](https://user-images.githubusercontent.com/387249/119205693-cf69d600-ba4d-11eb-8c79-236826589892.gif)
