### ISSUE TITLE
Back button on FTX is always shown 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15941]
## Description 

Back button on FTX is always shown 

## Steps to Reproduce

   1. Install 1.26.22 nightly build
   2. Open Futures market on FTX widget
   3. Background the widget, back button is still shown all the time

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/118679623-ef9f5800-b7f5-11eb-8202-6d21f5fdde02.png) | ![image](https://user-images.githubusercontent.com/17010094/118679727-08a80900-b7f6-11eb-8faa-6c060d43f52f.png) | ![image](https://user-images.githubusercontent.com/17010094/118679756-0fcf1700-b7f6-11eb-9a8a-15d741ea24a5.png)
-- | -- | --

## Expected result:
Back button on the widget should only be shown when the widget is in foreground

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --
Revision | `e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @petemill @simonhong

**Comment by petemill** [comment]
Hmm I think the back button with some space, like FTX is probably best. The solution here is probably to hide the back button when the widget is not in the foreground since it won't do anything.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.26.63 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | macOS Version 10.15.7 (Build 19H114)

- Verified back button is only shown when widget is in focus

https://user-images.githubusercontent.com/17010094/122436683-edfdb700-cf90-11eb-9c8c-6092fef38bc5.mov

---------
Verification passed on 

Brave | 1.26.63 Chromium: 91.0.4472.106 (Official Build) (64-bit)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | Linux

- Verified back button is only shown when widget is in focus

https://user-images.githubusercontent.com/17010094/122436928-230a0980-cf91-11eb-95d3-b052bfb12c32.mov

---------
Verification passed on 

Brave | 1.26.63 Chromium: 91.0.4472.106 (Official Build) (64-bit)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | Windows 10 OS Version 2009 (Build 19042.1052)

- Verified back button is only shown when widget is in focus

https://user-images.githubusercontent.com/17010094/122437433-9dd32480-cf91-11eb-8781-ea01e66708e0.mov
