### ISSUE TITLE
Missing tooltip for bottom Settings gear icon in Sidebar

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15948]
## Description 

Missing tooltip for bottom Settings gear icon in Sidebar

## Steps to Reproduce

   1. new profile in `nightly`
   2. enable `Sidebar` via `brave://flags`
   3. mouse over to the left of the screen
   4. mouse over the bottom gears (Settings) icon

## Actual result:

There's no tooltip for the bottom `Settings` gear icon in sidebar

<img width="1390" alt="Screen Shot 2021-05-18 at 11 17 58 AM" src="https://user-images.githubusercontent.com/387249/118706493-43964680-b7ce-11eb-937b-befdc196194e.png">

## Expected result:
Now, navigate to `brave://settings` and click to `Add to Sidebar`
Hover over the just-added Settings gear icon

Its tooltip reads `Settings`

<img width="550" alt="Screen Shot 2021-05-18 at 11 44 41 AM" src="https://user-images.githubusercontent.com/387249/118706655-7cceb680-b7ce-11eb-83d7-baa78124135b.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.26.24 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

@karenkliu @simonhong

**Comment by simonhong** [comment]
@karenkliu How about `Show settings` as a gear button's tooltip?

**Comment by karenkliu** [comment]
@simonhong Sounds good 👍

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.27.8 Chromium: 91.0.4472.70&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | fe095368270a32c92959403754bf6fd357dd9953-refs/branch-heads/4472@{#1172}
OS | macOS Version 11.3.1 (Build 20E241)

Confirmed that the tooltip for the bottom Settings gear icon reads `Show settings`

<img width="138" alt="Screen Shot 2021-05-21 at 11 38 37 AM" src="https://user-images.githubusercontent.com/387249/119183647-3d4fd680-ba29-11eb-8f21-c77678818ee5.png">
