### ISSUE TITLE
Crash when clicking and dragging a hyperlink to the omnibox

### ISSUE THREAD

**Issue by dentistformyeye** [brave/brave-browser#15955]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.24.85  Chromium: 90.0.4430.212
Operating System: Mac OS X 10.15.7

URL (if applicable) where crash occurred:
https://www.reddit.com/r/youtube/comments/nfnrqq/hiking_to_pedra_do_tel%C3%A9grafo4k_brazil_rio_de/
Has also happened on another Reddit post with a YT video. Not sure if the crash is related specifically to Reddit posts or generally to pages that have to load a lot of content.

Can you reproduce this crash?
Yes.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go to the [link](https://www.reddit.com/r/youtube/comments/nfnrqq/hiking_to_pedra_do_tel%C3%A9grafo4k_brazil_rio_de/) above
2. Preferrably before the page finishes loading, quickly click and drag the orange link in the top left of the page to the omnibox and release the mouse button.
![image](https://user-images.githubusercontent.com/51429646/118744640-b0d3c700-b822-11eb-9ea2-3e4ea57da886.png)

3. Refresh and try steps 1-2 repeatedly if there is no crash.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/bbc92c00-b423-5206-0000-000000000000

**Comment by iefremov** [comment]
duplicate https://github.com/brave/brave-browser/issues/13838
