### ISSUE TITLE
Side bar show always doesn't work properly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15958]
## Description 

Side bar show always doesn't work properly

## Steps to Reproduce

   1. Update to nightly
   2. Enable side bar flag
   3. Set it to show on hover, works as expected
   4. Set it show always
   5. Move cursor away from sidebar, hides again
   6. Select show always, sticks properly

## Actual result:

![Sidebar](https://user-images.githubusercontent.com/17010094/118769452-17370480-b878-11eb-9d9f-c05089a284f8.gif)

## Expected result:
Setting should work the first time

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.26.24 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --
Revision | `e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}`
OS | Windows&nbsp;10 OS Version 2009 (Build 19042.985)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @rebron

**Comment by stephendonner** [comment]
Verified `FIXED` using the inline steps with build

Brave | 1.27.25 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1.  new profile, launched Brave
2. enabled sidebar flag
3. set it to `Show on mouseover`, works as expected
4. set it `Show always`
5. moved cursor away from sidebar, it remained, as expected

![sidebar-hover](https://user-images.githubusercontent.com/387249/119911369-13595100-bf0e-11eb-94fc-511552ad6a9c.gif)
