### ISSUE TITLE
New Tab Page localization is partly not implemented

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#1595]
The muon method is still in the code, even though it does not do anything:

- Icon tooltips
- "Photo by" description

## Test plan
- Photo caption should be prefixed with the words "Photo by"

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/47057905-b9f2e800-d190-11e8-90fa-f282c30c7280.png)
