### ISSUE TITLE
Remove Unretained call from key import

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15961]
created from comment https://github.com/brave/brave-core/pull/8777#discussion_r635083457

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8858 with build

Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile, launched Brave
2. opened `brave://settings/ipfs`
3. loaded `ipns://brantly.eth`
4. clicked on `Use a local node`
5. downloaded `http://mirror.sfo12.us.leaseweb.net/speedtest/10000mb.bin`
6. while downloading, closed the `Settings` tab
7. waited for shared IPFS link to get copied to clipboard: `https://dweb.link/ipfs/QmdBjHTfAp1v4DRBeraqSpXqDS4VvHa4RahTTUnZW3Kwsj?filename=10000mb.bin`

Confirmed no crash while doing so; was able to open and save the 9.3 GB file from the above.

example | example | example
---------|---------|----------
<img width="1312" alt="Screen Shot 2021-05-27 at 11 24 34 AM" src="https://user-images.githubusercontent.com/387249/119877881-69160500-bede-11eb-81db-489ebee4899c.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 11 11 16 AM" src="https://user-images.githubusercontent.com/387249/119877576-11779980-bede-11eb-857d-25ae64bffbc1.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 11 11 37 AM" src="https://user-images.githubusercontent.com/387249/119877586-13415d00-bede-11eb-91dc-57797cabfff5.png">
