### ISSUE TITLE
Always show Refresh status for publishers on rewards panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15966]
## Description 
As part of #15154, @Miyayes confirmed that Android should always shows `Refresh Status` button which is not available on Android. This is a follow up for #15154.

## Steps to reproduce 

   1. Clean install build
   2. Enable rewards and visit a verified pub page
   3. Click Refresh button to validate pub status
   4. Once pub is shown as Verified pub, refresh button is not shown again

## Actual result 
Refresh button is not shown once publisher status is updated

## Expected result
Always show Refresh status for publishers on rewards panel

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Miyayes @deeppandya

**Comment by deeppandya** [comment]
![Screenshot_20210603-173110](https://user-images.githubusercontent.com/5146988/120714786-ad327800-c491-11eb-8003-871373094f3e.png)
![Screenshot_20210603-172941](https://user-images.githubusercontent.com/5146988/120714787-adcb0e80-c491-11eb-8b86-26b074eb4d44.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.27.77 x64 Beta build
- Verified refresh status updates the publisher state and is retained
- Verified refresh status is shown always for verified/connected/unverified publishers

https://user-images.githubusercontent.com/17010094/123251039-a91ed680-d4e2-11eb-86b7-e2ca19be6d9c.mp4

------------
Verification passed on Samsung Tab A with Android 10 running 1.27.77 x64 Beta build
- Verified refresh status updates the publisher state and is retained
- Verified refresh status is shown always for verified/connected/unverified publishers

https://user-images.githubusercontent.com/17010094/123250874-7bd22880-d4e2-11eb-8abf-f1fab8625962.mp4
