### ISSUE TITLE
Follow up of #15338- Close button doesn't dismiss the wallet verification error modal

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15963]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/15264
Follow up of #15338- Close button doesn't dismiss the wallet verification error modal

## Steps to Reproduce

   1. Follow the steps from https://github.com/brave/brave-browser/issues/15264#issuecomment-823636938
   

## Actual result:

![Bitflyer_error message validation](https://user-images.githubusercontent.com/38657976/118818834-601ba700-b8d2-11eb-9a1a-d2c206802f9e.gif)

## Expected result:
Click on close should dismiss the  wallet verification error modal

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave	1.25.64 Chromium: 90.0.4430.212 (Official Build) beta （64 ビット）
変更履歴	e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS	Windows 10 OS Version 1809 (Build 17763.1637)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @Miyayes @emerick @rebron

**Comment by LaurenWags** [comment]
reproduces for me on macOS

```
Brave | 1.25.64 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;beta&nbsp;（x86_64）
-- | --
変更履歴 | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | macOS バージョン10.15.7（ビルド19H1030）
```

**Comment by stephendonner** [comment]
@emerick @zenparsing for verification purposes, is there another way to reproduce this dialog/issue, given that bitFlyer isn't hooked up via the feature flag, like it used to be?  Thanks!

**Comment by emerick** [comment]
@stephendonner I think it still uses the feature flag, it's just that the feature defaults to enabled now. Maybe I'm not understanding? I think you can still follow the STR here https://github.com/brave/brave-browser/issues/15264#issuecomment-823636938

**Comment by stephendonner** [comment]
> @stephendonner I think it still uses the feature flag, it's just that the feature defaults to enabled now. Maybe I'm not understanding? I think you can still follow the STR here [#15264 (comment)](https://github.com/brave/brave-browser/issues/15264#issuecomment-823636938)

Sorry, @emerick diregard that comment; I had a typo in my commandline and got production, instead.

Verified `PASSED` using the testplan from https://github.com/brave/brave-browser/issues/15264#issuecomment-823636938 with build 

Brave | 1.27.33 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;（x86_64）
-- | --
変更履歴 | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS バージョン11.4（ビルド20F71）

![bitflyer](https://user-images.githubusercontent.com/387249/120403731-a8d35700-c2f9-11eb-8613-282e4b639b19.gif)
