### ISSUE TITLE
Add setting to change Rewards wallet region

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15968]
## Description

Request from support team: add a way for users to change their Rewards wallet region value more easily. 

_Specifics pending discussion._

**Comment by A-t-s-u-s-h-i** [comment]
I've got some inquiries from Japanese Users who sees Uphold option, but want to verify bitFlyer.
This is the opposite case, it shows bitFlyer option when a user try to verify Uphold.
https://community.brave.com/t/i-need-help-with-uphold-and-bitflyer/249633
