### ISSUE TITLE
Lint issue in BraveActivity on master

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#15978]
## Description 
Lint error 
`
./../brave/android/java/org/chromium/chrome/browser/app/BraveActivity.java:229: Error: Must be one of: TimePeriod.LAST_HOUR, TimePeriod.LAST_DAY, TimePeriod.LAST_WEEK, TimePeriod.FOUR_WEEKS, TimePeriod.ALL_TIME, TimePeriod.OLDER_THAN_30_DAYS, TimePeriod.TIME_PERIOD_LAST [WrongConstant]`

+ build warnings

## Steps to reproduce 

   1. 
   2. 
   3. 

## Actual result 

No errors and no new warning

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Removing this from `1.27.x - Beta` as it's not `release/blocking` and it appears as there's no PRs associated with this issue that landed in `1.27.x`.

**Comment by samartnik** [comment]
This has been fixed https://github.com/brave/brave-core/commit/d990493a20461155719cd6c52ae4ae392848ec26
