### ISSUE TITLE
Low resolution favicons on rewards panel and contribution table

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1597]
## Description 

Rewards panel shows favicons which are pixelated needs to have a high resolution icons 

## Steps to Reproduce

   1. Enable Rewards
   2. Add funds
   3. Visit any site and click the rewards button, see pixelated icons and close it immediately

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46978132-0ad4e480-d09c-11e8-9885-5b1431688354.png)

## Expected result:
Should show proper icons

## Reproduces how often: 

Easy 

## Brave version (chrome://version info)

 
Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Even contribution table has low resolution icons 
![image](https://user-images.githubusercontent.com/17010094/47020516-862fa800-d127-11e8-9392-76da84538ae2.png)

**Comment by NejcZdovc** [comment]
we get this icons from favicon store (chromium has control over it), will try to bump size that we are requesting

**Comment by srirambv** [comment]
@NejcZdovc we might need to bump this one. Looks awfully bad for some sites which has small icons in site favicon
![Pasted_image_at_2019-03-19__10_53_AM](https://user-images.githubusercontent.com/17010094/54616154-a694c300-4a35-11e9-96b7-8300d88daba0.png)

**Comment by jonathansampson** [comment]
This issue impacts our _New Tab Page_ too. For example, consider this icon:  brave://favicon/size/64@1x/http://try.bravesoftware.com/v1/

![image](https://user-images.githubusercontent.com/815158/73408976-7e1b5d80-42c3-11ea-98d0-ec8dc7e3a515.png)

**Comment by NejcZdovc** [comment]
agree, let's go with `64@1x`

**Comment by jonathansampson** [comment]
@NejcZdovc Does 64@1x look good on a high-density display? Or would 128 be more preferable?

**Comment by NejcZdovc** [comment]
I would go with 64 for now and we can always update if needed

**Comment by NejcZdovc** [comment]
Note that if site provides favicon only in resolution 32x32 like pia we can't do anything really about it. It's on sites to provide good resolution
