### ISSUE TITLE
History Sync - Sync Profile Service on iOS

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#15970]
## Description 

**Add support for iOS Chromium History so we can sync them with Desktop.**

1. Create Add - Remove - Query related wrappers for iOS
2. Create Observer methods related with History Service functionality

**Add support for iOS Sync Profile so we can change what types of data should be sync from iOS side.**

1. Create wrapper for Sync Profile Status related data for iOS (isSyncRequested, isSyncFeatureActive etc.)
2. Provide a way to fetch userSelected types and set activeSelectableTypes for iOS side. (This will used in order to activate desired enable desired type on iOS side with toggles)

Corresponding iOS Ticket: https://github.com/brave/brave-ios/issues/3227

**Comment by kjozwiak** [comment]
This will QA'd via the `iOS` issue once this feature lands in the next `iOS` release.
