### ISSUE TITLE
FTX widget should not appear when card setting is turned off

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#15972]
## Description 

For existing users who have the cards settings on the new tab page turned off so that no cards appear, we should not show the FTX widget to these existing users when they upgrade.

## Steps to Reproduce

   1. Use a Brave version lower than 1.26.21 and turn off cards. See image below.
   2. Upgrade to latest 1.26.22 or higher
   3. Notice that the FTX widget will appear as the sole widget on upgrade even though card settings is off.

<img width="411" alt="Screen Shot 2021-05-19 at 11 07 45 AM" src="https://user-images.githubusercontent.com/5951041/118862404-8c173800-b892-11eb-834d-15b0cf7142e1.png">

## Actual result:
FTX widget appears upon upgrade as the sole card in the widget stack for existing users and it comes across as not respecting a setting that was previously set.

## Expected result:
FTX widget should not appear for users who have turned off all cards. If a user has cards enabled, FTX will appear for them as part of the list.

New card tooltip promoting FTX should also appear for existing users with cards turned off. 
See: https://github.com/brave/brave-browser/issues/9616

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Brave 1.26.22 and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @karenkliu

**Comment by rebron** [comment]
@petemill This is fixed with https://github.com/brave/brave-core/pull/9074 right?

**Comment by petemill** [comment]
@rebron yes

**Comment by simonhong** [comment]
I also tested beta channel by updating from `1.25.64` to `1.26.60` and I can see widget area is still empty.

**Comment by rebron** [comment]
Closing. Fixed with brave/brave-core#9074

**Comment by stephendonner** [comment]
**Verified `PASSED`** using 

Brave | 1.26.63 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | macOS Version 11.4 (Build 20F71)

**Steps:**
1. installed `1.25.73`
2. launched Brave
3. opened a new tab page
4. clicked on `Edit Cards`
5. scrolled down in the resulting popup
6. toggled `Cards` to `Off`
7. installed `1.26.63` using the same profile from `1.25.73`
8. launched Brave
9. opened a new-tab page
10. confirmed there was no `Cards` stack on the right-hand side
11. clicked on `Customize`, then `Cards` and toggled the bottom `Cards` pref back to `On`
12. confirmed `FTX`, `Crypto.com`, `Binance`, `Gemini`, and `Brave Rewards` cards all returned, and were usable

`1.25.73`, cards `off` | `1.26.63`, cards `off` | `1.26.63`, cards `off` (pref state) | `1.26.63`, cards `on` again
--------|-----------|---------|---------
<img width="1312" alt="Screen Shot 2021-06-16 at 3 49 19 PM" src="https://user-images.githubusercontent.com/387249/122305941-7d856600-cebc-11eb-99b7-b6bd3fc4ee76.png"> | <img width="1312" alt="Screen Shot 2021-06-16 at 3 51 04 PM" src="https://user-images.githubusercontent.com/387249/122305950-81b18380-cebc-11eb-8a42-4a11577c082e.png"> | <img width="1312" alt="Screen Shot 2021-06-16 at 3 51 12 PM" src="https://user-images.githubusercontent.com/387249/122305957-837b4700-cebc-11eb-931e-fe6873cb97de.png"> | <img width="1312" alt="Screen Shot 2021-06-16 at 3 51 24 PM" src="https://user-images.githubusercontent.com/387249/122305958-8413dd80-cebc-11eb-9d8f-8e5c0c878287.png">
