### ISSUE TITLE
Brave News sources list in Customize panel shows 0 when not yet opted-in

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15977]
## Description 

Brave News sources list in Customize panel shows 0 when not yet opted-in

## Steps to Reproduce

   1. new profile, launch Brave
   2. click on `Skip welcome tour` or open a new-tab page
   3. scroll down
   4. click `No thanks` to the Brave News opt-in
   5. scroll back up
   6. click on `Customize`
   7. click on `Brave News` on the left
   8. now, click to toggle `Show Brave News` to `On`
   9. look at the panel

## Actual result:

A stray `0` shows up beneath the `Show Brave News` toggle

<img width="1312" alt="Screen Shot 2021-05-19 at 1 12 45 PM" src="https://user-images.githubusercontent.com/387249/118878705-b2de6a00-b8a4-11eb-8822-c539de3d8602.png">

![brave-news-zero](https://user-images.githubusercontent.com/387249/118879054-1bc5e200-b8a5-11eb-8b76-cb0070de9c32.gif)

## Expected result:

Should either disable the toggle control or show the list of sources anyway; I'm not sure

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.26.30 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

/cc @petemill @karenkliu

**Comment by karenkliu** [comment]
Haha thanks for catching this. 

Toggling Brave News on through Customize Dashboard should show the feed. It acts the same as if they clicked on "Show Brave News" in the welcome card.

**Comment by stephendonner** [comment]
@rebron can we get this slotted into 1.26.x?

**Comment by GeetaSarvadnya** [comment]
Reproduced in `Windows 10 x64 - 1.26.74`

**Comment by stephendonner** [comment]
**Verified `FIXED`** using the inline testplan with build 

Brave | 1.27.62 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)


**Steps:**

1. new profile, launch Brave
2. click on Skip welcome tour or open a new-tab page
3. scroll down
4. click No thanks to the Brave News opt-in
5. scroll back up
6. click on Customize
7. click on Brave News on the left
8. now, click to toggle Show Brave News to On
9. look at the panel

Confirmed the categories were present, and `Show Brave News` was toggled to `On`

steps 1-7 | step 8
---------|---------
<img width="1312" alt="Screen Shot 2021-06-14 at 1 54 23 PM" src="https://user-images.githubusercontent.com/387249/121958550-a53bc900-cd18-11eb-81b8-8cf8c06e271c.png"> | <img width="1312" alt="Screen Shot 2021-06-14 at 1 55 10 PM" src="https://user-images.githubusercontent.com/387249/121958552-a5d45f80-cd18-11eb-801a-5c5b8c7569a7.png">
