### ISSUE TITLE
Storybook: Add Skip Button to Recovery Onboarding Screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#15971]
## Description 
Add a Skip Button to the Recovery Onboarding Screen.

![Screen Shot 2021-05-19 at 11 50 44 AM](https://user-images.githubusercontent.com/40611140/118860320-7b69c080-b898-11eb-9b81-0e559ae88875.png)

You can find the specs for this component in Figma / Desktop Crypto Wallets.

Add the component too storybook with mock data for testing.

## Expected result:

Component should be visible and functional in Storybook under the Wallet/Desktop/Concepts and Wallet/Desktop/Components tabs.

**Comment by lukemulks** [comment]
Heya @Douglashdaniel someone flagged on Twitter that we have a misspelling of `understnd` (understand) in the copy. 

Just flagging here for ref.
