### ISSUE TITLE
Contextual reload icon on Brave Rewards panel should be removed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1598]
## Description 

Donate to this site monthly has a reload button next to it in rewards panel that is not functional. Should be removed similar to help icon removed in #1472

## Steps to Reproduce

   1. Enable rewards
   2. Add funds
   3. Visit a site and open rewards panel. Non functional reload icon is shown next to donate text

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46978676-913df600-d09d-11e8-85b0-77f229754941.png)

## Expected result:
Icon should be reomved

## Reproduces how often: 

All the time

## Brave version (chrome://version info)

 
Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@NejcZdovc to be honest its not very intuitive as to what the indicator is about. Using the reload button there, my initial thought was to refresh to see the donation. We should may be add a tool tip to explain what that is. 

On the rewards panel the text is self explanatory that the donation is to be done monthly so there is no need for the icon. If we do need an icon there and on the tips table in settings page may be we should use something like this rather than the reload button icon

![image](https://user-images.githubusercontent.com/17010094/47017650-d1928800-d120-11e8-9e15-81233705d8d4.png)

cc: @kjozwiak @LaurenWags @bradleyrichter

**Comment by NejcZdovc** [comment]
cc @jenn-rhim

**Comment by LaurenWags** [comment]
+1 to @srirambv comment - I also thought it was a reload button. It's almost identical to the browser reload icon: 
<img width="28" alt="screen shot 2018-10-16 at 9 09 03 am" src="https://user-images.githubusercontent.com/28145373/47018768-7c0baa80-d123-11e8-9346-ea28dbf01c12.png">

I don't think we need an icon, but if we do one that's more similar to the icon from https://github.com/brave/brave-browser/issues/1598#issuecomment-430225875 seems more appropriate to me.

**Comment by NejcZdovc** [comment]
sure we can do that

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7 x64

![image](https://user-images.githubusercontent.com/34715963/49838503-4691df00-fdab-11e8-938e-96aaf669544f.png)
