### ISSUE TITLE
First party java script blocked as 'cross domain tracking'

### ISSUE THREAD

**Issue by polynomial** [brave/brave-browser#15993]
## Description 

While using this website: https://refer.calo.app/ one of the critical pieces of functionality gets blocked:
core.js | (blocked:other)
It shows up in the shield: 
Cross-site trackers blocked
https://refer.calo.app/core.js

Which is confusing, as the javascript is being loaded from the same domain as the website in the URL bar. 

## Steps to Reproduce

   1. Install Brave
   2. Navigate to https://refer.calo.app/
   3. No widget shows to enable the user to get their reward.
   4. Turn off the ad blocker and load the page, you will then see the widget.

## Actual result:

No widget shows on the website above.

## Expected result:
It should show a pop-up widget that enables the user to get a reward.

## Reproduces how often: 

Always, if cross-site tracking is blocked, or the Ad blocking is set to normal or aggressive.

## Desktop Brave version:

Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 4XL
   - Android version: 11

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

I went through all of the adblock lists here:
https://brave.com/privacy-features/
Downloading them and looking and don't see any regexp's that would match the just /core.js, lots of other /ad/core.js etc. So I'm unsure why this is getting flagged.

**Comment by ryanbr** [comment]
Being a CNAME, its third-party. But now fixed.

**Comment by polynomial** [comment]
Is there some way to make this more universal? I assume it affects all of our customers, calo.app was just the customer that reported it to me. I see Brave users across hundreds of other domains, all of which are also CNAMEd, what should we do to resolve those? I feel like opening a ticket for each domain is hopefully not the right solution, but am hoping we can reach some decision about our other affected customers so users of Brave don't have a terrible experience using our clients websites.

**Comment by ryanbr** [comment]
Remove the CNAME
