### ISSUE TITLE
Support Brave Payment features about:rewards

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#16]
Add parity Brave features to what is in browser-laptop.  Determine what we need above and beyond #15.  We will likely move this to a new tab instead.

**Comment by bsclifton** [comment]
I think we'll likely want to move to `about:rewards` instead

`about:payments` page has been stubbed out with https://github.com/brave/brave-core/commit/a8409b6aa9242787c0741c2e93cfd678a1cc7cbc

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Able to load rewards page by navigating directly to chrome://rewards
* Able to load rewards page from hamburger menu
