### ISSUE TITLE
Refactor unblinded tokens

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#16005]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.35.99 Chromium: 98.0.4758.87 (Official Build) (64-bit) 
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Ubuntu 18.04 LTS

Verified in https://github.com/brave/internal/issues/846
