### ISSUE TITLE
Add setting to enable/disable search tabs button

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#16007]
## Description 

![image](https://user-images.githubusercontent.com/3299098/119031815-580a4880-b960-11eb-87f4-024ca4174bd3.png)

Chrome has removed this flag in Chromium v91.0.4472.77. Some of our users lean more towards "minimalists" and would prefer the option to hide/disable this option if possible.

## Designs
Add 'Hide search tabs button' under 'Hide Brave Rewards' toggle. Create new subsections for 'Bookmarks bar' 'Toolbar' and 'Typography'

![image](https://user-images.githubusercontent.com/2388823/123490729-a77c0e00-d5c9-11eb-9b4e-d07ad376353b.png)

## Assets
Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/?node-id=808%3A9463

**Comment by Tonev** [comment]
+1

It's frustrating we can't disable a feature we don't want to use.

**Comment by marcelduin** [comment]
+1

When introducing a button in such a prominent location, please also add the option to turn it off.

**Comment by Tonev** [comment]
The feature is being actively discussed on Reddit as well: https://www.reddit.com/r/brave_browser/comments/nmhdsf/what_the_fuck_is_this_thing_and_how_do_i_remove_it/

**Comment by mattspew** [comment]
+1

Don't need or want this button.

**Comment by Kil0grm** [comment]
> +1
> 
> When introducing a button in such a prominent location, please also add the option to remove it.

Better yet, don't introduce random buttons in any location. I mean holly shit, what year is this. Clean uis are an absolute must.

**Comment by manikandancode** [comment]
Add a option to remove the button completely

[OR/AND]

Add a option to show below components on that field
1) search field [OR/AND]
2) Open tabs [OR/AND]
3) Recently closed tabs

**Comment by SlyD1619** [comment]
+1
along with being able to remove it, please re-enable the feature to REMOVE Tab Hover Cards

**Comment by SlyD1619** [comment]
> In the past, the hover card on tab have released as enabled as default without a flag to toggle. This problem is happened again with the feature. Along with that, a promoted for search tab. 😂

its so f*ing annoying

**Comment by xbloodworkx** [comment]
Make it go away!

**Comment by sinankizar** [comment]
There is no need to use such feature. At least for me it is very very unnecessary. Please enable the setting so we may choose.

**Comment by Sy0xFF** [comment]
+1

**Comment by owlw** [comment]
+1

**Comment by richardwarriner** [comment]
+1
As a general rule, every time something is added to the UI make sure there is also a way to turn it off

I cant ever imagine a scenario where I would want to search across tabs

**Comment by Brave-Matt** [comment]
Several Community members requesting this here: 
https://community.brave.com/t/how-do-i-disable-the-search-tab/253756/4

**Comment by karenkliu** [comment]
Added the toggle to address this in https://github.com/brave/brave-browser/issues/13688.

**Comment by bstin** [comment]
> +1
> along with being able to remove it, please re-enable the feature to REMOVE Tab Hover Cards

Yes, I realize that chrome enabled these by default, but Brave devs please help unclutter the UI by removing these useless features. 
"Searching" your tabs and giving you "tab hover cards" are just useless clutter-UI. Nothing of value is gained.

**Comment by Tonev** [comment]
> > +1
> > along with being able to remove it, please re-enable the feature to REMOVE Tab Hover Cards
> 
> Yes, I realize that chrome enabled these by default, but Brave devs please help unclutter the UI by removing these useless features.
> "Searching" your tabs and giving you "tab hover cards" are just useless clutter-UI. Nothing of value is gained.

https://github.com/brave/brave-browser/issues/9906

**Comment by someguy9** [comment]
Still can't believe Chromium added this by default

**Comment by mac-repo-001** [comment]
Another usesless feature that clutters the interface. Please add option to disable it.

**Comment by kyleb1111** [comment]
This is F*in ridiculous. Why would you add this without an option to disable it? Nobody asks for this. Seriously guys, come on. 

+1 to everything said here.

**Comment by Lionel2001** [comment]
Any feature that is added (Search Tabs) should have an equivalent remove or disable option. This would be considered good design?

**Comment by EyeSalt** [comment]
Please remove it or have is disabled by default with an option to turn it on, NOT AUTOMATICALLY TURNED ON BY DEFAULT when updating Brave.

I might add it is a very irritating and virtually useless addon.

**Comment by wwwmonkey** [comment]
Ditto +1

**Comment by BobT36** [comment]
+1 Get rid of this, please.

Brave should NOT just be Chrome. Give us options to control this stuff.

**Comment by TheJakuPL** [comment]
+1

**Comment by charbelnicolas** [comment]
Also, if you choose the gtk theme on Linux the button shifts to the left and is no longer centered with the hamburger menu :( (already reported it to chromium btw).

**Comment by sinankizar** [comment]
I have removed chrome just because of they forced some settings like this. Now I am going to remove brave because of this attitude, It looks like they are just following google's footsteps with some privacy additives. Now I am looking for more customizable and more minimalist solution which is really don't exists IRL :(

**Comment by JimBreton** [comment]
> > +1
> > along with being able to remove it, please re-enable the feature to REMOVE Tab Hover Cards
> 
> Yes, I realize that chrome enabled these by default, but Brave devs please help unclutter the UI by removing these useless features.
> "Searching" your tabs and giving you "tab hover cards" are just useless clutter-UI. Nothing of value is gained.

Going to go out on a limb here; personally, I love the 'Search tabs' button, as it fulfills 75% of the usefulness of Firefox's Ctrl+Tab tab switching behavior and this was one of the things I really missed when switching over.  I think this feature is great.  And as a keyboard shortcut junkie AND a 'many open tabs' junkie this is very useful.

I realize this is a matter of opinion, and I don't disagree that it would be nice to be able to disable it, but personally I'd rather see limited Dev resources spent elsewhere vs. fighting upstream/mainstream Chromium UI changes.

**Comment by seanbebliss** [comment]
Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (64-bit) (p.s. - NEVER UPDATE AGAIN INVASIVE CIRCLE TRIANGLE ICON HATE SEEING IT MAKE IT GO AWAY! ROLL BACK TOO TECHNICAL (where easy install old version? NONE!!!!). YOU BREAKING MY MIND STUPED ALWAYS VISIBLE BUTTON!)

**Comment by EyeSalt** [comment]
It's been over a month and it looks like we are held captive at their whims.. if it’s not fixed soon I will have no option but to use an earlier portable version without this feature. I don’t want to have to do this, so please FIX this.

**Comment by y4rr** [comment]
Brave is becoming Chrome. I'm switching to Vivaldi lol.

**Comment by MadameSolette** [comment]
+1

Remove this button pls or give us an option to disable this crap.

**Comment by DevilEars** [comment]
+1
Pretty please. It was possible to remove this featuritis abomination with the flag:
`chrome://flags/#enable-tab-search`

That flag is no longer available, so now unfortunately Brave is less user-friendly due to a Chromium update.

**Comment by bsclifton** [comment]
I believe @nullhook is working on this now (guessing it'll go under brave://settings/appearance)

**Comment by bsclifton** [comment]
Adding missing milestone 😄

**Comment by stephendonner** [comment]
Verified `FIXED` using 
Brave | 1.29.45 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 12.0 (Build 21A5294g)

Steps:
1. new profile
2. launched Brave
3. opened `brave://settings/appearance`
4. saw `Show Search Tabs Button` is toggled to `on` by default, and the icon for the feature is on the top right of the tab strip
5. confirmed that toggling `Show Search Tabs Button` works in real-time and doesn't require browser restart

default | `off`
-------|------
<img width="1312" alt="Screen Shot 2021-08-02 at 5 22 13 PM" src="https://user-images.githubusercontent.com/387249/127939671-2cef0198-b68b-4d49-8e07-81812f69c948.png"> | <img width="1312" alt="Screen Shot 2021-08-02 at 5 26 55 PM" src="https://user-images.githubusercontent.com/387249/127939693-57562cd8-0fd4-442a-ac27-28700f0f7311.png">

**Comment by karenkliu** [comment]
This setting should be sentence case. 

cc @rmcfadden3

**Comment by stephendonner** [comment]
> This setting should be sentence case.
> 
> cc @rmcfadden3

oops, sorry, forgot to link https://github.com/brave/brave-browser/issues/17310 back here.
