### ISSUE TITLE
brave://about should list URL's as brave:// instead of chrome:// follow up to 1458

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1601]
## Description 

brave://about should list URL's as brave:// instead of chrome://

## Steps to Reproduce

   1. Launch profile on 0.55.14
   2. Open brave://about
   3. Page title says `List of Chrome URL's` and lists all URL's with `chrome://`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46986749-f5bd7d00-d0be-11e8-9f0f-b61aecc1e238.png)

## Expected result:
Page should say `List of Brave URL's` and all listed URL's should be `brave://*`

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bradleyrichter** [comment]
CC @rebron

**Comment by LaurenWags** [comment]
+1 from @gdregalo

**Comment by bsclifton** [comment]
We implemented this somewhere along the way 😄
