### ISSUE TITLE
Show "Added to sidebar" feedback bubble only three times

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#16018]
Currently, that feedback bubble is shown everytime new items are added.
Limit three times.

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with build 

Brave | 1.27.25 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

Steps:

1. Launched Brave with clean profile and enabled sidebar via `brave://flags`; relaunched
2. Loaded `brave.com`
3. Added current tab's site to sidebar
4. Repeated steps 2 and 3 (with `google.com`, `mozilla.com`, and `apple.com`) and checked that the sidebar-item-added feedback bubble is displayed only three times - as I added `apple.com` it didn't display.


brave://flags | brave.com | google.com | mozilla.com | apple.com
-------------|------------|-------------|-------------|-----------
<img width="1312" alt="Screen Shot 2021-05-27 at 4 52 32 PM" src="https://user-images.githubusercontent.com/387249/119910504-22d79a80-bf0c-11eb-8537-134c21a72a02.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 4 52 38 PM" src="https://user-images.githubusercontent.com/387249/119910507-23703100-bf0c-11eb-9d98-0a4aae695316.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 4 52 48 PM" src="https://user-images.githubusercontent.com/387249/119910509-2408c780-bf0c-11eb-92b8-886cbaad08b5.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 4 52 57 PM" src="https://user-images.githubusercontent.com/387249/119910510-2408c780-bf0c-11eb-9f6c-e1f98feed711.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 4 53 10 PM" src="https://user-images.githubusercontent.com/387249/119910511-2408c780-bf0c-11eb-9c6a-196a07f9732b.png">
