### ISSUE TITLE
Fix linking limit error notice only appears in the Rewards dropdown panel and not on brave://rewards page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16015]
## Description

If a user enters the verify wallet flow via the Rewards dropdown panel and exceeds the linking limit, they see the linking limit error message in the dropdown panel area.

<img src="https://user-images.githubusercontent.com/11497541/119071844-887dd100-b9b8-11eb-91e6-6b6d537fc898.png" width=200px>

However, when they go to brave://rewards settings page and enter the verify wallet flow through there, no limit error message is shown on that page.

<img src="https://user-images.githubusercontent.com/11497541/119071883-96335680-b9b8-11eb-9ae5-b3377bae1364.png" width=300px>

@A-t-s-u-s-h-i was able to reproduce in `1.24.85`.

## Solution

Show the linking limit error notice in the brave://rewards settings page area as well. 

**Update:** Use the big error modal popup as in all other verifying/linking error cases.

1. Text should be the same.
2. Learn more button is the orange button in bottom middle.
3. (x) button in top right corner to close.

**Comment by Miyayes** [comment]
**Update based on discussion:** Since it is non-trivial to make the error message look the same in brave://rewards settings page and we will be redesigning those elements in the near future anyway, just use the big error modal popup as in all other verifying/linking error cases. 

1. Text should be the same.
2. Learn more button is the orange button in bottom middle.
3. (x) button in top right corner to close.

**Comment by Miyayes** [comment]
@szilardszaloki I think this might be solved as part of your migration of notifications to error modals?

**Comment by szilardszaloki** [comment]
Yeah, definitely.
TBH, I don't think I've ever seen any of our notifications displayed on the `brave://rewards` settings page, only in the Rewards dropdown panel (regardless of where I entered the verify wallet flow).

**Comment by zenparsing** [comment]
Will be fixed by #16652
