### ISSUE TITLE
[hackerone] adblocking DNS issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#16011]
https://hackerone.com/reports/1203842

**Comment by diracdeltas** [comment]
cc @spylogsster to check whether https://github.com/brave/brave-core/pull/8068 has the same leak

**Comment by stephendonner** [comment]
I used a special test build from CI: `https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/proxy-disable-cname-uncloaking/b35173f457d8429bdeb9a44d956cc7d3f74c3752-0a1d47930bd4f300aab7638446bc44a100cdc478/windows/BraveBrowserStandaloneNightlySetup_91_1_27_39.exe`

Brave | 1.27.39 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2009 (Build 21390.1010)

Steps:

1. new profile
2. launched Brave
3. installed the NordVPN `2.29.1` extension (`https://chrome.google.com/webstore/detail/nordvpn-%E2%80%94-1-vpn-chrome-ex/fjoaledfpmneenckfbpdfhkmimnjocfa`)
4. signed in using internal Brave credentials
5. loaded `https://test-cname.brave.software/cname-uncloaking.html`
6. followed the instructions, and added `||dev-pages.brave.software/static/images/test.jpg` to `brave://adblock`
7. clicked `Run test`
8. confirmed that the output was `Request was allowed`
9. also confirmed by re-running the test that DNS-lookup traffic went to NordVPN

CNAME-test output | Wireshark
---------------------|-----------
![request-allowed](https://user-images.githubusercontent.com/387249/121602850-c0e35e80-c9fc-11eb-946b-ad3d81156505.png) | ![wireshark](https://user-images.githubusercontent.com/387249/121602869-c5a81280-c9fc-11eb-8ca7-36c776fd8b41.png)

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` until there is a 1.26.x build with this fix.

**Comment by stephendonner** [comment]
**Verified `PASSED`** using the inline testplan with build 

Brave | 1.26.63 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | macOS Version 11.4 (Build 20F71)


**Steps:**
1. new profile
2. launched Brave
3. installed the NordVPN 2.29.1 extension (`https://chrome.google.com/webstore/detail/nordvpn-%E2%80%94-1-vpn-chrome-ex/fjoaledfpmneenckfbpdfhkmimnjocfa`)
4. signed in using internal Brave credentials
5. loaded `https://test-cname.brave.software/cname-uncloaking.html`
6. followed the instructions, and added `||dev-pages.brave.software/static/images/test.jpg` to `brave://adblock`
7. clicked `Run test`
8. confirmed that the output was `Request was allowed`
9. also confirmed by re-running the test that DNS-lookup traffic went to NordVPN

example | example | example
---------|---------|----------
<img width="1078" alt="Screen Shot 2021-06-16 at 4 18 25 PM" src="https://user-images.githubusercontent.com/387249/122307245-d524d100-cebe-11eb-950f-c6a0017cafd9.png"> | <img width="1196" alt="Screen Shot 2021-06-16 at 4 19 18 PM" src="https://user-images.githubusercontent.com/387249/122307247-d5bd6780-cebe-11eb-9ffd-59f6989c84eb.png"> | <img width="1528" alt="Screen Shot 2021-06-16 at 4 19 24 PM" src="https://user-images.githubusercontent.com/387249/122307249-d5bd6780-cebe-11eb-8474-7629f0a33871.png">
