### ISSUE TITLE
Share local file/dir using IPFS does not work on desktop

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16020]
Second part of https://github.com/brave/brave-browser/issues/15935
Not all cases were handled in last PR

## Description + Steps to Reproduce
- Start node and try to import without IPNS keys

## Actual result:

Nothing happens, no error in console

## Expected result:

File/dir picker is opened

**Comment by stephendonner** [comment]
**Verified `PASSED`** using the testplan from https://github.com/brave/brave-browser/issues/14770#issuecomment-846145462; see there for detailed steps of the below tests.  Tested with build

Brave | 1.27.10 Chromium: 91.0.4472.70&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | fe095368270a32c92959403754bf6fd357dd9953-refs/branch-heads/4472@{#1172}
OS | macOS Version 11.3.1 (Build 20E241)

Also confirmed:
* no crashes
* no IPFS-shared files appeared in either the "shelf" on the browser toolbar, or the `Downloads` window; just their original, downloaded sources, as expected

CNN (directory) | CNN (file) | Vincent Van Goh (file) | The Maltese Falcon (file) | `Downloads` window
----------------|------------|-----------------------|---------------------------|----------------------
<img width="1493" alt="Screen Shot 2021-05-21 at 3 47 43 PM" src="https://user-images.githubusercontent.com/387249/119205022-e7d8f100-ba4b-11eb-96a8-bbc3d9b75499.png"> | <img width="1493" alt="Screen Shot 2021-05-21 at 3 53 48 PM" src="https://user-images.githubusercontent.com/387249/119205298-c3c9df80-ba4c-11eb-8257-1539d35023f0.png"> | <img width="1493" alt="Screen Shot 2021-05-21 at 3 37 04 PM" src="https://user-images.githubusercontent.com/387249/119205037-f0312c00-ba4b-11eb-88ab-e9e652f83c7a.png"> | <img width="1493" alt="Screen Shot 2021-05-21 at 3 34 26 PM" src="https://user-images.githubusercontent.com/387249/119205048-f8896700-ba4b-11eb-99ec-257f514dba47.png"> | <img width="1493" alt="Screen Shot 2021-05-21 at 3 52 00 PM" src="https://user-images.githubusercontent.com/387249/119205256-9f6e0300-ba4c-11eb-9bac-9430a08ebc73.png">




CNN page's directory share link: `https://dweb.link/ipfs/QmPThhLyadq1qfMp2ZDG3Qf8gCkCURuPgT9JuAGzUy3Hvq?filename=CNN+-+Breaking+News%2C+Latest+News+and+Videos_files`

Vincent Van Goh page share link: `https://bafybeiec4exjpqpkcoyh7eener6mhoeijhuj5es5qdz5dt7ei4y46knzty.ipfs.dweb.link/?filename=Vincent+van+Gogh+-+Wikipedia.html`

The Maltese Falcon file share link: `https://bafybeiepa2nep2hips6xlphsj6fg4uuxa2eicq4o3rkfke7njyo5veyc4a.ipfs.dweb.link/QmNbBjvpPRL7WwCorwCCawnjNCFDuWBBAr3rJWq1G3musS`

**Comment by kjozwiak** [comment]
Going to remove the `QA Pass-macOS` as the above was checked on Nightly so https://github.com/brave/brave-core/pull/8901 can be uplifted. Thanks for running through the above on a Friday night @StephenBass 👍

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-browser/issues/14770#issuecomment-846145462 with build 

Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

`CNN` dir | `CNN` file | `Maltese Falcon` video | `Vincent Van Gogh` page | `Downloads` window | `brave-imports` dir
---------|----------|---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2021-05-27 at 12 18 02 PM" src="https://user-images.githubusercontent.com/387249/119884584-a7fb8900-bee5-11eb-93dd-ae08107ed6a0.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 12 16 54 PM" src="https://user-images.githubusercontent.com/387249/119884618-b184f100-bee5-11eb-9bea-94e191499639.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 11 55 39 AM" src="https://user-images.githubusercontent.com/387249/119884215-3b808a00-bee5-11eb-907f-9330e1329c27.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 11 57 12 AM" src="https://user-images.githubusercontent.com/387249/119884220-3d4a4d80-bee5-11eb-8cb8-2a777a6ffb6b.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 12 01 02 PM" src="https://user-images.githubusercontent.com/387249/119884225-3e7b7a80-bee5-11eb-92bc-a813d163d922.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 12 16 40 PM" src="https://user-images.githubusercontent.com/387249/119884661-be094980-bee5-11eb-84dd-6bc97cfe1826.png">

Confirmed the following:
* all imports worked, without errors
* file content was intact
* no crashes while downloading/importing/loading
* no IPFS-shared files appeared in either the "shelf" on the browser toolbar, or the Downloads window; just their original, downloaded sources, as expected
