### ISSUE TITLE
Disable Brave ads custom ad notifications by default

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#16024]

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5`
3. opened four new-tab pages
4. clicked on `Start using Rewards` on the new-tab page
5. waited for a while
6. focused the URL bar
7. received an ad

Confirmed I got a native ad on macOS-Intel.

example | example
---------|---------
<img width="1680" alt="Screen Shot 2021-05-28 at 9 53 15 AM" src="https://user-images.githubusercontent.com/387249/120019224-0899cd00-bf9d-11eb-9242-00127484a71e.png"> | <img width="370" alt="Screen Shot 2021-05-28 at 9 53 27 AM" src="https://user-images.githubusercontent.com/387249/120019238-0cc5ea80-bf9d-11eb-9e5f-c91bb4d5c336.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy Tab version 10 running brave Beta build `Bravemonoarm64 1.26.56.apk`

- Confirmed by default native Ads are triggered on Android Tab
- Confirmed custom ads are triggered using the cmd line mentioned in the https://bravesoftware.slack.com/archives/GAA4017R7/p1623343892083200?thread_ts=1622822219.099100&cid=GAA4017R7

Nativ Ads | Custom Ads
-----------|---------------
![Screenshot_20210614-133415_Brave - Beta](https://user-images.githubusercontent.com/38657976/121860593-9fdd7f00-cd16-11eb-9777-7a33b510337c.jpg) | ![Screenshot_20210610-232233_Brave - Beta](https://user-images.githubusercontent.com/38657976/121860784-d4513b00-cd16-11eb-8c63-64666baebbc7.jpg)
