### ISSUE TITLE
NTP stats only update after refresh

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16023]
## Description 
NTP stats only update after refresh

## Steps to reproduce 

   1. Install RC build
   2. Visit a page wait till its loaded
   3. Quit the browser and restart
   4. Open a new tab upon relaunch
   5. Tab from step 2 loads in background but NTP stats doesn't update until refresh

## Actual result 
NTP stats only update after refresh

## Expected result
NTP stats should auto update as items are blocked even on background pages

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya

**Comment by anthonypkeane** [comment]
Fixed
