### ISSUE TITLE
[Android] Add Custom Tipping Amount feature (Phase 1)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16021]
#15006 was implemented on Desktop. Not yet implemented on Android so adding this tracking issue. 

cc: @deeppandya @Miyayes @zenparsing 

Issue description from #15006 

> Custom tipping amounts allows users to manually specify how much they would like to tip a Creator. The custom tipping amount option will be in addition to the default suggested tipping amounts.
> 
> Please refer to full feature specification.
>

**Comment by Saoiray** [comment]
Apologies, but does anyone have an ETA for this?

**Comment by Miyayes** [comment]
> Apologies, but does anyone have an ETA for this?

Yes, it will be done with https://github.com/brave/brave-browser/issues/17070, which is almost done.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.46.114`

- Verification notes can be found here https://github.com/brave/brave-browser/issues/17070#issuecomment-1318451208

---------

Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.46.114`

- Verification notes can be found here https://github.com/brave/brave-browser/issues/17070#issuecomment-1318451208
