### ISSUE TITLE
Update support URL links according to the following document

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1603]
https://docs.google.com/spreadsheets/d/16ubLUdPWmbzD4wiiiu0QbEGA6tbhJgqBemp_eVHz3FA/edit#gid=0

QA note:
Best effort if you can find some of the URLs described to make sure they go to the right place.
Don't spend too long but do verify some of them from the PR code.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified `address bar` link under Setting->Search pointed to the correct support link
* Verified `Learn more` for WebRTC pointed to the correct GitHub page link
