### ISSUE TITLE
Integrated Translation

### ISSUE THREAD

**Issue by Nicola-Sergio** [brave/brave-browser#16030]
### **Page Translation**
It is very annoying that you cannot automatically translate a foreign language page into your own language. I am of the opinion that besides a few other small problems, one of the reasons why Brave is not widespread is this. To extend the use of Brave it is necessary to introduce this functionality. Have you already thought about it or are there problems that do not allow the addition of this function?

I hope that this discomfort can be resolved as soon as possible

**Comment by Rizr09** [comment]
You can see the obstacles that Brave faces on #208

**Comment by Bundy01** [comment]
Rather than google, it would be more profitable to integrate Deepl if it is passible ;)

**Comment by Samk19** [comment]
+1 for open source language translation specially on ios and android app where we cannot install the extension 

Please do implement an opensourced language translation feature in your mobile apps

Thankyou

**Comment by Samk19** [comment]
+1 to integrate language translation feature in mobile app of brave ios and android as we cannot install translation extension on the mobile apps.

So its a must to have feature.

**Comment by bsclifton** [comment]
Previously tracked with https://github.com/brave/brave-browser/issues/208 - we closed that issue after running into licensing obstacles and choosing to integrate with the Google Translation extension as a work-around

**Comment by Samk19** [comment]
You can use Deepl or microsoft translate api if Google translate is creating problem to integrate with brave browser

https://www.deepl.com/translator


Please do implement this feature specially in Android and ios device where we cannot use extension to produce the desired result
