### ISSUE TITLE
Netflix doesn't work on M1 with 1.25.x/C91

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#16037]
## Description 

Netflix produces an error when attempting to stream on a fresh profile with 1.25.x/C91.

Does not reproduce with `1.24.86 Chromium: 90.0.4430.212`.

## Steps to Reproduce

   1. Clean profile, install `1.25.65 Chromium: 91.0.4472.57 (Official Build) (arm64)`
   2. Navigate to Netflix, login, allow Widevine
   3. Attempt to stream a show/movie

## Actual result:

<img width="1172" alt="Screen Shot 2021-05-21 at 4 04 20 PM" src="https://user-images.githubusercontent.com/28145373/119192802-ae55b500-ba4e-11eb-8926-f18cf6a4be54.png">

On brave://components, Widevine shows update error:
<img width="366" alt="Screen Shot 2021-05-21 at 3 54 16 PM" src="https://user-images.githubusercontent.com/28145373/119192824-b7df1d00-ba4e-11eb-8baf-e034ab4d0a4f.png">

## Expected result:
No error, able to stream

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave	1.25.65 Chromium: 91.0.4472.57 (Official Build) (arm64)
Revision	e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS	macOS Version 11.3.1 (Build 20E241)
```

```
Brave	1.27.8 Chromium: 91.0.4472.70 (Official Build) nightly (arm64)
Revision	fe095368270a32c92959403754bf6fd357dd9953-refs/branch-heads/4472@{#1172}
OS	macOS Version 11.3.1 (Build 20E241)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.24.x no, 1.25.x yes
- Can you reproduce this issue with the beta channel? 1.26.x yes
- Can you reproduce this issue with the nightly channel? 1.27.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? no, does not reproduce on Chrome using 
```
Google Chrome	91.0.4472.69 (Official Build) beta (arm64)
Revision	b6f10f407420cff532d7b29bd24077e8b35a2d10-refs/branch-heads/4472@{#1171}
OS	macOS Version 11.3.1 (Build 20E241)
```
## Miscellaneous Information:

cc @brave/legacy_qa @rebron @mkarolin

**Comment by rebron** [comment]
cc: @simonhong @bridiver

**Comment by LaurenWags** [comment]
Labeling as `QA/Blocked`, requires a new 1.25.x build

**Comment by LaurenWags** [comment]
Verification in progress

```
Brave	1.25.68 Chromium: 91.0.4472.77 (Official Build) (arm64)
Revision	1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS	macOS Version 11.3.1 (Build 20E241)
```

Confirmed able to install `Brave-Browser-universal.dmg` and `Brave-Browser-universal.pkg` for above versions
Confirmed able to install Widevine for a clean profile and stream Netflix
Confirmed no "Update error" for Widevine component on brave://components
Confirmed arm64 Widevine was downloaded

Example | Example
----- | -----
<img width="376" alt="Screen Shot 2021-05-26 at 7 10 58 AM" src="https://user-images.githubusercontent.com/28145373/119651484-10b60900-bdf3-11eb-8816-7f0b287625ea.png"> | <img width="771" alt="Screen Shot 2021-05-26 at 7 14 01 AM" src="https://user-images.githubusercontent.com/28145373/119651487-11e73600-bdf3-11eb-984f-70b3e72ad02d.png">

TBD: 
Upgrade checks

```
Brave	1.25.68 Chromium: 91.0.4472.77 (Official Build) (x86_64 translated)
Revision	1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS	macOS Version 11.3.1 (Build 20E241)
```

Confirmed able to install `Brave-Browser-x64.dmg` and `Brave-Browser-x64.pkg` for above versions
Confirmed able to install Widevine for a clean profile and stream Netflix
Confirmed no "Update error" for Widevine component on brave://components
Confirmed x64 Widevine was downloaded

Example | Example
----- | -----
<img width="380" alt="Screen Shot 2021-05-26 at 7 16 45 AM" src="https://user-images.githubusercontent.com/28145373/119651674-3f33e400-bdf3-11eb-9de4-b8b3c8a9bb5d.png"> | <img width="793" alt="Screen Shot 2021-05-26 at 7 17 34 AM" src="https://user-images.githubusercontent.com/28145373/119651680-40fda780-bdf3-11eb-9842-1d9a236427ff.png">

TBD:
Upgrade checks
