### ISSUE TITLE
Implement NTP Tutorial Page

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#16033]
Description:

Spec "NTP Tutorial Page"

Region: Japan only

URL: https://brave.com/ja/android-ntp-tutorial

When the users location is set to Japan, please auto load the above URL after onboarding.

**Comment by anthonypkeane** [comment]
cc @soi-tnk so you can keep track of progress

**Comment by anthonypkeane** [comment]
@soi-tnk please note this is scheduled for 1.28 currently

**Comment by srirambv** [comment]
@anthonypkeane there was an uplift for this but should that be removed and left it for 1.28.x?

**Comment by anthonypkeane** [comment]
1.27 is perfect too @srirambv TY

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using the following build:

```
1.27.107 Chromium: 92.0.4515.107
```

* ensured that `https://brave.com/ja/android-ntp-tutorial` is being opened in a NTP in the following scenarios:
  * ensured that the NTP correctly opens after `Privacy Stats` (which is basically the end of onboarding)
  * ensured that the NTP correctly opens if `Privacy Stats` is skipped
  * ensured that the NTP correctly opens when Brave is set as the default browser
* ensured that `https://brave.com/ja/android-ntp-tutorial` isn't being opened in a NTP for `Germany`, `Canada`, `Polish`
* ensured that `https://brave.com/ja/android-ntp-tutorial` matches the link mentioned via https://github.com/brave/brave-browser/issues/16033#issue-898277563
