### ISSUE TITLE
Browser crash in private window

### ISSUE THREAD

**Issue by ATrogolo** [brave/brave-browser#16041]
## Description 
When opening a new Private window and try to search something in the search bar the browser crash.

## Steps to Reproduce

   1. Open Brave with couple of tabs 
   2. Open a new Private Window
   3. Search something in the search bar
   4. The browser will crash

## Actual result:
![image](https://user-images.githubusercontent.com/6469648/119223596-9f2c4100-bafa-11eb-835e-c7c5909b2661.png)

## Expected result:
It shouldn't crash..

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave: 1.24.86 Chromium: 90.0.4430.212 (Build ufficiale) (a 64 bit)
Revision: e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Don't know
- Can you reproduce this issue with the nightly channel? Don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? Don't know

## Miscellaneous Information:

![image](https://user-images.githubusercontent.com/6469648/119223677-fe8a5100-bafa-11eb-9852-3fef5e559bbd.png)

**Comment by bsclifton** [comment]
@ATrogolo is your search engine set by extension? @simonhong recently pushed a fix for this which isn't on Release channel yet (it's on Beta). Fix was with https://github.com/brave/brave-core/pull/8626

**Comment by simonhong** [comment]
If this crash didn't come from search provider extension, this could be also related with https://github.com/brave/brave-browser/issues/16069.

**Comment by ATrogolo** [comment]
Hi @bsclifton , 
I'm using DuckDuckGo as search engine and the [DuckDuckGo Privacy Essentials](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg) extension. 
Disabling the extension the problem didn't happen.

**Comment by simonhong** [comment]
Thanks @ATrogolo for your info.
Crashes from extension was fixed and that fix is on beta now as @bsclifton mentioned above.
Will close this issue.

**Comment by ATrogolo** [comment]
Ok, thanks! 
@simonhong the issue will be fixed in the stable channel on 1.26 milestone (https://github.com/brave/brave-core/milestone/139)? 
Alternatively, where can I check the version which will include a Brave fix (in the stable channel)?

**Comment by simonhong** [comment]
@ATrogolo Yes, `1.26` will have this crash fix -
You can check the revision of the fix PR - https://github.com/brave/brave-core/pull/8626
From this page(https://github.com/brave/brave-core/pull/8626/commits/e4316b3f443e4f0af8d428733c509164ae1584c9), 
that fix is included from `1.26.22`
![image](https://user-images.githubusercontent.com/6786187/119632666-fd835780-be4b-11eb-8dfe-f52614b619a8.png)
