### ISSUE TITLE
Installing 1.27.12 from Brave-Browser-Nightly-universal.pkg crashes on launch with M1

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#16046]
## Description 

Installing `1.27.12` from `Brave-Browser-Nightly-universal.pkg` crashes on launch on M1.

Installing the other versions of `1.27.12` do not crash on launch w/ M1:
- `Brave-Browser-Nightly-universal.dmg`
- `Brave-Browser-Nightly-x64.dmg`
- `Brave-Browser-Nightly-x64.pkg`

Also, installing previous Nightly with universal builds available (`1.27.8`), does not crash on M1.

Unsure if this is related to changes made to fix https://github.com/brave/brave-browser/issues/16037.

## Steps to Reproduce

   1. Have M1 laptop
   2. Install 1.27.12 from `Brave-Browser-Nightly-universal.pkg` file https://github.com/brave/brave-browser/releases/tag/v1.27.12
   3. Attempt to launch --> crash on launch
   4. Try one of the other available macOS versions
   5. No crash on launch

## Actual result:

Crash on launch
<img width="999" alt="Screen Shot 2021-05-24 at 7 34 28 AM" src="https://user-images.githubusercontent.com/28145373/119346005-a15fde00-bc67-11eb-9d68-3aa78ebb0238.png">

## Expected result:
No crash

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.27.12 Brave-Browser-Nightly-universal.pkg file

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes, but only 1.27.12, not 1.27.8

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bridiver @simonhong @rebron @mihaiplesa @kjozwiak

**Comment by bridiver** [comment]
I don’t think this matters if it only happens on nightly. By the time this reaches stable we won’t have a universal binary anymore

**Comment by LaurenWags** [comment]
Reproducible with 
Nightly 1.27.12 Brave-Browser-universal.pkg
Nightly 1.27.13 Brave-Browser-universal.pkg
Dev 1.26.41 Brave-Browser-universal.pkg
Beta 1.26.40 Brave-Browser-universal.pkg

Does not reproduce with
Nightly 1.27.17 Brave-Browser-universal.pkg
Release Candidate 1.25.68 Brave-Browser-universal.pkg

This seems to be working after https://github.com/brave/brave-browser/issues/16054 was merged to Nightly and Release. Dev/Beta checks will be done once new builds are available.

**Comment by LaurenWags** [comment]
@bsclifton yep! Just wanted to check the following worked as expected before doing so:

Beta 1.26.43 Brave-Browser-Beta-universal.pkg
Dev 1.26.44 Brave-Browser-Dev-universal.pkg
