### ISSUE TITLE
[Follow up to #15021]Implement Social Sharing of Brave Stats

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16044]
## Description 
[Follow up to #15021]Implement Social Sharing of Brave Stats

## Steps to reproduce 

   1. Verify social sharing stats for different tiers

## Actual result 
No tooltip shown

## Expected result
Show tooltip as per sepc

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.25.65

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
@anthonypkeane please confirm if this is specific for JP or all regions?

**Comment by bsclifton** [comment]
@srirambv would be all regions

**Comment by bsclifton** [comment]
Follow up - I believe I was wrong about that; may only be `JP`. Confirming now...

**Comment by anthonypkeane** [comment]
Please search for "Brave Stats Social Sharing" in GDrive. Most of this feature is all regions, and part is JP only.

**Comment by kjozwiak** [comment]
If @alexsafe resolves this sooner, we can get this into the next `1.25.x` HF including re-adding Stats Share/Tooltips.

**Comment by srirambv** [comment]
Marking as QA/No as there is a follow up issue logged https://github.com/brave/brave-browser/issues/17126
