### ISSUE TITLE
Brave doesn't open

### ISSUE THREAD

**Issue by erhelito** [brave/brave-browser#16042]
## Description 

Hello !
When I start brave "normally", nothing happen. When I start it from the terminal, I have this error :
`[6756:6756:0523/153953.520140:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.`

## Steps to Reproduce

I don't know how to reproduce this issue?

## Actual result:

It just don't open.

## Expected result:
Well, I just expect my favorite browser to open ^^

## Reproduces how often: 

2/3 times approximately.

## Brave version (brave://version info)

I don't know, because I can't access brave... I'm in ubuntu, and all my software are updated (I installed brave with the website's instructions).

## Version/Channel Information:

- Can you reproduce this issue with the current ?
I'm with the current.
- Can you reproduce this issue with the beta channel? 
I didn't try.
- Can you reproduce this issue with the nightly channel? 
I didn't try.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
I can't access brave...
- Does the issue resolve itself when disabling Brave Rewards? 
I can't access brave...
- Is the issue reproducible on the latest version of Chrome? 
I didn't try

## Miscellaneous Information:

My computer is an msi gl 62 6qf, with and nvidia 960gtm. I'm on ubuntu lts.

**Comment by rebron** [comment]
@erhelito Can you try re-installing our latest Brave 1.29.81 Chromium 93.0.4577.82 
https://brave.com/linux/

**Comment by erhelito** [comment]
> @erhelito Can you try re-installing our latest Brave 1.29.81 Chromium 93.0.4577.82 
> https://brave.com/linux/

Oh, sorry, I totally forgot this thread! With de update I have no problem! Thanks!
