### ISSUE TITLE
Fix verifiable ad conversion idiosyncrasies 

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#16049]
Misc edge cases that can break the VAC feature.

1. mismatched conversion URLs
    1. the conversion URLs in the `catalog` & `resource file` must match.
        * ex. for conversion URL `https://brave.com/careers/`
            * `https://brave.com/careers/*` + `https://brave.com/careers*` will fail to fetch the conversion id
            * `https://brave.com/careers/*` in both or `https://brave.com/careers*` in both will do so successfully.

2. do not use single-quotes for HTML attributes in the regex.
    1. Brave browser re-interprets single-quotes in HTML as double-quotes in the DOM. <details> <summary> click to expand </summary>
<img width="1440" alt="single-quotes" src="https://user-images.githubusercontent.com/24831890/119043529-20fb5d80-b987-11eb-8f3f-04cd2a31fe0f.png"></details>
    2. using single-quotes in the regex for the VAC serializer will fail to capture the conversion id.

**Comment by tmancey** [comment]
@iambrianfung as discussed in DM #1 will be resolved by transitioning conversions from ads resources to the catalog. Lets raise a new issue and only resolve #2 for this ticket.

**Comment by tmancey** [comment]
With regards to #2 are we saying we should try replace ` with " before trying the match?

**Comment by tmancey** [comment]
@tackley discussed with @iambrianfung and we will raise issues to normalize regex, i.e. replace single quotes with double quotes in the resource generator for #2.

#1 will be resolved when transitioning conversions from component updater resources to the catalog.
