### ISSUE TITLE
[VISUAL BUG] Tab names bugging out with repetitive ones

### ISSUE THREAD

**Issue by Cube9999** [brave/brave-browser#16058]
## Description 
While browsing, I noticed a strange visual bug in the tab names that would make a little spacing in the tab name when the number 1 was repeated atleast twice (e.g 11 or 1111)

## Steps to Reproduce

Reproducing this bug is fairly simple, it works both in my machine and in a friend's machine
   1. Open an "about:blank" tab (this can also be a normal website)
   2. Change the title to something with a repeated 1 (e.g "11" or "111", "abc111" and "abc 111" work aswell)

## Actual result:

Image of the bug: (recorded by myself)
<img src="http://i.uploader.fun/WI2m.gif">
Videos of the bug: (recorded by a friend after I asked him, to see if this bug was also occurring in other machines)

https://user-images.githubusercontent.com/70229983/119431777-c7719680-bcd8-11eb-8a0c-a721e3150203.mp4
https://user-images.githubusercontent.com/70229983/119431795-d35d5880-bcd8-11eb-91c4-31c877ddb7da.mp4

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave = 1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit)
Revision = e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS = Windows 10 OS Version 2004 (Build 19041.985)

This build was not built from source

Brave = 1.24.86 Chromium: 90.0.4430.212 (Official Build) (64-bit)
OS = Windows 10 OS Version 20h2

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
Yes, this issue can be reproduced in all channels.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
It does not
- Does the issue resolve itself when disabling Brave Rewards? 
It does not
- Is the issue reproducible on the latest version of Chrome? 
This issue is not reproducible on the latest version of Chrome (90.0.4430.212)

**Comment by rebron** [comment]
Closing as stale, and it's also working as expected. The tab in focus gets highlighted with an increased font-weight. Going back and forth like that from focus to unfocused state will just highlight that change.
