### ISSUE TITLE
"Open with IPFS" target address doesn't update during HTTP navigations

### ISSUE THREAD

**Issue by autonome** [brave/brave-browser#16056]
## Description 

If you open an HTTP URL and see the "Open with IPFS" button, then nagivate to something else via link click, the "Open with IPFS" button opens a new tab with the original URL not the new one.

## Steps to Reproduce

   1. Enable IPFS
   1. Open https://filecoin.io
   1. Notice the "Open using IPFS" button in address bar
   1. Click on "Blog" in the top nav, wait for it to load
   1. Click the "Open using IPFS" button in address bar

## Actual result:

Filecoin homepage opens in new tab using IPFS

## Expected result:

Filecoin blog opens in new tab using IPFS

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.26.21 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(arm64)

## Version/Channel Information:

tested in Nightly only

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
**Verified `FIXED`** using the inline testplan with build 

Brave | 1.27.25 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

**Steps:**

1.  Enabled IPFS (loaded `ipns://brantly.eth` then clicked `Use a local node`)
2.  Opened `https://filecoin.io`
3.  Noticed the "Open using IPFS" button in address bar
4.  Clicked on "Blog" in the top nav, waited for it to load
5.  Clicked the "Open using IPFS" button in address bar

Confirmed it opened `ipfs://bafybeibshlsr2bombc6p7s66etfoho4w77nuqnbweiliyajfnbpw55wspe/blog/#posts`

![ipfs-redirect](https://user-images.githubusercontent.com/387249/119909801-9ed0e300-bf0a-11eb-9559-896ca1f74265.gif)
