### ISSUE TITLE
Dev builds of Brave crashes upon creation of a new profile

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#16050]
## Description 

On Chromium 91-based Brave (e.g. Brave 1.26.23 with Chromium: 91.0.4472.57) there's a crash on DCHECK-enabled builds when trying to create a profile: as soon as you click on main menu > Create new profile a crash like this will show up (both on Windows and Linux):
```
[438032:438032:0524/192112.571846:FATAL:extension_util.cc(66)] Check failed: IncognitoInfo::IsIncognitoAllowed(&extension). 
#0 0x7f54caaf7659 base::debug::CollectStackTrace()
#1 0x7f54ca9f63f3 base::debug::StackTrace::StackTrace()
#2 0x7f54caa16963 logging::LogMessage::~LogMessage()
#3 0x7f54caa1730e logging::LogMessage::~LogMessage()
#4 0x5633973b576d extensions::util::(anonymous namespace)::SetCorsOriginAccessListForExtensionHelper()
#5 0x5633973b556b extensions::util::SetCorsOriginAccessListForExtension()
#6 0x563398f2f6ea extensions::PermissionsUpdater::NetworkPermissionsUpdateHelper::UpdatePermissions()
#7 0x563398f318a9 extensions::PermissionsUpdater::SetUsesDefaultHostRestrictions()
#8 0x563398f31f1a extensions::PermissionsUpdater::InitializePermissions()
#9 0x563398ee4962 extensions::ExtensionService::CheckPermissionsIncrease()
#10 0x5633973ab1bb extensions::ExtensionRegistrar::AddExtension()
#11 0x563398ee414a extensions::ExtensionService::AddExtension()
#12 0x563397eabbe3 greaselion::GreaselionServiceImpl::Install()
#13 0x5633973ad720 base::internal::Invoker<>::RunOnce()
#14 0x7f54caa8a2bc base::TaskAnnotator::RunTask()
#15 0x7f54caaac577 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#16 0x7f54caaabd7d base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#17 0x7f54caa251ca base::MessagePumpGlib::Run()
#18 0x7f54caaad0fb base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#19 0x7f54caa5ff7a base::RunLoop::Run()
#20 0x7f54c82e6d0f content::BrowserMainLoop::RunMainMessageLoop()
#21 0x7f54c82e8e52 content::BrowserMainRunnerImpl::Run()
#22 0x7f54c82e44d7 content::BrowserMain()
#23 0x7f54c8d69f42 content::ContentMainRunnerImpl::RunBrowser()
#24 0x7f54c8d6999d content::ContentMainRunnerImpl::Run()
#25 0x7f54c8d675ba content::RunContentProcess()
#26 0x7f54c8d6769d content::ContentMain()
#27 0x563396ffe438 ChromeMain
#28 0x7f54b95fb0b3 __libc_start_main
#29 0x563396ffe27a _start
Task trace:
#0 0x563397eaba86 greaselion::GreaselionServiceImpl::PostConvert()
#1 0x563397ea9d4c greaselion::GreaselionServiceImpl::CreateAndInstallExtensions()
#2 0x563397ea9d4c greaselion::GreaselionServiceImpl::CreateAndInstallExtensions()
#3 0x7f54c3860d7a JsonPrefStore::ReadPrefsAsync()
#4 0x7f54c3860d7a JsonPrefStore::ReadPrefsAsync()
```

The good news is that this crash is **not reproducible** on release builds (neither on stable, nor on beta or nightly), and also **not reproducible on dev builds compiled off the `cr92` branch**, so perhaps not a priority after all (yet reporting it for the sake of tracking it).

## Steps to Reproduce
   1. On a fresh (i.e. first run, no profile data created yet) dev build of Chromium 91-based Brave (e.g. Component), launch brave
   2. Expand the main menu, then click on "Create new profile"

## Actual result:

The browser crashes with a stack trace like the one above

## Expected result:

The browser should not crash

## Reproduces how often: 

  * For Chromium 91-based builds of Brave: Always on DCHECK-enabled builds, never otherwise
  * For Chromium 92-based builds of Brave: Never, not even on dev builds

## Brave version (brave://version info)

Brave 1.26.23 with Chromium: 91.0.4472.57 (dev builds only)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
@mariospr Is this issue still relevant?

**Comment by mariospr** [comment]
@rebron Just tested the steps in the `master` branch (1.31.46 Chromium: 94.0.4606.41 (Developer Build) (64-bit)) on a DCHECK-enabled build and I'm **happy to report this crash does no longer reproduce**.

Feel free to close this issue.

**Comment by rebron** [comment]
Thanks @mariospr Closing per last comment.
