### ISSUE TITLE
Support Qwant in new Private Tab pages

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1607]
Current new tab pages for Private Browsing only show DuckDuckGo graphics. We should also support the case (as with the Qwant) where the default search engine can be used with Tor and in private windows. This covers a gap left by brave/brave-core#646's partial implementation of #1507.

**Comment by riastradh-brave** [comment]
We intend to choose between DDG and Qwant by the user's choice of locale/language setting, but apparently that information is not available in the new tab UI implementation.  We need to add some mechanism to get at it.

**Comment by riastradh-brave** [comment]
@simonhong Can you elaborate on what is missing here and what work needs to be done to make it work?

**Comment by petemill** [comment]
Issue to implement better detection for qwant cc @simonhong @bsclifton https://github.com/brave/brave-browser/issues/1632

**Comment by bsclifton** [comment]
Marking as `QA/No` in favor of testing https://github.com/brave/brave-browser/issues/1632 instead
