### ISSUE TITLE
detect architecture and set proper update channel for Intel and arm64 users

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#16076]
## Description 
Universal builds for macOS users will be going away. Before we stop offering universal builds, users who previously downloaded a universal build need to be sent to the proper update channel for Intel or arm64. 

In Sparkle, we'll need to detect OS architecture and set the proper update channel to get users the correct updates per their architecture. We now set that at build time and form the whole updater endpoint.

## Steps to Reproduce

   1. Install universal build on Intel mac
   2. Upload new arm64 version in Sparkle
   3. Update is performed but app is unusable now

## Actual result:

App is grayed out.

## Expected result:
Update channel should be detected at run time by architecture of the system and updated apps should keep working.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
@mihaiplesa  What we want is updating feed url from `stable-arm64` to `stable` in the runtime for users who use univeral on Intel macO?

**Comment by mihaiplesa** [comment]
Corect. I was thinking we can take out the feed URL from Info.plist and moving that to the client + detecting the arch at run time.

**Comment by simonhong** [comment]
@mihaiplesa It seems sparkle provide interface for overriding feed url easily. - `SUUpdaterDelegate:: feedURLStringForUpdater`
If we supply another url via this delegate, maybe sparkle will use that url instead of url in Info.plist. (not tested yet)
https://github.com/brave/Sparkle/blob/main/Sparkle/SUUpdaterDelegate.h#L79

**Comment by simonhong** [comment]
Yes from the browser. We already use that Delegate - https://github.com/brave/brave-core/blob/master/browser/mac/sparkle_glue.mm#L363

**Comment by simonhong** [comment]
@mihaiplesa Pushed https://github.com/brave/brave-core/pull/8989 for fixing this issue.
With this PR, feed url is generated in runtime by checking channel and cpu.
With local build, I confirmed that update check was done.
