### ISSUE TITLE
Add support for additional currencies, Gemini widget

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#16081]
## Description 

Add support for additional currencies in the Gemini widget. 
Full list of currencies to support:

Bitcoin (BTC), Ether (ETH), Litecoin (LTC), Bitcoin Cash (BCH), Zcash (ZEC), Filecoin (FIL)

ERC20's - 0x (ZRX), 1INCH (1INCH), Aave (AAVE), Amp (AMP), Bancor Network (BNT), Basic Attention (BAT), Balancer (BAL), Chainlink (LINK), Compound (COMP), Curve (CRV), Dai (DAI), Decentraland (MANA), Enjin (ENJ), The Graph (GRT), Kyber Network (KNC), Loopring (LRC), Maker (MKR), Orchid (OXT), Pax Gold (PAXG), Ren (REN), The Sandbox (SAND), Skale (SKL), Storj (STORJ), Synthetix (SNX), Uma (UMA), Uniswap (UNI), Yearn Finance (YFI)

## Steps to Reproduce

   1. Go to the New Tab page
   2. OAuth/Connect to a Gemini account via the widget
   3. View and trade currencies from the supported list above.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by simonhong** [comment]
I think we can use shared currency icon images with gemini widget also.

**Comment by simonhong** [comment]
Working on this.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.28.96 Chromium: 92.0.4515.115 (Official Build) beta (x86_64)
-- | --
Revision | `48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}`
OS | macOS Version 10.15.7 (Build 19H114)

- Verified additional currencies are listed as per issue description
- Verified additional currencies are listed in trading tab as well as deposit tab
- Verified QR code is generated for the new currencies in the list
- Verified able to copy the currencies address to clipboard using the copy button 
![image](https://user-images.githubusercontent.com/17010094/127965894-aa3587ab-6ea1-48c0-88b4-d5431d0c1b12.png)

<details>
<summary>List of available assets </summary>

```html
<p class="Text-sc-ek390b jaKZrb">Bitcoin</p>

<p class="Text-sc-ek390b jaKZrb">Ethereum</p>

<p class="Text-sc-ek390b jaKZrb">Litecoin</p>

<p class="Text-sc-ek390b jaKZrb">Bitcoin Cash</p>

<p class="Text-sc-ek390b jaKZrb">Zcash</p>

<p class="Text-sc-ek390b jaKZrb">Filecoin</p>

<p class="Text-sc-ek390b jaKZrb">0x</p>

<p class="Text-sc-ek390b jaKZrb">1INCH</p>

<p class="Text-sc-ek390b jaKZrb">Aave</p>

<p class="Text-sc-ek390b jaKZrb">Amp</p>

<p class="Text-sc-ek390b jaKZrb">Bancor Network</p>

<p class="Text-sc-ek390b jaKZrb">Basic Attention</p>

<p class="Text-sc-ek390b jaKZrb">Balancer</p>

<p class="Text-sc-ek390b jaKZrb">Chainlink</p>

<p class="Text-sc-ek390b jaKZrb">Compound</p>

<p class="Text-sc-ek390b jaKZrb">Curve</p>

<p class="Text-sc-ek390b jaKZrb">Dai</p>

<p class="Text-sc-ek390b jaKZrb">Decentraland</p>

<p class="Text-sc-ek390b jaKZrb">Enjin</p>

<p class="Text-sc-ek390b jaKZrb">The Graph</p>

<p class="Text-sc-ek390b jaKZrb">Kyber Network</p>

<p class="Text-sc-ek390b jaKZrb">Loopring</p>

<p class="Text-sc-ek390b jaKZrb">Maker</p>

<p class="Text-sc-ek390b jaKZrb">Orchid</p>

<p class="Text-sc-ek390b jaKZrb">Pax Gold</p>

<p class="Text-sc-ek390b jaKZrb">Ren</p>

<p class="Text-sc-ek390b jaKZrb">The Sandbox</p>

<p class="Text-sc-ek390b jaKZrb">Skale</p>

<p class="Text-sc-ek390b jaKZrb">Storj</p>

<p class="Text-sc-ek390b jaKZrb">Synthetix</p>

<p class="Text-sc-ek390b jaKZrb">Uma</p>

<p class="Text-sc-ek390b jaKZrb">Uniswap</p>

<p class="Text-sc-ek390b jaKZrb">Yearn Finance</p>

```
</details>

------------

Verification passed on 

Brave | 1.28.96 Chromium: 92.0.4515.115 (Official Build) beta (64-bit)
-- | --
Revision | `48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}`
OS | Windows 10 OS Version 2009 (Build 19043.1110)

- Verified additional currencies are listed as per issue description
- Verified additional currencies are listed in trading tab as well as deposit tab
- Verified QR code is generated for the new currencies in the list
- Verified able to copy the currencies address to clipboard using the copy button 
![image](https://user-images.githubusercontent.com/17010094/127967243-34b2bd66-16aa-480e-9e41-3afb2f9be829.png)


<details>
<summary>List of available assets </summary>

```html
<p class="Text-sc-ek390b jaKZrb">Bitcoin</p>

<p class="Text-sc-ek390b jaKZrb">Ethereum</p>

<p class="Text-sc-ek390b jaKZrb">Litecoin</p>

<p class="Text-sc-ek390b jaKZrb">Bitcoin Cash</p>

<p class="Text-sc-ek390b jaKZrb">Zcash</p>

<p class="Text-sc-ek390b jaKZrb">Filecoin</p>

<p class="Text-sc-ek390b jaKZrb">0x</p>

<p class="Text-sc-ek390b jaKZrb">1INCH</p>

<p class="Text-sc-ek390b jaKZrb">Aave</p>

<p class="Text-sc-ek390b jaKZrb">Amp</p>

<p class="Text-sc-ek390b jaKZrb">Bancor Network</p>

<p class="Text-sc-ek390b jaKZrb">Basic Attention</p>

<p class="Text-sc-ek390b jaKZrb">Balancer</p>

<p class="Text-sc-ek390b jaKZrb">Chainlink</p>

<p class="Text-sc-ek390b jaKZrb">Compound</p>

<p class="Text-sc-ek390b jaKZrb">Curve</p>

<p class="Text-sc-ek390b jaKZrb">Dai</p>

<p class="Text-sc-ek390b jaKZrb">Decentraland</p>

<p class="Text-sc-ek390b jaKZrb">Enjin</p>

<p class="Text-sc-ek390b jaKZrb">The Graph</p>

<p class="Text-sc-ek390b jaKZrb">Kyber Network</p>

<p class="Text-sc-ek390b jaKZrb">Loopring</p>

<p class="Text-sc-ek390b jaKZrb">Maker</p>

<p class="Text-sc-ek390b jaKZrb">Orchid</p>

<p class="Text-sc-ek390b jaKZrb">Pax Gold</p>

<p class="Text-sc-ek390b jaKZrb">Ren</p>

<p class="Text-sc-ek390b jaKZrb">The Sandbox</p>

<p class="Text-sc-ek390b jaKZrb">Skale</p>

<p class="Text-sc-ek390b jaKZrb">Storj</p>

<p class="Text-sc-ek390b jaKZrb">Synthetix</p>

<p class="Text-sc-ek390b jaKZrb">Uma</p>

<p class="Text-sc-ek390b jaKZrb">Uniswap</p>

<p class="Text-sc-ek390b jaKZrb">Yearn Finance</p>

```
</details>

-------------

Verification passed on 

Brave | 1.28.96 Chromium: 92.0.4515.115 (Official Build) beta (64-bit)
-- | --
Revision | `48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}`
OS | Linux

- Verified additional currencies are listed as per issue description
- Verified additional currencies are listed in trading tab as well as deposit tab
- Verified QR code is generated for the new currencies in the list
- Verified able to copy the currencies address to clipboard using the copy button 
![image](https://user-images.githubusercontent.com/17010094/127966937-16b3dbe3-cfc1-4a44-8ebb-eb5d646eccec.png)


<details>
<summary>List of available assets </summary>

```html
<p class="Text-sc-ek390b jaKZrb">Bitcoin</p>

<p class="Text-sc-ek390b jaKZrb">Ethereum</p>

<p class="Text-sc-ek390b jaKZrb">Litecoin</p>

<p class="Text-sc-ek390b jaKZrb">Bitcoin Cash</p>

<p class="Text-sc-ek390b jaKZrb">Zcash</p>

<p class="Text-sc-ek390b jaKZrb">Filecoin</p>

<p class="Text-sc-ek390b jaKZrb">0x</p>

<p class="Text-sc-ek390b jaKZrb">1INCH</p>

<p class="Text-sc-ek390b jaKZrb">Aave</p>

<p class="Text-sc-ek390b jaKZrb">Amp</p>

<p class="Text-sc-ek390b jaKZrb">Bancor Network</p>

<p class="Text-sc-ek390b jaKZrb">Basic Attention</p>

<p class="Text-sc-ek390b jaKZrb">Balancer</p>

<p class="Text-sc-ek390b jaKZrb">Chainlink</p>

<p class="Text-sc-ek390b jaKZrb">Compound</p>

<p class="Text-sc-ek390b jaKZrb">Curve</p>

<p class="Text-sc-ek390b jaKZrb">Dai</p>

<p class="Text-sc-ek390b jaKZrb">Decentraland</p>

<p class="Text-sc-ek390b jaKZrb">Enjin</p>

<p class="Text-sc-ek390b jaKZrb">The Graph</p>

<p class="Text-sc-ek390b jaKZrb">Kyber Network</p>

<p class="Text-sc-ek390b jaKZrb">Loopring</p>

<p class="Text-sc-ek390b jaKZrb">Maker</p>

<p class="Text-sc-ek390b jaKZrb">Orchid</p>

<p class="Text-sc-ek390b jaKZrb">Pax Gold</p>

<p class="Text-sc-ek390b jaKZrb">Ren</p>

<p class="Text-sc-ek390b jaKZrb">The Sandbox</p>

<p class="Text-sc-ek390b jaKZrb">Skale</p>

<p class="Text-sc-ek390b jaKZrb">Storj</p>

<p class="Text-sc-ek390b jaKZrb">Synthetix</p>

<p class="Text-sc-ek390b jaKZrb">Uma</p>

<p class="Text-sc-ek390b jaKZrb">Uniswap</p>

<p class="Text-sc-ek390b jaKZrb">Yearn Finance</p>

```
</details>
