### ISSUE TITLE
Browser crash when opening a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16084]
## Description 
Browser crash when opening a new tab

## Steps to reproduce 

   1. Install 1.25.68 on JP locale
   2. Try to reach 1k blocked items
   3. Open a new tab browser crash

## Actual result 
https://bravesoftware.slack.com/archives/C0816QH3R/p1622006559147800

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Not checked
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.25.68

## Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/android @bsclifton @kjozwiak @anthonypkeane

**Comment by kjozwiak** [comment]
If @alexsafe resolves this sooner, we can get this into the next `1.25.x` HF including re-adding Stats Share/Tooltips.

**Comment by kjozwiak** [comment]
Closing as this was merged into `1.26.x` as per https://github.com/brave/brave-core/pull/9189.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.65 x64 build
- Verified steps from issue description
- Verified no browser crash when opening a new tab when blocked items go beyond 1K
-----------
Verification passed on Samsung Tab A with Android 10 running 1.26.65 x64 build
- Verified steps from issue description
- Verified no browser crash when opening a new tab when blocked items go beyond 1K
