### ISSUE TITLE
Complete online documentation for private windows

### ISSUE THREAD

**Issue by tildelowengrimm** [brave/brave-browser#1608]
brave/brave-core#646 moves a bunch of the explanatory learn-more text from the tabs themselves into online documentation. That documentation should be complete and reviewed, especially given that this is a security/privacy-focused feature.

https://support.brave.com/hc/en-us/articles/360018121491
https://support.brave.com/hc/en-us/articles/360018266171
https://support.brave.com/hc/en-us/articles/360017840332

**Comment by co16353sidak** [comment]
Hey @tomlowenthal would like to work on this as my first contribution here. Please give me the go ahead and some tips on how to proceed.

**Comment by bsclifton** [comment]
@co16353sidak it would be awesome if you had time to help 😄 Sorry for the long turn-around here on a response. If you wanted to open a Google Doc or had another platform to share your proposed text, we can definitely give you feedback 😄 

cc: @Brave-Matt and @rebron who might be able to help too

**Comment by co16353sidak** [comment]
> https://support.brave.com/hc/en-us/articles/360018121491
> https://support.brave.com/hc/en-us/articles/360018266171
> https://support.brave.com/hc/en-us/articles/360017840332

How about I submit a PR editing the content in the links given above with more details.

**Comment by bsclifton** [comment]
@co16353sidak sure! that would be great
