### ISSUE TITLE
Do not launch node if it is not used 

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16085]
## Description 

Broken here https://github.com/brave/brave-core/pull/8892

Node started automatically even if the ipfs method is set as Ask

## Steps to Reproduce

Just start the browser 

## Expected result:

node doesnt start if it is not used

## Reproduces how often: 

easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED`

Steps:

1. clean profile
2. started Brave and confirmed the IPFS node is not launched automatically
3. shut down
4. relaunched Brave, this time using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5 --use-dev-goupdater-url`
4. confirmed that it got an update to `0.9.0-rc1` from the development server

example | example | example 
---------|----------|---------
<img width="1312" alt="Screen Shot 2021-05-27 at 5 21 31 PM" src="https://user-images.githubusercontent.com/387249/119912579-94b1e300-bf10-11eb-84e2-4ea9d76604ea.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 5 22 50 PM" src="https://user-images.githubusercontent.com/387249/119912580-954a7980-bf10-11eb-81e0-47e55711197d.png"> | <img width="1312" alt="Screen Shot 2021-05-27 at 5 26 12 PM" src="https://user-images.githubusercontent.com/387249/119912608-aa270d00-bf10-11eb-94e4-e363c562f5ca.png">



Console:
```
generating ED25519 keypair...done
peer identity: 12D3KooWGqKHNn8SjbquyonRefSUGDNj67F1ZkJ7AGCRLkQXmXVp
initializing IPFS node at /Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/brave_ipfs
to get started, enter:

	ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme

Error: daemon not running
Initializing daemon...
go-ipfs version: 0.9.0-rc1
Repo version: 11
System version: amd64/darwin
Golang version: go1.16.4
Swarm listening on /ip4/10.0.0.5/tcp/44002
Swarm listening on /ip4/127.0.0.1/tcp/44002
Swarm listening on /ip6/::1/tcp/44002
Swarm listening on /p2p-circuit
Swarm announcing /ip4/10.0.0.5/tcp/44002
Swarm announcing /ip4/127.0.0.1/tcp/44002
Swarm announcing /ip6/::1/tcp/44002
API server listening on /ip4/127.0.0.1/tcp/45002
WebUI: http://127.0.0.1:45002/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/48081
Daemon is ready
```
