### ISSUE TITLE
Brave Browser Blocking Legitimate Site moonbeam.network

### ISSUE THREAD

**Issue by purestakatie** [brave/brave-browser#16086]
## Description 
Brave browser is issuing a phishing detection warning for a Polkadot parachain site, https://moonbeam.network/. The site is legitimate and contains no solicitations of user information, nor does it make requests to any wallet provider. It's a static website.
Note: there is a subdomain for the documentation site that is hosted in mkdocs (https://docs.moonbeam.network/) that contains a "connect to MetaMask" button, but this is not malicious and simply allows users to connect their MetaMask to our TestNet: https://docs.moonbeam.network/getting-started/testnet/metamask/

## Steps to Reproduce

   1. Navigate to https://moonbeam.network/
   2. Receive warning from Brave

We received reports of this behavior as early as last week but were not able to reproduce until now. It seems to be related to the IP address of the user, since I am now traveling and accessed the website from a different location. Only experienced it on the browser so far. 

## Actual result:
![image](https://user-images.githubusercontent.com/54632920/119664608-81fcb880-be01-11eb-94c5-e36f9fdcb730.png)

## Expected result:
![image](https://user-images.githubusercontent.com/54632920/119664668-92ad2e80-be01-11eb-9d55-ad43e8d21cb9.png)

## Reproduces how often: 
Intermittent issue: does not happen for every user every time.

## Brave version (brave://version info)
Brave | 1.24.86 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Windows&nbsp;10 OS Version 2009 (Build 19042.985)

## Version/Channel Information:
N/A

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  I don't know what this is
- Can you reproduce this issue with the nightly channel? I don't know what this is

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Now that I have clicked "proceed anyway," it will not give me the screen again
- Does the issue resolve itself when disabling Brave Rewards? Now that I have clicked "proceed anyway," it will not give me the screen again
- Is the issue reproducible on the latest version of Chrome? No, only Brave

## Miscellaneous Information:
Your link on the warning asks people to "file an issue" but does not have a hyperlink or say where. There should be a better place for projects to prove their authenticity so they are not erroneously blocked.

**Comment by andreasflys** [comment]
I'm on Brave as we speak, I tried out the website and didn't find an issue.

**Comment by purestakatie** [comment]
I am not sure what triggers the behavior but I received it a second time when accessing a different subdomain. I'll note that I am traveling and accessing the website from a different IP than usual... I have accessed it many times previously without issue. I am not clear what is triggering the error but we did also submit requests to all the crypto DBs to whitelist the domain.
![image (7)](https://user-images.githubusercontent.com/54632920/119857917-f6a72400-bee1-11eb-9791-17ead3a2802d.png)

**Comment by No5251** [comment]
Maybe the same _problem_ as with reddit before?
https://community.brave.com/t/reddit-is-blocked-by-crypto-wallet/242391

**Comment by purestakatie** [comment]
Yes, same problem, but we are not listed in the CryptoScamsDB. I have also contacted them to see if they can do something anyway. Is that the only DB the Brave Wallet uses to make these kinds of blocks on domains? It makes it really difficult for those who are legit projects to get it removed bc their team is not responsive.

**Comment by bbondy** [comment]
cc @jonathansampson if you can help with thi

**Comment by jonathansampson** [comment]
@bbondy Looking into this now.

**Comment by jonathansampson** [comment]
@purestakatie Thank you for reporting. I've removed the domain from the blacklist; it should be updated for our users shortly. Our apologies for the inconvenience, and please do reach out if you ever encounter any other issues.

**Comment by purestakatie** [comment]
AMAZING thank you guys for being so quick about this!
