### ISSUE TITLE
Tor new tab page has a lot of redundant information

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16094]
The Tor new tab page contains a lot of blocks and some of them are pretty much the same:
![Screenshot from 2021-05-25 16-09-21](https://user-images.githubusercontent.com/167821/119734423-d585fb00-be2f-11eb-98b1-69e11c4a4bc1.png)
![Screenshot from 2021-05-25 16-09-30](https://user-images.githubusercontent.com/167821/119734432-d880eb80-be2f-11eb-923f-ff69bddd27b8.png)

In addition, the daemon status block is at the very bottom while it's actually the most useful tool for detecting problems connecting to the Tor network.

Also requested on https://community.brave.com/t/move-tor-status-window-to-the-top-of-the-screen/252677.

# New design

Here's a new simplified design that @karenkliu created:
![image](https://user-images.githubusercontent.com/2388823/123855442-c681e500-d8d4-11eb-898f-e18e365506ee.png)

![connection](https://user-images.githubusercontent.com/2388823/123855480-ce418980-d8d4-11eb-8514-26e0fbd9dd0f.gif)

## Assets
Figma: https://www.figma.com/file/5THkuEtO2Ewn9LfqrHZP9a/?node-id=544%3A401

**Comment by rebron** [comment]
Closing as duplicate and fixed in https://github.com/brave/brave-browser/issues/20583
