### ISSUE TITLE
Allow private (& private+Tor) search engines to be changed

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1609]
Currently, private windows have an immutable search engine. That's silly.

**Comment by simonhong** [comment]
Search engine provider work like below
* Private window (non-tor)
  * DDG is used when it's option is on in private newtab
  * Normal windows's provider is used when ddg option is off
* Private tor window
  * Initially it is to DDG
  * User can change search engine and it is persisted (Merged but not yet released)
  * Qwant is initially set when region is german or France (https://github.com/brave/brave-core/pull/647)

**Comment by simonhong** [comment]
@riastradh-brave I think this issue can be closed?

**Comment by rebron** [comment]
Fixed in RC builds. Reopen if it's not.
