### ISSUE TITLE
Checking if switch disables auto updates

### ISSUE THREAD

**Issue by rany2** [brave/brave-browser#16105]
Does https://github.com/brave/brave-core/blob/master/common/brave_switches.cc#L20-L21 actually disable auto updates? or does it do something else?

Checking is this switch would  help in closing https://github.com/flathub/com.brave.Browser/issues/15

**Comment by rany2** [comment]
Oh just found https://github.com/brave/Sparkle. Hopefully it isn't just a MacOS only thing

**Comment by bsclifton** [comment]
@rany2 Sparkle is a macOS only technology (Windows uses Omaha; Linux uses whatever installed (snap/apt/dfn/etc)). You can give the command line option a try- the official issue tracking this request can be found in https://github.com/brave/brave-browser/issues/5576
