### ISSUE TITLE
Brave please remove tracking URLS: Open Sourced

### ISSUE THREAD

**Issue by underling3311** [brave/brave-browser#16118]
## Description 

This should apart of brave because it removes tracking links! It is an open source link remover. In the past, the brave team has taken on Jitsi to make their own brave together video calling system that is open sourced. I think you can do the same with this and make it work on all devices. 

For Example: 
I am looking for a 8TB hard drive on amazon. I type "hard drive 8tb" then click one. Down below are the links, Big difference on the link size!

No ClearUrls:
https://www.amazon.com/SEAGATE-ST8000DM0004-BarraCuda-256MB-Cache/dp/B08C2ZYDV5/ref=sr_1_11?dchild=1&keywords=hard+drive+8tb&qid=1622162500&sr=8-11

With ClearUrls:
https://www.amazon.com/Seagate-BarraCuda-Internal-Drive-3-5-Inch/dp/B07H289S7C

## Miscellaneous Information:

Read Up about ClearURLS
https://clearurls.xyz/2020-08-21-about/

Github:
https://gitlab.com/anti-tracking/ClearURLs/rules/-/commits/master

ClearUrls Extension 
https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk

**Comment by Tonev** [comment]
https://github.com/brave/brave-browser/issues/11250
https://github.com/brave/adblock-rust/issues/166

**Comment by antonok-edm** [comment]
We've had support for `$removeparam` as of Brave 1.47.x (see https://github.com/brave/brave-browser/issues/23927), as well as our own query parameter stripping list - think it's safe to close this.

**Comment by chtpl** [comment]
How do I enable and test this functionality in brave?
