### ISSUE TITLE
Little indication of IPFS tab selected in settings

### ISSUE THREAD

**Issue by 0x1a8510f2** [brave/brave-browser#16111]
## Description 
All settings tabs have icons which change when the tab is selected, except for IPFS which stays grey regardless of selection status.

## Steps to Reproduce

   1. Open settings
   2. Select any tab other than IPFS
   3. Notice that the icon turns orange
   4. Select IPFS tab
   5. Notice that the icon does not turn orange

## Actual result:
IPFS icon shows no indication of selected tab

## Expected result:
IPFS icon changes colour to indicate selected tab

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 1.25.68 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? UNTESTED
- Can you reproduce this issue with the nightly channel? UNTESTED

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? UNTESTED
- Does the issue resolve itself when disabling Brave Rewards? UNTESTED
- Is the issue reproducible on the latest version of Chrome? UNTESTED

## Screenshots:

 Wallet | Extension | Getting started | IPFS
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/83190128/119883317-5247d080-bf27-11eb-9c7a-89f2f9be6e9a.png) | ![image](https://user-images.githubusercontent.com/83190128/119883344-5bd13880-bf27-11eb-86f2-652689375d4d.png) | ![image](https://user-images.githubusercontent.com/83190128/119883382-64297380-bf27-11eb-96d1-e7efd331d43d.png) | ![image](https://user-images.githubusercontent.com/83190128/119883430-71466280-bf27-11eb-9173-fa10b09f28fa.png)

On a somewhat-related note, I believe the hightlighted `Wallet` tab icon could be improved - it's much less highlighted than the others which makes it stick out IMO.

**Comment by rebron** [comment]
@karenkliu Do we have the right states for IPFS mocked up for selection?

**Comment by rebron** [comment]
cc: @spylogsster

**Comment by bbondy** [comment]
@karenkliu can you point to the figma asset to use that fixes this?

**Comment by karenkliu** [comment]
@bbondy  https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=491%3A13498

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

selected | selected | hover | hover
---------|---------|----------|---------
<img width="274" alt="Screen Shot 2021-07-06 at 3 51 55 PM" src="https://user-images.githubusercontent.com/387249/124676014-93aa9480-de72-11eb-8af9-cfb2c4445fec.png"> | <img width="279" alt="Screen Shot 2021-07-06 at 3 54 36 PM" src="https://user-images.githubusercontent.com/387249/124676016-94dbc180-de72-11eb-8885-8d155cf1054a.png"> | <img width="264" alt="Screen Shot 2021-07-06 at 3 52 52 PM" src="https://user-images.githubusercontent.com/387249/124676176-dd937a80-de72-11eb-814a-4d3edf982213.png"> | <img width="280" alt="Screen Shot 2021-07-06 at 3 53 04 PM" src="https://user-images.githubusercontent.com/387249/124676179-de2c1100-de72-11eb-877a-2b84bd5d6c6a.png">

**Comment by karenkliu** [comment]
@stephendonner Dark theme hover seems to be using the incorrect color, and therefore not passing accessibility standards. It should be this: 
<img width="230" alt="Screen Shot 2021-07-06 at 4 35 47 PM" src="https://user-images.githubusercontent.com/2388823/124678855-39143700-de78-11eb-8470-0563e7548c97.png">
`737ADE`
