### ISSUE TITLE
Bug: "Open using IPFS" not shown on public subdomain gateways

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#16116]
Found in nightly-1.27.25-linux-amd64:

 [path gateways](https://docs.ipfs.io/how-to/address-ipfs-on-web/#path-gateway) work as expected, badge is present:

>  ![2021-05-28--01-47-14](https://user-images.githubusercontent.com/157609/119910377-512e9780-bf57-11eb-98f5-97b35683e6d2.png)

 [subdomain gateways](https://docs.ipfs.io/how-to/address-ipfs-on-web/#subdomain-gateway) are missing the badge:

> ![2021-05-28--01-47-31](https://user-images.githubusercontent.com/157609/119910407-63103a80-bf57-11eb-9f56-9a314e31a4a1.png)

cc @spylogsster – this might be related / fixabletogether with https://github.com/brave/brave-browser/issues/16115

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.27.56 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launch Brave
3. load `ipns://brantly.eth`
4. click on `Use a local node`
5. load `https://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi.ipfs.dweb.link/`
6. click on the `Open using IPFS` badge icon in the URL bar
7. confirm it went to `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/`

example | example
---------|---------
<img width="1620" alt="Screen Shot 2021-06-10 at 3 09 24 PM" src="https://user-images.githubusercontent.com/387249/121603809-3ac81780-c9fe-11eb-954a-1b8409ce995b.png"> | <img width="1620" alt="Screen Shot 2021-06-10 at 3 09 28 PM" src="https://user-images.githubusercontent.com/387249/121603816-3f8ccb80-c9fe-11eb-9845-3b83cb431e9f.png">

NOTE: https://github.com/brave/brave-browser/issues/16339 covers the duplication seen right now on `nightly` where `Open using IPFS` keeps appearing, and I'll reverify it separately.
