### ISSUE TITLE
Bug: "Open using IPFS" badge broken on local gateway URLs

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#16115]
(found in nightly-1.27.25-linux-amd64)

Opening a  [path gateways](https://docs.ipfs.io/how-to/address-ipfs-on-web/#path-gateway) URL like https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR or http://127.0.0.1:48080/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR  and clicking on the "Open using IPFS" badge produces an error because duplicated (invalid) path is used in the request:

> ![2021-05-28--01-35-27](https://user-images.githubusercontent.com/157609/119909410-0ca1fc80-bf55-11eb-9cec-912fefc0996f.png)

> ![2021-05-28--01-33-22](https://user-images.githubusercontent.com/157609/119909247-bb920880-bf54-11eb-98c6-8e4d299c0fab.png)

@spylogsster  an example of   [path gateways](https://docs.ipfs.io/how-to/address-ipfs-on-web/#path-gateway) is  `ipfs.io` or `127.0.0.1`. 
 ([Subdomain gateways](https://docs.ipfs.io/how-to/address-ipfs-on-web/#subdomain-gateway)  like `dweb.link` and `localhost` seem to work fine)

**Comment by stephendonner** [comment]
@spylogsster current behavior on `nightly` is for

http://127.0.0.1:48081/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR (or http://127.0.0.1:48080/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR) and https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR to **not** show the `Open using IPFS` badge; should they?

If so, we should file a separate bug, right?

**Comment by spylogsster** [comment]
@stephendonner added https://github.com/brave/brave-browser/issues/16339

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan at https://github.com/brave/brave-core/pull/8971 with build 

Brave | 1.27.62 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. loaded `ipns://brantly.eth`
3. clicked on `Use a local node`
4. loaded `https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`
5. clicked on the `Open using IPFS` badge in the URL bar
6. confirmed it opened `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/` which did **not** have another `Open using IPFS` badge

example | example
--------|----------
<img width="1792" alt="Screen Shot 2021-06-14 at 11 34 47 AM" src="https://user-images.githubusercontent.com/387249/121942444-56386880-cd05-11eb-9ce7-60b7fac48372.png"> | <img width="1792" alt="Screen Shot 2021-06-14 at 11 34 52 AM" src="https://user-images.githubusercontent.com/387249/121942449-56d0ff00-cd05-11eb-9613-d74a52a0a520.png">
