### ISSUE TITLE
Support .zil resolutions for Unstoppable Domains too

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#16125]
Currently we only support .crypto domains for Unstoppable Domains. We should support .zil as well.

**Comment by 4c74356b41** [comment]
should a new issue be opened for additional domains:
```
.coin
.wallet
.bitcoin
.x
.888
.nft
.dao
.blockchain*
```

**Comment by yrliou** [comment]
An update, starting from 1.40.x, we support all domain registries under the Unstoppable Naming System (UNS), including the current .crypto, .x, .coin, .nft, .dao, .wallet, .888, .blockchain, and .bitcoin registries.

**Comment by supermassive** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/24621
