### ISSUE TITLE
Typo in IPFS log message: s/migragion/migration

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16128]
## Description 

Typo in IPFS log message: s/migragion/migration

## Steps to Reproduce

Not sure the actual steps to reproduce, here, yet.

Launching `nightly` with `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --use-dev-goupdater-url` might yield it.

## Actual result:

`Could not add migragion to IPFS: nothing downloaded by ipfs fetcher`

<img width="1256" alt="Screen Shot 2021-05-28 at 8 52 27 AM" src="https://user-images.githubusercontent.com/387249/120010724-54934480-bf92-11eb-9214-a103a35ce1ff.png">

## Expected result:

`Could not add migration to IPFS: nothing downloaded by ipfs fetcher`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.26 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

/cc @spylogsster

**Comment by spylogsster** [comment]
@lidel seems daemon issue

**Comment by lidel** [comment]
Correct, it is a typo on our end, the fix is in https://github.com/ipfs/go-ipfs/pull/8167

**Comment by spylogsster** [comment]
closed as related PR was merged

**Comment by stephendonner** [comment]
Confirmed fixed using `0.9.1` of `go-ipfs` on 


Brave | 1.30.15 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

<img width="828" alt="Screen Shot 2021-08-11 at 4 03 19 PM" src="https://user-images.githubusercontent.com/387249/129115132-b62ac1e4-81ee-4fe0-8a0d-ffc554af2fbc.png">

Now reads `Could not add migration to IPFS: nothing downloaded by ipfs fetcher`.

**Comment by stephendonner** [comment]
(Fixed by non-Chromium upstream - not sure the best resolution/label for this issue.)
