### ISSUE TITLE
Add some text to empty summary state

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16123]
## Description 

Add some text to empty summary state

## Steps to Reproduce

   1. Install 1.26.23 beta build
   2. Connect to FTX account without any balance
   3. Switch to Summary tab shows empty state

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/119944586-59ed9080-bf8c-11eb-8308-fc709551e62c.png)

## Expected result:
Something similar to convert
![image](https://user-images.githubusercontent.com/17010094/119944712-84d7e480-bf8c-11eb-870e-462c3cd78a53.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | `1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @petemill @rebron

**Comment by rebron** [comment]
We should show 0 balance and not empty.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.26.63 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | macOS Version 10.15.7 (Build 19H114)

- Verified empty wallet shows zero balance message
<img width="1312" alt="16123-mac" src="https://user-images.githubusercontent.com/17010094/122439055-36b66f80-cf93-11eb-8f6d-5add1660b2a5.png">

---------
Verification passed on 

Brave | 1.26.63 Chromium: 91.0.4472.106 (Official Build) (64-bit)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | Linux

- Verified empty wallet shows zero balance message
<img width="1054" alt="16123-Linux" src="https://user-images.githubusercontent.com/17010094/122439127-4635b880-cf93-11eb-82b2-720833cbf596.png">

---------
Verification passed on 

Brave | 1.26.63 Chromium: 91.0.4472.106 (Official Build) (64-bit)
-- | --
Revision | `574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}`
OS | Windows 10 OS Version 2009 (Build 19042.1052)

- Verified empty wallet shows zero balance message
<img width="1043" alt="16123-Win" src="https://user-images.githubusercontent.com/17010094/122439205-5a79b580-cf93-11eb-8430-b02019801073.png">
