### ISSUE TITLE
Brave Adblocker filter list 'unbreak' should stop whitelisting 1p DuckDuckGo analytics in Aggressive mode (I guess happens with other sites as well)

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#16133]
Hi,
We all know, Brave didn't block 1p in the beginning, but since that has changed with the introduction of Aggressive mode, I think Brave adblocker Unbreak.txt filter list (and maybe other lists) should stop whitelisting stuff, like that.

Earlier today, someone was saying how "Brave adblocker doesn't block DDG ads", the only thing that aggressive mode doesn't block compared to uBlock are some ddg images that have the _**improving.duckduckgo.com**_ URL on them.
Of course, it doesn't matter if you add a custom filter to block it, nothing will happen because it is an exception on the unbreak internal Brave list https://github.com/brave/adblock-lists/blob/master/brave-unbreak.txt which users can't do anything about unless you Brave Team do it.

But the commit about it it is like too old, dated back in September 2018 (https://github.com/brave/adblock-lists/commit/d8e1edb02141ebb510e68827a4297d8ad539b9a2) when aggressive mode wasn't really implemented at all, and Brave was meant to block only 3p.
But you even whitelisted it as "DDG 1P analytics and optimization", well, I don't think people who set stuff to aggressive want really have anything to do with DDG analytics.

Of course I mention DDG, but I will have to guess it happens with other sites as well and I think it would be a good idea to revisit Unbreak filter list and see what really unbreak sites and what was done to whitelist 1p, because you wanted to be nice about it, I mean, you are still nice since the default is Standard mode, and that's fine, but Aggressive should not have these whitelisted 1p stuff that doesn't break sites when blocked.

The closer Brave blocks to uBlock in aggressive mode the better, it will also stop users from assuming uBlock is just better just because they can see ads being blocked by uBlock while they don't see the same or any increase in the tracking or ads blocked at all in Brave adblocker like happens in DDG.

Thank you.

**Comment by pes10k** [comment]
Thanks for the note @HGhostRevisionist88 .  I think this is a great idea, the only constraint here is that we don't currently have a way of saying a network rule should only be applied in aggressive or standard mode, which would need to be some addition brave-specific syntax we'd need to add.  Thats not impossible of course, but its just more than a simple list addition or removal.

Anyway, TL;DR; its a good idea and we should do it.  It'll just take a little more intermediate plumbing before we can handle the direct issue.  Updates to come!

**Comment by antonok-edm** [comment]
I think it's been safe to close this as per changes to the default blocking policy detailed in https://brave.com/en-in/privacy-updates/9-web-compat-blocking/. The filter is no longer in `brave-unbreak` and I confirmed that requests to `improving.duckduckgo.com` are unblocked in default mode, but blocked in aggressive mode.
