### ISSUE TITLE
Brave tab crashes on youtube when it's memory footprint reaches 4GB

### ISSUE THREAD

**Issue by EnderShadow** [brave/brave-browser#16136]
## Description 
When watching youtube streams with many chat messages the tab will crash with a SIG_TRAP exception. This happens once the memory footprint for the tab reaches 4GB as seen in brave's task manager. This issue has also been happening for a while.

## Steps to Reproduce
   1. Watch a live stream from a popular streamer (for example, Ina from Hololive EN)
   2. Wait until the tab's memory footprint reaches 4GB

## Actual result:
The tab crashes usually with a SIG_TRAP exception

## Expected result:
The tab does not crash

## Reproduces how often: 
This easily reproduces.

## Brave version (brave://version info)
Brave: 1.24.86 Chromium: 90.0.4430.212 (Official Build) (64-bit)
Revision: e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS: Linux

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Untested
- Can you reproduce this issue with the nightly channel? Untested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
This may occur when the tab reaches 4GB usage in general, but I haven't tested that. It's also possible that this is youtube.com/sw.js causing the issue.

**Comment by ryanbr** [comment]
Does adding  `||youtube.com/sw.js` into `brave://adblock` help? @EnderShadow

**Comment by EnderShadow** [comment]
I'll test it and report back

**Comment by EnderShadow** [comment]
The tab still crashed. Apparently it also occurs on past livestreams as well.

**Comment by ryanbr** [comment]
How does youtube get to 4G in size? What does `≡ -> More Tools -> Task Manager` show

I would try, turning off GPU acceleration via `brave://settings/system`, disable ALL extensions. And failing that a new profile

**Comment by EnderShadow** [comment]
Hardware acceleration is already off. I'll do some more testing.

**Comment by EnderShadow** [comment]
Hmm, apparently it has nothing to do with the memory reaching 4GB. I now have no clue what the cause is, just that it happens only on youtube when watching livestreams. I assume lots of comments are still the reason, but I have no clue if that's actually true.

**Comment by EnderShadow** [comment]
Yeah, I've still had it a few times. Sometimes it's a SIG_KILL signal though
