### ISSUE TITLE
Brave Sync is broken

### ISSUE THREAD

**Issue by sobuj53** [brave/brave-browser#16131]
## Description 

Brave sync is broken both in android and Desktop. I can't leave sync chain nor remove a already added device! Also in android I can't find any option to scan QR code to add my device in sync chain.

## Steps to Reproduce

   1. Navigate to `brave://settings/braveSync/setup` Click on remove added device. It doesn't remove it.
   2. Now click on Sync everything then click reload button. The preference is lost.
   3. Click on `Leave sync chain` but nothing changes.
   4. Open brave in android. Go to sync menu. Click add device, there is no option to scan QR code to attach PC and android to sync chain. 

## Actual result:

Please watch the video 
[https://youtu.be/K5RsLsBjZOw](https://youtu.be/K5RsLsBjZOw)

## Expected result:
The browser should follow the user command.

## Reproduces how often: 

Every time

## Desktop Brave version:

Brave | 1.25.68 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2009 (Build 19042.985)

## Android Device details:
   - Install type (ARM, x86): ARMv8
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by DoDoENT** [comment]
I have a similar issue, but trying to sync my Brave on Linux and Mac. After clicking the `Leave sync chain` on Linux, it leaves the chain and automatically recreates a new chain (I can verify this by observing the chain code). This makes it impossible to join the sync chain started on my Mac (which also contains a Brave on my iPhone).

**Comment by joshuadavidson** [comment]
I have the same issue on using Brave for Windows. I click leave sync chain and then open the sync menu again only to be met by a newly created chain. I am unable to sync my PC due to this. 

Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
@joshuadavidson do you have multiple profiles? Curious if there are some other factors causing the bug?

**Comment by jsecretan** [comment]
@sobuj53 @DoDoENT @joshuadavidson sorry for the inconvenience, would you be willing to submit some additional debugging information from brave://sync-internals on the system where you are seeing these errors?  Using this form:

https://upload-support.brave.com/sync

Thanks for any information you can provide so we can get to the bottom of this.

**Comment by joshuadavidson** [comment]
@bsclifton & @jsecretan no inconvenience at all--just busy day. Here is some more context: 

I have a Windows machine with two logins (personal and work) each which use Brave with only the default profile configured. My personal Windows login works great and is actively synced with other devices without issue. When I try to join this sync chain while logged in with my work Windows profile this is where I see the issue described above. I was able to workaround the issue today by deleting the default Brave profile while logged in with my work Windows profile and configuring a new Brave profile. 

I have gone ahead and submitted the sync-internals for both my personal and work windows profiles--hopefully this helps and my workaround hasn't tainted the quality of these logs.
Work Windows Profile case number: `33b63587-9fa5-4980-87b4-1981697cd141`
Personal Windows Profile case number: ``

**Comment by jsecretan** [comment]
Thanks @joshuadavidson, we have @AlexeyBarabash taking a look at what you provided

**Comment by sobuj53** [comment]
Hi, 
Thanks for looking it up. here is the log `aa4f3b2a-1b66-4f9c-bcf7-c0705d7c545e`.
There is another problem, when I try to sync my PC with my mobile, if I scan the QC code from my PC to my mobile; the mobile device doesn't connect with the PC but connect with itself!

**Comment by AlexeyBarabash** [comment]
as per 
>Also in android I can't find any option to scan QR code to add my device in sync chain.

This may happened if there are no Google Services on the device. We use official API to scan QR code and it requires to have Google Services installed on device. @sobuj53 , maybe you have one of the latest Huawei devices?

**Comment by AlexeyBarabash** [comment]
About 
> I can't leave sync chain nor remove a already added device! 

Currently to leave the sync chain, device must send DELETE device record to server and get successfull response. This is done to ensure all other devices are aware about the current device has left the chain. And if there are either network issue or server gives error status, device will not leave the chain. There is in-progress PR for this https://github.com/brave/brave-core/pull/10044 .

@sobuj53 right now as an emergency way you can press `Disable Sync (Clear Data)` button on brave://sync-internals page.

**Comment by DoDoENT** [comment]
@jsecretan, here is my upload ID `a2536bf0-29ec-4feb-b488-8e712428cb64`. I couldn't do it earlier as I only have access to the Linux computer in question on weekends.

The weird part is that the traffic log in the sync-internals tab is completely empty and the about tab shows that the sync client ID is not initialized, while I do have my sync chain code - I'm just not able to join the sync chain created on another computer.

**Comment by DoDoENT** [comment]
> right now as an emergency way you can press Disable Sync (Clear Data) button on brave://sync-internals page.

This also worked for me - after clicking that, Brave allowed me to enter sync code from my other computer and joined the sync chain. Now everything works as expected.

**Comment by sobuj53** [comment]
> right now as an emergency way you can press `Disable Sync (Clear Data)` button on brave://sync-internals page.

Thank you very much. This works like a charm.

**Comment by CPete88** [comment]
Follow-Up: Kept the Sync menu open and `brave://sync-internals` open in a separate tab. Running `Disable Sync (Clear Data)` then makes the Sync menu show the option to start a new sync chain. So the temporary fix works.

**Comment by jsecretan** [comment]
Closing this because I believe the above fixes the issue and is now deployed.

**Comment by bobbywang1900** [comment]
Had the same issues, 
I had to leave the sync chain on all computers and mobile devices (tablets, cell phones) 
Then I uninstalled Brave and reinstalled it using the latest version downloaded from the website. 
Then I shared the new sync code across all devices
Hope this helps others

**Comment by skippy2481** [comment]
> ## Description
> Brave sync is broken both in android and Desktop. I can't leave sync chain nor remove a already added device! Also in android I can't find any option to scan QR code to add my device in sync chain.
> 
> ## Steps to Reproduce
> 1. Navigate to `brave://settings/braveSync/setup` Click on remove added device. It doesn't remove it.
> 2. Now click on Sync everything then click reload button. The preference is lost.
> 3. Click on `Leave sync chain` but nothing changes.
> 4. Open brave in android. Go to sync menu. Click add device, there is no option to scan QR code to attach PC and android to sync chain.
> 
> ## Actual result:
> Please watch the video https://youtu.be/K5RsLsBjZOw
> 
> ## Expected result:
> The browser should follow the user command.
> 
> ## Reproduces how often:
> Every time
> 
> ## Desktop Brave version:
> Brave	1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)
> Revision	1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
> OS	Windows 10 OS Version 2009 (Build 19042.985)
> ## Android Device details:
> * Install type (ARM, x86): ARMv8
> * Device type (Phone, Tablet, Phablet): Phone
> * Android version: 11
> 
> ## Version/Channel Information:
> * Can you reproduce this issue with the current release?  Yes
> * Can you reproduce this issue with the beta channel? Haven't tried
> * Can you reproduce this issue with the nightly channel? Haven't tried
> 
> ## Other Additional Information:
> * Does the issue resolve itself when disabling Brave Shields? No
> * Does the issue resolve itself when disabling Brave Rewards? No
> * Is the issue reproducible on the latest version of Chrome? No
> 
> ## Miscellaneous Information:

I worked great for me and the issue I was facing was moving brave from my pc so that I could reinstall windows 11 and the add the same brave folder back to my fresh windows install so that I would not loose my brave rewards thank you so much
