### ISSUE TITLE
Incorrect error message for expired TLS certs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16137]
## Description 

Sites with an expired TLS cert show a "your clock is ahead".

Also reported on https://community.brave.com/t/expired-server-certificate-handled-as-client-clock-error/253930.

## Steps to Reproduce

   1. Visit <https://expired.badssl.com/>

## Actual result:

![Screenshot from 2021-05-28 19-25-07](https://user-images.githubusercontent.com/167821/120055366-6dc7df80-bfea-11eb-8d24-57646924ab9a.png)

## Expected result:
![Screenshot from 2021-05-28 19-25-37](https://user-images.githubusercontent.com/167821/120055379-89cb8100-bfea-11eb-9012-0c5881133a9f.png)

## Reproduces how often: 
Always

## Desktop Brave version:
```
Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Linux
```

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 3a
   - Android version: 11

## Version/Channel Information:

- Can you reproduce this issue with the current release?  YES
- Can you reproduce this issue with the beta channel?  YES
- Can you reproduce this issue with the nightly channel?  YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  NO

**Comment by gvladas** [comment]
same problem 

![51e356d397f1eb7dc3b292b1e6bc78dfa7311acf](https://user-images.githubusercontent.com/85923127/122414200-3f08ad80-cf87-11eb-825f-5d0c0484be53.jpeg)
![f3d2157f2a5626fe20dbd9c0a6c70e77d9a9d749](https://user-images.githubusercontent.com/85923127/122414202-3fa14400-cf87-11eb-91bb-76632429d4d6.jpeg)

**Comment by shrirenjith** [comment]
Same issue with multiple sites .

**Comment by tewe** [comment]
I can reproduce this with Brave 1.25.72 on macOS 11.4.

![Clock 2021-06-21 at 19 02 03@2x](https://user-images.githubusercontent.com/645412/122900633-26184780-d34d-11eb-943f-db2b6c660216.png)
![Expired 2021-06-21 at 19 02 38@2x](https://user-images.githubusercontent.com/645412/122900643-29abce80-d34d-11eb-804b-e27333e28156.png)

I think this is wrong, but you could argue that it's user-friendly. In the unlikely case that the clock really is wrong, this message is actionable. An expired certificate only is actionable to developers.

**Comment by gvladas** [comment]
> I can reproduce this with Brave 1.25.72 on macOS 11.4.
> 
> I think this is wrong, but you could argue that it's user-friendly. In the unlikely case that the clock really is wrong, this message is actionable. An expired certificate only is actionable to developers.


There must be an option Proceed, as on Chrome, to continue with an expired certificate.



![Image_058](https://user-images.githubusercontent.com/85923127/122906973-f9ffc500-d352-11eb-8a8b-47ee82b490f5.jpg)
![Image_059](https://user-images.githubusercontent.com/85923127/122907011-008e3c80-d353-11eb-8158-09931b0197a4.jpg)

**Comment by sallyoh** [comment]
Same here June 2021: can't get to my own website because "the clock is wrong" but it is correct. Any workaround?

**Comment by bbleslie98** [comment]
The issue is still present on the Brave version 1.26.67, with Chromium: 91.0.4472.114

**Comment by gvladas** [comment]
> The issue is still present on the Brave version 1.26.67, with Chromium: 91.0.4472.114

and Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)

**Comment by diracdeltas** [comment]
@sallyoh does your website have a valid TLS cert? (does it work in other browsers?)

we initially thought this was due to an out of date build timestamp, but the timestamp seems right so we need to dig further

**Comment by sallyoh** [comment]
it does have a valid TLS cert and the site is working now...

**Comment by cyrilchristin** [comment]
_Issue still present for expired TLS certs_

Reproduced via https://expired.badssl.com/ on Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit) (Windows 10)

![Brave-vs-Chrome-Bug-Expired-Certs](https://user-images.githubusercontent.com/55538276/124450154-6f708a00-dd84-11eb-8b7c-18974e93101e.gif)

- Clock time is valid & synced
- Issue not present on Chrome Version 91.0.4472.124 (Official Build) (64-bit) (Windows 10)

_Extra Point:  I think that such a situation where there is absolutely no way to bypass an error should be avoided. There should be some way to bypass such errors, even if it takes multiple (advanced) steps to do so (eg. flag to enable & typing thisisabadidea). Such situations are rendering the browser unusable and forcing the user to switch browsers_

**Comment by jms1voalte** [comment]
Still present, `Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (x86_64)` on macOS 11.3.

**Comment by cyrilchristin** [comment]
_Issue still present on latest **nightly** build_
`Version 1.28.70 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit) (Windows 7)`
![2021-07-12_09-51-14](https://user-images.githubusercontent.com/55538276/125250642-c92e0280-e2f6-11eb-9aa7-a0cdd2a436d5.gif)

**Comment by alexandrevicenzi** [comment]
Same issue on openSUSE 15.3

**Comment by iefremov** [comment]
fwiw for me it works fine in current beta, but not nightly/stable
Brave | 1.27.100 Chromium: 91.0.4472.124 (Official Build) beta (x86_64)
-- | --

**Comment by cyrilchristin** [comment]
Issue still present in _current beta_ in my latest tests:

Build | Version | Status
------------ | ------------- | -------------
Official | 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit) (Windows 7) | Clock error
Beta | 1.27.102 Chromium: 91.0.4472.124 (Official Build) beta (64-bit) (Windows 7) | Clock error
Nightly | 1.28.77 Chromium: 92.0.4515.93 (Official Build) nightly (64-bit) (Windows 7) | Clock error

![2021-07-14_10-49-21](https://user-images.githubusercontent.com/55538276/125594332-963b1d69-ad6b-4bcc-a8c9-c6c0ef6e187d.gif)

**Comment by cdmichaelb** [comment]
Still an issue on:
Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)

**Comment by cyrilchristin** [comment]
Issue still present in builds:

Build | Version | Status
------------ | ------------- | -------------
Official | 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit) (Windows 7) | Clock error
Beta | 1.28.83 Chromium: 92.0.4515.93 (Official Build) beta (64-bit) (Windows 7) | Clock error
Nightly | 1.29.3 Chromium: 92.0.4515.101 (Official Build) nightly (64-bit) (Windows 7) | Clock error

**Comment by APB9785** [comment]
Just encountered this issue in the wild
Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (x86_64)
macOS 10.14.6

**Comment by iefremov** [comment]
thanks for the reports, we are looking into this.

**Comment by iefremov** [comment]
The problem is caused by some discrepancies in how "precise" network time is determined in the browser. We are figuring out a fix

**Comment by dutchkillscreative** [comment]
Is it possible to include a hotfix to allow a user to proceed through the advanced menu like other certificate issues?

**Comment by diracdeltas** [comment]
@dutchkillscreative if there's no button to proceed in the advanced menu, you could try typing `thisisunsafe` (option 2 in https://www.technipages.com/google-chrome-bypass-your-connection-is-not-private-message)

**Comment by iefremov** [comment]
Should be fixed now.

**Comment by bbleslie98** [comment]
> Should be fixed now.

It works for me in the latest official release, great news! Thank you!

**Comment by iefremov** [comment]
Fixed with https://github.com/brave/devops/pull/5518

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.29.30 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5.1 (Build 20G80)

Steps:
1. new profile
2. launched Brave
3. loaded `https://expired.badssl.com/` and confirmed I got the same experience as in the `Expected Results`
4. confirmed clicking on `Advanced` and then `Proceed to expired.badssl.com` let me through to `https://expired.badssl.com/`

example | example | example
---------|---------|----------
<img width="1247" alt="Screen Shot 2021-07-26 at 6 02 39 PM" src="https://user-images.githubusercontent.com/387249/127078837-036cb0bb-e13a-41f9-b534-adbf5de15aa5.png"> | <img width="1247" alt="Screen Shot 2021-07-26 at 6 05 54 PM" src="https://user-images.githubusercontent.com/387249/127078841-5472ef33-fc17-4702-9ff6-3fab398720f1.png"> |  <img width="1247" alt="Screen Shot 2021-07-26 at 6 07 45 PM" src="https://user-images.githubusercontent.com/387249/127078900-f9aaa89d-ea42-48b8-8d07-edf44427accc.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.29.51 x64 Beta build
- Verified interstitial page shows connection is not private message
- Verified proceed to page loads the page correctly 

![image](https://user-images.githubusercontent.com/17010094/128339968-0d3e745a-adad-4f75-a924-89f2d921756e.png) | ![image](https://user-images.githubusercontent.com/17010094/128339956-d3195422-84a5-4dfe-ba79-8c4abc3bf024.png) | ![image](https://user-images.githubusercontent.com/17010094/128339945-258659ac-bc9c-49ea-b639-e0de6805df69.png) | ![image](https://user-images.githubusercontent.com/17010094/128339914-b3220dfd-f406-4718-b45b-16ce57dbfb02.png)
-- | -- | -- | --

-------
Verification passed on Oppo Reno 5 with Android 11 running 1.29.51 x64 Beta build
- Verified interstitial page shows connection is not private message
- Verified proceed to page loads the page correctly 

![image](https://user-images.githubusercontent.com/17010094/128339795-2f011ff3-3a37-4666-b80b-0207af10a6d4.png) | ![image](https://user-images.githubusercontent.com/17010094/128339817-0ef94607-0318-4ac1-a61b-8d592841b0fa.png) | ![image](https://user-images.githubusercontent.com/17010094/128339839-ce34a510-035b-467b-b8e9-a81f59946c71.png) | ![image](https://user-images.githubusercontent.com/17010094/128339874-7df2eccd-3cda-4016-b48c-aea28a58e0cf.png)
-- | -- | -- | --

**Comment by jryagersr** [comment]
Stilll getting this on Brave [Version 1.37.113 Chromium: 100.0.4896.88 (Official Build) (x86_64)]

OSX El Capitan Version 10.11.6 (15G22010) (latest update for machine)

Loading this URL

https://community.brave.com/t/computers-date-and-time-are-incorrect-error/261672

**Comment by jryagersr** [comment]
Unfortunately, the latest allowed on this machine.
