### ISSUE TITLE
How can you generate a QR code?

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#16139]
In Chromium 91.0 the flag 'Enable sharing page via QR Code' has been deleted.
Chrome, Chromium, and Edge show this in the right-click menu, but Brave doesn't.
![QR-Code](https://user-images.githubusercontent.com/53431361/120073660-98bd3c80-c099-11eb-8bf1-814bfc629f5c.jpg)

**Comment by kjozwiak** [comment]
@Johann999 we're planning on re-enabling the QR code feature in `1.26.x` which is scheduled for release on `June 22, 2021` as per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule. You can follow the GH issue that re-enables the above via https://github.com/brave/brave-browser/issues/15900. If you want to use the feature, you can use it on either Nightly or BETA for the time being (added links below) until `1.26.x` is released.

* **`Nightly`** --> https://brave.com/download-Nightly/
* **`BETA`** --> https://brave.com/download-beta/
