### ISSUE TITLE
Update URL for Japan NTP Page

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#16130]
## Description 

For ticket https://github.com/brave/brave-browser/issues/15526
Please update the URL from https://brave.com/ja/users-bitflyer/ to https://brave.com/ja/desktop-ntp-tutorial

cc @Miyayes

**Comment by soham4abc** [comment]
Cannot find the link in the project pls help.

**Comment by soham4abc** [comment]
@rebron @anthonypkeane  Please review I have made a PR related to this issue. Please!

**Comment by rebron** [comment]
@anthonypkeane When is this page https://brave.com/ja/desktop-ntp-tutorial going live?

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.18 Chromium: 91.0.4472.114 (Official Build) nightly （x86_64）
-- | --
変更履歴 | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS バージョン11.4（ビルド20F71）

Steps:
1. set language + region in macOS to Japanese/Japan, respectively
2. new profile in Brave
3. launched Brave
4. looked at 2nd opened (but not focused) tab

Confirmed the URL in the 2nd tab is now `https://brave.com/ja/desktop-ntp-tutorial/`

<img width="1312" alt="スクリーンショット 2021-06-21 17 25 37" src="https://user-images.githubusercontent.com/387249/122844134-d3d81780-d2b5-11eb-91b4-b210afeac629.png">
