### ISSUE TITLE
Improving the UX of the settings bar

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#16141]
## Description 
Every time I see a new update I hope you have fixed it... 😂

## Actual result:
![image](https://user-images.githubusercontent.com/19390797/120091386-3c3e3980-c0fa-11eb-8013-cf964e031962.png)

## Expected result:
![image](https://user-images.githubusercontent.com/19390797/120091381-33e5fe80-c0fa-11eb-82a2-ba06697200f4.png)

**Comment by srirambv** [comment]
cc: @rebron @bradleyrichter @karenkliu

**Comment by rebron** [comment]
Closing as wontfix. Location of Settings is where we want it, similar placement as Chrome and Edge as well with 'Settings' title on the left of page.
