### ISSUE TITLE
privacy leak !

### ISSUE THREAD

**Issue by Deosaju** [brave/brave-browser#16146]
As using multiple private windows. the logins are being copied from one window to another!.
This won't make a good private space for doing things! 

Solution 
1. either remove the numbering of private tabs 
2. update the fix such that all private windows are independent.

Support by Tipping!

#privacy #Bugs #solve

**Comment by srirambv** [comment]
Its not leak its the expected behaviour for the session. Its like logging into Gmail in a private tab and then opening a new tab with gmail again and making the tabs into two separate windows. Individual private windows are not going to give you separate session. 

cc: @bridiver @pes10k
