### ISSUE TITLE
Brave Shield popup in private windows (UX)

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#16149]
## Description 
Information **popup always appears** when a new private window is opened **which is very annoying**.
In my opinion it would be best to remove this window completely because it adds nothing and an inexperienced person will click the only visible button anyway.

## Steps to Reproduce

   1. open a private window
   2. view sample page
   3. click on the shield

## Actual result:
![image](https://user-images.githubusercontent.com/19390797/120209290-04c8ad80-c21e-11eb-9e3f-1300fa6d2902.png)

## Expected result:
![image](https://user-images.githubusercontent.com/19390797/120209309-0b572500-c21e-11eb-83b5-4c62fc4e6fd0.png)

## Reproduces how often: 
100%

**Comment by rebron** [comment]
Closing/duplicate. Will be resolved as part of shields UI refresh 2.0.
https://github.com/brave/brave-browser/issues/18630
