### ISSUE TITLE
Tab Groups toggle glitch

### ISSUE THREAD

**Issue by mizzunet** [brave/brave-browser#16140]
## Description 
Tab Groups can't be turned off. 
## Steps to reproduce 

   1. Update to Version 1.25.69
   2. Disable Tab Group toggle
   3. Relaunch

## Actual result 

If disable the toggle and relaunch Brave it still stays on enabled

## Expected result
Just disable that.

## Issue reproduces how often 
It never disables 

## Version/Channel Information:

Haven't tried yet
- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Haven't tried
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): OnePlus 5
   - Android version: 11
   
## Brave version
Version 1.25.69

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Haven't tried

### Additional information

I hate this tab group feature in phone

**Comment by srirambv** [comment]
Did you try turning it off from Settings -> Appearance ? You will have to restart the browser after enable/disable setting.
<img width=300 src=https://user-images.githubusercontent.com/17010094/120144495-e771f000-c1d9-11eb-9726-e1fd7bbbba27.png>

**Comment by srirambv** [comment]
Reproduced the issue. Toogle doesn't seem to stick gets reenabled after relaunch.

cc: @samartnik

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.71 x64 build
- Verified on a clean install tab-group settings is enabled by default
- Verified on a clean install open link in tab-group works as expected
- Verified disabling the tab-group options triggers relaunch prompt
- Verified disabling the tab-group option and restarting keeps the setting intact and disable gird view in tab tray
- Verified after tab-group is disabled, context menu doesn't show `Open link in a tab-group` option
- Verified re-ordering tabs and disabling tab-group options doesn't reset the tabs positions
- Verified re-ordering tabs and re-enabling tab-group option regroups all the tabs as before
- Verified if tab-group is enabled on older build, upgrading to 1.25.71 build retains the settings and retains tab groups
- Verified if tab-group is disabled on older build, upgrading to 1.25.71 build retains the setting in disabled state and shows tabs in stack layout
- Verified tab-grouping works on both normal and private tabs when enabled
- Verified tab stack layout works fine on both normal and private tabs when disabled
- Verified closing a tab group in tab tray and click on `Undo` restores the tab group
- Verified no `Group tabs` option is shown in tab-tray view when menu is opened
- Verified able to drag and drop tabs in groups from tab-tray when settings is enabled
- Verified able to open custom tabs when tab-group setting is enabled or disabled
- Verified able to open New tab or private tab from home screen
- Verified no crash when setting is enabled or disabled
- Verified able to create a new tab inside a tab group via new tab button in tab-group bar and via tab-tray grid view
- Verified able to swipe switch tabs within tab-group and outside tab-group by swiping the bottom toolbar
- Verified tab-groups or stack layout works fine with bottom toolbar disabled

![image](https://user-images.githubusercontent.com/17010094/121110872-e3f7ed80-c805-11eb-982d-71864eef7953.png) | ![image](https://user-images.githubusercontent.com/17010094/121110865-dfcbd000-c805-11eb-8406-32e8d6508bce.png)
-- | --

------------
Verification passed on Samsung Tab A with Android 10 running 1.25.71 x64 build
- Verified no tab-group setting is shown for tablets
- Verified no context menu option for tab-group is shown on long press on a link

<img width=500 src=https://user-images.githubusercontent.com/17010094/121111377-a8115800-c806-11eb-864f-9ac1f4259bcf.png>

https://user-images.githubusercontent.com/17010094/121111401-b52e4700-c806-11eb-82e4-632c19891f19.mp4
