### ISSUE TITLE
No option to connect Brave Wallet to Gemini

### ISSUE THREAD

**Issue by MDouglas345** [brave/brave-browser#16154]
## Description 
The newest update to Nightly allowed support for users to connect Gemini accounts to verify their wallets; however no option to choose is seen and is defaulted to using Uphold to verify wallet.

## Brave version (brave://version info)

Brave | 1.27.27 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;(arm64)
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.2 (Build 20D64)

## Version/Channel Information:
Feature only available in nightly

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

**Comment by aaronsantamaria** [comment]
It’ll appear in a new minor version of v1.27.x Nightly
I think we can close this
