### ISSUE TITLE
Clear notification if you claim grant

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1615]
## Description 

We don't remove notification in panel after you claim grant on settings page

## Steps to Reproduce

   1. enable rewards
   2. claim grant
   3. click on BAT logo

## Actual result:

you see notification

## Expected result:
notification shouldn't be shown after you claim grant

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Shows even after the grant is claimed
![image](https://user-images.githubusercontent.com/17010094/47100377-535be180-d205-11e8-9640-a40005e6ef21.png)

**Comment by NejcZdovc** [comment]
@srirambv this is a problem, so that grant is not cleared after claim

**Comment by GeetaSarvadnya** [comment]
Currently, the notification is shown in Private tabs as well. Even this needs to be removed
@NejcZdovc @bbondy 


![image](https://user-images.githubusercontent.com/38657976/47239433-ee6dda80-d402-11e8-8270-ea60783aba2f.png)

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya please create separate issue where we shouldn't show this icon if logo is disabled

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Sure

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows
