### ISSUE TITLE
Pages will occasionally break when opening

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#16156]
## Description 
Opening a link is causing page rendering to break

## Steps to Reproduce

   1. Opening https://www.citibikenyc.com/ caused broken css to show.
   2. Opening a link (or copy/paste) will occasionally show a broken page 
   3. 

## Actual result:

![citibike](https://user-images.githubusercontent.com/1659004/120244216-c2ef4400-c2bd-11eb-8792-6f16f49b3b62.png)

## Expected result:
(After a reload)
![citibike-nightly](https://user-images.githubusercontent.com/1659004/120244532-8ff98000-c2be-11eb-9650-57cafb5daaf4.png)

## Reproduces how often: 

Intermittent issue, 

## Brave version (brave://version info)
```
Brave	1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)
Revision	1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS	Windows 10 OS Version 2009 (Build 19042.985)
JavaScript	V8 9.1.269.28
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
Command Line	"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,AutoupgradeMixedContent,SafetyTip,WinrtGeolocationImplementation,LegacyTLSEnforced,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=InterestCohortAPIOriginTrial,AutofillServerCommunication,HandwritingRecognitionWebPlatformApi,FledgeInterestGroups,InterestCohortFeaturePolicy,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,EnableProfilePickerOnStartup,TextFragmentAnchor,FederatedLearningOfCohorts,IdleDetection,NotificationTriggers,WebOTP,SubresourceWebBundles,NetworkTimeServiceQuerying,LangClientHintHeader,SignedExchangePrefetchCacheForNavigations,FirstPartySets,SignedExchangeSubresourcePrefetch,TrustTokens,DirectSockets,SharingQRCodeGenerator,TabHoverCards,LiveCaption --flag-switches-begin --load-media-router-component-extension=0 --enable-features=WebUIDarkMode,AutoupgradeMixedContent,SafetyTip,WinrtGeolocationImplementation,LegacyTLSEnforced,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,BraveAdblockCosmeticFilteringNative --flag-switches-end
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  Unsure
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Reported by another users, https://community.brave.com/t/some-sites-have-sudden-problems-in-brave/254484/10

**Comment by ryanbr** [comment]
Affecting Chrome also:

![chrome-citi](https://user-images.githubusercontent.com/1659004/120245025-0b0f6600-c2c0-11eb-9def-739b356ef3fd.png)

**Comment by kjozwiak** [comment]
Seeing the same results as @ryanbr, was able to reproduce the above on both `Brave` & `Chrome`. Example:

**`1.27.24 Chromium: 91.0.4472.77`** | **`90.0.4430.212 (Official Build) (64-bit) (cohort: Stable)`**
-----------------------------------------|-----------------------------------------------------------------
![image](https://user-images.githubusercontent.com/2602313/120264389-b215e280-c26b-11eb-807a-3669c3c8806b.png) | ![image (1)](https://user-images.githubusercontent.com/2602313/120264405-b93cf080-c26b-11eb-8144-d19db91246d7.png)
