### ISSUE TITLE
Move setting info below the header

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16164]
## Description 
Move setting info below the header

## Steps to reproduce 

   1. Install 1.26.46 x64 build
   2. Open settings
   3. Brave shields & privacy, global setting info is below the settings rather than the title

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/120287917-99cbb500-c2b7-11eb-9d6c-e0fd12883490.png)

## Expected result
Setting details to be below the header

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.24.46 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @karenkliu @jamesmudgett @anthonypkeane

**Comment by anthonypkeane** [comment]
https://bravesoftware.slack.com/archives/C0816QH3R/p1622534058183700

**Comment by kjozwiak** [comment]
Closing this as https://github.com/brave/brave-core/pull/9012 was merged into `1.26.x` which fixes the above.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.26.53 x64 build
- Verified setting info is below the header

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<Img width=300 src=https://user-images.githubusercontent.com/17010094/121176604-4ed01580-c854-11eb-9e85-c30ea2eaf581.png> | <Img width=400 src=https://user-images.githubusercontent.com/17010094/121176583-4972cb00-c854-11eb-8731-c6c6dee91ca7.png>
