### ISSUE TITLE
Sidebar UI should be hidden only when tab-initiated full screen

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#16160]
## Description 

On macOS, sidebar UI is hidden when browser enters full screen mode.
Sidebar only should not be visible when browser is in fullscreen by tab. (ex, youtube video fullscreen mode)

## Steps to Reproduce

   1. Enable sidebar feature via brave://flags relaunch
   2. Check sidebar is visible
   2. Maximize browser on macOS
   3. Check sidebar is visible

## Actual result:

Sidebar is hidden after browser is maximized

## Expected result:
Sidebar should not be hidden in maximized mode.

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above will require `1.44.68` or higher for `1.44.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:
1. installed `1.44.78`
2. launched Brave
3. ensure the sidebar was visible by default
4. maximized the window

#### Confirmed the sidebar was retained in full-screen mode

`1.44.73` | `1.43.88`
----------|---------- 
 <img width="1680" alt="Screenshot 2022-09-02 at 1 06 59 PM" src="https://user-images.githubusercontent.com/387249/188228697-2180e1a8-ed45-4ded-8ccf-b222cc6cc74d.png"> | <img width="1680" alt="Screenshot 2022-09-02 at 1 06 06 PM" src="https://user-images.githubusercontent.com/387249/188228681-9c5fff08-cb1b-47da-a7b6-8a4df03804d0.png">

#### Also ensured that the sidebar was hidden in YouTube's fullscreen mode

`YouTube`, default | `YouTube`, fullscreen
-------------------|----------------------- 
<img width="1312" alt="Screenshot 2022-09-02 at 1 12 04 PM" src="https://user-images.githubusercontent.com/387249/188229382-34be9946-d0eb-4d85-83b0-57e395f6698c.png"> | <img width="1680" alt="Screenshot 2022-09-02 at 1 12 14 PM" src="https://user-images.githubusercontent.com/387249/188229398-c95b5aed-3d0a-46da-9766-95244711461f.png">
