### ISSUE TITLE
Browser crash when opening downloads from menu

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16168]
## Description 
Browser crash when opening downloads from menu

## Steps to reproduce 

   1. Install 1.26.46
   2. Open Menu
   3. Click on Downloads, browser crash

## Actual result 

https://user-images.githubusercontent.com/17010094/120290784-9259db00-c2ba-11eb-8a3f-9761f0d8304b.mp4

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.26.46

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Closing this as https://github.com/brave/brave-core/pull/9012 was merged into `1.26.x` which fixes the above.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.53 x64 build
- Verified no crash when opening Downloads from menu
---------
Verification passed on Samsung Tab A with Android 10 running 1.26.53 x64 build
- Verified no crash when opening Downloads from menu
