### ISSUE TITLE
IPFS missing from privacy settings 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16165]
## Description 
IPFS missing from privacy settings 

## Steps to reproduce 

   1. Install 1.26.46 x64 build
   2. Open Settings -> Brave Shields & Privacy
   3. No setting found for `IPFS Gateway`

## Actual result <vs Expected result

Actual | Expected
-- | --
![image](https://user-images.githubusercontent.com/17010094/120289456-38a4e100-c2b9-11eb-89f2-0bbe5239fa80.png) | ![image](https://user-images.githubusercontent.com/17010094/120289423-2f1b7900-c2b9-11eb-8c43-f92de8e4e465.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version-? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.26.46

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @samartnik @mkarolin

**Comment by kjozwiak** [comment]
Closing this as https://github.com/brave/brave-core/pull/9012 was merged into `1.26.x` which fixes the above.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.26.53 x64 build
- Verified IPFS setting is listed under other privacy settings 
- Verified IPFS setting is enabled by default

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<Img width=300 src=https://user-images.githubusercontent.com/17010094/121179873-17636800-c858-11eb-94a7-8d7633b6c608.png> | <Img width=400 src=https://user-images.githubusercontent.com/17010094/121180005-3feb6200-c858-11eb-869f-cfcbc1f5fe46.png>
