### ISSUE TITLE
"chrome://" still being displayed when editing URL bar

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1616]
## Description 

When editing the URL bar, you'll still be able to see the `chrome://` protocol handler rather than the `brave://`

## Steps to Reproduce

   1. open either `dev` or `beta`
   2. visit `brave://settings` and start editing the URL once the page loads

## Actual result:

![urlprotocal](https://user-images.githubusercontent.com/2602313/47024827-7799be80-d130-11e8-91e5-8ea643062170.gif)

## Expected result:

Shouldn't be displaying the `chrome://` protocol handler when editing the URL box.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds?

Yes, currently reproducible on both `dev` and `beta` builds:

Brave | 0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

Brave | 0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/chrome-reference-in-brave-settings/35882

**Comment by srirambv** [comment]
+1 from @kirkins via #1973 for copy paste `brave://`

**Comment by fmarier** [comment]
This will be fixed by https://github.com/brave/brave-core/pull/1074.

**Comment by srirambv** [comment]
+1 from @anushshetty8  via #3170

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.11 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used STR from the description.
Checked all URL from: `brave://chrome-urls/`

**Comment by bsclifton** [comment]
Re-opening as this fix was reverted
