### ISSUE TITLE
Ethereum Name Service missing from privacy settings 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16167]
## Description 
Ethereum Name Service missing from privacy settings 

## Steps to reproduce 

   1. Install 1.26.46 x64 build
   2. Open Settings -> Brave Shields & Privacy
   3. No setting found for `Ethereum Name Service`

## Actual result <vs Expected result

Actual | Expected
-- | --
![image](https://user-images.githubusercontent.com/17010094/120289456-38a4e100-c2b9-11eb-89f2-0bbe5239fa80.png) | ![image](https://user-images.githubusercontent.com/17010094/120289423-2f1b7900-c2b9-11eb-8c43-f92de8e4e465.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version-? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.26.46

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @samartnik @mkarolin

**Comment by kjozwiak** [comment]
Closing this as https://github.com/brave/brave-core/pull/9012 was merged into `1.26.x` which fixes the above.
