### ISSUE TITLE
Use connect wallet modal on Rewards page

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#16178]
The Rewards page should be updated to display the new connect wallet modal added in #15787. The old "blue" verification modal will no longer be displayed after this change.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.27.76 Chromium: 91.0.4472.114 (Official Build) dev (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)


## Uphold (US)

**Steps:**
1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3. opened a new tab
4. clicked on `Start using Rewards`
5. clicked on the BAT icon in the URL bar
6. clicked on `Verify Wallet`
7. clicked on `Continue >`
8. clicked on `Uphold`
9. clicked on `Continue to login`
10. clicked on `Authorize`
11. logged in to Uphold
12. confirmed I saw my balance, and `Wallet Verified` state

| example | example  | example | example | example | example 
--------------- | ---------------- | ------------- | ----------------|---------------- | -------------|
| <img width="1312" alt="Screen Shot 2021-06-22 at 3 36 22 PM" src="https://user-images.githubusercontent.com/387249/123009977-971e2600-d372-11eb-8e1f-60899f127c97.png"> | <img width="1312" alt="Screen Shot 2021-06-22 at 3 37 43 PM" src="https://user-images.githubusercontent.com/387249/123009983-99808000-d372-11eb-8b42-0d8c568809c7.png"> | <img width="1312" alt="Screen Shot 2021-06-22 at 3 37 50 PM" src="https://user-images.githubusercontent.com/387249/123009987-9b4a4380-d372-11eb-915a-fb51f54a8a82.png"> | <img width="1312" alt="Screen Shot 2021-06-22 at 3 38 40 PM" src="https://user-images.githubusercontent.com/387249/123009991-9be2da00-d372-11eb-9e83-4c9fdbe71ab2.png"> | <img width="1098" alt="Screen Shot 2021-06-22 at 3 53 20 PM" src="https://user-images.githubusercontent.com/387249/123009996-9d140700-d372-11eb-91da-a8f95cbc523e.png"> | <img width="1312" alt="Screen Shot 2021-06-22 at 3 40 11 PM" src="https://user-images.githubusercontent.com/387249/123009995-9c7b7080-d372-11eb-88fa-c931bad8218f.png"> |

## bitFlyer (Japan)

**Steps:**
1. new profile; OS region and language set to Japan and Japanese, respectively
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3. opened a new tab
4. clicked on `Start using Rewards`
5. clicked on the BAT icon in the URL bar
6. clicked on `Verify Wallet`
7. clicked on `Continue >`
8. clicked on `bitFlyer`
9. logged in using QA's test credentials
10. confirmed I saw a balance, and `Wallet Verified` state

example | example | example | example | example
---------|----------|----------|---------|---------
<img width="1312" alt="スクリーンショット 2021-06-22 15 46 33" src="https://user-images.githubusercontent.com/387249/123010743-12cca280-d374-11eb-80f7-99fb94d64c12.png"> | <img width="1312" alt="スクリーンショット 2021-06-22 15 46 55" src="https://user-images.githubusercontent.com/387249/123010747-14966600-d374-11eb-904c-8edc32851e60.png"> | <img width="1312" alt="スクリーンショット 2021-06-22 15 46 59" src="https://user-images.githubusercontent.com/387249/123010751-16602980-d374-11eb-9e26-e7df3c40e214.png"> | <img width="1090" alt="スクリーンショット 2021-06-22 15 49 01" src="https://user-images.githubusercontent.com/387249/123010755-16f8c000-d374-11eb-9ff2-5be835310109.png"> | <img width="1312" alt="スクリーンショット 2021-06-22 16 04 29" src="https://user-images.githubusercontent.com/387249/123010756-17915680-d374-11eb-960c-f83d25beef99.png">
