### ISSUE TITLE
IPFS Interstital page is oddly formatted on Android

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16170]
## Description 
IPFS Interstital page is oddly formatted on Android

## Steps to reproduce 

   1. Install 1.26.46 x64 Beta Build
   2. Visit an IPFS URI to trigger interstitial page
   3. Page looks oddly formatted

## Actual result 

OnePlus 6T | Samsung Tab A
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/120315492-56cc0a80-c2d4-11eb-89b9-468ab7be0bcd.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/120315326-24baa880-c2d4-11eb-89ec-da77f1766de3.png>

## Expected result
On current release build
![image](https://user-images.githubusercontent.com/17010094/120315338-28e6c600-c2d4-11eb-9be7-1932d725606b.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.26.46 Beta Build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @spylogsster

**Comment by spylogsster** [comment]
it seems fixed in latest Nigthly, I cannot reproduce it, @srirambv can you check?

**Comment by srirambv** [comment]
@spylogsster yes this seems fixed on current nightly. Do you happen to know if its due to any PR changes? If so can you link it so it can ride the trains and get verified as it still happens on 1.26.x 

Going to close this as verified on Nightly(1.28.11) but still needs to be checked on other channels 

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/122632395-7469e400-d0ca-11eb-97c5-facf8c9de723.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/122632489-ff4ade80-d0ca-11eb-8b4c-6856ce5f8eb0.png>

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.28.99 x64 Beta Build

Oppo R5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/127975163-8fd84615-7184-4254-ac0d-b1f5d2b74174.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/127975156-8a47cf11-2b3a-42e9-be63-cbdbd4eb727f.png>
