### ISSUE TITLE
Media Notifications [Feature Request]

### ISSUE THREAD

**Issue by therealsujitk** [brave/brave-browser#16187]
## Description 

It would be convenient to have a notification with media buttons whenever a video or an audio track is being played in the browser. That way it would be possible to control the player from the notification menu while using another application rather than switching to Brave every time.

### Preview

![Screenshot from 2021-06-02 09-58-52](https://user-images.githubusercontent.com/60378235/120424075-4fb30400-c389-11eb-9659-f7d257778d8f.png)

## Brave version (brave://version info)

Brave | 1.25.68 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Linux

**Comment by therealsujitk** [comment]
This feature is already present in Chromium. Is there a reason it was removed in Brave?

**Comment by therealsujitk** [comment]
@rebron This feature is already present in Chromium. Is there a reason it was removed in Brave?

**Comment by therealsujitk** [comment]
@bridiver, this issue only occurs in the linux snap build, can you add the [OS/Linux/snap](https://github.com/brave/brave-browser/issues?q=is%3Aopen+is%3Aissue+label%3AOS%2FLinux%2Fsnap) label to this issue?

**Comment by fmarier** [comment]
We added a work-around in https://github.com/brave/brave-browser-snap/pull/19, but the real fix is to expose the correct service name instead of `org.mpris.MediaPlayer2.chromium` in https://source.chromium.org/chromium/chromium/src/+/main:components/system_media_controls/linux/system_media_controls_linux.cc;l=54;drc=12be03159fe22cd4ef291e9561762531c2589539

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.51.98 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}
OS | Ubuntu 22.04 LTS


Verified controls are shown when playing youtube video:
![image](https://user-images.githubusercontent.com/34715963/234354448-6dacb27f-d2e5-4fd2-b0df-3806cc6654e1.png)

Verified playlist on youtube is supported
![image](https://user-images.githubusercontent.com/34715963/234358682-0b8c9e38-96a3-4644-905c-104d04b75b5c.png)

Verified controls are shown when playing rumble video:
![image](https://user-images.githubusercontent.com/34715963/234355787-27b2516b-17f8-4677-959e-c550d423a972.png)

Verified test plan from https://github.com/brave/brave-core/pull/17440
`./mpris_player_control -l`
![image](https://user-images.githubusercontent.com/34715963/234357236-5854a332-1125-4bcd-996f-3bf2131196f6.png)
`./mpris_player_control -c`
![image](https://user-images.githubusercontent.com/34715963/234357385-4b1c3abe-f049-46ea-971e-d995836dab46.png)
