### ISSUE TITLE
Update global themes in Chromium and Cocoa APIs with Brave design system styling and components

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#16180]
## Description 

The global themes in Chromium views and Cocoa apis are not aligned with Brave design system styling and components, causing lower accessibility and user trust.

## Actual result:

All of our browser dialogs have this global styling issue. Here's a recent example:

![image](https://user-images.githubusercontent.com/2388823/120393412-be8b5100-c2e6-11eb-8ede-d049a1df43d7.png)

![image](https://user-images.githubusercontent.com/2388823/120393423-c2b76e80-c2e6-11eb-9a61-7e03d3135f38.png)

## Expected result:

![image](https://user-images.githubusercontent.com/2388823/120393454-ca771300-c2e6-11eb-8699-e1f9f28913f9.png)

![image](https://user-images.githubusercontent.com/2388823/120393463-cd720380-c2e6-11eb-918e-3034a710d19a.png)

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by keur** [comment]
cc @petemill

**Comment by petemill** [comment]
Are there any released examples? The existing dialogs do use the consistent Brave theming:

![image](https://user-images.githubusercontent.com/741836/120399750-7de50500-c2f1-11eb-83e4-d04e044bbc33.png)

I suggest we use those elements within the new Speedreader dialog.

**Comment by keur** [comment]
@pes10k Most the dialog is fine. It seems to just be `views::ToggleButton` and the link highlighting.

**Comment by karenkliu** [comment]
Something that might help if we can't get Poppins into the dialog is using a lower font weight for the bolded text - currently it's using an extremely heavy weight.

**Comment by rebron** [comment]
Closing as stale.
