### ISSUE TITLE
Remove "Gmail" language in SafeBrowsing text

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16181]
## Description

Currently, some "Gmail" language appears in the browser.  

![image](https://user-images.githubusercontent.com/11497541/120396576-c528c100-c304-11eb-8a2d-c63e8532fdcf.png)

## Solution

Remove "Gmail" language in the Brave browser.

## Reports

https://www.reddit.com/r/brave_browser/comments/nq2w0i/what_i_didnt_know_that_gmail_was_a_brave_service/

**Comment by srirambv** [comment]
This is an issue on Android as well

**Comment by Areckleh** [comment]
Reports through Brave Support Twitter DMs
![image](https://user-images.githubusercontent.com/43886134/123694603-25852280-d81f-11eb-894c-89a8ccd35faf.png)

**Comment by rebron** [comment]
https://github.com/brave/brave-browser/issues/11345 I think this is only Android and not on Desktop.

**Comment by akshat-rawat** [comment]
Hi, I would like to work on this issue. 
I have tracked down the root of this issue at `brave-core/app/settings_strings.grdp`, `brave-core/browser/ui/android/strings/android_chrome_strings.grd` and in `.xtb` files.

**Comment by srirambv** [comment]
@akshat-rawat Assigned the issue to you. Please open a PR for it.

**Comment by akshat-rawat** [comment]
@srirambv, Thankyou for the opportunity, I just wanted to confirm the changes.
From. 
`Does not protect you against dangerous websites, downloads and extensions. You’ll still get Safe Browsing protection, where available, in other Brave services, like Gmail and Search.`
To,
`Does not protect you against dangerous websites, downloads and extensions.`

Or is there a better alternative?

**Comment by srirambv** [comment]
Looping in @fmarier @karenkliu  for text change. We may want to keep the `You'll still get Safe Browsing protection` part

**Comment by akshat-rawat** [comment]
What about?
`Does not protect you against dangerous websites, downloads and extensions. You’ll still get Safe Browsing protection, where available, in other Brave services, like Search and Passwords.`

**Comment by karenkliu** [comment]
cc @rmcfadden3 on this for the text change. We have an in-house copywriter now and should filter all our text through them.

**Comment by akshat-rawat** [comment]
@karenkliu, please let me know if there are any updates on what the changed text should be.

**Comment by rmcfadden3** [comment]
How about this:

Does not protect you against dangerous websites, downloads, or extensions. (Where available, you’ll still get safe browsing protection in other Brave services.)

**Comment by srirambv** [comment]
@rmcfadden3 We proxy safe browsing requests so we may want to somehow mention that in there. Someone from @brave/sec-team may pitch in on it.

**Comment by soham4abc** [comment]
I am working on this issue. making the message " Does not protect you against dangerous websites, downloads, and extensions. (Where available, you’ll still get safe browsing protection in other Brave services.)"

**Comment by srirambv** [comment]
@soham4abc Think @akshat-rawat  may already have a PR up for it. You can always choose any issues from [here](https://github.com/brave/brave-browser/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

As for the wording I'd wait till someone from security team responds and @rmcfadden3 can update accordingly which can be used.

**Comment by soham4abc** [comment]
> @soham4abc Think @akshat-rawat may already have a PR ready for it. You can always choose any issues from [here](https://github.com/brave/brave-browser/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).
> 
> As for the wording I'd wait till someone from security team responds and @rmcfadden3 can update accordingly which can be used.

Okay then I am making a PR. If the wording needs to be changed I will do so. 
If possible please do assign me for this issue!
Thank you!

**Comment by soham4abc** [comment]
> @soham4abc Think @akshat-rawat may already have a PR ready for it. You can always choose any issues from [here](https://github.com/brave/brave-browser/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).
> 
> As for the wording I'd wait till someone from security team responds and @rmcfadden3 can update accordingly which can be used.

Okay sure! I already made a PR and if required will close it if @akshat-rawat  has the PR I will close my PR later.

**Comment by akshat-rawat** [comment]
@soham4abc  I do have a PR ready just wanted to confirm the changed text.

**Comment by soham4abc** [comment]
> @soham4abc  I do have a PR ready just wanted to confirm the changed text.

Sure... My PR is closed! Go ahead!

**Comment by akshat-rawat** [comment]
Is "Does not protect you against dangerous websites, downloads, or extensions. (Where available, you’ll still get safe browsing protection in other Brave services.)"
final or are we still waiting, @srirambv?

**Comment by srirambv** [comment]
We should wait on https://github.com/brave/brave-browser/issues/16181#issuecomment-872693209

**Comment by fmarier** [comment]
Given that we don't run GMail and Google Search, I think we should simply drop the second sentence and just have:

> Does not protect you against dangerous websites, downloads, or extensions.

That's why it's not recommended. You're turning off all of the Google Safe Browsing protections if you choose that option.

**Comment by akshat-rawat** [comment]
Should i move forward with `Does not protect you against dangerous websites, downloads, or extensions.`?

**Comment by srirambv** [comment]
@akshat-rawat yes please. Go ahead and create the PR

**Comment by akshat-rawat** [comment]
@srirambv, I have created the [PR](https://github.com/brave/brave-core/pull/9334).
If there are any updates required, do let me know.

**Comment by bsclifton** [comment]
Removing assignment as above PR was closed

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.28.99 64 Beta build
- Verified references to Brave is removed from safe browsing settings

Oppo R5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/127874567-aca7c873-7d01-4b6a-9302-83d6fd086a66.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/127874593-4371752c-5184-449b-b32a-218fde5b4244.png>
