### ISSUE TITLE
Left Margin too small when viewing FB page

### ISSUE THREAD

**Issue by dclose-im** [brave/brave-browser#16195]
## Description 
Left margin in too small when viewing Facebook and some other pages. I have checked tha same pages in other browsers and the margins appear are not jammed up on the left side.
![FB_margin](https://user-images.githubusercontent.com/56736277/120496796-7d954a00-c383-11eb-9617-fe52cdcc8ad8.JPG)

## Steps to Reproduce

   1.  Open Facebook group page
   2.  I have tried zooming in and out but no change to the left margin.
   3. 

## Actual result:
The left margin is too small - see attached screenshot

## Reproduces how often: 
Happens 100% of the time.

## Brave version (info found on brave://version)
Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)

**Comment by rebron** [comment]
@dclose-im Can you post additional screenshot examples, I'm not seeing what you mean by left margin by being too small. I'm on FB now and not seeing anything that looks out of the ordinary. 

Do you have an extension enabled that may be causing the left margin issue or some additional ad block filter turned on?

**Comment by rebron** [comment]
Closing as stale. @dclose-im We can reopen. Let us know if you're still experiencing this problem on 1.31.87 or if an extension might be causing this issue for you.
