### ISSUE TITLE
Brave Core (Dev + Beta) upgrades are causing Brave Rewards to lose all data (and there are other files missing as well from Brave directory)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#1619]
Existing issue: No such issues exists in the current set

## Description 
After upgrading both dev and beta builds, the Brave Rewards state (reconcile, synopsis, wallet, etc.) lose state and are unusable. This is a critical issue that needs to be fixed.

Before Upgrade Image 
![image](https://user-images.githubusercontent.com/35932307/47027907-34822000-d11d-11e8-896a-824e4e2594d9.png)

After Upgrade Image (Version 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)
![image](https://user-images.githubusercontent.com/35932307/47027974-48c61d00-d11d-11e8-9e43-5489ff57e38f.png)

After debugging with @NejcZdovc here is what files were supposed to be there in the 'Default' directory;
![image](https://user-images.githubusercontent.com/35932307/47028104-832fba00-d11d-11e8-886a-f18a6d87b202.png)

And here is what was left in my directory after upgrade causing the issue with Brave Rewards;
Mandars-MacBook-Pro:Default mandar$ ls -ltr
total 1080
-rw-r--r--@ 1 mandar  staff     164 Oct 15 05:27 README
-rw-------@ 1 mandar  staff   65536 Oct 15 05:27 Web Data
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 Web Data-journal
drwx------@ 7 mandar  staff     224 Oct 15 05:27 Site Characteristics Database
-rw-------@ 1 mandar  staff  118784 Oct 15 05:27 History
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 History-journal
-rw-------@ 1 mandar  staff   20480 Oct 15 05:27 Favicons
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 Favicons-journal
-rw-------@ 1 mandar  staff   16384 Oct 15 05:27 previews_opt_out.db
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 previews_opt_out.db-journal
drwx------@ 7 mandar  staff     224 Oct 15 05:27 data_reduction_proxy_leveldb
-rw-------@ 1 mandar  staff   16384 Oct 15 05:27 page_load_capping_opt_out.db
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 page_load_capping_opt_out.db-journal
drwx------@ 7 mandar  staff     224 Oct 15 05:27 BudgetDatabase
drwx------@ 3 mandar  staff      96 Oct 15 05:27 Sync Data
-rw-------@ 1 mandar  staff   18432 Oct 15 05:27 Login Data
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 Login Data-journal
-rw-------@ 1 mandar  staff   12288 Oct 15 05:27 Shortcuts
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 Shortcuts-journal
-rw-------@ 1 mandar  staff   36864 Oct 15 05:27 Network Action Predictor
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 Network Action Predictor-journal
drwx------@ 7 mandar  staff     224 Oct 15 05:27 Thumbnails
drwx------@ 7 mandar  staff     224 Oct 15 05:27 GPUCache
-rw-------@ 1 mandar  staff   20480 Oct 15 05:27 Top Sites
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 Top Sites-journal
-rw-r--r--@ 1 mandar  staff  131072 Oct 15 05:27 Visited Links
-rw-------@ 1 mandar  staff   20480 Oct 15 05:27 Cookies
-rw-------@ 1 mandar  staff       0 Oct 15 05:27 Cookies-journal
-rw-------@ 1 mandar  staff    3982 Oct 15 05:27 Translate Ranker Model
drwx------@ 3 mandar  staff      96 Oct 15 05:27 Local Storage
drwx------@ 7 mandar  staff     224 Oct 15 05:28 Extension State
-rw-------@ 1 mandar  staff     557 Oct 15 05:28 Current Session
drwx------@ 7 mandar  staff     224 Oct 15 05:28 Extension Rules
drwx------@ 3 mandar  staff      96 Oct 15 05:28 Local Extension Settings
drwx------@ 3 mandar  staff      96 Oct 15 05:28 Sync Extension Settings
drwx------@ 3 mandar  staff      96 Oct 15 05:28 Managed Extension Settings
-rw-------@ 1 mandar  staff   20480 Oct 15 05:28 Origin Bound Certs
-rw-------@ 1 mandar  staff       0 Oct 15 05:28 Origin Bound Certs-journal
-rw-------@ 1 mandar  staff     434 Oct 15 05:28 Current Tabs
-rw-r--r--@ 1 mandar  staff       6 Oct 15 05:28 History Provider Cache
-rw-------@ 1 mandar  staff   17034 Oct 15 05:28 Secure Preferences
-rw-------@ 1 mandar  staff    7284 Oct 15 05:28 Preferences
-rw-------@ 1 mandar  staff     233 Oct 15 05:28 Network Persistent State

## Steps to Reproduce

   1. Reproduces if any Brave Core user upgrade with BR on by going to About Brave, upgrading and launching
   2. Quickest way to upgrade is when BR is ON, go to About Brave, upgrade and if Brave gets stuck (which is 90% of the times) and does not relaunch, force relaunch it and will reproduce 100% of the time.
 

## Actual result:
See images in Description

## Expected result:
BR synopsis, states, etc. should remain intact after upgrade.
Upgrades are not supported from Muon to Core but should be supported within Core itself.

## Reproduces how often: 

100% of time if user has BR ON and relaunches manually after upgrade (since 0.55)

## Brave version (brave://version info)

See details above - did not capture build number before upgrade.

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 
On both Dev and Beta builds for Brave Core

cc @NejcZdovc

**Comment by srirambv** [comment]
Here's the observation on Linux

Updated from `0.55.12 -> 0.55.14`
• Contribution list retained
• Wallet balance retained
• `publisher_info_db` was retained in profile folder
• Contribution date was messed up (07/06/50843)
• Publisher icons for YouTube got messed up (shows blank page icon, other icons remained correctly) 

Upgraded `0.55.13 -> 0.55.14`
• Wallet balance retained correctly
• Contribution list retained
• `publisher_info_db-journal` was retained in profile folder
•  Contribution date was messed up (07/06/50843)
• Publisher icon retained. 

Updated from `0.56.2 -> 0.56.4`
• Contribution list retained
• Wallet balance retained
• `publisher_info_db` was retained in profile folder
• Contribution date was messed up on dev as well (07/06/50843)
• Publisher icons were retained nothing was showing default icons

Upgrade from `0.56.3 -> 0.56.4`
• Contribution list was lost on upgrade (https://youtu.be/ZzQGMLN_yYo)
• Wallet balance was retained
• Contribution date was messed up
• Pubs icon was retained

**Comment by rebron** [comment]
wontfix.
