### ISSUE TITLE
yarn install not working

### ISSUE THREAD

**Issue by JPRuehmann** [brave/brave-browser#162]
### Steps to Reproduce

git clone https://github.com/brave/brave-browser.git
cd brave-browser
yarn install

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by garrettr** [comment]
@JPRuehmann Can you provide more info about how `yarn install` is failing? Maybe an error message?

**Comment by garrettr** [comment]
@JPRuehmann What version of Node do you have installed? The error message suggests you need at least `8.9.2`. AIUI, this problem stems from the fact that `yarn` enforces `engines` version validation whereas `npm` does not: https://github.com/yarnpkg/rfcs/pull/69#issuecomment-308564847.

If upgrading to a Node >= 8.9.2 fixes this problem for you, please let us know! That would suggest we should update the [wiki](https://github.com/brave/brave-browser/wiki/macOS-Development-Environment), which currently says the Brave development environment only requires Node >= 7.x.

**Comment by JPRuehmann** [comment]
No, that does not help. I am using node 9.2.0 and the error still occures.

**Comment by garrettr** [comment]
@JPRuehmann On what platform (Windows, macOS, Linux) are you encountering this error?

**Comment by JPRuehmann** [comment]
Kubuntu 16.04 LTS (32Bit)

**Comment by garrettr** [comment]
Unfortunately, a 64-bit system is required to [build Chromium](https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_build_instructions.md#system-requirements) and therefore to build brave-browser.
