### ISSUE TITLE
Typekit (Adobe font) is getting blocked on Brave Core

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#1621]
## Description 

Uphold sandbox is using Adobe fonts for its delivery and on testing the sandbox on Core, the typekit was getting blocked.

## Steps to Reproduce

   1. Go to https://uphold-widget-uhocggaamg.now.sh/ (hosting Uphold sandbox widget)
   2. See shields

## Actual result:

Shields should not block Adobe fonts 

## Expected result:
Font should not be blocked

## Reproduces how often: 

100% of the time

## Brave version (brave://version info)

All Brave Core builds (latest beta 0.55 Chromium: 70)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 
Brave-Core (not tested on Brave Muon)

**Comment by tomlowenthal** [comment]
Duping this to #1816 .
