### ISSUE TITLE
Implement Brave Ads field trials

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#16213]

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
<!--StartFragment-->
Brave | 1.26.63 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.1052)

<!--EndFragment-->

```

Verified the test plan from https://github.com/brave/internal/issues/776

Scenario 1:  **should_only_serve_ads_if_browser_is_active - default value (true) - browser in foreground**

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.26.65 Chromium: 91.0.4472.114 (Official Build) (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 10.15.7 (Build 19H1030)
```

### should_only_serve_ads_if_media_is_not_playing - default value (true) - youtube - video playing
<details>

Ad was not shown

```
[6780:775:0621/130629.529933:VERBOSE2:permission_rule_util.cc(23)] Media is playing
[6780:775:0621/130629.530025:VERBOSE1:ad_notification_serving.cc(150)] Ad notification not served: Not allowed
[6780:775:0621/130629.530086:VERBOSE1:ad_notification_serving.cc(91)] Ad notification not delivered
```

</details>


### should_only_serve_ads_if_media_is_not_playing - default value (true) - youtube - video paused
<details>

Ad was shown

<img width="1200" alt="21 - should_only_serve_ads_if_media_is_not_playing - default value (true) - youtube - video paused" src="https://user-images.githubusercontent.com/28145373/122801260-e3456980-d291-11eb-99de-c2f0b36c7709.png">

</details>

### should_only_serve_ads_if_media_is_not_playing - false - youtube - video playing

<details>

Ad was shown

<img width="1199" alt="22 - should_only_serve_ads_if_media_is_not_playing - false - youtube - video playing" src="https://user-images.githubusercontent.com/28145373/122801233-db85c500-d291-11eb-8054-38d909907f8e.png">

</details>

### should_only_serve_ads_if_media_is_not_playing - false - youtube - video paused

<details>

Ad was shown

<img width="1200" alt="23 - should_only_serve_ads_if_media_is_not_playing - false - youtube - video paused" src="https://user-images.githubusercontent.com/28145373/122801214-d3c62080-d291-11eb-8481-93fc1842d002.png">

</details>
