### ISSUE TITLE
Truncated text in permission dialog with lifetime options

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#16219]
Increase dialog width or add auto layout based on text with if possible for this dialog.
![image](https://user-images.githubusercontent.com/5928869/120584448-35952680-c45a-11eb-8778-75a476d71878.png)

**Comment by rebron** [comment]
cc: @karenkliu

**Comment by karenkliu** [comment]
Current approach is to show the full dropdown option as alt text on hover over the dropdown, but it would be better to show the full text if possible. 

This is what the dialog is supposed to look like if using our Brave design system styling:

![image](https://user-images.githubusercontent.com/2388823/120687235-aa666180-c456-11eb-85cb-38561ba09b9a.png)

**Comment by goodov** [comment]
@rebron not sure what milestone exactly to set here. The task looks like a UI hotfix.

**Comment by kjozwiak** [comment]
Moving this into `1.27.x` as this landed in `master via https://github.com/brave/brave-core/pull/9006 and hasn't been uplifted into either `1.26.x` or `1.25.x` yet. Once it does land, the @brave/uplift-approvers will move the issue into the appropriate milestone.

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.27.48 Chromium: 91.0.4472.88&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 109e9cd038b94a631aea7d40ee3d56c1278f2597-refs/branch-heads/4472@{#1385}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launch Brave
3. load `permission.site`
4. click on the `HTTPS` toggle
5. click on `Location`
6. look at the prompt
7. constrain the window size
8. look again at the prompt

Confirmed in both cases the `until I close this site` text wasn't truncated any longer.

example | example
---------|---------
<img width="1242" alt="Screen Shot 2021-06-08 at 9 51 43 AM" src="https://user-images.githubusercontent.com/387249/121226687-b039b980-c83f-11eb-86a2-24e3d269dfbf.png"> | <img width="612" alt="Screen Shot 2021-06-08 at 9 56 37 AM" src="https://user-images.githubusercontent.com/387249/121226939-eaa35680-c83f-11eb-94d4-10537b7ffe92.png">

**Comment by stephendonner** [comment]
Verified `PASSED` on 

Brave | 1.25.72 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.5 (Build 20G5033c)

Sorry, meant to verify this before we released, and just forgot, with the other CNAME bug on my to-do list.

<img width="1220" alt="Screen Shot 2021-06-12 at 3 48 53 AM" src="https://user-images.githubusercontent.com/387249/121773506-3f411d00-cb31-11eb-88f1-c7322cabde83.png">
