### ISSUE TITLE
Brave Nightly and Brave Beta Shields 

### ISSUE THREAD

**Issue by AdrianaJ84** [brave/brave-browser#16217]
Hi,  I fiind a problem about Brave Shields. 
Is setup by default but I also change it. 
![162267646245878188](https://user-images.githubusercontent.com/83845684/120565308-6e5edc80-c415-11eb-93e6-e8ec5f978088.jpeg)
If I close the browser and I open again brave shields is default.  I don't understand why but I prefer high shields for more security online. 
My favorites setup for security:
![1622677173246384](https://user-images.githubusercontent.com/83845684/120565377-93534f80-c415-11eb-849b-9a4a6551b873.jpeg)
![162267646245878188 (1)](https://user-images.githubusercontent.com/83845684/120565378-93ebe600-c415-11eb-8e9f-126b6b6f1ddb.jpeg)
![1622677173246384](https://user-images.githubusercontent.com/83845684/120565379-94847c80-c415-11eb-8f7a-ac10167961b1.jpeg)
Also another problem with brave shields is Block Trackers across the sites.
![162267646245878188 (3)](https://user-images.githubusercontent.com/83845684/120565463-c4338480-c415-11eb-9ecb-35b207f3ddeb.jpeg)
Is deactivated by default.  Is not ok because sites can be tracked you,  me and anyone. 
I need activate  for all websites by default. 

This problems presist  3-4 versions ago. 

Please rezolve it this problems. 
Thanks for the support.  Please tell me when is resolve it. Also sorry for my bad English.

**Comment by nastavoi** [comment]
I've noticed this weird behaviour today as well.

"Block trackers & ads" and "Fingerprinting protection" in "Brave shields global default" reset itself from Agressive to Standard after browser restart, but only if "Clear data on exit" is enabled. 

Tested both on latest beta and nightly from Play Store, Android 11, Samsung Galaxy S10+.

**Comment by srirambv** [comment]
Its expected to reset if you have `Clear data on exit` enabled as clearing data would clear the changes you have made. Currently there is no option to select what to clear on exit so entire data/cache/setting is lost. Desktop has the same behaviour if you clear site settings upon exit. Once we implement option to select what to delete it should fix it

cc: @anthonypkeane @SergeyZhukovsky

**Comment by Tonev** [comment]
Not an Android-specific issue:

https://github.com/brave/brave-browser/issues/15347

**Comment by AdrianaJ84** [comment]
Yes, sorry, it was my fault.
Thanks for the help.

The only problem left is Block cross-site trackers.
 I hope this will be remedied along the way.

**Comment by Tonev** [comment]
It's not your fault, you actually did great opening this Github issue, there is still time until the upcoming feature lands in the stable channel. There are 2 issues regarding the upcoming feature that deserve attention:

- First: users can't choose which browsing data they want to clear on exit, an open issue here: https://github.com/brave/brave-browser/issues/16214
- Second: even if users choose to delete the browsing data for "Site and Shields Settings",  that shouldn't affect the global Shields settings, an open issue over here: https://github.com/brave/brave-browser/issues/15347

**Comment by srirambv** [comment]
#15347 is not a bug. That is the expected behaviour. We don't segregate shields settings separately so deleting site settings will reset shields. 

#16214 is something that will probably get done in future releases

**Comment by Furax-31** [comment]
On the nightly version there are big problems concerning the normal mode and the aggressive mode.  Ads and cosmetic filters problem.

**Comment by AdrianaJ84** [comment]
> The only problem left is Block cross-site trackers.
> I hope this will be remedied along the way.

Yep, is now remedied for Brave Nightly. Thanks you so much.
Please also implement for Brave and Brave Beta.
