### ISSUE TITLE
Ask Brave for suggestion needs to be removed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1623]
## Test plan
See https://github.com/brave/brave-core/pull/682

## Description 

Ask Brave for suggestion needs to be removed

## Steps to Reproduce

   1. Visit any site and right click on a text field
   2. Click on SpellCheck->Ask Brave for suggestion
   3. Modal comes up which should be blocked as no data is being sent to any Brave server
![image](https://user-images.githubusercontent.com/17010094/47036352-55149f00-d14a-11e8-8213-09c50cb5e49d.png)

## Actual result:

![spellcheck](https://user-images.githubusercontent.com/17010094/47036332-47f7b000-d14a-11e8-9f71-ad5f04d92e9d.gif)

## Expected result:
Should not show this. Issue was reported on #221 but was just renamed to Brave but not removed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
I can't seem to reproduce the problem on macOS... but I can on Windows.  @srirambv @btlechowski does this also show on Linux?

**Comment by srirambv** [comment]
@bsclifton yes I can see this on both Linux and Windows

**Comment by LaurenWags** [comment]
Verified passed on

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta(64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified option is still not available on macOS

**Comment by kjozwiak** [comment]
@srirambv seems to be working correctly under `Ubuntu 18.04 x64` & `Mint 18.3 x64`. Can you quickly double check to make sure it's working for you as you're the one that initially reported it? You can add the `QA Pass-Linux` if it's working for you as well 👍
