### ISSUE TITLE
Custom ad dismiss area extends beyond `x`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#16230]
Follow up to https://github.com/brave/brave-browser/issues/13137

There is a big area below `x` that will dismiss the ad

## Steps to Reproduce

1. Show a custom ad
1. Click the are shown below
![image](https://user-images.githubusercontent.com/34715963/120690309-55057100-c4a5-11eb-8a64-87ab27526602.png)

Note: it is fine to extend the area around `x` a bit, but this is clearly not intentional

## Actual result:

ad is dismissed

## Expected result:
ad is clicked and landing page is opened

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.26.50 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Ubuntu 18.04 LTS

cc @tmancey @moritzhaller @jsecretan @rebron @brave/legacy_qa

**Comment by tmancey** [comment]
Working as expected as the hit area is required to meet minimum requirements for touch devices such as Windows Surface

**Comment by btlechowski** [comment]
Why not extend it evenly around `x`?

**Comment by tmancey** [comment]
Unfortunately this would make the gap between the BAT Ad icon and the Close button too large

**Comment by btlechowski** [comment]
This is how clickable area looks like for custom ads:
![image](https://user-images.githubusercontent.com/34715963/120698044-ca297400-c4ae-11eb-87d8-bd05b3cfda73.png)

**Comment by btlechowski** [comment]
@jenn-rhim Should we improve handling of `x`? The area was extended to accommodate touch devices.
