### ISSUE TITLE
Brave Shields and UBO not working properly

### ISSUE THREAD

**Issue by gh0sti** [brave/brave-browser#16231]
## Description 

Brave Shields and UBlock Origin are not working properly. On old.reddit.com and new.reddit.com there must have been an update to how Brave Shields work b/c its not blocking sponsor ads but its not allow UBO to use it's element picker to block ads properly and not allow me to block the premium reddit banner. All filters are up to date on UBO and brave. When Brave aggressive ad blocking is turned to standard some of UBO works but the element picker won't even work when pressing the button to block an element. Also Brave's element picker isn't working properly either.

## Steps to Reproduce

   1. Install Brave Browser stable (latest version)
   2. Install Ublock Origin 
   3. head to reddit.com (new or old) and ads are popping up and element picker doesn't work for cosmetic filtering.

## Expected result:
ads should be blocked and UBO element picker should be available

## Reproduces how often: 

easy

## Desktop Brave version:

latest stable verison

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? haven't tried
- Can you reproduce this issue with the nightly channel? haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by gh0sti** [comment]
This issue didn't start till today. Did brave shields logic or anything else change recently?

**Comment by ryanbr** [comment]
I'm not aware of anything, does adjusting shields to aggressive make a difference @gh0sti  ?

**Comment by Tonev** [comment]
It seems to be related to Chromium 91:

- https://www.reddit.com/r/uBlockOrigin/comments/nmfx2a/ublock_stopped_working_on_reddit/
- https://www.reddit.com/r/uBlockOrigin/comments/nqhqkx/i_cant_seem_to_use_element_picker_on_reddit_opera/
- https://www.reddit.com/r/uBlockOrigin/comments/npu743/element_picker_no_longer_working_on_some_pages/

**Comment by ryanbr** [comment]
Interesting, thanks for confirming @Tonev  . Going by the issues, hard to say if the issue is with reddit or uBO. @gh0sti

**Comment by Tonev** [comment]
@ryanbr 

OP might be having issue due to https://bugs.chromium.org/p/chromium/issues/detail?id=1216788.
