### ISSUE TITLE
IPFS interstitial page is shown even when IPFS gateway setting is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16239]
## Description 
IPFS interstitial page is shown even when IPFS gateway setting is disabled

## Steps to reproduce 

   1. Install 1.27.39 nightly build
   2. Disable `IPFS Public Gateway` setting from Privacy & Shields settings
   3. Visit an IPFS URI, loads interstitial page
   4. Click on use public gateway button, loads page even when setting is disabled to use public gateway 

## Actual result 

https://user-images.githubusercontent.com/17010094/120766626-54ef8a80-c512-11eb-8ce8-aa87fd7d91b6.mp4

## Expected result
Should throw error and not show interstitial page if IPFS setting is disabled

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.27.39 Nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @alexsafe @spylogsster

**Comment by kjozwiak** [comment]
Closing this as this was fixed via https://github.com/brave/brave-core/pull/9021.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.59 x64 Beta build
- Verified steps from issue description
- Verified with settings disabled loading IPFS URI throws error
- Verified selecting use public gateway loads the page using IPFS public gateway(dweb.link)
-------------
Verification passed on Samsung Tab A with Android 10 running 1.26.59 x64 Beta build
- Verified steps from issue description
- Verified with settings disabled loading IPFS URI throws error
- Verified selecting use public gateway loads the page using IPFS public gateway(dweb.link)
