### ISSUE TITLE
[Android] remove share stats image after share

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#16247]
## Description 

After sharing the stats, the shared image shouldn't be kept in the device

## Steps to reproduce 

   1. Share some stats either by using the tooltip or the share button from shields 
   2. Check the shared image is still on the device
   3. 

## Actual result 

The image is still in the device after sharing

## Expected result

The shared image should not be in the device anymore.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/8984 landed in `1.27.x`.

**Comment by srirambv** [comment]
Marking as QA/No as this has a follow up issue #17049
