### ISSUE TITLE
Follow up of #14813 - The size of the custom ad notification popup is enlarged after reposition

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16241]
## Description 

Follow up of #14813 - The size of the custom ad notification popup is enlarged after reposition
## Steps to Reproduce

   1. Clean profile 1.26.50
   2. Trigger a custom Ad
   3. Reposition the custom Ad
   4. The size of the custom ad notification popup is enlarged after reposition

## Actual result:

The size of the custom ad notification popup is enlarged after reposition
![custom ad](https://user-images.githubusercontent.com/38657976/120817102-07553b00-c56f-11eb-9d21-9984813ec6e2.gif)

## Expected result:

The size of the custom Ad notification should be fixed
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.26.50 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @tmancey @jsecretan @brave/legacy_qa @rebron

**Comment by btlechowski** [comment]
Not reproducible on Linux

Brave | 1.26.50 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
@tmancey As requested please find the details below:
![image](https://user-images.githubusercontent.com/38657976/120841127-bb16f480-c588-11eb-935d-dcb33724c6d5.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.27.91 Chromium: 91.0.4472.124 (Official Build) beta (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

```
- Verified the STR from https://github.com/brave/brave-browser/issues/16241#issue-911554355
- Confirmed that the size of the custom Ad notification remained fixed after Ads reposition
![a](https://user-images.githubusercontent.com/38657976/124600998-f7d65400-de84-11eb-9fbe-90ec6428cb74.gif)
