### ISSUE TITLE
The upcoming "Clear data on exit" feature is hardly compatible with the aggressive mode for ads & trackers blocking and the strict fingerprinting protection preference

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#16250]
Moving the discussion over here since https://github.com/brave/brave-browser/issues/16214 was closed yesterday.

Disabling "Clear data on exit" by default is a step into the right direction, but unfortunately it's not enough as of the moment. I'll try to go into detail because the problem is deeper than people think at first.

Let's begin over here:
https://github.com/brave/brave-core/pull/8790

The mentioned pull request introduces the global Shields settings functionality, along with an aggressive mode for ads & trackers blocking, a strict fingerprinting protection, and eventually an option to clear the browsing data on exit.

Here comes the issue, which makes the "Clear data on exit" option hardly compatible with the aggressive ads & trackers mode and the strict fingerprinting protection:

- https://github.com/brave/brave-browser/issues/15347
- https://github.com/brave/brave-browser/issues/16217

Since the "Clear data on exit" option includes the clearing of the browsing data for "Site and Shields Settings", and that can't be changed anyhow, the following will happen:

- A lot of users will enable the aggressive mode for ads & trackers blocking, along with a strict fingerprinting protection
- Then a lot of users will enable the "Clear data on exit" option, because it's a highly anticipated option
- Closing the browser will lead to the following: https://github.com/brave/brave-browser/issues/16217

In other words, if users want to use all 3 new features (aggressive blocking of ads & trackers, a strict fingerprinting protection, and want to clear their browsing data on exit), they'll have to re-adjust the global Shields settings every single time they open their browser, because clearing the browsing data for "Site and Shields Settings" will reset the global Shields settings every single time users close their browser.

My suggestions until https://github.com/brave/brave-browser/issues/15347 is fixed:

- Allow users to choose which browsing data they want to clear on exit so they can disable the clearing of the browsing data for "Site and Shields Settings"
- If the previous suggestion is a lot of work for the remaining time until the next major release, simply exclude the clearing of the browsing data for "Site and Shields Settings" from the "Clear data on exit" feature
- If, for some reason, the option above is not possible either, introduce a warning dialog that informs users of the consequences of clearing the browsing data

If you proceed with the implementation of the "Clear data on exit" feature in its current state, you'll give users a false sense of stronger privacy protection. A lot of users won't notice that their global Shields settings have reset to their default values after they close their browser (clear their browsing data).

**Comment by bridiver** [comment]
Unless I'm missing something this doesn't appear to be a distinct issue from https://github.com/brave/brave-browser/issues/15347 and https://github.com/brave/brave-browser/issues/16217 (which itself is a dup of 15437)?

**Comment by Tonev** [comment]
> Unless I'm missing something this doesn't appear to be a distinct issue from #15347 and #16217 (which itself is a dup of 15437)?

If we exclude the suggestions I made here, it's correct to call it a duplicate of #15347. If you add the OS/Android to #15347, I'll close this one since #15347 will address the issue on both desktop and mobile, as it should.

**Comment by bridiver** [comment]
We’ve identified two distinct issues, one that is android specific and one that is desktop and android. The android only issue has a PR ready

**Comment by Tonev** [comment]
Yes, it's a distinct issue that site settings browsing data was a part of the "Clear data on exit" feature, and it's great there's already a PR to fix that. But #15347 is still an issue on both desktop and mobile, and unless I'm missing something, it should receive the OS/Android label, and after that I'll be able to close this issue in order to keep things sorted.

**Comment by Tonev** [comment]
@bridiver 

All right, after having my morning coffee, I realized what you mean. I'll close this issue in favor of https://github.com/brave/brave-browser/issues/16259, since the PR addressing it makes the "Clear data on exit" option compatible with the mentioned features, which fixes this issue in a way.

P.S. When you have the opportunity, take a look at  #15347 whether it needs the OS/Android label since I can't add any labels myself.
