### ISSUE TITLE
Global settings doesn't retain state after restart

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16259]
## Description 
Global settings doesn't retain state after restart

## Steps to reproduce 

   1. Clean install 1.26.53 Beta build
   2. Set Block cross-site trackers to aggresive
   3. Set Fingerprint blocking to aggressive
   4. Set Cookies to block all
   5. Set clear data on exit
   6. Quit and relaunch the browser all global shields settings are reset
   7. Click on individual setting and click done, gets reset back to aggressive/block all on its own

## Actual result 

https://user-images.githubusercontent.com/17010094/121000577-48716900-c782-11eb-916f-8f6c02c7c957.mp4

## Expected result
Do not reset global settings after restart

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.26.53

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @bridiver @alexsafe

**Comment by Tonev** [comment]
That's the result of clearing the browsing data for "Site and Shields Settings", which is part of the "Clear data on exit" feature.

https://github.com/brave/brave-browser/issues/16250

**Comment by bridiver** [comment]
this is a dup of https://github.com/brave/brave-browser/issues/15347

**Comment by bridiver** [comment]
so there are two separate issues here:
1. Global settings are deleted with content settings (@srirambv is checking on our behavior vs upstream)
2. "Clear data on exit" is incorrectly deleting content settings

**Comment by bridiver** [comment]
the original issue was correct https://github.com/brave/brave-browser/issues/7487 with `Clear cache, cookies, history`, but somehow site settings was incorrectly included in that. Site settings should only be cleared when users select it from the clear data dialog.

**Comment by srirambv** [comment]
Global settings are not deleted with content settings on Chrome. Setting Cookies to block (globally) and clearing all time data doesn't reset it back to Block 3rd-party cookies in Incognito (Default global setting). We however seem to do it so need to fix that

**Comment by kjozwiak** [comment]
Closing as this was fixed in `master` with https://github.com/brave/brave-core/pull/9040 and uplifted into `1.26.x` via https://github.com/brave/brave-core/pull/9049.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.63 x64 build
- Verified global settings changed are retained when data is set to clear on exit

https://user-images.githubusercontent.com/17010094/122349067-c2a0ab00-cf43-11eb-90f2-8c43c33786c9.mp4

-----------
Verification passed on Samsung Tab A with Android 10 running 1.26.63 x64 build
- Verified global settings changed are retained when data is set to clear on exit

https://user-images.githubusercontent.com/17010094/122349932-a5b8a780-cf44-11eb-9737-610958847183.mp4
