### ISSUE TITLE
npm run init fails when env is empty

### ISSUE THREAD

**Issue by bershanskiy** [brave/brave-browser#16254]
## Description 

`getNPMConfig()` [uses](https://github.com/brave/brave-browser/blob/master/lib/util.js#L9) `process.env` to get the required info about which revision of each project to check out. This fails for contributors who follow README and do not specify any environment variables.

```
$ npm run init

> brave@1.27.42 init
> node ./scripts/init.js

Performing initial checkout of brave-core
Cloning brave-core [undefined] into ~/brave-browser/src/brave...
-------------------------------------------------------------------------------
~/brave-browser/src/brave
> git clone  .

fatal: repository 'undefined' does not exist
```

## Steps to Reproduce

   1. Remove all environment varialbles
   2. `git clone git@github.com:brave/brave-browser.git`
   3. `cd brave-browser/`
   4. `npm i`
   5. `npm run init`
   6. observe that init script fails with error `fatal: repository 'undefined' does not exist`

## Actual result:

Script fails with `fatal: repository 'undefined' does not exist`.

## Expected result:
Script checks out project dependencies.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

N/A

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bridiver** [comment]
dup of https://github.com/brave/brave-browser/issues/13631
see https://github.com/brave/brave-browser/issues/13631#issuecomment-797611763
