### ISSUE TITLE
Brave does not respect Shield settings for Web-Sites

### ISSUE THREAD

**Issue by perariontaeadastra** [brave/brave-browser#16265]
## Description 

Brave ignores individual Shield settings for Web-Sites. If Shield is off for a Web-Site, ads are still being blocked if Trackers & ads blocking in Global Settings is not set to Disabled.

## Steps to Reproduce

   1. Enable Trackers & ads blocking in Global Settings. 
   2. Open Dev. Tools and load a page containing ads. 
   3.  Disable Shield for that particular Web-Site and reload.

## Actual result:

Ads are being blocked even if a particular domain has been whitelisted.
![X4JZ2CPD9J](https://user-images.githubusercontent.com/20157473/121032845-f34a4d00-c7ab-11eb-8938-dd4a997ce432.png)

## Expected result:
Should not block anything if Shield has been disabled for a particular domain, regardless of the global setting.

## Reproduces how often: 

Easily reproduced. Tested on 2 different PC.

## Brave version (brave://version info)

Brave | 1.25.70 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2009 (Build 19042.985)
JavaScript | V8&nbsp;9.1.269.28
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,WinrtGeolocationImplementation,SafetyTip --disable-features=FledgeInterestGroups,LangClientHintHeader,SignedExchangeSubresourcePrefetch,IdleDetection,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,EnableProfilePickerOnStartup,TextFragmentAnchor,TabHoverCards,InterestCohortFeaturePolicy,WebOTP,NotificationTriggers,SharingQRCodeGenerator,TrustTokens,DirectSockets,FederatedLearningOfCohorts,AutofillServerCommunication,LiveCaption,InterestCohortAPIOriginTrial,FirstPartySets,HandwritingRecognitionWebPlatformApi,SubresourceWebBundles,NetworkTimeServiceQuerying,SignedExchangePrefetchCacheForNavigations --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | aed3cac0-3f4a17df7146a73c-3f4a17dfc63a3c82-3d47f4f4

**Comment by rebron** [comment]
cc: @antonok-edm @ryanbr Can you add additional details, str?

**Comment by antonok-edm** [comment]
I don't know what site the original issue is referring to, but the same issue occurs on `https://mybroadband.co.za/news/energy/400329-koeberg-nuclear-power-station-manager-suspended.html`, in Beta and Nightly but not Release.

Either choosing "Allow all trackers and ads" for the site or disabling Brave Shields on the site will reproduce the issue, although in my experience the page may need to be refreshed once or twice.

**Comment by perariontaeadastra** [comment]
> I don't know what site the original issue is referring to, but the same issue occurs on `https://mybroadband.co.za/news/energy/400329-koeberg-nuclear-power-station-manager-suspended.html`, in Beta and Nightly but not Release.
> 
> Either choosing "Allow all trackers and ads" for the site or disabling Brave Shields on the site will reproduce the issue, although in my experience the page may need to be refreshed once or twice.

Hi. 
that happens with pretty much every web-site I test, e.g. https://www.tecmint.com/

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

<!--StartFragment-->
Brave | 1.25.72 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

<!--EndFragment-->

```
- Verified the description from the issue https://github.com/brave/brave-browser/issues/16265#issue-913602798

<details>
<summary>Case 1: Disable shield</summary>

**`1.25.70`** | **`1.25.72`**
--------------|-------------

<details>

**Comment by darkmac78** [comment]
Same happens on latest opensuse brave version.
