### ISSUE TITLE
Disable local node for iOS

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16267]
Disable local node for iOS, use only gateway there
Maybe add something like `ipfs_local_node_enabled = !ios`

**Comment by stephendonner** [comment]
Verified `PASSED` using the in-progress regression-testplan over at https://github.com/brave/brave-browser/wiki/IPFS-Features with build 

Brave | 1.27.88 Chromium: 91.0.4472.124 (Official Build) dev (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

and tested using the released-today `go-ipfs` `0.9.0` binary.

**Comment by stephendonner** [comment]
@spylogsster can you help us get a more-specific test plan which works for iOS?  I'd like to get it incorporated into https://github.com/brave/brave-browser/wiki/IPFS-Features; thanks!

**Comment by spylogsster** [comment]
afaik it is not implemented for iOS yet, in this issue just need to check that overall ipfs works on desktop and android via localnode as usual
