### ISSUE TITLE
Setting Block ads trackers to aggressive disables the setting

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16260]
## Description 
Setting Block ads trackers to aggressive disables the setting

## Steps to reproduce 

   1. Clean install 1.26.53
   2. Set Block trackers & ads to aggressive in global settings
   3. Visit a page in a new tab
   4. Check shields, Block cross-site trackers is disabled

## Actual result 

https://user-images.githubusercontent.com/17010094/121001511-478d0700-c783-11eb-8b72-2811d484e877.mp4

## Expected result
Should not disable ad blocker 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.26.53 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

### Additional information

cc: @bridiver @alexsafe

**Comment by kjozwiak** [comment]
Closing as this was fixed in `master` with https://github.com/brave/brave-core/pull/9040 and uplifted into `1.26.x` via https://github.com/brave/brave-core/pull/9049.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.63 x64 build
- Verified setting ad blocker to aggressive in global settings doesn't make it disabled in shields

https://user-images.githubusercontent.com/17010094/122350121-d698dc80-cf44-11eb-87a3-1e973c65a74d.mp4

-----------
Verification passed on Samsung Tab A with Android 10 running 1.26.63 x64 build
- Verified setting ad blocker to aggressive in global settings doesn't make it disabled in shields

https://user-images.githubusercontent.com/17010094/122350292-00520380-cf45-11eb-8150-5455483bbc6b.mp4
