### ISSUE TITLE
macos 1.25.70 Crash to desktop using Google Meet

### ISSUE THREAD

**Issue by rinchen** [brave/brave-browser#16268]
## Description 
Upon stopping a screenshare in Google Meet, Brave on macos crashes.

## Steps to Reproduce

   1. Screenshare on Google Meet
   2. Use brave for 3+ minutes
   3. Stop Screensharing (crash)

## Actual result:
Crash to desktop

## Expected result:
No crash

## Reproduces how often: 
100%

## Brave version (brave://version info)
Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (x86_64)  on macos 11.4.  This also happened on the previous release channel version of Brave.

## Version/Channel Information:
- Can you reproduce this issue with the current release? 

Yes

- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

Have not attempted with other channels

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 

Shields are down and crash still occurs.

- Does the issue resolve itself when disabling Brave Rewards? 

Rewards of off and crash still occurs.

- Is the issue reproducible on the latest version of Chrome? 

No

## Miscellaneous Information:

If I disable all extensions I cannot get any crash to happen. If I enable ANY extensions (doesn't matter which one) then I can reproduce the crash.

**Comment by rebron** [comment]
@rinchen Can you go into brave://crashes/ and send the report and include the crash report id in this issue when you get a chance?

**Comment by rinchen** [comment]
- 44270000-180d-7706-0000-000000000000
- 29bc2700-06d3-6d06-0000-000000000000
- b2712100-06d3-6d06-0000-000000000000
- be262000-06d3-6d06-0000-000000000000
- 24ae1f00-06d3-6d06-0000-000000000000
- e6ce0b00-06d3-6d06-0000-000000000000
- 4c8e0600-06d3-6d06-0000-000000000000

I have 22 of these showing in the crash section and they are all uploaded.

**Comment by dverb1647** [comment]
I have this exact problem as well, here are my ids

- 8cb74900-8ce9-8106-0000-000000000000
- 29b84900-8ce9-8106-0000-000000000000

**Comment by rinchen** [comment]
Still happens on Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (x86_64)

**Comment by iefremov** [comment]
Most probably, it was an upstream crash that should be fixed by migrating to chromium 92
https://brave.sp.backtrace.io/p/brave/explore?time=month&filters=((callstack.functions%2Ccontains%2CBaseTimerTaskInternal)%2C_deleted%3D0)&aggregations=((callstack%2Chead))&

pls reopen if happens again

**Comment by dverb1647** [comment]
@iefremov this happened again to me today 

2fdb0400-001d-ca06-0000-000000000000

It occurs only when I share an entire window. If I share a screen or tab then I'm fine.

**Comment by iefremov** [comment]
okay this a different stack trace.. reopening

**Comment by iefremov** [comment]
```
[ 00 ] 0x7fff68e1a33a
[ 01 ] 0x7fff68da1808
[ 02 ] 0x7fff68e9750b
[ 03 ] 0x7fff68ea8d27
[ 04 ] 0x7fff68e8f081
[ 05 ] 0x7fff68e8e279
[ 06 ] 0x7fff68e8dd8b
[ 07 ] mojo::core::UserMessageImpl::~UserMessageImpl()
[ 08 ] mojo::core::UserMessageImpl::~UserMessageImpl()
[ 09 ] mojo::core::ports::UserMessageEvent::~UserMessageEvent()
[ 10 ] mojo::core::Core::DestroyMessage(unsigned long)
[ 11 ] mojo::internal::MultiplexRouter::ProcessIncomingMessage(mojo::internal::MultiplexRouter::MessageWrapper*, mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*)
[ 12 ] mojo::internal::MultiplexRouter::Accept(mojo::Message*)
[ 13 ] mojo::MessageDispatcher::Accept(mojo::Message*)
[ 14 ] mojo::Connector::DispatchMessage(mojo::Message)
[ 15 ] mojo::Connector::ReadAllAvailableMessages()

```

**Comment by iefremov** [comment]
@dverb1647 can you please reproduce few times more and share crash IDs?

**Comment by dverb1647** [comment]
Happened again today dfa41200-001d-ca06-0000-000000000000 

If it helps I also have 40+ tabs open

I couldn't reproduce just on my own without anyone else in the call but I'll try again and leave the share open for a while

**Comment by sdbruder** [comment]
I error 11 every time I try to share full screen or tab but it works sharing single windows.
If I disable hardware acceleration it works.

**Comment by berters** [comment]
This happens to me all the time.

Another crash ID:

d36a1100-6f39-fa06-0000-000000000000

**Comment by leonp5** [comment]
Seems, that i face this issue too after the last Brave update (V1.39.111).

When i want to stop the screen sharing, the whole browser closes/crashes immediately.

Using MS Teams in Brave on a Linux Machine (Linux Mint 20).

Crash ID:
b9770300-2578-4408-0000-000000000000
