### ISSUE TITLE
Menu fixes for private windows with Tor

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#1627]
Unfinished business from https://github.com/brave/brave-browser/issues/1387:

- [x] Update the macOS `File` menu to include _New private window with Tor_ like the hamburger menu does.
- [x] Make the menu items match with or without Tor.  (In private windows with Tor, _New window_ and Ctrl-N should still open a new window in Tor; you can always get back to a non-private window, without Tor, in the profile menu.)

**Comment by riastradh-brave** [comment]
File menu is implemented here: src/chrome/browser/ui/cocoa/main_menu_builder.mm

But not everything from the hamburger menu needs to be echoed there; see GetShortcutsNotPresentInMainMenu in src/chrome/browser/global_keyboard_shortcuts_mac.mm.

**Comment by srirambv** [comment]
hamburger menu shows `New Private window with Tor` on master (Windows)
![image](https://user-images.githubusercontent.com/17010094/47042880-4f26ba00-d15a-11e8-8416-c04b9b9c810b.png)

**Comment by LaurenWags** [comment]
@riastradh-brave does this issue also cover adding 'New Private Window with Tor' to the 3 dots menu from Bookmarks (as mentioned in description of https://github.com/brave/brave-browser/issues/1387 ? If you'd like a different issue logged please let me know.

Screenshot from 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

![screen shot 2018-10-18 at 9 27 50 am](https://user-images.githubusercontent.com/28145373/47157951-8317f180-d2b8-11e8-86fa-1fbce1b3b403.png)

**Comment by tomlowenthal** [comment]
@simonhong Could you take care of this?

**Comment by simonhong** [comment]
@tomlowenthal yup. assigned to me.
