### ISSUE TITLE
Create a JS API for a search provider to ask permission to set itself as the default provider

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#16270]
The API should be limited to a specific set of URLs.

The API should contain 2 methods:

- `window.brave.getCanSetDefaultSearchProvider()`:
 --> Returns `Promise<bool>`: `false` if current site is the default provider or has asked > X times in current day or > Y times in total, or is in private / TOR context. Returns `true` otherwise.

- `window.brave.setIsDefaultSearchProvider()`:
 --> Returns `void`: Sets current site to be the default provider. Must be done inside user gesture. Internally checks same logic as `getCanSetDefaultSearchProvider`.

The API should be able to be disabled via feature flag / griffin.

**Comment by stephendonner** [comment]
**Verified `PASSED`** using the inline testplan with build 

Brave | 1.27.62 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

## Steps:

### Not on search.brave.com (negative test)

1. visited `https://github.com`
2. opened dev tools / console (ex: F12)
3. in console, pasted `window.brave.getCanSetDefaultSearchProvider` and hit enter
4. confirmed I got an error `Uncaught TypeError: Cannot read property "getCanSetDefaultSearchProvider" of undefined`
5. also pasted in `window.brave.setIsDefaultSearchProvider` and hit enter
6. confirmed I got the same error as in step 4

### On search.brave.com

1. visited `https://search.brave.com`
2. opened dev tools / console (ex: F12)
3. in console, pasted `window.brave.getCanSetDefaultSearchProvider` and hit enter
4. confirmed I saw a function definition
5. also pasted in `window.brave.setIsDefaultSearchProvider` and hit enter
6. confirmed I saw a function definition

github.com | search.brave.com
------------|-------------------
<img width="1082" alt="Screen Shot 2021-06-14 at 11 45 52 AM" src="https://user-images.githubusercontent.com/387249/121944720-d233b000-cd07-11eb-8d00-cc6616be3bf4.png"> | <img width="1082" alt="Screen Shot 2021-06-14 at 11 48 36 AM" src="https://user-images.githubusercontent.com/387249/121944748-d9f35480-cd07-11eb-96c5-bdfb0f02304c.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with `Brave - Nightly 1.27.62, Chromium 91.0.4472.101` on Google Pixel XL, arm64.

### Not on search.brave.com (negative test)
Steps:
1. new profile
2. launched Brave
3. loaded `brave://inspect/#devices` on desktop Brave
4. navigated to `github.com` on device
5. clicked on `inspect` on desktop Brave
6. in console, pasted window.brave.getCanSetDefaultSearchProvider and hit enter
confirmed I got an error Uncaught TypeError: Cannot read property "getCanSetDefaultSearchProvider" of undefined
also pasted in window.brave.setIsDefaultSearchProvider and hit enter
confirmed I got the same error as in step 4

<img width="880" alt="Screen Shot 2021-06-14 at 2 22 43 PM" src="https://user-images.githubusercontent.com/387249/121962153-34e37680-cd1d-11eb-84b0-3b10b32921c8.png">


### On search.brave.com

Steps:
1. new profile
2. launched Brave
3. loaded `brave://inspect/#devices` on desktop Brave
4. visited `https://search.brave.com`
5. opened dev tools / console (ex: F12)
6. in console, pasted `window.brave.getCanSetDefaultSearchProvider` and hit enter
7. confirmed I saw a function definition
8. also pasted in `window.brave.setIsDefaultSearchProvider` and hit enter
9. confirmed I saw a function definition

<img width="880" alt="Screen Shot 2021-06-14 at 2 22 12 PM" src="https://user-images.githubusercontent.com/387249/121962176-3e6cde80-cd1d-11eb-8c0b-86d5275c4063.png">
