### ISSUE TITLE
Update link to Brave Talk on new-tab page widget

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16289]
## Description 

Update link to Brave Talk on new-tab page widget

## Steps to Reproduce

   1. new profile
   2. launch Brave `nightly`
   3. open a new-tab page
   4. hover over/click on the video-camera icon
   5. look at the link

## Actual result:

Link currently goes to `https://together.brave.com/widget`

<img width="1017" alt="Screen Shot 2021-06-08 at 5 35 06 PM" src="https://user-images.githubusercontent.com/387249/121274859-41308500-c880-11eb-8da5-89bb9ec17323.png">

## Expected result:
Link should go to `https://talk.brave.com/widget`, which now exists and is a carbon copy of `together.brave.com/widget`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.48 Chromium: 91.0.4472.88&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 109e9cd038b94a631aea7d40ee3d56c1278f2597-refs/branch-heads/4472@{#1385}
OS | macOS Version 11.4 (Build 20F71)

/cc @mattmcalister @mrose17 @karenkliu @rebron @petemill

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.28.82 Chromium: 92.0.4515.93 (Official Build) nightly (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 10.15.7 (Build 19H1217)
```

Verified STR from description.

<img width="1035" alt="Screen Shot 2021-07-29 at 3 09 25 PM" src="https://user-images.githubusercontent.com/28145373/127551763-177c7502-275c-4d36-a3be-500da6faa12b.png">
