### ISSUE TITLE
Disable NTP background images switch does not disable NTP-SI setting

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#16280]
## Description 
Disable NTP background images switch `ntp_background_images::prefs::kNewTabPageShowBackgroundImage` does not disable NTP-SI setting

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing as stale.
