### ISSUE TITLE
brave attempting to download `crx` and crashes instead of installing extension

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1628]
## Description 

@jonathansampson mentioned that a user under Win 7 is having issues installing extensions. Instead of installing the extension, brave attempts to download the `.crx` file:

https://twitter.com/LittleSweetie4/status/1051933408266465285

When this situation where brave attempts to download the `.crx` file occurs, it also crashes the browser:

* https://stats.brave.com/dashboard#crash/5bc62fab72fff5001e088ba8 (dev)
* https://stats.brave.com/dashboard#crash/5bc6309172fff5001e0895a1 (dev)
* https://stats.brave.com/dashboard#crash/5bc6326c72fff5001e08aa5b (beta)

I also managed to reproduce this on Win 10 x64 but it doesn't happen as often as Win 7 right after an install. To reproduce this on Win 10, you usually need to remove the older profile, start brave again to generate the new profile and then attempt installing an extension. You'll eventually run into the issue.

## Steps to Reproduce

**Win 7 x64 STR:**

   1. install either `beta` or `dev`
   2. once brave is launched, visit https://chrome.google.com/webstore/category/extensions?hl=en
   3. search for `MetaMask` and attempt installing the extension

You'll notice that instead of installing it, it will attempt to download the `.crx` file and brave will end up crashing.

**Win 10 x64 STR:**

   1. install either `beta` or `dev` and launch brave
   2. close brave and remove `C:\Users\kjozwiak\AppData\Local\BraveSoftware` (**WARNING**: If you've installed Brave via none-admin, you'll only need to remove `C:\Users\kamil\AppData\Local\BraveSoftware\Brave-Browser-Beta\User Data`. Don't remove the entire `C:\Users\kjozwiak\AppData\Local\BraveSoftware` folder as that will remove the executables as well.)
   3. restart brave and visit https://chrome.google.com/webstore/category/extensions?hl=en
   4. search for `MetaMask` and attempt installing the extension

You'll notice that that sometimes instead of installing the extension, brave attempts to download the `crx` file and brave will end up crashing.

**Alternative Win 10 x64 STR:**

   1. install either `beta` or `dev` and launch brave
   2. create a new user via the `Manage People` feature
   3. using the new user profile, open https://chrome.google.com/webstore/category/extensions?hl=en
   4. search for `MetaMask` and attempt installing the extension

You'll notice that that sometimes instead of installing the extension, brave attempts to download the `crx` file and brave will end up crashing.

## Actual result:

**Windows 7 x64 Example:**

![extensioncrash](https://user-images.githubusercontent.com/2602313/47039443-f5ba8d00-d151-11e8-87f7-05b80bcbdb50.gif)

**Windows 10 x64 Example:**

![extensioncrashwin10](https://user-images.githubusercontent.com/2602313/47039456-fc490480-d151-11e8-8aca-aac55bfaad2c.gif)

## Expected result:

Brave shouldn't attempt to download the `crx` files and crash the browser when installing extensions.

## Reproduces how often: 

* Win 7 x64 - Reproducible 100% of the time
* Win 10 x64 - Reproducible about 70% of the time after removing the original profile

## Brave version (brave://version info)

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS |	Windows

Brave | 0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, currently reproducible under `dev` and `beta` as outlined above.

- Does it reproduce on browser-laptop? 

N/A

### Additional Information

Win 7 x64:

* 0.55.14 Chromium: 70.0.3538.54 (beta) - Reproduced
* 0.56.4 Chromium: 70.0.3538.54 (dev) - Reproduced

Win 10 x64: (Reproduced by @srirambv as well)

* 0.55.14 Chromium: 70.0.3538.54 (beta) - Reproduced
* 0.56.4 Chromium: 70.0.3538.54 (dev) - Reproduced

@LaurenWags @srirambv couldn't reproduce the issue on macOS & Linux. Right now it seems Win related.

**Comment by btlechowski** [comment]
Reproduced on my physical machine with Win7 x64 using `Win 7 x64 STR`

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows 7

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

* Verified extension download works and installs without crashing the browser
