### ISSUE TITLE
Provide a Brave Talk tooltip for `togetherPageTitle` on the new-tab page

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16288]
## Description 

Provide a Brave Talk tooltip for `togetherPageTitle` on the new-tab page

## Steps to Reproduce

   1. new profile
   2. launch Brave `nightly`
   2. open a new-tab page
   3. on the bottom, hover over the video-camera icon
   4. look at the resulting tooltip

## Actual result:

<img width="433" alt="Screen Shot 2021-06-08 at 5 30 46 PM" src="https://user-images.githubusercontent.com/387249/121274418-4c36e580-c87f-11eb-98f2-51cc50b30a7a.png">

This also shows up as an error in the console:

```
[33320:259:0607/113806.078262:ERROR:CONSOLE(219)] "Unexpected condition on chrome://newtab/: Could not find value for togetherPageTitle", source: chrome://resources/js/load_time_data.js (219)
```

## Expected result:

Should (now) say `Call with Brave Talk` or something similar, since we've renamed from `Brave Together`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.48 Chromium: 91.0.4472.88&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 109e9cd038b94a631aea7d40ee3d56c1278f2597-refs/branch-heads/4472@{#1385}
OS | macOS Version 11.4 (Build 20F71)

/cc @petemill @mrose17 @mattmcalister @karenkliu

**Comment by srirambv** [comment]
Reported internally here https://bravesoftware.slack.com/archives/C7VLGSR55/p1620313398145100

**Comment by stephendonner** [comment]
This is a duplicate of @GeetaSarvadnya's bug - sorry for not finding it earlier!

https://github.com/brave/brave-browser/issues/13513
