### ISSUE TITLE
Fix `$csp` rules being applied even when Shields are down

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#16283]
`$csp` rules, like all adblock filter rules, have some potential of causing webcompat issues. It should be possible to prevent injecting them altogether by bringing Shields down.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.25.72 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/8281
- Unable to verify test plan from https://github.com/brave/brave-browser/issues/16251#issuecomment-856500733 as file url is not supported on Android

OnePlus 6T(Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/121680022-f3e72a00-cab0-11eb-9e26-8b39226f03d3.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/121679983-e6ca3b00-cab0-11eb-9fa4-ec416a60d896.png>

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

<!--StartFragment-->
Brave | 1.25.72 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

<!--EndFragment-->

```
- Verified the test plan from https://github.com/brave/brave-core/pull/9053 
![image](https://user-images.githubusercontent.com/38657976/121688033-a387c080-cae0-11eb-8005-adae660a95ee.png)

**Comment by GeetaSarvadnya** [comment]
@antonok-edm When Shields are up and ads/trackers blocked setting is the aggressive mode I don't see `scripts violating the policy script-src 'self' 'unsafe-inline' https://hcaptcha.com *.hcaptcha.com.` in the console but the test plan says it should show script violating policy message in the console https://github.com/brave/brave-core/pull/9053 
(`This behavior should hold when Shields are up and ads/trackers blocked setting is either standard or aggressive mode. When Shields are down, or ads/trackers are allowed, the above should no longer be observed.`)

Could you review the test plan and let us know the behavior that we are seeing is correct or not?
