### ISSUE TITLE
Reduce radius  of corners on URL bar button hover shapes to match other button hovers

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#16290]
Good
![image](https://user-images.githubusercontent.com/13509546/121285853-e56ff700-c893-11eb-98b8-4c455abdb3fb.png)

Bad
![image](https://user-images.githubusercontent.com/13509546/121286135-44357080-c894-11eb-81e0-1306e4b5fd4f.png)

Good
![image](https://user-images.githubusercontent.com/13509546/121286158-4b5c7e80-c894-11eb-9c8f-fbe13d36baf4.png)

**Comment by kjozwiak** [comment]
Removing this from `1.26.x` as there's no work nor a PR associated with this. Opened issues should only be added into milestones when they're `release/blocking`.

**Comment by rebron** [comment]
Marked as QA/Yes, let's have @karenkliu QA clear this one.

**Comment by karenkliu** [comment]
lgtm 😃

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.29.12 Chromium: 92.0.4515.101 (Official Build) nightly (x86_64)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launched Brave
3. hovered over toolbar-UI elements in both `light` and `dark` modes

Confirmed that hover highlights for toolbar-UI elements are now square, not rounded.

<img width="783" alt="Screen Shot 2021-07-20 at 12 14 51 PM" src="https://user-images.githubusercontent.com/387249/126383014-a6fcef67-143b-4382-8f38-bef4f7ef100a.png"> | <img width="603" alt="Screen Shot 2021-07-20 at 12 15 29 PM" src="https://user-images.githubusercontent.com/387249/126383016-f39685ab-7efd-44ac-8cc3-849a6552d7c6.png"> | <img width="719" alt="Screen Shot 2021-07-20 at 12 17 54 PM" src="https://user-images.githubusercontent.com/387249/126383019-ad64464b-330f-48a0-92ec-486166036d7b.png"> | <img width="605" alt="Screen Shot 2021-07-20 at 12 18 07 PM" src="https://user-images.githubusercontent.com/387249/126383021-76e67b5f-e587-4012-acdb-3824c108c8fa.png">
