### ISSUE TITLE
Update `Block trackers & ads`  & `Block cross-site trackers` titles to be same similar to desktop

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16299]
## Description 
Update `Block trackers & ads`  & `Block cross-site trackers` titles to be same similar to desktop

## Steps to reproduce 

   1. Install 1.27.50 or 1.26.x build
   2. Open global shields settings, reads `Block trackers & ads`
   3. Visit a page and open shields, reads `Block cross-site trackers`

## Actual result 

![image](https://user-images.githubusercontent.com/17010094/121315375-31588580-c900-11eb-8ac2-b9b65d48eef6.png) | ![image](https://user-images.githubusercontent.com/17010094/121315363-2dc4fe80-c900-11eb-9f6d-fd9da3ea8216.png)
-- | --

## Expected result
Same naming convention similar to desktop 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.26.x & 1.27.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @karenkliu @anthonypkeane @jamesmudgett

**Comment by karenkliu** [comment]
I thought we brought Android up to desktop parity with this issue? https://github.com/brave/brave-browser/issues/7487  cc @acatarineu 

The trackers & ads toggle in Shields should now be an expand option that the user can tap to get more options.

![image](https://user-images.githubusercontent.com/2388823/121389442-4550b700-c901-11eb-8b8c-46ba9ea52cbb.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.27.105 x64 build
- Verified steps from issue description

![image](https://user-images.githubusercontent.com/17010094/125768926-c2e9a5d3-8b7d-49f3-a720-2c0bf413773a.png) | ![image](https://user-images.githubusercontent.com/17010094/125768947-d0f96c71-5824-4b47-9de5-6ec5292e5f23.png) | ![image](https://user-images.githubusercontent.com/17010094/125768964-4b990837-ed41-4c2f-bbf3-0f0bff5bcc9a.png)
-- | -- | --

-------
Verification passed on Samsung Tab A with Android 10 running 1.27.105 x64 build
- Verified steps from issue description

![image](https://user-images.githubusercontent.com/17010094/125768827-70540c29-6c58-41d9-b8bc-aee932cc8df9.png) | ![image](https://user-images.githubusercontent.com/17010094/125768878-ceffdf23-1584-4fce-a6bd-945e4ef9ebd3.png) | ![image](https://user-images.githubusercontent.com/17010094/125768851-dadaa0b9-72a3-4d2b-88b2-ff7af3b3fe91.png)
-- | -- | --
