### ISSUE TITLE
Whitelist origins accessed from main processes

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#163]
We should limit what the main app, renderer, &c, processes can connect to. We should do this by whitelist so that we don't accidentally add arbitrary domain connections from the main process like brave/browser-laptop#11727 . We should also only ever connect to secure origins from the main process — no plain HTTP. The sooner we do this, the easier it is, and the less cleanup might be needed. See brave/browser-laptop#11889 .

**Comment by bbondy** [comment]
I recommend we do this not by blocking by by DCHECK, at least to start.

**Comment by srirambv** [comment]
@bbondy any QA steps required for this or can be marked `QA/No-QA-needed` ?

**Comment by bbondy** [comment]
updated
