### ISSUE TITLE
Expose chrome.hid to Crypto Wallets extension

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#16305]
Crypto Wallets extension used to use U2F via a metamask.io page.
In Chromium 91 this changed to add a security check which we reverted temporarily in https://github.com/brave/brave-browser/issues/16204

We'd like to revert the C91 patch after this issue is released which is tracked here:
https://github.com/brave/brave-browser/issues/16205

Before we revert the C91 patch we need this to be on Release channel so that people that use Crypto Wallets with U2F won't break.

Code for using the new HID API is here:
https://github.com/brave/ethereum-remote-client/pull/243
and here: https://github.com/brave/eth-ledger-bridge-keyring/commit/6db82c15435f9ae47dadbc1fc19586552a7044eb

This issue is to track just allow the extension to use chrome.hid though.

# Test plan

- Load brave://wallet and create a wallet
- Go to chrome://extensions and enable dev mode, then click on inspect background page for the wallet extension
- type chrome.hid and make sure it's not undefined

Release notes title can be something like: Support Ledger devices in Crypto Wallets via HID transport.

**Comment by kjozwiak** [comment]
@bbondy I don't think this is working. I tried it on `macOS` using the following build and got `undefined`. Example:

```
Brave | 1.25.72 Chromium: 91.0.4472.101 (Official Build) (x86_64)
--- | ---
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.3 (Build 20E232)
```

<img width="1201" alt="Screen Shot 2021-06-11 at 1 14 08 AM" src="https://user-images.githubusercontent.com/2602313/121634504-ae940f80-ca52-11eb-9973-61b84549a553.png">

Once we get the `Win x64` executable, I can try on `Win` but so far it doesn't seem like it worked. Believe you mentioned this can be left in the release even if it doesn't work and `release-notes/exclude`.

**Comment by srirambv** [comment]
Same on Windows as well. Tried connecting to a Dapp and checked shows undefined, 
![image](https://user-images.githubusercontent.com/17010094/121683432-488ca400-cab5-11eb-8d38-b22bf6f2ac43.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)
--- | ---
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | Windows 10 OS Version 2009 (Build 19042.1023)
```

![image](https://user-images.githubusercontent.com/2602313/121745352-30774d80-cad2-11eb-81f7-df6bc778d2a6.png)

-----

Verification **PASSED** on `macOS 11.3 x64` using the following build:

```
Brave | 1.25.72 Chromium: 91.0.4472.101 (Official Build) (x86_64)
--- | ---
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.3 (Build 20E232)
```

<img width="1168" alt="Screen Shot 2021-06-11 at 4 33 33 PM" src="https://user-images.githubusercontent.com/2602313/121745900-fe1a2000-cad2-11eb-8c58-7823de01aa89.png">
