### ISSUE TITLE
Crash in BaseTimerTaskInternal

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#16301]
as reported on Twitter.

Looks like started in 90.1.25.68

https://brave.sp.backtrace.io/p/brave/explore?time=month&filters=((callstack.functions%2Ccontains%2CBaseTimerTaskInternal%3A%3ARun)%2C_deleted%3D0%2Cptype%3Dbrowser%2Cver%3E%3D%2290.1.25%22)&aggregations=((ver%2Cmin)%2C(ver%2Cdistribution)%2C(uname.sysname%2Cdistribution)%2C(callstack%2Chead))&

```
[ 00 ] base::internal::BaseTimerTaskInternal::Run()
[ 01 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*)
[ 02 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[ 03 ] invocation function for block in base::MessagePumpCFRunLoopBase::RunDelayedWorkTimer(__CFRunLoopTimer*, void*)

```

**Comment by goodov** [comment]
it's somewhere near `base::DeleteHelper<content::DesktopCaptureDevice::Core>::DoDelete(void const*)`
could it be this change? https://chromium.googlesource.com/chromium/src/+/eeba89752f9b48d801dd11948296b2ad09c4c1ff

I assume that Chromium has the same crash here https://bugs.chromium.org/p/chromium/issues/detail?id=1214089 :)

![image](https://user-images.githubusercontent.com/5928869/121359751-ff760c00-c95d-11eb-89f4-a10939e42a6a.png)

**Comment by iefremov** [comment]
there is a dupe dupe https://github.com/brave/brave-browser/issues/16301

**Comment by iefremov** [comment]
seems like it doesn't happen since chromium 92, closing for now
