### ISSUE TITLE
Brave News preference enabled before opt-in

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#16308]
## Description 
Brave News preference enabled before opt-in

## Steps to Reproduce

   1. Open NTP customise widget

## Actual result:
pref enabled

<img width="678" alt="Screenshot 2021-06-09 at 17 12 30" src="https://user-images.githubusercontent.com/1259879/121381412-9c747d00-c93d-11eb-882b-44cdb822c739.png">

## Expected result:
pref disabled by default

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by diracdeltas** [comment]
cc @fmarier @PrivacyMatters

**Comment by PrivacyMatters** [comment]
Brave News should be off until actively enabled. NO?

We should also agree how we describe 'preferences'. Brave sets a number of source defaults to ON but these are not preferences expressed by users but predetermined defaults by Brave

**Comment by tmancey** [comment]
Closing issue as working as expected

**Comment by diracdeltas** [comment]
@tmancey can you clarify? just want to make sure Brave News is actually not enabled until opt-in

**Comment by tmancey** [comment]
@diracdeltas We were using the wrong flag, and yes I can confirm Brave News is not enabled if a user has not opted-in
