### ISSUE TITLE
Site level shield setting doesn't allow sub options for Standard/Aggressive/Allow all

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16300]
## Description 
Site level ad-blocker doesn't allow sub options for Standard/Aggressive/Allow all

## Steps to reproduce 

   1. Install 1.26.53 
   2. Allows to set ads blocking to Standard/Aggressive/Allow all in global shields settings
   3. Visit a page and open shields, no such option to change via shields for a particular site

## Actual result 

![image](https://user-images.githubusercontent.com/17010094/121315375-31588580-c900-11eb-8ac2-b9b65d48eef6.png) | ![image](https://user-images.githubusercontent.com/17010094/121316461-441f8a00-c901-11eb-9ade-697441e8fa3f.png)
-- | --

## Expected result
Should allow granular options for ad blocker similar to Fingerprint and Cookies

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): AEM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.26.53 Beta &  1.27.50 Nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @karenkliu @anthonypkeane @SergeyZhukovsky

**Comment by karenkliu** [comment]
Did we not update the Shields options to match desktop as part of https://github.com/brave/brave-browser/issues/7487 ? cc @acatarineu 

The trackers & ads, cookie blocking, and fingerprinting all need to have options available in settings:

![image](https://user-images.githubusercontent.com/2388823/121390095-e5a6db80-c901-11eb-85a7-cbf98e900125.png)

**Comment by karenkliu** [comment]
@acatarineu Oops, sorry, yeah wrong Alex!

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.27.105 x64 build
- Verified site shields settings has the same options for Ads/Trackers blocked as in global settings

![image](https://user-images.githubusercontent.com/17010094/125767126-f8fc7a1c-860f-4fed-980b-686f98be7680.png) | ![image](https://user-images.githubusercontent.com/17010094/125767325-10f14636-f61e-4280-bfed-c4c88efce99c.png)
-- | --

----------
Verification passed on OnePlus 6T with Android 10 running 1.27.105 x64 build
- Verified site shields settings has the same options for Ads/Trackers blocked as in global settings

![image](https://user-images.githubusercontent.com/17010094/125767063-798939ca-3a28-491e-90d8-618ec5105227.png) | ![image](https://user-images.githubusercontent.com/17010094/125767085-6fb09efc-815f-445e-a73b-d6442fae5a91.png)
-- | --
