### ISSUE TITLE
Weird log formatting of conversion resource version

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#16303]
Follow up to https://github.com/brave/brave-browser/issues/15491

Formatting of the version is weird. Check the screenshot

## Steps to Reproduce

   1. Follow steps from `VAC_URL` from https://github.com/brave/brave-core/pull/8640

## Actual result:

Version formatting is weird
![image](https://user-images.githubusercontent.com/34715963/121356788-7d6fee00-c931-11eb-9e1b-4570b8ea59b9.png)
![image](https://user-images.githubusercontent.com/34715963/121356674-5b766b80-c931-11eb-8f45-acc8eec4ee8d.png)

## Expected result:
Version is `1`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.26.53 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Ubuntu 18.04 LTS

cc @tmancey @moritzhaller @iambrianfung  @jsecretan @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/124571402-5db2e380-de65-11eb-89ba-cd72110ca1a2.png)
