### ISSUE TITLE
Enable Crash reporting by default for Dev and Nightly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1630]
Crash reporting should be enabled by default on Dev and Beta so that we can get reports on whats causing the crashes. This should also be informed to the user on the welcome page probably on the first page as a note or as an option at the end. Preferably on the first view of the welcome page as some users might just click skip welcome tour and might not see it if its at the end.

cc: @bbondy @rebron @kjozwiak @bsclifton

**Comment by tomlowenthal** [comment]
First run flow is a great place to put the notification. It could also go on the download page next to the download button.

**Comment by tomlowenthal** [comment]
Text is now live on the download pages for dev and beta, which ✅ the privacy review. We should be fine to actually turn this on now.

**Comment by tomlowenthal** [comment]
Prompt for release builds is in brave/brave-browser#1841.

**Comment by kjozwiak** [comment]
<img width="869" alt="screen shot 2018-10-25 at 2 59 12 pm" src="https://user-images.githubusercontent.com/2602313/47523703-a61d4500-d866-11e8-903c-1528deedb6fa.png">

<img width="842" alt="screen shot 2018-10-25 at 2 59 42 pm" src="https://user-images.githubusercontent.com/2602313/47523707-a74e7200-d866-11e8-8007-eb1a080b0272.png">

@tomlowenthal should we mention `but you can turn this off if you’d like.` in the dev download page as well? You can still technically turn it off in `dev`. It might scare some users from using the `dev` channel? I'm not sure, might not be an issue. Just wanted to see what you thought 👍

**Comment by tomlowenthal** [comment]
I added it to the beta channel but not dev for two reasons. Number one, honestly was length — the dev text is already quite long. Number two was that I fully expect people using dev to go into their settings immediately after install and touch every button, switch, and knob. I very much doubt that anyone's going to compare the two pages and reach the conclusion that crash reporting can't be disabled on dev. And if folks are scared away from dev for that reason, I suspect they'd be happier on beta anyway. 🤷🏻‍♂️

**Comment by rebron** [comment]
Total number of users for dev and for beta are running the same right now.

**Comment by bbondy** [comment]
I think we'll want to run some marketing efforts to get Beta 10x the size as dev at some point.

**Comment by bsclifton** [comment]
Per https://github.com/brave/brave-browser/issues/3729 - I verified this was never actually enabled

**Comment by bsclifton** [comment]
@simonhong FYI - I just added a test plan (in case you wanted to verify it) 😄

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/54635245-02863880-4a84-11e9-9506-dd1a08f9c9a5.png)
