### ISSUE TITLE
Brave Talk/Together promo tooltip on NTP shouldn't be shown until 3 days after fresh install

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16312]
## Description 

Brave Talk/Together promo tooltip on NTP shouldn't be shown until 3 days after fresh install

## Steps to Reproduce

   1. new profile
   2. launch Brave `nightly`
   3. open a new-tab page
   4. look at the bottom-right corner

## Actual result:

The Brave Together (soon to be Brave Talk: https://github.com/brave/brave-browser/issues/16289) promo tooltip is displayed.

<img width="1631" alt="Screen Shot 2021-06-09 at 9 51 14 AM" src="https://user-images.githubusercontent.com/387249/121396494-4802da80-c908-11eb-83bf-c0801f5932ed.png">

## Expected result:

Per the design spec (https://www.figma.com/file/ycXqw8euy6z41uXrlDni6K/Desktop-Brave-Talk?node-id=1091%3A30916), for fresh installs, it **should only be shown 3 days _after_ installation**:

> Attention will also be drawn to the icon with a promo tooltip that points to it. The promo tooltip shows to:
> Existing users - as soon as the user updates Brave to a supported version. If the user does not interact with it, it shows on the new tab page for a total view time of 4 seconds spread across new tab pages.
> New users - 3 days after install. If the user does not interact with it, it shows on the new tab page for a total view time of 4 seconds spread across new tab pages.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.50 Chromium: 91.0.4472.88&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 109e9cd038b94a631aea7d40ee3d56c1278f2597-refs/branch-heads/4472@{#1385}
OS | macOS Version 11.4 (Build 20F71)

/cc @karenkliu @rebron @mattmcalister

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.28.103 Chromium: 92.0.4515.131 (Official Build) (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/9616

Confirmed prompt for Brave Talk is shown only when the OS clock is forwarded to 3 days

now | after 3 days
-----|------------
![image](https://user-images.githubusercontent.com/38657976/128506646-c2c374d6-8eb5-4a19-8bc6-053767a8741b.png) | ![image](https://user-images.githubusercontent.com/38657976/128506741-58e4e9bb-8027-49e4-98bb-58de123e6b48.png)

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` until we get Brave Talk enabled on `main` (staging) via Griffin. After it's enabled on staging, QA will be able to run through the above verification. Once we get closer to Brave Talk release date, we'll push the same change into `production`.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-variations/pull/93 was merged into `main` (Griffin staging).

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

```
- Verified the STR from the description
- ensured that the `BraveTalk` promo tooltip is shown in NTP when the OS system clock is forwarded to 3 days

now | after 3 days
-----|---------------
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/38657976/128819657-d074fd3e-db38-404f-a2a0-91066883be1d.png)
