### ISSUE TITLE
Hide DDG option from Private/Tor new tab if default search is overridden

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1632]
## Test plan
1. Fresh install of Brave (ex: move your profile folder out of the way)
2. Set your region to France or Germany
3. Launch Brave
4. Verify your default search engine is set to Qwant
5. Open a new private window and verify DDG is not shown
6. Open a new Tor window and verify DDG is not shown
7. Repeat steps 2-6 for the other country

## Description
Related to https://github.com/brave/brave-browser/issues/1607

The above issue has a fix implemented with https://github.com/brave/brave-core/pull/654

However, this is checking `navigator.language` in the JavaScript code instead of:
- checking the country (ex: if country should override search engine)
OR
- checking if the country was already overridden (when profile was created)

And exposing this to the webUI code. This could potentially be set as a new profile preference in `src/components/search_engines/template_url_prepopulate_data.cc`; for example:
- New user installs Brave
- User is in Germany
- Qwant is chosen as default search engine
- We could set a new preference: `prefs->SetInteger(prefs::kSearchOverridden, 1);`
- If search ever gets changed by the user (manually), we can set this value to 0

The new tab pages would then consider this value. If set to 1 or True, they would not display the DDG panel (matching behavior in `browser-laptop`)

**Comment by bsclifton** [comment]
cc: @mkarolin who implemented the original logic for search engine defaults with https://github.com/brave/brave-core/pull/516

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

* Verified Qwant was set as default search engine on normal tab
* Verified no DDG info on Private/Tor tab for France
* Verified no DDG info on Private/Tor tab for Germany
