### ISSUE TITLE
Launching Brave directly in incognito mode no longer works

### ISSUE THREAD

**Issue by jek6094** [brave/brave-browser#16323]
## Description 
I have previously launched Brave Dev directly in incognito mode by appending a `--incognito` parameter to the command line. Since version 1.26.x of Brave Dev, this no longer works. With Process Explorer active, I can see that a process is launched, but it quickly ends up in a suspended state, and there is no sign of a browser window during the start-up attempt. I have reported it on the [community site](https://community.brave.com/t/launch-brave-dev-in-incognito-mode-no-longer-works/251224/3) but there has been no answer, so I figured I would report it here instead.

## Steps to Reproduce
   1. Make a copy of the Brave shortcut and add `--incognito` at the end of the command line.
   2. Execute the shortcut
   3. No browser window appears, and the single remaining brave.exe process is in suspended state.

## Actual result:
The browser does not start.

## Expected result:
An incognito (aka. private) window should appear.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Version 1.26.55 Chromium: 91.0.4472.88 (Official Build) dev (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Dev and Beta are identical, so I assume yes.
- Can you reproduce this issue with the nightly channel? Have not tried.

## Other Additional Information:
OS Version: Windows 7 Professional SP1, 64-bit

## Miscellaneous Information:
Works fine in the latest Chrome version, both with `-icognito` and `--incognito` on the command line.

**Comment by jek6094** [comment]
More info: It still happens with Brave Dev Version 1.35.76 Chromium: 97.0.4692.71
However, I finally found the root cause: it is an extension that causes it, namely the DuckDuckGo Privacy Essentials extension. It doesn't matter if I allow it in private mode or not, it still causes Brave to crash. As soon as I disable the extension completely, Brave launches directly in incognito mode. In normal windows, Brave works fine with the extension enabled, so I guess it's something the extension does during launch that causes the crash.

**Comment by ryanbr** [comment]
Should this be taken up with https://github.com/duckduckgo/duckduckgo-privacy-extension @jek6094  ?

**Comment by jek6094** [comment]
I have the same extension in Opera which launches fine directly to incognito mode regardless of the "allow in private mode" extnsion setting, so it feels like a Brave specific issue at this point. Maybe someone with Brave debugging skills can take a look and see if it is an extension issue or a browser issue?

**Comment by btlechowski** [comment]
Works for me on

Brave | 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)
-- | --
Revision | b11086e62d7c1a44b0942ac5568d22a425c7ae35-refs/branch-heads/4844_74@{#5}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

I have run with `--incognito` and it has worked for me
![image](https://user-images.githubusercontent.com/34715963/160153141-c4e90b08-2b2c-4ee5-85c8-824a09093cb9.png)
![image](https://user-images.githubusercontent.com/34715963/160153113-8176f6ef-c599-4f57-8023-0093da1f29ee.png)
