### ISSUE TITLE
Missing period in Tor/.onion Settings description

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16326]
## Description 

Missing period in Tor/.onion Settings description

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `brave://settings/extensions`
   4. look at the `Automatically redirect .onion sites` section

## Actual result:

<img width="699" alt="Screen Shot 2021-06-09 at 3 45 50 PM" src="https://user-images.githubusercontent.com/387249/121439075-0b4fd700-c93a-11eb-9c64-14b2e99b7fda.png">

## Expected result:

Should have a period at the end of the descriptive sentence; additionally, the copy itself seems a bit stilted.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.26.54 Chromium: 91.0.4472.88&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | 109e9cd038b94a631aea7d40ee3d56c1278f2597-refs/branch-heads/4472@{#1385}
OS | macOS Version 11.4 (Build 20F71)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

**Comment by srl23** [comment]
Would I be able to work on this task?

**Comment by stephendonner** [comment]
> Would I be able to work on this task?

Yes, absolutely; please take a look through the code at https://github.com/brave/brave-core, find the relevant string(s) and submit a PR!  Assigning to you; please unassign if you change your mind :-)

**Comment by tonycoldashian** [comment]
I would like to work on this if that's okay.

**Comment by bsclifton** [comment]
@tonycoldashian anything open is fair game for submitting a PR. @srl23 were you able to make progress?

**Comment by srl23** [comment]
@bsclifton Sorry to say I haven't. I've been running into technical problems that I've been unable to resolve. I'm willing to let @terrycoldashian have the issue if they'd like it and I'll take a different one, as soon as things are fixed on my end.

**Comment by tonycoldashian** [comment]
Hey @bsclifton , I opened a PR with my contribution. It's my first time on open source, sorry if something is not right.

**Comment by bsclifton** [comment]
@tonycoldashian comment left in PR 😄

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.28.3 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | macOS Version 11.4 (Build 20F71)

<img width="1312" alt="Screen Shot 2021-06-17 at 3 00 27 PM" src="https://user-images.githubusercontent.com/387249/122477626-e6341780-cf7c-11eb-8c34-014c246a0eb9.png">
