### ISSUE TITLE
Typos on Brave Rewards onboarding tour slides

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16325]
## Description 
Typos on Brave Rewards onboarding tour slides

## Steps to reproduce 

   1. install Brave `nightly`
   2. tap on the BAT icon with the question mark in the URL bar
   3. tap on the `Take a quick tour` link
   4. look at the copy for the 1st and 3rd slides

## Actual result 

* The 1st slide reads `LETS TAKE A QUICK TOUR` (missing `'`)
* The 2nd slide reads `When do you receive rewards` (missing `?`)

1st slide | 3rd slide
---------|---------
![Screenshot_20210609-150911](https://user-images.githubusercontent.com/387249/121436188-f6247980-c934-11eb-823f-6fd61e83039e.png) | ![Screenshot_20210609-150922](https://user-images.githubusercontent.com/387249/121436192-f7ee3d00-c934-11eb-91ea-4b77c0c710bf.png)

## Expected results

* The 1st slide should read `LET'S TAKE A QUICK TOUR`
* The 3rd slide should read `When do you receive rewards?`

## Issue reproduces how often 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Google Pixel phone
   - Android version: 9.0
   
## Brave version
Brave `1.27.51, Chromium 91.0.4472.88`

**Comment by PrashantIndurkar** [comment]
Hello, @stephendonner , I saw the Typos,
I like to contribute to this I'm new to contribution.
I am working on this I try to solve it as fast as possible.

can anyone suggest to me where can I start, which code files I work on?

🙏 Thanks for this issue.

**Comment by stephendonner** [comment]
> Hello, @stephendonner , I saw the Typos,
> I like to contribute to this I'm new to contribute.
> I am working on this I try to solve it as fast as possible.
> 
> can anyone suggest to me where can I start, which code files I work on?
> 
> 🙏 Thanks for this issue.

Hi @PrashantIndurkar the best way to learn is to start searching through https://github.com/brave/brave-core for the relevant strings, and take it from there; thanks for working on this!  Assigning to you; please un-assign if you for whatever reason change your mind.

**Comment by TusharShahi** [comment]
If no one is assigned, can I take this up? First timer here.

**Comment by stephendonner** [comment]
> If no one is assigned, can I take this up? First timer here.

Hi @TusharShahi you sure can; welcome!  Assigning to you, please unassign if that changes, and we'll look forward to a fix hopefully!

**Comment by Shub-Gautam** [comment]
Hey @stephendonner I am a beginner in open source, I made some changes in my Brave-core repo regarding this issue can you tell me a way to test this.

**Comment by stephendonner** [comment]
@TusharShahi how's the fix going?  Please let us know if you're still working on this or not, so others can take this up, in case you're not; thanks!

**Comment by RichSlaton** [comment]
Hello, if you get any more of these, I would love to contribute.

**Comment by stephendonner** [comment]
> Hello, if you get any more of these, I would love to contribute.

@RichSlaton great; keep an eye out for unassigned ones on https://github.com/brave/brave-browser/labels/good%20first%20issue

**Comment by stephendonner** [comment]
Verified `FIXED` using Brave - `Nightly` `1.29.12, Chromium 92.0.4515.101` on a Google Pixel XL, running Android 9.

Steps:

1. installed Brave nightly
2. tapped on the BAT icon with the question mark in the URL bar
3. tapped on the `Take a quick tour` link
4. looked at the copy for the 1st and 3rd slides

Confirmed it now correctly reads `LET'S TAKE A QUICK TOUR` (1st slide) and `When do you receive rewards?` (3rd slide).

1st slide | 3rd slide
---------|---------
![Screenshot_20210720-115802](https://user-images.githubusercontent.com/387249/126380847-f234814c-44c9-4e34-a182-9d53a2448e44.png) |  ![Screenshot_20210720-115815](https://user-images.githubusercontent.com/387249/126380854-1648a7d2-76e3-4c48-86b1-c2750f083bfa.png)
