### ISSUE TITLE
Remove cid duplication for public gateways

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16339]
- Enable local node 
- Go to https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR -> see IPFS badge in address bar
- Click by badge it opens duplicated CID in url

Expected result:
- No duplication, url opened successfully

#Test Plan
- Enable local node 
- Go to https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR -> see IPFS badge in address bar
- Click by badge it opens url in new tab

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with build 

Brave | 1.27.62 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. loaded `ipns://brantly.eth`
3. clicked on `Use a local node`
4. loaded `https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`
5. clicked on the `Open using IPFS` badge in the URL bar
6. confirmed I was taken to `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/` which did **not** have another `Open using IPFS` badge

example | example
---------|----------
<img width="1792" alt="Screen Shot 2021-06-14 at 11 16 17 AM" src="https://user-images.githubusercontent.com/387249/121939877-58e58e80-cd02-11eb-98b0-fb2d98a4d69a.png"> | <img width="1792" alt="Screen Shot 2021-06-14 at 11 16 20 AM" src="https://user-images.githubusercontent.com/387249/121939886-5be07f00-cd02-11eb-926a-f325f7045235.png">
