### ISSUE TITLE
Improve Report Broken site 

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#16341]
## Description 

The report broken site works okay, but is very basic.  Some features that we should include to help with webcompat.

- Have an option for step-by-step instructions posted by the user.
- Also include User agent field, or just Brave Builds
- A way of contact or followup to the user reporting.

**Comment by ShivanKaul** [comment]
I'm going to mark this as stale, we have a number of webcompat reporter improvements planned.
