### ISSUE TITLE
Do not show badge on built-in ipfs-webui

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16340]
initial task https://github.com/brave/brave-browser/issues/15718

- Enable local node and redirect IPFS resources to configured gateway
- go to brave://ipfs -> My Node -> see IPFS badge in address bar
- Click badge -> url is opened, navigation to subpages will be failed

## Expected result

- the IPFS badge is not shown for build-in ipfs-webui

## Test plan

- Enable local node and redirect IPFS resources to configured gateway
- go to brave://ipfs -> My Node
- The IPFS badge is not visible for api pages

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with build 

Brave | 1.27.61 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. loaded `ipns://brantly.eth`
3. clicked `Use a local node`
4. went to `brave://settings/ipfs` and toggled `Redirect IPFS resources to the configured IPFS gateway` to `On`
5. loaded `brave://ipfs-internals` and clicked on `My Node`
6. confirmed there was no `Open using IPFS` badge in the URL bar for this internal API page

example | example | example
---------|---------|----------
<img width="1496" alt="Screen Shot 2021-06-14 at 11 00 02 AM" src="https://user-images.githubusercontent.com/387249/121938071-3bafc080-cd00-11eb-9fbd-2cf7db071c74.png"> | <img width="992" alt="Screen Shot 2021-06-14 at 11 03 33 AM" src="https://user-images.githubusercontent.com/387249/121938086-3eaab100-cd00-11eb-8f60-4bd43be9cc7a.png"> | <img width="1496" alt="Screen Shot 2021-06-14 at 11 00 10 AM" src="https://user-images.githubusercontent.com/387249/121938079-3d798400-cd00-11eb-83de-1706999a678c.png">
