### ISSUE TITLE
improving UX/UI for "Widevine is not installed" notification

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1634]
## Description 

I've noticed that a few folks within Brave reported that Netflix wasn't working. After a quick discussion, it's usually due to not noticing the `Widevine` notification, hence not installing `Widevine` before logging into Netflix. If we're already experiencing some confusion, I'm 100% sure users will be running into the same issue once released to a wider user base.

Because Netflix is such a popular website, I think we should look into ways of improving the notification to make it more obvious that `Widevine` isn't installed and is required.

## Steps to Reproduce

   1. launch `beta`, `dev` or `release` with a new profile that doesn't have `Widevine` installed
   2. load netflix.com

You should see a notification that says `Widevine is not installed` for a few seconds before it disappears. Because the message disappears so quickly, some folks are not aware that they need to click on the notification icon that's in the URL bar.

## Actual result:

![netflixnotification](https://user-images.githubusercontent.com/2602313/47055618-46e47400-d186-11e8-8296-d30186452e8e.gif)

## Expected result:

Maybe we should increase the timeout of the message that appears in the URL? It seems like it disappears pretty quickly and if you're not sure that you need to install `Widevine`, you might miss the small notification icon in the URL bar.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

Brave | 0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds?

Yes, currently reproducible using `beta` & `dev`.

- Does it reproduce on browser-laptop? 

N/A but the `Widevine` notification under b-l was a lot more obvious.

**Comment by srirambv** [comment]
Instead of increasing the time the notification is shown we can probably implement the notification bubble that shows up under site info similar to the Geolocation or Autoplay that way users will get an immediate UI feedback to `Run and Install Widevine` when the site is loaded.

**Comment by kjozwiak** [comment]
Going to close this as @karenkliu created https://github.com/brave/brave-browser/issues/1940 which has more activity.

**Comment by rickdev06** [comment]
this pluggin message should appear when accesing https://open.spotify.com/ had to open netflix.com to notice the installation of plugin.

**Comment by kjozwiak** [comment]
@rickdev06 we do have `spotify.com` in the whitelist of domains that will prompt users to download Widevine if it's not already installed. You can find the whitelist here:

* https://github.com/brave/brave-core/blob/43b4736fbf9580bc59f8bb6f499019b460babfad/common/shield_exceptions.cc#L125

You'll notice the following:

```
URLPattern(URLPattern::SCHEME_ALL, "https://www.spotify.com/*")
```

The reason it didn't work for you is that `https://open.spotify.com` doesn't match the pattern in the whitelist. We're working on better Widevine detection so in the future, we won't have to rely on whitelists and can cover a lot more websites.
