### ISSUE TITLE
Follow-up to revert #13190 clickable sponsored image

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#16351]
## Description 

Feedback on clickable sponsored image is showing too many mistaken clickthroughs. Need to revert #13190 to go back to only the NTPSI logo as the clickable item for the NTPSI sponsorship.

## Steps to Reproduce

   1. Click anywhere on NTP page (which has a NTPSI) that's not one of the widgets, e.g. near bookmarks toolbar.
   2. Notice the clickthrough for the NTPSI. 

## Expected result:
Clicking anywhere on the NTPSI image should not clickthrough to NTSPI destination, only when clicking the NTPSI logo.

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issue: https://github.com/brave/brave-browser/issues/13190

**Comment by stephendonner** [comment]
**Verified `PASSED`** using 

Brave | 1.26.63 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | macOS Version 11.4 (Build 20F71)

**Steps:**
1. new profile
2. launched Brave
3. opened a few new-tab pages
4. on one with a sponsored image, confirmed the following:
* sponsored image is in the bottom-left corner
* when hovered over, see a tooltip with the call to action of `Nexo - Unlock the Power of Your Crypto.  Sign up at nexo.io`
* a little box-with-arrow icon shows up on the top-right of the image
* link URL is `https://nexo.io/?utm_source=brave&utm_medium=fixed&utm_campaign=brave_nts_apr21`
* confirmed clicking on the link loads `https://nexo.io/?utm_source=brave&utm_medium=fixed&utm_campaign=brave_nts_apr21`
* confirmed no other click targets for the sponsored image
* confirmed clicking on `Customize` and toggling `Show Sponsored Images` to `Off` no longer shows them on new-tab pages
* conversely, confirmed toggling `Show Sponsored Images` back to `On` again shows them on every 4th new-tab page
* confirmed pref state for `Show Sponsored Images` (on/off) is honored when upgrading from `1.25.73` to `1.26.63`

example | example | example
---------|---------|----------
<img width="1206" alt="Screen Shot 2021-06-16 at 3 27 58 PM" src="https://user-images.githubusercontent.com/387249/122303612-a73c8e00-ceb8-11eb-9ea9-5a1799515a25.png"> | <img width="1318" alt="Screen Shot 2021-06-16 at 3 34 52 PM" src="https://user-images.githubusercontent.com/387249/122303615-a99ee800-ceb8-11eb-9478-80f6ef608929.png"> | <img width="1607" alt="Screen Shot 2021-06-16 at 3 37 54 PM" src="https://user-images.githubusercontent.com/387249/122303777-e79c0c00-ceb8-11eb-81b7-81254d29e975.png">
