### ISSUE TITLE
Custom ad notifications do not respect dark mode on Android

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16350]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/14810
Custom AD notifications don't respect dark mode

## Steps to reproduce 

   1. Clean profile 1.26.56
   2. Enable rewards
   3. Set the Dark mode/theme via settings->appearance
   4. View a custom AD

## Actual result 

**System Default**
![Screenshot_20210610-222911_Brave - Beta](https://user-images.githubusercontent.com/38657976/121570282-5b649180-ca3f-11eb-99df-c712ea84e55e.jpg)

**Dark Mode** 
![Screenshot_20210610-225018_Brave - Beta](https://user-images.githubusercontent.com/38657976/121570313-60294580-ca3f-11eb-8be9-62f46725371c.jpg)

## Expected result
Custom ads notification should respect dark mode

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): Android Tab
   - Device type (Phone, Tablet, Phablet): Android Tab 10
   - Android version: 10
   
## Brave version
1.26.56

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @tmancey

**Comment by btlechowski** [comment]
Similar issue on Linux: https://github.com/brave/brave-browser/issues/16234

**Comment by srirambv** [comment]
Verification passed on Oppo R5 with Android 11 running 1.28.99 x64 Beta Build
- Verified custom ad notification follow device/app theme

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/127994655-e50e8149-78f5-40da-b281-87b70253a9b0.png) | ![image](https://user-images.githubusercontent.com/17010094/127994687-26b218fc-8f7d-4255-a974-db0f297a4ca6.png)

-----------
Verification passed on Samsung Tab A with Android 10 running 1.28.99 x64 Beta Build
- Verified custom ad notification follow device/app theme

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/127996432-2ac9af8c-2b4c-4a1e-84a3-a468290ecb89.png) | ![image](https://user-images.githubusercontent.com/17010094/127996453-f0ada631-4574-41a4-92ba-7d9f01a07d63.png)
