### ISSUE TITLE
FTX widget - `.com` and `.us` selection is not persisted

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#16358]
After reloading NTP, it's always back to `.us`.

**Comment by petemill** [comment]
I think this is a small issue or not an issue at all. It only matters for connecting and authenticating. So if the user doesn't authenticate for that page view then they have to choose the option when they do want to connect. The API calls made when not connected are not affected, so it has no effect.

**Comment by simonhong** [comment]
@petemill Ok, got it. After connecting, it's not visible anymore :)

**Comment by rebron** [comment]
Closing as stale.
