### ISSUE TITLE
Brave not using recent Chrome version

### ISSUE THREAD

**Issue by jkarthick89** [brave/brave-browser#16369]
**Description of the issue:**
My corporate network blocks Brave browser in my Windows 10 Desktop as it is not using the recent Chromium version.
Chrome Version: Version 91.0.4472.101 (Official Build) (64-bit)
Brave Version: Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (64-bit)

**Steps to Reproduce:** 
1. Launch Brave
2. Click three lines in right top corner. Select "About Brave" displays 91.0.4472.77
3. Go to Chrome browser settings. Select "About Chrome" displays version 91.0.4472.101

**Actual Result:**
Brave browser still uses old Chrome version even after Chrome browser update

**Expected Result:**
Brave browser should uses recent Chrome version upon update

**Reproduces how often:**
Always

**Brave Version:**
Brave release - 1.25.70

**Reproducible on current live release (yes/no):**
Yes

**Comment by Tonev** [comment]
Will be fixed in the upcoming release:
https://github.com/brave/brave-browser/issues/16368

**Comment by kjozwiak** [comment]
> Will be fixed in the upcoming release:
> #16368

yup, as per @Tonev, we're planning on pushing an update today that will bump chromium to `91.0.4472.101`. The @brave/legacy_qa team is just running through a few checks before we release later in the day.
