### ISSUE TITLE
Rename Brave Together to Brave Talk in the sidebar

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16360]
## Description 

Rename Brave Together to Brave Talk in the sidebar

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. enable sidebar via `brave://flags`
   4. hover over the video-camera icon and look at the tooltip

## Actual result:

Tooltip says `Brave Together`

<img width="201" alt="Screen Shot 2021-06-11 at 12 05 28 AM" src="https://user-images.githubusercontent.com/387249/121645210-c6ff2c80-ca48-11eb-9bbf-d1e2fc0a018d.png">

## Expected result:
Tooltip says `Brave Talk`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.57 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)
JavaScript

/cc @mattmcalister @karenkliu @simonhong

**Comment by aniketartani** [comment]
It can be easily changed. @brave-browser-releases Assign me I will do it asap.

**Comment by simonhong** [comment]
> It is really easy to change it. @brave-browser-releases Assign me I will do it asap.

@aniketartani  Assigned. Thanks

**Comment by stephendonner** [comment]
Verified FIXED using

Brave | 1.28.3 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | macOS Version 11.4 (Build 20F71)

Confirmed the tooltip now reads `Brave Talk`

<img width="1201" alt="Screen Shot 2021-06-17 at 2 54 40 PM" src="https://user-images.githubusercontent.com/387249/122477161-26df6100-cf7c-11eb-971d-1183916dea92.png">
