### ISSUE TITLE
Shields is disabled on sites when its opened in a new background tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16362]
## Description 

Shields is disabled on sites when its opened in a new background tab

## Steps to Reproduce

   1. Open any GH issue
   2. Ctrl+click on any links to open in new tab
   3. Switch to the newly opened tabs in background, shields look disabled, can't click on it but shows blocked count
   4. Reload page fixes it

## Actual result:

![Screenshot-20210611050225-214x103](https://user-images.githubusercontent.com/17010094/121661493-26d2f300-ca9c-11eb-914d-52e753bcddd0.png)

## Expected result:
Shields should never be disabled unless user disables it

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.25.70 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | `1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Maybe not checked
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@iefremov also mentioned he reproduced it but not sure about steps

**Comment by GeetaSarvadnya** [comment]
Reproduced on Windows 10 x64 - `1.26.55 Chromium: 91.0.4472.88 `

**Comment by srirambv** [comment]
Console logs the following error when a tab is open in background.

```
[1972:1972:0611/082452.532794:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[1972:1972:0611/082452.533031:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Tabs cannot be edited right now (user may be dragging a tab).", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/_generated_background_page.html (0)
```

Trying to open dev tools causes shields to be come active again.

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible in `Windows 10 x64 - 1.25.72`

![image](https://user-images.githubusercontent.com/38657976/121710126-e48acf80-caf6-11eb-90e4-04cb15f8d238.png)

**Comment by Tonev** [comment]
I can only reproduce the issue after opening multiple background tabs, opening a single background tab seems not to trigger the issue. I don't know how important that is but thought I would share with you anyway.




Brave | 1.25.70 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;7 Service Pack 1 (Build 7601)
JavaScript | V8&nbsp;9.1.269.28
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PrefetchPrivacyChanges,AutoupgradeMixedContent,WinrtGeolocationImplementation,SafetyTip,LegacyTLSEnforced,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity --disable-features=AutofillServerCommunication,HandwritingRecognitionWebPlatformApi,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,FledgeInterestGroups,InterestCohortFeaturePolicy,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,InterestCohortAPIOriginTrial,FirstPartySets,SharingQRCodeGenerator,TrustTokens,DirectSockets,LiveCaption,IdleDetection,NetworkTimeServiceQuerying,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,SignedExchangeSubresourcePrefetch,NotificationTriggers,WebOTP,EnableProfilePickerOnStartup,TextFragmentAnchor,FederatedLearningOfCohorts,LangClientHintHeader,TabHoverCards --flag-switches-begin --enable-features=PrefetchPrivacyChanges,AutoupgradeMixedContent,WinrtGeolocationImplementation,SafetyTip,LegacyTLSEnforced,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,EphemeralStorage --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | aed3cac0-3f4a17df7146a73c-3f4a17dfc63a3c82-3f4a17df

**Comment by srirambv** [comment]
Just a note, this also happens when launching the browser fresh. Sometimes happens with inactive tabs becoming active upon launch

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.27.63 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. loaded this issue: `https://github.com/brave/brave-browser/issues/16362`
3. context-clicked on the PR link and chose `Open Link in New Tab`
4. confirmed the URL loaded
5. confirmed Shields were active and clickable

example | example
---------|---------
<img width="1472" alt="Screen Shot 2021-06-14 at 5 00 18 PM" src="https://user-images.githubusercontent.com/387249/121973893-1f794700-cd33-11eb-9121-f45743a59bdf.png"> | <img width="1591" alt="Screen Shot 2021-06-14 at 5 00 27 PM" src="https://user-images.githubusercontent.com/387249/121973898-21430a80-cd33-11eb-9a26-979cbc46fa60.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
<!--StartFragment-->
Brave | 1.25.73 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.1052)

<!--EndFragment-->

```
- Verified the STR from https://github.com/brave/brave-browser/issues/16362#issue-918469761

**Comment by oviniciusfeitosa** [comment]
Same problem here. 

```
Ubuntu 22.04
Brave Browser 101.1.38.109 
```
