### ISSUE TITLE
Fix check for passphrase to seed derivation in BatClient::continueRecover

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#1636]
## Description 
`written` needs to be dereferenced on https://github.com/brave-intl/bat-native-ledger/blob/f8bb01713bfb05b69aab1720f5cca460303343f3/src/bat_client.cc#L1002

Otherwise, the check is guaranteed to succeed and wallet recovery will continue regardless of whether the derivation of the wallet seed from the provided passphrase succeeded.

**Comment by srirambv** [comment]
@jasonrsadler any QA steps for this?

**Comment by jasonrsadler** [comment]
@bbondy Can you verify no-QA?

**Comment by bbondy** [comment]
can't we QA this with wrong seed phrase or something like that?

**Comment by jasonrsadler** [comment]
Sure. @srirambv, use test plan from https://github.com/brave/brave-core/pull/530
