### ISSUE TITLE
Events happening at the same time are logged in reverse order in Rewards internals

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#16376]
## Description 
We're listing `Logged at` chronologically from bottom to top, like:
```
06/11/2021, 03:07:36 PM
06/11/2021, 03:03:19 PM
```
but we're listing the entries logged at the same time from top to bottom:
```
06/11/2021, 03:07:36 PM    wallet_connected        uphold/962ef
06/11/2021, 03:07:36 PM    fetch_old_balance       0
06/11/2021, 03:07:36 PM    device_limit_reached    uphold/962ef
06/11/2021, 03:07:36 PM    wallet_disconnected     uphold/962ef
```

## Steps to Reproduce

   1. go to `brave://rewards-internals`
   2. click `Event logs`
   3. search for a group of events happening at the same time

## Actual result:
E.g.:
```
...
06/11/2021, 03:07:36 PM    wallet_connected        uphold/962ef
06/11/2021, 03:07:36 PM    fetch_old_balance       0
06/11/2021, 03:07:36 PM    device_limit_reached    uphold/962ef
06/11/2021, 03:07:36 PM    wallet_disconnected     uphold/962ef
06/11/2021, 03:03:19 PM    wallet_connected        uphold/962ef
06/11/2021, 03:03:19 PM    fetch_old_balance       0
06/11/2021, 03:03:19 PM    device_limit_reached    uphold/962ef
06/11/2021, 03:03:19 PM    wallet_disconnected     uphold/962ef
...
```

## Expected result:
E.g.:
```
...
06/11/2021, 03:07:36 PM    wallet_disconnected     uphold/962ef
06/11/2021, 03:07:36 PM    device_limit_reached    uphold/962ef
06/11/2021, 03:07:36 PM    fetch_old_balance       0
06/11/2021, 03:07:36 PM    wallet_connected        uphold/962ef
06/11/2021, 03:03:19 PM    wallet_disconnected     uphold/962ef
06/11/2021, 03:03:19 PM    device_limit_reached    uphold/962ef
06/11/2021, 03:03:19 PM    fetch_old_balance       0
06/11/2021, 03:03:19 PM    wallet_connected        uphold/962ef
...
```

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
E.g.:
```
Brave    1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)
Revision af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS       Windows 10 OS Version 2009 (Build 19043.1052)
```
But any version should suffice.

## Version/Channel Information:

- Can you reproduce this issue with the current release? ✔️ 
- Can you reproduce this issue with the beta channel? ✔️ 
- Can you reproduce this issue with the nightly channel? ✔️ 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ❌ 
- Does the issue resolve itself when disabling Brave Rewards? ❌ 
- Is the issue reproducible on the latest version of Chrome? ❌

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.43.61 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 12.5 (Build 21G72)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave `1.43.74, Chromium 104.0.5112.102` on a `Google Pixel XL` running `Android 9`.

#### Confirmed with the `wallet_verified` and `wallet_status_change` events, which are inverted in `release` vs. the correct `1.43.74`:

release | 1.43.74
--------|--------
![Screenshot_20220818-130128](https://user-images.githubusercontent.com/387249/185485051-66a1040e-c211-4f1f-820a-6c12633d8216.png) | ![Screenshot_20220818-130428](https://user-images.githubusercontent.com/387249/185485054-4acb15cb-23bb-4e25-a658-9ae16a8d15ec.png)
