### ISSUE TITLE
All saved logins deleted, new logins are only saved temporarily before being deleted as well

### ISSUE THREAD

**Issue by rdgh8** [brave/brave-browser#16377]
## Description 

Just over 2 weeks ago Brave (Beta) completely deleted all of my saved logins. I'm not sure what triggered it or how to reproduce it, or if it happened after an update. Immediately after I noticed, I also noticed that Brave was and still is unable to store any new logins. Once I save a username and password using Brave's password manager, it will show up initially but delete itself after some short period of time, within a few hours. 

## Steps to Reproduce

   1.  Go to website
   2. Login
   3. Save login using prompt
   4. Check login in Settings -> Additional Settings -> Autofill -> Passwords
   5. Close the settings, do something else on computer for a few hours
   6. Check back and notice that the passwords are empty 
Not sure how to reproduce the initial deletion that cleared all of my logins. 

## Actual result:

![Screenshot from 2021-06-11 08-41-53](https://user-images.githubusercontent.com/66289396/121687938-ea4dca00-ca90-11eb-968a-2a864122f4b5.png)

## Expected result:

Passwords are saved correctly

## Reproduces how often: 

Hours after a password is saved. 

## Brave version (brave://version info)

Brave | 1.26.57 Chromium: 91.0.4472.88&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 109e9cd038b94a631aea7d40ee3d56c1278f2597-refs/branch-heads/4472@{#1385}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
It has only occurred to me on this current instance of Brave Beta, starting from just over 2 weeks ago. I just tried today and have been unable to replicate on any other channel so it may be specific to my account. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
Have not tried Chrome, it still occurs with Shields and Rewards turned off.

**Comment by ikariwing** [comment]
I also encountered this in recent versions for 2~3 weeks, it seems like the issue was eased after my last updated but I realized that it actually didn't.

Now I am forced to login my multiple google accounts (and other accounts) almost everyday.

My Brave version = `Version 1.25.73 Chromium: 91.0.4472.106 (Official Build) (x86_64)`
OS version = MacOS Big Sur 11.2.3 (20D91)

@rdgh8  thank you for reporting this 👍 

c.c. @yrliou 😛  thanks for your info!

**Comment by ikariwing** [comment]
This issue might be related to https://github.com/brave/brave-browser/issues/14793

**Comment by rebron** [comment]
@rdgh8 Are you still seeing this issue. It was related to #14793 and believed to be an upstream issue that was fixed a while back. Can you update to Brave 1.35.103 and let us know if still running into this.

**Comment by rdgh8** [comment]
Seems to have been fixed sometime ago.
