### ISSUE TITLE
The Safe Browsing client-side phishing detection model is downloaded

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16379]
At first run, Brave browsers fetch the following file from Google (via Brave proxy):
```
   GET https://static.brave.com/safebrowsing/csd/client_model_v5_variation_6.pb HTTP/2.0
       ← 200 application/octet-stream 80.13k 159ms
```

I'm pretty sure that feature is disabled in Brave and so this is unnecessary.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.56 Chromium: 93.0.4577.58 (Official Build) beta (x86_64)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:
1. new profile
2. launched Charles Proxy
3. launched Brave
4. ran through I ran through all of the Webpage and Desktop Download tests on `https://testsafebrowsing.appspot.com/` successfully.
5. checked Charles Proxy for both `imefjhfbkmcmebodilednhmaccmincoa` and any calls to `static.brave.com`.

Confirmed:
1. no requests from `imefjhfbkmcmebodilednhmaccmincoa`
2. no calls to `static.brave.com`
3. the tests worked identically to my run using `1.28.106`

<img width="1611" alt="Screen Shot 2021-08-30 at 2 52 48 PM" src="https://user-images.githubusercontent.com/387249/131411528-92c2e0c8-2f4a-4526-8cbc-ab9cbc7be9cf.png">
