### ISSUE TITLE
Do not overwrite or generate new Wallet Payment ID when wallet info cannot be decrypted

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16373]
## Description

One effect of the current logic is that if the wallet info cannot be decrypted (e.g., OS encryption permissions are not granted to the Brave app), then the Rewards engine may try to generate a new Wallet Payment ID, which may overwrite the previous one. 

## Solution

1. Prevent this from happening.
2. Have proper error handling and messaging to the user in case wallet info cannot be decrypted.

### Notes

Related to: 

* https://github.com/brave/brave-browser/issues/15214
* https://github.com/brave/brave-browser/issues/15002

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan at https://github.com/brave/brave-core/pull/9504 with 


Brave | 1.29.46 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5.1 (Build 20G80)


Steps:

1. Opened the browser with a clean profile on staging.
2. Opened the `brave://rewards` panel and clicked "Start using Brave Rewards" to generate a rewards wallet.
3. Accepted the 30.000 BAT UGP grant.
4. Closed the browser.
5. Opened the `Keychain Access` app and removed `Brave Browser Nightly.app` from the `Brave Safe Storage` list.
6. Started the browser and denied the app's request to access the system password store.
7. Navigated to `brave://rewards`.
8. Toggled `Ads` to `off`.
9. Navigated to `brave://rewards-internals` and viewed the logs.
10. Verified a "Decryption failed" message was logged.
11. Restarted the browser, and granted access to the system password store.
12. Confirmed that Rewards tipping and auto-contributions were working.

example | example | example | example | example | example | example | example | example
---------|----------|---------|----------|---------|----------|----------|---------|---------
<img width="989" alt="Screen Shot 2021-08-03 at 10 32 26 AM" src="https://user-images.githubusercontent.com/387249/128062222-f70b4ad0-5f6f-4104-8c44-5b05b18205c6.png"> | <img width="646" alt="Screen Shot 2021-08-03 at 10 33 28 AM" src="https://user-images.githubusercontent.com/387249/128062228-37fa5f0e-e5e8-4a7e-89df-9043c28c06ca.png"> | <img width="546" alt="Screen Shot 2021-08-03 at 10 33 50 AM" src="https://user-images.githubusercontent.com/387249/128062282-17387dd5-631e-45e6-b2bd-2be06312e94c.png"> | <img width="1312" alt="Screen Shot 2021-08-03 at 10 34 39 AM" src="https://user-images.githubusercontent.com/387249/128062378-6dc97631-01f4-4de4-a996-29e6b37a30e4.png"> | <img width="1312" alt="Screen Shot 2021-08-03 at 10 35 10 AM" src="https://user-images.githubusercontent.com/387249/128062379-68f0fdec-eac8-46e5-be42-43274029da02.png"> | <img width="546" alt="Screen Shot 2021-08-03 at 10 35 48 AM" src="https://user-images.githubusercontent.com/387249/128062380-3bab5405-96ae-43dd-888f-296b7e7b8f84.png"> | <img width="1312" alt="Screen Shot 2021-08-03 at 10 36 26 AM" src="https://user-images.githubusercontent.com/387249/128062381-cfb0b3e0-09be-4f16-9c13-35dba8468945.png"> | <img width="1574" alt="Screen Shot 2021-08-03 at 10 39 01 AM" src="https://user-images.githubusercontent.com/387249/128062383-938b87c6-eb0a-4562-a757-669200fcb0a9.png"> | <img width="1574" alt="Screen Shot 2021-08-03 at 10 39 31 AM" src="https://user-images.githubusercontent.com/387249/128062387-f303626b-e07e-4614-94c4-945a8d035355.png">

**Comment by GeetaSarvadnya** [comment]
@zenparsing Is there any way to test this issue on Windows as the keychain concept is not there in windows.

**Comment by zenparsing** [comment]
@GeetaSarvadnya I haven't been able to discover how to manipulate user-based encryption keys on Windows, perhaps @emerick might know? Otherwise, it should be sufficient to follow the "Rewards wallet data is corrupted" scenario, since that will test the same code paths.

**Comment by GeetaSarvadnya** [comment]
@zenparsing To test the "Rewards wallet data is corrupted" scenario, I would need corrupted `brave.rewards.wallets.brave` preferences profile

**Comment by GeetaSarvadnya** [comment]
@zenparsing @emerick If there are no specific steps to verify the issue on Windows, probably we can add macOS and Linux label only.

**Comment by kjozwiak** [comment]
So `Win` does have a built-in password store in `C:\Windows\System32\Config\` via the `SAM` file but encrypted using the `system` file. You'll need to either download a tool that decrypts the `SAM` file or boot into a Linux distro in the same machine and extract the hashes from `SAM`. I'm not sure if it's even possible to edit/replace the `SAM` file on the system. Assuming editing/replacing the `SAM` file is going to case a lot of issues. QA will only check the corrupted preference file case. CCing @zenparsing
