### ISSUE TITLE
Usage ping opt out doesn't work

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16378]
We have a settings (default OFF) which claims to control both usage pings and crash reports:
![Screenshot from 2021-06-11 19-13-42](https://user-images.githubusercontent.com/167821/121762185-375d8a80-cae9-11eb-8598-b71495608be6.png)

However, requests to the stats endpoint (`laptop-updates.brave.com`) still take place despite this setting being turned off.

We should:
- Ensure crash report setting only applies to crash reports.

Related issues:
- Update the label to make it clear that this toggle is just for crash reports (and update screenshot on our [support page](https://support.brave.com/hc/en-us/articles/360017905872-How-do-I-enable-or-disable-automatic-crash-reporting-)) #16470
- Add a separate opt out for usage pings #16583

**Comment by fmarier** [comment]
There is also an issue open around improving the presentation of our various opt-outs in settings: https://github.com/brave/brave-browser/issues/14269

**Comment by karenkliu** [comment]
(Refer to #14269 for the updated crash reporting text)

**Comment by keur** [comment]
https://github.com/brave/brave-browser/issues/16583 for creating the pref in local state

**Comment by rebron** [comment]
@keur Is this resolved with this fix? https://github.com/brave/brave-browser/issues/16583

**Comment by keur** [comment]
Yep, and this is the PR. Closing https://github.com/brave/brave-core/pull/9229
