### ISSUE TITLE
Why did Laptop with HiDPI screen get removed?

### ISSUE THREAD

**Issue by Dr-Sauce** [brave/brave-browser#16389]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:
It used to be like this.
![20210612_231043](https://user-images.githubusercontent.com/82555878/121778855-d959a180-cbd3-11eb-8ecd-afd98df712e2.png)

But after the update **Laptop with HiDPI screen** and **Laptop with MDPI screen** has disappeared.
![20210612_232252](https://user-images.githubusercontent.com/82555878/121779139-2ee27e00-cbd5-11eb-8ad3-95e001341c88.png)

It's a feature I used all the time.  **Laptop with HiDPI screen** and **Laptop with MDPI screen** needs to return!!

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing as wontfix. This was removed as part of chromium update but the specs for laptops can be found here https://gist.github.com/TrevorJTClarke/27896c197a34e597a8a6 and can be added as custom device.
