### ISSUE TITLE
"one time tip" and "One-time tip" should read "one-time tip" and "One-time tip" in tip-successful message

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16387]
## Description 

"One time tip" should read "one-time tip" in various tip panels

## Steps to Reproduce

   1. new profile
   2. launch Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --rewards=staging=true,reconcile_interval=5  --brave-ads-debug`
   3. open a new tab
   4. click on `Start using Rewards`
   5. load `laurenwags.github.io`
   6. make a one-time tip

## Actual result:

<img width="1312" alt="Screen Shot 2021-06-12 at 3 31 37 AM" src="https://user-images.githubusercontent.com/387249/121773195-1ae44100-cb2f-11eb-96ff-48a8393aeee8.png">

<img width="1312" alt="Screen Shot 2021-06-12 at 3 53 55 AM" src="https://user-images.githubusercontent.com/387249/121773619-ec1b9a00-cb31-11eb-99e9-d50c81db4d0d.png">

## Expected result:

Should read one-time tip as it does in other `brave://rewards` UI, as it's a compound modifier.

<img width="1312" alt="Screen Shot 2021-06-12 at 3 31 16 AM" src="https://user-images.githubusercontent.com/387249/121773205-2e8fa780-cb2f-11eb-9026-315ef993b0b6.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.56 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.5 (Build 20G5033c)

**Comment by TusharShahi** [comment]
If no one has this, I would like to try this. First-timer here.

**Comment by rbrishabh** [comment]
I can help with this!

**Comment by stephendonner** [comment]
Verified `FIXED` using the inline testplan with 


Brave | 1.28.31 Chromium: 91.0.4472.124 (Official Build) nightly (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --rewards=staging=true,reconcile_interval=5 --brave-ads-debug`
3. open a new tab
4. click on `Start using Rewards`
5. clicked `OK` and solved the CAPTCHA to accept the UGP grant on staging
6. loaded `laurenwags.github.io`, `duckduckgo.com`
7. clicked on the BAT icon in the URL bar
8. clicked on `Send a tip`
9. ensured `One-time tip` was selected and spelled correctly
10. clicked `Send tip`

example | example
--------|----------
<img width="1490" alt="Screen Shot 2021-06-25 at 10 02 35 AM" src="https://user-images.githubusercontent.com/387249/123461529-0fb4fa80-d59e-11eb-8a18-4df78e961d08.png"> | <img width="1312" alt="Screen Shot 2021-06-25 at 10 10 21 AM" src="https://user-images.githubusercontent.com/387249/123461534-104d9100-d59e-11eb-81ee-d653566ea235.png">
