### ISSUE TITLE
Turning on media router breaks everything

### ISSUE THREAD

**Issue by deXterbed** [brave/brave-browser#16382]
## Description 

Turning on media router breaks every open/new tab

## Steps to Reproduce

   1. Turn on media router in settings
   2. Relaunch

## Expected result:
Turning on media router should enable cast, not break the tabs

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.25.72 Chromium: 91.0.4472.101 (Official Build) (x86_64)
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS: macOS Version 10.15.7 (Build 19H1217)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@deXterbed This is an issue we weren't able to reproduce with 1.25.72. Our latest now is 1.31.91. Are you still seeing this issue with that media router setting?

**Comment by rebron** [comment]
Closing as stale. @deXterbed Let us know if you're still experiencing this issue with 1.32.106 and we can reopen.
