### ISSUE TITLE
Decrease height of download bar by showing source on hover

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1638]
## Description 
Users are complaining about the download bar being too tall. Download may be integrated into sidebar in the future, but do a short term quick fix by only showing the source on hover.

Original description: 
>Visually download bar looks really big and is a distraction on UI. This was a problem on muon as well and users complained about it as well. With added URL info on downloads the size has doubled from normal. Definitely needs a redesign for download bar

## Steps to Reproduce

   1. Install 0.55.14
   2. Download a file
   3. Regret downloading file which makes you look at that huge download bar

## Actual result:
While downloading

![image](https://user-images.githubusercontent.com/17010094/47056876-58c91580-d18c-11e8-8721-47673ec5cd7b.png)
After download complete
![image](https://user-images.githubusercontent.com/17010094/47056891-5e266000-d18c-11e8-9cf2-01e07cc26a13.png)

## Expected result:
Do not show the source by default: 
![image](https://user-images.githubusercontent.com/2388823/107079961-754a4b00-67a5-11eb-848d-29a68e47b4ce.png)

Show the only source on hover (source replaces the title):
![image](https://user-images.githubusercontent.com/2388823/107080122-ad518e00-67a5-11eb-8fe8-82a815d024bb.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

All versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

@bradleyrichter @rossmoody @karenkliu  @bbondy @brave/legacy_qa

**Comment by bbondy** [comment]
note that this was a blocker from security to have this information, so we don't want to remove it with a new design. cc @diracdeltas

**Comment by bradleyrichter** [comment]
needs a UX review to see if there is a solution that makes everyone happy.

**Comment by diracdeltas** [comment]
maybe show the origin and/or the progress text on hover instead of in the area?

**Comment by srirambv** [comment]
+1 on hover behaviour. Honestly its too distracting when there are multiple downloads going on

**Comment by jonathansampson** [comment]
I received [a ping](https://twitter.com/TomasSinkunas/status/1120054843417210880) from a user via Twitter today asking that we consider UI changes. This user also encourages us to consider Safari's approach.

**Comment by Brave-Matt** [comment]
+1 from reddit:
https://www.reddit.com/r/brave_browser/comments/bkzz5u/customizing_the_browser_to_fix_a_few_glaring/

**Comment by Brave-Matt** [comment]
+1 from reddit:
https://www.reddit.com/r/brave_browser/comments/bljeqj/the_download_bar_seems_really_large_is_there_a/

**Comment by Neo23x0** [comment]
Any news on this?

**Comment by fakestatic** [comment]
I'd love to know the current status of this.

**Comment by voiceofvraja** [comment]
This is still not solved

**Comment by aemmadi** [comment]
Would love an update on the status of this issue, been on the backlog for a while now. @Brave-Matt Thanks!

**Comment by FUNKYBAT** [comment]
Any update on this?

**Comment by Neo23x0** [comment]
Why do developers include the URL in the download info? 
As a user, it doesn't give me useful information. Typically a user knows on which website or on which server he/she has started the download. It's dispensable information. This big download bar is an annoyance, especially on displays with a lower resolution.

**Comment by srirambv** [comment]
+1 from @dave90dave via #13848 

cc: @rebron we should increase the priority on this as this is getting a lot of attention. Also with Edge moving into FF style download button we should make this feature better

cc: @bbondy @karenkliu

**Comment by srirambv** [comment]
1 from @oxdead  via #13857

> It could be much more practical to have an option to show Download button at top right corner where extensions and options menu live, instead of showing whole Download Toolbar below.
> 
> So if someone likes toolbar they can have toolbar by default, but if someone, like me wants to have just small button instead of whole toolbar, they can go to options and switch option: "Show download button instead of download toolbar".
> 
> Download Toolbar is very big and everytime i download files, i click below to hide that toolbar.
> Everytime i need to look for downloaded files after 5-60 minutes, i need to go through a loophole OptionsMenu->Downloads and then handle a downloaded file in separate tab. It's inconvenient, slow and annoying process.
> 
> It's much faster and more convenient just to click a button at the top right corner of browser, (right before Options menu button) and manage downloaded files in popped up tooltip.
> 
> Benefits:
> -No need for big toolbars obstructing a site view
> -No need for useless clicks to hide toolbar everytime you downloaded a file
> -No need to go through menus and separate windows just to handle a downloaded file later.

**Comment by srirambv** [comment]
+1 from @Carandiru0 via #14852

> When a download is started, visibly the user see's a item popup in the [status bar] area of the canvas. A suggested improvement would be to rethink gui presentation for this particular dated item.
> Show the current bitrate (ie. Mbps) as the first item.
> Show the end of the url for location as the second item.
> Shade the background as to indicate the progress of the file download.
> Simple yet effective gui improvement with minimal change. (in regards to code changes needed to support improvement).
>

**Comment by vrindavan** [comment]
+1

**Comment by vrindavan** [comment]
Hope this comes soon :/

**Comment by JFMugen** [comment]
To be honest that is both surprising and annoying that they couldn't solve this after 3 years.

**Comment by vrindavan** [comment]
Don't know other than updating chromium, what's their plan 😂

**Comment by Brave-Matt** [comment]
@rebron can we take a look at this and see if this is something to be adjusted? It's minor (even aesthetically) but has been brought up consistently since switching to Chromium and is certainly worth considering an adjustment if not a redesign.

**Comment by JFMugen** [comment]
Yeah, PLEASE.

**Comment by y4rr** [comment]
The big irony is that there's screen space to show both file name and its url three times one after another in a row, but nobody seems to notice.

Why do file name and file url have to be trimmed to the length when both of them are not meaningful? @rebron

**Comment by JFMugen** [comment]
@bsclifton Yeah, I have been following it since he started to work on it :D 

Thank you very much @nullhook :)

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.29.45 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 12.0 (Build 21A5294g)

Steps:
1. new profile
2. launched Brave
3. context-clicked on the file-size buttons and downloaded files from `https://www.leaseweb.com/platform/network`
4. clicked on `keep` after getting `This file can't be downloaded securely` message
5. did `cancel`, `pause`, `resume`, `discard` and `file-downloaded` scenarios
6. tested in both `Light` and `Dark` colors
7. confirmed the origin URL shows up only on hover

light

<img width="1664" alt="Screen Shot 2021-08-02 at 3 30 03 PM" src="https://user-images.githubusercontent.com/387249/127931989-16a57a58-54f0-4aae-863d-116607a9be46.png">

dark

<img width="1664" alt="Screen Shot 2021-08-02 at 3 29 48 PM" src="https://user-images.githubusercontent.com/387249/127931955-90242900-9a1f-4bbd-9522-69ec3963a177.png">


height comparison (bottom) to current `1.27.109` release (top)

<img width="1493" alt="Screen Shot 2021-08-02 at 3 18 13 PM" src="https://user-images.githubusercontent.com/387249/127932130-f6fb24be-33a1-476b-9e61-23666edc44ff.png">
