### ISSUE TITLE
Rewards-related custom headers are sent by clients who have not opted into Rewards

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16381]
The [custom headers](https://github.com/brave/brave-browser/wiki/Custom-Headers) mechanism is currently used for three partners, at least one of which is strictly related to Ads.

This means that users who haven't opted into Rewards are fetching https://laptop-updates.brave.com/promo/custom-headers unnecessarily and sending the `X-Partner-Header` if they visit the partner site.

Not a privacy issue since the header is the same for all Brave users, but it's unexpected.

**Comment by Miyayes** [comment]
@fmarier Do you know if this still an issue? Lots has changed since.

**Comment by fmarier** [comment]
This was done in 1.28.x: https://github.com/brave/brave-core/pull/9157
