### ISSUE TITLE
EGL backend will enable hardware acceleration BUT the entire browser will start lagging and video playback does not smooth

### ISSUE THREAD

**Issue by minhduc66532** [brave/brave-browser#16385]
## Description 

Run brave with `brave --enable-features=VaapiVideoDecoder --use-gl=egl` will enable hardware decoding BUT entire browser will start lagging (stuttering scrolling, stuttering animation, almost half the number of frames dropped). IF I use only `brave --use-gl=egl` the same problem happen, so egl is the problem

## Steps to Reproduce

   1. Open the terminal and run `brave --use-gl=egl`
   2. Lots of stuttering
   3. 

## Actual result:

Lots of stuttering

## Expected result:
Smooth browser experience and smooth youtube video play back

## Reproduces how often: 

Always

## Brave version (brave://version info)

> Brave	1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)
> Revision	af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
> OS	Linux
> JavaScript	V8 9.1.269.36
> User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
> Command Line	/usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,PrefetchPrivacyChanges,SafetyTip,AutoupgradeMixedContent,PasswordImport,ReducedReferrerGranularity,LegacyTLSEnforced,DnsOverHttps --disable-features=SignedExchangePrefetchCacheForNavigations,DirectSockets,TrustTokens,IdleDetection,FledgeInterestGroups,InterestCohortFeaturePolicy,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,HandwritingRecognitionWebPlatformApi,SignedExchangeSubresourcePrefetch,NetworkTimeServiceQuerying,SubresourceWebBundles,LiveCaption,AutofillServerCommunication,FederatedLearningOfCohorts,InterestCohortAPIOriginTrial,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,FirstPartySets,TabHoverCards,TextFragmentAnchor,EnableProfilePickerOnStartup,SharingQRCodeGenerator,WebOTP,NotificationTriggers,LangClientHintHeader --flag-switches-begin --enable-gpu-rasterization --enable-zero-copy --ignore-gpu-blocklist --flag-switches-end
> Executable Path	/usr/lib/brave-bin/brave
> Profile Path	/home/minhduc/.config/BraveSoftware/Brave-Browser/Default
> Variations	aed3cac0-3f4a17df
> 7146a73c-3f4a17df
> c63a3c82-3f4a17df

**Comment by ukbeast** [comment]
You will need to have vulkan support and drivers installed with vulkan enabled under brave://flags/.

This obviously will use vulkan, however video acceleration is broken (white video on youtube)
But sites and videos are smoother than default brave flags.

**Comment by minhduc66532** [comment]
Thank you for the answer
