### ISSUE TITLE
(Android) Brave News on the New Tab Page

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#16398]
## Description
Desktop launched the Brave News (originally Brave Today) feature with https://github.com/brave/brave-core/pull/6192 (fixing https://github.com/brave/brave-browser/issues/12574)

There were several follow ups after that:
- [Add Brave Today URLs to network-audit allowlist](https://github.com/brave/brave-core/pull/7092)
- [Brave Today: popup menu for publisher name which disables publisher](https://github.com/brave/brave-core/pull/7104)
- [Brave Today: dismiss intro card if it has been viewed for 4 seconds](https://github.com/brave/brave-core/pull/7111)
- [Brave Today: p3a and some small fixes](https://github.com/brave/brave-core/pull/7245)
- [Brave Today: promoted content](https://github.com/brave/brave-core/pull/7290)
- [Brave Today: move from staging to production URLs](https://github.com/brave/brave-core/pull/7300)
- [Brave Today: do not limit history search to the default of 100 items](https://github.com/brave/brave-core/pull/7335)
- [Brave Today: optimize fetching](https://github.com/brave/brave-core/pull/7353)
- [Today: fix p3a key mismatch](https://github.com/brave/brave-core/pull/7392)
- [Brave Today: remove hint (scroll down arrow) animation](https://github.com/brave/brave-core/pull/7433)
- [Brave Today: japanese content feed](https://github.com/brave/brave-core/pull/7676)

This issue is intended to track the Android implementation which is now in progress 😄

**Comment by SoyDanielRomero** [comment]
Please keep it going until you succeed, this feature is really needed in the community

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using Brave `1.34.68, Chromium 97.0.4692.56` on a Google Pixel XL, running Android 9.0.

* ensured that Brave News isn't available/visible under NTP (attempt to scroll down and ensure it's not possible)
* ensured that NTP loads without any issues
* ensured that tapping on the image attribution links at the bottom correctly loads within the same tab
* ensured that you can switch between the `Top Sites` & `Privacy Stats` widget stacks without any issues
* ensured that `Brave News` isn't being displayed when tapping on the `Hamburger Menu`
* ensured that `Brave News` isn't being displayed under `Settings` via the `Features` section

**`News Disabled`** | **`News Disabled`**
----------------------|------------------------
![Screenshot_20211221-152254](https://user-images.githubusercontent.com/387249/147011150-52264496-ab75-4d8e-a480-57d103acfae5.png) | ![Screenshot_20211221-152303](https://user-images.githubusercontent.com/387249/147011165-b84eb7fc-8e30-4912-9cf8-3937661d9b34.png)


 
**`News Enabled`** | **`News Enabled`**
----------------------|------------------------
![Screenshot_20211221-152357](https://user-images.githubusercontent.com/387249/147011180-8e7e99db-d138-456a-a7dd-a2d3571b7e72.png) | ![Screenshot_20211221-152406](https://user-images.githubusercontent.com/387249/147011195-26dabfd8-2095-4c71-806a-272cf6bd8d0c.png)




**`News Disabled`** | **`News Enabled`**
----------------------|------------------------

**Comment by kjozwiak** [comment]
Adding `release-notes/exclude` as `Brave News` is still tied to Nightly via Griffin. The above verifications were to ensure that Brave News wasn't being displayed/shown via NTP on the `RELEASE` channel. QA also ensured that none of the Brave News settings were visible.
