### ISSUE TITLE
Linux no longer has video hardware acceleration

### ISSUE THREAD

**Issue by qingxiang-jia** [brave/brave-browser#16392]
## Steps to Reproduce

   1. Go to any YouTube video that is >= 1080p.
   2. Play it and use the inspector's media tag, check the video decoder.
   3. It would state various software encoders but not the hardware one. Check CPU usage confirms that indeed it's using CPU to decode video.

## Actual result:

We no longer has video hardware acceleration.

## Expected result:
We have a flag that allows us to enable video hardware acceleration like versions before 1.25.72.

## Reproduces how often: 

Always happens. Easy to reproduce.

## Brave version (brave://version info)

Official release. I have tried:
https://github.com/brave/brave-browser/releases/download/v1.25.72/brave-browser_1.25.72_amd64.deb
https://github.com/brave/brave-browser/releases/download/v1.25.72/brave-browser-1.25.72-linux-amd64.zip

But I guess it may all come from the same compiled version and just packaged differently.

## Version/Channel Information:

I didn't try.

- Can you reproduce this issue with the current release? Yes, 1.25.72
- Can you reproduce this issue with the beta channel? I didn't try.
- Can you reproduce this issue with the nightly channel? I didn't try.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Brave used to be compiled with the VAAPI flag on. I don't know why it has changed. But if the concern is "VAAPI may not with all users (notably the NVIDIA ones), so let's disable it for all", I don't think it makes sense as it's just a flag that you can enable. If people have issue with the GPU, they can just disable it (I believe previous Brave versions come with this default to software encoders).

Note, with the new release, we can no longer turn it on in `brave:flags`. It is now classified in the "unsupported group". On archlinux, you can make it "work" on paper by passing runtime flags `--enable-features=VaapiVideoDecoder` but this only makes the `brave://gpu` to show video acceleration is turned on. If you play any videos (>=1080p), it still uses CPU (again, can be confirmed using inspector's media tab).

**Comment by qingxiang-jia** [comment]
Sorry for posting an invalid issue. I think some videos on YouTube are encoded using AV1 and Brave will use dav1d software decoder for that. But for ones encoded differently, Brave indeed uses GPU for it if we have `--enable-features=VaapiVideoDecoder` on. I will close this issue.

**Comment by mirenradia** [comment]
I'm still having difficulty enabling hardware video decoding with Brave v1.25.73 for non-AV1 encoded videos. I have the `#ignore-gpu-blocklist` flag set to enabled and am passing `--enable-features=VaapiVideoDecoder` on the command line (so `brave://gpu` reports "Video Decode" as "Hardware accelerated"). I don't think it's an issue with my GPU/drivers as I had no problems with earlier versions. I've tried with and without the command line flag `--use-gl=desktop` and `--use-gl=egl` but `brave://media-internals` always seems to indicate `VpxVideoDecoder` or `FFMpegVideoDecoder` is being used (where it used to be `MojoVideoDecoder`).

In case it's helpful, I am on Ubuntu 20.04 with Intel HD Graphics 630 (KBL GT2) and am using the `intel-media-va-driver-non-free`.

I can reopen a new issue if that would be helpful.

**Comment by qingxiang-jia** [comment]
I am not sure why it didn't work in your setup. If it helps, I am using AMG GPU with X11. My understanding is, if you are using wayland (I am not sure if that's the case), there is currently no acceleration. Also, the media-internals page is been deprecated.

**Comment by mirenradia** [comment]
I am using X11 so Wayland can't be the problem.

I'm aware the media-internals page will eventually be removed in a future Chromium release but until it does, I still find it easier to access than the Developer tools.

**Comment by airfield20** [comment]
Same issue here, on X11, vaapi-drivers installed, ignore gpu blocklist enabled, and ran with command line flags and it just doesnt work. I have an nvidia GPU and I'm tring to use onshape CAD. 

Works perfectly on chrome without any extra work.
