### ISSUE TITLE
Table headers not locked - works as expected in Chrome

### ISSUE THREAD

**Issue by dharmatech** [brave/brave-browser#16393]
## Description 

Codepen:

https://jsfiddle.net/rpne1as6/1/

The top two table rows of the table should be locked. However, only the first one is locked:

![image](https://user-images.githubusercontent.com/20816/121789709-f454f300-cb8c-11eb-9d26-5a49625bf687.png)

In Chrome, both of them are locked as expected:

![image](https://user-images.githubusercontent.com/20816/121789756-6a595a00-cb8d-11eb-8329-6465c867eb8a.png)

## Brave version (brave://version info)

Brave | 1.25.70 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2009 (Build 19043.985)
JavaScript | V8&nbsp;9.1.269.28
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,PrefetchPrivacyChanges,LegacyTLSEnforced,AutoupgradeMixedContent,WinrtGeolocationImplementation,SafetyTip --disable-features=IdleDetection,FirstPartySets,InterestCohortAPIOriginTrial,AutofillServerCommunication,LiveCaption,SignedExchangePrefetchCacheForNavigations,NetworkTimeServiceQuerying,SubresourceWebBundles,TabHoverCards,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,SharingQRCodeGenerator,TrustTokens,DirectSockets,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,EnableProfilePickerOnStartup,TextFragmentAnchor,FederatedLearningOfCohorts,HandwritingRecognitionWebPlatformApi,FledgeInterestGroups,InterestCohortFeaturePolicy,WebOTP,NotificationTriggers,LangClientHintHeader,SignedExchangeSubresourcePrefetch --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\dharm\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 8eed39a1-b5b1907865588e80-d0fdf2a81f0eeff1-46c97c06aed3cac0-3f4a17df7146a73c-3f4a17dfc63a3c82-3f4a17df

**Comment by rebron** [comment]
@dharmatech Sorry the delay on this but wasn't reproducible. The top two rows look like they're locked and we're matching chrome behavior here. Please reopen if still an issue.

<img width="1177" alt="Screen Shot 2021-11-12 at 1 41 42 PM" src="https://user-images.githubusercontent.com/5951041/141537953-bdbf7340-06da-40ea-ac1b-df4a094c6f0c.png">

Checked on both macOS and Windows 11

Brave | 1.31.91 Chromium: 95.0.4638.69 (Official Build) (arm64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 12.1 (Build 21C5021h)
