### ISSUE TITLE
beachball during contribution process and becomes unusuable

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1639]
## Description 
While browser was going thru contribution process Brave beachballed and was unusable for a few minutes.

## Steps to Reproduce

enable rewards
add site
claim grant
close browser
modify go to your profile (Default/ledger_state) and modify reconcileStamp to now+5min)
start browser
visit a site (you could encounter https://github.com/brave/brave-browser/issues/1640)
wait for contribution to finish

## Actual result:
Brave beachballs during contribution process and is unusable

## Expected result:
Brave should not beachball.

## Reproduces how often: 
easy

## Brave version (brave://version info)

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? n/a
- Does it reproduce on browser-laptop? no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @kjozwiak @srirambv for testing on other platforms
cc @NejcZdovc

**Comment by NejcZdovc** [comment]
closing as dupe https://github.com/brave/brave-browser/issues/1614
