### ISSUE TITLE
random fingerprint not work when I use selenium to do some auto test

### ISSUE THREAD

**Issue by Planck0591** [brave/brave-browser#16394]
## Description 

I used brave to visist "https://browserleaks.com/canvas",the fingerprint changed every time.But I used selenium to controll brave to vist "https://browserleaks.com/canvas", the fingerprint always the same.

## Steps to Reproduce

options = Options()
options.binary_location = r"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
driver = webdriver.Chrome(executable_path='./drivers/chromedriver.exe',options=options)
driver.maximize_window()
driver.get('https://browserleaks.com/canvas')

## Actual result:

![image](https://user-images.githubusercontent.com/79493220/121800483-3c612d80-cc00-11eb-894c-8d62ce6a0d5b.png)

## Expected result:
changed every time

## Reproduces how often: 

always

## Brave version (brave://version info)

1.25.72 Chromium: 91.0.4472.101

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kanseaveg** [comment]
Seen the same problem on my project. Waiting the answer together~! LOL~

**Comment by fmarier** [comment]
This is related to farbling, cc'ing @pes10k and @pilgrim-brave .

**Comment by ShivanKaul** [comment]
Given that we haven't been able to repro this and it seems to happen only in Selenium, closing.
