### ISSUE TITLE
Rewards onboarding is not shown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16405]
## Description 
Rewards onboarding is not shown

## Steps to reproduce 

   1. Clean install 1.26.59 build
   2. Click on Rewards panel
   3. No onboarding is shown
   4. Close and reopen browser 
   5. No second onboarding is shown 

## Actual result 

https://user-images.githubusercontent.com/17010094/121914965-a970e200-cd2a-11eb-9cf8-f541d8a6a27f.mp4

## Expected result
Should show onboarding the first time rewards panel is opened

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
126.59

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/rewards-client @deeppandya @brave/ads-dev

**Comment by kjozwiak** [comment]
Removing `release/blocking` as @srirambv mentioned this was working in the latest BETA. Seems like there's an issue where sometimes the ledger service doesn't start. @deeppandya is looking into it.

@srirambv @deeppandya if you feel differently, please re-add the label.
