### ISSUE TITLE
auto contribute table is wiped out after adjusting reconcile stamp and visiting a site

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1640]
## Description 
If you visit a site after manually adjusting reconcile stamp, your auto-contribute table gets wiped out

## Steps to Reproduce

enable rewards
add sites
claim grant
close browser
modify go to your profile (Default/ledger_state) and modify reconcileStamp to now+5min)
start browser
visit a site --> previous sites are wiped out, only the site you just visited is in the table

## Actual result:
previous sites are wiped out, only the site you just visited is in the table

## Expected result:
table should not be cleared

## Reproduces how often: 
easy

## Brave version (brave://version info)

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? n/a
- Does it reproduce on browser-laptop? no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @kjozwiak @srirambv for testing on other platforms
cc @NejcZdovc

**Comment by NejcZdovc** [comment]
this is not a bug. Table is connected to reconcile stamp
