### ISSUE TITLE
Add additional via headers to Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#16406]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
-- | --
Revision | 541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569}
OS | Ubuntu 18.04 LTS

**VM**:

<details>

TC1:
![image](https://user-images.githubusercontent.com/34715963/125970054-5acafe75-e139-4eab-a286-ddb82920221e.png)

TC2:
![image](https://user-images.githubusercontent.com/34715963/125970616-1ee6c5d6-219d-461d-ad69-0f9e4a96c00f.png)

TC3:
![image](https://user-images.githubusercontent.com/34715963/125970957-6a1d6b78-d69a-489c-ac75-5ff43e0df8a8.png)


</details>

**Physical machine**
<details>

TC1:
![image](https://user-images.githubusercontent.com/34715963/125971097-2c2e432a-8b13-4e38-8d54-8ff3661296d2.png)


TC2:
![image](https://user-images.githubusercontent.com/34715963/125971128-c572eaa3-fd86-43ca-9936-c0ce07441b8a.png)


TC3:
![image](https://user-images.githubusercontent.com/34715963/125971184-ca85b861-228b-4261-9587-900c2b78acfa.png)


</details>
