### ISSUE TITLE
intel driver assistant doesn't work

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#16409]
## Description 

on windows10 when Brave is set as default browser the intel driver assistant doesn't work.
With chrome and edge it works.

## Steps to Reproduce

   1.  set brave as default browser
   2. go to https://www.intel.it/content/www/it/it/support/detect.html
   3. install "intel driver assistant"
   4. click the icon in tray area and search for new drivers

## Actual result:

I get an error.

## Expected result:
I want to see a list of drivers to update

## Reproduces how often: 

always

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
If you allow all ads/trackers in shields, does that help? @tortino

**Comment by tortino** [comment]
I forgot to check with shields disabled...  yes, it works.
