### ISSUE TITLE
Brave Ads `dom_distiller::RunIsolatedJavaScript` throws `DCHECK` exception

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#16410]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@tmancey I can still reproduce this on Nightly. I got into a loop where I kept receiving the following emails even though I've logged in several times:

![verification2](https://user-images.githubusercontent.com/2602313/123728297-07d8ad00-d861-11eb-85be-162c8ec95fe2.png)

STR:

* launched `1.28.35 Chromium: 91.0.4472.124`
* once launched, went into `brave://rewards` and clicked on `Verify`
* logged into my Uphold account and was told that I need to verify that it's me via a email verification
* clicked on `Yes, it's me` and was redirected back to Uphold where I need to re-login again
* entered all my credentials and 2FA and received the following screen once again (cycle repeats itself over and over)

![image](https://user-images.githubusercontent.com/2602313/123728594-7f0e4100-d861-11eb-9816-1559796bcc7f.png)

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` based on discussion in https://bravesoftware.slack.com/archives/CB0KCRCQN/p1624937105261700

**Comment by rebron** [comment]
QA note to double check classifications are working.

**Comment by kjozwiak** [comment]
As per the discussion with @tmancey via the b-b triage/planning call, we should check to make sure that page classifications are working as per https://github.com/brave/brave-browser/issues/16410#issuecomment-883594249.

Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.27.106 Chromium: 92.0.4515.101 (Official Build) (64-bit)
--- | ---
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | Windows 10 OS Version 2009 (Build 19042.1110)
```

Ensured that text classification was initialised as per the following:

```
[2408:28516:0720/144208.278:VERBOSE1:text_classification_resource.cc(48)] Successfully loaded feibnmjhecfbjpeciancnchbmlobenjn text classification resource
[2408:28516:0720/144208.609:VERBOSE1:text_classification_resource.cc(57)] Successfully initialized feibnmjhecfbjpeciancnchbmlobenjn text classification resource
```

* visited https://www.espn.com and ensured the page was classified as per the following:

```
[2408:28516:0720/144232.655:VERBOSE1:text_classification_processor.cc(62)] Classified text with the top segment as sports-american football
[2408:28516:0720/144234.189:VERBOSE1:text_classification_processor.cc(62)] Classified text with the top segment as sports-basketball
```

* visited https://www.metacritic.com and ensured the page was classified as per the following:

```
[2408:28516:0720/145003.772:VERBOSE1:text_classification_processor.cc(62)] Classified text with the top segment as gaming-gaming
```

* visited https://coinmarketcap.com and ensured the page was classified as per the following:

```
[2408:28516:0720/145130.122:VERBOSE1:text_classification_processor.cc(62)] Classified text with the top segment as hobbies & interests-coins
```
