### ISSUE TITLE
Feature Request:  Ability to view 7-day ads history and past monthly Brave Rewards statements

### ISSUE THREAD

**Issue by enxio27** [brave/brave-browser#16418]
**Feature Request**

## Description 

Android version of Brave has no options to view the 7-day ads history or monthly rewards statements.  Windows desktop version of Brave Rewards shows options to view 7-day ads history and monthly rewards statements.

## Steps to reproduce 

   1.  Open brave://rewards/ads and brave://rewards/#rewards-summary on Android device
 
## Actual result 

No options to view either 7-day ads history or past monthly Rewards statements (only most recent is accessible)

## Expected result

Be able to view 7-day ads history and past month Rewards statements (same as on Windows desktop version)

## Issue reproduces how often 
 
100%

## Version/Channel Information:

Play Store version, up to and including ver. 1.25.71

## Device details

   - Install type (ARM, x86):  Google Play Store
   - Device type (Phone, Tablet, Phablet):  Tablet (Samsung Galaxy Tab 6)
   - Android version:  Android 11;  Build/RP1A.200720.012
   
## Brave version

1.25.71; Chromium 91.0.4472.88

**Comment by enxio27** [comment]
Please extend to 30 day ad history along with issue #16627 
https://github.com/brave/brave-browser/issues/16627

**Comment by Miyayes** [comment]
I will break this out into 2 separate issues. Thanks for submitting!
