### ISSUE TITLE
Capitalize Text in Import Selected text to IPFS context-menu item

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16421]
## Description 

Capitalize `Text` in `Import Selected text to IPFS` context-menu item

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `ipns://brantly.eth`
   4. click on `Use a local node`
   5. load `https://www.lipsum.com/`
   6. scroll down to the `Lorem ipsum...` paragraph, highlight it, and context-click
   7. look at the `Import Selected text to IPFS` menu item

## Actual result:

Menu item reads `Import Selected text to IPFS`

<img width="1197" alt="Screen Shot 2021-06-14 at 4 04 23 PM" src="https://user-images.githubusercontent.com/387249/121969933-41ba9700-cd2a-11eb-9bbb-35f12634a51c.png">

## Expected result:
Should probably read `Import Selected Text to IPFS`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.63 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

**Comment by soham4abc** [comment]
I can work in this issue

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.18 Chromium: 91.0.4472.114 (Official Build) nightly (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)

Steps:

1. new profile
2. launch Brave
3. load ipns://brantly.eth
4. click on Use a local node
5. load https://www.lipsum.com/
6. scroll down to the Lorem ipsum... paragraph, highlight it, and context-click
7. look at the Import Selected text to IPFS menu item

Confirmed the context-menu item now reads `Import Selected Text to IPFS`

<img width="1198" alt="Screen Shot 2021-06-21 at 5 12 32 PM" src="https://user-images.githubusercontent.com/387249/122843360-1dbffe00-d2b4-11eb-93a7-45452c487bf2.png">
