### ISSUE TITLE
Small styling issue with checkbox

### ISSUE THREAD

**Issue by rexfordkelly** [brave/brave-browser#16428]
## Description 
toggle switch has border on :hover

## Steps to Reproduce
- open brave on windows, Brace version 1.25.72
- open a new tab
- click on customize
- click on "show background image" toggle

## Actual result:
![Screenshot 2021-06-14 223621](https://user-images.githubusercontent.com/3839452/121998640-025b6d00-cd61-11eb-8092-f5d207a1b1d9.png)

## Expected result:
just no border around the checkbox

## Reproduces how often: 
100% of the time, no need to do anything special

## Brave version (brave://version info)

Brave | 1.25.72 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | Windows&nbsp;10 OS Version 2009 (Build 19042.1052)
JavaScript | V8&nbsp;9.1.269.36
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
Command Line | "C:\Users\18189\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe" --from-installer --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,SafetyTip,WinrtGeolocationImplementation --disable-features=AutofillServerCommunication,InterestCohortFeaturePolicy,FederatedLearningOfCohorts,HandwritingRecognitionWebPlatformApi,LiveCaption,IdleDetection,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,SignedExchangePrefetchCacheForNavigations,NetworkTimeServiceQuerying,SubresourceWebBundles,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,EnableProfilePickerOnStartup,TextFragmentAnchor,InterestCohortAPIOriginTrial,FirstPartySets,FledgeInterestGroups,TabHoverCards,TrustTokens,DirectSockets,SharingQRCodeGenerator,SignedExchangeSubresourcePrefetch,WebOTP,NotificationTriggers,LangClientHintHeader --flag-switches-begin --flag-switches-end
Executable Path | C:\Users\18189\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\18189\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-59e286d0

**Comment by rebron** [comment]
Closing. This is working as expected as an accessibility/focus cue.
