### ISSUE TITLE
Enable TorSearchEngineProviderControllerTest.DISABLED_CheckTorProfileSearchProviderTest

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#1642]
When I implement `TorSearchEngineProviderController`, I wanted to add test case for this class whether appropriate default search engine is set.
To do this, stub test `CheckTorProfileSearchProviderTest` is added but crashed at initialization phase.
So, I did manually test this class and left as disabled state.
Later, anthony mentioned that `TorUnittestProfileManager` should be used.

https://github.com/brave/brave-core/pull/529#discussion_r222368775

**Comment by tomlowenthal** [comment]
Looks like this issue was just created to have something to reference in the PR? Could you add a plain-language summary of this change?
