### ISSUE TITLE
Error pinning reading config in pinmfs.go:74

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16423]
## Description 

Error pinning reading config in pinmfs.go:74

## Steps to Reproduce

   1. new profile
   2. launch Brave with `--use-dev-goupdater-url` (this doesn't reproduce with the default `0.7.0` binaries)
   3. load `ipns://brantly.eth`
   4. click on `Use a local node`
   5. look at the console output

## Actual result:

`2021-06-14T16:11:45.424-0700	ERROR	remotepinning/mfs	ipfs/pinmfs.go:74	pinning reading config (ipfs not initialized, please run 'ipfs init')`

I don't know if this is just an early warning presenting itself as an error, or if something is actually wrong?

<img width="1648" alt="Screen Shot 2021-06-14 at 4 16 49 PM" src="https://user-images.githubusercontent.com/387249/121970742-1042cb00-cd2c-11eb-9c92-28a3f52c610a.png">

## Expected result:

No error

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.63 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

/cc @lidel @autonome

**Comment by lidel** [comment]
Yes, in the context of the very first run, this does not look like an error, just a warning. 

@spylogsster (that being said) I was not able to reproduce this with `docker run --rm -it --net=host  ipfs/go-ipfs:v0.9.0-rc2`,   is anything additional happening in Brave to produce this?

**Comment by spylogsster** [comment]
I cannot reproduce it too, @stephendonner, how did you create new profile?

**Comment by stephendonner** [comment]
> I cannot reproduce it too, @stephendonner, how did you create new profile?

`rm -rf /Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser-Nightly`

**Comment by stephendonner** [comment]
Tried to reproduce this again a few times, using 

Brave | 1.27.65 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

and was unable to see the issue.

Closing out!
