### ISSUE TITLE
I can't add wallet

### ISSUE THREAD

**Issue by haima95** [brave/brave-browser#16438]
## Steps to Reproduce

   1. click <Crypto Wallet> tab，there is nothing，it's empty

## Actual result:

![image](https://user-images.githubusercontent.com/2991141/122019183-1dc48780-cdf6-11eb-9c53-9179ad996e86.png)

## Reproduces how often: 

it's always

## Brave version (brave://version info)

my computer is mac，10.15.7

brave version：版本 1.25.72 Chromium: 91.0.4472.101（正式版本） (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Can you check `brave://components` and see if Crypto Wallet component is downloaded?

**Comment by haima95** [comment]
> Can you check `brave://components` and see if Crypto Wallet component is downloaded?

![image](https://user-images.githubusercontent.com/2991141/122050882-87548e00-ce16-11eb-9cee-8113ad60a137.png)

dose that mean crypto wallet not be downloaded ?  How can I download crypto wallet. 

Thx

**Comment by srirambv** [comment]
Yes the component is not downloaded that is why its not loading. Click the button to check for update so it downloads the component and you will be able to create the wallet

**Comment by haima95** [comment]
> > Can you check `brave://components` and see if Crypto Wallet component is downloaded?
> 
> ![image](https://user-images.githubusercontent.com/2991141/122050882-87548e00-ce16-11eb-9cee-8113ad60a137.png)
> 
> dose that mean crypto wallet not be downloaded ? How can I download crypto wallet.
> 
> Thx



> Yes the component is not downloaded that is why its not loading. Click the button to check for update so it downloads the component and you will be able to create the wallet

It works。 Thx very much

**Comment by srirambv** [comment]
Closing the issue based https://github.com/brave/brave-browser/issues/16438#issuecomment-861470495
