### ISSUE TITLE
Guest/Tor window cannot be closed via browser action button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1643]
## Description 

Guest/Tor window cannot be closed via browser action button

## Steps to Reproduce

   1. Install 0.55.16
   2. Open a Guest/Tor window
   3. Try to close via browser action button, doesn't close. Have to close tabs to close the window

## Actual result:

https://youtu.be/Gyz9Sp7H5Xo

## Expected result:
Should be able to close the browser via browser action button

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
No
- Does it reproduce on browser-laptop? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information

Issue doesn't reproduce on Windows. @brave/legacy_qa to verify on other platforms

**Comment by kjozwiak** [comment]
Checked the following platforms:

* macOS 10.13.6 x64 - **Couldn't reproduce**
* Ubuntu 18.04 x64 VM - **Reproduced**
* Mint 18.3 x64 - **Reproduced**

Used the following build:

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}

**Comment by bbondy** [comment]
I couldn't reproduce from a local build on Mint, seems to be CI builds only for some strange reason.

**Comment by bbondy** [comment]
Moving out as `priority/p2` because we have no leads for this and it doesn't need to block today's release. 

I can reproduce easily on Linux Mint. 
I cannot reproduce with the same source code though with a debug build, or a release build.  Nor even with a release optimized build.  Nor if I build a .deb and install the deb.

It seems like something infra related but it's also strange it started happening back at an older version.

**Comment by srirambv** [comment]
New observation, issue happens when normal window is present. If normal tab window is closed then both Tor/Guest windows can be closed via the browser action buttons.

**Comment by darkdh** [comment]
• `0.55.16` - Reproduced
• `0.55.14` - Reproduced
• `0.55.13` - Reproduced
• `0.55.12` - Couldn't Reproduce
by @kjozwiak

**Comment by kjozwiak** [comment]
Went through verification using the following build under `Ubuntu 18.04 x64` - **PASSED**

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
--- | ---
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Linux

* ensured that you can close Tor windows using `X`
* ensured that you can close regular windows using `X`
* ensured that you can close private windows using `X`
* ensured that you can close Tor windows using `Exit Tor`
