### ISSUE TITLE
how local wallet can connect to  sites？

### ISSUE THREAD

**Issue by haima95** [brave/brave-browser#16440]
## Steps to Reproduce

   1.  Account is not connected to any sites. the hint is "Brave is not connected this site. To connect to a web3 site, find the connect button on their site."     How to fix it

## Actual result:

![image](https://user-images.githubusercontent.com/2991141/122070547-a52aee80-ce28-11eb-958f-1b311adac767.png)

## Reproduces how often: 

I create the local wallet and do nothing else, the local wallet show not connected.

## Brave version (brave://version info)

brave version: 版本 1.25.72 Chromium: 91.0.4472.101（正式版本） (x86_64)

my compute is mac:  version is 10.15.7

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Wallet only connects to Dapp and not all regular sites.
