### ISSUE TITLE
The custom header list should be hard-coded

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16455]
Right now, [custom headers](https://github.com/brave/brave-browser/wiki/Custom-Headers) rely on a list that's provided on startup by the following endpoint: https://laptop-updates.brave.com/promo/custom-headers

Since this is a deprecated mechanism to tell websites that a visitor is using Brave, there is no need for this list to be updatable more often than what can be provided via the normal release cycle.

@diracdeltas had the idea of taking another step towards removal of this legacy feature by moving the dynamic list to be hard-coded in a C++ constant. That way, we can deprecate the `laptop-updates` endpoint (combined with the work in #16374) and eventually turn it off.

**Comment by keur** [comment]
Test Plan
------------

Run the browser with a clean profile. Navigate to `brave://local-state`. Ensure the referral headers are the same between versions.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.27 Chromium: 91.0.4472.120 (Official Build) nightly (x86_64)
-- | --
Revision | 12c5925972cffe578ca7ca7a295e98ee7e178a7a-refs/branch-heads/4472@{#1506}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. clean profile
2. launched Wireshark, filtered for `dns` (and launched Charles Proxy, as backup verification)
3. launched Brave
4. opened Developer Tools' `Network` panel
5. loaded `eaff.com`
6. loaded `uphold.com`
7. loaded `grammarly.com`

Confirmed via the Network panel (and clicking on a request) for `eaff.com`, `uphold.com`, and `grammarly.com`:
* X-Brave-Partner: `eaff`, `uphold`, and `grammarly` were present, for their respective site
* there were *NO* DNS lookups/connections made to the `https://laptop-updates.com/promo/custom-headers` endpoint, while running these tests - checked via both Wireshark and Charles Proxy

eaff.com | uphold.com | grammarly.com
---------|--------------|---------------
<img width="1757" alt="Screen Shot 2021-06-24 at 3 12 43 PM" src="https://user-images.githubusercontent.com/387249/123339932-518f6380-d500-11eb-800b-21645a66f2ce.png"> | <img width="1757" alt="Screen Shot 2021-06-24 at 3 12 56 PM" src="https://user-images.githubusercontent.com/387249/123339935-5227fa00-d500-11eb-8307-1509720761a2.png"> | <img width="1757" alt="Screen Shot 2021-06-24 at 3 13 40 PM" src="https://user-images.githubusercontent.com/387249/123339936-5227fa00-d500-11eb-84cd-6cb7725050af.png">


Wireshark | Charles Proxy
-----------|--------------
<img width="1771" alt="Screen Shot 2021-06-24 at 3 14 58 PM" src="https://user-images.githubusercontent.com/387249/123339784-10974f00-d500-11eb-93c2-ad88b6203c00.png"> | <img width="1688" alt="Screen Shot 2021-06-24 at 3 13 49 PM" src="https://user-images.githubusercontent.com/387249/123339842-2efd4a80-d500-11eb-9dbb-b2a3d055b153.png">

**Comment by srirambv** [comment]
Verification passed on Oppo R5 with Android 11 running 1.28.99 x64 Beta Build
- Verified the test plan from https://github.com/brave/brave-browser/issues/16455#issuecomment-862846298
- Verified `X-Brave-Partner: eaff`, `X-Brave-Partner: uphold`, and `X-Brave-Partner: grammarly` were present, for their respective site via Network panel in dev tools 

EAFF.com | Uphold.com | Grammarly.com
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/127980623-318dbca3-42a9-4d00-8132-0be53e887460.png) | ![image](https://user-images.githubusercontent.com/17010094/127980776-690c01a9-40e7-448b-98cf-2c5b3794a8fa.png) | ![image](https://user-images.githubusercontent.com/17010094/127980876-58faefed-4ba2-460e-8a9b-415145685f42.png) | 

- Verified there were NO DNS lookups/connections made to the `https://laptop-updates.com/promo/custom-headers` endpoint, while running these tests for Uphold.com
![image](https://user-images.githubusercontent.com/17010094/127985570-0d80ad20-9929-4a32-9622-93bf1ac92b08.png)

----------------
Verification passed on Samsung Tab A with Android 10 running 1.28.99 x64 Beta Build
- Verified the test plan from https://github.com/brave/brave-browser/issues/16455#issuecomment-862846298
- Verified `X-Brave-Partner: eaff`, `X-Brave-Partner: uphold`, and `X-Brave-Partner: grammarly` were present, for their respective site via Network panel in dev tools 
- Verified there were NO DNS lookups/connections made to the `https://laptop-updates.com/promo/custom-headers` endpoint, while running these tests

EAFF.com | Uphold.com | Grammarly.com
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/127981251-ac7e3786-9b85-4c87-adaf-14cfca2b32c2.png) | ![image](https://user-images.githubusercontent.com/17010094/127981719-63a60f24-d9ef-4b5e-8b26-bfcca35ae6dc.png) | ![image](https://user-images.githubusercontent.com/17010094/127981826-c242bb16-a30b-42d3-b9b3-e8979acac796.png)

- Verified there were NO DNS lookups/connections made to the `https://laptop-updates.com/promo/custom-headers` endpoint, while running these tests for EAFF.com
- ![image](https://user-images.githubusercontent.com/17010094/127985589-a2d6cdfe-f109-40cc-9c7c-909f8236e587.png)
