### ISSUE TITLE
opening Incognito, Tor and Guest windows for the first time appears janky when loading "brave://newtab"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1645]
## Description 

After implementing the new `brave://newtab` pages, opening `Incognito`, `Tor` or `Guest` windows for the first time will appear white for a few seconds before loading `brave://newtab`. Sometimes this makes the window appear as it's "flashing". Sometimes it loads pretty quickly and sometimes there's a delay which makes it look like brave is janky/having issues loading the window.

We should make this a smoother transition.

## Steps to Reproduce

   1. install & open `0.55.16 Chromium: 70.0.3538.54 (release)`
   2. open `Incognito`, `Tor` or `Guest` windows 

You'll notice that when the window initially loads, it will appear white for a few seconds before loading `brave://newtab`.

## Actual result:

https://youtu.be/Rrmo6gGqq80

## Expected result:

Opening `Incognito`, `Tor` and `Guest` windows should be a smooth experience.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Not 100% sure as the changes just landed and we don't have `dev` nor `beta` builds available that include these new changes.

- Does it reproduce on browser-laptop?

N/A

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible in windows 10 x64 - Brave beta`0.70.109`

![white flash](https://user-images.githubusercontent.com/38657976/66311935-457b0100-e92d-11e9-82fd-bc39e6593621.gif)
