### ISSUE TITLE
Tab grouping doesn't work in Arch Linux

### ISSUE THREAD

**Issue by Rohit-Rangaraj** [brave/brave-browser#16458]
Tab groups flags don't include enable tab grouping 

![2021-06-16-12:12:09-screenshot](https://user-images.githubusercontent.com/20149534/122170589-5ae35500-ce9c-11eb-88dc-3c7bbd94be37.png)
![2021-06-16-12:14:41-screenshot](https://user-images.githubusercontent.com/20149534/122170693-7e0e0480-ce9c-11eb-8919-0633123e117d.png)
![2021-06-16-12:12:43-screenshot](https://user-images.githubusercontent.com/20149534/122170595-5c148200-ce9c-11eb-9c75-b26bc7322d8c.png)

**Comment by TheCultLeader666** [comment]
Right click > Add tab to new group? This is a feature that's fully implemented into chromium iirc

**Comment by wknapik** [comment]
@Rohit-Rangaraj please describe the issue. I'm using tab groups on Arch Linux without issues.

**Comment by Rohit-Rangaraj** [comment]
Ok very sorry jus updated and restarted Brave 
working as intended!
Sorry for the inconvenience.
