### ISSUE TITLE
ads from dismissed campaign keep showing

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#16451]
When user dismisses an ad, all other ads from that campaign should be frequency capped (not served). Those ads are not blocked in this scenario.

## Steps to Reproduce

1. Use catalog on staging:
[postview - same set v7.txt](https://github.com/brave/internal/files/6651041/postview.-.same.set.v7.txt)
[postview - same set v8.txt](https://github.com/brave/internal/files/6654267/postview.-.same.set.v8.txt)
1. Clean Profile
1. Run Brave with cmd line:
`--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6  --brave-ads-staging --brave-ads-debug --rewards=staging=true --variations-server-url=https://no-thanks.invalid`
1. Trigger a notification ad
1. Dismiss the ad
1. Close Brave
1. Wait 1hour
1. Trigger a notification ad

Also follow `exclude_ad_if_dismissed_within_time_window - default (48h) - blocked` from https://github.com/brave/internal/issues/776

Important: Without Browser restart, the test case passes and ads are blocked

## Actual result:

ads from the same campaign keep showing

## Expected result:
ads are blocked
Example log:
```
[28293:28293:0615/212444.199581:VERBOSE2:exclusion_rule_util.h(26)] campaignId 0d01425b-c970-4a25-b2d0-ccf748cfaf6e has exceeded the frequency capping for dismissed
[28293:28293:0615/212444.201611:VERBOSE2:exclusion_rule_util.h(26)] campaignId 0d01425b-c970-4a25-b2d0-ccf748cfaf6e has exceeded the frequency capping for dismissed
```

## Reproduces how often: 

100% repro rate

## Version/Channel Information:

Reproduced on:

Brave | 1.25.72 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | Ubuntu 18.04 LTS

Brave | 1.26.59 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | Ubuntu 18.04 LTS

Brave | 1.27.65 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | Ubuntu 18.04 LTS

cc @tmancey @moritzhaller @jsecretan @brave/legacy_qa @rebron

**Comment by tmancey** [comment]
This frequency cap is only triggered if you dismiss the same ad twice in a row. Thanks
