### ISSUE TITLE
New tab page Thumbnail Removed popup persists even after Brave is restarted

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#1646]
## Description 
If a top site thumbnail on the new tab page is deleted, the popup that says "Thumb Removed." is shown, as expected. However, if Brave is quit and restarted, the popup still shows. This is confusing because the thumbnail was not removed during the current browsing session.

## Steps to Reproduce
   1. Make sure there is at least one top site thumbnail on the new tab page. If not, browse a few websites.
   2. Click the remove button on the thumbnail.
   3. Quit Brave.
   4. Open Brave again.

## Actual result:
![](https://user-images.githubusercontent.com/19424103/47061705-4f45aa80-d198-11e8-9246-7231596fb483.png)
The Thumbnail Removed popup is still shown.

## Expected result:
The popup should not be shown.

## Reproduces how often: 
Possibly intermittent, but I haven't tested enough to be sure.

## Brave version (brave://version info)
Brave	0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
Revision	4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS	Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes.
- Does it reproduce on browser-laptop? Not sure.

### Additional Information
Labels: [feature/new-tab](/brave/brave-browser/labels/feature%2Fnew-tab)

**Comment by Liunkae** [comment]
May be fixed with the dashboard page redesign (as of 0.60.16 dev). The popup disappears if I close and reopen the window. I haven't tried with quit/restart yet.

**Comment by Liunkae** [comment]
Confirmed fixed as of 0.60.17 dev (after the dashboard page redesign).

**Comment by simonhong** [comment]
Fixed by https://github.com/brave/brave-core/pull/1194

**Comment by simonhong** [comment]
duplicated with https://github.com/brave/brave-browser/issues/2772
