### ISSUE TITLE
Show error modal when wallet verify fails because user tries verifying 2 different accounts at same custodian with same Wallet ID

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16468]
## Description 

A user cannot verify more than 1 of the same custodian (e.g., Uphold) account with any Rewards Wallet ID. If they try, the second Uphold linking attempt will fail. An error is logged in Rewards logs, but no specific error is shown in the UI to tell the user.

Edit: When testing in the bitFlyer case, the following generic error modal appears: 

<img src="https://user-images.githubusercontent.com/11497541/122303479-9e0beb00-ced1-11eb-8300-8c3c979bd06e.png" width="400px">

## Solution

Show an error modal in the brave://rewards settings page (as part of the linking attempt process) telling the user that wallet verifying failed because their Brave Rewards wallet is already associated with another account at that custodian. @emerick can help with this error modal if needed.

**Update:** Wallet should not go into "Wallet verified" state with the new account. Wallet state should remain whatever it was prior to attempt to verify with a second Uphold account. 

### Error Modal Text

>"Hmm, it looks like your Brave Rewards wallet has already been verified with another {custodian name} account. Please try verifying again using your previous account." 

Copy approved by @codybanxs

**Comment by LaurenWags** [comment]
Per the wallet disconnect (https://github.com/brave/brave-browser/issues/15237) testing call today with @jumde @Miyayes @husobee, we encountered this problem with the below version while testing on staging env. 

```
Brave | 1.27.78 Chromium: 91.0.4472.114 (Official Build) beta (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 10.15.7 (Build 19H1217)
```

The UI is showing "Wallet Verified" and the wallet balance but it should not be. If you look at the logs you will see an error:

```
> Result: Failure
> HTTP Code: 403
> Body: {"message":"error linking wallet: unable to link wallets: unable to match wallets: wallets do not match","code":403}
```

Steps for the two scenarios which produced this issue can be found under https://github.com/brave/internal/issues/774#issuecomment-856063731. They are:
* Scenario 1A: A user still cannot connect 2 accounts from the same custodian to a single Wallet ID (explicit disconnect)
* Scenario 1B: A user still cannot connect 2 accounts from the same custodian to a single Wallet ID (natural disconnect)

In 1A, the UI should not show wallet balance and should show "Verify Wallet".
In 1B, the UI should not show wallet balance and should show "Disconnected".

@Miyayes please correct if I've misspoken on any of the above per today's discussions.

**Comment by zenparsing** [comment]
This may be resolved by https://github.com/brave/brave-core/pull/9212

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/9212

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.29.63 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 10.15.7 (Build 19H1323)
```

<details>
<summary>Uphold</summary>

See https://github.com/brave/brave-browser/issues/17271#issuecomment-901389159, https://github.com/brave/brave-browser/issues/17265#issuecomment-901355140, https://github.com/brave/brave-browser/issues/17259#issuecomment-901351609 for verifications with Clean and Upgrade profiles.

</details>

TBD:

<details>
<summary>Gemini</summary>

</details>

<details>
<summary>bitFlyer</summary>

</details>
