### ISSUE TITLE
Youtube ads showing in Brave

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#16479]
## Description 
When experiencing youtube video ads with shields up.  We're trying to diagnose the cause and see what a possible solution is.

## Steps to Reproduce

- [ ]    1. Ensure shields is enabled
- [ ]    2. Open youtube.com link
- [ ]    3. Open the console Tab (Press F12)
- [ ]    4. Play youtube clip, with included ad video
- [ ]    5. Screenshot the output of the console tab when the advert is playing.
- [ ]    6. Does shields show any blocked items in Ads and Trackers?
- [ ]    7. Is the advert replicable in current, beta or nightly channels? (which version of Brave was tested)

## Troubleshooting. 

Some previous solutions which helped some people, **Test each option individually to see which is the possible fix.**

- [ ] - `brave://net-internals/#dns` -> Clear host cache, then refresh the youtube website, re-test for video ads.
- [ ] - `brave://net-internals/#sockets` -> Select Close idle sockets, and click Flush socket pools, then refresh the youtube website, re-test for video ads.
- [ ] - Chrome/Brave: Clearing Cache, `brave://settings/clearBrowserData`, then refresh the youtube website, re-test for video ads.

## Miscellaneous Information:

1. Also testing in a private window mode, and/or in a new Brave profile with no extensions
2. Which video is causing the video advert, link here.

**Comment by ryanbr** [comment]
Post the details from the above report here.

**Comment by vrischmann** [comment]
I'm getting ads on [this youtube video](https://www.youtube.com/watch?v=D8eCPl2zit4)
I consistently get an ad in a normal window where I'm logged in or in a private window, in both cases Shields is showing a bunch of trackers and ads blocked.

Here is a screenshot of the console in a normal window:
![Screenshot from 2021-06-24 00-22-45](https://user-images.githubusercontent.com/1916079/123176589-ffa8f800-d483-11eb-9c27-5f06cf34f157.png)

and a screenshot of the console in a private window:
![Screenshot from 2021-06-24 00-27-14](https://user-images.githubusercontent.com/1916079/123176609-0899c980-d484-11eb-9778-a6bf1adf3764.png)
 
I tried the troubleshooting steps, they don't appear to have any effect, I still get an ad.

I'm using Brave Stable. Let me know if you'd like more information.

**Comment by frankwaves** [comment]
I've been having this problem as well, tried everything I could think of but finally found the work-around. Going to desktop mode seemed to have defeated the ads, still getting them in mobile. Hope this helps

**Comment by ryanbr** [comment]
On Android, try clearing browsing data (cookies and site data). then close/restart Brave @frankwaves

**Comment by ryanbr** [comment]
@frankwaves @vrischmann   How is this looking? any more YT ads?

**Comment by frankwaves** [comment]
> @frankwaves @vrischmann How is this looking? any more YT ads?

Sorry for late reply. I had tried that already when I posted my original message, it did not work.

**Comment by vrischmann** [comment]
I was testing on desktop, not Android.

**Comment by ryanbr** [comment]
@vrischmann @frankwaves How is the latest version of Brave and Youtube ads?

**Comment by frankwaves** [comment]
> @vrischmann @frankwaves How is the latest version of Brave and Youtube ads?

Still getting ads on Android

**Comment by ryanbr** [comment]
@frankwaves Can you clear Browsing data, cookies/cache, then restart Brave

**Comment by vrischmann** [comment]
as of today, using v1.27.109 on Linux Desktop, I'm not seeing any ads on youtube.

**Comment by ryanbr** [comment]
No recent reports of youtube ads, seems to be okay.
