### ISSUE TITLE
Move security and privacy higher in brave://settings

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#16470]
The entire Security and Privacy section of settings should be moved so it's not behind the drop-down on the sidebar. If needed we can switch it with the Safety Check menu item which isn't very important.

- [ ] Move Privacy and security section above the fold under Social media blocking
- [ ] Move Safety check below the fold below Downloads and above Help tips

## Expected Result - Updated Design and Text
New placement for Privacy and security section under Social media blocking

<img width="240" alt="screen_shot_2021-06-24_at_10 50 59_pm" src="https://user-images.githubusercontent.com/5951041/123474485-e0f35000-d5ae-11eb-973f-1fc1c71b2cd2.png">

New placement for Safety check below Downloads and above Help tips

<img width="240" alt="screen_shot_2021-06-24_at_10 51 16_pm" src="https://user-images.githubusercontent.com/5951041/123474488-e2247d00-d5ae-11eb-8002-7c85d319bb5c.png">

## Current Design for QA Reference

Brave | 1.26.67 Chromium: 91.0.4472.114 (Official Build) (arm64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 12.0 (Build 21A5248p)

<img width="269" alt="Screen Shot 2021-06-25 at 12 40 01 PM" src="https://user-images.githubusercontent.com/5951041/123477218-94117880-d5b2-11eb-8f6b-181677adf3c9.png">

**Comment by fmarier** [comment]
Agreed. Safety Check is at the moment (at least until we implement https://github.com/brave/brave-browser/issues/12001) pretty useless in Brave since it essentially just tells users that Safe Browsing is enabled.

**Comment by diracdeltas** [comment]
we decided the text rewording will happen in a follow up

**Comment by stephendonner** [comment]
Verified `PASSED` with build 


Brave | 1.28.37 Chromium: 91.0.4472.124 (Official Build) nightly (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

Confirmed `Privacy & Security` moved up below `Social media blocking` and above `Sync`, and `Safety Check` moved into `Additional Settings`, and it matches that in https://github.com/brave/brave-core/pull/9243, and that various features and pref toggles/states worked, within both of those.

Example | Example | Example | Example
---------|----------|---------|----------
<img width="1312" alt="Screen Shot 2021-06-29 at 3 48 07 PM" src="https://user-images.githubusercontent.com/387249/123877411-fbe8fb80-d8f1-11eb-96c7-e92ba2b465a9.png"> | <img width="1312" alt="Screen Shot 2021-06-29 at 3 48 17 PM" src="https://user-images.githubusercontent.com/387249/123877417-fe4b5580-d8f1-11eb-8f13-6932cf5ef22d.png"> |  <img width="1312" alt="Screen Shot 2021-06-29 at 3 52 32 PM" src="https://user-images.githubusercontent.com/387249/123877483-1a4ef700-d8f2-11eb-9835-f9ce4e888a6e.png"> | <img width="1312" alt="Screen Shot 2021-06-29 at 3 52 40 PM" src="https://user-images.githubusercontent.com/387249/123877487-1c18ba80-d8f2-11eb-90bb-bd62afd45857.png">
