### ISSUE TITLE
Update RPill component

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#16475]

**Comment by LaurenWags** [comment]
@brave/legacy_qa test information is available here https://github.com/brave/internal/issues/780

**Comment by kjozwiak** [comment]
Verification **PASSED** on both `Win` & `Linux` using the following build:

```
Brave | 1.28.96 Chromium: 92.0.4515.115 (Official Build) beta (64-bit)
--- | ---
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
```

* verification notes can be found via https://github.com/brave/internal/issues/780#issuecomment-889510669.

Adding the `QA Pass-macOS` pass as well but more info/context can be found via https://github.com/brave/internal/issues/780#issuecomment-890003078.
