### ISSUE TITLE
Closing Brave ads tries to open Nvidia Experience's streaming tab on Windows

### ISSUE THREAD

**Issue by gaetschwartz** [brave/brave-browser#16487]
## Description 

When clicking the "Close" button on the Brave Ad Windows notification it seems to open the Stream tab on Nvidia and start a stream (This I am not sure, just an assumption, as when Instant Replay is enabled on Nvidia Experience, it displays a notification saying I need to disable Instant Replay to do this).

https://user-images.githubusercontent.com/25441359/122453984-bb5cba00-cfa2-11eb-9add-3329774a69c2.mp4

## Steps to Reproduce

   1. Have NVidia Experience installed
   2. Click the "Close" button when receiving an ad on Windows.
   3. NVidia Experience's overlay opens up on the Streaming tab 

## Actual result:
NVidia Experience's overlay opens up on the Streaming tab 

## Expected result:
Close the Ad without any of this happening

## Reproduces how often: 
Every time

## Desktop Brave version:

Brave | 1.27.69 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | Windows&nbsp;10 OS Version 2009 (Build 19043.1055)

## Android Device details:
   - Install type (ARM, x86): -
   - Device type (Phone, Tablet, Phablet): -
   - Android version: -

## Version/Channel Information:

- Can you reproduce this issue with the current release? _Haven't tried yet_
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? _Haven't tried yet_

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Well yes but that's the whole point of Ads
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

See my tweet for a video : https://twitter.com/gaetschwartz/status/1381536194505359362?s=20

Note: I made sure no keybinds are enabled for anything related to the streaming functionality of NVidia Experience if that helps.

**Comment by jonathansampson** [comment]
Thanks, @gaetschwartz! I suspect this is interpreting the notification_helper process/executable as an app you would like to stream. If you run the app manually, does it also launch the NVIDIA view? You can find the notification_helper.exe within the Brave directory in Program Files.

**Comment by gaetschwartz** [comment]
It doesn't do anything when I double click on notification_helper.exe. And I don't think it interprets the executable as an app I would like to stream because it doesn't do it with any games and it really doesn't seem like a normal behavior.

**Comment by jonathansampson** [comment]
Please also check your Game Experience settings to see if Brave or _notification_helper_ has been added to the list of _games and apps_ you would like to stream.

![image](https://user-images.githubusercontent.com/815158/122456847-a0268600-cf73-11eb-8451-d875ecd09c58.png)

**Comment by gaetschwartz** [comment]
It doesn't look like it.

![image](https://user-images.githubusercontent.com/25441359/122457133-3d9aad80-cfa6-11eb-9756-8f50aa6ab331.png)

**Comment by gaetschwartz** [comment]
Note that it happened previously and I had to reinstall Windows, once I did the issue was still here. Might help.

**Comment by gaetschwartz** [comment]
By the way Shield is to stream games to NVidia Shield, similar to Stadia or XCloud, it is not related to the Broadcast "Streaming" tab I was talking about.

**Comment by jonathansampson** [comment]
@gaetschwartz Thank you for that clarification; I was just realizing that on my end as well :) I'm not finding the _Streaming Tab_ on my system.

**Comment by gaetschwartz** [comment]
It is in the overlay. It opens the NVidia overlay. 


https://user-images.githubusercontent.com/25441359/122458298-928af380-cfa7-11eb-8c39-95e8454743f2.mp4

**Comment by jonathansampson** [comment]
I'm trying to understand what it is that invokes this app, but it seems there have been years of frustrated users reporting similar issues with this (not with Brave). 4 years ago it appears to have been really unpopular, with [Reddit posts](https://www.reddit.com/r/techsupport/comments/5mkcyl/nvidia_geforce_experience_keeps_opening_by_itself/) and even a popular Twitch streamer [raging on air](https://www.youtube.com/watch?v=4OOa_I29t2w).

I'm not able to reproduce the behavior, even after having enabled the feature locally. If you don't need this enabled, you can disable the _In-Game Overlay_ from within the [GeForce Experience settings](https://nvidia.custhelp.com/app/answers/detail/a_id/4228/~/disabling-the-geforce-experience-share-in-game-overlay). Unfortunately, it is not clear to me at this time what is triggering the overlay. When you click an ad notification, the notification_helper.exe process is briefly ran, followed by a new brave.exe process. I assume GeForce is detecting at least one of these, and asking if you'd like to stream. Really odd.

**Comment by gaetschwartz** [comment]
Hi @jonathansampson, thanks the answer, I will try to investigate a little more. Is there any way to trigger a sample Brave Ad i.e launching notification_helper.exe or else ?

**Comment by gaetschwartz** [comment]
Okay, I reinstalled NVidia Experience and it fixed it. It might be due to the order I installed the two software when reinstalling Windows; NVidia and then Brave.
