### ISSUE TITLE
Browser crashes frequently on macOS

### ISSUE THREAD

**Issue by leshik** [brave/brave-browser#1648]
## Description 
After the last update from dev channel, my browser crashes much more frequently than before.

## Steps to Reproduce
Not sure, it crashes on random pages, and doesn't after reopening. How can I help to troubleshoot the issue?

## Brave version (brave://version info)
Brave: 0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
Revision: 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS: Mac OS X

**Comment by iSOcH** [comment]
Also happens for me on windows. I did not use/update brave last week, got an update this week and have the same problem.

A site that triggers the crash quite reliably for me is https://pro.coinbase.com

**Comment by michalgcc** [comment]
Please wait for next dev release or use beta v0.55.14

**Comment by sidroast** [comment]
This happens for me with  0.56.4 as well on the same platforms:

- widows 10
- debian sid
- windows 2016 server

**Comment by bbondy** [comment]
I think this is fixed now if you upgrade to 0.57.1 for Dev Channel or 0.55.16 for Beta Channel (next build with be 0.56 on Beta)

**Comment by andrewcking** [comment]
It isn't a huge deal since I can just reopen Brave to my same exact place but I am still experiencing regular crashing on Mac OS 10.14 with Dev 57.1. It seems to occur frequently when closing tabs on pages with a lot of content.

**Comment by bbondy** [comment]
Sorry my bad above, we need a 0.57.2 to get a fix that was recently done for tab close and browser close crash.
