### ISSUE TITLE
Built-in dark theme is broken after auto-updating Brave browser beta from 1.26.x to 1.27.69 when strict fingerprinting is enabled

### ISSUE THREAD

**Issue by nastavoi** [brave/brave-browser#16496]
## Description 

Built-in dark theme is broken after updating Brave browser beta from 1.26.x to 1.27.69 (auto update) when strict fingerprinting protection is enabled. Not all of the UI elements and settings page are dark, even though dark theme is enabled (and has been enabled before the update).

(edit) At first I thought that my profile got corrupted during the update, but it's also the case with new profiles in Brave both beta and nightly.

## Steps to Reproduce

   1. Create clean profile
   2. Go to settings and enable dark theme - it's working fine
   3. Notice that fingerprinting protection is set to standard (by default)
   4. Change fingerprinting protection mode to strict
   5. Reload settings page 
   6. Settings page is themed light
   7. Reading list is themed light
   8. Pinned pages on NTP have light background 
   9. "Edit" context menu for pinned pages on NTP has light background while text is also light.
   10. Change back fingerprinting protection mode to standard again and cycle theme from dark to light to dark - 6, 7, 8, 9 looks fine again
   
## Actual result:

Some parts of the browser are light themed when fingerprinting protection is set to strict, even though dark theme is enabled.

![Bez tytułu](https://user-images.githubusercontent.com/61883414/122465616-996e3200-cfb8-11eb-9272-9f5990a435ac.png)
![brave2](https://user-images.githubusercontent.com/61883414/122633958-9b7ce180-d0db-11eb-9dbf-87b905b819fa.png)

## Expected result:
Dark theme is retained for settings page, reading list and pinned pages on NTP when fingerprinting protection is set to strict (just like with standard mode)

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:

Wersja 1.27.69 Chromium: 91.0.4472.106 (Oficjalna wersja) beta (64-bitowa)
Wersja 1.28.8 Chromium: 91.0.4472.106 (Oficjalna wersja) nightly (64-bitowa)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?

## Miscellaneous Information:

- Windows 10 21H1 19043.1052

**Comment by nastavoi** [comment]
I wasn't able to pinpoint the cause of the problem so I've created new profile and started configuring the browser from the scratch and:
Dark theme is retained **until I enable strict fingerprinting mode** in global shield settings. If I change it back to standard mode, dark theme is retained and working fine. Easily reproduced in my browser.

**Comment by arch-btw** [comment]
Can confirm having the same issue:


Version 1.28.9 Chromium: 91.0.4472.106 (Official Build) nightly (64-bit)

**Comment by nastavoi** [comment]
Similar reports from the community https://community.brave.com/t/brave-settings-page-wont-utilize-dark-mode-preference-macos-intel/260502

**Comment by rebron** [comment]
@ShivanKaul When you get a chance, I think related to https://github.com/brave/brave-core/pull/8832
cc: @petemill

**Comment by ShivanKaul** [comment]
Thanks for this report. This is actually working as intended: https://github.com/brave/brave-browser/issues/15265 - with fingerprinting mode set to strict, we have started blocking detection of dark mode by websites (`prefers-color-scheme` always report `light`). With standard fingerprinting mode, dark mode should work correctly.
Our philosophy for strict fingerprinting mode is that we try to remove as many [bits of identifiable information](https://brave.com/brave-fingerprinting-and-privacy-budgets/) as possible. Night mode is also correlated with a user's geographical region which is another strong reason to prevent websites from learning this extra piece of information for users who really care about reducing their browser fingerprint. 
cc @pes10k

**Comment by ShivanKaul** [comment]
Ah, my mistake - I see that the report is actually for Brave-specific settings page. ^ is relevant for websites, not Brave. Looking further.

**Comment by stephendonner** [comment]
I reproduced this 100% on 

Brave | 1.28.17 Chromium: 91.0.4472.114 (Official Build) nightly (64-bit)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | Windows 10 OS Version 2009 (Build 21390.2025)

Steps:
1. new profile
2. open `brave://settings/`
3. change `Light` to `Dark` under `Brave colors`
4. click on `Shields` on the left-hand `Settings` column
5. change `Fingerprinting blocking` to `Strict, may break sites`
6. reload `brave://settings/shields` (or top-level `brave://settings`)

Saw the mixed dark + light theme.

![dark-to-light](https://user-images.githubusercontent.com/387249/122964046-b8afeb00-d33b-11eb-9e87-ac0e7c50c893.gif)

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in Windows 10 x64:

```

Brave | 1.28.20 Chromium: 91.0.4472.114 (Official Build) nightly (64-bit)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

```

**Comment by Michael82548** [comment]
Can confirm. I am having the same issue. I can temporarily set it to dark by switching to light and then dark again but the page goes back to light after a refresh.

**Comment by Michael82548** [comment]
Also, if I use an extension like Darkreader, is that handled client side and not give the website any info?

**Comment by ShivanKaul** [comment]
I created https://github.com/brave/brave-core/pull/9215 to address this issue.

**Comment by ShivanKaul** [comment]
@stephendonner @GeetaSarvadnya I merged in the bugfix for this

**Comment by kjozwiak** [comment]
Adding missing `1.28.x - Nightly` milestone label as this landed in `master` which is currently on `1.28.x`.

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with build 


Brave | 1.28.27 Chromium: 91.0.4472.120 (Official Build) nightly (x86_64)
-- | --
Revision | 12c5925972cffe578ca7ca7a295e98ee7e178a7a-refs/branch-heads/4472@{#1506}
OS | macOS Version 11.4 (Build 20F71)



Steps:

1. new profile
2. opened `brave://settings/`
3. change `same as OS` to `Dark` under `Brave colors`
4. click on `Shields` on the left-hand `Settings` pane
5. change `Fingerprinting blocking` to `Strict, may break sites`
6. reload `brave://settings/shields` (or top-level `brave://settings`)

Confirmed going back and forth between `dark` and `light` themes with the above steps, I wasn't able to get into the Franken-themed state 👍 

example | example
---------|---------
<img width="1173" alt="Screen Shot 2021-06-24 at 10 06 34 AM" src="https://user-images.githubusercontent.com/387249/123304960-68b85c00-d4d4-11eb-91cf-d700918dfab0.png"> | <img width="1173" alt="Screen Shot 2021-06-24 at 10 06 42 AM" src="https://user-images.githubusercontent.com/387249/123304962-6950f280-d4d4-11eb-9f8a-8c66b3e4f250.png">

**Comment by stephendonner** [comment]
Verified `FIXED` using the inline testplan with build 


Brave | 1.27.91 Chromium: 91.0.4472.124 (Official Build) beta (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

Steps:

1. new profile
2. open `brave://settings/`
3. change `same as OS` or `Light` to `Dark` under `Brave colors`
4. click on `Shields` on the left-hand Settings column
5. change `Fingerprinting blocking` to `Strict, may break sites`
6. reload `brave://settings/shields` (or top-level `brave://settings`)

Confirmed that the theme stayed `dark`, and didn't go into a weird mixed `dark` and `light`-themed UI.

example | example
---------|---------
<img width="1053" alt="Screen Shot 2021-07-06 at 3 00 46 PM" src="https://user-images.githubusercontent.com/387249/124672107-57c00100-de6b-11eb-92ea-a8ba1996200c.png"> | <img width="1483" alt="Screen Shot 2021-07-06 at 3 01 00 PM" src="https://user-images.githubusercontent.com/387249/124672126-60b0d280-de6b-11eb-85c7-f3657f63a5a1.png">
