### ISSUE TITLE
Brave core uses a http timestamp server

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#165]
https://github.com/brave/brave-core/blob/e1a05625c04506b9d3b62a1adc1a8466a1a7fb03/script/sign_binaries.py#L14

May be we can use one of the secure time stamp servers: https://gist.github.com/Manouchehri/fd754e402d98430243455713efada710

**Comment by bsclifton** [comment]
cc: @mihaiplesa

**Comment by mherrmann** [comment]
I just tried to resolve this, but `signtool` only seems to accept `http://` URLs. This is contrary to some forum results and even some of Microsoft's documentation. I believe the reason for https:// appearing in forum results is that some forums automatically replace `http://` by `https://` in posts.

Evidence for my claim:

1. `signtool sign /t "http://timestamp.sectigo.com` works and I seed in Fiddler that it makes a network request.
2. `signtool sign /t "https://timestamp.sectigo.com` gives `SignTool Error: Invalid Timestamp URL: https://` without making any network request.
3. The same happens with `signtool sign /tr`.

I tried this with signtool from Windows SDK 10.0.22621.0 (the version currently recommended for Chromium). I also tried it both with the x64 and x86 signtool binaries.

The full command I used:

```
C:\Users\micha\dev\brave-omaha\omaha>"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe" sign /fd SHA256 /f "C:\Users\micha\dev\brave-omaha\omaha/data/OmahaTestCert.pfx" /p "test" -t "http://timestamp.sectigo.com" "scons-out\dbg-win\obj\installers\authenticode_BraveUpdateSetup.exe"
Done Adding Additional Store
Successfully signed: scons-out\dbg-win\obj\installers\authenticode_BraveUpdateSetup.exe

C:\Users\micha\dev\brave-omaha\omaha>"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe" sign /fd SHA256 /f "C:\Users\micha\dev\brave-omaha\omaha/data/OmahaTestCert.pfx" /p "test" -t "https://timestamp.sectigo.com" "scons-out\dbg-win\obj\installers\authenticode_BraveUpdateSetup.exe"
SignTool Error: Invalid Timestamp URL: https://timestamp.sectigo.com
```

I do see other HTTPS requests in Fiddler.

I'll resolve this issue via a comment that `https://` does not seem to be supported.
