### ISSUE TITLE
Inconsistent main menu capitalization

### ISSUE THREAD

**Issue by wyatt400** [brave/brave-browser#16503]
## Description 

The main menu in Brave is capitalized inconsistently with title case and sentence case. As with Chromium's **go/punctuation-standards** as well as Brave's standards, these should all be sentence case.

## Steps to Reproduce

   1. Open Brave
   2. Click the three lines at the top right corner to open the main menu

## Actual result:
**Soon, this seems to also affect "New Private window too, which should be "New private window**
![image](https://user-images.githubusercontent.com/54185618/122472982-1e842780-cf76-11eb-9d73-f043c34f6f9d.png)

Sentence and title case are mixed.

## Expected result:
Only sentence case is used, except for Brave's proper nouns such as Brave Rewards.

"Create a New Profile" should be "Create a new profile"
"Open Guest Window" should be "Open guest window"
"Report a Broken Site" should be "Report a broken site"
"New Private window" should be "New private window"

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.27.68 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **Yes**
- Can you reproduce this issue with the nightly channel? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **No**

## Miscellaneous Information:
I've opened a pull request here for it, it has a very simple solution. https://github.com/brave/brave-core/pull/8961

**Comment by wyatt400** [comment]
@rebron Any progress?

**Comment by rebron** [comment]
@wyatt400 Having a couple more people look but this looks like we're good to go. https://github.com/brave/brave-browser/issues/16982 looks like a dupe.

cc: @stephendonner @karenkliu

**Comment by wyatt400** [comment]
@rebron @srirambv Do you guys think we can get the issue fixed soon? If so, when? Because I don't know how to do this other than editing **brave-generated-resources.grd**, which has a lot of flaws.

**Comment by wyatt400** [comment]
"Create a New Profile" should be "Create a new profile"
"Open Guest Window" should be "Open guest window"
"Report a Broken Site" should be "Report a broken site"
"New Private window" should be "New private window"

**Comment by stephendonner** [comment]
Filed https://github.com/brave/brave-browser/issues/17309 for Windows and Linux, and https://github.com/brave/brave-browser/issues/17308 for macOS, to finish off/correct the above landing.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.29.50 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.1 (Build 20G80)

with the caveat that the changes are incomplete and will be addressed in #17309 for Windows and Linux, and #17308 for macOS.

Changes:
* `Report a broken site`
* `Create a new profile`
* `Open guest window`

macOS | Windows 10
--------|-------------
<img width="364" alt="macOS" src="https://user-images.githubusercontent.com/387249/128238884-c468ec42-3bc9-4b2f-99d2-893a802a698c.png"> | ![win10](https://user-images.githubusercontent.com/387249/128238889-bc6108fd-bd9d-4c7c-bae0-3e3350465e3c.png)
