### ISSUE TITLE
Unable to set Brave as default SE

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16516]
## Description 
Unable to set Brave as default SE

## Steps to reproduce 

   1. Clean install 1.28.11
   2. Set Google as default via onboarding
   3. Visit `search-dev.brave.com` & perform a search
   4. Wait for the default modal to show up
   5. Select Set as default, shows its done and dismisses the modal
   6. Check SE settings, still Google is set as default

## Actual result 
https://bravesoftware.slack.com/archives/C0816QH3R/p1624077033363800?thread_ts=1624076985.363700&cid=C0816QH3R

## Expected result
Should set Brave as default

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.28.11

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Reproduced on `Samsung S10+` running `Android 11` using `1.28.11 Chromium: 91.0.4472.114`

**Comment by kjozwiak** [comment]
@bsclifton @anthonypkeane moving this into `1.26.x` and labelling it as a `release/blocking`. Remove if you feel differently 👍

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.67 x64 build
- Verified setting as default via the modal only sets Brave Search beta as default

https://user-images.githubusercontent.com/17010094/122905873-82796800-d349-11eb-88f0-f4d75d2faa8c.mp4

--------------
Verification passed on Samsung Tab A with Android 10 running 1.26.67 x64 build
- Verified setting as default via the modal only sets Brave Search beta as default

https://user-images.githubusercontent.com/17010094/122910581-3ed52d00-d34e-11eb-88f7-d8ef180e4f78.mp4
