### ISSUE TITLE
The search engines dropdown menu doesn't display newly-added search engines properly

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#16519]
## Description 
Users can't choose a newly-added search engine from the dropdown menu at _**brave://settings/search**_ unless the newly-added search engine is selected as default at _**brave://settings/searchEngines**_. 

If users choose another search engine from the dropdown menu later, their previous search engine (the newly-added search engine from my previous sentence) will disappear from the dropdown menu, and users will have to make it default if they want to be able to choose it from the dropdown menu once again.

## Steps to Reproduce

   1. Add a search engine at _**brave://settings/searchEngines**_
   2. Check the search engines dropdown menu at _**brave://settings/search**_
   3. The newly-added search engine won't appear unless you make it default at _**brave://settings/searchEngines**_

## Actual result:

https://user-images.githubusercontent.com/20608253/122633237-265fdb00-d0e0-11eb-8d55-7c8e5caffd64.mp4

## Expected result:
Users should be able to select newly-added search engines from the dropdown menu without having to make those search engines their default.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.25.73 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | Windows&nbsp;7 Service Pack 1 (Build 7601)
JavaScript | V8&nbsp;9.1.269.36
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PrefetchPrivacyChanges,LegacyTLSEnforced,SafetyTip,WinrtGeolocationImplementation,AutoupgradeMixedContent,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity --disable-features=LangClientHintHeader,InterestCohortAPIOriginTrial,FirstPartySets,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,HandwritingRecognitionWebPlatformApi,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,EnableProfilePickerOnStartup,TextFragmentAnchor,FledgeInterestGroups,InterestCohortFeaturePolicy,SignedExchangePrefetchCacheForNavigations,NetworkTimeServiceQuerying,SubresourceWebBundles,IdleDetection,NotificationTriggers,WebOTP,SignedExchangeSubresourcePrefetch,DirectSockets,TrustTokens,TabHoverCards,SharingQRCodeGenerator,FederatedLearningOfCohorts,AutofillServerCommunication,LiveCaption --flag-switches-begin --enable-features=PrefetchPrivacyChanges,LegacyTLSEnforced,SafetyTip,WinrtGeolocationImplementation,AutoupgradeMixedContent,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,EphemeralStorage --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | aed3cac0-3f4a17df7146a73c-3f4a17dfc63a3c82-3f4a17df

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing as wontfix. This is working as expected as the list in that the drop down are the default search engines that ship with the browser. The number of search engines available via the drop down list could be exceptionally long if we add all the opensearch engines in there.

**Comment by Tonev** [comment]
Not that my comment will change anything, but I'll reply anyway.

> The number of search engines available via the drop down list could be exceptionally long if we add all the opensearch engines in there.

If only the **predefined default search engines + manually-added** search engines are display in the dropdown menu, the list won't become exceptionally long. Right now, you're limiting Brave users to seeing only the search engines the developers have selected as default  for one reason or another. There is absolutely no need to display every search engine that Brave adds at _**brave://settings/searchEngines**_, or in other words: https://community.brave.com/t/how-does-other-search-engines-added/261224.

What you're describing as "working as expected" might be true, but at the same time the feature is limiting users only to Brave's predefined "default" search engines, which could be changed for better.

Best regards.

**Comment by Tonev** [comment]
@rebron 

Is this still a `wontfix` if https://github.com/brave/brave-core/pull/9602 is the first step in implementing what I suggested?
