### ISSUE TITLE
Search suggestions don't show up for Brave Search

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16518]
## Description 
Search suggestions don't show up for Brave Search

## Steps to reproduce 

   1. Clean install 1.28.11
   2. Set Brave as default search via onboarding
   3. Open Settings -> Shields & Privacy -> `Autocomplete searches and URLs` , set it to enable
   4. Type in URL, no search suggestions are shown

## Actual result 
Search suggestions don't show up for Brave Search

## Expected result
Should show search suggestions

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.28.11

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by diracdeltas** [comment]
cc'ing @PrivacyMatters @solso because there has been a slack discussion about notifying the user about privacy implications of enabling this for Brave Search

**Comment by bsclifton** [comment]
After the auth wall was removed, this should work great - can we retest @srirambv?

Example on Desktop
![image](https://user-images.githubusercontent.com/4733304/123011965-427caa00-d376-11eb-82f3-46fad6476da2.png)

**Comment by bsclifton** [comment]
@samartnik has confirmed this works great on Android 😄 I'll close issue as this is working

cc: @diracdeltas @PrivacyMatters @solso in case you need to create a new issue (for discussion, etc)

**Comment by srirambv** [comment]
Verified suggestions show up on omnibox when setting is enabled 
![image](https://user-images.githubusercontent.com/17010094/123034725-f6674f00-d3e1-11eb-8c3e-ed0c48fc8a4e.png)

**Comment by ShintoPlasm** [comment]
Do you have a Suggest URL which we can enter in browsers like Vivaldi (which allow specifying this in the settings), please?

**Comment by petersaints** [comment]
> Do you have a Suggest URL which we can enter in browsers like Vivaldi (which allow specifying this in the settings), please?

According to the OpenSearch file included in the main Brave Search page this should work for you: https://search.brave.com/api/suggest?q=%s
