### ISSUE TITLE
Android crash after app update on Privacy settings

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#16510]
## Description 

App crashes  after updating from a previous version (<=1.25) when entering Brave Privacy Settings 

## Steps to Reproduce

   1. install a build that's less or equal with 1.25
   2. go to Settings->Privacy settings and uncheck fingerprinting 
   3. install a new build 1.26 + 
   4. the app crashes

## Expected result:

There shouldn't be any crash

## Reproduces how often: 

Easily reproduced

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.65 x64 build
- Verified steps from issue description
- Verified disable fingerprint on 1.23.76 and upgrading to 1.26.65 doesn't cause crash 
- Verified upon upgrade Fingerprint is set to Allow all globally
- Verified changing fingerprint setting globally and per site doesn't cause any crash
-----------
Verification passed on Samsung Tab A with Android 10 running 1.26.65 x64 build
- Verified steps from issue description
- Verified disable fingerprint on 1.23.76 and upgrading to 1.26.65 doesn't cause crash 
- Verified upon upgrade Fingerprint is set to Allow all globally
- Verified changing fingerprint setting globally and per site doesn't cause any crash
