### ISSUE TITLE
Cannot enable brave rewards via the Ads toggle button on the rewards page

### ISSUE THREAD

**Issue by TenaciousDan** [brave/brave-browser#16524]
## Description 

Cannot enable Ads on the brave rewards page. The toggle button immediately goes back to an OFF state when I click it to turn it on.

## Steps to Reproduce

   1. navigate to brave://rewards
   2. click on the toggle button (slider?) next to the "Ads" header when it is in OFF state
   3. 

## Actual result:

For a split millisecond, I see the state switch to ON, but then it immediately goes back to OFF state.

## Expected result:
Brave Rewards Ads are turned on and the toggle goes to and stays in an ON state.

## Reproduces how often: 

Easily reproduced. Happens every time I click on the "Ads" toggle.

## Brave version (info found on brave://version)

Brave | 1.25.73 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)
JavaScript | V8&nbsp;9.1.269.36
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Not sure where I can do this. Using default brave shield settings at the moment.
- Does the issue resolve itself when disabling Brave Rewards? 
This is the main issue, it is currently disabnled and I cannot enable it.
- Is the issue reproducible on the latest version of Chrome? 
Yes I just recently updated. There was a green update button that appeared at the top right corner of the browser.

## Miscellaneous Information:
I was having trouble seeing the rewards page at all. I had an error in the console about a missing json property. I fixed it by executing `localStorage.clear();` in the devtools console. Now I am able to see tthe brave rewards page but I cannot enablle brave rewards via the toggle.

GIF showing the problem:
<a href="https://ibb.co/zHKwNh4"><img src="https://i.ibb.co/gFsC6MR/brave-rewards-toggle-bug.gif" alt="brave-rewards-toggle-bug" border="0"></a>

**Comment by hayhurst-zz** [comment]
I have the same problem on 2 machines both Windows 10 Pro:

Brave	1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)
Revision	4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS	Windows 10 OS Version 2004 (Build 19041.1052)
JavaScript	V8 9.1.269.36
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

And:
Brave	1.25.73 Chromium: 91.0.4472.106 (Official Build) (64-bit)
Revision	574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS	Windows 10 OS Version 1809 (Build 17763.864)
JavaScript	V8 9.1.269.36
User agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

**Comment by Miyayes** [comment]
IIRC, this issue was due to invalid Rewards wallet issue (wallet cannot be decrypted, etc.). If so, this should be resolved since we removed Rewards wallet encryption awhile ago. In any case, can refile anew if this issue still exists.
