### ISSUE TITLE
read.amazon.com not working in brave

### ISSUE THREAD

**Issue by simonmadsen** [brave/brave-browser#16522]
## Description 

this was reported years ago but is closed https://github.com/brave/browser-laptop/issues/7836
still an issue though

only works for Chrome, Safari, Edge or Firefox is the prompt i get

## Steps to Reproduce
 just open read.amazon.com

## Actual result:
![image](https://user-images.githubusercontent.com/1309524/122635418-1cd87200-d0e4-11eb-8893-2a6a4874031a.png)

**Comment by ryanbr** [comment]
Just tested `read.amazon.com` and didn't see this error message. What version of Brave is being tested? Can you re-test in private window mode, with no extensions? @simonmadsen

**Comment by simonmadsen** [comment]
hmm i think you are right, im on linux, thought i had enabled updates, but i guess not,

will update soon, and if expected then sorry for the hassle

________________________________

**Comment by ryanbr** [comment]
https://gif.fanboy.co.nz/gif/readamazon.gif  (what I'm seeing)
