### ISSUE TITLE
64 bit build failure afte default search fix

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#16527]
64 bit builds fail on Android after that fix was done https://github.com/brave/brave-core/pull/9195

**Comment by kjozwiak** [comment]
@SergeyZhukovsky moved this into `1.26.x` as this was cherry-picked into https://github.com/brave/brave-core/pull/9191 & https://github.com/brave/brave-core/pull/9195 as per previous conversations 👍
