### ISSUE TITLE
Auto contribute table not refreshing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1652]
## Description 

Auto contribute table is not refresh if you browse sites and you don't have rewards settings opened.

## Steps to Reproduce

   1. enable rewards
   2. close rewards settings page
   3. visits some sites
   4. open rewards settings page

## Actual result:

Table is empty. You need to visit new site for previous pages to appear.

## Expected result:
Table should be up to date

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification Passed on

Brave	0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
Revision	9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS	Linux
