### ISSUE TITLE
Add Linux release channel install instructions to ReadTheDocs

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#1653]
Add the release channel to the dev/beta instructions here:

https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

**Comment by bbondy** [comment]
Closes since close syntax was slightly off in #1655 but it meant to close this.

**Comment by srirambv** [comment]
Verification passed on Linux. Commands in the help document works perfect.
