### ISSUE TITLE
Wallet always shows disconnected in Brave rewards

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#16533]
## Description 
Unable to get the wallet verified status on brave rewards.
Its already verified .

## Steps to Reproduce

   1. Click disconnected link from brave rewards
   2. Login successfully the uphold 
   3. But still it shows disconnected

## Actual result:
![2021-06-21_13-10-40](https://user-images.githubusercontent.com/46480489/122781596-9a130b00-d2cd-11eb-9fd8-2f15efb340ba.jpg)

## Expected result:
Wallet Verified
![Screenshot 2021-06-21 202210](https://user-images.githubusercontent.com/46480489/122782590-79978080-d2ce-11eb-89bf-dadd941042ff.png)

## Reproduces how often: 
always

## Brave version (brave://version info)

Brave | 1.25.73 Chromium: 91.0.4472.106&nbsp;(Official Build)&nbsp;(64-bit)
-- | --

**Comment by Miyayes** [comment]
Fixed here https://github.com/brave/brave-browser/issues/16269. Also contains workarounds on how to fix this now.
