### ISSUE TITLE
WebGL doesnt run 

### ISSUE THREAD

**Issue by VSNOOB** [brave/brave-browser#16549]
## Description 
I went to the webgl test website and the spinning cube didn't show up

## Steps to Reproduce
I dont know 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by TheCultLeader666** [comment]
Try disabling fingerprinting protection

**Comment by rebron** [comment]
Closing as not actionable. Not enough information.
