### ISSUE TITLE
CAPTCHA target appears on top quite often

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1654]
## Description 

CAPTCHA target appears on top very often

## Steps to Reproduce

   1. Clean profile (any branch)
   2. Enable rewards
   3. Claim grant, CAPTCHA opens up and more often than not the target triangle is at the top

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/47087404-e8e97800-d1e9-11e8-9ddb-a45b25acfc34.png)

## Expected result:
Target should be more randomized

## Reproduces how often: 

6/10 times i've seen the target being on top

## Brave version (brave://version info)

All Beta/Dev/Release

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@kjozwiak @LaurenWags noticed it too but may not too often. @btlechowski mentioned he noticed it more often on bottom than at top
cc: @davidtemkin @NejcZdovc @evq

**Comment by kjozwiak** [comment]
@evq noticed this was closed but I don't see any other issues/pr's associated with this issue. Was this created in another repo or are we just not concerned about this?
