### ISSUE TITLE
relabel search engine name to "Brave"

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#16564]
## Description 

We currently have search engine name set as `Brave Search beta` but the label looks awkward when searching from the url bar.

Search engine name should just be `Brave` and searches from url bar should show [query] - Brave Search

## Steps to Reproduce

   1. Download 1.26.67.
   2. Change default search engine to Brave Search beta from brave://settings/search
   3. Perform a search and notice [query] - Brave Search beta Search

## Actual result:
![image__42_](https://user-images.githubusercontent.com/5951041/123019675-ca1de500-d385-11eb-9746-951325e4ef0c.png)

## Expected result:
When searching from URL bar -
<img width="278" alt="Screen Shot 2021-06-22 at 6 17 31 PM" src="https://user-images.githubusercontent.com/5951041/123019836-241eaa80-d386-11eb-9ab7-e1ebd2f7e30f.png">

Manage Settings drop down -
<img width="711" alt="Screen Shot 2021-06-22 at 6 21 05 PM" src="https://user-images.githubusercontent.com/5951041/123020233-d7879f00-d386-11eb-9257-806ad47326a0.png">

Other Search engines list -
<img width="635" alt="Screen Shot 2021-06-22 at 6 22 00 PM" src="https://user-images.githubusercontent.com/5951041/123020214-cb034680-d386-11eb-9ed2-bb0cedae03ff.png">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.26.67

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.27 Chromium: 91.0.4472.120 (Official Build) nightly (x86_64)
-- | --
Revision | 12c5925972cffe578ca7ca7a295e98ee7e178a7a-refs/branch-heads/4472@{#1506}
OS | macOS Version 11.4 (Build 20F71)

Confirmed it now shows as `Brave Search` in:

Omnibox/URL bar | `brave://settings/search` | `brave://settings/searchEngines`
------------------|-----------|----------------------------------
<img width="1312" alt="Screen Shot 2021-06-24 at 9 56 27 AM" src="https://user-images.githubusercontent.com/387249/123303765-014ddc80-d4d3-11eb-8993-180b67fcce61.png"> | <img width="1312" alt="Screen Shot 2021-06-24 at 9 58 24 AM" src="https://user-images.githubusercontent.com/387249/123303769-03b03680-d4d3-11eb-88af-00804943873a.png"> | <img width="1312" alt="Screen Shot 2021-06-24 at 9 58 30 AM" src="https://user-images.githubusercontent.com/387249/123303779-04e16380-d4d3-11eb-951f-bee6f627977e.png">

**Comment by kjozwiak** [comment]
@brave/legacy_qa note that seeing `Brave Search beta` being displayed after upgrading on Android is expected as per:

![Screenshot_20210628-220042_Brave - Nightly](https://user-images.githubusercontent.com/2602313/123726523-24271a80-d85e-11eb-9433-583c7f037d11.jpg)

**Comment by kjozwiak** [comment]
Clearing `QA Pass-macOS` so we can make sure the above is working correctly once we get `1.26.x` RC's as Brave Search is pretty important 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.26.73 Chromium: 91.0.4472.124 (Official Build) (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.1052)


```
Went through two scenarios re: upgrading from `1.26.67` --> `1.26.73 Chromium: 91.0.4472.124`.
* `Scenario #1:` Brave Search isn't set as the default
* `Scenario #2:` Brave Search is set as the default

Ensured that the correct text/labels were being used for the two above scenarios. Also ensured that previously selected search engines stay as default after upgrading.

* `Scenario #1:` Brave Search isn't set as the default and upgraded to `1.26.73 Chromium: 91.0.4472.124`

Example | Example | Example | Example | Example | Example
---------|----------|---------|---------|----------|---------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.74 x64 build
**Clean Install**
- Verified `Brave Search beta` is updated to `Brave` during onboarding
- Verified selecting `Brave` during onboarding sets it as default for both normal and private tabs

![image](https://user-images.githubusercontent.com/17010094/123918585-ed472680-d97b-11eb-9539-c4791f90e178.png) |![image](https://user-images.githubusercontent.com/17010094/123918989-5af35280-d97c-11eb-804f-923d2d3dcddf.png) | ![image](https://user-images.githubusercontent.com/17010094/123918637-f9cb7f00-d97b-11eb-9e41-cf5616781c96.png) | ![image](https://user-images.githubusercontent.com/17010094/123918652-fdf79c80-d97b-11eb-8541-40500a8277e7.png)
-- | -- | -- | --

**Upgrade Install (with Brave as default)
- Verified upgrading to 1.26.74 updates the Search engine name for both standard and private tabs in selection view
- Verified upgrading to 1.26.74 retains `Brave Search beta` on Search engines overview page

![image](https://user-images.githubusercontent.com/17010094/123918708-0a7bf500-d97c-11eb-94ca-5084fc00af86.png) | ![image](https://user-images.githubusercontent.com/17010094/123918723-0ea81280-d97c-11eb-8b65-f25974979511.png)
-- | --

**Upgrade Install (with Brave not set as default)**
- Verified upgrading retains the SE list correctly and default SE
- Verified upon upgrade `Brave Search beta` is replaced by `Brave` for both standard and private tabs in selection view
--------
Verification passed on Samsung Tab A with Android 10 running 1.26.74 x64 build
**Clean Install**
- Verified `Brave Search beta` is updated to `Brave` during onboarding
- Verified selecting `Brave` during onboarding sets it as default for both normal and private tabs

![image](https://user-images.githubusercontent.com/17010094/123919356-c5a48e00-d97c-11eb-9220-c61fd8469dd0.png) | ![image](https://user-images.githubusercontent.com/17010094/123919377-c9381500-d97c-11eb-8a32-c6139af7742a.png) | ![image](https://user-images.githubusercontent.com/17010094/123919389-cc330580-d97c-11eb-8a49-9e73066fbad8.png) | ![image](https://user-images.githubusercontent.com/17010094/123919406-cf2df600-d97c-11eb-9658-9fcc1513accb.png)
-- | -- | -- | --

**Upgrade Install (with Brave as default)
- Verified upgrading to 1.26.74 updates the Search engine name for both standard and private tabs in selection view
- Verified upgrading to 1.26.74 retains `Brave Search beta` on Search engines overview page

![image](https://user-images.githubusercontent.com/17010094/123919451-d94ff480-d97c-11eb-8fce-5f126207bf53.png) | ![image](https://user-images.githubusercontent.com/17010094/123919465-dc4ae500-d97c-11eb-92d9-43f13ecf3a5c.png) 
-- | --

**Upgrade Install (with Brave not set as default)**
- Verified upgrading retains the SE list correctly and default SE
- Verified upon upgrade `Brave Search beta` is replaced by `Brave` for both standard and private tabs in selection view
