### ISSUE TITLE
attention % values for sites visited after contribution are incorrect

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1656]
## Description 
After a contribution occurs, the Auto-Contribute table is cleared as expected. However, when you visit sites and they are added back to the table, the % values aren't adding up to 100.
Found while testing https://github.com/brave/brave-browser/issues/1501

## Steps to Reproduce

   1. clean profile
   2. enable rewards
   3. claim grant
   4. Close Brave. Update reconcile stamp in ledger_state file (I used current time + 15 minutes)
   5. Reopen Brave.
   6. visit some sites so that they are added to the table (note % values add up to 100)
   7. wait for contribution
   8. make sure that table is cleared and reconcile stamp is updated
   9. Visit some sites and verify they are added to the table. Look at Attention % values.

## Actual result:
% values aren't recalculated so that they all add up to 100%
![screen shot 2018-10-17 at 10 41 03 am](https://user-images.githubusercontent.com/28145373/47094416-299cbd80-d1f9-11e8-9376-56583b80dc8a.png)

## Expected result:
% values should add up to 100%

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? n/a - code is not there at this time
- Does it reproduce on browser-laptop? n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @NejcZdovc 
cc @brave/legacy_qa for verification on other platforms

**Comment by NejcZdovc** [comment]
@kjozwiak possibly fixed with https://github.com/brave/brave-browser/issues/1701

**Comment by NejcZdovc** [comment]
@LaurenWags please re-check after hotfix 2

**Comment by kjozwiak** [comment]
> @kjozwiak possibly fixed with #1701

I couldn't check this reliably because I kept running into https://github.com/brave/brave-browser/issues/1796. @LaurenWags is on PTO till next week so I'll go through https://github.com/brave/brave-browser/issues/1796 and this issue once we get a RC 👍

**Comment by NejcZdovc** [comment]
will close and we can reopen if it's still a problem

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified STR from description (used flags for `--rewards-env=stag` and `--rewards-reconcile-interval=10` instead of manually changing the stamp)
