### ISSUE TITLE
Disable INCOGNITO and TOR Private Windows on Windows 10

### ISSUE THREAD

**Issue by NinjaShyam** [brave/brave-browser#16566]
The same issue was raised in 2019 but that doesnt work in 2021. Also I have tried the Registry Editor. The Required file locations are not to be found. i.e no Chromium folders.

OS - Windows 10 
Version - 21H1 for x64-based Systems (KB5003690)

I want to keep Parental Controls. Please Help

**Comment by rebron** [comment]
Hi @NinjaShyam You can disable Tor Private Windows here brave://settings/extensions
Disabling Private Window is a wontfix.
