### ISSUE TITLE
What Is the Schedule for When Devices Update through Sync?

### ISSUE THREAD

**Issue by danallendotcom** [brave/brave-browser#16563]
How long after saving in Brave Browser running Apple macOS before the new login information appear among the saved passwords in Brave Browser for Android, running on my phone, and on the same synch chain as the desktop?  

Seems like it takes hours.

**Comment by rebron** [comment]
Hi @danallendotcom. Are you still experiencing long delays with Sync? It shouldn't be hours, changes should occur within 45 seconds and shown in your other devices.

**Comment by danallendotcom** [comment]
Sorry for slow response.  No problems with sync for many months.  I have not timed exactly when it happens, but it is pretty close to continuous real time.  When a change happens on any device, it is synced to other devices within a minute, often less.

**Comment by AlexeyBarabash** [comment]
it seems the issue can be closed.
