### ISSUE TITLE
"Prove that you are human" challenge not working/"Hmmm, not quite" response received on all attempts

### ISSUE THREAD

**Issue by PhireSideZA** [brave/brave-browser#16561]
## Description 
When trying to claim Brave Rewards, I am unable to pass the challenge. It keeps on telling me "Hmmm, not quite" after every attempt.

## Steps to Reproduce

   1. Have Brave Rewards ready to be claimed
   2. Click on "Claim"
   3. Attempt to solve the puzzle

## Actual result:
"Hmmm, not quite" error pops up no matter how many times I try to align the logo.

## Expected result:
I expect to be able to pass the challenge successfully.

## Reproduces how often: 
Easily reproduced

## Brave version (info found on brave://version)
Brave | 1.26.67 Chromium: 91.0.4472.114 (Official Build) (arm64)
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Untested
- Can you reproduce this issue with the dev channel? Untested
- Can you reproduce this issue with the nightly channel? Untested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A, no Brave Rewards on Chrome

## Miscellaneous Information:

I have tried different combinations of DPI scaling, window zoom and resolution on macOS Big Sur 11.4, sadly to no avail. I have seen a few posts mention scaling to be a possible cause, but none of the proposed solutions have worked for me thus far.

**Comment by Miyayes** [comment]
@PhireSideZA Thanks for the report. If you still experience this with ad earnings these days in the most recent versions of Brave (as of Mar 2, 2022 we're basically at 1.35.x and 1.36.x now), let us know. But we did roll fixes for this CAPTCHA a couple versions ago, but likely later than 1.26 in your report here.
