### ISSUE TITLE
Ampersand sign ``&amp;`` is visible in the settings in Polish locale.

### ISSUE THREAD

**Issue by nastavoi** [brave/brave-browser#16567]
## Description 

Ampersand sign ``&amp;`` is visible in the settings in Polish locale.

## Steps to reproduce 

   1. Open Brave beta or nightly
   2. Open Settings 
   3. Notice that under ``Funkcje`` there is ``Brave chroni &amp; prywatność`` instead of ``Brave chroni prywatność``

## Actual result 

![Screenshot_20210623-115528_Brave - Nightly](https://user-images.githubusercontent.com/61883414/123082120-fa659200-d41e-11eb-8a84-c8cbb1df578b.jpg)

## Expected result

There should be ``Brave chroni prywatność`` under ``Funkcje``, ampersand sign ``&amp;`` shouldn't be visible.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Phone (Galaxy S10+ SM-G975F)
   - Android version: 11
   
## Brave version
Brave 1.28.20 Chromium: 91.0.4472.114 (Oficjalna wersja) canary (64-bitowa)
Wersja 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
System operacyjny Android 11; Build/RP1A.200720.012
Usługi Google Play SDK=12451000; Installed=212116046; Access=3p
JavaScript V8 9.1.269.36
Klient Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Mobile Safari/537.36

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

As I recall it was OK not so long ago.

**Comment by nastavoi** [comment]
The issue is still there, is there a more reliable way to report localization issues?

**Comment by bsclifton** [comment]
@nastavoi thanks for the report - let me track this down in Transifex and see if we can fix

**Comment by bsclifton** [comment]
OK - updated in our backend (Transifex). Next time we pull translations (Chromium 93), this fix will be included 😄 We're shooting for August 31st for the 1.29 release with Chromium 93
