### ISSUE TITLE
New Choose a wallet service modal should have Uphold privacy-policy link

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16579]
## Description 

New Choose a wallet service modal should have Uphold privacy-policy link

Credit goes to @LaurenWags who pointed this out to me - I should've caught it when verifying #16178 

## Steps to Reproduce

   1. launch Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
   2. click on the BAT icon
   3. click on `Start using Rewards`
   4. click `Skip for now`
   5. click `Done`
   6. click on `Verify Wallet` (`brave://rewards/#verify`)
   7. click `Continue >`
   8. click on `Uphold`
   9. look at the resulting change to the modal

## Actual result:

<img width="1312" alt="Screen Shot 2021-06-23 at 2 14 09 PM" src="https://user-images.githubusercontent.com/387249/123168818-5505ea80-d42d-11eb-8d91-cdafb4984183.png">

The modal correctly adds the minimum-balance-Uphold message and `Continue to login` link, but neglects adding the Uphold privacy-policy link in the bottom `Note:` paragraph.

## Expected result:

Per the mockup in the security/privacy review (https://github.com/brave/security/issues/473#issuecomment-856294892), the Choose a wallet service model should have an Uphold privacy policy link (`https://uphold.com/en/legal/privacy-policy`?)

<img width="917" alt="121093387-d1e46380-c7a1-11eb-9147-89eadc2ef230" src="https://user-images.githubusercontent.com/387249/123168864-67802400-d42d-11eb-9c77-bb8523b77b7e.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.77 Chromium: 91.0.4472.114 (Official Build) beta (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)

/cc @codybanxs @Miyayes @zenparsing

**Comment by zenparsing** [comment]
@codybanxs @Miyayes We may have discussed this previously, but with the current design we won't be able to display a link to the wallet provider's privacy policy, since the user has not yet selected a provider. If the user has the minimum BAT amount required by the provider, then they'll be taken directly to the provider's login screen when they press the button.
