### ISSUE TITLE
Text needs to be bold on dark mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16572]
## Description 
Text needs to be bold on dark mode

## Steps to reproduce 

   1. Set Device theme to dark
   2. Install Brave & open Shields global settings
   3. Open Ads/Cookies/Fingerprint menu, info text is not properly legible compared to light mode

## Actual result 

![image](https://user-images.githubusercontent.com/17010094/123102858-618a4300-d42d-11eb-9af3-fa00fcd21982.png) | ![image](https://user-images.githubusercontent.com/17010094/123102870-63ec9d00-d42d-11eb-9250-475d8f81224b.png) | ![image](https://user-images.githubusercontent.com/17010094/123102973-7a92f400-d42d-11eb-865f-03db6ad9e493.png)
-- | -- | --

## Expected result
Text should be readable

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:10
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @alexsafe @jamesmudgett

**Comment by aileenpalafox** [comment]
Hi, is this an easy-medium issue that a first timer could handle? I would like to try it out but may need some guidance.

**Comment by bsclifton** [comment]
@aileenpalafox looks like we have a fix in review; but for future reference, feel free to look into / ask for help on any issue 😄
