### ISSUE TITLE
Create pref for disabling stats ping

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#16583]
## Description

- [ ] Create a preference for disabling the stats ping

## Designs

- [ ] Add usage ping toggle
- [ ] Update text for P3A and Automatic crash reporting settings
- [ ] Move crash reporting, usage ping, and P3A toggles to be closer to each other

![image](https://user-images.githubusercontent.com/2388823/123491639-0b073b00-d5cc-11eb-849d-b2a7e04a3c4a.png)

## Assets
Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/?node-id=808%3A7122

**Comment by keur** [comment]
We will add QA/Yes when it's added to the settings page. I believe @diracdeltas will put it there

**Comment by keur** [comment]
Test Plan
-----------

1. Launch the browser. Using Wireshark ensure that usage ping is sent
2. Go to settings and opt out of the usage ping. Restart browser
3. Move time forward 1+ day and launch browser
4. Ensure usage ping is not set
5. Go to settings and opt into usage ping. Restart browser
6. Ensure usage ping is sent.

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with build 


Brave | 1.28.60 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 12.0 (Build 21A5268h)

Steps:

1. Launched Brave. Using Charles Proxy, ensured that usage ping is sent to `laptop-updates.brave.com`.
2. Went to `brave://settings` and opted out of the usage ping. Restarted Brave.
3. Moved time forward 1+ day and launched Brave.
4. Ensured usage ping was not sent, via Charles Proxy.
5. Went to `brave://settings` and opt into usage ping. Restarted Brave.
6. Ensured usage ping is sent, via Charles Proxy

step 1 | step 4 | step 6
------|--------|-------
<img width="1659" alt="Screen Shot 2021-07-07 at 4 24 31 PM" src="https://user-images.githubusercontent.com/387249/124841353-e3a45c80-df41-11eb-998a-5bdd5bffd460.png"> | <img width="1680" alt="Screen Shot 2021-07-08 at 4 27 47 PM" src="https://user-images.githubusercontent.com/387249/124841292-bce62600-df41-11eb-8371-db0475b227d3.png"> | <img width="1680" alt="Screen Shot 2021-07-08 at 4 29 20 PM" src="https://user-images.githubusercontent.com/387249/124841228-99bb7680-df41-11eb-82a1-c94d034a2e3c.png">

**Comment by srirambv** [comment]
@keur There is no UI Setting for this change on Android. I added Android specific implementation issue #17158, also removing Android label from this one
