### ISSUE TITLE
Discord not generating QR code login

### ISSUE THREAD

**Issue by WilliamShockleyfake** [brave/brave-browser#16587]
Discord not generating QR code for login. I deleted everything cookies, history all data. Still same keeps loading 

However works in Mozilla latest as shown in screeshots 

![](https://i.imgur.com/kVwHyTA.jpg)

**Comment by rebron** [comment]
@WilliamShockleyfake Can you refresh the page? I'm not able to reproduce on either windows or macOS 1.26.67.

**Comment by Rizr09** [comment]
@rebron It works for me
![Capture](https://user-images.githubusercontent.com/75122686/123371260-9c19ea00-d5ab-11eb-9ec5-d156cfba51f3.PNG)

**Comment by rebron** [comment]
Closing as stale and works for me.
