### ISSUE TITLE
Deleting Password from the Key icon in the address bar does not work

### ISSUE THREAD

**Issue by iamakhildabral** [brave/brave-browser#16599]
## Description 
Deleting Password from the Key icon in the address bar does not work, we have to delete them going into settings >> password section instead from the Address bar directly 

## Steps to Reproduce

   1. Go to any website for which you have already saved password in the browser.
   2. Go to the Key Icon in the Right hand side of the address bar.
   3. Try deleting one of the saved password come to the main page by clicking on then  trash button and click on the Key icon again to see whether the password has been deleted or not

## Actual result:
Deleting Password does not work and it stays in the browser.

## Expected result:
Deleting the password from the address bar should have delete the credentials.

## Reproduces how often: 
Easily reproduced/

## Brave version (info found on brave://version)
1.26.67 Chromium: 91.0.4472.114 (Official Build) (x86_64

## Version/Channel Information:
1.26.67 Chromium: 91.0.4472.114 (Official Build) (x86_64

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:
I think this exists across all the chromium builds and browsers.

Sample Image:
![image](https://user-images.githubusercontent.com/34294298/123315263-267d3200-d549-11eb-8874-395aa9373e83.png)

After Deleting:
![image](https://user-images.githubusercontent.com/34294298/123315390-4d3b6880-d549-11eb-86c9-9e211c0ec7ac.png)

**Comment by rebron** [comment]
@iamakhildabral Looks like deleting password from the key icon works and verified by deleting a password from that dialog and checked that it's gone in brave://settings/passwords

Going to close this as works for me but please reopen @iamakhildabral if you're still encountering this issue.
