### ISSUE TITLE
Android permission crash from logs

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#16596]
## Description 

```
java.lang.NullPointerException: 
  at androidx.core.content.ContextCompat.checkSelfPermission (ContextCompat.java:554)
  at org.chromium.chrome.browser.brave_stats.BraveStatsUtil.hasWritePermission (BraveStatsUtil.java:210)
  at org.chromium.chrome.browser.shields.BraveShieldsHandler$3.onClick (BraveShieldsHandler.java:429)
```

## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:

No uncaught exceptions 

## Reproduces how often: 

No steps to reproduce

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Labelled this as `QA/No` after speaking with @AlexeyBarabash. Crash was pulled from the GPS Console so we don't have any way of reproducing.
