### ISSUE TITLE
Open using IPFS badge always shown when using IPFS gateway

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16606]
## Description 

`Open using IPFS` badge always shown when using IPFS gateway

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `ipns://brantly.eth`
   4. click on `Public Gateway`
   5. in the resulting page (`https://brantly-eth.ipns.dweb.link/#/`), note the presence of the `Open using IPFS` badge in the URL bar
   6. click on it

## Actual result:

![ipfs-gateway-open](https://user-images.githubusercontent.com/387249/123330257-a3c98800-d4f2-11eb-8dc4-2c46f385389d.gif)

## Expected result:

Unsure

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.27 Chromium: 91.0.4472.120 (Official Build) nightly (x86_64)
-- | --
Revision | 12c5925972cffe578ca7ca7a295e98ee7e178a7a-refs/branch-heads/4472@{#1506}
OS | macOS Version 11.4 (Build 20F71)

/cc @lidel @spylogsster

**Comment by spylogsster** [comment]
@stephendonner it seems ok for gateways https://github.com/brave/brave-browser/issues/13609#issuecomment-786753724

**Comment by stephendonner** [comment]
> @stephendonner it seems ok for gateways [#13609 (comment)](https://github.com/brave/brave-browser/issues/13609#issuecomment-786753724)

That it shows up the 1st time seems fine to me, as it goes from `ipns://brantly.eth` to `https://brantly-eth.ipns.dweb.link/#/` when you click `Open using IPFS` when using the Gateway option; loading the same URL over and over doesn't make sense to me, though.

**Comment by lidel** [comment]
I think we should hide the badge when a third-party Gateway is used. 

Agree with @stephendonner that showing it makes sense only when local node is running (when you use Gateway you DON'T really "Open using IPFS", but delegate trust to a third-party)

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan on build 


Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)



Steps:
1. new profile
2. launched Brave
3. loaded `ipns://brantly.eth`
4. clicked on `Public Gateway`
5. confirmed I no longer got `Open using IPFS` badges

example | example
---------|---------
<img width="1748" alt="Screen Shot 2021-07-06 at 4 14 13 PM" src="https://user-images.githubusercontent.com/387249/124677717-e5085300-de75-11eb-95ac-4423a4e27829.png"> | <img width="1748" alt="Screen Shot 2021-07-06 at 4 14 20 PM" src="https://user-images.githubusercontent.com/387249/124677722-e6d21680-de75-11eb-9a4d-4859c28a9c1e.png">


Also tried with `https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR` (badge) -> `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/` (no badge) and `https://en.wikipedia-on-ipfs.org/wiki/` (badge) -> `ipns://en.wikipedia-on-ipfs.org/wiki/` (no badge)

badge | no badge | badge | no badge
-------|----------|--------|----------
<img width="1748" alt="Screen Shot 2021-07-06 at 4 20 26 PM" src="https://user-images.githubusercontent.com/387249/124677879-36184700-de76-11eb-939e-a6d319eee706.png"> | <img width="1748" alt="Screen Shot 2021-07-06 at 4 20 30 PM" src="https://user-images.githubusercontent.com/387249/124677883-39133780-de76-11eb-87c3-7c5d2402d34a.png"> | <img width="1748" alt="Screen Shot 2021-07-06 at 4 20 33 PM" src="https://user-images.githubusercontent.com/387249/124677887-39abce00-de76-11eb-9c9d-f1ca88135fc2.png"> | <img width="1748" alt="Screen Shot 2021-07-06 at 4 20 37 PM" src="https://user-images.githubusercontent.com/387249/124677889-3a446480-de76-11eb-9a62-b994f57e451a.png">
