### ISSUE TITLE
Chrome browser?

### ISSUE THREAD

**Issue by I-Cat** [brave/brave-browser#16602]
## Steps to Reproduce

   1.  Go to about brave browser
   2. Brave is showing it is chrome
   3. 
![Screenshot_20210624_154111_com brave browser_nightly](https://user-images.githubusercontent.com/68921721/123322916-d8454000-d502-11eb-936f-d4f9db5b902d.jpg)

## Actual result:

![Screenshot_20210624_154111_com brave browser_nightly](https://user-images.githubusercontent.com/68921721/123322916-d8454000-d502-11eb-936f-d4f9db5b902d.jpg)

## Expected result:
Well it should say brave browser I would thunk

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Side note I am uninstalling it since it's a chrome browser as I as looking for something that is not google related because of privacy reasons.

**Comment by Aayaan-Sahu** [comment]
I'm not a dev, but brave is built upon chromium, so that's probably all there is to it. I don't think it's an issue.

**Comment by srirambv** [comment]
[Chromium **not same as** Chrome](https://www.diffen.com/difference/Chromium_vs_Google_Chrome). Brave is built on Open Source Chromium and not on Google Chrome
