### ISSUE TITLE
Wrong option titles

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16618]
## Description 

Titles are cropped on the IPFS setting page

![image](https://user-images.githubusercontent.com/2965009/123463719-841a8880-d5f4-11eb-8c4f-d5821c134f84.png)

## Steps to Reproduce

open ipfs settings on windows

## Actual result:

titles are cropped 

## Expected result:
titles are not cropped, full title visible

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.28.34 Chromium: 91.0.4472.124 (Official Build) nightly (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2009 (Build 21390.2025)

Steps:
1. new profile
2. loaded `brave://settings/ipfs`
3. checked the appearance of the prefs/options

![ipfs-settings-fixed](https://user-images.githubusercontent.com/387249/123723072-7d7f5180-d83e-11eb-9f52-bee5ccce401b.png)
