### ISSUE TITLE
Make Rewards settings page responsive

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16619]
## Description

Currently, the Rewards settings page is not responsive to different window sizes.

**Related:**
https://github.com/brave/brave-browser/issues/20417

## Solution

Make responsive. For example, we can place top-level components into a CSS grid, etc.

**Comment by zenparsing** [comment]
When making the Rewards page responsive, we should also take into account the various dialogs (some of which have a wide, 2-column layout).

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.44.85 Chromium: 105.0.5195.127 (Official Build) beta (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 12.6 (Build 21G115)
```
