### ISSUE TITLE
Remove extra subtitle in tipping banner text area

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#1661]
The tipping banner text shows Welcome! and Hello! due to an editing mistake. 

This PR fixes the issue: https://github.com/brave/brave-core/pull/665

**Comment by bbondy** [comment]
@bradleyrichter pls use syntax:

Fix https://github.com/brave/brave-core/pull/665

in the PR description so when things are landed it will auto close the associated issue.

Thanks!

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/47176938-e7e94100-d2e4-11e8-8507-d8aeb438cb16.png)
![image](https://user-images.githubusercontent.com/17010094/47176976-094a2d00-d2e5-11e8-84eb-c6108d6019dd.png)
