### ISSUE TITLE
move Tor settings to `Privacy and security` section (brave://settings/privacy)

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#16624]
## Description 
The extensions section of brave://settings is overused and cluttered. 

Move Tor settings into Privacy and security section.
brave://settings/privacy

## New and Expected Design
![image-2](https://user-images.githubusercontent.com/5951041/178523920-c37ff64b-e2d7-4b95-b3f3-4d1e2dffa94d.png)

## Existing Design 
<img width="716" alt="Screen Shot 2021-06-25 at 12 54 32 PM" src="https://user-images.githubusercontent.com/5951041/123478609-83620200-d5b4-11eb-956d-216d998f1ea0.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2187%3A60437

**Comment by aguscruiz** [comment]
Updated design here:
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2187%3A60437

**Comment by rebron** [comment]
Fixed with https://github.com/brave/brave-core/pull/13290

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.44.92 Chromium: 105.0.5195.136 (Official Build) beta (64-bit)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Windows 10 Version 21H2 (Build 19044.2006)

Settings/UI

Checking Bridges
