### ISSUE TITLE
Increase 7-day ad history to 30-day ad history

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16627]
## Description

Currently, ad history contains up to 7 days of ads. This should be increased to 30 days.

## Solution

* Increase ad history list to contain 30 days of history. 
* Change hyperlink text as needed

cc: @tmancey @lukemulks

**Comment by himanshu007-creator** [comment]
Hi, I would like to work on this issue. Please guide me further where to make changes. 
BTW i am really enjoying Brave🎉

**Comment by enxio27** [comment]
This is a great idea!  It will help a lot with trouble-shooting.  Please also extend this feature to Android.

**Comment by tmancey** [comment]
@himanshu007-creator That's great you are enjoying Brave. Apologies, I just noticed you would have liked to work on this.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator That's great you are enjoying Brave. Apologies, I just noticed you would have liked to work on this.

Nevermind, I'll find some other low hanging fruit (easy issue)🙂

**Comment by stephendonner** [comment]
Setting as `QA/Blocked` because we should wait to verify after https://github.com/brave/brave-core/pull/9543 lands in `1.28.x`; without that fix, days are capped at `7` (not just a cosmetic UI change 👍 ).

**Comment by stephendonner** [comment]
### Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/9300 with build

| Brave    | 1.28.96 Chromium: 92.0.4515.115 (Official Build) beta (x86_64) |
| -------- | ------------------------------------------------------------ |
| Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4} |
| OS       | macOS Version 11.5.1 (Build 20G80)                           |

Also used for the migration cases were


| Brave    | 1.27.109 Chromium: 92.0.4515.115 (Official Build) (x86_64)   |
| -------- | ------------------------------------------------------------ |
| Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4} |
| OS       | macOS Version 11.5.1 (Build 20G80)                           |

| Brave    | 1.26.77 Chromium: 91.0.4472.164 (Official Build) (x86_64)    |
| -------- | ------------------------------------------------------------ |
| Revision | 541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569} |
| OS       | macOS Version 11.5.1 (Build 20G80)                           |

#### `1.28.96`:

Steps:

1. new profile
2. launched Brave
3. enabled `Rewards`
4. viewed ads
5. loaded `brave://rewards`
6. confirmed it says `30-day Ads History` and lists my ads
7. click on the above link
8. confirmed the popup reads `Ads you've received in the past 30 days`
9. shut down Brave
10. forwarded system clock 30 days
11. launched Brave
12. confirmed there's no ad history
13. shut down Brave
14. from today's date, forwarded system clock 29 days
15. launched Brave
16. confirmed `30-day ads history` returned

steps 6-8 | steps 6-8 | step 12 | step 16 | step 16
---------|----------|----------|----------|---------
<img width="1753" alt="Screen Shot 2021-07-29 at 12 41 56 PM" src="https://user-images.githubusercontent.com/387249/127565951-fcfb59fb-b35a-40f3-99d8-e929aa18f675.png"> | <img width="1753" alt="Screen Shot 2021-07-29 at 12 42 00 PM" src="https://user-images.githubusercontent.com/387249/127565955-265d23c9-06b7-4b69-b114-15ef9c175c7c.png"> | <img width="1677" alt="Screen Shot 2021-07-29 at 2 11 00 PM" src="https://user-images.githubusercontent.com/387249/127566400-fee5069a-24e7-467b-973a-d2c8bb6107d8.png"> | <img width="1753" alt="Screen Shot 2021-07-29 at 12 41 56 PM" src="https://user-images.githubusercontent.com/387249/127566490-bd1556fb-53c6-466c-9fdb-fef6add4b92e.png"> | <img width="1753" alt="Screen Shot 2021-07-29 at 12 42 00 PM" src="https://user-images.githubusercontent.com/387249/127566494-da73954a-bc6b-44dd-a9ab-dbd2a7678e8f.png">


#### `1.27.109` and `1.26.77`:

Steps (for both):

1. new profile
2. launched Brave
3. enabled `Rewards`
4. viewed ads
5. loaded `brave://rewards`
6. confirmed it says `7-day Ads History` and lists my ads
7. upgraded builds to `1.28.96`
8. launched Brave
9. loaded `brave://rewards`
10. confirmed and clicked on the `30-day Ads History` link
11. confirmed it says `30-day Ads History` and lists my ads


step 6 | step 6 | step 10 | step 11
-------|--------|------------|----
<img width="1753" alt="Screen Shot 2021-07-29 at 12 40 25 PM" src="https://user-images.githubusercontent.com/387249/127566868-dcbcbde3-09c3-4959-831b-6074007e5c27.png"> | <img width="1753" alt="Screen Shot 2021-07-29 at 12 40 28 PM" src="https://user-images.githubusercontent.com/387249/127566870-462f42cc-58a0-40ba-921b-5066722df1f6.png"> | <img width="1312" alt="Screen Shot 2021-07-29 at 12 49 28 PM" src="https://user-images.githubusercontent.com/387249/127566872-977153dd-4285-451c-a2d9-e1e640740a6a.png"> | <img width="1312" alt="Screen Shot 2021-07-29 at 12 49 31 PM" src="https://user-images.githubusercontent.com/387249/127566873-8697d571-189e-4aad-8ebb-3f26cfcd6a0e.png">
