### ISSUE TITLE
Allow for change in download location

### ISSUE THREAD

**Issue by S-Spektrum-M** [brave/brave-browser#16626]
## Description 
In the windows version of Brave Browser there is no way of changing the install location. For example: If I would like to install Brave to **"D:/ProgramFiles"** rather than **"C:/ProgramFiles"** I am out of luck.

## Steps to Reproduce

   1.  Install the brave browser on Windows 10. 

## Actual result:

![image](https://user-images.githubusercontent.com/52438929/123497788-40b81e00-d5e4-11eb-8996-3907ef815b87.png)

## Expected result:
The program should prompt you with an install location as Vivaldi does:
![image](https://user-images.githubusercontent.com/52438929/123497819-72c98000-d5e4-11eb-8dca-5f609f3f7ec2.png)

## Reproduces how often: 

Reproduces on every Windows 10 install

## Brave version (brave://version info)

Brave	1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)
## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Unsure
- Can you reproduce this issue with the nightly channel? 
Unsure

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? 
Unsure
- Does the issue resolve itself when disabling Brave Rewards? 
Unsure
- Is the issue reproducible on the latest version of Chrome? 
Yes

## Miscellaneous Information:

NA

**Comment by bsclifton** [comment]
Thanks for the report @S-Spektrum-M! We have this tracked with https://github.com/brave/brave-browser/issues/598 and you can subscribe there for updates.  I'll close this issue as a duplicate
