### ISSUE TITLE
Multiples ads (cosmetic) on 01net.com

### ISSUE THREAD

**Issue by Furax-31** [brave/brave-browser#16629]
## Description  

Multiples ads (cosmetic) on 01net.com (mobile version only)

## Steps to reproduce 

   1. Go to ```01net.com```

## Actual result  
![image](https://user-images.githubusercontent.com/61207108/123507368-43a92200-d669-11eb-86ef-3fbabffc883c.png)
![image](https://user-images.githubusercontent.com/61207108/123507376-4d328a00-d669-11eb-9f24-878b72cf13d7.png)
![image](https://user-images.githubusercontent.com/61207108/123507381-502d7a80-d669-11eb-9145-2eeca9fa075b.png)
![image](https://user-images.githubusercontent.com/61207108/123507384-528fd480-d669-11eb-9165-3b3ca4d6e77b.png)

## Expected result 
There should be no empty space

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version: 
Nightly 1.28.31

**Comment by ryanbr** [comment]
Enabling Cosmetic Filtering via `brave://flags` and add `01net.com##.mrf-adv__wrapper` into `brave://adblock` as a temp option. Just waiting on Adguard French filtering approval (via brave://adblock). @Furax-31
