### ISSUE TITLE
upwork.com captcha issue

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#16630]
Have you searched for similar issues? Yes.
 
## Description 
That bloody Captcha thing keeps showing up whenever I use the platform and after completing the Captcha, the Captcha simply refreshes again and again and again, non-stop.

## Steps to Reproduce

   1. Go to upwork.com see if you're promoted with a Captcha after perusing the site, see if it shows up. 

I don't know if it'll be easy for you to reproduce because I didn't immediately see it. Perhaps saving more than a dozen tabs of the site in Bookmarks and then opening them all up from bookmarks, after closing the browser of course may reproduce it.

   
## Actual result:
![Screenshot_20210626_194500](https://user-images.githubusercontent.com/31957540/123522798-a0cbc480-d6b7-11eb-9809-1c756f8c80a7.png)

## Expected result:
Either not show up at all via direct communication between yourselves and UpWork or simply just go to the page of origin or the page it was supposed to transfer to before the Captcha showed up.

## Reproduces how often: 

Intermittent issue. It doesn't happen always but it does occur often.

## Brave version (brave://version info)
Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit) (openSuse)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes.

## Miscellaneous Information:
I've been a long-time user of Brave, literally from the Muon days and to be quite frank, the browser has pi**ed me of big time on numerous occasions, I left the browser I think once during the Muon version and I think once shortly after the Core version. 

If you'd like some constructive criticism without coming across as disrespectful, I honestly believe having an actual long-time user (not implying myself) as a key product lead would do the company some good. I understand BAT/Rewards was/is an integral part of the software but it has become obvious that fundamental aspects to the browsing experience and productivity have long been neglected though you may disagree and it is likely to peeve of a lot of users, it is actually peeving of a lot of users. It was so nice giving BATs to content creators that I appreciate and it's going to be a pity bot being to able to support as easily as it was with the Tips feature but for someone who greatly needs productivity, minimal impact on memory and ease of use, Brave still seems far of from this. Brave occasionally provides these simple questionnaires and I was thinking maybe it might be a good idea to promote issue one as you typically do on brave browsers but also on brave.com for those of not using brave on what Brave Inc can do in the near future to make the software optimally useful to users, grouping those ideas together and radically implementing lets say the top four or five in the best manner possible. Anyway, that's my two bits; I've just been stuck with Brave as my only browser for so long I think it's necessary for me let it go soon. Thanks for reading my comments.

**Comment by ryanbr** [comment]
Hey @NumDeP 

The site uses ParameterX fingerprinting which is blocked by Easyprivacy, rather than ignoring the the blocked domains. ParameterX will display this error message. it's not a Brave specific issue it'll effect uBO also.

Not sure if this will work, try adding `upwork.com##+js(acis, _pxAppId)` into `brave://adblock`

**Comment by NumDeP** [comment]
@ryanbr I know it must be really simple to add a few lines here and there to alleviate issues cause by Shields but for the average person that isn't technically savvy, that doesn't have community or Github account because frankly it's a waste of time for them and us; it should work out of the box for us without having to fiddle about with it. It's integral that something more intelligent be developed.

Furthermore, if I were to install brave on a new system or lets say during the release of an entperize version, how are we to remember all of this and manage all of this, we shouldn't have to.

**Comment by arch-btw** [comment]
Having the same issue with any recaptcha.

For example when accessing egifter.com with a vpn.

![2021-06-27_09-26](https://user-images.githubusercontent.com/57669023/123552187-d8735480-d729-11eb-8043-746e26938cc2.png)

**Comment by arch-btw** [comment]
Not sure if the screenshot worked. Here's the error message:

> Uncaught DOMException: Blocked a frame with origin "https://geo.captcha-delivery.com" from accessing a cross-origin frame.
    at Object.blocker.install (<anonymous>:77:17)
    at HTMLIFrameElement.get [as contentWindow] (<anonymous>:128:19)

**Comment by arch-btw** [comment]
Video:

![brave](https://user-images.githubusercontent.com/57669023/123552993-bda2df00-d72d-11eb-94e6-f16132ef5457.gif)

**Comment by Immow** [comment]
I have the exact same problem on https://www.pixiv.net/en/

Could not connect to the reCAPTCHA service. Please check your internet connection and reload to get a reCAPTCHA challenge.

**Comment by ryanbr** [comment]
From the original report, This isn't a captcha issue guys @Immow @arch-btw

**Comment by ryanbr** [comment]
> @ryanbr I know it must be really simple to add a few lines here and there to alleviate issues cause by Shields but for the average person that isn't technically savvy, that doesn't have community or Github account because frankly it's a waste of time for them and us; it should work out of the box for us without having to fiddle about with it. It's integral that something more intelligent be developed.

I can implement any fix on Brave's side, to avoid users needing to find a work around. Does my suggested code work?

**Comment by NumDeP** [comment]
I pasted both of them but it didn't work, I thought it did but having used it recently with quite a few tabs open, the same issue showed up again.

Recently I changed the setting of 'On start-up' to 'Continue where you left off' and I put the computer to sleep and hibernate multiple times and it didn't seem to cause an issue when I started up Brave. However the last time the same problem occurred and it's so annoying because all the tabs you have open become contaminated if you know what I mean.

If you tried to replicate the same issue in Firefox with the same amount of tabs and that Cpatcha shows up, you literally just have to press the checkbox (without completing the image selection) and that's all and it immediately refreshes the original page and doesn't affect the other tabs at all.

**Comment by rebron** [comment]
@NumDeP and @Immow still seeing captchas on upwork or pixiv.net?

**Comment by Immow** [comment]
> @NumDeP and @Immow still seeing captchas on upwork or pixiv.net?

I just checked but did not get the captcha thingy so I can't say?

**Comment by rebron** [comment]
Closing per last comment. Please re-open if still an issue.
