### ISSUE TITLE
Update Ecosia search parameters

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#16639]
## Description 
Ecosia has an `add Ecosia` button on the search index page. This shouldn't be showing for Brave users who either have Ecosia set as their default search engine or do a search with the built in Ecosia engine (ex: `:e` shortcut keyword)

## Steps to Reproduce
   1. Fresh install
   2. Set Ecosia as default search engine
   3. Search in omnibox 

## Actual result:
SERP has a `Add Ecosia to Chrome` button

## Expected result:
SERP should not show `Add Ecosia to Chrome` button

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.1052)


```

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.74 x64 build
**Clean Install**
- Verified able to set Ecosia as default via onboarding and is set for both normal and private tabs
- Verified with Ecosia set as default, performing a search via omnibar adds `&addon=brave` to the query
- Verified with Brave Search set as default, visiting `https://ecosia.org` shows the `Add to Android` button on homepage
- Verified once `&addon=brave` is set, visiting `https://ecosia.org` replaces the `Add to Android` button with `Share Ecosia` button
- Verified with Ecosia set as default, visiting `https://ecosia.org` and performing a search on the page doesn't append `&addon=brave` parameter to the query string

**Upgrade Install (from `1.26.71` to `1.26.74`)**
- Verified upgrading doesn't reset default search engine that is set previously
- Verified with Brave Search set as default, upgrading and visiting `https://ecosia.org` shows the `Add to Android` button
- Verified with Ecosia set as default, upgrading and doing a search via omnibar appends `&addon=brave` parameter to the query string
- Verified upgrading and visiting `https://ecosia.org` and performing a search on the webpage doesn't append `&addon=brave` parameter to the query string

![image](https://user-images.githubusercontent.com/17010094/123910801-dc45e780-d972-11eb-91ba-e9ae9b0f05d1.png) | ![image](https://user-images.githubusercontent.com/17010094/123911166-55453f00-d973-11eb-83ec-ec9306ca0331.png) | ![image](https://user-images.githubusercontent.com/17010094/123911184-59715c80-d973-11eb-8251-3c25af7bcb29.png)
-- | -- | --

-------------
Verification passed on Samsung Tab A with Android 10 running 1.26.74 x64 build
**Clean Install**
- Verified able to set Ecosia as default via onboarding and is set for both normal and private tabs
- Verified with Ecosia set as default, performing a search via omnibar adds `&addon=brave` to the query
- Verified once `&addon=brave` is set, visiting `https://ecosia.org` doesn't show any button
- Verified with Brave Search set as default, visiting `https://ecosia.org` shows the `Add to Android` button on homepage
- Verified with Ecosia set as default, visiting `https://ecosia.org` and performing a search on the page doesn't append `&addon=brave` parameter to the query string

**Upgrade Install (from `1.26.71` to `1.26.74`)**
- Verified upgrading doesn't reset default search engine that is set previously
- Verified with Brave Search set as default, upgrading and visiting `https://ecosia.org` shows the `Add to Android` button
- Verified with Ecosia set as default, upgrading and doing a search via omnibar appends `&addon=brave` parameter to the query string
- Verified upgrading and visiting `https://ecosia.org` and performing a search on the webpage doesn't append `&addon=brave` parameter to the query string

![image](https://user-images.githubusercontent.com/17010094/123912264-ba4d6480-d974-11eb-94b0-7f38c95cc984.png) | ![image](https://user-images.githubusercontent.com/17010094/123912280-bfaaaf00-d974-11eb-97f0-82dd9ce5ad60.png) | ![image](https://user-images.githubusercontent.com/17010094/123912291-c33e3600-d974-11eb-9fab-836a73c28c28.png)
-- | -- | --
