### ISSUE TITLE
Service key should be added to requests being parsed by BraveRequestHandler

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#16633]
## Description 
Requests to download extensions use the `BraveRequestHandler`. Service key should be present in order to access the go-update server.

## Test Plan
Specified here: https://github.com/brave/internal/issues/784

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan in https://github.com/brave/internal/issues/784 with build 


Brave | 1.28.46 Chromium: 92.0.4515.70 (Official Build) nightly (x86_64)
-- | --
Revision | 2df01a82398e62190b2aae01aaad7ca3d47aba01-refs/branch-heads/4515@{#923}
OS | macOS Version 11.4 (Build 20F71)

https://github.com/brave/internal/issues/784#issuecomment-872613751
