### ISSUE TITLE
Assertion Failed When Building Release

### ISSUE THREAD

**Issue by poisson-aerohead** [brave/brave-browser#16632]
## Description 

Upon building Release, I do not get very far and there is a fatal error due to a failed assertion.

## Steps to Reproduce

`$ npm run build Release`

## Actual result:

```
ERROR at //brave/browser/brave_stats/sources.gni:13:3: Assertion failed.
  assert(brave_stats_updater_url != "")
  ^-----
See //brave/browser/sources.gni:10:1: whence it was imported.
import("//brave/browser/brave_stats/sources.gni")
^-----------------------------------------------
See //chrome/browser/BUILD.gn:2458:3: whence it was imported.
  import("//brave/browser/sources.gni") sources += brave_chrome_browser_sources deps += brave_chrome_browser_deps public_deps += brave_chrome_browser_public_deps defines += brave_chrome_browser_defines
  ^-----------------------------------
See //chrome/BUILD.gn:1312:5: which caused the file to be included.
    "//chrome/browser",
    ^-----------------
```

## Expected result:

A successful configuration and build.

## Reproduces how often: 

Every time, it is evidently a ninja issue.

## Brave version (info found on brave://version)

Latest update, a clean install with npm run init.

## Other Additional Information:

For what its worth, here is what the relevant section of src/brave/browser/brave_stats/sources.gni looks like:

```
import("//brave/components/brave_referrals/buildflags/buildflags.gni")

declare_args() {
  brave_stats_updater_url = ""
}

if (is_official_build) {
  assert(brave_stats_updater_url != "")
}
```

The only other hit a grep for brave_stats_updater_url through src/brave returned is at src/brave/build/commands/lib/config.js

**Comment by shhnjk** [comment]
I have same issue on Windows :(

**Comment by fmarier** [comment]
What if you put the following in your `~/.npmrc` (or the equivalent on Windows)?
```
brave_stats_updater_url=https://example.com
```

**Comment by shhnjk** [comment]
I did that, and how I see same problem with `brave_sync_endpoint`. I also set that to `https://example.com`. But now I get same problem with `brave_variations_server_url`.

I tried to build Release with Linux. Same problem :(

**Comment by shhnjk** [comment]
Looks like this is a won't fix per https://github.com/brave/brave-browser/issues/13750

**Comment by poisson-aerohead** [comment]
Thanks I get it. That is a bit wonky. It is not clear to me why the instructions in the README would indicate that you can just build a release version if that is not really the case. I just want to build the browser and install it on my machine and it has turned out to be rather difficult. Usually you can just sync a project from github and follow the instructions to build it unmodified from the master branch and it will work as long as you make sure you have all the build dependencies ahead of time.

**Comment by bsclifton** [comment]
Release build is absolutely supported; Official build is not though, as that requires Brave Software, Inc assets like certificates, keys, credentials, etc

There are going to be a list of items you'll need to set in your `~/.npmrc`:
```
brave_sync_endpoint=https://example.com
brave_stats_updater_url=https://example.com
brave_variations_server_url=https://example.com
safebrowsing_api_endpoint=example.com
```

There may be others; each time you run into one (ex; variations server mentioned above), you can add them to this list and put a dummy value. Providing dummy values will cause a problem when running. If you want to be able to put up a real value, you'll need to create an instance of that server type. For example:
- stats/update: https://github.com/brave/vault-updater
- sync server: https://github.com/brave/go-sync
- component updater: https://github.com/brave/go-update
- variations server: https://github.com/brave/brave-variations

Hope this helps - I'll close issue for now but we can keep discussing (just tag my username and I'll follow up 😄)

**Comment by n0thing2speak** [comment]
> Release build is absolutely supported; Official build is not though, as that requires Brave Software, Inc assets like certificates, keys, credentials, etc
> 
> There are going to be a list of items you'll need to set in your `~/.npmrc`:
> 
> ```
> brave_sync_endpoint=https://example.com
> brave_stats_updater_url=https://example.com
> brave_variations_server_url=https://example.com
> safebrowsing_api_endpoint=example.com
> ```
> 
> There may be others; each time you run into one (ex; variations server mentioned above), you can add them to this list and put a dummy value. Providing dummy values will cause a problem when running. If you want to be able to put up a real value, you'll need to create an instance of that server type. For example:
> 
> * stats/update: https://github.com/brave/vault-updater
> * sync server: https://github.com/brave/go-sync
> * component updater: https://github.com/brave/go-update
> * variations server: https://github.com/brave/brave-variations
> 
> Hope this helps - I'll close issue for now but we can keep discussing (just tag my username and I'll follow up 😄)

Sir,now i have another problem `ERROR at //brave/vendor/bat-native-ledger/config.gni:26:5: Assertion failed.
    assert(uphold_client_id != "")` , there have  docs to show whats meaning of this vars?
