### ISSUE TITLE
Blank (Empty, or buggy render of) Browser Windows

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#16635]
## Description 

Private Windows are, at times, opening in a blank state. The issue appears to be with rendering, as the window can eventually be drawn by hovering over the corresponding taskbar item, triggering the window-preview functionality.

![buggy-behavior-01](https://user-images.githubusercontent.com/815158/123556854-35373500-d753-11eb-8fc2-dc46b31dcb51.gif)

## Steps to Reproduce

Open a private window.

## Reproduces how often: 

Frequently.

## Brave version

Brave | 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)
--- | ---
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | Windows 10 OS Version 2009 (Build 19043.1055)
JavaScript | V8 9.1.269.36
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PrefetchPrivacyChanges,LegacyTLSEnforced,AutoupgradeMixedContent,WinrtGeolocationImplementation,SafetyTip,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity --disable-features=EnableProfilePickerOnStartup,TextFragmentAnchor,HandwritingRecognitionWebPlatformApi,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,TrustTokens,DirectSockets,IdleDetection,NetworkTimeServiceQuerying,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,SignedExchangeSubresourcePrefetch,NotificationTriggers,WebOTP,InterestCohortFeaturePolicy,FledgeInterestGroups,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,InterestCohortAPIOriginTrial,FirstPartySets,FederatedLearningOfCohorts,AutofillServerCommunication,LiveCaption,LangClientHintHeader --flag-switches-begin --flag-switches-end

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

The _window preview_ function of the taskbar appears to resolve the issue, temporarily.

![buggy-behavior-02](https://user-images.githubusercontent.com/815158/123556845-2ea8bd80-d753-11eb-9700-720be4d58852.gif)

**Comment by jonathansampson** [comment]
The issue doesn't appear to reproduce as easily today (after restarts and updates to Windows). If it doesn't happen again within a week or so, it might be fine to simply close the issue as _non-reproducible_ and _non-actionable_.

**Comment by kjozwiak** [comment]
@jonathansampson I'm on Windows as my daily driver using Nightly but I've never ran into the above. I do update my Nvidia drivers whenever a new one comes down the pipeline but I don't think that matters. I'll keep an eye out just in case though 👍

**Comment by jonathansampson** [comment]
Closing as no-repro.
