### ISSUE TITLE
Enable PermissionLifetime feature by default in code

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#16646]
The overall feature rollout looks fine, no any issues was found, so it's safe to enable the feature by default and remove it from Griffin after some time.

**Comment by stephendonner** [comment]
Verified `PASSED` using a subset of my testplans from #14126 with build 


Brave | 1.28.64 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

Confirmed:
* feature is ENABLED by default
* feature is still `ENABLED` / `DISABLED` toggleable via `brave://flags` (if that needs to change, file a bug or let me know, and I will, @goodov 👍 )

default (enabled) | disabled | previous UI
-------|-----------|--------
<img width="1113" alt="Screen Shot 2021-07-08 at 3 41 06 PM" src="https://user-images.githubusercontent.com/387249/125001133-ceddcc80-e006-11eb-98cd-14c65929541f.png"> | <img width="895" alt="Screen Shot 2021-07-08 at 4 06 40 PM" src="https://user-images.githubusercontent.com/387249/125001162-d9986180-e006-11eb-9143-4483d4f3194d.png"> | <img width="895" alt="Screen Shot 2021-07-08 at 4 06 54 PM" src="https://user-images.githubusercontent.com/387249/125001163-da30f800-e006-11eb-88a5-1c91f4a70e51.png">



**Origin-based behavior, multiple tabs** (`location`):

<summary>

<details>

1. load `hulu.com`
2. log in
3. Give permission `until I close this page`
4. click `Allow`
5. confirm `brave://settings/content/location` shows `Allow` for `Location`
6. click `Allow` when prompted to install Widevine
7. play a video
8. open `hulu.com` in another tab
9. play a video
10. close either of the two open tabs
11. confirm `brave://settings/content/location` shows `Allow` for `Location`
12. close the remaining tab
13. confirm `brave://settings/content/location` now shows `Ask before accessing (recommended)` and has nothing under `Block` and `Allow`

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1100" alt="Screen Shot 2021-07-08 at 3 43 24 PM" src="https://user-images.githubusercontent.com/387249/124999732-a4d6db00-e003-11eb-85ba-1477518cf80c.png"> | <img width="1100" alt="Screen Shot 2021-07-08 at 3 43 42 PM" src="https://user-images.githubusercontent.com/387249/124999734-a56f7180-e003-11eb-85c7-7742b915e334.png"> | <img width="1100" alt="Screen Shot 2021-07-08 at 3 44 31 PM" src="https://user-images.githubusercontent.com/387249/124999735-a6080800-e003-11eb-8493-050d4a926b97.png"> | <img width="1100" alt="Screen Shot 2021-07-08 at 3 44 44 PM" src="https://user-images.githubusercontent.com/387249/124999736-a6080800-e003-11eb-90bd-6585d010c69b.png"> | <img width="1100" alt="Screen Shot 2021-07-08 at 3 44 49 PM" src="https://user-images.githubusercontent.com/387249/124999737-a6080800-e003-11eb-958c-94f930ff4db6.png">


</details>


**24-hours positive test (23 hours)** (`microphone`):
<summary>

<details>


1. load `https://permission.site/`
2. click on `Microphone`
3. give permission `for 24 hours` and click `Allow`
4. confirm `brave://settings/content` shows `Allow` for `Microphone`
5. shut down Brave
6. set system clock forward by 23 hours
7. confirm `brave://settings/content` shows `Allow` for `Microphone`
8. load `https://permission.site/`
9. confirm you do NOT get re-prompted for microphone permissions when clicking on `Microphone

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="671" alt="Screen Shot 2021-07-08 at 3 50 42 PM" src="https://user-images.githubusercontent.com/387249/125000068-65f55500-e004-11eb-9172-672983dc19c1.png"> | <img width="1035" alt="Screen Shot 2021-07-09 at 2 50 42 PM" src="https://user-images.githubusercontent.com/387249/125000072-668deb80-e004-11eb-8676-4cdd219e1c6e.png"> | <img width="1035" alt="Screen Shot 2021-07-09 at 2 50 52 PM" src="https://user-images.githubusercontent.com/387249/125000073-668deb80-e004-11eb-9ea6-67a895f82ad0.png"> | <img width="1119" alt="Screen Shot 2021-07-08 at 3 49 31 PM" src="https://user-images.githubusercontent.com/387249/125000078-67bf1880-e004-11eb-8443-072eebb8da64.png"> | <img width="1035" alt="Screen Shot 2021-07-08 at 3 49 51 PM" src="https://user-images.githubusercontent.com/387249/125000079-6857af00-e004-11eb-8a94-d1247fffb97f.png">

</details>


**Allow forever** (`location`):
<summary>

<details>


1. load `https://permission.site/`
2. click on `Location`
3. give permission `forever`
4. confirm `brave://settings/content/location` shows `Allow` for `Location`
5. shut down Brave
6. set system clock forward by 2+ months
7. confirm `brave://settings/content/location` shows `Allow` for `Location`
8. load `https://permission.site/` and click on `Location` again
9. confirm you get do NOT get reprompted for Location

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1073" alt="Screen Shot 2021-07-09 at 2 54 09 PM" src="https://user-images.githubusercontent.com/387249/125000513-6b06d400-e005-11eb-84e0-e1ee990e253b.png"> | <img width="1073" alt="Screen Shot 2021-07-09 at 2 54 35 PM" src="https://user-images.githubusercontent.com/387249/125000518-6b9f6a80-e005-11eb-8e0a-536150fd0f47.png"> | <img width="780" alt="Screen Shot 2021-09-01 at 2 56 05 PM" src="https://user-images.githubusercontent.com/387249/125000519-6c380100-e005-11eb-9dbb-b506f5110011.png"> | <img width="1073" alt="Screen Shot 2021-09-09 at 2 55 28 PM" src="https://user-images.githubusercontent.com/387249/125000525-6d692e00-e005-11eb-9323-33ef2a6910bd.png"> | <img width="1073" alt="Screen Shot 2021-09-01 at 2 56 22 PM" src="https://user-images.githubusercontent.com/387249/125000521-6cd09780-e005-11eb-8a78-997755604105.png">

</details>

**Consecutive-revocation permissions** (`location`):
<summary>

<details>


1. launch Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --permission-lifetime-test-seconds=20`
2. load `https://permission.site`
3. click on `Location`
4. give permission for `20 seconds`
5. click on the lock icon next to `permission.site` in the URL bar
6. confirm `Location` is set to `Allow`
7. wait 10 seconds
8. open `https://browserleaks.com/geo`
9. give permission for 20 seconds
10. return to `permissions.site`
11. click on the lock icon; confirm you no longer see `Location` with any value
12. return to `browserleaks.com/geo`
13. click on the lock icon; confirm you no longer see `Location` with any value

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="895" alt="Screen Shot 2021-07-08 at 4 01 26 PM" src="https://user-images.githubusercontent.com/387249/125000782-fed8a000-e005-11eb-9e00-a2fcbf76cc4c.png"> | <img width="895" alt="Screen Shot 2021-07-08 at 4 01 32 PM" src="https://user-images.githubusercontent.com/387249/125000785-ff713680-e005-11eb-9204-304b7a5bf64c.png"> | <img width="895" alt="Screen Shot 2021-07-08 at 4 01 46 PM" src="https://user-images.githubusercontent.com/387249/125000786-0009cd00-e006-11eb-816a-4f1646a77879.png"> | <img width="895" alt="Screen Shot 2021-07-08 at 4 02 02 PM" src="https://user-images.githubusercontent.com/387249/125000787-0009cd00-e006-11eb-8733-a79d12411ad6.png"> | <img width="895" alt="Screen Shot 2021-07-08 at 4 02 19 PM" src="https://user-images.githubusercontent.com/387249/125000789-0009cd00-e006-11eb-95bc-5bfe4cf12fd0.png">

</details>

**Comment by goodov** [comment]
> feature is still toggleable via ```brave://flags```

good catch! I missed that. Let's also clean this up.

**Comment by srirambv** [comment]
Verification passed on Oppo R5 with Android 11 running 1.28.99 x64 Beta build
- Verified Permission lifetime is enabled by default 
- Verified permission prompt shows up on `https://permission.site` without having to enable/disable any flag
- Verified permission prompt for `until I close this site`, `for 24 hours`, `for 1 week` & `forever` works as expected for both allow and block 
- Verified `chrome://flags/#brave-permission-lifetime` flag is available and can still be used to disable the setting 
-----------
Verification passed on Samsung Tab A with Android 10 running 1.28.99 x64 Beta build
- Verified Permission lifetime is enabled by default 
- Verified permission prompt shows up on `https://permission.site` without having to enable/disable any flag
- Verified permission prompt for `until I close this site`, `for 24 hours`, `for 1 week` & `forever` works as expected for both allow and block 
- Verified `chrome://flags/#brave-permission-lifetime` flag is available and can still be used to disable the setting
