### ISSUE TITLE
Make possible to observe effective values of feature flags

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#16644]
It is hard to determine whether a feature flag is enabled or not.

1. brave://flags doesn't show any real values for untouched flags
2. brave://version/?show-variations-cmd shows only griffin and command line overrides.

We can either improve brave://flags UI or craft a new page.

**Comment by Johann999** [comment]
a flag should only have two possibilities: enabled or disabled
remove the default possibility

**Comment by rebron** [comment]
+1 and cc: @arch-btw as we'll address fix in this issue.
