### ISSUE TITLE
Ethereum doesn't resolve some ENS domains

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16655]
## Description 

ENS via Ethereum doesnt resolve some domains from `https://etherscan.io/enslookup?`, `http://blocktimer.dappstar.eth/` for example

## Steps to Reproduce

- new profile
- launch Brave
- load brave://settings/extensions for Method to resolve Ethereum Name Service (ENS) choose Ethereum
- open a new tab
- load http://blocktimer.dappstar.eth/

## Actual result:

dns error

## Expected result:

webpage is loaded

## Reproduces how often: 

100%

**Comment by stephendonner** [comment]
Verified `FIXED` using the inline testplan and build 


Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)



Steps:

1. new profile
2. launch Brave
3. load `brave://settings/extensions`
4. for `Method to resolve Ethereum Name Service (ENS)`, choose Ethereum`
5. open three new tabs
6. load `http://blocktimer.dappstar.eth/`, `brantly.eth`, and `matoken.eth`

`blocktimer.dappstar.eth`

`brave://settings/extensions` | `gateway` | `localhost` | `local IPFS`
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2021-07-06 at 11 32 27 AM" src="https://user-images.githubusercontent.com/387249/124658922-381fdd00-de59-11eb-88a2-e4ab6de954dd.png"> | <img width="1312" alt="Screen Shot 2021-07-06 at 12 46 16 PM" src="https://user-images.githubusercontent.com/387249/124659265-9baa0a80-de59-11eb-9db5-a2e29258d2b6.png"> | <img width="1748" alt="Screen Shot 2021-07-06 at 12 47 27 PM" src="https://user-images.githubusercontent.com/387249/124658981-4968e980-de59-11eb-8cb5-1c5b3e641208.png"> | <img width="1748" alt="Screen Shot 2021-07-06 at 12 47 31 PM" src="https://user-images.githubusercontent.com/387249/124658984-4a9a1680-de59-11eb-9b71-64151d562c3d.png"> | 


`brantly.eth`

`gateway` | `IPNS` | `local IPFS`
-----------|------------|-------------
<img width="1748" alt="Screen Shot 2021-07-06 at 12 59 00 PM" src="https://user-images.githubusercontent.com/387249/124659734-225ee780-de5a-11eb-9a1b-c9b7518ab9c6.png"> |  <img width="1748" alt="Screen Shot 2021-07-06 at 12 58 10 PM" src="https://user-images.githubusercontent.com/387249/124659836-3d315c00-de5a-11eb-847d-3f0354ce9b5c.png"> | <img width="1748" alt="Screen Shot 2021-07-06 at 12 58 38 PM" src="https://user-images.githubusercontent.com/387249/124659787-30ad0380-de5a-11eb-9a42-6e2cd1e3044b.png">

`matoken.eth`

`gateway` | `local IPFS`
-----------|-------------
<img width="1748" alt="Screen Shot 2021-07-06 at 1 05 58 PM" src="https://user-images.githubusercontent.com/387249/124660529-2b9c8400-de5b-11eb-9755-dc12045406e8.png"> | <img width="1748" alt="Screen Shot 2021-07-06 at 1 06 22 PM" src="https://user-images.githubusercontent.com/387249/124660544-2e977480-de5b-11eb-9930-07de04c33ce3.png">

**Comment by stephendonner** [comment]
@spylogsster mind starting an uplift into `1.27.x`?  Thanks!

**Comment by spylogsster** [comment]
@stephendonner done thanks

**Comment by LaurenWags** [comment]
labelling as `QA/Blocked` until we get a new 1.27.x build.

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.27.100 Chromium: 91.0.4472.124 (Official Build) beta (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)



Steps:

1. new profile
2. launched Brave
3. loaded `brave://settings/extensions`
4. for `Method to resolve Ethereum Name Service (ENS)`, I chose Ethereum`
5. opened three new tabs
6. loaded `http://blocktimer.dappstar.eth/`, `brantly.eth`, and `matoken.eth`

`blocktimer.dappstar.eth`

`brave://settings/extensions` | `gateway` | `localhost` | `local IPFS`
---------|----------|---------|---------
<img width="1648" alt="Screen Shot 2021-07-09 at 12 27 40 PM" src="https://user-images.githubusercontent.com/387249/125127397-51bb6180-e0b1-11eb-9b48-950a39e61044.png"> | <img width="1312" alt="Screen Shot 2021-07-09 at 8 14 03 AM" src="https://user-images.githubusercontent.com/387249/125127300-29cbfe00-e0b1-11eb-91f5-594202706e21.png"> | <img width="1648" alt="Screen Shot 2021-07-09 at 8 19 17 AM" src="https://user-images.githubusercontent.com/387249/125127303-2a649480-e0b1-11eb-93af-3e18ba94f12e.png"> | <img width="1648" alt="Screen Shot 2021-07-09 at 8 19 21 AM" src="https://user-images.githubusercontent.com/387249/125127305-2afd2b00-e0b1-11eb-8155-5096634b859c.png">



`brantly.eth`

`gateway` | `IPNS` | `local IPFS`
-----------|------------|-------------
<img width="1648" alt="Screen Shot 2021-07-09 at 8 20 16 AM" src="https://user-images.githubusercontent.com/387249/125126537-1f5d3480-e0b0-11eb-927b-0ac8793046c8.png"> | <img width="1648" alt="Screen Shot 2021-07-09 at 8 20 30 AM" src="https://user-images.githubusercontent.com/387249/125126539-1ff5cb00-e0b0-11eb-8be8-f7b3d6e493e5.png"> | <img width="1648" alt="Screen Shot 2021-07-09 at 8 19 33 AM" src="https://user-images.githubusercontent.com/387249/125126534-1d937100-e0b0-11eb-9f31-bdf44e79798c.png">


`matoken.eth`

`gateway` | `local IPFS`
-----------|-------------
<img width="1648" alt="Screen Shot 2021-07-09 at 8 21 16 AM" src="https://user-images.githubusercontent.com/387249/125127062-df4a8180-e0b0-11eb-8e09-131578bd1cbd.png"> | <img width="1648" alt="Screen Shot 2021-07-09 at 8 20 56 AM" src="https://user-images.githubusercontent.com/387249/125127147-f7220580-e0b0-11eb-9551-c83f6df2423a.png">
