### ISSUE TITLE
Fix non-KYC'ed (batLimit) modal in Uphold verification flow

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16651]
## Description

A user can end up in the `batLimit` error state during the verify Brave Rewards wallet flow with Uphold. This will display an error modal. This error modal is currently broken.

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/9530 with 


Brave | 1.29.42 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 12.0 (Build 21A5294g)



Steps:

1. new profile
2. launched Brave
3. clicked on the BAT icon in the URL bar
4. enabled `Rewards`
5. clicked on `Verify Wallet`
6. clicked the `Continue` button
7. clicked on the `Continue to login` button
8. on the `Uphold` screen, clicked `Authorize`
9. entered my Brave credentials (have account but not KYC'd like my personal gmail)
10. clicked on `Login`

Confirmed with my non-KYC'd account that I saw the correct `You need a verified wallet to log in, Please try again after you have completed ID verification on Uphold` modal.

<img width="1043" alt="Screen Shot 2021-08-02 at 1 58 19 PM" src="https://user-images.githubusercontent.com/387249/127923341-45ccb864-2431-444e-a6c5-b79f800b5e5a.png">
