### ISSUE TITLE
Properly handle Qwant in private windows + tor windows

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1666]
## Test plan
1. Fresh install of Brave (new profile directory, etc)
2. Set region as `France`
3. Launch Brave- verify Qwant is default for:
    - regular tabs
    - private window tabs
    - private window tabs with Tor
4. Change default search engine to Bing
5. Verify Bing is used in:
    - regular tabs
    - private window tabs
6. Verify Qwant is used for private tabs
7. Verify that DDG logo/wording does NOT show in:
    - private window tabs
    - private window tabs with Tor
8. Repeat steps 3-7 with region as `Germany`
9. Clear profile; set region as your real location (United States, Canada, etc)
10. Launch Brave
11. Verify DDG logo/wording DOES show in
    - private window tabs
    - private window tabs with Tor
12. Verify DDG is used as the default search for private window tabs with Tor

## Edited description
This is a follow up to https://github.com/brave/brave-browser/issues/1632

This issue originally was match the behavior in Muon, but the intention is now to handle it how we want it (verified by @davidtemkin). As he noted in https://github.com/brave/brave-core/pull/685#issuecomment-431046594:
> DDG should never be promoted / shown / defaulted on in Qwant regions. In Qwant regions, we default to Qwant for search in all types of windows, including private and private/tor and do not promote DDG.

**Comment by simonhong** [comment]
Hmm, I'm a little bit confusing with newtab UX in private(with or w/o tor).
I found that there are two kinds of ddg version new tab - with or w/o ddg toggle button.
It would be helpful to me if I can know the exact UX scenario of newtab.

**Comment by bsclifton** [comment]
Notes in original issue above fixed after verifying intended behavior

**Comment by GeetaSarvadnya** [comment]
@bsclifton step 6: should it be 'Verify Qwant is used for private window tabs with Tor'?

Verification passed on


Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows

- **Verified below points for `France` region**
   - Qwant is the default search egine for Normal tabs
   - Qwant is the default search egine for Private window tabs
   - Qwant is the default search egine for Private window tabs with tor
   Verified below points after changing default search engine to Bing
   - Bing is the default search engine for Normal tabs
   - Bing is the default search eginge for Private window tabs
   - Qwant is the default search egine for Private window tabs with tor
- **Verified below points for `Germany` region**
   - Qwant is the default search egine for Normal tabs
   - Qwant is the default search egine for Private window tabs
   - Qwant is the default search egine for Private window tabs with tor
   Verified below points after changing default search engine to Bing
   - Bing is the default search engine for Normal tabs
   - Bing is the default search eginge for Private window tabs
   - Qwant is the default search egine for Private window tabs with tor
  - **Verified below points for ` India/Real location` region**
    -  DDG logo/wording shows for Private window tabs
    -  DDG logo/wording shows for Private window tabs with tor
    -  DDG is the default search engine for Private window tabs with tor
