### ISSUE TITLE
Redundant import-video-to-IPFS context-menu items

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16666]
## Description 

Redundant import-video-to-IPFS context-menu items

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `ipns://brantly.eth`
   4. click on `Use a local node`
   5. load `https://en.wikipedia.org/wiki/File:Big_Buck_Bunny_4K.webm`
   6. right-click the video file
   7. look at the resulting context-menu items

## Actual result:

Two context-menu items appear:
1. `Selected Video > Import to IPFS`
2. `Import to IPFS > Selected video`

![double-menu-items-ipfs](https://user-images.githubusercontent.com/387249/123708453-49953380-d820-11eb-8115-f029be6303c8.png)

## Expected result:

We should probably have only one of these context-menu items.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.34 Chromium: 91.0.4472.124 (Official Build) nightly (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2009 (Build 21390.2025)

**Comment by spylogsster** [comment]
@stephendonner do you have IPFSCompanion installed as well?

**Comment by stephendonner** [comment]
> @stephendonner do you have IPFSCompanion installed as well?

Yes, I must have had it in my profile when testing `go-ipfs` `0.9.0` interop; sorry for forgetting to take stock and mention that!

**Comment by lidel** [comment]
IPFS Companion could hide duplicate actions when running in Brave – mind filling issue in https://github.com/ipfs/ipfs-companion with list of actions to hide?

**Comment by stephendonner** [comment]
> IPFS Companion could hide duplicate actions when running in Brave – mind filling issue in https://github.com/ipfs/ipfs-companion with list of actions to hide?

Will try to get to this, but am heavily backlogged with other (more-pressing) work, so no promises 😄

**Comment by stephendonner** [comment]
@lidel @spylogsster it's all the context-menu import types (video, audio file, text, linked content, etc.), e.g. `Import to IPFS -> This page` (Brave side) & `This page -> Import to IPFS`.

At least they're differently worded, so we can tell them apart, for now 😄

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
