### ISSUE TITLE
Update text from `Transform E R C20` to `Swap XXX to YYY`

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16673]
## Description 

Update text from Transform E R C20 to Swap XXX to YYY

## Steps to Reproduce

   1. Install/Upgrade to `1.0.31 Dev` component
   2. Perform a swap 
   3. Activity shows `Transform E R C20` looks quite unpolished

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/123750200-3630a980-d8ae-11eb-81e6-52cb625db97c.png)

## Expected result:
Similar to MM
![image](https://user-images.githubusercontent.com/17010094/123750227-3df04e00-d8ae-11eb-9ccb-2a03aefcb40e.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.26.67 Chromium: 91.0.4472.114 (Official Build) (x86_64)
-- | --
Revision | `4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}`
OS | All
Component | `1.0.31 Dev`

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @onyb @bbondy

**Comment by onyb** [comment]
Trying to infer the intent of a transaction (i.e., "Swap XXX to YYY") requires parsing the raw transaction against the 0x contract ABI. By default, all arbitrary function calls are displayed as "Transform E R C20".

I propose to close this one. Checked internally with @bbondy.

**Comment by srirambv** [comment]
Closing as wontfix

**Comment by srirambv** [comment]
Removing from milestone as its a wontfix issue
