### ISSUE TITLE
Learn more missing in Tor window description

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1667]
## Description 

Found while going through https://github.com/brave/brave-browser/issues/1507

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/47111143-b8710080-d220-11e8-807c-3916668daeb5.png)

## Expected result:
Should have learn more pointing to support link as per spec

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tomlowenthal** [comment]
This is an artifact of the changes to the other learn-more links on the page. Not going to fix in current form, but might change with the next refresh to the new-tab pages.
