### ISSUE TITLE
Able to import duplicate IPNS keys (but not by name)

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16670]
## Description 

Able to import duplicate IPNS keys (but not by name)

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `ipns://brantly.eth`
   4. click on `Use a local node`
   5. load `brave://settings/ipfs/keys`
   6. click `Add`
   7. type `importedkey` and click `Import`
   8. select the key file through the OS, click `OK`
   9. on `brave://settings/ipfs/keys` click `Add` again
   10. type `importedkey2` and click `Import`
   11. select the same key file through the OS, click `OK`

## Actual result:

Currently, we allow for duplicate-hash/data key files to be imported using a different name.

![ipfs-keys-list](https://user-images.githubusercontent.com/387249/123722409-2b89fc00-d83d-11eb-8526-49444ab5f52d.png)

## Expected result:

Shouldn't allow duplicate keys, by key hash/data

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | Windows 10 OS Version 2009 (Build 21390.2025)

**Comment by lidel** [comment]
Having the same key under different names is allowed by `ipfs key import`, so technically it is not a bug. More like an UX concern.

Brave could add check that forces user to have only one key, but not sure if that improves UX enough to justify additional development/code. I don't feel strongly about this either way :)

**Comment by stephendonner** [comment]
Same; mostly just wanted to get this logged for decision/paper-trail reasons :-)

**Comment by bbondy** [comment]
I think it's ok to allow it, we'll close for now unless a good reason surfaces to disallow. Thanks for logging it in any case.
