### ISSUE TITLE
Add province-level targeting for Canada + US-Wyoming

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#16682]
## Description 
Add province-level targeting for Canadian Provinces 

**Include**
      ['CA-AB', 'Alberta'],                                                     
      ['CA-BC', 'British Columbia'],                                            
      ['CA-MB', 'Manitoba'],                                                    
      ['CA-NB', 'New Brunswick'],                                               
      ['CA-NS', 'Nova Scotia'],                                                 
      ['CA-ON', 'Ontario'],                                                     
      ['CA-QC', 'Quebec'],                                                      
      ['CA-SK', 'Saskatchewan']   

**Exclude the following provinces**
 'CA-NL', 'Newfoundland & Labrador'
 'CA-PE', 'Prince Edward Island'
 'CA-NT', 'Northwest Territories'
 'CA-YT', 'Yukon'
 'CA-NU', 'Nunavut'
 
iOS does not show the UI at this time; however, we should raise a separate issue for iOS just in case the functionality is re-enabled in the future

**Comment by iambrianfung** [comment]
We have also been approved to include US-WY (Wyoming) as well.

**Comment by tmancey** [comment]
@iambrianfung US-WY is already part of the ads library. Removing from description. Thanks

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/15009

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
Revision	2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS	Android 12; Build/SP1A.210812.016
```

### Case 1: 

<details>

US-CA | CA-QC
-|-
![screenshot-1666297054981](https://user-images.githubusercontent.com/17885425/197057988-ea006dab-1b11-4172-abc9-6bb51af1fdf0.png) | ![screenshot-1666298158150](https://user-images.githubusercontent.com/17885425/197058200-303341c3-cbe3-46d6-9c91-9bf490afd69f.png)
![Screen Shot 2022-10-20 at 4 17 12 PM](https://user-images.githubusercontent.com/17885425/197058294-039b931e-ee98-4161-9b15-ccbdf2fef954.png) | ![Screen Shot 2022-10-20 at 4 35 45 PM](https://user-images.githubusercontent.com/17885425/197058303-b2b76e8b-e15c-47c3-80e8-4f07d5173ea1.png)



</details>

### Case 2

<details>

US-CA 
{"country":"US","region":"CA"}
`brave://rewards`



CA-QC
{"country":"CA","region":"QC"}
`brave://rewards`


Change Regional ad relevance to `Manitoba`



</details>

### Case 3

<details>

CA-QC
{"country":"CA","region":"QC"}
`brave://rewards`

Changed locale to `Manitoba`


Run brave in Polish locale (PL)


ad relevance is available CA-QC
{"country":"CA","region":"QC"}



</details>

### Case 4

<details>

</details>

### Case 5

<details>

</details>
