### ISSUE TITLE
Serve PDFJS from go-updater rather then CWS

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1669]
As [noted](https://github.com/brave/brave-browser/issues/527#issuecomment-430359190) by Lauren in #527, Brave currently connects to the Chrome Web Store on startup to get PDFJS and then subsequently for updates. Instead, we'll serve PDFJS from the go-updater server, which means no connection to Google for this.

**Comment by diracdeltas** [comment]
this is fixed by @emerick

**Comment by tomlowenthal** [comment]
Test plan:
- Use a tool like Little Snitch to show what servers Brave is connecting to.
- Get rid of your Brave profile.
- Open the Brave build you're testing.
- Your network monitor doesn't show any connections to Google.

**Comment by srirambv** [comment]
@tomlowenthal should we block connection to CWS on a clean profile? It makes sense to connect if a user has installed an extension on the profile, to check for update. There is still connection to clients2.google.com (CWS) at start up. I assume this is because we still have webstore shortcut on `brave://apps`

**Comment by tomlowenthal** [comment]
There should be no connections to any Google domains on first run (i.e: startup with a clean profile). Update checks for extensions should only happen when a user has installed extensions and seen the note that they'll get updates from the CWS.

If we're getting first-run CWS connections from the shortcut in apps, that's a separate issue which needs to be solved.

**Comment by diracdeltas** [comment]
@tomlowenthal that test plan doesn't actually work because of the google connections which still remain (mentioned in slack)

**Comment by tomlowenthal** [comment]
Understood. Sounds like we need to fix those other things too.

**Comment by srirambv** [comment]
@tomlowenthal @diracdeltas could you please add the updated test plan for the issue to be verified

**Comment by diracdeltas** [comment]
@srirambv https://github.com/brave/brave-browser/issues/1669#issuecomment-430772382 i think is still the test plan

on non-Mac, you can use chrome://net-internals instead of Little Snitch

**Comment by srirambv** [comment]
Verification Passed on

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux 

* Verified based on steps mentioned in https://github.com/brave/brave-browser/issues/1669#issuecomment-430772382
