### ISSUE TITLE
Analytics in URL causing issues

### ISSUE THREAD

**Issue by alaboudi** [brave/brave-browser#16702]
## Description 

I had to rack my brain to figure this one out but It seems like the Brave will block a request to an endpoint if the word `analytics` is in the url. This is true even if the request is a `GET` request. For context, I am trying to visualize some data on a web app but the Javascript request fails because the url happens to have the word `analytics` in it. I'm certain the the heuristic of blocking any api with the `analytics` in the url has worked for a lot of cases, but now its affecting my web app as the term is taken out of context

## Steps to Reproduce

   1. Via Javascript, call an api with the word `analytics` in it. (e.g. 'blah/blah/blah/analytics')

## Actual result:

It gets blocked by the client

## Expected result:
A GET request should not be blocked.

## Reproduces how often: 

Every time 

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes as of Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (x86_64)
- Can you reproduce this issue with the beta channel? dont know
- Can you reproduce this issue with the nightly channel?  dont know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
Example url causing issues? @alaboudi

**Comment by rebron** [comment]
Closing as stale. Please reopen @alaboudi if you have more information you can provide us.
