### ISSUE TITLE
fix missing A in BR panel grant notification text

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#1670]
fix https://github.com/brave/brave-core/pull/669

**Comment by LaurenWags** [comment]
@bradleyrichter to confirm, this is what you're looking for:
![screen shot 2018-10-18 at 4 08 44 pm](https://user-images.githubusercontent.com/28145373/47181556-3c92b900-d2f1-11e8-8ab4-aac433c093e5.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

![image](https://user-images.githubusercontent.com/34715963/47225659-ea1fce00-d3be-11e8-8f83-0f07657a5164.png)
