### ISSUE TITLE
[cr92 followup] Settings page is blank 

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#16708]
The brave://settings page is blank and there's an error in the console:

[Brave Settings Overrides] Could not find menu item '/safetyCheck'

STR:

1. Start Brave
2. Navigate to brave://settings

Observe: the settings page is blank
Expected results: settings are shown

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

```
- Confirmed that brave://settings and sub-settings loaded successfully and click on settings redirected correct section and settings worked fine

Example | Example | Example | Example | Example | Example | Example | Example
----------|-----------|-----------|----------|-----------|----------|-----------|----------
![image](https://user-images.githubusercontent.com/38657976/125762191-9438ecba-0383-4e21-b845-d26437d4bb71.png) | ![image](https://user-images.githubusercontent.com/38657976/125762410-3caaa320-a84b-4337-b1d0-c4835922efbd.png) | ![image](https://user-images.githubusercontent.com/38657976/125762498-c65ebd31-b031-402b-b8a2-25cb4d983bed.png) | ![image](https://user-images.githubusercontent.com/38657976/125762584-33b35912-4ece-4c88-83de-ce6e37a3387d.png) | ![image](https://user-images.githubusercontent.com/38657976/125762643-39139f20-f8c4-42ab-b931-3726df6734a9.png) | ![image](https://user-images.githubusercontent.com/38657976/125762780-f4cf33de-442f-44c4-a489-675ad4f2eec4.png) | ![image](https://user-images.githubusercontent.com/38657976/125762847-6fe0661c-4b62-4884-bf53-3855ffaeb581.png) | ![image](https://user-images.githubusercontent.com/38657976/125763020-ada56bbc-34f3-4170-8f48-2a28f199f6ac.png)
