### ISSUE TITLE
Brave informs me that it will use DuckDuckGo SE for Private Tabs even if Brave SE is enabled

### ISSUE THREAD

**Issue by nastavoi** [brave/brave-browser#16701]
## Description 

Brave informs me that it will use DuckDuckGo SE for Private Tabs even if Brave SE is enabled.

## Steps to reproduce 

   1. Open Brave Beta or Nightly
   2. Go to Settings and select Brave SE for private tabs
   3. Open private Tab
   4. See browser warning/notification that DDG SE will be used
   5. Search for something and notice that Brave SE is used  (as expected)

## Actual result 

Brave informs me that IT WILL use DuckDuckGo SE in Private Tabs even if Brave SE is enabled, which I think is inaccurate. Actual SE that is being used is Brave (as expected).

![123975677-d0cbde00-d9bd-11eb-8a88-7f4aeabc520b](https://user-images.githubusercontent.com/61883414/123984562-045e3680-d9c5-11eb-81f7-ad8030f8c85d.jpg) ![123975078-65820c00-d9bd-11eb-8a11-a31afb4e6d70](https://user-images.githubusercontent.com/61883414/123984573-06c09080-d9c5-11eb-839e-7021eeb05a0d.jpg) ![123975119-6adf5680-d9bd-11eb-8d4a-a0fc306c1e28](https://user-images.githubusercontent.com/61883414/123984583-088a5400-d9c5-11eb-9a58-7301c254c80d.jpg)

## Expected result

Brave shouldn't inform me that DDG SE will be used in private tabs if Brave SE enabled. Should tell me something about Brave SE instead.

## Issue reproduces how often 

Always on beta and nightly.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @anthonypkeane @timchilds

**Comment by samartnik** [comment]
We no longer promote DDG in private tabs. Closing issue as it is obsolete.
