### ISSUE TITLE
Preloaded MP4 files cannot be imported via IPFS context menu

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16705]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/15937
Preloaded MP4 files cannot be imported via IPFS context menu
## Steps to Reproduce

   1. Clean profile 1.27.x
   2. Enable IPFS
   3. Use the Ctlr+O shortcut key and open any MP4 file from your local machine
   4. Right-click on the play icon and select `Import to IPFS->Selected video` option
   5. Getting IPFS import failed

## Actual result:

IPFS import failed for MP4 files
![IPFS import failed](https://user-images.githubusercontent.com/38657976/123992930-a6901580-d9e9-11eb-9a78-d4122029154a.gif)

![image](https://user-images.githubusercontent.com/38657976/123990744-ac84f700-d9e7-11eb-965c-9d4cb46069ff.png)

## Expected result:

Should be able to import MP4 files
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.27.84 Chromium: 91.0.4472.124 (Official Build) beta (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster @brave/legacy_qa @rebron

**Comment by stephendonner** [comment]
Thanks, @GeetaSarvadnya - FWIW, I've also reproduced this on: 

Brave | 1.28.37 Chromium: 91.0.4472.124 (Official Build) nightly (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

File: `https://download.samplelib.com/mp4/sample-5s.mp4` from `https://samplelib.com/sample-mp4.html`

**Comment by stephendonner** [comment]
This worked for me, same build as above, when I ran with `--use-dev-goupdater-url`, and picked up `go-ipfs` `0.9.0` (which we are set to release today or tomorrow).  Does that fix it for you, @GeetaSarvadnya ?

**Comment by GeetaSarvadnya** [comment]
@stephendonner It's not working for me in IPFS version `0.9.0` 
![IPFS_MP4 Import failed](https://user-images.githubusercontent.com/38657976/124152277-030a3800-dab1-11eb-9cb5-b2dbecbe6e7d.gif)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

```
- Verified the STR from the issue and ensured .MP4 files can be imported via IPFS context menu
![image](https://user-images.githubusercontent.com/38657976/125776826-5688dec0-66d8-4194-8e43-344ee271aad5.png)
