### ISSUE TITLE
txt and json files cannot be imported via Share or import IPFS options

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16713]
## Description 

txt and json files cannot be imported via Share or import IPFS options

## Steps to Reproduce

   1. Clean profile 1.27.x
   2. Enable IPFS
   3. Click on the Hamburger menu and select `IPFS->Share local files using IPFS` or Import the local file via the `Import` menu
   4. Share/import the .txt or .json file from local machine

## Actual result:

txt and json files cannot be imported via Share or import IPFS options

![image](https://user-images.githubusercontent.com/38657976/124009612-70f42800-d9fb-11eb-8748-e76fdf216a9c.png)

![image](https://user-images.githubusercontent.com/38657976/124009683-88331580-d9fb-11eb-8e79-430022217863.png)

## Expected result:
txt and json files can be imported via Share or import IPFS options

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.27.84 Chromium: 91.0.4472.124 (Official Build) beta (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @spylogsster @rebron

**Comment by spylogsster** [comment]
![image](https://user-images.githubusercontent.com/2965009/124095124-0d511580-da62-11eb-9ed6-2c9d31119fdd.png)
it works for me on 0.9.0 node and we have duplicated issue https://github.com/brave/brave-browser/issues/16680 @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment]
@stephendonner Issue is working fine with `--use-dev-goupdater-url` `0.9.0`.  I will test the issue once the IPFS component version `0.9.0` is pushed into 1.27.x and close off the issue

**Comment by lidel** [comment]
Good news: ipfs-webui in go-ipfs 0.9.0 should have this bug fixed

**Comment by stephendonner** [comment]
@GeetaSarvadnya mind re-testing with `--use-dev-goupdater-url`, as that'll pick up the `0.9.1` version; this works for me using the following build with the above `go-ipfs` binary:


Brave | 1.30.15 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

**Comment by stephendonner** [comment]
Verified `FIXED` by upstream `go-ipfs` component; marking as such.

Works now with 


Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

and `go-ipfs-0.9.1`

example | example | example | example
---------|----------|---------|---------
<img width="1489" alt="Screen Shot 2021-08-18 at 1 07 02 PM" src="https://user-images.githubusercontent.com/387249/129965323-50557774-407c-4a76-9b94-6c3d09c8c3e4.png"> | <img width="1489" alt="Screen Shot 2021-08-18 at 1 08 01 PM" src="https://user-images.githubusercontent.com/387249/129965328-1d6b2a0a-6cc5-4e5c-800c-313173e33784.png"> | <img width="1489" alt="Screen Shot 2021-08-18 at 1 08 39 PM" src="https://user-images.githubusercontent.com/387249/129965330-09865358-12ee-430f-b159-b5f98ffa9d82.png"> | <img width="1489" alt="Screen Shot 2021-08-18 at 1 08 51 PM" src="https://user-images.githubusercontent.com/387249/129965333-0c383ca3-5ec8-420c-acf8-ab3b64e71fab.png">

**Comment by stephendonner** [comment]
Verified `PASSED` now using 


Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

and `go-ipfs` `0.9.1`

<img width="1489" alt="Screen Shot 2021-08-18 at 1 11 56 PM" src="https://user-images.githubusercontent.com/387249/129965683-789a3328-7dd6-464b-a4a8-2f3c3c65642c.png">

**Comment by GeetaSarvadnya** [comment]
@stephendonner Apologies somehow missed the issue. Today I have verified the issue on Windows 10 x64 - `1.28.106` build issue is fixed and working fine with ipfs component `0.9.1`
