### ISSUE TITLE
Don't connect to www.googleapis.com/chromewebstore/v1.1/items/verify

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1672]
On startup, we seem to make connections to `https://www.googleapis.com/chromewebstore/v1.1/items/verify`. We shouldn't.

Related to #633.

**Comment by diracdeltas** [comment]
didn't see this issue til now but i have a PR open for this: https://github.com/brave/brave-core/pull/674

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

![image](https://user-images.githubusercontent.com/34715963/47179537-99589880-d31e-11e8-872c-74489ef55d84.png)
