### ISSUE TITLE
Don't connect to Google for Safe Browsing

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1673]
On startup, we seem to make connections to `https://ssl.gstatic.com/safebrowsing/csd/client_model_v5_variation_0.pb`. We shouldn't.

Related to #633.

**Comment by diracdeltas** [comment]
FYI @tomlowenthal you tagged #633 instead of #663 on this series of issues so they weren't showing up in the parent issue

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

Used test plan from https://github.com/brave/brave-core/pull/676

![image](https://user-images.githubusercontent.com/34715963/47228602-ec395b00-d3c5-11e8-9d94-b3758f1c7daa.png)

Also verified in Fiddler.
