### ISSUE TITLE
[iOS] CI build error 'ads.mojom.h not found'

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#16733]
<pre>
11:16:25  In file included from gen/brave/ios/browser/api/ads/ads.mojom.objc.mm:7:
11:16:25  gen/brave/ios/browser/api/ads/ads.mojom.objc+private.h:8:9: fatal error: 'brave/vendor/bat-native-ads/include/bat/ads/public/interfaces/ads.mojom.h' file not found
11:16:25  #import "brave/vendor/bat-native-ads/include/bat/ads/public/interfaces/ads.mojom.h"
11:16:25          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:16:25  1 error generated.
</pre>

@kylehickinson, I am thinking `mojom_wrappers.gni`'s `source_set` should also add a dependency on the `${target_name}`?

**Comment by kylehickinson** [comment]
I didn't run into this in any of my local builds and it passed CI previously before I merged. Is this failing for all new pr's or is it a specific change?

**Comment by mkarolin** [comment]
> I didn't run into this in any of my local builds and it passed CI previously before I merged. Is this failing for all new pr's or is it a specific change?

Only ran into it once here: https://ci.brave.com/job/pr-brave-browser-maxk-revert-unit-tests-in-static-libs-ios/3/execution/node/140/log/ - it's probably intermittent.
