### ISSUE TITLE
update arrival date value for ad grant UI - follow up to #15005

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#16731]
## Description 

Found while testing #15005, the "arriving in X days" is sometimes rounding up, which can be confusing when comparing it to the displayed "Next payment date".

See https://bravesoftware.slack.com/archives/CB0KCRCQN/p1625153601283200 for additional context.

## Steps to Reproduce

   1. Have ad tokens cashed in for previous month.
   2. On the 1st of the next month, go to brave://rewards or NTP widget.
   3. View "arriving in X days" message.

## Actual result:

Message says my ad grant is arriving in 5 days (I think that means July 6th, today + 5 days)

Example | Example
----- | -----
<img width="648" alt="Jul1-15005 prod env profile1 ad panel" src="https://user-images.githubusercontent.com/28145373/124155433-7c2f6e00-da64-11eb-941f-04f65fe22034.png"> | <img width="305" alt="Jul1-15005 prod env profile1 NTP widget" src="https://user-images.githubusercontent.com/28145373/124155444-7df93180-da64-11eb-8e86-246b664378bf.png">

## Expected result:
I was expecting it to say 4 days since payment date is listed as July 5 (today + 4 days).

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.27.87 Chromium: 91.0.4472.124 (Official Build) beta (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 10.15.7 (Build 19H1217)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing @Miyayes

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with build 


Brave | 1.28.96 Chromium: 92.0.4515.115 (Official Build) beta (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5.1 (Build 20G80)

Steps:

1. have ad tokens cashed in for previous month
2. on the 1st of the next month, opened a new tab page with `Brave Rewards` widget and `brave://rewards`
3. noted their "arriving in X days" messages

Confirmed `+0.06 BAT arriving in 6 days` is correct (matches `Next payment date` in `brave://rewards`).

`brave://rewards` | `Brave Rewards` widget
----------------|-----------------------
<img width="547" alt="Screen Shot 2021-08-01 at 3 33 22 PM" src="https://user-images.githubusercontent.com/387249/127574597-1799d930-e333-4683-896d-b29a59cbfc73.png"> | <img width="1770" alt="Screen Shot 2021-08-01 at 3 40 00 PM" src="https://user-images.githubusercontent.com/387249/127574607-03433fba-50cb-446b-b140-5541722eecab.png">
