### ISSUE TITLE
ipns and ipfs URLs should not redirect/load over a Gateway in Private and Guest windows

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16737]
## Description 

`ipns://` and `ipfs://` URLs should not redirect/load over a Gateway in Private and Guest windows

See https://github.com/brave/brave-browser/issues/12978 for more details - the below testplan is from there.

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. set `Method to resolve IPFS resources` to `Gateway` in `brave://settings/ipfs`
   4. do either/both a Private Window / Guest Window
   5. load `ipns://brantly.eth` or `ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`

## Actual result:

Both URLs resolve and load in Private and Guest windows (but not in Private Window with Tor).

example | example
---------|--------
<img width="1312" alt="Screen Shot 2021-07-01 at 10 16 33 AM" src="https://user-images.githubusercontent.com/387249/124174658-7f752a80-da61-11eb-86b8-33c5edb79ada.png"> | <img width="1312" alt="Screen Shot 2021-07-01 at 10 17 42 AM" src="https://user-images.githubusercontent.com/387249/124174663-800dc100-da61-11eb-85e7-2321e737b9d3.png">

## Expected result:

Per https://github.com/brave/brave-browser/issues/12978 they shouldn't load in Private or Guest windows.

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-07-01 at 10 20 14 AM" src="https://user-images.githubusercontent.com/387249/124174515-52c11300-da61-11eb-9417-d5e298fd94ec.png"> | <img width="1312" alt="Screen Shot 2021-07-01 at 10 20 25 AM" src="https://user-images.githubusercontent.com/387249/124174519-52c11300-da61-11eb-9f94-5ce8381071ab.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.37 Chromium: 91.0.4472.124 (Official Build) nightly (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

**Comment by stephendonner** [comment]
@spylogsster @rebron @yrliou @kjozwiak I think (once I verify it's fixed on `nightly`) that we'll want to take an uplift for this in `1.27.x`, given it's behaving as expected in `1.26.74`, but present in `1.27`:

<img width="1677" alt="Screen Shot 2021-07-08 at 10 47 29 AM" src="https://user-images.githubusercontent.com/387249/124968190-2d408600-dfda-11eb-8c57-df87f894837b.png">

**Comment by stephendonner** [comment]
@spylogsster this is verified on `nightly`; can you get an uplift going so we can fix this in `1.27.x`?  Thanks!

**Comment by stephendonner** [comment]
Blocked temporarily, until we get a new `beta` / release-candidate build, for testing.  Marking as `QA/Blocked`.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, 1.27.105 is available to check this issue.

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with 


Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 11.4 (Build 20F71)

Steps:

1. new profile
2. launched Brave
3. set `Method to resolve IPFS resources` to `Gateway` in `brave://settings/ipfs`
4. do either/both a Private Window / Guest Window
5. load `ipns://en.wikipedia-on-ipfs.org` or `ipfs://QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`

Confirmed `ipns://` and `ipfs://` URIs were blocked, but loaded in regular windows.

`IPFS`

private window | guest window | private window with Tor
----------------|---------------|------------------------
<img width="1312" alt="Screen Shot 2021-07-15 at 11 37 04 AM" src="https://user-images.githubusercontent.com/387249/125839916-a2c5e382-58ab-4fa7-9eef-b08633ca9b57.png"> | <img width="1312" alt="Screen Shot 2021-07-15 at 10 25 05 AM" src="https://user-images.githubusercontent.com/387249/125839678-2d9d6222-ba29-4213-8563-43a78753421d.png"> | <img width="1312" alt="Screen Shot 2021-07-15 at 10 25 24 AM" src="https://user-images.githubusercontent.com/387249/125839687-0d599d09-0a53-430e-b83b-da3860efd6aa.png">

`IPNS`

private window | guest window | private window with Tor
----------------|---------------|------------------------
<img width="1312" alt="Screen Shot 2021-07-15 at 11 38 09 AM" src="https://user-images.githubusercontent.com/387249/125840062-0d6bab28-25d1-4756-8098-e8659248cc37.png"> | <img width="1312" alt="Screen Shot 2021-07-15 at 11 38 18 AM" src="https://user-images.githubusercontent.com/387249/125840068-fe49692b-ccb8-440f-946e-5ff1b1df67cf.png"> | <img width="1312" alt="Screen Shot 2021-07-15 at 11 38 25 AM" src="https://user-images.githubusercontent.com/387249/125840072-4928556d-d511-495e-8b67-4b201d73fa7f.png">
