### ISSUE TITLE
Don't connect to Google for translations

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1674]
On startup, we seem to make connections to `https://www.gstatic.com/chrome/intelligence/assist/ranker/models/translate/translate_ranker_20180123.model`. We shouldn't.

Related to #633.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/47178302-d5710680-d2e8-11e8-8dab-a636d6db62f6.png)
