### ISSUE TITLE
Question mark in peer-deletion confirmation dialog is on a new line

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16742]
## Description 

(Super, super minor.)

Question mark in peer-deletion confirmation dialog is on a new line

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. set up a peer (see #15567 for full steps)
   4. load `brave://settings/ipfs/peers`
   5. click on the trash-can icon
   6. look at the resulting dialog

## Actual result:

```
Do you really want to delete
12D3KooWDL8FAiiaGoTuzsAFvKrNCHA2NnaNMDNYTTaqgAszY7R4
?
```

<img width="1312" alt="Screen Shot 2021-07-01 at 1 40 31 PM" src="https://user-images.githubusercontent.com/387249/124187031-06320380-da72-11eb-823a-dbd76234e1f9.png">

## Expected result:
`?` would preferably be on the same line; maybe truncate the long peer ID with `...` or something?

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.37 Chromium: 91.0.4472.124 (Official Build) nightly (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue.

proposed solution 
<code>
</code>

**Comment by deepxcode** [comment]
@stephendonner  Would like to work on this? Can you assign this to me?
Thank You.

**Comment by stephendonner** [comment]
> @stephendonner Would like to work on this? Can you assign this to me?
> Thank You.

Sure, thanks!

**Comment by deepxcode** [comment]
@stephendonner  I read the pre-requisites to set up a peer, Is it necessary to have to two different machines to make a peer, I only have one laptop with me.

**Comment by stephendonner** [comment]
> @stephendonner I read the pre-requisites to set up a peer, Is it necessary to have to two different machines to make a peer, I only have one laptop with me.

Nope; you can set up one on `nightly` and another on `beta` or `dev` (`1.27.x` branch`) - they use different ports.

**Comment by deepxcode** [comment]
Hey @stephendonner, I know how to truncate the string. 
The code is need to be changed in this file right? [settings_localized_strings_provider.cc](https://github.com/brave/brave-core/blob/master/chromium_src/chrome/browser/ui/webui/settings/settings_localized_strings_provider.cc)

The id is in line 296: {"ipfsDeletePeerConfirmation", IDS_SETTINGS_IPFS_DELETE_PEER_CONFIRMATION},
I can add a method in that file like this:
```
#include <iostream>
#include <string>
using namespace std;

string truncate(string str, size_t width, bool show_ellipsis=true)
{
    if (str.length() > width)
        if (show_ellipsis)
            return str.substr(0, width) + "...";
        else
            return str.substr(0, width);
    return str;
}
```
and then just do the following change 
` {"ipfsDeletePeerConfirmation", truncate(IDS_SETTINGS_IPFS_DELETE_PEER_CONFIRMATION, 8)},`

After this, I guess the issue will be resolved.
Am I allowed to write the above method (truncate) in the file?
If so, then I can resolve the issue.

Till now I am able to come up with this approach to resolve the issue, If you are not satisfied with this approach, I will think of another way.

**Comment by petemill** [comment]
I don't think truncating the string in c++ is appropriate when this is a display issue and can be fixed close to the UI in JavaScript. You can truncTe there but it's still a long string of random characters to put in. A sentence. Perhaps it would be better to separate the peer ID and the question, e.g.

```
[peer ID]
Are you sure you want to delete this IPFS peer?
```

**Comment by deepxcode** [comment]
Yes it would be better if we do that, will make the necessary changes and make the Pull request.
Thank you

**Comment by deepxcode** [comment]
So instead of 
```
      <message name="IDS_SETTINGS_IPNS_DELETE_KEY_CONFIRMATION" desc="Confirmation text for deleting a key from IPFS keys manager page">
        Do you really want to delete <ph name="KEY_NAME">$1<ex>MyCustomKey</ex></ph>?
      </message>
```

It will be, 

```
      <message name="IDS_SETTINGS_IPNS_DELETE_KEY_CONFIRMATION" desc="Confirmation text for deleting a key from IPFS keys manager page">
         <ph name="KEY_NAME">$1<ex>MyCustomKey</ex></ph>
         Are you sure you want to delete this IPFS peer?
      </message>
```

**Comment by wadehrarshpreet** [comment]
@rebron seems working fine. Can see `?` same line with peer `ipfs address`
<img width="659" alt="Screenshot 2022-05-27 at 11 18 54 PM" src="https://user-images.githubusercontent.com/15067013/170764115-da5274ff-c590-4916-99b7-2ba8ec7c9c0e.png">

Brave v1.39.111

**Comment by srirambv** [comment]
This seem to be fixed already based on the above comment and checked on `1.49.100` as well. Closing the issue for now. Can always reopen if it regresses.
