### ISSUE TITLE
estimated pending rewards does not reset to expected value when you have uncashed in tokens - follow up to #16678

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#16744]
## Description 

Fix for #16678 works great, except when a user has uncashed in tokens. In the likely event that a user has tokens which have not been cashed in with the server, this will not work. So a user will still see incorrect pending BAT for current month.

## Steps to Reproduce

   1. Have a profile in the bad state with uncashed in tokens
   2. Launch with 1.28.46
   3. Look at UI and logs

## Actual result:

ads panel UI does not accurately reflect estimated pending BAT (for current month or the coming ad grant)

logs still show

```
[21660:775:0701/163623.792441:INFO:ad_rewards.cc(280)] Payment balance is not ready
[21660:775:0701/163623.792517:VERBOSE1:ad_rewards.cc(355)] Failed to reconcile ad rewards
```

## Expected result:
Ads panel UI to be correct, no such messages in logs

## Reproduces how often: 

100% for my personal case

## Brave version (brave://version info)

```
Brave	1.28.46 Chromium: 92.0.4515.70 (Official Build) nightly (x86_64)
Revision	2df01a82398e62190b2aae01aaad7ca3d47aba01-refs/branch-heads/4515@{#923}
OS	macOS Version 10.15.7 (Build 19H1217)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @tmancey @kjozwiak @jsecretan

**Comment by kjozwiak** [comment]
@brave/legacy_qa please leave this one as we're planning on uplifting this into `1.26.x`. @LaurenWags will run through this one once we get a new `1.27.x` dev build created.

**Comment by LaurenWags** [comment]
Reverted, marked `QA/No` per https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1625774492272100?thread_ts=1625143188.230600&cid=CHGKGMHDJ
