### ISSUE TITLE
[hackerone] #1249056 Tor log

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#16747]
https://hackerone.com/reports/1249056

We need to get rid of the disk tor.log and then replace them with control channel events 

`SETEVENTS NOTICE`, `SETEVENTS WARN` and `SETEVENTS ERR` with or without timestamp

**Comment by stephendonner** [comment]
Hi @darkdh; given this has a test plan (thanks!), is it `QA/Yes`?

**Comment by darkdh** [comment]
@stephendonner yeah, I forgot to added QA related labels, added!

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.27.101 Chromium: 91.0.4472.124 (Official Build) beta (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

### Tor log check:

1. new profile
2. launched Brave `beta`
3. opened `brave://tor-internals` and went to the `Logs` tab
4. opened `https://brave5t5rjjg3s6k.onion/` in a `New Private Window with Tor`
5. took note of `NOTICE` and `WARN` logged info/warnings, without timestamps
6. checked `/Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser-Beta` for the presence of a `tor.log` file; confirmed there was none

example | example | example | example
---------|----------|----------|--------
<img width="1446" alt="Screen Shot 2021-07-12 at 11 13 10 AM" src="https://user-images.githubusercontent.com/387249/125338081-9d197e00-e304-11eb-9a75-fab3a22968f9.png"> | <img width="1792" alt="Screen Shot 2021-07-12 at 11 13 14 AM" src="https://user-images.githubusercontent.com/387249/125338097-a0146e80-e304-11eb-8f8b-58b5ded2d422.png"> | <img width="975" alt="Screen Shot 2021-07-12 at 11 14 42 AM" src="https://user-images.githubusercontent.com/387249/125338102-a276c880-e304-11eb-8e18-4f7ff333eccb.png"> | <img width="1109" alt="Screen Shot 2021-07-12 at 11 15 34 AM" src="https://user-images.githubusercontent.com/387249/125338176-bae6e300-e304-11eb-9a37-24801f6c2896.png">


### Tor log migration:

1. launched `1.26.74`
2. opened `https://brave5t5rjjg3s6k.onion/` in a `New Private Window with Tor`
3. quit Brave
4. deleted `Brave-Browser-Beta` profile folder
5. renamed `1.26.74` profile folder from `Brave-Browser` to `Brave-Browser-Beta`
6. confirmed the above folder had a previous `tor.log` file
7. launched Brave `beta` with the above folder
8. opened `https://brave5t5rjjg3s6k.onion/` in a `New Private Window with Tor`
9. saw `tor.log` disappear from disk

example | example | example | example
---------|---------|----------|----------
<img width="1240" alt="Screen Shot 2021-07-12 at 11 14 21 AM" src="https://user-images.githubusercontent.com/387249/125338344-e9fd5480-e304-11eb-836c-8ca378aefd77.png"> | <img width="1301" alt="Screen Shot 2021-07-12 at 11 24 16 AM" src="https://user-images.githubusercontent.com/387249/125338380-f681ad00-e304-11eb-908f-994882f29845.png"> | <img width="1301" alt="Screen Shot 2021-07-12 at 11 25 41 AM" src="https://user-images.githubusercontent.com/387249/125338412-000b1500-e305-11eb-80f2-46e0756a6a63.png"> | <img width="1102" alt="Screen Shot 2021-07-12 at 11 26 42 AM" src="https://user-images.githubusercontent.com/387249/125338415-000b1500-e305-11eb-9674-d5e812219147.png">
