### ISSUE TITLE
NTP is blank on C92 Nightly

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#16740]
## Description 

New tab page is blank on C92 Nightly.

## Steps to Reproduce

   1. Clean profile with 1.28.46
   2. Open NTP

## Actual result:

<img width="1198" alt="Screen Shot 2021-07-01 at 4 04 48 PM" src="https://user-images.githubusercontent.com/28145373/124187330-aea09180-da8b-11eb-9d30-bd7b97c7d3e2.png">

<img width="1194" alt="Screen Shot 2021-07-01 at 4 11 41 PM" src="https://user-images.githubusercontent.com/28145373/124187333-b06a5500-da8b-11eb-9596-4d8f91e0b187.png">

## Expected result:
regular NTP with image and widgets

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave	1.28.46 Chromium: 92.0.4515.70 (Official Build) nightly (x86_64)
Revision	2df01a82398e62190b2aae01aaad7ca3d47aba01-refs/branch-heads/4515@{#923}
OS	macOS Version 10.15.7 (Build 19H1217)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @mkarolin @petemill

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.49 Chromium: 92.0.4515.70 (Official Build) nightly (x86_64)
-- | --
Revision | 2df01a82398e62190b2aae01aaad7ca3d47aba01-refs/branch-heads/4515@{#923}
OS | macOS Version 11.4 (Build 20F71)

Confirmed the new-tab page is back, with Sponsored Image and now-fixed Brave Together (Talk) tooltip, too.


example | example
---------|----------
<img width="1711" alt="Screen Shot 2021-07-02 at 2 42 44 PM" src="https://user-images.githubusercontent.com/387249/124331266-e23ef280-db43-11eb-84a8-8a438a936faf.png"> | <img width="1634" alt="Screen Shot 2021-07-02 at 1 24 07 PM" src="https://user-images.githubusercontent.com/387249/124331261-e0752f00-db43-11eb-97cc-d753d59aa1cd.png">
