### ISSUE TITLE
fix additional instance of Brave Payments, change 2 instances of "creators" to "content creators"

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#1675]
https://github.com/brave/brave-core/pull/672

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

* Verified text updates on 'Tips' panel on `brave://rewards`
![screen shot 2018-10-18 at 5 35 20 pm](https://user-images.githubusercontent.com/28145373/47185750-584f8c80-d2fc-11e8-93d3-4f38e67aaf65.png)
* Verified text update on Add Funds
![screen shot 2018-10-18 at 5 35 40 pm](https://user-images.githubusercontent.com/28145373/47185762-5f769a80-d2fc-11e8-8e21-38078e53cf97.png)
