### ISSUE TITLE
Change batLimit modal text to talk about ID verification in Uphold case

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16759]
## Description

![image](https://user-images.githubusercontent.com/11497541/124295365-c11bd900-db26-11eb-88a9-7a3c68c30132.png)

## Solution

Text should say: 

>**You need a fully verified account to log in**
>
>Please try again after you have completed ID verification on Uphold.

**Comment by szilardszaloki** [comment]
https://github.com/brave/brave-core/pull/9212#issuecomment-869072578

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/9530 with

Brave | 1.29.31 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5.1 (Build 20G80)

Steps:
1. new profile
2. launched Brave
3. clicked on the BAT icon in the URL bar
4. enabled Rewards
5. clicked on `Verify Wallet`
6. clicked the `Continue` button
7. clicked on the `Continue to login` button
8. on the Uphold screen, clicked `Authorize`
9. entered my Brave credentials (have account but not KYC'd like my personal gmail)
10. clicked on `Login`

Confirmed I got the `You need a verified wallet to log in` modal message.


example | example | example | example | example
---------|----------|---------|---------|----------
<img width="1752" alt="Screen Shot 2021-07-27 at 3 08 52 PM" src="https://user-images.githubusercontent.com/387249/127234414-ccd6af1d-7f45-4042-82c0-4f622f32ebbb.png"> | <img width="1752" alt="Screen Shot 2021-07-27 at 3 08 15 PM" src="https://user-images.githubusercontent.com/387249/127234491-4a8e06ea-1c4c-4c6a-b39c-7937236daf36.png"> | <img width="1752" alt="Screen Shot 2021-07-27 at 3 08 19 PM" src="https://user-images.githubusercontent.com/387249/127234509-4809376d-c9d9-4f0b-8b7c-34b4c21f6810.png"> | <img width="1752" alt="Screen Shot 2021-07-27 at 3 08 24 PM" src="https://user-images.githubusercontent.com/387249/127234532-08f15a34-c437-4bf0-bcff-7989eafd7b95.png"> | <img width="1752" alt="Screen Shot 2021-07-27 at 3 08 05 PM" src="https://user-images.githubusercontent.com/387249/127234580-80748f5c-117b-41e3-a381-817f284672a2.png">
