### ISSUE TITLE
Missing Translations for new swap feature

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16755]
## Description 

Brave specific text changes needs translations

## Steps to Reproduce

   1. Set locale to French
   2. Follow swap options
   3. Brave specific text changes are not translated

## Actual result:

Tooltip | Swap Screen | Swap settings | Set Allowance Tooltip
-- | -- | -- |--
![image](https://user-images.githubusercontent.com/17010094/124262157-98e1a980-db29-11eb-8215-eedcf90b4208.png) | ![image](https://user-images.githubusercontent.com/17010094/124262415-efe77e80-db29-11eb-8ed4-9fd7ca8bb76d.png) | ![image](https://user-images.githubusercontent.com/17010094/124262276-bf9fe000-db29-11eb-9a0e-ce6501fdf5c0.png) | ![image](https://user-images.githubusercontent.com/17010094/124262697-3e951880-db2a-11eb-9227-1f971440e857.png)

## Expected result:
Translated text everywhere (applicable)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.26.74 Chromium: 91.0.4472.124 (Official Build) (x86_64)
-- | --
Revision | `7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.32 Dev`

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy

**Comment by bbondy** [comment]
Updated l10n:
https://github.com/brave/ethereum-remote-client/commit/804a8438de94c6deb945a748f35158dd6c31895a

**Comment by srirambv** [comment]
@bbondy Not all strings are translated. Since translated are already merged to master we can keep this issue open and move it out of the milestone and for next release have all strings translated and verified

**Comment by bbondy** [comment]
Most translations re-pulled in here:
https://github.com/brave/ethereum-remote-client/commit/092477c547a49b155e755b44666d21393bb57adc

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.28.37 Chromium: 91.0.4472.124 (Official Build) nightly (64-bit)
-- | --
Revision | `7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}`
OS | Linux
Component | `1.0.33 Dev`

French

![image](https://user-images.githubusercontent.com/17010094/124958205-cd65d180-e011-11eb-890e-b700a1eb1015.png) | ![image](https://user-images.githubusercontent.com/17010094/124958254-dd7db100-e011-11eb-9486-cabed49c1e8c.png) | ![image](https://user-images.githubusercontent.com/17010094/124958315-f0908100-e011-11eb-9cb1-041945973ce3.png) | ![image](https://user-images.githubusercontent.com/17010094/124958360-fbe3ac80-e011-11eb-9bc1-0669d7d15098.png)
-- | -- | -- | --

German

![image](https://user-images.githubusercontent.com/17010094/124958995-aa87ed00-e012-11eb-8dfa-aa049d6f7075.png) |![image](https://user-images.githubusercontent.com/17010094/124958931-9d6afe00-e012-11eb-8776-20d70d4fdeb0.png) |![image](https://user-images.githubusercontent.com/17010094/124958824-7dd3d580-e012-11eb-9760-1325b8ae5792.png)  |  ![image](https://user-images.githubusercontent.com/17010094/124958859-86c4a700-e012-11eb-9508-2456ecf079be.png) 
-- | -- | -- | --
