### ISSUE TITLE
.PNG .JPG and .GIF files cannot be viewed via IPFS import

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16758]
## Description 

Found while testing #16267
.PNG .JPG and .GIF files cannot be viewed via IPFS import
## Steps to Reproduce

   1. Clean profile 1.27.x
   2. Launch brave `using --use-dev-goupdater-url`
   3. Make sure IPFS version is `0.9.0` in brave://ipfs-internals
   4. Import .PNG .JPG and .GIF files from the local machine
   3. Import is successful but files can't be viewed

## Actual result:

.PNG and .JPG files cannot be viewed via IPFS import
![image](https://user-images.githubusercontent.com/38657976/124292377-209fd600-db73-11eb-8cbb-00b886282242.png)

![image](https://user-images.githubusercontent.com/38657976/124297462-b722c600-db78-11eb-89cf-a7b3f7326497.png)

## Expected result:
Should be able to view .PNG and .JPG files via IPFS import

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.27.87 Chromium: 91.0.4472.124 (Official Build) beta (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster @brave/legacy_qa @rebron

**Comment by stephendonner** [comment]
@GeetaSarvadnya if you turn off Shields, does it render?

I had a similar issue on Linux, also `1.27.87`:

Shields up | Shields down
-----------|--------------
<img width="1540" alt="Screen Shot 2021-07-02 at 2 06 48 PM" src="https://user-images.githubusercontent.com/387249/124329071-a6099300-db3f-11eb-9b44-3283f21748c3.png"> | <img width="1540" alt="Screen Shot 2021-07-02 at 2 07 45 PM" src="https://user-images.githubusercontent.com/387249/124329075-a7d35680-db3f-11eb-863a-0245807bf55a.png">

/cc @spylogsster

**Comment by lidel** [comment]
This seems to be a variant of https://github.com/brave/brave-browser/issues/13641 however here we are on a trusted API port (45004) that tries to fetch the image from the Gateway port (45083). 

This is pretty safe environment, as both Origins are controlled by Brave (brave runs go-ipfs binary, which exposes those ports)

I  think the right  way of fixing this class of bugs is to allow  API port to fetch data from local Gateway.

**Comment by GeetaSarvadnya** [comment]
@stephendonner with Shields ON/OFF I am getting the same issue.

![IPFS_Shileds ON or OFF](https://user-images.githubusercontent.com/38657976/124559774-b2506180-de59-11eb-98de-b86eb97e9c77.gif)

**Comment by lidel** [comment]
This is the same issue as https://github.com/brave/brave-browser/issues/16752#issuecomment-874684824
(Due to fallback the preview image is being fetched from ipfs.io instead of local gateway.)

The fix here is to wait until we have go-ipfs 0.9.1 with bugfix release of webui: ipfs/go-ipfs#8243

**Comment by spylogsster** [comment]
blocked by https://github.com/ipfs/go-ipfs/pull/8243

**Comment by stephendonner** [comment]
@GeetaSarvadnya mind retesting with `go-ipfs` version `0.9.1` now that it's out using `--use-dev-goupdater-url`?

This worked for me using 

Brave | 1.30.15 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

<img width="1312" alt="Screen Shot 2021-08-11 at 3 24 37 PM" src="https://user-images.githubusercontent.com/387249/129111670-019cf0e3-e4f6-4a8d-86f3-9e162030c6d4.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

and `go-ipfs` `0.9.1`

example | example | example | example
---------|----------|---------|----------
<img width="1489" alt="Screen Shot 2021-08-18 at 1 07 02 PM" src="https://user-images.githubusercontent.com/387249/129965878-a64339d8-90f3-44ab-8aea-5357370b6a02.png"> | <img width="1489" alt="Screen Shot 2021-08-18 at 1 08 01 PM" src="https://user-images.githubusercontent.com/387249/129965882-f737c543-6940-4c66-8a22-d00a8443929e.png"> | <img width="1489" alt="Screen Shot 2021-08-18 at 1 08 39 PM" src="https://user-images.githubusercontent.com/387249/129965883-21ea1956-fb29-4382-915f-1393547775bb.png"> | <img width="1489" alt="Screen Shot 2021-08-18 at 1 08 51 PM" src="https://user-images.githubusercontent.com/387249/129965885-85fab58c-4f88-48ad-b535-0e305f1df0d4.png">

**Comment by GeetaSarvadnya** [comment]
@stephendonner Apologies somehow missed the issue. Today I have verified the issue on Windows 10 x64 - `1.28.106` build issue is fixed and working fine with ipfs component `0.9.1`
