### ISSUE TITLE
DNS leak while using vpn

### ISSUE THREAD

**Issue by specter78** [brave/brave-browser#16751]
## Description 
I have nextdns (app store app) and openvpn via Passepartout enabled at the same time.

When browsing using brave, dns requests go through nextdns (which exposes local ip) while browser ip is determined by vpn.

## Steps to Reproduce
Please refer to the description above.

## Actual result:
When browsing using brave, dns requests go through nextdns (which exposes local ip) while browser ip is determined by vpn.

## Expected result:
Both DNS requests as well as browser traffic should go through vpn.

## Reproduces how often: 
Every time

## Brave version (brave://version info)

Brave - 1.26.74 Chromium: 91.0.4472.124 (Official Build) (x86_64)
Revision - 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{6}
OS - macOS Version 11.4

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? don't know
- Can you reproduce this issue with the nightly channel? don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? na
- Does the issue resolve itself when disabling Brave Rewards? na
- Is the issue reproducible on the latest version of Chrome? don't know 

## Miscellaneous Information:
If nextdns app is disabled, dns requests go though vpn, which is what should normally happen. **However, in this case, page load time increases substantially.**

Firefox doesn't have this issue.

**Comment by ryanbr** [comment]
Can you replicate in Chrome? @specter78

**Comment by specter78** [comment]
@ryanbr I don't use chrome.

**Comment by ryanbr** [comment]
> @ryanbr I don't use chrome.

This would help debug whether its a Chromium specific issue or just Brave

**Comment by specter78** [comment]
It happens in chrome.

**Comment by ryanbr** [comment]
Okay, We'll need to log https://bugs.chromium.org/p/chromium/issues/list    I don't mind helping here, I would need debug logs on what you're seeing, and step-by-step instructions to reproduce the issue @specter78

**Comment by diracdeltas** [comment]
There was a version of this that only existed in Brave, which @antonok-edm fixed in https://github.com/brave/brave-core/pull/8957

**Comment by specter78** [comment]
Does Brave have CNAME uncloaking enabled? Because tabs load very slowly in normal window, but with normal performance in private window.

**Comment by specter78** [comment]
@ryanbr 

Here are the step-by-step instructions to reproduce the issue.

1. Install and run NextDNS app from mac app store (I'm using custom configuration)
2. Install and run vpn using Passepartout app from mac app store
3. Open ipleak.net in Brave
4. The website shows DNS close to my actual location.
5. Disable NextDNS app
6. The website shows DNS close to vpn location.

**Comment by ryanbr** [comment]
Does the same issue show up in Brave Beta @specter78 ?

**Comment by specter78** [comment]
@ryanbr Yes, both issues (slow loading in normal window and DNS leak issue) happen in brave beta also. However, neither of the issue happens in safari or firefox.

**Comment by ryanbr** [comment]
@antonok-edm  This wouldn't be related to the recent CNAME issues?

**Comment by diracdeltas** [comment]
thanks @neeythann, closing for now
