### ISSUE TITLE
Feature/category headings in the left-most pane in Settings shift on click

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16765]
## Description 

Category headings in the left-most pane in Settings shift on click

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open `brave://settings/` and click on the feature-area heading under `Settings`
   4. look at the focus ring and pane heading

## Actual result:

There's a (new) purple focus ring, and the heading item shifts on mouse-click/mouse-release.

![menu-items](https://user-images.githubusercontent.com/387249/124326815-f848b500-db3b-11eb-9317-57cc07db30eb.gif)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.49 Chromium: 92.0.4515.70 (Official Build) nightly (x86_64)
-- | --
Revision | 2df01a82398e62190b2aae01aaad7ca3d47aba01-refs/branch-heads/4515@{#923}
OS | macOS Version 11.4 (Build 20F71)

/cc @mkarolin @spylogsster: can you take a look?  see https://github.com/brave/brave-core/pull/9301#issuecomment-873201512

**Comment by spylogsster** [comment]
Fixed here https://github.com/brave/brave-browser/issues/16776

**Comment by stephendonner** [comment]
Although this was filed days earlier, this was re-filed and fixed over in https://github.com/brave/brave-browser/issues/16776, which means I'm duping this issue to that, and removing `QA/Yes` keyword, since we'll be verifying over in https://github.com/brave/brave-browser/issues/16776.
