### ISSUE TITLE
Disable connections to - https://clients1.google.com/tbproxy/af/query

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1676]
This is required for autofill-download - looks like this can be disabled by disabling `kAutoFillServerCommunication`

https://cs.chromium.org/chromium/src/components/autofill/core/browser/autofill_download_manager.cc?type=cs&g=0&l=104

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/47178447-3ef11500-d2e9-11e8-80a9-e27315173723.png)
