### ISSUE TITLE
Tab shows default favicon for NTP with C92.

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#16773]
We've not been set favicon for NTP. This is introduced at C92.

<img width="426" alt="Screen Shot 2021-07-05 at 3 36 39 PM" src="https://user-images.githubusercontent.com/6786187/124427806-d9019000-dda6-11eb-8ba0-4b9f2cc0027a.png">

Upstream change: https://chromium-review.googlesource.com/c/chromium/src/+/2785855

**Comment by rebron** [comment]
cc: @karenkliu

**Comment by karenkliu** [comment]
Remove it 👌

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

```
- Verified the STR from the description and ensured default favicon isn't shown for NTP in Normal/Private/Guest/Tor windows

**_Normal windows_**
![image](https://user-images.githubusercontent.com/38657976/125759858-58f28880-1ec0-4dc1-8fc9-0b55a9b65ab8.png)

**_Private windows_**
![image](https://user-images.githubusercontent.com/38657976/125760038-d1a2c2b3-0f34-45d2-863a-ba96cb48c576.png)

**_Guest windows_**
![image](https://user-images.githubusercontent.com/38657976/125760416-59d75c45-9ecf-4feb-b410-be85181adeaa.png)

**_TOR windows_**
![image](https://user-images.githubusercontent.com/38657976/125760611-e72b68d0-21f1-4325-82ff-02aacf000fa8.png)
