### ISSUE TITLE
Focus state causing the UI element to shift

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16776]
## Description 

In https://github.com/brave/brave-browser/issues/16111 focus state causing the UI element to shift

## Steps to Reproduce

- Open settings and click by any menu item

## Expected result:

element is not shifted

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

Steps:

1. new profile
2. launched Brave
3. opened `brave://settings/` and clicked on the various feature-area heading under `Settings` (e.g. `IPFS` in the screenshots below)
4. looked at the focus ring and pane heading

Confirmed:
* hover color is "blurple"
* clicked-state color is orange

hover | clicked
------|--------
<img width="1748" alt="Screen Shot 2021-07-06 at 3 09 45 PM" src="https://user-images.githubusercontent.com/387249/124672734-63f88e00-de6c-11eb-9ec1-67b831198cde.png"> | <img width="1748" alt="Screen Shot 2021-07-06 at 3 10 00 PM" src="https://user-images.githubusercontent.com/387249/124672737-65c25180-de6c-11eb-9bde-e8de80ed9a12.png">
