### ISSUE TITLE
"An unexpected error has occurred." - IGN.com

### ISSUE THREAD

**Issue by Patora1701** [brave/brave-browser#16785]
## Description 
Error message "An unexpected error has occurred." when visiting IGN.com.

## Steps to Reproduce

   1.  go to www.ign.com
   2. 
   3. 

## Reproduces how often: 
Always

## Brave version (brave://version info)
Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)

**Comment by ryanbr** [comment]
Hey, checked the site. Worked fine here. Does it work in private window mode? @Patora1701

**Comment by Patora1701** [comment]
Yes, it does work in private mode.

**Comment by ryanbr** [comment]
Can you retest in normal window mode, and also disable extensions?

**Comment by Patora1701** [comment]
OK, It appears the Malwarebytes Browser Guard extension was the culprit. The website works when it is disabled.
