### ISSUE TITLE
Reddit inline ads are not blocked on Android when shields are set to aggressive

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#16789]
## Description 
Unlike the desktop Brave browser, Reddit inline ads are not blocked on Android when shields are set to aggressive.

## Steps to reproduce 

   1. Launch Brave on Android
   2. Set Brave shields to aggressive
   3. Go to reddit.com
   4. Notice that an inline ad usually shows up as the second post in the feed.

## Actual result 
![image](https://user-images.githubusercontent.com/241316/124644506-32b99700-de47-11eb-842f-7ced643e59de.png)

## Expected result
No inline ads are shown when Brave shields are set to aggressive.

## Issue reproduces how often 
Every time

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Not tested
- Can you reproduce this issue with the current Play Store Nightly version? Not tested

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 5
   - Android version: Android 12 Beta
   
## Brave version
1.26.74

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tortino** [comment]
yes please block promoted ads!

**Comment by ryanbr** [comment]
Is fixed via `reddit.com##.size-compact.Post:has([class*="promoted"])`  in [uBO](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L4767). We currently don't support procedural filters (Like :has) 

Reference ticket for procedural filters https://github.com/brave/brave-browser/issues/16935

**Comment by tortino** [comment]
but on desktop the reddit promoted ads are already blocked.
does this means that the ad blocking engine on android is not the same as the one on desktop?

**Comment by 424344** [comment]
any news on this?

**Comment by antonok-edm** [comment]
I think we can close this as of https://github.com/brave/brave-browser/issues/27874. I confirmed I wasn't able to find any promoted content on Reddit's mobile website in Nightly.
