### ISSUE TITLE
Crash in sidebar::SidebarService::GetNotAddedDefaultSidebarItems

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#16787]
```
[ 00 ] <name omitted>
[ 01 ] <name omitted>
[ 02 ] <name omitted>
[ 03 ] sidebar::SidebarService::GetNotAddedDefaultSidebarItems() const
[ 04 ] sidebar::SidebarModel::IsSidebarHasAllBuiltiInItems() const
[ 05 ] SidebarControlView::SidebarControlView(BraveBrowser*)
[ 06 ] SidebarContainerView::Init()
[ 07 ] BraveBrowserView::InitSidebar()
[ 08 ] BraveBrowser::BraveBrowser(Browser::CreateParams const&)
[ 09 ] SessionRestoreImpl::CreateRestoredBrowser(Browser::Type, gfx::Rect, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, ui::WindowShowState, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)
[ 10 ] SessionRestoreImpl::ProcessSessionWindows(std::__1::vector<std::__1::unique_ptr<sessions::SessionWindow, std::__1::default_delete<sessions::SessionWindow> >, std::__1::allocator<std::__1::unique_ptr<sessions::SessionWindow, std::__1::default_delete<sessions::SessionWindow> > > >*, SessionID, std::__1::vector<SessionRestoreDelegate::RestoredTab, std::__1::allocator<SessionRestoreDelegate::RestoredTab> >*, int*, int*)
[ 11 ] SessionRestoreImpl::ProcessSessionWindowsAndNotify(std::__1::vector<std::__1::unique_ptr<sessions::SessionWindow, std::__1::default_delete<sessions::SessionWindow> >, std::__1::allocator<std::__1::unique_ptr<sessions::SessionWindow, std::__1::default_delete<sessions::SessionWindow> > > >*, SessionID)
[ 12 ] SessionRestoreImpl::Restore()
```

https://brave.sp.backtrace.io/p/brave/triage?filters=((callstack.functions%2Ccontains%2Csidebar)%2Cptype%3Dbrowser%2Cver%3E%3D%2291%22)&aggregations=((guid%2Cunique)%2C(classifiers%2Chead))&similarity=false

**Comment by iefremov** [comment]
cc @simonhong

**Comment by stephendonner** [comment]
Sadly (sorry!) this is fallout from my "simple string change" over in https://github.com/brave/brave-browser/issues/16709.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/9347

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan here with build 


Brave | 1.28.70 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)



Steps:

1. clean profile
2. launched Brave
3. enabled sidebar via `brave://flags/#sidebar`
4. restarted when prompted
5. confirmed Brave relaunches without crash after toggling `brave://flags/#sidebar` to true

<img width="1792" alt="Screen Shot 2021-07-09 at 12 01 58 PM" src="https://user-images.githubusercontent.com/387249/125124901-af4daf00-e0ad-11eb-9283-1c52fa5d3fea.png">

**Comment by GeetaSarvadnya** [comment]
@simonhong I don't see the `Enable Sidebar` flag under brave://flags in Brave Beta `1.28.91` but it exists in Dev `1.28.89` version

![image](https://user-images.githubusercontent.com/38657976/127035151-5e8c1deb-b4ea-4436-9a0d-ba759ad25332.png)

**Comment by simonhong** [comment]
@GeetaSarvadnya Sidebar feature is not available for beta/stable channel now.
