### ISSUE TITLE
IPFS support for Brave Rewards

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16793]
Update https://github.com/brave/brave-browser/issues/9631 solution to enable rewards only for IPNS urls that have dnslink record

**Comment by stephendonner** [comment]
@spylogsster should this be `QA/Yes`, and if so, what's the test plan?  Thanks!  /cc @brave/legacy_qa

**Comment by spylogsster** [comment]
closed as duplicate to https://github.com/brave/brave-browser/issues/16612
