### ISSUE TITLE
Make corners rounded for selector on settings menu

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16794]
## Description 

by design it should have rounded corners https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=491%3A13498

## Steps to Reproduce

open settings and press Tab to select menu item

## Actual result:

selection corners are not rounded

## Expected result:

selection corners are rounded

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.28.60 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 12.0 (Build 21A5268h)

Steps:
1. clean profile
2. launched Brave
3. opened `brave://settings/`
4. cycled through left-pane category items using `Tab`, to get focus rings
5. examined the focus ring

Dark, before | Light, before | Dark, after | Light, after
-------------|--------------|------------|-----------
<img width="1507" alt="Screen Shot 2021-07-07 at 3 39 48 PM" src="https://user-images.githubusercontent.com/387249/124837687-30843500-df3a-11eb-9287-770ca98a09e7.png"> | <img width="1507" alt="Screen Shot 2021-07-07 at 3 39 24 PM" src="https://user-images.githubusercontent.com/387249/124837706-3aa63380-df3a-11eb-898e-c9bde5740fc9.png"> | <img width="1507" alt="Screen Shot 2021-07-07 at 3 40 42 PM" src="https://user-images.githubusercontent.com/387249/124837727-498ce600-df3a-11eb-9f56-19292da44505.png"> | <img width="1507" alt="Screen Shot 2021-07-07 at 3 40 53 PM" src="https://user-images.githubusercontent.com/387249/124837734-4b56a980-df3a-11eb-9839-9983b9f19eea.png">

**Comment by bsclifton** [comment]
I agree with comment by @petemill:
https://github.com/brave/brave-core/pull/9345#issuecomment-876592931

Basically the borders for focus ring look a bit tight. @karenkliu WDYT?

**Comment by karenkliu** [comment]
Yeah, it does look tight. As I mentioned in this issue https://github.com/brave/brave-browser/issues/13688, we still need to bring the settings page in line with the Brave design system:

- update all typography to Poppins
- update icons with ones from our Brave icon library
- update dark theme colors
- remove shadows from the cards

The updated sidenav design also has a larger click target than what's currently in the browser:
![image](https://user-images.githubusercontent.com/2388823/125339462-2b423400-e306-11eb-92f8-7c3ec13e513f.png)

Looks like the browser has a click target height in the low 20s; this is smaller than even our smallest button height - 32px. The  sidebar items need to have a minimum click target height of 32px. What I've mocked up has a custom 34px height (Might be worthwhile to even bump it up to 40px, our default button height).
