### ISSUE TITLE
Brave Together text and image assets should read Brave Talk, in new-tab page's cards

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16798]
## Description 

Brave Together text and image assets should read Brave Talk, in new-tab page's cards

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open a new-tab page
   4. click on `Customize` on the bottom right
   5. click on `Cards`
   6. look at `Brave Together`'s text and image
   7. click `+ Add`
   8. now, look at the added widget
   9. click on the `...` and look at the resulting menu item

## Actual result:

`Cards` pane | `Brave Together` widget | `Hide Brave Together` menu item
--------------|--------------------------|----------------------------------
<img width="1748" alt="Screen Shot 2021-07-06 at 4 26 11 PM" src="https://user-images.githubusercontent.com/387249/124678510-83e17f00-de77-11eb-8b37-14dbfc1d252a.png"> | <img width="310" alt="Screen Shot 2021-07-06 at 4 32 14 PM" src="https://user-images.githubusercontent.com/387249/124678686-e9357000-de77-11eb-877b-6870817acd31.png"> | <img width="302" alt="Screen Shot 2021-07-06 at 4 32 09 PM" src="https://user-images.githubusercontent.com/387249/124678619-bee3b280-de77-11eb-8fce-881d2159d57e.png">

## Expected result:

Should read `Brave Talk` in each of the above 3 UI elements.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

@karenkliu can you/the team help provide new assets?  Thanks!

/cc @simonhong @petemill (I'll leave renaming to the pros, since I don't know what else I could break with simple text changes!)

**Comment by karenkliu** [comment]
Here's the link to the updated asset in Figma: https://www.figma.com/file/0pOzvvueMoeaCxKaVoU59Z/Widget-discovery?node-id=2506%3A23053 :)

**Comment by stephendonner** [comment]
Verified `FIXED` using the inline testplan with 


Brave | 1.29.36 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5.1 (Build 20G80)

Steps:

1. new profile
2. launch Brave
3. open a new-tab page
4. click on `Customize` on the bottom right
5. click on `Cards`
6. look at `Brave Talk`'s text and image
7. click ``+ Add`
8. now, look at the added widget
9. click on the `...` and look at the resulting menu item

cards pane | new-tab page widget w/`Hide` menu item
------------|------------------------------------------
<img width="1312" alt="Screen Shot 2021-07-28 at 3 33 52 PM" src="https://user-images.githubusercontent.com/387249/127405257-ba78c48a-26e6-4372-b009-1c6d8740d42d.png"> | <img width="1312" alt="Screen Shot 2021-07-28 at 3 37 37 PM" src="https://user-images.githubusercontent.com/387249/127405309-9eac13fb-5942-4892-9558-d4479f6c5022.png">

**Comment by stephendonner** [comment]
@bsclifton mind getting an uplift going for `1.28.x`? /cc @mattmcalister

**Comment by bsclifton** [comment]
@stephendonner done - https://github.com/brave/brave-core/pull/9608

**Comment by LaurenWags** [comment]
Changing label to `release-notes/exclude` since Brave Talk is not enabled in this release.
