### ISSUE TITLE
Refactor: Make rewards notification service an observer

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#1679]
@bridiver mentioned the following in regards to the `RewardsNotificationsService`:

> [...] this really doesn't make sense as separate keyed service. I think this should be a RewardsServiceObserver that is owned by RewardsService and be access through RewardsServiceFactory::GetInstance()->GetForProfile(profile)->notification_service();

Sounds like a good plan and shouldn't be too hard to implement.

**Comment by kjozwiak** [comment]
@emerick is there a test case that QA can go through to verify this particular issue? This was labelled as `QA/Yes` but there's nothing QA can use either in the original comment or https://github.com/brave/brave-core/pull/739 in terms of STR/test cases.

**Comment by emerick** [comment]
@kjozwiak Yeah, I believe `QA/No` is more appropriate. I relabeled it.
