### ISSUE TITLE
Change Brave Together to Brave Talk in new-tab page promo tooltip popup

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16799]
## Description 

Change Brave Together to Brave Talk in new-tab page promo tooltip popup

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open a new-tab page
   4. look at the `Brave Together` promo tooltip/popup near the bottom-right of the screen

## Actual result:

`Start unlimited calls with friends and colleagues in Brave Together.`

<img width="376" alt="Screen Shot 2021-07-06 at 10 18 36 AM" src="https://user-images.githubusercontent.com/387249/124679091-ac1dad80-de78-11eb-890f-a7e56764d1fb.png">

## Expected result:

`Start unlimited calls with friends and colleagues in Brave Talk.`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

/cc @karenkliu @rebron

**Comment by deepxcode** [comment]
@stephendonner  I am ready to work on this, Can you assign this to me?
I will be making pull request for the last issue and this issue soon

**Comment by deepxcode** [comment]
@stephendonner Since I am a beginner, how do I contribute to the nightly build? Like which branch should I change my code to fix this issue?

**Comment by stephendonner** [comment]
Sure, assigned to you @deepxcode; for starters, you should be able to find the string in https://github.com/brave/brave-core

**Comment by deepxcode** [comment]
@stephendonner  Can you review the pull request I made? It fixes this issue.

**Comment by stephendonner** [comment]
Fixed by https://github.com/brave/brave-core/pull/9368 - not sure why this didn't get auto-resolved.

**Comment by stephendonner** [comment]
Sorry @deepxcode and @petemill I'm not seeing this fixed on `nightly` / `master`, likely because it was targeted for and I merged it into `1.27.x`, instead of `master`, right?

@petemill are you able to help? sorry and thanks!

**Comment by deepxcode** [comment]
I guess, the PR was supposed to be merged in `master`, and it got merged into `1.27.x`. If you want, I can create another PR with the following changes and will target the merge to the `master` branch.
Let me know If I you want me to do this.

**Comment by stephendonner** [comment]
> I guess, the PR was supposed to be merged in `master`, and it got merged into `1.27.x`. If you want, I can create another PR with the following changes and will target the merge to the `master` branch.
> Let me know If I you want me to do this.
> @stephendonner and @petemill

Yes please @deepxcode and sorry and thanks! 🙏

**Comment by deepxcode** [comment]
@stephendonner  Made the change, now the PR will get merged into the master branch. The issue must be resolved now.
Thank You

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.29.12 Chromium: 92.0.4515.101 (Official Build) nightly (x86_64)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launch Brave
3. open a new-tab page
4. look at the orange-colored promo on the bottom-right of the page

Confirmed it now reads `Start unlimited calls with friends and colleagues in Brave Talk.`

<img width="1618" alt="Screen Shot 2021-07-20 at 11 24 27 AM" src="https://user-images.githubusercontent.com/387249/126376894-04e55f3f-71ea-43bb-948a-8ce44748a964.png">

**Comment by stephendonner** [comment]
Thanks again @deepxcode !

**Comment by deepxcode** [comment]
Anytime @stephendonner 😃🎉

**Comment by stephendonner** [comment]
@bsclifton sorry for the multiple uplift requests, but can we also get this into `1.28.x`?

**Comment by bsclifton** [comment]
@stephendonner created https://github.com/brave/brave-core/pull/9608 👍
