### ISSUE TITLE
Sign into Brave - may be removed?

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#168]
<img width="1185" alt="screen shot 2018-04-24 at 4 22 53 pm" src="https://user-images.githubusercontent.com/1903815/39218890-e7deed84-47db-11e8-80c1-c5ec7208c764.png">

**Comment by bbondy** [comment]
Should be disabled as of this merge:
https://github.com/brave/brave-core/commit/63c8daf1c26f1ed8ca2c57d903a0b406ebf8b8c4

UI looks removed to me locally. Please re-open if you have a counter example somewhere.
