### ISSUE TITLE
IPFS flyout share file/folder menu items missing IPNS key, at first

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16801]
## Description 

IPFS flyout share file/folder menu items missing IPNS key, at first

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `brave://ipfs`
   4. click on `Install and start`
   5. load `brave://settings/ipfs`
   6. choose `Local node` from `Method to resolve IPFS resources`
   7. click on the "hamburger" menu -> IPFS -> flyout

## Actual result:

Until you visit `brave://settings/ipfs/keys`, it's missing the IPNS key

<img width="1591" alt="Screen Shot 2021-07-06 at 5 13 31 PM" src="https://user-images.githubusercontent.com/387249/124681674-e473ba80-de7d-11eb-9972-7042868cff23.png">

## Expected result:

Should show the `self` IPNS key

<img width="1591" alt="Screen Shot 2021-07-06 at 5 13 44 PM" src="https://user-images.githubusercontent.com/387249/124681872-56e49a80-de7e-11eb-9fd1-63eabb849dc6.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

**Comment by spylogsster** [comment]
we deliberately removed them from this menu
cc @lidel

**Comment by stephendonner** [comment]
> we deliberately removed them from this menu
> cc @lidel

They're not removed; they still show up, as expected, eventually.  Did you try the steps verbatim?  Do you mean they are supposed to be removed as per those steps, or in general?

**Comment by spylogsster** [comment]
I found that thread https://github.com/brave/brave-core/pull/8706#issuecomment-834482044, you are right, we should show this. sorry @stephendonner

**Comment by spylogsster** [comment]
this issue was fixed in https://github.com/brave/brave-browser/issues/16743
