### ISSUE TITLE
Brave nightly gets installed automatically 

### ISSUE THREAD

**Issue by anjanraj027** [brave/brave-browser#16807]
Brave nightly gets installed automatically even after uninstalling it with Revo uninstaller.
Can anyone help me remove it completely from my pc i want to use brave stable one but it just doesn't leave my pc.
FcccK Nightly brave please let me know if i can remove it completely
![Screenshot (12)](https://user-images.githubusercontent.com/75117277/124715999-3588ba80-df21-11eb-8523-92e6ef15de3b.png)

**Comment by srirambv** [comment]
Am not sure what kind of a software that is but you can just go to Settings -> Apps -> Brave Nightly and uninstall it on Windows. Make sure you check the remove data folder when uninstall starts.
