### ISSUE TITLE
Missing selected-accent line in Settings' sidebar

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16803]
## Description 

Missing selected-accent line in Settings' sidebar; see https://github.com/brave/brave-browser/issues/16111#issuecomment-875152483 and Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=491%3A13498

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open `brave://settings/`
   4. hover over the left-hand side's category headings
   5. click on a category heading in Settings' sidebar

## Actual result:

It's missing the correct selected and hover colors (refer to Figma), as well as the selected accent line.

hover | selected
------|----------
<img width="277" alt="Screen Shot 2021-07-06 at 5 40 10 PM" src="https://user-images.githubusercontent.com/387249/124683185-4d106680-de81-11eb-930f-d8a47b48e741.png"> | <img width="286" alt="Screen Shot 2021-07-06 at 5 40 16 PM" src="https://user-images.githubusercontent.com/387249/124683186-4d106680-de81-11eb-9dfa-84cb2b659c94.png">

## Expected result:
When a section is selected:

<img width="296" alt="Screen Shot 2021-07-07 at 10 35 58 AM" src="https://user-images.githubusercontent.com/2388823/124804418-200a9500-df0f-11eb-9b49-b7ec1eef4993.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

/cc @karenkliu

**Comment by petemill** [comment]
@karenkliu I'm going to request that we use solid colors for the icons now, whilst still keeping the gradient text. This simplifies the icon generation. We can at least be iterative if you want to keep open an issue for making the icons have the nice gradient. It is possible with SVG just needs to be worked out within the system here.

**Comment by karenkliu** [comment]
@petemill Sounds good. We can simplify this issue and just make it about the missing selected-accent line. 

<img width="296" alt="Screen Shot 2021-07-07 at 10 35 58 AM" src="https://user-images.githubusercontent.com/2388823/124804418-200a9500-df0f-11eb-9b49-b7ec1eef4993.png">

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.28.64 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launched Brave
3. opened `brave://settings/`
4. hovered over the left-hand side's category headings
5. click on a category heading in Settings' sidebar
6. checked for accent line

confirmed there is a gradient-colored accent line to the left of the category heading, in both `dark` and `light` theme/modes

`dark mode` | `light mode`
-----------|------------
<img width="1504" alt="Screen Shot 2021-07-08 at 9 30 28 AM" src="https://user-images.githubusercontent.com/387249/124964357-c751ff80-dfd5-11eb-9699-19550e5f9e44.png"> | <img width="1504" alt="Screen Shot 2021-07-08 at 9 30 39 AM" src="https://user-images.githubusercontent.com/387249/124964362-c91bc300-dfd5-11eb-8f69-139d1a774dc4.png">
