### ISSUE TITLE
Expose additional NIK features as about://flags

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#16819]
Upstream / chromium is working on partitioning an number of currently shared resources (caches, connection pools, etc) and is roughly the same as the [Network Partitioning work is already doing](https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning#network_partitioning).

There exist feature flags for much of this already in Chromium (see `k*NetworkIsolationKey`](https://source.chromium.org/chromium/chromium/src/+/main:net/base/features.h?q=networkisolationkey%20feature&ss=chromium) but not all are exposed as brave://flags in Brave.

This issue is to expose all `k*NetworkIsolationKey` values as flags in Brave. This issue is part of a larger issue to enable more isolation in Brave, to complement or 3p ephemeral storage work

**Comment by pes10k** [comment]
@goodov do we still need this?  Now that we have everything flipped on for all channels, can this be closed?

**Comment by goodov** [comment]
we don't need this, let's close.
