### ISSUE TITLE
Change Monthly budget to Monthly Payment

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#1681]
PR: https://github.com/brave/brave-browser/issues/1670

problem:

![image](https://user-images.githubusercontent.com/13509546/47124273-f296ce00-d231-11e8-941e-1a2dd8e64aac.png)

**Comment by GeetaSarvadnya** [comment]
Verification Passed on

Brave	0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
Revision	9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS	Linux
