### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16828]
Few nits

https://github.com/brave/brave-core/pull/9342#discussion_r665787131 
https://github.com/brave/brave-core/pull/9342#discussion_r665787237
https://github.com/brave/brave-core/pull/9258#discussion_r665409074

## Test Plan
- check that export menu item works
- check keys are loaded after start

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.74 Chromium: 92.0.4515.93 (Official Build) nightly (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 11.4 (Build 20F71)

Confirmed importing and exporting/rotating keys still works.
Confirmed keys are available for signing published IPFS content.
Confirmed keys are loaded on start of Brave.

example | example
--------|----------
<img width="1792" alt="Screen Shot 2021-07-12 at 2 45 32 PM" src="https://user-images.githubusercontent.com/387249/125360013-0b1f6e80-e320-11eb-8873-219dd3b5fc9f.png"> | <img width="1792" alt="Screen Shot 2021-07-12 at 2 45 21 PM" src="https://user-images.githubusercontent.com/387249/125359999-065aba80-e320-11eb-9551-5d3fe8462e07.png">
