### ISSUE TITLE
Make first run dialog text friendlier

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#16820]
## Description 

Currently, we show a first run dialog with "Set Brave as default browser" checked prior to the browser launching for the first time. It's been pointed out that this ask could be jarring to the user since it appears before the user has had a chance to use the browser.

![image](https://user-images.githubusercontent.com/2388823/124829206-27d93200-df2d-11eb-9979-e906b8b302d2.png)

## Steps to Reproduce

   1. Download Brave
   2. Open Brave
   3. See first run dialog

## Actual result:

![image](https://user-images.githubusercontent.com/2388823/125508897-bb35970a-ccb0-4cdc-84e4-dcbe1f1b7389.png)

## Expected result:
- Remove the crash reporting checkbox (previously pointed out by security that it should remain unchecked since automatic crash reporting might send identifiable data).
- Replace `Brave is ready to complete your installation` with friendlier text that softens the ask.

![image](https://user-images.githubusercontent.com/2388823/124994452-bcf62c80-dffa-11eb-8822-7d98b631bae9.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel?  yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Assets
Figma: https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/?node-id=2207%3A35425

**Comment by rmcfadden3** [comment]
Drafting copy here — https://app.asana.com/0/1200197525818223/1200574742736127/f

**Comment by karenkliu** [comment]
Designs added!

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.29.20 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 11.4 (Build 20F71)

Confirmed the new `Set Brave as default browser` dialog is to-spec.

Namely:
* removal of the `Send crash reports` checkbox/line
* copy changes in the description
* change to `Set Brave as default browser` from `Set Brave as your default browser`

before | after
-------|------
<img width="592" alt="Screen Shot 2021-07-22 at 3 09 29 PM" src="https://user-images.githubusercontent.com/387249/126715810-853db796-441d-4786-b0ac-b3e2c1595d43.png"> | <img width="592" alt="Screen Shot 2021-07-22 at 3 03 57 PM" src="https://user-images.githubusercontent.com/387249/126715808-36584399-a509-44bd-9548-9d5b227258da.png">
