### ISSUE TITLE
Missing translation from Portuguese (Portugal)

### ISSUE THREAD

**Issue by gio-giorgio** [brave/brave-browser#16829]
## Description 
When right-clicking a page, everything is translated to portuguese except "Block Element" and "Manage custom filters":

## Steps to Reproduce

   1. Right click on any Brave page.

## Actual result:
![image](https://user-images.githubusercontent.com/26188435/124884548-a9cf6680-dfd2-11eb-858b-f144fece9671.png)

## Expected result:
They can be translated to "Bloquear elemento" and "Gerir filtros personalizados".

## Brave version (brave://version info)
<html>
<body>

Brave | 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2009 (Build 19043.1083)
JavaScript | V8 9.1.269.36
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip,WinrtGeolocationImplementation,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=FederatedLearningOfCohorts,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,AutofillServerCommunication,LiveCaption,FledgeInterestGroups,InterestCohortFeaturePolicy,SignedExchangePrefetchCacheForNavigations,NetworkTimeServiceQuerying,SubresourceWebBundles,TextFragmentAnchor,EnableProfilePickerOnStartup,IdleDetection,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,HandwritingRecognitionWebPlatformApi,SignedExchangeSubresourcePrefetch,LangClientHintHeader,NotificationTriggers,WebOTP,TrustTokens,DirectSockets,FirstPartySets,InterestCohortAPIOriginTrial --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Admin\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | AdRewardsStudy:NextPaymentDayEphemeralStorageStudy:EnabledPermissionLifetimeReleaseStudy:Enabled

</body>
</html>

**Comment by rebron** [comment]
cc: @mkarolin When you get a chance, can you take a look to see if this is still an issue?

**Comment by mkarolin** [comment]
@rebron, this doesn't appear to be an issue any more. 1.48.x shows localized strings:

![image](https://user-images.githubusercontent.com/41635752/221762047-2992b1d7-4598-415d-9bbb-fa9e562faec3.png)

**Comment by bsclifton** [comment]
Awesome - thanks for confirming, @mkarolin 😄
