### ISSUE TITLE
update search engine onboarding screen

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#16825]
## Description 

Update search engine onboarding screen graphic and text.

## Current result:

<img width="625" alt="Screen Shot 2021-07-07 at 4 07 52 PM" src="https://user-images.githubusercontent.com/5951041/124839650-07fe3a00-df3e-11eb-8ac3-684ba2b98844.png">

## Updated Design and Expected result:
<img width="1062" alt="Screen Shot 2021-07-09 at 12 16 37 PM" src="https://user-images.githubusercontent.com/5951041/125126193-9219e000-e0af-11eb-95ff-0e4298ecf04d.png">

Figma link for assets:
https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/Desktop-Onboarding?node-id=2182%3A35486

## Brave version (brave://version info)

Targeted for 1.27.x

## Version/Channel Information:

n/a

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc: @karenkliu

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.27.107 Chromium: 92.0.4515.107 (Official Build) (64-bit)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2004 (Build 19041.1110)

```

- Verified the Figma doc https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/Desktop-Onboarding?node-id=2182%3A35692 and ensured the below:
  - Confirmed search box favicon is changed to the search icon 
  - Confirmed the search onboarding slide text changed to `Choose the search engine you would like to use by default when searching the web from the address bar.`
![image](https://user-images.githubusercontent.com/38657976/126632520-2914cc39-ce7d-41ad-ab4b-48985b2ada50.png)
