### ISSUE TITLE
reward banner stackable when clicking on "Send a Tip" multiple times

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1683]
## Description 

When clicking on `Send a Tip..` via the Rewards panel in the URL, you'll stack several banners on top of each other. We shouldn't be stacking the same banner.

## Steps to Reproduce

   1. launch brave (used `0.55.17 Chromium: 70.0.3538.67`)
   2. enable rewards via `brave://rewards`
   3. once enabled, visit a random website and wait a few seconds
   4. click on the BAT icon in the URL and click on `Send a Tip..`
   5. once the tipping banner appears, click on the BAT icon in the URL and repeat 4-5 a few times

You'll notice that you can stack the same banner multiple times.

## Actual result:

![bannerstacking](https://user-images.githubusercontent.com/2602313/47127466-3225e000-d25b-11e8-9c5e-1f0ece831ccf.gif)

## Expected result:

The tip banner shouldn't be stackable. 

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, reproducible under `beta` & `dev`.

- Does it reproduce on browser-laptop? 

N/A

**Comment by Miyayes** [comment]
Reproduced in v1.31+, so still technically valid issue. Will get triaged in next meeting.

**Comment by Miyayes** [comment]
No longer an issue with Contribution Banner 3.0.
