### ISSUE TITLE
Search icon is overlapping on download option in Sidebar header

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16833]
## Description 

The search icon is overlapping on download option in Sidebar header

## Steps to Reproduce

   1. Clean profile 1.28.x
   2. Enable a sidebar
   3. Click on the bookmarks icon in the sidebar
   4. Bookmarks are not shown (known issue #https://github.com/brave/brave-browser/issues/1063 )
   5.  Search icon is overlapping on download option in Sidebar header

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/124911097-0306bc80-e00a-11eb-8bb4-af164a72b59b.png)

## Expected result:

Should not be any overlap icons
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.28.60 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA 

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron

**Comment by simonhong** [comment]
Not valid issue. we use side panel's bookmark page.
