### ISSUE TITLE
unexpected error messages in logs - follow up to #16810

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#16835]
## Description 

Still receiving error messages in logs after checking https://github.com/brave/brave-browser/issues/16810.

## Steps to Reproduce

   1. Have a profile that was affected by https://github.com/brave/brave-browser/issues/16744
   2. Launch with 1.28.62
   3. See that ad panel UI shows approximately expected estimated BAT
   4. Look at logs

## Actual result:

Still see `Payment balance is not ready` and `Failed to reconcile ad rewards` messages in logs after  `OnGetPayments`

## Expected result:
No error messages

## Reproduces how often: 

easily if affected

## Brave version (brave://version info)

1.28.62

## Version/Channel Information:

- Can you reproduce this issue with the current release? likely yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @tmancey @kjozwiak

**Comment by LaurenWags** [comment]
marked `QA/No` per https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1625774492272100?thread_ts=1625143188.230600&cid=CHGKGMHDJ

**Comment by stephendonner** [comment]
(Removed `QA/Yes` since it's marked `QA/No` - please revert if I'm in error.)

**Comment by LaurenWags** [comment]
whoops, missed removing that label. thanks @stephendonner 👍🏻
