### ISSUE TITLE
Estimated pending rewards reset to zero after redeeming tokens successfully

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16830]
## Description 

Estimated pending rewards reset to zero after redeeming tokens successfully

## Steps to Reproduce

   1. Clean profile 1.28.x staging environment
   2. Enable rewards and view an Ad
   3. Redeem tokens successfully
   4. Refresh brave://rewards page `Estimated pending rewards reset to zero`
   5. Estimated pending rewards remained zero even after multiple page refresh

## Actual result:

Estimated pending rewards reset to zero after redeeming tokens successfully

I am getting below-console logs before and after the successful token redemption  :

```
[10492:15008:0708/135607.942:INFO:ad_rewards.cc(280)] Payment balance is not ready
[10492:15008:0708/135607.949:VERBOSE1:ad_rewards.cc(355)] Failed to reconcile ad rewards
```
![Estimated earning resets to zero](https://user-images.githubusercontent.com/38657976/124887418-c8ddf080-dff2-11eb-9818-c1c7354f02d5.gif)

![image](https://user-images.githubusercontent.com/38657976/124906429-ad7be100-e004-11eb-84e7-1ddf0e2df729.png)

## Expected result:

Estimated pending rewards should not reset to zero
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.28.60 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @rebron @jsecretan

**Comment by GeetaSarvadnya** [comment]
@tmancey This issue is fixed and working fine in the version below, not sure which PR fixed this issue.

```
Brave | 1.28.64 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

```

**Comment by tmancey** [comment]
Closing as not actionable as we have reverted the changes with https://github.com/brave/brave-browser/issues/16856
