### ISSUE TITLE
Revert "Estimated Pending Rewards value decreased unexpectedly" fixes - 1.27.x

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#16857]
7b2a7bcb Revert "Fixes estimated Pending Rewards value decreased unexpectedly"
0000ed2d Revert "Fixes estimated pending rewards does not reset to expected value when you have uncashed in tokens - follow up to #16678"

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/9377 was reverted/merged into `1.27.x`.
