### ISSUE TITLE
Next payment date is shown incorrectly

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16858]
## Description 

The system date is `July 8th`, the next payment date in the Ads panel is showing up as `Jan 1` instead of `Aug 8`

## Steps to Reproduce

   1. Clean profile 1.28.x
   2. Enable rewards
   3. Next payment date is shown incorrectly

## Actual result:

Next payment date is shown incorrectly

![image](https://user-images.githubusercontent.com/38657976/124969131-f901af80-e043-11eb-8491-065b637ff908.png)

## Expected result:
Next payment date should be `Aug 8` as system date is `July 8`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.64 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

CC: @brave/legacy_qa @tmancey @rebron @jsecretan

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible in 1.26.x also

Clean profile - Ads panel is showing up the next payment date as `Aug 6` instead of `Aug 8` (current system date is July 8th)

![image](https://user-images.githubusercontent.com/38657976/124971901-62cf8880-e047-11eb-89cb-51fc5129c55d.png)

Restart the browser and reload brave://rewrads page, the Ads panel is showing up the next payment date as `Aug 8`
![image](https://user-images.githubusercontent.com/38657976/124972378-e7220b80-e047-11eb-8af2-1af307549d79.png)

**Comment by tmancey** [comment]
@GeetaSarvadnya Can you please retest this in 1.28.67, 1.27.98 and 1.26.75 as we have reverted some changes

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible in ` Windows 10 x64 - 1.26.74`

![image](https://user-images.githubusercontent.com/38657976/125204626-c81bb780-e29b-11eb-9a4b-09f2180d3e50.png)

**Comment by tmancey** [comment]
@GeetaSarvadnya please retest in 1.26.75

**Comment by GeetaSarvadnya** [comment]
Reproduced on Android also `1.27.105`

**Comment by tmancey** [comment]
@GeetaSarvadnya for a fresh install of the browser, you need to restart the browser for the variations service override to take effect. This is a known limitation with griffin

**Comment by GeetaSarvadnya** [comment]
@tmancey Even after the browser restart `Next payment date` is not shown correctly.

Clean profile, Next payment date is `Aug 6` after enabling the rewards:
![image](https://user-images.githubusercontent.com/38657976/125844808-2fb450a6-aaec-4ee8-a12a-5ca6fa3efaac.png)

The next payment date is `Aug 8` after browser restart:

![image](https://user-images.githubusercontent.com/38657976/125844986-f4b4f037-f10c-4cbb-b43f-63e81421b231.png)
