### ISSUE TITLE
[hackerone] Restrict cosmetic filter creation to the origin of the page it's on

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16863]
The content script which implements Shields cosmetic filtering talks to the extension background script over a `postMessage` channel. This means that a compromised renderer could send messages to the extension as well.

We should look into whether or not we can make use of a random token to restrict the messages accepted by the backend to those that originating from the content script injected by the extension.

Originally reported at https://hackerone.com/reports/1254125.

**Comment by fmarier** [comment]
Here's the pattern that iOS uses: https://github.com/brave/brave-ios/search?q=securityToken

**Comment by diracdeltas** [comment]
@keur have you looked at this one yet?

**Comment by keur** [comment]
@diracdeltas Not yet. Has no priority attached. We can put a `P3` on this and I'll look into it this week?

**Comment by diracdeltas** [comment]
P3 sounds good; added

**Comment by fmarier** [comment]
It is possible to insert arbitrary text into `brave://adblock` by changing the JS context to "Brave" in the devtools and running something like:

    chrome.runtime.sendMessage({type:"cosmeticFilterCreate", host:"fmarier.org", selector:"body { background-color: red; }"})

This gets applied immediately in the page and results in the following rule in brave://adblock:

    fmarier.org##body { background-color: red; }

but on a page reload it [fails to parse](https://github.com/brave/brave-core/blob/713692eb65af2adf39c9375d5c6f87f5afd830a6/components/brave_extension/extension/brave_extension/content_cosmetic.ts#L610):

    Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule 'body { background-color: red; }{display:none !important;}'.

The fact that a compromise renderer can temporarily affect the contents/looks of a page is not a new capability and so that's not something we need to fix.

**Comment by fmarier** [comment]
I was however able to insert a rule for a different domain:

1. Open <http://example.com/>.
2. Open the devtools.
3. Click on "top" (the JS context) in the Console tab and change it to "Brave".
4. Run the following JS code: `chrome.runtime.sendMessage({type:"cosmeticFilterCreate", host:"fmarier.org", selector:"#hidden-avatar"})`
5. Open <https://fmarier.org> and notice that the avatar photo is gone.
6. Open `brave://adblock/` to see that the following rule was inserted: `fmarier.org###hidden-avatar`

Derive the host ourselves from `sender.origin` by any chance and remove the [`host` parameter](https://github.com/brave/brave-core/blob/99054ea6524bef16428ec2fc71a131d083cfc187/components/brave_extension/extension/brave_extension/background/events/cosmeticFilterEvents.ts#L88-L92) in order to limit such rule injections to just the current origin.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.50.91`
2. launched Brave
3. loaded `abcnews.com`, `cnn.com`, and `foxnews.com`
4. on each, context-clicked on their logo and chose "Brave` --> `Block element`
5. selected the logo
6. clicked on `Create`
7. checked the filters in `brave://settings/shields/filters`
8. clicked `Reload this page`, for each site
9. ensured logos were still blocked



`abcnews.com` | `cnn.com` | `foxnews.com` | `brave://settings/shields/filters` | `sites without logos`
----------------|------------|---------------|-----------------------------------|---------------------
<img width="1502" alt="Screen Shot 2023-03-14 at 3 05 41 PM" src="https://user-images.githubusercontent.com/387249/225154232-a161d6ab-b169-48c7-b33b-ec08e48c721e.png"> | <img width="1502" alt="Screen Shot 2023-03-14 at 3 06 53 PM" src="https://user-images.githubusercontent.com/387249/225154314-66f3ccc4-5f0a-4a07-aaf1-388f010eca46.png"> | <img width="1502" alt="Screen Shot 2023-03-14 at 3 10 23 PM" src="https://user-images.githubusercontent.com/387249/225154401-d235adc5-b9c5-4975-9f29-27a4abd7addb.png"> | <img width="1942" alt="Screen Shot 2023-03-14 at 3 16 53 PM" src="https://user-images.githubusercontent.com/387249/225154765-9c2891b4-5934-491f-a7f2-93cdfd7e86eb.png"> | <img width="1383" alt="Screen Shot 2023-03-14 at 3 24 58 PM" src="https://user-images.githubusercontent.com/387249/225155844-77dfe721-26f7-4fac-bcb4-b90c4b604b24.png">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.50.108 Chromium: 112.0.5615.39 (Official Build) (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

### Steps:
1. installed `1.50.91`
2. launched Brave
3. loaded `nbcnews.com`, `time.com`, and `theguardian.com/us`
4. on each, context-clicked on their logo and chose "Brave` --> `Block element`
5. selected the logo/text
6. clicked on `Create`
7. checked the filters in `brave://settings/shields/filters`
8. clicked `Reload this page`, for each site
9. ensured logos were still blocked


`nbcnews.com` | `time.com` | `theguardian.com` | `brave://settings/shields/filters` | `sites without logos`
----------------|------------|---------------|-----------------------------------|---------------------
<img width="849" alt="image" src="https://user-images.githubusercontent.com/98358127/228662847-67fbe160-48f6-43e2-9dc2-a4bd2ec2bd0c.png">|<img width="841" alt="image" src="https://user-images.githubusercontent.com/98358127/228665106-cd1e1601-94a3-4f3f-a692-3ae7b4d50658.png">|<img width="546" alt="image" src="https://user-images.githubusercontent.com/98358127/228663976-fcea8a23-03e9-4f8b-a796-7676a395bd44.png">|<img width="346" alt="image" src="https://user-images.githubusercontent.com/98358127/228662964-4bfbb35b-f7b2-4bf1-a8f7-30c4f841307d.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/228664384-601138e0-592a-488b-a986-c06149e02e70.png">
