### ISSUE TITLE
CR92- `This file can't be downloaded securely` mixed-content text is unreadable

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16865]
## Description 

`This file can't be downloaded securely` mixed-content text is unreadable

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `https://www.leaseweb.com/platform/network` and scroll down to `Bandwidth Capacity`
   4. right-click any file and choose `Save link as...` and click `Save` in the resulting file-picker dialog
   5. look at the bottom download tray/bar
   6. click the `^` arrow and then `Learn more`

## Actual result:

* The text is garbled
* The `Learn more` link goes to top-level `https://support.brave.com/hc/en-us`

<img width="1491" alt="Screen Shot 2021-07-08 at 4 25 27 PM" src="https://user-images.githubusercontent.com/387249/125002624-3c3f2c80-e00a-11eb-89bc-8df2e8105291.png">

On Chrome (`92.0.4515.93 (Official Build) beta (x86_64)`)
* The text is readable
* The `Learn more` link goes to `https://support.google.com/chrome/answer/6261569?p=mixed_content_downloads&visit_id=637613837836535010-3633976846&rd=1`

## Expected result:

<img width="1106" alt="Screen Shot 2021-07-08 at 4 33 59 PM" src="https://user-images.githubusercontent.com/387249/125002663-52e58380-e00a-11eb-81b3-c3adeada482f.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.64 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

/cc @mkarolin @rebron @karenkliu

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Windows 10 x64 - 1.28.709` - This issue is specific to CR 92 works fine in CR 91


CR 91: 1.26.x - Text content is not overlapping 
![image](https://user-images.githubusercontent.com/38657976/125241024-8bd27080-e308-11eb-9950-dcd9ceb9ae28.png)


CR 92: 1.28.x - Text content is overlapping 
![image](https://user-images.githubusercontent.com/38657976/125241145-b6242e00-e308-11eb-8fde-d97f6f061915.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

```
- Verified the STR from the description and ensured text content is not overlapped
![image](https://user-images.githubusercontent.com/38657976/125753813-2241bc50-574b-482e-b74f-c4fcac156dfa.png)
- Confirmed notepad and other .exe files are downloaded successfully 
![image](https://user-images.githubusercontent.com/38657976/125754135-4075ccd9-c1c2-44f4-8714-5b64ef04a813.png)
