### ISSUE TITLE
Monthly contributions and Tips panel values reset to zero after upgrade 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16873]
## Description 

Monthly contributions and Tips panel values reset to zero after upgrade 

## Steps to Reproduce

   1. Clean profile 1.26.x nightly build staging env
   2. Setup monthly contributions and one-time tips 
   3. Trigger AC, after successful AC, upgrade profile to 1.28.x nightly build
   4. Monthly contributions and Tips panel are empty and values are reset to zero
   5. Reload brave://rewrads fixes the issue

## Actual result:

Monthly contributions and Tips panel values reset to zero after upgrade 
![image](https://user-images.githubusercontent.com/38657976/125069092-ea62d900-e0d3-11eb-83b3-9a69f1edeb3f.png)

## Expected result:

Monthly contributions and Tips panel values should not reset to zero after upgrade 
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.28.64 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @rebron

**Comment by zenparsing** [comment]
This appears to be a UI bug: the `firstLoad` state no longer works correctly (likely after removal of the "rewards enabled" pref) and does prevents a refresh of required data.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

```
- Verified the STR from the description and ensured Monthly contributions and Tips panel values aren't reset to zero after upgrade
