### ISSUE TITLE
Updated Tip settings are not retained after the upgrade

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16871]
## Description 

Updated Tip settings are not retained after the upgrade

## Steps to Reproduce

   1. Clean profile 1.26.x nightly build
   2. Enable rewards
   3. Navigate to the Tips panel and uncheck the checkbox for `Reddit` and `Twitter`
   4. Upgrade profile to 1.28.x nightly build
   5. Updated Tip settings are not retained after the upgrade

## Actual result:

Updated Tip settings are not retained after the upgrade

Before Upgrade
![image](https://user-images.githubusercontent.com/38657976/125048737-dd3aef80-e0bd-11eb-8fbc-199b603522d9.png)

After Upgrade
![image](https://user-images.githubusercontent.com/38657976/125048813-efb52900-e0bd-11eb-8949-c4d63feccc1b.png)

## Expected result:
Updated Tip settings should retain after upgrade

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.28.64 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2004 (Build 19041.1052)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @rebron

**Comment by Miyayes** [comment]
Just noting: I view this is as a very bad problem, and I would assign a high priority to it.

**Comment by zenparsing** [comment]
@GeetaSarvadnya After the upgrade in this scenario, do the tip icons show on the sites that were previously de-selected? (e.g. Twitter, in this case).

**Comment by zenparsing** [comment]
It appears that the inline tip settings UI is dependent on `localStorage` to maintain the current UI state, and does not currently request updated pref values from the browser.

**Comment by GeetaSarvadnya** [comment]
@zenparsing My observation is as below:

1. Install 1.26.x nightly build
2. Enable rewards and uncheck twitter and reddit checkboxes in Tips panel
3. Open https://twitter.com/bravelaurenwags and ensured inline tip button is available (known issue https://github.com/brave/brave-browser/issues/12870#issuecomment-732994642)
4. Restart the browser
5. Ensured inline tip is NOT available in https://twitter.com/bravelaurenwags
6. Upgrade profile to 1.28.x nightly build
7. Encountered the issue https://github.com/brave/brave-browser/issues/16871#issue-940549424 (Twitter and Reddit checkboxes are selected)
8. Open https://twitter.com/bravelaurenwags and ensured Inline Tip is NOT available although the Twitter option selected in step 7

Looks like it's UI issue it's not impacting the inline tip button in Twitter/Reddit

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

```
- Verified the STR from the description and ensured updated Tip settings are retained after the upgrade
