### ISSUE TITLE
Linking with Uphold broken when sent into e-mail verification flow - follow up to `16269` & `16410`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#16879]
## Description 

Originally, https://github.com/brave/brave-browser/issues/16410 was supposed to fix https://github.com/brave/brave-browser/issues/16269 which is the original issue that was filed by @Miyayes. However, users are still running into the issue. The current workaround for users is disabling `Shields`. Some more information:

* Seems to be cookie related as enabling `All cookies allowed` via shields fixes the issue
* Allowing the two `Google` cookies that are being blocked also fixes the issue
* Disabling `brave://flags/#brave-ephemeral-storage` via `brave://flags` also resolves the issues
* Logging into Uphold via a new tab before verifying via `brave://rewards` also works

This is what basically occurs when you run into the issue:

* log into Uphold after clicking `Verify` via `brave://rewards`
* you'll get screen mentioning that an email verification is needed
* once you verify via the email, it basically routes you to the login page again
* re-login and you'll get asked to verify yourself via the email again

## Steps to Reproduce

   1. launch brave and click on the Rewards icon (run through on-boarding)
   2. once rewards has been enabled, go into `brave:/rewards`
   3. click on `Verify Wallet` and start running through the login process
   4. with some accounts, you'll get asked to verify it's you via an "email verification"
   5. click on `Yes, it's me` once you get the email
   6. you'll get asked re-enter your credentials again (go through the flow again)
   7. you'll get asked to verify yourself via email once again

You'll basically get into a loop where it keeps just sending you verification emails without ever linking your account.

## Actual result:

Users are getting into a loop when required to verify via the email verification flow when attempting to link their wallets

## Expected result:

You should be able to link your Uphold account without getting into a verification loop when required to verify via email.

## Reproduces how often: 

100% reproducible with my account but not all accounts are required to verify via an email before logging into Uphold

## Brave version (brave://version info)

```
Brave | 1.28.64 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
--- | ---
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2009 (Build 19042.1081)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `Yes`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @bsclifton @rebron @LaurenWags @szilardszaloki @emerick @pes10k

**Comment by kjozwiak** [comment]
Example of the verification email that's sent:

![Screenshot 2021-07-09 135609](https://user-images.githubusercontent.com/2602313/125118356-96e59080-e0bd-11eb-890d-f89dda8d2ff1.png)

**Comment by Miyayes** [comment]
Discussed with Rewards QA and rewards client team, and we haven't seen any reports of this and haven't run into this for many months/a year. So, will close this out at stale for now. Can reopen/file anew if we start seeing it again.
