### ISSUE TITLE
Update search engine defaults for DE / AU / NZ / IE

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#16870]
## Description 
Update search engine defaults for Germany (DE), Australia (AU), New Zealand (NZ), and IE (Ireland)

## Test plan
See https://github.com/brave/internal/issues/789

**Comment by stephendonner** [comment]
Verified `PASSED` on Windows 10 using `nightly`; notes over in https://github.com/brave/brave-core/pull/9397#issuecomment-880025085

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.27.107 Chromium: 92.0.4515.107 (Official Build) (64-bit)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2004 (Build 19041.1110)


```
- Verification notes are linked in https://github.com/brave/internal/issues/789#issuecomment-884992237
