### ISSUE TITLE
Trying to enable Rewards when offline permanently breaks it

### ISSUE THREAD

**Issue by tildelowengrimm** [brave/brave-browser#1687]
In 55.16, I opened Rewards for the first time while offline. Even once I eventually went online, I was forever denied a wallet. The only solution was wiping my profile and starting over.

<img width="532" alt="screen shot 2018-10-17 at 11 00 55 am" src="https://user-images.githubusercontent.com/639937/47131377-2fbf8800-d253-11e8-817f-c164bcc5affd.png">

**Comment by GeetaSarvadnya** [comment]
Verification Passed on:
Brave	0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
Revision	9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS	Linux

![image](https://user-images.githubusercontent.com/38657976/47173913-f3f8f100-d32c-11e8-9454-fda305d73f8b.png)

- Verified error message "Wallet Creation Fail" when n/w disconnected
-  Verified able to accept the Grants after n/w connected
-  Verified adding sites to ledger is working after the n/w connected
