### ISSUE TITLE
Rewards opt-in text issue from greaselion

### ISSUE THREAD

**Issue by codybanxs** [brave/brave-browser#16886]
## Description 

It seems the subtext on the opt-in screen from the tipping banner is not quite right. 

## Steps to Reproduce

   1. Open any page that supports greaselion as a new Brave user
   2. Click on the BAT icon for inline tipping
   3. Tipping banner will appear which includes this incorrect string

## Actual result:

![image (2)](https://user-images.githubusercontent.com/61210652/125121630-0dc45e80-e0a9-11eb-8b6c-51a49bbbfd69.png)

## Expected result:
<img width="432" alt="Screen Shot 2021-07-09 at 2 01 31 PM" src="https://user-images.githubusercontent.com/61210652/125135658-37d44b80-e0be-11eb-982e-e84cfcf4e913.png">

## Brave version (brave://version info)

1.28.70 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
- Yes on Nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/9520 with build 


Brave | 1.29.20 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 11.4 (Build 20F71)



Steps:
1. new profile
2. launched Brave
3. opened `https://www.reddit.com/user/alex_the_brave`
4. clicked on an inline `tip` button
5. verified the copy in the resulting UI popup

Confirmed the `Tip with Brave

<img width="1312" alt="Screen Shot 2021-07-22 at 2 51 05 PM" src="https://user-images.githubusercontent.com/387249/126714131-f7be2fcd-c301-42bf-b261-61dd1ec5a9af.png">
