### ISSUE TITLE
[cr92 followup] Guest menu is missing "Exit" menu item.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#16885]
Currently, clicking on the Guest menu, doesn't show the "Exit" item:

<img src=https://user-images.githubusercontent.com/41635752/125134334-3cf0c500-e0d5-11eb-8339-5526a967c4ef.png height="20%" width="20%">

and with multiple windows we show:

<img src=https://user-images.githubusercontent.com/41635752/125134413-57c33980-e0d5-11eb-8f95-e9ef0c529a4d.png height="20%" width="20%">

whereas Chrome shows the item for either single or multiple windows:

<img src=https://user-images.githubusercontent.com/41635752/125134491-70cbea80-e0d5-11eb-9fc8-c8d899de838f.png height="20%" width="20%">
<img src=https://user-images.githubusercontent.com/41635752/125134513-77f2f880-e0d5-11eb-8451-3b14fd0a15d6.png height="20%" width="20%">

We should maintain parity with upstream here.

STR:

1. Start Brave
2. ☰ -> Open Guest Window
3. In the Guest window, click on the Guest profile menu
4. Observe popup menu items

**Current result:**
* No "Close Guest" menu item 

**Expected result:**
* "Close Guest" menu item is present

5. In the Guest Window, ☰ -> New Window
6. In the Guest Window, click on the Guest profile menu
7. Observer popup menu items

**Current result:**
* "Close 2 windows" menu item is present

**Expected result:**
* "Close Guest" menu item is present

cc: @GeetaSarvadnya, @rebron

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

```
- Verified the description from https://github.com/brave/brave-browser/issues/16885#issue-941059463

- Confirmed `X Close Guest` menu is shown when single Guest window is opened
![image](https://user-images.githubusercontent.com/38657976/125757739-2d23ec3b-703f-406a-9c7b-08fd851233da.png)
- Confirmed click on `X Close Guest` closes the Guest windows
- Confirmed `2 open windows` menu item along `X Close Guest` menu is shown when 2 or more Guest windows are opened
![image](https://user-images.githubusercontent.com/38657976/125757207-bf98f284-dec7-4a60-83b6-0fba56d0d8ef.png)
![image](https://user-images.githubusercontent.com/38657976/125757252-1310f75f-c840-47ad-bdf4-5ac54d8f9ac2.png)
- Confirmed click on `X Close Guest` closes all the Guest windows
