### ISSUE TITLE
Disabling Upgrade connections to HTTPS doesn't do anything

### ISSUE THREAD

**Issue by github-account1111** [brave/brave-browser#16891]
## Description 
![image](https://user-images.githubusercontent.com/5728319/125167186-cd3f1080-e18e-11eb-8c1b-e534162090fe.png)
HTTP-only sites don't work even when `Upgrade connections to HTTPS` is disabled in settings. The Dashboard ignores the settings (still has the option enabled) and even disabling from the Dashboard doesn't stop the connection from getting upgraded.

## Steps to Reproduce

   1. Disable `Upgrade connections to HTTPS` in `brave://settings`
   2. Go to an HTTP-only site (e.g. https://www.dslreports.com/speedtest?httpsok=0)

## Actual result:
Site's not working.

## Expected result:
Site's working

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
Windows 10 OS Version 1809 (Build 17763.2029)
## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes.
- Can you reproduce this issue with the beta channel? I don't know.
- Can you reproduce this issue with the nightly channel? I don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? I don't know.

## Miscellaneous Information:

Shields in general seem to be broken. Some settings get reset, some don't take effect at all.

**Comment by Johann999** [comment]
same issue as #3424

**Comment by bsclifton** [comment]
Thanks for finding the duplicate issue @Johann999 😄 I'll close this as dupe. @github-account1111 can you please follow https://github.com/brave/brave-browser/issues/3424 for updates?
