### ISSUE TITLE
Restore gesture requirement for async clipboard write access

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#16890]
Chromium 66+ implements [Asynchronous Clipboard API](https://w3c.github.io/clipboard-apis/). Chromium, in contrast to [Safari](https://webkit.org/blog/10855/async-clipboard-api/) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1619251), allow a website to write to the user's clipboard using `navigator.clipboard.writeText()/write()` without a user gesture (only criteria is that the tab should be active). 

We should require a user gesture (click, touch events)  to enable use of `navigator.clipboard.writeText()` and `navigator.clipboard.write()`. Else, promise should reject.

Demo website that attempts to write to the user's clipboard: https://shivankaul.com/brave/clipboard-paste.html (if you get a success message, try to paste)

**Comment by ShivanKaul** [comment]
https://github.com/mozilla/standards-positions/issues/89

**Comment by markg85** [comment]
Could this be re-evaluated?
Personally i really don't like this clipboard feature at all and want it gone in it's entirety.. That's probably not going to happen so please put it behind a permission request at the very least.

**Comment by androolloyd** [comment]
Am here to voice concern over this, its incredibly invasive and I would like to see it removed entirely from the Brave engine.

**Comment by bsclifton** [comment]
When it's time to try the fix, we'll need to go shields down to test the test page when fixing as EasyList is blocking what is required to test the gesture

**Comment by markg85** [comment]
Thank you for fixing brave!
Still, imho this entire feature shouldn't exist.. but having it be a permission check and false by default probably make it much less of an issue.

Interesting that this check was removed on the Chrome side for a freaking doodle new tab page purpose... It's beyond me how they can't (or won't) see that change to potentially be quite dangerous.

**Comment by mkarolin** [comment]
**Test Plan**
Please, see https://github.com/brave/brave-core/pull/14901

**Comment by kjozwiak** [comment]
The above will require `1.43.91` or higher for `1.43.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.43.91 Chromium: 105.0.5195.102 (Official Build) (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 12.5.1 (Build 21G83)
```

**Comment by MadhaviSeelam** [comment]
Verification In progress



Reproduced the issue using 1.43.89 and STR from https://github.com/brave/brave-core/pull/14901#issue-1356191620.
Checked with shields up and shields down as per https://github.com/brave/brave-browser/issues/16890#issuecomment-1232033919.

1.43.89 Shields Up | 1.43.89 Shields Down
---- | ---
<img width="777" alt="image" src="https://user-images.githubusercontent.com/98358127/189194499-bf77d8f8-2ac3-4013-9d5e-5270e24a625f.png">|<img width="767" alt="image" src="https://user-images.githubusercontent.com/98358127/189194826-03221f17-7f5e-4a87-bc87-c16735095910.png">
<img width="778" alt="image" src="https://user-images.githubusercontent.com/98358127/189195257-412f30d6-7d8d-4478-a3a7-e43b57dacb1e.png">|<img width="770" alt="image" src="https://user-images.githubusercontent.com/98358127/189195379-e285415a-7211-4397-8b6b-b65eeb8324bd.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.92 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Ubuntu 18.04 LTS

Verified https://github.com/brave/brave-core/pull/14901

Reproduced in 1.43.88
Verified in 1.43.92
<details>
shields on
![image](https://user-images.githubusercontent.com/34715963/189639263-4d473d42-2d7a-46cf-a314-cb040c9785a0.png)

shields down
![image](https://user-images.githubusercontent.com/34715963/189639334-4cb8b221-26d8-46eb-be10-defb59f93f85.png)



</details>

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.43.92 x64 build
- Reproduced the issue on 1.43.88
- Verified with both Shields Up/Down

1.43.88 | 1.43.92
-- | --
![image](https://user-images.githubusercontent.com/17010094/189848903-3ec1a774-4454-40de-96c2-9dc15042aadd.png) | ![image](https://user-images.githubusercontent.com/17010094/189848928-bb9e40a5-89f8-4abe-9806-8d771c024098.png)
