### ISSUE TITLE
Add a menu entry to access brave://apps

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#16898]
## Description 
In both Google Chrome and Brave, I find the "Create Shortcut" functionality very useful. It allows me to easily add website shortcuts to my Start Menu or make a website appear as a separate "app" on my computer when I check "Open as window". These shortcuts are shown in brave://apps, where I can manage and remove them if necessary.

However, unlike in Google Chrome, there's no easy way to access brave://apps in Brave. In Google Chrome, you can access chrome://apps via the new tab page. In Brave, there is no such button. I have to manually type brave://apps every time.

I suggest that an "Apps" menu entry be added to the hamburger menu.

## Steps to Reproduce

   1. Navigate to a webpage
   2. Click hamburger menu -> More tools -> Create shortcut
   3. Notice that a start menu entry has been created for that webpage
   4. Try to remove the shortcut with Brave. Notice there's no way to click your way to brave://apps and remove it.

## Actual result:
A user can create a website shortcut in Brave, but won't be able to remove it unless he/she explicitly knows about brave://apps.

## Expected result:
A menu entry should be available in the hamburger menu that navigates to brave://apps

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Windows 10 OS Version 2009 (Build 22000.65)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
There used to be a shortcut on bookmarks bar for chrome://apps which Chromium removed as they deprecated Google apps feature by default. Think this will be a wontfix as this would have significant changes that will require patching and maintenance overhead.

cc: @rebron

**Comment by urbenlegend** [comment]
@srirambv Does this mean the create shortcut functionality is also going away? I find this feature extremely useful actually. If it is deprecated, then what is the correct way of removing these shortcuts?

**Comment by srirambv** [comment]
> Does this mean the create shortcut functionality is also going away?

No not at all. Create shortcut will still be there. 

>  what is the correct way of removing these shortcuts?

Correct way is to go to brave://apps and right click on the shortcut and select `Remove from Brave`. You can also choose to remove the data in the process of removing the shortcut. Its a bit of manual work but its the right way to get rid of the shortcuts 
![image](https://user-images.githubusercontent.com/17010094/125395575-49aa3d00-e3a3-11eb-8931-d4f9f0942a6a.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.10 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | bdff9e7d7314280ddbce1c3ada3abee4ce4a3b32
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

1. Installed 1.74.10
2. launched Brave
3. clicked hamburger menu >> More tools
4. confirmed `Show apps` entry is shown beneath `Quick commands` entry
5. clicked `Show apps` 
6. confirmed `brave://apps` is shown
7. opened github.com in a new tab
8. installed github via PWA
9. opened brave://apps
10. confirmed `GitHub` is shown

example | example | example | example 
------ | ------ | -------- | ----------
![Image](https://github.com/user-attachments/assets/d8b34da2-e228-471f-8a66-5313e8519a95)|![Image](https://github.com/user-attachments/assets/b3dde4c9-b2a2-4def-8847-94013ef2904e)|![Image](https://github.com/user-attachments/assets/9da631f3-1b11-4b11-aa64-b303da5ec013)|![Image](https://github.com/user-attachments/assets/f6b11965-7f32-4aa4-b143-972abf01587a)
