### ISSUE TITLE
--is_asan flag doesn't turn is_asan = true in args.gn

### ISSUE THREAD

**Issue by shhnjk** [brave/brave-browser#16896]
## Description 
Per https://github.com/brave/brave-core/pull/6526, I build brave with the following command.

```
npm run build --is_asan
```

However, args.gn generated still has `is_asan = false`, which suggests that ASan build isn't compiling.

## Steps to Reproduce
   1.  Build with `npm run build --is_asan`

## Actual result:
Check `args.gn` and it still has `is_asan = false`

## Expected result:
`args.gn` should have `is_asan = true`

## Reproduces how often: 
Always

## Desktop Brave version:
Pulled from master today.

**Comment by bsclifton** [comment]
@shhnjk can you please try like this?
```
npm run build -- --is_asan
```

The `--` is required before to escape; otherwise the params are not passed through

**Comment by shhnjk** [comment]
That worked! Thanks!
