### ISSUE TITLE
Shields should be disabled for about pages

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#169]
<img width="1197" alt="screen shot 2018-04-24 at 4 27 18 pm" src="https://user-images.githubusercontent.com/1903815/39218967-840b5f76-47dc-11e8-8c48-5e6b07190943.png">

**Comment by srirambv** [comment]
Changing drop down or clicking on the switch reloads the page but setting doesn't change
![pagereload](https://user-images.githubusercontent.com/17010094/41442041-653ad62c-7003-11e8-87bf-83c5740c7ca9.gif)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Checked all links from chrome:about
