### ISSUE TITLE
Make "Refresh" button in brave://rewards-internals > Promotions page actually check for new promotions

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16909]
## Description

Currently, there is no way to force the browser to check/try and fetch any available promotions (claim buttons). In brave://rewards-internals > Promotions, there is a "Refresh" button, but it doesn't seem to actually check the promotions endpoint.

This would be very helpful during and for QA.

**Edit:** This should be restricted to working only against _staging_. 

## Solution

Make the "Refresh" button actually force a check to the promotions endpoint.

cc: @LaurenWags

**Comment by LaurenWags** [comment]
My understanding is that this just pulls info from the database not the endpoint, but @zenparsing would be best to confirm.

**Comment by Miyayes** [comment]
This should be restricted to working only against staging.

**Comment by szilardszaloki** [comment]
We came to find that we can retain the current behavior of the `Refresh` button on the `Promotions` tab in `brave://rewards-internals`, since the purpose of this change would be to avoid having to wait the 10 minute timeout each time we want the claim buttons for the new promotions to show up in `brave://rewards` when the browser is connected to staging.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.29.61 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 10.15.7 (Build 19H1323)
```

Verified test plan from https://github.com/brave/brave-core/pull/9579#issue-698856986 with assistance from @Miyayes
Note, per https://github.com/brave/brave-browser/issues/16909#issuecomment-888459011, refreshing brave://rewards page will perform this check on staging, not the `Refresh` button on brave://rewards-internals.

Confirmed that when one ad grant is available it is received by refreshing brave://rewards.
Confirmed that when multiple ad grants are available they are received by refreshing brave://rewards.

Initial | Single ad grant | Multiple ad grants
----- | ----- | -----
<img width="1194" alt="Screen Shot 2021-08-18 at 10 56 37 AM" src="https://user-images.githubusercontent.com/28145373/129923052-4f88ba66-78b7-45d6-8a44-c5360ef8aba2.png"> | <img width="1198" alt="Screen Shot 2021-08-18 at 11 00 06 AM" src="https://user-images.githubusercontent.com/28145373/129923058-0c1632d4-9a1f-4224-8b6d-74c33d279165.png"> | <img width="1186" alt="Screen Shot 2021-08-18 at 11 02 12 AM" src="https://user-images.githubusercontent.com/28145373/129923062-85b70c6c-cc2f-4017-b89d-096404bf9320.png">
