### ISSUE TITLE
change WebRTC learn more link from article on github to article on support site

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1690]
Learn More link under WebRTC points to github doc: https://github.com/brave/brave-browser/wiki/WebRTC-Custom-Settings

Move content to support web site and change link to point to that new article.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta(64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified test plan in https://github.com/brave/brave-core/pull/748
