### ISSUE TITLE
Sidebar settings and additional settings clustered incorrectly

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16900]
## Description 

Sidebar settings and additional settings clustered incorrectly

## Steps to Reproduce

   1. Clean profile 1.28.x nightly build
   2. Open brave://settings
   3. Sidebar settings and additional settings clustered incorrectly

## Actual result:

Sidebar settings and additional settings clustered incorrectly
![image](https://user-images.githubusercontent.com/38657976/125247117-3b5f1100-e310-11eb-8d73-b624c07682ce.png)

## Expected result:
Settings should be gathered correctly

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.28.70 Chromium: 92.0.4515.81 (Official Build) nightly (64-bit)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by mkarolin** [comment]
@GeetaSarvadnya, this was an intentional change described here: https://github.com/brave/brave-browser/issues/16470

**Comment by GeetaSarvadnya** [comment]
This is expected as per #16470 hence closing the issue.
