### ISSUE TITLE
Always show "30-day ads history" link button in Rewards settings page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16902]
## Description

Currently, when **30-day ads history** (or 7-day ads history previously) is empty, the 30-day ads history button/link in the bottom right corner of brave://rewards (Rewards settings page) does not appear. 

![image](https://user-images.githubusercontent.com/11497541/125250220-fca36980-e2c3-11eb-99ed-20adad07a12f.png)

(Note how it's missing in bottom-right corner.)

This doesn't train users to know that this feature exists. 

## Solution

1. Always show 30-day ads history link/button, even when list is empty
2. When list is empty, just put a message in there that says "You haven't seen any ads in the last 30 days." 

Can get design input as well if needed, but let's iterate. cc: @codybanxs.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.7 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.1 (Build 20G80)

Steps:
1. new profile
2. launched Brave
3. clicked `Start using Rewards`
4. opened `brave://rewards`
5. confirmed I saw `30-day Ads History` link
6. clicked on the link and confirmed I saw `No ads viewed in the last 30 days.`
7. viewed an ad
8. confirmed I saw the new ad appear after refreshing
9. confirmed `Ads I received this month` is now `1`, as expected too

example | example | example | example
---------|----------|---------|---------
<img width="1334" alt="Screen Shot 2021-08-07 at 9 58 37 AM" src="https://user-images.githubusercontent.com/387249/128608324-bcd1de9a-385d-440d-90e0-989c3f5e3ed7.png"> | <img width="1334" alt="Screen Shot 2021-08-07 at 9 58 42 AM" src="https://user-images.githubusercontent.com/387249/128608328-0448a5b0-234c-46f8-bfc6-41f8c58335ad.png"> | <img width="1770" alt="Screen Shot 2021-08-07 at 10 04 08 AM" src="https://user-images.githubusercontent.com/387249/128608329-2560c358-9a42-495b-9201-e73697077b23.png"> | <img width="1770" alt="Screen Shot 2021-08-07 at 10 11 16 AM" src="https://user-images.githubusercontent.com/387249/128608423-1fa42a4a-0362-4c40-94c3-17a29ea8d1b3.png">
