### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by enumag** [brave/brave-browser#16916]
## Description 

I'm trying to update the [Refined GitHub](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf) extension. However chrome webstore says it's not compatible.

```
This application is not supported on this computer. Installation has been disabled. The following problems are detected:
Chrome of version at least 88 is required
```

My Brave version is:

```
Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
```

I believe 91 is greater than 88 so I don't understand why it doesn't work.

## Steps to Reproduce

   1. Install the latest stable Brave Browser. (I'm on Ubuntu 20.04 but most likely the issue is OS independent.)
   2. Go to chrome web store and try to install [Refined Github](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf).

## Actual result:

Extension cannot be installed claiming to not be compatible.

## Expected result:

Extension installs.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
Brave | 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | Linux
JavaScript | V8 9.1.269.36
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=AutoupgradeMixedContent,SafetyTip,WebUIDarkMode,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,LegacyTLSEnforced,DnsOverHttps --disable-features=IdleDetection,TrustTokens,DirectSockets,InterestCohortFeaturePolicy,FledgeInterestGroups,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,TextFragmentAnchor,EnableProfilePickerOnStartup,HandwritingRecognitionWebPlatformApi,NetworkTimeServiceQuerying,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,WebOTP,NotificationTriggers,LangClientHintHeader,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,AutofillServerCommunication,LiveCaption,FederatedLearningOfCohorts,InterestCohortAPIOriginTrial,FirstPartySets,SignedExchangeSubresourcePrefetch --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/tousek/.config/BraveSoftware/Brave-Browser/Default
Variations | AdRewardsStudy:NextPaymentDayEphemeralStorageStudy:EnabledPermissionLifetimeReleaseStudy:Enabled
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? didn't try
- Can you reproduce this issue with the nightly channel? didn't try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Nothing to add for now. But ask me questions if needed.

**Comment by ryanbr** [comment]
Hey @enumag I just installed this extension without issue (using windows), can you test Brave Beta?

**Comment by enumag** [comment]
It seems the extension somehow updated itself so the error is gone now. I'm not gonna test it by removing it. I'll reopen if it happens again.
