### ISSUE TITLE
Notifications should allow custom ID

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1691]
Currently if you enable rewards and reload site counter will increase. We should be able to set custom notification ID, so that grant notification will be unique. We could also limit this per type?

cc @davidtemkin will we have any type of notifications except errors, that can co-exist (multiple notifications of the same type)

**Comment by kjozwiak** [comment]
STR:

* launch `0.55.18 Chromium: 70.0.3538.67`
* enable rewards via `brave://rewards`
* should see a notification indicator to let you know there's a grant available
* opens several `brave://rewards` pages and you'll see the notification stack

Example:

![notificationbrave](https://user-images.githubusercontent.com/2602313/47179063-0ce0b280-d2eb-11e8-800f-544428dce0bb.gif)

**Comment by NejcZdovc** [comment]
You don't even need to open multiple pages, you can just reload it

**Comment by kjozwiak** [comment]
> You don't even need to open multiple pages, you can just reload it

Yup, realized that after posting the above! A lot easier just to refresh the page 👍 Updated the above STR to make it easier. Thanks @NejcZdovc 👍

**Comment by rebron** [comment]
cc: @mandar-brave to revisit

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows
