### ISSUE TITLE
CR92 - Not getting save password prompt for Gmail accounts

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16926]
## Description 

CR92 - Not getting save password prompt for Gmail accounts

## Steps to Reproduce

   1. Clean profile 1.28.74
   2. Open gmail.com and sign in to gmail
   3. Not getting save password prompt

Please note I am seeing this issue only for Gmail accounts, I am getting save password prompt for Twitter and uphold logins

## Actual result:

Not getting save password prompt for Gmail accounts

## Expected result:
Should get save password prompt for Gmail

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.28.74 Chromium: 92.0.4515.93 (Official Build) nightly (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @mkarolin

**Comment by stephendonner** [comment]
Can confirm with 


Brave | 1.28.76 Chromium: 92.0.4515.93 (Official Build) nightly (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 11.4 (Build 20F71)

and 

Brave	1.28.74 Chromium: 92.0.4515.93 (Official Build) nightly (64-bit)
Revision	6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS	Linux

I'm also not getting offered to save passwords for Gmail.com.

**Comment by mkarolin** [comment]
Found the upstream bug filed on it, but they closed it as "Won't fix" saying it's an intentional change (without further explanation): https://bugs.chromium.org/p/chromium/issues/detail?id=1220026.

**Comment by mkarolin** [comment]
As mentioned in the bug above, the suspect for this change is the `Enable the account data storage for passwords` feature which is now turned on be default on Desktop platforms (https://chromium.googlesource.com/chromium/src/+/3d683277dd571f62df6cbe9eb80b4c3823e34971). Disabling this feature via brave://flags results in the Save Password dialog showing up when logging into Gmail.

The feature description in the code is 
<pre>
// Enables a second, Gaia-account-scoped password store for users who are signed
// in but not syncing.
</pre>
cc: @jumde @fmarier any recommendations on what we should do with this feature?

**Comment by mkarolin** [comment]
Will disable this feature for now.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```


Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

```
- Verified the STR from the issue and confirmed save password prompt is shown for Gmail login
- Ensured save password prompt is shown for Twitter/Reddit/Uphold etc
