### ISSUE TITLE
"New Private Window with TOR" is not working in Brave Beta 

### ISSUE THREAD

**Issue by mkz7** [brave/brave-browser#16924]
"New Private Window with TOR" is not working in Brave Beta, latest release: 
"Version 1.27.100 Chromium: 91.0.4472.124 (Official Build) beta (x86_64)"  [Mac OS Mojave / v. 10.14.3]

Toggling the TOR setting ("Private Window with Tor") in Settings > Extensions has no effect, whether set 'on' or 'off'. 

Progress meter (rotating half-circle) for all URL's spins indefinitely and the corresponding webpages never load. 

There was one successful loading of a URL on 7/11/21 with the TOR setting in the 'off' state. I don't know what explains that. 

Since then no other URL has loaded, including the same URL that had previously 'worked' now attempted in a new tab.

https://community.brave.com/t/new-private-window-with-tor-not-working/235213/60?u=fmarier

**Comment by darkdh** [comment]
@mkz7 did you use the same Tor window after set Tor off and on? could you try close the original Tor windows and use a brand new Tor window after you toggle the setting switch?

**Comment by mkz7** [comment]
@darkdh Thanks, that did work. Let's see if it lasts.

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/9586 with 


Brave | 1.29.42 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5.1 (Build 20G80)

1. Launched Brave and opened a Tor window
2. Killed tor process via `kill -9 19085`
3. A new tor process should be relaunch at once; confirmed `tor-0.4-5.9-brave-0` relaunched as `pid 19291`
4. Wait for Tor window connected to Tor network
5. Visited `https://check.torproject.org` in Tor window and we should be on Tor network
6. Visited `about:crashes` in a regular window, and saw no crashes
7. Closed Tor window
8. Went to `[User Data Dir]/tor`, `watch` folder should be deleted when there is no Tor process running

example | example | example
---------|---------|----------
<img width="900" alt="Screen Shot 2021-08-01 at 4 07 18 PM" src="https://user-images.githubusercontent.com/387249/127788267-687d331e-1a74-4bdf-b60b-91e97b83ffad.png"> | <img width="1599" alt="Screen Shot 2021-08-01 at 4 12 50 PM" src="https://user-images.githubusercontent.com/387249/127788268-2d213be6-39db-4c65-a537-7934d705f96e.png"> | <img width="1599" alt="Screen Shot 2021-08-01 at 4 15 11 PM" src="https://user-images.githubusercontent.com/387249/127788271-abf0c0de-43a4-4e2b-93ba-fb058a29b915.png"> 

Confirmed the user's `watch` directory was deleted on closing the Tor window:

**Before:**
```
stephendonner@Stephens-MacBook-Pro tor % pwd
/Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/tor
stephendonner@Stephens-MacBook-Pro tor % ls -la
total 0
drwx------@ 4 stephendonner staff  128 Aug 1 16:12 .
drwx------ 38 stephendonner staff 1216 Aug 1 16:15 ..
drwx------@ 9 stephendonner staff  288 Aug 1 16:14 data
drwx------@ 5 stephendonner staff  160 Aug 1 16:12 watch
```

**After closing Tor window**:
```
stephendonner@Stephens-MacBook-Pro tor % pwd  
/Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/tor
stephendonner@Stephens-MacBook-Pro tor % ls -la
total 0
drwx------@ 3 stephendonner staff  96 Aug 1 16:15 .
drwx------ 38 stephendonner staff 1216 Aug 1 16:15 ..
drwx------@ 9 stephendonner staff  288 Aug 1 16:15 data
```
