### ISSUE TITLE
IPFS pages load even with setting disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16923]
## Description 
IPFS pages load even with setting disabled

## Steps to reproduce 

   1. Clean install 1.28.76 Nightly build
   2. Visit a IPFS page
   3. No interstitial page is shown

## Actual result 
IPFS page loads with setting disabled

https://user-images.githubusercontent.com/17010094/125463904-0f6bd1d7-a786-4e66-8475-ca33a229b490.mp4

## Expected result
Should load interstitial page 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.28.76 x64 Nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @spylogsster @samartnik

**Comment by diracdeltas** [comment]
@bbondy @rebron marking this as p2 since IPFS pages shouldn't load without opt-in.

**Comment by srirambv** [comment]
We should probably add some sort of check on new CR bumps. This failed last time as well during major CR bump #16239
