### ISSUE TITLE
Bug with Adblock and Photopea Online Editor

### ISSUE THREAD

**Issue by imrolii** [brave/brave-browser#16928]
## Description 
Adblock doesn't seem to disable on [photopea.com](https://photopea.com) when shields are **off**, therefore triggering an adblock detection message.

## Steps to Reproduce
Sometimes, it will work fine, but other times, you'll be spammed by the alert.

   1. Go to [Photopea Online Editor](https://www.photopea.com), with AdBlocker (Shields) enabled
   2. Try edit or upload a PSD file
   3. Adblock message will appear

## Actual result:
Shows error message even when Shields are off.

![Error Displayed](https://user-images.githubusercontent.com/79724190/125499023-84a36001-dad9-4d89-a55d-6208610ecac8.png)

![Shields are off](https://user-images.githubusercontent.com/79724190/125499093-ae8bcb4b-1558-4037-b9c5-e35db6da1bf8.png)

## Expected result:
Webpage would run fluently with no alerts.

## Reproduces how often: 
Fairly often, happened to me when I uploaded a PSD for the first time.

## Brave version (brave://version info)

```
Brave: 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
Revision: 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS: Windows 8.1 (Build 9600.20046)
```

## Version/Channel Information:
Tested on current release.

## Other Additional Information:
[Original issue reported to the Photopea repository](https://github.com/photopea/photopea/issues/3549)

## Miscellaneous Information:
None

**Comment by ryanbr** [comment]
Thanks, investigating the issue @imrolii

**Comment by ryanbr** [comment]
Give it 24-48hrs @imrolii update will fix in Brave
