### ISSUE TITLE
Desktop browser automatically opens some links in a new Tor window

### ISSUE THREAD

**Issue by paymog** [brave/brave-browser#16925]
## Description 
Sometimes Brave opens a link in a TOR browser without prompting me. I've searched for similar issues and didn't find any.

## Steps to Reproduce

   1. visit https://mail.protonmail.com/u/0/inbox
   2. note that a new TOR browser is opened with a URL similar to https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/login

## Actual result:

The link is opened in the regular non-TOR browser and is also opened in a TOR browser.

![image](https://user-images.githubusercontent.com/1986950/125481438-ca11fcb7-8051-4f74-b96e-2815be4d3c9a.png)

## Expected result:

I expect that a new Tor window isn't automatically opened unless some setting is manually turned on (which I haven't done).

## Brave version (brave://version info)

```
Brave	1.26.74 Chromium: 91.0.4472.124 (Official Build) (x86_64)
Revision	7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS	macOS Version 11.4 (Build 20F71)
JavaScript	V8 9.1.269.36
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? *I believe I'm up to date*
- Can you reproduce this issue with the beta channel? *haven't tried*
- Can you reproduce this issue with the nightly channel? *haven't tried*

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? *no*
- Does the issue resolve itself when disabling Brave Rewards? *no*
- Is the issue reproducible on the latest version of Chrome? *no*

**Comment by diracdeltas** [comment]
cc @darkdh 

@paymog what are your settings in brave://settings/?search=onion ?

**Comment by paymog** [comment]
Ah, that was turned on though I don't remember ever turning it on. Turning it off fixes this. Thanks for the tip!
