### ISSUE TITLE
Preload pages info text is changed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16922]
## Description 
Preload pages info text is changed

## Steps to reproduce 

   1. Install CR92 nightly build
   2. Go to Brave Shields and Privacy and look for Preload pages setting
   3. The info text is updated

## Actual result 

CR 92 (Nightly) | CR 91 (Release)
-- | --
![image](https://user-images.githubusercontent.com/17010094/125454590-7fb48345-bee5-46be-a359-9af2bbf82923.png) | ![image](https://user-images.githubusercontent.com/17010094/125454637-4cb1eff6-8897-404c-9cf0-7cc16070c96f.png)

## Expected result
TBD

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.28.76

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik @mkarolin

**Comment by samartnik** [comment]
As per discussion this option was entirely removed https://bravesoftware.slack.com/archives/C0816QH3R/p1626180494016500

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.28.99 x64 Beta build
- Verified setting is removed from Other Privacy settings under Brave Shields & Privacy section

Oppo R5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/127870141-43a835dc-505d-4875-8e18-45caf1895f2f.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/127870169-abb663e4-7d92-4b6f-b1b3-21d33f5b6ffc.png>
