### ISSUE TITLE
Ephemeral localStorage is not shared between frames and cannot be used in 1PES context

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#16920]
Our current ephemeral ```localStorage``` implementation is based on ```SessionStorage``` backend which is not meant to be used from multiple frames. This breaks the case when 3PES ```localStorage``` should be shared when a same website is opened in multiple tabs. Also this implementation doesn't allow us to use ```localStorage``` properly in 1PES mode.

**Comment by goodov** [comment]
To test:
1. Open https://dev-pages.bravesoftware.com/storage/frames.html
2. Set any value
3. Open https://dev-pages.bravesoftware.com/storage/frames.html in another tab
4. Set new value
5. Observe that in both tabs all values are synced.

Previously a new value was not applied in the first tab after step 4.

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with 


Brave | 1.29.27 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 11.5 (Build 20G71)

Steps:
1. new profile
2. launched Brave
3. opened `https://dev-pages.bravesoftware.com/storage/frames.html`
4. set value to `3`
5. opened `https://dev-pages.bravesoftware.com/storage/frames.html` in another tab
6. set new value of `1`
7. observed that in both tabs all values for `key` are synced to `1`

before | after
-------|------
<img width="1312" alt="Screen Shot 2021-07-26 at 12 02 20 PM" src="https://user-images.githubusercontent.com/387249/127045095-072dc3bc-6664-4a41-98bd-34d36692d909.png"> | <img width="1672" alt="Screen Shot 2021-07-26 at 12 05 06 PM" src="https://user-images.githubusercontent.com/387249/127045097-4137b276-422d-4846-abbc-1f0c0a99dd76.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.29.60 x64 Beta build
- Verified steps from https://github.com/brave/brave-browser/issues/16920#issuecomment-885646364

https://user-images.githubusercontent.com/17010094/129538831-aafd5775-9677-4de7-a6bf-fb6aaa123c6a.mp4

---------
Verification passed on Samsung Tab A  with Android 10 running 1.29.60 x64 Beta build
- Verified steps from https://github.com/brave/brave-browser/issues/16920#issuecomment-885646364

https://user-images.githubusercontent.com/17010094/129538740-84b4e4a0-1971-472f-ac0a-9aed8785bc52.mp4
