### ISSUE TITLE
Sometimes a tab detaches itself from the current window when it's clicked

### ISSUE THREAD

**Issue by emarsk** [brave/brave-browser#16934]
## Description 

Sometimes (randomly? I didn't find any pattern) a tab detaches itself from the current window when it's clicked, jumping out into its own new window (as if I did a drag and drop).

## Steps to Reproduce

I have no idea how to consistently reproduce this bug. Anyway:

   1. Have some tabs opened.
   2. ???
   3. Click on an unselected tab.

## Actual result:

Tab detached.

## Expected result:

Tab selected.

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Brave: 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)

Revision: 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}

OS: Windows 10 OS Version 2009 (Build 19043.1083)

**Comment by rebron** [comment]
Closing as stale. Intermittent issue, I suspect it was too easy to tear off a tab and shouldn't be the case now with current version 1.62.162.
