### ISSUE TITLE
Consider adding uphold user ID to brave://rewards-internals

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#16937]
## Description 
I ran into the linking issue (see https://github.com/brave/brave-browser/issues/14927) recently and it was difficult to get the problem resolved.  I had to provide folks with the Uphold ID which we don't seem to display in the UI.

In my example, I had to get the ID via uphold.com using network tab (in developer tools). You can see it in the `https://api.uphold.com/v0/me/transactions` request - in the response JSON you need to look for your username; there will be a guid in the `id` field at the same level as the `username` field.

Having this ID would make any action we'd like to take with https://github.com/brave/brave-browser/issues/14927 a lot easier. For example, if we wanted to have a support workflow for that situation

**Comment by Miyayes** [comment]
@szilardszaloki, do you happen to know an easy way the browser might have access to this field (e.g., is it ever returned during one of the user's requests to Uphold)? If so, then we could have it displayed in brave://rewards-internals.

**Comment by szilardszaloki** [comment]
@Miyayes Yep, currently we don't parse it, but it's in the Uphold user object (`Get User` request).

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/9529 with 
https://github.com/brave/brave-core/pull/9529

Brave | 1.29.42 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 12.0 (Build 21A5294g)

Steps:

1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3. enabled `Rewards`
4. clicked on `Verify Wallet` from `brave://rewards` and logged in with my `KYC'd Uphold` account
5. confirmed `Custodian` and `Custodian member ID` were shown in `brave://rewards-internals`
6. disconnected `Uphold` account from `Rewards`
7. confirmed `Custodian` and `Custodian member ID` are **not** shown in `brave://rewards-internals`
8. confirmed for both `bitFlyer` and `Gemini` that only `Custodian` is shown.

`Uphold` | `bitFlyer` | `Gemini` | `disconnected`
----------|-----------|----------|--------------
<img width="1014" alt="Screen Shot 2021-08-02 at 1 34 54 PM" src="https://user-images.githubusercontent.com/387249/127921782-b6d32966-ebd6-49cd-90dd-05e11e5158be.png"> | <img width="1120" alt="Screen Shot 2021-08-02 at 11 19 44 AM" src="https://user-images.githubusercontent.com/387249/127921787-b9a5c435-42ad-481a-974b-c1c87b06373b.png"> | <img width="1175" alt="Screen Shot 2021-08-02 at 11 31 11" src="https://user-images.githubusercontent.com/387249/127921789-292ef3e2-d7e0-4428-bac3-7240a8ea1de9.png"> |  <img width="1130" alt="Screen Shot 2021-08-02 at 11 20 28 AM" src="https://user-images.githubusercontent.com/387249/127922023-9ee20ea1-4522-4bcb-bfe1-eac941d492a7.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.29.70 x64 Beta build
- Verified Uphold User ID is shown on `brave://rewards-internals` when a KYC'd wallet is connected

Disconnected | Connected
-- | --
![image](https://user-images.githubusercontent.com/17010094/130802960-674d8c52-8cb5-45af-ab7a-c55825651783.png) | ![image](https://user-images.githubusercontent.com/17010094/130802803-51af36ad-b76a-4301-afac-cd044610e50c.png)

-------

Verification passed on Samsung Tab A with Android 11 running 1.29.70 x64 Beta build
- Verified Uphold User ID is shown on `brave://rewards-internals` when a KYC'd wallet is connected

Disconnected | Connected
-- | --
![image](https://user-images.githubusercontent.com/17010094/130803004-32348f63-6ec0-4483-9001-c76836037f93.png) | ![image](https://user-images.githubusercontent.com/17010094/130802911-47e1a4a1-429f-4123-a977-296f2cec96e5.png)
