### ISSUE TITLE
Fix sentence casing on `Always Show Full URLs` in brave://settings/appearance

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16939]
## Steps to Reproduce

   1. load `brave://settings/appearance`
   2. look at the following two entries:
   `Always show bookmarks on new tab page`
   `Always Show Full URLs`

## Actual result:

`Always Show Full URLs` is in all uppercase/Initial Caps.

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-07-13 at 6 00 28 PM" src="https://user-images.githubusercontent.com/387249/125544349-6d737681-dd4f-4145-8028-64cebb04ca10.png"> |  <img width="677" alt="Screen Shot 2021-07-13 at 6 02 08 PM" src="https://user-images.githubusercontent.com/387249/125544402-f2fc88cd-350f-4db1-91f4-81089e9c92ab.png">

## Expected result:

`Always show full URLs` (lowercase, to match the above setting description)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.77 Chromium: 92.0.4515.93 (Official Build) nightly (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 11.4 (Build 20F71)

/cc @rmcfadden3

**Comment by rebron** [comment]
cc: @darkdh :-)

**Comment by swarup4741** [comment]
Can i work on this issue ?

**Comment by stephendonner** [comment]
> Can i work on this issue ?

Hi @swarup4741 - absolutely!  Thanks, I'll assign this to you.  If for some reason you're unable to pursue it further, please un-assign yourself so others can pick it up.

A good place to start is to look through https://github.com/brave/brave-core.  Cheers!

**Comment by swarup4741** [comment]
@stephendonner is it only a issue on macOS .. cause I'm using windows 10 and i am having it correctly said...

<img width="363" alt="brave" src="https://user-images.githubusercontent.com/69234404/125896798-5eb9b8a8-ab03-403f-ac08-96ec21c22565.PNG">

**Comment by swarup4741** [comment]
I was searching a lot of directory but i found this one close (`brave-core/browser/resources/settings/brave_appearance_page/`) but exactly couldn't figure out where to make changes 

@stephendonner  if you could please guide me a little bit

**Comment by swarup4741** [comment]
> > Can i work on this issue ?
> 
> Hi @swarup4741 - absolutely! Thanks, I'll assign this to you. If for some reason you're unable to pursue it further, please un-assign yourself so others can pick it up.
> 
> A good place to start is to look through https://github.com/brave/brave-core. Cheers!

@stephendonner  I think @deepxcode addressed this issue on #9461 and his changes looks fine to me ...

**Comment by namangirdhar16** [comment]
Hi @stephendonner  can i work on this issue, if hasn't fixed yet?

**Comment by bsclifton** [comment]
Hi @namangirdhar16 - thanks for the offer; Looks like @deepxcode has the fix in https://github.com/brave/brave-browser/issues/16939

Thanks @swarup4741 for the assist (ex: reviewing, suggestions in PR). We just need a rebase and then it's good to go

**Comment by simonhong** [comment]
Re-opened as it's reverted (https://github.com/brave/brave-core/pull/9970).

**Comment by Tonev** [comment]
Hey, @rebron !

I don't know how to proceed in such cases where you have the same string, with the same ID, for uses for upper and lowercase. I'm pretty sure there is a logic for that, because I can't reproduce the issue @stephendonner has reported, so there is definitely something that decides whether strings are displayed in upper or lowercase.

![image](https://user-images.githubusercontent.com/20608253/169211893-18c926d1-1e10-456d-9d72-9146a32cbbe5.png)

I will appreciate it if someone can explain why we need the upper/lowercase checks and how to proceed in cases like this one, so I can help you fix such string differences in the future. I can't simply delete the message because you'll have to revert the changes once again for the message ID will not be found.

**Comment by stephendonner** [comment]
> Hey, @rebron !
> 
> I don't know how to proceed in such cases where you have the same string, with the same ID, for uses for upper and lowercase. I'm pretty sure there is a logic for that, because I can't reproduce the issue @stephendonner has reported, so there is definitely something that decides whether strings are displayed in upper or lowercase.
> 
> ![image](https://user-images.githubusercontent.com/20608253/169211893-18c926d1-1e10-456d-9d72-9146a32cbbe5.png)
> 
> I will appreciate it if someone can explain why we need the upper/lowercase checks and how to proceed in cases like this one, so I can help you fix such string differences in the future. I can't simply delete the message because you'll have to revert the changes once again for the message ID will not be found.

@Tonev mac uses "Title Case" and Windows and Linux use "Sentence Case" - does that help?

**Comment by Tonev** [comment]
Thank you, @stephendonner!

I'm still a bit lost here though. Does it mean editing the string that is inside the titlecase check will be enough to resolve this issue? I can't fully understand why there is a separate, different message if we want to achieve the same result on all OS's.

**Comment by fallaciousreasoning** [comment]
@sangwoo108 has fixed this!
https://github.com/brave/brave-browser/issues/23179

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.58 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

<img width="1312" alt="Screen Shot 2022-08-05 at 4 40 36 PM" src="https://user-images.githubusercontent.com/387249/183223942-7a70973e-9191-4f56-9d16-73b1703e6799.png">
