### ISSUE TITLE
Support procedural cosmetic filtering

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#16935]
Procedural cosmetic filtering is useful for the most evasive kinds of in-content sponsored/promoted material. It'd be great to implement this and tie it to aggressive shields settings, to handle the last few examples of cosmetic items slipping through on Reddit, YouTube, Facebook, etc.

See also:
- Reddit promoted content on mobile https://github.com/brave/brave-browser/issues/16789
- Facebook sponsored items https://github.com/brave/brave-browser/issues/15869
- YouTube empty video slots https://github.com/brave/brave-browser/issues/11955
- Washington Post anti-adblock https://github.com/brave/brave-browser/issues/21212

**Comment by antonok-edm** [comment]
Another use/test case: sponsored posts on stuff.co.nz

![image](https://user-images.githubusercontent.com/22821309/163021473-33630b4b-10b3-49b4-a834-abafba21ef07.png)

Should be handled by `stuff.co.nz##[itemprop]:has(.sponsored-flag)`

**Comment by intrnl** [comment]
How many filters makes use of other procedural filters? (e.g. `:has-text`)
I'd imagine Chrome's upcoming support for `:has` is going to make this slightly less necessary.

**Comment by antonok-edm** [comment]
> How many filters makes use of other procedural selector? (e.g. :has-text)

I did a survey of procedural filter operator counts in Brave's default lists a few days ago:

```
:has
    164
:has-text
    336
:matches-css
    15
:matches-css-before
    19
:matches-css-after
    2
:matches-path
    12
:not
    165
:upward
    239
:xpath
    49
```

It's not an exact metric since some filters can contain multiple chained operators, and `:not` is a special case since it's also a valid CSS pseudo-class, but this list still gives a good idea of how important each is. `has-text` in particular would be great to support.

> I'd imagine Chrome's upcoming support for :has is going to make this slightly less necessary.

The recent efforts on `:has` are commendable, but it actually has a _really_ long history and who knows what else may delay the implementation. Plus, support procedural cosmetic filters in general should make `:has` fairly simple anyways.

**Comment by dharnil** [comment]
Hi Braver, Is there any update on this open ticket. I happy to contribute.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.72.83 Chromium: 130.0.6723.58 (Official Build) beta (arm64)
-- | --
Revision | b49615851cd2dc4b1c3f5f13d3207d3c032bfd8d
OS | macOS Version 14.6.1 (Build 23G93)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | Windows 11 Version 23H2 (Build 22631.4391)
```


1. Installed 1.72.85
2. launched Brave
3. opened `brave://settings/shields/filters` in a new tab
4. added https://antonok.com/tmp/procedural-filter-tests/test-extended-css-rules.txt to `Custom lists`
5. visited https://antonok.com/tmp/procedural-filter-tests/index.html in a new tab

#### Confirmed following numbered test cases are passed
      - 1,2.3
      - 6,7,8,9
      - 20,21
      - 24
      - 26
      - 28,29


step 4 | step 5a | step 5b
----  | ------ | ----
![Image](https://github.com/user-attachments/assets/50497286-335b-4cd5-9431-eaace177169d)|![Image](https://github.com/user-attachments/assets/714529f6-d46b-4f30-9ec2-56b3bf07f95c)|![Image](https://github.com/user-attachments/assets/5031685a-7916-4886-a95d-0bc6d6ac6b0c)

**Comment by Uni-verse** [comment]
In progress on Android using the following version:

```
Brave	1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
Revision	5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using the following version(s):

```
Brave	1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (64-bit) 
Revision	69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Using test plan in https://github.com/brave/brave-core/pull/24688#issue-2412035316
   * Ensured the following test case numbers are passing on `https://antonok.com/tmp/procedural-filter-tests/index.html` after adding `https://antonok.com/tmp/procedural-filter-tests/test-extended-css-rules.txt` to custom filter list

      - [x] 1, 2, 3
      - [x] 6, 7, 8, 9
      - [x] 20, 21, 24
      - [x] 26, 28, 29

`example`| `example` | `example`
---|---|---
![Image](https://github.com/user-attachments/assets/26601ee8-c7a1-4c8d-b958-dd47c2d2c4ca) | ![Image](https://github.com/user-attachments/assets/5178398b-88e5-45d6-8ab2-d4fd0175f2d1) | ![Image](https://github.com/user-attachments/assets/b7c9b9c3-a09a-4820-a465-fd7b84553c12)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.72.95 Chromium: 131.0.6778.24 (Official Build) beta (64-bit) 
Revision	006619fbaf6013cb3495b90fc3885eda343087e5
OS	Linux
```

1. Installed 1.72.95
2. launched Brave
3. opened `brave://settings/shields/filters` in a new tab
4. added https://antonok.com/tmp/procedural-filter-tests/test-extended-css-rules.txt to `Custom lists`
5. visited https://antonok.com/tmp/procedural-filter-tests/index.html in a new tab

#### Confirmed following numbered test cases are passed
      - 1,2.3
      - 6,7,8,9
      - 20,21
      - 24
      - 26
      - 28,29


step 4 | step 5a |  step 5b
----  | ------ | ----
![Image](https://github.com/user-attachments/assets/60f554d7-3e04-4789-b1bf-771a237e2fd8)|![Image](https://github.com/user-attachments/assets/e783b6c3-33a1-4e91-88ce-e8076f7033be)|![Image](https://github.com/user-attachments/assets/27b16c17-b41e-4621-9fd8-e77a2c9d5210)

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7.1
- iPad Mini (6th gen) / iPadOS 18.0.1
Brave build: 1.73 (89)
BraveCore: 1.73.89 (131.0.6778.69)
```

Observed the issue #40771 which is not a blocker according to @antonok-edm 
---------------------------

**STEPS:**
1. Launch Brave 
2. Settings > Shields & Privacy
3. Content Filtering > Add Filter By URL
4. Add `https://antonok.com/tmp/procedural-filter-tests/test-extended-css-rules.txt` > Tap `Update Lists`
5. Disable all filters in `Default filter lists` > Tap `Update Lists`
6. Close the settings and navigate to `https://antonok.com/tmp/procedural-filter-tests/index.html`
7. *Verify*

**ACTUAL RESULTS:**
- Verified that the following numbered test cases are passed
  - 1, 2, 3
  - 6, 7, 8, 9
  - 20, 21
  - 24
  - 26
  - 28, 29

---------------------------

`iPhone 14`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/c8d36e30-f50f-41dd-9cf7-d26ed29e0138) | ![2](https://github.com/user-attachments/assets/161b555c-8f45-4802-84df-ba79b1125f02) | ![3](https://github.com/user-attachments/assets/66d6b30f-de0b-4bcc-83e6-e24299c65a66) | ![4](https://github.com/user-attachments/assets/f11aed4a-0d9a-4dda-b6bd-e909c87bc6ed) |

`iPad Mini (6th gen)`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/efbccab8-1397-4c26-b18e-07433a1d8662) | ![2](https://github.com/user-attachments/assets/ca59db09-e5c7-49ab-a859-46b89a3e4bb9) | ![3](https://github.com/user-attachments/assets/6439d293-eec2-4e6f-b144-7832ae0eacc7) | ![4](https://github.com/user-attachments/assets/03bd4cac-a854-4ff7-90d7-5ae1d73e496f) |
