### ISSUE TITLE
Rendering of web pages stop working at random.

### ISSUE THREAD

**Issue by ianwijma** [brave/brave-browser#16945]
## Description 

After having the brave browser open for a while, it just stops rendering new pages. this only affects new pages or duplicated pages. Existing pages can be reload and work just find. Also sound just works of the non-rendering pages. 

Note: This happens on my home machine running POP_OS! 21.04 and my machine running MacOS 10.14.6

## Steps to Reproduce

   1. Use brave for a while	
   2. At random the rendering stops working
   3. Reboot of brave fixes this issue

## Actual result:

Does not render the page

![image](https://user-images.githubusercontent.com/17692119/125621229-92d982f9-122c-4b94-8d19-57f649f60038.png)

## Expected result:

Renders the page

![image](https://user-images.githubusercontent.com/17692119/125621303-a50934ce-69b2-4f0c-899d-877cbb315b69.png)

## Reproduces how often: 

Hard, because it happens randomly.

## Brave version (brave://version info)

```
Brave	1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)
Revision	4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS	Linux
JavaScript	V8 9.1.269.36
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Command Line	/opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PasswordImport,ReducedReferrerGranularity,WebUIDarkMode,PrefetchPrivacyChanges,DnsOverHttps,LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip --disable-features=FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,HandwritingRecognitionWebPlatformApi,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,EnableProfilePickerOnStartup,TextFragmentAnchor,FederatedLearningOfCohorts,TrustTokens,DirectSockets,NotificationTriggers,WebOTP,IdleDetection,LangClientHintHeader,SubresourceWebBundles,NetworkTimeServiceQuerying,FledgeInterestGroups,InterestCohortFeaturePolicy,AutofillServerCommunication,LiveCaption,SignedExchangeSubresourcePrefetch,InterestCohortAPIOriginTrial,FirstPartySets,SignedExchangePrefetchCacheForNavigations --flag-switches-begin --flag-switches-end
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/ian/.config/BraveSoftware/Brave-Browser/Default
Variations	AdRewardsStudy:NextPaymentDay
AdServingStudy:MaximumAdNotificationsPerDay=100
BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0h
BraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5
EphemeralStorageStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
	- Yes, somewhat
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
	- Have not tried it. Needed to reboot Brave when it happened.
- Does the issue resolve itself when disabling Brave Rewards? 
	- Have not tried it. Needed to reboot Brave when it happened.
- Is the issue reproducible on the latest version of Chrome? 
	- Never seen this happen in Chrome, Which I used more than brave at work.

## Miscellaneous Information:

Sorry for the hard to solve issue, let me know what I can do to gather more information regarding this, because it happens now multiple times a week, and is getting quite hindering.

**Comment by ryanbr** [comment]
Can you test in private window mode, no extensions enabled? @ianwijma

**Comment by rebron** [comment]
Closing. @ianwijma We can reopen if you're stilling running into rendering issues.
