### ISSUE TITLE
Replace bookmarks bar folder image with ours

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#16940]
This issue is only for bookmarks bar folder image and is sub issue of  https://github.com/brave/brave-browser/issues/7312

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.28.85 Chromium: 92.0.4515.93 (Official Build) beta (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launch Brave
3. either populate or import bookmarks, and ensure `View` | `Always show bookmarks` is toggled to `On`
4. look at the bookmarks bar's folder icons
5. confirmed the icons were new and matched the style over in https://github.com/brave/brave-core/pull/9424

`light`

before | after
-------|------
<img width="1197" alt="Screen Shot 2021-07-19 at 5 24 00 PM" src="https://user-images.githubusercontent.com/387249/126244221-7dd96407-6899-4fba-b455-ab8c132816f8.png"> | <img width="1205" alt="Screen Shot 2021-07-19 at 5 24 09 PM" src="https://user-images.githubusercontent.com/387249/126244242-ecdfd7bb-673c-45a2-a05f-52257421ac86.png">



`dark`

before | after
-------|------
<img width="1196" alt="Screen Shot 2021-07-19 at 5 24 23 PM" src="https://user-images.githubusercontent.com/387249/126244256-86fb3e3c-4c5e-4430-9498-197a182d693c.png"> | <img width="1196" alt="Screen Shot 2021-07-19 at 5 24 37 PM" src="https://user-images.githubusercontent.com/387249/126244257-147d125c-2161-49fc-bd97-32fcfb04a298.png">
