### ISSUE TITLE
Why use C++ instead of Rust for Ethereum network client

### ISSUE THREAD

**Issue by namelessperson0** [brave/brave-browser#16942]
As per https://brave.com/bat-roadmap-update-2 Brave will use C++ for Ethereum network client to replace Metamask. 

However Brave has found good success with Rust as show in this link https://brave.com/improved-ad-blocker-performance

The ethereum network client requires high security and performance which Rust can provide better than C++.

When the code has to be written from scratch, why use C++ instead of Rust?

**Comment by bbondy** [comment]
The wallet is be built with many languages. The UI on desktop is TypeScript, the UI on Android is Java, many components that integrate with Chromium are C++, iOS is Swift/Objective C. We'll very likely also use Rust for some things like if there's a complex protocol to support later on. Chromium is C++ so it's a natural fit for the basic parts (Integration with EVM and HD wallet). We won't introduce Rust just to say we're using Rust, nor when it adds more complexity than benefit. But I wouldn't rule it out down the road for some sub-components.
