### ISSUE TITLE
NTP Tutorial Page doesn't load if you skip onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16949]
## Description 
NTP Tutorial Page doesn't load if you skip onboarding

## Steps to reproduce 

   1. Install 1.28.80 on JP locale
   2. Skip privacy stats onboarding
   3. No NTP Tutorial page is loaded

## Actual result 
NTP Tutorial Page doesn't load if you skip onboarding

## Expected result
Should show NTP Tutorial page irrespective of onboarding is completed or skipped

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.28.80 Nightly

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using the following build:

```
1.27.107 Chromium: 92.0.4515.107
```

* verification completed via https://github.com/brave/brave-browser/issues/16033#issuecomment-885095238

------------------

Verification **PASSED** on `Samsung Galaxy Tab A` running `Android 10` using the following build:

```
1.27.107 Chromium: 92.0.4515.107
```

* verification completed via https://github.com/brave/brave-browser/issues/16033#issuecomment-885095238
