### ISSUE TITLE
Notify user that a browser restart is required for in-line tipping toggle to take effect

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16941]
## Description

When toggling in-line tipping buttons, user needs to restart the browser in order for this to take effect.

Currently, there is no notice or banner telling the user that a browser restart is required, leading to confusion.

<img src="https://user-images.githubusercontent.com/11497541/125547597-c55b89b6-aaa9-4f50-bdbb-c64192dc1b75.png" width=300px>

## Solution

Whenever inline (content-level) tipping checkboxes are toggled in brave://rewards (settings page), put a banner at the top or bottom (can be existing Chromium object if easier) telling the user a browser restart is required for changes to take effect.

(Maybe compare the banner that shows up at bottom in brave://flags when things are toggled.)

## Notes

Related: https://github.com/brave/brave-browser/issues/5551

**Comment by emerick** [comment]
@Miyayes I show a small Relaunch button in the tips settings box when any inline tip option is toggled. This mimics how Chrome handles settings changes that require a browser restart (for example, when changing the default UI language in brave://settings). Let me know what you think!

![127354488-6ed8a5ea-9317-4742-b5f3-e39edf66e117](https://user-images.githubusercontent.com/5033691/127368183-88cfd163-8849-49bd-b195-0f3fac5a8eff.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/9582 with


Brave | 1.29.45 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 12.0 (Build 21A5294g)

Steps:
1. new profile
2. launched Brave
3. opened `brave://rewards`
4. clicked on the `Tip Settings` icon
5. toggled `Reddit` to `off` (deselected)
6. confirmed the `Relaunch` button appeared beneath the list of sites in `Tip Settings`
7. confirmed clicking `Relaunch` restarted the browser and restored current tabs
8. visited `reddit.com/u/alex_the_brave` verified it doesn't show tip buttons per new setting
9. toggled `Twitter` to `off` (deselected)
10. confirmed clicking on the `Relaunch` button restarted the browser
11. visited `twitter.com/bravelaurenwags` and confirmed no in-line tipping buttons
12. restored both `Reddit` and `Twitter` prefs back to `on` (selected)
13. confirmed their respective inline tipping buttons appears and worked (brought up appropriate tipping banner)

relaunch | reddit - disabled | reddit - enabled | twitter - disabled | twitter - enabled | github - disabled | github - enabled
---------|---------|----------|----------|-------------|-------------|--------------
<img width="1199" alt="Screen Shot 2021-08-02 at 3 46 03 PM" src="https://user-images.githubusercontent.com/387249/127934077-450c9b15-8ac9-41a7-bd36-383d8340c86b.png"> | <img width="1199" alt="Screen Shot 2021-08-02 at 3 46 56 PM" src="https://user-images.githubusercontent.com/387249/127934100-0ca03b3b-6e79-48ca-a39b-04e96e3260ea.png"> | <img width="1374" alt="Screen Shot 2021-08-02 at 4 03 53 PM" src="https://user-images.githubusercontent.com/387249/127934201-25bddf20-beb8-4120-bea3-3743503f22af.png"> | <img width="1385" alt="Screen Shot 2021-08-02 at 3 59 44 PM" src="https://user-images.githubusercontent.com/387249/127934267-089a6969-c589-4e34-b516-213f2f242a64.png"> | <img width="1384" alt="Screen Shot 2021-08-02 at 4 00 31 PM" src="https://user-images.githubusercontent.com/387249/127934293-61eb94b0-4d26-4b89-a8e4-a33630aceb44.png"> | <img width="1393" alt="Screen Shot 2021-08-02 at 4 11 47 PM" src="https://user-images.githubusercontent.com/387249/127934719-19bc91ce-da73-4a5b-bee4-721374aa7ad4.png"> | <img width="1386" alt="Screen Shot 2021-08-02 at 4 11 10 PM" src="https://user-images.githubusercontent.com/387249/127934718-838d5342-d853-4122-b53a-b9eee3e9bef0.png">
