### ISSUE TITLE
Ephemeral sessionStorage keeps cached values on renderer-initiated navigation with disabled site isolation

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#16946]
```sessionStorage``` backed by ```CachedStorageArea``` keeps cached values even if a browser side has removed ephemeral ```SessionStorageNamespace``` in "disable site isolation" mode.
The "disable site isolation" mimics Android-specific behavior where in some cases a renderer is reused.

This is related to https://github.com/brave/brave-browser/issues/15646 but in context of ```sessionStorage```.

**Comment by stephendonner** [comment]
Heya @goodov - mind attaching a testplan?  Thanks!

**Comment by goodov** [comment]
Test case is similar to https://github.com/brave/brave-browser/issues/15646 but a value check should be done via DevTools->Console.

This should give the same result with enabled and disabled Site Isolation.

1. new profile
2. load `brave://flags` and enable `Enable Ephemeral Storage` and disable `Ephemeral Storage Keep Alive` if it's available in the release
3. restart / relaunch Brave
4. load `https://dev-pages.brave.software/storage/keep-alive.html`
5. click on the `Start test` button beneath the `Should "Keep Alive" Test`
6. wait for the test to finish and return you to the original page
7. open DevTools->Console, choose 3p frame, write ```sessionStorage``` in console and ensure it is empty.

<details>
  <summary>3p frame in DevTools</summary>

![image](https://user-images.githubusercontent.com/5928869/127118207-fce64446-758d-485c-99ce-f0a02023bb77.png)

</details>

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan (thanks again @goodov) with build 


Brave | 1.29.31 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5.1 (Build 20G80)

Steps:

1. new profile
2. loaded `brave://flags` and enabled `Enable Ephemeral Storage` and disabled `Ephemeral Storage Keep Alive`
3. restarted / relaunched Brave
4. loaded `https://dev-pages.brave.software/storage/keep-alive.html`
5. clicked on the `Start test` button beneath the `Should "Keep Alive" Test`
6. waited for the test to finish and return me to the original page
7. opened DevTools->Console, choose 3p frame, wrote `sessionStorage` in console and ensured it was empty.

example | example | example
---------|----------|---------
<img width="1074" alt="Screen Shot 2021-07-27 at 12 37 43 PM" src="https://user-images.githubusercontent.com/387249/127217480-acce660b-93a1-40f7-ab0f-ecbf2c587de5.png"> | <img width="1382" alt="Screen Shot 2021-07-27 at 12 39 49 PM" src="https://user-images.githubusercontent.com/387249/127217485-e34edae7-7570-45b1-9d73-4cb3a76af863.png"> | <img width="1689" alt="Screen Shot 2021-07-27 at 12 40 07 PM" src="https://user-images.githubusercontent.com/387249/127217496-44535f5e-3f3a-482b-81f2-77aad56d8448.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.29.60 x64 Beta Build
- Verified test plan from https://github.com/brave/brave-browser/issues/16946#issuecomment-887300449

<img width=380 src=https://user-images.githubusercontent.com/17010094/129528218-0d49779e-b750-421d-96e9-dd4d03999af8.png> | ![image](https://user-images.githubusercontent.com/17010094/129528233-177f4760-fa56-49ff-9f6a-f79beb258800.png)
-- | --

-------------
Verification passed on Samsung Tab A with Android 10 running 1.29.60 x64 Beta Build
- Verified test plan from https://github.com/brave/brave-browser/issues/16946#issuecomment-887300449


<img width=500 src=https://user-images.githubusercontent.com/17010094/129532954-371791bf-d153-46a7-ba84-2ef52a3f9c9f.png> | ![image](https://user-images.githubusercontent.com/17010094/129532773-e5a087ea-3c7d-4818-b6a3-f7f57e7102a4.png)
-- | --
