### ISSUE TITLE
silent installer is failed on x86 when there is no BraveSoftware\Promo registry key

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#1695]
Reproduce steps
1. Delete HKEY_CURRENT_USER\Software\BraveSoftware\Promo if exists
2. Run brave_installer.exe on x86 windows platform

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (32-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

Each time used fresh Windows 7 32 bit VM.
Tested all the installers.
