### ISSUE TITLE
Move iOS recovery code option to Backup & Restore (Manage Your Wallet) area

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16954]
## Description

Since this applies to fewer and fewer users over time, this item is too upfront and should be moved out of the way (but retained).

![image](https://user-images.githubusercontent.com/11497541/125668487-1c28a1e2-c6e0-4f88-8778-031b62b989b9.png)

## Solution

In the `Restore` tab in the Manage Your Wallet modal area, add a line that says:

>**View QR Code** for iOS Rewards users transferring BAT. 

The "View QR code" will be a hyperlink that displays the QR code as it currently works.

**Placement:** This line should go under the paragraph ending in "... before restoring" on a new paragraph line.

![image](https://user-images.githubusercontent.com/11497541/125668835-37188af9-8338-4002-a9fb-5c7525a26ffc.png)

## Discussion

Please let me know if you think we should add a completely separate tab instead.

**Comment by emerick** [comment]
@Miyayes I show a small `Relaunch` button in the tips settings box when any inline tip option is toggled. This mimics how Chrome handles settings changes that require a browser restart (for example, when changing the default UI language in brave://settings). Let me know what you think!

![relaunch-button](https://user-images.githubusercontent.com/5033691/127354488-6ed8a5ea-9317-4742-b5f3-e39edf66e117.png)

**Comment by stephendonner** [comment]
Unable to fully test the QR code, as the QA team doesn't readily have a `1.25` build of Brave on iOS, to use.

Verified `PASSED` using the testplan at https://github.com/brave/brave-core/pull/9566 with


Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (x86_64)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:

1. Launched Brave
2. Visited `brave://rewards`
3. Verified that QR code section doesn't appear in `Settings` page
4. Clicked the gear/settings icon
5. Selected the `Restore` tab in the modal
6. Verified that QR code link looks as expected
7. Clicked the QR code link
8. ~~Verify that appropriate QR code displays~~
9. ~~Verify that QR code functions as expected~~

Checked that the QR code was visible, in the right place, and looked viable, but did **NOT** test the userdrain portion.

example | example | example
---------|----------|---------
<img width="1502" alt="Screen Shot 2021-08-30 at 2 20 02 PM" src="https://user-images.githubusercontent.com/387249/131407772-43fccbcf-7caf-45b7-9b29-cdd3fcccb949.png"> | <img width="1502" alt="Screen Shot 2021-08-30 at 2 20 09 PM" src="https://user-images.githubusercontent.com/387249/131407779-ad5c958d-67b5-4126-858b-ff29e86c7c48.png"> | <img width="1502" alt="Screen Shot 2021-08-30 at 2 20 12 PM" src="https://user-images.githubusercontent.com/387249/131407780-b2088a40-04b0-4776-bf87-2e72177fbd95.png">
