### ISSUE TITLE
Update the DDG URL in Tor mode to use their V3 Onion service

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16955]
DuckDuckGo has a new V3 Onion service which performs quite well:
https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion

We should use that URL instead of https://duckduckgo.com for everyone who has their search engine set to DDG in Tor windows.

It will avoid occasional error messages like this:
![Screenshot from 2021-07-14 11-41-17](https://user-images.githubusercontent.com/167821/125675450-28fa549c-e713-43c4-a24f-9fe369f1e4fd.png)

**Comment by fmarier** [comment]
cc @notpeter from DDG who shared the new endpoint with me.

**Comment by PeterDaveHello** [comment]
> DuckDuckGo has a new V3 Onion service which performs quite well

I have a difference experience, DuckDuckGo V3 Onion service seems to be less stale/reliable to me, easily timed out, no such problem on V2.

![image](https://user-images.githubusercontent.com/3691490/125791539-134ddfea-0f3e-4ac4-84a0-d9863706a88e.png)

**Comment by rebron** [comment]
Closing as stale. We're using Brave Search for Private Window with Tor.
