### ISSUE TITLE
Preload pages info text is changed

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#16957]
Same as https://github.com/brave/brave-browser/issues/16922, but for Desktop.

Remove `Preload pages for faster browsing and searching` toggle in brave://settings -> Privacy and security -> Cookies and other site data.

STR:

1. Start Brave (Nightly - cr92 based build).
2. Navigate to `brave://settings` -> `Privacy and security` -> `Cookies and other site data`

Current result:
There is a `Preload pages for faster browsing and searching` toggle with the description `Preloads pages that Brave thinks you might visit. To do this, Brave may use cookies, if you allow cookies, and may encrypt and send pages through Brave to hide your identity from sites.`

Expected result:
The toggle is not present on the page.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.27.107 Chromium: 92.0.4515.107 (Official Build) (64-bit)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2004 (Build 19041.1110)

```

- Verified description from the issue and ensured `Preload pages for faster browsing and searching toggle` with the description `Preloads pages that Brave thinks you might visit. To do this, Brave may use cookies, if you allow cookies, and may encrypt and send pages through Brave to hide your identity from sites` is removed from brave://settings/cookies
![image](https://user-images.githubusercontent.com/38657976/126631058-58bd9232-d4ed-439c-8568-842580eeb5a0.png)
