### ISSUE TITLE
update Brave beta icon

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#16953]
## Description 
Use the same blue Brave icon that we use for the Dev channel for the beta icon but with beta label.

## Steps to Reproduce

Download Brave beta.

## Actual result:

<img width="36" alt="Screen Shot 2021-07-14 at 1 12 30 PM" src="https://user-images.githubusercontent.com/2388823/125686599-4e1cd000-36bc-44be-9bd8-c9159de4f945.png">

## Expected result:
Change Beta build to use blue icon.

![image](https://user-images.githubusercontent.com/2388823/125686567-36c1d6b7-c112-475f-a02a-0d0b780b73aa.png)

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Assets
MacOS: https://drive.google.com/open?id=19vpBbv-bjQjgbHvytkp7plltXzaVrhyi&authuser=kliu%40brave.com&usp=drive_fs 
Windows: https://drive.google.com/open?id=1kJtFeXfVACtjD5iHSbwuTAdrnm9ikrmW&authuser=kliu%40brave.com&usp=drive_fs

**Comment by karenkliu** [comment]
Designs added!

**Comment by rodrigoswz** [comment]
Since this is also expected to occur in Brave Beta for Android at any moment, please consider already add an adaptive icon to close #14660 issue

**Comment by simonhong** [comment]
@karenkliu needs more assets for windows - `ico` format files for icon and file type below.
<img width="168" alt="Screenshot 2021-07-15 at 13 48 37" src="https://user-images.githubusercontent.com/6786187/125730577-b226c2d4-f886-4305-a113-fafd63af8dcb.png">

**Comment by simonhong** [comment]
@karenkliu  One more thing I need help is about resolution of file type ico.
As you can see, brave logo ico and brave file ico have same 32x32 demensions.
but brave logo file looks bigger than brave file image. To generate brave file image ico, I used online converter(png -> ico) by using your png. but it looks not good.
![image](https://user-images.githubusercontent.com/6786187/125734088-96860555-2b0d-4684-84c2-bd03631468e6.png)

**Comment by bsclifton** [comment]
Love the Blue beta 😄

**Comment by srirambv** [comment]
@karenkliu @rebron Is the change only for Desktop for now? I don't see an Android issue created for the icon change

cc: @anthonypkeane

**Comment by karenkliu** [comment]
We should do it for update the Beta icon everywhere.

**Comment by simonhong** [comment]
@rebron maybe we will have another issue for beta icon for mobile?

**Comment by srirambv** [comment]
@simonhong added Android specific issue  #17025

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.29.51 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.1 (Build 20G80)

example | example
---------|---------
<img width="802" alt="Screen Shot 2021-08-07 at 6 18 01 PM" src="https://user-images.githubusercontent.com/387249/128617755-370d940e-73d8-4a56-80ae-0afcd5d8bd02.png"> | <img width="1046" alt="Screen Shot 2021-08-07 at 6 18 24 PM" src="https://user-images.githubusercontent.com/387249/128617756-f65fa1b7-ed7e-415c-9af0-0e24e678a73d.png">
