### ISSUE TITLE
Reenable SE onboarding for DE/IE/NZ/AU

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16965]
## Description 
Re-enable SE onboarding for DE/IE/NZ/AU regions

### Additional information

Related to #11021 & #16870

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using the following build:

```
Brave 1.27.107 Chromium: 92.0.4515.107
```

* verification notes can be found under https://github.com/brave/internal/issues/789#issuecomment-885422039
