### ISSUE TITLE
Temp remove backup modal actions

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1696]
We should hide them until we have this one in https://github.com/brave/brave-browser/issues/929

**Comment by srirambv** [comment]
Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/47173486-31815e00-d2dc-11e8-83af-457e6671b515.png)
