### ISSUE TITLE
Create a JS API for requesting ads enabled

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#16964]
API should ask the user for permission to enable ads.

**Comment by diracdeltas** [comment]
is this the work for https://docs.google.com/document/d/1v1GJkVoZD-t8st0Yqhs9NIZvwrKd6m0HcITOcfkZCKQ/edit?

please file a security review when the code is ready, thanks. https://github.com/brave/security/issues/new/choose

**Comment by aseren** [comment]
> is this the work for https://bravesoftware.slack.com/archives/CELA35G5S/p1624627578005000?
>
Yes, it is.

> please file a security review when the code is ready, thanks. https://github.com/brave/security/issues/new/choose
>
Okay, I will do, thank you!

**Comment by jsecretan** [comment]
Sizing at 1 point remaining

**Comment by mattmcalister** [comment]
Add copy on re-enabling ads popup "By turning on Ads, you agree to the Terms of Service and Privacy Policy."

See https://github.com/brave/brave-browser/issues/18292
