### ISSUE TITLE
Remove EAFF custom header

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16961]
This header was tied to a custom homepage campaign that is no longer active.

**Comment by stephendonner** [comment]
Verified `PASSED`; followed the steps from https://github.com/brave/brave-core/pull/9442 and confirmed the custom `EAFF` header is **NOT** present, in 


Brave | 1.29.5 Chromium: 92.0.4515.101 (Official Build) nightly (x86_64)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | macOS Version 11.4 (Build 20F71)

pre-fix (with `X-Brave-Partner: eaff` header | post-fix (missing `X-Brave-Partner: eaff` header
--------|--------
![125708823-d4fe23d3-5dac-49ab-a6ff-6577f93c0b43](https://user-images.githubusercontent.com/387249/125991863-6e90b01f-14a3-4b9c-b93d-b3596bbcca0b.png) | <img width="990" alt="Screen Shot 2021-07-16 at 11 17 08 AM" src="https://user-images.githubusercontent.com/387249/125991739-e50dcc38-d756-44f7-bc7d-c070a937ab10.png">

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.29.60 x64 Beta build
- Verified test plan from brave/brave-core#9442. 
- Verified `X-Brave-Partner: eaff` header is not included
 
Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
![image](https://user-images.githubusercontent.com/17010094/129542217-2f6e2186-6c5a-4916-80b4-ab87ecfa38e4.png) | ![image](https://user-images.githubusercontent.com/17010094/129542394-bbd8c384-e822-4be0-8d78-630d59970f46.png)
