### ISSUE TITLE
Feature Request: Please make the bookmarks manager keyboard accessible. 

### ISSUE THREAD

**Issue by leeniu** [brave/brave-browser#1697]
Hello dear maintainers,

first, thanks for the effort you put into this project!

To the topic: as many of us would probably agree, using the keyboard more often adds to your computer productivity and usage speed. Using bookmarks in Firefox is a breeze, due to the sidebar (as discussed in other tickets here) that is accessible via the TAB key. (CTRL + B, TAB, TAB and you are there)

I figured that you can access the bookmark manager with CTRL + SHIFT + O (in Windows), but for some reason I am not able to TAB into the manager in order to navigate to a bookmark to then open it hitting ENTER.

It would be very nice if the bookmark manager would be accessible via the keyboard so you don't have to touch the mouse to open bookmarks.

Thanks for your time.

**Comment by srirambv** [comment]
Which version are you running? Mind adding the details from `brave://version`? I am able to navigate using TAB button once I open bookmark manager with CTRL+SHIFT+O

**Comment by leeniu** [comment]
Ok, there seems more strange stuff going on here. I actually can't execute brave://version from the search bar, nothing happens. Is this a layer 8 error again?

**Comment by srirambv** [comment]
You are actually on the release version of browser-laptop which will be deprecated soon and will be replaced with Brave-Browser. This repository is for the new version of Brave-Browser that will be available. You can download the latest beta from https://brave.com/download-beta. 

Closing the issue for now but please continue any conversations on the same issue.

**Comment by leeniu** [comment]
Awesome, thank your for your quick response, support and time. Sry to bother.
