### ISSUE TITLE
laggy webgl on windows

### ISSUE THREAD

**Issue by mmaenz** [brave/brave-browser#16973]
## Description 
When browsing to [github.com](github.com) there is a webgl spinning globe which lags.
I'm using Brave Browser on Windows and Mac at home and Google Chrome at work. None of us is using the github landing page so I didn't recognise it. But on my Windows machine at home I wasn't logged in and when I went to github the globe stutters. Tried on Mac, everything is fine. Tried Brave Browser on my machine at work, it stutters too. Screenshots taken with private mode so no logout of github is required.

Seems to be a Windows only problem. Maybe there's some flags that differ?
![image](https://user-images.githubusercontent.com/22559887/125817107-681ca9ec-c702-461b-89c3-edb3533e4b29.png)

## Steps to Reproduce
On Windows and Mac 
   1. Open new Brave window in private mode
   2. Goto [github.com](github.com)
   3. Watch the spinning globe

## Actual result:
On Windows the globe lags
On Mac the globe is spinning smoothly

## Expected result:
Smoothly spinning globe on Windows

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Laggy Windows: ![image](https://user-images.githubusercontent.com/22559887/125814873-463b6102-27ab-4c02-a1a3-12d720dc1755.png)
Working Mac: ![image](https://user-images.githubusercontent.com/22559887/125816718-4a18d6a7-44a0-4370-ab70-2e5f150f7943.png)

## Version/Channel Information:
I didn't try other channels.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?: **No**
- Does the issue resolve itself when disabling Brave Rewards?: **No** 
- Is the issue reproducible on the latest version of Chrome?: **No**

## Miscellaneous Information:
None

**Comment by mmaenz** [comment]
I had a closer look and tried several examples with Brave and ThreeJS.
On Windows, WebGL seems unusable, it lags very hard at 2fps:
![image](https://user-images.githubusercontent.com/22559887/125935508-1d591185-a509-4294-8c7f-cb837d759d87.png)


Tried same on macOS as mentioned above and the result is as exprected with capped 60fps:
![image](https://user-images.githubusercontent.com/22559887/125936031-27a12635-aa70-4bf3-8492-a84ed527a1f9.jpg)

**Comment by ryanbr** [comment]
Ensure you have Hardware Acceleration enabled in `brave://settings/system` @mmaenz 

Tested on my low end laptop (Using Vega 10 Graphics AMD APU).

https://threejs.org/examples/#webgl_animation_keyframes  `68-86fps`

https://threejs.org/examples/#webgl_animation_cloth   `100+ fps`

**Comment by mmaenz** [comment]
Thank you so much! This did the trick. I had to turn it on.

Isn't hardware acceleration enabled in windows by default?
Now I have same fps on mac and windows (bootcamp) on same machine.
