### ISSUE TITLE
Safe shutdown for ipfs node on mac

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#16978]
## Description 

Someitmes we kill the node without allowing it to remove lock file and it fails launch start next time with error `brave_ipfs/repo.lock: someone else has the lock`

## Steps to Reproduce

   1. Fast start/stop node on macos, especially when node is busy with something as migration
   2. If the node will not respond more than 2 seconds it will be killed without removing lock file
   3. The node will fail start next time with `brave_ipfs/repo.lock: someone else has the lock` error

## Actual result:

Unable to start node

## Expected result:

Start/stop node works correctly

## Reproduces how often: 

rare, only if start/stop when node is busy with something

**Comment by lidel** [comment]
What is the mechanism Brave uses for stopping go-ipfs?

iirc there `ipfs shutdown` CLI command can be used for graceful shutdown,  alternative is to send `SIGHUP`, `SIGINT` or `SIGTERM` – those should trigger graceful shutdown as well. 

If graceful shutdown does not finish within your time budger, `SIGKILL` will trigger forced shutdown. 

When go-ipfs is no longer running, there should be no `$IPFS_PATH/repo.lock`. If it was left due to forceful shutdown, Brave should remove it before starting it again.

**Comment by stephendonner** [comment]
For posterity, this is what it looks like when it happens:

<img width="1100" alt="Screen Shot 2021-07-14 at 4 40 32 PM" src="https://user-images.githubusercontent.com/387249/125872094-6ac6bccb-4350-4f33-8be4-2b00cb7c41f6.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


Brave | 1.30.30 Chromium: 92.0.4515.159 (Official Build) nightly (x86_64)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | macOS Version 11.5.2 (Build 20G95)

### Steps:
1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3. load `brave://ipfs-internals/`
4. click `Install and start`
5. clicked `Start`, `Restart`, and `Stop` repeatedly, varying timing a bit (but usually doing so quickly)

Confirmed I never saw `Error: lock /Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser/brave_ipfs/repo.lock: someone else has the lock` which is easily reproducible in earlier builds

before fix | with fix
----------|--------
<img width="1330" alt="Screen Shot 2021-08-18 at 10 10 47 AM" src="https://user-images.githubusercontent.com/387249/129949031-ef7265cd-5d33-4933-9495-b6035bfd5fe4.png"> | <img width="1320" alt="Screen Shot 2021-08-18 at 11 01 31 AM" src="https://user-images.githubusercontent.com/387249/129949056-449aa1bc-fa7a-4646-9211-bda7993edfaf.png">
