### ISSUE TITLE
[P3A] Update `Brave.Search.DefaultEngine` to include Brave Search

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#16970]
**Q20: Which is your currently selected search engine?**
`Brave.Search.DefaultEngine.4` [D] [A]

Other
Google
DuckDuckGo
Startpage
Bing
Qwant
Yandex
Ecosia
**Brave Search**

**Comment by bsclifton** [comment]
This is already done - however, I forgot to notify folks for stats (doh)
https://github.com/brave/brave-core/pull/8966/files#diff-5ac72f147b974a5c7cfafdf0ea3c72b0147e313768f5c8ea037f07523f0b36f5R40

Created https://github.com/brave/stats/issues/725 to address
