### ISSUE TITLE
Bookmark folder icon has got changed in 1.28.x (Dev) and 1.29.x (Nightly)

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#16989]
## Description 

The bookmark folder icon has got changed in 1.28.x (Dev) and 1.29.x (Nightly)

## Steps to Reproduce

   1. Clean profile 1.28.x or 1.29.x
   2. Import bookmark folders
   3. Bookmark folders icon has got changed in 1.28.x (Dev) and 1.29.x (Nightly)

## Actual result:

**1.27.x**

![image](https://user-images.githubusercontent.com/38657976/125921529-704d47d8-e271-4d5f-b3e7-9375383dc662.png)

**1.28.x**
![image](https://user-images.githubusercontent.com/38657976/125921674-474ffa5a-d2be-4f11-9fec-e2be07052e39.png)

**1.29.x**
![image](https://user-images.githubusercontent.com/38657976/125921798-76765335-e9e9-4869-8dd8-3d70e1f462b8.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.28.84 Chromium: 92.0.4515.93 (Official Build) dev (64-bit)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

Brave | 1.29.3 Chromium: 92.0.4515.101 (Official Build) nightly (64-bit)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | Windows 10 OS Version 2004 (Build 19041.1083)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron

**Comment by simonhong** [comment]
@GeetaSarvadnya we updated folder icon at bookmarks bar - https://github.com/brave/brave-core/pull/9424

**Comment by GeetaSarvadnya** [comment]
@simonhong Thanks! Closing the issue as invalid.
