### ISSUE TITLE
Brave private ads should read Brave Private Ads in brave://settings/shields

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16987]
## Description 

`Brave private ads` should read `Brave Private Ads` in `brave://settings/shields`.

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `brave://settings/shields`
   4. read the 2nd paragraph under `Block trackers and ads which follow you across the web.`
  

## Actual result:

Reads `Brave private ads`.

<img width="727" alt="Screen Shot 2021-07-15 at 9 50 16 PM" src="https://user-images.githubusercontent.com/387249/125893557-7d36eb6f-a6c5-47b6-a699-2a6624d17cc7.png">

## Expected result:

Should read `Brave Private Ads`.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.29.3 Chromium: 92.0.4515.101 (Official Build) nightly (x86_64)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | macOS Version 12.0 (Build 21A5268h)

/cc @rmcfadden3 @karenkliu

**Comment by deepxcode** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.29.12 Chromium: 92.0.4515.101 (Official Build) nightly (x86_64)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | macOS Version 11.4 (Build 20F71)

Steps:

1. new profile
2. launch Brave
3. load `brave://settings/shields`
4. read the 2nd paragraph under `Block trackers and ads which follow you across the web`.

Confirmed it reads `Brave Private Ads` now.

<img width="723" alt="Screen Shot 2021-07-20 at 9 44 55 AM" src="https://user-images.githubusercontent.com/387249/126363634-6db93964-82ca-41e5-8ee9-3d4d87944d68.png">
