### ISSUE TITLE
Text cursor disappears at the end of currency input

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#16983]
## Description 

Text cursor disappears when a user tries to click at the end of an amount input.

## Steps to Reproduce

   1. Go to Swap or Send screen.
   2. In the amount field, click on the space after the number. The bug is seen only when the input is an integer.

## Actual result:

The cursor disappears.

<img width="400" alt="Screenshot 2021-07-15 at 23 59 20" src="https://user-images.githubusercontent.com/3684187/125863515-2b20c830-e59f-46d8-9ca0-09c04d47e687.png">

## Expected result:

The cursor of type "text" should appear, just like it does when clicking on the space before the number.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 1.26.74 Chromium: 91.0.4472.124 (Official Build) (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | All
Component | 1.0.32 Dev

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards?  N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

N/A

**Comment by srirambv** [comment]
Verification passed on 


Brave | 1.26.74 Chromium: 91.0.4472.124 (Official Build) (x86_64)
-- | --
Revision | `7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.35 Dev`

- Verified cursor is displayed when an integer value is entered and clicked on the right side of the value
- Verified cursor is displayed when a float value is entered and clicked on the right side of the decimal value
- Verified on both swap screen and send screen

https://user-images.githubusercontent.com/17010094/125912285-20df1407-a508-4a50-984b-30a9834e3aaa.mov


-----

Verification passed on 

Brave | 1.28.83 Chromium: 92.0.4515.93 (Official Build) beta (64-bit)
-- | --
Revision | `6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}`
OS | Windows 10 OS Version 2009 (Build 19043.1083)
Component | `1.0.35 Dev`

- Verified cursor is displayed when an integer value is entered and clicked on the right side of the value
- Verified cursor is displayed when a float value is entered and clicked on the right side of the decimal value
- Verified on both swap screen and send screen

https://user-images.githubusercontent.com/17010094/125913887-0bc27484-7ec7-40d9-ad82-0af8b77c4c7e.mov

-----

Verification passed on 

Brave | 1.29.3 Chromium: 92.0.4515.101 (Official Build) nightly (64-bit)
-- | --
Revision | `edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}`
OS | Linux
Component | `1.0.35 Dev`

- Verified cursor is displayed when an integer value is entered and clicked on the right side of the value
- Verified cursor is displayed when a float value is entered and clicked on the right side of the decimal value
- Verified on both swap screen and send screen

https://user-images.githubusercontent.com/17010094/125913696-deacc191-4e8d-49e4-857a-161454a1df27.mov
