### ISSUE TITLE
Suggest "Allow contribution to videos" be "Allow contributions for videos"

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16986]
## Description 

Suggest "Allow contribution to videos" be "Allow contributions for videos"

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open a new tab and click `Start using Rewards`
   4. open `brave://rewards`
   5. scroll down to `Auto-Contribute Settings`
   6. under `Other settings`, look at `Allow contribution to videos`

## Actual result:

It currently reads `Allow contribution to videos`

<img width="334" alt="Screen Shot 2021-07-15 at 4 24 13 PM" src="https://user-images.githubusercontent.com/387249/125870296-f0b3c106-e92d-4c29-8484-f55e3862308f.png">

## Expected result:

Might be slightly more accurate to say `Allow contributions for videos`, since you're not actually contributing to the videos themselves.  (I'm less confident in my suggestion to pluralize `contributions` here, and could go either way.)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.27.105 Chromium: 92.0.4515.93 (Official Build) (x86_64)
-- | --
Revision | 6eb43ff7850a1d710c3f827a0555737c74edab5c-refs/branch-heads/4515@{#1378}
OS | macOS Version 11.4 (Build 20F71)

/cc @rmcfadden3

**Comment by deepxcode** [comment]
@stephendonner  I would like to contribute to this issue.

**Comment by deepxcode** [comment]
@stephendonner  I think this would sound correct `Allow contribution for videos` instead of `Allow contributions for videos`.
Do let me know so that I can make the changes accordingly.

**Comment by rmcfadden3** [comment]
@stephendonner — yeah, let's go with "Allow contributions for videos" where "contributions" is plural. It's consistent with the text that appears above it (non-verified sites).

If you wanted something more explicit, you could say like "Allow contributions to video producers" or "Allow contributions to video creators" or similar. But, honestly, I think that just adds to the confusion rather than remove. So let's just stick with the general "Allow contributions for videos" and call it good.

**Comment by AnudeepGunukula** [comment]
Hi @stephendonner . if this issue is still open kindly assign it to me.
i will make a pr as soon as possible.

**Comment by stephendonner** [comment]
> Hi @stephendonner . if this issue is still open kindly assign it to me.
> i will make a pr as soon as possible.

Awesome; done!  Thanks!

**Comment by stephendonner** [comment]
Thanks for looking into this originally, @deeppandya; going to assign to @AnudeepGunukula for what is probably his first contribution to Brave - hope you understand, and cheers.

**Comment by AnudeepGunukula** [comment]
Hi @stephendonner. i had made a pr kindly let me know the changes if needed.

**Comment by deepxcode** [comment]
> Thanks for looking into this originally, @deeppandya; going to assign to @AnudeepGunukula for what is probably his first contribution to Brave - hope you understand, and cheers.

I totally understand and appreciate and encourage the new contributors to be part of the Brave community and contribute to it.

Also😅, you  mentioned the wrong user, My username is @deepxcode .

**Comment by stephendonner** [comment]
> > Thanks for looking into this originally, @deeppandya; going to assign to @AnudeepGunukula for what is probably his first contribution to Brave - hope you understand, and cheers.
> 
> I totally understand and appreciate and encourage the new contributors to be part of the Brave community and contribute to it.
> 
> Also😅, you mentioned the wrong user, My username is @deepxcode .

Sorry, yes, yes it is, @deepxcode; I accidentally pinged my colleague :-(

**Comment by AnudeepGunukula** [comment]
Hi @stephendonner . kindly review the pr 
brave/brave-core#9814 
and please let me know the changes if needed

**Comment by srirambv** [comment]
This should have been marked for both Android and Desktop. @AnudeepGunukula  mind creating a separate PR for Android? I'll add an issue and link it here

**Comment by bsclifton** [comment]
Closing - somewhere along the line, this was updated and fixed 👍
