### ISSUE TITLE
Add a Brave controlled address for swap fees on Ropsten

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16988]
## Description 
Add a Brave controlled address for transactions on Ropsten

cc: @bbondy @onyb

**Comment by bbondy** [comment]
What is this for?

**Comment by onyb** [comment]
The Swap `feeRecipient` address we use for Ropsten is actually a random mainnet address I grabbed from etherscan. It makes sense to use an address that we (or at least I) control for easier QA. Not that important.

**Comment by bbondy** [comment]
ah ok, I didn't have the context of swap

**Comment by onyb** [comment]
Fixed in https://github.com/brave/ethereum-remote-client/pull/268/commits/9d904fdb0637cce1696b9300d81894633f666e9d.
