### ISSUE TITLE
Publishing to IPNS should be in separate menu 

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#16998]
## UX Problem

There is confusing inconsistency in sharing menu.

By default, we show simple actions for sharing IPFS CIDs: 

>  ![2021-07-16--15-28-44](https://user-images.githubusercontent.com/157609/125955895-f6d4876b-a154-4789-b3f7-c5fad54d8019.png)

Note there is no way to share over IPNS (which IMO is a bug, because `self` key is always present).

To enable IPNS sharing, one needs to go to settings and click on "Set up IPNS keys":

> ![2021-07-16--15-29-14](https://user-images.githubusercontent.com/157609/125955893-8526c4ee-e26d-452e-93f5-764884be854e.png)

You dont need to add any, just open it. There is `self` key by default.

After that, a confusing submenu is presented in the main menu:

> ![1-2021-07-16--15-26-03](https://user-images.githubusercontent.com/157609/125955900-de72e29f-f18c-4a99-be67-56eb2dfb8d5d.png)

It has problematic UX → the most common use case (sharing static IPFS CID) is buried 2 levels deep, and users most likely will abandon interaction or pick IPNS without fully understanding it is mutable publishing.

### Proposed fix 

I believe submenu is too confusing.
Instead, we should  have IPNS in the top menu:

```
IPFS → 
        Share local file using IPFS              (no submenu, instant action)
        Share local directory using IPFS         (no submenu, instant action)
        Publish local file under IPNS key      → (submenu key list)
        Publish local directory under IPNS key → (submenu with key list)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.37.40 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

### `Case 1: publish with local node`
1. install `1.37.40`
2. launch Brave
3. load `ipns://ipfs.io`
4. click `Use a Brave local IPFS node`
5. click the 3-dots menu
6. click on `Import and Share a File`
7. click on `Import and Share a Directory`
8. click on `Open Files`
9. click on `Update IPNS` -> `With a File` -> `self {key}`
10.click on `Update IPNS` -> `With a Directory` -> `self {key}`

#### `Import and Share` (`File`, `Directory`)


file | file | directory | directory
----|-----|------|--------
<img width="1299" alt="Screen Shot 2022-02-10 at 2 44 19 PM" src="https://user-images.githubusercontent.com/387249/153521277-cdcf94b0-d6a3-4d3a-a4ee-012189c75669.png"> | <img width="1020" alt="Screen Shot 2022-02-10 at 2 46 15 PM" src="https://user-images.githubusercontent.com/387249/153521291-d0c1c8f6-eeda-4fd7-a1e5-1827f2a1c449.png"> |<img width="1591" alt="Screen Shot 2022-02-10 at 2 47 08 PM" src="https://user-images.githubusercontent.com/387249/153521350-89329239-735f-4625-b3d1-834d3a6d4d34.png"> | <img width="1312" alt="Screen Shot 2022-02-10 at 2 49 23 PM" src="https://user-images.githubusercontent.com/387249/153521356-f3fb10e9-2711-4a81-bf10-a3ed333fb504.png">



#### `Open Files`

example | example
---------|---------
<img width="1553" alt="Screen Shot 2022-02-10 at 4 52 02 PM" src="https://user-images.githubusercontent.com/387249/153521737-7d08e3ab-f91e-4456-a472-f6d8a9a5f051.png"> | <img width="1274" alt="Screen Shot 2022-02-10 at 4 51 49 PM" src="https://user-images.githubusercontent.com/387249/153521805-ea11d1c8-5c1e-49ce-bfae-7c1fe8a4454f.png">



#### `Update IPNS` with (`File`, `Directory`)

file | file | directory | directory
----|-----|------|--------
<img width="1591" alt="Screen Shot 2022-02-10 at 2 55 09 PM" src="https://user-images.githubusercontent.com/387249/153521916-cfdccc78-ad91-4a53-8ca0-56df6a05a0de.png"> | <img width="1312" alt="Screen Shot 2022-02-10 at 2 56 54 PM" src="https://user-images.githubusercontent.com/387249/153522159-f534182e-2538-4963-8819-726c1a931b20.png"> | <img width="1591" alt="Screen Shot 2022-02-10 at 2 57 38 PM" src="https://user-images.githubusercontent.com/387249/153522224-d74229e6-28ac-4ade-ba90-f4f4600d2419.png"> | <img width="1312" alt="Screen Shot 2022-02-10 at 2 59 29 PM" src="https://user-images.githubusercontent.com/387249/153522272-e0fb18c2-3f52-4b64-a67d-7ff9a22acc4f.png">





### `Case Two: IPFS flyout menu`
1. install `1.37.40`
2. launch Brave
3. click on the `"hamburger"` menu
4. confirmed there is no `IPFS` flyout menu
5. load `brave://ipfs-internals/`
6. click `Use a Brave local IPFS node`
7. open `brave://settings/ipfs`
8. choose any one of the `Ask`, `Gateway`, `Disabled` options under `Method to resolve IPFS resources`
9. click on the `"hamburger"` menu again
10. confirm you now see the `IPFS` flyout menu item

default | `ask` / `gateway` / `disabled` | `Brave-local IPFS node enabled`
---------|----------|--------
<img width="1274" alt="Screen Shot 2022-02-10 at 4 38 33 PM" src="https://user-images.githubusercontent.com/387249/153520542-c2cff610-0776-4f16-9b11-475f6916c348.png"> | <img width="1161" alt="Screen Shot 2022-02-10 at 4 43 22 PM" src="https://user-images.githubusercontent.com/387249/153521056-33fadb5c-71f8-4b79-85d4-83d4a419281f.png"> |<img width="1162" alt="Screen Shot 2022-02-10 at 4 43 41 PM" src="https://user-images.githubusercontent.com/387249/153521062-33c76170-18b7-490f-86b7-8aeb4fa1ff89.png">
