### ISSUE TITLE
Update to Chromium 91.0.4472.164

### ISSUE THREAD

**Issue by Area51Kacz** [brave/brave-browser#17005]
Could we update to Chromium 91.0.4472.164 

https://chromereleases.googleblog.com/2021/07/stable-channel-update-for-desktop.html

**Comment by LaurenWags** [comment]
This has already been completed:

https://github.com/brave/brave-browser/issues/16836#issuecomment-881676280 (desktop)
Android is phased release.

https://github.com/brave/brave-browser/releases/tag/v1.26.77
