### ISSUE TITLE
Ads received this month value is incorrect - follow up to #16861

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#17006]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/16861

"Current earnings this month (estimated)" looks to be correct after https://github.com/brave/brave-browser/issues/16861, but the "Ads received this month" value is only showing the server value and is not accounting for those ads which were viewed but not cashed in/redeemed with the server.

## Steps to Reproduce

Much like https://github.com/brave/brave-browser/issues/16861, need to have a profile in this state like I do 😞 

## Actual result:

Ads received this month says 83

<img width="665" alt="1 29 x" src="https://user-images.githubusercontent.com/28145373/126006070-94321afa-64fd-4200-959d-709c6788c594.png">
 

## Expected result:

Expected 87 which would be server value of 83 + 4 views not redeemed

## Reproduces how often: 

 unsure

## Brave version (brave://version info)

1.29.5

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure, possibly
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Discussed with Terry, looks like my confirmations.json shows 83 views, which would be why I'm seeing 83. However, this seems odd. It's possible I've gotten myself into a weird position and this is not a bug - @tmancey is investigating and will close this issue if this is not a bug.

**Comment by tmancey** [comment]
Closing issue as works for me, and after checking @LaurenWags data it would appear in all of our testing this has got corrupt. However, it will fix itself from August 1st.
