### ISSUE TITLE
center speedreader icon

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#17004]
The one we have right now is a offset one pixel too high.

**Comment by kjozwiak** [comment]
We should at least check that it looks good/correct within the URL bar as per https://github.com/brave/brave-core/pull/9475#issuecomment-884417630.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.29.20 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 11.4 (Build 20F71)

Confirmed it's vertically centered, and looks good in both `light` and `dark` modes.

light | dark
-----|------
<img width="1201" alt="Screen Shot 2021-07-22 at 3 12 27 PM" src="https://user-images.githubusercontent.com/387249/126716205-3c4fcaa9-7697-4428-85e7-dba649391a1d.png"> | <img width="1184" alt="Screen Shot 2021-07-22 at 3 16 06 PM" src="https://user-images.githubusercontent.com/387249/126716377-dbea58a2-87d9-44b8-9860-5bcd3e3a603f.png">
