### ISSUE TITLE
sync button text  too long in italian translation

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#17017]
## Description 

when I want to configure sync there is a button with the text that is too long
I think the second buitton should go under the fdirst one, not on the right.

![image](https://user-images.githubusercontent.com/26486758/126073325-afd83299-07a2-47d6-bd11-a93564ff5756.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Brave-Matt** [comment]
Also happens in French translation:
![image](https://user-images.githubusercontent.com/3299098/186485152-bcdb133d-2170-4783-a527-623fead973a5.png)

**Comment by rebron** [comment]
cc: @fallaciousreasoning When you get a chance can you take a look?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.35 Chromium: 105.0.5195.102 (Build ufficiale) nightly (x86_64)
-- | --
Revisione | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
Sistema operativo | macOS Versione 13.0 (Build 22A5331f)

`Italian`

example | example | example
---------|---------|----------
<img width="1312" alt="Screenshot 2022-09-08 alle 2 41 55 PM" src="https://user-images.githubusercontent.com/387249/189232072-553baee1-8a9a-4ba9-8b9b-2c7932e7238d.png"> | <img width="612" alt="Screenshot 2022-09-08 alle 2 42 00 PM" src="https://user-images.githubusercontent.com/387249/189232077-29bca825-19aa-4b8d-a0b4-73dd5b51f64b.png"> | <img width="1770" alt="Screenshot 2022-09-08 alle 2 42 08 PM" src="https://user-images.githubusercontent.com/387249/189232082-33958456-806f-490e-be7f-f7b2c6391447.png">


`French`

example | example | example
---------|----------|---------
<img width="1065" alt="Capture d’écran 2022-09-08 à 2 55 47 PM" src="https://user-images.githubusercontent.com/387249/189233326-784f3686-01c2-48d5-b910-5d2f49200e50.png"> | <img width="612" alt="Capture d’écran 2022-09-08 à 2 55 57 PM" src="https://user-images.githubusercontent.com/387249/189233333-08044df0-8728-4a79-b7f0-e76c815b8a9b.png"> | <img width="1748" alt="Capture d’écran 2022-09-08 à 2 55 52 PM" src="https://user-images.githubusercontent.com/387249/189233331-b9915b5f-2c3d-440a-bf05-701cec9981b1.png">
