### ISSUE TITLE
Toggling Show Bookmarks has no effect in private window

### ISSUE THREAD

**Issue by sandeepspatil** [brave/brave-browser#17012]
## Description 
Toggling "Show Bookmarks" has no effect in the private window, it is always shown. It works fine in a normal window. If I have two windows open side by side and toggle the "Show Bookmarks" (in any window), it only toggles the bar in the normal window, no change in private window.

## Steps to Reproduce
   1. Open a Private window (any of the two options)
   2. Open the menu by clicking on the burger menu in the window 
   3. toggle Show Bookmarks, it should show/hide the bookmark bar just below the address bar. 

## Actual result:
No toggling, the bookmark bar is always shown

## Expected result:
The bookmark bar should toggle hide/show

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? --- Yes
- Can you reproduce this issue with the beta channel? --- Not Tried
- Can you reproduce this issue with the nightly channel? --- Not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? I don't have Chrome, works fine on Edge.

**Comment by TheUnixDude** [comment]
On Ubuntu Linux, it has no effect at all, regardless of private window. No matter what I've tried, I can't get rid of the annoying bar. Removing all the imported bookmarks (or just moving them to Other bookmarks) leaves horizontal "For quick access, place your bookmarks here on the bookmarks bar" text.

**Comment by bsclifton** [comment]
This is definitely a weird one - thanks for the report! Toggling `Show Bookmarks` just goes it on the non-private window 🤔 

cc: @rebron

**Comment by rebron** [comment]
Closing as invalid. `Always show bookmarks on new tab page` is the toggle that will hide the bookmarks bar on the New tab page private window, normal new tab page and in Tor Window new tab page.

**Comment by TheUnixDude** [comment]
This is still reproducible on the build listed, but is fixed at least as of 1.40.107 Chromium 103/0/5060.52 in Ubuntu 22. So if anyone runs across this Issue in the future the issue was fixed in some unknown build between ~1.26 and 1.40.

So "closed/invalid" is not accurate, but good enough.
