### ISSUE TITLE
https://back.egybest.co/ detects adlocker

### ISSUE THREAD

**Issue by youssef20031** [brave/brave-browser#17010]
## Description 

So `https://back.egybest.co/` detects an adblocker and tells to disable it which is intersting

## Steps to Reproduce

   1. Use brave
   2. Open `https://back.egybest.co/`
   3. If it did not give any warnings try going into a submenu

## Actual result:

![Screenshot 2021-07-17 003753](https://user-images.githubusercontent.com/43968405/126014914-ecac7766-277c-4833-ad65-9ac54a6b8225.png)

## Expected result:
![Screenshot 2021-07-17 003841](https://user-images.githubusercontent.com/43968405/126014922-ab0dbaa8-7676-4124-9a18-5cae77b3b8ba.png)

## Reproduces how often: 

Every time

## Brave version (brave://version info)

<html>
<body>

Brave | 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
-- | --
Revision | 541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel? 
- N/A
- Can you reproduce this issue with the nightly channel? 
- N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- No

## Miscellaneous Information:

If anyone needs translation, please do not hesitate to contact me

**Comment by rebron** [comment]
Closing as invalid. Website looks like it's no longer around.
