### ISSUE TITLE
SE onboarding order is wrong

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17023]
## Description 
SE onboarding order is wrong

## Steps to reproduce 

   1. Set locale to IE/NZ/AU/DE
   2. Clean install 1.29.8 x64 nightly build
   3. Click on URL bar to trigger SE onboarding
   4. Order is different, also Brave is missing from SE list (https://github.com/brave/brave-browser/issues/17022)

**Actual result**  |  **Expected result**
-- | --
![image](https://user-images.githubusercontent.com/17010094/126116170-6547ee37-37b1-4de7-ac24-79af7e647e85.png) | ![image](https://user-images.githubusercontent.com/17010094/126116190-6021ec80-6f8b-4c1b-8eae-fe1c3b6fdd3f.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.29.8

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @bsclifton

**Comment by bsclifton** [comment]
Closing - I've raised with product (@janypiotrowski) and we can see what next steps are after they get a chance to evaluate
