### ISSUE TITLE
Getting no BAT on Android 11

### ISSUE THREAD

**Issue by Phil1988** [brave/brave-browser#17027]
## Description 
I am on Android 11 (Build/RKQ1.200826.002) and installed the latest Brave browser (1.26.74) via play store.
Even after 5 days of usage, I still dont have and BAT.
But I do get notification-adds.

## Steps to reproduce 

   1. Install brave from play store
   2. use brave
   3. no BAT

## Actual result 
![photo_2021-07-19_12-49-57](https://user-images.githubusercontent.com/6054234/126149293-df89a202-39aa-477c-8466-29b3048f3b95.jpg)

## Expected result
Getting BAT. As I also get adds :)
![Inkedphoto_2021-07-19_12-45-51_LI](https://user-images.githubusercontent.com/6054234/126149650-238e70f0-9b53-41c1-94cb-44d4e3a20088.jpg)

## Version/Channel Information:

- Happens with the current Play Store version.

## Device details
   - Device type (Phone, Tablet, Phablet): Mi Note 10 Lite
   - Android version: 11 (Build/RKQ1.200826.002) a
   
## Brave version
1.26.74

### Additional information
SafetyNet test passed
![photo_2021-07-19_12-50-10](https://user-images.githubusercontent.com/6054234/126149555-7303776d-fe4b-4ecb-b942-041d7d14f9bb.jpg)

**Comment by thefallofbecause** [comment]
You have two BAT balances. The balance you are looking at only updates monthly around the 5th-8th of each month.

To see your pending balance before the payout date you need to go into your Rewards settings.

**Comment by Phil1988** [comment]
like this?
![photo_2021-07-19_13-33-57](https://user-images.githubusercontent.com/6054234/126154077-6f72bf26-ab57-47d4-8896-16e5f2eb0d5d.jpg)

**Comment by Miyayes** [comment]
Press on "Detaillerte Informationen Anzeigen >". You will see your estimated pending rewards there.

We understand this is not the best UI, and we are currently in the midst of updating this page on Android to be much more intuitive to users.
