### ISSUE TITLE
Brave is missing from SE onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17022]
## Description 
Brave is missing from SE onboarding

## Steps to reproduce 

   1. Clean install 1.29.8 x64 nightly build
   2. Click on URL bar to trigger SE onboarding
   3. Brave is missing from the list
   4. Open Settings -> Search Engine, Brave is listed

## Actual result 

https://user-images.githubusercontent.com/17010094/126115177-efb820a2-7ec2-4c00-8e40-576210aa72d8.mp4

## Expected result
Brave should be listed in SE onboarding

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.29.8

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @bsclifton

**Comment by bsclifton** [comment]
This is expected; when Brave Search added (see https://github.com/brave/brave-browser/issues/15663) it was only added to onboarding for US and Canada
