### ISSUE TITLE
search brave

### ISSUE THREAD

**Issue by Pantyhose-X** [brave/brave-browser#17021]
## Expected result:

https://search.brave.com/ open source
https://searx.me/ Privacy-respecting metasearch engine open source

**Comment by bsclifton** [comment]
@Pantyhose-X not exactly sure what you're asking for here?

- Brave Search should be added as a default under brave://settings/searchEngines (under `Default search engines`)
- searx.me can be added after visiting it by using the same page (brave://settings/searchEngines under `Other search engines`)
