### ISSUE TITLE
Update Verifiable Ad Conversions regex

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#17039]
We capture values using a regex (1) but then validate with a different regex (2). There is no need for a superset of Conversion IDs for a decision tree so we should just use the same capture group group in both cases `[-a-zA-Z0-9]`

ie. update (1) to use regex `<meta.*name=\"ad-conversion-id\".*content=\"([-a-zA-Z0-9]*)\".*>`

(1) https://github.com/brave/brave-core/blob/9bdcdd4da4e63e405cad25bb9ecbd4aa88a2bb5a/vendor/bat-native-ads/src/bat/ads/internal/features/conversions/conversions_features.cc#L24

(2) https://github.com/brave/brave-core/blob/9bdcdd4da4e63e405cad25bb9ecbd4aa88a2bb5a/vendor/bat-native-ads/src/bat/ads/internal/security/conversions/conversions_util.cc#L35

Once completed, make follow up task to remove this the fix from Griffin
https://github.com/brave/brave-variations/pull/115

**Comment by LaurenWags** [comment]
@tmancey can you please provide a test plan for this one?

**Comment by iambrianfung** [comment]
@LaurenWags same test plan as https://github.com/brave/brave-variations/pull/108

cc: @tmancey to confirm these suffice

**Comment by LaurenWags** [comment]
awesome, thanks guys, appreciate it
