### ISSUE TITLE
[Android] Add "Show all pending contributions" view 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17038]
## Description

Add "Show all pending contributions" view on Android to match desktop.

## New UI

New UI on brave://rewards settings page. When user presses "See all", it should open up into a view of all the pending tips (pending contributions list) that is responsive for Android/mobile. 

Ask @Miyayes or @mkarolin for Figma.

**Comment by Miyayes** [comment]
With the new Rewards redesign, the pending contributions view only appears on the brave://rewards settings page as a line item (see screenshot below). cc: @emerick 

![image](https://user-images.githubusercontent.com/11497541/147152781-93905f14-66e2-4152-923f-b07e984ea2f6.png)

**Comment by emerick** [comment]
@Miyayes @minkyeongshin I think we probably need to rethink this design a little bit for Android. If we want to make the smallest change possible, we could drop some columns for Android (say `Type` and `Pending Until`). Not sure if that would be enough, but it might work.

Or if we wanted to make a more comprehensive change that retained all of the data but laid things out in a more vertical format, something like:

```
cnn.com (Trash can icon)
  Type: One-time tip
  Pending Until: 02/01/2022
  Amount: 0.250 BAT 0.30 USD
  
yahoo.com (Trash can icon)
  Type: One-time tip
  ...
```

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.38.83
