### ISSUE TITLE
Gemini wallet shows up as "Missing wallet" in rewards-internals

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#17032]
## Description 
Gemini wallet shows up as `Missing wallet` in `rewards-internals`.

## Steps to Reproduce
Go to `brave://rewards-internals`.

## Actual result:
![image](https://user-images.githubusercontent.com/5390451/126181905-b81a4e68-b0c7-48b6-be43-3a7dc3dd227a.png)

## Expected result:
```
Total balance 30 BAT
bitFlyer Wallet: 0 BAT
Rewards BAT: 30 BAT
Gemini Wallet: 0 BAT
Uphold Wallet: 0 BAT
```
## Reproduces how often: 
100%

## Brave version (brave://version info)
Building from source.
```
Brave    1.29.9 Chromium: 92.0.4515.101 (Developer Build) (64-bit)
Revision edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS       Windows 10 OS Version 2009 (Build 19043.1110)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? ❌
- Can you reproduce this issue with the beta channel? ❌
- Can you reproduce this issue with the nightly channel? ❌

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ❌
- Does the issue resolve itself when disabling Brave Rewards? ❌
- Is the issue reproducible on the latest version of Chrome? ❌

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.29.43 Chromium: 92.0.4515.115 (Official Build) nightly (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Windows 10 OS Version 2004 (Build 19041.1110)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/9585#issue-699018851
![image](https://user-images.githubusercontent.com/38657976/127889452-a8c990b4-b2ba-4ac3-bbc7-e401f1d51e64.png)
