### ISSUE TITLE
Always show "Refresh status" button in the Rewards dropdown panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17030]
## Description

On desktop, the "Refresh status" button always appears in the dropdown panel, regardless of the state of the Creator. However, on Android, there are cases where the Refresh status button does not appear. 

**Example (STR):**

1. Have verified user wallet on Android 
2. Go to batcommunity.org
3. Notice that batcommunity.org does not have a refresh status button. (On desktop, it does have a refresh status button in the exact same circumstances.)

## Solution

Show "Refresh status" button in the Rewards dropdown panel in _all_ cases.

**Comment by srirambv** [comment]
This is already shipped in 1.27.x via https://github.com/brave/brave-browser/issues/15966
