### ISSUE TITLE
[Android] Add 30-day ads history view

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17035]
## Description

Add 30-day ads history view on Android to match desktop.

![image](https://github.com/brave/brave-browser/assets/11497541/4f3b8fca-201b-4814-b818-175a663afdac)

https://www.figma.com/file/ag8i1OV5vpvn4SiOhW2c0f/Github-fixes?type=design&node-id=3105-53171&t=mjqKNy5HwHKCI1ug-0

https://github.com/brave/brave-browser/issues/16418 (previous request from community)

**Comment by emerick** [comment]
This will probably need a slightly tweaked design for Android.

**Comment by Miyayes** [comment]
Will be solved by Rewards 3.0 redesign.
