### ISSUE TITLE
How Brave browser check a link is verified creator?

### ISSUE THREAD

**Issue by izzetemredemir** [brave/brave-browser#17048]
Can somebody explain how to verified publisher check mechanism work or send a link?

Which api use for it ?

**Comment by bsclifton** [comment]
Hi @izzetemredemir - sorry this question got lost in the mix

Sounds like you are wanting to get a list of verified publishers (or check if a given publisher is verified)?

I'm not sure if there's a public API for this available
cc: @Miyayes @yachtcaptain23 

I'm going to close this issue though as this isn't a feature request or problem with the browser itself; we have a separate repo for publishers (for example https://github.com/brave-intl/publishers)
