### ISSUE TITLE
Update links for "Add Funds" and "Withdraw Funds" buttons for Gemini 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17045]
## Solution

Use the following links for the "Add Funds" and "Withdraw Funds" buttons 

Add funds: https://exchange.gemini.com/transfer/deposit

Withdraw funds: https://exchange.gemini.com/transfer/withdraw 

@jumde Let me know if you see anything incorrect with above! 

## Test Plan
Specified Here: https://github.com/brave/brave-core/pull/9519

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.29.60 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.1 (Build 20G80)
```

Verified test plan from https://github.com/brave/brave-core/pull/9519
Confirmed `Add Funds` link from panel and brave://rewards directs to expected URL:
<img width="1186" alt="Screen Shot 2021-08-13 at 12 49 31 PM" src="https://user-images.githubusercontent.com/28145373/129393121-98624891-ae85-4b95-a352-a81bd0be333e.png">
Confirmed `Withdraw Funds` link from brave://rewards directs to expected URL:
<img width="1192" alt="Screen Shot 2021-08-13 at 12 49 45 PM" src="https://user-images.githubusercontent.com/28145373/129393185-631c49a2-acce-4134-b8fe-1242d2885a87.png">
