### ISSUE TITLE
Does Brave respect user data dir?

### ISSUE THREAD

**Issue by angelog0** [brave/brave-browser#17057]
On GNU/Linux (Mint) I unpacked [this](https://github.com/brave/brave-browser/releases/download/v1.27.106/brave-browser-1.27.106-linux-amd64.zip) ZIP and started Brave with this command line:

```
./brave-browser --user-data-dir=/tmp/Brave_data --disable-brave-update --no-default-browser-check --disable-logging --disable-breakpad
```

Brave start and works but I noticed that it, in addition to `/tmp/Brave_data` folder, creates also `~/.config/BraveSoftware`. Shouldn't it create just `/tmp/Brave_data` directory?

```
$ ls -R ~/.config/BraveSoftware/
~/.config/BraveSoftware/:
Brave-Browser

~/.config/BraveSoftware/Brave-Browser:
'Crash Reports'   NativeMessagingHosts

'~/.config/BraveSoftware/Brave-Browser/Crash Reports':
attachments  completed  new  pending  settings.dat

'~/.config/BraveSoftware/Brave-Browser/Crash Reports/attachments':
'~/.config/BraveSoftware/Brave-Browser/Crash Reports/completed':
'~/.config/BraveSoftware/Brave-Browser/Crash Reports/new':
'~/.config/BraveSoftware/Brave-Browser/Crash Reports/pending':
~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts:
```

I thested this also creating a shortcut (_launcher_) with the same result...

**Comment by bsclifton** [comment]
@angelog0 yes, this should definitely be working and I believe it is. The `NativeMessagingHosts` folder is created for compatibility with extensions that write to that folder for communication with native apps. For example, 1Password will do this
