### ISSUE TITLE
Site shield settings are not working as expected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#17052]
## Description 
Site shield settings are not working as expected

## Steps to reproduce 

   1. Clean profile 1.27.106
   2. Open CNN.com
   3. Open the shield and check the ads and trackers count in the shield
   4. Select `Allow all trackers and ads` from Block trackers & ads settings
   5. Reload cnn.com
   6. Ads and trackers still blocked in shield

## Actual result 
Site shield settings are not working as expected

## Expected result
Site-level settings should work as expected

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Not sure
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Tab
   - Android version: 10
   
## Brave version
1.27.106
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane

**Comment by LaurenWags** [comment]
Reproduced on Asus Zenfone (x86) using 1.27.106. Putting shields down entirely works as expected.

**Comment by kjozwiak** [comment]
Nice catch @GeetaSarvadnya 👍

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.27.107, Chromium 92.0.4515.107` on a Google Pixel XL, running Android 9.

Steps:

1. new profile; launched `1.27.107`
2. opened `CNN.com`
3. opened Shields and checked the ads and trackers count in the shield
4. next, selected `Allow all trackers and ads` from `Block trackers & ads` settings
5. reloaded `cnn.com`

Confirmed there were `0` blocked trackers and ads on `cnn.com`.

example | example | example
---------|----------|---------
![Screenshot_20210722-095412](https://user-images.githubusercontent.com/387249/126691535-960b7623-3d98-44ba-9a55-4a9c30ba308a.png) | ![Screenshot_20210722-095433](https://user-images.githubusercontent.com/387249/126691545-73365d30-9b7d-4f9c-9f9d-90905282e5c1.png) | ![Screenshot_20210722-095458](https://user-images.githubusercontent.com/387249/126691547-8477e6b5-1105-4972-996d-d33fd1c05f2a.png)
