### ISSUE TITLE
Add wallet_active to stats usage ping

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#17059]
Will include data for `wallet_daily`, `wallet_weekly`, and `wallet_monthly`. To reduce the number of query parameters on the server-side, we will send it up as a bitstring.

#### Prerequisites 

1. A clean browser profile
2. A system whereby it is possible to modify the system clock
3. Charles proxy, wireshark, or other HTTP sniffing tool 

#### Scenario 1
Without enabling brave crypto wallets, close browser, move system time forward one day, open browser. Stats ping should be the same with a new parameter walletActive=0

##### Step 1: Daily, weekly, monthly
In this order: (1) Enable brave crypto wallets, (2) close browser, (3) move systems time forward by one day (ensure the month and week don’t change), (4) restart browser and look for stats ping. Stats ping should include walletActive=7 on the following stats ping.

##### Step 2: Weekly, monthly
Do not use the crypto wallet. Move system time forward an arbitrary number of days within the same week (greater than 1 day from). Restart browser. Stats ping should include walletActive=6.

##### Step 3: Monthly
Do not use the crypto wallet. Move system time forward an arbitrary number of days within the same month (greater than 1 week). Restart browser. Stats ping should include walletActive=4.

##### Step 4: Re-enabling
Use the crypto wallet. Close browser. Move system time forward by a day. Restart browser. Stats ping should include walletActive=7.

**Comment by keur** [comment]
Added p2 because @bbondy asked for this to be uplifted. cc @kjozwiak @stephendonner

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (64-bit)
-- | --
Revision | `c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}`
OS | Linux

<details>
<summary>Scenario 1</summary>
<br/>

- Verified without enabling Crypto Wallet, stats ping shows new parameter `&walletActive=0`
![image](https://user-images.githubusercontent.com/17010094/131373484-cc7fbcb3-c861-43c2-80a0-72313c147691.png)

</details>

<details>
<summary>Scenario 2</summary>

<br>

<details>
<summary>Step 1:  (Daily, Weekly, Monthly)</summary>
<br/>

- Enabled crypto wallet, closed browser
- Move device date ahead to the next date within the same week/month
- Restart the browser and verified stats ping now includes `&walletActivie=7`
![image](https://user-images.githubusercontent.com/17010094/131373509-033b114e-100e-4a24-acc5-7fd472c65e96.png)

</details>
<details>
<summary>Step 2: (Weekly, monthly)</summary>
<br/>

- Enabled crypto wallet, closed browser
- Move device date ahead to a random day within the same week/month 
- Restart the browser and verified stats ping now includes `&walletActivie=6`
![image](https://user-images.githubusercontent.com/17010094/131373529-05a3e36f-9e89-4b6c-bc1d-3dcc51768af9.png)

</details>
<details>
<summary>Scenario 3: Monthly</summary>
<br/>

- Did not use crypto wallet, closed browser
- Move device date ahead to a future date within the same month 
- Restart the browser and verified stats ping now includes `&walletActivie=4`
![image](https://user-images.githubusercontent.com/17010094/131373446-ebbaf9b7-e9c3-455f-a8b3-3690ef44afe6.png)

</details>
<details>
<summary>Scenario 4: Re-enabling</summary>
<br/>

- Logged into crypto wallet and added a new account and closed browser
- Move device date ahead to the next date
- Restart the browser and verified stats ping now includes `&walletActivie=7`
![image](https://user-images.githubusercontent.com/17010094/131373466-a08b5885-e9dc-47c6-8471-a419c7873041.png)

</details>
</details>

-----------

Verification passed on 

Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (64-bit)
-- | --
Revision | `c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}`
OS | Windows 10 OS Version 2009 (Build 19043.1110

<details>
<summary>Scenario 1</summary>
<br/>

- Verified without enabling Crypto Wallet, stats ping shows new parameter `&walletActive=0`
![image](https://user-images.githubusercontent.com/17010094/131373323-dd16e402-71d0-4853-b58e-0c65ea025087.png)

</details>

<details>
<summary>Scenario 2</summary>

<br>

<details>
<summary>Step 1:  (Daily, Weekly, Monthly)</summary>
<br/>

- Enabled crypto wallet, closed browser
- Move device date ahead to the next date within the same week/month
- Restart the browser and verified stats ping now includes `&walletActivie=7`
![image](https://user-images.githubusercontent.com/17010094/131373349-b533527a-1139-4c86-ad69-e9e6102a9ea8.png)

</details>
<details>
<summary>Step 2: (Weekly, monthly)</summary>
<br/>

- Enabled crypto wallet, closed browser
- Move device date ahead to a random day within the same week/month 
- Restart the browser and verified stats ping now includes `&walletActivie=6`
![image](https://user-images.githubusercontent.com/17010094/131373369-cd19b7d0-1b9e-4a6c-a613-603f5d88e4aa.png)

</details>
<details>
<summary>Scenario 3: Monthly</summary>
<br/>

- Did not use crypto wallet, closed browser
- Move device date ahead to a future date within the same month 
- Restart the browser and verified stats ping now includes `&walletActivie=4`
![image](https://user-images.githubusercontent.com/17010094/131373384-6ecf8d93-ac50-49ae-a5b4-08ab1d0d22b8.png)

</details>
<details>
<summary>Scenario 4: Re-enabling</summary>
<br/>

- Logged into crypto wallet and added a new account and closed browser
- Move device date ahead to the next date
- Restart the browser and verified stats ping now includes `&walletActivie=7`
![image](https://user-images.githubusercontent.com/17010094/131373405-f6b0a849-b5d1-463c-ba20-e4919fe9b049.png)

</details>
</details>

-----------

Verification passed on 


Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (x86_64)
-- | --
Revision | `c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}`
OS | macOS Version 11.5.2 (Build 20G95)

<details>
<summary>Scenario 1</summary>
<br/>

- Verified without enabling Crypto Wallet, stats ping shows new parameter `&walletActive=0`
![image](https://user-images.githubusercontent.com/17010094/131373224-eaa484fc-b06e-48b9-b30c-16e67bd70927.png)

</details>

<details>
<summary>Scenario 2</summary>

<br>

<details>
<summary>Step 1:  (Daily, Weekly, Monthly)</summary>
<br/>

- Enabled crypto wallet, closed browser
- Move device date ahead to the next date within the same week/month
- Restart the browser and verified stats ping now includes `&walletActivie=7`
![image](https://user-images.githubusercontent.com/17010094/131373250-d6115bbc-c8b7-4bf0-8bd0-c42681d5c844.png)

</details>
<details>
<summary>Step 2: (Weekly, monthly)</summary>
<br/>

- Enabled crypto wallet, closed browser
- Move device date ahead to a random day within the same week/month 
- Restart the browser and verified stats ping now includes `&walletActivie=6`
![image](https://user-images.githubusercontent.com/17010094/131373134-2d649a2c-ac66-4895-9317-b282d6fefa92.png)

</details>
<details>
<summary>Scenario 3: Monthly</summary>
<br/>

- Did not use crypto wallet, closed browser
- Move device date ahead to a future date within the same month 
- Restart the browser and verified stats ping now includes `&walletActivie=4`
![image](https://user-images.githubusercontent.com/17010094/131373162-141aa9b7-136b-4dc7-b852-c6c27d19a8f9.png)

</details>
<details>
<summary>Scenario 4: Re-enabling</summary>
<br/>

- Logged into crypto wallet and added a new account and closed browser
- Move device date ahead to the next date
- Restart the browser and verified stats ping now includes `&walletActivie=7`
![image](https://user-images.githubusercontent.com/17010094/131373180-455f2ff8-5d39-4d31-8d18-6f8f2437e07e.png)

</details>
</details>
