### ISSUE TITLE
UX: brave://settings text and subtext for humanweb

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#17053]
Similar to the usage ping, we need to add a toggle to the settings page for humanweb. It is opt-in by default. @remusao has more information.

**Comment by karenkliu** [comment]
We need @rmcfadden3 our copywriter to take a look at this toggle text.

**Comment by rmcfadden3** [comment]
@keur — can you include link to a planning doc or mock or something so I can see this in context? Once I have that I can try to draft something.

**Comment by rmcfadden3** [comment]
hi all. heads up that I crafted a bunch of copy for this (including the Settings toggle), and bumped to Aldo and Josep to review. Hopefully light edits, at which point I can get over to you to use.

**Comment by rebron** [comment]
Closing as stale. Addressed with WDP changes.
