### ISSUE TITLE
Still shows 7-day Ads History in popup linked from 30-day Ads History on brave://rewards

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17063]
## Description 

Still shows 7-day Ads History in popup linked from 30-day Ads History on brave://rewards

(Cross-reference with https://github.com/brave/brave-browser/issues/16627 which bumped # of ads history days from 7 -> 30.)

## Steps to Reproduce

   1. new profile
   2. launch with `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
   3. open a new-tab page
   4. click on `Start using Rewards`
   5. trigger, view, and click on an ad (either via opt-in to Brave News or regular)
   6. load `brave://rewards`
   7. look at the 30-days Ad History link
   8. click on it
   9. look at the # of days presented in the popup

## Actual result:

**30-day Ads History**

<img width="1425" alt="Screen Shot 2021-07-20 at 6 08 17 PM" src="https://user-images.githubusercontent.com/387249/126415886-ddb6a8d3-2186-4781-807b-2eecd470f431.png">

**7-day ads history**

<img width="1770" alt="Screen Shot 2021-07-20 at 6 19 03 PM" src="https://user-images.githubusercontent.com/387249/126415923-2aa79570-b744-4fa8-b516-a46bc15ba2c5.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.29.12 Chromium: 92.0.4515.101 (Official Build) nightly (x86_64)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | macOS Version 11.4 (Build 20F71)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? no

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with build 


Brave | 1.29.23 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 11.5 (Build 20G71)

Steps:

1.  new profile
2.  launch with `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3.  open a new-tab page
4.  click on Start using Rewards
5.  trigger, view, and click on an ad (either via opt-in to Brave News or regular)
6.  load `brave://rewards`
7.   look at the 30-days Ad History link
8.  click on it
9.  look at the # of days presented in the popup

Confirmed both places say `30 day(s)` in the UI.

example | example
---------|---------
<img width="1416" alt="Screen Shot 2021-07-23 at 9 50 30 AM" src="https://user-images.githubusercontent.com/387249/126816148-e12ac997-fda0-4ad1-b5a2-e0d8cfa86500.png"> | <img width="1416" alt="Screen Shot 2021-07-23 at 9 50 34 AM" src="https://user-images.githubusercontent.com/387249/126816156-4a545e3a-3f1f-4846-be63-8ba21c3fb520.png">

**Comment by stephendonner** [comment]
@tmancey I think given https://github.com/brave/brave-browser/issues/16627 we should take an uplift into `1.28.x` for this issue; thoughts?

**Comment by tmancey** [comment]
@stephendonner please see https://github.com/brave/brave-core/pull/9543, thanks

**Comment by stephendonner** [comment]
Verified `FIXED` on 


Brave | 1.28.96 Chromium: 92.0.4515.115 (Official Build) beta (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5.1 (Build 20G80)

Steps:

1.  new profile
2.  launch with `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3.  open a new-tab page
4.  click on `Start using Rewards`
5.  trigger, view, and click on an ad (either via opt-in to Brave News or regular)
6.  load `brave://rewards`
7.  look at the `30-days Ad History` link
8.  click on it
9.  look at the # of days presented in the popup

example | example
---------|---------
<img width="1770" alt="Screen Shot 2021-07-29 at 11 32 54 AM" src="https://user-images.githubusercontent.com/387249/127546952-de9e7e59-34d6-4ef4-8baf-9a5714c171d2.png"> | <img width="1770" alt="Screen Shot 2021-07-29 at 11 32 58 AM" src="https://user-images.githubusercontent.com/387249/127546954-c56d343a-0fcc-4985-87e1-5b3612d1ae36.png">
