### ISSUE TITLE
Browser is slow to detect (lag) clickable content

### ISSUE THREAD

**Issue by ksajan** [brave/brave-browser#17064]
## Description 

While visiting the web pages mostly noticeable media players such as youtube and some websites. It takes a little bit of time to convert my cursor to a clickable cursor. 

## Steps to Reproduce

   1. Go youtube 
   2. Watch  2 to 3 videos
   3. while watching video move your cursor on the media content you will a lag

## Actual result:

There is noticeable lag sometimes when visit websites with media content mainly

## Expected result:
There shouldn't be any lag

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Brave | 1.26.77 Chromium: 91.0.4472.164 (Official Build) (x86_64)
-- | --
Revision | 541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569}
OS | macOS Version 11.4 (Build 20F71)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

I have some extensions installed for adblocking such as ublock, etc.

**Comment by ryanbr** [comment]
Try in private window mode, with no extensions. Having both shields and uBlock enabled may cause additional delays

**Comment by rebron** [comment]
Closing as stale. Let us know if this still an issue for you @ksajan in version 1.62.162.
