### ISSUE TITLE
Remove connected state for Gemini

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#17079]
## Description 
If the user is not verified on Gemini, the user is in the `Connected` state which allows the user to initiate the verification with Gemini. 

Update the workflow to show user an error when the `user is not verified` - 

```
“You’ll need to verify your account on Gemini first. Once you’ve completed identity verification for your Gemini account, please try again!”
```

**Comment by Miyayes** [comment]
Noting: This error should be the big error modal popup on Rewards settings page if possible. The little notification in the dropdown panel is not visible enough.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.29.57 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 10.15.7 (Build 19H1323)
```

Verified test plan from https://github.com/brave/brave-core/pull/9603

Steps used:
1. Clean profile, non-Japan region, staging environment. Enable Gemini in brave://flags and relaunch as necessary.
2. Enable Rewards
3. Select Verify Wallet and login with non-KYC'd Gemini account

example logs:

```
[ REQUEST ]
> URL: https://api.qa6.aurora7.net/v1/payments/recipientIds
> Method: POST
[88655:259:0811/161730.436072:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://api.qa6.aurora7.net/v1/payments/recipientIds
> Result: Failure
> HTTP Code: 403
> Body: 
[88655:259:0811/161730.436219:VERBOSE9:logging_util.cc(137)] 
[ RESPONSE HEADERS ]
> Url: https://api.qa6.aurora7.net/v1/payments/recipientIds
> Header content-length: 0
> Header date: Wed, 11 Aug 2021 20:17:30 GMT
> Header server: nginx
> Header vary: Origin
> Header www-authenticate: Bearer error="unverified_account", error_description="To access this endpoint, you need a fully verified account."
[88655:259:0811/161730.437647:INFO:gemini_authorization.cc(141)] Unverified User
```

4. brave://rewards page shows an error message that can be closed with the "Close" button

<img width="970" alt="Screen Shot 2021-08-11 at 4 17 34 PM" src="https://user-images.githubusercontent.com/28145373/129097546-dd6b189f-ccb1-44a8-b73b-5edfbbcdb5f2.png">

5. Confirmed UI shows "Verify wallet" messaging, no indication of wallet successful connection

Example | Example
----- | -----
<img width="485" alt="Screen Shot 2021-08-11 at 4 23 34 PM" src="https://user-images.githubusercontent.com/28145373/129098100-83aada11-feb0-46fc-a28e-f871f1be75ca.png"> | <img width="412" alt="Screen Shot 2021-08-11 at 4 24 03 PM" src="https://user-images.githubusercontent.com/28145373/129098105-b3de656e-bcdd-488c-969e-134d68164d50.png">

6. Checked linking status, confirmed not linked on server:

```
laurenwags@Laurens-MacBook-Pro ~ % curl "https://grant.rewards.bravesoftware.com/v3/wallet/c.......2" | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0    388      0 --:--:-- --:--:-- --:--:--   388
{
  "paymentId": "c........2",
  "walletProvider": {
    "id": "",
    "name": "brave"
  },
  "altcurrency": "BAT",
  "publicKey": "e30dc3fe645f953098c4ae8654d60d55b554a2a6ade7c052f78e95ea5d53ded2"
}
```

</details>
