### ISSUE TITLE
[Android] Implement new tipping banner (Phase 1)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17070]
## Description

The tipping banner on Android needs to be updated to be at parity with the tipping banner on desktop. This will be split into different phases. This issue is for Phase 1, which includes:

- [x] Fetching the default tip amount suggestions 
- [x] Custom tipping amount feature https://github.com/brave/brave-browser/issues/16021
- [x] Fetching the channel's custom description 
- [x] Fetching the channel's social links 
- [x] Overall styling

## Deferred to follow-up issues (later phases)

1. Multiple default backgrounds (not just the blue background)
2. Dedicated Monthly tip change amount UI (see figure 1 below)
4. Fetching actual cover photo set by the creator 
5. Confetti animation on success

------------
Figure 1:
<img src="https://user-images.githubusercontent.com/11497541/190442072-5ad1abac-0789-4283-ac75-9ecec2ab20a0.png" width=300px>
<img src="https://user-images.githubusercontent.com/11497541/190442118-e814fe1c-682f-42da-b79b-9b4165fd4049.png" width=300px>
------------

**Comment by aman-m1** [comment]
@deeppandya is sitting on (no offence) so many important updates. Like https://github.com/brave/brave-browser/issues/17408 and https://github.com/brave/brave-browser/issues/15618. I give you an icecream to chill and a rocket for speed.

**Comment by Miyayes** [comment]
https://github.com/brave/brave-browser/issues/16021 @deeppandya @sujitacharya2005
