### ISSUE TITLE
brave_stats: Change dtoi parameter to 30 days

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#17089]
Growth team requested this so retention data can be better understood.

**Comment by keur** [comment]
## Test Plan

Follow the same steps described in https://github.com/brave/brave-browser/issues/10061, but use 30 days instead of 14 days.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.29.70 x64 Beta build
- Verified test plan from https://github.com/brave/brave-browser/issues/10061
- Verified `dtoi` is set to null after 30 days
------------
Verification passed on Samsung Tab A  with Android 10 running 1.29.70 x64 Beta build
- Verified test plan from https://github.com/brave/brave-browser/issues/10061
- Verified `dtoi` is set to null after 30 days

![image](https://user-images.githubusercontent.com/17010094/130776042-e2b9278c-d801-4430-a120-e228730f75ec.png) | ![image](https://user-images.githubusercontent.com/17010094/130776286-45608b82-023a-4b5a-a5df-168ce5ba953b.png)
-- | --
