### ISSUE TITLE
Disable navigator.battery API 

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#171]
navigator.battery API can be used for tracking users. 

<img width="1435" alt="screen shot 2018-04-24 at 6 01 28 pm" src="https://user-images.githubusercontent.com/1903815/39221023-93aae5de-47e9-11e8-8558-1d323d602522.png">

**Comment by jumde** [comment]
Fixed: https://github.com/brave/brave-core/pull/114

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

test cases in brave/brave-core#114
