### ISSUE TITLE
Creating links to highlighted text

### ISSUE THREAD

**Issue by abdulsalam0** [brave/brave-browser#17101]
## Description 

when creating a link to highlighted text and trying to use the brave browser to open it. it will just direct me to the start of the page. instead of opening the page where the text is highlighted as well as the text is not highlighted. 

## Steps to Reproduce

   1.  Using chrome browser copy link to highlighted or Link to Text Fragment Extention to create a special link to the currently selected text on a page
   2.  Use the brave browser to open the link
   3.  the page will open with no highlighted text 

## Actual result:

the page loads with no highlighted text and directs you to the start of the page.

## Expected result:
the page should open with highlighted text and the page should scroll down to the level where the text is at.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)

## Version/Channel Information:

NA

- Can you reproduce this issue with the current release? 
- yes
- Can you reproduce this issue with the beta channel? 
- NA
- Can you reproduce this issue with the nightly channel? 
- NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- No

**Comment by AnkushMalaker** [comment]
From what I understand from the "closed/wontfix" label on this issue, this bug/issue will not see a fix in the near future. For people who stumble upon this issue and would like to disable it: 

1. Go to brave://flags
2. Search for "Copy Link To Text"
3. On the drop-down menu, select disabled.  

This should remove the option from the context menu.

**Comment by eligrey** [comment]
@rebron Could you provide some context as to why this issue was marked closed/wontfix?

**Comment by stopsopa** [comment]
This is important feature of chrome which a lot of people have used to use. Please consider to implement it.

**Comment by dragonis41** [comment]
@rebron Could you provide the reason to why this issue was marked as closed/wontfix ?

It's annoying to constantly have to search for basic feature that have been deactivated without reason in Brave.

**Comment by thienguen** [comment]
I couldn't find this feature in the flag anymore, so I assume it was removed, really hope to have it back

**Comment by CamperSamu** [comment]
Makes no sense for this flag to be completely removed as it's an important feature for many users.
As it's said, "Here be dragons!" and never break the user's workflow.
