### ISSUE TITLE
`Additional settings` text distorted in few locales

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#17109]
## Description 

`Additional settings` text distorted in few locales

## Steps to Reproduce

   1. Clean profile 1.27.107 
   2. Set OS locale to `Germany`/`France`/ `Hindi` or any other locale apart from `English`
   3. Open brave://settings
   4. Verify the `Additional Settings` text

## Actual result:

`Additional settings` text distorted in few locales

`1.27.107` - `Germany`
![image](https://user-images.githubusercontent.com/38657976/126656661-60b8be7f-8dfb-4443-aaa6-226de1e0c3cd.png)

`France`
![image](https://user-images.githubusercontent.com/38657976/126658431-a0febb95-257b-4154-ac87-d4aa8a8b2119.png)

## Expected result:

`1.26.77`
![image](https://user-images.githubusercontent.com/38657976/126656529-9ea0c01f-cfb2-452c-b59e-894b14182eca.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.27.107 Chromium: 92.0.4515.107 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
Betriebssystem | Windows 10 OS Version 2004 (Build 19041.1110)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by kjozwiak** [comment]
Labelling this one as `QA/No` as this will be fixed/QA'd via a https://github.com/brave/brave-browser/issues/17461. As per process, the above issue has a PR associated with it which unfortunately didn't work. We usually try to make sure issues only have a single PR so things don't get confusing when there's multiple PRs for one issue.
