### ISSUE TITLE
Brave prompts about installing external extensions, like Chrome

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1710]
## Description 

Sometimes when you're installing Brave, you'll get a random notification that states that a new extension has been added. In my case (example below in the screenshot), I had Ace Streaming installed which is attempting to add an extension every single time I install Brave.

@LaurenWags ran into the same issue before with `LastPass` but she did have it installed. We assumed that the native application was attempting to install the extension.

However, @bsclifton mentioned that he had the same issue occur but he never installed `LastPass`.

We need to figure out why `LastPass` is installed randomly sometimes and we should be blocking native applications from attempting to install extensions.

## Steps to Reproduce

I don't have 100% STR but I think this is happening when a native application attempts to install an extension in a new browser. However in @bsclifton case, he mentioned he didn't have `LastPass` installed but still received the notification.

## Actual result:

![winextensions](https://user-images.githubusercontent.com/2602313/47171911-00069380-d2d8-11e8-98f3-488a0b8bb86c.PNG)

<img width="521" alt="screen shot 2018-10-18 at 10 13 22 am" src="https://user-images.githubusercontent.com/2602313/47171919-072da180-d2d8-11e8-8d82-fcf33bf0ab71.png">

## Expected result:

* We shouldn't be installing random extensions on first launch (@bsclifton case)
* We should be blocking native applications from trying to install extensions on b-c

## Reproduces how often: 

* 100% reproducible once you have a native application that attempts to install an extension

## Brave version (brave://version info)

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, reproduced it on `dev` and `beta` (with Ace Streaming)

- Does it reproduce on browser-laptop? 

N/A

### Additional Information

CCing @bsclifton

**Comment by bsclifton** [comment]
Here is more information about the issue I'm running into

With both the Beta and Release channels, I'm getting prompted about installing LastPass via the hamburger menu:
<img width="521" alt="screen shot 2018-10-18 at 10 13 22 am" src="https://user-images.githubusercontent.com/4733304/47172914-8bc0f580-d2c1-11e8-98f2-7354945f4c69.png">

When the above is clicked, it shows this:
<img width="481" alt="screen shot 2018-10-18 at 10 35 48 am" src="https://user-images.githubusercontent.com/4733304/47172977-adba7800-d2c1-11e8-9f3f-22d73831be4e.png">

I don't recall ever using LastPass and if they have binaries available, I've never installed them (in fact, I'm on a new machine). This happens to me consistently with a new profile (ex: delete `~Library/Application Support/BraveSoftware/Brave-Browser/` and start Brave again).

When launching a fresh instance of Google Chrome, it oddly enough has the same behavior:
<img width="514" alt="screen shot 2018-10-18 at 10 39 35 am" src="https://user-images.githubusercontent.com/4733304/47173169-39340900-d2c2-11e8-8ae5-8966f5dab28d.png">

**Comment by bsclifton** [comment]
Update on the above- I went through several removal guides (such as https://nektony.com/how-to/uninstall-lastpass-on-mac) and I did find a folder here: `~/Library/Containers/com.lastpass.LastPass`. I deleted this and it doesn't seem to make a difference; new Chrome and Brave installs still prompt to install this extension

**Comment by bsclifton** [comment]
I found and deleted a lot more items, but no change (even after emptying trash and restarting). I'm really curious what type of detection is being done by the code?

I've basically ran the following and nothing is coming back:
```
cd /
sudo find . | grep "lastpass"
```

**Comment by onmyouji** [comment]
I had the same problem with Ace Script, I thought I was infected by malware and my Brave browser was getting hijacked.

Managed to remove it by searching for mjbepbhonbojpoaenhckjocchgfiaofo (the extension ID on web store) entry on my Windows registry and deleting them all.

**Comment by tomlowenthal** [comment]
So, technically this isn't a security/privacy issue. But I'd like us to treat it like it is because it definitely *feels* like an invasion or loss of control when this happens, and that really is not a good look for trust/confidence.

**Comment by bsclifton** [comment]
Props to @petemill for finding the details on this 😄 
Chrome/Chromium/Brave was checking the JSON files here (path on macOS):
`/Library/Application Support/Google/Chrome/External Extensions/`

(where it found the LastPass JSON file)

This behavior is expected per the docs:
https://developer.chrome.com/extensions/external_extensions

@rebron @davidtemkin @bbondy would you be OK closing this issue as `wontfix`?

**Comment by kjozwiak** [comment]
Going through https://developer.chrome.com/extensions/external_extensions, it seems like on Win, you'll need to remove the extension from the following registry location:

* `HKEY_CURRENT_USER\Software\Google\Chrome\Extensions\`

For Ace Stream, removing the following will resolve above issue that I mentioned above:
* `HKEY_CURRENT_USER\Software\Google\Chrome\Extensions\mjbepbhonbojpoaenhckjocchgfiaofo`

**Comment by bbondy** [comment]
I'll step back from this decision and leave it to product and security teams.

**Comment by diracdeltas** [comment]
fine with closing as wontfix
