### ISSUE TITLE
Fix up Speedreader ToggleButton UI styling

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#17113]
Speedreader uses the default button from Chromium views. The dimensions are hardcoded to be 24x12, and the thumb is is larger than the track. We need to add methods to `views::ToggleButton()` to make it more configurable. The dimensions in figma are 48x24, and the thumb should be inset 2 pixels inwards.

**Comment by keur** [comment]
Upstream PR https://chromium-review.googlesource.com/c/chromium/src/+/3045178

**Comment by rebron** [comment]
Closing as stale.
