### ISSUE TITLE
When user is unverified, do not say "Your Brave Wallet is powered by Uphold"

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17115]
## Description

When the user is **unverified**, do **not** show this:

![image](https://user-images.githubusercontent.com/11497541/126692933-cdf34c4d-dec8-46ad-ae1b-dbc2fde938fd.png)

Instead, we can remove the text entirely. 

The text is no longer true ever since we moved away from legacy Uphold anon cards, and is no longer applicable as a default fallback value with non-Uphold options available.

cc: @lukemulks

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.29.67 Chromium: 92.0.4515.159 (Official Build) beta (x86_64)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:
1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3. clicked on the BAT icon in the URL bar and clicked `Start using Rewards`
4. on `brave://rewards`, clicked on `Verify Wallet`
5. logged in to Uphold on staging
6. confirmed UI for verified wallet
7. logged out
8. confirmed UI for disconnected/non-verified wallet

Unlinked/unverified | Linked/verified | Disconnected after linked/verified
--------------------|----------------|----------------------------------
<img width="1312" alt="Screen Shot 2021-08-23 at 1 17 04 PM" src="https://user-images.githubusercontent.com/387249/130515985-2f3266c9-f165-41b5-a8e8-0e597e6a0f4c.png"> | <img width="1312" alt="Screen Shot 2021-08-23 at 1 17 31 PM" src="https://user-images.githubusercontent.com/387249/130515996-1befe0a5-2114-4d62-adb0-e882443f8d06.png"> | <img width="1312" alt="Screen Shot 2021-08-23 at 1 17 43 PM" src="https://user-images.githubusercontent.com/387249/130515999-06d0da45-1519-4732-9a26-6b7f38fe3f5c.png">
