### ISSUE TITLE
Add "Do not disturb" (DND) or snooze option for custom Brave Ads notifications

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17110]
## Description

Unlike native OS notifications, Brave Ads's custom ad notifications cannot easily detect and respect OS-level DND/snooze settings. However, such user settings should be respected.

## Solution

Implement our own DND option that snoozes Brave Ads's custom ad notifications.

**Comment by stephendonner** [comment]
Thanks for filing this, @Miyayes - this would also be great for the "don't want custom ad notifications during Brave Talk" calls use-case.

**Comment by bkardell** [comment]
+1 to this, please.
