### ISSUE TITLE
Updating to chromium 92

### ISSUE THREAD

**Issue by Area51Kacz** [brave/brave-browser#17121]
Could we update Brave (Stable channel) to Chromium 92

**Comment by Tonev** [comment]
The upcoming update will upgrade Chromium to 92.0.4515.107. You can track team's progress in pushing the next release over here: https://github.com/brave/brave-browser/milestone/205.

**Comment by bsclifton** [comment]
Thanks for the assist @Tonev 😄 

We are shooting for a Stable channel release tomorrow! It'll be product version 1.27

You can try the latest release candidate we have here:
https://github.com/brave/brave-browser/releases/tag/v1.27.107

Thanks for your patience 😄
