### ISSUE TITLE
"Brave rewards" should be "Brave Rewards" in inline-tip popup

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17120]
## Description 

"Brave rewards" should be "Brave Rewards" in inline-tip popup

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `https://www.reddit.com/user/alex_the_brave`
   4. find and click on any inline `tip` button
   5. look at the resulting UI popup's spelling of `Brave Rewards`

## Actual result:

The heading reads `Tip with Brave rewards` (highlighted in the screenshot below)

<img width="1312" alt="Screen Shot 2021-07-22 at 2 52 54 PM" src="https://user-images.githubusercontent.com/387249/126714583-7aa24529-4161-423f-88e3-79a596bf0d90.png">

## Expected result:

It should read `Tip with Brave Rewards`
## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.29.20 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 11.4 (Build 20F71)

**Comment by m4thieulavoie** [comment]
Since no one was assigned and it looked pretty straight forward I went ahead and opened a PR for this translation issue!

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.29.29 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 11.5 (Build 20G71)

Steps:

1. new profile
2. launch Brave
3. load `https://www.reddit.com/user/alex_the_brave`
4. find and click on any inline tip button
5. look at the resulting UI popup's spelling of Brave Rewards

Confirmed it now reads `Tip with Brave Rewards`.

<img width="1312" alt="Screen Shot 2021-07-26 at 3 27 32 PM" src="https://user-images.githubusercontent.com/387249/127067395-c39cb487-4492-4cb3-b433-15ccfcedf414.png">
