### ISSUE TITLE
Cosmetic filtering breaks hamburger menu on porntrex.com

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#17135]
## Description 
Something related to cosmetic filtering is breaking the hamburger menu on porntrex.com (NSFW). Note that the menu only appears when the window is sufficiently narrow (i.e. mobile layout).

Same issue does not occur on uBlock Origin, or with Brave Shields when the `#brave-adblock-cosmetic-filtering` flag is disabled in brave://flags.

## Steps to Reproduce

   1. Visit https://porntrex.com (NSFW)
   2. Resize the window to be narrower until the hamburger menu appears in the top right corner.
   3. Attempt to click on it

## Actual result:

Nothing happens

## Expected result:
Menu should open

## Reproduces how often: 

Always

## Desktop Brave version:

1.29.19 Nightly (Linux)

## Miscellaneous Information:

Tried a whole bunch of custom filters in brave://adblock with no luck. This will likely require some deeper debugging.

It likely has something to do with the `Uncaught ReferenceError: aawsmackeroo is not defined` error in the console, which does not appear with uBlock Origin.

**Comment by ShivanKaul** [comment]
@ryanbr is this still a problem?

**Comment by ryanbr** [comment]
Resized, and the hamburger showed, and was clickable. Closed

cc; @antonok-edm
