### ISSUE TITLE
Migrate keyring prefs of brave wallet to single dictionary pref

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#17137]
We currently have separate prefs like `kBraveWalletEncryptedMnemonic`, `kBraveWalletDefaultKeyringAccountNum`, `kBraveWalletBackupComplete`, `kBraveWalletLastUnlockTime`, `kBraveWalletAccountNames`...etc
And we should really have one dictionary pref like
```
{[keyringid]: 
  {  backup_complete: false, 
     encrypted_mnemonic: [mnemonic],
     // last_locked_time: [time]
     account_metas: {
        "m/44'/60'/0'/0/0": {
              account_name: "account 1",
              ...
         },
         "m/44'/60'/0'/0/1": {
              account_name: "account 2",
              ...
         }
      }
      ...
     }
    ...
}

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.30.79 Chromium: 93.0.4577.82 (Official Build) beta (64-bit)
-- | --
Revision | `e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}`
OS | Windows 11 Pro Insider Preview OS Version 2009 (Build 22458.1000)

- Verified test plan form [brave/brave-core#9674](https://github.com/brave/brave-core/pull/9674)
- Verified creating a new wallet account and adding different accounts with unique names are retained across browser launch
- Verified restoring from a seed and adding new accounts with unique names are retained across browser launch
---------
Verification passed on

Brave | 1.30.79 Chromium: 93.0.4577.82 (Official Build) beta (64-bit)
-- | --
Revision | `e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}`
OS | Linux

- Verified test plan form [brave/brave-core#9674](https://github.com/brave/brave-core/pull/9674)
- Verified creating a new wallet account and adding different accounts with unique names are retained across browser launch
- Verified restoring from a seed and adding new accounts with unique names are retained across browser launch
----------
Verification passed on

Brave | 1.30.79 Chromium: 93.0.4577.82 (Official Build) beta (x86_64)
-- | --
Revision | `e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}`
OS | macOS Version 11.5.2 (Build 20G95)

- Verified test plan form [brave/brave-core#9674](https://github.com/brave/brave-core/pull/9674)
- Verified creating a new wallet account and adding different accounts with unique names are retained across browser launch
- Verified restoring from a seed and adding new accounts with unique names are retained across browser launch
