### ISSUE TITLE
Update 1.27.108 causes breakage in dark mode

### ISSUE THREAD

**Issue by youssef20031** [brave/brave-browser#17139]
## Description 

After the update error screens show up as white despite me using dark mode in brave

## Steps to Reproduce

   1. Update
   2. Simulate an error screen like no internet

## Actual result:

![Screenshot from 2021-07-23 20-00-17](https://user-images.githubusercontent.com/43968405/126823010-7d6d8747-5be9-4011-911e-f34120fe287e.png)

## Expected result:
the same picture but with dark mode

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Ubuntu 20.04.2.0 LTS
JavaScript | V8 9.2.230.20
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel? 
- N/A
- Can you reproduce this issue with the nightly channel? 
- N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Yes, Fingerprinting protection is affecting local page
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- N/A

**Comment by supernes** [comment]
It's not just error screens, every website that uses media queries to detect dark mode is [intentionally broken as of the last update with max fingerprinting protection enabled](https://github.com/brave/brave-browser/issues/15265).
I hate this change, I thinks it's unreasonable to force users to choose between protection and their preferred aesthetics.

Please add a flag or some other way for users to change/disable this behavior.

**Comment by Tonev** [comment]
I confirm the update broke websites' functionality to change their theme based on users' theme preferences.

Steps to reproduce:

1. Go to `brave://settings/appearance` and set `Brave colors` to `Dark`.
2. Open https://9gag.com/.
3. Click on the Brave Shields icon in the address bar and set `Fingerprinting blocked (strict, may break sites)`.

Website's theme will reset to light. Clicking on the Brave Shields icon in the address bar and setting `Fingerprinting blocked (standard)` will once again change the website's theme to dark, successfully enforcing a theme based on user's preferences.

CC: @ShivanKaul as an author of the changes, and @pes10k as someone who can provide the best approach in such cases :+1:

**Comment by WormChickenWizard** [comment]
Also experiencing this issue. Changing fingerprint protection from strict to either standard or allowed seems to remedy the problem.
<html>
<body>


Brave | 1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2009 (Build 19043.1110)
JavaScript | V8 9.2.230.20
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36


</body>
</html>

**Comment by ShivanKaul** [comment]
The dark mode detection block checks for shields up and fingerprinting mode strict. I see that on error pages (no wifi, DNS lookup failed) we still have Shields up. Will check with @pes10k about the right thing to do here.

**Comment by shimizacken** [comment]
Last Brave update (`1.27.108 Chromium: 92.0.4515.107` on MacOs Big Sure `11.4`), causes **all**  websites/error pages/settings page etc. to be shown with a **dark theme**, like if [dark reader extension was applied](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh). For my tests it happens regardless if:
- Mac theme settings in light/dark mode
- Brave theme settings in light/dark mode
- Brave open in `Private`/`Guest` or as a fresh user modes.
- `Fingerprinting` mode
- Shields enabled/disabled
- Website have or not have [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by ShivanKaul** [comment]
I added a feature flag in https://github.com/brave/brave-core/pull/9735 that allows opting-out of this fingerprinting protection

**Comment by stephendonner** [comment]
@ShivanKaul mind adding a succinct test plan for this?  Thanks!

**Comment by stephendonner** [comment]
**Verified `PASSED`** using 


Brave | 1.30.45 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 11.5.2 (Build 20G95)

### Steps:
1. clean profile
2. launched Brave
3. reproduced the issue in https://github.com/brave/brave-browser/issues/17139#issuecomment-886019704 by toggling between `strict, may break site` and `standard` modes for `fingerprinting blocking` with the `Default` (`Enabled`) value for `Enable dark mode blocking fingerprinting protection` in `brave://flags`
4. next,  set `Enable dark mode blocking fingerprinting protection` to `Disabled` in `brave://flags` and restarted
5. repeated the steps in https://github.com/brave/brave-browser/issues/17139#issuecomment-886019704 but confirmed I was able to toggle between `strict, may break site` and `standard` modes for `fingerprinting blocking` without changing the site's background color

## `Default` (`Enabled`)
example | example | example
---------|----------|---------
<img width="1333" alt="Screen Shot 2021-08-24 at 3 48 39 PM" src="https://user-images.githubusercontent.com/387249/130701377-63701dfe-55e7-430f-85d1-5f25a16a5c96.png"> | <img width="1333" alt="Screen Shot 2021-08-24 at 3 48 25 PM" src="https://user-images.githubusercontent.com/387249/130701091-d73b42a5-a99b-41ce-b04a-418e3ea3a6ea.png"> | <img width="1333" alt="Screen Shot 2021-08-24 at 3 48 32 PM" src="https://user-images.githubusercontent.com/387249/130701094-bae17bba-487a-443c-867f-e5e08131987e.png">

## `Disabled`
example | example | example
---------|----------|---------
<img width="1067" alt="Screen Shot 2021-08-24 at 3 42 37 PM" src="https://user-images.githubusercontent.com/387249/130701401-f07c8b9e-87bc-494c-8c0e-4d30e13f4729.png"> | <img width="1333" alt="Screen Shot 2021-08-24 at 3 49 48 PM" src="https://user-images.githubusercontent.com/387249/130701273-3d31316e-f529-4da3-8189-e10da78815f3.png"> | <img width="1333" alt="Screen Shot 2021-08-24 at 3 49 53 PM" src="https://user-images.githubusercontent.com/387249/130701275-06cb019f-9dd5-4791-969b-790045e26c5c.png">
