### ISSUE TITLE
Add administrative functions for use in corporations and schools.

### ISSUE THREAD

**Issue by Marcdnd** [brave/brave-browser#17131]
## Description 

Add administrative functions for use in corporations and schools so owners have a new source of income.
Many educational institutions use laboratories with extensive use of computers and internet access, with this functionality an institution could use Brave Browser as a source of extra income, this would mainly benefit institutions with humanitarian support in needy countries.

## Steps to Reproduce

1. Provide bulk installations with unique and secure admin user settings.
2. Secure wallet setup to prevent theft and reward changes.
3. When enabling a new profile, block the configuration of the wallet by the user.
4. Administrative control of the institution's use wallet.

## Actual result:

Currently, a user can configure a new wallet, in this type of installation this would be blocked for common users and only allowed by an admin user.

## Expected result:
Do not allow the regular user to change wallet settings.

## Reproduces how often: 

Ever

## Brave version (all)

All versions.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

This feature could be implemented as an extension.

**Comment by rebron** [comment]
Closing. Thanks for the suggestion @Marcdnd
