### ISSUE TITLE
Add UI messaging/design that tells users they have 90 days to claim ad earnings and solve CAPTCHA

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17133]
## Description

Unverified users have to go through a claim + CAPTCHA process in order to claim their ad earnings every month. These `claim ad earnings` buttons last for 90 days. After 90 days, they are no longer valid, and the virtual-BAT can no longer be claimed.

However, the interface does not sufficiently alert the user to this fact.

## Solution

Add some kind of design or UI messaging that makes it more apparent that the user only has 90 days to claim their ad earnings.

cc: @codybanxs @jsecretan @bradleyrichter

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.37.87 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/11957

**_Clean profile_**

- Confirmed Ad grant available to claim UI is shown in the rewards settings page, NTP widget
- Confirmed number of days to claim is the same `You have 91 days left to claim` in all the places (settings page, NTP widget)
- 
Rewards settings page | NTP widget
-----|-------
![image](https://user-images.githubusercontent.com/38657976/157834920-a05aea40-1eb4-40a5-a24c-9ccb2ad8413a.png) | ![image](https://user-images.githubusercontent.com/38657976/157834974-90f33825-2c79-42c6-922f-0c6186d64548.png)



**_Upgrade profile_**

**Comment by btlechowski** [comment]
Verification PASSED on

```

Brave | 1.37.87 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/11957

**_Clean profile_**

- Confirmed Ad grant available to claim UI is shown in the rewards settings page, NTP widget and BR panel
- Confirmed number of days to claim is the same `You have 91 days left to claim` in all the places (settings page, NTP widget and BR panel)
- Set the system ahead by 1 day and the confirmed number of days to claim grants is decreased each day

Rewards settings page | NTP widget | BR panel
-----|-------|----
![image](https://user-images.githubusercontent.com/34715963/160216871-c11de79f-49e9-4e3f-9886-95410b1cc081.png)|![image](https://user-images.githubusercontent.com/34715963/160216947-502b7ba7-e85c-4b1b-85cf-fecbe5405ebc.png)|![image](https://user-images.githubusercontent.com/34715963/160216906-387338b6-eaab-471c-af13-78ac94fa41ee.png)



1 day - Rewards settings page | 1 day - NTP widget 
-----|-----
![image](https://user-images.githubusercontent.com/34715963/160217103-0eeabe72-6edc-4782-9e2f-d7112355ae08.png)|![image](https://user-images.githubusercontent.com/34715963/160217112-967c7c90-0c4e-43ed-96eb-acb369d72a28.png)



**_Upgrade profile_**

**Before upgrade**

1.36.x - Rewards settings page | 1.36.x - NTP widget | 1.36.x - BR panel
-----|-------|------
![image](https://user-images.githubusercontent.com/34715963/160217333-22e3766a-9777-493b-9175-cda30a436312.png)|![image](https://user-images.githubusercontent.com/34715963/160217341-e1ca8069-e4f8-4039-9e8f-fe1a6909c589.png)|![image](https://user-images.githubusercontent.com/34715963/160217354-f7f54eba-e533-44c7-b200-77f72a99cc42.png)


**New UI after upgrade**

- BR panel is showing up the old UI, encountered https://github.com/brave/brave-browser/issues/21604
- Set the system ahead by 1 day (12th March) and the confirmed number of days to claim grants is decreased each day
- Set the system ahead by 1 week (20th March) and the confirmed number of days to claim grants is decreased each day

1.37.x - Rewards settings page | 1.37.x - NTP widget | 1.37.x - BR panel
-----|-------|------
![image](https://user-images.githubusercontent.com/34715963/160217446-d29266c6-5480-4c09-95f4-f71ebe2c9a7e.png)|![image](https://user-images.githubusercontent.com/34715963/160217456-e8f6ac3d-372c-43e1-b0cd-4034669cdcd2.png)|![image](https://user-images.githubusercontent.com/34715963/160217440-c65918b5-a09a-412d-a14b-c9042298d4fd.png)


1day - Rewards settings page | 1day - NTP widget 
-----|-------
![image](https://user-images.githubusercontent.com/34715963/160217514-07d02d9f-36e1-463e-a24c-749529f8c24b.png)|![image](https://user-images.githubusercontent.com/34715963/160217536-a8780aa4-73a5-461a-b28e-56a5bf818c68.png)

**Comment by stephendonner** [comment]
Verification PASSED on



Brave | 1.37.107 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)



- Verified the test plan from https://github.com/brave/brave-core/pull/11957

**_Clean profile_**

- Confirmed Ad grant available to claim UI is shown in the rewards settings page, NTP widget and BR panel
- Confirmed number of days to claim is the same `You have 91 days left to claim` in all the places (settings page, NTP widget and BR panel)
- Set the system ahead by 1 day and the confirmed number of days to claim grants is decreased each day

Rewards settings page | NTP widget | BR panel
-----|-------|----
<img width="1312" alt="Screen Shot 2022-03-28 at 10 08 38 AM" src="https://user-images.githubusercontent.com/387249/160456422-bf9bc54f-a695-4a04-9fea-2174c3e92f10.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 10 04 55 AM" src="https://user-images.githubusercontent.com/387249/160456383-78da0afc-0637-4bb7-a050-b9019348cf52.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 10 08 24 AM" src="https://user-images.githubusercontent.com/387249/160456409-84592b8b-2864-451a-a44d-7f317579afb7.png"> | 




1 day - Rewards settings page | 1 day - NTP widget 
-----|-----
<img width="1312" alt="Screen Shot 2022-03-29 at 10 35 03 AM" src="https://user-images.githubusercontent.com/387249/160456626-b15b7dd7-3038-4b4e-92a4-6f7a6b7e4c41.png"> | <img width="1312" alt="Screen Shot 2022-03-29 at 10 35 12 AM" src="https://user-images.githubusercontent.com/387249/160456634-7869b72e-5fed-486c-b9d3-c733a03e0f50.png"> | <img width="1312" alt="Screen Shot 2022-03-29 at 10 35 16 AM" src="https://user-images.githubusercontent.com/387249/160456645-544b3f6b-c8f3-40fa-85d7-1508c30d4239.png">




**_Upgrade profile_**

**Before upgrade**

1.36.x - Rewards settings page | 1.36.x - NTP widget | 1.36.x - BR panel
-----|-------|------
<img width="1312" alt="Screen Shot 2022-03-28 at 10 28 31 AM" src="https://user-images.githubusercontent.com/387249/160455777-d6b39b2f-88e4-4177-8d6f-fd99d17d22da.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 10 28 35 AM" src="https://user-images.githubusercontent.com/387249/160455785-5a823dfa-42aa-458b-928a-20033d55ccdb.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 10 28 46 AM" src="https://user-images.githubusercontent.com/387249/160455792-ca92f77c-a430-47cf-b154-dd01bf0e40ae.png">


**New UI after upgrade**

- BR panel is showing up the old UI, encountered https://github.com/brave/brave-browser/issues/21604
- Set the system ahead by 1 day (29th March) and the confirmed number of days to claim grants is decreased each day
- Set the system ahead by 1 week (4th April) and the confirmed number of days to claim grants is decreased each day

1.37.x - Rewards settings page | 1.37.x - NTP widget | 1.37.x - BR panel
-----|-------|------
<img width="1312" alt="Screen Shot 2022-03-28 at 10 32 03 AM" src="https://user-images.githubusercontent.com/387249/160456005-8756a785-5861-4d84-99ec-8eec5a98fec9.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 10 32 07 AM" src="https://user-images.githubusercontent.com/387249/160456007-303dabe2-9d19-414c-9671-b5c8b6d480fd.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 10 31 58 AM" src="https://user-images.githubusercontent.com/387249/160455979-9784cc41-0386-487a-9416-72c8e5b889fc.png">



1day - Rewards settings page | 1day - NTP widget | 1day - BR panel
-----|-------|---------
<img width="1312" alt="Screen Shot 2022-03-29 at 10 32 58 AM" src="https://user-images.githubusercontent.com/387249/160456164-9f455ae8-f9d7-42bd-ad79-d275ea444bb1.png"> | <img width="1312" alt="Screen Shot 2022-03-29 at 10 33 04 AM" src="https://user-images.githubusercontent.com/387249/160456173-9a8fc740-1203-4fe0-af89-59bc350e37cb.png"> | <img width="1312" alt="Screen Shot 2022-03-29 at 10 33 08 AM" src="https://user-images.githubusercontent.com/387249/160456190-3235e482-3050-4d0b-828a-d6ab32a2251d.png">
