### ISSUE TITLE
Missing BATs

### ISSUE THREAD

**Issue by jmzsa7789** [brave/brave-browser#17149]
Good Night, 
 It is a pleasure, the reason of this email is because of I had 4.3 BATs and suddenly I had 2 BATs and I checked my wallet and there's not any payment. 
Could you inform me what is happening?
Thanks in advance.
The Mail I have registered is inversionesjml96@gmail.com this is my business account.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by hollons** [comment]
Thanks @jmzsa7789 for reporting. I can help to troubleshoot. Can you email your devices Wallet ID (which can be found here - brave://rewards-internals/) to Steven@brave.com. Thank you!

**Comment by jmzsa7789** [comment]
My wallet is :
16af5795-2c6d-4065-a4b8-dc4ff86f46ae

**Comment by jmzsa7789** [comment]
The email related to my Uphold account is ***@***.***

**Comment by tmancey** [comment]
Closing issue as will be resolved by https://github.com/brave/brave-browser/issues/17149#issuecomment-886735783
