### ISSUE TITLE
When shield is up videos not playing on espn.com/watch

### ISSUE THREAD

**Issue by vishnusudheendran** [brave/brave-browser#17148]
## Description 
When shield is on, videos not playing on espn.com/watch. When I turn off the shield I am able to play the live matches.

## Steps to Reproduce

   1. Log in with ESPN+ account on espn.com/watch
   2. Play any of the live videos.
   3. Getting "We are unable to play this video at the moment. Please try again later." error

## Actual result:
![image](https://user-images.githubusercontent.com/4574615/126880111-48a96877-8ce8-4701-8628-e318b0060086.png)

## Expected result:
The live videos should play without any error when shield is on.

## Reproduces how often: 

100% of the time on both Linux and Windows 10 with shields on.

## Brave version (brave://version info)

Brave | 1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel? - Haven't tried.
- Can you reproduce this issue with the nightly channel? - Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - Yes
- Does the issue resolve itself when disabling Brave Rewards? - No
- Is the issue reproducible on the latest version of Chrome? - No

**Comment by ryanbr** [comment]
@vishnusudheendran  Hey is this working in the latest Brave builds? (haven't got a ESPN+ account)
