### ISSUE TITLE
"Start video call" button in card should link to talk.brave.com/widget

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17146]
## Description 

`Start video call` button in card should link to talk.brave.com/widget

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load a new-tab page
   4. click on `Edit cards`
   5. add the `Brave Together` (to be renamed to `Brave Talk`) card
   6. open the `Network` panel in `Developer Tools` 
   7. click on the `Start video call` button
   8. look at the URLs/redirects

## Actual result:

button | URL
-------|------
<img width="306" alt="Screen Shot 2021-07-24 at 11 34 20 AM" src="https://user-images.githubusercontent.com/387249/126878798-78f95ec7-a04b-4d76-8a53-0e5e8208cbfa.png"> | <img width="1710" alt="Screen Shot 2021-07-24 at 11 35 07 AM" src="https://user-images.githubusercontent.com/387249/126878800-da9852cd-baf6-4c43-b7d1-cdcab73f337a.png">

## Expected result:
Should go to `talk.brave.com/widget` without any loads to/redirects from `together.brave.com`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.29.20 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 12.0 (Build 21A5284e)

cc @mattmcalister @rebron @bsclifton

**Comment by stephendonner** [comment]
@bsclifton think we can get an uplift going for `1.28.x`?  /cc @mattmcalister

**Comment by bsclifton** [comment]
@stephendonner done - https://github.com/brave/brave-core/pull/9608

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` until we get Brave Talk enabled on `main` (staging) via Griffin. After it's enabled on staging, QA will be able to run through the above verification. Once we get closer to Brave Talk release date, we'll push the same change into `production`.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-variations/pull/93 was merged into `main` (Griffin staging).

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

```
- Verified the STR from the description 
- Confirmed click on `Start video call` in NTP widgets redirects to `https://talk.brave.com/widget`
- Confirmed click on `Start video call` in `https://talk.brave.com/widget` initiates the call successfully

![image](https://user-images.githubusercontent.com/38657976/128842923-7dc63b57-ad90-41e7-9d6b-08f365709b32.png) | ![image](https://user-images.githubusercontent.com/38657976/128843122-cb1f6fb2-6e95-4f55-b32a-a2ced212a5a1.png)
---|---
