### ISSUE TITLE
"Try it out" should link to talk.brave.com/widget on promo tooltip

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17147]
## Description 

"Try it out" should link to talk.brave.com/widget on promo tooltip

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open a new-tab page
   4. on the bottom right, click on the `Try it out` button
   5. see where it links to

## Actual result:

Goes to `https://together.brave.com/widget`.

<img width="1312" alt="Screen Shot 2021-07-24 at 12 19 52 PM" src="https://user-images.githubusercontent.com/387249/126879246-90a81ab3-f9b3-4d7b-bb2a-6f7d278ddaea.png">

## Expected result:

Should go to `https://talk.brave.com/widget`.

## Reproduces how often: 

100%

## Brave version (info found on brave://version)

Brave | 1.29.20 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 12.0 (Build 21A5284e)

**Comment by stephendonner** [comment]
@bsclifton mind getting an uplift going for `1.28.x`?  /cc @mattmcalister

**Comment by bsclifton** [comment]
@stephendonner done - https://github.com/brave/brave-core/pull/9608

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` until we get Brave Talk enabled on `main` (staging) via Griffin. After it's enabled on staging, QA will be able to run through the above verification. Once we get closer to Brave Talk release date, we'll push the same change into `production`.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-variations/pull/93 was merged into `main` (Griffin staging).

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

```
- Verified the STR from the description
- Confirmed that click on `Try it now` redirects to `https://talk.brave.com/widget`

![image](https://user-images.githubusercontent.com/38657976/128833944-1c92f6fd-799f-4176-a3e3-b7f89d12bed9.png) | ![image](https://user-images.githubusercontent.com/38657976/128834027-59d6882a-50d6-4f66-9de0-62bf9954c65e.png)
----|---
