### ISSUE TITLE
Settings title should say Wallet and not Crypto Wallets

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#17140]
<img width="1451" alt="Screen Shot 2021-07-23 at 1 07 33 PM" src="https://user-images.githubusercontent.com/831718/126824944-d03c1fa2-7bd4-488a-9380-bb1f0078b1af.png">

**Comment by adithyaakrishna** [comment]
@bbondy Can I work on this?
Ig this is on https://github.com/brave/brave-core/blob/master/components/resources/brave_components_strings.grd File right?
Please do let me know if its the right one 👀

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.31.59 Chromium: 94.0.4606.54 (Official Build) beta (x86_64)
-- | --
Revision | `c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}`
OS | macOS Version 11.5.2 (Build 20G95)

- Verified settings title says Wallet
- Verified tooltip also shows as Wallet
![image](https://user-images.githubusercontent.com/17010094/134661437-4cb22c91-bd75-4ac9-96d9-bf0e5483b124.png)

-------
Verification passed on 

Brave | 1.31.55 Chromium: 94.0.4606.50 (Official Build) beta (64-bit)
-- | --
Revision | `0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}`
OS | Windows 11 Version Dev (Build 22458.1000)

- Verified settings title says Wallet
- Verified tooltip also shows as Wallet

![image](https://user-images.githubusercontent.com/17010094/134663331-447c90a6-6b9c-4a6c-8426-ffe31bd490c4.png)

-------
Verification passed on 

Brave | 1.31.59 Chromium: 94.0.4606.54 (Official Build) beta (64-bit)
-- | --
Revision | `c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}`
OS | Linux

- Verified settings title says Wallet
- Verified tooltip also shows as Wallet

![Screenshot from 2021-09-24 02-47-54](https://user-images.githubusercontent.com/17010094/134662799-829aaff0-180c-4712-b346-b9b36c06c6d9.png)

**Comment by adithyaakrishna** [comment]
🎉
