### ISSUE TITLE
[Feature request] Add Passwords to menu

### ISSUE THREAD

**Issue by francoism90** [brave/brave-browser#17144]
## Description 
This would be really useful and replaces the steps needed to show saved passwords.

Nowadays Brave/Chromium also offers password generation, it would especially useful if you need to search for site credentials.

## Steps to Reproduce

   1.  Open Settings
   2.  Search for Passwords
   3. Open Passwords

## Actual result:
Having Passwords listed in the main menu and mobile app.

## Expected result:
Having Passwords listed as option in the hamburger menu.

## Desktop Brave version:

1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)

## Android Device details:
   - Install type (ARM, x86): ARM, x86
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11.0

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by francoism90** [comment]
I would like to reopen this, it would be great addition.

**Comment by kjozwiak** [comment]
@francoism90 going to close this one off as it's from `2022`. I know we're trying to reduce the amount of features we're adding within the main hamburger menu as it's already pretty congested. Please feel free to create a new issue. CCing product via @timchilds @anthonypkeane in case the above is in the plans.
