### ISSUE TITLE
Create pref for disabling stats ping

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17158]
@keur Android specific issue for feature implementation as #16583 is desktop

## Description

- [ ] Create a preference for disabling the stats ping

## Designs

- [ ] Add usage ping toggle
- [ ] Update text for P3A and Automatic crash reporting settings
- [ ] Move crash reporting, usage ping, and P3A toggles to be closer to each other

## Assets
TBA

cc: @karenkliu for Assets and Design, @SergeyZhukovsky @anthonypkeane to prioritize

**Comment by diracdeltas** [comment]
does this also need to be done on iOS?

**Comment by bsclifton** [comment]
@diracdeltas yes - I believe so. cc: @anthonypkeane

**Comment by samartnik** [comment]
![device-2021-08-05-103358](https://user-images.githubusercontent.com/30602739/128368287-f68c8832-f12e-487b-961b-868d7e006853.png)

**Comment by samartnik** [comment]
@keur do you know how QA may test it on Android? I was able to check it only using temporary logs.

**Comment by keur** [comment]
@samartnik Is it possible for them to setup wireshark or any other network analyzers on an Android or the emulator? That's how we check it on desktop

**Comment by srirambv** [comment]
@keur  can use Charles Proxy for this checking stats ping.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.30.82 x64 build
- Verified no usage ping is sent when the setting is disabled
- Verified enabling the setting and restarting the browser sends usage ping


First launch ping (setting enabled by default) | Disable setting after moving date by 1 day | Enable Setting and restart browser | Android setting 
-- | -- | -- | -- 
![img](https://user-images.githubusercontent.com/17010094/134346334-5f5a18a3-d61a-47d4-b844-0122c424a9db.png) | ![img](https://user-images.githubusercontent.com/17010094/134346357-7ff0e8c2-b3d0-464e-8cda-24aa3ea5e6d8.png) | ![img](https://user-images.githubusercontent.com/17010094/134346363-be2280af-439e-4b2d-b797-d69e52b74548.png) | ![image](https://user-images.githubusercontent.com/17010094/134346940-9df38e42-efd5-4312-ac55-4ec660ac3aa9.png)
