### ISSUE TITLE
"Clear cookies and site data when you quit Brave" reverted to original Chromium name

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#17153]
## Description 

It looks like the latest Chromium upgrade reverted the name of the feature to its original Chromium name:
`Clear cookies and site data when you quit Brave` -> `Clear cookies and site data when you close all windows`.

The feature is found at `brave://settings/cookies`.

## Steps to Reproduce

   1. Open Brave.
   2. Type `brave://settings/cookies` in the address bar.
   3. Check feature's name.

## Actual result:

Feature's name is `Clear cookies and site data when you close all windows` since the latest Chromium upgrade.

## Expected result:
Unless developers intentionally reverted feature's name, it should be `Clear cookies and site data when you quit Brave`.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

<html>
<body>

Brave | 1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 7 Service Pack 1 (Build 7601)
JavaScript | V8 9.2.230.20
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,LegacyTLSEnforced,SafetyTip,AutoupgradeMixedContent,WinrtGeolocationImplementation,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=NotificationTriggers,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApi,IdleDetection,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,EnableProfilePickerOnStartup,TextFragmentAnchor,AutofillServerCommunication,LiveCaption,InterestCohortFeaturePolicy,FledgeInterestGroups,WebOTP,PrivacySandboxSettings,FederatedLearningOfCohorts,SignedExchangeSubresourcePrefetch,EnablePasswordsAccountStorage,InterestCohortAPIOriginTrial,FirstPartySets,NetworkTimeServiceQuerying,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,TrustTokens,DirectSockets,LangClientHintHeader --flag-switches-begin --enable-features=WebUIDarkMode,LegacyTLSEnforced,SafetyTip,AutoupgradeMixedContent,WinrtGeolocationImplementation,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,EphemeralStorage --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | AdRewardsStudy:NextPaymentDayEphemeralStorageStudy:EnabledNativeCosmeticFilteringStudy:EnabledPermissionLifetimeReleaseStudy:Enabled

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

I believe the change happened here: https://github.com/brave/brave-core/commit/2195b1e195012f2f486a9b78a8590404b2584d70#diff-ea9438378234d255cac10399b4b40451179915ffb8b03fd41721d689e373f10eL41

**Comment by bsclifton** [comment]
cc: @brave/chromium-src-reviewers

**Comment by rebron** [comment]
Closing. The setting was removed in Chromium 121 see: brave://settings/cookies and had been redundant with our more accessible `Clear Browsing Data` dialog `on Exit` option that we added ourselves (not available with Chrome).
