### ISSUE TITLE
[Auto upgrade to https:// does not work]

### ISSUE THREAD

**Issue by aerocyber** [brave/brave-browser#17152]
## Steps to Reproduce

   1. When visiting [http://www.glyphrstudio.com/](http://www.glyphrstudio.com/) and some other sites, I found this issue.

## Actual result:

![Not Secure badge when visiting http:// site.](https://user-images.githubusercontent.com/86760749/126887138-7840e0e6-9da0-4773-a06c-9a3745b6353a.png)

## Expected result:
![Padlock sign indicating https://](https://user-images.githubusercontent.com/86760749/126887147-e9ae4699-d025-4446-b7ca-7a4d61813a50.png)

## Reproduces how often: 

No steps to reproduce; occurs on random sites.

## Desktop Brave version:

```
Brave: 1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)
Revision: 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS: Linux
```

## Android Device details:
   - Install type : x86
   - Device type : Phone
   - Android version: 5.1; 11

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by diracdeltas** [comment]
Brave only upgrades websites to HTTPS currently if they are on the HTTPS Everywhere list:  https://github.com/EFForg/https-everywhere

**Comment by aerocyber** [comment]
Thanks for answering.
So, should this issue be reported to HTTPS Everywhere instead of here?

**Comment by diracdeltas** [comment]
Yes, that would be best for now since we don't maintain our own upgrade list.

**Comment by aerocyber** [comment]
Thanks for the help!
