### ISSUE TITLE
Brave web3 + MetaMask extension not working

### ISSUE THREAD

**Issue by jcp3alex** [brave/brave-browser#17168]
Ever since the update to V1.27.108 MetaMask fails to connect to web3 websites on Brave browser. Up until today, I was able to get it working by uninstalling the addon and re-installing the addon, but today that doesn't work any longer. Sometimes I will get a Metamask pop-up, independent of the addon that I can sign in to, but it happens randomly. I have tried re-installing after I shut down my PC, but that doesn't work either,

**Comment by TravelinMax** [comment]
Same experience here. MetaMask shows a message about the window.web3 API being removed form the add-on but that's not the issue. I found more discussion on the issue here: https://community.brave.com/t/metamask-stop-working-with-brave-browser/269031/11

I hope this gets some priority because MetaMask can't connect to any web3 site right now as far as I can tell.

**Comment by Tonev** [comment]
A lot of complaints regarding MetaMask in Community.

In one of the threads, a user (Luckys) shared a workaround that worked for a few users.

> Hi managed to sort mine by going into Brave settings and turning off (Load crypto wallets on startup) then restarting browser hope this may help some of you.
> 
> it worked for some of us try it!

Community thread:
https://community.brave.com/t/metamask-stop-working-with-brave-browser/269031

**Comment by isim95** [comment]
Can confirm that this worked for me - thank you Tonev for the fix. Hopefully this solve will work for all others with this issue as well


> A lot of complaints regarding MetaMask in Community.
> 
> In one of the threads, a user (Luckys) shared a workaround that worked for a few users.
> 
> > Hi managed to sort mine by going into Brave settings and turning off (Load crypto wallets on startup) then restarting browser hope this may help some of you.
> > it worked for some of us try it!
> 
> Community thread:
> https://community.brave.com/t/metamask-stop-working-with-brave-browser/269031

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.31.67 Chromium: 94.0.4606.61 (Official Build) beta (x86_64)
-- | --
Revision | `418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}`
OS | macOS Version 11.5.2 (Build 20G95)

- Verified there is no option for `Load crypto wallet on startup` 
- Verified when MM is installed, default provider is set to MM with or without flag being enabled

![image](https://user-images.githubusercontent.com/17010094/135620861-d68ce35f-f71f-4dae-8532-6822dae92bd9.png) | ![image](https://user-images.githubusercontent.com/17010094/135620539-1ffd5f43-a97a-446e-8f99-97068446d75a.png)
-- | --

----------
Verification passed on 

Brave | 1.31.67 Chromium: 94.0.4606.61 (Official Build) beta (64-bit)
-- | --
Revision | `418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}`
OS | Windows 11 Version Dev (Build 22468.1000)

- Verified there is no option for `Load crypto wallet on startup` 
- Verified when MM is installed, default provider is set to MM with or without flag being enabled

![image](https://user-images.githubusercontent.com/17010094/135623327-cefde5a1-967a-4858-8c81-931b7bfc2bab.png) | ![image](https://user-images.githubusercontent.com/17010094/135623813-ddd8c4a9-0baf-47aa-9750-88fe3a7adbf6.png)
-- | --

----------
Verification passed on 

Brave | 1.31.67 Chromium: 94.0.4606.61 (Official Build) beta (64-bit)
-- | --
Revision | `418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}`
OS | Linux

- Verified there is no option for `Load crypto wallet on startup` 
- Verified when MM is installed, default provider is set to MM with or without flag being enabled

![image](https://user-images.githubusercontent.com/17010094/135624354-4336f3cd-27d9-4ec8-a2f8-ffbf393576df.png) | ![image](https://user-images.githubusercontent.com/17010094/135625292-d86154ee-4b34-4574-85f2-86f3722275d7.png)
-- | --

**Comment by Billyv1** [comment]
Greetings,
My MetaMask extension was working just fine in Brave Browser with web3 sites until I got hit with the new V1.31.87 (Oct 19, 2021) today. Now web3 sites are not working, I can't connect with MetaMask and log into my account on these sites, like Rarible.com using my MetaMask. MetaMask wallet is no longer an option, even though if I just log into MetaMask and it shows my wallet is connected to that site.  Also if I'm not logged into MetaMask and I select "Connect Wallet" on the web3 site, the "Crypto Wallet" login pops up instead of the MetaMask login pop up.

**Comment by srirambv** [comment]
@Billyv1  what is the default provider set to?

**Comment by srirambv** [comment]
@rjaym mind adding an example where it's failing or adding more detailed steps? I ran through MM on current nightly and it worked fine with a bunch of sites.

**Comment by afkjm** [comment]
> @rjaym mind adding an example where it's failing or adding more detailed steps? I ran through MM on current nightly and it worked fine with a bunch of sites.

I am unable to use your nightly channel.

**Comment by rjaym** [comment]
> @rjaym mind adding an example where it's failing or adding more detailed steps? I ran through MM on current nightly and it worked fine with a bunch of sites.

I am unable to use your nightly builds.

**Comment by rjaym** [comment]
> @rjaym mind adding an example where it's failing or adding more detailed steps? I ran through MM on current nightly and it worked fine with a bunch of sites.

Also, sorry there really are no detailed steps or special setup as far as I know, it's just Brave on Windows 10 and MM with the versions stated above, although I am using the Avalanche network and not Ethereum.

**Comment by srirambv** [comment]
Ok thanks for the update. I'll give it a try on Avalanche network. Any specific Defi sites that you are facing problems with?

**Comment by rjaym** [comment]
> Ok thanks for the update. I'll give it a try on Avalanche network. Any specific Defi sites that you are facing problems with?

All defi sites, they show connected in MM with a green status icon, but the site itself shows as disconnected to MM. Also yes I have tried changing the "Default cryptocurrency wallet" option many times (all options) but nothing has allowed the sites to understand that MM is installed and connected. All the defi sites prompt me to connect to a wallet as if MM is not installed.

**Comment by bbondy** [comment]
If you're changing between wallets you might want to clear cookies on the site in question

**Comment by andrewvink** [comment]
> 

Same here not working for me either - updated Brave too, but still doesn't connect.  Works on Chrome but not Brave

**MetaMask** - Version - 10.16.2
**Brave** - Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)]

**Comment by bbondy** [comment]
> Not working for me either - updated Brave too, but still doesn't connect. Works on Chrome but not Brave
> 
> **MetaMask** - Version - 10.16.2 **Brave** - Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)]

What is your "default wallet" set to in brave://settings/wallet ?
What happens when you try to connect? Does Brave Wallet come up or MetaMask?

**Comment by bbondy** [comment]
fwiw I've deeply investigated dozens of these types of reports and every time it ends up being that there are multiple wallet extensions installed that are competing for `window.ethereum` and causing problems with each other. The claims that it works in Chrome is because the same set of extensions aren't installed on Chrome.

I'm still willing to investigate further, but for the past couple years I believe every investigation has led to no real issue.

Setting your wallet to None in brave://settings/wallet will make it so Brave does not try to insert `window.ethereum` at all. 
Setting it to Brave Wallet (Prefer extensions) makes it so Brave does insert `window.ethereum` but allows it to be overwritten.

**Comment by andrewvink** [comment]
@bbondy thanks for the reply! 

Checking my "default wallet" was the first thing I did - it is set as 'NONE' - but still having the issue.

Cleared all cache, cookies, site data, hosted app data in Brave ( Clear Browsing Data - All Time )

When going to Pancake Swap ( https://pancakeswap.finance/ ) for example the site loads - as soon as I click "connect wallet", the screen goes black and inspecting I can see a number of errors in the console.

The one that sticks out the most based on your other 2nd comment was:
MetaMask: 'ethereum.send(...)' is deprecated and may be removed in the future. Please use 'ethereum.sendAsync(...)' or 'ethereum.request(...)' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193

Pancake Swap - Screenshot:
https://i.imgur.com/ny8yNvX.png

On a separate DAPP similar thing happens - click on 'Connect Wallet' - screen turns black, this time if I inspect no ethereum error
https://i.imgur.com/LQhrnku.png

Thanks for reading! 🙏🏼

**Comment by rjaym** [comment]
An update, I ended up uninstalling the MM extension and reinstalling and now it is working again after I importing my old wallet using the 12 word recovery phrase. 
This implies some LocalStorage or cached data from the extension itself was causing an issue. Unfortunately, the workaround can be quite cumbersome.
I am still not sure where the blame should lie though to be honest, MM or Brave, it's unclear.
