### ISSUE TITLE
EIP-1559 specs for Ethereum Remote Client

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#17160]
### Background

[EIP-1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md) proposes a dynamic adjustment of block sizes in response to changes in demand for gas, thereby translating volatility in transaction fees to volatility in block space. Transactions must pay a **`BASEFEE`**, which is basically some sort of a moving average based on the current gas limit.

### Technical background

EIP-1559 introduces three gas variables into the picture:
1. `baseFeePerGas` ➜ recorded in block headers and burnt. 🔥 
2. `maxPriorityFeePerGas` ➜ aka miner tip.  ⚒️ 
3. `maxFeePerGas` ➜ same as `baseFeePerGas + maxPriorityFeePerGas`; anything extra is refunded back to user.

These new gas variables must be encoded into a brand-new transaction type ([EIP-2718](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2718.md)), defined by the following RLP:

```
0x02 || rlp([chainId, nonce, maxPriorityFeePerGas, maxFeePerGas, gasLimit,
             destination, value, data, accessList, signatureYParity, signatureR, signatureS])
```

Note that the `baseFeePerGas` is implicit and not part of the transaction RLP.

#### Metamask UX before EIP-1559

|<img src="https://user-images.githubusercontent.com/3684187/126914920-cc2cd5fc-57f7-48c4-8c40-f5bc4d285e94.png">|<img src="https://user-images.githubusercontent.com/3684187/126914944-79b24e0b-1ca5-4e8a-8b7d-c1d59e2890fb.png">|<img src="https://user-images.githubusercontent.com/3684187/126915019-ca9d6dcc-f6e8-4220-9095-abb11143d213.png">|
-|-|-

#### Metamask UX after EIP-1559   ✨

|<img src="https://user-images.githubusercontent.com/3684187/126914627-0ce2a79e-96d8-4e9f-b23c-1cefd55dc3cb.png">|<img src="https://user-images.githubusercontent.com/3684187/126914644-5952a2aa-52a7-4427-a66d-22944a8586e2.png">|<img src="https://user-images.githubusercontent.com/3684187/126914663-76a4709f-c4bf-43dd-aba6-358e71b0d1a9.png">|<img src="https://user-images.githubusercontent.com/3684187/126914705-2aeea5de-9e2a-4307-b546-c785e4b3e46a.png">|
-|-|-|-

### User stories

1. As a user, I can sign EIP-2178 typed transactions, post the London upgrade.
2. As a user, I can sign transactions that use EIP-1559 gas variables, post the London upgrade.
2. As a user, I can switch back to legacy transactions and gas controls, under Settings.
3. As a user, I can optionally customize the max priority fee and max fee, if EIP-1559 is activated.
4. As a user, I can continue using EVM-compatible chains and networks not supporting EIP-1559.

### High-level Tech specs

* Upgrade keyring controllers to work with `@ethereumjs/tx` (including Ledger and Trezor bridges).
* Support EIP-2718 Typed Transaction Envelope using `@ethereumjs/tx`.
* Implement new components for EIP-1559 fee controls (see Metamask screens for UX inspiration).
* Update existing components (ex, transaction detail, history, etc.) to display fees correctly.
* Update transaction parser to extract details from EIP-2718 transactions.
* Implement a background script to read block headers and extract the base fee per gas.
* Integrate with gas API providers or support `eth_maxPriorityFeePerGas` (geth only?).
* Implement a background script to track the miner tip to pay for slow/medium/fast confirmations.
* Update fee estimation for transactions (see tx-gas-utils controller).
* Conditionally support various EIPs (1559, 2718) based on the activated hardfork.
* Support EIP-1559 in speedup and cancel functionalities.
* Allow switching back to legacy gas and raw transaction format easily.

### Additional resources

- [1559 Cheatsheet for Implementers](https://hackmd.io/4YVYKxxvRZGDto7aq7rVkg?view).
- Issue tracking implementation in the new Brave Wallet: https://github.com/brave/brave-browser/issues/14709

**Comment by onyb** [comment]
## Self-QA audit

### Smoke tests

- [x] Wallet unlocks without crashing (wait at least 15 seconds).
- [x] Able to switch networks from the main wallet dashboard, without crashing.
- [ ] ❌ Legacy Type-0 transactions continue to work on Ledger hardware wallet.
- [ ] **??** Legacy Type-0 transactions continue to work on Trezor hardware wallet.

### Send ETH flow

- [x] Clicking on "Send" button does not result in any provider errors (watch out for Varnish errors in the console).
- [x] Able to switch networks from the "Send ETH" container.
- [x] Should not display gas controls in the "Send ETH" container.
- [x] Should display EIP-1559 gas fields in the transaction summary (estimated max priority fee, and max fee).
- [x] Should open gas controls on clicking "EDIT" in the transaction summary page.
- [x] Should allow choosing between slow/average/fast under Basic gas controls.
- [x] Should allow customizing max priority fee, max fee, and gas limit, in Advanced gas controls.
- [x] Should perform basic validation of gas fields in Advanced gas controls.
- [x] Should broadcast the transaction on clicking "Confirm".

### Activity

- [x] Should display max fee per gas and max priority fee per gas (in GWEI), under transaction details (values may be approximated).
- [x] Should display total gas fee (max fee per gas X gas limit), under the Activity Log.

### Send ERC-20 flow

- [x] Should work exactly the same as Send ETH.

### Replace by Fee / Replace by Nonce

- [x] Pending transaction previously submitted with very low max priority fee, can be be sped up with custom fees.
- [x] "-32000 transaction underpriced" RPC error is thrown if max priority fee per gas is 0.
- [x] Pending transaction can be cancelled by bumping the max priority fee by 1.1x.
- [x] Pending cancel transaction can be sped up by bumping the max priority fee by 1.1x.
- [x] Failed transaction can be resubmitted by customizing the max priority fee.

### Swap

- [x] Should be able to swap ETH-DAI using legacy gas pricing fields (type-0 transaction).
- [ ] ❌ Should be able to approve allowance limit for DAI, in DAI-ETH swap. This must use legacy gas fields (type-0 transaction).
- [ ] **??** Should be able to swap DAI-ETH using legacy gas pricing fields (type-0 transaction).
- [ ] **??** Should be able to customize legacy gas pricing fields while fetching swap quotes.
- [ ] **??** Should be able to customize legacy gas pricing fields in transaction confirmation page.

### Fee estimation

- [x] Max priority fee (per gas) estimates, in the gas controls modal, are close to what's being currently being paid on the network.
- [x] `maxFeePerGas = baseFeePerGas + maxPriorityFeePerGas` always holds true (check etherscan).
- [x] Time estimates for slow/average/fast are realistic (not very accurate, so don't bother too much).


### Dapp interactions

- [x] Should be able to swap ETH-UNI on Uniswap, using legacy gas pricing fields (type-0 transaction).
- [ ] **??** Should be able to ..., using EIP-1559 gas pricing fields (type-2 transaction).

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (x86_64)
-- | --
Revision | `c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}`
OS | macOS Version 11.5.2 (Build 20G95)
Component | `1.0.37 dev`

<details> 
<summary>Verified tests from <a href=https://github.com/brave/brave-browser/issues/17160#issuecomment-908282853>#17160 (comment)</a> & <a href=https://github.com/brave/ethereum-remote-client/pull/268>brave/ethereum-remote-client#268</a></summary>
<br/>

<details>
<summary>Smoke tests</summary>
<br/>

- [x]  Wallet unlocks without crashing (wait at least 15 seconds)
- [x]  Able to switch networks from the main wallet dashboard, without crashing
- [x]   Legacy Type-0 transactions continue to work on Ledger hardware wallet
    - [x] Unlock
    - [x] [Send Tx](https://ropsten.etherscan.io/tx/0x31d07740c956aff59901822bdac616aed5febf7e4d1f9779efd521c4815c5c2d)
    - [x] [Swap Tx](https://ropsten.etherscan.io/tx/0xf95fe160842cd148a6e3d602a383437ed2e7bbb226084eb73341fd62175cb98f)

Unlock | Account | Send | Swap
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/132327369-9735ecae-49a1-494a-b585-13d7d7cac4fa.png) | ![image](https://user-images.githubusercontent.com/17010094/132326856-731c9aff-efa0-407b-98bd-fe8501f0b49d.png) | ![image](https://user-images.githubusercontent.com/17010094/132327291-3abe3cf4-8efa-41e1-8f3d-cdbebb71d49c.png) | ![image](https://user-images.githubusercontent.com/17010094/132328143-17fec22b-87d6-4b58-8f4b-eeaf8b5a91b2.png)

- [x]  Legacy Type-0 transactions continue to work on Trezor hardware wallet
    - [x] Unlock
    - [x] [Send Tx](https://ropsten.etherscan.io/tx/0x18840dd0e120db9b9a6f9c7d997cf68e27d8653cb3a4c9a7b5c4fa92dc461e0a)
    - [x] [Swap Tx](https://ropsten.etherscan.io/tx/0xaf297ae331f5109c0c1ccbb0db4ff7bbce57c0094539f9ebb9406301ad87741d)


Unlock | Account | Send | Swap
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/132322251-c731fb1b-e97b-4152-9a14-aa59df024f6c.png) | ![image](https://user-images.githubusercontent.com/17010094/132322861-4ad5dabc-3bb1-4bdc-949a-7084fc554cea.png) | ![image](https://user-images.githubusercontent.com/17010094/132322829-2dc86ef1-7398-449e-a58b-84fd722152fe.png) |  ![image](https://user-images.githubusercontent.com/17010094/132322953-5f0d8c5d-c4ff-438d-b8ef-ca2ff915d597.png)

</details>

<details>
<summary>Send ETH flow</summary>
<br/>

- [x]  Verified clicking on "Send" button does not result in any provider errors in console
- [x]  Verified able to switch networks from the "Send ETH" container
- [x]  Verified gas controls is not shown in the "Send ETH" container
- [x]  Verified EIP-1559 gas fields are shown in the transaction summary (estimated max priority fee, and max fee)
- [x]  Verified gas controls open on clicking "EDIT" in the transaction summary page
- [x]  Verified choosing between slow/average/fast is available under Basic gas controls
- [x]  Verified customizing max priority fee, max fee, and gas limit, is available in Advanced gas controls
- [x]  Verified basic validation of gas fields in Advanced gas controls
- [x]  Verified transaction is broadcasted on clicking "Confirm".

![image](https://user-images.githubusercontent.com/17010094/132328940-8d16bb95-d210-435a-bb4c-8c8e62f57fa6.png) | ![image](https://user-images.githubusercontent.com/17010094/132329306-dbebac18-7c3b-4fb3-a3cb-814bfdbfca8c.png) | ![image](https://user-images.githubusercontent.com/17010094/132329624-fb427d38-d833-4253-aa53-9dfe5fd2ac49.png) | ![image](https://user-images.githubusercontent.com/17010094/132330445-414de9aa-2910-43a5-9c57-b1ade88e6502.png) | ![image](https://user-images.githubusercontent.com/17010094/132331587-147203e6-6e8f-482a-9528-5f7cf1f6f1e1.png) | ![image](https://user-images.githubusercontent.com/17010094/132331665-41902555-448a-452f-8ed3-bad100604cd6.png)
-- | -- | -- | -- | -- | --

</details>

<details>
<summary>Activity</summary>
<br/>

- [x]  Verified max fee per gas and max priority fee per gas in GWEI is displayed under transaction details
- [x]  Verified Total gas fee (Gas Used by Transaction X Max Fee Per Gas) is shown under Activity log
![image](https://user-images.githubusercontent.com/17010094/132333533-ecb843ed-6e01-4814-88c1-384192658cb4.png)

</details>

<details>
<summary>Send ERC-20 flow</summary>
<br/>

- [x]  Verified `Send ERC-20` token works as expected. [Txhash](https://etherscan.io/tx/0x6927b5a8eb8428737b7125063195d1e8d08ceb39319fd063e9657bb13b28e54d)
![image](https://user-images.githubusercontent.com/17010094/132343700-a66917f8-000c-4524-8f89-81dead280017.png)

</details>

<details>
<summary>Replace by Fee / Replace by Nonce</summary>
<br/>

- [x]  Verified pending transaction previously submitted with very low max priority fee, can be be sped up with custom fees.
- [x]  Verified "-32000 transaction underpriced" RPC error is thrown if max priority fee per gas is 0.
- [x]  Verified pending transaction can be cancelled by bumping the max priority fee by 1.1x.
- [x]  Verified pending cancel transaction can be sped up by bumping the max priority fee by 1.1x.
- [x]  Verified failed transaction can be resubmitted by customizing the max priority fee.

![image](https://user-images.githubusercontent.com/17010094/132353322-a4bdb0d1-7d20-41a2-a369-c36de6409694.png)
![image](https://user-images.githubusercontent.com/17010094/132353528-d1f8bcce-1d84-4dd3-b08b-b72ff4830362.png)

</details>

<details>
<summary>Swap</summary>
<br/>

- [x]  Verified able to swap ETH-DAI using legacy gas pricing fields [type-0 transaction](https://ropsten.etherscan.io/tx/0xf95fe160842cd148a6e3d602a383437ed2e7bbb226084eb73341fd62175cb98f).
- [x]  Verified able to approve allowance limit for DAI, in DAI-ETH swap. This must use legacy gas fields (type-0 transaction).
- [x]  Verified able to swap DAI-ETH using legacy gas pricing fields [type-0 transaction](https://ropsten.etherscan.io/tx/0x70b6963c186a2c88a4d6160169a427827c7cb66b3a3d93955e1db361b409b726).
- [x]  Verified able to customize legacy gas pricing fields while fetching swap quotes.
- [x]  Verified able to customize legacy gas pricing fields in transaction confirmation page

![image](https://user-images.githubusercontent.com/17010094/132443870-8d3bfc67-24ea-41be-8237-2f88e18b3fd6.png) | ![image](https://user-images.githubusercontent.com/17010094/132444142-3bbe4d1b-4b55-4b6b-b618-7fb848392114.png) | ![image](https://user-images.githubusercontent.com/17010094/132444126-c6b92751-91a1-4f9a-9301-6469394721cd.png) | ![image](https://user-images.githubusercontent.com/17010094/132444569-cb7e259b-1fea-46e6-85cf-5a358d2e888d.png) | ![image](https://user-images.githubusercontent.com/17010094/132444595-984ac2c2-94e7-4574-af5b-cad37833e19f.png) | ![image](https://user-images.githubusercontent.com/17010094/132444685-cf162ec2-5fe3-4cd7-8bcc-c12ddd4c22db.png) | ![image](https://user-images.githubusercontent.com/17010094/132444787-dcae8e1c-48eb-4a39-b1ce-129d961c1127.png) | ![image](https://user-images.githubusercontent.com/17010094/132444876-740b079d-cd14-4bc2-9e17-d8e49e884706.png) | ![image](https://user-images.githubusercontent.com/17010094/132444979-32ada55b-c3d7-4902-8fd8-22eb1924bc1e.png)
-- | -- | -- | -- | -- | -- | -- | -- | -- 



</details>

<details>
<summary>Fee estimation</summary>
<br/>

- [x] Verified `Max priority fee` (per gas) estimates, in the gas controls modal, are close to what's being currently being paid on the network.
- [x] Verified `maxFeePerGas = baseFeePerGas + maxPriorityFeePerGas` always holds true 
- [x] Verified `Time` estimates for slow/average/fast are realistic 


</details>

<details>
<summary>Dapp interactions</summary>
<br/>

- [ ]  Verified able to swap ETH-UNI on Uniswap, using legacy gas pricing fields [type-0 transaction]() - Pending

</details>

</details>


* Encountered [#17907](#17907) & [#17936](#17936)
