### ISSUE TITLE
Focus on existing tab rather than opening a new one every time

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17164]
## Description 

Focus on existing tab rather than opening a new one every time

## Steps to Reproduce

   1. Enable wallet flag on nightly
   2. Open wallet page in a new tab
   3. Click on browser action button and click on create/restore, opens a new tab rather than focusing on the existing tab

## Actual result:

https://user-images.githubusercontent.com/17010094/127007242-ab17acff-0437-42b9-880c-8e941ebd699f.mp4

## Expected result:
Focus on existing tab rather than opening a new one every time

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.29.20 Chromium: 92.0.4515.107 (Official Build) nightly (64-bit)
-- | --
Revision | `87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @bbondy

**Comment by HEagle18** [comment]
No resolved with new onboarding.
