### ISSUE TITLE
Disable GCM

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#1716]
GCM (Google Cloud Messaging) is a deprecated but still supported way for websites to do push messaging. It routes everything through Google servers. It also provides a `chrome.gcm` API for extensions, which we should also disable.

Google's developer documentation: https://developers.google.com/cloud-messaging/chrome/client

Chromium code is in and around https://cs.chromium.org/chromium/src/google_apis/gcm/engine/

**Comment by LaurenWags** [comment]
@pilgrim-brave does this require manual QA? if so, can you provide a test plan please? cc @kjozwiak

**Comment by pilgrim-brave** [comment]
No.
