### ISSUE TITLE
tip/contribution not recorded if wifi dropped or browser closed during contribution

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1717]
## Description 
If you lose wifi connection or close Brave immediately after tipping a creator, the BAT is removed from your wallet but the Tip is not recorded. 

This was not tested with auto-contribute as I can't tell when contribution is happening at this time, but it should be verified against auto-contribute when we can tell when a contribution is in progress.

## Steps to Reproduce

   1. Clean profile on 0.55.18. 
   2. Enable Rewards, claim grant/fund wallet.
   3. Navigate to a site. 
   4. Wait a bit, click on the BAT logo to get the panel. 
   5. Click on the Send a Tip button.
   6. Choose an amount and click on Send My Tip.
   7. Immediately close Brave or kill wifi.

## Actual result:
When you get wifi back/reopen Brave, your balance is lower, but Tip is not listed in Wallet Summary or Tip panel:
![screen shot 2018-10-18 at 3 52 53 pm](https://user-images.githubusercontent.com/28145373/47180211-056ed880-d2ee-11e8-93b4-0c71366ba4e1.png)

![screen shot 2018-10-18 at 3 53 06 pm](https://user-images.githubusercontent.com/28145373/47180217-09025f80-d2ee-11e8-8ccf-297912af866e.png)

## Expected result:
Tip should be recorded

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? n/a
- Does it reproduce on browser-laptop? n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Once we get Verbose flag we need to check this with auto-contribute as well.

**Comment by NejcZdovc** [comment]
closing in favour of https://github.com/brave/brave-browser/issues/1483
