### ISSUE TITLE
Long Ads titles need better styling in brave://rewards' Ads History 

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17179]
## Description 

Long Ads titles need better styling in brave://rewards' Ads History 

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open a new-tab page
   4. click to `Start using Rewards`
   5. scroll down and click `Show Brave News`
   6. view/click on a inline-content ad
   7. open a new tab page with a sponsored image
   8. open `brave://rewards`
   9. look at the layout of the `Make your gear more...` ad entry

## Actual result:

<img width="852" alt="Screen Shot 2021-07-26 at 10 58 18 AM" src="https://user-images.githubusercontent.com/387249/127050535-6523a147-1091-47f9-90b2-3695a0fffc79.png">

## Expected result:
Either better line wrapping/padding, or the size (length) of the box borders could use increasing, to match the longest strings possible via Ads.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.29.27 Chromium: 92.0.4515.107 (Official Build) nightly (x86_64)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 11.5 (Build 20G71)

/cc @rebron (credit for finding)

**Comment by Miyayes** [comment]
Will close in favor of https://github.com/brave/brave-browser/issues/29365
