### ISSUE TITLE
Verify efficacy of https://github.com/brave/brave-site-specific-scripts/pull/61

### ISSUE THREAD

**Issue by mrose17** [brave/brave-browser#17183]
## Description 
 https://github.com/brave/brave-site-specific-scripts/pull/61 added an new site to the list to run the test for Brave Rewards being enabled. Other sites have been tested under the same list. The site isn't running yet, so the goal is simply to ensure that Greaselion.json loads properly!

## Steps to Reproduce
N/A

## Actual result:
N//A

## Expected result:
N/A

## Reproduces how often: 
N/A

## Brave version (info found on brave://version)
N/A

## Version/Channel Information:
N/A

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
N/A

**Comment by LaurenWags** [comment]
Labelling `QA/No` per discussion with @mrose17 @stephendonner @emerick @kjozwiak 

Fixed per the PR referenced in the description - https://github.com/brave/brave-site-specific-scripts/pull/61
