### ISSUE TITLE
Sites are never added to auto-contribute list if rewards are enabled through Rewards Panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1719]
## Steps to Reproduce

1. Clean install
2. Enable rewards through Rewards Panel (Rewards icon)
3. Open twitch.tv in a new tab and watch a stream for few minutes
4. Close twitch.tv tab
5. Go to brave://rewards/ and check auto-contribute list.

Important: Sites will be added to auto-contribute list only after brave://rewards/ is opened first.

## Actual result:

auto-contribute list is empty. 
the publisher is not added to publisher_info_db

Steps 1-3
![1719_fail](https://user-images.githubusercontent.com/34715963/47184901-3968ee80-d32c-11e8-9bf7-408619d70bb1.gif)

Steps 4-5 after 5 minutes of watching stream.
![1719_fail2](https://user-images.githubusercontent.com/34715963/47184906-3e2da280-d32c-11e8-90bc-c7811de750c5.gif)

## Expected result:
the twitch publisher is added to auto-contribute list

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

Reproduced by @LaurenWags on Mac OS
cc @GeetaSarvadnya @kjozwiak @srirambv @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows
