### ISSUE TITLE
Brave News feed jumps down to Discount card rather than starting from beginning of the feed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17198]
## Description 

Brave News feed jumps down to Discount card rather than starting from beginning of the feed

## Steps to Reproduce

   1. Open a new tab
   2. Scroll down using mouse wheel 
   3. News feed jumps to discount card rather than starting from beginning

## Actual result:

https://user-images.githubusercontent.com/17010094/127179481-6ddb25ba-da87-4658-958a-9e430251fa18.mp4

## Expected result:
Start feed at begninning

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 1.29.27 Chromium: 92.0.4515.107 (Official Build) nightly (64-bit)
-- | --
Revision | `87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No 
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Note: I do have certain feeds disabled so its not the default setting
cc: @brave/legacy_qa to check on other platforms. Can share the source settings if required

**Comment by mattmcalister** [comment]
@srirambv or @stephendonner can you check whether this is still relevant?

**Comment by srirambv** [comment]
Checked on latest nightly and don't see it reproduce. We are good to close this. Will reopen if I can get into this state again
