### ISSUE TITLE
How to disable Chromecast to Android TV in Brave Android?

### ISSUE THREAD

**Issue by cbwee** [brave/brave-browser#17195]
In Brave Android, is there any way to disable Chromecast that appears in the menu of an online video?

Because when an Android TV box is on, the cast option appears in the menu when a video is played in the video player of Brave Android on the phone, and it's easy to accidentally cast a video while trying to download the video.

If there is any way to disable it, please let me know, if not, I hope an option can be added to disable it.

**Comment by Brave-Matt** [comment]
@cbwee unfortunately no, there is no way to disable this button in a specific browser that I am aware of. You can disable casting entirely on your Android phone in your phone's `Settings` but I'm not sure that's desirable for your situation.
