### ISSUE TITLE
Verifiable Ad Conversion are not working on existing campaigns without fresh profile

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#17200]
## Description 
Verifiable Ad Conversions are not working on campaigns that are VAC-enabled mid campaign.

I believe this is because conversion URLs are persisted even when changed in the ad server/catalog.
<img width="1440" alt="redbubble-multipleUrl" src="https://user-images.githubusercontent.com/24831890/127187052-ef5e11e2-1ab6-482d-bd3c-d1f110d0cd63.png">

## Steps to Reproduce
   1. Load daily driver or profile that had previously loaded a US-based catalog with VAC-enabled campaign
   (ask @iambrianfung for help)
   2. Update the conversion URL on VAC-enabled campaign + add conversionPublicKey
   3. Load profile again to fetch new catalog
   4. Check local database `creative_ad_conversion` to see both conversion URLs as entries
   5. force ad to show & convert.
   6. Confirm conversion event
   7. Check that `conversion_id` was is not extracted + `advertiser_public_key` is not shown.
   This indicates the incorrect conversion URL triggered this

## Actual result:
`conversion_id` is not extracted & `advertiser_public_key` exists
<img width="1440" alt="redbubble_noConversion" src="https://user-images.githubusercontent.com/24831890/127186345-ca96664c-1ed6-46f5-8c3e-82995501aeef.png">

## Expected result:
`conversion_id` is extracted & `advertiser_public_key` exists
not the same campaign but shows expected values:
<img width="1440" alt="Screen Shot 2021-06-09 at 09 08 35" src="https://user-images.githubusercontent.com/24831890/127186454-ec2aa827-91e4-4648-9381-8d4996e6665d.png">

## Reproduces how often: 
Based on pulling conversion events from the production ad server, it seems highly reproducible on our users. 
This may be more difficult to reproduce internally. Coordinate with @iambrianfung to set up the correct reproduction scenario.

## Brave version (brave://version info)
Version 1.27.108 Chromium: 92.0.4515.107 (Official Build) (arm64).

## Version/Channel Information:
This is occurring on Release Channel. Very likely on Beta/Nightly as well.

**Comment by moritzhaller** [comment]
@tmancey this seems to be a general problem with conversion URL updates, not only for VAC. @iambrianfung can you confirm that this would also impact non-VAC campaigns?

**Comment by tmancey** [comment]
Closing issue as will be superseded by multiple conversions https://github.com/brave/brave-browser/issues/16091
