### ISSUE TITLE
Adjust "ad-supported" in Brave News intro card, per user research 

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#17206]
per @rmcfadden3 at https://github.com/brave/brave-com-resources/issues/331

> We got some feedback in user research that the phrase "ad-supported" in the Brave News intro tile was confusing, or even a turnoff. I'd like to remove this phrase, and replace the body copy. So it would look like:
>
> Header: Today's top stories in a completely private feed, just for you.
Body: Brave News is completely private, and customized directly in your browser. Your data never leaves your device. Learn more in our privacy policy.
>
> For reference, here's a screenshot of the place I mean:
>
> ![image](https://user-images.githubusercontent.com/741836/127207904-9c6b01d1-d748-4fe0-b3b1-cad2b6242dff.png)
>
> CC @mattmcalister & @karenkliu
>
> ## Designs
> ![image](https://user-images.githubusercontent.com/741836/127207943-27f5f739-dc6e-4881-b0b9-76c7f414132a.png)
>
> Assets
> Figma: figma.com/file/wpjvatVQQvOtC96WaPCw86/?node-id=1151%3A23106

However, the ensuing discussion might mean we don't need to do this?

@mattmcalister :
> The whole point of the opt-in is so that we can show ads and send content to the user's browser with their explicit consent. This was defined and discussed in the opt-in spec and agreed with Yan, Brian Bondy and Pat.
> that said, we are going to need better discoverability for this feature asap. @karenkliu has done some concept work for that on desktop that we should finish and prioritize with dev. we could re-work the language on the opt-in card as part of that effort.

**Comment by karenkliu** [comment]
@mattmcalister We should discuss with Pat/Yan/Brian Bondy soon about having a blanket opt-in card when user downloads and installs Brave so we don't have to put these Brave Ad disclaimers on individual features.

**Comment by mattmcalister** [comment]
Sounds good. Do you have mockups of what you're thinking?

**Comment by karenkliu** [comment]
@mattmcalister  Yes, kind of. Need to start the conversation first with privacy/security to inform the design.

**Comment by mattmcalister** [comment]
This has been noted and will be addressed in the revised onboarding coming soon. Am closing this issue.
