### ISSUE TITLE
BAT tokens suddenly disappeared

### ISSUE THREAD

**Issue by yann12100** [brave/brave-browser#17215]
Hi, Brave Team!
I just saw that my more than 100 BAT tokens disappeared from my account afew days ago.
Could you please take a look and restore my tokens please ?

Thanks !

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by hollons** [comment]
@yann12100 thanks for reporting! Can you submit a ticket using this link and include the Wallet ID linked to your device - https://support.brave.com/hc/en-us/requests/new. We can troubleshoot from there. Thanks!

**Comment by tmancey** [comment]
Closing issue as @hollons is handling via https://support.brave.com/hc/en-us/requests/new
