### ISSUE TITLE
Follow up of #16940 - Brave branded bookmarks subfolder images are not shown clearly in Private tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#17214]
## Description 

Follow up of #16940 - Brave branded bookmarks subfolder images are not shown clearly in Private tabs

## Steps to Reproduce

   1. Clean profile 1.28.92
   2. Import bookmarks folder or create a new bookmarks folder in the bookmarks bar
   3. Open Private tab/Tor private tab
   4. Brave branded bookmarks subfolder images are not shown clearly in Private tabs

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/127284797-22ad4836-53ea-4cbd-8edf-5f1e84dfab4a.png)

## Expected result:

Brave branded bookmarks subfolder images should be shown clearly in Private tabs
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.28.92 Chromium: 92.0.4515.107 (Official Build) beta (64-bit)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2004 (Build 19041.1110)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @simonhong @rebron @karenkliu

**Comment by kjozwiak** [comment]
Going to `release-notes/exclude` as https://github.com/brave/brave-browser/issues/17463 basically covers this change/fix as well.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.29.80 Chromium: 93.0.4577.63 (Official Build) (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/10037

**_Regular window - Light theme_**
![image](https://user-images.githubusercontent.com/38657976/133055343-3d0b05e3-0787-4157-b967-0d22232975ce.png)

**_Regular window - Dark theme_**
![image](https://user-images.githubusercontent.com/38657976/133055543-4a6a126b-50a6-4437-a97b-a35e1da7e7a6.png)

**_Private window - Light theme_**
![image](https://user-images.githubusercontent.com/38657976/133055761-c4d6b17e-f524-42f1-9b7a-81974e71ca20.png)

**_Private window - Dark theme_**
![image](https://user-images.githubusercontent.com/38657976/133055907-ef9afb46-b821-4360-b5bb-bbb192ebf2f6.png)

**_Tor window - Light theme_**
![image](https://user-images.githubusercontent.com/38657976/133056026-1596970f-77f0-4d11-9edb-dfcedc5b24ce.png)

**_Tor window - Dark theme_**
![image](https://user-images.githubusercontent.com/38657976/133056132-51669e70-32b3-449f-9334-6dd41d6ba22c.png)
