### ISSUE TITLE
[Feature request] Being able to add and edit "top sites"

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#17217]
The feature which make users be able to edit and add "top sites" is really useful. I hope it be added to the Anfroid version. Thank you.

**Comment by sanathusk** [comment]
It would be great if the feature could be implemented

**Comment by Dave051987** [comment]
Yes this feature would be awesome.

**Comment by gossbill** [comment]
I totally support this feature request!

**Comment by blogmangit** [comment]
+1 I support this issue and I think to have this feature will be awesome 👌

**Comment by DarrenSem** [comment]
+1!!! I accidentally clicked Remove on a frequent site and now it thinks I wanted it permanently hidden from the list :-(

**Comment by SlowNicoFish** [comment]
They have this on Mac, iOS and windows. Seems like android is always drawing the short end of the stick

**Comment by SlowNicoFish** [comment]
https://github.com/brave/brave-browser/issues/16821

**Comment by kyoyacchi** [comment]
Up

**Comment by Bohdan-Mishchuk** [comment]
+

**Comment by Hmm-mmm** [comment]
I wonder if it is really difficult to add this option to manually add/edit the sites in the front page. 🤔

It would be great if the devs could bring this feature. It is really needed.

**Comment by RickAust** [comment]
Definitely a very worthwhile feature. Surely it's not that difficult to implement.

**Comment by nicdevera** [comment]
no one's picking up on this? maddening lack in brave mobile.

**Comment by senescence01** [comment]
It's baffling how no one cares about this feature.

**Comment by bill-mcgonigle** [comment]
from a closed issue: 

> The ANDROID app needs this feature! I accidentally clicked Remove on a frequent site and **now it thinks I wanted it permanently hidden from the list** :-(

This, especially.

Do I need to get in with sqlite or something to undo a fat-finger removal of my top daily news site? It's probably my second most frequent site.

**Comment by bsclifton** [comment]
Thanks for the feedback folks - I'm going to close this issue as a duplicate of https://github.com/brave/brave-browser/issues/33845

Please subscribe for updates on that issue - we have mock ups and will be starting work soon! 😄
