### ISSUE TITLE
Uplift Brave Talk to Beta/Release

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#17210]
## Test plan
1. Ensure Brave Talk is enabled in Griffin
2. Fresh profile
3. Launch Brave
4. Open a new tab
5. You should see the Brave Talk promo (bottom right)
6. If you click `Edit Cards` you should be able to add `Brave Talk`

## Description 
Currently, Brave Talk is only on Nightly. We need to show it for all channels:
- Brave Talk widget
- Icon in bottom right of NTP
- Tooltip that shows
- other places?

**Comment by stephendonner** [comment]
> ## Description
> Currently, Brave Talk is only on Nightly. We need to show it for all channels:
> 
> * Brave Talk widget
> * Icon in bottom right of NTP
> * Tooltip that shows
> * other places?

It's in Sidebar, but don't think Sidebar itself is ready (and there shouldn't be anything to do anyhow?)

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` until we get Brave Talk enabled on `main` (staging) via Griffin. After it's enabled on staging, QA will be able to run through the above verification. Once we get closer to Brave Talk release date, we'll push the same change into `production`.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-variations/pull/93 was merged into `main` (Griffin staging).

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

```
- ensured that `Brave Talk` widget is enabled via NTP on main (staging) after launching brave via the following:
`brave.exe --variations-server-url=https://variations.bravesoftware.com/seed`
- ensured that `BraveTalkStudy` is enabled via brave://version/?show-variations-cmd
![image](https://user-images.githubusercontent.com/38657976/128813325-096f0aa8-fa7a-41d1-a2df-f94f40aa6ae5.png)
- ensured that the `BraveTalk` promo tooltip is shown in NTP when the OS clock is forwarded to 3 days

now | after 3 days
-----|---------------
![image](https://user-images.githubusercontent.com/38657976/128813555-9d18444d-0894-4a08-890c-138e3857f27c.png) | ![image](https://user-images.githubusercontent.com/38657976/128813691-80a79cfe-78c3-4bdc-b70d-bc20e762244f.png)
