### ISSUE TITLE
Audio Cuts in current version

### ISSUE THREAD

**Issue by feiercrack** [brave/brave-browser#17233]
in current Windows  Version 1.27.109 Chromium: 92.0.4515.115 (Offizieller Build) (64-Bit)
when starting an video or an Olympia livestream there are many audio cuts, almost unviewable

start Brave
goto e.g. https://www.zdf.de/sport/sport-im-zdf-livestream-live-100.html#videoId=olympia-tokio-2020-3-wettkampftag-sportstudio-live-100
watch and listen
each few seconds audio starts and stops
sometimes its muted a long time

Windows 10 x64 Pro 21H1 19043.1110

p.s. same in the Nightly Version 1.29.27 Chromium: 92.0.4515.107 (Offizieller Build) nightly (64-Bit)
Browser Player Volume is set 100% Windows ~10%

**Comment by ryanbr** [comment]
Hey @feiercrack   Due to geo checks, I wasn't able to play the url. However, `https://www.zdf.de/wissen/leschs-kosmos/vermuellt-versauert-ausgebeutet-reha-fuer-die-ozeane-100.html` playback seemed okay, Is this still an issue? Does adjusting the video bitrate help?

**Comment by feiercrack** [comment]
hiya @ryanbr Yes, still occurs. How to adjust the bitrate?

**Comment by ryanbr** [comment]
Click on the "Cog" menu, near the bottom right. Change the video quality, select the middle option. See if it helps

**Comment by ryanbr** [comment]
Re-checked this, playback is fine in the latest Brave build. Safe to close? @feiercrack

**Comment by rebron** [comment]
Closing as stale and per last comment. @feiercrack We can re-open if you're still experiencing the issue.
