### ISSUE TITLE
Crash after stopping Google Meet Screenshare

### ISSUE THREAD

**Issue by maharjanaman** [brave/brave-browser#17237]
## Description 

Brave browser sometimes crashes after stopping screen sharing in Google Meet.

## Steps to Reproduce

   1. Join any Google Meet
   2. Screenshare browser window
   3. Stop screenshare

## Actual result:

Browser crashes.

## Expected result:
Screen share should be stopped.

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Not tested
- Can you reproduce this issue with the nightly channel?  Not tested

**Comment by rebron** [comment]
@maharjanaman When you get a chance, can you go to brave://crashes and send the crash report and paste the crash id here?

**Comment by maharjanaman** [comment]
@rebron There is two,
`Local Crash Context:	8ec0c302-8d35-40e5-8272-62ac99298fd2`
`Local Crash Context:	9792a7bb-b879-46b7-b60d-e23b1b1d98ca`

**Comment by dverb1647** [comment]
I have the same problem, here is my crash ID
dfa41200-001d-ca06-0000-000000000000

This also seems identical to https://github.com/brave/brave-browser/issues/16268

**Comment by Tonev** [comment]
@bsclifton @rebron 

Multiple users report the same issue in Brave Community:
https://community.brave.com/t/always-crashes-after-screen-sharing-on-google-meet-whereby-microsoft-teams/263647

**Comment by berters** [comment]
This happens to me all the time.

Another crash ID:

d36a1100-6f39-fa06-0000-000000000000

**Comment by leonp5** [comment]
Seems, that i face this issue too after the last Brave update (V1.39.111).

When i want to stop the screen sharing, the whole browser closes/crashes immediately.

Using MS Teams in Brave on a Linux Machine (Linux Mint 20).

Crash ID:
b9770300-2578-4408-0000-000000000000

**Comment by RaphaelColman** [comment]
This is happening to me as well.
Brave: V1.39.111
Linux: Ubuntu 20.04.4 LTS

How do I get a crash ID?

**Comment by natrad100** [comment]
Have this in the current Beta as well
Version 1.40.75
Chromium: 102.0.5005.61 (Official Build) beta (64-bit)

**Comment by AlexeyBarabash** [comment]
I can reproduce it with Brave Talk, 


Uploaded Crash Report ID:  a98a0400-2578-4408-0000-000000000000

**Comment by leonp5** [comment]
> This is happening to me as well. Brave: V1.39.111 Linux: Ubuntu 20.04.4 LTS
> 
> How do I get a crash ID?

Simply type `brave://crashes/`

**Comment by AlexeyBarabash** [comment]
>How do I get a crash ID?

>Simply type brave://crashes/

You need also to enable `Automatically send diagnostic reports` option at brave://settings/privacy

**Comment by RaphaelColman** [comment]
> > This is happening to me as well. Brave: V1.39.111 Linux: Ubuntu 20.04.4 LTS
> > How do I get a crash ID?
> 
> Simply type `brave://crashes/`

Thanks! In that case
Crash id: 42c00800-2578-4408-0000-000000000000

**Comment by agilob** [comment]
Brave version (brave://version info)

Brave | 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}

Crash IDs:
436b0500-b1ec-5608-0000-000000000000
45780400-b1ec-5608-0000-000000000000
46270300-b1ec-5608-0000-000000000000

**Comment by umasse** [comment]
I have just provided one more Crash ID:
https://github.com/brave/brave-browser/issues/23599
1ffa0400-4c26-6008-0000-000000000000

Brave Version: 1.40.105 Chromium: 103.0.5060.53
Operating System: Linux 5.15.0-39-generic (Ubuntu 22.04 with Gnome and Wayland)

**Comment by adambadu** [comment]
Happens also when using MS Teams web app. Unfortunately i cannot pin down the moment when this started :(

Last crash id: 07760000-e963-6908-0000-000000000000
Probably worth to mention that i had around 40 tabs open last time it happened.

**Comment by leonp5** [comment]
I just discovered, that i can prevent the crash, when i **don't** use the close button which appears on the shared screen. Instead i cancel the screensharing with the button inside the browser tab where the (MS Teams) web app runs.
I try to make the description more clear: In MS Teams the button to start the screensharing can also be used to stop it. When i use this button to stop the sharing, at the moment, Brave doesn't crash.
I guess, every other client like Google Meet has a similar possibility to stop the screensharing.

**Comment by ohno418** [comment]
Happens on Linux (Arch with kernel 5.18.7).
id: bd9e1e5d-a8a0-494f-89f6-e726751480ed

I tried on macOS but didn't happen on it.

**Comment by vmoyankov** [comment]
Same on Debian 11, i3wm. Every time when stop sharing the entire screen. Not noticed when sharing window or tab.
Crash ID: 576f0200-2086-9708-0000-000000000000

**Comment by agilob** [comment]
If you want to prevent brave crashing when stopping screen share, don't click on the popup dialog, but go back to the meeting and cancel it there
![image](https://user-images.githubusercontent.com/2544251/181826969-b0db7113-f221-4374-883e-99ee3194c7a0.png)
