### ISSUE TITLE
Auto-purge Browsing History on Android?

### ISSUE THREAD

**Issue by TriggerDingus** [brave/brave-browser#17230]
I'm finding in various Android apps/browsers that an option for auto-clearing of browsing data is being removed and I'm not sure I understand why, particularly in browsers that claim to be privacy-minded. (even Tor on Android has removed this in the latest version, favoring burying a 'clear browsing data' function deeply in its menus) The Brave browser on the desktop (I use Linux) can be set to "Clear History/Data on Exit" but the Android version has no such capability to auto-clear at a set time interval or upon exit and I'm pretty sure it used to since I've been a user since the beginning. I find saving browser history/data on my phone highly undesirable and a liability as a privacy-minded user and I'm a bit surprised Brave on Android doesn't offer auto-purging of some kind any longer. Does someone have any insight? Perhaps I'm mistaken?

**Comment by Tonev** [comment]
Brave on Android allows users to clear all of their browsing data on exit via `Settings` -> `Brave shields & privacy` -> `Clear data on exit`.

There is an open feature request for the possibility to choose what to clear on exit:

- https://github.com/brave/brave-browser/issues/17209

**Comment by srirambv** [comment]
You have clear data on exit in shields and privacy settings. Note this will delete everything what ever is listed in Advanced section of clear browsing data

<img width=500 src=https://user-images.githubusercontent.com/17010094/127428131-ce7f1bc3-571b-4d3d-a5e9-357a2d71d119.png>

https://github.com/brave/brave-browser/issues/17209 is logged for selecting the options to clear

**Comment by TriggerDingus** [comment]
I did a bunch of digging but I don't have that menu option.
I eventually found that I'm on v1.21, which is the latest version in the F-Droid and Aurora Store repositories but there's a later version APK I can download so I'll try that. I see the Google store has a later version but I stay away from that

Thanks for helping out!
