### ISSUE TITLE
"Processor" is blank on Contribution tab on brave://rewards-internals when Gemini is used

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#17239]
## Description 

"Processor" field is blank on Contributions tab of brave://rewards-internals when KYC'd Gemini wallet was used to do the contribution.

## Steps to Reproduce

Pre-req: be on VPN
   1. Clean profile, staging, enable Gemini
   2. Enable Rewards
   3. Connect KYC'd Gemini account
   4. Do a one time tip to KYC'd Gemini publisher
   5. Wait for tip to go through (may take up to 10 min)
   6. Once balance decreases appropriately, look at brave://rewards-internals

## Actual result:

<img width="1193" alt="Screen Shot 2021-07-29 at 11 16 32 AM" src="https://user-images.githubusercontent.com/28145373/127519423-0728ef84-d6b5-47c8-843b-4ea153dab622.png">

## Expected result:
Processor should not be blank

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.29.37 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 10.15.7 (Build 19H1217)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? likely yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @jumde

**Comment by stephendonner** [comment]
Verified `PASSED` using the inline testplan with 


Brave | 1.29.42 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 12.0 (Build 21A5294g)

Steps:

1. clean profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3. enabled Gemini via `brave://flags`
4. enabled Rewards
5. connected KYC'd Gemini account
6. did a one time tip to KYC'd Gemini publisher
7. waited for tip to go through (took ~10 min)
8. once balance decreased from tip, looked at `brave://rewards-internals`

Confirmed `Processor:` now shows `Gemini Wallet`

tip | `brave://rewards` | `brave://rewards-internals`
---|-------------------|---------------------------
<img width="1200" alt="Screen Shot 2021-08-02 at 2 06 08 PM" src="https://user-images.githubusercontent.com/387249/127925204-e193b77c-356d-4328-850f-8ea8d8d9618e.png"> | <img width="1312" alt="Screen Shot 2021-08-02 at 2 14 08 PM" src="https://user-images.githubusercontent.com/387249/127925298-8b313e0e-c00b-4edb-8b36-e83601c66f4f.png"> | <img width="1312" alt="Screen Shot 2021-08-02 at 2 14 30 PM" src="https://user-images.githubusercontent.com/387249/127925301-a0c9933e-66a3-46ee-b185-f911aff701ce.png">
