### ISSUE TITLE
combine 2 strings into 1 string in BR-Off panel text

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#1723]
This was a hack to avoid breaking the page with missing content in a string.

Please combine the 2 strings into one paragraph here:

![image](https://user-images.githubusercontent.com/13509546/47188411-c7bd8000-d2ec-11e8-9b36-79efb5cbf902.png)

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows
