### ISSUE TITLE
Add `Brave VPN` to hamburger menu

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#17244]
## Description 
Add `Brave VPN` menu item to Hamburger menu [behind the VPN feature flag](https://github.com/brave/brave-core/pull/9531).

Before purchase
- [x] https://github.com/brave/brave-browser/issues/17778
<img width="584" alt="Screen Shot 2021-09-01 at 9 39 22 AM" src="https://user-images.githubusercontent.com/2388823/131710062-8873d8fe-3d88-4473-9fe8-868bef27c234.png">

Post purchase
- [x] https://github.com/brave/brave-browser/issues/17882
<img width="580" alt="Screen Shot 2021-09-01 at 9 38 57 AM" src="https://user-images.githubusercontent.com/2388823/131710013-1b4393c4-33fc-4467-9e13-21d83a9dc95e.png">

**Comment by simonhong** [comment]
@rebron @karenkliu Curious we should put toggle option for vpn button (`Show VPN button in toolbar`) only in post-purchase menu. maybe we should give this option always to users?

**Comment by karenkliu** [comment]
@simonhong I updated the screenshots for the hamburger menu! It's the final version. The pre-purchase and post-purchase hamburger menu are a little different. Prior to purchase, users will have to go to the permanent option in brave://settings to hide/show the VPN button in the toolbar. (Again, this is a permanent option so it's there whether or not the user has purchased VPN).

<img width="621" alt="Screen Shot 2021-09-01 at 9 40 55 AM" src="https://user-images.githubusercontent.com/2388823/131710260-8b606b27-befe-486d-8711-803783a6c6ef.png">

**Comment by simonhong** [comment]
@karenkliu we should use `Show VPN button in toolbar` and `Hide VPN button in toolbar` based on button's visibility?

**Comment by karenkliu** [comment]
@simonhong 

>we should use Show VPN button in toolbar or Hide VPN button in toolbar based on button's visibility?

No, the text in brave://settings should not change. Only the toggle turns on and off.

**Comment by simonhong** [comment]
@karenkliu how about app menu entry? it also shows one `Show VPN button in toolbar`?

**Comment by simonhong** [comment]
All sub tasks are resolved.
