### ISSUE TITLE
Brave randomly changes language when I visit different websites

### ISSUE THREAD

**Issue by bozzmob** [brave/brave-browser#17255]
## Description 

Websites that support localization randomly, brave randomly change the locale of my browser.

## Steps to Reproduce

   1. Set browser language to English US
   2. I visit a random website and see website language changed and many times, for the same website, new links open in new languages
   3. This issue is from the last 6 months.

## Actual result:

![image](https://user-images.githubusercontent.com/1252941/127603306-90f65e07-9ee9-4306-9928-6f6150adf1e7.png)

![image](https://user-images.githubusercontent.com/1252941/127603162-ea4a172e-e10f-42cd-b983-86f81a03ed8f.png)

![image](https://user-images.githubusercontent.com/1252941/127603212-d2d3fa8e-9e0d-41d5-88f0-875c061f46ca.png)

## Expected result:
Should be in English

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
Brave	1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)
Revision	87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS	Windows 10 OS Version 2009 (Build 19043.1110)
JavaScript	V8 9.2.230.20
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --no-startup-window /prefetch:5 --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,WinrtGeolocationImplementation,SafetyTip --disable-features=AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,EnablePasswordsAccountStorage,HandwritingRecognitionWebPlatformApi,LiveCaption,AutofillServerCommunication,TrustTokens,DirectSockets,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,IdleDetection,SignedExchangeSubresourcePrefetch,FledgeInterestGroups,InterestCohortFeaturePolicy,InterestCohortAPIOriginTrial,FirstPartySets,FederatedLearningOfCohorts,PrivacySandboxSettings,NetworkTimeServiceQuerying,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,WebOTP,NotificationTriggers,LangClientHintHeader,TextFragmentAnchor,EnableProfilePickerOnStartup --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=SecurePaymentConfirmation
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\satvi\AppData\Local\BraveSoftware\Brave-Browser\User Data\Profile 1
Variations	AdRewardsStudy:NextPaymentDay
EphemeralStorageStudy:Enabled
NativeCosmeticFilteringStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled

```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't checked
- Can you reproduce this issue with the nightly channel? Haven't checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by unlucio** [comment]
I tried the same settings:

<img width="705" alt="Screenshot 2021-07-30 at 15 17 27" src="https://user-images.githubusercontent.com/778799/127658591-3f37e7d7-ddce-4ded-be88-df0515ae755a.png">

and it doesn't happen to me:
<img width="1389" alt="Screenshot 2021-07-30 at 15 17 41" src="https://user-images.githubusercontent.com/778799/127658646-7e0298ed-d5d5-404d-8452-0ec353a755ff.png">
<img width="474" alt="Screenshot 2021-07-30 at 15 17 52" src="https://user-images.githubusercontent.com/778799/127658659-75ecf198-ad14-40b6-abbb-f76ce978ff34.png">
tho I am most likely in another part of the world.

<img width="1204" alt="Screenshot_2021-07-30_at_15_20_41" src="https://user-images.githubusercontent.com/778799/127659210-6e41927d-d239-4af0-8bea-c371340bac2a.png">
I would check if the `accept-language` header is consistent with the intended configuration.
If those are fine it might be evidence pointing to something "external". Perhaps there might be "something else" between you and your website of choice. Stuff like proxies or chances, you might be unaware, who are messing around the response?

**Comment by rebron** [comment]
@bozzmob Are you using a VPN?

**Comment by bozzmob** [comment]
@rebron No, I am not using any VPN. This issue is still reproducible. I am on the latest version.

**Comment by unlucio** [comment]
this is very odd, I still don't seem to be able to reproduce it.
Are you sure you're computer I fine? Can you try with another computer on the same network and see what happens?
I'd do a quick test using a virtual machine on the same computer, just to exclude come machine-specific issues.

**Comment by ryanbr** [comment]
Is this still an issue with current Brave? would test toggling via `Prevent sites from fingerprinting me based on my language preferences` brave://settings/shields @bozzmob

**Comment by bozzmob** [comment]
It's not an issue anymore. Closing the issue. Thanks.

**Comment by ryanbr** [comment]
Thanks for the update @bozzmob Apologies for not getting back to you sooner
