### ISSUE TITLE
ADVs from the reward program have wrong and misleading categorisation

### ISSUE THREAD

**Issue by unlucio** [brave/brave-browser#17256]
## Description 
I genuinely love Brave's idea to try to make ADVs actually useful (and maybe less annoying) for everybody. While I generally really despise ADV, I was more than happy to join the Brave Reward program.
That said in all these months the only ADs I got are __ALL__ financial stuff (often borderline scammy).
Checking under [brave://rewards/](brave://rewards/) they're pretty much all misleadingly categorized as "technology & computing", "science" or even "hobbies & interests".

https://user-images.githubusercontent.com/778799/127627664-93773cf6-248b-4db3-bb14-3b5815eda54f.mov

While I am interested in tech/science/etc and would probably be fine (again I'm not a fan of ADV so allowing myself to be targetted by it is a big step out of my comfort zone) with receiving announcements on breakthrough discoveries and innovations, I'm not exactly what I would call a "finance fan or enthusiast" and I really would do great without those ADs.
I dully spent some time during the last 6 months reviewing the ADs I got served and "thumbing down" those I didn't want in the hope I wouldn't be served those kinds of ADs again. Well, I guess I was wrong because that's all I'm still getting.

Before leaving the Rewards program for good I thought it might be useful to report this bad experience as I'm most likely not the only one feeling this way and this whole thing might hinder Brave's adoption and ultimately its mission.

## Steps to Reproduce

   1. Join the Rewards program
   2. Live your life
   3. Notice only finance/crypto Ads been served to you
   4. Open the setting's reward page
   5. Verify all those Ads were actually mistargeted.
   6. Dislike and/or "Mark as inappropriate"
   7. proceed with your life
   8. Verify all you're getting is still the same 💩

## Actual result:
- ADs disguising as science/tech/hobby are actually finance
- Disliking and flagging those ads doesn't make them stop nor change what's been served to the end-user

## Expected result:
- I would expect Ads categorization to be more accurate and faithful to the real content of the AD
- I would expect to be able to influence, and perhaps select, ADs I'm targeted with through the Rewards program so they don't annoy the heck out of me and push me to evaluate other browsers.
- I would also expect Brave to take more care in selecting its advertisers and the ADs it serves to the end-user
- I would expect to be able to trust Brave enough to give it to my old parents and be sure they're not gonna be served potential click bites or scam

## Reproduces how often: 
Every hour for at least 6 months.
It would be more often if I allowed a higher frequency of Ads served to me, of course.

## Version/Channel Information:
Currently using:
Brave	1.27.109 Chromium: 92.0.4515.115 (Official Build) (x86_64)
Revision	48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS	macOS Version 11.5.1 (Build 20G80)
JavaScript	V8 9.2.230.20
User agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,SafetyTip --disable-features=AutofillServerCommunication,HandwritingRecognitionWebPlatformApi,IdleDetection,InterestCohortFeaturePolicy,FledgeInterestGroups,TrustTokens,DirectSockets,SubresourceWebBundles,NetworkTimeServiceQuerying,LangClientHintHeader,LiveCaption,PrivacySandboxSettings,FederatedLearningOfCohorts,EnableProfilePickerOnStartup,TextFragmentAnchor,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,NotificationTriggers,WebOTP,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,SignedExchangePrefetchCacheForNavigations,SignedExchangeSubresourcePrefetch,InterestCohortAPIOriginTrial,FirstPartySets,EnablePasswordsAccountStorage --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/lucio/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations	AdRewardsStudy:NextPaymentDay
EphemeralStorageStudy:Enabled
MacCoreLocationBackendStudy:Enabled
NativeCosmeticFilteringStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled

But I doubt it to be directly linked with the browser its self.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
Well, yes to both, but of course this is not the point, isn't it?

- Is the issue reproducible on the latest version of Chrome?
Kind of not part of chrome's feature set 😆

**Comment by unlucio** [comment]
Perhaps this wasn't the best part to report these kinds of bugs.
Perhaps someone can point me in the right direction?

**Comment by rebron** [comment]
cc: @jsecretan @lukemulks

**Comment by jsecretan** [comment]
Thanks @unlucio for sending this are way.  Right now, we are doing some of this categorization operationally to make sure everybody gets sufficient ad delivery.  But we are reworking our ad serving logic so we can bring this back into alignment.  The engineers are working on this now, and hopefully we'll have an update in a few weeks.

**Comment by tmancey** [comment]
@unlucio some of the improvements which will help are https://github.com/brave/brave-browser/issues/17236 and https://github.com/brave/brave-browser/issues/17319. Thank you for feedback
