### ISSUE TITLE
crash when trying to re-link previous Uphold account in certain case

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#17259]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/15390

In the scenario below I was correctly kicked out of the semi-verified state when upgrading to 1.29.x, but when I tried to re-link my account the browser crashed.

## Steps to Reproduce

1. Using current release version, 1.27.109, clean profile, staging env, enable Rewards, link KYC'd Uphold wallet
2. Manually disconnect from Uphold (from wallet panel)
3. Confirm you are returned to pre-link state (UI, no balance, etc)
4. Link a second (different) KYC'd Uphold wallet
5. Confirm UI appears fine (UI, balance is shown), but logs show 403 error for linking 

example logs:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/3........7/claim
> Method: POST
> Content: {"signedLinkingRequest":"ey...........
> Content Type: application/json; charset=utf-8
[99975:775:0730/084522.183930:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/3.............7/claim
> Result: Failure
> HTTP Code: 403
> Body: {"message":"error linking wallet: unable to link wallets: unable to match wallets: wallets do not match","code":403}
[99975:775:0730/084522.185136:INFO:post_claim_uphold.cc(112)] Forbidden
```

6. Close browser
7. "Upgrade" (rename profile to `Brave-Browser-Nightly`) to 1.29.x
8. Open panel and confirm your 2nd verified, KYC'd wallet from step 4 is no longer connected
9. UI shows pre-link state (UI, no balance) as expected. You still see 403 error in logs, I guess this is ok?

example logs:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/3.........7/claim
> Method: POST
> Content: {"signedLinkingRequest":"eyJ..........
> Content Type: application/json; charset=utf-8
[266:775:0730/084942.492632:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/3............7/claim
> Result: Failure
> HTTP Code: 403
> Body: {"message":"error linking wallet: unable to link wallets: unable to match wallets: wallets do not match","code":403}
```

10. From panel, click on "Verify wallet"
--> brave://rewards/#verify loads in a new tab but it is blank
--> refresh this page, it loads
11. Click on Continue on the modal
12. Click on Uphold
13. Click on "Continue to login" link
--> Browser crashes. Example Uploaded crash report ID: `3cdc2c00-217a-ae06-0000-000000000000`

Note, if in step 10 you click on "Verify wallet" from brave://rewards page not panel, no modal ever opens. There is also no crash. The logs just keep trying to link and you keep getting the 403 response.

## Actual result:

browser crashes

## Expected result:

no crash

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.29.40 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 10.15.7 (Build 19H1217)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @szilardszaloki

**Comment by szilardszaloki** [comment]
This crash itself is originally Gemini-related, but now it gets picked up by all the custodian implementations (it gets resolved by https://github.com/brave/brave-core/pull/9622).
For the Uphold retry-loop in the `PENDING` state, I filed https://github.com/brave/brave-browser/issues/17316.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.29.63 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 10.15.7 (Build 19H1323)
```

Verified STR from description. 
Confirmed 1.28.105 is in the correct state:

Example | Example
----- | -----
<img width="404" alt="Screen Shot 2021-08-18 at 2 31 39 PM" src="https://user-images.githubusercontent.com/28145373/129953038-07b60f1f-9768-4d39-8499-b00abea3aaab.png"> | <img width="467" alt="Screen Shot 2021-08-18 at 2 31 50 PM" src="https://user-images.githubusercontent.com/28145373/129953043-9fac1163-9896-4196-9b02-093bfcc7e206.png">

Logs:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/d..........5/claim
> Method: POST
> Content: {"signedLinkingRequest":"ey.......
[36757:775:0818/143029.086406:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/d.........5/claim
> Result: Failure
> HTTP Code: 403
> Body: {"message":"error linking wallet: unable to link wallets: unable to match wallets: wallets do not match","code":403}
```

Upgrade to 1.29.x.
After opening the panel in 1.29.x I now see the notification from https://github.com/brave/brave-browser/issues/17271 and https://github.com/brave/brave-browser/issues/16468 which is expected. Closing this notification shows the pre-link state, which is also expected.

Example | Example | Example | Example
----- | ----- | ----- | -----
<img width="1195" alt="Screen Shot 2021-08-18 at 2 34 21 PM" src="https://user-images.githubusercontent.com/28145373/129953319-64feb7c4-302f-4e47-a348-14cd28b5055b.png"> | <img width="1190" alt="Screen Shot 2021-08-18 at 2 36 12 PM" src="https://user-images.githubusercontent.com/28145373/129953527-c1bef5ee-d562-4c65-b2a2-c4dd4a306c5b.png"> | <img width="560" alt="Screen Shot 2021-08-18 at 2 52 28 PM" src="https://user-images.githubusercontent.com/28145373/129955617-f921689d-a6ca-43da-ae14-f2254e44b332.png"> | <img width="1195" alt="Screen Shot 2021-08-18 at 2 52 42 PM" src="https://user-images.githubusercontent.com/28145373/129955621-9346229c-410c-4484-bcc3-5cfcddd300ff.png">


Logs do not repeatedly show the 403 error, which is expected now per https://github.com/brave/brave-browser/issues/17265.

Logs:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/d........5/claim
> Method: POST
> Content: {"signedLinkingRequest":"eyJi.....
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/d.........5/claim
> Result: Failure
> HTTP Code: 403
> Body: {"message":"error linking wallet: unable to link wallets: unable to match wallets: wallets do not match","code":403}
[36901:775:0818/143414.889469:INFO:post_claim_uphold.cc(123)] Forbidden
[36901:775:0818/143414.890496:VERBOSE1:uphold.cc(188)] Disconnecting wallet
```

I clicked on "Verify wallet" from panel and brave://rewards/#verify opened in a new tab (not blank).
Clicked Continue, then selected Uphold.
Clicked on "Continue to login" link and confirmed no crash.

Note - still unable to connect this second account which is expected since verifying a single wallet with multiple of the same custodian is not allowed.

------------
