### ISSUE TITLE
Google Drive can't do upload long videos

### ISSUE THREAD

**Issue by victorfernandesraton** [brave/brave-browser#17262]
## Description 
I try to upload a large vídeo file in mp4 format and google drive but that informed to was corrupted

## Steps to Reproduce
   1. Open the google drive folder 
   2. Click with the right button and select "Upload file"
   3. Select a file to have more than 100MB size (mp4 video)

## Brave version (brave://version info)
Version 1.27.109 Chromium: 92.0.4515.115 (Official Version) 64 bits

**Comment by rebron** [comment]
@victorfernandesraton Have you tried uploading other large files to Google Drive and still wasn't working or was it specific to the one file?

**Comment by victorfernandesraton** [comment]
@rebron I tried different files and formats and it's still crashing in file videos mp4 only. I tr upload these files in other browsers and it's work
