### ISSUE TITLE
Estimated pending rewards on NTP Rewards widget suddenly decreasing or inaccurate

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17267]
## Description

Users reporting that the estimated pending rewards on the NTP Rewards widget is suddenly decreasing or showing incorrect numbers. However, the counter in brave://rewards (Rewards settings) is working as expected. 

https://www.reddit.com/r/BATProject/comments/otplul/rewards_number_on_dashboard_not_going_up_even/h70lap4/?context=3

**Comment by zenparsing** [comment]
One possibility might be that the NTP widget is caching data differently that the rewards page.

**Comment by tmancey** [comment]
This is likely resolved by https://github.com/brave/brave-browser/issues/16028

**Comment by LaurenWags** [comment]
cc @btlechowski for when you're testing https://github.com/brave/brave-browser/issues/16028

**Comment by LaurenWags** [comment]
added `release-notes/exclude` as this is covered by #16028 per https://github.com/brave/brave-browser/issues/17267#issuecomment-989878901.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
<html>
<body>
<!--StartFragment-->

Brave | 1.35.99 Chromium: 98.0.4758.87 (Official Build) (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1503)

<!--EndFragment-->
</body>
</html>
```
- Verification notes can be found here https://github.com/brave/brave-browser/issues/16028#issuecomment-1011299595
