### ISSUE TITLE
LastPass login issue

### ISSUE THREAD

**Issue by lennardboehnke** [brave/brave-browser#1726]
## Description 
Cannot log into LastPass plugin on Brave Browser.

## Steps to Reproduce

   1.  Install Brave and LastPass Plugin
   2. Try to log in

## Actual result:
Gets stuck on the login screen.

## Expected result:
Should have logged me in.

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
OS | Mac OS X
JavaScript | V8 7.0.276.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36

**Comment by kjozwiak** [comment]
Thanks for the report @@lennardboehnke! I managed to login into my LastPass account on macOS and Win 10 x64 using `0.55.18`:

<img width="513" alt="screen shot 2018-10-19 at 4 22 05 pm" src="https://user-images.githubusercontent.com/2602313/47241918-526cb080-d3bb-11e8-93c6-e6d23e8129fb.png">

Is this the extension that you're attempting to install?

https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd/

> Gets stuck on the login screen.

What do you mean by getting stuck? Are you seeing the login screen and just can't login? Is the login screen loading?

**Comment by kjozwiak** [comment]
@itstheandre can you still reproduce the above issue with the latest LastPass extension on the current release?
