### ISSUE TITLE
Displays new tab ads for the wrong region

### ISSUE THREAD

**Issue by matachi** [brave/brave-browser#17264]
## Description 

I live in Sweden, and even when I'm running my browser in Swedish, it displays new tab page ads for the wrong region that I don't receive any BATs for. I would prefer to be able to run the browser in English, since I prefer to run all of my software in English. But even when I switch Brave to Swedish, the bug persist with it displaying ads for the wrong region.

Here you can see that I have selected Swedish (`svenska`) in Brave on my Android phone:

![Screenshot_20210730-121823](https://user-images.githubusercontent.com/980838/127668284-c7d2a4ab-9fc3-4bd9-94b5-131cb8bd3a52.jpg)

I made that setting visible by turning on the flag `#desktop-detailed-language-settings` on `brave://flags`.

On the ads page I can see that I have seen 108 ads:

![Screenshot_20210730-121805](https://user-images.githubusercontent.com/980838/127668562-9461086b-c122-4cf0-944a-c0cba4f3df2a.jpg)

But when I trigger a new tab page ad, I can see on the above page that it doesn't increase. Here's an example of an ad:

![Screenshot_20210730-121756](https://user-images.githubusercontent.com/980838/127668654-73878b99-73ff-4c9b-b8ab-d445436c2d9a.jpg)

However, when checking on https://sampson.codes/brave/ads/my_region/, there's no ad campaign for the site kusama.network, so I don't understand why those ads are being shown to me.

The same problem happens on my laptop, where I'm also being shown ads that I don't receive BATs for:

![image](https://user-images.githubusercontent.com/980838/127669234-99dbd380-ef96-4481-9cae-2f2f5010df61.png)

I reported the issue previously here: https://github.com/brave/brave-browser/issues/17159 I tried the suggested workaround of changing the `LANG` environment variable, but it didn't help, see my comment: https://github.com/brave/brave-browser/issues/17159#issuecomment-886764406.

Ping @tmancey 

## Steps to Reproduce

   1. Change the browser's language to Swedish and be in Sweden.
   2. Open new tabs until receiving a new tab page ad.
   3. Check on https://sampson.codes/brave/ads/my_region/ if the ad is available in the region. If not, it doesn't pay, even if it was shown to you.

## Actual result:

Being shown ads that aren't for Sweden.

## Expected result:

Only be shown ads that I receive BATs for.

## Reproduces how often: 

Easily reproduced. Seems like most ads that I am shown on the new tab page are for some other region.

## Desktop Brave version:

```
Brave | 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Linux
JavaScript | V8 9.2.230.20
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-crashpad --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PasswordImport,ReducedReferrerGranularity,WebUIDarkMode,AutoupgradeMixedContent,SafetyTip,PrefetchPrivacyChanges,LegacyTLSEnforced,DnsOverHttps --disable-features=IdleDetection,HandwritingRecognitionWebPlatformApi,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,FledgeInterestGroups,InterestCohortFeaturePolicy,EnableProfilePickerOnStartup,TextFragmentAnchor,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,LangClientHintHeader,AutofillServerCommunication,LiveCaption,NotificationTriggers,WebOTP,PrivacySandboxSettings,FederatedLearningOfCohorts,SignedExchangeSubresourcePrefetch,DirectSockets,TrustTokens,NetworkTimeServiceQuerying,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,InterestCohortAPIOriginTrial,FirstPartySets,EnablePasswordsAccountStorage --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/matachi/.config/BraveSoftware/Brave-Browser/Default
Variations | AdRewardsStudy:NextPaymentDayEphemeralStorageStudy:EnabledNativeCosmeticFilteringStudy:EnabledPermissionLifetimeReleaseStudy:Enabled
```

## Android Device details:
   - Install type (ARM, x86):

From the Play store.

   - Device type (Phone, Tablet, Phablet):

Phone. It's a OnePlus Nord.

   - Android version:

Oxygen OS 11.1.4.4.AC01BA based on Android 11.

```
Brave | 1.26.77 Chromium: 91.0.4472.164 (Officiell version) (64 bitar)
-- | --
Version | 541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569}
OS | Android 11; Build/RP1A.201005.001
Google Play-tjänster | SDK=12451000; Installed=212418046; Access=3p
JavaScript | V8 9.1.269.39
Användaragent | Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Mobile Safari/537.36
Kommandorad | --disable-fre --use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --use-mobile-user-agent --enable-viewport --validate-input-event-stream --enable-longpress-drag-selection --touch-selection-strategy=direction --main-frame-resizes-are-orientation-changes --disable-composited-antialiasing --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,PrefetchPrivacyChanges,WebUIDarkMode,SafetyTip,AutoupgradeMixedContent,PasswordImport,ReducedReferrerGranularity --disable-features=AutofillServerCommunication,TextFragmentAnchor,WebNFC,HandwritingRecognitionWebPlatformApi,IdleDetection,TrustTokens,DirectSockets,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,SignedExchangeSubresourcePrefetch,InterestCohortFeaturePolicy,SignedExchangePrefetchCacheForNavigations,OfflinePagesPrefetching,NetworkTimeServiceQuerying,SubresourceWebBundles,NotificationTriggers,WebOTP,InterestFeedV2,FederatedLearningOfCohorts,LiveCaption,FledgeInterestGroups,Translate,LangClientHintHeader,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,InterestCohortAPIOriginTrial,InterestFeedContentSuggestions,FirstPartySets,MobileIdentityConsistency --flag-switches-begin --enable-features=LegacyTLSEnforced,PrefetchPrivacyChanges,WebUIDarkMode,SafetyTip,AutoupgradeMixedContent,PasswordImport,ReducedReferrerGranularity,AndroidDarkSearch,DarkenWebsitesCheckboxInThemesSetting,DetailedLanguageSettings,WebContentsForceDark --flag-switches-end
Sökväg till körbar fil | Filen eller katalogen finns inte
Profilsökväg | /data/user/0/com.brave.browser/app_chrome/Default
Varianter | AdRewardsStudy:NextPaymentDayEphemeralStorageStudy:EnabledForceDarkVariations:AboutFlagsPermissionLifetimeReleaseStudy:EnabledVulkanStudy:Disabled
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 

Have only tried the current release.

- Can you reproduce this issue with the beta channel? 

Have not tried.

- Can you reproduce this issue with the nightly channel? 

Have not tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by matachi** [comment]
@tmancey Sounds like a great solution to get the locale from the same place as the ads reward validation gets it from :+1:

**Comment by tmancey** [comment]
Closing as stale, please let us know the issue reoccurs.
