### ISSUE TITLE
Full screening PWA causes artifacts

### ISSUE THREAD

**Issue by youssef20031** [brave/brave-browser#17260]
## Description 

When I full screen a PWA  the extensions puzzle icon appears in content 

## Steps to Reproduce

   1. Install PWA
   2. Press F11

## Actual result:

![Screenshot 2021-07-30 160639](https://user-images.githubusercontent.com/43968405/127665127-49b20807-10d1-4ead-b8ee-ba8214756333.png)

## Expected result:
No Icon

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Windows 10 OS Version 2009 (Build 19043.1151)
JavaScript | V8 9.2.230.20
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel? 
- No
- Can you reproduce this issue with the nightly channel? 
- No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- N/A

**Comment by youssef20031** [comment]
Fixed with update 1.27.111. It seamed to be a chromium issue

**Comment by bsclifton** [comment]
Thanks for the update, @youssef20031!
