### ISSUE TITLE
Chromium 92 (And Brave 1.27) currently broken when using systemd-resolved (Systemd 249)

### ISSUE THREAD

**Issue by alosarjos** [brave/brave-browser#17263]
## Description 
If the user is using systemd-resolved for name resolution the pages freezes / can't find the domain name

## Steps to Reproduce

   1. Get a system using systemd-resolved on Systemd 249
   2. Install latest Chrome/Brave
   3. Try to go to any website

## Actual result:
Freezes and domains not resolved

## Expected result:
Should work just fine

## Reproduces how often: 
Always

## Brave version
1.27.109

## Other Additional Information:

This issue has been fixed on upstream Chromium and I think a new Chromium version is scheduled for next week.

I'm just putting here the issue since the update on the Arch Linux AUR `brave-bin` package is being frozen on 1.26 until this is fixed. Hoping we can get a new Brave release rebased on the fixed Chromium ASAP

The issue on Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1221442

**Comment by alerque** [comment]
This doesn't *just* affect Arch by the way (although that's where I'd like to see it work), the underlying Chromium issue is *anything* with `systemd-resolved`. Other resolver work such as unbound, or a local bind install, or NetworkManager, etc.

**Comment by alosarjos** [comment]
Just to be clear, the `brave-bin` package in AUR comes from the precompiled zip provided from the releases here on GitHub.

**Comment by duhdugg** [comment]
The nss-resolve module is the other piece of the puzzle that is required to reproduce this issue, so not all distros using systemd-resolved will be affected.

https://bugs.chromium.org/p/chromium/issues/detail?id=1221442#c11

**Comment by alosarjos** [comment]
Closing this issue since it's fixed on 1.27.111
