### ISSUE TITLE
do not show "Your wallet is verified!" message when reconnecting after natural disconnect

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#17278]
## Description 

Per discussion in https://bravesoftware.slack.com/archives/CB0KCRCQN/p1627659102017500, we should not show the "Your wallet is verified!" message/notification when a user is reconnecting after natural disconnect.

## Steps to Reproduce

1. Clean profile 1.29.x, staging env
2. Enable Rewards
3. Link KYC'd, verified Uphold account
4. Simulate "natural" disconnect by revoking Brave-Browser app authorization on Uphold site
5. Confirm UI shows "Disconnected"/no balance
6. Click on "Disconnected" and reauthorize Uphold
7. You are successful in re-auth and you get this notification

Also reproduces in this scenario:
1. Using current release version, 1.27.109, clean profile, staging env, enable Rewards, link KYC'd Uphold wallet
2. Simulate "natural" disconnect by revoking Brave-Browser app authorization on Uphold site
3. Close browser
4. "Upgrade" (rename profile to `Brave-Browser-Nightly`) to 1.29.x
5. Confirm your verified, KYC'd wallet is still in Disconnected status after upgrade (appropriate UI, no Uphold balance shown)
6. Click on "Disconnected" and re-auth with Uphold

## Actual result:

Your wallet is verified notification:
<img width="417" alt="Screen Shot 2021-07-30 at 11 26 04 AM" src="https://user-images.githubusercontent.com/28145373/127707342-5b823f45-248f-4857-a672-f8dcfbf5ccb3.png">

## Expected result:
No notification in this case

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.29.40 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5.1 (Build 20G80)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @szilardszaloki

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in `Windows 10 x64 - 1.29.58`

**Comment by szilardszaloki** [comment]
Hey @GeetaSarvadnya!
FYI: https://github.com/brave/brave-core/pull/9738 is not getting uplifted to `1.29.x`.

**Comment by GeetaSarvadnya** [comment]
@szilardszaloki Looks like the issue is not yet fixed, verified the issue in the nightly build `1.31.12`

```
Brave | 1.31.12 Chromium: 93.0.4577.58 (Official Build) nightly (64-bit)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

```

**Comment by GeetaSarvadnya** [comment]
Verified the issue in the following build

```
Brave | 1.30.59 Chromium: 93.0.4577.58 (Official Build) beta (64-bit)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

```
Verified the STR from the description, the issue is not yet fixed hence logged a follow-up issue https://github.com/brave/brave-browser/issues/17807

**Comment by szilardszaloki** [comment]
@GeetaSarvadnya That's odd. Just took a look with `1.31.10` and it was working fine. Let me rebase and try that again!

**Comment by szilardszaloki** [comment]
@GeetaSarvadnya Just tried with `1.31.14 Chromium: 93.0.4577.63` and actually it's working fine. I'll reach out to you via Slack.
