### ISSUE TITLE
Show error notification when user tries to connect second custodian account in `wallet generation` flow

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17271]
## Description

When a user tries to connect a second Uphold/custodian account in the `wallet generation flow`, no error modal is shown. 

## Solution

The relevant error modal should show for the "2 custodian accounts to 1 browser" error case.

**Comment by szilardszaloki** [comment]
We're creating a notification for the "ambiguous Uphold accounts" case here and creating the modals for all the notifications in https://github.com/brave/brave-browser/issues/16652 in one go (deliberated with @Miyayes).

**Comment by LaurenWags** [comment]
Verification passed with

```
Brave | 1.29.63 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 10.15.7 (Build 19H1323)
```

Verified scenarios from https://github.com/brave/brave-core/pull/9669#issuecomment-896809506

<details>
<summary>Upgrade Case</summary>

Confirmed 1.28.105 is in the correct state (see https://github.com/brave/brave-core/pull/9669#issuecomment-896809506 as a guide)

Example | Example
----- | -----
<img width="404" alt="Screen Shot 2021-08-18 at 2 31 39 PM" src="https://user-images.githubusercontent.com/28145373/129953038-07b60f1f-9768-4d39-8499-b00abea3aaab.png"> | <img width="467" alt="Screen Shot 2021-08-18 at 2 31 50 PM" src="https://user-images.githubusercontent.com/28145373/129953043-9fac1163-9896-4196-9b02-093bfcc7e206.png">

Logs:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/d..........5/claim
> Method: POST
> Content: {"signedLinkingRequest":"ey.......
[36757:775:0818/143029.086406:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/d.........5/claim
> Result: Failure
> HTTP Code: 403
> Body: {"message":"error linking wallet: unable to link wallets: unable to match wallets: wallets do not match","code":403}
```

Upgrade to 1.29.x.
After opening the panel in 1.29.x I now see the expected notification. Closing this notification shows the pre-link state, which is also expected.

Example | Example 
----- | ----- 
<img width="1195" alt="Screen Shot 2021-08-18 at 2 34 21 PM" src="https://user-images.githubusercontent.com/28145373/129953319-64feb7c4-302f-4e47-a348-14cd28b5055b.png"> | <img width="1190" alt="Screen Shot 2021-08-18 at 2 36 12 PM" src="https://user-images.githubusercontent.com/28145373/129953527-c1bef5ee-d562-4c65-b2a2-c4dd4a306c5b.png">


Logs do not repeatedly show the 403 error, which is expected now per https://github.com/brave/brave-browser/issues/17265.

Logs:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/d........5/claim
> Method: POST
> Content: {"signedLinkingRequest":"eyJi.....
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/d.........5/claim
> Result: Failure
> HTTP Code: 403
> Body: {"message":"error linking wallet: unable to link wallets: unable to match wallets: wallets do not match","code":403}
[36901:775:0818/143414.889469:INFO:post_claim_uphold.cc(123)] Forbidden
[36901:775:0818/143414.890496:VERBOSE1:uphold.cc(188)] Disconnecting wallet
```

Additionally, looking at brave://rewards-internals I can now see that I am no longer in the "PENDING" state, I have moved (as expected) to "NOT_CONNECTED".

Example | Example
----- | ----- 
<img width="560" alt="Screen Shot 2021-08-18 at 2 52 28 PM" src="https://user-images.githubusercontent.com/28145373/129955617-f921689d-a6ca-43da-ae14-f2254e44b332.png"> | <img width="1195" alt="Screen Shot 2021-08-18 at 2 52 42 PM" src="https://user-images.githubusercontent.com/28145373/129955621-9346229c-410c-4484-bcc3-5cfcddd300ff.png">

</details>

<details>
<summary>Clean Profile</summary>

Confirmed that after attempting to link the second KYC'd Uphold account I do not see the 403 errors repeatedly in the logs:

```
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/7.............4/claim
> Result: Failure
> HTTP Code: 403
> Body: {"message":"error linking wallet: unable to link wallets: unable to match wallets: wallets do not match","code":403}
[37143:775:0818/154412.656110:VERBOSE9:logging_util.cc(137)] 
[ RESPONSE HEADERS ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/7........4/claim
[37143:775:0818/154412.656944:INFO:post_claim_uphold.cc(123)] Forbidden
[37143:775:0818/154412.657703:VERBOSE1:uphold.cc(188)] Disconnecting wallet
```

Confirmed message is shown on panel.
Confirmed UI returned to NOT_CONNECTED state.

Example | Example | Example | Example
----- | ----- | ----- | -----
<img width="1196" alt="Screen Shot 2021-08-18 at 3 52 05 PM" src="https://user-images.githubusercontent.com/28145373/129963197-d93b0944-0a03-4b7c-a5fe-4eec6e20e3cd.png"> | <img width="415" alt="Screen Shot 2021-08-18 at 3 52 12 PM" src="https://user-images.githubusercontent.com/28145373/129963204-f584931d-3a5a-47ef-8972-c829b990e80e.png"> | <img width="528" alt="Screen Shot 2021-08-18 at 3 52 22 PM" src="https://user-images.githubusercontent.com/28145373/129963210-d3de3ddc-cdb5-4b7a-8850-7a566f439efa.png"> | <img width="1192" alt="Screen Shot 2021-08-18 at 3 52 34 PM" src="https://user-images.githubusercontent.com/28145373/129963217-929f842e-7aec-45d7-a861-3e8eac4d902f.png">

</details>

------------
