### ISSUE TITLE
Label ad type in 30-day Ads History view (sponsored image, notification, display ad, etc.) 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17277]
## Description

We should add labels in the 30-day Ads History view that specify whether the ad was a:

* Sponsored image
* Notification
* Display Ad

cc: @codybanxs Simple design may be required.

**Comment by tmancey** [comment]
@Miyayes closing as duplicate of https://github.com/brave/brave-browser/issues/12692, thanks
