### ISSUE TITLE
Flash not properly blocked after clearing browser data

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#1727]
## Description 
Default Flash UI flow is described here: https://github.com/brave/brave-core/pull/116

After clearing browser data, Flash UI flow is identical to Chromium, i.e. not blocked by default, only click-to-play.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.56.9 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows 7 x64

Used test plan from https://github.com/brave/brave-browser/issues/1727#issuecomment-436697429

**Comment by kjozwiak** [comment]
Added the `OS/macOS` &  `OS/Windows` labels due to Flash not working with b-c on Linux. @srirambv created https://github.com/brave/brave-browser/issues/1562.
