### ISSUE TITLE
Remove tabId used in panel handler for connect with site requests

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#17273]
Follow-up of https://github.com/brave/brave-core/pull/9443
We could probably drop the usage of tabID now, see below for the original review comment.
review comment:
```
since the webui is tied to a webcontents now, I'm wondering if we should drop tabId and pass the active webcontents to the Handler when it's created.
then it will just be origin/addresses so they'll be identical requests
and we know the webcontents because the webui is tied to the same webcontents for its entire lifetime
```

**Comment by yrliou** [comment]
Test plan is specified in the linked PR.

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.34.67 Chromium: 97.0.4692.56 (Official Build) beta (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)
```

Verified test plan from https://github.com/brave/brave-core/pull/11243
Created 2 wallet accounts:
Acct 1: `0x74...`
Acct 2: `0x43...`
Confirmed prompts contained expected origins:
Website 1 - clifton.io
Website 2 - rebron.org
Accepted prompt on clifton.io w/ acct 2 (`0x43...`)
Accepted prompt on rebron.org w/ acct 1 (`0x74...`)
Confirmed brave://settings/content/ethereum shows website 1 + acct 2 and website 2 + acct 1

Step 1 | Step 3 | Step 5 | Step 7 | Step 8
----- | ----- | ----- | ----- | -----
<img width="835" alt="step 1 - 2 wallet accts" src="https://user-images.githubusercontent.com/28145373/146797980-89949595-e347-4c3c-a155-7799e293f278.png"> | <img width="1190" alt="Step 3 - website 1" src="https://user-images.githubusercontent.com/28145373/146797985-96e41560-dcaa-481c-aaa0-2fd4da3b5dce.png"> | <img width="1190" alt="Step 5 - website 2" src="https://user-images.githubusercontent.com/28145373/146797994-e2ed241c-31b4-4108-a448-0d8478e181c0.png"> | <img width="1192" alt="Step 7" src="https://user-images.githubusercontent.com/28145373/146798010-25cf66a6-3f89-4387-8f13-993e5f45c170.png"> | <img width="1193" alt="Step 8" src="https://user-images.githubusercontent.com/28145373/146798024-5c34407a-3603-4757-8dbe-f38c04c31b48.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified steps from [brave/brave-core#11243](https://github.com/brave/brave-core/pull/11243)
- Verified correct account is linked with domain name 

Accounts | Site 1 Acc1 connect  | Site 2 Acc1 connect | Site 1 Acc 2 connect | Ethereum Connections
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/148015662-18bfefe5-24a1-4b3a-9c26-79b3593305e3.png) | ![image](https://user-images.githubusercontent.com/17010094/148014993-56b5618e-6cdb-4981-8f13-0039a821f740.png) | ![image](https://user-images.githubusercontent.com/17010094/148015162-1d5ea9f2-1e22-4b0d-bdf5-33cc890b55c2.png) | ![image](https://user-images.githubusercontent.com/17010094/148015275-5bdf54c7-f956-4802-902d-989ed39a8c2c.png) | ![image](https://user-images.githubusercontent.com/17010094/148015440-6a95b635-f2e8-4ed8-90e2-1f5942f08968.png)

---------
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Linux

- Verified steps from [brave/brave-core#11243](https://github.com/brave/brave-core/pull/11243)
- Verified correct account is linked with domain name 

Accounts | Site 1 Acc1 connect  | Site 2 Acc1 connect | Site 1 Acc 2 connect | Ethereum Connections
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/148016237-871a416d-e1b1-4cd3-b195-5ffe3eee5260.png) | ![image](https://user-images.githubusercontent.com/17010094/148016297-eaa435fe-fe3c-4d92-b17a-1c0719441860.png) | ![image](https://user-images.githubusercontent.com/17010094/148016319-b45e4dd1-ad83-48ba-8820-a7ee983e5b7f.png) | ![image](https://user-images.githubusercontent.com/17010094/148016355-62bf9082-2aaf-4545-bf57-9c7df62e7942.png) | ![image](https://user-images.githubusercontent.com/17010094/148016373-a6892d2c-ff7e-432a-b576-8f13e8fe392b.png)
