### ISSUE TITLE
Gemini widget, in the balance display show currencies that a user owns

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#17287]
## Description 

In a connected Gemini widget Balance display, only show the currencies/assets where there's a value or in other words currencies that a user has holdings.

## Steps to Reproduce

   1. Connect an account to the Gemini widget on the new tab page.
   2. Go to the balance view.
   3. Notice that all assets are listed but should only show the assets where a user has a balance or holdings.

## Actual result:

<img width="283" alt="Screen Shot 2021-08-01 at 3 54 17 PM" src="https://user-images.githubusercontent.com/5951041/127787779-2f6a7021-635e-41ee-914a-7123830189be.png">

## Expected result:
Just the currencies that a user owns.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.28.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)
-- | --
Revision | `0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}`
OS | Windows 10 OS Version 2009 (Build 19043.1110)

- Verified upgrading to 1.28.106 only shows currencies that have balance

1.28.105 | 1.28.106
-- | --
![image](https://user-images.githubusercontent.com/17010094/130009589-8e5b6626-765d-4f6b-b03c-68fb2f462d11.png) | ![image](https://user-images.githubusercontent.com/17010094/130008606-bfb7ea45-36c8-4f5e-b35a-3d56b878a264.png)

-------
Verification passed on 

Brave | 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)
-- | --
Revision | `0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}`
OS | Linux

- Verified upgrading to 1.28.106 only shows currencies that have balance

1.28.105 | 1.28.106
-- | --
![image](https://user-images.githubusercontent.com/17010094/130009230-a7e147e9-36e2-41e3-b4fa-9d5448027e7e.png) | ![image](https://user-images.githubusercontent.com/17010094/130009007-c230f05b-1c09-487e-aa91-d5f027839e6e.png)


-------

Verification passed on 

Brave | 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
-- | --
Revision | `0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}`
OS | macOS Version 10.15.7 (Build 19H114)

- Verified upgrading to 1.28.106 only shows currencies that have balance

1.28.105 | 1.28.106
-- | --
 ![image](https://user-images.githubusercontent.com/17010094/130008731-44c6d34d-a490-47a1-b988-8d0587584a63.png) | ![image](https://user-images.githubusercontent.com/17010094/130009085-bab7e3e0-7b27-470e-a2a2-24dec57cb18b.png)
