### ISSUE TITLE
Referral download links for publishers point to the download of the old "Brave.app" browser app

### ISSUE THREAD

**Issue by dekaru** [brave/brave-browser#1728]
## Description 
Referral download links for publishers currently point to the download of the old "Brave.app" browser instead of the new "Brave Browser.app"

## Steps to Reproduce
Follow a referral download link for the Brave browser, such as 
https://brave.com/reb420

## Actual result:
On a Mac, the page takes you to a download of a .pkg installer  which installs the old "Brave.app" browser.

## Expected result:
A download of a .dmg image which contains the new "Brave Browser.app" browser, based on Chromium.

## Reproduces how often: 
Every time.

**Comment by kjozwiak** [comment]
Thanks for the report @dekaru! We're currently working on getting the referral program working with the newer builds. Should be working sometime next week 👍 CCing @aekeus.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/brave-referal-old-download-link/35565

**Comment by kjozwiak** [comment]
Win 10 x64 - PASSED

* installed using `BraveBrowserSetup-KAM253.exe`
* ensured that `promoCode` was being created under `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* waited 10-30s and ensured `promoCode` was removed from `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* checked `Local State` for `{"brave":{"referral":{"download_id":"75cfc36d-8a8d-4883-bda5-adcc1b5aa1a4","promo_code":"KAM253"}}`

Win 10 x86 - PASSED

* installed using `BraveBrowserSetup-86-KAM253.exe`
* ensured that `promoCode` was being created under `C:\Users\kjozwiakBrave\AppData\Local\BraveSoftware\Brave-Browser\User Data\`
* waited 10-30s and ensured `promoCode` was removed from `C:\Users\kjozwiakBrave\AppData\Local\BraveSoftware\Brave-Browser\User Data\`
* checked `Local State` for `{"brave":{"referral":{"download_id":"9d3aa2c6-8a5b-4c27-9aa2-67979c8888cd","promo_code":"KAM253"}}`

Win 8.1 x64 - PASSED

* installed using `BraveBrowserSetup-KAM253.exe`
* ensured that `promoCode` was being created under `C:\Users\kamil\AppData\Local\BraveSoftware\Brave-Browser\User Data\`
* waited 10-30s and ensured `promoCode` was removed from `C:\Users\kamil\AppData\Local\BraveSoftware\Brave-Browser\User Data\`
* checked `Local State` for `{"brave":{"referral":{"download_id":"c8da7daa-e980-44c4-a3f0-1335df6cb9fd","promo_code":"KAM253"}}`

Win 7 x86 - PASSED

* installed using `BraveBrowserSetup-86-KAM253.exe`
* ensured that `promoCode` was being created under `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data\`
* waited 10-30s and ensured `promoCode` was removed from C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data\`
* checked `Local State` for `{"brave":{"referral":{"download_id":"896026da-4aae-495c-8b7e-32c93d7af4b1","promo_code":"KAM253"}}`

macOS 10.13.6 x64 - PASSED

* installed using `Brave-Browser-KAM253.pkg`
* ensured that `promoCode` was being created under `~/Library/Application\ Support/BraveSoftware/Brave-Browser/`
* launched Brave
* waited 10-30s and ensured `promoCode` was removed from `~/Library/Application\ Support/BraveSoftware/Brave-Browser/`
* checked `Local State` for `{"brave":{"referral":{"download_id":"fe1126e4-58cc-435a-a5ef-043927eec8d0","promo_code":"KAM253"}}`

**Comment by bbondy** [comment]
I think this should be closed now, closing.

**Comment by kjozwiak** [comment]
Win 10 x64 - **PASSED**

website: https://brave.com/kjo527
* downloaded `BraveBrowserSetup-KJO527.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"ac827f2f-20ad-43b6-a177-ecaf7493728f","promo_code":"KJO527"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

YT: https://brave.com/kam253
* downloaded `BraveBrowserSetup-KAM253.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"027d757b-9bae-4f8b-8571-19f0dfbfdb2c","promo_code":"KAM253"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Twitch: https://brave.com/red194
* downloaded `BraveBrowserSetup-RED194.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"7eb4e9df-0a00-4652-a14b-27a9b39f6b3b","promo_code":"RED194"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Win 10 x86 - **PASSED**

website: https://brave.com/kjo527
* downloaded `BraveBrowserSetup32-KJO527.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (32-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiakBrave\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"06109baa-81de-4ba9-bb87-7048d514d61c","promo_code":"KJO527"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

YT: https://brave.com/kam253
* downloaded `BraveBrowserSetup32-KAM253.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (32-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiakBrave\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"f6f2df1a-76d3-4dd4-bdfa-1fa241cc1236","promo_code":"KAM253"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Twitch: https://brave.com/red194
* downloaded `BraveBrowserSetup32-RED194.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (32-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiakBrave\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"758f3508-e08a-4a54-b606-c229c49bc65b","promo_code":"RED194"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Win 8.1 x64 - **PASSED**

website: https://brave.com/kjo527
* downloaded `BraveBrowserSetup-KJO527.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kamil\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"f6d257cb-1434-4c43-abd3-708b480bf507","promo_code":"KJO527"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

YT: https://brave.com/kam253
* downloaded `BraveBrowserSetup-KAM253.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kamil\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"e7b34f94-99e7-4035-8032-e5b514d96461","promo_code":"KAM253"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Twitch: https://brave.com/red194
* downloaded `BraveBrowserSetup-RED194.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kamil\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"18fe5cdc-f128-47b1-aa72-3d97b8567ecc","promo_code":"RED194"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Win 7 x64 - **PASSED**

website: https://brave.com/kjo527
* downloaded `BraveBrowserSetup-KJO527.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"5f26fe40-40f8-48d3-b70e-6d22e2195912","promo_code":"KJO527"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

YT: https://brave.com/kam253
* downloaded `BraveBrowserSetup-KAM253.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"8b4a665e-1740-4702-a0ca-e5b69ed7349c","promo_code":"KAM253"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Twitch: https://brave.com/red194
* downloaded `BraveBrowserSetup-RED194.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"cf994419-66f2-4a7a-8715-4882c57bbee8","promo_code":"RED194"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Win 7 x86 - **PASSED**

website: https://brave.com/kjo527
* downloaded `BraveBrowserSetup32-KJO527.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (32-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"436d0ea5-014b-4396-8530-0023c6472ad5","promo_code":"KJO527"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

YT: https://brave.com/kam253
* downloaded `BraveBrowserSetup32-KAM253.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (32-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"02e13af4-7582-4280-a454-ba71db40ebf8","promo_code":"KAM253"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Twitch: https://brave.com/red194
* downloaded `BraveBrowserSetup32-RED194.exe` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (32-bit)` was being installed
* ensured `promoCode` was added into `C:\Users\kjozwiak\AppData\Local\BraveSoftware\Brave-Browser\User Data`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"a7202e34-65c4-4f42-aca6-0340b0710930","promo_code":"RED194"}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

macOS 10.13.6 x64 - **PASSED**

website: https://brave.com/kjo527
* downloaded `Brave-Browser-KJO527.pkg` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `~/Library/Application\ Support/BraveSoftware/Brave-Browser/`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"4c05afaf-2a4e-456a-919c-9099197d5e8f","promo_code":"KJO527"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

YT: https://brave.com/kam253
* downloaded `Brave-Browser-KAM253.pkg` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `~/Library/Application\ Support/BraveSoftware/Brave-Browser/`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"89f01109-f924-4334-9e26-296100811fd1","promo_code":"KAM253"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home

Twitch: https://brave.com/red194
* downloaded `Brave-Browser-RED194.pkg` and made sure `0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)` was being installed
* ensured `promoCode` was added into `~/Library/Application\ Support/BraveSoftware/Brave-Browser/`
* ensured that `promoCode` was removed and `{"brave":{"referral":{"download_id":"d5a00196-2c6a-443e-8e70-dd55ddce176c","promo_code":"RED194"}}` was added into `Local State`
* ensured that `Downloaded` was incremented under https://publishers.basicattentiontoken.org/publishers/home
