### ISSUE TITLE
`Help improve Brave's features and performance` is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#17289]
## Steps to Reproduce

1. Run Brave in PL polish locale
1. Open `brave://settings/privacy`

## Actual result:

`Help improve Brave's features and performance` is not translated
![image](https://user-images.githubusercontent.com/34715963/127790352-8e9562d8-21e0-481f-8c7e-f9c6fa7d122b.png)
![image](https://user-images.githubusercontent.com/34715963/127790342-2d3c3c83-25ec-4292-b452-ca082b928bda.png)

## Expected result:
`Help improve Brave's features and performance` is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.28.98 Chromium: 92.0.4515.115 (Official Build) beta (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Ubuntu 18.04 LTS

Brave | 1.29.42 Chromium: 92.0.4515.115 (Official Build) nightly (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Linux

cc @mkarolin @rebron @brave/legacy_qa

**Comment by kjozwiak** [comment]
@btlechowski now that we uplifted https://github.com/brave/brave-core/pull/9676, mind checking if the above has been addressed once the next `1.28.x` RC build is ready?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/128861445-1698a7cb-af6f-4dae-b199-60214aa64546.png)
