### ISSUE TITLE
Wrong Polish translation for `View Sync Code`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#17288]
## Steps to Reproduce

1. Run Brave in Polish PL locale
1. Create an empty sync chain

## Actual result:

`Pokaż nowy kod synchronizacji`
![image](https://user-images.githubusercontent.com/34715963/127789654-bda329f8-3d80-4593-8f0e-468c6a7c28eb.png)
![image](https://user-images.githubusercontent.com/34715963/127789778-fc279a14-0550-4f27-871b-fdb9f5de1dbb.png)

## Expected result:
`Pokaż kod synchronizacji`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Verification passed on

Brave | 1.28.98 Chromium: 92.0.4515.115 (Official Build) beta (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Ubuntu 18.04 LTS

cc @mkarolin @rebron @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.28.104 Chromium: 92.0.4515.131 (Oficjalna wersja) (64-bitowa)
-- | --
Wersja | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
System operacyjny | Windows 10 OS Version 2009 (Build 19043.1110)

```
- Verified the STR from the description 
![image](https://user-images.githubusercontent.com/38657976/128704289-71a7857a-c43b-49c4-8b4b-b125a941451b.png)
