### ISSUE TITLE
LocalStorage changes made by extensions not persisted

### ISSUE THREAD

**Issue by o9o** [brave/brave-browser#17285]
## Description 

Content scripts injected by extensions can no longer persist data into localStorage.

## Steps to Reproduce

Extension https://chrome.google.com/webstore/detail/dark-mode-night-reader/hmafjphdklmdjfcnljjeonfpgafanjjc or load unpacked from https://gitlab.com/o9000/darken

Step 1: Open some page.
Step 2: Click the extension button. The button label should change into "2".
Step 3: Close the tab, then re-open.
Step 4: Click the extension button again.

## Actual result:
The button label changes into "2".

## Expected result:
The button label should change into "3".

## Reproduces how often: 
Always on 1.29.42.

## Brave version (brave://version info)
1.29.42 on Linux

## Version/Channel Information:
Seems a nightly issue, but not sure when it was introduced. I see several very recent related commits like https://github.com/brave/brave-core/pull/9402

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? NO

## Miscellaneous Information:

The extension shows a button that when pressed causes a script to be injected into the current page:

```
chrome.browserAction.onClicked.addListener(function(tab) {
  chrome.tabs.executeScript({ file: "content.js" });
});
```

The content script executes some logic that sets a value that should be persisted in the page's localStorage:

```
...
localStorage.setItem(key, value);
...
```

After closing the tab and opening a new one, OR after just opening a new one, the key-value pair is no longer found in the localStorage. This was confirmed with the dev tools.

**Comment by o9o** [comment]
@goodov raised an issue possibly related to the recent commits such as https://github.com/brave/brave-core/pull/9402

**Comment by o9o** [comment]
IMHO `BraveContentSettingsAgentImpl::GetEphemeralStorageOriginSync` should allow content scripts to access localStorage instead of confusing them with 3rd party scripts. There is no point in blocking this access.

**Comment by goodov** [comment]
Thanks! I have a nightly build and it seems to work but I can see where it can go wrong. Can you please write the exact steps so it can be easier to reproduce?

**Comment by o9o** [comment]
I am unable to reproduce this anymore. Not sure why. All I did differently compared to yesterday was to disable ephemeral storage in flags. But now I have set it back to default, and restarted the browser, and I still cannot reproduce it.
