### ISSUE TITLE
 Gemini wallet text contents aren't translated to other locales

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#17297]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/17032
 Gemini wallet text contents aren't translated to other locales
## Steps to Reproduce

   1. Set OS locale to `Kannada`/ `Hindi`
   2. Clean profile 1.29.x staging env
   3. Enable rewards and connect to Gemini staging wallet
   4. Open to brave://rewrads-internals
   5. Few text contents aren't translated to Kannada locale

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/127890670-7306318a-fb3a-4c6b-8552-268456c9497b.png)

## Expected result:

`Gemini wallet` - wallet needs to be translated to other locales
`Custodian` - needs to be translated to other locales
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.29.43 Chromium: 92.0.4515.115 (ಅಧಿಕೃತವಾಗಿ ನಿರ್ಮಿಸಿ) nightly (64-ಬಿಟ್)
-- | --
ಪರಿಷ್ಕರಣೆ | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Windows 10 OS Version 2004 (Build 19041.1110)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @Miyayes @jumde

**Comment by mkarolin** [comment]
@GeetaSarvadnya, please recheck with https://github.com/brave/brave-browser/issues/18116

**Comment by Miyayes** [comment]
@GeetaSarvadnya Is this resolved?

**Comment by mkarolin** [comment]
Closing as this should have already been addressed (and current strings might not even match any more). @GeetaSarvadnya, please re-test if needed.
