### ISSUE TITLE
brave://about missing Brave-specific URLs

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#17299]
## Steps to Reproduce
   1.  Open `brave://about`

## Expected result:
The page should include:
* `brave://ipfs-internals`
* `brave://adblock`
* …others?

## Actual result:
The page doesn’t include these URLs.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
1.27.109 Chromium: 92.0.4515.115

**Comment by SebastianLF** [comment]
Can i work on this one ?

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.56 Chromium: 93.0.4577.58 (Official Build) beta (x86_64)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:
1. new profile
2. launched Brave
3. opened `brave://about`
4. looked at the listed URLs

Confirmed both `brave://adblock` and `brave://ipfs-internals` were now listed.

example | example | example
---------|----------|---------
<img width="936" alt="Screen Shot 2021-08-30 at 2 28 59 PM" src="https://user-images.githubusercontent.com/387249/131408446-08525d9a-967c-4d5a-8be0-b7c3ff76b499.png"> | <img width="936" alt="Screen Shot 2021-08-30 at 2 29 08 PM" src="https://user-images.githubusercontent.com/387249/131408452-fba01c60-aaba-44c8-8843-c588c7896baf.png"> | <img width="936" alt="Screen Shot 2021-08-30 at 2 29 34 PM" src="https://user-images.githubusercontent.com/387249/131408455-419bbc2d-5de0-4839-9c0d-20a4d9f4afdf.png">
