### ISSUE TITLE
Fallback to custom Brave ad notifications if native notifications are disabled

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#17298]
- Show custom ad notifications on macOS if `can_fallback_to_custom_notifications` is set to `true` for the `AdNotifications` feature and
    - native notifications feature is disabled or
    - macOS is older than 10.14

- Always show custom ad notifications on Linux if `can_fallback_to_custom_notifications` is set to `true` for the `AdNotifications` feature

- Show custom ad notifications on Windows if `can_fallback_to_custom_notifications` is set to `true` for the `AdNotifications` feature and
    - native notifications feature is disabled or
    - Windows is older than build 17134 or
    - native notifications are disabled
   
- Show custom ad notifications on Android if `can_fallback_to_custom_notifications` is set to `true` for the `AdNotifications` feature and
    - Android version is 8 or older or
    - native notifications are disabled

NOTE: `can_fallback_to_custom_notifications` for the `AdNotifications` feature is configured via the variations service and defaults to `false`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.30.65 Chromium: 93.0.4577.63 (Official Build) beta (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Ubuntu 18.04 LTS


Verified when enabled the feature through command line:
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true --brave-today-host=brave-today-cdn.bravesoftware.com --variations-server-url=https://no-thanks.invalid --enable-features="CustomAdNotifications<CommandLineStudy" --force-fieldtrials="CommandLineStudy/Enabled" --force-fieldtrial-params="CommandLineStudy.Enabled:can_fallback_to_custom_notifications/true/ad_notification_timeout/0/ad_notification_fade_duration/2000"
```
![image](https://user-images.githubusercontent.com/34715963/132382264-1c8e0207-2e4e-4396-b3db-86a6786cc1a5.png)

Verified when enabled through brave://flags
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true --brave-today-host=brave-today-cdn.bravesoftware.com --variations-server-url=https://no-thanks.invalid
```
![image](https://user-images.githubusercontent.com/34715963/132382991-5255c39a-804f-4cb4-ac69-bde7839bd6dd.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.66 Chromium: 93.0.4577.63 (Official Build) dev (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)


### Commandline

Steps:
1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true --brave-today-host=brave-today-cdn.bravesoftware.com --variations-server-url=https://no-thanks.invalid --enable-features="CustomAdNotifications<CommandLineStudy" --force-fieldtrials="CommandLineStudy/Enabled" --force-fieldtrial-params="CommandLineStudy.Enabled:can_fallback_to_custom_notifications/true/ad_notification_timeout/0/ad_notification_fade_duration/2000"`
3. clicked on `Start using Rewards`
4. confirmed I got custom ad notifications

<img width="1565" alt="Screen Shot 2021-09-07 at 2 34 54 PM" src="https://user-images.githubusercontent.com/387249/132415130-596e2654-75a5-4f84-8a37-2764b6000abd.png">

### `brave://flags`

Steps:
1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true --brave-today-host=brave-today-cdn.bravesoftware.com --variations-server-url=https://no-thanks.invalid`
3. in `brave://flags`, set `Enable Brave Ads custom notifications` to `Enabled`; restart
4. confirmed I got custom ad notifications


example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-09-07 at 2 36 13 PM" src="https://user-images.githubusercontent.com/387249/132415358-1f03dca8-3c25-44ce-bbfd-53986f4e8b56.png"> | <img width="1482" alt="Screen Shot 2021-09-07 at 2 37 33 PM" src="https://user-images.githubusercontent.com/387249/132415360-2aa52fd2-2286-48d0-ad2b-a08d985e0dd6.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.30.82 x64 build
- Verified custom ad is shown on both when using command line and flag 

Command line | Flag | Ad when flag enabled
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/134339669-15eda51d-83ac-4f89-92d5-65e0d2d56bd0.png) | ![image](https://user-images.githubusercontent.com/17010094/134339686-412d94ef-b3fb-410d-bae1-b0830b667b9c.png)  | ![image](https://user-images.githubusercontent.com/17010094/134339636-587c6e83-ddbd-4841-8953-79936cc50aa7.png)
