### ISSUE TITLE
Toggle Setting for Bookmarks Bar on a New Tab

### ISSUE THREAD

**Issue by hl2guide** [brave/brave-browser#17296]
## Description 

Please add the ability to hide the Bookmarks Bar on a New Tab. 

## Steps to Reproduce

   1. Open a New Tab

## Actual result:

![1](https://user-images.githubusercontent.com/17044982/127882265-81726aed-a609-4739-bbe5-a5c7d9e8de75.png)

## Expected result:
Bookmarks Bar on a New Tab can be hidden.

## Reproduces how often: 

all the time

## Brave version (brave://version info)

Version 1.27.109

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Untested
- Can you reproduce this issue with the nightly channel? Untested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Untested

## Miscellaneous Information:

No

**Comment by rebron** [comment]
Hi @hl2guide. 

Go to: brave://settings/appearance and this toggle should do it.

<img width="708" alt="Screen Shot 2021-08-02 at 8 42 24 AM" src="https://user-images.githubusercontent.com/5951041/127888056-4ffb8bb1-b2a1-4c35-afa6-e430e5dc4641.png">
