### ISSUE TITLE
Mouse pointer doesn't disappear in fullscreen videos

### ISSUE THREAD

**Issue by noomly** [brave/brave-browser#17292]
## Steps to Reproduce
   1. open a video on Youtube or Vimeo;
   2. enter fullscreen;
   3. observe the mouse pointer not disappearing.

## Actual result:
The mouse pointer stay visible when playing fullscreen videos.

## Expected result:
The mouse pointer disappear when playing fullscreen videos.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave: 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
Revision: 541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569}
OS: Linux

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by areebqazi** [comment]
Hey @rebron is this issue still active

**Comment by sash9696** [comment]
Hi @noomly . Could u please assign this issue to me.

**Comment by noomly** [comment]
Hello @sash9696, I'm afraid I don't have the permission to do that. Also, at the time of creation of this issue (~3 years ago) I was only trying out Brave, and have not continued using it since then.

**Comment by Blagoja95** [comment]
Hi @noomly. Problem described in this issue can't be reproduced anymore. Can you please check?

Brave version info:

Brave	1.62.165 Chromium: 121.0.6167.184 (Official Build) (64-bit) 
Revision	646e9a49ef45084cb2341eb1e9afabc339004a27
OS	Linux

**Comment by KirtiPriya07** [comment]
I am using brave v 1.65.126 and the issue described above is not in this version.

**Comment by THEBOSS0369** [comment]
Hey Everyone!! I have tested this issue on the latest version 1.68.134 on Windows , this issue has been resolved the mouse pointer disappears when on full screen. So if someone is not facing this issue anymore, perhaps this issue can be closed?
Thanks!

**Comment by bsclifton** [comment]
Thanks for updating @THEBOSS0369 - I'll close this out
