### ISSUE TITLE
Media Skipping Ahead on YouTube and YouTube Music

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#17302]
## Description 
In Youtube Music : Songs keep randomly skipping once a while as if somebody pressed "next", even if I don't touch anything.
In Youtube.com: I was watching a long video and it skipped from beginning to middle without me doing anything.

## Steps to Reproduce
unknown. Seems to be happening at random, no user action required.

## Actual result:
Skips a song at random (YTMusic) 

## Expected result:
Smooth playback from beginning to end (YTM)

## Reproduces how often: 
No steps.. I had it happen twice in past minute but then can go hours without issues (?). My extensions  + shields are all disabled on music.youtube.com

## Brave version (brave://version info)
<html>
<body>

Brave | 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

</body>
</html>

**Comment by ryanbr** [comment]
Hey @pilsnerbeer  If you bring up `Stats for Nerds` via rightclick on the video, does it show any dropped frames?

**Comment by pilsnerbeer** [comment]
On youtube yes, its slowly coming up. 19 dropped out of ~1800. Can't access such stats on youtube music though.

**Comment by ryanbr** [comment]
Do you have any extensions enabled? @pilsnerbeer

**Comment by pilsnerbeer** [comment]
shields only on youtube, all disabled on youtube music

**Comment by ryanbr** [comment]
Can you test in private window mode? Does the same issues occur in youtube? Shields=On on youtube is safe too

**Comment by pilsnerbeer** [comment]
I think I might have made a mistake the first time. The frames don't actually seem to be dropping at all unless I am on a different tab. I assume thats expected behavior? If focused on the tab thats playing video, 0 frames are dropped on youtube.

**Comment by ryanbr** [comment]
Unless you PC has system resources being used, youtube/youtube music should be fine playing in the background. 

Just tested `https://music.youtube.com/watch?v=mdcdxpn0JHY&list=OLAK5uy_nM5FWR-VXWkRNrsU_XEPQLFP7gmh-dyVs`  (one tab showed a video, the other didn't)

1. Does it show an issue whether you're logged in or not?
2. Enable Fanboy Annoyances in `brave://adblock` (and keep shields up).
3. Would test YT Music in private window mode.
4. When playing back a song on youtube, what does task manager show?

**Comment by pilsnerbeer** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/36133540/128018711-2208031d-2ea9-43dd-b889-f10fc564dc87.png)
If I quickly shuffle between tabs (A and B where A is playing YT video and B is whatever else) my dropped frame count goes quickly up (pic). But I have been so far unsuccessful in replicating the video-skipping issue today. I tried loading the link you sent but I can't access nerd stats for it.

When playing back a song on youtube, what does task manager show?
![Screenshot_2](https://user-images.githubusercontent.com/36133540/128019306-2edb5def-4fa7-4807-9afd-da3602dcbb1a.png)

**Comment by ryanbr** [comment]
@pilsnerbeer Not sure if you're still experiencing this, but I recheck youtube/YT Music in the latest builds, seems safe to close?
