### ISSUE TITLE
Uphold retry-loop in `PENDING` state doesn't display `PENDING` UI.

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#17316]
## Description 

In the `wallet generation flow` the wallet enters the retry-loop on API failures.
This results in the `PENDING` state and the corresponding UI should be displayed.

## Steps to Reproduce

1. fake a faulty endpoint, e.g. with Charles Proxy (`get user` (Uphold) / `get card ID` (Uphold) / `create card` (Uphold) / `update card settings` (Uphold) / `get anon funds` (Rewards) / `link` (Rewards))
2. try linking your Rewards wallet with a KYC'd Uphold account

## Actual result:

![actual](https://user-images.githubusercontent.com/5390451/128015821-d174dffa-9ef9-4211-97bf-de50db6cfbdf.png)

## Expected result:
![expected](https://user-images.githubusercontent.com/5390451/128015844-c418debb-c479-42c3-be34-c6107ee34d3e.png)

## Reproduces how often: 

Only reproducible with a faulty endpoint.

## Brave version (brave://version info)

Brave | 1.29.45 Chromium: 92.0.4515.115 (Developer Build) (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.29.61 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
Revision	6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS	macOS Version 10.15.7 (Build 19H1323)
```

<details>
<summary>Scenario 1 - `get user` (Uphold)</summary>

Used Charles Proxy to rewrite the response to https://api-sandbox.uphold.com/v0/me from 200 --> 404.
Confirmed that the logs reflected this rewrite:

```
[ REQUEST ]
> URL: https://api-sandbox.uphold.com/v0/me
> Method: GET
[32381:775:0817/155625.420725:VERBOSE1:uphold.cc(114)] Uphold wallet is not VERIFIED.
[32381:775:0817/155625.447447:VERBOSE2:tab_manager.cc(77)] Tab id 4 was updated
[32381:775:0817/155625.447908:VERBOSE6:user_activity.cc(41)] Triggered event: 11 (8:2:3600 s)
[32381:775:0817/155625.515965:VERBOSE7:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://api-sandbox.uphold.com/v0/me
> Result: Failure
> HTTP Code: 404
[32381:775:0817/155625.517126:INFO:get_me.cc(64)] Unexpected HTTP status: 404
[32381:775:0817/155625.518295:INFO:uphold_user.cc(69)] Couldn't get user
[32381:775:0817/155625.519851:INFO:uphold_wallet.cc(110)] Couldn't get the user object from Uphold!
```

Confirmed the UI shows the "Pending" state:

<img width="412" alt="get user pending" src="https://user-images.githubusercontent.com/28145373/129793759-2ef442b4-8079-4c7e-aaf0-707a3bb50b38.png">

</details>
