### ISSUE TITLE
Show Search Tabs Button should be Show Search Tabs button in brave://settings/appearance

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17310]
## Description 

Show Search Tabs Button should be Show Search Tabs button in brave://settings/appearance

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `brave://settings/appearance`
   4. look at the casing of `Show Search Tabs Button`

## Actual result:

<img width="1312" alt="Screen Shot 2021-08-02 at 5 26 55 PM" src="https://user-images.githubusercontent.com/387249/127939487-bc657afc-bc73-48dd-8f9d-e040efce2583.png">

## Expected result:

Should read `Show Search Tabs button`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.29.45 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 12.0 (Build 21A5294g)

**Comment by karenkliu** [comment]
cc @rmcfadden3 for copy/casing

**Comment by petemill** [comment]
Yeah `button` should definitely be lower case. I guess there's ambiguity as to whether "Search Tabs" is a feature name or a not (vs a description of an ability). If it is a feature, then it's perhaps a confusing one that we don't mention anywhere else! Maybe we should go with something like **"Tab Search"**:

`Show button to open Tab Search`

![image](https://user-images.githubusercontent.com/741836/128056981-002969b7-c7e1-4ac4-9d9d-c910005bf76e.png)

**Comment by rmcfadden3** [comment]
My vote would be "Search tabs" for this one. We should reserve title case only for branded features (e.g. Brave Talk, Brave News, etc), things truly unique to us.

**Comment by petemill** [comment]
@rmcfadden3 do you mean Search to be capitalised? And the feature is "Search tabs" not "tab search"?

**Comment by karenkliu** [comment]
@rmcfadden3 The copy we need is for this toggle: 

<img width="609" alt="Screen Shot 2021-08-03 at 1 37 30 PM" src="https://user-images.githubusercontent.com/2388823/128060892-707f5928-dcf2-4d5b-a4d4-a4838930f0c3.png">

**Comment by rmcfadden3** [comment]
> @rmcfadden3 do you mean Search to be capitalised? And the feature is "Search tabs" not "tab search"?

@petemill — This is for the grey text that appears beside the magnifying glass icon, prompting user to search among open tabs, right? If yes, then yeah, "Search tabs" would be the right copy. It's not a branded feature per say, so sentence case is right. LMK if I'm not thinking about this right.

@karenkliu — As for the Settings toggle (and I suppose the button name that appears if user hovers over it in browser)… I suppose button hover should = "Search tabs" and Settings toggle should = "Show Search tabs button"

**Comment by petemill** [comment]
@rmcfadden3 no this is not about the placeholder text in the feature - that was purely to show you what the feature is that the settings toggle turns on and off.

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.29.50 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.1 (Build 20G80)

Steps:

1. new profile
2. launch Brave
3. load brave://settings/appearance

Confirmed the text now reads `Show tab search button`

<img width="1770" alt="Screen Shot 2021-08-04 at 10 47 43 AM" src="https://user-images.githubusercontent.com/387249/128229885-f60fc090-ad64-4629-a900-313f53c94f64.png">
