### ISSUE TITLE
Illegible overlapping error text in download infobar

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17313]
## Description 

Illegible overlapping error text in download infobar

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `https://www.leaseweb.com/platform/network`
   4. context-click on any large file and choose `Save File As...`
   5. click `Save`
   6. you'll get the `[filename] can't be downloaded securely` message
   7.  click on `Keep`
   8. now, disconnect from wi-fi
   9. wait for the error state to show `Failed - network disconnected`
   9. click on `Resume`

## Actual result:

<img width="1312" alt="Screen Shot 2021-08-02 at 7 46 21 PM" src="https://user-images.githubusercontent.com/387249/127949767-bb27db93-4907-446e-af53-e516b36b5193.png">

![download-legible](https://user-images.githubusercontent.com/387249/127949885-f1f81bfc-eb9f-48ec-9c26-5524b73441dd.gif)

## Expected result:
<img width="1312" alt="Screen Shot 2021-08-02 at 7 49 27 PM" src="https://user-images.githubusercontent.com/387249/127949794-80d1000a-e79b-495a-b639-2dc4ef917c03.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.29.45 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 12.0 (Build 21A5294g)

/cc @nullhook @mkarolin

**Comment by rebron** [comment]
<img width="1414" alt="Screen Shot 2021-08-06 at 2 46 59 PM" src="https://user-images.githubusercontent.com/5951041/128574318-49008da0-78e5-4fc8-9c8f-3f92a25ec3f0.png">
I'm also seeing this error.

**Comment by kjozwiak** [comment]
I ran into something similar but not as bad as @stephendonner. Example:

![image](https://user-images.githubusercontent.com/2602313/130550864-e7ae7400-12d6-4d7a-b7e9-419520a42ec1.png)

You can see that there's an extra `content` text that seems to be spilling over in between the two sentences. Ran into the issue using the following build:

```
Brave | 1.30.41 Chromium: 93.0.4577.51 (Official Build) nightly (64-bit)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | Windows 10 OS Version 2009 (Build 19042.1165)
```

**Comment by stephendonner** [comment]
**Verified `PASSED`** using 


Brave | 1.31.54 Chromium: 94.0.4606.50 (Official Build) beta (x86_64)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | macOS Version 11.6 (Build 20G165)

### Steps:

1. new profile
2. launch Brave
3. load `https://www.leaseweb.com/platform/network`
4. context-click on any large file and choose `Save File As...`
5. click `Save`
6. you'll get the `[filename] can't be downloaded securely` message
7. click on `Keep`
8. now, disconnect from wi-fi
9. wait for the error state to show `Failed - network disconnected`
10. click on `Resume`

Confirmed there was no overlapping text in any of these steps.

example | example | example
---------|---------|----------
<img width="1312" alt="Screen Shot 2021-09-20 at 12 35 13 PM" src="https://user-images.githubusercontent.com/387249/134063561-c123d530-871f-4635-8518-2f2c66c70673.png"> | <img width="1312" alt="Screen Shot 2021-09-20 at 12 35 17 PM" src="https://user-images.githubusercontent.com/387249/134063605-fe566675-5cba-4bca-bbeb-641533c85d92.png"> | <img width="1312" alt="Screen Shot 2021-09-20 at 12 35 34 PM" src="https://user-images.githubusercontent.com/387249/134063608-b705c4af-f6c7-44e9-b2a9-e7ee70b9ab97.png">
