### ISSUE TITLE
Update Shield and Rewards icon sizing and color

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#1731]
Our current Brave Bar icons are 16px in size and need scaled to be 18x18. The black background shields notification color is also blending into the address bar in dark theme and should be adjusted to #662D91.  
![brave-bar](https://user-images.githubusercontent.com/29072694/47234905-271e9d00-d38c-11e8-9d81-2d7f27172fd5.png)

**Comment by rossmoody** [comment]
Going to do a larger encompassing cross platform design spec for these elements, make sure this is valid concrete direction and repost.

**Comment by bbondy** [comment]
Updated milestone to dupe / invalid.
