### ISSUE TITLE
Custodian verification error modal disappears intermittently

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#17311]
## Description 
A non-KYC'ed user sees a message that a user needs to be verified with the custodian before using Brave Rewards. This message intermittently disappears when using a non-KYC'ed account.

## Steps to Reproduce

   1. Login to Gemini/Uphold with a non-KYC'ed account

## Actual result:
Error message should be displayed on OAuth

## Expected result:
Error message sometimes disappears

## Reproduces how often: 
Intermittent issue

**Comment by LaurenWags** [comment]
Verified using 

```
Brave | 1.31.70 Chromium: 94.0.4606.71 (Official Build) beta (x86_64)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | macOS Version 10.15.7 (Build 19H1417)
```

Issue persists using test plan from https://github.com/brave/brave-core/pull/9925#issue-984155760. Per discussion with @szilardszaloki, he has encountered this as well and this will be handled with https://github.com/brave/brave-browser/issues/16652.
