### ISSUE TITLE
add open downloads in temp feature to brave

### ISSUE THREAD

**Issue by iknothing** [brave/brave-browser#17314]
## Description 

similar to firefox and edge browser, i want open downloads in temp folder in brave browser, also called as open with (program name)

## Steps to Reproduce

   1. download an app
   2.  automatically shows where to download box
   3. should have the below image box instead

## Actual result:

automatically downloads the file in selected directory
![image](https://user-images.githubusercontent.com/78652689/127982523-e69a9673-47f2-4dea-8d3d-914506207fb7.png)

## Expected result:
![image](https://user-images.githubusercontent.com/78652689/127981894-2bf07853-375a-4398-999a-d741bd578b35.png)

## Reproduces how often: 

everytime

## Brave version (info found on brave://version)

1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? :yes
- Can you reproduce this issue with the beta channel? :yes
- Can you reproduce this issue with the dev channel? :yes
- Can you reproduce this issue with the nightly channel? :yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? :no
- Does the issue resolve itself when disabling Brave Rewards? :no
- Is the issue reproducible on the latest version of Chrome? :yes

## Miscellaneous Information:

edge and firefox browser have this feature

**Comment by rebron** [comment]
hi @iknothing 

When you go to: brave://settings/downloads can you toggle the bottom setting? A file window should open up at that point.
<img width="701" alt="Screen Shot 2021-08-05 at 8 40 55 AM" src="https://user-images.githubusercontent.com/5951041/128379594-5a285b62-7e29-475a-a1b8-a94dd69647f2.png">

**Comment by iknothing** [comment]
Ofc this works for me, but that is not what i was talking about. There should be a feature for  directly opening a file without downloading it ie- saving it in temp folder. If u use firefox and download any thing once then u will understand. Pla refer to my screenshot. Firefox asks open/save a file before downloading. The open option just download it to temp folder and then opens it, save option downloads the file

**Comment by rebron** [comment]
@iknothing I understand your request to show a different dialog (the same one you're used to when using Firefox) when downloading files. That's different from opening a file without downloading it though, e.g. viewing pdf pages. You're still downloading the file regardless, it's either we show you the File Explorer window or (Firefox version) give you option to choose the app to open the file rather than dropping you into File Explorer window automatically.

cc: @stephendonner

**Comment by iknothing** [comment]
Yes but in Firefox when u choose to open the file directly from that dialog box, it automatically downloads it in the temporary folder in windows, but u cant manually navigate to temp folder all the time with  the option to choose where to download in brave. Do u understand now? When u click open with in firefox,it downloads the file to the temporary folder in windows and also gives the user the option to download it to user specified folder, i want that feature. Temp folder gets deleted when u reboot the pc

**Comment by stephendonner** [comment]
@iknothing I believe we're just doing what Chromium does - would something like https://chrome.google.com/webstore/detail/download-to-temp-folder/cmgdgmohnilgoblgjmnklajoedgpenan?hl=en address your use-case?

**Comment by iknothing** [comment]
hmm the  extension  fits  my use case, sorry for the  late  reply. But  i regret to tell you that i have  already  started  using ms edge  instead  of  brave  now.
