### ISSUE TITLE
Add promotional card for Gemini in Brave Rewards settings page

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#17315]
Add a promotional card for Gemini in the Brave Rewards settings (brave://rewards) in the bottom right, where the TAP Network card typically goes (bottom right corner).

**Comment by stephendonner** [comment]
Verified `PASSED` using 


| Brave    | 1.29.50 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64) |
| -------- | ------------------------------------------------------------ |
| Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933} |
| OS       | macOS Version 11.5.1 (Build 20G80)                           |

Confirmed:

1. new profile has both `Gemini` and `Tap`
2. confirmed the card URL is `https://www.gemini.com/brave`
3. clicking on the `x` removes `Gemini`, which persists after restart
4. clicking on the `x` removes `Tap`, which persists after restart
5. upgrading from `1.27.109` adds `Gemini` (`Gemini` at top and `Tap`, below it, displayed)
6. upgrading from `1.27.109` with `Tap` removed adds `Gemini`

example | example | example | example | example | example
---------|----------|---------|----------|---------|----------
<img width="1401" alt="Screen Shot 2021-08-04 at 2 45 51 PM" src="https://user-images.githubusercontent.com/387249/128261480-55173b56-fee6-4240-862e-08fb3a81b385.png"> | <img width="1312" alt="Screen Shot 2021-08-04 at 3 08 43 PM" src="https://user-images.githubusercontent.com/387249/128261755-3e45ae5d-20a2-4aca-82f5-c5778fcbe592.png"> | <img width="1312" alt="Screen Shot 2021-08-04 at 2 54 53 PM" src="https://user-images.githubusercontent.com/387249/128261514-33f0f3bf-d123-42bf-b560-8e3b4e66a8c5.png"> | <img width="1312" alt="Screen Shot 2021-08-04 at 2 55 40 PM" src="https://user-images.githubusercontent.com/387249/128261542-9fe2ad9d-8f2c-4892-9c7c-a2b320ed7c9f.png"> | <img width="1401" alt="Screen Shot 2021-08-04 at 2 46 01 PM" src="https://user-images.githubusercontent.com/387249/128261603-d2510311-e171-4c54-b525-af085dee485b.png"> | <img width="1312" alt="Screen Shot 2021-08-04 at 2 54 53 PM" src="https://user-images.githubusercontent.com/387249/128261623-e6278c5b-ec60-4b4d-8793-127f2af43544.png">

**Comment by LaurenWags** [comment]
https://github.com/brave/brave-browser/issues/17383 can be tested along side this issue.
