### ISSUE TITLE
brave ads crashing/restarting in constant loop on older profiles

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#17331]
## Description 

Brave Ads constantly crashes/restarts when enabling rewards on older versions of Brave. Example:

* https://github.com/brave/brave-browser/releases/v1.22.39
* https://github.com/brave/brave-browser/releases/v1.23.21

```
[10468:8772:0803/155416.924:VERBOSE1:ads_impl.cc(99)] Initializing ads
[10468:8772:0803/155416.924:VERBOSE1:text_classification_resource.cc(53)] Successfully loaded keahfifnfebhoaaghffigjnhgbkkaibd text classification resource
[10468:8772:0803/155417.026:VERBOSE1:ads_service_impl.cc(704)] Restarting ads service
```

@tmancey added the logs and the profile as discussed:

* Full log --> [adsServiceCrash.txt](https://github.com/brave/brave-browser/files/6926821/adsServiceCrash.txt)
* Zipped/Archived profile: https://drive.google.com/file/d/1xzK1fEqBrQashyTkFR9TJVJUINJapXZk/view?usp=sharing

## Steps to Reproduce

   1. download/install either https://github.com/brave/brave-browser/releases/v1.22.39 or https://github.com/brave/brave-browser/releases/v1.23.21
   2. launch from the CLI/terminal and enable ads via `brave://rewards`
   3. you'll notice that the ads service will keep crashing & restarting in a constant loop
   4. visit `brave://crashes` and note all the crashes that occurred

## Actual result:

Crash reports from `macOS 11.5.1 x64`:

```
* Uploaded Crash Report ID:	08e73f00-217a-ae06-0000-000000000000
* Uploaded Crash Report ID:	ffe63f00-217a-ae06-0000-000000000000
* Uploaded Crash Report ID:	0de73f00-217a-ae06-0000-000000000000
* Uploaded Crash Report ID:	0ae73f00-217a-ae06-0000-000000000000
```

Crash reports from `Win 10 x64`:

```
* Uploaded crash report ID: 29ea3f00-217a-ae06-0000-000000000000
* Uploaded crash report ID: 26ea3f00-217a-ae06-0000-000000000000
* Uploaded crash report ID: 25ea3f00-217a-ae06-0000-000000000000
* Uploaded crash report ID: 22ea3f00-217a-ae06-0000-000000000000
```

## Expected result:

Ads service shouldn't be crashing

## Reproduces how often: 

100% reproducible on both `macOS 11.5.1 x64` & `Win 10 x64` when running through the above STR/Cases.

## Brave version (brave://version info)

```
Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (64-bit)
--- | ---
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | Windows 10 OS Version 2009 (Build 19042.1110)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No` (only on older profiles)
- Can you reproduce this issue with the beta channel?  `No` (only on older profiles)
- Can you reproduce this issue with the nightly channel?  `No` (only on older profiles)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `No`
- Does the issue resolve itself when disabling Brave Rewards? `Yes`
- Is the issue reproducible on the latest version of Chrome? `No`

## Miscellaneous Information:

CCing @tmancey @moritzhaller @bsclifton @brave/legacy_qa

**Comment by kjozwiak** [comment]
Just a heads up, as per the above, this only happens on older versions of Brave. However, because of this issue, it makes it impossible to QA upgrade cases from either `1.22.x` & `1.23.x` to the current release.

**Comment by tmancey** [comment]
Closing issue as stale
