### ISSUE TITLE
Unable to switch away from dark mode

### ISSUE THREAD

**Issue by alissa-huskey** [brave/brave-browser#17333]
## Description 

Even when selecting "Light" from "Brave colors" in Settings, the browser remains in dark mode.

## Steps to Reproduce

   1. Open brave://settings/
   2. Under, Appearance, for the "Brave colors" setting, select "Light" 

## Actual result:

The browser remains in dark mode.

<img width="1273" alt="brave" src="https://user-images.githubusercontent.com/48001/128089403-1a095e74-23d6-45e5-a064-5c3a9ff05417.png">

## Expected result:

The browser should switch to light mode.

## Reproduces how often: 

Always, as of the most recent version update.

## Brave version (info found on brave://version)

Brave | 1.27.109 Chromium: 92.0.4515.115 (Official Build) (x86_64)
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.2.3 (Build 20D91)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? \
   No
- Does the issue resolve itself when disabling Brave Rewards?
   No
- Is the issue reproducible on the latest version of Chrome? 
   NA--no "Brave colors" on chrome.

**Comment by Tonev** [comment]
Open `brave://flags/#enable-force-dark` via the address bar, and set flag's value to `Default`.

**Comment by bsclifton** [comment]
@Tonev thanks for the assist 😄 

@alissa-huskey can you please try that?

**Comment by alissa-huskey** [comment]
Thanks, that did it! I thought I had remembered experimenting with something like that before but couldn't recall what I'd done. Sorry for the trouble. :-)

**Comment by bsclifton** [comment]
Awesome, thanks for the update @alissa-huskey 😄
