### ISSUE TITLE
Update "Your wallet is unreachable" error text

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17348]
## Description

A user can see this error message when their access token expires in Brave Rewards: 

![image](https://user-images.githubusercontent.com/11497541/128213442-24e0a07f-45c6-4a0b-a484-3540961c8d32.png)

@szilardszaloki confirms:

We only use the above error when the access token expires, with 1 minor exception: in the very unlikely event of an Uphold account returning an undocumented user status, this error message is used.
 
## Solution

Use this text:

![image](https://user-images.githubusercontent.com/11497541/138936449-046f0d5a-439d-4d51-b292-78043da3cf04.png)

**Comment by codybanxs** [comment]
Will log this and find a friendlier alt description!

**Comment by Miyayes** [comment]
![image](https://user-imag@codybanxs ithubusercontent.com/11497541/130266953-3bc59630-6f41-4659-8bf7-1f73656fb167.png)
@codybanxs

**Comment by Miyayes** [comment]
I think this is done. The below is fine: 
![image](https://user-images.githubusercontent.com/11497541/151263965-693fcd30-be92-4eaf-8fa7-a388711dd58e.png)
