### ISSUE TITLE
Dev channel download redirects to beta

### ISSUE THREAD

**Issue by Madis0** [brave/brave-browser#17344]
## Description 

[Download for Brave Dev](https://brave.com/download-dev) [redirects to beta](https://brave.com/download-beta/). It is also not found in the homepage anymore.

## Steps to Reproduce

   1. Visit https://brave.com/download-dev
   2. Notice how it gets redirected to https://brave.com/download-beta/
   3. Notice how there is no mention of Dev in the page

## Actual result:

Redirected to https://brave.com/download-beta/

## Expected result:
Expected a download, [because it is clearly built on Github](https://github.com/brave/brave-browser/releases/tag/v1.28.101), [mentioned on support](https://support.brave.com/hc/en-us/articles/360017916752-What-is-the-difference-between-Nightly-Dev-Beta-and-Release-builds-) [and wiki](https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#beta--dev-channel-dates) and I currently run it while also receiving updates.

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave: 1.28.101 Chromium: 92.0.4515.115 (Official build) dev (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No 
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

If it is indeed deprecated, shouldn't the users be migrated to beta now? And why is it still built on Github?

**Comment by stephendonner** [comment]
@AlanBreck - something you can take a look at, when you get a chance?

**Comment by AlanBreck** [comment]
This is intended behavior. cc @bsclifton @bbondy

**Comment by bbondy** [comment]
Yes this is intended. 
Brave Dev channel is deprecated, although we still produce builds on github because we haven't had time to migrate old users.

**Comment by bbondy** [comment]
The builds we do for it are equivalent to Beta.

**Comment by bsclifton** [comment]
Thanks for reporting @Madis0 

We intend to completely deprecate the `Dev` channel at some point... but there's not really a clean way to do it. If we push Beta binaries out to the folks on Dev, it'll create a new profile directory and it will appear to them that they've lost everything

We would need to plan a migration, which is a bigger discussion. Some possible options may include (one or a mix of these):
1. put a special "End of Life" page when the browser opens. Include instructions about how to install beta and how to migrate the profile (ex: rename profile folder `Brave-Browser-Dev` as `Brave-Browser-Beta`)?
2. have a special Dev only version which changes the profile folder name to `Brave-Browser-Beta` and then updates itself?
3. Have a fresh install of Beta look for the existence of `Brave-Browser-Dev` and automatically import it / delete the old directory?
4. Add a proper import for other channels (see https://github.com/brave/brave-browser/issues/1357)
4. Push beta binaries to folks on Dev. Create help article sharing how to restore the other profile

cc: @rebron
