### ISSUE TITLE
Show tabs search preference not being read properly on initial browser start

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#17343]
## Description 

When you set a preferred setting on "Show tab search button" in brave://settings/apperance and restart the browser the saved preference doesn't update the toggle state.

## Steps to Reproduce

   1. Turn the toggle on/off on "Show search tab button"
   2. Restart the browser
   3. Check the toggle state

## Actual result:

The toggle state doesn't remember the last saved setting on initial start

## Expected result:
The toggle state should reflect the last saved setting when you restart the browser

## Reproduces how often: 

Always

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.29.50 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.1 (Build 20G80)

Steps:
1. new profile
2. launched Brave
3. confirmed `Show tab search button` is preffed `On` by default
4. confirmed toggling it to `Off` removes the feature UI from browser chrome
5. confirmed restarting Brave persisted the `Off` state
6. confirmed toggling to `On` brought back the feature UI
7. confirmed toggling `On` and `Off` repeatedly toggles the UI in real-time
8. confirmed a few more times that restart during either of those two states persists correctly

![tab-pref-persists](https://user-images.githubusercontent.com/387249/128257533-bc124ce5-5f02-413e-bab2-614f778240c9.gif)
