### ISSUE TITLE
Crash when ending screen share using Brave Talk

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17353]
## Description 

Crash when ending screen share using Brave Talk

(Filing for @mattmcalister who should feel free and encouraged to correct/add details!)

## Steps to Reproduce

   1. load `talk.brave.com`
   2. click on `Start video call`
   2. click through the microphone and video-camera permissions requests
   3. enter your name, click `Join meeting`
   4. on the bottom toolbar, click on the screen/monitor with an arrow icon
   5. choose `Window` from the top tabs
   6. select a window, click `Share`
   7. wait a while / add participants
   8. click again on the `Start / Stop sharing your screen` icon

## Actual result:

Crashes here, occasionally, for @mattmcalister :

```
[ 00 ] 0x1118d75
[ 01 ] mojo::MessageDispatcher::Accept(mojo::Message*)
[ 02 ] mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*)
[ 03 ] mojo::internal::MultiplexRouter::ProcessIncomingMessage(mojo::internal::MultiplexRouter::MessageWrapper*, mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*)
[ 04 ] mojo::internal::MultiplexRouter::Accept(mojo::Message*)
[ 05 ] mojo::MessageDispatcher::Accept(mojo::Message*)
[ 06 ] mojo::Connector::DispatchMessage(mojo::Message)
[ 07 ] mojo::Connector::ReadAllAvailableMessages()
[ 08 ] <name omitted>
[ 09 ] <name omitted>
[ 10 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*)
[ 11 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[ 12 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[ 13 ] base::MessagePumpCFRunLoopBase::RunWork()
[ 14 ] base::mac::CallWithEHFrame(void () block_pointer)
[ 15 ] base::MessagePumpCFRunLoopBase::RunWorkSource(void*)
[ 16 ] 0x7fff2072597c
[ 17 ] 0x7fff207258e4
[ 18 ] 0x7fff20725664
[ 19 ] 0x7fff2072408c
[ 20 ] 0x7fff2072364c
[ 21 ] 0x7fff28961ab3
[ 22 ] 0x7fff28961815
[ 23 ] 0x7fff289615b3
[ 24 ] 0x7fff22f246f2
[ 25 ] 0x7fff22f22ec5
[ 26 ] __71-[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke
[ 27 ] base::mac::CallWithEHFrame(void () block_pointer)
[ 28 ] -[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:]
[ 29 ] 0x7fff22f15239
[ 30 ] base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*)
[ 31 ] base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*)
[ 32 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta)
[ 33 ] <name omitted>
[ 34 ] content::BrowserMainLoop::RunMainMessageLoop()
[ 35 ] content::BrowserMainRunnerImpl::Run()
[ 36 ] content::BrowserMain(content::MainFunctionParams const&)
[ 37 ] content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams&, bool)
[ 38 ] content::ContentMainRunnerImpl::Run(bool)
[ 39 ] content::RunContentProcess(content::ContentMainParams const&, content::ContentMainRunner*)
[ 40 ] content::ContentMain(content::ContentMainParams const&)
[ 41 ] ChromeMain
[ 42 ] main
[ 43 ] 0x7fff20647f5d
[ 44 ] 0x7fff20647f5d
```

https://share.backtrace.io/api/share/w6x1shHhPFvc5B5M2OCcuE1

## Expected result:

No crash

## Reproduces how often: 

Unsure; @mattmcalister ?

## Brave version (brave://version info)

@mattmcalister please fill in your build ID

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by diracdeltas** [comment]
I also saw this yesterday. 
Version 1.30.68 Chromium: 93.0.4577.63 (Official Build) beta (arm64)
Uploaded Crash Report ID:  143e1500-4d04-ef06-0000-000000000000

**Comment by agilob** [comment]
436b0500-b1ec-5608-0000-000000000000
45780400-b1ec-5608-0000-000000000000
46270300-b1ec-5608-0000-000000000000

**Comment by mbacchi** [comment]
The browser crashes for me every time I run brave talk and share my screen. I have some success closing the browser tab with brave talk, instead of clicking the "Stop sharing" button. But this does not always work, and today I had a crash even though I closed the browser tab and did not click the "Stop sharing" button.

Most recent crash ID: 59520000-3035-b308-0000-000000000000
