### ISSUE TITLE
Trackers Blocked on new tab always shows zero

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1735]
Trackers and ads get counted together on newtab page.

## Steps to Reproduce

   1. Clean install
   2. Open `https://jsfiddle.net/bkf50r8v/13/`
   3. Open a new tab and check `Trackers Blocked`

## Actual result:

`Trackers Blocked` shows 0
![image](https://user-images.githubusercontent.com/34715963/47238775-8fe53400-d3e3-11e8-9c08-6ca5ffc48e77.png)

## Expected result:
`Trackers Blocked` shows 1

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

Reproduced by @GeetaSarvadnya  on Windows 10

cc @srirambv @LaurenWags @kjozwiak to check on other platform

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/stats-incomplete-on-new-tab-page/35271/4

**Comment by Liunkae** [comment]
+1 from me. Brave 0.57.1 on macOS 10.14.

**Comment by srirambv** [comment]
+1 from https://www.reddit.com/r/BATProject/comments/9pub7w/whats_with_the_low_level_of_trackers_blocked_and/

**Comment by GeetaSarvadnya** [comment]
Verification Passed on:


Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

![1735](https://user-images.githubusercontent.com/38657976/47354783-392a7380-d6dd-11e8-852f-b0a7f55fea8b.gif)
