### ISSUE TITLE
Onion website for Brave search is creating a bad user experience

### ISSUE THREAD

**Issue by ksajan** [brave/brave-browser#17357]
## Description 

After opening a new tab when I type and search that word. It opens an onion website for me it started happening this week. Even though it's not an onion site I have no idea why it's happening. Example When I search "Joker" using brave search it opened an onion site for me.

Note:- After thorough observation, it opens only one type of onion site which goes directly to brave search beta hope page.
link to onion [site](https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/)

I know I have enabled a setting to open an onion site of the same website on a different window but this defeats the whole argument of using this setting if I have to disable this setting just because brave search has an onion site and can't be used with this setting enabled.

## Steps to Reproduce

   1. Make Brave search the default
   2. Search any keyword on the new tab with brave search enabled
   3. It will open a Brave search homepage in a different window

## Actual result:

<img width="1650" alt="Screenshot 2021-08-05 at 10 27 50 AM" src="https://user-images.githubusercontent.com/31013555/128294616-9eff4df8-9bf6-4702-9d5f-787f8f85151c.png">
<img width="1678" alt="Screenshot 2021-08-05 at 10 41 05 AM" src="https://user-images.githubusercontent.com/31013555/128294625-29f2228e-da41-460a-bcd7-4d16d904d770.png">

## Expected result:
It should only open an onion site when I visit a website that has an onion link. Not with every search on brave search engine. This makes the entire experience very bad.  

## Reproduces how often: 

Every time when used with a brave search engine as default.

## Brave version (brave://version info)

Brave | 1.27.109 Chromium: 92.0.4515.115 (Official Build) (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 11.5 (Build 20G71)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Tonev** [comment]
Community user reported the same just yesterday.

https://community.brave.com/t/search-on-brave-sometimes-pops-up-a-private-with-tor-window/271509

**Comment by ksajan** [comment]
Thanks for pointing it out. I actually disabled the setting because it annoyed the hell out of me.
But my question isn't that make that setting useless with brave search?

**Comment by wknapik** [comment]
Yesterday we started advertising the new onion address via the onion-location header for search.

The same value - `onion-location: https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` - was returned for every url under search.brave.com. This was at least a contributing factor to this issue.

This is now changed, so that the header is only returned at search.brave.com (only at `/` - thanks for the quick fix @remusao!). This should improve things, please report back!

Questions that remain:
* Should the browser functionality around opening onion urls be changed?
* Should we return the onion-location header for other paths than `/` for search (including the path in the header)?

**Comment by wknapik** [comment]
cc @rebron

**Comment by Tonev** [comment]
@wknapik 

> Should the browser functionality around opening onion urls be changed?

It definitely should be changed. Right now, opening a website that has an .onion version will make Brave automatically open that website in a regular window once and once again in a Tor window while focusing on the slowly loading Tor window. That's quite user unfriendly, at least in my opinion, and I'm sure a lot of users will be unpleasantly surprised when that happens to them for the first time.

I recorded a short video that shows how casually entering an address could lead to a slow loading of the page, whereas the page is already available in a minimized regular window tab.


https://user-images.githubusercontent.com/20608253/128365565-183d25de-fa22-4c52-bdf7-56aa9c474d9f.mp4

My suggestion would be to change the automatic character of the feature. If a user is in a regular window and enters the address of a website that has an .onion version, alert the user of that information and gave them the choice to either continue browsing that website in the regular window or allow them to reload the website in a Tor window.

**Comment by wknapik** [comment]
Linking @Tonev's related issue https://github.com/brave/brave-browser/issues/17363.

**Comment by wknapik** [comment]
@rebron any plans for this? I'd like to enable the `onion-location` header for all search urls, but I think this needs to wait for this issue to be resolved.

**Comment by wknapik** [comment]
ping

**Comment by rebron** [comment]
https://github.com/brave/brave-browser/issues/36933 With that change, we can close this correct? @wknapik

**Comment by rebron** [comment]
Closing. Fixed in 1.66.x and with this pr: https://github.com/brave/brave-core/pull/22697
