### ISSUE TITLE
Gray notice not showing in Tipping `dropdown panel` in certain cross-custodial cases, but shows in Tipping `banner` 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17362]
## Description

In some cross-custodial cases, the gray notice is not showing in the Tipping dropdown panel. Occurs in the Uphold-verified-user to Gemini-creator case, and also in bitFlyer-verified-user case with Gemini-creator. (See comments below as well.)

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/9679

**Steps to reproduce:**

1. Verify user profile with Uphold
2. Navigate to a site/channel that is Gemini-verified (e.g., batcommunity.org)
3. Observe that the tipping dropdown panel does not show gray notice telling the user that the channel is not configured to receive tips from their wallet (due to cross-custodian)
4. Observe that the notice _does_ appear in the Tipping banner itself

<img src="https://user-images.githubusercontent.com/11497541/128375212-94def13d-f21c-45b4-830a-8b460a1c2bc1.png" width=300px>

![image](https://user-images.githubusercontent.com/11497541/128375234-791aa13f-72cc-48b5-be9c-bf7e254ea368.png)

## Solution

Show the gray notice in this case. 

cc: @LaurenWags

**Comment by LaurenWags** [comment]
```
Brave	1.29.51 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
Revision	6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS	macOS Version 11.5.1 (Build 20G80)
```

Does not reproduce when Gemini verified with the following publisher types:

`Unverified`:

Example | Example
----- | -----
<img width="401" alt="unverified1" src="https://user-images.githubusercontent.com/28145373/128360290-2c42647d-1d72-45b2-a158-8d9f16dafabb.png"> | <img width="1194" alt="unverified2" src="https://user-images.githubusercontent.com/28145373/128360298-3e8b7038-f13f-46d1-83c0-b1c92a081077.png">

`Connected`:

Example | Example
----- | -----
<img width="410" alt="connected1" src="https://user-images.githubusercontent.com/28145373/128360358-c9c046c7-fc1a-4833-b0d4-97036c24c91d.png"> | <img width="1187" alt="connected2" src="https://user-images.githubusercontent.com/28145373/128360366-877eb849-fb13-4b8b-93da-c59686dd0b32.png">

`Uphold Verified`:

Example | Example
----- | -----
<img width="398" alt="uphold1" src="https://user-images.githubusercontent.com/28145373/128360391-98e9840f-c775-4516-ba27-fa30e1c1b126.png"> | <img width="1192" alt="uphold2" src="https://user-images.githubusercontent.com/28145373/128360398-cd0a8baf-0f07-4bfb-8536-e0b5569190e4.png">

`bitFlyer Verified`:

Example | Example
----- | -----
<img width="400" alt="bf1" src="https://user-images.githubusercontent.com/28145373/128360423-71515678-8443-4a50-ae08-142ba1e10942.png"> | <img width="1190" alt="bf2" src="https://user-images.githubusercontent.com/28145373/128360428-83d49bd4-3df0-4178-857a-ead33ea308a2.png">

**Comment by LaurenWags** [comment]
```
Brave	1.29.51 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
Revision	6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS	macOS Version 11.5.1 (Build 20G80)
```

Does reproduce when bitFlyer verified with the following publisher type:

`Gemini Verified`:

Example | Example
----- | -----
<img width="402" alt="スクリーンショット 2021-08-05 11 46 47" src="https://user-images.githubusercontent.com/28145373/128381270-7c9f5643-f9d0-43bc-ad69-7746f6750457.png"> | <img width="1192" alt="スクリーンショット 2021-08-05 11 46 55" src="https://user-images.githubusercontent.com/28145373/128381276-9e552f1d-94a9-48c0-b2a8-8d8f979b4a73.png">


Does not reproduce with bitFlyer verified with the following publisher types:

`Unverified`:

Example | Example
----- | -----
<img width="411" alt="スクリーンショット 2021-08-05 11 45 46" src="https://user-images.githubusercontent.com/28145373/128381048-183afb7c-4c59-4d33-bc9b-42962e5f3f37.png"> | <img width="1188" alt="スクリーンショット 2021-08-05 11 45 52" src="https://user-images.githubusercontent.com/28145373/128381059-793c111b-324c-4f42-83c1-66ef03826fe1.png">

`Connected`:

Example | Example
----- | -----
<img width="394" alt="スクリーンショット 2021-08-05 11 46 02" src="https://user-images.githubusercontent.com/28145373/128381126-5490223e-ae17-4000-8683-a0ee7feec316.png"> | <img width="1189" alt="スクリーンショット 2021-08-05 11 46 10" src="https://user-images.githubusercontent.com/28145373/128381136-f67236a4-6c7d-4e5a-be0b-37abc71ff659.png">

`Uphold Verified`:

Example | Example
----- | -----
<img width="409" alt="スクリーンショット 2021-08-05 11 46 22" src="https://user-images.githubusercontent.com/28145373/128381189-f6083db9-7e42-4efb-9627-021ad7c80a6f.png"> | <img width="1196" alt="スクリーンショット 2021-08-05 11 46 30" src="https://user-images.githubusercontent.com/28145373/128381194-2f09ffa5-fec6-44fc-b1e3-07874491a28d.png">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.29.61 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 10.15.7 (Build 19H1323)
```

#### **Anon User Wallet**
* Confirmed that when using an anon wallet (funded only by grants), only unverified creators display messaging on panel and tip banner. 
* Confirmed that creators verified with Brave (regardless of their creators custodial wallet status), do not show any messaging on panel or tip banner.

<details>
<summary>Anon (not KYC'd) wallet screenshots</summary>

**`Unverified Creator`**:

Example | Example
----- | -----
<img width="400" alt="Screen Shot 2021-08-17 at 10 04 02 AM" src="https://user-images.githubusercontent.com/28145373/129740496-ec3248e5-099c-4106-b67b-e8cf34a6126f.png"> | <img width="1197" alt="Screen Shot 2021-08-17 at 10 04 08 AM" src="https://user-images.githubusercontent.com/28145373/129740504-2568eb5b-2c88-4bc6-a3b4-6016a9d93446.png">

**`Connected (Verified, not KYC'd) Creator`**:

Example | Example
----- | -----
<img width="401" alt="Screen Shot 2021-08-17 at 10 06 16 AM" src="https://user-images.githubusercontent.com/28145373/129740910-d4e4c21d-d1ad-4833-af3e-98780c81ab7e.png"> | <img width="1188" alt="Screen Shot 2021-08-17 at 10 06 38 AM" src="https://user-images.githubusercontent.com/28145373/129740918-8160f86d-84ce-4c8b-a353-9acd60ce1ba7.png">

**`Uphold Verified Creator`**:

Example | Example
----- | -----
<img width="397" alt="Screen Shot 2021-08-17 at 10 08 27 AM" src="https://user-images.githubusercontent.com/28145373/129741317-69a73bf0-36b4-492d-b57f-c046f6655aa1.png"> | <img width="1195" alt="Screen Shot 2021-08-17 at 10 08 53 AM" src="https://user-images.githubusercontent.com/28145373/129741325-5a8c5bee-ec27-430d-b5c6-6b0c705d7d30.png">

**`bitFlyer Verified Creator`**:

Example | Example
----- | -----
<img width="405" alt="Screen Shot 2021-08-17 at 10 10 10 AM" src="https://user-images.githubusercontent.com/28145373/129741608-bc404fa1-46d1-4a48-8253-275c2c747439.png"> | <img width="1196" alt="Screen Shot 2021-08-17 at 10 10 30 AM" src="https://user-images.githubusercontent.com/28145373/129741613-f4fefc2d-ff03-4308-8f83-cc9e6586ab66.png">

**`Gemini Verified Creator`**:

Example | Example
----- | -----
<img width="403" alt="Screen Shot 2021-08-17 at 10 11 48 AM" src="https://user-images.githubusercontent.com/28145373/129741846-d8106d6e-a1ab-4b5f-bf34-a64251c95960.png"> | <img width="1193" alt="Screen Shot 2021-08-17 at 10 11 58 AM" src="https://user-images.githubusercontent.com/28145373/129741854-c7ff4f20-b1a3-4413-ba9d-d57caf0e258c.png">

</details>
