### ISSUE TITLE
`Uncaught TypeError` in logs for Rewards

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#17364]
## Description 

While doing some testing for Gemini I noticed this in my logs several times:

`[79893:259:0805/095055.736676:ERROR:CONSOLE(3645)] "Uncaught TypeError: ug(...).setFirstLoad is not a function", source: chrome://rewards/brave_rewards_page.bundle.js (3645)`

It didn't seem to produce any adverse effects, but it's possible I just didn't notice if something else was amiss.

I don't believe this is specific to Gemini after brief discussion with @zenparsing who mentioned that this looks like it's a bit of leftover code from when some rewards page cleanup was done.

## Steps to Reproduce

There could be other ways to trigger this in the logs, but this is what I did:
pre-req, be on Brave VPN

1. Clean profile, non-Japan region, staging environment, persist logs=true, and short reconcile-interval of your choosing. Enable Gemini in brave://flags and relaunch as necessary.
2. Enable Rewards
3. Connect a KYC'd Gemini wallet
4. Confirm balance is shown in UI.
5. Set up a monthly tip for an unverified publisher (ex nike.com)
6. Set up a monthly tip for a connected, but not KYC'd publisher. (ex. ddg)
7. Set up a monthly tip for a KYC'd Uphold publisher. Confirm this publisher shows messaging on panel/banners indicating they cannot accept tips. (ex. laurenwags.github.io)
8. Set up a monthly tip for a KYC'd Gemini publisher. (ex. batcommunity.org)
9. Wait for Monthly tips to contribute.
10. Look at logs

## Actual result:

I noticed `[79893:259:0805/095055.736676:ERROR:CONSOLE(3645)] "Uncaught TypeError: ug(...).setFirstLoad is not a function", source: chrome://rewards/brave_rewards_page.bundle.js (3645)` showing around the time that the monthly contribution was started, but it's possible it showed before then and I hadn't seen it due to not looking at the logs.

## Expected result:

No mention of `[79893:259:0805/095055.736676:ERROR:CONSOLE(3645)] "Uncaught TypeError: ug(...).setFirstLoad is not a function", source: chrome://rewards/brave_rewards_page.bundle.js (3645)``

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.29.51 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
Revision	6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS	macOS Version 11.5.1 (Build 20G80)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.30.59 Chromium: 93.0.4577.58 (Official Build) beta (x86_64)
Revision	c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS	macOS Version 11.5.2 (Build 20G95)
```

Verified STR from description.
Confirmed `"Uncaught TypeError: ug(...).setFirstLoad is not a function", source: chrome://rewards/brave_rewards_page.bundle.js` is not shown in logs

**Comment by jonathansampson** [comment]
I'm seeing this error today, in version 1.29.81. It appears to be preventing me from setting up tips for unverified creators.
