### ISSUE TITLE
(Win/Linux) New Private window should be New private window, in hamburger menu

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17377]
## Implementation note (from @mkarolin; updated by @bsclifton)
- The `_override.grd` files can't be modified; these are auto-generated when we run `npm run chromium_rebase_l10n`
- The strings in the `_override.grd` files are based on automatic generic substitutions that are mapped in https://github.com/brave/brave-core/blob/master/script/lib/grd_string_replacements.py
- There is no mapping for Incognito -> private
- One option to solve this is to add a new string into `app/brave_generated_resources.grd` and then replace `IDS_NEW_INCOGNITO_WINDOW` with our string ID in code via a `chromium_src` override.

## Original issue description 

New Private window should be New private window, in hamburger menu

Windows and Linux desktop only;`macOS` is taken care of in https://github.com/brave/brave-browser/issues/17308

## Steps to Reproduce

* open the hamburger menu on the browser toolbar
* look at the capitalization of the menu items

## Actual result:

Reads `New Private window`

![windows10-menu](https://user-images.githubusercontent.com/387249/128429876-f206594b-c6e2-43e8-82bf-76115e826340.png)

## Expected result:

`New private window`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.30.3 Chromium: 92.0.4515.131 (Official Build) nightly (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 22000.120)

/cc @nullhook

**Comment by rebron** [comment]
@stephendonner Windows and Linux?

**Comment by stephendonner** [comment]
> @stephendonner Windows and Linux?

Yup.

**Comment by SebastianLF** [comment]
Let's give it a try.

**Comment by stephendonner** [comment]
> Let's give it a try.

Hi @SebastianLF by this, do you mean to say you'd like to try fixing this issue?  If so, please confirm, and I'll assign to you; thanks!

**Comment by SebastianLF** [comment]
> Let's give it a try.

Exactly. I will work on it tomorrow.

**Comment by SebastianLF** [comment]
Package 'libgnome-keyring-dev' is no more maintained on my actual version of ubuntu 20.04. I'll install version 18.04 in a new partition on my disk and make it work.

**Comment by stephendonner** [comment]
How's this going @SebastianLF?  If for some reason you're (later) unable to make progress, please unassign it back, so others can also take a look; thanks!

**Comment by SebastianLF** [comment]
@stephendonner I just installed ubuntu 18.04 and set up everything today. I certainly send a PR tomorrow.

**Comment by SebastianLF** [comment]
when "npm run init", it starts to download 16gb of data, why is that big ?

**Comment by bsclifton** [comment]
@SebastianLF running `npm run init` will download all of the source from Chromium (including history, which is the biggest). If you're able to compile locally, that's great. But you can still PR the text change without trying locally and we can try on our side with our CI

**Comment by SebastianLF** [comment]
> @SebastianLF running `npm run init` will download all of the source from Chromium (including history, which is the biggest). If you're able to compile locally, that's great. But you can still PR the text change without trying locally and we can try on our side with our CI (or building locally)

Thanks for your help I'm just wondering where to look into "brave-browser" or "brave-core" ? it's not very explicit, sorry.

**Comment by SebastianLF** [comment]
> @SebastianLF running `npm run init` will download all of the source from Chromium (including history, which is the biggest). If you're able to compile locally, that's great. But you can still PR the text change without trying locally and we can try on our side with our CI (or building locally)

Thanks for your answer, I'll do this way. Is it in 'generated_resources_override.grd' or 'generated_resources.grd' that the string should be modified?
Sorry guys for the delay.

**Comment by bsclifton** [comment]
@SebastianLF check out our wiki entry here for more info on strings:
https://github.com/brave/brave-browser/wiki/Strings-and-Localization#chromium-strings

**Comment by deepxcode** [comment]
I can work on this issue and make the PR asap.

**Comment by AnudeepGunukula** [comment]
Hi @bsclifton  @stephendonner . i had made a pr that will close this issue
kindly review it and let me know the changes if needed.

**Comment by stephendonner** [comment]
Folks, thanks for your willingness to help; @SebastianLF still has this assigned to him, so I'd like to give him first attempt at solving it; thanks!

**Comment by SebastianLF** [comment]
PR: https://github.com/brave/brave-core/pull/9821
Let me know if it works. If any error, I will change accordingly.

**Comment by stephendonner** [comment]
> PR: [brave/brave-core#9821](https://github.com/brave/brave-core/pull/9821)
> Let me know if it works. If any error, I will modify accordingly.

Sorry for the delay; I've put a couple more reviewers on your PR, who will hopefully be able to take a look soon!  🙏

**Comment by bsclifton** [comment]
Thanks for the attempt @SebastianLF - I removed the `good first issue` tag as there is some complexity here due to the replacement done for Chromium strings by Brave. More information available in https://github.com/brave/brave-core/pull/9821#discussion_r700585827

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.87 Chromium: 111.0.5563.64 (Official Build) dev (64-bit) 
--|--
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Linux

#### Confirmed string now reads `New private window with Tor`

<img width="1343" alt="Screen Shot 2023-03-11 at 11 12 03 PM" src="https://user-images.githubusercontent.com/387249/224580415-6799e796-6269-44f6-8f9c-c983144b5287.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.87 Chromium: 111.0.5563.64 (Official Build) dev (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 22H2 (Build 19045.2673)

### Confirmed string now reads `New private window with Tor`

![image](https://user-images.githubusercontent.com/387249/224581334-cbb84ee4-fc06-426b-97e1-f9bdfa254248.png)
