### ISSUE TITLE
Live tv doesn't work on Spectrum 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1737]
### Description
>Carried over from https://github.com/brave/browser-laptop/issues/13957#issuecomment-431416045 

@frostbytedata confirms still an issue on b-c as well https://github.com/brave/browser-laptop/issues/13957#issuecomment-431416045

### Steps to Reproduce
>It has nothing to do with the cable company because the video playback works perfectly fine on both Chrome and FireFox… and yes, i did click on “allow” when the Flash notification came up

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/39317076-ba53540e-4948-11e8-8ed3-686b467c15ee.png)
![image](https://user-images.githubusercontent.com/17010094/39317121-d4357da2-4948-11e8-82bf-31e035df90a0.png)

**Expected result:**

**Reproduces how often:**

### Brave Version

**Reproducible on current live release:**

### Additional Information
Added flash as enabling it doesn't load video as well
cc: @diracdeltas  @bsclifton

**Comment by tomlowenthal** [comment]
Is the behavior the same with Shields down?

**Comment by TampaJoey** [comment]
Did this issue ever get solved? 

Spectrum TV doesn't work in Brave Browser. 

Does not work with Shields down.

Spectrum TV does work in regular Chrome Browser with no problem.

**Comment by leloyon** [comment]
Still an issue as of today.

Shields are down, javascript enabled, flash is allowed.

I disabled HTTPS too. For some odd reason, this occurs in Firefox unless you use HTTP instead of HTTPS. Disabling HTTPS in Brave however, does nothing.

**Comment by ryanbr** [comment]
Safe to close @srirambv (since flash is now removed)

**Comment by srirambv** [comment]
Yes closing the issue as stale
