### ISSUE TITLE
Restoring a wallet using an invalid seed phrase causes default keyring erasure

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#17384]
## Description 

The unlock screen has a restore button which allows a user to restore using their seed mnemonic assuming they forgot their password, however in doing so if you input an invalid mnemonic—which will cause the restore to fail—the default keyring is erased. If you attempt to access wallet again by going back or just revisiting the wallet screen you are met with onboarding to create a new wallet instead of unlocking your old one since the default keyring is erased.

## Actual result:
The default keyring is erased

## Expected result:
The default keyring should only be erased if the restore succeeds

## Reproduces how often: 
Always

## Brave version (brave://version info)
Nightly (1.30.3+)

**Comment by darkdh** [comment]
QA blocked by https://github.com/brave/brave-browser/issues/17415

**Comment by LaurenWags** [comment]
Removed `QA/Blocked` since https://github.com/brave/brave-browser/issues/17415 is merged to 1.30.x miilestone

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.30.79 Chromium: 93.0.4577.82 (Official Build) beta (x86_64)
-- | --
Revision | `e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}`
OS | macOS Version 11.5.2 (Build 20G95)

- Verified test plan from https://github.com/brave/brave-core/pull/9718
- Encountered #18206
--------------
Verification passed on 

Brave | 1.30.79 Chromium: 93.0.4577.82 (Official Build) beta (64-bit)
-- | --
Revision | `e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}`
OS | Windows 11 Version Dev (Build 22458.1000)

- Verified test plan from https://github.com/brave/brave-core/pull/9718
- Encountered #18206
--------------
Verification passed on 

Brave | 1.30.79 Chromium: 93.0.4577.82 (Official Build) beta (64-bit)
-- | --
Revision | `e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}`
OS | Linux

- Verified test plan from https://github.com/brave/brave-core/pull/9718
- Encountered #18206
