### ISSUE TITLE
Crash on Chromium 94-based Brave when downloading large files.

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#17386]
## Description 

When downloading a large file the DownloadItemView widget is supposed to show certain information about the item being downloaded, such as the name and the current status. Additionally, it's also meant to show the URL but, due to changes done recently in [PR 9521](https://github.com/brave/brave-core/pull/9521) (see [issue 1638](https://github.com/brave/brave-browser/issues/1638)), Brave contains changes to only show the URL when hovering over the download item view, to save space.

Turns out that these changes were causing a crash after [CL 3044607 upstream](https://chromium-review.googlesource.com/c/chromium/src/+/3044607) whenever you attempted to download a file large enough that the DownloadItemView widget would start showing progress:
```
 base::debug::CollectStackTrace()
 base::debug::StackTrace::StackTrace()
 content::(anonymous namespace)::DumpStackTraceSignalHandler()
 (/usr/lib/x86_64-linux-gnu/libc-2.33.so+0x4103f)
 gfx::ImageSkia::width()
 views::ImageButton::ComputeImagePaintPosition()
 views::ImageButton::PaintButtonContents()
 views::Button::OnPaint()
 views::View::Paint()
 views::View::RecursivePaintHelper()
 views::View::Paint()
 views::View::RecursivePaintHelper()
 views::View::Paint()
 views::View::RecursivePaintHelper()
 BrowserView::PaintChildren()
 views::View::Paint()
 views::View::RecursivePaintHelper()
 views::View::Paint()
 views::View::RecursivePaintHelper()
 views::View::Paint()
 views::View::RecursivePaintHelper()
 BrowserRootView::PaintChildren()
 views::View::Paint()
 views::View::PaintFromPaintRoot()
 ui::Layer::PaintContentsToDisplayList()
 cc::PictureLayer::Update()
 cc::LayerTreeHost::DoUpdateLayers()
 cc::LayerTreeHost::UpdateLayers()
 cc::SingleThreadProxy::DoPainting()
 cc::SingleThreadProxy::BeginMainFrame()
 base::internal::Invoker<>::RunOnce()
 base::TaskAnnotator::RunTask()
 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
 base::MessagePumpGlib::Run()
 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
 base::RunLoop::Run()
 [...]
```

Such change also manifests when running the following 2 browser tests:
```
  BraveCheckClientDownloadRequestBaseBrowserTest.FilterRequest
  SavePackageFinishedObserverBrowserTest.Success
```

## Steps to Reproduce

Using a build of Brave based at least on the `94.0.4584.0` release:

   1. Attempt to download a large enough file (e.g. an [Ubuntu installation ISO](https://ubuntu.com/download/desktop/thank-you?version=20.04.2.0&architecture=amd64))

## Actual result:

Browser crashes.

## Expected result:

Browser should not crash and behaviour implemented to satisfy [issue 1638](https://github.com/brave/brave-browser/issues/1638) should be preserved.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Build of Brave based at least on the `94.0.4584.0` (sorry you'd have to compile it at this point)

## Miscellaneous Information:

Since this is only affecting the `cr94` branch for now, it might be considered as not urgent strictly speaking. However, the potential for causing issues of a redefinition leaking outside of its chromium_src file is not something minor, so I think it would be better to get this fixed on `master` ASAP.

**Comment by stephendonner** [comment]
https://www.leaseweb.com/platform/network is also very handy for testing file downloads of a few sizes, from various locations.
