### ISSUE TITLE
canvas.context.measureText returns '0'

### ISSUE THREAD

**Issue by rsimonton** [brave/brave-browser#1738]
## Description 

Creating a dynamic canvas element and attempting to use its 2d context to measure text always renders a width of '0'.

## Steps to Reproduce

https://jsfiddle.net/jdmtu2xL/

## Actual result:

Width of test string "Testing...1..2...3...." is: 0    :(

## Expected result:

Width of test string "Testing...1..2...3...." is: 114.392578125    :)

## Reproduces how often: 

Consistently

## Brave version (brave://version info)

Brave: 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
Revision: 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS: Mac OS X

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome? no

Thanks for Brave!

**Comment by srirambv** [comment]
The Canvas Fingerprinting is blocked. Hence you see `Width of test string "Testing...1..2...3...." is: 0 :(`. Try setting Fingerprint protection to `Allow All fingerprinting` in Shields(lion icon in URL bar) and you will see the desired result. This is expected with blocking fingerprint mechanism

**Comment by subzey** [comment]
Can't the measurement result just be of lower precision, not always `0`?

As for me, zeroing 44 out of the 53 bits of the `Double` mantissa would do. That would significantly complicate the fignerprinting while keeping all this stuff in the working condition.

[Demo](https://jsfiddle.net/subzey/tsm6p0hj/)

_Also, currently the feature can identify user as scripts now knows for sure that Brave is used_ :grin:

**Comment by bsclifton** [comment]
cc: @diracdeltas @riastradh-brave about the above comment RE: fingerprinting
