### ISSUE TITLE
Update locales for Gemini promo card

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#17383]
The Gemini promo card should be shown in all of the locales where Gemini is supported, as listed on this web site: https://www.gemini.com/areas-of-availability.

**Comment by LaurenWags** [comment]
@brave/legacy_qa just pick 2-3 different locales from https://github.com/brave/brave-core/pull/9684/files#diff-6b6ed7044cbb83bc4e57c74f9d946505e033ec70915527c7d525351b0a4c8e48R72 to check for this issue

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplans at https://github.com/brave/brave-core/pull/9684 and https://github.com/brave/brave-browser/issues/17383#issuecomment-897915330 with build 


Brave | 1.29.63 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

<details>

<summary>Steps:</summary>

1. set computer locale to France
2. clean profile
3. launched Brave
4. went to brave://flags
5. set `#brave-rewards-gemini` to `Enabled`
6. went to brave://rewards
7. enabled Rewards
8. confirmed the Gemini promo did **not** show up
<img width="1312" alt="Capture d’écran 2021-08-18 à 13 56 51" src="https://user-images.githubusercontent.com/387249/129972201-5782497a-5176-4039-b52d-f51885a296bf.png">
9. set computer locale to Brazil
10. repeated steps 2-7, above
11. confirmed the Gemini promo **did** show up
12. 
<img width="1312" alt="Captura de Tela 2021-08-18 às 13 48 53" src="https://user-images.githubusercontent.com/387249/129972351-09a2d3f6-f6ba-41f0-9128-7848bd923d8b.png">
13. set computer locale to Greece
14. repeated steps 2-7, above
15. confirmed the Gemini promo **did** show up
<img width="1312" alt="Στιγμιότυπο 2021-08-18, 1 52 14 μμ" src="https://user-images.githubusercontent.com/387249/129972496-fd151097-3cd7-445b-885a-121dece2d54f.png">
16. set computer locale to South Africa
17. repeated steps 2-7, above
18. confirmed the Gemini promo **did** show up
<img width="1312" alt="Screenshot 2021-08-18 at 14 01 29" src="https://user-images.githubusercontent.com/387249/129972623-b542fbf3-ae19-406d-8636-d1fd893c1fc5.png">

</details>
