### ISSUE TITLE
Make block tracker detect by block format if the network supports EIP 1559

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#17395]

**Comment by bbondy** [comment]
This is maybe needed in eth_json_controller more important than in block tracker. 

https://github.com/brave/ethereum-remote-client/pull/268/commits/2bb9b230d94ab856dfd1b6436039db38c804b2ad#diff-dda4db7505d587d659399c63ee2dffae9e6a715ea43a381059bbd9d053eb6d2eR237

```
 // Detect if network supports EIP-1559.
 //
// We consider EIP-1559 activated if baseFeePerGas is available in the
    // block headers.
    const { baseFeePerGas } = latestBlock
    this.networkCapabilities.updateState({
      [NetworkCapabilities.EIP1559]: baseFeePerGas !== undefined,
    })
  }
```

cc @yrliou

**Comment by onyb** [comment]
@bbondy Wondering if we can have an `isEIP1559` in [`EthereumChain`](https://github.com/brave/brave-core/blob/87452530d4818faf3bad5723e499a1ba1a57cefb/components/brave_wallet_ui/constants/types.ts#L768-L779) type, instead of exposing something in `eth_json_controller`. What do you think?

**Comment by yrliou** [comment]
Not needed now, closing.
