### ISSUE TITLE
Other sections in onboarding should open in new tabs or have "back" buttons

### ISSUE THREAD

**Issue by bflora** [brave/brave-browser#1739]
When a user goes through Brave onboarding, they are encouraged to take a few detours like "Enable Brave reward".  When a user engages with one of these by clicking the button, they are taken out of the onboarding UX and "stranded" in the new area.  These buttons should either open in new tabs or the new sections should have obvious links to return to the onboarding flow.

Example:

![image](https://user-images.githubusercontent.com/543562/47242959-51308900-d3a5-11e8-84ec-800cbbe1b089.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rossmoody** [comment]
This will get auto fixed when new onboarding process is implemented. @cezaraugusto

**Comment by cezaraugusto** [comment]
done in https://github.com/brave/brave-core/pull/708, thanks for reporting!

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

* Verified all links in welcome page opened in individual new tabs
