### ISSUE TITLE
How to arrange Tabs Vertically?

### ISSUE THREAD

**Issue by byteshiva** [brave/brave-browser#17396]
How to Tile Tabs Vertically? Is it feature available?

For example:
Vivaldi browser provides vertically arranged Tabs
![image](https://user-images.githubusercontent.com/10637299/128601764-6af89344-1bf4-4acf-9e97-915613ebe87c.png)

**Comment by srirambv** [comment]
Not available yet. There is an open issue for it. Closing this as dupe of #373
