### ISSUE TITLE
Brave Ads do not seem to be displaying in Windows 10 VMs.

### ISSUE THREAD

**Issue by Zerophase** [brave/brave-browser#17397]
## Description 
I run some crypto stuff in VMs for security purposes. Few projects seem like they might spy on me; so, I just run them in a seperate OS. In the future I'll mostly be using Qubes for crypto just for privacy purposes. According to my thinking separating every crypto web application to different VM makes it much harder for someone to compromise your hardware wallet.

There might be more to this, as I added extensions to Brave. Presearch, and Swash. I'm fine with having information I believe is safe being collected being collected when I know it is being collected.

## Steps to Reproduce
   1. Install Virtual Box
   2. Run Windows 10 in virtual box (if doesn't reproduce I can give system settings)
   3. Make sure notification settings are enabled.
   4. Install Brave.
   5. Turn on ads and set to 10 per hour.
   6. If does not reproduce install Presearch
   7. If still does not reproduce install Swash

## Actual result:
No ads display.

## Expected result:
Ads display.

## Reproduces how often: 
Reproduces every time.

## Brave version (brave://version info)
1.27.111

## Version/Channel Information:
Current release

**Comment by tmancey** [comment]
Closing as wont fix
