### ISSUE TITLE
Browser Navigation Has No Dark Mode

### ISSUE THREAD

**Issue by simonferndriger** [brave/brave-browser#17402]
In contrast to (regular) Google Chrome, Brave does NOT (yet) adapt its navigation (tabs, address bar, bookmark bar) to (Windows) dark mode - it always stays bright. Would be nice if that would be the case in the future.

**Comment by srirambv** [comment]
Should work fine on Windows as long as you set it as `Same as Windows`
![image](https://user-images.githubusercontent.com/17010094/128660085-35f754a6-dadd-4e3d-9d2a-775aa1c1350f.png)

Mind adding screenshots for comparison? Also do you have multiple profiles in which case it maybe using the profile theme set during its launch

**Comment by simonferndriger** [comment]
Thanks, actually, I already have the setting on "Same as Windows". However, only the lower part is switching into dark mode, even with my latest version of Brave...

![Screenshot 2021-08-09 111908](https://user-images.githubusercontent.com/1435963/128684799-7f9c7356-33fa-475e-813a-f506b92b05b1.jpg)

**Comment by rebron** [comment]
@simonferndriger Can you go into brave://settings/manageProfile. You'll need to have the first theme color selected for light/dark more to apply.

<img width="682" alt="Screen Shot 2021-08-09 at 9 13 55 AM" src="https://user-images.githubusercontent.com/5951041/128738859-04c1196f-53a6-4368-ba8e-7ec4ecd863d5.png">

**Comment by simonferndriger** [comment]
Thanks, that was it! I previously had an additional profile for testing,
that must have changed this setting...

Am Mo., 9. Aug. 2021 um 18:14 Uhr schrieb Rafael Ebron <
***@***.***>:

**Comment by bsclifton** [comment]
Great catch, @rebron 🙂
