### ISSUE TITLE
Trigger fetch balance flow after the wallet is linked (Uphold)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17401]
## Description

As of v1.29 for Uphold-verified users, users have to refresh their Brave Rewards settings page in order to see their balance after verifying/linking.

## Solution

Users should not have to press refresh before seeing their balance appear. We should trigger the `fetch balance` flow only after the wallet is linked.

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.29.66 Chromium: 92.0.4515.159 (Official Build) beta (x86_64)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | macOS Version 10.15.7 (Build 19H1323)
```

Steps:
1. Clean profile, staging env
2. Enable Rewards
3. Click on Verify Wallet, navigate to Uphold option
4. Click Uphold and then Continue to login link
5. Click Authorize on Uphold page
6. Enter login info
7. When redirected to the brave://rewards page, confirm balance is shown without needing a page refresh

Confirmed no page refresh was required to see balance after linking KYC'd Uphold account:
<img width="402" alt="Screen Shot 2021-08-20 at 11 28 07 AM" src="https://user-images.githubusercontent.com/28145373/130257258-319cd887-f7e0-4b3e-a0f7-32954f648385.png">

**Comment by srirambv** [comment]
Removing Android label as the fix is only working on Desktop as per above comment. Logged #17691 as a followup Android only issue
