### ISSUE TITLE
Rename Brave Talk beta domain name

### ISSUE THREAD

**Issue by mrose17** [brave/brave-browser#17406]
This issue is being created for a milestone, cf., https://github.com/brave/brave-site-specific-scripts/pull/63

**Comment by stephendonner** [comment]
confirmed I got version 1.0.50 in build 1.28.105 Chromium: 92.0.4515.131 (Official Build) (x86_64) and was able to start a call from beta.talk.brave.com after enabling Rewards :thumbsup:
