### ISSUE TITLE
The last update of brave browser freezes and crash in all version of windows

### ISSUE THREAD

**Issue by zekecarter** [brave/brave-browser#17400]
The last update of brave browser freezes and crash in all version of windows and the ram memory is increased in task manager.

I use deepfreeze so I was able to make the test video for them

In the video I show the correct operation and the moment when it starts to fail
[https://youtu.be/GYkDytEf-XE](https://youtu.be/GYkDytEf-XE)

Data from my operating system
![system](https://user-images.githubusercontent.com/83554130/128637086-2772e789-eec5-4fb5-a1c8-14b902e727fa.png)

**I hope you can solve the problem, because I really appreciate this browser**

**Comment by CrashVHub** [comment]
Same on Manjaro i3WM; since the last update from the AUR, brave uses up all my RAM prints out the following error lines:
![2021-08-08-193330_1920x1080_scrot](https://user-images.githubusercontent.com/52385222/128640538-0cd73626-9c81-454d-aa41-05733bb63cde.png)

**Comment by zekecarter** [comment]
The problem is the built-in adblock lists and only programmers can fix it.

of all the lists that we activate from brave adblock one or some of them causes the failure.

I will leave a video of the operation and the cause of the problem.
[https://youtu.be/xGqpZtCU324](https://youtu.be/xGqpZtCU324)

A quick solution while the programmers solve, is to uninstall the browser and use the Clean Space temporary file cleaner from the Cyrobo website. ccleaner and the other cleaners do not completely clean the uninstalled data from the browser, which confirmed

**I hope I have contributed so that the programmers can correct the problem**

**Admin Please Fix It**

**Comment by shom13** [comment]
This is a serious issue. It not only crashes, but freezes the entire system as it takes up all available RAM. And I am on linux desktop, so its safe to say its not just a windows problem, its happening across operating system. Its definitely a browser problem, as this started happening after recent update. 

Please resolve the issue as quickly as possible, as i use brave as my default browser, for now forced to use firefox.

**Comment by Tonev** [comment]
@iefremov @rebron 

Sorry for disturbing you, but Brave Community is literally flooded with threads regarding crashes. I haven't had seen such a thing before, countless threads regarding crashes.

**Comment by iefremov** [comment]
Thanks @Tonev , I'm looking into this. We have the dumps on our radars

**Comment by Tonev** [comment]
@iefremov 

You're most welcome! Let me know if you would like me to check Community for anything specific that could help you, will be happy to help ;)

**Comment by iefremov** [comment]
@zekecarter @CrashVHub @shom13 Hey folks, thanks for reporting this. Could you please share how many of regional lists do you have enabled on brave://adblock?

**Comment by shom13** [comment]
Cant check right now as when i open brave the whole system crashes. It takes a while for brave itself to crash. Hence cant use brave at all. But as far as i remember while installing the defauls+1 or at most 2.

**Comment by antonok-edm** [comment]
The issue has been resolved, although if you're still experiencing the freezing please see [this Community post](https://community.brave.com/t/notice-users-seeing-browser-freeze-or-crash-may-have-faulty-ad-block-updater-component/273097) for the browser-side fix.
