### ISSUE TITLE
I can't recieve the BAT on Brave Nightly

### ISSUE THREAD

**Issue by Willy-Willy-Will** [brave/brave-browser#17403]
## Description 
This bug has started 3 months ago, I thinked that this'd be fixed soon, but I'm still with Bug so I decided open this issue.

Basically, when I try collect my BAT I can't, when i touch on recieve the process starts to loading forever.

Sometime the loading stop and the Button "Recieve" appears again but if I click It starts to loading again, This started 3 months ago and I have 3 rewards notifications (3.500 bat on totally) that I can't recieve, I'd wanna switch to Brave release but I don't wanna lost my BAT, please fix it.

Note 1: I use Brave Nightly

Note 2: I have a parent that use Brave Release on Android and his can recieve normally.

## Steps to reproduce 

   1. Click on some ads in the month.
   2. Wait the day to recieve the rewards.
   3. Try to collect the rewards.

## Actual result 
![screenshot-1](https://user-images.githubusercontent.com/65524034/128647321-b17c4349-dd18-46f5-bdfe-606ea122132e.jpg)
![screenshot-0](https://user-images.githubusercontent.com/65524034/128647332-b3e35673-51d8-4cc5-9480-065b0c15b6e0.jpg)

## Expected result
Recieve the Rewards

## Issue reproduces how often 
The bug happeng everytime that I try recieve the Rewards

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
No (A parent can recieve the reward)

- Can you reproduce this issue with the current Play Store Beta version? 
I don't know

- Can you reproduce this issue with the current Play Store Nightly version?
Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 10
   
## Brave version
Brave - Nightly  1.30.6, Chromium 92.0.4515.131

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
No

- Does the issue resolve itself when disabling Brave Rewards?
No

- Is the issue reproducible on the latest version of Chrome?
No

**Comment by Miyayes** [comment]
1. Please update to the latest version of the Brave app and try again. 
2. Check if your phone passes Android SafetyNet. If it does not pass Android SafetyNet, you won't be able to claim.

For continued help, kindly use our support forum: https://community.brave.com.
