### ISSUE TITLE
BR notification should be removed for Private tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1741]
## Description 
BR notification should be shown only for normal tabs. For PT/Guest/Tor tabs notification should not be shown. Currently, BR notification shown for PT's, this needs to be removed.

## Steps to Reproduce

   1. Clean profile on 0.55.18
   2. Enable Rewards
   3. Verify the grants notification on BAT logo (URL bar)
   4. Open Private tab
   5. Verify that the grants notification shown for PT's 

## Actual result:
BR notification shown for Private tabs also
![notification on pt s](https://user-images.githubusercontent.com/38657976/47243971-778c0e00-d411-11e8-9805-a36b7387853e.gif)

## Expected result:
BR notification should be removed for Private tabs

## Reproduces how often: 
Easy

## Brave version (brave://version info)

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No
- Does it reproduce on browser-laptop? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by tomlowenthal** [comment]
@mandar-brave & I have previously chatted about this. The short-term goal for Rewards' interactions with the various private modes is as follows.
- Rewards pyramid icon greyed out and non-interactive in URL bar.
- Brave Rewards item in hamburger menu greyed out.
- Site views and so on in private modes don't get counted towards attention for auto-contribute.

Later, we can work out how to do one-off tipping with rewards in private modes, but that's not currently on the table.

**Comment by NejcZdovc** [comment]
closing this one as we hide BAT in private window

https://github.com/brave/brave-browser/issues/4593
