### ISSUE TITLE
Add brave vpn flags to brave://flags on nightly

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#17416]

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


Brave | 1.30.18 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

### Steps:
1. new profile
2. launched Brave
3. went to `brave://flags` and set `Enable experimental Brave VPN` to `Enabled`
4. confirmed I saw a (placeholder/inactive) `* VPN` button to the right of the BAT icon in the toolbar

* Confirmed the button is inactive
* Confirmed the button has hover and click states

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-08-12 at 1 11 15 PM" src="https://user-images.githubusercontent.com/387249/129263536-68e2aa02-b082-4d81-93d0-66ee669c96de.png"> | <img width="1312" alt="Screen Shot 2021-08-12 at 1 12 26 PM" src="https://user-images.githubusercontent.com/387249/129263546-6a4220f4-7809-4183-aba9-7d596c6ef92a.png">
