### ISSUE TITLE
Unable to start the video call via `Try it now` promo prompt

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#17421]
## Description 

Unable to start the video call via `Try it now` promo tooltip

## Steps to Reproduce

   1. Clean profile 1.28.x/1.29.x/130.x
   2. Confirm Brave Talk study is enabled in brave://version
   3. Forward the OS clock to 3 days
   4. Open a new tab page/existing new tab page
   5. Observe the `Try it now` promo tooltip in NTP
   6. Click on `Try it now`  
   7. Click on `Start a video call` doesn't initiate the video call, throwing the error message as `Request failed: internal error`

 (launched brave using `brave.exe --variations-server-url=https://variations.bravesoftware.com/seed` in `1.28.105`)

## Actual result:

 Click on `Start a video call` doesn't initiate the video call, throwing the error message as `Request failed: internal error`
![image](https://user-images.githubusercontent.com/38657976/128839134-09178453-e3fc-4588-8bd3-0160598993b2.png)
## Expected result:
Should not get any error and should be able to start the video call

## Reproduces how often: 

Easy
## Brave version (brave://version info)

RC:  1.28.105
Beta: 1.29.55
Nightly: 1.30.9

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @petemill @mrose17

**Comment by mrose17** [comment]
Fascinating. I am not surprised that messing with the clock causes problems with cryptographic operations. perhaps there is a better way to test this?

**Comment by GeetaSarvadnya** [comment]
I am not aware of the other ways to test this in a clean profile. @petemill - Any thoughts on this?

**Comment by mrose17** [comment]
Here are two possibilities:

First,

1. Set the clock back 3 days and then create a new profile.
2. Quit the browser.
3. Set the clock to the current time and start the browser.

Second, create a new profile at the current time. Periodically check to see if the tooltip comes up within the first three days. (Obviously, this is something that will take at least three days to test...)

**Comment by GeetaSarvadnya** [comment]
@mrose17 we just followed the steps mentioned in the slack thread mentioned below,  it worked fine we're waiting for confirmation from @petemill  
https://bravesoftware.slack.com/archives/C7VLGSR55/p1628602926082900?thread_ts=1628596170.077200&cid=C7VLGSR55

**Comment by GeetaSarvadnya** [comment]
Works as exoected. closing the issue.
