### ISSUE TITLE
Long domain names overflow Rewards screen

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#17434]
## Steps to Reproduce
   1.  Enable Brave rewards.
   2. Visit some super long domain names.
   3. Go to the Brave Rewards page.

## Actual result:
![brave-rewards-all-contributions](https://user-images.githubusercontent.com/1102886/129035421-19a9ddd8-6bf3-42ff-aad2-f8c5a8173e84.png)
![brave-rewards-auto-contribute](https://user-images.githubusercontent.com/1102886/129035425-f2e6500a-f7a8-4d64-9af1-d0919d358b25.png)

## Expected result:
Overly long domains shouldn’t be allowed to break the page design.

Note that the **entire domain must remain visible,** so line-breaking is expected to string overflow clipping. Clipping it may allow for sneaky dastardly behavior like pretending to be `super-cool-domain-you-really-like-com-the-rest-is-clipped.github.io.` The example screenshot shows IPFS domains, but this is a generic problem.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
1.27.111 Chromium: 92.0.4515.131

## Version/Channel Information:
stable

## Miscellaneous Information:
I like pistachio ice cream.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.53.82 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```
- Confirmed that long domains doesn't break the page design
- Confirmed that long domain text is wrapped within the page so that user can read it completely 
![image](https://github.com/brave/brave-browser/assets/38657976/db8111ea-437a-4580-8af8-f8cfb12d6b0d)
