### ISSUE TITLE
Dismiss the Tipping banner on user cues that indicate that they're moving on

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#1743]
## Description 

Dismiss the tipping banner when the user
- clicks outside of the banner
- types in the URL bar

to support the user's natural, fluid navigation/browsing experience, instead of requiring them to explicitly 'close' the banner.

![screen shot 2018-10-19 at 12 12 38 pm](https://user-images.githubusercontent.com/4369856/47244988-5e9d4180-d3ac-11e8-99a2-a35f66b36022.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by agentofuser** [comment]
If #4590 is not going to be fixed, I think this issue should be made higher priority. It's pretty annoying for the banner not to go away on its own.

Also, it should be possible to dismiss it mouselessly with Esc and/or Enter.

**Comment by LaurenWags** [comment]
++ on re-prioritizing this one based on discussions in #4590

**Comment by Miyayes** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/23740.
