### ISSUE TITLE
private window with tor is not working on windows version Version 1.27.111

### ISSUE THREAD

**Issue by KavyanshJain** [brave/brave-browser#17433]
Private window with tor is not connecting and always stuck at disconnected. I even tried to disable and enable the private window with tor option in the extension settings. 

## Steps to Reproduce

   1. I not know what is "steps to reproduce" is

## Actual result:
![image](https://user-images.githubusercontent.com/69588134/129032822-d61ec8d5-eb6d-42d5-b43e-05f2e0335ca5.png)

## Expected result:
Initializing or connected

## Brave version
Brave Version - 1.27.111 
Chromium: 92.0.4515.131 
Current release, 
OS - Windows 11

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not know
- Can you reproduce this issue with the dev channel? Not know
- Can you reproduce this issue with the nightly channel? Not know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not related
- Does the issue resolve itself when disabling Brave Rewards? Not related
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
@KavyanshJain Can you update to the latest version of Brave from brave://settings/help to 1.28.105 and can you take a look at brave://components after opening up a Tor Window. Let me know if you see a Brave Tor Client updater as one of the components.

**Comment by KavyanshJain** [comment]
> @KavyanshJain Can you update to the latest version of Brave from brave://settings/help to 1.28.105 and can you take a look at brave://components after opening up a Tor Window. Let me know if you see a Brave Tor Client updater as one of the components.

hey thanks to the reply, updated the brave to latest 1.28.105 version and I also check the `Brave://components` it shows -
![image](https://user-images.githubusercontent.com/69588134/129190369-58d9b42f-ed6f-4125-9e7b-4d7078a8f963.png)
![image](https://user-images.githubusercontent.com/69588134/129190385-279074f7-2803-4e95-8e43-9135df85bec0.png)

no tor component there. And on more when I tap check for update for any component it says components not update how can I update them and I also don't know much about it

**Comment by KavyanshJain** [comment]
**Edit: After I turn on and off private windows with tor I get the option in components and I touched nothing and start a tor window it works.** 
But still can you show me how to update this components or are this already updated because I am getting component not updated when I click to update in the components section to any component

**Comment by rebron** [comment]
@KavyanshJain If you see the component there, it should be the most up to date. If you manually check for update and it says `component not updated`, you have the latest. If you refresh brave://components it should read `Up to date`
