### ISSUE TITLE
Disk image for beta should be blue color

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17441]
## Description 

The `beta` disk image should be blue

(I missed this when verifying https://github.com/brave/brave-browser/issues/16953; @LaurenWags caught it and I'm filing.)

## Steps to Reproduce

   1. download `Brave-Browser-Beta-x64.dmg` from `https://github.com/brave/brave-browser/releases/tag/v1.29.57`
   2. double-click to unpack/extract
   3. look at the disk image colors

## Actual result:

The disk image for the `beta` channel's browser is still orange.

<img width="711" alt="Screen Shot 2021-08-11 at 10 58 58 AM" src="https://user-images.githubusercontent.com/387249/129080300-a04e73bb-0d18-41c3-8826-ee66fa76e39f.png">

## Expected result:

The disk image should be the same blue color as the icons.

Disk image:

![image](https://user-images.githubusercontent.com/2388823/129230510-c32bfbfb-79bb-40a2-80e4-66a688cca355.png)

Figma: https://www.figma.com/file/bqB5WK3g9kik7EVDAwkqza/Brand-Logos-and-Logotypes?node-id=28%3A974

Download page image:

![image](https://user-images.githubusercontent.com/2388823/129230549-ee96d7c8-001b-4a9e-a6ee-742d06369c37.png)

Figma: https://www.figma.com/file/bqB5WK3g9kik7EVDAwkqza/Brand-Logos-and-Logotypes?node-id=65%3A1674

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.29.57 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.1 (Build 20G80)

/cc @rebron @simonhong @kliu

**Comment by Tonev** [comment]
@stephendonner 

First of all, excuse me for "hijacking" your Github issue, but I'm not aware who I'm supposed to contact about it. I see you guys are changing the icon everywhere but it's still the old one at https://brave.com/download-beta/. I'm mentioning it because not long ago a user in Community was confused what was going on, and guess we can see where the confusion could come from.

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in `Windows 10 x64 - 1.29.55`

![image](https://user-images.githubusercontent.com/38657976/129158378-cb18652b-a0f7-4136-9417-a54cddfdd4d4.png)

**Comment by Tonev** [comment]
@GeetaSarvadnya 

Thank you for the quick reply! I don't have any issues with the `Brave Beta` icon after installation, it's the new blue icon as it's supposed to be. I meant the `Brave Beta` icon is still the old one at https://brave.com/download-beta/ & https://brave.com/download-nightly/ which is confusing to users.

**Comment by karenkliu** [comment]
Assets added!

**Comment by simonhong** [comment]
Removed `OS/Windows` label because I can see proper icon on Windows.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.58 Chromium: 94.0.4606.54 (Official Build) beta (x86_64)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. downloaded `https://github.com/brave/brave-browser/releases/download/v1.31.58/Brave-Browser-Beta-x64.dmg`
2. double-clicked to unpack/extract
3. dragged the Brave Beta icon to `Applications`
4. launched Brave
5. observed the following Brave Beta icons

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="115" alt="Screen Shot 2021-09-22 at 6 23 57 PM" src="https://user-images.githubusercontent.com/387249/134442489-6bdf9d67-0550-4a1e-b714-bab598f4f400.png"> | <img width="601" alt="Screen Shot 2021-09-22 at 6 24 07 PM" src="https://user-images.githubusercontent.com/387249/134442490-bd3f6edb-db12-44cd-b94e-d070f27b3b5f.png"> | <img width="1009" alt="Screen Shot 2021-09-22 at 6 25 04 PM" src="https://user-images.githubusercontent.com/387249/134442491-23be003b-a4e0-4612-a8e5-9324614d8306.png"> | <img width="354" alt="Screen Shot 2021-09-22 at 6 25 14 PM" src="https://user-images.githubusercontent.com/387249/134442492-ef10d5ef-ce67-4c5c-88e5-92d2926a8a8a.png"> | <img width="42" alt="Screen Shot 2021-09-22 at 6 25 35 PM" src="https://user-images.githubusercontent.com/387249/134442494-9bb173d1-9da8-447d-8222-0a8050aea4a3.png">


**NOTE:** https://github.com/brave/brave-browser/issues/18223 (first screenshot there) is still outstanding, and will be verified separately.
