### ISSUE TITLE
Mouse loading animation bug

### ISSUE THREAD

**Issue by lostopkk** [brave/brave-browser#17448]
## Description 
when I start the browser, my mouse keeps doing the loading animation forever until I close the browser

## Steps to Reproduce

   1. Open the browser
   2. Wait for 5 segonds
   3. Bug starts

## Actual result:
https://user-images.githubusercontent.com/50776714/129114968-5bcba803-9585-45c3-abeb-d5c565ba7483.mp4

## Expected result:
no mouse loading animation

## Brave version (brave://version info)
1.28.105

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- no
- Does the issue resolve itself when disabling Brave Rewards? 
- no
- Is the issue reproducible on the latest version of Chrome? 
- no

**Comment by rebron** [comment]
Hi @lostopkk We're on version 1.62.162. We suspect this is no longer occurring? We can reopen if you're still encountering the mouse icon issue.
