### ISSUE TITLE
Filter out rb_clickid from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#17451]
`rb_clickid` was added as a tracking parameter in https://github.com/jparise/chrome-utm-stripper/pull/44, but it's very hard to find any information about it (note that [we should leave `linkid` alone for webcompat reasons](https://github.com/jparise/chrome-utm-stripper/issues/46)).

It's used all over the place on Russian sites, for example:

    https://veryberrylab.ru/catalog/bukety-s-klubnikoy/?rb_clickid=86252549-1618003652-1663225310&size=1&price_from=3000&price_to=5000

A lot of Russian websites also exclude it in their `robots.txt`, for example https://esh-derevenskoe.ru/robots.txt.

The [TopMailRu tracker](https://top.mail.ru/help/en/) does seem to use it, though their [minified code](https://top-fwz1.mail.ru/js/code.js) is especially hard to decipher.

The only [blog post](http://madik.ru/web-analitika/metki-gclid-yclid-ymclid-fbclid/) I could find about it only mentions that it's often seen in combination with `utm_source=mytarget` though the example above shows that it's not always the case.

Based on its name and the fact that it's high-entropy, we should assume that this is tracking users as opposed to campaigns.

**Comment by stephendonner** [comment]
@fmarier mind providing a simplified testcase? (I just want to be sure we don't miss anything.) Thanks!

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan at https://github.com/brave/brave-core/pull/9733 with build


Brave | 1.30.27 Chromium: 92.0.4515.159 (Official Build) nightly (x86_64)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | macOS Version 11.5.2 (Build 20G95)


Steps:

1. new profile
2. launch Brave
3. opened Developer Tools, clicked on the Network panel
4. loaded `https://brave.com/?rb_clickid=1234567890abcdef`
5. confirmed that the redirected page loaded doesn't contain the `rb_clickid=` parameter

<img width="1675" alt="Screen Shot 2021-08-17 at 8 53 19 AM" src="https://user-images.githubusercontent.com/387249/129761158-e6150822-6a3a-45a5-84a3-072895cd0509.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.30.76 x64 build
- Verified test plan from [brave/brave-core#9733](https://github.com/brave/brave-core/pull/9733)
---------
Verification passed on Samsung Tab A with Android 11 running 1.30.76 x64 build
- Verified test plan from [brave/brave-core#9733](https://github.com/brave/brave-core/pull/9733)
