### ISSUE TITLE
Top sites in ntp

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#17454]
## Description 

Hi i like different privacy implementations of brave browser, they do a solid job at desktop, yet android version lacks several privacy control features, currently i am really annoyed at brave not giving me an option to disable top sites in ntp (there is no way to disable it) and even worse this feature connects with google server to fetch those websites based on my country and not only that it also makes connection with those top sites (that i would actually never visit most of them), this is a feature of chrome browser most chromium forks have alreadey disabled or removed this, i  expect brave as a privacy browser to either remove it or give an option to disable it.

## Steps to reproduce 

   1. Install/update Brave browser on your android device
   2. Enable your internet connection
   3. Open brave browser

**Comment by thefallofbecause** [comment]
On the new tab page with the top sites visible tap the 3 dots, then "Remove Widget".

**Comment by ABodmer** [comment]
> On the new tab page with the top sites visible tap the 3 dots, then "Remove Widget".

I have a clean new tab page (no widgets or wallpapers) besides my concern is fetching these top sites not just showing them, the problem with brave is even when none of the ntp options are on (widgets, wallpaper etc) it still fetches top websites this is not implemented by brave team its a feature in chromium and chrome that most forks disable, yet brave as a privacy browser decided to keep it there for some unknown reason.

**Comment by thefallofbecause** [comment]
https://github.com/brave/brave-browser/issues/12263

**Comment by bsclifton** [comment]
Thanks for ID-ing the duplicate issue, @thefallofbecause 😄 Closing this one in favor of https://github.com/brave/brave-browser/issues/12263
