### ISSUE TITLE
Updating beta channel to new version crashes browser

### ISSUE THREAD

**Issue by garrettr** [brave/brave-browser#1745]
## Description 

When a new update is released for the beta channel, it is downloaded and queued to install on the next browser restart. If I trigger the installation of the update in any way, e.g. by manually clicking **Relaunch**, or simply quitting the browser after the update is finished downloading, the browser crashes.

This cycle of downloading the latest update, attempting to install it, and crashing repeats several times before the update eventually installs successfully and the browser restarts without crashing.

## Steps to Reproduce

   1. Be me, using the latest beta channel release (currently https://github.com/brave/brave-browser/releases/tag/v0.56.5)
   2. Learn that an upgrade for the beta channel is available
   3. Navigate to `chrome://settings/help` (or click **About Brave** in the **Brave**/main application menu)
   4. Wait for the upgrade to be downloaded
   5. Click **Relaunch**

## Actual result:

The browser immediately crashes. If I start the browser again, I am prompted to restore my previous session due to a crash.

## Expected result:

The browser should install the update and relaunch without crashing. All of my tabs from my previous session should be open and I should not need to restore them.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

I experienced this behavior for each of the last two beta channel updates:

1. v0.55.13 -> v0.55.14
2. v0.55.14 -> v0.56.5

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds?
I have only seen this issue in the beta channel, but it may affect other channels as well.

### Additional Information

I have only noticed this issue on macOS 10.13.6 (where I am using the beta channel release as my daily driver for dogfooding purposes) and do not know if it affects any other platforms.

**Comment by LaurenWags** [comment]
Verified passed on `macOS x64 10.12.6` when updating from 0.58.12 -> 0.58.14 on `test` channel.

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

cc @kjozwiak for verification on his mac
