### ISSUE TITLE
Filter out s_cid from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#17452]
`s_cid` is the [default campaign tracking code for Adobe Site Catalyst](https://help.goacoustic.com/hc/en-us/articles/360043311613-Track-lead-sources). Based on an [official blog post](https://blog.adobe.com/en/publish/2012/07/19/sitecatalyst-finance-fundamentals-external-campaign-performance-part-1.html) and [third-party documentation](https://www.omeda.com/knowledge-base/email-web-tracking/) though it does seem like it can be used for very granular tracking.

These sites have examples of it being used in the wild:

- https://kauffmanmuseum.org/exhibitions/travelingexhibits/vapes-exhibit/research-documents/
- https://seclists.org/fulldisclosure/2018/Jul/63

Since there are lots of examples of this parameter being used as a high-entropy ID, I think it would be preferable to block.

**Comment by stephendonner** [comment]
@fmarier mind providing a simplified testcase? (I just want to be sure we don't miss anything.) Thanks!

**Comment by fmarier** [comment]
@stephendonner Sure, this is pretty simple to test, have a look at the test plan on https://github.com/brave/brave-core/pull/9733

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan at https://github.com/brave/brave-core/pull/9733 and build 


Brave | 1.30.27 Chromium: 92.0.4515.159 (Official Build) nightly (x86_64)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:
1. new profile
2. launch Brave
3. opened Developer Tools, clicked on the `Network` panel
4. loaded `https://brave.com/?s_cid=abcdef1234567890`
5. confirmed that the redirected page loaded doesn't contain the `s_cid=` parameter

<img width="1675" alt="Screen Shot 2021-08-17 at 8 54 13 AM" src="https://user-images.githubusercontent.com/387249/129760712-67b51e91-158b-4373-84b6-62792252f9b9.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.30.76 x64 build
- Verified test plan from [brave/brave-core#9733](https://github.com/brave/brave-core/pull/9733)
---------
Verification passed on Samsung Tab A with Android 11 running 1.30.76 x64 build
- Verified test plan from [brave/brave-core#9733](https://github.com/brave/brave-core/pull/9733)
