### ISSUE TITLE
YouTube Notification Bell Menu doesnt work anymore since latest Version

### ISSUE THREAD

**Issue by fuzzygoerk** [brave/brave-browser#17465]
## Description 

Since the latest update im no more able to open the notification menu on youtube on the top right corner (bell icon) that displays a list of the latest notification/videos.

## Steps to Reproduce

   1. open youtube.com
   2. click on the bell icon
   3. no list will be displayed

## Reproduces how often: 

easily reproduced

## Brave version (brave://version info)

Brave | 1.28.105 Chromium: 92.0.4515.131 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
Betriebssystem | Linux
JavaScript | V8 9.2.230.22
User-Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes!
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? yes. workaround, turn on ublock origins, disable shields on youtube
- Does the issue resolve itself when disabling Brave Rewards?  no
- Is the issue reproducible on the latest version of Chrome?  no

**Comment by Brave-Matt** [comment]
Adding that it appears to affect other buttons in that same place on the page for some users (Account/avatar icon menu for example).

Majority of users seeing this are reporting Windows 10 OS. Some additional reports + user details:

- https://community.brave.com/t/youtube-notification-bell-not-displaying-with-shields-up-on-latest-version/273974/18?u=mattches
- https://community.brave.com/t/youtube-notification-bell-not-displaying-with-shields-up-on-latest-version/273974/19?u=mattches
- https://community.brave.com/t/youtube-notification-bell-not-displaying-with-shields-up-on-latest-version/273974/20?u=mattches
- https://community.brave.com/t/youtube-notification-bell-not-displaying-with-shields-up-on-latest-version/273974/21?u=mattches
- https://community.brave.com/t/youtube-notification-bell-not-displaying-with-shields-up-on-latest-version/273974/22?u=mattches

**Comment by fuzzygoerk** [comment]
It doesnt seem to be only a Windows 10 related problem.

**Comment by Brave-Matt** [comment]
Additional reports:
https://community.brave.com/t/notifications-button-youtube/274105/6 
https://community.brave.com/t/youtube-dropdowns-broken-by-shields/274146/3

**Comment by kjozwiak** [comment]
Reproduced on `Win 10 x64` using the following build:

```
Brave | 1.30.17 Chromium: 92.0.4515.131 (Official Build) nightly (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 19042.1151)
```

![Capture](https://user-images.githubusercontent.com/2602313/129245402-5a5db392-3341-4a0f-be9b-9aed450311c7.PNG)

**Comment by Tonev** [comment]
Another Community thread, the author mentioned that they can't reproduce the issue on their Mac machine.

https://community.brave.com/t/cannot-click-on-the-profile-or-notification-button-on-youtube/274173

**Comment by ryanbr** [comment]
In brave://components/  Update "Brave Ad Block Updater" too Version: 1.0.1030, then refresh the page @fuzzygoerk  does that help?

**Comment by itsmordecai** [comment]
I also had this issue including other buttons and context menus on YouTube not working but a solution provided in the Community to an unrelated issue somehow helped resolve the YouTube issues. 

Below is the Notice that helped me. I'm on Windows 10 21H1 but it has also worked on another user on macOS as seen [here](https://community.brave.com/t/youtube-dropdown-not-working-with-ad-and-track-blocking-enabled/274195/4)
https://community.brave.com/t/notice-users-seeing-browser-freeze-or-crash-may-have-faulty-ad-block-updater-component/273097

**Comment by kjozwiak** [comment]
> In brave://components/ Update "Brave Ad Block Updater" too Version: 1.0.1030, then refresh the page @fuzzygoerk does that help?

As per the above, this should be fixed with `Brave Ad Block Updater - Version: 1.0.1030` 👍 The `Brave Ad Block` component will update itself but if you want to force an update, you can follow what @ryanbr mentioned above via:

* go into `brave://components`
* look for `Brave Ad Block Updater` and click on `Check for update`

You should pull the following:

```
`Brave Ad Block Updater - Version: 1.0.1030`
```

Once you have the above version, the bell notification should work on YT.

**Comment by fuzzygoerk** [comment]
> > In brave://components/ Update "Brave Ad Block Updater" too Version: 1.0.1030, then refresh the page @fuzzygoerk does that help?
> 
> As per the above, this should be fixed with `Brave Ad Block Updater - Version: 1.0.1030`  The `Brave Ad Block` component will update itself but if you want to force an update, you can follow what @ryanbr mentioned above via:
> 
> * go into `brave://components`
> * look for `Brave Ad Block Updater` and click on `Check for update`
> 
> You should pull the following:
> 
> ```
> `Brave Ad Block Updater - Version: 1.0.1030`
> ```
> 
> Once you have the above version, the bell notification should work on YT.

Hello!

just updatet to Version: 1.0.1031 and its working fine now. thank you so much :)
