### ISSUE TITLE
Blocking trackers and ads also blocks some YouTube buttons

### ISSUE THREAD

**Issue by japaweiss** [brave/brave-browser#17464]
Blocking trackers and ads also blocks some YouTube buttons.
Other users also report this on reddit: https://www.reddit.com/r/brave_browser/comments/p2zb1o/some_youtube_buttons_not_working_anymore/

**Comment by itsmordecai** [comment]
This kinda helped me, you can check this [comment](https://github.com/brave/brave-browser/issues/17465#issuecomment-897982046) I left

**Comment by ryanbr** [comment]
Safe to close this, fix has rolled out automatically, if not follow: https://github.com/brave/brave-browser/issues/17465#issuecomment-897983874
