### ISSUE TITLE
Additional settings text distorted in few locales - follow up to #17109

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#17461]
Original issue was filed by @GeetaSarvadnya via https://github.com/brave/brave-browser/issues/17109. However, https://github.com/brave/brave-core/pull/9537 didn't resolve the problem as per https://github.com/brave/brave-core/pull/9537#issuecomment-897345996. Creating a follow up as the original issue already has a PR associated with it.

> 
> 
> ## Description 
> 
> `Additional settings` text distorted in few locales
> 
> ## Steps to Reproduce
> 
> 
>    1. Clean profile 1.27.107 
>    2. Set OS locale to `Germany`/`France`/ `Hindi` or any other locale apart from `English`
>    3. Open brave://settings
>    4. Verify the `Additional Settings` text
> 
> ## Actual result:
> 
> 
> `Additional settings` text distorted in few locales
> 
> `1.27.107` - `Germany`
> ![image](https://user-images.githubusercontent.com/38657976/126656661-60b8be7f-8dfb-4443-aaa6-226de1e0c3cd.png)
> 
> `France`
> ![image](https://user-images.githubusercontent.com/38657976/126658431-a0febb95-257b-4154-ac87-d4aa8a8b2119.png)
> 
> ## Expected result:
> 
> `1.26.77`
> ![image](https://user-images.githubusercontent.com/38657976/126656529-9ea0c01f-cfb2-452c-b59e-894b14182eca.png)
> 
> ## Reproduces how often: 
> 
> Easy
> 
> ## Brave version (brave://version info)
> 
> 
> 
> Brave | 1.27.107 Chromium: 92.0.4515.107 (Offizieller Build) (64-Bit)
> -- | --
> Überarbeitung | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
> Betriebssystem | Windows 10 OS Version 2004 (Build 19041.1110)
> 
> 
> 
> ## Version/Channel Information:
> 
> 
> - Can you reproduce this issue with the current release? No
> - Can you reproduce this issue with the beta channel? Not sure
> - Can you reproduce this issue with the nightly channel? Yes
> 
> ## Other Additional Information:
> 
> - Does the issue resolve itself when disabling Brave Shields? NA
> - Does the issue resolve itself when disabling Brave Rewards? NA
> - Is the issue reproducible on the latest version of Chrome? NA
> 
> ## Miscellaneous Information:
> 
> cc: @brave/legacy_qa @mkarolin @rebron

**Comment by srirambv** [comment]
+1 from @ygoe via #17489

**Comment by LaurenWags** [comment]
labelling as `QA/Blocked` until we have an RC where this can be tested

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.30.84 Chromium: 94.0.4606.54 (Official Build) (x86_64)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | macOS Version 10.15.7 (Build 19H1417)
```

Reproduced the issue with the following languages using 1.29.81:

German | French | Spanish | Portuguese
----- | ----- | ----- | -----
<img width="310" alt="German 1 29 81" src="https://user-images.githubusercontent.com/28145373/134516742-e99287fb-5473-455c-b8f1-8ae56e0a6d2a.png"> | <img width="279" alt="French 1 29 81" src="https://user-images.githubusercontent.com/28145373/134516847-f153d579-d251-41eb-a032-3979dfcaf724.png"> | <img width="277" alt="Spanish 1 29 81" src="https://user-images.githubusercontent.com/28145373/134516854-d0cbc07c-3440-46b3-9d79-3c18f7dc6e13.png"> | <img width="270" alt="Portuguese 1 29 81" src="https://user-images.githubusercontent.com/28145373/134516864-6d46348a-1c04-4653-a35c-ee85d3a9acae.png">


Confirmed the "Additional settings" text is not distorted in the following languages using 1.31.84:

German | French | Spanish | Portuguese
----- | ----- | ----- | -----
<img width="275" alt="GERMAN" src="https://user-images.githubusercontent.com/28145373/134517430-1387094d-d924-4959-a717-a5967fb03614.png"> | <img width="270" alt="FRENCH" src="https://user-images.githubusercontent.com/28145373/134517436-d668cc71-fc75-42d9-9f34-3884eee7d9a0.png"> | <img width="278" alt="SPANISH" src="https://user-images.githubusercontent.com/28145373/134517446-25bd7336-c0f6-4a92-b250-7eca989fa0ca.png"> | <img width="276" alt="PORTUGUESE" src="https://user-images.githubusercontent.com/28145373/134517455-adc174d9-8270-4640-8bd6-42380b566bfb.png">
