### ISSUE TITLE
Gemini balance should not be displayed if wallet claim fails

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#17474]
## Description 
If the claim endpoint returns an error, wallet balance should not be fetched from Gemini

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/9755

**Comment by GeetaSarvadnya** [comment]
https://github.com/brave/internal/issues/788#issuecomment-898265442

Points observed while testing Gemini linking limit:
1. Wallet balance is still shown even after getting linking limit reached notification on BR panel
2. Able to send one-time tips, but balance is not going down after sending tips and Tips aren't shown in tips panel, the rewards-internal page shows Step: Failed, Retry Count: -1 under contributions tab
3. Able to set monthly tips, monthly tips are shown in the Monthly Contributions panel in the rewards settings page
4. AC and monthly tips are not processed after reconcile interval

point 2 and 4 will be tested once issue #17474 is fixed

**Comment by LaurenWags** [comment]
from https://github.com/brave/brave-browser/issues/17474#issuecomment-898422437, 

1 is the issue from description and I think 2 & 4 are due to this, wdyt @jumde?

as for 3, I think this is fine because even with a 0 BAT balance you can set monthly tips, wdyt @Miyayes?
