### ISSUE TITLE
Reload all tabs

### ISSUE THREAD

**Issue by miladmaz12** [brave/brave-browser#1747]
## Description 
Self-explanatory

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:
No option for Reload all tabs

## Expected result:
Hover the mouse to any tab --> right click --> Reload all tabs

## Brave version (brave://version info)
0.55.18

### Reproducible on current release:
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by miladmaz12** [comment]
It would be convenient if there's a setting instead of using keyboard shortcuts.

**Comment by jhuckelba** [comment]
Ctrl-Shift-R would be awesome.  this feature is very underrated.  i have used this in the past (think firefox used to support it) when you have separate windows with tabs for things like jira issues, etc.  refreshing all in the morning to check state is a nice thing to have rather than going one by one.

**Comment by jonathansampson** [comment]
This request recently received a +1 from [a user on Twitter](https://twitter.com/erich13/status/1272333620133257217). This user also pointed out that the current suggested workaround of manually selecting all tabs, and then refreshing, is not ideal for those who have quite a few tabs.

Another approach would be to work-up a basic extension which calls `chrome.tabs.reload` on each tab (optionally working across various windows, and even ignoring cache).

**Comment by fallaciousreasoning** [comment]
@jonathansampson should we close this now?
