### ISSUE TITLE
How to use chromium source code i downloaded previously?

### ISSUE THREAD

**Issue by navaneethkm004** [brave/brave-browser#17470]
I already downloaded chromium source code using ``depot_tools``. Now how can I use that source code to build brave instead of downloading it again using ``npm init``.

**Comment by bsclifton** [comment]
Hi @navaneethkm004 

You might be able to use it. Let's say you cloned the Chromium code to:
`/home/clifton/source/chromium`

There should be a folder there `src`. You can either move or copy that folder (the entire folder) over the one created by cloning `brave-browser`

The history should be the same, so running init should only pull what's new (and in addition, grab the brave specific items and run the brave specific triggers). You'll want to un-PATH your depot_tools as we use ours (under `brave_core/vendor`).

**Comment by navaneethkm004** [comment]
> Hi @navaneethkm004
> 
> You might be able to use it. Let's say you cloned the Chromium code to:
> `/home/clifton/source/chromium`
> 
> There should be a folder there `src`. You can either move or copy that folder (the entire folder) over the one created by cloning `brave-browser`. If you cloned `brave-browser` to `/home/clifton/source/brave-browser`, it would look like:
> 
> ```shell
> mv /home/clifton/chromium/src /home/clifton/source/brave-browser
> ```
> 
> The history should be the same, so running init should only pull what's new (and in addition, grab the brave specific items and run the brave specific triggers). You'll want to un-PATH your depot_tools as we use ours (under `brave_core/vendor`).

Thank you sir for replying :).

**Comment by bsclifton** [comment]
@navaneethkm004 my pleasure! Let me know if the above works for you

**Comment by navaneethkm004** [comment]
sure will do

**Comment by navaneethkm004** [comment]
@bsclifton Yesss it worked. Thank you so much sir.
