### ISSUE TITLE
[Desktop] Brave News Display Ad gets served more than once

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#17471]
Occurs for first ad position - ad content will get requested twice. The first response will be discarded and the second response will be used. This results in premature ad capping from the ads service.

The only way to monitor the issue on the current build is to check the ads service local SQL database. The fix will contain more debug logging.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.29.67 Chromium: 92.0.4515.159 (Official Build) beta (x86_64)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:

1. new profile
2. launched Brave
3. opened the "hamburger" menu, and chose `More Tools -> Developer Tools`
4. from the `All levels` dropdown, added `Verbose`
5. opened a new-tab page
6. scrolled down
7. examined console


Confirmed I only saw one `asking for an ad 0` call logged in the Console

<img width="1312" alt="Screen Shot 2021-08-23 at 1 04 22 PM" src="https://user-images.githubusercontent.com/387249/130512659-8a8116a5-9041-425f-9608-9be27e2cb0c1.png">
