### ISSUE TITLE
Featurerequest: "Text to Speech" in Mac Version 

### ISSUE THREAD

**Issue by avolution** [brave/brave-browser#1748]
Would be nice when It is possible to integrate the Text to Speech Feature for the Mac Version.
Like on the other browsers(Chrome, Safari).

In Detail:
You select a text ... right click ... context menu Speech -> start speaking ... the OS integrated Speech Engine starts to speak the text.

**Comment by Liunkae** [comment]
![](https://user-images.githubusercontent.com/19424103/47257630-eb500a00-d455-11e8-8608-96b5e1970a45.png)
This feature already exists as of Brave 0.57.1.

**Comment by bsclifton** [comment]
Closing after confirming this does exist
