### ISSUE TITLE
Unable to rotate key due to uncaught DOMException

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17485]
## Description 

Unable to rotate key due to uncaught DOMException

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `ipns://en.wikipedia-on-ipfs.org`
   4. click on `Use a local node`
   5. load `brave://settings/ipfs/keys`
   6. click on the `rotate` icon (circular arrow)
   7. type `rotatedKey` and click `Rotate`

## Actual result:

The rotated key named `rotatedKey` doesn't appear in the `Keys` list

<img width="1312" alt="Screen Shot 2021-08-13 at 4 17 33 PM" src="https://user-images.githubusercontent.com/387249/129426596-5d0a1cef-caef-4d19-9375-c969c8d0c052.png">

```
keys:1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "cr-toolbar" has already been used with this registry
    at chrome://settings/settings.js:4510:866
```

Later (after refresh):

```
Unchecked runtime.lastError: Unable to load keys
```

## Expected result:
Should immediately see `rotatedKey` appear for us in the `Keys` list

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.30.22 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

@spylogsster @lidel this happens with both `0.9.0` and `0.9.1` versions of `go-ipfs` (which is expected, given this is likely our bug, but just mentioning) /cc @kjozwiak

**Comment by stephendonner** [comment]
Can also reproduce in:

Brave | 1.29.58 Chromium: 92.0.4515.131 (Official Build) beta (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)



Brave | 1.28.105 Chromium: 92.0.4515.131 (Official Build) (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.2 (Build 20G95)

But sometimes it also Just Works (tm) or takes a little time to work; it's really odd.

**Comment by spylogsster** [comment]
@stephendonner works well for me, pls recheck on latest nightly

**Comment by stephendonner** [comment]
> @stephendonner works well for me, pls recheck on latest nightly

@spylogsster I can still reproduce with a new profile on 


Brave | 1.31.7 Chromium: 93.0.4577.58 (Official Build) nightly (x86_64)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | macOS Version 12.0 (Build 21A5304g)


![rotateKey](https://user-images.githubusercontent.com/387249/131418270-354a37ab-473f-40a9-9458-ec94a5b4ccdb.gif)

**Comment by stephendonner** [comment]
Confirmed I was able to rotate keys using 

Brave | 1.37.32 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

example | example
---------|---------
<img width="1412" alt="Screen Shot 2022-02-07 at 10 06 14 PM" src="https://user-images.githubusercontent.com/387249/152928401-d6feccbc-bd0f-426a-ac5e-afa3da40ed7a.png"> | <img width="1412" alt="Screen Shot 2022-02-07 at 10 08 30 PM" src="https://user-images.githubusercontent.com/387249/152928408-2c1bd0ff-a1bd-422b-8e61-89a9f7e6b32e.png">

Closing as Works for Me.
