### ISSUE TITLE
Automatically select matching custodian deposit address for Tips 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17498]
## Description

Given https://github.com/brave-intl/creators-private-issues/issues/637, the browser should select from the correct deposit address in the list given by the PCDN that matches with the user's custodian, if exists, to tip to. Example:

_Suppose that:_ 

* User is Gemini-verified
* Creator is Gemini-verified AND Uphold-verified

_Then:_ 

* The user's browser should select the Gemini deposit address to send tips to. 

And as expected, we should also only show the gray notice ("This creator is not configured to receive tips from your wallet") if there are no available paths.

**Comment by bbondy** [comment]
Just wanted to see if I understand this correctly...

The client is setup with Gemini, the publisher is setup as both. 
The user picks that publisher to try to tip to. The client picks (wrongly) Uphold to try to tip to. But that is considered cross custodian transfer so they client gets an error. 
Neither the client nor the publisher can get around this error?

Am I understanding it correctly? If so wanted to double check on the P4 priority.  Does a client that setup as Gemini always pick Uphold and error out?

**Comment by Miyayes** [comment]
Ah, right now as of Sept 2021 @bbondy: 

1. Creators can only be linked to a single custodian (Gemini only, or Uphold only, for example), so this "selection problem" doesn't yet exist 
2. We are going to allow creators to link to multiple custodians soon, so this "selection problem" can become an issue once that's implemented on Creators side https://github.com/brave-intl/publishers/issues/3363
3. This issue was filed as part of the work needed on client-side/browser-side to handle point 2 (once https://github.com/brave-intl/publishers/issues/3363 is implemented)
