### ISSUE TITLE
Add GitLab search engine

### ISSUE THREAD

**Issue by Jacalz** [brave/brave-browser#1749]
## Description 
A lot of people have switched over to GitLab after microsoft bought GitHub so it would be great to have a search engine in Brave to search on GitLab. I my self will stay on GitHub for the time being but it is still a great thing to have when looking at repos. But please note that the feature must use the repo search on https://gitlab.com/explore/projects and not the search at the top of the page.

## Actual result:
No gitlab search engine

## Expected result:
Should be able to search gitlab with :gl in the search bar

## Brave version (brave://version info)
0.55.18 Chromium: 70.0.3538.67

### Additional Information
The only issue right now is that you won't be able to search self hosted instances of gitlab like gnome, xorg and others. Gitlab is a bit fragmented and that is basically why I stay with GitHub.

**Comment by srirambv** [comment]
Adding this as a custom search engine works just fine. 
`https://gitlab.com/search?utf8=%E2%9C%93&search=%s&group_id=&project_id=&repository_ref=`

>The only issue right now is that you won't be able to search self hosted instances of gitlab like gnome, xorg and others.

for self hosted instances you can just replace the above query with `https://gitlab.your_host_instance.com/search?utf8=%E2%9C%93&search=%s&group_id=&project_id=&repository_ref=`

Again this would only work as long as your self hosted instance setting is set to public

**Comment by Jacalz** [comment]
Thanks @srirambv 👍
But it would be pretty sweet having the first on in the the browser from the start though, like added to the default search engines list.
