### ISSUE TITLE
Disabling Brave Rewards on MacOS does not stop the "Brave Ads Service" or "Bat Ledger Service" from running

### ISSUE THREAD

**Issue by elsubigo** [brave/brave-browser#17491]
## Description 

Disabling Brave Rewards on MacOS Big Sur 11.4 does not stop the "Brave Ads Service" or "Bat Ledger Service" from running in the background. Launching the app with the --disable-brave-rewards-extension or --disable-brave-extension flags won't work either. I've tried this on a fresh install with rewards not enabled, as well as an old install with rewards turned on/off again.

Not only will the services not disable, they remain among the highest users of memory/CPU when at an idle.

## Steps to Reproduce

   1. Launch Brave on MacOS. Disable rewards in settings. Check built in task manager.
   2. Launch Brave with --disable-brave-rewards-extension / --disable-brave-extension flags from CLI. Check built in task manager.

## Actual result:

"Brave Ads Service" and "Bat Ledger Service" continue to run.

## Expected result:

"Brave Ads Service" and "Bat Ledger Service" should not have active services running.

## Reproduces how often: 

100% of the time.

## Brave version (info found on brave://version)

Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (x86_64)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No

**Comment by srirambv** [comment]
cc: @tmancey

**Comment by tmancey** [comment]
@srirambv this is correct if a user opts in to Brave News. Can you please confirm you were opted-in to Brave News

**Comment by tmancey** [comment]
@elsubigo did you opt-in to Brave News please? Thanks

**Comment by tmancey** [comment]
@elsubigo would you be willing to screen-share so I can investigate further, if so can you please reach out to tmancey@brave.com so I can send a link. Thanks

**Comment by tmancey** [comment]
If you are opted-in to Brave News then the ads service will be running. This is as expected.

**Comment by elsubigo** [comment]
Screenshots:

<img width="1440" alt="1" src="https://user-images.githubusercontent.com/73205387/129626497-46a38824-b0e2-48da-8aa4-fe117c1b2612.png">
<img width="1433" alt="2" src="https://user-images.githubusercontent.com/73205387/129626505-b6bad5a7-a60c-4ce4-8b79-0e46d12e972e.png">
<img width="1439" alt="3" src="https://user-images.githubusercontent.com/73205387/129626514-5187a2ba-6081-4cb5-90a0-f851afc5daac.png">

**Comment by bsclifton** [comment]
Re-opening: we might have a bug where disabling News isn't resetting the conditions needed to start the service

**Comment by bsclifton** [comment]
Visiting brave://rewards will always start the Ledger service, even if you reset your wallet. However, if you close all instances of brave://rewards and quit/re-open Brave Ledger service WILL NOT be running. See https://github.com/brave/brave-browser/issues/14277 for more info

I did confirm this issue (Ads service running) though; turning OFF News doesn't stop the Ads service from running. I would expect as a user that ads service should NOT be running when:
1. rewards has not been enabled (specifically ads)
AND
2. Brave News is disabled

**Comment by tmancey** [comment]
@bsclifton Thanks, I can confirm "I did confirm this issue (Ads service running) though; turning OFF News doesn't stop the Ads service from running. I would expect as a user that ads service should NOT be running" is a bug. Raising a PR now against this issue.

**Comment by stephendonner** [comment]
** Verified `PASSED` using 


Brave | 1.30.41 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 11.5.2 (Build 20G95)

### Steps:

#### Case 1: Ads Enabled & Brave News Ads Enabled > Ads service should be running
1. new profile
2. launch Brave
3. enabled Ads & Rewards via clicking on the BAT icon and clicking `Start using Rewards`
4. enabled Brave News via new-tab page, `Customize` -> `Brave News` -> `Show Brave News`
5. `Window` -> `Task Manager`

<img width="1509" alt="Screen Shot 2021-08-23 at 14 21 35" src="https://user-images.githubusercontent.com/387249/130522224-aba44f8c-fd08-4b2b-bfbf-7e435f166227.png">

**Confirmed `BAT Ad Service` was running in `Task Manager`**

### Case 2: Ads Enabled & Brave News Ads Disabled > Ads service should be running
1. new profile
2. launch Brave
3. enabled Ads & Rewards via clicking on the BAT icon and clicking `Start using Rewards`
4. ensured Brave News was disabled already via new-tab page, `Customize` -> `Brave News` -> `Show Brave News`
5. `Window` -> `Task Manager`

<img width="1510" alt="Screen Shot 2021-08-23 at 14 22 29" src="https://user-images.githubusercontent.com/387249/130521745-769bfbf7-9632-4f6d-baad-da71e9a8e15f.png">

**Confirmed `BAT Ad Service` was running in `Task Manager`**

#### Case 3: Ads Disabled & Brave News Ads Enabled > Ads service should be running
1. new profile
2. launch Brave
3. ensured Ads & Rewards were disabled by default via `brave://rewards`
4. enabled Brave News via new-tab page, `Customize` -> `Brave News` -> `Show Brave News`
5. `Window` -> `Task Manager`

<img width="1508" alt="Screen Shot 2021-08-23 at 14 23 25" src="https://user-images.githubusercontent.com/387249/130521699-c3c144a9-f087-499a-9767-1ed12ea99da7.png">

**Confirmed `BAT Ad Service` was running in `Task Manager`**

#### Case 4: Ads Disabled & Brave News Ads Disabled > Ads service should **not** be running
1. new profile
2. launch Brave
3. ensured Ads & Rewards were disabled by default via `brave://rewards`
4. ensured Brave News was disabled already via new-tab page, `Customize` -> `Brave News` -> `Show Brave News`
5. `Window` -> `Task Manager`

<img width="1514" alt="Screen Shot 2021-08-23 at 14 24 11" src="https://user-images.githubusercontent.com/387249/130521634-51ead7b8-304f-4c2f-881b-bdc86296d8cf.png">

**Confirmed `BAT Ad Service` was **NOT** running in `Task Manager`**

**Comment by LaurenWags** [comment]
cc @tmancey - should this be checked on Windows and Linux also?

**Comment by tmancey** [comment]
@LaurenWags I would recommend checking on Windows and Linux
