### ISSUE TITLE
Retry logic for Gemini should support multiple transactions

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#17505]
## Description 
If two transactions for Gemini are initiated in parallel, status for one of the transaction will not be updated correctly if the first transaction is waiting for the `Completed` transaction status. 

## Steps to Reproduce

   1. Initiate a tip to a Gemini creator
   2. Initiate a second tip to the Gemini creator
   3. Navigate to brave://rewards-internals, and verify that the first tip did not complete successfully.

## Actual result:
First tip does not complete successfully.

## Expected result:
First tip should complete successfully

## Reproduces how often: 
Easily

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/9771

**Comment by LaurenWags** [comment]
Verification in progress with

```

```

Verified test plan from https://github.com/brave/brave-core/pull/9771#issue-714413744 and scenarios from https://github.com/brave/brave-core/pull/9771#issuecomment-902902409.

<details>
<summary>Scenario 1 - 2 one time tips - In Progress</summary>

Did a one time tip and while I was waiting the 3 min for the browser to fetch txn status, I did another one time tip.

Tip 1 is 1 BAT:

Example | Example
----- | -----


<details>
<summary>Logs</summary>

Retries not shown, only log entry from the completed txn status is below:

</details>

Tip 2 is for 3 BAT:

Example | Example
----- | -----


<details>
<summary>Logs</summary>

Retries not shown, only log entry from the completed txn status is below:

</details>

Confirmed that both One Time Tips completed:

Example | Example | Example
----- | ----- | -----

</details>

<details>
<summary>Scenario 2 - AC and One Time Tip - TBD</summary>

Set up AC to complete with a `reconcile-interval=8` and `retry-interval=60`. After AC was triggered but before the browser had completed waiting 3 min to check for txn status, I did a one time tip.

AC:

Example | Example
----- | -----


<details>
<summary>Logs</summary>

Retries not shown, only log entry from the completed txn status is below:

</details>

One Time Tip:

Example | Example
----- | -----


<details>
<summary>Logs</summary>

Retries not shown, only log entry from the completed txn status is below:

</details>

Confirmed both AC and One Time Tip complete:

Example | Example | Example | Example | Example | Example
----- | ----- | ----- | ----- | ----- | -----

</details>

<details>
<summary>Scenario 3 - AC and Monthly Tips - TBD</summary>

Set up AC and monthly recurring tips (2) with `reconcile-interval=8` and `retry-interval=60`. 

AC:

Example | Example
----- | -----

<details>
<summary>Logs</summary>

Retries not shown, only log entry from the completed txn status is below:

</details>

Monthly Tips:

Example | Example
----- | -----


<details>
<summary>Logs</summary>

Retries not shown, only log entry from the completed txn status is below:

</details>

Confirmed both AC and Monthly Tips completed:

Example | Example | Example | Example | Example | Example
----- | ----- | ----- | ----- | ----- | -----


</details>
