### ISSUE TITLE
Remove Brave Rewards build flags

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#17504]

**Comment by bsclifton** [comment]
@tmancey are there still more in place?

I removed what I thought was all of them with https://github.com/brave/brave-core/pull/9607

**Comment by tmancey** [comment]
@bsclifton apologies yes they have all been removed, could you please review https://github.com/brave/brave-core/pull/9769 which removes build flags for ads. Thanks

**Comment by tmancey** [comment]
Closing issue as already resolved
