### ISSUE TITLE
Decouple `AdsService` from `RewardsServiceImpl`

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#17500]
Notify `AdsServiceImpl` of the following `ledger::type::PromotionType::ADS` promotion via the `OnPromotionFinished` observer:
```
  if (promotion->type == ledger::type::PromotionType::ADS) {
    auto* ads_service = brave_ads::AdsServiceFactory::GetForProfile(profile_);
    if (ads_service) {
      ads_service->ReconcileAdRewards();
    }
  }
```

Change `ads_service->ResetAllState` to notify `AdsServiceImpl` via the Observer Pattern that we should reset all data

**Comment by Miyayes** [comment]
@tmancey Is this still relevant?
