### ISSUE TITLE
Move BraveWalletProviderImpl into browser/brave_wallet

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#17506]
@bridiver suggests that we should move `BraveWalletProviderImpl` from components to browser/brave_wallet because there's no reason to have that in components, and it will simplify our codes. 
We can access rpc_controller directly in the renderer code instead of going through BraveWalletProviderImpl, and only keep permissions related code inside the class which won't be shared with iOS anyway.

**Comment by bbondy** [comment]
I think we want this in components now for iOS and given recent refactoring from @SergeyZhukovsky . Closing.
