### ISSUE TITLE
Prevent blacklisted tokens to be listed in Swap

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#17523]
Uniswap, which fills most of the orders on Brave Swap, maintains a list of [blacklisted tokens](https://raw.githubusercontent.com/Uniswap/uniswap-interface/main/src/constants/tokenLists/unsupported.tokenlist.json) - usually known scams or tokens identified as securities. We would like to respect this list to avoid legal complications.

**TODO:** Update the asset registry script to filter out blacklisted tokens, and update the `@metamask/contract-metadata` package to pull in the latest modifications on the Metamask side.

**Comment by srirambv** [comment]
@onyb Is this a QA/Yes or QA/No?

**Comment by onyb** [comment]
@srirambv Let's do a light QA - here's the test plan:

1. As a user, I should be able to find `AAAVE` token in the Swap asset list.
2. As a user, I should not be able to find `MATTER` token in the Swap asset list.

Additionally, let's do a simple send transaction for any ERC-20 token on the mainnet, since we have updated the `@metamask/contract-metadata` project.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (x86_64)
-- | --
Revision | `c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}`
OS | macOS Version 11.5.2 (Build 20G95)
Component | `1.0.37 dev`

- Verified test plan from https://github.com/brave/brave-browser/issues/17523#issuecomment-900247069
- Verified `AAAVE` token is listed in swap asset list
- Verified `MATTER` token is note listed in swap asset list

![image](https://user-images.githubusercontent.com/17010094/132174922-ab882482-b59f-4603-80d8-845752388edb.png) | ![image](https://user-images.githubusercontent.com/17010094/132172796-0cee7c0c-9c6d-4929-ad29-07e790da8e86.png)
-- | --

---------
Verification passed on 

Brave | 1.30.57 Chromium: 93.0.4577.58 (Official Build) beta (64-bit)
-- | --
Revision | `c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}`
OS | Linux
Component | `1.0.37. dev`

- Verified test plan from https://github.com/brave/brave-browser/issues/17523#issuecomment-900247069
- Verified `AAAVE` token is listed in swap asset list
- Verified `MATTER` token is note listed in swap asset list

![image](https://user-images.githubusercontent.com/17010094/132175778-4ca6ec7d-0fcc-4ed9-9f3b-1989c0474e46.png) | ![image](https://user-images.githubusercontent.com/17010094/132175873-a6d0dd82-4cd0-44db-8508-dbb507c4e486.png)
-- | --
---------
Verification passed on 

Brave | 1.31.22 Chromium: 93.0.4577.63 (Official Build) nightly (64-bit)
-- | --
Revision | `ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}`
OS | Windows 10 OS Version 2009 (Build 19043.1165)
Component | `1.0.37. dev`

- Verified test plan from https://github.com/brave/brave-browser/issues/17523#issuecomment-900247069
- Verified `AAAVE` token is listed in swap asset list
- Verified `MATTER` token is note listed in swap asset list

![image](https://user-images.githubusercontent.com/17010094/132175506-68fcc4b1-b8fb-4447-8949-a6695af4ce70.png) | ![image](https://user-images.githubusercontent.com/17010094/132175554-6354b815-4001-4603-92a4-a906f80c5bfc.png)
-- | --

* Verified able to perform [transaction](https://etherscan.io/tx/0x6f37ce73529e02945d439f2226edcb84b811f2151d7b5c11b273607e40615d41) on mainnet
