### ISSUE TITLE
Snap custom Brave ad notifications to the edge of the screen

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#17527]
- Snap custom Brave ad notifications to the edge of the screen when
    - dragging
    - to the closest monitor when removing a display
    - changing resolution

**Comment by stephendonner** [comment]
Verified `IN-PROGRESS` using 

Brave | 1.32.84 Chromium: 95.0.4638.54 (Official Build) beta (x86_64)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | macOS Version 11.6.1 (Build 20G224)

Case 1: dragging custom-ad notification

Steps:
1. new profile
2. launched Brave
3. via `brave://flags`, enabled custom ads
4. restarted
5. enabled Rewards
6. waited for an ad
7. once custom-ad notification appeared, started dragging it to various screen positions

example | example | example | example | example
---------|----------|---------|---------|----------
<img width="1312" alt="Screen Shot 2021-11-01 at 1 08 52 PM" src="https://user-images.githubusercontent.com/387249/139736565-96c47a43-c160-42d4-af09-d51ca47cd2d1.png"> | <img width="1680" alt="Screen Shot 2021-11-01 at 1 10 45 PM" src="https://user-images.githubusercontent.com/387249/139736628-ed0bd9f5-e840-4e7b-904e-0d4d49ea2895.png"> | <img width="1680" alt="Screen Shot 2021-11-01 at 1 10 53 PM" src="https://user-images.githubusercontent.com/387249/139736647-c4310406-45cd-4155-818b-9591b7437696.png"> | <img width="1680" alt="Screen Shot 2021-11-01 at 1 11 00 PM" src="https://user-images.githubusercontent.com/387249/139736654-12df2864-a725-4491-9448-77d64851272c.png"> | <img width="1666" alt="Screen Shot 2021-11-01 at 1 11 12 PM" src="https://user-images.githubusercontent.com/387249/139736660-e3588593-ef55-4d7e-a218-b6e90411f6c1.png">



Case 2: changing screen resolution

Case 3: removing monitor
