### ISSUE TITLE
No clear statement about 32-bit/i386 compatibility; is it compatible?

### ISSUE THREAD

**Issue by InternetUser1** [brave/brave-browser#1752]
## Description 
Trying to install in Lubuntu 18.04 on a 32-bit laptop I encounter [the error, "Unable to locate package brave-browser"](https://askubuntu.com/questions/1085319/unable-to-locate-package-brave-browser-on-ubuntu-18-04-1-lts-lubuntu). Someone suggests Brave is 64-bit only, but I cannot find that statement anywhere on the Brave website, community, or documentation on github. [The question has been asked on Reddit](https://www.reddit.com/r/brave_browser/comments/9ppuib/is_there_no_32bit_linux_version/) but so far there has been no reply.

Is there no 32-bit linux version? Is that the explanation for the "Unable to locate package" error? Would you please add this to the website, or at least the github wiki or readme file?

## Steps to Reproduce

   1. Get Lubuntu 18.04.1 LTS on a 32-bit laptop.
   2. Try to install the linux version according to the instructions on the website.
   3. Try to find a statement about 32-bit incompatibility from the Brave website and github.

## Actual result:
confusion and lack of clarity

## Expected result:
successful installation of the Brave browser in Lubuntu 18.04.1 LTS

### Additional Information
Upgraded from Lubuntu 16 prior to attempted installation in 18, although installation was also attempted in v. 16 (though forgotten when trying to install in v. 18).

**Comment by AtjonTV** [comment]
There are 32-bit builds, but only for Windows (https://github.com/brave/brave-browser/releases/download/v0.56.5/brave-v0.56.5-win32-ia32.zip).

So Brave seems to somehow support 32-bit but they only build that version for Windows.

And as it is possible to build 32b versions, why only windows? :thinking:

**Comment by bsclifton** [comment]
As far as I know, we have no plans on supporting 32-bit Linux
cc: @bbondy and @davidtemkin for confirmation

**Comment by InternetUser1** [comment]
In that case, please clearly state this fact on [your downloads page](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux).

**Comment by weirdal3333** [comment]
A shame, this would make the internet usable on older computers.

**Comment by bbondy** [comment]
I'd like to support it.

**Comment by bsclifton** [comment]
https://brave.com/linux/ has 64-bit only support called out 👍
