### ISSUE TITLE
Allow the restore input to except multiple mnemonic lengths

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#17532]
Currently the `Restore Input` on the `Restore Wallet` page only allows a user to restore a wallet with a 12 character seed phrase.

We need to allow for 12, 15, 18, 21, 24 mnemonic lengths.

**Comment by diracdeltas** [comment]
Note that the 24 word case will be tricky to handle since we won't be able to tell if it's a metamask-style phrase or a legacy brave wallet (which uses an incompatible key derivation algorithm). probably best to ask the user which one it is. https://github.com/brave/brave-browser/issues/9837
