### ISSUE TITLE
Brave Extension increases page load times by ×10

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#17538]
## Steps to Reproduce
   1.  Visit a very simple HTML page like https://example.com
   2. Open Developer Tools: Performance
   3. Click record page load time.
   4. Focus in on the page load portion and inspect what’s slowing down the page load.

(Compare to Edge or Chrome with no extensions.)

## Actual result:
 `content_cosmetic.bundle.js` (a script inserted by the [bundled Brave Extension](https://github.com/brave/brave-core/blob/2caab34dca9d74c3437828c542f87d0bd13248b0/components/brave_extension/extension/brave_extension/manifest.json)) increases the page load time by ×10.

Even for simple pages, page loads go from 30–50 ms to 500–700 ms. (Times excluding networking overhead.)

For more complex pages served from a local file (no network overhead), the Lighthouse performance score drops from 98 to low 60s.

## Expected result:
No compromises on performance. (Or, at least only tiny ones.)

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
1.28.105 Chromium: 92.0.4515.13

## Version/Channel Information:
stable

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 

no.

- Does the issue resolve itself when disabling Brave Rewards? 

no.

- Is the issue reproducible on the latest version of Chrome? 

no, it’s Brave specific.

**Comment by bsclifton** [comment]
cc: @antonok-edm

**Comment by Tonev** [comment]
@bsclifton @antonok-edm 

Related to https://github.com/brave/brave-browser/issues/17906?

**Comment by antonok-edm** [comment]
@Tonev possibly. It would also be good to check if it's affected at all by https://github.com/brave/brave-core/pull/9995

**Comment by atuchin-m** [comment]
To resolve this the following issues should be done:
#17918
#17906
#17935

**Comment by iefremov** [comment]
@da2x we significantly optimized Brave Extension in Nightly, would be great if you could test that.

**Comment by iefremov** [comment]
Pls reopen if this happens again
