### ISSUE TITLE
Home page not loaded from browser cache

### ISSUE THREAD

**Issue by ygoe** [brave/brave-browser#17534]
## Description 
I've set up a quick start link page as my browser home page. It's displayed when I press the "home" button in the toolbar and gives me links I often use. I want that page to load fast so I set it up to cache for a month by returning the appropriate HTTP response headers. This works nicely in Firefox. Brave, however, always loads that page from the server, ignoring all cache. All other resources are taken from the cache though, just not the main document.

## Steps to Reproduce
   1. Set up a custom URL as home page
   2. Open a new empty tab and press the "home" button, or just click the button with the middle mouse button.

## Actual result:
Page loads from server.

## Expected result:
Page should load from cache.

## Reproduces how often: 
Always

## Brave version (brave://version info)
<html>
<body>

Brave | 1.28.105 Chromium: 92.0.4515.131 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
Betriebssystem | Windows 10 OS Version 2009 (Build 19042.1052)

</body>
</html>

## Miscellaneous Information:
These are the response headers from the page loaded:

```
HTTP/1.1 200 OK
Date: Tue, 17 Aug 2021 19:25:52 GMT
Server: Apache
Expires: Fri, 17 Sep 2021 21:25:52 +0200
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
```

**Comment by stephendonner** [comment]
Hi @ygoe; if I'm reading https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires correctly, since there are no `Cache-Control` headers here, `Expires` takes precedent.  Is that your understanding, as well?

Can you share the relevant pieces of your `.htaccess` file?  To me, it looks like when you filed this bug, the `Expires` value was for the same day, so it'd be great to confirm how you're setting the caching directives.

Thanks!

**Comment by stephendonner** [comment]
Also: mind testing in Chrome, too, as we share the same underlying Chromium code (with modifications for security and privacy)?

**Comment by ygoe** [comment]
Thank you for the hint about cache headers. I've read [the docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) again and added a cache-control header that explicitly allows private caching for a month. Now the page is loaded from the browser cache (verified with an embedded server-generated timestamp and the dev tools).

Here's the corresponding PHP code:

```php
header('Cache-Control: private, max-age=' . $seconds);
header('Expires: ' . date('r', time() + $seconds));
```
