### ISSUE TITLE
Add missed actions to share to Brave

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#17531]
We miss some actions in the manifest to propose to share to Brave when share from other third-party apps. For example that one with reddit
https://www.reddit.com/r/brave_browser/comments/p5clbb/dear_developers_please_add_brave_on_the_android/
Another example is Share from YT. Brave is also not in the list.

**Comment by anthonypkeane** [comment]
Slack Link: https://bravesoftware.slack.com/archives/C0816QH3R/p1629119831031900
