### ISSUE TITLE
Should always show `Ads enabled: false` when ads are disabled, in `Ad diagnostics` tab of brave://rewards-internals

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17535]
## Description 

Should always show `Ads enabled: false` when ads are disabled, in `Ad diagnostics` tab of brave://rewards-internals

## Steps to Reproduce

Steps:
1. new profile
2. launched Brave
3. loaded `brave://rewards-internals` and clicked on the `Ad diagnostics` tab
4. looked at the help message

## Actual result:

`Ads not initialized, please refresh the page.`

<img width="1108" alt="Screen Shot 2021-08-17 at 2 19 04 PM" src="https://user-images.githubusercontent.com/387249/129802075-4a3eb7ce-a8ca-4066-8a94-e0cc75b988dd.png">

## Expected result:

`Ads enabled: false`

(Sometimes this works - I haven't nailed down when it does, concretely, yet.)

<img width="927" alt="Screen Shot 2021-08-17 at 2 13 07 PM" src="https://user-images.githubusercontent.com/387249/129802834-7b919e86-7751-4ca7-84e2-70fc5311b054.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.30.27 Chromium: 92.0.4515.159 (Official Build) nightly (x86_64)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | macOS Version 11.5.2 (Build 20G95)

**Comment by tmancey** [comment]
Closing as won't fix
