### ISSUE TITLE
Users may accidentally dislike ad when trying to close ads history

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#17543]
## Description
When a user is scrolling through their ad history and decide to close the modal window, they may accidentally dislike the ad instead of the 'x' to close the window.

This will become problematic when dislikes are enforced by https://github.com/brave/brave-browser/issues/17319

<img width="1046" alt="Screenshot 2021-08-18 at 09 09 09" src="https://user-images.githubusercontent.com/24831890/129953242-568e7ceb-c66c-4558-8daa-7546990d894f.png">

## Steps to Reproduce

   1. Open brave://rewards
   2. Click '30-day Ad History'
   3. Scroll down Ad History
   4. Align 'x' button over dislike button.
   5. Click on 'x' and see it toggle the dislike feature.

Possibly add margin around the 'x' button or ensure it's z-index is hightest.

## Version/Channel Information:
I saw this on my work machine's Release Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (arm64)
Could not replicate on personal machine. I think it possibly has to do with the "Ad" or "Category" column (https://github.com/brave/brave-browser/issues/9799)
<img width="1021" alt="Screen Shot 2021-08-18 at 14 32 48" src="https://user-images.githubusercontent.com/24831890/129953139-6cb33e3f-cf83-414c-b246-3b3a904ef8f2.png">

**Comment by tmancey** [comment]
Closing issue as stale, however making @Miyayes aware for future consideration in new ongoing design changes
