### ISSUE TITLE
Implement setting to disable the chrome sharing hub

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#17548]
## Description 
A user left some great feedback [here](https://www.reddit.com/r/brave_browser/comments/p1ekvj/brave_is_paying_for_googles_terrible_design/?utm_medium=android_app&utm_source=share) pertaining to sharing hub.

He wants a way to disable the "chrome sharing hub" and replace it with Android's default sharing window. 

Please implement a setting to disable "chrome sharing hub"

In Appearance, under Enable Tab Groups add

Enable Android sharing window 
Defaulted to Off

cc @karenkliu and @jamesmudgett for views.

**Comment by samartnik** [comment]
As per slack discussion, option will be named `Disable Sharing Hub`

**Comment by bsclifton** [comment]
Bumped up to P2 since we would uplift this when a fix is available (work in progress by @samartnik 😄)
