### ISSUE TITLE
Decouple Brave Ads serving pipeline

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#17542]
Abstract ad serving into classes, instead of having conditional `MaybeServeAdV1`/`MaybeServeAdV2`/etc. logic

**Comment by rebron** [comment]
Updated milestone to 1.32.x.

**Comment by btlechowski** [comment]
@rebron There was confusion around this issue as we needed only logging to be uplifted. It was handled in https://github.com/brave/brave-browser/issues/18726

This issue belongs to 1.33.x.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.33.83 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/10580
Verification done in https://github.com/brave/internal/issues/833
