### ISSUE TITLE
Build out Welcome Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#17547]
## Description 
Build out the Welcome Modal and display it after wallet creation.

![Screen Shot 2021-08-18 at 2 56 01 PM](https://user-images.githubusercontent.com/40611140/129971319-9d72054d-6dd1-45d1-8035-bb03e69c10a0.png)

You can find the specs for this component in Figma / Desktop Crypto Wallets.

Add the component too storybook with mock data for testing.

## Expected result:

Component should be visible and functional in Storybook under the Wallet/Desktop/Concepts and Wallet/Desktop/Components tabs.

**Comment by bbondy** [comment]
Closing this out as invalid since I don't think it is the right UX.
