### ISSUE TITLE
[cr93 followup]: Hide "Set up new Brave profile" page when adding a new profile in profile picker.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#17552]
STR:
1. In Brave window, click on ☰ -> Create a new profile
2. Observe popup window showing Set up page:
![image](https://user-images.githubusercontent.com/41635752/130001629-d2c780fd-1a3e-42ef-a51f-0ca56ef5d589.png)

Expected result:
Popup goes directly to the next page (same as clicking "Continue without an account" button):
![image](https://user-images.githubusercontent.com/41635752/130001696-8060e160-2cee-4f33-bee6-61d82e05db44.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.29.67 Chromium: 92.0.4515.159 (Official Build) beta (x86_64)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:
1. new profile
2. launch Brave
3. click on `☰` -> `Create a New Profile`
4. confirm page shown is same as 2nd screenshot, above, and goes right to `Customize your Brave profile`

<img width="1136" alt="Screen Shot 2021-08-23 at 14 07 04" src="https://user-images.githubusercontent.com/387249/130519685-600f91b1-9217-4359-9b53-db45315a7fc9.png">
