### ISSUE TITLE
Add entry in settings webui for configuring Brave as a default app for microsoft-edge protocol

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#17558]
This is next step for https://github.com/brave/brave-browser/issues/13875
- User could see the status of whether Brave is the default app or not for `microsoft-edge` protocol from this new settings entry.
- If not, we can have a button to launch into the proper control panel from settings (like we do for default browser setting) where user can adjust it themselves.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.32.112 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 20H2 (Build 19042.1348)

Verified test plan from https://github.com/brave/brave-core/pull/10879

Test case 1:
![default3_1](https://user-images.githubusercontent.com/34715963/143281525-fc40a597-16a3-498b-8596-60961de9f5ab.png)|![default3_2](https://user-images.githubusercontent.com/34715963/143281527-361a3bcd-aec0-4815-81c7-e2c1b2467ba7.png)|![default3_3](https://user-images.githubusercontent.com/34715963/143281528-0e3c7e23-a563-46b3-8743-c58d208ca0aa.png)|![default3_4](https://user-images.githubusercontent.com/34715963/143281531-f762a59e-2085-483f-bf45-528b9166b043.png)|![default3_5](https://user-images.githubusercontent.com/34715963/143281533-886fa795-0a1f-4d33-8517-2190cd2ecd81.png)|![default3_6](https://user-images.githubusercontent.com/34715963/143281540-2f5130c2-cac0-4cec-9a0f-9482f616b4aa.png)
--|--|--|--|--|--


Test case 2:
![default4_1](https://user-images.githubusercontent.com/34715963/143281601-46b3b4cd-0683-44e3-b0e7-c01893eaab34.png)|![default4_2](https://user-images.githubusercontent.com/34715963/143281606-419a93b5-dec0-48aa-a6ac-be93c3f92460.png)|![default4_3](https://user-images.githubusercontent.com/34715963/143281608-50361361-5eba-41ba-8321-6ce45681e269.png)|![default4_4](https://user-images.githubusercontent.com/34715963/143281611-35db102c-325c-409e-a870-bf4d29cc5d08.png)
--|--|--|--
