### ISSUE TITLE
Chromebook Support

### ISSUE THREAD

**Issue by Hifiz** [brave/brave-browser#1755]
## Description 

No Chromebook support

## Steps to Reproduce

   1. add support for Chromebook
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tomlowenthal** [comment]
Chromebooks with Crostini should support the Linux build of desktop Brave just like any other Linux app. And Chromebooks with Android app support should be able to use the Brave Android app (though the tablet mode could be better). I'm not sure what other Chromebook support could reasonably be expected.
