### ISSUE TITLE
Make Android send crash reports to backtrace.io

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#17563]
## Description 

Right now we getting crashes through the Google Play developer console. There are two main disadvantages:
1. Hard to symbolize stack of crashed thread, impossible to make that do Google Play console, because for the current aab/apk we get function offset from the apk and not from the so-module; 
2. When crash happens in Java code, sometime we can see only the native part of the stack, and impossible to say what exactly happened.

The solution is to use Chromium crash reporting, which now is disabled and, if user agrees, send crash dumps to our backtrace.io instance, like we do on the desktop.

Advantages:
1. Crashed function offset is relative to the library and when backtrace.io has symbols for the build - stack is symbolized instantly;
2. Chromium crashpad saves the information about the Java exception and stored it into `exception_info` , it is visible in backtrace.io.

In anyway reporting to Google Play console still will work.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.31.67 x64 Beta Build
- Verified test plan from https://github.com/brave/brave-core/pull/9665
- Verified able to see symbolized stack trace in backtrace

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/136010011-66484b1f-a0c1-4905-861d-81c54b6f1cb7.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/136010045-be67d9f2-2bfa-4a59-8f0e-a4344a7bb288.png>
