### ISSUE TITLE
WebGL leaks in private windows

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#1756]
https://browserleaks.com/webgl

specifically the vendor and renderer debug fields (other fields should be dealt with through farbling)

**Comment by pes10k** [comment]
Now that farbling is in place, narrowing this issue to only be about vendor and renderer debug fields

**Comment by pes10k** [comment]
closing in favor of https://github.com/brave/brave-browser/issues/9189 and https://github.com/brave/brave-browser/issues/9188
