### ISSUE TITLE
Offer to translate pages does not work 

### ISSUE THREAD

**Issue by balintmaci** [brave/brave-browser#17565]
## Description 

Offer to translate pages does not work. I have the language settings set up to offer translations to English, yet the browsers has never offered to translate any pages.
![image](https://user-images.githubusercontent.com/13272850/130066575-af9d3cab-0070-4e55-a56a-fd8873088dbd.png)
I have to use danish websites regularly, and have never seen the built in translation work. Google translator toolbar works ok but is a pain to click on every page navigation.

## Brave version (brave://version info)

Brave	1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
Revision	6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS	Windows 10 OS Version 2009 (Build 22000.132)

but it has been the same on any version I've ever used and I've been a user for a few months at this point

**Comment by rebron** [comment]
Closing as not actionable. 

Hi @balintmaci Our current solution right now is with Google Translate extension https://github.com/brave/brave-browser/issues/5561 I know it's the ideal solution for you. We are working on a built in solution but we won't be addressing it with this issue.
