### ISSUE TITLE
Start using Rewards button in Brave Rewards NTP widget isn't clickable

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17572]
## Description 

`Start using Rewards` button in Brave Rewards NTP widget isn't clickable

## Steps to Reproduce

   1.  new profile
   2. launch Brave
   3. load a new-tab page
   4. try to click on the `Start using Rewards` button on the widget

## Actual result:

The `Start using Rewards` button isn't clickable, most times.

## Expected result:

The `Start using Rewards` button should be clickable and enable Rewards.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.30.33 Chromium: 93.0.4577.42 (Official Build) nightly (x86_64)
-- | --
Revision | f794baa90de7ca837ab1f8dc0c482a20140ba26a-refs/branch-heads/4577@{#744}
OS | macOS Version 11.5.2 (Build 20G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

/cc @zenparsing @petemill @emerick

**Comment by stephendonner** [comment]
Meant to mention: this works using `1.30.31`.

**Comment by zenparsing** [comment]
It appears that the main Rewards widget content and the notification container are assigned to the same CSS grid, with the notification container occurring later in the layout. It may be that CSS grid behavior has changed slightly such that a later element overrides a prior element when the grid layout is computed.

**Comment by stephendonner** [comment]
Also verified on

Brave | 1.29.74 Chromium: 93.0.4577.58 (Official Build) (64-bit)
--|--
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | Linux

example | example
---------|---------
<img width="1686" alt="Screen Shot 2021-08-27 at 3 59 46 PM" src="https://user-images.githubusercontent.com/387249/131196477-7998afda-6ef2-4501-add2-8e16bd236593.png"> | <img width="1686" alt="Screen Shot 2021-08-27 at 3 59 58 PM" src="https://user-images.githubusercontent.com/387249/131196486-f0e50ea1-e4fb-490e-9679-49180a927c1e.png">
