### ISSUE TITLE
Remove encryption for Brave Rewards vBAT wallet

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#17571]

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` per https://bravesoftware.slack.com/archives/C0YL5KMA8/p1632233994068700?thread_ts=1631744779.040800&cid=C0YL5KMA8

**Comment by stephendonner** [comment]
@tmancey I’ve put up a skeleton of a test plan here for review/feedback, please, when you get a moment?

Questions:
1) I think I’ll need to add Ads to some cases, to confirm multiple wallets?
https://gist.github.com/stephendonner/4b1cb47c4956a5d7b6fbf5b584d0f563
2) can you help define the following, in terms of what to look for in `brave.wallets.brave` in `Preferences`?

`unencrypted ==`
`decrypted ==`
`not decrypted ==`

Thanks!

**Comment by zenparsing** [comment]
@stephendonner An unencrypted `brave.rewards.wallets.brave` entry in `Preferences` will look something like this:

```
"brave": "{\"payment_id\":\"374263e0-05d7-469c-ba23-b10af952a1b0\",\"recovery_seed\":\"i8BwvQzl8OHs9ecyNx2ixtJNg/o7rrMvtABi3VOCo+o=\"}"
```

An encrypted value for `brave.rewards.wallet.brave` will be base64-encoded binary data, perhaps something like:

```
"brave": "djEwAn6VRxTsKS05AM6/WLm2UGqEYIaEWuIml/VZVNusE3+YYhRLjwXSngeVS0vSXGs9aOmuoCIYN6Imtp0JqygDn+yS0/dFt5EySt2MUIHandfvTK+HZRKFnpO1lsoLu3v31a1gtOCFemhs4r5D48/+19fpSeECArKFOHywmYmboIUlUJW1OxvChBiUR9ml6kE1Z8KgW7sbWWzfbocWzIMC7upMgLU9TPZdEBuJrxr5M42SjDdUAxywAi1KregTtaIbd+xOgKTTAT+ch3kAlJzbzslukxKI3nDaqVdlO7rfJIAd68ezGmTbmOG+HDQC1NykNbePgAYyyeSLr7Bf6qtwa5bKnf0rkcJrVB3+G22/mKGGf6ZktAgu1AA7Utxjv/oEYDPVuSc6bgSZ1FbvcOLeW8IKOvLgolsePyOkue+VsFyz/hegrHJvJpyjHU2NKYKO5NIGzq+N2KwrsauDwlNHg+juNymdv2QDhizE6gAABrzl70dJ9FvsCUkffPVo6AqvNPmlnkCjDibODAnZeiam44jSiXeAQ1mQ3JiJ3+nxQb2VSz8fFOlJRK8PJOyNXFBF9fzFvhA1nGjB0mdJt2SlRT9Sx7hx4jj+BnPH5vCejej+8ryvjIGt6NiltCeszdN5GE+wxltqNRapGObD01E31ENAT1EYizTn/HOOJcPZXC8iFmlwFfNodbQrccmUo4Wmsb94p/wCFAauN9I5+V+iPlX7OsYw6KmmVqhw2fIZ1OkQ67suYje/my1+fo5wFnAGsJlReFirhHJgNTjp+FcyW6Wbf4FOv2cftz7ke06tmYP+1+cytW7QFeBX1De2JCcrwfH59eEnys4RkMWz+asRX9+ZfHsCWt0G64bbn0EYMF0+cZGZcl4jKbmMxxT4rQNz7dzK/7k9sL/spU3nvECyWPpTExF79CnzZvcUIB95XMjNBaK5a/l+WyNYD4O3MDo/cUZkei7UBbKYxUCZA09bLbsDPXV/NyslPiK7DBtDAfIN0PLpCrhpKyLnSk6V7U16/dFo3VR+ItuLk3iWX9Tpp+ttyXm4vyeJBfKzSp/LRT7kTJlL0BwKTetPalmG4l1dRR4YIzdjMnjXTosZT7K5k0hwjVxVMI+dq1oqRtxk0rDtwJE4xIMVkLe4NtZrMPuzFOci1saUAwO9PvHSAT6O3R5IQNrpNEejeli3s8jeoLmiivnHG/zxLVNGu2XzV7YZL2Y1SNcRqGmN+p+UsDiiOVWZ6jHFmaTYAWekBfI1fj5GPNvymRtLYJ8iejhRSFB6V4a5S0XO8WO5yJRrdGVkv6vJBnw75Id+5dze2AQmJLix/jcr+201CdmF02vvaLyG"
```

Your test cases look good to me. We may also want to ensure that for the upgrade cases, wallet actions do not result in any errors. Wallet actions might include fetching promotions (grants), tipping, etc.

**Comment by tmancey** [comment]
Looks good to me and thanks @zenparsing, much appreciated

**Comment by stephendonner** [comment]
### Verified `PASSED` using 


Brave | 1.31.68 Chromium: 94.0.4606.61 (Official Build) dev (x86_64)
-- | --
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | macOS Version 11.6 (Build 20G165)

## Steps:

### Case One:

#### Check upgrade paths to confirm encrypted wallet(s) in the `Preferences` file are decrypted

1. fresh install `1.27.111` 
2. launch Brave using Rewards staging
3. enable Rewards
4. accept UGP grant
5. close Brave
6. open `Preferences` in `/Users/stephendonner/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev/default`  (confirm wallets are `encrypted`)
7. confirm the wallet is `decrypted`
8. upgrade to `1.31.68`
9. accepted UGP grant (`2x 2.00 BAT`)
10. tipped and auto-contributed
9. open `Preferences` in `/Users/stephendonner/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev/default` 
10. confirm `brave.rewards.wallet.brave` is `unencrypted`

Actual:

`1.27.111` was `encrypted`:

```
"wallets": {
        "brave": "djEwW1...9QOyo=",
        "uphold": "djEwi8...IrIA=="
      }
```

`1.31.68` upgrade was `decrypted`

```
"wallets": {
        "brave": "{\"payment_id\":\"a72952c9-c5d6-4177-a0ff-d8041a42cfcd\",\"recovery_seed\":\"FU3qO/25Hke0nF5BTWHvjObJrTrIhtKLU9vpbaq+qQQ=\"}",
```

example | example |
---------|----------|
<img width="1312" alt="Screen Shot 2021-09-30 at 9 58 10 AM" src="https://user-images.githubusercontent.com/387249/135507265-4d5c4dec-69f4-42c2-b8cb-ab3382afcaae.png"> | <img width="1312" alt="Screen Shot 2021-09-30 at 9 59 19 AM" src="https://user-images.githubusercontent.com/387249/135507461-c648bf5c-14a5-4aa0-8ea7-687660723eb5.png"> |  | . |




### Case Two:

#### Check upgrade paths to confirm corrupted wallets in the `Preferences` file are not decrypted

1. fresh install `1.29.81`
2. launch Brave using Rewards staging
3. enable Rewards
4. accept UGP grant
5. close Brave
6. corrupt the wallet by adding junk characters to the `wallet` in `Preferences`
7. upgrade to `1.31.68`
8. open `Preferences` in `/Users/stephendonner/Library/Application\ Support/BraveSoftware/Brave-Browser-Beta/default` 
8. confirm `brave.rewards.wallet.brave` is `encrypted`

Actual:

```
"wallets": {
        "brave": "^H@@H@HH@H@.djEwiSST...ouijOMY=",
```

Confirmed I got the following in logs:

```
[12977:259:0930/101840.179888:INFO:wallet.cc(260)] Parsing of brave wallet failed
[12977:259:0930/101840.180770:INFO:wallet_create.cc(32)] Wallet does not exist and could not be created
[12977:259:0930/101840.181386:INFO:promotion.cc(315)] Wallet couldn't be created
```

example | example
---------|---------
<img width="1783" alt="Screen Shot 2021-09-30 at 10 15 13 AM" src="https://user-images.githubusercontent.com/387249/135508180-c50ad9bd-5575-482b-a5e8-b70926e09c79.png"> | <img width="1245" alt="Screen Shot 2021-09-30 at 10 19 24 AM" src="https://user-images.githubusercontent.com/387249/135508183-ff510535-2754-4a1a-a2bb-231a64f8cb2c.png">



### Case Three:

#### Check fresh install that vBAT wallet is persisted unencrypted

1. fresh install `1.31.68`
2. launch Brave using Rewards staging
3. click on the BAT icon in the URL bar
4. enable Rewards
5. accept UGP grant
6. close Brave
7. open `Preferences` in `/Users/stephendonner/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev/default` 
8. confirm `brave.rewards.wallet.brave` is `unencrypted`

Actual:

```
"wallets": {
        "brave": "{\"payment_id\":\"71995091-ce62-49c0-819f-45fd5d52091d\",\"recovery_seed\":\"VAJ16s4PN6LRR7wgHPY+Yt2J3z4EY6pnL8hvYVI5s1s=\"}",
```

### Case Four:

#### Check restoring a wallet is persisted unencrypted

1. fresh install `1.31.68`
2. launch Brave using Rewards staging
3. enable Rewards
4. click on `Manage your wallet`
5. click on the `Restore` tab
6. enter a recovery key (`https://docs.google.com/spreadsheets/d/1Bi2uqiy93KfoP9Jayz5Bw-hRvU7aKadAjUozKT5t1UQ/edit#gid=1418117328` ) and click `Restore`
7. close Brave
8. open `Preferences` in `/Users/stephendonner/Library/Application\ Support/BraveSoftware/Brave-Browser-Beta/default` 
9. confirm `brave.rewards.wallet.brave` is `unencrypted`

Actual:

```
"wallets": {
        "brave": "{\"payment_id\":\"108809fb-497e-4ed6-a0cd-abfc6224497d\",\"recovery_seed\":\"gqHvjgCit0fsn+VYOlluWRpdbcQeBh97YBv1C7sPZHc=\"}",
```
