### ISSUE TITLE
[cr93 followup] Turn off kReadLater feature by default

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#17573]
This feature got turned on by default on Desktop in cr93. We need to turn it back off.

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/8bdb3b260d33741fc75658e511751cacc1b9f4c7

@rebron says "We need to disable Reading List for now, we need to make a modification to the bookmarks UI window, otherwise there’s no UX to actually use Reading List."

**Comment by huyz** [comment]
Enabling brave://flags/#read-later worked for me in v1.38.80 on macOS.
I didn't even need to enable brave://flags/#side-panel which I've read was needed in the past.
Can this feature be enabled by default now?

**Comment by dairefagan** [comment]
On linux stable v1.35.100 I can access reading list but only by using #read-later and #side-panel.
