### ISSUE TITLE
Brave News Display Ads length may affect Brave Ads History render

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#17575]
## Description 
The new Brave News Display ads have a different character length limit than Push Notification Ads. The `title` property of the creative gets shown in the Ads History and mess with the way we render the creatives.

Likely the cause of: https://github.com/brave/brave-browser/issues/17543
Similar to issue: https://github.com/brave/brave-browser/issues/9799

## Steps to Reproduce

   1. Open Brave News
   2. Attempt to find a Brave Stickers Ad in Brave News
   3. Look at Ads History

## Actual result:

<img width="1433" alt="Screen Shot 2021-08-19 at 13 54 11" src="https://user-images.githubusercontent.com/24831890/130120026-b565444a-5508-403c-aefb-097840c93cee.png">
<img width="1061" alt="Screen Shot 2021-08-19 at 14 14 25" src="https://user-images.githubusercontent.com/24831890/130122658-62dd7eb1-3481-4bed-a40a-4015a4b1f330.png">

## Expected result:
Probably do some kind of text wrap

## Brave version (brave://version info)
1.28.105 Chromium: 92.0.4515.131 (Official Build) (arm64)

## Version/Channel Information:
Release, but likely all channels

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.30.45 Chromium: 93.0.4577.51 (Official Build) nightly (64-bit)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | Windows 10 OS Version 2009 (Build 22000.160)

Steps:
1. clean profile
2. launch Brave
3. open `brave://rewards` and click `Start using Rewards`
4. open a new-tab page
5. scroll down
6. click on `Show Brave News`
7. keep scrolling until you see one or more `ads` with long titles
8. load `brave://rewards` again

Confirmed the ads' titles are cropped, with an ellipsis `...` for the missing text.

![ads-history-panel](https://user-images.githubusercontent.com/387249/130693254-e504b9d5-ad89-43ad-a269-eed01034aa9a.png)

**Comment by btlechowski** [comment]
Good to check on all platforms.
