### ISSUE TITLE
Search DuckDuckGo for text in Tor Window still uses Google

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#1758]
## Description 
If you right-click some text, it gives an option called "Search DuckDuckGo for …". In Private Window with Tor, the search engine is DuckDuckGo by default. However, if you click the menu option, it searches with Google instead. This is very inconvenient because Google is not Tor-friendly.

## Steps to Reproduce
   1. Select hamburger menu > New private window with Tor.
   2. Navigate to any website with text (e.g., github.com).
   3. Right-click any text.
   4. Click Search DuckDuckGo for …

## Actual result:
The search is with Google.
![](https://user-images.githubusercontent.com/19424103/47260658-5fee6d00-d485-11e8-9427-3b566515c84d.gif)

## Expected result:
The search should be with DuckDuckGo.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 0.57.1 Chromium: 70.0.3538.67 (Official Build) dev(64-bit)
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by dnguneratne** [comment]
I'd like to take a crack at this. Any tips on where I should start?

**Comment by diracdeltas** [comment]
In b-l we also had this issue with the 'Search for image' option when you right click on an image. If that menu option in fact exists in Tor sessions, it should just be removed.

**Comment by simonhong** [comment]
Similar issue on private window(non tor) - https://github.com/brave/brave-browser/issues/1037

**Comment by bbondy** [comment]
Updated milestone to 0.58.x since it was merged there.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified STR in description
