### ISSUE TITLE
[Android] Chromium 93 sync data types extra controls

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#17580]
On 1.30.34, Chromium 93 in `Settings => Sync => Data Preferences` there are extra controls which should not be there:

![Screenshot_20210819-231019](https://user-images.githubusercontent.com/24739341/130137534-07ab5067-9af5-4e75-9e23-f86f5e95e662.png)

Expected not to have `Sign out and turn off sync` and `Advanced`.

cc @samartnik , @mkarolin

**Comment by samartnik** [comment]
Good finding @AlexeyBarabash, I suggest to add unit tests to check items here to avoid such issues on rebases.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.29.74 x64 build
- Verified Chromium UI is removed 

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=350 src=https://user-images.githubusercontent.com/17010094/131302455-81b1aa70-a4b8-4749-a017-8758264328ce.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/131302542-ff1a2452-27d6-4a81-85a0-9c52ed673aa3.png>
