### ISSUE TITLE
Shouldn't be able to set validation-failed gateway strings

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17604]
## Description 

Shouldn't be able to set validation-failed gateway strings.

Found while testing https://github.com/brave/brave-browser/issues/16999.

## Steps to Reproduce

1. new profile
2. launch Brave
3. load `brave://settings/ipfs`
4. click on the `Change` button for `IPFS public gateway fallback`
5. enter `https://blah`
6. click `Submit`
7. notice the error message
8. cancel the dialog
9. look at the value in `brave://settings/ipfs` for `IPFS public gateway address`

## Actual result:

I was able to set `https://blah` as the gateway host, even though it failed validation.

example | example | example
---------|---------|---------
<img width="1312" alt="Screen Shot 2021-08-20 at 9 38 29 AM" src="https://user-images.githubusercontent.com/387249/130267047-947a7dfa-fcc3-4424-bd47-8ab0bba4fafd.png"> | <img width="1312" alt="Screen Shot 2021-08-20 at 9 38 43 AM" src="https://user-images.githubusercontent.com/387249/130266787-ab74b09d-0b07-4597-9cdd-ef6a35fb957c.png"> | <img width="1312" alt="Screen Shot 2021-08-20 at 9 39 17 AM" src="https://user-images.githubusercontent.com/387249/130266792-decb6166-94d5-4e84-9d70-4393b32daf23.png">

## Expected result:

Should still be the default `https://dweb.link` after throwing the error message.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.30.38 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 11.5.2 (Build 20G95)

/cc @spylogsster @lidel

**Comment by stephendonner** [comment]
**Verified `PASSED`** using the inline test plan with


Brave | 1.30.42 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 11.5.2 (Build 20G95)

### Steps:
1. new profile
2. launched Brave
3. loaded `brave://settings/ipfs`
4. clicked on the `Change` button for IPFS public gateway fallback
5. entered `https://blah`
6. clicked `Submit`

Confirmed I received `Invalid gateway address` error message in the dialog, and the `Submit` button didn't do anything.

<img width="1128" alt="Screen Shot 2021-08-23 at 3 03 48 PM" src="https://user-images.githubusercontent.com/387249/130525520-f6a3f5dc-538f-4846-b7d2-1195ffab7ea7.png">

**Comment by Ayern12** [comment]
## no in 2 days I just withdrew..Saba ya ..

**Comment by LaurenWags** [comment]
Updated to `release-notes/exclude` per discussion with @rebron and @kjozwiak
