### ISSUE TITLE
DuckDuckGo + autocomplete suggestions in address bar does not work

### ISSUE THREAD

**Issue by valynor** [brave/brave-browser#17602]
When searching from the address bar with DDG I do not get any search suggestions **except** for old searches from the history and URLs. 
Google, Brave Search beta and e.g. searx.be work as expected and **do** show search suggestions in the address bar. 

My query URL for DDG is https://duckduckgo.com/?q=%s
With that exact same query URL I **do** get DDG search suggestions from address bar searches in both Firefox 91 and Chrome 92 on the same computer.

Brave | 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | Linux Mint 19.3

**Comment by rebron** [comment]
@valynor Do you have brave://settings/privacy `Autocomplete searches and URLs turned on`

With that setting you should see the following (I used `test` as my query):

<img width="774" alt="Screen Shot 2021-08-20 at 9 41 05 AM" src="https://user-images.githubusercontent.com/5951041/130266386-b2df31a5-7948-4ea0-9650-406ef8a70aef.png">

<img width="833" alt="Screen Shot 2021-08-20 at 9 40 56 AM" src="https://user-images.githubusercontent.com/5951041/130266375-72e889b0-740d-4a13-b6e6-c0de3732ceb5.png">

**Comment by valynor** [comment]
@rebron 
"Autocomplete searches and URLs" is turned on. 

Here's how it looks with DDG:
![s1](https://user-images.githubusercontent.com/23384233/130274419-87f4b486-13f0-49d8-b692-5687b1b86f04.png)
Just search history and 2 bookmarks.

With searx.be it looks like this:
![s2](https://user-images.githubusercontent.com/23384233/130274622-638071c4-99bf-4f3f-aa78-388cf9c1be1c.png)
Proper search suggestions and search history (but no bookmarks).

Google auto suggestions work fine, too.

**Comment by rebron** [comment]
@valynor Did you select DDG from the Default search engine list or from Other Search Engines? 
And if from Other Search Engines, did you add the DDG url manually or did you go to DDG and then wait to see DDG listed?

I might be wrong, but I'm going to guess you added DDG manually and that might not have registered the autocomplete url that's needed when waiting for DDG to show up on that list or selecting from the default search engine list.

Can you try selecting from the Default search engine list? Or deleting the DDG entry you have in brave://settings/searchEngines , go to ddg, and add it back when it shows up.

**Comment by valynor** [comment]
@rebron 

Indeed, I added DDG manually. 
I removed the DDG entry completely from the search engines list as per your suggestion and after visiting duckduckgo.com it reappeared and with this new entry suggestions work again.

Thanks a lot for your help & time. <3

**Comment by rebron** [comment]
Cool. Closing as fixed. @valynor You can thank me by using Brave Search instead :-)
