### ISSUE TITLE
Build out Confirm Send UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#17600]
## Description 
Build out the Confirm Send UI for the Buy/Send/Swap component

You can find the specs for this component in Figma / Desktop Crypto Wallets.

Add the component too storybook with mock data for testing.

## Expected result:

Component should be visible and functional in Storybook under the Wallet/Desktop/Concepts and Wallet/Desktop/Components tabs.

**Comment by onyb** [comment]
Can't find the mockups on Figma. Do you have a direct link?
