### ISSUE TITLE
Force network requests from YouTube to be blocked in aggressive mode

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#17607]
YouTube sometimes breaks spectacularly when not kept in sync with uBlock Origin's upstream filter changes. We should keep our behavior on `*.youtube.com` as similar as possible, meaning kept in aggressive mode at all times.

**Comment by antonok-edm** [comment]
Leaving this as `release-notes/exclude` because it's a tweak to the bigger change in https://github.com/brave/brave-browser/issues/17366

**Comment by Ayern12** [comment]
##owh you is commander pattner

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.42 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 11.5.2 (Build 20G95)

`YouTube.com` Steps:
1. Set the `brave-adblock-default-1p-blocking` flag to `Disabled` in `brave://flags`.
2. Visited `youtube.com` and clicked on a video.
3. Ensured no pre-roll ads appear.
4. Verified that there are blocked requests in the Shields panel, and that at least one is from `youtube.com` or one of its subdomains.

example | example
---------|----------
<img width="1128" alt="Screen Shot 2021-08-23 at 3 00 32 PM" src="https://user-images.githubusercontent.com/387249/130525145-f01cd7e8-fff9-4491-a77b-47bac08703f4.png"> | <img width="1124" alt="Screen Shot 2021-08-23 at 2 51 32 PM" src="https://user-images.githubusercontent.com/387249/130525063-e7f6e8d7-12e9-44a0-9275-0a9efed1b64f.png">

`m.YouTube.com` Steps:
1. Set the `brave-adblock-default-1p-blocking` flag to `Disabled` in `brave://flags`.
2. Visited `https://m.youtube.com/?persist_app=1&app=m` and clicked on a video.
3. Ensured no pre-roll ads appear.
4. Verified that there are blocked requests in the Shields panel, and that at least one is from `youtube.com` or one of its subdomains.

example | example
---------|----------
<img width="1312" alt="Screen Shot 2021-08-23 at 2 50 12 PM" src="https://user-images.githubusercontent.com/387249/130524973-a0f4568d-52d7-495f-a2a3-fd8b5f339757.png"> | <img width="1088" alt="Screen Shot 2021-08-23 at 2 54 33 PM" src="https://user-images.githubusercontent.com/387249/130524982-b6ddb289-4460-4091-b3f4-54a85ca365f4.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.30.76 x64 beta build
- Verified test plan from [brave-core#9808](https://github.com/brave/brave-core/pull/9808)
- Verified disabling flag doesn't show pre-roll ads on `youtube.com` or `m.youtube.com`

![image](https://user-images.githubusercontent.com/17010094/133628080-c5c08157-4712-451a-98d9-c8080df116c2.png) | ![image](https://user-images.githubusercontent.com/17010094/133628121-d14a16e8-6125-4f18-bdad-290f2e324c5b.png) | ![image](https://user-images.githubusercontent.com/17010094/133628155-2dbe416c-0579-48a1-aeb8-021bb37d7ed4.png)
-- | -- | --

--------
Verification passed on Samsung Tab A with Android 10 running 1.30.76 x64 beta build
- Verified test plan from [brave-core#9808](https://github.com/brave/brave-core/pull/9808)
- Verified disabling flag doesn't show pre-roll ads on `youtube.com` or `m.youtube.com`

![image](https://user-images.githubusercontent.com/17010094/133630881-ce834db5-c7d4-48e3-9688-e363e5280941.png) | ![image](https://user-images.githubusercontent.com/17010094/133630922-88d1d7e6-3d10-4d67-bb1f-3bd993522bdb.png) | ![image](https://user-images.githubusercontent.com/17010094/133631001-fcc4c6d7-4e71-40aa-8372-0ae7130deef7.png)
-- | -- | --
