### ISSUE TITLE
Already Turn Off Brave Rewards but Ads Keep Showing

### ISSUE THREAD

**Issue by Rizr09** [brave/brave-browser#17615]
I've seen problems like this but on Mac OS several days ago, it's like Ads turned off but in the background still running

## Description
Haven't turned on Brave Rewards for several weeks and I got these ads

## Steps to reproduce 
   1. Make sure disabled Brave Rewards 
   2. Open a new tab several times 
   3. See those ads

## Actual result
https://user-images.githubusercontent.com/75122686/130302247-06afd6a2-44bd-4a64-a2b6-466ca020f465.mp4

## Expected result
No ads

## Issue reproduces how often
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 8.1.0
   
## Brave version
1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
-

**Comment by diracdeltas** [comment]
if you're talking about the sponsored images on the new tab page, those are there regardless of the ads enabled setting but can be turned off via https://support.brave.com/hc/en-us/articles/360041346091-How-do-I-enable-or-disable-images-on-my-New-Tab-Page-Android-.

**Comment by Rizr09** [comment]
Ah, thank you for your explanation. I'll close this 👍
