### ISSUE TITLE
Brave dev crashes everytime I leave or close tab from Inbox by Google (MacOS)

### ISSUE THREAD

**Issue by mil1i** [brave/brave-browser#1762]
## Description 

I don't experience this on Windows 10, but on my MBP using Brave Dev build it crashes every time I try to close a tab that has Inbox by Google open. Same thing occurs just trying to navigate away from Inbox.

## Steps to Reproduce

   1. Open Brave Dev
   2. Go to Inbox (by Google) [logged in]
   3. Open another bookmark, or close the tab that has Inbox open

## Actual result:

Brave Dev browser crashes and asks to reopen or remain close or report to Apple.

## Expected result:
Close tab, or allow navigating to another bookmark/website.

## Reproduces how often: 

Happens every time with the current build.

## Brave version (brave://version info)

0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
0.57.1 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Only occurs on Dev build. Does not occur on Beta build.
- Does it reproduce on browser-laptop? 
Do not have this installed.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes
- Is the issue reproducible on the latest version of Chrome? 
No.

### Additional Information

After retesting with Shields disabled from Inbox, it does not crash.

**Comment by rebron** [comment]
This looks fixed. 
Can you verify with a recent Brave Dev build?
Version 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)

**Comment by mil1i** [comment]
I tested a few times with Shields up and did not crash closing tab or navigating to another site! Looks fixed to me as well.

Thank you!

**Comment by rebron** [comment]
Looks like this was fixed in latest build marking closed.
