### ISSUE TITLE
Shield button is disabled on macOS Montery

### ISSUE THREAD

**Issue by A-Sam** [brave/brave-browser#17626]
## Description 
Shield button is disabled&gray and can't be clicked for any website.

## Steps to Reproduce
Update to macOS Montery from Big Sur.

## Actual result:
![Screen Shot 2021-08-23 at 10 38 19GMT+2](https://user-images.githubusercontent.com/11005214/130417085-bbad310b-e8db-4c0f-bcc6-5a5f4bcf8c17.png)

## Expected result:
Active button to access shield properties and report.

## Reproduces how often: 
Always. After restart and reinstall.

## Brave version (brave://version info)
Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
macOS Montery

## Miscellaneous Information:
Brave is freezing more often now. Can't be reproduced. But mainly happens while editing Jupyter notebooks or editing python notebooks on Kaggle.

**Comment by Tonev** [comment]
@A-Sam 

Clearing `Site and Shields Settings` resets all `Brave Shields` settings, let's give it a try. Do the following:

1. Open `brave://settings/clearBrowserData`.
2. Click on `Advanced` and set `Time range` to `All time`.
3. Select `Site and Shields Settings` and click on `Clear data`.

**Comment by A-Sam** [comment]
Ok that did it. It seems I had to clear everything from inside.

Thanks @Tonev

**Comment by Tonev** [comment]
@A-Sam 

You are welcome! Just a reminder that if you were using different global `Brave Shields` settings than the default ones before clearing `Site and Shields Settings`, you will have to adjust them via `brave://settings/shields`.

**Comment by A-Sam** [comment]
> @A-Sam
> 
> You are welcome! Just a reminder that if you were using different global `Brave Shields` settings than the default ones before clearing `Site and Shields Settings`, you will have to adjust them via `brave://settings/shields`.

Got it. Yes seems some custom settings are gone but it's fine.

 Thanks a lot!
