### ISSUE TITLE
brave://rewards broken

### ISSUE THREAD

**Issue by Sh1d0w** [brave/brave-browser#1763]
Brave version: Version 0.57.1 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)

![Broken rewards screen](https://i.imgur.com/mPcb8FZ.png)

**Comment by NejcZdovc** [comment]
@Sh1d0w thx for reporting. This was already fixed in the code and will be available in the next dev release. I will close this one, but if this is still a problem with new version feel free to reopen it.
