### ISSUE TITLE
C93 missing permission for Crypto Wallets Ledger devices - usbDevices

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#17646]
@lukemulks reported this at first
<img width="838" alt="Screen Shot 2021-08-23 at 4 54 24 PM" src="https://user-images.githubusercontent.com/831718/130518127-93dc9ff0-b613-4b44-97d8-39646fef4969.png">

**Comment by kjozwiak** [comment]
This will get QA'd via https://github.com/brave/brave-browser/issues/17655 as it has STR/Cases and more information.
