### ISSUE TITLE
Crypto Wallets extension status being initialised after every browser update

### ISSUE THREAD

**Issue by KudretBayram** [brave/brave-browser#17656]
## Description 

Whenever an update is performed, the Crypto Wallets extension is automatically toggled to "Enabled". It should maintain settings ("disabled" in my case because there's a conflict with MetaMask) prior to the update. 

## Steps to Reproduce

   1.  Disable Crypto Wallets Extensions
   2. Perform Update
   3. Check Crypto Wallets Extension to notice it is now enabled

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

All.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Just did.
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Rather straight forward I would assume, the Crypto Wallets extension status is being initialised with each browser update.

**Comment by bbondy** [comment]
Could you verify @srirambv ?

**Comment by srirambv** [comment]
It only happens if you have `Load crypto wallet at startup` setting enabled. 

Here's how it works with that setting disabled

https://user-images.githubusercontent.com/17010094/132289237-908760a6-00de-453a-91b9-b79dae56ae08.mov

And with the setting enabled

https://user-images.githubusercontent.com/17010094/132288856-ccc56fe1-4c92-4cde-a52a-4fde34cb62ab.mov

Verified it on all platforms and its the same behaviour. @KudretBayram Can you check if you have the setting enabled? If so please disable it and check. As it is it should not be a problem unless you have set default Dapp provider to ask in which case it will have conflict if you try to use MM.

**Comment by KudretBayram** [comment]
Thanks for that wonderfully detailed response @srirambv .

I understand what you've demonstrated and it indeed does work that way.

There are however a couple of logic / UX issues in handling it like that:

1) Using "Crypto Wallets" as the name for the native wallet for Brave is confusing. MetaMask, Keplr, Arweave etc... are all "crypto wallets".

2) The "Load Crypto Wallets on start-up" option is confusing for the reason I mentioned above - which one are you loading? All of them, or just the native one? 

3) The "Load Crypto Wallets on start-up" supersedes the enabled/disabled toggle option for the specific native Crypto Wallets extension. Even if the user manually disables the native "Crypto Wallets" extension, this setting over-rides that one. 

From a developers perspective, I'm assuming that you're using that value to run functions in preparation for use of the native Crypto Wallets, but from a user perspective it's confusing.

As a user, if you've toggled a feature off, it should remain off. Having a secondary option which toggles it back on is not ideal.

I am a big fan of what you guys are doing and I write only in the interest in helping further improve your fantastic product. 

Thank you for your work. Please keep going!

**Comment by srirambv** [comment]
@KudretBayram I understand why its confusing. Probably if the setting was worded as `Load Brave Crypto Wallet on start-up` , it would have been more clearer to users.  The setting was specifically implemented for Brave's Crypto Wallet and not other extensions that are installed, as there were a number of iteration which changed the way Brave CW worked along with MM. 

With the native wallet implementation I think a lot of these issues would be resolved. cc: @jamesmudgett 

I'll go ahead and close the issue for now. We can continue to discuss on the design part of it here if required I've tagged @jamesmudgett  for design considerations.
