### ISSUE TITLE
Brave crashes when closing a private tab after opening shields on the private tab

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#17657]
## Description 
Opening the `Brave Shields` panel via the icon in the address bar while in a private tab leads to an immediate crash upon closing the private tab.

- The crash will happen regardless of the opened website, it can be any website.
- There is nothing at `brave://crashes`, neither any message appears before Brave crashes.

## Steps to reproduce 

1. Open Brave.
2. Open a private tab from the 3 dots menu.
3. Open a random website.
4. Click on the `Brave Shields` icon in the address bar to open the `Brave Shields` panel.
5. Click on the `Brave Shields` icon in the address bar to close the opened `Brave Shields` panel.
6. Click on the opened tabs menu and close the opened private tab.

## Actual result 
Brave closes immediately without any message. There is nothing at `brave://crashes`. 

## Expected result
No crash.

## Issue reproduces how often 
Easily reproduced.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): `Huawei Mate 10 lite`
   - Android version: 8
   
## Brave version
1.28.106

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

The issue was originally reported by Wiggly in Brave Community:
https://community.brave.com/t/opening-shield-settings-in-private-browsing-crashes-brave/273237

This is not a new issue as Wiggly reported the issue while using `Brave 1.27.111`.

**Comment by srirambv** [comment]
Cant repro it on 1.29.76 build. Can this be checked on the new release and see if it still repro's

**Comment by Tonev** [comment]
@srirambv 

Since `1.29.76` is still not available to me, I downloaded `Brave Beta` and `Brave Nightly`. Unfortunately, reproduced the issue in both.

`Brave - Beta 1.30.57`
`Brave - Nightly 1.31.10`

I'll update my ticket including that the issue is reproducible in `Beta` and `Nightly`.

**Comment by Tonev** [comment]
@srirambv 

I've seen that you provide video recordings in a lot of your `Android` tickets. If you could recommend me a simple application that could the job, I could record my screen, that might be of help to you and others to track down the issue.

**Comment by Tonev** [comment]
@srirambv 

I just received the `1.29.76` update and tested whether the issue is present - unfortunately, it is.

Steps to reproduce:

1. Opened `Brave`.
2. Opened a private tab from the 3 dots menu.
3. Opened a random website.
4. Clicked on the `Brave Shields` icon in the address bar to open the `Brave Shields` panel.
5. Clicked on the `Brave Shields` icon in the address bar to close the opened `Brave Shields` panel.
6. Clicked on the opened tabs menu and closed the opened private tab.

Brave immediately froze and got minimized. I successfully re-opened the same instance by clicking on the button that shows minimized applications.

 I'll ask Wiggly from `Brave Community` whether they're able to re-open the same Brave instance after freeze, and will provide an update after Wiggly answers me.

**Comment by Tonev** [comment]
Wiggly:

> Yes, it still crashes my browser on 1.29.76.

https://community.brave.com/t/opening-shield-settings-in-private-browsing-crashes-brave/273237/5?u=rethanis

**Comment by srirambv** [comment]
@Tonev thanks for the details I can repro now with the steps you mentioned in https://github.com/brave/brave-browser/issues/17657#issuecomment-912243194.

I guess I was switching back to the tabs. Had to stay on the tab tray for the app to crash. 

@samartnik can we fix this and get it uplifted as this is already in release and will also repro on 1.29.77

**Comment by Tonev** [comment]
@srirambv 

You are most welcome, I thank you for your attention ;)

**Comment by bsclifton** [comment]
Thanks for the great details here @Tonev 😄👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 with 1.29.78 x64 build
- Verified steps from issue description
- Verified no browser crash when closing private tabs
