### ISSUE TITLE
`TransportOpenUserCancelled` error when attempting to connect a ledger nano using CW

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#17655]
## Description 

Connecting to a `Ledger Nano` stopped working on Nightly. You'll get a `TransportOpenUserCancelled`error when viewing the browse console for CW via `brave://inspect/#extensions`. However, Trezor works without any issues once you've installed the needed bridge so it seems to be `ledger nano` related.

## Steps to Reproduce

   1. launch Nightly (used `1.30.41 Chromium: 93.0.4577.51` in this case)
   2. ensure that you have a nano ledger connected/unlocked and `ETH` selected
   3. visit `brave://wallet` and attempt to connect to the ledger nano

I tried connecting it on `BETA` & `Release` and it worked without any issues:

* `1.29.67 Chromium: 92.0.4515.159` - **Couldn't reproduce**
* `1.28.106 Chromium: 92.0.4515.159` - **Couldn't reproduce**

## Actual result:

![ledgerNightly](https://user-images.githubusercontent.com/2602313/130556559-d298ae95-a93e-4cf7-99fb-d475b0fba2e0.png)

## Expected result:

![BETA](https://user-images.githubusercontent.com/2602313/130556653-e913bcc6-0832-465c-9668-bce7e4d75801.png)

## Reproduces how often: 

100% reproducible using the STR mentioned above.

## Brave version (brave://version info)

```
Brave | 1.30.41 Chromium: 93.0.4577.51 (Official Build) nightly (64-bit)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | Windows 10 OS Version 2009 (Build 19042.1165)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @mkarolin @bsclifton @rebron @bbondy @srirambv

**Comment by kjozwiak** [comment]
Closing as this was fixed via https://github.com/brave/brave-core/pull/9827.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (x86_64)
-- | --
Revision | `c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}`
OS | macOS Version 11.5.2 (Build 20G95)

- Verified no error while connecting Ledger Nano
- Verified able to unlock h/w device and link an address

![image](https://user-images.githubusercontent.com/17010094/131335199-45f29041-d838-4bea-b9c5-b41e0a1af6c5.png) | ![image](https://user-images.githubusercontent.com/17010094/131335215-ab2c4f4d-67de-4140-8725-26b0525436ca.png)
-- | --


---------
Verification passed on 

Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (64-bit)
-- | --
Revision | `c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}`
OS | Windows 10 OS Version 2009 (Build 19043.1110

- Verified no error while connecting Ledger Nano
- Verified able to unlock h/w device and link an address

![image](https://user-images.githubusercontent.com/17010094/131336489-05d27348-4542-44e4-b292-bb9955ee0b5d.png) | ![image](https://user-images.githubusercontent.com/17010094/131336516-424d6394-46eb-461e-87f7-5c1490d1c689.png)
-- | --

--------
Ledger still fails to connect on Linux.
