### ISSUE TITLE
Rewards panel not showing "verified" status in some cases

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#17669]
## Description 

For some users, the Rewards panel is not displaying Twitter and/or Youtube channel verification status in the Rewards panel. Strangely, other websites _do_ appear to show site verified status.
(Expected display on left, issue on right)
![image](https://user-images.githubusercontent.com/3299098/130669618-b0c453e1-ba61-4b58-a569-663f58155806.png) ![image](https://user-images.githubusercontent.com/3299098/130669644-cfdc0363-dcb4-4c48-a91a-d77ce6360ec9.png)

Issue _appears_ to be intermittent and seems to "fix" itself temporarily, although what fixes it is still unclear. For users who are experiencing this, it appears to be broken consistently (as opposed to intermittent) and are unable to resolve the issue after:

- Relaunching/restarting browser
- Clearing cache/cookies
- Updating to latest build
- Visiting both `.es` and/or `.com` 
- Changing language settings for both sites as well as language settings in the browser

## Steps to Reproduce/ Reproduces how often: 
Steps to reproduce the issue are unclear. At the time of writing this, the issue appears to show up most consistently in Nightly build, version 1.30.41 (at the time of writing this). 

## Desktop Brave version:

In addition to Nightly build, user's are seeing this issue in Brave stable `v1.28.150` and `1.28.106`.

## Version/Channel Information:

Stable/Nightly

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

Internal Brave conversation here:
https://bravesoftware.slack.com/archives/CB0KCRCQN/p1629303796208800 
Community thread w/some users experiencing the issue:
https://community.brave.com/t/idk-if-its-a-bug-please-read-and-help-me/275583/30

**Comment by kjozwiak** [comment]
I can manage to reproduce the above almost 100% on `Win 10 x64` using the following build:

```
Brave | 1.30.43 Chromium: 93.0.4577.51 (Official Build) nightly (64-bit)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | Windows 10 OS Version 2009 (Build 19042.1165)
```

STR:

* launch `1.30.43 Chromium: 93.0.4577.51`
* enable rewards via the rewards panel
* visit https://www.youtube.com
* search `hot ones` and click on the `First We Feast` channel
* click on `Videos` within the `First We Feast` channel
* pick a random video from the list
* once that video loads, click on the rewards panel

I also get the following whenever I click on the rewards panel on YT (not sure if related):

```[61996:72356:0824/134303.039:INFO:CONSOLE(1)] "Greaselion script loaded: youtubeBase.ts", source: chrome-extension://feipjgjfhmnfhhmbkclfopokbcgnpnnd/youtubeBase.bundle.js (1)
[61996:72356:0824/134303.040:WARNING:CONSOLE(1)] "Received external message from a sender who is not allowed to send messages to this background. Origin: https://www.youtube.com, URL: https://www.youtube.com/", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[61996:72356:0824/134303.160:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'ruleExceptions')", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)```

**`Example (Existing profile)`** | **`Example (New profile)`**
----------------------------------|--------------------------------
![image](https://user-images.githubusercontent.com/2602313/130677623-f8cb1683-9e54-4e1d-879c-daa4349b277a.png) | ![image (1)](https://user-images.githubusercontent.com/2602313/130677666-6bd0fbdf-91b8-4992-88d1-9d55a535b177.png)

**Comment by emerick** [comment]
I can repro following the steps @kjozwiak provided. I see the following error in the console log for the Rewards extension:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'catch')
    at Module.359 (brave_rewards_panel_background.bundle.js:1)
    at r (brave_rewards_panel_background.bundle.js:1)
    at brave_rewards_panel_background.bundle.js:1
    at brave_rewards_panel_background.bundle.js:1
```

**Comment by zenparsing** [comment]
The Rewards extension still uses extension manifest v2, which does not support promise return values on `chrome.*` APIs. We should probably remove the call to `.catch(...)` and add a tslint ignore comment if TS generates an error.

**Comment by Miyayes** [comment]
I think we can close this, as it is superseded and resolved by https://github.com/brave/brave-browser/issues/14602
