### ISSUE TITLE
default browser dialog (first run dialog) doesn't show on Chromium 93 versions of Nightly

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#17667]
## Description 

Chromium 93 versions of Brave Nightly do not show the default browser dialog on first run. The prompt is still shown on 3rd and 20th open, but not the first open.

This worked in 1.30.31 (Chromium 92) and stopped working when Chromium 93 was merged.

## Steps to Reproduce

   1. Clean install 1.30.x w/ Chromium 93 (be sure you don't have any existing Nightly profile)
   2. Install app
   3. Launch app

## Actual result:

Browser opens, no default browser dialog prompt / first run dialog box

## Expected result:

<img width="499" alt="Screen Shot 2021-08-24 at 12 50 44 PM" src="https://user-images.githubusercontent.com/28145373/130657947-17b905d3-4bde-4dca-a3fe-7a74905e1c81.png">

## Brave version (brave://version info)

Brave | 1.30.44 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 10.15.7 (Build 19H1323)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, 1.28.x
- Can you reproduce this issue with the beta channel? no, 1.29.x
- Can you reproduce this issue with the nightly channel? yes with Chromium 93 versions (chromium 92 versions work as expected)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @mkarolin @rebron @brave/legacy_qa

**Comment by LaurenWags** [comment]
I finally just got this prompt after a bunch of (~15) installs. Then I tried again after I got it, and didn't receive the prompt 😞

**Comment by simonhong** [comment]
This is upstream issue - filed https://bugs.chromium.org/p/chromium/issues/detail?id=1243221
