### ISSUE TITLE
Distorted colors on transparent images, emoji and icons

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#1766]
## Description 

Icon's border (apparently with yellow background) is causing a green border on icons, emoji and transparent images (with other colors distortion)

## Steps to Reproduce

   1. You can see this issue on Facebook (Like)
   2. You can see this issue on Bitcoin website
   3. You can see this issue while browsing images (png, svg?) with transparent background

## Actual result:

![Screenshot](https://i.imgur.com/fHBlDdO.png)

## Expected result:
![Screenshot](https://i.imgur.com/X1EGlfp.png)

## Reproduces how often: 

In every icon with yellow/orange/transparent background

## Brave version (brave://version info)

0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
Linux (Ubuntu 18.04.1)

**Comment by srirambv** [comment]
Does it still happen if you enable/disable hardware acceleration from settings? 
`chrome://settings/system`

**Comment by ntilotta** [comment]
> Does it still happen if you enable/disable hardware acceleration from settings?
> `chrome://settings/system`

No, I confirm the issue has been solved by disabling hardware acceleration, but what if I wanna use hw acceleration instead? it's a problem related to my side (xorg, drivers) or it depends on brave' side?

**Comment by ntilotta** [comment]
> Does it still happen if you enable/disable hardware acceleration from settings?
> `chrome://settings/system`

I confirm, disabling hw acceleration it works perfectly.

**Comment by srirambv** [comment]
@bbondy @bridiver do we need to look into this more?

**Comment by bbondy** [comment]
Do you know if Chrome has the same problem for you if you have hardware acceleration on there?

**Comment by ntilotta** [comment]
> Do you know if Chrome has the same problem for you if you have hardware acceleration on there?
I don't have any problem with Chromium with hardware acceleration turned on, tested on the same machine using package from Ubuntu repository.

**Comment by ntilotta** [comment]
> Do you know if Chrome has the same problem for you if you have hardware acceleration on there?

I don't have any problem with Chromium with hardware acceleration turned on, tested on the same machine using package from Ubuntu repository.

**Comment by MNU-497** [comment]
I had the same problem and resolved it by turning off hardware acceleration. I did note that in Chrome I had hardware acceleration ON and had no issues in Chrome. Here is a system hardware info dump in case processor or video card info helps resolve cause.

Using windows system:
OS Name	Microsoft Windows 10 Home
Version	10.0.17134 Build 17134
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	*****************
System Manufacturer	Dell Inc.
System Model	OptiPlex 9010
System Type	x64-based PC
System SKU	
Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. A08, 9/19/2012
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Dell Inc.
PCR7 Configuration	Binding Not Possible
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17134.285"
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.96 GB
Available Physical Memory	3.89 GB
Total Virtual Memory	16.0 GB
Available Virtual Memory	10.1 GB
Page File Space	8.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected, Disabled by policy, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

Video Hardware:

Name	NVIDIA Quadro 2000
PNP Device ID	PCI\VEN_10DE&DEV_0DD8&SUBSYS_084A10DE&REV_A1\4&357F23CF&0&0008
Adapter Type	Quadro 2000, NVIDIA compatible
Adapter Description	NVIDIA Quadro 2000
Adapter RAM	1.00 GB (1,073,741,824 bytes)
Installed Drivers	nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvwgf2umx.dll
Driver Version	10.18.13.5362
INF File	oem150.inf (Section003 section)
Color Planes	Not Available
Color Table Entries	4294967296
Resolution	1920 x 1080 x 60 hertz
Bits/Pixel	32
Memory Address	0xF4000000-0xF5FFFFFF
Memory Address	0xE8000000-0xEFFFFFFF
Memory Address	0xF0000000-0xF3FFFFFF
I/O Port	0x0000E000-0x0000E07F
IRQ Channel	IRQ 4294967294
I/O Port	0x000003B0-0x000003BB
I/O Port	0x000003C0-0x000003DF
Memory Address	0xA0000-0xBFFFF
Driver	c:\windows\system32\drivers\nvlddmkm.sys (10.18.13.5362, 10.64 MB (11,151,720 bytes), 7/29/2015 11:50 PM)



Brave: Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)

**Comment by oshanz** [comment]
emojis are not colorful like other browsers.
https://emojipedia.org/people/

![image](https://user-images.githubusercontent.com/5364479/59245727-8b51e200-8c37-11e9-976f-77a6c4742e8b.png)

**Comment by bsclifton** [comment]
For folks experiencing this:
Can you please try going to chrome://flags/#force-color-profile and picking `sRGB`?

This should resolve the color differences. Not sure why the emojis aren't working for you, @oshanz (that seems like a different problem). Can you create a new issue with more of your details? Here's what that page looks like for me:
<img width="1038" alt="Screen Shot 2019-06-23 at 10 10 16 PM" src="https://user-images.githubusercontent.com/4733304/59993127-e30f2680-9603-11e9-9c11-b53137b95ee6.png">
