### ISSUE TITLE
ASAN test failures

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#17666]
- [x] https://github.com/brave/brave-browser/issues/19031
- [x] https://github.com/brave/internal/issues/831
- [x] https://github.com/brave/internal/issues/809
- [x] https://github.com/brave/internal/issues/808
- [x] https://github.com/brave/internal/issues/796
- [x] https://github.com/brave/internal/issues/797
- [x] https://github.com/brave/internal/issues/798
- [x] https://github.com/brave/internal/issues/806

**Comment by wknapik** [comment]
Should this be closed?

**Comment by iefremov** [comment]
indeed @wknapik
