### ISSUE TITLE
Update Wallet Panel UIs

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#17676]
## Description 
Update the `Confirm Transaction`, `Allow Spend` and `Sign Message` panels UI to introduce `Panel Tabs`

![Screen Shot 2021-08-24 at 4 47 45 PM](https://user-images.githubusercontent.com/40611140/130700145-89b9a2ff-2eeb-484e-bbcb-4be77b4df14e.png)

You can find the specs for this component in Figma / Desktop Crypto Wallets.

Add the component too storybook with mock data for testing.

## Expected result:

Component should be visible and functional in Storybook under the Wallet/Desktop/Concepts and Wallet/Desktop/Components tabs.

**Comment by pkopparla** [comment]
Cool stuff! Just wanted to point out a small typo on the right panel "beign" instead of "being".
