### ISSUE TITLE
Hookup balances of asset options in Buy/Swap tabs

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#17682]
<img width="284" alt="Screen Shot 2021-08-24 at 8 11 48 PM" src="https://user-images.githubusercontent.com/4730197/130720220-fc5a7d8e-d7c0-4672-993b-1b31f8dd091a.png">
<img width="284" alt="Screen Shot 2021-08-24 at 8 11 58 PM" src="https://user-images.githubusercontent.com/4730197/130720223-e9d33ce8-8be2-4eb0-a874-11e75637bbf8.png">

To use real balance in above tabs, we need to store wyre option list with balances for buy tab and swap option list with balances for swap tab.

**Comment by bbondy** [comment]
This was moved to Backlog because we're removing the balances for now to avoid a perf problem before MVP:
https://github.com/brave/brave-browser/issues/18418

**Comment by bbondy** [comment]
I think this is invalid since we don't have balances there anymore. Closing.
