### ISSUE TITLE
When Brave handles `microsoft-edge:` protocol searches use user's default search instead of Bing

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#17684]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/13875

Searching in the built in Windows Search will direct queries to Brave when the `microsoft-edge:` protocol handler is setup 👍 
![image](https://user-images.githubusercontent.com/4733304/130733815-8bf37b8c-dfae-468a-a9d9-751ba2fa0e3b.png)

However, it will always do a search using bing.com. We have the ability to intercept this and replace with the user's default search. For example, above search was resulting in this query:
https://www.bing.com/search?q=shoes&form=WNSGPH&qs=AS&cvid=d53e967be4de4c838b4d0acbdea846f6&pq=shoes&cc=US&setlang=en-US&nclid=D66578AD81C68AE27DB24A0A6978176D&ts=1629870667294&wsso=Moderate

## Steps to Reproduce

   1. Setup Brave as the protocol handler for `microsoft-edge:`
   2. Do a search (Press Windows key, type `shoes`)
   3. Click `See web results`

## Actual result:
Query opens in Brave but opens using Bing

## Expected result:
Query should open using the user's default search engine

**Comment by bsclifton** [comment]
Code to change would be in https://github.com/brave/brave-core/blob/master/browser/microsoft_edge_protocol_util.cc

We'd want to have some good unit test coverage when implemented 😄

**Comment by jonathansampson** [comment]
Great suggestion! We could probably drop most of those query-string values too (lang/regional parameters may be useful).

**Comment by bsclifton** [comment]
Good considerations here
https://www.ctrl.blog/entry/anti-competitive-browser-edges.html
> Brave is treading into dangerous and uncharted waters by rewriting the destination of a link. This resembles the “growth hacking” tactics employed by [mostly Russian] search portals and malware that was prevalent around 2010. These potentially unwanted applications (PUA; colloquially known as “crapware”) would redirect search links, replace or inject affiliate codes, and link to frame farms that would surround a page with extra ads.

Work on this issue hasn't been planned (yet) - but if we do want to pick it up, let's a privacy and security review before we start work

**Comment by Madis0** [comment]
Also, some Windows help links do open Bing instead of an article and the topmost "result card" shows the help material. Using any other search engine would not give that card and may give different results overall, therefore increase confusion.

**Comment by Nihal247** [comment]
> Also, some Windows help links do open Bing instead of an article and the topmost "result card" shows the help material. Using any other search engine would not give that card (and may give different results overall), therefore increasing confusion.
> 
Yes you're right here, when looking at certain results in Windows Search and different on Brave is something which'll create confusion. I would want to stick with Brave's current state.

**Comment by bsclifton** [comment]
Closing as Windows has patched `microsoft-edge` protocol in Windows 11, claiming apps being able to service this is a bug
