### ISSUE TITLE
Unable to search Vimeo Videos in incognito with Brave Shield Turn On

### ISSUE THREAD

**Issue by irrationalRock** [brave/brave-browser#1768]
## Description 

When searching the Vimeo site in incognito mode, Brave does not load. This problem does not happen in regular mode. 

## Steps to Reproduce

   1. Go to https://vimeo.com in incognito.
   2. Search what ever you want in the search bar and hit enter.
   3. The page doesn't load.

## Actual result:

The page is blank.

## Expected result:
The page should display search results.

## Reproduces how often: 

Easily Reproduced

## Brave version (brave://version info)

Brave | 0.56.5 Chromium: 70.0.3538.67 (Official Build) beta (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows
JavaScript | V8 7.0.276.28

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes.
- Is the issue reproducible on the latest version of Chrome? 
No.

**Comment by rebron** [comment]
This works with shields down.

**Comment by irrationalRock** [comment]
Yes, it work with shields down but it would be better if I didn't have to turn the shield on and off when I go to search for Vimeo videos.

**Comment by ryanbr** [comment]
@irrationalRock this should be fixed now, can you confirm?

**Comment by ryanbr** [comment]
Closing, re-tested. Any issues let us know @irrationalRock 

Search worked: https://vimeo.com/search?q=cats
Video played: https://vimeo.com/23608259
