### ISSUE TITLE
Remove W3Schools extension doesn't work

### ISSUE THREAD

**Issue by tallpants** [brave/brave-browser#1769]
## Description 
Remove W3Schools extension doesn't work. It's supposed to remove any W3schools links from Google search, but it seems to have no effect in Brave.

## Steps to Reproduce

   1. Install Remove W3Schools extension ([link](https://chrome.google.com/webstore/detail/remove-w3schools/gohnadkcefpdhblajddfnhapimpdjkje))
   2. Search for something like "JavaScript Date" on Google
   3. Notice results from W3Schools are still present.

## Actual result:
Results from W3Schools aren't removed.

## Expected result:
Results from W3Schools should be removed from the search results. This works fine in Chrome.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds: Yes
- Does it reproduce on browser-laptop: Unsure

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields: No 
- Is the issue reproducible on the latest version of Chrome: No

### Additional Information
Nope.

**Comment by akosipax** [comment]
I just installed [the extension](https://chrome.google.com/webstore/detail/remove-w3schools/gohnadkcefpdhblajddfnhapimpdjkje/related) and it seems to be working fine now.

**Comment by tallpants** [comment]
Works on the latest!
