### ISSUE TITLE
Add messaging in tipping flow to tell users that tips could take a few minutes to process

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17700]
## Description

Let users know that it's possible that their tips could take a few minutes to process.

## Solution

![image](https://user-images.githubusercontent.com/11497541/130881838-738e20c1-f4b2-4355-a66b-38594a264915.png)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.29.75 Chromium: 93.0.4577.58 (Official Build) (x86_64)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | macOS Version 10.15.7 (Build 19H1323)
```

<details>
<summary>Anon/UGP grant funded user wallet - PASSED</summary>

**`One Time`** | **`Monthly`**
---------------|------------------
<img width="1193" alt="ugp user wallet - DDG - 1time" src="https://user-images.githubusercontent.com/28145373/131366149-c06712a2-e8e3-4d58-abe9-1e6ea0c074f5.png"> | <img width="1197" alt="ugp user wallet - jumde - monthly" src="https://user-images.githubusercontent.com/28145373/131366155-5b323534-16f8-4c1c-bdbc-3648ddd6c680.png">

</details>

<details>
<summary>Gemini funded user wallet - PASSED</summary>

**`One Time`** | **`Monthly`**
---------------|------------------
<img width="1198" alt="gemini wallet - batcommunity - 1time" src="https://user-images.githubusercontent.com/28145373/131366278-0eadbe2e-cecc-4b03-8ee4-495ad5a85310.png"> | <img width="1196" alt="gemini wallet - laurenwagsGHio - monthly" src="https://user-images.githubusercontent.com/28145373/131366282-c71fec44-8b65-4ede-ab95-88061d6634a3.png">

</details>

<details>
<summary>bitFlyer funded user wallet - PASSED</summary>

**`One Time`** | **`Monthly`**
---------------|------------------
<img width="1190" alt="bF - dlipeles on GH - 1time" src="https://user-images.githubusercontent.com/28145373/131366331-d43b5213-7d57-4c1e-b7fd-20a0bc66d89f.png"> | <img width="1194" alt="bf - sampson on YT - monthly" src="https://user-images.githubusercontent.com/28145373/131366335-1e6a4529-d9a8-45cb-bd32-fe14f2c5a075.png">

</details>

<details>
<summary>Uphold funded user wallet - TBD</summary>

**`One Time`** | **`Monthly`**
---------------|------------------


</details>

Encountered https://github.com/brave/brave-browser/issues/17756 and https://github.com/brave/brave-browser/issues/17761.
