### ISSUE TITLE
Unable to unblock ads through ads history after 30 days

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#17713]
Follow up to https://github.com/brave/brave-browser/issues/17305
The blocked ads are blocked permanently after 30 days

Important: If user had ever blocked an ad pre 1.29.x, the block would be applied in 1.29.x. This way user can be surprised that ads are no longer shown.

## Steps to Reproduce

Test case 1:
1. Follow `Released notification ad after 30 days - Untargeted segment` from https://github.com/brave/internal/issues/794

Test case 2:
1. Follow `Released notification ad after 30 days after upgrade - Untargeted segment` from https://github.com/brave/internal/issues/794

## Actual result:

Unable to unblock ads through ads history
The blocked ads are blocked permanently

ads history is empty
![image](https://user-images.githubusercontent.com/34715963/131000596-b2ecbfee-fbe7-411a-b95a-882b49181e72.png)

## Expected result:
Able to unblock ads after 30 days

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.29.67 Chromium: 92.0.4515.159 (Official Build) beta (64-bit)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | Linux

cc @tmancey @jsecretan @moritzhaller @rebron @brave/legacy_qa

**Comment by tmancey** [comment]
@btlechowski @jsecretan this could be blocking inventory from being served to users. How about we automatically remove blocks after 90 days and users can just block again?

**Comment by jsecretan** [comment]
I don't think I'm ready to do that just yet.  And really inventory should cycle mostly in that time.  I'm willing to hold on this issue right now

**Comment by tmancey** [comment]
@jsecretan sure but unfortunately inventory cycling will not help as users are able to block categories and once blocked they can never unblock

**Comment by tmancey** [comment]
Closing issue as stale, however making @Miyayes aware for future consideration in new ongoing design changes
