### ISSUE TITLE
crash prompt dialog has both rounded and square corners - follow up to #1841

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#17722]
## Description 

Crash prompt was added with https://github.com/brave/brave-browser/issues/1841

On macOS Catalina this crash prompt dialog looks odd, it has both rounded and square corners:

<img width="1036" alt="Screen Shot 2021-08-27 at 8 24 02 AM" src="https://user-images.githubusercontent.com/28145373/131127773-ff7ae44c-296a-46a6-80a4-a903332a3f6e.png">

Looking at the verification notes under https://github.com/brave/brave-browser/issues/1841#issuecomment-891359676, the prompt looks ok with macOS 12.0, but Windows and Linux behave the same as Catalina having both rounded and squared corners on this prompt.

## Steps to Reproduce

Follow test plan for https://github.com/brave/brave-browser/issues/1841 or:

   1. Clean profile 1.29.x
   2. Open Guest window
   3. Go to brave://settings
   4. Click on Rewards at the top of the settings page
   5. Brave crashes (known issue, logged with https://github.com/brave/brave-browser/issues/15053)
   6. Relaunch Brave
   7. Get crash report prompt

## Actual result:

Light | Dark
----- | -----
<img width="1030" alt="Screen Shot 2021-08-27 at 8 41 11 AM" src="https://user-images.githubusercontent.com/28145373/131129143-c2114bb4-0f30-416e-b928-5cb26a724efe.png"> | <img width="1036" alt="Screen Shot 2021-08-27 at 8 24 02 AM" src="https://user-images.githubusercontent.com/28145373/131129146-81730a71-34f9-4e4d-be97-102051edec50.png">

## Expected result:

Rounded or squared corners on the prompt, not both

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.29.74 Chromium: 93.0.4577.58 (Official Build) (x86_64)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | macOS Version 10.15.7 (Build 19H1323)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.28.x n/a, but 1.29.x yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa @rebron @simonhong

**Comment by Michael82548** [comment]
Would be nice if this could be changed by a flag.
