### ISSUE TITLE
Enable Gemini

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#17742]
## Description 
Set `kGeminiFeature` to `base::FEATURE_ENABLED_BY_DEFAULT`

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.29.76 Chromium: 93.0.4577.58 (Official Build) (x86_64)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | macOS Version 10.15.7 (Build 19H1323)
```

<details>
<summary>Clean install - Production - PASSED</summary>

Confirmed on clean install that after enabling Rewards Gemini was an option for custodial wallet without enabling via flags.
Confirmed clicking on the Gemini option took me to their Production site.

Example | Example
----- | -----
<img width="1194" alt="Screen Shot 2021-08-31 at 7 29 39 AM" src="https://user-images.githubusercontent.com/28145373/131495694-04d37e88-db7e-4f3e-a0ab-e2c2517a2428.png"> | <img width="1196" alt="Screen Shot 2021-08-31 at 7 29 54 AM" src="https://user-images.githubusercontent.com/28145373/131495699-8433e5f6-ecf5-4897-8930-5c726d65de17.png">

</details>

<details>
<summary>Upgrade - Production - In Progress</summary>

Confirmed on upgrade that Gemini was an option for custodial wallet without enabling via flags.
Confirmed clicking on the Gemini option took me to their Production site.

Example | Example
----- | -----


</details>
