### ISSUE TITLE
Fill real contract addresses and decimals for assets available for buy

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#17741]
In that list https://github.com/brave/brave-core/blob/master/components/brave_wallet/browser/brave_wallet_constants.h#L28

**Comment by bbondy** [comment]
One thing to consider is ETH is not erc20 so maybe it makes sense to have a different similar type fort this.  Also on Wyre you can buy things like Bitcoin too.
I'm not very concerned about this though, so we can just leave this sit.
