### ISSUE TITLE
German translation is missing

### ISSUE THREAD

**Issue by bastele7** [brave/brave-browser#17749]
## Description 
- When right-clicking a page or open the menu, everything is translated to german except the marked items.

![Unbenannt1](https://user-images.githubusercontent.com/74867100/131223279-f5c39c09-58fd-4257-83d5-f6d71f651277.png)

![Unbenannt2](https://user-images.githubusercontent.com/74867100/131223280-128e4ca7-6e0f-4809-8fcf-fcf41ec3fdca.png)

## Brave version (brave://version info)
1.29.74 Chromium: 93.0.4577.58

**Comment by bastele7** [comment]
Solved in 1.29.76

**Comment by namangirdhar16** [comment]
Is this issue still open, if yes can i work on this?
