### ISSUE TITLE
remove message warning users about tips taking several minutes when setting up monthly contribution

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#17756]
## Description 

We should remove the `Note: Your tip can take several minutes to process` message when users set up monthly contributions. We're currently displaying it in all instances. It should only be displayed when an actual tip occurs. Originally implemented via https://github.com/brave/brave-core/pull/9873.

## Steps to Reproduce

   1. launch Brave and enable rewards either via `brave://rewards` or the rewards panel
   2. once enabled, setup a monthly contribution and you'll notice the `your tip might take a few minutes` is being displayed

## Actual result:

![monthlyContribution](https://user-images.githubusercontent.com/2602313/131267567-1af0b9e8-91f8-49bc-a3f9-9301f3788415.png)

## Expected result:

We shouldn't be displaying the `Note: Your tip can take several minutes to process` message when a user sets up a monthly contribution.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.31.5 Chromium: 93.0.4577.58 (Official Build) nightly (64-bit)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | Windows 10 OS Version 2009 (Build 19042.1165)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No` (but it will once `1.29.x` gets released)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @Miyayes @jumde @LaurenWags @rebron @bsclifton

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.31.29 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 10.15.7 (Build 19H1323)
```

Verified STR from description. Confirmed message does not display on the monthly tip banner success screen:

<img width="1193" alt="DDG" src="https://user-images.githubusercontent.com/28145373/132706587-3485fe3f-38b8-45e1-bd47-2b69cce986e6.png">
