### ISSUE TITLE
Brave doesn't find a specific font I've installed

### ISSUE THREAD

**Issue by waldyrious** [brave/brave-browser#17753]
## Description 

I have installed the [Libertinus](https://github.com/alerque/libertinus) font family as my preferred serif font, but Brave doesn't seem to be able to detect it in the list of available fonts.

I am on Ubuntu 20.04, and installed the font with:

```
nix-env -iA nixpkgs.libertinus
```

Then made it available to fontconfig by:

```console
$ mkdir -p ~/.config/fontconfig/conf.d/
$ cat << EOF > ~/.config/fontconfig/conf.d/10-nix-fonts.conf
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <dir>~/.nix-profile/share/fonts/</dir>
</fontconfig>
EOF
``` 

Some programs (e.g. Firefox, Gnome Font Viewer, the LibreOffice programs...) appear to be able to detect this font, while others can't (Brave, Inkscape, GIMP).

| Firefox can find the font | Brave can't find the font |
|-|-|
| ![Screenshot from 2021-08-29 14-19-54](https://user-images.githubusercontent.com/478237/131252400-6d642636-ac9d-4ec8-841d-0b246ef5a6a3.png) | ![Screenshot from 2021-08-29 14-22-16](https://user-images.githubusercontent.com/478237/131252402-f872c99b-12ac-4acb-92b2-33f6a7fd3873.png) |

`fc-list` does report it as available:

```console
$ fc-list | grep -i libertinus
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSerif-SemiboldItalic.otf: Libertinus Serif,Libertinus Serif Semibold:style=Semibold Italic,Italic
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSerifDisplay-Regular.otf: Libertinus Serif Display:style=Regular
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSerif-Bold.otf: Libertinus Serif:style=Bold
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSerif-BoldItalic.otf: Libertinus Serif:style=Bold Italic
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSerif-Regular.otf: Libertinus Serif:style=Regular
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusMath-Regular.otf: Libertinus Math:style=Regular
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSerifInitials-Regular.otf: Libertinus Serif Initials:style=Regular
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSans-Italic.otf: Libertinus Sans:style=Italic
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSans-Bold.otf: Libertinus Sans:style=Bold
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSans-Regular.otf: Libertinus Sans:style=Regular
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusKeyboard-Regular.otf: Libertinus Keyboard:style=Regular
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSerif-Semibold.otf: Libertinus Serif,Libertinus Serif Semibold:style=Semibold,Regular
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusMono-Regular.otf: Libertinus Mono:style=Regular
/home/waldyrious/.nix-profile/share/fonts/opentype/LibertinusSerif-Italic.otf: Libertinus Serif:style=Italic
```

## Steps to Reproduce

   1. Install Libertinus as described above
   2. Go to Brave settings
   3. Try to select Libertinus as the default font

## Actual result:

The font does not appear in the list

## Expected result:
The font should appear in the list of available fonts to choose from.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | Linux

(Brave was installed as a Snap)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by waldyrious** [comment]
@bsclifton thanks for closing this — I can confirm this issue no longer occurs. Can I assume the fix was https://github.com/brave/brave-browser-snap/pull/25?

**Comment by bsclifton** [comment]
@waldyrious yup! that should have been it
