### ISSUE TITLE
Apply our corner radius on all dialogs

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#17758]

**Comment by rebron** [comment]
Follow up to: #17722

**Comment by Michael82548** [comment]
Would be nice if this could be changed with a flag.

**Comment by nullhook** [comment]
```c++
WebUIBubbleManagerT<VPNPanelUI>
```

`WebUIBubbleManagerT`
creates a WebUIBubbleDialogView (views::BubbleDialogDelegateView) which basically is a view and sets a border `border->SetCornerRadius(GetCornerRadius());`

`GetCornerRadius` is a function that detects OS and applies platform specific corner radius

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/32150 and fixed with https://github.com/brave/brave-core/pull/19795 in 1.59.x
