### ISSUE TITLE
Recent update of Brave bricked my 1Password extension from working

### ISSUE THREAD

**Issue by posita** [brave/brave-browser#17751]
## Steps to Reproduce

   1. Install [1Password](https://1password.com/downloads/)
   2. Install the ["classic" 1Password extension](https://support.1password.com/cs/1password-classic-extension/) for Brave (redirects [here](https://chrome.google.com/webstore/detail/1password-extension-deskt/aomjjhallfgjeglblehebfpbcfeobpgk))
   3. Note the warning 1Password presents:

## Actual result:

<img width="532" alt="Screen Shot 2021-08-28 at 15 25 26" src="https://user-images.githubusercontent.com/222581/131230391-b974c1c6-bc0f-4ac9-b6ea-af249384fb9d.png">

## Expected result:

This was working immediately prior to upgrading to the latest version and was working through many Brave updates.

## Reproduces how often: 

Since upgrading, every time, including after trying to uninstall and reinstall the extension.

## Brave version (brave://version info)

Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)

**Comment by posita** [comment]
Note that blowing away `/Applications/Brave.app` and then downloading and reinstalling from the latest version resolved the issue, so I'm not sure what about/how the update process broke things….

**Comment by rebron** [comment]
Closing as stale. Wasn't reproducible and no other reports.
