### ISSUE TITLE
Weak fingerprinting protection

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#17755]
So i was trying different browsers fingerprint protection methods on a powerful test that utilizes latest java script features, this test uses powerful methods that even firefox based browsers have a really rough time to evade them and most of the times fail, yet i wanted to check how chromium based browsers perform in this test and the results were as expected, terrible, all privacy focused chromium browsers (including bromite and ungoogled chromium) have miserably failed to cover even the most basic information about device like gpu model, cpu cores, ram or device model (in android), the worst among all was brave, being completely predictable, i suggest to use this test for fingerprinting protection from now and add mitigations to this leaks as your p1 since the main reason of using brave is to protect fingerprinting otherwise if someone wanted to just block ads and trackers there would a lot of other methods.
Test : https://abrahamjuliot.github.io/creepjs/
Project : https://github.com/abrahamjuliot/creepjs
As mentioned in the project's description it's been made to show weaknesses in fingerprinting protection methods.

**Comment by evoyy** [comment]
I made a post about this a few months ago:

https://community.brave.com/t/braves-anti-fingerprinting-technology-is-flawed/239884

My conclusion is that the 3rd party bot protection services are now so advanced that it is impossible to prevent fingerpinting. My opinion is that this ultimately a waste of resources, because it is a battle that can't be won.

**Comment by pes10k** [comment]
Closing this out, im not sure i understand the claim being made. Doing the test, i see the test reporting brave the least fingerprintable (fingerprint trust == 0%), compared with Chrome and Firefox (both fingerprint trust = 100%).

I also see the test noting the randomization Brave injects into high entropy fingerprinting vectors (Canvas, WebAudio) and medium entropy fingerprinting vectors (deviceMemory, hardwareConcurrency, plugins), and so not using those as inputs to the fingerprint (good).

I also see the test not accounting for additional randomization brave injects into the fingerprint, and so consuming those poison pill data points (even better).

Anyway, all that is to say that the link to test shows Brave is providing extremely strong protections
