### ISSUE TITLE
vineyardvines.com hard refresh required for page views

### ISSUE THREAD

**Issue by cwmke** [brave/brave-browser#17754]
## Description 
A family member likes to shop at vineyardvines.com on her Mac laptop. The initial website loads but after clicking a menu item she is left with a blank white page. When troubleshooting, it appears a hard refresh then loads the selected page but this is required for each subsequent new page.

## Steps to Reproduce

   1. Go to vineyardvines.com
   2. Click any of the menu options such as "New," "Men," "Women," etc.
   3. Page loads with a blank white screen.

## Actual result:
Blank page

## Expected result:
The page to fully load and display its contents.

## Reproduces how often: 
Everytime. I have tested on Mac and Linux computers.

## Brave version (brave://version info)

Brave | 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | Linux

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome?
Not sure but wasn't reproducible in Safari or Firefox.

**Comment by ryanbr** [comment]
Thanks for the report @cwmke fix is incoming, give it 24-48hrs. I'll leave this open if you can test the site is working.

**Comment by cwmke** [comment]
Working great. Really impressed with the fast turnaround on this. Thanks!
