### ISSUE TITLE
Pending tips for Gemini creators not sent when switching from Uphold to Gemini

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#17766]
## Description 

If a user changes their custodial wallet from Uphold to Gemini, pending tips that were earmarked for a Gemini creator are not being sent out once the change to Gemini is made.

## Steps to Reproduce

   1. Have a profile w/ Uphold KYC'd user wallet
   2. Tip a Gemini verified creator
   3. Confirm the tip goes to the pending tips list
   4. Disconnect from Uphold and connect KYC'd Gemini wallet

## Actual result:

Pending tip is not sent to the Gemini creator, it remains in the pending list. I tried the following per suggestions to get this to happen:
- refreshing the publisher list (manually from panel)
- advancing computer clock 1 day 
- advancing computer clock 3 days

<img width="945" alt="Screen Shot 2021-08-30 at 12 42 03 PM" src="https://user-images.githubusercontent.com/28145373/131381643-4ffac67b-7c32-4205-954b-833bbe4fea2c.png">

## Expected result:

At some point the pending tip for Gemini creator should be sent out

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.29.75

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.28.x n/a, 1.29.x yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the nightly channel? 1.31.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa @Miyayes @jumde @rebron

**Comment by stephendonner** [comment]
Verified using

Brave | 1.32.86 Chromium: 95.0.4638.54 (Official Build) beta (64-bit)
--|--
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Windows 10 Version 20H2 (Build 19042.1288)

<details>
<summary>Clean Profile - PASSED</summary>

Per https://github.com/brave/brave-core/pull/10324#issue-1011506941, confirmed database migration (v1 -> v33) is successful.
Also confirmed there's no `processor` column in the `pending_contribution` table.

Example | Example
----- | -----
![clean-profile-db](https://user-images.githubusercontent.com/387249/139598314-5630dc83-f07d-4db5-b410-ffe09f7c11de.png) | ![upgrade-04](https://user-images.githubusercontent.com/387249/139598331-ac5d11bd-74dc-4c4d-91c7-76347f6b4421.png)



</details>

<details>
<summary>Upgrade Profile - PASSED</summary>

Installed 1.31.87 and enabled Rewards.
Confirmed DB version is 32 and there is a `processor` column in the `pending_contribution` table.

Example | Example
----- | -----
![upgrade-01](https://user-images.githubusercontent.com/387249/139598403-7d5587ea-425a-4fd9-af33-5109de35bdcc.png) | ![upgrade-02](https://user-images.githubusercontent.com/387249/139598405-32cb88c2-741e-44af-8199-d5cd6abaef4a.png)


Upgraded to 1.32.81 by renaming the profile. 
Per https://github.com/brave/brave-core/pull/10324#issue-1011506941, confirmed database migration (v32 -> v33) is successful. (note, DB migration in logs shows 33->33. Discussed this with Szilard and he confirmed that previous migrations also showed this way in the logs)
Also confirmed there's no `processor` column in the `pending_contribution` table.

Example | Example
----- | -----
![upgrade-03](https://user-images.githubusercontent.com/387249/139598385-50f9d623-69b6-4fe5-81f6-74b1baf02285.png) | ![upgrade-04](https://user-images.githubusercontent.com/387249/139598411-afb330b4-330f-476c-acb5-7d501d39b77d.png)



</details>

<details>
<summary> Uphold --> Gemini wallet change - PASSED</summary>

Verified test plan from https://github.com/brave/brave-core/pull/10324#issue-746187970

Confirmed when tipping a Gemini verified creator from an Uphold User wallet (step 3), the tip is sent to pending list:

Example | Example
----- | -----


Confirmed able to disconnect from Uphold and connect Gemini account per step 4:


Advanced computer clock by 3 days as per step 5. On relaunch, I got this message from the panel:


I checked the logs and saw that the tip was now being initiated.

<details>
<summary>Step 6 logs</summary>

```
.
```

```
.
```

```
.
```

```
.
```

```
.
```

```
.
```

</details>

Confirmed the tip and fee were sent successfully

Example | Example | Example
----- | ----- | -----



</details>



<details>
<summary> Gemini --> Uphold wallet change - PASSED</summary>

Verified test plan from https://github.com/brave/brave-core/pull/10324#issue-746187970

Confirmed when tipping a Gemini verified creator from an Uphold User wallet (step 3), the tip is sent to pending list:

Example | Example
----- | -----


Confirmed able to disconnect from Uphold and connect Gemini account per step 4:


Advanced computer clock by 3 days as per step 5. On relaunch, I got this message from the panel:


I checked the logs and saw that the tip was now being initiated.

<details>
<summary>Step 6 logs</summary>

```
CREATING CONTRIBUTION...
....
.
...........
.
```

</details>

Confirmed the tip and fee were sent successfully

Example | Example | Example
----- | ----- | -----


</details>

**Comment by stephendonner** [comment]
Verified `in-progress` using 

<details>
<summary>Clean Profile - PASSED</summary>

Per https://github.com/brave/brave-core/pull/10324#issue-1011506941, confirmed database migration (v1 -> v33) is successful.
Also confirmed there's no `processor` column in the `pending_contribution` table.

Example | Example
----- | -----
<img width="1653" alt="Screen Shot 2021-11-10 at 11 16 48 AM" src="https://user-images.githubusercontent.com/387249/141181166-c8bd28f9-bef2-4302-8500-414a406db429.png"> | <img width="1653" alt="Screen Shot 2021-11-10 at 11 23 43 AM" src="https://user-images.githubusercontent.com/387249/141181215-398adaf2-b68f-4e11-8944-dc9fd40a1e8a.png">

</details>

<details>
<summary>Upgrade Profile - PASSED</summary>

Installed 1.31.87 and enabled Rewards.
Confirmed DB version is 32 and there is a `processor` column in the `pending_contribution` table.

Example | Example
----- | -----
<img width="1653" alt="Screen Shot 2021-11-10 at 11 28 39 AM" src="https://user-images.githubusercontent.com/387249/141181315-e91eb329-3f55-4434-84a2-0fbba4fd7ac4.png"> | <img width="1653" alt="Screen Shot 2021-11-10 at 11 29 48 AM" src="https://user-images.githubusercontent.com/387249/141181330-d484ca1f-9740-4667-bc11-32923be15b72.png">


Upgraded to 1.32.81 by renaming the profile. 
Per https://github.com/brave/brave-core/pull/10324#issue-1011506941, confirmed database migration (v32 -> v33) is successful. (note, DB migration in logs shows 33->33. Discussed this with Szilard and he confirmed that previous migrations also showed this way in the logs)
Also confirmed there's no `processor` column in the `pending_contribution` table.

Example | Example
----- | -----
<img width="1653" alt="Screen Shot 2021-11-10 at 11 31 53 AM" src="https://user-images.githubusercontent.com/387249/141181405-2be6d1e3-6add-4fb7-837f-ae73a45a77db.png"> | <img width="1653" alt="Screen Shot 2021-11-10 at 11 32 33 AM" src="https://user-images.githubusercontent.com/387249/141181415-69bb378d-62c1-4f7a-9e0a-28f234a25bce.png">




</details>
