### ISSUE TITLE
[Android] Send tip button shrinks when grant notification is closed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17776]
## Description 
Send tip button shrinks when grant notification is closed

## Steps to reproduce 

   1. Enable rewards and visit a publisher site
   2. Open panel to trigger grant check (use staging to get UGP grant)
   3. Send tip button is fully stretched 
   4. Close the grant notification, observe the tip button shrinks 

## Actual result 

With grant | Without grant
-- | --
![image](https://user-images.githubusercontent.com/17010094/131442125-7b234762-f71c-4ff7-a6ee-4f1153695d30.png) | ![image](https://user-images.githubusercontent.com/17010094/131442140-b5847ae3-a314-4e49-b0ad-0b8d9896d90d.png)

## Expected result
Consistent UI for buttons

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya

**Comment by Miyayes** [comment]
Superseded by new panel in 1.35.
