### ISSUE TITLE
"Tip" icon location is shifted in Github Discussions

### ISSUE THREAD

**Issue by Songyu-Wang** [brave/brave-browser#17771]
## Description 

![Screenshot from 2021-08-30 16-29-29](https://user-images.githubusercontent.com/36670132/131418655-7355c38a-0894-4476-a044-35aae3a2f730.png)
The tip icon location is not correct

## Steps to Reproduce

   1.  Create a discussion in a GitHub repo
   2.  Check the tip icon on the page
   3. 

## Actual result:

See description

## Expected result:
Everything should be in one line 
![Screenshot from 2021-08-30 16-32-52](https://user-images.githubusercontent.com/36670132/131418876-10a33c21-c422-49f5-833e-f9ab65d2b20d.png)
Using PR page as an example

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
Did not check

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by rebron** [comment]
Closing as invalid. Tip buttons were removed in 1.62.x with https://github.com/brave/brave-browser/issues/33783
