### ISSUE TITLE
[Suggestion] If the user clicks "Block" on the crash report dialogue after a crash, it should not appear again.

### ISSUE THREAD

**Issue by Michael82548** [brave/brave-browser#17772]
I am running Version 1.29.71 Chromium: 92.0.4515.159 (Official Build) beta (64-bit)
and Version 1.31.7 Chromium: 93.0.4577.58 (Official Build) nightly (64-bit)

**This appears to affect only Beta and Nightly users and most likely other users that are not using stable**

This dialogue box never even appeared for me until a couple weeks ago (probably introduced in an update).

Steps to reproduce:
1. Make sure the browser has "Help improve Brave's features and performance" toggled off in settings, restart if necessary.
2. Crash the browser in an "unexpected" way "brave://inducebrowsercrashforrealz"
3. Relaunch the browser
4. You should now see the menu popup. This keeps happening every time until you opt-in to crash reports.
![image](https://user-images.githubusercontent.com/53535277/131420802-4831bd06-2e63-4930-bef3-d04890e84b5c.png)

Expected result:
Once the user clicks "block", the dialogue box should never appear again unless the user has turned on crash reporting and then off again, resetting the cycle, or just never showing the dialogue box ever again after the user clicks "block".
Normally I would see this box and I would like to keep it that way. Especially when I opt-out to crash reports, since it's mostly my computer crashing and not the browser itself.
![image](https://user-images.githubusercontent.com/53535277/131420732-f8830f9b-005f-48cf-9020-575b41a65994.png)

Closing words:
Brave Browser is a Chromium browser that boasts security, and respecting user privacy. If this is the case, then respect us when we click "block" after asking us to opt-in to crash reports, and never ask again.

**Comment by Tonev** [comment]
@simonhong 

Did I understand correctly that the crash report dialog will be available only in the `Stable` builds soon?

https://github.com/brave/brave-browser/issues/17378

If so, can we get an option to disable the dialog in `Stable` builds? Right now, users are forced to either report crashes silently or see the dialog every time a crash happens.

Feedback from `Brave Community`: https://community.brave.com/t/browser-keeps-asking-if-i-want-to-send-a-crash-report-when-i-have-it-turned-off/278956

**Comment by simonhong** [comment]
> Did I understand correctly that the crash report dialog will be available only in the Stable builds soon?

We enabled this dialog on all channel (nightly, beta and stable)

@rebron some users want to have something like `don't ask again` checkbox or prevent this this when `Block` is clicked. WDYT?

**Comment by Tonev** [comment]
Yes, I know it's currently available in all channels. Does the following issue mean that it will be available only in `Beta` and `Nightly` soon? https://github.com/brave/brave-browser/issues/17378

**Comment by simonhong** [comment]
> Yes, I know it's currently available in all channels. Does the following issue mean that it will be available only in Stable soon?

No, non-official means  local dev build. All release channels are `official`.

**Comment by Tonev** [comment]
Ah, got you. Thank you for the clarification, @simonhong, highly appreciate your quick replies!

**Comment by simonhong** [comment]
> Ah, got you. Thank you for the clarification, @simonhong, highly appreciate your quick replies!

Feedback always welcome. Thanks! :)

**Comment by bsclifton** [comment]
Assigned to @rebron for next steps - thanks for reporting 😄

**Comment by dstathis** [comment]
This also bothers me a lot. I restart my computer with the browser open all the time which it thinks is a crash.

I am on the stable snap.

**Comment by coreshift** [comment]
> This also bothers me a lot. I restart my computer with the browser open all the time which it thinks is a crash.
> 
> I am on the stable snap.

Same. I also hate the restore session popup. Can we get an option to disable that as well? Or just let me check a box to recover the session after a crash or not. Why even ask each time?

**Comment by rebron** [comment]
Duping out to #18103 to clean up this issue bit via template.

**Comment by Michael82548** [comment]
> > This also bothers me a lot. I restart my computer with the browser open all the time which it thinks is a crash.
> > I am on the stable snap.
> 
> Same. I also hate the restore session popup. Can we get an option to disable that as well? Or just let me check a box to try and restore the session after a crash or not. Why even ask each time?

**I would still like an option to keep that specific dialogue box enabled and not to remove it entirely.** A useful tip is to press "CTRL + SHIFT + T" for the same thing to happen and to restore any windows/tabs that were last closed in a non-incognito session (Although an optional toggle to enable this functionality in incognito would be AWESOME).

**Comment by Michael82548** [comment]
> @simonhong
> 
> Did I understand correctly that the crash report dialog will be available only in the `Stable` builds soon?
> 
> #17378
> 
> If so, can we get an option to disable the dialog in `Stable` builds? Right now, users are forced to either report crashes silently or see the dialog every time a crash happens.
> 
> Feedback from `Brave Community`: https://community.brave.com/t/browser-keeps-asking-if-i-want-to-send-a-crash-report-when-i-have-it-turned-off/278956

We should be able to have that option to manually turn off those prompts on non-stable as well. If you are a developer testing things and the browser keeps crashing and you manually opt-out of sending crash reports because you know what you are doing, it would be very annoying to keep clicking "block" every time the browser crashes.
