### ISSUE TITLE
On restart panel shows wallet summary

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1777]
## Description 

On restart panel shows wallet summary until you do some interaction  (switch tab, reload site, visit a site)

## Steps to Reproduce

   1. clean profile
   2. enable rewards
   3. visit a site
   4. make sure that publisher is displayed in the panel
   5. restart browser
   6. open panel

## Actual result:

Wallet summary is shown

## Expected result:
Publisher of the current site should be displayed

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows
