### ISSUE TITLE
Verify wallet not linking with Uphold

### ISSUE THREAD

**Issue by neroxyr** [brave/brave-browser#17789]
## Description 
The wallet is not verified when clicked and following the steps to verify the wallet

## Steps to Reproduce
   1. Verify Wallet
   2. Continue
   3. Uphold
   4. Continue to login 
   5. Authorize
 

## Actual result:
The wallet is not verified

## Expected result:
The wallet to be verified

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.29.76 Chromium: 93.0.4577.58 (Official Build) (64-bit)
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

## Version/Channel Information:
Stable

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? don't know
- Can you reproduce this issue with the nightly channel? don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by thefallofbecause** [comment]
Try signing into Uphold in another tab before going through the verification process. There is a known session cookie issue with Uphold at the moment that causes a loop like this.

**Comment by neroxyr** [comment]
Thanks, logged out and signed in again in another tab but still can't verify my wallet.

**Comment by thefallofbecause** [comment]
That usually works for most people, but you could also try disabling shields on Uphold.

**Comment by Miyayes** [comment]
Does it give you any error messages after you try? Check in the BAT dropdown panel as well (click BAT icon in the URL bar). Thanks.

**Comment by neroxyr** [comment]
> Does it give you any error messages after you try? Check in the BAT dropdown panel as well (click BAT icon in the URL bar). Thanks.

this message appears
"Device Limit Reached |Your wallet cannot be verified because you've reached the maximum verified device limit. 9/6/2021"

I've previously had this verified

**Comment by bsclifton** [comment]
@brave/rewards-support

**Comment by Miyayes** [comment]
@neroxyr If you can send me your brave://rewards-internals (general info tab copy-paste) of one of your previously linked desktop browsers, that would be great. You can send it by email to christopher@brave.com.

**Comment by neroxyr** [comment]
Tha

> @neroxyr If you can send me your brave://rewards-internals (general info tab copy-paste) of one of your previously linked desktop browsers, that would be great. You can send it by email to [christopher@brave.com](mailto:christopher@brave.com).

Thanks, just emailed it to you.

**Comment by MuffyOne** [comment]
> @neroxyr If you can send me your brave://rewards-internals (general info tab copy-paste) of one of your previously linked desktop browsers, that would be great. You can send it by email to [christopher@brave.com](mailto:christopher@brave.com).

Hi, I'm having the same exact issue, I have a windows computer and a mac mini linked and when I try to verify my Android phone I get back "Device Limit Reached |Your wallet cannot be verified because you've reached the maximum verified device limit.".

**Comment by neroxyr** [comment]
Still no solution for this issue.

**Comment by neroxyr** [comment]
> > @MuffyOne  Hi, I'm having the same exact issue, I have a windows computer and a mac mini linked and when I try to verify my Android phone I get back "Device Limit Reached |Your wallet cannot be verified because you've reached the maximum verified device limit.".
The issue is still present, emailed them but no response so far.
