### ISSUE TITLE
Brave shield unable to block google ads when shields=standard 

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#17785]
Now 4 ads on google in shields=standard mode. Brave default shield settings should block these ads or Make aggressive mode as default. 
Its against brave claim like Brave Block ads and trackers. https://brave.com
https://github.com/brave/brave-browser/issues/15106

![2021-08-31 07%3a44%3a46 050152161](https://user-images.githubusercontent.com/46480489/131550522-a0541b97-e2a5-401c-b672-ad91e5be7a2c.gif)

**Comment by rebron** [comment]
Closing as stale. 
<img width="1019" alt="Screenshot 2024-02-08 at 9 56 40 PM" src="https://github.com/brave/brave-browser/assets/5951041/6398aa74-ed06-46d7-a420-f5a558e84432">
<img width="1411" alt="Screenshot 2024-02-08 at 9 56 27 PM" src="https://github.com/brave/brave-browser/assets/5951041/8db04bf0-7553-404f-bb97-920c4c8f7842">
