### ISSUE TITLE
Remove vestiges of "memories" in brave://flags

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17782]
## Description 

Remove the last vestiges of "memories" in `brave://flags`

This is a followup to https://github.com/brave/brave-browser/issues/15582

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `brave://flags`
   4. type `"memories"`

## Actual result:

<img width="1312" alt="Screen Shot 2021-08-31 at 9 20 13 AM" src="https://user-images.githubusercontent.com/387249/131539928-bfa80192-bfe4-4fe5-98f6-3e446487d0e8.png">

## Expected result:
Nothing listed/found

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.31.10 Chromium: 93.0.4577.58 (Official Build) nightly (x86_64)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | macOS Version 11.5.2 (Build 20G95)

/cc @goodov

**Comment by rebron** [comment]
Closing as stale. Flags look like they've been removed.

<img width="879" alt="Screenshot 2024-02-08 at 10 01 17 PM" src="https://github.com/brave/brave-browser/assets/5951041/102a0090-c320-4ceb-ace4-8574da7b9485">
