### ISSUE TITLE
Implement wallet state notifications for Android

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17780]
## Description 
As part of #15390, new notifications are implemented for various wallet connection state (Pending/Blocked/Restricted/BAT not available/Linking Limit). These notifications don't show up on Android and needs to be implemented to have parity between desktop and Android

## Steps to reproduce 

Follow test plan from https://github.com/brave/brave-core/pull/9212

## Actual result 
No notifications shown on Android

## Expected result
Show notifications on Android similar to desktop 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version: 11
   
## Brave version
1.29.x onward

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Miyayes @deeppandya @szilardszaloki

**Comment by Miyayes** [comment]
Is this automatically resolved via https://github.com/brave/brave-browser/issues/20175?

**Comment by Miyayes** [comment]
@srirambv I think all of these error modals are gotten for free, since we do verifying/linking flow via brave://rewards settings page, and all the error modals are now inherited for free from desktop. (You can see in various Rewards testing of v1.35.)
