### ISSUE TITLE
New Tab Page backgrounds are over-compressed

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#1779]
For the New Tab Page wallpapers, compression artifacts are relatively visible, especially on high DPI displays.

Ideally, these would be reduced.

**Comment by petemill** [comment]
Also mentioned in https://github.com/brave/brave-browser/issues/1361#issuecomment-431854354

**Comment by drcongo** [comment]
Is there any way to turn these off completely? They really cheapen the experience.
