### ISSUE TITLE
The default search engines that come by default in Brave are not what they should be.

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#17801]
All the things that I am showing come default in Brave when they should be somewhat different.

> In the URL of **Google** in `brave://settings/searchEngines` ,It is some URL which is very long but It doesn't need to be there.
> `{google:baseURL}search?q=%s&{google:RLZ}{google:originalQueryForSuggestion}{google:assistedQueryStats}{google:searchFieldtrialParameter}{google:iOSSearchLanguage}{google:prefetchSource}{google:searchClient}{google:sourceId}{google:contextualSearchVersion}ie={inputEncoding}`
> ,Instead in google search engine **URL there should be this**.
> `https://www.google.com/search?q=%s`
> Why such a **long URL** when there is no need for that and **it doesn't do anything special than the simple URL**.

> The same way it is in **duckduckgo**, In duckduckgo, It goes more far **by telling duckduckgo the browser name.**
> `https://duckduckgo.com/?q=%s&t=brave`
> Why is it supposed to do that when It can do it simply by using this URL and without using t=brave because **it doesn't need to tell duckduckgo that This search came from Brave Browser**.
> `https://duckduckgo.com/?q=%s&t=h_&ia=web`

> In the same way it goes with Brave Search also In the url it is **telling Brave search that the source of the search is desktop**.
> `https://search.brave.com/search?q=%s&source=desktop`
> Why does it needs to do this and **tell Brave search that the search came from desktop when It can do it without showing that the search came from desktop and by simply removing`&source=desktop`**.
> `https://search.brave.com/search?q=%s`

**Comment by rebron** [comment]
Closing as invalid. You don't have to use a search engine from the default search engines list. Feel free to add another search engine or simpler versions of the ones you want to see in the Other search engines section.

**Comment by clicky6** [comment]
> Closing as invalid. You don't have to use a search engine from the default search engines list. Feel free to add another search engine or simpler versions of the ones you want to see in the Other search engines section.

But for a normal user he would only use the default ones and will not change it and as I said that the default ones share browser user agent and name of browser, version etc. so the browser user agent, browser name and version is being shared and is against what Brave says they are protecting against tracking and fingerprinting so implementing something like this would make these things more privacy-respecting.
