### ISSUE TITLE
Update Main Wallet Panel UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#17814]
## Description 
1) Change `Connected` icon to a bigger `CheckMark` with out a circle.
2) Remove the  <- -> switch icon bellow the `account circle` and address.
3) Make the `account circle` clickable to switch between accounts.
4) Add a `chevron` icon to the `account circle`
5) Change the `Apps` tab icon to a `star` icon

Current UI:

![Screen Shot 2021-09-01 at 3 53 36 PM](https://user-images.githubusercontent.com/40611140/131750391-9307ba07-6f60-4907-ad95-09b062d62031.png)

Expected Result:

![Screen Shot 2021-09-01 at 3 48 11 PM](https://user-images.githubusercontent.com/40611140/131749828-b200855a-aac5-40dc-ba0d-daeca956f62d.png)

**Comment by NhlanhlaHasane** [comment]
Hey @Douglashdaniel I noticed that description 2 isn't removed from the expected results.

**Comment by Douglashdaniel** [comment]
> Hey @Douglashdaniel I noticed that description 2 <---> isn't removed from the expected results.

Hey @NhlanhlaHasane it's referring to this icon!

![Screen Shot 2021-09-02 at 9 12 03 AM](https://user-images.githubusercontent.com/40611140/131869832-22a416ec-d4d9-4148-966d-682ef369e8a0.png)

Update my comment to be more clear! Thank you! 😊
