### ISSUE TITLE
Brave hanging for a few seconds on version 1.29.76 on both Linux and Windows 10

### ISSUE THREAD

**Issue by NOOBNOOBOX** [brave/brave-browser#17811]
## Description 
When typing something in the search bar it hangs or crashes for few seconds then starts typing normally. This has happened to both my Linux and Windows 10.
Note - Tried disabling hardware acceleration, Issue still persists.

## Brave version (brave://version info)
Brave version  - 1.29.76 
Chromium version - 93.0.4577.58

**Comment by NOOBNOOBOX** [comment]
Yes I have been using the Brave Browser for a while and the problem started after recent update.  I do not use VPN or any extensions. Brave rewards is disabled. other chromium based browsers are also installed but this issue does not seem to be there.

**Comment by rebron** [comment]
@NOOBNOOBOX We just released 1.30.86. Can you update to that version and let us know if you're still running into issues.

**Comment by NOOBNOOBOX** [comment]
> @NOOBNOOBOX We just released 1.30.86. Can you update to that version and let us know if you're still running into issues.

Hello I have updated to the latest version and used it quite a while. The issue came only once after that iam not experiencing.
