### ISSUE TITLE
Cert invalid error when visiting *.eth.link

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#17815]
## Description 

https://github.com/brave/brave-core/pull/9375 adds eth.link into public suffix list and we will have cert invalid error when visiting *.eth.link.

## Steps to Reproduce

   1. Visit https://swapr.eth.link/

## Actual result:
<img width="1136" alt="Screen Shot 2021-09-01 at 3 49 20 PM" src="https://user-images.githubusercontent.com/4730197/131755478-17fb7dee-d637-49df-ad03-ec9dc6c854be.png">

## Expected result:
<img width="1531" alt="Screen Shot 2021-09-01 at 3 50 44 PM" src="https://user-images.githubusercontent.com/4730197/131755588-8d733328-8808-4872-907c-a566f2c540e3.png">

## Reproduces how often: 
Always

## Version/Channel Information:
Starting from 1.29.x

**Comment by stephendonner** [comment]
Thanks for flagging, filing, and fixing, @yrliou 🤜 🤛

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.29.79 Chromium: 93.0.4577.63 (Official Build) (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/9951
- Encounter the website issue which @kjozwiak mentioned via https://github.com/brave/brave-core/pull/9951#issuecomment-912150386 multiple page reload fixed the issue.
![image](https://user-images.githubusercontent.com/38657976/132497711-965a3dc4-bead-4efe-bbc1-3f40e3e37eab.png)
