### ISSUE TITLE
Youtube Bug

### ISSUE THREAD

**Issue by starboyvarun** [brave/brave-browser#17836]
## Description 

While I play a video on youtube,
1. It is not able to automatically change the quality, even if I change it automatically.
2. Then when I select 720p quality video, the video gets buffered but still lags for no reason at intervals of 5 seconds or less for 1 or 2 seconds.
I tested with other browser's it works fine even with 4k.

## Brave version (brave://version info)

Version 1.29.76 Chromium: 93.0.4577.58 (Official Build) (64-bit)

## Version/Channel Information:
 Every channel.

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? No

## Miscellaneous Information:

While I increase the speed *2 it happens more frequently.
I think this is a bug please fix this.

**Comment by starboyvarun** [comment]
@bsclifton thanks.

**Comment by ryanbr** [comment]
Hey @starboyvarun   

- Can you clear cookies, cache images in `brave://settings/clearBrowserData` then relogin into youtube to retest? 
- Does it perform in private window mode (with no extensions)? 
- Does it matter if you're logged in or not?

**Comment by starboyvarun** [comment]
@ryanbr yes I did it.
still facing the same issue.
It performs in the private window as well.
It doesn't matter whether logged in or not.

**Comment by vikdb** [comment]
Same here

**Comment by starboyvarun** [comment]
@ryanbr  @vikdb  Is this issue resolved?
I am still facing this issue.

**Comment by starboyvarun** [comment]
This issue is still not resolved.

**Comment by starboyvarun** [comment]
@bsclifton  This issue has still not been fixed can you please recheck this.
Thank You.!

**Comment by bsclifton** [comment]
@starboyvarun there's not enough here for us to act on, unfortunately. I think both myself and @ryanbr have tried the steps but it's not reproducible. I'm going to close - but let's re-open if there are more actionable details for us:
- OS and version of OS
- Are you using VPN?
- Have you tried disabling hardware acceleration? (even just as a test) Perhaps a graphics patch we have has a conflict with something
