### ISSUE TITLE
User should be able to 'Claim' the grant from the BAT panel.

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#1783]
## Description 

On vs 0.55.19, received token grant notification. The button should be 'Claim' instead of 'OK'. And the claiming the grant should be done on the panel without user having to go to the Settings page.

In the current build:
![screen shot 2018-10-22 at 3 56 50 pm](https://user-images.githubusercontent.com/4369856/47324183-ac67b300-d613-11e8-96a5-cc6311e78615.png)

Expected:
![screen shot 2018-10-22 at 4 00 42 pm](https://user-images.githubusercontent.com/4369856/47324197-b984a200-d613-11e8-81c3-f26cf0adc58f.png)

Click on the Claim button:
![screen shot 2018-12-03 at 12 47 27 pm](https://user-images.githubusercontent.com/4369856/49400736-09b65000-f6fa-11e8-8bb4-19280758e217.png)

Error:
![screen shot 2018-12-03 at 12 47 31 pm](https://user-images.githubusercontent.com/4369856/49400740-0de26d80-f6fa-11e8-9bc2-edce76237ad4.png)

Success:
![screen shot 2018-12-03 at 12 47 37 pm](https://user-images.githubusercontent.com/4369856/49400777-1fc41080-f6fa-11e8-8e4e-fd7f68840bae.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1092 and did some exploratory testing
Experienced https://github.com/brave/brave-browser/issues/2959 and https://github.com/brave/brave-browser/issues/2956
![image](https://user-images.githubusercontent.com/34715963/51356846-74f68e80-1abc-11e9-9485-50d3a194d9f9.png)
