### ISSUE TITLE
google maps poor performance

### ISSUE THREAD

**Issue by tx350z** [brave/brave-browser#17835]
## Description 

Noticed in the last week that google maps perform poorly when using Brave. No such problem exists with other browsers.

## Steps to Reproduce

   1. Go to https://www.google.com/maps
   2. Notice extended time required for page to complete
   3. Attempt to drag or zoom the map.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Version 1.29.76 Chromium: 93.0.4577.58 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Don't use beta software.
- Can you reproduce this issue with the nightly channel? Don't use dev version software

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Don't use Brave Rewards
- Is the issue reproducible on the latest version of Chrome? Don't use Chrome browser

**Comment by ryanbr** [comment]
I saw no obvious slowdowns Is Hardware Acceleration enabled via `brave://setting/extensions` ? Also would test via ethernet, since googlemaps streams lots of data (wifi would show slowdowns) @tx350z

**Comment by Tonev** [comment]
`Brave Community` feedback:
https://community.brave.com/t/google-maps-slowness-and-cpu-very-high/279092/

**Comment by onmyouji** [comment]
I have the same issue when using Google Maps. 

FYI this problem is also reproducible on latest Chrome 93.0.4577.63 (Official Build) (64-bit) (cohort: 93_Win_63)

**Comment by gibranparvez** [comment]
Same issue, 93.0.4577.63

**Comment by tx350z** [comment]
Hardware acceleration does not solve this for me but I have an older laptop.

**Comment by ryanbr** [comment]
I retested Brave release and Chrome, couldn't see any difference. But there is an open ticket regarding performance.

https://bugs.chromium.org/p/chromium/issues/detail?id=1246406

Not much we can do here, since its a Chromium regression. Any possible fix here will come to Brave.

**Comment by rebron** [comment]
Per the activity in https://bugs.chromium.org/p/chromium/issues/detail?id=1246406 and with current version of Brave 1.29.81 Chromium: 93.0.4577.82

I'm not seeing any issues on Windows or macOS performance wise with Google Maps on the current version.

This issue should be resolved.

**Comment by ryanbr** [comment]
@tx350z is the latest Brave release build ok with google maps?

**Comment by tx350z** [comment]
Yes, the problem seems to be resolved!

**Comment by ryanbr** [comment]
Thanks!
