### ISSUE TITLE
Bat tokens disappeared. 

### ISSUE THREAD

**Issue by seriousdee** [brave/brave-browser#17837]
## Steps to reproduce 

   1.  Last time I checked, I had 4.00+ bat tokens
   2. But today, I only have 0.202 tokens
   3. I didn't enabled auto contribute. Please help return my tokens

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): phone
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by Miyayes** [comment]
Hello, it would be better to open a thread here on our official support forum: https://community.brave.com. It will allow support team to more effectively render support than on Github. If we discover a bug as a result of our investigation, it will be filed on Github.
