### ISSUE TITLE
Feature Request: Add Cookie Popup Code to Brave

### ISSUE THREAD

**Issue by NathanaelA** [brave/brave-browser#17846]
## Description 

Most sites now have those annoying you have to accept these mandatory cookies to use the website...   Integrate into the brave code something like this https://www.i-dont-care-about-cookies.eu/ so that these stupid dialogs are  blocked by default in Brave just like Brave blocks advertising and tracking...

**Comment by Tonev** [comment]
Brave allows you to hide those annoying consent windows, too.

1. Open `brave://adblock` via the address bar.
2. Enable `Fanboy Annoyances List` and `uBlock Annoyances List (used with Fanboy Annoyances List)`.

**Comment by ryanbr** [comment]
yeah this is a dube, we're certainly investigating it. Just no eta just yet.  @NathanaelA
