### ISSUE TITLE
Please add a toggle for reverting audio icon

### ISSUE THREAD

**Issue by sadgachawhalenoises** [brave/brave-browser#17845]
## Description 

Please add a toggle for either reverting the audio icon when audio is playing in a page or removing it entirely
It is extremely distracting and looks terrible against the background

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/77848679/131900586-a552cc83-63f3-45b8-9a73-8f6f3a09fa96.png)

## Expected result:
![image](https://user-images.githubusercontent.com/77848679/131900372-c78b86c6-9121-4990-ab02-7082b37637a0.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.29.76

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Y
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the nightly channel? - Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - N
- Does the issue resolve itself when disabling Brave Rewards? - N
- Is the issue reproducible on the latest version of Chrome?

**Comment by Tonev** [comment]
+1 from me, I believe it was much better positioned at the right side.

`Brave Community` feedback:
https://community.brave.com/t/speaker-icon-moved-in-tab-annoying/278618

**Comment by bsclifton** [comment]
cc: @rebron @karenkliu

**Comment by rebron** [comment]
Closing as wontfix. A future extension to be built that allows for this type of customization is how this should be handled for folks who want it. Maintaining a toggle/setting for something like this is too heavy to maintain and not trivial.

We deliberatly moved the audio icon as it was right next to the close button. There were too many opportunities for closing a tab versus muting a tab especially when users had many tabs open when the tabs themselves shrank.
