### ISSUE TITLE
speedreader: Add CLI flag for a custom stylesheet

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#17852]
This will allow others (like @jonathansampson ) to test stylesheet changes in https://github.com/brave-experiments/SpeedReader

**Comment by boocmp** [comment]
CLI already added.

**Comment by jonathansampson** [comment]
@boocmp I did a quick check for the CLI flag, but couldn't find one. Are you certain it landed? Thanks!

**Comment by boocmp** [comment]
Sorry, I was wrong, PR wasn't merged :/ I'll reopen it.

**Comment by boocmp** [comment]
@jonathansampson Just merged support of the --speedreader-stylesheet=<path to css> command line argument. It tracks file changes, so to test css, you can simply reload the test page without restarting the browser. NOTE: make sure you're using UTF-8 encoding in css file.
