### ISSUE TITLE
Need to improve the resolution/font weight of the notification counter

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#1785]
## Description 

On 0.55.19 Chromium
Both Shields and Bat notification counters are hard to see/read on my regular monitor (2560 x 1440) and retina (1680 x 1050) . May need to bump up the font weight. 

![screen shot 2018-10-22 at 3 16 04 pm](https://user-images.githubusercontent.com/4369856/47324758-f782c580-d615-11e8-96d7-f9a845ced080.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tomlowenthal** [comment]
Is @rossmoody going to specify the font-weight/colors for both of these? IMO we shouldn't have different behavior in Rewards vs. Shields.

**Comment by NejcZdovc** [comment]
@petemill @rossmoody correct me if I am wrong, but this was fixed right?

**Comment by rossmoody** [comment]
This was fixed. I think if there are any remaining discrepancies we should open a new issue with specific instance(s)
