### ISSUE TITLE
Bundle torrc-defaults 

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#17851]
https://hackerone.com/reports/1327794

**Comment by stephendonner** [comment]
@darkdh mind checking my results here?  essentially, we're just regression-testing and should have identical results as your steps say?

Both of my `TorClientUpdater`s are at `1.0.22`, and I noticed the testplan says `>=1.10.22`, so I wasn't sure.  🙏 

`release`

example | example | example | example
----------|-----------|----------|----------
![17851-1](https://user-images.githubusercontent.com/387249/147370817-39cf81d0-cb22-4dfd-bc55-fdde81f74779.png) | ![17851-2](https://user-images.githubusercontent.com/387249/147370818-d0d4c703-402a-4dd9-b279-9c8a544d4bf9.png) | ![17851-3](https://user-images.githubusercontent.com/387249/147370819-3b2c3a10-4aed-48da-ab86-36f2a032c0b6.png) | ![17851-4](https://user-images.githubusercontent.com/387249/147370820-90c80d2f-e8c1-4b84-9b78-43512447e57e.png)


`1.35.56`

example | example | example | example
----------|-----------|----------|----------
![17851-5](https://user-images.githubusercontent.com/387249/147370830-cdf810c6-7c14-4947-b22b-f3f9626ca49a.png) | ![17851-6](https://user-images.githubusercontent.com/387249/147370832-95c5b85a-fbed-45ee-b63c-04baa678e59c.png) | ![17851-8](https://user-images.githubusercontent.com/387249/147370842-0b86ba5b-61e0-427e-a1d6-c4715424d94c.png) | ![17851-7](https://user-images.githubusercontent.com/387249/147370847-091274eb-c523-4cb1-a73a-d9b003db91f7.png)

**Comment by darkdh** [comment]
I can't predict what QA would test on what version of the TorClientUpdaters but it has to be greater than 1.0.22
The result is correct, 1.35.56 has the fix works and release which doesn't have the fix but updated TorClientUpdaters works too.

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/11406 with build 

Brave | 1.35.59 Chromium: 97.0.4692.56 (Official Build) nightly (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 12.2 (Build 21D5025f)

Steps:

1. launch Brave `release` (`1.33.106`) and opened a `Private Browsing with Tor` window
2. made sure `TorClientUpdater` is `>= 1.10.22`
3. Navigate to `https://check.torproject.org/`, confirmed I successfully connected to the Tor network
4. launch Brave with this fix and open a Tor window
5. make sure TorClientUpdater is >= 1.10.22
6. navigated to `https://check.torproject.org/`, confirmed I successfully connected to the Tor network

`release`

example | example | example | example
----------|-----------|----------|----------
![17851-1](https://user-images.githubusercontent.com/387249/147370817-39cf81d0-cb22-4dfd-bc55-fdde81f74779.png) | ![17851-2](https://user-images.githubusercontent.com/387249/147370818-d0d4c703-402a-4dd9-b279-9c8a544d4bf9.png) | ![17851-3](https://user-images.githubusercontent.com/387249/147370819-3b2c3a10-4aed-48da-ab86-36f2a032c0b6.png) | ![17851-4](https://user-images.githubusercontent.com/387249/147370820-90c80d2f-e8c1-4b84-9b78-43512447e57e.png)


`1.35.59`

example | example | example | example
----------|-----------|----------|----------
<img width="988" alt="Screen Shot 2021-12-24 at 9 32 17 PM" src="https://user-images.githubusercontent.com/387249/147378170-525f6fc0-c628-434f-aff9-7b2bce6a35c5.png"> | <img width="988" alt="Screen Shot 2021-12-24 at 9 32 33 PM" src="https://user-images.githubusercontent.com/387249/147378171-a1131090-70b3-4503-9a30-5d67a5710466.png"> | <img width="988" alt="Screen Shot 2021-12-24 at 9 33 20 PM" src="https://user-images.githubusercontent.com/387249/147378173-889aeaff-a0d9-4dca-b74e-ef619d9efa49.png"> | <img width="988" alt="Screen Shot 2021-12-24 at 9 33 12 PM" src="https://user-images.githubusercontent.com/387249/147378172-e03ba451-08db-485d-bdc4-5c63dd157842.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 20H2 (Build 19042.1415)

**Comment by stephendonner** [comment]
Verification `PASSED` using

Brave | 1.35.78 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
--|--
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Linux

Steps:

1. launch Brave `release` (`1.34.80`) and opened a `Private Browsing with Tor` window
2. made sure `TorClientUpdater` is `>= 1.10.22`
3. Navigate to `https://check.torproject.org/`, confirmed I successfully connected to the Tor network
4. launch Brave with this fix and open a Tor window
5. make sure TorClientUpdater is >= 1.10.22
6. navigated to `https://check.torproject.org/`, confirmed I successfully connected to the Tor network

`release - 1.34.80`

example | example | example | example
----------|-----------|----------|----------
<img width="1200" alt="Screen Shot 2022-01-10 at 1 09 06 PM" src="https://user-images.githubusercontent.com/387249/148840248-8355af64-5fb8-4f05-b97c-795416e81d5f.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 1 09 31 PM" src="https://user-images.githubusercontent.com/387249/148840255-a82a2cb6-e19a-461e-8b82-8ce93a26dd84.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 1 10 04 PM" src="https://user-images.githubusercontent.com/387249/148840258-29f56dd5-65d4-4807-8a42-04ac1d2456c5.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 1 10 07 PM" src="https://user-images.githubusercontent.com/387249/148840262-0f50ead2-5f88-497e-bece-eef384999cf9.png">




`1.35.77`

example | example | example | example
----------|-----------|----------|----------
<img width="1200" alt="Screen Shot 2022-01-10 at 1 13 51 PM" src="https://user-images.githubusercontent.com/387249/148840379-879e446e-804d-4f25-9038-f717901e8c79.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 1 10 44 PM" src="https://user-images.githubusercontent.com/387249/148840412-b077c8b5-bae7-4879-94f7-cbbb57c42b49.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 1 10 52 PM" src="https://user-images.githubusercontent.com/387249/148840416-aa6b24b2-0f75-4d03-85dd-f24d0621a1e7.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 1 11 11 PM" src="https://user-images.githubusercontent.com/387249/148840418-5c43ac25-1c56-4765-ad9e-65cf214020eb.png">
