### ISSUE TITLE
Release Notes for Android 1.29.x Release #2

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17856]
- Fixed Brave crash when launching Twitter App on tablets running Android 5. ([#17735](https://github.com/brave/brave-browser/issues/17735))
 - Upgraded Chromium to 93.0.4577.63. ([#17790](https://github.com/brave/brave-browser/issues/17790)) ([Changelog for 93.0.4577.63](https://chromium.googlesource.com/chromium/src/+log/93.0.4577.58..93.0.4577.63?pretty=fuller&n=1000))

**Comment by Tonev** [comment]
@srirambv @kjozwiak 

Sorry for bothering you, but just wondering if https://github.com/brave/brave-browser/issues/17657 was intentionally not included although it has the `release-notes/include` label?

**Comment by srirambv** [comment]
It is part of the release notes. https://github.com/brave/brave-browser/blob/master/CHANGELOG_ANDROID.md#12978. Its just missed in the issue but added to the Changelog file and will be updated in `https://brave.com/latest/`

**Comment by Tonev** [comment]
Thanks for the quick reply, @srirambv & sorry for bothering :sweat_smile:
