### ISSUE TITLE
Implement P3A Brave.Sync.Status.2 metric

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#17862]
It is required to implement Implement `Brave.Sync.Status.2` P3A metric to understand better what happens with Sync.

cc @jsecretan

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Galaxy A52s 5G Android version 11` running `BraveMonoarm.64_1.32.94`

- Verified the test plan from https://github.com/brave/brave-core/pull/9921

<details>
<summary>Clean profile</summary>

<details>
<summary>Case 1: Sync is not enabled, Response value is `0`</summary>

</details>

<details>
<summary>Case 2: Standalone Sync is enabled (only one device is added in sync list), Response value is `1`</summary>

</details>

<details>
<summary>Case 3: Sync is enabled, 2nd device is added to the sync list, Response value is `2`</summary>

</details>

<details>
<summary>Case 4: Sync is enabled, 3rd device is added to the sync list, Response value is `3`</summary>

</details>

<details>
<summary>Case 5: Sync is enabled, 4th device is added to the sync list, Response value is `3`</summary>

</details>

<details>
<summary>Case 6: Sync is turned OFF, Response value is `0`</summary>

</details>

<details>
