### ISSUE TITLE
secure DNS not working

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [brave/brave-browser#17867]
## Steps to Reproduce
Enable Brave setting: Privacy and security > Security > 'Use secure DNS' > with Cloudflare (1.1.1.1) 

## Actual result:
Going to https://www.cloudflare.com/ssl/encrypted-sni/ shows that secure DNS is not working ok:

![image](https://user-images.githubusercontent.com/7840350/132052856-6045fac8-4318-4716-b5c7-46331d036e67.png)

Going to https://www.dnsleaktest.com/results.html or https://ipleak.net/ ----  shows my ISP DNS resolvers instead of 1.1.1.1

## Brave version (brave://version info)
Version 1.29.76 Chromium: 93.0.4577.58 (Official Build) (64-bit) on Windows 10 21H1

**Comment by TheAresjej** [comment]
Exactly the same result with manual dns setting.
**Brave:** Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (64-bit)
**OS:** Fedora 34

![image](https://user-images.githubusercontent.com/19390797/132130984-8fa9cf67-ca10-4e0f-8568-9090458742e2.png)
![image](https://user-images.githubusercontent.com/19390797/132130999-14e82113-e1af-4065-8c01-86808dca3873.png)
![image](https://user-images.githubusercontent.com/19390797/132131008-35d2687d-fdbc-40c6-becf-d63c90ac35b2.png)
![image](https://user-images.githubusercontent.com/19390797/132131040-e4aaa3db-6650-43f3-b14a-90f31c27eb6e.png)

**Comment by diracdeltas** [comment]
what do you see when doing this in Chrome/Chromium?

**Comment by fusionneur** [comment]
Can we have an increased priority on this? Advertising security which doesn't work doesn't sound too good..

**Comment by arthuredelstein** [comment]
I tried this today and I'm getting all good results on the test page:

![image](https://github.com/brave/brave-browser/assets/355566/0af0f1bf-419a-4793-b31e-3d8fef38b6b6)

Also, ipleak.net is showing the Cloudflare DNS servers as expected:

![image](https://github.com/brave/brave-browser/assets/355566/62680934-73e1-428b-ba53-634d4a884419)

So I'm closing as "works for me."
