### ISSUE TITLE
Feature request please: Side bar 

### ISSUE THREAD

**Issue by MaximumCodingLife** [brave/brave-browser#17876]
A small bar on the side like what oprea and Vivaldi browsers have. Features such as: Music with Spotify, apple music. Custom tabs, messaging apps.
Thank you

**Comment by stephendonner** [comment]
Hi @MaximumCodingLife you can enable this via the toggle to `Enabled` in `brave://flags/#sidebar` - might still only work in `nightly` builds.

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/15833
