### ISSUE TITLE
Handle wallet_watchAsset method to add suggested tokens

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#17878]
Example code to trigger this popup:
https://docs.metamask.io/guide/registering-your-token.html#example

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/11518.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11518>brave/brave-core#11518</a></li>
         <li>Verified suggested tokens can be added successfully when approved on the panel</li>
         <li>Verified suggested tokens with a favicon loads correctly</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/149292264-dd1078d4-7b0e-4cb8-af74-139dc035aabf.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/149291067-2132ec0a-2ea1-4091-9af8-5ce2a8698946.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/149290556-e1d9f2b4-38ea-42aa-b278-ee0aa58b7d3d.mov>
      </td>
   </tr>
</table>
