### ISSUE TITLE
How to run brave with command line flag --log-net-log=/sdcard/file.json

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#17877]
## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Can you elaborate on this a bit?

**Comment by tathastu871** [comment]
> Can you elaborate on this a bit?

Wanted to launch brave with  --log-net-log=/sdcard/file.json command line flag. Launching android browsers with command line flags require to specify flags in /data/local/tmp/chrome-command-line.
Want to launch brave with this log net command line flag  so that every opened tab url is logged in file. 
Brave has no feature to export opened tab urls because bookmark is non functional and bloggy.


SO THIS IS MY ALTERNATIVE SOLUTION THAT MAY WORK
