### ISSUE TITLE
Disable media-router by default

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#17873]
## Description 
Cast initiates SSDP requests by default. Cast should be disabled by default, add a setting to enable cast.

More details here: https://github.com/brave/brave-browser/issues/5057#issuecomment-912781690

**Comment by kjozwiak** [comment]
Removing `OS/Android` as this will be verified on `Android` via https://github.com/brave/brave-browser/issues/17972.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.29.80 Chromium: 93.0.4577.63 (Official Build) (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/10007

**Comment by reyesvicente** [comment]
Encountered this just now. I just opened Brave Browser and this popped up. 
![Screenshot 2021-11-22 at 11 09 32 PM](https://user-images.githubusercontent.com/45283313/142885828-4836bb8f-c132-4562-9929-943d0ef83248.png)

**Comment by GeetaSarvadnya** [comment]
cc: @stephendonner

**Comment by stephendonner** [comment]
> Encountered this just now. I just opened Brave Browser and this popped up. ![Screenshot 2021-11-22 at 11 09 32 PM](https://user-images.githubusercontent.com/45283313/142885828-4836bb8f-c132-4562-9929-943d0ef83248.png)

Please file a new issue with steps to reproduce and as much info as you can.  (cc me on it, please).

I installed Lulu and have Media Router disabled and don't see anything with mediacast popping up on Lulu.
