### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by Githuborian** [brave/brave-browser#17872]
Brave whitelist is broken.
- You added your links but can't change a thing about the cookies, for example, youtube uses lots of cookies, why not just allow those that are used to login and make it functionall and block the rest? Can't be doen right now.
- If you whitelist sites and want all the rest to be deleted on close whitelist is also deleted. Does brave even care about users..
- If you have sites in your whitelist or blacklist and the site changes domain (in just a tiny part) the site can never be removed and thus its cookies. You first need to delete ALL cookies (clearing) in order to have it gone and then you have to start all over again with whitelisting, logging in. Whats up Brave...
- There aren't any options you can choose from, for example, i want to whitelist marketplaats.nl but not account.marketplaats.nl yet when i open a different extension all of it is whitelisted. Why isn't there a function that automaticly reads these site cookies and gives you a list so you can individualy block certain cookies from 1 site is beyond me.

For a browser that says is all about privacy there are allot of things that need to be worked on FIRST. I mean, cookies, dude... thats basics.

When i look around on the internet, people have been waiting for these functions for years and nobody is addressing these issues of the users, or addressing them but then ignoring them because it is not fixed.
I hope that with this thread i can convince some smart kid at Brave to open up a conversation and have this on the top of the list at the Devs.

Thanks.

**Comment by Githuborian** [comment]
And i forgot to say that Brave has build in the option to block ALL cookies.. why?
Today you can't even open a website without a cookie. Is this the stone age? I thought Brave was the future..

Frustrations...

**Comment by Nihal247** [comment]
Hi @Githuborian, this feature is completely optional, not all sites will be broken by blocking all cookies btw. Many still function. This option is helpful for the people, who crave privacy more than others. Brave even don't recommends selecting this feature. This option isn't built only to Brave, but browsers like Safari, Microsoft Edge and Firefox even have this option.  If you don't want to block all cookies, just simply select 'Block third-party cookies' or if you want to allow all, just select 'All all cookies'.

**Comment by Nihal247** [comment]
> * You added your links but can't change a thing about the cookies, for example, youtube uses lots of cookies, why not just allow those that are used to login and make it functionall and block the rest? Can't be doen right now.
> * If you whitelist sites and want all the rest to be deleted on close whitelist is also deleted. Does brave even care about users..
> * If you have sites in your whitelist or blacklist and the site changes domain (in just a tiny part) the site can never be removed and thus its cookies. You first need to delete ALL cookies (clearing) in order to have it gone and then you have to start all over again with whitelisting, logging in. Whats up Brave...
> * There aren't any options you can choose from, for example, i want to whitelist marketplaats.nl but not account.marketplaats.nl yet when i open a different extension all of it is whitelisted. Why isn't there a function that automaticly reads these site cookies and gives you a list so you can individualy block certain cookies from 1 site is beyond me.

I suspect all your problems are related to sign in again and again after each browser restart. Right? Hmmm...., just use a password manager to autofill, Brave has it's own one. You can use it. It'll ease your life.

But I agree to one of your points, to allow subdomains to store cookies, and block the main domain.

**Comment by Githuborian** [comment]
This is NO option because today you need to login with 2FA, sms, email all 3, so auto login with extensions or from brave doesnt help me. Brave needs to step up and fix the cookies section. If you ask me this isnt all that hard to do for the devs.

**Comment by Nihal247** [comment]
I see your concern @Githuborian

**Comment by Githuborian** [comment]
Good, someone sees my problems. unfortonatly Brave team is asleep.........

**Comment by rebron** [comment]
Closing. We have templates and processes that we have in place to fix specific and actionable issues. 
For additional comments and feedback, please visit https://community.brave.com/
