### ISSUE TITLE
PDFs fail to load if behind basic auth

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1788]
Carried over from https://github.com/brave/browser-laptop/issues/8702

> If a pdf file is behind basic auth, then it fails to display with our pdfjs extension.
> 
> Steps to reproduce: 
> 1. Download this script and extract it to your home directory
> [SimpleHTTPAuth.py.zip](https://github.com/brave/browser-laptop/files/977487/SimpleHTTPAuth.py.zip). Create a pdf file named `type.pdf` in the same directory.
> 
> 2. Start it `python SimpleHTTPAuth.py 9001 u:p`
> 3. Navigate to `http://localhost:9001/type.pdf`
> 
> Note it works in Chrome with pdfjs but not in Brave built in.
> 
> 
> CC @diracdeltas

**Comment by diracdeltas** [comment]
This is actually sort-of fixed in Brave core, except it prompts you to download the PDF after you authenticate. However if you click 'cancel' on the save prompt and reload, then it displays the PDF in PDFJS.

**Comment by tpeacock19** [comment]
I think this may have been the wrong issue to identify; however I'm experiencing the following:

I have a kanboard instance here https://kb.treypeacock.com which you can login with u:test p:testpass

If you access the only shared project
![01-brave-pdf-issue](https://user-images.githubusercontent.com/6407145/47336276-559fbf00-d68f-11e8-8e8a-8f5ac92666cd.png)
select the task
![02-brave-pdf-issue](https://user-images.githubusercontent.com/6407145/47336282-5e909080-d68f-11e8-9b9c-89da2ef66938.png)
attempt to view the pdf you are thrown the following error:
![03-brave-pdf-issue](https://user-images.githubusercontent.com/6407145/47336287-60f2ea80-d68f-11e8-8eec-11cc47ce7e31.png)
![04-brave-pdf-issue](https://user-images.githubusercontent.com/6407145/47336383-ce9f1680-d68f-11e8-8cf0-25a409d4a81e.png)

I get the same error when I need to login to my university's Active Directory and attempt to view a pdf.

**Comment by mwdiers** [comment]
Thank you for bringing this forward again. This is is the one issue that is preventing me from switching entirely to Brave, as I cannot view any reports in our ERP system without downloading them first (which is a pain in the rear when I am trying to pound through PO approvals for IT).

**Comment by diracdeltas** [comment]
@tpeacock19 that is a separate PDFJS issue (this one only applies to PDFs which are behind HTTP basic auth)

**Comment by diracdeltas** [comment]
confirmed that it works on Chrome with PDFJS extension

**Comment by tpeacock19** [comment]
@diracdeltas is there currently an open issue for this or should I make one?

**Comment by diracdeltas** [comment]
actually i was mistaken, the basic auth issue is not fixed in Chrome either. what happens in Chrome is that it loads in pdfium (which i mistook for pdfjs). Brave disables pdfium so instead it tries to download the pdf.

**Comment by bbondy** [comment]
@tpeacock19 the one you ran into is not related to basic auth and is fixed here:
https://github.com/brave/brave-browser/issues/1287
It'll be included in 0.57.x but I'll see if we can get it in 0.56.x which is about a week away.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7 x64

Used STR from OP.
