### ISSUE TITLE
Hide Brave Icon in Address Bar

### ISSUE THREAD

**Issue by damienbutt** [brave/brave-browser#17888]
Trying out Brave for the first time today.

How do I hide the Brave Shields icon in the address bar. I don't want to see it. 

Also, the "Bookmark this Tab" button on the left in the Toolbar, how do I hide that?

**Comment by thefallofbecause** [comment]
The team have previously stated they won't give a way to hide the Shields icon: https://github.com/brave/brave-browser/issues/16778

**Comment by damienbutt** [comment]
Shame. Uninstalled.
