### ISSUE TITLE
Pinned tabs scroll away

### ISSUE THREAD

**Issue by ygoe** [brave/brave-browser#17881]
## Description 
Pinned tabs are just small but not pinned. When tab scrolling is enabled (through flags), which is IMO necessary to handle larger amounts of tabs, then the pinned tabs at the left end of the tab bar are simply scrolled away with all the other tabs. Firefox shows pinned tabs permanently, while scrolling all other tabs (without a special setting, it just scrolls as default).

## Steps to Reproduce

   1. Enable tabs scroling in flags
   2. Pin tabs
   3. Open many tabs until scrolling is in effect

## Actual result:
Pinned tabs scroll out of view

## Expected result:
Pinned tabs remain visible all the time

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
<html>
<body>

Brave | 1.29.77 Chromium: 93.0.4577.63 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
Betriebssystem | Windows 10 OS Version 2009 (Build 19042.1052)

</body>
</html>

## Version/Channel Information:
- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? unknown
- Can you reproduce this issue with the nightly channel? unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? yes

## Miscellaneous Information:
What's the purpose of "pinned tabs" after all?

**Comment by TheCultLeader666** [comment]
Pinned tabs are preserved between browser sessions when normal tabs aren't.

**Comment by ygoe** [comment]
Ah. Never noticed that as my default for productive browsers is always to restore the session on startup.

**Comment by rebron** [comment]
Closing, not actionable. Experimental flags are experimental and not something we act on. Pinned tabs fix may get addressed as the tab scrolling feature gets developed.

**Comment by ygoe** [comment]
Okay, so I guess nobody is interested in knowing that new tabs aren't completely visible either. When a new tab is opened (not the right-most one), the new tab header is moved out of the view by 2 or 3 pixels to the right. I haven't found out the exact circumstances yet.

Also, when tab scrolling is active, a small part left and right of the scroll container isn't painted when the browser window is activated or deactivated. My active title colour is blue and the inactive colour is white. When the browser is activated or deactivated, a part remains in the old colour until the tabs are scrolled again.

Where would be a place to report such bugs in "experimental" features? I mean, somebody is trying them out so they should be interested in knowing whether they work or not.

**Comment by JimB-Dev** [comment]
Chromium project for this one I think.
