### ISSUE TITLE
Need to add the Verified mark for the verified YT channel.

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#1789]
## Description 

Verified YT channel is not indicated with the mark. (0.55.20 on Mac)

![image](https://user-images.githubusercontent.com/4369856/47333214-eac29980-d636-11e8-826d-ae316b011ca7.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
closing as dupe of https://github.com/brave/brave-browser/issues/1795
