### ISSUE TITLE
Auto Contribute enabled by default

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#17892]
## Description 
Brave Rewards auto-contribute is enabled by default. The Rewards onboarding assistant only asks the user for the amount per month, no option to not enable it. This would prevent people from discovering some of their BAT was lost due to AC being on.

## Steps to Reproduce

   1. Install Brave
   2. Enable Rewards

## Actual result:
Onboarding assistant asks for how many ads max per hour you want to see, and how much BAT you want to allocate for monthly auto-tipping.

## Expected result:
Brave should explicitly asks users if they want to enable auto-contribute. It also only gives a 1-5 ads per hour despite 10 ads/hour being available.
**It should also clearly mention that, regardless to how many ads you've set, the actual number of ads you will see will likely vary.**

## Reproduces how often: 
Every single time.

## Brave version (brave://version info)

Brave | 1.31.23 Chromium: 93.0.4577.63 (Build officiel) nightly (64 bits)
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
Operating system | Windows 10 OS Version 2004 (Build 19041.1165)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by Ayern12** [comment]
##But I don't know if the money will be due?

Pada Sel, 7 Sep 2021, 04:40 UjCbFwtBayFM ***@***.***> menulis:

**Comment by bsclifton** [comment]
cc: @Miyayes

**Comment by Miyayes** [comment]
This was an intentional product decision, and should essentially be resolved with https://github.com/brave/brave-browser/issues/15308.

**Comment by UjCbFwtBayFM** [comment]
No, it is not related. Feels like you didn't even read my post. Users should have the option to disable it when they first set up Brave.
