### ISSUE TITLE
Build out Add Custom Token UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#17893]
## Description 
Build out the Add Custom Token UI to the `Visible Asset List` Modal

![Screen Shot 2021-09-06 at 8 21 50 PM](https://user-images.githubusercontent.com/40611140/132274606-1282ec19-52e5-4cf8-9c3d-050eecd6f5a0.png)

You can find the specs for this component in Figma / Desktop Crypto Wallets.

Add the component too storybook with mock data for testing.

## Expected result:

Component should be visible and functional in Storybook under the Wallet/Desktop/Concepts and Wallet/Desktop/Components tabs.

**Comment by bbondy** [comment]
moved this to non MVP backlog
