### ISSUE TITLE
"Switch to this tab" button which appears when typing in a URL already opened in another tab loads it in a new tab, instead of switching to the tab

### ISSUE THREAD

**Issue by life777eternal** [brave/brave-browser#17891]
## Description 
The "Switch to this tab" button opens the URL in a new tab, instead of switching to the previous tab.  

## Steps to Reproduce

   1. Reopen Brave with several windows and quite a bit of tabs in each window.
   2. Type the name of a previously opened tab.
   3. Click on the "Switch to this tab" link button that appears under the URL
   4. Notice that it loads it in a new tab.
   5. If that is done again, it switches to the previously opened tab. 

## Actual result:
A new tab is opened.

## Expected result:
A switch to the previously opened tab. 

## Reproduces how often: 
Always for me.

## Brave version (brave://version info)
Brave | 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

## Version/Channel Information:
Release

- Can you reproduce this issue with the current release? Aye
- Can you reproduce this issue with the beta channel? Not attempted
- Can you reproduce this issue with the nightly channel? Not attempted

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Would be happened because the previous tab is not reloaded? 

Thank you.

**Comment by bsclifton** [comment]
@life777eternal I can't reproduce this - but I had noticed you're on an older version of Brave. Can you please update? We're up to Chromium 93 now, which means you're two major versions behind (Chromium team has lots of updates- this may have been an issue and fixed)

**Comment by life777eternal** [comment]
> I can't reproduce this - but I had noticed you're on an older version of Brave. Can you please update? We're up to Chromium 93 now, which means you're two major versions behind (Chromium team has lots of updates- this may have been an issue and fixed)

@bsclifton Had to do a manual update, with a full uninstall and then a reinstall after shut down. My copy of Brave wasn't updating automatically.  And that update did fix it for me. Thank you, I hadn't realized that there was any update, my copy of Brave hadn't shown any updates for a while.  Shalom.
