### ISSUE TITLE
Bug: Online jupyter notebook's  .ipynb

### ISSUE THREAD

**Issue by starboyvarun** [brave/brave-browser#17901]
## Description 
When I open online assignment jupyter notebook i.e Coursera. It takes a lot of time to open the notebook or load the online notebook. And sometimes I have to refresh it more than 20-25 times.
When I open it in another browser it opens in less than 5 seconds to load.

## Reproduces how often: 
Most of the times.

## Brave version (brave://version info)

Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome?  I am using the latest version of Brave.

## Miscellaneous Information:
 I think brave is blocking some particular files of the online notebook, thinking it to be unsafe.

##  *Please solve this is bug on priority as most of them are having Study from home and having a similar online notebook for assignments.
Thank You.

**Comment by rebron** [comment]
@starboyvarun Do you have a specific .ipynb or link to look at? We'll need to create an account with Coursera to investigate this issue. Have you also let coursera know you're running into issues?

cc: @rynabr

**Comment by starboyvarun** [comment]
@rebron Actually I haven't told Coursera about the issue as with another browser it's working fine.
I will let them know for sure now. 
Specific .ipynb assignment is linked with your account of Coursera.
And to be exact I was using a deep learning course  .ipynb assingments.
Thanks!

**Comment by starboyvarun** [comment]
@rebron  ??

**Comment by starboyvarun** [comment]
@rebron  I reported the Bug to Coursera they closed it saying it's not related to them.

**Comment by starboyvarun** [comment]
@rebron This bug hasn't been fixed till now.Can you set the deadline?
Thanks!

**Comment by rebron** [comment]
@starboyvarun We don't have enough information here as we need to be able to reproduce the issue ourselves and we're not at that point yet. We need more information. Can you provide the course, the file, a video showing what you're encountering.
Can you try turning shields off? Is it possible that you might be in conflict with another extension? 

What browsers were you able to view the Coursera course in?

**Comment by rebron** [comment]
cc: @ryanbr Are we blocking anything with Coursera? 

Is this Extension is helpful. Again @starboyvarun, we just don't have any information.
https://chrome.google.com/webstore/detail/jupyter-notebooks-ipynb-v/obgkpboeomlhgaphgcodgmpphdohclgj?hl=en-US

**Comment by ryanbr** [comment]
We do block some items, but nothing unusual.  Not easy to test without using login details/problem link from @starboyvarun . Free to DM me with the details (via twitter on @fanboynz or via telegram https://t.me/FanboyNZ)

**Comment by starboyvarun** [comment]
@rebron  No, the extension doesn't help. It  convert .ipynb notebook in HTML or PDF format. We have to submit the assignment online and complete it online.

**Comment by starboyvarun** [comment]
@ryanbr
Done. Please check your telegram.
Thank You.

**Comment by starboyvarun** [comment]
This Bug has been fixed in the latest version of Brave: V1.29.81 (Sep 14, 2021). Therefore I am closing this issue.
@ryanbr @rebron 
Thank you.
