### ISSUE TITLE
Optimize parseDomain in content_cosmetic.ts

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#17906]
## Description 
Optimize page load by replacing parseDomain in native cosmetic filter implementation to the faster alternative.

## Steps to Reproduce
   1. Visit a very simple HTML page like https://example.com
   2. Open Developer Tools: Performance
   3. Click record page load time. 
   4. Find for parseDomain in the trace
## Actual result:
1. parseDomain exists and takes some time (>20ms), which **slow down** every page/frame loads
2. it **takes few additional MB** for each frame.

## Expected result:
Now significant speed/memory impact.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Version 1.31.23 Chromium: 93.0.4577.63 (Official Build) nightly (64-bit)

## Version/Channel Information:
- Can you reproduce this issue with the current release? : yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? yes (partially: still have the same problem with brave extension)
- Does the issue resolve itself when disabling Brave Rewards?  no
- Is the issue reproducible on the latest version of Chrome?  no

![brave_local_build](https://user-images.githubusercontent.com/45488748/132354356-3245db34-3ab1-4d1d-9175-d5c2d4435c87.png)
![brave_nightly_without_shield](https://user-images.githubusercontent.com/45488748/132354361-94a2b77b-3185-47f0-a2f0-4bd53c7761d7.png)
![chrome_no_adblock](https://user-images.githubusercontent.com/45488748/132354362-bf9ab985-acd5-4c59-8abe-f8f25c197774.png)

**Comment by iefremov** [comment]
cc @antonok-edm @pes10k

**Comment by stephendonner** [comment]
@atuchin-m I've tried to reproduce the problem before I verify the fix, and on macOS, using `1.29.81` (and likely just-released `1.30.86`), I can find `Parse HTML` and others always, but haven't-yet managed to see `parseDomain` in the affected build.

Would you mind recording a screencast (using https://www.cockos.com/licecap/ or similar) showing how to reproduce the issue?  Thanks regardless!

**Comment by stephendonner** [comment]
Setting `QA/Blocked` since although there are helpful steps, I just haven't been able to reproduce the problem, to verify the fix, yet.

**Comment by atuchin-m** [comment]
@stephendonner 
Hi! Not sure that the steps to reproduce are absolutely correct;)  The screenshot was from a dev build to give the more detailed information.

The ticket is about a performance problem, therefore the key aspect is the time of `ParseHTML`. And `ParseDomain` one of the reasons why it was slow. The other were [here](https://github.com/brave/brave-browser/issues/17538#issuecomment-915150973).
Now all issues are fixed, and we have a good performance again: I see 127ms(stable) vs 13ms (nightly).

About the `ParseDomain`: is harder prof by QA that this particular thing is optimised (but you can see optimization in general) 
You can't see the exact function name in release builds because it's obfuscated. But you can guest we it's from the call tree.

Note that this js-function was completely removed in the PR and replaced with a native function. So you can't find it now in perf-traces after the fix.

 I suggest comparing 1.30 with a recent nightly build and you see the difference in **call structure** and time.
 
Here is the gifs:
![brave_nighly](https://user-images.githubusercontent.com/45488748/135209856-c1b5f7af-d351-4474-96da-41071eaef186.gif)
![brave_1_30_parse_domain](https://user-images.githubusercontent.com/45488748/135209860-c86d8202-f222-4878-96e2-2eb28f368404.gif)
:

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.31.67 x64 Beta build
- Verified parseDomain load time reduced from 410ms to 61ms when profiled for 5 sec 

1.30.86 | 1.31.67 Beta
-- | --
![image](https://user-images.githubusercontent.com/17010094/136020033-32cf2947-8fc1-4fa9-ad12-14c7026c3ce9.png) | ![image](https://user-images.githubusercontent.com/17010094/136020155-d2130dba-9a93-4cb1-9850-0c5e2f0dc710.png)
