### ISSUE TITLE
Follow up to #17294 Purchase intent is extracted twice on google.com

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#17908]
This is because of gdpr consent

## Steps to Reproduce

1. Clean profile
1. Connect to UK through VPN
1. Run Brave with UK locale
1. Enable rewards
1. Wait till ads catalog and all components are downloaded
1. Close Brave
1. search with google for a keyword (example: `free bitcoin mining`)
1. Check `ads_serice/client.json`

## Actual result:

Purchase intent is extracted twice for both funnel site (google.com) and keyword(conspiracy)
![image](https://user-images.githubusercontent.com/34715963/127841562-c8fabc65-1359-4656-9eea-f780a1cb0918.png)

Note: notice that sometimes only keyword is extracted, still it is extracted twice

This is before gdpr consent:
![image](https://user-images.githubusercontent.com/34715963/127843985-482b5d42-deab-4435-b677-a95d37dc4112.png)
After gdpr consent, the purchase intent is extracted again
![image](https://user-images.githubusercontent.com/34715963/127844152-cbfae47e-e7b6-4701-9650-e62508758ae9.png)

Important: the purchase intent will always be extracted twice, that is on subsequent searches, even when not shown:
![image](https://user-images.githubusercontent.com/34715963/127844451-81b13352-6b5c-4169-9e1d-f6c93b141a5a.png)

## Expected result:
Purchase intent extracted once

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

Brave | 1.30.65 Chromium: 93.0.4577.63 (Official Build) beta (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Ubuntu 18.04 LTS

cc @tmancey @moritzhaller @iambrianfung @rebron @jsecretan @brave/legacy_qa

**Comment by tmancey** [comment]
@btlechowski could you please retest, as the code has changed since this was raised. Thanks

**Comment by tmancey** [comment]
@btlechowski this should be resolved
