### ISSUE TITLE
Setup basic perf tests infra

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#17903]
We need to run at least basic perf tests continuously. This would be an umbrella task for this work
 1. Discuss and pick up proper tests, metrics, scenarios
 2. Run them locally, compare with the upstream and/or other "competitors" (e.g. chrome + ublock), file obvious issues if needed
 3. Work with devops to setup cloud infra and regular runs

**Comment by atuchin-m** [comment]
Devops tickets:
https://github.com/brave/devops/issues/6330
https://github.com/brave/devops/issues/6328

Catapult PR: https://github.com/atuchin-m/catapult/pull/1

**Comment by LaurenWags** [comment]
@atuchin-m can you please label `QA/Yes` or `QA/No` as appropriate? If `QA/Yes`, please ensure there's a test plan, thanks!

cc @rebron @kjozwiak

**Comment by atuchin-m** [comment]
@LaurenWags I've added `QA/No`
