### ISSUE TITLE
Tor window freezes browser Ubuntu 16.04

### ISSUE THREAD

**Issue by scmart** [brave/brave-browser#1791]
## Description 
Opening a "New private window with Tor" instead opens a window that is entirely grey, and freezes all other windows, unable to close or interact.  The CPU usage also spikes, and during one attempt, while the Brave task manager was open, it refreshed a single time after approximately 30 seconds to show high CPU usage for the "Browser" task.  After a while an unresponsive tab warning shows up, but it is also frozen, and empty inside the popup.

## Steps to Reproduce

   1. Open Brave
   2. Attempt to open a private window with Tor

## Actual result:
Entirely grey window opens (from border to border, top to bottom), all other windows are frozen.

## Reproduces how often: 
100% reproducible

## Brave version (brave://version info)
Version 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
Ubuntu 16.04

### Reproducible on current release:
Current repository stable release

**Comment by scmart** [comment]
Hey bbondy, what sort of further info would you like from me? Are there some logs or something I could gather and send?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.57.17 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

- Able to open Tor window via keyboard shortcuts
- Able to open Tor window via profile menu
