### ISSUE TITLE
Brave Talk not recognizing when rewards is enabled, because Greaselion precondition not met

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#17914]
## Description 
For certain internal users, even when they have Brave Ads enabled, the ads enabled precondition in the associated Greaselion script is not triggering.  We have tested this by putting in a separate simple script that alerts with the same precondition.  On installs unaffected, the alert triggers, but not on affected installs.

More information here: https://github.com/brave/brave-together/issues/215

## Steps to Reproduce
~Currently unknown, we have been unable to reproduce this from a fresh install.  But some internal users with existing installs have profiles that reliably reproduce this.  It is worthwhile to note that when the ads enabled slider is cycled off and on, this precondition, along with all other Greaselion enabled rewards functionality, starts to work.  But this work around does not survive a browser restart.~

1. Start with clean profile
1. Start Brave, enable Ads
1. Create a second profile, don’t enable Ads
1. Restart Brave and select the first profile with Ads enabled
1. Go to beta.talk.brave.com and “Start Call”

## Actual result:
You will see the pop up complaining you don’t have Ads

## Expected result:
Start Call should work as expected

## Reproduces how often: 
Often for affected profiles.

## Brave version (brave://version info)
1.29.77

## Version/Channel Information:
Release 

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Unknown
- Can you reproduce this issue with the nightly channel? Unknown

**Comment by emerick** [comment]
The rewards service isn't waiting for Greaselion to fire `OnRulesReady` before it starts calling `SetFeatureEnabled` to install Greaselion extensions. It's probably a timing-related issue that mostly worked before but stopped working now that Brave pops up a profile picker on startup when there are multiple profiles. The fix is to call `SetFeatureEnabled` only after `OnRulesReady` fires.

**Comment by emerick** [comment]
Related to https://github.com/brave/brave-together/issues/215.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.29.80 Chromium: 93.0.4577.63 (Official Build) (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

```
- Verified the STR from the description

Confirmed Ads-enabled state was detected and I was able to make a Brave Talk call.

Example | Example | Example | Example | Example | Example
-----| ----|----|---|---|----
![image](https://user-images.githubusercontent.com/38657976/133077485-3f5d3a98-363c-4426-ad94-3affe91ee2d6.png) | ![image](https://user-images.githubusercontent.com/38657976/133077598-fd2b59a2-2d69-427c-b985-e127c816d550.png) | ![image](https://user-images.githubusercontent.com/38657976/133077762-a9c06175-30aa-43b2-9075-e9681a1b2e4e.png) | ![image](https://user-images.githubusercontent.com/38657976/133077921-ac592709-2a47-4551-832d-2aca3784ab89.png) | ![image](https://user-images.githubusercontent.com/38657976/133077978-418ce5d0-c6b4-4daf-8bf9-60e1b8e02fe1.png) | ![image](https://user-images.githubusercontent.com/38657976/133078017-d5491199-34d9-4806-9bff-af9ebf0b8294.png)
