### ISSUE TITLE
Metadata from filter list subscriptions should be available in brave://adblock UI

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#17910]
In addition to https://github.com/brave/brave-browser/issues/17909, there are a number of metadata parameters that can be specified by filter list maintainers (full list at https://help.eyeo.com/en/adblockplus/how-to-write-filters#special-comments). The `Title`, `Homepage`, and `Version` fields should be surfaced to the UI in brave://adblock.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` 
```
Brave | 1.41.55 Chromium: 102.0.5005.115 (Official Build) nightly (64-bit)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

1. Install 1.41.55
2. Launch brave
3. Visit `https://filterlists.com` 
4. Click filter icon on the `Syntaxes` column to select `Adblock Plus` lists. 
5. Click on the `blue (i)` icon for `AakList (Anti-Adblock Killer)`
6. Click `View` button in the info panel to the right.
7. Page opens in a new tab and note down the `Title` or `Homepage`:
    `Title`: `AakList (Anti-Adblock Killer)`
    `Homepage`:` https://github.com/reek/anti-adblock-killer/`
8. Copy the URL `https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt` 
9. Visit `brave://settings/shields/content-filters`
10. Paste above URL in the ` Add custom filter lists` input field
11. Click `Add` button 
12. A new list subscription is created URL is added to `Custom lists` area and shows `Last Updated` time
13. Visit `brave://local-state` 
14. Search for `AakList (Anti-Adblock Killer)` 
15. The new subscription should be listed and the list matches to entry from `https://filterlists.com` 


Step 3|Step 6|Step 7|Step10|Step 12|Step 14&15
---|---|---|---|---|---
<img width="947" alt="Step 3" src="https://user-images.githubusercontent.com/98358127/173162126-f0e463fa-3abd-491a-b95c-0e5c3501b2d9.png">|<img width="947" alt="Step 6" src="https://user-images.githubusercontent.com/98358127/173162163-ad87d397-e933-4a9d-85c8-9f8989e0d4db.png">|<img width="947" alt="Step 7" src="https://user-images.githubusercontent.com/98358127/173162375-efe2e0b3-134d-438b-a867-4ec56a8adf8d.png">|<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/173162505-71f3a1e2-3103-4619-88c0-ceea7784040c.png">|<img width="943" alt="image" src="https://user-images.githubusercontent.com/98358127/173162517-22e92941-e035-472c-8969-096a0b637da5.png">|<img width="947" alt="Step 15" src="https://user-images.githubusercontent.com/98358127/173162803-f95d583a-382b-435b-9391-36fc7427f9a3.png">

**Comment by stephendonner** [comment]
## Verification `PASSED` using



Brave | 1.41.62 Chromium: 103.0.5060.42 (Official Build) nightly (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 11.6.7 (Build 20G630)

### Steps:
1. Install 
2. Launch brave
3. Visit `https://filterlists.com` 
4. Click filter icon on the `Syntaxes` column to select `Adblock Plus` lists. 
5. Click on the `blue (i)` icon for `AakList (Anti-Adblock Killer)`
6. Click `View` button in the info panel to the right.
7. Page opens in a new tab and note down the `Title` or `Homepage`:
    `Title`: `AakList (Anti-Adblock Killer)`
    `Homepage`:` https://github.com/reek/anti-adblock-killer/`
8. Copy the URL `https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt` 
9. Visit `brave://settings/shields/content-filters`
10. Paste above URL in the ` Add custom filter lists` input field
11. Click `Add` button 
12. A new list subscription is created URL is added to `Custom lists` area and shows `Last Updated` time
13. Visit `brave://local-state` 
14. Search for `AakList (Anti-Adblock Killer)` 
15. The new subscription should be listed and the list matches to entry from `https://filterlists.com` 


Step 3 | Step 6 | Step 7 | Step 12 | Step 14 & 15
---|---|---|---|---
<img width="1263" alt="Screen Shot 2022-06-14 at 1 45 10 PM" src="https://user-images.githubusercontent.com/387249/173686396-cea061fd-b138-4cf4-b416-9382d2574675.png"> | <img width="1217" alt="Screen Shot 2022-06-14 at 1 51 58 PM" src="https://user-images.githubusercontent.com/387249/173686552-56b1285e-6004-4d3f-92e7-2a3ed522ea23.png"> | <img width="1263" alt="Screen Shot 2022-06-14 at 1 45 40 PM" src="https://user-images.githubusercontent.com/387249/173686607-d68f68b5-82a4-484a-a07b-8b8d0dc4e454.png"> | <img width="1263" alt="Screen Shot 2022-06-14 at 1 46 53 PM" src="https://user-images.githubusercontent.com/387249/173686708-3aa163d6-eb6f-4340-9053-d556c6a9e855.png"> | <img width="1217" alt="Screen Shot 2022-06-14 at 1 48 06 PM" src="https://user-images.githubusercontent.com/387249/173686925-6e026854-fec0-430b-87d5-340831a10164.png">
