### ISSUE TITLE
Crash when clicking Chromecast button on YouTube video player

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#17919]
## Description 
Reported by @faheem-nadeem. Crash report available at:
https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3Ddf0a1400-f6ca-e506-0000-000000000000)&debug=(%2227939e7%22,0,0)

## Steps to Reproduce

   1. Visit YouTube
   2. Play a video
   3. Click the Chromecast button (on the YouTube player; in bottom right hand corner of player)
       ![image](https://user-images.githubusercontent.com/4733304/132415213-95ac811c-db68-4175-9506-6bb6ddb9c982.png)

## Actual result:
See screen recording here (thanks @faheem-nadeem)
https://user-images.githubusercontent.com/4733304/132414865-d93128bc-5280-411f-831f-c8d81e69d6ff.mov

## Expected result:
Shouldn't crash

## Reproduces how often: 
100%

## Brave version (brave://version info)
`Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (x86_64)`
macOS Big Sur 11.5.2 (20G95) on Intel hardware

## Version/Channel Information:
- Can you reproduce this issue with the current release? y
- Can you reproduce this issue with the beta channel? unknown
- Can you reproduce this issue with the nightly channel? unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? unknown
- Does the issue resolve itself when disabling Brave Rewards? unknown
- Is the issue reproducible on the latest version of Chrome?  no; tested on Chrome `Version 93.0.4577.63 (Official Build) (x86_64)`

**Comment by bsclifton** [comment]
Should be fixed by https://github.com/brave/brave-core/pull/9987

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.5.2 x64` using the following build:

```
Brave | 1.29.80 Chromium: 93.0.4577.63 (Official Build) (x86_64)
--- | ---
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)
```

* enabled `Media Router` via `brave://settings/extensions`
* visited https://www.youtube.com/watch?v=ySBzSEYvLuU
* clicked on the `Cast` icon via the video and ensured that Brave doesn't crash

<img width="1819" alt="Screen Shot 2021-09-13 at 1 29 03 PM" src="https://user-images.githubusercontent.com/2602313/133130106-8b65c0d4-8c02-4035-b83d-c08265bb01c9.png">
