### ISSUE TITLE
favicons not loading correctly when enabling rewards via the panel

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1792]
## Description 

When enabling rewards via the `BAT` panel located in the URL while on a website, the wrong favicon source will be used. Example:

Using:

<img width="523" alt="screen shot 2018-10-23 at 1 07 24 am" src="https://user-images.githubusercontent.com/2602313/47337014-08f0bf80-d660-11e8-8974-3aff5dbae65c.png">

Instead of:

<img width="511" alt="screen shot 2018-10-23 at 1 08 29 am" src="https://user-images.githubusercontent.com/2602313/47337035-2e7dc900-d660-11e8-90cc-e8cc78c3ee73.png">

Which will result in the following:

<img width="409" alt="screen shot 2018-10-23 at 1 12 37 am" src="https://user-images.githubusercontent.com/2602313/47337147-c8de0c80-d660-11e8-902c-d6b5243925d1.png">

## Steps to Reproduce

   1. launch `0.55.20 Chromium: 70.0.3538.67` using a brand new profile
   2. visit wsj.com and enable rewards via the `BAT` icon in the URL
   3. once enabled and the wallet is created, open a new tab and load ft.com
   4. click on the `BAT` icon in the URL while on ft.com (you'll see the favicon)
   5. switch back to the wsj.com tab and click on the `BAT` icon in the URL (favicon missing)

Now if you visit `brave://rewards` and refresh the wsj.com tab, the favicon will appear.

## Actual result:

![faviconrewardpanel](https://user-images.githubusercontent.com/2602313/47337070-5a994a00-d660-11e8-8e15-0d6eb250a715.gif)

## Expected result:

Favicons should be loading within the `Rewards` panel via the URL without any issues

## Reproduces how often: 

100% reproducible using the above STR

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, currently reproducible on `dev` and `beta`.

### Additional Information

@NejcZdovc mentioned that this might be fixed once https://github.com/brave/brave-browser/issues/1719 has been addressed. Once https://github.com/brave/brave-browser/issues/1719 has been fixed, we'll need to go through the following and ensure that this case as been addressed as well.

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows



**ft.com:**

![image](https://user-images.githubusercontent.com/38657976/47570639-4a30ea00-d954-11e8-8ab9-0bb1ad745aa2.png)

**Twitch**

![image](https://user-images.githubusercontent.com/38657976/47570709-72b8e400-d954-11e8-9042-24746589e452.png)
