### ISSUE TITLE
brave notifying users there's a grant available even though there's none available

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1793]
## Description 

When we were testing https://github.com/brave/brave-browser/issues/1350 tonight, several internal employees including myself started running into CAPTCHA issues. We couldn't complete the CAPTCHA and figured the fix wasn't working. However, @evq mentioned that the server ran out of grants so there weren't any to accept.

We shouldn't be notifying issues when there's no grants available.

## Steps to Reproduce

We'll need to create a scenario on staging where there's no more grants available. Launching brave with a new profile in this scenario shouldn't notify the user that there's grants available.

* ensure that the above scenario is setup (most likely on staging)
* install brave and enable rewards (you shouldn't be seeing any notifications)
* add more grants to the backend
* restart brave with a new profile and ensure that the notifications are now being displayed

## Actual result:

Being notified that there's a grant available even though the server has ran out of grants.

## Expected result:

Users shouldn't be notified about grants if there's none left on the server.

## Reproduces how often: 

Assuming it's 100% as @mandar-brave @yrliou @jenn-rhim and myself reproduced the issue over and over again.

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Additional Information

CCing @evq

**Comment by evq** [comment]
fixed in https://github.com/brave-intl/bat-ledger/pull/422

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.9 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified STR from description
