### ISSUE TITLE
Miscalculation for total gas for a transaction

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17936]
## Description 

There is a miscalculation for total gas for a transaction. As per design it is supposed to be 
```
Max Fee Per Gas  X  Gas Limit
```
however for some transactions it is 
```
Max Fee Per Gas  X Gas Used
```

## Steps to Reproduce

   1. Submit a Type 2 transaction
   2. Check the transaction details to calculate fees

## Actual result:

As per this [transaction](https://etherscan.io/tx/0x6927b5a8eb8428737b7125063195d1e8d08ceb39319fd063e9657bb13b28e54d) ,

Max Fee Per Gas: 0.000000084365458386 Ether (84.365458386 Gwei)
Gas Limit: 77,760
Gas Used by Transaction: 47,040 (60.49%)

So as per design logic total gas fee should be `0.006560258` which is wrong 
```
Max Fee Per Gas(0.000000084365458386) x Gas Limit(77,760) =  Total Gas Fee ( 0.006560258)
```
In fact it is `0.003968551` which is much closer to `Transaction Fee:0.00389521291539744` shown on Etherscan and on UI
```
Max Fee Per Gas(0.00000008436545838) X Gas Used by Transaction (47,040) =  Total Gas Fee (0.003968551 )
```
![image](https://user-images.githubusercontent.com/17010094/132497730-75b7953d-d16b-40e7-8184-a532f54db305.png)

## Expected result:
Proper calculation of gas fee 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Component : `1.0.37 Dev`

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Logic works fine when `Gas Used by Transaction` is same as `Gas Limit` but it fails when `Gas Used by Transaction` **is less than** `Gas Limit`

**Comment by onyb** [comment]
There is a small nuance here. Since the "Transaction submitted with gas fee ..." entry in the "Activity Log" is displayed even before the transaction is mined, the fees is shown as a best guess (hence, `Max Fee Per Gas  X  Gas Limit`), since we actual gas consumption cannot be accurately predicted before inclusion in the blockchain.

However, the "Total" field under transaction details must reflect `Max Fee Per Gas  X  Gas Used`.

Propose resolution as non-issue.

**Comment by srirambv** [comment]
@onyb  this is fine for an actual transaction that happens with less gas than estimated(max). Would this still hold good if you try to speed up the transaction? Wouldn't that be a best guess estimate as well?

**Comment by onyb** [comment]
Even if you speed up a transaction, the actual gas used may be quite different. We only bump the max priority fee per gas, not the gas limit. Does that answer your question?

**Comment by srirambv** [comment]
> Even if you speed up a transaction, the actual gas used may be quite different. We only bump the max priority fee per gas, not the gas limit. Does that answer your question?

This sounds good. Going to close the issue as won't fix
