### ISSUE TITLE
Change "`x` BAT arriving in `y` days" text to emphasize that payouts will begin by that time

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17943]
## Description

Currently, we say "2.1 BAT arriving in 3 days" messaging upon a new month. However, payout team usually only _starts_ payout processing on that date, and payouts (especially to verified users) can take a couple days to all process due to transaction times on various exchanges/custodians. We should change text to reflect this, as there is still user confusion.

OR, the payout team can adjust payout date to catch the end/completion of payouts. However, some users will see this messaging even though they've already received their payout (since transactions are sequentially processed). cc: @aekeus 

![image](https://user-images.githubusercontent.com/11497541/132545099-834e384d-0258-4adb-9eb7-244f56bba138.png)

## Solution

Main message: Your X BAT payout will begin processing in Y Days.
Subtext (fine print): Note: It can take a few days for the payout to process and your BAT to arrive.

![image](https://user-images.githubusercontent.com/11497541/134052469-98fc8891-fc0a-423b-bd2a-15f3c763e509.png)

cc: @jonathansampson

**Comment by Miyayes** [comment]
Main message: Your X BAT payout will begin processing in Y Days.
Subtext (fine print): Note: It can take a few days for the payout to process and your BAT to arrive.

**Comment by rmcfadden3** [comment]
Per sidebar in Slack, here's our winner:

**Main message**: Your X BAT payout will begin processing in Y Days.
**Subtext (fine print)**: Note: It can take a few days for the payout to process and your BAT to arrive.

**Comment by Miyayes** [comment]
![image](https://user-images.githubusercontent.com/11497541/134052450-08f676e3-b7af-4d07-be7f-f00c283187d1.png)

**Comment by emerick** [comment]
@Miyayes Do we want to skip the "fine print" note on the Rewards widget version? Seems like it will get cramped there, but let me know.

**Comment by Miyayes** [comment]
@emerick Good point. We can skip it for now, especially as Kevin will be reworking Rewards NTP Widget v2. Will keep an eye out on user feedback.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.32.74 Chromium: 95.0.4638.54 (Official Build) dev (x86_64)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | macOS Version 11.6 (Build 20G165)

### Steps:
1. new profile
2. launched Brave
3. enabled Rewards
4. viewed some ads
5. opened `brave://rewards` and noted the `Next payment date`
6. shut down Brave
7. time traveled to 3 days before the payout date
8. reopened `brave://rewards` and a new-tab page
9. confirmed messaging changes:

`brave://rewards`:
```
Your +0.03 BAT payout will begin processing in 3 days.
Note: It can take a few days for the payout to process and your BAT to arrive.
```

New-tab page:
```
Your +0.03 BAT payout will begin processing in 3 days.
```

`brave://rewards` | new-tab page
---------|---------
<img width="1312" alt="Screen Shot 2021-11-02 at 3 35 56 PM" src="https://user-images.githubusercontent.com/387249/138000772-c21e85a7-fa93-413e-98b2-0b515517ee72.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 3 36 00 PM" src="https://user-images.githubusercontent.com/387249/138000778-49cbe43b-005a-4083-88de-766981154d19.png">
