### ISSUE TITLE
Garbage-collection sweep doesn't work

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17948]
## Description 

Garbage-collection sweep doesn't work

## Steps to Reproduce

   1. new profile
   2. load `ipns://en.wikipedia-on-ipfs.org`
   3. click on `Use a local node`
   4. load `brave://ipfs-internals`
   5. click on the `Perform a garbage collection sweep` button
   6. note the before and after values for `Objects` and `Size`

## Actual result:

`Objects` and `Size` don't decrease, under `Repo Stats`; I don't see anything logged to Terminal/console, either

![garbage-collection](https://user-images.githubusercontent.com/387249/132560799-d77e8a46-051e-4014-a5ae-2f6af973892b.gif)

## Expected result:
`Objects` and `Size` should both decrease, under `Repo Stats`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.31.26 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)

/cc @spylogsster

**Comment by spylogsster** [comment]
works well for me, @stephendonner please try to surf more sites to increase cache size before sweep

**Comment by stephendonner** [comment]
> works well for me, @stephendonner please try to surf more sites to increase cache size before sweep

Thanks; I went from `209` object to `6` just fine, so will close out.
