### ISSUE TITLE
Handle different return results when doing grant captcha 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1794]
Server returns this errors when you do grant captcha

```
403 Unauthorized - Client has failed captcha
404 Not Found - Promotion or wallet specified do not exist
410 Gone - No more grants are available for this promotion
422 Bad Data - Malformed client request, should not be retried
```

We should handle all of them. Currently we only handled 402.

For 404 and 410 we should display error that grant ended and provide button to close (action is the same as pressing X). It should also remove claim banner at the top.

When you get 422 we should display error and say please try claiming again later. There should be ok button that do the same as close button in previous scenario.

**Comment by NejcZdovc** [comment]
cc @brad @davidtemkin for text for both new screens

**Comment by srirambv** [comment]
Verification passed on 


Brave | 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux

* Verified steps from https://github.com/brave/brave-core/pull/721
![image](https://user-images.githubusercontent.com/17010094/47660957-82ac1000-db6e-11e8-9361-c972e35c64f1.png)
