### ISSUE TITLE
Add publisher status hover note to Rewards panel

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#17941]
If the displayed publisher is unverified, or their verified account does not match the user's external wallet type (for users that have connected an external wallet), then display a hover note with an explanation.

<img width="323" alt="Screen Shot 2021-09-08 at 11 39 22 AM" src="https://user-images.githubusercontent.com/5995084/132540996-2ed2ba23-3673-48bf-af01-446002514692.png">

**Comment by stephendonner** [comment]
Setting QA/Blocked until https://github.com/brave/brave-core/pull/10224 is merged in to 1.31.x

**Comment by LaurenWags** [comment]
labelling `QA/Blocked` until uplift to 1.31.x is completed

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-core/pull/10181 was uplifted into `1.31.x` via https://github.com/brave/brave-core/pull/10224.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.31.67 Chromium: 94.0.4606.61 (Official Build) beta (64-bit)
-- | --
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | Windows 10 Version 21H1 (Build 19043.1237)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/10181

<details>
<summary>Case 1: Not registered</summary>


</details>

<details>
<summary>Case 2: Registered but not verified</summary>


</details>

<details>
<summary>Case 3: Verified and user is not connected</summary>


</details>

<details>
<summary>Case 4: Verified with non-matching wallet provider</summary>


</details>

<details>
<summary>Case 5: Verified with matching wallet provider</summary>


</details>
