### ISSUE TITLE
verified icon not appearing for verified YT channels

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1795]
## Description 

Verification icons not appearing for verified YT channels: Examples:

```
["youtube#channel:UClFSU9_bUb4Rc6OYfTt5SPw",true,false,{}] <-- Philip DeFranco
["youtube#channel:UCazMm3tOCkYrIGE_17j0mVg",true,false,{}] <-- Bart Barker
```
Both of the above channels are verified but don't have the verified icons displayed:

<img width="634" alt="screen shot 2018-10-23 at 2 20 01 am" src="https://user-images.githubusercontent.com/2602313/47339915-ae109580-d66a-11e8-915d-6be1d3afb049.png">

## Steps to Reproduce

   1. launch `0.55.20 Chromium: 70.0.3538.67` and enable rewards
   2. visit https://www.youtube.com/channel/UCazMm3tOCkYrIGE_17j0mVg and watch a video
   3. visit https://www.youtube.com/channel/UClFSU9_bUb4Rc6OYfTt5SPw and watch a video
   4. visit `brave://rewards` and you'll notice both entires are not displaying the verified icon

## Actual result:

Verified YT channels are not displaying the verified icons

## Expected result:

Verified YT channels should be displaying verified icons

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, reproducible under `dev` & `beta`.

### Additional Information

CCing @jenn-rhim

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

<img width="628" alt="screen shot 2018-10-26 at 11 03 45 am" src="https://user-images.githubusercontent.com/2602313/47575059-28614400-d90f-11e8-9566-749e1b0f1bdc.png">

**Comment by jnki** [comment]
i have just updated to Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)

there is still no way to tip directly to publisher for me.

this is all that shows up in the panel:
![image](https://user-images.githubusercontent.com/17442109/48281874-ed532a80-e44f-11e8-955c-51ada2da0b10.png)
