### ISSUE TITLE
`Invalid gateway address` message is shown when `https://localhost:{any port}` is set in IPFS gateway

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#17966]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/16999

## Steps to Reproduce

   1. Clean profile 1.30.68
   2. launch Brave
   3. load `brave://settings/ipfs`
   4. click on the `Change` button
   5. enter `https://localhost:48083` and click `Submit`

  
## Actual result:

`Invalid gateway address` error message is returned.

![image](https://user-images.githubusercontent.com/38657976/132683734-48fb261f-cbb6-4f51-9049-d180bb9f227e.png)

## Expected result:

It should work as it works in `1.29.79`

![image](https://user-images.githubusercontent.com/38657976/132684160-44f141ed-2af9-4ab7-be8e-64bed88a295a.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.30.68 Chromium: 93.0.4577.63 (Official Build) beta (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @spylogsster

**Comment by spylogsster** [comment]
@GeetaSarvadnya we check what will that gateway respond for predefined ipfs url, if it has wrong response we alert it as invalid, so to setup localhost url that localhost should resolve ipfs correctly, more details here https://github.com/brave/brave-browser/issues/16999
