### ISSUE TITLE
Exclude / Include don't work when publisher is not in the ac table

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1797]
## Steps to Reproduce

   1. enable rewards
   2. open new tab
   3. click on panel
   4. try to toggle include/exclude

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/734
