### ISSUE TITLE
Enable media router by default on android

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#17972]
## Description 
This issue disabled media router by default for all platforms - https://github.com/brave/brave-browser/issues/17873 - It should be enabled by default on Android.

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/10020

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.29.80 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/10020
- Verified cast option shows up on link 
- Verified clicking on cast button tries to search for devices and not crash the browser
- Verified on clean install and upgrade and works fine

![image](https://user-images.githubusercontent.com/17010094/133048355-c35a8e14-bc6a-499e-a557-8907952dc838.png)| ![image](https://user-images.githubusercontent.com/17010094/133046823-31342ad2-b766-4ee8-80c0-187e4cd3e92b.png)
-- | --

---------
Verification passed on Samsung Tab A with Android 10 running 1.29.80 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/10020
- Verified cast option shows up on link 
- Verified clicking on cast button tries to search for devices and not crash the browser
- Verified on clean install and upgrade and works fine

![image](https://user-images.githubusercontent.com/17010094/133048098-8976aebc-892c-4863-a838-eb8590d6019e.png) | ![image](https://user-images.githubusercontent.com/17010094/133048146-026ac8b3-fa4a-44ed-961f-773d91bdc9ab.png)
-- | --
