### ISSUE TITLE
Add "on {{platform}}" in Rewards tipping panel 2.0

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17976]
## Description

In the new Rewards panel 2.0, there is no "on Github" or "on YouTube" after the channel name as there is in the original panel. Perhaps we should add it? cc: @codybanxs. 

![image](https://user-images.githubusercontent.com/11497541/132729241-6bf61218-3f99-4cbc-898d-cfd49549d032.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.37 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. new profile
2. enabled Rewards
3. went to the sites listed
4. for each, clicked on the BAT icon in the URL bar

Confirmed each attributed Twitter, GitHub, YouTube, and Vimeo correctly; included DuckDuckGo.com just to show what happens currently, in that case.

twitter | github | vimeo | duckduckgo | youtube
---------|----------|---------|----------|----------
<img width="1312" alt="Screen Shot 2021-09-13 at 15 53 18" src="https://user-images.githubusercontent.com/387249/133167548-5d4482f7-e21e-4974-9a5d-e9e931069ce4.png"> | <img width="1312" alt="Screen Shot 2021-09-13 at 15 53 47" src="https://user-images.githubusercontent.com/387249/133167550-b8dfbf1a-3a37-47cd-8305-63607e5fe3a8.png"> | <img width="1312" alt="Screen Shot 2021-09-13 at 15 53 59" src="https://user-images.githubusercontent.com/387249/133167551-a2903a48-8139-4d75-bf7c-9050f75abcba.png"> | <img width="1312" alt="Screen Shot 2021-09-13 at 15 54 06" src="https://user-images.githubusercontent.com/387249/133167552-ae745509-294e-4e76-8f57-ca170b4d4ce7.png"> | <img width="1312" alt="Screen Shot 2021-09-13 at 15 55 03" src="https://user-images.githubusercontent.com/387249/133167553-5e3986c1-8ebb-4641-92a5-ebb926f1ca89.png">
