### ISSUE TITLE
Add Ledger support in the new wallet

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#17971]
The hardware wallet UI is already built out https://github.com/brave/brave-core/pull/9614

- We calculate device id for each ledger device as "Ledger + hash(address on zero index)" to be able to indentify device in future and keep devices metadata(customised names)
- Devices organised as separate keyrings In preferences like:
```
keyrings: {
   "hardware":  {
     "Ledger12445": {
         "account_metas": {
            "0xEA04...CC8Acc": {
              "account_name": "Ledger 1",
              "derivation_path": "m/44'/60'/1'/0/0",
           },
           "0x264Ef...6b8F1": {
              "account_name": "Ledger 2",
              "derivation_path": "m/44'/60'/2'/0/0",
            }
         },
         device_name: "Ledger 123"
     },
     "Ledger44332":{
      ...
     }
   }
}
```
- Update device permissions dialog to be able to make requests from panel

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.86 Chromium: 95.0.4638.54 (Official Build) beta</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.194)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10169>brave/brave-core#10169</a></li>
         <li>Verified able to connect Ledger Nano S and perform a transaction successfully</li>
        </ul>
      </td>
   </tr>
</table>
