### ISSUE TITLE
Add more hover states to Rewards Panel UI 2.0

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17974]
## Description

* Send Tip
* Verify wallet

Currently do not have hover states in the Rewards Panel 2.0 design. We should consider adding hover states to make everything feel more reactive and clickable in UX. 

![image](https://user-images.githubusercontent.com/11497541/132720931-4cb9efca-5cdd-4b51-ab8f-296c023b2938.png)

**Comment by LaurenWags** [comment]
labelling `QA/Blocked` until uplift to 1.31.x is completed

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.31.70 Chromium: 94.0.4606.71 (Official Build) beta (x86_64)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | macOS Version 10.15.7 (Build 19H1417)
```

See testing notes under https://github.com/brave/brave-browser/issues/18341#issuecomment-933506070
