### ISSUE TITLE
If amount is 0.0 BAT in Rewards panel summary view, do not show negative sign

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17973]
## Description

In Rewards Panel 2.0, if amount is 0.0, perhaps we shouldn't show a negative sign. It makes sense since these _would be_ debits, but it looks a little scarier than just 0.0.

![image](https://user-images.githubusercontent.com/11497541/132720683-2a868a01-4497-4826-8ef2-581ff162b362.png)

cc: @codybanxs

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.37 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.6 (Build 20G165)

Confirmed no `-` sign when values are `0.00` .

<img width="1312" alt="Screen Shot 2021-09-13 at 16 04 38" src="https://user-images.githubusercontent.com/387249/133169227-1f18cdab-2446-489b-ad28-2914e5f31817.png">
