### ISSUE TITLE
Can't Install Brave on iOS 12.5.4

### ISSUE THREAD

**Issue by TexanScot** [brave/brave-browser#17970]
## Description 
Attempt to install Brave from ios App Store to older iPad running ios 12.5.4 unsuccessful. Error message states that ios 13 is required to run 'this' version of Brave. However hardware on the older iPad does not support any version of ios above 12.5.4. 

Does this imply that Brave is not compatible with older iPad's that cannot run the latest version of the operating system? If not, where would I find (compiled) versions of the app that can be installed on an older iPad.

**Comment by rebron** [comment]
cc: @anthonypkeane

**Comment by srirambv** [comment]
The lowest version that is supported for new updates is iOS 13.  App store will download the last supported version of Brave on your iOS 12 device but that would not receive any updates in future so essentially you will be using a very old, outdated version of Brave. To have the latest Brave version you need to be on a device that supports iOS 13 and higher.
