### ISSUE TITLE
speedreader titles are being cut short

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#17983]
We handle description truncation naively. Ensure that we don't mistake sentence terminators with common abbreviations.

Reported by @janypiotrowski for this site. Getting cut off on U.S. https://www.usnews.com/news/national-news/articles/2021-08-30/the-war-in-afghanistan-ends-where-it-started

**Comment by keur** [comment]
### Test Plan

Ensure the description on the above site isn't truncated mid-sentence.

**Comment by stephendonner** [comment]
@brave/legacy_browser-laptop can also use https://www.sfgate.com/hawaii/article/Hawaii-Haiku-Stairs-removal-advances-Honolulu-16449522.php?IPID=SFGate-HP-CP-Spotlight to test

<img width="1312" alt="Screen Shot 2021-09-10 at 6 40 42 PM" src="https://user-images.githubusercontent.com/387249/132932174-c2c39df2-8497-4b28-a3e4-8ebddcb34a68.png">

**Comment by stephendonner** [comment]
@keur the above two sites: do they have the same issue or a different issue?  They're not fixed, and I'm not sure if they should be here, or if I should file a new issue; thanks!

**Comment by keur** [comment]
@stephendonner the SFGate is behaving actually as expected. If you view source on it and search for `meta name="description"`, they provide the description with the ellipsis. For the variety article the same is true, but there are some shorter titles which we should preference. I'll create the followup for that.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.37 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:
1. new profile
2. launched Brave
3. loaded `https://www.usnews.com/news/national-news/articles/2021-08-30/the-war-in-afghanistan-ends-where-it-started`
4. enabled Speedreader mode

Confirmed the summary text beneath the title is all intact, now.

before fix | after fix
----------|---------
![image](https://user-images.githubusercontent.com/387249/133160887-b577b004-5241-46cd-a49d-3def34e2975e.png) | <img width="1312" alt="Screen Shot 2021-09-13 at 2 43 41 PM" src="https://user-images.githubusercontent.com/387249/133160926-12075615-b623-403a-97e1-c0a71f1a7495.png">
