### ISSUE TITLE
Ensure Ethereum provider option in brave://wallet settings works correctly with MM and Crypto Wallets

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#17984]
This still needs to be checked, but I don't think it works correctly currently.
- If a user installs MetaMask, that should become the Dapp provider and we shouldn't try to inject window.ethereum unless the user explicitly selects us later.
- If a user selects Crypto Wallets explicitly we shouldn't be the window.ethereum provider as well
- If the user uninstalls MetaMask, we should set Brave Wallet as the Dapp provider

**Comment by bbondy** [comment]
cc @jamesmudgett

**Comment by srirambv** [comment]
Removed Android label for now
