### ISSUE TITLE
Check grant in panel

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1798]
We should check for grant when you open panel / create wallet via panel.

**Comment by NejcZdovc** [comment]
should be done in combination with https://github.com/brave/brave-browser/issues/1783

**Comment by rebron** [comment]
Due to @NejcZdovc on combo with #1783 moving to .56.x - beta milestone.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

- Logged #1798 as follow up to reduce the annoyance of showing the notification each time
