### ISSUE TITLE
Implement eth_sign and related functions for signging

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#17986]
eth_sign <- we should add a warning for this because it can be used to sign transaction
personal_sign
signTypedData / signTypedData_v1
signTypedData_v3
signTypedData_v4

**Comment by darkdh** [comment]
signTypedData will be implemented in 
https://github.com/brave/brave-browser/issues/17986

UI integration will be in https://github.com/brave/brave-browser/issues/18660
