### ISSUE TITLE
Something is wrong when opened this link.

### ISSUE THREAD

**Issue by iam-frankqiu** [brave/brave-browser#17997]
## Description 

 When I using this website to watch some videos, It showed that hadn't been supported with the brave browser.

## Reproducing link

  https://v.qq.com/x/cover/vqeduf4egjyrc8w.html

**Comment by ryanbr** [comment]
There is a geo block, getting similar errors on other browsers. (Edge and Chrome below). Brave got the same error @iam-frankqiu  Could be more of a generic error message
![qq-screenshot](https://user-images.githubusercontent.com/1659004/179653419-0e8be144-c428-4742-8af3-53eb1d4ff514.png)
