### ISSUE TITLE
Hide Wallet apps tab and star icon in the panel since it won't be for MVP

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#17998]
1) Hide Apps in both the `Panel` and `Page`
2) Disable `Buy` and `Swap` tabs in the `Panel` if the selected network is not supported.
3) Add a tooltip to say `Network not supported` when hovering over disabled `tabs`

**Comment by srirambv** [comment]
> 2. Disable Buy and Swap tabs in the Panel if the selected network is not supported.

Can these be hidden instead of disabled? cc: @jamesmudgett

**Comment by jamesmudgett** [comment]
@srirambv see https://github.com/brave/brave-browser/issues/18004
