### ISSUE TITLE
Add more details about the fingerprinting techniques

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1799]
We have a brief documentation about what we block to prevent fingerprinting. Adding more details about how the APIs are used for fingerprinting would help useful. 

https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode

**Comment by srirambv** [comment]
@jumde  created wiki on b-c https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode

**Comment by jumde** [comment]
This still lacks details about why certain APIs are blocked, how the APIs can be used for fingerprinting.

**Comment by tomlowenthal** [comment]
Probably this content should live on @Brave-Matt's public knowledge-base, right?

**Comment by tomlowenthal** [comment]
We should probably migrate all this documentation from `browser-laptop`'s wiki to this repo's. We should also make sure that we have plenty of detail about *why* we've implemented particular protections.

**Comment by tomlowenthal** [comment]
Correction: the wiki page is already [here](https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode). Time to:
- [ ] add some _why_s to this
- [ ] make a public-facing version of this for the knowledge-base

**Comment by pes10k** [comment]
fixed with https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
