### ISSUE TITLE
`brave://flags/#copy-link-to-text` should be disabled by default

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#17994]
## Description 
There is no reason `brave://flags/#copy-link-to-text` to remain enabled by default since the `Copy link to highlight` feature isn't available in Brave due to concerns shared by @pes10k over here - https://github.com/WICG/scroll-to-text-fragment/issues/76.

## Steps to Reproduce

   1. Select a random text.
   2. Right-click on it and select `Copy link to highlight`.
   3. Enter the copied link in the address bar to visit that specific section of the page.

## Actual result:

Nothing, the feature isn't available in Brave.

## Expected result:
The created link should send users to the specific highlighted section of the page.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

<html>
<body>

Brave | 1.29.79 Chromium: 93.0.4577.63 (Official Build) (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

<html>
<body>

Brave | 1.30.68 Chromium: 93.0.4577.63 (Official Build) beta (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

<html>
<body>

Brave | 1.31.30 Chromium: 93.0.4577.63 (Official Build) nightly (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
cc: @pes10k @mkarolin

**Comment by pes10k** [comment]
no argument from me.  If all thats needed here is to remove the UI-facing parts of the feature, that sounds 👍 to me.

Just to make sure there is no misunderstanding though, this is only about making the UI match the behavior, and not changing the behavior

**Comment by Tonev** [comment]
> no argument from me. If all thats needed here is to remove the UI-facing parts of the feature, that sounds  to me.
> 
> Just to make sure there is no misunderstanding though, this is only about making the UI match the behavior, and not changing the behavior

Correct. I only suggest the removal of the UI part of the feature as long as the feature isn't available in Brave. 

Right now, the default value of `brave://flags/#copy-link-to-text` is enabled, but at the same time the feature itself is missing in Brave, which makes the default enabled state meaningless.

**Comment by mkarolin** [comment]
**QA STR:**
1. Start Brave
2. Navigate to any site
3. Select some text on the page (that's not a link)
4. Right-click to get the context menu

_Observe:_
Menu has an item "Copy link to highlight"

_Expected result:_
Menu does not have an item "Copy link to highlight"

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.31.50 Chromium: 94.0.4606.50 (Official Build) nightly (64-bit)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | Windows 10 Version 21H1 (Build 19043.1165)

```
- Verified the STR from https://github.com/brave/brave-browser/issues/17994#issuecomment-920034357

Reproduced the issue in `1.29.x`
![image](https://user-images.githubusercontent.com/38657976/133797892-43385024-d8aa-4641-80f4-707eca41f912.png)

Confirmed menu doesn't have an item "Copy link to highlight" when text is selected on the website
![image](https://user-images.githubusercontent.com/38657976/133798123-139e0ddf-d5dd-4fe7-8f2f-28d4b9126655.png)

**Comment by vegerot** [comment]
Why not keep this feature behind a flag?

**Comment by pirate** [comment]
Bumping this as it's an extremely useful feature that I used daily in Chrome, and miss in Brave. I'd love to be able to enable it behind a flag as the minor security risk is easily tolerable for me.

**Comment by ronnie** [comment]
Please re-enable with a flag, I want this too and use it daily.

**Comment by mary-ext** [comment]
Would like this to be brought back, part of what I do on a daily basis is referencing parts of the documentation, where linking to a specific heading isn't enough. The copy highlighted link functionality allows me to highlight the relevant sentence of the things I talk about.

At the very least, can the links not be neutered at least? It's fucking awful that Brave is just stripping them out and not highlighting any of my text that I've referenced with another browser.

**Comment by pirate** [comment]
I've opened a new issue to formally request they re-add this flag: https://github.com/brave/brave-browser/issues/42393

Please comment/vote over there as comments on closed PRs and issues likely wont get seen.
