### ISSUE TITLE
Update bitFlyer promo image in onboarding flow (Sept 2021) 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18001]
## Description

Replace bitFlyer images in onboarding with the following asset.

* The image should link out to: https://twitter.com/bravesoftwarejp
* Use the image asset below:

![image](https://user-images.githubusercontent.com/11497541/132870487-164ea765-41b5-4473-9cca-1a16724f16d7.png)

@soi-tnk

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.80 Chromium: 94.0.4606.50 (Official Build) beta (x86_64)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | macOS Version 11.6 (Build 20G165)


Steps:

1. Clean profile
2. Set OS region to Japan
3. Enabled Rewards
4. Verified that the new bitFlyer image appears at end of onboarding flow
5. Verified that clicking new bitFlyer image opened a new page to `https://twitter.com/bravesoftwarejp`

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-09-17 at 8 27 21" src="https://user-images.githubusercontent.com/387249/133811358-85a6b22e-2605-4204-a38b-c0903ab199c9.png"> | <img width="1312" alt="Screen Shot 2021-09-17 at 8 27 30" src="https://user-images.githubusercontent.com/387249/133811402-5493ff37-b09e-4de5-87e0-54415e4bbe3c.png">
