### ISSUE TITLE
Unable to horizontally scroll long lines of text

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#18008]
## Description 

Unable to horizontally scroll long lines of text

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `https://www.networkworld.com/article/3631415/using-the-linux-set-command.html`
   4. click on the Speedreader/reader-mode icon in the URL bar
   5. look at the long line of code text, and try to horizontally scroll it

## Actual result:

Unable to scroll long lines of non-wrapped text

<img width="1334" alt="Screen Shot 2021-09-09 at 4 41 43 PM" src="https://user-images.githubusercontent.com/387249/132882708-417ad905-c93a-4bec-b805-d6c84bbb2bbf.png">

## Expected result:
Should be able to scroll 

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.31.33 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)

**Comment by keur** [comment]
### Test Plan

Make sure to update the Speedreader component in `brave://components` and ensure this site is no longer affected.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.41 Chromium: 94.0.4606.41 (Official Build) nightly (x86_64)
-- | --
Revision | 333e85df3c9b656b518b5f1add5ff246365b6c24-refs/branch-heads/4606@{#845}
OS | macOS Version 11.6 (Build 20G165)

Steps:

1. new profile
2. launch Brave
3. load `https://www.networkworld.com/article/3631415/using-the-linux-set-command.html`
4. click on the Speedreader/reader-mode icon in the URL bar

Confirmed the text now wraps, and can still be selected/copied, etc.

<img width="1260" alt="Screen Shot 2021-09-14 at 1 42 10 PM" src="https://user-images.githubusercontent.com/387249/133331056-52c68caf-88cd-46f6-be24-655578c6f1f4.png">
