### ISSUE TITLE
Speedreader bylines can sometimes have escaped/encoded text

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#18006]
## Description 

Speedreader bylines can sometimes have escaped/encoded text

## Steps to Reproduce

   1. clean profile
   2. launch Brave
   3. load `https://www.wired.com/2021/09/geeks-guide-final-girls/`
   4. click on the Speedreader/reader-mode icon in the URL bar
   5. look at the byline for the linked article

## Actual result:

`By Geek&#039;s Guide to the Galaxy`

<img width="1312" alt="Screen Shot 2021-09-10 at 8 49 54 AM" src="https://user-images.githubusercontent.com/387249/132881893-94fd49fb-e1c4-4ef8-8f9a-781bfd0c3390.png">

## Expected result:
`By Geek's Guide to the Galaxy`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.31.33 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)

**Comment by keur** [comment]
### Test Plan

Ensure the affected site no longer has an HTML encoded byline.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.35 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 12.0 (Build 21A5506j)

Steps:

1. clean profile
2. launch Brave
3. load `https://www.wired.com/2021/09/geeks-guide-final-girls/`
4. click on the Speedreader/reader-mode icon in the URL bar

Confirmed the byline now reads `By Geek's Guide to the Galaxy` without any encoding.

<img width="1782" alt="Screen Shot 2021-09-12 at 11 01 51 AM" src="https://user-images.githubusercontent.com/387249/132997998-df0fd2a4-ff0e-4ec3-ba32-494044ddb362.png">
