### ISSUE TITLE
Unable to login to the Microsoft Editor extensions

### ISSUE THREAD

**Issue by leodoi3** [brave/brave-browser#18018]
## Description 

I have downloaded the Microsoft Editor extension from the Chrome store, but it has a problem of not keeping me logged in. Each time I open it prompts me to log in, every time. I tried on a clean install. With no help.  Essentially makes this extension unusable. 
## Steps to Reproduce

   1.  Download Microsoft Editor https://chrome.google.com/webstore/detail/microsoft-editor-spelling/gpaiobkfhnonedkhhfjpmhdalgeoebfa
   2.  Log In 
   3.  Click the extension icon
   4. Restart Brave and repeat step 3. 

## Actual result:

It keeps asking me to log in. 

## Expected result:
I should stay logged in. 

## Reproduces how often: 

Easily reproduced
## Brave version (brave://version info)

<html>
<body>

Brave | 1.29.79 Chromium: 93.0.4577.63 (Official Build) (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19042.1165)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@leodoi3 Looks like I was able to login and I'm still logged-in. There's no need restart Brave for Microsoft Editor to show up. When you logged-in to Microsoft Editor which redirects you to live.com, were you able to complete that process?

`https://support.microsoft.com/en-us/office/welcome-to-the-microsoft-editor-browser-extension-9a5ee6c4-f6b7-4b26-bbca-cd38a8b44d6a?ocid=prod_core_neu_oxo_fm_chromestore_bxinstall&ui=en-us&rs=en-us&ad=us#bkmk_assistant`

**Comment by rebron** [comment]
I also closed out my browser and restarted and I'm still logged-in as expected to the Microsoft Editor Extension.
