### ISSUE TITLE
Make backup language in Manage Your Wallet section more custodian neutral 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18014]
## Description

In `Manage Your Wallet > Backup`, it says "we recommend connecting to a verified Gemini wallet." It should say "We recommend **verifying your wallet**." instead, which is more neutral when there are multiple custodial options. 

![image](https://user-images.githubusercontent.com/11497541/132914786-bb652093-b88a-4d79-b3fb-0087be3ae81c.png)

**Reproduces in:** 

v1.29.x
v1.31.x

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.37 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)

Steps:
1. clean profile
2. launch Brave
3. enable Rewards
4. load `brave://rewards`
5. click on `Manage your wallet`
6. look at the text and link for `verifying your wallet`

Confirmed the text change; clicking on `verifying your wallet` loads the `Verifying is optional` info dialog

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-09-13 at 2 29 28 PM" src="https://user-images.githubusercontent.com/387249/133159497-fd06ffe0-bff1-42bd-a1f5-1794a1c47726.png"> | <img width="1312" alt="Screen Shot 2021-09-13 at 2 29 32 PM" src="https://user-images.githubusercontent.com/387249/133159505-6661a48f-5c2a-4338-a865-5a62fd6b34f1.png">
