### ISSUE TITLE
Remove Uphold custom header

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#18015]
We currently send Uphold a custom header `x-brave-partner: uphold` as specified in https://github.com/brave/brave-browser/wiki/Custom-Headers. Uphold should be able to work without this custom header, so we should remove it.

@pes10k 

#### Base test
1. Go to uphold.com
2. Verify that no custom header sent (i.e. `x-brave-partner: uphold`)

#### New Uphold account
(thanks @Miyayes)
1. Remove custom header for Uphold
2. Brave Browser > Brave Rewards > Verify wallet
3. Inside that flow, when prompted to log in/sign up for Uphold, create an account (given you don’t already have one). Note: this will require ID verification. Check if you’re ever taken out of the flow, or the account creation process loses context of the fact that you’re coming through Brave and trying to verify your Brave Rewards wallet
4. When you’re done, see if your Brave Rewards wallet is verified
5. Once verified, press “Withdraw funds” and press “Add funds” buttons on brave://rewards page
6. Disconnect from Uphold, and then link again (just have to log in again)

#### Existing Uphold account
Check if an existing Uphold account still works correctly.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.31.82 Chromium: 95.0.4638.40 (Official Build) beta (x86_64)
-- | --
Revision | e3e7c76ba0284b16087cf4cf3153abfaef6470c7-refs/branch-heads/4638@{#624}
OS | macOS Version 10.15.7 (Build 19H1417)
```

Confirmed that the `x-brave-partner: uphold` is not sent with 1.31.x.
1.30.x | 1.31.x
----- | -----
<img width="937" alt="1 30 x" src="https://user-images.githubusercontent.com/28145373/137024243-50df0ad3-f761-42ad-8e16-9f983061b23e.png"> | <img width="993" alt="1 31 x" src="https://user-images.githubusercontent.com/28145373/137024252-d489c6b8-05c8-459f-ac1f-5b181a99b8b4.png">

Confirmed that existing Uphold account could be linked. Confirmed that balance displayed as expected and I could perform a tip without issue.

Example | Example
----- | -----
<img width="413" alt="Existing1" src="https://user-images.githubusercontent.com/28145373/137024850-58eb83e3-fb77-42d7-b65a-581a98073e4e.png"> | <img width="444" alt="Existing2" src="https://user-images.githubusercontent.com/28145373/137024860-13890a01-7d11-4695-a5ff-886225dc0b53.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.31.86 x64 build
<details>
<summary><code>x-brave-partner</code> Header - <b>PASSED</b></summary>
<br>

- Verified `x-brave-parnter: uphold` header is not sent 

1.30.89 | 1.31.86
-- | --
![image](https://user-images.githubusercontent.com/17010094/137728213-6002de7f-b181-41db-8152-fe0acdd16d7b.png) | ![image](https://user-images.githubusercontent.com/17010094/137728530-8325bc11-0c37-46a6-9f3e-9ba9432654bc.png)

</details>

<details>
<summary>Clean Profile - link existing KYC account - <b>PASSED</b></summary>
<br>

- Verified able to link an existing Uphold account to wallet on a clean install.
- Verified balance is displayed correctly 
- Verified able to perform a tip without any issues

![image](https://user-images.githubusercontent.com/17010094/137847508-1edd3523-dec5-4535-a7a6-4464aed0bb3e.png) | ![image](https://user-images.githubusercontent.com/17010094/137847514-5bd4a96a-3612-4301-b10a-7a61f171df14.png)
-- | --

</details>

<details>
<summary>Upgrade Profile - KYC account linked prior to upgrade - <b>PASSED</b></summary>
<br>

- Verified linking Uphold on 1.30.89 and upgraded to 1.31.86 retained Uphold wallet connection and balance was shown correctly 

</details>
