### ISSUE TITLE
A Brave user agent is sent in Chromecast SSDP packets

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#18017]
## Description 

Instead of using the regular user agent (like we send to websites, i.e. the Chrome one), Chromecast SSDP packets create their own user agent manually: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/router/discovery/dial/dial_service.cc;l=111-128;drc=46bbb9795fcc1934c6cfbec096764f888c4d400a

## Steps to Reproduce

   1. Open Wireshark, filter for `ssdp`
   2. Start the browser
   3. Expand the "Simple Service Discovery Protocol" entry
   4. Look for `USER-AGENT`

## Actual result:
![Screenshot from 2021-09-10 17-33-29](https://user-images.githubusercontent.com/167821/132930272-5325043e-4fde-4b1a-94e6-c34053e1e6ed.png)

## Expected result:

We should either send our regular web user agent:
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
```

or perhaps it would be better for compatibility with Chromecast devices to pretend to be a Chrome browser. This is what Chrome sends:
```
USER-AGENT: Google Chrome/93.0.4577.63 Linux
```

**Comment by ShivanKaul** [comment]
Thanks for filing @fmarier! Also noting here that on Mac the channel info is included for the user agent:

![image](https://user-images.githubusercontent.com/5284154/132930628-96815d34-1bbe-4a8b-b773-be596df76243.png)

**Comment by LaurenWags** [comment]
Issue still reproduces with

```
Brave | 1.64.43 Chromium: 121.0.6167.139 (Official Build) nightly (x86_64)
-- | --
Revision | 190a1d5dbad671a0994283b793d4e66e98b82371
OS | macOS Version 13.6.4 (Build 22G513)
```

Steps:
1. Open Wireshark, filter for `ssdp`
2. Launch Nightly
3. Enable `Media Router` under brave://settings/extensions
4. Relaunch as required
5. Expand the "Simple Service Discovery Protocol" entry
6. Look for `USER-AGENT`

<img width="790" alt="Screenshot 2024-02-02 at 3 36 39 PM" src="https://github.com/brave/brave-browser/assets/28145373/9e02375d-540d-481c-8a11-df4482369299">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave	1.65.77 Chromium: 123.0.6312.29 (Official Build) nightly (x86_64) 
Revision	031ef8c7876fbefaede9ac29292258fe299e06fc
OS	macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.65.77`
2. launched Brave
3. launched Wireshark
4. filtered to `ssdp`
5. opened `brave://settings/extensions`
6. set `Media Router` to `Enabled`
7. clicked `Relaunch`
8. examined the `ssdp` packets

### Confirmed `USER-AGENT: Google Chrome/124.0.6355.0 Mac OS X\r\n`
    
example | example | example
---------|---------|---------
<img width="1312" alt="Screen Shot 2024-03-13 at 11 43 57 AM" src="https://github.com/brave/brave-browser/assets/387249/e4cc8aba-4c90-4c61-baea-97e5d1d47e85"> | <img width="1388" alt="Screen Shot 2024-03-13 at 11 44 39 AM" src="https://github.com/brave/brave-browser/assets/387249/8e86e182-1a41-4b68-bb7b-e0c56551ab93"> | <img width="1132" alt="Screen Shot 2024-03-13 at 11 44 36 AM" src="https://github.com/brave/brave-browser/assets/387249/329b32ce-3aae-4675-a4a9-3edde524b133">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.65.93 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | a6eee503125f9441360861f96cfdcccf43b6fee0
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

Steps:

1. installed 1.65.93
2. launched Brave
3. launched Wireshark
4. filtered to ssdp
5. opened brave://settings/extensions
6. set Media Router to Enabled
7. clicked Relaunch
8. examined the ssdp packets

Confirmed `USER-AGENT: Google Chrome/123.0.6312.58 Windows`

example | example | example 
----- | ----  | ----
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/89b686c5-d8b6-4478-9168-03c62d00fc0b">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a86fe15f-298a-4c4b-9377-ff8a1b64da6e">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c4a3cee0-3283-4dbd-ae8c-a7a95113da60">

**Comment by hffvld** [comment]
Hi @fmarier does it apply to `Android`? I don't think we can `cast` with a mobile browser.

**Comment by fmarier** [comment]
> Hi @fmarier does it apply to `Android`? I don't think we can `cast` with a mobile browser.

Good question. I may have filed this as Desktop & Android by mistake. I don't remember ever testing this on Android.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Linux
```

Steps:

1. installed 1.65.96
2. launched Brave
3. launched Wireshark
4. selected ens33 for `...using this filter`
5. filtered to ssdp
6. opened brave://settings/extensions
7. set Media Router to Enabled
8. clicked Relaunch
9. examined the ssdp packets

#### Confirmed USER-AGENT: Google Chrome/123.0.6312.86 Linux 


example | example | example 
--- | ----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/037be172-f3d1-4364-8d21-2fcdd5f5a724)|![image](https://github.com/brave/brave-browser/assets/98358127/17c6089c-5de0-4427-af79-824d6e38011f)|![image](https://github.com/brave/brave-browser/assets/98358127/9bc52c98-c7dc-4a24-8cb8-2adad7198a42)

**Comment by hffvld** [comment]
Hi @fmarier, @SergeyZhukovsky and @kjozwiak  I spent some time trying to connect `Android` to `Wireshark` and capture traffic data. I couldn't figure out how to get `SSDP` protocol info, I only see `MDNS` protocol running on the device. I'm not sure if we must use `rooted` device to see all traffic info or if my setup is incorrect. So, any help is appreciated. 

-------------------

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240305.005 release-keys
Brave build: 1.65.103
Chromium: 123.0.6312.105 (Official Build) beta (64-bit) 
```
----------------------

|Android|MacOS|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/8ab296e8-6de3-475b-9a6e-6f9dfb6af4a3) | ![2](https://github.com/brave/brave-browser/assets/128532965/d5eda7ca-4993-4c22-934d-c6535042483d) |
