### ISSUE TITLE
reorganize app menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18011]
## Description 
The app menu is too long and the length is problematic for users will lower screen resolutions. Need some reorganization to show prominence to new and key features like Brave VPN and Wallet.

## Existing menu

<img width="374" alt="Screen Shot 2021-09-10 at 4 36 38 PM" src="https://user-images.githubusercontent.com/2388823/132914784-e2539179-7f55-48c0-8a8f-b2b4ae9954cf.png">

## Design

[placeholder]

## Brave version (brave://version info)
n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Assets
Figma: https://www.figma.com/file/sS3l8tqUFxt54MEiBTalUI/?node-id=1118%3A21627

**Comment by karenkliu** [comment]
Designs added!

**Comment by Madis0** [comment]
Brave AdBlock doesn't need a main menu entry as it is planned to be merged to settings anyway, right now a link in Shields settings could suffice. 

That entry could be replaced with Sync.

**Comment by adithyaakrishna** [comment]
@rebron I would like to work on this, but is it possible to get a Screenshot of the Design in the issue comments here as the Figma file is not accessible?

// @karenkliu

**Comment by aguscruiz** [comment]
Updated designs available here: 
https://www.figma.com/file/sS3l8tqUFxt54MEiBTalUI/Desktop-toolbar-and-menu?node-id=1483%3A27609

**Comment by adithyaakrishna** [comment]
@aguscruiz Could you please add a SS of the design if it would be fine as we don't have access to it 😶

**Comment by aguscruiz** [comment]
Order/layout is still being discussed, so this screenshot may be outdated soon

<img width="1562" alt="image" src="https://user-images.githubusercontent.com/15734630/161406363-265e1a4e-2b5f-4f7b-8536-d415d774696a.png">

**Comment by lil5** [comment]
Icons improves accessibility for those with reading difficulties or sight difficulties.

Please add icons for:
- history
- bookmarks
- downloads
- find
- settings
- help
- developer tools

**Comment by rebron** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/32410 for app menu restructure (merged 1.59.53 and higher)  https://github.com/brave/brave-browser/issues/32089 to add icons in progress.
