### ISSUE TITLE
Brave Wallet RPC error

### ISSUE THREAD

**Issue by Frito-Lay74** [brave/brave-browser#18023]
## Description 
Hi, I have the brave wallet configured to use in the BSC and MATIC network, they used to work fine but now I get an error when I try to use a swap on both chains.

BSC error:
Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"invalid sender"}}}'

MATIC error:
legacy pre-eip-155 transactions not supported (error={"code":-32603,"message":"Error: [ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Internal JSON-RPC error.\",\"data\":{\"code\":-32000,\"message\":\"only replay-protected (EIP-155) transactions allowed over RPC\"}}}'"}, method="sendTransaction", transaction=undefined, code=UNSUPPORTED_OPERATION, version=providers/5.4.3)

## Steps to Reproduce
   1. Try to do any swap
   2. Confirm gas fee
   3. Error appears

## Brave version (brave://version info)
Brave | 1.29.76 Chromium: 93.0.4577.58 (Official Build) unknown (64-bit)
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | Linux

**Comment by sarraayush** [comment]
is it an open source program .i have experience in c++ can i contribute something to it ?

**Comment by Frito-Lay74** [comment]
It's not a program I am developing, I'm just an user who is trying to do a swap in a dex (pancakeswap, quickswap)

**Comment by Frito-Lay74** [comment]
Nevermind, found out it is a brave bug after an update
