### ISSUE TITLE
Filter out the Twitter Click ID from the query string

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#18020]
Twitter started using a [query string parameter to track click on ads](https://business.twitter.com/en/blog/performance-advertising-on-twitter.html
) and work-around third-party cookie blocking. This unique ID (`twclid`)  should be removed.

Here are some examples in the wild:

- https://humanitec.com/lp/devops-maturity-test-v2?twclid=11434229305609916421&utm_source=twitter&utm_medium=paid_social&utm_campaign=devops_m_test_v2_lu_us
- https://www.silive.com/?twclid=11432019458843975681
- https://www.nj.com/?twclid=11428727354013192197
- https://www.silive.com/?twclid=11432019458843975681

**Comment by ryanbr** [comment]
Picked up another one, we could add. `&__twitter_impression` @fmarier 

`https://www.insider.com/mississippi-teachers-want-mask-mandate-after-thousands-kids-get-covid-2021-8?amp&__twitter_impression=true`

**Comment by fmarier** [comment]
@ryanbr Is it just a boolean value or have you seen that used with unique IDs?

A boolean like that looks like it's more for the purpose of campaign-level tracking as opposed to cross-site user tracking. We only filter out the latter: https://github.com/brave/brave-browser/wiki/Query-String-Filter

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.41 Chromium: 94.0.4606.41 (Official Build) nightly (x86_64)
-- | --
Revision | 333e85df3c9b656b518b5f1add5ff246365b6c24-refs/branch-heads/4606@{#845}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. clean profile
2. launched Brave
3. opened Developer Tools, selected the Network tab
4. loaded `https://brave.com/?twclid=1234`
5. confirmed the URL bar didn't retain the `?twclid=1234` query string

<img width="1780" alt="Screen Shot 2021-09-14 at 1 36 00 PM" src="https://user-images.githubusercontent.com/387249/133330524-40333ae4-f65c-4c74-b6cc-fc2a8db0a8f8.png">

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.31.67 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/10054

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
![image](https://user-images.githubusercontent.com/17010094/136010772-3cefc481-273f-4d5f-83fe-95bb4f4be93b.png) | ![image](https://user-images.githubusercontent.com/17010094/136010657-c92da1a9-337b-45f1-8367-92f7e449c14e.png)
