### ISSUE TITLE
Brave Rewards for Firefox and Chromium

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#18029]
Brave should consider releasing a Brave Rewards browser extension for Mozilla Firefox and Chromium.

**Reason:**
Mozilla Firefox and Chromium-variants together hold more than 84% of the desktop browser market share. If Brave Rewards is able to tap on this userbase, the advertising value of Brave Rewards network will explode overnight.

What this means:

More people are exposed to Brave Rewards
Advertisers want to onboard to Brave Rewards
BAT token’s demand and circulation increases
More people become vested in the Brave ecosystem
These are all good things.

Brave should not tunnel-vision itself into thinking everything must be embedded within the Brave Browser. Fact is, browser development is tough, and every browser has its strengths and its fans. We should spread the love of BAT by allowing browser users to join in.

**Comment by bsclifton** [comment]
cc: @rebron

**Comment by Miyayes** [comment]
Thanks. This has been noted, and a BAT SDK as well as extensions have been discussed in the past. For example, you can also see discussion of it in this podcast with Brendan Eich's (Brave CEO) and Binance CEO CZ: https://www.youtube.com/watch?v=4pUlK7n2yVY 

If and when we're ready to do implement this, we will file an issue as needed that we can use to track the project.

**Comment by clicky6** [comment]
> Thanks. This has been noted, and a BAT SDK as well as extensions have been discussed in the past. For example, you can also see discussion of it in this podcast with Brendan Eich's (Brave CEO) and Binance CEO CZ: https://www.youtube.com/watch?v=4pUlK7n2yVY
> 
> If and when we're ready to do implement this, we will file an issue as needed that we can use to track the project.

@Miyayes I think voice in podcast is somewhat not clear and it is not loud enough on YouTube so any other option of listening to it.
