### ISSUE TITLE
Brave Rewards database failing to migrate from schema 29

### ISSUE THREAD

**Issue by nkavian** [brave/brave-browser#18024]
## Description 
I didn't receive July and August rewards. When August came, the rewards tab said the next payment date would be October 7. Now on September 11 the next payment date says November 7. Since July, I have not seen a single Ad.

Looking at the rewards logs, back in July 12th, I received a 504, and since then the log is full of other types of errors:

```
[Jul 11, 2021, 9:52:50.4 PM:ERROR:publisher.cc(763)] Publisher info not found
[Jul 12, 2021, 9:20:19.9 AM:ERROR:get_available.cc(69)] Unexpected HTTP status: 504
[Jul 12, 2021, 5:36:14.3 PM:ERROR:publisher.cc(763)] Publisher info not found
```
```
[Sep 05, 2021, 9:23:30.4 AM:ERROR:get_available.cc(69)] Unexpected HTTP status: -1
...
[Sep 05, 2021, 11:55:24.8 AM:ERROR:publisher.cc(774)] Publisher info not found
...
[Sep 05, 2021, 1:43:28.8 PM:ERROR:refill_unblinded_tokens.cc(189)] Failed to get signed tokens
```
The internals log tab shows a few interesting things (there is no database migration 29->30):
```
09/09/2021, 11:12:30 AM | ac.next_reconcile_stamp | 1633803150
09/06/2021, 08:01:58 AM | version | 10
08/09/2021, 02:00:42 PM | ac.next_reconcile_stamp | 1631134842
07/10/2021, 01:59:13 PM | database_migrated | 30->32
07/10/2021, 01:59:13 PM | version | 9
07/10/2021, 01:59:13 PM | ac.next_reconcile_stamp | 1628542753
06/01/2021, 01:54:47 AM | ac.next_reconcile_stamp | 1625129687
04/24/2021, 04:45:13 PM | ac.next_reconcile_stamp | 1621899913
03/24/2021, 10:12:53 AM | ac.next_reconcile_stamp | 1619197973
02/16/2021, 05:47:59 PM | ac.enabled | 0
02/16/2021, 05:45:17 PM | database_migrated | 1->29
```

## Steps to Reproduce
My only guess as to what happened. The browser said to "Update" in yellow, then it became red. I have so many tabs open that I don't want to lose my place in the tabs. Sometimes browsers lose tabs.. So long after it became red, I finally decided to upgrade. I think it crashed on that upgrade and I simply reopened the browser.

## Expected result:
- programmatically detect I'm missing database upgrade 30 and fix it.
- help me recover the BAT I've already earned.
- resolve the other `errors` in the log. Error means error, so I assume they should be fixed. If they are ignorable, reclassify it to a warning or info.

## Brave version (brave://version info)
Brave | 1.29.77 Chromium: 93.0.4577.63 (Official Build) (x86_64)
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 10.14.6 (Build 18G8022)

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by nkavian** [comment]
I had help from support with the log messages. I'm receiving ads now. The unresolved question is what to do about the missing migration from 29 -> 30.

**Comment by Miyayes** [comment]
@nkavian I think at this point, if you're still in a weird state and your Rewards is not working due to failed 29 -> 30 schema migration, we recommend you reset your Brave Rewards profile. Let us know if any BAT is at stake and we can help (hopefully you have an Uphold or Gemini account). Thanks!

**Comment by nkavian** [comment]
It was resolved. The root cause was that Brave locked me out; my VPN usage somehow triggered it; and someone at Brave took me off the blacklist to resolve the issue.
