### ISSUE TITLE
Brave blocks HTML5 canvas without option to allow

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#1803]
https://community.brave.com/t/uploading-profile-picture-and-cover-photo-on-twitter/35205/5

It is sensible to block HTML5 canvas fingerprinting in private windows with Tor by default, but sometimes users do not need to prevent fingerprinting by the site, particularly if they're logging into the site.  The Tor Browser pops up a permissions box for HTML5 canvas access.

(If disabling fingerprinting protection suffices to allow HTML5 canvas access, then we can close this and answer with that on the community forum.)

**Comment by pes10k** [comment]
Fixed by farbling
