### ISSUE TITLE
Allow to leave sync chain when offline

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#18054]
## Description 

Allow to  leave sync chain when offline. If server does not replies on delete device for a certain amount of time, perform forced leave sync chain.

**Comment by stephendonner** [comment]
**Verified `PASSED`** using 


Brave | 1.31.54 Chromium: 94.0.4606.50 (Official Build) beta (x86_64)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | macOS Version 11.6 (Build 20G165)

### Steps:
1. new profile
2. launched Brave
3. clicked on the “hamburger” menu
4. chose `Sync`
5. clicked on `Start a new Sync Chain`
6. clicked on `Computer`
7. clicked `OK`
8. disconnected Wi-Fi
9. went to `Manage your synced devices` (`brave://settings/braveSync/setup`)
10. clicked `Leave Sync Chain`
11. device should leave sync in 5 seconds
12. opened in `brave://sync-internals`; confirmed `Transport State` is `Disabled
13. confirmed device is gone from `brave://settings/braveSync/setup`


example | example | example | example
---------|----------|---------|----------
<img width="1175" alt="Screen Shot 2021-09-20 at 12 15 03 PM" src="https://user-images.githubusercontent.com/387249/134061741-fe97c441-d806-4c78-885f-ec3fdf583460.png"> | <img width="1340" alt="Screen Shot 2021-09-20 at 12 18 18 PM" src="https://user-images.githubusercontent.com/387249/134061779-b4fbeacf-77f4-4065-8119-a1df8a43d09d.png"> | <img width="1340" alt="Screen Shot 2021-09-20 at 12 18 45 PM" src="https://user-images.githubusercontent.com/387249/134061815-6ca46cfb-afd5-44e5-a365-4d5bc337af6a.png"> | <img width="1326" alt="Screen Shot 2021-09-20 at 12 19 22 PM" src="https://user-images.githubusercontent.com/387249/134061816-19e21830-eab4-49e2-8c10-04357d00c7fa.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.31.67 x64 Beta build
- Verified test plan from https://github.com/brave/brave-core/pull/10044
- Verified when device is offline able to remove device from sync chain via the delete button
- Verified `chrome://sync-internals` shows `Transport State: Disabled`
- Verified reconnecting the device to networks doesn't turn sync on again and transport status remains disabled
--------------
Verification passed on Samsung Tab A with Android 10 running 1.31.67 x64 Beta build
- Verified test plan from https://github.com/brave/brave-core/pull/10044
- Verified when device is offline able to remove device from sync chain via the delete button
- Verified `chrome://sync-internals` shows `Transport State: Disabled`
- Verified reconnecting the device to networks doesn't turn sync on again and transport status remains disabled
