### ISSUE TITLE
build brave

### ISSUE THREAD

**Issue by QairexStudio** [brave/brave-browser#18058]
## Description 

tried (npm-v6.1, nodejs-v12.22.6)
tried other opened and closed issues but dont worked

### System information
OS: Linux 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux
npm: v7.5.2
nodejs: v12.22.5

## Steps to Reproduce

   1. npm install
   2. npm run init
   3. npm run build Release (or npm run build)

## Actual result:

```
> brave@1.31.35 init
> node ./scripts/init.js

Performing initial checkout of brave-core
------------------------------------------------------------------------------------------------------------
/home/al0ne/brave-browser/src/brave
> npm install
------------------------------------------------------------------------------------------------------------
/home/al0ne/brave-browser/src/brave
> npm run sync -- --init

> brave@1.31.35 sync
> npm --prefix src/brave run sync -- "--init"

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/al0ne/brave-browser/src/brave/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/al0ne/brave-browser/src/brave/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/al0ne/.npm/_logs/2021-09-13T16_51_12_900Z-debug.log
npm ERR! code 254
npm ERR! path /home/al0ne/brave-browser
npm ERR! command failed
npm ERR! command sh -c npm --prefix src/brave run sync -- "--init"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/al0ne/.npm/_logs/2021-09-13T16_51_13_042Z-debug.log
null
null
npm ERR! code 1
npm ERR! path /home/al0ne/brave-browser
npm ERR! command failed
npm ERR! command sh -c node ./scripts/init.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/al0ne/.npm/_logs/2021-09-13T16_51_13_233Z-debug.log

```

## Expected result:
succesfully builded brave

## Reproduces how often: 

always

## Brave version (brave://version info)

brave: 1.31.35

## Version/Channel Information
Only tested stable version

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
Yes

**Comment by bsclifton** [comment]
Sorry it's taken a while to respond. In your example above, you'll want to be running `npm run init`. 

If you run into problems with `npm run init`, you'll want to follow the steps at https://github.com/brave/brave-browser/wiki/Linux-Development-Environment to make sure you have the proper pre-requisites to get setup

`npm run sync` is something you can run; but it's fine without arguments. If you wanted, you can run one of these:
```
npm run sync -- --all
npm run sync -- --run_hooks
```

Sync is intended to be ran after `init` has already been done once and it will update the Chromium repo and re-apply patches to brave-core
