### ISSUE TITLE
Download instead of subscription page is shown for dowjones referral promo

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1805]
## Steps to Reproduce

1. (Important) Uninstall Brave Browser with User Data to have a Clean install
![image](https://user-images.githubusercontent.com/34715963/47382336-5e7da880-d702-11e8-9de3-68cf7495a568.png)
2. (On Windows )Download stub/mini installer and rename it to `BraveBrowserSetup-dowjones-barrons.exe`
3. Run the stub/mini installer
4. After Brave has started wait for `https://brave.com/dowjones-barrons` page to be shown (can take up to 60 seconds)

## Actual result:

The Download page is shown.
![image](https://user-images.githubusercontent.com/34715963/47383220-80782a80-d704-11e8-8b27-b5264d7951fb.png)

The Underlying issue is lack of "X-Brave-Access-Key" Header.
The header is listed in `Local State` file (located in `[user]\AppData\Local\BraveSoftware\Brave-Browser\User Data\`)

The `headers` in the `Local State` file cannot handle more than one entry.
The subscription page is shown if I modify the `Local State` file to:
```
"referral": {
    "download_id": "d63858c3-985f-4cec-b76d-88136d03bef6",
    "headers": [{
            "cookieNames": [],
            "domains": ["brave.com", "staging.brave.com"],
            "expiration": 3.1536e+10,
            "headers": {
                "X-Brave-Access-Key": "BBOfz269pb6"
            }
        }
    ],
    "promo_code": "dowjones-barrons"
}
```
from
```
"referral": {
    "download_id": "d63858c3-985f-4cec-b76d-88136d03bef6",
    "headers": [{
            "cookieNames": [],
            "domains": ["marketwatch.com", "barrons.com"],
            "expiration": 3.1536e+10,
            "headers": {
                "X-Brave-Partner": "dowjones"
            }
        }, {
            "cookieNames": [],
            "domains": ["brave.com", "staging.brave.com"],
            "expiration": 3.1536e+10,
            "headers": {
                "X-Brave-Access-Key": "BBOfz269pb6"
            }
        }
    ],
    "promo_code": "dowjones-barrons"
}
```
## Expected result:
The Subscription page is shown
![image](https://user-images.githubusercontent.com/34715963/47383295-b4ebe680-d704-11e8-81a2-b6a1522e9914.png)

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

Reproduced on Windows 10 x64 by @GeetaSarvadnya 
Reproduced on Mac and Windows by @kjozwiak 

### Additional Information

cc @srirambv @LaurenWags @emerick @bsclifton

**Comment by btlechowski** [comment]
Still reproducible on Windows with the exact steps from OP.
The required header(X-Brave-Access-Key) is not sent.


Brave | 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows 7 x64

**Comment by kjozwiak** [comment]
Yup, same results on `macOS 10.13.6 x64` using the following build:

Brave | 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* installed `BraveBrowserSetup-dowjones-barrons.pkg` which opened https://brave.com/dowjones-barrons but included the `Download Brave` button rather than the `Claim my subscription` button.
* installed `BraveBrowserSetup-dowjones-marketwatch.pkg` which opened https://brave.com/dowjones-marketwatch but included the `Download Brave` button rather than the `Claim my subscription` button.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* installed Brave-Browser-dowjones-barrons.pkg which opened https://brave.com/dowjones-barrons and got the `Get my subscription` button.
![screen shot 2018-11-02 at 5 48 16 pm](https://user-images.githubusercontent.com/28145373/47942449-64287a80-dec8-11e8-9157-966cc1786cd9.png)
* installed Brave-Browser-dowjones-marketwatch.pkg which opened https://brave.com/dowjones-marketwatch and got the `Get my subscription` button.
![screen shot 2018-11-02 at 5 51 07 pm](https://user-images.githubusercontent.com/28145373/47942452-668ad480-dec8-11e8-9cf0-dc45664e2088.png)
