### ISSUE TITLE
Security/Privacy: Jumio API for KYC triggered via Brave Rewards Panel is getting blocked for security reasons

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#1806]
See parent issue for feature description #923

Issue: When we launch the sandbox from Brave Rewards panel for add-funds. During the add-funds work flow (See primary issue for docs), the Uphold sandbox triggers a Jumio API that is getting auto-blocked by Shields. We need to be able to allow Jumio API calls w/o getting blocked for this specific use case.

Test Link (to reproduce issue): https://uphold-widget-uhocggaamg.now.sh/

Issue has been discussed with Tom in detail and preliminary call with Uphold has concluded.

Please assign to @tomlowenthal

**Comment by tomlowenthal** [comment]
Basically, we need to whitelist the Jumio host for shields from within this particular context.

**Comment by mandar-brave** [comment]
Closing per chat with @tomlowenthal .
Issue recorded in #923
