### ISSUE TITLE
Fingerprinting 3.0: SpeechSynthesis API

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#18062]
This is a sub-issue of the larger fingerprint defense reorganization issue: #8787

API information:
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis

Relevant API
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices

**default protections:** add a farbling-determined voice name to the list returned by `getVoices`, and have that name be an alias for the first name returned in the list
**aggressive protection:** have the API always return an empty list

**Comment by rillian** [comment]
What should we do with then `voice` list is empty?

**Comment by pes10k** [comment]
Ah, so if there is nothing to alias against?  Then, i think nothing to do there; if its default settings and the "true" value for `getVoices` is an empty list, then do nothing
