### ISSUE TITLE
[hackerone] Strip referrer and origin in cross-origin requests from a `.onion` origin

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#18071]
If a cross-origin request originates from a `.onion` service, we should match the Tor Browser behavior and:
- omit the `Referer` header
- send a value of `null` for the `Origin` header whenever present (e.g. in the case of a `POST` request)

Same-origin requests should follow [our normal referrer policy](https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)#modified-features-and-functionality).

Test page: http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html

**Comment by diracdeltas** [comment]
hackerone issue: https://hackerone.com/reports/1337624 (credit: kkarfalcon)

**Comment by fmarier** [comment]
I updated https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)/_compare/1ae15b494ba87516f0afe85d5ddf0303bb9e5018...f31accf2c951fefa6e07b623277c007e3d87b1b3 for the referrer changes introduced here.

**Comment by LaurenWags** [comment]
Verification in progress using

```
Brave | 1.33.94 Chromium: 96.0.4664.45 (Official Build) beta (x86_64)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 11.6.1 (Build 20G224)
```

## `Sub-resources`

### `Same-origin`

**`Test Case #1`**
```
onion16_1.png - was loaded with the full Referer header and the origin of this page in the Origin header.
```

* Origin: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion`
* Referer: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`

<img width="1638" alt="sub resources same-origin 1" src="https://user-images.githubusercontent.com/28145373/144135523-ff6cada2-851b-4cad-a368-2b51487d49f3.png">

**`Test Case #2`**
```
onion16_2.png - was loaded with a full Referer header and without an Origin header.
```

* Referer: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`

<img width="1642" alt="sub resources same-origin 2" src="https://user-images.githubusercontent.com/28145373/144135543-693461e7-2fb6-4af5-ac6e-cd200195ad94.png">

**`Test Case #3`**
```
onion16_3.png - was loaded with a full Referer header and the origin of this page in the Origin header.
```

* Origin: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion`
* Referer: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`

<img width="1638" alt="sub resources same-origin 3" src="https://user-images.githubusercontent.com/28145373/144135566-9caac4e3-52d9-4652-b1ea-2362f3216e0d.png">

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 

Brave | 1.33.95 Chromium: 96.0.4664.45 (Official Build) dev (64-bit)
--|--
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux

<details>
<summary>Sub-resources</summary>

### `Same-origin`

**`Test Case #1`**
```
onion16_1.png - was loaded with the full Referer header and the origin of this page in the Origin header.
```

* Origin: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion`
* Referer: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`



**`Test Case #2`**
```
onion16_2.png - was loaded with a full Referer header and without an Origin header.
```

* Referer: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`


**`Test Case #3`**
```
onion16_3.png - was loaded with a full Referer header and the origin of this page in the Origin header.
```

* Origin: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion`
* Referer: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`



### `Cross-origin`

**`Test Case #1`**
```
onion16_4.png - was loaded without a Referer header and with a value of null in the Origin header.
```

* origin: `null`



**`Test Case #2`**
```
onion16_5.png - was loaded without Referer or Origin headers.
```



**`Test Case #3`**
```
onion16_6.png - was loaded without a Referer header and a value of null in the Origin header.
```



</details>

<details>
<summary>Navigations</summary>
</details>

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 

`1.33.98, Chromium 96.0.4664.55` on Windows 10

<details>
<summary>Sub-resources</summary>

### `Same-origin`

**`Test Case #1`**
```
onion16_1.png - was loaded with the full Referer header and the origin of this page in the Origin header.
```

* Origin: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion`
* Referer: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`




**`Test Case #2`**
```
onion16_2.png - was loaded with a full Referer header and without an Origin header.
```

* Referer: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`




**`Test Case #3`**
```
onion16_3.png - was loaded with a full Referer header and the origin of this page in the Origin header.
```

* Origin: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion`
* Referer: `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`




### `Cross-origin`

**`Test Case #1`**
```
onion16_4.png - was loaded without a Referer header and with a value of null in the Origin header.
```

* origin: `null`




**`Test Case #2`**
```
onion16_5.png - was loaded without Referer or Origin headers.
```





**`Test Case #3`**
```
onion16_6.png - was loaded without a Referer header and a value of null in the Origin header.
```





</details>

<details>
<summary>Navigations</summary>

### `Same-origin`

```
The Referer header should be present (full URL of this page) in this example:
```

**`Test Case #1 - after a same-origin GET navigation`**




**`Test Case #2 - after a same-origin GET navigation ending up in a redirect`**




```
The Referer and Origin headers should be present (full URL, and same hostname as this page, respectively) in all of these examples:
```

**`Test Case #1 - after a same-origin POST navigation`**




**`Test Case #2 - after a POST navigation ending up in a redirect`**




### `Cross-origin`

```
Neither the Referer not the Origin header should be present in these examples:
```

**`Test Case #1 - after a cross-origin GET navigation`**




**`Test Case #2 - after a same-origin GET navigation ending up in a cross-origin redirect`**




**`Test Case #3 - after a cross-origin GET navigation ending up in a same-origin redirect`**




```
The Referer header should not be present and the Origin header should be null in all of these examples:
```

**`Test Case #1 - after a cross-origin POST navigation`**




**`Test Case #2 - after a same-origin POST navigation ending up in a cross-origin redirect`**




**`Test Case #3 - after a cross-origin POST navigation ending up in a same-origin redirect`**




</details>
