### ISSUE TITLE
Ethereum address validation, balance validations on tx

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#18074]
This should also cover as part of address validation

```
Give a warning when trying to send ETH or tokens to...

A contract address
An account trying to send to itself
```

**Comment by SergeyZhukovsky** [comment]
those checks should only be done for ERC20 transfers and NFT transfers and ETH sends with no contract data. Use the transaction_type field to tell.   We don’t want it for Other type.

**Comment by AlexeyBarabash** [comment]
The related Desktop PR is https://github.com/brave/brave-core/pull/10933

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.104 x64 build
- Verified test plan from [brave/brave-core#11521](https://github.com/brave/brave-core/pull/11521)
- Verified all error message show up as expected

Sufficient Balance | Insufficient Balance | Invalid ETH Address | Own Address | Token's Contract Address 
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/145572979-2522055f-6905-4f10-9bff-c9c7db0448f1.png) | ![image](https://user-images.githubusercontent.com/17010094/145572955-11fd5ac2-ff68-41fd-aa36-ca4649a2ef8c.png) | ![image](https://user-images.githubusercontent.com/17010094/145573008-4a0021a1-442a-4b7b-a108-7fa0acb7035f.png) | ![image](https://user-images.githubusercontent.com/17010094/145573093-f1d95942-fb8e-44bf-a9a7-0a8e4d78b03e.png) | ![image](https://user-images.githubusercontent.com/17010094/145573029-420b165d-584f-40fa-9327-d9e2eb66a407.png)

------------
Verification passed on Samsung Tab A with Android 11 running 1.33.104 x64 build
- Verified test plan from [brave/brave-core#11521](https://github.com/brave/brave-core/pull/11521)
- Verified all error message show up as expected

Sufficient Balance | Insufficient Balance | Invalid ETH Address | Own Address | Token's Contract Address 
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/145573199-9b5d5aca-63ca-4f47-a73d-531871be717c.png) | ![image](https://user-images.githubusercontent.com/17010094/145573174-b69cc192-acd7-40fc-aa83-2de8546213bd.png) | ![image](https://user-images.githubusercontent.com/17010094/145573289-cb89e5d9-041c-4d53-820d-ec63fded2567.png) | ![image](https://user-images.githubusercontent.com/17010094/145573273-8615f2a5-75ad-4852-83af-e2f16a283fa0.png) | ![image](https://user-images.githubusercontent.com/17010094/145573303-3fe9633b-ac8d-42ef-9dae-891d5a1d8c14.png)
