### ISSUE TITLE
Regression: reset profile dialog shows checkbox to report current settings

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#18077]
Not sure when this regressed. Present in 1.29.x+

![image](https://user-images.githubusercontent.com/41635752/133178449-392ad41a-9a80-4570-8c13-172381a4a242.png)

The footer with the checkbox should be removed.

STR:
1. Start Brave
2. Navigate to brave://settings/reset
3. Click on `Restore settings to their original defaults`
Observer the dialog.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.44 Chromium: 94.0.4606.41 (Official Build) nightly (x86_64)
-- | --
Revision | 333e85df3c9b656b518b5f1add5ff246365b6c24-refs/branch-heads/4606@{#845}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. new profile
2. launched Brave
3. opened `brave://settings/reset`
4. clicked on `Restore settings to their original defaults`
5. examine the dialog / text

Confirmed the `Help make Brave better...` option is removed

<img width="1312" alt="Screen Shot 2021-09-15 at 8 46 39 AM" src="https://user-images.githubusercontent.com/387249/133466242-15fa08fb-7d51-484b-a96e-81020edcbffe.png">
