### ISSUE TITLE
Why the folder icon that shows in bookmarks bar doesn't show when we go to bookmark manager.

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#18081]
I have posted this issue earlier and I think it was solved with the new update but It wasn't solved. #18021.

Why the folder icon that shows in bookmarks bar doesn't show when we go to bookmark manager (brave://bookmarks/).

Fix this issue the folder icon doesn't show up everywhere it only shows on bookmarks bar but doesn't show when we go to bookmark manager (brave://bookmarks/).

![93](https://user-images.githubusercontent.com/89839714/133197167-247beaae-5a32-4984-b5a5-1f4f9fd87e3c.png)
It is showing in bookmarks bar but why not showing in bookmark manager.

![92](https://user-images.githubusercontent.com/89839714/133197208-fc5e429a-511b-48ac-8cfa-7647933eb194.png)

**Comment by Johann999** [comment]
It would actually be logical and useful if the icons in the bookmark bar and in the bookmark manager
would be identical (same appearance and same color).

**Comment by clicky6** [comment]
Ya It must be the same. No Browser has different folder icons like Brave which shows different on favorites bar and different on bookmark manager.
For example take Microsoft Edge (Chromium).
It has the same icons for bookmark bar and bookmark manager.
See:-
![89](https://user-images.githubusercontent.com/89839714/133289608-d7e2d230-5729-4dcb-83db-fc3755c769bf.png)

![88](https://user-images.githubusercontent.com/89839714/133289633-ef5fb7e5-af70-4ffb-8a2a-d6cd4885e2b3.png)

Different icons are not given in Edge like they are given in Brave so please Brave Team improve this.
