### ISSUE TITLE
component resources have organizational and dependency issues

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#1808]
component resources are not well organized or encapsulated within the relevant components. This makes resources both hard to find and also difficult to use in other projects like android

**Comment by bridiver** [comment]
Test plan:
1. Open Rewards UI - all text should visible without translation placeholders

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta(64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified step from test plan https://github.com/brave/brave-browser/issues/1808#issuecomment-432820068
