### ISSUE TITLE
Brave logo is cut off on dowjones prom subscription page

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1809]
## Steps to Reproduce

1. (Important) Uninstall Brave Browser with User Data to have a Clean install
![image](https://user-images.githubusercontent.com/34715963/47382336-5e7da880-d702-11e8-9de3-68cf7495a568.png)
2. (On Windows )Download stub/mini installer and rename it to `BraveBrowserSetup-dowjones-barrons.exe`
3. Run the stub/mini installer
4. After Brave has started wait for `https://brave.com/dowjones-barrons` page to be shown (can take up to 60 seconds)

## Actual result:

Brave logo is cut off on the top of the page
![image](https://user-images.githubusercontent.com/34715963/47383295-b4ebe680-d704-11e8-81a2-b6a1522e9914.png)

## Expected result:
Brave logo is not cut off

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

Resolution: 1366x768

cc @kjozwiak @srirambv @LaurenWags @GeetaSarvadnya

**Comment by btlechowski** [comment]
Blocked by: https://github.com/brave/brave-browser/issues/1805

**Comment by NejcZdovc** [comment]
cc @jonathansampson @bradleyrichter

**Comment by rebron** [comment]
@kjozwiak closing

**Comment by kjozwiak** [comment]
Created https://github.com/brave/brave-website/issues/199 as discussed in the triage meeting.
