### ISSUE TITLE
Chinese translation typo

### ISSUE THREAD

**Issue by FWangZil** [brave/brave-browser#18094]
## Description 

Wrong wording when requesting notification permission on the website

## Steps to Reproduce

   1. Web page (e.g. youtube) Pop-up notification permission request
   2. 
   3. 

## Expected result:

知道我关闭这个站点 ——> 直到我关闭这个站点

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

<html>
<body>

Brave | 1.29.79 Chromium: 93.0.4577.63 (正式版本) （64 位）
-- | --
修订版本 | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
操作系统 | Windows 10 OS Version 2009 (Build 19043.1202)

</body>
</html>

## Version/Channel Information:

I'm only using the desktop version of the browser for now

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

I can  reproduce this issue with the current release.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by FWangZil** [comment]
The same problem has reappeared in the current version

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.34.80 Chromium: 97.0.4692.71 (正式版本) (x86_64)
-- | --
修订版本 | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
操作系统 | macOS 版本11.6.1（版号20G224）
```

Confirmed translation on notification popup:

<img width="622" alt="截屏2022-01-06 上午11 21 40" src="https://user-images.githubusercontent.com/28145373/148415073-19b7018a-ba6a-4e39-a26f-abe2b45eb272.png">
