### ISSUE TITLE
Add do not ask again checkbox on crash report prompt

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18103]
## Description 

Add and support a do not ask again checkbox/setting for the crash report dialog.
 
No additional UI or setting for users to show the prompt again is needed; users can go to brave://settings/privacy to toggle sending crash reports.

## Steps to Reproduce

   1. On clean profile/release channel, force crash and notice crash prompt setting on restart. brave://inducebrowsercrashforrealz/
   2. No `Do not show again` checkbox
   3. For testers, note that crash report prompt is on by default for beta and nightly.

## Actual result:
![131420802-4831bd06-2e63-4930-bef3-d04890e84b5c](https://user-images.githubusercontent.com/5951041/133304341-f8e1f92d-6acf-4139-95c3-2df0d2e21d2e.png)

## Expected result:
![image](https://user-images.githubusercontent.com/2388823/133337912-07acba43-990a-48eb-9dbe-8c3b2b93eb6d.png)

## Reproduces how often: 

n/a

## Brave version (brave://version info)

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? no, crash report prompt is on by default
- Can you reproduce this issue with the nightly channel? no, crash report prompt is on by default

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Michael82548** [comment]
You are able to reproduce this in non-stable branches if you manually opt-out out of sending crash reports

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.47 Chromium: 94.0.4606.50 (Official Build) nightly (x86_64)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. clean profile
2. launched Brave and disabled crash reporting from `brave://settings/privacy` and re-launched
3. loaded `brave://inducebrowsercrashforrealz/` and crashed
4. re-launched and checked the crash-permission/ask dialog is launched
5. checked `Don't ask again` checkbox and clicked `Block`
6. shut down Brave
7. re-launched to save preferences
8. loaded `brave://inducebrowsercrashforrealz/` again
9. re-launched and check crash permission ask dialog is not launched
10. confirmed that `Help improve Brave's features and performance` was now enabled/on

example | example | example | example
---------|----------|---------|---------
<img width="1034" alt="Screen Shot 2021-09-16 at 2 47 06 PM" src="https://user-images.githubusercontent.com/387249/133690550-568c0bbf-c818-4465-beac-700d5df9b703.png"> | <img width="1034" alt="Screen Shot 2021-09-16 at 2 47 49 PM" src="https://user-images.githubusercontent.com/387249/133690570-6062bdb8-a097-4fde-8f86-257fc8860b30.png"> | <img width="1034" alt="Screen Shot 2021-09-16 at 2 48 28 PM" src="https://user-images.githubusercontent.com/387249/133690622-50635062-23f8-45e7-a862-dc4172b073b2.png"> | <img width="1034" alt="Screen Shot 2021-09-16 at 2 51 58 PM" src="https://user-images.githubusercontent.com/387249/133690736-7e4e2ec4-92cf-4067-9250-86fb1f675bd9.png">

**Comment by rebron** [comment]
@stephendonner Step 5 and Step 10 don't look right. Shouldn't step 10 be off if selecting block.
cc: @simonhong

**Comment by stephendonner** [comment]
> @stephendonner Step 5 and Step 10 don't look right. Shouldn't step 10 be off if selecting block.
> cc: @simonhong

Fixed; sorry!
