### ISSUE TITLE
Github in-line tipping button is squeezed in between name and id when the name is long enough

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18106]
## Description 

Tip button is squeezed in between name and id when the name is long enough

## Steps to Reproduce

   1. Login to Github
   1. Visit https://github.com/orgs/brave/people
   1. Look for the longest name
   1. Tip button is in between the name and id

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/133308343-6bc5871a-adc1-4d68-b0c8-9c243ea0230d.png)

## Expected result:
Not whats shown in screenshot above

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.31.36 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | `ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}`
OS | macOS Version 11.5.2 (Build 20G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @emerick

**Comment by emerick** [comment]
I'm not able to repro on Windows at various resolutions. Maybe it has something to do with the default font size?

![Untitled](https://user-images.githubusercontent.com/5033691/133635428-ac81ade6-a80a-4d99-a289-5625779b52f0.png)

**Comment by srirambv** [comment]
Sorry for the delayed update. The issue I saw was on default screen resolution on macOS (1440x900). Setting it to 1680x1050 it shows like this 

![image](https://user-images.githubusercontent.com/17010094/135301862-5429f21e-a7a4-4367-b137-98e0af4d03f8.png) | ![image](https://user-images.githubusercontent.com/17010094/135301979-33f371a2-94ae-48db-a70d-a3e5aca3f870.png)
-- | --

As a matter of fact I see it like this even if I set it to default resolution

**Comment by LaurenWags** [comment]
+1 from @pes10k re: https://bravesoftware.slack.com/archives/C20HMJ62H/p1642647659056500

**Comment by mkarolin** [comment]
No longer valid as tipping buttons have been removed (https://github.com/brave/brave-browser/issues/34367).
