### ISSUE TITLE
Implement account discovery when restore wallet

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#18104]
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account-discovery

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.39.101 Chromium: 101.0.4951.64 (Official Build) beta (64-bit)
-- | --
Revision | `d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}`
OS | Linux

- Verified steps from issue description
- Verified all accounts that are having a send transaction are discovered and restored when wallet is restored using a seed
- Verified if there is no send transaction on the last account but there is an incoming transaction then only the accounts which has send transactions are restored

Successful restore for all send accounts | Unsuccessful restore of last receiving acocunt
-- | --
<video src=https://user-images.githubusercontent.com/17010094/168274447-01e78178-179d-4b73-8241-e4af26bbaddb.mp4> | <video src=https://user-images.githubusercontent.com/17010094/168274780-7d89e95e-9d83-49fb-8201-c2745d5e6e9e.mp4>
