### ISSUE TITLE
Add RPill to unblinded token and unblinded payment token redemption

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#18100]
Add RPill to unblinded token and unblinded payment tokens requests. `odyssey`:`host` and `odyssey`:`guest`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

Verification in https://github.com/brave/internal/issues/867#issuecomment-1094214759

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verification in https://github.com/brave/internal/issues/867#issuecomment-1094249179

**Comment by stephendonner** [comment]
Verification `PENDING` using 

Brave | 1.38.93 Chromium: 100.0.4896.88 (Official Build) beta (x86_64)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | macOS Version 12.4 (Build 21F5048e)



Verification notes over in https://github.com/brave/internal/issues/867#issuecomment-1100716057
