### ISSUE TITLE
[Android] Implement Rewards Backup & Restore 2.0 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18102]
## Description 

Implement Rewards Backup & Restore 2.0, which will allow user with unverified Rewards wallets to backup and restore their Brave Rewards wallet with vBAT in a privacy-preserving way.

**Comment by newuser-web** [comment]
Any update on this one?

**Comment by Miyayes** [comment]
We would have gotten this for free with the desktop implementation in any case.
