### ISSUE TITLE
promoCode is never claimed after closing browser just after install

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1811]
## Steps to Reproduce

1. (Important) Uninstall Brave Browser with User Data to have a Clean install
![image](https://user-images.githubusercontent.com/34715963/47382336-5e7da880-d702-11e8-9de3-68cf7495a568.png)
2. (On Windows )Download stub/mini installer and rename it to `BraveBrowserSetup-KAM253.exe`
3. Run the stub/mini installer
4. Close Brave as soon as it is started 
5. Run Brave and wait for promoCode to disappear
6. Check `Local State` file for `promo_code`

Note: `promoCode` and `Local State` files are located in `AppData\Local\BraveSoftware\Brave-Browser\User Data\` on Windows

## Actual result:

`promoCode` is never claimed
`promo_code` is not added to `Local State`

## Expected result:
`promoCode` is claimed
`promo_code` is added to `Local State`

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

@kjozwiak Can you check on Mac?
cc @srirambv @LaurenWags @GeetaSarvadnya @emerick

**Comment by emerick** [comment]
This is because we only look for the `promoCode` file on "first run". We should probably just look for it as long as we don't have a `download_id` in our local state, though.

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows
