### ISSUE TITLE
Linux error log: chrome Corruption detected in extension

### ISSUE THREAD

**Issue by jurekb** [brave/brave-browser#18125]
## Description 

brave-bin-1:1.29.80-1-x86_64.pkg.tar.zst

5.14.3-arch1-1

On Brave open these errors are logged (journalctl):

Sep 14 15:29:04 r61i chrome[40650]: [40650:40650:0914/152904.151908:WARNING:chrome_content_verifier_delegate.cc(212)] Corruption detected in extension eoceebklhjepohnakemchinmkdpbolgh installed at: /home/jb/.config/BraveSoftware/Brave-Browser/Greaselion/Temp/scoped_dirtVb0bH, from webstore: 0, corruption reason: 1, should be repaired: 1, extension location: kComponent

Sep 14 15:29:04 r61i chrome[40650]: [40650:40650:0914/152904.163976:WARNING:chrome_content_verifier_delegate.cc(212)] Corruption detected in extension bpkoijdaibakhfgahdfknbdcankhidoa installed at: /home/jb/.config/BraveSoftware/Brave-Browser/Greaselion/Temp/scoped_dirglbwx9, from webstore: 0, corruption reason: 1, should be repaired: 1, extension location: kComponent

Sep 14 15:29:04 r61i chrome[40650]: [40650:40650:0914/152904.164252:WARNING:chrome_content_verifier_delegate.cc(212)] Corruption detected in extension ldopphkgfhfchjcgfilekhkifaodmegm installed at: /home/jb/.config/BraveSoftware/Brave-Browser/Greaselion/Temp/scoped_dirWcPPFX, from webstore: 0, corruption reason: 1, should be repaired: 1, extension location: kComponent

Sep 14 15:29:04 r61i chrome[40650]: [40650:40650:0914/152904.182283:WARNING:chrome_content_verifier_delegate.cc(212)] Corruption detected in extension gajhkmnhhoadjcfchafgbekhgigglnkp installed at: /home/jb/.config/BraveSoftware/Brave-Browser/Greaselion/Temp/scoped_dirB3yGbZ, from webstore: 0, corruption reason: 1, should be repaired: 1, extension location: kComponent

Sep 14 15:29:04 r61i chrome[40650]: [40650:40650:0914/152904.182560:WARNING:chrome_content_verifier_delegate.cc(212)] Corruption detected in extension mjkjompjknhcipamakpfliebpggggpga installed at: /home/jb/.config/BraveSoftware/Brave-Browser/Greaselion/Temp/scoped_dirUjC7FV, from webstore: 0, corruption reason: 1, should be repaired: 1, extension location: kComponent

Sep 14 15:29:04 r61i chrome[40650]: [40650:40650:0914/152904.182739:WARNING:chrome_content_verifier_delegate.cc(212)] Corruption detected in extension feipjgjfhmnfhhmbkclfopokbcgnpnnd installed at: /home/jb/.config/BraveSoftware/Brave-Browser/Greaselion/Temp/scoped_dirKf5TAc, from webstore: 0, corruption reason: 1, should be repaired: 1, extension location: kComponent

## Steps to Reproduce

   1.  start/open Brave browser
   2. journalctl
   3. 

## Reproduces how often: 

every time

## Brave version (brave://version info)

brave-bin-1:1.29.80-1-x86_64.pkg.tar.zst

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Redbatman89** [comment]
Im getting these too

**Comment by wknapik** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/17145?

**Comment by jurekb** [comment]
OK. Thanks for reference to  #17145.
I close this one.
