### ISSUE TITLE
**Send a tip** button isn't showing up on Twitter on Android. 

### ISSUE THREAD

**Issue by suny24x7** [brave/brave-browser#18123]
## Description 
Self explanatory. 

## Steps to reproduce 

   1. Go to https://mobile.twitter.com/home 
   2. Navigate to a verified creator account. (example: https://mobile.twitter.com/brave)
   3. Tap the bat icon. 

## Actual result 
![Screenshot_20210915101906.jpg](https://user-images.githubusercontent.com/68751169/133369966-d5627b86-0cba-4c81-9be4-e999a2677f10.jpg)
![Screenshot_20210915101851.jpg](https://user-images.githubusercontent.com/68751169/133369983-b2018fd5-ff77-4d68-9455-b3d687320dd8.jpg)

## Expected result
![Screenshot_20210915101958.jpg](https://user-images.githubusercontent.com/68751169/133370049-23404011-5f97-429d-9942-cdc445da69a2.jpg)

## Issue reproduces how often 
Easily reproduce. 

- Can you reproduce this issue with the current Play Store version?
Yes 

- Can you reproduce this issue with the current Play Store Beta version? 
N/A

- Can you reproduce this issue with the current Play Store Nightly version?
Yes

## Device details
   - Install type : ARM
   - Device type : Phone
   - Android version : 9
   
## Brave version
1.29.81

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
No 

- Does the issue resolve itself when disabling Brave Rewards?
No

**Comment by srirambv** [comment]
This is expected. Twitter tipping is not supported on Android. This was removed as part of #10208
