### ISSUE TITLE
Update text on Gemini widget card

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18121]
## Description 

Update text on the Gemini widget card to read:

Buy crypto with Gemini

Connect to Gemini to view your balance and trade 45+ cryptos. 

## Current result:

<img width="227" alt="Screenshot 2021-09-14 191052" src="https://user-images.githubusercontent.com/5951041/133358923-1be1552c-1ba8-497e-9c7f-6dbb8e5c9a68.png">

## Expected result:
<img width="332" alt="133360251-d69e55e6-9e8d-4817-841b-97748079b418" src="https://user-images.githubusercontent.com/5951041/133360948-1b722eb9-4326-4a09-8922-1cb75f418ef9.png">

See description above.

"Purchase and trade with Gemini" should be replaced with "Buy crypto with Gemini"

"Enable a Gemini connection to view your Gemini account balance and trade crypto" should be replaced with "Connect to Gemini to view your balance and trade 45+ cryptos."

## Brave version (brave://version info)

n/a

## Version/Channel Information:

n/a

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.30.79 Chromium: 93.0.4577.82 (Official Build) beta (64-bit)
-- | --
Revision | `e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}`
OS | Windows 11 Pro Insider Preview OS Version 2009 (Build 22458.1000)

- Verified the text is updated to `Buy Crypto on Gemini`
![image](https://user-images.githubusercontent.com/17010094/133725362-e7654deb-5b33-4ec7-a351-4eab26c466d6.png)

---------
Verification passed on

Brave | 1.30.79 Chromium: 93.0.4577.82 (Official Build) beta (64-bit)
-- | --
Revision | `e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}`
OS | Linux

- Verified the text is updated to `Buy Crypto on Gemini`
![image](https://user-images.githubusercontent.com/17010094/133730760-84e34109-7a1a-4339-b6f5-be7f201efe46.png)

----------
Verification passed on

Brave | 1.30.79 Chromium: 93.0.4577.82 (Official Build) beta (x86_64)
-- | --
Revision | `e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}`
OS | macOS Version 11.5.2 (Build 20G95)

- Verified the text is updated to `Buy Crypto on Gemini`
![image](https://user-images.githubusercontent.com/17010094/133730844-67dd7145-741f-4884-92e1-90eea11cccca.png)
