### ISSUE TITLE
Copy URL bar to clipboard doesn't work

### ISSUE THREAD

**Issue by DataUncertain** [brave/brave-browser#18130]
## Description 
Copying URL from URL bar does not work.

## Steps to Reproduce
   1. Open Any Webpage
   2. Copy the URL from the URL bar using any method:
- Select URL with mouse, CTRL+C
- Select URL with mouse, CTRL+X (URL disappears as if CUT but is not placed on the clipboard)
- Right Click the URL bar, select "Copy"
   3. Attempt to paste the URL into any other app (Notepad, Word, Sublime, Kate - anything).

## Actual result:
Clipboard contents are unchanged. Paste operation pastes the pre-existing clipboard contents.

## Expected result:
Clipboard contains URL. Paste operation pastes the URL

## Reproduces how often: 
100% of the time (Windows)
Intermittent (Linux)

## Brave version (brave://version info)
Windows:
Brave  1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)
Revision  e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}

Linux:
Brave	1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
Revision	c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? **unknown**
- Can you reproduce this issue with the nightly channel? **unknown**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  **NO**
- Does the issue resolve itself when disabling Brave Rewards?   **NO**
- Is the issue reproducible on the latest version of Chrome?   **NO**

**Comment by rebron** [comment]
I'm not able to reproduce this on Windows or Linux
1.29.81 Chromium: 93.0.4577.82

@DataUncertain Are you running any extensions that may conflict with any of the copy and paste functions?

**Comment by DataUncertain** [comment]
I’m not running any extensions at all. It’s quite perplexing.

**Comment by rebron** [comment]
@DataUncertain This is one of those issues where if it was widespread we'd hear about it really quickly and would have encountered in either the beta or nightly channels. 

Any other apps where you're having issues with copy and paste?

**Comment by rebron** [comment]
Closing as stale, no additional reports.
