### ISSUE TITLE
Reposition new setting under Brave Shields & privacy

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18132]
## Description 
Reposition new setting under Brave Shields & privacy

## Steps to reproduce 

   1. Install 1.31.41 nightly
   2. Open Brave shields and privacy setting
   3. Shows new setting for `Always use secure connections` at top of Shields 

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/133446232-dd596b83-0fac-4922-9c00-89a765fbc20e.png>

## Expected result
Place it under `Other privacy settings` under Brave Shields and privacy

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.31.41

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.30.82 x64 build

Samsung Tab A (Android 10) | Oppo Reno 5 (Android 11)
-- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/134336614-27de94bd-869a-4ab3-938a-a80d258e2c8b.png> | <img width=290 src=https://user-images.githubusercontent.com/17010094/134336649-46f671ad-7db6-4b15-9db2-657801b98f3b.png>

**Comment by Tonev** [comment]
@srirambv 

Sorry for disturbing you, just wanted to ask - shouldn't this option be re-positioned under `brave://shields` on desktop as well? I can open a Github ticket for the matter if the subject is something planned, in case you are currently busy with other tasks.
