### ISSUE TITLE
Fix tipping banner warning text for `unverified creator` versus `no available path` creators

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18137]
## Description

There are two kinds of reasons why a tip will go into a pending state (i.e., the tip will be put into the pending list, and retry for 90 days):

1. **TYPE 1: The creator is unverified.** When the creator is unverified, they cannot receive tips from _any_ users, and all tips from all possible users will go into pending)
2. **TYPE 2: No available path from user to creator.** The creator is "verified" (blue checkmark), but (a) the creator does not have a custodian that matches the user's custodian, OR (b) the creator does not have a custodian at all. 

Our error messages need to reflect the above two cases properly. For example, below is a case of TYPE 1, but the messaging reflects TYPE 2: 

![image](https://user-images.githubusercontent.com/11497541/133463169-7cfedc0c-0268-4532-a9b7-6b74310b7b25.png)

## Solution

**TYPE 1 TEXT**

>This creator is not signed up yet. Any tip you make will remain pending in your wallet and retry automatically for 90 days. Learn more.

**TYPE 2 TEXT** 

>This creator is currently not configured to receive tips from your wallet. Any tip you make will remain pending in your wallet and retry automatically for 90 days. Learn more.

cc: @kjozwiak

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.31.70 Chromium: 94.0.4606.71 (Official Build) beta (x86_64)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | macOS Version 10.15.7 (Build 19H1417)
```

See testing notes under https://github.com/brave/brave-browser/issues/18341#issuecomment-933506070
