### ISSUE TITLE
sometimes brave crashes when using barrons or marketwatch promotions

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1813]
## Description 

When installing Brave via the `barrons` or `marketwatch` promotions, Brave will sometimes get into a state where it starts crashing with the following:

`Framework!brave::OnBeforeStartTransaction_ReferralsWork(net::URLRequest*, net::HttpRequestHeaders*, base::RepeatingCallback const&, std::__1::shared_ptr) [brave_referrals_network_delegate_helper.cc : 26 + 0x19]`

• https://stats.brave.com/dashboard#crash/5bcf67e3f40ff6001e678fb0
• https://stats.brave.com/dashboard#crash/5bcf68bc87ad1a001e833bc4
• https://stats.brave.com/dashboard#crash/5bcf68bc96b930001e8c59ba
• https://stats.brave.com/dashboard#crash/5bcf6a9996b930001e8c6f73

## Steps to Reproduce

   1. install `0.55.20 Chromium: 70.0.3538.67` using `Brave-Browser-dowjones-marketwatch.pkg` or `Brave-Browser-dowjones-barrons.pkg`
   2. once you launch, you'll receive the promotional tab after ~30-40s
   3. leave the browser idle for a few minutes and Brave will eventually crash

## Actual result:

Sometimes brave is crashing when using the `barrons` or `marketwatch` promotions.

## Expected result:

Brave shouldn't be crashing when using the `barrons` or `marketwatch` promotions.

## Reproduces how often: 

50% or so? Initiating the promotion several times will eventually put you into the bad state.

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds?

Haven't tried but assuming it's in `beta` and `dev` as the channels are similar right now.

### Additional Information

* Reproduced on macOS (@kjozwiak)
* Reproduced on Win 10 x64 (@btlechowski)

CCing @emerick @aekeus

**Comment by GeetaSarvadnya** [comment]
Verification Passed on.


Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows

**Comment by btlechowski** [comment]
Verification passed on Windows 10 x64 and Windows 7 x64


Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows
