### ISSUE TITLE
Use synced Rewards Autocontribute Status as the Default for new Rewards Signups

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#18144]
## Description 
When users sign up for Rewards/Ads on a device, many turn off the autocontribute setting.  Some are surprised when they sign up a new device that the AC setting is per device.  We might be able to mitigate this problem by 1) Syncing a per device autocontribute setting if the user has also signed up for Brave sync, and then 2) Defaulting AC to off in any subsequent device sign ups if any of the devices have turned off AC.

cc: @Miyayes for your thoughts

**Comment by Miyayes** [comment]
In general, could this be like a "Rewards settings sync" category in Brave Sync (but not a full Rewards data sync with vBAT)?
