### ISSUE TITLE
Cannot tip directly to Twitch channels.

### ISSUE THREAD

**Issue by jnki** [brave/brave-browser#1814]
## Description 

When you visit a verified twitch channel and attempt to "send tip", it only lets you send a tip to twitch.tv, not the specific channel.

## Steps to Reproduce

   1. Visit a brave verified twitch channel ([mine as example](https://twitch.tv/jenoki))
   2. Click on Brave Rewards button

## Actual result:
![image](https://user-images.githubusercontent.com/17442109/47394935-9396f480-d71c-11e8-95c4-3588980d6fc4.png)

## Expected result:
Expect to see correct url for the specific twitch channel with verified badge, and be able to send tip to it.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 10 64bit 1809

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/888
* Verified STR
* Encountered #3327, #3330, #3265
* Verified that unverified publishers show generic twitch icon in Auto-Contribute table, Tips table, and Panel. 
![screen shot 2019-02-12 at 4 53 42 pm](https://user-images.githubusercontent.com/28145373/52671610-82e7d580-2ee9-11e9-9816-5de30f8a58e2.png)
![screen shot 2019-02-12 at 4 49 12 pm](https://user-images.githubusercontent.com/28145373/52671618-89764d00-2ee9-11e9-8bff-e1aef3844ae3.png)
* Verified that unverified publishers do not show favicon on tipping banner
![screen shot 2019-02-12 at 5 17 24 pm](https://user-images.githubusercontent.com/28145373/52671803-16210b00-2eea-11e9-8942-b99029d196b1.png)
* Verified that verified publishers show their favicon in Auto-Contribute table, Tips table, and Panel (except for scenario outlined in #3330)
![screen shot 2019-02-12 at 4 12 45 pm](https://user-images.githubusercontent.com/28145373/52671651-998e2c80-2ee9-11e9-90fc-3efc1e7587b3.png)
![screen shot 2019-02-12 at 4 13 01 pm](https://user-images.githubusercontent.com/28145373/52671652-9b57f000-2ee9-11e9-90f7-7c9e45690638.png)
* Verified that verified publishers do show a favicon on tipping banner
![screen shot 2019-02-12 at 5 18 15 pm](https://user-images.githubusercontent.com/28145373/52671850-3224ac80-2eea-11e9-8768-6eb7e9adde29.png)
* Verified that custom tipping banner shows for verified twitch publishers:
![screen shot 2019-02-12 at 5 19 09 pm](https://user-images.githubusercontent.com/28145373/52671909-53859880-2eea-11e9-8af1-d234efcc828f.png)
