### ISSUE TITLE
Add `10 ads per hour` option to Rewards onboarding flow

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18147]
## Description

In the Rewards onboarding, users can set their default ads per hour. However, the 10 ads per hour option is currently not shown. We should add the 10 per hour option in onboarding, per @lukemulks @ddvorin1.

![image](https://user-images.githubusercontent.com/11497541/133491452-37969b52-1a26-4424-a9e3-8efebb4bb7fe.png)

cc: @karenkliu

**Comment by karenkliu** [comment]
cc @rmcfadden3 For text this screen

**Comment by Miyayes** [comment]
Note: "(from your ad earnings)" is technically incorrect at this time, since the BAT could come from altruistic self-funding if the user is verified.

**Comment by rmcfadden3** [comment]
Only seeing 3 things here:

- "Go back" should be in sentence case, per style guide
- Merge parenthetical with main text on per-hour setting: "How many ads per hour would you like to see?"
- Per @Miyayes latest comment, remove parenthetical on BAT-contribution setting, and adjust text to: "How much monthly support (in BAT) would you like to give your favorite content creators?"

**Comment by adithyaakrishna** [comment]
@rmcfadden3 Can I work on this?

**Comment by adithyaakrishna** [comment]
If permitted, can I make the changes suggested by you in the last but one comment in the same PR?

**Comment by rmcfadden3** [comment]
@adithyaakrishna — I'll defer to @Miyayes, but it seems OK to me.

**Comment by adithyaakrishna** [comment]
@rmcfadden3 Okay sure, thanks a lot :)

**Comment by Miyayes** [comment]
Do we know if another option can be added to that list, and the list will rescale appropriately? Or, do we need to make a decision about which one of the 5 options should be removed for now? cc: @zenparsing

**Comment by adithyaakrishna** [comment]
> Do we know if another option can be added to that list, and the list will rescale appropriately? Or, do we need to make a decision about which one of the 5 options should be removed for now? cc: @zenparsing

@Miyayes IMO as it is wrapped in responsive styles it may scale properly, also in ads setting, there's another 0 ads per option which is not added here 😶

**Comment by Miyayes** [comment]
Superseded by new onboarding.
