### ISSUE TITLE
"Keep" option on download bar displays incorrectly

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#18157]
## Description 

Downloading files from a potentially insecure source presents the option to `Keep` or `Discard` those files in the download bar. In some cases, the `Keep` option appears to display incorrect on the bar, although the button _does_ still function properly. 

Note that this issue may be specific to macOS.

## Steps to Reproduce

   0. Ensure this setting is turned off on the Settings page
![image](https://user-images.githubusercontent.com/741836/133830510-461f0759-936a-46c9-971b-90d37040b190.png)

   1. Download a file/files from potentially insecure site
   2. Options to `Keep` and/or `Discard` 
   3. Observe `Keep` displays incorrectly

## Actual result:

![image](https://user-images.githubusercontent.com/3299098/133653952-93290900-e4c5-4a13-939c-6d827fae6d58.png)

## Reproduces how often: 

Intermittent

## Brave version (brave://version info)

v1.29.80

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Miscellaneous Information:

Community threads reporting this issue:
https://community.brave.com/t/download-on-download-bar-information-isnt-displaying-correctly/282804?u=mattches
https://community.brave.com/t/download-on-download-bar-information-isnt-displaying-correctly/282804/8?u=mattches

**Comment by rebron** [comment]
cc: @nullhook Can you take a look when you get a chance.?

**Comment by petemill** [comment]
note that you need this setting off to trigger this prompt:
```
![image](https://user-images.githubusercontent.com/741836/133830439-366ead30-6ef0-4054-9e17-debc45873872.png)

```

**Comment by nullhook** [comment]
This issue seems to be fixed with this PR: https://github.com/brave/brave-core/pull/9759
