### ISSUE TITLE
Connected publisher message is not shown in the BR panel for DDG

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#18153]
## Description 

Connected publisher message is not shown in the BR panel for DDG
## Steps to Reproduce

   1. Clean profile `1.31.41` staging env
   2. Enable rewards, connect KYC'd uphold wallet
   3. Open DDG (or any other connected pubs), click on the panel
   4. Connected pubs message isn't shown in the BR panel

## Actual result:

Connected publisher message is not shown in the BR panel for DDG
![image](https://user-images.githubusercontent.com/38657976/133555198-655147b8-6166-4aa8-82b6-400a5d57f34e.png)

## Expected result:

`1.29.x`

![image](https://user-images.githubusercontent.com/38657976/133555508-67d02640-3215-4587-993f-6bc18e4e59a7.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.31.41 Chromium: 94.0.4606.41 (Official Build) nightly (64-bit)
-- | --
Revision | 333e85df3c9b656b518b5f1add5ff246365b6c24-refs/branch-heads/4606@{#845}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @szilardszaloki

**Comment by LaurenWags** [comment]
cc @Miyayes @zenparsing @codybanxs - I am marking this as `release/blocking` and putting in the 1.31.x milestone for the same reasons we did this for https://github.com/brave/brave-browser/issues/17941 and https://github.com/brave/brave-browser/issues/17869. If you disagree please feel free to change.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.32.16 Chromium: 94.0.4606.54 (Official Build) nightly (64-bit)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | Windows 10 Version 21H1 (Build 19043.1237)

```
- Verified the STR from the description

**Comment by LaurenWags** [comment]
labelling `QA/Blocked` until uplift to 1.31.x is completed

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-core/pull/10181 was uplifted into `1.31.x` via https://github.com/brave/brave-core/pull/10224.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.31.70 Chromium: 94.0.4606.71 (Official Build) beta (x86_64)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | macOS Version 10.15.7 (Build 19H1417)
```

See testing notes under https://github.com/brave/brave-browser/issues/18341#issuecomment-933506070

--------------
