### ISSUE TITLE
System/OS ad notifications are missing icons

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#18154]
## Description 

System/OS ad notifications are missing icons

## Steps to Reproduce

1. new profile
2. launch Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3. open a new-tab page
4. click on the `Start using Rewards` button
5. open 3 or so more tabs
6. wait a bit
7. move the mouse/keyboard
8. look at the system-level Brave Ads ad notification

Actual Result:
It's missing its icon/favicon

<img width="1680" alt="Screen Shot 2021-09-16 at 3 29 01 AM" src="https://user-images.githubusercontent.com/387249/133600378-6a60236a-5e66-4f5b-a01e-6a9fbc84d497.png"> | 
<img width="364" alt="Screen Shot 2021-09-16 at 3 53 18 AM" src="https://user-images.githubusercontent.com/387249/133600656-99d1b83a-8a7e-498a-acb6-dbd7a659b9fe.png">

## Expected Result:
Should have its respective icon/favicon

<img width="1680" alt="Screen Shot 2021-09-16 at 3 43 23 AM" src="https://user-images.githubusercontent.com/387249/133600628-39ef9c21-9118-44ee-b231-9d023af1e650.png">

BTW: custom-ad notifications are fine 👍 

<img width="1358" alt="Screen Shot 2021-09-16 at 3 09 12 AM" src="https://user-images.githubusercontent.com/387249/133600804-a0790b38-1282-4987-bd74-1bf1aa533a7a.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.31.46 Chromium: 94.0.4606.41 (Official Build) nightly (x86_64)
-- | --
Revision | 333e85df3c9b656b518b5f1add5ff246365b6c24-refs/branch-heads/4606@{#845}
OS | macOS Version 12.0 (Build 21A5506j)

cc @kjozwiak @tmancey @btlechowski @GeetaSarvadnya

**Comment by tmancey** [comment]
@stephendonner can you please reboot your computer and see if that resolves the issue. System notifications show the app icon, so this bug is outside of the ads library. But first, lets see if a reboot resolves the issue.

**Comment by stephendonner** [comment]
> @stephendonner can you please reboot your computer and see if that resolves the issue. System notifications show the app icon, so this bug is outside of the ads library. But first, lets see if a reboot resolves the issue.

I still see this on two separate MacBook Pro laptops, both after rebooting.

**Comment by kjozwiak** [comment]
Definitely looks like a regression as I managed to reproduce this on my MPB as well. Example:

Using `1.31.46 Chromium: 94.0.4606.41`, I could reproduce the issue @stephendonner was seeing re: the icon missing form the ad notification. Example:

**`Custom ad notification (working)`** | **`Default ad notification (Broken)`**
------------------------------------------|-------------------------------------------
<img width="454" alt="Screen Shot 2021-09-16 at 1 33 54 PM" src="https://user-images.githubusercontent.com/2602313/133659986-979a8c5b-4d2b-4747-9443-5d9eb8374330.png"> | <img width="376" alt="Screen Shot 2021-09-16 at 1 36 15 PM" src="https://user-images.githubusercontent.com/2602313/133660017-77fcaa51-02cc-4902-98af-d2bd5e955217.png">

I double checked `1.31.37 Chromium: 93.0.4577.63` which was still using `93.0.4577.63` and the icon was being displayed without any issues:

<img width="372" alt="Screen Shot 2021-09-16 at 1 41 17 PM" src="https://user-images.githubusercontent.com/2602313/133660085-10c73e05-15e2-4322-b7eb-e5d302111b67.png">

@tmancey definitely a c94 regression that needs to be fixed for `1.30.x`.

Builds used during verification:

```
Brave | 1.31.46 Chromium: 94.0.4606.41 (Official Build) nightly (x86_64)
--- | ---
Revision | 333e85df3c9b656b518b5f1add5ff246365b6c24-refs/branch-heads/4606@{#845}
OS | macOS Version 11.5.2 (Build 20G95)
```

```
Brave | 1.31.37 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
--- | ---
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)
```

**Comment by stephendonner** [comment]
There's also this, on `dev`, even, so it feels lower level than `Ads`:

<img width="714" alt="Screen Shot 2021-09-16 at 10 46 06 AM" src="https://user-images.githubusercontent.com/387249/133660508-1e2cc7d8-138a-4d14-82e6-ceb2d717d574.png">

**Comment by stephendonner** [comment]
This is lowel-level than `Ads`, so removing its keyword and clearing from `Ads project`.

**Comment by bsclifton** [comment]
cc: @simonhong

**Comment by LaurenWags** [comment]
labelling as `QA/Blocked` until uplift is completed and an RC containing this fix is created so it can be tested.

**Comment by LaurenWags** [comment]
Verification **PASSED** on `macOS 11.6 x64` using the following build:

```
Brave	1.30.84 Chromium: 94.0.4606.54 (Official Build) (x86_64)
Revision	c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS	macOS Version 11.6 (Build 20G165)
```

**`Installer`** | **`Applications`** | **`Notification Prompt`** | **`Ads Notification`**
---------------|--------------------|--------------------|--------------------------
<img width="609" alt="Installer (1)" src="https://user-images.githubusercontent.com/28145373/134528722-5f9474e5-63d6-480e-a664-84896278162a.png"> | <img width="440" alt="Applications (1)" src="https://user-images.githubusercontent.com/28145373/134528741-466e4278-a760-4464-8d87-bead3775b6af.png"> | <img width="356" alt="Notification prompt (1)" src="https://user-images.githubusercontent.com/28145373/134528756-867b12fb-0a34-494f-aa84-49d46ed72154.png"> | <img width="352" alt="Ad Notification" src="https://user-images.githubusercontent.com/28145373/134528770-b537bfe0-4b19-40df-9f2a-2d34a2f02c50.png">

--------------------
