### ISSUE TITLE
Add Jive Search as default search engine

### ISSUE THREAD

**Issue by gitty-git-git** [brave/brave-browser#1815]
## Description 

I was directed to post here from https://www.reddit.com/r/BATProject/comments/9pdu7u/duckduckgo_as_the_default_search_engine/?utm_content=full_comments&utm_medium=message&utm_source=reddit&utm_name=frontpage. 

I would like to suggest adding [Jive Search](https://jivesearch.com) as the default search provider. If not, at least add it as a choice as it is essentially an open source version of DuckDuckGo with !bangs and instant answers. I think JS aligns better with Brave's open source philosophy and that's why I suggest it as the default as open source provides better privacy than a closed source search engine.

## Steps to Reproduce

Nothing to reproduce.
   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Don't have plans to make Jive search a default search engine. Users have the ability to make Jive their default search engine though. Thanks for the suggestion. Marking closed/wontfix.

**Comment by gitty-git-git** [comment]
There isn't a way to add Jive Search unless I'm missing something. How can you edit the list of search engines?

**Comment by srirambv** [comment]
You can manually add search engine by visiting `chrome://settings/searchEngines` and Click on the Add button and `https://jivesearch.com/?q=%s`
