### ISSUE TITLE
C94 - URL border blue focus ring issue

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#18156]
## Description 

C94 - URL border color changed to dark blue 

## Steps to Reproduce

   1. Clean profile 1.31.44
   2. Open a NTP
   3. URL border color changed to dark blue 

## Actual result:

URL border color changed to dark blue 
![image](https://user-images.githubusercontent.com/38657976/133612466-febdc2de-c5d3-49d6-b466-219f63240f80.png)

## Expected result:

`1.29.x`
![image](https://user-images.githubusercontent.com/38657976/133612573-4d1aaaf3-bb55-43a8-bb1f-fcd2ee2725ad.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.31.44 Chromium: 94.0.4606.41 (Official Build) nightly (64-bit)
-- | --
Revision | 333e85df3c9b656b518b5f1add5ff246365b6c24-refs/branch-heads/4606@{#845}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @mkarolin @simonhong

**Comment by GeetaSarvadnya** [comment]
blue focus ring issue in set default browser popup
![image](https://user-images.githubusercontent.com/38657976/133638289-0a96f55b-fca2-46bc-9c41-72c5953ed139.png)

**Comment by simonhong** [comment]
@GeetaSarvadnya button's ring in popup also will be fixed by https://github.com/brave/brave-core/pull/10119

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.31.50 Chromium: 94.0.4606.50 (Official Build) nightly (64-bit)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | Windows 10 Version 21H1 (Build 19043.1165)

```
Verified https://github.com/brave/brave-browser/issues/18156#issue-998158484 and https://github.com/brave/brave-browser/issues/18156#issuecomment-920995734 and ensured focus ring isn't shown.

**_NTP_**
![image](https://user-images.githubusercontent.com/38657976/133777704-4e54437d-682d-4db4-b91b-23b95642c183.png)

**_Set as default_**
![image](https://user-images.githubusercontent.com/38657976/133777795-b21c0802-24bc-4e4f-9b7c-1881edc541bd.png)

**Comment by kjozwiak** [comment]
Removed both `QA Pass-Win64` & `QA Pass-macOS` as they were checked on `1.31.x`. We'll need to do a quick check on either platform with `1.30.x` when we kick off the next RC that includes `94.0.4606.54`.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.30.84 Chromium: 94.0.4606.54 (Official Build) (x86_64)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | macOS Version 10.15.7 (Build 19H1417)
```

Confirmed URL focus bar color is no longer blue:

<img width="1029" alt="18156" src="https://user-images.githubusercontent.com/28145373/134518479-f77dcbf8-ac1e-4005-95fc-c02d9ceec7c5.png">
