### ISSUE TITLE
Privacy/Security: Uphold typekit API is getting blocked on Brave-Core (0.55.20 - Hotfix 1)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#1816]
The typekit call from Uphold is getting blocked (as a tracker) while calling from Brave Rewards Panel. 

We have asked for Uphold to download and host fonts; meanwhile filing issues to track it.

See image ---
![image](https://user-images.githubusercontent.com/35932307/47396156-8a873280-d6de-11e8-8771-46aa719dfc5d.png)

Assign to @tomlowenthal for 0.56 milestone

**Comment by mandar-brave** [comment]
An ask has been made to Uphold to check if they can download the font locally and not make a call. Opening this for tracking at our end. cc @tomlowenthal

**Comment by fmarier** [comment]
This is still an issue:
![Screenshot from 2020-07-10 11-24-29](https://user-images.githubusercontent.com/167821/87186209-f12bf580-c29f-11ea-8879-f6ede912a652.png)

**Comment by fmarier** [comment]
This is not something that we can fix on our end.
