### ISSUE TITLE
Include web-discovery-project in brave

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#18166]

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.62 Chromium: 94.0.4606.54 (Official Build) beta (x86_64)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | macOS Version 11.6 (Build 20G165)


Went through and verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/9381#issuecomment-925257846 as per the following:

* ensured that `Web Discovery Project` is disabled by default via `brave://settings/search` 
* ensured that clicking on `Learn more` opens https://brave.com/privacy/browser/#web-discovery-project without any issues
* ensured that `WDP.isRunning` returns `false` when `Web Discovery Project` is disabled
* ensured that `WDP.isRunning` returns `true` when `Web Discovery Project` is enabled

**`WDP.isRunning = false`** | **`WDP.isRunning = true`**
-------------------------------|---------------------------------
<img width="752" alt="Screen Shot 2021-09-27 at 3 13 24 PM" src="https://user-images.githubusercontent.com/387249/134993305-535317db-766d-4e30-85f9-1b77d31bd429.png"> | <img width="752" alt="Screen Shot 2021-09-27 at 3 14 13 PM" src="https://user-images.githubusercontent.com/387249/134993308-b0d62a82-1e98-4985-b65d-09f7d4a74b97.png">


* ensured that `WDP.isRunning` stays `true` if enabled after restarting the browser several times
* ensured that `WDP.isRunning` stays `false` if disabled after restarting the browser several times
* ensured that an error was displayed via the browser console when using `WDP.modules['web-discovery-project'].background.webDiscoveryProject.patternsLoader.resourceWatcher.forceUpdate()` but `WDP.isRunning` is `false`
* ensured that `WDP.modules['web-discovery-project'].background.webDiscoveryProject.patternsLoader.resourceWatcher.forceUpdate()` displayed the correct data when `WDP.isRunning` is enabled/appearing as `true`

**`Disabled Output`** | **`Enabled Output`**
------------------------|---------------------------
<img width="752" alt="Screen Shot 2021-09-27 at 3 16 06 PM" src="https://user-images.githubusercontent.com/387249/134993490-2ce63710-71f8-4c99-b28f-33a0aacef08f.png"> | <img width="1010" alt="Screen Shot 2021-09-27 at 3 18 22 PM" src="https://user-images.githubusercontent.com/387249/134993561-f3266a0c-ec97-470e-b401-28d6446354cd.png">


<img width="1010" alt="Screen Shot 2021-09-27 at 3 20 11 PM" src="https://user-images.githubusercontent.com/387249/134993616-9af1191b-6a71-494f-8266-37083ec65af1.png">


* waited ~10min once `WDP` was disabled after confirming that `WDP.isRunning` is `false` and ensured that no calls to `wdp.brave.com` occurred
