### ISSUE TITLE
Add auto lock timer for wallet page

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#18172]
- The Brave Wallet should have an auto lock timeout (keyring lock)
- There should be an auto lock timeout setting in brave://settings/wallet which allows you to enter the number of minutes for automatically locking an inactive wallet with a default value of 5.
`The number of minutes to wait before automatically locking the wallet interface`

**Comment by bbondy** [comment]
cc @yrliou or @darkdh whichever of you is available first to work on this after current tasks

**Comment by darkdh** [comment]
as discussed in slack,
we should have a mojo API like `NotifyUserInteraction` in KeyringController which will reset the native timer.
When native timer timed out, it will automatically lock the keyring.
All platforms just need to call the same mojo API to indicate user is active.
