### ISSUE TITLE
Deprecate `brave_ads::AdsService::SetNotificationAdsPerHour` and directly access the preference

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#18178]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/18908

<details>

Verified changing ads per hour in `brave://rewards` changes the frequency of notification ads

</details>
