### ISSUE TITLE
Brave news display ads/advertisers should round robin before showing the same ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#18184]
## Description 

Brave news display ads/advertisers should round robin before showing the same ads

## Steps to Reproduce

   1. View news display ads

## Actual result:

Ads and advertisers do not round robin before showing the same ad or advertiser

## Expected result:
Ads and advertisers should round robin before showing the same ad or advertiser

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.31.86 Chromium: 95.0.4638.50 (Official Build) (64-bit)
-- | --
Revision | 3e9db37693d0cf8e31a89fbcf50401ae91125cef-refs/branch-heads/4638@{#816}
OS | Windows 10 Version 21H1 (Build 19043.1288)

```
- Verified the test plan mentioned in https://github.com/brave/internal/issues/819
