### ISSUE TITLE
Suggestion re: "Privacy and security" placement in brave://settings/

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#1819]
## Description 

This may be an item that there is a current plan of record for. Please close if this is the case. Couldn't locate an existing issue that covered it.

In `brave://settings/`, if I want to access `Privacy and security` settings, I need to click to expand the `Advanced settings` 

Suggesting we feature `Privacy and security` settings above the fold, and expose by default when a user navigates to `brave://settings/`.

We currently assume that users are comfortable enough to access `Advanced` settings to discover privacy settings. Additional click and discovery required. Isn't easy to locate.

I strongly suspect this is already something people have discussed, and this is likely a waste of an issue. That said, am noting just in case.  

@tomlowenthal ^ I suspect you've got the answer for this one. 

## Steps to Reproduce

   1.  in the URL bar, enter: brave://settings/
   2. scroll down, below `people`and `appearance`. 
   3. hope that the users venture into`Advanced` settings-territory. 

## Actual result:

Sub-level, post-click placement of privacy and security settings. 

## Expected result:
Privacy and Security for non-advanced preference-setting users.

## Brave version (brave://version info)

Version 0.55.20 Chromium: 70.0.3538.67 (Official Build) (32-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tomlowenthal** [comment]
The 0.55 series doesn't have our settings design improvements — there are only small changes from Chrome. Probably worth looking at this against the updated designs instead.

**Comment by fmarier** [comment]
Implemented in https://github.com/brave/brave-browser/issues/16470.
