### ISSUE TITLE
Removing tile link on home page and then removing a second one causes previously removed to reappear in lineup

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#182]
## Description 
If you remove a home page tile link at startup, It will reappear if another one is removed

## Steps to Reproduce

   1. Open Brave
   2. Remove a tile link from the home page.
   3. Remove a second tile link from the home page.

 ## Actual result:
The first tile link reappears in the lineup

## Expected result:
Expect removed tiles to remain removed

## Reproduces how often: 
Easily

## Brave version (about:brave info)
Brave logo
Brave
Version 66.0.3359.117 (Developer Build) (64-bit)

### Reproducible on current release:
No

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? NA
- Does the issue reproduces on Chrome? NA

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Windows 7
