### ISSUE TITLE
No balance on wallet page with new profile

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#18208]
## Description 

No balance on wallet page, console shows errors

![image](https://user-images.githubusercontent.com/2965009/133971423-1f637452-39e4-4f1f-9581-df71e9f74ccc.png)

## Steps to Reproduce

   1. new profile
   2. restore wallet
   3. pay attention to main account balance

## Actual result:

the page is broken

## Expected result:

balance visible, no errors in console

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
I think this is the same as https://github.com/brave/brave-browser/issues/18265

**Comment by spylogsster** [comment]
seems fixed
