### ISSUE TITLE
Settings Query

### ISSUE THREAD

**Issue by Nihal247** [brave/brave-browser#18214]
![Screenshot (84)](https://user-images.githubusercontent.com/80682093/134017428-11c38ebc-38b0-4f5f-a37c-68f527ef8c48.png)

Is my IP Address collected when these settings are turned on ☝?

**Comment by fmarier** [comment]
Unless you use a VPN, your IP address will of course be part of these requests when your browser makes them. However, since these features exist to collect anonymous data, we do not store the IP addresses associated with these network requests.

**Comment by Nihal247** [comment]
Thanks @fmarier

**Comment by fmarier** [comment]
We've updated our support page to add this important detail: https://support.brave.com/hc/en-us/articles/360017989132
