### ISSUE TITLE
[Question] Is there a way to get brave stats, top sites and brave wallet data from local computer?

### ISSUE THREAD

**Issue by ScottCowe** [brave/brave-browser#18218]
I am trying to make a browser extension to edit the new tab page. However, brave stats, top sites and brave wallet only appear on the brave new tab page? Is there any way to add these features to a html file?

**Comment by bsclifton** [comment]
Sorry that this has been unanswered for such a long time ☹️ 

For those curious, you can find most of this information in the `Preferences` file in the profile directory.
