### ISSUE TITLE
Improve error message for IPFS gateway without Origin isolation

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#18212]
## UX problem

A check was introduced in https://github.com/brave/brave-browser/issues/16999 that blocks use of gateways without Origin isolation:

> ![2021-09-20_15-17](https://user-images.githubusercontent.com/157609/134009138-bfb692a7-df31-4487-b6e0-6b34b307084a.png)

The error message "Invalid gateway address" is bit confusing, because `ipfs.io` is a valid gateway, it is just insecure when used for loading websites that expect Origin isolation.

## Proposed fix

I suggest renaming the error message to something long of the lines "Only a valid IPFS gateway  with Origin isolation enabled can be used in Brave"

cc @spylogsster

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.32.7 Chromium: 94.0.4606.50 (Official Build) nightly (x86_64)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. new profile
2. launch Brave
3. open `brave://settings/ipfs`
4. click on the `Change` button next to `IPFS public gateway address`
5. enter `https://ipfs.io`
6. click `Submit`

Confirmed we now see `Only a valid IPFS gateway with Origin isolation enabled can be used in Brave` as the more-appropriate error message.

<img width="1312" alt="Screen Shot 2021-09-20 at 9 27 18 PM" src="https://user-images.githubusercontent.com/387249/134114905-85e759ce-c506-47ff-96fd-20fb95c3dab1.png">
