### ISSUE TITLE
iCloud.com on desktop gives "Your browser is not supported" error message

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#18228]
## Description 

Visiting iCloud.com in any Brave build at this time lands you on `Your browser is not supported` error page. Shields up/down do not appear to make a difference, nether does a fresh profile or clearing cache/site data. No errors shown in dev tools console.
![image](https://user-images.githubusercontent.com/3299098/134070856-9646f12c-8f2f-4ab4-9a95-4f26e56ad19f.png)

## Steps to Reproduce

1. Visit https://icloud.com

## Reproduces how often: 

Always

## Brave version (brave://version info)

Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

User reports:
https://community.brave.com/t/just-got-your-browser-is-not-supported-from-icloud-com/284365/6
https://old.reddit.com/r/brave_browser/comments/ps03fa/wwwicloudcom_no_longer_works_with_brave/

**Comment by ryanbr** [comment]
Re-open to confirm the fix is working with everyone.

**Comment by andreprawira** [comment]
@ryanbr  it wasnt working about 3 hours ago, just checked it again, now its working

**Comment by ryanbr** [comment]
Give it 24hrs @andreprawira

**Comment by Tonev** [comment]
@ryanbr 

Your fix seems to work. I added `icloud.com##+js(aopw, navigator.brave)` via `brave://adblock` and the page no longer tells me my browser is unsupported.

**Comment by ryanbr** [comment]
Its in the latest adblock brave://components/  just for an update there. No need for a manual filter

**Comment by Tonev** [comment]
Sure, but your suggestion to manually update the component didn't work, at least for me, so I checked if your fix works by manually entering it via `brave://adblock`.

**Comment by ryanbr** [comment]
Investigating. Will update thread.

**Comment by andreprawira** [comment]
@ryanbr been 24 hrs, its all good cause i use icloud multiple times a day everyday

**Comment by antonok-edm** [comment]
This is still not be 100% fixed by the new `aopw` scriptlet for some users due to a race condition in the cosmetic filter injection code, but I'm preparing a PR with a solution that appears to work reliably.

**Comment by valynor** [comment]
Still not working here: 
-Brave Shields are OFF (except x-site cookies blocked and fingerprinting blocked)
-I use uBlock Origin 1.38.0 instead - just refreshed all filter lists

I can only access icloud.com when I add `icloud.com##+js(aopw, navigator.brave)` to "My filters" in uBO.

**Comment by antonok-edm** [comment]
@valynor we're getting the solution from https://github.com/brave/brave-core/pull/10192 into the next hotfix release, which should be coming out later today.

**Comment by LaurenWags** [comment]
labelling as `QA/Blocked` until this is uplifted to 1.30.x and an RC is created where it can be tested

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.30.84 Chromium: 94.0.4606.54 (Official Build) (64-bit)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | Windows 10 Version 21H1 (Build 19043.1237)

```
- Verified using 1.30.84 opening a bunch of new tabs in succession and visiting https://icloud.com doesn't get redirected to https://icloud.com/unsupported_browser

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.30.84 x64 build
- Verified test plan from [https://github.com/brave/brave-core/pull/10192](https://github.com/brave/brave-core/pull/10192)
- Verified on both normal tab and private tabs
- Verified quickly opening `https://icloud.com` doesn't get redirected to `https://icloud.com/unsupported_browser` 
------------
Verification passed on Samsung Tab A with Android 10 running 1.30.84 x64 build
- Verified test plan from [https://github.com/brave/brave-core/pull/10192](https://github.com/brave/brave-core/pull/10192)
- Verified on both normal tab and private tabs
- Verified quickly opening `https://icloud.com` doesn't get redirected to `https://icloud.com/unsupported_browser`
