### ISSUE TITLE
Beta disk-image icon background should be transparent

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#18223]
## Description 

Beta disk-image icon background should be transparent

Found while testing https://github.com/brave/brave-browser/issues/17441

## Steps to Reproduce

   1.  download `1.31.54` from `https://github.com/brave/brave-browser/releases/tag/v1.31.54`
   2. double-click to uncompress the file
   3. look at the disk-image icon

## Actual result:

<img width="110" alt="Screen Shot 2021-09-20 at 11 17 42 AM" src="https://user-images.githubusercontent.com/387249/134054376-d3b5dffb-4ea7-4ca1-a38f-e4efb6907c64.png">

## Expected result:
No white background; it should be transparent

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.31.54 Chromium: 94.0.4606.50 (Official Build) beta (x86_64)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | macOS Version 11.6 (Build 20G165)

/cc @simonhong

**Comment by karenkliu** [comment]
Hi, sorry I found a white background included in the icon export - it's fixed now. @simonhong
