### ISSUE TITLE
Speedreader icon disappears after toggling on/off a few times

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#18234]
## Description 

Speedreader icon disappears after toggling on/off a few times; found while testing https://github.com/brave/brave-browser/issues/18151

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `https://brave.com/blog/`
   4. click on the reader-mode icon and click `Turn on Speedreader`
   5. toggle Speedreader `off`
   6. toggle Speedreader `on` 

## Actual result:

The Speedreader icon and mode disappear

(A `shift` + `reload` bring it back.)

<img width="1312" alt="Screen Shot 2021-09-20 at 4 58 08 PM" src="https://user-images.githubusercontent.com/387249/134092490-1de37c56-6a45-4387-806b-4ab53486ebe3.png">

## Expected result:

Should still be an option to toggle Speedreader back on

<img width="1312" alt="Screen Shot 2021-09-20 at 4 58 01 PM" src="https://user-images.githubusercontent.com/387249/134092509-9e83bbbb-b89b-4adc-92c0-38ad1153d41a.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.32.5 Chromium: 94.0.4606.50 (Official Build) nightly (x86_64)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | macOS Version 11.6 (Build 20G165)

/cc @keur

**Comment by Tonev** [comment]
@stephendonner 

Easily reproduced the issue you've described. I have some additions to your Github ticket that might be of interest to you and @keur.

- There is no need to reload the page via `Shift` + `Reload`, switching tabs is enough to bring back the icon.

https://user-images.githubusercontent.com/20608253/134132785-d8dd532f-a08c-487d-aae5-a4c3935b75c7.mp4

- After hiding the `Speedreader` icon (performing your `STR`), if users close the tab, and then re-open it at some later point, the `Speedreader` icon will still be gone. In addition to this, I figured out that the `Speedreader` toggle won't go back to `Disabled` after clearing **all** browsing data. Please, confirm to me whether this is intentional behavior so I can fill another bug report regarding reader mode, if needed.


https://user-images.githubusercontent.com/20608253/134133267-30dd0ab9-fe5a-4a8f-b008-3f0fc107bf47.mp4

---
P.S I filled the following reader mode bug - https://github.com/brave/brave-browser/issues/18243. Thank you for tagging me, @stephendonner :+1:

**Comment by Tonev** [comment]
@keur 

Could you please let me know if I should fill an issue about the following:

> I figured out that the Speedreader toggle won't go back to Disabled after clearing all browsing data.

That's shown in the second video in my previous comment. Long story short, enabling `Speedreader` for a specific web page makes that web page open in `Speedreader` mode every time, even if **all** browsing data is cleared.

**Steps to reproduce**:

1. Enable `Speedreader` via `brave://settings/appearance`.
2. Open `https://www.reuters.com/business/environment/us-seeks-double-climate-change-aid-developing-nations-biden-2021-09-21/`.
3. Enable `Speedreader` mode via the icon in the address bar.
4. Close `https://www.reuters.com/business/environment/us-seeks-double-climate-change-aid-developing-nations-biden-2021-09-21/`.
5. Open `brave://settings/clearBrowserData`.
6. Clear all browsing data for `All time`.
7. Open `https://www.reuters.com/business/environment/us-seeks-double-climate-change-aid-developing-nations-biden-2021-09-21/`.

**Actual result**:

The article is still in `Speedreader` mode.

**Expected result**:

I guess the article shouldn't load in `Speedreader` mode after clearing **all** browsing data.

**Comment by keur** [comment]
> @keur
> 
> Could you please let me know if I should fill an issue about the following:
> 
> > I figured out that the Speedreader toggle won't go back to Disabled after clearing all browsing data.
> 
> That's shown in the second video in my previous comment. Long story short, enabling `Speedreader` for a specific web page makes that web page open in `Speedreader` mode every time, even if **all** browsing data is cleared.
> 
> **Steps to reproduce**:
> 
> 1. Enable `Speedreader` via `brave://settings/appearance`.
> 2. Open `https://www.reuters.com/business/environment/us-seeks-double-climate-change-aid-developing-nations-biden-2021-09-21/`.
> 3. Enable `Speedreader` mode via the icon in the address bar.
> 4. Close `https://www.reuters.com/business/environment/us-seeks-double-climate-change-aid-developing-nations-biden-2021-09-21/`.
> 5. Open `brave://settings/clearBrowserData`.
> 6. Clear all browsing data for `All time`.
> 7. Open `https://www.reuters.com/business/environment/us-seeks-double-climate-change-aid-developing-nations-biden-2021-09-21/`.
> 
> **Actual result**:
> 
> The article is still in `Speedreader` mode.
> 
> **Expected result**:
> 
> I guess the article shouldn't load in `Speedreader` mode after clearing **all** browsing data.

If Speedreader is still enabled in settings then the article should still load in Speedreader mode. I don't think clearing browsing data resets that in brave://settings

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.70 Chromium: 100.0.4896.46 (Official Build) beta (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

Followed the steps of my original issue here, from https://github.com/brave/brave-browser/issues/18234#issue-1001579175

example | example | example | example | example
---------|----------|---------|-----------|---------
<img width="1312" alt="Screen Shot 2022-03-28 at 1 01 57 PM" src="https://user-images.githubusercontent.com/387249/160478277-70c6999c-4a6c-4c2f-8e8a-bdb851a7d27c.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 1 02 01 PM" src="https://user-images.githubusercontent.com/387249/160478288-1bc70588-68b1-4ac8-9877-910384eed68f.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 1 02 12 PM" src="https://user-images.githubusercontent.com/387249/160478295-0bf78752-43d7-481f-9c86-031dca34928a.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 1 02 19 PM" src="https://user-images.githubusercontent.com/387249/160478301-e704b7be-8661-46b3-8961-d6e038cc039d.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 1 02 22 PM" src="https://user-images.githubusercontent.com/387249/160478305-ca0fe155-61c4-40e1-b46d-61b90b7d8ebd.png">

Confirmed I was able to `enable`/`disable` the Speedreader feature correctly from its icon in the URL bar

**Comment by MadhaviSeelam** [comment]
Brave | 1.38.78 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 11 Version 21H2 (Build 22000.593)

- Fresh profile
- Launch Brave
- Load https://brave.com/blog/
- Click on the reader-mode icon and click Turn on Speedreader
- Toggle Speedreader on
- Toggle Speedreader off
- Verified turning on and off few times
- Verified Speedreader on/off toggle in the URL bar works expected  and the icon do not disappear

ex1|ex2|ex3|ex4
---|---|---|---
<img width="943" alt="disabled settings -1" src="https://user-images.githubusercontent.com/98358127/161654040-9f34a300-b01c-4862-b8cd-3cdee942131c.png">|<img width="952" alt="click speed reader" src="https://user-images.githubusercontent.com/98358127/161654044-c40678cd-e50b-48f0-bc04-527ae65ec6f5.png">|<img width="947" alt="Turn on speed reader " src="https://user-images.githubusercontent.com/98358127/161654258-cccd82fc-a2fb-4701-a918-2e4b6e83ebcc.png">|<img width="952" alt="Turn off speed reader " src="https://user-images.githubusercontent.com/98358127/161654119-44a3e06a-0b99-4426-abd1-5e5d2d1110fa.png">
