### ISSUE TITLE
Body text in Rewards settings is too light / low contrast

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#1824]
The body text in Brave Rewards settings is hard to read because of low contrast.

An example of the low-contrast text in question is: 

"Earn tokens by viewing ads in Brave. Ads presented are based on your interests, as inferred from your browsing behavior. No personal data or browsing history ever leaves your browser"

**Comment by jenn-rhim** [comment]
addressed in here: https://github.com/brave/brave-ui/pull/235

**Comment by kjozwiak** [comment]
@davidtemkin seems a bit darker than before but wanted to double check with you if this is good enough or should the text be a bit more darker? Added both examples below:

Using `0.55.22 Chromium: 70.0.3538.77` which is the currently released build:

<img width="635" alt="old" src="https://user-images.githubusercontent.com/2602313/47974738-f96a7100-e078-11e8-8f97-706cd6e54920.png">

Using `0.56.8 Chromium: 70.0.3538.77` which is the current RC which includes the above fix:

<img width="644" alt="new" src="https://user-images.githubusercontent.com/2602313/47974743-fc656180-e078-11e8-8315-2f0dc95b0598.png">

**Comment by davidtemkin** [comment]
This is a lot better, but perhaps a little darker would be good? @jenn-rhim ?

**Comment by kjozwiak** [comment]
@jenn-rhim we'll most likely need a new RC build because of https://github.com/brave/brave-browser/issues/1991. If we want to get the above text a bit more darker as per @davidtemkin in the above comment, we'll need to get this fixed before the RC2 builds.

If we don't have the time to get this fixed today, we can create a follow up issue and QA can mark this as verified.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.14 x64` - **PASSED**

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X
