### ISSUE TITLE
Unable to exit reader mode when `Speedreader` is disabled

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#18242]
## Description 

Users can't exit reader mode if `Speedreader` is disabled. After opening an article in reader mode, users can't exit the reader mode by clicking on the icon in the address bar.

## Steps to Reproduce

   1. Ensure `Speedreader` is disabled via `brave://settings/appearance`.
   2. Open `https://www.reuters.com/technology/cryptocurrencies-selloff-widens-bitcoin-down-nearly-4-ether-6-2021-09-07/`.
   3. Click on the reader mode icon in the address bar to **enter** reader mode.
   4. Click on the reader mode icon in the address bar to **exit** reader mode.

## Actual result:

The article remains in reader mode.

## Expected result:
Clicking on the reader mode icon when an article is in reader mode should exit reader mode.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

<html>
<body>

Brave | 1.32.4 Chromium: 94.0.4606.50 (Official Build) nightly (64-bit)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@stephendonner https://github.com/brave/brave-browser/issues/17949#issuecomment-923102839

**Comment by stephendonner** [comment]
@Tonev thanks a ton for catching and filing this; not sure how I missed it when verifying, before? 😦 

/cc @keur

**Comment by Tonev** [comment]
Happy to help, @stephendonner :wink:

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Windows 10 x64 -1.31.66`

```

Brave | 1.31.66 Chromium: 94.0.4606.61 (Official Build) beta (64-bit)
-- | --
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | Windows 10 Version 21H1 (Build 19043.1237)

```

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.70 Chromium: 100.0.4896.46 (Official Build) beta (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

Followed the original steps to reproduce from https://github.com/brave/brave-browser/issues/18242#issue-1001823256.

example | example | example | example | example
---------|---------|----------|----------|---------
<img width="1312" alt="Screen Shot 2022-03-28 at 1 13 04 PM" src="https://user-images.githubusercontent.com/387249/160479850-3be2b3f8-5a70-4c41-b3b9-d6b6853db7f7.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 1 13 08 PM" src="https://user-images.githubusercontent.com/387249/160479863-17a35ff0-6331-45f2-bbea-777ecd9ca545.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 1 13 11 PM" src="https://user-images.githubusercontent.com/387249/160479868-cef26041-f8bc-4382-b86d-703adec2f0ce.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 1 13 14 PM" src="https://user-images.githubusercontent.com/387249/160479870-50ebe782-c3e9-4206-b310-6a3b697ccc1f.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 1 13 20 PM" src="https://user-images.githubusercontent.com/387249/160479872-a9226b93-9f2e-40e3-a7e5-3fdfa135a4db.png">


Confirmed I was able to enter and exit Speedreader mode at will, including after initial enable/disable.
