### ISSUE TITLE
Asset change needed for Tips from Donations

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#1825]
## Description 

As the feature name has changed, the graphic representation needs to be replaced accordingly.

Current:
![image](https://user-images.githubusercontent.com/4369856/47459008-e2ca3d00-d78f-11e8-8b49-6508c7ee97b5.png)

**Updated: (assets attached, for Welcome & Settings page)**
![screen shot 2018-10-24 at 1 18 52 pm](https://user-images.githubusercontent.com/4369856/47458974-ce864000-d78f-11e8-8f86-ec8090677ac1.png)

[assets-2.zip](https://github.com/brave/brave-browser/files/2512160/assets-2.zip)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@jenn-rhim  any chance we can change it from the thumbs up to something else. Looks too close to FB icon.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

Icons in rewards welcome page
![image](https://user-images.githubusercontent.com/34715963/51357532-b472aa00-1abf-11e9-87a9-1aaa552fa465.png)

Icons in rewards settings page were not update: https://github.com/brave/brave-browser/issues/3013

**Comment by ryanml** [comment]
See comment regarding this here: https://github.com/brave/brave-browser/issues/3013#issuecomment-455383938
