### ISSUE TITLE
Farble in ServiceWorkers

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#18251]
Currently we are not farbling in ServiceWorkers, only WebWorkers.  We should apply the same protections in ServiceWorkers

QA tests here: https://dev-pages.brave.software/fingerprinting/farbling.html

**Comment by dreammjow** [comment]
@pes10k What about SharedWorker? Brave's protection must be applied for all types of workers, not only for ServiceWorker.

**Comment by pes10k** [comment]
@dreammjow yep, absolutely! Thank you for the note and reminder.  We're revising how protections are applied now, to make sure we cover all possible workers (and similar situations). Thanks!
