### ISSUE TITLE
Request for Brave Position on Idle Detection API

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#18269]
https://www.chromestatus.com/feature/4590256452009984
https://bugs.chromium.org/p/chromium/issues/detail?id=878979
https://wicg.github.io/idle-detection/

Firefox: Harmful
Safari: Negative

**Comment by Tonev** [comment]
Developers have disabled the `Idle Detection API` via https://github.com/brave/brave-core/pull/7054.

**Comment by pes10k** [comment]
thank you @Tonev !  Yes, its been disabled in Brave for almost a year now.  We are not fans

**Comment by pes10k** [comment]
I'm going to close this though @manikandancode if it would be helpful for me / us / Brave to echo our concerns with the API somewhere else, just let us know where

**Comment by pachainti** [comment]
> thank you @Tonev ! Yes, its been disabled in Brave for almost a year now. We are not fans

Hi,
even it is merged, the API is still enabled as default on release, beta and nightly.
![API](https://user-images.githubusercontent.com/72299220/135056933-35d6707e-8d44-4b7b-9710-42b4d38b7f24.png)

**Comment by jonathansampson** [comment]
@pachainti Can you go to https://idle-detection.glitch.me/ and let me know what you see written at the top? You should see "Your browser doesn't support the Idle Detection API" in Brave.

**Comment by aquaspy** [comment]
Good news guys, seems to be off by default:
![image](https://user-images.githubusercontent.com/49214136/135347262-d876e419-86a0-4f2b-ab5b-3196b678b214.png)

Maybe that was just a graphical glitch? For me the default behavior is also to ask....
