### ISSUE TITLE
Pending contributions / tips not being sent even after creator has verified

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18262]
## Description

STR:

1. Be Uphold-verified user (not sure if this generalizes)
2. Tip a Twitter account (not sure if this generalizes) that isn't verified whatsoever
3. Note that the tip goes into `Pending contributions list`
4. Twitter account verifies and also links to Uphold
5. Go to Twitter account, and see that the browser recognizes this fact (shows that the account is verified with blue checkmark and no "path unavailable" gray notice)
6. Tip remains pending and does not get sent (and it's been sufficiently long — many days)

Screenshots:

![image](https://user-images.githubusercontent.com/11497541/134264291-4e25b2b5-d8fa-4743-bb9a-5bbc5f94c66b.png)

<img src="https://user-images.githubusercontent.com/11497541/134264284-41bac8d3-fa74-4f26-bfee-8c147e30d349.png" height=450px>
 
Reproduced by @cryptojennie.

**Comment by cryptojennie** [comment]
Update: The tip in question went through (confirmed by the recipient) shortly after I updated to v1.29.81. 

Screenshot from today shows tip no longer in my pending contributions list: 
<img width="937" alt="Screen Shot 2021-09-22 at 1 37 19 PM" src="https://user-images.githubusercontent.com/32344882/134393753-b4dce1a0-8a46-4b98-aa30-af9dc4c7a701.png">

**Comment by Miyayes** [comment]
See this issue: https://github.com/brave/brave-browser/issues/18343
