### ISSUE TITLE
Change default (standard) network blocking policy to always allow 1p requests

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18274]
To improve web compat (and so reduce how often users need to drop all shields, and so all protections) we should change the default blocking configuration in Brave.  All sub-requests with the same eTLD+1 as the top level document (i.e., "first party requests") should be allowed when in "Trackers & Ads Blocked (Standard)" mode.

"Trackers & Ads Blocked (Aggressive)" mode should retain the current behavior.

This feature should be default on, ie when the flag is set to default, the above policy is active.

However, it should, day-0, be rolled out with 0% deployment (off for everyone) with Griffin

The above was done on Desktop via  #17366. On Android the setting/flag has no effect on the page as images are blocked hence the followup issue

cc: @pes10k @antonok-edm @iefremov

**Comment by antonok-edm** [comment]
@srirambv can we get this retested? I suspect this is fixed now
