### ISSUE TITLE
Installing profile doesn't show expiry date until configuration is reset

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18271]
## Description 
Installing profile doesn't show expiry date until configuration is reset

## Steps to reproduce 

   1. Clean install and enable VPN
   2. Install VPN profile
   3. Select Setttings -> VPN
   4. Expiry date is not shown
   5. Reset configuration
   6. Subscription expiry date is shown

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/134293315-a64542b4-b068-4a08-b37c-684bb0f3dcb7.jpg>

## Expected result
<img width=300 src=https://user-images.githubusercontent.com/17010094/134293333-6c12a189-a7b0-4b99-b527-f76c916ab8de.jpg>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.32.7

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya

**Comment by deeppandya** [comment]
@srirambv this should be resolved. would it be possible to quickly verify and close the issue ?

**Comment by srirambv** [comment]
Verified this isn't an issue any more
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/5d5697a2-2e05-4a72-85b5-db07d750311f>
