### ISSUE TITLE
Windows Defender detects "Trojan:Win32/Bitrep.B" in 0.55.20

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1827]
Someone let us know that Windows Defender identified "tor-0.3.3.8-win32-brave-5 as being infected with "Trojan:Win32/Bitrep.B": 

![image](https://user-images.githubusercontent.com/639937/47462930-a8659d80-d799-11e8-8192-197136a2065a.png)

**Comment by tomlowenthal** [comment]
I was unable to repro in a VM with Windows Defender threat definition version 1.279.441.0 as of a few minutes ago. Have asked for more info from the reporter.

**Comment by tomlowenthal** [comment]
Reporter was unable to reproduce with updated definitions. Seems to have been a transient issue.

**Comment by DubstepManCZ** [comment]
So, what is this? I'm having the same exact problem because of downloading BlackBone for Xenos Injector.
