### ISSUE TITLE
Reset configuration and trying to enable VPN fails. Only works when you select a different region

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18270]
## Description 
Reset configuration and trying to enable VPN fails. Only works when you select a different region

## Steps to reproduce 

   1. Subscribe and install VPN profile
   2. Go to Settings -> VPN -> reset configuration
   3. Enable VPN switch to active VPN, fails to enable
   4. Change region, automatically enables VPN

## Actual result 

https://user-images.githubusercontent.com/17010094/134291121-ea88f54d-1d50-45d6-b878-b377f945f1bd.mp4

## Expected result
Should be able to enable VPN successfully after resetting configuration

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:11
   
## Brave version
1.32.7

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya

**Comment by deeppandya** [comment]
@srirambv This issue should be resolved. can you verify and close the issue if it's irrelevant ?
