### ISSUE TITLE
Chunk of whitespace in middle of article

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#18280]
## Description 

Chunk of whitespace in middle of article

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `https://www.cbsnews.com/news/gabby-petito-body-found-wyoming-confirmed-ruled-homicide/`
   4. click to enable Speedreader, in the URL bar
   5. scroll down the page a bit after it reloads

## Actual result:

Chunk of whitespace

<img width="1312" alt="Screen Shot 2021-09-22 at 9 41 50 AM" src="https://user-images.githubusercontent.com/387249/134386146-205e7255-fa08-4460-ab56-762edf9418ae.png">

## Expected result:
No chunk of whitespace

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.32.9 Chromium: 94.0.4606.54 (Official Build) nightly (x86_64)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | macOS Version 11.6 (Build 20G165)

/cc @keur

**Comment by keur** [comment]
Issue is due to `srcset=srcset="data:image/svg+xml,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%20620%20366'%2F%3E"` and Speedreader is not throwing out bad srcsets.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.32.20 Chromium: 94.0.4606.54 (Official Build) nightly (x86_64)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. new profile
2. launch Brave
3. load `https://www.cbsnews.com/news/gabby-petito-body-found-wyoming-confirmed-ruled-homicide/`
4. click to enable Speedreader, in the URL bar
5. scroll down the page a bit after it reloads

Confirm there's now an image where the blank space used to be.

<img width="1778" alt="Screen Shot 2021-09-24 at 11 26 57 AM" src="https://user-images.githubusercontent.com/387249/134723187-82ba3f53-a5ca-4999-9c57-843428e36a30.png">
