### ISSUE TITLE
Block Scripts shield sometimes doesn't work

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#1829]
## Description
Edit: [See my comment below](https://github.com/brave/brave-browser/issues/1829#issuecomment-433141542).

Toggling on the Block Scripts shield does not disable JavaScript. This happens even after reloading the page several times after toggling the switch.

## Steps to Reproduce
   1. Open a new window and navigate to https://enable-javascript.com/
   2. Click the Brave Shields button and toggle on Block Scripts.

## Actual result:
Despite Block Scripts being enabled, JavaScript is still enabled.

The website text shows "Javascript is enabled in your web browser."
![](https://user-images.githubusercontent.com/19424103/47472450-660d8200-d7d4-11e8-99b6-801fb2f01429.png)

## Expected result:
JavaScript should be disabled.

The website text should show "Javascript is disabled in your web browser", like Safari does when JavaScript is disabled:
![](https://user-images.githubusercontent.com/19424103/47472570-cac8dc80-d7d4-11e8-8039-085a573efb0d.png)

## Reproduces how often: 
Sometimes.

## Brave version (brave://version info)
Brave | 0.57.2 Chromium: 70.0.3538.67 (Official Build) dev(64-bit)
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by srirambv** [comment]
Can't reproduce this on Windows

This is on Beta  (0.56.6)
![javascript](https://user-images.githubusercontent.com/17010094/47500240-4310bb80-d830-11e8-8f65-2802ce1fabd3.gif)


This is on dev (0.57.2)
![javascriptdev](https://user-images.githubusercontent.com/17010094/47500280-60de2080-d830-11e8-935b-a65973e082a8.gif)

**Comment by Liunkae** [comment]
Weird. After clearing cookies, caches, and content settings, this no longer reproduces for me.

**Comment by Liunkae** [comment]
I think the content/shield settings got in an inconsistent state (maybe because of an upgrade?). Perhaps clearing the content settings fixed it. I'll definitely keep an eye out for this problem to see if it happens again.

**Comment by srirambv** [comment]
@Liunkae that would be awesome. If you can check this during the next upgrade would be really helpful to see if the content settings getting messed up

**Comment by onmyouji** [comment]
> I think the content/shield settings got in an inconsistent state (maybe because of an upgrade?). Perhaps clearing the content settings fixed it. I'll definitely keep an eye out for this problem to see if it happens again.

I had the same problem on Brave 0.55.20
You're right, clearing the Content settings fixed it.

**Comment by onmyouji** [comment]
The problem happens again after the latest update to 0.55.22

**Comment by srirambv** [comment]
Could be related to https://github.com/brave/brave-browser/issues/1991

**Comment by Liunkae** [comment]
Happened to me again, and I don't think there was an update involved this time (I'm on 0.57.4, the latest dev version). After clearing content settings and restarting the browser, the problem was resolved.

**Comment by onmyouji** [comment]
@Liunkae 
Did you toggle your shield off/on? I'm able to reproduce the problem by doing that (issue 1991).

**Comment by kjozwiak** [comment]
@onmyouji can you still reproduce the issue on `0.56.12` which was just pushed? If you can still reproduce, can you provide some steps that you're using?

**Comment by onmyouji** [comment]
@kjozwiak 
Just updated to 0.56.12, I think the problem has been fixed now. Scripts are still being blocked after disabling/enabling.

**Comment by tomlowenthal** [comment]
@kjozwiak Can we get a QA test on this, and either close if it's resolved or get STR if not?

**Comment by kjozwiak** [comment]
@tomlowenthal once things start cooling off with `0.57.x`, @brave/legacy_qa will take a look and see if we can reproduce and provide STR 👍

**Comment by Liunkae** [comment]
I have not experienced this in several months, so I assume it's no longer a problem. Closing.
