### ISSUE TITLE
Brave Talk - add link to TOS 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#18292]
## Description 
Per: https://bravesoftware.slack.com/archives/C01BC0K5QP7/p1632321648245400?thread_ts=1632254778.221300&cid=C01BC0K5QP7

When a user enables Rewards to get free calls on Talk we should have a link to the Rewards TOS in that UI modal  

The text will be

By turning on Ads, you agree to the [Terms of Service](https://basicattentiontoken.org/user-terms-of-service) and [Privacy Policy](https://brave.com/privacy/#rewards).

<img width="1157" alt="2021-09-22_15-32-42" src="https://user-images.githubusercontent.com/7606853/134420467-10682332-d2c8-4746-a0b9-01dc8e28639e.png">

cc @mattmcalister

**Comment by mattmcalister** [comment]
The case here is when a current Brave user has already enabled Rewards and then disabled Ads. When that user tries Brave Talk and wants to use the Free 1:1 feature they must re-enable ads. 

The toggle in this case must include the copy mentioned above. The spec also needs to be updated to reflect this change. cc @karenkliu

**Comment by adithyaakrishna** [comment]
@anthonypkeane Is there any mockup for the same?
I would like to work on this 👀

**Comment by mattmcalister** [comment]
We can close this now that we have the toggle behavior. The TOS link appears in the "Turn on Rewards" panel on all platforms.
