### ISSUE TITLE
Unable to enable rewards

### ISSUE THREAD

**Issue by Bajotaz** [brave/brave-browser#18298]
## Description 
Could not get Uphold to update current bat amount so i disabled rewards, now i can't enable rewards again.
The page glitches when i click enable but does not enable

## Steps to Reproduce

   1.  open brave:rewards
   2.  click enable rewards
   3. 

## Expected result:
Enable rewards

## Reproduces how often: 

Constant problem for 1 hour

## Brave version (brave://version info)

Windows 10, all current updates, Brave with all current updates

## Version/Channel Information:

Current windows 10 version
- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @brave/rewards-client

**Comment by Miyayes** [comment]
When you go to brave://rewards-internals, do you see "Wallet not yet created"?
