### ISSUE TITLE
some DEPS hooks shouldn't run for android

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#1830]
DEPS specifies several hooks that don't make sense for android

**Comment by srirambv** [comment]
Does this require any QA verification? Can `QA/No` be added if nothing needs to be tested

**Comment by kjozwiak** [comment]
Labelling this as `QA/No` as similar issues were also labelled as `QA/No`. I don't see anything actionable from QA's perspective.

@SergeyZhukovsky @bridiver please let me know if there's something that QA should check here.
