### ISSUE TITLE
Embedded tweets not appearing

### ISSUE THREAD

**Issue by yokoffing** [brave/brave-browser#18304]
## Description 

Embedded tweets do not appear even with Social media Twitter option ON.

## Steps to Reproduce

   1. Ensure your allow embedded tweets option is ON
   2.  Visit:

- `https://blavity.com/7-things-to-know-about-destini-smothers-the-mother-whose-body-was-found-in-the-trunk-of-her-car?category1=news&item=2`
- or `https://www.billboard.com/articles/news/9632962/taylor-swift-fearless-taylors-version-signed-copies-permanent-claw-hands`
- or `https://www.engadget.com/apple-fortnite-ios-app-store-court-appeals-epic-games-175240669.html`

## Actual result:

Embedded tweet does not show.

## Expected result:
Embedded tweets should show when allow embedded tweet option is ON.

## Reproduces how often: 

Doesn't work on the sites I listed, but they will appear on some sites (like this one from 2018 `https://www.resetera.com/threads/embedded-tweets-not-working-for-anyone-else-or-is-it-just-me.16064/`).

## Brave version (info found on brave://version)

1.31.56

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the dev channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Yes (with related flags enabled)

**Comment by yokoffing** [comment]
**Update:** I've resolved the issue resolved itself after I reset all the experiments on `brave://flags`. I am slowly turning them back on one-by-one to see if I can isolate which flag caused the issue.

**Comment by rebron** [comment]
Closing as wontfix. Flags are experimental. Thanks for posting which flags could be causing the issue though.
