### ISSUE TITLE
Crash reporting should be enabled by default on nightly

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#18315]
## Description 

Crash reporting should be enabled by default on nightly

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `brave://settings/privacy`
   4. look at the default for `Help improve Brave's features and performance`

## Actual result:

It's toggled to `off` by default

<img width="1312" alt="Screen Shot 2021-09-23 at 9 11 08 AM" src="https://user-images.githubusercontent.com/387249/134545472-5e47f86a-3385-4fdf-91ca-edca92a37836.png">

## Expected result:
Should be toggled to `on` by default

<img width="1312" alt="Screen Shot 2021-09-23 at 9 17 07 AM" src="https://user-images.githubusercontent.com/387249/134545434-16d21fed-3419-4c88-b1b9-9560ba9620cf.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.32.17 Chromium: 94.0.4606.54 (Official Build) nightly (x86_64)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | macOS Version 11.6 (Build 20G165)

/cc @rebron @simonhong @karenkliu

**Comment by simonhong** [comment]
@stephendonner Can you check this also on Windows?
I can repro this on macOS also but can't on Windows.

**Comment by stephendonner** [comment]
> @stephendonner Can you check this also on Windows?
> I can repro this on macOS also but can't on Windows.

Sorry for the delay; can confirm it's on by default in the latest `nightly` on Windows 10.

**Comment by simonhong** [comment]
@stephendonner Thanks for checking :)

**Comment by simonhong** [comment]
Only macOS has this issue. linux is also fine.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.32.26 Chromium: 94.0.4606.61 (Official Build) nightly (x86_64)
-- | --
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | macOS Version 11.6 (Build 20G165)



Steps:

1. new profile
2. launch Brave
3. load `brave://settings/privacy`
4. look at the default for `Help improve Brave's features and performance`
5. confirmed it's checked
6. loaded `brave://inducebrowsercrashforrealz`
7. crashed
8. confirmed I didn't see a crash-submission prompt
9. confirmed I was prompted to restore pages upon restart
10. confirmed `brave://crashes` shows my auto-submitted crash incident


example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2021-09-27 at 10 59 54 AM" src="https://user-images.githubusercontent.com/387249/134961640-5be8b6a6-b6cd-46be-bfeb-1dbe88033916.png"> | <img width="1312" alt="Screen Shot 2021-09-27 at 11 01 06 AM" src="https://user-images.githubusercontent.com/387249/134961648-8d6debf5-4487-4349-8902-9a00218a6e5e.png"> | <img width="1312" alt="Screen Shot 2021-09-27 at 11 01 14 AM" src="https://user-images.githubusercontent.com/387249/134961659-8e5ef33d-d5ad-4b9a-9115-d6c5fb9afaf8.png">

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` as we have a 1.32.x RC which can be used to verify this

**Comment by LaurenWags** [comment]
Verified on `Release` channel:

```
Brave | 1.32.97 Chromium: 96.0.4664.35 (Official Build) (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)
```

Confirmed crash reporting is not enabled by default on release channel.

Steps:

1. new profile 1.32.97
2. launch Brave
3. load `brave://settings/privacy`
4. look at the default for `Help improve Brave's features and performance`
5. confirmed it is not enabled
6. loaded `brave://inducebrowsercrashforrealz`
7. crashed
8. on relaunch, confirmed I did see a crash-submission prompt
9.  confirmed I was prompted to restore pages 
10. confirmed clicking "Block" did not enable crash reporting
11. confirmed `brave://crashes` shows my crash report as not submitted
12. loaded `brave://inducebrowsercrashforrealz` again
13. crashed
14. on relaunch, confirmed I saw crash submission prompt again
15. selected "Don't ask again" and Block
16. confirmed I was prompted to restore pages
17. confirmed clicking "Block" did not enable crash reporting
18. confirmed `brave://crashes` shows my crash report as not submitted
19. loaded `brave://inducebrowsercrashforrealz` again
20. crashed
21. on relaunch, confirmed I did not see crash submission prompt
22. confirmed I was prompted to restore pages

Example | Example | Example
----- | ----- | -----
<img width="1025" alt="Screen Shot 2021-11-10 at 10 29 54 AM" src="https://user-images.githubusercontent.com/28145373/141144349-3d8d25d1-aae7-4910-8294-d4a892e38b94.png"> | <img width="1027" alt="Screen Shot 2021-11-10 at 10 30 19 AM" src="https://user-images.githubusercontent.com/28145373/141144357-45372a6b-9f4d-43c1-96ef-815d74764abc.png"> | <img width="1030" alt="Screen Shot 2021-11-10 at 10 30 56 AM" src="https://user-images.githubusercontent.com/28145373/141144375-e94ffdc5-9093-4913-af28-c7e721180f19.png">

1. new profile 1.32.97
2. launch Brave
3. load `brave://settings/privacy`
4. look at the default for `Help improve Brave's features and performance`
5. confirmed it is not enabled
6. loaded `brave://inducebrowsercrashforrealz`
7. crashed
8. on relaunch, confirmed I did see a crash-submission prompt
9. clicked "Allow"
10. confirmed I was prompted to restore pages
11. confirmed clicking "Allow" did enable crash reporting
12. loaded `brave://inducebrowsercrashforrealz` again
13. crashed
14. on relaunch, confirmed I did not see crash submission prompt
15. confirmed I was prompted to restore pages
16. confirmed my crash report was shown as submitted

Example | Example | Example | Example
----- | ----- | ----- | -----
<img width="1023" alt="Screen Shot 2021-11-10 at 10 42 30 AM" src="https://user-images.githubusercontent.com/28145373/141145308-e08a5259-fbcf-4fde-bfcc-942385c01c0f.png"> | <img width="1028" alt="Screen Shot 2021-11-10 at 10 42 52 AM" src="https://user-images.githubusercontent.com/28145373/141145324-564d4a20-ce27-4be7-9665-09c0bd43a7fe.png"> | <img width="1028" alt="Screen Shot 2021-11-10 at 10 43 12 AM" src="https://user-images.githubusercontent.com/28145373/141145345-f41be91b-bfb2-4e34-bd34-30adb232e324.png"> | <img width="1029" alt="Screen Shot 2021-11-10 at 10 46 21 AM" src="https://user-images.githubusercontent.com/28145373/141145387-f58d1592-3c27-44e2-a0aa-9ab7e557d059.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.72 Chromium: 96.0.4664.35 (Official Build) nightly (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)

Confirmed crash reporting is not enabled by default on release channel.

Steps:

1. new profile 1.32.97
2. launch Brave
3. load brave://settings/privacy
4. look at the default for Help improve Brave's features and performance
5. confirmed it is not enabled
6. loaded brave://inducebrowsercrashforrealz
7. crashed
8. on relaunch, confirmed I did see a crash-submission prompt
9. confirmed I was prompted to restore pages
10. confirmed clicking "Block" did not enable crash reporting
11. confirmed brave://crashes shows my crash report as not submitted
12. loaded brave://inducebrowsercrashforrealz again
13. crashed
14. on relaunch, confirmed I saw crash submission prompt again
15. selected "Don't ask again" and Block
16. confirmed I was prompted to restore pages
17. confirmed clicking "Block" did not enable crash reporting
18. confirmed brave://crashes shows my crash report as not submitted
19. loaded brave://inducebrowsercrashforrealz again
20. crashed
21. on relaunch, confirmed I did not see crash submission prompt
22. confirmed I was prompted to restore pages

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2021-11-10 at 8 47 51 AM" src="https://user-images.githubusercontent.com/387249/141157119-b962f6aa-3721-42c0-8171-640d26586b43.png"> | <img width="1312" alt="Screen Shot 2021-11-10 at 8 48 41 AM" src="https://user-images.githubusercontent.com/387249/141157128-a4b9bc8e-eb96-46f2-8ab0-e346284781da.png"> | <img width="1312" alt="Screen Shot 2021-11-10 at 8 49 11 AM" src="https://user-images.githubusercontent.com/387249/141157142-4c35c251-1984-4324-8713-d9d7bc633369.png">

1. new profile 1.32.97
2. launch Brave
3. load brave://settings/privacy
4. look at the default for Help improve Brave's features and performance
5. confirmed it is not enabled
6. loaded brave://inducebrowsercrashforrealz
7. crashed
8. on relaunch, confirmed I did see a crash-submission prompt
9. clicked "Allow"
10. confirmed I was prompted to restore pages
11. confirmed clicking "Allow" did enable crash reporting
12. loaded brave://inducebrowsercrashforrealz again
13. crashed
14. on relaunch, confirmed I did not see crash submission prompt
15. confirmed I was prompted to restore pages
16. confirmed my crash report was shown as submitted

example | example | example | example
---------|----------|---------|----------
<img width="1312" alt="Screen Shot 2021-11-10 at 8 55 09 AM" src="https://user-images.githubusercontent.com/387249/141157945-55c2830a-3909-4210-a6ec-4519450a14fc.png"> | <img width="1312" alt="Screen Shot 2021-11-10 at 8 55 32 AM" src="https://user-images.githubusercontent.com/387249/141157952-4fd8bfcd-c1c2-493b-aa0d-183b2d687192.png"> | <img width="1312" alt="Screen Shot 2021-11-10 at 8 56 03 AM" src="https://user-images.githubusercontent.com/387249/141157963-a21fff83-4495-489b-bac6-229c46418d8c.png"> | <img width="1200" alt="Screen Shot 2021-11-10 at 8 57 07 AM" src="https://user-images.githubusercontent.com/387249/141157968-3558d27e-dff0-4772-8a72-6f5f20826a34.png">
