### ISSUE TITLE
Use most recent text from copywriter for WDP in settings

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#18316]
Text body needs to be changed to: _Contribute some anonymous search & browsing data to refine Brave Search. Learn more_

Learn more URL should be changed from help center to https://brave.com/browser/privacy/#web-discovery-project

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.31.62 Chromium: 94.0.4606.54 (Official Build) beta (x86_64)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. new profile
2. launch Brave
3. load `brave://settings/search`
4. read the description for Web Discovery Project
5. clicked on `Learn more` link

Confirmed:
* description changed to `Contribute some anonymous search & browsing data to refine Brave Search.`
* `Learn more` link goes to `https://brave.com/browser/privacy/#web-discovery-project`

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-09-27 at 2 46 55 PM" src="https://user-images.githubusercontent.com/387249/134990314-91a96f00-ac95-49aa-a118-2ed5c41c03de.png"> | <img width="1758" alt="Screen Shot 2021-09-27 at 2 49 43 PM" src="https://user-images.githubusercontent.com/387249/134990319-4126ee3d-c6f4-4120-9472-c00bdb5e043d.png">
