### ISSUE TITLE
wallet addresses are not being updated when restoring previous wallets

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1831]
## Description 

When restoring wallets, the addresses are not being updated to reflect the restored wallet, example:

Original wallet when enabling rewards:

```
"paymentId":"0dd3d2e5-452f-4055-8206-8faae8f387f7",
"addressBAT":"0x526620Aa18B011e2314a05A44068eF63121E9bC4",
"addressBTC":"1DRVEcbbR3zohQg4o6kP6ewNruzchWyvY4",
"addressCARD_ID":"57f211b9-eca8-4e3c-b695-fb60fe793503",
"addressETH":"0x526620Aa18B011e2314a05A44068eF63121E9bC4",
"addressLTC":"LbMdhD3umBAxuQaCujxn7Q9yTnwcRvzjQR"
```

After restoring another wallet:

```
"paymentId":"eb42caf4-17dd-41d7-80be-f868d98bd513",
"addressBAT":"0x526620Aa18B011e2314a05A44068eF63121E9bC4",
"addressBTC":"1DRVEcbbR3zohQg4o6kP6ewNruzchWyvY4",
"addressCARD_ID":"57f211b9-eca8-4e3c-b695-fb60fe793503",
"addressETH":"0x526620Aa18B011e2314a05A44068eF63121E9bC4",
"addressLTC":"LbMdhD3umBAxuQaCujxn7Q9yTnwcRvzjQR"
```

In the above example, I restored a wallet and ended up sending funds to `1DRVEcbbR3zohQg4o6kP6ewNruzchWyvY4` instead of `0x526620Aa18B011e2314a05A44068eF63121E9bC4`. Because I never backed up the previous wallet, I've lost all my funds.

## Steps to Reproduce

   1. launch `0.56.6 Chromium: 70.0.3538.67` and enable `rewards` via `brave://rewards`
   2. once enabled, open `ledger_state` and note `paymentId`, `addressBAT`, `addressBTC`, `addressCARD_ID`, `addressETH` and `addressLTC`
   3. restore a previously created wallet via `Settings` -> `Restore your Wallet`
   5. once restored, open `ledger_state`

You'll notice that `paymentId` has changed but the other addresses haven't been updated.

## Actual result:

See example above. The addresses are not being correctly updated when restoring wallets.

## Expected result:

Addresses should be updated and reflect the correct addresses associated with the restored wallet.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.56.6 Chromium: 70.0.3538.67 (Official Build) beta(64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, reproducible on all the channels. Reproduced using:

Brave | 0.57.2 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

Brave | 0.56.6 Chromium: 70.0.3538.67 (Official Build) beta(64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

**Comment by NejcZdovc** [comment]
fixed https://github.com/brave/brave-core/pull/734

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux

```

**Comment by kjozwiak** [comment]
Clearing current labels, we should try again once we get the new RC builds just to double check and make sure this is still resolved and working as expected.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux

* Verified Wallet address is updated after recovery
* Verified recovered wallet retains all the funds that were there in the wallet
* Verified QR code scan shows the correct wallet address 

```
Before recovery
"paymentId":"eb0dc24d-fa14-4c56-95cb-feea1a0628bb",
"addressBAT":"0xb753c879a412457B80677Ed39E4FF9dbEf361318",
"addressBTC":"1jMXpEz5L5qnuQpbEwvmDvnQXa6E9qq2u",
"addressCARD_ID":"314f4cba-ddc4-4a9d-935a-05f3cecf1a6c",
"addressETH":"0xb753c879a412457B80677Ed39E4FF9dbEf361318",
"addressLTC":"LKn9iiNZtQ6D3xfoWHV8dNjQAwCy5S3iRp",
"personaId":"c3c49cd3-6169-4d92-a0b3-9114ace595ac"

After recovery
"paymentId":"15d6298a-312f-4cd0-b090-d58f2403084e",
"addressBAT":"0x3c11c968C559CEfdA1Bac909bcB1eeC938784618",
"addressBTC":"1Gj9ZWqsWubQSKT8pktaoZafCNsNoHAa94",
"addressCARD_ID":"3e8beedd-4aaf-46db-9af9-b9ec2a5aca9d",
"addressETH":"0x3c11c968C559CEfdA1Bac909bcB1eeC938784618",
"addressLTC":"Ldb544DzK53YzvbpFondq8gmnGTNZevE2A",
"personaId":"c3c49cd3-6169-4d92-a0b3-9114ace595ac"
```

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

Addresses generated when enabling `brave://rewards`:

```
"paymentId":"9ee67136-7a98-41b8-b678-bbb238669f7e",
"addressBAT":"0x76A820Db7c19F526db1Ab9AA7f3A3d0FA9c25e0b",
"addressBTC":"1Cspq7HRVgiEZxsTYSdmDJLfYEp62FwEcq",
"addressCARD_ID":"d63c3bbf-69cd-410c-bee0-071b2d0c8290",
"addressETH":"0x76A820Db7c19F526db1Ab9AA7f3A3d0FA9c25e0b",
"addressLTC":"LMY119mJG7rNuuTKMcgdkQ4q1K7uj9AJSK"
```

* enabled `brave://rewards` and ensured that the addresses being listed under `ledger_state` are the same addresses being listed under in the Rewards UI
* scanned each QR code and ensured that the addresses are matching
* relaunched Brave several times and ensured that the addresses under `ledger_state` and `brave://rewards` haven't changed
* sent 25 BAT from an Uphold `LTC` wallet to the `LTC` address Brave generated and ensured that the funds were received and displayed under `brave://rewards`
* sent 10 BAT from an Uphold `BTC` wallet to the `BTC` address Brave generated and ensured that the funds were received and displayed under `brave://rewards`
* sent 5 BAT from an Uphold `ETH` wallet to the `ETH` address Brave generated and ensured that the funds were received and displayed under `brave://rewards`
* sent 5 BAT from an Uphold `BAT` wallet to the `BAT` address Brave generated and ensured that the funds were received and displayed under `brave://rewards`

Backed up the above wallet and went through the following cases once I restored a new wallet:

```
"paymentId":"9ad2aaac-f7c9-4000-af58-86dc608f3dd5",
"addressBAT":"0x42D97CDE05cc8A0A16E0F4728DEf5E2E565E5Dcb",
"addressBTC":"19VksjpRQMnqk6G96PWrdwozpuPvNBsSCo",
"addressCARD_ID":"1eaae0d7-c9c8-4d06-ad5a-92555d41fa48",
"addressETH":"0x42D97CDE05cc8A0A16E0F4728DEf5E2E565E5Dcb",
"addressLTC":"Lc9nF4pBjcprTkkCMN3zqJPEHja6EVyWsn"
```

* ensured that the previous addresses have been replaced with the new restored wallet
* scanned each QR code and ensured that the addresses are matching
* relaunched Brave several times and ensured that the addresses under `ledger_state` and `brave://rewards` haven't changed
* sent 5 BAT from an Uphold `LTC` wallet to the `LTC` address Brave generated and ensured that the funds were received and displayed under `brave://rewards`
* sent 5 BAT from an Uphold `BTC` wallet to the `BTC` address Brave generated and ensured that the funds were received and displayed under `brave://rewards`
* sent 5 BAT from an Uphold `ETH` wallet to the `ETH` address Brave generated and ensured that the funds were received and displayed under `brave://rewards`
* sent 5 BAT from an Uphold `BAT` wallet to the `BAT` address Brave generated and ensured that the funds were received and displayed under `brave://rewards`

Nuked the entire profile and restored the two above wallets.. Ensured everything still matched.
