### ISSUE TITLE
Update Gemini promo card in `brave://rewards` page (end of Sept 2021)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18319]
## Description

Update text on Gemini promo card in `brave://rewards` to the following:

```
Gemini lets you easily trade, store, and earn 3.49% APY on your BAT. Verify and link your Brave Rewards wallet with Gemini now!

* Gemini Earn APY as of Sept 15, 2021
```

Target: A release on or before Sept 30, 2021. 

![image](https://user-images.githubusercontent.com/11497541/134563967-ca761da0-7df2-494d-b1fa-f2e652f6fa05.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)
-- | --
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | Windows 10 Version 20H2 (Build 19042.1237)
```
![Screenshot 2021-09-27 224559](https://user-images.githubusercontent.com/2602313/135014554-a1a1baae-9592-4187-b757-be7efa54d739.png)
