### ISSUE TITLE
Feature Request - Add ability to view list of tab groups for later opening

### ISSUE THREAD

**Issue by BigSauce** [brave/brave-browser#18313]
## Description 
I don't know if this is the appropriate place to request a feature, but I was hoping to request a feature where users can view a list of their tab groups so that if they ever decide to close them, they can simply view that tab group list and click on the tab group they wish to re-open.

**Comment by NikharPandya** [comment]
@BigSauce 
Refer to this issue 
https://github.com/brave/brave-browser/issues/9381

**Comment by NikharPandya** [comment]
and also there is a label to tab group issues 
https://github.com/brave/brave-browser/labels/feature%2Ftabs-bar

**Comment by NikharPandya** [comment]
@bsclifton 
You may close this issue
