### ISSUE TITLE
Add default wallet setting for Android

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#18325]
from brave_wallet_utils.h you can get/set the default wallet:
https://github.com/brave/brave-core/pull/10236

We should only support Brave Wallet and None on Android. Default being Brave Wallet.

This will disable the dapp detection, but we might also want it for other functionality in the future.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.63.157 x64 build
- Verified steps from [brave/brave-core#21340](https://github.com/brave/brave-core/pull/21340)
- Verified new settings for `Default Ethereum Wallet` and `Default Solana Wallet` is available
- Verified default value is set to `Brave Wallet` for both setting
- Verified setting `Default Ethereum Wallet` set to `None`, doesn't recognise Brave Wallet on Dapps
- Verified setting `Default Solana Wallet` set to `None`, doesn't recognise Brave Wallet on Dapps

https://github.com/brave/brave-browser/assets/17010094/c2f867d8-7280-4a62-8ac9-a923ff3c202a
