### ISSUE TITLE
Please update the URL when Brave is set as default

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#18324]
## Description 
When a user set Brave as Default they are taken to brave.com/blog. 

Please update this URL to https://brave.com/privacy-features/

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using `1.32.30 Chromium: 94.0.4606.61`

* ensured that when a user sets Brave as the default via on-boarding, https://brave.com/privacy-features is opened
* ensured that when a user sets Brave as the default via Settings, https://brave.com/privacy-features/ is opened
