### ISSUE TITLE
Bookmark icon slightly smaller in Ubuntu version of Brave Browser

### ISSUE THREAD

**Issue by blueedgetechno** [brave/brave-browser#18322]
## Steps to Reproduce

   1. Open Brave in windows and ubuntu
   2. Enable bookmark if not already
   3. Observe the relative size of the icon

## Actual result:

![ubuntu](https://user-images.githubusercontent.com/54899800/134572858-71d9ef77-b679-4eb4-8966-34e714b90923.png)
Ubuntu 20.04.2 LTS

## Expected result:

![windows](https://user-images.githubusercontent.com/54899800/134572756-8a6cd027-69a8-4034-86d1-c72458b32526.png)
Microsoft Windows [Version 10.0.19042.1237]

## Reproduces how often: 

Everytime we open the ubuntu version

## Brave version (brave://version info)

Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@blueedgetechno Do you have a theme installed? Those aren't our icons for reload and home for Linux.

**Comment by blueedgetechno** [comment]
I have only dark reader installed as an extension and no other extension.

The situation gets worse for v1.32 with unsually longer search bar

![image](https://user-images.githubusercontent.com/54899800/143087782-c4848f54-8d7e-4c8b-8985-390be1541f81.png)

**Comment by blueedgetechno** [comment]
Never mind, I reinstalled brave and it's fine now
