### ISSUE TITLE
two windows being opened when installing without admin

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1833]
## Description 

When installing Brave without admin, you'll notice that two windows are being launched. The first window will include the `brave://welcome` tab and the other window will have `brave://newtab` opened. @srirambv @bsclifton have reproduced this several times as well.

## Steps to Reproduce

   1. download one of the latest stub installers for Win 
   2. double click on the stub installer and select "No" under the UAC prompt
   3. click `Yes` when prompted `Brave can be installed without admin privileges. Continue?`

Once Brave is installed and launched, you'll notice two windows being launched.

## Actual result:

![twowindowsstub](https://user-images.githubusercontent.com/2602313/47481108-9d922380-d800-11e8-88b3-3c3f1afc1332.gif)

## Expected result:

Should only open `brave://welcome` in a single window. There shouldn't be two windows.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.56.6 Chromium: 70.0.3538.67 (Official Build) beta(64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, currently reproducible with the `dev`, `beta` and `release` stub installers.

### Additional Information

CCing @bsclifton @srirambv as they've experienced this issue as well.

**Comment by btlechowski** [comment]
Still reproducible on Windows 10 x64:

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

**Comment by kjozwiak** [comment]
Still reproducible with `0.66.100` which is the latest release:

Brave | 0.66.100 Chromium: 75.0.3770.142 (Official Build) (64-bit)
--- | ---
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Windows 10 OS Version 1809 (Build 17763.615)

**Comment by cacilhas** [comment]
I’m getting the same result using Brave Browser 83.1.10.97 on GNU/Linux 5.3.0-42-generic SMP x86_64.

**Comment by mherrmann** [comment]
Still seeing this on Brave Nightly 1.37.23.

**Comment by mherrmann** [comment]
@mihaiplesa are we passing `--do-not-launch-chrome` to the `install` action on the update server?

**Comment by mherrmann** [comment]
Appears fixed for me as of Nightly 1.37.40.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.46 Chromium: 98.0.4758.87 (Official Build) nightly (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1526)

Steps:
1. downloaded `BraveBrowserStandaloneNightlySetup.exe` from `https://github.com/brave/brave-browser/releases/tag/v1.37.46`
2. double-clicked to install
3. when at the User Access Control prompt (elevated permissions), I chose `No`
4. clicked `Yes` when prompted `Brave can be installed without admin privileges.  Continue?`
5. let installation finish
6. checked # of launched Brave windows, post-install

Confirmed only one (1) window was launched, post-install.

example | example | example | example | example | example
----------|----------|-----------|-----------|----------|------------
![1833-1](https://user-images.githubusercontent.com/387249/153941214-ca54eea7-bac9-4d6b-af2b-69fd4b8d5729.png) | ![1833-2](https://user-images.githubusercontent.com/387249/153941218-d1232950-67a7-420d-b2db-e82f6b15b5de.png) | ![1833-3](https://user-images.githubusercontent.com/387249/153941220-fb1e7e86-f170-4786-bbba-76cbb266c9a4.png) | ![1833-4](https://user-images.githubusercontent.com/387249/153941225-e72a899f-e93b-4e7c-bbe5-42cb7f92dbe1.png) | ![1833-5](https://user-images.githubusercontent.com/387249/153941227-99fbc062-9f6f-4ef6-b783-7310086d2b04.png) | ![1833-6](https://user-images.githubusercontent.com/387249/153941233-38006485-a4b9-485f-9ec6-5dc22e3df619.png)
