### ISSUE TITLE
Do not show tipping notice for unverified rewards user case

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#18341]
Follow up to #18137 

Users should see an "tipping warning" in both the rewards panel and on the tip dialog in the following case:

- The user does not have a connected external wallet.
- The publisher is registered but does not have a verified wallet address.

>  If the user is unverified, then as long as the creator has a blue checkmark, they'll be able to tip/a path exists from user to creator.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.31.70 Chromium: 94.0.4606.71 (Official Build) beta (x86_64)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | macOS Version 10.15.7 (Build 19H1417)
```

Verified test plan from https://github.com/brave/brave-core/pull/10242#issue-742307054

<details>
<summary>Scenario 1 - Not registered - In Progress</summary>

Confirmed message 1 is displayed on the tipping banner

Example | Example
----- | -----

</details>

<details>
<summary>Scenario 2 - Registered but not verified, user not verified - TBD</summary>

Confirmed no message is displayed about publisher status

Example | Example
----- | -----

</details>

<details>
<summary>Scenario 3 - Registered but not verified, user verified - TBD</summary>

Confirmed message 2 is displayed about publisher status

Example | Example
----- | -----

</details>

<details>
<summary>Scenario 4 - Verified and user is not connected - TBD</summary>

Confirmed no message is displayed about publisher status

Example | Example
----- | -----

</details>

<details>
<summary>Scenario 5 - Verified with non-matching wallet provider - TBD</summary>

Confirmed message 2 is displayed about publisher status

Example | Example
----- | -----

</details>

<details>
<summary>Scenario 6 - Verified with matching wallet provider - TBD</summary>

Confirmed no message is displayed about publisher status

Example | Example
----- | -----

</details>

Additional checks performed:

<details>
<summary>Anon wallet (funded via UGP grant) - TBD</summary>

Confirmed tip to unverified creator went to pending list and appropriate message (1) was displayed:

Example | Example | Example | Example
----- | ----- | ----- | -----

Confirmed able to tip connected, Uphold, Gemini, and bitFlyer KYC'd creators and no messaging was displayed.
Confirmed balance decreased as expected for tip to each of these creators.

Connected Example | Connected Example | Uphold Example | Uphold Example | Gemini Example | Gemini Example | bitFlyer Example | bitFlyer Example | Tips List | Wallet Panel
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- 


</details> 

<details>
<summary>Uphold wallet (funded via Uphold BAT on staging env) - TBD</summary>

Confirmed tip to unverified creator went to pending list and appropriate message (1) was displayed:

Example | Example | Example | Example
----- | ----- | ----- | -----


Confirmed tip to connected, Gemini, and bitFlyer creators went to pending list and appropriate message (2) was displayed:

Connected Example | Connected Example | Gemini Example | Gemini Example | bitFlyer Example | bitFlyer Example | Wallet Panel | Pending Tips List
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- 


Confirmed able to tip Uphold KYC'd creator and no messaging was displayed.
Confirmed balance decreased as expected for tip.

Example | Example | Example | Example
----- | ----- | ----- | -----

</details> 

<details>
<summary>bitFlyer wallet (funded via bitFlyer BAT on staging env) - TBD</summary>

Confirmed tip to unverified creator went to pending list and appropriate message (1) was displayed:

Example | Example | Example | Example
----- | ----- | ----- | -----

Confirmed tip to connected, Gemini, and Uphold creators went to pending list and appropriate message (2) was displayed:

Connected Example | Connected Example | Gemini Example | Gemini Example | Uphold Example | Uphold Example | Wallet Panel | Pending Tips List
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- 


Confirmed able to tip bitFlyer KYC'd creator and no messaging was displayed.
Confirmed balance decreased as expected for tip.

Example | Example | Example | Example
----- | ----- | ----- | -----


</details> 

<details>
<summary>Gemini wallet (funded via Gemini BAT on staging env) - TBD</summary>

Confirmed tip to unverified creator went to pending list and appropriate message (1) was displayed:

Example | Example | Example | Example
----- | ----- | ----- | -----

Confirmed tip to connected, bitFlyer, and Uphold creators went to pending list and appropriate message (2) was displayed:

Connected Example | Connected Example | bitFlyer Example | bitFlyer Example | Uphold Example | Uphold Example | Wallet Panel | Pending Tips List
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- 


Confirmed able to tip Gemini KYC'd creator and no messaging was displayed.
Confirmed balance decreased as expected for tip.

Example | Example | Example | Example
----- | ----- | ----- | -----


</details>

**Comment by stephendonner** [comment]
Scenario 1 - Not registered - PASSED
Confirmed message 1 is displayed on the tipping banner

example | example
---------|---------
<img width="320" alt="Screen Shot 2021-10-11 at 12 07 38 PM" src="https://user-images.githubusercontent.com/387249/136843572-6f43d6b5-dc8a-4c38-9c5a-a8219d367919.png"> | <img width="1580" alt="Screen Shot 2021-10-11 at 11 54 46 AM" src="https://user-images.githubusercontent.com/387249/136843468-7aee0ab3-b9d0-4ccd-b9a0-6f4064baa7a5.png">


Scenario 2 - Registered but not verified, user not verified - PASSED
Confirmed no message displayed about publisher status

example | example
---------|---------
<img width="317" alt="Screen Shot 2021-10-11 at 12 09 58 PM" src="https://user-images.githubusercontent.com/387249/136843840-7dcf240b-ff96-4f6a-b64f-fe322d0f7549.png"> | <img width="992" alt="Screen Shot 2021-10-11 at 12 01 58 PM" src="https://user-images.githubusercontent.com/387249/136843755-822f8d66-1ef9-430f-87ae-e94dc2099bda.png">


Scenario 3 - Registered but not verified, user is verified - PASSED
Confirmed message 2 is displayed about publisher status

example | example
---------|---------
<img width="403" alt="Screen Shot 2021-10-11 at 12 04 50 PM" src="https://user-images.githubusercontent.com/387249/136843931-1da6ac71-1406-40d3-bac1-3a44f0a582e0.png"> | <img width="1455" alt="Screen Shot 2021-10-11 at 12 05 07 PM" src="https://user-images.githubusercontent.com/387249/136843937-0dd47db5-c71d-44ae-bbfb-7a94cb8ecf3d.png">


Scenario 4 - Verified and user is not connected - PASSED
Confirmed no message is displayed about publisher status

example | example
---------|---------
<img width="405" alt="Screen Shot 2021-10-11 at 12 13 57 PM" src="https://user-images.githubusercontent.com/387249/136844218-f88192be-f73f-4166-9bcb-1d8034a0467c.png"> | <img width="1457" alt="Screen Shot 2021-10-11 at 12 14 05 PM" src="https://user-images.githubusercontent.com/387249/136844222-8760059d-64ea-413f-8323-21367fc92524.png">


Scenario 5 - Verified with non-matching wallet provider - PASSED
Confirmed message 2 is displayed about publisher status

example | example
---------|---------
<img width="406" alt="Screen Shot 2021-10-11 at 12 16 08 PM" src="https://user-images.githubusercontent.com/387249/136844404-e50e81ed-30c4-404c-9124-6a264fe6a15d.png"> | <img width="1458" alt="Screen Shot 2021-10-11 at 12 16 16 PM" src="https://user-images.githubusercontent.com/387249/136844409-d5ae4b05-b0e1-4e00-a978-329b70628fcf.png">


Scenario 6 - Verified with matching wallet provider
Confirmed no message is displayed about publisher status

example | example
---------|---------
<img width="403" alt="Screen Shot 2021-10-11 at 12 18 33 PM" src="https://user-images.githubusercontent.com/387249/136844957-c37e3e84-9823-47c1-ada8-0dd2c6dfe6e7.png"> | <img width="1463" alt="Screen Shot 2021-10-11 at 12 18 43 PM" src="https://user-images.githubusercontent.com/387249/136844959-145bd737-6c0d-46c7-8689-bb91feecc78c.png">

Additional checks performed:

Anon wallet (funded by UGP grant)

Confirmed tip to unverified creator went to pending list and appropriate message (1) was displayed

example | example | example | example
---------|----------|---------|---------
<img width="401" alt="Screen Shot 2021-10-11 at 12 29 24 PM" src="https://user-images.githubusercontent.com/387249/136846836-0ba924d1-8bbd-4996-80b1-157f59b2af2a.png"> | <img width="1453" alt="Screen Shot 2021-10-11 at 12 29 35 PM" src="https://user-images.githubusercontent.com/387249/136846841-a1f3dfdd-e305-4f27-8903-a2f49cd4ac24.png"> | <img width="377" alt="Screen Shot 2021-10-11 at 12 39 41 PM" src="https://user-images.githubusercontent.com/387249/136846844-68e2e793-34ae-41d6-ae8f-25e796afd233.png"> | <img width="925" alt="Screen Shot 2021-10-11 at 12 39 48 PM" src="https://user-images.githubusercontent.com/387249/136846847-072206f9-6f22-475a-adff-1043d6e20643.png">




Confirmed able to tip connected, Uphold, Gemini, and bitFlyer, KYC'd creators, and no messaging was displayed

connected | connected | uphold | uphold | gemini | gemini | bitflyer | bitflyer | tips list | wallet panel
-----------|-------------|--------|-------|-------|---------|--------|--------|--------|--------------
<img width="399" alt="Screen Shot 2021-10-11 at 12 33 44 PM" src="https://user-images.githubusercontent.com/387249/136847637-15e10b54-36d6-48ce-bfc1-3a2cbcb66e1a.png"> | <img width="993" alt="Screen Shot 2021-10-11 at 12 35 56 PM" src="https://user-images.githubusercontent.com/387249/136847642-2f409c8c-7ce1-414a-952f-d1e3a2ce9fff.png"> | <img width="400" alt="Screen Shot 2021-10-11 at 12 46 12 PM" src="https://user-images.githubusercontent.com/387249/136847678-44e14ee0-b338-4ef3-ac39-b5c7158e0ea8.png"> | <img width="1352" alt="Screen Shot 2021-10-11 at 12 46 23 PM" src="https://user-images.githubusercontent.com/387249/136847680-01ec7719-60be-476f-9769-43eb21ddfd03.png"> | <img width="407" alt="Screen Shot 2021-10-11 at 12 43 32 PM" src="https://user-images.githubusercontent.com/387249/136847737-c5d4264a-f747-4a40-887e-d1dd5d4af720.png"> | <img width="1346" alt="Screen Shot 2021-10-11 at 12 45 32 PM" src="https://user-images.githubusercontent.com/387249/136847743-d7b4ca81-f076-425c-8c6b-56db2af5f9a5.png"> | <img width="407" alt="Screen Shot 2021-10-11 at 12 43 32 PM" src="https://user-images.githubusercontent.com/387249/136848133-6c3a4001-dde8-4b7b-bf5a-47947642a271.png"> | <img width="1346" alt="Screen Shot 2021-10-11 at 12 45 32 PM" src="https://user-images.githubusercontent.com/387249/136848136-4ebf2b39-bf1d-4276-8a6f-6d9a1df22584.png"> | <img width="559" alt="Screen Shot 2021-10-11 at 12 48 26 PM" src="https://user-images.githubusercontent.com/387249/136847775-289d8c77-6df1-4625-b602-27563feab76f.png"> | <img width="337" alt="Screen Shot 2021-10-11 at 12 51 09 PM" src="https://user-images.githubusercontent.com/387249/136848175-0f12f973-116a-4653-b255-dddc1ff0bbe8.png">


Uphold wallet (funded by Uphold BAT on staging env)

Confirmed tip to unverified creator went to pending list and appropriate message (1) was displayed:

example | example | example | example
---------|----------|----------|---------
<img width="404" alt="Screen Shot 2021-10-11 at 1 08 49 PM" src="https://user-images.githubusercontent.com/387249/136849857-557e33e1-7dbe-4225-87f8-323c61aea919.png"> | <img width="1163" alt="Screen Shot 2021-10-11 at 1 09 02 PM" src="https://user-images.githubusercontent.com/387249/136849861-10435326-e936-483a-82e6-a2abfbaec32a.png"> | <img width="374" alt="Screen Shot 2021-10-11 at 1 09 21 PM" src="https://user-images.githubusercontent.com/387249/136849866-197ce200-ed26-4574-952c-fdb680dda8c7.png"> | <img width="621" alt="Screen Shot 2021-10-11 at 1 09 30 PM" src="https://user-images.githubusercontent.com/387249/136849870-68fe2d45-c49c-4b58-a574-bb92d8adb787.png">

Confirmed tip to connected, Gemini, and bitFlyer creators went to pending list and appropriate message (2) was displayed:

connected | connected | gemini | gemini | bitFlyer | bitFlyer | wallet panel | pending tips
-----------|-----------|----------|---------|---------|---------|-----------|-------------
<img width="411" alt="Screen Shot 2021-10-11 at 1 24 45 PM" src="https://user-images.githubusercontent.com/387249/136851528-35ec4895-afa2-4967-9ac6-3e12c95bf3d4.png"> | <img width="997" alt="Screen Shot 2021-10-11 at 1 24 53 PM" src="https://user-images.githubusercontent.com/387249/136851538-2efb4b01-aa55-4586-a01b-1778243ab991.png"> | <img width="405" alt="Screen Shot 2021-10-11 at 1 25 14 PM" src="https://user-images.githubusercontent.com/387249/136851582-5d796f2b-4f7d-4c72-9db9-8032b0131f74.png"> | <img width="997" alt="Screen Shot 2021-10-11 at 1 25 25 PM" src="https://user-images.githubusercontent.com/387249/136851585-c6b95a38-153f-440e-981f-93c441034c37.png"> | <img width="404" alt="Screen Shot 2021-10-11 at 1 23 47 PM" src="https://user-images.githubusercontent.com/387249/136851675-40cd07d8-a43a-40ee-8d85-5fba2aa4e431.png"> | <img width="992" alt="Screen Shot 2021-10-11 at 1 24 06 PM" src="https://user-images.githubusercontent.com/387249/136851682-53c04388-b025-487b-8b2d-a019d986eb19.png"> | <img width="373" alt="Screen Shot 2021-10-11 at 1 25 46 PM" src="https://user-images.githubusercontent.com/387249/136851746-0f47ec2b-67cb-4391-a31c-8f562f503898.png"> | <img width="923" alt="Screen Shot 2021-10-11 at 1 26 13 PM" src="https://user-images.githubusercontent.com/387249/136851751-01b104ef-0391-412d-a59f-b1b03bd07c59.png">

Confirmed able to tip Uphold KYC'd creator and no messaging was displayed.
Confirmed balance decreased as expected for tip.

example | example | example | example
---------|----------|----------|--------
<img width="409" alt="Screen Shot 2021-10-11 at 1 30 29 PM" src="https://user-images.githubusercontent.com/387249/136852093-1033acdb-9381-4634-a626-395e49210c7d.png"> | <img width="1393" alt="Screen Shot 2021-10-11 at 1 30 44 PM" src="https://user-images.githubusercontent.com/387249/136852099-68a791b1-cb20-4f71-b413-49f59c76a555.png"> | <img width="614" alt="Screen Shot 2021-10-11 at 1 31 08 PM" src="https://user-images.githubusercontent.com/387249/136852138-f7daac98-a2fe-4b29-bf80-a43c5f7d3985.png"> | <img width="391" alt="Screen Shot 2021-10-11 at 1 31 21 PM" src="https://user-images.githubusercontent.com/387249/136852143-9bf6ea10-dd81-4305-bdbe-e20c25f4696e.png">

bitFlyer wallet (funded by bitFlyer BAT on staging env)

Confirmed tip to unverified creator went to pending list and appropriate message (1) was displayed:

example | example | example | example
---------|----------|----------|---------
<img width="412" alt="Screen Shot 2021-10-11 at 1 40 20 PM" src="https://user-images.githubusercontent.com/387249/136853140-e9c27d55-e492-47d9-b999-6551189a51bc.png"> | <img width="990" alt="Screen Shot 2021-10-11 at 1 40 26 PM" src="https://user-images.githubusercontent.com/387249/136853146-942327d5-79d1-4114-887c-93a43a48faab.png"> | <img width="379" alt="Screen Shot 2021-10-11 at 1 40 48 PM" src="https://user-images.githubusercontent.com/387249/136853151-cc2478c0-82ff-45b4-a217-3221891dfc31.png"> | <img width="916" alt="Screen Shot 2021-10-11 at 1 41 06 PM" src="https://user-images.githubusercontent.com/387249/136853152-09ed3f9a-6c4b-4482-a827-6c3a4a8fc7be.png">

Confirmed tip to connected, Gemini, and Uphold creators went to pending list and appropriate message (2) was displayed.
Confirmed balance decreased as expected for tip.

connected | connected | gemini | gemini | uphold | uphold | wallet panel | pending tips
-----------|-------------|--------|-------|--------|---------|------------|-------------
<img width="410" alt="Screen Shot 2021-10-11 at 1 45 11 PM" src="https://user-images.githubusercontent.com/387249/136853755-97460887-5312-45d4-86fc-c9e5fbc67f04.png"> | <img width="1321" alt="Screen Shot 2021-10-11 at 1 45 21 PM" src="https://user-images.githubusercontent.com/387249/136853758-914b657b-5c74-417f-bf4a-f72d39c5c13b.png"> | <img width="411" alt="Screen Shot 2021-10-11 at 1 45 54 PM" src="https://user-images.githubusercontent.com/387249/136853793-4ecaf91b-3fb3-46cb-9b8b-3db99fe344aa.png"> |<img width="1316" alt="Screen Shot 2021-10-11 at 1 46 01 PM" src="https://user-images.githubusercontent.com/387249/136853795-885b1540-6433-4a48-aac5-eb7a47e02a81.png"> | <img width="415" alt="Screen Shot 2021-10-11 at 1 46 55 PM" src="https://user-images.githubusercontent.com/387249/136853818-89d1733f-53da-4875-aa24-406162b3b287.png"> | <img width="1317" alt="Screen Shot 2021-10-11 at 1 47 02 PM" src="https://user-images.githubusercontent.com/387249/136853820-45cd18bc-35c8-4833-bb65-2c52b42db857.png"> |<img width="380" alt="Screen Shot 2021-10-11 at 1 47 27 PM" src="https://user-images.githubusercontent.com/387249/136853892-e355d66a-0ff5-4c94-8ddd-bc6253ea894e.png"> | <img width="916" alt="Screen Shot 2021-10-11 at 1 47 18 PM" src="https://user-images.githubusercontent.com/387249/136853890-5df3bec5-c923-4d03-bc77-4eb2d35fc1ea.png">

Confirmed able to tip bitFlyer KYC'd creator and no messaging was displayed.
Confirmed balance decreased as expected for tip.

example | example | example | example
---------|----------|----------|---------
<img width="416" alt="Screen Shot 2021-10-11 at 1 51 36 PM" src="https://user-images.githubusercontent.com/387249/136854275-82211593-f1de-41bc-a11a-3e94bec16e8d.png"> | <img width="1313" alt="Screen Shot 2021-10-11 at 1 51 43 PM" src="https://user-images.githubusercontent.com/387249/136854281-db2a2e4e-78d7-4a48-a584-a8257519e473.png"> | <img width="623" alt="Screen Shot 2021-10-11 at 1 53 10 PM" src="https://user-images.githubusercontent.com/387249/136854283-a841f16f-afa8-4945-8024-2faec53b99f5.png"> | <img width="386" alt="Screen Shot 2021-10-11 at 1 53 18 PM" src="https://user-images.githubusercontent.com/387249/136854284-ffbb7606-2b29-4a9e-a275-ca7ce08def5b.png">


Gemini wallet (funded by Gemini BAT on staging env)

example | example | example | example
---------|----------|---------|----------
