### ISSUE TITLE
Custom notifications are shown when native(system) notifications are enabled

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#18342]
native(system) notifications must be used when native(system) notifications are enabled and 
 For Windows 10 build 17134 and newer (should not be shown if Focus Assist is enabled)
 For macOS 10.14 and newer if native notifications are enabled
 For Android 8 and newer

More info https://github.com/brave/brave-variations/pull/120

## Steps to Reproduce

1. Enable native(system) notifications
1.  Run Brave with `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true --variations-server-url=https://variations.bravesoftware.com/seed`
1. Restart Brave
1. Make sure variations are downloaded in `brave://version`
1. Enable rewards and ads
1. Trigger an ad

## Actual result:

Custom notification is shown

## Expected result:
native(system) notifications is shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.30.84 Chromium: 94.0.4606.54 (Official Build) (64-bit)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | Windows 10 Version 20H2 (Build 19042.1237)

cc @brave/legacy_qa @rebron @tmancey @jsecretan

**Comment by kjozwiak** [comment]
As @btlechowski mentioned, this is also reproducible on `macOS 11.5.2 x64` as well. Even though you have system notifications enabled via `Notifications` under `System Notifications`, you're always going to get added into the following and you'll get custom ad notifications 100% of the time even though native notifications should be shown/used:

```
[9007:259:0924/120415.982593:VERBOSE1:features.cc(45)] Study BraveAds.ShowCustomAdNotificationOnMacStudy is active (Enabled)
```

This is in relation to https://github.com/brave/brave-variations/pull/120. Specifically:

Native ad notifications should be displayed via the following when:

*  for macOS 10.14 and newer if native notifications are enabled - seeing custom ad notifications
* for Windows 10 build 17134 and newer (should not be shown if Focus Assist is enabled) - seeing custom ad notifications

**Comment by tmancey** [comment]
@btlechowski fixed via variations seed

**Comment by btlechowski** [comment]
Needs to be verified with seed from https://github.com/brave/brave-variations/pull/128

**Comment by kjozwiak** [comment]
Once we get RC builds, we should quickly run throughhttps://github.com/brave/brave-variations/pull/129 to make sure things are working as expected. There's some notes/better STR/Cases outlined via https://github.com/brave/brave-variations/pull/120 which is the same PR but merged into `main` (staging).

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)
-- | --
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | Windows 10 Version 21H1 (Build 19043.1237)

```

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.30.86 x64 build
- Verified test plan from https://github.com/brave/brave-variations/pull/120 & issue description
- Verified default ad notification is shown when native notifications are enabled
- Verified custom ad notification is shown when flag is enabled and native notifications are disabled 
- Encountered #18351 on Android as well when using command line flag for variations and disabling native notifications

Native Ads | Custom Ads via Flags
-- | --
![image](https://user-images.githubusercontent.com/17010094/135084383-bd2012e4-7c2d-4bbd-a5c6-439dd4fc95a7.png) | ![image](https://user-images.githubusercontent.com/17010094/135084349-fad0da16-3b88-45ad-ad2a-7da5faf09087.png)
