### ISSUE TITLE
[MacOS] Do not override notifications to `alerts` for the browser app.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#18345]
As part of the fix for https://github.com/brave/brave-core/pull/3850, we ended up tweaking `.plist` for the browser app to use `alert` notifications (rather than `banner`).

This doesn't appear to be needed any more, so we can remove tweaking of `.plist`s and get in sync with Chromium: main app shows banners and Alerts Helper (previously XPC service) shows alerts.

**Testing:**

1. MacOS notifications prompts on fresh install and upgrade
* Fresh install should show 2 prompts
* Upgrade may show either one or zero prompts (depending on if the older version had 1 or 2 prompts when installed)

2. Ad notifications on fresh install and upgrade (@tmancey, please update this part as necessary)

**Comment by kjozwiak** [comment]
@brave/legacy_qa there's more information/test cases that @btlechowski provided via https://github.com/brave/brave-browser/issues/18342. We'll just use this one for verification notes but if you need more context, please take a look at https://github.com/brave/brave-browser/issues/18342.

**Comment by kjozwiak** [comment]
@brave/legacy_qa we'll use this issue to add our verification notes but if you would like more information/context regarding the the problem, please take a look at https://github.com/brave/brave-browser/issues/18276 where @LaurenWags added some cases/screenshots. We'll be running through the cases that @tmancey provided via https://github.com/brave/brave-core/pull/10237#issue-1005859532.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.6 x64` using the following build:

```
Brave | 1.30.86 Chromium: 94.0.4606.61 (Official Build) (x86_64)
--- | ---
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | macOS Version 11.6 (Build 20G165)
```

Went through and verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/10237#issue-1005859532 as per the following:

### **`Test Case #1`** (Upgrade `0.70.123` --> ` 1.30.86` - pre https://github.com/brave/brave-browser/issues/6466)
```
Brave | 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)
--- | ---
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.16 (Build 20G165)
```

* ensured that two notification prompts are being shown when launching `0.70.123 Chromium: 78.0.3904.97`
* checked `Notifications` under `System Preferences` and ensured one is for `Alerts` and the other is for `Banners` permissions
* visited `https://www.bennish.net/web-notifications.html` and ensured that the web notifications dismiss after `5s`

**`NOTE:`**: You won't be able to check ad notifications while on  `0.70.123 Chromium: 78.0.3904.97` as that's been disabled/not working via server side.

**`Before Upgrading`**

**`Example`** | **`Example`** | **`Example`** 
---------------|----------------|----------------
<img width="1207" alt="Screen Shot 2021-09-28 at 12 30 43 AM" src="https://user-images.githubusercontent.com/2602313/135025327-581ed8c1-d57d-4a33-b447-3f12221987e7.png"> | <img width="679" alt="Screen Shot 2021-09-28 at 12 31 08 AM" src="https://user-images.githubusercontent.com/2602313/135025335-ed8ef973-134a-4db9-9d5c-2be032dacff1.png"> | <img width="1207" alt="Screen Shot 2021-09-28 at 12 34 10 AM" src="https://user-images.githubusercontent.com/2602313/135025337-ac9eabfb-fa0a-4e35-a3db-256d992db7ea.png">

* replace `0.70.123 Chromium: 78.0.3904.97` with `1.30.86 Chromium: 94.0.4606.61`
* re-launch Brave and you shouldn't see any notification permission prompts (`Alerts` & `Banners` already in `Notifications`)
* visited `https://www.bennish.net/web-notifications.html` and ensured that the web notifications dismiss after `5s`
* triggered an ad notification and ensured that it's dismissed after `2mins` (120s timeout)

```
[3465:259:0928/005604.532435:VERBOSE1:ads_impl.cc(204)] Browser state changed to idle
[3465:259:0928/005656.575606:VERBOSE1:ads_impl.cc(221)] Browser state changed to unidle after 56 s
[3465:259:0928/005656.581381:VERBOSE1:eligible_ad_notifications.cc(90)] Get eligible ads for parent-child segments:
[3465:259:0928/005656.581465:VERBOSE1:eligible_ad_notifications.cc(92)]   technology & computing-software
[3465:259:0928/005656.581508:VERBOSE1:eligible_ad_notifications.cc(92)]   technology & computing-technology & computing
[3465:259:0928/005656.581548:VERBOSE1:eligible_ad_notifications.cc(92)]   personal finance-personal finance
[3465:259:0928/005656.594164:VERBOSE2:ad_pacing_util.h(23)] Pacing delivery for creative instance id e026e947-ec19-47e6-8c5b-4e4408d91198 [Roll(0.764781):0.931497]
[3465:259:0928/005656.594229:VERBOSE2:ad_pacing_util.h(23)] Pacing delivery for creative instance id 0fc9ea04-5b12-4f79-b9b2-830c784799f3 [Roll(0.764781):0.842398]
[3465:259:0928/005656.594265:VERBOSE2:ad_priority.h(32)] 11 ads with a priority of 1 in bucket 1
[3465:259:0928/005656.594669:VERBOSE1:ad_notification_serving.cc(126)] Found 11 eligible ads
[3465:259:0928/005656.594717:VERBOSE1:ad_notification_serving.cc(222)] Serving ad notification:
  uuid: 12523ed2-40d3-49b5-abfc-a7351d3d6c8c
  creativeInstanceId: f1126b98-761f-4092-a067-28928809ab25
  creativeSetId: 755e6092-854b-4722-9c34-fa5bdd62565d
  campaignId: 091c9617-cbfd-4087-8219-10d791e42a2d
  advertiserId: fc06e101-e5bc-44dd-8c89-77958f7ea53d
  segment: technology & computing-software
  title: Coinsmart.com/bravecrypto
  body: Buying BTC with CAD? Try CoinSmart & get free $30 in BTC
  targetUrl: https://www.coinsmart.com/bravecrypto/
[3465:259:0928/005656.595118:VERBOSE1:ads_service_impl.cc(1971)] Timeout ad notification with uuid 12523ed2-40d3-49b5-abfc-a7351d3d6c8c in 120 seconds
```

**`After Upgrading`**

**`Example`** | **`Example`** | **`Example`** 
---------------|----------------|----------------
<img width="679" alt="Screen Shot 2021-09-28 at 12 40 21 AM" src="https://user-images.githubusercontent.com/2602313/135025936-73098554-af05-484f-9294-07ce1eb8aa15.png"> | <img width="1302" alt="Screen Shot 2021-09-28 at 12 40 14 AM" src="https://user-images.githubusercontent.com/2602313/135025961-d9b253eb-d562-4b29-923f-f15e7f957db2.png"> | <img width="1302" alt="Screen Shot 2021-09-28 at 12 42 51 AM" src="https://user-images.githubusercontent.com/2602313/135025966-cfad0457-e658-4893-99f5-cd20764b930d.png">

### **`Test Case #2`** (Upgrade from C93 --> C94)

```
Brave | 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
--- | ---
Revision | e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}
OS | macOS Version 11.6 (Build 20G165)
```

* ensured that a single notification prompts is being shown when launching `1.29.81 Chromium: 93.0.4577.82`
* checked `Notifications` under `System Preferences` ensured that the `Alerts` permission is being listed
* visited `https://www.bennish.net/web-notifications.html` and ensured that the web notifications dismiss after `5s`
* triggered an ad notification and ensured that it's dismissed after `2mins` (120s timeout)

```
[2956:259:0928/000423.059584:VERBOSE1:ads_service_impl.cc(1971)] Timeout ad notification with uuid 27a8195b-ce5f-4cf9-b138-a77d368d8f61 in 120 seconds
```

**`Before Upgrading`**

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|----------------|----------------|-----------------
<img width="1201" alt="Screen Shot 2021-09-27 at 11 30 32 PM" src="https://user-images.githubusercontent.com/2602313/135022062-c521bbd0-fe0d-4104-94b6-b5fcf9e6689e.png"> | <img width="690" alt="Screen Shot 2021-09-27 at 11 30 52 PM" src="https://user-images.githubusercontent.com/2602313/135022073-f468336f-cb8f-49dd-813a-9b899a6b4820.png"> | <img width="1227" alt="Screen Shot 2021-09-27 at 11 48 24 PM" src="https://user-images.githubusercontent.com/2602313/135022083-5f4ee972-3db6-4fbe-810e-b99c4ee40716.png"> | <img width="1218" alt="Screen Shot 2021-09-27 at 11 50 18 PM" src="https://user-images.githubusercontent.com/2602313/135022089-e48881f3-9f55-491c-8592-28a3022f7e99.png"> | <img width="1259" alt="Screen Shot 2021-09-27 at 11 57 22 PM" src="https://user-images.githubusercontent.com/2602313/135022101-4e20f30d-61bd-4dde-83c5-ee1d158538bb.png">

* re-launched Brave using `--update-feed-url=https://updates.bravesoftware.com/sparkle/Brave-Browser/test/appcast.xml`
* upgraded to `1.30.86 Chromium: 94.0.4606.61` and ensured that a single permission notification request appeared
* checked `Notifications` under `System Preferences` ensured that the `Banners` permission is being listed alongside `Alerts`
* visited `https://www.bennish.net/web-notifications.html` and ensured that the web notifications dismiss after `5s`
* triggered an ad notification and ensured that it's dismissed after `2mins` (120s timeout)

```
[2956:259:0928/001644.813654:VERBOSE1:ads_service_impl.cc(1971)] Timeout ad notification with uuid 66e05d08-ae64-490f-b044-2121d3aeb4c1 in 120 seconds
```

* ensured that clicking on ad notifications works as expected

```
[2956:259:0928/001643.794027:VERBOSE1:ads_impl.cc(204)] Browser state changed to idle
[2956:259:0928/001644.795699:VERBOSE1:ads_impl.cc(221)] Browser state changed to unidle after 5 s
[2956:259:0928/001644.800567:VERBOSE1:eligible_ad_notifications.cc(90)] Get eligible ads for parent-child segments:
[2956:259:0928/001644.800634:VERBOSE1:eligible_ad_notifications.cc(92)]   technology & computing-software
[2956:259:0928/001644.800683:VERBOSE1:eligible_ad_notifications.cc(92)]   business-marketing
[2956:259:0928/001644.800726:VERBOSE1:eligible_ad_notifications.cc(92)]   personal finance-personal finance
[2956:259:0928/001644.812676:VERBOSE2:ad_pacing_util.h(23)] Pacing delivery for creative instance id e026e947-ec19-47e6-8c5b-4e4408d91198 [Roll(0.764674):0.940787]
[2956:259:0928/001644.812733:VERBOSE2:ad_priority.h(32)] 14 ads with a priority of 1 in bucket 1
[2956:259:0928/001644.813235:VERBOSE1:ad_notification_serving.cc(126)] Found 14 eligible ads
[2956:259:0928/001644.813304:VERBOSE1:ad_notification_serving.cc(222)] Serving ad notification:
  uuid: 66e05d08-ae64-490f-b044-2121d3aeb4c1
  creativeInstanceId: 42f4d6c8-6056-4c5c-a821-6c471a2809ba
  creativeSetId: 5492cf86-e74e-41e3-9e63-2d8b2a31884b
  campaignId: aadf3903-cc96-4673-96d6-a0ef9fc95c0f
  advertiserId: 8ca6dfad-899b-4693-a3dd-0c4a0a2b4dc7
  segment: technology & computing-software
  title: Heatbit
  body: Electric heater that makes you money by mining bitcoin
  targetUrl: https://heatbit.com/brave
[2956:259:0928/001644.813654:VERBOSE1:ads_service_impl.cc(1971)] Timeout ad notification with uuid 66e05d08-ae64-490f-b044-2121d3aeb4c1 in 120 seconds
```

**`After Upgrading`**

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|----------------|----------------|-----------------
<img width="1263" alt="Screen Shot 2021-09-27 at 11 57 35 PM" src="https://user-images.githubusercontent.com/2602313/135022720-81801a57-5271-41ab-b382-e73b7274bcee.png"> | <img width="697" alt="Screen Shot 2021-09-27 at 11 57 49 PM" src="https://user-images.githubusercontent.com/2602313/135022727-9d641e64-f055-48f8-b4a0-3fad855c46bc.png"> | <img width="1277" alt="Screen Shot 2021-09-27 at 11 58 34 PM" src="https://user-images.githubusercontent.com/2602313/135022746-54b91bf4-bf88-461b-93e2-bc5243294fbd.png"> | <img width="1245" alt="Screen Shot 2021-09-28 at 12 04 34 AM" src="https://user-images.githubusercontent.com/2602313/135022755-2d69ff31-4122-4693-8b5b-6bbdf0afdd6e.png">

### **`Test Case #3`** (Clean Install)

```
Brave | 1.30.86 Chromium: 94.0.4606.61 (Official Build) (x86_64)
--- | ---
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | macOS Version 11.6 (Build 20G165)
```

* ensured that two notification prompts are being shown when launching `1.30.86 Chromium: 94.0.4606.61`
* checked `Notifications` under `System Preferences` and ensured one is for `Alerts` and the other is for `Banners` permissions
* visited `https://www.bennish.net/web-notifications.html` and ensured that the web notifications dismiss after `5s`
* triggered an ad notification and ensured that it's dismissed after `2mins` (120s timeout)

```
[2179:259:0927/232031.899662:VERBOSE1:ads_service_impl.cc(1971)] Timeout ad notification with uuid 444b6d47-0742-4174-bde3-3dd5037fb94a in 120 seconds
```

* ensured that clicking on ad notifications works as expected

```
[2179:259:0927/232031.889084:VERBOSE1:eligible_ad_notifications.cc(90)] Get eligible ads for parent-child segments:
[2179:259:0927/232031.889156:VERBOSE1:eligible_ad_notifications.cc(92)]   technology & computing-software
[2179:259:0927/232031.889200:VERBOSE1:eligible_ad_notifications.cc(92)]   technology & computing-technology & computing
[2179:259:0927/232031.889263:VERBOSE1:eligible_ad_notifications.cc(92)]   personal finance-personal finance
[2179:259:0927/232031.898874:VERBOSE2:ad_priority.h(32)] 15 ads with a priority of 1 in bucket 1
[2179:259:0927/232031.899231:VERBOSE1:ad_notification_serving.cc(126)] Found 15 eligible ads
[2179:259:0927/232031.899271:VERBOSE1:ad_notification_serving.cc(222)] Serving ad notification:
  uuid: 444b6d47-0742-4174-bde3-3dd5037fb94a
  creativeInstanceId: 9fed67e0-5fe2-4682-b147-e5b1ff26c58d
  creativeSetId: e3fa4776-d529-4ae9-9c6e-7741232ee1df
  campaignId: 399a5816-33b9-4167-b7c6-d8783ed9ddd8
  advertiserId: b6d581f3-cf2c-4422-a43c-75d4a675fe58
  segment: technology & computing-software
  title: Bitbuy - Canada's #1 Platform
  body: Wow! Get $20 free when you make your first deposit
  targetUrl: https://bitbuy.ca/en/sign-up/?c=Brave
[2179:259:0927/232031.899662:VERBOSE1:ads_service_impl.cc(1971)] Timeout ad notification with uuid 444b6d47-0742-4174-bde3-3dd5037fb94a in 120 seconds
```

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|----------------|----------------|-----------------
<img width="1213" alt="Screen Shot 2021-09-27 at 10 56 10 PM" src="https://user-images.githubusercontent.com/2602313/135017874-46af1301-deed-4add-b1f0-74e084dab063.png"> | <img width="687" alt="Screen Shot 2021-09-27 at 10 56 48 PM" src="https://user-images.githubusercontent.com/2602313/135017873-a15b544b-83a6-48fe-b226-14b259327e9c.png"> | <img width="1241" alt="Screen Shot 2021-09-27 at 11 04 30 PM" src="https://user-images.githubusercontent.com/2602313/135017875-550d9335-f297-4990-98e2-5df0002e4a47.png"> | <img width="1222" alt="Screen Shot 2021-09-27 at 11 06 13 PM" src="https://user-images.githubusercontent.com/2602313/135017871-8d3aa165-5d21-4665-b95b-5490aabd91c3.png">

**Comment by LaurenWags** [comment]
Verification **In Progress** on `macOS 10.15.7 x64` using the following build:

```
Brave	1.30.86 Chromium: 94.0.4606.61 (Official Build) (x86_64)
Revision	418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS	macOS Version 10.15.7 (Build 19H1417)
```

Went through and verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/10237#issue-1005859532 as per the following:

### **`Test Case #1`** (Upgrade `0.70.123` --> ` 1.30.86` - pre https://github.com/brave/brave-browser/issues/6466)
```
Brave	0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)
Revision	021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS	macOS Version 10.15.7 (Build 19H1417)
```

* ensured that two notification prompts are being shown when launching `0.70.123 Chromium: 78.0.3904.97`
* checked `Notifications` under `System Preferences` and ensured one is for `Alerts` and the other is for `Banners` permissions
* visited `https://www.bennish.net/web-notifications.html` and ensured that the web notifications dismiss after `5s`

**`NOTE:`**: You won't be able to check ad notifications while on  `0.70.123 Chromium: 78.0.3904.97` as that's been disabled/not working via server side.

**`Before Upgrading`**

**`Example`** | **`Example`** | **`Example`** 
---------------|----------------|----------------
<img width="1200" alt="Screen Shot 2021-09-28 at 7 50 11 AM" src="https://user-images.githubusercontent.com/28145373/135081794-f6d1b6f1-7210-4c5e-9088-b874473894cc.png"> | <img width="664" alt="Screen Shot 2021-09-28 at 7 50 50 AM" src="https://user-images.githubusercontent.com/28145373/135081804-eb6522c1-0bee-49b1-a03c-2998ff86500b.png"> | <img width="1198" alt="Screen Shot 2021-09-28 at 7 52 31 AM" src="https://user-images.githubusercontent.com/28145373/135081822-f2989991-8faf-4966-b211-b10275afa999.png">


* replace `0.70.123 Chromium: 78.0.3904.97` with `1.30.86 Chromium: 94.0.4606.61`
* * re-launch Brave and I did receive a notification permission prompt (`Alerts` & `Banners` were already in `Notifications` but `Banners` had been turned Off, the prompt was to re-enable it)
* visited `https://www.bennish.net/web-notifications.html` and ensured that the web notifications dismiss after `5s`
* triggered an ad notification and ensured that it's dismissed after `2mins` (120s timeout)

```
[3047:775:0928/080309.494619:VERBOSE1:ad_notification_serving.cc(222)] Serving ad notification:
  uuid: 9c110c65-5b57-4ee7-a2f8-745953696933
  creativeInstanceId: c9c1df09-236e-4cbd-aeea-a21a9ef5cfbd
  creativeSetId: e4e150a3-3764-4657-a5f2-82ca27f65be7
  campaignId: a9309655-ded0-4993-9fa7-778709012f99
  advertiserId: 8cfac071-75f8-46ab-9c7f-4f8420d914d7
  segment: untargeted
  title: Quicken Loans
  body: Want to refinance again? - Lock a low rate
  targetUrl: https://mortgage.quickenloans.com/lending/home-refinance?providerId=14278391&pkey1=&pkey2=&pkey3=&sourceid=lmb-75400-196325
[3047:775:0928/080309.494652:VERBOSE9:client.cc(573)] Saving client state
[3047:775:0928/080309.494793:VERBOSE9:ad_notifications.cc(381)] Saving ad notifications state
[3047:775:0928/080309.495037:VERBOSE1:ads_service_impl.cc(1971)] Timeout ad notification with uuid 9c110c65-5b57-4ee7-a2f8-745953696933 in 120 seconds
```

**`After Upgrading`**

**`Example`** | **`Example`** | **`Example`** 
---------------|----------------|----------------
<img width="1202" alt="Screen Shot 2021-09-28 at 8 01 20 AM" src="https://user-images.githubusercontent.com/28145373/135083407-60f9277b-776a-4fad-8457-42a405fde73b.png"> | <img width="1198" alt="Screen Shot 2021-09-28 at 8 02 13 AM" src="https://user-images.githubusercontent.com/28145373/135083418-85e97ed0-df81-45f7-8484-61cbd12839fc.png"> | <img width="1200" alt="Screen Shot 2021-09-28 at 8 03 25 AM" src="https://user-images.githubusercontent.com/28145373/135083436-c0b236d5-35b0-4f0b-a52e-c7f1f69020db.png">
