### ISSUE TITLE
adding recurring date within the tip table under brave://rewards

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1834]
## Description 

We should display the recurring date within the Tip table under `brave://rewards`. Once a user sets a recurring tip and forgets the date, there's no visible way to check via the current UI.

## Steps to Reproduce

   1. launch the most recent version of brave (`0.55.20 Chromium: 70.0.3538.67` in this case)
   2. enable rewards via `brave://rewards` & accept a grant
   3. visit a any website and click on the `BAT` icon under the URL
   4. click on `Send tip..`
   5. select an amount and enable `Make this monthly` and click on `Set monthly Tip`
   6. visit `brave://rewards` and you'll see the entry but there's no visible recurring date

## Actual result:

<img width="639" alt="screen shot 2018-10-25 at 3 04 18 am" src="https://user-images.githubusercontent.com/2602313/47481807-cadfd100-d802-11e8-8173-f9e559e3b461.png">

## Expected result:

We should display the recurring date within the table. Once a user sets a recurring tip and forgets the date, there's no visible way to check via the current UI.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, reproducible under both `dev` and `beta` as well.

### Additional Information

CCing @jenn-rhim

**Comment by NejcZdovc** [comment]
@kjozwiak recurring date is the same as auto contribute date in table above

**Comment by NejcZdovc** [comment]
ping @davidtemkin @mandar-brave should we implement this or close it?

**Comment by davidtemkin** [comment]
Let's do it. Add a line to the Tips panel, as follows: 

"Monthly tips will next be sent" followed by the next contribution date. 

The formatting should match the line in the A-C panel ("next contribution date").

*NOTE* : This line should only appear if the user has established one or more monthly tips. In the event that there are no active monthly tips, the line should not appear.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1412
* Verified if there are no recurring tips, the contribution line is not displayed:
![screen shot 2019-02-08 at 5 43 44 pm](https://user-images.githubusercontent.com/28145373/52510531-528ef700-2bca-11e9-8a27-7698d38e6415.png)
![screen shot 2019-02-08 at 5 44 55 pm](https://user-images.githubusercontent.com/28145373/52510536-5458ba80-2bca-11e9-9863-90964c18851c.png)
* Verified when there is at least one recurring tip the contribution line is displayed:
![screen shot 2019-02-08 at 5 45 10 pm](https://user-images.githubusercontent.com/28145373/52510557-676b8a80-2bca-11e9-9a35-741e921dd402.png)
* Verified that if only one recurring tip is listed and you remove it, the contribution date line is removed from view
* Verified that once monthly recurring tips contribute, the date in this panel is updated:
![screen shot 2019-02-08 at 5 50 09 pm](https://user-images.githubusercontent.com/28145373/52510562-70f4f280-2bca-11e9-8650-ba6e90074913.png)
![screen shot 2019-02-08 at 5 51 40 pm](https://user-images.githubusercontent.com/28145373/52510566-72261f80-2bca-11e9-8869-96850e0df383.png)
