### ISSUE TITLE
Pin test page for TLS pinning

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#18352]
Now that we have a [test page](https://ssl-pinning.someblog.org/) which is using a CA outside of our pinset (Sectigo), we need to pin it in order to trigger the interstitial page.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.32.31 Chromium: 94.0.4606.61 (Official Build) nightly (x86_64)
-- | --
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. clean profile
2. launched Brave
3. loaded `https://ssl-pinning.someblog.org/`

Confirmed I now see the interstitial warning page

before | after
-------|------
<img width="1738" alt="Screen Shot 2021-09-29 at 8 32 01 AM" src="https://user-images.githubusercontent.com/387249/135301301-3e7742b2-1e2a-469c-bbe9-e9e5e1e67aba.png"> | <img width="1738" alt="Screen Shot 2021-09-29 at 8 32 08 AM" src="https://user-images.githubusercontent.com/387249/135301308-710ae3c1-0b89-4e4e-bc90-19c794fa7f11.png">
