### ISSUE TITLE
Keepassxc extension integration

### ISSUE THREAD

**Issue by tneo** [brave/brave-browser#1835]
## Description 
After installing the KeepassXC browser extension, the extension is not able to connect to the database. While Vivaldi (chromium based as well) can connect to the database. 

## Steps to Reproduce

   1. Set-up KeepassXC database and allow chromium browser integration (settings > browser integration > check Chromium)
   2. Install KeepassXC extension from chrome store
   3. Connect to Database. 

## Actual result:
Timeout message is thrown. Under settings in the extension the database name is not showing.

## Expected result:
Successfully connected to the database to manage passwords.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)

### Reproducible on current release:
Yes. Latest beta has the same issue.

### Additional Information
Cross link: https://github.com/keepassxreboot/keepassxc/issues/2414

**Comment by tneo** [comment]
I can try that when I'm home again. What I forgot to mention in my ticket is that I'm running openSUSE.

**Comment by tneo** [comment]
Allowing all cookies does not have effect. I also tried to add a symlink as suggested [here](https://github.com/keepassxreboot/keepassxc/issues/2414)

**Comment by tneo** [comment]
Adding a symlink to `org.keepassxc.keepassxc_browser.json` in `.config/BraveSoftware/Brave-Browser/NativeMessagingHosts` makes integration work. That file is found in `.config/Chromium/NativeMessagingHosts`

**Comment by hirvinen** [comment]
Seems to work now, at least on Mac OS Mojave, *without* checking chromium under browser integration settings.

**Comment by nickmcgill** [comment]
> Adding a symlink to `org.keepassxc.keepassxc_browser.json` in `.config/BraveSoftware/Brave-Browser/NativeMessagingHosts` makes integration work. That file is found in `.config/Chromium/NativeMessagingHosts`

Thank you - I copied the file instead. It fixed the problem!

**Comment by monaxle** [comment]
Thank you +1. This worked for me too.

**Comment by mjgiarlo** [comment]
I'm not sure this is fixable on the Brave side. Here's the issue in KeePassXC land (at least for Linux): https://github.com/keepassxreboot/keepassxc/issues/2414 The issue (consistent with @tneo's account above) seems to be that KeePassXC doesn't have an integration option for Brave, and thus doesn't know where to put its JSON configuration. This seems like it may be a `wontfix` for Brave?

**Comment by tomlowenthal** [comment]
Happy to close until I hear otherwise.

**Comment by telmotrooper** [comment]
Just to let anyone interested know, as of today (November 11, 2019), KeePassXC already has an option to enable Brave integration. Enabling it and installing the [KPXC Chrome extension](https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk) on Brave works fine.

**Comment by gb-123-git** [comment]
How to fix it for Brave in Windows 10 ? Any registry key that needs to be added ?
