### ISSUE TITLE
Custom ad notifications are not shown when system notifications are disabled

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#18351]
We should fall back to custom ad notifications when system notifications are disabled

Follow up to: https://github.com/brave/brave-variations/pull/120
```
Should show custom ad notifications:
- For all Windows versions If native notifications are disabled (should not be shown if Focus Assist is enabled)
```

## Steps to Reproduce

1. Disable native(system) notifications
1.  Run Brave with `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true --variations-server-url=https://variations.bravesoftware.com/seed`
1. Restart Brave
1. Make sure variations are downloaded in `brave://version`
1. Enable rewards and ads
1. Trigger an ad

## Actual result:

Notification is not shown at all 

## Expected result:
Custom notification is shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.30.84 Chromium: 94.0.4606.54 (Official Build) (64-bit)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | Windows 10 Version 20H2 (Build 19042.1237)

cc @brave/legacy_qa @rebron @tmancey @jsecretan

**Comment by btlechowski** [comment]
Needs to be verified along with https://github.com/brave/brave-variations/pull/128

**Comment by srirambv** [comment]
Issue repro'd on Android as well. Using command line args for variations ad notifications are not shown. Logs shows 
```
2021-09-28 08:06:19.021 31780-31780/? V/chromium: [VERBOSE2:permission_rule_util.cc(23)] Notifications not allowed
2021-09-28 08:06:19.021 31780-31780/? V/chromium: [VERBOSE1:ad_notification_serving.cc(104)] Ad notification not served: Not allowed due to permission rules
2021-09-28 08:06:19.025 31780-31780/? V/chromium: [VERBOSE1:ad_notification_serving.cc(187)] Maybe serve ad notification in 0 hours, 2 minutes, 0 seconds at 5:38 PM
2021-09-28 08:08:19.030 31780-31780/? V/chromium: [VERBOSE2:permission_rule_util.cc(23)] Notifications not allowed
2021-09-28 08:08:19.031 31780-31780/? V/chromium: [VERBOSE1:ad_notification_serving.cc(104)] Ad notification not served: Not allowed due to permission rules
2021-09-28 08:08:19.035 31780-31780/? V/chromium: [VERBOSE1:ad_notification_serving.cc(187)] Maybe serve ad notification in 0 hours, 2 minutes, 0 seconds at 5:40 PM
2021-09-28 08:10:19.041 31780-31780/? V/chromium: [VERBOSE2:permission_rule_util.cc(23)] Notifications not allowed
2021-09-28 08:10:19.041 31780-31780/? V/chromium: [VERBOSE1:ad_notification_serving.cc(104)] Ad notification not served: Not allowed due to permission rules
2021-09-28 08:10:19.046 31780-31780/? V/chromium: [VERBOSE1:ad_notification_serving.cc(187)] Maybe serve ad notification in 0 hours, 2 minutes, 0 seconds at 5:42 PM
```

**Comment by tmancey** [comment]
We only move the`can_fallback_to_custom_notifications` parameter from the `CustomAdNotifications` feature to the `AdNotifications` feature. I would recommend that we only need to test the `can_fallback_to_custom_notifications` parameter. There are no business logic changes

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.32.43 Chromium: 94.0.4606.71 (Official Build) nightly (64-bit)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | Linux

Verified custom ads are shown when `BraveAds.ShowCustomAdNotificationOnLinuxStudy` is enabled

![image](https://user-images.githubusercontent.com/34715963/136071738-3c4d413a-80e1-4eea-bab1-98f472507e5b.png)

------------

Verification passed on

Brave | 1.32.38 Chromium: 94.0.4606.71 (Official Build) nightly (64-bit)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified custom ads are shown when `BraveAds.ShowCustomAdNotificationOnWindowsStudy` is enabled on Windows 7

![image](https://user-images.githubusercontent.com/34715963/136072185-1ba4c49a-24b5-4b01-9169-75c5ea7dd7e8.png)

-------------

Verification passed on

Brave | 1.32.43 Chromium: 94.0.4606.71 (Official Build) nightly (64-bit)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | Window 10 Version 20H2 (Build 19042.1237)

Important: Made sure that on nightly study `BraveAds.ShowCustomAdNotificationOnWindowsStudy:Default` was used, otherwise custom ads will be always shown

Verified native(system) ads are shown when system notifications are enabled:
![18351 system notifications](https://user-images.githubusercontent.com/34715963/136083863-b2bb6b64-56ed-4e2b-bd9b-5f86adf9599e.png)

Verified custom ads are shown when system notifications are disabled:
![18351 custom notifications](https://user-images.githubusercontent.com/34715963/136084124-22886434-c004-497b-b380-bd95f41c4302.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on Gionee s5 with `Android 5.1` running `Bravearm1.30.89.apk` build

Verified when system native notifications are disabled and variations seed enabled, custom ads notification is shown based on `BraveAds.ShowCustomAdsNotificationOnAndroidStudy:Enabled` being enabled
