### ISSUE TITLE
Brave can't block Amazon associate ads.

### ISSUE THREAD

**Issue by sys9kdr** [brave/brave-browser#18357]
## Description 

Brave can't block Amazon Associate ads(`amazon-adsystem.com`).
A rule that block (`amazon-adsystem.com`) doesn't work.

## Steps to Reproduce

I created new profile for testing. All configurations are default mode.

   1. Open `brave://adblock` and disable all additional filters.
   2. Add a rule that blocks `||amazon-adsystem.com^` to custom filters.
   3. Open `https://www.giftideageek.com/gag-gifts/` that contains amazon associate ads and browse.

## Actual result:

All connections to `*.amazon-adsystem.com` are not blocked.  Ads shown.

## Expected result:

All connections to `*.amazon-adsystem.com` are blocked.  No ads shown.

## Reproduces how often: 

Easily reproduced. Always.

## Brave version (info found on brave://version)

```
1.32.17 Chromium: 94.0.4606.54 (Official Build) nightly (x86_64)

macOS Version 11.6 (Build 20G165)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?
    - Yes. In version 1.29.81 Chromium: 93.0.4577.82
- Can you reproduce this issue with the nightly channel?
    - Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
    - It is adblocking issue.
- Does the issue resolve itself when disabling Brave Rewards?
    - No.
- Is the issue reproducible on the latest version of Chrome? 
    - No. It is adblocking issue.

### My Adblock Settings

![chrome___adblock_](https://user-images.githubusercontent.com/1529486/134764378-5540912d-6040-4c3a-82bb-b478e11ea4cc.png)

### reproduced page

![image](https://user-images.githubusercontent.com/1529486/134763936-06b036b0-a7a2-47c9-9a18-0bda13006865.png)

![image](https://user-images.githubusercontent.com/1529486/134764049-7d9be335-c573-4729-9f8a-f6f83c12a925.png)

**Comment by ryanbr** [comment]
Hey @sys9kdr 

We block amazon-ads in [Easylist already](https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers.txt#L1282). 

Links to amazon isn't the same as amazon ads. May break the site, but adding into `brave://adblock` `giftideageek.com##a[href^="https://www.amazon.com/"]`

**Comment by sys9kdr** [comment]
@ryanbr  Thank you for replying.

I mistakenly thought rules like `||example.com^` block all connections. In actually, these rules in Brave don't block  `<img src=example.com/foo.gif>` and others. Is my understanding correct?

**Comment by ryanbr** [comment]
Depending on how you want to block it. 

`||example.com/foo.gif` would block the image directly. but if you wanted to prevent an ahref `##a[href^="https://www.asite.com/"]`

**Comment by sys9kdr** [comment]
I misunderstood *Brave has strict blocking mode* like uBlock Origin, but Brave doesn't seems to  have strict blocking mode.

https://adblockplus.org/forum/viewtopic.php?f=10&t=44063

Thank you so much.
