### ISSUE TITLE
Build breaks at "vpython3 script/web_discovery_project.py --install --build"

### ISSUE THREAD

**Issue by etna** [brave/brave-browser#18361]
Description:

Build breaks at the runhooks phase, specifically at "vpython3 script/web_discovery_project.py --install --build"

Steps to Reproduce:
   1. Follow the build instructions as published
   2. 
   3. 

Console log:
Running hooks:  98% (117/119) build_web_discovery_project
________ running 'vpython3 script/web_discovery_project.py --install --build' in '/home/etna/Tmpdir/Brave/brave-browser/src/brave'

Traceback (most recent call last):
  File "/home/etna/Tmpdir/Brave/brave-browser/src/brave/script/web_discovery_project.py", line 43, in <module>
    sys.exit(main())
  File "/home/etna/Tmpdir/Brave/brave-browser/src/brave/script/web_discovery_project.py", line 25, in main
    execute_stdout([NPM, 'install'], env=env)
  File "/home/etna/Tmpdir/Brave/brave-browser/src/brave/script/lib/util.py", line 202, in execute_stdout
    execute(argv, env)
  File "/home/etna/Tmpdir/Brave/brave-browser/src/brave/script/lib/util.py", line 184, in execute
    raise RuntimeError('Command \'%s\' failed' % (' '.join(argv)), stderr)
RuntimeError: ("Command 'npm install' failed", "npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.\nnpm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added\nnpm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.\nnpm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'\nnpm WARN deprecated event-to-promise@0.8.0: Use promise-toolbox/fromEvent instead\nnpm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.\nnpm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained\nnpm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'\nnpm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained\nnpm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained\nnpm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\nnpm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.\nnpm WARN deprecated har-validator@5.1.5: this library is no longer supported\nnpm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated\nnpm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated\nnpm ERR! code Z_DATA_ERROR\nnpm ERR! errno -3\nnpm ERR! zlib: incorrect data check\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/etna/.npm/_logs/2021-09-25T15_33_13_890Z-debug.log\n")
Error: Command 'vpython3 script/web_discovery_project.py --install --build' returned non-zero exit status 1 in /home/etna/Tmpdir/Brave/brave-browser/src/brave

Traceback (most recent call last):
  File "/home/etna/Tmpdir/Brave/brave-browser/src/brave/script/web_discovery_project.py", line 43, in <module>
    sys.exit(main())
  File "/home/etna/Tmpdir/Brave/brave-browser/src/brave/script/web_discovery_project.py", line 25, in main
    execute_stdout([NPM, 'install'], env=env)
  File "/home/etna/Tmpdir/Brave/brave-browser/src/brave/script/lib/util.py", line 202, in execute_stdout
    execute(argv, env)
  File "/home/etna/Tmpdir/Brave/brave-browser/src/brave/script/lib/util.py", line 184, in execute
    raise RuntimeError('Command \'%s\' failed' % (' '.join(argv)), stderr)

Expected result:
Build should succeed

Reproduces how often: 
Always reproduced. Last working build was done on 18 Sept.

Kindly assist. Thanks.

**Comment by likhith1542** [comment]
Hey, I am facing the same issue. Did you find any fix for that??

![image](https://user-images.githubusercontent.com/53570191/144762229-a85181c1-2149-4dbb-b56a-ee4c4df14cb9.png)

![image](https://user-images.githubusercontent.com/53570191/144762244-5b11b43f-481b-4b8a-a159-1e6febcabe16.png)

**Comment by likhith1542** [comment]
I found a fix for this.
Use node version less than 16
I rolled back to 15.4.0

**Comment by lostystyg** [comment]
Same here with nodejs 16.13.2 and npm 8.1.2 on void linux. Commit aadf3823265200bf5626c5a54e6d6a5015418245. `npm run init` just  stucks at 98% on performing `Hook 'vpython3 script/web_discovery_project.py`.
The reason was because `npm install --no-save` that is called by the hook inside `brave-browser/src/brave/vendor/web-discovery-project` directory is waiting for input:
```code
Need to install the following packages:
  npm-force-resolutions@0.0.10
Ok to proceed? (y)
```
After manually installing this package hook is no longer stucked. `npm install -y --no-save` can be a good fix because allows to skip this input waiting.
[Here](https://github.com/brave/brave-core/blob/d77084b8fb187f1122587283ef2d877e38af5392/script/web_discovery_project.py#L26) probably just add `'-y'`.

**Comment by etna** [comment]
Two things:

If you are using a downloaded pre-built version of nodejs for Linux from the node.js homepage it most definitely will work, regardless of the version.

But if it's a self-built nodejs most of the problems come down to zlib.

**Comment by bsclifton** [comment]
Hi folks

Going to close this issue - but we do recommend always using the LTS version of node. We had some issues before with newer node version and we've since updated 😄 

Please reply back to this issue if you're still having trouble. Thanks!
