### ISSUE TITLE
Padding on top is missing on the rewards setting pages

### ISSUE THREAD

**Issue by NikharPandya** [brave/brave-browser#18368]
## Steps to reproduce 

   1. Open NTP
   2. Press the reward icon on top right corner
   3. Go to settings
   4. Go to view details for Ads or monthly contribution or tips

## Actual result 

![Screenshot_20210926-131542_Brave.jpg](https://user-images.githubusercontent.com/70164257/134817712-2d7c3ff8-fb6c-4f42-b20a-76725aeca3cd.jpg)

![Screenshot_20210926-131547_Brave.jpg](https://user-images.githubusercontent.com/70164257/134817716-8e208b26-6613-43f3-b1fc-24d440022f09.jpg)

![Screenshot_20210926-131554_Brave.jpg](https://user-images.githubusercontent.com/70164257/134817720-4d80d0bc-d0a4-4295-831a-ba6c1c03acd9.jpg)

## Expected result
There should be padding on the top of title 

## Issue reproduces how often :Easily reproduced

- Can you reproduce this issue with the current Play Store version? 
Yes 
- Can you reproduce this issue with the current Play Store Beta version?
Yes
- Can you reproduce this issue with the current Play Store Nightly version?
Yes

## Device details
   - Install type (ARM, x86):ARM 
   - Device type (Phone, Tablet, Phablet): Samsung galaxy S20 FE
   - Android version: 11 
   
## Brave version : 
 play store :1.29.81
Beta : 1.31.59
Nightly: 1.32.20

**Comment by srirambv** [comment]
Maybe fixed with https://github.com/brave/brave-browser/issues/15969

cc: @deeppandya @Miyayes

**Comment by NikharPandya** [comment]
Okay Thanks
