### ISSUE TITLE
Brave sends referer when open link from Google

### ISSUE THREAD

**Issue by EsuRt** [brave/brave-browser#18360]
## Description 

Brave sends referer when open link from Google. But old version doesn't send, what's the problem?
![1](https://user-images.githubusercontent.com/15177069/134774454-315f59b6-545c-48ef-b6f2-2b384a527990.jpg)

## Brave version (brave://version info)

Brave: 1.29.81 Chromium: 93.0.4577.82
Revision: e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}
OS: Windows 10 OS Version 2009 (Build 19043.1237)

**Comment by NikharPandya** [comment]
@jonathansampson

**Comment by diracdeltas** [comment]
the referer policy was changed in https://github.com/brave/brave-browser/issues/13464
