### ISSUE TITLE
IPFS redirect to localhost doesn't preserve query parameters

### ISSUE THREAD

**Issue by markg85** [brave/brave-browser#18367]
Hi,

Feel free to test this out on my playground site.
https://imagecompare.sc2.nl?cid=QmZPwrgteYTvd8ySbje5RN2WcMxivAbXmTUK6xgJVVfk31

When you are not using any IPFS integration that link works and you get a popup on that page asking for an AES key.

When you enable IPFS integration and have your own local node (so with IPFS set to gateway where it is pointing to your local node, not the brave baked in local node) then you get redirected to:

http://imagecompare.sc2.nl.ipns.localhost:8080/

Where it should have been:

http://imagecompare.sc2.nl.ipns.localhost:8080/?cid=QmZPwrgteYTvd8ySbje5RN2WcMxivAbXmTUK6xgJVVfk31

Side note. Please **ignore** the details that a CID is given as an argument and that you get asked for an AES key on that site if it works properly. The moral of the bug report here is that the url query is not passed on in a redirect which is a bug.

**Comment by stephendonner** [comment]
@spylogsster has filed https://github.com/brave/brave-browser/issues/20567 based on @lidel's investigation of IPFS redirects, and should be verified/vetted, before verifying this issue.

**Comment by stephendonner** [comment]
@markg85: thanks for the report!  Would you be willing to download the latest `nightly` build and let us know if it's fixed?  I'm currently having trouble getting a local testcase going (which I'll continue to work on), but it'd be great to have confirmation from you, as the reporter.  Thanks!  https://github.com/brave/brave-browser/releases

**Comment by markg85** [comment]
Hi @stephendonner I just installed the nightly build. Using Arch linux here but it had the latest build in the AUR repositories. It was actually really easy to install and use!

I confirm that the latest nightly works as expected for me. The query parameters survive a redirect to the IPFS gateway!
Thank you for taking care!

**Comment by stephendonner** [comment]
Thanks again for confirming @markg85; keep the bugs coming! 🙏
