### ISSUE TITLE
BR panel message is not translated to Japanese for connected publisher DDG

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#18373]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18153
BR panel message is not translated to Japanese for connected publisher DDG

## Steps to Reproduce

   1. Set OS locale to Japan
   2. Clean profile 1.32.20
   3. Enable rewards and connect KYC'd bitflyer account
   4. Open https://github.com/dlipeles
   5. Mouse hover on publisher indicator status
   6. Message is not translated to Japanese

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/134913797-0217ac33-8b44-40c2-8fab-831d9a2fdd17.png)

## Expected result:

Should be translated to Japanese
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave	1.32.20 Chromium: 94.0.4606.54 (Official Build) nightly （64 ビット）
変更履歴	c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS	Windows 10 Version 1809 (Build 17763.1637)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @zenparsing @szilardszaloki

**Comment by GeetaSarvadnya** [comment]
cc: @Miyayes

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/10559 landed into `master` and is being uplifted via Updated l10n for 1.31.x release (1.32.x). #10578 - https://github.com/brave/brave-core/pull/10578 & https://github.com/brave/brave-core/pull/10579.
