### ISSUE TITLE
Use mojo method to retrieve a link to buy assets

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#18377]
Currently we hardcode the link in ts https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/utils/buy-asset-url.ts#L9. We should use a new mojo method to retrieve the link `GetBuyUrl(string address, string symbol, string amount) => (string url);` inside `ERCTokenRegistry`

**Comment by bbondy** [comment]
cc @Douglashdaniel
