### ISSUE TITLE
Connected publisher message is shown incorrectly when Bitflyer account is connected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#18376]
## Description 

Found while testing #18153
Connected publisher message is shown incorrectly when Bitflyer account is connected

## Steps to Reproduce

   1. Set OS locale to Japanese
   2. Clean profile 1.32.20
   3. Enable rewards and connect KYC'd bitflyer account
   4. Open duckduckgo.com
   5. Open tipping banner
   
message is displayed as `注意: このクリエイターは現在、あなたのウォレットからチップを受け取る設定が完了していません。あなたが作成したチップは、あなたのウォレットに保留されたまま90日間自動的に再試行されます。 詳細を見る` 

equivalent message in English

`Note: This creator is not currently set up to receive chips from your wallet. Chips you create will be automatically retried for 90 days while being held in your wallet. view the details`

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/134934400-d14d6066-c2bf-4ff1-97d1-f5bcbbbc2d37.png)

## Expected result:

The message should be displayed as in the BR panel "This creator is currently not configured to receive tips from your wallet. Any tip you make will remain pending in your wallet and retry automatically for 90 days. Learn more."
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave	1.32.20 Chromium: 94.0.4606.54 (Official Build) nightly （64 ビット）
変更履歴	c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS	Windows 10 Version 1809 (Build 17763.1637)
## Version/Channel Information:

- Can you reproduce this issue with the current release? No, RC has different message `Note: This Brave Authorized Creator has not completed account setup to receive assistance from Brave users. Brave will try to assist you until your account is set up or 90 days have passed. view the details`
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @zenparsing @szilardszaloki

**Comment by LaurenWags** [comment]
cc @Miyayes to review and determine if this should be uplifted to 1.31.x

**Comment by Miyayes** [comment]
@GeetaSarvadnya, sorry maybe I'm misunderstanding:

It looks like the **Expected** and **Actual** results are the same in your report? Wouldn't that be correct?

**Comment by Miyayes** [comment]
@GeetaSarvadnya said the issue was seeing `Chips` instead of `Tips` in the translation. This should be correct. In Japanese, there is no "Ti" sound, so it is replaced with "Chi". When it is translated back into English via Google Translate, it comes back as "Chips" instead of "Tips". But the actual Japanese should be correct.

Only remaining thing is to replace the English text in the Rewards dropdown panel with its Japanese text. 

![image](https://user-images.githubusercontent.com/11497541/134954975-1a72ba1d-e456-43c7-adc0-4e3e3f4ab0ad.png)

**Comment by GeetaSarvadnya** [comment]
@Miyayes Thanks for the clarification. For BR panel message translation, a separate issue is logged https://github.com/brave/brave-browser/issues/18373.  Hence closing this issue.
