### ISSUE TITLE
Unverified pubs tipping banner message isn't translated to Japanese locale

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#18374]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18153
Unverified pubs tipping banner message isn't translated to Japanese locale
## Steps to Reproduce

   1. Set OS locale to Japanese
   2. Clean profile 1.32.20
   3. Enable rewards and connect KYC'd bitflyer account
   4. Open any unverified pubs (e.g CNN.COM)
   5. Open tipping banner, unverified pubs tipping banner message isn't translated to Japanese

## Actual result:

Unverified pubs tipping banner message isn't translated in Japanese

![image](https://user-images.githubusercontent.com/38657976/134932243-ead881a3-44c7-4101-8a5a-1457f0557e03.png)

## Expected result:
message should be translated to Japanese locale

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave	1.32.20 Chromium: 94.0.4606.54 (Official Build) nightly （64 ビット）
変更履歴	c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS	Windows 10 Version 1809 (Build 17763.1637)
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA 
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @zenparsing @szilardszaloki

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/10559 landed into `master` and is being uplifted via Updated l10n for 1.31.x release (1.32.x). #10578 - https://github.com/brave/brave-core/pull/10578 & https://github.com/brave/brave-core/pull/10579.
