### ISSUE TITLE
Do not allow Deprecated Crypto Wallet Extensions to be set as default when it has never been installed before

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18375]
## Description 

Do not allow Deprecated Crypto Wallet Extensions to be set as default

## Steps to Reproduce

   1. Clean nightly profile
   2. Enable Brave Native wallet flag
   3. Go to `brave://settings/wallet`, ensure `Deprecated Crypto Wallet extension` is not available as default provider

## Actual result:

CW Extension is listed as default provider for clean profiles

## Expected result:
Do not allow Deprecated Crypto Wallet Extensions to be set as default

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.20 Chromium: 94.0.4606.54 (Official Build) nightly (64-bit)
-- | --
Revision | `c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @bbondy @Douglashdaniel

**Comment by bbondy** [comment]
** When it has never been installed before

**Comment by bbondy** [comment]
Here's the expected behavior: 
if the user already has used crypto wallets we will still show it in settings
if the user has never used it we won’t show it in settings unless that chrome://flags flag is on

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10855>/brave/brave-core#10855</a></li>
         <li>Verified deprecated wallet option doesn't show up on clean install</li>
         <li>Verified deprecated wallet option shows when flag is enabled on clean install</li>
         <li>Verified deprecated wallet option shows when wallet is already enabled on previous version and then upgraded to 1.32.x</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Clean Install
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140911104-f5a3aed8-5924-4d67-8069-1303285a2abc.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140909793-f95a7a95-ab1e-42c1-bf4f-6425ad150a22.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140906093-e6f7c8ec-c92c-40d5-ab55-8ba9dcddb5e2.png>
      </td>
   </tr>

   <tr>
      <td>Flag enabled
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140911173-778c740b-3918-425a-961a-383d117a4eee.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140909930-9806b0e2-9e1b-4d69-9fce-9e4dea48df8f.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140906184-b52e8623-2fed-4e57-adda-97d9da451bc0.png>
      </td>
   </tr>
   <tr>
      <td>Option Enabled after flag is enabled
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140911345-d86a8c7b-ba9d-466b-b2dd-f12a00d71166.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140910014-77de128d-4e83-4b19-8dd2-80d2736d74dd.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140906253-028dddb7-a9c4-4f88-8add-44a9df7f1582.png>
      </td>
   </tr>
   <tr>
      <td>Option listed upon upgrade
      </td>
      <td><img src=
![image](https://user-images.githubusercontent.com/17010094/140910975-eaa58695-e5d7-4257-8a95-670a9f24985c.png)
>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140909565-6ec911ad-bf6f-4e26-b0e5-0a1ca66cee23.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140908207-ec46607d-8818-4443-b5d5-5b393fb6eaed.png>
      </td>
   </tr>
</table>
