### ISSUE TITLE
Missing BRAVEREWARDSCREATINGTEXT string on Rewards Panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1838]
## Steps to Reproduce

1. Clean install 
2. Open Rewards Panel
3. Click Join Rewards
4. Observe the Join Rewards Button to be transformed into Waiter message (https://github.com/brave/brave-browser/issues/1502)

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/47511322-3d3fc800-d87a-11e8-9fc4-9c1fa75eb9fd.png)

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.56.6 Chromium: 70.0.3538.67 (Official Build) beta (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

### Reproducible on current release:
No
There is no waiter message in Rewards Panel on Release build.

@srirambv @GeetaSarvadnya @kjozwiak @LaurenWags @NejcZdovc @ryanml

**Comment by bbondy** [comment]
Transifex was moved to C71 strings and we can't maintain multiple transifex's.  So you'll have to work around that in some way @NejcZdovc

**Comment by bbondy** [comment]
0.56.x must remain on C70.

**Comment by NejcZdovc** [comment]
ok will just copy en string to all files. wdyt? @bbondy

**Comment by srirambv** [comment]
Issue doesnt seem to be fixed.

![1838](https://user-images.githubusercontent.com/17010094/47595821-31bed080-d950-11e8-9c20-936f75d07ff1.gif)

**Comment by NejcZdovc** [comment]
cc @bbondy for help

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta(64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

![screen shot 2018-10-31 at 4 47 54 pm](https://user-images.githubusercontent.com/28145373/47817722-cc425980-dd2c-11e8-9424-dcb533ab9777.png)
