### ISSUE TITLE
promoCode file is not generated when stub installer file has (1) suffix

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1839]
## Steps to Reproduce

The suffix is generated when downloading the same file twice.
```
Firefox: BraveBrowserSetup-KAM253(1).exe
Chrome: BraveBrowserSetup-KAM253 (1).exe
```

1. (Important) Uninstall Brave Browser with User Data to have a Clean install
![image](https://user-images.githubusercontent.com/34715963/47382336-5e7da880-d702-11e8-9de3-68cf7495a568.png)
2. (On Windows )Rename the stub installer to `BraveBrowserSetup-KAM253(1).exe`
3. Run the stub/mini installer
4.  (On Windows )Check if `promoCode` file is generated in `[user]\AppData\Local\BraveSoftware\Brave-Browser\User Data\`  
OR check `Local State` file for `promo_code`

Alternate file names to check:
```
BraveBrowserSetup-dowjones-marketwatch (1).exe
BraveBrowserSetup-dowjones-marketwatch(1).exe
BraveBrowserSetup-dowjones-barrons (1).exe
BraveBrowserSetup-dowjones-barrons(1).exe
BraveBrowserSetup-KAM253(1).exe
BraveBrowserSetup-KAM253 (1).exe
BraveBrowserSetup-KAM253(2).exe
BraveBrowserSetup-KAM253 (2).exe
```

## Actual result:

promoCode is not generated

## Expected result:
promoCode is generated

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

@kjozwiak Can you check on Mac?
cc @srirambv @LaurenWags @GeetaSarvadnya @emerick @NejcZdovc @bbondy

**Comment by emerick** [comment]
Yes, I can confirm that we're lacking handling for this on the Windows side.

**Comment by btlechowski** [comment]
Since we are concerned about referral promo, maybe this issue should be uplifted? @rebron @kjozwiak @bbondy

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 10

- Verified below scenarios, sent downloaded id's to @aekeus to confirm whether promo code are finalized
![image](https://user-images.githubusercontent.com/38657976/52794339-a51e5680-3095-11e9-957d-4833087eb725.png)
- Verified that promocode file got created
- Verified that Download id shown in Local state file
- Verified that barrons and market watch tabs opened automatically after brave launched
