### ISSUE TITLE
Implement P3A RewardsEnabledDuration

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#18394]
Add a new P3A key to record how long Brave Rewards had been enabled when they're disabled.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.36.86 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1503)

```

**Comment by GeetaSarvadnya** [comment]
@rillian  - Followed the test plan from https://github.com/brave/brave-core/pull/11147, unable to get the reports for `2`, `3`, `4` , `5` and `6`. Currently report `0` and `1` are working fine. Could you please look into this again?

**Comment by rillian** [comment]
Hrm. I'll see if I can reproduce. We do have some reports on the stats dashboard for values above one, so it's working intermittently, at least.

**Comment by rillian** [comment]
I got a `2` after setting the vm clock forward a month, which should have been a `5`. Hopefully it's just hard to pick up the correct clock.

**Comment by Miyayes** [comment]
@rillian I have a question: What does it mean to "Disable Brave Rewards"? Does that mean "Disable Brave Ads", for example? Ever since an initiative called Brave Rewards Everywhere (BRE), the master toggle for Brave Rewards in brave://rewards settings page was removed. So, there's no super clear sense in which Brave Rewards can be enabled or disabled in our post-BRE world. Thanks.

**Comment by GeetaSarvadnya** [comment]
QA Blocked until the issue https://github.com/brave/brave-browser/issues/21017 is fixed

**Comment by GeetaSarvadnya** [comment]
As discussed with @rillian in the P3A meeting, removing the milestone and QA blocked label from the issue. The follow-up issue is logged to address the issue https://github.com/brave/brave-browser/issues/21017
