### ISSUE TITLE
Add a dark theme for dev-channel

### ISSUE THREAD

**Issue by Sa-Ja-Di** [brave/brave-browser#184]
As there are also many people around with some eye issues, a dark UI would help such people quite a lot.

That suggestion was also made on the Brave old repository, perhaps this idea can built inside the newly planned Brave, based on real Chromium?

**Comment by h3298** [comment]
**Developers, please reference the following comment which offers a potential solution:**

https://github.com/brave/browser-laptop/issues/271#issuecomment-410486507

**Comment by bbondy** [comment]
Option will be added but that's the default for dev channel only.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
