### ISSUE TITLE
Hide UI elements related to IdleDetection

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#18409]
Following up from https://github.com/brave/brave-browser/issues/18269#issuecomment-929221220, Brave currently disables the Idle Detection API, but doesn't remove the UI elements / settings around it, causing confusion.

To prevent confusion, we should just hide the UI elements related to the Idle Detection API

**Comment by mkarolin** [comment]
QA verification steps (Desktop):

1. Start Brave and navigate to any site (e.g. cnn.com)
2. Navigate to brave://settings → "Privacy and security" → "Site and Shields Settings"
3. Under "Permissions" section, click on "Additional permissions"
4. Verify that "Your device use" item is not present
5. Scroll back to the top of the page and click on "View permissions and data stored across sites"
6. Pick the site you visited in step 1 and click to expand
7. Click on the site
8. Verify that "Your device use" item is not present
9. Navigate to brave://settings/content/idleDetection
10. Verify that the page is empty.

Verify that the UI is not hidden when the feature is enabled:
1. Start Brave from the command line with `--enable-features=IdleDetection`
2. Repeat steps above, expect the reverse in the Verify steps.

**Comment by mkarolin** [comment]
Split out Android into a separate issue: https://github.com/brave/brave-browser/issues/18414

**Comment by kjozwiak** [comment]
Going to change this from `release-note/exclude` --> `release-notes/include` as we're removing UI elements. @rebron @LaurenWags if you feel differently, please feel free to change it back 👍
