### ISSUE TITLE
Incorrect password when trying to migrate from old CW to Brave Wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18405]
## Description 

As per https://github.com/brave/brave-core/pull/10161, entering old CW password should allow for successful import of old wallet to new but that flow fails even when you enter correct password

## Steps to Reproduce

1. Setup Crypto Wallet and remember the password and mnemonic 
2. Enable `brave://flags/#native-brave-wallet`
3. Navigate to brave://wallet/
4. Click "Get Started" on onboarding page
5. There will be "Existing Crypto Wallets detected" page
6. Try input different password from step 1 and click Import
7. There will be error message
8. Input correct password from step 1 and click Import
9. The wallet will be setup using same password in step 1  
10. Check the mnemonic is same as step 1
11. Check brave://extensions/ and there is not crypto wallet extension loaded

## Actual result:

https://user-images.githubusercontent.com/17010094/135073282-73c005b7-0903-4ec7-93ee-0e4549023116.mov

## Expected result:
Should allow successful import

## Brave version (brave://version info)

Brave | 1.32.25 Chromium: 94.0.4606.54 (Official Build) nightly (64-bit)
-- | --
Revision | `418b78f5838ed0b1c9bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @darkdh

**Comment by darkdh** [comment]
Fixed by https://github.com/brave/brave-core/pull/10298
