### ISSUE TITLE
Crash reporting prompt on release channel

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1841]
## Description

In dev and beta, crash reporting is on by default and folks can turn it off if they really want to. On release channel, we should ask folks if they want to send us reports. They're probably most likely to be in the right headspace for that question right after the browser has crashed — there's a motivation to send the report to prevent this specific crash from happening in future releases.

After a crash, when the browser restarts, we should ask whether to send crash reports. The possible answers should be always/yes/no/never or ideas to that effect.

## Design
Show a user-blocking modal requesting permission to automatically send crash reports when the app re-opens after a crash. This dialog should take precendence over any other user-blocking dialog (e.g. the 'set Brave as default browser' dialog that occurs on 2nd launch).

![image](https://user-images.githubusercontent.com/2388823/109708056-bdb01b00-7b4f-11eb-9691-8532061a5088.png)

"This setting" links to the crash reports item in `brave://settings`

## Assets
Figma: https://www.figma.com/file/pVwKlNQJU9wTVOa9tImKpo/Browser-Dialogs?node-id=36%3A810

**Comment by srirambv** [comment]
Crash reporting is not enabled by default on Dev and Beta. #1630 is logged to enable it since we mention its enabled on the download page

cc: @rebron

**Comment by rebron** [comment]
Note to take a look at info bar and using onboarding to set crash reporting pref.

**Comment by iefremov** [comment]
We may also try to be a bit more proactive - e.g. suggest sending a crashdump after an actual crash. Or anything like this to encourage existing auditory to toggle the switch.

**Comment by iefremov** [comment]
P3A metric proved that almost nobody enables crash reporting on release channel. We definitely should raise the priority of this to start getting some real data from stable clients.

**Comment by karenkliu** [comment]
@rebron WDYT about this crash reports dialog text?

**Comment by rebron** [comment]
@karenkliu If we go modal here and show this crash prompt modal first, there's a restore tabs dialog that also shows up so we'd have back to back notifications. Infobar as an option or ok with this back to back prompts in this order.

**Comment by karenkliu** [comment]
@rebron Fine with crash reports dialog first then restore tabs prompt. The crash reports dialog is user-blocking while the restore tabs prompt isn't.

**Comment by simonhong** [comment]
@rebron This new dialog should be visible before restore pages dialog?

**Comment by simonhong** [comment]
Working on this.
@rebron @karenkliu , With current dialog design, we give two options, block or allow.
If user selects block, we will not show this dialog again for the future crash?

**Comment by karenkliu** [comment]
@simonhong If user selects block, we still show the dialog again after future crash(es).

**Comment by stephendonner** [comment]
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/9508 with build 


Brave | 1.29.45 Chromium: 92.0.4515.115 (Official Build) nightly (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 12.0 (Build 21A5294g)

Steps:

1. new profile
2. launched Brave and opened several tabs
3. checked and confirmed crash reporting is not enabled on `brave://settings/privacy`
4. loaded `brave://inducebrowsercrashforrealz` to simulate browser crash
5. restarted Brave
6. confirmed crash reporting permission ask dialog was launched
7. confirmed clicking on `this settings` opens `brave://settings/privacy` in the background (still a modal window displayed)
8.  clicked `Block` and confirmed tab-restore bubble was displayed
9. clicked `Allow` and confirmed the tab-restore bubble was displayed
10. confirmed crash reporting is now enabled from `brave://settings/privacy`

default crash-reporting pref (disabled) | crash reporting permission dialog | `this setting` | `Block` step | `Allow` step | crash-reporting pref enabled
------------|-----------------------------------|--------------|--------------|------------------------------|--------------
<img width="1312" alt="Screen Shot 2021-08-02 at 2 36 54 PM" src="https://user-images.githubusercontent.com/387249/127928197-26108ec8-c4db-44c7-a3f8-ee0d4942951c.png"> | <img width="1312" alt="Screen Shot 2021-08-02 at 2 36 39 PM" src="https://user-images.githubusercontent.com/387249/127928266-1fd9b774-dd8e-4bba-90f6-1aacc869665d.png"> | <img width="1312" alt="Screen Shot 2021-08-02 at 2 51 45 PM" src="https://user-images.githubusercontent.com/387249/127928577-2ea8b41c-f296-4a7b-8c92-5592cb3e0333.png"> | <img width="1312" alt="Screen Shot 2021-08-02 at 2 36 54 PM" src="https://user-images.githubusercontent.com/387249/127928302-efbe7552-e5d5-4e02-bf29-d58ba2360189.png"> | <img width="1312" alt="Screen Shot 2021-08-02 at 2 37 24 PM" src="https://user-images.githubusercontent.com/387249/127928303-429fe2cc-1f68-452c-8db1-65a672515fdf.png"> | <img width="1312" alt="Screen Shot 2021-08-02 at 2 37 33 PM" src="https://user-images.githubusercontent.com/387249/127928413-1a495978-c7ca-49f4-9560-38c1ac33a422.png">

Also checked the `Light` theme

<img width="1312" alt="Screen Shot 2021-08-02 at 2 36 19 PM" src="https://user-images.githubusercontent.com/387249/127928815-25e7eeb9-264b-4602-a8c6-c93ba605db1e.png">

**Comment by stephendonner** [comment]
Casting `QA/Test-All-Platforms` label because it'd be great to have eyeballs across platforms, here, given the importance of the data.
