### ISSUE TITLE
Support using environment variables to adjust referral checks

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#1842]
QA requested supporting environment variables to adjust some of the referral checks that we make. In particular, we should add support for the following enviornment variables:

`BRAVE_REFERRALS_DELETE_TIME` - Number of seconds after which to delete the referral code (default is 90 days)
`BRAVE_REFERRALS_CHECK_TIME` - Number of seconds to continue checking for referrals (default is 30 days)

**Comment by emerick** [comment]
cc: @kjozwiak @srirambv

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.14 x64` - **PASSED**

Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* launch brave via `BRAVE_REFERRALS_SERVER=laptop-updates-staging.herokuapp.com` (make sure you're using a referral code that's on stating and NOT production)
* wait 10min (this is what the staging server is set too) or you'll receive `Referral is not ready, please wait at least 30 days` if you do the below steps without waiting 10min
* after waiting 10min, relaunch using `BRAVE_REFERRALS_SERVER=laptop-updates-staging.herokuapp.com BRAVE_REFERRALS_CHECK_TIME=5`
* you should see a `timestamp` being created next to the `promo_code`, example: `"promo_code":"MIM486","timestamp":"13186203834926030"`
