### ISSUE TITLE
Browser crash when trying to enable VPN after doing a reset configuration

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18423]
## Description 
Browser crash when trying to enable VPN after doing a reset configuration

## Steps to reproduce 

   1. Install 1.32.30 and enable VPN
   2. Install config and ensure VPN is enabled
   3. Go to Settings -> VPN -> Reset configuration
   4. Click on Enable VPN button app crashes

## Actual result 
Browser crash when trying to enable VPN after doing a reset configuration

## Expected result
No crash just enable VPN

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.32.30 x64 Nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Maybe related to #18270

**Comment by deeppandya** [comment]
@srirambv can you verify and close this issue ? it should be fixed

**Comment by srirambv** [comment]
Verified on latest master and there is no crash when re-enabling VPN. Closing the issue as invalid
