### ISSUE TITLE
Remove Griffin flag for Brave Talk

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#18426]
## Test plan
1. Remove `BraveTalk` study for the channel in question (staging)
2. Launch Brave (fresh profile) pointing at staging (I think you can use `--variations-server-url=https://variations.bravesoftware.com/seed`)
3. You should see the `Brave Talk` promo (bottom right)
4. If you click Edit Cards you should be able to add `Brave Talk`

## Description 
Brave Talk has a card available on New Tab Page and also a promo flyout that shows. This was put behind a flag with https://github.com/brave/brave-core/pull/9605

We can remove this config now that it's live. After that is done and fix makes its way to release channel, we can remove study (tracked with https://github.com/brave/brave-variations/issues/133)

**Comment by stephendonner** [comment]
@bsclifton @rebron @kjozwiak are we going to uplift this into `1.31.x`, or will it ride the trains to `1.32.x`?  I verified it on https://github.com/brave/brave-core/pull/10311#issuecomment-936885365.
