### ISSUE TITLE
Unable to turn brave reward ads option back on

### ISSUE THREAD

**Issue by KavyanshJain** [brave/brave-browser#18432]
Around a week ago I mistakenly turn off ads option in the brave rewards settings and then I tried to turn it on back.

![image](https://user-images.githubusercontent.com/69588134/135286630-0d15ad32-c900-4cf5-b456-cb0f5eace3ab.png)

## Actual result:
When I try to turn it on it off again and grey out

![Rewards - Brave 2021-09-27 21-53-21](https://user-images.githubusercontent.com/69588134/135287329-02c1ee5f-7768-48c0-91be-e11e730d9c9b.gif)

## Expected result:
The option should be turn on back as we tap on it 

## Brave version and OS
1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)
Windows 11 Dev build

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- > yes
- Can you reproduce this issue with the beta channel? 
- > don't know
- Can you reproduce this issue with the nightly channel? 
- > don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
If you want me to recommend update to latest version it is already to the latest one and I have tried to close and open browser multiple time and tried to turn it on.

Please help me

**Comment by KavyanshJain** [comment]
@rebron can you please tell any solution of it or any progress of this.

**Comment by Miyayes** [comment]
Hi @KavyanshJain, can you help provide some additional information:

1. Was Brave Ads working in the past when you were on Windows 11? Or did you upgrade to Windows 11 last week?
2. Do you have an Uphold or Gemini account?
3. Did you reset/refresh Windows or change your Windows password in the past week?

Thanks.

**Comment by KavyanshJain** [comment]
> Hi @KavyanshJain, can you help provide some additional information:
> 
> 1. Was Brave Ads working in the past when you were on Windows 11? Or did you upgrade to Windows 11 last week?
> 2. Do you have an Uphold or Gemini account?
> 3. Did you reset/refresh Windows or change your Windows password in the past week?
> 
> Thanks.

Answers -

1) I started using brave after upgrading to win 11, everything works nice and smooth on it and I have updated my pc to win 11 from the day it was released to dev channel for the first time.

2) No I not have any of the above account and also not connect my brave wallet to any of this.

3) No, I have not done any changes to my system settings.

Thanks to reply

**Comment by tmancey** [comment]
@KavyanshJain I work on the ads team here at Brave, could you please email tmancey@brave.com with a screenshot of brave://rewards-internals so that I can investigate. Thank you

**Comment by KavyanshJain** [comment]
> @KavyanshJain I work on the ads team here at Brave, could you please email [tmancey@brave.com](mailto:tmancey@brave.com) with a screenshot of brave://rewards-internals so that I can investigate. Thank you

Thanks to reply I will send you mail of it

**Comment by tmancey** [comment]
@Miyayes this user has a corrupt wallet.

**Comment by KavyanshJain** [comment]
> @Miyayes this user has a corrupt wallet.

What is that how does it corrupt. Any solution or problem from my side @tmancey

**Comment by KavyanshJain** [comment]
> @KavyanshJain We are working on a fix for this that will land in a hotfix of v1.31.x, or v1.32.x. It will generate a new Rewards wallet for you that is not corrupted (without deleting your BAT).

That's sound great and thanks

**Comment by KavyanshJain** [comment]
Hey Just get the update of 1.32 version and the issue is solved and everything working properly
**Thanks @Miyayes @tmancey**
