### ISSUE TITLE
[Android] Implement bitFlyer Rewards user wallets 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18439]
## Description

Android version of https://github.com/brave/brave-browser/issues/14591.

**Comment by emerick** [comment]
Going to close this out as this work is now complete.

**Comment by LaurenWags** [comment]
Verification in progress with Google Pixel 3 XL with Android 12 running various 1.35.x versions.
* Verification notes can be found under https://github.com/brave/internal/issues/838#issuecomment-999633411 and https://github.com/brave/internal/issues/838#issuecomment-1015901673
* Various follow up issues were logged and noted with https://github.com/brave/internal/issues/838#issuecomment-999633411
