### ISSUE TITLE
Disable reset report uploader

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#1844]
Settings → Advanced → "Restore settings to their original defaults" brings up a psuedo-dialog that says "This will reset your startup page, new tab page, search engine, and pinned tabs. It will also disable all extensions and clear temporary data like cookies. Your bookmarks, history and saved passwords will not be cleared. Learn more"

The "learn more" link points to a Brave support page (good), but under the text is a checkbox (selected by default) "Help make Brave better by reporting the current settings". If checked, selecting the "Reset settings" button will send a report to a Google-owned server.

Relevant code: https://cs.chromium.org/chromium/src/chrome/browser/profile_resetter/reset_report_uploader.cc

According to @bbondy, we should

 - keep the "reset settings" functionality, but
 - unconditionally disable uploading of current settings
 - hide the UI (checkbox) that offers the choice of uploading

**Comment by srirambv** [comment]
@pilgrim-brave can you add `QA/Yes`/`QA/No` label and any test steps in the issue/PR accordingly?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

![screenshot from 2018-12-12 16-14-24](https://user-images.githubusercontent.com/17010094/49864696-10934000-fe29-11e8-9a5c-0e94dfbd1a57.png)
