### ISSUE TITLE
Remove DST Root CA X3 from list of pinned CA certs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#18440]
Let's Encrypt's DST Root CA X3 is expiring on 2021-09-30. We should remove it from our pinned set:
https://github.com/brave/brave-core/blob/51257a3bbde971f98c34cfb8e83aedd6404b141b/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc#L280-L300

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.65.88 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	e260e641e7db9e88b9b51112f4f00febf5a2f5eb
OS	macOS Version 11.7.10 (Build 20G1427)
```

## No `TLS` errors

https://go-updater.brave.com/
https://p3a.brave.com/
https://variations.brave.com/
https://creators.brave.com/
https://mainnet-polygon.brave.com/
https://anonymous.ads.brave.com/
https://search.brave.com/
https://account.brave.com/

## `NET::ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN` error
https://ssl-pinning.someblog.org/

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.65.93 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | a6eee503125f9441360861f96cfdcccf43b6fee0
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

1. Installed 1.64.93
2. launched Brave
3. opened the following websites, as per the testplan in https://github.com/brave/brave-core/pull/22540#issue-2180415488
4. Confirmed appropriate sites didn't have TLS errors, and the last site in the test plan returned its appropriate error, as noted below


`https://go-updater.brave.com/`|`https://p3a.brave.com/`| `https://variations.brave.com/` | `https://creators.brave.com/`
-------------- | ------------ | ------------- | -----------------
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/578899fd-5ec2-45c5-8854-90b837d6946a">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/43e956b2-1478-4961-9b92-ff652346a39c">| <img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8a8baa7a-05bd-41da-8b93-4177dc5ad8f7">| <img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e4358238-ceda-4383-b54b-064088c3811b">


`https://mainnet-polygon.brave.com/` | `https://anonymous.ads.brave.com/` | `https://search.brave.com/` | `https://account.brave.com/`
 -------------- | ---------- | ------------- | ----------------
![image](https://github.com/brave/brave-browser/assets/98358127/71fcd78e-f3b3-4672-afd9-7a05738e4cee)|![image](https://github.com/brave/brave-browser/assets/98358127/db6d224f-8f2e-4b94-95df-fcd91838e348)|![image](https://github.com/brave/brave-browser/assets/98358127/77389ac2-1858-406f-a2c2-e5c9d2be6da0)|![image](https://github.com/brave/brave-browser/assets/98358127/183685d2-37a3-481d-a73f-e778a7892acb)


- Open https://ssl-pinning.someblog.org/

Confirm that this one returns a NET::ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN TLS error:

![image](https://github.com/brave/brave-browser/assets/98358127/410df8c3-d96c-47c5-b714-725360d09689)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Linux
```

**Comment by hffvld** [comment]
## IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240305.005 release-keys
Brave build: 1.65.101
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```

Filed follow-up issue #
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22540#issue-2180415488
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `TLS` error is not shown when opening any of these: `https://go-updater.brave.com/`, `https://p3a.brave.com/`, `https://variations.brave.com/`, `https://creators.brave.com/`, `https://mainnet-polygon.brave.com/`, `https://anonymous.ads.brave.com/`, `https://search.brave.com/`, `https://account.brave.com/`
- Verify that the `TLS` error must be shown when accessing `https://ssl-pinning.someblog.org/`. Observed that `TLS` error is not shown actually.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |

**Comment by fmarier** [comment]
The verification failure on Android (https://github.com/brave/brave-browser/issues/37322) can be ignored since this feature is not actually enabled on Android yet: https://github.com/brave/brave-browser/issues/24453
