### ISSUE TITLE
Add sending email for VPN support from VPN settings panel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18469]
## Description 
VPN users need a way to contact us for support issues. We should match the current designs for mobile with an email form 
To: brave at guardianapp.com 
From: user, prefilled
Subject: Brave Firewall + VPN Issue

Users should be able to select from the following options:
- Cannot connect to the VPN (Other error)
- No internet when connected
- Slow connection
- Website doesn't work
- Other

## Design [Placeholder]
Help needed specifically with how the options should look! 😄 

We can wire up here:
![image](https://user-images.githubusercontent.com/4733304/153091302-5ab3ed7e-1c2b-4c29-a104-9b006b96de5c.png)

**Comment by jenn-rhim** [comment]
@aguscruiz ^

**Comment by aguscruiz** [comment]
@rebron are we using a mailto link after the user selects the subject? Or can we add something more complex like an inline form on the popup itself?

I'm thinking something like this, if we can:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/15734630/155575773-4899e34b-7975-4540-b37c-1013130ed24a.png">

**Comment by bsclifton** [comment]
Updated picture from Figma 😄 
![image](https://user-images.githubusercontent.com/4733304/156427329-4941b203-813b-4994-8ffe-d4bac648ffc0.png)

Thanks @aguscruiz!

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.39.84` on Windows 10

### Confirmed successful VPN sign-in, log-in, and technical-support form submission.

### Steps:
   1. install `1.39.84`
   2. launch Brave using `--vmodule="*/skus/*"=1 --enable-logging=stderr`
   3. via `brave://flags`, set `Enable experimental SKU SDK` to `Enabled`
   4. set `Experimental SKU Environment` to `Development`
   5. also set `Brave Experimental VPN` to `Enabled`
   6. click to `Relaunch`
   7. load `account.brave.software`
   8. enter basic auth creds for site
   9. enter an email and click `Get login link`
   10. check your email inbox
   11. click `Log in to Brave` or the link in the email
   12. click on `Browse plans`
   13. scroll down and click on `Buy now` for `Brave VPN Subscription`
   14. enter payment details on `https://checkout.stripe.com/pay/cs_test…`
   15. click `Subscribe`
   16. you should get a `Complete your purchase...` screen
   17. click on `Complete payment`
   18. click on the VPN icon
   19. click on `Settings`
   20. click on `Contact technical support`
   21. fill out the form
   22. click `Submit`

Submitted | Received From Guardian
-----------|-------------------------
![15804-windows-7](https://user-images.githubusercontent.com/387249/165867547-0b9a5d8b-1dea-4053-ac19-47d45893b04a.png) | <img width="592" alt="Screen Shot 2022-04-28 at 5 16 32 PM" src="https://user-images.githubusercontent.com/387249/165867459-56014534-7db0-49f0-be96-da5f0df99745.png">



(They are looking at the hostname showing city, as a bug.)

**Comment by stephendonner** [comment]
Verified `PASSED` using 



Brave | 1.39.108 Chromium: 101.0.4951.67 (Official Build) beta (x86_64)
-- | --
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | macOS Version 12.5 (Build 21G5027d)



Followed my original steps to reproduce, and cross-confirmed again with Guardian that they received my 3 test submissions: https://bravesoftware.slack.com/archives/C0141L60REG/p1653176119435419.

<img width="1312" alt="Screen Shot 2022-05-21 at 4 32 16 PM" src="https://user-images.githubusercontent.com/387249/169672448-8a133b48-70ea-470f-a352-bc3aad6260eb.png">

**Comment by stephendonner** [comment]
Logged:
* https://github.com/brave/brave-browser/issues/22731
* https://github.com/brave/brave-browser/issues/22628
