### ISSUE TITLE
Remove swap arrow from send

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#18465]
Down arrow is not needed on send
<img width="281" alt="Screen Shot 2021-09-29 at 9 35 47 PM" src="https://user-images.githubusercontent.com/318119/135376677-8ff6dbe1-93dc-45be-82fa-f0be39053380.png">

**Comment by SergeyZhukovsky** [comment]
it's done in the context of that https://github.com/brave/brave-core/pull/10357/files

**Comment by LaurenWags** [comment]
@jamesmudgett @SergeyZhukovsky does this need manual QA? If so, please add `QA/Yes` and a test plan. If not, please mark `QA/No`. Thanks!
