### ISSUE TITLE
Network dropdown naming format

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#18464]
Name should formatting should be copied from desktop wallet. 

Example:

Ethereum Mainnet

Displays: "Ethereum" on button.
Displays: "Ethereum Mainnet" in dropdown.

iOS Example:
<img width="287" alt="Screen Shot 2021-09-29 at 9 34 48 PM" src="https://user-images.githubusercontent.com/318119/135376501-a9dde2ea-a729-479d-8de4-e1e3d63d5190.png">

**Comment by SergeyZhukovsky** [comment]
it's done in the context of that https://github.com/brave/brave-core/pull/10320
