### ISSUE TITLE
Asset detail graph

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#18461]
Min and max of time-range data should be spread across vertical height of container graph to not appear flat.

Current
![Screenshot_20210921-110452](https://user-images.githubusercontent.com/318119/135375584-f64a63f0-6e32-4e5c-b549-c3b016571f34.png)

Desired graph range
![portfolio-active-backup-reminder](https://user-images.githubusercontent.com/318119/135375622-5e9295c5-39ab-4693-a1e5-6e8c4f18eecc.png)

**Comment by SergeyZhukovsky** [comment]
it's done in the context of that https://github.com/brave/brave-core/pull/10352

**Comment by LaurenWags** [comment]
@jamesmudgett @SergeyZhukovsky does this need manual QA? If so, please add `QA/Yes` and a test plan. If not, please mark `QA/No`. Thanks!
