### ISSUE TITLE
show VPN subscription information in VPN panel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18467]
## Description 

Add Subscription Status, Expiration date and a link to `Manage Subscription` as a pointer to account.brave.com in the VPN settings panel.

Current design:
<img width="319" alt="Screen Shot 2021-09-30 at 12 19 26 AM" src="https://user-images.githubusercontent.com/5951041/135409695-96464e4b-de01-4044-937a-6bc8809c3a1c.png">

This should match mobile.  
<img width="370" alt="Screen Shot 2021-09-30 at 12 14 16 AM (1)" src="https://user-images.githubusercontent.com/5951041/135410991-637f5d80-48b0-4b80-9006-d28c49577fa1.png">

## Design
![image](https://user-images.githubusercontent.com/2388823/135935463-65b2e1f8-6bde-4d70-a942-f4a1954acb16.png)

## Brave version (brave://version info)
n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Figma link: https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/Desktop-VPN?node-id=28%3A12100

**Comment by nullhook** [comment]
as discussed with @bsclifton i don't think we'll show this info and keeping it simple for now

**Comment by mattmcalister** [comment]
Closing. As with mobile, keep sub status and dates for desktop purchases exclusively with account site for now.
