### ISSUE TITLE
updates to welcome flow to fix multiple issues

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#1847]
## Description 
The new welcome experience in Brave-UI needs merged. It is currently living in https://github.com/brave/brave-ui/tree/1.0

A living representation of the branch can be viewed here: https://bit.ly/2ApyaXi

**Comment by rebron** [comment]
this fix should also address: 
https://github.com/brave/brave-browser/issues/1316#issuecomment-428269515

**Comment by LaurenWags** [comment]
@rossmoody @cezaraugusto could one of you provide a test plan for this issue?

**Comment by srirambv** [comment]
@rossmoody  I see the flow  https://bit.ly/2ApyaXi on the latest beta. Is this the expected flow or are there any other iterations of this?

**Comment by rossmoody** [comment]
We have outstanding issues to get the Welcome experience up to spec but for the time being the Welcome Experience is reflecting the right flow.

**Comment by kjozwiak** [comment]
@rossmoody the current strings under `brave://welcome` differ in some places compared to the flow that's outlined in https://bit.ly/2ApyaXi. Can you quickly confirm that these are the expected screens for `0.59.28 Chromium: 72.0.3626.64`?

<img width="734" alt="screen shot 2019-01-23 at 6 03 56 pm" src="https://user-images.githubusercontent.com/2602313/51643171-9383dc00-1f39-11e9-976c-2fbe0995bcc6.png">
<img width="737" alt="screen shot 2019-01-23 at 6 04 01 pm" src="https://user-images.githubusercontent.com/2602313/51643176-97176300-1f39-11e9-8b94-239535893234.png">
<img width="704" alt="screen shot 2019-01-23 at 6 04 06 pm" src="https://user-images.githubusercontent.com/2602313/51643179-9979bd00-1f39-11e9-9b9b-d37f494adf5c.png">
<img width="687" alt="screen shot 2019-01-23 at 6 04 12 pm" src="https://user-images.githubusercontent.com/2602313/51643188-9d0d4400-1f39-11e9-9530-0fd3232e9c3c.png">
<img width="685" alt="screen shot 2019-01-23 at 6 04 18 pm" src="https://user-images.githubusercontent.com/2602313/51643192-a0083480-1f39-11e9-8cad-485a844a2d6d.png">
<img width="690" alt="screen shot 2019-01-23 at 6 04 25 pm" src="https://user-images.githubusercontent.com/2602313/51643195-a1d1f800-1f39-11e9-8425-54782aabcec0.png">

**Comment by rossmoody** [comment]
@bradleyrichter and I tackled the locale and PR'd directly against Core (we were hoping to make the Muon migration). The screenshots you posted here are the most current/approved/correct and I will circle back to Brave UI so there's parity. There will be updates to the copy once we find time to bring the inline functionality into the panels but for now this is good. Sry for making your jobs hard here. @kjozwiak @LaurenWags

**Comment by kjozwiak** [comment]
@rossmoody no worries! QA will go through the current `brave://welcome` implementation and make sure that they match the screenshots I added above. We'll make sure that that all the buttons function as expected. It sounds like we won't be doing any other changes in `0.59.x` as we're releasing next week. If we do anymore changes, can you make sure we get an issue filed?
