### ISSUE TITLE
UI problems in new rewards panel for translations

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#18476]
## Steps to Reproduce

   1. Clean install
   1. Run Brave in Polish locale
   1. Enable rewards and ads
   1. Open `interia.pl`
   1. Open Rewards Panel

Note: also reproducible for German locale

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/135512844-040b56ec-cb57-4c4c-99a1-072c0367d445.png)

1 - `Weryfikuj portfel` (Verify Wallet) - extends to a new line, looks ugly.
2 - `Niezewryfikowany twórca` (Unverified creator) - extends to a new line. Also text alignment is left while `Refresh status` is center. Looks weird.
3 - `Odśwież status` (Refresh status) - extends to a new line. 
4 - `Uwzględnij w wsparciu automatycznym` (Include in Auto-Contribute) - extends to a new line. Also the toggle should center vertically when the strings takes 2 lines.
5 - Ugly Vertical scrollbar is shown. 

German:
![image](https://user-images.githubusercontent.com/34715963/135514442-093a9e10-af25-4283-8f49-4cdd9a334f5a.png)

## Expected result:
Nice looking UI.

English for reference:
![image](https://user-images.githubusercontent.com/34715963/135515015-d15cf088-bfb5-4147-aa00-c90099455817.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.32.31 Chromium: 94.0.4606.61 (Oficjalna wersja) nightly (64-bitowa)
-- | --
Wersja | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @zenparsing @Miyayes

**Comment by LaurenWags** [comment]
Verification in progress using

```
Brave | 1.33.85 Chromium: 96.0.4664.45 (Offizieller Build) beta (x86_64)
-- | --
Überarbeitung | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
Betriebssystem | macOS Version 11.6.1 (Build 20G224)
```

Verified images from https://github.com/brave/brave-core/pull/10495.
Verified adjustments made to the panel using Polish and German languages:
* `Verify Wallet` translation remains on one line
* `Unverified creator` translation still extends to a new line per the PR but the text alignment now matches with the `Refresh Status` translation
* `Refresh status` translation still extends to a new line per the PR but the text alignment matches with the text on the same line
* `Include in Auto-Contribute` translation still extends to a new line per the PR but now the toggle should centers vertically when the strings takes 2 lines

Vertical scroll bar is still shown on Polish translation, checking with @zenparsing if this is expected (does not seem so from his PR).

Polish | German
----- | -----
<img width="436" alt="Polish" src="https://user-images.githubusercontent.com/28145373/142680517-44d6d754-a9a9-466a-86a0-2dbb652d14a4.png"> | <img width="422" alt="German" src="https://user-images.githubusercontent.com/28145373/142680523-20a74b74-5efc-4131-b86b-85ff3890c9cb.png">
