### ISSUE TITLE
Add component extension version to brave://ipfs page

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#18493]
## Description 

In order to make it easier to diagnose problems, it is worth adding the current version of component extension on brave://ipfs

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.32 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
--|--
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.3 (Build 21E5196i)

Confirmed correct name and version via `brave://ipfs-internals`
Confirmed correct name and version via `brave://components`

example | example
---------|---------
<img width="1572" alt="Screen Shot 2022-02-07 at 8 40 57 PM" src="https://user-images.githubusercontent.com/387249/152919775-cc298ea7-2d0e-4b01-b0e1-839d99c9613e.png"> | <img width="1244" alt="Screen Shot 2022-02-07 at 8 41 35 PM" src="https://user-images.githubusercontent.com/387249/152919820-16b98762-c0ab-4131-8629-2be0ed9c5370.png">

**Comment by MadhaviSeelam** [comment]
Verified `PASSED` using 

Brave |	1.37.80 Chromium: 99.0.4844.51 (Official Build) beta (64-bit) 
---|--
Revision | 	d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | 	Windows 11 Version 21H2 (Build 22000.493)

Verified correct name and component extension version on `brave://ipfs-interals`
Verified correct name and version on `brave://components`

example|example
----|----
<img width="450" alt= "ipfs-updater" src = "https://user-images.githubusercontent.com/98358127/156612025-c9577841-796d-49af-a8d0-f7d7db897c66.png"> | <img width="450" alt = "ipfscomponents" src = "https://user-images.githubusercontent.com/98358127/156612681-1d1c95da-d949-4da8-b144-96f4af05e1af.png">
