### ISSUE TITLE
[cr95-followup] Rework patches/chrome-browser-resources-settings-about_page-about_page.ts.patch

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#18498]
Consider if this patch can be minimized via patching handler instead of .ts.
(Maybe patch `BrowserLifetimeHandler::HandleRelaunch` to call into `BraveRelaunchHandler` on MacOS and return).

cc: @mariospr

**Comment by simonhong** [comment]
Already handled by https://github.com/brave/brave-core/commit/49a2cc40e1bcb16650a5433415c046b30fd5cb25
