### ISSUE TITLE
Brave wallet Accounts changes

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#18495]
This issue includes accounts related changes such as,
1. Import account with json
2. Import account with private key
3. Update primary account
4. Update secondary account

**Comment by srirambv** [comment]
Import tests blocked on  #19971

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.103 x64 build
- Verified able to import secondary account via Private key
- Verified able to update primary account name
- Verified able to update secondary(imported) account name
----------
Verification passed on Samsung Tab A with Android 10 running 1.33.103 x64 build
- Verified able to import secondary account via Private key
- Verified able to update primary account name
- Verified able to update secondary(imported) account name
