### ISSUE TITLE
[cr95-followup] Convert WebUI::DeprecatedMessageCallback to WebUI::MessageCallback

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#18496]
cr95 made the change "[Migrate to content::WebUI::RegisterDeprecatedMessageCallback() for now](https://github.com/brave/brave-core/pull/9934/commits/19ba45fe4b27c7b37421da97b585b979b4e3a630)".

Following upstream https://bugs.chromium.org/p/chromium/issues/detail?id=1243386, we need to transition all the usages of  `WebUI::DeprecatedMessageCallback` (which uses `base::ListValue*`) to the new implementation of `WebUI::MessageCallback` (which uses `base::Value::ConstListView`)

cc: @mariospr

**Comment by mariospr** [comment]
@mkarolin Not sure about this one, I've already fixed those for cr95, in a follow-up commit in `cr95`, see https://github.com/brave/brave-core/commit/0188be24a794cc68bd385026b2f8da14ead02317

Am I missing anything?

**Comment by mkarolin** [comment]
Closing as based on @mariospr's comment this was already addressed.
