### ISSUE TITLE
Make KeyringControllers SelectedAccount Observable

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#18508]
## Description 
Need to make `KeyringController` `SelectedAccount` Observable to update the `selectedAccount` between tabs and the `Wallet Panel`

https://user-images.githubusercontent.com/40611140/135733932-c7202df9-074c-4556-a49a-712730668ab5.mov

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.86 Chromium: 95.0.4638.54 (Official Build) beta</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.194)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10344>brave/brave-core#10344</a>
</li>
         <li>Verified active account is listed on both panel and wallet page</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/139657307-c29b6826-b50a-47e5-b679-1d0af6bd1f95.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/139657414-5bffd2cf-0c73-4904-85ba-5017a19237f1.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/139657355-5162ff6c-c71c-4c79-a211-82470eb2603c.mov>
      </td>
   </tr>
</table>
