### ISSUE TITLE
Tooltip prevents from accessing site exclude button in rewards

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1850]
## Steps to Reproduce

1. Enable rewards in brave:rewards
2. Browse two sites to add them to auto-contribute table
3. Go to brave:rewards
4. Move mouse over top close button in auto-contribute table
5. Quickly move mouse over bottom close button in auto-contribute table

## Actual result:

Tooltip prevents from accessing site exclude button

![tooltip_fail](https://user-images.githubusercontent.com/34715963/47531781-e1436680-d8ae-11e8-9833-3d0f37a2c73f.gif)

## Expected result:
Tooltip is hidden so that it does not cover button behind it

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

cc @GeetaSarvadnya @kjozwiak @srirambv @LaurenWags to check on other platforms.
cc @NejcZdovc

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.13.6 x64` using the following build which has the latest changes:

Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7 x64

Used STR from OP. 
Thanks @ryanml .
