### ISSUE TITLE
Run go-ipfs with brave agent version suffix 

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#18505]
[go-ipfs 0.10.0 shipped](https://github.com/ipfs/go-ipfs/releases/tag/v0.10.0) with support for running  `ipfs daemon` with custom `--agent-version-suffix`  (https://github.com/ipfs/go-ipfs/pull/8419)

Soon, we will be running our ipfs-desktop nodes with [`--agent-version-suffix=desktop`](https://github.com/ipfs/ipfs-desktop/pull/1914), and it would be useful to run Brave instances with  `--agent-version-suffix=brave` to have better insight into metrics / DHT distribution / usage patterns.

Agent Version can be read via `ipfs id | jq .AgentVersion`:

- `go-ipfs/0.10.0/` - standalone go-ipfs binary
- `go-ipfs/0.10.0/desktop` - node managed by IPFS Desktop
- `go-ipfs/0.10.0/brave` - node managed by Brave

@bbondy @autonome Thoughts?
I remember we wanted to do this a while ago, but it was not possible without recompiling go-ipfs.
(Now it's just a runtime flag which we could enable after upgrading Brave to go-ipfs 0.10.0)

**Comment by bbondy** [comment]
Posted a security review to make sure this is ok, but I don't see a problem with doing this.

**Comment by stephendonner** [comment]
### Verified `FIXED` using 


Brave | 1.32.46 Chromium: 94.0.4606.71 (Official Build) nightly (x86_64)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | macOS Version 11.6 (Build 20G165)

### Steps:
1. new profile
2. launched Brave
3. opened `brave://ipfs` and clicked `Install and start` (confirmed I got `go-ipfs 0.9.1`)
4. in `Terminal.app`, entered `ps ax | grep go-ipfs`
5. confirmed I didn't see `--agent-version-suffix=brave` in the output
6. new profile
7. launched Brave with `--use-dev-goupdater-url`
8. opened `brave://ipfs` and clicked `Install and start` (confirmed I got `go-ipfs 0.10.0`)
9. in `Terminal.app`, entered `ps | ax | grep go-ipfs`
10. confirmed I saw `--agent-version-suffix=brave` in the output

#### `go-ipfs 0.9.1`
**stephendonner@Stephens-MacBook-Pro** ~ % `ps ax | grep go-ipfs      
51152 s000  S+     0:02.36 /Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/nljcddpbnaianmglkpkneakjaapinabi/1.0.6/go-ipfs_v0.9.1_darwin-amd64 daemon --migrate=true --enable-gc --routing=dhtclient`

#### `go-ipfs 0.10.0`
**stephendonner@Stephens-MacBook-Pro** ~ % `ps ax | grep go-ipfs
51007 s000  S+     0:40.59 /Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/nljcddpbnaianmglkpkneakjaapinabi/1.0.54/go-ipfs_v0.10.0_darwin-amd64 daemon --migrate=true --enable-gc --routing=dhtclient --agent-version-suffix=brave`
