### ISSUE TITLE
Google Docs writing cursor stuck at left side.

### ISSUE THREAD

**Issue by farhun1** [brave/brave-browser#18517]
## Description 

If I try to use google docs for writing then the writing cursor is stuck at left. I have checked with chrome, iridium and firefox browser. It isn't showing any problem there. It has something to do with ad blocker as I searched up. The problem is present in the latest version. I have been using brave for over an year now didn't faced it before.

## Steps to Reproduce

   1. Set  trackers & ads blocked to aggressive, cross site cookie blocked ,scripted blocked off & fingerprint blocked strict.
   2. Visit docs.google.com and open a new document.
   3.  Start writing and the cursor will be stuck at  the left

## Actual result:

![image](https://user-images.githubusercontent.com/90555543/135814534-3085ccef-4079-4b07-b7e1-3f424a788e11.png)

## Expected result:
Cursor won't move as we type

## Reproduces how often: 

Everytime.

## Brave version (brave://version info)

Brave | 1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | Windows 11 Version 21H2 (Build 22000.194)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel?
- I haven't tested yet. 
- Can you reproduce this issue with the nightly channel? 
- - I haven't tested yet. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- No.
- Is the issue reproducible on the latest version of Chrome? 
- Chrome doesn't have this issue.

**Comment by rebron** [comment]
@farhun1 Is this working with Shields trackers & ads blocked set to standard?

**Comment by farhun1** [comment]
@rebron Yes it is present when the the shield & trackers was standard. Turning it off fixed it. But again turning it back on was resulting the same issue.

**Comment by J0hnL0cke** [comment]
Fixed by changing fingerprinting blocking from aggressive to standard

**Comment by farhun1** [comment]
Issue was fixed on the later updates and it works fine now.
