### ISSUE TITLE
brave web store blocked by Google

### ISSUE THREAD

**Issue by opichon** [brave/brave-browser#18515]
## Description 
When trying to open the brave web store, I get an error message from Google saying:
"We are sorry, but you do not have access to this service. Please log in to your Admin Console to enable this service."

I am logged in to my google account. In google admin, the setting "Allow users to install any app from Google Workspace Marketplace" is enabled.

## Steps to Reproduce

   1. Open brave browser
   2. Click on Window | Extensions
   3. Click on "Find extensions and themes in the Brave Web Store"
   
## Actual result:

This error page opens: 
https://admin.google.com/ServiceNotAllowed

## Expected result:
Brave web store page should open

## Reproduces how often: 
All the time

## Brave version (brave://version info)
Brave is up to date
Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
No, in chrome I can open the Chrome Web Store

## Miscellaneous Information:
I am running MacOS Big Sur 11.6 on a Mac Mini M1 and a Mac Mini Intel. Both exhibit the same behavior.

**Comment by ryanbr** [comment]
Try signing in to another google account, I'm guessing its related to the google account. @opichon

**Comment by opichon** [comment]
Actually, I logged _out_ of all google accounts, and I could access the zeb store.
