### ISSUE TITLE
How can I view the certificate?

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#18522]
## Description 
How can I view the certificate?

There is no scrolling option.
Zoom doesn't work either.

![Zertifikat](https://user-images.githubusercontent.com/53431361/135855134-029ca78b-9925-4717-b81f-013d71e29f13.jpg)

**Comment by srirambv** [comment]
Does the same happen on Chrome?

**Comment by Johann999** [comment]
If you click on the lock symbol in the urlbar, the settings for this website and the certificate for this website should be displayed.

Unfortunately, only some of the settings and never the certificate are displayed because there is no scroll bar.

The same problem exists with Chrome, Chromium, Opera and Vivaldi.

This display is correct for Firefox, Edge and Yandex. All settings and the certificate are displayed.

**Comment by Johann999** [comment]
This display is now also correct for Chrome. All settings and the certificate are displayed.

**Comment by Johann999** [comment]
Works now correct under version 1.34

**Comment by rebron** [comment]
@Johann999 Thanks for the follow-up.
