### ISSUE TITLE
Dark theme for request ads enabled popup

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#18525]
Need to support dark theme for popup that is triggered by `chrome.braveRequestAdsEnabled` api.

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.32.63 Chromium: 95.0.4638.40 (Official Build) nightly (x86_64)
-- | --
Revision | e3e7c76ba0284b16087cf4cf3153abfaef6470c7-refs/branch-heads/4638@{#624}
OS | macOS Version 11.6 (Build 20G165)

Steps:
1. new profile
2. launched Brave with `--enable-features=RequestAdsEnabledApi`
3. set `Brave colors` to `Dark` via `brave://settings/appearance`
4. loaded `talk.bravesoftware.com`
5. clicked on the `Start free 1:1 call` button
6. confirmed that the popup was dark-themed
7. changed `Brave colors` to `Light` and `same as macOS`, and confirmed the popup was light-themed again

example | example | example | example | example | example
---------|----------|---------|----------|---------|----------
<img width="1312" alt="Screen Shot 2021-10-11 at 5 04 54 PM" src="https://user-images.githubusercontent.com/387249/136869307-9246ba00-3a94-4d39-b57b-4a9e89db1cd3.png"> |  <img width="1312" alt="Screen Shot 2021-10-11 at 4 57 41 PM" src="https://user-images.githubusercontent.com/387249/136869302-5ecd14b7-08b3-4101-aa5e-75ea05d1f690.png"> | <img width="1312" alt="Screen Shot 2021-10-11 at 5 06 55 PM" src="https://user-images.githubusercontent.com/387249/136869524-e532c4f9-de6e-4ca6-b24b-4ad72b3cbc3f.png"> |  <img width="1312" alt="Screen Shot 2021-10-11 at 5 04 48 PM" src="https://user-images.githubusercontent.com/387249/136869306-58807833-2408-4d00-93de-1cd0d9a0a693.png">  | <img width="1312" alt="Screen Shot 2021-10-11 at 5 04 43 PM" src="https://user-images.githubusercontent.com/387249/136869305-59d700e3-fe83-44aa-a080-4890b99f3be9.png"> | <img width="1312" alt="Screen Shot 2021-10-11 at 5 00 39 PM" src="https://user-images.githubusercontent.com/387249/136869304-fd82b7bd-4645-4a63-9e41-5e5b6231cbcf.png">
