### ISSUE TITLE
Remove Brave ads deprecated files

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#18524]
Remove Brave ads deprecated files from the users profile:
```
Default/ads_service/ad_conversions.json
Default/ads_service/bundle_state
Default/ads_service/bundle_state-journal
Default/ads_service/bundle.json
Default/ads_service/catalog.json
```

**Comment by sanketpathak64** [comment]
@tmancey are we supposed to remove above files from codebase or are we talking about adding this files to gitignore

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.33.83 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/10820
Verified legacy files are deleted

![image](https://user-images.githubusercontent.com/34715963/142473794-a1aee03c-8717-46fc-a09c-54e88a83a052.png)|![image](https://user-images.githubusercontent.com/34715963/142473812-e79bc3c3-bdc7-4b50-9268-aface48f3e3b.png)
--|--
