### ISSUE TITLE
Remove extensions dep and buildflag for IPFS

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#18530]

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.34.62 Chromium: 96.0.4664.110 (Official Build) dev (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Steps:
1. fresh install
2. loaded `ipns://en.wikipedia-on-ipfs.org`
3. clicked on `Use a local node`
4. tested a few `IPNS://` and `IPFS://` URLs
5. confirmed they resolved and had content

example | example | example | example
----------|-----------|----------|----------
![18530-1](https://user-images.githubusercontent.com/387249/146246642-834f04ac-7b72-415e-a2ec-7457c8f27964.png) | ![18530-2](https://user-images.githubusercontent.com/387249/146246668-d7983c3f-c9fe-4ee6-8b4c-cc6c0dbeb033.png) | ![18530-3](https://user-images.githubusercontent.com/387249/146246670-5add3d7f-1e75-4c24-82c2-92a53adc9382.png) | ![18530-4](https://user-images.githubusercontent.com/387249/146246672-21baab9d-961a-49b6-9609-4647360c0a01.png)

**Comment by stephendonner** [comment]
@spylogsster this is labeled `OS/Android`, but Android doesn't have local-node support.  Given `Check that IPFS localnode installed and we can navigate ipfs sites` from the testplan, what needs to be tested on Android?  Just the gateway support?

**Comment by spylogsster** [comment]
@stephendonner sure, just gateway to check that it works high-level

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.34.63, Chromium 96.0.4664.110` on a Google Pixel XL running Android 9.0.

Confirmed after a fresh install I got the IPFS gateway interstitial, and after that, content (both `IPFS://` and `IPNS://`) loaded fine.

example | example | example | example
----------|----------|-----------|-----------
![Screenshot_20211217-105812](https://user-images.githubusercontent.com/387249/146594891-f4204870-5818-4f9f-ad7c-d47d8156b6f7.png) | ![Screenshot_20211217-105854](https://user-images.githubusercontent.com/387249/146594917-6bc943a0-74b8-47e1-b963-f6c4d9ed3c5a.png) | ![Screenshot_20211217-105909](https://user-images.githubusercontent.com/387249/146594918-85bd5903-7469-4a40-bea9-08e6206049e4.png) | ![Screenshot_20211217-105821](https://user-images.githubusercontent.com/387249/146594919-5b7e4580-c620-4a35-8444-c7fc8437de42.png)
