### ISSUE TITLE
Only show MM/crypto wallets import flow when the user has actually created a wallet on MM/crypto wallets

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18534]
## Description 

Current flow detects installation of MM and prompts to import on the new wallet screen. This fails as there is nothing to import so seems unnecessary to show the Import from MM button and the importer page 

## Steps to Reproduce

   1. Install MM from Web Store (do not create an account)
   2. Enable flag and enable wallet
   3. Wallet page shows Import from MM even when there is nothing to import from

## Actual result:

Wallet page shows Import from MM even when there is nothing to import from

## Expected result:
Only show MM import button when the user has actually created a wallet on MM

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.38 Chromium: 94.0.4606.71 (Official Build) nightly (x86_64)
-- | --
Revision | `1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@darkdh @jamesmudgett

**Comment by darkdh** [comment]
This should also applies to crypto wallets.
Don't show import flow when we detect crypto wallets is not setup

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.98 Chromium: 98.0.4758.72 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11354>brave/brave-core#11354</a></li>
         <li>Verified when CW Extension is installed, no importer is shown</li>
         <li>Verified when CW Extension is installed and wallet is created, importer is shown during onboarding</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/20799>#20799</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/151834627-68e458cf-40a3-4bb0-a074-b003f13d01fd.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151832940-25209f84-e50a-46cc-b999-8e9fcfead4d9.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151831862-0dcfbe71-5145-4a74-af25-a494060dc483.mp4>
      </td>
   </tr>
</table>
