### ISSUE TITLE
Allow passing multiple Visible Assets Information to BraveWalletService calls

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#18532]
## Description 
Consider Refactoring the the `BraveWalletService`: `addUserAsset`, `removeUserAsset` and `setUserAssetVisible` api's to allow multiple assets to be passed in, in one call. See discussion here: https://github.com/brave/brave-core/pull/10336#discussion_r720621018

**Comment by bbondy** [comment]
unassigned for now because I think we can fix this front end side without native changes. If that changes please let me know.

**Comment by bbondy** [comment]
We can also close this please from the front end team once it is confirmed if it can be done from the front end side.

**Comment by Douglashdaniel** [comment]
Was able to implement these changes on the front-end side in this PR https://github.com/brave/brave-core/pull/11875
Closing as duplicate.
