### ISSUE TITLE
Cannot install Brave due to "more recent version of brave installed" error

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1855]
## Description 
Cannot install Brave due to "more recent version of brave installed" error on Windows. Installer throws an error message every time, even after uninstalling all the brave versions. Got a temporary fix from @bsclifton, after deleting the following registry keys and install the exe worked fine. But, this is not a permanent solution, definitely would need fix for this. Please note this issue is happening only for Windows.

Go into `regedit` and specifically look for the below two keys:
- `HKEY_CURRENT_USER\Software\BraveSoftware\`
- `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\`

Delete BraveSoftware folder from both keys and install the exe solves the issue.

## Steps to Reproduce

   1.  Download the stub installer exe file from Github
   2.  Click on the installer 
   3.  Gives the error

## Actual result:

Click on stub installer is throwing the error as "This computer already has more recent version of Brave. If you're software is not working please uninstall Brave and try again"

![image 6](https://user-images.githubusercontent.com/38657976/47541106-ae709100-d8f5-11e8-9eb8-a7f7771b72d3.png)

## Expected result:

Installer should not throw any error

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.55.20

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? -Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by GeetaSarvadnya** [comment]
Similar issues reported by community:

1+https://community.brave.com/t/cannot-install-brave-dev-and-then-beta-and-stable-in-same-computer/35833

**Comment by kjozwiak** [comment]
Here's a log that @Brave-Matt managed to get from a user experiencing this issue: [log.txt](https://github.com/brave/brave-browser/files/2517457/log.txt)

**Comment by GeetaSarvadnya** [comment]
@simonhong I am not seeing this error on current Dev Build 0.57.3.

**Comment by GeetaSarvadnya** [comment]
I am getting the installation error when I am trying to install Brave from Barron's page

![image](https://user-images.githubusercontent.com/38657976/47647030-d5e88780-db9b-11e8-8492-39a28aaf481a.png)

**Comment by GeetaSarvadnya** [comment]
@simonhong  In my machine `BraveBrowserStandaloneSetup.exe_0.56.14` is already installed on top of that i was trying to install 'BraveBrowserStandaloneSetup.exe_0.56.12' and i got the below error message

![image](https://user-images.githubusercontent.com/38657976/48687994-08f5c800-ebea-11e8-89e8-b8cadf61b276.png)

and `pv` value is - 0.56.12
![image](https://user-images.githubusercontent.com/38657976/48688076-70ac1300-ebea-11e8-854a-259f75b170cc.png)

**Comment by srirambv** [comment]
Ran into this as well. Even after uninstalling the existing version and trying to reinstall release version from https://brave.com/download kept giving the same error. Had to remove the registry keys to install the latest build again

**Comment by kjozwiak** [comment]
@GeetaSarvadnya @srirambv have you guys seen this happen recently in newer versions? Last update was since `December 2, 2018` so this might have been fixed.

**Comment by bbondy** [comment]
Closing because I think it is not valid anymore. Please reopen or comment if you disagree.

**Comment by GeetaSarvadnya** [comment]
@kjozwiak I haven't seen this issue recently in newer versions. I did not see this issue in the last 6 to 7 months. I agree with @bbondy comments, good to close the issue.

**Comment by MadhaviSeelam** [comment]
This issue surfaced today as I tried to install older version Nightly 1.36.64 on Windows 11. Reopening as per @kjozwiak.

**Comment by bsclifton** [comment]
Closing as there hasn't been an update on here in over 1 year
