### ISSUE TITLE
NTP Fall 2021 wallpapers

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18568]
## Description 
Swap out all of our current wallpapers on the new tab with a fresh set of images. 

Purpose:
prevent the images from feeling stale
give other photographers/creators a chance to showcase their work
it's fun!

- [x] https://github.com/brave/brave-browser/issues/19129
- [x] https://github.com/brave/brave-browser/issues/19157
- [x] https://github.com/brave/brave-browser/issues/19127
- [x] https://github.com/brave/brave-browser/issues/19128

## Design
<img width="682" alt="Screen Shot 2021-10-05 at 11 19 38 AM" src="https://user-images.githubusercontent.com/2388823/136080332-e52f4afc-e48d-44b6-945c-3939e91dff32.png">

## Assets
Assets and photo attribution:
https://bravesoftware.slack.com/archives/C7TG12KC3/p1633458074003900
AVIF, WEBP, and compressed JPG available.
For the photo attribution - Corwin and David won't have any links.

## Test plan
[placeholder]

## Miscellaneous information:
Related/prior issues
https://github.com/brave/brave-browser/issues/6904

**Comment by karenkliu** [comment]
Designs added!

**Comment by karenkliu** [comment]
Let's do this as the default :)

![image](https://user-images.githubusercontent.com/2388823/139482200-5c48bcda-44b4-41d9-87c5-0018664a6128.png)

**Comment by simonhong** [comment]
Closed as all sub-tasks are completed.

**Comment by simonhong** [comment]
and set `duplicated` as each subtask PR can be tracked.

**Comment by stephendonner** [comment]
@simonhong is this really `QA/Yes`, given that it's a duplicate/invalid?  If so, what's the test plan?  Just confirm that all images made it to the component, right?

**Comment by simonhong** [comment]
@stephendonner Yes, we update new BG images via component. and I wrote test plan in above each sub-tasks.
and set qa/no to this meta issue.
