### ISSUE TITLE
Profile icon too large

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#1856]
The profile icon is 2px too large and it's causing the menu icon stroke to look to skinny in immediate relation to it. 

![image](https://user-images.githubusercontent.com/29072694/47544654-016a2a00-d89d-11e8-8f02-acfc96079d3e.png)

**Comment by rebron** [comment]
marking wontfix, we're going to change this completely.

**Comment by rossmoody** [comment]
@rebron I have a pr with a fix for this ready to merge. Even if this changes it’ll help in the interim

**Comment by rossmoody** [comment]
It’s just 10 lines of skia code that need approved and merged
