### ISSUE TITLE
Replaced temp strings with final strings

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#1858]
issue for PR: https://github.com/brave/brave-core/pull/743

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Can you please provide the test plan?

**Comment by srirambv** [comment]
@bradleyrichter are we still going `Hmmm... not quite.` ? or are we changing it to `Hmmm, not quite...` ?

**Comment by bradleyrichter** [comment]
@srirambv we need to edit this

Could you make a pr for it?

**Comment by srirambv** [comment]
@bradleyrichter https://github.com/brave/brave-core/pull/808 created and ready for review

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.56.9 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows



![image](https://user-images.githubusercontent.com/38657976/48127137-ff469900-e2a8-11e8-9966-df7c431a5d6e.png)
