### ISSUE TITLE
The method 'wallet_switchEthereumChain' does not exist / is not available.

### ISSUE THREAD

**Issue by neilhoff** [brave/brave-browser#18583]
## Description 
I am attempting to claim some rewards from https://cryptomeda.tech/staking and keep getting this error: The method 'wallet_switchEthereumChain' does not exist / is not available.

I talked with their support and they said to use chrome instead. I don't want to use chrome 😉  

wallet_switchEthereumChain comes from EIP-3326
- https://docs.metamask.io/guide/rpc-api.html#wallet-switchethereumchain
- https://eips.ethereum.org/EIPS/eip-3326

## Steps to Reproduce
From Console run something like this:

```
await ethereum.request({
    method: 'wallet_switchEthereumChain',
    params: [{ chainId: '0x89' }],
  });

```

## Actual result:
![image](https://user-images.githubusercontent.com/1918319/136186874-6dbeffc1-394b-45bc-8bab-e7575f081b7d.png)

## Brave version (brave://version info)

- Brave | 1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)
- Revision: 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
- Windows 10 Version 21H1 (Build 19043.1237)

**Comment by neilhoff** [comment]
I am using the Brave Crypto Wallet Extension.

Is there someplace better where I can request adding support for this?

**Comment by srirambv** [comment]
We can use this issue itself for feature request

**Comment by darkdh** [comment]
QA will be testing on https://github.com/brave/brave-browser/issues/19160
