### ISSUE TITLE
Request: Allow adblock whitelist for extensions

### ISSUE THREAD

**Issue by leodoi3** [brave/brave-browser#18594]
## Description 

I'm using an extension called [Invisibly](https://chrome.google.com/webstore/detail/invisibly/amklimpikigpmhdgokjeobmkegdadegd) , and that extension relies having adblock disabled in order to work correctly.  I contacted the developer and they replied they are unable to support Brave because of the built-in adblocker. So it is possible to add a whitelist for extensions?

**Comment by iefremov** [comment]
there is no such extension anymore
