### ISSUE TITLE
visiting a website closes down (crash?) the whole browser 

### ISSUE THREAD

**Issue by AdKiller** [brave/brave-browser#1859]
## Description 
copy pasting this into the address bar closes down the whole browser "mbtechnicalservices.it"

## Steps to Reproduce

   1.  open new tab
   2.  paste into address bar without quotation marks "mbtechnicalservices.it"
   3.  enter

## Actual result:
the whole browser closes immediately 

## Expected result:
should open the site. it works in Firefox

## Reproduces how often: 

very easy. it happens consistently.

## Brave version (brave://version info)

brave-portable

Brave | 0.25.2
-- | --
V8 | 6.9.427.23
rev | 8ea2a9c
Muon | 8.1.8
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  NO

- Is the issue reproducible on the latest version of Chrome?  NO

**Comment by sillibird** [comment]
On non-portable 0.55.20 a crash does not seem to happen.

**Comment by srirambv** [comment]
This doesnt crash on 0.55.x brave browser. You are on muon browser which will be depreciated soon. You can upgrade to brave browser by downloading it from https://brave.com/download
