### ISSUE TITLE
Add `Payout status` button for ad earnings Rewards payouts and add new state to payout banner

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18602]
## Description

Per @jsecretan, add "Check status" button for ad earnings Rewards payouts.

## Implementation

**Updated Dec 10, 2021**:

https://github.com/brave/brave-browser/issues/18602#issuecomment-991371526

Message @Miyayes or @minkyeongshin for design files.

**Comment by Miyayes** [comment]
Designs have been added. Should be ready to implement.

**Comment by Miyayes** [comment]
Let's set `n` = `7` to start (a week). cc: @jsecretan No big deal if we overshoot and keep showing the banner even though user has received their earnings deposit already.

**Comment by Miyayes** [comment]
**New logic as of Dec 10:** 

```Proposed-logic:
if current day is before 7th
      show 'countdown' message
if current day is between 7th and 10th
      if unverified user and promotion is available
           show 'arrived' message
       else
            show 'arriving' message
```

**Countdown Message**

Your +3.21 BAT October rewards will arrive in %days% days.

**Arrived Message**
Congrats! Your +3.21 BAT October rewards have arrived!

**Arriving Message**
Your +3.21 BAT October Rewards are on the way. Keep an eye out! (edited) ```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 21H2 (Build 19044.1415)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/11347

<details>
<summary>Scenario 1: Payment pending messaging</summary>

</details>

**Comment by GeetaSarvadnya** [comment]
QA blocked as unable to verify the payment messages in the latest beta build `1.35.92`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.35.98 Chromium: 98.0.4758.74 (Official Build) (64-bit) 
-- | --
Revision | d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}
OS | Ubuntu 18.04 LTS


<details>
<summary>Scenario 1: Countdown Message/Payment pending - PASSED</summary>

- Viewed a couple of Ads and close the browser
- Forward the system clock ahead by 24 hours
- Restart the browser
- Confirmed ads are cashed in with the server (verified `Successfully redeemed unblinded payment tokens` msg in logs)
- Close the browser
- Set the system date to be beginning of next month (ex. Feb 1)
- Restart the browser
- Confirmed `Your +X BAT January rewards will arrive in Y days` message is shown in the rewards settings, panel, NTP widget and on the site panel as expected (X is number of BAT, Y is number of days)
- Confirmed that `Countdown Message` is retained even after closing and reopening the panel
- Confirmed that `Countdown Message` is retained in rewards settings, NTP widget and BR panel even after browser restart

![image](https://user-images.githubusercontent.com/34715963/151880435-6142e67e-3d53-477b-8956-941e456324ae.png)|![image](https://user-images.githubusercontent.com/34715963/151880499-7133b8f3-e364-4dcb-a550-6da15c62e9f2.png)|![image](https://user-images.githubusercontent.com/34715963/151880540-bf461b00-7dba-453a-bdd6-ae36e8cf3453.png)|![image](https://user-images.githubusercontent.com/34715963/151880654-5ad3fff2-1e26-4bc3-8db6-1df48afa78f0.png)|![image](https://user-images.githubusercontent.com/34715963/151880797-0403b3d3-78c4-408e-a76c-7c2ce63426ae.png)|![image](https://user-images.githubusercontent.com/34715963/151880906-7f8410a2-dfaf-4dd4-89ff-00536250c91d.png)|![image](https://user-images.githubusercontent.com/34715963/151880833-af7ac9ba-6716-43e4-b530-64a4ed4eefbb.png)
--|--|--|--|--|--|--

- Confirmed countdown message is shown when the system date is set to 1st, 2nd, 3rd, 4th, 5th and 6th Feb (confirmed on settings, panel, widget but only took SS of settings)

1st Feb | 2nd Feb | 3rd Feb | 4th Feb | 5th Feb | 6th Feb
----|----|---|---|---|---
![image](https://user-images.githubusercontent.com/34715963/151881313-938a13f5-65a5-4f3f-95b6-ab72f9f592bc.png)|![image](https://user-images.githubusercontent.com/34715963/151881372-ba2d19e2-5107-4d53-bb49-262ef5e993ae.png)|![image](https://user-images.githubusercontent.com/34715963/151881420-2ce29dc4-8d65-4c12-bd9f-a1a3fac3ff1e.png)|![image](https://user-images.githubusercontent.com/34715963/151881474-a8a6252e-6f7a-4f5f-b6b7-f79eb61a4c0e.png)|![image](https://user-images.githubusercontent.com/34715963/151881615-9053de48-3530-4aa1-b4bc-eb54c3e3b5df.png)|![image](https://user-images.githubusercontent.com/34715963/151881678-5fa7f33d-c2eb-4a0e-8425-de47c0b91de6.png)


- Confirmed countdown message isn't shown on 7th Feb

</details>

<details>
<summary>Scenario 2: Arriving Message - PASSED</summary>

- Completed Scenario 1
- Set the system date to payout date (Feb 7)
- Confirmed `Your +X BAT January rewards are on the way. Keep an eye out! Check Status` message is shown in the rewards settings, panel, NTP widget and on the site panel as expected. (X is number of BAT)
- Confirmed click on `Check Status` redirects to BAT community site https://community.brave.com/t/ads-payout-status-update/287895
- Confirmed that BAT arriving message is retained even after closing and reopening the panel
- Confirmed that BAT arriving message is retained in rewards settings, NTP widget and BR panel even after browser restart
- Confirmed Arriving message is shown on 8th, 9th and 10th Feb.
- Confirmed no messages are shown on 11th Feb

![image](https://user-images.githubusercontent.com/34715963/151882014-c173aaef-3309-44c3-84f9-9d4ab9cd26c9.png)|![image](https://user-images.githubusercontent.com/34715963/151882169-c8a1dd13-a984-4b9f-9b4e-7b1d5a25a713.png)|![image](https://user-images.githubusercontent.com/34715963/151882245-640b018b-94f5-4f8a-bd20-1c2bd5f711fc.png)|![image](https://user-images.githubusercontent.com/34715963/151882277-187ec189-9f26-46e5-93c6-1a7556fcd8b3.png)|![image](https://user-images.githubusercontent.com/34715963/151882304-f47b583f-5e09-4181-ba42-3e8511e5c2e2.png)|![image](https://user-images.githubusercontent.com/34715963/151882328-2071422b-0928-4816-a12c-7b68dd4c1ef2.png)|![image](https://user-images.githubusercontent.com/34715963/151882356-819c48e0-9d76-41c7-bcb1-9184bab9204d.png)
--|--|--|--|--|--|--

</details>

<details>
<summary>Scenario 3: Arrived Message - Part 1 - PASSED</summary>

- Completed Scenario 1
- Simulated ad grant in DB (`balance_report_info` table)
- Set the system date to payout date (Feb 7)
- Confirmed `Congrats! Your January rewards have arrived!` message is shown in the rewards settings, panel, NTP widget and on the site panel as expected.
- Confirmed arrived message is retained even after closing and reopening the panel
- Confirmed arrived message is retained in rewards settings, NTP widget and BR panel even after browser restart
- Confirmed arrived message is shown on 7th, 8th, 9th and 10th Feb.
- Confirmed no messages are shown on 11th Feb
- Note, value was removed from message with https://github.com/brave/brave-browser/issues/20597

![image](https://user-images.githubusercontent.com/34715963/151882922-ba8d1e4e-eb41-4ae4-b68f-e47114e41f21.png)|![image](https://user-images.githubusercontent.com/34715963/151882960-f0923001-cf76-453c-ba14-73d74b58335b.png)|![image](https://user-images.githubusercontent.com/34715963/151883017-5a58bb53-6543-4eca-afe6-9b13ddfee0d8.png)|![image](https://user-images.githubusercontent.com/34715963/151883050-1e9f9067-34c8-48cd-8cb0-0eb71c99f440.png)|![image](https://user-images.githubusercontent.com/34715963/151883100-2b6516b5-afcf-499f-be36-ab8b9fd79e0e.png)|![image](https://user-images.githubusercontent.com/34715963/151883119-55fd591f-de53-4355-bac9-f2052f44e538.png)|![image](https://user-images.githubusercontent.com/34715963/151883144-acb3ed9c-d709-4254-944d-00f720b4032b.png)
--|--|--|--|--|--|--

</details>
