### ISSUE TITLE
Browser crash when trying to enable VPN

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18610]
## Description 
Browser crash when trying to enable VPN

## Steps to reproduce 

   1. Enable VPN flag
   2. Select VPN from settings menu, app crashes
   3. Select VPN from intro card in menu, app crashes
   4. Go to VPN Settings and enable it, app crashes

## Actual result 

https://user-images.githubusercontent.com/17010094/136335923-9517a344-fbd5-4059-96c1-5e249f93ecaf.mp4

## Expected result
No crash. Should enable and install configuration file and enable VPN

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.32.73 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Moving this into `1.31.x - Release #2` as VPN won't be enabled/released till Oct. 26th so we should be fine for the initial `1.31.x` release. However, this should definitely get fixed for `1.31.x - Release #2`

**Comment by kjozwiak** [comment]
@deeppandya @bsclifton going to `release/blocking` as I'm going to remove this from a milestone till we get a more concrete/solid plan re: VPN and which version it will be included in.

**Comment by bsclifton** [comment]
Going to close this issue as everything is behind a flag - when we do launch VPN, we can make sure it doesn't crash 😄
