### ISSUE TITLE
Disable share hub doesn't work on Tablet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18612]
## Description 
Disable share hub doesn't work on Tablet

## Steps to reproduce 

   1. Clean install 1.31.74 x64 build
   2. Enable `Disable share hub` setting
   3. Click share button from menu, still show Google Share hub

## Actual result 

https://user-images.githubusercontent.com/17010094/136397253-42be1947-56e3-48d6-b044-59c5f906a662.mp4

## Expected result
Show share sheet when setting is enabled

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? YEs

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.31.74 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc; @deeppandya @samartnik

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` as the above will require a `1.31.x` RC which I'm hoping to kick off tonight 👍 We'll need `1.31.84` or higher.
