### ISSUE TITLE
document.referer leaks the referrer

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1861]
Referer headers are spoofed in brave, but document.referer leaks the current referer

**Comment by bbondy** [comment]
This was a regression and we have a test fail for it, @yrliou will fix on Monday.

**Comment by yrliou** [comment]
Marked as QA/No because it is covered by browser tests.

**Comment by bbondy** [comment]
> @yrliou will fix on Monday.

I lied, she did it today :P
