### ISSUE TITLE
Monthly Payment USD convertion value is shown 0.00

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1862]
## Description 
Monthly Payment USD conversion value is shown 0.00. Reload the page will display the correct value.

## Steps to Reproduce

Test Plan 1:
   1. Launch Brave with clean profile 0.57.3
   2. Click on BAT logo (Open Rewards panel)
   3. Click on `JOIN REWARDS` to enable the wallet
   4. Click on new tab and open any site (spend minimum page time 5 secs on site)
   5.  Open `chrome://rewards/` through Hamburger menu
   6.  Observer the `Monthly Payment USD` conversion value

Test Plan 2:
  1. Launch Brave with clean profile 0.56.7
  2. Open Rewards panel
  3. Click `Join Rewards`
  4. Click ok button on Grants notification pop up
  5. Click on `Rewards settings` to open rewards page
  6. Observe the `Monthly Payment USD` conversion value displayed as 0.00 

**Note**: Reload the page will display correctly value

## Actual result:
Monthly Payment USD convertion value is shown 0.00
![usd value null](https://user-images.githubusercontent.com/38657976/47573724-a4817900-d95b-11e8-9c96-b474a17210ef.gif)

## Expected result:
Monthly Payment USD convertion value should be shown correctly.

## Reproduces how often: 
Easy

## Brave version (brave://version info)

Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by jasonrsadler** [comment]
@GeetaSarvadnya This isn't reproducible on latest master. Can you confirm if this is still a problem?

**Comment by NejcZdovc** [comment]
closing for now, please reopen if this still happens
