### ISSUE TITLE
Network issues when upgraded 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18640]
## Description 
Network issues when upgraded 

## Steps to reproduce 

   1. Install 1.32.46 x64 nightly build
   2. Enable VPN and check you are connected by checking IP 
   3. Keep the device idle for >10 mins and exit Brave Nightly 
   4. Upgrade to 1.32.56 x64 nightly build
   5. VPN connection shows active but webpages don't load
   6. Disconnect and try to reconnect VPN, shows `Connecting to your server...` message and gets stuck there
   7. Visiting pages on Chrome works so not an issue with device network capability
   8. Try loading pages on Brave Nightly fails 

## Actual result 
Network issues when upgraded 

## Expected result
Should not disrupt network connection during upgrades

## Issue reproduces how often 
Once

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.32.46 & 1.32.56

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @anthonypkeane @brave/uplift-approvers  we should probably get this uplifted to 1.31.x

**Comment by mattmcalister** [comment]
This is pretty old now. Is it still happening?

**Comment by deeppandya** [comment]
@mattmcalister this should be fixed. @srirambv I am updating test plan to cover this scenario for VPN.
