### ISSUE TITLE
Google Duo service not working on Brave

### ISSUE THREAD

**Issue by ksajan** [brave/brave-browser#18658]
## Description 

Recently I tried using Duo on the brave browser it was not working it said "We are sorry, but you do not have access to this service. Please contact your Organization Administrator for access." Even though it's my personal Gmail account. And logging in to the same account from chrome or firefox or safari was working for me. It previously used to work for me. Recently only it started behaving like this. Any reason and any fix to use google duo service on the brave browser.

## Steps to Reproduce

   1. Open Duo website
   2. Try using the Web version of Duo
   3. After logging in to your account you will the msg saying you don't have access.

## Actual result:

<img width="1680" alt="Screenshot 2021-10-09 at 12 45 28 AM" src="https://user-images.githubusercontent.com/31013555/136614239-0d44720a-8765-4ac5-80b0-44f94a9afdee.png">

## Expected result:
<img width="1680" alt="Screenshot 2021-10-09 at 12 52 46 AM" src="https://user-images.githubusercontent.com/31013555/136614724-f5565b5b-a6cb-4f92-a704-9614a35d681a.png">

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | macOS Version 11.6 (Build 20G165)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
@ksajan Try using a different google username/login

**Comment by ksajan** [comment]
Recently google services on my brave are lagging too much or seem buggy. Recently Youtube homepage won't load video won't be shown I can't scroll I have to refresh multiple times to fix this. Is this anti-competitive behavior by google some bug only with me.

**Comment by rebron** [comment]
@ksajan Do you think there might be an extension that could be causing the issue?
