### ISSUE TITLE
Implement eth_signTypedData and in particular eth_signTypedData_v4 version of EIP-712

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#18659]
https://eips.ethereum.org/EIPS/eip-712

**Comment by darkdh** [comment]
"Unlock currency" in https://opensea.io/ now uses `eth_signTypedData_v4`
and also https://zed.run/

**Comment by cruzdanilo** [comment]
kinda unbelievable that the new wallet (which is currently the default) has just "removed" this functionality

**Comment by cruzdanilo** [comment]
kinda unbelievable that the new wallet was released without this functionality, effectively removing it from the old wallet.

**Comment by kjozwiak** [comment]
Moving this back to `1.33.x` as it was reverted from `1.32.x` as per https://github.com/brave/brave-core/pull/11277 due to causing https://github.com/brave/brave-browser/issues/19719.
