### ISSUE TITLE
Remove "Auto-Contribute" from Rewards Summary for Japan region

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#18651]
## Description 

Rewards panel UI is being refreshed with https://github.com/brave/brave-browser/issues/14602

Previously line items only displayed on the summary as they occurred. However, with the UI refresh the line items are always there. In the case of Japan region, Auto Contribute is not applicable, so AC should be removed from the summary.

## Steps to Reproduce

   1. Install 1.31.x with Japan region, staging env
   2. Enable Rewards
   3. Look at summary (in my example I have bF wallet connected, but AC should be removed regardless of whether bF wallet is connected or not)

Repeat for Upgrade case also

## Actual result:

Auto Contribute is listed in summary but is not applicable to Japan region:

Example | Example
----- | -----
<img width="1191" alt="Screen Shot 2021-10-08 at 9 32 06" src="https://user-images.githubusercontent.com/28145373/136566716-ba6db9a1-8de8-49bb-9d7a-910bfb421c66.png"> | <img width="439" alt="Screen Shot 2021-10-08 at 9 32 20" src="https://user-images.githubusercontent.com/28145373/136566751-ee30fd35-e982-4b01-9947-bd4f2ab3b22e.png">

## Expected result:
AC should not be listed in summary for Japan region

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.31.74 Chromium: 94.0.4606.71 (Official Build) beta (x86_64)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | macOS Version 10.15.7 (Build 19H1417)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by Miyayes** [comment]
Based on discussions, @zenparsing's solution will be as follows: If Auto-Contribute is disabled, then the line item will disappear from the summary. Since it is always disabled in JP region for now, it will not appear. (If US user has it disabled, it will also not appear.)

**Comment by LaurenWags** [comment]
Requires 1.31.84 or above to test this issue.

**Comment by LaurenWags** [comment]
Verified passed with 

```
Brave | 1.31.84 Chromium: 95.0.4638.40 (Official Build) (x86_64)
-- | --
Revision | e3e7c76ba0284b16087cf4cf3153abfaef6470c7-refs/branch-heads/4638@{#624}
OS | macOS Version 10.15.7 (Build 19H1417)
```

Confirmed when AC is enabled (US region), Auto Contribute line displays on wallet summary:

Example | Example
----- | -----
<img width="1196" alt="US AC on" src="https://user-images.githubusercontent.com/28145373/137146643-9ee7f9e5-0afd-4b65-bff4-641d10cbac66.png"> | <img width="1196" alt="US AC on2" src="https://user-images.githubusercontent.com/28145373/137146662-553d31a9-0cd8-443a-9f33-44e80fd20cab.png">

Confirmed when AC is disabled (US region), Auto Contribute line does not display on wallet summary:

Example | Example
----- | -----
<img width="1194" alt="US AC off" src="https://user-images.githubusercontent.com/28145373/137146794-4f120d7c-f4d3-4654-87e5-c0793dd29d72.png"> | <img width="1192" alt="US AC off2" src="https://user-images.githubusercontent.com/28145373/137146807-9f3052b9-fb8a-4114-9dcc-a5c636f98c98.png">

Confirmed when AC is not available (bitflyer/Japan region), Auto Contribute line does not display on wallet summary:

Example | Example
----- | -----
<img width="1195" alt="bF1" src="https://user-images.githubusercontent.com/28145373/137147285-ddad5b33-29a9-48ba-9611-e41c763a3c8a.png"> | <img width="1192" alt="bF2" src="https://user-images.githubusercontent.com/28145373/137147299-7b878b9b-07f2-4dbc-9e1b-e36aa62a9a5b.png">
