### ISSUE TITLE
Colors of the settings menu bar

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#18679]
## Description 
So I wouldn't call my issue a bug, but the settings menu bar has a very bright purple color which can really hurt eyes somewhat on a dark theme. It would be good if there was a possibility to change it's color in the profile menu or at least if it's default color was changed to black, gray or something else that is darker(like it is in Firefox and Google Chrome)

## Steps to Reproduce
   1. Open Brave Browser
   2. Go to settings

## Actual result:
Bright purple bar shining into my eyes

## Expected result:
It would be good if it was colored similar to how it is in Chrome or Firefox(screenshots attached)

## Brave version (brave://version info)
1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)

## Version/Channel Information:
Haven't tried

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information
Brave
![brave](https://user-images.githubusercontent.com/83418948/136709036-a3ce758a-9dd5-45df-b395-c4687d7dbad3.png)
Firefox
![firefox](https://user-images.githubusercontent.com/83418948/136709039-de30392a-798e-4362-84a3-da71fb602d88.png)
Chrome
![chrome](https://user-images.githubusercontent.com/83418948/136709045-c625423d-6dd0-48d1-a8cb-4fbc2036b08a.png)

**Comment by rebron** [comment]
Closing as wontfix. That's the color palette we've chosen and we're going to continue to use. We may revisit at a later time.
