### ISSUE TITLE
Menu-Bar

### ISSUE THREAD

**Issue by misterhsp** [brave/brave-browser#18676]
Without a menu bar, this browser is unusable. Simply garbage.

...

**Comment by lglista** [comment]
Hi @misterhsp, Brave is built on Chromium which does not have a menu bar by default. All options that could be found in a menu bar can be found by clicking the "hamburger" button (three horizontal lines) at the top right of the browser.

Alternatively, there is an extension that adds a menu bar that can be downloaded and installed for free through the chrome web store [here](https://chrome.google.com/webstore/detail/proper-menubar-for-google/egclcjdpndeoioimlbbbmdhcaopnedkp)

**Comment by misterhsp** [comment]
Proper Menubar has not worked for a long time (Linux).

...

**Comment by rebron** [comment]
Closing. If you have additional feedback, we invite you to visit https://community.brave.com
