### ISSUE TITLE
NotAbleToWatchVideos: primevideo.com/

### ISSUE THREAD

**Issue by starboyvarun** [brave/brave-browser#18674]
Whenever I am playing any movies/ series on amazon prime this error pops out.
![1](https://user-images.githubusercontent.com/26819449/136697748-395ff083-d2d7-4604-975d-875845c8248e.JPG)
I have tried each possible solution, cleared cache, disabled brave shield, not using VPN or anything .
When I tried running on chrome or any other browser it runs perfectly.
I have previously reported a similar error/issue. I think brave is blocking some useful mp4 /videos files.
Thank You.

**Comment by clicky6** [comment]
![1](https://user-images.githubusercontent.com/89839714/136702269-1736927c-d67b-4bc0-ab52-ddf80ab8eac5.png)
See enable this...

**Comment by davidone** [comment]
Same is happening here.
OS: OSX Big Sur 11.6
Brave: Version 1.31.87 Chromium: 95.0.4638.54 (Official Build) (x86_64)
Widevine is enabled (just in case I tried to disable it and re-enable it back, no success)

I tried with Brave Nightly and everything works as expected.

**Comment by rebron** [comment]
@davidone When you enable back, can you restart? 
In brave://components/ do you see Widevine Content Decryption Module - Version: 4.10.2198.0
