### ISSUE TITLE
Disable Google-assisted address normalization

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#1868]
Autofill may attempt to contact a Google-owned server to download rules for normalizing address components such as phone numbers.

Some internal documentation: https://cs.chromium.org/chromium/src/components/autofill/core/browser/address_normalizer.h

Network access occurs in https://cs.chromium.org/chromium/src/third_party/libaddressinput/chromium/chrome_metadata_source.cc and should be disabled. There are no ill effects to disabling it; autofill will continue to function.

**Comment by srirambv** [comment]
@pilgrim-brave can you add `QA/Yes`/`QA/No` label and any test steps in the issue/PR accordingly?
