### ISSUE TITLE
Block Instagram embedded posts?

### ISSUE THREAD

**Issue by bayazidbh** [brave/brave-browser#18682]
## Description 
Turning off "Allow Facebook logins and embedded posts" doesn't seem to block instagram posts. Is there any particular reason why Instagram isn't included in the Facebook toggles? Any plans on including it, creating a separate toggle for it, or any built-in alternatives?

(Just asking for clarification, if this isn't part of current plans)

## Expected result:
Block Instagram when Facebook logins and embedded posts are blocked.

## Actual result:
![image](https://user-images.githubusercontent.com/26621899/136731512-20318b45-c35f-4f80-9f3d-bc8f2cbecde6.png)

<img src="https://user-images.githubusercontent.com/26621899/136732165-ffe7460c-2a2c-433e-9e17-ef7946917dce.jpg" width=35% height=35%>

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:
```
Brave | 1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | Linux
```

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 11

## Version/Channel Information:
Checked only with Release channel.

**Comment by SANDEEPSINWAR39** [comment]
Ok

**Comment by ryanbr** [comment]
As annoying as it is, blocking this would cause issues with users, major webcompat complaints. So nothing default in Brave. @bayazidbh 

However, Adding the following in `brave://adblock` would block instagram:

```
||instagram.com/embed.js$third-party
##.instagram-media
```

**Comment by bayazidbh** [comment]
Ah, no text-based alternative like Twitter? Understandable, thank you for the explanation and easy way to block.
