### ISSUE TITLE
Improve error messages for devices if user selected wrong application

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#18698]
Improve error messages for devices if user selected wrong application:
![image](https://user-images.githubusercontent.com/2965009/136848705-e6047d4a-2816-41b9-8c5a-49572e906fd1.png)

Need to make it more user-friendly

**Comment by jamesmudgett** [comment]
Let's map common errors like this with a better description and instructions.

**Comment by yrliou** [comment]
test plan specified in https://github.com/brave/brave-core/pull/10867

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10867>brave/brave-core#10867</a></li>
         <li>Verified error message is shown when wrong application is opened while connecting h/w device</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/141131879-258c30ab-a22e-4acc-bcc1-f28edb586c6c.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/141131901-2bbe95ff-3a25-492d-9555-e8e45d7c0884.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/141130989-987d61c7-c9bb-4787-b788-6909cd1f5233.png>
      </td>
   </tr>
</table>
