### ISSUE TITLE
Add new feature to use free proxies from web 

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#18694]
## Description 
RIGHT NOW TO VISIT CERTAIN SITES IT REQUIRES SEPERATE VPN APP THAT COST A LOT.
HOWEVER IF BRAVE HAS INBUILT FUNCTIONALITY AND SETTINGS TO SPECIFY FREE PROXIES OR SPECIFY SITE TO SCRAPE AND USE FREE PROXIES SUCH COST CAN BE ELIMINATED.

ALSO WITH VPN WE HAVE LIMITED COUNTRY OPTIONS BUT WITH FREE PROXIES WE CAN HAVE MULTIUDE OF FEATURES TO BUPASS GEO RESTRICTIONS.

ADD NEW OPTION IN MENU TO SPECIFY PROXY

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
We plan on integrating VPN within but no plans for any free proxies. You can set the proxy at a network level so doesn't require Brave to handle it. 


@anthonypkeane going to close this please reopen if you think this is something we need to consider doing in future

**Comment by tathastu871** [comment]
Reopen it. 
Reason for adding proxy routing.
On non rooted device using vpn and adblocker together is not possible.

There are some sites with extensive ads that brave was not able to block. On those sites i have to use adblocker app that uses local vpn profile to filter ads. But also those sites are georestricted. Hence to access them i need to use different country vpn. But vpn and adblocker cannot be used simultaneously. 

Hence while ad blocker is on if we can route all traffic through proxy we can solve above problem.

Midori browser android has options to define custom proxy, tor, ip2
