### ISSUE TITLE
Unable to build Brave on Apple ARM following the instructions in README

### ISSUE THREAD

**Issue by philippemnoel** [brave/brave-browser#18701]
## Description 
I'm following the instructions for compiling Brave on macOS. I'm on an M1 Macbook Pro. It fails at various steps. Notably I needed to change `brave-core` to `brave_core` in the package.json. Now, it fails at `deep-freeze-node` which says that my architecture is not supported.

This begs the question: How does the Brave team build Brave on Apple ARM? Clearly it's not with the scripts/instructions here.

## Steps to Reproduce
Follow the macOS steps to compile on macOS, but on an M1 machine.

## Actual result:
<img width="964" alt="Capture d’écran, le 2021-10-11 à 16 26 02" src="https://user-images.githubusercontent.com/21990816/136851450-a760fa76-64dc-4008-a08f-a97669198185.png">

## Expected result:
Actually compiling Brave on macOS

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Current master

## Version/Channel Information:
N/A

## Other Additional Information:
N/A

## Miscellaneous Information:
N/A

**Comment by mihaiplesa** [comment]
@philippemnoel we build for arm64 (m1) on x64 (Intel). If you'd like please retry with the changes in the linked PR.
