### ISSUE TITLE
White flash when new window is opened in dark mode

### ISSUE THREAD

**Issue by SlowNicoFish** [brave/brave-browser#18703]
## Description 

The issue is that the screen flashes white while starting the browser/opening a new window when dark mode is enabled.

## Steps to Reproduce

   1. Start Brave
   2. 
   3. 

## Actual result:

The Brave windows shows a white page before new tab page loads in.

## Expected result:
If brave is in dark mode the window should not flash

## Reproduces how often: 

Every time Brave is launched

## Brave version (brave://version info)

V1.30.87

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by rebron** [comment]
@SlowNicoFish What OS are you on? Can you update to 1.31.87 and let me know if you're still experiencing the issue?

**Comment by heywoodlh** [comment]
Setting Auto Dark Mode in `chrome://flags` to Enabled fixed this for me.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/18178614/155582877-26899fea-5cab-4c39-911f-a57b6f593b75.png">

**Comment by rebron** [comment]
Closing as duplicate and fixed in 1.42.x with https://github.com/brave/brave-browser/issues/16078
