### ISSUE TITLE
Auto-populate token details when adding custom asset

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#18704]
From Edward Ridgely on Slack:

> Is anyone else able to add custom tokens (0xc770eefad204b5180df6a14ee197d99d808ee52d)? It’s a jarring experience contra MM as it doesn’t auto-populate the fields.

![Screen Shot 2021-10-11 at 8 12 45 PM](https://user-images.githubusercontent.com/3684187/136871562-404b6953-b6d3-41b2-b6bc-9e3e9e32beb7.png)

Etherscan has an API for this: https://docs.etherscan.io/api-endpoints/tokens#get-token-info-by-contractaddress

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11589>brave/brave-core#11589</a></li>
         <li>Verified entering token contract address auto-populates the token details</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/149293920-c4450e73-c757-4818-82bb-b88b37d4576f.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/149293959-257bf964-e0a6-42f9-a460-cf674827eacf.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/149294016-ee0beb29-84f1-4df2-91e5-c55b5ce4de65.mov>
      </td>
   </tr>
</table>
