### ISSUE TITLE
Brave Windows Browser _ When I try to release a tab which I have docked on to the right before … nothing happens. If I close the tab and the brave browser … at the next start the tab is back again. How can i release / remove a Tab? Is this a bug or something I got wrong?

### ISSUE THREAD

**Issue by AntonKanns** [brave/brave-browser#1870]
When I try to release a tab which I have docked on to the right before … nothing happens.
If I close the tab and the brave browser … at the next start the tab is back again.
How can i release / remove a Tab? Is this a bug or something I got wrong?

![grafik](https://user-images.githubusercontent.com/44521792/47602265-c111c580-d9dc-11e8-97be-032774581b11.png)

**Comment by srirambv** [comment]
This is on muon browser which will be deprecated soon. To unpin the tab you can drag it out after all pinned tabs.

**Comment by AntonKanns** [comment]
Where can I get the up to date version?

I have the following version ...
 
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 10.0.17763 
Update Channel: Veröffentlichung 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

If i try to update no vew version is available ...
![grafik](https://user-images.githubusercontent.com/44521792/47605325-342f3200-da05-11e8-8f39-70b03b1e2609.png)

**Comment by srirambv** [comment]
You download it from https://brave.com/download. Upgrade from muon is not yet implemented. You can manually download the new version from https://brave.com/download and then import bookmarks/history/cookies/new tab stats from your muon browsers.
