### ISSUE TITLE
Rewards wallet is not regenerated when wallet data is unreadable

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#18717]
Currently, if the Rewards wallet info stored in `Preferences` becomes unreadable (most commonly due to a pre-1.31 version of the browser losing access to `OSCrypt` keys) a new wallet is not created for the user.

When the user is performing an action that requires a payment ID and the existing data cannot be read, we should:

- Write to the event log, recording that wallet corruption was detected.
- Generate a new wallet for the user.
- Display previous wallet IDs for the user on the `rewards-internals` page.

**Comment by stephendonner** [comment]
## Addendum

### Case One: mangled `recovery_seed`

### Steps:

1. installed `1.31.87`
2. launched Brave
3. enabled Rewards
4. viewed a few ads
5. shut down Brave
6. opened `Preferences` and  added junk characters to the  `recovery_seed` section; saved changes
7. renamed the folder to `Brave-Browser-Beta`
8. relaunched Brave using `1.32.81`
9. viewed an ad and claimed UGP grants

**Confirmed:**

- newly created wallet ID is displayed after upgrade
- previous (corrupted) wallet ID is displayed
- there's an event in the log recording that wallet corruption was detected
- confirmed ad rewards are reconciled and unblinded tokens are redeemed successfully after regenerating a new wallet ID

example | example | example | example | example | example | example
---------|----------|---------|---------|----------|----------|---------
<img width="1227" alt="Screen Shot 2021-11-02 at 10 11 43 AM" src="https://user-images.githubusercontent.com/387249/139958885-e168b015-9d14-49db-a5f0-1732e17b2fbd.png"> | <img width="1227" alt="Screen Shot 2021-11-02 at 10 11 56 AM" src="https://user-images.githubusercontent.com/387249/139958931-be647f7e-7d3c-44c9-961d-10b80be260ef.png"> | <img width="1777" alt="Screen Shot 2021-11-02 at 10 14 01 AM" src="https://user-images.githubusercontent.com/387249/139958968-013efdc9-5370-4b13-8dcb-93117f6351f1.png"> | <img width="1777" alt="Screen Shot 2021-11-02 at 10 14 17 AM" src="https://user-images.githubusercontent.com/387249/139958971-8ecc677f-91b2-4c6a-8514-70834fbf0824.png"> | <img width="1503" alt="Screen Shot 2021-11-02 at 10 20 52 AM" src="https://user-images.githubusercontent.com/387249/139958973-734ff596-3384-4f55-8b04-cc02e7c9013b.png"> | <img width="1503" alt="Screen Shot 2021-11-02 at 10 21 52 AM" src="https://user-images.githubusercontent.com/387249/139959117-cd92d6bb-217e-4489-a038-47b3d6ac70ec.png"> | <img width="1503" alt="Screen Shot 2021-11-02 at 10 22 41 AM" src="https://user-images.githubusercontent.com/387249/139959120-2b1bef04-b172-4872-80b6-5a200ca1e14f.png">





```
[Nov 02, 2021, 10:15:02.5 AM:ERROR:ad_rewards.cc(67)] Failed to reconcile ad rewards due to invalid wallet
[Nov 02, 2021, 10:15:02.5 AM:ERROR:redeem_unblinded_payment_tokens.cc(55)] Failed to redeem unblinded payment tokens due to invalid wallet
[12879:259:1102/141013.936545:VERBOSE1:ad_rewards.cc(240)] OnGetPayments
[12879:259:1102/141013.936634:VERBOSE6:ad_rewards.cc(242)] URL Response:
 URL: https://ads-serve.bravesoftware.com/v1/confirmation/payment/a26f29ca-d773-4ce3-a45d-d63aa6646a6a
 Response Status Code: 200
 Response: [{"balance":"0","month":"2021-11","transactionCount":"0"}]
[12879:259:1102/141013.937861:VERBOSE1:ad_rewards.cc(263)] Successfully reconciled ad rewards
```


### Case Two: mangled `wallets.brave` JSON

### Steps:

1. installed `1.31.87`
2. launched Brave
3. enabled Rewards
4. viewed a few ads
5. shut down Brave
6. opened `Preferences` and  added junk characters to the  `wallets.brave` section; saved changes
7. renamed the folder to `Brave-Browser-Beta`
8. relaunched Brave using `1.32.81`
9. viewed an ad and claimed UGP grants

** Confirmed:**

- newly created wallet ID is displayed after upgrade
- previous (corrupted) wallet ID is displayed
- there's an event in the log recording that wallet corruption was detected
- confirmed ad rewards are reconciled and unblinded tokens are redeemed successfully after regenerating a new wallet ID

example | example | example | example | example | example | example | example
---------|----------|---------|----------|----------|---------|---------|----------
<img width="1525" alt="Screen Shot 2021-11-02 at 2 56 00 PM" src="https://user-images.githubusercontent.com/387249/139958667-d052db35-3635-449c-b7a4-02d896f89be4.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 2 48 36 PM" src="https://user-images.githubusercontent.com/387249/139958662-b89c8536-5f7c-49a1-a937-18bb8bb31220.png"> | <img width="1777" alt="Screen Shot 2021-11-02 at 2 58 25 PM" src="https://user-images.githubusercontent.com/387249/139958672-d5b05432-e9f7-4df6-b0f4-eeacfb4d0ed3.png"> | <img width="1777" alt="Screen Shot 2021-11-02 at 2 58 42 PM" src="https://user-images.githubusercontent.com/387249/139958676-40c21a45-6c70-4223-adbe-37b48164ecc5.png"> | <img width="1525" alt="Screen Shot 2021-11-02 at 2 59 40 PM" src="https://user-images.githubusercontent.com/387249/139958681-675c9e7a-185a-4a1a-a6ea-3a1e6fc05ea6.png"> | <img width="1538" alt="Screen Shot 2021-11-02 at 2 59 53 PM" src="https://user-images.githubusercontent.com/387249/139958682-55ce24b9-88cc-4432-ab83-07f5462bff4e.png"> | <img width="1538" alt="Screen Shot 2021-11-02 at 3 00 25 PM" src="https://user-images.githubusercontent.com/387249/139958683-7a062e74-8202-4ad0-8910-43ce135d3071.png"> | <img width="1538" alt="Screen Shot 2021-11-02 at 3 00 40 PM" src="https://user-images.githubusercontent.com/387249/139958685-9e989df0-f3bf-4e24-a6e8-ede1f94862f8.png">


```
[13824:259:1102/150429.523689:VERBOSE1:ad_rewards.cc(301)] Retry reconciling ad rewards
[13824:259:1102/150429.523883:VERBOSE1:ad_rewards.cc(218)] Reconcile ad rewards
[13824:259:1102/150429.523972:VERBOSE1:ad_rewards.cc(226)] GetPayments
[13824:259:1102/150429.524048:VERBOSE2:ad_rewards.cc(227)] GET /v1/confirmation/payment/{payment_id}
[13824:259:1102/150429.526024:VERBOSE6:ad_rewards.cc(231)] URL Request:
  URL: https://ads-serve.bravesoftware.com/v1/confirmation/payment/e7593781-e2b6-4aef-9348-7ca1b0cc29ee
  Method: kGet
[13824:259:1102/150429.727059:VERBOSE1:ad_rewards.cc(240)] OnGetPayments
[13824:259:1102/150429.727166:VERBOSE6:ad_rewards.cc(242)] URL Response:
  URL: https://ads-serve.bravesoftware.com/v1/confirmation/payment/e7593781-e2b6-4aef-9348-7ca1b0cc29ee
  Response Status Code: 200
  Response: [{"month":"2021-11","transactionCount":"2","balance":"0.02"}]
[13824:259:1102/150429.728382:VERBOSE1:ad_rewards.cc(263)] Successfully reconciled ad rewards
```
```
[13824:259:1102/150022.003721:VERBOSE1:redeem_unblinded_payment_tokens.cc(80)] RedeemUnblindedPaymentTokens
[13824:259:1102/150022.003791:VERBOSE2:redeem_unblinded_payment_tokens.cc(89)] PUT /v1/confirmation/payment/{payment_id}
[13824:259:1102/150022.003989:VERBOSE6:redeem_unblinded_payment_tokens.cc(99)] URL Request:
  URL: https://ads-serve.bravesoftware.com/v1/confirmation/payment/e7593781-e2b6-4aef-9348-7ca1b0cc29ee
  Content: {"payload":"{\"paymentId\":\"e7593781-e2b6-4aef-9348-7ca1b0cc29ee\"}","paymentCredentials":[{"credential":{"signature":"zLgXJKWWIps9f8PKMPt5vnfPOqaJpEu/8hTvYLKM7+Du7il5y/xIh8XXI/eWdxbJ8d4xBHpGAgAq7N8dAtWENw==","t":"PTr8rTYyxxinEwvIi/BrpKrGTaZ6TL2l1bxUkiDVwfw43ef6pheTmzr/JRFy7NS+e+ojY34g6uNKOEqgx4whlw=="},"publicKey":"/DzrvcA+Ob40JPiCtbnsYQzYitesf2qfD8cb2A4eQUo="},{"credential":{"signature":"7rREuHFpEYMjkHtaL+HAo+hp1TMw8o6b6bfmbsVif7VOLUa5ABRhaCo6gumRm8sTrsT4HalBqYtDXwn2XJp7Wg==","t":"1ZjWbX0d9xMjqsI95Ai0U22J2nm7Dj/EK6YwKK87mwTJmF0LQTIJ/FrfYI9ImfTcrsWipXuyGKrx3r9sDaKukw=="},"publicKey":"6JgWYjDtDWAzMSfXFLNEbP5h2q+hZabhX9/DmKkl5Rg="},{"credential":{"signature":"cPuuSW9WSHqmcAL0UFH7+OsWL5GQp9jWcmxr5JL0UaCFajYlS0GFcqsElnKHrTkEETxfVaF7XlTFmi7MyJzF+w==","t":"fgFl4VuUdHt/DMKBGEbaC9DrVfHLG1woZUnHtIbYJYCF2q6fP3gc8ErCDlc28DM0cBb6i2KLm8k0luJ9WJMSFg=="},"publicKey":"/DzrvcA+Ob40JPiCtbnsYQzYitesf2qfD8cb2A4eQUo="}]}
  Content Type: application/json
  Method: kPut
[13824:259:1102/150022.183619:VERBOSE1:redeem_unblinded_payment_tokens.cc(110)] OnRedeemUnblindedPaymentTokens
[13824:259:1102/150022.183733:VERBOSE6:redeem_unblinded_payment_tokens.cc(112)] URL Response:
  URL: https://ads-serve.bravesoftware.com/v1/confirmation/payment/e7593781-e2b6-4aef-9348-7ca1b0cc29ee
  Response Status Code: 200
  Response: {"status":"ok"}
[13824:259:1102/150022.184318:VERBOSE1:account.cc(193)] Successfully redeemed unblinded payment tokens
```
