### ISSUE TITLE
Blank New Tab Page

### ISSUE THREAD

**Issue by krmbzds** [brave/brave-browser#1872]
## Description 

There is no way to disable Brave's new tab template.

## Steps to Reproduce

   1. Open Brave Browser
   2. Open a New Tab

## Actual result:

- Browsing Stats
- Time in 12 hour format
- Most Visited Web Pages
- A Random Wallpaper
- Author and Location Information for the Wallpaper
- Icons for Settings, Bookmarks and History

## Expected result:

- A blank page.

## Reproduces how often: 

Every time a new tab is opened.

## Additional Information

I tried a couple of Blank New Tab extensions and they didn't work.

## Extra Information

Things I hate:
- Seeing stats on every new tab page
- 12 hour time formats
- Random Wallpapers
- Irrelevant Information
- Unnecessary Shortcut Icons

Things I like:
- Simplicity
- Minimalism
- Peace of Mind

## Thank You

Most of my initial problems are solved since the Chromium fork and I switched back to Brave. New tab is the only nuisance left. Other than that, I can say Brave is the perfect browser for me now.

Thank you for the **amazing** work!

 ❤️💛💚💙💜

**Comment by Jacalz** [comment]
Kind of relevant to this issue is the fact that you can’t set a website as you newtab

**Comment by krmbzds** [comment]
> Kind of relevant to this issue is the fact that you can’t set a website as you newtab

Yes, and [all the extensions](https://chrome.google.com/webstore/category/collection/customize_your_new_tab_page) that rely on overriding `chrome://newtab` won't work as well.

**Comment by srirambv** [comment]
Extension override on new tab is a known issue and being tracked here https://github.com/brave/brave-browser/issues/993. Added a +1 there.

**Comment by timl206** [comment]
Still not fixed eh? I'm using the old version of Brave browser because of this issue, I really don't like to see photos every time I open a new tab, it's distracting.

**Comment by rmacnutt** [comment]
Add me to the list of folks who want a blank new tab feature.
The pictures are decent, but I just don't like seeing them every time.  I'm one of those people who turns off all the user interface "enhancements" in Windows and sets my background to a solid color.  If I want to look at art, I'll visit a museum.
