### ISSUE TITLE
reward wallet only support Gemini and Uphold, but user can't regist account in China

### ISSUE THREAD

**Issue by fanux** [brave/brave-browser#18733]
![image](https://user-images.githubusercontent.com/8912557/137064131-96599325-9b6c-4487-aebe-ce9f610a3483.png)

Why can't support brave wallet?

![image](https://user-images.githubusercontent.com/8912557/137064246-742b4a06-7579-451b-83a4-d5784959ee12.png)

If support brave wallet, we needn't care about Gemini and Uphold any more. If not, we can't use the website reward.

Brave is awesome, we want join it.

**Comment by Miyayes** [comment]
Thanks, we'll see if we introduce a custodian that supports China in future.

**Comment by fanux** [comment]
Why not support brave wallet directly? For regulatory requirements or tax?
