### ISSUE TITLE
Searches & Redirects based from Google are redirected incorrectly

### ISSUE THREAD

**Issue by tcampbPPU** [brave/brave-browser#18734]
## Description 

When doing Google searches with quick search or clicking on links from Google i.e. Google Calendar: Links are not properly redirecting.
For example When I am in Google calendar and clicking on Zoom meeting link it redirects me to:
```
https://www.bing.com/search?q=https%3A%2F%2Fus02web.zoom.us%2Fj%2F77112551586%3Fpwd%3DaUpWalVzWnlxSjZaeTdHbU11SlY4Zz09&pc=0AGL&ptag=C24N1AA57877ED9B&form=CONBNT&conlogo=CT3210127
```
Also similar is happening when I do quick search in new Brave Browser tab. I get redirected to bing.

But my settings are configured to use DDG.
![image](https://user-images.githubusercontent.com/25044744/137064460-9dcd78e2-01ee-4a94-984d-7611c4c9d0cb.png)

This appears to only happen with anything revolving google, I can do same quick search with 
`:br speedtest` and I do not get same result as issue with google.

But very strangely it does not happen when using browser in private mode.. 

## Steps to Reproduce

For Google Calendar
   1. Open `https://calendar.google.com`
   2. Click on Zoom meeting invite
   3. Gets redirected to Bing instead of opening Zoom application

For Google Quick Search
   1. Open new tab
   2. type in quick search `!g speedtest`
   3. Gets redirected to Bing instead of google

## Actual result:

**Clicking on Zoom link**
![image](https://user-images.githubusercontent.com/25044744/137063466-9590e4db-de06-4ded-89e3-b7674b3af969.png)
**With quick search**
![image](https://user-images.githubusercontent.com/25044744/137063842-0d1732f8-ba56-4bd8-841d-e9ec72a2bb46.png)
![image](https://user-images.githubusercontent.com/25044744/137063891-11a6d9dd-2647-4ebc-8847-867a2857e7d2.png)

https://user-images.githubusercontent.com/25044744/137064743-086986a5-6aba-4991-a5a1-d91e8c4895b9.mp4

## Expected result:
When I do quick search I expect to be redirected to that search engine. i.e. Google

When clicking on Zoom link from Google calendar I expect it to open my Zoom application

## Reproduces how often: 
Every time I do either
- Quick Search
- Open Zoom invite from Google Calendar

## Brave version (brave://version info)

```
Brave | 1.32.56 Chromium: 95.0.4638.40 (Official Build) nightly (64-bit)
-- | --
Revision | e3e7c76ba0284b16087cf4cf3153abfaef6470c7-refs/branch-heads/4638@{#624}
OS | Linux
JavaScript | V8 9.5.172.17
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.40 Safari/537.36
Command Line | /opt/brave.com/brave-nightly/brave --disable-client-side-phishing-detection --disable-domain-reliability --disable-features=InterestCohortAPIOriginTrial,ConversionMeasurement,FledgeInterestGroups,DirectSockets,TrustTokens,NavigatorPluginsFixed,SignedExchangeSubresourcePrefetch,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,IdleDetection,SignedExchangePrefetchCacheForNavigations,NetworkTimeServiceQuerying,SubresourceWebBundles,FederatedLearningOfCohorts,PrivacySandboxSettings,FirstPartySets,AutofillServerCommunication,LiveCaption,CopyLinkToText,InterestCohortFeaturePolicy,WebOTP,NotificationTriggers,LangClientHintHeader,TextFragmentAnchor,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,ReadLater --enable-crashpad --enable-dom-distiller --enable-features=WebUIDarkMode,LegacyTLSEnforced,DnsOverHttps,SafetyTip,AutoupgradeMixedContent,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --lso-url=https://no-thanks.invalid --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --variations-server-url=https://variations.brave.com/seed --enable-crashpad --component-updater=url-source=https://go-updater.brave.com/extensions --enable-features=ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,LegacyTLSEnforced,DnsOverHttps,SafetyTip,AutoupgradeMixedContent,WebUIDarkMode --disable-features=AppDiscoveryRemoteUrlSearch,ComputePressure,PrivacySandboxSettings2,ReadLater,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,TextFragmentAnchor,NotificationTriggers,WebOTP,LangClientHintHeader,SubresourceWebBundles,NetworkTimeServiceQuerying,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,DirectSockets,TrustTokens,NavigatorPluginsFixed,SignedExchangeSubresourcePrefetch,IdleDetection,LiveCaption,TabGroupsFeedback,AutofillServerCommunication,InterestCohortFeaturePolicy,CopyLinkToText,SettingsLandingPageRedesign,FledgeInterestGroups,SignedExchangePrefetchCacheForNavigations,PrivacySandboxSettings,FederatedLearningOfCohorts,ConversionMeasurement,FirstPartySets,InterestCohortAPIOriginTrial --flag-switches-begin --disable-gpu-rasterization --flag-switches-end
Executable Path | /opt/brave.com/brave-nightly/brave
Profile Path | /home/user/.config/BraveSoftware/Brave-Browser-Nightly/Default
Variations | AdRewardsStudy:NextPaymentDayAdServingStudy:MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=8/MaximumInlineContentAdsPerDay=40AdvertiserSplitTestStudy:GroupBBraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.ShowCustomAdNotificationOnLinuxStudy:EnabledBraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5BraveTalkStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledExtendedVariationsSafeMode:WriteSynchronouslyViaPrefServiceNativeCosmeticFilteringStudy:EnabledOperationalPatternsCollectionStudy:DisabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeStudy:Enabled
```

## Version/Channel Information:

I am on Brave nighly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? -- No
- Does the issue resolve itself when disabling Brave Rewards? -- No
- Is the issue reproducible on the latest version of Chrome? -- No

## Miscellaneous Information:
I am on:
OS: Ubuntu 20.10 x86_64
Kernel: 5.11.0-7620-generic
CPU: Intel i7-10750H (12) @ 5.000GHz

**Comment by rebron** [comment]
@tcampbPPU Can you disable your extensions and see if that's the issue? I suspect one of the extensions you've installed may have messed with your search settings to use bing.com

**Comment by tcampbPPU** [comment]
> @tcampbPPU Can you disable your extensions and see if that's the issue? I suspect one of the extensions you've installed may have messed with your search settings to use bing.com

So strange.. I didn't have issue before, and I haven't changed my extension in quite awhile but when I disabled `Color Picker` my problem with random redirects where solved!

![image](https://user-images.githubusercontent.com/25044744/138022834-84b4b0c9-6375-4866-8638-9d8a269dd2ae.png)

Thank you for this!! My issue is now resolved!
