### ISSUE TITLE
Add sitehacks and cosmetic filters from browser-laptop

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1874]
There's a number of cosmetic filters and sitehacks that browser-laptop had which we don't have on brave-core. This issue is to track adding them back in.

Cosmetic filters for removing blank spaces:
https://www.washingtonpost.com/*
https://www.youtube.com/*
https://coinmarketcap.com/*
https://www.yahoo.com/*

Cosmetic filters for marketwatch to remove some forever loading banners.
https://www.marketwatch.com/*

Sitehack for inserting some cookies for glennbeck.com to not show a blank overlay
https://www.glennbeck.com/*

**Comment by LaurenWags** [comment]
@bbondy when testing this, is it enough to do the following or are additional tests needed?
* Verify no large blank spaces on the following sites (check several pages/articles on each): https://www.washingtonpost.com/*, https://www.youtube.com/*, https://coinmarketcap.com/*, https://www.yahoo.com/*
* Verify no eternally loading banners displayed on https://www.marketwatch.com/* (check several pages/articles)
* Verify no blank overlay displayed on https://www.glennbeck.com/* (check several pages)

**Comment by bbondy** [comment]
@LaurenWags yep sounds good.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified items in https://github.com/brave/brave-browser/issues/1874#issuecomment-436070397

**Comment by srirambv** [comment]
@bbondy The banner on Yahoo is only removed for US based IP. When I use other IP's I can see the empty banner space on the home page. Is this ok ?
