### ISSUE TITLE
U2F Not Working

### ISSUE THREAD

**Issue by WeirdOrange** [brave/brave-browser#1875]
## Description 

U2F does not work anywhere, prompts time out or runs forever.

## Steps to Reproduce

   1. Go to the [Yubico U2F demo](https://demo.yubico.com/u2f)
   2. Register for an account
   3. Try to register a Yubikey

## Actual result:

![image](https://user-images.githubusercontent.com/6020546/47612447-bf282f00-dace-11e8-919a-6edcd3c42980.png)

Prompt for a key times out or runs forever. Additionally, the indicator on the key will not activate. On Yubikeys, this will result in no uniform blinking.

## Expected result:

U2F key successfully registers or allows user to log in.

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave Dev  |   0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
------------|-------------
Revision     |   9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS             |   Windows 10 (Build 18262)

Brave       |   0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-----------|-------------
Revision   |   9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS           |   Windows 10 (Build 18262)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
  -  This occurs on **dev** and **stable**

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
  - **No**
- Is the issue reproducible on the latest version of Chrome? 
  - **No**. Chromium (71.0.3576.0, not Brave) behaves correctly.

### Additional Information

Also tested with GitHub, Google, and Login.gov (which uses WebAuthn) with the same results.

I installed regular Brave just to test, so it's a fresh install.

I am also aware of #324, but unlike that issue, there are no errors in the console and prompts seem to run forever or until they time out instead of being interrupted.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.3 x64` using the following build:

Brave | 0.61.50 Chromium: 73.0.3683.67 (Official Build) (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Mac OS X

* Went through https://demo.yubico.com/webauthn/ and ensured I can register and login using yubikey

Verification **PASSED** on `Mint 19.1 x64` using the following build:

Brave | 0.61.50 Chromium: 73.0.3683.67 (Official Build) (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Linux

* Setup my system using https://support.yubico.com/support/solutions/articles/15000006449-using-your-u2f-yubikey-with-linux
* Went through https://demo.yubico.com/webauthn/ and ensured I can register and login using yubikey

Verification **PASSED** on `Windows 10 x64` using the following build:

Brave | 0.61.50 Chromium: 73.0.3683.67 (Official Build) (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows

* Went through https://demo.yubico.com/webauthn/ and ensured I can register and login using yubikey

**Comment by kjozwiak** [comment]
Adding the `release-notes/exclude`, will use https://github.com/brave/brave-browser/issues/3558 as the main issue for the release notes.
