### ISSUE TITLE
DNS Leak When Using Socks5 Proxy

### ISSUE THREAD

**Issue by jimsmt** [brave/brave-browser#18759]
## Description 

Brave is leaking local DNS when using socks proxy

## Steps to Reproduce

   1. Use the SwithcyOmega extension to set proxy to a local socks5 proxy
   2. Vist https://browserleaks.com/dns to test

## Actual result:

Results show that local DNS is leaked

## Brave version (brave://version info)

Brave | 1.30.89 Chromium: 94.0.4606.81 (Official Build) (64-bit)
Revision | 5a03c5f1033171d5ee1671d219a59e29cf75e054-refs/branch-heads/4606@{#1320}
OS | Windows 10 Version 1809 (Build 17763.2237)

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome? 
No, tested on latest version of Chrome and other Chromium based browsers

**Comment by gitgayhub** [comment]
Also tested on latest lightly version: Nightly v1.33.6, same issue

**Comment by gitgayhub** [comment]
I can confirm that this issue exists from version 1.17 to latest 1.33, version older than 1.16 doesn't have this problem
