### ISSUE TITLE
Add Google's new iOS URL parameters to the query string filter

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#18758]
Google has [announced two new URL parameters for iOS 14](https://support.google.com/google-ads/answer/10417364): `gbraid` for deep linking into apps, and `wbraid` for web links originating from an app. They claim that these new parameters comply with Apple's new privacy guidelines and that they therefore do not require asking for permission via the [App Tracking Transparency](https://developer.apple.com/documentation/apptrackingtransparency).

Since these parameters replace the [Google Click Identifier (`gclid`)](https://support.google.com/google-ads/answer/9744275) which we block and which is against [Apple's tracking rules](https://developer.apple.com/app-store/app-privacy-details/#user-tracking), we should consider blocking these new parameters.

[According to Google](https://blog.wickedreports.com/gclids-gbraids-wbraids-what-is-going-on), `wbraid` uses:
> - Aggregation techniques that only use the parameter when a group of users complete a similar conversion path e.g; campaign ID
> - De-identification techniques that ensure cross-site behavior cannot be tied back to a user’s identity

Campaign-level parameters are [out-of-scope](https://github.com/brave/brave-browser/wiki/Query-String-Filter) for the Brave query filter, but until more details about their aggregation and de-identification schemes are published, it may be safer to strip these out.

Some examples in the wild:
- https://free-now.com/crossborder-summer-2021/?wbraid=CjsKCQjw9aiIBhCoARIqAN3tgvtTQJCGK6Ss562obXyiTxy4UyI-d9Q4lNXjjLzmml1Xt3cucnLcGgJsxA&cHash=ba5defe1bdf6ca89ca08f4e4f7ebd197
- https://www.watchnow.com/show/destination-truth?wbraid=CjgKCAjw_8mHBhAoEigAVbKN5cWh1MTC5OijgaOyK-2dsBJKFGc6IrZjNP6MVjqpAXURzd9BGgK6LQ&utm_source=Google&utm_medium=Search&t_source=64&utm_campaign=2557
- https://food52.com/shop/collections/our-greatest-hits?page=2&wbraid=CjsKCQjwkZiFBhDLARIqAOHz7u8H_TauLC37F_yEFkjNJDc0eIEdmcWMmGUun_3kONAsSDVt3u1_GgJdnQ

**Comment by fmarier** [comment]
Also being discussed on https://github.com/privacycg/nav-tracking-mitigations/issues/11

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.57 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. opened `https://brave.com/?untouched=yes` and confirmed the query-string parameter `?untouched=yes` remains in the URL bar
4. opened `https://brave.com/?wbraid=foo` and confirmed the query-string parameter `?wbraid=foo` gets dropped from the URL bar
5. opened `https://brave.com/?gbraid=bar` and confirmed the query string parameter `?gbraid=foo` gets dropped from the URL bar

`?untouched=yes` | `?wbraid=foo` | `?gbraid=bar`
-----------------------------------|---------------------------------|------------------------------
<img width="1312" alt="Screen Shot 2021-11-03 at 11 18 11 AM" src="https://user-images.githubusercontent.com/387249/140169880-ed5a5f37-f7e6-4131-877e-70cf8c133cba.png"> | <img width="1312" alt="Screen Shot 2021-11-03 at 11 18 49 AM" src="https://user-images.githubusercontent.com/387249/140169890-610dded6-c5ad-4f90-bf34-54cacf7604b6.png"> | <img width="1312" alt="Screen Shot 2021-11-03 at 11 19 14 AM" src="https://user-images.githubusercontent.com/387249/140169895-e47dc298-1948-454f-b0ec-95b82684542c.png">

**Comment by stephendonner** [comment]
Verified `PASSED` on Android 9, using Brave `1.33.69, Chromium 96.0.4664.35` on a Google Pixel XL.

`?untouched=yes` | loaded | `?wbraid=foo` | loaded | `?gbraid=foo` | loaded
---------|----------|---------|----------|---------|----------
![Screenshot_20211108-154748](https://user-images.githubusercontent.com/387249/140836583-d33d2a7c-cd38-49ce-b0b5-ae0b245445e5.png) | ![Screenshot_20211108-154755](https://user-images.githubusercontent.com/387249/140836585-de510a59-fc5d-4e87-a256-462521dd9e06.png) | ![Screenshot_20211108-154814](https://user-images.githubusercontent.com/387249/140836622-b0eac975-562f-42f3-9226-c2b22c380ac9.png) | ![Screenshot_20211108-154820](https://user-images.githubusercontent.com/387249/140836625-47a24277-b931-48e8-aa5e-ff88343904f5.png) | ![Screenshot_20211108-154847](https://user-images.githubusercontent.com/387249/140836626-961692a1-deb4-4d21-a3e4-474584949fb8.png) | ![Screenshot_20211108-154852](https://user-images.githubusercontent.com/387249/140836628-13bce400-7545-4906-ae76-50dfe23aa9ef.png)
