### ISSUE TITLE
Parse swap transactions and provide additional details in TransactionInfo

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#18767]
Following the UX refresh of transaction history (see https://github.com/brave/brave-core/pull/10511), we would like to have additional information about a Swap transaction. This is how it looks like right now.

<img width="1225" alt="swap" src="https://user-images.githubusercontent.com/3684187/137318295-f6d48928-117d-49a0-9ef5-433bce4cb0cc.png">

In particular, we need:
* An additional `TransactionType` enum field for swap.
* The From and To assets.
* The From amount.
* Optional: The To amount
* Optional: the taker address if it exists - it's possible to swap from one asset to another, while specifying a different destination address.

**Comment by srirambv** [comment]
Blocked on https://github.com/brave/brave-browser/issues/23443 as the issue happens on 1.40.x as well. We'll need an uplift of https://github.com/brave/brave-core/pull/13790 to 1.40.x

**Comment by onyb** [comment]
Uplift created here: https://github.com/brave/brave-core/pull/13797

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12797>brave/brave-core#12797</a></li>
         <li>Verified transaction details are shown for <code>ETH-> ERC20</code>, <code>ERC20-> ERC20</code> & <code>ERC20-> ETH</code> transactions</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/174543541-93af505d-b565-4e0c-8a64-44bf6616012b.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/174542297-0112050a-9c1f-48c0-b0be-66ce0449b0cb.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/174543747-7ff98ff1-4877-43f7-990c-46745b813bd5.png>
      </td>
   </tr>
</table>
