### ISSUE TITLE
Page background paints as white before image loads on New Tab Page.

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#1876]
## Description 
Page background paints as white before image loads on New Tab Page. This is most apparent when using Mac OS Mohave in Dark Mode.

## Steps to Reproduce

   1. Set Dark Mode on Mac OS Mohave
   2. Set Brave Colors to Dark
   3. Make new tabs and notice the page background paint in as white before BG image loads 

## Actual result:
seemingly unnecessary white flash of the entire page area.

## Expected result:
"Black Flash" or none by preloading the image or or a different approach to eliminate the visible page background draw. 

## Reproduces how often: 
every time

## Brave version (brave://version info)
Version 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)

**Comment by mashuma** [comment]
This is extremely annoying behaviour.
Any workaround until it is fixed would be much appreciated!

Can be reproduced on Version 0.57.4 (Dev)

**Comment by LaurenWags** [comment]
I don't have Mojave on macOS, but it's still happening for me with Brave using dark colors. You can kind of see it in this gif:
![1876](https://user-images.githubusercontent.com/28145373/52650031-721e6c00-2eb7-11e9-95dc-57957bce4fcc.gif)

@kjozwiak can you check your macOS with mojave when you get a chance?

**Comment by LaurenWags** [comment]
Verified with

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Logged follow up issue #3362 since I'm still seeing a white flash before new tab page loads.

**Comment by kjozwiak** [comment]
Checked this with @LaurenWags while we were on a call together as I'm running Mojave. Still seeing the "white flash" when opening new tabs. Also seeing a "white flash" whenever switching between `brave://newtab` tabs. Example of the issue:

![switchingtabs](https://user-images.githubusercontent.com/2602313/52830045-04339980-309d-11e9-811a-a5b4c87a8757.gif)

Used the following build:

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

@rossmoody @bradleyrichter seems like this is still an issue as per the above example. I don't think we're going to fix this in time for `0.60.x` so @LaurenWags opened https://github.com/brave/brave-browser/issues/3362 as a follow up as there's code that already landed in this issue so we're not going to re-open unless we try fixing this in this issue by Monday-Tuesday.
