### ISSUE TITLE
Brave snap doesn't work without `--no-sandbox` on systems with CONFIG_USER_NS_UNPRIVILEGED disabled

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#18768]
```console
% zgrep CONFIG_USER_NS /proc/config.gz
CONFIG_USER_NS=y
# CONFIG_USER_NS_UNPRIVILEGED is not set
% snap run brave
[2205850:2205850:1014/153436.343633:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! You probably need to enable user namespaces in your kernel. See https://brave.com/linux for more info.
[1014/153436.343935:ERROR:process_memory_linux.cc(42)] open: Permission denied (13)
/snap/brave/133/opt/brave.com/brave/brave-browser: line 48: 2205850 Trace/breakpoint trap   (core dumped) "$HERE/brave" "$@"
%
```

This affects users of the linux-hardened kernel on Arch Linux, among others. From https://wiki.archlinux.org/title/Security#Sandboxing_applications:
> Warning: Unprivileged user namespace usage (CONFIG_USER_NS_UNPRIVILEGED) is enabled by default in linux (5.1.8 or later), linux-lts (4.19.55-2 or later) and linux-zen (5.1.14.zen1-2 or later) unless the kernel.unprivileged_userns_clone sysctl is set to 0. Since this greatly increases the attack surface for local privilege escalation, it is advised to disable this manually, or use the linux-hardened kernel. For more information see FS#36969.

This does not affect the non-snap version of the browser:
![image](https://user-images.githubusercontent.com/1129003/137329176-332de11a-8034-4675-b706-143c1e327f76.png)

Related: https://github.com/brave/brave-browser/issues/18723
Slack thread: https://bravesoftware.slack.com/archives/CG7GV6M7Z/p1634147626023000?thread_ts=1634046675.021500&cid=CG7GV6M7Z

**Comment by fmarier** [comment]
> The question is whether we even want to make changes to the package, so it works on systems with `CONFIG_USER_NS_UNPRIVILEGED=n`, or not. This would introduce the setuid sandbox binary, which was previously not included.

Is there any reason not to apply the above patch? I'm not saying it should be a priority to debug and support this use case given that the regular packages work fine on Arch, but at the same time, we don't need to explicitly disable it.

**Comment by fmarier** [comment]
There's an interesting comment here about the same work-around for another browser sandbox: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brave-bin#n51

**Comment by wknapik** [comment]
> Is there any reason not to apply the above patch? I'm not saying it should be a priority to debug and support this use case given that the regular packages work fine on Arch, but at the same time, we don't need to explicitly disable it.

It would require fixing all the new problems it causes, but also introduces a suid binary, where there previously wasn't one.

**Comment by fmarier** [comment]
> So this also affects the -beta and -nightly packages from AUR (on systems with CONFIG_USER_NS_UNPRIVILEGED=n, such as Arch with linux-hardened).

That looks like a bug in the Arch packaging of these versions.

**Comment by wknapik** [comment]
On Arch hardened
```console
% uname -a                                         
Linux whatever 6.0.6-hardened2-1-hardened #1 SMP PREEMPT_DYNAMIC Sun, 30 Oct 2022 14:45:27 +0000 x86_64 GNU/Linux
% zgrep CONFIG_USER_NS_UNPRIVILEGED /proc/config.gz
# CONFIG_USER_NS_UNPRIVILEGED is not set
%
```
the snap package appears to be broken
```console
% sudo snap remove brave
% sudo snap install brave
brave 1.45.118 installed
% snap run brave          
/snap/brave/185/bin/desktop-launch: line 16: 1871364 Floating point exception(core dumped) $@
ERROR: /snap/brave/185/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders exited abnormally with status 136
/snap/brave/185/bin/desktop-launch: line 448: 1871368 Floating point exception(core dumped) $1/glib-2.0/gio-querymodules $GIO_MODULE_DIR
/snap/brave/185/bin/desktop-launch: line 16: 1871389 Floating point exception(core dumped) $@
ERROR: /snap/brave/185/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 exited abnormally with status 136
ERROR: compile_giomodules /snap/brave/185/usr/lib/x86_64-linux-gnu exited abnormally with status 136
cat: error while loading shared libraries: cat: unsupported version 0 of Verneed record
cat: error while loading shared libraries: cat: unsupported version 0 of Verneed record
%
```
but works (including sandboxing) with the changes from https://github.com/brave/brave-browser-snap/pull/18
```console
% sudo snap remove brave
% sudo snap install ./brave_1.45.118_amd64.snap --dangerous --devmode
brave 1.45.118 installed
% snap run brave
[works fine]
```
