### ISSUE TITLE
Bookmarks do not get synced successfully in any android version of Brave browser.

### ISSUE THREAD

**Issue by FahimFBA** [brave/brave-browser#18778]
## Description 

I can't get/access the bookmarks which I have on my Desktop on my android phones. I tried in several ways to get all the bookmarks on my android phone. enabling syncing with the same sync code and so on. Nothing resolves the issue at all. 

## Steps to reproduce 

   1.  Simply install a brave browser from the Google Play Store to any android smartphone.
   2.  Enable the sync by using the same sync code with your PC
   3.  Go to the bookmark in your android app of Brave. You will get nothing there.

## Expected result

We should get all the bookmarks we have on other devices (especially from our PC).

## Issue reproduces how often 

It reproduces always.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? - **YES**
- Can you reproduce this issue with the current Play Store Beta version? -  **YES**
- Can you reproduce this issue with the current Play Store Nightly version? - **YES**

## Device details
   - Install type (x86):
   - Device type (Phonet):
   - Android version: 10
   
## Brave version
1.30.87

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? - **No**
- Does the issue resolve itself when disabling Brave Rewards? - **No**
- Is the issue reproducible on the latest version of Chrome? - **Chrome doesn't have this type of issue at all.**

**Comment by vrindavan** [comment]
I am waiting for the same for ages. They should work on this now. Cannot access bookmarks from one device to another is just a simple thing that is not here.
