### ISSUE TITLE
Brave window is permanently minimized

### ISSUE THREAD

**Issue by BeeGaat** [brave/brave-browser#18773]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@BeeGaat We need more information. If you can fill out the template we can try and address, otherwise, we'll need to close out this issue. You can also connect with us on https://community.brave.com for these issues.
