### ISSUE TITLE
Detect if Brave Ads native/system notifications are enabled before serving ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#18799]

**Comment by UndarkAido** [comment]
Is this just going to render #18798 a null issue?

**Comment by tmancey** [comment]
Blocked because Chromium does not use the latest Apple APIs (unless enabling via a flag) and due to requiring a patch. Further discussions needed.

**Comment by tmancey** [comment]
Closing due to the transition to custom push notifications
