### ISSUE TITLE
Show ERC721TransferFrom transactions in the account transaction history

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#18805]
Currently UI does not show those transactions because it only show ETHSend and ERC20Transfer transactions, we should show ERC721TransferFrom transactions too.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.99 Chromium: 96.0.4664.35 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/10798>brave/brave-core#10798</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141446044-4042a709-920a-4e9c-9037-2a766dafdc83.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141446802-90e917d4-2ace-46f0-a519-9e2393b5bbd1.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141446263-ebe16533-3631-414b-b719-04bd835f7fa8.mov>
      </td>
   </tr>
</table>
