### ISSUE TITLE
Widevine should be Profile specific.

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#18811]
When I turn on widevine component, Why it gets turned on for all profiles in my browser and when I turn it off, Why it gets turned off for all profiles in my browser.
Suppose I stream Netflix on my 1st profile and do work related things on my 2nd profile then I want widevine to turn on only for Netflix profile and not for my work profile.

Steps to reproduce:-
Make a 2nd profile turn on widevine for that profile ,widevine gets turned on for both profiles. 
Turn off widevine for 2nd profile, widevine gets turned off for the 1st profile also.

Widevine should be profile specific, When I turn it on for 1 profile it shouldn't get turned on for all profiles. Same applies for turning it off.

![1](https://user-images.githubusercontent.com/89839714/137595577-102aa058-e067-4f4c-8fef-113448f262cf.png)

Thanks

**Comment by Nihal247** [comment]
@clicky6, not just Widevine, if you enable a separate DNS provider (Cloudflare in my case) in 1st profile, you'll have the same DNS provider in the second profile, but it's actually useful for me 😂. Don't know if this is a bug or Brave devs do it on purpose.

**Comment by clicky6** [comment]
@Nihal247 😂,Yes sometimes it's useful like in DNS case but not in WideVine case, Then there should be an option present to enable it for all profiles or for separate profiles like when clicking on Widevine in 1 profile, it should be enabled for that profile only and there should be a button given bellow that to enable or disable Widevine for all profiles, Same goes with DNS.

> ![1](https://user-images.githubusercontent.com/89839714/137595577-102aa058-e067-4f4c-8fef-113448f262cf.png)
> This option for enabling it for 1 profile.

AND ANOTHER OPTION BELOW THAT SAYING:-

> Enable or disable Widevine for all Profiles

SAME GOES WITH DNS...
Thanks...

> And just a quick question, How to insert labels in Issues. Because when I create a new issue there are only some label options. 
> ![6](https://user-images.githubusercontent.com/89839714/137613703-081d4424-8e98-4d61-9939-644d353935ab.png)
> Then, How do people add other issue labels than these?
>
