### ISSUE TITLE
Option to restrict internet access for Extensions.

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#18818]
### Add an Option to restrict internet access for Extensions.

This would help to stop extensions from accessing internet, It would be pretty much helpful when we use proprietary extensions that do not require internet but still use internet for collecting data and doing some nasty things like tracking and all .So It would be helpful, with this we would be able to use proprietary extensions without needing to worry about breaking privacy.

And If you ask why use proprietary extensions in the 1st place - Chrome Web Store is flooded with proprietary extensions and we are not able to find which are totally free extensions {(open source) & (according to fsf)} so we have no choice but to use proprietary extensions...

**Comment by rebron** [comment]
Closing as not actionable. Please use community.brave.com for suggestions and feedback like this one.
