### ISSUE TITLE
Media Assets Missing from Crypto Wallets

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#18810]
## Description 
Some image assets are missing from the Crypto Wallets repo (e.g. `./app/images/icons/connected-sites.svg`) which creates noticeable UI issues.

![image](https://user-images.githubusercontent.com/815158/137571918-f05c0dfc-ed7d-43ac-952c-1f9cb6c8ac04.png)

Many appear to have been removed by https://github.com/brave/ethereum-remote-client/pull/172.

## Brave version (brave://version info)
1.30.89

**Comment by kjozwiak** [comment]
Added `QA/No` after speaking with @srirambv 👍
