### ISSUE TITLE
Support upstream features override (in code) with ability to Griffin-override on top

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#18829]
The variations seed doesn't support features state apply at the first start. We can implement some `chromium_src`-based change to alter the default state of Chromium features and still be able to control it via Griffin. Our current approach with appending `--enable/disable-features` doesn't allow Griffin overrides.

Reasoning from @pes10k:
> Could we change our deployment to make the features enabled by default in code, and then use griffin to disable only if needed? I know that for users it wont make a difference, but it’ll be increasingly important to make sure researchers / bloggers / measurers accurately understand and can replicate the privacy protections we’re providing.

Note: this does not replace [`master_preferences`](https://github.com/brave/brave-browser/issues/15229). The problem with `master_preferences` is that it's not supported by `selenium-webdriver` for example. In reality, all experiments and research made with `selenium-webdriver` won't get the actual features state we're using in production.

**Comment by goodov** [comment]
For QA: please find few easy-to-check features from [the list](https://github.com/brave/brave-core/commit/4683f44b789c6cfdcf0d0e0f28dd85f3bf4d4a7f#diff-d87c87d69388153cc1341b8b763b08432c5a0b63ce8b6ff8c9b4cff91eefe156L213-L282) and make sure they are in the same state we want it to be.

**Comment by LaurenWags** [comment]
@brave/legacy_qa this is `QA/Blocked` until additional information is obtained from @kjozwiak

**Comment by LaurenWags** [comment]
Reference: https://bravesoftware.slack.com/archives/C01LKMP6X36/p1640713240108000

**Comment by goodov** [comment]
### Test cases
#### (1) Feature is enabled by default in Chromium, but disabled by default in Brave. Can be overridden via cmd line.
1. Ensure Brave doesn't have `Copy link to highlight` context menu item when a text on a website is selected and a context menu is triggered (mouse right click).
2. Start Brave with `--enable-features=CopyLinkToText`
3. Expect the menu item is available.

#### (2) Feature is disabled by default in Chromium, but enabled by default in Brave. Can be overridden via cmd line.
1. Ensure there is `Import passwords` item on `brave://settings/passwords` in `Saved Passwords` section (click the three-dots button on the right).
2. Start Brave with `--disable-features=PasswordImport`.
3. Expect the item has disappeared.

#### (3) Control Brave-overridden feature using `brave://flags`.
1. Ensure there is `Import passwords` item on `brave://settings/passwords` in `Saved Passwords` section, make sure to cleanup command line after running test case `#2`.
2. Open `brave://flags`, change `Password import` flag state, relaunch browser.
3. Expect the item exists or doesn't exist depending on the flag state.
4. Expect `Default` flag state shows the item.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.34.78 Chromium: 97.0.4692.71 (Official Build) (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 21H2 (Build 19044.1415)

```
