### ISSUE TITLE
Fix, or suppress cargo audit finding RUSTSEC-2020-0071 and RUSTSEC-2020-0159

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#18835]
[RUSTSEC-2020-0071](https://rustsec.org/advisories/RUSTSEC-2020-0071) affects release, beta and nightly channels.
[RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159) affects nightly.

Slack thread: https://bravesoftware.slack.com/archives/CA5FPHWLF/p1634550684493700
Blocker: https://bravesoftware.slack.com/archives/C8ZJB9F9B/p1634572288125800?thread_ts=1634560082.125300&cid=C8ZJB9F9B

**Comment by wknapik** [comment]
Looks like on nightly we have an additional finding - https://rustsec.org/advisories/RUSTSEC-2020-0159.

**Comment by rillian** [comment]
Re-opened by #11890; we have new uses in the SKU and rss-feed implementations.

**Comment by rillian** [comment]
Closing in favour of the new tracking issue.
