### ISSUE TITLE
[Chromium] Images cache partitioning doesn't work while a 3p renderer is alive

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#18831]
Looks like images are cached in the renderer and don't know anything about NIK areas. If we navigate the renderer away (for ex. to `example.com` to effectively destroy/clear cache) then the image is not found in the cache and refetched properly.

See https://privacytests.org/ `image cache` test.

~~Need to figure out how/if blink caches some simple blobs and make sure it supports NetworkIsolationKey-based partitioning there.~~

Blink indeed have MemoryCache, but it doesn't support partitioning out of the box. There is an open issue to implement this, but no signs of activity https://bugs.chromium.org/p/chromium/issues/detail?id=1127971.

**Comment by goodov** [comment]
For QA: nothing should be changed visually, but internal blink memory cache should behave differently for 3p frames. Can we please check the usual browser behavior regarding 3p frames and any frames in general hasn't changed and everything works as it should? The test plan will look like this:
1. Enable `PartitionBlinkMemoryCache` feature via command line.
2. Perform various tests from https://dev-pages.brave.software/storage/index.html
3. Perform an SSO authorization, make sure it works without any issues.

We'd like to have a QA approve for a general sanity so we can enable this in nightly.

**Comment by LaurenWags** [comment]
@goodov what's the command line QA needs to use?

**Comment by goodov** [comment]
> @goodov what's the command line QA needs to use?

`--enable-features=PartitionBlinkMemoryCache`

**Comment by LaurenWags** [comment]
@brave/legacy_qa this is `QA/Blocked` for now, don't test until additional information is provided by @kjozwiak

**Comment by kjozwiak** [comment]
Labelling this as `QA/No` as this was already verified on Nightly via https://github.com/brave/brave-variations/pull/168#issuecomment-987686685 before pushing to Nightly via Griffin. We're already at 100% on BETA as per https://github.com/brave/brave-variations/pull/187.
