### ISSUE TITLE
[Android] Set default Auto-Contribute amount to 1.0 BAT on Android (Oct 2021)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18834]
## Description

Currently, the default A-C amount is 5.0 BAT. On Desktop, it is dynamically fetched, and is currently 1.0 BAT.

## Solution

Change it to 1.0 BAT.

## Notes

This is likely related to how we currently don't dynamically fetch values from server, but these values are hardcoded: https://github.com/brave/brave-browser/issues/17070 The long term solution is to fetch dynamically. But in the short run, we should set to 1.0 BAT.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.89, Chromium 97.0.4692.71` on a `Google Pixel XL` running `Android 9.0.`

Steps:
1. installed `1.35.89`
2. launched Brave
3. tapped through onboarding
4. tapped on the 3-dots menu
5. tapped on `Settings`
6. tapped on `Developer options` a few times to unlock sekret menu
7. tapped on `QA Preferences`
8. entered the QA code
9. tapped to enable: `Use Rewards staging server`, `Maximize initial ads number`, and `Verbose Logs for Ad-Rewards`
10. tapped on the `X` at the top of `Settings`
11. loaded `brave.com`
12. tapped on the BAT icon
13. tapped to `Start using Brave Rewards`
14. tapped to claim UGP grant
15. tapped again on the BAT icon
16. confirmed `Monthly contribution` defaults now to `1 BAT`
17. tapped on `Send tip`
18. Filed https://github.com/brave/brave-browser/issues/20606 for the default being wrong, here
19. tapped on the `Settings` icon at the bottom of the Rewards panel
20. tapped on `View Details` under `Auto-Contribute`
21. confirmed `Monthly Payment` is set to `1.000 BAT (0.99 USD)`
22. tapped on the `Settings` icon
23. confirmed `Monthly Payment` is also set there to `1.000 BAT (0.99 USD)`

example | example | example | example | [issue 206060](https://github.com/brave/brave-browser/issues/20606)
---------|----------|---------|----------|---------
![Screenshot_20220120-113917](https://user-images.githubusercontent.com/387249/150411746-999cdc5f-85e2-4692-befa-8d85fe909f7f.png) | ![Screenshot_20220120-113849](https://user-images.githubusercontent.com/387249/150411794-6b7dedae-b931-45c6-9293-6328f1d3050d.png) | ![Screenshot_20220120-113906](https://user-images.githubusercontent.com/387249/150411825-a3f9f2ee-91a6-4957-84d4-5c51898fc506.png) |  ![Screenshot_20220120-113859](https://user-images.githubusercontent.com/387249/150411888-07c08f22-3eb6-457c-b10d-82649c046dc9.png) | ![Screenshot_20220120-113925](https://user-images.githubusercontent.com/387249/150412050-22b75296-c8b5-4ab3-86ea-aa02986c7425.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.93 x64 Beta build
- Verified default monthly payment value is set to 1BAT in AC settings
- Verified default value for dropdown under AC settings is set to 1BAT
- Verified default monthly contribution value is set to 1BAT in Rewards panel for publishers
- Encountered [#20200](https://github.com/brave/brave-browser/issues/20200)

 Monthly Payment Setting | AC settings | Panel (#20200)
 -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/151194494-10982566-b565-4167-8d1e-c7b7abbecf7e.png) | ![image](https://user-images.githubusercontent.com/17010094/151194527-d5ab6af0-9399-4f5d-91d8-0742cfe2f636.png) | ![image](https://user-images.githubusercontent.com/17010094/151194576-562e7e3e-02d3-4ace-9869-35bcaed2d855.png)
