### ISSUE TITLE
Review Strict-Transport-Security header partitioning in Chromium

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#18830]
`Strict-Transport-Security` header handler doesn't support partition logic unlike `Expect-CT`: [the first is not keyed by NIK, the second is keyed](https://github.com/chromium/chromium/blob/97.0.4666.1/net/http/transport_security_state.cc#L1300-L1311) (and controlled by `PartitionExpectCTStateByNetworkIsolationKey`).

Need to figure out if this is intentional or WIP.

**Comment by pes10k** [comment]
I think that sounds great, thanks!

**Comment by goodov** [comment]
related issues
https://github.com/brave/brave-browser/issues/3419
https://github.com/brave/brave-browser/issues/5936

**Comment by stephendonner** [comment]
@goodov mind putting up a test plan for QA, when you get a chance?  Thanks! ❤️

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.41.59 Chromium: 103.0.5060.42 (Official Build) nightly (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 12.5 (Build 21G5037d)

Case One: hsts.badssl.com
<details>

1. installed `1.41.59`
2. launched Brave
3. loaded `https://hsts.badssl.com/`
4. confirmed it's green with an  `HSTS is working` message
<img width="1434" alt="Screen Shot 2022-06-13 at 10 40 14 AM" src="https://user-images.githubusercontent.com/387249/173414847-4d17b763-9e1a-4bb1-8e19-dc2c87abe1fa.png">



</details>

Case Two: brave.com
<details>

1. installed `1.41.59`
2. launched Brave
3. opened Developer Tools
4. clicked on the `Network` panel
5. loaded `http://brave.com/`
6. confirmed it redirected to `https://brave.com/` with a `307 Internal Redirect`
<img width="1434" alt="Screen Shot 2022-06-13 at 10 43 09 AM" src="https://user-images.githubusercontent.com/387249/173414790-464bb76b-3a2a-43e0-ba68-8915677bba20.png">



</details>

**Comment by MadhaviSeelam** [comment]
Verification `In-Progress` using
```
Brave | 1.41.65 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

Case One: hsts.badssl.com - PASSED
<details>

1. installed `1.41.65`
2. launched Brave
3. loaded `https://hsts.badssl.com/` in default window
4. confirmed it's green with an  `HSTS is working` message
5. loaded `https://hsts.badssl.com/` in private/incognito window

default_window|private_window
---|---
<image width="950" alt="default" src="https://user-images.githubusercontent.com/98358127/173872503-94066123-161b-4605-b661-bb00911c6c3b.png">|<image width="950" alt="private"  src="https://user-images.githubusercontent.com/98358127/173876326-7611fbc3-452b-4f9c-8ff7-b40daf20399b.png">

</details>

Case Two: brave.com
<details>

1. installed `1.41.65`
2. launched Brave
3. opened Developer Tools
4. clicked on the `Network` panel
5. loaded `http://brave.com/`
6. confirmed it redirected to `https://brave.com/` with a `307 Internal Redirect`


<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/173873275-66b98694-01f9-469e-a5e3-1e9a4d91e754.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.77 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Linux




## Case One: `hsts.badssl.com`
<details>

### Steps
1. installed `1.41.77`
2. launched Brave
3. loaded `https://hsts.badssl.com/`
4. confirmed it's green with an  `HSTS is working` message



</details>

## Case Two: `brave.com`
<details>
### Steps
1. installed `1.41.77`
2. launched Brave
3. opened Developer Tools
4. clicked on the `Network` panel
5. loaded `http://brave.com/`
6. confirmed it redirected to `https://brave.com/` with a `307 Internal Redirect`



</details>
