### ISSUE TITLE
Add signTypedData keyring support in the new wallet

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#18833]
Add support for the signTypedData method, same as https://github.com/brave/brave-browser/issues/14705

**Comment by kjozwiak** [comment]
Will require `1.36.103` or higher.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.36.106 Chromium: 99.0.4844.45 (Official Build) (arm64)
-- | --
Revision | `edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}`
OS | macOS Version 12.1 (Build 21C52)

- Verified test plan from [brave/brave-core#12265](https://github.com/brave/brave-core/pull/12265)
- Verified able to sign messages using Ledger device
- Verified Trezor throws error of min version when trying to sign message

Note: Trezor worked while verifying the uplift on Nightly as mentioned in [brave/brave-core/#12265 (comment)](https://github.com/brave/brave-core/pull/12265#issuecomment-1047420040).  This is failing on Linux as well now so logged #21338 for further investigation

Ledger | Trezor
--  | --
<video src=https://user-images.githubusercontent.com/17010094/155725999-1c95d6cf-4aa3-4dcf-8ef1-4ed69ab085bc.mov> | <video src=https://user-images.githubusercontent.com/17010094/155726184-1234a62b-9fae-43b0-a6db-825918d56dfd.mov>

Checked with @spylogsster verification on one platform is sufficient
