### ISSUE TITLE
Allow users to disable Brave custom ad notification fallback from brave://flags

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#18846]

**Comment by Jurek54321** [comment]
>

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Ubuntu 18.04 LTS

It seems that the flag has no effect. Per our process I will log a follow up issue.
