### ISSUE TITLE
Import additional data related to referral promo and retention tracking for continuity with Muon

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#1884]
In addition to importing the promoCode, we need to import the the following data when importing from Muon to Brave-core:

-- Date of install for referral promo-- this is used to determine the date of the 30-day realization ping for browsers installed via referral promo. The installation date should not be reset upon upgrade, but stay on the same realization schedule that the user had be on when they installed Muon.

-- "week of install" used for retention tracking -- this is used whether or not a browser has been installed via referral promo, and is used to determine retention rates for a given user over time -- even if they are upgraded to Brave Core. So, the desired behavior would be that upon upgrading from Muon to Brave Core, a given user would retain the same "week of install" from their initial installation (of Muon). (I believe this data is cleared after 90 days, so not all Muon profiles will contain this data).

@aekeus -- Have I overlooked any information here? We already import the promo code itself.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.16 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/935
