### ISSUE TITLE
Lock Brave custom ad notification position to the main display

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#18845]
Lock Brave custom ad notification position to the main display (allow user to unblock via brave://flags)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2

Verified for Monitor 1 as default for `AdNotifications/should_support_multiple_displays/false`
Verified custom ads are glued to Monitor 1
![4k_default_0](https://user-images.githubusercontent.com/34715963/146996977-fbfc634c-8fa8-4104-ba16-03400379ec40.jpg)|![4k_default_1](https://user-images.githubusercontent.com/34715963/146996995-9f363e4b-27a9-4c64-97ba-d4af856a28c0.jpg)|![4k_default_2](https://user-images.githubusercontent.com/34715963/146996998-24b026d1-735c-435b-9050-87056d09e04b.jpg)|![4k_default_3](https://user-images.githubusercontent.com/34715963/146997000-1da31cb1-1a4d-4395-b0e8-158a792c611a.jpg)|![4k_default_4](https://user-images.githubusercontent.com/34715963/146997002-b9fd423f-7197-432f-a58b-750696d06649.jpg)
--|--|--|--|--

Verified for Monitor 2 as default for `AdNotifications/should_support_multiple_displays/false`
Verified custom ads are glued to Monitor 2
![2k_default_0](https://user-images.githubusercontent.com/34715963/146997134-899b0b26-1183-4142-bc45-af2537b1d061.jpg)|![2k_default_1](https://user-images.githubusercontent.com/34715963/146997148-6cd22cde-0eb3-4e4b-95f7-84900063e3ac.jpg)|![2k_default_2](https://user-images.githubusercontent.com/34715963/146997150-67de7a3e-0659-4e2e-bd6a-628d0a84f57a.jpg)|![2k_default_3](https://user-images.githubusercontent.com/34715963/146997154-647c957d-ddfd-47f1-9afc-f29f4818e39c.jpg)
--|--|--|--

Verified for Monitor 2 as default for `AdNotifications/should_support_multiple_displays/true`
Verified custom ads can be dragged between Monitor 1 and 2
Used commandline:
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true --brave-today-host=brave-today-cdn.bravesoftware.com --variations-server-url=https://no-thanks.invalid --enable-features="AdNotifications<CommandLineStudy" --force-fieldtrials="CommandLineStudy/Enabled" --force-fieldtrial-params="CommandLineStudy.Enabled:should_support_multiple_displays/true"
```
![2k_default_flag_0](https://user-images.githubusercontent.com/34715963/146997402-e841d0d5-1d0e-44d7-a17c-811520db7f13.jpg)|![2k_default_flag_1](https://user-images.githubusercontent.com/34715963/146997410-8a9e241e-d5ba-491f-80e3-819a9a34316d.jpg)
--|--

**Comment by stephendonner** [comment]
Verification passed on

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2

Verified for Monitor 1 as default for `AdNotifications/should_support_multiple_displays/false`
Verified custom ads are glued to Monitor 1

monitor 1 default | top right | top left | bottom left | bottom right
---------|----------|---------|---------|----------
<img width="780" alt="Screen Shot 2021-12-23 at 11 47 51 AM" src="https://user-images.githubusercontent.com/387249/147290618-84adab8e-4977-47df-b912-07cbf1531550.png"> | ![Screen Shot 2021-12-23 at 11 20 59 AM](https://user-images.githubusercontent.com/387249/147290477-18521fef-88b5-458d-b794-6bb76e96bffc.png) | ![Screen Shot 2021-12-23 at 11 27 30 AM](https://user-images.githubusercontent.com/387249/147290496-3991fe22-f25f-4df9-810a-4276dbe4a451.png) | ![Screen Shot 2021-12-23 at 11 39 50 AM](https://user-images.githubusercontent.com/387249/147290524-69c09bf1-d187-4b42-9ea6-8eae6af1c0b3.png) | ![Screen Shot 2021-12-23 at 11 33 35 AM](https://user-images.githubusercontent.com/387249/147290547-ac7eb4e6-c013-4293-abc1-81fdef3babb8.png)





Verified for Monitor 2 as default for `AdNotifications/should_support_multiple_displays/false`
Verified custom ads are glued to Monitor 2

monitor 1 default | top right | top left | bottom left | bottom right
---------|----------|---------|---------|----------
<img width="780" alt="Screen Shot 2021-12-23 at 11 47 58 AM" src="https://user-images.githubusercontent.com/387249/147290866-858a4fd1-83d5-4432-8b42-c4a3e54a4cbd.png"> | ![Screen Shot 2021-12-23 at 12 09 14 PM](https://user-images.githubusercontent.com/387249/147290938-0f80963f-470c-40dc-8c6a-f32d779507ea.png) | ![Screen Shot 2021-12-23 at 12 09 14 PM](https://user-images.githubusercontent.com/387249/147290976-44352592-8a10-4013-af98-224015ad9ecb.png) | ![Screen Shot 2021-12-23 at 12 15 46 PM](https://user-images.githubusercontent.com/387249/147291014-253552c4-e970-4a63-a749-4a8bc6a26c5e.png) | ![Screen Shot 2021-12-23 at 12 22 35 PM](https://user-images.githubusercontent.com/387249/147291021-050b7b6d-c674-464c-b104-89b89e588a75.png) | ![Screen Shot 2021-12-23 at 12 41 09 PM](https://user-images.githubusercontent.com/387249/147291030-2157caaf-ea8f-4fef-aee7-65649fc62dee.png)





Verified for Monitor 2 as default for `AdNotifications/should_support_multiple_displays/true`
Verified custom ads can be dragged between Monitor 1 and 2
Used commandline:
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true --brave-today-host=brave-today-cdn.bravesoftware.com --variations-server-url=https://no-thanks.invalid --enable-features="AdNotifications<CommandLineStudy" --force-fieldtrials="CommandLineStudy/Enabled" --force-fieldtrial-params="CommandLineStudy.Enabled:should_support_multiple_displays/true"
```

example | example (2nd monitor not displayed in screenshot; note position of ad)
---------|---------
![Screen Shot 2021-12-23 at 12 46 36 PM](https://user-images.githubusercontent.com/387249/147291106-3ce22704-aaa4-435c-840b-3ab3f61a574f.png) | ![Screen Shot 2021-12-23 at 12 47 05 PM](https://user-images.githubusercontent.com/387249/147291119-0771ee6e-a792-4004-83b8-851ea137270b.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.34.71 Chromium: 97.0.4692.56 (Official Build) beta (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Ubuntu 18.04 LTS

Verified for Monitor 1 as default for `AdNotifications/should_support_multiple_displays/false`
Verified custom ads are glued to Monitor 1

![default_1_1](https://user-images.githubusercontent.com/34715963/147374930-930e8b07-caa3-4f54-8e46-5d3efa1d5fbf.jpg)|![default_1_2](https://user-images.githubusercontent.com/34715963/147374933-d3369b07-7632-41e5-96d4-497cafe1cf82.jpg)|![default_1_3](https://user-images.githubusercontent.com/34715963/147374934-6d0730ab-f178-4028-8759-4ca6fc5be338.jpg)|![default_1_4](https://user-images.githubusercontent.com/34715963/147374935-679985af-ba23-4608-969f-4c4a5182be08.jpg)
--|--|--|--

Verified for Monitor 2 as default for `AdNotifications/should_support_multiple_displays/false`
Verified custom ads are glued to Monitor 2
![default_2_1](https://user-images.githubusercontent.com/34715963/147374943-ebe01c66-addb-4dbb-937f-1fe6bebbe3d5.jpg)|![default_2_2](https://user-images.githubusercontent.com/34715963/147374944-5d05e097-7c19-4469-b9c5-d6f6a67b1666.jpg)|![default_2_3](https://user-images.githubusercontent.com/34715963/147374945-9a2a4631-c96f-4fb2-97a0-3e9d72ab0d79.jpg)|![default_2_4](https://user-images.githubusercontent.com/34715963/147374946-503bd477-7399-4c80-affe-8ed10219e1bd.jpg)
--|--|--|--

Verified for Monitor 2 as default for `AdNotifications/should_support_multiple_displays/true`
Verified custom ads can be dragged between Monitor 1 and 2
Used commandline:
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true --brave-today-host=brave-today-cdn.bravesoftware.com --variations-server-url=https://no-thanks.invalid --enable-features="AdNotifications<CommandLineStudy" --force-fieldtrials="CommandLineStudy/Enabled" --force-fieldtrial-params="CommandLineStudy.Enabled:should_support_multiple_displays/true"
```
![flag_1_1](https://user-images.githubusercontent.com/34715963/147374951-708f0ce2-63f9-410f-9d49-c1d050ba0100.jpg)|![flag_1_2](https://user-images.githubusercontent.com/34715963/147374954-01455f66-9611-442e-b15e-ca4e3f2f8f4d.jpg)
--|--
