### ISSUE TITLE
Improve Brave ads serving pipeline performance

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#18843]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.33.83 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/10580
Verification done in https://github.com/brave/internal/issues/833
