### ISSUE TITLE
Update default search provider list for South Korea

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#18855]
It should have Naver and Daum search provider as a default.

**Comment by jenn-rhim** [comment]
Naver and Daum logos

![naver](https://user-images.githubusercontent.com/4369856/210639164-f38566f9-87a0-48a2-98df-50f148eea080.svg)

![daum](https://user-images.githubusercontent.com/4369856/210639324-1c93d354-f76e-437f-b8c6-526cb5e542f1.svg)

**Comment by jenn-rhim** [comment]
i'm checking to see why the colors of the Daum logo come out all off.  please hold...

**Comment by jenn-rhim** [comment]
it should look like this

<img width="291" alt="Screenshot 2023-01-04 at 12 22 13 PM" src="https://user-images.githubusercontent.com/4369856/210642981-479b38dc-82a6-4383-90b2-ebe1c35fc697.png">

**Comment by simonhong** [comment]
@rebron We also want to change default provider as Naver or Daum at SK?
We set google as a default now.

**Comment by kjozwiak** [comment]
@brave/qa-team more detailed STR/Cases can be found via https://github.com/brave/brave-core/pull/10590#issuecomment-1413391092.

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` until the following are resolved:
- https://github.com/brave/brave-browser/issues/28232 (Android)
- https://github.com/brave/brave-browser/issues/28235 (Desktop)

**Comment by simonhong** [comment]
@kjozwiak @LaurenWags @rebron I'll reopen when revert (https://github.com/brave/brave-core/pull/17089) is done.
As we discussed in slack, we're not ready to update default provider list because private default search provider is not
handled properly when default list is updated. Desktop fix is ready(https://github.com/brave/brave-core/pull/17015).
When fix for android is ready, I'll try to reland SK search provider list update.

**Comment by simonhong** [comment]
Re-opened as revert PR(https://github.com/brave/brave-core/pull/17089) is merged.

**Comment by anthonypkeane** [comment]
@simonhong did you get the one line sentence for this search engine on Android? 

Also, @deeppandya just making sure you know about this so the change doesn't conflict with any other logic. (cc @timchilds )

**Comment by simonhong** [comment]
> @simonhong did you get the one line sentence for this search engine on Android?

@anthonypkeane  Yes, I got - https://github.com/brave/brave-core/pull/10590#issuecomment-1183473674

> 
> Also, @deeppandya just making sure you know about this so the change doesn't conflict with any other logic. (cc @timchilds )

@deeppandya also reviewed this change but reverted as we found some bug when default provider is updated.
Desktop fix is merged and Android fix is in reviewing. When it's finished, I'll reland PR for this again.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.5 (Build 20G1225)

### Steps:

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.51.84 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

### <summary>Testcase 1: New profile<summary>

#### Case 1: Default SE  - Normal Window  - `PASSED`
<details>

1. set Windows Country or region to Korea and Regional format to Korean(Korea)
2. Installed `1.51.84`
3. launched Brave and skipped onboarding 
4. opened `brave://settings/search`
5. confirmed search engine list show South Korea specific provider list in `Normal Window` 
      - `Brave`, `Naver`, `Daum` and `Google`
6. confirmed `Naver` is selected as the default SE
7. confirmed  `Brave` is at the top of the Normal Window dropdown
8. confirmed  `Naver` is  retained after restarting the browser couple of times
9. confirmed the new default SE (`Naver`) is also reflected via `brave://settings/searchEngines`
10. confirmed Naver search-engine (without favicon) in a new-tab window 
11. Naver favicon was fetched and shown in the additional tab
12. confirmed searches from the URL bar went to https://search.naver.com/search.naver?ie=UTF-8&query=brave&sm=chr_hty

step 1|step 5|step 6|step 7|step 9|step 10|step 11|step 12
----|----|-----|------|-----|-----|----|-----
<img width="502" alt="image" src="https://user-images.githubusercontent.com/98358127/230986038-c813485f-9633-4395-b7da-1c375d770bfe.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/230986116-42a586a2-9c0c-48af-b096-0eb9a64962f9.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/230987394-c260604e-8597-4413-9762-e8544e900637.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/230987177-6bdcf78d-ad7d-409b-ac0c-80b98feb5adc.png">|<img width="490" alt="image" src="https://user-images.githubusercontent.com/98358127/230990930-ad4e2300-299d-4333-8696-5c8fc0005f8c.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/230989676-4a93fd8a-a27b-405f-a420-ec0cc56a4612.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/231014723-4cf423e0-925d-4ed9-926d-6aaae9083671.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/230989788-b23b2f92-1c00-44b1-b3d8-47895b413757.png">
</details>

#### Case 2:  Default SE - Private Window  - `PASSED`
<details>

1. Continue from Case 1: 
      - opened `brave://settings/search`
2. confirmed search engine list show South Korea specific provider list in `Private window` 
      - `Brave`, `Naver`, `Daum` and `Google`
3. confirmed `Brave` is selected as the default SE
4. confirmed Brave Search is shown (without icon) in the URL bar of the new-tab
5. confirmed searches from the URL bar went to https://search.brave.com/search?q=brave&source=desktop

step 2|step 3|step 4|step 5
---|-----|-----|-----
<img width="487" alt="image" src="https://user-images.githubusercontent.com/98358127/230991887-f499ef39-4da0-49ff-ace3-0d0f21d07592.png">|<img width="488" alt="image" src="https://user-images.githubusercontent.com/98358127/230991905-eb82c9c8-52e0-4f55-9653-644f01fce72b.png">|<img width="486" alt="image" src="https://user-images.githubusercontent.com/98358127/230992054-474f07c1-ba06-4389-8945-3e0877bb26b4.png">|<img width="494" alt="image" src="https://user-images.githubusercontent.com/98358127/230992123-eb3156cf-47c0-40c1-a350-9195fdc1ccf6.png">
</details>

#### Case 3: Custom search-engine choice -  Normal window - `Brave` - PASSED
<details>

1. New profile 
2. launch Brave
3. click Set Brave as default Browser
4. select `Naver Whale` and click `Import`
5. click `Select All` and click `Import profiles`
6. click `Finish`
7. click Profile Manager/Profile list next to hamburger menu
8. select `Naver Whale Person 1` 
9. opened `brave://settings/search`
10. confirmed search engine list show South Korea specific provider list in `Normal window` 
      - `Brave`, `Naver`, `Daum` and `Google`
11. selected `Brave`  
13. opened a new tab and searched `Brave`
14. confirmed searches went to https://search.brave.com/search?q=brave&source=desktop
15. confirmed `Brave` as default in Search engine list in `brave://settings/searchEngines

step 4|step 5|step 7|step 10|step 11|step 13|step 15
----|-----|-----|------|-----|------|-----
<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/230994818-4a95dbad-c55c-486d-a062-c5d7bdc89fda.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/230994895-dd8c31ac-6fc8-45b1-84b5-7cb9f91f8f86.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/230995241-863b21d4-0f3f-45f8-b442-5f8694ab6546.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/230995673-2084e9a2-5399-49ae-96fe-c83f6f0ac7b9.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/230995894-0bc38c55-bf4c-4e1b-bb68-eb466e6680ec.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/230996172-ab3978c3-416f-4578-abab-6a5cf73f5a55.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/230997960-4d1088c2-0506-450a-a106-077b223c094f.png">
</details>

#### Case 4: Custom search-engine choice -  Normal window - `Daum` - PASSED
<details>

1. New profile 
2. launch Brave
3. opened `brave://settings/search`
4. confirmed search engine list show South Korea specific provider list in Normal `Window` 
      - `Brave`, `Naver`, `Daum` and `Google`
5. confirmed `Naver` is selected as the default SE 
6. selected `Daum`  
7. confirmed Daum Search is shown (without icon) in the URL bar of the new-tab 
8. confirmed searches went to https://search.daum.net/search?w=tot&DA=JU5&q=brave
9. confirmed `Daum` as default in Search engine list in `brave://settings/searchEngines`

step 4|step 6|step 7|step 9
----|-----|-----|-----
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/230998456-86db8dd6-0ad3-4102-9455-65ea396c034d.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/230998873-3b28c742-41ab-4fbd-833d-d97374ee57b6.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/230999259-683d5179-45b0-4014-bedb-5917fa77c0d5.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/230999349-90b31a5d-4128-4b03-a80f-98694ddbcf69.png">
</details>

#### Case 5: Custom search-engine choice - Private Window - `Naver` - PASSED
<details>

1. Continue from Case 4
      - Daum was selected as SE in Normal window
      - Brave was default SE in Private window
2. open a Private window 
3. confirmed Naver Search is shown (without icon) in the URL bar of the new-tab 
4. confirmed searches from the URL bar went to https://search.naver.com/search.naver?ie=UTF-8&query=brave&sm=chr_hty

step 1a|step 1b|step 3|step 4
-----|-----|------|----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/231016578-a14fc63a-2303-4e52-b7dd-d69a44bf4f2a.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/231016678-bea2bbb0-7c0f-49e5-8ca4-6ead77050865.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/231016706-76dd0f96-3f1e-4bdb-a2a7-1e5eb4f54e4b.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/231016805-ceeab5e0-1fe6-4c62-bac2-1d2e1e8263eb.png">

</details>

### <summary>Testcase 2: Upgrade</summary>

#### Case 1:  Default SE  - `Normal window` & `Private window`  - `PASSED`
<details>

1. set OS region to `Korea`
2. installed `1.50.114`
3. launched Brave and skip onboarding
4. verified Google search shown as a default SE in a new tab URL bar
5. opened `brave://settings/search`
6. verified search-engine defaults of `Google` and `Brave` for `Normal window` and `Private window`, respectively
7. verified `brave://settings/searchEngines` page show `Google` as a default
8. renamed the profile `Brave-Browser-Beta`
9. installed `1.51.84` 
10. launched Brave
11. opened `brave://settings/search`
12. opened `brave://settings/searchEngines`
13. opened a new tab 

- Confirmed defaults of `Google` and `Brave` for `Normal window` and `Private window`, respectively as default SE in `brave://settings/search`
- Confirmed ``Naver` & `Daum` are listed for `Normal window` and `Private window` respectively in `brave://settings/search`
- Confirmed `Naver` & `Daum` are listed Search engines list in `brave://settings/searchEngines`
- Confirmed `Google` listed as a default SE in brave://settings/searchEngines
- Confirmed Google search in the Search bar

step 6|step 7|step 11(NW)|step 11(PW)|step 12|step 13
---|----|----|----|-----
<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/231018130-2c3a8c85-469f-4cf7-aee3-829090824f0a.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/231018222-266b8d44-bd95-4fd1-b5f8-37c2a1a2f446.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/231019496-0fdf998c-2c08-4bc2-a8c1-9f381e7af2de.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/231019523-311cbd81-1b63-4a68-bbdb-063b19b3a327.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/231020654-f7955383-dbb9-401b-80b7-464bb76778b2.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/231020921-c7173305-108f-4f35-8f0a-99687477647a.png">
</details>

#### Case 2: Custom search-engine choice(s) - `PASSED`
<details>

1. Continue from Case 1 (Testcase 2 Upgrade)
    - Default SE is `Google` for Normal window in `brave://settings/search`
    - Default SE is `Brave` for Private window in `brave://settings/search`
2. selected `Qwant` and `Bing` as search engines for Normal window and Private window respectively 
3. verified `Qwant` is shown as a default in the Search Engine list in `brave://settings/searchEngines`
4.  renamed the profile `Brave-Browser-Beta`
5. installed `1.51.84` 
6. launched Brave
7. opened `brave://settings/search`
8. opened `brave://settings/searchEngines`
9. opened a new tab for Normal window and Private window

- Confirmed `Qwant` and `Bing` selections are retained upon upgrade in `brave://settings/search` for Normal window and Private window respectively
- Confirmed `Qwant` is shown as default in the searchEngine list upon upgrade in `brave://settings/searchEngines`
- Confirmed `Qwant` search in the Search bar for `Normal window`
- Confirmed `Bing` in the Search bar for `Private window`

step 1|step 2|step 3|step 7a|step 7b|step 8|step 9a|step 9b
-----|-----|------|------|------|------|------|----
<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/231021476-e69fc028-475f-44ac-bdd8-355cf29ed766.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/231021688-88c4bea2-4178-4cf2-a111-f5a077f79ec6.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/231021726-b30ad4f1-111c-4b14-a1cf-adfbaf13fff5.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/231028346-fb236a98-af06-4c7e-832e-3bfb41933df2.png">|<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/231022135-685ccefe-8f8a-4762-96d7-1094ca9919e8.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/231028377-9aa78586-d131-462c-b461-09c30679d826.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/231029215-28b75083-68fd-4881-bae0-af5396ff9582.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/231028982-c3faf297-76bf-4c80-bc16-f90075654670.png">

</details>

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 6` using version(s):

```
Device/OS: Google Pixel 6 [oriole-user 13 TQ2A.230405.003.E1 release-keys]
Brave build: 1.51.107 Chromium: 113.0.5672.63 (Official Build) (64-bit)
Revision: 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
```
---------------------------

<details>
<summary> Clean profile - PASS </summary>

- Verified that the search onboarding screen is shown for South Koria
- Verified that only Brave Search, Naver, Daum and Google search providers are available
- Verified that `Naver` is the default search provider for `Normal tab` and `Private tab`
- Verified that Brave search the first one on the list for `Normal tab` and `Private tab`
- Verified `Naver` and `Daum` thumbnails color in the search bar for `Normal tab`
- Verified that search results are done by the correct SE for the `Normal tab` and `Private tab`

Re: #26318

|1|2|3|4|
|-|-|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/235254015-ad6464a5-7950-4172-afa3-c267620a1b60.png) | ![2](https://user-images.githubusercontent.com/128532965/235254753-806ec132-4ab7-46fa-a096-f349ea09be24.png) | ![3](https://user-images.githubusercontent.com/128532965/235254839-f1070f34-b3ba-4960-b44d-a5d69616c84a.png) | ![34](https://user-images.githubusercontent.com/128532965/235254866-f5b66847-8482-452f-9918-36dd03f3b7ef.png) |
|-|-|-|-|
|5|6|7|8|
| ![5](https://user-images.githubusercontent.com/128532965/235257932-632ad4fc-4200-4d52-a2df-2b2be803df3d.png) | ![6](https://user-images.githubusercontent.com/128532965/235258043-55bb8aea-5b38-4f3b-b748-2c503be51026.png) | ![7](https://user-images.githubusercontent.com/128532965/235258603-952b2c3f-797b-49ce-9f93-289781891411.png) | ![8](https://user-images.githubusercontent.com/128532965/235258654-636ad452-b958-464b-8dc5-9d9c097c18dd.png) |
</details>

<details>
<summary> Upgraded profile - FAILED </summary>

1. Install build `1.50.121 Chromium: 112.0.5615.138`
- Verified that the search onboarding screen is shown and Google is the default SE
- Verified that `Google` is the default search provider for `Normal tab` and `Private tab`
- Verified that Brave search the first one on the list for `Normal tab` and `Private tab`
2. Change SE to `DDG` and `Bing` for `Normal tab` and `Private tab` accordingly
3. Upgrade to build `1.51.107 Chromium: 113.0.5672.63`
- Observed that `DDG` and `Bing` were still selected for `Normal tab` and `Private tab`
- Verified that `Qwant` and `Startpage` are removed from the list of SE
- Verified that search results are done by search engines that were selected for the `Normal tab` and `Private tab`

|1|2|
|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/235269169-2273dc78-4be6-4151-b687-155ad6e74aed.png) | ![2](https://user-images.githubusercontent.com/128532965/235269173-bb10c817-1ecb-4946-969e-c82e4b6e00b3.png) |
</details>

NOTE: Created issue #30063
