### ISSUE TITLE
Ad Notifications Not Displaying Nor Incrementing

### ISSUE THREAD

**Issue by leefc01** [brave/brave-browser#18850]
## Description 
With current build, no ads notifications are being displayed.  The only ads I see are the home screen background images.  When the background ad images do display, they are not incrementing the Ads Received This Month counter.

## Steps to Reproduce
   1. Open browser.
   2. Navigate to brave://rewards/
   3. Note count of Ads Received This Month
   4. Open new tab
   5. Refresh until ad is displayed
   6. Navigate back to brave://rewards/
   7. Note the count of Ads Received This Month does not increment

## Actual result:
Count of Ads Received This Month does not change.
Additionally, I haven't received a single ad notification with the new build, but it's hard to show how that is not happening.

![Test](https://user-images.githubusercontent.com/63391845/137818168-ff8ed7fe-ba33-4a68-bf7a-18654c0a9dd0.gif)

## Expected result:
Count of Ads Received This Month should increment by one after ad is displayed.
Ads with notifications should display.

## Reproduces how often: 
Easily reproduced at will.

## Brave version (info found on brave://version)

Brave | 1.30.89 Chromium: 94.0.4606.81 (Official Build) (64-bit)

Revision | 5a03c5f1033171d5ee1671d219a59e29cf75e054-refs/branch-heads/4606@{#1320}
OS | Windows 10 Version 20H2 (Build 19042.1288)
JavaScript | V8 9.4.146.21
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release?   Yes
- Can you reproduce this issue with the beta channel? Not yet tried
- Can you reproduce this issue with the dev channel? Not yet tried
- Can you reproduce this issue with the nightly channel? Not yet tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  NA - only applies to Brave Browser

## Miscellaneous Information:
I've noticed a few other folks have this issue mentioned on Reddit.  Might be related to being on Win10 Enterprise.

**Comment by leefc01** [comment]
Ad history info.
![image](https://user-images.githubusercontent.com/63391845/137941250-5200130b-a6d3-4b6f-94ad-2b10c962d560.png)

**Comment by svowl** [comment]
Hi, @leefc01 did you find a solution? I'm experiencing the same now and I think this happen after Brave upgraded to V1.33.106 last week.
Are there any tips for how to resolve this?

**Comment by tmancey** [comment]
@svowl I work on the ads team here at Brave, can you please email me your wallet id (do not post here) to terry@brave.com and I can investigate thanks

**Comment by svowl** [comment]
Hi @tmancey 
Did you have a chance to review the info I sent you?
