### ISSUE TITLE
Add option to hide thumbnails on new tab page

### ISSUE THREAD

**Issue by FWDekker** [brave/brave-browser#1885]
## Description 
Users should have the option to hide the thumbnails displayed on the new tab page. This option may be preferred by users for two reasons:
1. It reduces clutter for users who do not use the thumbnails.
2. It prevents people who look over your shoulder from being judgmental.

## Brave version
0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)

**Comment by Jacalz** [comment]
+1 from me, really never using them

**Comment by bbondy** [comment]
cc @bradleyrichter

**Comment by ppizzo** [comment]
Looking forward to seeing this feature implemented. It's very annoying to show my most visited web sites when I'm presenting my desktop in a meeting and need to use the browser.

**Comment by bbondy** [comment]
For now you could consider installing a chrome extension which gives more customizations to the new tab page.

**Comment by rebron** [comment]
Closing. Fixed with https://github.com/brave/brave-browser/issues/4510. This is in 69.x nightly channel now and will make its way to release channel.
