### ISSUE TITLE
Cannot Build on Windows

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#18864]
## Description 

Windows users attempting to build Brave may encounter a couple issues in the process:

1. Python is not properly located (or is environmentally ambiguous), leading to failure
2. Lengthy commands (in excess of 8,191 characters) passed to cmd.exe, leading to failure

Brave's build tools provide an instance of Python, which should be preferred during the build process. We should also not rely on cmd.exe, given its limitations.

cc @mkarolin

**Comment by mkarolin** [comment]
No longer relevant due to https://github.com/brave/brave-browser/issues/20632
