### ISSUE TITLE
`Learn more` text in the tipping banner isn't translated to Japanese

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#18863]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18374
`Learn more` in the tipping banner isn't translated to Japanese

## Steps to Reproduce

   1. Set OS locale to Japanese
   2. Clean profile 1.31.87
   3. Enable rewards and connect KYC'd bitflyer wallet
   4. Open DDG or CNN.COM
   5. Open tipping banner, `Learn more` in the tipping banner isn't translated to Japanese

## Actual result:

`Learn more` in the tipping banner isn't translated to Japanese
![image](https://user-images.githubusercontent.com/38657976/137913973-f6fcf125-a45f-483a-8e0f-fee4b438305c.png)

## Expected result:

`Learn more` in the tipping banner should be translated to Japanese

`1.30.89`
![image](https://user-images.githubusercontent.com/38657976/137914652-169372bf-2d7b-4d2c-971c-429c79b2737f.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave	1.30.89 Chromium: 94.0.4606.81 (Official Build) （64 ビット）
変更履歴	5a03c5f1033171d5ee1671d219a59e29cf75e054-refs/branch-heads/4606@{#1320}
OS	Windows 10 Version 1809 (Build 17763.1637)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mkarolin @Miyayes @brave/legacy_qa

**Comment by mkarolin** [comment]
I don't think it reproduces any more. Checking with 1.32.113

![image](https://user-images.githubusercontent.com/41635752/144675065-09a27ce5-ba92-4847-988f-3d562c723ad1.png)

**Comment by rebron** [comment]
@GeetaSarvadnya When you get a chance to check to see if this is still an issue.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave	1.35.92 Chromium: 97.0.4692.99 (Official Build) beta （64 ビット）
変更履歴	d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS	Windows 10 Version 1809 (Build 17763.1637)
```

@rebron Issue is fixed and working fine. 

![image](https://user-images.githubusercontent.com/38657976/151113644-71fbcebf-ec3b-4bfa-85ef-06687502f1eb.png)
