### ISSUE TITLE
Youtube videos with custom paths should show in Rewards panel correctly

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#1886]
## Description 

When navigating to a youtube channel with a custom path, youtube is shown as the publisher in panel instead of the actual publisher

## Steps to Reproduce

   1. Navigate to https://www.youtube.com/bravesoftware
   2. Open Rewards panel

## Actual result:

Publisher is listed as YouTube

## Expected result:
Publisher should be listed as Brave or any other publisher that corresponds to a custom path.

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.58.1 Chromium: 70.0.3538.77 (Developer Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by jonathansampson** [comment]
Glad to see this has been captured; I've noticed it off and on and assumed it was some transient issue with state. Glad to see it is already well understood!

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/2732

**Comment by kjozwiak** [comment]
@brave/legacy_qa now that https://github.com/brave/brave-core/pull/1867 has landed, we'll need to go through this issue with the latest `0.62.x` build and verify that it's working and didn't cause any other obvious regressions. If things are looking good, we'll uplift to `0.61.x` as per the discussion on the b-c triage meeting earlier in the week.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.3 x64` using the following build:

Brave | 0.62.24 Chromium: 73.0.3683.56 (Official Build) dev(64-bit)
-- | --
Revision | 303af44e2f2948869279f120021c778855d76ead-refs/branch-heads/3683@{#653}
OS | Mac OS X

* Went through the test cases outlined under https://github.com/brave/brave-core/pull/1703
