### ISSUE TITLE
Favicon is not displayed for media publisher

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1887]
## Description 

When you are viewing media publisher in the panel, favicon is not displayed until you start playing a video.

## Steps to Reproduce

   1. enable rewards
   2. visit youtube site for example https://www.youtube.com/channel/UCFNTTISby1c_H-rm5Ww5rZg
   3. click on bat logo

## Actual result:

favicon is not always displayed

## Expected result:
favicon should be always displayed

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Problem is that we shouldn't fetch favicon if fetch is already in place. We shouldn't set favicon until we actually got it.

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows
