### ISSUE TITLE
Linux - Ubuntu (Fedora): Dev/Beta Builds opens in new dock location, displays wrong icon in dock 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#1888]
## Description 

_@mbacchi Has Fedora information, will add to this issue later._

In Ubuntu (18.04), the Developer and Beta Build shows up in a new icon on the doc as opposed to adding new windows to the same dock icon (see third gif opening Firefox to compare). Additionally, when launching the Developer build, I'm seeing the Stable build icon displayed in the doc rather than the developer build. Screens of the behavior:

Original video report from Reddit user:
<blockquote class="reddit-card" data-card-created="1540837190"><a href="https://www.reddit.com/r/brave_browser/comments/9sdpod/the_bug_in_brave_dev_for_linux_probably_not/">The bug in Brave Dev for Linux (Probably not specifically Ubuntu)</a> from <a href="http://www.reddit.com/r/brave_browser">r/brave_browser</a></blockquote>

My testing of the issue (includes incorrect icon displaying:
![devubuntu](https://user-images.githubusercontent.com/3299098/47671447-bc7c1700-db6c-11e8-9637-b54c194264a4.gif)

Compared to launching Firefox:
![devubuntu2](https://user-images.githubusercontent.com/3299098/47671537-f6e5b400-db6c-11e8-849d-2b3d9f3d7b83.gif)

#Steps to Reproduce

   1. Download/install fresh Ubuntu profile of Dev/Beta
   2. Launch Dev/Beta
   3. Open additional window(s)

## Actual result:

Brave (Dev/Beta) launches and displays in a second icon in the dock. Launching additional windows appear in the _second_ docked icon. 

## Expected result:
Brave windows are displayed/appear in the original docked icon.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Dev - v0.57.3
Beta - v0.56.6

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
No.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information

Link to original report: https://www.reddit.com/r/brave_browser/comments/9sdpod/the_bug_in_brave_dev_for_linux_probably_not/

**Comment by kpuljek** [comment]
This happens because Brave doesn't have a proper StartupWMClass set in its .desktop file. I had to add it manually on more than one installation:
StartupWMClass=brave-browser

GNOME and other modern desktops just don't know that the newly spawned process matches the icon on the dock and just makes a new one. 

I'd also like to point out that in situations where I had multiple versions installed (stable, beta and/or dev), this problem appeared much more often and the above WM class solution worked sporadically.

**Comment by fmarier** [comment]
I cannot reproduce this. I suspect it may have been fixed as a result of fixing #1324.

@Brave-Matt are you still seeing this problem?

**Comment by fmarier** [comment]
I'll assume this is resolved for dev/beta. We have another issue open for Nightly: https://github.com/brave/brave-browser/issues/1746
