### ISSUE TITLE
Brave Window Overflows when Maximized

### ISSUE THREAD

**Issue by intersectRaven** [brave/brave-browser#18881]
## Description 
Brave window overflows screen when maximized.

## Steps to Reproduce
   1. Maximize screen.

## Actual result:
![image](https://user-images.githubusercontent.com/229447/138003811-501f2a2a-e986-4eb3-8883-d8205b3686cf.png)
![image](https://user-images.githubusercontent.com/229447/138003832-ce1ef772-c88c-4796-b29b-5af61524341a.png)

## Expected result:
Should not overflow screen.

## Brave version (brave://version info)
Brave	1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)
Revision	d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS	Linux
JavaScript	V8 9.5.172.21
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Command Line	/usr/lib/brave-bin/brave --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,LegacyTLSEnforced,DnsOverHttps,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,SafetyTip --disable-features=AutofillServerCommunication,ComputePressure,FledgeInterestGroups,SettingsLandingPageRedesign,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,InterestCohortFeaturePolicy,CopyLinkToText,TrustTokens,DirectSockets,AppDiscoveryRemoteUrlSearch,WebOTP,NotificationTriggers,FirstPartySets,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,InterestCohortAPIOriginTrial,TextFragmentAnchor,ReadLater,FederatedLearningOfCohorts,ConversionMeasurement,SignedExchangeSubresourcePrefetch,NavigatorPluginsFixed,LiveCaption,IdleDetection,PrivacySandboxSettings2,SignedExchangePrefetchCacheForNavigations,NetworkTimeServiceQuerying,SubresourceWebBundles --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/brave-bin/brave
Profile Path	/home/intersectraven/.config/BraveSoftware/Brave-Browser/Default
Variations	AdRewardsStudy:NextPaymentDay
BraveTalkStudy:Enabled
ConversionsStudy:NewDefaultPattern
EphemeralStorageStudy:Enabled
NativeCosmeticFilteringStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SpeedreaderReleaseStudy:Enabled

## Version/Channel Information:
I don't know since I only use stable.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
None

**Comment by intersectRaven** [comment]
This still occurs on 1.31.88.

**Comment by iago-pssjd** [comment]
It happens to me too on 1.31.88 under Debian 11, XFCE 4.16

**Comment by intersectRaven** [comment]
Fixed now in 1.32.106.
