### ISSUE TITLE
Path names do not appear in address bar for IPNS addresses

### ISSUE THREAD

**Issue by autonome** [brave/brave-browser#18888]
## Description 

If you open an IPNS address and click around, paths do not appear in the address bar. If you open the IPFS address for the same website, paths do appear in the address bar

## Steps to Reproduce

   1. Open `ipns://docs.ipfs.io`
   2. Click some items in the navigation bar

## Actual result:

Paths do not appear in the address bar after the FQDN.

## Expected result:

Paths are visible in the address bar after the FQDN.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave nightly Oct 20 2021

## Version/Channel Information:

Reproduced on Nightly and Release channels

**Comment by autonome** [comment]
So should add a regression test for this, since it used to work.

Yep I also noticed that hover links work fine, so looks like only the address bar code path (so far).

**Comment by lidel** [comment]
I published a small demo under `bafybeid2sz6646igfsciecr2cwcb7e2hxl6xewigxy3rjwgk6cbfmiiium` to help with narrowing this down. 

Clicking on cat names update the address bar via `history.pushState`.  Tested in  Brave 1.31.91 with different addresses:
- :green_apple:  `ipfs://bafybeid2sz6646igfsciecr2cwcb7e2hxl6xewigxy3rjwgk6cbfmiiium/demos/history/`  – works as expected
- :green_apple:  `ipns://k51qzi5uqu5dgutdk6i1ynyzgkqngpha5xpgia3a5qqp4jsh0u4csozksxel2r/demos/history/` – works as expected
- :anger:  `ipns://kittens-history-push-demo.aergia.eu/demos/history/` – broken (address in address bar does not get updated when clicking on links)

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.34.37 Chromium: 96.0.4664.45 (Official Build) nightly (x86_64)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. loaded `ipns://docs.ipfs.io/`
4. clicked on various side-navigation anchors
5. confirmed they showed up in the URL bar
6. via `brave://settings/ipfs` toggled `IPFS Companion` to install it
7. confirmed clicking on various side-navigation anchors reflected the anchors in the Companion, as well as the clipboard
8. also confirmed same for various cat links on `ipns://kittens-history-push-demo.aergia.eu/demos/history/`

`ipns://docs.ipfs.io/install/ipfs-desktop/#macos` | IPFS Companion | clipboard | fluffy | socks
-------------------------------------------------|------------------|----------|-------|-------
<img width="1224" alt="Screen Shot 2021-11-25 at 6 38 37 AM" src="https://user-images.githubusercontent.com/387249/143436188-79c2aa55-e487-4694-95ef-c4cb5abb9f9f.png"> | <img width="1403" alt="Screen Shot 2021-11-25 at 6 47 24 AM" src="https://user-images.githubusercontent.com/387249/143436297-074a99a7-a5eb-40a6-ae27-d69635a6d93a.png"> | <img width="370" alt="Screen Shot 2021-11-25 at 6 48 15 AM" src="https://user-images.githubusercontent.com/387249/143436403-896635bc-5c2f-4e50-b198-6f4109638160.png"> | <img width="1515" alt="Screen Shot 2021-11-25 at 6 49 30 AM" src="https://user-images.githubusercontent.com/387249/143436698-2d293d63-1f58-477e-9e1f-d188190acb0a.png"> | <img width="1515" alt="Screen Shot 2021-11-25 at 6 49 33 AM" src="https://user-images.githubusercontent.com/387249/143436704-834f4fba-b509-4f17-8e4e-2e4ed92da3dd.png">
