### ISSUE TITLE
Encourage users to try Brave again

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#18880]
## Description 
Some user download Brave, use it for a time and forget about us. We want to remind them about the app and show them how we have improved. 

Please search for Mobile Dormant Users Engagement in GDrive for details

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/10942

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using Brave `1.34.70` on a `Google Pixel XL` running `Android 9.0`.

### Scenario 1 (14+ days):
<details>

1. install `1.34.x`
2. tap through onboarding
3. tap on the 3-dots menu
4. tap on `Settings`
5. tap on `About Brave`
6. tap 7 times on `Application version`
7. tap on `Developer Options`
8. tap on `QA Preferences`
9. enter the code
10. tap to set `Enable dormant users engagement` to `ON`
11. tap `RELAUNCH NOW`
12. shut down Brave
13. change the system date to > 15 days from now
14. pull down the notifications widget on Android
15. wait
16. tap to expand the plethora of notifications
17. tap on the `Brave is lightning fast` notification
18. confirm Brave launches and displays the above dialog

![Screenshot_20220212-103701](https://user-images.githubusercontent.com/387249/147293960-75e9b9b7-3db2-4ef9-9c32-767a217cadba.png)

</details>

### Scenario 2 (42+ days):
<details>

1. install `1.34.x`
2. tap through onboarding
3. tap on the 3-dots menu
4. tap on `Settings`
5. tap on `About Brave`
6. tap 7 times on `Application version`
7. tap on `Developer Options`
8. tap on `QA Preferences`
9. enter the code
10. tap to set `Enable dormant users engagement` to `ON`
11. tap `RELAUNCH NOW`
12. shut down Brave
13. change the system date to > 42 days from now
14. pull down the notifications widget on Android
15. wait
16. tap to expand the plethora of notifications
17. tap on the `Brave is lightning fast` notification
18. confirm Brave launches and displays the above dialog
19. shut down Brave
20. tap on the `Get more battery life on every charge` notification
21. confirm Brave launches and displays the above dialog
22. shut down Brave
23. tap on the `Top up your mobile data less often` notification
24. confirm Brave launches and displays the above dialog

1st | 2nd | 3rd
----|------|----
![Screenshot_20220212-103701](https://user-images.githubusercontent.com/387249/147293960-75e9b9b7-3db2-4ef9-9c32-767a217cadba.png) | ![Screenshot_20220228-104522](https://user-images.githubusercontent.com/387249/147293966-16de2fab-3f6b-4fba-bc9d-e6d3b07a7b0a.png) | ![Screenshot_20220228-104507](https://user-images.githubusercontent.com/387249/147293962-2316bcf1-349e-4182-b12c-a42aac2ba54a.png)

</details>

### Scenario 3 (< 14 days):
<details>

1. install `1.34.x`
2. tap through onboarding
3. tap on the 3-dots menu
4. tap on `Settings`
5. tap on `About Brave`
6. tap 7 times on `Application version`
7. tap on `Developer Options`
8. tap on `QA Preferences`
9. enter the code
10. tap to set `Enable dormant users engagement` to `ON`
11. tap `RELAUNCH NOW`
12. shut down Brave
13. change the system date to < 14 days from now
14. pull down the notifications widget
15. wait
16. confirm no notifications
17. change the system date to > 14 days from the last day you set
18. pull down the notifications widget
19. wait
20. confirm you get the `Brave is lightning fast` notification
21. tap on the above notification
22. confirm Brave launches and displays the above dialog

example | example
---------|-----------

</details>

### Scenario 4 (upgrade):
<details>

1. install the `latest public beta` from the Google Play Store
2. install `1.34.70` atop, to upgrade
3. tap on `Settings`
4. tap on `About Brave`
5. tap 7 times on `Application version`
6. tap on `Developer Options`
7. tap on `QA Preferences`
8. enter the code
9. tap to set `Enable dormant users engagement` to `ON`
10. tap `RELAUNCH NOW`
11. shut down Brave
12. change the system date to 15+ days from now
13. pull down the notification widget on Android
14. wait
15. confirm you get the `Brave is lightning fast` notification
16. tap on the above notification
17. confirm Brave launches and displays the above dialog

example | example
----------|----------


</details>

**Comment by stephendonner** [comment]
Before I can finish verifying this (the last two scenarios), we need to get to the bottom of https://github.com/brave/brave-browser/issues/20217 (which @deeppandya knows; just bringing this to attention so we know what's what for release).

/cc @rebron @brave/legacy_qa

**Comment by stephendonner** [comment]
> Before I can finish verifying this (the last two scenarios), we need to get to the bottom of #20217 (which @deeppandya knows; just bringing this to attention so we know what's what for release).
> 
> /cc @rebron @brave/legacy_qa

This was user error; there's a legitimate bug here on at least Android 12, which @kjozwiak will file and @deeppandya saw firsthand.
