### ISSUE TITLE
Unable to get out of reader mode

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#18883]
I’m am sometimes not able to get out of the reader mode version of a page.

If i go back and forward, im still in reader mode after returning to the stuck-in-reader-mode-page.

This is an example URL that triggers the issue for me, though it see it on multiple pages https://www.politico.com/news/2021/10/19/climate-joe-manchin-plan-c-democrats-516262

I have speedreader disabled in brave://settings.

in brave://flags speedreader is "enabled" and enable reader mode is set to “default”.

I am on `1.33.19 Chromium: 95.0.4638.54 (Official Build) nightly (x86_64)`

https://user-images.githubusercontent.com/76526/138011553-ce4690fd-d3de-4dcd-8dc0-20d407272d5c.mov

**Comment by Tonev** [comment]
Possibly a duplicate?

https://github.com/brave/brave-browser/issues/18242

**Comment by iefremov** [comment]
duplicate https://github.com/brave/brave-browser/issues/18242
