### ISSUE TITLE
Dragging Rewards aCAPTCHA prompt grows to fill up screen

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#18891]
## Description 

Dragging Rewards aCAPTCHA prompt grows to fill up screen

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. enable Rewards
   4. schedule an aCAPTCHA
   5. when it appears, drag it and "snap" it to a screen corner (bottom, top, left, right)
   6. now, try to move the notification by dragging it

## Actual result:

The aCAPTCHA grows to fill up the screen

![acaptcha](https://user-images.githubusercontent.com/387249/138121923-c194dc40-5919-45d7-99ca-d93e04651f41.png)

## Expected result:
Clicking to drag should just drag, not arbitrarily resize

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.33.19 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Windows 10 Version 20H2 (Build 19042.1288)

Additional info:

![display-settings](https://user-images.githubusercontent.com/387249/138124162-8d769238-bbe4-4372-aeb3-453678ee2ab7.png)

**Comment by LaurenWags** [comment]
@stephendonner did this reproduce on macOS for you? if not, we may want to add `OS/Windows` label.

**Comment by stephendonner** [comment]
> @stephendonner did this reproduce on macOS for you? if not, we may want to add `OS/Windows` label.

No, I don't think so.

**Comment by LaurenWags** [comment]
updated to `release-notes/exclude` per discussion with @rebron
