### ISSUE TITLE
New tab screen too bright.

### ISSUE THREAD

**Issue by Axgk23** [brave/brave-browser#18899]
Hello!

I leave my screen on a new tab whenever im on my other monitor.

However some of them are too bright, the only decent one is the Echeveria picture.

I was wondering if there was a option to change it or somewhere in the files i could replace the pictures.

Thank you!

**Comment by rebron** [comment]
Hi @Axgk23 You can make changes to the new tab page here: brave://settings/newTab or if you select "Customize" on the New Tab page.
