### ISSUE TITLE
Pinned Tab cannot be muted or unmuted by clicking speaker icon

### ISSUE THREAD

**Issue by franktopel** [brave/brave-browser#18897]
## Description 
See title

## Steps to Reproduce
1. Open any Twitch.tv stream with audio in any tab.
2. Pin that tab.
3. Try to mute (or if it is already muted, unmute) it using mouse click on the speaker icon in the pinned tab.

Cannot be muted/unmuted like this.

## Actual result:
No change of audio when clicking the speaker icon.

## Expected result:
Toggling muted/unmuted state.

## Reproduces how often: 
Reliably reproducible 

## Brave version (brave://version info)
1.31.87 Chromium: 95.0.4638.54 (Offizieller Build) (arm64)
--
Überarbeitung | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
Betriebssystem | macOS Version 12.0.1 (Build 21A558)
JavaScript | V8 9.5.172.21
User-Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

## Version/Channel Information:
Haven't tried other channels.

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome? 
Yes.

**Comment by franktopel** [comment]
Reconsider this, please. I understand the hassle that caused the design decision, but the current state is also less than ideal.

This is how other browsers address this in a better way that doesn't enforce dropping meaningful functionality:

Edge: First click on speaker icon only un/mutes the tab if it is already the active tab, otherwise it makes it the active tab. Second click then mutes.

Firefox (and for me, this would be preferrable): Simply grants pinned tabs a little more space, so it's easy enough to still decide whether you want to mute or switch.

**Comment by DevilEars** [comment]
Please do not break the Brave browser again and remove this infernal mute button on the tabs where no sane person with any background in UX would ever have put it

**Comment by lexcasa** [comment]
I'm agree with @franktopel. 
Please reconsider this. I will fix that on a development branch to use only on my machine because it's annoying issue.
Thanks.
