### ISSUE TITLE
Maximising the browser extends it off the screen

### ISSUE THREAD

**Issue by williamd1k0** [brave/brave-browser#18895]
## Description 

Maximising the browser extends it off the screen.
It looks like it started to happen in the version 1.31.87.

## Steps to Reproduce

   1. Just try to maximise the window.

## Actual result:

I tested it on an actual display with xfwm4, but the screenshots were taken using Xephyr with xfwm4.

![image](https://user-images.githubusercontent.com/10428035/138138177-a3c5f3dc-6c13-46bd-ae68-a5bc2f15ed23.png)
![image](https://user-images.githubusercontent.com/10428035/138138194-c5238967-472a-4c65-a41f-0605236c5640.png)

Note: If the system title bar is enabled, the behaviour is the same as #11967

## Expected result:
The window is maximised to fit the current display.

## Reproduces how often: 

It happens every time.

## Brave version (brave://version info)

Brave | 1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? I don't know
- Can you reproduce this issue with the nightly channel?  I don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? I don't know

## Miscellaneous Information:

OS info: Manjaro Linux 21.1.6 / Linux 5.14.10-1; xfce4/xfwm4; package from AUR (brave-bin 1:1.31.87-1)

**Comment by williamd1k0** [comment]
Looks like this was fixed a long time ago.

**Comment by bsclifton** [comment]
Thanks for following up, @williamd1k0 😄
