### ISSUE TITLE
Shields settings should have precedence over script and fingerprinting settings

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#189]
When shields is down, scripts or fingerprinting should not be blocked.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Visit https://jsfiddle.net/bkf50r8v/13/, disable shields, all FP mechanism is listed
* Visit https://brianbondy.com/, open shields https://brianbondy.com/js/analytics.js is blocked. Disable shields and analytics.js is loaded
