### ISSUE TITLE
Edges of Brave Browser go beyond screen edge when maximised

### ISSUE THREAD

**Issue by shakeelansari63** [brave/brave-browser#18906]
## Description 
Edges of Brave Browser go beyond screen edge when maximised

## Steps to Reproduce
On XFCE open Brave Browser (v1.31.87) and maximise the window. The window edges will go beyond screen edge 

## Actual result:
Browser window edges go beyond screen edge due to which the window id truncateed. 

## Expected result:
Window should fit in the screen edge.

## Reproduces how often: 
Every time window is maximised.

## Brave version (brave://version info)
Brave	1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)
Revision	d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS	Linux
JavaScript	V8 9.5.172.21
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Command Line	/usr/lib/brave-bin/brave --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=AutoupgradeMixedContent,SafetyTip,WebUIDarkMode,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,LegacyTLSEnforced,DnsOverHttps --disable-features=AppDiscoveryRemoteUrlSearch,PrivacySandboxSettings2,SignedExchangePrefetchCacheForNavigations,AutofillServerCommunication,SignedExchangeSubresourcePrefetch,NavigatorPluginsFixed,LiveCaption,TrustTokens,DirectSockets,IdleDetection,InterestCohortFeaturePolicy,CopyLinkToText,FledgeInterestGroups,SettingsLandingPageRedesign,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,FederatedLearningOfCohorts,ConversionMeasurement,TextFragmentAnchor,ReadLater,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,ComputePressure,NotificationTriggers,WebOTP,NetworkTimeServiceQuerying,SubresourceWebBundles,FirstPartySets,InterestCohortAPIOriginTrial --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/brave-bin/brave
Profile Path	/home/freak/.config/BraveSoftware/Brave-Browser/Default
Variations	AdRewardsStudy:NextPaymentDay
BraveTalkStudy:Enabled
ConversionsStudy:NewDefaultPattern
EphemeralStorageStudy:Enabled
NativeCosmeticFilteringStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SpeedreaderReleaseStudy:Disabled

## Version/Channel Information:
I am on Stable build and facing this issue. 

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Screenshot is attached

![Brave browser screen edge truncation](https://user-images.githubusercontent.com/8319053/138229081-575f059f-ff0a-4274-9e9e-e13b23dc4316.png)

**Comment by buffoon86** [comment]
I have this issue too on Debian Bullseye + XFCE.
I was able to reproduce this with chrome and then I found those 2 Bugs:

https://bugs.chromium.org/p/chromium/issues/detail?id=1261797&q=maximize&can=2
https://bugs.chromium.org/p/chromium/issues/detail?id=1260821

where the latter one was just confirmed that this bug still exists. So i think we'll have to wait for upstream chromium to get this fixed.

**Comment by smarkoco** [comment]
I also have this issue with below configuration of Ubuntu Studio.

Browser: brave-browser/stable,now 1.31.88 amd64
Kernel: 5.4.0-89-lowlatency x86_64 bits: 64 
Desktop: Xfce 4.14.2 Distro: Ubuntu 20.04.3 LTS (Focal Fossa)

**Comment by shakeelansari63** [comment]
This issue is getting on my nerves now. Everytime I open Brave, the edges are cropped and I have to go to Settings and change theme. The workaround works but we can't keep doing same. 

I am at a point where I am even considering changing my browser from Brave to something else. 

If this issue is not fixed, I am going to switch to another browser which does not have this issue.

**Comment by shakeelansari63** [comment]
Enabling "Use system title bar and borders" option makes the issue go away. But now we have to deal with title bar which looks odd.

**Comment by bsclifton** [comment]
Thanks @buffoon86 for sharing the upstream Chromium bug reports- looks like this is captured with https://bugs.chromium.org/p/chromium/issues/detail?id=1260821

**Comment by tquetano-netflix** [comment]
I just updated to `1.32.106`, and notice that it has gotten _better_ but not completely solved. If I maximize the window via the toolbar icon (next to the close icon), then it fills the window appropriately. If I drag to a window edge to trigger the same maximization, then the buggy behavior returns. It is not sticky, though; if I trigger the buggy behavior, un-maximize, and then maximize via the toolbar icon, it maximizes as expected.

**Comment by shakeelansari63** [comment]
The issue is fixed in XFWM4. Got update for XFWM4 on ArchLinux and bug is gone. 

For reference - 
https://github.com/archlinux/svntogit-packages/commits/packages/xfwm4/trunk
