### ISSUE TITLE
Follow up of #PR https://github.com/brave/brave-core/pull/10300 - Incorrect response value is shown for `Default was Brave, did not switch`

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#18909]
## Description 

Follow up of #PR https://github.com/brave/brave-core/pull/10300 - Incorrect response value is shown for `Default was Brave, did not switch`
## Steps to Reproduce

   1. Clean profile 1.30.x nightly build
   2. Set the default SE as Brave in `brave://settings/search`
   3. Upgrade the profile to 1.33.x nightly build
   4. Open brave://local-state
   5. Response value is `0` for `Brave.Search.SwitchEngine` instead of `1`

## Actual result:

 Response value is `0` for `Brave.Search.SwitchEngine` stats
![image](https://user-images.githubusercontent.com/38657976/138246420-1e6cf2bd-eda3-4f08-ad37-302fd05f329f.png)

## Expected result:
As per https://github.com/brave/brave-browser/issues/18224#issue-1001270331, The Response value should be `1` for `Brave.Search.SwitchEngine` 

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.24 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Windows 10 Version 21H1 (Build 19043.1288)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mattmcalister @rillian

**Comment by rillian** [comment]
Thanks for testing!

The response value of `1` changing SE from Brave to Google is expected. As originally written, the question had more than permitted number of responses, so in consultation with @solso I combined the first two, which shifts everything else down by one.

Please see the table of expected values at the end of the test plan. I've now amended the statement of the question in #18224 to reflect the change. Sorry for the confusion!
