### ISSUE TITLE
`Stability and security will suffer` warning message upon launch

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#18907]
## Description 

The latest `Brave Nightly` shows a warning message `You are using an unsupported command-line flag: --translate-security-origin=https://translate.brave.com. Stability and security will suffer.`

## Steps to Reproduce

   1. Install the latest `Brave Nightly`.
   2. Launch the browser.
   3. Check if there is a warning message.

## Actual result:

![Untitled](https://user-images.githubusercontent.com/20608253/138236821-6e2a6520-2bed-4a96-a996-dabe45193c37.png)

## Expected result:
No warning message.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.24 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

**Comment by atuchin-m** [comment]
The result of https://github.com/brave/brave-browser/issues/18593
Nothing else should be broken, the problem is only with the message itself.
