### ISSUE TITLE
failing browser tests SearchEngineProviderServiceTest.{GuestWindowControllerTest,CheckDefaultTorProfileSearchProviderTest} on macos

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#18910]
failure log - https://ci.brave.com/job/brave-browser-build-macos-x64/4260/execution/node/144/log/
Both are failed due to timeout.

**Comment by wknapik** [comment]
And again https://ci.brave.com/job/brave-browser-build-macos-x64/4263/execution/node/144/log/?consoleFull.
