### ISSUE TITLE
Some special characters not recognized correctly

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#18912]
Example password which doesn't work: `SG8/8.27yUxScd`.

<img width="480" alt="2021-10-21_10-58-02" src="https://user-images.githubusercontent.com/3684187/138285348-07e8bb5a-64ee-4c49-a812-046a708d4af3.png">

The UI should also inform the user about the special characters that are permissible.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.86 Chromium: 95.0.4638.54 (Official Build) beta</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.194)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified password field now accepts all variations of symbols and characters</li>
        </ul>
      </td>
   </tr>
</table>
