### ISSUE TITLE
Rewards panel displays scrollbars on some displays

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#18914]
## Description 

On some displays or monitor configurations, the rewards panel displays scrollbars.

## Steps to Reproduce

*Unknown*

## Actual result:

![Screenshot from 2021-10-21 20-02-35](https://user-images.githubusercontent.com/5995084/138294742-913ae4f9-78f7-47f6-ad5d-61e441765726.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
@zenparsing Is this still relevant with WebUI-based Rewards panel?

**Comment by Miyayes** [comment]
Resolved with: https://github.com/brave/brave-browser/issues/22423
