### ISSUE TITLE
Brave Rewards Still Not Redeemable

### ISSUE THREAD

**Issue by monroemann** [brave/brave-browser#18916]
## Description 

I am still unable to collect any of my rewards regardless of how many times I try or how I change the screen resolution.  It's frustrating, because it's been this way for months, and I have lost out on my rewards each month since July.  So I've been needlessly looking at all these ads.  

## Steps to Reproduce
   1. Look at ads
   2. Gain BAT
   3. Try to redeem
   4. No matter how perfectly you match up the captcha, its says, "Not Quite"

## Actual result:
"Not Quite, Try Again"

## Expected result:
I can redeem my earned BAT

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.30.89 Chromium: 94.0.4606.81 (Official Build) (64-bit)
-- | --
Revision | 5a03c5f1033171d5ee1671d219a59e29cf75e054-refs/branch-heads/4606@{#1320}
OS | Windows 10 Version 20H2 (Build 19042.1237)
JavaScript | V8 9.4.146.21

## Version/Channel Information:
N/A

- Can you reproduce this issue with the current release? 
I believe that I have the latest version

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
N/A

- Does the issue resolve itself when disabling Brave Rewards? 
This is the issue

- Is the issue reproducible on the latest version of Chrome? 
N/A|

## Miscellaneous Information:
Hoping this can be fixed soon.

**Comment by Miyayes** [comment]
Since no reply in 2 weeks, closing this.
