### ISSUE TITLE
VAAPI broken on Brave 1.31.87 (Chromium: 95.0.4638.54)

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#18911]
## Description 
Seems that Chromium 95 broke VAAPI and that needs to be patched (Arch linux patch for Chromium 95: https://github.com/archlinux/svntogit-packages/commit/5316f38b605306e6f0627a8ee9e818550abec826#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a).
On Arch Linux Chromium 95 works by just passing `--enable-features=VaapiVideoDecoder`, Brave does not.
All flags passed to both browsers
```
--enable-features=OverlayScrollbar,VaapiVideoDecoder
--enable-gpu-rasterization
--enable-zero-copy
--disable-smooth-scrolling
--password-store=gnome
```

## Steps to Reproduce

   1. Try to enable VAAPI by passing `--enable-features=VaapiVideoDecoder` to both Chromium 95 and Brave 1.31.87
   2. Try to play video with accelerated codec with large enough resolution 720p+
   2. Check Media tab in inspector to see if hardware decoder is used: Chromium works, Brave does not
   3. NOTE: on some systems, additional flags have to be passed like `--use-gl=egl` or `--use-gl=desktop`

## Actual result:
Chromium
![Screenshot from 2021-10-21 12-53-02](https://user-images.githubusercontent.com/1936195/138263634-45d5d3b0-d1d5-4780-b7d0-769d7d1a70a4.png)
Brave
![Screenshot from 2021-10-21 12-54-52](https://user-images.githubusercontent.com/1936195/138263886-a3e0d688-3a7e-4fac-a8c2-0cd97e8a5eb7.png)

## Expected result:
Brave uses hardware accelerated VDAVideoDecoder like Chromium

## Reproduces how often: 
Always

## Brave version (brave://version info)
```
Brave	1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)
Revision	d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS	Linux
JavaScript	V8 9.5.172.21
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Command Line	/usr/lib/brave-bin/brave --enable-features=OverlayScrollbar,VaapiVideoDecoder --enable-gpu-rasterization --enable-zero-copy --disable-smooth-scrolling --password-store=gnome --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=AutoupgradeMixedContent,SafetyTip,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,PrefetchPrivacyChanges,LegacyTLSEnforced,DnsOverHttps,VaapiVideoDecoder,OverlayScrollbar --disable-features=AutofillServerCommunication,WebOTP,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,ConversionMeasurement,FederatedLearningOfCohorts,AppDiscoveryRemoteUrlSearch,ComputePressure,NotificationTriggers,TrustTokens,DirectSockets,ReadLater,TextFragmentAnchor,InterestCohortFeaturePolicy,FledgeInterestGroups,SettingsLandingPageRedesign,CopyLinkToText,NetworkTimeServiceQuerying,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,InterestCohortAPIOriginTrial,FirstPartySets,IdleDetection,PrivacySandboxSettings2,NavigatorPluginsFixed,SignedExchangeSubresourcePrefetch,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,LiveCaption --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/brave-bin/brave
Profile Path	/home/vuk/.config/BraveSoftware/Brave-Browser/Default
Variations	AdRewardsStudy:NextPaymentDay
BraveTalkStudy:Enabled
ConversionsStudy:NewDefaultPattern
EphemeralStorageStudy:Enabled
NativeCosmeticFilteringStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SpeedreaderReleaseStudy:Disabled
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, in patched version.

**Comment by duhdugg** [comment]
I'm seeing this fixed in 1.32.106. Can someone confirm the same?
