### ISSUE TITLE
Make Brave Available Through Microsoft Store

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#18913]
From Windows 11 (coming even to Windows 10), Microsoft has made a decision to let all kinds of apps enter the Microsoft Store, irrespective of app framework and packaging technology – such as Win32, .NET, UWP, Xamarin, Electron, React Native, Java and even Progressive Web Apps.

[Here](https://developer.microsoft.com/en-us/microsoft-store/) is the place to sign up for publishing Brave into the Microsoft Store.

Looking forward to know what Brave developers think of this.

Thanks!

**Comment by Dyras** [comment]
Kind of unrelated but there seems to be a fake Brave Browser in the store now.

https://www.microsoft.com/en-us/p/brave-x-browser/9pdb0hd9lv79?cid=msft_web_chart&activetab=pivot:overviewtab

**Comment by bsclifton** [comment]
@Dyras thanks for reporting- we'll follow up on that

**Comment by ccptr** [comment]
Users of Windows 10/11 S mode can only install programs from the Microsoft Store, so it'd be really nice for those of us who want S mode :) Having it in the MS Store would also increase publicity.

**Comment by mihaiplesa** [comment]
We're now live at https://apps.microsoft.com/store/detail/brave-browser/XP8C9QZMS2PC1T

**Comment by Dyras** [comment]
@mihaiplesa Absolute legends!

**Comment by ccptr** [comment]
I still cannot install it on my S mode laptop. I'm assuming it has something to do with it not requesting any permissions (i.e. not sandboxed?)

**Comment by mihaiplesa** [comment]
Another thing is also happening. After installing via store then going through a browser update Brave disappears from the app library and doesn't show as installed anymore in the store app.

**Comment by mherrmann** [comment]
@mihaiplesa i think i observed this behavior even just by closing and re-opening the Store.
