### ISSUE TITLE
Make launch in Tor button smaller

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#18923]
## Description 

The button to launch a webpage in Tor takes up a lot of space in the URL bar and competes with other actions. Make the button smaller to allow for more space

## Steps to Reproduce

   1. Go to a page that can launch in Tor
   2. See the launch in Tor button appear
 

## Actual result:

<img width="106" alt="Screen Shot 2021-07-14 at 9 41 50 AM" src="https://user-images.githubusercontent.com/2388823/138375685-38ad5590-621d-4643-aec5-b1ee12517583.png">

## Expected result:
<img width="196" alt="Screen Shot 2021-10-21 at 5 47 27 PM" src="https://user-images.githubusercontent.com/2388823/138375858-6dec3256-8eb6-4ee9-86ac-7fd573063fb0.png">

## Reproduces how often: 
Easily

## Brave version (brave://version info)

all versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Assets
Figma: https://www.figma.com/file/5THkuEtO2Ewn9LfqrHZP9a/?node-id=1042%3A19759

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.51 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)

new button | comparison to `release`
---------|---------
<img width="1312" alt="Screen Shot 2021-11-02 at 8 49 16 AM" src="https://user-images.githubusercontent.com/387249/139883826-11076f5a-f087-4568-8fde-350630903d8f.png"> | <img width="1199" alt="Screen Shot 2021-11-02 at 8 49 42 AM" src="https://user-images.githubusercontent.com/387249/139883838-0f6d8a58-2b1d-4d08-a037-1a109183e15b.png">
