### ISSUE TITLE
Linux Desktop Policy Question - Options for BAT, DoH & Tor

### ISSUE THREAD

**Issue by donateur** [brave/brave-browser#18921]
## Description 
**I wish to configure Brave using desktop policy on Linux but the options are not documented.**

_Wow you guys are busy now.  I'll be overjoyed if someone could just please point me in the right direction!_

Brave currently has a help page for Group Policy on Windows: https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy but there's no doco for Linux.

I wish to change the Linux Workstations of a security-conscious client to Brave from Chrome/Chromium.  However I cannot do this without disabling a few features (so users may not enable them).
1. BAT (they detect and strictly do not allow any crypto currency transactions on the network)
2. DNS over HTTPS (they need to enforce use of local DNS for security monitoring)
3. Tor in Private windows

_Hopefully these desires aren't controversial (this is a corporate business-use only network)_

* Are there options to control these through policy?
* What are the option names please?

We already configure Chromium using the json policy files supplied by them https://www.chromium.org/administrators/linux-quick-start so just need the extra features here and we can start using Brave!

## Brave version (brave://version info)
Latest Brave for Linux  - currently 1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)

**Comment by bd-g** [comment]
+1

**Comment by donateur** [comment]
> @donateur implementation will be the same (or at least close) as the Chrome one. Can you share what you're trying? There are only a few Brave Specific options at the moment; you can check for (`TorDisabled`, and `IPFSEnabled`)

Thanks, but to be honest, I've not tried anything as I wasn't sure how effective it would be at guessing the options.  I was really hoping someone could document what the options are!

**Comment by donateur** [comment]
PS: The options I'm asking about are specific to Brave, so I can't just copy what Chrom(ium) has documented.

**Comment by HamburgerJungeJr** [comment]
It seems to be changed from 
`/etc/chromium/policies/managed/`
to
`/etc/brave/policies/managed/`

At least for me it worked to set the AuthServerAllowlist policy.

Having the policies under the chromium path they were not applied
Source: https://github.com/brave/brave-core/commit/6f2f55b266e4e6abf2f401a18e0fed21fea47bfb

**Comment by donateur** [comment]
@HamburgerJungeJr thanks for that.

Does this mean there's two issues?

1. The issue I've reported, that there are no documented options for Brave-specific Browser configuration (things like BAT and TOR which aren't in Chromium upstream)
2. Brave policy on Linux needs to be applied to a unique directory  `/etc/brave/policies/managed/` (unlike Chromium upstream) but this isn't documented either

**Comment by HamburgerJungeJr** [comment]
Regarding 1: As @bsclifton said, there seem to be only the two mentioned brave-specific policies available. These are also documented at the windows-policy document. I could find only one source file containing these policies: https://github.com/brave/brave-core/blob/27cefaf47f00b618db2ce22d719904fb8719f2e7/script/policy_source_helper.py 
And there are no more listed, so I think there are no other brave-specific policies. 

But as I am no brave developer there might be some policies I'm missing.

Regarding 2: As far as I can tell: yes

**Comment by donateur** [comment]
@HamburgerJungeJr  thanks for your response.

> PS: Have a look at `brave://policy` If you check the checkbox in the right upper corner you can search all available policies. These are the names you have to enter in the config file.

I see;
* No options for BAT, token, background image or Brave News (we'd disable all)
* DnsOverHttpsMode (Not required given next option)
* BuiltInDnsClientEnabled (A Chromium policy which could be configured to "false" so that OS DNS is used. Hurray!)
* TorDisabled (Set to "true" I guess)

**Comment by donateur** [comment]
I'm going to close this and add a new request titled "Add policy options to allow disabling BAT on Linux".

**Comment by donateur** [comment]
Sorry, learning github, but I need to close this linking to #22029
