### ISSUE TITLE
Display language doesn't work [Windows]

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#18927]
## Description 
In settings - languages, I have set the language to english (only). Despite 'Display brave in this language' option being checked, the language both in browser and localized websites is my system language.

## Steps to Reproduce

   1.  windows system language is A, brave display language is B
   2. notice the browser displays websites and UI with language A

## Actual result:
described above

## Expected result:
UI and websites should display in language that I have set in brave language settings

## Reproduces how often: 
always

## Brave version (brave://version info)

<html>
<body>

Brave | 1.31.87 Chromium: 95.0.4638.54 64bit
-- | --
version| d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
os | Windows 10 Version 21H1 (Build 19043.1288)

</body>
</html>

**Comment by rame0** [comment]
I have the same issue.

I've also tried to set `ForcedLanguages` policy to `en-US`. Did not worked eather.

![image](https://user-images.githubusercontent.com/2233607/199067947-bcda2c84-f914-4e24-8135-1ed33089f495.png)

### Brave version (brave://version info)
Brave | 1.45.116 Chromium: 107.0.5304.91 (Официальная сборка) (64 бит)
-- | --
Версия | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
ОС | Windows 11 Version 21H2 (Build 22000.1098)
