### ISSUE TITLE
Swap transactions are shown as Send in panel

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#18929]
![Screenshot from 2021-10-21 15-32-44](https://user-images.githubusercontent.com/3684187/138440113-68a81468-cafd-4029-8214-11fd41964672.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified for swap transactions, panel shows<code>Swap</code> instead of <code>Send</code></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140921220-93a9d3f0-5a6d-4830-aa12-5d107270fcb7.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140921354-8c752831-8253-4ea0-948b-159f2034d8a9.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/140921109-ceafd35c-dd30-4265-8b75-e94cb170ee78.png>
      </td>
   </tr>
</table>
