### ISSUE TITLE
Enable horizontal scroll on read-only detailed views

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1892]
## Description
When looking at the detailed view of 3rd-party trackers blocked, Connections upgraded to HTTPS, and device recognition blocked, we should enable horizontal scrolling so that someone can see the full element URL.

## Designs 
3rd-party trackers detail view:
![3rd-party trackers breakdown](https://user-images.githubusercontent.com/2388823/52825477-b190b800-3071-11e9-8cf8-054dc8c3da60.png)

Connections upgraded to HTTPS detail view:
![https upgrades breakdown](https://user-images.githubusercontent.com/2388823/52825487-b7869900-3071-11e9-88db-30916ae6db91.png)

Device recognition detail view:
![shields device recognition breakdown](https://user-images.githubusercontent.com/2388823/52825492-bb1a2000-3071-11e9-998f-248befcdab6b.png)

For more CSS and plain text, check Abstract link: https://share.goabstract.com/68d70c4d-8c77-4588-9ee5-ce6418505c79

**Comment by tomlowenthal** [comment]
The designs for this should be part of #1934.

**Comment by karenkliu** [comment]
Closing this issue because comprehensive design specs and other issues are covered by #2565

**Comment by karenkliu** [comment]
### Reopening this issue because #2565 has been split into smaller issues.

**Comment by karenkliu** [comment]
This passed design QA :thumbsup:

**Comment by kjozwiak** [comment]
> ### Reopening this issue because #2565 has been split into smaller issues.

Removing `Dupe / Invalid / Not actionable` milestone as per the above.

**Comment by karenkliu** [comment]
Hi @cezaraugusto, I took a look at your latest updates at https://brave-ui-959w0ii2u.now.sh. The scroll seems to work correctly, but there's a minor visual design issue where the scroll area seems to leave a gap at the top + bottom. Please fix these issues:

![enable scroll design qa](https://user-images.githubusercontent.com/2388823/53120996-ff8d3c00-3507-11e9-9165-8b787acb3f8a.png)

**Comment by karenkliu** [comment]
Hi @cezaraugusto, your latest build to enable scroll looks good to go from the design side. 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1797
Horizonal scrollbars are enabled
![image](https://user-images.githubusercontent.com/34715963/56709188-2b9f8600-6720-11e9-9e59-96c77961b174.png)

Logged https://github.com/brave/brave-browser/issues/4227
