### ISSUE TITLE
Update button should look more Brave

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#18924]
## Description 

The Chrome update button still has Chromium branding; our update button should look more Brave.

## Steps to Reproduce

   1. Wait for an update
   2. Look at the update button in the toolbar

## Actual result:

![image](https://user-images.githubusercontent.com/2388823/138377025-b3226513-6482-47bf-bd1f-7f0c67527ba0.png)

## Expected result:
![image](https://user-images.githubusercontent.com/2388823/138377342-b802bb7c-15bf-4cbd-b778-c165fff9a9cd.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

all versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Assets
Figma: https://www.figma.com/file/sS3l8tqUFxt54MEiBTalUI/?node-id=1188%3A22928

**Comment by Coffeeling** [comment]
I'm an outsider, but would opine that gradienting text (and aggressive gradienting in general) gets into cancerous territory really fast, and I'd say the suggested look crosses that line, or is close to it. It works fine in light mode on pure contrast, but in the dark theme goes into hard to read territory. It's also unclear how it should respond to patch urgency: Upstream changes color.

A Google look as it may be, I think upstream does the job just fine. If we want to make the look more Brave, I'd look more towards ornamentation than going Miami Vice on the text itself. The dark mode version should favor the pink-purple over the blue, at least.

**Comment by aguscruiz** [comment]
@rebron I think the current implementation works just fine, specially with the green-yellow-red scheme signaling urgency. I'd say let's close this one out if it's ok for you too.

**Comment by rebron** [comment]
Closing as wontfix.
