### ISSUE TITLE
Add copy button to shields detail views

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1893]
The advanced views in shields aren't the easiest places to select text. We could add a little "copy" button to those entries to make it easier to use.

**Comment by tomlowenthal** [comment]
Designs for this will be combined with #1934 and show up in that issue.

**Comment by karenkliu** [comment]
@tomlowenthal What is the reason behind copying script text? Would someone using this feature want to copy all the scripts names at once, or select specific ones to copy the name of? What are they doing with the script text once they copy it? Are they pasting it somewhere?

**Comment by cezaraugusto** [comment]
closing per https://github.com/brave/brave-browser/issues/4243#issue-437430943. please re-open if I'm mistaken
