### ISSUE TITLE
Export all pending sign message requests to UI

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#18935]
Current we only show UI the oldest one when it calls `GetPendingSignMessageRequest`
We should export all the requests to UI so UI can show queueing sign requests

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.86 Chromium: 95.0.4638.54 (Official Build) beta</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.194)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10712>brave/brave-core#10712</a></li>
         <li>Verified able to sign messages</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/139675508-1a76b360-e51e-4b65-b3db-2f550b5e376f.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/139675223-25ae2a1a-feb5-4bf3-af56-1386a3e70558.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/139674910-1b601c5f-7169-4313-8f29-ab61e1cee157.png>
      </td>
   </tr>
</table>
