### ISSUE TITLE
In a private window, duckduckgo logo does not appear

### ISSUE THREAD

**Issue by japrozs** [brave/brave-browser#18931]
## Description
whenever i create a new private window and switch my search engine to duckduckgo, the search bar says 'search duckduckgo',  but there is a google logo next to it. i know its not a big thing but i just wanted to let you guys know

## Steps to Reproduce
Create a new private window

## Actual result:
![Screen Shot 2021-10-22 at 7 40 04 PM](https://user-images.githubusercontent.com/66138036/138468641-ec2cb948-4882-4988-b093-ea5d0d5db95e.png)

but when i change the search engine to duckduckgo

![Screen Shot 2021-10-22 at 7 40 45 PM](https://user-images.githubusercontent.com/66138036/138468754-7e6e4807-e455-464d-9c38-533a5421a7ae.png)

## Expected result:
It would be nice if it also showed the duckduckgo logo instead of the google logo next to the input field

**Comment by ShreyasSN** [comment]
Hi, is this issue still available?

**Comment by MadGanGithub** [comment]
Hey @japrozs, shall I work on this issue?

**Comment by RonakSurana-2001** [comment]
No I dont think this issue exists anymore
