### ISSUE TITLE
 txInfo.fromAddress should be stored as checksum address

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#18938]
We stored the from address from the input of `EthTxController::AddUnapprovedTransaction`
And we didn't convert it to be checksum address.
Also need to verify ImportAccount, ImportAccountFromJson, GetSelectedAccount, GetERC721OwnerOf, GetPendingSignMessageRequest

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.88 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10774>brave/brave-core#10744</a></li>
         <li>Verified rejected transactions are listed</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/140029952-7f7a0862-9eaa-464f-b1d3-6dc7e82d9186.png>
      </td>
      <td><img width=800  src=https://user-images.githubusercontent.com/17010094/140030012-7e78fbcb-a1b8-4c16-bfe1-2d71cbbc5e1f.png>
      </td>
      <td><img width=800  src=https://user-images.githubusercontent.com/17010094/140025767-f27e7b85-f7b0-4679-8717-55b1dc91ac00.png>
      </td>
   </tr>
</table>
