### ISSUE TITLE
Show transactions history

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#18940]
We need to show transactions history similar to desktop in 2 places:
- when any of assets clicked from visible assets list(it should show all transactions for the current assets on the selected network);
- when any of accounts clicked(it should show all transactions for the current account on the selected network);

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.100 x64 build
- Verified all transactions are shown when account details is opened
- Verified all token transactions are shown when a token is selected
----------
Verification passed on Samsung Tab A with Android 10 running 1.33.100 x64 build
- Verified all transactions are shown when account details is opened
- Verified all token transactions are shown when a token is selected
