### ISSUE TITLE
Fix focus indicators in shields

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1894]
## Description
All interactive UI elements in the Shields panel should have keyboard support and the appropriate focus treatment.

## Designs 
![shields focus states](https://user-images.githubusercontent.com/2388823/53043086-8bd22d00-343c-11e9-8209-92eb09eaaaad.png)

For more CSS and plain text, check Abstract link: https://share.goabstract.com/68d70c4d-8c77-4588-9ee5-ce6418505c79

**Comment by srirambv** [comment]
This is on Windows
![image](https://user-images.githubusercontent.com/17010094/47816352-4cff5680-dd29-11e8-9292-06376b366b92.png)

**Comment by tomlowenthal** [comment]
Karen is going to come up with a mock showing the specific outlines for each element.

**Comment by rossmoody** [comment]
This is something I can adjust in Brave-ui fairly easily. I think it’s a result of us padding the icons instead of margin.

**Comment by karenkliu** [comment]
@rossmoody the entire row should get the focus area because it is interactive, not only the icon.

**Comment by rossmoody** [comment]
Ah, gotcha. Yeah this prob requires further component behavior definition then. I suppose for accessibility the ideal would be to be able to tab from toggle to dropdown in each section.

**Comment by karenkliu** [comment]
@tomlowenthal @cezaraugusto 
![slice](https://user-images.githubusercontent.com/2388823/48648709-5e4d9180-e9be-11e8-8ffa-4e67da67508f.png)
Abstract link: https://share.goabstract.com/68d70c4d-8c77-4588-9ee5-ce6418505c79

**Comment by karenkliu** [comment]
Closing this issue because comprehensive design specs and other issues are covered by #2565

**Comment by karenkliu** [comment]
Reopening this issue because #2565 has been split into smaller issues.

**Comment by kjozwiak** [comment]
> Reopening this issue because #2565 has been split into smaller issues.

Removing the `Dupe / Invalid / Not actionable` label as per the above.

**Comment by karenkliu** [comment]
Hi @cezaraugusto, thanks for your updates on the focus treatment. Here is my design feedback:

![focus states design qa](https://user-images.githubusercontent.com/2388823/52372251-86bcb900-2a0c-11e9-865c-516d419c9ffa.png)

**Comment by karenkliu** [comment]
Hi @cezaraugusto, thanks for your update! After hearing your feedback, I think the best workaround is to have the focus indicator on *part* of the row and not overlapping the toggle or dropdown (I've updated the spec in the OP as well):

![shields focus states](https://user-images.githubusercontent.com/2388823/53043292-000cd080-343d-11e9-8739-6a4c64439cde.png)

Everything else for the focus looks great.

**Comment by karenkliu** [comment]
Hi @cezaraugusto, your latest build for these focus states looks good to go from the design side. :+1:

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1797
Checked indicators on main shields page and subpages.
