### ISSUE TITLE
Show private key for accounts(for both primary and secondary)

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#18942]

**Comment by srirambv** [comment]
Blocked on #19971 as secondary account import is failing.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.103 x64 build
- Verified Private key option is shown for both primary and secondary(imported) accounts
- Verified able to view private keys for both primary and secondary(imported) accounts
----------
Verification passed on Samsung Tab A with Android 10 running 1.33.103 x64 build
- Verified Private key option is shown for both primary and secondary(imported) accounts
- Verified able to view private keys for both primary and secondary(imported) accounts
