### ISSUE TITLE
Add EIP1559 support

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#18941]

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.100 x64 build
- Verified EIP-1559 gas pricing is shown for both send and swap transactions
- Verified block explorer shows `Txn Type: 2 (EIP-1559)` for all submitted transactions

Default | Custom
-- | --
![image](https://user-images.githubusercontent.com/17010094/145034288-6d29160c-5fdd-4d66-8f90-09b6401a69fe.png) | ![image](https://user-images.githubusercontent.com/17010094/145034300-29d671a0-1e16-42ec-b2d9-d2c5e778f060.png)

-----------
Verification passed on Oppo Reno 5 with Android 11 running 1.33.100 x64 build
- Verified EIP-1559 gas pricing is shown for both send and swap transactions
- Verified block explorer shows `Txn Type: 2 (EIP-1559)` for all submitted transactions

Default | Custom
-- | --
![image](https://user-images.githubusercontent.com/17010094/145034958-9ca4d4be-2ae0-488e-a806-30fe16156241.png) | ![image](https://user-images.githubusercontent.com/17010094/145034978-d70bf4d2-949a-4962-8798-59dff7b01e1f.png)
