### ISSUE TITLE
What binary should i try?

### ISSUE THREAD

**Issue by HotelBellaMuerte** [brave/brave-browser#1895]
What binary should i try=
host: archlinux 64bit
cpu: amd

**Comment by Brave-Matt** [comment]
We're working on adding snap packages for Brave soon: https://github.com/brave/brave-browser/issues/1007
If you'd like to open a thread on our [Community website](https://community.brave.com) I'd be happy to discuss in greater detail with you. Thanks!

**Comment by rebron** [comment]
marking closed. Discussion belongs in community.

**Comment by bbondy** [comment]
Marking invalid milestone since no code landed for this closed issue.
