### ISSUE TITLE
Incorrect scale if browser is full screen

### ISSUE THREAD

**Issue by Pushkin31** [brave/brave-browser#18964]
I looked for a solution to the problem - didn't find it

## Description 
Hello. When you first start the browser - the browser opens in full screen mode, if you minimize to a window and maximize back - the browser becomes larger than the screen diagonal.
The same occurs in the latest version of the browser chromium.
On chromium version 94.0.4606.81-1 - everything is fine.

## Steps to Reproduce

1. launch the browser
2. minimize in a window
3. expand to full screen

## Actual result:
<details>
<summary>Screenshot</summary>

![2021-10-24_22-54](https://user-images.githubusercontent.com/35974828/138610570-41bace78-374e-4585-89fc-076eabc4a429.png)

</details>

## Reproduces how often: 
Easily reproduced

## Brave version
Version 1.31.87 Chromium: 95.0.4638.54 (Official Build), (64 bit)

## Version/Channel Information:
1.31.87
I haven't tried any higher.

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome?
Yes, at least the version chromium.
On the version 94.0.4606.81-1 and there's no such thing before

## Operating system:
Arch linux, 5.14.14-arch-1

**Comment by gslin** [comment]
* https://bugs.chromium.org/p/chromium/issues/detail?id=1260821
* https://bugs.chromium.org/p/chromium/issues/detail?id=1261797

**Comment by ejybe** [comment]
Same here with 
OS: Arch Linux x86_64
Kernel: 5.14.14-arch1-1
DE: Xfce 4.16
WM: Xfwm4

on :
Brave 1.31.87 Chromium 95.0.4638.54
Brave 1.31.88 Chromium 95.0.4638.69

**Comment by ddillert** [comment]
It seems to be a known bug in Chrome:

https://bugs.chromium.org/p/chromium/issues/detail?id=1261797&q=maximize&can=2

There is another workaround using the Fill Window option in XFCE, which can be set in Window Manager > Keyboard and then set a shortcut for Fill Window. I found it here:

https://unix.stackexchange.com/questions/674540/chrome-window-gets-too-big-when-maximizing-on-linux-mint-xfce

This way, there is no title bar and Brave maximizes correctly.

**Comment by openbit64** [comment]
Please close this issue.

**Comment by rabinadk1** [comment]
Fixed using this patch in Arch Linux: https://gitlab.xfce.org/xfce/xfwm4/-/commit/488288f6e35d5d3dc077e87fe2ed83129692f62e
