### ISSUE TITLE
Shields disabled on private window

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1897]
## Description 

Shields disabled on private window

## Steps to Reproduce

Reproducible step 1 - with old user data
   1. Delete dev user data
   2. Install very old dev release (ex, https://github.com/brave/brave-browser/releases/download/v0.50.13/Brave-Browser-Dev.dmg)
   3. Launch normal browser window and quit
   4. Delete installed old dev release w/o deleting user data
   5. Install latest dev release
   6. Open private window and check shields is off

Reproducible step2 - with clean profile with latest version
   1. Launch browser with clean profile 
   2. Load www.brave.com and toggle off and toggle on brave shields with normal window
   3. Open private window and load www.brave.com
   4. Check shields is on in private window

## Actual result:

Shields disabled on private window

## Expected result:
Shields should be enabled on private windows 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.1 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes. I was able to reproduce it on both dev and beta builds

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Issue originally reported by @Brave-Matt

**Comment by simonhong** [comment]
I also saw this one of my pc(can't reproduce on others).
However, I can't reproduce anymore after I removed user data.
I think there is a precondition to make this happen.

**Comment by kjozwiak** [comment]
I tried reproducing this with clean profiles using the STR mentioned above using `macOS 10.13.6 x64` but couldn't reproduce the issue:

* `0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)` - Couldn't reproduce
* `0.56.6 Chromium: 70.0.3538.67 (Official Build) beta (64-bit)` - Couldn't reproduce
* `0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)` - Couldn't reproduce

 I think @simonhong is right in that there's some type of precondition that's causing the above. @rebron also mentioned that he ran into this but couldn't reproduce with a new profile.

@srirambv can you reproduce this on your end with clean profiles?

**Comment by srirambv** [comment]
I can't reproduce it on a clean profile or on a new people profile on both Dev/Beta. It only shows up on an upgraded profile on both Dev and Beta.

**Comment by kjozwiak** [comment]
> I can't reproduce it on a clean profile or on a new people profile on both Dev/Beta. It only shows up on an upgraded profile on both Dev and Beta.

Thanks @srirambv, I edited the above STR and mentioned that it doesn't happen with clean profiles so it doesn't confuse dev's looking into this. We'll need to find the STR and edit the original issue.

**Comment by Brave-Matt** [comment]
Just had someone report this, and I too now see this happening on both Dev and Beta, release version seems to be fine.
User report:
https://www.reddit.com/r/brave_browser/comments/a1vnw8/shields_not_on_in_incognito_mode/

**Comment by Brave-Matt** [comment]
+ 1 from Twitter:
![image](https://user-images.githubusercontent.com/3299098/49489805-8bdd6c00-f801-11e8-8eac-b8620d7a73ec.png)

**Comment by simonhong** [comment]
I found the reproduce step and updated in description @srirambv @kjozwiak

**Comment by lukemulks** [comment]
I am able to consistently repro this issue in Windows on multiple sites in private windows (Dev Channel). 
Version 0.60.3 Chromium: 71.0.3578.98 (Official Build) dev (64-bit)

Not able to repro in GA. 
Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

* Verified both scenarios from issue description

**Comment by Werve** [comment]
Hello,
I noticed that there is this problem with the latest release version of Brave. 
In incognito mode the shields are disabled on all sites by default.
<html>
<body>


Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit) 
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 10 Version 21H2 (Build 19044.1706)


</body>
</html>
