### ISSUE TITLE
Text is out of bounds on adaptive captcha max attempts reached modal for translations

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#18971]
Follow up to https://github.com/brave/brave-browser/issues/15600

## Steps to Reproduce

1. Clean profile
1. Run Brave in Polish PL locale
1. Enable Rewards and Ads
1. Schedule a captcha for your payment ID
1. Trigger unblinded tokens refill
1. Click `Rozwiąż`
1. Fail captcha till you get max attempts reached modal

## Actual result:

Text is out of bounds
![image](https://user-images.githubusercontent.com/34715963/138703554-77412502-ab0a-4563-9b1a-eb75c43b8df0.png)
![image](https://user-images.githubusercontent.com/34715963/138336841-ec29bf33-97a8-4b8c-a096-3b6d4d1c6a3e.png)

## Expected result:
Text is within bounds

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.32.76 Chromium: 95.0.4638.54 (Official Build) beta (64-bit)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Ubuntu 18.04 LTS

cc @emerick @tmancey @jsecretan @brave/legacy_qa @rebron @mkarolin

**Comment by mkarolin** [comment]
I think we can probably shorten the text a bit. Would just saying `Skontaktuj się z pomocą techniczną` be an acceptable replacement @btlechowski? It seems the current translation actually is saying something like "contact technical support department!" (there's no ! in the original either 😄 ).

Additionally, we can probably make the button grow with the text. It's not pretty but it's better than the text sticking out. Something like:

![image](https://user-images.githubusercontent.com/41635752/159744733-48b26e60-ab7a-4a33-adc0-087c4fb9dc5d.png)

![image](https://user-images.githubusercontent.com/41635752/159744830-c0943710-b8a1-4764-9893-6f03b82d8b22.png)

**Comment by btlechowski** [comment]
@mkarolin `Skontaktuj się z pomocą techniczną` works great! Thanks!

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.87 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/167379522-9ba03bf6-6232-4f55-8103-4fafc97a667e.png)
