### ISSUE TITLE
Allow folks to enable File System API with a Flag

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#18979]
could i bug you to change the Native File System API feature from “off with no way to enable” (what it is currently) to “disabled by default but enable-able with a flag”?

**Comment by mkarolin** [comment]
Test plan:

1. Start Brave
2. Navigate to **https**://brave.com
3. Right-click and select Inspect to open DevTools
4. In the DevTools, select Console tab
5. Paste the following code in the Console window: `self.showOpenFilePicker()`

**Expected result:**
`Uncaught TypeError: self.showOpenFilePicker is not a function`

6. Navigate to brave://flags
7. In the search box type `file-system-access-api`

**Expected result:**
`File System Access API` item is shown

8. Change the File System API item's status to `Enabled`
9. Click on the `Relaunch` button
10. Once the browser restarts, repeat steps 2 - 5

**Expected result:**
`Open` file picker dialog is shown

**Comment by mkarolin** [comment]
Note: File System Access API is not available for Android yet. See: https://bugs.chromium.org/p/chromium/issues/detail?id=1011535

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.33.51 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)

### Steps:

1. Start Brave
2. Navigate to **https**://brave.com
3. Right-click and select Inspect to open DevTools
4. In the DevTools, select Console tab
5. Paste the following code in the Console window: `self.showOpenFilePicker()`

**Expected result:**
 `Uncaught TypeError: self.showOpenFilePicker is not a function`

<img width="973" alt="Screen Shot 2021-11-02 at 8 56 50 AM" src="https://user-images.githubusercontent.com/387249/139891204-b485bea0-ff2c-4093-90ef-bcd16c074f1f.png">


6. Navigate to brave://flags
7. In the search box type `file-system-access-api`

**Expected result:**
 `File System Access API` item is shown


example | example
---------|---------
<img width="973" alt="Screen Shot 2021-11-02 at 8 57 17 AM" src="https://user-images.githubusercontent.com/387249/139891644-4dbffa86-d0cd-46cd-8159-eae1e3cb1c07.png"> | <img width="973" alt="Screen Shot 2021-11-02 at 8 57 39 AM" src="https://user-images.githubusercontent.com/387249/139891651-17689b41-dadb-40c4-a555-7f4f4d15cd71.png">


8. Change the File System API item's status to `Enabled`
9. Click on the `Relaunch` button
10. Once the browser restarts, repeat steps 2 - 5

**Expected result:**
 `Open` file picker dialog is shown

<img width="973" alt="Screen Shot 2021-11-02 at 8 58 03 AM" src="https://user-images.githubusercontent.com/387249/139891444-0ad572ad-06d2-4b8e-95dd-a00d3853b0fd.png">

**Comment by jimmywarting** [comment]
Borrowing this thread a bit. but may i ask what the reasoning behind having it disabled by default?

**Comment by pes10k** [comment]
bc users giving websites direct access to their local disk (even behind a permission) is a huge footgun that is very likely to be abused and harm some users.  

We're interested (resources permitting) on supporting the origin filesystem (file system like API but not tied to the actual file system), but do not plan to enable the over all File System API

**Comment by guest271314** [comment]
> bc users giving websites direct access to their local disk (even behind a permission) is a huge footgun that is very likely to be abused and harm some users.

When users write to `localStorage` or private origin filesystem that data is written to the users' local disk, and is accessible, readable, see [How to write into a file (in user directory) using JavaScript?](https://stackoverflow.com/a/36098618).

What about cookies?

I don't get the top-down, hierarchical organizational idea that users are not capable of making their own decisions on their own machines about what they enable or disable. 

If you don't want to write files to the local filesystem don't do so on your own machine. What you decide to do on your own machine does not translate to all users in the known universe must do as you say and do on their own machines.

**Comment by guest271314** [comment]
> bc users giving websites direct access to their local disk (even behind a permission) is a huge footgun that is very likely to be abused and harm some users.

```
const a = document.createElement("a");
a.download = "direct_access_to_local_filesystem.txt";
a.href = "data:text/plain,direct access to their local disk";
a.click();
```

**Comment by trcrsired** [comment]
Why is this not working on Android?
