### ISSUE TITLE
Brave crashes on --app-id flag

### ISSUE THREAD

**Issue by samsapti** [brave/brave-browser#18972]
## Description 

Starting Brave with `--app-id` (after installing a PWA) flag causes it to crash. The browser never opens. If I however first start it with an invalid argument to `--app-id` and then with the valid one, it works fine, but next time it's run it crashes again. Attached is a trace made with the `--trace-startup` flag and the proper `--app-id` argument, where the instance crashed, on Artix.

## Steps to Reproduce

   1. Install any PWA
   2. Launch Brave with the proper `--app-id` argument

## Actual result:

Browser doesn't start.

## Expected result:
Browser should start as normal

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

```
Brave: 1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)
Revision: d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS: Linux
```
Installed on Artix Linux via AUR package `brave-bin` and on Fedora Workstation 35 through official Brave DNF repository. Reproduces on both system (also before upgrade to Fedora 35).

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Haven't tried.
- Can you reproduce this issue with the nightly channel? Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? Haven't tried.

## Miscellaneous Information:

Issue doesn't occur on previous release version `1.30.89`.

[chrometrace.log.zip](https://github.com/brave/brave-browser/files/7411564/chrometrace.log.zip)

**Comment by theanonymousexyz** [comment]
Bug still present in version `1.31.88`.

**Comment by theanonymousexyz** [comment]
Also present on `1.31.91`.

**Comment by theanonymousexyz** [comment]
UPDATE: Bug doesn't occur if a Brave window is already open.

Bug still present on version `1.32.106`.
