### ISSUE TITLE
Set `ServiceWorkerTerminationOnNoControllee` to True

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#18980]
Chromium is testing a feature that would tie service worker lifetimes to their controlling documents.  This matches (mostly) Firefox and Safari.  This is a very good thing

https://source.chromium.org/chromium/chromium/src/+/main:content/public/common/content_features.cc;l=692;drc=5539ecff898c79b0771340051d62bf81649e448d

**Comment by mkarolin** [comment]
@pes10k, it looks like just enabling `kServiceWorkerTerminationOnNoControllee` feature is insufficient.

The default timeout for the feature is set to a max int value via this feature param: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/service_worker/service_worker_version.cc;l=72.

The param value is changed via field trials, which we don't have set (see https://source.chromium.org/chromium/chromium/src/+/main:content/browser/service_worker/service_worker_version.cc;l=823 and https://source.chromium.org/chromium/chromium/src/+/main:content/browser/service_worker/service_worker_version.cc;l=1230)

**Comment by pes10k** [comment]
Could we hardcode in the value of 2sec (to match https://github.com/brave/brave-core/blob/9a2161c47a22fcc71fcac40122eefff749dddc2c/browser/ephemeral_storage/ephemeral_storage_browsertest.cc#L47), or if thats tricky, 0 (assuming that means close immediately when there are no more controllers?)

**Comment by atuchin-m** [comment]
This feature is disabled in chromium right now and there are no active experiments with it.

I've found only one trace that chromium had enabled the experiment. [It was ](https://bugs.chromium.org/p/chromium/issues/detail?id=1114874&q=ServiceWorkerTerminationOnNoControllee&can=1)more than a year ago.

So in theory we can enable it, the CL/feature's code looks clean.
As for the timeout IMHO it should be greater than zero (because a SW can do some work after).
I see that in Firefox a service worker runs about 15-30 sec after closing the related page.
So better to set a similar limit.


But for some reasons chromium hasn't rolled this experiment (webcompat problems?) and this looks suspicious.

**Comment by pes10k** [comment]
15 or 30 seconds is fine with me.  I'm just eager to avoid the current situation, where (effectively) the SW can continue as long as its doing work (and the system isn't under resource pressure).

Would that be an acceptable way forward @atuchin-m and @mkarolin ?

**Comment by atuchin-m** [comment]
Ok, 30 sec is fine, I've prepared a PR.

Possible steps for QA:
1. launch browser with a clean profile
2. open a tab with `https://twitter.com/`
3. Go to `brave://serviceworker-internals/`, find the service worker and check status: RUNNING
4. Close the twitter.com tab
5. Go to `brave://serviceworker-internals/`, check the status. Should be RUNNING
6. Wait 30 sec and look at the status. Should be RUNNING (before the fix) or STOPPED(after the fix, changed from RUNNING after 30 sec timeout)
7. Open the site again and check that it works fine.

**Comment by atuchin-m** [comment]
@pes10k Do we want to enable the feature explicitly in the code? Or start with deploying it using griffin and enabling in the code after some time?

**Comment by pes10k** [comment]
I think default on, with the ability to switch off in Griffin if something unexpected happens, is good

**Comment by atuchin-m** [comment]
@pes10k 
Do you have an example of such a long-living service worker?
I've tried to create one but failed.
There are more mechanisms to kill SW by inactivity/irresponsibility: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/service_worker/service_worker.mojom;l=136-147?q=ServiceWorkerDefaultIdleDelayInSeconds&start=11

**Comment by pes10k** [comment]
> Do you have an example of such a long-living service worker?

Twitter has one 

> It seems that kServiceWorkerDefaultIdleDelayInSeconds is the actual and more correct way to terminate such SWs.
> And ServiceWorkerTerminationOnNoControllee has webcompat issues with inflight requests.

The goal is to kill service workers, even if they're not idle though, when they're running at times user's wouldn't expect though.  For example, the twitter one above wants to run more or less constantly.

**Comment by atuchin-m** [comment]
@pes10k I've tried Twitter before.
SW will stop in 30 sec after closing the tab.

Idle in terms of this features is not processing events or pushes. SetInteval or similar JS don't count.

**Comment by pes10k** [comment]
> SW will stop in 30 sec after closing the tab.

But it also starts running the moment the browser is open, even w/o a twitter tab being open, no?

**Comment by atuchin-m** [comment]
No. An event is needed to start it (fetch, push, background sync)

**Comment by pes10k** [comment]
Ah, i see, i must have been mistaken something waking up from background sync with a long lived service worker.  Apoloiges, i dont have an example on hand then

**Comment by iefremov** [comment]
@pes10k maybe you have any additional info about how Chromium is testing the feature?
So far it seems that it is abandoned and there are other things that stop workers, thus we shouldn't enable.

**Comment by atuchin-m** [comment]
If we have afraid that in some cases SW will run for a long time, we should find/write an example of such SW.
I've tried several approaches to write one: js timers(SetInterval), process the push for a long time, enqueue a lot of events + slowly process them. In all cases, SW will be killed after some time.

For now, It seems that the chromium idle timeout fixed the problem completely.
Therefore I suggest closing this ticket.
WDYT @pes10 ?

**Comment by pes10k** [comment]
Okie dokie, I am happy with that outcome.  Apologies for the error on my end, and thank you both very much for looking into this.
