### ISSUE TITLE
Full Screen Overextended on XFCE | Arch Linux

### ISSUE THREAD

**Issue by openbit64** [brave/brave-browser#18989]
## Description 
The full screen gets "overextended" on XFCE. Please fix this I have provided an Imgur link below to show you how it looks in full screen. Also is this a Chromium Issue, if it is, Please fix it.

## Actual result:
https://i.imgur.com/STpx39E.png

## Brave version (brave://version info)

Version 1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)

**Comment by openbit64** [comment]
Now it works on my machine.

**Comment by victorqribeiro** [comment]
what did you do to fix this? mine's still broken

**Comment by rabinadk1** [comment]
Fixed using this patch in Arch Linux: https://gitlab.xfce.org/xfce/xfwm4/-/commit/488288f6e35d5d3dc077e87fe2ed83129692f62e
