### ISSUE TITLE
Default wallet handling to not special case MetaMask

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#18982]
Description and test plan:

- Settings will have these options for the default wallet: Default Wallet: [ `Brave Wallet (prefer extensions)` | `Brave Wallet` | `Crypto Wallets (Deprecated)` | `None` ]
- By default let all Dapps overwrite window.ethereum to be the Dapp provider.
- If the user explicitly goes to settings and picks `Brave Wallet` then we restrict extensions from overwriting window.ethereum.
- Removes some old code that we don't use anymore.
- Migrating from a profile where we only had Crypto Wallets will work now by changing everyone to `Brave Wallet (prefer extensions)`. The only exception is when the setting is `None`, it will retain that.
- Migrating from a profile where we had the new wallet (like Nightly) will work now by changing everyone to `Brave Wallet (prefer extensions)`.  The only exception is when the setting is `None`, it will retain that.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10683>brave/brave-core#10683</a></li>
         <li>Verified on clean install default available options are [<code>Brave Wallet (Prefer Extensions)</code> | <code>Brave Wallet</code> |  <code>None</code> ]</li>
         <li>Verified on clean install default is set to <code>Brave Wallet (Prefer Extensions)</code></li>
         <li>Verified changing default wallet from <code>Brave Wallet</code> to <code>Brave Wallet(Prefer Extensions)</code> requires to load the Dapp in a new tab to take effect</li>
         <li>Verified changing default to extensions allows to overwrite the <code>window.ethereum</code></li>
         <li>Verified when <code>Brave Wallet</code> is not set as default, a persistent banner is shown</li>
         <li>Verified user can dismiss the banner, reloading the wallet page shows the banner again</li>
         <li>Verified the default banner is only shown when MM or other wallet is installed and <code>Brave Wallet (Prefer Extensions)</code> is set as default</li>
         <li>Verified <code>Crypto Wallets (Deprecated)</code> is only shown when Crypto Wallet is enabled on previous version and upgraded</li>
         <li>Verified even when <code>Crypto Wallets (Deprecated)</code>  is available post upgrade, <code>Brave Wallet(Prefer Extensions)</code>  is still set as default </li>
         <li>Verified user can enable <code>brave://flags/#ethereum_remote-client_new-installs</code> flag and still use the deprecated extension</li>
         <li>Verified except when <code>None</code> is set as default, for all other values, <code>Brave Wallet(Prefer Extensions)</code>  will be set as default when migrated</li>
        </ul>
      </td>
   </tr>
</table>
