### ISSUE TITLE
Change "Ads" title to "Brave Private Ads" in Brave Rewards settings page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18983]
## Description

Change "Ads" title to say "Brave Private Ads"

![image](https://user-images.githubusercontent.com/11497541/138766671-8dc73088-a19d-445f-b4e3-b08c9446e1e9.png)

## Notes

For translators: Translate "Private Ads" portion, but not "Brave" portion.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave

Brave | 1.35.56 Chromium: 97.0.4692.56 (Official Build) nightly (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Confirmed the title now reads `Brave Private Ads` in `brave://rewards`

`nightly` | `release`
---------|-----------
![nightly-private-ads](https://user-images.githubusercontent.com/387249/147367320-0c03487d-b2d1-4329-bc19-73007327aba1.png) | ![current-release](https://user-images.githubusercontent.com/387249/147367323-e657b437-4835-4d97-b4f7-6d8bd8bc3784.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using `Brave 1.36.75, Chromium 98.0.4758.66` on a `Google Pixel XL` running `Android 9.0`.

Confirmed it now reads `Brave Private Ads` on `brave://rewards`; compared to `1.34.81`.

`before` | `after`
---------|-------
![Screenshot_20220127-142634](https://user-images.githubusercontent.com/387249/151455591-59560ad1-15d0-4cd3-a35d-f6944d152bce.png) | ![Screenshot_20220127-142745](https://user-images.githubusercontent.com/387249/151455629-90732305-dfd6-447f-8e9e-6cde0fdfd930.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.98 x64 build
- Verified `Brave Private Ads` is set as the heading for ads settings section
- Verified the new text is reflected when ads is enabled or disabled and in the ads details view

Rewards Page | Ads Setting page
-- | --
![image](https://user-images.githubusercontent.com/17010094/151754091-6daf04f4-ccda-4d7f-8135-8b2a122f3ecf.png) | ![image](https://user-images.githubusercontent.com/17010094/151754114-5043a760-ba3c-4cb1-a474-9ca78631026f.png)
