### ISSUE TITLE
Auto Focus on SelectedAccount in ConnectWithSite Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#18992]
## Description 
We need to Auto Focus on the `SelectedAccount` in the the `ConnectWithSite Panel` account list.
For if a user has a lot of accounts and the `SelectedAccount` is at the bottom of the list, the `AutoSelected` `SelectedAccount` will be out of view in the list and the user will not know that they are allowing permission to connect to a site.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.86 Chromium: 95.0.4638.54 (Official Build) beta</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.194)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10743>brave/brave-core#10743</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/139680963-4ded54a8-3918-4235-b2eb-8b764123c9ff.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/139681471-8c8c1b4d-14b1-4177-8ba7-39f9f1e375e8.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/139681343-2d9fa227-b9db-4e1d-8eae-98bf7bd7eea9.mov>
      </td>
   </tr>
</table>
