### ISSUE TITLE
Show confirmation of resetting wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18997]
## Description 

Currently we only show the confirmation before resetting the wallet. When you type 'yes` instead of `Yes` the wallet doesn't reset and there is no confirmation about whether reset was a success or failure

## Steps to Reproduce

   1. Go to `brave://settings/wallet`
   2. Click on `Reset wallet`
   3. Type `yes` and click enter, modal closes wallet isn't reset and there is no confirmation of it
   4. Click `Reset wallet` again
   5. Type `Yes` and click ok. Wallet is reset but no confirmation

## Actual result:

No confirmation of a successful/failure in resetting the wallet

## Expected result:
Should show a confirmation of success

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.33.32 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)
-- | --
Revision | `d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy @jamesmudgett

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.69 Chromium: 97.0.4692.56 (Official Build) dev (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. clicked on the wallet icon on the browser toolbar
4. clicked `Get Started`
5. entered a password, twice
6. went through code words (12)
7. confirmed my empty wallet was created
8. loaded `brave://settings/wallet`
9. clicked on `Wallet`
10. clicked on `Reset Wallet`
11. typed `Yes` and clicked `OK` (confirmed other responses silently failed, closing the dialog)
12. confirmed my wallet -- in the other tab -- was now reset

example | example | example
---------|---------|----------
<img width="948" alt="Screen Shot 2021-12-30 at 1 45 50 PM" src="https://user-images.githubusercontent.com/387249/147790289-ac91c158-8d75-4876-8735-2c399b437143.png"> | <img width="948" alt="Screen Shot 2021-12-30 at 1 45 57 PM" src="https://user-images.githubusercontent.com/387249/147790306-058903ea-17c7-4059-9e4b-397e5032387c.png"> | <img width="948" alt="Screen Shot 2021-12-30 at 1 46 03 PM" src="https://user-images.githubusercontent.com/387249/147790314-c53406f1-c950-4453-8865-820dc0ee18e0.png">

**Comment by kjozwiak** [comment]
Removing `QA Pass-macOS` as this was reverted from `1.35.x` and will need to be retested with `1.36.x` just in case 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified successfully reset message is shown once wallet is reset</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/153817390-bf3a1cce-6fc1-443f-875b-2d536f50d081.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/153819086-ee205c93-71d6-436f-a1e2-b7c34413410f.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/153819058-bbd3acd5-c8f3-42ee-9111-ef56b8e9c748.png>
      </td>
   </tr>
</table>
