### ISSUE TITLE
Add menu to allow to edit/remove networks on wallet page

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19004]
- Add menu like in ipfs keys to Edit/Remove networks
- Add hand cursor for double click  indication

![image](https://user-images.githubusercontent.com/2965009/138910847-4eb02a7d-8240-4624-a764-67364e443e4e.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.33.93 Chromium: 96.0.4664.45 (Official Build) beta (arm64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified menu has two entries for Edit and Remove
- Verified clicking on Remove shows confirmation before removing it
- Verified clicking on edit brings up the edit modal
- Verified able to successfully remove the network from list after clicking ok on the confirmation popup

![image](https://user-images.githubusercontent.com/17010094/143901408-50734476-d8b5-41b7-b27b-a9d269190650.png) | ![image](https://user-images.githubusercontent.com/17010094/143901765-6b89c4e6-3a35-4715-a60c-97f6addaf1ff.png)
-- | --

-------

Verification passed on 

Brave | 1.33.93 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Windows 11 Version Dev (Build 22504.1010)

- Verified menu has two entries for Edit and Remove
- Verified clicking on Remove shows confirmation before removing it
- Verified clicking on edit brings up the edit modal
- Verified able to successfully remove the network from list after clicking ok on the confirmation popup

![image](https://user-images.githubusercontent.com/17010094/143902105-c76114b3-7b3e-42b5-9e2f-ab9480ca78a2.png) | ![image](https://user-images.githubusercontent.com/17010094/143902161-411be4d0-3249-4773-afe5-ce8b9e5f0956.png)
-- | --

-------

Verification passed on 

Brave | 1.33.93 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Linux

- Verified menu has two entries for Edit and Remove
- Verified clicking on Remove shows confirmation before removing it
- Verified clicking on edit brings up the edit modal
- Verified able to successfully remove the network from list after clicking ok on the confirmation popup

![image](https://user-images.githubusercontent.com/17010094/143902448-bdec5d91-1c6d-4b36-be31-cbdb7d1c8ce1.png) | ![image](https://user-images.githubusercontent.com/17010094/143902470-ed95c461-6e27-493f-9f03-d19741414d02.png)
-- | --
