### ISSUE TITLE
Brave Notification Ads Issue on MacOS Monterey

### ISSUE THREAD

**Issue by ianfife** [brave/brave-browser#19001]
## Description 

Brave icon has a cross through it in ad notifications upon updating to macOS Monterey (12.0.1)

## Steps to Reproduce

   1. Update to macOS Monterey
   2. Turn on Brave Rewards
   3. Wait for ad notification

## Actual result:

![image](https://user-images.githubusercontent.com/50230324/138887207-ed010fc0-ab05-4a91-a9d5-d2f6ff010a3e.png)

## Expected result:
Brave Icon is normal

## Brave version (brave://version info)

Version 1.31.87 Chromium: 95.0.4638.54 (Official Build) (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

May be fixable via uninstall/reinstall
MacBook Pro 2021 M1

**Comment by Brave-Matt** [comment]
A user in the thread linked above is reporting that this also appears to be happening (at least for them) with regular (allowed) website notifications -- so this may not be specific to Brave Ads:
https://community.brave.com/t/missing-notification-icon-in-macos/318720/13?u=mattches

**Comment by tmancey** [comment]
Closing issue as restarting macOS appears to resolve the issue. @ianfife can you please let me know if restarting does not resolve the issue. Thanks

**Comment by ianfife** [comment]
This was actually fixed (seemingly randomly) a couple months ago.

**Comment by tmancey** [comment]
@ianfife great news, thank you
