### ISSUE TITLE
Improve error message when Chain ID is already in use

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19005]
it would better to say something like Chain ID is already in use, unable to add network

![image](https://user-images.githubusercontent.com/2965009/138912100-e6ecf496-010e-467e-afea-0a4707e08928.png)

# Test plan
- Try adding chain ID 0x1 with other info filled out, it should give an error about the network being already added.
- I'm not sure how to get the other error, but for any other error it will return the old error. I have unit tests that cover both cases though.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.88 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified error message is more meaningful when trying to add a network with the same ChainID</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/140031247-1a2e1e46-2d34-42c7-94d7-e54b37ea37ca.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/140031352-11bdab8b-2048-4a9d-a7da-102bac6b78ab.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/140031155-e56d3cd2-8486-42d6-b80b-386fde847a74.png>
      </td>
   </tr>
</table>
