### ISSUE TITLE
Cannot connect my Ledger to the Keplr Wallet extension

### ISSUE THREAD

**Issue by CryptoNuragic** [brave/brave-browser#19003]
## Description 

Hi! I'm trying to connect my ledger wallet with Keplr and I cannot do it. I get the foolowing window and it freezes without letting me continue the process.
![Immagine 2021-10-26 163157](https://user-images.githubusercontent.com/70372742/138901322-71121d66-edf9-4b5f-8f3f-37072a84b713.png)
 thank you for your kind attention

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
Closing because no info, please feel free to respond and we'll re-open. We also need to know the version of Brave that you are using and if the native wallet was enabled by you or not.
