### ISSUE TITLE
Disable Send and Confirm buttons for insufficient funds

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19014]
## Description 
We need to disable the `Send` and `Confirm` buttons on the `Page` and `Panel` if the user has insufficient funds to make the transactions

 ![image](https://user-images.githubusercontent.com/40611140/138962551-c4149345-cbf7-4621-9139-a1b3bca7b32a.png)
 
 
![image](https://user-images.githubusercontent.com/40611140/138962625-6b4c3b09-1268-4dcb-a65e-07842385f09e.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.86 Chromium: 95.0.4638.54 (Official Build) beta</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.194)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/10733>brave/brave-core#10733</a></li>
         <li>Verified both panel and page shows insufficient funds message</a></li>
         <li>Verified insufficient funds message is shown when manually editing the gas price and goes beyond what is available to perform a transaction</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/139672860-e133c353-aff0-4e9e-b3b9-8b98d4e531d2.png><img src=https://user-images.githubusercontent.com/17010094/139673002-e2f8f96c-7e2a-4935-868d-ab3059dbfd5a.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/139671726-753d7565-8767-4d67-8133-ec1c1dea133b.png><img src=https://user-images.githubusercontent.com/17010094/139672311-d2ed71d8-55e8-46ea-9eff-02abad5d9377.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/139672532-6719f74d-a8f5-4570-94d3-808f2ec058d8.png><img src=https://user-images.githubusercontent.com/17010094/139672613-aaa8ee86-4376-45d8-ae8c-f2fb4040ea59.png>
      </td>
   </tr>
</table>
