### ISSUE TITLE
brave://wallet open while doing a transaction through the panel crashes

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19019]
This happens because we try to open the panel when it's already open.
The wallet page has a listener for new transactions and it opens up the panel with an API when it sees it.  

# QA test plan:
- Open up brave://wallet
- Open up the panel and go to the send tab
- paste an address and some eth
- press the send button

Actual results: It crashes
Expected results: It doesn't crash

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.86 Chromium: 95.0.4638.54 (Official Build) beta</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.194)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from issue description</li>
         <li>Verified no crash when trying to submit a transaction via panel</li>
        </ul>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.94 x64 beta build
- Verified test plan from issue description
- Verified no crash when trying to submit a transaction
------------
Verification passed on Samsung Tab A with Android 10 running 1.33.94 x64 beta build
- Verified test plan from issue description
- Verified no crash when trying to submit a transaction
