### ISSUE TITLE
Give a warning in UI when trying to send ETH or tokens to...

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19011]
Give a warning when trying to send ETH or tokens to...
- A contract address
- An account trying to send to itself

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.99 Chromium: 96.0.4664.35 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue descripton</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Same wallet address
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141344636-65e83779-2097-4c36-8726-1a3e35601a47.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141344313-c7462fb7-074f-4908-b4ba-7d76ac9d6b00.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141343832-e7fc4b61-2a4c-4343-bf6a-216c1d8c7e1e.png>
      </td>
   </tr>
   <tr>
      <td>Contract Address
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141345186-3fe7cec3-e886-4f3c-b818-cf2922f3d6d0.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141345264-598f5cef-145a-46f9-9bf2-8579c4dbf9d6.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141344837-2a52f080-15df-445c-8f01-f1002893084c.png>
      </td>
   </tr>
   <tr>
      <td>Same wallet address (panel)
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141344572-60c57cb9-94eb-46b3-9581-222266fe7085.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141344397-01dfd198-1ba7-4dac-8115-c31e9f2848aa.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141344002-98c58f8f-fb77-43e7-b80d-f1b790e23c1b.png>
      </td>
   </tr>
   <tr>
      <td>Contract Address (Panel)
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141345042-1de1275f-5236-403d-8cb0-359cd073c107.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141344966-8177afba-a03e-4804-9341-06f21bfdad39.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141345120-d72b9828-613e-41a7-9fba-c296ec0af236.png>
      </td>
   </tr>
</table>
