### ISSUE TITLE
We should notifyUserInteraction for the panel too, not just the page

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19013]
I noticed while testing that I got the keyring locked mid interaction.

# Test plan
- Change auto lock wallet setting to 1 minute
- Open up the panel and unlock it
- Keep the panel open and move your mouse around for more than a minute

The wallet should not lock itself.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.90 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from issue description</li>
         <li>Verified panel and page remains unlocked when the user is active</li>
        </ul>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.94 x64 beta build
- Verified auto-lock works as per setting
- Encountered #19831
-------------
Verification passed on Samsung Tab A running 1.33.94 x64 beta build
- Verified auto-lock works as per setting
- Encountered #19831
