### ISSUE TITLE
Add support for signing transactions with Trezor accounts

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19029]
## Steps to Reproduce

   1. Import Trezor accounts 
   2. Send money to Trezor accounts
   3. Send money from Trezor accounts

## Actual result:

Transaction failed

## Expected result:

Transaction successs

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10902>brave/brave-core#10902</a></li>
         <li>Verified able to sign transaction via Trezor wallet</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141759505-28d9582f-65e3-46a7-8654-6a30377cd53b.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141759587-4bef3ed6-31b1-47ee-b027-5e715d723150.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141759064-9d9dfff7-2d52-4ad7-800e-b20cc946ae5e.mov>
      </td>
   </tr>
</table>
