### ISSUE TITLE
no feedback/indicator when copying phrase from `Your recovery phrase` screen

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#19021]
## Description 

When a user clicks on `Copy` via the `Your recovery phrase` during wallet creation, there's no UI indicators that let the user know that the phrase was copied in the clipboard. I needed to paste it into a text file/URL bar to make sure it was actually copied before moving on the next step.

I think we should fix this for the initial launch as users might get nervous if they don't see any feedback when it comes to copying their phrase.

Even better, offer a way to export the key via a text file along side the `Copy` option. Let me know if this is a good idea and we can create a new issue/feature suggestion.

## Steps to Reproduce

   1. launch Brave and enable `brave://wallet` (new implementation)
   2. run through wallet creation till you reach the  `Your recovery phrase` phase
   3. click on `Copy` and notice there's no UI/UX indicators that the phrase was actually copied.

## Actual result:

When clicking on `Copy`, there's no UI/UX indicator that anything was actually copied into the clipboard.

## Expected result:

We should have some type of UI/UX indicator that lets users know that their phrase was copied/added into the clipboard.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.33.34 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Windows 11 Version 21H2 (Build 22000.258)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.56 Chromium: 97.0.4692.56 (Official Build) nightly (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Confirmed I got a `Copied` feedback message.

example | example
----------|----------
![copy-1](https://user-images.githubusercontent.com/387249/147368775-6da0bce4-5109-48f0-9f18-871e31af1e66.png) | ![copy-2](https://user-images.githubusercontent.com/387249/147368776-de3e13a1-3ec5-483e-9ea9-59324ddfaa58.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | 1adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}1
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified test plan from [brave/brave-core#11535](https://github.com/brave/brave-core/pull/11535)
- Verified clicking on the copy button changes the text from `Copy` to `Copied`
- Verified after 5 seconds it reverts back to `Copy`
- Verified works during onboarding and when doing manual backup
- Logged follow up issue [#20470](https://github.com/brave/brave-browser/issues/20470)


Onboarding (Copy) | Onboarding (Copied) | Backup Wallet (Copy) | Backup Wallet (Copied)
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/149159592-89569c73-e411-4bce-b609-37a10517e09f.png) | ![image](https://user-images.githubusercontent.com/17010094/149159537-760e6458-967d-4408-860e-0755fe3b4274.png) | ![image](https://user-images.githubusercontent.com/17010094/149159682-094ea38c-3ff4-4571-96ae-c97b30708752.png) | ![image](https://user-images.githubusercontent.com/17010094/149159723-46164090-f16d-4d34-b72a-f9d42a4cbd16.png)

-------
Verification passed on 

Brave | 1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | 1adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}1
OS | Linux

- Verified test plan from [brave/brave-core#11535](https://github.com/brave/brave-core/pull/11535)
- Verified clicking on the copy button changes the text from `Copy` to `Copied`
- Verified after 5 seconds it reverts back to `Copy`
- Verified works during onboarding and when doing manual backup
- Logged follow up issue [#20470](https://github.com/brave/brave-browser/issues/20470)

Onboarding (Copy) | Onboarding (Copied) | Backup Wallet (Copy) | Backup Wallet (Copied)
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/149160273-2f2278f7-fbb9-4b6d-bb1d-1c8f68ebd9d7.png) | ![image](https://user-images.githubusercontent.com/17010094/149160293-128a2890-ea9a-4c05-8318-64e33d6e8bdc.png) | ![image](https://user-images.githubusercontent.com/17010094/149160316-94c8f658-27f6-4e1d-b05b-e6ac88a6f941.png) | ![image](https://user-images.githubusercontent.com/17010094/149160335-2aedfd1a-1c77-48f7-9a63-8d663ec14fa7.png)

-------
Verification passed on 

Brave | 1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (arm64)
-- | --
Revision | 1adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}1
OS | macOS Version 12.1 (Build 21C52)

- Verified test plan from [brave/brave-core#11535](https://github.com/brave/brave-core/pull/11535)
- Verified clicking on the copy button changes the text from `Copy` to `Copied`
- Verified after 5 seconds it reverts back to `Copy`
- Verified works during onboarding and when doing manual backup
- Logged follow up issue [#20470](https://github.com/brave/brave-browser/issues/20470)

Onboarding (Copy) | Onboarding (Copied) | Backup Wallet (Copy) | Backup Wallet (Copied)
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/149158618-9b23cb46-cabc-4048-be73-22573f720be0.png) | ![image](https://user-images.githubusercontent.com/17010094/149158627-04f3abb2-3db3-4e0e-8cff-350fd3830d4d.png) | ![image](https://user-images.githubusercontent.com/17010094/149158631-f89c804b-53e2-4a60-9468-c1315505b858.png) | ![image](https://user-images.githubusercontent.com/17010094/149158635-b9b38461-b0ed-4e23-bf6f-76162415a372.png)
