### ISSUE TITLE
default off "ink skipping" urls instead of default on

### ISSUE THREAD

**Issue by kevinlawler** [brave/brave-browser#1902]
## Description 
text-decoration-skip-ink is on by default but this seems to be the wrong decision. seems to be an inherited mistake to me

https://duckduckgo.com/?q=chrome+ink+skipping&t=brave&ia=web

perhaps adding a toggle in the options in case someone wants it on

![unnamed](https://user-images.githubusercontent.com/376238/47727710-e7c53b80-dc2a-11e8-98c9-5725383e46fd.png)
image taken from an extension that disables it: https://chrome.google.com/webstore/detail/disables-ink-skipping-in/ibhigfbbjaeadpfgfhjgcoioddhhlbmf

**Comment by tomlowenthal** [comment]
This is the specified behavior for CSS: https://drafts.csswg.org/css-text-decor-4/#text-decoration-skip-ink-property . Sites which don't want this can change it via CSS. I don't think we should just ignore parts of the the CSS spec.

**Comment by kevinlawler** [comment]
I see. That does complicate things...

**Comment by rebron** [comment]
marking wontfix. Part of CSS spec and there is an extension to remove if really want to.
