### ISSUE TITLE
Some unit tests fail almost every time in the Windows ASAN pipeline

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#19031]
Same unit tests keep failing in the Windows ASAN pipeline for a long time:
* BatAdsAdPacingTest.NoPacing
* BatAdsAdPacingTest.PacingAndPrioritization
* BatAdsAdPacingTest.PacingDisableDelivery
* BatAdsAdPacingTest.SimplePacing

https://ci.brave.com/view/asan/job/brave-browser-build-windows-x64-asan/

**Comment by wknapik** [comment]
@iefremov yes, [here](https://ci.brave.com/job/brave-browser-build-windows-x64-asan/151/execution/node/119/log/?consoleFull)'s an example from today.

**Comment by iefremov** [comment]
Ah, correct, as @tmancey says those are timeouts. Perhaps, something expected with enabled asan.

**Comment by tmancey** [comment]
@wknapik others are reporting timeouts for tests with ASAN, i.e. https://github.com/att/ast/issues/673. This is not an issue with the tests. Can we not increase the timeouts?

**Comment by wknapik** [comment]
@tmancey https://github.com/att/ast/issues/673 was closed in July 2018. A lot has changed since then.

Last I heard the tests from this issue only time out in CI and not locally.

If tests pass locally, but time out on beefy CI VMs, that suggests a problem. Extending timeouts seems like sweeping that problem under the rug, rather than addressing it.

We should be heading in the direction of fewer differences between local and CI.

If we extend timeouts that were being exceeded, then we're also extending the run time for those tests. Also not the direction we want to be heading. I'd like to enable ASAN by default (at least in PRs), but for that to happen, those tests need to be stable and sufficiently fast.

If you think extending timeouts is the way to go, then we can do that.

I can assist with any changes in pipelines and/or investigations/debugging, just let me know what you'd like to do. Also, feel free to submit PRs against the [pipeline code](https://github.com/brave/devops/blob/master/jenkins/jobs/browser/brave-browser-build-windows-x64-asan.yml#L224) if that's easier.

**Comment by tmancey** [comment]
@iefremov your thoughts on this please?

**Comment by iefremov** [comment]
I agree that slow tests are a problem, and extending timeouts will only mask this problem.
We need to improve tests, but I'm not sure when it could be priorized.

Btw @wknapik do we known the duration difference between running these tests with/without asan?

**Comment by wknapik** [comment]
@iefremov 

[Here](https://ci.brave.com/view/asan/) are the ASAN pipelines:
* [Linux](https://ci.brave.com/view/asan/job/brave-browser-build-linux-x64-asan/) (test-unit: ~8.5min, test-browser: ~23min)
* [macOS](https://ci.brave.com/view/asan/job/brave-browser-build-macos-x64-asan/) (test-unit: ~10.5min, test-browser: ~49min)
* [Windows](https://ci.brave.com/view/asan/job/brave-browser-build-windows-x64-asan/) (test-unit: ~27.5min, test-browser: ~30.5min)

[Here](https://ci.brave.com/) are the regular pipelines:
* [Linux](https://ci.brave.com/job/brave-browser-build-linux-x64/) (test-unit: ~11min, test-browser: ~12.5min)
* [macOS](https://ci.brave.com/job/brave-browser-build-macos-x64/) (test-unit: ~12.5min, test-browser: ~28.5min)
* [Windows](https://ci.brave.com/job/brave-browser-build-windows-x64/) (test-unit: ~7.5min, test-browser: ~20.5min)

**Comment by iefremov** [comment]
@wknapik how realiable are these measurements? Hard to believe asan runs can be faster than normal

**Comment by wknapik** [comment]
@iefremov I just looked at recent execution times at the links provided.

It is indeed surprising that ut/bt on Linux and ut on macOS were faster with ASAN, but bt on macOS and ut/bt on Windows were slower with ASAN on Windows, as expected.

Those builds get exclusive access to the build node, so I'm not sure what could be behind this variance.
