### ISSUE TITLE
Decide how to handle native wallet flag and admin policy for controlling it

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19035]
With Wallet being enabled by default we should consider
1. Remove the flag entirely
2. Alternately change the flag to handle wallet functionality in browser

1 is pretty straight forward we won't have the flag in `brave://flags`
2 would be to make the flag more generic like enabling all wallet functionality or disabling all wallet functionality in the browser. So setting this flag to disable would remove the entry for `brave://setting/wallet` from browser settings and won't load `brave://wallet`

In addition to the above we should consider adding an admin policy to control the flag similar to what we did for Tor (#454 & #12426)

cc: @brave/crypto-wallets

**Comment by bbondy** [comment]
We should also review that changes in this PR are covered by the flag: https://github.com/brave/brave-core/pull/10852


```
brianjohnson  1:59 PM
shouldn't some of these like https://github.com/brave/brave-core/pull/10852/files#diff-d665c90359b8b4eb62a748f6fab0151aa41ed2b3cd3de704fd320ba176cd51e6R121 be behind the feature flag?
2:00
same here https://github.com/brave/brave-core/pull/10852/files#diff-ec9781bb0072659ae6dd0dd4607a48f1efc577d22dbb70d61688e33949a1fb36R79
2:01
https://github.com/brave/brave-core/pull/10852/files#diff-a41e51332bd7613044392e5f68853e6155e964eff947f0093b5b887ca6ebf3e8R312
2:01
https://github.com/brave/brave-core/pull/10852/files#diff-993c17882cc3b6e092ae1048b78ccf8d0501a9b33c46597f427f49065e2e8599R23
2:02
https://github.com/brave/brave-core/pull/10852/files#diff-9f59402a3e195c8f1fd5f29bc43270777f4bd61925130803869ae2e5c6f4cb5dL18
```
