### ISSUE TITLE
Letter C's in "BitCoin" and "LiteCoin" need to be lowercased in Brave Rewards: Add Funds

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#1903]
**Issue:** In Brave Rewards: Add Funds, the words "BitCoin" and "LiteCoin" feature a capitalized letter C. Bitcoin and Litecoin should not have their letter C's capitalized this way.

From Brave Rewards in 0.55.20, MacOS:

![image](https://user-images.githubusercontent.com/11497541/47736775-cb82c800-dc45-11e8-9fb1-7d2b78e654cf.png)
![image](https://user-images.githubusercontent.com/11497541/47736781-ce7db880-dc45-11e8-84b5-9392ee53e728.png)

**Sources:** 

* Spelling of Bitcoin from Satoshi Nakamoto's whitepaper. (This spelling is corroborated by the Wikipedia page.) 
![image](https://user-images.githubusercontent.com/11497541/47736861-fa00a300-dc45-11e8-9015-fd4214021042.png)

* Spelling of Litecoin from Wikipedia usage: 
![image](https://user-images.githubusercontent.com/11497541/47736919-1a306200-dc46-11e8-9eb7-1c7453263fe8.png)

**Comment by biskit1** [comment]
Can anyone explain to me how the file system works? (i.e where would the file containing the code for this be located?)

**Comment by NejcZdovc** [comment]
this needs to be fixed here https://github.com/brave/brave-core/blob/master/components/resources/brave_components_strings.grd#L412

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/52756643-596e9d00-3002-11e9-9913-f7d957a9c3f3.png)
