### ISSUE TITLE
Use same password field should be focused on tab after entering existing extension password

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19030]
## Description 

Use same password field should be focused on tab after entering existing extension password

## Steps to Reproduce

   1. Install MM or CW
   2. Enable native wallet
   3. Detects existing wallets and prompts to import account
   4. Enter existing account password and press tab
   5. Selects new password instead of use same password checkbox

## Actual result:

Selects new password instead of use same password checkbox when user presses tab after entering old password

## Expected result:
Use same password field should be focused on tab after entering existing extension password

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.33.34 Chromium: 95.0.4638.54 (Official Build) nightly (x86_64)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment]
Is going to require this update to brave-ui https://github.com/brave/brave-ui/pull/595

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified tab sets focus to checkbox for easier keyboard accessibility</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/140923543-ca058ba2-deaf-4548-bf05-89d3f3cadf8d.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/140923473-08c29c84-a88e-402e-9898-1cc1834dcb07.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/140923498-01398ce8-872f-40cf-b7f7-588b2fd0d206.mov>
      </td>
   </tr>
</table>
