### ISSUE TITLE
npm run sync branch_name doesn't switch branches correctly

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#19041]
This is really a fundamental issue with changing branches from code that exists inside the branch so the functionality will be restricted to init only (brave-browser repo)

**Comment by kjozwiak** [comment]
Closing after speaking with @bridiver. Both https://github.com/brave/brave-browser/pull/18731 & https://github.com/brave/brave-core/pull/10479 have also been merged into `1.33.x`.
