### ISSUE TITLE
Brave reading /etc/chromium/policies

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#19052]
## Description 

On Fedora linux systems, brave loads policy settings from `/etc/chromium/policies/managed` which is populated by the `fedora-chromium-config` package, installed by default on Fedora Workstation targets to support the project's gssapi sign-on system.

This results in a 'Your browser is managed by your organization' warning at the top of the settings page, which may be alarming for private users.

## Steps to Reproduce

   1. Install [Fedora Workstation](https://getfedora.org/en/workstation/download/) 35 (linux distro) on a vm
   2. Add brave-browser-beta [package feed](https://brave.com/linux/#fedora-28-centosrhel-8-1)
   3. `sudo dnf install brave-browser-beta`
   4. Launch brave, visit the settings page

## Actual result:

"Your browser is managed by your organization" appears at the top of `brave://settings`.

![Screenshot from 2021-10-27 10-26-38](https://user-images.githubusercontent.com/225102/139160459-3373b4c3-0274-469d-af07-a4502de7d66b.png)

## Expected result:

Since this makes tracking easier, I would expect brave to not load this chrome/chromium-specific configuration data.

## Reproduces how often: 

Only tried on my current laptop, which is a pretty recent install. Removing the `fedora-chromium-config` package also removes the warning from within brave.

## Brave version (brave://version info)

Brave	1.32.76 Chromium: 95.0.4638.54 (Official Build) beta (64-bit)
Revision	d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS	Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.65 Chromium: 96.0.4664.35 (Official Build) nightly (64-bit)
--|--
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | Linux

on Fedora 35 Workstation

<img width="1182" alt="Screen Shot 2021-11-05 at 4 12 07 PM" src="https://user-images.githubusercontent.com/387249/140588122-8df0263e-bd63-4b5c-96fe-a4fd87fa3223.png">


`1.33.65` | `1.32.91`
----------|---------
<img width="1182" alt="Screen Shot 2021-11-05 at 4 06 03 PM" src="https://user-images.githubusercontent.com/387249/140588001-4bd4e83c-3eae-4e3d-b3e9-10b42bb62ddc.png"> | <img width="1182" alt="Screen Shot 2021-11-05 at 4 06 31 PM" src="https://user-images.githubusercontent.com/387249/140588003-2c2ee471-5be2-4dfe-a18d-c02a8534805a.png">

Confirmed there's no longer the `Your browser is managed by your organization` message at the top of `brave://settings`

Reproduced the issue using 

Brave | 1.32.91 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)
--|--
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Linux
