### ISSUE TITLE
remove the `Later` button from the second adaptive captcha notification/modal

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#19056]
## Description 

We should remove the `Later` button from the second notification/modal. Or at least make it look disabled/unclickable. With the current implementation, a enabled/disabled `Later` button looks exactly the same which might lead to confusion/support issues regarding why the `Later` button isn't clickable.

More information/screenshots can be found via https://github.com/brave/internal/issues/769.

## Steps to Reproduce

   1. https://github.com/brave/internal/issues/769#issuecomment-946388708

## Actual result:

`Later` button on the second notification isn't clickable and appears broken.

## Expected result:

We should either make it appear as disabled or remove it entirely.

## Reproduces how often: 

100% reproducible using the STR/Cases mentioned above.

## Brave version (brave://version info)

```
Brave | 1.33.34 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Windows 11 Version 21H2 (Build 22000.258)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @emerick @jsecretan @rebron @brave/legacy_qa

**Comment by emerick** [comment]
We'll remove the button when snooze is no longer allowed (i.e., after the first snooze).

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Steps:
1. new profile
2. launched Brave against Rewards staging
3. enabled Rewards
4. drove down unblinded tokens
5. issued an aCAPTCHA challenge using `curl` against the staging endpoint
6. confirmed I saw the 1st aCAPTCHA, with `Solve` and `Later` buttons
7. restarted the browser
8. drove down unblinded tokens again
9. issued another aCAPTCHA challenge
10. confirmed 2nd aCAPTCHA dialog only had a `Solve` button

1st aCAPTCHA | 2nd aCAPTCHA
----------------|-------------------
![19056-1](https://user-images.githubusercontent.com/387249/146270646-9595d81b-4d3c-48bb-9e6d-e7297d2e14e6.png) | ![19056-2](https://user-images.githubusercontent.com/387249/146270648-78864a71-3b19-4f1c-ae8a-fa4ab2f13438.png)

**Comment by stephendonner** [comment]
NOTE: clicking on `Solve` in the 2nd aCAPTCHA dialog doesn't trigger the solve-challenge dialog.  Will file and circle back.

**Comment by stephendonner** [comment]
> NOTE: clicking on `Solve` in the 2nd aCAPTCHA dialog doesn't trigger the solve-challenge dialog. Will file and circle back.

Filed https://github.com/brave/brave-browser/issues/20121.

**Comment by stephendonner** [comment]
Verified `PASSED` on macOS using 

Brave | 1.34.66 Chromium: 96.0.4664.110 (Official Build) beta (x86_64)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | macOS Version 11.6.1 (Build 20G224)

Followed the steps above, and confirmed the 2nd dialog no longer has the `Later` button.

Also, confirmed (just as a datapoint) that I got the aCAPTCHA when clicking on `Solve`.

example | example | example
---------|---------|----------
<img width="1680" alt="Screen Shot 2021-12-17 at 11 21 20 AM" src="https://user-images.githubusercontent.com/387249/146597361-6f6e00ef-b1e3-489c-be34-e6f2b6e713d6.png"> | <img width="1680" alt="Screen Shot 2021-12-17 at 11 22 54 AM" src="https://user-images.githubusercontent.com/387249/146597370-1946c314-eb34-4ba7-bbd8-d85442c4f359.png"> | <img width="1463" alt="Screen Shot 2021-12-17 at 11 23 01 AM" src="https://user-images.githubusercontent.com/387249/146597373-4e7e8db6-e2f3-4a5c-af71-6de66036baef.png">
