### ISSUE TITLE
Fix clicking on a `Brave Talk` ad switches to an already opened `Brave Talk` tab loading the new URL

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#19055]
## Description 

This is a bit annoying and could be a problem for users who might heavily use Brave Talk. If you're already on a Brave Talk call and get an ad notification that's promoting the feature, clicking on the ad will switch to your current Brave Talk tab and re-load it with the new targeted URL which in turn boots you from your current session/meeting.

Due to muscle memory, I usually click on the ad notifications without reading them. When the Brave Talk campaign was active, I must have accidently been booted from ~4-5 meetings before I started paying attention to which ad I'm clicking on while in a Brave Talk session.

## Steps to Reproduce

**`Perquisites:`** Some type of ad/link that points to Brave Talk

   1. launch any version of Brave that supports Brave Talk
   2. launch a call/meeting using Brave Talk
   3. click on a link/ad that's promoting Brave Talk
   4. rather than opening it in a new tab, it will switch to your Brave Talk tab and load the new URL

## Actual result:

When clicking on a link/ad that's promoting Brave Talk, rather than opening it in a new tab, it will switch to an already created Brave Talk tab which in turn will kick the user from their current session/call.

## Expected result:

I'm not 100% sure that the right solution is but if we're going to push more campaigns, we should target a new tab and not open in an already created Brave Talk tab which could be a live call/session.

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.33.34 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Windows 11 Version 21H2 (Build 22000.258)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @jsecretan @stephendonner @iambrianfung @mrose17

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Ubuntu 18.04

Verified test plan from the description


Verified Brave Talk url is always opened in new tab, even if URL is exactly the same

![19055](https://github.com/brave/brave-browser/assets/34715963/11c0abac-f5c6-4726-9a84-0c2f62f1c219)
