### ISSUE TITLE
Should handle incorrect decimal values specified for custom networks

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19059]
## Description 

Should handle incorrect decimal values specified for custom networks

## Steps to Reproduce

   1. Enable wallet
   2. Enter custom network via settings
   3. Add BSC to custom network
   4. Add an incorrect decimal value to the testnet
   5. Open panel/widget shows wrong balance value 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/139230903-0c543297-42e6-4201-8b80-329e6c675592.png)

## Expected result:
Some correct way of handling incorrect decimal values for custom networks

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.33.37 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)
-- | --
Revision | `d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @spylogsster

**Comment by HEagle18** [comment]
@srirambv I think is solved now ?

**Comment by Douglashdaniel** [comment]
Closing as `not-actionable` since we pre-fill this information in settings now.
