### ISSUE TITLE
Web Store Update URL Missing, causing source-attribution confusion

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#19069]
## Description 

Extensions installed from the Chrome Web Store are claiming to be _not from the web store_. This includes extensions like Google Translate and more, which clearly are from the Chrome Web Store.

## Steps to Reproduce
1. Install Google Translate
2. Navigate to brave://extensions/
3. Note state of extension

## Actual result:

The extension is not properly identified as having originated from the Web Store.

![image](https://user-images.githubusercontent.com/815158/139267285-a4dc0169-1f40-4987-84b8-6dcf11ab914f.png)

## Reproduces how often: 

Always.

## Brave version (brave://version info)

1.32.84, 1.32.85, 1.33.37

## Version/Channel Information:
- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

https://github.com/brave/brave-core/blob/9929ff6411a14350dd61fd19a37e93726b44e64d/common/extensions/brave_extensions_client.cc#L47 assumes a `kComponentUpdater` switch, never falling back on `extension_urls::GetDefaultWebstoreUpdateUrl()` in its absence.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.58 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. installed [Google Translate](https://play.google.com/store/apps/details?id=com.google.android.apps.translate&hl=en_US&gl=US)
4. opened `brave://extensions`
5. examined the state of the extension

Confirmed I no longer saw the `Not from Web Store.` messaging.


default | `developer` mode
-------|-------------------
<img width="1010" alt="Screen Shot 2021-11-03 at 3 10 43 PM" src="https://user-images.githubusercontent.com/387249/140200613-9901deb8-46b5-46b8-85ae-7d4280b4f92a.png"> | <img width="1010" alt="Screen Shot 2021-11-03 at 3 10 46 PM" src="https://user-images.githubusercontent.com/387249/140200624-e142be0a-36ca-44a1-bd5a-4d177246f01d.png">

**Comment by JimBreton** [comment]
FYI it looks like this bug made it into Release 1.32.106.

**Comment by jonathansampson** [comment]
@JimBreton Apologies; we're working on getting this uplifted and delivered.

**Comment by stephendonner** [comment]
> FYI it looks like this bug made it into Release 1.32.106.

thanks for the heads-up; this should be in the next release of `1.32.x` (as soon as we can cut it, with a few other crucial fixes).

**Comment by kjozwiak** [comment]
Clearing the `QA Pass` labels. We should re-check this once we get an RC.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.32.111 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1348)

```
- Verified the STR from the description

default | developer mode
--------|--------------
![image](https://user-images.githubusercontent.com/38657976/143018111-e217e4ba-5a06-4ee2-93c0-30e9fc2416b0.png) | ![image](https://user-images.githubusercontent.com/38657976/143018165-05617dd3-fa41-4cef-9828-cd68a9c41274.png)
