### ISSUE TITLE
Remove Block all text when there are no entries

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1906]
## Description 

Remove Block all text when there are no entries

## Steps to Reproduce

   1. Build from master
   2. Enable `Scripts Blocked` (text is also a little confusing) @karenkliu relating to the conversation on https://github.com/brave/brave-extension/pull/70#issuecomment-429372629
   3. Click on the expand button to see the items blocked
   4. `Block all` text is shown even though there are no items under allowed list

## Actual result:
![image](https://user-images.githubusercontent.com/17010094/47746918-8bc7da80-dc5d-11e8-8cdc-fe50330f48e3.png)

## Expected result:
Should not have unwanted text which is confusing

## Reproduces how often: 

Easy

## Brave version (brave://version info)

master

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @karenkliu @rebron @bsclifton @brave/legacy_qa

**Comment by karenkliu** [comment]
This issue will be fixed when we fix #1957

**Comment by bbondy** [comment]
Moving this to 0.57.x milestone since that's when it will be fixed as part of #1957

**Comment by LaurenWags** [comment]
Issue not resolved. Logged https://github.com/brave/brave-browser/issues/2371 for follow up. Marking as QA/Blocked.
