### ISSUE TITLE
Make tipping banner response depend on success/error from server: Follow up to 15543

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#19071]
## Description 

**Update Oct 29, 2021:** Upon further testing and investigation, original #15543 was not resolved by changes there. Much deeper changes to the contribution engine will be needed to successfully resolve #15543. I have updated title of this issue to become the new #15543.

@szilardszaloki found this issue while discussing https://github.com/brave/brave-browser/issues/15543

Due to a long existing but, anon or Uphold user wallets will always show "Success" (confetti) after tipping. They do not show the "Failure" state. From @szilardszaloki:

Just found a bug deep down in the contribution code (which has been around since June 2020). `ContributionTip` doesn't pass down the callback to the layer that actually handles the processing of contributions, but instead returns with `LEDGER_OK` when saving the contribution queue in the `contribution_queue` table (no matter if it was successful or not).

## Steps to Reproduce

Case 1 - Anon wallet (pre-req: have Charles Proxy set up to return 500 error for `https://grant.rewards.bravesoftware.com/v1/suggestions`)
   1. Clean profile, staging env
   2. Enable Rewards, claim UGP grant
   3. Go to tip a verified publisher
   4. Watch logs
   5. You will see the 500 error, but you get the success/confetti on tip banner

Case 2 - Uphold wallet (pre-req: have Charles Proxy set up to return 500 error for staging version of `https://api.uphold.com/v0/me/cards/:card-id/transactions`)
   1. Clean profile, staging env
   2. Enable Rewards, connect KYC'd Uphold staging wallet
   3. Go to tip an Uphold verified publisher
   4. Watch logs
   5. You will see the 500 error, but you get the success/confetti on tip banner

All tipping scenarios for all wallet types (including bitFlyer and Gemini) would need to be retested once this is resolved.

## Actual result:

Success on tip banner

## Expected result:
Failure on tip banner

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.32.84 Chromium: 95.0.4638.54 (Official Build) beta (x86_64)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | macOS Version 11.6 (Build 20G165)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @szilardszaloki @Miyayes

**Comment by LaurenWags** [comment]
thanks for the updates to this issue @Miyayes 👍🏻

**Comment by Miyayes** [comment]
Will be able to implement fix following this refactor: https://github.com/brave/brave-browser/issues/20473.

**Comment by szilardszaloki** [comment]
I think there's a good chance @zenparsing's work on refactoring the `contribution_queue` in https://github.com/brave/brave-browser/issues/20473 will make the changes in https://github.com/brave/brave-browser/issues/15543 take effect.

**Comment by Miyayes** [comment]
Possible workaround w/o full contribution engine refactor: Tipping banner won't wait for contribution engine. It'll get a success response from contribution engine ("successfully put into queue"), but then it would listen for general contribution failures. @zenparsing

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 12.5 (Build 21G72)
```
