### ISSUE TITLE
Add UI to switch EVM networks

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19072]
<img width="329" alt="Screen Shot 2021-10-28 at 12 16 48 PM" src="https://user-images.githubusercontent.com/831718/139306238-ff905d28-dfdf-41dc-b2a9-c993c229158d.png">

**Comment by darkdh** [comment]
blocked by https://github.com/brave/brave-browser/issues/18583

**Comment by darkdh** [comment]
QA will be testing on #19160

**Comment by srirambv** [comment]
QA blocked on  #19160

**Comment by srirambv** [comment]
As per discussion with @darkdh and https://github.com/brave/brave-browser/issues/19072#issuecomment-957088822  marking this as QA/No
