### ISSUE TITLE
hackerone #1377864 - CNAME Uncloacking in SOCKS5 protocol

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#19070]
https://hackerone.com/reports/1377864

**Comment by stephendonner** [comment]
### Verified `PASSED` using 


Brave | 1.33.51 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)

### Steps:

1. new profile
2. launched Brave
3. installed the Proxy SwitchyOmega extension
4. In the extension settings page, set the Proxy Servers section to have a single entry, as follows:
5. Scheme	Protocol	Server	Port
6. (default)	SOCKS5	127.0.0.1	8081
7. cleared the "Bypass List" section in the extension settings page
8. ensured the above changes were applied by clicking the "Apply changes" button in the left column
9. started a SOCKS5 proxy server on the device via: `ssh 127.0.0.1 -D 8081` (after opening up `Remote Login` in `Sharing` (macOS Settings).
10. added the following line to the Custom filters section in brave://adblock:  `||dev-pages.brave.software/static/images/test.jpg`
11. visited `https://test-cname.brave.software/cname-uncloaking.html`
12. used the Proxy SwitchyOmega icon in the "puzzle piece" extensions menu to enable `proxy mode` (should be the 3rd option).
13. pressed the `Run test` button
14. confirmed the request was `allowed` (green).
15. in the "puzzle piece" extensions menu, changed to `[System Proxy]` and ran the test again. Confirmed the request was `blocked` (red).
16. in the "puzzle piece" extensions menu, changed to `[Direct]` and run the test again. Confirmed the request was `blocked` (red).

example | example | example | example | example | example
---------|----------|---------|----------|---------|---------
<img width="780" alt="Screen Shot 2021-11-02 at 10 47 03 AM" src="https://user-images.githubusercontent.com/387249/139918788-6ab18557-4181-4a86-ad1a-56f064bcb624.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 10 41 07 AM" src="https://user-images.githubusercontent.com/387249/139919008-b047aeb2-3a3a-4ce0-8b0d-74abb2c7525f.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 10 42 02 AM" src="https://user-images.githubusercontent.com/387249/139919048-8a65d943-e5d4-4187-b640-af968e8b3816.png"> | <img width="956" alt="Screen Shot 2021-11-02 at 10 43 04 AM" src="https://user-images.githubusercontent.com/387249/139919117-99e36846-92a0-450a-a58b-84a04b07af40.png"> | <img width="956" alt="Screen Shot 2021-11-02 at 10 43 18 AM" src="https://user-images.githubusercontent.com/387249/139919125-9f6b9bbd-b209-41c3-8453-673998c63fcb.png"> | <img width="956" alt="Screen Shot 2021-11-02 at 10 43 32 AM" src="https://user-images.githubusercontent.com/387249/139919130-a00e62e6-581f-4b96-8f2d-008ebfa35354.png">

**Comment by stephendonner** [comment]
Update for @brave/legacy_qa: I've tried (unsuccessfully) to get this verified on both Linux and Windows.

Linux: DNS/name resolvers seemingly return cached names, leading to the test always showing `green` (allowed), when in two cases it should be `red` (blocked).

Windows: I've tried both 1) ShadowSocks and 2) freesshd (servers)  No dice so far.

Haven't-yet tried https://github.com/jgaa/shinysocks; YMMV.

**Comment by LaurenWags** [comment]
thanks for the update on this one @stephendonner 👍🏻

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using `1.35.5`


Android progress-status:
1. installed ProxyDroid: https://play.google.com/store/apps/details?id=org.proxydroid&hl=en_US&gl=US
2. started ProxyDroid with a SOCKS5 proxy running on port 8081
3. enabled ProxyDroid
4. installed and launched Brave
5. added `||dev-pages.brave.software/static/images/test.jpg` to `brave://adblock`
6. enabled CNAME uncloaking via `brave://flags`
7. restarted Brave
8. loaded `https://test-cname.brave.software/cname-uncloaking.html` and clicked on the `Run test` button
9. confirmed I saw a green-background `Request was allowed` message beneath the above button

...and that's as far as I've gotten.  Not sure what else can be tested here, from desktop's test plan.

@antonok-edm mind conferring with @samartnik @SergeyZhukovsky et al on the test plan, here?  🙏 

example | example | example | example
---------|---------|----------|---------
![Screenshot_20211203-085531](https://user-images.githubusercontent.com/387249/144658880-dacf0b97-334d-4025-82c2-562b2088a80d.png) | ![Screenshot_20211203-090234](https://user-images.githubusercontent.com/387249/144658899-ecfde5be-60d9-4059-992d-300c458dc30f.png) | ![Screenshot_20211203-110533](https://user-images.githubusercontent.com/387249/144658928-ccc58cb0-35a5-4b97-8362-9bc4e3740083.png) | ![Screenshot_20211203-090614](https://user-images.githubusercontent.com/387249/144659022-9341b4b7-2891-44bb-9747-6abb4700acd8.png)

**Comment by stephendonner** [comment]
Current status with Windows 10 attempt to verify; tested with 

Brave | 1.33.103 Chromium: 96.0.4664.93 (Official Build) (64-bit)
-- | --
Revision | 17531e0a70b4f8108f2418e8b5117f465077710b-refs/branch-heads/4664@{#1229}
OS | Windows 10 Version 20H2 (Build 19042.1348)

After all of the above setup (which worked on macOS and Linux), I'm still stuck here: when using `[proxy]` via `SwitchyOmega`, I'm unable to connect to the test site (or any sites).  `[System Proxy]` and `[Direct]` work, but should be showing `Request was blocked`.

I've confirmed that I've got `Shadowsocks` listening on port `8081` (via `netstat -a | grep 8081`) but looks like it's not forwarding the traffic.

Any ideas @antonok-edm ?

`Brave`

example | example | example | example | example | example 
----------|-----------|-----------|----------|----------|-----------
![19070-omega-proxy-set](https://user-images.githubusercontent.com/387249/145496031-74d97f4d-7d58-4485-874b-d4155e974f71.png) | ![19070-omega-system-proxy-set](https://user-images.githubusercontent.com/387249/145496115-980eee03-8e4e-419f-b543-02366cdcc299.png) | ![19070-omega-proxy-direct](https://user-images.githubusercontent.com/387249/145496111-11f97418-45f4-48ba-9b2e-7dbfae88b307.png) | ![19070-adblock](https://user-images.githubusercontent.com/387249/145496211-ef949089-160b-402e-9057-483170a85776.png) | ![19070-enabled-flags](https://user-images.githubusercontent.com/387249/145496212-a5f4ea68-451f-4b84-8488-a966bb6ebccb.png) | ![19070-systemsettings](https://user-images.githubusercontent.com/387249/145496213-cf105b32-5d1d-436e-970e-8943b2ab7e65.png)

`SwitchyOmega` | `Windows 10` | `Shadowsocks listener`

example | example | example
----------|-----------|----------
![19070-proxyswitchyomega](https://user-images.githubusercontent.com/387249/145496712-21197549-34c3-4bf2-800c-cea3ea4b15ec.png) | ![19070-windows-showing-proxy](https://user-images.githubusercontent.com/387249/145496508-49687172-5353-44fa-a68e-98525487412e.png) | ![19070-netstat-port-8081](https://user-images.githubusercontent.com/387249/145496661-c4ce3ef9-ff8d-425a-836a-6a64e597a9ff.png)



cc @brave/legacy_qa

**Comment by stephendonner** [comment]
@diracdeltas can you confirm you get similar results?

`[direct-proxy]` | `[proxy]` | `[system-proxy]`
-----------------|-----------|-----------------
![direct-results](https://user-images.githubusercontent.com/387249/145666177-2fb4ec6d-56d4-4389-8be8-9159f2972517.png) | ![proxy-results](https://user-images.githubusercontent.com/387249/145666187-3dc0ebc0-985b-4358-9bc5-16916a9be799.png) | ![system-proxy](https://user-images.githubusercontent.com/387249/145666194-385284ca-617d-4f91-b80b-13f2a6569f57.png)


The above is with the following config:

SwitchyOmega settings | SOCKS5 config
--------------------------|-------
![switchyomega-settings](https://user-images.githubusercontent.com/387249/145666214-098eaf09-43ce-4358-9d4a-8d2f2020614e.png) | ![socks5server](https://user-images.githubusercontent.com/387249/145666298-4e1e2de2-9b62-4851-876c-4432b0048d59.png)

**Comment by diracdeltas** [comment]
@stephendonner yep i got those results on my windows 10 VM

**Comment by stephendonner** [comment]
@diracdeltas thanks for confirming 👍

**Comment by antonok-edm** [comment]
Results above look good to me. We definitely don't want leakage outside of the proxy, which the CNAME resolver does not use for whatever reason. There are no "request blocked" results while the proxy is installed and active so this should be all set.
