### ISSUE TITLE
Network list is not updated in existing wallet page after adding new custom chains

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19086]
## Description 
Add a new network via settings, network list in existing wallet page is not updated.

## Steps to Reproduce

   1. Open a tab and visit brave://wallet, unlock the wallet
   2. Open another tab and add a new custom chain in brave://settings/wallet/networks
   3. Go back to brave://wallet tab and click the network dropdown list
<img width="290" alt="Screen Shot 2021-10-28 at 4 13 26 PM" src="https://user-images.githubusercontent.com/4730197/139348845-c08444a4-c8af-46b5-94a0-e55a9d0f7fe0.png">

## Actual result:

<img width="281" alt="Screen Shot 2021-10-28 at 4 13 03 PM" src="https://user-images.githubusercontent.com/4730197/139348876-61cef742-e587-44bf-990e-5c239c49b070.png">

## Expected result:
<img width="297" alt="Screen Shot 2021-10-28 at 4 13 13 PM" src="https://user-images.githubusercontent.com/4730197/139348872-9fbaab6f-118c-442d-b6a6-dad0a0edc27b.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.33.90 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/10893>brave/brave-core#10893</a></li>
         <li>Verified newly added network is automatically shown on the network dropdown list on both page and panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143434886-2ef895d0-ee2c-4bd1-be33-878e25153645.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143433979-6d82ed51-e1fd-47c5-a740-0a2c79b23a0f.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143433477-0ae43350-79a9-4568-9429-cb93668c1fbd.mov>
      </td>
   </tr>
</table>
