### ISSUE TITLE
unable to view DirecTVNow videos

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1908]
### Description
Can't view DirecTVNow videos. Also looks possibly related to https://github.com/brave/browser-laptop/issues/8581, can't view videos at HBOGO.

### Steps to Reproduce

  1. Go to https://directvnow.com
  2. Login. 
  3. Landing page: https://www.directvnow.com/watchnow and notice error.

### What version of Brave are you using?
- Version 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)

### Screenshot
<img width="1629" alt="screen shot 2018-10-30 at 2 01 23 pm" src="https://user-images.githubusercontent.com/5951041/47754238-794aa280-dc57-11e8-9675-96a2fb30b969.png">

**Comment by tomlowenthal** [comment]
Does the same thing happen with Shields down?

**Comment by rebron** [comment]
Possible widevine issue. Not getting widevine prompt though. Will install widevine on netflix and try again.

**Comment by byroniac** [comment]
Possibly related: I get error code M7701-1003 missing Widevine component error on Netflix using Ubuntu 18.10 x64 Linux Brave 0.60.45? On Windows 10, I got a prompt to install the Widevine component. Nothing on Linux appeared.

**Comment by bbondy** [comment]
@rebron we since improved widevine detection so it's always caught.  Could you check if you get the install widevine option in the url bar and close this if you do?

**Comment by rebron** [comment]
DirecTVNow videos are working for me now, looks like it was a widevine issue.
