### ISSUE TITLE
Integrate first party ephemeral storage with domain block functionality

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#19099]
Add logic to automatically enable first party ephemeral storage (1PES) for a domain when a user proceeds the blocked top level domain interstitial.

Related:
https://github.com/brave/brave-browser/issues/14134
https://github.com/brave/brave-browser/issues/15906

**Comment by stephendonner** [comment]
Hi @goodov; mind providing us with a test plan for this one?  Thanks!

**Comment by goodov** [comment]
> Hi @goodov; mind providing us with a test plan for this one? Thanks!

Sure! Some context first: currently if a user visits a first-party-blocked website, we show an interstitial in Aggressive blocking mode, however in Standard blocking the website is loaded as usual. The change we're adding here will enable [1PES](https://github.com/brave/brave-browser/issues/15906) for such websites in Standard blocking mode if no data (`cookies`, `localStorage`) was stored for a website previously.

### Test cases

Prerequisites:
1. Enable features on `brave://flags`: `First Party Ephemeral Storage`,  `Domain blocking using First Party Ephemeral Storage`.

#### Case 1
1. Open any website (that was not previously opened in a browser profile) from [this list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext)
2. Expect the website is added in `Sites that clear cookies when you close them` section at `brave://settings/cookies`:
![image](https://user-images.githubusercontent.com/5928869/147558404-573253c3-17e2-4cc5-8ed4-58b2acba010e.png)
3. Expect no cookies or localStorage data is stored for a website.

#### Case 2
1. Enable Aggressive blocking mode
2. Open any website (that was not previously opened in a browser profile) from the list
3. Expect a blocking interstitial is visible:
![image](https://user-images.githubusercontent.com/5928869/147560200-d65c3733-e495-4457-af8e-9a9f0b5ef894.png)
4. Expect the website is added in `Sites that clear cookies when you close them` section at `brave://settings/cookies` when `Proceed` is pressed without `Don't warn me about this site again` checkbox.
5. Expect no cookies or localStorage data is stored for a website.

##### Case 3
1. Enable Aggressive blocking mode
2. Open any website (that was not previously opened in a browser profile) from the list
3. Expect a blocking interstitial is visible
4. Expect the website is **not** added in `Sites that clear cookies when you close them` section at `brave://settings/cookies` when `Proceed` is pressed **with** `Don't warn me about this site again` checkbox.
5. Expect cookies or localStorage data is stored for a website (if a website does this).

Also a redirect test case can be performed. For example, perform a redirect from any website to a website mentioned in the list, expect it's added automatically in `Sites that clear cookies when you close them` section.

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using

Brave | 1.35.79 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 20H2 (Build 19042.1415)

### Prerequisite

![19099-1](https://user-images.githubusercontent.com/387249/149039398-aee48865-5844-41e1-b4b9-5605da3da82c.png)

### Case 1

example | example | example | example
----------|----------|-----------|----------
![19099-2](https://user-images.githubusercontent.com/387249/149039399-59bf1b2f-f4c4-4e0c-8ccd-7283158a9132.png) | ![19099-3](https://user-images.githubusercontent.com/387249/149039401-2aafb2c8-78a3-42d1-a21a-cd6397bc4ce3.png) | ![absurd-water-no-cookies](https://user-images.githubusercontent.com/387249/149040456-5b995242-1f2c-4293-b0bf-a756606410bc.png) | ![absurd-water](https://user-images.githubusercontent.com/387249/149040262-a697bc31-d787-4a44-9807-ee194d00b3f5.png)



### Case 2

example | example | example | example
----------|-----------|----------|----------
![19099-4](https://user-images.githubusercontent.com/387249/149039402-614db471-4ae0-4968-a92c-d7cea1e9adb2.png) | ![19099-5](https://user-images.githubusercontent.com/387249/149039728-8cef5bfb-2c95-46cc-92de-686d098adf1a.png) | ![19099-6](https://user-images.githubusercontent.com/387249/149039732-63715a22-58d8-4e28-b55f-5d1ff6f65ed1.png) | ![19099-7](https://user-images.githubusercontent.com/387249/149039859-dcdc59ec-66f1-4f2c-bf3a-c7c9bbce9184.png)


### Case 3

example | example | example | example | example | example
----------|-----------|----------|-----------|-----------|----------
![aniview-1](https://user-images.githubusercontent.com/387249/149042234-366b3724-e2ff-4c5a-a5bb-851604f5dce8.png) | ![aniview-2](https://user-images.githubusercontent.com/387249/149042235-739e392d-b455-44d9-b891-c8d1216e5cdc.png) | ![aniview-3](https://user-images.githubusercontent.com/387249/149042236-0a5d7c45-a7b4-4d35-8abe-a623d6925ecf.png) | ![aniview-4](https://user-images.githubusercontent.com/387249/149042237-2d08b0f7-d6e6-44ae-8d0b-efed91e84ffd.png) | ![19099-2](https://user-images.githubusercontent.com/387249/149043218-236a2fae-c2da-416e-b6a3-708388a92b99.png) | ![19099-4](https://user-images.githubusercontent.com/387249/149043220-0773697b-7a79-4d04-bcee-ea10d68e3a8a.png)
