### ISSUE TITLE
alexa.com is not rendered correctly

### ISSUE THREAD

**Issue by bitcoinuser** [brave/brave-browser#1909]
## Description 
alexa.com is not rendered correctly

## Steps to Reproduce

   1. Go to https://www.alexa.com/
   2. 
   3. 

## Actual result:

![captura de tela de 2018-10-30 22-46-45](https://user-images.githubusercontent.com/1178856/47761032-b6ce2080-dc95-11e8-96e3-7c1a7729371f.png)

## Expected result:

See site rendered correctly

## Reproduces how often: 

Always with Brave Shields enabled. Works ok with Brave Shields disabled.

## Brave version (brave://version info)

Versão 0.55.22 Chromium: 70.0.3538.77 (Versão oficial) 64 bits

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

I don't know.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Need to add sitehack for this. Block almost everything from the site 
![image](https://user-images.githubusercontent.com/17010094/47761733-f42faf80-dc8f-11e8-876e-1282092eb020.png)

**Comment by ryanbr** [comment]
@bitcoinuser If you're still testing, this should be resolved :) If you can confirm?

**Comment by ryanbr** [comment]
Also implemented a site-trackers fix: https://github.com/easylist/easylist/commit/afcf234038bd30a5d26e727d3556b5ff47af7eb4

**Comment by antonok-edm** [comment]
This looks resolved to me; @bitcoinuser feel free to re-open if you still see the issue.
