### ISSUE TITLE
CR 96 - `Safety check` setting isn't shown in the sidebar menu in a clean profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19095]
## Description 

CR 96 - `Safety check` setting isn't shown in sidebar menu in a clean profile

## Steps to Reproduce

   1. Install the build from https://brave-jenkins-build-artifacts.s3.amazonaws.com/brave-browser-build-pr/cr96/a256de80702a43175279986a1a68be3393e10fd9-385c2a26dc547bc4153669fa4ac978b2280da47a/windows/BraveBrowserStandaloneNightlySetup_96_1_33_39.exe   

## Actual result:

CR 96 - `Safety check` setting isn't shown in the sidebar menu in a clean profile

![image](https://user-images.githubusercontent.com/38657976/139420424-9ed00dc3-6f74-41cd-81c8-d3f4af7dc944.png)

## Expected result:
`Safety check` setting should be shown in the sidebar menu

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.33.39 Chromium: 96.0.4664.27 (Official Build) nightly (64-bit)
-- | --
Revision | 0658dae02ef18b530eda4384920ee23f5e156c55-refs/branch-heads/4664@{#459}
OS | Windows 10 Version 21H1 (Build 19043.1288)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by stephendonner** [comment]
Shouldn't this be `QA/No`, as there's nothing fixed to verify?

**Comment by kjozwiak** [comment]
> Shouldn't this be `QA/No`, as there's nothing fixed to verify?

Yup, there's nothing that QA can do here. Technically we can probably remove this from the milestone and label it as `closed/invalid` but probably a good idea to keep it in the milestone in case anyone comes across the above.
