### ISSUE TITLE
Disable Wallet button on Tor/Private windows

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19096]
## Description 

Following up on #18455, we should disable the wallet buttons on private and Tor windows similar to rewards button. we can revert this change once `window.ethereum` is enabled on Tor/Private windows

cc: @jamesmudgett @bbondy

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.32.94 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 10 Version 20H2 (Build 19042.1288)

Confirmed there are no wallet icons on `Guest`, `Private`, and `Private with Tor` windows.

`Guest` | `Private` | `Private with Tor`
--------|-----------|------------------
![guest](https://user-images.githubusercontent.com/387249/140835143-81870002-d0bc-4180-a4f4-d3256d447971.png) | ![private](https://user-images.githubusercontent.com/387249/140835156-be3ce943-3e3b-4000-94d1-290ff5464129.png) | ![private-tor](https://user-images.githubusercontent.com/387249/140835175-e2110382-66fc-4766-bbb0-afb4dacb7921.png)
