### ISSUE TITLE
Unable to connect to Ledger Nano on Linux

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19092]
## Description 

Unable to connect to Ledger Nano on Linux

## Steps to Reproduce

   1. Clean beta profile
   2. Connect Ledger Nano S and open the Ethereum App
   3. Add accounts and select Hardware and select Ledger Nano S
   4. Console logs errors and doesn't list accounts to unlock

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/139379477-f07bd590-0d8f-461f-a3a9-4ea0404f64e6.png)

## Expected result:
Unlock and connect h/w wallet

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.84 Chromium: 95.0.4638.54 (Official Build) beta (64-bit)
-- | --
Revision | `d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster @bbondy

**Comment by spylogsster** [comment]
@srirambv seems this is related to how the ledger detected in the linux devices. Got this error too but it was solved by re-connecting the device. Maybe usefull to connect it to the LedgerLive app first, they have a wizard with terminal commands that may help users to solve some popular issues. If the device is detected in the ledger live app it works in the browser too.

**Comment by srirambv** [comment]
Verified able to connect to Ledger once the Ledger Live app was installed and ran the `add udev` command line. Thanks for the tip @spylogsster 
![Ledger](https://user-images.githubusercontent.com/17010094/139655089-37b01f44-d907-4d4c-b3da-71e59f787311.png)


Closing the issue as invalid.
