### ISSUE TITLE
Please do NOT use default DNS after connected to a proxy server.

### ISSUE THREAD

**Issue by bqt5** [brave/brave-browser#19097]
## Description 

After the browser is connected to a proxy server, it still tries to use the default DNS config of Windows, rather than use the DNS  configed by the proxy server.

This may lead to DNS LEAK!

## Steps to Reproduce

   1. Connect to a proxy server
   2. Set different DNS between the computer and the proxy server
   3. Open https://browserleaks.com/ip You can find that the browser still ueses the local DNS config. 

## Actual result:

Open https://browserleaks.com/ip You can find that the browser still ueses the local DNS config. 

## Expected result:
When connect to a proxy server, use the DNS config in the proxy server instead (as other browsers do).

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave 1.31.87 Chromium: 95.0.4638.54

## Version/Channel Information:

- Can you reproduce this issue with the current release?   **YES**
- Can you reproduce this issue with the beta channel?  **YES**
- Can you reproduce this issue with the nightly channel?  **YES**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **NO**
- Does the issue resolve itself when disabling Brave Rewards? **NO**
- Is the issue reproducible on the latest version of Chrome? **NO (Even Edge, Firefox)**

## Miscellaneous Information:

The latest version of Chrome, Edge and Firefox do not have the same problem.

It seems to appear in Brave Browser only.

Hope you can fix it ASAP, as it does really harm to anonymity!

**Comment by diracdeltas** [comment]
what proxy are you using? this may have been fixed by https://github.com/brave/brave-browser/issues/19070

**Comment by bqt5** [comment]
> what proxy are you using? this may have been fixed by #19070

I am using HTTP Proxy with no addons. I have tested for many times, it seems that the problem has not been fixed.

**Comment by diracdeltas** [comment]
are you using a proxy just for the browser or all traffic for the operating system? how was this configured? does the same issue occur in Chrome?

**Comment by diracdeltas** [comment]
closing as dupe of https://github.com/brave/brave-browser/issues/15038
