### ISSUE TITLE
Use policy pref for restore on startup instead of patch

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#191]
https://www.chromium.org/administrators/policy-list-3#RestoreOnStartup

**Comment by bbondy** [comment]
QA notes:
- Just make sure windows and tabs restore on restart.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
