### ISSUE TITLE
Pull missing Android l10n from Transifex.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#19100]
This is a follow up to #17991. Not all translations have been pulled in brave/brave-core#10704.

QA: Please, reverify the same strings as described in #17991

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using the following build:

```
1.31.90 Chromium: 95.0.4638.69
```

Verification notes can be found via https://github.com/brave/brave-browser/issues/17991#issuecomment-957090564.

----------------------------

Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 11` using the following build:

```
1.31.90 Chromium: 95.0.4638.69
```

Verification notes can be found via https://github.com/brave/brave-browser/issues/17991#issuecomment-957090564.
