### ISSUE TITLE
Crashes on Pixel 6 Pro on launch

### ISSUE THREAD

**Issue by jwefers** [brave/brave-browser#19109]
## Description 
Crash on Startup

## Steps to reproduce 

   1. Open Brave on Pixel 6 Pro
   2. 
   3. 

## Actual result 
![Screenshot_20211029-194043](https://user-images.githubusercontent.com/851823/139479195-61c465a1-f123-41b0-822c-12fb9183a8e4.png)

## Issue reproduces how often 
Every time

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version?  No
- Can you reproduce this issue with the current Play Store Nightly version? Not tested

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Google Pixel 6 Pro
   - Android version: 12.0
   
## Brave version
1.30.89

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by Hhlnlt111** [comment]
Crashes on Pixel 3a on launch every time. Unable to use Brave at all.

**Comment by jwefers** [comment]
funny, on my Pixel 3a it worked fine

**Comment by jwefers** [comment]
fixed in 1.31.87
