### ISSUE TITLE
Polish how the widget/portfolio page behave when you try to swap

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19102]
## Description 

When trying to swap, portfolio page reloads causing the Swap button to change to `Insufficient Funds` momentarily but its quite prominent. We should make this more smooth so the button doesn't switch to `Insufficient Funds`

## Steps to Reproduce

   1. Select Swap of tokens
   2. Click Swap to trigger panel to open
   3. Briefly swap button changes to Insufficient Funds

## Actual result:

https://user-images.githubusercontent.com/17010094/139467282-039bde93-aa10-4e50-aa28-8c0d042c84ec.mov

## Expected result:
Better handling of UI

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.84 Chromium: 95.0.4638.54 (Official Build) beta (x86_64)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @Douglashdaniel 
Follow up to #18905

**Comment by Douglashdaniel** [comment]
@srirambv Just tested this, seems like this is not occurring any more.
Might have been resolved by some other fix.
Are you able to confirm?

**Comment by srirambv** [comment]
@Douglashdaniel yes the issue seems to be fixed now. I don't see the `Insufficient funds` message on the swap button when trying to swap. Closing as the issue is not reproducible anymore
