### ISSUE TITLE
Android changelog not updated

### ISSUE THREAD

**Issue by mraonea** [brave/brave-browser#19116]
Android changelog not getting updated

**Comment by kjozwiak** [comment]
@mraonea it's been updated a few days ago 👍 There was a bit of a delay regarding getting both `1.31.87` & `1.31.88` reviewed on the GPS, hence the CHANGELOG wasn't updated till those versions were live via the GPS. You can find the updated `Android` CHANGELOG via:

* https://raw.githubusercontent.com/brave/brave-browser/master/CHANGELOG_ANDROID.md
