### ISSUE TITLE
Rewards panel showing former Uphold balance, even after Gemini is connected

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19119]
## Description

Steps to reproduce:

1. Connect Rewards wallet to Uphold
2. Observe balance
3. Disconnect (edit: maybe specifically by using the Rewards dropdown panel?), then connect to Gemini
4. Balance remains your Uphold balance
5. Persists even if I close the panel and open it again, or exit/refresh the brave://rewards tab and open it again
6. Even persists after a browser restart 

**My actual Gemini balance is properly detected according to rewards-internals > logs:**

```
[ REQUEST ]
> URL: https://api.gemini.com/v1/balances
> Method: POST
[Oct 30, 2021, 1:38:57.0 PM:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://api.gemini.com/v1/balances
> Result: Success
> HTTP Code: 200
> Body: [{"type":"exchange","currency":"BAT","amount":"51.045051265783409444","available":"51.045051265783409444","availableForWithdrawal":"51.045051265783409444"}]
```

But for some reason, this is not being reflected in the panel. 

Brave | 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.5.2 (Build 20G95)

![image](https://user-images.githubusercontent.com/11497541/139543464-5555845a-7a04-487d-92a4-83da0587c0cb.png)

![image](https://user-images.githubusercontent.com/11497541/139543492-a144f068-9ff0-4f66-8594-def207ecd0d0.png)

**Comment by LaurenWags** [comment]
Reproduced - see https://github.com/brave/internal/issues/823

**Comment by Miyayes** [comment]
@zenparsing Should no longer be an issue right? In any case, it is solved for free/this path is no longer relevant as of 1.48.x.
