### ISSUE TITLE
Detect user's interaction with a wallet

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#19112]
We should detect user's interaction with a wallet to reset autolock timer. There is a method `NotifyUserInteraction()` in `KeyringController` to notify about any interaction.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 
- Verified wallet auto-locks after the specified time has passed
- Verified setting wallet to auto-lock after 1 min and using it for more than a min doesn't auto lock
- Verified setting wallet to auto-lock after 1 min and keeping wallet active auto-locks the wallet after 1 min
- Encountered #19970
--------------
Verification passed on Samsung Tab A  with Android 10
- Verified wallet auto-locks after the specified time has passed
- Verified setting wallet to auto-lock after 1 min and using it for more than a min doesn't auto lock
- Verified setting wallet to auto-lock after 1 min and keeping wallet active auto-locks the wallet after 1 min
- Encountered #19970
