### ISSUE TITLE
Unmaximized window shrinks on every launch, window size not preserved on Linux (Chrome issue #1261874)

### ISSUE THREAD

**Issue by supernes** [brave/brave-browser#19122]
## Description 
Unmaximized window size shrinks on every launch. Previous window size is not saved.

## Steps to Reproduce
   1. Launch Brave
   2. (Optional) Resize unmaximized window
   3. Quit Brave, relaunch
   4. Observe that window size is not preserved, window size is smaller than last time
   5. Repeat 1-3 and observe window size gets smaller every time until only the address bar is visible

## Actual result:
Window size gets smaller after every launch

## Expected result:
Window size is preserved

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Started with 1.31.87, present in 1.31.88
Works as expected in 1.30.89

## Version/Channel Information:
Current release

- Can you reproduce this issue with the current release? Yes. 
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No. 
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Fedora 34 (x86_64)
GNOME 40.5
Wayland

**Comment by DashCruft** [comment]
I can confirm this ^

Happening in Arch Linux with KDE Plasma as Desktop Environment (Not DE based for sure)

Here is a video showing it as well
https://user-images.githubusercontent.com/59381835/139571106-d088e1fb-62d8-4aea-ac35-54a1ef1d9107.mp4

**Comment by supernes** [comment]
This bug is not present when trying the 1.32.92 dev release **with a fresh profile**. When migrating the original 1.30.98 config the window starts shrinking again, as in the 1.31.x releases.
I'll do some more tests to try and find what flag or setting might be causing this.

**Comment by DashCruft** [comment]
Possibly a chromium bug?

**Comment by supernes** [comment]
Looks like it, the Chromium bug tracker has [this entry from a few days ago](https://bugs.chromium.org/p/chromium/issues/detail?id=1261874). People are also reporting issues with maximized windows overflowing, which is tracked in a couple of issues over there and is being reported in the Brave repo as well.
I think I'll stay on 1.30.x and hope it gets fixed in Chromium 96 or whenever.

**Comment by DashCruft** [comment]
Knew it.

The bug is present on chromium for me but on brave, the bug is more visible and eye catchy.

Hopefully chromium will fix the issue cuz its super annoying to deal with it lol

**Comment by supernes** [comment]
Issue is resolved as of Brave 1.32.106 (Chromium 96.0.4664.45)
