### ISSUE TITLE
Save To Pocket extension stopped working

### ISSUE THREAD

**Issue by jeffgoh** [brave/brave-browser#19121]
## Description 

"Save to Pocket" extension stopped working in brave

## Steps to Reproduce

   1. right-click greyed-out "Save to pocket" extension
   2. select login instead of sign-up, using credentials tested as working on getpocket.com
   3. wheel spins infinitely

## Actual result:

![image](https://user-images.githubusercontent.com/18367815/139565014-9394fbfa-2767-42f5-9eb6-5fcc035ab1fe.png)

## Expected result:
To be logged into pocket extension and be able to save the page to pocket.

## Reproduces how often: 

100% of the time

## Brave version (brave://version info)

Brave | 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? not yet, will try
- Can you reproduce this issue with the beta channel? not yet, will try
- Can you reproduce this issue with the nightly channel? not yet, will try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by jeffgoh** [comment]
Updating to current release (Version 1.31.88) works - I forgot I had frozen my Brave version because I kept losing my wallet.

**Comment by pras92** [comment]
Faced the same issue with v 1.22.71 and though I can't update to Brave latest for other reasons, I'm glad that it's fixed with latest versions. 

Not my intention to re-open an obsolete issue but, I wonder what made the extension to stop working in the first place, when both Brave and Pocket were being prevented from auto-updates.
