### ISSUE TITLE
Update default NTP wallpaper on Android

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19128]
This is sub-task of https://github.com/brave/brave-browser/issues/18568 for replacing default bg image on Android.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `nightly`, version `1.33.69, Chromium 96.0.4664.35` on a Google Pixel XL, running Android 9.

Steps:
1. new install
2. disabled Wi-Fi
3. opened a new-tab page after installation
4. opened a couple more new-tab pages
5. confirmed -- when offline -- I always got Dylan Malval's image
6. reconnected to Wi-Fi
7. restarted Brave
8. confirmed new-tab pages cycled through the rest of the wallpaper images

example | example | example | example
---------|---------|---------|----------
![Screenshot_20211108-125636](https://user-images.githubusercontent.com/387249/140817977-4d6878e7-817c-4398-9c55-867067378e6f.png) | ![Screenshot_20211108-130032](https://user-images.githubusercontent.com/387249/140817987-6d795d43-06a4-4535-8afd-8c53e2eb418d.png) | ![Screenshot_20211108-130152](https://user-images.githubusercontent.com/387249/140817989-fd1c3e32-bdb5-486d-9805-98992441098c.png) | ![Screenshot_20211108-130413](https://user-images.githubusercontent.com/387249/140817998-d144b033-b085-4e1b-a171-d31aa628b9d3.png)
