### ISSUE TITLE
Uninstall of Muon Brave on Windows should leave behind the stub executable

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1912]
When a user uninstalls the Muon based Brave on their machine (Windows only), we currently remove the application folders and only leave the `Update.exe` behind. This can potentially break folks that haven't updated their default browser to be Brave Core (if they uninstalled Muon Brave after upgrade took place)

Squirrel needs to be updated to leave the `Brave.exe` behind during uninstall. If shortcuts or handlers still point at it, the stub executable already has logic to detect Brave Core and launch into it

**Comment by bsclifton** [comment]
Looking at the code here, I'm not seeing a "low hanging fruit" way to make this happen

@bbondy is this a blocker for the migration?

**Comment by bbondy** [comment]
I would say yes because it will be very common for people to uninstall muon and then they will have a default browser status.

**Comment by bsclifton** [comment]
OK digging into this 👍

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/Squirrel.Windows/pull/7
