### ISSUE TITLE
Update NTP Background Images component for Fall 2021 wallpapers

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19129]
This is sub-task of https://github.com/brave/brave-browser/issues/18568 for updating `NTP Background images` component

**Comment by simonhong** [comment]
It's done by https://ci.brave.com/view/all-extensions/job/brave-core-ext-ntp-background-images-component/8/console

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.51 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. loaded `brave://components`
4. confirmed `Version: 1.0.4` of `NTP Background Images`
<img width="973" alt="Screen Shot 2021-11-02 at 9 09 45 AM" src="https://user-images.githubusercontent.com/387249/139907975-e631aa7d-8ca6-48b9-9e29-b48a4e194bbb.png">

5. cycled through each new-tab page, noting the background images
6. confirmed they were (15) new images which match those in https://github.com/brave/brave-browser/issues/18568

|   |   |   |   |   |
|---|---|---|---|---|
<img width="1312" alt="Screen Shot 2021-11-02 at 9 29 31 AM" src="https://user-images.githubusercontent.com/387249/139906406-3de7bc4b-e0d8-48b1-8027-c6a5efa89d18.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 29 35 AM" src="https://user-images.githubusercontent.com/387249/139906489-564ece63-0d7b-4d28-8bb8-e5765433c78e.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 29 37 AM" src="https://user-images.githubusercontent.com/387249/139906573-8f1afc65-04c2-4029-9957-d617a17b7c68.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 29 39 AM" src="https://user-images.githubusercontent.com/387249/139906593-14e1cdc9-07e3-422c-97be-3cfb8f0d076b.png"> |  <img width="1312" alt="Screen Shot 2021-11-02 at 9 29 43 AM" src="https://user-images.githubusercontent.com/387249/139906629-f8aacc95-4948-423a-bc77-5f04910b6a40.png">
| <img width="1312" alt="Screen Shot 2021-11-02 at 9 29 45 AM" src="https://user-images.githubusercontent.com/387249/139906852-f6a1c3e7-e1df-49da-af7f-14466aaa6a2a.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 29 47 AM" src="https://user-images.githubusercontent.com/387249/139906923-c118745c-b56a-4811-9e17-c3e4f3836d25.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 29 52 AM" src="https://user-images.githubusercontent.com/387249/139906994-ea032807-131e-43f6-a83b-7b0dc06ff9d1.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 29 56 AM" src="https://user-images.githubusercontent.com/387249/139907070-7dcee653-6141-4b60-b4ed-4952b7363432.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 29 58 AM" src="https://user-images.githubusercontent.com/387249/139907113-eac60c24-51b0-4549-8551-5ef417e421b7.png"> |
| <img width="1312" alt="Screen Shot 2021-11-02 at 9 30 03 AM" src="https://user-images.githubusercontent.com/387249/139907323-410280c5-0f8c-40b2-a802-4dce9e21c000.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 30 05 AM" src="https://user-images.githubusercontent.com/387249/139907329-2073d5ff-63b7-4961-bf74-e3d3028f5fe4.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 30 08 AM" src="https://user-images.githubusercontent.com/387249/139907331-07c8be87-5cad-4159-8cc8-18a166369199.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 30 13 AM" src="https://user-images.githubusercontent.com/387249/139907334-035d4d5b-39f8-4204-81c1-af0155561caa.png"> | <img width="1312" alt="Screen Shot 2021-11-02 at 9 30 16 AM" src="https://user-images.githubusercontent.com/387249/139907337-fdb139b0-74c1-4a88-a46c-ab36529a6527.png">
