### ISSUE TITLE
100% CPU Usage - Brave Beta PRIVATE WINDOW ONLY

### ISSUE THREAD

**Issue by jhefgithub** [brave/brave-browser#19120]
I have seen this issue addressed in older posts, and I tried some of the solutions suggested there (see below).
Note: It IS NOT an issue with a generic Brave Beta 'New Window', only with a 'New PRIVATE Window.'

Notes:
1. I have Uninstalled/Reinstalled Brave Beta after a fresh download from Brave.com.
2. I have checked the '%USERS%/.../Ledger-State' file for entries under 'Ballots' but found no such entry.
3. Brave Rewards are not available in a Private Window, and cannot be disabled.
4. I have tried disabling Hardware Acceleration, but it made no difference.
5. I have no extensions installed or enabled.
6. Redirect Onion Sites, WebTorrent, and Widevine are all OFF.
7. Generic profile, no sign-in.
8. 'Continue running background apps when Brave is closed' is OFF.

## Description 
After opening a Brave Beta Private Window, CPU resources go to 100% - no URL entry required.
This does not occur with a generic Brave Beta window, only with a Private Window.

Brave Beta v1.32.84
Windows 10 Home - 64-bit
Intel Core i5-2450 CPU
8.0 GB RAM

## Steps to Reproduce
1. Open Brave Beta window
2. Open new Brave Beta Private Window - no URL entry required.

## Expected result:
CPU resources go to 100% (per Process Explorer and Brave Task Manager)

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Brave | 1.32.84 Chromium: 95.0.4638.54 (Official Build) beta (64-bit)
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Windows 10 Version 21H1 (Build 19043.1288)

## Version/Channel Information:
Beta Channel Only - Private Window Only

## Other Additional Information:
Cannot disable Rewards in a Private Window

## Miscellaneous Information:
None

**Comment by nihj09** [comment]
This is the solution that works for Nightly builds. https://github.com/brave/brave-browser/issues/18961#issuecomment-955241606 : "It seems to be the wallet functionality. If I disable the brave://flags/#native-brave-wallet experimental flag, it doesn't happen!"

See if it works in Beta build

**Comment by NexVeridian** [comment]
disable brave://flags/#native-brave-wallet
fixed the problem for me on

Brave | 1.32.84 Chromium: 95.0.4638.54 (Official Build) beta (64-bit)
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Windows 10 Version 2004 (Build 19041.1052)

**Comment by privacyosint** [comment]
https://github.com/brave/brave-browser/issues/19193 Linux for me

**Comment by jhefgithub** [comment]
@nihj09 said:
> This is the solution that works for Nightly builds. [#18961 (comment)](https://github.com/brave/brave-browser/issues/18961#issuecomment-955241606) : "It seems to be the wallet functionality. If I disable the brave://flags/#native-brave-wallet experimental flag, it doesn't happen!"
> 
> See if it works in Beta build


@NexVeridian said:
> disable brave://flags/#native-brave-wallet fixed the problem for me on
> 
> Brave | 1.32.84 Chromium: 95.0.4638.54 (Official Build) beta (64-bit) Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871} OS | Windows 10 Version 2004 (Build 19041.1052)


Thanks for the replies, folks,
This worked like a charm for me as well.  A new Brave-Beta Private window has gone from 100% CPU usage to almost ZERO!

Do you have any idea of what functionality we lose by disabling this flag?
I am still receiving Brave pop-up notices for ads. 
Is it possible that this fix might break the Rewards functionality with the Brave wallet?

Thanks again for the help.

**Comment by bbondy** [comment]
Fixed here, will be updated within the next couple days. Closing this one as a duplicate.
https://github.com/brave/brave-browser/issues/18961
