### ISSUE TITLE
Add + Add Custom Asset to the Select Asset View

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19139]
## Description 
We need to add a `+` button to the top right corner in the `SelectAsset` view to open the `AddVisibleAseets` modal.

![Screen Shot 2021-11-01 at 10 34 59 AM](https://user-images.githubusercontent.com/40611140/139707365-e51ac965-fcff-4bd7-b25d-afa7a8159d4c.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11559>brave/brave-core#11559</a></li>
         <li>Verified new <code>+</code> button is available for all Buy/Send/Swap options on both widget and panel</li>
         <li>Verified clicking on <code>+</code> on panel loads add asset route page in a new tab</li>
         <li>Verified able to directly navigate to add asset view by visiting <code>brave://wallet/crypto/portfolio/add-asset</code></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/149325429-acc6a115-1f42-4f95-afdc-9be1f84abfc9.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/149324829-dcecc647-2e05-449d-976b-260582307f9d.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/149297683-9632b76a-aee5-46ac-8b2a-dc161d920810.mov>
      </td>
   </tr>
</table>
