### ISSUE TITLE
1 Task Manager Bug and 1 Task Manager enhancement

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#1913]
Have you searched for similar issues? Yes and I think it could be fixed with #1278 

## Description 
When you create New Private Windows and close them, multiple tasks of the same tasks, extension and other remain in memory or at least look like it in Brave's Task Manager.

## Steps to Reproduce

   1. Open New Private Window
   2. Close Private Window
   3. Open Brave's Task manager

## Actual result:
![screenshot_20181030_235536](https://user-images.githubusercontent.com/31957540/47767826-4a6f1380-dccd-11e8-9e81-8c394c14a5dc.png)

## Expected result:
Closed Windows should not still be in memory.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
0.56.6 Chromium: 70.0.3538.67 (Official Build) beta (64-bit) from ...x86_64.rpm on OpenSuse

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes.

### Additional Information

As for the 1 enhancement, in Brave's Task Manager, it would be better to have all tasks appropriately sectioned. So all opened tabs listed under Tasks to be viewed within a section which presents total Memory footprint of all the tabs inside when it isn't expanded, same goes for user installed extensions as well excluding Brave related features.

~~~
Browser
GPU Process
Tabs:-
 -
  -
Brave Rewards
Brave
Extensions:-
-
 -
~~~

**Comment by tomlowenthal** [comment]
This is working as intended: there are separate instances of those extensions with their own state and memory.

**Comment by NumDeP** [comment]
I'd appreciate it if someone else took a second look at this and perhaps apply a `feature/user-interface` label to it. 

I understand it is working as intended but it is unnecessary for certain extensions and their instances to be shown in the task manager if 'Private Window with Tor' is existed and currently it doesn't allow anyone to perform easy to view tests. 

Just to fill you in again, if a user were to open normal browsing and task manager, understandably everything that a user has enabled is shown as well as other requisites of the browser.

I have two issues with the task manger, the first one being if you open Tor, the task manager understandably displays the additional instances but as you close the Tor browser, those instances still remain in plain view in the task manager. I think someone somewhere clarified that it isn't using any memory but it just doesn't look neat and if you're trying to figure something out or perform comparison tests or any other kind of tests, everything just looks complicated.

The second issue is that the order of things don't present themselves neatly. You know next to the headers of task manger it has the `arrow` to either allow Tasks to be set alphabetically and Memory to be set in terms of highest and lowest footprint,  [ Task ` ^   `   |     Memory footprint     |    CPU   ...] which is the standard Chromium/Google based arrow functionality. 

Not to come across as demanding, I just think it only requires a couple of tweaks for better organisation and a neater view of applications.
What I suggest is to simply add one more functionality to `Task` (which would be the fourth setting) which sorts it like the following:

~~~
| Task                                        | Memory footprint     
Browser
GPU Process
Utility: Bat Ledger Service
Utility: Bat Ads Service

Extension: Brave Rewards
Extension: Brave

Extensions:
-Extensions: Print Friendly
-Extensions: Screenshot

Tabs:
-Tabs: IMDB
-Tabs: Samsung

Utility: Tor Launcher
Incognito Extension: Brave Rewards
Incognito Extension: Brave

Extensions:
-Incognito Extension: PDF Viewer

Tabs:
-Incognito Tab: Github
~~~
