### ISSUE TITLE
Brave Ads notifications are "cut off" and need to be expanded to read them – unsure if it's an Android 12 issue or just a OneUI 4 issue

### ISSUE THREAD

**Issue by meejle** [brave/brave-browser#19145]
## Description 
![Screenshot_20211101-175229_Reddit](https://user-images.githubusercontent.com/35422415/139717556-4bcf5322-9192-4785-899b-658ff10e043e.jpg)

## Steps to reproduce 

   1. Receive a Brave Rewards notification on OneUI 4.0 Beta 3

## Issue reproduces how often 
Every time

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): armv8-a
   - Device type (Phone, Tablet, Phablet): Phone – Samsung Galaxy S21 Ultra Exynos, SM-G998B
   - Android version: OneUI 4.0 Beta 3, Android 12, build number SP1A.210812.016.G998BXXU3ZUJG
   
## Brave version
Release, 1.31.88

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
++ as I have received report of this as well

**Comment by srirambv** [comment]
I can't repro it on Pixel device

**Comment by aseren** [comment]
I was able to reproduce this issue on Android 12 emulator device (Pixel 5) without OneUI 4 installed. The issue is connected to custom notification changes on version 12: https://developer.android.com/about/versions/12/behavior-changes-12

PR with fix changes Android notification appearance and on version 12 notifications will look like following:
![image](https://user-images.githubusercontent.com/86598290/149738076-3eb757e1-7ef3-4fdd-a5ad-78f6aa8dd347.png)

**Comment by Uni-verse** [comment]
Verification PASSED using version `1.36.107` on `Android ARM`

Device: `Samsung GS 21` | `Android 12` | `One UI Version: 4.0`

- Verified Brave Ads are not cut off in the notification tray.

1 | 2
-|-
<img width="416" alt="Screen Shot 2022-02-28 at 6 10 03 PM" src="https://user-images.githubusercontent.com/17885425/156234135-e66a3e8d-ba75-457b-affa-0fc02a42c8ab.png"> | <img width="416" alt="Screen Shot 2022-02-28 at 6 25 36 PM" src="https://user-images.githubusercontent.com/17885425/156234145-772977c1-8a92-4997-a43a-91d19bea8753.png">
