### ISSUE TITLE
Fix Double Scroll Bar In Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19146]
## Description 
Fix double scroll bar bug that is occurring when the browser windows height is shrunk down.

![image](https://user-images.githubusercontent.com/40611140/139717898-cf3b0dac-87e2-4d2b-8c21-792602d087b4.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified no double scroll bar is shown when window is small</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141113714-888b732d-b427-4ba0-8b6f-bdee70dee39c.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141113931-e2258440-7559-4e31-b28a-fcd05fd36662.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141113810-a1ada39c-087b-4891-8501-e7447bfb5572.mov>
      </td>
   </tr>
</table>
