### ISSUE TITLE
Android S Ads notification crash

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#19149]
## Description 
Ads notifications will crash on Android 12. 

## Steps to reproduce 

   1. install nightly app
   2. enable ads by clicking on `start using rewards`
   3. wait for the notification

## Actual result 
Browser crashes.

## Expected result
Browser doesn't crash.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
Nightly.

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@srirambv you'll need to run through this one alone as you're the only one with an Android 12 device at the moment. I ordered a Pixel with Android 12 so we have two within QA but it hasn't shipped/still on back-order. I think a single check on your device should be good enough.

**Comment by srirambv** [comment]
Verification passed on Pixel 3XL with Android 12 running 1.31.90 x6 build
- Verified no crash when ads notification is shown
- Verified no crash when clicking on ad and opening landing page
- Verified no crash in general when using the app
- Verified no crash when disabling and enabling ads
