### ISSUE TITLE
Github should be spelled GitHub on brave://settings/rewards

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19155]
## Description 

Github should be spelled GitHub on brave://settings/rewards

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `brave://settings/rewards`
   4. look at the spelling of `GitHub`

## Actual result:

`Github` (note the lower-case `h`)

<img width="1609" alt="Screen Shot 2021-11-01 at 5 29 50 PM" src="https://user-images.githubusercontent.com/387249/139760963-0670e78f-536f-4dbc-8a58-a897bb857d3d.png">

## Expected result:

`GitHub` (note the capital `H`)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.33.50 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by lpizzinidev** [comment]
Hi! Can I work on this issue?

**Comment by bsclifton** [comment]
@lpizzinidev please do! 😄

**Comment by coder-abhi** [comment]
What is the status of this issue? 
Assign it to me if possible.

**Comment by lpizzinidev** [comment]
@bsclifton I'm currently working on other projects and I didn't have time to check this out.
You could assign this to @coder-abhi if you wish.

**Comment by bsclifton** [comment]
done 😄 @coder-abhi let me know if you have any questions

**Comment by coder-abhi** [comment]
Hello @bsclifton . help me out with this error i get while building on local machine
![brave-installation issue](https://user-images.githubusercontent.com/69362502/141415673-d8c5a99d-1f50-4a5b-9ac1-482ccc7b452d.JPG)

**Comment by bsclifton** [comment]
@coder-abhi ah - this is a bug we have which is not solved unfortunately. Some commentary about it here:
https://github.com/brave/brave-browser/issues/13631

Basically, you should be able to downgrade your `npm` version in order to work past this. For example, you can install `6.14.11`

I'll create an official issue for this because it's a bit embarrassing having to use an old NPM to work-around this

**Comment by hmarcuzzo** [comment]
I started working on this issue, but the page dosn't exist anymore and in the new page this has already been fixed

**Comment by amit-2000** [comment]
is this issue still open?

**Comment by stephendonner** [comment]
> is this issue still open?

@amit-2000 hi, yes, the pull request is still open too: https://github.com/brave/brave-core/pull/11719.  That'll need to get reviewed and landed, before we close this out and verify it.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.73 Chromium: 98.0.4758.66 (Official Build) nightly (x86_64)
-- | --
Revision | db1b4001d5ce29f141297f260d2b778e000b85a3-refs/branch-heads/4758@{#762}
OS | macOS Version 12.2 (Build 21D48)

Confirmed it's spelled `GitHub` now in `brave://settings/rewards`.

<img width="1150" alt="Screen Shot 2022-01-26 at 5 46 26 PM" src="https://user-images.githubusercontent.com/387249/151276883-45357a94-4b8d-48a6-ba01-ee1a5534fbf1.png">
