### ISSUE TITLE
UI should uses address from GetPendingSignMessageRequests to display request

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#19153]
STR:
1. Add an "Account 2"
2. Navigate to https://wallet.polygon.technology/
2. Click "Connect to a Wallet"
3. Give permission to account 1 and reject the signing request
4. Refresh the page
5. Select Account 2 on wallet panel
6. Click "Connect to a Wallet" again 
7. It's displaying sign request with Account 2 while in the native side the request is for Account 1

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified when Account 2 is selected ,sign request message is for Account 1 as that is the connected wallet</li>
        </ul>
      </td>
   </tr>
</table>
