### ISSUE TITLE
Update Account Balances After Transaction Status Change

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19156]
## Description 
We need to Update Account Balances after a transactions status has changed to either `Confirmed` or `Error`

<img width="1243" alt="139758926-62634068-a0de-46e6-8a58-b03837e95cd1" src="https://user-images.githubusercontent.com/40611140/139777808-62f179be-9c40-45e0-9abb-de01e171ff58.png">

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified status updates correctly</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141174073-ab6b2fa2-ab48-449e-a2bc-c602c872cfa7.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141176990-755e68a0-b61c-40a2-a334-d2f7f5deadc0.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141174935-97476b34-50a8-4d54-b0b5-8bd6d1916cfe.png>
      </td>
   </tr>
</table>
