### ISSUE TITLE
Use more shorter NPT SI component update check interval

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19154]
## Test plan
1. Start Brave. Check component version in brave://components for sponsored image
2. Have someone publish a new component
3. 15 minutes from launching (step 1) it should update to the new version

Tip: To use dev-component, pass `--use-dev-goupdater-url` cmd switch.
For publishing new dev-component, ping to @simonhong.

## Description
To deliver it at a more accurate time, let's use 15min update check interval. 1h is current interval.

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.33.67 Chromium: 96.0.4664.35 (Official Build) nightly (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)

### Steps:
1. new profile
2. launched Brave using `--use-dev-goupdater-url`
3. loaded `brave://components`
4. confirmed `NTP SI` component was at `1.0.71` @ `5:28pm PDT`
5. @simonhong pushed `1.0.72` to the `US` region
6. waited 15 minutes
7. confirmed `NTP SI` component was updated to `1.0.72` around `5:43pm PDT`

1.0.71 | 1.0.72
------|------
<img width="1312" alt="Screen Shot 2021-11-05 at 5 28 33 PM" src="https://user-images.githubusercontent.com/387249/140593980-684559a8-ebed-446d-8ba9-e8711c652c24.png"> | <img width="940" alt="Screen Shot 2021-11-05 at 5 43 20 PM" src="https://user-images.githubusercontent.com/387249/140593981-e31eb41d-c4f1-449c-8787-b3d1473de481.png">

**Comment by simonhong** [comment]
Set `QA/No` as it's very difficult to test this on android with dev go-updater.
We already verified this on desktop(macOS).
I think it's safe to skip verifying this on Android because this fix is cross-platform code.
