### ISSUE TITLE
Polish the Windows upgrade experience

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1916]
Steps we can take to make sure the Windows upgrade is as smooth as possible
- [x] Ensure the name that shows in `Default app settings` is accurate. This gets updated during the upgrade... but doesn't always seem to be reflected. We may need to flush the MUI cache
- [x] If a shortcut is pinned to the taskbar (before the upgrade), it needs to work after upgrade is done. It should launch into Brave Core
- [ ] @simonhong finished work on the offline installers for Windows. We should consider packaging these instead of using a stub installer. This would still need to do a silent install (ex: not escalating via UAC). The download of the Muon update will be bigger, but the install should be much quicker (especially if our CDNs experience an outage or folks are experiencing a slow connection)

**Comment by bsclifton** [comment]
The behavior for the taskbar pin is a little odd, but it DOES work 😄 (not sure why it didn't work during the demo). Basically, it launches brave-core (which has a different icon). So the pinned item never gets focus/underline (since a different executable was launched)

**Comment by bsclifton** [comment]
For the first item, I did notice the wrong name was present in the MUI cache:
`HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache`

Deleting this key will cause it to get "re-calculated"... but even after doing that, the UI didn't update. The original key which gets set is here:
https://github.com/brave/browser-laptop/commit/ff26edb2fce8e6d80a5a415c09b73611d3fb1884#diff-ac3c512cd6ab5e2c8b8956234544a8a1R70

Somehow, the entry was removed from `HKEY_CURRENT_USER\Software\Classes\Applications`. I wonder if `BraveDefaults.exe` (which can add and remove the key) was ran during the upgrade and removed it

**Comment by bsclifton** [comment]
OK two of the items fixed above last nite 😄 

@simonhong hooked me up with an offline omaha installer and I verified it works and also doesn't open the browser afterwards. He got me a copy of the one for master- I'll need one for 0.56.x on 32-bit and 64-bit cc: @mbacchi (basically blocked until we can get those

**Comment by simonhong** [comment]
With https://github.com/brave/omaha/pull/13/files, we could install silently.

**Comment by bsclifton** [comment]
For next steps:
- reviewers (including me) review + merge https://github.com/brave/brave-core/pull/810
- new 0.56.x build takes place (@mbacchi can help with this)
- manually apply https://github.com/brave/omaha/pull/13 to help create the installed needed 😄 

Earlier today, I verified an executable @simonhong created from master using https://github.com/brave/omaha/pull/13, so this approach should work great 😄

**Comment by bsclifton** [comment]
We can move forward with just 64-bit (which I confirmed works as expected!)

We'll be having a release which quickly follows 0.56.x. For that final release, we'll need to update the binaries for all platforms
