### ISSUE TITLE
When `Brave Rewards` are disabled, clicking on the link at `brave://settings/rewards` doesn't launch the rewards panel if the `Brave Rewards` button is hidden

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#19163]
## Description 

If `Brave Rewards` are disabled, clicking on the link at `brave://settings/rewards` only begins the rewards processes but wouldn't launch the rewards panel if the `Brave Rewards` button is hidden via `brave://settings/appearance`.

## Steps to Reproduce

   1. Make sure `Brave Rewards` are disabled.
   2. Hide the `Brave Rewards` button via `brave://settings/appearance`.
   3. Open `brave://settings/rewards`.
   4. Click on `Click here to learn more`.

## Actual result:

The `Brave Rewards` panel wouldn't show up, as per https://github.com/brave/brave-browser/issues/18158.

## Expected result:
Clicking on the link should launch the rewards panel as per https://github.com/brave/brave-browser/issues/18158.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.57 Chromium: 95.0.4638.69 (Official Build) nightly (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

@Miyayes @emerick

**Comment by Tonev** [comment]
This issue seems to be related to my current user profile, couldn't reproduce with a completely fresh user profile. Closing.

**Comment by stephendonner** [comment]
@Tonev would you mind trying an upgrade from 1.31.87 -> 1.32.x, if you have time?

**Comment by Tonev** [comment]
@stephendonner 

I figured it out just now. The rewards panel wouldn't show up when `Hide Brave Rewards button` at `brave://settings/appearance` is disabled.

I'll update this bug report with my discovery so developers can take a look when possible.

**Comment by Tonev** [comment]
If this is the expected behavior, I don't think clicking on the link should start any `Brave Rewards` processes if users aren't displayed anything at the time, because users won't understand any new processes have been started unless they check Brave's Task Manager.

**Comment by emerick** [comment]
@Miyayes Any opinon/thoughts on the correct behavior in this situation (i.e., how do we handle clicking `Start Rewards` in brave://settings/rewards when the user has the Rewards button hidden)?

**Comment by Miyayes** [comment]
> @Miyayes Any opinon/thoughts on the correct behavior in this situation (i.e., how do we handle clicking `Start Rewards` in brave://settings/rewards when the user has the Rewards button hidden)?

Is it possible to temporarily enable it, pop it open, and once Rewards is enabled and onboarding is complete, hide it again?

**Comment by emerick** [comment]
@Miyayes Yep, and in fact, I think we do something like that in other similar situations.

**Comment by Miyayes** [comment]
@Tonev Is this still an issue?

**Comment by Miyayes** [comment]
Closing as stale. Please refile if you see this again in more recent versions of Brave.
