### ISSUE TITLE
CR 96- brave://settings are shown on a single page instead of a section by section in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19167]
## Description 

CR 96- brave://settings are shown on a single page instead of a section by section in an upgraded profile

## Steps to Reproduce

   1. Clean profile `1.33.38` or latest nightly build ` 1.33.47`
   2. Upgrade the profile to CR 96 - 1.33.39
   3. Open brave://settings
   4. Click on any of the settings from the sidebar menu
   5. Brave settings are shown on a single page instead of a section by section
   6.  Delete the profile and launch brave with a new profile 
   7. open brave://settings, brave settings are shown section by section in a clean profile of `1.33.39`

## Actual result:

![Nightly build upgrade from 1 33 38 to 1 33 39](https://user-images.githubusercontent.com/38657976/139815730-b1ced8c6-c8f1-4996-a874-f593c7dde49b.gif)

## Expected result:
Brave settings should be shown section by section in an upgraded profile of  CR 96 1.33.39

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.33.39 Chromium: 96.0.4664.27 (Official Build) nightly (64-bit)
-- | --
Revision | 0658dae02ef18b530eda4384920ee23f5e156c55-refs/branch-heads/4664@{#459}
OS | Windows 10 Version 21H1 (Build 19043.1288)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by rebron** [comment]
@GeetaSarvadnya I think this is stale and no longer the case. Can you retest?

**Comment by rebron** [comment]
Closing as stale.
