### ISSUE TITLE
Provide feedback to users on confirmation panel view for hardware transactions

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19166]
## Description 

Hardware transactions have 2 steps of confirmations, the first is on the Panel Confirmation view, the second is on the device. We do not have any way to provide the feedback in the UI to users If the transaction has been declined on the device or an error happened. The panel stays with the confirm button and user can do multiple clicks. 

Would be great to add not only errors but additional view like "Go to device and confirm transaction" because it can be not obvious to some users.

## Steps to Reproduce

   1. Make hardware transaction
   2. Decline it on device

## Actual result:

No error appeared

## Expected result:

User sees error message

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by spylogsster** [comment]
There are few operations when we get error messages from devices:
- signing transactions, in master it is in the `handlers.ts` (https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/async/handlers.ts#L402) but I move it to `wallet_panel_async_handler.ts` in my opened PR https://github.com/brave/brave-core/pull/10902/files#diff-54c80cca70af79cdc89fd074c1f87ede5ce5600ca72f74f5f0f0db4b203981a6R137

- signing messages (https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/panel/async/wallet_panel_async_handler.ts#L191) I also changed it in PR https://github.com/brave/brave-core/pull/10903/files#diff-54c80cca70af79cdc89fd074c1f87ede5ce5600ca72f74f5f0f0db4b203981a6R232

All of these places return errors from the devices, but the values are currently being ignored and not redirected to the users.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.104 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/11056>brave/brave-core#11056</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Cancel Transactions
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141986866-33c565f8-40ff-4c52-8493-c898c3619f3d.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141986127-c418285c-c5ae-4e3b-a87c-f8e82d8b91da.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141985944-9178d528-883d-475c-8c68-d130425f95c0.mov>
      </td>
   </tr>
   <tr>
      <td>Submit Transactions
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141986826-9cef3834-8e05-4ad1-ad9c-24d2594bf1a9.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141986772-5b9d014a-8c73-459c-98aa-64d5b94daeff.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141986030-15762d08-cfa2-4c4b-b774-ed1533b217bc.mov>
      </td>
   </tr>
</table>
