### ISSUE TITLE
Tor window progress is not rendered

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19165]
Tor private window shows always `disconnected`
This is regresssion of https://github.com/brave/brave-core/pull/10690
Only happens current nightly version - `1.33.x`

err msg from console.
```
brave_new_tab.bundle.js:3870 New Tab Page fatal error: TypeError: Cannot read properties of undefined (reading 'backgroundWallpaper')
    at Sr (brave_new_tab.bundle.js:3367)
    at newTabData (brave_new_tab.bundle.js:3367)
    at brave_new_tab.bundle.js:3367
    at f (brave_new_tab.bundle.js:3367)
    at brave_new_tab.bundle.js:3367
    at Object.dispatch (brave_new_tab.bundle.js:3367)
    at Object.setInitialData (brave_new_tab.bundle.js:3367)
    at brave_new_tab.bundle.js:3870
```

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.33.62 Chromium: 96.0.4664.27 (Official Build) nightly (x86_64)
-- | --
Revision | 0658dae02ef18b530eda4384920ee23f5e156c55-refs/branch-heads/4664@{#459}
OS | macOS Version 11.6.1 (Build 20G224)

### Steps:
1. new profile
2. launched Brave
3. opened Developer Tools
4. selected the `Console` tab
5. `File` -> `New Private Window with Tor`
6. waited for Tor to successfully initialize
7. checked `brave://tor-internals`

Confirmed Tor loads without any errors.

example | example | example
---------|----------|---------
<img width="1146" alt="Screen Shot 2021-11-04 at 8 35 39 AM" src="https://user-images.githubusercontent.com/387249/140362984-29c2ea03-3813-4580-ab14-97f6d93ec0e9.png"> |<img width="1183" alt="Screen Shot 2021-11-04 at 8 36 04 AM" src="https://user-images.githubusercontent.com/387249/140363022-76012a34-9f8d-471e-ba7c-ae9c34375e57.png"> | <img width="1183" alt="Screen Shot 2021-11-04 at 8 36 07 AM" src="https://user-images.githubusercontent.com/387249/140363041-994e3fc0-efc0-4fb5-a318-d31e6bae210e.png">
