### ISSUE TITLE
Hookup switchEthereumChain UI

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#19160]
blocked by both https://github.com/brave/brave-browser/issues/18583
and https://github.com/brave/brave-browser/issues/19072

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.99 Chromium: 96.0.4664.35 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10939>brave/brave-core#10939</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141479225-c88865df-9ad1-45a0-b7db-cead737b3221.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141479554-e87ed7fe-bb30-4705-b1a0-5ab99809e547.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141479502-33424e7e-f2bf-420d-98c2-93757bce8123.mov>
      </td>
   </tr>
</table>
