### ISSUE TITLE
Move hardware keyrings to typescript factory module

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19171]
following up from https://github.com/brave/brave-core/pull/10681#discussion_r740711692
Create a separate module at common/api/getKeyringsByType.ts and export a function that returns either the browser keyring or one of the hardware keyrings, and this time returns a common interface with getAccounts, etc.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.34.78 Chromium: 97.0.4692.56 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/10924>brave/brave-core#10924</a> </li>
         <li>Verified wallet page and panels shows correct information for default wallet</li>
         <li>Verified able to connect Ledger and import accounts successfully</li>
         <li>Verified able to connect Trezor and import accounts successfully</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/20313>#20313</a> on all platforms</li>
        </ul>
      </td>
   </tr>
</table>
