### ISSUE TITLE
Update `AdRewards` study defaults to match the Griffin seed

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#19179]
```
        {
            "name": "AdRewardsStudy",
            "experiments": [
                {
                    "name": "NextPaymentDay",
                    "probability_weight": 100,
                    "parameters": [
                        {
                            "name": "next_payment_day",
                            "value": "7"
                        }
                    ],
                    "feature_association": {
                        "enable_feature": ["AdRewards"]
                    }
                },
                {
                    "name": "Default",
                    "probability_weight": 0
                }
            ],
            "filter": {
                "channel": ["NIGHTLY", "BETA", "RELEASE"],
                "platform": ["WINDOWS", "MAC", "LINUX", "ANDROID"]
            }
        },
```

**Comment by tmancey** [comment]
Before deprecating studies where the feature is enabled by default we should ensure that all users, especially Android users, have proper feature values in the code across all platforms. If the feature is disabled by default then we should test that the default values are working as expected

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.83 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Ubuntu 18.04 LTS


Verified `next_payment_day` is set to `7` by default
`Nov 7`
![image](https://user-images.githubusercontent.com/34715963/198905521-089a770c-ed69-4ef6-b4dd-1eb88c2cff5e.png)
