### ISSUE TITLE
Speedreader customization controls

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#19186]
TBD: dark/light theme selector, font settings, image sizes, etc

**Comment by pixelplanetdev** [comment]
is there any way of gettng a dark theme in speed reader yet?

**Comment by ASBaumgarten** [comment]
Please add customization options for speedreader so it's not just black text on white background. Makes it near impossible to use with a dark theme at night, unless you enjoy getting your eyes seared.

**Comment by NukeManDan** [comment]
https://www.reddit.com/r/brave_browser/search/?q=SpeedReader&restrict_sr=1&sr_nsfw=

Many requests for this here too - mostly "dark mode" 

Like firefox ideally: https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages

**Comment by iefremov** [comment]
@NukeManDan this is about to start soon, pls check the newer issue https://github.com/brave/brave-browser/issues/23446

**Comment by iefremov** [comment]
automatic dark/like theme support is tracked here https://github.com/brave/brave-browser/issues/23447
