### ISSUE TITLE
Brave ad notifications timing out after a few seconds

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#19180]
## Steps to reproduce 

   1. TBC
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by aseren** [comment]
Brave Ads system notifications on Android work as expected:
- Notification is displayed for a few seconds (5 seconds)
- Then the notification is hidden but still available in the notification drawer
