### ISSUE TITLE
Create a support article with useful information about the upgrade

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1918]
- Article can live at https://support.brave.com/hc/en-us/articles/360018538092 (this should be live, although only accessible to admins)
- The deprecated Muon browser can link to the article (see https://github.com/brave/brave-browser/issues/1544)
- This should help folks that hit edge cases (described in https://github.com/brave/brave-browser/issues/1863) who need manual support

Some important goals for the support article
- Describe why this upgrade is needed
- Explain the possible impact to the user
    - needing to import, if that part fails
    - Brave Rewards impact (items that were pinned may need to be resolved manually to direct tips)
    - How default browser setting is affected (and how to set Brave Core as new default browser)

The article can then also contain information on:
- where the Muon profile lives (and letting them know it's not touched during the upgrade)
- how to launch the old browser (in case they need to save Brave Payments reports, etc)
- how to grab extension data (ex: MetaMask)
- how to find/install extensions they may have had enabled in Muon Brave

**Comment by diracdeltas** [comment]
can someone let me see the article? login is yan@brave.com (google auth)

**Comment by bsclifton** [comment]
@diracdeltas both you and @jumde should have access now 😄 Since this article has been created and has a decent amount of content, I'll close the issue. We'll of course want to review before launch 😄
