### ISSUE TITLE
Change Ropsten faucet URL to https://faucet.ropsten.be/ 

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19188]
## Description 
We are currently using https://faucet.metamask.io/ which always fail to get eth from the faucet.
We should change to https://faucet.ropsten.be/  instead.

## Steps to Reproduce

   1. Switch network to Ropsten and go to Buy tab via page or panel
   2. Click `Get Ether`

## Actual result:
Link to https://faucet.metamask.io/ 

## Expected result:
Link to https://faucet.ropsten.be/

**Comment by stephendonner** [comment]
Shouldn't this have the `1.33` milestone, @yrliou ?

**Comment by yrliou** [comment]
@stephendonner Yes I forgot to add the milestone, thanks.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified <code>Get Ether</code> for Ropsten loads <code>https://faucet.ropsten.be</code></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><Video src=https://user-images.githubusercontent.com/17010094/140926947-b59ad611-622c-4706-9b4c-5931f4df69d8.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/140927025-785df183-3e57-47f2-b4e3-52341cd82bb0.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/140926987-a129e846-400e-4e91-9ce9-01f52e761849.mov>
      </td>
   </tr>
</table>
