### ISSUE TITLE
Fix insufficient balance bug when selecting a preset

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19197]
## Description 
Some times when selecting a preset amount on the `Send` tab it will show `Insufficient Balance`

https://user-images.githubusercontent.com/40611140/139958505-c7e58496-a2d6-452e-909f-5fa875e34eb1.mov

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10836>brave/brave-core#10836</a></li>
         <li>Verified selecting a preset value doesn't show insufficient balance warning</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141145198-157889f7-ef3d-4ad3-a5df-cda086019650.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141145388-414bed87-0ba5-499a-9490-d34ebcd19c26.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141145330-d6c0240c-4e61-436a-8de5-cd40d5b728a3.mov>
      </td>
   </tr>
</table>
