### ISSUE TITLE
Allow session restore for brave://wallet tab

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19195]
It was disabled before because of the hackiness of Crypto Wallets and the extension not being loaded in time.

# QA test plan:
- Session restore should work now for brave://wallet for the new wallet whether or not brave://wallet was the active tab
- If the user sets Crypto Wallets this will run into the original problem of if brave://wallet was the active tab. But we shouldn't optimize for Crypto Wallets since it'll be infrequently used and deprecated.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.33.94 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from issue description</li>
         <li>Verified wallet page is restored between session</li>
         <li>Verified wallet page is set to focus if it was the last active tab before the session ended</li>
         <li>Verified the same behaviour works for CW as well and there is no lazy load of extension that is done with the change</li>
        </ul>
      </td>
   </tr>
</table>
