### ISSUE TITLE
Is it okay for the normal browser to close as well when 'Exit'ing Tor?

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#1920]
Have you searched for similar issues? Yes.

## Description
Naturally, in Linux versions users have to open the normal brave browser to run Tor but I believe on many occasions users tend to open or switch to New Private Window with Tor whilst there are already many tabs open in the normal browser. Exiting the Tor window via Exit at the bottom of the Menu always closes the normal browser as well with tabs still open without a warning. Is this normal and should there be a warning about closing the initial browser?

## Brave version (brave://version info)
Built 0.56.6 Chromium: 70.0.3538.67 (Official Build) beta (64-bit) from x86_64.rpm on OpenSuse

**Comment by srirambv** [comment]
That is the expected behaviour. `Exit` under menu options basically same as `Close all windows`. If you want to just close the browser window you can either close all tabs or just close via the window `X` button. This is the same behaviour on Windows as well.

**Comment by NumDeP** [comment]
@srirambv but don't you think a small notification should appear if a user forgets? 

In addition, there have been many times in the past where I've had the Tor browser in the Muon and Core version open separately on top of the normal browsing window as usual and I can't be the only one who's done this but don't you ever click on the 'x' button to close one browser down and you end up accidentally also closing the browser behind it. Now to avoid this, having done this on multiple occasions whilst having dozens of tabs open :( I always manually move the browser slightly down before closing.

Some support from would be nice.
