### ISSUE TITLE
Should billion-dollar companies and .gov Sites be added to Rewards?

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#1921]
## Description
I should admit one reason for this was because excluding some sites currently makes them pop back up after visiting them again and they're usually sites that can honestly do without contributions.

As the title suggests, it doesn't make much sense to have .gov and multi-billion dollar companies such as amazon, ebay, google (and all subsidiary sites, youtube, gmail and others), facebook (whoever still uses it), microsoft (and all subsidiary company sites, outlook, github, Linkedin and other) as well as many other international companies to appear on Rewards.

## Expected result:
Perhaps highlighted grey at the bottom without a % so users can identify any bugs if any.

**Comment by tomlowenthal** [comment]
I don't think that Brave should be in the position of deciding which sites are "legitimate" places for you to auto-contribute. You might well want to contribute to the `.gov` site responsible for your local park. We certainly don't want to maintain a list of all the places which don't "deserve" auto-contributions.

I think it's more reasonable to just allocate auto-contribute based on your attention. If there are sites you don't want to support, that's fine. I'm open to the notion that folks might want to share no-contribute lists of domains to make that easier, but Rewards really needs to get off the ground before that sort of enhancement could be considered.
