### ISSUE TITLE
Add support for signing messages by Trezor

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19219]

**Comment by srirambv** [comment]
Blocked on https://github.com/brave/brave-browser/issues/19443

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.104 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10903>brave/brave-core#10903</a></li>
         <li>Verified calling <code>eth_sign</code> with hardware transactions triggers panel to sign messages</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/19487>#19487</a> which should be the final verification of signing messages for Trezor wallets</li>
        </ul>
      </td>
   </tr>
</table>
