### ISSUE TITLE
Ad earnings "Claim buttons" cannot be clicked and are unresponsive

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19211]
## Description

Report from users: https://reddit.com/r/brave_browser/comments/qjp91a/the_claim_buttons_cannot_be_pressed_is_this_normal/

![image](https://user-images.githubusercontent.com/11497541/140153197-9c651d0b-aa46-4f75-b278-20b75821c6c4.png)

I asked if their wallets were corrupted (i.e., whether rewards-internals was reporting "Wallet not yet created"), and unanimously the answer was no (not corrupted).

**Comment by zenparsing** [comment]
@Miyayes  I was able to reproduce by enabling the "Hide Brave Rewards icon" setting. Similar to #19163.

**Comment by Miyayes** [comment]
The user confirmed that unhiding the BAT icon resolves this issue.

**Comment by LaurenWags** [comment]
Labelling `QA/Blocked` as this is pending a test plan per https://github.com/brave/brave-core/pull/11118#issue-1055199497

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.34.64 Chromium: 96.0.4664.110 (Official Build) beta (x86_64)
Revision	d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS	macOS Version 11.6.1 (Build 20G224)
```

Verified test plan from https://github.com/brave/brave-core/pull/11118

<details>
<summary>Scenario 1 - Claim single ad grant from brave://rewards - PASSED</summary>

1. Enabled "Hide Brave Rewards icon" setting from brave://settings/appearance
2. Asked Chris to send a single Ad grant, waited a bit
3. Navigated to brave://rewards
4. Confirmed able to click on "Claim" button for the ad grant
5. Confirmed BAT logo displayed and panel opened to show CAPTCHA
6. Confirmed CAPTCHA could be solved successfully
7. Confirmed when the panel is closed, the BAT logo is hidden

Step 4 | Step 5 | Step 6 | Step 7
----- | ----- | ----- | -----
<img width="464" alt="4" src="https://user-images.githubusercontent.com/28145373/146379636-be9e41cc-2cbc-4bfb-9ccc-f1823284f88e.png"> | <img width="541" alt="5" src="https://user-images.githubusercontent.com/28145373/146379641-58e6d9b8-268c-411e-91b7-69f892140607.png"> | <img width="536" alt="6" src="https://user-images.githubusercontent.com/28145373/146379652-503cfc32-719a-458f-9799-70142de181c6.png"> | <img width="444" alt="7" src="https://user-images.githubusercontent.com/28145373/146379660-8afeac07-85c6-4fb1-9f0b-9f3a020f5db4.png">

</details>

**Comment by stephendonner** [comment]
@brave/legacy_qa: per Slack convo, we only need to do scenarios 1 & 2 on all platforms: https://bravesoftware.slack.com/archives/GAA4017R7/p1639667016124800
