### ISSUE TITLE
Console error in wallet page for new wallet

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19214]
## Description 
Seeing a console error doing wallet onboarding.

## Steps to Reproduce

   1. Create a new profile and visit brave://wallet

## Actual result:
Page loads fine but seeing a console error in devtools.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'address')
    at brave_wallet_page.bundle.js:44228
    at reduce (brave_wallet_page.bundle.js:186556)
    at combination (brave_wallet_page.bundle.js:42901)
    at dispatch (brave_wallet_page.bundle.js:42661)
    at brave_wallet_page.bundle.js:44349
    at brave_wallet_page.bundle.js:44349
    at brave_wallet_page.bundle.js:43781
    at dispatch (brave_wallet_page.bundle.js:43032)
    at brave_wallet_page.bundle.js:44554
    at async refreshWalletInfo (brave_wallet_page.bundle.js:44698)
```

## Expected result:
No console error

## Reproduces how often: 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Marking QA/No as #19350 is same as this and needs to be verified on RC build
