### ISSUE TITLE
Fix Split Strings in Brave Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19217]
## Description 
There are places in the Brave Wallet where strings are split into first and second halves. 
Need to audit the strings and fix this for it will not translate correctly for some languages.

Replace as needed with `getLocale('walletStringHere').replace('$1', 'insertedString')`

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10892>brave/brave-core#10892</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>MM Import screen
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141746466-cada1141-196d-4f61-ab66-1e46cccad3e7.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141746717-0fdef55e-6942-4275-b69d-28a89770d523.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141744760-b019abc0-63aa-4bbd-8a42-1522643abe94.png>
      </td>
   </tr>
   </tr>
   <tr>
      <td>Buy Tab check
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141745865-3fa75da6-beb8-4173-9f58-cd58cd32154e.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141745378-1d12ac30-15f1-4726-8d63-e9806dae9d8f.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141745096-3fce1e9b-aa15-4253-999f-75668c4c42d9.png>
      </td>
   </tr>
   </tr>
   <tr>
      <td>Ledger Info
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141745938-abee45b7-b7d0-4318-8455-6575f82f4d30.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141745232-c0ca8bc6-b191-4383-8cfc-09a6ee41793a.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141745132-c967f436-63c0-4b76-a99d-62b12d01bffb.png>
      </td>
   </tr>
   </tr>
   <tr>
      <td>Trezor Info
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141746013-501237ee-d7e1-469e-bde8-fe93706bf490.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141745295-040c99af-e104-43c7-98ee-feefcf879c34.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141745168-447cc60b-11ec-4178-980d-ecc7f0b40a7a.png>
      </td>
   </tr>
</table>
