### ISSUE TITLE
Hidden link in IPFS preference settings page

### ISSUE THREAD

**Issue by jefersonf** [brave/brave-browser#19221]
## Description 
On the IPFS preferences page I cannot access the settings link that allows me to change my initial configuration. The link seems to be hidden by the footer.

## Steps to Reproduce

   1. Make you first access to ipfs://ipfs.io
   2. Resize your window vertically (In my case it was enough to be in maximized mode)
   3. Try clicking on the `settings` link

## Actual result:

![Screenshot from 2021-11-03 17-10-54](https://user-images.githubusercontent.com/3049540/140192510-f631c5a3-63cd-49a9-871a-47b095b5145a.png)

## Expected result:

Be able to access the settings link in any size window.

## Brave version (brave://version info)

Brave | 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by stephendonner** [comment]
Mind providing your screen/window resolution, @jefersonf?

**Comment by stephendonner** [comment]
Can confirm; thanks for the report!  When I resize my window to make `Settings` visible, it still doesn't turn into a link until I resize the window a bit more).  Looks like 144x144px on my machine reproduces the issue for me.

<img width="1408" alt="Screen Shot 2021-11-03 at 3 38 45 PM" src="https://user-images.githubusercontent.com/387249/140214154-a9a36c23-7dbb-46be-aba7-60142911b4b9.png">

**Comment by jefersonf** [comment]
> Mind providing your screen/window resolution, @jefersonf?

My screen resolution is 1294x672.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.69 Chromium: 96.0.4664.35 (Official Build) nightly (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)

Confirmed I could click on the `Settings` link even when the window size was very small.

example | example
---------|---------
<img width="815" alt="Screen Shot 2021-11-08 at 9 21 11 AM" src="https://user-images.githubusercontent.com/387249/140788914-006d5175-6aac-4eaf-97a4-c367a958557a.png"> | <img width="927" alt="Screen Shot 2021-11-08 at 9 21 33 AM" src="https://user-images.githubusercontent.com/387249/140788917-9fed07e7-4783-4207-b9b7-b0031457bea5.png">
