### ISSUE TITLE
Order of tips sites differs between brave://settings/rewards and brave://rewards

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19223]
## Description 

Order of tips sites differs between brave://settings/rewards and brave://rewards

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open `brave://settings/rewards`
   4. open `brave://rewards`
   5. compare the `Tip buttons` and `Tips` sections, respectively, for the above

## Actual result:

In `brave://settings/rewards`, the order is `Reddit, Twitter, GitHub`

In `brave://rewards`, the order is `Twitter, Reddit, GitHub`

`brave://settings/rewards` | `brave://rewards`
-------------------------|----------------
<img width="724" alt="Screen Shot 2021-11-03 at 2 59 08 PM" src="https://user-images.githubusercontent.com/387249/140199191-04de2669-94dd-448c-92d7-4b0dc6520c89.png"> | <img width="637" alt="Screen Shot 2021-11-03 at 2 59 22 PM" src="https://user-images.githubusercontent.com/387249/140199215-3e7ccd8b-1f2a-4c87-a565-f8bfdf67e90c.png">

## Expected result:

Perhaps they could just be listed in alphabetical order?

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.33.58 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)

**Comment by stephendonner** [comment]
Their order matches the `brave://settings/rewards` entry, here, in `Tips Settings`

<img width="633" alt="Screen Shot 2021-11-03 at 3 05 41 PM" src="https://user-images.githubusercontent.com/387249/140199923-cacd03af-a732-48fb-aeda-13418198f0ce.png">

**Comment by Tonev** [comment]
@stephendonner @Miyayes 

Please, take a look when possible - https://github.com/brave/brave-core/pull/10876.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.36.73 Chromium: 98.0.4758.66 (Official Build) nightly (x86_64)
-- | --
Revision | db1b4001d5ce29f141297f260d2b778e000b85a3-refs/branch-heads/4758@{#762}
OS | macOS Version 12.2 (Build 21D48)

### Confirmed the order is consistently: `Reddit`, `Twitter`, and `GitHub`.

example | example | example
---------|----------|---------
<img width="632" alt="Screen Shot 2022-01-27 at 1 02 25 AM" src="https://user-images.githubusercontent.com/387249/151326695-1dec504d-880b-4602-8b5e-b9dc1c69f48d.png"> | <img width="638" alt="Screen Shot 2022-01-27 at 1 03 06 AM" src="https://user-images.githubusercontent.com/387249/151326700-5fa27cf6-1368-473d-ad0b-5fd8a01f35a6.png"> | <img width="704" alt="Screen Shot 2022-01-27 at 1 03 53 AM" src="https://user-images.githubusercontent.com/387249/151326703-c43db0d6-a668-4bd7-9726-f4490e137b4e.png">
