### ISSUE TITLE
Sync UX hotfix

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#19233]
See https://github.com/brave/internal/issues/824 for details

**Comment by kjozwiak** [comment]
Closing as the fixes for both Desktop & Android have been merged into `1.32.x` & `1.31.x` as per the following:

### **`Desktop`**:

* https://github.com/brave/brave-core/pull/10913
* https://github.com/brave/brave-core/pull/10914

### **`Android`**:

* https://github.com/brave/brave-core/pull/10900
* https://github.com/brave/brave-core/pull/10901

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 10 Version 21H1 (Build 19043.1288)

```
- Verification notes are linked in https://github.com/brave/internal/issues/824#issuecomment-964152470

**Comment by LaurenWags** [comment]
`security` label added after checking with @diracdeltas.
