### ISSUE TITLE
wrong italian translation in adblock settings

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#19237]
## Description 

On desktop in the settings (adblocking section) there is a wrong italian text: 
in english "Block scripts" becomes in italian "Script di blocco", which is incorrect.
Instead it should be "Blocco degli script", which is similar to the other options "Blocco di tracker e annunci", 
"Blocco dei cookie" and "Blocco del fingerprinting", which are all correct translations.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-core/pull/11062. Can ben verified on 1.34.13+

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.34.62 Chromium: 96.0.4664.110 (Official Build) dev (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Confirmed the string now reads "Blocco degli script".

![italian](https://user-images.githubusercontent.com/387249/146133233-432c5ec2-ecd0-41c4-b10a-5c837a433ed4.png)
