### ISSUE TITLE
Console error when adding new networks via brave://settings/wallet/networks

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19239]
## Description 
Seeing below error when trying to add networks.
```
settings.js:1363 Uncaught (in promise) TypeError: this.$$ is not a function
    at HTMLElement.notifyKeylist (chrome://settings/settings.js:1363)
    at chrome://settings/settings.js:1363
```

## Steps to Reproduce

   1. Visit brave://settings/wallet/networks and add new networks

## Actual result:
Seeing above error in the console

## Expected result:
No console error

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10891>brave/brave-core#10891</a></li>
         <li>Verified no errors when trying to add a new custom network</li>
         <li>Verified no errors when trying to edit a custom network</li>
        </ul>
      </td>
   </tr>
</table>
