### ISSUE TITLE
Missing Hardware-accelerated video encode in Linux

### ISSUE THREAD

**Issue by Apogeum12** [brave/brave-browser#19238]
## Missing Hardware-accelerated video encode in Linux 
Missing Hardware-accelerated video encode flags for linux version
In previous version work fine after enabled flags with igpu intel

## Actual result:
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Enabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Hardware accelerated
OpenGL: Enabled
Rasterization: Hardware accelerated on all pages
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Enabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated

## Expected result:
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Enabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Hardware accelerated
OpenGL: Enabled
Rasterization: Hardware accelerated on all pages
Skia Renderer: Enabled
Video Decode: Hardware acceleration Enabled
Vulkan: Enabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated

## Brave version (1.31.87 Chromium: 95.0.4638.54)

```sh
brave-browser/stable 1.31.88 amd64 
brave-browser/stable 1.31.87 amd64
```

**Comment by KodzghlyCZ** [comment]
Have the same issue, same results

**Comment by Apogeum12** [comment]
@KodzghlyCZ Since chromium 94 you must add flags `--use-gl=desktop` `--enable-features=VaapiVideoDecoder ` in execute file.
For example in ubuntu in path:
`/usr/share/application/brave-browser.desktop` Adding in Exec:
```sh
Exec=/usr/....-stable --use-gl=desktop --enable-features=VaapiVideoDecoder 
```
Add this in all Exec in file.
In add you must have enabled ignore-blacklist etc.
I don't know how for others gpu but for Intel gpu must be installed none-free driver 
`intel-media-va-driver-non-free` and work only version 20.2.0+i374~u20.04 and alls below, others above driver version is crashed.

info from `chrome://gpu`:
![intel](https://user-images.githubusercontent.com/35242996/148652421-dbf485ce-479d-4061-b184-d80882fa7a73.png)

**Comment by KodzghlyCZ** [comment]
Yes, I did that. But the same way I still do not have video encode enabled. I think this is not much of an issue, it is just annoying to see that anything is not the way it should
