### ISSUE TITLE
Media publishers site banner

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1924]
## Description 

We need to show media publisher name and favicon in site banner circle if publisher don't provide custom image. We should do the same for regular sites regarding favicon. We need to pass name and favicon into webui. If publisher is media we should pass publisher name, if regular site we should pass in domain as name.

## Steps to Reproduce

   1. enable rewards
   2. go to https://www.youtube.com/channel/UCFNTTISby1c_H-rm5Ww5rZg
   3. click on bat logo and click donate

## Actual result:

![image](https://user-images.githubusercontent.com/9574457/47788349-c1c69680-dd11-11e8-82f4-5be758edbfca.png)

## Expected result:
![image](https://user-images.githubusercontent.com/9574457/47788422-faff0680-dd11-11e8-9f21-07c0f3a65a9c.png)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@NejcZdovc it's expected that we don't add 'on YouTube' on the site banner, correct? Just wondering as we do have this 'on YouTube' text on the panel and brave://rewards page (see below).
![screen shot 2018-11-26 at 4 12 37 pm](https://user-images.githubusercontent.com/28145373/49042424-28ff2b80-f196-11e8-8574-62859bd088e3.png)
![screen shot 2018-11-26 at 4 12 46 pm](https://user-images.githubusercontent.com/28145373/49042427-2ac8ef00-f196-11e8-85cc-f3a428a23e34.png)

Here's the site banner for comparison:
![screen shot 2018-11-26 at 4 12 57 pm](https://user-images.githubusercontent.com/28145373/49042440-2e5c7600-f196-11e8-9158-a144db48990a.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.7 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/800
