### ISSUE TITLE
`CR96`: The `Task Manager` uses wrong highlight color

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#19241]
## Description 

Something has changed during the upgrade to `Chromium 96` and now the highlight color in browser's `Task Manager` is wrong.

## Steps to Reproduce

   1. Open the browser.
   2. Open browser's `Task Manager`.
   3. Observe the highlight color after selecting a process.

## Actual result:
![actual_one](https://user-images.githubusercontent.com/20608253/140486470-f19492fa-1bf4-4aee-9068-d707dd9171e3.png)
![actual_two](https://user-images.githubusercontent.com/20608253/140486507-54eb087f-0e40-487d-8d1c-d51f86cf3749.png)

## Expected result:
![expected_one](https://user-images.githubusercontent.com/20608253/140486594-7058f8b7-1a99-4e1e-9412-443912cbbf75.png)
![expected_two](https://user-images.githubusercontent.com/20608253/140486606-71712036-3aea-4323-879f-62c7a342605f.png)

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.62 Chromium: 96.0.4664.27 (Official Build) nightly (64-bit)
-- | --
Revision | 0658dae02ef18b530eda4384920ee23f5e156c55-refs/branch-heads/4664@{#459}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

@mkarolin

**Comment by stephendonner** [comment]
Thanks as always for your keen eye, @Tonev!

**Comment by Tonev** [comment]
@stephendonner 

Happy to help after receiving such friendly replies :+1:

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.32.97 Chromium: 96.0.4664.35 (Official Build) (64-bit)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | Windows 10 Version 21H1 (Build 19043.1288)


```
- Verified the STR from the description

**_Light mode_**
![image](https://user-images.githubusercontent.com/38657976/141129723-dec6867b-471a-47c2-9633-8f06a529ae9f.png)

**_Dark mode_**
![image](https://user-images.githubusercontent.com/38657976/141129982-aed0ab71-5d06-4c11-a451-bcc402269454.png)
