### ISSUE TITLE
[Android] Use error modals in Brave Rewards settings page instead of error notifications for linking-related errors - follow up to 16652

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#19246]
## Description 

Certain errors will be shown as modals on brave://rewards on desktop which is being implemented with https://github.com/brave/brave-browser/issues/16652. This issue is to bring this functionality to Android per https://github.com/brave/brave-browser/issues/16652#issuecomment-942334570.

## Steps to reproduce 

See desktop issue https://github.com/brave/brave-browser/issues/16652

cc @Miyayes @szilardszaloki @deeppandya

**Comment by zenparsing** [comment]
May be fixed by https://github.com/brave/brave-core/pull/10934

**Comment by LaurenWags** [comment]
note - this can't be implemented until https://github.com/brave/brave-browser/issues/17780 is resolved as currently (1.32.x, 1.33.x) Android does not display these notifications.

**Comment by Miyayes** [comment]
Is this automatically resolved via https://github.com/brave/brave-browser/issues/20175?

**Comment by Miyayes** [comment]
I think we can close this issue, as of 1.35.
