### ISSUE TITLE
Not able to send BAT from my wallet

### ISSUE THREAD

**Issue by provirus** [brave/brave-browser#19243]
## Description 

In the internal wallet: brave://wallet/ , there is no error, but I cannot send BAT.

## Steps to Reproduce

1. going in brave://wallet/
2. clicking “Send BAT”
3. Choosing a BAT recipient
4. Leaving “Asset” to “BAT”
5. Putting the “Amount” I want to send

## Actual result:

The "next" button is still disabled. There is no warning, error or any info about what is happening.

## Expected result:

The "next" button must be enabled or an error must display what is missing.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave : 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)
Revision : 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS : Windows 10 Version 21H1 (Build 19043.1288)

## Other Additional Information:

I discussed that issue on https://community.brave.com/t/not-able-to-send-bat-from-my-wallet/292901 and someone thinks it might be related to gas, but there is no mention of gas at all on that page. Nothing saying it needs gas, how much gas and that I am currently missing gas if needed

<img width="311" alt="1" src="https://user-images.githubusercontent.com/1053172/140503939-bdf56cb9-d426-4935-b4a0-b02ef9fd8801.png">
<img width="318" alt="2" src="https://user-images.githubusercontent.com/1053172/140503943-66b3d291-87bc-469f-b498-f643ce53f2fb.png">
<img width="312" alt="16" src="https://user-images.githubusercontent.com/1053172/140503945-4e6973f6-e67f-4453-9e36-884228752402.png">
.

**Comment by bbondy** [comment]
Not sure what the error is but we're deprecating this wallet in a couple weeks. (it'll still be usable if you need to get to it though).  
It'll migrate to the new wallet. If you want to try the new wallet early though you can download Brave Nightly and then restore your words there. Then you'll be able to send.

**Comment by Miyayes** [comment]
Also, do you have ETH in order to pay for the transaction fee? It might be graying out the next button because there isn't enough ETH to pay for the gas fees.

**Comment by provirus** [comment]
> It might be graying out the next button because there isn't enough ETH to pay for the gas fees

That is what someone though on the community forum.

> do you have ETH in order to pay for the transaction fee?

No because the screen doesn't say anything about transaction fees or ETH. Looking at that page, I don't know that I need anything else and if I need anything else, how much. So, that is part of the bug.

> It'll migrate to the new wallet. 

I'll see if the new wallet has that same UI bug when it will be available.

thanks

**Comment by provirus** [comment]
I now have the new wallet, but that still doesn't work and doesn't show any error.

I start by filling all fields:

<img width="961" alt="1" src="https://user-images.githubusercontent.com/1053172/142071561-1873efca-bf9b-4070-b2a0-096515e0bef9.png">

Then I press "Send" and it just resets the form. Nothing is written as an error and I still have the BAT:
<img width="961" alt="2" src="https://user-images.githubusercontent.com/1053172/142071442-35fd2f62-438c-4312-bbce-46969bbb97c5.png">

**Comment by bbondy** [comment]
After you click send you should see the panel pop up from the wallet icon on the top right. Could you check there and see if there are any pending transactions in that icon?

**Comment by provirus** [comment]
Now I finally have a popup with the new version (Version 1.32.113 Chromium: 96.0.4664.45 (Build officiel) (64 bits)). 
When I tried last time, there were no popup. Now it shows that I need a crazy amount of Etherum (10,78$ USD).  That's why cryptocurrency will never replace actual money transfer... It was supposed to be less expensive than credit card fees... big fail with 56% fees, but that is a different debate.

thanks for the fix

**Comment by bbondy** [comment]
The gas fees are incredibly high on Ethereum, I agree. Note that other EVM compatible networks like Polygon, Avalanche (C-CHain) are lower cost.  In the future we'll also have Solana support.
