### ISSUE TITLE
Android 12 - App does not start version 1.31.87

### ISSUE THREAD

**Issue by ThraaxSession** [brave/brave-browser#19240]
The current version in the app store seems not to work with the current android version.  

![Screenshot_20211105-075650.png](https://user-images.githubusercontent.com/3085830/140470752-810cae38-31c2-423c-bd11-08c3f30f049e.png)

**Comment by bsclifton** [comment]
@ThraaxSession what version are you using? We are rolling out a new version now with a fix for this (`1.31.90`)

**Comment by ThraaxSession** [comment]
Hi :) this one 
![Screenshot_20211105-090834.png](https://user-images.githubusercontent.com/3085830/140478684-f08111d7-32c5-4701-b64d-82229bc9eb76.png)

**Comment by ThraaxSession** [comment]
So yes, I'll wait for the new one to validate!

**Comment by bsclifton** [comment]
Closing as there is no action needed here - other than waiting 😄 We should have this new 1.31.90` rolled out across the board end of weekend
