### ISSUE TITLE
`CR96`: When creating a new user profile, the `Done` button uses a wrong color and shape

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#19255]
## Description 

The `Done` button is blue and its shape is different.

## Steps to Reproduce

   1. Click on the hamburger menu at the top-right corner.
   2. Click on `Create a new profile`.
   3. Enter a random name for your new profile.
   4. Observe the color and shape of the `Done` button.
   5. Click on the option to choose a user profile icon.
   6. Observe the color and shape of the `Done` button.

## Actual result:

<table>
	<tr>
		<td>Actual Light</td>
		<td>Actual Light</td>
		<td>Actual Dark</td>
		<td>Actual Dark</td>
	</tr>
	<tr>
		<td><img src="https://user-images.githubusercontent.com/20608253/140608566-d42dc659-ea09-43af-bf96-48b0be0df78b.png"/></td>
		<td><img src="https://user-images.githubusercontent.com/20608253/140608568-c539a550-6982-4686-9303-15d982da6596.png"/></td>
		<td><img src="https://user-images.githubusercontent.com/20608253/140608571-c080044a-7c8e-4ec3-b42a-a9b682bf6f9b.png"/></td>
		<td><img src="https://user-images.githubusercontent.com/20608253/140608572-32a9ec56-b681-42ba-97cc-119414b29c4a.png"/></td>
	</tr>
</table>	

## Expected result:
<table>
	<tr>
		<td>Expected Light</td>
		<td>Expected Light</td>
		<td>Expected Dark</td>
		<td>Expected Dark</td>
	</tr>
	<tr>
		<td><img src="https://user-images.githubusercontent.com/20608253/140608594-2b8fbfa0-f2dd-4249-b313-b04d19bf2c9f.png"/></td>
		<td><img src="https://user-images.githubusercontent.com/20608253/140608598-fe4833e0-d8a2-4e79-a004-ce24e0520f30.png"/></td>
		<td><img src="https://user-images.githubusercontent.com/20608253/140608603-7be27739-d459-4f38-8e81-924b904e649d.png"/></td>
		<td><img src="https://user-images.githubusercontent.com/20608253/140608608-9d51f283-3327-4fe7-924c-bf033e4cda32.png"/></td>
	</tr>
</table>

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.65 Chromium: 96.0.4664.35 (Official Build) nightly (64-bit)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

@mkarolin @rebron :eyes:

**Comment by GeetaSarvadnya** [comment]
@Tonev Good catch. Thanks for logging the issue.

**Comment by rebron** [comment]
cc: @nullhook

**Comment by rebron** [comment]
cc: @mkarolin 
@GeetaSarvadnya Was this a regression from cr96?

**Comment by mkarolin** [comment]
@rebron yes, this is regression for both the `Done` button, as seen on the captures above, and the `Guest mode` button.

**1.33.x**
![image](https://user-images.githubusercontent.com/41635752/140982919-d08f0e05-143c-4ace-b005-6662fc33e6ce.png)
 
**1.31.x**
![image](https://user-images.githubusercontent.com/41635752/140983039-e9d5f704-676e-4aeb-8156-486774df5311.png)

**Comment by GeetaSarvadnya** [comment]
@rebron Yes, it's regression.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build:

```
Brave | 1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 11 Version 21H2 (Build 22000.318)
```

**`Creating Profile`** | **`Editing Profile Icon`** | **`Guest Mode Button`**
-----------------------|----------------------------|-----------------------------
![image](https://user-images.githubusercontent.com/2602313/141827305-42f79510-1caf-46b2-b185-c507910e9144.png) | ![image](https://user-images.githubusercontent.com/2602313/141827357-a794b88a-a9a4-4c22-aa91-382e791988ac.png) | ![image](https://user-images.githubusercontent.com/2602313/141827479-7f471e3b-58d6-4f3d-91bd-f7eca2ee5587.png)
![image](https://user-images.githubusercontent.com/2602313/141827639-b8642ede-66b9-41ba-84c8-42568521a13e.png) | ![image](https://user-images.githubusercontent.com/2602313/141827703-c2e619e8-67bd-414c-b62a-2ad76759f42d.png) | ![image](https://user-images.githubusercontent.com/2602313/141827767-969eafee-d45b-47dc-bf21-3baf198da63a.png)
