### ISSUE TITLE
Remove payout status banners ("X BAT will arrive in y days" notices) for unverified users once they claim

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19253]
## Description

Suppose payment date is Nov 7. Sometimes, virtual-BAT ad earnings become available a little earlier (e.g., Nov 5). Then, even though users have already claimed the BAT, the notice/countdown persists until Nov 7.

This occurred in Nov 2021, for example: 

<img src="https://user-images.githubusercontent.com/11497541/140595233-c9cff16d-1364-4f06-9ff6-7515af040298.png" width=300px>

## Solution

When user claims, clear countdown notice (@jsecretan). This basically only applies to unverified users, since verified users don't go through the claim process.

**Comment by Miyayes** [comment]
I believe this is superseded by https://github.com/brave/brave-browser/issues/18602, right? Feel free to re-open if that's not the case.

**Comment by LaurenWags** [comment]
@Miyayes I am not sure this is true.

afaik https://github.com/brave/brave-browser/issues/18602 is still date based, so if grant arrives on 5th and user claims, I think the message still shows until the 7th, at which point it will change to the "Arrived" messaging. @zenparsing should double check me on this though.

**Comment by Miyayes** [comment]
Will this be superseded by https://github.com/brave/brave-browser/issues/23429?
