### ISSUE TITLE
Use Full Version Number for Release tags

### ISSUE THREAD

**Issue by Trenly** [brave/brave-browser#19252]
## Description 

The releases page here on GitHub shows the latest release tag as `v1.33.67` when installed, the version is reported as `96.1.33.67`. Because the major version may change, I suggest that the release tags include the full version number as used for desktop

**Comment by Miyayes** [comment]
Hm, are you sure you're not mixing up the 96.1.33.67 with the Chromium version number? Brave versions usually look like this:

brave://version shows: 

Brave | 1.33.65 Chromium: 96.0.4664.35 (Official Build) nightly (x86_64)
-- | --

brave://help shows:

`Version 1.33.65 Chromium: 96.0.4664.35 (Official Build) nightly (x86_64)`

**Comment by Trenly** [comment]
![image](https://user-images.githubusercontent.com/12611259/140593509-1fdae206-6b62-4cb3-9793-5e61c0e21533.png)

**Comment by rebron** [comment]
Closing as wontfix.

Brave version can be found here -> brave://version

The 96 in the your screenshot represents chromium version.
