### ISSUE TITLE
ERROR:refill_unblinded_tokens.cc(232)] Failed to get signed tokens

### ISSUE THREAD

**Issue by MickaelTH** [brave/brave-browser#19266]
## Description 

No getting ads for 2 months, payout not getting through, all reward system is down. Even the wallpaper payout is not working.

## Steps to Reproduce

No sure how this happened at the first place. It worked fine few months, then all of the sudden with no intervention it all broke. Could be corruption of some files during Brave previous updates or I/O.

## Actual result:

ERROR:refill_unblinded_tokens.cc(232)] Failed to get signed tokens

![image](https://user-images.githubusercontent.com/26375917/140681422-0377d327-8d5d-4d00-8a30-16da5754ad99.png)

## Expected result:

Expecting to get ads and get the rewards paid to the wallet.

## Reproduces how often: 

It's always happening now as it seems Brave rewards are broken, or at least the encryption/decryption process.

## Brave version (brave://version info)

1.31.88 (Windows 10)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No, that's only for the installed version after few months of use.
- Can you reproduce this issue with the nightly channel? No, that's only for the installed version after few months of use.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? No, that's related to the rewards - this is not in Chromium.

## Miscellaneous Information:

Wallet is not linked to Uphold or Gemini (as my country is not supported), so this is purely issue on the browser internal wallet. The only solution seems to be to reset the wallet, meaning lost of the previous BAT in it.

**Comment by tmancey** [comment]
Closing issue as stale, please reopen if the issue reoccurs.
