### ISSUE TITLE
wallet performance - user activity detection for wallet locking

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#19264]
Issues:
1. Calling react set state for every mousemove is adding unneccessary performance implications
2. This does not include non-mouse users

Recommendation:

```ts
const hasInteractedSinceInterval = React.useRef<boolean>(false);
```

Add a few event handlers to detect:
- mouse move
- key down
- tab active / inactive via pge visibility API

The simpler logic would look like

```
on mousemove, if !hasInteractedSinceInterval.current, set hasInteractedSinceInterval.current to `true`
on keydown, if !hasInteractedSinceInterval.current, set hasInteractedSinceInterval.current to `true`
on visibility change, if document moved from hidden to visible and !hasInteractedSinceInterval.current, set hasInteractedSinceInterval.current to `true`
```

Then every 50 seconds, change `hasInteractedSinceInterval.current` to `false` and if `hasInteractedSinceInterval.current` is `true`, then call `notifyUserInteraction`

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.99 Chromium: 95.0.4638.54 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
      	<ul>
         <li>Verified <code>brave://settings/wallet</code> shows option for wallet auto-lock</li>
         <li>Verified default value for auto-lock is set to 5 mins</li>
         <li>Verified updating the value for auto-lock works fine</li>
         <li>Verified panel/wallet page auto-locks after the specified amount of time is passed</li>
         <li>Verified min time that can be specified is 1 minute</li>
         <li>Verified setting value to 0 and reloading cause it to update to 1</li>
         <li>Verified any activity in the wallet/page causes the auto-lock timer to postpone</li>
         <li>Verified page & panel auto-lock after the time out set in settings</li>
        </ul>
      </td>
   </tr>
</table>
