### ISSUE TITLE
Cannot build brave from source in void linux

### ISSUE THREAD

**Issue by WilliamBehrens** [brave/brave-browser#19272]
## Description 

I'm following the guide in the readme on how to build brave from source but after running `npm run init` I get 
```
ode ./scripts/init.js

Performing initial checkout of brave-core
Cloning brave-core [undefined] into /home/will/Code/builddir/brave-browser/src/brave...
------------------------------------------------------------------------------------------------------------------------------------------
/home/will/Code/builddir/brave-browser/src/brave
> git clone  .

fatal: repository 'undefined' does not exist
```

## Steps to Reproduce

   1. clone from git
   2. follow instructions in readme to build from source
   note: this may only apply on void linux or this might be a larger issue

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

latest from master

- Can you reproduce this issue with the current nightly? yes

**Comment by bsclifton** [comment]
Thanks for the report @WilliamBehrens - this is a known issue which we're tracking here (subscribe for updates):
https://github.com/brave/brave-browser/issues/19398
