### ISSUE TITLE
Don't need to ask an address for each Ethereum tokens from gemini widget

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19271]
We can share one address for all Ethreum tokens because they all return same address for Ethereum tokens.
This only increases the load on the server.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.33.94 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width="4200" src=https://user-images.githubusercontent.com/17010094/144373653-7544173e-03a6-4887-ad80-3a04510c255b.png>
      </td>
      <td><img width= 1600 src=https://user-images.githubusercontent.com/17010094/144373236-eadbaa64-7021-4dd6-8ef7-cfb40239d33f.png>
      </td>
      <td><img width="1840" alt="Screen Shot 2021-12-02 at 1 54 17 AM" src="https://user-images.githubusercontent.com/17010094/144372958-b96d2be8-e66f-4f9f-a3df-2ebb3ed9ba31.png">
      </td>
   </tr>
</table>
