### ISSUE TITLE
Implement `eth_decrypt` Ethereum method for Dapps

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19275]
See also https://docs.metamask.io/guide/rpc-api.html#eth-decrypt

This issue is to track the backend for UI on this:
<img width="323" alt="Screen Shot 2022-03-30 at 4 13 42 PM" src="https://user-images.githubusercontent.com/831718/160922877-06e457b8-552e-4073-ac3d-3944ccfbc828.png">

<img width="321" alt="Screen Shot 2022-03-30 at 4 13 47 PM" src="https://user-images.githubusercontent.com/831718/160922872-698fd27f-1eba-4b89-82a5-129f6f60bdc7.png">

## How it works:
eth_decrypt takes in 2 params:
1) A serialized JSON object which is base64 encoded
2) An address

What we will do:
- To match MM, eth_decrypt will have a user prompt to allow the user to approve that the string be decrypted by the user's private key.
- If the user doesn't approve, then the operation results in an error(user rejected)
- The user can peak at the data at any time to see what it contains, it is just only returned to the dapp if it is approved. 
- When decrypting the message we will **sanitize first**, then parse the JSON object. Note that since this is shared functionality, the JSON parsing after serialization happens in the main process. 

# Test plan

Setup a new wallet: 

```
Seed:
home various adjust motion canvas stand combine gravity cluster behave despair dove

Private key:
72d388592fb23300948c9eaf2dfaa60b8c3297903f2ea698d489d7c12116e2e6

Address is: 
0xB884707865B85990e6a140a12C3e5f5D24FE5736
```

Get the public key:

```js
var x= await window.ethereum.request({method:'eth_getEncryptionPublicKey', params:['0xB884707865B85990e6a140a12C3e5f5D24FE5736']})
```

Check the value of `x`:
>  `'eui9/fqCHT7aSUkKK9eooQFnOCD9COK9Mi1ZtOxIj2A='`

Run these commands with npm to install deps in a test directory: 
```
npm install @metamask/eth-sig-util
npm install ethereumjs-util

And then run this script: 
```js
const ethUtil = require('ethereumjs-util');
const sigUtil  = require('@metamask/eth-sig-util');

const encryptedMessage = ethUtil.bufferToHex(
  Buffer.from(
    JSON.stringify(
      sigUtil.encrypt({
        publicKey: 'eui9/fqCHT7aSUkKK9eooQFnOCD9COK9Mi1ZtOxIj2A=',
        data: 'Ode to Anthony!', // <- Be creative with different values here
        version: 'x25519-xsalsa20-poly1305',
      })
    ),
    'utf8'
  )
);
```

If you then check the value of `encryptedMessage` you'll see:

```
'0x7b2276657273696f6e223a227832353531392d7873616c736132302d706f6c7931333035222c226e6f6e6365223a2232666f7254336e4350425279653944654d31515375574e385776475a5670584e222c22657068656d5075626c69634b6579223a226d6a67655235324a4347446c393333367551774e3239716b62595230574c4b4367696e42504446747958593d222c2263697068657274657874223a22653378704b703276476d70643965634f6a524a36786c7456723046656f2b506d2f432f67544d437944673d3d227d'
```

FYI, you can see the JSON this string contains with this:

You can get back at the string with:

```js
JSON.parse(Buffer.from('7b2276657273696f6e223a227832353531392d7873616c736132302d706f6c7931333035222c226e6f6e6365223a2232666f7254336e4350425279653944654d31515375574e385776475a5670584e222c22657068656d5075626c69634b6579223a226d6a67655235324a4347446c393333367551774e3239716b62595230574c4b4367696e42504446747958593d222c2263697068657274657874223a22653378704b703276476d70643965634f6a524a36786c7456723046656f2b506d2f432f67544d437944673d3d227d', 'hex'))
```
Which gives:
```
{
  version: 'x25519-xsalsa20-poly1305',
  nonce: '2forT3nCPBRye9DeM1QSuWN8WvGZVpXN',
  ephemPublicKey: 'mjgeR52JCGDl9336uQwN29qkbYR0WLKCginBPDFtyXY=',
  ciphertext: 'e3xpKp2vGmpd9ecOjRJ6xltVr0Feo+Pm/C/gTMCyDg=='
}
```

Finally run the decrypt command with your encrypted string:

```js
const encryptedMessage = '0x7b2276657273696f6e223a227832353531392d7873616c736132302d706f6c7931333035222c226e6f6e6365223a2232666f7254336e4350425279653944654d31515375574e385776475a5670584e222c22657068656d5075626c69634b6579223a226d6a67655235324a4347446c393333367551774e3239716b62595230574c4b4367696e42504446747958593d222c2263697068657274657874223a22653378704b703276476d70643965634f6a524a36786c7456723046656f2b506d2f432f67544d437944673d3d227d'
ethereum
  .request({
    method: 'eth_decrypt',
    params: [encryptedMessage, '0xB884707865B85990e6a140a12C3e5f5D24FE5736']
  })
  .then((decryptedMessage) =>
    console.log('The decrypted message is:', decryptedMessage)
  )
  .catch((error) => console.log(error.message));
```

It will popup the UI to decrypt the message for the user. And if you press approve it will send it back to the Dapp. Check the JS console in dev tools to see.

Repeat these steps with a new seed phrase and a different message to encrypt.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.101 Chromium: 101.0.4951.64 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22616.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from issue description</li>
         <li>Verified decrypt message UI is shown correctly and the message is deciphered correctly</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/168228973-f3c21e1e-8c07-4200-b549-160b7dc2d0fa.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/168231350-721af19a-9922-4f7e-b360-d991ff1bddd9.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/168231265-a526672e-9190-456c-aae0-cca390e9b081.mov>
      </td>
   </tr>
</table>

**Comment by morgansson** [comment]
This is broken in the last release. ([Version 1.58.124 Chromium: 117.0.5938.62 (Official Build) unknown (64-bit)](https://brave.com/latest/)) It just broke my production App also.
