### ISSUE TITLE
Add allow fingerprinting functionality for troubleshooting per site

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1927]
## Description 

Currently users can only troubleshoot up to toggling on or off individual shields.
It would be great if we could empower users to troubleshoot within individual shields to toggle on and off individual resources. 

## Steps to Reproduce

   1. Load a site with fingerprinting protection
   2. Click the fingerprinting count to see the list
   

## Actual result:

You can't toggle things in this list.

## Expected result:

You should be able to toggle things in this list. 

## Reproduces how often: 

Always

## Brave version (brave://version info)

All versions, but at the time of this writing 0.57.3.

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A. 
- Is the issue reproducible on the latest version of Chrome?  N/A.

**Comment by arthuredelstein** [comment]
See https://github.com/brave/brave-browser/issues/39510

**Comment by bitcoink188-cpu** [comment]
closed and removed
