### ISSUE TITLE
Implement `wallet_requestPermissions` and `wallet_getPermissions` for compat with https://market.x.immutable.com/ and others

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19274]
https://eips.ethereum.org/EIPS/eip-2255

https://docs.metamask.io/guide/rpc-api.html#wallet-requestpermissions

https://market.x.immutable.com/ uses this and fails when connecting wallet because of it.

# Test plan

Go through the whole connect and sign in process of Immutable X and make sure it acts the same as MetaMask.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.93 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified able to connect to the Dapp similar to MetaMask</li>
         <li>Verified disconnecting the wallet, able to reconnect with the same wallet by sign message</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/151507856-8f431a95-8900-4048-a305-90590b8275f4.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151509261-cc24d665-aa9b-464f-9cd0-7fa9366d0ce2.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151510089-5f2244b1-6e4c-416c-bd67-d93b1bb4ff96.mp4>
      </td>
   </tr>
</table>
