### ISSUE TITLE
Add better handling for ` web3_clientVersion`

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19278]
Issue posted here to discuss: https://github.com/brave/security/issues/650

But I think `BraveWallet/v<chromium-version>` is an appropriate value instead of asking Infura.

For test plan see the pull request https://github.com/brave/brave-core/pull/12900

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12900>brave/brave-core#12900</a></li>
         <li>Verified Brave Wallet version is shown with CR version</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/166653104-f56a4f46-27b2-4667-af21-bdfe7f98b244.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/166653561-21154eef-c9df-4bc2-a057-f7643ce41682.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/166652768-84cf2307-7d87-40a8-a405-ca3d6664979a.png>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Removing Android label as Android specific issue is logged https://github.com/brave/brave-browser/issues/22799
