### ISSUE TITLE
Captcha gives no indication of success/failure on Linux

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#19288]
@jonathansampson reports that a Linux user tried to solve the Rewards CAPTCHA and nothing happened (no visual indication of success or failure). When asked to purposefully fail the CAPTCHA, the same thing occurred: no visual indication of failure.

The user is running `Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)` on Linux.

**Comment by manikandancode** [comment]
Not only Linux. Also with below

<html>
<body>


Brave | 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 11 Version 21H2 (Build 22000.469)
JavaScript | V8 9.8.177.9


</body>
</html>

**Comment by Miyayes** [comment]
Rewards claim CAPTCHA no longer relevant with vBAT deprecation.
