### ISSUE TITLE
Import Filecoin account from Ledger

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19285]
Now that we have Ledger support, we should add the ability to import a user's Filecoin account.

**Comment by bbondy** [comment]
Reverted here https://github.com/brave/brave-core/pull/11776 due to it causing brave://wallet not to load. So re-opening the issue.

**Comment by bbondy** [comment]
Note that I did do a fresh sync and fresh npm install and it still gave the error.

**Comment by spylogsster** [comment]
waiting when deps will be fixed https://github.com/Zondax/filecoin-signing-tools/issues/427
