### ISSUE TITLE
P3A measurements maybe causing UI hangs

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#19280]
## Test plan
TBD

## Description
After the `1.31.90` rollout, many users, mostly on Android but perhaps some also on desktop reported ui hangs. Since this is correlated with the first P3A submission window after #18224 was uplifted to release, it may be prudent to revert the change until we understand the issue better.

## Steps to Reproduce
Unknown

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rillian** [comment]
It seems the problem was first seen on `v1.31.87`, while the P3A Search Engine Switch change landed on `v1.31.88` so this is unlikely to be the cause. releases 1.31.88 and 1.31.89 didn't reach full roll-out on Android because of other issues, so 1.31.90 is the first with wide adoption.

**Comment by bsclifton** [comment]
P3A temporarily disabled on Android with https://github.com/brave/brave-core/pull/10940 - we'll want to re-enable after we find the root cause

**Comment by bsclifton** [comment]
Created https://github.com/brave/brave-browser/issues/19302 as a follow up - so we don't forget to re-enable at some point

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 10 Version 21H1 (Build 19043.1288)

```

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.31.91 Chromium: 95.0.4638.69 (Official Build) (x86_64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:

1. new profile
2. opened 9 tabs
3. changed my default search engine to Ecosia
4. disable sponsored images via new tab > `Customize` > `Show Background Images` - toggled to `Off`
5. opened `brave://local-state`
6. searched for `Brave.NTP.NewTabsCreated`; verified value of `3` corresponds to the `9 to 20` tabs, per https://github.com/brave/brave-browser/wiki/P3A#q25-on-average-how-many-new-tab-pages-did-you-create-per-day
7. searched for `Brave.Search.SwitchEngine`; verified value of `3` is correct
8. searched for `Brave.NTP.SponsoredImagesEnabled`; verified value is `0`
9. verified some of the values have `sent` as `true`

example | example | example | example | example | example
---------|---------|----------|----------|---------|---------
<img width="1165" alt="Screen Shot 2021-11-09 at 10 13 29 AM" src="https://user-images.githubusercontent.com/387249/140984285-abc474f7-1afa-4037-a89c-a80fdf6188ba.png"> | <img width="1197" alt="Screen Shot 2021-11-09 at 10 11 17 AM" src="https://user-images.githubusercontent.com/387249/140984207-d97e1139-d9b0-4dd5-9465-015e0b902857.png"> | <img width="1165" alt="Screen Shot 2021-11-09 at 10 11 35 AM" src="https://user-images.githubusercontent.com/387249/140984218-b3353284-e00a-4ec3-a4be-e05e76f654e8.png"> | <img width="1378" alt="Screen Shot 2021-11-09 at 10 28 06 AM" src="https://user-images.githubusercontent.com/387249/140984472-ad6a0c32-4f8d-4f95-9d24-1586735c89d3.png"> | <img width="1378" alt="Screen Shot 2021-11-09 at 10 28 44 AM" src="https://user-images.githubusercontent.com/387249/140984539-33d8d8e4-b19b-43b8-9bcd-72b5df06d448.png"> | <img width="1378" alt="Screen Shot 2021-11-09 at 10 29 37 AM" src="https://user-images.githubusercontent.com/387249/140984594-542a771b-bd47-4aca-a6f8-53e6176f9a72.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using the following build:

```
`1.31.91 Chromium: 95.0.4638.69`
```

**Clean Profile/New User**

* ensured that `Brave.NTP.NewTabsCreated`, `Brave.Search.SwitchEngine` & `Brave.NTP.SponsoredImagesEnabled` weren't being logged under `brave://local-state` on a clean profile on `1.31.91 Chromium: 95.0.4638.69`

**Previous/Upgraded Profile/User**

* ensured that previous data from `brave://local-state` isn't being removed when upgrading to `1.31.91 Chromium: 95.0.4638.69`
* ensured that `P3A` cohorts are not being updated after updating to `1.31.91 Chromium: 95.0.4638.69`

Found https://github.com/brave/brave-browser/issues/19324 while running through verifications. Looks like we're re-enabling `P3A` whenever an upgrade is done on `Android`.
