### ISSUE TITLE
Improve Rewards panel 2.0 initial render performance

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19287]
## Description 

The new Brave Rewards dropdown panel 2.0 takes a second or so to boot up each time the user presses the BAT icon. Would make for better UX to improve the panel load up time.

## STR

1. Click the BAT icon to reveal the Rewards dropdown panel
2. Note it usually takes 1 second or so for the contents of the panel to render/appear, even on a fast machine

**Comment by zenparsing** [comment]
See also #8674 for a likely underlying issue.

**Comment by Miyayes** [comment]
+1 from Al Ebanks, though taking 30s.

**Comment by zenparsing** [comment]
I've seen a case where, if the the panel is trying to fetch new promotions and the server is taking a long time (or there's some other network issue) the panel will stay in the loading state for a very long time.

The updated promotions list is not really necessary for displaying the panel; we should just show the panel while the promotions are loaded in the background.
