### ISSUE TITLE
Add Filecoin to the TokenRegistry and allow users to add the coin

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19284]
Open question:
- We currently store the user selected assets per network. This probably needs to change so that we can display all assets. Users should be able to filter the assets they're interested in by selected network
- Users should be able to see their FileCoin wallet balances 
- Users should be able to send FileCoin

**Comment by spylogsster** [comment]
blocked by https://github.com/brave/brave-browser/issues/20053

**Comment by bbondy** [comment]
No longer valid.
