### ISSUE TITLE
Unable to turn off reader mode

### ISSUE THREAD

**Issue by Pound-Hash** [brave/brave-browser#19286]
## Description 
The reader mode won't turn off on the [New Yorker's](www.newyorker.com/) website.

## Steps to Reproduce

   1. Visit the New Yorker, spec. [here](https://www.newyorker.com/magazine/2021/11/15/the-great-organic-food-fraud?utm_source=nl&utm_brand=tny&utm_mailing=TNY_Daily_Control_110821&utm_campaign=aud-dev&utm_medium=email&utm_term=tny_daily_recirc&bxid=5be9e4d23f92a40469fac838&cndid=52294831&hasha=0c196dd887d237c47385315a6d7071b9&hashb=260afcc60d2044d74d4a22198bdbdfbd73afc31a&hashc=6134986edf1b9b99bf6add17ef10ebc1ca0ff0fb6df7850bd920c8323b979e36&esrc=bounceX).
   2. Turn on reader mode
   3. Click to turn off reader mode

## Actual result:
Nothing happens

## Expected result:
Reader mode turns off

## Reproduces how often: 
I tried it with another article, [here](https://www.newyorker.com/magazine/2014/04/28/the-man-in-the-woods?utm_source=nl&utm_brand=tny&utm_mailing=TNY_Classics_Sunday_102721&utm_campaign=aud-dev&utm_medium=email&bxid=5be9e4d23f92a40469fac838&cndid=52294831&hasha=0c196dd887d237c47385315a6d7071b9&hashb=260afcc60d2044d74d4a22198bdbdfbd73afc31a&hashc=6134986edf1b9b99bf6add17ef10ebc1ca0ff0fb6df7850bd920c8323b979e36&esrc=NYR_NEWSLETTER_TheNewYorkerThisWeek_217_SUB_SourceCode&utm_term=TNY_SundayArchive). The same results.

## Brave version (brave://version info)

Brave | 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Linux

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? *I don't know how to disable this*

**Comment by rebron** [comment]
cc: @rillian @iefremov

**Comment by rebron** [comment]
Reader mode button is not getting users out of reader mode. Selecting the article and pasting into a new tab does work showing the original page (a workaround that does work but not ideal).

**Comment by Tonev** [comment]
Looks like a duplicate of https://github.com/brave/brave-browser/issues/18242.

**Comment by Pound-Hash** [comment]
> Looks like a duplicate of #18242.

Looks like, because it is 😉
