### ISSUE TITLE
Block/Allow scripts functionality needs rework

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1928]
## Description 

Block/Allow functionality needs rework

## Steps to Reproduce

   1. Enable `Script blocked` from shields
   2. Go into the details pane of blocked items
   3. `Blocked` text is shown which is not required as its already listed under `Blocked Scripts (x)`
   4. Rename `Undo` text to `Load` or `Run` or `Unblock`
   5. Click on `Undo` text , moves the script to `Allowed Scripts (x)` section
   6. `Block` text is before the script link where as `Undo` was after the script in blocked section

## Actual result:

![blockallow](https://user-images.githubusercontent.com/17010094/47791943-3f2ddf00-dcf1-11e8-94bb-101cd8dfbc87.gif)

## Expected result:
1. Rename `Undo` to `Unblock` to keep in line with `Block`
2. Remove `Blocked` text for scripts that are blocked 
3. Keep `Undo` and `Block` either on before the script URL or after the script URL to keep design consistent

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

master

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @rebron @karenkliu @cezaraugusto @kjozwiak

**Comment by karenkliu** [comment]
Detailed specs for the functionality are covered in #2996
