### ISSUE TITLE
Add strings for dormant users engagement modals

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#19295]
This issue is to add strings for dormant users engagement modals and notification.

**Comment by kjozwiak** [comment]
Moving this into `1.34.x` as https://github.com/brave/brave-core/pull/10942 landed in `1.34.x`. Uplifts into `1.33.x` & `1.32.x` were closed via https://github.com/brave/brave-core/pull/11240#issuecomment-982262898 & https://github.com/brave/brave-core/pull/11242#issuecomment-982263606 after speaking with @bsclifton & @anthonypkeane.

**Comment by kjozwiak** [comment]
Once we push out `1.33.x` and get Wallet out on iOS/Android, we'll need to thoroughly run through the above as I couldn't get the modals to appear within the browser after moving the date forward the expected time frames that the spec outlined.

**Comment by bsclifton** [comment]
Also see https://github.com/brave/brave-browser/issues/18880
