### ISSUE TITLE
building from source Ubuntu

### ISSUE THREAD

**Issue by MaazBinMusa** [brave/brave-browser#19293]
## Description 
I am trying to build brave from source but first it gave me undefined error on npm run init.
I changed the package.json file brave-core to brave_core
It started the init but crashed at glient sync saying

"gclient solution is incomplete"

## Steps to Reproduce

   1. Install ubuntu 18.04
   2. Install requirements
   3. run npm insatll
   4. npm run init
   5. change package.json
   6. change .gclient

## Expected result:
Build to complete

## Reproduces how often:
All the time

## Brave version (brave://version info)
latest repo

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes

Ubuntu 18.04 Bionic Beever
Node 16.13.0
Npm 8.1.0

**Comment by erazneza** [comment]
Try now changed in package.json file brave_core to brave-core and npm run init...

1.    Install ubuntu 18.04
 2.   Install requirements
  3.  run npm install
    3a. change package.json ----- brave-core to brave_core
   4. npm run init
    4a. change package.json ----- brave_core to brave-core
   5. npm run init

**Comment by MaazBinMusa** [comment]
Changing package.json before running init fixed it.
