### ISSUE TITLE
HTTPSE upgrade shows as blocked in shields 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1929]
## Description 

HTTPSE upgrade shows as blocked in shields 

## Steps to Reproduce

   1. Visit https://https-everywhere.badssl.com/
   2. Click on shields, shows `1 Total blocked `
   3. Shields badge shows count of 1 when it shouldn't. Nothings blocked on HTTPSE.

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/47792605-c3cd2d00-dcf2-11e8-95a1-977c4c45aba5.png)

## Expected result:
HTTPSE upgrades should not be counted as blocked items and should be excluded from showing count on badge

## Reproduces how often: 

Easy

## Brave version (brave://version info)

master

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @rebron @karenkliu @cezaraugusto @kjozwiak

**Comment by tomlowenthal** [comment]
resolution in #1930
