### ISSUE TITLE
dependabot alerts

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#19299]
https://github.com/brave/brave-core/security/dependabot

https://github.com/brave/brave-core/security/dependabot/package-lock.json/immer/open looks pretty bad but can't be auto-updated due to:

```
@storybook/addon-essentials@6.3.1 requires immer@8.0.1 via a transitive dependency on react-dev-utils@11.0.4
@storybook/react@6.3.1 requires immer@8.0.1 via react-dev-utils@11.0.4
```

cc @petemill

**Comment by petemill** [comment]
Uplifting to 1.32.x requires also uplifting https://github.com/brave/brave-core/pull/10499 which is also a dependency-update. thoughts @diracdeltas @remusao  - is it very low risk to break any functionality?

**Comment by diracdeltas** [comment]
@petemill that's fine with me

**Comment by remusao** [comment]
@petemill good from my side. I did a round of testing at the time on WDP worked fine. I can look again a bit later today or early tomorrow.
