### ISSUE TITLE
When printing (all or even or odd) pages add an option to print pages except some page.

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#19298]
When printing (all or even or odd) pages Add an option to print pages except some page.
I am printing even pages from 1-100 I don't want to print page 6,18,60 so how will I do that if there is no option to print pages except some pages.
Currently I can only do that by typing all numbers 1by1 and that is a lengthy process, it's time consuming and there is chance of making mistake so Why not add an option in Brave like print (all or even or odd) pages and then a dialog saying except for, where we can type the pages that we don't want to be printed...

**Comment by rebron** [comment]
@clicky6 This isn't an issue we'll be addressing. It's possible this could be fixed in Chromium, I would file there. https://bugs.chromium.org/p/chromium/issues/list
