### ISSUE TITLE
CR96 - Translate bubble isn't shown when the non-English site is visited

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19300]
## Description 

CR96 - Translate bubble isn't shown when the non-English site is visited

## Steps to Reproduce

   1. Clean profile `1.33.69`
   2. Open any non-English sites, https://www.deutschland.de/de or https://www.3zsistemi.si/ 
   3. Translate bubble isn't shown

## Actual result:

The translate bubble isn't shown
![image](https://user-images.githubusercontent.com/38657976/140864781-2c397609-43a9-470c-88af-fe97eaadfb4c.png)

## Expected result:
Translate bubble should be shown

**1.31.x**
![image](https://user-images.githubusercontent.com/38657976/140864817-0e065477-8b0d-4036-b021-3fd3f72a083c.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.69 Chromium: 96.0.4664.35 (Official Build) nightly (64-bit)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | Windows 10 Version 21H1 (Build 19043.1288)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by mkarolin** [comment]
cc: @atuchin-m

**Comment by atuchin-m** [comment]
The result of #18593

**Comment by mkarolin** [comment]
This doesn't seem to be cr96-related as 1.32.x with cr96 (and without #18593) works the same way as 1.31.x does.

However, in 1.33.x with #18593 (but with #brave-translate-go disabled) I don't see the bubble that offers to install the Google Translate extension for languages like Chinese (http://news.cn/) or Hindi (https://www.aajtak.in/), so something isn't quite as expected, @atuchin-m?

**Comment by atuchin-m** [comment]
>This doesn't seem to be cr96-related as 1.32.x with cr96 (and without #18593) works the same way as 1.31.x does.
That's correct @mkarolin.

> However, in 1.33.x with #18593 (but with #brave-translate-go disabled) I don't see the bubble that offers to install the Google Translate extension for languages like Chinese (http://news.cn/) or Hindi (https://www.aajtak.in/), so something isn't 
quite as expected, @atuchin-m?
It's the same problem. The correct description of the bug is: 
The bubble isn't shown when the feature is disabled and for the source/target language out of the [brave supported list ](https://github.com/brave/brave-core/blob/master/components/translate/core/common/brave_translate_language_filter.cc#L14-L18)(for example for Chinese or Hindi).

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.79 Chromium: 96.0.4664.45 (Official Build) beta (x86_64)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. loaded each of the following URLs

Confirmed, for each, there was a dialog prompting to install Google Translate.

`https://www.3zsistemi.si` | `aol.de` | `china.com` | `https://www.deutschland.de/de`
---------|----------|---------|----------
<img width="1597" alt="Screen Shot 2021-11-15 at 10 55 11 AM" src="https://user-images.githubusercontent.com/387249/141838713-dedfad94-8a9e-4364-abc0-7b0504b0956e.png"> | <img width="1597" alt="Screen Shot 2021-11-15 at 10 55 19 AM" src="https://user-images.githubusercontent.com/387249/141838730-814778c4-345f-4d94-a0db-29cee098fdea.png"> | <img width="1597" alt="Screen Shot 2021-11-15 at 10 56 27 AM" src="https://user-images.githubusercontent.com/387249/141838736-b031a8b2-2b16-481b-a02c-7dee0c5c9b34.png"> | <img width="1597" alt="Screen Shot 2021-11-15 at 10 58 09 AM" src="https://user-images.githubusercontent.com/387249/141838744-054772be-1513-4aa7-8f01-48698d2c42b9.png">
