### ISSUE TITLE
Open Search is not working

### ISSUE THREAD

**Issue by Iftakharpy** [brave/brave-browser#19305]
## Description 
Many browsers like Google Chrome/Chromium/Microsoft Edge allow users to search in specific websites after typing the domain name and pressing the `Tab` key. It's a great feature it saves a lot of time.

## Steps to Reproduce

   1. Open Chromium/Chrome browser and Brave browser.
   2. Visit https://www.youtube.com/ on both browsers.
   3. Then open a new tab and close the tab opened earlier on both browsers.
   4. Type youtube.com and press the `Tab` button on both browsers

## Actual result on brave:
![Screenshot from 2021-11-09 17-55-57](https://user-images.githubusercontent.com/37600593/140921157-a78851ea-355d-4ccb-814f-634b3913c649.jpg)

## Expected result on chromium:
![Screenshot from 2021-11-09 17-56-11](https://user-images.githubusercontent.com/37600593/140921217-a0e1fe1e-d369-4347-8e3e-a55db34b967e.jpg)

## Brave version (brave://version info)
```
Brave | 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Linux
JavaScript | V8 9.5.172.25
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Command Line | /snap/brave/135/opt/brave.com/brave/brave --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,DnsOverHttps,LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip --disable-features=AppDiscoveryRemoteUrlSearch,ComputePressure,AutofillServerCommunication,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,SettingsLandingPageRedesign,FledgeInterestGroups,InterestCohortFeaturePolicy,CopyLinkToText,SubresourceWebBundles,NetworkTimeServiceQuerying,PrivacySandboxSettings2,IdleDetection,WebOTP,NotificationTriggers,SignedExchangePrefetchCacheForNavigations,InterestCohortAPIOriginTrial,FirstPartySets,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,NavigatorPluginsFixed,SignedExchangeSubresourcePrefetch,DirectSockets,TrustTokens,ConversionMeasurement,FederatedLearningOfCohorts,LiveCaption,TextFragmentAnchor,ReadLater --flag-switches-begin --flag-switches-end
Executable Path | /snap/brave/135/opt/brave.com/brave/brave
Profile Path | /home/iftakhar/snap/brave/135/.config/BraveSoftware/Brave-Browser/Default
Variations | AdRewardsStudy:NextPaymentDayBraveTalkStudy:EnabledConversionsStudy:NewDefaultPatternEphemeralStorageStudy:EnabledNativeCosmeticFilteringStudy:EnabledPermissionLifetimeReleaseStudy:EnabledSpeedreaderReleaseStudy:Disabled
```

## Version/Channel Information: I don't know

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Not sure
- Can you reproduce this issue with the nightly channel?  Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  Don't know
- Does the issue resolve itself when disabling Brave Rewards? Don't know
- Is the issue reproducible on the latest version of Chrome? No

### My system info
```
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish
```

**Comment by bsclifton** [comment]
@Iftakharpy this is expected - you can enable Open Search by visiting brave://settings/search and enabling `Index other search engines`
