### ISSUE TITLE
Re-enable P3A uploads on Android

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#19302]
## Description 
P3A uploading temporarily disabled with https://github.com/brave/brave-core/pull/10940

(see https://github.com/brave/brave-browser/issues/19280)

We should re-enable this once we understand the root cause or if we determine this didn't impact things over the weekend

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Vivo X70 Pro version Android 11 ` running `Bravemonoarm.64_apk_1.32.111`

<details>
<summary>Case 1: Clean install</summary>


</details>

<details>
<summary>Case 1: Upgrade install</summary>


</details>
