### ISSUE TITLE
X Total blocked heading needs to be reworded

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1930]
## Description 

X Total blocked heading needs to be reworded

## Steps to Reproduce

   1. Visit any site and open shields
   2. Shows `X Total blocked` 
   3. Makes you think  **What Total do you mean**

## Actual result:
![image](https://user-images.githubusercontent.com/17010094/47793086-d85df500-dcf3-11e8-985b-b21c49b5baf1.png)

## Expected result:
May be `XX items blocked` or `Block count XX` 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

master

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @tomlowenthal @karenkliu @rebron @kjozwiak

**Comment by karenkliu** [comment]
Closing this issue because comprehensive design specs and other issues are covered by #2565
