### ISSUE TITLE
DevTools Elements in a bugged state after specific style changes

### ISSUE THREAD

**Issue by Maxime-J** [brave/brave-browser#19317]
From https://bugs.chromium.org/p/chromium/issues/detail?id=1267389
I've filled a chromium issue but it's Brave specific.

> UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
> 
> Steps to reproduce the problem:
> 1. Find an element with a numeric value in css (eg height: 20px)
> 2. Click on the numeric value (not the unit)
> 3. Either use keyboard arrow to move up and down or enter another value like 40px
> 
> What is the expected behavior?
> 
> What went wrong?
> Changes are correctly made, but after that, dev tools are bugged :
> elements are not visually shown on the website when being hovered on the source
> and it's difficult to add styling, we can't click where we want on the styles.
> 
> Did this work before? Yes Probably before drag and slide the values and unit changing were made available.
> 
> Chrome version: 95.0.4638.69  Channel: stable
> OS Version: 11
> 
> Closing and reopening the dev tools restore the usability.
> 
> [Please note that an inline style issue can be produced like that]
> 1. add a numeric css rule for any element in element.style (eg height: 20px)
> 2. Click on the unit px and change it to another unit
> 3. Uncheck and check that styling multiple times
> 4. See the inline style problem in the source
> 
>```
>/* height: 20em; */
>em; */
>em; */
>em; */
>```
**Additional info**
All chromium browsers are affected by a bug when we try to copy css from styles.
For example width: 225px; gets copied to
```
width: 225
px
;
```
Could that Brave issue have the same origin ?

**Comment by Egnus** [comment]
I can confirm this is happening only on brave, and not only this but many more issues regarding styles like when you activate and deactivate them without changing element.

A workaround I found is to close the devtools and reopen it again, for a few minutes it will work as expected all. Then, after some rebuilds, or reload (don't know exactly the trigger) the styles will start failing again in behaviour...

**Comment by Maxime-J** [comment]
It's now fixed on latest stable release (1.32.106)
By the way, the additional info still happens, so it probably wasn't linked.
