### ISSUE TITLE
warning message when creating sync chain - follow up to 19233

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#19314]
see https://github.com/brave/internal/issues/828

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.34.7 Chromium: 96.0.4664.35 (Official Build) nightly (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)

Verification notes in https://github.com/brave/internal/issues/828.

**Comment by stephendonner** [comment]
Verified passed using 

Brave | 1.34.62 Chromium: 96.0.4664.110 (Official Build) dev (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Verification notes in https://github.com/brave/internal/issues/828#issuecomment-994215248
