### ISSUE TITLE
Fix custom Brave notification ads should not be shown after re-enabling native/system push notifications

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#19315]
Follow up to https://github.com/brave/brave-browser/issues/18332

```
- Show custom ad notifications on Android if `can_fallback_to_custom_notifications` is set to `true` and
    - Android version is 8 or older or
    - native notifications are disabled
```

## Steps to reproduce 

1. Clean install on staging on Android > 8.0
1. Use command line: `--enable-features="AdNotifications<CommandLineStudy" --force-fieldtrials="CommandLineStudy/Enabled" --force-fieldtrial-params="CommandLineStudy.Enabled:can_fallback_to_custom_notifications/true" --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/p3a/*"=6 --brave-ads-debug --brave-ads-staging --rewards=staging=true --variations-server-url=https://no-thanks.invalid`
1. Disable native notifications
1. Trigger an ad -> get custom notification ad
1. Enable native notifications
1. Trigger an ad

## Actual result 
custom ad notification is shown

![Screenshot_20211109-151718_Brave - Beta](https://user-images.githubusercontent.com/34715963/140945673-6de7964d-2987-45ad-a315-243f9abaa93c.jpg)|![Screenshot_20211110-175531_Settings](https://user-images.githubusercontent.com/34715963/140945687-bc94c6af-344d-4396-a6d2-1c65cc1e7927.jpg)
--|--

## Expected result
native ad notification is shown

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

Reproduced on Brave v1.32.95 on Samsung Galaxy Tab S5e (Android 10.0)

cc @brave/legacy_qa @jsecretan @tmancey

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue on Gionee s5.1 running Bravearm `1.33.52`

Example | Example
---------|--------
![Screenshot_2021-11-10-18-11-42](https://user-images.githubusercontent.com/38657976/141126175-000c23e0-7a36-4015-8cd1-2f3fb4568757.png) | ![Screenshot_2021-11-10-18-16-32](https://user-images.githubusercontent.com/38657976/141126207-8804aad9-366b-4dd8-ab3a-f194e1e58702.png)

**Comment by aseren** [comment]
This is working as expected. When Browser shows a Custom Notification as a fallback, it enters `notifications fallback mode` which is controlled by brave.brave_ads.ad_notification.did_fallback_to_custom preference.
To reset this mode (i.e. reset the preference) it is needed to start browser with `can_fallback_to_custom_notifications` parameter set to false:
`--enable-features=NotificationAds:can_fallback_to_custom_notifications/false`
