### ISSUE TITLE
about:adblock page with regional filters selection followup to #267

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1931]
## Description 
Create an about:adblock page followup to #267. Add regional adblock list similar to muon build
![image](https://user-images.githubusercontent.com/17010094/47667583-bd1ca980-db7c-11e8-901a-d2921141e30b.png)

## Additional information
#267 
Split from https://github.com/brave/brave-browser/issues/403

**Comment by tomlowenthal** [comment]
This should eventually live in global settings. Karen is going to produce some designs for the settings panel.

**Comment by bbondy** [comment]
sounds good, there's going to be a lot of settings over time though, more than in browser-laptop too.  uBlock has multiple tabs.

**Comment by tomlowenthal** [comment]
Yeah, I think that having a lot of settings is just the necessary consequence of having a lot of convoluted behaviors which folks might want to twiddle. I think we under-exposed advanced settings in Muon, which is part of the difference.

**Comment by emerick** [comment]
Our existing behavior (i.e., prior to any changes detailed in this ticket) is that on startup we retrieve the current application locale and start an AdBlock instance for that region if applicable. We also store this "current" AdBlock region in a preference, as there was only the concept of a single active region in this scenario.

How would we want to handle this going forward? The simplest thing would be to eliminate that preference completely and the regional filters are all initially disabled until a user enables them via the brave://adblock/ page. Alternatively we could try to be more clever and remain somewhat backward-compatible with the existing setting, "importing" it into our new regional settings on startup.

@bbondy any thoughts here?

**Comment by bbondy** [comment]
Just following up for anyone following this issue, Emerick and I talked on Slack and discussed that we'd allow anything to be set, but that'd we'd auto turn on whatever matches the current language setting. The PR is updated with that.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/57392610-4269c200-718f-11e9-8937-5cd75b5b7d45.png)
* Custom filter rules not working logged #4348
