### ISSUE TITLE
Reduce Approved Allowance in Transaction List Item

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19328]
## Description 
Reduce `Approved Allowance` in `transactionListItem` to prevent overflowing into other components.

![image](https://user-images.githubusercontent.com/40611140/141010452-8525e21b-7e09-4b5a-a494-8d3cfe317bba.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10991>brave/brave-core#10991</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141830122-b4eeb012-0b63-4e2a-bf1f-7eb66920fba4.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141830187-539d4bde-fb18-4961-aa8b-c97ae87271f9.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141825117-49286178-4048-4b10-8167-c184a71b24e4.mov>
      </td>
   </tr>
</table>
