### ISSUE TITLE
Fingerprint block in shields is broken

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1932]
## Description 

Fingerprint block in shields is broken

## Steps to Reproduce

   1. Build from master
   2. Visit https://jsfiddle.net/bkf50r8v/13/
   3. Toggle Fingerprint protection dropdown, nothing gets blocked, doesn't show blocked items list 

## Actual result:

![fingerprint](https://user-images.githubusercontent.com/17010094/47795091-3391e680-dcf8-11e8-8536-fd025419c696.gif)

## Expected result:
Fingerprint blocking should work as expected

## Reproduces how often: 

Easy

## Brave version (brave://version info)

master

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @kjozwiak @rebron @cezaraugusto @tomlowenthal

**Comment by kjozwiak** [comment]
Hmm seems to be working on `macOS 10.13.6 x64`. Example:

![fpmaster](https://user-images.githubusercontent.com/2602313/47797733-3f33dc00-dcfd-11e8-9c7c-b69c134afad3.gif)

**Comment by cezaraugusto** [comment]
can't repro either but the fingerprinting feature didn't change in the back-end so I wonder this is intermittent and/or something that also happens in the current 0.55.x shields. I don't think this was introduced with the rebrand shields pr

**Comment by srirambv** [comment]
Seems to be working on Windows and Linux with `Brave | 0.56.7`. 

Closing the issue for now. Will retest on master and reopen if reproduces.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.14 x64` - **PASSED**

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

**Comment by kjozwiak** [comment]
@srirambv is this working for you using `0.56.8 Chromium: 70.0.3538.77`?

**Comment by srirambv** [comment]
Verification passed on

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux
