### ISSUE TITLE
Fix Brave Wallet Onboarding Error

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19331]
## Description 

![Screen Shot 2021-11-09 at 3 31 54 PM](https://user-images.githubusercontent.com/40611140/141016083-fe959df1-0343-4831-b110-8e474d44d780.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.99 Chromium: 96.0.4664.35 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified no error on onboarding on clean install or on upgrade</li>
        </ul>
      </td>
   </tr>
</table>
