### ISSUE TITLE
ads and trackers blocked in shields v2 shows different blocked resources from v1

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#1933]
## Description 

after https://github.com/brave/brave-extension/pull/78, ads/trackers blocked shows a different number of resources blocked. 

## Steps to Reproduce

   1. using 0.55.x, go to https://twitter.com/brianbondy
   2. check there are 5 ads/trackers blocked. click the stat and assert they are 5
   3. using 0.56.x, go repeat the steps above

## Actual result:

shields indicate 5 resources blocked but blocked list shows only 4

## Expected result:
should show 5

## Reproduces how often: 

always

## Brave version (brave://version info)

>0.56.x

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by cezaraugusto** [comment]
fixed via https://github.com/brave/brave-extension/pull/79. DEPS update via https://github.com/brave/brave-core/pull/773

**Comment by GeetaSarvadnya** [comment]
Verification Passed on 


Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows



- Verified the site mentioned in STR along with below sites
   https://clifton.io/
   http://homestarrunner.com/
   https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API
   https://browserleaks.com/geo
   https://www.nytimes.com/
   https://jsfiddle.net/bkf50r8v/13/
   https://www.ft.com/
   https://slashdot.org/

**Comment by GeetaSarvadnya** [comment]
As per my knowledge, we will not be able to test this defect on Windows as we don't have offline installer and don't have option to install older version and upgrade it to the latest version.
@kjozwiak Please suggest if there are any ways i can test this defect on windows.

**Comment by kjozwiak** [comment]
@GeetaSarvadnya I don't think this requires a `0.55.x` -> `0.56.x` update. I believe all we need to do for this issue is the following:

* download & install `0.56.8 Chromium: 70.0.3538.77`
* visit https://twitter.com/brianbondy and ensure that `Total Blocked` lists 5 resources blocked and that 5 recourses are appearing under the `Ads and trackers blocked` list

@cezaraugusto is that correct?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux

* Verified https://twitter.com/brianbondy shows total blocked items as 5 
![image](https://user-images.githubusercontent.com/17010094/48070816-c3c3a600-e1a6-11e8-8433-cb1216631bf4.png)

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Thanks for the clarification.
