### ISSUE TITLE
Individual scripts from same domain are not listed in shields v2

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1934]
## Description 

Individual scripts from same domain are not listed in shields v2

## Steps to Reproduce

   1. Visit any site 
   2. Block scripts 
   3. Details view only shows per domain. should show individual scripts blocked

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/47799018-d00bb700-dcff-11e8-8b3d-0417d4c43145.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/47799048-e154c380-dcff-11e8-8655-6db69ae22119.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

master

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @cezaraugusto @yrliou @karenkliu @rebron

**Comment by tomlowenthal** [comment]
With some informal interviews, it seems that full script URIs aren't important. Instead, we should just show the origin domain(s).
