### ISSUE TITLE
Missing translations for Wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19348]
## Description 

Missing translations for Wallet

## Steps to Reproduce

   1. Use a non-EN locale and check wallet

## Actual result:

Passwords don't match

![image](https://user-images.githubusercontent.com/17010094/141075085-ab955b0c-0178-4837-9dd3-6eca8bda40fa.png) | ![image](https://user-images.githubusercontent.com/17010094/141076526-be1dd7ec-d741-4e01-af14-67fc9069a288.png)
-- | --

Ledger Error messages
![image](https://user-images.githubusercontent.com/17010094/141077226-9de741d2-0688-4854-98fb-a780dc673e3f.png)

Trezor Error message
![image](https://user-images.githubusercontent.com/17010094/141077335-b0dc395b-c85a-45e6-bcf3-2f794a26e538.png)

Not a valid address on Send transaction
![image](https://user-images.githubusercontent.com/17010094/141077556-c7953404-85f5-4d8a-97c1-62376f91bd0b.png)

Add network settings

![image](https://user-images.githubusercontent.com/17010094/141077894-41130a63-f2dc-4e46-b2db-e733962fea07.png) | ![image](https://user-images.githubusercontent.com/17010094/141077849-04a4e980-d788-4a2f-a954-eaf9d5981bcd.png)
-- | --

Reset Wallet message 
![image](https://user-images.githubusercontent.com/17010094/141077949-0bf29e65-2ce5-4ffc-b1b3-a1da626ec9cc.png)

Brave Wallet (Prefer Extensions) 
![image](https://user-images.githubusercontent.com/17010094/141078014-1fc9e4a2-5303-4b0c-b365-5637773dad0d.png)

Missing info for adding network
![image](https://user-images.githubusercontent.com/17010094/141078316-4e35adec-c8e2-404a-921c-99ec6a3c123a.png) | ![image](https://user-images.githubusercontent.com/17010094/141078372-5b598fd0-9e28-40e3-9474-44effe5b12a5.png)
-- | --

Update network changes
![image](https://user-images.githubusercontent.com/17010094/141078494-cc72a02f-5677-40ab-a55a-27f5e4e72b7f.png)

## Expected result:
All strings to be translated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.95 Chromium: 95.0.4638.69 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | `6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}`
Betriebssystem | Windows 11 Version 21H2 (Build 22000.282)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc; @rebron @bbondy we need to take a call to get these strings fixed for MVP

**Comment by bbondy** [comment]
I think this needs to be rechecked once @mkarolin pulls down the next translation order

**Comment by mkarolin** [comment]
Yes, let's re-check please. I haven't checked all of them but at least the ones I checked are being translated in the current round.

**Comment by srirambv** [comment]
Verified the above missing strings are translated. Will add a follow up issue for the new strings that got included for 0x and CoinGecko
