### ISSUE TITLE
Archives brave-<version>-win32-x64.zip (with windows release builds) are broken

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#19344]
The zip archives `brave-<version>-win32-x64.zip` from https://github.com/brave/brave-browser/releases/ are broken.
The `chrome.dll` and some other resources are missed => the browser fails to start.
Also:
1. The size much is less than standalone installed (~37MB vs 84MB, but should be near the same)
2. The problem isn't new. A year-old (Dec 2020) `brave-v1.20.12-win32-x64.zip` is also broken

![image (3)](https://user-images.githubusercontent.com/45488748/141063998-734324e3-68ce-46ee-b872-9a3a070634fd.png)

**Comment by rebron** [comment]
cc: @mihaiplesa @brave/legacy_qa

**Comment by mihaiplesa** [comment]
We just upload the archives in the pipelines so we'd need someone to look at the browser code generating them.

**Comment by atuchin-m** [comment]
Here is the code that create the archive: https://github.com/brave/brave-core/blob/master/BUILD.gn#L370

**Comment by LaurenWags** [comment]
@atuchin-m can QA get a test plan for this one please? cc @rebron 

if no manual QA is needed, we can change this to `QA/No`.

**Comment by atuchin-m** [comment]
You simply to download the recent win zip and check that it works (without any other brave instalation on the computer).

https://github.com/brave/brave-browser/releases

**Comment by stephendonner** [comment]
Verified `PASSED` on both

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)

--and--

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) (64-bit)
--|--
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 11 Version 21H2 (Build 22000.348)

Steps:
1. downloaded `https://github.com/brave/brave-browser/releases/download/v1.34.63/brave-v1.34.63-win32-x64.zip`
2. extracted to `Downloads`
3. ran the `brave.exe` from the above folder
4. confirmed I could use the browser

Windows 10 | Windows 11
--------------|--------------
![file-archive-windows10](https://user-images.githubusercontent.com/387249/146255066-f6665986-a1c3-4deb-a147-6cd2fa34064b.png) | ![file-archive-windows11](https://user-images.githubusercontent.com/387249/146255122-5a7c0204-7274-4dc2-8d2d-4cef39724689.png)
