### ISSUE TITLE
Brave Wallet UI issues due to translated strings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19349]
## Description 

UI issues due to translated strings

## Steps to Reproduce

   1. Use a non-EN locale and use wallet

Note: Will update if I come across any other UI issue 

## Actual result:

Icon on panel gets cut off 
![image](https://user-images.githubusercontent.com/17010094/141074260-5af9a529-f04e-4c77-a326-651cd7774e3d.png)

Swap button needs padding (Not specific to translated strings)
![image](https://user-images.githubusercontent.com/17010094/141075881-73282342-3a45-4513-b2d8-f5d0eaa9bf69.png)

Panel text overload
![image](https://user-images.githubusercontent.com/17010094/141076956-227a4438-e372-4ca2-b52b-9348ee7a2a08.png)

Button oversized for custom gas price 

![image](https://user-images.githubusercontent.com/17010094/141077032-49fa488d-09f1-48f2-b9ea-3cdff009e7b1.png) | ![image](https://user-images.githubusercontent.com/17010094/141077073-a88ee621-ea1a-4006-ab84-58fb4ef8dfa4.png)
-- | --

Insufficient funds message
![image](https://user-images.githubusercontent.com/17010094/141077670-3357c6d0-7084-4904-824f-277d786b8350.png)

Panel lock screen padding missing
![image](https://user-images.githubusercontent.com/17010094/141077762-a61526f1-0048-4b16-b73c-dd1b4db706e0.png)

## Expected result:
No UI issues

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.95 Chromium: 95.0.4638.69 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
Betriebssystem | Windows 11 Version 21H2 (Build 22000.282)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @bbondy @Douglashdaniel

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.32.111 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified UI is shown correctly for translated strings

<img width="334" alt="Bildschirmfoto 2021-11-23 um 8 22 43 AM" src="https://user-images.githubusercontent.com/17010094/143035696-12a89e9e-ed10-4226-8899-2de46ea2d5c7.png"> | <img width="334" alt="Bildschirmfoto 2021-11-23 um 8 23 20 AM" src="https://user-images.githubusercontent.com/17010094/143035714-bd536d4a-f20b-4714-a9da-93407b6ef01d.png"> | <img width="334" alt="Bildschirmfoto 2021-11-23 um 8 26 40 AM" src="https://user-images.githubusercontent.com/17010094/143035719-1d4bfa24-5aac-46ad-bd26-349d99093a0c.png"> | <img width="334" alt="Bildschirmfoto 2021-11-23 um 8 26 51 AM" src="https://user-images.githubusercontent.com/17010094/143035728-a0227662-a39d-4f05-bc54-39e752923ebf.png"> | <img width="334" alt="Bildschirmfoto 2021-11-23 um 8 26 57 AM" src="https://user-images.githubusercontent.com/17010094/143035734-4b4f3af5-954d-4042-9bab-2e8647c97643.png"> | <img width="334" alt="Bildschirmfoto 2021-11-23 um 8 27 07 AM" src="https://user-images.githubusercontent.com/17010094/143035742-c26ca999-7ba5-42ca-bf32-4f84561dcac8.png"> | <img width="334" alt="Bildschirmfoto 2021-11-23 um 8 27 28 AM" src="https://user-images.githubusercontent.com/17010094/143035747-15a0f4c0-2012-4b06-864f-b935695c6844.png">
-- | -- | -- | -- | -- | -- | -- 

---------

Verification passed on 

Brave | 1.32.111 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Windows 11 Version 21H2 (Build 22000.318)


- Verified UI is shown correctly for translated strings

![1](https://user-images.githubusercontent.com/17010094/143038101-b31ef15c-8c62-4b0c-a13f-c53cd9286fbf.png) | ![2](https://user-images.githubusercontent.com/17010094/143038105-95ad2412-8798-4dff-a699-0b0a900c2e29.png) | ![3](https://user-images.githubusercontent.com/17010094/143038107-2ee2e9a8-3954-48b1-a7b3-668c9f747dfa.png) | ![4](https://user-images.githubusercontent.com/17010094/143038113-9b569231-d4c3-486b-89f2-cbc7753e33c5.png) | ![5](https://user-images.githubusercontent.com/17010094/143038119-64fb00ae-5599-48d3-95d0-734ffa419a40.png) | ![6](https://user-images.githubusercontent.com/17010094/143038122-4bd75675-090a-46e9-8169-ec836e1edea9.png) | ![7](https://user-images.githubusercontent.com/17010094/143038127-ef629baa-fc41-4798-bbfd-bfdc627e876a.png)
-- | -- | -- | -- | -- | -- | --

**Comment by bbondy** [comment]
Changing to `release-notes/include` because users using translated builds would want to know about this.
