### ISSUE TITLE
Use inclusive language in brave_network_audit

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#19357]
## Description 

brave/brave-core#10389 refactored `npm run test-security` into `brave_network_audit_tests` but carried over the previous exclusionary 'whitelist' terminology. It would be better to use [inclusive language](https://google.github.io/styleguide/cppguide.html#Inclusive_Language) here.

## Brave version (brave://version info)

1.34.3

**Comment by Mubelotix** [comment]
Dear `whitelist`,
You have been such an amazing word. Clear, short, and well known.
Over the past years, you have been one of the most loved word among programmers. And that was with a reason.
No other word could do the job better than you did.
But today, I have to say goodbye.
You have been repudiated, insulted and rejected. You have been the target of defamation.
Some people chose to destroy you and they were successful. You, the innocent little word.
The world is unfair and cruel, but please, forgive us.
I still love you, `whitelist`, and you will forever have a place in my heart.
Seeing you like this makes me feel really bad, but I assure you, you will be remembered by many.
Goodbye, `whitelist`.I swear to do what I can to protect other innocent words from being abused like you were.

**Comment by BroVic** [comment]
There are no more statues to pull down, so I guess it's fine. Kudos.

**Comment by UjCbFwtBayFM** [comment]
There's no visible technical/security reason for this change, so it can't be anything but a no from me.
