### ISSUE TITLE
Hide A-C section in Rewards settings on `brave://settings` when region is JP

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19355]
## Description

Since A-C is not available in JP region at this time, hide the A-C section in Brave Rewards settings on `brave://settings` when region is JP (using same rules/conditions as how we do it on brave://rewards settings page).

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.33.85 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 20H2 (Build 19042.1348)

JP region

Steps:

1. clean profile
2. launched Brave using --rewards-countryid=19024 to simulate running in JP region
3. opened brave://settings
4. clicked on Brave Rewards in the left pane
5. clicked the link in the right pane to open the Rewards panel
6. clicked on Start using Brave Rewards
7. clicked Skip for now
8. clicked Continue
9. clicked Do it later
10. dismissed the panel
11. looked at brave://settings/rewards

Confirmed there was no Auto-Contribution section under Brave Rewards
Additionally, confirmed no A-C on brave://rewards or the tips panel

Non-JP region

Steps:

1. clean profile
2. launched Brave in en-US region
3. opened brave://settings
4. clicked on Brave Rewards in the left pane
5. clicked the link in the right pane to open the Rewards panel
6. clicked on Start using Brave Rewards
7. clicked Skip for now
8. clicked Continue
9. clicked Do it later
10. dismissed the panel
11. looked at brave://settings/rewards

Confirmed there was an Auto-Contribution section under Brave Rewards
Additionally, confirmed an auto-contribution was scheduled for duckduckgo.com
