### ISSUE TITLE
Token list jumps back to top when a token is added

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19352]
## Description 

Token list jumps back to top when a token is added making it hard to add multiple items at a time

## Steps to Reproduce

   1. Select Add token
   2. Scroll down a bit and select a token
   3. Jumps back to top doesn't retain the position

## Actual result:

https://user-images.githubusercontent.com/17010094/141138520-afc8c64b-425a-4e91-a2a2-fc6e89007612.mov

## Expected result:
Just add the token don't refresh until user clicks Done or closes the add token modal

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @Douglashdaniel

**Comment by Douglashdaniel** [comment]
This will be fixed when we implement this https://github.com/brave/brave-browser/issues/18532

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description and <a href=https://github.com/brave/brave-core/pull/11875>brave/brave-core#11875</a></li>
         <li>Verified selecting a token via checkbox doesn't cause the list to jump back to the top</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/153827129-e875a029-b936-4bc3-8628-dee95b11f72a.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153835700-61a7d4a7-19c1-48ff-9499-08fe175758a7.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153835813-16b7a69b-de0a-4c3d-9ba0-bfdf9ed076ea.mov>
      </td>
   </tr>
</table>
