### ISSUE TITLE
Transaction status text is not showing in transaction details

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19358]
Regression caused by https://github.com/brave/brave-browser/issues/19347

Select a specific account in brave://wallet to see the transaction history of the account.
Actual result:
<img width="1100" alt="Screen Shot 2021-11-10 at 11 01 33 AM" src="https://user-images.githubusercontent.com/4730197/141181556-1f88ac64-a275-442f-846b-dff317ebd4b5.png">
Expected result:
<img width="1225" alt="Screen Shot 2021-11-10 at 11 48 27 AM" src="https://user-images.githubusercontent.com/4730197/141187869-490d265b-13f3-49ae-bd02-87bbc1cd0f8b.png">

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.33.90 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/10985>brave/brave-core#10985</a></li>
         <li>Verified transaction status is listed for a selected asset</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width= 1200 src=https://user-images.githubusercontent.com/17010094/143429377-527cf568-2210-4b38-81e0-5608bddc539a.png>
      </td>
      <td><img width= 800 src=https://user-images.githubusercontent.com/17010094/143427901-be2e7317-4cfd-403e-9312-506ccfe71985.png>
      </td>
      <td><img width= 800 src=https://user-images.githubusercontent.com/17010094/143428113-227f3940-9473-4a07-89b1-e2bb13daec7d.png>
      </td>
   </tr>
</table>
