### ISSUE TITLE
Add subtitle text string to Add Funds dialog

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#1935]
To make the add funds window a bit easier to understand, we need to add more helpful intro text.

![image](https://user-images.githubusercontent.com/13509546/47799675-02111f00-dce8-11e8-9469-7df547ed3a6e.png)

Initial strings:

Title: Send cryptocurrency from your external account to your Brave Rewards wallet.

Subhead: Be sure to use the address below that matches the type of cryto you own. It will be converted automatically to BAT by Uphold and appear as an increased balance in your Brave Rewards wallet. Please allow up to one hour for your wallet balance to update.

**Comment by bradleyrichter** [comment]
typo - "cryto" should be "crypto"

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified text was updated per description. Typo will be dealt with in https://github.com/brave/brave-browser/issues/2474
![screen shot 2018-12-12 at 5 31 07 pm](https://user-images.githubusercontent.com/28145373/49903025-bcda2400-fe33-11e8-81cf-4bdf513ea363.png)
