### ISSUE TITLE
Fix Selected Slippage Not Persisting on Refresh

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19369]
## Description 
Fix selected `Slippage` not persisting when clicking the `Refresh` button

Feedback:
``
swap price quote is not respecting the selected slippage percentage if i click the little refresh  button. seems like it always use the first option.
``

https://user-images.githubusercontent.com/40611140/141228348-a5f21ddd-c5f2-4efb-9ca2-6161675688f7.mov

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10995>brave/brave-core#10995</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141790607-bb6b238d-be67-4a37-87ab-47895580a598.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141790682-a49bb062-710c-4df7-a095-7486c339d216.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141790647-a26504e3-66e3-42bd-b138-1d2cc4730d1a.mov>
      </td>
   </tr>
</table>
