### ISSUE TITLE
Hyphens display incorrectly on macOS speedreader articles

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#19363]
## Description 

We set `hyphens: auto` in the speedreader css, which asks the layout engine to break long words at the end of lines when the article is marked with a recognized `lang` value. A user reports the square boxes where hyphen characters should be shown.

## Steps to Reproduce

   1. Enable Speedreader
   2. Visit [a page](https://pitchfork.com/news/8-dead-many-injured-at-travis-scotts-astroworld-2021-festival/) where Speedreader is triggered.
   3. Change the window width until some words are split across lines
   4. Observe line-ending word break characters
  

## Actual result:

Square boxes appear at the end of some lines.
<img width="778" alt="Screen Shot 2021-11-07 at 4 45 36 PM" src="https://user-images.githubusercontent.com/225102/141202287-93d65c18-693f-4ee5-ad9d-b21be23c0d55.png">

## Expected result:
Word-breaks should be marked by inserted hyphen (`-`) characters.
![Screenshot from 2021-11-10 14-11-14](https://user-images.githubusercontent.com/225102/141202335-075bca23-5818-451b-b98e-511f0cc36e3c.png)

## Reproduces how often: 

User reports it happens with multiple fonts on their macOS system, including Apple system fonts like Optima as well as the requested Georgia. The problem does not occur with Helvetica.

If the `hyphens: auto` style rule is disabled in devtools, words are not broken and the problem doesn't manifest.

I haven't been able to reproduce on Linux, hyphenation works as expected.

I don't see hyphenation happening at all on Windows 10, so I can't reproduce there either.

## Brave version (brave://version info)

Brave 1.33.x Nightly

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rillian** [comment]
Possibly something is wrong with font substitution, triggered by where in the layout pipeline the hyphens are inserted.

Possibly the rough quality of the speedreader html is triggering some quirk that's affecting text parsing.

Quickest work-around is to disable hyphenation in the speedreader stylesheet.

**Comment by rillian** [comment]
cc @pes10k

**Comment by rillian** [comment]
To test the theory that invalid html is triggering some quirks-mode interference, please compare the following two versions and see if either shows the hyphenation problem:

- [Speedreader html](https://thaumas.net/~giles/2021/brave-19363/default.html)
- [Reformatted to validate](https://thaumas.net/~giles/2021/brave-19363/clean.html)

I get a different column width with the cleaned version, which suggests there is something going on with layout. The css also doesn't validate, but I didn't attempt to clean that up.

**Comment by rillian** [comment]
@pes10k reports the problem still occurs with the reformatted html. :(

**Comment by boocmp** [comment]
We can just add `html {
    -webkit-hyphenate-character: '-';
}` in our style sheet

**Comment by rillian** [comment]
That would be a simple fix! @pes10k could you check please?
- [bad rendering](https://thaumas.net/~giles/2021/brave-19363/default.html)
- [possible fix](https://thaumas.net/~giles/2021/brave-19363/hyphen-char.html)

**Comment by rillian** [comment]
Possibly the same as [cr 1267606](https://bugs.chromium.org/p/chromium/issues/detail?id=1267606).

**Comment by pes10k** [comment]
@rillian good catch, https://codepen.io/brettgoulder/pen/abVNEYV reproduces for me too

**Comment by pes10k** [comment]
> That would be a simple fix! @pes10k could you check please?
> 
> * [bad rendering](https://thaumas.net/~giles/2021/brave-19363/default.html)
> * [possible fix](https://thaumas.net/~giles/2021/brave-19363/hyphen-char.html)

I'm not sure why but at least for me, right now, neither of the above shows the problem

**Comment by rillian** [comment]
> I'm not sure why but at least for me, right now, neither of the above shows the problem

Heisenbug! Does pasting `html { -webkit-hyphenate-character: '-'; }` in the codepen's css tab fix the issue?

**Comment by pes10k** [comment]
<img width="480" alt="Screen Shot 2022-03-25 at 15 12 49" src="https://user-images.githubusercontent.com/76526/160194432-c2328821-fe35-4464-a658-f2a4ed53f0d5.png">
Unfortunately no, though i did momentarily get a different box!

**Comment by rillian** [comment]
Fascinating. Ok, sounds like @boocmp's suggestion isn't sufficient on its own. :(

**Comment by pes10k** [comment]
its looking good to me now.  Hurray! I'll close this out, thanks @rillian !

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 12.6.4 (Build 21G526)
```
