### ISSUE TITLE
brave://settings/importData screen is blank, and exception is thrown

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19364]
## Description 

`brave://settings/importData` screen is blank, and exception is thrown

## Steps to Reproduce

   1.  new profile/install
   2. load `brave://settings/importData` or click on the 3-dots menu and choose `Bookmarks` -> `Import Bookmarks and Settings`
   3. look at the resulting screen

## Actual result:

The screen is empty, and an exception is thrown:

<img width="1312" alt="Screen Shot 2021-11-10 at 2 47 46 PM" src="https://user-images.githubusercontent.com/387249/141207597-bd7b3946-c199-427a-b728-3aadbf271824.png">

## Expected result:

Should pop-up the `Import Bookmarks and Settings` dialog:

<img width="1312" alt="Screen Shot 2021-11-10 at 2 44 49 PM" src="https://user-images.githubusercontent.com/387249/141207632-bba4db2e-f720-472e-bda3-94da3dd49e2d.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.32.97 Chromium: 96.0.4664.35 (Official Build) (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)

/cc @brave/legacy_qa and @mkarolin

**Comment by stephendonner** [comment]
Was fine on `1.32.95`

<img width="1597" alt="Screen Shot 2021-11-10 at 3 12 05 PM" src="https://user-images.githubusercontent.com/387249/141208889-2e4c44d4-f0ab-4fd1-b34b-28de1c1cd461.png">

Broken in:



Brave | 1.33.74 Chromium: 96.0.4664.35 (Official Build) beta (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)



Brave | 1.34.3 Chromium: 96.0.4664.35 (Official Build) nightly (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 1.32.97 Chromium: 96.0.4664.35 (Official Build) (64-bit)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | Ubuntu 18.04 LTS

Also reproducible when importing from NTP
![image](https://user-images.githubusercontent.com/34715963/141209019-f0acc2f6-3d9c-49c5-b7c9-14b1dc7977a9.png)

**Comment by kjozwiak** [comment]
Reproduced on my `Win 11 x64` machine as well running `1.33.72 Chromium: 96.0.4664.35`. Checked the following:

* directly loading `brave://settings/importData` via the URL bar - **Reproduced**
* loading through the `Hamburger` -> `Bookmarks` -> `Import bookmarks and settings...` - **Reproduced**
* loading `brave://settings` directly in the URL and then selecting  `Import bookmarks and settings...` - **Couldn't reproduced**
*

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1288)

```
-  Verified the STR from the description

<details>
<summary>Case 1: NTP ->Import bookmarks</summary>


</details>

<details>
<summary>Case 2: Hamburger menu->BM->Import bookmarks and settings</summary>


</details>

<details>
<summary>Case 3: brave://settings->Import bookmarks and settings</summary>


</details>

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.32.103 Chromium: 96.0.4664.45 (Official Build) (x86_64)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 11.6.1 (Build 20G224)

<details>
<summary>Case 1:  NTP -> Import bookmarks</summary>
* Confirmed click on NTP -> `Import bookmarks...` opens up `brave://settings/importData` page with `Import bookmarks and settings` modal popup
* Confirmed bookmarks can be imported

example | example | example
---------|----------|---------
<img width="1792" alt="Screen Shot 2021-11-15 at 9 20 03 AM" src="https://user-images.githubusercontent.com/387249/141825862-070625a8-9a20-4c80-8595-a3b26f308643.png"> | <img width="1792" alt="Screen Shot 2021-11-15 at 9 20 07 AM" src="https://user-images.githubusercontent.com/387249/141825902-59dbbaf1-003b-4ecc-a285-87df518fc2cd.png"> | <img width="1792" alt="Screen Shot 2021-11-15 at 9 20 11 AM" src="https://user-images.githubusercontent.com/387249/141825904-17a88fb6-1d93-4d28-98c9-c268680b9f86.png">

</details>

<details>
<summary>Case 2: Hamburger menu -> Bookmarks -> `Import Bookmarks and Settings...</summary>
* Confirmed click on Hamburger menu -> BM -> `Import bookmarks and settings` opens up `brave://settings/importData` page with `Import bookmarks and settings` modal popup
* Confirmed bookmarks can be imported

example | example | example
---------|----------|---------
<img width="1634" alt="Screen Shot 2021-11-15 at 9 23 43 AM" src="https://user-images.githubusercontent.com/387249/141826379-700c1001-4d0f-400c-be9a-ac4f7a27dc4f.png"> | <img width="1312" alt="Screen Shot 2021-11-15 at 9 23 47 AM" src="https://user-images.githubusercontent.com/387249/141826389-ecd512c4-6066-4244-a8ab-d6f29c239287.png"> | <img width="1312" alt="Screen Shot 2021-11-15 at 9 23 49 AM" src="https://user-images.githubusercontent.com/387249/141826399-5b377973-92cb-49c1-9d68-2b92a31aeda8.png">

</details>
 
<details>
<summary>Case 3: brave://settings -> Import bookmarks and settings</summary>
* Confirmed click on `brave://settings` -> `Import bookmarks and settings` opens up `brave://settings/importData` page with `Import bookmarks and settings` modal popup
* Confirmed bookmarks can be imported

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2021-11-15 at 9 25 34 AM" src="https://user-images.githubusercontent.com/387249/141826641-8f8f55cf-3994-4b1a-bb71-763d61cd11ba.png"> | <img width="1312" alt="Screen Shot 2021-11-15 at 9 25 36 AM" src="https://user-images.githubusercontent.com/387249/141826645-eb4a3e76-74a0-4c47-8d61-5fd286618cff.png"> | <img width="1312" alt="Screen Shot 2021-11-15 at 9 25 39 AM" src="https://user-images.githubusercontent.com/387249/141826649-955bf5ae-a298-4ce3-94cc-e9ea014a25ba.png">

</details>

<details>
<summary>Case 4: Hamburger menu -> Bookmarks Manager -> Import bookmarks</summary>
* Confirmed click on Hamburger menu -> BM manager -> `Import bookmarks` opens up local directory popup modal to import the bookmarks from the local machine/directory
* Confirmed bookmarks can be imported

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2021-11-15 at 9 28 02 AM" src="https://user-images.githubusercontent.com/387249/141827012-95d636aa-aba4-438f-973f-f508841c5e66.png"> | <img width="1436" alt="Screen Shot 2021-11-15 at 9 28 19 AM" src="https://user-images.githubusercontent.com/387249/141827020-1e4e5059-784e-419d-8a96-ba82ce6c6cd0.png"> | <img width="1312" alt="Screen Shot 2021-11-15 at 9 28 24 AM" src="https://user-images.githubusercontent.com/387249/141827025-1d93f077-92af-4a6f-9732-237fb6073486.png">

</details>
