### ISSUE TITLE
One linking endpoint client abstraction for all custodians.

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#19361]
## Description 

`PostClaimBitflyer`, `PostClaimGemini` and `PostClaimUphold` pretty much do the same, therefore there should be only one linking endpoint client abstraction. Obviously, `GeneratePayload` would need to be abstracted away (because of Uphold's dummy transaction verification on the server side), but other than that, they're almost identical.

**Comment by Miyayes** [comment]
https://github.com/brave/brave-browser/issues/24542 behind this issue.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 12.6 (Build 21G115)
```

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.45.100
