### ISSUE TITLE
Notify Interaction Upon Initialized

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19362]
## Description 
The `beginWatchingForInteraction` method is being called in the `unlocked` event but needs to be passed into the `initialized` event instead for if the wallet is already unlocked the event will never start after revisiting the `Panel` or the `Page`

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10987>brave/brave-core#10987</a></li>
        </ul>
      </td>
   </tr>
</table>
