### ISSUE TITLE
can't change exit nodes/receive new IP in Tor window

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#19371]
## Description 

With `C96`, users won't be able to connect to a new exit node/get a new IP address. Doing a hard refresh or running through `Hamburger Menu` -> `New Tor connection for this site` doesn't work/change the IP address.

## Steps to Reproduce

   1. launch a build that has `C96` (used `1.32.97 Chromium: 96.0.4664.35` in this case)
   2. launch a Tor window
   3. visit https://check.torproject.org
   4. hard refresh (notice that the IP/exit node doesn't change)
   5. try changing the exit node via `Hamburger Menu` ->  `New Tor connection for this site` (nothing happens)

## Actual result:

Can't connect to a new exit node/get a new IP address in Tor windows.

## Expected result:

Users should be able to change exit nodes/get new IP addresses like they did in previous versions

## Reproduces how often: 

100% reproducible using the above STR

## Brave version (brave://version info)

```
Brave | 1.34.3 Chromium: 96.0.4664.35 (Official Build) nightly (64-bit)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | Windows 11 Version 21H2 (Build 22000.318)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (but it's in the current `1.32.x` RC)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @diracdeltas @brave/legacy_qa @mkarolin @rebron

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Windows 10 x64 - 1.32.97`

**Comment by stephendonner** [comment]
Looks like this is related to the SOCK5 auth rewrite in CR96; I see this in the logs:

`SESSION_GROUP=-4 ISO_FIELDS=SOCKS_USERNAME,SOCKS_PASSWORD,CLIENTADDR,SESSION_GROUP,NYM_EPOCH
STREAM: 44 NEW 0 check.torproject.org:443 SOURCE_ADDR=127.0.0.1:53762 PURPOSE=USER SOCKS_USERNAME="torproject.org" SOCKS_PASSWORD="F9F75CAE831DB4B19023DE00FA946539" CLIENT_PROTOCOL=SOCKS5 NYM_EPOCH=0 SESSION_GROUP=-4 ISO_FIELDS=SOCKS_USERNAME,SOCKS_PASSWORD,CLIENTADDR,SESSION_GROUP,NYM_EPOCH
STREAM: 44 SENTCONNECT 6 check.torproject.org:443 SOCKS_USERNAME="torproject.org" SOCKS_PASSWORD="F9F75CAE831DB4B19023DE00FA946539" CLIENT_PROTOCOL=SOCKS5 NYM_EPOCH=0 
`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build:

```
Brave | 1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 11 Version 21H2 (Build 22000.318)
```

* verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/19371#issue-1050605271
* ensured that `Tor` initializes and connects once opened without any issues

<details>
<summary>Connecting to Tor - Logs</summary>

```
Nov 15 11:59:18.986 [notice] Tor 0.4.5.11 running on Windows 8 [or later] with Libevent 2.1.11-stable, OpenSSL 1.1.1l, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Nov 15 11:59:18.986 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Nov 15 11:59:18.987 [notice] Configuration file "C:\nonexistent" not present, using reasonable defaults.
Nov 15 11:59:18.987 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\96.1.32.103\<default>. Is this what you wanted?
Nov 15 11:59:18.987 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\96.1.32.103\<default>. Is this what you wanted?
Nov 15 11:59:18.988 [notice] Wow!  I detected that you have 32 CPUs. I will not autodetect any more than 16, though.  If you want to configure more, set NumCPUs in your torrc
Nov 15 11:59:18.989 [notice] Opening Socks listener on 127.0.0.1:0
Nov 15 11:59:18.989 [notice] Socks listener listening on port 55198.
Nov 15 11:59:18.989 [notice] Opened Socks listener connection (ready) on 127.0.0.1:55198
Nov 15 11:59:18.989 [notice] Opening Control listener on 127.0.0.1:0
Nov 15 11:59:18.989 [notice] Control listener listening on port 55199.
Nov 15 11:59:18.989 [notice] Opened Control listener connection (ready) on 127.0.0.1:55199
[43272:31708:1115/115918.990:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[43272:31708:1115/115918.990:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[43272:31708:1115/115918.991:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[43272:31708:1115/115918.992:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[43272:31708:1115/115918.992:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
Nov 15 11:59:19.000 [notice] Bootstrapped 0% (starting): Starting
Nov 15 11:59:19.000 [notice] Starting with guard context "default"
Nov 15 11:59:19.000 [notice] New control connection opened from 127.0.0.1.
Nov 15 11:59:19.000 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\96.1.32.103\<default>. Is this what you wanted?
Nov 15 11:59:19.000 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\96.1.32.103\<default>. Is this what you wanted?
Nov 15 11:59:19.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Nov 15 11:59:19.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Nov 15 11:59:19.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Nov 15 11:59:19.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Nov 15 11:59:19.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
Nov 15 11:59:19.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
Nov 15 11:59:19.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
Nov 15 11:59:21.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Nov 15 11:59:21.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
Nov 15 11:59:21.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
Nov 15 11:59:21.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Nov 15 11:59:21.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6145, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
Nov 15 11:59:22.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
Nov 15 11:59:22.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
Nov 15 11:59:23.000 [notice] Bootstrapped 57% (loading_descriptors): Loading relay descriptors
Nov 15 11:59:23.000 [notice] Bootstrapped 62% (loading_descriptors): Loading relay descriptors
Nov 15 11:59:23.000 [notice] Bootstrapped 72% (loading_descriptors): Loading relay descriptors
Nov 15 11:59:23.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Nov 15 11:59:24.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
Nov 15 11:59:24.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
Nov 15 11:59:24.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
Nov 15 11:59:24.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Nov 15 11:59:24.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Nov 15 11:59:24.000 [notice] Bootstrapped 100% (done): Done
```
</details>

* ensure that you can change the current exit node/IP address via `CTRL` + `SHIFT` + `R`
* ensure that you can change the current exit node/IP address via `Hamburger Menu` -> `New Tor connection for this site...`
* ensure that https://check.torproject.org correctly displays that you're connected to the `Tor` network
* ensure that loading https://brave.com & https://duckduckgo.com within Tor works without any issues
* ensure that loading `https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion` within `Tor` works
* ensure that loading `https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion` within `Tor` works
* ensure that visiting `https://www.nytimes.com`, `https://brave.com` & `https://account.protonmail.com/login` displays the `Open in Tor` button in the URL bar when loading in a `Normal` window
* ensure that clicking on `Open in Tor` works as expected (opening the website within `Tor`)
