### ISSUE TITLE
Ensure fast gas fees for swap transactions

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#19372]
Swap transactions may undergo slippage or failure during contract execution if it stays too long in the mempool. We therefore need to make sure:
1. default fee suggested in Swap transactions is the fastest setting.
2. if fast and average fees are the same, bump the miner tip and max fee (fast) by 1 GWei, for extra confidence.

**Comment by onyb** [comment]
**Test plan:** just perform some swaps and check if the fees are okay (should be fastest by default).

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-browser/issues/19372#issuecomment-966164929>#19372 (comment)</a></li>
         <li>Verified swap gas fee is always set to the highest value</li>
         <li>Verified swap gas fee always takes the high value even if the suggested fee is set to high and is lower</li>
        </ul>
      </td>
   </tr>
</table>
