### ISSUE TITLE
Can't watch SlingTV

### ISSUE THREAD

**Issue by echosa** [brave/brave-browser#1937]
## Description 
I'm unable to watch anything on SlingTV in Brave (neither live TV nor video on demand). When I try to watch something, I get `Authorization error occurred. Please try again later. (8-12)`. This does not happen in Chrome.

I disabled shields, but that did not fix it.

## Steps to Reproduce
   1. Go to https://www.sling.com
   2. Login
   3. If you are not automatically redirected there, go to https://watch.sling.com
   4. Try to watch a show

## Actual result:
`Authorization error occurred. Please try again later. (8-12)`

## Expected result:
The show should play.

## Reproduces how often: 
100%

## Brave version (brave://version info)
```
Brave | 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X
```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
widevine related issue? regional issue also?

**Comment by echosa** [comment]
Seems to be working now, at least with shields down.
