### ISSUE TITLE
Typo on error message 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19378]
## Description 

Typo on error message 

## Steps to Reproduce

   1. Select Send tab and enter a contract address
   2. Error message shown reads `tokens contract address` instead of `token's contract address`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/141298062-53435bc0-9594-44db-af34-c04a51d57566.png)

## Expected result:
`token's contract address`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.33.72 Chromium: 96.0.4664.35 (Official Build) nightly (64-bit)
-- | --
Revision | `8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel 
Follow up to https://github.com/brave/brave-core/pull/10933

**Comment by kjozwiak** [comment]
Reverted back into `1.33.x` via https://github.com/brave/brave-core/pull/11182.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Widget
      </td>
      <td><img width=600 src=https://user-images.githubusercontent.com/17010094/143426116-aa05fdaa-f16f-4bdc-9a91-3e76c09bf3b5.png>
      </td>
      <td><img width=600 src=https://user-images.githubusercontent.com/17010094/143425481-d462095f-a8ec-4c7a-9a42-f6f186937c92.png>
      </td>
      <td><img width=600 src=https://user-images.githubusercontent.com/17010094/143424583-f7fc97fb-efcc-496e-9c23-92af825b08bc.png>
      </td>
   </tr>
   <tr>
      <td>Panel
      </td>
      <td><img width=600 src=https://user-images.githubusercontent.com/17010094/143426141-fe515755-d7c6-4f9d-8161-562a3ac3aab1.png>
      </td>
      <td><img width=600 src=https://user-images.githubusercontent.com/17010094/143425600-1a1d794e-dc86-4208-a0e3-d8d075971fa6.png>
      </td>
      <td><img width=600 src=https://user-images.githubusercontent.com/17010094/143425715-ed7c2b56-91b9-4db7-9ada-a972c4b2835e.png>
      </td>
   </tr>
</table>
