### ISSUE TITLE
Show asset balance per account

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#19388]
We need to show an asset balance for each account when click on it from portfolio screen. Check how it shows on desktop
![Screenshot_20211111-144654_Brave - Debug (1)](https://user-images.githubusercontent.com/12011303/141359084-05093446-1fd6-44dd-8b5c-bd054d03c2ab.jpg)
:

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33.100
- Verified asset balance is shown for individual accounts

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/145034233-e390a69f-7a09-4948-aa7f-c17a46f3786b.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145034933-d41c20b8-7ac5-4884-8abd-3dbcc01c59d4.png>
