### ISSUE TITLE
Cannot scan the QR code after tapping outside of the sync warning modal

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#19389]
Found when testing https://github.com/brave/internal/issues/824#issuecomment-961497974

## Steps to Reproduce

Details in https://github.com/brave/internal/issues/825

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave v1.33.65 on Samsung Galaxy Tab S5e (Android 10.0)
Brave v1.33.65 on Samsung s7 (Android 8.0).

cc @brave/legacy_qa @AlexeyBarabash @jsecretan @rebron

**Comment by kjozwiak** [comment]
Closing as this was uplifted into `1.32.x` via https://github.com/brave/brave-core/pull/10986 and verifications on Nightly were completed via https://github.com/brave/brave-core/pull/10931#issuecomment-966272879.

**Comment by btlechowski** [comment]
Verification passed on Brave v1.32.103  on Samsung Galaxy Tab S5e (Android 10.0)

Verification in https://github.com/brave/internal/issues/825#issuecomment-969267749
