### ISSUE TITLE
Refactor wallet provider to share most codes between desktop and android

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19393]
We have separate wallet_provider_delegate_impl for desktop and android at the moment, and most codes in desktop's impl can be shared with android, this issue is to share them and only use separate implementation for UI specific calls which are platform-dependent.

**Comment by yrliou** [comment]
Test plan specified in the PR.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.34.78 Chromium: 97.0.4692.56 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11241>brave/brave-core#11241</a></li>
         <li>Verified able to perform a send transaction without errors</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/148196705-072fc0e5-97f3-446b-86e9-bfa64d4ddf07.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/148197378-399a8395-ee9c-4104-8d6e-fd8d07a137ef.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/148195771-7aeaea2e-09ea-4fe0-b04d-878c35955692.png>
      </td>
   </tr>
</table>
