### ISSUE TITLE
Support EIP-1155: Multi Token Standard

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19394]
Spec: https://eips.ethereum.org/EIPS/eip-1155
- [x] balanceOf and safeTransferFrom https://github.com/brave/brave-browser/issues/23164
- [x] metadata support https://github.com/brave/brave-browser/issues/22745

**Comment by nvonpentz** [comment]
Additional work to support ERC1155 such as safeBatchTransferFrom and balanceOfBatch, will be tracked and in a new issue.
