### ISSUE TITLE
Display 0x Privacy Policy in Brave Wallet Swap Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19392]
## Description 
Display 0x Privacy Policy in the Brave Wallet `Swap` panel

![Screen Shot 2021-11-12 at 12 38 27 PM](https://user-images.githubusercontent.com/40611140/141544901-1cfefd25-ad76-484a-aeb2-0f09f9ab97bd.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/11069>brave/brave-core#11069</a></li>
         <li>Verified 0x Privacy policy is shown for Swap feature on both wallet page and widget</a></li>
         <li>Verified hover over info icon shows the privacy policy in a tooltip window</a></li>
         <li>Verified 0x is hyperlinked to <code>https://0x.org/</code></a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Wallet Panel
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141719328-cac22fff-247e-43a4-b425-09983e1f760f.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141720489-e885e10d-fec7-438a-a6b0-7311e15939d5.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141717832-497763b1-ffc4-4c55-876e-da6417cb9f6b.png>
      </td>
   </tr>
   <tr>
      <td>Wallet Page
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141719293-9ff22aba-191e-44c1-9e68-b27333f8afe8.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141720455-f302c128-7c3a-41d4-85b1-e25098319eaa.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141717869-ca66219b-fc58-4e78-b880-f6c13ba38b4b.png>
      </td>
   </tr>
</table>
