### ISSUE TITLE
Update brave-core to work with newer NPM (fatal: repository 'undefined' does not exist)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#19398]
## Description 
Trying to use a newer (7 or later) version of NPM results in an error for folks when trying to run `npm run init`

For more info, please see:
- https://github.com/brave/brave-browser/issues/14639
- https://github.com/brave/brave-browser/issues/19272
- https://github.com/brave/brave-browser/issues/13631
- https://github.com/brave/brave-browser/pull/14089
- https://github.com/brave/brave-core/pull/11146

## Steps to Reproduce

   1. Have the current LTS version of node.js installed
   2. Verify npm is > 6 via `npm --version`
   3. Try to run `npm run init`

## Actual result:
`fatal: repository 'undefined' does not exist`

## Expected result:
It should work

**Comment by bsclifton** [comment]
cc: @mihaiplesa @bridiver

**Comment by saikatharryc** [comment]
```
export npm_config_projects_brave_core_tag=master
export npm_config_projects_brave_core_branch=master
export npm_config_projects_brave_core_repository_url=https://github.com/brave/brave-core.git
```
got me working this!
