### ISSUE TITLE
Bit of design issues

### ISSUE THREAD

**Issue by saymedgm** [brave/brave-browser#19397]
## Description 
This is exactly not an issue but the bookmarked websites earlier were shown don't the top only on the opening of new tab but now whenever I open any website I can see those bookmarks. These are a bit breach of privacy and it better earlier when I used to see those bookmarks only on the opening of new tab and it was better so I think it should be back.

## Actual result:
This is how it looks now
![image](https://user-images.githubusercontent.com/60937033/141413358-77d14f56-7310-4405-9dbe-7f703ed96a35.png)

## Expected result:
I want to see bookmarks on the opening of new tab only

**Comment by MartinEesmaa** [comment]
Umm, did you check settings?
brave://settings/?search=bookmark

Go to Appearance, please double check did you tick always shows bookmarks on new tab page?
![solutiontomanbrave123](https://user-images.githubusercontent.com/88035011/141414196-64fbd82b-f928-4240-942e-dacd1c2a17ad.png)

Reply me as soon as you can.
- MartinHero13

**Comment by saymedgm** [comment]
Thanks you @MartinEesmaa

**Comment by MartinEesmaa** [comment]
You're welcome @saymedgm, if you're happy, please close this issue or leave a comment with close issue.
- MartinHero13
