### ISSUE TITLE
Tooltip on wallet page is retained for unsupported networks. Similar to #19061

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19400]
## Description 

Tooltip on wallet page is retained for unsupported networks. Similar to #19061

## Steps to Reproduce

   1. Add a custom network
   2. Hover over Buy/Swap tabs on widget
   3. Tooltip is retained 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/141433983-0d5abd60-3796-40c3-a509-33696b960b56.png)

## Expected result:
Dismiss tooltip when mouse is moved away

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.99 Chromium: 96.0.4664.35 (Official Build) (x86_64)
-- | --
Revision | `8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, will be once released
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.34.68 Chromium: 97.0.4692.56 (Official Build) beta (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)
```

Reproduced the issue using 1.33.106 and STR.
Verified STR using 1.34.68 and confirmed tooltip does not remain when navigating away.

1.33.106 | 1.34.68 | 1.34.68
----- | ----- | -----
<img width="342" alt="1 33 x " src="https://user-images.githubusercontent.com/28145373/146991096-72f31cba-2077-4160-93bc-823c3c93d0e8.png"> | <img width="329" alt="1 34 x 1" src="https://user-images.githubusercontent.com/28145373/146991103-d9d20f40-82ec-4cad-95c3-d91e04a57fa8.png"> | <img width="324" alt="1 34 x 2" src="https://user-images.githubusercontent.com/28145373/146991113-09c5f309-1c1f-447a-ac96-8d483595bdf0.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified tooltip isn't retained for unsupported network on both page widget and on panel

Buy Widget | Sell Widget | Buy Panel | Sell Panel 
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/147939078-fff14300-287a-4a83-80d6-e0ac2aa82e8e.png) | ![image](https://user-images.githubusercontent.com/17010094/147939114-d27059f8-a62c-4650-be03-bd4234b63819.png) | ![image](https://user-images.githubusercontent.com/17010094/147939186-a03cb410-8931-463e-8046-1159271618b6.png) | ![image](https://user-images.githubusercontent.com/17010094/147939203-e0edaf5a-d45d-42cd-995a-b1505ea2a804.png)

-------------
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified tooltip isn't retained for unsupported network on both page widget and on panel

Buy Widget | Sell Widget | Buy Panel | Sell Panel 
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/147939977-3f343f31-dbf6-4cda-8e02-37e767fd75ce.png) | ![image](https://user-images.githubusercontent.com/17010094/147939994-d53ce9f9-cdee-46f7-9b23-47f922931e3b.png) | ![image](https://user-images.githubusercontent.com/17010094/147940010-d698a08b-30ee-4b8f-88ee-15352def5e8a.png) | ![image](https://user-images.githubusercontent.com/17010094/147940022-68c78198-eb95-4fa1-b8a7-c4752ea82b04.png)

-------------
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (x86_64 translated)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | macOS Version 12.1 (Build 21C52)

- Verified tooltip isn't retained for unsupported network on both page widget and on panel

Buy Widget | Sell Widget | Buy Panel | Sell Panel 
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/147940861-dd9e07f8-889d-4de9-99e3-723d43e9338b.png) | ![image](https://user-images.githubusercontent.com/17010094/147940881-0afc4f7c-b0dc-40db-abf5-0b834e429b28.png) | ![image](https://user-images.githubusercontent.com/17010094/147940650-c3ce8ef9-e1dd-4462-b6b3-263e281fdda9.png) | ![image](https://user-images.githubusercontent.com/17010094/147940617-f9c052cb-3715-4022-9404-68c47e2cd503.png)
