### ISSUE TITLE
Widevine prompt needs to be more obvious to the user

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#1940]
## Description 

When I try to view a video on Hulu e.g. Rick and Morty S2E1, the page won't load. Hulu shows me an error page with this text "Error playing this video. Sorry, we encountered an error playing this video. Please ensure your browser is supported. Error code: 3001"
Same problem on Netflix - gives me a "Missing Component" error"
Seems to affect all sites that need Widevine -  Amazon Video, BBC, Hulu, Netflix and Spotify

## Steps to Reproduce

   1. Log into Hulu.com or Netflix
   2. Select any video to watch
   3. Try to play the video

## Actual result:

<img width="1310" alt="screen shot 2018-10-31 at 1 39 46 pm" src="https://user-images.githubusercontent.com/2388823/47817309-84aed400-dd12-11e8-9803-a510586bfc58.png">
<img width="728" alt="screen shot 2018-11-05 at 2 19 45 pm" src="https://user-images.githubusercontent.com/2388823/48031053-d1761e80-e107-11e8-8e3e-b3286b1edfe9.png">

## Expected result:
Video should play

## Reproduces how often: 

Easily reproduced (always)

## Brave version (brave://version info)

Version 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No.
- Is the issue reproducible on the latest version of Chrome? 
No. It plays correctly in Chrome.

**Comment by rebron** [comment]
widevine related issue?

**Comment by karenkliu** [comment]
@rebron confirmed it's a widevine issue. I didn't notice it in the URL bar.
<img width="395" alt="screen shot 2018-11-05 at 11 40 15 am" src="https://user-images.githubusercontent.com/2388823/48022354-c8795300-e0ef-11e8-933a-7ce83a911655.png">

Why doesn't Widevine come pre-installed?

**Comment by bsclifton** [comment]
@karenkliu I think the disclaimer does a fair job explaining why it's not bundled by default - maybe we should make it more obvious?

**Comment by karenkliu** [comment]
@bradleyrichter  @bsclifton I don't think it's obvious at all to the user why Widevine doesn't come bundled with Brave. Why does Brave "discourage" it? Is there an impact to user privacy by enabling it? Why would there be "damages or losses" by using it? Damages to what? Loss of what?

The wikipedia page https://en.wikipedia.org/wiki/Widevine describing it just makes it seem like it's a benign thing to enforce licensing and make sure creators + the platforms get paid for the content.

It's a huge product problem if Brave users can't figure out how to make Amazon Video, BBC, Hulu, Netflix and Spotify work in Brave and don't understand why we're making it harder for them to stream from these huge content platforms.

@bbondy moving this discussion to Github from Slack so that it's tracked with an issue.

**Comment by bbondy** [comment]
Per Slack.  We discourage it because it's a closed source CDM and because we decided as a company not to promote DRM.

>  Is there an impact to user privacy by enabling it? 

Yes.

> Why would there be "damages or losses" by using it? Damages to what? Loss of what?

Yes, we don't know what it does, or if it does more than what it says. 

> It's a huge product problem if Brave users can't figure out how to make Amazon Video, BBC, Hulu, Netflix and Spotify work in Brave and don't understand why we're making it harder for them to stream from these huge content platforms.

Yep, so let's figure out a better UI for it, but we can't include it by default.  

@BrendanEich and @diracdeltas

**Comment by bbondy** [comment]
I think we could just open the flyout by default so that people would notice it better.

**Comment by diracdeltas** [comment]
I agree with @bbondy; this seems to be an issue of helping the user discover that the problem is widevine and install it smoothly as opposed to a problem of bundling widevine by default.

Once widevine is installed, they won't run into this issue in the future. (unlike Flash, widevine doesn't prompt anymore once it's installed)

**Comment by srirambv** [comment]
@bbondy we should have this dialogue come out when Widevine needs to be installed 
![image](https://user-images.githubusercontent.com/17010094/48028682-2753c200-e11a-11e8-8cac-ea83055df90d.png)

**Comment by kjozwiak** [comment]
Adding example of the current flow that was added into #1634 which I closed a duplicate as this one has more activity:

![netflixnotification](https://user-images.githubusercontent.com/2602313/47055618-46e47400-d186-11e8-8296-d30186452e8e.gif)

**Comment by karenkliu** [comment]
@rebron @tomlowenthal can we do something like this: 
![widevine permission notification](https://user-images.githubusercontent.com/2388823/48099050-3ba7c580-e1d3-11e8-90fe-7b9466252dcd.png)
UX:
Widevine is already installed but not running. The first time the user encounters a site that needs Widevine, prompt the user for permission to run it in an obvious way by showing this notification *in the page content area* so that the user is sure to notice it. 

- If the user clicks block, this permission notification will show everytime a site needs it to run.

- If the user clicks allow, this permission notification will never show again because Widevine will always run on sites that need it.

**Comment by srirambv** [comment]
+1 on the bubble notification. If user ignores this it can still be run from the URL slide notification.

**Comment by diracdeltas** [comment]
@karenkliu there is no need to prompt users to run widevine if it's already installed. the only case we would show a prompt is if widevine is needed but not installed. this matches the browser-laptop behavior. 

therefore the prompt should say 'install widevine' or something to make it clear that clicking the affirmative option will install new software.

**Comment by karenkliu** [comment]
@diracdeltas when @tomlowenthal looked at it with me he mentioned that the prompt makes it seem like it's not installed, but from the speed at which the page was able to play correctly after clicking install, he made the assumption that it was actually already installed in the browser and clicking install made it run instead of downloading new software and installing it. 

If that's not true then yes, of course we should change the prompt to "install widevine" instead of "run" and only show it when it's not already installed.

**Comment by diracdeltas** [comment]
@karenkliu the intended behavior is that widevine only prompts if it's not installed. if it's already installed and still prompting, we should remove those prompts. not sure about tom's assumption since i haven't verified it.

**Comment by eljuno** [comment]
+1 from Twitter: https://twitter.com/porteneuve/status/1075049456133906432?s=09

**Comment by angezanetti** [comment]
Is it possible to popup if not installed and then popup with `block`, `allow once`, `allow`?  I'm not sure I want to run Widevine everytime if I didn't explicitly  allow it to run

**Comment by bbondy** [comment]
@angezanetti we have no ability right now for a per run permission prompt.  I'm not opposed to the idea, please post another issue for that since this one is tracking just the ability for users to see an install prompt.

**Comment by rebron** [comment]
@mkarolin: 
To close on the implementation, we'll go with the following screen -> https://github.com/brave/brave-browser/issues/1940#issuecomment-436438375

Only change from that screen is we're going with "Install Widevine" instead of "Run Widevine"

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1772
also checked netflix.com

![image](https://user-images.githubusercontent.com/34715963/54333822-31378580-4624-11e9-8beb-36ee749308dc.png)
