### ISSUE TITLE
Balance, Transactions and graphs are not shown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19403]
## Description 

Balance, Transactions and graphs are not shown. More discussion [here](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1636699459390200)

## Actual result:
Balance, Transactions and graphs are not shown

## Expected result:
Balance, Transactions and graphs should be shown/listed

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/crypto-wallets

**Comment by bbondy** [comment]
Should be resolved now by Ben H. I posted some follow ups for better handling in case of errors.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified balance, transaction history and graphs are shown without any errors</li>
        </ul>
      </td>
   </tr>
</table>
