### ISSUE TITLE
We aren’t displaying asset balances until we get prices for them, we should

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19407]
When the asset ratio service was timing out and not returning values, we were not displaying token balances even though Infura was up and responding.

The front end code should still display token balances even if the USD balance can't be shown

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.33.98 Chromium: 96.0.4664.55 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11244>brave/brave-core#11244</a></li>
         <li>Verified balance is shown when price value fetch is delayed</li>
         <li>Verified balance and price calls are independent of each other</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/144411084-2cfe727e-eb20-44be-ae8f-5e7838805df4.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/144410999-b43f2753-8b03-4c0f-a087-c8cdc4b2b218.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/144410942-a95a6867-8379-420c-8613-90ba59d7798c.mov>
      </td>
   </tr>
</table>
