### ISSUE TITLE
Change CTA to buy on vpn panel

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#19406]
Change CTA to "Buy" for now on VPN panel

**Comment by LaurenWags** [comment]
@nullhook what would the QA Test plan be for this one? cc @rebron @brave/legacy_qa

**Comment by rebron** [comment]
Switching to QA/No. CTA to have "Buy" label vs having some arbitrary pricing that may have confused people who enabled the flag.

 Checked on the following build with brave://flags/#brave-vpn enabled. 
Brave | 1.35.30 Chromium: 97.0.4692.45 (Official Build) nightly (arm64)
-- | --
Revision | 513579c4234d36379b32e422772546e885cef641-refs/branch-heads/4692@{#802}
OS | macOS Version 12.1 (Build 21C5021h)


<img width="343" alt="Screen Shot 2021-12-14 at 9 30 07 AM" src="https://user-images.githubusercontent.com/5951041/146049574-b20c3858-b10d-4f15-9b96-22551dc443e0.png">
