### ISSUE TITLE
Don't treat unknown balances as 0, show N/A instead.

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19404]
When displaying any token balance, we should never assume a value of 0 if we can't obtain the value. 
0 is not a good default to display to users because it will scare them into thinking they've lost funds.

The only time we should display 0 is if a successful result tells us the value is 0.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.33.93 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>

   <tr>
      <td colspan=4>
         <ul>
         <li>Verified balance is not shown as 0 when its not yet fetched </li>
        </ul>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.98 x64 build
- Verified balance is not shown as 0 when balance is not fetched
----------
Verification passed on Samsung Tab A with Android 10 running 1.33.98 x64 build
- Verified balance is not shown as 0 when balance is not fetched
