### ISSUE TITLE
Microsoft has blocked third parties from changing the default `microsoft-edge` handler in Windows 11

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#19402]
The microsoft-edge: URI scheme that handles web links from within Windows 11 build 22494 microsoft-edge:// can no longer be overridden.
https://github.com/da2x/EdgeDeflector/issues/141

**Comment by bsclifton** [comment]
Per the release notes here:
https://blogs.windows.com/windows-insider/2021/11/12/releasing-windows-11-build-22000-346-to-beta-and-release-preview-channels/
![image](https://user-images.githubusercontent.com/4733304/141597957-45a595c4-e7a4-43c4-a706-65fd6081f5e7.png)

It seems devs at Microsoft considered this a bug. But if it's a bug, why would they have approved applications for sale on the Microsoft Store which offer this *exact same functionality*? 🤔 
![image](https://user-images.githubusercontent.com/4733304/141598188-a85ae3dd-1244-4a5e-8440-454e09255daf.png)
![image](https://user-images.githubusercontent.com/4733304/141598336-1079f54b-2801-4043-8cd6-ae1ba8f00161.png)

The paid option `Search Deflector` is open source and available here:
https://github.com/spikespaz/search-deflector

**Comment by bsclifton** [comment]
Closing as `wontfix`. Nothing we can really do here, unfortunately

**Comment by manikandancode** [comment]
Windows 11 build 22509 Dev channel comes with a new "Set default" option present in it the Default Apps settings default browser selection.
https://pbs.twimg.com/media/FFjtL0yVgAsDRo9?format=jpg&name=large
