### ISSUE TITLE
Always tries to connect to other accounts when trying to interact with Dapp

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19401]
## Description 

Always tries to connect to other accounts when trying to interact with Dapp

## Steps to Reproduce

   1. Add two accounts Acc1 and Acc2 to wallet
   2. Visit `https://rarible.com` and connect Acc2 to Dapp
   3. Lock wallet
   4. Update profile so it triggers sign message for connected account
   5. Panel opens, enter password to unlock
   6. Shows connect message for Acc1 before showing sign message

## Actual result:

https://user-images.githubusercontent.com/17010094/141443492-b7b97186-5788-4776-bd08-5d883e52c18c.mov

## Expected result:
Do not try to connect other accounts on each unlock 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.99 Chromium: 96.0.4664.35 (Official Build) (x86_64)
-- | --
Revision | `8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes once released
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @bbondy

**Comment by bbondy** [comment]
I'd guess this happens because the accounts are not given to `eth_accounts` when the wallet is locked. So there's probably another call to `eth_requestAccounts` or `ethereum.enable()`.  We could auto-reply with success after unlock perhaps.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified when two accounts are available, interacting with a Dapp doesn't trigger wallet connect before any message signing</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 height=800 src=https://user-images.githubusercontent.com/17010094/149352294-be9de5c5-cd17-4ebb-a97e-fc3d73452047.mp4>
      </td>
      <td><video width=1200 height=800 src=https://user-images.githubusercontent.com/17010094/149351730-133fe6ea-064d-42a4-9f8a-8b4bff981b1a.mov>
      </td>
      <td><video width=1200 height=800 src=https://user-images.githubusercontent.com/17010094/149351431-2ca3be04-8ecf-46c0-abf4-00a65a64331f.mov>
      </td>
   </tr>
</table>
