### ISSUE TITLE
Article timestamp differs in nightly and release

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19428]
## Description 

Article timestamp differs in nightly and release

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `https://www.indy100.com/news/subway-tuna-cattle-pork-chicken-b1956078`
   4. enable Speedreader mode
   5. look at the article's timestamp

## Actual result:

<img width="1312" alt="Screen Shot 2021-11-13 at 1 37 50 AM" src="https://user-images.githubusercontent.com/387249/141614004-3d36bc83-f6ce-42a6-a9f4-f8a2ab2e5dea.png">

## Expected result:
Perhaps the timestamp when viewed in `release`?

<img width="1312" alt="Screen Shot 2021-11-13 at 1 37 55 AM" src="https://user-images.githubusercontent.com/387249/141614026-e382a7e3-5118-4e5b-8296-acebdc7f632f.png">

## Reproduces how often: 

100% on this site

## Brave version (brave://version info)

Brave | 1.34.10 Chromium: 96.0.4664.45 (Official Build) nightly (arm64)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 11.6 (Build 20G165)

/cc @rillian

**Comment by stephendonner** [comment]
Or is this actually _not_ a bug, since showing 12-hour time might be preferred to 24-hour timestamps?  When I posted this in Slack, I said `nightly vs. prod` (in that order), but the screenshots shown were presented in reverse order, so couldn't been misleading.

**Comment by Tonev** [comment]
@stephendonner 

If the idea is to use 24-hour clock, there shouldn't be `AM` and `PM`, so even if that is the intention, there is still room for improvement so your issue is still a valid one for me :+1:

**Comment by rillian** [comment]
Ok, thanks for filing the issue. Having checked the code against the screenshots more carefully, I think this is not in fact a bug. brave/brave-core#10965 switched from a 24- to 12-hour clock representation, but if we're posting am/pm, that's more appropriate.

It is a bug that this format is hard-coded instead of using the current locale, but that's not a regression, so I don't consider it urgent. I filed #19452 to follow up.
