### ISSUE TITLE
update IPFS dialog for page info version 2

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#19421]
## Description 

Update design for ipfs dialog to support page info version 2 currently viewable brave://flags/#page-info-version-2-desktop in 1.31.x but will be on by default in 1.34.x and Chromium 97.

## Current result:

![pagebubblev1vsv2](https://user-images.githubusercontent.com/5951041/141532338-a3dc31bd-3126-4be0-9ce0-2acd7d2182d7.png)

## Expected result:
[Design placeholder]

## Reproduces how often: 

Enable flag. brave://flags/#page-info-version-2-desktop
Visit IPFS page e.g. ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html
Select IPFS icon in the url bar and open page info dialog.

## Brave version (brave://version info)

1.31.x and higher with flag enabled.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes w/ flag enabled
- Can you reproduce this issue with the beta channel? yes w/ flag enabled
- Can you reproduce this issue with the nightly channel? yes w/ flag enabled

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Follow-up to https://github.com/brave/brave-browser/issues/16907

**Comment by spylogsster** [comment]
temporarily fixed it as https://github.com/brave/brave-core/pull/11167 in cr98 branch

**Comment by MadhaviSeelam** [comment]
Verified `PASSED` using

Brave |	1.37.80 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
---|--
Revision | 	d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | 	Windows 11 Version 21H2 (Build 22000.493)

- Visit IPFS page with
   - ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html
   - ipns://ipfs.io/
- Select IPFS icon in the url bar and open page info dialog.
- Verified HTTPs pages as well.

`IPFS` scheme
1|2|3|4
---|----|----|----
<img width="750" alt="Screenshot 2022-03-03 123743" src ="https://user-images.githubusercontent.com/98358127/156661530-60612d50-39ae-484e-854e-75c37ad997db.png"> | <img width="750" alt="Screenshot 2022-03-03 123847" src="https://user-images.githubusercontent.com/98358127/156661600-ae7f02e9-07dc-408d-89ae-f10a7e38b523.png"> |  <img width="750" alt="Screenshot 2022-03-03 150531" src ="https://user-images.githubusercontent.com/98358127/156664449-9dec99b1-6658-4e36-b95c-6b912e201d9e.png">  | <img width="750" alt="Screenshot 2022-03-03 150617" src="https://user-images.githubusercontent.com/98358127/156661732-cb28afb5-6c6d-4e9b-b299-a3d0769d0e76.png">

`HTTPS` scheme
1|2|3|4
---|---|---|---
<img width="750" alt="Screenshot 2022-03-03 123923" src="https://user-images.githubusercontent.com/98358127/156666422-bb2cdce2-97f3-44b5-b62b-e9c2561824b4.png"> | <img width="750" alt="Screenshot 2022-03-03 123959" src="https://user-images.githubusercontent.com/98358127/156666485-849facbe-4dc4-4873-8722-81b23eb1e480.png"> | <img width = "750" alt= "Screenshot 2022-03-03 150342" src="https://user-images.githubusercontent.com/98358127/156666047-bd837118-f4da-4dbf-8e97-814213512723.png"> | <img width="750" alt="Screenshot 2022-03-03 150132" src="https://user-images.githubusercontent.com/98358127/156664818-2e50abb2-5160-47cc-89f3-78fd260b7d0b.png">

**Comment by stephendonner** [comment]
Adding `QA-Pass-Win64`; thanks for verifying on Windows, @MadhaviSeelam !
