### ISSUE TITLE
Add Brave services key for bat ratio server usage

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19425]
We use it for gas estimations and CG price data.

After a bunch of versions we'll start enforcing that the key needs to be present to use the service.

# Test plan

Use Brave and Fiddler or a similar HTTP traffic analyzer. 
Look at the HTTP requests that look like these:
https://ratios.rewards.brave.com/v2/relative/provider/coingecko/eth/usd/1d
https://ratios.rewards.brave.com/v2/etherscan/passthrough?module=gastracker&action=gasoracle

And make sure an http request header for `x-brave-key` exists with a value.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.98 Chromium: 98.0.4758.72 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified header <code>x-brave-key</code> value is passed in the http request</li>
         <img src=https://user-images.githubusercontent.com/17010094/151962675-2ff88c6f-2798-4aa1-b4ea-3d928ad41411.png>
        </ul>
      </td>
   </tr>
</table>
