### ISSUE TITLE
Add Price data powered by CoinGecko

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19432]
## Description 
Add `Price data powered by CoinGecko` in the footer of the `Asset Details` screen.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified footer text <code>Price data powered by CoinGecko</code> is shown on asset details page</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141729840-477314b0-9d29-42dd-ad42-eb0b6fce689c.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141729637-72be7af3-fe46-4094-91d6-3c18635b77d1.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141726054-95b0afc3-7f11-4ca5-860d-5d5f74c52c71.png>
      </td>
   </tr>
</table>
