### ISSUE TITLE
Add auto tab-group rules to settings

### ISSUE THREAD

**Issue by noahlavelle** [brave/brave-browser#19433]
## Description 
Add a new field to settings where users can enter full / partial URLs and a tab group name to add them too. For example, I would add `github.com/brave/brave-browser/issues` to go into an Issues group automatically. A more complicated system could be used to match all `github.com` domains with a path pointing to `/issues`

**Comment by Kornelijus** [comment]
Was just looking up how to do this myself, found an extension [loilo/auto-group-tabs](https://github.com/loilo/auto-group-tabs) which does exactly this,
you can match any url with [Match patterns](https://developer.chrome.com/docs/extensions/mv3/match_patterns/). Not sure if it needs to be a built in feature, as most people don't group their tabs.

**Comment by noahlavelle** [comment]
Thanks! I was planning on writing one myself so this saves me the effort
