### ISSUE TITLE
Rendering errors

### ISSUE THREAD

**Issue by autocadder** [brave/brave-browser#19439]
## Description 

1. Fonts fail to render clearly
2. embedded videos flicker like a strobe light
3. previous tab appears to "burn through" current tab 

## Steps to Reproduce

   1. open the browser
   2. 
## Actual result:

![2021-11-14 11_10_15-Window](https://user-images.githubusercontent.com/81970875/141688928-538b7806-28e5-4755-844c-708ce2084e63.png)

https://user-images.githubusercontent.com/81970875/141689187-7c5260a3-8af5-4be3-ac32-c22d1887e462.mp4

## Reproduces how often: 

constantly

## Brave version (info found on brave://version)

multiple releases, including current 

<html>
<body>

Brave | 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? I don't use Chrome.

**Comment by srirambv** [comment]
Does disabling hardware acceleration fix the issue

**Comment by autocadder** [comment]
That did it. I forgot that hardware acceleration is an option in browsers. Thank you!
