### ISSUE TITLE
Unable to claim brave rewards, no event listeners on the Claim button.

### ISSUE THREAD

**Issue by zanderwar** [brave/brave-browser#19440]
## Description 

Brave is not allowing me to claim rewards, there is no console error, the "Claim" button simply does nothing and has no event listeners tied to it. I have previously claimed several with no issue. Sadly this occurs on the claim that is meant to put me over 15USD therefore I'd have been eligible to withdraw to a wallet.

## Steps to Reproduce

   1.  Click "Brave Rewards"
   2.  Click "Claim"
   3.  Nothing happens.

## Actual result:

Unable to claim
![image](https://user-images.githubusercontent.com/13566916/141702946-481d773b-2683-4353-aafe-ac825f718c8e.png)

## Expected result:
The claim challenge window should appear.

## Reproduces how often: 

Infinite

## Brave version (brave://version info)

1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
Windows 11 Version 21H2 (Build 22000.282)

## Version/Channel Information:

Brave is up to date
Version 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by zanderwar** [comment]
The button had appeared 2 days before the "Next payment date" that used to display here (was 8 Nov at the time)
![image](https://user-images.githubusercontent.com/13566916/141703128-82e0c3c8-f695-4db6-a13f-1a2762c2cde4.png)

**Comment by Miyayes** [comment]
Most likely you have your BAT / Brave Rewards icon hidden in brave://settings. Please make sure it's enabled, restart browser and try again. Thanks.

**Comment by Miyayes** [comment]
https://github.com/brave/brave-browser/issues/19211

**Comment by zanderwar** [comment]
Did this and got rounded down to exactly 1.000 BAT.. unlikely accurate.. but free nonetheless, and the button is working. Thanks

**Comment by Miyayes** [comment]
@zanderwar, good to know! Question: Did you disable the BAT icon/Brave Rewards icon yourself in the past? Or was it hidden automatically without your action? Thanks.

**Comment by zanderwar** [comment]
I had disabled it manually as it served no use for me in the address bar, it's a nice quality-of-life feature but usually if I want to see where my BAT is at, I'd wait until I open a new tab and see the Brave Rewards widget there instead.

**Comment by Miyayes** [comment]
Actual payouts can round because currently the smallest unit of BAT is 0.25 BAT. However, it normally rounds up if anything. In terms of getting less than what it says in estimated earnings, the difference should flip over to the estimated earnings of the following month, if there is any. cc: @jsecretan

**Comment by zanderwar** [comment]
> Actual payouts can round because currently the smallest unit of BAT is 0.25 BAT. However, it normally rounds up if anything. In terms of getting less than what it says in estimated earnings, the difference should flip over to the estimated earnings of the following month, if there is any. cc: @jsecretan @tmancey

Thanks, this would imply that the claim ripped me off by roughly 2BAT.  Oh well(?)

**Comment by tmancey** [comment]
@zanderwar I can jump on a screen-share to check if that helps? Thanks

**Comment by zanderwar** [comment]
If it helps you clarify the issue, sure, It's not a big deal to me, it's just 1BAT is impossible, given that I'm full-time work from home 50hours+ a week, and this is what the current month looks like, (and I've had 3 weeks off work and a newborn taking up most of my time)

![image](https://user-images.githubusercontent.com/13566916/143726906-a6b67011-04d1-4246-bb3c-670faadd1feb.png)

**Comment by tmancey** [comment]
@Miyayes do you think this could be related to the drain?
