### ISSUE TITLE
Insufficient funds message shown when Connect your ledger is cancelled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19444]
## Description 

Insufficient funds message shown when Connect your ledger is cancelled

## Steps to Reproduce

   1. Pair Ledger Nano with Wallet
   2. Disconnect Nano and initiate a send transaction from Ledger
   3. Click confirm to send transaction and wait for the Ledger connect popup to showup
   4. Connect your ledger back and click on cancel on the popup 
   5. Shows insufficient funds message 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/141778207-adc958c7-5fcd-41c5-9cfe-8e4349202514.png)

## Expected result:
No error for insufficient funds

## Reproduces how often: 

Intermittent, repro'd twice only

## Brave version (brave://version info)

Brave | 1.32.103 Chromium: 96.0.4664.45 (Official Build) (x86_64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 11.5.2 (Build 20G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @spylogsster

**Comment by onyb** [comment]
@srirambv I believe https://github.com/brave/brave-core/pull/11247 fixed this issue. Can you please check again if you're able to reproduce this bug?

**Comment by srirambv** [comment]
@onyb you are correct. this issue is fixed now. 

https://user-images.githubusercontent.com/17010094/144566332-596c6f5b-6e66-44fb-a527-25d8a4fc5336.mov
