### ISSUE TITLE
Limit the number of rejected transactions that is shown on transaction page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19441]
## Description 

Decide if we need to show rejected transactions in transaction history or not

@onyb **Update:** After some internal discussions, we decided to limit the number of rejected transactions. Additionally, the limits for rejected transactions could be lower than completed transactions, due to storage restrictions.

## Steps to Reproduce

   1. Initiate a transaction
   2. Reject the transaction via panel
   3. Open transactions and click on the view block explorer via the menu button, shows error message

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/141739268-ff1a0cf0-ae9b-43d9-887b-aa4dfe6c9389.png)

## Expected result:
TBA

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.103 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc; @jamesmudgett @bbondy

**Comment by josheleonard** [comment]
What criteria do we want to use for deciding if a rejected transaction should be displayed or hidden?
cc @jamesmudgett  @onyb

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.108 Chromium: 108.0.5359.71 (Official Build) beta (64-bit)
-- | --
Revision | `1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}`
OS | Linux

- Verified steps from [brave/brave-core#15544](https://github.com/brave/brave-core/pull/15544)
- Verified only submitted transactions are listed
- Verified none of the rejected transactions are shown 

https://user-images.githubusercontent.com/17010094/205713448-b455fee8-6f71-46db-b41d-2f287b29bef2.mp4

---------------------

Verification passed on 

Brave | 1.47.108 Chromium: 108.0.5359.71 (Official Build) beta (64-bit)
-- | --
Revision | `1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15544](https://github.com/brave/brave-core/pull/15544)
- Verified only submitted transactions are listed
- Verified none of the rejected transactions are shown 

https://user-images.githubusercontent.com/17010094/205715010-a23eabbf-a4bd-4232-a295-1fa0cf0e6976.mp4


---------------------

Verification passed on 

Brave | 1.47.108 Chromium: 108.0.5359.71 (Official Build) beta (arm64)
-- | --
Revision | `1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15544](https://github.com/brave/brave-core/pull/15544)
- Verified only submitted transactions are listed
- Verified none of the rejected transactions are shown 

https://user-images.githubusercontent.com/17010094/205716228-92eb55d2-a6ba-4561-8551-bae6881724f3.mov
