### ISSUE TITLE
Browser crash when trying to sign transactions via Trezor

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19443]
## Description 

Browser crash when trying to sign transactions via Trezor

## Steps to Reproduce

   1. Connect Trezor account
   2. Visit cryptokitties.co and connect to the site
   3. Try to sign message from site, browser crashes

## Actual result:

https://user-images.githubusercontent.com/17010094/141769952-110541b8-79f6-4d62-b328-a829ff548550.mov

## Expected result:
No crash just sign message

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.103 Chromium: 96.0.4664.45 (Official Build) (x86_64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 11.5.2 (Build 20G95) & Windows 11

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes when released
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy @spylogsster

**Comment by kjozwiak** [comment]
https://github.com/brave/brave-core/pull/11087 was uplifted into `1.33.x` & `1.32.x` so we can save time and get RC's building again. Issue will be closed once https://github.com/brave/brave-core/pull/11087 has been closed.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.104 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified no browser crash when trying to sign transaction</li>
         <li>Encountered #19482 & #19487</li>
        </ul>
      </td>
   </tr>
</table>
