### ISSUE TITLE
Prevent panel from dismissing while connecting hardware wallet

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#19450]
Always keep the panel open while the "Connect Hardware Wallet" screen is active.

Related to https://github.com/brave/brave-browser/issues/19445.

### Test plan

As soon as the following screen is displayed, dismissing it by clicking somewhere else should not be possible.

<img width="354" alt="Screenshot 2021-11-15 at 7 56 41 PM" src="https://user-images.githubusercontent.com/3684187/141798534-128f3d0d-fb41-4bfb-9aa8-c08a219bd7f0.png">

Please test with Ledger and Trezor devices, on Windows, Linux, and MacOS.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.104 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from issue description</li>
         <li>Verified Wallet panel is not dismissed when clicked anywhere outside</li>
         <li>Verified WebHID panel is not dismissed when clicked anywhere outside</li>
         <li>Verified when device is unlocked, device is auto-detected and initiates transactions approval request on the device</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/19481>#19481</a> & <a href=https://github.com/brave/brave-browser/issues/19482>#19482</a></li>
        </ul>
      </td>
   </tr>
</table>
