### ISSUE TITLE
Unable to import Ledger accounts

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19451]
![image](https://user-images.githubusercontent.com/2965009/141828800-cfb9bea4-cab6-4c40-99e5-0b9190d6d7dc.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.34.78 Chromium: 97.0.4692.56 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11099>brave/brave-core#11099</a></li>
         <li>Verified able to connect Ledger and import accounts successfully</li>
         <li>Verified no console errors while importing accounts</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/148074003-2366f5e5-ae36-4a6b-9232-80ce23ef72dc.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/148074034-0b3ef41b-fc4c-4469-989a-4a39b4c26c36.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/148073769-9cea7d81-fed9-499b-b08a-518d15f8f451.png>
      </td>
   </tr>
</table>
