### ISSUE TITLE
Custom ad notifications should be attached to the browser window

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#19464]
Custom ad notifications should be attached to the browser window (z-order)

**Comment by aseren** [comment]
I was able to attach notification popup to browser window by setting `parent` member of `views::Widget::InitParams` structure here: https://github.com/brave/brave-core/blob/master/browser/ui/views/brave_ads/ad_notification_popup_widget.cc#L26

Passing browser window handler to `AdNotificationPopupWidget::InitWidget` function will be done separately in this issue: https://github.com/brave/brave-browser/issues/17593. So change current issue to blocked until https://github.com/brave/brave-browser/issues/17593 will be resolved.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

Commandline used was:
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --brave-ads-staging --rewards=staging=true --variations-server-url=https://v --enable-features="CustomAdNotifications:should_attached_ad_notification_to_browser_window/true"
```

light, `attached` | light, `repositioned` | dark, `attached` | dark, `repositioned`
-----|-----|------|-------
<img width="1739" alt="Screen Shot 2022-04-12 at 12 48 11 PM" src="https://user-images.githubusercontent.com/387249/163046441-56768d4b-4806-4bd7-840b-4d55ece65880.png"> | <img width="1680" alt="Screen Shot 2022-04-12 at 12 48 28 PM" src="https://user-images.githubusercontent.com/387249/163046446-22bf7026-1f3a-4924-ab55-748ac7d5e33b.png"> | <img width="1680" alt="Screen Shot 2022-04-12 at 1 14 15 PM" src="https://user-images.githubusercontent.com/387249/163046608-92d9e501-a095-4660-ab78-d24fbc6787bc.png"> | <img width="1680" alt="Screen Shot 2022-04-12 at 1 14 32 PM" src="https://user-images.githubusercontent.com/387249/163046656-27c99423-fe3b-415c-bac0-2502ab57ce63.png">
