### ISSUE TITLE
Set Brave as a default browser w/o using system UI

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19466]
By calculating proper hash we can set w/o system UI on Windows.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.32.112 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 20H2 (Build 19042.1348)

Verified test plan from https://github.com/brave/brave-core/pull/11125

Test case 1:
![default1](https://user-images.githubusercontent.com/34715963/143256659-fc8666de-85d5-4bd0-aa2f-dba195db2fbd.png)|![default2](https://user-images.githubusercontent.com/34715963/143256688-3720be2d-9690-4a1f-905b-5ca6187387b7.png)
--|--

Test case 2:
![default2_1](https://user-images.githubusercontent.com/34715963/143256733-4f574d00-7b52-46cc-b1d3-00ed9d972ef1.png)|![default2_2](https://user-images.githubusercontent.com/34715963/143256743-8d6f6828-79d0-4115-b926-88af8ef89a7d.png)|![default2_3](https://user-images.githubusercontent.com/34715963/143256751-f9047d20-f4a1-4257-a149-13f927463a62.png)
--|--|--
