### ISSUE TITLE
bip32-ed25519 for deterministic account generation

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19462]
We will use `bip32-ed25519` for deterministic account generation.  
https://ieeexplore.ieee.org/document/7966967

The bip44 base path is `m/44'/501'`.  As with most Solana wallets we will derive wallets with `m/44'/501'/W'/0'`, where `W` is `wallet-1`.

Note that some Solana wallets have used m/44'/501'/W' in the past, so we may want to have that as an option later on, but not for the initial release.

**Comment by darkdh** [comment]
it should be [SLIP-0010](https://github.com/satoshilabs/slips/blob/master/slip-0010.md)
https://docs.solana.com/wallet-guide/paper-wallet#hierarchical-derivation
