### ISSUE TITLE
Change default position for custom Brave ad notifications on Windows

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#19463]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Ubuntu 18.04 LTS

Verified custom ads are shown in the bottom right corner, shifted to the left

![image](https://user-images.githubusercontent.com/34715963/146420937-f23b186e-9807-43ea-abfe-b9b1f80c507b.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using Windows 10:

Brave | 1.34.66 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Custom-ad notification | Native/system-ad notification
--------------------------|----------------------------------
![19463-custom-ads](https://user-images.githubusercontent.com/387249/146610271-e886cab8-691d-41b7-80e0-de78428d6442.png) | ![19463-native-ads](https://user-images.githubusercontent.com/387249/146610288-0dedfeb8-4af0-4062-8683-1d361eadb450.png)

**Comment by stephendonner** [comment]
Verified `PASSED` on 

Brave | 1.34.68 Chromium: 97.0.4692.56 (Official Build) beta (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)

Verified custom-ad position and notifications didn't regress on macOS.

<img width="1680" alt="Screen Shot 2021-12-21 at 1 36 52 PM" src="https://user-images.githubusercontent.com/387249/147001291-526f3570-dc97-4ff0-87fc-1b2fc5a9b026.png">
