### ISSUE TITLE
Remove crypto widgets from Desktop and Android

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19478]
This issue is to track removing the crypto widgets from the new tab page.
They should retire to the gallery for Desktop.

On Desktop this includes:  https://github.com/brave/brave-browser/issues/19708
- Binance
- Gemini
- FTX
- Crypto.com

On Android this includes:
- Binance

**Comment by deeppandya** [comment]
@bbondy issue for removing binance widget on andrioid : https://github.com/brave/brave-browser/issues/19546
this issue also includes changes from desktop so i thought of creating specific for android.

**Comment by deeppandya** [comment]
PR for android changes : https://github.com/brave/brave-core/pull/11148

**Comment by simonhong** [comment]
@bbondy I think we can close this as all PRs for desktop and android are merged?
Desktop: https://github.com/brave/brave-core/pull/11266
Android: https://github.com/brave/brave-core/pull/11148

**Comment by bbondy** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/19708
