### ISSUE TITLE
Return device error if exists

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19489]
Instead of "Received error from hardware device, probably you need to confirm the transaction on your device" return error from device if that is available

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11110>brave/brave-core#11110</a></li>
         <li>Verified console throws the following error when device is disconnected when the confirmation prompt is shown on device</li>
         <pre>
[45636:45636:0104/024629.021553:INFO:CONSOLE(4923)] "device disconnected during action", 
source: chrome://wallet-panel.top-chrome/brave_wallet_panel.bundle.js (4923)
</pre>
        </ul>
      </td>
   </tr>
</table>
