### ISSUE TITLE
Trezor transactions are auto-rejected 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19482]
## Description 

Trezor transactions are auto-rejected 

## Steps to Reproduce

Scenario 1: Device Disconnected

   1. Pair the Trezor device with wallet 
   2. Physically disconnect Trezor
   3. Initiate a transaction via Trezor account 
   4. Panel pops up to confirm transaction and shows the Connect Trezor message 
   5. Within few seconds transaction is auto-rejected even before device can be connected
   
Scenario 2: Device Connected

   1. Pair the Trezor device with wallet 
   2. Initiate a send transaction via widget on wallet page
   3. Wait for the panel popup to show confirm transaction
   4. Connect Trezor shows and then auto-rejects the transaction
   5. A second later Trezor confirm popup flashes and closes 

## Actual result:

Scenario 1:

https://user-images.githubusercontent.com/17010094/141926844-4b5be106-1535-4174-8cc4-bad1245d05b2.mov

Scenario 2:

https://user-images.githubusercontent.com/17010094/141939647-9969fdba-2be4-4a9c-8d73-e7f3e794e043.mov

## Expected result:
Wait for the device to approve the transaction

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.104 Chromium: 96.0.4664.45 (Official Build) (x86_64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes when released
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @spylogsster @bbondy

**Comment by kjozwiak** [comment]
Uplifted into `1.33.x` & `1.32.x` via https://github.com/brave/brave-core/pull/11112 & https://github.com/brave/brave-core/pull/11113. We'll close this off once it lands into `master` via https://github.com/brave/brave-core/pull/11111 unless the `1.32.x` RC build finishes before that. In that case, we'll close this off.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.104 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified transactions are not auto-rejected when device is connected or not connected</li>
         <li>Verified no connect Trezor message is shown on the panel</li>
        </ul>
      </td>
   </tr>
</table>
