### ISSUE TITLE
The warning modal is not dismissed after timeout on scanning QR code is reached #826

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#19483]
Please see https://github.com/brave/internal/issues/826 for STR/Verification information.

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/11040 was merged into `1.32.x`.

**Comment by btlechowski** [comment]
Verification passed on Brave v1.32.106  on Samsung Galaxy Tab S5e (Android 10.0)

Verification in https://github.com/brave/internal/issues/826#issuecomment-970439857
