### ISSUE TITLE
Pending `wallet` verifications/Release Notes from `1.32.x - Release #2`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#19484]
Current list of issues that have been fixed/resolved in [`1.32.x Release #2`](https://github.com/brave/brave-browser/milestone/250) but haven't been verified by QA and should be completed for `1.33.x`

* [ ] https://github.com/brave/brave-browser/issues/17100
* [ ] https://github.com/brave/brave-browser/issues/17638
* [ ] https://github.com/brave/brave-browser/issues/18256
* [ ] https://github.com/brave/brave-browser/issues/18852
* [ ] https://github.com/brave/brave-browser/issues/18867
* [ ] https://github.com/brave/brave-browser/issues/18889
* [ ] https://github.com/brave/brave-browser/issues/18967
* [ ] https://github.com/brave/brave-browser/issues/19011
* [ ] https://github.com/brave/brave-browser/issues/19013
* [ ]  https://github.com/brave/brave-browser/issues/19019

Current list of issues that were `release-notes/include` via `1.32.x Release #2` and should be added into the release notes for `1.33.x`:

* https://github.com/brave/brave-browser/issues/17100 - Shouldn't be included as Android never had the extension wallet

**Comment by srirambv** [comment]
Verified issues that are applicable for Android. Removed Android label on other issues where it is not applicable as part of MVP release
