### ISSUE TITLE
Trezor sign messages doesn't process

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19487]
## Description 

Trezor sign messages doesn't process

## Steps to Reproduce

   1. Connect Trezor to Cryptokitites.co
   2. Click sign message
   3. Confirm Sign on Trezor via panel popup, page continues to load perpetually with no response

## Actual result:

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1637042291449800

## Expected result:
Complete sign process

## Reproduces how often: 

easy

## Brave version (brave://version info)

Brave | 1.32.104 Chromium: 96.0.4664.45 (Official Build) (x86_64)
-- | --
Revision |` 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @spylogsster @bbondy

**Comment by spylogsster** [comment]
should be fixed in https://github.com/brave/brave-core/pull/11111

**Comment by kjozwiak** [comment]
Uplifted into `1.33.x` & `1.32.x` via https://github.com/brave/brave-core/pull/11112 & https://github.com/brave/brave-core/pull/11113. We'll close this off once it lands into `master` via https://github.com/brave/brave-core/pull/11111 unless the `1.32.x` RC build finishes before that. In that case, we'll close this off.

@srirambv if the above isn't fixed by https://github.com/brave/brave-core/pull/11111, please move this out and we can add it into a HF or another release.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified able to sign messages successfully</li>
         <li>Verified signed hash is returned properly</li>
        </ul>
      </td>
   </tr>
</table>
