### ISSUE TITLE
Missing translations for Wallet 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19494]
## Description 

New strings translations required for Wallet

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/141980916-df6ed754-35fe-45ca-b1f0-442e8b8f4c17.png)
0x and CoinGecko strings
![image](https://user-images.githubusercontent.com/17010094/141981144-0f6d0b07-e8d8-4b78-b6f9-1af2fcec98e0.png)

Trezor/Ledger Error messages

![image](https://user-images.githubusercontent.com/17010094/141981290-18a395d8-c142-44dc-a798-021f2676280e.png) | ![image](https://user-images.githubusercontent.com/17010094/141981363-a21ad980-c562-4997-9e93-9f763d9cf8f0.png)
-- | --

## Expected result:
Translated strings

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.104 Chromium: 96.0.4664.45 (Official Build) (64-Bit)
-- | --
Revision  | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes 
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:

cc: @rebron @mkarolin @jamesmudgett

**Comment by bbondy** [comment]
@Douglashdaniel could you confirm that these were just done after the string translation? If so then we just need to wait for the next string translation for this.

**Comment by Douglashdaniel** [comment]
Yes sir! All of these were added after the latest translation order.

**Comment by bbondy** [comment]
@mkarolin pls resolve after the next translation order. Thank you!
