### ISSUE TITLE
Make ConnectHW screen working on both Trezor/Ledger devices

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19495]
In release 1.32.x we disabled it for Trezor urgently because of the constant retries for signature actions, need to rework it to avoid redundant retries and keep retries working only when HID error appeared

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.33.98 Chromium: 96.0.4664.55 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified able to Sign transactions and messages by Ledger and Trezor</li>
         <li>Verified Ledger throws error when trying to connect without enabling Ethereum app</li>
         <li>Verified Trezor shows connect hardware screen</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/19858>#19858</a> & <a href=https://github.com/brave/brave-browser/issues/19873>#19873</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Trezor Disconnected
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/144442091-badd1815-fb65-4874-8f6d-5cd824d6d18e.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/144448795-995e4241-c6b0-4f29-a040-66f5cb48beb9.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/144443546-cdc5d92b-5ee4-4d18-8452-38ffaba4e77f.png>
      </td>
   </tr>
   <tr>
      <td>Trezor Connected
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/144441946-5bd6f7a5-a644-47f1-95ed-c53a1ab69275.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/144448755-40a028e2-1b70-447f-9540-5c9cc9e1c382.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/144443405-a4b9abad-43a8-42fc-8164-bcaf1eb1a912.png>
      </td>
   </tr>
</table>
