### ISSUE TITLE
Double click by Confirm/Sign buttons for Trezor transactions closes wallet panel

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19490]
## Description 

Fast first-time double click by the buttons to sign or confirm transactions closes wallet panel

## Steps to Reproduce

   1. Sign message or Transaction
   2. Do fast double click by the button first time

## Actual result:

Popup closed

## Expected result:

Transaction/Message signed

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.33.98 Chromium: 96.0.4664.55 (Official Build) (arm64)
-- | --
Revision | `38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified steps from issue description
- Verified panel doesn't auto-close unless manually closed
---------
Verification passed on 

Brave | 1.33.98 Chromium: 96.0.4664.55 (Official Build) (64-bit)
-- | --
Revision | `38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}`
OS | Linux

- Verified steps from issue description
- Verified panel doesn't auto-close unless manually closed
---------
Verification passed on 

Brave | 1.33.98 Chromium: 96.0.4664.55 (Official Build) (64-bit)
-- | --
Revision | `38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}`
OS | Windows 11 Version Dev (Build 22509.1000)

- Verified steps from issue description
- Verified panel doesn't auto-close unless manually closed
