### ISSUE TITLE
Missing hyperlinks for Brave rewards under Settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19496]
## Description 

`Brave Rewards are disabled` text and `Click here to learn more` link are not showing up as mentioned in #18158

## Steps to Reproduce

   1. Clean profile `1.33.80`
   2. Navigate to brave://settings/rewards
   3. Click on `Brave Rewards are disabled` text 
   4. Rewards onboarding modal popup is displayed
   5. `Brave Rewards are disabled` text and  `Click here to learn more` link should work/shown as mentioned in the description https://github.com/brave/brave-browser/issues/18158#issue-998481791
   

## Actual result:

- `Click here to learn more` is not showing up as a link
- `Brave Rewards are disabled` text and  `Click here to learn more` link are shown in two lines instead of a single line
![image](https://user-images.githubusercontent.com/38657976/141986747-227a82a7-6807-4e5b-8f3d-99af5e943842.png)

## Expected result:
- `Click here to learn more` should be displayed as a link
-  `Brave Rewards are disabled` text and  `Click here to learn more` link should be displayed in the single line
-  `Brave Rewards are disabled` text should not show as a clickable

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.33.80 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1348)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @Miyayes @emerick

**Comment by emerick** [comment]
@GeetaSarvadnya I think the idea there is that clicking to "learn more" pops up the Rewards panel which explains how Rewards works, etc. I don't think it's meant to be its own separate link, but cc: @Miyayes in case I have that wrong.

**Comment by Miyayes** [comment]
Yes, I remember from @jamesmudgett that it's supposed to pop open the Rewards dropdown panel.

**Comment by Miyayes** [comment]
Ryan McFadden suggests using: `"Open Rewards panel to enable and get started`. Avoiding "Click" language for accessibility reasons. cc: @rebron

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.33.94 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H2 (Build 19044.1387)

```
* ensured that the new text under `brave://settings/rewards` matches https://github.com/brave/brave-browser/issues/19496#issuecomment-971959638
* ensured that clicking on the button always opens the rewards panel without any issues
* ensured that once rewards has been enabled, the button is removed and the rewards settings are visible

**`Text Change`** | **`Opening rewards panel`** | **`Rewards Enabled`**
-------------------|---------------------------------|-------------------------
