### ISSUE TITLE
Disable sign in to Chrome

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#195]
The ability is described in this Chrome admin policy:
https://www.chromium.org/administrators/policy-list-3#SigninAllowed

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified `Sign in to Chrome` doesn't show up anywhere
