### ISSUE TITLE
Sort hardware wallet addresses by index order vs alphabetically by address

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#19507]
![Screen Shot 2021-11-16 at 12 39 36 PM](https://user-images.githubusercontent.com/318119/142037723-fd09ae59-f2d9-4a89-a390-6b478cadd46e.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.93 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11684>brave/brave-core#11684</a></li>
         <li>Verified new naming convention is used for both new and legacy wallets addresses</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>New HW account naming
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/151400933-59476b2e-e354-406a-973c-ac0906472005.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151399538-1020603e-4d87-4948-9401-addf35ee662e.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151399082-d068ceb1-3480-4bbc-9236-2d3e6a098928.png>
      </td>
   </tr>
   <tr>
      <td>Legacy index 3 account is preselected
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/151400977-2b7001f1-6439-48c3-9a58-95d40c89128e.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151399620-88ec10cc-54e4-402d-bdf2-5f52a954da11.png>
      </td>
      <td><img width=900 src="https://user-images.githubusercontent.com/17010094/151399141-ec4aa2e7-eba6-447c-b4a2-d3f9d5acdf1d.png">
      </td>
   </tr>
</table>
