### ISSUE TITLE
Sign using Trezor fails on Cryptokitties.co

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19504]
## Description 

Sign using Trezor fails on Cryptokitties.co

## Steps to Reproduce

   1. Connect Trezor 
   2. Visit cryptokitties.co and try to sign mesage via trezor wallet
   3. Sign message popup goes into loop 

## Actual result:

Sign using Trezor fails on Cryptokitties.co

## Expected result:
Should be able to sign message using Trezor wallet

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes when released
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @spylogsster

**Comment by spylogsster** [comment]
@srirambv can you try to remove all cookies for https://www.cryptokitties.co/ and sign message again. seems working for me

**Comment by srirambv** [comment]
Issue still reproducible on 1.34.40 on a clean profile

**Comment by abjugard** [comment]
Something similar happens using Loopring, perhaps related? Should I open a different issue or is it the same issue?
![image](https://user-images.githubusercontent.com/287697/145879833-be924bd1-0c19-4405-a4b0-8f2f32b454db.png)

**Comment by srirambv** [comment]
Seems to be an issue on 1.35.89 as well. Shared recording with @spylogsster

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.35.98 Chromium: 98.0.4758.74 (Official Build) (arm64)
-- | --
Revision | `d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}`
OS | macOS Version 12.1 (Build 21C52)

- Verified steps from issue description
- Verified able to sign message and login successfully using a Trezor wallet
-------
Verification passed on 

Brave | 1.35.98 Chromium: 98.0.4758.74 (Official Build) (64-bit)
-- | --
Revision | `d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}`
OS | Windows 11 Version Dev (Build 22543.1000)

- Verified steps from issue description
- Verified able to sign message and login successfully using a Trezor wallet
-------
Verification passed on 

Brave | 1.35.98 Chromium: 98.0.4758.74 (Official Build) (64-bit)
-- | --
Revision | `d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}`
OS | Linux

- Verified steps from issue description
- Verified able to sign message and login successfully using a Trezor wallet
