### ISSUE TITLE
Make it easier to hide the Wallet icon in the Brave toolbar

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19514]
Users can hide the Brave Wallet icon in brave://settings/wallet

But it's hard to discover that if you don't know. 
It would be better to be able to right click on the icon and have a Hide option there in a menu.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.106 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed able to context-click and select `Hide Brave Wallet icon on toolbar` to remove the icon
Confirmed pref state is reflected in icon-visibility state, and vice-versa
Confirmed `Show Brave Wallet icon on toolbar` pref correctly sets and shows/hides the icon

example | example | example | example
---------|---------|----------|---------
<img width="1527" alt="Screen Shot 2022-03-27 at 5 32 02 PM" src="https://user-images.githubusercontent.com/387249/160308374-f20885cb-2787-4473-a8a1-d8dbeb8cf5bd.png"> | <img width="1312" alt="Screen Shot 2022-03-27 at 5 32 06 PM" src="https://user-images.githubusercontent.com/387249/160308378-76ff9840-95b6-4afa-8eee-7e054151a6a7.png"> | <img width="1312" alt="Screen Shot 2022-03-27 at 5 32 14 PM" src="https://user-images.githubusercontent.com/387249/160308379-0c8c0a5d-b46e-444e-a701-0520807fedf6.png"> | <img width="1312" alt="Screen Shot 2022-03-27 at 5 32 18 PM" src="https://user-images.githubusercontent.com/387249/160308381-e5178b69-1724-43cc-9992-b0d3a945ac37.png">

**Comment by amdiv** [comment]
Finally! Thank you [stephendonner](https://github.com/stephendonner)!
