### ISSUE TITLE
Unexpected update, lost Wallet imported account

### ISSUE THREAD

**Issue by VictorMGoulart** [brave/brave-browser#19516]
## Description 
My Brave Wallet updated few minutes ago, NO advises, I logged in as usual, but my imported account wasn't there. I don't have my secret to import it again, for security reasons I only copy paste when needed.

## Steps to Reproduce
There is no steps, I just opened my browser and it was updated, when I opened my wallet it said I should login and I did it.

## Actual result:
There is 3 accounts, but the imported one, no.

## Expected result:
I wasn't even expecting LOL

## Brave version (brave://version info)
Brave | 1.32.106 Chromium: 96.0.4664.45 (Versão oficial) 64 bits
Revisão | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
SO | Windows 10 Version 21H1 (Build 19043.1288)

![image](https://user-images.githubusercontent.com/37090146/142080147-29692fd0-1cf3-4f50-888c-30770ca1d6f1.png)

**Comment by VictorMGoulart** [comment]
For those who face the same problem, I just went into Settings > Wallet > Default Cryptocurrency Wallet and returned to the old version (you must restart the browser).

Logged in my wallet and got my secret and setted up my imported account on the new Brave Wallet.

![image](https://user-images.githubusercontent.com/37090146/142081251-d46fe6fa-9e05-43ae-88b5-5d8e122bab6f.png)

**Comment by bbondy** [comment]
I highly recommend using the newer Brave Wallet instead and just going to the accounts tab and clicking on add account. Your account will show up with the balance.
