### ISSUE TITLE
Apple M1 Monterey Memory Leak

### ISSUE THREAD

**Issue by JohnAntoineG710** [brave/brave-browser#19511]
## Description 

On Macbook Air 2020 (M1) running macOS Monterey 12.0.1, Brave starts out with around 160MB of memory usage and climb non-stop to reach 2GB in two or three hours, reaching 14GB to 15GB in a couple of days, as reported by Brave's own task manager

## Steps to Reproduce

   1. Disable all extensions as well as hardware acceleration
   2. Completely quit Brave
   3. Open Brave and check memory usage (should be around 100MB-120MB)
   4. Use Brave as normal for a couple of hours
   5. Close all tabs and check the task manager again (memory usage of the main Brave process should be now around 1.8GB - 2GB)

## Actual result:

Memory usage continuously increases over time even if no tabs are open and all extensions are disabled.

## Expected result:
Memory usage stable, rises and falls according to open tabs, falls to the same stable figure when all tabs are closed.

## Reproduces how often: 

The buggy behavior is the default, I can't get the memory usage to stabilize no matter what I do

## Brave version (brave://version info)

Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (arm64)
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{\#947}
OS | macOS Version 12.0.1 (Build 21A559)
JavaScript | V8 9.6.180.12
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
  yes
- Can you reproduce this issue with the beta channel? 
  no attempt
- Can you reproduce this issue with the nightly channel? 
  no attempt

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
  Haven't tried, but the issue still happens with no tabs open
- Does the issue resolve itself when disabling Brave Rewards? 
  Brave rewards disabled, the issue still happens
- Is the issue reproducible on the latest version of Chrome? 
  I don't use chrome

## Miscellaneous Information:

I searched for the issue, found some similar threads on the community from a year to two years ago, with no apparent answers or solutions. I tried to create an account in the community but the verification e-mail never arrived.

**Comment by FirasSoltani** [comment]
I can report that I'm suffering the same issue with usage reaching 25gb at times

**Comment by philsimon** [comment]
Same issue here. Brave is inexplicably taking up 65GB of ram when I've got only 16 on my M1.

**Comment by culturerich** [comment]
Same issue on Monterey, but with an Intel, not M1.

**Comment by robertvanhoesel** [comment]
This may very well be the same [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1735345) that Mozilla Identified caused by changing the pointer color in _System Preferences > Accessibility_, which leaks memory [every time the cursor type changes](https://eclecticlight.co/2021/11/15/montereys-memory-leak-and-how-to-avoid-it/) (from i.e. the pointer hand to normal cursor to text selection) which obviously happens a lot in browsers.

**Comment by philsimon** [comment]
Thank you. I have disabled this feature for the time being.



Regards,

[horizontal bar]
Phil Simon| ***@***.*** | https://www.philsimon.com/
[cid:c3e2452b-c21f-40e1-b6a8-90d5b57c493c] "Action expresses priorities.” —Mahatma Gandhi


________________________________

**Comment by JohnAntoineG710** [comment]
> This may very well be the same [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1735345) that Mozilla Identified caused by changing the pointer color in _System Preferences > Accessibility_, which leaks memory [every time the cursor type changes](https://eclecticlight.co/2021/11/15/montereys-memory-leak-and-how-to-avoid-it/) (from i.e. the pointer hand to normal cursor to text selection) which obviously happens a lot in browsers.

It may very well be the case, and I do in fact have the cursor color in a non-standard configuration, but this wouldn't explain the fact that memory was leaking while the main browser window was open on the home tab, with no other tabs open and all extensions disabled, with a stationary mouse pointer/cursor, and I could see the memory rising linearly in the Brave task manager.

A necessary update: The issue seems to have gone away since the last two macOS updates without me changing anything with my workflow, but since we don't know the cause, we can't guarantee that it won't happen again
