### ISSUE TITLE
Blocked count overlaps with text when it goes beyond 3 digits

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1951]
## Description 

Blocked count overlaps with text when it goes beyond 3 digits

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/47871132-a88d1b00-dde1-11e8-9eee-bde1173b0ada.png)

## Expected result:
Blocked count shouldn't overlap on text

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on Beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @karenkliu @rebron @kjozwiak

**Comment by bsclifton** [comment]
Updated to be 0.58.x after DEPS was updated with https://github.com/brave/brave-core/pull/820

PR is tagged with uplift-request; let's make sure to modify milestone if that is approved 😄

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Mac OS X

* Verified Blocked Ads/Trackers is set to 99+ if value is over 99
![screen shot 2018-12-04 at 9 15 19 am](https://user-images.githubusercontent.com/28145373/49447766-599e2100-f7a5-11e8-8354-115e6cd7f60e.png)
