### ISSUE TITLE
changing the wallpaper of a new tab

### ISSUE THREAD

**Issue by netharuM** [brave/brave-browser#19525]
# changing the wallpaper of the brave new tab 

brave is a good browser with so many features 
but the main issue that annoys me is changing the wallpaper in brave 

even when i change my default home page to the default chrome one still i cant set a custom wallpaper to new tab in brave 

pls guys fix this issue 

thanks 😀😀

**Comment by rebron** [comment]
Closing as a dupe of https://github.com/brave/brave-browser/issues/15252
