### ISSUE TITLE
http://vger.kernel.org/: unreachable

### ISSUE THREAD

**Issue by harridu** [brave/brave-browser#19520]
## Description 
If I try to access http://vger.kernel.org/, then I end up with an error message
```
https://vger.kernel.org/vger-lists.html is unreachable.
ERR_ADDRESS_UNREACHABLE
```
First I didn't ask for https. Second, "ERR_ADDRESS_UNREACHABLE" is incorrect. The site is fine,as a broweser session with Firefox or Safari shows. It should be "ERR_PORT_UNREACHABLE".

## Steps to Reproduce
1. try to access http://vger.kernel.org/ in Brave

## Expected result:
The browser should do as I say. At least there should be some override button. A warning indicator saying "hey, this connection is not secured" is fine.

## Reproduces how often: 
I am not able to reproduce this with http://emportal.info/, for example. There is surely something fishy here.

## Brave version (brave://version info)
```
Version 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
Linux
```

**Comment by alimkoca** [comment]
I have the same problem too.

**Comment by kjozwiak** [comment]
@harridu @alimkoca does the website load for you in other browsers? I just tried it on Chrome & Edge and basically get the same results I'm getting in Brave. Seems like it's timing out as per:

```
ERR_CONNECTION_TIMED_OUT
```

Maybe the website was having issues and went down?

**`Edge`** | **`Chrome`**
-----------|----------------
![image](https://user-images.githubusercontent.com/2602313/149211584-da247d76-9f1b-4c0f-a7b1-a90e81ea1ece.png) | ![image](https://user-images.githubusercontent.com/2602313/149211748-c5013ab2-059a-4b7f-b4de-5061af97dff7.png)

**Comment by alimkoca** [comment]
No, Brave has some problems. I heard that from my friends and I tried.

**Comment by harridu** [comment]
Any news on this? I can still reproduce this problem using 
```
Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
```

**Comment by kjozwiak** [comment]
Hmmm looks like http://vger.kernel.org is loading fine on other browsers now. Maybe I ran into a network hiccup when I ran through https://github.com/brave/brave-browser/issues/19520#issuecomment-1011397688.

**Comment by alimkoca** [comment]
Did it get better?

**Comment by harridu** [comment]
No problem with
```
Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)
```

**Comment by alimkoca** [comment]
Okay, am I should update Brave?

**Comment by joshlreese** [comment]
I encountered this problem as well.

Version info:
```
Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (x86_64)
```

This appears to be due to the "Upgrade connections to HTTPS" option under advanced controls. Disabling the option allows me to browse to the non-https site, which is the only one that's available.

**Comment by harridu** [comment]
This problem still exists for 1.47.171
