### ISSUE TITLE
No back button on restore wallet screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19528]
## Description 
No back button on restore wallet screen

## Steps to reproduce 

   1. Enable Wallets via flag
   2. Click on Restore
   3. No back button to go back to onboarding screen. Have to use device back which closes the wallet page

## Actual result 
No back button on restore wallet screen

## Expected result
Back button on the restore page so user can go back and start fresh if they decide not to restore

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.33.82 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @jamesmudgett @SergeyZhukovsky

**Comment by bbondy** [comment]
What do you mean by: 
> Enable Wallets via flag

**Comment by srirambv** [comment]
Currently Crypto Wallet on Android is enabled via flag only unlike desktop

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.93 x64 Beta build
- Verified back button is visible on restore wallet screen
- Verified clicking on it goes back to onboarding screen
- Logged [#19810](https://github.com/brave/brave-browser/issues/19810)

Dark | Light 
-- | --
![image](https://user-images.githubusercontent.com/17010094/143913342-0f0b873d-35fa-4893-a822-d4039a3a9419.png) | ![image](https://user-images.githubusercontent.com/17010094/143913328-5df60f29-b2ef-4cb4-a1b5-93498a64160a.png)

-----------
Verification passed on Oppo Reno 5 with Android 11 running 1.33.93 x64 Beta build
- Verified back button is visible on restore wallet screen
- Verified clicking on it goes back to onboarding screen
- Logged [#19810](https://github.com/brave/brave-browser/issues/19810)

Dark | Light 
-- | --
![image](https://user-images.githubusercontent.com/17010094/143913293-fa4dab49-e2c1-4658-b59a-c9c911eb1a53.png) | ![image](https://user-images.githubusercontent.com/17010094/143913305-56c8c41e-62b4-45d2-ba2c-3fe3adfbe662.png)
