### ISSUE TITLE
Wallet - transfer of ERC-20 tokens rounded

### ISSUE THREAD

**Issue by krijnsent** [brave/brave-browser#19521]
## Description 
Using the new wallet I tried to move all ERC-20 tokens from one Ethereum wallet to another. My wallet had 0,012654 wBTC, but when transferring, the amount got rounded to 0,0127, which obviously fails... Entering the amount with more decimals is not possible, it keeps getting rounded (up). That happens too when I select "100%".

## Steps to Reproduce
   1. Try to transfer any amount with more than 4 decimals, the amount gets rounded. For ERC-20 tokens 18 decimals is somewhat standard...

## Expected result:
Being able to input at least 18 decimal places.

## Brave version (brave://version info)
v1.32.106

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11938>brave/brave-core#11938</a></li>
         <li>Verified full transaction value is shown and truncated</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/154916352-33e40e3c-c66d-4bd0-9b97-bb4ad9ebc0ca.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/154915978-92ffc34c-0245-4903-bae6-2df6497c16ce.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/154915763-3a20e839-2ebd-47e6-9a1e-e186f0b16699.png>
      </td>
   </tr>
</table>
