### ISSUE TITLE
Linked Address can't be found when trying to connect Trezor

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19523]
## Description 

Linked Address can't be found when trying to connect Trezor

## Steps to Reproduce

   1. Connect Trezor on device 1 (macOS Release - 1.32.106) and link an account
   2. Do some transactions with the wallet address
   3. Connect Trezor on device 2 (Linux nightly - 1.34.10) 
   4. Default address with the balance from step 2 isn't shown 
   5. Search for the actual address, doesn't list, keeps searching without any result

## Actual result:

Wallet address is not found

## Expected result:
Should list the address that has balance and allow to link with Brave Wallet account

## Reproduces how often: 

Easy on my device 

## Brave version (brave://version info)

Device 1:

Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 11.5.2 (Build 20G95)

Device 2: 
Brave | 1.34.10 Chromium: 96.0.4664.45 (Official Build) nightly (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}` 
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb

**Comment by onyb** [comment]
Need some more information to debug this, ideally a screen recording. Are you seeing the same address list in both devices when adding a Trezor account? Or is it just that the correct balance doesn't show up in the accounts list?

**Comment by srirambv** [comment]
This seems to be fixed. Can't repro any more. Going to close for now. Can reopen if I run into it again or someone else has the same issue
