### ISSUE TITLE
Remove Hardcoded URL in AllowSpend Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19534]
## Description 
The `AllowSpend` Panel has a hardcoded value of 'https://app.compound.finance' needs to be removed and passed the sites origin.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.32.111 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Linux

- Verified hardcoded URL is removed 
![image](https://user-images.githubusercontent.com/17010094/143039616-b7c5867f-a55c-4ab0-9e8e-9d675e4731ef.png)
- Encountered #19556

---------
Verification passed on 

Brave | 1.32.111 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Windows 11 Version 21H2 (Build 22000.318)

- Verified hardcoded URL is removed 
![image](https://user-images.githubusercontent.com/17010094/143041638-047e4960-db31-469e-a9eb-cbb458a44ec5.png)
- Encountered #19556

---------
Verification passed on 

Brave | 1.32.111 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)


- Verified hardcoded URL is removed 
![image](https://user-images.githubusercontent.com/17010094/143040893-083735ea-83b0-4c5f-9cf3-277c6d19a970.png)
- Encountered #19556
