### ISSUE TITLE
Show active transactions and token balances in the panel 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19533]
It'd be nice to see any active and recent transactions directly in the wallet panel. Users feel like they have to dig to get to them now in brave://wallet.

Users would also like to see asset balances easily in the panel.

**Comment by srirambv** [comment]
Android specific implementation https://github.com/brave/brave-browser/issues/20765
iOS specific implementation https://github.com/brave/brave-ios/issues/4912

Removing Android label from the issue as Android specific issue is logged

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.98 Chromium: 98.0.4758.72 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11655>brave/brave-core#11655</a></li>
         <li>Verified panel has a new <code>Lightning bolt</code>button next to swap</li>
         <li>Verified clicking on the <code>Lightning bolt</code>button shows the recent transactions</li>
         <li>Verified able to click individually listed transaction to see transaction details </li>
         <li>Verified able to submit <code>Speedup</code> or <code>Cancel</code> from the panel itself</li>
         <li>Verified transaction status's displays <code>Value</code>, <code>Transaction fee</code>, <code>Date</code>, <code>Network</code> and <code>Status</code></li>
         <li>Verified <code>Submitted</code>, <code>Confirmed</code> transactions provide hash which links to the block explorer for that transaction</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/151915061-5dd7cdaa-7140-41ad-88bf-9e32796226b7.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151914866-45ce1a71-913d-4596-a32f-9e141566afa3.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151914710-bd047b2b-7419-40b4-894e-95bf1a5837ab.mov>
      </td>
   </tr>
</table>
