### ISSUE TITLE
wallet: using `window.ethereum` opens the old wallet extension

### ISSUE THREAD

**Issue by hazae41** [brave/brave-browser#19531]
## Description 
When connecting to a dApp that uses `window.ethereum`, Brave opens a pop-up related to the old wallet extension, instead of the new Brave Wallet.

## Steps to Reproduce

   1. Setup the old wallet extension
   2. Update Brave
   3. Setup the new Brave Wallet
   4. Connect to a dApp

## Actual result:

Brave opens a pop-up related to the old wallet extension

## Expected result:
Brave opens a pop-up related to the new Brave Wallet

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.32.106 Chromium: 96.0.4664.45

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Untested
- Can you reproduce this issue with the nightly channel? Untested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I guess it happens because I had setup the old wallet extension.

**Comment by bbondy** [comment]
Please check your brave://settings/wallet default wallet.
If it's already set to Brave Wallet then maybe you have added another wallet manually in the past?
Check your brave://extensions if so

**Comment by bbondy** [comment]
This is all explained here https://github.com/brave/brave-browser/wiki/Wallet-support-FAQ#my-metamask-or-other-extension-is-not-working-with-dapps
Closing this since it's not a task.
