### ISSUE TITLE
Properly handle Cargo lockfiles in version control

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#19537]
From discussion with @evq, it's probably worth removing all `Cargo.lock` files except for the one in `build/rust`. As per [The Cargo Book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html):

> If you’re building a non-end product, such as a rust library that other rust packages will depend on, put `Cargo.lock` in your `.gitignore`. If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of `staticlib` or `cdylib`, check `Cargo.lock` into `git`. If you're curious about why that is, see ["Why do binaries have `Cargo.lock` in version control, but not libraries?" in the FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).

We build all of our Rust FFI components into the browser by tying them into a single crate under `build/rust`. We currently check each FFI's individual `Cargo.lock` into version control as well as `build/rust/Cargo.lock`. By the rules above, only `build/rust/Cargo.lock` should be checked in; we should add the others to `.gitignore` and remove them from the repo.

**Comment by antonok-edm** [comment]
@mihaiplesa will this require any extra work regarding Renovate? I don't think I've ever seen Renovate touch `build/rust/Cargo.lock`; that's always required manual PRs afterwards.

**Comment by mihaiplesa** [comment]
It does say it would touch Cargo.lock https://docs.renovatebot.com/rust/

**Comment by antonok-edm** [comment]
Ok, looks like it might have just been confused by the multiple lockfiles in the past, so this would help.

I'll go ahead and make a PR then.
