### ISSUE TITLE
Swapping via Quickswap (Polygon/MATIC) chain shows insufficient funds

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19536]
Reports of insufficient funds even though there are funds here:
https://www.reddit.com/r/brave_browser/comments/qvo5px/does_swapping_via_quickswap_polygonmatic_chain/

## Steps to reproduce

1. Ensure Polygon is added as a network.
    <img width="256" alt="Screenshot 2021-11-19 at 6 33 51 AM" src="https://user-images.githubusercontent.com/3684187/142521167-dd96a84e-f225-41b8-abee-d3702c2aae51.png">
2. Switch your network to Polygon, and make sure you have some MATIC in your account (ping @onyb if you need some).
3. Go to [Quickswap Exchange](https://quickswap.exchange/#/swap) and connect your wallet.
4. Perform a MATIC-USDC exchange, and confirm the transaction on the panel popup.
5. Click on `View on Block Explorer` in this screenshot and wait for the transaction result in that page to be ready.
<img width="1473" alt="Screen Shot 2021-11-18 at 9 09 58 PM" src="https://user-images.githubusercontent.com/4730197/142568585-648c44e2-76d0-42df-9e6f-4469572f32c0.png">

## Expect Result
The transaction should be successful.

## Actual Result
The transaction failed with this error
    <img width="256" alt="Screenshot 2021-11-19 at 6 38 29 AM" src="https://user-images.githubusercontent.com/3684187/142522927-2fab6116-e4bb-4f7b-b258-65b7278a19e3.png">

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/bsc-polygon-chain-buggy-cant-pay-for-gas-fee/302603/3

**Comment by WhiteWolf333** [comment]
Same bug on Fantom Opera Chain ID 0xFA.

**Comment by vleewy** [comment]
Same issue goes to BSC, AVAX network. cant pay for gas fee at all

**Comment by darkdh** [comment]
In `components/brave_wallet/renderer/brave_wallet_js_handler.cc`
We use gas price emptiness to determine using legacy tx or eip1559 tx but gas price is optional
And there is no eip1559 support in polygon (verified by @onyb )
```
...
  } else if (method == kEthSendTransaction) {
    std::string from;
    auto tx_data =
        ParseEthSendTransactionParams(normalized_json_request, &from);
    if (tx_data && !tx_data->gas_price.empty()) {                   <<<<<<<<<< gas_price should be optional
      brave_wallet_provider_->AddAndApproveTransaction(
          std::move(tx_data), from,
          base::BindOnce(&BraveWalletJSHandler::OnAddAndApproveTransaction,
                         weak_ptr_factory_.GetWeakPtr(), std::move(id),
                         std::move(global_context), std::move(global_callback),
                         std::move(promise_resolver), isolate,
                         force_json_response));
    } else {
      from.clear();
      mojom::TxData1559Ptr tx_data_1559 =
          ParseEthSendTransaction1559Params(normalized_json_request, &from);
      if (!tx_data_1559)
        tx_data_1559 = mojom::TxData1559::New();
      brave_wallet_provider_->AddAndApprove1559Transaction(
          std::move(tx_data_1559), from,
          base::BindOnce(&BraveWalletJSHandler::OnAddAndApproveTransaction,
                         weak_ptr_factory_.GetWeakPtr(), std::move(id),
                         std::move(global_context), std::move(global_callback),
                         std::move(promise_resolver), isolate,
                         force_json_response));
    }
  } else if (method == kEthSign || method == kPersonalSign) {
```

We should check the network with `EthJsonRpcController::GetIsEip1559` to decide use eip1559 or not

**Comment by onyb** [comment]
As @darkdh pointed out, we are erroneously signing EIP-1559 transactions (Type-2) whereas Polygon and probably most other EVM chains do not support EIP-1559.

```sh
$ curl -s https://polygon-rpc.com -X POST -H "Content-Type: application/json" -d '{"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false]}' | jq '.result.basefee'
null
```

Note that transactions originating from the wallet are not impacted. This bug only affects dapp transaction requests.

**Comment by darkdh** [comment]
we already update `is_eip1559` support when add/switch network, so we can get that from `GetAllCustomChains` without initiating additional query

**Comment by yrliou** [comment]
`EthJsonRpcController::GetAllNetworks` is probably better for this.

**Comment by yrliou** [comment]
I ended with exposing a new `GetNetwork` API to get the current network info and use it when deciding if we should create eip1559 tx or legacy tx.

**Comment by onyb** [comment]
Tested OK with QuickSwap on Polygon. ✅

**Comment by vleewy** [comment]
please check in depth. 

1. unable to transfer out of brave wallet

![image](https://user-images.githubusercontent.com/94606742/142798569-82b2fa86-b92f-464e-bbe3-dce38f0edd55.png)

2. unable to cancel transactions. where do we change the noune?

![image](https://user-images.githubusercontent.com/94606742/142798613-8360426f-dc29-4799-8a64-1dfbed7cc8ca.png)

3. unable to unstake from https://dapp.klimadao.finance/#/stake

![image](https://user-images.githubusercontent.com/94606742/142798637-9f65356c-9787-49ad-8f5f-f3ddca93ac2a.png)

![image](https://user-images.githubusercontent.com/94606742/142798644-8502441d-0cb1-43bd-95ac-c19fced6e755.png)

**Comment by srirambv** [comment]
@vleewy  did you check on the latest nightly build `1.34.28`?

**Comment by onyb** [comment]
@vleewy Regarding 1/, I was able to reproduce the bug and created an https://github.com/brave/brave-browser/issues/19642 to track it. Thanks for reporting.

Bug 2/ should be fixed in the latest nightly build as @srirambv pointed out, but let us know if it isn't the case.

**Comment by vleewy** [comment]
> @vleewy Regarding 1/, I was able to reproduce the bug and created an #19642 to track it. Thanks for reporting.
> 
> Bug 2/ should be fixed in the latest nightly build as @srirambv pointed out, but let us know if it isn't the case.

noted with thanks

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.32.111 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Linux

- Verified test plan from issue description
- Verified able to swap tokens on Quickswap (Polygon/MATIC) [Txhash](https://polygonscan.com/tx/0xffab0aa428e7b7f86858ca74310f540d86ded0a9106bf46465d26cc16608d86f)


![image](https://user-images.githubusercontent.com/17010094/143042844-68b5f2c1-fa93-48c1-a58c-dc0da0c660a4.png) | ![image](https://user-images.githubusercontent.com/17010094/143043300-eb1399f8-5f11-4d6b-b6e6-29846c7b7e7e.png) | ![image](https://user-images.githubusercontent.com/17010094/143043338-8a70bc6c-f7b0-4ede-9299-37b7e7bcd20f.png) | ![image](https://user-images.githubusercontent.com/17010094/143043416-238d02a6-41e1-4df6-a472-a35913e14b65.png) | ![image](https://user-images.githubusercontent.com/17010094/143043464-53ee944c-94fe-44c2-9d2a-65472ef8a9c0.png) | ![image](https://user-images.githubusercontent.com/17010094/143043528-f768ce6b-e508-464f-9e41-c4dc1d5cc548.png)
-- | -- | -- | -- | -- | --
