### ISSUE TITLE
Brave wallet

### ISSUE THREAD

**Issue by rafalohaki** [brave/brave-browser#19535]
New version of brave wallet:
![image](https://user-images.githubusercontent.com/20607107/142241737-1f461829-39e7-4abf-8770-f5adfdae076d.png)
am i doing it right? there is 2 lines for ids. should it be the same id?

**Comment by rafalohaki** [comment]
ps. what is diff with brave wallet and brave wallet (extensions)
![image](https://user-images.githubusercontent.com/20607107/142246152-f509f8bb-68ea-4b39-b293-0f796b1c6616.png)

**Comment by rafalohaki** [comment]
brave wallet is not compatible with metamask integration
for example adding new network to wallet from https://chainlist.org/

**Comment by rafalohaki** [comment]
icons in wallet from adding network not loading from imgur

**Comment by UjCbFwtBayFM** [comment]
> ps. what is diff with brave wallet and brave wallet (extensions) ![image](https://user-images.githubusercontent.com/20607107/142246152-f509f8bb-68ea-4b39-b293-0f796b1c6616.png)

`Brave Wallet (Prefer extensions)` will have the new Brave Wallet as your default wallet unless you install a wallet extension like Metamask. If you select `Brave Wallet` it won't be overriden by extensions.

**Comment by bbondy** [comment]
Selecting Brave Wallet will lock `window.ethereum` to Brave.
Selecting Brave Wallet (Prefer extensions) will allow extensions to overwrite `window.ethereum` with their own implementation.

**Comment by bbondy** [comment]
The 0x prefix means base 16 so you'll want 0x89
We're making this more simple so you can put base 10 numbers though in the issue below.

Going to close this as a duplicate to https://github.com/brave/brave-browser/issues/19583

**Comment by rafalohaki** [comment]
> The 0x prefix means base 16 so you'll want 0x89 We're making this more simple so you can put base 10 numbers though in the issue below.
> 
> Going to close this as a duplicate to #19583
 there is still a lot of problems with brave wallet. basically its just not working using custom networks

**Comment by bbondy** [comment]
> there is still a lot of problems with brave wallet. basically its just not working using custom networks
> idk but explorers not working too. not showing any amount of my tokens.
> first, you should make tests for foolproof. as a normal user im forced install metamask

Yes we have various issues posted for the various problems. Many of them are being released in the next 1-2 days in the next hotfix.

>  not showing any amount of my tokens.

We don't have token discovery yet so you can add them to your visible asset list from the brave://wallet main interface.
