### ISSUE TITLE
Give a warning when sending to a non-checksum'ed address or an address who's checksum doesn't validate the address

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19532]
In Ethereum an address casing is used as a checksum for validation.  We should check this and if it fails give an error. 

- If an input address matches the API result for `KeyringController`'s `GetChecksumEthAddress` then don't give a warning
- If an address has each alphabetic character as lowercase, give a warning that the address has no checksum information and might be invalid.
- If an address has each alphabetic character as uppercase, give a warning that the address has no checksum information and might be invalid.
- If an address has both lowercase and uppercase alphabetic characters, and it doesn't match the checksum address, give an error and don't allow the user to send.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.89 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11607>brave/brave-core#11607</a></li>
         <li>Verified entering an invalid address throws message about not a valid ETH address</li>
         <li>Verified an error is shown when the address is missing checksum or has an invalid checksum</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/150786875-cdd8c2b6-3eef-4976-a6d7-9739d57e00f9.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/150786231-4410a207-ac02-4432-9705-326b9c719ec7.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/150785759-bcfe0bf6-5ee8-40a4-8d02-f93a04d4e661.mov>
      </td>
   </tr>
</table>

**Comment by Ymetro** [comment]
So, then we have to ask, for instance, Binance for using casing in their deposit addresses, cause now it can only be sent by Brave Browser for PC/Mac/Linux and not by the Brave Mobile browser version 1.47 (23.2.1.14) on iOS 16.3, because after the check there is no way to proceed when asked; the sent button remains greyed out.
