### ISSUE TITLE
Remove binance widget from new tab page

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#19546]
This issue is to track removing the binance widget from the new tab page.
Parent issue which also includes desktop changes : https://github.com/brave/brave-browser/issues/19478

**Comment by srirambv** [comment]
This issue is not fixed on 1.33.98

https://user-images.githubusercontent.com/17010094/144402752-4dc7a9f9-0dec-4233-9409-e0f984d3d6c9.mp4

**Comment by kjozwiak** [comment]
Going to do https://github.com/brave/brave-browser/issues/19888 instead of completely removing it. Closing as https://github.com/brave/brave-core/pull/11148 will be reverted from `1.35.x` & `1.34.x`.
