### ISSUE TITLE
Ledger Nano S fails to open in linux - Ubuntu 20.04

### ISSUE THREAD

**Issue by scmart** [brave/brave-browser#19540]
Fails to connect to Ledger Nano S.

## Steps to Reproduce

   1. Connect Ledger Nano S
   2. Open Brave Wallet
   3. Add Account
   4. Select Hardware, Ledger, and hit Connect 

## Actual result:

 "Failed to open the device."

## Expected result:
  Hardware wallet opens

## Reproduces how often: 
  Always.

## Brave version (brave://version info)
 Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

## Other Additional Information:

  This is using UsbHid, Ledger Live is not installed.

  The ledger Nano S connects with metamask in Firefox, but not metamask in Brave or Chromium. 

- Is the issue reproducible on the latest version of Chrome?  Yes

With a Debug build, the issue can be traced to:

`third_party/blink/renderer/modules/hid/hid_device.cc:439`

leading to a DOMException of "Failed to open the device."

**Comment by srirambv** [comment]
Was Ethereum app opened on Ledger before trying to connect?

**Comment by scmart** [comment]
Yes the Ledger S ETH app was opened.

**Comment by spylogsster** [comment]
whether your device is visible in Trezor Suite app on Linux?

**Comment by scmart** [comment]
Not a Trezor, so no Trezor Suite.  The Ledger Nano S shows up in the dropdown box that asks me to select the device the first time I attempt access, but then it seems to act as though I denied access.

Better than a different browser profile, I can set up a second install on another machine and try it there.

**Comment by scmart** [comment]
As I said above, this problem persists on Chromium on the same install, but works on Firefox.


Installed on a separate Ubuntu 20.04 on a machine and it works.  So this seems to be an Issue with WebHID on one specific machine.

**Comment by spylogsster** [comment]
@scmart I appologies for the mistyping, please try run Ledger Live app on that Linux and check if it sees device correctly, if not they have hints how to fix common issues, when it will be visible in the Ledger's app it should work in the browser too

**Comment by scmart** [comment]
Was able to solve the problem. Looks like adding udev rules is required again for chromium based browsers.  This ticket can be closed.
