### ISSUE TITLE
Incorrect origin is shown when a spend approval is pending

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19557]
## Description 

Incorrect origin is shown when an spend approval is pending

## Steps to Reproduce

   1. Initiate a send approval on `https://app.uniswap.org`
   2. Do not approve or reject the request via panel
   3. Open a new site in a new tab and open wallet panel, shows spend approval from the new site rather than initiator

## Actual result:

<img width=500 src=https://user-images.githubusercontent.com/17010094/142402714-f4871fd1-9a32-415a-9ffc-483d851c568a.png>

## Expected result:
<img width=500 src=https://user-images.githubusercontent.com/17010094/142401538-72a96ae9-4282-4b3f-b54f-c4d4cba59c62.png>

## Reproduces how often: 

easy

## Brave version (brave://version info)

Brave | 1.34.22 Chromium: 96.0.4664.45 (Official Build) nightly (x86_64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Side effect of https://github.com/brave/brave-core/pull/11132
cc: @Douglashdaniel

**Comment by onyb** [comment]
Moved this to Backlog (backend). We need an `origin` field in the `TransactionInfo` struct, which should contain the site url and the favicon url.

**Comment by supermassive** [comment]
Should've been fixed by https://github.com/brave/brave-browser/issues/21915
