### ISSUE TITLE
 Brave Wallet Cannot Connect to Hex 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19551]
## Description 

 Brave Wallet Cannot Connect to Hex 

## Steps to Reproduce

   1. Visit `https://go.hex.com/stake/`
   2. See banner message 

## Actual result:

https://user-images.githubusercontent.com/17010094/142377828-775889eb-994e-4ac6-9e00-6c5e0c48b64b.mp4

## Expected result:
Able to connect wallet

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Reported on community https://community.brave.com/t/bug-new-brave-wallet-cannot-connect-to-hex/302961

**Comment by bbondy** [comment]
To fix this we need to stop hard coding:
```
  window.ethereum._metamask = {
    isUnlocked: () => {
      return Promise.resolve(false);
    }
  }
```

And instead give the real value of if the wallet is locked or not.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified able to connect wallet to the site</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143412733-8b4df3d7-6541-4db7-8502-a8ada2081308.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143413257-83777031-3e3e-4553-ac9d-24ca33780d05.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143412100-01b7b78e-ef94-404d-8a30-464cce900529.mov>
      </td>
   </tr>
</table>
