### ISSUE TITLE
[Sync] Devices reappear after removing from the sync chain

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#19561]
## Description 

Issue reported by @iefremov 

May be related to https://bugs.chromium.org/p/chromium/issues/detail?id=1225961

```
Basically I add a device to the existing chain, then remove and it reappears after a while - sometimes immediately, sometimes after 1-3 minutes.
Tried one more time: removed a phone from the chain on desktop browser. After ~10 minutes phone is not shown on the chain on desktop (which is good), but the browser on the phone itself is synced, shows the whole chain on the settings page.
```

## Steps to Reproduce

   1. Create a sync chain between two desktop profiles
   2. From deviceA remove deviceB
   3. Wait ~3 minutes

## Actual result:

4. deviceB disappears from the devices list at deviceA, but then re-appears
5. deviceB never goes into `sync is turned off` state

## Expected result:
4. deviceB disappears from the devices list at deviceA, and then doesn't  re-appear
5. deviceB  goes into `sync is turned off` state

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

Confirmed at 

Brave | 1.33.77 Chromium: 96.0.4664.35 (Official Build) unknown (64-bit)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @jsecretan , @darkdh

**Comment by LaurenWags** [comment]
@brave/legacy_qa check leaving a sync chain with various devices/platforms

**Comment by stephendonner** [comment]
We're going to do:

desktop --> iOS
desktop --> Android
desktop --> desktop (same OS)
iOS --> desktop
Android --> desktop
iOS --> Android
Android --> iOS

desktop --> iOS and Android
desktop --> desktop (same or diff), 2 mobiles of your choosing

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 

Brave | 1.34.67 Chromium: 97.0.4692.56 (Official Build) beta (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)

<summary>Windows --> iOS - FAILED</summary>
<details>

1. new profile of `1.34.x` on Windows 10
2. launch Brave
3. set up a Sync chain
4. join Sync chain from iOS by scanning the QR code
5. from desktop, click on the trashcan icon to remove the iOS device
6. click `OK` when prompted to confirm
7. wait 3 minutes
8. look at the Sync screen on Windows
9. look at the Sync screen on iOS
</details>

<summary>Windows --> Android - PASSED</summary>
<details>

1. new profile of `1.34.x` on Windows 10
2. launch Brave
3. set up a Sync chain
4. join Sync chain from Android by scanning the QR code
5. from desktop, click on the trashcan icon to remove the Android device
6. click `OK` when prompted to confirm
7. wait 3 minutes
8. look at the Sync screen on Windows
9. look at the Sync screen on Android

example | example | example | example
----------|-----------|----------|----------
![19561-1](https://user-images.githubusercontent.com/387249/146849242-67603f20-9838-4bbb-b7a9-bb79f64e191d.png) | ![Screenshot_20211220-160855](https://user-images.githubusercontent.com/387249/146849299-dbb9a6f3-3ab8-49d0-b2d7-33f753565e68.png) | ![19561-2](https://user-images.githubusercontent.com/387249/146849321-d9ffae75-85b4-4d41-aa74-6ea3c5a91903.png) | ![Screenshot_20211220-161027](https://user-images.githubusercontent.com/387249/146849340-a801e42c-96ad-4add-b624-415fff555968.png)





</details>
<summary>Windows --> Windows</summary>

<details>
.
</details>
<summary>iOS --> Windows</summary>
<details>

1. fresh install Brave for iOS`1.34.x`
2. tap through onboarding
3. tap on the 3-dots icon on the bottom right of the toolbar
4. tap `Settings`
5. tap `Sync`
6. tap `Start a new sync chain`
7. tap `Add a computer`
8. copy the code words
9. on Windows, launch Brave `1.34.x`
10. load `brave://settings/braveSync`
11. click on `Start using sync`
12. click `I have a Sync Code`
13. paste the code words and click `Confirm`
14. click `OK`
15. tap on the Windows device on iOS
16. tap `Remove device` 
17. tap `Remove`
18. wait 3 minutes
19. look at the Sync screen on iOS
20. look at the Sync screen on Windows

example | example | example | example
----------|----------|-----------|----------
![19561-3](https://user-images.githubusercontent.com/387249/146850632-a19a8f6d-9902-40f1-8f74-156cddd24e56.png) | ![Image from iOS](https://user-images.githubusercontent.com/387249/146850696-baff8c85-ea79-4a2c-8962-9383adbdf63c.png) | ![19561-4](https://user-images.githubusercontent.com/387249/146850723-16475641-14e3-45e0-9979-f182e4659eca.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/146850740-806aedb8-913d-4e62-ba70-5580a6198f29.png)





</details>

<summary>Android --> Windows</summary>

<details>
1. fresh install Brave for Android `1.34.x`
2. tap through onboarding
3. tap on the 3-dots icon on the bottom right of the toolbar
4. tap `Settings`
5. tap `Sync`
6. tap `Start a new sync chain`
7. tap `Add a computer`
8. copy the code words
9. on macOS, launch Brave `1.34.x`
10. load `brave://settings/braveSync`
11. click on `Start using sync`
12. click `I have a Sync Code`
13. paste the code words and click `Confirm`
14. click `OK`
15. click on the trashcan icon to remove Windows
16. wait 3 minutes
17. look at the Sync screen on Android
18. look at the Sync screen on Windows

example | example | example | example
----------|-----------|----------|----------
![19561-1](https://user-images.githubusercontent.com/387249/146848808-1645a36e-e7b6-4a4a-be44-91880304b2f8.png) | ![Screenshot_20211220-160226](https://user-images.githubusercontent.com/387249/146848830-86671abe-2645-4d46-8080-19d5a14830a8.png) | ![19561-2](https://user-images.githubusercontent.com/387249/146848860-54752501-fd65-45e4-a40e-08a9c6397fff.png) | ![Screenshot_20211220-160441](https://user-images.githubusercontent.com/387249/146848876-23ebdeff-f901-4fa0-8562-0eab67166e9a.png)






</details>

<summary>iOS --> Android</summary>

<details>
.
</details>
<summary>Android --> iOS</summary>

<details>
.
</details>

<summary>desktop --> iOS and Android</summary>

<details>
.
</details>

<summary>Windows --> macOS, iOS, and Android</summary>

<details>
.
</details>

**Comment by stephendonner** [comment]
Setting to `QA/Blocked` as we're unable to get iOS devices removed remotely, due to https://github.com/brave/brave-ios/issues/4747.  Will revisit the `FAILED` tests when the above is addressed, and unblocking us.

**Comment by stephendonner** [comment]
> Setting to `QA/Blocked` as we're unable to get iOS devices removed remotely, due to [brave/brave-ios#4747](https://github.com/brave/brave-ios/issues/4747). Will revisit the `FAILED` tests when the above is addressed, and unblocking us.

The above issue is itself now blocked by a crasher (which has a fix and we'll get tomorrow): https://github.com/brave/brave-ios/issues/4764.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.34.70, Chromium 97.0.4692.56`

See verification notes from https://github.com/brave/brave-browser/issues/19561#issuecomment-998370656 for:
* Android ==> Windows
* iOS ==> Android
* Windows ==> iOS and Android
* Windows ==> macOS, iOS, and Android

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using

Brave | 1.34.70 Chromium: 97.0.4692.56 (Official Build) beta (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)

 and the same version for Android; iOS is `1.34 (21.12.21.19)`

<summary>macOS --> iOS - PASSED</summary>
<details>

1. new profile of `1.34.x` on macOS
2. launch Brave
3. set up a Sync chain
4. join Sync chain from iOS by scanning the QR code
5. from desktop, click on the trashcan icon to remove the iOS device
6. click `OK` when prompted to confirm
7. wait 3 minutes
8. look at the Sync screen on macOS
9. look at the Sync screen on iOS

Confirmed the macOS desktop remains
Confirmed the iOS device is removed

Example | Example | Example | Example
---------|---------|----------|----------
<img width="1104" alt="Screen Shot 2021-12-22 at 9 37 27 PM" src="https://user-images.githubusercontent.com/387249/147193491-ed6166f6-9149-4e34-8831-0823f20f09df.png"> | ![Image from iOS](https://user-images.githubusercontent.com/387249/147193693-fc9fdb65-9308-49e0-a565-91ac65317c4b.png) | <img width="1104" alt="Screen Shot 2021-12-22 at 9 37 42 PM" src="https://user-images.githubusercontent.com/387249/147193494-93b396ff-0706-4867-8887-fd218cc2e352.png"> | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/147193690-7dd7a160-3f23-41e3-b103-b008e2a86a21.png)


</details>

<summary>macOS --> Android - PASSED</summary>
<details>

1. new profile of `1.34.x` on macOS
2. launch Brave
3. set up a Sync chain
4. join Sync chain from Android by scanning the QR code
5. from desktop, click on the trashcan icon to remove the Android device
6. click `OK` when prompted to confirm
7. wait 3 minutes
8. look at the Sync screen on macOS
9. look at the Sync screen on Android

Confirmed the macOS desktop remains
Confirmed the Android device is removed

Example | Example | Example | Example
---------|---------|----------|----------
<img width="1104" alt="Screen Shot 2021-12-22 at 9 47 05 PM" src="https://user-images.githubusercontent.com/387249/147194349-c3526595-ea15-4595-a881-054c9b60c71e.png"> | ![Screenshot_20211222-214709](https://user-images.githubusercontent.com/387249/147194400-0bfc7d1e-1d5c-404d-97c5-ba855f0586a6.png) | <img width="1104" alt="Screen Shot 2021-12-22 at 9 47 15 PM" src="https://user-images.githubusercontent.com/387249/147194353-9b97875f-8c31-4642-99b1-c879e58b1c7f.png"> | ![Screenshot_20211222-214739](https://user-images.githubusercontent.com/387249/147194427-eea6b7e0-effe-420c-a564-1a56a00187f1.png)




</details>

<summary>macOS (x86) --> macOS (arm64) - PENDING</summary>

<details>

1. fresh install Brave on macOS (x86) & macOS (arm64)
2. from macOS (x86), start a Sync chain
3. copy the code words
4. join the Sync chain on macOS (arm64) by pasting in the copied code words
5. from macOS (x86), click on the trashcan icon to remove the macOS (arm64) device
6. look at the Sync screen on macOS (x86)
7. look at the Sync screen on macOS (arm64)

Confirmed the macOS (x86) desktop remains
Confirmed the macOS (arm64) desktop is removed

example | example | example | example
----------|-----------|----------|----------



</details>
<summary>iOS --> macOS - PASSED</summary>
<details>

1. fresh install Brave for iOS `1.34.x`
2. tap through onboarding
3. tap on the 3-dots icon on the bottom right of the toolbar
4. tap `Settings`
5. tap `Sync`
6. tap `Start a new sync chain`
7. tap `Add a computer`
8. copy the code words
9. on macOS, launch Brave `1.34.x`
10. load `brave://settings/braveSync`
11. click on `Start using sync`
12. click `I have a Sync Code`
13. paste the code words and click `Confirm`
14. click `OK`
15. tap on the macOS device on iOS
16. tap `Remove device`
17. tap `Remove`
18. wait 3 minutes
19. look at the Sync screen on iOS
20. look at the Sync screen on macOS

Confirmed the iOS device remains
Confirmed the macOS desktop is removed

Example | Example | Example | Example
---------|---------|----------|----------
![Image from iOS (4)](https://user-images.githubusercontent.com/387249/147195696-c681f2f6-c82b-48f8-a7a5-a3ff5e6d5905.png) | <img width="1104" alt="Screen Shot 2021-12-22 at 9 59 22 PM" src="https://user-images.githubusercontent.com/387249/147195756-091b037c-6f2c-438b-a337-e3d85f1bda4a.png"> | ![Image from iOS (5)](https://user-images.githubusercontent.com/387249/147195699-209e936c-7d64-4989-bc2f-52a1ae392fb8.png) | <img width="1104" alt="Screen Shot 2021-12-22 at 9 59 52 PM" src="https://user-images.githubusercontent.com/387249/147195758-c3dd8deb-0b7c-413f-8385-602b089a0a9f.png">







</details>

<summary>Android --> macOS - PASSED</summary>

<details>

1. fresh install Brave for Android `1.34.x`
2. tap through onboarding
3. tap on the 3-dots icon on the bottom right of the toolbar
4. tap `Settings`
5. tap `Sync`
6. tap `Start a new sync chain`
7. tap `Add a computer`
8. copy the code words
9. on macOS, launch Brave `1.34.x`
10. load `brave://settings/braveSync`
11. click on `Start using sync`
12. click `I have a Sync Code`
13. paste the code words and click `Confirm`
14. click `OK`
15. click on the trashcan icon to remove macOS
16. wait 3 minutes
17. look at the Sync screen on Android
18. look at the Sync screen on macOS

Confirmed the Android device remains
Confirmed the macOS desktop is removed

Example | Example | Example | Example
---------|---------|----------|----------
<img width="1104" alt="Screen Shot 2021-12-22 at 9 53 04 PM" src="https://user-images.githubusercontent.com/387249/147194898-2fd2805c-a892-424a-a4fb-7092ea515bb3.png"> |![Image from iOS](https://user-images.githubusercontent.com/387249/147194998-55e39a28-4ca6-45e1-b5d6-5b9d901fde76.png) | <img width="1104" alt="Screen Shot 2021-12-22 at 9 53 13 PM" src="https://user-images.githubusercontent.com/387249/147194901-f71d7c24-4ceb-4f4d-a73d-667abdb986e6.png"> | ![Image from iOS (3)](https://user-images.githubusercontent.com/387249/147195027-4ecda64a-539f-430e-9f11-e8fa55936daa.png)


</details>



<summary>macOS--> iOS and Android - PASSED</summary>

<details>

1. new profile of `1.34.x` on macOS
2. launch Brave
3. click on `Start a new Sync chain`
4. click on `Phone/Tablet`
5. join Sync chain from iOS
5. join Sync chain from Android
6. from macOS, click on the trashcan icons to remove both iOS & Android devices
7. click `OK` when prompted to confirm
8. wait 3 minutes
9. look at the Sync screen on macOS
10. look at the Sync screen on iOS
11. look at the Sync screen on Android

Confirmed the macOS desktop remains
Confirmed the iOS device is removed
Confirmed the Android device is removed

Example | Example | Example | Example | Example | Example
---------|---------|----------|----------|---------|----------
<img width="1104" alt="Screen Shot 2021-12-22 at 10 11 21 PM" src="https://user-images.githubusercontent.com/387249/147196593-900af8c1-05c7-4dc4-88e1-ba7a653e4345.png"> | ![Image from iOS (6)](https://user-images.githubusercontent.com/387249/147196722-ed1b5193-b483-4dfa-8555-b71715f4e0a1.png) | ![Screenshot_20211222-221126](https://user-images.githubusercontent.com/387249/147196754-80422235-ed57-40c6-a139-ebe39b7a7c64.png) | <img width="1104" alt="Screen Shot 2021-12-22 at 10 12 02 PM" src="https://user-images.githubusercontent.com/387249/147196602-08c24d51-d032-48b1-b1b1-1f981fb2e87f.png"> | ![Image from iOS (7)](https://user-images.githubusercontent.com/387249/147196805-a6a0ab19-a981-4d60-a56c-578804d7f6d5.png) | ![Screenshot_20211222-221220](https://user-images.githubusercontent.com/387249/147196823-45d262b4-59f8-401c-8c95-a5830483e1ca.png)







</details>

<summary>macOS --> Windows, iOS, and Android -</summary>

<details>

1. new profile of `1.34.x` on Windows
2. launch Brave
3. click on `Start a new sync chain`
4. click on `Phone/Tablet`
5. join Sync chain from iOS
5. join Sync chain from Android
6. join Sync chain from Windows
7. from macOS, click on the trashcan icons to remove the macOS, iOS, & Android devices
7. click `OK` when prompted to confirm
8. wait 3 minutes
9. look at the Sync screen on macOS
10. look at the Sync screen on Windows
11. look at the Sync screen on iOS
12. look at the Sync screen on Android

Confirmed the macOS desktop remains
Confirmed the Windows desktop is removed
Confirmed the iOS device is removed
Confirmed the Android device is removed


Example | Example | Example | Example
---------|---------|----------|---------
<img width="1054" alt="Screen Shot 2021-12-22 at 10 21 55 PM" src="https://user-images.githubusercontent.com/387249/147198322-ae0c14b7-818c-4fc8-8f4e-e38c6d0fcbfe.png"> | ![all-four-clients](https://user-images.githubusercontent.com/387249/147198371-946152c6-c384-4ff2-86f6-e242b97b8818.png) | ![Image from iOS](https://user-images.githubusercontent.com/387249/147198448-38395dbc-dc0f-4d31-b3f7-f97e556a2ccf.png) | ![Screenshot_20211222-222144](https://user-images.githubusercontent.com/387249/147198487-1d4c5174-54fa-4522-b7a3-14e4ca51256e.png)

Example | Example | Example | Example
---------|---------|----------|----------
<img width="1054" alt="Screen Shot 2021-12-22 at 10 23 17 PM" src="https://user-images.githubusercontent.com/387249/147198895-ddb47a01-6465-482c-9667-e46916790ec7.png"> | ![all-clients-gone](https://user-images.githubusercontent.com/387249/147198927-cb3009a5-c31f-4d36-98cc-21bc0436aab2.png) | ![Image from iOS](https://user-images.githubusercontent.com/387249/147198961-ce95903d-38de-4f21-9618-93c09f1f507a.png) | ![Screenshot_20211222-222217](https://user-images.githubusercontent.com/387249/147198989-3789f064-e686-4416-ac1e-7aa48ac1a582.png)










</details>

**Comment by stephendonner** [comment]
I botched a simple copy and paste operation, and overwrote (and then made another silly mistake and deleted the wrong edit on the comment) my Windows-verification notes.  I'll rebuild them, but leave the label stand, as I've done the work).

https://github.com/brave/brave-browser/issues/19561#issuecomment-998370656

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.34.71 Chromium: 97.0.4692.56 (Official Build) beta (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Ubuntu 18.04 LTS

 and the same version for Android; iOS is `1.34 (21.12.21.19)`

<summary>Linux --> iOS - PASSED</summary>
<details>

1. new profile of `1.34.x` on Linux
2. launch Brave
3. set up a Sync chain
4. join Sync chain from iOS by scanning the QR code
5. from desktop, click on the trashcan icon to remove the iOS device
6. click `OK` when prompted to confirm
7. wait 3 minutes
8. look at the Sync screen on Linux
9. look at the Sync screen on iOS

Confirmed the Linux desktop remains
Confirmed the iOS device is removed

![image](https://user-images.githubusercontent.com/34715963/147372384-f0204527-dba5-404a-a865-4f03cbf7df7a.png)|![image](https://user-images.githubusercontent.com/34715963/147372393-de34865b-a9ac-4cb1-ac66-4bce36b0f647.png)|![IMG_0079](https://user-images.githubusercontent.com/34715963/147372752-6521b5ac-7d5e-441f-9518-f5222840dd3e.PNG)
--|--|--

</details>

<summary>Linux --> Android - PASSED</summary>
<details>

1. new profile of `1.34.x` on Linux
2. launch Brave
3. set up a Sync chain
4. join Sync chain from Android by scanning the QR code
5. from desktop, click on the trashcan icon to remove the Android device
6. click `OK` when prompted to confirm
7. wait 3 minutes
8. look at the Sync screen on Linux
9. look at the Sync screen on Android

Confirmed the Linux desktop remains
Confirmed the Android device is removed

![image](https://user-images.githubusercontent.com/34715963/147372173-fe098c11-9cb0-4d69-9341-430df51cc796.png)|![image](https://user-images.githubusercontent.com/34715963/147372185-bdb63e09-3cfb-43d7-869d-ec4bbc0b2f9a.png)|![Screenshot_20211224-220617_Brave - Beta](https://user-images.githubusercontent.com/34715963/147372302-cb9ebab7-eee1-4f5e-9674-fa8e1f1b1a73.jpg)
--|--|--


</details>




</details>
<summary>iOS --> Linux - PASSED</summary>
<details>

1. fresh install Brave for iOS `1.34.x`
2. tap through onboarding
3. tap on the 3-dots icon on the bottom right of the toolbar
4. tap `Settings`
5. tap `Sync`
6. tap `Start a new sync chain`
7. tap `Add a computer`
8. copy the code words
9. on Linux, launch Brave `1.34.x`
10. load `brave://settings/braveSync`
11. click on `Start using sync`
12. click `I have a Sync Code`
13. paste the code words and click `Confirm`
14. click `OK`
15. tap on the Linux device on iOS
16. tap `Remove device`
17. tap `Remove`
18. wait 3 minutes
19. look at the Sync screen on iOS
20. look at the Sync screen on Linux

Confirmed the iOS device remains
Confirmed the Linux desktop is removed


![image](https://user-images.githubusercontent.com/34715963/147372426-4881ba60-d7fd-4b89-aaa0-eb7e099f3be0.png)|![image](https://user-images.githubusercontent.com/34715963/147372469-25d77ae1-8cb8-4a55-983e-4b6e43002b38.png)|![IMG_0080](https://user-images.githubusercontent.com/34715963/147372753-138f5023-133d-4b2a-89c9-8756dee87018.PNG)
--|--|--

</details>

<summary>Android --> Linux - PASSED</summary>

<details>

1. fresh install Brave for Android `1.34.x`
2. tap through onboarding
3. tap on the 3-dots icon on the bottom right of the toolbar
4. tap `Settings`
5. tap `Sync`
6. tap `Start a new sync chain`
7. tap `Add a computer`
8. copy the code words
9. on Linux, launch Brave `1.34.x`
10. load `brave://settings/braveSync`
11. click on `Start using sync`
12. click `I have a Sync Code`
13. paste the code words and click `Confirm`
14. click `OK`
15. click on the trashcan icon to remove Linux
16. wait 3 minutes
17. look at the Sync screen on Android
18. look at the Sync screen on Linux

Confirmed the Android device remains
Confirmed the Linux desktop is removed

![image](https://user-images.githubusercontent.com/34715963/147372223-f486dc10-4a18-4012-b47c-1ce1cd731015.png)|![image](https://user-images.githubusercontent.com/34715963/147372240-a319a9d7-6b7d-41a0-b0d7-5b7f2af78094.png)|![Screenshot_20211224-220811_Brave - Beta](https://user-images.githubusercontent.com/34715963/147372305-1507a9e2-c2f8-4637-9b51-0e52ba529196.jpg)
--|--|--

</details>





<summary>Linux --> Windows, iOS, and Android - PASSED</summary>

<details>

1. new profile of `1.34.x` on Windows
2. launch Brave
3. click on `Start a new sync chain`
4. click on `Phone/Tablet`
5. join Sync chain from iOS
5. join Sync chain from Android
6. join Sync chain from Windows
7. from Linux, click on the trashcan icons to remove the Windows, iOS, & Android devices
7. click `OK` when prompted to confirm
8. wait 3 minutes
9. look at the Sync screen on Linux
10. look at the Sync screen on Windows
11. look at the Sync screen on iOS
12. look at the Sync screen on Android

Confirmed the Linux desktop remains
Confirmed the Windows desktop is removed
Confirmed the iOS device is removed
Confirmed the Android device is removed


![image](https://user-images.githubusercontent.com/34715963/147372659-75e0d470-bf83-4bee-af6c-a98ed4ac820a.png)|![image](https://user-images.githubusercontent.com/34715963/147372664-1ba0301b-8fc1-4e7f-871f-147c4fdfdf2d.png)|![Screenshot_20211224-223158_Brave - Beta](https://user-images.githubusercontent.com/34715963/147372687-ff869b03-6009-4383-b6a9-37f6285059ca.jpg)|![IMG_0081](https://user-images.githubusercontent.com/34715963/147372754-1289908c-53f2-4727-81e6-df78e021202f.PNG)
--|--|--|--

![image](https://user-images.githubusercontent.com/34715963/147372711-32ce4ba0-8bb1-4f51-85a0-a4fa389def58.png)|![image](https://user-images.githubusercontent.com/34715963/147372712-2c52d2e7-7d0b-4db6-8a55-4a8992cfaaf1.png)|![Screenshot_20211224-223455_Brave - Beta](https://user-images.githubusercontent.com/34715963/147372722-714bee28-37df-419b-9512-b9faf1664e30.jpg)|![IMG_0082](https://user-images.githubusercontent.com/34715963/147372755-d34db55d-5aaa-4eb2-afa9-264c6625e2bd.PNG)
--|--|--|--




</details>
