### ISSUE TITLE
Failed to sync extensions

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#19563]
@WNG555 reported
https://github.com/brave/brave-browser/issues/19125#issuecomment-972429044

> 
> I gave up hope after updating to Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit).....as there was no fix to the previously stated problems.
> So, I uninstalled Brave x64, and manually stripped all instances of Brave from my registry, and deleted all zombied files and directories. Since I have my settings Synced, I surmised I won't lose my customizations. A fresh install restored my PC to normal operation. No more CPU and RAM runaway conditions, and all the hardware and OS operations are snappy again. The 2 instances of Brave.exe consuming 1+GB of RAM no longer exist.
> But....Brave Sync seems to be buggy as it failed to sync all my extensions, and themes...only bookmarks. Didn't have any problem syncing before with both Linux and Windows systems. Possibly a bug when Brave Sync assigns a name for the Synced system but the name is the same as the previous instance uninstalled. It listed two system of the same name. Deleting the older name didn't correct the Sync issue.
> Just an FYI to anyone planning to take the same route.

**Comment by iefremov** [comment]
cc @jsecretan @AlexeyBarabash

**Comment by tortino** [comment]
see also:
https://github.com/brave/brave-browser/issues/19164

**Comment by iefremov** [comment]
closing as a dupe then https://github.com/brave/brave-browser/issues/19164
