### ISSUE TITLE
Relaunch option is not shown in Tips settings section when the Tips settings are toggled via brave://settings/rewards

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19560]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18158
Relaunch option is not shown in the Tips settings section when the Tips settings are toggled via brave://settings/rewards
## Steps to Reproduce

   1. Clean profile 1.33.x
   2. Enable rewards via BR panel
   3. Open brave://settings/rewards settings page
   4. Toggle Reddit switch
   5. Navigate to brave://rewards settings page
   6. Open Tips section, Reddit option is unchecked but there is no `Relaunch` option

## Actual result:

Relaunch option is not shown in Tips settings section when the Tips settings are toggled via brave://settings/rewards
![image](https://user-images.githubusercontent.com/38657976/142411634-7eec55de-54d4-463f-995c-9f814f51744c.png)

## Expected result:

**1.32.x**
![image](https://user-images.githubusercontent.com/38657976/142411676-fb5ed348-d9ed-40e7-88f8-17c366f35698.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.83 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1348)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @Miyayes @emerick

**Comment by emerick** [comment]
Right, we're not correctly reflecting the "needs a restart" state back to the brave://rewards page. This could be a little bit tricky, as that state management is all handled in-page.

**Comment by mkarolin** [comment]
No longer valid as tipping buttons have been removed (https://github.com/brave/brave-browser/issues/34367).
