### ISSUE TITLE
Fix crash when permission requests for Ethereum are from a popup window

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19566]
Browser crashes on connecting Brave Wallet to https://market.x.immutable.com.
Related bug report: https://community.brave.com/t/brave-wallet-crashing-brave-after-new-update/302976

# Test plan

- Simply go to https://market.x.immutable.com and click on Connect Wallet, the popup window will come up and our popup should come up above it.
- Note that there's a webcompat item separate from this issue so you won't actually be able to connect to the site.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.32.111 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`

- Verified no crash when trying to connecting wallet
- Verified test plan from issue description
- Encountered webcompat issue mentioned in test plan

Linux | Windows | macOS 
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/143053121-ed8e70f5-1c5a-4791-871d-bb754475601e.png> | <img width=350 src=https://user-images.githubusercontent.com/17010094/143053734-a5a65e31-6f0b-4d20-ab59-b32e418671d1.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/143053776-59111ee5-ec43-4719-9411-4622a4e3ba81.png>
