### ISSUE TITLE
Consider using Contract Address for Fetching Prices

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19574]
## Description 
Consider using Contract Address for Fetching Token Prices

Currently we are using the Tokens Symbol as a param to fetch the price of a Token from CoinGecko.
In some occasions the Symbol is different than the `token-id` param required by CoinGecko's api which will cause an incorrect price.

**Comment by bbondy** [comment]
Dropping priority of this since we have a server side fix now for better symbol matching

**Comment by waylonflinn** [comment]
Server side fix may not have addressed all issues.
I posted some details about a problem I encountered today on the community forum:
https://community.brave.com/t/wallet-pointing-to-the-incorrect-price-for-a-coin/305383/4?u=waylonflinn

**Comment by bbondy** [comment]
Note when the server supports lookup by contract address, I think we'll only be able to use it for lookups with Ethereum contract addresses.  We'll still need to query by symbol for when the tokens are on a different network.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.34.78 Chromium: 97.0.4692.56 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11557>brave/brave-core#11557</a></li>
         <li>Verified selecting custom token shows asset price fetched from CoinGecko API</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/148084945-9a12ea36-468f-464a-a2ce-42926525b395.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/148084450-f0ec705f-dde1-4c62-bf46-7e82557f3900.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/148084431-6eb9d2ab-2f91-4f0d-afcb-28912298908e.mov>
      </td>
   </tr>
</table>
