### ISSUE TITLE
Switch network Brave popup window only show one time when interacting on dapp

### ISSUE THREAD

**Issue by bitcoinuser** [brave/brave-browser#19576]
I click on the dapp to switch the network to Ethereum, and I see the Brave Browser popup to change the network, but if I go back to portfolio and click to swich network, the Brave popup doesn't show. I need to click on Brave wallet icon to switch manually the network. So I think the switch network brave wallet popup only show one time when interacting with the dapp. 

The brave popup that I mean:

![Captura de tela de 2021-11-18 19-44-58](https://user-images.githubusercontent.com/1178856/142509484-8501db32-9ea6-4d5f-b396-db07c7a8fc47.png)

 

## Steps to Reproduce

   1. Go to https://live.sovryn.app/ and connect using Brave wallet and RSK network
   2. Go to Portfolio and click to Deposit XUSD and choose ETH network on the dapp page. Then click on switch network button of the dapp. The switch network popup of Brave wallet will show. So click on cancel button on Brave. Now click again on Switch network button on the dapp. As you can see the Brave popup to switch network will not appear this time.
   3. 

## Actual result:

Nothing happens

## Expected result:
Appear the Brave wallet popup to switch the network.
OBS. On Metamask works ok.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Versão 1.32.106 Chromium: 96.0.4664.45 (Versão oficial) 64 bits

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by bbondy** [comment]
Working on the new update? Thanks for closing!
