### ISSUE TITLE
Details view open for 0 blocked items on shields

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1957]
## Description 

Details view open for 0 blocked items on shields

## Steps to Reproduce

   1. Install beta build
   2. Visit https://brave.com
   3. Click on shields, click on down carrot, doesn't open the details view, cursor changes to hand icon
   4. Click on `0`, opens details view even though there is nothing to show

## Actual result:

![508](https://user-images.githubusercontent.com/17010094/47881521-bac88280-ddfc-11e8-8d7e-3d811e657569.gif)

## Expected result:
Should only change cursor to hand icon when there are blocked items so that the details view can be shown

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Follow up to #507 
cc: @karenkliu @tomlowenthal

**Comment by bsclifton** [comment]
Updated to be 0.58.x after DEPS was updated with https://github.com/brave/brave-core/pull/820

PR is tagged with uplift-request; let's make sure to modify milestone if that is approved 😄

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Windows

- Verified the STR mentioned in the issue.
