### ISSUE TITLE
Autofill suggestions can cover the address bar

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#19575]
## Description 
Reported in slack https://bravesoftware.slack.com/archives/C0816QH3R/p1637100951267500

## Steps to reproduce 

   1. Go to https://kirtikumarar.com/brave/autofill.html
   2. Click `click me`
   3. Autofill pop up covers address bar

## Actual result 
Autofill pop up covers address bar

## Expected result
Autofill pop up should not cover address bar

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED` with Brave `1.34.63, Chromium 96.0.4664.110` using the inline testplan on a Google Pixel XL running Android 9.0.

Confirmed after tapping `click me` that the autocomplete popup was anchored below the URL bar:

![Screenshot_20211215-093213](https://user-images.githubusercontent.com/387249/146236736-7f001aaa-aec6-4f19-8022-13f7595f0800.png)
