### ISSUE TITLE
error modal text is generic when using non KYC bitFlyer wallet 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#19572]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/16652

For bitFlyer, when attempting to login with non KYC'd account, the error modal shows a "generic" error instead of the more specific one from https://github.com/brave/brave-core/pull/10469.

Note - this is also how this works with 1.32.x.

## Steps to Reproduce

   1. Clean profile 1.33.x, set region to Japan, use staging env
   2. Enable Rewards
   3. Choose to verify with bitFlyer
   4. Login with non KYC'd account

## Actual result:

<img width="1189" alt="Screen Shot 2021-11-18 at 15 40 33" src="https://user-images.githubusercontent.com/28145373/142499983-85b334b1-2849-49d5-a6a7-a06bb6c4ff56.png">

## Expected result:

Expected the bitFlyer version of the `kycRequiredModal` from https://github.com/brave/brave-core/pull/10469:

![kycreq](https://user-images.githubusercontent.com/28145373/142500078-473864f2-f5c4-4273-817e-ce0adb193033.png)

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.33.83 Chromium: 96.0.4664.45 (Official Build) beta (x86_64)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 11.6.1 (Build 20G224)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 1.32.x
- Can you reproduce this issue with the beta channel? yes 1.33.x
- Can you reproduce this issue with the nightly channel? yes 1.34.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @szilardszaloki

**Comment by szilardszaloki** [comment]
Asked `bitFlyer` to make the appropriate change on their end, so that when a non-KYC'd user hits `Cancel` on the linkage confirmation screen, they redirect them to `brave://rewards/bitflyer/authorization?error=access_denied&state=<state>&error_description=User+does+not+meet+minimum+requirements` (instead of redirecting them to `brave://rewards/bitflyer/authorization?error=access_denied&state=<state>&error_description=Resource+owner+or+authorization+server+rejected+the+request.`).

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.36.86 Chromium: 98.0.4758.87 (Official Build) beta (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.2 (Build 21D49)
```

Verified STR from description.

English | Japanese
----- | -----
<img width="1193" alt="English" src="https://user-images.githubusercontent.com/28145373/152869523-86953a7f-a86c-4951-b88b-85c74b76646e.png"> | <img width="1192" alt="Japanese" src="https://user-images.githubusercontent.com/28145373/152869535-cafba7b7-4af5-4c35-8f40-b89edc0c6dc4.png">
