### ISSUE TITLE
Support decimal chain id in custom networks input

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#19583]
From reddit https://www.reddit.com/r/brave_browser/comments/qws7o2/brave_wallet_should_support_decimal_chain_id/

Check decimal number against hex for chain ID

**Comment by jamesmudgett** [comment]
duplicate https://github.com/brave/brave-browser/issues/19524

**Comment by bbondy** [comment]
Let's do this as a first step before #19424 @jamesmudgett. Re-opening.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.114 Chromium: 96.0.4664.55 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified able to add a custom RPC network using the decimal chain id</li>
         <li>Verified chain id field only access decimal value so entering <code>0x89</code> results in <code>089</code></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144786431-f64548f2-45ad-4167-912d-4c13658e0840.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144786083-5c42f69d-9a01-4baa-bc65-d252a158cb9f.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144785724-56d4f791-52b3-4c81-a790-ae7c43c8f54c.mov>
      </td>
   </tr>
</table>
