### ISSUE TITLE
Fix conflicts in PageInfo dialog for IPFS pages 

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19586]
## Description 

Chromium has changed the dialog layout, need to rework IPFS page information

## Steps to Reproduce

- In cr97 need to enable flag. brave://flags/#page-info-version-2-desktop
- Visit IPFS page e.g. ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html
- Select IPFS icon in the url bar and open page info dialog.

## Reproduces how often: 

100% 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by spylogsster** [comment]
fixed in cr98

**Comment by LaurenWags** [comment]
Additional info: https://bravesoftware.slack.com/archives/C7VLGSR55/p1639622683299100

**Comment by stephendonner** [comment]
Per @mariospr and @spylogsster: the flag has now been removed from cr97 as well on commit https://chromium-review.googlesource.com/c/chromium/src/+/3245532 (it was pulled as part of Chromium 97.0.4690.0, and we now have Chromium 97.0.4692.56 there).

Verified `PASSED` using 

Brave | 1.34.68 Chromium: 97.0.4692.56 (Official Build) beta (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Steps:
1. new profile
2. launched Brave
3. loadedd `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
4. clicked on `Use a local node`
5. clicked on page-info icon
6. confirmed presence and functionality of IPFS UI

example | example
----------|----------
![ipfs-page-info-1](https://user-images.githubusercontent.com/387249/146978753-d4277021-2f6f-4cd9-a629-fa8800a0e886.png) | ![ipfs-page-info-2](https://user-images.githubusercontent.com/387249/146978758-222e5b63-dcd9-46de-bd6f-876f7304c6ba.png)
