### ISSUE TITLE
State-level ads targeting dropdown is shown for the non-US region in brave://settings/rewards

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19589]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18158
State-level ads targeting dropdown is shown for the non-US region in brave://settings/rewards

## Steps to Reproduce

   1. Clean profile 1.33.x, OS is set to INDIA (stats level ads not supported country)
   2. Enable rewards and open brave://settings/rewards
   3. State-level ads targeting dropdown is shown for region India

## Actual result:

**brave://settings/rewards**
![image](https://user-images.githubusercontent.com/38657976/142626468-10877d9a-0e79-4783-bdff-af125f440301.png)

**brave://rewards/**
![image](https://user-images.githubusercontent.com/38657976/142626582-18de9b3d-bda9-468f-8926-f7fc6d35f73d.png)

## Expected result:
State-level ads targeting dropdown should be shown only for US region

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.83 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1348)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @Miyayes

**Comment by emerick** [comment]
@GeetaSarvadnya Does it work properly on brave://rewards?

**Comment by GeetaSarvadnya** [comment]
@emerick Sorry for the typo error corrected step1. My OS locale is set to India (not US) and I haven't changed locale in the browser. It works properly in brave://rewards, when OS locale is India, I don't see state-level target dropdown in Ads settings.

**Comment by LaurenWags** [comment]
`QA/Blocked` until new 1.33.x (1.33.96 or above)

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, 1.33.98 is available.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.33.98 Chromium: 96.0.4664.55 (Official Build) (64-bit)
-- | --
Revision | 38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}
OS | Windows 10 Version 21H2 (Build 19044.1387)

```
Confirmed state-level ad targeting dropdown isn't shown for the non-US region **`India`**

**`brave://settings/rewards`** | **`brave://rewards/`**
-----------------------------|---------------------------------


Confirmed state-level ad targeting dropdown is shown only for **`US`** region

**`brave://settings/rewards`** | **`brave://rewards/`**
-----------------------------|---------------------------------
![image](https://user-images.githubusercontent.com/38657976/144486363-61ce2b8a-fb19-4584-bd3b-9616b2a67583.png) | ![image](https://user-images.githubusercontent.com/38657976/144486391-400efe1f-cb9c-4988-8a68-4557a1b59c49.png)
