### ISSUE TITLE
`Default` option in the `Monthly auto-contribution limit` dropdown doesn't serve any purpose

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19585]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18158
`Default` option in the `Monthly auto-contribution limit` dropdown doesn't serve any purpose

Select `Default` in the `Monthly auto-contribution limit` dropdown in the brave://settings/rewards page doesn't make any changes in the brave://rewards `Auto contribution` advanced settings. By default `Monthly auto-contribution limit` 1 BAT will be selected in brave://rewards. Set Upto 5.000 BAT in `brave://rewards` and select `Default` in `brave://settings/rewards` will set the value to default  upto 1.000 BAT in `Auto contribution` advanced settings in `brave://rewards`

The Option `Default` and `Upto 1.000BAT` serve the same purpose, better to remove it from brave://settings/rewards page to avoid confusion.

## Steps to Reproduce

   1. NA
   

## Actual result:

**brave://settings/rewards** | **brave://rewards/**
-----------------------|-----------------------
![image](https://user-images.githubusercontent.com/38657976/142594858-86019135-b7b5-466c-a6e3-a32b563fbd4f.png) | ![image](https://user-images.githubusercontent.com/38657976/142594982-9fb9a054-9695-4eaa-8874-83ec92a1dc49.png)

## Expected result:

Remove `Default` option in the `Monthly auto-contribution limit` dropdown from brave://settings/rewards
## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.83 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1348)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @Miyayes

**Comment by emerick** [comment]
The background on this is that when you enable Rewards on a clean profile, the preference for auto-contribution limit is set to 0 which is not one of the valid AC choices. Our C++ code has logic to use 1 in this specific scenario (i.e., when the preference is 0). I'm not sure why it was done this way (it might be a backwards-compatibility hack or something similar) and was a little reluctant to change it.

In Chromium, settings are tied to preferences. When displaying choices in a dropdown menu, if the currently selected choice isn't represented then Chromium will auto-insert an item for it and name it "Custom". So, to avoid this situation, we must have an item for 0 and we chose to name it "Default".

I think that maybe (haven't tested it yet) we could work around this by having the entry 0 map to the text "1". This would be a bit confusing in the code and would also mean that the value `1` would never be written to the preference file. It feels a little weird to do that, but we could if it's important enough. Personally, I would say that having a `Default` option is a bit cleaner and more maintainable and matches what we already have to do for the other Rewards dropdowns for Ads.

cc: @Miyayes, just FYI
