### ISSUE TITLE
pdfium not fully blocked on Linux

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#1958]
STR:

1. try the repro steps from https://github.com/brave/brave-browser/issues/1788 on Linux
2. notice that instead of prompting you to download the PDF, it loads in Chrome's PDF viewer (pdfium)

**Comment by darkdh** [comment]
<img width="481" alt="screen shot 2018-11-01 at 10 49 00" src="https://user-images.githubusercontent.com/11330831/47881788-6b765800-dde4-11e8-85af-e61cc26e92de.png">
<img width="908" alt="screen shot 2018-11-01 at 10 58 38" src="https://user-images.githubusercontent.com/11330831/47881789-6b765800-dde4-11e8-8b7f-713b3d4b8170.png">
component is also showing enable in both `brave://extensions` and `brave://net-internals/#modules`

**Comment by yrliou** [comment]
Seems like it is not always happening because I could not reproduce it on 0.55.22 using Ubuntu 18.04. Chromium PDF Viewer is disabled for me and the STR would prompt me to download the PDF.

**Comment by bbondy** [comment]
Can anyone reproduce this with c71 and beyond?

**Comment by diracdeltas** [comment]
It was repro'ed by anonymous on Linux with 0.55.x master

**Comment by kjozwiak** [comment]
I can't reproduce the behaviour @diracdeltas mentioned in the original comment. Every time I load `http://localhost:9001/type.pdf`, I'm getting the following notification:

<img width="1103" alt="screen shot 2018-11-26 at 12 33 21 am" src="https://user-images.githubusercontent.com/2602313/48994828-2b6c7180-f113-11e8-8671-fc7ac2fcce5d.png">

However, `Chromium PDF Viewer` doesn't seem to be disabled under `brave://extensions`:

<img width="1104" alt="screen shot 2018-11-26 at 12 33 29 am" src="https://user-images.githubusercontent.com/2602313/48994839-44752280-f113-11e8-91ea-9de4570a0146.png">

Used the following build:

Brave | 0.57.7 Chromium: 71.0.3578.53 (Official Build) beta (64-bit)
--- | ---
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Linux

Platforms checked:

* `Ubuntu 18.04 x64` & `Fedora 29 x64`

**Comment by kjozwiak** [comment]
This is what I'm seeing when using `0.57.7 Chromium: 71.0.3578.53` under `Ubuntu 18.04 x64 VM`:

![linuxpdf](https://user-images.githubusercontent.com/2602313/48997466-0e896b80-f11e-11e8-9804-d7b86dcd3bd7.gif)

What basically happens is that when I initially authenticate, it uses `Chrome's PDF viewer (pdfium)`, however re-loading it again after the authentication loads the PDF within PDFJS. `Chrome's PDF viewer (pdfium)` seems to be enabled under `brave://extensions` as well.

**Comment by diracdeltas** [comment]
@yrliou based on what @kjozwiak posted above, it appears the original bug is still in c71

**Comment by bbondy** [comment]
upping this to p2

**Comment by fmarier** [comment]
Based on https://github.com/brave/brave-core/pull/980#issuecomment-453213508, I don't think we can disable PDFium entirely. I'll have to dig into why it gets picked up for PDFs behind auth.

**Comment by fmarier** [comment]
By following [the repro steps](https://github.com/brave/brave-browser/issues/1788#issue-372773910), I was able to see PDFium in these versions:

- Version 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta (64-bit)
- Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

but not in these ones:

- Version 0.58.9 Chromium: 71.0.3578.53 (Official Build) dev (64-bit)
- Version 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
- Version 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)

So as far as I can tell, this problem was fixed in 0.58.

**Comment by srirambv** [comment]
Moving to `Not actionable` milestone as its already fixed and release channel migration has already completed.
