### ISSUE TITLE
shields should deeplink to brave://settings/shields

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#1959]
there should be a route for there instead of linking to brave://settings/ only

this is a 2-step work:

* add route for shields inside brave://settings: https://github.com/brave/brave-core/pull/785
* add link for that route in brave-extension https://github.com/brave/brave-extension/pull/80

**Comment by bsclifton** [comment]
Updated to be 0.58.x after DEPS was updated with https://github.com/brave/brave-core/pull/820

PR is tagged with uplift-request; let's make sure to modify milestone if that is approved 😄

**Comment by btlechowski** [comment]
Verification Passed on

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (32-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Windows 7

`brave://settings/shields` worked
