### ISSUE TITLE
The list to disconnect addresses is too small, show more than 2 addresses

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19596]
Feedback from:
https://old.reddit.com/r/brave_browser/comments/qwovh0/my_feedback_about_new_brave_wallet/

<img width="373" alt="Screen Shot 2021-11-19 at 10 40 17 AM" src="https://user-images.githubusercontent.com/831718/142649988-3e9416a4-e91b-4edc-bded-1b459bf148ae.png">

**Comment by Douglashdaniel** [comment]
Was addressed in this PR https://github.com/brave/brave-core/pull/11486
Closing as `duplicate`
