### ISSUE TITLE
Make it easier to connect multiple accounts to a single Dapp

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19598]
Currently the only way to change the connected account list for a Dapp is to:
i) Disconnect all accounts and request permission again from the site
ii) Lock the wallet after connecting a single account and request permissions again from the site

We should have some easier way in the panel to connect even without the Dapp requesting it.

**Comment by Douglashdaniel** [comment]
Was addressed in this PR https://github.com/brave/brave-core/pull/11486
Closing as `duplicate`
