### ISSUE TITLE
Some tokens have balance of 0

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19600]
From https://old.reddit.com/r/brave_browser/comments/qwovh0/my_feedback_about_new_brave_wallet/

> I noticed that some tokens (like uni but there are others, Uniswap is not such an exotic token) had a value of 0$ that makes the wallet balance unusable

**Comment by Douglashdaniel** [comment]
https://github.com/brave/brave-browser/issues/19574 is related.

**Comment by bbondy** [comment]
This was fixed server side. The problem was that CG had many different symbols matching our requests. We dedupe based on the name in our list now.
