### ISSUE TITLE
[Android] Change onboarding default Auto-Contribute values (Nov 2021)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19608]
## Description

In onboarding, default A-C amounts should be: 1, 2, 3, 5, with 1 selected as default.

See desktop for comparison:

![image](https://user-images.githubusercontent.com/11497541/142668371-ea842daa-204d-4811-aec8-376e9ba9b703.png)

**Comment by LaurenWags** [comment]
@deeppandya this issue needs a milestone so it can be tested by @brave/legacy_qa

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.35.89, Chromium 97.0.4692.71` on a `Google Pixel XL` running `Android 9.0.`

### Steps:

1. install 1.35.89
2. launch Brave
3. tap continue
4. tap through onboarding
5. tap on the BAT icon
6. tap `Start using Brave Rewards`
7. tap `Let's take a quick tour >`
8. tap `Next >` until you get to the 7th slide
9. look at the default BAT amount

* Confirmed `1 BAT` is the default, with `2 BAT`, `3 BAT`, and `5 BAT` as the remaining options
* Also tested changing the default amount, and ensured it persisted after dismissing the onboarding tour.

default 1 BAT, tour | 3 BAT, tour | 3 BAT, persisted
---------|---------|-------------
![Screenshot_20220120-132034](https://user-images.githubusercontent.com/387249/150424135-228bb13c-e3ee-4dc7-8a54-9efa13e92e23.png) | ![Screenshot_20220120-132043](https://user-images.githubusercontent.com/387249/150424160-cdf07990-367e-4067-b6a0-3d963c8dec05.png) | ![Screenshot_20220120-132058](https://user-images.githubusercontent.com/387249/150424204-fa7f0077-887f-4585-80eb-fa69f79abcd3.png)
