### ISSUE TITLE
eth_sendTransaction should check keyring support when deciding to create EIP1559 or legacy tx

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19617]
A follow-up issue from https://github.com/brave/brave-core/pull/11187.
Trezor currently doesn't support EIP1559 tx even when the network supports it, so we should check keyring support too as we do in https://github.com/brave/brave-core/blob/d170d9038927102d88450d965abff41e3835a3fa/components/brave_wallet_ui/common/async/handlers.ts#L267-L297

**Comment by yrliou** [comment]
The manual test plan here should be tested after https://github.com/brave/brave-core/pull/11229 landed.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Polygon Mainnet
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143401877-44e20b2a-1d38-4538-a7e4-7cdafb386891.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143407152-395d9f24-dc15-4c8f-9f99-07431bbaa08b.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143396639-f419f486-01a5-49ef-b3ae-f10fb7ac0c0f.mov>
      </td>
   </tr>
   <tr>
      <td>Software Keyring
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143401830-d0a1869a-4db3-4f9e-bcf8-390ac7b84e01.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143407033-1b508bd6-a309-4568-a9f7-d3b22083d716.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143396589-1036fd85-1b94-4d8c-b936-de4b158edd97.mov>
      </td>
   </tr>
   <tr>
      <td>Ledger Keyring
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143401865-0a5d979a-a9ae-4b56-a324-af977dc8e5e7.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143407082-fecdfb4c-a1bb-472f-9f21-196f771cb229.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143396530-c1b37f0b-2f67-4b34-a641-1a46f769b4ee.mov>
      </td>
   </tr>
   <tr>
      <td>Trezor Keyring
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143401884-48fab4f4-d40f-4790-8609-4221d0a08b8e.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143407221-98a96de0-b4d2-4a54-bdab-8cc6d250b985.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143396659-33b7cd8d-e8b0-4cd1-875a-4bffd6509a1e.mov>
      </td>
   </tr>
</table>

**Comment by bbondy** [comment]
Changed this one to `release-notes/include` since a lot of users were affected by this, they would be interested to know it is fixed. I changed the title to `Fixed wrong transaction type sometimes being used for EVM compatible networks ` to make it easier to understand.
