### ISSUE TITLE
Brave wallet: cannot add more than 3 secondary accounts using private key import

### ISSUE THREAD

**Issue by markrtgh** [brave/brave-browser#19619]
## Description 

Can only add 3 secondary ethereum accounts in Brave wallet using private key import

## Steps to Reproduce

   1. Import 3 separate accounts using private key import
   2. Attempting to add a 4th ethereum account using private key import results in an error message "Failed to import account, please try again"
   3. Can add a 4th ethereum account using a hardware wallet but not by using a private key

## Actual result:

Error message "Failed to import account, please try again"

## Expected result:
Successful import of more than 3 ethereum accounts using private keys

## Reproduces how often: 

Easily reproduced

## Brave version (info found on brave://version)

Brave	1.32.106 Chromium: 96.0.4664.45 (Official Build) (arm64)
Revision	76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS	macOS Version 12.0.1 (Build 21A559)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the dev channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards?  N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

Using the Crypto Wallets (depreciated) can add more than 3 accounts using private key import

**Comment by bbondy** [comment]
Is it possible that this is related to the particular key you're trying to import and not related to being the 4th? 
Perhaps for example you could try on a new profile to import it into a new wallet first.

**Comment by bbondy** [comment]
Closing as there was no response. I don't think there is a limit of 3 and I checked with Anthony T. on this too.
