### ISSUE TITLE
Fix patches changes for Chromium 96.0.4664.45

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#19611]
Due to this issue https://github.com/brave/devops/issues/6358 with the Chromium update job, the upgrade from Chromium 96.0.4664.35 to Chromium 96.0.4664.45 (https://github.com/brave/brave-core/pull/11020) did not commit patches changes correctly.

Correct patches need to be committed into the repository and the strings rebase script needs to be rerun.

QA:

Please, check Android Wallet settings for correct strings around wallet auto-lock timing.

**Comment by LaurenWags** [comment]
Nothing to check on desktop per: https://bravesoftware.slack.com/archives/C7VLGSR55/p1637678173462600
