### ISSUE TITLE
Install error with M1 chip with Brave and Brave Beta:  "brave browser quit unexpectedly"

### ISSUE THREAD

**Issue by sobopla** [brave/brave-browser#19628]
Yes - it is unanswered. 
## Description 
error message: `brave browser quit unexpectedly upon install on Mac 2021 with M1 chip.`

## Steps to Reproduce

   1. Install Brave or Brave beta on Mac OS Monterey 12.0 and 12.01 for M1 chip on system with M1
   2. Open Brave
   3. Get error alert

## Actual result:
alert displays with `brave browser quit unexpectedly`

<img width="238" alt="Screen Shot 2021-11-20 at 11 26 37 AM" src="https://user-images.githubusercontent.com/19863639/142735719-fde20082-cb7e-4a7d-8e7d-908165be81c8.png">

## Expected result:
Brave browser opens

## Reproduces how often: 

Every time Brave or Brave beta is downloaded and opened. 

## Version/Channel Information:

n/a
- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:
n/a
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by coupeborgward** [comment]
yep same here. Installs fine but when starting it crashes.

**Comment by seanarmstrong87** [comment]
Same for me on M1 Pro

**Comment by KombangkoeDias** [comment]
same, has to use the intel version, quite slow please fix

**Comment by falcon4ever** [comment]
Just tried to install it on a new M1 Max / 12.1 and the latest m1 build won't work for me.

**Comment by GraveyardEnthuisast** [comment]
Had the same problem after buying my mac. Found a solution. Open terminal and type sudo rm -rf ~/Library/Application\ Support/BraveSoftware

From: https://githubmemory.com/repo/brave/brave-browser/issues/18618
https://community.brave.com/t/cannot-open-browser-on-mac-m1-bigsur-11-6/294338/24?u=runoe

**Comment by bsclifton** [comment]
Hi folks - there hasn't been an update in 2 years. I'm going to close this out - but please re-open or add details here if this still happens. Maybe you are in the future and you found this page via search engine 😄
