### ISSUE TITLE
revvracing.com (dapp on Polygon) shows a blank black screen when using Brave native Wallet

### ISSUE THREAD

**Issue by yusufg-git** [brave/brave-browser#19624]
## Description 

revvracing.com (dapp on Polygon) shows a blank black screen when using Brave native Wallet,  ie 
Settings->Wallet->Default cryptocurrency wallet-> Brave Wallet

## Steps to Reproduce

   1.  Launch Brave Browser
   2.  Use native browser wallet Settings->Wallet->Default cryptocurrency wallet-> Brave Wallet
   3. Visit https://revvracing.com/
   4. You will observe a black screen
   5. Use Metamask Extension Settings->Wallet->Default cryptocurrency wallet -> Brave Wallet (prefer extensions)
   5. restart browser
   6.  You will see the site normally

## Actual result:

<img width="1328" alt="Screenshot 2021-11-20 at 4 25 39 PM" src="https://user-images.githubusercontent.com/63719184/142719801-c0ef5da6-376e-4641-82c2-bf593c771da3.png">

## Expected result
<img width="1311" alt="Screenshot 2021-11-20 at 4 24 04 PM" src="https://user-images.githubusercontent.com/63719184/142719743-ad90b92e-8a1c-4802-97c3-aedb329378fc.png">

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (arm64)
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 11.6 (Build 20G165)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?      yes
- Can you reproduce this issue with the nightly channel?   yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  no
- Does the issue resolve itself when disabling Brave Rewards?  no
- Is the issue reproducible on the latest version of Chrome?   no

**Comment by bbondy** [comment]
Looks like it's using something we don't expose currently `removeAllListeners`

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified page loads correctly when default provider is set to "Brave Wallet"</li>
         <li>Verified able to connect wallet to dapp without any issues</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143392499-880977d4-3de5-42ae-820b-5d4b289f28ea.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143392205-9f72ed0d-bdcf-42d9-bfe6-6738e990e0dc.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143392237-b444326d-a547-4ffc-995b-1744247b6766.mov>
      </td>
   </tr>
</table>
