### ISSUE TITLE
Can't enable Ads while offline, from brave://rewards page

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19620]
## Description 

Can't enable Ads while offline, from brave://rewards page

## Steps to Reproduce

1.  new profile
2. launch Brave
3. disconnect from Wi-Fi/internet
4. load `brave://settings`
5. click on `Brave Rewards` in the left pane
6. click on the right pane to enable `Brave Private Ads`
7. click `Skip for now`
8. click `Continue`
9. click `Done`
10. dismiss the panel
11. load `brave://rewards`
12. try to toggle `Ads` to `On`

## Actual result:

![fun-one](https://user-images.githubusercontent.com/387249/142710217-8554871d-9f47-495c-b7d2-7b07f0ad5312.gif)

## Expected result:

Should be able to enable `Ads`, as you can from `brave://settings`, while offline

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.33.51 Chromium: 95.0.4638.69 (Official Build) nightly (64-bit)
--|--
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Linux

**Comment by tmancey** [comment]
@emerick your thoughts on the above please? Thanks

**Comment by emerick** [comment]
@tmancey I wasn't aware of that. So I take it then that the bug is we're allowing ads to be enabled from brave://settings/rewards?

**Comment by tmancey** [comment]
@emerick see above screenshot, as "Brave private ads" are not enabled for me when following the above steps. So for me, this is working as expected

**Comment by tmancey** [comment]
@stephendonner ah so yes I missed the last step where you enabled "Brave private ads" from brave://settings/rewards. @emerick a user should not be able to enable ads unless they have an internet connection.

**Comment by emerick** [comment]
OK, got it.

**Comment by tmancey** [comment]
If we allow users to enable rewards/ads without an internet connection, they will see a lot of -1 errors in the logs.

**Comment by emerick** [comment]
Is it me or does this behavior only work on Mac? After disabling WiFi on Windows, Ads is still allowing me to enable/disable itself at will.

**Comment by stephendonner** [comment]
> Is it me or does this behavior only work on Mac? After disabling WiFi on Windows, Ads is still allowing me to enable/disable itself at will.

Just you 😉 

![windows](https://user-images.githubusercontent.com/387249/142889920-e906923e-6e01-44aa-8f8c-dc709bc75940.gif)

**Comment by tmancey** [comment]
I have seen inconsistencies with Chromium detecting Windows network connections.
