### ISSUE TITLE
[Android] Update "Disconnect from Brave Rewards" text to be "Disconnect from {{custodian_name}}"

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19627]
Android version of https://github.com/brave/brave-browser/issues/19626. 

_____________

## Description

When users go to disconnect their Brave Rewards wallet from their custodian (Uphold/Gemini/bitFlyer) and return to an unverified state, change the text to be "Disconnect from {{custodian_name}}", as suggested by @bbondy. 

![image](https://user-images.githubusercontent.com/11497541/142735284-8fd1de63-3a37-47cc-a861-e01caacf28c3.png)

## Solution

Change the text to be "Disconnect from {{custodian_name}}".

**Comment by deeppandya** [comment]
@Miyayes this would be relevant issue with rewards 2.5.

**Comment by Miyayes** [comment]
No longer relevant in 1.48.x.
