### ISSUE TITLE
Implement `personal_ecRecover` - signing to unlock L2 Looping account fails

### ISSUE THREAD

**Issue by markrtgh** [brave/brave-browser#19621]
## Description 

Unlocking an ethereum account on L2 loopring requires a signature. Signing fails using Brave Wallet but succeeds using Crypto Wallets (depreciated).

## Steps to Reproduce

   1. Use an ethereum account previously used to connect to L2 Loopring [https://loopring.io/#/layer2](https://loopring.io/#/layer2)
   2. Connect account by following prompts and selecting Metamask. Connection successful.
   3. Attempt to unlock account. Window pops up requesting signature. Press sign button.

## Actual result:

After pressing sign button Result is "Unlock failed"

## Expected result:
Successful signing and account unlocking which occurs when using Crypto Wallets (depreciated)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave	1.32.106 Chromium: 96.0.4664.45 (Official Build) (arm64)
Revision	76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS	macOS Version 12.0.1 (Build 21A559)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel?  Not tested 
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Signature window for Brave wallet displays the same information as  the Crypto Wallets (depreciated) window popup but signing fails for the Brave wallet  but succeeds with Crypto Wallets (depreciated).

**Comment by bbondy** [comment]
Any errors in the console? I wonder if it's trying to use sign typed data which will be supported in 1.33.x

**Comment by Fillicia** [comment]
Only error I can see in the console is that it throws 

`[Violation] 'setTimeout' handler took 55ms main~402f6fec.289c83e0.chunk.js:2`

as soon as you click unlock, then nothing when you sign the message other than failing site-wise

**Comment by darkdh** [comment]
can anyone show me how to trigger the sign message request? I didn't see "unlock" button on the website after connected.

**Comment by bbondy** [comment]
I also tried, I was able to do steps 1 and 2, but I'm not sure what to do in step 3. It seems like a step is missing between 2 and 3.

**Comment by Fillicia** [comment]
Sorry for the delay, it's a 2 step process for Loopring. You have to connect your wallet and then, on the "L2 Wallet" tabs, unlock it if you want to manage your assets. The unlock part is only if you have an active loopring account.

![Screenshot from 2021-12-09 08-46-33](https://user-images.githubusercontent.com/42915622/145408553-a36647ee-8a49-4c52-8d2e-2c0b3679c448.png)
![Screenshot from 2021-12-09 08-46-47](https://user-images.githubusercontent.com/42915622/145408549-13073c0b-fa75-4849-b17c-74baec45acb8.png)
![Screenshot from 2021-12-09 08-46-52](https://user-images.githubusercontent.com/42915622/145408540-b922c1c8-b606-43e5-82af-528a3c14658c.png)

**Comment by bbondy** [comment]
Looks like we need support for `personal_ecRecover` which I think is used to verify a signature from `personal_sign`.

**Comment by bbondy** [comment]
https://www.rdocumentation.org/packages/gethr/versions/0.1.0/topics/personal_ecRecover

**Comment by srirambv** [comment]
@bbondy confirmed that this was verified. Marking the issue as `QA/No`

**Comment by bbondy** [comment]
This is live on today's release.
