### ISSUE TITLE
Give Shields its own icon

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1962]
In @karenkliu's interviews, it transpired that a lot of folks think that the Brave lion icon is just branding. The addition of a notification number and (eventually) other discovery indicators should improve this. But maybe Shields just needs its own icon? Maybe a shield?

**Comment by NumDeP** [comment]
No way, leave it the way it is. 

I was going to create an issue sort of related to this but I'll just post it here instead to read what you thoughts are on it further, which is to say the counts beside the widgets/icons in url bar should be adjusted slightly. Both icons displaying counts inside url bar can seem too small. the icons themselves are alright but I feel the counts can be ever so slightly larger as well as being a little to the south-east. There seems to be some space available on the right so as not to infringe on the space of the BAT icon and the suggestion of moving them slightly is considered, perhaps the size of those counts can be slightly enlarged, slightly.

Brave is practically advertised as an Ad&Track blocking browser, it's clearly obvious that the count has to be somewhere visible. Beside, the team is doing a brilliant job making the default settings the standard, so it shouldn't really be a worry to new users considering nothing really needs to be changed and if it was changed it would most likely break some/many sites.

**Comment by tomlowenthal** [comment]
@BrendanEich says we are absolutely not doing this. So that's an easy conversation.

**Comment by bbondy** [comment]
Marking not actionable / invalid milestone since this is closed without a fix.
