### ISSUE TITLE
npm run build errors

### ISSUE THREAD

**Issue by roman-cook** [brave/brave-browser#19632]
## Description 
Just trying to build the Brave android apk on my **Mac OS Catalina 10.15.7**
All prerequisites are installed as in the instructions.

## Steps to reproduce 

1. npm run build -- Debug --target_os=android --target_arch=arm 

## Actual result 
ERROR at //build/util/version.gni:73:11 (//build/toolchain/mac:clang_x64): Script returned non-zero exit code.
_result = exec_script("version.py",

## Expected result
Successful build 
## Issue reproduces how often 
Easily reproduced

**Comment by SergeyZhukovsky** [comment]
@roman-cook Android build under mac OS isn't supported. We support Linux only.
