### ISSUE TITLE
 installing extensions from Chrome Web Store results in "Not from Web Store" warning on extensions page

### ISSUE THREAD

**Issue by jcraig999** [brave/brave-browser#19637]
## Description
Whenever I Install an extension from the Chrome Web Store, Brave comes back with a warning on the extensions page saying it is not from the web store. I'm concerned that I may not receive automatic updates from my extensions because of this.

## Steps to Reproduce

   1. Go to Chrome Web Store
   2. Download an extension
   3. Check brave://extensions/ and it says the extension is not from the web store

## Actual result:
![Extensions Page](https://images2.imgbox.com/7d/e6/cOHVdS4G_o.png)
![Not from Web Store](https://images2.imgbox.com/85/ac/o1wJOQTx_o.png)

## Expected result:
To not receive not from Web Store warning on extensions page

## Reproduces how often: 
Every time an extension is installed

## Brave version (info found on brave://version)

Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 10.15.7 (Build 19H1519)
JavaScript | V8 9.6.180.12
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=LegacyTLSEnforced,PrefetchPrivacyChanges,SafetyTip,AutoupgradeMixedContent,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity --disable-features=IdleDetection,AppDiscoveryRemoteUrlSearch,InterestCohortAPIOriginTrial,AdInterestGroupAPI,ComputePressure,ConversionMeasurement,InterestGroupStorage,WebSQLInThirdPartyContextEnabled,AutofillServerCommunication,TabGroupsFeedback,Parakeet,Fledge,NetworkTimeServiceQuerying,SubresourceWebBundles,TrustTokens,DirectSockets,Prerender2,SpeculationRulesPrefetchProxy,ReportAllJavaScriptFrameworks,InterestCohortFeaturePolicy,CopyLinkToText,WebOTP,NotificationTriggers,NavigatorPluginsFixed,SignedExchangeSubresourcePrefetch,AutofillEnableAccountWalletStorage,FirstPartySets,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,ReadLater,TextFragmentAnchor,FederatedLearningOfCohorts,LiveCaption --flag-switches-begin --disable-features=IdleDetection,AppDiscoveryRemoteUrlSearch,InterestCohortAPIOriginTrial,AdInterestGroupAPI,ComputePressure,ConversionMeasurement,InterestGroupStorage,WebSQLInThirdPartyContextEnabled,AutofillServerCommunication,TabGroupsFeedback,Parakeet,Fledge,NetworkTimeServiceQuerying,SubresourceWebBundles,TrustTokens,DirectSockets,Prerender2,SpeculationRulesPrefetchProxy,ReportAllJavaScriptFrameworks,InterestCohortFeaturePolicy,CopyLinkToText,WebOTP,NotificationTriggers,NavigatorPluginsFixed,SignedExchangeSubresourcePrefetch,AutofillEnableAccountWalletStorage,FirstPartySets,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,ReadLater,TextFragmentAnchor,FederatedLearningOfCohorts,LiveCaption,NativeBraveWallet --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/josh/Library/Application Support/BraveSoftware/Brave-Browser/Default
Linker | lld
Variations | AdRewardsStudy:NextPaymentDayAdServingStudy:MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=8/MaximumInlineContentAdsPerDay=40AdvertiserSplitTestStudy:GroupBBraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5BraveTalkStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledMacCoreLocationBackendStudy:EnabledNativeCosmeticFilteringStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:DefaultPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Disabled

**Comment by bsclifton** [comment]
Thanks for the report @jcraig999! This has already been captured with https://github.com/brave/brave-browser/issues/19069 and will be fixed in an upcoming release (this week)
