### ISSUE TITLE
Brave freezing my PC?

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#19631]
## Description 
The whole system freezes all of a sudden for 3-5 seconds. Then, black screen (1-2seconds) followed by unfreeze. If the tab is playing video, it needs to be re-opened otherwise it will not load.

In event viewer, I found this message appearing at the time of freeze: - may or may not be related. ?
**Display driver igfx stopped responding and has successfully recovered.**

## Steps to Reproduce

Unknown! But happens only when using brave, I think.

## Reproduces how often: 
1 time today
2 times yesterday

## Brave version (brave://version info)

<html>
<body>

Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1348)

</body>
</html>

## Other Additional Information:

the freeze appears to by system-wide, not just the browser. (mouse works but can't interact with anything). Happens ONLY on my second laptop ( X1 carbon , lenovo), never happened on my other PC. To date it mustve been ~20 times it has happened, but I still dont know for sure if Brave is causing it.
So far Ive tried reinstalling gpu drivers & scanning sfc for system errors + windows update, no difference

**Comment by rebron** [comment]
@pilsnerbeer When you get a chance can you go to brave://crashes and send the report there and past the crash id into this issue?

**Comment by rebron** [comment]
Could you also disable hardware acceleration brave://settings/system and see if that helps?

**Comment by pilsnerbeer** [comment]
@rebron I see 'Crash reporting is not available in Brave.' on brave://crashes/ - do I need to enable it somehow?

**Comment by iefremov** [comment]
Crash dumps will not help in this situation. @pilsnerbeer have you tried this in Chrome or other browsers?

**Comment by pilsnerbeer** [comment]
@iefremov No, unfortunately I wasn't able to replicate this issue when using other browsers (firefox). The issue last happened yesterday and once again, I was interacting with Brave during that time.
