### ISSUE TITLE
Feature request: Ethereum test networks

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#19636]
It might be good to add testnets in addition to the built-in brave wallet.

- Görli
- Rinkeby
- Ropsten
- Matic
- etc...

**Comment by srirambv** [comment]
You have Goreli/Ropsten/Rinkeby/Kovan available by default. You can also add custom chains via `brave://settings/wallet/networks` 

![image](https://user-images.githubusercontent.com/17010094/143256926-fcdc7c40-4d91-4d19-87c9-d0f75500500f.png)
