### ISSUE TITLE
Option to delete on download bar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1963]
## Description 

Originally reported  here https://community.brave.com/t/delete-a-download-from-the-download-bar/36456

> One of the best features of the original Brave browser was the ability to delete downloads from the download bar so that you could keep track of active downloads without opening the download page. Would love to see this feature re-added to the new browser/dev build.

## Actual result:

No option to delete from download bar

## Expected result:
Provide option to delete from download bar

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

**Comment by SilverPuppy** [comment]
I miss this feature as well. I only just migrated to this version from the old -laptop build, and I immediately; missed this feature.

Also, I dislike the fact that the settings page is like Chrome. The old -laptop settings page was better.

**Comment by SilverPuppy** [comment]
@bsclifton You closed this as completed, but it is not completed. I would say that as long as it has been and this feature is still not implemented no one cares to do it, but users were promised feature parity with the Muon builds, and refusing to implement it ever is a broken promise. Color me disappointed. This was one of my favorite features.

**Comment by SilverPuppy** [comment]
@srirambv You originally opened this, and it would be interesting to know if this is still important to you, as it is to me.
