### ISSUE TITLE
eth_requestAccounts should return no accounts when locked

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19641]
`eth_accounts` is not returning accounts to sites with permissions when the keyring is locked
`eth_requestAccounts` is returning the accounts. We should make this consistent.

#test plan
Use https://github.com/bbondy/eth-manual-tests to test that 
1) `eth_accounts` does not return connected accounts when the wallet is locked
2) `eth_requestAccounts` asks to unlock and then if you unlock returns the accounts

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 height=800 src=https://user-images.githubusercontent.com/17010094/149354367-1c006dd5-91ae-4831-b459-e399010c2fbc.mp4>
      </td>
      <td><video width=1200 height=800 src=https://user-images.githubusercontent.com/17010094/149354272-4865fdd7-0dd6-459d-91b7-b6465612ce66.mov>
      </td>
      <td><video width=1200 height=800 src=https://user-images.githubusercontent.com/17010094/149353937-a00c3930-6e1c-4cba-ab46-53c721a4fba9.mov>
      </td>
   </tr>
</table>
