### ISSUE TITLE
Use custom images for NTP Background

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19640]
This is sub task of https://github.com/brave/brave-browser/issues/15252

Overall design is described in https://github.com/brave/brave-browser/issues/15252.

* Specification
  * Custom image is per-profile configuration
  * Uploaded image is stored only in local device
  * After uploaded, NTP shows uploaded images by default
    * NTP SI will be displayed together if user doesn't disable it
  * When user choose `Brave backgrounds` again after uploading custom image, stored image will be deleted

**Comment by simonhong** [comment]
Hmm, chromium's custom background image doesn't work from brave://new-tab-page
![image](https://user-images.githubusercontent.com/6786187/144964856-be30cc59-674b-4c06-9835-20ba076b24d2.png)

**Comment by simonhong** [comment]
Above issue was fixed. And our custom background option and chromium's should use same image.

**Comment by simonhong** [comment]
When user upload custom image, already opened NTP that shows SI image should not be affected.

**Comment by simonhong** [comment]
NTP SI(Sponsored Images) and NTP BI(Background Images) are browser-wide data.
but custom image should be per-profile configuration.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


Brave | 1.37.65 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1566)

### Steps:
1. installed `1.37.65`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize` on the lower right
5. chose `Upload from device`
6. confirmed the various images
7. restarted and confirmed they persisted after restart
8. chose `Brave backgrounds`
9. confirmed I could cycle through the various backgrounds

`clock.gif` | `clock.png` | `transparent-fire-gif.gif` | `lexus-is-350.jpg` | `Brave backgrounds (default)`
-----------|-------------|-----------------------|---------------|-----------------
![19640-2](https://user-images.githubusercontent.com/387249/155242414-7496ee01-1417-4ed1-8d63-5d5973f25734.png) | ![19640-3](https://user-images.githubusercontent.com/387249/155242431-b2f7ca13-5141-473d-a7da-87dd249d5731.png) | ![19640-4](https://user-images.githubusercontent.com/387249/155242445-32ddc920-1d00-41b9-bf16-13ce87234656.png) | ![19640-5](https://user-images.githubusercontent.com/387249/155242689-b3599f4a-fb7f-4885-9ee4-a0b9836c1ee7.png) | ![19640-6](https://user-images.githubusercontent.com/387249/155242704-a3195367-3836-409e-b8d7-340b779f3899.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.83 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/11622

<details>

### Default image is brave background

![image](https://user-images.githubusercontent.com/34715963/157137176-6921cb8c-17e5-46d4-975f-26977e3507fd.png)


### Custom image
Verified able to chose custom background

![image](https://user-images.githubusercontent.com/34715963/157137372-41166770-f713-4ae3-8af8-8ab5d036bb29.png)
![image](https://user-images.githubusercontent.com/34715963/157137426-1c94d641-bd9d-43db-b9fd-a75992cae586.png)

Verified NTP SI was shown
![image](https://user-images.githubusercontent.com/34715963/157137455-64c9c80c-3033-4194-904b-aee715b1c61e.png)

Verified able to go back to brave background:
![image](https://user-images.githubusercontent.com/34715963/157137564-3848d65d-54ca-4396-9790-c5fcd466fa54.png)

### Dark theme

![image](https://user-images.githubusercontent.com/34715963/157137818-1bc0381b-51fb-4ac0-9743-cd3918c3be19.png)


</details>

Logged: https://github.com/brave/brave-browser/issues/21518
