### ISSUE TITLE
`State-level ad targeting` isn't auto detected and not shown in `State-level ad targeting` dropdown in brave://settings/rewards

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19645]
## Description 

Found while testing #18158 
`State-level ad targeting` auto detected state is not showing up in brave://settings/rewards

## Steps to Reproduce

   1. Clean profile 1.33.x
   2. OS region is set to US
   3. Connect Protonvpn to US - FL state (Florida state)
   4. Launch brave with staging flags and enable rewards
   5. Open ads settings in brave://rewards
   6. `Auto-detected as Florida` is showing up in Ads settings but not in brave://settings/rewards

## Actual result:

`State-level ad targeting` auto detected state is not showing up in brave://settings/rewards

**`Brave://rewards`** | **`brave://settings/rewards`**
-------|--------
![image](https://user-images.githubusercontent.com/38657976/142861254-ac663b6f-32b8-4b68-b141-5cb8a6db3bc5.png) | ![image](https://user-images.githubusercontent.com/38657976/142861327-3cf90ea5-3fe1-42d4-8ecb-03be0ba980ea.png)

## Expected result:
`State-level ad targeting` auto-detected state should be shown in brave://settings/rewards

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.83 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1348)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @Miyayes

**Comment by emerick** [comment]
Just to clarify, it is doing the right thing (i.e., auto-detecting the state). It's just not reflecting the auto-detected state in the dropdown menu.

**Comment by GeetaSarvadnya** [comment]
@emerick State-level ad targetting is auto-detected only in brave://rewards ads settings page, not in brave://settings/rewards. Edited the title. Thanks!
