### ISSUE TITLE
Unable to approve cancel transactions

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#19642]
The transaction confirmation UI in the panel prevents the user from approving a cancel transaction because the sender and receiver addresses are the same. There's no such limitation at the protocol level, so we should remove such checks.

Additionally (to be discussed with team first), we should also allow zero-value transactions from the Send container, since they are valid EVM transactions.

See user bug report here: https://github.com/brave/brave-browser/issues/19536#issuecomment-975057496

Feature first introduced in https://github.com/brave/brave-browser/issues/19011.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (arm64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified test plan from [#11231](https://github.com/brave/brave-core/pull/11231)
- Verified able to approve cancel transactions and confirm on block explorer

https://user-images.githubusercontent.com/17010094/143383390-12f10dc0-e739-48f2-ab78-8bd65c3e6378.mov
