### ISSUE TITLE
New Brave Wallet not working with Ledger

### ISSUE THREAD

**Issue by cstrat** [brave/brave-browser#19643]
## Description 
I am able to add my ledger accounts to my wallet, this all works fine.
However when trying to execute a transaction it fails saying the ledger is disconnected.
I have tested this on both mac and PC, happens on both devices with my ledger.

![image](https://user-images.githubusercontent.com/4209076/142854646-a29662e6-edb1-4744-b53d-fd91a00152db.png)

## Reproduces how often: 
Since updating to the new wallet, I am unable to execute any transactions.
I have removed my accounts from the wallet and added them again (USB works fine for this).
Just interacting and executing contracts fails.

## Brave version (brave://version info)
- Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (arm64)
- Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

## Version/Channel Information:
- Ledger Ethereum App version 1.9.13

**Comment by srirambv** [comment]
Do you have the Ethereum app opened on Ledger? Also do you see the WebHID Prompt when you try to initiate a transaction?

cc: @spylogsster @onyb

**Comment by spylogsster** [comment]
should already be fixed in current nightly,  @cstrat can you try?

**Comment by cstrat** [comment]
I will try now, I disabled the Brave Wallet and installed the MetaMask extension to get by...

**Comment by cstrat** [comment]
Yeah it worked fine with the nightly build, it still prompts saying USB not connected, but then it does request access to the USB interface and the transaction can be authorised.

**Comment by cstrat** [comment]
Fixed in nightly...

**Comment by bbondy** [comment]
Awesome, thanks for letting us know!
