### ISSUE TITLE
Add Indications for Selected Network

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19651]
## Description 
Add Indications for Selected Network
1) Add a checkmark next to the `selectedNetwork` in the `SelectNetwork` dropdown list.
2) Add a hover `tooltip` to the `Select Network` button to display the full `selectedNetwork` name.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.34.68 Chromium: 97.0.4692.56 (Official Build) beta (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)
```

Reproduced the 2 items from https://github.com/brave/brave-browser/issues/19651#issue-1060321547 in 1.33.106, no indicator next to selected network in list and no hover tooltip on selected network button which shows full network name.

1.33.106 | 1.33.106 | 1.33.106
----- | ----- | -----
<img width="339" alt="1 33 1" src="https://user-images.githubusercontent.com/28145373/147000010-627d40f5-2bf6-43f7-9bc6-18d1841004ee.png"> | <img width="356" alt="1 33 2" src="https://user-images.githubusercontent.com/28145373/147000013-fd7858cc-b53f-4672-9786-67fc0ab3acb0.png"> | <img width="350" alt="1 33 3" src="https://user-images.githubusercontent.com/28145373/147000017-2a8db327-3753-4a0f-8cb4-1be14b2b84a9.png">

Verified the items from https://github.com/brave/brave-browser/issues/19651#issue-1060321547 and https://github.com/brave/brave-core/pull/11225#issue-1060620023.
Confirmed there is a checkmark indicator next to the selected network in the list.
Confirmed there is a hover tooltip on the selected network button which shows the full network name.

1.34.86 | 1.34.68 | 1.34.68
----- | ----- | -----
<img width="406" alt="1 34 1" src="https://user-images.githubusercontent.com/28145373/146999988-377dc195-b881-4dc6-b1e9-0a63adb1c852.png"> | <img width="359" alt="1 34 2" src="https://user-images.githubusercontent.com/28145373/146999993-57be11f4-2d32-44bc-b09a-323f9c73b070.png"> | <img width="365" alt="1 34 3" src="https://user-images.githubusercontent.com/28145373/146999996-0d631800-fbb4-4e0c-a157-dce84fd4415d.png">
<img width="272" alt="1 34 12" src="https://user-images.githubusercontent.com/28145373/147000035-ca8eaca0-1abf-4ac7-9817-db00650e15c0.png"> | <img width="351" alt="1 34" src="https://user-images.githubusercontent.com/28145373/147000124-0a7cc41a-fcf0-4edf-b771-99b92c2b6b81.png"> | <img width="370" alt="1 34 32" src="https://user-images.githubusercontent.com/28145373/147000048-e98f5f68-721a-4518-9bf6-3e8aac902c06.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified network selection and tool tip is shown for current selected network from the list

Portfolio network indicator | Widget network indicator | Panel network indicator | Portfolio Network Tooltip | Widget Network Tooltip | Panel Network Tooltip 
-- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/147941957-d15af7f5-11dc-481b-b13b-1ffc6a5c15c0.png) | ![image](https://user-images.githubusercontent.com/17010094/147941916-aba63fc6-5f59-418a-8c11-48a27ecb16d4.png) | ![image](https://user-images.githubusercontent.com/17010094/147942014-c0caa9f9-e11d-49cb-aa6f-5a9a1baeef97.png) | ![image](https://user-images.githubusercontent.com/17010094/147941834-ad6b02b4-a90b-422f-965c-55f8675382d2.png) | ![image](https://user-images.githubusercontent.com/17010094/147941860-2f9ce09d-45ea-4821-9af3-3e97048891a1.png) | ![image](https://user-images.githubusercontent.com/17010094/147941893-3158eb82-4e7f-4c97-a50e-ad3fe91ca785.png)

----------
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Linux

- Verified network selection and tool tip is shown for current selected network from the list

Portfolio network indicator | Widget network indicator | Panel network indicator | Portfolio Network Tooltip | Widget Network Tooltip | Panel Network Tooltip 
-- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/147945954-632d7693-f9b9-4258-a1c6-be0e8afdd753.png) | ![image](https://user-images.githubusercontent.com/17010094/147945962-76ee53fb-9404-4703-b499-11a19d4d7e1f.png) | ![image](https://user-images.githubusercontent.com/17010094/147945977-8bb2682f-2546-483c-bf5c-05318650e2ce.png) | ![image](https://user-images.githubusercontent.com/17010094/147945995-b4d1b4c0-a37f-4dbc-961b-37066f315ea2.png) | ![image](https://user-images.githubusercontent.com/17010094/147946008-2980b22a-ec68-402f-8745-65ff531907ef.png) | ![image](https://user-images.githubusercontent.com/17010094/147946068-06bd65ed-6826-4f95-a7ea-cd719930a8c7.png)
