### ISSUE TITLE
Brave heading should read Discounts in Brave News

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19658]
## Description 

"Brave" heading should read "Discounts" in Brave News

Found while testing https://github.com/brave/brave-browser/issues/18787

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. click on `Show Brave News`
   4. scroll down until you see the slew of Amazon items
   5. look at the heading title

## Actual result:

`beta` vs. `release`
![brave-discounts](https://user-images.githubusercontent.com/387249/142905349-0921909b-801f-4285-a6a1-6d649d79467f.png)

## Expected result:
Should read `Discounts`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.33.85 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 20H2 (Build 19042.1348)

cc @petemill

**Comment by stephendonner** [comment]
@mattmcalister @rebron we should address this soonish, yeah, esp. given it should be an easy string change?

**Comment by mattmcalister** [comment]
Closing as is irrelevant now
