### ISSUE TITLE
zapper.fi switch network is not working

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19656]
zapper.fi
Switch network via zapper.fi's menu on the bottom left corner doesn't seem to be working.

![image (5)](https://user-images.githubusercontent.com/831718/142903878-ece02d58-3e89-4145-86e2-e913c59a0f9a.png)
After selecting a network, it doesn't prompt to switch.

**Comment by bbondy** [comment]
This is because they only call `wallet_addEthereumChain` instead of `wallet_switchEthereumChain`.
To fix we’ll do like MetaMask and do a switch request instead of an add add request when a network is already added.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (arm64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified test plan from [#11222](https://github.com/brave/brave-core/pull/11222)
- Verified clicking on a network from the list, automatically prompts to add network and then switch network immediately
- Verified custom network is set as default afterwards and is also added to the list of custom networks in wallet settings

https://user-images.githubusercontent.com/17010094/143379461-efb9031d-08e3-4c49-a068-f19546214d93.mov


-------------
Verification passed on 

Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (arm64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Windows 11 Version Dev (Build 22504.1010)

- Verified test plan from [#11222](https://github.com/brave/brave-core/pull/11222)
- Verified clicking on a network from the list, automatically prompts to add network and then switch network immediately
- Verified custom network is set as default afterwards and is also added to the list of custom networks in wallet settings

https://user-images.githubusercontent.com/17010094/143379309-ac36a400-4bbc-4ae1-93e9-a4fb3b840f6e.mov


-------------
Verification passed on 

Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Linux

- Verified test plan from [#11222](https://github.com/brave/brave-core/pull/11222)
- Verified clicking on a network from the list, automatically prompts to add network and then switch network immediately
- Verified custom network is set as default afterwards and is also added to the list of custom networks in wallet settings

https://user-images.githubusercontent.com/17010094/143379430-342d9f58-faaa-4bfa-861c-d5a9deb3b70e.mp4
