### ISSUE TITLE
Add a menu item on the panel for viewing account on Etherscan

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19655]
Add a "View Account on Etherscan" option to this menu: 
<img width="320" alt="Screen Shot 2021-11-22 at 11 47 53 AM" src="https://user-images.githubusercontent.com/831718/142901554-acad608b-098c-4123-8e40-ad6b52f8c416.png">

Reported via the 4th point in https://community.brave.com/t/new-brave-wallet-missing-features/304532

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified new option is shown on panel to open link in block explorer</li>
         <li>Verified changing network loads the correct block explorer for that network</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=600 src=https://user-images.githubusercontent.com/17010094/143380222-0463d926-960f-4c1a-aae9-abcb9eba5f8b.png>
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/143380082-04db3093-1e04-4e9e-bd7d-bbc712d3f157.png>
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/143380119-341be4cb-46fd-4e79-a687-811cccf0a514.png>
      </td>
   </tr>
</table>
