### ISSUE TITLE
Fix console warning for ConnectWithSite Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19652]
## Description 
Getting a console warning from the `ConnectWithSite` panel when trying to connect to a site. 
Looks like it's missing a `key` in the account map list

![Screen Shot 2021-11-22 at 8 58 35 AM](https://user-images.githubusercontent.com/40611140/142894313-fdbf22f9-aae4-4c6c-b75f-a97610cca5c8.png)

**Comment by yrliou** [comment]
I changed to QA/No because I don't see the warning in nightly when trying to do `window.ethereum.enable()` but seeing it in my local build.
