### ISSUE TITLE
Weekly usage is showing up incorrect response when a week overlaps two months

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19653]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18254
Weekly usage is showing up incorrect response when a week overlaps two months
## Steps to Reproduce

    
1. Set the system date to 29th Nov
2. Create a wallet
3. Open brave://local-state and confirmed Daily/weekly/monthly metrics response value is 1 as expected
4. Close brave
5. Set the system date 1st Dec
6. Relaunch brave and verify brave://local-state
7. `Brave.Wallet.UsageWeekly` response value is `0` instead of `1`   - weekly usage stats collection starts from Monday, here 29th Nov is Mon and 1st Dec is Wed hence the weekly usage calculation should happen from 29th Nov to 5th Dec. So, I am expecting weekly usage as `1` but it's showing up zero.

## Actual result:

Weekly usage is showing up incorrect response when a week overlaps two months

## Expected result:
Weekly usage value should be `1`

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.83 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1348)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mattmcalister @rillian @porteron

**Comment by rillian** [comment]
Does this happen only when the week overlaps a month boundary, or is this explained by resetting the walled also resetting the weekly and monthly usage measurements, as in #18254?

**Comment by GeetaSarvadnya** [comment]
@rillian The issue happens when a week overlap  a month boundary in both normal scenario (https://github.com/brave/brave-browser/issues/19653#issue-1060357752) and reset wallet scenario (https://github.com/brave/brave-browser/issues/18254#issuecomment-972648315)

**Comment by iefremov** [comment]
cc @bbondy can you please triage as part of the wallet project?

**Comment by bbondy** [comment]
Yes but DAU and MAU are more important to us so I'd be ok with a low priority on this and it sitting for a while.

**Comment by srirambv** [comment]
@rillian, shouldn't all 3 values be set to 1 for the above? 

Daily should be set to 1 as wallet is accessed on a new day (Dec 1st)
Weekly should be set to 1 as wallet is access on the same week where two months overlap 
Monthly should also be set to 1 as the wallet is accessed on the 1st day of the month. 

I tried the following scenario and the values don't update accordingly

* Set date to Nov 30 
* Enable CW flag and create an account (account login changes all values to be set to 1)
* Close browser
* Set date/time to Nov 31 11:59 PM 
* Wait for the day/time roll over 
* Launch browser 
* Values for all 3 (daily/weekly/monthly) are set to 0 and doesn't update to 1

The above scenario only happened for CW and not for Brave Wallet

**Comment by HEagle18** [comment]
@bbondy @srirambv is this issue still relevant ?
