### ISSUE TITLE
Selected Network stays persisted after removing

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19668]
## Description 
A custom network will stay persisted as the `selectedNetwork` after removing from `brave://wallet/settings`

https://user-images.githubusercontent.com/40611140/142932467-93a6a12a-62f2-4d25-b90c-52e6c1d191f2.mov

**Comment by bbondy** [comment]
This PR makes it impossible to remove the selected network: https://github.com/brave/brave-core/pull/11234/
So I think this can be closed and labeled closed/duplicate.
I'll let you do that if you agree! Thanks.

**Comment by Douglashdaniel** [comment]
That would fix the bug! 
Agreed!
Closing as `duplicate` issue.
