### ISSUE TITLE
On beta, the load new content bubble doesn't appear concurrently with release's

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19665]
## Description 

On beta, the load new content bubble doesn't appear concurrently with release's

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. scroll down on the new-tab page
   4. click on `Show Brave News`
   5. keep scrolling down to content
   6. set system clock ahead 3 hours
   7. restart Brave
   8. wait for `Load new content` bubble to appear

## Actual result:

Doesn't appear on `beta` at the same time it does in `release`

`beta` vs. `release`

![load-new-content](https://user-images.githubusercontent.com/387249/142924604-3956231f-18fc-47e5-bc8f-2c6f1eaaf84a.png)

## Expected result:

Assuming:
* same content feed
* brand-new profiles
* same interactions

it should show the `Load new content` bubble on `beta` when/around when it does on `release`

## Reproduces how often: 

100% so far

## Brave version (brave://version info)

Brave | 1.33.85 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 20H2 (Build 19042.1348)

cc @petemill

**Comment by mattmcalister** [comment]
@stephendonner will check to see if this is still happening?

**Comment by stephendonner** [comment]
> @stephendonner will you check to see if this is still happening?

Checked using 

Brave | 1.36.119 Chromium: 99.0.4844.83 (Official Build) (x86_64)
-- | --
Revision | b11086e62d7c1a44b0942ac5568d22a425c7ae35-refs/branch-heads/4844_74@{#5}
OS | macOS Version 12.3 (Build 21E230)

and



Brave | 1.37.101 Chromium: 99.0.4844.83 (Official Build) beta (x86_64)
-- | --
Revision | b11086e62d7c1a44b0942ac5568d22a425c7ae35-refs/branch-heads/4844_74@{#5}
OS | macOS Version 12.3 (Build 21E230)

Using my listed steps, I didn't get `Load new content` on either - will investigate and file a separate issue, depending.

I think we can close this one out, given I'm not seeing it working the same, any longer.
