### ISSUE TITLE
Brave BAT does not appear in Brave Wallet

### ISSUE THREAD

**Issue by Darthagnon** [brave/brave-browser#19666]
## Description 
Brave Rewards seems to only pay into Gemini wallet, not into the new Brave Wallet. I've got Brave Rewards connected to Gemini, I've got BAT in Gemini, it's all set up in the browser, but the Wallet section shows 0 BAT, and seems to not be connected to Gemini or BAT or anything. Confused.

## Steps to Reproduce

   1. Earn some BAT in Brave Browser
   2. Connect wallet to Gemini (advertised service in the Brave Rewards page), and hand over a bunch of personal info
   3. Update Brave Browser to v1.32.106, with the new Wallet gui.
   4. Look in Wallet, expecting my BAT to show up there.

## Actual result:
BAT is not paid into Brave Wallet, nor does earned BAT appear there, which is unexpected behaviour. Why is it only paid into Gemini Wallet?

## Expected result:
BAT should be paid into Brave Wallet, or at least appear there somehow.

## Brave version (brave://version info)
```
Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 1709 (Build 16299.967)
```

**Comment by dev-ankur** [comment]
Not created any account online yet, still not reflecting BAT in the new brave wallet, same with the older(previous) ones. Moreover, there is a difference between total BAT I counted in monthly statements and under the title "Your balance"!

**Comment by Miyayes** [comment]
Hi, we will be working Brave Rewards more into Brave Wallet in the future. But at this time, this is expected and not considered a bug. Hopefully some helpful explanations:

>Right now, BAT inside your Brave Wallet is effectively separate from the Brave Rewards ecosystem. In order to use the BAT that’s in your Brave Wallet in the Rewards ecosystem (e.g. to tip creators), you’ll need to send the BAT from your Brave Wallet to your crypto custodian account that’s linked to your Brave Rewards. 
>
>The Brave Wallet (brave://wallet) is a self-custody wallet where you own the keys to the assets in your on-chain Ethereum/EVM-compatible address (and soon Solana, Bitcoin, plus other networks).
>
>You can earn BAT via Brave Rewards (Brave Ads), and then move that BAT to a crypto custodian account (such as Gemini, Uphold, or bitFlyer in Japan) by “verifying” your Brave Rewards. Once that BAT is in your crypto custodian account, you can withdraw that BAT into your Brave Wallet address using your crypto custodian’s normal on-chain withdrawal function.
