### ISSUE TITLE
favourite should be spelled favorite in Brave News

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19661]
## Description 

favourite should be spelled favorite in Brave News

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. scroll down from the new-tab page
   4. click on `Show Brave News`
   5. look for the block of 3 Amazon promotions
   6. look at the spelling of `favorite`

## Actual result:

Spelled `favourite` (British)

![favourite](https://user-images.githubusercontent.com/387249/142908459-0a61ca13-244c-492b-9b41-a487b517f708.png)

## Expected result:
Spelled `favorite` ('MERICA! 😉 )

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.33.85 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 20H2 (Build 19042.1348)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @petemill @mattmcalister

**Comment by mattmcalister** [comment]
No longer relevant. Binning this issue 😄
