### ISSUE TITLE
"2 hours ago" should be "about 2 hours ago" on Brave News feed

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19660]
## Description 

"2 hours ago" should be "about 2 hours ago" on Brave News feed

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. scroll down a bit to any article
   4. look at the "2 hours ago" timestamp

## Actual result:

Shows "2 hours ago"

`beta` vs. `release`

![about-hours-ago](https://user-images.githubusercontent.com/387249/142906956-35c122ca-1ef8-43b3-8af9-fc7fd5b3e166.png)

## Expected result:
Should show "about 2 hours ago" to match parity with release

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.33.85 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 20H2 (Build 19042.1348)

cc @petemill

**Comment by petemill** [comment]
I'm ok with keeping it the new way. It piggy backs on a more thorough "relative time" calculation function from chromium which also provides correct translations unlike the same code path in release. Cc @mattmcalister

**Comment by mattmcalister** [comment]
this is fine. Closing.
