### ISSUE TITLE
relaunch buttons don't display if rewards is enabled while `brave://settings/rewards` is opened/active tab

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#19676]
## Description 

When you enable rewards using the panel after initiating the rewards panel via `brave://settings/rewards`, you'll notice that enabling/disabling the inline tip settings won't display a `relaunch` button as per https://github.com/brave/brave-core/pull/11157.

## Steps to Reproduce

   1. launch Brave with a new profile
   2. once launched, open `brave://settings/rewards` (in my case, this was the only tab opened)
   3. click on the button that toggles the rewards panel and enable rewards
   4. you'll notice that `brave://settings/rewards` will get populated once rewards is enabled
   5. toggle the inline tip settings under `Tip buttons` and you'll notice that the `Relaunch` button isn't being displayed

Note: Closing/re-opening `brave://settings/rewards` fixes the issue so the above isn't a high priority issue.

## Actual result:

![issue](https://user-images.githubusercontent.com/2602313/142968069-146cdcc7-13a2-4a0f-a1dc-6e943ce01ef8.gif)

## Expected result:

![image](https://user-images.githubusercontent.com/2602313/142968118-743c10af-4737-473d-bbc5-22b0d85ac6a5.png)

## Reproduces how often: 

100% reproducible using the above STR. @stephendonner also confirmed/reproduced.

## Brave version (brave://version info)

```
Brave | 1.34.28 Chromium: 96.0.4664.45 (Official Build) nightly (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 11 Version 21H2 (Build 22000.318)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes` (once https://github.com/brave/brave-core/pull/11157 is uplifted)
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @Miyayes @LaurenWags @emerick

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.33.94 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H2 (Build 19044.1387)

```
