### ISSUE TITLE
Should ignore casing when compare account address in ShouldCreate1559Tx

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19673]
Regression introduced by https://github.com/brave/brave-core/pull/11200.
from address could be non-checksum address while address in our account info is checksum address.
This will make us create legacy tx when we shouldn't.

**Comment by yrliou** [comment]
Test plan specified in PR.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11229>brave/brave-core#11229</a></li>
         <li>Verified swap shows EIP-1559 gas pricing</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143382015-a47871c9-4f18-40dc-9b6c-68ce7411e2ac.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143381559-f20901ee-5032-4041-906f-a756ae4de04b.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/143381543-e13a7a30-9f7b-4981-9788-df6c3d0edd35.mov>
      </td>
   </tr>
</table>
