### ISSUE TITLE
Change naturally "Disconnected" state to say "Logged out" (verified Rewards wallet)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19674]
## Description

Change the naturally Disconnected state to say "Logged out", which better reflects the meaning.

Naturally Disconnected state = when the access token expires, for example.

![image](https://user-images.githubusercontent.com/11497541/143370824-a426e3e3-e31c-4fa7-b8f2-eeda7f3eb9d5.png)

Also makes better sense with this error notification:

![image](https://user-images.githubusercontent.com/11497541/142965990-3a6788ba-42c2-43bd-a255-d760c0c54420.png)

**Comment by emerick** [comment]
@Miyayes mentioned picking this one up, so reassigning to me. :-)

**Comment by GeetaSarvadnya** [comment]
When the wallet is disconnected naturally, the BR panel doesn't show uphold user name, is this expected?

![image](https://user-images.githubusercontent.com/38657976/148757404-c82b1ead-cade-49e1-8900-8fd72a6e4eae.png)

**Comment by GeetaSarvadnya** [comment]
When uphold wallet is disconnected naturally, The logged out overlay shows the option as `Log out from uphold` should it be `Log out from Brave Rewards`?
cc: @Miyayes @emerick 

RC 1.34.x | 1.35.x
------|-----
![image](https://user-images.githubusercontent.com/38657976/148760417-7f3e3d3f-2e35-4683-b0fc-6afa50ddc543.png) | ![image](https://user-images.githubusercontent.com/38657976/148760506-8827b75a-09a2-45b5-a667-ddc9805b1130.png)

**Comment by emerick** [comment]
@GeetaSarvadnya That's intentional, per https://github.com/brave/brave-browser/issues/19626.
