### ISSUE TITLE
Brave Browser is jerking and not showing rewards properly 

### ISSUE THREAD

**Issue by NooruddinLakhani** [brave/brave-browser#19681]
## Description 
Brave Browser is jerking and not showing rewards properly. Jerking all the time as showing in video attached. Looks like a UI issue and also wallet showing different screen

## Brave version (brave://version info)
V1.32.106

## Video Link Attached
[Video Here](https://drive.google.com/file/d/1BZZPLFiPpLZ-eBgEayK8xZqgJ_nqaIJj/view?usp=sharing)

**Comment by rebron** [comment]
Hi @NooruddinLakhani. Can you go to brave://settings/system and turn off Hardware Acceleration and see if that changes how it's looking?

**Comment by NooruddinLakhani** [comment]
@rebron Thanks It works and got smooth now 👍 But is there any way to get more ads?

**Comment by Miyayes** [comment]
@NooruddinLakhani, you can also try updating your graphics card drivers, and when you're done, enable Hardware Acceleration again to see if that fixes it. If not, you can just keep Hardware Acceleration off. But that solves it sometimes for users.
