### ISSUE TITLE
Add feature flag to enable 'Easylist-Cookie List' by default

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#19689]
We'd like to evaluate the feasibility of adding 'Easylist-Cookie List' to Brave's set of default lists, to remove cookie notices by default (like Vivaldi already does). To accomplish this, we'd like a way to roll out the cookie list to users with a feature flag, and have the ability to disable the feature if it's too problematic.

We can use the feature to ignore any existing local setting for the list, such that if the flag is disabled again, the original setting can be restored for users who've changed it in the past.

**Comment by stephendonner** [comment]
Verification `PASSED` using 

Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)

See https://github.com/brave/brave-browser/issues/20126#issuecomment-1007782828 for verification notes and screenshots.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 10 running 1.35.93 x64 beta build
- Verification notes can be found here [#20126 (comment) ](https://github.com/brave/brave-browser/issues/20126#issuecomment-1023345717)
