### ISSUE TITLE
Temporarily restore PR branch, if deleted, in uplift.py

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#19683]
When a PR is merged, the branch is automatically deleted. If an uplift is attempted afterwards, it will fail, because the PR branch is gone. I added a note on [the wiki](https://github.com/brave/brave-browser/wiki/Uplifting-a-pull-request#using-automation-to-create-those-pull-requests) about restoring it manually, but ideally there would be no manual steps needed, except calling the script.

This feature could be behind a command-line option. We'd certainly use that option in the brave-core-create-uplift-prs pipeline.

**Comment by wknapik** [comment]
cc @bsclifton as top contributor to the script

**Comment by bsclifton** [comment]
@wknapik I didn't think the branch name was ever used? The script will look up the original pull request by the pull request number and then get the SHA that was merged into master basically

There is a problem if you need to uplift in other scenarios though; like once it's already in master and beta, trying to use the script to get into release will fail.

**Comment by wknapik** [comment]
@bsclifton this is easy to reproduce. Every time I've tried using the [uplift pipeline](https://ci.brave.com/job/brave-core-create-uplift-prs/), which [just calls the script](https://github.com/brave/devops/blob/master/jenkins/jobs/browser/brave-core-create-uplift-prs.yml#L50), it failed when the PR branch was deleted and succeeded when it was restored. I might be doing something wrong, but there isn't much to mess up here...

**Comment by bsclifton** [comment]
@wknapik do you have a link to a failed job? I uplift PRs all the time which are already merged and branch is deleted. The PR number is used w/ GitHub's API to retrieve meta data; the branch itself is never referenced AFAIK

**Comment by bsclifton** [comment]
I guess I'd just like to see a case where it does break? Basically, `brave-core` is setup to auto-delete the branch after merge. I've never had a branch existing when running the tool

I have had problems where the tool will fail if the branch is NOT merged and NOT deleted. Maybe that's what we were thinking of?

**Comment by wknapik** [comment]
@bsclifton https://bravesoftware.slack.com/archives/C5DT3GPCH/p1638818877341000?thread_ts=1638794549.324200&cid=C5DT3GPCH

**Comment by bsclifton** [comment]
Awesome, thanks for sharing a case! 😄 Wonder why this doesn't happen all the time? Maybe something changed on GitHub side about how they prune the remote. One solution would be to grab the merge commit instead (and uplift that)

**Comment by wknapik** [comment]
In my experience this happens a 100% of the time, I think. I don't do uplifts that often.

I was thinking maybe it's about something I'm doing differently, so I waited for someone else to run into this.

As for looking at the merge commit - sounds good.

**Comment by mihaiplesa** [comment]
Definitely does not work anymore without restoring the branch.
https://github.com/brave/brave-core/pull/11436
https://ci.brave.com/job/brave-core-create-uplift-prs/1451/
https://ci.brave.com/job/brave-core-create-uplift-prs/1452/

**Comment by wknapik** [comment]
@mihaiplesa we could add triggering the uplift pipeline (and deleting branches at the right time) based on a label on PRs
