### ISSUE TITLE
Lock wallet is not properly aligned on panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19680]
## Description 

Lock wallet is not properly aligned on panel

## Steps to Reproduce

   1. Set language to a different locale 
   2. Open wallet panel and click on 3 dot menu
   3. Text is not properly aligned and also overlaps on the lock icon (see dark theme screenshot)

## Actual result:

Light | Dark 
-- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/143038659-870cd733-70c4-4178-b617-56af1372f1e9.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/143038734-628c6fff-128b-4466-bd95-7fe8999c2a07.png>

## Expected result:
Proper alignment and not overlapping on lock icon

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.111 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by josheleonard** [comment]
<img width="339" alt="Capture d’écran, le 2022-03-01 à 19 28 15" src="https://user-images.githubusercontent.com/30185185/156480858-977dcc12-3fc0-465b-8313-09c73364b3d4.png">
<img width="334" alt="Bildschirmfoto 2022-03-01 um 7 36 56 PM" src="https://user-images.githubusercontent.com/30185185/156480860-5528b0f0-6b9d-45da-b8bc-43a7c380a514.png">

Looks like with the latest translations, "lock wallet" is aligned correctly now, but the "view on block explorer" link will need realignment

**Comment by Uni-verse** [comment]
Verified using 

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.3.1 (Build 21E258)

- Verified lock wallet is properly aligned
- Verified view on block explorer text is aligned properly

Light | Dark
-|-
<img width="315" alt="Bildschirmfoto 2022-04-15 um 1 33 37 PM" src="https://user-images.githubusercontent.com/17885425/163629824-87d5e5e5-bbd4-4220-a590-ddbb868de2ec.png"> | <img width="322" alt="Bildschirmfoto 2022-04-15 um 1 34 51 PM" src="https://user-images.githubusercontent.com/17885425/163629827-1e9edcc0-e6c3-4bca-bfbf-7f770ed2a9e7.png">
