### ISSUE TITLE
Create Lock functionality in the main wallet menu

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#19699]
Provide Lock near the Settings and apply icons desktop and iOS have
![Image from iOS](https://user-images.githubusercontent.com/12011303/143148116-88ac3216-9b59-47a5-8a01-a177cd63fe02.png)
:

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33.100 x64 build
- Verified lock option is shown on wallet menu 
- Verified clicking on it locks the wallet immediately 

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/145012830-11f8f656-ae17-4fa3-aad3-82c7ddced47e.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145012849-fb640d24-8d60-416a-be4c-403c36a33dff.png>
