### ISSUE TITLE
Remove Header Info From Add and Switch Network Panels

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19692]
## Description 
Remove header info from the Add/Switch Network Panels to match what's in the figma design. 

1) Remove `Network` top left
2) Remove `Address` top middle
3) Remove `Account Orb` top right

![image](https://user-images.githubusercontent.com/40611140/143130126-5344d423-15e6-45e6-bd0f-a686104cfb2a.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.93 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified header info is removed on Switch Network prompt</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/151513231-5231413f-b759-4456-be96-61921c359dd5.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151513260-f1f7f63e-5b94-44fb-b753-61f29f92825a.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151513320-d2d02dfc-9e2c-47e5-be92-a7c5ce482b17.mp4>
      </td>
   </tr>
</table>
