### ISSUE TITLE
"Hide Brave Rewards button" stands out from the other toggles

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#19695]
The "Hide Brave Rewards button" toggle in `brave://settings/appearance` stands out from the rest of the toggles because all of the other ones use "Show xxxx" or "Always show xxxx":
![Screenshot from 2021-11-23 14-22-25](https://user-images.githubusercontent.com/167821/143138695-0127fa76-d4b9-4375-8583-c240d626b140.png)

We should change that to be "Show Brave Rewards button" (default ON) to match the rest of the settings. Otherwise some people may think we're trying to confuse people with a "dark pattern", as opposed to the real reason which is that we didn't notice the inconsistency when we originally added that toggle.

(Originally reported in https://neilzone.co.uk/2021/11/brave-browser-less-privacy-respectful-than-i-was-expecting by @neilzone.)

**Comment by Miyayes** [comment]
Simple proposal: The setting should read as follows:

>Show Brave Rewards icon in URL bar

It should be _enabled_ by default (toggled on). When user toggles off, then it will hide the Brave Rewards icon.

**Comment by neilzone** [comment]
👍

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.36.39 Chromium: 97.0.4692.71 (Official Build) nightly (64-bit)
--|--
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 20H2 (Build 19042.1466)

### Case 1: 1.34.80 upgrade, default pref - PASSED

launch 1.34.80
load `brave://settings/appearance`
confirm `Hide Brave Rewards button` is set to `OFF` (default)
confirm Brave Rewards button is shown in the URL bar
install 1.36.x latest (upgrade)
launch 1.36.x
confirm `Show Brave Rewards icon in address bar` is set to `ON`
confirm Brave Rewards button is shown in the URL bar

### Case 2: 1.34.80 upgrade, toggled `ON` (hide) - PASSED

launch 1.34.80
load `brave://settings/appearance`
confirm `Hide Brave Rewards button` is set to `OFF` (default)
toggle `Hide Brave Rewards button` to `ON`
confirm there's NO Brave Rewards button is shown in the URL bar
install 1.36.x latest (upgrade)
confirm `Show Brave Rewards icon in address bar` is set to `OFF`
confirm there's NO Brave Rewards button in the URL bar

### Case 3: 1.36.x fresh install, default pref - PASSED

launch 1.36.x
load `brave://settings/appearance`
confirm `Show Brave Rewards icon in address bar` is set to `ON`
confirm Brave Rewards button is shown in the URL bar

### Case 4: 1.36.x, fresh install, toggled `OFF` - PASSED

launch 1.36.x
load `brave://settings/appearance`
confirm `Show Brave Rewards icon in address bar` is set to `ON`
confirm Brave Rewards button is shown in the URL bar
toggle `Show Brave Rewards icon in address bar` to `OFF`
confirm there's NO Brave Rewards button in the URL bar

### Case 5: 1.33.106 upgrade, default pref - PASSED

launch 1.33.106
confirm `Hide Brave Rewards button` set to `OFF` (default)
install 1.36.x latest (upgrade)
launch 1.36.x
confirm `Show Brave Rewards icon in address bar` is set to `ON`
confirm Brave Rewards button is shown in the URL bar

### Case 6: 1.33.106 upgrade, toggled `ON` (hide) - PASSED

launch 1.33.106
load `brave://settings/appearance`
confirm `Hide Brave Rewards button` is set to `OFF`
confirm Brave Rewards button is shown in the URL bar
toggle `Hide Brave Rewards button` to `ON`
confirm NO Brave Rewards button is shown in the URL bar
install 1.36.x latest (upgrade)
launch 1.36.x
confirm `Show Brave Rewards icon in address bar` is set to `OFF`

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 


<summary>Case 1: 1.34.80 upgrade, default pref - PASSED</summary>
<details>

1. launch 1.34.80
2. load `brave://settings/appearance`
3. confirm `Hide Brave Rewards button` is set to `OFF` (default)
4. confirm Brave Rewards button is shown in the URL bar
5. install `1.36.45` (upgrade)
6. launch `1.36.45`
7. confirm `Show Brave Rewards icon in address bar` is set to `ON`
8. confirm Brave Rewards button is shown in the URL bar

steps 3-4 | steps 7-8
---------|---------


</details>

<summary>Case 2: 1.34.80 upgrade, toggled `ON` (hide) - PASSED</summary>
<details>

1. launch 1.34.80
2. load `brave://settings/appearance`
3. confirm `Hide Brave Rewards button` is set to `OFF` (default)
4. toggle `Hide Brave Rewards button` to `ON`
5. confirm there's NO Brave Rewards button is shown in the URL bar
6. install `1.36.45` (upgrade)
7. confirm `Show Brave Rewards icon in address bar` is set to `OFF`
8. confirm there's NO Brave Rewards button in the URL bar

step 3 | step 5 | steps 7-8
---------|---------|---------


</details>

<summary>Case 3: 1.36.45 fresh install, default pref - PASSED</summary>
<details>

1. launch `1.36.45`
2. load `brave://settings/appearance`
3. confirm `Show Brave Rewards icon in address bar` is set to `ON`
4. confirm the Brave Rewards button is shown in the URL bar

steps 3-4
----------

</details>

<summary>Case 4: 1.36.45, fresh install, toggled `OFF` - PASSED</summary>
<details>

1. launch 1.36.45
2. load `brave://settings/appearance`
3. confirm `Show Brave Rewards icon in address bar` is set to `ON`
4. confirm Brave Rewards button is shown in the URL bar
5. toggle `Show Brave Rewards icon in address bar` to `OFF`
6. confirm there's NO Brave Rewards button in the URL bar

steps 3-4 | step 6
---------|----------


</details>

<summary>Case 5: 1.33.106 upgrade, default pref - PASSED</summary>
<details>

1. launch 1.33.106
2. confirm `Hide Brave Rewards button` set to `OFF` (default)
3. confirm Brave Rewards button is shown in the URL bar
4. install `1.36.45` latest (upgrade)
5. launch `1.36.45`
6. confirm `Show Brave Rewards icon in address bar` is set to `ON`
7. confirm Brave Rewards button is shown in the URL bar

steps 2-3 | steps 6-7
----------|----------



</details>

<summary>Case 6: 1.33.106 upgrade, toggled `ON` (hide) - PASSED</summary>
<details>

1. launch 1.33.106
2. load `brave://settings/appearance`
3. confirm `Hide Brave Rewards button` is set to `OFF`
4. confirm Brave Rewards button is shown in the URL bar
5. toggle `Hide Brave Rewards button` to `ON`
6. confirm NO Brave Rewards button is shown in the URL bar
7. install `1.36.45` (upgrade)
8. launch `1.36.39`
9. confirm `Show Brave Rewards icon in address bar` is set to `OFF`
10. confirm NO Brave Rewards button is shown in the URL bar

steps 3-4 | step 6  | steps 9-10
---------|----------|----------


</details>

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` for `Android` till https://github.com/brave/brave-browser/issues/21183 is addressed/fixed. The above can also be tested alongside https://github.com/brave/brave-browser/issues/20633 & https://github.com/brave/brave-browser/issues/20646 when https://github.com/brave/brave-browser/issues/21183 is fixed.

**Comment by srirambv** [comment]
Verification passed as part of https://github.com/brave/brave-browser/issues/21183#issuecomment-1050609212. 
- Verified on both clean install and upgrade scenario rewards button is hidden or shown based on the setting
