### ISSUE TITLE
Is brave affected by mandatory google sync?

### ISSUE THREAD

**Issue by caspertone2003** [brave/brave-browser#1969]
Sorry is this is not the right place to ask.
Is this happening also to brave:
https://techcrunch.com/2018/09/26/google-to-give-chrome-users-an-opt-out-to-forced-login-after-privacy-backlash/?guccounter=1 
Thanks

**Comment by sillibird** [comment]
Brave is built on chromium, with all of google's junk stripped out. You can't even sign the browser into a google account, so no.

**Comment by caspertone2003** [comment]
Thanks
