### ISSUE TITLE
FATAL error log in CheckSchemeForReferrerPolicy

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#197]
## Description 
Saw a fatal error logged in my console while testing.
```
[62331:775:0511/194546.935002:FATAL:resource_dispatcher.cc(66)] Trying to send secure referrer for insecure request with
URL = http://google.com/
Referrer = https://www.youtube.com/
```
## Steps to Reproduce
   1. Open a tab and navigate to https://brianbondy.com/
   2. try to navigate to google.com

## Reproduces how often: 
Every time.

### Additional Information
Saw it on brave-core master, it doesn't show up when I am at the commit before merging brave/brave-core/pull/100

cc @bbondy

**Comment by bbondy** [comment]
Yikes, instead of reverting I just effectively disabled for now until I fix it for real:
https://github.com/brave/brave-core/commit/c9b43450f4bd5a9eb2493bcd40d06f20b6258d22

I'll take a look.

**Comment by yrliou** [comment]
@bbondy I'm seeing this FATAL error again today visiting http://www.benzworld.org/forums/w126-s-se-sec-sel-sd/
```[40161:775:0601/135448.968577:FATAL:resource_dispatcher.cc(66)] Trying to send secure referrer for insecure request without an appropriate referrer policy.
URL = http://staticxx.facebook.com/connect/xd_arbiter/r/oVjM2wVZ10b.js?version=42#channel=f385f5a644c3e9&origin=http%3A%2F%2Fwww.benzworld.org
Referrer = https://staticxx.facebook.com/```

**Comment by bbondy** [comment]
I was reproducing on that site but it just went away again :( 
I notice there's 2 iframes on that page one with http://staticxx.facebook.com and one with the same url but https.

**Comment by bbondy** [comment]
Being tracked here:
https://github.com/brave/brave-browser/issues/234
