### ISSUE TITLE
Verbose flag for rewards

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#1970]
Add option for QA to print out logs into the terminal.

QA will be able to use VLOG for rewards.

We should have 5 levels:
```
ERROR = 1,
WARNING = 2,
INFO = 3,
REQUEST = 4,
RESPONSE = 5
```

You can use it like `npm start -- --vmodule=*rewards*=2`, where 2 is level. If you specify 2 as a level, you will get logs for levels 1 and 2. If you specify 5, you will get levels 1, 2, 3, 4 and 5

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.14 x64` - **PASSED**

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X
