### ISSUE TITLE
Can't not found the remote debugging option in the settings

### ISSUE THREAD

**Issue by dc198689** [brave/brave-browser#19707]
## Description 

Hi, I already install the brave browser in the Window PC Desktop,
I am trying to find the remote debugging option in the privacy and security category page, but not found it,
Is the brave browser version are disabled ? or Still any step to trigger before show the option ?

## Steps to Reproduce

   1. Download and Install Brave Browser
   2. Go to 'brave://settings/privacy
   3. Not found the remote debugging option

## Actual result:

Can't not find the option

## Expected result:
Can show the option

## Brave version (brave://version info)

Brave v1.32.106

**Comment by rebron** [comment]
@dc198689 We removed it. Here's the issue: https://github.com/brave/brave-browser/issues/9715 There are several related issues that led to that decision.
