### ISSUE TITLE
Set custom nonce for transactions

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#19705]
Allow advanced setting of nonce for transactions. Expose a settings icon on send confirmation panel to set custom nonce.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.83 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11840>brave/brave-core#11840</a></li>
         <li>Verified settings option is shown on transaction details view</li>
         <li>Verified clicking on the gear icon opens nonce page</li>
         <li>Verified info text is shown below the nonce input field and doesn't have a pre-populated value</li>
         <li>Verified input nonce value is set and doesn't clear when closed</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/152521051-92361445-b8af-4bac-90df-77e7c184a247.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152516071-7dd5b84e-de36-476d-9970-fcbb38139f85.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152521190-70639957-3046-4375-83d5-2e31e7bad1d7.mov>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Android specific issue logged #20887. Removing Android label
