### ISSUE TITLE
Hide crypto widgets by default on desktop

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19708]
This is desktop part of https://github.com/brave/brave-browser/issues/19478

* For new users, all crypto widgets are hidden by default
  * User can control crypto widgets' visibility from gallery
* For existing users, migrate current widget visibility
   * Migrate strategy: if current foremost widget is crypto widget, only it is visible and others are hidden
   * After migration, user can control crypto widget's visibility from gallery

**Comment by LaurenWags** [comment]
Added labels that were on https://github.com/brave/brave-browser/issues/19478 (duplicate issue)

**Comment by srirambv** [comment]
Removing Android label as there is an Android specific issue https://github.com/brave/brave-browser/issues/19546

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.33.94 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Linux

- Verified test plan from https://github.com/brave/brave-core/pull/11266
- Verified on clean install only Brave rewards widget is shown
- Verified all other widgets are disabled and can be enabled via dashboard settings
- Verified enabled widgets are retained across browser relaunches
- Verified on upgrade from previous version, only Brave rewards is shown if it was the foremost widget
- Verified when a crypto widget(auth'd or not) is in foreground and rewards is the second one, post upgrade the same order is retained except all other widgets behind rewards is hidden
- Verified when two crypto widgets are auth'd and rewards is third, the same order is retained post upgarde
- Verified when rewards is the last widget, post upgrade all widgets are hidden and only rewards is shown
- Verified post upgrade only rewards and Brave Talk widgets are retained when Talk is enabled on the older version
- Verified if all widgets are hidden on older version, post upgrade none of them are enabled including rewards
- Verified if rewards is disabled and Binance is the foremost widget, post upgrade only Binance widget is retained and rest all is hidden
----------
Verification passed on 

Brave | 1.33.94 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | Windows 11 Version Dev (Build 22509.1000)

- Verified test plan from https://github.com/brave/brave-core/pull/11266
- Verified on clean install only Brave rewards widget is shown
- Verified all other widgets are disabled and can be enabled via dashboard settings
- Verified enabled widgets are retained across browser relaunches
- Verified on upgrade from previous version, only Brave rewards is shown if it was the foremost widget
- Verified when a crypto widget(auth'd or not) is in foreground and rewards is the second one, post upgrade the same order is retained except all other widgets behind rewards is hidden
- Verified when two crypto widgets are auth'd and rewards is third, the same order is retained post upgarde
- Verified when rewards is the last widget, post upgrade all widgets are hidden and only rewards is shown
- Verified post upgrade only rewards and Brave Talk widgets are retained when Talk is enabled on the older version
- Verified if all widgets are hidden on older version, post upgrade none of them are enabled including rewards
- Verified if rewards is disabled and Binance is the foremost widget, post upgrade only Binance widget is retained and rest all is hidden
----------
Verification passed on 

Brave | 1.33.94 Chromium: 96.0.4664.45 (Official Build) beta (arm64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified test plan from https://github.com/brave/brave-core/pull/11266
- Verified on clean install only Brave rewards widget is shown
- Verified all other widgets are disabled and can be enabled via dashboard settings
- Verified enabled widgets are retained across browser relaunches
- Verified on upgrade from previous version, only Brave rewards is shown if it was the foremost widget
- Verified when a crypto widget(auth'd or not) is in foreground and rewards is the second one, post upgrade the same order is retained except all other widgets behind rewards is hidden
- Verified when two crypto widgets are auth'd and rewards is third, the same order is retained post upgarde
- Verified when rewards is the last widget, post upgrade all widgets are hidden and only rewards is shown
- Verified post upgrade only rewards and Brave Talk widgets are retained when Talk is enabled on the older version
- Verified if all widgets are hidden on older version, post upgrade none of them are enabled including rewards
- Verified if rewards is disabled and Binance is the foremost widget, post upgrade only Binance widget is retained and rest all is hidden
