### ISSUE TITLE
2021 and no portable !? And I can`t select the folder for installation! fukit 

### ISSUE THREAD

**Issue by DStrifer** [brave/brave-browser#19701]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

not going to kill my ssd because of this automatic installer

**Comment by rebron** [comment]
Closing. For general feedback and feature requests such as these, invite you to https://community.brave.com/
