### ISSUE TITLE
Enable wallet by default, disable Dapps

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#19702]

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 110running 1.33.103 x64 build
- Verified Wallet is enabled by default
- Verified able to create wallet successfully
- Verified able to restore wallet successfully
- Verified visiting a Dapp doesn't trigger wallet connection 
------------
Verification passed on Oppo Reno 5 with Android 11 running 1.33.103 x64 build
- Verified Wallet is enabled by default
- Verified able to create wallet successfully
- Verified able to restore wallet successfully
- Verified visiting a Dapp doesn't trigger wallet connection
