### ISSUE TITLE
Wallet onboarding doesn't load

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19719]
## Description 

Wallet onboarding doesn't load

## Steps to Reproduce

   1. Clean install 1.32.112
   2. Open `brave://wallet`
   3. Console throws errors and doesn't load onboarding screen

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/143233760-484d07bf-608a-4ac5-9f89-49b3544a87ff.png)

## Expected result:
Load onboarding 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.112 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/crypto-wallets @kjozwiak @rebron

**Comment by kjozwiak** [comment]
@srirambv once we get the new RC builds with https://github.com/brave/brave-core/pull/11277 and the above works, we can close this off 👍

**Comment by darkdh** [comment]
1.32.x is missing https://github.com/brave/brave-core/pull/10967 so any PR with new added mojo interface will have that error

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build:

```
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 11 Version 21H2 (Build 22000.348)
```

**`Wallet panel`** | **`brave://wallet`**
--------------------|----------------------
![image](https://user-images.githubusercontent.com/2602313/143338354-7c2c3c50-c53a-42a4-90a7-286d6dbcd03b.png) | ![image](https://user-images.githubusercontent.com/2602313/143338916-059a9831-78b0-4596-9b31-f8860d2d1510.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (arm64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified onboarding is shown correctly 
- Verified no errors on console

![image](https://user-images.githubusercontent.com/17010094/143375712-c7a68d84-5d02-4b07-bb6d-ff532fe829ce.png)
