### ISSUE TITLE
Plus button urls is blocked when editing networks

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19717]
## Description 

Plus button for RPC urls is blocked when editing networks

## Steps to Reproduce

   1. Add custom network
   2. Double click to edit
   3. Check "+" button for RPS urls

## Actual result:

The button is blocked

## Expected result:

The button is unblocked

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.34.68 Chromium: 97.0.4692.56 (Official Build) beta (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)
```

Verified STR and test plan from https://github.com/brave/brave-core/pull/11273#issue-1062166452.
Confirmed when editing a custom network the "+" for RPC URLs field is visible and can be clicked on.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified steps from [brave/brave-core#11273](https://github.com/brave/brave-core/pull/11273)
- Verified editing a custom network shows the `+` button for adding a new RPC URL
- Verified clicking on the `+` button in edit mode hides the button for adding a new URL
- Verified adding a valid URL brings back the `+` button to focus

https://user-images.githubusercontent.com/17010094/147938385-cf990fdb-f07e-4436-b8da-1c0fd0629eef.mov

------------
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Linux

- Verified steps from [brave/brave-core#11273](https://github.com/brave/brave-core/pull/11273)
- Verified editing a custom network shows the `+` button for adding a new RPC URL
- Verified clicking on the `+` button in edit mode hides the button for adding a new URL
- Verified adding a valid URL brings back the `+` button to focus


https://user-images.githubusercontent.com/17010094/147938517-d76e553f-72b5-4188-8ddd-766717556fae.mp4
