### ISSUE TITLE
Unable to fetch recent tags from Chromium's GitHub mirror

### ISSUE THREAD

**Issue by mariospr** [brave/brave-browser#19720]
## Description 

As reported in the [upstream bug here](https://bugs.chromium.org/p/chromium/issues/detail?id=1272797), the [Chromium's GitHub mirror](https://github.com/chromium/chromium) automatic syncing has been broken since past Wednesday (November 17th), causing trouble during our rebases since Brave scripts initialize everything against that GitHub mirror (e.g. working on `cr98` to update to `98.0.4710.4` required manually fixing the `.git/config` file to point to the upstream git repo instead).

As [mentioned in the bug upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=1272797#c7), fixing this problem is high priority but at the same time it's blocked on an external dependency and it's not possible to know and ETA for the complete solution.

At the moment, this has only been a problem for the `cr98` branch, but as soon as we want to update to any other recent tag in the other branches we'll hit the same problem in there, so we better fix this sooner rather than later by switching to using the upstream repo at https://chromium.googlesource.com/chromium/src.git instead (regardless of maybe switching back to the mirror later on, if it makes sense).

## Steps to Reproduce
   1. Checkout the `cr98` branch
   2. Try to run `npm run sync`

## Actual result:

It fails due to not finding the `98.0.4710.4` tag.

## Expected result:

It should not fail

## Reproduces how often: 

Always

**Comment by mkarolin** [comment]
https://github.com/brave/brave-core/pull/11276#issuecomment-989691387
