### ISSUE TITLE
38-day old Apple article with broken link appears in feed

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19728]
## Description 

38-day old Apple article with broken link appears in feed

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. scroll down
   4. click on `Show Brave News`
   5. keep scrolling down until you see an Apple-event article from `Techcrunch`
   6. click on the article

## Actual result:

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-11-24 at 8 52 35 PM" src="https://user-images.githubusercontent.com/387249/143362776-594a6bf8-99f2-452a-ab43-badb16b0a067.png"> | <img width="1312" alt="Screen Shot 2021-11-24 at 8 52 39 PM" src="https://user-images.githubusercontent.com/387249/143362848-95b0ee69-6e9a-4b57-8f8d-ba40c2810f46.png">

* 38-day old article (according to its timestamp)
* The link goes to `https://www.blogger.com/blogin.g?blogspotURL=https%3A%2F%2Ftechncruncher.blogspot.com%2F2021%2F10%2Fwatch-apples-unleashed-event-live-right.html&type=blog&bpli=1`
* That's a 404.

## Expected result:

Comparing with release which doesn't have this article linked, and given this is a 404, I don't think it should be displayed at all (38-day old timestamp).

## Reproduces how often: 

100% (right now)

## Brave version (brave://version info)

Brave | 1.33.87 Chromium: 96.0.4664.45 (Official Build) beta (x86_64)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 11.6.1 (Build 20G224)

/cc @petemill @mattmcalister

**Comment by stephendonner** [comment]
Sorry, not a regression; eventually saw this pop up in `release`, `1.32.106`, too.  Feed issue from Techcrunch, then?

**Comment by mattmcalister** [comment]
This was fixed with the source URL update at that time. Closing now.
