### ISSUE TITLE
Full Fiat Balance not showing with ERC721 tokens

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19725]
## Description 
The Full Portfolio Fiat Balance is not showing up when you have an `ERC721` in your visible list

https://user-images.githubusercontent.com/40611140/143298456-3da167c0-5d50-4f42-b571-81a2b159712f.mov

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.33.98 Chromium: 96.0.4664.55 (Official Build) (64-bit)
-- | --
Revision | `38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}`
OS | Linux

- Verified test plan from https://github.com/brave/brave-core/pull/11280
- Verified fiat balance is shown when ERC721 token is added to the list 
![image](https://user-images.githubusercontent.com/17010094/144413230-9799a2c5-6fd1-473e-97c7-95a0c058847e.png)

-----
Verification passed on 

Brave | 1.33.98 Chromium: 96.0.4664.55 (Official Build) (64-bit)
-- | --
Revision | `38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}`
OS | Windows 11 Version Dev (Build 22509.1000)

- Verified test plan from https://github.com/brave/brave-core/pull/11280
- Verified fiat balance is shown when ERC721 token is added to the list
![image](https://user-images.githubusercontent.com/17010094/144412806-814d4000-6d79-48b2-b1c6-a1a43ae2884d.png)
 
-------
Verification passed on 

Brave | 1.33.98 Chromium: 96.0.4664.55 (Official Build) (arm64)
-- | --
Revision | `38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified test plan from https://github.com/brave/brave-core/pull/11280
- Verified fiat balance is shown when ERC721 token is added to the list 
![image](https://user-images.githubusercontent.com/17010094/144412499-d9c0e321-3f90-42df-9e0a-0428a387e7a7.png)
