### ISSUE TITLE
Update Wallet icon for dark theme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19721]
## Description 
Update Wallet icon for dark theme

## Steps to reproduce 

   1. Set device to dark theme
   2. Enable Wallet
   3. Setting is not using correct icon

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/143259862-406aaba9-5131-4a0d-8f8e-d992b3cb87b9.png)

## Expected result
Should be white icon on dark there

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 11
   
## Brave version
-

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @wchen342

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.104 x64 build
- Verified wallet icon is properly visible on both dark and light theme

Dark | Light 
-- | --
![image](https://user-images.githubusercontent.com/17010094/145568067-0bb5bf82-1e4b-4831-8848-cd8c3f73698e.png) | ![image](https://user-images.githubusercontent.com/17010094/145568097-c9acc2c1-1e73-4332-9f6a-544e85e84f11.png)

------------
Verification passed on Samsung Tan A with Android 10 running 1.33.104 x64 build
- Verified wallet icon is properly visible on both dark and light theme

Dark | Light 
-- | --
![image](https://user-images.githubusercontent.com/17010094/145569377-25985524-d008-404c-8655-9fd73a804701.png) | ![image](https://user-images.githubusercontent.com/17010094/145569363-cc729659-8fca-4eb3-9763-31462809e0db.png)

**Comment by srirambv** [comment]
@AlexeyBarabash we should create a new one as that would be a regression on nightly .

**Comment by wchen342** [comment]
@AlexeyBarabash Doesn't nightly has Brave News in settings? The wallet icon uses the same color as news so I'm not sure what was going on there.

**Comment by AlexeyBarabash** [comment]
@wchen342  Brave News was Default through the brave://flags for me. Turned on :
Dark | 
-- | 
![Screenshot_20211210-142528](https://user-images.githubusercontent.com/24739341/145574122-4536362f-d416-416f-a9e8-7870f4f259c0.png)
