### ISSUE TITLE
Clicking Version Link in About Brave Section Opens .onion website in Private with Tor Window

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#19739]
Brave Version 1.32.106
OS : Windows 7
Link : https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/latest/

Please check below video

https://user-images.githubusercontent.com/46480489/143482551-96844e24-bdf9-4006-819c-0bd5c1d28bd2.MP4

o

**Comment by diracdeltas** [comment]
do you have this setting turned on in brave://settings/extensions
<img width="672" alt="Screen Shot 2021-11-29 at 4 14 20 PM" src="https://user-images.githubusercontent.com/549654/143962630-41357d80-a038-4e21-81fb-f6ff054ab487.png">
