### ISSUE TITLE
Swap error on Ropsten

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19730]
## Description 

Swap error on Ropsten

## Steps to Reproduce

   1. Switch network to Ropsten
   2. Click on Swap 
   3. Enter an input token value 
   4. Swap button starts to load but console throws error

## Actual result:

<img width="1840" alt="0x Ropsten Error" src="https://user-images.githubusercontent.com/17010094/143424039-5eac26a4-b3d6-4d63-80cc-1b8e8618d2ab.png">

## Expected result:
No error, proceed to swap

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (arm64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @Douglashdaniel

**Comment by onyb** [comment]
@srirambv Is this still valid?

**Comment by srirambv** [comment]
This seems to be fixed now. Sorry for the late response on the issue. 
![image](https://user-images.githubusercontent.com/17010094/148748901-79ba1f20-85d4-4250-b8e2-6b8f48ad15b5.png)
