### ISSUE TITLE
Restore open search behaviour for Android

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#19737]
## Description 
Recent PR https://github.com/brave/brave-core/pull/9602 caused a regression in Android behavour, we need to restore it until we figure out what we want to do with this option.

## Steps to reproduce 

1. On Android, visit a search engine and perform a search (user used searx.be)
2. After performing the search, check Settings --> Search engines --> Recently visited and observe no searches have been added

## Actual result 
No recently visited serach engines.

## Expected result
There should be recently visited serach engines.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33.114 x64 build
- Verified steps from issue description
- Verified performing a search on a page that supports open search gets listed under `Recently visited`
- Verified able to select the search engine added via open search and set it as default
- Verified open search engine gets listed for both normal and private search engine settings
- Verified able to switch back to default list which moves the added search engine back to recently visited list

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/144820462-47a32743-397f-4a70-87f0-997986638999.mp4> | <video src=https://user-images.githubusercontent.com/17010094/144820536-16aa6f2b-1462-47f3-811b-e1950be56f9b.mp4>
