### ISSUE TITLE
Brave isn't set as a default app for microsoft-edge protocol

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19735]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/17558
Brave isn't set as a default app for microsoft-edge protocol

## Steps to Reproduce

   1. Clean profile `1.32.112`
   2. Follow the steps from Test 1 https://github.com/brave/brave-core/pull/10879
   
## Actual result:

 Brave is set as the default app under `Set defaults by app`, but when any keyword or link is searched via taskbar, then brave is not displayed under `How do you want to open this` popup model

![image](https://user-images.githubusercontent.com/38657976/143449016-5a067b1e-f7a0-477f-90e6-91efc5845140.png)
![image](https://user-images.githubusercontent.com/38657976/143449282-d86beade-277c-4ccf-b564-a0ed250d5f3c.png)

![brave defaut_edge protocol](https://user-images.githubusercontent.com/38657976/143450055-f53972bd-77cf-4dbd-af63-471c977e0af1.gif)

## Expected result:
Brave should be set as a default app for microsoft-edge protocol and any keyword or link is searched via the taskbar should open search result in brave

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.32.112 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H2 (Build 19044.1387)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @brave/legacy_qa @rebron

**Comment by GeetaSarvadnya** [comment]
@simonhong Works fine for most of the audience, not sure why I am seeing the issue. The Windows version is as below, let me know if you need more details.
![image](https://user-images.githubusercontent.com/38657976/143450548-b16e236b-a1a7-4d57-a89b-16da22792d99.png)

**Comment by manikandancode** [comment]
https://github.com/brave/brave-browser/issues/19402

**Comment by bsclifton** [comment]
Closing as `wontfix` since the functionality will eventually be broken. See https://github.com/brave/brave-browser/issues/19402 for more info
