### ISSUE TITLE
Auto detect token balances when > 0 balance

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19746]
It would be best for UX if we can auto detect a user's token balances and auto-add any token that has a balance, instead of making the user add them manually.

We may want to filter out some small balances if there's a lot of noise.  This is only for tokens in our registry for now.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.70 x64 Beta build
- Verified test plan from [brave/brave-core#13295](https://github.com/brave/brave-core/pull/13295)
- Verified restoring a wallet via seed shows all tokens that have balance across all accounts
- Verified restoring an account via private key also restores/shows all tokens from that account in addition to already visible tokens
- Verified on a clean wallet only Ethereum and BAT are listed as expected and no other tokens are listed

---------
Verification passed on Samsung Tab A with Android 10 running 1.46.70 x64 Beta build
- Verified test plan from [brave/brave-core#13295](https://github.com/brave/brave-core/pull/13295)
- Verified restoring a wallet via seed shows all tokens that have balance across all accounts
- Verified restoring an account via private key also restores/shows all tokens from that account in addition to already visible tokens
- Verified on a clean wallet only Ethereum and BAT are listed as expected and no other tokens are listed

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified test plan from [brave/brave-core#13295](https://github.com/brave/brave-core/pull/13295)
- Verified restoring a wallet via seed shows all tokens that have balance across all accounts
- Verified restoring an account via private key also restores/shows all tokens from that account in addition to already visible tokens
- Verified restoring account via hardware wallet restores all the tokens from the account that have balance
- Verified on a clean wallet only Ethereum and BAT are listed as expected and no other tokens are listed

----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified test plan from [brave/brave-core#13295](https://github.com/brave/brave-core/pull/13295)
- Verified restoring a wallet via seed shows all tokens that have balance across all accounts
- Verified restoring an account via private key also restores/shows all tokens from that account in addition to already visible tokens
- Verified restoring account via hardware wallet restores all the tokens from the account that have balance
- Verified on a clean wallet only Ethereum and BAT are listed as expected and no other tokens are listed

----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 12.6 (Build 21G115)

- Verified test plan from [brave/brave-core#13295](https://github.com/brave/brave-core/pull/13295)
- Verified restoring a wallet via seed shows all tokens that have balance across all accounts
- Verified restoring an account via private key also restores/shows all tokens from that account in addition to already visible tokens
- Verified restoring account via hardware wallet restores all the tokens from the account that have balance
- Verified on a clean wallet only Ethereum and BAT are listed as expected and no other tokens are listed
