### ISSUE TITLE
Update tor to 0.3.4.9

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#1974]

**Comment by bbondy** [comment]
@mihaiplesa I think the Tor job needs to be run manually for this change so the new binary is bundled.

**Comment by bbondy** [comment]
@riastradh-brave can you please see to it that it gets updated in the extension jenkins job? Mainly by either asking @mihaiplesa or creating a devops issue, or running the job yourself on Jenkins. Thanks!

**Comment by mihaiplesa** [comment]
Tor extension updated to 1.0.3 via Jenkins job with the following changes:

Import supported extensions from Chrome Web Store
Remove vault-updater-path option, which is no longer needed
Use correct S3 options and brave-core-specific bucket
Use version 0.3.4.8 of the Tor client
Add "Troubleshooting" section to README.md
Issue 35: Tor client v0.3.4.9

@riastradh-brave just gave you access (details on Slack) to our Jenkins instance so you can initiate the build and deploy of future versions.

**Comment by jumde** [comment]
@LaurenWags updated the test plan, let me know if you have any questions.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux


![image](https://user-images.githubusercontent.com/17010094/50591230-80d73380-0eb4-11e9-9f65-798cef4555d8.png)
