### ISSUE TITLE
"The receiving address is a tokens contract address" should only be applied to ERC20 and NFT transfers.

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19745]
From: 
https://community.brave.com/t/im-not-able-to-swap-my-weth-for-eth-using-my-brave-wallet/305085

"(Using my updated Brave wallet) I sold an item in Opensea for WETH. The WETH is now in my wallet. The problem is that I cant swap it for ETH, nor can I move it to a different wallet. Every time I try to swap it, my wallet says “The receiving address is a tokens contract address.” and wont make the swap. And when I try to move my WETH to a different wallet I get this error on Etherscan “ERC-20 Token Transfer Error (Unable to locate corresponding Transfer Event Logs), Check with Sender.” Please Help!"

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.114 Chromium: 96.0.4664.55 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11300>brave/brave-core#11300</a></li>
         <li>Verified able to submit a ETH-WETH transaction without getting the token's contract address error message</li>
         <li>Verified able to cancel a transaction and confirm it. Cancelled transaction doesn't show up on block explorer but the cancelling transaction does get confirmed on the block</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144800641-562cb949-181a-479f-b959-81e26d218178.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144800565-c9901586-72f5-4188-8ec7-af8af27ef029.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144800402-857fd24d-958f-4250-bc78-7eb58a764d44.mov>
      </td>
   </tr>
</table>
