### ISSUE TITLE
New Crypto Wallet: connected Ledger hardware not able to send transactions

### ISSUE THREAD

**Issue by DWrigly** [brave/brave-browser#19743]
## Description 
Connected ledger nano cannot send from new brave wallet. 
<img width="363" alt="Screen Shot 2021-11-18 at 11 18 22 PM" src="https://user-images.githubusercontent.com/94882751/143493715-858091f4-8e91-4702-b099-289b0ce6fd40.png">

## Steps to Reproduce

   1. Enable new wallet e.g. Settings -> Wallet -> Default cryptocurrency wallet -> Brave Wallet
   1a. Open new tab
   2. Open wallet, go to accounts e.g. brave://wallet/crypto/accounts
   3. Click 'Add Account'
   4. Follow prompts, add Ledger hardware wallet
   5. Ledger is seen and are imported
   6. Ledger accounts show up under secondary accounts
   7. ERC20 tokens are recognized and show up under 'Portfolio'
   8. Click 'Send' tab upper right hand corner
   9. Select token asset to send
   10. select 100%
   11. paste recipient address in 'To:'
   12. Click 'Send'

## Actual result:

Ledger disconnected, Connect your Ledger
<img width="314" alt="Screen Shot 2021-11-18 at 10 42 54 PM" src="https://user-images.githubusercontent.com/94882751/143494449-83a460f4-c3c4-4631-9c31-486598b345ed.png">
As you can see with the first screen shot, the ledger is connected (device HID)
Additionally, the instructions link leads to no help.

## Expected result:
Transaction is sent.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
macOS Big Sur 11.5.2

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by spylogsster** [comment]
@DWrigly please try in Nightly build, it should be fixed there I think

**Comment by bbondy** [comment]
Closing this until there's an indication that it's not yet fixed.
Likely fixed in 1.33.x by https://github.com/brave/brave-browser/issues/19495
