### ISSUE TITLE
 ens.domains app compat ready only problem with the Brave Wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19747]
From https://community.brave.com/t/app-ens-domains-is-read-only-with-native-brave-wallet/303797

```
When I start the ens.domains app and connect it with the “native brave wallet”, the connection stays “read only” … and I can’t change the parameters of my ens-domains.

If I change back to the old wallet then the wallet is really connected and I can change the parameters of my ens-domains.

Do I miss something?
```

**Comment by bbondy** [comment]
Seems to be working for me, I asked for more details in the issue and asked to clear cookies.

**Comment by liamhession** [comment]
Strangely for me the recommended steps at https://community.brave.com/t/app-ens-domains-is-read-only-with-native-brave-wallet/303797/2 did not work, but after i bit the bullet and installed the MetaMask extension and added funds there, then re-logged into Brave Wallet to check something (after auto-logout), the site automatically refreshed and it was connected to Brave Wallet

Connecting to MetaMask also worked on the site, but it was only then that i saw it connect to Brave Wallet. Either something to do with re-logging in, or MetaMask working allowed Brave Wallet to work somehow
