### ISSUE TITLE
Add Ethereum chain network dialog should list number of decimals too

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19749]
Details view for adding a network doesn't show `Decimals: X` from the payload, where X is a number like 18.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.83 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11941>brave/brave-core#11941</a></li>
         <li>Verified add network now lists Decimal value as well</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/152526183-296e6f6f-c376-4b40-8580-937f2f89ba6c.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152526235-418171c8-7603-4d83-8e1a-1ad653c29e64.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152526196-931d7f9c-b67f-435f-bf1a-ec0c82d19eea.mov>
      </td>
   </tr>
</table>
