### ISSUE TITLE
New Wallet: Snapshot issue

### ISSUE THREAD

**Issue by gergo-szabo** [brave/brave-browser#19744]
## Description 
I tried to vote on snapshot(https://snapshot.org/) with governance token. 

## Steps to Reproduce
   1. Open snapshot proposal
   2. Connect wallet (not automatical as before wallet "UI" change)
   3. Press Yes then Vote button

## Actual result:
1, Incorrect number of tokens displayed!
2, Something went wrong message
![image](https://user-images.githubusercontent.com/46539838/143498846-fa34603f-bf31-4f40-ad3f-61c1bc352a96.png)

## Expected result:
Vote without issue

## Reproduces how often: 
Always reproduced the error message. But when first the wallet first connected it sometimes displays correct number of tokens.

## Brave version (brave://version info)
1.32.106 Chromium: 96.0.4664.45 (Hivatalos verzió) (64 bites)
76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
Windows 10 Version 1909 (Build 18363.1916)

## Version/Channel Information:
Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?    No
- Does the issue resolve itself when disabling Brave Rewards?  Not tested
- Is the issue reproducible on the latest version of Chrome?     Not tested

## Miscellaneous Information:
Might be relevant: Adding new tokens via webpage's "Add X token to your MetaMask wallet" buttons are also broken for me.

**Comment by bbondy** [comment]
This was fixed in the last release a few weeks ago here:
https://github.com/brave/brave-browser/issues/20282

Closing this issue.
