### ISSUE TITLE
User report of not enough gas when sending from Polygon

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19748]
See https://community.brave.com/t/unable-to-send-funds-out-of-wallet/303120
Cc @onyb

**Comment by HEagle18** [comment]
Just completed a send on Polygon on 1.50. @onyb @srirambv are we happy to close this out ?

**Comment by bbondy** [comment]
maybe ask the user if he's still seeing the issue

**Comment by HEagle18** [comment]
Closing out. Haven't heard back from user and haven't had any issues sending from Polygon or heard any issues from the community in the past few months.
