### ISSUE TITLE
Edit account name shows password error message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19753]
## Description 
Edit account name shows password error message

## Steps to reproduce 

   1. Enable wallet and create an account
   2. Go to account and add an account
   3. Enter random values for private key and tap on Add, shows error for account name field
   4. Tap on error message, shows password criteria error message

## Actual result 

https://user-images.githubusercontent.com/17010094/143522548-610f986b-9663-4855-b864-ad9c752c8e01.mp4

## Expected result
Should not show error message, rather should not enable the add button until proper details are entered

## Issue reproduces how often 
Easy 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):All
   - Android version: 10
   
## Brave version
1.33.90

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @wchen342

**Comment by SergeyZhukovsky** [comment]
I fixed in the context of that PR https://github.com/brave/brave-core/pull/11398
