### ISSUE TITLE
Only default bg image is displayed in NTP when "New Tab Page Branded Wallpapers" flag is off

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19754]
When `New Tab Page Branded Wallpapers` is off from the brave://flags,
NTP only shows default bg image because NTPBackgroundImagesService is not
launched.

**Comment by simonhong** [comment]
@rebron @bsclifton I think we can remove this feature flag because user can control in NTP settings. WDYT?

**Comment by bsclifton** [comment]
@simonhong SGTM! 😄

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.72 Chromium: 97.0.4692.56 (Official Build) beta (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Used the testplan from https://github.com/brave/brave-core/pull/11307.

1. new profile
2. launched Brave
3. loaded `brave://flags`
4. confirmed the feature flag `brave://flags/#brave-ntp-branded-wallpaper` no longer exists
5. confirmed both new-tab page wallpapers as well as Sponsored Images were still working/toggleable

`1.33.106` | `1.35.72` | toggled off | wallpaper | Sponsored Image
-----------|----------|--------------|-------------|--------------------
![19754-1](https://user-images.githubusercontent.com/387249/148286466-af64de6d-7568-44b0-ab0a-0e501cfc2a56.png) | ![19754-2](https://user-images.githubusercontent.com/387249/148286498-a235edf6-4a03-4228-b750-ff3d2e02c648.png) | ![19754-3](https://user-images.githubusercontent.com/387249/148286717-16322ee9-38b0-4f8d-8790-df91139c387f.png) | ![19754-4](https://user-images.githubusercontent.com/387249/148286743-a3d4d893-abea-49cd-8d45-c169d7fc0455.png) |![19754-5](https://user-images.githubusercontent.com/387249/148286747-1b6b58a1-849a-4e3c-ba2c-cd5df01ab28c.png)
