### ISSUE TITLE
OpeanSea selects last connected account when multiple accounts are given

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19750]
From community:
https://community.brave.com/t/brave-wallet-cannot-be-find-by-any-web3-app/303392

```
when you have multiple accounts connected for example to OpenSea and you switch account in Brave wallet it won’t change the account at OpenSea. In previous version of Brave Wallet it worked fine.
```

---

Upon testing what seems to happen currently is that it selects the last item in the allowed accounts array.
I think the only way for us to be compatible without the site changing is for us to only allow 1 site to have permission at a time via eth_accounts like MetaMask has.

**Comment by bbondy** [comment]
Upon testing what seems to happen currently is that it selects the last item in the allowed accounts array. 
I think the only way for us to be compatible without the site changing is for us to only allow 1 site to have permission at a time via eth_accounts like MetaMask has.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified changing account on wallet automatically changes it on Opensea as well</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/149358575-a7da733a-f173-4f6a-b19c-762277c5c1bd.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/149358201-c9469895-376b-41e4-99e9-ccb5d11bfad6.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/149358138-5c430d36-bbc7-4222-9246-df57f1546ada.mov>
      </td>
   </tr>
</table>
