### ISSUE TITLE
Add a new account doesn't pre-populates with placeholder name

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19752]
## Description 
Add a new account doesn't pre-populates with placeholder name

## Steps to reproduce 

   1. Enable Wallet
   2. Create an account, names it as `Account 1` by default
   3. Go to Accounts and add a new account
   4. No placeholder name is set for the account
   5. Click on add, creates a second account with out a name. 
   6. Edit to update the nameless account, you'll run into [#19751](#19751)

## Actual result 

https://user-images.githubusercontent.com/17010094/143520645-6c25771b-1e30-4a64-8666-c377a4965f19.mp4

## Expected result
Should pre-populate the account names so user can modify it later if need be

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.33.90

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @wchen342 @AlexeyBarabash

**Comment by kjozwiak** [comment]
Added missing `1.34.x` milestone as this landed in `master` which is currently `1.34.x`.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.93 x64 Beta build
- Verified add account pre-populate with placeholder name

https://user-images.githubusercontent.com/17010094/143909983-68179a4c-d8e4-4bbe-ba92-a441ae256373.mp4


------------
Verification passed on Samsung Tab A with Android 10 running 1.33.93 x64 Beta build
- Verified add account pre-populate with placeholder name

https://user-images.githubusercontent.com/17010094/143910055-f5584d9a-1823-4fb6-87f9-7d56acf7c712.mp4
