### ISSUE TITLE
Edit account without name shows add account causing it to create a new one

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19751]
## Description 
Edit account without name shows add account causing it to create a new one

## Steps to reproduce 

   1. Enable wallet and create an account
   2. Go to Accounts and tap on `Add an Account`
   3. Tap on Add to create an account. Doesn't add a name by default
   4. Open the nameless account and tap on rename, Opens add account page
   5. Tap on Add, creates a 3rd account with no name 

## Actual result 

https://user-images.githubusercontent.com/17010094/143519990-6ee26444-52cf-47fd-a1a4-cf2a08eaa34f.mp4

## Expected result
Should remain on edit screen and only update the selected account

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.33.90

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @wchen342 @AlexeyBarabash

**Comment by kjozwiak** [comment]
Added missing `1.34.x` milestone as this landed in `master` which is currently `1.34.x`.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.93 x64 Beta build
- Verified edit account name doesn't show `Add account` 
- Encountered [#19809](#19809)
------------
Verification passed on Samsung Tab A with Android 10 running 1.33.93 x64 Beta build
- Verified edit account name doesn't show `Add account` 
- Encountered [#19809](#19809)
