### ISSUE TITLE
Have a way to filter tokens to some minimum threshold

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19758]
"Default to show tokens that have $100 or greater value. Allow this threshold to be modified. And allow tokens above the threshold to be hidden on an individual basis."

Maybe an option like "Show small balances" that will hide anything below a certain level.

Via
https://community.brave.com/t/feature-request-improve-display-of-wallet-tokens/303246

**Comment by Douglashdaniel** [comment]
We now have a way to hide small balances! :)
Introduced in https://github.com/brave/brave-core/pull/18727

Closing this issue out!

![Screenshot 26](https://github.com/brave/brave-browser/assets/40611140/c5c7d119-cfc4-4d72-b118-50f36906a1b6)
