### ISSUE TITLE
Wallet gas issue

### ISSUE THREAD

**Issue by rafalohaki** [brave/brave-browser#19767]
latest version: V1.32.113
still cant use transactions 
![image](https://user-images.githubusercontent.com/20607107/143603798-0ec2fa1a-e0b1-44ba-b17f-85f1165a85a8.png)
![image](https://user-images.githubusercontent.com/20607107/143603497-ed123fe0-443d-4c85-a446-d52e1cbc4651.png)
when set gas fee, it change back to 0.
when i try to swap some tokens bnb/token, it showing it sends 0 bnb

PS. PLS FIX IT

**Comment by bbondy** [comment]
I believe this is a duplicate of https://github.com/brave/brave-browser/issues/19821
cc @onyb to confirm. I'll close this as a dupe but please re-open if not.

**Comment by rafalohaki** [comment]
why my issues are always duplicate but i write them days before...

**Comment by onyb** [comment]
I confirm that this issue is the same as #19821.

@rafalohaki Thanks for reporting these issues - we're simply closing this one because a pull request has already been created and linked to the other issue.

**Comment by bbondy** [comment]
Yep the reports are very helpful, it is just random if 2 issues exist for the same problem which gets picked when fixed. So not a negative thing :) Thanks for reporting.
