### ISSUE TITLE
Add a way to reset local transaction / nonce information

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19760]
It's common for developers using something like Ganache to reset state on the server. 
We should have a way to reset the nonce info without having to restore the whole wallet. 

Via community: 
https://community.brave.com/t/how-to-reset-set-transaction-nonce-in-brave-wallet-without-deleting-all-accounts/303038

But I've also had to do this before.

**Comment by DefiDebauchery** [comment]
Also incredibly helpful if you have RPC issues on alt-chains and submitted txns never complete.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.83 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11721>brave/brave-core#11721</a> description</li>
         <li>Verified a new setting is available under <code>brave://settings/wallet</code></li>
         <li>Verified typing <code>Yes</code> in the new setting clears all transactions from all networks on both page and panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/152532291-213c0163-96f7-484f-9236-b38c1bb6a19e.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152532028-5d3090a5-56c3-4267-82aa-75bd0b3a545c.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152531734-1d1d31aa-d73a-4fc4-b884-837cfd6000ab.mov>
      </td>
   </tr>
</table>

**Comment by jamesmudgett** [comment]
Will need to add this to Android

**Comment by kjozwiak** [comment]
@jamesmudgett we don't re-open already resolved/tested issues as this was already released via `1.36.x` on desktop. If we need this on `Android`, please create a new independent issue that will be used for `Android`.

**Comment by kjozwiak** [comment]
@jamesmudgett @srirambv assuming we can remove the `OS/Android` label in this case? Seems like this basically landed on `desktop` only so we'll need a new issue as mentioned above for `Android` specifically.

**Comment by Pavneet-Sing** [comment]
thanks @kjozwiak. An for issue for android has been created and linked [21457](https://github.com/brave/brave-browser/issues/21457). just renamed the issue title to mimic the same.

cc: @srirambv

**Comment by kjozwiak** [comment]
awesome, thanks @Pavneet-Sing 👍
