### ISSUE TITLE
Add a way to hide built-in networks

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19764]
Currently testnets that users will never use can't be hidden.
Users would like to hide them: https://community.brave.com/t/feature-request-allow-removal-of-test-networks/302447

**Comment by HEagle18** [comment]
@bbondy we now allow you to select what networks you want to see on the portfolio. if you want to control the networks you want to see to on the panel, they can be changed at brave://settings/wallet/networks. All networks can be hidden except for ethereum, filecoin and solana. Tested on desktop 1.54. All test networks are hidden by default. closing out.
