### ISSUE TITLE
Replace "Wallet" text in Rewards contexts to say "Brave Rewards"

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19768]
## Description

With Brave Wallet now live, there are many text/naming collisions between Wallet and Rewards that cause confusion among users. We want to change any "wallet" or "Rewards wallet" language to just "Brave Rewards", so as to not use the term "Wallet" in Rewards contexts.

## Solution

**Updated Jan 11, 2022:**

![image](https://user-images.githubusercontent.com/11497541/148974923-a59b8c6c-6c72-40b6-b96a-4f1a9193f6e4.png)

Change this to say "Manage Brave Rewards"

![image](https://user-images.githubusercontent.com/11497541/148975108-44278052-9865-4394-91d3-8211a8f92e63.png)

In verified state, change this to just say "Verified" in the Rewards settings page + dropdown panel. 

![image](https://user-images.githubusercontent.com/11497541/149428761-6ec79d83-2a4a-47fc-a334-a7f34a91a8b3.png)

Should just say "Brave Rewards Activity" 

![image](https://user-images.githubusercontent.com/11497541/149428789-ce604527-90e1-4116-9e22-913951e19711.png)

Should just say "Manage Brave Rewards" 

The funds in your Brave Rewards are virtual [...]

We recommend verifying your Brave Rewards

![image](https://user-images.githubusercontent.com/11497541/149428894-e4dcc004-4271-4ec6-8204-2b838b807846.png)

Restoring with a recovery key will replace your current Brave Rewards profile, so make sure you empty or back up your current Brave Rewards before restoring. 

![image](https://user-images.githubusercontent.com/11497541/149428973-4335442a-fd49-4625-a7d8-5cb866bec909.png)

[...] if you reset your Brave Rewards.

**Comment by Miyayes** [comment]
cc: @rmcfadden3 for thoughts about how to rename this. Goal is to remove "Wallet" language from Brave Rewards sections to avoid naming collisions with the Brave (crypto) Wallet.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.37.82 Chromium: 99.0.4844.51 (Official Build) beta (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)
```
