### ISSUE TITLE
Select network drop down should have a + icon that points to settings for network management

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19763]
Currently a user has no indication that a network can be added to brave://settings/wallet/networks
We should have a + button similar to how we have one for accounts.

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/r6s7sf/comment/hmv2ib6/

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11470>brave/brave-core#11470</a></li>
         <li>Verified add network button is shown on network dropdown list on both widget and panel</li>
         <li>Verified clicking on the <code>+</code> button loads a new tab and loads <code>brave://settings/wallet/networks</code></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Buy Tab on Widget
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150737882-a4154cdb-5d09-4271-bd6d-63e08370577f.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/149722473-25689f39-b39a-435a-96b4-7765cc46bbf6.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/149706027-df846ff7-9740-4237-a6bb-99cab8641e40.png>
      </td>
   </tr>
   <tr>
      <td>Send Tab on Widget
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150737895-0743bfd5-42d5-43aa-b629-94f1474926cc.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/149722538-bd7f7fcf-c1a6-4088-8629-d7140ee2249d.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/149705968-6ede84c8-dae8-4bee-a09c-aa2d8dc1342a.png>
      </td>
   </tr>
   <tr>
      <td>Swap Tab on Widget
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150737910-7682100e-ebac-43f5-91e1-d9a391a79d81.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/149722568-46caa109-06d1-493b-bb81-2b9959b17eb4.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/149705981-0ea3f786-c21a-43a2-b09f-d02adaac6a6c.png>
      </td>
   </tr>
   <tr>
      <td>Wallet Panel
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150737934-0c5fd8e5-ec74-4db6-b285-9ae9d617bc43.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/149722795-4482e59a-45e4-4392-944a-8d7f7672b522.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/149706067-f0009651-aca5-4299-a361-0e1fd1d67471.png>
      </td>
   </tr>
</table>
