### ISSUE TITLE
Send tip option not available for verified creators

### ISSUE THREAD

**Issue by abhi-glitchhg** [brave/brave-browser#19773]
PLEASE USE THE TEMPLATE BELOW TO PROVIDE INFORMATION ABOUT THE ISSUE. 
INSUFFICIENT INFO WILL GET THE ISSUE CLOSED. IT WILL ONLY BE REOPENED AFTER SUFFICIENT INFO IS PROVIDED-->

## Steps to reproduce 

   1.  Open any verified creator account on android browser
   2.  Click on reward  button 
## Actual result 
No `Send Tip` option

## Expected result
Send Tip option expected

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information: I guess after new update this started

- Can you reproduce this issue with the current Play Store version?  yes
- Can you reproduce this issue with the current Play Store Beta version? i don't know 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Can you please add a screenshot? If the publisher is Twitter it wont show as we don't support tipping for Twitter on Android.

**Comment by abhi-glitchhg** [comment]
@srirambv  hey, thanks for reply, today i checked the browser and now the option for tip is coming,
IDk why it was not showing previously, I am closing this issue as of now.
