### ISSUE TITLE
Cannot interact with ens domain names on Ethereum with Brave Wallet

### ISSUE THREAD

**Issue by Prahasaurus** [brave/brave-browser#19779]
I cannot use the Brave Wallet at ENS Domains https://ens.domains/ to claim an airdrop.  To do this I need to "Confirm" a transaction within Brave Wallet.  The wallet connects to the site and opens a pop up, but it won't let me "Confirm" the transaction.  It will only allow me to "Reject" the transaction.

**Comment by srirambv** [comment]
Seems to work just fine. Although it did take a page refresh to see the wallet as connected. Can you try clearing the cache once and see if its working?

**Comment by Prahasaurus** [comment]
It's definitely not working for the airdrop claim, clearing the cache doesn't help.  Here is the exact site within ENS for the airdrop:  https://claim.ens.domains/

I've just spent an hour with ENS trying to resolve, no luck.  They concluded the following:

"It looks like Brave put in  "protection" against contract calls to token addresses..."  They believe the old Brave wallet might work.  Or I need to recreate the wallet outside of Brave.

**Comment by Prahasaurus** [comment]
I downgraded to the earlier version of Brave Wallet and it now works.  But it won't work with the newest version.

**Comment by bbondy** [comment]
That issue was fixed and is live now so you can move back to the new wallet.

**Comment by Prahasaurus** [comment]
Thanks!
