### ISSUE TITLE
Accessibility Text-Cursor always enabled and visible

### ISSUE THREAD

**Issue by looterz** [brave/brave-browser#19776]
## Description 

The chrome accessibility text cursor always appears after clicking somewhere with text, with no setting in brave to disable it.

## Steps to Reproduce

   1. Open Brave
   2. Click nearly anywhere on any web page

## Actual result:

![56a892d8-387d-45ec-8de3-92ae2f493a72](https://user-images.githubusercontent.com/1891673/143661106-3549af5c-60cd-47fb-93f4-d3a21b791c6a.gif)

## Expected result:
No accessibility text-cursor when clicking anywhere.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

![bd274128-208d-4c7b-9b08-350c1508355f](https://user-images.githubusercontent.com/1891673/143661134-d9cd6f30-e04e-4774-a516-8c7f06ef17b5.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No (they have an option to control this behavior)

## Miscellaneous Information:

This issue only started after updating to the above version of Brave. There is more information about this setting in chrome [here](https://support.google.com/chrome/thread/77878717/there-is-a-text-cursor-bug-in-my-chrome-that-causes-the-blinking-cursor-to-appear-everywhere-i-click?hl=en), but accessibility setting are inaccessible in Brave.

**Comment by iwaqarhussain** [comment]
I also don't see any setting for caret browsing. You can toggle caret browsing by pressing `F7`

![2021-11-27 13_12_54-Turn on caret browsing_](https://user-images.githubusercontent.com/28485033/143673780-79bb7281-26d5-49e1-8b93-1785d30f03ee.png)

**Comment by looterz** [comment]
> I also don't see any setting for caret browsing. You can toggle caret browsing by pressing `F7`
> 
> ![2021-11-27 13_12_54-Turn on caret browsing_](https://user-images.githubusercontent.com/28485033/143673780-79bb7281-26d5-49e1-8b93-1785d30f03ee.png)

That fixed it for me, must have hit F7 by accident at some point. Brave really needs an accessibility options area similar to chrome for these types of flags.
