### ISSUE TITLE
No visual indication that Wallet networks are editable; impossible to remove

### ISSUE THREAD

**Issue by tredondo** [brave/brave-browser#19781]
In `brave://settings/wallet/networks`, once you define a chain, there's no UI that indicates how to edit or remove the network

![image](https://user-images.githubusercontent.com/10043369/143723769-664c2b2c-6dab-4f69-9bc9-38c17e59fc8f.png)

## Brave version (brave://version info)

Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux

## Version/Channel Information:
Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

## Miscellaneous Information:

I figured out that double-clicking the network opens the "Add new network" form.

**Comment by srirambv** [comment]
You can only remove after changing the selected network to something else (Mainnet/Testnet). Change the network to something else and reload the network page to get the trash icon to delete the entry

![image](https://user-images.githubusercontent.com/17010094/143819482-8a83f0fc-9cd8-4b5f-9272-b4fb55613f6c.png)

**Comment by tredondo** [comment]
Thanks for clearing that up.

Would it help other users if the UI indicated this requirement somehow? For example by having a disabled 🗑️ with a tooltip advising to change the network to something else in order to delete that one?
