### ISSUE TITLE
Wallet transactions: show exact time as tooltip when hovering on the relative time ago

### ISSUE THREAD

**Issue by tredondo** [brave/brave-browser#19789]
## Description 
In the wallet transactions, the time is only given approximately, e.g."1m" or "8h". It's customary to show the exact time when mousing over such labels.

## Steps to Reproduce

   1. Find a transaction in your wallet
   2. Mouse over its timestamp

## Expected result:
![image](https://user-images.githubusercontent.com/10043369/143764317-3ed58c06-8010-4074-b832-2ff178ad11f1.png)

## Brave version (brave://version info)
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux

## Version/Channel Information:
Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.93 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified tooltip shows exact transaction time when hovered over</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/20774>#20774</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Max window screen
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/151549937-7b6c4ad7-5dfb-4d6f-af8b-772376e00825.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151548337-b0dcc7a2-07fc-4753-ad5b-11eea42172ef.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151549120-f6e29c4a-8c25-47d6-a552-62a83e96a969.png>
      </td>
   </tr>
   <tr>
      <td>Default browser window size
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/151549959-f57292dd-557e-4146-9d0e-b0653d029fe9.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151550542-4b80749c-daf2-45c7-866f-8b6329c01703.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151549492-43723bf8-ade2-47b7-83b1-02833194925f.png>
      </td>
   </tr>
   <tr>
      <td>Min width window size
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/151549999-171da6b8-fb3a-48b1-aae8-a5267ac1efcc.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151548522-4192cbf0-54f9-46ad-a095-4d99a1c7cb38.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151549539-e6d08840-febe-4d60-bf00-c7c2fbc09613.png>
      </td>
   </tr>
</table>
