### ISSUE TITLE
Deleting a custom RPC URL should remove input field

### ISSUE THREAD

**Issue by tredondo** [brave/brave-browser#19782]
## Description 
At brave://settings/wallet/networks, add a new network (see #19781), then double click it

## Steps to Reproduce

   1. brave://settings/wallet/networks
   2. Add a new network, e.g. [BSC](https://docs.binance.org/smart-chain/wallet/metamask.html)
   3. Make sure to add all three RPC URLs
   4. Click "Submit"
   5. Double-click the network
   6. Delete the last 2 RPC URLs.
   7. Try to Submit

## Actual result:
![image](https://user-images.githubusercontent.com/10043369/143723808-cac5886b-d689-41ed-bfbb-539f319b8fef.png)

## Expected result:
Delete the URLs either with a UX affordance, or by not erroring out if the user has cleared those fields.

## Reproduces how often: 

Every time

## Brave version (brave://version info)
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux

## Version/Channel Information:
Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

## Miscellaneous Information:
Adding the BSC mainnet from [these settings](https://docs.binance.org/smart-chain/developer/rpc.html) resulted in a ridiculous BNB balance (trillions).

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.34.67 Chromium: 97.0.4692.56 (Official Build) beta (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)
```

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified deleting a custom RPC URL shows `Invalid Address` for the input field but still allows to click on `Submit` button
- Verified deleting RPC URL and clicking on `Submit` shows confirmation of updating the custom network 
- Verified selecting `Ok` updates the list and removes the URL and updates the network details

Removed URL | Delete Confirmation | Updated Network details
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/147934562-7c8527e1-9e13-448c-8e58-15b814690e06.png) | ![image](https://user-images.githubusercontent.com/17010094/147934589-978ce4e9-06f2-443a-a100-b0a9cd804f35.png) | ![image](https://user-images.githubusercontent.com/17010094/147934621-6e6aeb42-6dda-44d0-bfb0-3702392bcc99.png)

--------------
Verification passed on 

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | Linux

- Verified deleting a custom RPC URL shows `Invalid Address` for the input field but still allows to click on `Submit` button
- Verified deleting RPC URL and clicking on `Submit` shows confirmation of updating the custom network 
- Verified selecting `Ok` updates the list and removes the URL and updates the network details

Removed URL | Delete Confirmation | Updated Network details
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/147934900-74215934-0aff-4605-8a36-98ecb01b8d6b.png) | ![image](https://user-images.githubusercontent.com/17010094/147934916-95aef7aa-e000-4943-8ee0-f141b18368cc.png) | ![image](https://user-images.githubusercontent.com/17010094/147934933-3e6ddaa8-732f-4057-a410-3307a8c5881d.png)
