### ISSUE TITLE
Brave reloading open tabs when I switch to them

### ISSUE THREAD

**Issue by echosa** [brave/brave-browser#1978]
## Description 
I've been using Brave for the last 6 or 7 hours for everything I do, work and personal. My previous usage with Brave has been mostly one-off sites and things aren't working right in other browsers, so I decided to give Brave a full-blown try.

I have 4 pinned tabs open and 11 non-pinned tabs. I just switched to a tab I hadn't looked at in a few hours, and it reloaded. I switched to another tab, and it reloaded. I got curious and went through all my tabs, and most of them reloaded, including two of the pinned tabs.

## Steps to Reproduce
I'm not exactly sure how to reproduce. Maybe just keep some tabs open for a few hours, then click back to them? 

## Actual result:
Tabs reload when clicked.

## Expected result:
Tabs should not have to reload when clicked.

## Reproduces how often: 
Not sure. I've only been seriously using Brave for half a day or so, so this is the first time I'm encountering this issue.

## Brave version (brave://version info)
Brave | 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? I don't know.

**Comment by echosa** [comment]
Oh… apparently this is a "feature" in Chrome/Chromium. Apparently it can be turned off, but why is it even necessary? 

https://superuser.com/questions/1048029/disable-auto-refresh-tabs-in-chrome-desktop/1049471

**Comment by Palando** [comment]
This can not be deactivated anymore. This "feature" is so anoying, to have to wait after so many tab switches and my PC has many GB of free RAM! I go back to Firefox. (I blame not the brave team. It's Googles fault.)

**Comment by bsclifton** [comment]
@Palando you can try disabling tab discarding; the side effect is that more RAM would be used, as the tab is not unloaded

Try visiting chrome://flags/#proactive-tab-freeze-and-discard and marking this as `Disabled`

**Comment by chelder86** [comment]
> @Palando you can try disabling tab discarding; the side effect is that more RAM would be used, as the tab is not unloaded
> 
> Try visiting chrome://flags/#proactive-tab-freeze-and-discard and marking this as `Disabled`

I don't see that option on Brave. I'm on Mac Mojave.

I've this problem (which did **not** occur 2 weeks ago!!)
