### ISSUE TITLE
Wallet: "Allow this app to spend your ?" [what?]

### ISSUE THREAD

**Issue by tredondo** [brave/brave-browser#19785]
## Description 
Tried to use dYdX. After connecting, you must Enable USDC. That transaction generates a prompt that seems to be missing the currency name.

## Steps to Reproduce

   1. Go to https://trade.dydx.exchange/trade/BTC-USD
   2. Connect Brave's wallet
   3. Click "Deposit" then "Enable USDC"

## Actual result:
![image](https://user-images.githubusercontent.com/10043369/143724049-db4f72a5-681a-444b-ad39-8f211dc3aeb5.png)

## Brave version (brave://version info)
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux

## Version/Channel Information:
Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by srirambv** [comment]
cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment]
This issue happens when the token that you are allowing to spend is not set as a visible asset in your portfolio. 

If the token that you are allowing to spend is not set as one of your visible tokens we do not have a record of it being one of your assets nor do we know how much of that asset you own that you can allow to be spent. 

Will likely need to be resolved by an backend API to allow us to get that information from Etherscan, etc... first before front end can be resolve this issue.

**Comment by Douglashdaniel** [comment]
Looks like the API needed is in the works https://github.com/brave/brave-browser/issues/19279 🙂

**Comment by bbondy** [comment]
@Douglashdaniel if the info is in our token registry and not a visible asset I think this can be supported.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11736>brave/brave-core#11736</a></li>
         <li>Verified panel correctly shows the token name in Allow spend screen</li>
         <li>Verified allow spend shows the token name correctly whether it is listed in visible assets or not</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/153843385-95513afb-6803-42ef-a784-e1bfaa20cd3c.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153844958-5b81c10c-e22b-47bb-bdba-1d6db2bc7e52.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153844868-08ed83d1-39be-4852-9647-675362a9106a.mov>
      </td>
   </tr>
</table>
