### ISSUE TITLE
`MICROSOFT-EDGE` Links Don't Open In Brave

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#19786]
## Description 
Brave has provided users to open specific links that open in only Microsoft Edge, to open in Brave, when it's set as the default browser. But, that option is no longer available.

## Steps to Reproduce

   1. Search for "Default apps" in Windows Search.
   2. When opened, click on Brave.
   3. No option  to let Brave open `MICROSOFT-EDGE` links.

## Actual result:
Brave is not shown  as an option to `MICROSOFT-EDGE` links.

![image](https://user-images.githubusercontent.com/80682093/143729225-4bb31965-afd3-4b16-98f5-d374de055e95.png)

## Expected result:
Brave should be seen as an option to `MICROSOFT-EDGE` links.

## Reproduces how often: 
Always

## Brave version (brave://version info)
1.32.113

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Operating System: Windows 11 Home (22000.348)

**Comment by dreag2121** [comment]
So was this fixed or nah? I am personally having some issues with it.

**Comment by bsclifton** [comment]
Hi folks - we added this feature a while back... but Microsoft broke this in a Windows 10 update. More information at https://github.com/brave/brave-browser/issues/19402

Because it's no longer possible to solve, I'm going to close the issue as `wontfix`
