### ISSUE TITLE
Wallet swap: set the focus in the coin search field

### ISSUE THREAD

**Issue by tredondo** [brave/brave-browser#19788]
## Description 
In the wallet, swap dialog, after clicking the input or output currency, the "Select from" combo box should set the focus in the "Search coins" field.

## Steps to Reproduce

   1. Go to `brave://wallet/crypto/portfolio/ETH`
   2. Click Swap
   3. Click "ETH" or "BAT"

![image](https://user-images.githubusercontent.com/10043369/143764131-98ed612a-2ba4-42c4-83cc-329fcc5cf66f.png)

## Brave version (brave://version info)
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux

## Version/Channel Information:
Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by not-so-rabh** [comment]
Is it okay if I take up this?

**Comment by evanrittenhouse** [comment]
@muliswilliam can I take this one? Saw that you self-assigned, but happy to take it up if you're busy.

**Comment by muliswilliam** [comment]
@tredondo Go ahead

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.108 Chromium: 99.0.4844.51 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11923> brave/brave-core#11923</a></li>
         <li>Verified selecting Swap tab on widget automatically sets focus on the input field of From token</li>
         <li>Verified selecting the token name sets focus on the search coin list</li>
         <li>Verified selecting token from the Swap tab on panel also sets focus on the coin search field</li>
        </ul>
      </td>
   </tr>
</table>
