### ISSUE TITLE
The "site" operator isn't working

### ISSUE THREAD

**Issue by onchov** [brave/brave-browser#19783]
## Description 
The "site" operator in search queries isn't working for me anymore.

## Steps to Reproduce

   1. Enter a search query containing the "site" operator, eg "uhren site:de".
   2. Confirm search with the Enter key or search button.

## Actual result:

"This site can’t be reached
The webpage at https://search.brave.com/search?q=uhren+site%3Ade might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED"

## Expected result:
Search results.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Affects both Windows and Linux. Does not affect Android.

WINDOWS:
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 2004 (Build 19041.1348)

LINUX:
Brave	1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
Revision	76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS	Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

![site](https://user-images.githubusercontent.com/76524364/143723924-78ab1a57-2327-4e95-9339-6bbbde290cee.jpg)

**Comment by rebron** [comment]
@onchov Can you try your query again? I'm getting results for your query.

**Comment by onchov** [comment]
Same as before, tried on 3 or 4 machines. I switched the search setting from "All regions" to "Germany" to check if there's a conflict, but that doesn't seem to help, either. I tried with my VPN both on and off, also no changes.

**Comment by onchov** [comment]
The issue persists as of:

Brave | 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}

**Comment by onchov** [comment]
The issue seems gone.

As of 1.62.156 Chromium: 121.0.6167.139 (Official Build) (64-bit) the search works fine and respects the "site" operator.

Closing, thank you.
