### ISSUE TITLE
Load new content is shown on other pages rather than on NTP

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19795]
## Description 
Load new content is shown on other pages rather than on NTP

## Steps to reproduce 

   1. Follow steps from [#19794](#19794) to trigger load new content
   2. Open a new tab and load a top tile
   3. `Load new content` message is still shown on a webpage that is loaded or chrome internal page
   4. Clicking on it results in crash (logged  [#19794](#19794))

## Actual result 
<img width=500 src=https://user-images.githubusercontent.com/17010094/143824204-6ba8ed2c-df6a-4123-a0bd-02cbcf0df0ca.png>

## Expected result
Only show on NTP

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.34.43

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @brave/legacy_qa

**Comment by stephendonner** [comment]
Hrm; @alexsafe I can still easily reproduce this using `1.34.64, Chromium 96.0.4664.110` on a Google Pixel XL running Android 9.0.

Any idea what's up?

![Screenshot_20211215-111413](https://user-images.githubusercontent.com/387249/146250740-a6cd871b-7773-4c9a-b45a-a9c333b4e393.png)

**Comment by LaurenWags** [comment]
@stephendonner I believe you're correct, I think this also landed after the train migration and is in 1.35.x. 

@alexsafe mind updating the issue and PR to have the correct milestones?

**Comment by stephendonner** [comment]
Moved this and https://github.com/brave/brave-core/pull/11335 over to the `1.35.x` milestone, where this landed.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.58, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.0.

Tried @srirambv's steps which easily reproduced this for me before, and can no longer reproduce it.

example | example
----------|----------
![Screenshot_20211225-162148](https://user-images.githubusercontent.com/387249/147371519-522d7442-96a5-4cdc-a21c-5dcf080fc39c.png) | ![Screenshot_20211225-162208](https://user-images.githubusercontent.com/387249/147371527-33e1cfd7-f9e9-4efb-a231-b818b09d3b6b.png)
