### ISSUE TITLE
News onboarding position is wrong

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19797]
## Description 
News onboarding position is wrong

## Actual result 
<img width=500 src=https://user-images.githubusercontent.com/17010094/143824829-d451cae0-e595-4ba2-a6cc-3776414f056c.png>

## Expected result
Should be placed below the widgets similar to iOS

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes
 
## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.34.43

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @brave/legacy_qa

**Comment by stephendonner** [comment]
@alexsafe I think perhaps this landed in the `1.35.x` branch/milestone, rather than in `1.34.x`?  I'm not seeing the fix in `1.34.63, Chromium 96.0.4664.110`, but can in `1.35.36, Chromium 97.0.4692.45`.

**Comment by LaurenWags** [comment]
@stephendonner yeah, looks like this one didn't make it in to 1.34.x per https://github.com/brave/brave-core/commits/master?after=e24e119e13e82049d82af350e56369436b075d10+454&branch=master

@alexsafe mind updating this issue and the PR with the correct milestone of 1.35.x please?

**Comment by stephendonner** [comment]
Moving this to the `1.35.x` milestone, as the fix landed there.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.58, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.0.

Confirmed the Brave News onboarding is below the new-tab page widget stack.

example | example
----------|----------
![Screenshot_20211224-092203](https://user-images.githubusercontent.com/387249/147366911-fefe2e63-cdbb-4732-a84b-00d537ed0285.png) | ![Screenshot_20211224-092213](https://user-images.githubusercontent.com/387249/147366917-7d7da33b-f2e6-4c83-a3a1-d62ce48804a1.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.77 x64 Beta build
- Verified Brave News is below the widget stack
- Encountered [#20405](#20405)
