### ISSUE TITLE
fingerprinting not blocked at all (browserprint.info, jsfiddle.net/bkf50r8v/13)

### ISSUE THREAD

**Issue by jeroen7s** [brave/brave-browser#1979]
## Description 
when testing browser fingerprinting on browserprint.info (which uses a more realistic dataset than panopticlick) brave doesn't seem to be blocking anything

## Steps to Reproduce
enable fingerprint blocking globally (Block All Fingerprinting)
go to browserprint.info
click fingerprint me
fill in capcha

## Actual result:
nothing is blocked
all fonts are there
the canvas fingerprint and audio fingerprint was captured, 
along with webgl data like graphics card
brave shields report 0 fingerprinting methods are blocked

## Expected result:
fingerprinting should be blocked
canvas fingerprint should be empty
graphics card should not be visible
audio fingerprint should be blocked

## Reproduces how often: 
reproduces every time for me
not tested different browsers versions yet 
(tested Windows only, Not tested on Muon version of Brave)

## Brave version (brave://version info)
Brave | 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)

Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}

### Reproducible on current release:
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by jeroen7s** [comment]
seems like https://jsfiddle.net/bkf50r8v/13/ is also not blocked
https://valve.github.io/fingerprintjs2/ shows fingerprints being blocked though (if i disable adblock since that blocks the fingerprintjs itself instead of the fingerprinting methods)

**Comment by jeroen7s** [comment]
Not reproducible on Linux, fingerprint detection seems to work as intended on Linux
not sure if it's a windows only issue or an issue with my setup

**Comment by tomlowenthal** [comment]
@kjozwiak Can you confirm whether this is reproducible?

**Comment by tomlowenthal** [comment]
@brave/legacy_qa — can you reproduce this?

**Comment by jeroen7s** [comment]
just re-tested using updated version of brave, now both sites show "device recognition" being blocked
so I guess it was just an issue in older versions of brave

**Comment by tomlowenthal** [comment]
🎉
