### ISSUE TITLE
Wallet "Visible assets" dialog: set the focus in the search field

### ISSUE THREAD

**Issue by tredondo** [brave/brave-browser#19790]
## Description
When the user clicks the "+ Visible assets" button in the Portfolio, it would help to set the focus in the search field of the popup dialog.

## Steps to Reproduce

   1. Go to brave://wallet/crypto/portfolio
   2. Click "+ Visible assets"

## Expected result:
![image](https://user-images.githubusercontent.com/10043369/143764382-f1ca853a-914b-4c67-9a3f-4d8d89d9cf53.png)

## Brave version (brave://version info)
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux

## Version/Channel Information:
Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by Douglashdaniel** [comment]
Currently have an issue pending for this! 🙂  https://github.com/brave/brave-browser/issues/19326

**Comment by bbondy** [comment]
Closing this one as a duplicate since it'll be covered in the above issue that Douglas mentioned. Thanks for posting though!
