### ISSUE TITLE
Brave News on menu doesn't do anything

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19796]
## Description 
Brave News on menu doesn't do anything

## Steps to reproduce 

   1. Enable Brave news
   2. Open menu
   3. Tap on Brave News, does nothing

## Actual result 
Brave News on menu doesn't do anything

## Expected result
Should load Brave news settings menu or open a new tab and focus on first article 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.34.43

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @brave/legacy_qa

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.34.63, Chromium 96.0.4664.110` on a Google Pixel XL running Android 9.0.

Confirmed using the inline testplan that enabling `Brave News` via `brave://flags` and tapping on the `Brave News` menu item under `Settings` loads content after explicitly turning it on.

example | example | example | example
----------|-----------|----------|----------
![news-1](https://user-images.githubusercontent.com/387249/146238675-be78be2d-7e00-440f-b834-d8251ab293b5.png) | ![news-2](https://user-images.githubusercontent.com/387249/146238699-4c31d227-be20-41a8-aaae-1ad33b21b0d2.png) | ![news-3](https://user-images.githubusercontent.com/387249/146238734-69e03411-8f16-4816-8190-2d87d87f3877.png) | ![news-4](https://user-images.githubusercontent.com/387249/146238764-63dbff3c-357c-4804-8ae2-3bb857112890.png)
