### ISSUE TITLE
ETH swap from Wallet botched, out of gas, over $100 fee never refunded

### ISSUE THREAD

**Issue by XfeRecover** [brave/brave-browser#19804]
## Description 
Yesterday I did my first swap with the new integrated Brave wallet, from ETH to USDC. The quoted fee was outrageous ($130), but that's not Brave's fault.

The problem is that the transfer ran "out of gas". Here is the [tx](https://etherscan.io/tx/0xbcebe61eef68f133dd1fb7eb99cf995fd08ba8408926a8994060b752f2d0d0c1).

I don't see any way in Brave to complete or speed up the transfer.

Brave didn't warn me about the possibility of insufficient gas. **This issue cost me $121** (as of today). In my country, that is food for two weeks.

I'm not a super-technical user, so I don't really understand all the inner workings of gas. If this occurrence is likely, there should be a big red warning before users attempt swaps (or presumably transfers as well).

I would also appreciate a refund of the fee.

## Steps to Reproduce
As you can imagine, I won't attempt to reproduce this.

## Brave version (brave://version info)
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux

## Version/Channel Information:
Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by jamesmudgett** [comment]
Needs UI follow up, self-assigning

**Comment by jamesmudgett** [comment]
We've added CoinGecko price difference label to the swap quotes in swap 2.0, currently in Beta. This will be released to production in 1.48 on February, 7 2023
