### ISSUE TITLE
Shields should be capitalized on menu

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19807]
## Description 
Shields should be capitalized on menu

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/143903072-42a97c7d-9033-4708-9c6a-8644afd8c33b.png)

## Expected result
Shields should be capitalized

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @alexsafe @rmcfadden3

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.34.63, Chromium 96.0.4664.110` on a Google Pixel XL running Android 9.0.

Confirmed it now reads `Brave Shields & privacy` in both top-level `Settings` as well as the individual entry.

release | release | beta | beta
--------|----------|------|------
![release-1](https://user-images.githubusercontent.com/387249/146231253-fbff0477-2a5a-4eb0-9089-896eb79f707a.png) | ![beta-2](https://user-images.githubusercontent.com/387249/146231326-6dcadca9-c2d7-424e-9a37-50a1bae7c6dc.png) | ![beta-1](https://user-images.githubusercontent.com/387249/146231322-92b01ae8-e2de-482a-a72e-a1d342b44baf.png) | ![release-2](https://user-images.githubusercontent.com/387249/146231275-acb9a616-0d09-4598-950a-7f7ccb647129.png)
