### ISSUE TITLE
Users are not paid for viewing a few Promoted content Ads

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19800]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18787
Users are not paid for viewing a few Promoted content Ads

## Steps to Reproduce

   1. Clean profile 1.33.x, US region, staging environment
   2. Launch brave and enable rewards
   3. Open an NTP and click on `Show Brave News` 
   4. Scroll down the brave news feed to view `Promoted` content Ad
   5. After viewing the `Promoted` content Ad, open the brave://rewards page
   6. User is not paid for `Promoted` content Ad and there is no ad history listed 

## Actual result:

Users are not paid for viewing a few Promoted content Ads

![image](https://user-images.githubusercontent.com/38657976/143851373-efcc974f-9004-4265-a6ae-53778f70df4b.png)

```
[7024:14284:1129/155017.573:INFO:creative_promoted_content_ads_database_table.cc(527)] Failed to get creative new tab page ad
[7024:14284:1129/155017.573:VERBOSE1:promoted_content_ad.cc(64)] Failed to fire promoted content ad event due to missing creative instance id 2626e169-a372-42ca-af14-b0df795d2819
[7024:14284:1129/155017.576:VERBOSE1:ads_impl.cc(835)] Failed to fire promoted content ad kViewed event for uuid a2ddeb83-0731-4742-95a9-8547f8d8af07 and creative instance id 2626e169-a372-42ca-af14-b0df795d2819
[7024:14284:1129/155019.616:VERBOSE2:tab_manager.cc(86)] Tab id 3 is visible
```

## Expected result:

Users should be paid for viewing all the Promoted content Ads

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.90 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H2 (Build 19044.1387)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @petemill @tmancey @jsecretan

**Comment by btlechowski** [comment]
Works as intended. Promoted content ads are are served by Brave News server, but in order to be paid, the ads catalog needs to contain the promoted content ads. There is a push to change this behavior and have it work the same as inline ads, that promoted content ads are taken from catalog alone.

Having catalog and feed mismatch is expected, but I will let @iambrianfung confirm.

**Comment by iambrianfung** [comment]
@GeetaSarvadnya confirming what @btlechowski said. This is a known limitation.

cc: @jsecretan  @mattmcalister

**Comment by GeetaSarvadnya** [comment]
As per the above comments, closing the issue as expected.

**Comment by newuser-web** [comment]
Facing a similar issue on my android device. I'm using the latest version of Brave. I am viewing NTP sponsored image but in estimating earning it is not getting reflected.

**Comment by tmancey** [comment]
@newuser-web please email me your payment id from brave://rewards-internals so I can look into this for you. My email address is terry@brave.com

**Comment by newuser-web** [comment]
@tmancey Done. Please check.

**Comment by newuser-web** [comment]
@tmancey I have sent you the details. Please check.
