### ISSUE TITLE
Build out Add Suggested Token Panel UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19819]
## Description 
Build out the `Add Suggested Token` Panel UI found in figma

![Screen Shot 2021-11-29 at 1 43 51 PM](https://user-images.githubusercontent.com/40611140/143956564-2889ec6f-43ae-4dbe-9a3b-db35a5fc0620.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.97 Chromium: 98.0.4758.72 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d63e30f73734c5326037b0d94eceed77168d95e1-refs/branch-heads/4758@{#905}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11375>brave/brave-core#11375</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/151584435-b3ae92fc-51d8-4b13-837c-87b7b6ee2833.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151584917-c967df93-cc8a-4106-8d01-6baa6aeb7d13.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151584700-a20ac4b4-e92d-4321-9f77-53dd3aaa5254.png>
      </td>
   </tr>
</table>
