### ISSUE TITLE
Redundant Ordinal Numbers in Wallet Recovery Phrase

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#19813]
## Description 
As [reported by a user](https://twitter.com/catfish161616/status/1465121705270128640), the Brave Wallet recovery phrase is displayed with redundant ordinal numbers at times (when a word appears more than once in the phrase).

## Steps to Reproduce
1. Display your Brave Wallet recovery phrase

## Actual result:
Note redundant ordinal numbers.

## Expected result:
Ordinal numbers should not be duplicated.

## Reproduces how often: 
Easily.

## Brave version (info found on brave://version)
1.34.41

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:
The problem is with the manner in which the ordinal number is determined. We currently look-up the word in the recovery phrase, and use the returned index to determine the ordinal number. This approach will always return the index of the first instance of the word.

```html
<RecoveryPhraseContainer>
  {recoverPhrase.map((word) =>
    <RecoveryBubble key={word}>
      <RecoveryBubbleText>{recoverPhrase.indexOf(word) + 1}. {word}</RecoveryBubbleText>
    </RecoveryBubble>
  )}
</RecoveryPhraseContainer>
```

Since we're using `recoveryPhrase.map` here, we could use the map's `index` value instead:

```html
<RecoveryPhraseContainer>
  {recoverPhrase.map((word, index) =>
    <RecoveryBubble key={word}>
      <RecoveryBubbleText>{index + 1}. {word}</RecoveryBubbleText>
    </RecoveryBubble>
  )}
</RecoveryPhraseContainer>
```

Alternatively, another approach would be to use an HTML ordered list (`<ol>`) and avoid manual-construction of indexes altogether.

**Comment by jonathansampson** [comment]
I just realized that we're using the _word_ as the key as well. While I'm not aware of any issues this could cause here, this too is probably not wise given the potential for duplicity among keys.

**Comment by Christy930** [comment]
I am so grateful to ADRIAN LAMO for assisting me in returning the 790,000 GBP I had been defrauded of by phony binary brokers within 72 hours. HIRE A REPUTABLE HACKING GROUP WHO ARE PROFESSIONAL AND REAL TO STOP BEING SCAMMED BY FAKE HACKERS AND BINARY BROKERS. Adrian is a skilled private hacker who possesses a backup master key that nobody else does. When he helped me regain all I felt had already been lost, it was like a miracle. He also assisted in keeping an eye on my adulterous spouse, about whom I had direct knowledge through her phone. I now have access to all of her incoming and outgoing texts, emails, call records, online browser history, photographs, and videos, as well as her GPS coordinates, Get live broadcasting of all phone conversations with a phone tap. This person specializes in various hacking services, and I'm sure someone out there needs one. All I can do is suggest Adrian Lamo; you may contact him at (HACK WITH ADRIAN LAMO @ GMAIL . COM). BETTER LUCK. His recommendations are widespread, and that fact alone elevates him to the top tier of available professionals.
