### ISSUE TITLE
removing widgets leaves blank area rather than removing the widget completely

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#19814]
## Description 

When removing widgets from NTP, you'll notice that a blank area is left behind rather than removing the widget as expected. Once you open the tab tray and return to the same tab, the NTP will refresh and display the widget correctly

## Steps to reproduce 

   1. download/install https://github.com/brave/brave-browser/releases/tag/v1.34.43
   2. tap on the kabob menu under the `Widget Stacks` via NTP and tap on `Remove Widget`

## Actual result 

**`Pixel 6 Android 12`** | **`S10+ Android 11`**
--------------------------|---------------------------
![Screenshot_20211129-140612](https://user-images.githubusercontent.com/2602313/143934389-81bcf246-79a7-43c8-9414-9ecc71bef47d.png) | ![Screenshot_20211213-100135_Brave - Nightly](https://user-images.githubusercontent.com/2602313/143934411-4edfca47-0bb3-4efd-8c3e-ecbcbace2930.jpg)

## Expected result

Widgets should be removed from the NTP without any issues/leaving a white space behind. NTP should be correctly updated.

## Issue reproduces how often 

100% reproducible when using the STR/Cases mentioned above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `No` (not with `1.33.93`) 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details

   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` & `Samsung S10+`
   - Android version: `Android 11` & `Android 12`
   
## Brave version

* `1.34.43 Chromium: 96.0.4664.45` - **Reproduced**
* `1.33.93 Chromium: 96.0.4664.45` - **Couldn't reproduce**
* `1.32.112 Chromium: 96.0.4664.45` - **Couldn't reproduce**

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @anthonypkeane @srirambv @simonhong @acatarineu

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.58, Chromium 97.0.4692.56` on a Google Pixel XL, running Android 9.0.

Confirmed the blank area doesn't appear after removing both widgets in the stack.

example | example
----------|----------
![Screenshot_20211224-095918](https://user-images.githubusercontent.com/387249/147368038-85798c7b-90c2-4ef7-9ad4-9ca74845ef02.png) | ![Screenshot_20211224-095930](https://user-images.githubusercontent.com/387249/147368043-ea30d4e6-795a-4174-b1fe-5c70549ea3f8.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.77 x64 build
- Verified widget container is not shown when all widgets are hidden
   <img width=400 src=https://user-images.githubusercontent.com/17010094/148719101-66beb403-4171-47c9-bf79-b2ba324fbc48.png>

- Encountered #20410
