### ISSUE TITLE
Make not supported messages more specific

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19815]
Some users are confused that we don't support EVM compatible chains because the buttons are disabled and the tooltip is not specific enough.

https://community.brave.com/t/how-can-i-connect-bsc-on-new-brave-wallet/302966/15
<img width="397" alt="Screen Shot 2021-11-29 at 3 49 02 PM" src="https://user-images.githubusercontent.com/831718/143940884-f5d7839d-52cd-4753-b00f-5abf4efe5b4d.png">

We should instead say Buy support is not available for Avalanche.
and Swap support is not available for Avalanche.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.108 Chromium: 99.0.4844.51 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11848>brave/brave-core#11848</a></li>
         <li>Verified both Buy & Swap on widget and panel shows not supported message with the network name</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/21402>#21402</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td><b>Buy Widget</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/156308697-a6b292cd-42ea-4652-aa14-2e04cb33f7e0.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/156310685-0fb01f4d-09c7-43f6-832a-5864db6e01f4.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/156310113-3ec5adc5-a522-47cc-9485-4d7b638367c3.png>
      </td>
   </tr>
   <tr>
      <td><b>Swap Widget</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/156308727-236580bb-94a5-41a6-ba1d-22396255cf7c.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/156310712-a47af9df-805b-4920-9612-019708f8bac1.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/156310143-59cf068e-9a8c-48ac-bd8f-c76780fe1169.png>
      </td>
   </tr>
   <tr>
      <td><b>Buy on Panel</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/156308756-7e4b6d97-da43-40ec-9b69-272676d26857.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/156310743-24cd9c0d-8a2b-4c20-a25c-59bd925905ca.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/156310179-45142181-d1a5-4b2c-b959-f2ba39a660cb.png>
      </td>
   </tr>
   <tr>
      <td><b>Swap on Panel</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/156308803-3d2391af-1b09-4a55-b3ea-23e22e41ac21.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/156310786-a9999d19-a592-4061-945f-897b1409c935.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/156310214-d7db1236-989f-4573-8bab-643361aa66ea.png>
      </td>
   </tr>
</table>
