### ISSUE TITLE
Can't install Brave beta on Ubuntu 18.10

### ISSUE THREAD

**Issue by mcd223** [brave/brave-browser#1981]
## Description 

When I try to install Brave beta with the instructions from the Brave website it gives me a 403 Error after updating.

## Steps to Reproduce

   1. curl https://brave-browser-apt-beta.s3.brave.com/brave-core-nightly.asc | sudo apt-key add -
   2. echo "deb [arch=amd64] https://brave-browser-apt-beta.s3.brave.com/ `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list.d/brave-browser-beta-`lsb_release -sc`.list
   3. sudo apt update

## Actual result:

Hit:1 http://us.archive.ubuntu.com/ubuntu cosmic InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu cosmic-updates InRelease [83.2 kB]                                                                                 
Get:3 http://us.archive.ubuntu.com/ubuntu cosmic-security InRelease [83.2 kB]                                                                                
Hit:4 http://us.archive.ubuntu.com/ubuntu cosmic-backports InRelease                                                           
Get:5 http://us.archive.ubuntu.com/ubuntu cosmic-proposed InRelease [92.5 kB]                 
Hit:6 http://ppa.launchpad.net/daniruiz/flat-remix/ubuntu cosmic InRelease                                                     
Ign:7 http://repo.vivaldi.com/stable/deb stable InRelease                                                                      
Hit:8 http://ppa.launchpad.net/system76/pop/ubuntu cosmic InRelease                            
Hit:9 http://repo.vivaldi.com/stable/deb stable Release                  
Err:10 https://brave-browser-apt-beta.s3.brave.com cosmic InRelease                            
  403  Forbidden [IP: 151.101.22.217 443]
Get:11 http://apt.pop-os.org/proprietary cosmic InRelease [11.4 kB]      
Get:13 http://apt.pop-os.org/proprietary cosmic/main amd64 Packages [48.2 kB]
Get:14 http://apt.pop-os.org/proprietary cosmic/main all Packages [6,380 B]
Reading package lists... Done         
E: Failed to fetch https://brave-browser-apt-beta.s3.brave.com/dists/cosmic/InRelease  403  Forbidden [IP: 151.101.22.217 443]
E: The repository 'https://brave-browser-apt-beta.s3.brave.com cosmic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

## Expected result:
Brave beta should install

## Reproduces how often: 

everytime

## Brave version (brave://version info)

Current beta as of 11/3/2018 on Ubuntu 18.10

**Comment by avndp** [comment]
I'm facing the same issue. Can't install Brave on Ubuntu 18.10

**Comment by KarmaMonk** [comment]
Workaround 

>sudo gedit /etc/apt/sources.list.d/brave-browser-release-cosmic.list

from
deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ cosmic main

to
deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ bionic main
