### ISSUE TITLE
Change the description for the setting `Automatically sends crash reports to Brave`

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#19822]
We are planning to`HangWatcher` feature which send crash dump when browser hangs.
Before enabling the feature the text should be changed to something like _Automatically sends crash reports and **hangs** to Brave_

Existing
<img width="698" alt="Screen Shot 2021-11-30 at 10 42 46 AM" src="https://user-images.githubusercontent.com/5951041/144108297-37db7f87-b047-4f52-a97a-99e8312f1ddd.png">

Security review: https://github.com/brave/security/issues/659

**Comment by atuchin-m** [comment]
@kjozwiak Do we need to add `release-notes/include` here?

**Comment by rebron** [comment]
cc: @rmcfadden3

**Comment by rmcfadden3** [comment]
@rebron — I feel like the term "Hangs" might not be fully understood. What about something like:

Header: Help improve Brave's features and performance
Body: Automatically send reports to Brave when the browser crashes or hangs on page load

**Comment by atuchin-m** [comment]
ok. One nit: I suggest removing the last part `on page load`. Crashes/hangs can occur on startup/shutdown during page interaction (or even without it). Secondary processes (like gpu/audio/etc) also are taken into account.

Here is my proposal:
![image](https://user-images.githubusercontent.com/45488748/144231196-2c6644a0-6f64-4b80-93a7-e00b71b91969.png)

Also, the feature is relevant for Android too, so let's also change the text in android settings (the text is the same).

**Comment by rmcfadden3** [comment]
@atuchin-m — sure, that works for me. Let's go with what you have in your latest screenshot. I like it!

**Comment by atuchin-m** [comment]
@rebron @akeane
Could you please verify the final screenshots here?
https://github.com/brave/brave-core/pull/11360#issuecomment-1002587237

The discussion about texts: https://github.com/brave/brave-com-resources/issues/424#issuecomment-995031006

**Comment by rebron** [comment]
@atuchin-m Looks good.

**Comment by atuchin-m** [comment]
new keys are added:
IDS_BRAVE_DIAGNOSTIC_REPORTS_PREF
IDS_BRAVE_DIAGNOSTIC_REPORTS_PREF_DESC

keys changed:
IDS_FR_ENABLE_LOGGING
IDS_CRASH_REPORT_PERMISSION_ASK_DIALOG_CONTENT_TEXT
IDS_CRASH_REPORT_PERMISSION_ASK_DIALOG_FOOTNOTE_TEXT

**Comment by anthonypkeane** [comment]
@atuchin-m Looks good.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.22 Chromium: 97.0.4692.71 (Official Build) nightly (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)

Confirmed the UI now reads "Help improve Brave's product stability by automatically sending diagnostic reports when the Brave Browser crashes or freezes."

before | after
-------|------
<img width="1312" alt="Screen Shot 2022-01-07 at 8 54 10 AM" src="https://user-images.githubusercontent.com/387249/148578389-48ca4fc9-1860-4a65-828d-c29d50bf05e3.png"> | <img width="1792" alt="Screen Shot 2022-01-07 at 8 52 00 AM" src="https://user-images.githubusercontent.com/387249/148578202-153af9de-049b-4feb-9964-4f6402977ab6.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.36.29, Chromium 97.0.4692.71` on a `Google Pixel XL` (`arm64`) running `Android 9.0.`

Confirmed it now reads, `"Help improve Brave's product stability by automatically sending diagnostic reports when the Brave Browser crashes or freezes."`

![Screenshot_20220110-150953](https://user-images.githubusercontent.com/387249/148860423-6685b06a-528c-4517-8421-dff86f56e4ac.png)
