### ISSUE TITLE
Confirm button in panel is disabled for zero gas fee

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#19821]
Confirm button in transaction confirmation panel is disabled when fiat value of gas fee is 0. Validations should never be performed on fiat values as some precision will invariably be lost in the process.

**Community thread:** https://community.brave.com/t/moved-bat-to-brave-wallet-and-wont-let-me-move-it-out/304642/9

**Screenshot of a similar report:**
![イラスト](https://user-images.githubusercontent.com/3684187/143989437-a88ed112-afc1-457a-9f23-1d53b20e256a.jpg)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.114 Chromium: 96.0.4664.55 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11330>brave/brave-core#11330</a></li>
         <li>Verified fiat value check is removed for insufficient funds error</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144806766-7282ba71-17f9-4ba0-b3fd-6f3b8dc29bc1.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144803793-b2da2eb9-3856-4c62-aab9-a44038efd578.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144807984-4adc4ffe-c298-4c2d-991f-d22fc6642481.mov>
      </td>
   </tr>
</table>
