### ISSUE TITLE
Save account watchlist button needs bottom padding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19828]
## Description 
Save account watchlist button needs bottom padding

## Actual result 
 
| Samsung Tab | Oppo Reno 5 
-- | --
![image](https://user-images.githubusercontent.com/17010094/144036756-8b927576-24c7-4994-af52-9e068bcf2a4d.png) | ![image](https://user-images.githubusercontent.com/17010094/144036842-33a27781-c791-4b57-b357-d5f062f10063.png)

## Expected result
Better padding 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.33.93

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33.100 x64 build
- Verified text has extra padding

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/145011061-1ce9afda-a739-4ac8-88c8-10df119a98a8.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145011110-d1cb3658-4cc5-4687-beb6-411a5274fba1.png>

**Comment by jamesmudgett** [comment]
This needs bottom padding. The inside padding on the button should be increased left and right, and reduced on top and bottom.
