### ISSUE TITLE
No Internet error when reloading with Dev Tools on

### ISSUE THREAD

**Issue by vlahovivan** [brave/brave-browser#19826]
## Description 

When reloading a page with dev tools opened, you get No Internet error. 

## Steps to Reproduce

   1. Open any page (e.g. https://brave.com/)
   2. Press F12 (the page still looks OK)
   3. Press F5 (No Internet error)

## Actual result:

![image](https://user-images.githubusercontent.com/30372377/144021903-5beed1ce-1433-442e-add0-165800fa828a.png)

## Expected result:
![image](https://user-images.githubusercontent.com/30372377/144021791-b7e2e1c3-fc01-4837-94f4-c833b70f56eb.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

I don't know what these things are

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, nor Firefox

**Comment by rebron** [comment]
@vlahovivan Can you try your steps again? We're not able to reproduce your steps from a few machines and folks we've had try internally.

**Comment by vlahovivan** [comment]
Hello, today I tried the steps again and got the same error. After that, I tried the steps on a private window, where everything worked normally, and after that I tried on a normal window and now the problem is gone. I don't know how this could have fixed it but it did.

**Comment by vlahovivan** [comment]
Today the problem came back again.

**Comment by vlahovivan** [comment]
Almost a year later, I finally found out what the problem was: inside the Network tab, in the Throttling dropdown, the selected option was Offline. After I changed it to No throttling, the problem was gone. I don't remember ever using the Throttling dropdown though, so maybe checking its default options would be a good idea.
