### ISSUE TITLE
Wallet URLs that redirect to the lock screen should go back to the correct URL after unlocking

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19820]
If you type this:
brave://wallet/crypto/accounts

and your wallet is locked, it goes to the unlock URL.

But after you unlock it doesn't go to brave://wallet/crypto/accounts

This makes it a bit harder for people to understand steps when answering in support.

cc @Douglashdaniel

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)
```

Verified using the STR/Cases outlined via https://github.com/brave/brave-core/pull/12135#issue-1123653586.

https://user-images.githubusercontent.com/2602313/160074241-4479673d-9125-49aa-aa47-ccdf059510e7.mp4
