### ISSUE TITLE
Don't hardcode 21000 for gas limit for ETH transfers

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19835]
Some contracts require more gas so we should estimate gas in all cases and use the default values only as a fallback. 
See for example this case: https://etherscan.io/tx/0x79144e4af4324d992438bcdf867d61e299147b1fa6d93c59b56c4e1253165d53

The correct gas that we should’ve suggested is 34914.

**Comment by JanHadari** [comment]
Prosím o pomoc už fakt nemůžu přišel jsem už o všechno a je před vánocemi moc prosím o pomoc

**Comment by JanHadari** [comment]
> Some contracts require more gas so we should estimate gas in all cases and use the default values only as a fallback. 
> See for example this case: https://etherscan.io/tx/0x79144e4af4324d992438bcdf867d61e299147b1fa6d93c59b56c4e1253165d53
> 
> The correct gas that we should’ve suggested is 34914.

Moc prosím o pomoc ja se oděčim něco čekám ještě po vánocích moc Vás prosím

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.114 Chromium: 96.0.4664.55 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11414>brave/brave-core#11414</a></li>
         <li>Verified gas fee isn't hardcoded to 21000 for various kind of transactions</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144819240-0ee2de31-13d5-4281-aaa3-1a2b57601ba9.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144818163-96dcebab-4815-431a-8b12-5dd1c3edaecf.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144817551-3fe61ca5-cb7e-4925-b823-88caf93d2c77.mov>
      </td>
   </tr>
</table>
