### ISSUE TITLE
Wallet doesn't auto-lock after timeout

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19831]
## Description 
Wallet doesn't auto-lock after timeout

## Steps to reproduce 

   1. Set Wallet auto-lock to 1min
   2. Open Portfolio page and keep the phone idle
   3. Wallet doesn't lock
   4. Navigate out of wallet and relaunch wallet, asks password to unlock

## Actual result 
Wallet doesn't auto-lock after timeout

## Expected result
Should auto-lock after timeout even when wallet is active

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.33.94 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @wchen342 @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
That issue will be resolved when this one is done https://github.com/brave/brave-browser/issues/19110. It's in progress right now.

**Comment by SergeyZhukovsky** [comment]
The issue has been fixed and merged in the context of that PR https://github.com/brave/brave-core/pull/11311

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.98 
- Verified steps from issue description 
- Verified wallet auto-locks when the time is passed 
---------
Verification passed on Samsung Tab A with Android 10 running 1.33.98 
- Verified steps from issue description 
- Verified wallet auto-locks when the time is passed
