### ISSUE TITLE
Resetting your wallet doesn't reset selected chain ID until app relaunch

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#19844]
## Description 

When you reset your wallet in settings all of your wallet prefs are erased and you no longer have any keyring, however this does not erase all local state on keyed services used throughout wallet.

In this case `EthRpcController::GetChainId` returns a value not read from prefs until the controller is reinstantiated in a future session which means creating or restoring a wallet after resetting will retain this value instead of resetting back to the default selected chain

## Steps to Reproduce

   1.  Create wallet, change selected network to Ropsten
   2. Reset wallet from settings
   3.  Create a new wallet 

## Actual result:

Selected network will still be Ropsten

## Expected result:

Selected network should be reset to Ethereum

## Reproduces how often: 
Always

## Brave version (brave://version info)
1.34.47 Chromium: 96.0.4664.45 (Official Build) nightly (x86_64)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified setting network to Ropsten and reset wallet resets the chain ID to Mainnet when a new wallet is created</li>
         <li>Verified adding a custom network and setting as default and resetting wallet and creating a new wallet sets default network to Mainnet</li>
        </ul>
      </td>
   </tr>
</table>
