### ISSUE TITLE
Function type text missing in transaction detail box UI

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#19841]
Example: 
<img width="322" alt="Screen Shot 2021-11-26 at 9 04 04 PM" src="https://user-images.githubusercontent.com/4730197/144122850-a284c5b8-4aeb-4a4c-8bc9-d9fea0e409ac.png">

We were using `TransactionType[txType]` which doesn't work anymore after using mojom type directly.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.33.98 Chromium: 96.0.4664.55 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11344>brave/brave-core#11344</a></li>
         <li>Verified Function Type is shown in details tab</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/144604627-373299fa-c79f-4e7a-bc43-285adec92be8.mp4>
      </td>
      <td><video width=600 src=https://user-images.githubusercontent.com/17010094/144604566-0e19132f-2a08-44a1-8d33-be20715f3d84.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144603955-bd22684e-7217-4b92-8937-3b1aa4cc419a.mov>
      </td>
   </tr>
</table>
