### ISSUE TITLE
Yandex Maps not showing properly due to Ad blocking

### ISSUE THREAD

**Issue by eljuno** [brave/brave-browser#1984]
## Description 

Originally reported on Community https://community.brave.com/t/can-not-show-in-brave-browser-yandex-ru-maps/36555?u=eljuno

Yandex Maps is not showing properly. Likely the resources is blocked by Brave's ads and tracker blocker. Brave should display it properly with default shields settings.

## Steps to Reproduce

   1. Open Yandex Maps https://yandex.ru/maps
   2. The maps is not showing
   3. Open per site shields settings, change to _Allow ads and tracking_
   4. Map is show properly

## Actual result:

![image](https://user-images.githubusercontent.com/25360853/47969874-4cabe600-e0b0-11e8-8ffb-9152bdda940d.png)

## Expected result:
![image](https://user-images.githubusercontent.com/25360853/47969899-bd530280-e0b0-11e8-9511-22580be48857.png)

## Reproduces how often: 

Easy.

## Brave version (brave://version info)

Brave Version(about:brave): 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Reproduced on 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit) Win8.1 x64

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?

Changed to _Allow ads and tracking_ show the maps
 
- Is the issue reproducible on the latest version of Chrome? 

NDA

**Comment by GeetaSarvadnya** [comment]
Nytimes videos are not playing due to Ad blockers issue on Version 0.56.12

![nytimes_adblockers issue](https://user-images.githubusercontent.com/38657976/48359961-1a0f7800-e6c4-11e8-8674-2ee0eaafcb11.gif)

**Comment by iefremov** [comment]
Fixed here: https://github.com/mozilla-services/shavar-prod-lists/pull/42/files#diff-005fd85a9f635cd2580b842685143653L5763

**Comment by srirambv** [comment]
This needs to be moved to a proper milestone. @iefremov could you link the brave-core or any other brave repo PR that fixes it and move the issue to appropriate milestone where the fix has landed.

**Comment by iefremov** [comment]
@srirambv Sorry, but its hard to determine the milestone, since the issue was fixed in a 3rdparty repo that provides an ad-blocking list for us.

It was fixed here https://github.com/mozilla-services/shavar-prod-lists/pull/42/files#diff-005fd85a9f635cd2580b842685143653L5763

**Comment by srirambv** [comment]
cc: @bbondy to add the issue to milestone as this would need to be QA'd

**Comment by bbondy** [comment]
@srirambv I put it in 0.59.x.  For cases like this just put it in the closest to release milestone.

**Comment by kjozwiak** [comment]
Verification **PASSED** with `macOS 10.14.2 x64` using the following build:

Brave | 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X
