### ISSUE TITLE
DNS leak

### ISSUE THREAD

**Issue by xooyo** [brave/brave-browser#19847]
## Description
The default settings of Brave could cause dns leak.

## Steps to Reproduce

   1. Set a system proxy(socks5) in Windows 10
   2. Visit https://www.expressvpn.com/dns-leak-test
   3. Check dns servers on the page

## Actual result:
The ISP's dns

## Expected result:
The proxy server's dns

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.33.106 Chromium: 96.0.4664.110 64bit

## Version/Channel Information:
Release

## Other Additional Information:
There are two ways resolve this issue
Disable brave://settings/shields
or
Disable brave://flags/#brave-adblock-cname-uncloaking

Is the issue reproducible on the latest version of Chrome? 
No

**Comment by Brave-Matt** [comment]
@xooyo can you please edit/repost this and fill out the template that appears in the editor so the team can better understand/follow the issue you're reporting?

Thank you.

**Comment by diracdeltas** [comment]
what version of Brave are you on? wondering if this is the issue @antonok-edm fixed recently

**Comment by xooyo** [comment]
@Brave-Matt hi, I find the problem is brave://flags/#brave-adblock-cname-uncloaking, it causes dns leak.

**Comment by xooyo** [comment]
@diracdeltas the newest version. I find the problem is brave://flags/#brave-adblock-cname-uncloaking, it causes dns leak.

**Comment by diracdeltas** [comment]
@xooyo stable, beta, or nightly? you can just copy paste from brave://settings/help
