### ISSUE TITLE
U2fApiRequest doesn't support lifetime options

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#19848]
Chromium added a new permission dialog for soon-to-be-removed U2F API. This permission isn't stored persistently and we shouldn't show lifetime options in the permission dialog.

https://chromium-review.googlesource.com/c/chromium/src/+/3050592

<img width="322" alt="Screenshot 2021-12-01 at 15 14 50" src="https://user-images.githubusercontent.com/5928869/144196792-47524443-1d20-43b6-876f-910f6a27431e.png">

**Comment by goodov** [comment]
It might worth uplifting, but the bug is not breaking, just the UI options doesn't work (and shouldn't) for this exact permission.
cc @rebron

**Comment by stephendonner** [comment]
@goodov please provide us with a testplan for this one too; thanks!

**Comment by goodov** [comment]
> @goodov please provide us with a testplan for this one too; thanks!

I was following this message to reproduce the issue: https://bravesoftware.slack.com/archives/C02DT9F5EP5/p1638295343136800

Basically, you need to have Yubikey, register it as a 2F on https://publishers.brave.com and use it to login. The U2F message should popup without lifetime selection. I was able to test this only on MacOS, because Windows tried to do show some Windows-specific auth methods.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.37 Chromium: 97.0.4692.71 (Official Build) nightly (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. loaded `https://creators-staging.brave.com`
4. entered auth credentials
5. clicked on `Sign up`
6. entered my Brave email address
7. checked my Inbox
8. clicked on the message to confirm my email account
9. loaded `https://publishers-staging.basicattentiontoken.org/publishers/security?locale=en`
10. clicked `Add key`
11. typed `My Yubikey`
12. clicked `Add`

Confirmed the popup appeared, without any lifetime-limitation options

<img width="1595" alt="Screen Shot 2022-01-14 at 9 31 02 AM" src="https://user-images.githubusercontent.com/387249/149562529-142d6c9f-da70-4ef5-8e0e-773373675b55.png">
