### ISSUE TITLE
Reposition Brave items together on menu

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19852]
## Description 
Brave news and Brave Rewards are together however Wallet is separate. All Brave features should be put in one place or next to each other

## Steps to reproduce 

   1. Install Nightly
   2. Restart the browser twice
   3. Open Menu, Brave news is at the bottom above exit and below Reards
   4. Wallet is positioned between bookmarks and recent tabs

## Actual result 
<img width=500 src=https://user-images.githubusercontent.com/17010094/144233746-a57d4014-4fe0-4b4a-bc65-c29f4039310e.png>

## Expected result
Group Brave features together

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes soon
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.35.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @anthonypkeane @jamesmudgett @alexsafe

**Comment by anthonypkeane** [comment]
Going to keep as-is. This will be updated once https://github.com/brave/brave-browser/issues/18603  is completed.

**Comment by cdhiraj40** [comment]
This seems easy, would like to work on this. has it been added via some PR? @srirambv @anthonypkeane

**Comment by GAURAV1-ui** [comment]
Hey @anthonypkeane can I solve this issue?

**Comment by vrindavan** [comment]
Hey, may I ask how did you get that wallpaper? For me it only uses the same old 3-4 walls.

**Comment by meeddhhaa** [comment]
I'm new to open-source and I'd love to work on this issue. 
Is anyone currently working on this one?

**Comment by meeddhhaa** [comment]
> I'm new to open-source and I'd love to work on this issue. Is anyone currently working on this one?

@bsclifton could you assign this one to me?

**Comment by meeddhhaa** [comment]
> I'm new to open-source and I'd love to work on this issue. Is anyone currently working on this one?

@srirambv can you assign this one to me?

**Comment by bsclifton** [comment]
@meeddhhaa sure thing - go for it 😄

**Comment by bsclifton** [comment]
@meeddhhaa I assigned you - but actually I'm going to close this in favor of https://github.com/brave/brave-browser/issues/23465

We have a redesign planned which would make this obsolete
