### ISSUE TITLE
Trezor Popup reopened after closing

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19858]
## Steps to Reproduce

   1. Sign Message with Trezor account
   2. Close Trezor popup when ConnectHardwareView is opened
   3. Trezor popup reopened 

## Actual result:

Trezor popup reopened 

## Expected result:

Wallet panel closed, error forwarded to the page

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11365>brave/brave-core#11365</a></li>
         <li>Verified when popup is closed shows the error on console</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/148066183-0ecbe370-53f0-4eab-8cbb-a26af66154ba.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/148069185-132017ce-c850-4f1d-8e0f-828d826888a2.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/148028127-f7f5b19f-98d7-4e79-97cb-30cea4778d41.png>
      </td>
   </tr>
</table>
