### ISSUE TITLE
Brave News doesn't start unless a new tab is opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19853]
## Description 
Brave News doesn't start unless a new tab is opened

## Steps to reproduce 

   1. Clean install Nightly build
   2. Restart twice to enable Brave News via variation
   3. Do not turn on news via NTP card
   4. Go to Settings -> Brave News -> Turn on News
   5. Close settings, NTP still shows opt-in message for Brave news
   6. Close tab and open a new one, Brave news loads
   7. Go back to settings, Turn on news settings is hidden only Show Brave news is shown

## Actual result 

https://user-images.githubusercontent.com/17010094/144234815-e3ed6c72-a556-4afd-b9b1-2f8d0b80c82f.mp4

## Expected result
Should enable news on the active NTP once enabled via settings

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.35.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @petemill @alexsafe

**Comment by alexsafe** [comment]
@srirambv I think this has been solved for some time. should link I PR and close?

**Comment by srirambv** [comment]
@alexsafe  yes this is fixed. Closing as invalid. No need to open new tab to load the feed

**Comment by Uni-verse** [comment]
Verification completed on `Samsung GS21` running `Android 12` using `1.36.90, Chromium 98.0.4758.87`

- Verified news should enable on the active NTP once enabled via settings
