### ISSUE TITLE
Swipe on widget causes Brave News to scroll up

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19854]
## Description 
Swipe on widget causes Brave News to scroll up

## Steps to reproduce 

   1. Install 1.35.1 and restart twice to trigger news variations to be loaded
   2. Enable Brave News
   3. Open a new tab and try to scroll the widgets, brave news starts to scroll. have to be very careful while swiping between widgets

## Actual result 

https://user-images.githubusercontent.com/17010094/144248531-80754d79-4adb-41b3-9891-8c83a406cca1.mp4

## Expected result
Swipe on widgets should be restricted to widgets alone and not affect Brave news scrolling

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 11
   
## Brave version
1.35.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe

**Comment by srirambv** [comment]
Still an issue on 1.37.5

**Comment by alexsafe** [comment]
@srirambv @stephendonner Linking it to  https://github.com/brave/brave-core/pull/12155 . Not 100% fixed but should be better/easier to scroll.

**Comment by srirambv** [comment]
This is still an issue Follow up issue is logged #21166

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.104 x64 build
- Verified **slow swipe** on widget doesn't cause Brave news to scroll up
- Encountered [#21166](https://github.com/brave/brave-browser/issues/21166)
