### ISSUE TITLE
Purchased content from youtube doesn't prompt to install Widevine (Amazon too)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1985]
## Description 

A user from Twitter reports that purchased content doesn't prompt to install Widevine.

Widevine currently only prompts to install based on URL pattern:

https://github.com/brave/brave-core/blob/a57dc16dba02ea52adcca39a5189533e15168752/common/shield_exceptions.cc#L127
But we don't want to prompt for all of youtube.com for Widevine.

So we'd need a content script or some kind of network filter or other detection mechanism.

If Widevine is already installed, it does play.

## Steps to Reproduce

I haven't tried these steps yet, but I think they would be:

   1. Go to in a new profile https://www.youtube.com/watch?v=RQn-Pqvnzc8
   2. Purchase it
   

## Actual result:

Video doesn't play
![screen shot 2018-11-28 at 12 38 58 pm](https://user-images.githubusercontent.com/2388823/49243508-62b47a00-f3c2-11e8-81a9-81f6c72202d7.png)

## Expected result:

It prompts to install Widevine in the URL bar. Clicking the prompt should make the video play.

## Reproduces how often: 

Always, as long as Widevine is not installed.

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by eljuno** [comment]
+1 from Community for `amazon.de` https://community.brave.com/t/are-there-any-solutions-for-widevinecdm-problem/37966?u=eljuno

**Comment by karenkliu** [comment]
+1 here too

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.2 x64` using the following build:

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Mac OS X

* ensured that I received the Widevine notification on `Netflix`, `YouTube` and `Amazon Prime Video`

**Amazon Prime Video** -- PASSED

<img width="1503" alt="screen shot 2019-01-23 at 4 43 32 pm" src="https://user-images.githubusercontent.com/2602313/51640506-a98d9e80-1f31-11e9-9074-9e5a68d1f270.png">

**Netflix** -- PASSED

<img width="1349" alt="screen shot 2019-01-23 at 5 09 07 pm" src="https://user-images.githubusercontent.com/2602313/51640528-b4e0ca00-1f31-11e9-9203-c6a10b5b8cf7.png">

**YouTube** -- PASSED

<img width="1379" alt="screen shot 2019-01-23 at 5 12 03 pm" src="https://user-images.githubusercontent.com/2602313/51641092-51579c00-1f33-11e9-9287-847d54065774.png">
