### ISSUE TITLE
Navigate to the expected landing page when click first ad

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#19856]
## Description 
We should navigate to the expected landing page when click first ad

## Steps to reproduce 

1. First run with Rewards
2. Received "my first ad"
3. Clicked on "my first ad"
4. Was not navigated to the expected landing page

## Actual result 
Not navigated to the expected landing page

## Expected result
Navigated to the expected landing page

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.68, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.

Confirmed I got `brave.com/my-first-ad` when I tapped on the 1st ad after enabled Rewards.


https://user-images.githubusercontent.com/387249/147793958-d6cde74c-b143-4eaa-8dba-2b78f3daad00.mp4
