### ISSUE TITLE
Improve formatting of input values (send and swap)

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#19855]
Similar to https://github.com/brave/brave-browser/issues/19521, but this issue is about what's allowed to be input in text boxes. It should fix the following:
* Selecting 100% preset should not round the amount. This doesn't need to be the case for other presets.
* Precision of amounts (in Swap) should be increased.
* Very small amounts (in Swap) should not be rounded. Ex: `0.00000000000001` is currently rounded to `0.0001`.

Note that https://github.com/brave/brave-browser/issues/19521 is more about how the amount is presented to the user during transaction confirmation, which may not be the actual thing user is signing (as it stands today).

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.33.99 Chromium: 96.0.4664.55 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11363>brave/brave-core#11363</a></li>
         <li>Verified when 100% asset preset value is selected shows full decimal range</li>
         <li>Verified when conversion value is in decimals shows the equivalent value for sending token as well
</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144611797-c66ef979-6aca-4bcd-86ab-f739e685a89e.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144611557-051ae6cc-6a22-4c43-a529-32342065cd3a.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/144611747-d8c66a84-1dbc-4c96-98e0-85d5c222dc50.mov>
      </td>
   </tr>
</table>
