### ISSUE TITLE
Prevent screenshots on sensitive screens

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#19864]
All screens with private keys, recovery phrase and password enter should prevent screenshots

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.100 x64 build
- Verified taking screenshot is disabled on Login/Wallet Seed Recovery/Private Key screen
-----------
Verification passed on Samsung Tab A with Android 10 running 1.33.100 x64 build
- Verified taking screenshot is disabled on Login/Wallet Seed Recovery/Private Key screen
