### ISSUE TITLE
Use different text in pre-filled tweet message when Tipping unverified creators

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19861]
## Description

When tipping unverified creators and the tip goes into a pending state, we should use different text in the prefilled tweet, as suggested by @jonathansampson. 

>Alternatively, or perhaps in addition, an alternative message for unverified recipients would be helpful. Instead of "I just tipped <domain>…", we could say something like "I'm ready to support &lt;domain&gt; with Brave! If &lt;domain&gt; verifies (creators.brave.com) before <now + 90 days>, they'll receive my scheduled tip." (This wording would need some work).

cc: @rmcfadden3 for text suggestions.

## Solution

Approved by Ryan McFadden:

>“Love that #Brave lets me support creators! Just tipped <creator_name> with #BAT. If they verify at creators.brave.com before <now + 90 days>, the BAT is theirs!”

Example of prefilled tweet: https://twitter.com/norgpharnotl/status/1466076457839435779

**Comment by rmcfadden3** [comment]
@Miyayes — This might be too long, but what about something like the following?

"Love that #Brave lets me support creators & publishers without creepy ads. Just tipped <creator_name> with #BAT. If they verify at creators.brave.com before <now + 90 days>, the BAT is theirs!"

**Comment by Miyayes** [comment]
Text approved by Ryan McFadden:

>“Love that #Brave lets me support creators! Just tipped <creator_name> with #BAT. If they verify at creators.brave.com before <now + 90 days>, the BAT is theirs!”

**Comment by mkarolin** [comment]
QA steps:
1. Open Brave
2. Sign into your Twitter account
3. Navigate to a verified twitter creator page
4. Click the rewards icon, then click the `Send Tip` button
5. Select the tip amount and click the `Send Tip` button
6. Click the `Tweet about your support button` button

**Expected result:**
A new tab opens with your Twitter account and a new tweet with the text:
<pre>
I just tipped @&lt;creator_name&gt; using the Brave Browser. Check it out at https://brave.com/tips.
</pre>

8. Repeat steps 3-6, but with an unverified twitter creator page

**Expected result:**
A new tab opens with your Twitter account and a new tweet with the text:
<pre>
Love that #Brave lets me support creators! Just tipped @&lt;creator_name&gt; with #BAT. If they verify at https://creators.brave.com before &lt;now + 90 days&gt;, the BAT is theirs!
</pre>

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.41.39 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
- Verified the test plan from https://github.com/brave/brave-browser/issues/19861#issuecomment-1145339253

<details>
<summary>1. Send a tip via BR panel</summary>

**Verified publishers**

Example | Example
-- | --

**Unverified publishers**

</details>

<details>
<summary>2. Send a tip via inline tip button</summary>

**Verified publishers**

**Unverified publishers**

</details>

**Comment by GeetaSarvadnya** [comment]
@mkarolin Need a small clarification on the tweet text message for unverified pubs, when we tip unverified pubs the BAT amount should be shown in the tweet text message, in place of #BAT?

```
Love that #Brave lets me support creators! Just tipped @<creator_name> with #BAT. If they verify at https://creators.brave.com before <now + 90 days>, the BAT is theirs!
```

**Comment by mkarolin** [comment]
@GeetaSarvadnya I don’t believe so. ‘#BAT’ here is just a hashtag.
