### ISSUE TITLE
Change Gemini promo card text on Rewards settings page (Dec 2021)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19865]
## Description

New text should just say: 

>Gemini lets you easily trade, store, and earn interest on your BAT. Verify and link your Brave Rewards wallet with Gemini now!

**Please restrict the appearance of the promo card to the following geos:** United States, Singapore, Hong Kong

**Comment by emerick** [comment]
We should remove disclaimer at bottom of card as well, per @Miyayes.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.79 Chromium: 97.0.4692.71 (Official Build) beta (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. changed OS (region) and language to each of the following
2. new profile
3. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
4. loaded `brave://rewards`
5. looked for the existence or absence of the Gemini promo card

Confirmed the Gemini promo card appeared with the updated text, in:

United States | Singapore | Hong Kong
--------------|------------|-----------
<img width="1312" alt="Screen Shot 2022-01-11 at 12 18 26 PM" src="https://user-images.githubusercontent.com/387249/149015899-fdb93eab-960b-4acd-a62a-124af1110551.png"> | <img width="1312" alt="Screenshot 2022-01-11 at 12 16 21 PM" src="https://user-images.githubusercontent.com/387249/149015941-1cee0602-6142-47eb-bbad-91ff9965247d.png"> | <img width="1312" alt="螢幕截圖 2022-01-11 下午12 08 46" src="https://user-images.githubusercontent.com/387249/149015979-f44de744-487c-4599-a114-f8c9df32bc1f.png">

Confirmed there's NO Gemini promo card in the following locales:

France | Spain | Greece
-------|-------|--------
<img width="1312" alt="Capture d’écran 2022-01-11 à 11 51 08" src="https://user-images.githubusercontent.com/387249/149015765-5f3ef7e5-f0eb-46af-baec-2304e60728b4.png"> | <img width="1312" alt="Captura de pantalla 2022-01-11 a las 12 03 51" src="https://user-images.githubusercontent.com/387249/149015797-c8d3b6a2-24ed-4b5a-bf91-cb8b8885d116.png"> | <img width="1312" alt="Στιγμιότυπο 2022-01-11, 11 55 25 πμ" src="https://user-images.githubusercontent.com/387249/149015817-81e83f0f-c6d9-4a73-8a24-ebb4c9f5b5e3.png">
