### ISSUE TITLE
Specify fee percentage in the swap UI

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#19868]
We currently do not explicitly display the swap fees collected by Brave. This must be visible while presenting the quote to the user. Here's what it looks like in the legacy wallet:

<img width="360" alt="Screenshot 2021-12-02 at 7 49 40 AM" src="https://user-images.githubusercontent.com/3684187/144352503-fedcb3b4-2d02-4a11-aaf9-6602ec6f9ece.png">

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.114 Chromium: 96.0.4664.55 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22504.1010)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified swap fee is shown on both Swap widget and on Panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Swap Widget
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/144782681-56318a2a-7112-4cf6-8da2-5fbb5f765d4b.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/144782530-78754deb-e863-44af-b20d-e76188a770db.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/144782121-afd07eb7-6aa8-4a59-9820-7b42aa7ec40b.png>
      </td>
   </tr>
   <tr>
      <td>Swap panel
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/144782711-36532aa4-8729-4a98-a642-77db1cd732fb.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/144782637-b20e8b73-81e2-42d4-baa2-d4490dfe317a.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/144782156-95d865f4-847c-469b-83d7-1c74345025f5.png>
      </td>
   </tr>
</table>
