### ISSUE TITLE
Use Common Password Validation on Desktop

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19875]
There is a new method in `KeyringController` with a name `IsStrongPassword`. We should call it for a password validation to be consistent with other platforms.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.98 Chromium: 98.0.4758.72 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11456>brave/brave-core#11456</a></li>
         <li>Verified password field checks for the min criteria to be satisfied</li>
         <li>Verified password field throws error when min criteria is not met</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Length not satisfied
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/151960053-b27bd34e-528a-4b4e-b6f2-32d56835965a.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151959751-cdc2fefa-bad6-416a-82e9-487f5fe56a74.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/151959326-704ec7e3-23e8-405e-90b0-25c8a26bfeb6.png>
      </td>
   </tr>
   <tr>
      <td>Special char/number not satisfied but min length satisfied
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/151960072-1f5a892c-ba0e-4022-9e9a-9a6b7907bc42.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151959803-d1a1868b-5ba9-4c05-9cf9-207fc910f7a8.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/151959469-3176019f-385f-40ab-abcd-2f3ef3d88fdc.png>
      </td>
   </tr>
   <tr>
      <td>Password criteria satisfied
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/151960098-f7db9408-737c-4e58-9646-625dd4ce8128.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151959846-53f08731-78a7-4e38-9b29-9a718f832224.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/151959650-0702e159-2441-4a85-9245-40812b638d44.png>
      </td>
   </tr>
</table>
