### ISSUE TITLE
Getting Leave site popups from browser.

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#19870]
From Yesterday 1-Dec-2021 I am getting leave site popups from the sites that I didn't saved any information with.

![200](https://user-images.githubusercontent.com/89839714/144389518-5cbbc19d-29e3-4bc1-b135-7c2def442d9b.png)

**Comment by ryanbr** [comment]
Is there a specific page causing it? Test in private window mode, with no extensions. @clicky6

**Comment by clicky6** [comment]
@ryanbr 
Most pages are showing it in simple mode but with private mode it's not appearing.
Then definitely there should be some issue with some extension, right and not with Brave Browser.
How to find which extension is causing this?

**Comment by ryanbr** [comment]
Just disable each extension, until you can replicate it. @clicky6

**Comment by clicky6** [comment]
@ryanbr 
OK, Thank You.
