### ISSUE TITLE
Brave browser beta: Developer tool black theme is not working

### ISSUE THREAD

**Issue by rohitsharmahub** [brave/brave-browser#19871]
## Description 

I am unable to use the dark theme under the developer tool section. 
Version: 1.33.94

## Steps to Reproduce

   1.  Go to a developer tool
   2.  Change the theme to dark
   3.  Reload the developer tool and you will see the light theme

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by thenoseman** [comment]
Also happens in stable (`Version 1.32.115 Chromium: 96.0.4664.93 (x86_64)`)

**Comment by cyress** [comment]
Yes, it seems that some DevTools settings are no longer saved since a brave release a month ago.
Related ticket: #19530

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/brave-core/pull/12600 - duplicate of https://github.com/brave/brave-browser/issues/20491
