### ISSUE TITLE
Add notifications for successful / failed transactions

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19885]
Currently when a transaction fails or succeeds, the user needs to go find the transaction.
We should have a notification and if you click it, it should go to the transaction list with that item in view.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13330>brave/brave-core#13330</a></li>
         <li>Verified a transaction notification is shown for both successful and error'd transaction</li>
         <li>Verified a transaction notification is only shown when system notification is enabled</li>
         <li>Verified a transaction notification is not shown if Focus assist is enabled on Windows</li>
         <li>Verified a transaction notification is not shown if the system is set to DnD</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/176890573-9be682da-ace2-4eec-a54e-9b40cb5cc985.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176887551-3e788245-9985-4978-942f-c8b1c5556456.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176889284-e8d26260-f275-4e11-8c14-e60c64ace4cc.mov>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Removing Android label as Android specific issue is logged https://github.com/brave/brave-browser/issues/23879
