### ISSUE TITLE
No option to disable updates

### ISSUE THREAD

**Issue by jazzybeat** [brave/brave-browser#19889]
Why there is no option in settings to disable software updates? As a user, I don't need the latest security updates, bug fixes, or features.
<img width="732" alt="Screen Shot 2021-12-03 at 09 00 14" src="https://user-images.githubusercontent.com/815706/144567619-d2e52a14-d271-4b44-aea1-382ac0083efc.png">

**Comment by srirambv** [comment]
Dupe of #5576
