### ISSUE TITLE
Wallet HD path is wrong for legacy

### ISSUE THREAD

**Issue by scmart** [brave/brave-browser#19883]
When connecting to a Ledger S hardware wallet, and using "Legacy (MEW/MyCrypto)", only the first address is correct.

## Steps to Reproduce

   1.  Connect Ledger Nano S
   2.  Add Account
   3.  Select Legacy (MEW/MyCrypto)

## Actual result:
  Addresses 2-5 (and probably beyond) are the wrong addresses.

## Expected result:
  Addresses 2-5 should match what MEW, MyCrypto, and metamask with the legacy option list.

## Reproduces how often: 
  Always

## Brave version (brave://version info)
  Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
  Ubuntu 20.04

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?   Unknown
- Can you reproduce this issue with the nightly channel?   Unknown

## Miscellaneous Information:
  A minor note, the UI experience switching between Ledger Live and Legacy is bad.  It reverts to the connect to HW wallet view, where I though I had to reclick connect, so I did, followed by an error, before it then snaps back to the address list.

**Comment by srirambv** [comment]
cc: @onyb @darkdh

**Comment by scmart** [comment]
@srirambv  Seems like this should be an easy and important fix.  Hard to use the Brave wallet when most of my addresses aren't discoverable.

**Comment by scmart** [comment]
Still broken in Version 1.35.101


@spylogsster @srirambv  @onyb @darkdh

**Comment by spylogsster** [comment]
will take a look tomorrow, thanks @scmart for the reminder

**Comment by bbondy** [comment]
Shouldn't we permanently have a third option now to have the other derivation path in case someone used those addresses and wants to get access again via a new import?

**Comment by spylogsster** [comment]
> Shouldn't we permanently have a third option now to have the other derivation path in case someone used those addresses and wants to get access again via a new import?

follow-up issue https://github.com/brave/brave-browser/issues/21171

**Comment by kjozwiak** [comment]
This was originally uplifted/scheduled to go into a `1.35.x` HF but never ended up being released. It will go out via `1.36.x` as we won't be having another `1.35.x` release at this point.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.106 Chromium: 99.0.4844.45 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/12314>brave/brave-core#12314</a></li>
         <li>Verified import accounts with Legacy derivation path from MM and Brave Wallet works </li>
         <li>Verified imported accounts on both legacy and live are both same on MM and Brave Wallet</li>
        </ul>
      </td>
   </tr>
</table>
