### ISSUE TITLE
Submitting a transaction doesn't go back to portfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19891]
## Description 
Submitting a transaction doesn't go back to portfolio

## Steps to reproduce 

   1. Initiate a transaction
   2. Approve the transaction via the approval popup
   3. Remains on the send screen with input data as is

## Actual result 

https://user-images.githubusercontent.com/17010094/144598930-b8bf9716-c2a0-4b8a-a2b8-ab68f7599bf2.mp4

## Expected result
Navigate back to portfolio or token page so transaction is shown

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.33.98

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @jamesmudgett @SergeyZhukovsky @wchen342 @bbondy

**Comment by bbondy** [comment]
I think a user might not realize it's actually submitted in this case and might accidentally try to submit again

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.103 x64 build
- Verified submitting a send/swap transaction navigates back to the portfolio page
---------
Verification passed on Samsung Tab A with Android 10 running 1.33.103 x64 build
- Verified submitting a send/swap transaction navigates back to the portfolio page
