### ISSUE TITLE
String typos for Android Wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19895]
- I don't believe you can actually pay with Apple Pay on Android (I tried and it says not available). So that text should be adjusted.
- We use Wyre and not Wire for buying crypto to the wallet.
- Nit on grammar for never disclosing the key.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.100 x64 build
- Verified text updates are shown correctly 
- Verified there is no mention of `Apple Pay` on buy button
- Verified buy button now reads `Continue to Wyre`

![image](https://user-images.githubusercontent.com/17010094/144978531-aeefdcef-ad7d-4f50-baea-16c7daa9ffa1.png) | ![image](https://user-images.githubusercontent.com/17010094/144978542-4d3c17c2-7982-4edb-816c-b0338ad23420.png)
-- | --

--------
Verification passed on Samsung Tab A with Android 10 running 1.33.100 x64 build
- Verified text updates are shown correctly 
- Verified there is no mention of `Apple Pay` on buy button
- Verified buy button now reads `Continue to Wyre`

![image](https://user-images.githubusercontent.com/17010094/144978560-5c11a7cd-bf5d-486c-a4c4-c03214acd472.png) | ![image](https://user-images.githubusercontent.com/17010094/144978570-2df4c50d-ca46-4914-8b98-967a9d7d1847.png)
-- | --
