### ISSUE TITLE
Update or remove chrome's noscript UI

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#199]
A follow up issue of brave/brave-core/pull/97
<img width="324" alt="screen shot 2018-05-14 at 10 30 23 pm" src="https://user-images.githubusercontent.com/4730197/40038332-6f2162dc-57c6-11e8-967f-5f7dd001fc35.png">
In the short term, we should update the strings shown in chrome's noscript UI to redirect users to our shield panel.
And we should customize this UI to achieve the similar functionality we have in shields in the long run.

## Update (11/16)

We should remove the Chromium noscript UI entirely since it doesn't have much benefit and causes some issues (#12648, #12681).  

### QA Test Plan

1. Go to https://terrillthompson.com/tests/noscript.html
2. Disable scripts in shields. The page should say "This paragraph is contained within the noscript element."
3. You should NOT see the chromium noscript icon in the url bar.
4. Same result if scripts is disabled globally.

**Comment by bbondy** [comment]
cc @bradleyrichter

**Comment by diracdeltas** [comment]
I think this should have parity with the noscript icon in browser-laptop currently does:

1. list all origins of the scripts with checkboxes
2. have allow once / allow until restart buttons

a highly-requested feature was "allow all" (for certain origins): https://github.com/brave/browser-laptop/issues/9307

**Comment by diracdeltas** [comment]
integrating it into shields sgtm. does the design also account for 'allow once' and 'allow until restart'?

**Comment by diracdeltas** [comment]
IMO (as a noscript user) the 'allow once' and 'allow until restart' settings are pretty useful for me

**Comment by davidtemkin** [comment]
We want a single way of managing "shields" (i.e., resource load blocking, among other things) so let's fit this in that framework.

**Comment by bsclifton** [comment]
cc: @tomlowenthal

**Comment by cezaraugusto** [comment]
ping @tomlowenthal @karenkliu

**Comment by karenkliu** [comment]
@cezaraugusto Please refer to #2996 for the most recent designs related to script blocking.

**Comment by rebron** [comment]
Removing p5 label, let's re-evaluate this one.

**Comment by diracdeltas** [comment]
Per discussion in the above issues, i think we should remove the noscript UI for now since it's the same number of clicks to unblock in shields

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.55 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the STR from the description. 
![image](https://user-images.githubusercontent.com/38657976/101899519-f76a2900-3bd3-11eb-89cc-cb3231a521b8.png)
