### ISSUE TITLE
Move window.ethereum to use gin

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19909]
@bridiver noted we should use gin for `window.ethereum` like we did for muon.

As an example:
NetErrorPageController
anything that includes object_template_builder.h

```

return gin::Wrappable<NetErrorPageController>::GetObjectTemplateBuilder(
             isolate)
      .SetMethod("downloadButtonClick",
                 &NetErrorPageController::DownloadButtonClick)
      .SetMethod("reloadButtonClick",
                 &NetErrorPageController::ReloadButtonClick)
      .SetMethod("detailsButtonClick",
                 &NetErrorPageController::DetailsButtonClick)
      .SetMethod("diagnoseErrorsButtonClick",
                 &NetErrorPageController::DiagnoseErrorsButtonClick)
      .SetMethod("trackEasterEgg", &NetErrorPageController::TrackEasterEgg)
      .SetMethod("updateEasterEggHighScore",
                 &NetErrorPageController::UpdateEasterEggHighScore)
      .SetMethod("resetEasterEggHighScore",
                 &NetErrorPageController::ResetEasterEggHighScore)
      .SetMethod("launchOfflineItem",
                 &NetErrorPageController::LaunchOfflineItem)
      .SetMethod("launchDownloadsPage",
                 &NetErrorPageController::LaunchDownloadsPage)
      .SetMethod("savePageForLater", &NetErrorPageController::SavePageForLater)
      .SetMethod("cancelSavePage", &NetErrorPageController::CancelSavePage)
      .SetMethod("listVisibilityChanged",
                 &NetErrorPageController::ListVisibilityChanged);
```

**Comment by darkdh** [comment]
`gin::Wrappable` will also guarantee non function properties are read only

**Comment by darkdh** [comment]
Task for `window.ethereum.['_metamask', 'chainId', 'networkVersion', 'selectedAddress']` non writable protection will be merged into this issue

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit)
-- | --
Revision | `846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}`
OS | Linux

- Verified steps from [brave/brave-core#15498](https://github.com/brave/brave-core/pull/15498)
- Verified Ethereum Dapp options from https://github.com/bbondy/eth-manual-tests
- Verified able to connect to an Ethereum Dapp
- Verified after connecting to an Ethereum Dapp the connected state is saved in `brave://settings/content/ethereum`
- Verified able to connect multiple accounts to Dapp 
- Verified able to Sign Transactions from an Ethereum account

---------------------

Verification passed on 

Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit)
-- | --
Revision | `846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15498](https://github.com/brave/brave-core/pull/15498)
- Verified Ethereum Dapp options from https://github.com/bbondy/eth-manual-tests
- Verified able to connect to an Ethereum Dapp
- Verified after connecting to an Ethereum Dapp the connected state is saved in `brave://settings/content/ethereum`
- Verified able to connect multiple accounts to Dapp 
- Verified able to Sign Transactions from an Ethereum account

---------------------

Verification passed on 

Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (arm64)
-- | --
Revision | `846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15498](https://github.com/brave/brave-core/pull/15498)
- Verified Ethereum Dapp options from https://github.com/bbondy/eth-manual-tests
- Verified able to connect to an Ethereum Dapp
- Verified after connecting to an Ethereum Dapp the connected state is saved in `brave://settings/content/ethereum`
- Verified able to connect multiple accounts to Dapp 
- Verified able to Sign Transactions from an Ethereum account

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.47.167 x64 build

- Verified steps from [brave/brave-core#15498](https://github.com/brave/brave-core/pull/15498)
- Verified Ethereum Dapp options from https://github.com/bbondy/eth-manual-tests
- Verified able to connect to an Ethereum Dapp
- Verified after connecting to an Ethereum Dapp the connected state is saved in `Settings -> Site Settings -> Ethereum`
- Verified able to connect multiple accounts to Dapp 
- Verified able to Sign Transactions/Messages from an Ethereum account

---------------------

Verification passed on Lenovo Tab with Android 12 running 1.47.167 x64 build

- Verified steps from [brave/brave-core#15498](https://github.com/brave/brave-core/pull/15498)
- Verified Ethereum Dapp options from https://github.com/bbondy/eth-manual-tests
- Verified able to connect to an Ethereum Dapp
- Verified after connecting to an Ethereum Dapp the connected state is saved in `Settings -> Site Settings -> Ethereum`
- Verified able to connect multiple accounts to Dapp 
- Verified able to Sign Transactions/Messages from an Ethereum account
