### ISSUE TITLE
Buttons are wrong color in Rewards flyout panel

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#19907]
## Description 
Buttons are wrong color in Rewards flyout panel

## Steps to reproduce 

   1. install 1.35.3
   2. upgrade to the PR build, which is 1.35.5 with CR97
   3. open `laurenwags.github.io` and tap on the BAT icon
   4. look at the resulting Rewards panel

## Actual result 
![Screenshot_20211203-101718](https://user-images.githubusercontent.com/387249/144652902-7c31edc6-de9f-4d12-8cfe-7672d4cc168b.png)

## Expected result
![Screenshot_20211203-101517](https://user-images.githubusercontent.com/387249/144652924-c5af3ca7-6814-48f7-a089-9fe9107b0a81.png)

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): Google Pixel XL (phone)
   - Android version: 9.0
   
## Brave version
Brave - Nightly 1.35.5, Chromium 97.0.4692.36`

cc @samartnik @mkarolin @kjozwiak @srirambv

**Comment by samartnik** [comment]
Fixed directly in `cr97` branch https://github.com/brave/brave-core/commit/92f4e2b68df3df38f73b6fd3555a0396a12957a9

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.34.67, Chromium 97.0.4692.56` with the original inline testplan.

Confirmed button colors have returned to normal.

![Screenshot_20211220-111716](https://user-images.githubusercontent.com/387249/146821202-f82b6f6b-8a38-400a-b9b1-13314c6638f3.png)
