### ISSUE TITLE
Wallet crash when after resetting wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19905]
## Description 
Wallet crash when after resetting wallet

## Steps to reproduce 

1. Create wallet
2. Lock device
3. Unlock device
4. Open Settings -> Wallet -> Reset wallet
5. Open Wallet from menu, showed unlock screen and crashed
6. Open again showed onboarding screen

## Actual result 
Wallet crash when after resetting wallet

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.33.98

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? Yes

### Additional information

https://share.backtrace.io/api/share/CThx1RcRuVKLpFne6SQphd0

**Comment by SergeyZhukovsky** [comment]
@srirambv let me know if you see it still, that crash has been fixed yesterday

**Comment by srirambv** [comment]
@SergeyZhukovsky  repro'd the crash on nightly again. Steps are mostly same but after rest when I launch wallet again, it doesn't crash but tapping on the restore button crashed. Here's the link for crash report https://share.backtrace.io/api/share/iIaf63Tok9iIqx1ztmRVnM0

**Comment by srirambv** [comment]
There seems to be random crashes and not just after reset. I had a crash on a clean build and after enabling flags selecting wallet crashed it. Here's the link to the crash report https://share.backtrace.io/api/share/x1Kb6iePP5XNUypox3Rihdb2

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.103 x64 build
- Verified steps from issue description
- Verified no browser crash at random or when resetting wallet
-----------
Verification passed on Samsung Tab A with Android 10 running 1.33.103 x64 build
- Verified steps from issue description
- Verified no browser crash at random or when resetting wallet
