### ISSUE TITLE
Passing valid --target_os and --target_arch to tests causes failure

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#19906]
In [my PR](https://github.com/brave/devops/pull/6405), I'm switching to always passing `--target_os` and `--target_arch` when running unit/browser tests in CI. Apparently this can cause trouble. In a Linux x64 ASAN build, this is the difference between a successful:
```
ninja: Entering directory `/home/ubuntu/workspace/brave-browser-build-linux-x64-asan-nightly/src/out/Release' 
```
and an unsuccessful:
```
ninja: Entering directory `/home/ubuntu/workspace/brave-browser-build-linux-x64-asan-wknapik-nightly/src/out/linux_Release'
ninja: fatal: chdir to '/home/ubuntu/workspace/brave-browser-build-linux-x64-asan-wknapik-nightly/src/out/linux_Release' - No such file or directory
```
Seems like a bug.

**Comment by wknapik** [comment]
Log for the failure: https://ci.brave.com/job/brave-browser-build-linux-x64-asan-wknapik/4/execution/node/111/log/
Log for the success: https://ci.brave.com/view/asan/job/brave-browser-build-linux-x64-asan/170/execution/node/96/log/?consoleFull

**Comment by mihaiplesa** [comment]
Change should be in https://github.com/brave/brave-core/blob/master/build/commands/lib/config.js#L919

**Comment by wknapik** [comment]
Same issue for
* Windows x64: https://ci.brave.com/job/test-brave-browser-build-windows-x64-wknapik/3/execution/node/179/log/
* Windows x86: https://ci.brave.com/job/test-brave-browser-build-windows-x86-wknapik/3/execution/node/179/log/
