### ISSUE TITLE
Wallet unlock sometimes doesn't load the correct screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19916]
## Description 

Wallet unlock sometimes doesn't load the correct screen

## Steps to Reproduce

Scenario 1:
   1. New profile
   2. Click on restore
   3. Enter seed words to restore wallet
   4. Doesn't show portfolio, URL remains on `brave://wallet/crypto/restore-wallet`

Scenario 2:
   1. New profile
   2. Create wallet
   3. Open Accounts page and lock wallet
   4. Unlock wallet doesn't show account page rather its just empty (similar to screenshot from scenario 1)

## Actual result:

<img width="1840" alt="Screen Shot 2021-12-04 at 4 40 33 AM" src="https://user-images.githubusercontent.com/17010094/144707523-871219ad-a480-4e03-be3c-f39c015d3ff8.png">

## Expected result:
Should load the page correctly when unlocked 

## Reproduces how often: 

Intermittent

## Brave version (brave://version info)

Brave | 1.35.7 Chromium: 96.0.4664.55 (Official Build) nightly (arm64)
-- | --
Revision | `38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}`
OS | macOS Version 12.0.1 (Build 21A559)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Maybe
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy @Douglashdaniel 
Maybe related to #19820

**Comment by josheleonard** [comment]
Could not replicate on 1.38.42

![Screen Shot 2022-03-14 at 5 14 43 PM](https://user-images.githubusercontent.com/30185185/158275902-b1c44c60-3bbb-4978-a68b-be00834ab5ee.png)


Scenario 1:

https://user-images.githubusercontent.com/30185185/158275794-aa67cfca-0b78-4a17-92d8-0b46c7ba9b0d.mov

Scenario 2:
 
https://user-images.githubusercontent.com/30185185/158275845-de11b624-5fa1-4a9b-9897-83d8f189c533.mov

**Comment by Douglashdaniel** [comment]
Is no longer reproducible, closing as invalid.
