### ISSUE TITLE
scripts not being blocked

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1991]
## Description 
Scripts are not being blocked

## Steps to Reproduce

   1. Launch 0.56.8 (I was using a clean profile)
   2. Visit buzzfeed.com
   3. Toggle shields off. Let ads load.
   4. Toggle shields on.
   5. Open a new tab, navigate to brianbondy.com.
   6. Enable Block Scripts.

## Actual result:
Page loads, no scripts are blocked.
![screen shot 2018-11-05 at 10 08 20 am](https://user-images.githubusercontent.com/28145373/48005981-c957b800-e0e2-11e8-8f24-13f7cf74e4e4.png)

## Expected result:
Page should not load, scripts should be blocked.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Reproduced on Linux by @srirambv

**Comment by srirambv** [comment]
Reproduced on linux with 0.56.8.

**Comment by kjozwiak** [comment]
Possibly related to https://github.com/brave/brave-browser/issues/1829

**Comment by LaurenWags** [comment]
Removed `intermittent-issue` label, reproducible steps found.

**Comment by srirambv** [comment]
Issue reproduced on `0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)` as well so not a regression

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.56.9 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows
