### ISSUE TITLE
Reduce minimum BAT requirement for Uphold verification to 2 BAT (Dec 2021)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19911]
## Description

Reduce minimum BAT requirement to 2 BAT.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)
```

Confirmed text is updated to reflect that minimum of 2 BAT is required for Uphold.
Confirmed when balance is < 2 BAT, the message is displayed when selecting Uphold as the provider.

0 BAT | 1 BAT | 1.75 BAT
----- | ----- | -----
<img width="1190" alt="1" src="https://user-images.githubusercontent.com/28145373/149153961-f405a34e-456f-4ab6-91eb-1e827d9c372b.png"> | <img width="1193" alt="3" src="https://user-images.githubusercontent.com/28145373/149153975-5a41fda1-9513-4692-9455-f6787e187672.png"> | <img width="1189" alt="2" src="https://user-images.githubusercontent.com/28145373/149153988-cbbc49a7-ff19-4f1c-acb3-4c6347f5e1aa.png">

Confirmed when balance is >= 2 BAT and Uphold is selected as the provider, no message is displayed and you are directed to the Uphold site.

<img width="1194" alt="4" src="https://user-images.githubusercontent.com/28145373/149154132-1a9d20cc-c8a8-47c2-a7b7-16f055934f14.png">

--------------
