### ISSUE TITLE
Current network should be able to be modified, just not removed

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19917]
If a user for example puts the wrong number of decimals for the current network. 
They should be able to go to chrome://settings/wallet
We currently don't allow a user to edit the current network at all.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.89 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11438>brave/brave-core#11438</a></li>
         <li>Verified remove button is hidden when a custom network is set as default</li>
         <li>Verified able to double click and open edit network settings</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/20653>#20653</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/150804111-eb423aa6-d054-4318-86c1-a43271382b09.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/150803550-1f4de67e-b463-4c27-825a-42803dce4fb9.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/150802689-70be9387-851d-499d-88bb-f347d73111ff.mov>
      </td>
   </tr>
</table>
