### ISSUE TITLE
[Android] Reduce minimum BAT requirement for Uphold verification to 2 BAT (Dec 2021)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19912]
## Description

https://github.com/brave/brave-browser/issues/19911

**Comment by zenparsing** [comment]
This will need to be implemented after #18439

**Comment by LaurenWags** [comment]
Verified passed with `1.35.77 Chromium 97.0.4692.71` on Pixel 3 XL with Android 12.

Confirmed 2 BAT minimum balance required message is shown when balance is 0 and 1 BAT.
Confirmed when balance is 2 BAT (requested @Miyayes to send 2 ad grants each for 1 BAT to my wallet), there was minimum balance required message.
Did a second install and confirmed after claiming UGP grant, there was no minimum balance message.

![Screenshot_20220110-112102](https://user-images.githubusercontent.com/28145373/148803461-8cf84839-83a5-41d8-9b64-077a85d0b36f.png)
