### ISSUE TITLE
F/U issue for microsoft-edge protocol handler implementation

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19922]
1. Update patch file `BRAVE_DEFAULT_BROWSER_WORKER_H` should be in public section (don't need QA)
2. Move `ms_edge_protocol_message_handler.cc` to `browser/ui/webui/settings` (don't need QA)
3. Notify default protocol change to system - W/o notifying, control panel is not refreshed whe when it's already opened (**Need QA**)

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.72 Chromium: 97.0.4692.56 (Official Build) beta (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Used the testplan from https://github.com/brave/brave-core/pull/11445.

Steps:
1. new profile
2. launched the Control Panel for default apps on Windows 10
3. confirmed Microsoft Edge was the default handler for the `ms-edge` protocol
4. launched Brave
5. confirmed Brave was *not* the default handler for the `ms-edge` protocol
6. clicked on the `Make default` button while the Control Panel was open
7. confirmed Brave dynamically became the `MICROSOFT-EDGE` protocol handler in the above


example | example
----------|----------
![19922-1](https://user-images.githubusercontent.com/387249/148288193-0edb3067-1ba2-48c4-a2e4-fbc5e0ce1ffb.png) | ![19922-2](https://user-images.githubusercontent.com/387249/148288196-0282d202-7932-49ec-adbf-3ae53f1d4314.png)
