### ISSUE TITLE
Give us back the top menu bar that Chrome Developers stole from us

### ISSUE THREAD

**Issue by Tectract** [brave/brave-browser#19920]
We want the old "File Edit View History Bookmarks Tools Help" menu bar back. The three lines pancake thing is bad user interface design because it requires more mouse movements and clicks to use. Removing the menu bar was a way for Chrome devs to flaunt that Chrome was a "mac style" program because it specifically breaks linux convention of having a menu bar at the top of each window. Linux users expect the menu for each window, and Chrome developers spit in our faces by going out of their way to remove even the option to have the top menu bar.

Please give us the menu bar back. We are begging the Brave team to fix some of these very controversial BUGS that the Chrome team implemented in Chrome, against the will of the users.

**Comment by rebron** [comment]
Closing as feedback/malformed issue. @Tectract We invite you to go to community.brave.com for feedback of this type. For future issues, if you can look at the latest release notes to see how some of the actionable github issues were written it will show how we address issues here.

**Comment by Tectract** [comment]
So you guys don't track issues through the github issues system? Is that correct?
