### ISSUE TITLE
Disable WebRTC log uploading

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#1993]
Chromium maintains a private API for whitelisted components and extensions that aggregates debugging information about WebRTC sessions and uploads it to a Google server. (An example of a whitelisted extension mentioned in the source code is Google Hangouts. I do not have direct access to the entire whitelist.)

We should disable this subsystem and write tests to ensure that logs are never uploaded.

**Comment by aldosandi604-beep** [comment]
Google Chrome: Versi 93.0.4577.107 (Build Resmi)  (64 bit)
Platform: 14092.77.0 (Official Build) stable-channel candy
Saluran: stable-channel
Versi Firmware: Google_Candy.5216.310.186
ARC Aktif: false
ARC: 
Terdaftar sebagai Perusahaan: false
Mode Developer: false
