### ISSUE TITLE
Allow to make the network active in wallet networks settings

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#19930]
Add new item "Set as Active" to network menu:

![image](https://user-images.githubusercontent.com/2965009/144866425-a06969c7-6aae-4501-aed5-b3d2632abcf9.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.93 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11464>brave/brave-core#11464</a></li>
         <li>Verified setting a network as active from <code>brave://settings/wallet/networks</code> updates the current network</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/151553964-87557ea4-620f-4ecf-9797-d7c5c8a58e73.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151552204-f342cac9-ebb4-46f1-bdb3-379da2bbb9bb.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151552128-4b9bce74-a820-446d-bafd-f3bfb75c6e6e.mov>
      </td>
   </tr>
</table>
