### ISSUE TITLE
Wallet errors on console. Broken verify wallet page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19933]
## Description 

Wallet errors on console. Broken verify wallet page

## Steps to Reproduce

   1. New profile on nightly
   2. Open console, shows errors
   3. Create wallet and verify wallet seed, broken onboarding  page with errors
   4. Click on wallet again, loads portfolio correctly

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/144843894-746c1cc2-9d2f-4952-a1e7-91647af14854.png)

## Expected result:
No such onboarding page failure

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.35.7 Chromium: 96.0.4664.55 (Official Build) nightly (64-bit)
-- | --
Revision | `38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}`
OS | Windows 11 Version Dev (Build 22509.1011)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Maybe 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @bbondy

**Comment by darkdh** [comment]
this is fixed with https://github.com/brave/brave-core/pull/11437/commits/3d439b2bea5d2ab763bcbeda9d9ce4c4c26983ec

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified no console errors when creating a wallet</li>
         <li>Verified no UI issues when creating wallet and onboarding</li>
        </ul>
      </td>
   </tr>
</table>
