### ISSUE TITLE
Trying to drag and move a link, image or tab on Ubuntu Linux will move the object to a Brave window in a completely different workspace

### ISSUE THREAD

**Issue by rdgh8** [brave/brave-browser#19934]
## Description 

Trying to drag and move a link, image or tab on Ubuntu Linux will move the object to a Brave window in a completely different workspace. It's difficult to explain with words, please see the video below. 

## Steps to Reproduce

   1. Open two Brave windows, one on workspace 1 (W1) and one on workspace 2 (W2).
   2. Open another tab on Brave window in W1.
   3. Try to pick up the tab in W1

## Actual result:

Tab is moved moved to W2

## Expected result:

You pick up the tab and it remains in W1 unless you manually move it elsewhere. 

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Brave | 1.34.50 Chromium: 96.0.4664.45 (Official Build) beta (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel?

Have only tried in Beta 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

I have found that this can be reproduced with any two chromium-based programs (ex. Brave in one workspace and VS Code in another).

## Miscellaneous Information:

See the demo below with both links and tabs in a Pop!_OS virtual machine:

https://user-images.githubusercontent.com/66289396/144853492-8bd94001-e93b-4820-a277-0b148247a3eb.mp4

**Comment by tony-oldport** [comment]
I have the same issue with Brave Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit)

Running on Pop!_OS v21.04 64-bit, GNOME Version 3.38.5, Windowing System X11

I am not able to reproduce it with the latest version of Chromium (Version 96.0.4664.110 (Official Build) (64-bit))

**Comment by rdgh8** [comment]
Fixed on latest Brave Beta
