### ISSUE TITLE
Remove dot from time scale selector Brave Wallet portfolio

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#19947]
![Screenshot_20211201-105123](https://user-images.githubusercontent.com/318119/144919037-10a60521-d577-4a73-8f3b-82836e14aabf.png)

The dot in the selected time scale is not necessary, please remove from all active time scale buttons.

**Comment by srirambv** [comment]
Verification passed on Oppe Reno 5 with Android 11 running 1.33.103 x64 build
- Verified the dot is removed for the selected time on the portfolio screen
- Verified the dot is removed for the selected time on the asset details screen
-----------
Verification passed on Samsung Tab A with Android 10 running  1.33.103 x64 build
- Verified the dot is removed for the selected time on the portfolio screen
- Verified the dot is removed for the selected time on the asset details screen
