### ISSUE TITLE
Wallet UI cleanup portfolio

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#19948]
Overlapping line on time. Needs some space below the time label to the line. May also look better to stop the line at 0y axis.
![Screenshot_20211201-105123](https://user-images.githubusercontent.com/318119/144921051-8003e0e0-9087-4ae1-9993-69021b8dd214.png)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.104
- Verified timestamp doesn't overlap on the time line selector 

Portfolio | Token Graph
-- | --
![image](https://user-images.githubusercontent.com/17010094/145569185-e6294600-f18a-4510-8ff1-69b53f368a66.png) | ![image](https://user-images.githubusercontent.com/17010094/145569223-15297781-2dc7-4c07-87f3-64e5c3e46b95.png)


------
Verification passed on Samsung Tab A  with Android 10 running 1.33.104
- Verified timestamp doesn't overlap on the time line selector 

Portfolio | Token Graph
-- | --
![image](https://user-images.githubusercontent.com/17010094/145569239-3d503604-e2e5-4b9c-9831-83e4408e2f81.png) | ![image](https://user-images.githubusercontent.com/17010094/145569256-05af2d98-5d3f-4be0-9fff-9d8843372347.png)
