### ISSUE TITLE
Settings issues for Brave News

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#19941]
## Description 
Some fixes needed in Settings, one of which causes a crash.
1. After turning off Brave News it should go away when I return to NTP. The cards should no longer be present on NTP.
2. After turning off Brave News and opening a new tab, if I go back to the tab with Brave News then the browser crashes.
3. After turning off Brave News the sources list goes away. That's good. But if I return to Brave News in Settings then the list is back, including my previous selections. This is confusing.

**Comment by mattmcalister** [comment]
@alexsafe on desktop it just disappears. thinking from the user's perspective, I've made my choice with the toggle, so just clear it away for me then.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.85 x64 Beta Build
- Verified steps from issue description
- Verified closing news setting doesn't enable them back when news setting is loaded
- Verified going back to the same tab where news was disabled doesn't crash the browser
- Verified disabling and going back to NTP doesn't show the news feed on the original tab where it was enabled
---------
Verification passed on Samsung Tab A with Android 10 running 1.35.85 x64 Beta Build
- Verified steps from issue description
- Verified closing news setting doesn't enable them back when news setting is loaded
- Verified going back to the same tab where news was disabled doesn't crash the browser
- Verified disabling and going back to NTP doesn't show the news feed on the original tab where it was enabled
