### ISSUE TITLE
Onboarding issues from the panel

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19957]
Couple of UX problems:

1) When opening the panel and clicking Restore, it takes you to the restore screen but the Back button doesn't work. In this case we should hide the back button.

2) When clicking on Getting started, it takes you to the exact same thing on the full page. We should instead go to the 2nd page in that case so the user doesn't need to click Getting Started twice.  This should also not have a back button in that case when coming from the panel.

<img width="1010" alt="Screen Shot 2021-12-06 at 7 14 19 PM" src="https://user-images.githubusercontent.com/831718/144942880-1e781b0b-742d-4968-92b9-98aa59ac851d.png">

**Comment by jamesmudgett** [comment]
This one needs more UX to avoid jumping over MetaMask and crypto wallets detection specific UI. We should either support all logic from first onboarding screen within the panel or change the panel design to be less similar to the first screen of onboarding.

**Comment by bbondy** [comment]
Good catch, I think we should probably support the same flows in the panel in that case.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.3 (Build 21E230)
```

Reproduced both the duplicate onboarding as well as "Back" button not working on brave://wallet/crypto/restore-wallet page using 1.36.119.
