### ISSUE TITLE
Fix broken images for Custom Networks Base Currency

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19953]
## Description 
Fix broken icons for Custom Networks Base Currency

1) Got to brave://settings/wallet
2) Add a new custom network, add a `url` for `Icon URLs`
3) Go to brave://wallet and switch to the new network
4) The icon will be broken for the networks base currency.

We currently do not have a way to support `icon url's` in front end UI but it should at-least default to the `placeholder` icon

![image](https://user-images.githubusercontent.com/40611140/144941237-d99dbac5-e7cb-4839-bed4-445a30943349.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.89 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified images for custom network's base currency doesn't show a broken icon instead shows the first letter of the token name</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150783210-fea9ec0d-fba7-4018-a1bc-59398bb3b2bd.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/150782115-c2d53576-46f6-402d-b437-6dc53710f9bd.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/150781910-67d1c0d5-2888-48e0-9c10-ab372db2cec3.png>
      </td>
   </tr>
</table>
