### ISSUE TITLE
Implement Add Ethereum Site Permissions in UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#19954]
## Description 
Implement new Add Ethereum Site Permissions to Wallet UI

There is a new method called `AddEthereumPermission` in `braveWalletService` to allow adding permission to a `dapp` in the `Site Permissions` panel for other accounts.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.97 Chromium: 98.0.4758.72 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d63e30f73734c5326037b0d94eceed77168d95e1-refs/branch-heads/4758@{#905}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11486>brave/brave-core#11486</a></li>
         <li>Verified UI to matches the new design </li>
         <li>Verified there is a <code>New account</code> button to redirect to the <code>Add Account modal</code></li>
         <li>Verified able to <code>Connect</code> to a site origin from the <code>Permissions</code> panel.</li>
         <li>Verified able to <code>Swtich</code> accounts for a site in the<code>Permissions</code> panel.</li>
         <li>Verified able to <code>Disconnect</code> to a site origin from the <code>Permissions</code> panel.</li>
         <li>Verified able to view the <code>Selected Account</code> when <code>Disconnect</code> from a site origin</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/151580324-d40fa841-51d1-4ec6-b034-a826f1c98ee4.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151579052-e2a08579-7957-4b72-8481-9d391261544e.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151575371-8a052a1d-8cff-474d-8d93-95871d38e0d8.mov>
      </td>
   </tr>
</table>
