### ISSUE TITLE
Show BTC equivalent of current asset

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#19963]
Shows 0 BTC but should show accurate BTC fractio
![Screenshot_20211201-105152](https://user-images.githubusercontent.com/318119/144970163-4495f842-628e-4fc2-b986-1062dfc5b980.png)
n

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33.103 x64 build
- Verified BTC equivalent value is shown for all selected asset

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/145352483-eee4109d-d0bf-40fb-833a-ca598a49a5e8.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145352506-7dfb0a9d-9582-483f-ba53-884e31f333c3.png>
