### ISSUE TITLE
Timestamp to be hidden when initially when viewing asset detail

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#19964]
Currently shows timestamp (which should only be shown on press & drag) when asset detail screen is presented.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.33.103 x64 build
- Verified timestamp is not shown by default on portfolio graph
- Verified timestamp only shows when a particular time spot is selected on the portfolio graph
 
Asset Details | Time scale selected
-- | --
![image](https://user-images.githubusercontent.com/17010094/145351497-95afa6ce-7460-4af9-b40b-81bb58208530.png) | ![image](https://user-images.githubusercontent.com/17010094/145351513-9e2e2390-40c5-4ffc-9681-dc8b7d320b9d.png)

-----------
Verification passed on Oppo Reno 5 with Android 11 running 1.33.103 x64 build
- Verified timestamp is not shown by default on portfolio graph
- Verified timestamp only shows when a particular time spot is selected on the portfolio graph

Asset Details | Time scale selected
-- | --
![image](https://user-images.githubusercontent.com/17010094/145351529-45c76141-960e-4af5-b70e-05849d1b7a5c.png) | ![image](https://user-images.githubusercontent.com/17010094/145351542-0d7d7ce2-d6e2-4d50-993a-d636b02e236f.png)
