### ISSUE TITLE
Custom background image from brave://new-tab-page doesn't work

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#19962]
## Description 

Upstream custom background image feature is broken

## Steps to Reproduce

   1. Load brave://new-tab-page
   2. Go to customize page via bottom right button
   3. Upload any image via `Upload from device` button

## Actual result:

Uploaded image is not displayed as a bg

## Expected result:
Uploaded image should be used for bg

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Hi @simonhong - I'm not seeing this custom-background image UI exposed, using 

Brave | 1.35.72 Chromium: 97.0.4692.56 (Official Build) beta (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)

I also looked in `brave://flags` for it; are we awaiting a merge of `cr98` or something, first?

cc @brave/legacy_qa

**Comment by simonhong** [comment]
@stephendonner This issue is only for brave://new-tab-page. Can't see uploaded image at this page?
I confirmed that this page shows custom image with current beta(macOS).

**Comment by stephendonner** [comment]
> 1. brave://new-tab-page

I see it now, sorry; didn't realize there was an actual page at that address!  I was just opening a new-tab page, not loading that URL.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.72 Chromium: 97.0.4692.56 (Official Build) beta (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. loaded `brave://new-tab-page`
4. clicked on `Customize Brave` at the bottom-right corner
5. clicked on `Upload from device` at the next screen
6. uploaded my custom image
7. clicked `Done`

Confirmed my custom image replaced the default white background 👍 

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2022-01-05 at 3 57 11 PM" src="https://user-images.githubusercontent.com/387249/148306842-69e76099-1a0a-405d-8dd0-bca0debba3bd.png"> | <img width="1312" alt="Screen Shot 2022-01-05 at 3 57 15 PM" src="https://user-images.githubusercontent.com/387249/148306870-e1beda24-9706-4b78-9937-634c46fef411.png"> | <img width="1312" alt="Screen Shot 2022-01-05 at 3 57 27 PM" src="https://user-images.githubusercontent.com/387249/148306889-9a5bc296-588f-4054-8aa5-12a9f078d281.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.78 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
--|--
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Linux

Steps:
1. new profile
2. launched Brave
3. loaded `brave://new-tab-page`
4. clicked on `Customize Brave` at the bottom-right corner
5. clicked on `Upload from device` at the next screen
6. uploaded my custom image
7. clicked `Done`

Confirmed my custom image replaced the default white background

example | example | example
--------|-----------|---------
<img width="1200" alt="Screen Shot 2022-01-10 at 1 30 56 PM" src="https://user-images.githubusercontent.com/387249/148842697-8550a6c3-68ff-4c8a-89e8-10774acc8ce4.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 1 31 02 PM" src="https://user-images.githubusercontent.com/387249/148842701-cc738b56-2f5b-45d7-8f06-93adfc078e98.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 1 31 11 PM" src="https://user-images.githubusercontent.com/387249/148842705-1159e451-f091-4e18-9220-fb855c685e98.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Steps:

1. new profile
2. launched Brave
3. loaded brave://new-tab-page
4. clicked on Customize Brave at the bottom-right corner
5. clicked on Upload from device at the next screen
6. uploaded my custom image
7. clicked Done

Confirmed my custom image replaced the default white background

example | example | example
----------|----------|-----------
![19962-1](https://user-images.githubusercontent.com/387249/148844404-640987f2-5f02-4fe9-8468-c29b2d2d23fd.png) | ![19962-2](https://user-images.githubusercontent.com/387249/148844409-ae2f1993-7860-4f87-a827-884556eb4fd1.png) | ![19962-3](https://user-images.githubusercontent.com/387249/148844411-adf0cff0-88b9-44ca-b0f7-e53355d0e43d.png)
