### ISSUE TITLE
[Follow-up #19828] Save account watchlist button needs bottom padding 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19977]
## Description 
Based on https://github.com/brave/brave-browser/issues/19828#issuecomment-987958283 button needs bottom padding

## Actual result 

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/145011061-1ce9afda-a739-4ac8-88c8-10df119a98a8.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145011110-d1cb3658-4cc5-4687-beb6-411a5274fba1.png>

## Expected result
Better padding 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.33.100

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@jamesmudgett @SergeyZhukovsky Visually I don't see any change in the buttons position from the bottom navigation bar on Tablets. Can we move this one out of MVP and have a proper fix later on?

**Comment by SergeyZhukovsky** [comment]
we need to dig deeper, I saw a diff of my device, but yeah I don't on your devices. The combination of controls behaves strange. Let's move it to post MVP
