### ISSUE TITLE
Token swap fails

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19986]
## Description 

Token swap fails

## Steps to Reproduce

   1. Initiate a swap transaction from ETH -> USDC
   2. Transaction gets submitted once approved via panel
   3. Errors immediately after submitting

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/145183734-78d601ff-e333-4257-bb30-c0a45e8e94db.png)

## Expected result:
Successfully submit swap transaction

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.34.54 Chromium: 96.0.4664.55 (Official Build) beta (64-bit)
-- | --
Revision | `38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy @onyb

**Comment by srirambv** [comment]
Seems to be working but will need to investigate the issue as to why it suddenly stopped working for sometime 
![image](https://user-images.githubusercontent.com/17010094/145230716-3503fca4-291b-4c23-af45-77d40f078eae.png)

**Comment by nuo-xu** [comment]
Had the same experience on iOS. 
Was not able to swap some eth to usdc initially. But successfully swapped the same amount the next day.
![IMG_D1C947E98D92-1](https://user-images.githubusercontent.com/1187676/145232703-922e7ce3-4329-4b57-89ba-6da6e2e2c79c.jpeg)

**Comment by Douglashdaniel** [comment]
Looks like `Ratios - ETH Gas Price` was down for a moment today, maybe that was part of the issue? https://status.brave.com/

**Comment by srirambv** [comment]
This is fixed hence closing
