### ISSUE TITLE
Wallet icon in settings should be tinted to match the other monochrome icons

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#19984]
Currently shows in a grey on dark mode. This should be tinted with the same code that tints the other settings icons (except shields, and rewards)

![Screenshot_20211207-214347](https://user-images.githubusercontent.com/318119/145145119-e2dd19b5-9bb4-4186-9eb1-a226ab2d35e9.png)

**Comment by srirambv** [comment]
Dupe of  #19721
