### ISSUE TITLE
ads and trackers not displayed on marketwatch - follow up to 1874

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1998]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/1874

If you navigate to marketwatch.com the site hack (not showing the eternally loading banners) works, however if you enable Ads/Tracking, the ads never show. Seems as though the cosmetic filters are not being taken into consideration. 

This also happened with browser-laptop.

## Steps to Reproduce

   1. Clean profile navigate to marketwatch.com
   2. Verify eternally loading banners are not displayed.
   3. Allow Ads and Tracking from shields.

## Actual result:
Ads do not display on the page

## Expected result:
Ads should display.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by ryanbr** [comment]
Safe to close? (Just need to adjust filters to Aggressive on `https://www.marketwatch.com/`  @LaurenWags

**Comment by LaurenWags** [comment]
@ryanbr here's what I see with the various shield settings. If you can confirm the below images are expected then I think this is ok to close.

`Allow all trackers & ads`: ads are displayed on the side and banner ad is displayed:
<img width="1195" alt="Screen Shot 2020-11-02 at 7 38 30 AM" src="https://user-images.githubusercontent.com/28145373/97869220-16c18c80-1cdf-11eb-829f-1ea91c99ee28.png">

`Trackers & ads blocked (standard)`: "Loading" messages shown for side and banner ads:
<img width="1192" alt="Screen Shot 2020-11-02 at 7 38 55 AM" src="https://user-images.githubusercontent.com/28145373/97869224-17f2b980-1cdf-11eb-913f-5ed6978e2f7b.png">

`Trackers & ads blocked (aggressive)`: no "Loading" messages shown for side and banner ads:
<img width="1197" alt="Screen Shot 2020-11-02 at 7 39 18 AM" src="https://user-images.githubusercontent.com/28145373/97869227-19bc7d00-1cdf-11eb-999e-b1e045f07298.png">


Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)

**Comment by ryanbr** [comment]
Yeah, the non-collapse cosmetic elements seems to be related to first-party. @antonok-edm  could confirm ?

**Comment by antonok-edm** [comment]
Correct, looks like those are currently falling under first-party classification.
cc @pes10k

**Comment by pes10k** [comment]
I've got a solution to this and will put together a PR tomorrow, but the issue is there is some weird non-transitivy with innerText that i didn't account for.  Usually innerText gives you the text of the subtree, w/o the text of script nodes.  but, innerText on a script node gives you… the text of the script node.

I'll fix in a PR asap

**Comment by pes10k** [comment]
For release notes: "Improve heuristic for determining first/third-party-ness of ads for default cosmetic filtering"
QA test: the "Handling Script Tags" test on  https://dev-pages.brave.software/cosmetic-filtering/text-ads.html

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 with Android 5.1 running 1.18.67 Bravearm.apk
- Verified STR from description
