### ISSUE TITLE
Crash when open Asset's screen

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#19989]
Open Asset's screen on latest builds and observe a crash.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.33.103 x64 build
- Verified no browser crash when opening asset details screen
----------
Verification passed on Samsung Tab A  with Android 10 running 1.33.103 x64 build
- Verified no browser crash when opening asset details screen
