### ISSUE TITLE
crash with bookmarks overflow

### ISSUE THREAD

**Issue by Abmohamed07** [brave/brave-browser#19980]
## Steps to Reproduce

   1. Add bookmarks until your bookmarks bar is overflowing
   2. Click on the two arrows to view more bookmarks
   3. Brave browser crashes when I click the double arrows

## Brave version (brave://version info)

1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
http://76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@%7B#947}
Windows 11 Version Dev (Build 22509.1011)

## Version/Channel Information: Stable

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? IDK
- Can you reproduce this issue with the nightly channel? IDK

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
@Abmohamed07 When you get a chance can you go to brave://crashes and send the report from there and post the crash report id here.

**Comment by Abmohamed07** [comment]
This is the ID on the page, and I did click "Send Now"

3c7790b4-4fd5-42cb-abf2-2490b3a3c08b

**Comment by iefremov** [comment]
https://brave.sp.backtrace.io/p/brave/explore?filters=((callstack.functions%2Ccontains%2CMoveAndSetGroup)%2Cver%3E%3D%2292%22%2Cptype%3Dbrowser)&aggregations=((callstack%2Chead))&

```
[ 00 ] void TabStripModel::MoveAndSetGroup(int, int, class absl::optional<tab_groups::TabGroupId>)
[ 01 ] _tailMerge_esent.dll
[ 02 ] malloc_base
[ 03 ] malloc_base
[ 04 ] operator new(unsigned __int64)
[ 05 ] void TabStripModel::MoveTabsAndSetGroupImpl(const class std::__1::vector<int,std::__1::allocator<int> > & const, int, class absl::optional<tab_groups::TabGroupId>)
[ 06 ] TabGroupModel::AddTabGroup(tab_groups::TabGroupId const &,absl::optional<tab_groups::TabGroupVisualData>)
[ 07 ] void TabStripModel::AddToNewGroupImpl(const class std::__1::vector<int,std::__1::allocator<int> > & const, const class tab_groups::TabGroupId & const)
[ 08 ] chrome::OpenAllIfAllowed(Browser *,base::OnceCallback<content::PageNavigator * >,std::__1::vector<bookmarks::BookmarkNode const *,std::__1::allocator<bookmarks::BookmarkNode const *> > const &,WindowOpenDisposition,bool)
[ 09 ] 0x7ffb72c5101d
[ 10 ] malloc_base
[ 11 ] base::RandBytes(void *,unsigned __int64)
[ 12 ] TabStripModel::AddToNewGroup(std::__1::vector<int,std::__1::allocator<int> > const &)
[ 13 ] void BookmarkBarView::OnMenuButtonPressed(const class bookmarks::BookmarkNode *, const class ui::Event & const)

```

**Comment by iefremov** [comment]
Many thanks for the report @Abmohamed07

**Comment by mkarolin** [comment]
This could be an upstream bug fixed here https://source.chromium.org/chromium/chromium/src/+/ec3532203dd162ad783e3318119cf9d5bd8e3633

**Comment by adamocca** [comment]
Same issue occurring with Linux (mint 20.2). Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

**Comment by iefremov** [comment]
seems fixed upstream
