### ISSUE TITLE
Only list available tokens to swap similar to send 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19987]
## Description 
Swap from lists all tokens in the filter list which doesn't make sense and user need to type in tokens to select. Selecting a token that has not balance results in changing the swap button to `Insufficient balance` so rather to hide. However keep the Swap to list full 

## Actual result 
`Swap From` has full token list, including all tokens without balance

## Expected result
Only `Swap To` should have the full list so user can select which to swap to. `Swap From` should only list the tokens that have balance as those will be the only ones that can be used to swap

## Issue reproduces how often 
Easy

## Version/Channel Information:

All Versions of Brave on all platforms that supports wallets

## Brave version
All Wallet enabled versions

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @bbondy @jamesmudgett

**Comment by muliswilliam** [comment]
@jamesmudgett When discussing this issue with the frontend team, there was a concern raised: for new wallets, the token balances will be default be 0 and the users will see empty from list. One proposed solution was to use visual clues to assist the user when performing a swap. How do you propose we proceed with this?

**Comment by HEagle18** [comment]
@srirambv Are you happy this is now dealt with in Swaps 2.0 ?

**Comment by josheleonard** [comment]
We decided to still allow choosing unowned tokens during swaps so that users can obtain quotes for any token pair. We now display unowned tokens underneath the owned tokens under a dedicated grouping

See: [feat(wallet): Updated Select Token Modal](https://github.com/brave/brave-core/pull/23467#top)
