### ISSUE TITLE
Add private new tab page

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#200]
<img width="1303" alt="screen shot 2018-05-15 at 3 09 45 am" src="https://user-images.githubusercontent.com/4672033/40039630-7ac90370-57ed-11e8-8620-dc12ffbd70fc.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Nice work.
