### ISSUE TITLE
Support image param in wallet_watchAsset

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#20000]
Currently we do not support providing the image URL for custom tokens via wallet_watchAsset because we don't support getting a remote resource yet.

Test Plan:
1. Visit https://www.coingecko.com/en/coins/railgun and click on the fox icon to add suggest token
<img width="1163" alt="add_to_metamask" src="https://user-images.githubusercontent.com/4730197/145308959-61b8add5-8a79-48b5-820d-e61a15a09699.png">

2. Prompt should show up for adding suggest token (will be asking to unlock first if wallet is locked), make sure the icon is displayed as expected here.
![Screen Shot 2022-01-26 at 2 02 41 PM](https://user-images.githubusercontent.com/4730197/151246831-51f516f7-c69e-4210-8cee-527c300cc831.png)

3. Click to add the token and check the token is added to user visible asset list and make sure the icon is displayed as expected here.
![Screen Shot 2022-01-26 at 2 03 08 PM](https://user-images.githubusercontent.com/4730197/151246904-28c969eb-29d7-4e5c-9423-29af13246f56.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from issue description</li>
         <li>Verified <code>Add token</code> shows icon for the coin that is being added</li>
         <li>Verified custom asset added shows the icon on visible asset list </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/153857875-09e182fe-de07-4205-b501-ebc5b3785827.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153858820-265c2ef5-8168-4464-8be4-97b30e3b586f.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153858912-90192c63-6e02-4424-9b55-f9a44b14912d.mov>
      </td>
   </tr>
</table>
