### ISSUE TITLE
brave://settings nits

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#20002]
Here are a couple of minor nit issues with the formatting and presentation of brave://settings

1. Inconsistent "." use in settings descriptions
---
<img width="703" alt="screen_shot_2021-12-02_at_11 31 43_am" src="https://user-images.githubusercontent.com/76526/145336369-999b34c1-926f-46bb-9bed-b4dd733d75a6.png">

Some of the settings have a period at the end of the description, some don't. @mkarolin noted on Slack that Chrome settings don't have a period, so that might be the right way for Brave-added settings to go.

2. Inconsistent capitalization in the sidebar
---
<img width="302" alt="screen_shot_2021-12-08_at_10 05 25_pm" src="https://user-images.githubusercontent.com/76526/145336504-baee9194-d06d-4317-8704-e2e910c16087.png">

Some of the sidebar entries use title caps (e.g., “Security and Privacy”) and some use sentence caps (e.g., “Social media blocking”).  No suggested preference on my end, but as a data point, chrome:// uses only sentence caps

**Comment by rebron** [comment]
cc: @Tonev Something you can grab?

**Comment by Tonev** [comment]
@rebron 

The thing is developers keep introducing features with a period at the end of the description, so if I fix the current state, we can't guarantee consistency until you internally decide on a template for upcoming features. 

Let me know what you think about it.

**Comment by Rakshit358** [comment]
Is this issue still active?

**Comment by mkarolin** [comment]
@rebron I don't think this issue is actionable any more.
