### ISSUE TITLE
Importing password  without Sync

### ISSUE THREAD

**Issue by frogtile** [brave/brave-browser#20006]
## Description 
A way to import password, password which was exported from chromium based browsers

## Steps to reproduce 

   1. Go to settings - password
   2. Tab on the 3-dot on top-right   3. There is password export, but no import

## Actual result 
password importer isn't there

## Expected result
Option to import password

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by frogtile** [comment]
I don't  know if there exists password importing option on desktop version

**Comment by frogtile** [comment]
This issue should be brought to upstream chromium

**Comment by frogtile** [comment]
Hello?

**Comment by frogtile** [comment]
@bbondy man this is disappointing

**Comment by bbondy** [comment]
Can you just import from the importer on brave://welcome ?

**Comment by frogtile** [comment]
brave://welcome doesn't exist.

Even it exists on others installation, No.

**Comment by bbondy** [comment]
> brave://welcome doesn't exist.
> 
> Even it exists on others installation, No.

Sorry I missed the android label.
The best way is to setup desktop, import there and then sync to Android.

**Comment by frogtile** [comment]
> The best way is to setup desktop, import there and then sync to Android.

How do you know that I have a desktop?

**Comment by bbondy** [comment]
> How do you know that I have a desktop?

I don't. if you do, you can use it.

If not, then we have this issue to track adding support. 
Note that I didn't close this issue. 

Also note that we have over 4000 issues and comments like this 3 days after adding an issue won't help make this issue the top of our priority:
> @bbondy man this is disappointing

**Comment by frogtile** [comment]
@bbondy it would be very helpful if you bring this issue to chromium upstream

**Comment by frogtile** [comment]
@bbondy don't want it, don't use brave anymore, you guys should have done this earlier.
