### ISSUE TITLE
Brave News settings icon bug

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#20013]
## Description 
Tapping the Settings icon in the header bar sometimes goes to the article that is behind the icon.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.68, Chromium 97.0.4692.56` on a `Google Pixel XL` running `Android 9.0`.

Tested:
* tapping on the controls with various positions of content adjacent to the Settings widget (article heading, background image, and empty space)
* tapping on the `X` to return to the `Brave News` source-selection list
* stability (i.e. no crashes)

example | example | example | example
---------|----------|---------|---------
![Screenshot_20211230-160530](https://user-images.githubusercontent.com/387249/147795718-c2ef2d41-77a9-4ae3-915a-ecc91ebcc2ef.png) | ![Screenshot_20211230-160550](https://user-images.githubusercontent.com/387249/147795723-08a9a940-7864-4d8e-8309-f4c610509d9f.png) | ![Screenshot_20211230-160743](https://user-images.githubusercontent.com/387249/147795725-4ce49453-ac75-4b16-81d4-0e79f6a85bbd.png) | ![Screenshot_20211230-160535](https://user-images.githubusercontent.com/387249/147795734-c590ef2c-0ab8-4ca8-a122-89b588d4fc15.png)

**Comment by srirambv** [comment]
This is blocked on Android tablet due to #20407
