### ISSUE TITLE
Make Brave Talk widget default in NTP stack

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#20015]
Show Brave Talk widget on NTP by default by changing default visibility to `visible`. (Updated based on comment from @simonhong )

**Comment by simonhong** [comment]
How about changing widget's default visibility to `visible`?
By making it visible, existing users that have not customized it's visiblity and new users will see talk widget.
If users already modified its visibility, default value change doesn't affect to those users.

**Comment by mattmcalister** [comment]
> How about changing widget's default visibility to `visible`? By making it visible, existing users that have not customized it's visiblity and new users will see talk widget. If users already modified its visibility, default value change doesn't affect to those users.

That makes more sense, actually, yes. I've updated the original description.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.36.66 Chromium: 98.0.4758.66 (Official Build) nightly (x86_64)
-- | --
Revision | db1b4001d5ce29f141297f260d2b778e000b85a3-refs/branch-heads/4758@{#762}
OS | macOS Version 11.6.1 (Build 20G224)

## new installs

### 1.36.66, default (shown)
1. install `1.36.66`
3. launch Brave
4. click on `Skip welcome tour`
5. look at the widget stack on the right
6. click on `Brave Talk`

Confirmed Brave Rewards and Brave Talk were shown by default
Confirmed Brave Rewards is focused by default
Confirmed widget and links work (checked in more detail at the end)

step 5 | step 6
-------|-------
<img width="1312" alt="Screen Shot 2022-01-25 at 3 27 43 PM" src="https://user-images.githubusercontent.com/387249/151077215-ea1029ba-0cc5-4aa2-b8fd-0bb67d0375bb.png"> | <img width="1312" alt="Screen Shot 2022-01-25 at 3 30 33 PM" src="https://user-images.githubusercontent.com/387249/151077224-673c72f4-52f9-427a-849a-f58c00686b29.png">



## migration

### 1.34.81, default
1. install `1.34.81`
2. launch Brave
3. click `Skip welcome tour`
4. note the absence of a `Brave Talk` card on the new-tab page
5. upgrade to `1.36.66` (rename `Brave Browser` profile on macOS to `Brave Browser Nightly`, and relaunch with `1.36.66`)
6. confirm the`Brave Talk` card is visible on the new-tab page (behind `Brave Rewards`)
7. click on `Brave Talk`

Confirmed Brave Rewards and Brave Talk were shown by default
Confirmed Brave Rewards is focused by default
Confirmed widget and links work (checked in more detail at the end)

step 4 | step 6 | step 7
-------|-------|--------
<img width="1312" alt="Screen Shot 2022-01-25 at 3 32 11 PM" src="https://user-images.githubusercontent.com/387249/151077603-20370c07-d154-4a9d-b8a1-a3589aa7d5d4.png"> | <img width="1312" alt="Screen Shot 2022-01-25 at 3 32 52 PM" src="https://user-images.githubusercontent.com/387249/151077611-167fbca6-77d1-485d-af23-efa5db693aa7.png"> | <img width="1312" alt="Screen Shot 2022-01-25 at 3 32 57 PM" src="https://user-images.githubusercontent.com/387249/151077612-7910de44-2e4f-4439-a414-c46104914e7e.png">



### 1.34.81 ==> 1.33.66, card enabled
1. install `1.34.81`
2. launch Brave
3. click `Skip welcome tour`
4. note the absence of a `Brave Talk` card on the new-tab page
5. click `Edit Cards`
6. click on `+ Add` to add `Brave Talk`
7. confirm it's added and visible
8. upgrade to `1.36.66`
9. launch Brave
10. confirm the `Brave Talk` card is on the new-tab page

step 4 | step 7 | step 10
-------|--------|-------
<img width="1143" alt="Screen Shot 2022-01-25 at 3 20 10 PM" src="https://user-images.githubusercontent.com/387249/151076372-d03c3dfe-e1c3-4dbc-86d9-0c578401b1bd.png"> | <img width="1146" alt="Screen Shot 2022-01-25 at 3 20 31 PM" src="https://user-images.githubusercontent.com/387249/151076385-db70ab5f-d141-4ab2-bd05-d5b3f5ba9ff3.png"> | <img width="1145" alt="Screen Shot 2022-01-25 at 3 21 19 PM" src="https://user-images.githubusercontent.com/387249/151076393-9c71a539-ff4f-4e91-a3ed-c8b9a77aca51.png">

Confirmed Brave Rewards and Brave Talk were shown by default
Confirmed Brave Rewards is focused by default
Confirmed widget and links work (checked in more detail at the end)

---
Confirmed:
* `Start call` goes to `https://talk.brave.com/widget`
* `About your data` goes to `https://brave.com/privacy/browser/#brave-talk-learn`
* `...` `Hide` - confirmed widget can be hidden/re-added
