### ISSUE TITLE
Brave News large image bug

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#20012]
## Description 
Image dimensions not being enforced
![image](https://user-images.githubusercontent.com/71029/145448592-105105ed-04a0-4227-a5d1-3b3f9577f415.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.74, Chromium 97.0.4692.71` on a Google Pixel XL running Android 9.0.

Steps:
1. installed `1.35.74`
2. via `brave://flags`, enabled Brave News
3. tapped `Relaunch`
4. opened new-tab page
5. tapped `Enable Brave News`
6. swiped down
7. continued to swipe down for ~30 seconds

Confirmed I saw no tall images; everything was in its grid layout.


https://user-images.githubusercontent.com/387249/148315755-fddba887-9491-4fb2-9a21-bcb17f42e919.mp4
