### ISSUE TITLE
BAT icon missing in Brave News display ads

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#20011]
## Description 
The BAT Ad icon needs to appear in the upper right hand corner of Brave News Display Ads
![image](https://user-images.githubusercontent.com/71029/145446528-1b182381-7960-4f2b-8565-094d5ea2d044.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.74, Chromium 97.0.4692.71` on a Google Pixel XL running Android 9.0.

Steps:
1. installed `1.35.74`
2. opened `brave://flags`
3. enabled Brave News
4. tapped on `Relaunch`
5. opened a new-tab page
6. tapped on `Show Brave News`
7. swiped down, viewed cards

Confirmed using both `light` and `dark` themes, that the BAT ad icon was legible and in the correct place.

example | example | example | example | example
---------|----------|---------|----------|---------
![Screenshot_20220105-133137](https://user-images.githubusercontent.com/387249/148310682-f01cc270-2cca-4388-944d-070ade210434.png) | ![Screenshot_20220105-153536](https://user-images.githubusercontent.com/387249/148310689-5977883b-92f5-44c8-8f94-2a002b0fda0b.png) | ![Screenshot_20220105-164139](https://user-images.githubusercontent.com/387249/148310693-1838ad17-3512-440d-9a38-57148c7d553c.png) | ![Screenshot_20220105-164203](https://user-images.githubusercontent.com/387249/148310697-02bf66c6-f5a6-4023-8535-ade4ddce26b3.png) | ![Screenshot_20220105-164228](https://user-images.githubusercontent.com/387249/148310699-98751a9f-5e4c-45bb-af6b-9ce690ac3a6f.png)

**Comment by srirambv** [comment]
Verification failed on Samsung Tab A with Android 10 running 1.35.77 x64 Beta build. Logged #20412
