### ISSUE TITLE
Calculate BLS public key on native side

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#20024]
## Description 

Placeholder to move the implementation from typescript to native side. We are using `noble-bls12-381` to calculate BLS public keys for filecoin accounts, but there is rust library https://github.com/filecoin-project/filecoin-ffi to calculate it natively. 

and remove @noble/bls12-381 from typescript

**Comment by paulmillr** [comment]
Why native side? The noble-bls is tiny and will be audited in a bit.

**Comment by spylogsster** [comment]
@paulmillr we can't do a typescript library call for all cases, because it requires opening a web page
