### ISSUE TITLE
Brave wallet: the method wallet_watchAsset does not exist/is not available

### ISSUE THREAD

**Issue by ancho85** [brave/brave-browser#20026]
## Description 
A site cannot auto add a token to the Brave Wallet watchlist.

## Steps to Reproduce
   1. Go to morpher.com and add site's sidechain to the brave wallet networks. 
   2. Switch to morpher sidechain within Brave Wallet
   3. Visit https://www.morpher.com/trade/settings and click on the button "MPH in Metamask" and then "Add MPH (Sidechain)"

## Actual result:
Nothing happens. A console error appears.
```
{code: -32601, message: 'the method wallet_watchAsset does not exist/is not available'}
code: -32601
message: "the method wallet_watchAsset does not exist/is not available"
[[Prototype]]: Object
constructor: ƒ Object()...
```

## Expected result:
MPH should be added to the token watchlist

## Reproduces how often: 
Every time

## Version/Channel Information:
Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit)

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Didn't test it
- Can you reproduce this issue with the nightly channel?  Didn't test it

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Brave Wallet not available there.

## Miscellaneous Information:
None

**Comment by yrliou** [comment]
Thanks for reporting this, we just fixed https://github.com/brave/brave-browser/issues/17878 in our Nightly, and it will be supported starting from 1.35.24, thanks.

**Comment by yrliou** [comment]
You can try the feature out by downloading Brave Nightly via https://brave.com/download-nightly/, or wait for 1.35.x to be released around 02/01/2022.
Another option is downloading Beta via https://brave.com/download-beta/, which will be releasing 1.35.x around 12/28/2021.

**Comment by ancho85** [comment]
Thank you. I will
