### ISSUE TITLE
Wallet settings should be enabled only after wallet is created

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20027]
## Description 

Wallet settings should be enabled only after wallet is created for Android. For Desktop should only shown if an existing wallet/extension is found

## Steps to Reproduce

Android
   1. Clean install 
   2. Open Menu --> Settings -> Brave Wallet 
   3. Shows option to reset which doesn't makes sense as wallet is not created yet

Desktop
   1. Clean profile
   2. Open `brave://settings/wallet`
   3. All settings are available, able to reset wallet even without creating  

## Actual result:

Wallet settings are available which doesn't make sense

## Expected result:
On Desktop only show `Default cryptocurrency wallet` if no prior wallet/MM extension is detected. 
On Android only enable the settings when wallet is created

## Reproduces how often: 

Easy

## Desktop Brave version:

All

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @bbondy @Douglashdaniel

**Comment by bbondy** [comment]
not sure if this is needed because the wallet is actually always possible to be accessed in brave://wallet. It isn't like before with an install that happens for the wallet, nor like IPFS that needs an install action too.

**Comment by HEagle18** [comment]
Are we happy to close this because I don't see it being worked on in the short to medium term ? @bbondy @jamesmudgett

**Comment by bbondy** [comment]
I think it should be closed out because some wallet settings are useful even if the wallet is not created
