### ISSUE TITLE
Selecting repeated words in verify wallet screen removes all of them

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20037]
## Description 
Selecting repeated words in verify wallet screen removes all of them

## Steps to reproduce 

   1. Create wallet 
   2. See if you have repeated words 
   3. Try verifying seed, select one of the repeated word, both of them get removed

## Actual result 
Selecting repeated words in verify wallet screen removes all of them

## Expected result
Should only put one word in verify screen

## Issue reproduces how often 
Easy when you have repeated words

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.33.104

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.33.105

* Confirmed if backup words contain a repeated word, when verifying the wallet seed only one is removed from the verify list as expected

---------------

Verification passed on Pixel 3 XL with Android 11.0 running 1.33.105

* Confirmed if backup words contain a repeated word, when verifying the wallet seed only one is removed from the verify list as expected
