### ISSUE TITLE
Biometric unlock not coming up when autolock happens within wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20036]
Steps to reproduce:
- Go to wallet
- Lock your phone for 5 minutes
- Unlock your phone

Your wallet will go to the lock screen but no biometric button is present.

Expected:
It should be on the lock screen as it is, but there should be a way for biometric to come up.  Users don't want to have to type a long password.

Workaround:
Users can do a workaround if they experience this to go out of the wallet, then click on the wallet menu again, then it will come up.  But that is extra steps so not good UX.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.36.85 x64 beta build
- Verified steps from issue description
- Verified bio-metric unlock option shows up on lock screen irrespective of how the wallet is locked
