### ISSUE TITLE
Reduce wallet icon strength on Android

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20034]
## Description 
Wallet icon on Android looks bigger compared to the other icons 

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/145602731-bc129259-bd48-40df-972d-b5d932574059.png>

## Expected result
All icons looks same size 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.33.104 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by MohitMandalia** [comment]
Hi @bbondy ,

Could I take up this issue and work on it?

**Comment by jamesmudgett** [comment]
@MohitMandalia definitely! feel free to give it a shot.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.58, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.0.

Confirmed the `Brave Wallet` icon in `Settings` is correctly sized.

![Screenshot_20211225-161011](https://user-images.githubusercontent.com/387249/147371246-d735ffec-22e1-45fa-8b08-b74427c1f867.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.77 x64 beta build
- Verified wallet icon is of the same size compared to other icons 
- Verified on both dark and light theme

Dark | Light
-- | --
![image](https://user-images.githubusercontent.com/17010094/148730804-d1a2020c-b191-485a-ba92-977c51a98c45.png) | ![image](https://user-images.githubusercontent.com/17010094/148730845-b36cf597-b5d2-4067-a0f4-a7c1fdb07316.png)


@jamesmudgett although the size of the image is reduced it still looks bolder than other outline icons.
