### ISSUE TITLE
Refactor AssetDetailActivity.setUpAccountList to fetch balances after the list is displayed

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#20030]
Make changes to  https://github.com/brave/brave-core/blob/master/android/java/org/chromium/chrome/browser/crypto_wallet/activities/AssetDetailActivity.java to give the assets list and fill the balances later. Otherwise on slow network UI will have visible delay.

**Comment by simoarpe** [comment]
We are now relying on WebUI implementation to show assets list and balances. This activity will most likely be completely removed. Anything related to account list is inherited from Desktop. I'm closing this.
