### ISSUE TITLE
Text on a chart isn't smooth on tablet

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#20035]
![Screenshot from 2021-12-10 12-06-55](https://user-images.githubusercontent.com/12011303/145613465-30fbdc61-6bcc-46c2-b4e1-4ce3b649293d.png)

A text with date and time isn't smooth

**Comment by GeetaSarvadnya** [comment]
Verification passed on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarm64.apk_1.33.105`

- Confirmed text with `Date and Time` is smooth and clearly visible on the chart

Example | Example | Example
------|------|------
![Screenshot_20211213-195252_Brave](https://user-images.githubusercontent.com/38657976/145831052-1c403e20-fc64-4fe0-adce-65e9585c818f.jpg) | ![Screenshot_20211213-195307_Brave](https://user-images.githubusercontent.com/38657976/145831074-51ef9afe-f9da-4928-b632-ae1cc1fcd3a7.jpg) | ![Screenshot_20211213-195318_Brave](https://user-images.githubusercontent.com/38657976/145831087-b2068f5f-7798-445b-960b-9c86e4491cf3.jpg)
