### ISSUE TITLE
Can't dismiss grant notification

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#2004]
## Description 

It's possible to get into a state where a user is unable to dismiss a grant notification. This is most likely due to an old installation leaving an invalid value in `Preferences`.

## Steps to Reproduce

   1. Delete your existing profile
   2. Launch Brave
   3. Opt-in to Rewards
   4. Close Brave without dismissing the grant notification
   5. In your profile directory, open the `Preferences` file and in the `brave.rewards.notifications` section set id to `0`
   6. Save the `Preferences` file
   7. Launch Brave
   8. Try to dismiss grant notification by clicking its OK button

## Actual result:
Grant notification can't be dismissed

## Expected result:
Grant notification is dismissed when you click OK

## Reproduces how often: 
Always

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.56.9 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows
