### ISSUE TITLE
Add UI for Filecoin accounts in Brave Wallet

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#20053]
Add UI to allow users to work with multi-currencies and manage FIL in BraveWallet:
- Import from device
- Import by private key
- Sign Transactions/Messages and check balances

**Comment by spylogsster** [comment]
Example how it works in the web https://wallet.glif.io/

**Comment by lidel** [comment]
Note that aside from the main wallet actors, Filecoin has multisigs, which are special wallets that can have more than one "owner" than can sign transactions.  There is a separate interface for managing those at https://wallet.glif.io/vault?network=f, it includes the same operations as regular wallet plus ability to modify the list of "owners".
Not sure if this is in the scope, but mentioning it for completeness.

**Comment by spylogsster** [comment]
> Note that aside from the main wallet actors, Filecoin has [multisigs](https://lotus.filecoin.io/docs/set-up/multisig/), which are special wallets that can have more than one "owner", and one or more signatures required. There is a separate interface for managing those at https://wallet.glif.io/vault?network=f, it includes the same operations as regular wallet plus ability to modify the list of "owners". Not sure if this is in the scope, but mentioning it for completeness.

cc @jamesmudgett

**Comment by spylogsster** [comment]
if we selected to import filecoin accounts need to update import overlay to be like
![image](https://user-images.githubusercontent.com/2965009/150991078-0a0c42a4-d8d1-47ec-ada3-cc13672d22c9.png)
Filecoin app is only for Ledger

**Comment by spylogsster** [comment]
![image](https://user-images.githubusercontent.com/2965009/151147803-1bfbad63-ae4c-4f22-a3fa-0a1afa74e8d2.png)
We need to add network selectors here and key type:
Network: Testnet, Mainnet, but we can use same as glif (Use t addresses/Use f addresses):
![image](https://user-images.githubusercontent.com/2965009/151148043-8dac20aa-2846-451c-a0c4-794a44cc8476.png)

Key Type: Private key BLS12-381/Private Key secp256k1
