### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by yessGlory17** [brave/brave-browser#20055]
npm run init

> brave@1.35.24 init
> node ./scripts/init.js

Performing initial checkout of brave-core
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> git rev-parse HEAD
Resetting brave core to "c2a832fa225523d7da7df1a4fe79fbd0e41badcc"...
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> git reset --hard HEAD
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> git checkout c2a832fa225523d7da7df1a4fe79fbd0e41badcc
...brave core is now at commit ID c2a832fa225523d7da7df1a4fe79fbd0e41badcc
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> npm install
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> npm run sync -- --init

> brave-core@1.35.24 sync
> node ./build/commands/scripts/sync.js "--init"

Brave Browser Sync starting
Fixup Depot Tools...
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> git -C /home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave/vendor/depot_tools clean -fxd
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> git -C /home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave/vendor/depot_tools reset --hard HEAD
HEAD şimdi şurada: ecc14aa4 Roll recipe dependencies (trivial).
Done Depot Tools...
Stashing any local changes
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> git stash
Running gclient sync...
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> git rev-parse HEAD
Resetting brave core to "c2a832fa225523d7da7df1a4fe79fbd0e41badcc"...
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> git reset --hard HEAD
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave
> git checkout c2a832fa225523d7da7df1a4fe79fbd0e41badcc
...brave core is now at commit ID c2a832fa225523d7da7df1a4fe79fbd0e41badcc
-------------------------------------------------------------------------------
/home/ozgur/Masaüstü/Open-Source/brave-browser
> gclient sync --reset --nohooks --revision src/brave@master --revision src@refs/tags/97.0.4692.36 --force --with_tags --with_branch_heads --upstream
Platform linux-amd64 is not supported by the CIPD client bootstrap: there's no pinned SHA256 hash for it in the *.digests file.
Platform linux-amd64 is not supported by the CIPD client bootstrap: there's no pinned SHA256 hash for it in the *.digests file.
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave/vendor/depot_tools/bootstrap_python3: satır 32: bootstrap-2@3.8.10.chromium.23_bin/python3/bin/python3: No such file or directory
Platform linux-amd64 is not supported by the CIPD client bootstrap: there's no pinned SHA256 hash for it in the *.digests file.
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave/vendor/depot_tools/bootstrap_python3: satır 32: bootstrap-2@3.8.10.chromium.23_bin/python3/bin/python3: No such file or directory
cat: /home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave/vendor/depot_tools/python3_bin_reldir.txt: No such file or directory
/home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave/vendor/depot_tools/vpython3: satır 52: /home/ozgur/Masaüstü/Open-Source/brave-browser/src/brave/vendor/depot_tools/.cipd_bin/vpython3: No such file or directory
null
null
null
null

OS: Ubuntu 20.04

**Comment by Brave-Matt** [comment]
@yessGlory17,
We typically use Github for logging issues rather than direct support. It appears you are trying to build the browser from source and are having some trouble. Can you please reach out to us on our [Community website](https://community.brave.com/c/contributing/developers/8) with your issue? Please include _as much detail about the issue as possible_ so that we can provide you with the best support. 

Thank you.
