### ISSUE TITLE
Request ads enabled popup couldn't be scrolled in landscape mode

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#20060]
Steps to reproduce:
- Install and run Release Brave browser on Android
- Switch phone to landscape mode
- Open talk.brave.com
- Press `Start free 1:1 call` button
- `Request ads enabled` popup shoud be shown

Actual result:
- `Request ads enabled` popup couldn't be scrolled

Expected result:
- `Request ads enabled` popup could be scrolled

**Comment by stephendonner** [comment]
@mattmcalister @jsecretan this won't be testable at present due to @tackley's changes before Christmas.

Should we punt on this to a future milestone, for verification, or just skip?

**Comment by jsecretan** [comment]
Yes, should be ok to skip for now

**Comment by srirambv** [comment]
Confirmed with @jsecretan and marking as `QA/No` as we have changed the free call tier upto 4 people now. We need to add a follow up issue and verify if this changes in the future.
