### ISSUE TITLE
Update IPFS node to go-ipfs v0.11.0

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#20072]
go-ipfs 0.11 was released: https://github.com/ipfs/go-ipfs/releases/tag/v0.11.0

* There are no breaking changes that impact Brave integration, and should be just a matter of bumping the version on your end.
  * go-ipfs 0.11+ will fix the "rebooting printer" issue from https://github.com/brave/brave-browser/issues/19007, as noted and confirmed  in https://github.com/ipfs/go-ipfs/issues/8534#issuecomment-985665628
* This is not urgent, can be tackled in January, after holidays

**Comment by rebron** [comment]
cc: @spylogsster

**Comment by stephendonner** [comment]
Tested 0.11.0 using `1.34.80` on:
* Windows: https://github.com/brave/brave-browser/issues/20253
* macOS: https://github.com/brave/brave-browser/issues/20254
* Linux: https://github.com/brave/brave-browser/issues/20255

Unrelated to `0.11.0` but found while testing:
* https://github.com/brave/brave-browser/issues/20340
* https://github.com/brave/brave-browser/issues/20341

PR up for adding release notes: https://github.com/brave/brave-core-crx-packager/pull/305

**Comment by stephendonner** [comment]
We shipped this to production around 10:15am PDT 1/11/2022.
