### ISSUE TITLE
[Feature Request] Auto update script for github release for Linux

### ISSUE THREAD

**Issue by tazihad** [brave/brave-browser#20085]
## Description 
Brave browser installed from github do not auto update. Brave Software suggests to install Brave browser to install from brave site or flatpak version. But for immutable os like Fedora Silverblue doesn't have easy way to install from Brave repo. And Flatpak Brave browser has many problems. ex: hardware acceleration not working. KeepassXC not working. This issues can be easily solved when used with Brave release from github. But there's only one problem. Brave release doesn't have auto update feature. 

## Steps to Reproduce
   1. Download Brave browser from releases section of github
   2. Download any version nightly or stable
   3. Download example "brave-browser-1.33.104-linux-amd64.zip"

## Actual result:
Brave browser do not update itself. Need manual download for every release

## Expected result:
A bash script should be added which will be run when Brave Browser is run to check and auto update.

## Version/Channel Information:
Script for both nightly and stable

## Miscellaneous Information:
I was able to get good performance in Github release of Brave browser in Fedora Silverblue. But failed in  flatpak version from Flathub beta. KeepassXC do not work in flatpak version. The problem of Brave browser in Fedora Silverblue/Kinoite can be easily solve if installed from Github release. A auto update feature is needed for linux build.

**Comment by wknapik** [comment]
Linking https://github.com/brave/brave-browser/issues/21409
