### ISSUE TITLE
Start using PGO with chromium profiles

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#20086]
PGO can dramatically improve browsing speed in some scenarios: https://blog.chromium.org/2020/08/chrome-just-got-faster-with-profile.html.

A new switch to `npm run init` should be implemented to enable using PGO in nightly CI builds.
Slack discussion: https://bravesoftware.slack.com/archives/C7VLGSR55/p1639408091273200

**Comment by atuchin-m** [comment]
**for QA**: 
* only speed improvement, no behavior changed;
* compare nightly speed (with fixed and without) on https://browserbench.org/Speedometer2.0/.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.32 Chromium: 97.0.4692.71 (Official Build) nightly (64-bit)
--|--
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Compared to 

Brave | 1.36.16 Chromium: 97.0.4692.71 (Official Build) nightly (64-bit)
--|--
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 20H2 (Build 19042.1415)

**Higher numbers are better, here:**

current, `187` (median) | previous, `146` (median)
---------|----------
![current](https://user-images.githubusercontent.com/387249/149048607-5c627ced-82f7-4434-8c75-4cd6e7d16bbc.png) | ![previous](https://user-images.githubusercontent.com/387249/149048610-2476fdaf-8d0c-46f1-8a53-d824b9eed19a.png)

Brave `1.36.32`:

`194, 194, 187, 185, 184`

run 1 | run 2 | run 3 | run 4 | run 5
------|--------|-------|-------|-------
![20086-1-current](https://user-images.githubusercontent.com/387249/149047850-1db39901-2132-4a34-b665-1f5769785391.png) | ![20086-2-current](https://user-images.githubusercontent.com/387249/149047851-7bf88ff0-a386-481e-8323-3e25071b28b6.png) | ![20086-3-current](https://user-images.githubusercontent.com/387249/149047852-db1a2bf9-d3a1-41b2-877a-1a7fdceb4530.png) | ![20086-4-current](https://user-images.githubusercontent.com/387249/149047853-d8d61573-e83b-4659-97fb-ebebd82dd8b5.png) | ![20086-5-current](https://user-images.githubusercontent.com/387249/149047855-cfb1e8fb-f27a-4daa-86da-02335b8bb785.png)


Brave `1.36.16`:

`165, 152, 146, 146, 143`

run 1 | run 2 | run 3 | run 4 | run 5
-------|-------|------|--------|-------
![20086-1-previous](https://user-images.githubusercontent.com/387249/149047915-9656aa75-a066-4427-a085-27c99dfc5a25.png) | ![20086-2-previous](https://user-images.githubusercontent.com/387249/149047918-508edd3d-033e-4f2d-8e42-b3306d3592a7.png) | ![20086-3-previous](https://user-images.githubusercontent.com/387249/149047920-2ae92456-54c5-4727-9b12-efb6d29ed32d.png) | ![20086-4-previous](https://user-images.githubusercontent.com/387249/149047922-501834ca-bd8a-4228-b2f0-f2a4a9789682.png) | ![20086-5-previous](https://user-images.githubusercontent.com/387249/149047924-a3b257af-e611-410c-800d-31f202337602.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.36.37

Compared to 

Brave | 1.36.16 Chromium: 97.0.4692.71 (Official Build) nightly (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)

**Higher numbers are better, here:**

current, `` (median) | previous, `` (median)
---------|----------

### Brave `1.36.37`:

``

run 1 | run 2 | run 3 | run 4 | run 5
------|--------|-------|-------|-------
<img width="1312" alt="Screen Shot 2022-01-13 at 4 05 19 PM" src="https://user-images.githubusercontent.com/387249/149429059-b2a39b20-9bbd-486e-82b9-a35d1905204a.png"> | <img width="1312" alt="Screen Shot 2022-01-13 at 4 06 21 PM" src="https://user-images.githubusercontent.com/387249/149429064-23ec518c-e290-4e42-b6d2-8699222e1f71.png"> | <img width="1312" alt="Screen Shot 2022-01-13 at 4 07 26 PM" src="https://user-images.githubusercontent.com/387249/149429068-5aee2bf8-b3ae-44cd-9e56-a49dcb2c6989.png"> | <img width="1312" alt="Screen Shot 2022-01-13 at 4 08 29 PM" src="https://user-images.githubusercontent.com/387249/149429070-c6468600-84af-4662-826d-f057a8c4d5b7.png"> | <img width="1312" alt="Screen Shot 2022-01-13 at 4 09 35 PM" src="https://user-images.githubusercontent.com/387249/149429072-fdf3efb3-2bcd-4c1b-8ae4-a0f0aee1b3cb.png">



### Brave `1.36.16`:

``

run 1 | run 2 | run 3 | run 4 | run 5
-------|-------|------|--------|-------
<img width="1312" alt="Screen Shot 2022-01-13 at 4 05 19 PM" src="https://user-images.githubusercontent.com/387249/149430621-658ae9b2-9ba5-43df-9d0c-c215ff3fb585.png"> | <img width="1312" alt="Screen Shot 2022-01-13 at 4 06 21 PM" src="https://user-images.githubusercontent.com/387249/149430625-b347cf61-604d-4cb4-b2b7-59a4a13fd15f.png"> | <img width="1312" alt="Screen Shot 2022-01-13 at 4 07 26 PM" src="https://user-images.githubusercontent.com/387249/149430628-9227c64c-eb70-479d-a057-de19dbf3b404.png"> | <img width="1312" alt="Screen Shot 2022-01-13 at 4 08 29 PM" src="https://user-images.githubusercontent.com/387249/149430630-e0003967-3013-43ba-b45b-37584ea0efe3.png"> | <img width="1312" alt="Screen Shot 2022-01-13 at 4 09 35 PM" src="https://user-images.githubusercontent.com/387249/149430632-54abcfbf-05ee-4f54-9a93-ccbafa8f22af.png">

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 


Compared to 


**Higher numbers are better, here:**

current, `` (median) | previous, `` (median)
---------|----------


### Brave `1.36.33`:

``

run 1 | run 2 | run 3 | run 4 | run 5
------|--------|-------|-------|-------


### Brave `1.36.16`:

``

run 1 | run 2 | run 3 | run 4 | run 5
-------|-------|------|--------|-------
