### ISSUE TITLE
Remove Make searches and browsing better

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2008]
## Description 

Remove Make searches and browsing better

## Steps to Reproduce

   1. Build from master (e50c886)
   2. Settings-> Sync and Brave Services -> Make searches and browsing better
   3. Need to remove this from settings

## Actual result:
![image](https://user-images.githubusercontent.com/17010094/48072160-e3a89900-e1a9-11e8-84ac-d3ef19cf4f72.png)

## Expected result:
Should be removed 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

master(e50c8861e966bfad1cd830f7813ee5abe79a4867)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Data collection should not be there as there is no data being collected from user profile

![image](https://user-images.githubusercontent.com/17010094/48072557-cc1de000-e1aa-11e8-8c5e-81aacf9d02f4.png)

**Comment by rebron** [comment]
Closing. This was fixed when we removed Sync services when a Chromium update inserted them, I believe with 57.x.
