### ISSUE TITLE
Brave News add Share option to long press menu

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20098]
Add Share button to the bottom menu when long pressing on card title
To be placed first in the list of buttons

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.58, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.0.

Confirmed I got a `Share` option, and tested sharing the link in Slack/opening in a browser session, etc.

example | example
----------|----------
![Screenshot_20211224-100641](https://user-images.githubusercontent.com/387249/147368292-c68e3e02-2bc4-4db4-a5a7-12954f5c3611.png) | ![Screenshot_20211224-100654](https://user-images.githubusercontent.com/387249/147368297-a17d0d30-f6b1-45b5-ab07-82c69d417b5a.png)
