### ISSUE TITLE
Don't allow viewing Site Permissions Panel for brave://wallet route

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20094]
## Description 
Previously we showed a `Connected` status and didn't allow viewing the `Site Permissions` in the panel when your current tabs origin is `brave://wallet`. It has regressed and needs to be fixed to not allow.

https://user-images.githubusercontent.com/40611140/146084580-b74a21ca-b0f7-4ec2-989b-2c9766dcf13a.mov

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.69 Chromium: 97.0.4692.56 (Official Build) dev (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. created a wallet
3. loaded `brave://wallet/crypto/portfolio`
4. clicked on the Wallet icon on the browser toolbar
5. confirmed I couldn't click on `Not connected`, but *could* click on `Ethereum`, as expected

example | example | example
---------|----------|---------
<img width="1021" alt="Screen Shot 2021-12-30 at 1 58 07 PM" src="https://user-images.githubusercontent.com/387249/147790698-0221010b-278e-42fa-b115-590693b1a6a3.png"> | <img width="1021" alt="Screen Shot 2021-12-30 at 2 00 13 PM" src="https://user-images.githubusercontent.com/387249/147790701-f69089b4-7c24-471d-b1e7-0f1ab2e9cf64.png"> | <img width="1021" alt="Screen Shot 2021-12-30 at 2 00 15 PM" src="https://user-images.githubusercontent.com/387249/147790704-f08cb50c-332b-4590-ae9d-67950bca882c.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | `adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}`
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified test plan from [brave/brave-core#11603](https://github.com/brave/brave-core/pull/11603)
- Verified sites permission shows `Connected` for `brave://wallet`
- Verified clicking on it doesn't open account list 
- Verified even when multiple accounts are added site permission doesn't open 
- Verified still able to select Network dropdown and change network

------
Verification passed on 

Brave | 1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | `adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}`
OS | Linux

- Verified test plan from [brave/brave-core#11603](https://github.com/brave/brave-core/pull/11603)
- Verified sites permission shows `Connected` for `brave://wallet`
- Verified clicking on it doesn't open account list 
- Verified even when multiple accounts are added site permission doesn't open 
- Verified still able to select Network dropdown and change network
