### ISSUE TITLE
suggestion: add regex search

### ISSUE THREAD

**Issue by tommycarstensen** [brave/brave-browser#201]
There is an extension for Chrome that allows me to do regex searches:
https://chrome.google.com/webstore/detail/chrome-regex-search/bpelaihoicobbkgmhcbikncnpacdbknn

This is helpful when looking up prices and when browsing technical data.

Brave does not allow installation of extensions.

Would it be possible to add regex search to Brave? Thanks!

**Comment by srirambv** [comment]
Beta and Dev builds now allow installing of extensions from CWS. Should be able to install any extensions from there.
