### ISSUE TITLE
Allow 0 gas price in legacy gas controls

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20103]
User report: https://community.brave.com/t/brave-wallet-not-allowing-0-gas-price-on-arbitrum-test-network/308777

This is kind of a rare case, but we would like to support it. This is typically the case with PoA networks which do allow zero gas price for transactions.

Doesn't apply to networks supporting EIP-1559 transactions, where minimum price of `baseFee` must be paid for burning. The `maxPriorityFeePerGas` could however be zero.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.34.78 Chromium: 97.0.4692.56 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11662>brave/brave-core#11662</a></li>
         <li>Verified able to set 0 gas price for legacy gas controls</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/148192654-2ffc672a-d2cf-4595-bcfd-9d8f1e8a4dc0.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/148192800-cc7ca8b1-12b8-4d7f-a719-e198296e5a35.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/148192680-9b1ce161-815a-49bc-bb14-a5c9d593b6e0.mov>
      </td>
   </tr>
</table>
