### ISSUE TITLE
Rename Private Ads to Brave Private Ads in brave://rewards

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#20108]
This is a follow-up to https://github.com/brave/brave-browser/issues/18983. The title for the Ads settings should be `Brave Private Ads` not `Private Ads`.

cc: @Miyayes

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.56 Chromium: 97.0.4692.56 (Official Build) nightly (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)

See verification notes over in https://github.com/brave/brave-browser/issues/18983#issuecomment-1000906912.
