### ISSUE TITLE
Enable EIP-1559 Type-2 transactions for Trezor keyring

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20116]
We currently force Trezor keyring to always create Type-0 (legacy) transactions. Since the new Trezor firmware now supports EIP-1559, we should default to Type-2 transactions now.

See relevant code [here](https://github.com/brave/brave-core/blob/db0589c266238e18872ef7a7f29ef658afbffbf3/components/brave_wallet_ui/common/async/handlers.ts#L307-L309).

### Test plan

(ensure Trezor keyring is used)

- For wallet-originating transactions on Ethereum networks, should use EIP-1559 gas fields.
- For dapp-initiated transactions on Ethereum networks, should use EIP-1559 gas fields.
- For all other EVM compatible networks, should use legacy gas fields.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.99 Chromium: 98.0.4758.72 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified Wallet-initiated transactions and Dapp-initiated transactions use EIP-1559 transaction gas estimates</li>
         <li>Verified EVM-initiated transactions use legacy(Type-0) transaction gas estimates</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Wallet-originated tx
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/152000690-66364b16-1002-4c84-90c2-58785f05f1d1.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152005688-26d516b2-54c2-4b0a-b03b-526bdc37b525.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151998408-0ada8b9f-c45c-4737-b856-f2df764e3b59.mov>
      </td>
   </tr>
   <tr>
      <td>Dapp-initiated tx
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/152000737-32ff0d19-ac9f-40d0-87dc-74841de6e644.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152004864-1edc22b6-4eaa-4e40-8680-53cb981edcc4.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151998286-4fe5852a-7f6f-46a2-972a-3ededafada3d.mov>
      </td>
   </tr>
   <tr>
      <td>EVM-initiated tx
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/152000777-31f0c493-6f63-469f-9a3b-9b4e1f05a453.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152005245-eda23dfb-6e01-4117-87aa-52cfcc3ef249.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151998345-986143ed-a1af-44ef-aab7-e6fff01af973.mov>
      </td>
   </tr>
</table>
