### ISSUE TITLE
`Private with Tor` should just read `Tor` in `New private window with Tor`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20118]
## Description 

`Private with Tor` should just read `Tor` in `New private window with Tor`

Per https://github.com/brave/brave-browser/issues/13704.

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. click on the "hamburger" menu on the browser toolbar
   4. choose `New private window with Tor`
   5. examine the icon and text to the right of the URL bar

## Actual result:

![13704-3](https://user-images.githubusercontent.com/387249/146273031-92992a26-415f-444f-bbfc-ddd88020352e.png)

## Expected result:

Should just read `Tor`, according to https://github.com/brave/brave-browser/issues/13704

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)

cc @nullhook @rebron

**Comment by rebron** [comment]
cc: @diracdeltas Wanted to double check this is ok, going from `Private window with Tor` to just `Tor`. It's a follow-up to https://github.com/brave/brave-browser/issues/13704 to make some room in the toolbar.

**Comment by diracdeltas** [comment]
sgtm
