### ISSUE TITLE
Remove additional instagram and Marketo tracking query parameters

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#20115]
Identified by https://privacytests.org/

As best i can tell, the instagram `igshid` is the id of the profile doing the sharing, and so should be blocked.

Similarly the Marketo `mkt_tok` value seems to also identify the email recipient.
https://nation.marketo.com/t5/product-discussions/what-s-the-use-of-mkt-tok-in-emails/m-p/303482

**Comment by fmarier** [comment]
Dupe of https://github.com/brave/brave-browser/issues/9018 and https://github.com/brave/brave-browser/issues/11580.
