### ISSUE TITLE
Hang/crash when tapping between thumbnail and full-tab mode for Brave News

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20124]
## Description 

Hang/crash when tapping between thumbnail and full-tab mode for Brave News

## Steps to reproduce 

Steps:
1. launch Brave
2. enable Brave News via `brave://flags`
3. leave the Brave News opt-in up
4. open a Brave News new-tab page
5. tap on the `[1]` on the bottom toolbar, to put it into a thumbnail/tile layout
6. tap again to refocus and full-screen the page
7. repeat steps 3&4 until you hang/crash

## Actual result 

<video src="https://user-images.githubusercontent.com/387249/146286048-cf177e0d-828c-4395-8286-a6be16252bec.mp4"></video>

All I get via Backtrace is a bunch of registers; on their website, it's another "generic"-looking `libmonochrome.so` crash (looks like we need symbols uploaded).

## Expected result

No crash when tapping between tab-view/preview modes

## Issue reproduces how often 
100%

## Version/Channel Information:
Brave `1.34.63, Chromium 96.0.4664.110` (currently `beta/dev`)

/cc @alexsafe

**Comment by alexsafe** [comment]
@stephendonner this one has been solved for some time. should i link a PR and close?

**Comment by stephendonner** [comment]
> @stephendonner this one has been solved for some time. should i link a PR and close?

Yes, please, and thanks!

**Comment by srirambv** [comment]
This one seems fixed as well but since its a OOM crash would be good to test once on older device. 

cc: @laurenwags to test on her Android 6 device once and see if it crashes. If no crash then we are good to close this

**Comment by LaurenWags** [comment]
@srirambv I couldn't reproduce the crash with 1.34.81, 1.35.100, 1.36.80.

**Comment by stephendonner** [comment]
> This one seems fixed as well but since its a OOM crash would be good to test once on older device.
> 
> cc: @LaurenWags to test on her Android 7 device once and see if it crashes. If no crash then we are good to close this

Agreed; @alexsafe mind closing this with a link to the relevant series of commits?

**Comment by stephendonner** [comment]
Verified `PASSED` for me using Brave `1.37.67, Chromium 99.0.4844.35` on a `Google Pixel XL` (`arm64`) running `Android 9.0.`

Ran through my original steps (and then some), and confirmed there's no crashes 👍 


https://user-images.githubusercontent.com/387249/155402308-46dcc77d-5413-4044-803b-346f33ecbfa9.mp4
