### ISSUE TITLE
Tweak the behavior of the #brave-adblock-cookie-list-default flag

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#20126]
The original implementation of the `#brave-adblock-cookie-list-default` flag, added in https://github.com/brave/brave-browser/issues/19689, simply removed the cookie list from the regional lists on `brave://adblock` and forced it to always be on.

After further discussion, we want the option of turning it off to still be available to users. The revised implementation should continue to present the cookie list option in `brave://adblock`, but store an additional boolean preference to keep track of whether or not a user has interacted with its toggle in the past. Whenever the `#brave-adblock-cookie-list-default` feature is active, that particular list will default to "enabled" regardless of the underlying per-list setting, so long as it was never manually changed.

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using

Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)


Followed the testplan from https://github.com/brave/brave-core/pull/11621.

Steps:

1. Visit https://digikey.com and confirm that a cookie notice is shown. It will appear either as a banner at the top, or as a popup along the bottom depending on window size.
2. Visit brave://flags and enable the #brave-adblock-cookie-list-default flag, then restart the browser.
3. Visit https://digikey.com and confirm that no cookie notice is shown.
4. Visit brave://adblock and confirm that the entry for Easylist-Cookie List - Filter Obtrusive Cookie Notices under Additional filters exists and is checked.
5. Return to brave://flags and set #brave-adblock-cookie-list-default to Disabled, and restart the browser.
6. Visit https://digikey.com and confirm that the cookie notice is shown again.
7. Visit brave://adblock and confirm that the entry for Easylist-Cookie List - Filter Obtrusive Cookie Notices is no longer checked.
8. Manually toggle the Easylist-Cookie List - Filter Obtrusive Cookie Notices entry to be enabled, then repeat steps 2-5.
9. Visit brave://adblock and confirm that the entry for Easylist-Cookie List - Filter Obtrusive Cookie Notices is checked.
10. Manually toggle the Easylist-Cookie List - Filter Obtrusive Cookie Notices entry to be disabled.
11. Visit brave://flags and enable the #brave-adblock-cookie-list-default flag, then restart the browser.
12. Visit brave://adblock and confirm that the entry for Easylist-Cookie List - Filter Obtrusive Cookie Notices is unchecked.
13. Visit https://digikey.com and confirm that the cookie notice is shown.

step1 | step 2 | step 3 | step 4 | step 5 | step 6 | step 7
-------|--------|--------|--------|--------|--------|--------


step 8a | step 8b | step 8c | step 9 | step 10 | step 11 | step 12 | step 13
--------|---------|---------|----------|---------|---------|----------|---------

**Comment by stephendonner** [comment]
Verification `PASSED` using

Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Followed the testplan from https://github.com/brave/brave-core/pull/11621.

Steps:

1. Visit `https://digikey.com` and confirm that a cookie notice is shown. It will appear either as a banner at the top, or as a popup along the bottom depending on window size.
2. Visit `brave://flags` and enable the `#brave-adblock-cookie-list-default` flag, then restart the browser.
3. Visit `https://digikey.com` and confirm that no cookie notice is shown.
4. Visit `brave://adblock` and confirm that the entry for `Easylist-Cookie List - Filter Obtrusive Cookie Notices` under `Additional filters` exists and is checked.
5. Return to `brave://flags` and set `#brave-adblock-cookie-list-default` to `Disabled`, and restart the browser.
6. Visit `https://digikey.com` and confirm that the cookie notice is shown again.
7. Visit `brave://adblock` and confirm that the entry for `Easylist-Cookie List - Filter Obtrusive Cookie Notices` is no longer checked.
8. Manually toggle the `Easylist-Cookie List - Filter Obtrusive Cookie Notices` entry to be `enabled`, then repeat steps 2-5.
9. Visit `brave://adblock` and confirm that the entry for `Easylist-Cookie List - Filter Obtrusive Cookie Notices` is checked.
10. Manually toggle the `Easylist-Cookie List - Filter Obtrusive Cookie Notices` entry to be `disabled`.
11. Visit `brave://flags` and `enable` the `#brave-adblock-cookie-list-default` flag, then restart the browser.
12. Visit `brave://adblock` and confirm that the entry for `Easylist-Cookie List - Filter Obtrusive Cookie Notices` is `unchecked`.
13. Visit `https://digikey.com` and confirm that the cookie notice is shown.

step1 | step 2 | step 3 | step 4 | step 5 | step 6 | step 7
-------|--------|--------|--------|--------|--------|--------
![20126-1](https://user-images.githubusercontent.com/387249/148832977-9f3775e2-5ffb-430e-bfaf-50e0936678b6.png) | ![20126-2](https://user-images.githubusercontent.com/387249/148832979-96c636ba-4135-49e6-8582-e0eb5c153e49.png) | ![20126-3](https://user-images.githubusercontent.com/387249/148832980-969eca5b-9392-42a3-a494-51e7664c7757.png) | ![20126-4](https://user-images.githubusercontent.com/387249/148832981-145aac9f-97da-46aa-a7a3-eff39cd2b441.png) | ![20126-5](https://user-images.githubusercontent.com/387249/148832982-ffd9505c-d3f9-49e7-b960-8cd431984f85.png) | ![20126-6](https://user-images.githubusercontent.com/387249/148832985-72db446f-ea63-46c8-b928-985d481b5860.png) | ![20126-7](https://user-images.githubusercontent.com/387249/148832990-85d18a8c-c2d2-44e8-8b7a-918694bb503e.png)




step 9 | step 10 | step 11 | step 12 | step 13
----------|---------|---------|----------|---------
![20126-10](https://user-images.githubusercontent.com/387249/148833144-3adb1421-cf7a-419c-b60f-7ff45508eb37.png) | ![20126-11](https://user-images.githubusercontent.com/387249/148833147-ddc01c43-ac4d-4d11-bd5a-beec06ab9a5e.png) | ![20126-12](https://user-images.githubusercontent.com/387249/148833149-2fbf649e-cb26-4d6d-9737-5961726441bf.png) | ![20126-13](https://user-images.githubusercontent.com/387249/148833150-44196aa0-69a0-4812-850c-dd9f460104bf.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.35.78 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
--|--
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Linux

Followed the testplan from https://github.com/brave/brave-core/pull/11621.

Steps:

1. Visit `https://digikey.com` and confirm that a cookie notice is shown. It will appear either as a banner at the top, or as a popup along the bottom depending on window size.
2. Visit `brave://flags` and enable the `#brave-adblock-cookie-list-default` flag, then restart the browser.
3. Visit `https://digikey.com` and confirm that no cookie notice is shown.
4. Visit `brave://adblock` and confirm that the entry for `Easylist-Cookie List - Filter Obtrusive Cookie Notices` under `Additional filters` exists and is checked.
5. Return to `brave://flags` and set `#brave-adblock-cookie-list-default` to `Disabled`, and restart the browser.
6. Visit `https://digikey.com` and confirm that the cookie notice is shown again.
7. Visit `brave://adblock` and confirm that the entry for `Easylist-Cookie List - Filter Obtrusive Cookie Notices` is no longer checked.
8. Manually toggle the `Easylist-Cookie List - Filter Obtrusive Cookie Notices` entry to be `enabled`, then repeat steps 2-5.
9. Visit `brave://adblock` and confirm that the entry for `Easylist-Cookie List - Filter Obtrusive Cookie Notices` is checked.
10. Manually toggle the `Easylist-Cookie List - Filter Obtrusive Cookie Notices` entry to be `disabled`.
11. Visit `brave://flags` and `enable` the `#brave-adblock-cookie-list-default` flag, then restart the browser.
12. Visit `brave://adblock` and confirm that the entry for `Easylist-Cookie List - Filter Obtrusive Cookie Notices` is `unchecked`.
13. Visit `https://digikey.com` and confirm that the cookie notice is shown.

step1 | step 2 | step 3 | step 4 | step 5 | step 6 | step 7
-------|--------|--------|--------|--------|--------|--------
<img width="1200" alt="Screen Shot 2022-01-10 at 12 34 33 PM" src="https://user-images.githubusercontent.com/387249/148836082-8059c6b2-d06e-4635-9b0c-2908601d28c9.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 35 08 PM" src="https://user-images.githubusercontent.com/387249/148836088-bb968d39-d843-44d9-9977-009c54d9278f.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 35 19 PM" src="https://user-images.githubusercontent.com/387249/148836097-84947e89-01fa-46a1-a301-1f6603c99585.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 35 29 PM" src="https://user-images.githubusercontent.com/387249/148836104-b479ef07-3ea2-4cc9-afcb-24270ff207b8.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 35 55 PM" src="https://user-images.githubusercontent.com/387249/148836107-497a10e8-ca7c-4895-8681-e2d20b4ef844.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 36 01 PM" src="https://user-images.githubusercontent.com/387249/148836110-744a4912-3dbf-4bed-bdd5-f8bcfe23b79e.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 36 14 PM" src="https://user-images.githubusercontent.com/387249/148836114-28d5d310-61d2-410b-89cb-5fb0bfc3f9e5.png">




step 9 | step 10 | step 11 | step 12 | step 13
----------|---------|---------|----------|---------
<img width="1200" alt="Screen Shot 2022-01-10 at 12 36 25 PM" src="https://user-images.githubusercontent.com/387249/148836255-66a929ff-01e1-4941-9bbe-7a4fcbd18738.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 36 58 PM" src="https://user-images.githubusercontent.com/387249/148836259-37a330e0-2be9-4505-b1af-78bd565a9d34.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 37 26 PM" src="https://user-images.githubusercontent.com/387249/148836264-e87266c2-3332-48f1-8b11-5a31951edea3.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 37 48 PM" src="https://user-images.githubusercontent.com/387249/148836266-92e18740-86ac-4f86-8681-d61d7ba21107.png"> | <img width="1200" alt="Screen Shot 2022-01-10 at 12 37 54 PM" src="https://user-images.githubusercontent.com/387249/148836268-ba26c691-7227-490a-9bce-b1bef2fec2e6.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.93 x64 Beta build
- Verified steps from [brave/brave-core#11621](https://github.com/brave/brave-core/pull/11621)
- Verified enabling `#brave-adblock-cookie-list-default` flag auto enables the settings in filter list in `brave://adblock`
- Verified when flag is enabled cookie consent notification is blocked 
- Verified `Easylist-Cookie List - Filter Obtrusive Cookie Notices` being disabled manually shows the cookie consent notification
- Verified setting the #brave-adblock-cookie-list-default` flag to disable shows the cookie consent notification

Default | Flag Enabled | No consent with flag enabled | Easy list enabled with flag | Notice with flag/Easylist diasbled | Easy list manual toggle | Notice removed with flag enabled
-- | -- | -- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/151390876-41612174-bb41-4e73-a95e-cce892a0c8c6.png) | ![image](https://user-images.githubusercontent.com/17010094/151390696-d7ec620c-e98c-4f69-a595-af8fae719141.png) | ![image](https://user-images.githubusercontent.com/17010094/151390666-d596b1e1-9b61-4ca5-b005-c19f91dfb7a3.png) | ![image](https://user-images.githubusercontent.com/17010094/151390720-bfaa6bbd-bdcc-4356-8ada-7f26d35773c9.png) | ![image](https://user-images.githubusercontent.com/17010094/151390749-c25f29ff-aaf5-4ded-bb38-cf5461163765.png) | ![image](https://user-images.githubusercontent.com/17010094/151390767-f7bb666a-5ed0-48ed-8599-c4df145aa550.png) | ![image](https://user-images.githubusercontent.com/17010094/151390781-d37af325-293f-421b-9b4f-0ea688b37e20.png)
