### ISSUE TITLE
Use same rounding logic between Rewards panels and Ads panel

### ISSUE THREAD

**Issue by dodieboy** [brave/brave-browser#20128]
## Description 

The estimated earning found earning found in brave://rewards/ show to different value. Most likely cause by the different rounding off method use

## Actual result:
![image](https://user-images.githubusercontent.com/9015764/146333537-538937a2-ac10-43c0-89e9-539bc8bd6f45.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 21H2 (Build 19044.1348)

**Comment by zenparsing** [comment]
Note that floating point rounding can differ between `Intl.NumberFormat` and `Number.prototype.toFixed`. (See examples at [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#using_tofixed).)

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.47 Chromium: 97.0.4692.71 (Official Build) nightly (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:

1. new profile
2. clicked on `Skip welcome tour`
3. clicked on `Start using Rewards`
4. changed `5 ads per hour` to `10 ads per hour` on `brave://rewards/`
5. waited for 1st ad
6. opened `brave://rewards`
7. checked that the `Current earnings this month (estimated)` and `Estimated Earnings` match up
8. repeated steps 5-7 for ads 2-15

Confirmed that both `estimated earnings` numbers matched and are rounded

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
-|---|---|---|---|--|---|---
<img width="1312" alt="Screen Shot 2022-01-19 at 12 13 06 PM" src="https://user-images.githubusercontent.com/387249/150219455-5a0e7647-1ca5-493a-ba00-a82851a23049.png"> | <img width="1312" alt="Screen Shot 2022-01-19 at 12 19 32 PM" src="https://user-images.githubusercontent.com/387249/150219557-fb4676e2-f472-4e1e-be03-9e1bcb8f8e1b.png"> | <img width="1312" alt="Screen Shot 2022-01-19 at 12 20 06 PM" src="https://user-images.githubusercontent.com/387249/150219562-aeb26350-cf3b-4e59-b22c-239ab8dad81c.png"> | <img width="1312" alt="Screen Shot 2022-01-19 at 12 20 42 PM" src="https://user-images.githubusercontent.com/387249/150219569-cc04f808-d63a-44dd-8656-6058f8226fdb.png"> | <img width="1312" alt="Screen Shot 2022-01-19 at 12 25 44 PM" src="https://user-images.githubusercontent.com/387249/150219572-18149849-2592-48c2-952b-03cbd9214d45.png"> | <img width="1399" alt="Screen Shot 2022-01-19 at 12 33 09 PM" src="https://user-images.githubusercontent.com/387249/150219574-5543ced2-5f1e-4357-b38e-531c5419c36f.png"> | <img width="1399" alt="Screen Shot 2022-01-19 at 12 39 31 PM" src="https://user-images.githubusercontent.com/387249/150219577-8897863c-2207-48a5-a33a-fa0aee66469b.png"> | <img width="1399" alt="Screen Shot 2022-01-19 at 12 48 12 PM" src="https://user-images.githubusercontent.com/387249/150219579-793944e7-1fe1-47a5-9357-d51293e20aa4.png">




9 | 10 | 11 | 12 | 13 | 14 | 15
--|---|---|---|---|---|---
<img width="1399" alt="Screen Shot 2022-01-19 at 12 54 25 PM" src="https://user-images.githubusercontent.com/387249/150219680-9bb99e17-74ab-4e98-9b3a-26aaefc98d4c.png"> | <img width="1399" alt="Screen Shot 2022-01-19 at 1 01 22 PM" src="https://user-images.githubusercontent.com/387249/150219371-6a9ffd4e-5706-48c2-bd0e-0fefafb8e1d5.png"> | <img width="1399" alt="Screen Shot 2022-01-19 at 1 16 57 PM" src="https://user-images.githubusercontent.com/387249/150220075-86c48e79-0956-4ad4-a985-f3ab8368b39b.png"> | <img width="1399" alt="Screen Shot 2022-01-19 at 1 19 17 PM" src="https://user-images.githubusercontent.com/387249/150220085-8b1100cb-87d8-419a-86f8-bca3cd06bed0.png"> | <img width="1442" alt="Screen Shot 2022-01-19 at 1 25 34 PM" src="https://user-images.githubusercontent.com/387249/150220090-1cb7ae0d-091f-4793-ac73-5fa4df3f7ac1.png"> | <img width="1442" alt="Screen Shot 2022-01-19 at 1 31 51 PM" src="https://user-images.githubusercontent.com/387249/150220094-0a77419d-5a1f-4b83-828b-e98642309539.png"> | <img width="1442" alt="Screen Shot 2022-01-19 at 1 38 08 PM" src="https://user-images.githubusercontent.com/387249/150220095-73e0b881-0e0b-40bc-8714-79984987f7da.png"> | <img width="1442" alt="Screen Shot 2022-01-19 at 1 44 15 PM" src="https://user-images.githubusercontent.com/387249/150220099-381f1b1b-c0e7-4165-988e-5ae30c2f5bd6.png">
