### ISSUE TITLE
Make Brave News peek up from bottom of NTP

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#20129]
Many users who have opted in to Brave News forget that it's there. The "Scroll for Brave News" button on desktop NTP is insufficient. Mobile users see the top card peaking up from the bottom of the NTP. 

Desktop should match mobile and show the top card peaking up from the bottom of the NTP.

**Comment by LaurenWags** [comment]
@brave/qa-team please pay attention to performance (especially NTP load time) when checking this issue.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.40.83 Chromium: 102.0.5005.78 (Official Build) beta (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

### Case One: general `peeking` animation - PASSED
<details>

#### Steps:
1. new profile
2. launch Brave
3. click on `Skip welcome tour`
4. scroll down
5. click on `Show Brave News`
6. open a new tab
7. observe the `peeking` animation for `Scroll Brave News`

Confirmed
* `Scroll for Brave News` appears and is animated for about 2 seconds duration (4 seconds from new-tab to animation end, beginning 2 seconds after new-tab load finishes)
* if interacted with before it animates, no animation occurs
* I can scroll up and down, in both opted-out and opted-in cases, without additional jank

opted-out (default) | opted-in
--------------------|---------
(screencast) | (screencast)

</details>

### Case Two: network request for feed only on/after `peeking` - PASSED
<details>

#### Steps:
1. launch Charles Proxy or similar tool, and start monitoring traffic
2. new profile
3. launch Brave
4. click on `Skip welcome tour`
5. scroll down on the new-tab page (confirm no network requests)
6. click on `Show Brave News`
7. (there will be lots of initial network requests, might want to let them "settle")
8. clear Charles Proxy output
9. restart Brave
10. watch Charles Proxy output while the `Scroll for Brave News` animation cycles
11. confirm there's a request for `feed.json` from `https://brave-today-cdn.brave.com/brave-today/feed.json`

</details>

### Case Three: "back" navigation restores article's viewport position - PASSED
<details>

#### Steps:
1. new profile
2. launch Brave
3. click on `Skip welcome tour`
4. scroll down
5. click on `Show Brave News`
6. click on any article
7. confirm the article loads in the current tab/window
click the `Back` button `<`
8. confirm you are restored to the same scrolled viewport position

</details>

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.40.87 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)

```

### Case One: general `peeking` animation - `PASSED`
<details>

1. Install 1.40.87 
2. Launch Brave
3. Click on Skip welcome tour
4. Verified `Scroll for Brave News` appears and is animated for about 4 seconds duration
5. scroll down
6. click on Show Brave News
7. open a new tab
8. observe the peeking animation for Scroll Brave News
9. Verified the duration from NTP to animation end was 4 seconds
10. Also confirmed  if interacted before animates, no animation occurred.
11. Content is fetched after Opt-in as expected
12. After scrolling down past the first card, first ad card rendered in the  NTP
13. Able to scroll up and down, in both opted-out and opted-in cases, without additional jank

Default|opt-in|Step 12
-----|-----|-----
<img width="850" alt="default" src="https://user-images.githubusercontent.com/98358127/172441965-f98c319e-b65d-478f-aae6-396fc92c4e85.gif">|<img width="850" alt="opt-in" src="https://user-images.githubusercontent.com/98358127/172445730-3bf7087e-059a-4f66-b0d7-f090633abe99.gif">|<img width="850" alt="image" src="https://user-images.githubusercontent.com/98358127/172449215-887af351-fe95-4e40-b4bf-20bf73ea8f05.png">

</details>

### Case Two: network request for feed only on/after `peeking` - `PASSED`
<details>

#### Steps:
1. launch Charles Proxy or similar tool, and start monitoring traffic
2. new profile
3. launch Brave
4. click on `Skip welcome tour`
5. scroll down on the new-tab page (confirm no network requests)
6. click on `Show Brave News`
7. (there will be lots of initial network requests, might want to let them "settle")
8. clear Charles Proxy output
9. restart Brave
10. watch Charles Proxy output while the `Scroll for Brave News` animation cycles
11. confirm there's a request for `feed.json` from `https://brave-today-cdn.brave.com/brave-today/feed.json`

Step 7|Step 8| Step 11
----|----|----
<img width="935" alt="Step7" src="https://user-images.githubusercontent.com/98358127/172446282-65eff395-3749-494d-81c4-e1910617fc71.png">|<img width="935" alt="Step 8" src="https://user-images.githubusercontent.com/98358127/172446449-83051526-4d76-4c0b-8428-4f143e6dbd72.png">|<img width="935" alt="image" src="https://user-images.githubusercontent.com/98358127/172446508-dad9ba1c-8b0a-4a5e-893a-c7dda150e087.png">

</details>

### Case Three: "back" navigation restores article's viewport position - `FAILED`
<details>

#### Steps:
1. new profile
2. launch Brave
3. click on `Skip welcome tour`
4. scroll down
5. click on `Show Brave News`
6. click on any article
7. confirm the article loads in the current tab/window
click the `Back` button `<`
8. confirm you are restored to the same scrolled viewport position


initial viewport | article loaded | viewport position after being restored
-----|-----|-----
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/172448338-94e49660-e919-42cc-bf43-301d3e3a59fc.png">|<img width="947" alt="image2" src="https://user-images.githubusercontent.com/98358127/172448429-3f407cb8-5b45-4386-a5e8-4abc49650ea9.png">|<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/172448580-c51fb4fa-a716-4928-95a5-5d87a25f5154.png">

Reproduced the bug: 
* https://github.com/brave/brave-browser/issues/23244

</details>

### Case Four: multiple new-tab performance - `PASSED`

<details>

Memory/performance:
* per @matuchin: no noted perf regressions/changes relating to `1.40.43`, when this first landed

#### Scenario One: opted-out of Brave News (default) - `PASSED`
<details>

#### Steps:
1. new profile
2. launch Brave
3. open the Developer Tools
4. click on `Performance`
5. click on `Start profiling and reload page`
6. click on `Skip welcome tour`
7. wait for it to finish running
8. look at the results for the following: `DOM Content Loaded` (`DCL`), `First-Contenful Paint` (`FCP`), and `Largest-Contentful Paint` (`LCP`)

Repeat the above 3x.

All times in milliseconds; `medians`, **(means)**


|    Opted-out     | `DCL`  | `FCP` | `LCP` |
|---------|-----|-----|-----|
|`1.39.111`| 93.8, 91.2,95.8 **(93.6 )** |211.5,222.0,211.2 **(214.9 )** |211.5,222.0,211.2 **(214.9)**
| `1.40.83` |95.5.2,96.0,94.0 **(95.1)** |163.0,193.9,216.2 **(191.3)**|163.0, 193.9,216.2  **(191.03)**                                     |


</details>

#### Scenario Two: opted-in to Brave News - `PASSED`
<details>

#### Steps:
1. new profile
2. launch Brave
3. click on `Skip welcome tour`
4. scroll down
5. click on `Show Brave News`
6. wait for it to load/render
7. scroll back up to the top of Brave News
8. open the Developer Tools
9. click on `Performance`
10. click on `Start profiling and reload page`
11. wait for it to finish running
12. look at the results for the following:  `DOM Content Loaded` (`DCL`), `First-Contenful Paint` (`FCP`), and `Largest-Contentful Paint` (`LCP`)

Repeat the above 3x.

All times in milliseconds; `medians`, **(means)**

|   Opted-in     | `DCL`  | `FCP` | `LCP` |
|---------|-----|-----|-----|
|`1.39.111`| 112.4, 111.7, 122.8 **(115.6)**|204.0. 204.60, 227.7 **(212.10)**|287.5, 304.9, 294.6 **(295.67)**
| `1.40.83` | 100,1,117.0,119.5 **(112.2)**|175.3,180.9, 183.5 **(179.9)**|175.3, 197.6, 183.5 **(185.47)**

</details>

</details>

### Case Five: upgrade from 1.39.111, `Show Brave News` enabled - `PASSED`
<details>

#### Steps:
1. install `1.39.111`
2. launch Brave
3. click `Skip welcome tour`
4. scroll down
5. click on `Show Brave News`
6. wait for it to complete loading/rendering
7. shut down Brave
8. update to `1.40.83`
9. observe the `peeking` animation for `Scroll Brave News`

#### Confirmed:
* no `Show Brave News` / `No thanks` opt-in dialog
* `Scroll for Brave News` appears and is animated for about 2 seconds duration (4 seconds from new-tab to animation end, beginning 2 seconds after new-tab load finishes)
* if interacted with before it animates, no animation occurs
* I can scroll up and down, in both opted-out and opted-in cases, without additional jank


`1.39.111` | `1.40.80`
---------|---------
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/172486394-8ccea531-3855-466c-897d-cdbc30a3dbf3.png">|<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/172486365-7a2fda12-8502-4208-944f-18bfee5ed002.png">
</details>

### Case Six: With the feature flag `#brave-news-peek`  `OFF` in brave://flags - `PASSED`
<details>

#### Steps:
1. new profile
2. launch Brave
3. Disable `#brave-news-peek` flag in brave://flags
4. Relaunch Browser
5. Verified 'Scroll for Brave News` doesn't peek and no animation available
6. Scroll down and content loaded as expected

Step 3|Step 5|Step 7
---|---|---
<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/172487921-8eb20a9b-49cb-4aa9-a577-be4cb514a1e8.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/172487952-06c49700-bb83-434d-a43d-b9032e87a1d2.png">|<
<img width="946" alt="image" src="https://user-images.githubusercontent.com/98358127/172487888-93ece402-4640-4d79-99fb-fa558198f027.png">

</details>
