### ISSUE TITLE
Remove `navigator.connection` from Brave-core

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#20122]
Chromium allows sites to learn about local network conditions by querying `navigator.connection`. This is privacy harming information. It can be used by fingerprinters, as well as by more determined attackers to potentially learn about user traveling patterns (including when the user is at home or not).

Ideal behavior here would be for the below to both be true in all shields configurations:

`navigator.connection === undefined`
`"connection" in window.navigator === false`

An ideal implementation would also include a brave://flags option (default off) that advanced users could use to re-enable the API. The flag description should have text mentioning that the functionality risks their privacy.

**Comment by mkarolin** [comment]
Test Plan:

1. Open Brave and navigate to any site.
2. Open DevTools and go to the Console tab
3. Enter: `"connection" in window.navigator`
Expected result: false

4. Navigate to brave://flags
5. Locate `navigator-connection-attribute` flag, enable it, and click restart
6. Repeat steps 1-3
Expected result: true

**Comment by pes10k** [comment]
For QA, i've also added a test for this in the QA suite: https://dev-pages.brave.software/dom-properties.html

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.69 Chromium: 97.0.4692.56 (Official Build) dev (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)

Followed the steps above.

Steps:
1. opened Brave and navigated to a site (`wired.com`)
2. opened DevTools and went to the Console tab
3. entered: `"connection" in window.navigator`
4. confirmed the expected result: `false`
5. navigated to `brave://flags`
6. located `navigator-connection-attribute` flag, enabled it, and clicked `restart`
7. repeated steps 1-3
8. confirmed the expected result: `true`

example | example | example
---------|----------|---------
<img width="864" alt="Screen Shot 2021-12-30 at 2 17 14 PM" src="https://user-images.githubusercontent.com/387249/147791667-c1d0722f-5478-4e2f-8735-602475c546da.png"> | <img width="864" alt="Screen Shot 2021-12-30 at 2 17 43 PM" src="https://user-images.githubusercontent.com/387249/147791673-2286baf7-e7bc-47ac-9598-dcf27d56af04.png"> | <img width="864" alt="Screen Shot 2021-12-30 at 2 18 06 PM" src="https://user-images.githubusercontent.com/387249/147791675-425350bc-dc3d-405e-a2e9-4a77f6ba1439.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.74, Chromium 97.0.4692.71` on a Google Pixel XL running Android 9.0.

Steps:

1. opened Brave and navigated to a site (`wired.com`)
2. opened DevTools and went to the Console tab
3. entered: `"connection" in window.navigator`
4. confirmed the expected result: `false`
5. navigated to `brave://flags`
6. located `navigator-connection-attribute` flag, enabled it, and clicked `Relaunch`
7. repeated steps 1-3
8. confirmed the expected result: `true`

example | example | example
---------|---------|---------
<img width="752" alt="Screen Shot 2022-01-05 at 4 26 22 PM" src="https://user-images.githubusercontent.com/387249/148309178-6a2e27dd-d54c-46c5-a68b-a33b63667fa5.png"> | <img width="752" alt="Screen Shot 2022-01-05 at 4 31 43 PM" src="https://user-images.githubusercontent.com/387249/148309219-adbb6e1e-4d33-4651-96aa-5021d661394c.png"> | <img width="752" alt="Screen Shot 2022-01-05 at 4 29 28 PM" src="https://user-images.githubusercontent.com/387249/148309237-463f5866-40d8-4114-9620-6abd34c9df76.png">

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.77 x64 Beta build
- Verified steps from https://github.com/brave/brave-browser/issues/20122#issuecomment-1001720661 & https://github.com/brave/brave-browser/issues/20122#issuecomment-1001774779


![image](https://user-images.githubusercontent.com/17010094/148733822-dace2c4b-1f77-4755-8f38-9770ae5e366b.png) | ![image](https://user-images.githubusercontent.com/17010094/148734731-3399a6ce-28d1-4fd6-bee8-de250ee38d72.png) | ![image](https://user-images.githubusercontent.com/17010094/148734857-2a2babbc-fb2e-4b09-979b-fd3f8e1a5019.png) | ![image](https://user-images.githubusercontent.com/17010094/148734893-bfb2ac5e-44bc-4f7c-b556-9718a4b6080d.png) | ![image](https://user-images.githubusercontent.com/17010094/148734878-b9c1d36a-0db8-4ab5-a4ad-4e75aacc64a6.png)
-- | -- | -- | -- | --
