### ISSUE TITLE
Make Verify Sorted Box Bigger for 24 Word Recovery Phrases

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20125]
## Description 
1) Make the Verify Sorted Box Bigger if Recovery Phrase is 24 words
2) Change the text in the first backup step to say `24` if Recovery Phrase is 24 words

![Screen Shot 2021-12-15 at 5 49 41 PM](https://user-images.githubusercontent.com/40611140/146287975-0c00be39-6311-40b8-9146-ebe1f7f4b8ab.png)

![Screen Shot 2021-12-15 at 5 58 09 PM](https://user-images.githubusercontent.com/40611140/146289220-3cebf23a-02fc-458d-891f-3b9ccda88df1.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.89 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11630>brave/brave-core#11630</a></li>
         <li>Verified welcome message is updated based on the number of seed words in the wallet</li>
         <li>Verified input box for seed words is adjusted based on the input seed words(12/15/24)</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>24-word Welcome message
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150821781-e3b8940a-0a4b-4184-b900-f0c672563622.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/150822551-5afb59be-0e13-448c-a9a7-bd182e1e2bb2.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/150821296-37de9a8e-4e0b-466a-b15d-d4160aeea0f4.png>
      </td>
   </tr>
   <tr>
      <td>24-word Seed phrase Backup
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150821381-ad89b492-499b-460c-ae6b-2aafcfb344ca.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/150822934-9421a002-4bbe-4016-ad72-dd384b3389e6.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/150821363-16d8a469-672e-4d3b-bcd6-853c955532d5.png>
      </td>
   </tr>
   <tr>
      <td>12-word Welcome Message
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150821829-d9115930-1564-4d3d-81c7-0cd7ccda861b.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/150822307-5b4253fa-384c-4504-a464-3ab25372bc57.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/150821310-e47be69c-d367-4fb2-96bd-9b5de759a2ce.png>
      </td>
   </tr>
   <tr>
      <td>12-word Seed Phrase Backup
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150821896-6f241510-f94d-48cc-b6c6-03b7ddbf9b23.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/150823240-2666690a-cf54-4f55-8e54-cd0657873fbe.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/150821334-7c1d53a7-99ea-48ec-be4e-50b93db1e651.png>
      </td>
   </tr>
</table>
