### ISSUE TITLE
[Android] Make Rewards panel 2.0 more closely match design spec

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20137]
## Description

See design files. 

Use Poppins font inside the Rewards panel. 

Increase width of the panel if needed for most common larger screen sizes to better accommodate design. 

Make sure error notifications in Rewards panel have correct assets and text.

## Version

As of v1.35 with the first merge of the new Rewards panel.

**Comment by LaurenWags** [comment]
@Miyayes will this issue cover this padding issue as noticed by @srirambv?

![Screenshot_20211218-200201](https://user-images.githubusercontent.com/28145373/146772147-c9522170-a1ac-4ec2-a59c-38b87215515d.png)

**Comment by Miyayes** [comment]
> @Miyayes will this issue cover this padding issue as noticed by @srirambv?

I don't believe so as this PR is mainly for the Rewards dropdown panel and not for the settings page.

**Comment by deeppandya** [comment]
> @Miyayes will this issue cover this padding issue as noticed by @srirambv?
> 
> ![Screenshot_20211218-200201](https://user-images.githubusercontent.com/28145373/146772147-c9522170-a1ac-4ec2-a59c-38b87215515d.png)
> 
> 

@LaurenWags this should be fixed from the react pages. The PR is for panel changes.

**Comment by LaurenWags** [comment]
great, thanks @Miyayes. Logged https://github.com/brave/brave-browser/issues/20173 for this to be handled separately.

**Comment by LaurenWags** [comment]
Verification passed on Google Pixel 3 XL with Android 12 running various 1.35.x versions.
* Per discussion with @Miyayes this issue has been covered under multiple issues, no additional specific checks remain.
