### ISSUE TITLE
Auto-populate token details when adding custom asset on Android

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#20139]
Similar to that issue on desktop https://github.com/brave/brave-browser/issues/18704

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36.89 x64 Beta build
- Verified entering a token contract address auto-populates the token details
- Encountered [#21599](https://github.com/brave/brave-browser/issues/21599)

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/157827469-c3a06ce4-bc00-42f7-9c05-62d204b3f6e3.mp4> | <video src=https://user-images.githubusercontent.com/17010094/157827675-bcde0f48-696e-450d-aff4-66e8b2bbf76d.mp4>
