### ISSUE TITLE
[Android] Fix and generalize creator verification status detection in Rewards panel 2.0 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20136]
## Description

If the creator is verified in any capacity (_regardless of whether the creator's custodian matches the user's custodian_), then it should show a blue checkmark and say "Verified creator".

For now, any notices about whether the tip can actually be made will appear in the tipping banner, per: https://github.com/brave/brave-browser/issues/20135

**Comment by LaurenWags** [comment]
Verification in progress with `1.35.87 Chromium: 97.0.4692.71 (Official Build) beta` on Pixel 3 XL with Android 11.

See testing notes under https://github.com/brave/brave-browser/issues/20232#issuecomment-1015473342.
