### ISSUE TITLE
Add an extra validation of ETH address

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#20132]
Create a validation the same way as desktop did https://github.com/brave/brave-browser/issues/19532

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.36.85 x64 Beta build
- Verified steps from [brave/brave-core#11607](https://github.com/brave/brave-core/pull/11607)
- Verified error is shown when an invalid ETH addres is entered
- Verified error is shown when an address has missing checksum
- Verified error is shown when an address has invalid checksum 
- Encountered [#20930](https://github.com/brave/brave-browser/issues/20930)

Not a valid ETH  | Invalid checksum |  Missing checksum
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/152772670-361e0912-a1bf-4147-8b82-595a6e350b06.png) | ![image](https://user-images.githubusercontent.com/17010094/152772701-abf43478-c9dd-4449-a530-c50aee64b726.png) | ![image](https://user-images.githubusercontent.com/17010094/152772738-f630f1b8-6310-4779-b06a-86deb296ce31.png)

--------------
Verification passed on Samsung Tab A  with Android 10 running 1.36.85 x64 Beta build
- Verified steps from [brave/brave-core#11607](https://github.com/brave/brave-core/pull/11607)
- Verified error is shown when an invalid ETH addres is entered
- Verified error is shown when an address has missing checksum
- Verified error is shown when an address has invalid checksum 
- Encountered [#20930](https://github.com/brave/brave-browser/issues/20930)

Not a valid ETH  | Invalid checksum |  Missing checksum
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/152772819-535a2d9a-af2a-4d71-89f8-fcf5b6205db6.png) | ![image](https://user-images.githubusercontent.com/17010094/152772838-bf4e6971-cdcf-449d-a26c-c6ef49efb870.png) | ![image](https://user-images.githubusercontent.com/17010094/152772850-cfb5fbee-4823-44ab-aa41-bae1f671990b.png)
