### ISSUE TITLE
Unblinded tokens refill is not scheduled after captcha is solved

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#20131]
User may not be paid for viewing ads even after solving the captcha.
User needs to restart the browser to trigger unblinded tokens refill

## Steps to Reproduce

1. Clean profile
1. Run Brave
1. Enable Rewards and Ads
1. Schedule a captcha for your payment ID
1. Trigger unblinded tokens refill
1. Solve captcha

## Actual result:

unblinded tokens refill is not scheduled after captcha is solved

Note: unblinded tokens refill is triggered after browser restart

## Expected result:
unblinded tokens refill is scheduled after captcha is solved

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Ubuntu 18.04 LTS

cc @emerick @tmancey @jsecretan @brave/legacy_qa

**Comment by emerick** [comment]
Spoke with @tmancey and he suggested that we add a `OnDidCompleteCaptcha` callback to `RefillUnblindedTokensDelegate` which `RefillUnblindedTokens` will call at the appropriate time to refill tokens (via `TopUpUnblindedTokens`).

**Comment by tmancey** [comment]
@Miyayes this is still an issue and ideally does need resolving, thanks

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.53.99 Chromium: 114.0.5735.133 (Official Build) beta (64-bit) 
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/18460

<details>

Verified unblinded tokens refill is scheduled after captcha is solved



</details>
