### ISSUE TITLE
[Android] Fix tipping notice logic in tipping banner

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20135]
## Description

There are two types of notices, each with different text:

1. **Unverified notice:** when the creator is not verified whatsoever 
2. **Configuration notice:** when the creator is verified, _but there is no available tipping path between the user and this creator._

**Unverified notice** text:

>**NOTE:** This creator is not signed up yet. Any tip you make will remain pending in your wallet and retry automatically for 90 days. Learn more.

![image](https://user-images.githubusercontent.com/11497541/146976310-32dd2846-5d27-4daa-93ec-7b0d0e85beef.png)

**Configuration notice** text:

>**NOTE:** This creator is currently not configured to receive tips from your wallet. Any tip you make will remain pending in your wallet and retry automatically for 90 days. Learn more.

Learn more links out to: https://brave.com/faq/#unclaimed-funds

![image](https://user-images.githubusercontent.com/11497541/146976159-722a492f-b29b-4080-a918-6a433dca1a11.png)

### Unverified user case

**1. Goes to unverified creator:** show unverified notice
**2. Goes to verified creator:** do not show any notice

### Verified user case

**1. Goes to unverified creator:** show unverified notice
**2. Goes to verified creator _who has a different custodian than the user has_:** show configuration notice
**3. Goes to verified creator _who has no custodian_:** show configuration notice
**4. Goes to verified creator who has the same custodian:** do not show any notice

**Comment by LaurenWags** [comment]
Verification in progress with `1.35.87 Chromium: 97.0.4692.71 (Official Build) beta` on Pixel 3 XL with Android 11.

See testing notes under https://github.com/brave/brave-browser/issues/20232#issuecomment-1015473342.
