### ISSUE TITLE
Crash Report on brave://rewards

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#20147]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.35.36  Chromium: 97.0.4692.45
Operating System: Linux 5.11.0-41-generic

URL (if applicable) where crash occurred:
brave://rewards

Can you reproduce this crash?
yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. open brave://rewards
2. click `Show 30-day Ads History` 
3. click `Heart` button in the Category column

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/9f620200-f24d-7007-0000-000000000000

**Comment by iefremov** [comment]
https://brave.sp.backtrace.io/p/brave/debug?time=month&filters=((callstack.functions%2Ccontains%2CToggleAdOptIn)%2Cver%3E%3D%2292%22%2Cptype%3Dbrowser)&debug=(%222d4c85c%22,0,0)
```
[ 00 ] gsignal
[ 01 ] absl::variant_internal::ThrowBadVariantAccess()
[ 02 ] absl::optional<ThreadProfilerConfiguration::VariationGroup> const& absl::variant_internal::TypedThrowBadVariantAccess<absl::optional<ThreadProfilerConfiguration::VariationGroup> const&>()
[ 03 ] base::Value::GetInt() const
[ 04 ] (anonymous namespace)::RewardsDOMHandler::ToggleAdOptIn(base::CheckedContiguousRange<std::__1::vector<base::Value, std::__1::allocator<base::Value> > const>)
[ 05 ] content::WebUIImpl::ProcessWebUIMessage(GURL const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, base::ListValue const&)
[ 06 ] content::WebUIImpl::Send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, base::Value)
[ 07 ] content::mojom::WebUIHostStubDispatch::Accept(content::mojom::WebUIHost*, mojo::Message*)
[ 08 ] mojo::InterfaceEndpointClient::HandleIncomingMessageThunk::Accept(mojo::Message*)
[ 09 ] mojo::MessageDispatcher::Accept(mojo::Message*)
[ 10 ] mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*)

```

**Comment by iefremov** [comment]
should be super simple, @bsclifton @zenparsing can take a look?

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.35.69 Chromium: 97.0.4692.56 (Official Build) dev (64-bit)
--|--
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Linux

Steps:

1. new profile
2. launched Brave
3. opened `brave://rewards`
4. enabled Rewards
5. viewed a few new-tab page ads + 1 system-notification ad
6. clicked `Show 30-day Ads History`
7. clicked ❤️  button in the `Category` column

Confirmed no crash; repeated several times.

<img width="1140" alt="Screen Shot 2021-12-30 at 3 35 16 PM" src="https://user-images.githubusercontent.com/387249/147794586-a07baecf-789c-44f1-a112-6680849a4ca3.png">
