### ISSUE TITLE
Stats not imported during auto-upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2014]
## Description 

Found while testing #1545, stats not imported during auto-upgrade

## Steps to Reproduce

   1. Create a browser profile on muon with nice stats
   2. Install b-c release version and launch with `--upgrade-from-muon`
   3. Stats not imported. Bookmarks/History/Passwords are imported

## Actual result:

Stats not imported during auto-upgrade

## Expected result:
Should import stats as well on auto-upgrade

## Reproduces how often: 

Easy

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Reproduced by @kjozwiak @LaurenWags on macOS

**Comment by btlechowski** [comment]
Reproduced on Windows 7 x64

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows 7 x64

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.56.14 Chromium: 70.0.3538.102 (Official Build) (64-bit)
-- | --
Revision | 4bbeebac88fdc09c97265e47c205868bbd190497-refs/branch-heads/3538@{#1077}
OS | Windows
