### ISSUE TITLE
QR Code and Code Words headings are clipped on Sync-setup screen

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20140]
## Description 
QR Code and Code Words headings are clipped on Sync-setup screen

## Steps to reproduce 

   1. install `1.35.40`
   2. tap on the 3-dots menu on the bottom toolbar
   3. tap `Settings`
   4. tap `Sync`
   5. tap `Start a new sync chain`
   6. tap `Add a Mobile Device`
   7. look at the `QR Code` and `Code Words` headings

## Actual vs. Expected Results:

They are clipped

`1.35.40` |  `release`
----------|-------
![Screenshot_20211216-110526](https://user-images.githubusercontent.com/387249/146433497-5bccd15e-f1ff-4e37-bdcc-ee9f39d45982.png) | ![Screenshot_20211216-110554](https://user-images.githubusercontent.com/387249/146433474-20853f90-e8a0-4cb3-9b39-c540218914ef.png)

## Issue reproduces how often 
100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): Google Pixel XL phone
   - Android version: 9.0
   
## Brave version

`1.35.40, Chromium 97.0.4692.45`

cc @mkarolin @samartnik

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.47, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.0.

Confirmed, using my original steps, above, that the headings are no longer cropped.

`QR Code` | `Code Words`
------------|---------------
![Screenshot_20211220-152719](https://user-images.githubusercontent.com/387249/146846310-e9778ffd-2690-4fb1-a8ea-a3acc5578450.png) | ![Screenshot_20211220-152938](https://user-images.githubusercontent.com/387249/146846323-b31af70b-c587-4455-bdc6-c0ff0adb5c68.png)

**Comment by stephendonner** [comment]
@samartnik @mkarolin @kjozwiak looks like we still need to uplift the fix to `1.34.x`, too?

**Comment by samartnik** [comment]
Uplift created, needs only approve https://github.com/brave/brave-core/pull/11647

**Comment by kjozwiak** [comment]
Removing the `QA/Pass` label as we'll recheck the above when checking the PR against `1.34.x`. We'll use https://github.com/brave/brave-browser/issues/20140#issuecomment-998347177 as the verification notes against Nightly for the uplift. @stephendonner verified that the fix is working so we're clear to uplift into `1.34.x` via https://github.com/brave/brave-core/pull/11647.

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.34.70, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.0.

QR Code | Code Words
----------|-------------
![Screenshot_20211222-100548](https://user-images.githubusercontent.com/387249/147136649-f3a7f8a2-3eba-4b08-9afd-57105c04ab80.png) | ![Screenshot_20211222-100558](https://user-images.githubusercontent.com/387249/147136652-4fc9f164-bbf3-4fae-b6d7-f2d2602c32e2.png)
