### ISSUE TITLE
[Android] Verify wallet modal does not open from Rewards panel if you're already on `brave://rewards/#verify`

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20141]
## Description

STR:

1. Press "Verify wallet" to open verify wallet modal from Rewards dropdown panel
2. Close the Verify wallet modal (press x)
3. Press "Verify wallet" inside the Rewards dropdown panel
4. Notice that it doesn't appear anymore

**Comment by emerick** [comment]
I investigated this issue this morning and I think I'm coming to the conclusion that the only safe way to deal with this is to have the panel launch brave://rewards/#verify in a new tab (rather than trying to navigate to it from the current tab). This is the same behavior exhibited by desktop, so it will be consistent for all platforms. If we don't do that, then the code we added to work around https://github.com/brave/brave-browser/issues/5771 doesn't work properly.

cc: @deeppandya

**Comment by Miyayes** [comment]
@emerick Opening in a new tab sounds perfect to me, especially if that means it is at parity with desktop.

**Comment by Miyayes** [comment]
Should be resolved with this PR, per Deep: https://github.com/brave/brave-core/pull/11642#discussion_r772497184

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave 1.35.68, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.

Followed the steps in the description, and confirmed I could open/close the `Verify Wallet` modal dialog at will, from `brave://rewards/#verify`.

example | example | example | example
---------|----------|---------|---------
![Screenshot_20211230-140837](https://user-images.githubusercontent.com/387249/147791192-68ab1d95-6261-4278-8505-cfddad81145e.png) | ![Screenshot_20211230-140851](https://user-images.githubusercontent.com/387249/147791204-c77a085b-df3b-4f04-bd8c-8cba9acb771c.png) | ![Screenshot_20211230-140844](https://user-images.githubusercontent.com/387249/147791248-aca380cc-a05f-44e9-9310-80ea0872d063.png) | ![Screenshot_20211230-140855](https://user-images.githubusercontent.com/387249/147791228-4a133bf9-4d64-4b65-846a-144242bae1ec.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.77 x64 Beta build
- Verified steps from issue description
- Verified the modal can be closed and reopened by clicking on the `Verify wallet` button
- Verified works on both landscape and portrait mode
- Encountered #20417

https://user-images.githubusercontent.com/17010094/148735425-c49dc5f0-d3ed-4098-b448-82b8afb674b4.mp4
