### ISSUE TITLE
[Android] Rewards panel needs higher contrast in dark theme/mode

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20145]
## Description 

Rewards panel needs higher contrast in dark theme/mode

## Steps to reproduce 

   1. install `Brave 1.35.40, Chromium 97.0.4692.45`
   2. tap through onboarding screens
   3. tap the 3-dots menu on the bottom-right corner of the toolbar
   4. tap `Settings`
   5. tap `Appearance`
   6. tap `Theme`
   7. tap on the `Dark` radio button
   8. load `brave.com`
   9. tap on the BAT icon
   10. tap `Start using Brave Rewards`
   11. tap to `Skip` the rest of the Rewards tour
   12. tap `Done`
   13. look at the resulting panel

## Actual result 

Very hard to read, due to low-contrast colors.

`nightly` | `release`
-----------|-----------
![Screenshot_20211216-164503](https://user-images.githubusercontent.com/387249/146471513-434a7d90-488b-4fb3-96a3-2f741f49740e.png) | ![Screenshot_20211216-164612](https://user-images.githubusercontent.com/387249/146471543-655b22e6-1c52-4917-b3e4-b1342c5182f3.png)

## Expected result

Easy to read.

## Issue reproduces how often 
100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`, phone
   - Android version: `9.0`
   
## Brave version
`Brave 1.35.40, Chromium 97.0.4692.45`

**Comment by Miyayes** [comment]
I think this is related to your overall work to make the Rewards panel better match the design spec @deeppandya. Related issue: https://github.com/brave/brave-browser/issues/20137

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.50, Chromium 97.0.4692.56`, on a Google Pixel XL running Android 9.0.

![Screenshot_20220203-125046](https://user-images.githubusercontent.com/387249/146996359-07750931-46ec-489c-ab17-904f9ba84420.png)
