### ISSUE TITLE
[Android] Remove "Manage your wallet" section from Android

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20153]
## Description 

Found by @stephendonner 

Remove "Manage your wallet" functionality from Android for now, re-implement at a later time as decided by @Miyayes 

## Steps to reproduce 

   1. Navigate to chrome://rewards
   2. Enable Rewards if not already enabled
   3. See "Manage your wallet" area

## Actual result 

Manage your wallet is available

## Expected result

Manage your wallet should not be available

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? n/a
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.35.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes @emerick @deeppandya

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.58, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.0.

Confirmed the `Manage your wallet` section is removed on Android in `brave://rewards`.

before fix | after fix
-----------|---------
![manage-your-wallet](https://user-images.githubusercontent.com/387249/147367612-5764f41f-45b9-4aa7-b135-1fff285532b6.png) | ![Screenshot_20211224-094646](https://user-images.githubusercontent.com/387249/147367647-684842e1-014f-4d43-bce7-f3880e59f08d.png)
