### ISSUE TITLE
Sleeping tabs. please add this from edge r

### ISSUE THREAD

**Issue by maxperkin1989** [brave/brave-browser#20157]
Please add sleeping tab from the edge browser. its literally the only thing I miss and makes such a difference performance wise

thank you

**Comment by shaunhaney** [comment]
Chrome has an experimental extension called "reduce-user-agent-request-header" that you can try out in Brave.  Go to "brave://flags" and search for "reduce" or "freeze".   This is supposed to provide the same sleeping tabs functionality as Edge. https://wccftech.com/how-to/how-to-enable-sleeping-tabs-in-google-chrome/    (Also, if you try this and it doesn't provide the desired functionality, that would be valuable information.) 

![image](https://user-images.githubusercontent.com/11708756/146696221-1509bb86-78d5-4aef-b187-a7fa63d928b1.png)

**Comment by UjCbFwtBayFM** [comment]
> Chrome has an experimental extension called "reduce-user-agent-request-header" that you can try out in Brave. Go to "brave://flags" and search for "reduce" or "freeze". This is supposed to provide the same sleeping tabs functionality as Edge. https://wccftech.com/how-to/how-to-enable-sleeping-tabs-in-google-chrome/ (Also, if you try this and it doesn't provide the desired functionality, that would be valuable information.)
> 
> ![image](https://user-images.githubusercontent.com/11708756/146696221-1509bb86-78d5-4aef-b187-a7fa63d928b1.png)

This flag has unfortunately absolutely nothing to do with sleeping tabs. 
Chrome already freeze tabs on its own since C86, but you can manually unload a tab by going to `brave://discards/` and clicking "urgent discard" on tabs you want to unload from memory.
