### ISSUE TITLE
Brave Rewards "Claim" button not working

### ISSUE THREAD

**Issue by ktapasya** [brave/brave-browser#20152]
## Description 

Hi team, I'm using brave browser on MacOS. During this month's rewards payout, I received a message in brave://rewards page "Your rewards from Ads are here!" with a claim button next to it. But nothing happens on clicking the button. No event is getting fired.

## Steps to Reproduce

   1. Link your Gemini wallet and earn BAT for 1 month successfully (Say payout happened on 10th of month M1).
   2. Now disconnect your wallet on the same month (12th of month M1).
   3. Reconnect your wallet on the start of the next month (M2) during the time where it says payouts will be processed.
   4. Now, during the time when the payouts are being processed, we get a message "Your rewards from Ads are here!" with a claim button but the button doesn't work.

## Actual result:
We get a notification "Your rewards from Ads are here!" with a claim button but the button doesn't work.

## Expected result:
Either all those rewards would be synced into the Gemini wallet automatically without any "Claim" notification or on clicking "Claim" button rewards should get synced into Gemini wallet.

## Reproduces how often: 
Has happened 1 time atleast for me.

## Brave version (brave://version info)

Brave : 1.33.106 Chromium: 96.0.4664.110 (Official Build) (arm64)
Revision : d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS : macOS Version 12.0.1 (Build 21A559)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

<img width="559" alt="Screenshot 2021-12-17 at 7 24 24 PM" src="https://user-images.githubusercontent.com/13344766/146554755-2fa2a08f-4cfb-4fa5-9587-b94870654a7a.png">

**Comment by Miyayes** [comment]
Do you by any chance have the BAT icon in your Brave Browser hidden? Go to brave://settings > Brave Rewards icon, and make sure it's visible (BAT icon in the URL bar). If you enable it, it should work. This issue is a result of this setting 9/10 times.

**Comment by ktapasya** [comment]
Amazing! Thanks @Miyayes, it worked. Is this like a known issue or something, or did I mistake claim notification for being a button? Note that it was showing a pointer type (hand like) cursor on hovering over "Claim".

**Comment by Miyayes** [comment]
Yes, it's a known issue and it is resolved in 1.34: https://github.com/brave/brave-browser/issues/19211 Thanks.
