### ISSUE TITLE
Scale cover image height on tipping banner

### ISSUE THREAD

**Issue by dlipeles** [brave/brave-browser#2015]
The cover image height on tipping banners is fixed at `176px` leading to the cover image getting chopped.

Following discussion with @NejcZdovc and @jenn-rhim , it would be a good to fix the cover image rendering on the browser.

![screen shot 2018-11-06 at 11 43 45 am](https://user-images.githubusercontent.com/4713771/48093163-a14c7f80-e1dc-11e8-83db-af9a22825aea.png)

With a scaled height the banner could achieve something like 

![screen shot 2018-11-06 at 12 21 55 pm](https://user-images.githubusercontent.com/4713771/48093200-bd502100-e1dc-11e8-992d-08a1d8633030.png)

The solution would be dynamically calculating the height of the cover to `(176/900) * width`

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-ui/pull/484
* Encountered #5870 on a smaller sized window.
custom image at ~1500px
![Screen Shot 2019-09-06 at 2 55 55 PM](https://user-images.githubusercontent.com/28145373/64454020-e6b93200-d0b7-11e9-9dba-ffddb0b53a2f.png)

custom image at ~1000px
![Screen Shot 2019-09-06 at 2 56 35 PM](https://user-images.githubusercontent.com/28145373/64454034-eae54f80-d0b7-11e9-92ac-b2922f360517.png)

standard image at ~1500px - verified image height is 176 px.
![Screen Shot 2019-09-06 at 2 57 43 PM](https://user-images.githubusercontent.com/28145373/64454050-efaa0380-d0b7-11e9-9ef5-3a02477e2c09.png)
