### ISSUE TITLE
Brave News newspaper icon is tiny

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20156]
## Description 

Brave News newspaper icon is tiny

## Steps to reproduce 

   1. install `Brave 1.35.44, Chromium 97.0.4692.56` (or later)
   2. launch Brave
   3. restart Brave (to pick up Griffin/seed-variations)
   4. open a new-tab page
   5. swipe down
   6. swipe down to see the Brave News opt-in dialog
   7. look at the size of the newspaper icon

## Actual result 

It's...tiny.

## Expected result

Should be similarly sized to iOS and desktop.

Android | iOS | desktop
---------|------|---------
![Image from iOS](https://user-images.githubusercontent.com/387249/146591741-e4a3d98f-59bf-4a5a-9a62-b9bd9ee363c5.jpg) | ![Image from iOS (4)](https://user-images.githubusercontent.com/387249/146591778-f0962e1b-aa6a-41a6-8cfa-a9ac37dd7039.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/146591801-bc03f77a-8e4b-4e7f-aa06-5deec51f1582.jpg)

## Issue reproduces how often 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`, phone
   - Android version: `9.0`
   
## Brave version
`1.35.44, Chromium 97.0.4692.56`

@mattmcalister @alexsafe @petemill

**Comment by kjozwiak** [comment]
Reproduced as well 👍 @srirambv also mentioned this a while ago. Seems like the UI/UX on Android is really small compared to iOS. Still needs some polish IMO.

**Comment by srirambv** [comment]
There's a few inconsistencies in the onboarding screen as well. 

1. iOS and Android uses a different icon compared to Desktop. 
2. The fancy dots and plus icons are not on Android but is on iOS and Desktop. 
3. Desktop says `Shows Brave News` while iOS and Android says `Turn on Brave News`

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.36.20, Chromium 97.0.4692.71` on a `Google Pixel XL` phone running `Android 9.0`.

![Screenshot_20220107-085955](https://user-images.githubusercontent.com/387249/148579620-724afa52-e080-4384-b4a2-bebf213597f3.png)
