### ISSUE TITLE
Fix Brave Ads `base::Time::FromLocalExplode` always returns `false` from Linux sandbox on non UTC+0 timezones

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#20169]
`base::Time::FromLocalExpolode` uses libc `mktime` call which requires access to `/etc/timezone` file: https://source.chromium.org/chromium/chromium/src/+/main:base/time/time_exploded_posix.cc;l=107?q=time_exploded_pos&ss=chromium
But access to filesystem is restricted from sandbox, so `mktime` uses UTC+0 timezone.

The problem is that `base::Time::FromLocalExpolode` verifies the results of `mktime` using `base::Time::LocalExpolode` function which uses local timezone (not UTC+0), because it calls libc `localtime_r` function. In fact `localtime_r` function call is intercepted in browser process thus returns time in local timezone. See:
https://bugs.chromium.org/p/chromium/issues/detail?id=16800
https://codereview.chromium.org/165011
https://source.chromium.org/chromium/chromium/src/+/main:sandbox/linux/services/libc_interceptor.cc;l=225?q=libc_interce&ss=chromium

So if local timezone is not UTC+0 then verification step fails and `base::Time::FromLocalExpolode` always returns false here:
https://source.chromium.org/chromium/chromium/src/+/main:base/time/time_exploded_posix.cc;l=283?q=time_exploded_pos&ss=chromium

**Comment by btlechowski** [comment]
The corresponding has been merged. This issue can be closed.

**Comment by tmancey** [comment]
Blocked until ads has moved to the browser process 100%

**Comment by tmancey** [comment]
CHECKs were triggered so https://github.com/brave/brave-core/pull/20627 removes those CHECKs.

**Comment by tmancey** [comment]
Closing as won't fix

**Comment by tmancey** [comment]
@aseren are we sure the linked bugs are related because they are 14 years old?

**Comment by tmancey** [comment]
Resolved by https://github.com/brave/brave-browser/issues/39307
