### ISSUE TITLE
Prevent `estimated earnings` counter from ever decreasing unexpectedly

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20165]
## Description

Lots of users report the estimated earnings counter decreasing suddenly. Many users watch the estimated earnings counter like hawks, so any non-monotonically increasing changes will immediately make them distrustful and angry. Even if the estimated earnings counter resolves itself after awhile (e.g., a browser restart or after an hour or so), it should not decrease in this way.

Is it the case that the estimated earnings can never be _over-calculated_ (such that drops in the estimated earnings amount are actually required for accuracy)? If so, then we should be able to prevent it from ever decreasing unexpectedly.

cc: @jsecretan

**Comment by tmancey** [comment]
@Miyayes which version of the browser please?

**Comment by tmancey** [comment]
@Miyayes do you know the build channel? Thanks

**Comment by tmancey** [comment]
Closing issue as will be resolved by https://github.com/brave/brave-browser/issues/16028. QA should test as part of https://github.com/brave/brave-browser/issues/16028.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.98 x64 build
- Verification notes can be found here [#16028 (comment)](https://github.com/brave/brave-browser/issues/16028#issuecomment-1025668732)
