### ISSUE TITLE
Brave Privacy Browser. Plz Fix this

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#20160]
Search history appears in address bar
https://github.com/brave/brave-browser/issues/12292

**Comment by UjCbFwtBayFM** [comment]
Disabling "Show autocomplete in address bar" should fix this.

**Comment by manikandancode** [comment]
No.  Issue opened for this reason. 
You need to use private mode or clear browsing history brave://settings/clearBrowserData every time to remove the search history  from address bar.

**Comment by UjCbFwtBayFM** [comment]
I've done it multiple times, no suggestion (search history included) show when autocomplete is disabled.

**Comment by manikandancode** [comment]
https://user-images.githubusercontent.com/46480489/146792520-71fdfd0d-d102-43d2-b21e-05037814974f.mp4

**Comment by rebron** [comment]
Closing as duplicate. Hi @manikandancode If an issue already exists, no reason to file a new one.
