### ISSUE TITLE
Wallet add account and add asset popups should dismiss if Esc is pressed

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20164]
If you press escape after one those poups happen nothing happens.
Instead they should dismiss.
cc @muliswilliam

**Comment by muliswilliam** [comment]
@bbondy I will pick this up.

**Comment by bbondy** [comment]
Thank you!

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.69 Chromium: 97.0.4692.56 (Official Build) dev (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)


Confirmed using `esc` closes dialogs/popups, as seen below:

![escape-to-close](https://user-images.githubusercontent.com/387249/147793328-559715e1-daef-4f35-b1a0-85f9b6a48f02.gif)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | `adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}`
OS | Windows 11 Version Dev (Build 22523.1000)

- Verified steps from [brave/brave-core#11646](https://github.com/brave/brave-core/pull/11646)
- Verified Add wallet modal is dismissed when `Esc` is pressed
- Verified Add wallet modal on Import and Hardware Wallet tabs can also be closed via `Esc`
- Verified Visible assets modal can be closed via `Esc` button
- Verified Visible assets modal with `Add custom token` view can also be closed via `Esc` button
----------
Verification passed on 

Brave | 1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | `adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}`
OS | Linux

- Verified steps from [brave/brave-core#11646](https://github.com/brave/brave-core/pull/11646)
- Verified Add wallet modal is dismissed when `Esc` is pressed
- Verified Add wallet modal on Import and Hardware Wallet tabs can also be closed via `Esc`
- Verified Visible assets modal can be closed via `Esc` button
- Verified Visible assets modal with `Add custom token` view can also be closed via `Esc` button
