### ISSUE TITLE
Pls add support for linux arm

### ISSUE THREAD

**Issue by Painadath** [brave/brave-browser#20161]
HI i am a brave user on android but i want to get it on my raspberry pi so please provide a arm32 build.

**Comment by waltercool** [comment]
Try installing arm64 on your RPi

Problem solved

**Comment by rebron** [comment]
Closing per last comment. Thanks @waltercool

**Comment by Painadath** [comment]
> Try installing arm64 kernel on your RPi
> 
> Problem solved

@waltercool but is there a arm64 linux version for brave?

**Comment by waltercool** [comment]
@Painadath Ah good point, there is only ARM64 support for OSX (Darwin) devices. Their documentation says support for Linux under x86_64 and amd64 architectures https://brave.com/linux/

You could try requesting this here https://github.com/brave/brave-browser/issues/11836

Seems unlikely to make support for ARM32, Brave is a 64bit browser (except for Windows)
