### ISSUE TITLE
[Android] fix padding on chrome://rewards page

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20173]
## Description 

Found by @srirambv 

Wallet panel/card on brave://rewards doesn't have equal padding on either side on Android device

## Steps to Reproduce

   1. Navigate to chrome://rewards w/ Rewards enabled on Android
   2. Look at wallet card/panel
   3. See padding on either side isn't equal

## Actual result:

![Screenshot_20211218-200201](https://user-images.githubusercontent.com/28145373/146799203-94c78a64-9080-458a-ba8a-cfe5d2185951.png)

## Expected result:

Equal padding on either side

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.35.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @emerick

**Comment by Miyayes** [comment]
**Noting:** When ad grant claim button appears too, it's a little misaligned due to padding issue as well.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.77 x64 Beta build
- Verified panel padding is fixed on rewards page
  <img width=300 src=https://user-images.githubusercontent.com/17010094/148751274-3f97f0b4-8542-46f5-acaf-58100e79ea2d.png>

---------
Verification passed on Oppo Reno 5 with Android 11 running 1.35.77 x64 Beta build
- Verified panel padding is fixed on rewards page
- Encountered #20418 
  <img width=300 src=https://user-images.githubusercontent.com/17010094/148751246-0eb4cd9f-da9f-4ee9-a78f-7695e6e9d24b.png>
