### ISSUE TITLE
[Android] select wallet provider screen mentions 15 BAT - follow up to 19912

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20174]
## Description 

When attempting to verify from panel on Android you will see message about 2 BAT. When on wallet provider screen, you will see message about 15 BAT.

## Steps to reproduce 

   1. Install 1.35.47
   2. Enable staging env in QA prefs
   3. Enable Rewards, don't claim grant
   4. Open panel, tap on Verify wallet --> see message about 2 BAT
   5. Select "continue to login" link
   6. Follow UI until you get to screen where you select Uphold.
   7. Select Uphold
   8. See message about 15 BAT

## Actual result 

![Screenshot_20211220-114908](https://user-images.githubusercontent.com/28145373/146803807-a7111f0f-51c8-463e-bdd9-8bbc2f056f51.png)

## Expected result

message should reflect 2 BAT req:

![Screenshot_20211220-114901](https://user-images.githubusercontent.com/28145373/146803842-f5628c63-0c53-4d8a-920f-06011e76ce8c.png)

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? n/a
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.35.47+

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes

**Comment by Miyayes** [comment]
I think Deep has gotten rid of this little white panel completely:
![image](https://user-images.githubusercontent.com/11497541/146811878-5420fecd-f0ef-41c2-857a-ac878da47dc1.png)

So it will only be handled/enforced by the Verify Wallet modal on settings page. cc: @emerick

**Comment by deeppandya** [comment]
> I think Deep has gotten rid of this little white panel completely:
> ![image](https://user-images.githubusercontent.com/11497541/146811878-5420fecd-f0ef-41c2-857a-ac878da47dc1.png)
> 
> So it will only be handled/enforced by the Verify Wallet modal on settings page. cc: @emerick 

@Miyayes it works fine with rewards settings page. I have verified it for uphold and decided to remove it as we do all authentication from react page.

**Comment by LaurenWags** [comment]
ok, fine for the panel one to go away, but the provider screen still needs to be updated to 2BAT.

**Comment by emerick** [comment]
@LaurenWags You're right, thanks for catching that!

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.35.68, Chromium 97.0.4692.56` on a `Google Pixel XL` running `Android 9.0`

Followed the steps given in the description, and confirmed:
* white `Verify Wallet` panel is now gone
* the other interstitial popup now reads `Uphold requires a minimum balance of 2 BAT...`

![Screenshot_20211230-152643](https://user-images.githubusercontent.com/387249/147794346-6363e88d-20e0-46c5-84e7-6730569b2321.png)
