### ISSUE TITLE
Cosmetic filtering uses suboptimal stylesheet injection API

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#20177]
Originally found on https://www.foodnetwork.com/recipes/food-network-kitchen/classic-shrimp-scampi-8849846, where `#dfp_bigbox_recipe_top` and a few other banner ad spaces are not being collapsed. Corresponding filter rules are present in Easylist as generic class/id cosmetic filters.

Minimal example:

```html
<html>
  <head></head>
  <body>
    <div id="dfp_bigbox_recipe_top" style="padding: 100px; background: #ccc; display: block!important"></div>
  </body>
</html>
```

The gray box should _not_ be shown with Shields in aggressive mode. uBlock Origin is able to handle this correctly.

Of note is that Brave Shields creates a `constructed stylesheet` rule, which gets overridden by the inline `display: block!important` style on the element. uBlock Origin creates an `injected stylesheet` rule, which has higher precedence.

**Comment by ryanbr** [comment]
Reported from the community; https://community.brave.com/t/foodnetwork-com-ad-boxes/316301

**Comment by pes10k** [comment]
I've confirmed that this works:
```void HideCssSelectorsInFrame(const blink::WebLocalFrame& frame,
    const base::ListValue& selectors) {
  std::string stylesheet_text;
  for (const auto &selector : selectors.GetList()) {
    stylesheet_text.append(
        selector.GetString() + " {display:none !important;}\n");
  }
  frame.GetDocument().InsertStyleSheet(
      blink::WebString::FromUTF8(stylesheet_text),
      nullptr,
      blink::WebDocument::kUserOrigin); // <-- this is the important part
}
```

I'm not sure how to best integrate with the `hide1pContent` setting, but replacing [the below](https://github.com/brave/brave-core/blob/b004a5b245bae5222b8f58597399fd2a4e82215a/components/cosmetic_filters/renderer/cosmetic_filters_js_handler.cc#L435):

```  if (force_hide_selectors_list &&
      force_hide_selectors_list->GetList().size() != 0) {
    std::string json_selectors;
    if (!base::JSONWriter::Write(*force_hide_selectors_list, &json_selectors) ||
        json_selectors.empty()) {
      json_selectors = "[]";
    }
    // Building a script for stylesheet modifications
    std::string new_selectors_script = base::StringPrintf(
        kForceHideSelectorsInjectScript, json_selectors.c_str());
    web_frame->ExecuteScriptInIsolatedWorld(
        isolated_world_id_, blink::WebString::FromUTF8(new_selectors_script),
        blink::BackForwardCacheAware::kAllow);
  }
```

with 
```
  base::ListValue* force_hide_selectors_list;
  if (resources_dict->GetList("force_hide_selectors",
                               &force_hide_selectors_list)) {
    HideCssSelectorsInFrame(*web_frame, *force_hide_selectors_list);
  }
```

Solves the issue.

**Comment by ryanbr** [comment]
Another example, possibly related empty spaces: https://community.brave.com/t/arstechnica-com-blank-ad-boxes/317201  on `https://arstechnica.com/gadgets/2021/10/surface-laptop-studio-review-one-well-built-weird-convertible-pc/`

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.37.37 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.3 (Build 21E5196i)

### Steps:
1. new profile
2. `python3 -m http.server`
3. saved the minimal HTML testcase locally
4. loaded it `http://localhost:8000/Desktop/issue20177/issue20177-testcase.html`
5. confirmed I saw the text
6. from the text, added `###generic` to `brave://adblock`
7. reloaded the test page
8. confirmed the text was hidden

example | example | example
---------|----------|---------
<img width="731" alt="Screen Shot 2022-02-09 at 5 45 48 PM" src="https://user-images.githubusercontent.com/387249/153321247-65e7ab8e-64a0-4486-9319-20f80cd4cf07.png"> | <img width="1215" alt="Screen Shot 2022-02-09 at 5 38 28 PM" src="https://user-images.githubusercontent.com/387249/153321071-7a0268a3-87f2-45d7-bbe3-835a3e0f966c.png"> | <img width="1610" alt="Screen Shot 2022-02-09 at 5 40 08 PM" src="https://user-images.githubusercontent.com/387249/153321108-580c68e9-bc9c-4baa-8caf-364ce1079a96.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.37 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.3 (Build 21E5196i)

1. installed `1.37.37`
2. saved the minimal HTML testcase to my desktop
3. started a webserver locally via `python3 -m http.server`
4. loaded the file over the webserver: `http://localhost:8000/Desktop/issue20177/issue20177-testcase.html`
5. confirmed issue in `1.35.101` build, in both `aggressive` and `standard` Shields modes
6. switched back to `1.37.37`

Confirmed fix in both `aggressive` and `standard` Shields modes: no gray box showing.
Confirmed gray box shows when `allow all trackers & ads` is set or Shields are `Down`/`Off`.

1.35.101, aggressive | 1.35.101, standard | 1.37.7, aggressive | 1.37.7, standard | 1.377 .7, allow all trackers & ads
--------------------|--------------------|------------------|-----------------|-----------------------
<img width="1680" alt="Screen Shot 2022-02-09 at 6 10 26 PM" src="https://user-images.githubusercontent.com/387249/153323955-a52721f1-146d-49fb-967c-fa7ece180049.png"> | <img width="1680" alt="Screen Shot 2022-02-09 at 6 10 39 PM" src="https://user-images.githubusercontent.com/387249/153324031-2d72c04f-ac1b-416c-880c-10fb2ad90790.png"> | <img width="1492" alt="Screen Shot 2022-02-09 at 6 14 57 PM" src="https://user-images.githubusercontent.com/387249/153324279-2019c4b2-e847-4c9a-8397-3b58076c2f73.png"> |<img width="1492" alt="Screen Shot 2022-02-09 at 6 14 51 PM" src="https://user-images.githubusercontent.com/387249/153324337-6bbd1dc6-a5f5-4194-ae4e-96f48ceee001.png"> | <img width="1380" alt="Screen Shot 2022-02-09 at 6 15 23 PM" src="https://user-images.githubusercontent.com/387249/153324401-d69bb673-7047-4be3-bf2d-11f681901e5b.png">

**Comment by Uni-verse** [comment]
Verified using Beta 1.37.98, Chromium 99.0.4844.74 on Samsung GS 21 running Android 12

- Used minimal html file to test - https://github.com/brave/brave-browser/issues/20177#issue-1085062665
- Element will not be displayed in standard and aggressive modes with shields on. 
- Element will be shown when allow trackers or disabling shields.

1 | 2 | 3 | 4
-|-|-|-
![Screen Shot 2022-03-18 at 12 42 06 PM](https://user-images.githubusercontent.com/17885425/159073229-f68b02b0-5791-4069-b81f-56d4fc87f491.png) | ![Screen Shot 2022-03-18 at 12 42 17 PM](https://user-images.githubusercontent.com/17885425/159073236-b9e079d7-4b1d-4c24-9e36-e2d1fc382eda.png) | ![Screen Shot 2022-03-18 at 12 42 25 PM](https://user-images.githubusercontent.com/17885425/159073239-1b52e30c-5b19-4006-89ce-a81f9b403892.png) | ![Screen Shot 2022-03-18 at 12 42 36 PM](https://user-images.githubusercontent.com/17885425/159073241-6bd899a4-e2dc-4c2b-9a98-b45bfacb8932.png)
