### ISSUE TITLE
Sync isn't working at all in Windows 11

### ISSUE THREAD

**Issue by FahimFBA** [brave/brave-browser#20171]
## Description 
For the past 3 years, Brave is my default browser in my phones, tabs, desktops and laptops. I haven't faced this type of issue for quite a long time. After installing a fresh Windows11 and installing Brave, I added my previous sync chain to the browser, and I clicked on `Sync everything`, but unfortunately the sync isn't working at all. I have waited more than 3 hours, and restarted my PC, cleaned the junk using Bleachbit and so on, but nothing resolved the issue. I checked the `Sync everything` and later `Customize Sync` but nothing works at all. Even though I am selecting `Customize sync` and selecting all of them, after refreshing, I am finding out that all of the checkboxes are disabled and that happened automatically! 

![Screenshot 2021-12-20 202845](https://user-images.githubusercontent.com/64195132/146782889-59faeb8d-feb9-466a-9d6d-e7bb43f8dcc0.png)

## Steps to Reproduce

   1.  Download brave from the official site
   2.  Install
   3.  Add the sync chain

## Actual result:

![Screenshot 2021-12-20 202845](https://user-images.githubusercontent.com/64195132/146782889-59faeb8d-feb9-466a-9d6d-e7bb43f8dcc0.png)

## Expected result:
The sync should have started and been completed within some time.

![Screenshot 2021-12-20 202845](https://user-images.githubusercontent.com/64195132/146783405-3ec0a0b2-80eb-484f-97ac-2177b3ea5368.png)

## Reproduces how often: 

Every time in my case.

## Brave version (brave://version info)

brave://version details:

<html>
<body>

Brave | 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 11 Version 21H2 (Build 22000.376)
JavaScript | V8 9.6.180.21
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,AutoupgradeMixedContent,SafetyTip,WinrtGeolocationImplementation,LegacyTLSEnforced,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=AutofillEnableAccountWalletStorage,ComputePressure,AdInterestGroupAPI,AppDiscoveryRemoteUrlSearch,InterestGroupStorage,ConversionMeasurement,Fledge,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging,CopyLinkToText,ReportAllJavaScriptFrameworks,InterestCohortFeaturePolicy,AutofillServerCommunication,WebSQLInThirdPartyContextEnabled,TabGroupsFeedback,Parakeet,Prerender2,SpeculationRulesPrefetchProxy,TrustTokens,DirectSockets,IdleDetection,NotificationTriggers,WebOTP,NavigatorPluginsFixed,SignedExchangeSubresourcePrefetch,InterestCohortAPIOriginTrial,FirstPartySets,NetworkTimeServiceQuerying,SubresourceWebBundles,FederatedLearningOfCohorts,LiveCaption,TextFragmentAnchor,ReadLater --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\FBA\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | AdRewardsStudy:NextPaymentDayConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledNativeCosmeticFilteringStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Disabled

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release?  YES
- Can you reproduce this issue with the beta channel?  NOT SURE
- Can you reproduce this issue with the nightly channel? NOT SURE

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

**Comment by rebron** [comment]
@FahimFBA How many devices and what are they that you're trying to sync?

**Comment by FahimFBA** [comment]
I am using the sync with 4 devices currently. 
1 Laptop
1 Tab
1 Smartphones
1 Desktop

**Comment by freezingDaniel** [comment]
I am having the same/a similar issue on 2 of my recently reinstalled devices:

- Manjaro GNOME: 
  - Brave 1.34.57 Chromium: 96.0.4664.93 (Official Build) beta (64-bit)
  - Brave 1.32.115-1 (unintalled now)
- Tablet with LineageOS (installed through Play Store):
  - Brave 1.33.106, Chromium 96.0.4664.110

Manjaro shows the same behavior as above (Listing no devices and unticking every sync setting)
Android shows "LOADING DEVICES..."

My phone is the only device still on the sync chain.
Removed other no longer existing devices in the process of trying to make it work.

**Comment by knightncc74656** [comment]
I experienced the same problem on windows 11 and leaving then rejoining the sync chain fixed the problem for me.

**Comment by FahimFBA** [comment]
The issue has also been resolved for me after trying some days. I am closing the issue for now.
