### ISSUE TITLE
Update Sync QR v2 text error for valid too long case

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#20170]
According to the discussion and updated spec: 

Is the `not_after` datetime further than 60 minutes into the future,  `Valid for too long case` - error text should be: 
```
This code is invalid. Please check that the time and timezone are set correctly on your device.
```

**Comment by stephendonner** [comment]
Verified `IN-PROGRESS` using Android and macOS client versions: 

Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)
