### ISSUE TITLE
Add Token Balances in Brave Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20179]
## Description 
Display Token Balances in the Brave Wallet Panel 

![Screen Shot 2021-12-20 at 2 56 36 PM](https://user-images.githubusercontent.com/40611140/146837964-5507383c-3dbb-41a9-a4a9-0eeceb061c9b.png)

**Comment by srirambv** [comment]
Marking as `QA/No` as this is superseded by #20464
