### ISSUE TITLE
[Android] Update all bitFlyer logos with new assets

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20187]
Android version of https://github.com/brave/brave-browser/issues/20186. 

## Description

Update all bitFlyer logos with new assets where relevant. Message @Miyayes or @soi-tnk for assets and documentation.

![image](https://user-images.githubusercontent.com/11497541/146954121-4af9c00d-5d23-4506-9c70-f1667f1291df.png)

Note: color of the image has changed, and font has changed.

**Comment by LaurenWags** [comment]
Verified with `1.35.89 Chromium: 97.0.4692.71 (Official Build) beta` on Google Pixel 3 XL running Android 12.

Confirmed bitFlyer logo is shown in the following places before/after logging in:

Before login on verification modal | Settings page | Settings page drop down | Panel | Panel modal
----- | ----- | ----- | ----- | -----
![1](https://user-images.githubusercontent.com/28145373/150375726-561295d6-6ace-418f-acf9-bd011d09a241.png) | ![2](https://user-images.githubusercontent.com/28145373/150375740-4d240aa1-a919-4a90-b869-e0ba22819adb.png) | ![3](https://user-images.githubusercontent.com/28145373/150375750-addbd5e1-0023-49bd-8e07-5b09b9168137.png) | ![4](https://user-images.githubusercontent.com/28145373/150375760-2262640f-0609-4440-b4f3-f26cb4199d11.png) | ![5](https://user-images.githubusercontent.com/28145373/150375771-fa4d697a-0edf-488d-90c0-42f200213b96.png)

Confirmed bitFlyer logo is shown in the following places after simulating a natural disconnect:

Settings page | Settings page drop down | Panel 
----- | ----- | ----- 
![7](https://user-images.githubusercontent.com/28145373/150376076-e427b48c-a324-423d-a5de-0daec0fe2b0e.png) | ![8](https://user-images.githubusercontent.com/28145373/150376087-9bb6c792-d22b-44d9-8418-9046e4b832ae.png) | ![6](https://user-images.githubusercontent.com/28145373/150376093-3ebd349e-d295-4094-b193-645fcb36efbf.png)
