### ISSUE TITLE
Brave news Settings bar appears lower

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20182]
## Description 

The settings bar appears lower than it should on the first run

## Steps to reproduce 

   1. Fresh install
   2. Opt in brave news
   3. Scrolling the news cads makes the settings bar visible but it appears lower and disconnected from the address bar
   4. Swiping out the app and restarting will show the correct position

## Actual result 

The settings bar should be in the right place all the time

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
@alexsafe do you happen to have a screenshot of this?  I can't seem to reproduce it using `1.35.44, Chromium 97.0.4692.56`.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.85 x64 Beta build
- Verified steps from issue description
- Verified there is no gap between URL bar and Brave News setting bar

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/149758731-b8aaa9c6-8c94-4e94-85b7-ce54c60bba53.png) | ![image](https://user-images.githubusercontent.com/17010094/149758704-bc56116a-ab5c-4abb-bb54-81df585245a1.png)

------
Verification passed on Samsung Tab A with Android 10 running 1.35.85 x64 beta build
- Verified steps from issue description
- Verified there is no gap between URL bar and Brave News setting bar
- Encountered [#20525](https://github.com/brave/brave-browser/issues/20525) & [#20416](https://github.com/brave/brave-browser/issues/20416)

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/149762449-9df08c32-6695-4c76-97e2-b40a845d6ea5.png) | ![image](https://user-images.githubusercontent.com/17010094/149762852-25c69322-952f-43bd-a0b2-85bd136fa949.png)
