### ISSUE TITLE
[Feature Request] Bottom URL Addres bar on bottom and options to remove AMP.

### ISSUE THREAD

**Issue by SwiftyPop** [brave/brave-browser#20198]
**Bottom URL address bar**

* Firefox, Vivaldi, and Kiwi Browsers, for example, already have a bottom address bar. Is there any progress on this?

**Remove AMP**

* Usually, when I click some articles from my Google Discover/Feed. It will load AMP site which I don't really like. Example problem with AMP have some weird blank buffering ads and can't use comments in the site. AMP very limited. Bromite,Kiwi and Firefox,which is open-source have ability to remove AMP from the site and it working great. Is there any new update about this? It's been a long time. This should be an option in privacy-focused browsers.

**Comment by NayamAmarshe** [comment]
> Bottom URL address bar

Have you never opened appearance settings? Afaik, Brave comes with a bottom address bar by default too.

**Comment by SwiftyPop** [comment]
> > Bottom URL address bar
> 
> Have you never opened appearance settings? Afaik, Brave comes with a bottom address bar by default too.

I only see bottom toolbar? You should read "Bottom URL Address bar" again.
