### ISSUE TITLE
Replace "Refresh status" with refresh icon only

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20195]
## Description

"Refresh status" takes up too much horizontal space and can cause new lines, etc. depending on translations. Replace it with a refresh icon only so that it can be moved to the right of the "Verified creator" label. 

Note: Ensure that there is enough spacing/margin between the "Verified creator" label and the refresh icon.

<img src="https://user-images.githubusercontent.com/11497541/146994835-c2fc4788-b491-455b-ac68-ae91f4e256ba.png" height=300px>

## Solution

Use the following icon: 
![image](https://user-images.githubusercontent.com/11497541/188208109-802ffbe8-e56a-449b-80c0-51f1d5d323b4.png)

**Comment by Miyayes** [comment]
@minkyeongshin do you have any preferred refresh icon?

**Comment by Miyayes** [comment]
Icon received. Ready to go.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.75`
2. launched Brave
3. loaded `jumde.github.io`
4. clicked on the BAT icon
5. enabled Rewards
6. clicked again on the BAT icon
7. examined the new `Refresh` icon

example | example
---------|---------
<img width="465" alt="Screen Shot 2022-09-27 at 5 07 44 PM" src="https://user-images.githubusercontent.com/387249/192635810-5edc069f-6547-424b-8d28-5e701778f274.png"> | <img width="456" alt="Screen Shot 2022-09-27 at 5 08 19 PM" src="https://user-images.githubusercontent.com/387249/192635813-f44ad6c2-858c-4381-97d2-1ed0461b509a.png">

#### Confirmed:
* tooltip reads `Refresh`
* clicking `Refresh` reloads via the following:
> > Url: https://pcdn.bravesoftware.com/publishers/prefixes/0d62
> Result: Success
> HTTP Code: 200
> Body:
[13688:259:0927/171127.700040:VERBOSE9:logging_util.cc(135)]
[ RESPONSE HEADERS ]
> Url: https://pcdn.bravesoftware.com/publishers/prefixes/0d62
> Header accept-ranges: bytes
> Header age: 24
> Header cache-control: max-age=5259492
> Header content-length: 1000
> Header content-type: binary/octet-stream
> Header date: Tue, 27 Sep 2022 21:11:04 GMT
> Header etag: "6f278cc493b0591ed1826f7574f7bde6"
> Header last-modified: Tue, 27 Sep 2022 19:00:12 GMT
> Header server: AmazonS3
> Header via: 1.1 fb7a91e6436d6c6ab7f46f75c256840c.cloudfront.net (CloudFront)
> Header x-amz-cf-id: TU-mDEm0QKAzEvQtvVnA6Fhr2IpJ-uCiLR73jGGAoi-nWeWWVo86Qw==
> Header x-amz-cf-pop: JFK51-C1
> Header x-cache: Hit from cloudfront
[13688:259:0927/171127.700152:VERBOSE1:database_server_publisher_banner.cc(40)] Empty publisher banner data, skipping insert
