### ISSUE TITLE
[Android] Hide "Total Grants Claimed" line from Rewards panel summary

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20194]
## Description

Remove the Total Grants Claimed line from Rewards panel summary, as it is no longer relevant to end-users.

**Comment by LaurenWags** [comment]
Verification in progress using `1.35.81 Chromium: 97.0.4692.71` on Google Pixel 3 XL running Android 12.

<details>
<summary>US Region - PASSED</summary>

Confirmed for anon wallet, US region, "Total Grants Claimed" is not displayed on the panel or rewards page:

Panel | Rewards page
----- | -----
![US-anon-panel](https://user-images.githubusercontent.com/28145373/149528404-a8694557-1949-485d-80f7-3d5fd7bf28a3.png) | ![US-anon-rewardspage](https://user-images.githubusercontent.com/28145373/149528414-6302b279-b25e-4b91-bb08-4b0012d7758d.png)

Confirmed for Uphold KYC'd wallet, US region, "Total Grants Claimed" is not displayed on the panel or rewards page:

Panel | Rewards page
----- | -----
![US-Uphold-panel](https://user-images.githubusercontent.com/28145373/149528432-52f77f0e-854b-4c09-886c-9b0e6344dc96.png) | ![US-Uphold-rewardspage](https://user-images.githubusercontent.com/28145373/149528450-c60a807e-7942-448f-a5cd-05dc7b46074f.png)

</details>
