### ISSUE TITLE
[Android] Replace "Refresh status" with refresh icon only

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20193]
## Description

"Refresh status" takes up too much horizontal space, especially on Android. Replace it with a refresh icon only so that it can be moved to the right of the "Verified creator" label.

Note: Ensure that there is enough spacing/margin between the "Verified creator" label and the refresh icon.

**Comment by LaurenWags** [comment]
Verified passed with `1.35.81 Chromium 97.0.4692.71` on Pixel 3 XL running Android 12.

Confirmed only refresh icon is present.
Confirmed refresh icon refreshes the publisher status when selected.
Confirmed looks ok for a couple languages (English and Japanese).

Example | Example | Example
----- | ----- | -----
![Screenshot_20220113-165201](https://user-images.githubusercontent.com/28145373/149415328-b07533ea-2ce3-41e5-a33e-e1f16525bacd.png) | ![Screenshot_20220113-165208](https://user-images.githubusercontent.com/28145373/149415340-6ff8ad2e-5dfa-4d1b-9824-7f300a61b912.png) | ![Screenshot_20220113-165236](https://user-images.githubusercontent.com/28145373/149415346-0e0ab9bc-6da5-4ea6-b894-2b33506d5cc8.png)
