### ISSUE TITLE
Create a Reusable GetBlockExplorerUrl Util

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20192]
## Description 
Currently we have multiple methods through out the wallet for getting an `EthereumChain` block explorer URL.
We should create a reusable `GetBlockExplorerUrl` util to cut down on duplicated code.

**Comment by bbondy** [comment]
Posted a follow up for this here https://github.com/brave/brave-browser/issues/20246

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.98 Chromium: 98.0.4758.72 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified able to view addresses, transactions, and contracts</li>
         <li>Verified able to open block explorer links both from Wallet page as well as panel</li>
         <li>Verified able to open block explorer links for custom networks, such as Polygon</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/151913778-77aa1ebb-d45b-49f4-8529-a9b9d025ca0c.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151913410-769be1ac-4b59-444f-a7f5-0c9a28aea3b9.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/151913101-a5b1c58b-5957-4488-b472-6589138d0504.mov>
      </td>
   </tr>
</table>
