### ISSUE TITLE
Use Update instead of Insert for creative_ads_conversion table

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#20191]
When parsing a new catalog, if the ads library `creative_ads_conversion` table has an existing `creativeInstanceId`, update it with the values from the new catalog rather than inserting a new entry.

Insertion of a new entry introduces a race condition that should be avoided.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.35.98 Chromium: 98.0.4758.74 (Official Build) (64-bit) 
-- | --
Revision | d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}
OS | Ubuntu 18.04 LTS

Before update
![image](https://user-images.githubusercontent.com/34715963/151738928-f0cb9381-3fe4-4703-8e9a-3387517fb8e9.png)

After update
![image](https://user-images.githubusercontent.com/34715963/151739104-93b20b21-8386-49ac-9264-d490ac02393c.png)

**Comment by srirambv** [comment]
Discussed with @btlechowski  and removing Android label as there is no way to access the Ads db file.
