### ISSUE TITLE
Clicking on stats should show resources blocked

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#202]
For parity with browser-laptop. We should allow clicking on the numbers to show what is blocked next.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
