### ISSUE TITLE
BatAdsTimeUtilTest* tests are failing for CET+1 timezone

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#20204]
> 2 tests failed:
>     BatAdsTimeUtilTest.AdjustTimeToBeginningOfPreviousMonth/1 (../../brave/vendor/bat-native-ads/src/bat/ads/internal/time_util_unittest.cc:91)
>     BatAdsTimeUtilTest.GetTimeAtBeginningOfLastMonth/1 (../../brave/vendor/bat-native-ads/src/bat/ads/internal/time_util_unittest.cc:187)

**Comment by stephendonner** [comment]
As this is unittests, @aseren is this really `QA/Yes` -- and if so, can you please provide a testplan? -- or can we mark it `QA/No`?  Thanks!

**Comment by btlechowski** [comment]
Marked as `QA/Blocked`, we really need a test plan for this one.

**Comment by aseren** [comment]
@stephendonner @btlechowski 
Sorry for missing a test plan for the issue. I've updated PR description with testing steps: https://github.com/brave/brave-core/pull/11683

**Comment by btlechowski** [comment]
Removed `QA/Blocked`, test plan was added.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.35.92 Chromium: 97.0.4692.99 (Official Build) beta (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/11683. Verified for CET +1

Verified "Current earnings this month (estimated)" has the correct value and "Ads received this month" has the correct value
Verified that the values is not reset after browser restart

<details>

2 ads:
![image](https://user-images.githubusercontent.com/34715963/150898471-2b1e29e2-9ea0-4bf9-b4df-6e0a3174a37a.png)

3 ads:
![image](https://user-images.githubusercontent.com/34715963/150898990-63a6fc28-e01e-4125-bd37-9557ed08617d.png)


</details>
