### ISSUE TITLE
[Android] Remove/hide and modify A-C slides in onboarding tours when region is Japan

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20202]
## Description

When user is presented with Rewards opt in modal, they have two options:

1. Enable Rewards
2. Take a tour

Some A-C elements appear in both paths, but should not if region is Japan.

## Solution

- [ ] In Take a Tour path, there is a `SLIDE 1` about A-C. This should be hidden/removed if region == Japan.
- [ ] In Enable Rewards path, there is also also `SLIDE 1` about A-C. This should be hidden/removed if region == Japan.
- [ ] In Enable Rewards path, there is also a `SLIDE 2` where user can set default A-C amount. This **subportion** of the slide should be hidden/removed, but the rest above (which sets ad frequency per hour) should remain as is, when region == Japan.

**SLIDE 1**

<img src="https://user-images.githubusercontent.com/11497541/147121530-dc2ba476-2f78-49a9-a6bf-529fc1380f78.png" height=300px>

**SLIDE 2**

<img src="https://user-images.githubusercontent.com/11497541/147121547-0f728e07-d25b-4a23-ae8a-61a6e1ae617f.png" height=300px>

Relevant subportion that should be hidden:

![image](https://user-images.githubusercontent.com/11497541/147122279-db91ab0a-e5b7-4831-818a-e9804a7a046d.png)

Found by @LaurenWags.

**Comment by LaurenWags** [comment]
@brave/legacy_qa I added `OS/Desktop` to this issue as well. We confirm that desktop retains the bitFlyer specific onboarding for Japan region as well as confirm that non-Japan regions still contain the AC information in their onboarding.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.35.75 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 21H2 (Build 19044.1415)

```
- Verified the test plan from https://github.com/brave/brave-browser/issues/20202#issue-1086974861

**Comment by LaurenWags** [comment]
Verification in progress with `1.35.87 Chromium: 97.0.4692.71 (Official Build) beta` on Pixel 3 XL with Android 11.
