### ISSUE TITLE
[Android] "Take a tour" Rewards onboarding should take user back to opt in modal

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20201]
## Description

When user is not opted into Rewards and opens Rewards panel, they are presented with a "opt in modal" that gives them two options:

1. Enable Rewards
2. Take a tour

When they press "Take a tour", they are shown some tour slides. At the end of the tour slides, they should be redirected back to the "opt in modal" screen. However, currently when they finish the "take a tour" tour, it shows them the Rewards panel as though they have opted in, even though they have not actually. When they re-open panel, they are presented with "opt in modal" again.

## Actual behavior

Currently when they finish the "take a tour" tour, it shows them the Rewards panel as though they have opted in, even though they have not actually.

## Expected behavior

At the end of the tour slides, they should be redirected back to the "opt in modal" screen.

**Comment by LaurenWags** [comment]
@deeppandya this issue needs a milestone so it can be tested by @brave/legacy_qa

**Comment by LaurenWags** [comment]
Verified with 1.35.87 Chromium: 97.0.4692.71 (Official Build) beta on Pixel 3 XL with Android 11.

* Verified selecting "Take a quick tour" from panel directs user back to the opt-in modal on the panel.
* Selecting "Take a quick tour" from brave://rewards page does not re-show the opt-in modal on the brave://rewards page. This is covered with https://github.com/brave/brave-browser/issues/20447.
