### ISSUE TITLE
Fix Brave Ads save and dislike filters

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#20206]
Should be tested as part of https://github.com/brave/brave-browser/issues/16005. Only affects nightly 1.35

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.35.89 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Ubuntu 18.04 LTS

#### Save an ad

Confirmed ad was saved by clicking "Saved" filter
![image](https://user-images.githubusercontent.com/34715963/150399487-d55af4dc-3b4d-47a5-9ff0-3880881cc588.png)

Confirm creative instance id was saved under client.json / adPreferences / saved_ads
![image](https://user-images.githubusercontent.com/34715963/150399785-632cd5c6-08da-440b-aaf3-438a00ef76a6.png)

#### Remove an ad from saved

Confirm ad was removed from "Saved" filter
![image](https://user-images.githubusercontent.com/34715963/150400737-1314c2aa-7f2c-4c4d-84ab-085b4b7e3aa5.png)

Confirm creative instance id was removed from client.json / adPreferences / saved_ads
![image](https://user-images.githubusercontent.com/34715963/150400824-578ea219-d0c2-42ae-b2ba-a77b2d91f62c.png)

#### Mark as inappropriate (see kebab menu)

Confirm ads are blocked based upon the creative set id for the marked ad
![image](https://user-images.githubusercontent.com/34715963/150401901-de08fe3b-e59f-4abc-9a1b-93746feff1f9.png)

```
[7965:7965:0120/204735.276974:VERBOSE2:exclusion_rules_base.cc(123)] creativeSetId 5e96fecc-2926-4c72-bb76-4e745bf6b539 excluded due to being marked as inappropriate
```

Confirm creative set id was saved under client.json / adPreferences / flagged_ads
![image](https://user-images.githubusercontent.com/34715963/150402822-14c1f6f1-75ff-4ad3-ab07-ee08e160e549.png)

Confirmation was successful
```
[7965:7965:0120/205112.689549:VERBOSE1:confirmations.cc(69)] Confirming flag for ad_notification with transaction id 8e8f13f7-0d8e-45ed-b388-702d09716831 and creative instance id 0e3fa44c-edd4-4ad3-b21e-e6c93ef001c4
[7965:7965:0120/205112.690913:VERBOSE1:redeem_unblinded_token.cc(55)] Redeem unblinded token
[7965:7965:0120/205112.691478:VERBOSE1:redeem_unblinded_token.cc(74)] CreateConfirmation
[7965:7965:0120/205112.691596:VERBOSE2:redeem_unblinded_token.cc(75)] POST /v2/confirmation/{confirmation_id}/{credential}
[7965:7965:0120/205112.691787:VERBOSE6:redeem_unblinded_token.cc(79)] URL Request:
  URL: https://ads-serve.bravesoftware.com/v2/confirmation/a3cd30f3-36ac-4656-a6e4-1cd98186edef/eyJwYXlsb2FkIjoie1wiYmxpbmRlZFBheW1lbnRUb2tlbnNcIjpbXCJHRVIzamRUS016bE4rZ2ZBVjZ1N3VtR3hrVmV5K2p2NURwYk1hOXoxTEJBPVwiXSxcImJ1aWxkQ2hhbm5lbFwiOlwiYmV0YVwiLFwiY3JlYXRpdmVJbnN0YW5jZUlkXCI6XCIwZTNmYTQ0Yy1lZGQ0LTRhZDMtYjIxZS1lNmM5M2VmMDAxYzRcIixcInBheWxvYWRcIjp7fSxcInBsYXRmb3JtXCI6XCJsaW51eFwiLFwicHVibGljS2V5XCI6XCJpTWhSSGY5MnEyM05ueUpKTnBleVZ0S2JTaUNSRkxtS1g3UFE1bHJmaWs4PVwiLFwic3R1ZGllc1wiOltdLFwidHlwZVwiOlwiZmxhZ1wifSIsInNpZ25hdHVyZSI6IjNxamhaU29iMkNPN3FyOU9pWXVGRTgvNXZZL1JGVzlOdzFJbzFkL3o0M2Ivb2IzWk84NFhlT3k2V0VLeGVWbDU3azhtTmYzblp3RDBuemhFQmVPTWRRPT0iLCJ0IjoiaEMxLzNCckFMcENQYVJWMHlBQ1JTclBWbTl0TC84VUd1Y01RNmswQy9XNGM3UmgvVlhYQ1ZnaDJFMzdDVkFiL2o2SUNYb0ZQL0V0K3plQldPc0JzK3c9PSJ9
  Content: {"blindedPaymentTokens":["GER3jdTKMzlN+gfAV6u7umGxkVey+jv5DpbMa9z1LBA="],"buildChannel":"beta","creativeInstanceId":"0e3fa44c-edd4-4ad3-b21e-e6c93ef001c4","payload":{},"platform":"linux","publicKey":"iMhRHf92q23NnyJJNpeyVtKbSiCRFLmKX7PQ5lrfik8=","studies":[],"type":"flag"}
  Content Type: application/json
  Method: kPost
[7965:7965:0120/205112.920505:VERBOSE1:redeem_unblinded_token.cc(90)] OnCreateConfirmation
[7965:7965:0120/205112.920543:VERBOSE6:redeem_unblinded_token.cc(92)] URL Response:
  URL: https://ads-serve.bravesoftware.com/v2/confirmation/a3cd30f3-36ac-4656-a6e4-1cd98186edef/eyJwYXlsb2FkIjoie1wiYmxpbmRlZFBheW1lbnRUb2tlbnNcIjpbXCJHRVIzamRUS016bE4rZ2ZBVjZ1N3VtR3hrVmV5K2p2NURwYk1hOXoxTEJBPVwiXSxcImJ1aWxkQ2hhbm5lbFwiOlwiYmV0YVwiLFwiY3JlYXRpdmVJbnN0YW5jZUlkXCI6XCIwZTNmYTQ0Yy1lZGQ0LTRhZDMtYjIxZS1lNmM5M2VmMDAxYzRcIixcInBheWxvYWRcIjp7fSxcInBsYXRmb3JtXCI6XCJsaW51eFwiLFwicHVibGljS2V5XCI6XCJpTWhSSGY5MnEyM05ueUpKTnBleVZ0S2JTaUNSRkxtS1g3UFE1bHJmaWs4PVwiLFwic3R1ZGllc1wiOltdLFwidHlwZVwiOlwiZmxhZ1wifSIsInNpZ25hdHVyZSI6IjNxamhaU29iMkNPN3FyOU9pWXVGRTgvNXZZL1JGVzlOdzFJbzFkL3o0M2Ivb2IzWk84NFhlT3k2V0VLeGVWbDU3azhtTmYzblp3RDBuemhFQmVPTWRRPT0iLCJ0IjoiaEMxLzNCckFMcENQYVJWMHlBQ1JTclBWbTl0TC84VUd1Y01RNmswQy9XNGM3UmgvVlhYQ1ZnaDJFMzdDVkFiL2o2SUNYb0ZQL0V0K3plQldPc0JzK3c9PSJ9
  Response Status Code: 201
  Response: {"id":"a3cd30f3-36ac-4656-a6e4-1cd98186edef","payload":{},"createdAt":"2022-01-20T18:50:20.813Z","type":"flag","modifiedAt":"2022-01-20T18:50:20.813Z","creativeInstanceId":"0e3fa44c-edd4-4ad3-b21e-e6c93ef001c4"}

```

#### Unmark as inappropriate (see kebab menu)

Confirm ads are not blocked based upon the creative set id for the unmarked ad
![image](https://user-images.githubusercontent.com/34715963/150403287-f9ed981b-60a2-4c22-90ad-e2b2c7a32698.png)


Confirmed ad was shown:
```
[8386:8386:0120/205949.906645:VERBOSE1:ad_notification_serving.cc(260)] Serving ad notification:
  uuid: 44ca577b-3116-4ab3-9f29-39d8210b71d1
  creativeInstanceId: 13fdf11c-b5f3-460a-b347-902862b65ef4
  creativeSetId: 5e96fecc-2926-4c72-bb76-4e745bf6b539
  campaignId: 0d01425b-c970-4a25-b2d0-ccf748cfaf6e
  advertiserId: ecbcc833-8b1d-4867-98f7-ad2341396ce8
  segment: technology & computing
  title: Ad Set 2 - Creative 1 - Ad 1
  body: Ad Set 2 - Creative 1 - Ad 1
  targetUrl: https://youtube.com

```

Confirm creative set id was removed from client.json / adPreferences / flagged_ads
![image](https://user-images.githubusercontent.com/34715963/150403956-05a31498-564e-4007-a7ac-532a8b9e8d35.png)

#### Mark to no longer receive (aka no entry icon)

Confirm ads are blocked based upon the category name for the marked ad
![image](https://user-images.githubusercontent.com/34715963/150892253-4f137cba-da97-44a5-a817-1cfcbe77e5ee.png)

Confirm ad is blocked
```
[10528:10528:0125/021650.756151:VERBOSE2:exclusion_rules_base.cc(123)] creativeSetId c49b78ab-27a3-4a08-9cda-434f097d8cf8 excluded due to untargeted category being marked to no longer receive ads
```

Confirm category name was saved under client.json / adPreferences / filtered_categories
![image](https://user-images.githubusercontent.com/34715963/150892337-6064f2cf-35c6-4b3d-820e-759088a375ec.png)

#### Unmark to no longer receive (aka heart icon or neutral, i.e. no icon selected)

Confirm ads are not blocked based upon the category name for the unmarked ad
![image](https://user-images.githubusercontent.com/34715963/150893596-273f1d46-c0e0-46c4-a1a9-fe36c842b745.png)

Confirm category name was removed from client.json / adPreferences / filtered_categories
![image](https://user-images.githubusercontent.com/34715963/150893642-2765558d-4b6c-4a36-b3de-c90957d8ee84.png)

Verified received the ad after unblocking
```
[14101:14101:0125/050243.397131:VERBOSE1:ad_notification_serving.cc(141)] Found 3 eligible ads
[14101:14101:0125/050243.397252:VERBOSE1:ad_notification_serving.cc(260)] Serving ad notification:
  uuid: 7620a0ab-d4d8-4b84-9a27-5edbe682728c
  creativeInstanceId: 4cda3ae7-1f70-4bca-b361-ca01d6a8f1ed
  creativeSetId: 5f8c4787-8431-49a5-9d09-bba40f8ad5f4
  campaignId: d1e25388-b362-4f30-bd4b-36b8205e59e5
  advertiserId: a34de75d-5654-4331-8713-8f4d4e2b6bf7
  segment: untargeted
  title: Vivamus sagittis lacus vel aug
  body: Duis mollis, est non commodo luctus, nisi erat porttitor lig
  targetUrl: https://www.apple.com

```

#### Dislike (aka thumbs down icon)

Confirm ads are blocked based upon the advertiser id for the disliked ad
![image](https://user-images.githubusercontent.com/34715963/150895616-3e67a9f7-7e8a-44d7-93dd-4b7d3df60749.png)


Confirm advertiser id was saved under client.json / adPreferences / filtered_advertisers
```
{"filtered_advertisers":[{"id":"ecbcc833-8b1d-4867-98f7-ad2341396ce8"}]
```

#### Like (aka thumbs up icon or neutral, i.e. no icon selected)

Confirm ads are not blocked based upon the advertiser id for the liked ad

Ad was shown:
```
[3420:3420:0121/102112.968419:VERBOSE1:eligible_ad_notifications_v1.cc(39)] Get eligible ad notifications:
[3420:3420:0121/102112.969400:VERBOSE1:eligible_ad_notifications_v1.cc(150)] Get eligible ads for untargeted segment
[3420:3420:0121/102112.971101:VERBOSE1:seen_advertisers.h(30)] All ad_notification advertisers have been shown, so round robin
[3420:3420:0121/102112.971308:VERBOSE1:client.cc(446)] Resetting seen ad_notification advertisers
[3420:3420:0121/102112.971461:VERBOSE1:seen_ads.h(30)] All ad_notification ads have been shown, so round robin
[3420:3420:0121/102112.971549:VERBOSE1:client.cc(410)] Resetting seen ad_notifications
[3420:3420:0121/102112.971673:VERBOSE2:ad_priority.h(32)] 1 ads with a priority of 1 in bucket 1
[3420:3420:0121/102112.971891:VERBOSE1:ad_notification_serving.cc(141)] Found 1 eligible ads
[3420:3420:0121/102112.971982:VERBOSE1:ad_notification_serving.cc(260)] Serving ad notification:
  uuid: ac3e41b9-d76f-4d8d-8745-3fa62b2d0ce2
  creativeInstanceId: 4cda3ae7-1f70-4bca-b361-ca01d6a8f1ed
  creativeSetId: 5f8c4787-8431-49a5-9d09-bba40f8ad5f4
  campaignId: d1e25388-b362-4f30-bd4b-36b8205e59e5
  advertiserId: a34de75d-5654-4331-8713-8f4d4e2b6bf7
  segment: untargeted
  title: Vivamus sagittis lacus vel aug
  body: Duis mollis, est non commodo luctus, nisi erat porttito
```

Confirm advertiser id was removed from client.json / adPreferences / filtered_advertisers
```
"filtered_advertisers":[]
```
