### ISSUE TITLE
[Android] Implement Gemini creator detection in Rewards 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20208]
## Description

Gemini creators should be able to be detected as verified on Android, and follows all the same logic as laid out here:  https://github.com/brave/brave-browser/issues/20135 

When tipping a Gemini creator on Android _as an unverified user_, it follows the same vBAT tipping paths as any other case with unverified users, and should just tip using vBAT.

**Comment by LaurenWags** [comment]
Verification in progress with `1.35.87 Chromium: 97.0.4692.71 (Official Build) beta` on Pixel 3 XL with Android 11.

See testing notes under https://github.com/brave/brave-browser/issues/20232#issuecomment-1015473342.
