### ISSUE TITLE
[Android] panel has 5 BAT monthly contribution set automatically

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20200]
## Description 

When visiting a site for the first time the panel is showing a 5 BAT monthly contribution automatically. The panel should be showing a link with "Set" instead which will direct the user to a place with the pre-set options available to set a monthly tip (note, custom tipping is not yet available on Android per https://github.com/brave/brave-browser/issues/16021).

Note - QA will need to verify this against anon wallet, Uphold wallet, and bitFlyer wallet.

## Steps to reproduce 

   1. Clean install 1.35.50 (Nightly)
   2. Enable Staging env, relaunch
   3. Enable Rewards
   4. Navigate to a site like brave.com
   5. Open panel

## Actual result 

See Monthly Contribution as 5 BAT.

![Screenshot_20211222-102610](https://user-images.githubusercontent.com/28145373/147115967-80bb31b3-b32d-4511-a5d6-5823795e0f36.png)

## Expected result
Should show a link w/ "Set" where a user can go to select pre-set options for monthly tip since custom tipping is not yet available on Android.

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? n/a
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.35.50

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes @brave/legacy_qa

**Comment by Miyayes** [comment]
## Implementation

![image](https://user-images.githubusercontent.com/11497541/147608403-f92af2a8-7257-44eb-9761-f4d32c9744cd.png)

Pressing "Set" will open up tipping banner with monthly contribution option set. 

Once it is set, then it will show the set value plus a little dropdown carrot, and when pressed, a dropdown menu with two options:

![image](https://user-images.githubusercontent.com/11497541/147608444-263882b7-4301-4bce-bfce-3d48104d86e0.png)

When user presses "Cancel" (on Android), it can just reset it to nothing, and the user will see "Set".

When user presses "Change amount", it will open up the tipping banner with monthly contribution option set again.

**Comment by LaurenWags** [comment]
labelling `QA/Blocked` until uplifted to 1.35.x

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.97 x64 build
- Verified BR panel has no default monthly contribution set for any publisher (Unverified/Connected/KYC'd)
- Verified default value for monthly contribution is `Set`
- Verified clicking on `Set` loads tipping banner for the publisher and `Set Monthly Tip` checkbox is selected
- Verified clicking on `Set` loads the tipping banner and has the default preset set during onboarding
- Verified setting a monthly contribution lists under `brave://rewards`
- Verified clicking on the set value brings a dropdown with `Change amount` and `Cancel`
- Verified selecting `Change amount` brings the tipping banner again and is able to change the value
- Verified changed value is updated and reflected under Monthly contributions in `brave://rewards`
- Verified selecting `Cancel` removes the monthly contributions set for that publisher

Anon Wallet | Uphold KYC'd Wallet | bitFlyer KYC'd Wallet 
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/151559574-950c98dc-0045-4c72-8b0c-b29af9b24f45.mp4> | <video src=https://user-images.githubusercontent.com/17010094/151559619-dcdd0c73-cf79-442b-8f15-88767566f952.mp4> | <video src=https://user-images.githubusercontent.com/17010094/151559596-183fcd67-f14b-4d73-b33d-ba7800745d6f.mp4>
