### ISSUE TITLE
Custom notifications are shifted to the left on Windows 7 and 8

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#20219]
The shift to the left was introduced to accommodate native (system) notifications.
Windows 7 and 8 don't have native (system) notifications so the shift is not needed

## Steps to Reproduce

1. Clean profile
1. Enable rewards and ads
1. Trigger custom ad notification

## Actual result:

Custom notifications are shift to the left on Windows 7 and 8

![image](https://user-images.githubusercontent.com/34715963/146420937-f23b186e-9807-43ea-abfe-b9b1f80c507b.png)

## Expected result:
Custom notifications are not shifted left on Windows 7 and 8

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @tmancey @jsecretan

**Comment by tmancey** [comment]
This should be resolved via Griffin

**Comment by tmancey** [comment]
Closing issue as Chromium 109 drops support for Windows 7/8
