### ISSUE TITLE
Update Gemini promo card (Jan 2022)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20211]
## Description

- [ ] **Change body text to:** Trade 50+ cryptos, including BAT, on Gemini. It’s a secure platform to store your crypto. Plus, you can earn interest in US, HK, and SG. Create an account to link your Brave Rewards wallet to Gemini.
- [ ] Enable in all previous geos again

**Comment by Miyayes** [comment]
@emerick Got approval to remove the last line "Create an account to link Brave Rewards with Gemini". That should give us enough space!

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.31 Chromium: 97.0.4692.71 (Official Build) nightly (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)

Confirmed available in at least the following (from the [big list](https://github.com/brave/brave-core/blob/b1eb0ddbfcb0e41fd8ad8aa4aa9b319fd955adf0/components/brave_rewards/resources/page/promos/index.tsx#L80-L84):

US | Hong Kong | Singapore | Spain
---|--------------|----------|-------
<img width="1667" alt="Screen Shot 2022-01-11 at 6 34 29 PM" src="https://user-images.githubusercontent.com/387249/149053645-562253d3-b75b-427e-857f-11f497023939.png"> | <img width="1680" alt="Screenshot 2022-01-11 at 6 11 53 PM" src="https://user-images.githubusercontent.com/387249/149053460-10f18bdb-c5ac-491c-b223-b0ccb458c848.png"> | <img width="1680" alt="Screenshot 2022-01-11 at 6 11 00 PM" src="https://user-images.githubusercontent.com/387249/149053408-8e523454-6510-4f3d-a735-e5c2c06582df.png"> | <img width="1680" alt="Captura de pantalla 2022-01-11 a las 18 26 29" src="https://user-images.githubusercontent.com/387249/149053767-89a2bfa6-2d54-4739-9130-fbc67d47b1e1.png">

Confirmed the link goes to `https://www.gemini.com/brave`


Confirmed these locales aren't showing the promo:

Germany | France | Iran 
----------|--------|--------
<img width="1680" alt="Bildschirmfoto 2022-01-11 um 18 16 08" src="https://user-images.githubusercontent.com/387249/149053871-dd88fff7-dace-48eb-a1b4-8627644a3404.png"> | <img width="1312" alt="Capture d’écran 2022-01-11 à 11 51 08" src="https://user-images.githubusercontent.com/387249/149054154-6afc953b-690d-4d36-a382-a0ba2817b01a.png"> | <img width="1680" alt="Screen Shot 1400-10-21 at 18 13 29" src="https://user-images.githubusercontent.com/387249/149053923-8d8e7614-0969-417a-b88b-b1262b18745e.png">
