### ISSUE TITLE
Chrome logo shown when typing "passwords" in address bar with autocomplete on

### ISSUE THREAD

**Issue by erikKeresztes** [brave/brave-browser#20223]
## Description 

When typing `passwords` in the address bar the Chrome logo will be shown in the Manage Passwords button.

## Steps to Reproduce

   1. Turn autocomplete on
   2. Type `passwords` in the address bar

## Actual result:

![image](https://user-images.githubusercontent.com/58667141/147392123-5919b1fb-a2f7-418d-8b7c-46c44a77a30e.png)

## Expected result:
The Brave logo should be shown instead.

## Brave version (brave://version info)

```
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Linux
```

**Comment by mkarolin** [comment]
Note, that his applies not only to `passwords`, but to other keywords, such as `address`, `site settings`, `private tab`, etc..

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
```
- Verified the STR from the description
Reproduced the issue in 1.34.78

**`1.34.78`**
Google SE - Normal tab | Google SE - Private tab | Brave SE -Normal tab | Brave SE -Private tab
------|------|------|------
![image](https://user-images.githubusercontent.com/38657976/148391484-c00aac31-7441-423c-bba0-31974566f5b4.png) | ![image](https://user-images.githubusercontent.com/38657976/148391533-847f8b1c-f871-48aa-9f47-46f62a1f33e1.png) | ![image](https://user-images.githubusercontent.com/38657976/148391991-5267c548-18ed-4774-9684-02e0ee6893f8.png) | ![image](https://user-images.githubusercontent.com/38657976/148392040-1bc8a871-72e9-4633-a876-c883f9385158.png)
