### ISSUE TITLE
BAT token suddenly disappeared 

### ISSUE THREAD

**Issue by Rajatk497** [brave/brave-browser#20225]
Hi, Brave Team!
I just noticed that my BAT tokens disappeared from my account.
Could you please take a look and restore my tokens!

I'm using the same email for Brave and Uphold.
So, please have a look and restore my balance.

Thanks

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by Miyayes** [comment]
Hi @Rajatk497, can you help answer these questions:

1. Were you verified with Uphold at the time this happened?
2. Did you recently reinstall your Android browser?
3. Roughly how much BAT was it? Was it your actual BAT balance, or are you referring to your estimated earnings for the month?
4. Would you be able to submit your brave://rewards-internals (general info) tab, and (event logs) tab to my email at christopher@brave.com? Thanks. Please include your username here.

**Comment by Miyayes** [comment]
Hi, I am going to redirect this to https://community.brave.com for support. That is our official support forum.
