### ISSUE TITLE
Follow up to #19796: Brave News on menu doesn't do anything

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#20221]
Issue is still reproducible. Maybe it is Android Tab only.

## Steps to reproduce 

   1. Enable Brave news
   2. Open menu
   3. Tap on Brave News, does nothing

## Actual result 
Brave News on menu doesn't do anything

## Expected result
Should load Brave news settings menu or open a new tab and focus on first article 

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

Brave v1.34.73  on Samsung Galaxy Tab S5e (Android 10.0)

cc @brave/legacy_qa @alexsafe

**Comment by alexsafe** [comment]
@srirambv I think i forgot to add this to the PR when i self-assigned. It's been fixed quite a while back

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.36.82, Chromium 98.0.4758.87` on a `Google Pixel XL` (`arm64`) running `Android 9.0.`

Steps:
1. fresh install
2. launch Brave
3. tap through onboarding
4. open `brave://flags`
5. type `news`
6. enable `Enable Brave News`
7. relaunch
8. tap on the 3-dots menu on the bottom toolbar
9. tap `Settings`
10. tap `Brave News`
11. tap to `Show Brave News`
12. tap on the `X`
13. swipe down on a new-tab page

Confirmed Brave News loaded

example | example | example | example | example
---------|----------|---------|---------|----------
![Screenshot_20220202-111041](https://user-images.githubusercontent.com/387249/152224179-998f698c-c987-48b5-a85e-4d667ab5150f.png) | ![Screenshot_20220202-111052](https://user-images.githubusercontent.com/387249/152224228-f0339b4a-2bea-40b5-8485-f9ead27bee2b.png) | 
![Screenshot_20220202-111101](https://user-images.githubusercontent.com/387249/152224285-a322e856-7464-465d-a8d6-8688844629ae.png) | ![Screenshot_20220202-111109](https://user-images.githubusercontent.com/387249/152224292-7cd76ab0-4ace-4d8d-a118-92f2a43eb989.png) | ![Screenshot_20220202-111122](https://user-images.githubusercontent.com/387249/152224293-d3038f91-d249-4527-83dc-63734927f3c8.png)
