### ISSUE TITLE
Widevine support on Android - required for sites like Spotify, Hulu, etc

### ISSUE THREAD

**Issue by vishnubhadri** [brave/brave-browser#20241]
## Description 
Spotify webplayer is not opening in brave browser version `1.33.106`

## Steps to reproduce 

   1. open [open.spotify.com](https://open.spotify.com)

## Actual result 
Spotify page is displaying **playback disabled**
Screenshot from brave version `1.33.106`  and chromium `96.0.4664.110`
![Screenshot from brave version `1.33.106` chromium `96.0.4664.110`](https://user-images.githubusercontent.com/11070758/147569834-15e06a5a-9ff5-4859-9408-e13a08515fd1.jpeg)

## Expected result
Spotify should be open. Screenshot from chrome `96.0.4664.104`
![Screenshot from chrome `96.0.4664.104`](https://user-images.githubusercontent.com/11070758/147569889-aaf51eb1-b579-4398-832f-b6c6969502ff.jpeg)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 1.33.106
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.33.106

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Can you check if autoplay is disabled under site settings? It should be enabled by default

**Comment by vishnubhadri** [comment]
Auto play is enabled.
![Screenshot_20220103-092141](https://user-images.githubusercontent.com/11070758/147898560-6d245c0e-2cc8-43cf-947a-aea87e075532.jpg)

**Comment by vishnubhadri** [comment]
> Can you check if autoplay is disabled under site settings? It should be enabled by default
Auto play is already enabled.
https://github.com/brave/brave-browser/issues/20241#issuecomment-1003854986

**Comment by ryanbr** [comment]
This is related to the DRM support/playback, https://github.com/brave/brave-browser/issues/13820

**Comment by ActualDisaster2447** [comment]
It has been 6 months since this issue was opened. Any updates?

**Comment by vishnubhadri** [comment]
as @ryanbr mentioned. it is related to DRM and Widevine. by default brave mobile browser block Widevine.

**Comment by ActualDisaster2447** [comment]
I wonder what is taking so long for them to at least give us the option to toggle DRM manually like on desktop.

**Comment by HarshPatel5940** [comment]
Still waiting for an option to enable DRM in brave mobile

**Comment by Nakul4** [comment]
Still waiting for developers to give updates on this. How long till we get the widevine solution on mobile app

**Comment by HarshPatel5940** [comment]
We are still waiting for Widevine to come in the Brave mobile version.

Getting access to some extensions in mobile versions to increase productivity.

**Comment by urbenlegend** [comment]
Just ran into this issue after corridordigital.com added DRM to all their videos as well. Would very much appreciate Widevine support on Brave Android as well.

**Comment by realnyamasege** [comment]
![IMG_20230202_224959.jpg](https://user-images.githubusercontent.com/114096807/216434901-df6f9b7c-f988-43f4-9e6b-86fba7b09855.jpg)

Hello developers, any solution to the problem?

**Comment by samvv** [comment]
Would really appreciate if this issue could be fixed. Brave is awesome but this is a real downer.

**Comment by dinosoeren** [comment]
I can't use brave to watch content I paid for, therefore switching back to chrome until this is fixed.

**Comment by vrindavan** [comment]
I just switched to Firefox for the same reason.

**Comment by vrindavan** [comment]
I switched to Firefox for the same reason @dinosoeren.

**Comment by deeppandya** [comment]
@dinosoeren @vrindavan we are adding widevine support with https://github.com/brave/brave-core/pull/18958. It would land on nightly soon.

**Comment by lukemulks** [comment]
+1 on this thread; I ran into issues playing back content purchased on YouTube in Brave as a result of not having Widevine support in Brave on Android. Having to watch that content in the YT native app on Android reminded me how much I appreciate the better UX with YT in Brave. If we support this it will make that support even better.

**Comment by alembiq** [comment]
+1

**Comment by iJosiasCastro** [comment]
Any update? We need this

**Comment by deeppandya** [comment]
> Any update? We need this

@iJosiasCastro we have the feature merged to the nightly channel. Please checkout the brave nightly application

**Comment by vrndavn** [comment]
It made it to the nightly so hopefully stable soon. Thanks!

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.60.88 
Chromium: 118.0.5993.70 (Official Build) beta (64-bit) 
Revision: ff9150ac5dd9934a7f431ddf478ad3e45ae68546
```
---------------------------

**STEPS:**
1. Fresh install and launch Brave 
2. Three-dot menu > Settings
3. Media > Widevine DRM > Verify
4. Go back to NTP and open any of these: https://corridordigital.com, https://open.spotify.com, https://hulu.com, https://tv.apple.com, https://youtube.com > Verify
5. Tap `Learn more about Widevine` > Verify
6. Go back from the support page > Tap `Allow (Relaunch Now)`
7. After Brave is relaunched go to the `Widevine` settings > Verify that the toggle switch is `ON`
8. Go back to the website > Tap any file to play > Verify
9. Refresh the page > Verify

**ACTUAL RESULTS:**
- Verified that the `Widevine DRM` toggle switch is shown in the `Settings` > `Media` and disabled by default
- Verified when opening the `Widevine required` website, a pop-up message is shown
- Verified tapping `Learn more about Widevine` is opening `How do I enable Widevine DRM on Android?` support page https://support.brave.com/hc/en-us/articles/17428756610061
- Verified when the `Widevine DRM` toggle switch is `ON`, media files are playing normally
- Verified when the `Widevine DRM` toggle switch is `ON` already, pop-up message is not shown again if refreshing the page
- Verified also when the `Widevine DRM` toggle switch is `OFF`, media files can't be played and a pop-up message is shown again if refreshing the page, and the `Don't ask again` checkbox is not selected


NOTE: 
- Some websites like `Hulu` and `YT` require you to open `Desktop site` to watch movies. The same behavior is in Chrome.
- `Netflix` is not playing for me in Chrome as well.

---------------------------

*`Widevine DRM` is `OFF`*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/91b0d69b-4439-4e74-b5f9-91540138ef28) | ![2](https://github.com/brave/brave-browser/assets/128532965/e2827ef9-b7c5-45cd-9b0b-7ff31b814dcf) | ![3](https://github.com/brave/brave-browser/assets/128532965/3145e285-f726-4789-9b56-2f4e8c4efb9f) | ![4](https://github.com/brave/brave-browser/assets/128532965/19902cc4-28ec-4b7f-b5eb-35b3e126e74e) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/6ab39fe0-b622-48ff-90c3-53a36d6beb87) | ![2](https://github.com/brave/brave-browser/assets/128532965/5b2fe1d9-eecd-4e7c-b1c6-9938ab676a62) | ![3](https://github.com/brave/brave-browser/assets/128532965/23019b12-f76e-460c-8977-56aeda492bb0) | ![4](https://github.com/brave/brave-browser/assets/128532965/d32ca1af-50d9-4641-9b40-73410a088e4c) |

*`Widevine DRM` is `ON`*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c40539de-4d13-4ba9-bc39-b3f0447988de) | ![2](https://github.com/brave/brave-browser/assets/128532965/832b57ea-8549-403c-a1e9-189c916f0b16) | ![3](https://github.com/brave/brave-browser/assets/128532965/89891f81-2ef3-4ff1-aa04-5485fd7ea5ae) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/0fcb0b7c-423a-4e6c-a33e-e1afbc015879) | ![2](https://github.com/brave/brave-browser/assets/128532965/ac64d788-0bfc-41c8-9a75-c7d8a11c1966) | ![3](https://github.com/brave/brave-browser/assets/128532965/a6a8c1c3-ff08-4240-b6d6-e9b0bd687c27) |

**Comment by foreachthing** [comment]
Works on Android, but not Windows 11:
![image](https://github.com/brave/brave-browser/assets/10420187/896c5a24-9d48-46a9-9fad-79d28c1eb42f)

Widevine is activated:
![image](https://github.com/brave/brave-browser/assets/10420187/833091b6-7e4e-4b64-ac6e-dca26036611b)

**Comment by kjozwiak** [comment]
@foreachthing I'm on `Win 11 x64` and everything seems to be working. I double checked `Netflix`, `Max` and `Spotify`. Can you try the following?

* go into `brave://settings/extensions` and disable `Widevine` (you'll need to restart the browser)
* once restarted, go into Spotify or any other website that needs Widevine (you should see a modal requesting to enable)

Once enabled, does that work? I tried it a few times on my `Win 11 x64` machine and everything seems to be working:

```
Brave | 1.62.90 Chromium: 120.0.6099.35 (Official Build) nightly (64-bit)
-- | --
Revision | 276c6d1745bff39888cedcc6aa54e9c5c35e764e
OS | Windows 11 Version 22H2 (Build 22621.2715)
```

**`Example`** | **`Example`**
----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/232d0080-abd9-4efc-b651-9bc5168ed24c) | ![image](https://github.com/brave/brave-browser/assets/2602313/e2cdfdd3-aab1-44fa-8a08-93ebeb14f5d3)

**Comment by foreachthing** [comment]
@kjozwiak , thanks for your reply. No, it does not work. Interestingly, it does work "at work" (_where I get blocked to play content but I don't see this message_). Could it be a firewall setting or something else with Bitdefender? 
I pretty much sync all settings across devices and should not have an addon messing with Brave.
Thanks again!

**Comment by 2008-sketch** [comment]
Sorry to beat a dead horse here, but I currently am stuck on a windows 11, 64 bit processer, even tried using brave beta. With widevine enabled, content protection allowed, all that stuff, and it still hasn't allowed me to play it, I went to the component section, and I found that my widevine version is 0.0.0.0, how do I even manually update that if most settings are blocked?

**Comment by kjozwiak** [comment]
> Sorry to beat a dead horse here, but I currently am stuck on a windows 11, 64 bit processer, even tried using brave beta. With widevine enabled, content protection allowed, all that stuff, and it still hasn't allowed me to play it, I went to the component section, and I found that my widevine version is 0.0.0.0, how do I even manually update that if most settings are blocked?

@2008-sketch Google had a `Widevine` outage about ~3 weeks ago as per https://github.com/brave/brave-browser/issues/50895. Maybe you ran into the above? But your post is from ~a week ago and the outage was fixed ~3 weeks ago.

If you go into `brave://components`, can you click on `Update` via `Widevine Content Decryption Module`? Hopefully that pulls the latest component. This is assuming you're still having issues.
