### ISSUE TITLE
Clicking the speaker icon on a tab playing audio does nothing

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#2025]
## Description 
When a site is playing audio, the tab that the audio is playing in will show a small speaker icon. You should be able to click this to mute the tab.  Unfortunately, that is not working on DEV and BETA channels (BETA worked with 0.56.7, RELEASE works fine). If you right click and choose `Mute` from the context menu, it does work

## Test plan / Steps to Reproduce

   1. Visit a site that plays audio (ex: http://beirutnights.com/)
   2. Ensure audio is playing and that speaker icon shows for the tab
   3. Try clicking the speaker icon and notice that nothing happens

## Actual result:
Speaker button does absolutely nothing

## Expected result:
Speaker button should toggle (showing a speaker with a cross through it)

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 0.57.4 Chromium: 71.0.3578.31 (Official Build) dev (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Mac OS X

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta(64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
ONLY reproduces on DEV and BETA. RELEASE work fine

**Comment by simonhong** [comment]
This feature was removed from upstream.
https://chromium-review.googlesource.com/c/chromium/src/+/1241813

**Comment by bsclifton** [comment]
🙀

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/is-there-a-way-to-retain-this-flag-enable-tab-audio-muting-which-is-removed-from-chromium-71/36982/2

**Comment by stevenchu** [comment]
I dunno why I can't reply to this topic on community.brave.com so will reply here. 

This is still happening, and I did not get an audio icon either.

I just had ROBOTIZED NARRATOR VOICES blast at 100% volume in my apartment with no way to shut it off.

No mute tab, no mute site. No clicking on the spam CNET video to block or disable it.

<img width="981" alt="brave has no mute button for annoying sites" src="https://user-images.githubusercontent.com/1848517/48299879-83637100-e4a1-11e8-9dcb-e1cce6e2142d.png">

**Comment by srirambv** [comment]
@stevenchu  You are on the older muon browser which is deprecated. Request you to update tot he new Brave browser.

**Comment by Liunkae** [comment]
+1 from #2145.

**Comment by RyanJEC** [comment]
I really need this functionality. how long do we have to wait I can't revert the update!

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/shutting-off-sound-with-multiply-taps/39767?u=eljuno

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/mute-tabs-individually-and-with-one-click-like-on-firefox/41100?u=eljuno

**Comment by lukejackson958** [comment]
please bring this feature back!

**Comment by pemartins1** [comment]
+1

This is really useful.

**Comment by RasterCrow** [comment]
+1, just switched to brave and I really miss this functionality.

**Comment by JulianoFL** [comment]
+1, i use Brave is the best browser here, but without this function is really "annonying" for me to use it.

**Comment by Qbzomatique** [comment]
+1, just went from Firefox to Brave today and this is a really annoying issue.

**Comment by garretlaxton** [comment]
+1, only flaw with this browser for me.

**Comment by DatXFire** [comment]
+1 really good feature

**Comment by batmonkey** [comment]
+1 Please re-implement this feature. This is the only feature stopping me from moving away from Chrome forever

**Comment by CrisBD** [comment]
Still not working in brand-new Brave release updated Monday, 2019/07/08:

Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

using MacOS 10.10.5 on 8 gig 2.6 GHz Intel Core i5 MacMini

**Comment by simonhong** [comment]
@CrisBD The fix(https://github.com/brave/brave-core/pull/2861) is in review :)

**Comment by webjive** [comment]
Can confirm. Just installed Brave and the Mute/Unmute on the tab doesn't work. Had to install an extension to control this for now.

**Comment by bsclifton** [comment]
Code merged - our next Nightly build will have this fixed 😄👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux

* Verified click on speaker icon mutes the audio from the tab
* Verified click on speaker icon mutes the audio from a pinned tab
* Logged #5837 for context menu on pinned tab while audio is playing

**Comment by NotAmaan** [comment]
Can this be disabled with a flag or something? I usually have some YouTube music stream playing while I work and tend to Pin that tab. Now I can never switch to the pinned tab playing audio without muting it once or twice.

**Comment by webjive** [comment]
There is a new Chrome flag (can't remember the site) out that when enabled puts a play/stop button for sound on any running background tab. Click it and it shows the tab name and stops playback.

**Comment by simonhong** [comment]
@NotAmaan @webjive hmm, we don't have a flag for disable it now.
@rebron how should we handle this? My idea is don't show speaker button if tab width is small or pinned.

**Comment by webjive** [comment]
The Chrome flag worked for me.
![Screen Shot 2019-10-08 at 6 41 44 AM](https://user-images.githubusercontent.com/286935/66392889-b86c9200-e996-11e9-9284-4c52285303af.jpg)

**Comment by bsclifton** [comment]
Good call on hiding for pinned tab - I created a new issue to track this:
https://github.com/brave/brave-browser/issues/6358
