### ISSUE TITLE
google.com shows as Not yet verified, but should be Verified Creator (Uphold) on staging

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20250]
## Description 

google.com shows as `Not yet verified`, but should be `Verified Creator` (Uphold) on staging

Found while testing https://github.com/brave/brave-browser/issues/19458 on Android.

## Steps to reproduce 

   1. install `1.34.74`
   2. tap through onboarding
   3. tap on the 3-dots menu
   4. tap on `Settings`
   5. tap on `About Brave`
   6. tap on `Application version` a few times
   7. tap on the now-present `Developer options` menu item
   8. enter the QA code
   9. tap on `Use Rewards staging server`
   10. tap `Later`
   11. tap on `Verbose Logs for Ad-Rewards`
   12. tap on `Relaunch now`
   13. load `google.com`
   14. tap on the BAT icon in the URL bar
   15. tap `Start using Brave Rewards`
   16. tap `Skip`
   17. tap `Done`
   18. tap on the `CLAIM` button to get the UGP grant
   19. tap on the BAT icon in the URL bar
   20. look at the states for `google.com`

## Actual result 
`Not yet verified`

![Screenshot_20220104-115635](https://user-images.githubusercontent.com/387249/147604149-c6405451-8921-4ca4-a2a4-c3cb5b8bd50a.png)

## Expected result
Should be a `Verified Creator` with Uphold (as it is on desktop)

<img width="1312" alt="Screen Shot 2021-12-28 at 12 02 11 PM" src="https://user-images.githubusercontent.com/387249/147604276-6eafb04d-0cfd-4549-ad33-4b385f2e53d4.png">

## Issue reproduces how often 
100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `Android 9.0`
   
## Brave version
`1.34.74, Chromium 97.0.4692.56`

Original Slack thread here: https://bravesoftware.slack.com/archives/CNH9Q6REV/p1638821312113700

cc @deeppandya @LaurenWags @Miyayes

**Comment by Miyayes** [comment]
Noting here as well: I think this is because google.com is actually coming up as bitFlyer-verified on staging, and 1.34 cannot detect bitFlyer-verified creators (and instead shows any to be `unverified creator`).
