### ISSUE TITLE
Make token icon URI used

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20256]
Currently custom tokens have a `logo` URI that is unused. We should make this work so it shows the icon correctly.

**Comment by Feliphegomez** [comment]
whats link assets wallets ?

**Comment by bbondy** [comment]
Closed by https://github.com/brave/brave-core/pull/12003

**Comment by topaciotrade** [comment]
Why was support for logos never added? Is only CoinGecko supported?
wallet_watchAsset is a standard implemented by other wallets, blockchains, and libraries like ethers.js.
Why hasn't support for the image parameter been added?"
```js

    const configToken = {
      type: 'ERC20',
      options: {
        symbol: tokenSymbol,
        decimals: tokenDecimals,
        image: tokenImage,
        address: addressToken
      }
    }

    provider.send('wallet_watchAsset', configToken)
```

**Comment by topaciotrade** [comment]
Key Technical Clarifications:

    Brave ignores the image parameter in wallet_watchAsset intentionally, as confirmed in their GitHub issues.

    They rely exclusively on centralized registries (CoinGecko/CoinMarketCap) for logos.

    This violates the EIP-747 standard which explicitly defines the image field.
