### ISSUE TITLE
Missing Bulgarian translation when `Top Sites` is selected in dashboard

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#20258]
## Description 

Noticed Bulgarian translation is missing when `Top Sites` is selected via `Customize Dashboard`.

## Steps to Reproduce

   1. Configure Brave to be displayed in Bulgarian.
   2. Open the new tab page, and click on `Customize Dashboard`.
   3. Click on `Top Sites`.

## Actual result:

![Untitled](https://user-images.githubusercontent.com/20608253/147634702-4725bdab-c41f-4e4f-8ccb-d97aacd1b338.png)

## Expected result:
Instead of only `T`, it should be `Топ сайтове`.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

<html>
<body>

Brave | 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

<html>
<body>

Brave | 1.34.74 Chromium: 97.0.4692.56 (Official Build) beta (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

<html>
<body>

Brave | 1.35.63 Chromium: 97.0.4692.56 (Official Build) nightly (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CC: @mkarolin

**Comment by mkarolin** [comment]
Thank you for reporting @Tonev 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.34.80 Chromium: 97.0.4692.71 (Официално издание) (64 бита)
-- | --
Ревизия | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
ОС | Windows 10 Version 21H2 (Build 19044.1415)

```

![image](https://user-images.githubusercontent.com/38657976/148401510-a3e4f43c-1b52-405d-882d-f9c20331b659.png)

**Comment by srirambv** [comment]
Removing Android label as this is desktop specific setting
