### ISSUE TITLE
Prevent transaction confirmation if estimated gas limit is zero

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20259]
If the gas limit is zero, we should disable the "Confirm" button with an error that indicates the user that there's something wrong with the gas estimation and they should manually specify a value.

<img width="256" src="https://user-images.githubusercontent.com/3684187/147637298-3d1b6542-80c9-40cf-9288-f113b83d691f.png">

⚠️ This is a safety mechanism to prevent issues with signing/broadcasting transactions. Since it can occur very rarely and cannot be reproduced easily, I've added the `QA/No` label.

**Comment by kyoobey** [comment]
how can i opt out ?
