### ISSUE TITLE
Brave news opt-in card wrong positioning when switching between NTP & tab manager

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20267]
## Description 

When viewing the `Tab Manager` and then returning to the NTP, the Brave News opt-in card gets moved a lot further down the NTP page. A user in this case would need to scroll down to find the opt-in card. Creating a new NTP will reset the position. However, it's still positioned incorrectly as per https://github.com/brave/brave-browser/issues/20266.

## Steps to reproduce 

   1. download/install Brave and ensure that Brave News is visible/enabled in this build
   2. ensure that you're currently viewing a NTP
   3. open the `Tab Manager` and go back to the NTP and you'll notice that the opt-in card gets moved down the NTP

## Actual result 

https://user-images.githubusercontent.com/2602313/147792098-06a3ad54-0326-4614-aef3-c64c92e7bd9c.mp4

## Expected result

The Brave News opt-in card shouldn't be moving further down but should appear in the same position as when opening a NTP.

## Issue reproduces how often 

100% reproducible using the STR/Cases mentioned above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` (but Brave News needs to be enabled via the flag)
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details

   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 12`
   
## Brave version

`1.36.5 Chromium: 97.0.4692.56`

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.36.77, Chromium 98.0.4758.66` on a `Google Pixel XL` running `Android 9.0`.

Followed the original steps above, and confirmed correct opt-in dialog positioning, when switching between Brave News tabs.


https://user-images.githubusercontent.com/387249/151651919-eab599cb-38a5-47ab-963d-80359fa8ca75.mp4
