### ISSUE TITLE
Brave News opt-in modal & feed appearing too high on NTP (positioning needs to be fixed)

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20266]
## Description 

The peaking card to opt-in into Brave News should appear a bit lower like it does on `iOS`. It's currently pretty high and takes a  lot of NTP space. This is a bigger issue when we comes to NTP SI.

## Steps to reproduce 

   1. launch Brave and ensure that Brave News is enabled (meaning via the flag)
   2. open a NTP and notice the incorrect positioning
   3. enable Brave News so the feed is visible (notice the incorrect positioning again)

## Actual result 

**`Example (Android)`** | **`Example (Android)`**
---------------|-----------------
![Screenshot_20211230-174441](https://user-images.githubusercontent.com/2602313/147792774-5ff98e1b-52e0-4c40-960f-094afdd44337.png) |  ![Screenshot_20211230-174451](https://user-images.githubusercontent.com/2602313/147792775-a1071fea-e522-4e77-80a0-bc7d34ba0df5.png)

## Expected result

**`Example (iOS)`** | **`Example (iOS)`**
---------------|-----------------
![IMG_0504](https://user-images.githubusercontent.com/2602313/147792962-5853d8c9-0097-4f4c-a6ab-2bf2f3133854.png) | ![IMG_0505](https://user-images.githubusercontent.com/2602313/147792965-30d472dc-6b9e-4a5b-8031-0fd53a74a8d8.png)

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` (However, needs to be enabled via the flag)
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 12`
   
## Brave version

`1.36.5 Chromium: 97.0.4692.56`

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.36.66, Chromium 98.0.4758.66` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

Steps:
1. installed `1.36.66`
2. launched Brave
3. restarted to pick up the `Brave Talk` seed via Griffin
4. tapped through onboarding
5. opened a new-tab page
6. swiped down
7. noted the position of the opt-in dialog
8. tapped on `Turn on Brave News`
9. noted the position of the first article

example | example | example | example
----------|-----------|----------|-----------
![Screenshot_20220125-230521](https://user-images.githubusercontent.com/387249/151120740-7a02c652-e462-4c10-b763-d325913d9bd3.png) | ![Screenshot_20220125-230653](https://user-images.githubusercontent.com/387249/151120901-5d2862e7-e999-46da-8a15-89957f1c1bfd.png) | ![Screenshot_20220125-230603](https://user-images.githubusercontent.com/387249/151120905-40c2a4ea-c049-4b81-a8a6-2b14c3e1de35.png) | ![Screenshot_20220125-230635](https://user-images.githubusercontent.com/387249/151120906-1e978e32-34af-475f-9bed-65014435ea0f.png)
