### ISSUE TITLE
Indefinitely spinning loading graphic due to uncaught null feed parameter 

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20272]
## Description 

Indefinitely spinning loading graphic due to uncaught null feed parameter 

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open a new-tab page
   4. click on `Customize`
   5. disable all sources via the `Brave News` card/link
   6. open Developer Tools, Console tab
   7. look at the exception thrown

## Actual result:

```
brave_new_tab.bundle.js:1956 Uncaught Error: Received BraveNewsController_GetFeed_ResponseParams with invalid null field "feed"
    at r.internal.Decoder.decodeStructInline (brave_new_tab.bundle.js:1956:12978)
    at r.internal.interfaceSupport.InterfaceRemoteBase.onMessageReceived (brave_new_tab.bundle.js:1956:36230)
    at r.internal.interfaceSupport.Endpoint.onMessageReceived (brave_new_tab.bundle.js:1956:31278)
    at r.internal.interfaceSupport.Router.onMessageReceived_ (brave_new_tab.bundle.js:1956:28783)
    at r.internal.interfaceSupport.HandleReader.read_ (brave_new_tab.bundle.js:1956:41093)
```

<img width="1537" alt="Screen Shot 2021-12-30 at 4 55 22 PM" src="https://user-images.githubusercontent.com/387249/147796989-0424f0c1-a2be-482b-b785-9ba1d8952744.png">

## Expected result:

No exception; some kind of messaging/UX to remind the user to enable more sources?

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.36.5 Chromium: 97.0.4692.56 (Official Build) nightly (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 12.2 (Build 21D5025f)

cc @petemill @mattmcalister @kjozwiak

**Comment by jonathansampson** [comment]
Note, I am able to reproduce this after enabling _only_ one item.

1. Disable all sources
2. Enable _Brave Blog_ alone

Issue reproduces.

**Comment by mattmcalister** [comment]
Resolved with Settings upgrade. Closing.
