### ISSUE TITLE
Top Sites and Favorites are still clickable when not visible, with content scrolled up

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20273]
## Description 

Top Sites and Favorites are still clickable when not visible, with content scrolled up

This is super minor, but a fun bug to find 👍 

## Steps to Reproduce

   1. new profile
   2. open a new-tab page
   3. enable Brave News
   4. scroll down
   5. scroll back up to just below where Top Sites / Favorites are (now hidden)
   6. move the mouse/pointer around and see that there are links

## Actual result:

Although no longer visible, the Top Sites / Favorites are still clickable

![opacity](https://user-images.githubusercontent.com/387249/147798206-07d26ad6-a766-4c1e-b645-5b7c3415ce9d.gif)

## Expected result:

If they're no longer visible, perhaps we shouldn't link them

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.34.76 Chromium: 97.0.4692.56 (Official Build) (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)

**Comment by mattmcalister** [comment]
Closing
