### ISSUE TITLE
Don't fetch prices for assets with a 0 balance

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20280]
## Description 
To better optimization and to prevent unnecessary api calls, we should not fetch prices for a users `visibleAssets` that have 0 balance.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.98 Chromium: 98.0.4758.72 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from </li>
         <li>Verified there is no fetch price call done to ratios server when the wallet balance is 0 on a new wallet</li>
         <li>Verified selecting ETH performs a fetch price call even when ETH balance is 0</li>
         <li>Verified selecting BAT performs a fetch price call even when BAT balance is 0 </li>
         <li>Verified locking and unlocking the wallet on a zero balance wallet doesn't do any more fetch calls</li>
         <li>Verified quit and relaunch browser doesn't do a fetch call on a zero balance wallet</li>
         <li>Verified if there is wallet balance then appropriate call is done on the above scenarios to get the price balance</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Clean Wallet Launch
      </td>
      <td><img width=1200 src=>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151917953-d3335e3e-ba18-4b7f-a7e0-891016b0ac67.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151918753-980c646e-ae48-4d19-bb4a-8e6420ec6423.png>
      </td>
   </tr>
   <tr>
      <td>ETH Fetch Price
      </td>
      <td><img width=1200 src=>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151918009-38d3e4e3-663a-4a6c-af15-430f1502d6b1.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151918726-3b9ebfa1-988d-4b22-b7aa-1306a13d10af.png>
      </td>
   </tr>
   <tr>
      <td>BAT Fetch Price
      </td>
      <td><img width=1200 src=>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151918101-b6aea3d8-0c4d-406c-ab00-43ac91e2b3ef.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151918688-69f317eb-954f-4cf1-aaf7-ea86a8ca553e.png>
      </td>
   </tr>
   <tr>
      <td>Lock Wallet/Restart browser
      </td>
      <td><img width=1200 src=>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151918249-d6381278-af65-4617-b9ad-3fc7166542c0.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/151918645-a8e002da-8fb5-4f2b-b478-eba4318c6d7e.png>
      </td>
   </tr>
</table>
