### ISSUE TITLE
personal_sign should accept hex message without 0x prefix too

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20283]
After signing in on the Dapp https://studio.manifold.xyz/ it tries to sign data with personal sign without 0x prefix for the hex data. 

See the implementation of personal_sign here:
https://github.com/ethereum/go-ethereum/pull/2940/files#diff-d0d5842eca210323f32aeb8c0710124e1bfd1a19f732c7ed5ee7519a318a405aR40

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.34.78 Chromium: 97.0.4692.56 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21A559)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified connect wallet continues and connects successfully without going back</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/148082010-a4cbd06f-357d-409d-8a23-7f12578f3629.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/148075944-72e695b7-7505-4d8f-aafe-2f11af6ee55d.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/148076220-1ec30da8-7580-4b8f-8ec9-251719ae10a9.mov>
      </td>
   </tr>
</table>
