### ISSUE TITLE
sign typed data should accept string values for uint* and int* types

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20282]
MM allows for typed data with `uint*` and `int*` types to have string values. 

Snapshot a dapp for governance and voting on proposals does this. Instead of on chain it just signs data for voting.
https://snapshot.org/#/bbondy.eth/proposal/0xe8d6d011fd1ced4f7b9ef5de19dcd47ac728d9a3553fa60dcb73ecf6ad768b61 (edited)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.34.78 Chromium: 97.0.4692.71 (Official Build) (arm64)
-- | --
Revision | `adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}`
OS | macOS Version 12.1 (Build 21C52)

- Verified steps from issue description
- Verified able to cast votes without issues. [Confirmation](https://cloudflare-ipfs.com/ipfs/QmSarr1KF23RGTdV5FmmXUknCmpgtpdrosf78KLgWAk4wn)
