### ISSUE TITLE
special characters in YT channel names not appearing correctly under Rewards panel

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2028]
## Description 

YT channels that use special characters in their names are not being displayed correctly in the Rewards panel.

## Steps to Reproduce

   1. launch the latest brave (`0.56.8 Chromium: 70.0.3538.77` in this case)
   2. enable rewards via `brave://rewards`
   3. visit https://www.youtube.com/channel/UC5v8uRCMdzHXgEOZC4rtbXg
   4. click on the `BAT` icon in the URL to display the `Rewards` panel

You'll notice that it's being displayed as `D\u0026E miniature and board gameson YouTube` instead of `D&E miniature and board games`

## Actual result:

![screen shot 2018-11-05 at 7 19 51 pm](https://user-images.githubusercontent.com/2602313/48116792-2e232780-e235-11e8-8679-fbc44627a319.png)

## Expected result:

Should display `D&E miniature and board games` instead of `D\u0026E miniature and board gameson YouTube`.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Yes, reproducible under `dev` and `beta`

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1735

![image](https://user-images.githubusercontent.com/34715963/54252151-0aa51c00-454a-11e9-8271-2023bea72417.png)
![image](https://user-images.githubusercontent.com/34715963/54252177-214b7300-454a-11e9-83f0-bf05c37d99f4.png)
