### ISSUE TITLE
Wallet summary is not centre aligned and doesn't have bottom padding 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20297]
## Description 
Wallet summary is not centre aligned and doesn't have bottom padding 

## Steps to reproduce 

   1. Install nightly build
   2. Open `chrome://rewards`
   3. Wallet summary is left aligned and doesn't have any bottom padding

## Actual result 
<img width=500 src=https://user-images.githubusercontent.com/17010094/147902967-086c6ddb-dcff-4758-b09a-eb163f35c110.png>

## Expected result
Should be centre aligned and have enough padding on top and bottom so it doesn't look like its missing margin

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.36.9

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @emerick @Miyayes

**Comment by emerick** [comment]
@srirambv Which tablet do you use for testing purposes?

**Comment by srirambv** [comment]
@emerick This issue happens on Samsung Tab A

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.104 x64 build
- Verified wallet summary is properly stretched out on the rewards page
![image](https://user-images.githubusercontent.com/17010094/155368691-60f1ba7a-2fc2-4164-8851-6174909493a3.png)
