### ISSUE TITLE
[speedreader] Bad layout for nationalpost.com

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#20300]
https://nationalpost.com/news/canada/canadas-public-health-agency-admits-it-tracked-33-million-mobile-devices-during-lockdown
![Screenshot from 2022-01-03 19-34-40](https://user-images.githubusercontent.com/3109556/147931074-7e249a45-c6d3-49b3-b6b6-85eb7ec565f3.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.35 Chromium: 105.0.5195.102 (Official Build) nightly (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:
1. installed `1.45.35`
2. launched Brave
3. loaded `https://nationalpost.com/news/canada/canadas-public-health-agency-admits-it-tracked-33-million-mobile-devices-during-lockdown`
4. clicked on the `Speedreader` icon
5. compared the page with `1.43.89`

1.43.89 | 1.45.35
--------|--------
<img width="1312" alt="Screenshot 2022-09-08 at 3 26 51 PM" src="https://user-images.githubusercontent.com/387249/189237060-d2494ed8-722a-45a9-85ee-08282c65c390.png"> | <img width="1065" alt="Screenshot 2022-09-08 at 3 27 04 PM" src="https://user-images.githubusercontent.com/387249/189237061-821d9938-800c-4a64-a65e-9b913687b057.png">
