### ISSUE TITLE
Enable sending crash reports by HangWatcher using Griffin

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#20304]
Security review: brave/security#659
The description was changed here: https://github.com/brave/brave-browser/issues/19822

The feature is already enabled by default in the code, but the params should be adjusted to enable sending crash reports.
io_thread_log_level = 2
ui_thread_log_level = 2
threadpool_log_level = 2

Steps:
1. nightly, desktops only, 50%.

**Comment by kjozwiak** [comment]
Close and moved this into `1.36.x` as we pushed this out to Nightly using Griffin via https://github.com/brave/brave-variations/pull/207. Labelled as `QA/No` as it was verified on the Nightly channel via https://github.com/brave/brave-variations/pull/194#issuecomment-1007705716. As discussed, @iefremov & @atuchin-m will keep an eye and ensure reports are being submitted correctly.

Settings change re: Brave sending both crashes & hangs was also verified by QA via https://github.com/brave/brave-browser/issues/19822#issuecomment-1007566811 & https://github.com/brave/brave-browser/issues/19822#issuecomment-1009483354.
