### ISSUE TITLE
Cookie list default flag doesn't work in some cases

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#20308]
Followup to https://github.com/brave/brave-core/pull/11621

@stephendonner discovered that the cookie list default flag implementation was not working. It turns out the implementation from https://github.com/brave/brave-core/pull/11621 only works as expected for users who have enabled and disabled the cookie list in the past.

**Comment by stephendonner** [comment]
Verification `PASSED` using 

Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)


See notes over in https://github.com/brave/brave-browser/issues/20126#issuecomment-1007782828.
