### ISSUE TITLE
panel onboarding for Japan region is showing some incorrect slides

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20309]
## Description 

Onboarding for Japan region is incorrectly showing AC information on panel (narrow) view of onboarding:
* Quick tour shows AC slide when it should not.
* Start using Brave Rewards tour shows AC slide and Settings slide (containing AC budget setting), when it should not.

This was last working with 1.30.89, and is broken in 1.31.87. I think maybe it's related to the work done with https://github.com/brave/brave-browser/issues/14602, but I am not sure.

Also note, the "wide" view (visible from brave://rewards page) does not have this problem, it is specific to the "narrow" view, only visible from the panel.

## Steps to Reproduce

pre-req: be set to Japan region
   1. Clean install
   2. View quick tour for rewards onboarding from panel
   3. You will see AC slide (example 1), if you complete the tour you will see Settings slide is not available
   4. Reset profile
   5. Select "Start using Brave Rewards" from panel 
   6. You will see AC slide (example 1) and Settings slide with AC setting (example 2)
   7. If you repeat these steps and use brave://rewards page, not the panel, the issue does not reproduce

## Actual result:

Example 1 - AC slide (narrow) | Example 2 - Settings slide (narrow) 
----- | -----
<img width="1192" alt="Screen Shot 2022-01-03 at 13 48 16" src="https://user-images.githubusercontent.com/28145373/147968107-98a4e3fa-46e2-437e-a198-657323a7c481.png"> | <img width="1190" alt="Screen Shot 2022-01-03 at 13 48 25" src="https://user-images.githubusercontent.com/28145373/147968129-f8a4e0bc-8d93-42d4-b3be-6cd3470c2836.png">

## Expected result:

Per the initial implementation of this, neither slide should be available. However, Android was able to implement the Settings slide w/o AC budget setting (per https://github.com/brave/brave-browser/issues/20202). Perhaps this should be done on desktop as well. cc @Miyayes to make this determination.

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.31.x, 1.32.x, 1.33.x, 1.34.x, 1.35.x, 1.36.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 1.33.x, was last working with 1.30.89. Broken in 1.31.87
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @brave/rewards-client

**Comment by GeetaSarvadnya** [comment]
The issue is reproduced in 1.35.x from the BR panel:

AC slide | Settings slide
------|-----
![image](https://user-images.githubusercontent.com/38657976/148742491-ced76224-0290-4e97-91da-2a63a9146e3e.png) | ![image](https://user-images.githubusercontent.com/38657976/148742627-de492ea6-6ca9-4797-a4a7-717c5b95c26e.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.84 Chromium: 98.0.4758.87 (Official Build) dev （x86_64）
-- | --
変更履歴 | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS バージョン12.3（ビルド21E5196i）

Followed the original steps to reproduce.

* Confirmed there are now 6 slides, vs. 8 before
* Confirmed the previously 4th, `Autocomplete` slide: `Giving back made...` and 7th: `Lastly, let's get you...` slides were no longer present in the onboarding tours for Rewards.

`Dark` theme (`English`):

`slide 1` | `slide 2` | `slide 3` | `slide 4` | `slide 5` | `slide 6` | `slide 7`
---------|----------|----------|--------|----------|----------|---------
<img width="1312" alt="Screen Shot 2022-02-03 at 18 25 44" src="https://user-images.githubusercontent.com/387249/152478454-7356e6ef-361e-4f35-a01a-41f165236fe7.png"> | <img width="1312" alt="Screen Shot 2022-02-03 at 18 25 24" src="https://user-images.githubusercontent.com/387249/152478092-71264481-9e21-493f-a391-3746a3f34df2.png"> | <img width="1312" alt="Screen Shot 2022-02-03 at 18 25 27" src="https://user-images.githubusercontent.com/387249/152478122-efc57d98-ff16-468a-a0aa-5a257100f360.png"> | <img width="1312" alt="Screen Shot 2022-02-03 at 18 25 30" src="https://user-images.githubusercontent.com/387249/152478169-90d28525-8e0f-4b0c-b6f0-cd7b9ae9bdf4.png"> | <img width="1312" alt="Screen Shot 2022-02-03 at 18 25 33" src="https://user-images.githubusercontent.com/387249/152478241-47e6dd95-9453-47fc-817e-3d927d6470a7.png"> | <img width="1312" alt="Screen Shot 2022-02-03 at 18 25 36" src="https://user-images.githubusercontent.com/387249/152478281-89ce12b2-68c3-4561-8186-4f78921eb9a7.png"> | <img width="1312" alt="Screen Shot 2022-02-03 at 18 26 04" src="https://user-images.githubusercontent.com/387249/152478349-b3152a72-887d-4e6b-9fe7-2ccd0cac6c04.png">

`Dark` theme (`Japanese`):

`slide 1` | `slide 2` | `slide 3` | `slide 4` | `slide 5` | `slide 6` | `slide 7`
---------|----------|----------|--------|----------|----------|---------
<img width="1312" alt="スクリーンショット 2022-02-03 21 49 14" src="https://user-images.githubusercontent.com/387249/152479475-d8555081-f53e-4306-84ad-c57daa29a014.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 49 19" src="https://user-images.githubusercontent.com/387249/152479479-39db8868-b938-4e6b-8a83-f32a96533cdc.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 49 22" src="https://user-images.githubusercontent.com/387249/152479482-d2967d4f-38cb-47e2-adff-cb40493da450.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 49 25" src="https://user-images.githubusercontent.com/387249/152479486-4c70ba0f-4cd1-4b5a-9fd6-a16219b7b855.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 49 27" src="https://user-images.githubusercontent.com/387249/152479488-61794f07-8102-430e-8c2e-96ec8310e01a.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 49 29" src="https://user-images.githubusercontent.com/387249/152479489-906dbcd1-60e1-47fb-a1c1-1b70aa518f35.png"> |<img width="1312" alt="スクリーンショット 2022-02-03 21 49 31" src="https://user-images.githubusercontent.com/387249/152479491-15b8e408-6b1c-41f8-adab-fa097a0efe8b.png">


`Light` theme (`Japanese`):

`slide 1` | `slide 2` | `slide 3` | `slide 4` | `slide 5` | `slide 6` | `slide 7`
---------|----------|----------|--------|----------|----------|---------
<img width="1312" alt="スクリーンショット 2022-02-03 21 56 10" src="https://user-images.githubusercontent.com/387249/152479967-ede01084-df2c-41ad-80d3-78b922814621.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 56 15" src="https://user-images.githubusercontent.com/387249/152479973-88e4e648-1ff1-4309-9d42-b297cc5ad3b8.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 56 24" src="https://user-images.githubusercontent.com/387249/152479985-fcc989ee-e86b-4618-af72-0232e5b2303f.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 56 33" src="https://user-images.githubusercontent.com/387249/152479987-5f1628c5-7066-4406-a669-bd3bc95263a9.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 56 36" src="https://user-images.githubusercontent.com/387249/152479988-60b216cf-3bef-4570-8aa3-0c30cafff84a.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 56 39" src="https://user-images.githubusercontent.com/387249/152479990-850beaa6-8a3c-4073-8ade-88a020d2f1c2.png"> | <img width="1312" alt="スクリーンショット 2022-02-03 21 56 41" src="https://user-images.githubusercontent.com/387249/152479992-42cfa054-b5fa-468c-9b1e-7e17d5064db9.png">
