### ISSUE TITLE
[Android] selecting "Start using Brave Rewards" from chrome://rewards doesn't show onboarding tour

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20307]
## Description 

Visiting chrome://rewards prior to enabling rewards on Android shows an intro screen which leads to onboarding. However, if you tap on "Start using Brave Rewards", no onboarding is shown.

Note, if you tap on "Take a tour", the panel opens and shows onboarding tour. I think we would want "Start using Brave Rewards" to open the panel and show the tour, but cc @Miyayes to make that call.

Found while testing https://github.com/brave/brave-browser/issues/20202.

## Steps to reproduce 

1. Clean install
2. Navigate to chrome://rewards page
3. Tap on "Start using Brave Rewards"

## Actual result 

No onboarding tour is shown

## Expected result

Onboarding tour to be shown (probably from panel)

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  yes 1.33.x
- Can you reproduce this issue with the current Play Store Beta version?  unsure, probably yes
- Can you reproduce this issue with the current Play Store Nightly version? yes 1.36.x

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.33.x, 1.36.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes

**Comment by Miyayes** [comment]
After Rewards is enabled, we can just open up the dropdown panel, which should reveal the onboarding tour.

**Comment by LaurenWags** [comment]
Verified passed with `1.35.81 Chromium: 97.0.4692.71` on Google Pixel 3 XL running Android 12.

Confirmed text visible on brave://rewards and panel initial onboarding slides for both light and dark themes.
Note - onboarding is not visible on chrome://rewards page. This was discussed in https://bravesoftware.slack.com/archives/C0816QH3R/p1641901934054500 and https://bravesoftware.slack.com/archives/C0816QH3R/p1641898139052900. It will be resolved with chrome:// --> brave:// redirect when https://github.com/brave/brave-browser/issues/16565 is solved.

Dark theme:
brave://rewards | Panel
----- | -----
![1](https://user-images.githubusercontent.com/28145373/149589989-05569e87-4429-471d-ad2a-d1093aba83ea.png) | ![2](https://user-images.githubusercontent.com/28145373/149589996-1beb922b-36e9-4c38-af36-a5ee18c13915.png)

Light theme:
brave://rewards | Panel
----- | -----
![3](https://user-images.githubusercontent.com/28145373/149590013-a60575fe-dbe2-4ef0-8141-b53ba8c7a4ff.png) | ![4](https://user-images.githubusercontent.com/28145373/149590022-507c79ee-7084-4bf1-9ea1-f4066de332f5.png)
