### ISSUE TITLE
Opt-in card close button has wrong behaviour

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20312]
## Description 

The opt-in card for news should have the same behaviour as the iOS app:

- tapping on the close icon ("X") should remove the opt-in card from view and display a normal NTP (the image credits should be in their normal positions) and the only way to turn on news should be from the news settings.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Looks like https://github.com/brave/brave-browser/issues/20271 was filed first, but was missed, so forward-duping 👍

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.36.47, Chromium 97.0.4692.71` on a `Google Pixel XL`, `Android 9.0`.

1. installed `1.36.47`
2. launched Brave
3. restarted (to pick up Griffin changes to enable Brave News)
4. opened a new-tab page
5. swiped down
6. confirmed I saw the `Turn on Brave News` opt-in dialog, with `X` close widget on the top right
7. tapped on the `X`
8. confirmed the dialog disappeared
9. swiped down; confirmed neither the opt-in dialog nor Brave News feed shows up
10. tapped on the 3-dots menu
11. tapped on `Settings`
12. tapped on `Brave News`
13. tapped to toggle `Turn on Brave News` on, which also makes `Show Brave News` appear, toggled to `ON`
14. confirmed Brave News displayed after swiping down again on a new-tab page
15. tapped on the 3-dots menu
16. tapped on `Settings`
17. tapped on `Brave News`
18. tapped to toggle `Show Brave News` off
19. confirmed NO Brave News displayed after swiping down again on a new-tab page

example | example | example | example
---------|----------|---------|----------
![Screenshot_20220119-112746](https://user-images.githubusercontent.com/387249/150201658-fe69dbfc-7306-46c1-a9cb-4ce024b8b80c.png) | ![Screenshot_20220119-112755](https://user-images.githubusercontent.com/387249/150201728-a3520193-ebd9-42df-ac5e-c22bdc3ce108.png) | ![Screenshot_20220119-112805](https://user-images.githubusercontent.com/387249/150201889-fc138a48-c331-4f71-998c-bc2cf4caa158.png) | ![Screenshot_20220119-112812](https://user-images.githubusercontent.com/387249/150201813-687cf78a-3c07-40d3-ae6b-f0f88e046ac7.png)


example | example | example | example
---------|----------|---------|---------
![Screenshot_20220119-112832](https://user-images.githubusercontent.com/387249/150202059-df3242e7-2120-45ff-b092-e73b0d010f6d.png) | ![Screenshot_20220119-112841](https://user-images.githubusercontent.com/387249/150202748-6cd64fb6-2f94-44d7-9d03-dbefe927dead.png) | ![Screenshot_20220119-112846](https://user-images.githubusercontent.com/387249/150202787-7c394f10-d1cc-476e-bdca-abd5b5dd77cb.png) | ![Screenshot_20220119-112851](https://user-images.githubusercontent.com/387249/150202833-4b0a8294-f98e-4e21-8f37-24097fb7e3e8.png)
