### ISSUE TITLE
Percentage selector remains selected when input value is changed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20315]
## Description 

Percentage selector remains selected when input value is changed

## Steps to Reproduce

   1. Open Swap/Send screen
   2. Select a fixed percentage value so that the input field is populated based on wallet balance
   3. Edit the balance to be more/less than the selected value
   4. Preset value is still selected while the entered value is either more or less

## Actual result:

Percentage selector remains selected when input value is changed

## Expected result:
Should reset if the input value is changed from the default value

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @spylogsster

**Comment by Uni-verse** [comment]
Verified using 

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.3.1 (Build 21E258)

- Using STR from above, the percentage selector is reset when input value is changed in Swap. 

https://user-images.githubusercontent.com/17885425/163065781-509261b1-cc2d-4e94-83f8-689c1567a6fa.mov
