### ISSUE TITLE
Brave Nightly crashes if tab groups are disabled and then trying to open new tab

### ISSUE THREAD

**Issue by Nojuuu** [brave/brave-browser#20318]
## Description 

Brave Nightly crashes if tab groups are disabled and then trying to open new tab

## Steps to reproduce 

   1. Disable Tab Groups
   2. Try to open new tab

## Actual result 

Crashing.

## Expected result

No crashing.

## Issue reproduces how often 
Every time when trying to open new tab

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- No
- Can you reproduce this issue with the current Play Store Beta version? 
- No
- Can you reproduce this issue with the current Play Store Nightly version?
- Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): OnePlus 7T Pro
   - Android version: 10
   
## Brave version
1.36.11 Chromium: 97.0.4692.56

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@Nojuuu is this working for you now?

**Comment by Nojuuu** [comment]
Yep, seems to be working now.
