### ISSUE TITLE
Global shield settings are not retained for Block scripts

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2031]
## Description 
Identified this issue while testing #1991 

Before applying Global shield settings (Block script),  if you have already enabled or disabled the shield site specific scripts, then the Global shield settings will not retained.

## Steps to Reproduce

   1.  Clean profile 0.56.9
   2.  Open Nytimes.com and enable "Scripts blocked" in shield panel
   3.  Verify scripts are blocked 
   4.  Reset to "All scripts allowed" and verify all scripts are allowed
   5. Click "Global shield defaults" option in shield panel
   6. Enable "Scripts blocking" option
   7. Reload the Nytimes page and observe scripts are not blocking
   8. Open a new tab and enter cnn.com 
   9. Verify that scripts are blocked and Global shield settings are retained
  

## Actual result:
Global shield settings are not retained for Block scripts

![block script issue_0 56 9](https://user-images.githubusercontent.com/38657976/48123962-3618b100-e2a1-11e8-9f26-1be8bc527bb5.gif)

## Expected result:
Global shield settings should retain for all websites even after enabling or disabling the scripts. 

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.56.9 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by yrliou** [comment]
I think what happens here is that step 4 will add Nytimes into the allow list (can check it in chrome://settings/content/javascript), so it won't use the default shields rule but its own rule.

**Comment by GeetaSarvadnya** [comment]
@yrliou That's correct. I am seeing nytimes in Allow list under chrome://settings/content/javascript

**Comment by GeetaSarvadnya** [comment]
Closing the issue as it's expected behavior.
