### ISSUE TITLE
parental controls: website whitelist

### ISSUE THREAD

**Issue by jaxankey** [brave/brave-browser#20311]
Hello!

I'm looking for a browser that allows me to whitelist a few safe websites and block the rest, so I can give my kids a computer and not worry about them going down a click-bait hole or watching inappropriate videos or something. 

It seems like this should be easy to implement and password protect (the filter list could live in a protected area of the system, e.g.), and it would definitely help a lot of people. It just does not exist anywhere and system-wide packet-filtering kills other necessary apps, like Teams (used to connect to school). 

It doesn't need to be fancy; even just a text file with something like 

```
*.wikipedia.org
*.wikimedia.org
kiddle.co
```

or something that, if present in `/etc/whatever/the/path.cfg`, would act as a filter for outbound requests (could be checked on the app's first load). This only has to be clever enough to block a 5 year old, not a full-fledged teenage hacker.

Thanks,
Jack

**Comment by Brave-Matt** [comment]
@jaxankey,
Would you mind posting this to our [Community website](https://community.brave.com) where we can discuss what options are available out of the box for Brave? We typically reserve Github for issue reporting and field questions/handle support on Community.

Thank you.

**Comment by jaxankey** [comment]
ack sorry!
