### ISSUE TITLE
Console errors when connecting a Trezor wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20313]
## Description 

While testing https://github.com/brave/brave-core/pull/10924, found that console logs errors when trying to connect a Trezor wallet. Also if the account selection is kept idle then it fails when trying to import an account

## Steps to Reproduce

   1. Clean profile of wallet
   2. Connect Trezor, check console throws a bunch of errors
   3. Keep the account selection screen idle for a while and try to select an account to import, throws error and doesn't import (This step is not consistently repro'd)

## Actual result:

<img width="1840" src="https://user-images.githubusercontent.com/17010094/148020015-cbee6746-bdd3-45de-ad0a-bf96b8d6beeb.png"> | <img width="1840"  src="https://user-images.githubusercontent.com/17010094/148020079-92588aa5-5cc9-45b1-9cfa-f82fb6ed58cf.png"> | <img width="1840" src="https://user-images.githubusercontent.com/17010094/148020182-1e5b0c36-4da9-49f8-8fef-ed1cc3740899.png"> | <img width="1840" src="https://user-images.githubusercontent.com/17010094/148020391-67f4135e-ee23-4e8d-898d-642a6ca5e48b.png">
-- | -- | -- | --

## Expected result:
No errors and should be able to import account after x amount of inactivity on the import screen

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (x86_64 translated)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | macOS Version 12.1 (Build 21C52)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster

**Comment by spylogsster** [comment]
seems fixed

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.93 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified no errors are shown when connecting a Trezor Wallet</li>
         <li>Also verified no errors are shown when initiating a transaction Trezor Wallet and submitting it</li>
        </ul>
      </td>
   </tr>
</table>
