### ISSUE TITLE
Build out the NFT Details Page

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20319]
## Description 
Build out the NFT Details Page

![image](https://user-images.githubusercontent.com/40611140/148090114-58ad9099-357e-48db-8956-2495284a5ae4.png)

You can find the specs for this component in Figma / Desktop Crypto Wallets.

Add the component too storybook with mock data for testing.

## Expected result:

Component should be visible and functional in Storybook under the Wallet/Desktop/Concepts tab.

**Comment by bbondy** [comment]
Changing to release-notes/exclude because it is not available to users just yet.
