### ISSUE TITLE
[Android] Don't auto open the Rewards Panel upon upgrade

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#20321]
## Description 

Please don't auto open the Rewards Panel on upgrade. Users will find the new screen when they tap the BAT icon. 

![Screenshot_20220103-111206](https://user-images.githubusercontent.com/7606853/148108638-573ac12b-71fc-40a6-942e-b833d085decb.jpg)

This applies to all users

**Comment by Miyayes** [comment]
@deeppandya, does this happen every single time, or only every 4th or so open? Just checking so that QA knows when checking.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.87 x64 Beta build
- Verified  upgrading from older build doesn't launch the rewards panel
- Verified by relaunching the browser multiple times after upgrade and still doesn't open rewards panel unless clicked

Upgrade without Rewards Enabled | Upgrade with Rewards Enabled
-- | --
<video src=https://user-images.githubusercontent.com/17010094/150125854-29ab5720-61a1-4b99-80c3-e31a5531864d.mp4> | <video src=https://user-images.githubusercontent.com/17010094/150125806-6d2b2f68-97ea-4b6a-9694-00c5208b30d6.mp4>

------
Verification passed on Samsung Tab A with Android 10 running 1.35.87 x64 Beta build
- Verified  upgrading from older build doesn't launch the rewards panel
- Verified by relaunching the browser multiple times after upgrade and still doesn't open rewards panel unless clicked

Upgrade without Rewards Enabled | Upgrade with Rewards Enabled
-- | --
<video src=https://user-images.githubusercontent.com/17010094/150126964-39b01796-734d-487d-ad09-daa9b957df26.mp4> | <video src=https://user-images.githubusercontent.com/17010094/150126948-b980a6a6-c86d-4aeb-9e50-5d20143a7764.mp4>
