### ISSUE TITLE
Migrate transaction history from json prefs to leveldb

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#20323]
Using `components/value_store` in `EthTxStateManager`

**Comment by srirambv** [comment]
**Verification passed on** 

Brave | 1.58.117 Chromium: 116.0.5845.180 (Official Build) (64-bit)
-- | --
Revision | 99255ad6abf2fa399c063683c051f973e1f5c0af
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#11743](https://github.com/brave/brave-core/pull/11743)
- Verified transactions continue to show up in Activity tab after upgrading from 1.57.x
- Verified `brave://prefs-internals` continues to show transactions completed before upgrade
- Verified able to create new transactions and transactions value is shown under `brave://perfs-internals`
- Verified on a clean install transactions are **not** shown in `brave://prefs-internals`

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.117 x64 build
- Verified steps from [brave/brave-core#11743](https://github.com/brave/brave-core/pull/11743)
- Verified transactions continue to show up in Activity tab after upgrading from 1.57.x
- Verified `brave://prefs-internals` continues to show transactions completed before upgrade
- Verified able to create new transactions and transactions value is shown under `brave://perfs-internals`
- Verified on a clean install transactions are **not** shown in `brave://prefs-internals`
