### ISSUE TITLE
DNSLink sometimes redirect to IPNS and othertimes IPFS depending on whether a DNS-CNAME-to-IPFS or DNS-IPNS-to-IPFS redirect is involved

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#20320]
## Steps to Reproduce

   1. Set up a local IPFS node from brave://settings/ipfs
   2. Enable automatically redirect DNSLink to IPFS from the same page
   2. Open a tab and visit https://ipfs.io, wait for it to redirect to IPFS and note the resulting address.
   3. Open a tab and visit https://docs.ipfs.io, wait for it to redirect to IPFS and note the resulting address.

## Actual result:
The address field shows ipns://ipfs.io/ for the first tab, but ipfs://bafybeic6n535syl7mivyh4wciefsbrxh5gztef3jtjid4abqvkss6a2wyy/ for the second tab.

## Expected result:
The difference between the two domain is how the DNS records and DNSLink is configured. However, the end-result is always the same (an IPFS record). So, either both domains are expected to return ipns://ipfs.io/ and ipns://docs.ipfs.io/ OR  both are expected to return ipfs://bafybeihi23ixdqi4vsh6rpklnk65nqiix7mgziwi2pb3keckrvpi2aauxu/ and ipfs://bafybeic6n535syl7mivyh4wciefsbrxh5gztef3jtjid4abqvkss6a2wyy/, respectively.

I can’t say which is the expected result, only that they return different answers is unexpected. I’m leaning towards always using IPNS-domain masking whenever possible, though. (It simplifies issues like #14774 and others.)

It’s unspecified in the DNSLink and IPNS specs how this should be handled, so @lidel should confirm the expected behavior. 

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave | 1.33.106 Chromium: 96.0.4664.110 (Official Build) unknown (64-bit)

## Other Additional Information:

```
dig TXT _dnslink.ipfs.io.
_dnslink.ipfs.io.	300	IN	TXT	"dnslink=/ipns/website.ipfs.io"

dig TXT _dnslink.website.ipfs.io.
_dnslink.website.ipfs.io. 300	IN	CNAME	_dnslink.ipfs-website.on.fleek.co.
_dnslink.ipfs-website.on.fleek.co. 300 IN TXT	"dnslink=/ipfs/QmRokRMcoCNFX6gUqSBPqnvziUZiRc232Ms4hv9dBxDqTZ"


dig TXT _dnslink.docs.ipfs.io.
_dnslink.docs.ipfs.io.	300	IN	CNAME	_dnslink.ipfs-docs.on.fleek.co.
_dnslink.ipfs-docs.on.fleek.co.	300 IN	TXT	"dnslink=/ipfs/Qme1ZHHoH5MhmjjLwJYr7HYxPt8ps24ZhsPvrDUT3u3w2U
```

**Comment by cqcallaw** [comment]
I can reproduce this on a clean install of Brave `1.34.80`. 

Enabling the IPFS Companion integration changes the behavior. With Companion integration enabled, `ipns://ipfs.io/` and `ipns://docs.ipfs.io/` are the final contents of the address bar.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.24 Chromium: 98.0.4758.87 (Official Build) nightly (64-bit) 
--|--
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1466)

1. new profile
2. loaded `brave://ipfs`
3. clicked on `install and start`
4. loaded `brave://settings/ipfs`
5. chose `Brave local IPFS node` from `Method to resolve IPFS resources`
6. toggled `Automatically redirect to IPFS pages via DNSLink when possible` to `ON`
7. loaded `https://ipfs.io`
8. confirmed I got redirected to `ipns://ipfs.io`
9. loaded `https://docs.ipfs.io`

Confirmed I got `docs.ipfs.io.ipns.localhost:48081` in the URL bar, and the content loaded.

example | example | example
---------|----------|---------
![20320-1](https://user-images.githubusercontent.com/387249/152435415-ab05ec87-d723-4f26-8924-33a8a828872e.png) | ![20320-2](https://user-images.githubusercontent.com/387249/152435427-10b58e05-2bb4-4d0b-8365-2128f702e986.png) | ![20320-3](https://user-images.githubusercontent.com/387249/152435430-a4517db8-3142-49be-b789-35edb3d5020e.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.87 Chromium: 99.0.4844.51 (Official Build) beta (arm64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.4 (Build 20G417)

example | example | example
---------|---------|---------
<img width="1027" alt="Screen Shot 2022-03-10 at 4 23 52 PM" src="https://user-images.githubusercontent.com/387249/157778216-af660c89-e7f2-4752-b472-fd2f5d799faf.png"> | <img width="1271" alt="Screen Shot 2022-03-10 at 4 24 57 PM" src="https://user-images.githubusercontent.com/387249/157778220-eb687683-7842-417d-8bb2-5308c27a345d.png"> | <img width="1271" alt="Screen Shot 2022-03-10 at 4 25 52 PM" src="https://user-images.githubusercontent.com/387249/157778222-6312dc2c-4614-4136-a635-7e18fe50beb9.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.101 Chromium: 99.0.4844.83 (Official Build) beta (x86_64)
-- | --
Revision | b11086e62d7c1a44b0942ac5568d22a425c7ae35-refs/branch-heads/4844_74@{#5}
OS | macOS Version 12.3 (Build 21E230)

example | example | example | example
---------|----------|---------|----------
<img width="1312" alt="Screen Shot 2022-03-22 at 5 13 12 PM" src="https://user-images.githubusercontent.com/387249/159597723-a1be6fd4-fedb-4181-be39-33412cb42c8a.png"> | <img width="1312" alt="Screen Shot 2022-03-22 at 5 13 47 PM" src="https://user-images.githubusercontent.com/387249/159597725-97dbed9b-9f61-46ea-ac04-5fe36b8edb60.png"> | <img width="1312" alt="Screen Shot 2022-03-22 at 5 16 23 PM" src="https://user-images.githubusercontent.com/387249/159597731-6d3f4588-2ce1-4db9-a449-a803a7c21766.png"> | <img width="1312" alt="Screen Shot 2022-03-22 at 5 16 43 PM" src="https://user-images.githubusercontent.com/387249/159597735-5dedcb7c-9258-4f3f-9f85-84996f6b0de9.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.101 Chromium: 99.0.4844.83 (Official Build) beta (64-bit)
-- | --
Revision | 	b11086e62d7c1a44b0942ac5568d22a425c7ae35-refs/branch-heads/4844_74@{#5}
OS | Ubuntu 20 LTS

<details>

![image](https://user-images.githubusercontent.com/34715963/159605647-f4648c4d-657b-4e51-af59-8f3d0baa4790.png)
![image](https://user-images.githubusercontent.com/34715963/159605752-2663f2ba-d62c-4c59-b35a-95e2507efb50.png)
![image](https://user-images.githubusercontent.com/34715963/159605898-a513628c-ed84-4e6c-9302-6e757cd51ceb.png)

</details>
