### ISSUE TITLE
Support EVM compatible chains

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#20337]

**Comment by Uni-verse** [comment]
Verification **PASSED** on `Samsung GS 21` running `Android 12` using build version: 

`1.36.86, Chromium 98.0.4758.87`

Verified Acceptance Criteria: 

- User is able to add custom EVM compatible networks - [5efd665](https://github.com/brave/brave-core/pull/11822/commits/5efd66567b500095845d51d2cc25ec1a7546e90f)
- Buy/Swap action button options hidden when a custom network is selected - [adb5c84](https://github.com/brave/brave-core/pull/11822/commits/adb5c843f2c90a45bf8fd059e5878b633b4f2b04)
- Custom networks are displayed in dropdown after getting added in the settings
- User is able to remove custom networks in the settings
- User can edit custom networks in the settings
- User is able to set network as active in the settings

Network Dropdown | Buy/Swap hidden | Network menu item
-|-|-
![Screenshot_20220208-061741_Brave - Beta](https://user-images.githubusercontent.com/17885425/152892006-6cc76d51-51bb-497b-bc36-471de5f100c6.jpg) | ![Screenshot_20220208-063636_Brave - Beta](https://user-images.githubusercontent.com/17885425/152892015-6176dd30-f9ee-4a65-8d3f-bf40b9319ae6.jpg) | ![Screenshot_20220208-065231_Brave - Beta](https://user-images.githubusercontent.com/17885425/152892022-0d998738-c68b-4ba5-a876-6b27a25999f8.jpg)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.87 x64 beta build
- Verified steps from [brave/brave-core#11822](https://github.com/brave/brave-core/pull/11822)
- Verified a new setting item is shown under Menu -> Brave Wallet -> Networks
- Verified able to add a new custom network via wallet settings from wallet or via menu settings
- Verified added custom networks show up on portfolio
- Verified custom networks only has send transactions
- Verified transaction approval shows up for custom EVM networks 
- Verified able to add multiple custom networks
- Verified added custom networks are retained between restarts
- Encountered [#20967](https://github.com/brave/brave-browser/issues/20967) & [#20968](https://github.com/brave/brave-browser/issues/20968)

New Networks Setting  | Add network | Network Details | Add Network details | Added Custom networks
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/152944293-016c007e-ff90-411a-97f4-ea095b9e54fe.png) | ![image](https://user-images.githubusercontent.com/17010094/152944353-95cbca13-5cd0-4ed9-a439-2eb0d95b3342.png) | ![image](https://user-images.githubusercontent.com/17010094/152944386-e22113bc-9e13-49c7-963c-02b60c00f75b.png) | ![image](https://user-images.githubusercontent.com/17010094/152944408-42ac2c20-1aa4-4f6c-8356-ef851cec69cc.png) | ![image](https://user-images.githubusercontent.com/17010094/152944461-509cc024-65d2-4e6b-a02d-1baf33f01eb8.png)

Custom Network on Portfolio | Select Custom Network | Send only | Transaction Approval | Transaction Details
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/152944558-c57b94f3-594e-4726-8859-e4dd963d82ec.png) | ![image](https://user-images.githubusercontent.com/17010094/152944588-005b24ae-4fb8-4563-be34-d0c86fa38cc1.png) | ![image](https://user-images.githubusercontent.com/17010094/152944668-753764a1-33d4-4686-83ca-6116fbca3fc9.png) | ![image](https://user-images.githubusercontent.com/17010094/152944693-d598d621-f823-4c0d-adec-be21e9612e3d.png) | ![image](https://user-images.githubusercontent.com/17010094/152944733-2a96b565-d39d-45e5-9f81-3ff4740ac3cc.png)
