### ISSUE TITLE
Cannot reload the page

### ISSUE THREAD

**Issue by gautam071** [brave/brave-browser#20330]
## Description 
- I could not reload any page while I inspect the elements of the particular page the error is No internet is connected.

## Steps to Reproduce

   1. Go to any page click on inspect elements. 
   2.  Then reload the page. 

## Actual result:

Before reloading
![image](https://user-images.githubusercontent.com/73119570/148174679-85537f07-0e25-4886-a4b8-869d21f5eaab.png)

After reloading
![image](https://user-images.githubusercontent.com/73119570/148174616-a3d53be7-648d-489d-804c-ffa4216a612e.png)

## Expected result:
- It should reload the page properly 

## Reproduces how often: 

- It happens always

## Brave version (brave://version info)

1.33.106  Chromium: 96.0.4664.110 (Official Build) (arm64)

## Version/Channel Information:

Version 1.33.106  Chromium: 96.0.4664.110 (Official Build) (arm64)

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  **No**
- Does the issue resolve itself when disabling Brave Rewards?  **No**
- Is the issue reproducible on the latest version of Chrome? **No**

**Comment by rebron** [comment]
@gautam071 I'm not able to reproduce and consistently able to reload. Do you have an extension installed that might be causing the issue or some other connection error? 

Can you try with a different profile that has no extensions?

**Comment by gautam071** [comment]
@rebron Thanks for the reply. I have removed all my extensions and tried to reload my page again it shows same error. But I tried using different profile it worked perfectly

**Comment by gautam071** [comment]
Closing this is issue. 
- It is working as expected the issue was the option `custom` from the dropdown on the top line change it `no throttling`.
