### ISSUE TITLE
I get spammed  with HTTP Warning when visiting some sites

### ISSUE THREAD

**Issue by CuboidRaptor** [brave/brave-browser#20334]
## Description 

When I visit vertain sites, like [Google Slides](slides.google.com) The browser spams me with HTTP warnings so I have to press >10 buttons just to open the website and tell Brave to calm down.

## Steps to Reproduce

   1. Open Brave browser
   2. Open a website, (e.g slides.google.com)

## Actual result:

It gives me a warning that the site doesn't support HTTPS, and then when I dismiss it it gives me another warning. And again, and again, and it becomes *painfully* difficult to open these websites.

## Expected result:
The page opens normally.

## Reproduces how often: 

Some sites Brave doesn't seem to care, others it does care. This does happen most of the time, although this might just happen on my computer.

## Brave version (info found on brave://version)

1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
Windows 10 Version 20H2 (Build 19042.1415)

## Version/Channel Information:

I'm not sure, I have only tested it on my version, which I believe is the Stable channel.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? wait um actually yes
- Does the issue resolve itself when disabling Brave Rewards? No, I don't think so
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by diracdeltas** [comment]
Did you turn on the "always use secure connections" switch on brave://settings/security ?

**Comment by rebron** [comment]
@CuboidRaptor Can you post some screenshots for what you're seeing?

**Comment by diracdeltas** [comment]
if you turn it off you won't see any of these warnings anymore, but you'll be able to navigate to HTTP sites without any warning, so it's up to you. if you mostly just click through these warnings anyway i'd say there's not much point in turning it on.

**Comment by CuboidRaptor** [comment]
yeah, I know that. Guess I'll keep it off and then keep my eyes on the address bar then. Or make a Tampermonkey thing instead.
