### ISSUE TITLE
Add More Menu to Wallet Tab Bar

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20339]
## Description 
Add a More Menu to Wallet Tab Bar

1) Replace the `Lock Wallet Icon` button with a `More Icon` button.
2) More menu should contain `Lock Wallet`, `Back up now` and `Settings` buttons.
3) Remove the `Back up now` and `Settings` buttons from the `Accounts` page.

![Screen Shot 2022-01-05 at 10 04 10 AM](https://user-images.githubusercontent.com/40611140/148259461-efd4e95b-a999-4076-bb3c-b7965d27ca64.png)

You can find the specs for this component in Figma / Desktop Crypto Wallets.

Add the component too storybook with mock data for testing.

## Expected result:

Component should be visible and functional in Storybook under the Wallet/Desktop/Concepts tab.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.87 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11752>brave/brave-core#11752</a></li>
         <li>Verified lock button is now replaced with <code>More</code> button</li>
         <li>Verified opening more button shows <code>Lock</code>, <code>Backup Code</code>, <code>Connected sites</code> and <code>Settings</code> options</li>
         <li>Verified there is no <code>Back up now</code> and <code>Settings</code> buttons from the Accounts page.</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/153225143-407f0a08-5221-42a7-a70a-0dddf0af142e.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153229332-431282be-bcfe-4478-a3ce-2745642f4d4d.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153229174-acfe876a-0040-4933-80bf-1fadecc2fab9.mov>
      </td>
   </tr>
</table>
