### ISSUE TITLE
Brave news - Background image is sometimes stretched when starting a new tab page

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20348]
## Steps to reproduce 

   1. Start a NTP with news opted in
   2. Check if the background image looks ok.

## Expected result

The ratio of the background image / sponsored should have the right look and feel and not be stretched. 
As an optimisation the wallpaper will be set using the Glide library.

## Issue reproduces how often 
Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
### Verified `PASSED` using Brave `1.36.66, Chromium 98.0.4758.66` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

**Confirmed:**
* background looks correctly scaled (before opt-in)
* Sponsored Image background looks correctly scaled (before opt-in)
* after opting in, both wallpaper and Sponsored-Image backgrounds are scaled correctly

example | example | example | example | example
---------|---------|-----------|---------|---------
![Screenshot_20220125-124200](https://user-images.githubusercontent.com/387249/151057439-2487faf7-f460-4a8c-a668-e766b7d9deb2.png) | ![Screenshot_20220125-124303](https://user-images.githubusercontent.com/387249/151057478-9cd23125-969c-4017-b06d-ca97090d4863.png) | ![Screenshot_20220125-124238](https://user-images.githubusercontent.com/387249/151057560-baededf3-bdca-4ed2-9bc7-f96d6cd30e15.png) | ![Screenshot_20220125-124122](https://user-images.githubusercontent.com/387249/151057635-0c15aa3d-6f95-4df4-8dbb-58bd4e97bcda.png) | ![Screenshot_20220125-124533](https://user-images.githubusercontent.com/387249/151057648-23a29f6b-c81c-49b6-a916-75f3d9404d51.png)
