### ISSUE TITLE
`Open using IPFS` button is missing sometimes

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20340]
## Description 

`Open using IPFS` button is missing sometimes

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `https://bafybeicgmdpvw4duutrmdxl4a7gc52sxyuk7nz5gby77afwdteh3jc5bqa.ipfs.dweb.link/wiki/Mars.html`
   4. click on `Use a local node` on the interstitial page
   5. wait for page to fully load
   6. look at the URL bar

## Actual result:

<img width="1312" alt="Screen Shot 2022-01-05 at 10 35 58 AM" src="https://user-images.githubusercontent.com/387249/148270705-84f90cd2-8989-43df-93ff-3eb96e4b8d7e.png">

There's no `Open using IPFS` button

## Expected result:

As there is on `https://en.wikipedia-on-ipfs.org/wiki/`, I'd expect there to be an `Open using IPFS` button, since the page *does* have `x-ipfs-path: /ipfs/bafybeicgmdpvw4duutrmdxl4a7gc52sxyuk7nz5gby77afwdteh3jc5bqa/wiki/Mars.html`

<img width="1312" alt="Screen Shot 2022-01-05 at 10 40 05 AM" src="https://user-images.githubusercontent.com/387249/148271359-def6140d-3d20-42f7-9902-1a8b3690a790.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.33.106 Chromium: 96.0.4664.110 (Official Build) (arm64)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | macOS Version 11.6 (Build 20G165)

Reproduced this issue with both `go-ipfs` version `0.10.0` and `0.11.0`.

cc @spylogsster and @lidel

**Comment by autonome** [comment]
So does that mean it's a regression? I don't remember this working spottily in previous versions.

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.36.30 Chromium: 97.0.4692.71 (Official Build) nightly (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 12.2 (Build 21D5025f)

Confirmed that with IPFS installed as a local node, loading https://bafybeicgmdpvw4duutrmdxl4a7gc52sxyuk7nz5gby77afwdteh3jc5bqa.ipfs.dweb.link/wiki/Mars.html yields the `IPFS` button (we shortened it as we've done with `Tor`).

<img width="1312" alt="Screen Shot 2022-01-11 at 1 54 21 AM" src="https://user-images.githubusercontent.com/387249/148921001-2c577487-41aa-40d3-9a0f-7470dee10bb0.png">
