### ISSUE TITLE
Move Reset for wallet into BraveWalletService

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20346]
Currently the ResetWallet function is not usable from iOS.
This changes it so you only need to call reset on `BraveWalletService`.
It also fixes a bug with reloading a tab when not needed for restoring a wallet seed phrase.

# QA test:
- Test that resetting the wallet reloads the wallet tab that is already open (if you have one open)
- Test that restoring seed phrase does not reload the active tab
- Test that adding a custom chain and switching to it, then resetting the wallet resets things back to normal

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.36.85 x64 Beta build
- Verified steps from issue description
- Verified reset wallet closes the wallet window and goes back to tabs view when reset from within the wallet
- Verified reset wallet from settings closes the settings page and goes back to tabs view
------------
Verification passed on Samsung Tab A  with Android 10 running 1.36.85 x64 Beta build
- Verified steps from issue description
- Verified reset wallet closes the wallet window and goes back to tabs view when reset from within the wallet
- Verified reset wallet from settings closes the settings page and goes back to tabs view

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.36.86 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | `e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}`
OS | Linux

- Verified test plan from issue description
- Verified reset wallet reloads the existing wallet page
- Verified reset removes all custom tokens added
- Verified reset removes all custom networks that are added 
- Verified auto-lock is also reset when wallet is reset but takes page reload to reflect changes
- Verified default base currency is reset when wallet is reset but takes page reload to reflect changes 
- Encountered [#20966](https://github.com/brave/brave-browser/issues/20966)

-----------------
Verification passed on 

Brave | 1.36.86 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | `e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}`
OS | Windows 11 Version Dev (Build 22543.1000)

- Verified test plan from issue description
- Verified reset wallet reloads the existing wallet page
- Verified reset removes all custom tokens added
- Verified reset removes all custom networks that are added 
- Verified auto-lock is also reset when wallet is reset but takes page reload to reflect changes
- Verified default base currency is reset when wallet is reset but takes page reload to reflect changes 
- Encountered [#20966](https://github.com/brave/brave-browser/issues/20966)

-----------------
Verification passed on 

Brave | 1.36.86 Chromium: 98.0.4758.87 (Official Build) beta (arm64)
-- | --
Revision | `e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}`
OS | macOS Version 12.1 (Build 21C52)

- Verified test plan from issue description
- Verified reset wallet reloads the existing wallet page
- Verified reset removes all custom tokens added
- Verified reset removes all custom networks that are added 
- Verified auto-lock is also reset when wallet is reset but takes page reload to reflect changes
- Verified default base currency is reset when wallet is reset but takes page reload to reflect changes 
- Encountered [#20966](https://github.com/brave/brave-browser/issues/20966)
