### ISSUE TITLE
Add a `coingeckoId` to `ERCToken` to be used in the future in `TokenRegistry`

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20344]
We should try to parse a `coingeckoId` in preparation for better multi chain lookups and 1-off fixes of wrong prices.

**Comment by onyb** [comment]
@bbondy Should we add a field for this to "Add custom asset"?

<img width="400px" src="https://user-images.githubusercontent.com/3684187/149329788-7d795d44-152e-4f5a-b27a-0ab61db214a5.png">

**Comment by bbondy** [comment]
> @bbondy Should we add a field for this to "Add custom asset"?
> 
> <img alt="" width="400px" src="https://user-images.githubusercontent.com/3684187/149329788-7d795d44-152e-4f5a-b27a-0ab61db214a5.png">

I think that'd be a good change, but pls post a new issue for that.
