### ISSUE TITLE
Brave news - Load new content button not appearing

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20349]
## Description 

On the first install the Load new content button appears only after the second NTP is opened.

## Steps to reproduce 

   1.  Opt in news
   2.  When the feed is available change a source from settings or the long press menu
   3. The Load new content button doesn't appear
   4. Open another NTP and repeat 2. the button will appear

## Expected result

The Load new content button should appear since the beginning

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.36.66, Chromium 98.0.4758.66` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

### Steps:
1. installed `1.36.36`
2. launched Brave
3. tapped through onboarding
4. restarted (to pick up Griffin seed for Brave News)
5. opened a new-tab page
6. swiped down
7. tapped to `Turn on Brave News`
8. tapped on the `Settings` icons at the top right
9. tapped on `All Sources`
10. tapped to enable/disable sources
11. tapped on the `X`

**Confirmed the `Load new content` orange button appeared.**


https://user-images.githubusercontent.com/387249/151069263-f617ef52-7164-4d08-ae5d-2cd500f42472.mp4
