### ISSUE TITLE
startup crash on C97 due to `ui::AddNativeUiColorMixer(ui::ColorProvider)` when using `10.13.6` (High Sierra) or lower

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#20351]
## Description 

As reported via https://community.brave.com/t/brave-beta-macos-crashes-upon-open/316900/11, there's a startup crash that occurs on `macOS 10.13.6` or lower that's 100% reproducible. I managed to reproduce the crash and retrieve a `dmp`  from `Crashpad` that @mkarolin symbolized as per the following:

* **`Crash Stack`** from @mkarolin ---> [crash.txt](https://github.com/brave/brave-browser/files/7818463/crash.txt)

OS's affected:

* `Sierra 10.12.6` <-- crashing
* `High Sierra 10.13.6` <-- crashing
* `Mojave` <-- doesn’t crash (tested/confirmed by @rebron)
* `Catalina`
* `Big Sur` <-- doesn’t crash (tested/confirmed by @stephendonner)
* `Monterey 12.1` <-- doesn’t crash (tested/confirmed by @kjozwiak)

```
Operating system: Mac OS X
                  10.13.6 17G14042
CPU: amd64
     family 6 model 158 stepping 13
     4 CPUs

GPU: UNKNOWN

Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0x0
Process uptime: 5 seconds

Thread 0 (crashed)
 0  Brave Browser Framework!<name omitted> [vector : 1526 + 0x0]
    rax = 0x0000000000000000   rdx = 0x000000000000000e
    rcx = 0x0000000000000000   rbx = 0x0000000000000000
    rsi = 0x0000000000000047   rdi = 0x00007ffed81a3890
    rbp = 0x00007ffeeec809d0   rsp = 0x00007ffeeec809d0
     r8 = 0x00000000ed81a9fb    r9 = 0x0000000000000003
    r10 = 0x00000000f8000000   r11 = 0x00007ffed8100000
    r12 = 0x00007ffed4420810   r13 = 0x0000000000000000
    r14 = 0x00007ffed81a3890   r15 = 0x00007ffed81a3890
    rip = 0x00000001104f76f8
    Found by: given as instruction pointer in context
 1  Brave Browser Framework!ui::AddNativeUiColorMixer(ui::ColorProvider*, bool, bool) [native_color_mixers_mac.mm : 33 + 0xd]
    rbp = 0x00007ffeeec80a30   rsp = 0x00007ffeeec809e0
    rip = 0x000000011050002f
    Found by: previous frame's frame pointer
 2  Brave Browser Framework!ui::AddColorMixers(ui::ColorProvider*, ui::ColorProviderManager::Key const&) [color_mixers.cc : 22 + 0xd]
    rbp = 0x00007ffeeec80a60   rsp = 0x00007ffeeec80a40
    rip = 0x00000001104fac71
    Found by: previous frame's frame pointer
 3  Brave Browser Framework!void base::internal::CallbackListBase<base::RepeatingCallbackList<void (ui::ColorProvider*, ui::ColorProviderManager::Key const&)> >::Notify<ui::ColorProvider*, ui::ColorProviderManager::Key&>(ui::ColorProvider*&&, ui::ColorProviderManager::Key&) [callback.h : 241 + 0x3]
    rbp = 0x00007ffeeec80aa0   rsp = 0x00007ffeeec80a70
    rip = 0x00000001104fb46f
    Found by: previous frame's frame pointer
 4  Brave Browser Framework!ui::ColorProviderManager::GetColorProviderFor(ui::ColorProviderManager::Key) [color_provider_manager.cc : 126 + 0x8]
    rbp = 0x00007ffeeec80b00   rsp = 0x00007ffeeec80ab0
    rip = 0x00000001104fb352
    Found by: previous frame's frame pointer
 5  Brave Browser Framework!views::Widget::GetColorProvider() const [widget.cc : 1756 + 0xb]
    rbp = 0x00007ffeeec80b50   rsp = 0x00007ffeeec80b10
    rip = 0x000000011163d55c
    Found by: previous frame's frame pointer
 6  Brave Browser Framework!views::StyledLabel::OnThemeChanged() [view.h : 907 + 0x8]
    rbp = 0x00007ffeeec80b90   rsp = 0x00007ffeeec80b60
    rip = 0x00000001115e023e
    Found by: previous frame's frame pointer
 7  Brave Browser Framework!views::View::PropagateThemeChanged() [view.cc : 3177 + 0xc]
...
```

## Steps to Reproduce

   1. install and version of Brave that has C97
   2. attempt to launch Brave and you'll get a startup crash after the `Default Browser` modal/prompt

## Actual result:

<img width="1291" alt="Screen Shot 2022-01-05 at 3 28 28 PM" src="https://user-images.githubusercontent.com/2602313/148306941-39245855-0c08-4614-b60f-99f187e2832e.png">

## Expected result:

Brave shouldn't be crashing on startup.

## Reproduces how often: 

100% reproducible when running through the above STR/Cases.

## Brave version (brave://version info)

* `1.33.106 Chromium: 96.0.4664.110` - **Couldn't reproduce**
* `1.34.63 Chromium: 96.0.4664.110` - **Couldn't reproduce**
* `1.34.78 Chromium: 97.0.4692.71` - **Reproduced**

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (C97 hasn't been released yet)
- Can you reproduce this issue with the beta channel? `Yes` (Reproduced)
- Can you reproduce this issue with the nightly channel? `Yes` (Reproduced)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @bsclifton @mkarolin @simonhong

**Comment by LaurenWags** [comment]
labelling as `release-notes/exclude` per discussion with @rebron 

cc @kjozwiak

**Comment by LaurenWags** [comment]
Verified passed with `Catalina 10.15.7`:

```
Brave	1.34.80 Chromium: 97.0.4692.71 (Official Build) (x86_64)
Revision	adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS	macOS Version 10.15.7 (Build 19H1519)
```

Confirmed no startup crash.
Confirmed able to open/close the browser (fully) several times.

---------------

Verified passed with `Mojave 10.14.6`:

```
Brave	1.34.80 Chromium: 97.0.4692.71 (Official Build) (x86_64)
Revision	adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS	macOS Version 10.14.6 (Build 18G9323)
```

Confirmed no startup crash.
Confirmed able to open/close the browser (fully) several times.

--------------
