### ISSUE TITLE
Wallet cannot connect to snowtrace.io ( Avalanche C-Chain explorer) 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20353]
## Description 

Wallet cannot connect to snowtrace.io ( Avalanche C-Chain explorer) 

## Steps to Reproduce

1. Go to `https://snowtrace.io/tokenapprovalchecker`
2. Enter a Wallet address
3. Click the `Connect to Web 3` button on left
4. Select `Metamask` in popup window
5. The site returns another window that prompts you to `Please connect your metamask`
6. Then nothing happens, Brave Wallet cannot connect to Web3 Metamask feature for `https://snowtrace.io/`

## Actual result:

<img width="1840" alt="Screen Shot 2022-01-05 at 10 37 18 PM" src="https://user-images.githubusercontent.com/17010094/148325334-83ff6480-8845-45ee-a2ad-ce653a80fe44.png">

## Expected result:
Should connect to Dapp

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.36.11 Chromium: 97.0.4692.56 (Official Build) nightly (arm64)
-- | --
Revision | `04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}`
OS | macOS Version 12.1 (Build 21C52)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy

**Comment by bbondy** [comment]
thanks for the ping, I'll take a look

**Comment by bbondy** [comment]
It's because they're using window.web3.currentProvider and wallets should not provide window.web3 anymore. 

I tweeted at them here and hopefully someone there sees it. 
https://twitter.com/brianbondy/status/1479124596456624144

I also asked MM to actually get rid of the web3 shim they inject.
For transparency, that message was:

> Are you guys planning to remove window.web3 shim anytime soon? We haven’t included one in the new Brave Wallet and have only ran into 1 issue so far with snowtrace.io which uses window.web3.currentProvider instead of using window.ethereum
> I’d rather not pollute the global namespace and add support for Dapp compat for it.  But I might have to if there’s no plans to actually deprecate window.web3 from MetaMask’s end.
