### ISSUE TITLE
Localization doesn't work in for Brave chrome strings and web-ui pages like brave://welcome and brave://rewards

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2035]
## Description 

If you change your system language to French or some other language, localization will not show up on web-ui pages.

## Steps to Reproduce

   1. Change source language on macOS in system preferences (other OS instructions may differ)
   2. Launch Brave with a fresh profile
   3. Navigate to brave://rewards

## Actual result:

In step 2. on the welcome page you'll see no translated strings.
In step 3. you'll also see no translated strings.

## Expected result:

Translated strings should show up (note that maybe not all of them will actually show up if we are missing translations, but at least some of them should show up to resolve this issue).

## Reproduces how often: 

Always.

## Brave version (brave://version info)

All but I'm using 0.57.4

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome?  No, Chrome translates its web-ui pages. But it doesn't have the ones in question.  We do translate the Chrome ones correctly.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.7 Chromium: 71.0.3578.53 (Offizieller Build) beta(64-Bit)
-- | --
Überarbeitung | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
Betriebssystem | Mac OS X

* Verified test plan from description, verified with several languages.
