### ISSUE TITLE
Fix Wallet Panel Tokens Undefined Error

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20367]
## Description 
Fix Wallet Panel Error showing a log of `Cannot read properties of undefined (reading 'tokens')`

![image](https://user-images.githubusercontent.com/40611140/148446388-b83d784a-bfa9-4abb-bc2b-eeabd903e22b.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.93 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified no errors on console when panel is opened</li>
         <li>Verified no errors on console when selecting network from wallet panel</li>
         <li>Verified no errors on console when selecting accounts from wallet panel</li>
         <li>Verified no errors on console when initiating transactions from panel for Buy/Send/Swap</li>
         <li>Verified no errors on console when signing a message from wallet panel</li>
        </ul>
      </td>
   </tr>
</table>
