### ISSUE TITLE
Cosmetic Filter Adds Noise to Console

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2036]
## Description 
Opening the contextmenu results in a CSS selector being logged to the page console. This is related to the Cosmetic Filter feature beneath the Brave submenu. Since this doesn't yield any value to the user, and is unexpected output, we should remove […/app/content.ts#L10](https://github.com/brave/brave-extension/blob/85aa24a86a9956bac37bba05c8c78b869a2f45f3/app/content.ts#L10).

## Steps to Reproduce
1. Right-click on any website
2. Check the console for that page

## Actual result:
A CSS selector has been logged.

## Expected result:
Brave should not logged unnecessary output to the console.

## Reproduces how often: 
100%

## Brave version (brave://version info)
0.55.22

### Reproducible on current release:
Yes

**Comment by kirkins** [comment]
You just want the console log removed here, or only show in non-release versions?

**Comment by bsclifton** [comment]
Closing as this was fixed with https://github.com/brave/brave-extension/pull/87
