### ISSUE TITLE
URL doesn't get debounced

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#20368]
## Description 

I was trying to use https://github.com/brave/adblock-lists/blob/master/brave-lists/debounce.json to come up with a URL that should get debounced but haven't had much luck.

## Steps to Reproduce

   1. Make sure `Enable debouncing` flag is Enabled in `brave:flags`
   2. Enter https://m.facebook.com/1.php?u=https://brave.com into omnibox

## Actual result:

![image](https://user-images.githubusercontent.com/5284154/148449777-aac2bd3d-e419-481a-beed-d78129dc4594.png)

## Expected result:
I would expect to be navigated to https://brave.com because of the debounce rule in https://github.com/brave/adblock-lists/blob/master/brave-lists/debounce.json

## Reproduces how often: 

Always

## Brave version (brave://version info)

Stable

Brave | 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | macOS Version 11.6 (Build 20G165)

Component version: **Brave Local Data Updater - Version: 1.0.45**

## Version/Channel Information:

Seems to happen on all channels.

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Didn't try
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fmarier and I ran into this, but it seems to work for @pes10k 
fyi @pilgrim-brave

**Comment by stephendonner** [comment]
I get the same on

Brave | 1.36.20 Chromium: 97.0.4692.71 (Official Build) nightly (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 20H2 (Build 19042.1415)

![same](https://user-images.githubusercontent.com/387249/148464737-876a115d-fcf9-4d74-8d28-15610905e644.png)

**Comment by fmarier** [comment]
I believe this is resolved now that we have the [test URLs](https://github.com/brave/adblock-lists/blob/d4180786b6d4b18c97a84efa38d447a19160f1d5/brave-lists/debounce.json#L327-L357).
