### ISSUE TITLE
Detect and store VPN state after restoring on account.brave.com

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#20374]
## Test plan
See https://github.com/brave/brave-core/pull/14715

## Description
When it comes to VPN, we'll need to update Android to have 3 states:
- VPN not purchased
- VPN purchased with In-App-Purchase
- VPN purchased with Desktop credentials

If VPN is not purchased, we should continue to promote the In-App-Purchase path. Nothing should change there.

Desktop currently supports VPN purchases using the accounts website (live on https://account.brave.software and https://account.bravesoftware.com). The SKU SDK (see implementation in https://github.com/brave/brave-core/pull/10847) is used to safely intercept credentials.

On Android, we can now support Desktop credentials. The use-case would look like this:
1. Customer purchases VPN on Desktop
2. They switch to their Android device
3. Navigate to accounts website (ex: https://account.bravesoftware.com)
4. After logging in, customer should see the VPN product showing (or they can buy VPN)
5. Purchased VPN product will show a button `Refresh Brave VPN`
6. Credentials are intercepted using SKU SDK and browser can present them

With browser being aware of the credentials, Android should consider the VPN product "purchased". We can authenticate with Guardian VPN using this desktop credential.

## Additional details
- When we click VPN button on Desktop (need to enable via brave://flags; it's next to hamburger button), as the panel is shown, VPN service will call `ReloadPurchasedState` which we can do also on Android 😄 
- On Android, we can call that method at any time we'd like. VPN feature (with https://github.com/brave/brave-core/pull/13387 branch) the feature is now enabled. The process of getting the purchase state is asynchronous
- Calling `ReloadPurchasedState` will go through a series of calls (to SKU backend) and you can call `vpn_service->is_purchased_user()` at any given time. This will return true if there are valid (issued and not expired) SKU credentials loaded
- If you want to CONNECT (on Android) and get subscriber credentials using the Desktop credentials, the `GetSubscriberCredentialV12` method can be called. The credential should be stored in `skus_credential_`

### iOS
- [Wire up SKU SDK to a JavaScript DOM element](https://github.com/brave/brave-ios/issues/4804)
- [Detect and store VPN state after sign-in](https://github.com/brave/brave-ios/issues/4805)

### Desktop
- [Integrate the SKU SDK into the browser](https://github.com/brave/brave-browser/issues/17614)
- [(Desktop) Detect and store VPN state after sign-in](https://github.com/brave/brave-browser/issues/17254)

**Comment by bsclifton** [comment]
@deeppandya can you help me check this out after we land https://github.com/brave/brave-core/pull/10692? 😄

**Comment by Uni-verse** [comment]
In progress on Android ARM using the following build(s):

```
Brave	1.45.109 Chromium: 107.0.5304.62 (Official Build) (64-bit) 
Revision	1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS	Android 12; Build/SP1A.210812.016
```
Acceptance Criteria: 

VPN not purchased
VPN purchased with In-App-Purchase
VPN purchased with Desktop credentials
