### ISSUE TITLE
Password and recovery phrase values are being persisted after restore action

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#20370]
## Description 
Entered (hidden) password and Recovery phrase on the Restore Crypto Account screen is being persisted after successful restore action. Recovery phrase can be viewed after locking wallet and another restore action.

## Steps to reproduce 

   1. Enter any password value on unlock wallet
   2. Click "Restore" wallet and complete the restoration process
   3. Lock the wallet from the menu on the Wallet home screen
   4. Verify the previously entered password and click on "Restore" to view the recovery details

## Actual result 
Password (hidden) and recovery phrase can be viewed after restoring wallet on the Restore Crypto Account and unlock wallet screens.

## Expected result
User details should be cleared after restore.

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): Both
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.33.106

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @deeppandya

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.85 x64 beta build
- Verified steps from issue description
- Reproduced the issue on 1.34.100
- Verified restoring a wallet and locking it, going back to restore doesn't show the recovery key and stores the passwords
------------
Verification passed on Oppo Reno 5 with Android 11 running 1.36.85 x64 beta build
- Verified steps from issue description
- Reproduced the issue on 1.34.100
- Verified restoring a wallet and locking it, going back to restore doesn't show the recovery key and stores the passwords
