### ISSUE TITLE
https://ge.globo.com

### ISSUE THREAD

**Issue by Ramys** [brave/brave-browser#20372]
Adds Google in site 
https://ge.globo.com

Brave Android.
https://ibb.co/sCkSbVQ

**Comment by Ramys** [comment]
https://ibb.co/sCkSbVQ

**Comment by rebron** [comment]
Closing/not actionable. 

@Ramys We need a lot more information than this for an issue in github. 
Please use the issue template or visit https://community.brave.com/ if there's an issue you'd like us to address.
