### ISSUE TITLE
Unable to drag bookmarks on the bookmark bar

### ISSUE THREAD

**Issue by amithiel** [brave/brave-browser#20375]
## Description 

From the bookmark bar, can't drag any folders or links around. Everytime i drag a folder/link  it gets somehow dropped on my desktop as a shortcut.

## Steps to Reproduce

   1. drag a folder or link to change positions on the bar or drag a new link to your bar
   2. 
   3. 

## Actual result:

it creates a shortcut on ~/Desktop instead

## Expected result:
should make the changes in your bookmarks bar

## Brave version (brave://version info)

it happens on version 1.34.80-1
i had to downgrade to working versions: 1.33.106-1

Using ArchLinux, installed package brave-bin from AUR.

cheers

**Comment by agilob** [comment]
Introduced between 1.33.106 and 1.34.80

**Comment by iamjameswalters** [comment]
I encountered this bug. I also reproduced this in the latest Chromium snap (edge channel, v. 98.0.4758.9), so it appears to be upstream as well. May be related to my issue, #20386

**Comment by iamjameswalters** [comment]
FYI, this regression appears to be fixed for me in the latest release, 1.34.81.

**Comment by agilob** [comment]
A tab Im moving around it tearing, move isn't smooth as it was before, but I'll take it :+1:
