### ISSUE TITLE
Link to connected site list in the panel

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20380]
Users sometimes have trouble finding this link:
brave://settings/content/ethereum?search=ethereum 

We should link from it in the menu on the panel and possibly also the one in brave://wallet

cc @Douglashdaniel

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.86 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11797>brave/brave-core#11797</a></li>
         <li>Verified connected sites option is available in Panel and on portfolio menu</li>
         <li>Verified connected sites option is only shown on webpages and not on internal pages</li>
         <li>Verified for a non-connected site panel shows <code>Connect</code> instead of <code>Disconnected</code></li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/20973>#20973</a> & <a href=https://github.com/brave/brave-browser/issues/20974>#20974</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/152981004-8067061a-3792-4fb6-b3e0-c9a29b7385ea.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152983017-5894daa9-3fc6-4c3c-85ac-5bb575baa485.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152984058-2719a017-58a2-46be-b7e2-963dea69c553.mov>
      </td>
   </tr>
</table>
