### ISSUE TITLE
Unable to drag and reorder tabs on Linux

### ISSUE THREAD

**Issue by iamjameswalters** [brave/brave-browser#20386]
## Description 

Attempting to drag tabs around to reorder them just pulls the tab out into its own window, which will not reduce and combine with any other windows.

## Steps to Reproduce

   1. Open a series of tabs.
   2. Drag one of these tabs to a new spot in the tab dock.
   3. Or, try to drag a tab from one window into another window.

## Actual result:

Tab is pulled out into its own window, and will not combine.

## Expected result:
Tabs are reordered or tabs from separate windows are reduced to one window.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Linux (specifically, Ubuntu MATE 20.04.3)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, I'm using the PPA
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? **Yes,** installed the Chromium snap from the edge channel (at time of writing, version 98.0.4758.9) and this bug is present.

## Miscellaneous Information:

Perhaps this is related to #20375 ? I encounter that bug as well.

**Comment by wildanpurnomo** [comment]
I experienced this issue as well after updating to 1.34.80 with AUR. I've downgraded back to 1.33.106 and tabs dragging went back to normal.

**Comment by bongochong** [comment]
Confirmed on this end too, under both Cinnamon and Xfce on Fedora 35.

**Comment by Darshil-P** [comment]
Same issue here too.
With Brave Beta `v1.35.75`
On Debian Bookworm (KDE)

**Comment by SteshinSS** [comment]
Same issue with KDE Plasma 5.22.5 / Kubuntu 21.10

**Comment by otikscypi** [comment]
Duplicate: #20275. (but this one has more traction) 

Also, yeah same here Gnome 40.5 / PopOS 21.10.

**Comment by jdnixx** [comment]
Yep have this problem too. Comment on the reddit thread for 1.34.80: https://www.reddit.com/r/brave_browser/comments/rxp7zw/comment/hrl1m0j/

**Comment by jota2016** [comment]
Same here.

Fedora 35 KDE.
Brave 1.34.80
Downgrading to 1.33.106 it works fine.

It's also happening with Chrome. 
google-chrome-stable.x86_64 96.0.4664.110 --> works fine
google-chrome-stable.x86_64 97.0.4692.71 --> has the issue

The latest update of both browsers presents this behavior.

**Comment by ipha** [comment]
This is broken upstream in chromium 97. There are patches available that have been applied to 98+, but not 97 yet

upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1279532

patch 1/2: https://chromium-review.googlesource.com/c/chromium/src/+/3355376
patch 2/2: https://chromium-review.googlesource.com/c/chromium/src/+/3355470

**Comment by jota2016** [comment]
Thanks for the info,  @ipha

**Comment by iamjameswalters** [comment]
> Duplicate: #20275. (but this one has more traction)

Ack! Sorry 😅

**Comment by bsclifton** [comment]
cc: @mariospr @mkarolin

**Comment by dusty-1** [comment]
For what it is worth, it appears that this issue is a general problem with "drag and drop", not just tabs. Here are some links to discussions of people impacted by "drag and drop" not working as it did in the previous version: 

https://www.reddit.com/r/brave_browser/comments/s0tfp7/cant_claim_bat_because_captcha_doesnt_work/
https://community.brave.com/t/unable-to-drag-bookmarks-into-bookmarks-bar/316827
https://community.brave.com/t/after-clicking-on-brave-rewards-i-cannot-drag-bat-img-into-target-img-so-i-cannot-claim-bat-rewards/310719

**Comment by ipha** [comment]
This is fixed upstream in Chromium 97.0.4692.92 and newer.

**Comment by neofutur** [comment]
serioulsly this is a HUGE functional bug that should be fixed ASAP.

**Comment by petersaints** [comment]
> serioulsly this is a HUGE functional bug that should be fixed ASAP. and since it is fixed upstream . . .

I agree. It is SO bad that makes the browser almost unusable. It should be a top priority to deploy a fix on all Brave Channels (I use the Beta Channel and the issue is also present there).

**Comment by aerocyber** [comment]
I agree. Brave is the browser I use daily and this bug is frustrating.

**Comment by otikscypi** [comment]
Gentleman. This is frustrating bug but:
- there is simple, temporary workaround of downgrading your brave version. It is linux, not osx we are talking here, downgrade is ordinarily a quick and easy procedure;
- it affects only a subsection of the user base - Linux users;
- is already fixed in the upstream, so we can expect the fix in the next release.

So: it's annoying, but does not affect everyone, there is an easy workaround, fix is coming from the upstream. Hardly a top priority for brave devs. In my opinion there is nothing wrong with the way this is handled so far.

**Comment by theRoboxx** [comment]
> Gentlemen. This is frustrating bug but:
> 
> * there is simple, temporary workaround of downgrading your brave version. It is linux, not osx, affected, downgrade is ordinarily a quick and easy procedure;
> * it affects only a subsection of the user base - Linux users;
> * is already fixed in the upstream, so we can expect the fix in the next release.
> 
> So: it is annoying, but does not affect everyone, there is an easy workaround, fix is coming from the upstream. Hardly a top priority for brave devs. In my opinion there is nothing wrong with the way this is handled so far.

You are right and it worked for me. For everyone: If you use the package manager Synaptic you can do it easily like mentioned here:
https://community.brave.com/t/how-to-revert-to-earlier-version-of-brave-for-linux/99490

**Comment by bongochong** [comment]
Just chiming in again to remind people that beyond downgrading, there's an even simpler fix that I mentioned several comments back: Right-click on unused space in the tab bar and un-check the _Use system title bar and borders_ entry. This will allow tab reordering and dragging again. Though you are sacrificing the standard title bar, I think it's worth it for now.

**Comment by ipha** [comment]
> Just chiming in again to remind people that beyond downgrading, there's an even simpler fix that I mentioned several comments back: Right-click on unused space in the tab bar and un-check the _Use system title bar and borders_ entry. This will allow tab reordering and dragging again. Though you are sacrificing the standard title bar, I think it's worth it for now.

That doesn't work on KDE.

**Comment by bongochong** [comment]
Well shoot. I can vouch for it working under Cinnamon and Xfce, so maybe it's only relevant to users in GTK land.

**Comment by maciek16180** [comment]
Same issue here on Kubuntu 20.04. 
Brave Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)

**Comment by dylif** [comment]
Same issue here on KDE/Arch Linux
Brave Version 1.34.80

Downgrading the package to the previous commit on the AUR works (brave-bin)
Can verify that using system title bar does not work on KDE as stated previously

**Comment by chavinlo** [comment]
For arch users if downgrade doesn't works:
`git clone https://aur.archlinux.org/brave-bin.git/`
`cd brave-bin`
`git checkout 8ced618cd527363919005f704d284c43e2ee3d23` (1.33.106 commit)
`makepkg -si`

**Comment by neofutur** [comment]
> Just chiming in again to remind people that beyond downgrading, there's an even simpler fix that I mentioned several 
>comments back: Right-click on unused space in the tab bar and un-check the _Use system title bar and borders_ entry. This 
>will allow tab reordering and dragging again. Though you are sacrificing the standard title bar, I think it's worth it for now.

thanks !  working great here on ubuntu !

**Comment by tmvkrpxl0** [comment]
This issue also happens on Kubuntu 21.10/Plasma 5.22.5 with framework 5.86.0 using Qt 5.15.2 on X11
And un-checking system title bar does not fixed the issue

**Comment by jdnixx** [comment]
Was excited to see a new stable release, so tried upgrading back only to see it's not fixed. I guess because 1.34.81 is still on chromium 97.0.4692.71 and we need ... .92 for the fix. As others have said, the system title bar trick doesn't appear to work on KDE. Time to downgrade again

**Comment by szymonpk** [comment]
@jdnixx are you sure?

> Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)

And tab re-ordering works for me again (KDE).

**Comment by DavidNorena** [comment]
I'm on arch linux, updated today to the latest version in the AUR and it seems it works again:

Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)

**Comment by wildanpurnomo** [comment]
Would like to confirm as well the issue has been resolved on my side with latest AUR package.

Thank you very much team and everyone. Hope you're doing well and safe always.

**Comment by iamjameswalters** [comment]
Just upgraded to 1.34.81 and this has been ✅ fixed for me! 🎊

Thanks to everyone here and upstream who worked on this. 💝

**Comment by idkw** [comment]
I was having the issue for a month on Linux Mint, this is now fixed, thank you for the reactivity.

**Comment by tmvkrpxl0** [comment]
This issue has been fixed recently for me

**Comment by bsclifton** [comment]
Thanks to everybody who has confirmed! With the recent upgrade to Chromium `97.0.4692.99`, this was fixed! (versions `1.34.81` and higher.

Beta channel doesn't have yet - I believe this is due to continuous integration errors. I'll try to get a new Beta build pushed soon!

**Comment by aloysius-pgast** [comment]
In the meantime, it's possible to install one of

* https://github.com/brave/brave-browser/releases/download/v1.35.93/brave-browser-beta_1.35.93_amd64.deb
* https://github.com/brave/brave-browser/releases/download/v1.35.92/brave-browser-beta_1.35.92_amd64.deb

Currently running 1.35.92 since it has been released

**Comment by khamer** [comment]
Just to add -

I first saw this issue today with version 1.36.105 Chromium: 99.0.4844.45. It's working properly with brave-beta Version 1.37.72 Chromium: 99.0.4844.45 though.

**Comment by nzbtuxnews** [comment]
> Just to add -
> 
> I first saw this issue today with version 1.36.105 Chromium: 99.0.4844.45. It's working properly with brave-beta Version 1.37.72 Chromium: 99.0.4844.45 though.

Same here on Mint 20.3 running XFCE and Brave 1.36.116 Chromium: 99.0.4844.74 (Official Build) (64-bit)]

Cant drag tabs or reorder them, the entire desktop behaves like it has a seizure.

**Comment by khamer** [comment]
Just adding - the AUR version of 1.36.122 Chromium 99.04844.88 shows this bug, but the Snap version does not.

**Comment by khamer** [comment]
Beyond being broken in version 1.36.122 Chromium: 99.0.4844.88 (Official Build) (64-bit), After Brave Beta updated, it's also now broken in Brave Beta version 1.37.84 Chromium: 99.0.4844.51.

It works in the snap version of brave - 1.37.109 Chromium: 100.0.4896.60

I'm guessing there was a regression of this bug between 1.34.81 / 97.0.4692.99 and 1.36.105, but I'm worried there was another regression between 1.37.72 and 1.37.84. After updating more, it seems to be fixed again in 1.37.109 Chromium: 100.0.4896.60.

**Comment by error256** [comment]
It works for me in 1.37.109 and 1.37.111 on the same system where it didn't at the time of the original issue, so some details must be different.

**Comment by khamer** [comment]
Also doesn't work for me with 1.37.111 Chromium: 100.0.4896.79.

**Comment by khamer** [comment]
Sorry for the frequent replies - testing out different versions available from the AUR, I found that the latest version of Brave is reporting
```
[194244:194244:0406/092550.112535:ERROR:wayland_window_drag_controller.cc(139)] zcr_extended_drag_v1 extension not available! Window/Tab dragging won't be fully functional.
```
Which lead me to [Sway #5692](https://github.com/swaywm/sway/issues/5692) and [wlroots #2889](https://github.com/swaywm/wlroots/issues/2889). These issues are both closed and Chromium is supposed to be patched for around a year.

Sure enough, I have the follow brave-flags enabled:
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```
And if I remove those, dragging works again, but that causes other issues (with things like screensharing.)

So my guess is that this may be a different issue than the original, and now Brave doesn't work properly under Wayland anymore.

**Comment by loyd** [comment]
It's broken for me on v1.39.111/102.0.5005 from AUR. Xorg =(

**Comment by nPHYN1T3** [comment]
Why is this marked as closed? Still an issue on V1.39.111 (May 24, 2022) (also X here)

**Comment by error256** [comment]
It broke after the latest update. Now it's broken in some weird way: most of the time it doesn't work, but sometimes tabs can be dragged correctly. When they can, it works correctly for all the tabs in the window until I switch to another window, then it can stop working in that window too.

**Comment by nPHYN1T3** [comment]
It's been broken to some degree for several updates. I noticed a while ago tab tearing was virtually impossible but I could move a tab in a window, now you can't do either. Just an ongoing regression that is now pushing 5 months.

**Comment by khamer** [comment]
In case it helps, I'm on Manjaro, Brave Browser 102.1.39.111, with the following in ~/.config/brave-flags.conf
```
--enable-features=UseOzonePlatform --ozone-platform=wayland --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy
```
And it works for me. Some of these flags I believe are related to wayland/screensharing on wayland, but wanted to include these in case any of these matter.

**Comment by nPHYN1T3** [comment]
Wayland flags only help if you run Wayland.

**Comment by mil-ad** [comment]
@bbondy I still have this issue on Brave 1.39.111 (Chromium: 102.0.5005.61). Is there a new issue to track this?

**Comment by nPHYN1T3** [comment]
Exactly why the hell is this closed?!

**Comment by ristomatti** [comment]
I've ended up here by searching for such issue on Chromium. If anyone reading happens to know a link to watch, it would be most welcome!

**Comment by mkarolin** [comment]
Please, recheck with the latest `1.39.120` release. This release includes the Chromium fix.

**Comment by nPHYN1T3** [comment]
I'm on 1.39.120, no change.

**Comment by mil-ad** [comment]
` 1.39.120` does fix the problem for me!

**Comment by mil-ad** [comment]
Moving tabs. This bug doesn't seem to be related to tearing?

**Comment by nPHYN1T3** [comment]
Moving, tearing and replacing are all the same thing as far as the action of moving tabs to and from windows and reordering. However I just tried again and I CAN get a tad to re-attach but it's still really jank. So it's fixed...but it sucks.

**Comment by mil-ad** [comment]
what window manager are you using? If you're on i3 then you might want to try something like [Syphdias/i3-chrome-tab-dragging](https://github.com/Syphdias/i3-chrome-tab-dragging)

**Comment by nPHYN1T3** [comment]
ctwm

**Comment by wommy** [comment]
> what window manager are you using? If you're on i3 then you might want to try something like [Syphdias/i3-chrome-tab-dragging](https://github.com/Syphdias/i3-chrome-tab-dragging)

https://github.com/Syphdias/i3-chrome-tab-dragging/issues/5

**Comment by ristomatti** [comment]
Seems to have been fixed on Chrome 102.0.5005.115 (Linux Mint 20).

Curiously it was not yet fixed on Chromium 102.0.5005.61 or Edge 102.0.1245.39 which both were upgraded as well.

**Comment by diivi** [comment]
I still get this problem on v1.57.53, Ubuntu

**Comment by kilroyjones** [comment]
I am also experience odd window dragging issues, though the window will actually float to the bottom of the screen and then disappear, but only on my second monitor. I am using Linux Mint - KDE Plasma with Brave version 1.60.118  and Chromium: 119.0.6045.163.
