### ISSUE TITLE
"when the Brave browser crashes or freeze" should be "...crashes or freezes"

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20394]
## Description 

"When the Brave browser crashes or freeze" should be "...crashes or freezes"

## Steps to reproduce 

   1. install `1.36.23`
   2. launch Brave
   3. tap through onboarding
   4. tap on the 3-dots menu
   5. tap on `Settings`
   6. tap on `Brave Shields & privacy`
   7. swipe to the bottom
   8. look at the `Automatically send diagnostic reports` info text.

## Actual result 

![Screenshot_20220108-015823](https://user-images.githubusercontent.com/387249/148640234-d0e5834e-35ed-4b88-920e-919847c84781.png)

## Expected result

Should read plural, as in `..when the Brave Browser crashes or freezes.`

## Issue reproduces how often 
100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

Brave `1.36.23, Chromium 97.0.4692.71`

cc @atuchin-m

**Comment by deepxcode** [comment]
Can I pick this up?

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.36.29, Chromium 97.0.4692.71` on a `Google Pixel XL` (`arm64`) running `Android 9.0`

Using my original steps, confirmed the text now reads, `"...when the Brave Browser crashes or freezes."`

![Screenshot_20220110-150953](https://user-images.githubusercontent.com/387249/148853435-670631b6-add9-4555-b10d-9dcbbf78bdc0.png)
