### ISSUE TITLE
brave-core release build should fail if `npm run test-security` fails

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#2039]
this is to track https://github.com/brave/devops/issues/343

if it cannot be done automatically in time for 0.56.x, it should be run manually on at least one platform before the build is officially released (but preferably on all platforms)

**Comment by diracdeltas** [comment]
it appears we are going to try to manually do this for 0.56 release, so i'm going to move this to hotfix1

**Comment by mihaiplesa** [comment]
Done, it runs automatically as part of the Mac build and will fail the build if audit fails.

**Comment by bsclifton** [comment]
Manually verified before we started the latest 0.57.x builds:
https://bravesoftware.slack.com/archives/C7VLGSR55/p1543512803370200
