### ISSUE TITLE
Tap target for Settings icon feels too small

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20392]
## Description 

Tap target for Settings icon feels too small

## Steps to reproduce 

   1.  install `1.35.77`
   2.  launch Brave
   3. tap through onboarding
   4. load `brave://flags`
   5. enable `Enable Brave News`
   6. tap `Relaunch`
   7. open a new-tab page
   8. swipe down
   9. tap to `Turn on Brave News`
   10. now, tap on the Settings icon

## Actual result 

The tap target seems a little small, just empirical evidence.  However, it's clear there's more CSS border padding/gutter space on iOS than on Android, seen below in this direct comparison:

iOS | Android
-----|---------
![Image from iOS](https://user-images.githubusercontent.com/387249/148635085-6ed453b0-51ae-4916-b893-f9559bcc3487.png) | ![Screenshot_20220107-225550](https://user-images.githubusercontent.com/387249/148635089-e8fd2948-ca8a-48a2-9d2b-1629656729de.png)

## Expected result

iOS -- on a similar screen size -- feels easier to successfully tap

Might just be my fingers/imprecision.

## Issue reproduces how often 
30% of the time?  Maybe less frequently?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

`1.35.77, Chromium 97.0.4692.71`

@srirambv @alexsafe how's your experience?

**Comment by srirambv** [comment]
I see this issue as well on my devices. Tap radius seems to be quite small especially when scrolling down the feed. 

@stephendonner Thanks for logging.

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.36.63, Chromium 97.0.4692.99` on a `Google Pixel XL` running `Android 9.0`.

I can consistently hit the tap target, now 👍 


https://user-images.githubusercontent.com/387249/150864351-f2d410b3-4431-4e1a-bb62-ff0b753c2265.mp4
