### ISSUE TITLE
BAT ad icon in promoted content ads should link to brave://rewards

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20390]
## Description 

BAT ad icon in promoted content ads should link to brave://rewards

## Steps to reproduce 

   1. install Brave `1.35.74`
   2. tap through onboarding
   3. load `brave://flags` and enable `Enable Brave News`
   4. open a new-tab page
   5. swipe down
   6. tap to `Turn on Brave News`
   7. swipe down a few "pages" until you see the BAT-logo ad icon
   8. tap on it

## Actual result 

Nothing happens.

![Screenshot_20220107-170920](https://user-images.githubusercontent.com/387249/148625514-555a1818-cf9e-407b-8c08-9c1547d2e095.png)

## Expected result

Should open up brave://rewards (not sure if in same tab or separate), which is how desktop works.

## Issue reproduces how often 
100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

`1.35.77, Chromium 97.0.4692.71`

**Comment by kjozwiak** [comment]
@stephendonner mind rechecking this one on `master`? @AlexeyBarabash mention this was already fixed.

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.37.13, Chromium 98.0.4758.74` on a `Google Pixel XL` running `Android 9.0`.

Confirmed that tapping on the BAT-logo icon for `Ad` load `brave://rewards`.


https://user-images.githubusercontent.com/387249/151842863-44e6dccd-b091-492a-9cc2-702e0627d20a.mp4

**Comment by stephendonner** [comment]
@alexsafe mind closing and pointing to a relevant set of commits?

**Comment by alexsafe** [comment]
@stephendonner fixed in https://github.com/brave/brave-core/pull/11766/files

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.105 x64 build
- Verified clicking on the BAT Ad icon loads `brave://rewards` page

https://user-images.githubusercontent.com/17010094/155665830-b3ed9023-44a1-489b-a838-7e8c1625adda.mp4
