### ISSUE TITLE
updated version not reflecting in browser

### ISSUE THREAD

**Issue by VenomFate-619** [brave/brave-browser#20397]
## Description 

I had updated my brave browser to 1.34.80 from my terminal, but it is not reflected in the browser.
I had tried to view in new window of browser also , but it was same

## Actual result:

![image](https://user-images.githubusercontent.com/67755128/148671320-1dc10a05-3d40-490d-a2f8-6d7330ddd1a4.png)

## Expected result:
![image](https://user-images.githubusercontent.com/67755128/148671331-c0a7a47f-083a-46fc-aea8-0bf9d795016d.png)

**Comment by rebron** [comment]
@VenomFate-619 Did you exit Brave and relaunch? Are you looking at a different instance of Brave?
brave://settings/help and brave://version should match.

**Comment by VenomFate-619** [comment]
It got resolved , after shutting down the system
