### ISSUE TITLE
Enable SafeBrowsing

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#204]
- [ ] Replace kSbV4UrlPrefix with the brave proxy
- [ ] Update the interstitial pages
- [ ] Disable reporting
- [ ] Update API key

**Comment by bbondy** [comment]
Is this issue fully completed?

**Comment by jumde** [comment]
API key update is tracked here: https://github.com/brave/brave-browser/issues/543
Interstitial pages update is tracked here: https://github.com/brave/brave-browser/issues/532

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Permissions Blacklisting does not work, but it also does not work in Chrome 69.0.3497.100
