### ISSUE TITLE
Load new content hides Brave News feed 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20408]
## Description 
When load new content is clicked for Brave News, it jumps to the top of the feed causing it to hide the entire feed on Tablets

## Steps to reproduce 

   1. Enable Brave News
   2. Scroll down the feed and open settings
   3. Disable a source so it trigger Load new content message
   4. Click on Load new content button, feed jumps to top causing it to 

## Actual result 

https://user-images.githubusercontent.com/17010094/148718299-75a13a9c-5a41-4a3e-8cdb-1a0fccff00e4.mp4

## Expected result
Jump to the top of feed but still show it 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.35.77 x64 Beta

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @anthonypkeane

**Comment by srirambv** [comment]
@alexsafe  this still seems to happen. Load new content still hides the feed view.


https://user-images.githubusercontent.com/17010094/155658515-d0a081a6-0077-4bfe-bc8d-429dc58015e0.mp4

cc: @Uni-verse

**Comment by Uni-verse** [comment]
Looks like its not reseting to top of view on mobile as well. (Samsung GS21 | Android 12)
version: `1.36.107, Chromium 99.0.4844.45`

https://user-images.githubusercontent.com/17885425/156076684-14281547-958c-4725-8f56-c160456967c2.mp4

cc: @srirambv
