### ISSUE TITLE
bookmarks in side panel not enabled

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#20400]
## Description 

I have notices that in latest chrome there is a flag to enable side panel, which shows a reading list and bookmarks.
I have enabled the same side panel flag in brave, and the panel is enabled, but it doesn't shows bookmarks.
please enable showing bookmarks. (note that instead the reading list is working).

## Steps to Reproduce

   1. save some bookmarks
   2. in brave://flags enable flag #side-panel and restart browser
   3. click on toolbar button to show the side panel
   4. click on bookmarks menu in the side panel
   
## Actual result:

bookmarks are not visible.

## Expected result:
bookmarks should be visible in side panel.

## Brave version (brave://version info)

Versione 1.34.80 Chromium: 97.0.4692.71 (Build ufficiale) (a 64 bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@simonhong @petemill Any idea why bookmarks in #side-panel aren't displaying?

**Comment by simonhong** [comment]
Got below error log when bookmark section is opened.
```
[12209:12209:0111/092016.466735:ERROR:CONSOLE(11)] "Uncaught TypeError: Cannot read properties of undefined (reading 'onChanged')", source: chrome://read-later.top-chrome/side_panel/bookmarks_api_proxy.js (11)
```
