### ISSUE TITLE
100% Preset is removing trailing 0's before decimal separator

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20402]
## Description 
100% Preset is removing trailing 0's before decimal separator

https://user-images.githubusercontent.com/40611140/148694423-ce47770e-cb7e-4ff8-a846-8a8eff560406.mov

cc: @onyb @Douglashdaniel

**Comment by bbondy** [comment]
Pls uplift this one to release channel after it is fixed.

**Comment by onyb** [comment]
Related issue: https://github.com/brave/brave-browser/issues/19521

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.82 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11804>brave/brave-core#11804</a></li>
         <li>Verified input value doesn't get trimmed on both Send and Swap</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/150462674-5686ec4b-3de8-4c25-a45d-57fc39bbd141.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/150462701-a32f191f-2171-4b1e-8b55-ec11056af7ce.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/150462131-cf1d7567-d720-4ef7-b4af-9e96f22ca7aa.mov>
      </td>
   </tr>
</table>
