### ISSUE TITLE
normalize week for promos

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#2041]
## Description 
Need to normalize weeks for promos. 

Currently, a week is defined as day of install through the next week. It should be normalized to define week as: Monday at 12:00 AM and end on Sunday at 11:59 PM, in device-local time. 

Users will then have an associated week of install.

**Comment by bsclifton** [comment]
After discussing with @emerick, we found this is already done 😄 See https://github.com/brave/brave-core/blob/09572b224c048e1927a4c023154b0a8ffe922d22/browser/brave_stats_updater_params.cc#L67

The code will work backwards to the last Monday in the week. @emerick proposed reenforcing this logic with more unit tests (found in https://github.com/brave/brave-core/blob/09572b224c048e1927a4c023154b0a8ffe922d22/browser/brave_stats_updater_unittest.cc)

**Comment by bsclifton** [comment]
No QA needed - functionality was already there (no code changes needed). The PR referencing this issue adds more unit tests to ensure this behavior is enforced
