### ISSUE TITLE
[Android] Rewards panel alignment issues with text and panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20418]
## Description 
Rewards panel alignment issues with text and panel

## Steps to reproduce 

   1. Visit `brave://rewards` on a tablet

## Actual result 
Portrait Mode
<img width=400 src=https://user-images.githubusercontent.com/17010094/148750567-9534f6fd-5de9-4ba6-9c10-4f2bfa31d6f6.png>

Landscape Mode
<img width=400 src=https://user-images.githubusercontent.com/17010094/148750588-0da257fa-e595-4b11-b5de-fa711f73ea68.png>

## Expected result
Should be similar to desktop mode with two columns so that changing orientation shouldn't cause issues

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? YEs

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.35.77 & 1.36.23

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @emerick @Miyayes

**Comment by Miyayes** [comment]
Is this resolved with https://github.com/brave/brave-browser/issues/24570? cc: @srirambv
