### ISSUE TITLE
Branded list card has unusually large images making it look awkward

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20414]
## Description 
Branded list card has unusually large images making it look awkward

## Steps to reproduce 

   1. Enable Brave news via flag
   2. Scroll down to view a branded list card
   3. Images are unusually large making it look stretched

## Actual result 
<img width=400 src=https://user-images.githubusercontent.com/17010094/148729113-ebdedbe3-e22f-4ce6-a22f-13af214e1411.png>

## Expected result

Android ARM | iOS
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/148729474-f045c75b-373f-495f-93fe-2d09a6102612.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/148729466-dd205107-72e8-4786-97cb-45ba54ef295f.png>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): Arm
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.35.77

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @petemill

**Comment by alexsafe** [comment]
@srirambv in 1.36 it looks more like the Android arm photo from Expected. I've been tweaking that, maybe the images need to be smaller still...

**Comment by srirambv** [comment]
On tablet its the same on both Beta and Nightly. Here's how it looks on nightly on tablet

https://user-images.githubusercontent.com/17010094/148799780-812b9eb4-3b08-4ae3-a506-83dca9d4fa25.mp4

**Comment by stephendonner** [comment]
Verified `PASSED` using `Brave 1.36.75, Chromium 98.0.4758.66` on a `Google Pixel XL` running `Android 9.0`.

Followed the original steps to reproduce, and confirmed branded card lists' images are correctly sized.

Example | Example
----------|---------
![Screenshot_20220127-135212](https://user-images.githubusercontent.com/387249/151450058-19865af4-cdc0-4936-b979-5d6be83e25f2.png) | ![Screenshot_20220127-135245](https://user-images.githubusercontent.com/387249/151450065-0ca1683e-5157-49f2-8369-0cbb40b05150.png)
