### ISSUE TITLE
Widget menu is unclickable when Brave News is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20410]
## Description 
Widget menu is unclickable when Brave News is enabled

## Steps to reproduce 

   1. Enable Brave News
   2. Open a new tab and click on Widget stack menu
   3. Doesn't show the menu options

## Actual result 

https://user-images.githubusercontent.com/17010094/148719210-8ce932df-d3f3-4bca-ab91-72869c4fba2f.mp4

## Expected result
Should be able to click the widget stack menu when Brave News is enabled

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.35.77

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @anthonypkeane @petemill

**Comment by alexsafe** [comment]
could be the same as this, not sure if this one involved exactly the same steps to repro
https://github.com/brave/brave-browser/issues/20899

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.104 x64 build
- Verified steps from issue description
- Verified able to tap on widget menu when Brave News is enabled

https://user-images.githubusercontent.com/17010094/155358389-132c6bd6-de98-4eb5-bdff-702ed4a1eb4b.mp4
