### ISSUE TITLE
[Android] [Follow up #20141] Verify wallet modal has a lot empty space

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20417]
## Description 
[Follow up #20141] Verify wallet modal has a lot empty space

## Steps to reproduce 

   1. Click on Verify Wallet from panel or via `brave://rewards/#verify`

## Actual result 

https://user-images.githubusercontent.com/17010094/148735425-c49dc5f0-d3ed-4098-b448-82b8afb674b4.mp4

## Expected result
Modal should not have empty space and should be properly aligned

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.35.77 x64 Beta Build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @emerick @deeppandya @Miyayes

**Comment by suchat932** [comment]
>
