### ISSUE TITLE
Brave mobile does not support playing drm protected content

### ISSUE THREAD

**Issue by notahumanthatisimportant** [brave/brave-browser#20424]
### Description: 
Unable to view drm protected content on hulu.com

### Steps to Reproduce 
  1. Go to hulu.com in desktop mode
  2. Login
  3. Attempt to view content

**Actual result:** 
Unable to view requested content

**Expected result:**
View requested content

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Persistent issue (every time i visit the page)

**Brave Version:** 
1.33.106

**Device details:** 
Model: S21 OS: android 12

**Website problems only:**
- did you check with Brave Shields down? Yes, same result
- did you check in Safari/Firefox (WkWebView-based browsers)? Firefox did not work but due to the nature of this issue I did not feel this was applicable

### Additional Information
Probably due to lack of widevine support. Also the same issue occured on the desktop version when widevine was not enabled

**Comment by vrindavan** [comment]
Need this.

**Comment by bsclifton** [comment]
@androidacy-user there actually have been designs and more put together- it's in our queue and we'll be picking it up soon

I'm going to close this issue in favor of https://github.com/brave/brave-browser/issues/20241 which has a lot more information. Please check there for updates 😄
