### ISSUE TITLE
Notify Uphold-verified users if they have to complete `customer due diligence` with Uphold

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20427]
## Description

Uphold now requires some users to complete an additional due diligence survey in order to be able to receive deposits (edit: or to send transactions). This status can be checked with `GET /me/capabilities/receives` or `.../sends`. (Uphold may soon add `/capabilities` generically which will return list of all capabilities, without checking each capability individually.)

Until this is complete, transfers/deposits to these users' Uphold accounts will fail. This includes deposits for ad payouts as well as userdrains. Transactions from the user's account, such as direct tips, will also fail. 

## Solution

**Updated: Jan 13, 2022**

1. When this state is detected
2. Throw the user back into "Logged out" state (and show "logged out" notification)
3. When user goes to log back/verify again, if they haven't completed the CDD survey, it'll fail and they'll get an error modal that tells them to complete this survey and then try again. (@Miyayes or @szilardszaloki have the appropriate error modal text. This error modal shows on Rewards settings page, so on Android, might be automatically inherited.) 

cc: @amirsaber @husobee @szilardszaloki 

## Notes

If user runs into this restriction, it does _not_ expire their access tokens. So this needs to be detected via separate API call.

**Comment by szilardszaloki** [comment]
`GET https://api.uphold.com/v0/me`'s response already contains if a user is required to fill in the CDD survey or not, and since this API is called in Uphold's wallet generation flow (which runs quite frequently), we'll just need to parse out `verifications.customerDueDiligence.status` and check if it's required for them.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.35.96 Chromium: 98.0.4758.66 (Official Build) (64-bit)
-- | --
Revision | db1b4001d5ce29f141297f260d2b778e000b85a3-refs/branch-heads/4758@{#762}
OS | Windows 10 Version 21H2 (Build 19044.1466)

```
