### ISSUE TITLE
[Android] Custodian selection modal looks empty (should be responsive) 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20421]
## Description 
Verify wallet has a empty react panel with Uphold listed. No title no text info

## Steps to reproduce 

   1. Enable rewards
   2. Click on Verify wallet button from panel
   3. Click on Verify on the popup modal, shows Uphold as custodian but panel has no info text or title

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/148788142-24a346f8-e0c3-4f0e-8790-84cbf2cf3ae0.png)

## Expected result
Either add a title saying `Select your custodian` or just skip it to show 2BAT warning for Uphold if Uphold is the only custodian avaiable

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes after 1.35 goes to release
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All version after 1.35 goes to release

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Miyayes

**Comment by emerick** [comment]
On desktop, the modal is wide and has a left pane that explains the picker. For phone-sized layouts, I agree that this needs a title or some explanatory text. However, tablets have enough width (I think) to show the full modal in this scenario, just like on desktop.

We should probably go through the Rewards UI and ensure that it's responsive on mobile/tablet/desktop, with the tablet UI approaching or using the desktop layout. cc: @Miyayes

**Comment by Miyayes** [comment]
Should be done as part of the new designs that come with https://github.com/brave/brave-browser/issues/22905.

**Comment by Miyayes** [comment]
Related to: https://github.com/brave/brave-browser/issues/16619
