### ISSUE TITLE
Support overrides to the eTLD+1 exception policy from default adblock filter lists

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#20426]
The default adblock engine, into which the default Brave filter lists are loaded, is subject to first-party exceptions to improve web compatibility when in standard Shields blocking mode, as per https://brave.com/privacy-updates/9-web-compat-blocking/.

However, there are cases where we can verify that some first-party resources are an invasion of privacy, cause excessive CPU load, or are otherwise harmful to users and do not break pages - in this case we'd like a way to override the first-party exception policy, and ensure that those requests are blocked anyways in standard Shields mode.

This can be accomplished by loading some filters into a separate adblock engine without the first-party exceptions.

**Comment by antonok-edm** [comment]
Now that the adblock engines are merged (#5461), this should be significantly easier to implement. We can create a new component in https://github.com/brave/brave-core-crx-packager to host the list in plaintext format, then use a new `AdBlockComponentFiltersProvider` similar to the [default filters provider](https://github.com/brave/brave-core/blob/master/components/brave_shields/browser/ad_block_service.cc#L271-L273) to load the list in the browser. Unlike the default filters provider, however, this new provider will be registered with the `AdBlockFiltersProviderManager` so that it can be loaded into the `additional_filters_engine_` rather than the `default_engine_`.

**Comment by LaurenWags** [comment]
@antonok-edm once the component mentioned in the [test plan](https://github.com/brave/brave-core/pull/18829#issue-1748499303) loads, are there additional steps we should take to verify it's working? For example, are there any sites we should check specifically?

**Comment by antonok-edm** [comment]
You can check https://www.the-scientist.com/ - there should be no blank bottom bar like there is on Release at the moment.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.54.85 Chromium: 115.0.5790.56 (Official Build) beta (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 11.7.8 (Build 20G1351)
```

### Steps:
1. installed `1.54.85`
2. launched Brave
3. loaded `https://www.the-scientist.com/`
4. noted site in `Standard` blocking mode
5. switched to `Aggressive` blocking mode and noted site
6. compared to `1.52.129`

## Confirmed the following:
* no blank space in either `Aggressive` or `Standard` blocking modes
* `Brave Ad Block First Party Filters` shows version `Version: 1.0.6` in `brave://components`
* blank space was seen in `1.52.129`, in `Standard` mode

## `1.54.85`

`Aggressive` | `Standard` | `brave://components`
--------------|------------|----------------------
<img width="1312" alt="Screen Shot 2023-07-01 at 3 07 23 PM" src="https://github.com/brave/brave-browser/assets/387249/3d50403b-f9c5-4692-bfb3-327cbc75360f"> | <img width="1312" alt="Screen Shot 2023-07-01 at 3 07 32 PM" src="https://github.com/brave/brave-browser/assets/387249/82cee781-8ce5-4350-9f23-50eb7e75c2cc"> | ![Screen Shot 2023-07-01 at 3 07 08 PM](https://github.com/brave/brave-browser/assets/387249/d9d2d9b3-15b5-4d7d-b409-d2513173c364)


## `1.52.129`

`Aggressive` | `Standard`
--------------|-----------
![Screen Shot 2023-07-01 at 2 55 05 PM](https://github.com/brave/brave-browser/assets/387249/91c7c87b-1937-4968-827a-ab1c0c297c3c) | ![Screen Shot 2023-07-01 at 2 56 21 PM](https://github.com/brave/brave-browser/assets/387249/4bc1d64a-1249-4327-ab3f-19dbb1aecdb3)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.57.36 Chromium: 115.0.5790.171 (Official Build) beta (64-bit) 
Revision	a4bb683f14dc402f5da13707e13559dc4d5ef08b
OS	Linux
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.57.41 Chromium: 115.0.5790.171 (Official Build) beta (64-bit)
-- | --
Revision | adc7e3e2defac3f9b39cb22bcbb354b72b74c2eb
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

### Steps:
1. installed `1.57.41`
2. launched Brave
3. loaded `https://www.the-scientist.com/`
4. noted site in `Standard` blocking mode
5. switched to `Aggressive` blocking mode and noted site
6. compared to `1.56.x`

## Confirmed the following:
* no blank space in either `Aggressive` or `Standard` blocking modes
* `Brave Ad Block First Party Filters` shows version `Version: 1.0.20` in `brave://components`
* blank space was seen in `1.56.20`, in `Standard` mode

## `1.57.41`

`Aggressive` | `Standard` | `brave://components`
--------------|------------|----------------------
<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1cdc8ad5-b149-4448-bd27-baaaaad24bc9">|<img width="645" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/dc0919a7-ecc0-49ec-a2dd-90dce6f19203">|<img width="647" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/20622b5f-4046-4f99-af2e-5b41d6be8f86">


## `1.56.20`  
Aggressive | Standard 
---- | -----
<img width="649" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4a1e435a-6163-47d1-9f46-15ddaa6965e2">|<img width="649" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b0683c0d-295f-4ef2-971a-0fb193d710a5">
