### ISSUE TITLE
[Android] Site icon for creator takes a long time to fetch/appear.

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20434]
## Description 

Site icon for creator takes a long time to fetch/appear.

## Steps to reproduce 

   1. install `1.36.29`
   2. launch Brave
   3. tap through onboarding
   4. load `jumde.github.io`
   5. tap on the BAT icon
   6. tap to `Start using Rewards`
   7. tap again on the BAT icon
   8. wait...
   9. look for the site icon, just to the left of the `jumde.github.io` header

## Actual result 

It takes a super long time to fetch/appear (~1 minute!)

NOTE: Additionally -- and this is a separate bug/issue -- there's no caching, once fetched (open, dismiss, and reopen the Rewards panel).

https://user-images.githubusercontent.com/387249/148877801-1d13ca87-0d5a-43d8-8a38-a65a05761fba.mp4

## Expected result

Should be within mere seconds (<10, for sure)

## Issue reproduces how often 

100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`.
   
## Brave version

`1.36.29, Chromium 97.0.4692.71`

cc @deeppandya @LaurenWags

**Comment by srirambv** [comment]
This is not a bug. GH pages where there is no site icon takes a while to show the generic icons.

**Comment by stephendonner** [comment]
> This is not a bug. GH pages where there is no site icon takes a while to show the generic icons.

It's a bug...just not fully ours.  Are we being rate-limited, perhaps?  Maybe we need to investigate getting an API key, if we don't, already have one?

**Comment by emerick** [comment]
No, we're not being rate-limited. The issue is that there's no favicon set for this page and our code will continue to try for 30 seconds before giving up. I think we can reduce the retry interval to 10 seconds with no adverse effect.
