### ISSUE TITLE
Remove corner radius background on Rewards panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20439]
## Description 
Remove corner radius background on Rewards panel

## Steps to reproduce 

   1. Install Beta/Nightly build
   2. Open a page so tab has a background
   3. Open rewards panel, each corner with curved radius has a dark overlay background

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/148933071-ed0a038b-9510-4bc3-9091-b2c2dde0e92f.png)

## Expected result
Not what you see

## Issue reproduces how often 
Easy on light theme much more difficult to notice on dark theme

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
Beta and Nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Miyayes

**Comment by Uni-verse** [comment]
Verification completed on `S Galaxy S21` running `Android 12` using build version: 

`1.36.86, Chromium 98.0.4758.87`

- Verified corners with curved radius in the rewards panel don't contain dark overlay background - https://github.com/brave/brave-browser/issues/20439#issue-1099026807

Dark BG | Light BG
-|-
![Screenshot_20220208-031933_Brave - Beta](https://user-images.githubusercontent.com/17885425/152867160-f397be80-58ce-4917-9948-ab02b7d8d91f.jpg) | ![Screenshot_20220208-032622_Brave - Beta](https://user-images.githubusercontent.com/17885425/152867176-40d29b82-ecc5-49a5-9ba4-456464d9aaa2.jpg)
