### ISSUE TITLE
[Android] Rewards onboarding first slide causes the panel bottom corners to be moved away from the panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20438]
## Description 
Rewards onboarding first slide causes the panel bottom corners to be moved away from the panel

## Steps to reproduce 

   1. Clean install Beta/Nightly build
   2. Load a page in NTP
   3. Open Rewards panel and click on start to trigger rewards onboarding, first slide causes the rewards panel bottom part to be separate from the panel

## Actual result 
Happens only on the first slide not on others 
![image](https://user-images.githubusercontent.com/17010094/148931707-8665e537-ec06-41a9-b5e3-14d5753e59a6.png)

## Expected result
Expand the panel in background fully rather than just the bottom part of the panel similar to release channel 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.35.x and 1.36.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Miyayes

**Comment by Uni-verse** [comment]
Verified `Samsung GS 21` & `Tab S7` using

```
Brave	1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Android 12; Build/SP1A.210812.016
```

Using STR in https://github.com/brave/brave-browser/issues/20438#issue-1099018124

- Confirmed the corners in the first onboarding slide are not separated from the panel.

Mobile | Tablet
-|-
![screenshot-1658808905245](https://user-images.githubusercontent.com/17885425/180922033-1c1edf89-3969-4bb0-afed-cdf9ccca1f8d.png) | ![screenshot-1658809060534](https://user-images.githubusercontent.com/17885425/180922036-e629a9d4-d285-4551-92af-bf49c6209032.png)
