### ISSUE TITLE
Move `window.chrome.braveSkus` to use gin

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#20437]
## Description 
Follow up from https://github.com/brave/brave-core/pull/10847
(similar to https://github.com/brave/brave-browser/issues/19909)

Goal would be to eliminate the boiler plate code in `brave/components/skus/renderer/skus_js_handler.cc` by using `gin::Wrappable`

As an example:
NetErrorPageController
anything that includes object_template_builder.h

```
return gin::Wrappable<NetErrorPageController>::GetObjectTemplateBuilder(
             isolate)
      .SetMethod("downloadButtonClick",
                 &NetErrorPageController::DownloadButtonClick)
      .SetMethod("reloadButtonClick",
                 &NetErrorPageController::ReloadButtonClick)
      .SetMethod("detailsButtonClick",
                 &NetErrorPageController::DetailsButtonClick)
      .SetMethod("diagnoseErrorsButtonClick",
                 &NetErrorPageController::DiagnoseErrorsButtonClick)
      .SetMethod("trackEasterEgg", &NetErrorPageController::TrackEasterEgg)
      .SetMethod("updateEasterEggHighScore",
                 &NetErrorPageController::UpdateEasterEggHighScore)
      .SetMethod("resetEasterEggHighScore",
                 &NetErrorPageController::ResetEasterEggHighScore)
      .SetMethod("launchOfflineItem",
                 &NetErrorPageController::LaunchOfflineItem)
      .SetMethod("launchDownloadsPage",
                 &NetErrorPageController::LaunchDownloadsPage)
      .SetMethod("savePageForLater", &NetErrorPageController::SavePageForLater)
      .SetMethod("cancelSavePage", &NetErrorPageController::CancelSavePage)
      .SetMethod("listVisibilityChanged",
                 &NetErrorPageController::ListVisibilityChanged);
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.62 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 11.6.7 (Build 20G630)

### Steps:
1. installed `1.42.62`
2. launched Brave
3. set the appropriate `SKU SDK` and `VPN` flags in `brave://flags`
4. restarted Brave
5. loaded `account.brave.software` (`development`)
6. entered basic auth
7. purchased `VPN`
8. confirmed when prompted to add `BraveVPN`'s config
9. confirmed my `BraveVPN` connection was working

example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2022-07-12 at 5 21 33 PM" src="https://user-images.githubusercontent.com/387249/178623097-85f030c1-048e-4670-929b-eb35d0275772.png"> | <img width="1312" alt="Screen Shot 2022-07-12 at 5 22 34 PM" src="https://user-images.githubusercontent.com/387249/178623109-3ecd6eca-0a29-4380-9dc7-1e11df4fac2f.png"> | <img width="1201" alt="Screen Shot 2022-07-12 at 5 22 54 PM" src="https://user-images.githubusercontent.com/387249/178623115-4928f582-838a-4d8b-be54-d3e84fe6049a.png"> | <img width="1312" alt="Screen Shot 2022-07-12 at 5 23 00 PM" src="https://user-images.githubusercontent.com/387249/178623117-6a51cf44-b8da-4000-95e4-70b38f1a32ba.png">

**Comment by LaurenWags** [comment]
Updated label to `release-notes/exclude` as Brave VPN is not part of the 1.42.x release.
