### ISSUE TITLE
group policy/settings: consistent configuration for --sync-url= argument

### ISSUE THREAD

**Issue by tycho** [brave/brave-browser#20431]
## Test plan
See https://github.com/brave/brave-core/pull/25498

## Description 

There should be a [group policy](https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy) or UI option for Brave to provide the `--sync-url=` option without needing to explicitly add a command-line argument.

One issue is that adding command line arguments varies a lot by platform:
- On Linux, you can wrap the Brave launcher to provide custom arguments. This can be annoying if your distribution packager did not provide a functional equivalent to Chrome's `~/.config/chrome-flags.conf` file (where each line of the file is treated as a command line argument appended whenever the browser is launched).
- On Windows, you can edit all the Brave shortcuts to add the arguments (this is very painful if you need to do this at scale).
- On macOS, I have no idea how you'd add the arguments without using a shell script or something to launch the app bundle.

A group policy config option would be ideal, because deploying that kind of policy is well defined for each platform. Adding this also makes self-hosting a sync server much easier.

Alternatively, a UI option to customize the sync server URL would be nice as well. As long as the setting persists without needing to add a command-line flag.

## Steps to Reproduce

N/A, see description.

## Actual result:

The `--sync-url=` option is difficult to configure consistently across platforms. Self-hosting a sync server is very difficult without a way to consistently customize the sync URL.

## Expected result:
The `--sync-url=` option should be configurable across platforms without having to resort to manipulating command line arguments, to enable self-hosting a sync server.

## Reproduces how often: 

Always?

## Desktop Brave version:

```
Brave	1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
Revision	adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS	Windows 10 Version 21H1 (Build 19043.1415)
```

## Version/Channel Information:
All channels at the moment. Nothing provides more than the `--sync-url=` flag.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by ppar** [comment]
I'd very much like to see this implemented too. 

Even exposing the setting in a config file like `~/{.config,Library/Application Support}/BraveSoftware/Brave-Browser/*/Preferences` that one could edit manually would be nice. 

> A group policy config option would be ideal, because deploying that kind of policy is well defined for each platform.

This might be my own shortcoming, but the [linked ​documentation at support.brave.com](https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy) only mentions Windows. If this applies to Linux and Mac as well, instructions (for users outside a managed corporate IT environment) could be useful.

**Comment by ppar** [comment]
Another aspect of missing a persistent setting is that it's easy to commit changes to the public sync server by accident. I've tested & verified the following:

1) Start Brave processes on 2 computers with `--sync-url=` set to your self-hosted server
1) Set up Sync between them in the usual way
1) One of the Brave instances stops and then restarts without the --sync-url option (e.g. because the computer crashed and recovered the desktop session, or an automated software update overwrote a shell wrapper, etc)
1) Add a bookmark on the restarted browser instance. It will now push your change to the public Sync endpoint, which happily accepts it, even though the chain didn't exist on the public server before.
1) Restart the other browser, also without --sync-url. It will now pull the new bookmark from the public Sync server.

Apparently the sync chain gets implicitly created (either by Brave or the sync service).  

IMO more expected behaviour would have been for Brave to issue an error message if the sync chain that had earlier been set up doesn't exist on the server.

**Comment by DaCHack** [comment]
This is requested since long time.
See related issue #12314
https://github.com/brave/brave-browser/issues/12314#issue-729322829

Hope this gets some new traction. I cannot believe that a UI switch in both desktop and mobile versions is that much of a deal.

Already offered my support and finding my way through the Code despite being a complete noob when I at least receive a clue where to start 😞

**Comment by trymeouteh** [comment]
What should be done is that a setting should be added in the brave sync menu to change the URL of the sync server. This will be a user friendly way to changing the server and will allow you to use your self hosted sync server on desktop and mobile.

**Comment by JamesImmerso** [comment]
Why has this basic feature request languished for over a year? Self-hosting a bravesync server is only practical/useful if we can set the self-hosted bravesync sever location within brave browser settings! Thank you to the amazing team at Brave, but this right here is a curious omission. Please advise.

**Comment by metal450** [comment]
> Why has this basic feature request languished for over a year? 

Over 2 years: https://github.com/brave/brave-browser/issues/12314

> this right here is a curious omission. Please advise.

Wondering this myself.

**Comment by Graxo** [comment]
Are there any plans to give this more priority? Or is there some sort of Roadmap for Brave?

**Comment by NicholasFlamy** [comment]
> This is requested since long time. See related issue #12314 [#12314 (comment)](https://github.com/brave/brave-browser/issues/12314#issue-729322829)
> 
> Hope this gets some new traction. I cannot believe that a UI switch in both desktop and mobile versions is that much of a deal.
> 
> Already offered my support and finding my way through the Code despite being a complete noob when I at least receive a clue where to start 😞

They f8cking shadow deleted the issue.

**Comment by bsclifton** [comment]
@NicholasFlamy (and others) for full transparency, I'm not sure who deleted that issue. I'm trying to find out now - I've asked internally and so far haven't found anyone with privs that has done this. I'll dig in more and find out

For now, we can recreate the issue. I don't have the original issue content - was this just asking to make it configurable in app?

**Comment by NicholasFlamy** [comment]
> @NicholasFlamy (and others) for full transparency, I'm not sure who deleted that issue. I'm trying to find out now - I've asked internally and so far haven't found anyone with privs that has done this. I'll dig in more and find out
> 
> For now, you are welcome to recreate the issue. I don't have the original issue content - was this just asking to make the URL configurable in app?
> 
> **UPDATE**: I opened a ticket with GitHub support to find out what happened ![image](https://private-user-images.githubusercontent.com/4733304/320978291-44934eee-5cf8-420a-bd4f-97306f0913e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTEzNzAsIm5iZiI6MTcxMjY5MTA3MCwicGF0aCI6Ii80NzMzMzA0LzMyMDk3ODI5MS00NDkzNGVlZS01Y2Y4LTQyMGEtYmQ0Zi05NzMwNmYwOTEzZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTkzMTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY5NzU0M2Y4OTZiNWJjZmI4OGI5OGFhMzM0ZTc0OTM4OGM1YjE4NjU2MDA0NzQ1M2JhZDkyMTMyMTZlMGY5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cS3Bsze4sW8mY_kpjmpN6MsL7SVIQVYVmxDLdH4TUJ8)

I pulled up the latest Google Webcache of it and posted a link in the discussion I made:
https://github.com/orgs/flamy-brave/discussions/3

I might make a new issue but I'll hold off because the issue being deleted is super strange.

**Comment by bsclifton** [comment]
@NicholasFlamy got a response from GitHub - seems the person who created the original issue set their account as private and that is why it's not showing. We definitely keep posts up - although sometimes we will remove posts in an issue if they cross the line (disrespectful, etc).

Please create a new issue describing what you were wanting. Here's the official response from GitHub support:
![image](https://github.com/brave/brave-browser/assets/4733304/638caa2f-25d6-47cb-85ab-f1994aeb768b)

**Comment by NicholasFlamy** [comment]
Wow, that's something I've never seen before. Okay, I'll get on it.

**Comment by NicholasFlamy** [comment]
#37448 made this for now.

**Comment by GanerCodes** [comment]
This really, really, _really_ shouldn't be a two-year delayed feature. For an open source project the fact I can't use a basic feature on my phone without using their servers is really annoying

**Comment by h7sj** [comment]
It seems extremely suspicious that this simple issue has not been resolved. There are so many ways to fix it, i.e. UI option, `brave://flags`, `brave://sync-internals`, config file, `chrome-command-line`, group policy etc. 

This would certainly qualify as a priority issue for a browser that emphasizes privacy to the extent Brave does. Customers switching to Brave absolutely want this functionality as we are increasingly turning our backs on corporate-owned clouds in general. This feature would be significantly more popular if officially supported. 

Not actioning this request is clearly deliberate, but with no stated reason perhaps we should question _why_ Brave are resisting. There is a dizzying amount of information in sync payloads and I highly suspect these may not be as private and secure as Brave claim. Is this omission Brave's [warrant canary](https://www.cloudflare.com/en-gb/learning/privacy/what-is-warrant-canary/)? Is Brave being compelled to retain a role in the flow of sync data by outside influences?

**Comment by h7sj** [comment]
I couldn't resist - There is exactly one mention of `https://sync-v2.brave.com/v2` in `chrome.dll`.

I have a domain name that is a few characters less than that in length. Using a hex editor, I overwrote the brave URL with mine and padded the dead space with null characters.

Amazingly this works according to `brave://sync-internals` and some light testing. Brave doesn't seem to notice it's running with a hacked dll.

I'm going down with the Win7 ship, so I'm on 1.47.186. Maybe this works in newer versions too? If it does, a patcher would only be a few lines of Python, a scheduled task and a line in the `hosts` file to drop `https://sync-v2.brave.com/v2`.

**Comment by GanerCodes** [comment]
cool, someone make a script to do this with the APK or something lol

**Comment by drajabr** [comment]
> if it really is that easy, its also really suspicious why they would not add this..

For real! I just started looking for alternative browser (using Edge for work, but Firefox at home with selfhosted sync) and my only requirement is self-hostable sync server, preferably to work cross platform (Windows + Linux + Android).

Brave would be the IDEAL choice if it had self-hostable browser, but it looks quite shady why they didn't implement one of the very basic features in a product marketed as a privacy focused, user data respecting browser! 
Apparently, someone want to keep the users attached to their servers for some reason...

**Comment by NicholasFlamy** [comment]
> > if it really is that easy, its also really suspicious why they would not add this..
> 
> For real! I just started looking for alternative browser (using Edge for work, but Firefox at home with selfhosted sync) and my only requirement is self-hostable sync server, preferably to work cross platform (Windows + Linux + Android).
> 
> Brave would be the IDEAL choice if it had self-hostable browser, but it looks quite shady why they didn't implement one of the very basic features in a product marketed as a privacy focused, user data respecting browser! Apparently, someone want to keep the users attached to their servers for some reason...

So on desktop I have been using the command line argument. On mobile I have been using the developer options QA Preferences menu and the command line string option.

**Comment by NicholasFlamy** [comment]
Brave QA code:
bbqkdk

**Comment by drajabr** [comment]
> So on desktop I have been using the command line argument. On mobile I have been using the developer options QA Preferences menu and the command line string option.

This is amazing! So I assume its possible to get a browser that do any outgoing connections I didn't tell it to make? I mean, I want to setup my sync server, but want to make sure that the browser is not sending any request except to my server, and ofc the web pages I only open, is that possible ..? I may setup a test few hours later, if that achievable then I'm definitely switching to brave!

**Comment by metal450** [comment]
> So if you want to be more secure about it you could firewall your setup and block the default brave sync server, on case your browser crashes and relaunches and therefore wasn't launched from the shortcut on desktop

Or it should just have a proper setting rather than using a command-line arg, which avoids this risk

**Comment by NicholasFlamy** [comment]
A hardened Firefox fork is what I'll go to if I stop using Brave because Firefox with a self-hosted sync server is easy, but Brave has an adblocker on mobile, HEVC/H.265 support because it's Chromium-based, and being Chromium-based means I'm never worried about website support.

**Comment by NicholasFlamy** [comment]
> > So if you want to be more secure about it you could firewall your setup and block the default brave sync server, on case your browser crashes and relaunches and therefore wasn't launched from the shortcut on desktop
> 
> Or it should just have a proper setting rather than using a command-line arg, which avoids this risk

This exactly.

**Comment by metal450** [comment]
> A hardened Firefox fork is what I'll go to if I stop using Brave because Firefox with a self-hosted sync server is easy, but Brave has an adblocker preinstalled (on mobile is why I care*), HEVC/H.265 support because it's Chromium-based, and being Chromium-based means I'm never worried about website support.
> 
> Edit: *I think Firefox has extension support on mobile.

Firefox does have adblock extension support on mobile. And Firefox is what I remain stuck using because Brave bafflingly refuses to fix this.

**Comment by bsclifton** [comment]
Hi folks - thanks for the enthusiasm for this feature.

To be completely transparent, I deleted a few posts. Off-topic posts and then one sharing a password for restricted functionality. I'll keep this locked for now as things went off topic.

With regards to this feature request being "so easy it's suspicious why they didn't do it"... There's nothing to be suspicious of, it's just simple logistics. If you look at our issue log... our issue count is (at the time of this comment) now at 7,705 issues. We're looking into the big ones first (crashes, proper bugs, data loss, etc). You can see this is assigned a P4. You can search for things with labels P1, P2, and P3 and those have been determined (as we triage issues) to have a higher priority. 

We'll do our best to get to this - I added it to a special tracking board "Papercuts" after noticing all the community attention it received.  I might know a contributor that might be interested in this - will share with them. Thanks for your patience

**Comment by davidstrauss** [comment]
> We'll do our best to get to this - I added it to a special tracking board ["Papercuts"](https://github.com/orgs/brave/projects/105) back in April

Just so you know, @bsclifton, this board is not publicly accessible.

**Comment by bsclifton** [comment]
@davidstrauss thanks for the heads up on that - try now please 😄 I just fixed

BTW - I took a stab at this over the weekend. It's not exactly trivial, but I do have something working. Will need to clean things up and then rebase/squash/write tests and submit for review

**Comment by NicholasFlamy** [comment]
> @davidstrauss thanks for the heads up on that - try now please 😄 I just fixed
> 
> BTW - I took a stab at this over the weekend. It's not exactly trivial, but I do have something working. Will need to clean things up and then rebase/squash/write tests and submit for review

You mentioned here that Android supports group policy:
https://github.com/brave/brave-browser/issues/29397#issue-1646608736

I haven't found any documentation provided by brave on this functionality. Is it the same as Linux? If not, could you please provide some information on this?

**Comment by NicholasFlamy** [comment]
> @davidstrauss thanks for the heads up on that - try now please 😄 I just fixed
> 
> BTW - I took a stab at this over the weekend. It's not exactly trivial, but I do have something working. Will need to clean things up and then rebase/squash/write tests and submit for review

Apparently, someone made a draft PR very recently: https://github.com/brave/brave-core/pull/25484

**Comment by bsclifton** [comment]
> > @davidstrauss thanks for the heads up on that - try now please 😄 I just fixed
> > BTW - I took a stab at this over the weekend. It's not exactly trivial, but I do have something working. Will need to clean things up and then rebase/squash/write tests and submit for review
> 
> Apparently, someone made a draft PR very recently: [brave/brave-core#25484](https://github.com/brave/brave-core/pull/25484)

Yup - I'm working together on this with @jagadeshjai. I'm getting the group policy part working - where the interception needs to happen. And then he can do the custom URL which will also need to show that field as read-only (non-editable) if group policy is set.

**Comment by bsclifton** [comment]
> > @davidstrauss thanks for the heads up on that - try now please 😄 I just fixed
> > BTW - I took a stab at this over the weekend. It's not exactly trivial, but I do have something working. Will need to clean things up and then rebase/squash/write tests and submit for review
> 
> You mentioned here that Android supports group policy: [#29397 (comment)](https://github.com/brave/brave-browser/issues/29397#issue-1646608736)
> 
> I haven't found any documentation provided by brave on this functionality. Is it the same as Linux? If not, could you please provide some information on this?

Hi @NicholasFlamy - I think the code is basically done at this point. I'll be adding a test plan for each OS. I'll dig in and see if it's possible to do w/ Android also (it should be, as far as I know). If it's not possible, I'll remove the `OS/Android` label. In that case the solution might be with https://github.com/brave/brave-browser/issues/12314

**Comment by bsclifton** [comment]
OK folks - this is merged 😄 

Unfortunately, I couldn't find a way to do Android group policy. I do believe it's possible - but I don't know at the moment though. If someone has more information, please do share it.

I'll work with @jagadeshjai on https://github.com/brave/brave-core/pull/25484 next

**Comment by NicholasFlamy** [comment]
> OK folks - this is merged 😄
> 
> Unfortunately, I couldn't find a way to do Android group policy. I do believe it's possible - but I don't know at the moment though. If someone has more information, please do share it.
> 
> I'll work with @jagadeshjai on [brave/brave-core#25484](https://github.com/brave/brave-core/pull/25484) next

I appreciate the work! If configuration through the UI is the solution for Android (and I assume same for iOS) then that's alright.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

Installed 1.72.85
opened Registry editor

Case 1: Using regedit.exe

1. opened Registry editor
2. navigated to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\`
3. navigated to the key (folders) BraveSoftware\Brave\  
4. created a new string value (REG_SZ) with the name `BraveSyncUrl` and the value `https://sync-v2.brave.com/v2`
5. launched Brave 
6. opened brave://policy/ in a new tab
7. confirmed `BraveSyncUrl` link is shown under `Policy name` column
8. confirmed `https://sync-v2.brave.com/v2` is shown under `Policy value` column
9. confirmed when clicked on the `BraveSyncUrl` link, it navigated to https://chromeenterprise.google/policies/?policy=BraveSyncUrl

step 4 | step 7-8 | step 9
----- | ------ | -----
![Image](https://github.com/user-attachments/assets/5e0fa4df-f3fd-400e-aac9-3ce965b250fd)|![Image](https://github.com/user-attachments/assets/4a66c7a5-9d57-47d7-843b-0f23c7ac49aa)|![Image](https://github.com/user-attachments/assets/fe01fba9-885e-45e9-a7d9-525cc1808563)

Case 2: Adding using a .reg file 

1. new profile
2. created a new empty file called `sync-policy.reg`
3. opened it in Notepad and put this for the content:
    ```
      Windows Registry Editor Version 5.00
       
       [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave]
       "BraveSyncUrl"="https://sync-v2.brave.com/v2"
 
4. saved the file and closed 
5. double clicked the `sync-policy.reg` file 
6. clicked `Yes` 
7. clicked `Ok`  
8. launched Brave
9. opened brave://policy/ in a new tab
10. confirmed `BraveSyncUrl` link is shown under `Policy name` column
11. confirmed `https://sync-v2.brave.com/v2` is shown under `Policy value` column
12. confirmed when hovered the `BraveSyncUrl`, correct URL is shown at the bottom left
13. confirmed registry keys (from steps 5-7) created as expected

step 2-3 | step 5-6 | step 7 | step 10-12 | step 13
----- | ------ | ------ | ------ | ------
![Image](https://github.com/user-attachments/assets/4acb51af-14ec-4d8c-8016-88b61d265f16)|![Image](https://github.com/user-attachments/assets/4ba321f4-a1a7-4897-8688-8ad29b460b99)|![Image](https://github.com/user-attachments/assets/bdecbdb8-53bb-4caa-80e3-2e0f6aa8d5f8)|![Image](https://github.com/user-attachments/assets/99dbfa0a-fa04-430f-8f26-6e3a23ba8fa0)|![Image](https://github.com/user-attachments/assets/9aa37938-0fdf-4ec0-a4e6-73b40a18e47a)

**Comment by DaCHack** [comment]
@MadhaviSeelam Great, thanks! Can you confirm whether there is also work going on to enable it on iOS?
There is no brave://policy/ in the iOS app.
This would finally enable syncing tabs and other items between desktop and mobile.

**Comment by NicholasFlamy** [comment]
> [@MadhaviSeelam](https://github.com/MadhaviSeelam) Great, thanks! Can you confirm whether there is also work going on to enable it on iOS? There is no brave://policy/ in the iOS app. This would finally enable syncing tabs and other items between desktop and mobile.

They're working on a GUI option that will handle mobile as well (since afaik mobile doesn't have policies): https://github.com/brave/brave-core/pull/25484

**Comment by bsclifton** [comment]
Unfortunately, I'm not sure how to do group policy on iOS and Android. I believe it's possible, I just don't know how

@NicholasFlamy thanks for linking the custom URL one. That will solve for Desktop. We'll need to do a similar pull request for Android and iOS to enable changing sync URL.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (arm64)
-- | --
Revision | 69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS | macOS Version 14.6.1 (Build 23G93)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.73.86 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | 52163bcf4e40f27ddb76ffa79c90a8833084a9bd
OS | Linux
```
