### ISSUE TITLE
Inexact amounts in transaction confirmation screen

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20432]
Extracted out from https://github.com/brave/brave-browser/issues/20264.

☠️ A critical bug as a result of storing amounts in native currency units. 👇

https://user-images.githubusercontent.com/3684187/148872532-6bba6b03-a682-45c3-b77d-862b48d54aaf.mov

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11938>brave/brave-core#11938</a></li>
         <li>Verified input value is not truncated and shows the full value on the transaction confirmation screen</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/154916352-33e40e3c-c66d-4bd0-9b97-bb4ad9ebc0ca.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/154915978-92ffc34c-0245-4903-bae6-2df6497c16ce.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/154915763-3a20e839-2ebd-47e6-9a1e-e186f0b16699.png>
      </td>
   </tr>
</table>
