### ISSUE TITLE
[Android] User is able to get around Rewards opt-in modal and user is trapped on brave://rewards when Rewards opt-in modal appears

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20447]
## Description

1. Fresh profile or without Rewards opt-in
2. Go to brave://rewards
3. Notice that onboarding modal appears and grays out the Rewards page
4. Android UI elements (like URL bar) are untouchable, and back does not do anything. User feels trapped.
5. However, user can get around this by pressing "Take a quick tour", which opens the Rewards panel. If the user taps Rewards panel/dismisses it, then they are now on the Rewards settings page with no onboarding blocking them, even though they haven't opted in/enabled Rewards yet.

## Solution

1. I propose we keep Android UI elements (like URL bar) tappable in step 4.
2. We should also always find a way to show onboarding modal to block user interaction on brave://rewards page if Rewards is not enabled.

**Comment by srirambv** [comment]
+1 on this. Tapping outside the opt-in modal should dismiss it and not force user to start tour and then exit.

**Comment by srirambv** [comment]
+1 from @PascalDk via #21290. @Miyayes maybe prioritize the issue and have it fixed for 1.38.x

**Comment by diracdeltas** [comment]
+1 from Habr: https://habr.com/en/company/brave/blog/598279/#comment_24103751
