### ISSUE TITLE
Web Discovery Project - "More Info" link inside Settings > Search is wrong

### ISSUE THREAD

**Issue by alosarjos** [brave/brave-browser#20453]
## Description 
The URL for more info of the Web Discovery Project is wrong inside the Settings > Search view

![Captura de pantalla de 2022-01-11 19-12-25](https://user-images.githubusercontent.com/29999427/148998283-29ad4b02-b8af-4746-b178-7ff29cc49d95.png)

## Steps to Reproduce

   1. Click on the link
   2. Get a 404

## Actual result:

![Captura de pantalla de 2022-01-11 19-12-57](https://user-images.githubusercontent.com/29999427/148998361-eca61160-1219-4ce9-befb-414215f6cff2.png)

## Expected result:

Go to the correct URL

## Reproduces how often: 
Always

## Brave version (brave://version info)
1.34.80

## Version/Channel Information:
Stable

I'm providing a MR on brave-core with the fix

**Comment by rebron** [comment]
New link should be:`https://brave.com/privacy/browser/#web-discovery-project`

**Comment by alosarjos** [comment]
Yeah, I made a PR: https://github.com/brave/brave-core/pull/11813

**Comment by rebron** [comment]
We'll get the redirect in place for this one. Thanks for the report and pr @alosarjos

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.36.82 Chromium: 98.0.4758.87 (Official Build) beta (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)
```

Verified STR from description.
Confirmed link directs to `https://brave.com/privacy/browser/#web-discovery-project` as per https://github.com/brave/brave-browser/issues/20453#issuecomment-1011405371.

<img width="1199" alt="Screen Shot 2022-02-02 at 11 07 25 AM" src="https://user-images.githubusercontent.com/28145373/152191704-9e495ae4-3d27-47ce-bd70-fa12f2fbe695.png">
