### ISSUE TITLE
Use different wording for "Log out from {custodian name}" when user is in Logged Out state

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20451]
## Description

State is called "Logged out", however an option to "Log out from {custodian}" also appears, which could be a little confusing. 

![image](https://user-images.githubusercontent.com/11497541/148986177-f2dd0566-03cd-4a6e-8d12-eaaefa2dd842.png)

## Solution

Use "Disconnect from {custodian}" language in this case.

**Comment by Miyayes** [comment]
Change to "Disconnect from Uphold"

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.47 Chromium: 97.0.4692.71 (Official Build) nightly (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)

Steps (for each custodian):
1. new profile
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3. loaded `brave://rewards`
4. clicked on `Start using Rewards`
5. clicked on `Verify Wallet`
6. entered test credentials
7. returned to `brave://rewards` / clicked on the BAT icon
8. clicked on the `My Wallet` dropdown
9. examined the text

bitFlyer | Uphold | Gemini
--------|--------|--------
 . | <img width="1237" alt="Screen Shot 2022-01-19 at 2 02 00 PM" src="https://user-images.githubusercontent.com/387249/150230147-46acda6b-775d-4ccf-b77e-ab48fcbde6cd.png"> | <img width="1312" alt="Screen Shot 2022-01-19 at 2 32 23 PM" src="https://user-images.githubusercontent.com/387249/150230411-fe7708b3-46c7-4eba-b0b6-f28e02b0aaae.png">
