### ISSUE TITLE
[Android] inconsistent UI for Disconnected/Logged out state

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20450]
## Description 
Found while testing https://github.com/brave/internal/issues/838

When simulating natural disconnect, the panel and chrome://rewards / brave://rewards page have different UI.

Panel:
- says "Disconnected" 
- has the gray UI
- Tapping on "Disconnected" opens brave://rewards/#verify but doesn't close the panel (this feels weird)

rewards page 
- Says "Logged out"
- no gray UI
- Tapping on "Logged out" shows dropdown with options

## Steps to reproduce 

1. Clean install
2. Navigate QA Preferences
3. Enable staging environment, relaunch as necessary
4. Enable Rewards
5. Select Verify Wallet and login with custodial account
6. Confirm balance is shown in UI
7. On custodial site, revoke access to Brave Browser (where applicable)
8. Compare UI on panel and rewards page.

Need to verify this for Uphold, Gemini, and bitFlyer custodians.

Note, there is no notification alerting the user that they need to log back in. This is covered under https://github.com/brave/brave-browser/issues/9576.

## Actual result 

Panel | brave://rewards | brave://rewards
----- | ----- | -----
![panel](https://user-images.githubusercontent.com/28145373/148981230-a1f99da6-6825-4a16-9f30-997fc04031fa.png) | ![rewards page 1](https://user-images.githubusercontent.com/28145373/148981239-f817823e-f1c4-4e05-9f9f-75b4cc45fe20.png) | ![rewards page 2](https://user-images.githubusercontent.com/28145373/148981246-a2fdf129-06d6-4d70-af33-e16f3e912588.png)

## Expected result

Per discussion with @Miyayes:

Rewards settings page is more correct. I think when tapping on “Disconnected” via Panel, it should open that white menu (similar to when they’re verified) and give option to log into your Uphold account. (Please note: https://github.com/brave/brave-browser/issues/20452) 

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  n/a
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.35.77

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes @deeppandya cc @brave/legacy_qa

**Comment by deeppandya** [comment]
@Miyayes i think this issue is invalid as we have only verified/unverified state. WDYT ?

**Comment by Miyayes** [comment]
> @Miyayes i think this issue is invalid as we have only verified/unverified state. WDYT ?

There should be three states:

1. Unverified
2. Verified
3. Logged out

Logged out = OAuth access token has expired

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.48.141.
