### ISSUE TITLE
Brave Wallet / Brave Swap: Displaying Brave DEX Aggregator on Android

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#20463]
## Description 

On mobile (confirmed on Android, uncertain on iOS), in the Swap feature, we reference the Brave DEX Aggregator. See image below. 
![Screenshot_20220111-162539_Brave](https://user-images.githubusercontent.com/8979240/149050607-92bc5c3e-f996-45fb-ab51-fc9f5c5b8193.jpg)

We should remove the Brave DEX Aggregator reference from the Swap feature text. 

Something like "Swap tokens for tokens" or some such may work well to replce. 

## Steps to Reproduce

   1.  Open Brave Wallet on mobile
   2. Tap Send/Receive/Swap <> arrow icon
   3. See Swap feature copy

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Seems to be just mobile issue that was missed. Desktop uses `Brave uses 0x as a DEX aggregator.` on both widget and panel

Panel | Widget
-- | --
![image](https://user-images.githubusercontent.com/17010094/149054441-a27f50c1-c338-42b2-8ed5-6005fd6dbc0d.png) | ![image](https://user-images.githubusercontent.com/17010094/149054551-d4a887a3-cde2-4ed6-829e-96d484c475de.png)

**Comment by SergeyZhukovsky** [comment]
@srirambv we have exactly the same text on a Swap screen on Android. The issue is about text before you go to a swap screen
![Screenshot_20220125-111601_Brave - Debug](https://user-images.githubusercontent.com/12011303/151013790-2bb43562-96dc-40cd-aef5-03cfae14fdae.jpg)

**Comment by Pavneet-Sing** [comment]
@srirambv this also has iOS label on it so could you please confirm if this is there on iOS?, then probably we will create an iOS issue for same. BTW, new label is "Swap tokens and assets".

**Comment by srirambv** [comment]
@Pavneet-Sing yes this is an issue on iOS as well. Its only on the Buy/Send/Swap main screen not on the individual feature screen. 

This is on iOS 
<img width=300 src=https://user-images.githubusercontent.com/17010094/151492177-0d9e97ac-db52-41ec-a2df-e467753a3c00.png>


I'll add an iOS specific issue as well

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.37.89 x64 beta build
- Verified Swap option now has the description of `Swap tokens and assets`

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/157842522-65fb7317-b309-472b-9734-63107d969948.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/157842558-1be7d20a-0a00-4668-bb51-01d4cace53ee.png>
