### ISSUE TITLE
[Android] Add padding/margin at top of brave://rewards settings page "View details" subsections

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20462]
## Description

1. On Android, go to brave://rewards
2. Go to "View details" on any subsection (Brave Private Ads, Monthly Contributions, etc.)
3. Note that padding/margin is missing at the top, which makes the back arrow and the feature ON/OFF toggle hard to hit

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.36.75, Chromium 98.0.4758.66` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

Ads | after | Auto-Contribute | after | Monthly Contributions | after | Tips | after
-------|------|--------|------|-------|------|--------|-----
![Screenshot_20220127-142634](https://user-images.githubusercontent.com/387249/151454478-537561a4-358e-4c21-b7e3-1fb3ef356481.png) | ![Screenshot_20220127-142745](https://user-images.githubusercontent.com/387249/151454481-fa0a136c-9e83-43e5-967f-11fc74fed3b7.png) | ![Screenshot_20220127-142642](https://user-images.githubusercontent.com/387249/151454823-0aae8faa-e2f5-4cd3-87d6-f00efbb534f0.png) | ![Screenshot_20220127-142757](https://user-images.githubusercontent.com/387249/151454827-947b4332-474c-4daa-b2f7-b81e5724a0e3.png) | ![Screenshot_20220127-142649](https://user-images.githubusercontent.com/387249/151454923-5a7366e6-0447-4f89-a982-b88e627a5e9b.png) | ![Screenshot_20220127-142805](https://user-images.githubusercontent.com/387249/151454932-c667f9ef-ff77-4604-a9a2-8355421d0a68.png) | ![Screenshot_20220127-142654](https://user-images.githubusercontent.com/387249/151455007-8de2536e-1452-421f-b46a-0a3e43038573.png) | ![Screenshot_20220127-142811](https://user-images.githubusercontent.com/387249/151455011-0aa448bd-b161-4aa1-8f75-7e1b9448681f.png)
