### ISSUE TITLE
Update Recent Transactions Icon in Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20472]
## Description 

1) Update the `Recent transactions` icon in the `Panel` from the `lightningbolt` to a `history` icon
2) Fix header title from `Recent Transactions` to `Recent transactions` should be sentence casing

You can find the specs for this component in Figma / Desktop Crypto Wallets.

Add the component too storybook with mock data for testing.

## Expected result:

Component should be visible and functional in Storybook under the Wallet/Desktop/Concepts tab.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.83 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11825>brave/brave-core#11825</a></li>
         <li>Verified Recent transactions icon in the <code>Panel</code> is changed from <code>lightningbolt</code> to <code>history</code> icon</li>
         <li>Verified <code>Recent Transactions</code> is changed to <code>Recent transactions</code> following sentence casing</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/152528374-869bcdc8-4820-4112-a9ff-1ca906cc78a0.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152528392-9b2c0f4f-6f58-4494-9cf8-25d949d5158a.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/152528383-4d77774b-2270-4d50-90ea-b23f965289f9.mov>
      </td>
   </tr>
</table>
