### ISSUE TITLE
Replace network selector

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#20471]
With a support of different chains we want to change a network selector from a dropdown to some kind of modal dialog. Check with @jamesmudgett on a design before doing that task. We have some draft in a spec, but there was a discussion in slack that we should do it different.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.38.103
- Verified steps from [brave/brave-core#12396](https://github.com/brave/brave-core/pull/12396)
- Verified network selector screen is shown when the network drop down is clicked
- Verified selecting network and going back sets the new network 
- Encountered [#22424](https://github.com/brave/brave-browser/issues/22424) & [#22425](https://github.com/brave/brave-browser/issues/22425)

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/164283699-9755c05a-df1a-4d14-ba48-512f80a289f0.mp4> | <video src=https://user-images.githubusercontent.com/17010094/164283412-80a48e01-9dac-442e-87c4-e909363cfacf.mp4>
