### ISSUE TITLE
Unstoppable Domain support for Polygon Network

### ISSUE THREAD

**Issue by kodxana** [brave/brave-browser#20475]
## Description 

In November 2021 Unstoppable Domain added option to free mint on Polygon network. As I noticed Brave only resolve domains from ETH network and fails on Polygon ones.

## Steps to Reproduce

   1. Go to domain minted on Polygon ex. madiator.wallet/
   2. Page wont load cause DNS resolve error.
 

## Actual result:

DNS_PROBE_POSSIBLE

## Expected result:
Page should be resolved corectly.

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Brave	1.34.80 Chromium: 97.0.4692.71
OS: Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@bbondy @srirambv please remove from the `Wallet` project if this isn't applicable.

**Comment by DeepDoge** [comment]
I believe this belongs to https://github.com/brave/brave-browser/projects/32

**Comment by bbondy** [comment]
Probably belongs on both boards, thx.

**Comment by tiffisucks** [comment]
still not working ... no news on here?

**Comment by heyoka404** [comment]
Hi. Any timeframe for this? we all appreciated the hard work, Thanks!

**Comment by dallastexas92** [comment]
Any update? Still not working

**Comment by supermassive** [comment]
> Any update? Still not working

Work in progress.

**Comment by supermassive** [comment]
Done with https://github.com/brave/brave-browser/issues/22147

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/22147#issuecomment-1139471688
