### ISSUE TITLE
brave://settings/ipfs/keys is blank

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#20485]
## Description 

![ipfs-keys](https://user-images.githubusercontent.com/2965009/149316601-555181d5-2677-4eec-a1b5-71bcde62db62.gif)

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `ipns://en.wikipedia-on-ipfs.org`
   4. click on `Use a local node` at the interstitial screen
   5. open `brave://settings/ipfs`

## Actual result:

IPNS keys are not visible

## Expected result:

IPNS keys are visible

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Removing `QA Pass-macOS` as this was uplifted into `1.34.x` via https://github.com/brave/brave-core/pull/11861 and should be re-tested once we have a `1.34.x` RC. The verification that @stephendonner completed via https://github.com/brave/brave-browser/issues/20485#issuecomment-1012605666 was needed either way to get the above uplifted.

**Comment by LaurenWags** [comment]
updated to be `release-notes/exclude` as this fixes the same issue as https://github.com/brave/brave-browser/issues/20341 which is already `release-notes/include`.

**Comment by stephendonner** [comment]
Verified `PASSED` using  

Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | macOS Version 11.6.1 (Build 20G224)

Notes over in https://github.com/brave/brave-browser/issues/20341#issuecomment-1017956620.
