### ISSUE TITLE
Brave Browser Not Allowing Dropbox File Download

### ISSUE THREAD

**Issue by xxxsskxxx** [brave/brave-browser#20484]
## Description 

Using the desktop version of brave (latest is installed), when I am trying to download the file below I receive a 'There was an error downloading your file' message at the top of the page in red.  This URL / file download works fine with Microsoft Edge and Google Chrome

https://www.dropbox.com/sh/0n37s3j3iybww9q/AABN74pzb3CMJBiI76r4jZ48a?dl=0&preview=kodinerds-20220105-25148d187c-Matrix-arm64-v8a.apk

## Steps to Reproduce

   1. Go to URL - https://www.dropbox.com/sh/0n37s3j3iybww9q/AABN74pzb3CMJBiI76r4jZ48a?dl=0&preview=kodinerds-20220105-25148d187c-Matrix-arm64-v8a.apk
   2. Select the small down arrow next to the Download text towards the bottom of the page
   3. A small sub menu will appear
   4. Click 'Download'
   5. Error appears everytime

## Actual result:
Screenshot
![image](https://user-images.githubusercontent.com/96975040/149301532-bc30278d-9226-4fb3-a6c7-efab40e7d99e.png)

## Expected result:

File should download to your desktop / location of choice

## Reproduces how often: 
Can be reproduced all the time

## Brave version (brave://version info)

1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel? - Checking
- **Cant**  reproduce this issue with the nightly channel using same extensions and settings applied

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - No
- Does the issue resolve itself when disabling Brave Rewards? - No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
Link is dead, is this still an issue with the latest Brave build? @xxxsskxxx
