### ISSUE TITLE
Don't see an issue in here for brave upgrading to chrome 97.0.4664.87

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#20495]
I have searched and searched and can't find a ticket or issue that says brave is going to be updated to chrome 97.0.4664.87. Normally I see an issue stating upgrade patch to new chrome version but for this version I have not found an issue like that. if I am mistaken forgive me. Thanks

**Comment by rebron** [comment]
See https://github.com/brave/brave-browser/issues/20553.

**Comment by rebron** [comment]
Closing as invalid.
