### ISSUE TITLE
[Android] Notify Uphold-verified users if they have to complete customer due diligence with Uphold

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20497]
Android version of https://github.com/brave/brave-browser/issues/20427.

**Comment by LaurenWags** [comment]
Verification in progress with `1.35.97 Chromium: 98.0.4758.72` on Google Pixel 3 XL running Android 12.

Note - the "Disconnected" panel notification is not implemented on Android, see https://github.com/brave/brave-browser/issues/20603

<details>
<summary>Scenario 1: Clean install - PENDING ==> NOT_CONNECTED - PASSED</summary>

Pre-req: Use Charles Proxy to simulate CDD required or use an Uphold sandbox account in this state.

1. Clean install w/ staging parameters
2. Enable Rewards
3. Link KYC'd account which has CDD "required"
4. Confirm you get modal on brave://rewards page
5. Confirm link on modal directs to `https://wallet.uphold.com/customer-due-diligence` (staging or production env, both link to the same place)
6. Confirm close closes the modal
7. Open the panel
8. Confirm that no notification is shown on the panel

Settings Page | Panel
----- | -----
![1](https://user-images.githubusercontent.com/28145373/151607490-02ea4ed2-1c67-4ea4-a776-2832c9654471.png) | ![2](https://user-images.githubusercontent.com/28145373/151607499-55d44757-22b5-4e3f-af92-433971018cb7.png)

</details>

<details>
<summary>Scenario 2: Upgrade - VERIFIED ==> DISCONNECTED_VERIFIED (brave://rewards tab active) - TBD</summary>

Pre-req: Use Charles Proxy to simulate CDD required or ask for your Uphold sandbox account to be put into this state.

1. Clean install 1.34.x w/ staging parameters
2. Enable Rewards
3. Link KYC'd account which has CDD "required"
4. Confirm you are logged in without any problem (UI reflects this, your balance is displayed on settings and panel, etc)
5. Have brave://rewards page open and as the active tab
6. Upgrade to 1.35.x 
7. Confirm you get modal on brave://rewards page
8. Confirm link on modal directs to `https://wallet.uphold.com/customer-due-diligence` (staging or production env, both link to the same place) 
9. Confirm close closes the modal
10. Open the panel
---> notification is not displayed, see https://github.com/brave/brave-browser/issues/20603

Note - different UI on settings page and panel for disconnected state is logged and will be handled separately, known issue not related to this PR.

Settings Page before upgrade | Panel before upgrade | Settings page after upgrade - modal | Settings page after upgrade - modal closed | Panel after upgrade
----- | ----- | ----- | ----- | -----

</details>

<details>
<summary>Scenario 3: Upgrade - VERIFIED ==> DISCONNECTED_VERIFIED (brave://rewards tab not active) - TBD</summary>

Pre-req: Use Charles Proxy to simulate CDD required or ask for your Uphold sandbox account to be put into this state.

1. Clean install 1.34.x w/ staging parameters
2. Enable Rewards
3. Link KYC'd account which has CDD "required"
4. Confirm you are logged in without any problem (UI reflects this, your balance is displayed on settings and panel, etc)
5. Close brave://rewards page if open
6. Upgrade to 1.35.x
7. Open the panel 
---> notification is not displayed, see https://github.com/brave/brave-browser/issues/20603
8. Navigate to brave://settings
9. Confirm no modal shown

Settings Page before upgrade | Panel before upgrade | Panel after upgrade | Settings page after upgrade
----- | ----- | ----- | ----- 

</details>
