### ISSUE TITLE
Can't import: "To finish importing, close all Chrome windows."

### ISSUE THREAD

**Issue by goocreations** [brave/brave-browser#2049]
## Description 
In the new beta, when using the "Import bookmarks and settings" option under Linux (Ubuntu) and one selects a profile from Chrome, the following message shows:

_To finish importing, close all Chrome windows._

Although Chrome is closed and not showing at all under the process list. This only happens on Linux, Windows works fine. Might be something wrong with the code that detects if Chrome is running.

## Steps to Reproduce

   1. Have Chrome open and then open Brave.
   2. Go to Settings -> Import bookmarks and settings
   3. Select one of the detected Chrome Profiles. A popup dialog will show with the message "To finish importing, close all Chrome windows."

## Expected result:

Settings from Chrome being imported.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave	0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
Revision	c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS	Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Both beta and dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by amilleranalytics** [comment]
Same problem, cannot import bookmarks and settings with error message: "To finish importing, close all Chrome windows." when Chrome not running.

Brave	0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
Revision	c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS	Linux Ubuntu 18.04.1 LTS 
Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by acramatte** [comment]
I had the same issue trying to import everything from my old brave.

Somehow by not checking the 'Browsing history' from the items to import it ended up working. I could then re-do the import and this time check the 'Browsing history' and now everything has been imported.

Not sure if that helps.

Old Brave: 0.25.304 with Muon 8.1.8
New Brave: Version 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
MacOS X High Sierra 10.13.4

**Comment by mlabieniec** [comment]
Same issue here

Ubuntu 18.10
Brave: Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Chromium: Version 71.0.3578.80 (Official Build) Built on Ubuntu , running on Ubuntu 18.10 (64-bit)

Unchecking Browser history didn't work for me still stuck on "Close all chrome windows"

**Comment by srirambv** [comment]
Cant reproduce this issue. @goocreations @subat0mik @amilleranalytics do you guys have Google Hangouts extension running on your Chrome? If so there might be a background process running it which has locked the Chrome process.

**Comment by goocreations** [comment]
No, no Hangouts extension installed or running. I tried this by restarting Ubuntu and not opening Chrome at all. I also checked the process list and as far as I can see there is no Chrome-related process running.

Any reason why Chrome must be closed? Seems like a read operation. If nothing is written to Chrome, then why not just import with Chrome "running"? Haven't checked the code, so might be a stupid suggestion.

**Comment by jessehonig** [comment]
I had the same issue. I fixed it by disabling and removing my DuckDuckGo extension from my Chrome Browser  and then refreshing my Brave page.

**Comment by goocreations** [comment]
Ahh, DuckDuckGo might be the issue.

**Comment by amilleranalytics** [comment]
Unfortunately, I do not have the DuckDuckGo extension installed on 
Chrome or Brave.  Still unable to import Chrome bookmarks into Brave :-(.

I was able to import my Chrome bookmarks by first exporting them from 
Chrome to an HTML file and then importing the file into Brave.  But the 
"unable to import Chrome bookmarks error" in this this ticket still 
manifests, which would be very off-putting to new users.


Brave logoBrave
Version 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)

Ubuntu 18.04.1 LTS

**Comment by jmd1011** [comment]
New user trying to switch -- can agree, it's very off-putting. :(

Is there no resolution?

**Comment by jeremy-flusin** [comment]
If anyone on Ubuntu is still encountering this issue :

On Ubuntu, Chrome has a process on the top-right corner bar which keeps the lock file :
 
![chrome](https://user-images.githubusercontent.com/5628536/64534493-da321500-d315-11e9-952b-ce7f0f626f69.png)

After killing it by right-clicking, I was able to import my settings. If it does not work, try remove your lock file located at : `~/.config/google-chrome/SingletonLock`

That is to say that it's not a problem with Brave itself, btw.

**Comment by BikashPandey17** [comment]
On Windows, the issue might be because chrome continues running background apps even when it is closed. Turning this feature off in [chrome -> settings -> system(Advanced)](chrome://settings/system)  worked for me.

**Comment by bsclifton** [comment]
@jeremy-flusin great solution - that is what I've had to do also (on macOS, Linux, and Windows). Depending on the platform, the Chrome profile directory is different. 

Sometimes, launching and then exiting Chrome would be enough to properly clean it up. But there were several times where this wouldn't work

**Comment by bsclifton** [comment]
We should be able to fix this - I believe we put a check in place for the Muon import, that would remove the files. Would need to investigate more

Definitely not a bug with Brave, but something we can handle more elegantly (by trying to delete the lock file)

cc: @rebron

**Comment by juanaguillon** [comment]
I solved it.
Entry to google chrome and disable all extensions and aplications.

Try again importing on brave.

Hope you help.

**Comment by bsclifton** [comment]
Bumping up to a P3 since this seems to be broken for many users and import is an important feature

**Comment by debugster** [comment]
> If anyone on Ubuntu is still encountering this issue :
> 
> On Ubuntu, Chrome has a process on the top-right corner bar which keeps the lock file :
> 
> ![chrome](https://user-images.githubusercontent.com/5628536/64534493-da321500-d315-11e9-952b-ce7f0f626f69.png)
> 
> After killing it by right-clicking, I was able to import my settings. If it does not work, try remove your lock file located at : `~/.config/google-chrome/SingletonLock`
> 
> That is to say that it's not a problem with Brave itself, btw.

Removing the SingletonLock file solved my issue. Thanks.

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the STR from the description
- Verified that settings, bookmarks, and extensions are imported to brave even when chrome is opened
