### ISSUE TITLE
Add support on the front end side for other blockchain registry tokens 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20494]
Create a file here:
```
~/Library/Application\ Support/BraveSoftware/Brave-Browser-Development/BraveWallet/1.0.11/evm-contract-map.json
```

(Note adjust the above path depending on which channel you're using and which OS)

with contents:
```
{
  "0xad6d458402f60fd3bd25163575031acdce07538d": {
    "name": "DAI Stablecoin",
    "logo": "dai.png",
    "erc20": true,
    "symbol": "DAI",
    "decimals": 18,
    "chainId": "0x3"
  },
  "0x07865c6e87b9f70255377e024ace6630c1eaa37f": {
    "name": "USD Coin",
    "logo": "usdc.png",
    "erc20": true,
    "symbol": "USDC",
    "decimals": 6,
    "chainId": "0x3"
  }
}
```

Then add support on the front end to be able to handle tokens from the registry for other networks, not only mainnet. 
https://github.com/brave/brave-core/pull/11791

The above adds 2 tokens to Ropsten and in the PR above it will parse those and make them available. 

Note that in an update of the brave wallet data files component soon, we'll include the same file and the same contents.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.93 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from<a href=https://github.com/brave/brave-core/pull/11881>brave/brave-core#11881</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/154063231-d9aee50c-aa6b-4892-9131-6da59a219215.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154065289-327fa13e-ecd7-4937-a567-726c5633e812.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154065012-7103b5a3-6d0c-496a-a874-87aee0d0ee3e.mov>
      </td>
   </tr>
</table>
