### ISSUE TITLE
Brave DevTools settings not persisting after closed

### ISSUE THREAD

**Issue by JoaoHamerski** [brave/brave-browser#20491]
## Description 
The settings for developer panel (F12) just doesn't persist, any checkbox or option i try to change is reseted after i restart the browser, already tried to reinstall the browser, i even reinstalled the OS

## Steps to Reproduce
   1. Press F12 to open developer panel
   2. Press F1 to open settings
   3. Check any checkbox or uncheck it, for example, "Log XMLHttpRequests"
   4. Restart the browser or just close the dev-tools.

## Actual result:
The option will be reseted to default.

## Expected result:
The option setted should persist.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.34.80 Chromium: 97.0.4692.71 (Official version) 64 bits
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
SO | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No

- Does the issue resolve itself when disabling Brave Rewards? 
No

- Is the issue reproducible on the latest version of Chrome? 
No, on Chrome it's working as intended.

**Comment by JoaoHamerski** [comment]
So am i the only one having this annoying issue? I'm using Chrome until this get fixed, i need "Log XMLHttpRequest" settings on to web development but every time it gets disabled.

**Comment by hugonasciutti** [comment]
> So am i the only one having this annoying issue? I'm using Chrome until this get fixed, i need "Log XMLHttpRequest" settings on to web development but every time it gets disabled.

I am having the same problem as well, any configuration is lost when dev-tools is closed and reopen, I don't even need to restart the browser for it to happen. I noticed this when I added a new Custom Device for testing, and lost every time I reopen dev-tools.

## Brave version (brave://version info)
Brave | 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Linux

**Comment by JoaoHamerski** [comment]
@hugonasciutti I just tested and can confirm now, this bug happens when dev-tools is closed, i just updated the issue title to a more accurated one.

**Comment by cyress** [comment]
Related tickets: #20075, #19530, #19509, #19871

**Comment by JoaoHamerski** [comment]
Still not fixed on Brave "stable" 1.35.100

**Comment by twopills** [comment]
> Still not fixed on Brave "stable" 1.35.100

I tried version 1.35 now, to me it seems to work.

**Comment by JoaoHamerski** [comment]
@twopills  It's really still bugged to me. 

I just open devtools > settings > enable LogXMLHTTPRequest > close devtools > open it again > LogXMLHTTPRequest is disabled.

Also the changelog not mentioned anything about it.

**Comment by LeonFedotov** [comment]
very annoying, back to chrome >:(

**Comment by Lemonawa** [comment]
I also have the same problem.Fuck that nobody replied me :-1:

**Comment by KnifeFed** [comment]
Why isn't anybody from the Brave team even acknowledging this issue, anywhere?

**Comment by twopills** [comment]
> @twopills It's really still bugged to me.
> 
> I just open devtools > settings > enable LogXMLHTTPRequest > close devtools > open it again > LogXMLHTTPRequest is disabled.
> 
> Also the changelog not mentioned anything about it.

Hey @JoaoHamerski now i try and i have the bug . Sh*t

**Comment by Lemonawa** [comment]
I back to chrome. 👎

**Comment by hugonasciutti** [comment]
Hey @rebron or @JoaoHamerski, could you add this issue with the bug label for this issue get a higher priority?

**Comment by bsclifton** [comment]
Quick update for anyone subscribed - this is fixed in our latest Nightly and will be making it to Beta and Release versions soon

**Comment by kjozwiak** [comment]
Above will require `1.37.101` or newer for `1.37.x` verification.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.37.106 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
