### ISSUE TITLE
Phone model leaking with navigator

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#20499]
## Description 
Users phone model leaks with javascript navigator

## Steps to Reproduce

   1. Go to https://abrahamjuliot.github.io/creepjs/
   2. Scroll dowm
   3. See your phone model being shown

## Expected result:
The results should be faked, or brave should disable the feature by default

## Reproduces how often: 
Easily reproduced

## Android Device details:
   - Install type (ARM, x86): arm
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 10

## Version/Channel Information:
Every brave versions and channels seems to have this issue 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes, but chrome dose not aim for hiding users phone model

**Comment by diracdeltas** [comment]
cc @pes10k - i know we discussed removing phone model in android UA but not sure if we actually did it

**Comment by pes10k** [comment]
Yea, @pilgrim-brave did, back in https://github.com/brave/brave-core/pull/8320 and https://github.com/brave/brave-core/pull/8562 .  I don't have an android device to test with.  @pilgrim-brave could you take a look tomorrow when you're online?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.35.101 x64 build
- Verified steps from issue description
- Verified phone model is not shown 

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/153127522-f547eb43-504c-47a3-9799-b881deedaa58.mp4> | <video src=https://user-images.githubusercontent.com/17010094/153128307-f6a0aaea-72b2-4801-9971-6a6b4e4e24c7.mp4>
