### ISSUE TITLE
Add Custom Devices Bug

### ISSUE THREAD

**Issue by twopills** [brave/brave-browser#20506]
## Description 

Yesterday after opening the tool inspection and clicking on the responsive mode icon, I saw that the custom profiles of the size and preferences on which devices to show in the dropdown were brought back to the default settings.
Then yesterday I fixed everything again, then later I realized that they were reset again. 

## Steps to Reproduce

   1. Right click > Inspector
   2.  Ctrl + shift + m
   3.  Dimension: Responsive -> Click -> Edit...

## Actual result:

N/A

## Expected result:

After i save a profile with dimension of screen, it remain in memory.

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

1.34.80 Chromium: 97.0.4692.71 (Build ufficiale) (a 64 bit)

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  N/a
- Can you reproduce this issue with the nightly channel? N/a 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  N/a
- Does the issue resolve itself when disabling Brave Rewards?  N/a
- Is the issue reproducible on the latest version of Chrome?  Nope

**Comment by twopills** [comment]
Up

**Comment by rebron** [comment]
Looks like a dupe of https://github.com/brave/brave-browser/issues/20506?

**Comment by twopills** [comment]
> Looks like a dupe of #20491?

Yes, thanks.
