### ISSUE TITLE
FTX widget causing requests to ftx.com at startup without user opt-in

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#20501]
## Steps to Reproduce

   1. Run browser through a proxy such as mitmproxy:
```
mitmproxy --mode socks5 --listen-port 9000
brave-browser-stable --user-data-dir=/home/francois/brave-temp-profile --proxy-server="socks5://localhost:9000"
```
   2. Create a new browser profile.
   3. Start the browser.
   4. Wait until the NTP has been shown.

## Actual result:
![Screenshot from 2022-01-13 17-21-26](https://user-images.githubusercontent.com/167821/149438092-b8bbdf61-b4ff-4693-aa66-d9b7f172c524.png)

## Expected result:
No requests to ftx.com should occur unless the user has interacted / signed into the FTX widget.

## Reproduces how often: 
Always

## Brave version (brave://version info)
```
Brave | 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Linux

```
## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel?  YES
- Can you reproduce this issue with the nightly channel? YES

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | macOS Version 11.6.1 (Build 20G224)

`Clean Install Cases`

Verified the STR/Cases outlined via [brave/brave-browser#20501 (comment)](https://github.com/brave/brave-browser/issues/20501#issue-1102759124) and ensured that there wasn't any outbound network connections when opening the NTP on a new profile. Example:

<img width="1680" alt="Screen Shot 2022-01-20 at 2 29 57 PM" src="https://user-images.githubusercontent.com/387249/150433945-e4932ac9-5d31-4c41-84c7-48c3a7938a0a.png">

Also ensured that none of the crypto widgets were visible on a new profile but were available via the following:

`Customize dashboard -> Cards`

`Upgrade Case`

Upgraded from `1.34.80` -> 1.34.81`
* added all crypto widgets  in `1.34.80, upgraded, and ensured they were present and in the same order, in `1.34.81`
* hid widgets and confirmed they were not re-enabled by default when upgrading, but were available also via `Customize dashboard -> Cards`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build:

```
Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Windows 11 Version 21H2 (Build 22000.434)
```

**`Clean Install Cases`**

Verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/20501#issue-1102759124 and ensured that there wasn't any outbound network connections when opening the NTP on a new profile. Also ensured that there was no third party outbound connections that are not being proxies when launching Brave for the first time. Example:

**`First Launch`** | **`Opening NTP`**
-------------------|---------------------
![startupCalls](https://user-images.githubusercontent.com/2602313/150433860-99b248e6-d3da-405a-b24a-5c390ad5aba5.png) | ![ntp](https://user-images.githubusercontent.com/2602313/150433866-8e5eec51-12bc-4257-a8b4-250f86cc67db.png)

Also ensured that none of the crypto widgets were visible on a new profile but were available  via the following:
* `Customise dashboard` -> `Cards`

**`Upgrade Cases`**

For the following cases, upgrade from `1.34.80 Chromium: 97.0.4692.71` --> `1.34.81 Chromium: 97.0.4692.99`

* ensured that crypto widgets are being displayed in the widget stack if a user has already enabled them
  * checked using Binance, FTX & Gemini
 * ensured that users stay authenticated after upgrading when the widget is active/visible under the widget stack
 * ensured that users stay authenticated after upgrading when the authenticated widget isn't active/visible in the widget stack
 * ensured that the correct order/active widget is maintained after upgrading
 * ensured that crypto widgets are not being removed from the widget stack and into `Customise dashboard` -> `Cards` when they've been enabled
