### ISSUE TITLE
CMD + (command-plus) does not zoom on MacOS with German keyboard

### ISSUE THREAD

**Issue by what-name** [brave/brave-browser#20509]
## Description 
CMD + (command-plus) does not zoom on MacOS with German keyboard. CMD - (command-minus) does work for zooming out. CMD 0 (command-zero) works for default resize. Issue present since a couple of versions, sorry I'm not sure since when.

## Steps to Reproduce
   1. Open Brave on MacOS with German keyboard.
   2. Go to any website.
   3. Hit `CMD +` (command-plus) on your keyboard

## Actual result:
Page does not zoom in.

## Expected result:
Page zooms in.

## Reproduces how often: 
At all times

## Brave version (brave://version info)
![Screenshot 2022-01-14 at 17 13 54](https://user-images.githubusercontent.com/20590073/149548172-9b6d6f5f-2777-4294-959e-9b94e2467a7c.png)

## Other Additional Information:
Present on all profiles. Checked in System preferences, there is nothing seemingly blocking the shortcut.
Possibly related https://github.com/electron/electron/issues/1507
It's now at `CMD SHIFT =`, but only since a couple weeks.

**Comment by maarsson** [comment]
Same issue on Swedish keyboard layout. Zoom in has a keyboard shortcut `CMD =` for some days. I even tried to disable all of my extensions, seems like it is not connected to any extension.

**Comment by what-name** [comment]
With the latest version, neither `CMD SHIFT 0` nor `CMD +` work.

**Comment by maarsson** [comment]
Just noticed that the new (currently) working shortcut is `CMD  backtick` (also `CMD SHIFT ´`) at least on Swedish keyboard.
The constant changing of the shortcuts is more annoying than the original problem.

**Comment by what-name** [comment]
Your comment made me try around. Turns out it moved to `CMD SHIFT +` on German keyboard. Agree with the point about the constant changing, frustrating.

**Comment by ddprrt** [comment]
This is also in contrast to the official docs: https://support.brave.com/hc/en-us/articles/360032272171-What-keyboard-shortcuts-can-I-use-in-Brave-
Is it possible to user-define this? Basically every app I use relies on `CMD +`. for zoom. I like to have this consistent.

**Comment by what-name** [comment]
German keyboard moved back to `CMD +`. Parkour.
