### ISSUE TITLE
Import relevant settings from Brave Payments

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#2050]
When a user is being upgraded from Muon/Brave Payments to Brave Core/Brave Rewards, the following settings should be carried over:

- [x] Minimum page time before logging a visit
- [x] Minimum visits for publisher relevancy
- [x] Allow contributions to non-verified sites
- [x] Allow contributions to videos

In the event of automatic/silent upgrade, all of these items should be automatically imported. 

In the event of a manual import, following a manual download/install of Brave Core, these items should be imported whenever a user decides to import "Brave Payments data" (an option on the list that includes bookmarks, cookies, passwords, etc). 

This is **in addition** to the import of the following items, covered elsewhere:

- [x] Wallet (this includes Grants; attached to wallet by way of server query)
- [x] Pinned sites*
- [x] Monthly Budget*
- [x] Excluded sites

*pinned sites and monthly budget import are _tied together_. See https://github.com/brave/brave-browser/issues/1910, specifically @jenn-rhim 's comment , for details.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/736

**Comment by btlechowski** [comment]
Verification Passed on

Brave | 0.57.17 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

Used STR from https://github.com/brave/brave-core/pull/736
Also imported using `--upgrade-from-muon` flag

Verified import is canceled when Brave Payments in b-l are turned off
Verified that following settings were imported:
- Minimum page time before logging a visit
- Minimum visits for publisher relevancy
- Allow contributions to non-verified sites
- Allow contributions to videos
- Wallet (this includes Grants; attached to wallet by way of server query)
- Monthly Budget
- Pinned sites (Tips) 
- Turning auto-contribute on/off based on ledger table and pinned sites
