### ISSUE TITLE
Rewards panel keeps spinning on failure when getting the external wallet.

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#20529]
## Description 
When [getting the external wallet](https://github.com/brave/brave-core/blob/0811c2333aa5ab9c4db6451e3421bb437e7885cf/vendor/bat-native-ledger/src/bat/ledger/internal/ledger_impl.cc#L747-L751), every return value other than `type::Result::LEDGER_OK` and `type::Result::CONTINUE` results in passing back `nullptr` as the external wallet, which causes the `Rewards` panel to spin. Clicking outside the panel then clicking on the BAT icon again resolves the issue (since the next time wallet generation runs it returns `type::Result::LEDGER_OK`) – see in the test plan of https://github.com/brave/brave-core/pull/11857.

Maybe we should consider returning the external wallet even in case of failure, since returning something other than `type::Result::LEDGER_OK` and `type::Result::CONTINUE` doesn't necessarily mean that we don't have a valid external wallet object.

**Comment by LaurenWags** [comment]
On Android it seems as though I don't get the spinner, but it acts like no external wallet is connected.

STR:

Pre-req: Use Charles Proxy to simulate CDD required or ask for your Uphold sandbox account to be put into this state.

1. Clean install 1.36.44 Nightly
2. Enable Rewards
3. Link KYC'd account which has CDD "required"
4. Confirm you are logged in without any problem (UI reflects this, your balance is displayed on settings and panel, etc)
5. Close brave://rewards page if open
6. Upgrade to 1.36.58 
7. Open the panel 
---> no spinner, but panel acts as though no wallet is connected, see "Verify wallet" on panel
8. Close/reopen panel
---> now see Disconnected/Logged out UI as expected.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```


Brave | 1.40.83 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
