### ISSUE TITLE
Consider removing implemented/unwanted flags

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20527]
The following flags are available on Brave and some of them needs to be remove as its already implemented for example ipfs/Wallet/news etc.

```

1. New Tab Page Demo Branded Wallpaper
2. #brave-ntp-branded-wallpaper-demo
3. #brave-adblock-cname-uncloaking
4. #brave-adblock-collapse-blocked-elements
5. #brave-adblock-cookie-list-default
6. #brave-adblock-cosmetic-filtering
7. #brave-adblock-csp-rules
8. #brave-adblock-default-1p-blocking
9. #brave-dark-mode-block
10. #brave-adblock-redirect-url
11. #brave-domain-block
12. #brave-domain-block-1pes
13. #brave-debounce
14. #brave-extension-network-blocking
15. #brave-cosmetic-filtering-sync-load
16. #brave-super-referral
17. #brave-ephemeral-storage
18. #brave-ephemeral-storage-keep-alive
19. #brave-first-party-ephemeral-storage
20. #brave-rewards-verbose-logging
21. #brave-ads-custom-push-notifications-ads
22. #brave-ads-allowed-to-fallback-to-custom-push-notification-ads
23. #brave-sync-v2
24. #brave-decentralized-dns
25. #brave-ipfs
26. #native-brave-wallet
27. #brave-wallet-filecoin
28. #brave-news
29. #brave-rewards-gemini
30. #brave-vpn
31. #brave-speedreader
32. #brave-shields-v2
33. #brave-translate-go

```

cc: @brave/brave-core @rebron

**Comment by bridiver** [comment]
Just because they have already been implemented does not necessarily mean we want to remove the flag. In some cases we want to provide the ability for users to toggle them on/off and in some cases we still want to retain the ability to toggle them off remotely if there is a problem. A recent example was an issue with a feature that has been deployed for many months that we had to temporarily disable on android to avoid a crash.

**Comment by kjozwiak** [comment]
> Just because they have already been implemented does not necessarily mean we want to remove the flag. In some cases we want to provide the ability for users to toggle them on/off and in some cases we still want to retain the ability to toggle them off remotely if there is a problem. A recent example was an issue with a feature that has been deployed for many months that we had to temporarily disable on android to avoid a crash.

Just for some context, this is referring to https://github.com/brave/brave-variations/pull/205.

**Comment by rebron** [comment]
Closing/wontfix. We'll follow-up on the individual flags on how we want to handle preserving or removing.
