### ISSUE TITLE
Bookmarks bar showing in private window on new tab page

### ISSUE THREAD

**Issue by rayzhudev** [brave/brave-browser#20537]
## Description 
In a private window on a new tab, bookmarks will still show when they are turned off.

## Steps to Reproduce

   1. Turn off show bookmarks
   2. Open private window
   3. Open new tab

## Actual result:
Bookmarks bar still shows in new tab on in private

## Expected result:
Bookmarks bar does not show anywhere when option is disabled.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave	1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
Revision	adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS	Windows 10 Version 20H2 (Build 19042.1466)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Is on the current release
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by GeetaSarvadnya** [comment]
@rayzhudev This behavior is the same for a long time. There is no change in the feature

**Comment by Vidhu007** [comment]
Yes even on my MAC my private bookmarks are visible in the private window which should not be the case

**Comment by rebron** [comment]
@rayzhudev Do you have `Always show bookmarks on new tab page` toggled off?

**Comment by rayzhudev** [comment]
@rebron yes that was it thank you, I had the setting on. That setting is hidden away. 
But that means that bug is in normal browser windows, not private ones.
While the `Always show bookmarks on new tab page` is on, and `Show bookmarks` is off, the new tab page doesn't show it.
It should be showing bookmarks but it isn't.
I'm guessing it's because I'm using a new tab page extension `Infinity New Tab Pro`

**Comment by rebron** [comment]
@rayzhudev I'm going to go ahead and close this one then. Sounds like it's the extension. Go ahead and reopen if that's not the case.
