### ISSUE TITLE
Fix Formatting to not show Metric Values in Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20535]
## Description 
Large numbers are being displayed in Metric Values, we need to add better formatting for bigNumbers.

https://community.brave.com/t/digits-in-wallet-are-cryptic-numbers/327272

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11982>brave/brave-core#11982</a></li>
         <li>Verified BTC value is not shown as an exponential value</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/154918851-0d28bd94-0896-44a4-b307-82471eeb8c12.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/154918198-5b19cf36-4594-46cf-9271-5b5164bf3a69.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/154918100-074fd2ea-e23a-44d8-9712-b41f37dce625.png>
      </td>
   </tr>
</table>
