### ISSUE TITLE
Third party tracker obfuscation

### ISSUE THREAD

**Issue by kaytwo** [brave/brave-browser#20533]
## Description 

Cloudflare acquired [Zaraz](https://blog.cloudflare.com/why-cloudflare-bought-zaraz/), which purports to increase privacy and performance for third party tracking, and have integrated it into their main whole-site CDN product. A significant side effect of their architecture is that these third party (largely tracking-related) requests appear to the browser to be first party requests to `https://YOURDOMAIN/cdn-cgi/zaraz/**`. In Brave Nightly on Windows, these requests are not blocked by aggressive shields in incognito mode (or any weaker setting).

## Steps to Reproduce

   1. Activate Zaraz on a Cloudflare-proxied website
   2. Load the site in Brave 
   3. Observe in the Network tab that tracking via Facebook Pixel, Google Analytics, etc. is successfully sent.

## Actual result:

Status: 200

## Expected result:

Status: Blocked

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:

Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 11 Version 21H2 (Build 22000.434)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Did not attempt
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the nightly channel? 
Yes

**Comment by diracdeltas** [comment]
cc @ryanbr , should be easy to add a filter for this

**Comment by ryanbr** [comment]
Example website of this in action @kaytwo ?

**Comment by kaytwo** [comment]
I enabled it on kaytwo.org for testing purposes. (for posterity: I will
probably turn it off after we resolve this).

**Comment by ryanbr** [comment]
`kaytwo.org` unable to find domain from NZ/US/UK ips. Standard Cloudflare error message @kaytwo

**Comment by kaytwo** [comment]
My bad, url bar slurping up www strikes again -
https://www.kaytwo.org/ is the correct one.
