### ISSUE TITLE
Undefined identifier in string expansion - sources += [ "$root_out_dir/$v8_context_snapshot_filename" ]

### ISSUE THREAD

**Issue by philippemnoel** [brave/brave-browser#20534]
## Description 
I am trying to run the Component build of Brave on macOS Monterrey 12.1, on an M1 MacBook pro 2021. I have latest Xcode installed (SDK 12.1), ran `xcode-select --install` and I am using Node 16.13 via `nvm` and npm 8.1.2.

I run `npm install` and `npm run init` and everything goes well. When I run `npm run build`, it almost immediately fails with the following error:
```
ERROR at //content/shell/BUILD.gn:584:38: Undefined identifier in string expansion.
        sources += [ "$root_out_dir/$v8_context_snapshot_filename" ]
                                     ^---------------------------
"v8_context_snapshot_filename" is not currently in scope.
See //BUILD.gn:194:7: which caused the file to be included.
      "//content/shell:content_shell",
      ^------------------------------
```

## Steps to Reproduce
Simply follow the standard build steps (`npm install`, `npm run init` and `npm run build`) from a machine with the following dependencies:
- macOS 12.1 Monterrey, M1 MacBook Pro
- node 16.13 and npm 8.1.2 via `nvm` 
- Xcode macOS 12.1 SDK

## Actual result:

<img width="1384" alt="Capture d’écran, le 2022-01-17 à 14 08 13" src="https://user-images.githubusercontent.com/21990816/149825469-482facab-8b11-40c9-b328-824dc0fe550c.png">

## Expected result:

A working Brave build

## Reproduces how often: 
All the times for me, it never gets past this step

**Comment by kjozwiak** [comment]
CCing @bsclifton as he might be able to point you in the right direction.

**Comment by philippemnoel** [comment]
> CCing @bsclifton as he might be able to point you in the right direction.

Thanks! Still no luck :|

**Comment by philippemnoel** [comment]
I fixed it

**Comment by djsavvy** [comment]
For posterity, the solution was not specifying a target architecture when building it.

**Comment by kdenhartog** [comment]
for clarity to build on @djsavvy comments you'll need to run the following commands to get the build working:

1. `npm install`
2. `npm config set target_arch arm64` 

note: target_os only needs to be set if you're working on a mobile build. Otherwise your os will be picked up via the Node.js `process.platform()` API in the build scripts

3. `npm run init`
4. `npm run build` // this will take awhile it has to compile the entire repo basically
5. `npm start Component`
