### ISSUE TITLE
Wallet backup sends user to Verify recovery phrase page the first time after reset

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#20532]
## Description 
The first time Backup fragment is displayed after a reset, it will go directly to Verify recovery phrase page. From the second time it will display the correct page.

## Steps to reproduce 

   1. Create a new wallet then reset.
   2. Create a new wallet again, skip backup during onboarding.
   3. Tap the backup banner, the Verify recovery phrase page is shown.

## Version/Channel Information:
1.36.41 Nightly

## Device details
Android 7.1.1, ARM64

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.85 x64 beta build
- Verified steps from issue description
- Verified tapping on the backup banner doesn't show verify seed but rather shows the backup seed message
----------
Verification passed on Samsung Tab A with Android 10 running 1.36.85 x64 beta build
- Verified steps from issue description
- Verified tapping on the backup banner doesn't show verify seed but rather shows the backup seed message
