### ISSUE TITLE
"Next payment date" for ads is incorrect

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20545]
## Description 

Possibly related to https://github.com/brave/brave-browser/issues/20204

Once the griffin seed is applied, the ads payment date should be 7th of the month. This is working correctly on 1.34.x.

This is not working correctly on 1.35.x, 1.36.x in certain timezones (like UTC-5). However, it is working for some timezones (UTC+5, UTC+1).

## Steps to Reproduce

pre-req: Be in UTC-5 timezone (New York, New York US for example)
   1. Install 1.34.x (Release channel)
   2. Enable Rewards, see 5th as the date for ads payment
   3. Restart to apply griffin seed
   4. Ads date updates to 7th as expected
   5. Install 1.35.x or 1.36.x (Beta/Nightly)
   6. Enable Rewards, see 4th as the date for ads payment
   7. Restart to apply griffin seed
   8. Ads date shows the 6th, should be the 7th

## Actual result:

1.36.x:
<img width="727" alt="Screen Shot 2022-01-18 at 10 56 17 AM" src="https://user-images.githubusercontent.com/28145373/149980862-9bf1a13d-c622-4d6b-916c-e828494ec17a.png">

## Expected result:
1.34.x:
<img width="723" alt="Screen Shot 2022-01-18 at 10 55 53 AM" src="https://user-images.githubusercontent.com/28145373/149980945-47746d60-3a7a-4aef-982d-91b88f83a8c2.png">

per griffin, should be 7th (thx for screenshot @btlechowski )
![image](https://user-images.githubusercontent.com/28145373/149981113-fd091f5f-5b79-47fe-a8be-d44ef86b11f5.png)

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.35.x, 1.36.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.34.x no
- Can you reproduce this issue with the beta channel? 1.35.x yes
- Can you reproduce this issue with the nightly channel? 1.36.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

reproduced by @Miyayes 

cc @tmancey @aseren @brave/legacy_qa

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.70 Chromium: 98.0.4758.66 (Official Build) nightly (64-bit)
-- | --
Revision | db1b4001d5ce29f141297f260d2b778e000b85a3-refs/branch-heads/4758@{#762}
OS | Windows 10 Version 20H2 (Build 19042.1466)

Case 1: `1.34.81`
1. installed `1.34.81`
2. enabled Rewards
3. on `brave://rewards` saw the 5th as the ads-payment date
4. restarted to apply the Griffin seed

example | example | example
----------|----------|----------
![20545-1](https://user-images.githubusercontent.com/387249/151238663-73ab545e-1f10-4cc7-89a7-bf00a3869a34.png) | ![20545-2](https://user-images.githubusercontent.com/387249/151238664-b9bd9ec0-d9a0-4bef-8d91-c396b1db8744.png) | ![20545-3](https://user-images.githubusercontent.com/387249/151238661-00176431-8c29-4fa2-8226-e7ff532bf0ba.png)


Confirmed ad-payment date updated to the 7th

Case 2: `1.36.70`
1. installed `1.36.70`
2. enabled Rewards
3. on `brave://rewards` saw the 5th as the ads-payment date
4. restarted to apply the Griffin seed
5. loaded `brave://rewards`

Confirmed ad-payment date updated to the 7th

example | example | example
----------|-----------|----------
![20545-4](https://user-images.githubusercontent.com/387249/151238560-649100eb-bd74-471b-96d0-3932efe3e2c1.png) | ![20545-5](https://user-images.githubusercontent.com/387249/151238567-a0eb56bc-b57d-4ef2-8ffc-b0183c13b3ec.png) | ![20545-6](https://user-images.githubusercontent.com/387249/151238569-47edb8bb-988c-40f7-bcfc-c9c61c5c61bd.png)

**Comment by stephendonner** [comment]
Verified using 

Brave | 1.35.93 Chromium: 97.0.4692.99 (Official Build) beta (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Windows 10 Version 20H2 (Build 19042.1466)


<summary>Scenario 1 - UTC-5 (New York, New York) - production env.</summary>
<details>

Confirmed "Next payment date" for ads showed 5th prior to griffin seed being applied.
Restarted browser.
Confirmed "Next payment date" for ads showed 7th after griffin seed applied.


Before | After
-------|------
![20545-1](https://user-images.githubusercontent.com/387249/151257095-236f1b12-cdba-4a35-9929-3ec19acb8f2a.png) | ![20545-2](https://user-images.githubusercontent.com/387249/151257098-e86b50d6-4f80-40a7-aad4-59b80f124547.png)

</details>

<summary>Scenario 2 - UTC-5 (New York, New York) - staging env.</summary>
<details>

Confirmed "Next payment date" for ads showed 5th prior to griffin seed being applied.
Restarted browser.
Confirmed "Next payment date" for ads showed 7th after griffin seed applied.


Before | After
-------|------
![20545-3](https://user-images.githubusercontent.com/387249/151257168-7625cfa7-4a62-4b6a-ba66-2651f46c5510.png) | ![20545-4](https://user-images.githubusercontent.com/387249/151257173-db4941d9-dad2-44dd-b08e-68cdd367d61a.png)

</details>

<summary>Scenario 3 - UTC+1 (Warsaw, Poland) - production env.</summary>
<details>

Confirmed "Next payment date" for ads showed 6th prior to griffin seed being applied.
Restarted browser.
Confirmed "Next payment date" for ads showed 8th after griffin seed applied.

Before | After
-------|------
![20545-5](https://user-images.githubusercontent.com/387249/151257204-bccd9429-3775-4d12-abec-9f8f67c1be4c.png) | ![20545-6](https://user-images.githubusercontent.com/387249/151257207-9ceb9439-ced6-477d-8da0-af94479abe87.png)


</details>

<summary>Scenario 4 - UTC+5:30 (Hyderabad, India) - production env.</summary>
<details>

Confirmed "Next payment date" for ads showed 6th prior to griffin seed being applied.
Restarted browser.
Confirmed "Next payment date" for ads showed 8th after griffin seed applied.


Before | After
-------|------
![20545-7](https://user-images.githubusercontent.com/387249/151258579-9f687ab3-fa18-4c41-a1da-266db7a9af60.png) |![20545-8](https://user-images.githubusercontent.com/387249/151258581-3bd1b9df-85f7-497c-ad7c-65cfc0ea2e2e.png)


</details>

<summary>Scenario 5 - UTC+0 (London, England) - production env.</summary>
<details>

Confirmed "Next payment date" for ads showed 5th prior to griffin seed being applied.
Restarted browser.
Confirmed "Next payment date" for ads showed 7th after griffin seed applied.

Before | After
-------|------
![20545-9](https://user-images.githubusercontent.com/387249/151257919-fa17a12e-c3dd-4bfc-944e-94129f623f8b.png) | ![20545-10](https://user-images.githubusercontent.com/387249/151257920-175ae5c9-e28b-4e5e-b8af-83833aad7fdc.png)
