### ISSUE TITLE
Ad notification count increased to one without viewing Ads/Custom ads/NTPSI in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#20543]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/16028
Ad notification count increased to one without viewing Ads/Custom ads/NTPSI in an upgraded profile

## Steps to Reproduce

   1. Clean profile 1.34.80 - RC build
   2. Open an NTP and enable rewards via NTP
   3. Open brave://settings page and confirm ads switch is ON 
   4. Confirm ads notification count and estimated rewards is Zero 
   5. Rename the profile to beta (1.35.x) and launch brave
   6. Reload the brave://rewards page
   7. Ads notification count increased to one 

**Note:** When I upgrade 1.33.x by 1.34.x this issue is not reproduced. The issue appears only with 1.35.x upgrade

## Actual result:

Ad notification count increased to one without viewing Ads/Custom ads/NTPSI in an upgraded profile

## Expected result:

Ads notification count should be zero after the upgrade
## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.35.87 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 21H2 (Build 19044.1466)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jsecretan @tmancey @brave/legacy_qa @btlechowski 

Logs attached
[Logs for upgrade from 1.34. to 1.35.txt](https://github.com/brave/brave-browser/files/7887681/Logs.for.upgrade.from.1.34.to.1.35.txt)

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 

Brave | 1.35.85 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/149929219-40fc1dc5-6f6a-424f-a402-fb5c03d87405.png)

**Comment by kjozwiak** [comment]
Removing `release/blocking` as per @tmancey @jsecretan. This doesn't need to be uplifted and can ride the trains.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Ubuntu 18.04 LT

#### upgrade path: 1.34.x->1.36.x - PASS

1.34.81
![image](https://user-images.githubusercontent.com/34715963/153516843-bfa89492-3075-44ca-9ee7-5b476d370511.png)

upgraded to 1.36.x from 1.34.x
![image](https://user-images.githubusercontent.com/34715963/153516930-89a1bd2f-28a1-44c5-814e-dcb1430ae584.png)

#### upgrade path: 1.34.x->1.35.x ->1.36.x - FAIL

upgraded to 1.35.x from 1.34.x
![image](https://user-images.githubusercontent.com/34715963/153517508-c7a1e748-4c33-4eb2-b3dd-b0d61e320706.png)

upgraded to 1.36.x from 1.35.x  - FAIL - the state was not fixed when upgrading from 1.35.x
![image](https://user-images.githubusercontent.com/34715963/153517640-01445d94-677e-41e4-a61c-cc3e2504b010.png)

Logged https://github.com/brave/brave-browser/issues/21031

#### upgrade path: 1.35.x->1.36.x - PASS
1.35.x
![image](https://user-images.githubusercontent.com/34715963/153518233-6c20d34c-a6ea-4b07-9ac3-8ced90948b47.png)

upgraded to 1.36.x from 1.35.x
![image](https://user-images.githubusercontent.com/34715963/153518290-34809fd7-e879-4a7c-b5b9-eb84f22ae05e.png)
