### ISSUE TITLE
Tab groups news related crash

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20540]
## Steps to reproduce 

   1. Settings => Appearance => Enable Tab Groups off => restart
   2. Add new tab
   3.  

## Actual result 
App crashes

## Expected result

No crash
## Issue reproduces how often 

Easily reproduced
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@alexsafe was this related to Brave News? Or does this affect other channels? If so, seems like something we should uplift and get into a HF. If related to Brave News, it can stay in `1.36.x`.

**Comment by alexsafe** [comment]
@kjozwiak it's in the news flag controlled area of the code so I think it should be ok if it stays

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.36.66, Chromium 98.0.4758.66` on ` Google Pixel XL` (`arm64`) using `Android 9.0`.

### Steps:
1. installed `1.36.66`
2. launched Brave
3. tapped through onboarding
4. tapped the 3-dots menu
5. tapped `Settings`
6. tapped `Appearance`
7. tapped to set `Enable Tab Groups` to `Off`
8. tapped `RELAUNCH NOW`
9. tapped to open new tabs repeatedly

**Confirmed I didn't crash.**

NOTE: while testing this, I discovered and filed https://github.com/brave/brave-browser/issues/20689 for the `Brave News`-enabled case.


https://user-images.githubusercontent.com/387249/151066947-ed6e66db-bc33-4d43-bba8-47261fe37cf1.mp4
