### ISSUE TITLE
vBAT failing to be submitted for userdrain

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20554]
## Description

Some users have stubborn vBAT that is not being userdrained. That is, the vBAT persists inside the browser, and is not being successfully submitted to the userdrain endpoint. The user continues to see this vBAT balance as part of their Rewards balance, even though they are verified. 

Investigation: https://github.com/brave/internal/issues/859

_________

+1 from /u/AllenDoStuff

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/13974
-

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (x86_64)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 12.5 (Build 21G72)
```
