### ISSUE TITLE
[Android] Add bitFlyer verification promo card on brave://rewards settings page (Q1 2022)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20569]
## Description

Refer to @Miyayes and @minkyeongshin for designs. 

**Note:** This is for Japan region only.

Learn more should link out to:  https://support.brave.com/hc/en-us/articles/4403459972365-%E5%BA%83%E5%91%8A%E9%96%B2%E8%A6%A7%E5%A0%B1%E9%85%AC%E3%81%A7%E7%8D%B2%E5%BE%97%E3%81%97%E3%81%9FBAT%E3%81%AF%E5%BC%95%E3%81%8D%E5%87%BA%E3%81%99%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%81%8B

![image](https://user-images.githubusercontent.com/11497541/151584029-b8052dfd-4120-42f6-8d81-af4b2b779d87.png)

**Comment by Miyayes** [comment]
@emerick Added the link "Learn more" should go out to :). See above.

**Comment by emerick** [comment]
@Miyayes Thanks for the "Learn more" link, any word on an image yet? :-)

**Comment by kjozwiak** [comment]
Requires `1.37.87` or higher. However, we should wait till both https://github.com/brave/brave-browser/issues/21567 & https://github.com/brave/brave-browser/issues/21568 are resolved to run through the above.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as we decided not to fix https://github.com/brave/brave-browser/issues/21568 in `1.37.x`.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6`  using `Android 12` running `1.37.107 Chromium: 100.0.4896.46`

* ensured that the `bitFlyer` promo card only appears for the `Japan` locale.
  * checked both `Canada`, `Spain` & `Germany` and ensured that the promo card doesn't appear via `brave://rewards`
* ensured that the user can dismiss the card using `X`
  * ensure that the promo banner doesn't re-appear when re-visiting `brave://rewards` (even after browser restart)
* ensured that the user can dismiss the card using `Don't show again`
   * ensure that the promo banner doesn't re-appear when re-visiting `brave://rewards` (even after browser restart)
* ensured that the bitFlyer promo code doesn't closed when tapping on the button to open link (confirmed by @Miyayes)
* ensured that tapping on the button opens the following website in a new tab:

```https://support.brave.com/hc/en-us/articles/4403459972365-%E5%BA%83%E5%91%8A%E9%96%B2%E8%A6%A7%E5%A0%B1%E9%85%AC%E3%81%A7%E7%8D%B2%E5%BE%97%E3%81%97%E3%81%9FBAT%E3%81%AF%E5%BC%95%E3%81%8D%E5%87%BA%E3%81%99%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%81%8B```

* upgraded `1.36.22 Chromium: 99.0.4844.88` -> `1.37.107 Chromium: 100.0.4896.46` and ensured that the promo was appearing

**`Example (Canada)`** | **`Example (Spain)`** |  **`Example (Germany)`** | **`Example (Japan)`** | **`Example (Website)`**
---------------------------|--------------------------|------------------------|----------------------------|--------------------------
![Screenshot_20220328-142724](https://user-images.githubusercontent.com/2602313/160470386-1f350dae-a81e-4c54-9b97-f2e30793f842.png) | ![Screenshot_20220328-143029](https://user-images.githubusercontent.com/2602313/160470457-74958312-187d-442d-a09c-50e469bcecec.png) | ![Screenshot_20220328-151445](https://user-images.githubusercontent.com/2602313/160470507-b690e26b-de79-4a8e-8536-f97f9a7dae62.png) | ![Screenshot_20220328-143449](https://user-images.githubusercontent.com/2602313/160470537-622b2fcb-6665-4018-926e-695f22a193a0.png) | ![Screenshot_20220328-145110](https://user-images.githubusercontent.com/2602313/160470573-8572c279-b53a-4684-8360-cd0b94cae770.png)
