### ISSUE TITLE
Use `coingeckoId` to fetch prices whenever possible

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20562]
Following up on https://github.com/brave/brave-browser/issues/20344, use the `coingeckoId` field in `BlockchainToken` type to fetch prices whenever defined. This is a more accurate way to fetch prices from Coingecko, compared to via symbol or contract address.

👉  **QA steps:** Please refer to the test plan in the linked PR.

Also related to https://github.com/brave/brave-browser/issues/19740.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11900>brave/brave-core#11900</a></li>
         <li>Verified asset balance is shown correctly</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/21214>#21214</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/154932736-bcc34006-ff1a-41e9-a876-b6413ef13898.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/154932660-e940349b-3efa-4074-9835-26c93c5cc7a2.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/154932415-a065e0bd-d93e-4dc8-91dc-928f82fce98b.png>
      </td>
   </tr>
</table>
