### ISSUE TITLE
Investigate enabling PGO with Chromium profiles for Android 

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#20560]
By default PGO is disabled for Android:
https://github.com/chromium/chromium/blob/main/build/config/compiler/pgo/pgo.gni#L20

In fact Chrome has a little bit more on speedometer2, mostly because of PGO.
We should build PGO enabled Android build and compare the performance.

**Comment by atuchin-m** [comment]
Right now chromium doesn't have PGO builds. It doesn't support [downloading profiles](https://source.chromium.org/chromium/chromium/src/+/main:tools/update_pgo_profiles.py;l=135) and PGO is [disabled by default](https://source.chromium.org/chromium/chromium/src/+/main:build/config/compiler/pgo/pgo.gni;l=18-19;bpv=1) for Release build.

On the other hand Chrome has builders with chrome_pgo_phase=1: [link 1](https://source.chromium.org/chromium/chromium/src/+/main:tools/mb/mb_config.pyl;l=2915?q=official_goma_android_arm64_pgo&ss=chromium%2Fchromium%2Fsrc) [link 2](https://bugs.chromium.org/p/chromium/issues/detail?id=1234908#c3)
There is also a few closed tickets: [1](https://bugs.chromium.org/p/chromium/issues/detail?id=1223583), [2](https://bugs.chromium.org/p/chromium/issues/detail?id=1227766) .
Also there is [a code](https://chromium-review.googlesource.com/c/chromium/tools/build/+/3193803) to support working with PGO profiles in `chromium/tools/build`.

It seems that Chrome uses PGO (or has plans to enable it soon) but decided not to make it public.
Therefore using PGO for Chrome require to build own PGO profiles.

**Comment by atuchin-m** [comment]
By default android PGO is enabled only for `is_high_end_android` build. Currently, we don't have one.
As we don't set `chrome_pgo_phase=2` explicitly PGO seems to be disabled for release android builds.

**Comment by zamazan4ik** [comment]
@atuchin-m Could you please clarify, for which platforms right now Brave is optimized with PGO? Am I right is the only Brave version without PGO right now is the build for Android?

**Comment by atuchin-m** [comment]
@zamazan4ik PGO is used only for desktop platforms (win, linux, mac).
Android uses another profile guided optimization technique called AFDO.

The same for the upstream (Chromium/Chrome). They has [an experiment](https://source.chromium.org/chromium/chromium/src/+/main:build/config/chrome_build.gni;l=23-25?q=is_high_end_android) to make PGO-enabled builds for high-end devices.
We don't have a plan to enable that thing before the upstream, because it can create a performance degradation for some configuration.
