### ISSUE TITLE
Change `Monthly Contributions` to be `Monthly Tips` 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20564]
## Description

- [ ] Rename "Monthly Contributions" to "Monthly Tips"
- [ ] Reorder the Monthly Tips component in brave://rewards settings page to be last position (3rd), and move Tips section up into 2nd position
- [ ] Fix description text in Monthly Tips component to be "Set up recurring monthly tips so you can continually support your favorite creators". 
- [ ] Change line item text to be "Total monthly tips this month"
- [ ] Change line item text to be "Next monthly tip date"
- [ ] Change any relevant "Monthly contributions" language in Tipping banner 
- [ ] Change any relevant "Monthly contributions" language in the Wallet Activity section

![image](https://user-images.githubusercontent.com/11497541/150174516-8bfd32c3-2e3a-43b0-9ff6-f125d9087676.png)

**Comment by zenparsing** [comment]
We should also check the tipping banner for any text changes that need to be made.

**Comment by Uni-verse** [comment]
Verified using `1.38.103, Chromium 100.0.4896.127` on `Samsung GS21` & `Samsung Galaxy Tab S7` running `Android 12`

Acceptance Criteria

`PASS` - Rename "Monthly Contributions" to "Monthly Tips"
`PASS` - Reorder the Monthly Tips component in brave://rewards settings page to be last position (3rd), and move Tips section up into 2nd position
`PASS` - Fix description text in Monthly Tips component to be "Set up recurring monthly tips so you can continually support your favorite creators".
`PASS` - Change line item text to be "Total monthly tips this month"
`PASS` - Change line item text to be "Next monthly tip date"
`PASS`- Change any relevant "Monthly contributions" language in Tipping banner
`PASS` - Change any relevant "Monthly contributions" language in the Wallet Activity section

1 | 2 | 3 | 4
-|-|-|-
![Screen Shot 2022-04-20 at 2 38 48 PM](https://user-images.githubusercontent.com/17885425/164328178-d373cf61-4d1b-429f-ba6c-b0ebe38bd60d.png) | ![Screen Shot 2022-04-20 at 2 44 04 PM](https://user-images.githubusercontent.com/17885425/164328182-b4001eb9-8ca6-498e-9efb-4005fc7252ef.png) | ![Screen Shot 2022-04-20 at 2 44 15 PM](https://user-images.githubusercontent.com/17885425/164328187-74d5978b-0f17-4f64-a6a0-86443c88af27.png) | ![Screen Shot 2022-04-20 at 2 45 01 PM](https://user-images.githubusercontent.com/17885425/164328191-e34ce096-7854-46d2-9a31-ffbfaf9438d8.png)

1 | 2 | 3
-|-|-
![Screen Shot 2022-04-20 at 2 47 59 PM](https://user-images.githubusercontent.com/17885425/164329235-9f0f3244-5cca-4e9a-9831-03b55de3de1c.png) | ![Screen Shot 2022-04-20 at 2 48 13 PM](https://user-images.githubusercontent.com/17885425/164329245-ea41684f-4870-4d77-9fd2-775825e3337f.png) | ![Screen Shot 2022-04-20 at 2 48 47 PM](https://user-images.githubusercontent.com/17885425/164329249-61419d85-d1af-4f14-be4c-5d4a1756ec6f.png)
