### ISSUE TITLE
Clipped content when returning back to Brave News from article

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20575]
## Description 

Clipped content when returning back to Brave News from article

## Steps to reproduce 

   1. install `Brave 1.36.47`
   2. launch Brave
   3. restart Brave (to pick up Brave News seed from Griffin)
   4. tap through onboarding
   5. swipe down
   6. tap to `Show Brave News`
   7. tap various articles and then use the `<` button to return to Brave News
   8. rinse, lather, repeat (until you see the issue)

## Actual result 

Content is clipped

![Screenshot_20220119-154800](https://user-images.githubusercontent.com/387249/150237431-e8b5a5bc-8e29-44fe-92d7-89cc6364c27c.png)

## Expected result

No clipped content

## Issue reproduces how often 

Hard (so far) to reproduce

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

`1.36.47, Chromium 97.0.4692.71`

cc @alexsafe @srirambv

**Comment by alexsafe** [comment]
should be fixed by this [PR](https://github.com/brave/brave-core/pull/11877)  . I'll add it to the rezolved issues

**Comment by stephendonner** [comment]
> should be fixed by this [PR](https://github.com/brave/brave-core/pull/11877) . I'll add it to the rezolved issues

FWIW, it looks like this happens when:
1) new-ish profile displays the `You just blocked trackers & ads!` orange doorhanger (so feels like a z-index region/painting issue) when you hit the URL
2) after navigating back, that doorhanger "hangs" on (pun intended) but after you tap through it, you see this bug, sometimes

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.36.63, Chromium 97.0.4692.99` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

Heavily tested back/"forward" navigation within and to/from Brave News.  Didn't observe any clipping, this time 👍
