### ISSUE TITLE
Consider Adding a Block Confirmation Count to Pending Transaction

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20573]
## Description 
Consider adding a `Block Confirmation` count status for `Pending Transactions` to give the user more feedback of how much time is left before a transaction is confirmed.

https://community.brave.com/t/speed-up-pending-transaction-in-new-brave-wallet/328703/4

**Comment by onyb** [comment]
We also need to have a field in `EthereumChain` called `confirmationsNeeded` based on this list: https://support.kraken.com/hc/en-us/articles/203325283-Cryptocurrency-deposit-processing-times.

**Comment by josheleonard** [comment]
@onyb, do we need to create a separate issue for getting `confirmationsNeeded` added to `EthereumChain`

**Comment by onyb** [comment]
Created relevant backend issues - https://github.com/brave/brave-browser/issues/22168 and https://github.com/brave/brave-browser/issues/22169.
