### ISSUE TITLE
Add skipValidation flag to request quota on swap

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#20572]
0x team is pushing a fix that is going to break our current swap from ERC20 token if not enough allowance.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11903>brave/brave-core#11903</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Activate Token
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150461476-32485c4b-706b-418f-a230-450db4e61f2f.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/150460710-5835f3cb-4cdc-44f1-95ee-8bf9f584262c.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/150458609-166f1dcc-f585-47b3-9e72-6c5f914fe6e7.png>
      </td>
   </tr>
   <tr>
      <td>Confirm Activation
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150461497-f2422d28-d535-45e1-8d4d-65db83f05bf2.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/150460741-7f27586e-2dfa-441d-9bfd-6a5fc5fe0960.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/150458656-27ab652a-3b5b-4b4a-b1b4-9aaed1005422.png>
      </td>
   </tr>
   <tr>
      <td>Swap Enabled
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/150461515-00135f82-8df7-4c1e-a043-879d6115d012.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/150460791-51e08152-7ac9-464f-bc2c-76d02ffa1b07.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/150458753-b575d708-6d81-4664-92fd-36fef96c695a.png>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.34.81 x64 build
- Verified steps from [brave/brave-core#11903](https://github.com/brave/brave-core/pull/11903)

Activate Token | Confirm Activation  | Swap Enabled  
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/150512436-feff2bfb-dcf6-4bc6-83aa-4c5ac5fecacc.png) | ![image](https://user-images.githubusercontent.com/17010094/150512456-c29c7e06-af0e-47e5-8f51-b476db094066.png) | ![image](https://user-images.githubusercontent.com/17010094/150512474-68376d99-cf80-4f5a-aa84-ed8787d6dbbf.png)

--------
Verification passed on Samsung Tab A with Android 10 running 1.34.81 x64 build
- Verified steps from [brave/brave-core#11903](https://github.com/brave/brave-core/pull/11903)

Activate Token | Confirm Activation  | Swap Enabled  
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/150514092-c7addb17-9c07-48b9-8046-932988d7e3d5.png) | ![image](https://user-images.githubusercontent.com/17010094/150514100-6fb2a51a-9d20-428b-bd6a-8be2900bf452.png) | ![image](https://user-images.githubusercontent.com/17010094/150514124-ba3383fe-baf0-45e2-bd35-b966c19eda7e.png)
