### ISSUE TITLE
[Brave-iOS] - Sync-Internals not loading

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#20577]
Sync Internals scheme is incorrect and is formatted as: `chrome/sync-internals` when it should be `chrome://sync-internals`.
This causes Sync-Internals not to load on brave-ios.

**Comment by stephendonner** [comment]
## Verified `PASSED` using Brave `1.36 (22.2.22.17)` on an `iPhone 6s` running iOS `14.4.2 (18D70)`

### Steps:
1. installed `1.36`
2. launched Brave
3. tapped on the 3-dots menu `...`
4. tapped on `Settings`
5. tapped on `Sync`
6. tapped on the `Settings` icon (gears)

Confirmed `Sync Internals` loaded and was functional/updated.



example | example | example | example
----------|---------|---------|----------
![Image from iOS (3)](https://user-images.githubusercontent.com/387249/155375120-e3e02c1c-358c-45c8-8725-4424a76b3006.png) | ![Image from iOS (2)](https://user-images.githubusercontent.com/387249/155374900-e6fc7c72-b6ae-4646-af6a-23943ed3e745.png) | ![Image from iOS](https://user-images.githubusercontent.com/387249/155375263-20a7644d-1dd9-4979-b160-13a6356f199e.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/155375299-234d3fc7-af66-43fb-95db-eb2edcf8dcec.png)
