### ISSUE TITLE
Scroll (swipe?) position in viewport not retained between tab switches

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20580]
## Description 

Scroll (swipe?) position in viewport not retained between tab switches

## Steps to reproduce 

   1. install `1.36.47, Chromium 97.0.4692.71`
   2. launch Brave
   3. tap through onboarding
   4. restart Brave (to pick up Griffin seed changes)
   5. open a new-tab page
   6. tap to `Show Brave News`
   7. swipe up until your article is near the top `Brave News` dynamic toolbar pane
   8. tap on the tabs-overview button  on the bottom Brave toolbar (in-between the 🔍 and the 3-dots menu item)
   5. now tab back on your Brave News article

## Actual  vs. Expected

actual | expected
-------|----------
![Screenshot_20220119-175209](https://user-images.githubusercontent.com/387249/150248253-5f4f0f97-00ce-4501-96a2-be596863db0c.png) | ![Screenshot_20220119-175217](https://user-images.githubusercontent.com/387249/150248258-2bb48b11-f86e-4231-acfa-2c709f5ad99d.png)

## Issue reproduces how often 

100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

`1.36.47, Chromium 97.0.4692.71`

cc @alexsafe @petemill @mattmcalister @srirambv

**Comment by srirambv** [comment]
Still an issue. Easier steps to repro
1. Enable News and opt-in
2. Open a new tab and reload the page
3. Automatically jumps to the middle of the feed. Doesn't stay on top with widgets in view

https://user-images.githubusercontent.com/17010094/151539273-1659c942-474a-4654-8b06-8ca88e5ac2f6.mp4

**Comment by kjozwiak** [comment]
Above requires `1.38.98` or higher for `1.38.x` verification.

**Comment by kjozwiak** [comment]
Created a follow up via https://github.com/brave/brave-browser/issues/22356 to improve Android keeping the correct position with the Brave News feed when switching tabs.

**Comment by Uni-verse** [comment]
Verification completed using `1.38.103, Chromium 100.0.4896.127`

Devices: 
Samsung Galaxy S21 running Android 12
Samsung Galaxy Tab S7 running Android 12

As mentioned in https://github.com/brave/brave-browser/issues/22356#issue-1205997563 there are mainly two cases observed where the position is not retained and will need improvements. In the case of scrolling through articles in feed, when using the tab tray and returning to the same tab, the position is shifted down slightly. Second case is when scrolling where the first card is at the top of the screen just below the news setting bar, using the tab tray and return to this tab will change the position of the view to the top of NTP.  This behavior is the same on Android Tablets. 

- Follow up issue https://github.com/brave/brave-browser/issues/22356

Behavior on 1.38.x for Test Case #1 Position of card in feed
 Original position | After using tab overview
 -|- 
![Screen Shot 2022-04-20 at 1 43 50 PM](https://user-images.githubusercontent.com/17885425/164322012-e4912fab-68a0-41dc-a49b-a79005a8dd74.png) | ![Screen Shot 2022-04-20 at 1 44 06 PM](https://user-images.githubusercontent.com/17885425/164322018-6a01b283-d478-4563-8fd9-adb6fb995e82.png)

Test Case #2 - First Card (1.38)
 Original position | After using tab overview
 -|- 
![Screen Shot 2022-04-20 at 1 44 36 PM](https://user-images.githubusercontent.com/17885425/164323403-f7b00710-b15c-4633-99ac-e0245228bbed.png) | ![Screen Shot 2022-04-20 at 1 44 58 PM](https://user-images.githubusercontent.com/17885425/164323411-86424fce-237e-4581-8b3d-b09ded840436.png)
