### ISSUE TITLE
Add CoingeckoID field to AddCustomAsset form

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20581]
## Description 
Add a `CoingeckoID` field to `AddCustomAsset` form.
Follow up to https://github.com/brave/brave-browser/issues/20562

 <img alt="" width="400px" src="https://user-images.githubusercontent.com/3684187/149329788-7d795d44-152e-4f5a-b27a-0ab61db214a5.png">

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11934>brave/brave-core#11934</a></li>
         <li>Verified adding CoingeckoID field to custom asset token as <code>bitcoin</code> starts to show the balance in BTC value</li>
         <li>Verified deleting the custom token resets the value back to default</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/154938434-fc67c39a-9b53-465d-a266-1a0ccca60915.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154937031-d3d2efd3-5bc2-4a92-a67f-f31098f3a474.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154936623-df8ba6fd-220b-4bf8-aa76-9428c5c09ebd.mov>
      </td>
   </tr>
</table>
