### ISSUE TITLE
Update Tor to Brave Search

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#20583]
## Description 

For New Private Window with Tor, default search engine should be Brave Search. 
https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/search?q=%s

Will also need to update the New Private Window with Tor new tab page to remove reference to DuckDuckGo.

## Steps to Reproduce

   1. Open New Private Window with Tor
   2. Enter search terms in the url bar. Should say `Search Brave or type a URL`
   3. Should go to Brave Search.

## Actual result:

Currently defaults to DuckDuckGo search.

<img width="1124" alt="Screen Shot 2022-01-18 at 12 07 28 PM" src="https://user-images.githubusercontent.com/5951041/150270390-a2d5d61e-f32d-4eb3-8144-9fbc1f896e97.png">

## Expected result:
See description.
https://www.figma.com/file/5THkuEtO2Ewn9LfqrHZP9a/Desktop-Private-and-TOR-Windows?node-id=942%3A19384

<img width="1317" alt="Screen Shot 2022-01-18 at 12 07 10 PM" src="https://user-images.githubusercontent.com/5951041/150270408-01e856fe-9ebe-47fa-b12e-240b48708c9c.png">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Target version for update 1.36.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by diracdeltas** [comment]
this was blocked on https://github.com/brave/internal/issues/781 - were all those items done?

**Comment by rebron** [comment]
Per @fmarier https://github.com/brave/search/issues/3425#issuecomment-1043657123 Let's get this merged down.

**Comment by bsclifton** [comment]
Reopening after revert via https://github.com/brave/brave-core/pull/12390

**Comment by kjozwiak** [comment]
@brave/legacy_qa some of the cases that I ran through via https://github.com/brave/brave-core/pull/12391#issuecomment-1066151499 can be used to verify the above as well. Requires `1.37.91` or higher for QA verification's via `1.37.x`.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.36.115 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.115 Chromium: 99.0.4844.51 (Official Build) (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.3 (Build 20G415)

Verification PASSED on


- Verified the STR mentioned in the description
- Confirmed open a TOR window displays the text as `Search Brave or type a URL` in the URL bar
- Confirmed search is performed by using the `Brave` SE
- Confirmed that CAPTCHA test is being done whenever searching via the Tor window

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
<img width="1312" alt="Screen Shot 2022-03-15 at 12 04 55 PM" src="https://user-images.githubusercontent.com/387249/158465543-587f7c96-cc61-4a86-b6e1-c758c213a3a9.png"> | <img width="1312" alt="Screen Shot 2022-03-15 at 12 05 24 PM" src="https://user-images.githubusercontent.com/387249/158465580-4367dbc2-ab77-41b6-b73e-500a7a933451.png"> | <img width="1312" alt="Screen Shot 2022-03-15 at 1 25 49 PM" src="https://user-images.githubusercontent.com/387249/158465915-90ed30a5-d40e-46b7-b5f3-301444634168.png">




- Verified the cases mentioned in the https://github.com/brave/brave-core/pull/12391#issuecomment-1066151499

#### **`Test Case #1`** - Clean Install

* ensured that Brave Search is the default SE for both Normal/Private windows
* ensured that Brave Search is the default SE for Tor Windows and ensured that the `.onion` address is being used
  * `https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/search?q`
* ensured that `https://search.brave.com/search?q=` is still being used under Normal & Private windows
* ensured that there's no mention of DDG anywhere under the Tor window nor any images associated with DDG
* ensured that the progress bar correctly indicates when Tor is being downloaded/connecting and connected successfully
* ensured that Brave Search is only listed once under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that the `:search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion` keyword is working as expected
* ensured that changing defaults via brave://settings/searchEngines doesn't affect the default Tor SE (should always be Brave)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|---------------|-----------------|----------------|-----------------
<img width="1312" alt="Screen Shot 2022-03-15 at 12 04 48 PM" src="https://user-images.githubusercontent.com/387249/158461877-980ba841-8ff3-4008-bcb1-0befa66c785d.png"> | <img width="1312" alt="Screen Shot 2022-03-15 at 12 04 55 PM" src="https://user-images.githubusercontent.com/387249/158461884-3e180788-6478-40ca-9809-4acf2cbd9810.png"> | <img width="1312" alt="Screen Shot 2022-03-15 at 12 07 53 PM" src="https://user-images.githubusercontent.com/387249/158462063-80d3b0d1-5928-4295-bf18-a4ec8cdab0fc.png"> | <img width="1312" alt="Screen Shot 2022-03-15 at 12 10 43 PM" src="https://user-images.githubusercontent.com/387249/158465095-555bec71-4824-42db-9f05-a7adcf233af0.png">





CAPTCHA screens whenever searching via the Tor window

<img width="1312" alt="Screen Shot 2022-03-15 at 12 05 24 PM" src="https://user-images.githubusercontent.com/387249/158464738-153f362c-9c63-4226-8290-b7df3855d1ee.png">


#### **`Test Case #2`** - Upgrade (Other SE default other than Brave Search)

* downloaded/installed `1.36.112`
* ensured that the Tor window mentions that DDG is the default SE
* ensured that the Tor window is using `https://duckduckgo.com/?q=` as the default SE
* changed the default SE to `Ecosia` via `brave://settings/search`
* ensured that `Ecosia` is set as the default SE via `brave://settings/searchEngines`
* Upgraded to `1.36.115`
* ensured that `Ecosia` is still the default SE under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that there's no duplicates being listed under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that all mentions of DDG are removed from the Tor window
* ensured that `https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/search?q=` is the default SE

**`Before`** - `1.36.112`

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/38657976/158365457-e45c8ece-00ad-4120-ab92-78ef074283cb.png) | ![image](https://user-images.githubusercontent.com/38657976/158365621-da1ba277-8122-4b44-88ac-a4f9c557da3a.png) | ![image](https://user-images.githubusercontent.com/38657976/158365765-221098a7-7681-4642-bfd1-834079083b1d.png)


**`After`** - `1.36.115`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|-----------------
![image](https://user-images.githubusercontent.com/38657976/158366632-3339e230-e431-4248-a0a4-256862bae9bd.png) | ![image](https://user-images.githubusercontent.com/38657976/158366739-eff3ca5d-ade0-4e68-927a-e8e378b9dfaf.png) | ![image](https://user-images.githubusercontent.com/38657976/158366853-809a9f0d-f101-4da8-b3d0-e3b62f8caf2e.png) | ![image](https://user-images.githubusercontent.com/38657976/158366955-d647ca42-6363-4309-9e47-b7b44410d28c.png) | ![image](https://user-images.githubusercontent.com/38657976/158367021-9b4d5873-7dbc-4eac-b8ee-67d5c6f75c42.png)


#### **`Test Case #3`** - Upgrade (Brave Search as default)

* downloaded/installed `1.36.112`
* ensured that the Tor window mentions that DDG is the default SE
* ensured that the Tor window is using `https://duckduckgo.com/?q=` as the default SE
* changed the default SE to `Brave` via `brave://settings/search`
* ensured that `Brave` is set as the default SE via `brave://settings/searchEngines`
* Upgraded to `1.36.115`
* ensured that `Brave` is still the default SE under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that there's no duplicates being listed under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that all mentions of DDG are removed from the Tor window
* ensured that `https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/search?q=` is the default SE

**`Before`** - `1.36.112`

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/38657976/158368747-92f8774f-0ae9-4955-8747-7b29b543e2b4.png) | ![image](https://user-images.githubusercontent.com/38657976/158368830-767aa488-0348-4cca-b7f0-e4c8e18040eb.png) | ![image](https://user-images.githubusercontent.com/38657976/158368889-be4521ae-378f-4321-816b-b11e35e42948.png)


**`After`** - `1.36.115`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|-----------------
<img width="1312" alt="Screen Shot 2022-03-15 at 1 27 28 PM" src="https://user-images.githubusercontent.com/387249/158466990-5f58adf1-c0b4-4e38-acb2-efe3c89a5dd1.png"> | <img width="1312" alt="Screen Shot 2022-03-15 at 1 12 05 PM" src="https://user-images.githubusercontent.com/387249/158467093-a5efa6eb-e706-4bf6-93e7-dd04bc14cb83.png"> | <img width="1312" alt="Screen Shot 2022-03-15 at 1 25 49 PM" src="https://user-images.githubusercontent.com/387249/158467206-ffdacd60-3951-4a41-a180-8ac4b9ae7e65.png"> | <img width="1312" alt="Screen Shot 2022-03-15 at 1 34 31 PM" src="https://user-images.githubusercontent.com/387249/158467592-07e1e0e0-c246-409e-bdb9-6d1481d0fed9.png"> | <img width="1312" alt="Screen Shot 2022-03-15 at 1 34 36 PM" src="https://user-images.githubusercontent.com/387249/158467599-7c901a98-ee3a-400b-b05c-c35babcaeceb.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.36.115 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Ubuntu 18.04 LTS

- Verified the STR mentioned in the description
- Confirmed open a TOR window displays the text as `Search Brave or type a URL` in the URL bar
- Confirmed search is performed by using the `Brave` SE
- Confirmed that CAPTCHA test is being done whenever searching via the Tor window

<details>
![image](https://user-images.githubusercontent.com/34715963/158485034-78e37409-094d-45ab-81f9-b1adb05d075c.png)
![image](https://user-images.githubusercontent.com/34715963/158485215-cbbc96a7-89da-466a-a495-aa9588f1041d.png)
![image](https://user-images.githubusercontent.com/34715963/158485264-7fba6103-f7a0-47a6-a5d9-0583394f822d.png)


</details>


- Verified the cases mentioned in the https://github.com/brave/brave-core/pull/12391#issuecomment-1066151499

#### **`Test Case #1`** - Clean Install

* ensured that Brave Search is the default SE for both Normal/Private windows
* ensured that Brave Search is the default SE for Tor Windows and ensured that the `.onion` address is being used
  * `https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/search?q`
* ensured that `https://search.brave.com/search?q=` is still being used under Normal & Private windows
* ensured that there's no mention of DDG anywhere under the Tor window nor any images associated with DDG
* ensured that the progress bar correctly indicates when Tor is being downloaded/connecting and connected successfully
* ensured that Brave Search is only listed once under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that the `:search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion` keyword is working as expected
* ensured that changing defaults via brave://settings/searchEngines doesn't affect the default Tor SE (should always be Brave)

<details>

![image](https://user-images.githubusercontent.com/34715963/158483504-0d115f13-6241-4dad-8d56-4560ba7d0241.png)
![image](https://user-images.githubusercontent.com/34715963/158484323-67c4b9d7-ea55-462f-aaa9-c4ce23f58e3d.png)
![image](https://user-images.githubusercontent.com/34715963/158484378-89d44bd9-1560-4c7e-b5e3-3dd3498ceb37.png)
![image](https://user-images.githubusercontent.com/34715963/158484421-04679877-6386-4ad7-a202-d9b68662068e.png)
![image](https://user-images.githubusercontent.com/34715963/158484742-b9f50206-47c2-46b9-8455-551e76412176.png)
![image](https://user-images.githubusercontent.com/34715963/158484796-81e506e1-3eb4-4736-81aa-00a332a21748.png)


</details>




#### **`Test Case #2`** - Upgrade (Other SE default other than Brave Search)

* downloaded/installed `1.36.112`
* ensured that the Tor window mentions that DDG is the default SE
* ensured that the Tor window is using `https://duckduckgo.com/?q=` as the default SE
* changed the default SE to `Ecosia` via `brave://settings/search`
* ensured that `Ecosia` is set as the default SE via `brave://settings/searchEngines`
* Upgraded to `1.36.115`
* ensured that `Ecosia` is still the default SE under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that there's no duplicates being listed under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that all mentions of DDG are removed from the Tor window
* ensured that `https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/search?q=` is the default SE

<details>


**`Before`** - `1.36.112`

![image](https://user-images.githubusercontent.com/34715963/158486198-ce582f55-1daa-4038-ace0-8d06646e8b9f.png)
![image](https://user-images.githubusercontent.com/34715963/158486336-529abd4c-1138-4b9e-a872-23ac9f47be45.png)



**`After`** - `1.36.115`

![image](https://user-images.githubusercontent.com/34715963/158486445-09bb4769-fb16-4948-9928-c5840b97ad5b.png)
![image](https://user-images.githubusercontent.com/34715963/158486544-c1b221a6-6f28-4738-bc8d-49b31886e000.png)
![image](https://user-images.githubusercontent.com/34715963/158486602-9ac15474-eb7b-4674-aa25-ab8e3d414884.png)


</details>

#### **`Test Case #3`** - Upgrade (Brave Search as default)

* downloaded/installed `1.36.112`
* ensured that the Tor window mentions that DDG is the default SE
* ensured that the Tor window is using `https://duckduckgo.com/?q=` as the default SE
* changed the default SE to `Brave` via `brave://settings/search`
* ensured that `Brave` is set as the default SE via `brave://settings/searchEngines`
* Upgraded to `1.36.115`
* ensured that `Brave` is still the default SE under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that there's no duplicates being listed under `brave://settings/search` & `brave://settings/searchEngines`
* ensured that all mentions of DDG are removed from the Tor window
* ensured that `https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/search?q=` is the default SE

<details>

**`Before`** - `1.36.112`

![image](https://user-images.githubusercontent.com/34715963/158486921-408a5f66-c573-4477-a069-27c020ebcacd.png)
![image](https://user-images.githubusercontent.com/34715963/158487014-6d24a5e8-2e5c-4c62-bcee-6f51b0f404ab.png)



**`After`** - `1.36.115`

![image](https://user-images.githubusercontent.com/34715963/158487141-dc0eb234-bea6-4298-8392-c983ef7360ff.png)
![image](https://user-images.githubusercontent.com/34715963/158487196-7fb772c6-b43b-403c-8452-3fd1a9d70ae5.png)
![image](https://user-images.githubusercontent.com/34715963/158487243-705849c6-0c6f-42a8-b78b-9ad1f0e49dd5.png)


</details>
