### ISSUE TITLE
Arrived message is not showing up the actual claimed BAT amount

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#20597]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18602
The arrived message is not showing the actual claimed BAT amount

## Steps to Reproduce

   1. Clean profile 1.35.x enable rewards
   2. Fake the ads earnings for the previous month
   3. Confirmed ads earnings are shown in Ads panel
   4. Ask Chris to send Ad grants to this profile
   5. Claim the Ad grants and confirmed ad grants BAT is shown (In my case it was 9 BAT ad grants)
   6. Set the device date to 7th Jan
   7. Relaunch the browser and ensured `Arrived message` is shown but it's not showing up the actual claimed amount of `9 BAT`
   instead it's showing up the faked ads earnings of previous month `0.01 BAT` and this amount is not cashed in with server
## Actual result:

The arrived message is not showing up the actual claimed BAT amount
![image](https://user-images.githubusercontent.com/38657976/150340821-6d0125d5-cc38-452f-a878-569c86a5a72b.png)

## Expected result:
The arrived message should show the actual claimed 9 BAT amount

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.35.87 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 21H2 (Build 19044.1466)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @zenparsing @Miyayes

**Comment by LaurenWags** [comment]
Needs 1.35.96 or higher

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.35.96 Chromium: 98.0.4758.66 (Official Build) (64-bit)
-- | --
Revision | db1b4001d5ce29f141297f260d2b778e000b85a3-refs/branch-heads/4758@{#762}
OS | Windows 10 Version 21H2 (Build 19044.1466)

```
Method 1:
- Create a new profile and enable rewards.
- Close browser
- Fake ad earnings for the previous month by adding an entry to the `transactions` table.
- Fake ad grant claim for the previous month by setting a value in the `balance_report_info` table.
- Set the system time to Jan 7th Jan.
- Open the browser and refresh the rewards page
- Confirmed payment `Arrived message` is shown and `BAT amount is removed` from the Arrived message
- Confirmed payment Arrived message is shown on 8th, 9th, 10th and 11th Jan

8th Jan | 9th Jan | 10th Jan | 11th Jan
-----|-----|-----|----
![image](https://user-images.githubusercontent.com/38657976/151519022-03494ec1-ac68-410b-b1f8-25b248ed7ea4.png)
