### ISSUE TITLE
`Start using rewards` button isn't removed from NTP even after enabling rewards in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#20598]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/16028
`Start using rewards` button isn't removed from NTP even after enabling rewards in an upgraded profile
## Steps to Reproduce

   1. Clean install 1.34.x enable rewards
   2. View a couple of ads and reset the rewards
   3. Confirm ads and AC switches are in OFF state
   3. Upgrade the profile 1.35.x
   4. Confirm ads and AC switches are in OFF state
   5. Open a new NTP and click on `Start using rewards` to enable rewards
   6. Confirm rewards gets enabled
   7. `Start using rewards` button isn't removed from NTP even after enabling rewards

## Expected result:
`Start using rewards` button should be removed from NTP after enabling rewards

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.35.87 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 21H2 (Build 19044.1466)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @Miyayes @LaurenWags

**Comment by LaurenWags** [comment]
@GeetaSarvadnya this reproduces in 1.34.x as well, correct?

**Comment by GeetaSarvadnya** [comment]
@LaurenWags That's correct

**Comment by Miyayes** [comment]
@rmcfadden3 Might have reproduced.
