### ISSUE TITLE
Limit decimals for amounts in input fields based on the token

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20596]
Use `BlockchainToken.decimals` to limit the number of decimals an amount can have in an input field. Currently, there's no validation done on decimals, which results in hex-encoded values like `0x0.004816f0068db8bac711`, subsequently failing in the transaction creation step without any indication.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.93 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11948>brave/brave-core#11948</a></li>
         <li>Verified <code>Too many decimals</code> error is shown when decimal value is exceeded the limit</li>
         <li>Verified <code>Send</code>/ <code>Swap</code> button is disabled when decimal value is exceeded the limit</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/154087968-2f4df4d1-43e2-4134-8ffa-3221ac769957.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154089754-09f5b122-306b-463d-b22a-fd1b667b7867.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154090296-c6885006-37ee-48fe-bc4a-b7ed81219a18.mov>
      </td>
   </tr>
</table>
