### ISSUE TITLE
PrivacyTests.org comparison: improve brave performance

### ISSUE THREAD

**Issue by pachainti** [brave/brave-browser#20599]
Hi,
I found this interesting [comparison](https://privacytests.org/). Brave already performs quite well, there is room for improvement in the test especially (state partitioning, https, fingerprint)?
Thank you

Edit: https://brave.com/privacy-updates/14-partitioning-network-state/

**Comment by pachainti** [comment]
Great, now brave fulfils almost all points in all categories.
Still needs to improve in the HTTPS test and Fingerprinting resistance tests sections.
What about providing [HTTPS only mode](https://github.com/brave/brave-browser/issues/22737)?
With regard to fingerprinting [System font detection](https://github.com/brave/brave-browser/issues/816#issuecomment-1101698392) is supported by several browsers and brave could also do it.

**Comment by pachainti** [comment]
A very interesting article on fingerprinting [Why browser anti-fingerprinting techniques are not effective](https://fingerprint.com/blog/browser-anti-fingerprinting-techniques/). It analyses uniformity and randomization approaches. Regarding brave it states that:

_Interestingly, however, this wiki page is currently not fully up-to-date as WebRTC has [dedicated settings](https://support.brave.com/hc/en-us/articles/360017989132-How-do-I-change-my-Privacy-Settings-#webrtc). Instead, the [Client Hints JavaScript API](https://github.com/brave/brave-browser/issues/17651)’s [getHighEntropyValues](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues) method returns accurate information, and the [Battery Status API](https://github.com/brave/brave-core/blob/1cb5818aa0b70666c6aeea5ea9c06cc4e712171a/chromium_src/third_party/blink/renderer/modules/battery/battery_manager.cc) returns fixed values in all cases._

_More importantly, the algorithms for randomization are prone to several errors:_

_Websites can detect artificial randomization by calling the affected APIs twice, finding anomalies in the randomized data, or simply assuming that values are randomized by identifying the browser. Websites can afterward either ignore these values or process them in a way that aids fingerprinting.
The original entropy from the raw source data still exists, and implementations adding additional randomness to the underlying data [might be reversible in practice](https://fingerprint.com/blog/audio-fingerprinting/#reverting-brave-standard-farbling).
When other potentially indirect methods exist of learning about the raw source data, the original entropy can still be used without using one of the obvious ways to serialize the original data._

I think Brave should do something to improve the current situation.
Thank you

**Comment by pes10k** [comment]
Thank you for the report @pachainti , though Im going to close this out as a duplicate.  We have shipped several additional fingeprinting protections since your report (for example [screen attributes](https://brave.com/privacy-updates/23-grab-bag-5/#4-protecting-against-screen-attribute-based-browser-fingerprinting)) and have some additional ones in the pipeline. We've also fixed the `getHighEntropyValues` issue reported.  If there are specific items from privacytests.org you think should be fixed, please check for and file bugs against those though, that'd be greatly appreciated.
