### ISSUE TITLE
Can't install translate extension after prompt

### ISSUE THREAD

**Issue by mostaf7583** [brave/brave-browser#20608]
## Steps to Reproduce

   1. when click ib add extenstion for google translate it doesnot add to the browser .

## Reproduces how often: 

easily prouduced

## Brave version (brave://version info)

Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by rebron** [comment]
@mostaf7583 What operating system are you using? Windows?

**Comment by rebron** [comment]
cc: @kjozwiak

**Comment by kjozwiak** [comment]
Going to close this one off as it seems to be working on both `1.39.122 Chromium: 102.0.5005.115` & `1.41.59 Chromium: 103.0.5060.42`. Basically went through the following:

**`Test Case #1 - 1.39.122 Chromium: 102.0.5005.115`**

* downloaded/installed `1.39.122 Chromium: 102.0.5005.115`
* visited https://www.wp.pl and ensured that I was prompted re: installing the Google Translate extension
* installed the extension without any issues and pinned the extension once installed
* translated https://www.wp.pl using `Translate this page` without any issues

**`Test Case #2 - 1.41.59 Chromium: 103.0.5060.42`**

* downloaded/installed `1.41.59 Chromium: 103.0.5060.42`
* visited https://www.bild.de and ensured that I was prompted re: installing the Google Translate extension
* installed the extension without any issues and pinned the extension once installed
* translated https://www.bild.de using `Translate this page` without any issues

**`Example using 1.39.122`** | **`Example using 1.41.59`**
---------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/173498817-1fccd4ef-ac6b-4b63-99d0-b448d226d46a.png) | ![germanExample](https://user-images.githubusercontent.com/2602313/173499594-4596ca0f-913c-42a0-816a-2a66e2aa9c02.png)

Builds being used:

```
Brave | 1.41.59 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.708)
```

```
Brave | 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | Windows 11 Version 21H2 (Build 22000.708)
```

**Comment by kjozwiak** [comment]
@mostaf7583 let me know if you're still having issues. I tried the above on a few different machines and it seems to be working.

**Comment by mostaf7583** [comment]
there isno issues
 thanks alot
