### ISSUE TITLE
After connecting to https://lostpoets.xyz/ personalSign request does not work.

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20600]
personalSign should be more flexible and allow the address to be specified as the first parameter.  MM is more flexible and allows that so Dapps get it wrong sometimes. 

# QA Steps

Load  https://lostpoets.xyz/

Unlock wallet

Click connect

If there is a popup about needing MetaMask ignore it.  

Then it should ask to sign. After you sign it should show it is connected.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.93 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified able to connect wallet and sign message</li>
         <li>Verified disconnecting and reconnecting requests for sign message</li>
         <li>Verified able to successfully sign back in after disconnecting</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/153999000-6819929a-ee05-49b8-849d-5736cc1beb15.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153998467-ddb288ea-d6aa-4478-8fac-a7f32241e67d.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153998456-9693e688-815d-4686-92e9-1dc543eefec8.mov>
      </td>
   </tr>
</table>
