### ISSUE TITLE
Auto-contribute default should be 1.000 BAT, not 5.000 BAT

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20606]
## Description 

Auto-contribute default should be 1.000 BAT, not 5.000 BAT

Per https://github.com/brave/brave-browser/issues/18834, the default has changed from `5.000 BAT` -> `1.000 BAT` elsewhere in the UI.

## Steps to reproduce 

   1. install `1.36.54`
   2. launch Brave
   3. tap through onboarding
   4. enable Rewards staging prefs via `Developer options` -> `QA Preferences` -> `Use Rewards staging server` + `Verbose Logs for Ad-Rewards`
   5. relaunch Brave
   6. load `brave.com`
   7. tap on the BAT icon
   8. tap to `Start using Rewards`
   9. tap again on the BAT icon
   10. claim the UGP grant
   11. tap one more time on the BAT icon
   12. confirm `Monthly contribution` reads `1 BAT` in the Rewards panel
   13. tap on `Send Tip`
   14. in the resulting `Tip amount` dialog, note the default BAT amount/value

## Actual result 

`5.000 BAT`

![Screenshot_20220120-113130](https://user-images.githubusercontent.com/387249/150409213-7d9dce2d-12fb-4856-b1c5-1979b4b8b557.png)

https://user-images.githubusercontent.com/387249/150408895-80080ca5-f215-4391-b81d-478cc3d9eaeb.mp4

## Expected result

`1.000 BAT`

![Screenshot_20220120-113135](https://user-images.githubusercontent.com/387249/150409234-3698e5fb-90d3-4ce9-821e-bd79cf00b865.png)

## Issue reproduces how often 

100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

`1.36.54, Chromium 97.0.4692.99`

cc @LaurenWags @deeppandya

**Comment by stephendonner** [comment]
This is also present in `1.35.x`, so once this is fixed and verified on `nightly`, we should probably uplift 👍

**Comment by LaurenWags** [comment]
fyi @stephendonner - I think this is a duplicate of https://github.com/brave/brave-browser/issues/20200

**Comment by stephendonner** [comment]
> fyi @stephendonner - I think this is a duplicate of #20200

Indeed; thanks (and I should've looked more).
