### ISSUE TITLE
Add chainId validation to the network settings page

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#20605]
follow up from https://github.com/brave/brave-browser/issues/17640 and https://github.com/brave/brave-core/pull/10641#discussion_r734846967

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.93 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11971>brave/brave-core#11971</a></li>
         <li>Verified <code>chainId</code> validation is done on both <code>Chain ID</code> and <code>RPC URL's</code></li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/21101>#21101</a> & <a href=https://github.com/brave/brave-browser/issues/21102>#21102</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Invalid <code>chainiD</code>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/154022716-6d1c0ba7-23ae-4e87-bae6-34ed969d2fa8.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/154025625-91bdf12d-3b68-4d4d-be55-fea52ab78045.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/154025578-caeefae4-013b-4138-a844-44ed3d022d37.png>
      </td>
   </tr>
   <tr>
      <td>Invalid  <code>RPC URL's</code>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/154022937-44f496c6-ce17-4825-bda9-b239d07cc565.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/154025668-d7275adc-5413-4fa6-9838-cba23ebbb779.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/154025604-9cb898f2-b417-4279-bc45-25e828760cfa.png>
      </td>
   </tr>
</table>
