### ISSUE TITLE
Replace crlsets with redirector

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#20609]
### `Test Plan`

* https://github.com/brave/brave-core/pull/11917#issue-1108918729

### `Information/Context`

* See https://github.com/brave/devops/issues/3313 for more information/context.

**Comment by kjozwiak** [comment]
@brave/legacy_qa please ping me when you're about to run through the above. This requires some configuration from @linhkikuchi via server side before we can run through the STR/Cases.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.84 Chromium: 98.0.4758.87 (Official Build) dev (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. set up Charles Proxy
2. installed Brave
3. ran Charles Proxy
4. launched Brave


Confirmed:
* spellcheck dictionary request is handled over in https://github.com/brave/brave-browser/issues/16380
* requests for components were proxied through `redirector.brave.com` and all return `200 OK` (e.g. `https://redirector.brave.com/edgedl/release2/chrome_component/acswg5tbkr2ithrql6kjeh6vvwrq_2022.1.24.1201/ggkkehgbnfjpeggfpleeakpidbkibbmn_2022.1.24.1201_all_oa3ppuxckzsaqpp445iqxhz4e4.crx3`)
* requests via `componentupdater.brave.com` were handled and returned `200 OK` (e.g. `https://componentupdater.brave.com/service/update2/json`
* within an 8-minute window, `brave://components` updated with a successful check for `CRLSet`, and displayed `Up-to-date` status
* also confirmed requests had a `braveservicekey` header w/key value (not pictured)

example | example | example
---------|----------|---------
<img width="1787" alt="Screenshot 2022-02-04 at 06 47 44" src="https://user-images.githubusercontent.com/387249/152550553-9e6a3b81-855f-4120-93d3-17aeb45f26af.png"> | <img width="1787" alt="Screenshot 2022-02-04 at 06 53 37" src="https://user-images.githubusercontent.com/387249/152550642-69b0c328-e468-4dfe-9f51-567985d21120.png"> | <img width="1312" alt="Screenshot 2022-02-04 at 06 45 36" src="https://user-images.githubusercontent.com/387249/152551187-80a8503e-e6db-456b-89d2-7a7290989e91.png">
