### ISSUE TITLE
Shouldn't be able to drag/drop BAT icon outside of CAPTCHA panel

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20619]
## Description 

Shouldn't be able to drag/drop BAT icon outside of CAPTCHA panel

## Steps to Reproduce

   1. fresh profile
   2. launch Brave using Rewards & Ads staging
   3. enable Rewards
   4. click to try to claim the UGP grant
   5. drag the CAPTCHA piece out of its panel, into the browser window

## Actual result:

You'll get a `chrome://` URL such as `chrome-extension://jidkidbbcafjabdphckchenhfomhnfma/out/c9255cc2aa3d81ca6328e82d25a95766.png`

example | example
---------|----------
<img width="1312" alt="Screen Shot 2022-01-21 at 6 23 24 AM" src="https://user-images.githubusercontent.com/387249/150543511-526943b6-97db-4c5c-9b8f-caf3f59439e2.png"> | ![wtf-captcha-drag](https://user-images.githubusercontent.com/387249/150543588-40a0a2cb-2f1d-4c39-8b42-ec45c4057c1d.gif)

## Expected result:

Shouldn't be a drop/drag target outside the panel bounds

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.36.55 Chromium: 97.0.4692.99 (Official Build) nightly (x86_64)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | macOS Version 12.2 (Build 21D48)

cc @emerick @LaurenWags

**Comment by srirambv** [comment]
This has been an issue from the time Captcha was implemented. #2959 was logged for the same reason and closed as wontfix without reasoning.

**Comment by Miyayes** [comment]
Given vBAT removal, this will no longer be relevant.
