### ISSUE TITLE
GOV.UK Covid-19 Lateral Flow Test Reporting: Scandit QR code scan not working

### ISSUE THREAD

**Issue by ShintoPlasm** [brave/brave-browser#20616]
## Description 
The UK Government allows people to self-report the results of their Covid-19 rapid antigen tests via a dedicated website. You can either register an account (using NHS login credentials) or enter all details from scratch each time. As part of this process, the website allows you to either scan the QR code on the testing device or manually enter the code. The QR code scanning function (provided by Scandit) asks for permission to use your device's camera. This works fine in Firefox for Android, but in Brave the scanning function only shows a black screen. Clearly something *is* happening because Android's green camera indicator appears in the top bar and the Scandit overlay icons appear in the QR scanning area on the webpage; but nothing seems to appear through the device's camera itself.

## Steps to reproduce 

   1. Go to https://test-for-coronavirus.service.gov.uk/report-result/
   2. Start reporting an LFT result, entering your details.
   3. When you arrive at the QR code scanning stage (specifically on https://test-for-coronavirus.service.gov.uk/report-result/barcode), tap on the button telling you to scan your QR code.

## Actual result 
Brave asks for camera permission. The QR scanning function starts up in a rectangle on the webpage, as expected, but the rectangle itself doesn't show anything through the device's camera and remains black. The overlay icons appear in the rectangle. The Android 12 camera indicator appears in the top bar.

## Expected result
The QR scanning function should start, with the 'camera' rectangle showing things through the device's camera.

## Issue reproduces how often
Easily reproduced every time.

## Version/Channel Information:
Observed in Stable.

## Device details
   - Device type (Phone, Tablet, Phablet): Phone - Google Pixel 5
   - Android version: 12
   
## Brave version
1.34.80

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A (Brave Rewards already disabled)
- Is the issue reproducible on the latest version of Chrome? Not attempted

**Comment by bhourahine** [comment]
Its probably coming from upstream chrome (and most likely broken on the website side, rather than the browser). I get the same behaviour on android with chrome 97.

**Comment by ShintoPlasm** [comment]
> Its probably coming from upstream chrome (and most likely broken on the website side, rather than the browser). I get the same behaviour on android with chrome 97.

Quite possible, though I note that it works correctly in Firefox for Android.

**Comment by ShintoPlasm** [comment]
Fixed as of Brave Stable v1.38.109 (Chromium 101.0.4951.41).
