### ISSUE TITLE
Upgrade from C97 -> C98 on `macOS x64` for `1.36.x - Nightly` (Checking C98)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#20611]
As per process, we're going to QA and ensure that upgrading from `C97` --> `C98` doesn't cause any issues. Once everything looks good on `Win x64`, `Linux`, `macOS x64` and `Android ARM`, QA will sign off and get C98 merged into `master`.

### Upgrade

- [x] Make sure that data from the last version appears in the new version OK
- [x] Ensure that `brave://version` lists the expected Brave & Chromium versions
- [x] With data from the last version, verify that:
  - [x] Bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x] Cookies are preserved
  - [x] Installed extensions are retained and work correctly
  - [x] Opened tabs can be reloaded
  - [x] Stored passwords are preserved
  - [x] Sync chain created in previous version is retained
  - [x] Social media-blocking buttons changes are retained
  - [x] Rewards
    - [x] Wallet balance is retained
    - [x] Auto-contribute list is retained
    - [x] Both Tips and Monthly Contributions are retained
    - [x] Wallet panel transactions list is retained
    - [x] Changes to rewards settings are retained
    - [x] Ensure that Auto Contribute is not being enabled when upgrading to a new version if AC was disabled
  - [x] Ads
    - [x] Both `Estimated pending rewards` & `Ad notifications received this month` are retained
    - [x] Changes to ads settings are retained
    - [x] Ensure that ads are not being enabled when upgrading to a new version if they were disabled
    - [x] Ensure that ads are not disabled when upgrading to a new version if they were enabled

**Comment by stephendonner** [comment]
Verified `PASSED` using

(`Chromium 97` `nightly`)
Brave | 1.36.59 Chromium: 97.0.4692.99 (Official Build) nightly (x86_64)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | macOS Version 12.2 (Build 21D48)

to

(`Chromium 98` `nightly`)
Brave | 1.36.57 Chromium: 98.0.4758.66 (Official Build) nightly (x86_64)
-- | --
Revision | db1b4001d5ce29f141297f260d2b778e000b85a3-refs/branch-heads/4758@{#762}
OS | macOS Version 12.2 (Build 21D48)
