### ISSUE TITLE
Unable to turn on Brave Ads

### ISSUE THREAD

**Issue by ygz213** [brave/brave-browser#20620]
## Description

Brave Ads button is unable to be changed.

## Steps to reproduce

   1. Go to chrome://rewards
   2. Click button

## Expected result

It should be able to be turned on and off.

## Issue reproduces how often

Easily reproduced (always)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? **?**
- Can you reproduce this issue with the current Play Store Beta version? **Yes**
- Can you reproduce this issue with the current Play Store Nightly version? **Yes**

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10 (Q)
   
## Brave version

1.34.81 from GitHub

### Additional information

Changed flags:

`#smooth-scrolling`: Enabled
`#enable-quic`: Enabled
`#enable-gpu-rasterization`: Enabled
`#enable-force-dark`: Enabled
`#enable-parallel-downloading`: Enabled
`#reduce-user-agent`: Enabled

Video: (no flag changed in Beta and Nightly versions)

https://user-images.githubusercontent.com/77006222/150544068-0a887bdc-a4ab-4bfa-a4f6-0facc065faa3.mp4

**Comment by Miyayes** [comment]
Can you go to brave://rewards-internals? This happens if "Wallet not yet created". 

>1.34.81 from GitHub

Also, builds that aren't downloaded from the Google Play Store have various issues with Rewards, so testing via github apk releases isn't necessarily representative for Rewards.

**Comment by ygz213** [comment]
> This happens if "Wallet not yet created".

I created an empty wallet but it didn't change.

**Comment by Miyayes** [comment]
>I created an empty wallet but it didn't change.

Do you see a valid Wallet Payment ID there? 

>I installed 1.34.81's Play Store version and nothing changed.

Can you download an Android Safety Net checker app and see if your phone passes/fails SafetyNet? Thanks.

**Comment by ygz213** [comment]
> Do you see a valid Wallet Payment ID there?

In accounts window, I see my crypto account name and ID.

> Can you download an Android Safety Net checker app and see if your phone passes/fails SafetyNet? Thanks.

![SafetyNet](https://user-images.githubusercontent.com/77006222/150874095-66347a67-1a2e-4639-9dce-ee91cea700e0.jpeg)

**Comment by Miyayes** [comment]
>In accounts window, I see my crypto account name and ID. 

Thanks, but would you be able to go to brave://rewards-internals and see if it says "Wallet not yet created", or if you see a UUID (a bunch of letters, numbers, with dashes) after "Wallet Payment ID"? Thanks.

**Comment by ygz213** [comment]
I already created one but it still says "Wallet not yet created".

**Comment by Miyayes** [comment]
Related per @srirambv: https://github.com/brave/brave-browser/issues/13489

**Comment by ygz213** [comment]
I just fixed the issue by logging into my old crypto account.
