### ISSUE TITLE
[Android] Add UI messaging/design that tells users they have 90 days to claim ad earnings and solve CAPTCHA

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20626]
## Description 

Android version of https://github.com/brave/brave-browser/issues/17133. 

I believe we inherit the settings page changes. The NTP Rewards widget changes are irrelevant on Android. Only changes needed are on Rewards panel (toast notification). 

![image](https://user-images.githubusercontent.com/11497541/150569799-b2aa9407-bdd4-4f87-b5dd-0a84c56303be.png)

**Comment by Miyayes** [comment]
Right now, the claim button looks like this, which should be updated to be much closer to design spec and desktop: 
![image](https://user-images.githubusercontent.com/11497541/163599350-40be029d-1cb9-40bc-9a2b-74ead5ee3bb4.png)
 
@deeppandya

**Comment by stephendonner** [comment]
## Verified `PASSED` using `Brave` `1.48.140`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` running `Android 9`

### Steps:
1. installed `1.47.161`
2. launched Brave
3. through the `QA Debug` menu, enabled `Rewards` staging
4. relaunched
5. had @LaurenWags set up on ad grant for me on staging
6. confirmed I saw a pending ad-grant notification on the `BAT icon` in the URL bar 
7. installed `1.48.140` atop of `1.47.161` (both are `beta`-channel builds)
8. relaunched Brave
9. tapped the `BAT icon`
10. tapped `CLAIM` for the `3.250 BAT` ad grant

#### Confirmed the new UI and that 3.250 BAT was added to my profile

`pending ad grant` | `claimed ad grant` | `screencast`
--------------------|--------------------|-------------
![Screenshot_20230125-113235](https://user-images.githubusercontent.com/387249/214680282-d1ca4b44-8aec-47f9-8602-cfce9b7e5da3.png) | ![Screenshot_20230125-113248](https://user-images.githubusercontent.com/387249/214680286-8cd879b4-d969-4cfd-829a-bbc0b8e5992d.png) | <video src="https://user-images.githubusercontent.com/387249/214680621-3d89fc66-1fdd-4cca-bbef-f574e9f7fe68.mp4">

**Comment by Miyayes** [comment]
Also, as of late 1.49.x, this will no longer be relevant, since vBAT payouts will be no more.
