### ISSUE TITLE
Brave wallet incorrect gas price for Rinkeby test net.

### ISSUE THREAD

**Issue by mklilley** [brave/brave-browser#20629]
## Description 
Brave wallet reports gas price on Rinkebey Ethereum testnet about 100 times what it should be. Is the wallet actually reporting the mainnet price instead of the testnet?

## Steps to Reproduce
Not sure how to describe this. I created a little webapp to call a smart contract on the Rinkeby network (using ethers js library). Everything went fine. I clicked a button to mint an NFT and the wallet opened - nice. But, the gas price was huge, 0.175ETH as you can see in the attached image

![Screenshot 2022-01-21 at 20 34 40](https://user-images.githubusercontent.com/7937044/150598940-ea43da79-880e-4e5f-ab2b-48a2b4f519e8.png)

When you look at the result of the [minting of the NFT on etherscan](https://rinkeby.etherscan.io/tx/0xcfc93b860a346b0512151a8a0340122130d26ad0c7d19782af233695148d864e) you can see that the actual transaction fee was much lower 0.00098894501186734 ETH

 
![Screenshot 2022-01-21 at 20 53 06](https://user-images.githubusercontent.com/7937044/150599107-d250fe7e-e165-4afc-996a-d789f56c7861.png)

Is this a bug? Is the wallet pulling in the Ethereum main net gas price instead of the testnet one? Currently main net gas price is about 100-200 times Rinkeby testnet.

## Brave version (brave://version info)
Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (x86_64)

I'm using MacOS 12.0.1

**Comment by josheleonard** [comment]
Closing. The Ethereum Foundation deprecated Rinkeby on October 5th, 2022
