### ISSUE TITLE
The page (except to navigation bar) is still while in dark theme

### ISSUE THREAD

**Issue by BugRMSys** [brave/brave-browser#20634]
## Description 
When I set the theme of Brave to dark and go back to homepage and search something, the navigation bar is in dark, but the background is still in white color.

## Steps to reproduce 

   1. Click "three dots" button on the right-down position of Brave.
   2. Click the settings 
   3. Click apperance
   4. Click Theme
   5. Choose  Dark and go back to homepage and serach something
   6. The body of page is still white

## Actual result 
The backgound of pages are still in white color, only the navigation bar is in dark color

## Expected result
The whole page are in dark color .

## Issue reproduces how often 
Easily reproduced

## Screen Shot:
![Uploading im
![brave-01](https://user-images.githubusercontent.com/15137182/150641854-b34f7d84-3e6b-41b2-928b-abb7efb4ba41.jpeg)
age.png…]()

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Yes
- Can you reproduce this issue with the current Play Store Nightly version?
- Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): XIMI 11 Ultra
   - Android version: MIUI 12.5.20
   
## Brave version
1.34.80

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Daniel4SE** [comment]
![brave-01](https://user-images.githubusercontent.com/93385422/150642775-bf7356f2-e8cf-4fba-ba11-778e9a145e4b.jpeg)

**Comment by BugRMSys** [comment]
![brave-01](https://user-images.githubusercontent.com/15137182/150642827-bfbe5512-8473-4f9e-b0c9-41c34ca30774.jpeg)

**Comment by spylogsster** [comment]
cc @rebron

**Comment by srirambv** [comment]
Changing theme only applies to the bottom bar and URL bar not for webview. If you want the webpages to show up in dark theme as well, please enable the `Enable "Night Mode" (Experimental)` option under Appearance. Note this is not a finished feature but rather a Chrome flag that is provided, so it will probably have issues with some sites and may not provide true dark theme experience on all websites.
