### ISSUE TITLE
Add source button text is unreadable on hover state

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20639]
## Description 

Add source button text is unreadable on hover state

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. open a new-tab page
   4. opt in to Brave News
   5. click on `Customize`
   6. click on `Brave News`
   7. hover over the `Add source` button
   8. try to read it

## Actual result:

It's unreadable: white-on-white text and background.

![button-hover-unreadable](https://user-images.githubusercontent.com/387249/150667977-3ad86cd4-65ef-43e1-baba-c36429f3d5b8.png)

## Expected result:

Button text isn't obscured by color change; remains readable upon hover

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.36.60 Chromium: 97.0.4692.99 (Official Build) nightly (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Windows 10 Version 20H2 (Build 19042.1466)

cc @petemill @mattmcalister @srirambv

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.7 Chromium: 99.0.4844.45 (Official Build) nightly (x86_64)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | macOS Version 12.3 (Build 21E5222a)

Confirmed default, hover, and clicked states, using `light` and `dark` themes.

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-02-27 at 7 09 13 PM" src="https://user-images.githubusercontent.com/387249/155917851-417c31a2-68e8-4b0f-9fe2-f6586fcca9ee.png"> | <img width="1312" alt="Screen Shot 2022-02-27 at 7 08 22 PM" src="https://user-images.githubusercontent.com/387249/155917868-897888a7-24b8-4903-91dc-b2a3fb385888.png">

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.36.115 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the STR mentioned in the description and enured mouse hover text is in readable format

Light mode | Dark mode
--|---
![image](https://user-images.githubusercontent.com/38657976/158372348-1cca071a-08a2-4bba-accd-1849c3f6eb05.png) | ![image](https://user-images.githubusercontent.com/38657976/158372418-6026d949-951c-4ac2-8011-439af5d90b2d.png)
