### ISSUE TITLE
Feed Url should read Feed URL

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20638]
## Description 

Feed Url should read Feed URL

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. opt in to Brave News
   4. click on `Customize` on the new-tab page
   5. click on `Brave News`
   6. look beneath `Your Sources`

## Actual result:

It reads `Feed Url`

![feed-url](https://user-images.githubusercontent.com/387249/150667859-fa07c60b-8cfe-47cb-a893-eaa5df555129.png)

## Expected result:

Should read `Feed URL`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.36.60 Chromium: 97.0.4692.99 (Official Build) nightly (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Windows 10 Version 20H2 (Build 19042.1466)

**Comment by ash1895-web** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by srirambv** [comment]
@ash1895-web Please create a PR for the fix. I've assigned the issue to you

**Comment by ash1895-web** [comment]
Thanks @srirambv  for assigning the issue.

**Comment by ash1895-web** [comment]
Hello @srirambv , I am trying to clone the repository from last 20 hours but the process is still not completed. Is this a normal behaviour? or may be it is too much to bear for my intel i3 ?

**Comment by srirambv** [comment]
> I am trying to clone the repository from last 20 hours 

Cloning the brave repo is taking that long or building the code?

**Comment by ash1895-web** [comment]
Cloning

**Comment by Tonev** [comment]
@stephendonner 

I think this one should be closed as resolved.

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

#### Confirmed the string now reads `Feed URL`

<img width="1228" alt="Screen Shot 2022-04-12 at 2 16 28 PM" src="https://user-images.githubusercontent.com/387249/163056046-7766cbed-5348-4c4e-b4ec-908a67568dff.png">
