### ISSUE TITLE
Incorrect Asset icon on Brave Wallet (Crypto)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20649]
## Description 
Incorrect Asset icon on Brave Wallet (Crypto)

## Steps to reproduce 

   1. Clean install 1.36.57 x64 Nightly build
   2. Enable Brave Wallet
   3. Skip onboarding for backup key
   4. Once portfolio loads shows ETH & BAT both having ETH icon

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/150755581-524d1125-94c4-46e7-a9d8-a46e05e97b52.png>

## Expected result
<img width=300 src=https://user-images.githubusercontent.com/17010094/150755798-ad57e0f2-7a07-43b0-8553-82f9476a0046.png>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 11
   
## Brave version
1.36.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @wchen342

**Comment by SergeyZhukovsky** [comment]
@srirambv I tried on 3 diff devices with a fresh nightly(it's 1.36.58 currently). Samsung Galaxy S10, Pixel 6 and Motorola One Vision. I see correct icons on all of them. Do you have more details?

**Comment by srirambv** [comment]
Issue happened on CR98 build

**Comment by samartnik** [comment]
Problem was with components loading, fixed in cr98 https://github.com/brave/brave-core/commit/47d09ff41e730d5afeb6d1face7a16ac27a41d9c

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36.85 x64 beta build
- Verified individual token icon is shown correctly 

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<img width=285 src=https://user-images.githubusercontent.com/17010094/152780626-fe14202d-5ede-43f1-84f0-4d4ff7c59f3c.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/152780611-2e6e37e3-2ed4-454c-bb82-b3b3bd22bf53.png>
