### ISSUE TITLE
Rewards button is not shown upon upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20646]
## Description 
Rewards button is not shown upon upgrade

## Steps to reproduce  

Note: Steps may not be concrete. That was the setup I had before upgrade so added it as steps

   1. Install 1.36.54 nightly 
   2. Enable rewards
   3. Enable News (maybe optional)
   4. View some ads and add AC list
   5. Upgrade to 1.36.57 build, Rewards button is not shown in URL bar

## Actual result 

![image](https://user-images.githubusercontent.com/17010094/150753185-ad91ae2f-e6ab-4dc2-9347-6c1302671998.png) | ![image](https://user-images.githubusercontent.com/17010094/150753210-9fbea777-401c-42dd-b309-a951c3084a73.png)
-- | --

## Expected result
Show Rewards button when enabled

## Issue reproduces how often 
Intermittent. Needs investigation

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.36.57 x64 Nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Tried clean install and multiple upgrades after I ran into the issue but no luck reproducing it.

**Comment by Miyayes** [comment]
Perhaps related to this? https://github.com/brave/brave-browser/issues/20633 @srirambv @emerick

**Comment by emerick** [comment]
Yes, most likely the same issue.

**Comment by srirambv** [comment]
Repro'd the issue when night mode is enabled and relaunched via prompt

**Comment by srirambv** [comment]
A work around to get the rewards button back is to disable bottom toolbar but re-enabling it will cause the button to hide again

https://user-images.githubusercontent.com/17010094/150979129-20c11324-fd0b-4415-be43-061edf8ecf3c.mp4



cc: @samartnik

**Comment by samartnik** [comment]
I got this issue on my nightly build. Somehow `PREF_HIDE_BRAVE_REWARDS_ICON` returns true for me, even though I didn't change it. @emerick is it possible this is due to this change? https://github.com/brave/brave-core/commit/747ebb9213fc4406ef3ada65a18e9d00cf2712ff

**Comment by emerick** [comment]
@samartnik Yep, it is due to that change. @deeppandya is looking into fixing this today!

**Comment by Uni-verse** [comment]
Verified using `1.36.93, Chromium 98.0.4758.87`

Device: `Samsung GS21` / `Android 12`

- Upgrading does not result in missing rewards icon
- Rewards data persists after upgrade

**Comment by kjozwiak** [comment]
@Uni-verse we're going to need to recheck this as this wasn't uplifted into `1.36.x` yet as per https://github.com/brave/brave-core/pull/12228. Still opened while writing this comment.

@deeppandya issues should stay in milestones where they're fixed and are moved once uplifts are completed. For example, in this case, this should still be in `1.37.x` until https://github.com/brave/brave-core/pull/12228 is uplifted at which point, the release team will move it into the milestone.

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` for `Android` till https://github.com/brave/brave-browser/issues/21183 is addressed/fixed. The above can also be tested alongside https://github.com/brave/brave-browser/issues/19695 & https://github.com/brave/brave-browser/issues/20633 when https://github.com/brave/brave-browser/issues/21183 is fixed.

**Comment by srirambv** [comment]
Verification passed as part of https://github.com/brave/brave-browser/issues/21183#issuecomment-1050609212. 
- Verified on both clean install and upgrade scenario rewards button is hidden or shown based on the setting
