### ISSUE TITLE
Browser crash when Wallet Networks is selected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20648]
## Description 
Browser crash when Wallet Networks is selected

## Steps to reproduce 

   1. Install 1.36.57 nightly build
   2. Create Wallet account (optional)
   3. Open Settings -> Brave Wallet -> Networks, browser crashes

## Actual result 
Browser crash when Wallet Networks is selected

## Expected result
No crash

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.36.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
@srirambv I tried on 3 diff devices with a fresh nightly(it's 1.36.58) currently. Samsung Galaxy S10, Pixel 6 and Motorola One Vision. Not crashes on them. Could you please catch logs if you still can replicate it?

**Comment by srirambv** [comment]
Issue happened on CR98 build

**Comment by samartnik** [comment]
Fixed directly in cr98 https://github.com/brave/brave-core/commit/03bba1e13010faca7d0c4a7a21388ebdad5c33f4

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.96 x64 build
- Verified no crash when changing network from portfolio page
- Verified no crash when changing network when changing it from Buy/Send/Swap screen

https://user-images.githubusercontent.com/17010094/151489558-d99a64be-657c-4fb5-92e0-fdaaf2f8b75a.mp4

---------
Verification passed on Oppo Reno 5 with Android 11 running 1.35.96 x64 build
- Verified no crash when changing network from portfolio page
- Verified no crash when changing network when changing it from Buy/Send/Swap screen

https://user-images.githubusercontent.com/17010094/151489575-b1494e21-3ad7-4f8d-8caa-61d104a098e0.mp4
