### ISSUE TITLE
No check mark on P3A onboarding slide

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20647]
## Description 
No check mark on P3A onboarding slide

## Steps to reproduce 

   1. Clean install Android build
   2. P3A onboarding slide has a checkbox which is filled with solid colour instead of check mark

## Actual result 
<img witdh=300 src=https://user-images.githubusercontent.com/17010094/150754146-7a9e0dfa-020a-4c25-a677-5bde50434c17.png>

## Expected result
<img witdh=300 src=https://user-images.githubusercontent.com/17010094/150754163-d7d36517-2e1a-4938-a6a6-d0735f02c188.png>

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.36.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by samartnik** [comment]
Fixed directly in cr98 https://github.com/brave/brave-core/commit/83cdb36394971c59af2a5d35f4a96fee62f8d685

**Comment by Uni-verse** [comment]
Verification **PASSED** on `Samsung GS 21` running `Android 12` using `1.36.96, Chromium 98.0.4758.87`

- Verified P3A onboarding slide has a checkbox which is filled with solid colour instead of check mark

![Screenshot_20220217-100611_Brave - Beta](https://user-images.githubusercontent.com/17885425/154397816-2f8e59e8-2b9b-4d0d-a143-c10074c66964.jpg)
