### ISSUE TITLE
Put an icon in sidebar if Brave Talk is being used. If clicked, go to active tab

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#20645]
## Description 
If Brave Talk is active in any tabs, we should show an icon in the sidebar (Maybe @bradleyrichter / @mattmcalister can help provide)

If the user clicks this icon, it should locate and jump to the active Brave Talk tab. If there are multiple, it should handle properly

## Steps to Reproduce
   1. Have 30 tabs open
   2. Open a Brave Talk session and join a meeting
   3. Mute yourself because you're not talking
   4. Look at work related stuff in other tabs during the meeting
   5. Somebody calls your name - time to find the tab so we can unmute ourselves!

## Actual result:
Takes like 10 seconds to find the tab (so that we can unmute ourself)

## Expected result:
It should be super easy to find the active tab

**Comment by bsclifton** [comment]
I forgot - we already do have an icon there:
![image](https://user-images.githubusercontent.com/4733304/150739053-69d8eeef-7ed3-41e2-a177-a913ca4556db.png)

We could make the behavior of this button:
Does user have Brave Talk already open?
- YES
    - Find the tab (if multiple, try to find the one with active session; ex using microphone and/or video)
    - Make that tab active
- NO
    - Open https://talk.brave.com/widget

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.29 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

#### Case 1: Negative testing
1. new profile
2. launch Brave
3. load `brave://flags`
4. click to set `Enable Sidebar` to `Enabled`
5. load `talk.brave.com`
6. click the `Start free call (up to 4 people)` button
7. enter a name (`"talk tab 1"`) and click on `Join meeting`
8. click on the `Brave Talk` icon in the Sidebar
9. confirm:
    * clicking does NOT open a new window/tab
    * clicking does NOT interrupt current call

#### Case 2: Single Brave Talk tab
1. new profile
2. launch Brave
3. load `brave://flags`
4. click to set `Enable Sidebar` to `Enabled`
5. load `search.brave.com`
6. click on the `Brave Talk` icon in the Sidebar
7. confirm `talk.brave.com/widget` loads in the current tab

#### Case 3: Multiple Brave Talk tabs
1. new profile
2. launch Brave
3. load `brave://flags`
4. click to set `Enable Sidebar` to `Enabled`
5. load `talk.brave.com`
6. click the `Start free call (up to 4 people)` button
7. enter a name (`"Talk tab 1"`) and click on `Join meeting`
8. in a new tab (but same *window*), open `search.brave.com`
9. in a new tab, open `talk.brave.com`
10. enter a name (`"Talk tab 2"`) and click on `Join meeting`
11. click to focus the `search.brave.com` tab
12. click on the `Brave Talk` icon in the Sidebar
13. confirm you cycle focus to `tab 2`
14. click again on the `Brave Talk` icon in the Sidebar
15. confirm you cycle focus to `tab 1`

example | example
---------|---------
<img width="1156" alt="Screen Shot 2022-02-06 at 12 22 01 AM" src="https://user-images.githubusercontent.com/387249/152913052-b42ccd3a-d4eb-48dd-bdf9-843715864856.png"> | <img width="1092" alt="Screen Shot 2022-02-06 at 3 46 47 AM" src="https://user-images.githubusercontent.com/387249/152913220-80b7e30b-73f8-41de-a65f-daf9ac1c5898.png"> | 

Encountered these issues:
https://github.com/brave/brave-browser/issues/20921
https://github.com/brave/brave-browser/issues/20907

**Comment by simonhong** [comment]
Re-opened. This doesn't work after merging https://github.com/brave/brave-core/pull/12330.

**Comment by kjozwiak** [comment]
Requires `1.37.90` or higher for QA verification's via `1.37.x` .
