### ISSUE TITLE
Session history issues 

### ISSUE THREAD

**Issue by bitshiftnetau** [brave/brave-browser#20642]
## Description 
Session does not restore when hitting "Restore" and other session history issues, such as this form. In other browsers such as firefox, if I enter information here, close brave then reopen, it should restore all the text inside this form. 

## Steps to Reproduce

   1. Unknown

## Actual result:
Session is sporadic in restoration

## Expected result:
All session history should be restored

## Reproduces how often: 
Every time I close brave

## Brave version (brave://version info)
Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? unknown
- Can you reproduce this issue with the nightly channel? unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Unknown

## Miscellaneous Information:
Arch Linux system 5.16.2-arch1-1

**Comment by bitshiftnetau** [comment]
Turns out this was a result of clearing all website data. I know this coz I've also been signed out of all my accounts like Netflix and Gmail. 

**This was prompted by Brave** to "save space" or some shit... which I thought meant like clearing cruft data not active data being used in a session, didn't expect it would delete the last session or credential history. 

Please fix or alert the user properly as to what this means. If I want to clear my cache, I'll do that myself thanks. 

Also, next time... think before you code. I know it's difficult to accept but not every feature you roll out is golden, sometimes it's just fucking stupid.

**Comment by rebron** [comment]
Closing per your last comment. Apologies, looks like an error on our part for not notifying you on what clearing all website data means but not an issue on session history in general as you originally reported.
