### ISSUE TITLE
Editing a custom network adds a new entry rather than updating existing one

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20653]
## Description 

Found while testing #19917, editing a custom network doesn't update the existing one instead adds a new entry 

## Steps to Reproduce

   1. Add a custom network
   2. Edit the network by updating the decimal value of the chain and save
   3. Adds a new entry with updated data instead of updating the existing one

## Actual result:

Editing a custom network adds a new entry rather than updating existing one

## Expected result:
Should update existing entry rather than adding a new one

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster

**Comment by HEagle18** [comment]
I tried this with Arbitrum network on 1.50v and it worked okay. Can you reproduce @srirambv  ?

**Comment by srirambv** [comment]
Can't repro this anymore. Closing as stale
