### ISSUE TITLE
using `CHROMN` as attribution when searching using Bing

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#20659]
## Description 

When searching via Brave within Desktop/Android, we use `CHROMN` as the search attribution. I'm pretty sure this belongs to Google which means any Brave user searching with Bing is generating revenue for Google.

```
https://www.bing.com/search?q=test&PC=U316&FORM=CHROMN
```

## Steps to Reproduce

  1. launch Brave
  2. Using Bing, perform a search and you'll notice `PC=U316&FORM=CHROMN` being used as the search attribution

## Actual result:

Using the following search attribution when using Bing:

```
https://www.bing.com/search?q=test&PC=U316&FORM=CHROMN
```

## Expected result:
Remove PC=U316&FORM=CHROMN

Url should be: https://www.bing.com/search?q=%s

## Reproduces how often: 

100% reproducible using the STR/Cases mentioned above.

## Desktop Brave version:

```
Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Windows 11 Version 21H2 (Build 22000.438)
```

## Android Device details:

   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Mobile/Phone`
   - Android version: `Android 12`

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @bsclifton @janypiotrowski @rebron

**Comment by kjozwiak** [comment]
iOS has a similar issue as per https://github.com/brave/brave-ios/issues/4890 but uses `MOZMBA` rather than `CHROMN`.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.36.86 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1503)

```
**Case 1**: Search using bing search keyword `:b` 
           - Clean profile 1.36.x
           - Enter the `Bing` search keyword  `:b` in the URL bar and hit TAB 
           - Enter any string and confirmed URL no longer has the attached search-attribution parameters mentioned in the issue https://github.com/brave/brave-browser/issues/20659#issue-1113124586
           - Opened dev tool and confirmed URL no longer has the attached search-attribution parameters

Search result parameter | Dev tool parameter
-----|-------
![image](https://user-images.githubusercontent.com/38657976/152821276-1c0e4f8a-fe80-4f26-810c-d86c43b3d14d.png) | ![image](https://user-images.githubusercontent.com/38657976/152821190-067a4c3b-5bcb-48da-b5ca-e7cbf5a489ef.png)

**Comment by Uni-verse** [comment]
Verification **PASSED** on `Samsung Galaxy S21` running `Android 12` using build version: 

`1.36.86, Chromium 98.0.4758.87`

https://github.com/brave/brave-browser/issues/20659#issue-1113124586
- Verified search attribution is removed when setting `Bing` as default search engine
- Verified searching in private mode removes attribution

![Screenshot_20220208-035230_Brave - Beta](https://user-images.githubusercontent.com/17885425/152872344-964b698c-158a-4ef7-82fe-40a7635fe3b0.jpg)
