### ISSUE TITLE
Disable EIP-1559 on Polygon and Avalanche

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20652]
Emergency fix until https://github.com/brave/brave-browser/issues/20469 is ready.

We want to disable EIP-1559 (Type-2) transactions on Polygon and Avalanche for the time being, since our current gas oracle for EIP-1559 only supports Ethereum mainnet, leading to bad priority fee estimations.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.93 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11968> brave/brave-core#11968</a></li>
         <li>Verified EIP-1559 gas pricing is removed for Polygon</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/154019230-7f757946-9b21-4db1-b2af-e1408933448d.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154020019-da961114-17b6-4393-af5b-27cf53bf07df.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154020097-14f73c78-0011-4507-be92-5537d508af8b.mov>
      </td>
   </tr>
</table>
