### ISSUE TITLE
[Android] Rewards panel needs better handling for smaller screen sizes

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20679]
## Description 
If you are using a newer Android device (ex. Google Pixel 3XL with Android 12), the rewards panel looks fine - most text is on 1 line and the panel doesn't take up the whole screen. However, on an older Android device (Samsung J7 Neo with Android 7), the panel doesn't look at nice. Lots of text goes onto 2 lines. This is ok in English but could cause problems with non-english languages as the panel grows longer. Also, the panel just doesn't look as nice this way.

## Steps to reproduce 
pre-req: be using older Android device
   1. Clean install 1.35.x
   2. Enable staging env in QA Prefs, relaunch as necessary
   3. Enable rewards
   4. Look at panel

## Actual result 

Light theme | Dark theme
----- | -----
![light](https://user-images.githubusercontent.com/28145373/150997033-865a7573-46f6-46d7-80f7-378193038f26.png) | ![dark](https://user-images.githubusercontent.com/28145373/150997049-c78c3bba-1704-4541-9d21-ecafadae8bc0.png)

## Expected result

Pixel for comparison:
![Screenshot_20220125-092557](https://user-images.githubusercontent.com/28145373/150997080-2eb93554-6d77-4bdb-a649-1c5bf4eba151.png)

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: older, such as 7
   
## Brave version
1.35.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

viewport size on Pixel 3XL: 412px x 693px, screen size is 412px x 846px
viewport size on J7 Neo: 360px x 560px, screen size is 360px x 640px

cc @Miyayes @deeppandya

**Comment by Miyayes** [comment]
Will be somewhat resolved with changes coming in estimated earnings 2.0 redesign.
