### ISSUE TITLE
Show new transactions in BuySendSwap transactions list

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#20677]
## Description 
New transactions are not being added in transactions list

## Steps to reproduce 

   1. Login wallet, Select ETH (or any) coin in the list
   2. Perform a swap (or any transaction)
   3. Verify if the new transaction is being shown on buysendswap screen

## Actual result 
New transactions are not being shown in the transaction list

https://user-images.githubusercontent.com/11755381/151238212-71a32ef1-b109-4c00-a2a4-e5acacf903cd.mp4

## Expected result
List should show the new transactions (should show the unapproved transaction). 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.36.67

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.37.89 x64 beta build
- Verified steps from issue description
- Verified new transactions are listed in asset details view 

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/157852150-e1cb7886-88bc-4448-b592-977f267dafc1.mp4> | <video src=https://user-images.githubusercontent.com/17010094/157852077-977cfc13-9ff6-4d23-ae9e-97edd80b4ff0.mp4>
