### ISSUE TITLE
Implement Sending transactions with Filecoin accounts

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#20676]
placeholder to sign transactions with Filecoin accounts
https://github.com/blitslabs/filecoin-js-signer/blob/master/src/client/methods/tx.ts#L74
https://documenter.getpostman.com/view/4872192/SWLh5mUd?version=latest
https://github.com/glifio/wallet/blob/refactor/components/Wallet/Send/index.tsx#L93
https://github.com/blitslabs/filecoin-js-signer/blob/2a6b45bef529a94bfeffdcc0feeac834a48d992d/src/signing-tools/methods/tx.ts#L81

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13061>brave/brave-core#13061</a></li>
         <li>Verified able to do a send transaction from Filecoin account</li>
         <li>Encountered <a href=https://github.com/brave/brave-core/pull/23192>#23192</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171494901-7bf7f15e-fad4-43fa-ac43-0c4b7a7c0068.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171496453-0916dde5-b31e-4cff-bd7a-9cc3e6f445bf.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171496406-be061cf1-1877-4a86-9ac1-5e4e30ec3fd2.mov>
      </td>
   </tr>
</table>
