### ISSUE TITLE
Selector moved out of bounds

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#20681]
## Description 

In narrow windows selector is moved out of overlay borders
![image](https://user-images.githubusercontent.com/2965009/151008276-8f828973-b890-46df-855e-e30463fb93c2.png)

## Steps to Reproduce

   1. open imported accounts
   2. make window narrow
   3. check derivation path selector position

## Actual result:

wrong selector position

## Expected result:

selector inside overlay

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/11986>brave/brave-core#11986</a></li>
         <li>Verified reducing the window size to the smallest possible width doesn't cause the selector to be misaligned</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/154940803-d92eafba-5bce-490b-8563-cbc0ee404e30.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154940398-3cf242e0-bd4e-4521-bc7f-e81d0222abfd.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154940173-f475e3a9-269f-45be-ba81-5918c36e41a4.mov>
      </td>
   </tr>
</table>
