### ISSUE TITLE
Wire up Wallet UI to use Chain Icons

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20687]
## Description 
Wire up the Wallet UI to use Chain Icons
Follow up to https://github.com/brave/brave-core/pull/11966

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-browser/issues/20000>#20000</a></li>
         <li>Verified <code>Add token</code> shows icon for the coin that is being added</li>
         <li>Verified custom asset added shows the icon on visible asset list </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/153857875-09e182fe-de07-4205-b501-ebc5b3785827.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153858820-265c2ef5-8168-4464-8be4-97b30e3b586f.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153858912-90192c63-6e02-4424-9b55-f9a44b14912d.mov>
      </td>
   </tr>
</table>
