### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Marsbar69** [brave/brave-browser#20704]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.34.81  Chromium: 97.0.4692.99
Operating System: Windows NT 10.0.19042

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/29be0500-ce7a-9e07-0000-000000000000

**Comment by iefremov** [comment]
not actionable
