### ISSUE TITLE
Expose method to check if network supports swap via mojom

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20716]
Add a method `IsSwapSupported(string chain_id) => (bool result)` to the `SwapService` mojom interface, to avoid hardcoding supported networks for swap by clients.

Need to do integrate the same for mobile as well.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.3 (Build 21E230)
```

**Comment by Uni-verse** [comment]
Verification Completed using

```
Brave	1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64) 
Revision	5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS	macOS Version 12.1 (Build 21C52)
```

- New method automatically detects if network supports swap when switching between networks.

https://user-images.githubusercontent.com/17885425/160687055-4297356e-da2f-451a-bcd9-7106c10464c5.mov
