### ISSUE TITLE
[Android] bitFlyer announcement notification for Japan users

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#20725]
## Description 

@soi-tnk and the team in Japan would like to notify all Android users in Japan that they can now, as of V1.35, use bitFlyer with Brave Rewards. 

They would like to send all Japan Android users a system push notification with the following details:

**Title:** AndroidでもbitFlyer連携開始！
_(English: Now you can verify your Rewards wallet with bitFlyer in  Brave for Android as well!)_

**Body:** 最大5万円相当BATプレゼントキャンペーン実施中！bitFlyerアカウントと連携して獲得したBATを管理しよう。
_(English: Check special BAT present campaign - chance of getting BAT as much as ¥50,000. Let's manage BAT you earn by verifying your Rewards wallet with bitFlyer.)_

**Timing:** 120 min after upgrade or first install
**Region:** Japan only (new and existing users)

Tapping on the notification should open: http://try.bravesoftware.jp/brave_20220121-1/

This notification should **only** be scheduled once for the given release and should not be scheduled for subsequent releases. (i.e. if this notification is released into 1.36, the notification should not be rescheduled again in 1.37 or 1.38 etc)

**Comment by kjozwiak** [comment]
Some quick notes for @brave/legacy_qa. I went through the clean install cases via https://github.com/brave/brave-core/pull/12268#issuecomment-1041001367. However, we'll need to double check the following:

* We'll need to make sure that non-japan users upgrading from `1.35.100` to `1.35.101` don't see any BitFlyer notifications after 120mins (2hrs)
* ensure that Japan users see the BitFlyer notification after 120min (2hrs) but only see it once after upgrading from `1.35.100` to `1.35.101`.
* As per https://github.com/brave/brave-browser/issues/20725#issuecomment-1040961407, the URLs have changed

We'll need to be thorough re: the above as it wasn't checked via https://github.com/brave/brave-core/pull/12268#issuecomment-1041001367 as upgraded cases couldn't be done with the one off build that @deeppandya provided. We'll still need to run through the clean install cases, but keep in mind that the upgrade cases haven't been checked yet.

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/12268 was merged into `1.35.x`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 12` using `1.35.103 Chromium: 98.0.4758.102`

## Non-Japan (using Canada)

#### Clean Install (using `1.35.103 Chromium: 98.0.4758.102`)

* ensured that the BitFlyer notification being displayed on a clean install on first launch
* ensured that the BitFlyer notification isn't being displayed after `2hrs`
* ensured that the BitFlyer notification isn't being displayed after `3hrs`
* ensured that the BitFlyer notification isn't being displayed after `4hrs`
* ensured that the BitFlyer notification isn't being displayed after `1 day`
* ensured that the BitFlyer notification isn't being displayed after `2 days`
* ensured that the BitFlyer notification isn't being displayed after `3 days`
* ensured that the BitFlyer notification isn't being displayed after `4 days`

#### Upgrade (using `1.35.101 Chromium: 98.0.4759.87` --> `1.35.103 Chromium: 98.0.4758.102`)

* ensured that the BitFlyer notification isn't displayed after upgrading to `1.35.103 Chromium: 98.0.4758.102`
* ensured that the BitFlyer notification isn't being displayed after `2hrs`
* ensured that the BitFlyer notification isn't being displayed after `3hrs`
* ensured that the BitFlyer notification isn't being displayed after `4hrs`
* ensured that the BitFlyer notification isn't being displayed after `1 day`
* ensured that the BitFlyer notification isn't being displayed after `2 days`
* ensured that the BitFlyer notification isn't being displayed after `3 days`
* ensured that the BitFlyer notification isn't being displayed after `4 days`

## Non-Japan (using Canada)

#### Clean Install (using `1.35.103 Chromium: 98.0.4758.102`)

* ensured that the BitFlyer notification isn't being displayed on a clean install on first launch
* ensured that the notification appears after `2hrs` (example below)
* ensured that tapping on the BitFlyer notification opens https://brave.com/ja/bitflyer-on-android/
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved time `~3hrs` ahead)
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved time `~4hrs` ahead)
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved date by `1`)
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved date by `2`)
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved date by `4`)

**`Example`** | **`Example`**
---------------|----------------
![Screenshot_20220216-230439](https://user-images.githubusercontent.com/2602313/154387210-2787915a-09d1-41d0-ab81-7c08bf998c96.png) | ![Screenshot_20220216-230536](https://user-images.githubusercontent.com/2602313/154387222-f8cbc3ac-330e-4f44-b7a7-172b769a687b.png)

#### Upgrade (using `1.35.101 Chromium: 98.0.4759.87` --> `1.35.103 Chromium: 98.0.4758.102`)

* ensured that the BitFlyer notification isn't displayed after upgrading to `1.35.103 Chromium: 98.0.4758.102`
* ensured that the notification appears after `2hrs` (example below)
* ensured that tapping on the BitFlyer notification opens https://brave.com/ja/bitflyer-on-android/
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved time `~3hrs` ahead)
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved time `~4hrs` ahead)
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved date by `1`)
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved date by `2`)
* ensured that the BitFlyer notification doesn't appear once it's been displayed once (moved date by `4`)

**`Example`** | **`Example`**
---------------|----------------
![Screenshot_20220216-173113](https://user-images.githubusercontent.com/2602313/154387539-914fa593-f443-4879-8313-a82372e40f95.png) | ![Screenshot_20220216-173148](https://user-images.githubusercontent.com/2602313/154387564-0d5fca85-96cf-4f6b-ae55-fcb759b6fd43.png)
