### ISSUE TITLE
Don't include history to sidebar's default builtin items

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#20728]
## Test plan
1. Fresh install
2. Ensure sidebar is showing
3. Verify `History` isn't showing (you can hover to see tooltip name of the icons)

## Description
Built-in sidebar history item should not be included in sidebar.
Default items will be three items like below. (talk, wallet and bookmarks)
<img width="59" alt="Screen Shot 2022-01-27 at 2 37 39 PM" src="https://user-images.githubusercontent.com/6786187/151298325-8aa94b44-6462-456a-87ee-119800d0f6ff.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.36 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. installed `1.37.36`
2. loaded `brave://flags`
3. enabled `Enable Sidebar`
4. clicked `Relaunch`
5. looked at the Sidebar's default UI elements

Confirmed the default three (3) are: 1) Brave Talk 2) Wallet 3) Bookmarks

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-02-09 at 9 58 58 AM" src="https://user-images.githubusercontent.com/387249/153262731-6cf7e05e-00ff-4f07-8e95-0742fbea85f2.png"> | <img width="1312" alt="Screen Shot 2022-02-09 at 9 07 49 AM" src="https://user-images.githubusercontent.com/387249/153262875-832c0435-9b8b-42f7-82c2-1ad2fc772f42.png">

**Comment by MadhaviSeelam** [comment]
Brave |	1.37.91 Chromium: 99.0.4844.51 (Official Build) beta (64-bit) 
---|--- 
Revision |	d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS |	Windows 11 Version 21H2 (Build 22000.556)

1. Installed 1.37.x
2. 'Enable Sidebar' is no longer available in `brave://flags`
3. Verified Brave talk, Wallet and Bookmarks elements are available on the sidebar as a default
4. Verified all three elements on private tor window, private window and guest window

ex1|ex2|ex3|ex4
---|---|---|---
<img width="1550" alt="Screenshot 2022-03-14 163255" src="https://user-images.githubusercontent.com/98358127/158277740-e25327a8-d58a-42fb-88d0-c433186dec3d.png">|<img width="1550" alt="Tor Window" src="https://user-images.githubusercontent.com/98358127/158268253-fdedba84-30fb-4ab7-babd-775f4fa7e01c.png">|<img width="1550" alt="private window" src="https://user-images.githubusercontent.com/98358127/158268422-2fd8187d-d9a0-40ad-b21d-19991837a2f2.png">|<img width="1550" alt="guestwindow" src="https://user-images.githubusercontent.com/98358127/158268558-b896ce1c-4c1c-402e-a508-fc2d828e0b7d.png">|
