### ISSUE TITLE
Ad text in inline-content ad icon is red on Android, blurple on desktop

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20732]
## Description 

Ad text in inline-content ad icon is red on Android, blurple on desktop

## Steps to Reproduce

   1. view an inline-content ad on Android
   2. view an inline-content ad on desktop
   3. compare

## Actual result:

`Ad` is red on Android
`Ad` is blurple on desktop

Android | desktop
---------|---------
![Screenshot_20220127-004702](https://user-images.githubusercontent.com/387249/151324420-5b3879ff-bfad-46a0-952c-1faa752dc630.png) | <img width="61" alt="Screen Shot 2022-01-27 at 12 46 52 AM" src="https://user-images.githubusercontent.com/387249/151324631-7c7cdc1b-e1a6-43e2-aa0d-95667784dbf8.png">

## Expected result:

Should be the same...guessing the blurple?

## Reproduces how often: 

100%

## Brave version (brave://version info)

`1.36.73`

cc @alexsafe @mattmcalister @srirambv

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.38.63, Chromium 100.0.4896.46` on a `Google Pixel XL` running `Android 9.0`.

![Screenshot_20220322-111350](https://user-images.githubusercontent.com/387249/159548531-c73fc84c-cfe7-463c-96a7-417a02699b81.png)

**Comment by Uni-verse** [comment]
Verification completed us version

```
1.37.105 Chromium: 100.0.4896.46 (Official Build) (32-bit) 
Revision	5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
```

Devices:
`Samsung Galaxy S21` | `Android 12`
`Samsung Galaxy Tab S7` | `Android 11`

Tablet | Mobile
-|-
![Screen Shot 2022-03-24 at 3 35 18 PM](https://user-images.githubusercontent.com/17885425/160021628-d13bf4bc-ca87-40e8-a5a8-78a06657dca6.png) | ![Screen Shot 2022-03-24 at 3 38 09 PM](https://user-images.githubusercontent.com/17885425/160021630-b991e9a9-fb49-45c8-ba84-3dda4c60bc2a.png)
