### ISSUE TITLE
Brave Rewards panel can have a mismatch for icon and URL

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2073]
## Description 

Sometimes there's a mismatch for icon and name in the rewards panel.
<img width="521" alt="screen shot 2018-11-09 at 11 22 11 am" src="https://user-images.githubusercontent.com/831718/48275444-831c9480-e413-11e8-9416-4ad407614f42.png">

## Steps to Reproduce

Unsure of the exact steps, but probably something like go to calendar.google.com first, then google.com.

## Actual result:

google.com is displayed as the name
chrome://favicon/size/48@1x/https://calendar.google.com/ is displayed as the icon.

Both going to google.com and calendar.google.com displays the same way as per the screenshot above.

## Expected result:

It displays consistent results. 

## Reproduces how often: 

Always on my open window.

## Brave version (brave://version info)
0.56.10 

### Reproducible on current release:
Yes,

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  Yes.
- Is the issue reproducible on the latest version of Chrome?  N/a.

**Comment by LaurenWags** [comment]
@NejcZdovc two questions:
1. test plan from https://github.com/brave/brave-core/pull/1030 works, but I have to refresh brave://rewards to see the favicon for brave.com at the end of the test plan. Is this expected? 
2. stats.brave.com doesn't have a favicon
![screen shot 2019-02-06 at 11 00 46 am](https://user-images.githubusercontent.com/28145373/52354498-8cab9d80-29fe-11e9-8184-df24078b57eb.png)
so when I substitute a different site that does have a favicon, such as technology.slashdot.org, i see the same result (no favicon in Rewards until I visit slashdot.org). Is this expected?

**Comment by NejcZdovc** [comment]
@LaurenWags re 1 and 2: yes expected

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1030 and saw that at the end, brave://rewards had to be refreshed to see the favicon. Verified in comments above that this is expected.
