### ISSUE TITLE
Introduce "You've set up a pending tip" messaging for pending tip cases

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20748]
## Description

When a tip cannot go through and goes into the pending state, we should change the success messaging (right side of the tipping banner on desktop) to something that actually reflects the fact that the tip went into pending. The current text, which says "Your one-time tip has been sent" makes it seem as though the tip succeeded at that point. 

Example:

![image](https://user-images.githubusercontent.com/11497541/151442473-335ac93f-a54f-4a41-a162-1b3c034051b8.png)

**Comment by Miyayes** [comment]
Text: "You've set up a pending tip!"

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 12.5 (Build 21G72)
```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 10 Version 21H2 (Build 19044.1889)
```
