### ISSUE TITLE
incorrect URL bar placement on NTP for certain locales

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20743]
## Description 
URL bar placement on the Android NTP is incorrect for certain locales. It looks ok for US/English but is below the stats box for Japan/Japanese.

## Steps to reproduce 
pre-req: be set to Japan/Japanese
   1. Install 1.37.2 (Nightly) or 1.36.75 (Beta) from GPS
   2. Open NTP
   3. Looks like no URL bar until you look below stats box

## Actual result 

![Japan](https://user-images.githubusercontent.com/28145373/151426449-af48a4f4-445f-4092-bdb9-9f7cec31d6fb.png)

## Expected result

![US](https://user-images.githubusercontent.com/28145373/151426467-d4c84125-1d3d-4d71-9ae9-542e52a1ca63.png)

## Issue reproduces how often 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 1.34.x no, 1.35.x yes
- Can you reproduce this issue with the current Play Store Beta version? 1.36.x yes
- Can you reproduce this issue with the current Play Store Nightly version? 1.37.x yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @brave/legacy_qa @anthonypkeane

**Comment by LaurenWags** [comment]
Per additional investigation from @samartnik this has to do with Google as the SE. Reproduces with US/English when setting Google as SE.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.97 x64 build
- Verified updating the search engine to Google or any other SE doesn't move the URL bar position on NTP
- Verified selecting Google from onboarding on JP doesn't move the URL position on NTP
- Verified URL bar position is not changed on both normal and private tabs when Google is set as default SE

US | JP
-- | --
<video src=https://user-images.githubusercontent.com/17010094/151561794-f0bd3d0e-fdf1-47e3-8114-32cdc1086ec3.mp4>  | <video src=https://user-images.githubusercontent.com/17010094/151561878-9b4064a5-e82d-4587-a1d7-4021934cf144.mp4>

-------------
Verification passed on Samsung Tab A with Android 10 running 1.35.97 x64 build
- Verified updating the search engine to Google or any other SE doesn't move the URL bar position on NTP
- Verified selecting Google from onboarding on JP doesn't move the URL position on NTP
- Verified URL bar position is not changed on both normal and private tabs when Google is set as default SE

US | JP
-- | --
<video src=https://user-images.githubusercontent.com/17010094/151562998-1b4c202a-75a6-4e2d-b4da-2f747b77eff6.mp4> | <video src=https://user-images.githubusercontent.com/17010094/151563069-b172cdbd-7187-4359-b46e-41ede7b39d9c.mp4>
