### ISSUE TITLE
[Android] remove Auto Contribute line from panel summary when AC is off

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#20749]
## Description 

When AC is off, the summary line item for it should not be shown in the panel. 

This summary line item is correctly removed from the settings page. This is consistent with desktop.

## Steps to reproduce 

   1. Install 1.35.x, 1.36.x
   2. Enable Rewards
   3. Disable AC
   4. Look at summary from panel --> Auto Contribute line item is shown
   5. Look at summary on settings page --> Auto Contribute line item is not shown

## Actual result 

![AC off but on panel](https://user-images.githubusercontent.com/28145373/151444752-f68b522a-1e64-4ecc-8a46-11d9899ac41d.png)

## Expected result

![AC off and not on settings](https://user-images.githubusercontent.com/28145373/151444771-3549b99c-54bd-48ea-a231-0160a0931d32.png)

## Issue reproduces how often 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 1.35.x yes, 1.34.x n/a
- Can you reproduce this issue with the current Play Store Beta version? 1.36.x
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.35.x, 1.36.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes @deeppandya

**Comment by Uni-verse** [comment]
Verification completed for `Android ARM` using version `1.37.101, Chromium 99.0.4844.83`

Device: `Samsung GS 21` running `Android 12`

- Auto-Contribute entry removed from summary when disabling under brave://rewards
- Auto-Contribute not shown in summary from BR when disabled
- User is able to enable Auto-Contribute
- Auto-Contribute shown in summary when re-enabled 
- Auto-Contribute sites state is preserved when toggling off/on

Summary | BR panel
-|-
![Screen Shot 2022-03-22 at 5 00 22 PM](https://user-images.githubusercontent.com/17885425/159597657-24b98796-d51c-4fb7-aab5-e2d42bb5fcb7.png) | ![Screen Shot 2022-03-22 at 5 02 40 PM](https://user-images.githubusercontent.com/17885425/159597663-8f410080-536b-45fc-b6c0-0b068cd74ed5.png)

**Comment by Uni-verse** [comment]
Verification completed for `Android ARM` using `version 1.37.101, Chromium 99.0.4844.83`

Device: `Samsung Galaxy Tab S7` running `Android 11`

- Auto-Contribute entry removed from summary when disabling under brave://rewards
- Auto-Contribute not shown in summary from BR when disabled
- User is able to enable Auto-Contribute
- Auto-Contribute shown in summary when re-enabled
- Auto-Contribute sites state is preserved when toggling off/on

![Screen Shot 2022-03-22 at 5 58 08 PM](https://user-images.githubusercontent.com/17885425/159601094-aecc931d-1198-48e1-a33d-560ad6c4b2f3.png)
