### ISSUE TITLE
shields not tracking blocked embedded scripts breaking `Allow scripts once`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#20744]
## Description 

As per the issue mentioned via https://github.com/brave/brave-core/pull/11928#issuecomment-1022756329, it looks like we're not keeping track of embedded scripts as per https://github.com/brave/brave-browser/issues/20503#issuecomment-1023155540. Blocking them works as expected but the `Allow scripts once` feature doesn't unblock the scripts due to us not tracking what was blocked.

## Steps to Reproduce

1. loaded https://www.blizzard.com/en-gb and enabled `Scripts blocked`
2. once enabled, you'll notice that most of the website doesn't load (expected as scripts are being blocked)
3. click on `Allow scripts once` and you'll notice that scripts have been allowed but the website still doesn't work/load
4. disable `Scripts blocked` after you've clicked on `Allow scripts once` and notice that the website loads without any issues
5. enable `Scripts blocked` once more and notice that scripts are being blocked but it's showing `0` blocked next to `Scripts`

## Actual result:

![151274293-fbf3e1db-b0cb-4ad2-be90-7e4a4c561bdf](https://user-images.githubusercontent.com/2602313/151431283-f4d8b744-e163-4ed5-8acf-013b67187c29.gif)

## Expected result:

The  `Allow scripts once` feature should work as expected and Brave should be tracking which embedded scripts are being block so users can pick which exact scripts are being blocked via the `Allow scripts once` feature within shields.

## Reproduces how often: 

100% reproducible using the STR/Cases mentioned above.

## Brave version (brave://version info)

```
Brave | 1.36.73 Chromium: 98.0.4758.66 (Official Build) nightly (64-bit)
-- | --
Revision | db1b4001d5ce29f141297f260d2b778e000b85a3-refs/branch-heads/4758@{#762}
OS | Windows 11 Version 21H2 (Build 22000.438)
```

```
Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Windows 11 Version 21H2 (Build 22000.438)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A` (issue is related to shields)
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @goodov @rebron @bsclifton @brave/legacy_qa

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.35.98 Chromium: 98.0.4758.74 (Official Build) (x86_64)
-- | --
Revision | d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. loaded `www.blizzard.com` and enabled `Scripts blocked`
3. clicked on `Allow scripts once` and confirmed the page loaded
4. clicked on it again, and confirmed the rest of the page loaded

example | example | example
---------|----------|----------
<img width="1312" alt="Screen Shot 2022-01-31 at 10 14 51 AM" src="https://user-images.githubusercontent.com/387249/151850183-f8a44b7c-2256-489f-ae74-6671f650a452.png"> | <img width="1312" alt="Screen Shot 2022-01-31 at 10 15 06 AM" src="https://user-images.githubusercontent.com/387249/151850190-8f4d41aa-e0fa-49b4-821e-a94caf916a74.png"> | <img width="1312" alt="Screen Shot 2022-01-31 at 10 15 10 AM" src="https://user-images.githubusercontent.com/387249/151850206-a6a89c19-b7d5-411a-8554-c05ec76e9666.png">
