### ISSUE TITLE
set kDesktopSharingHubEnabled to false

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#20757]
## Description 

The sharing hub feature in recent Chrome needs additional consideration. For the time being, set kDesktopSharingHubEnabled to false until users are able to customize the `Share link to` of providers. 

We can keep kDesktopSharingHubEnabled set to true in Beta and Nightly channels as we test this implementation.

## Steps to Reproduce

   1. Use latest with RC, beta or nightly with latest Chromium 98.
   2. brave://flags/#sharing-hub-desktop-omnibox Should be default and in this case will be default enabled.
   3. Notice the sharing hub icon and functionality in url bar when visiting any web page (not the new tab page or any internal page).

## Actual result:

<img width="337" alt="Screen Shot 2022-01-26 at 9 20 28 PM" src="https://user-images.githubusercontent.com/5951041/151471530-71ce5dff-b20b-4f16-9d52-8d7162634d60.png">

## Expected result:
Same as in 1.34.x with individual icons for QR code, sending of device, and no sharing icon in the url bar.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.35.96 and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a but release candidate
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.35.98 Chromium: 98.0.4758.74 (Official Build) (x86_64)
-- | --
Revision | d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}
OS | macOS Version 11.6.1 (Build 20G224)

Confirmed:
* pref is set to false via `brave://prefs-internals`
* no share icon/UI shows up in the URL bar
* even re-enabling the hub via `brave://flags` doesn't bring it back (probably needs a specific pref change)

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-01-31 at 10 00 33 AM" src="https://user-images.githubusercontent.com/387249/151848922-63a9f356-8bc7-4881-84eb-ec7a846c8a2e.png"> | <img width="1312" alt="Screen Shot 2022-01-31 at 10 09 02 AM" src="https://user-images.githubusercontent.com/387249/151848981-79b5d9de-b728-45ae-9493-fcc3b856f9bd.png">
