### ISSUE TITLE
Add Swap Rewards slide in Rewards onboarding slideshow 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20751]
## Description

Add a slide in the Rewards onboarding slideshow that promotes Swap Rewards. It would probably have to come at the end, since if the user clicks on it, it'll probably open up a new tab into brave://wallet (?). UI/UX TBD. 

**Note:** Recall that there are 2 onboarding slideshow flows: one where the user actually enables Brave Rewards, and one where the user is only taking a tour but not necessarily enabling Brave Rewards.

**Comment by srirambv** [comment]
@Miyayes @jamesmudgett  is this going to be Desktop specific or will there be a Android one as well?
