### ISSUE TITLE
[Cr98] "Autocomplete search and URLs" setting is missing.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#20750]
## Description 

"Autocomplete search and URLs" setting is missing from the brave://settings/privacy page.

## Steps to Reproduce

   1. Start Brave and navigate to brave://settings/privacy
   
## Actual result:
No "Autocomplete search and URLs" toggle on the page
![image](https://user-images.githubusercontent.com/41635752/151447165-0effd611-fcdb-45f4-acd3-57745d6520d6.png)

## Expected result:
"Autocomplete search and URLs" is the first toggle on the page
![image](https://user-images.githubusercontent.com/41635752/151447277-584c88dc-4b4d-45cc-adf1-3843bf5e83d7.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.37.2, 1.35.96

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.35.98 Chromium: 98.0.4758.74 (Official Build) (64-bit)
-- | --
Revision | d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}
OS | Windows 10 Version 21H2 (Build 19044.1466)

```
- Confirmed `Autocomplete searches and URLs` is shown in the brave://settings/privacy in CR 98 
![image](https://user-images.githubusercontent.com/38657976/151772944-7e03fadd-0666-4212-8029-db604a2f1563.png)
