### ISSUE TITLE
Widevine not working since C71

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2076]
It's because the build flags changed, so it's no longer attempting to install it.

To test: Just make sure Netflix works.

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.57.7 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X
