### ISSUE TITLE
Brave News toolbar / Settings header isn't cleared on tab-overview page

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20768]
## Description 

Brave News toolbar / Settings header isn't cleared on tab-overview page

## Steps to reproduce 

   1. install `1.37.5`
   2. launch Brave
   3. tap through onboarding
   4. tap on the 3-dots menu on the bottom toolbar
   5. tap `Settings`
   6. tap `Appearance`
   7. tap to set `Enable Tab Groups` to `Off`
   8. tap `RELAUNCH NOW`
   9.  swipe down
   10. tap to `Show Brave News`
   11. open a bunch of new-tab pages
   12. ensure you see the `Brave News` header w/`Settings` icon in at least one of the tabs
   13. add 2 or 3 more tabs
   14. now click on the tab-count eg `[11]` icon

## Actual result 

example | example  | example
---------|---------|---------
![Screenshot_20220128-001032](https://user-images.githubusercontent.com/387249/151513728-b160727c-6ef5-4f7a-b173-36f3d62d2032.png) | ![Screenshot_20220128-001731](https://user-images.githubusercontent.com/387249/151513735-c21e75fe-8e9f-48ff-926f-c4e49b54ed23.png) | ![Screenshot_20220128-001748](https://user-images.githubusercontent.com/387249/151513736-3ee40efe-7527-4c15-bb93-0148bc11a090.png)

https://user-images.githubusercontent.com/387249/151514086-81e0a165-269e-4ff9-848c-70ab3e2ae6e4.mp4

## Expected result

The `Brave News` toolbar header shouldn't persist in the tab-overview view

## Issue reproduces how often 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

`1.37.5, Chromium 98.0.4758.74`

cc @alexsafe @mattmcalister @srirambv @kjozwiak

**Comment by srirambv** [comment]
This seems fixed on nightly. @stephendonner mind re-testing this one and close it out

cc: @alexsafe

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.37.18, Chromium 98.0.4758.87` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

Tested using my original steps, and confirmed the `Brave News` header didn't "bleed" or leave artifacts.

example | example | example
---------|----------|---------
![Screenshot_20220201-155508](https://user-images.githubusercontent.com/387249/152071533-56b38cdb-4366-477e-902a-1c029686dcd4.png) | ![Screenshot_20220201-155517](https://user-images.githubusercontent.com/387249/152071538-6a2c4203-d7d6-4066-b7b2-83fdd5c8dbd7.png) | ![Screenshot_20220201-155533](https://user-images.githubusercontent.com/387249/152071539-3203561e-bf8f-47d8-8ddf-7145b448e59f.png)

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.36.99`, `Chromium 98.0.4758.102` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.


https://user-images.githubusercontent.com/387249/154779355-64800de9-207c-4923-8f6c-e268d5ef057a.mp4
