### ISSUE TITLE
Brave News Settings header disappears after loading Brave News tab via Home button

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20766]
## Steps to reproduce 

   1.  install Brave `1.37.5` on Android
   2. launch Brave
   3. restart (to pick up Brave News Griffin seed)
   4. tap through onboarding
   5. on a new-tab page, swipe down
   6. tap the blurple `Show Brave News` button
   7. notice you have a `Brave News` header with `Settings` icon
   8. tap on any article
   9. now, tap on the 🏠 button on the bottom toolbar
   10. look for the `Brave News` header with `Settings` icon

## Actual result 

It's gone (out of scope for the document type?  caching issue?)

https://user-images.githubusercontent.com/387249/151504097-bafaa6b2-778e-410c-89bb-3b11dd2836f7.mp4

## Expected result

Should remain or at least be repainted/redrawn.

## Issue reproduces how often 

100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

`1.37.5, Chromium 98.0.4758.74`

cc @alexsafe @mattmcalister @srirambv

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.37.18, Chromium 98.0.4758.87` using `Google Pixel XL` (`arm64`) on `Android 9.0`.

Followed my original steps to reproduce, and confirmed the `Brave News` heading/toolbar re-appears dynamically.


https://user-images.githubusercontent.com/387249/152067702-73d2f1af-9880-4980-93f0-43798092669e.mp4

**Comment by srirambv** [comment]
Removing QA label as this is being uplifted and needs to be re-tested on the beta channel

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.
