### ISSUE TITLE
Disable and Re-enable News doesn't show the feed immediately

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20772]
## Description 
Disable and Re-enable News doesn't show the feed immediately

## Steps to reproduce 

   1. Enable news flag 
   2. Open a new tab and opt-in
   3. Tap on news settings and disable Brave News
   4. On same tab open menu and select Brave News and re-enable it
   5. Feed doesn't load instantly. Takes a while causing it to look that feed doesn't work on the tab
   6. If a new tab is opened immediately after re-enabling news feed is shown instantly 

## Actual result 
Disable and Re-enable News doesn't show the feed immediately

## Expected result
Similar to iOS should be shown instantly or at least show loading spinner so that there is some sort of UI feedback that its being loaded

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:11
   
## Brave version
1.36.77

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @mattmcalister

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by Uni-verse** [comment]
Verification completed on release branch `1.36.105, Chromium 99.0.4844.45`
**PASSED** on `Samsung Galaxy S21` | `Android 12` | `ARM`

- [ ] Disabling and Re-enabling Brave News from settings show feed immediately on same tab
- [ ] Load Content button shows up when changing sources
- [ ] Brave News toolbar when scrolling brave news
