### ISSUE TITLE
Add summary

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#20779]
See https://github.com/brave/internal/issues/847

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.86 Chromium: 99.0.4844.51 (Official Build) beta (64-bit) 
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Ubuntu 18.04 LTS

Verified in https://github.com/brave/internal/issues/847#issuecomment-1064612985
