### ISSUE TITLE
Update without restarting

### ISSUE THREAD

**Issue by leobel96** [brave/brave-browser#20778]
I usually update the browser just before switching off the PC and, so, I don't need the browser to restart once the update is finished. I keep a lot of tabs open so it takes a while to restart and refresh all of them and, sometimes, it uses all my RAM freezing the system for some seconds. Have an option to update the browser without restarting would be amazing.

**Comment by srirambv** [comment]
> I don't need the browser to restart once the update is finished.

Changes only reflect when browser is restarted. It doesn't auto-restart when updates are downloaded. If the updates are a week old you get an `Update` message on the menu. So when you switch off your PC and restart its applying the updates as its considered as a browser restart. 

Closing the issue as wortfix as the current behaviour is expected.
