### ISSUE TITLE
News feed repeats after a few scroll

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20773]
## Description 
News feed repeats after a few scrolls

## Steps to reproduce 

   1. Enable News and opt-in
   2. Scroll down news feed
   3. After a while the same feed starts to repeat

## Actual result 

https://user-images.githubusercontent.com/17010094/151540765-4564b3cd-a659-4157-9a40-407ba860232e.mp4

## Expected result
Should not repeat feed 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.36.73

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @mattmcalister

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.104 x64 beta build
- Verified steps from issue description
- Verified news feed doesn't repeat after a few scrolls
- Verified no lag in scrolling through the news feed
-----------
Verification passed on Oppo Reno 5 with Android 12 running 1.36.104 x64 beta build
- Verified steps from issue description
- Verified news feed doesn't repeat after a few scrolls
- Verified no lag in scrolling through the news feed
