### ISSUE TITLE
Brave News settings bar is shown on other tabs when open via tab tray

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20771]
## Description 
Brave News settings bar is shown on other tabs when open via tab tray

## Possible Steps to reproduce 

   1. Enable News flag on beta
   2. Open a new tab and opt-in to News
   3. Open a few tabs and visit pages (not from news)
   4. Open a few more new tabs (5) and scroll down news feed
   5. On 5th new tab open news settings from brave news bar and disable a source
   6. Verify you get the load new content message
   7. Click load new content to refresh the feed
   8. Open tab tray and open a page where you have  a site loaded
   9. Brave news setting bar is shown on tab. Swipe to switch tabs, settings bar is removed once you hit new tab page

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/151537757-3f84add5-6a90-4b7d-9f61-51b7ae1166b9.png>

## Expected result
Only show news bar when on NTP and scrolled down the feed

## Issue reproduces how often 
Intermittent. steps mentioned may not be accurate. I just ran into the issue when I did those steps so needs investigation

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Maybe

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.36.75

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @mattmcalister

**Comment by srirambv** [comment]
Possibly related to #20768

**Comment by srirambv** [comment]
This is still not fixed. Adding a follow up issue for this one

**Comment by srirambv** [comment]
Marking QA/No as this is superseded by #21164

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.
