### ISSUE TITLE
[Follow up to #18534] MM importer is shown even when MM wallet is not created

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20799]
## Description 

MM importer is shown even when MM wallet is not created

## Steps to Reproduce

   1. Clean profile and open Brave Rewards page
   2. Install MM from webstore, Only install do not create wallet
   3. Open Brave wallet, shows MM importer

## Actual result:

https://user-images.githubusercontent.com/17010094/151819237-d53bb2a2-c0fb-4d1b-bb04-40ce71aaec68.mov

## Expected result:
Should only show importer if wallet is created

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.35.98 Chromium: 98.0.4758.74 (Official Build) (64-bit)
-- | --
Revision | `d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}`
OS | All

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes when 1.35.x will be released which has the fix
- Can you reproduce this issue with the beta channel? Yes 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @darkdh

**Comment by darkdh** [comment]
```
handler.on(WalletPageActions.checkWalletsToImport.getType(), async (store) => {
  const braveWalletService = getWalletPageApiProxy().braveWalletService
  const cwResult =
    await braveWalletService.isExternalWalletInitialized(
      BraveWallet.ExternalWalletType.CryptoWallets)
  const mmResult =
    await braveWalletService.isExternalWalletInitialized(
      BraveWallet.ExternalWalletType.MetaMask)
  store.dispatch(WalletPageActions.setCryptoWalletsInstalled(cwResult.initialized))
  store.dispatch(WalletActions.setMetaMaskInstalled(mmResult.initialized))
})
```
mmResult from c++ has a false initialized value but somehow UI still display the button

**Comment by Uni-verse** [comment]
Verification completed using

```
Brave	1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64) 
Revision	5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS	macOS Version 12.1 (Build 21C52)
```

- MM importer not shown when MM wallet does not exist, only installed.
