### ISSUE TITLE
Estimated earning is not fully reset to 0 when the next month roll over happens

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20795]
## Description 
Estimated earning is not fully reset to 0 when the next month roll over happens

## Steps to reproduce 

   1. Clean install with date set to 31st Jan
   2. Enable Rewards and view NTP ads
   3. View an ad notification
   4. Verify rewards page shows total ads view as 5 and estimated earning of 0.025 ( 4 NTP SI x 0.005 = 0.020 + 1 Ad notification * 0.005 = 0.005)
   5. Quit browser and set day/time to 31st Jan 11.59 PM
   6. Restart the browser and wait till it gets past to Feb 1st 12.00 AM
   7. Reload rewards page, Ads viewed this month is reset to 0 but estimated ads earnings is not reset to 0

## Actual result 
Tried a few times and repro'd it consistently. In one of the attempt it reduced only the ad earning so value remained 0.020 and in other instance it remained 0.005

## Expected result
Should reset to 0 similar to desktop

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes when 1.35.x is released
- Can you reproduce this issue with the current Play Store Beta version? Not checked
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.35.98

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/ads-dev @brave/legacy_qa

**Comment by tmancey** [comment]
@srirambv this is working as expected because you have unreconciled transactions from previous months. See the transactions database table. Cash in your tokens before changing the date time to the next month

cc @GeetaSarvadnya

**Comment by tmancey** [comment]
We carry over unreconciled transactions. Thanks

**Comment by tmancey** [comment]
@srirambv closing issue, see above. Any questions please let me know. Thanks

**Comment by srirambv** [comment]
Thanks for the clarification @tmancey  👍
