### ISSUE TITLE
[Feature] Adding Master password for saved password to improve safety.

### ISSUE THREAD

**Issue by HediMuhamad** [brave/brave-browser#20794]
## Description 
[Feature] Adding Master password for saved password to improve safety.

## Steps to Reproduce
   1. Visit these sites that their password saved.
   2. Click input box.
   
## Actual result:
The dotted saved password will appear and others can use it.
NOTE: Others can't see the password if the input box doesn't have *show* button, but the password can be used easily every time.

## Expected result:
Brave request for Master password to use saved password
NOTE: The Master password should require at first trying to use saved password in every Brave startup, not in every websites.

## Desktop Brave version:
**Brave:** 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)
**Revision:** d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
**OS:** Windows 10 Version 20H2 (Build 19042.1466)

## Android Device details:
   - **Install type:** *(ARM, x64)*: arm64-v8a
   - **Device type:** *Phone*: Mi 9T Pro
   - **Android version:** 11 RKQ1.200826.002

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:
Issue Briefly: The Others can access the PC owner's accounts without permission when the PC owner only allows someone else to use the PC.

**Comment by fmarier** [comment]
See https://github.com/brave/brave-browser/issues/13350.
