### ISSUE TITLE
Possible display bug on recovery phrase screen

### ISSUE THREAD

**Issue by coltxyz** [brave/brave-browser#20796]
## Description 
When setting up a new Brave wallet on osx 12.1, the recovery phase shows duplicate words and numberings indicating a possible bug.

## Steps to Reproduce

   1. Initiate brave wallet onboarding
   2. View recovery phrase screen (brave://wallet/crypto/onboarding)
   3. Observe that there should be 12 unique recovery phrases

## Actual result:

There are 11 unique recovery phases with items #1 and #5 both numbered as #1
<img width="1312" alt="Screen Shot 2022-01-31 at 7 54 43 AM" src="https://user-images.githubusercontent.com/1873024/151797836-07cfd38d-bbd9-4469-8840-2375734ce6ae.png">

## Expected result:
There should be 12 unique recovery phrases

## Reproduces how often: 
Happened on initial setup but did not reoccur after resetting wallet and setting up a second time

## Brave version (brave://version info)

Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (arm64)
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | macOS Version 12.1 (Build 21C52)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Douglashdaniel** [comment]
This was addressed in https://github.com/brave/brave-browser/issues/19813
Landed in 1.35.x so should be in release now! 🙂

**Comment by srirambv** [comment]
Closing based on https://github.com/brave/brave-browser/issues/20796#issuecomment-1030286492. Personally haven't hit this one in the last release while testing. Can reopen the issue if it gets reported again or if I run into it while testing.
