### ISSUE TITLE
In page translation for content

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#208]
Similar to what is offered in Chrome:
![screen shot 2018-05-17 at 1 56 32 pm](https://user-images.githubusercontent.com/4733304/40203487-3980fa0a-59da-11e8-9b4c-41640e94c1d8.png)

- foreign language detected
- small message box shown asking if user would like translation
- button remains in place in URL bar (in case message box is dismissed)

Per https://github.com/brave/brave-browser/issues/237, you should also be able to trigger this process by right clicking on the page and pick `Translate` from the context menu

**Comment by Naigel56** [comment]
I want to strongly back this addition. How many of us nowadays are living/working abroad for extensive periods of time? It's really hard to read any non-english local business website (or "non-your-native-language") without any kind of translate plugin. Not to mention the possibility to read some foreign language articles, having an invaluable help while learning a foreign language, and so on.

I like Brave browser but personally this single missing feature is what refrain me from completely dropping Chrome.

**Comment by AvraamMavridis** [comment]
Exactly @Naigel56 

I keep reopening Chrome because I live in Germany and I don't speak the language.
Any time I want to read an email from a german service I have to open Chrome...

**Comment by bsclifton** [comment]
+1 from @srirambv via https://github.com/brave/brave-browser/issues/237
The popup is presented, but when you click `Translate` it presents a `The page could not be translated` message
> ![translate](https://user-images.githubusercontent.com/17010094/40620673-a8eb0efe-6267-11e8-8533-b034ba01e5fe.gif)

**Comment by iMartyn** [comment]
+1 another vote for this, living in a country who's primary language is not my own and the frustrating web devs who believe that location == language.

**Comment by Brave-Matt** [comment]
+1 from Community: https://community.brave.com/t/setting-the-automatic-language-for-web-pages/34400

**Comment by Miyayes** [comment]
+1 from Reddit community: https://www.reddit.com/r/BATProject/comments/9mn632/query_regarding_language_translation_on_brave/

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/right-click-translate-to-english-does-not-work/35663?u=eljuno

>Version 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
>English interface
>Windows 10 Pro English v1803

Right click > Translate to _language_ not working > Nothing happens

**Comment by sadiqevani** [comment]
+1 this would be awesome to have!

**Comment by cbatub** [comment]
+1 please guys please please please fix it, fix it and Brave is close to perfect.

**Comment by NejcZdovc** [comment]
cc @mandar-brave @davidtemkin @bbondy  for prioritisation

**Comment by ArisAmp** [comment]
+1 Right click -> Translate is a plugin to take the browser to the next level

**Comment by juanguren** [comment]
Hey guys, what´s the current status on this plugin/option?

**Comment by marintoo** [comment]
+1
Nothing happens when I click on translate

**Comment by ArisAmp** [comment]
> +1
> Nothing happens when I click on translate

You need to download and crack mate translate. After install it you can use its plugin to translate pages in Brave Browser

**Comment by dwinnert** [comment]
> > +1
> > Nothing happens when I click on translate
> 
> You need to download and crack mate translate. After install it you can use its plugin to translate pages in Brave Browser

Mate Translate does not work well. Many pages I go to Mate will only translate menus and not the body. Highlighting text and translate sucks.  

Firefox also has the same issue as Brave in not having a native translator. I use this is Firefox and it works great. Maybe it could be ported over.....

https://github.com/andreicristianpetcu/google_translate_this

**Comment by hex0cter** [comment]
+1

**Comment by 2635599** [comment]
"I want to strongly back this addition. How many of us nowadays are living/working abroad for extensive periods of time? It's really hard to read any non-english local business website (or "non-your-native-language") without any kind of translate plugin. Not to mention the possibility to read some foreign language articles, having an invaluable help while learning a foreign language, and so on.

I like Brave browser but personally this single missing feature is what refrain me from completely dropping Chrome"

yes the builtin translate featire needs to be added back in. there was no real reason to remove it. brave is fast, responsive, crisp and clean looking, but make no mistake it has faults. the above being one, adding your would ad blocker without anyway to universally turn it off, adding rewards without a way to completely turn it off. the last two as far as i'm concerned are uncompleted features added.

**Comment by steferr** [comment]
+1

**Comment by megalithic** [comment]
i find myself needing this more and more..

`+1`

**Comment by hex0cter** [comment]
Please enable this feature!

**Comment by StefanTod** [comment]
I live in the Netherlands and as a non-dutch speaker I use this feature a lot. I switched to Brave yesterday and none of the pages I try to translate work. I don't get the pop up on in the navigation bar asking me to translate it.

Maybe this is related to Chromium missing API keys for communication with the google translate API's.
+1

**Comment by tomlowenthal** [comment]
Hello everyone. If you want this feature without having to wait, you can install the Google Translate extensions from the Chrome Webstore. That should give you essentially the same functionality as Chrome in the short term.

For those wondering why we haven't just implemented this: Chrome's implementation isn't that privacy-friendly. It effectively involves sending every page you visit to Google so that Google can tell you whether it's in another language and can be translated. Obviously, we're not doing that. So we have a bit more work to do to implement this from scratch.

**Comment by 2635599** [comment]
tomlowenthal AhHaHaHahAhAhAhAhAhAhAhA TRY AGAIN

**Comment by 2635599** [comment]
tomlowenthal AhHaHaHaHaHaHaHaHaHaHa TRY AGAIN

**Comment by bbondy** [comment]
I think it'd be perfectly fine to do this if we make the UI say that the strings on the page, if submitted, would be sent up for translation.  We'll discuss more internally. 
Reason we haven't done it yet is more because we have had other things head of it. I agree this needs to be prioritized though.

**Comment by j26w** [comment]
+1. Really looking forward to this feature! This would be the final piece of the puzzle for me to move 100% over to Brave for web browsing.

**Comment by rafael-acioli15** [comment]
![screenshot from 2019-02-09 17-35-43](https://user-images.githubusercontent.com/25211399/52526034-9436a500-2c91-11e9-8629-434cf9924db8.png)

The extension google translate, allow translate pages, just put in the toolbar and click in the option 'Translate this page'. But few pages not is possible translate, but i can translate many pages with this extension in brave browser. I hope have helped.

**Comment by N4rsha** [comment]
+1

**Comment by bsclifton** [comment]
One of our devs, @yrliou, is checking this out now 😄

**Comment by jimmi-joensson** [comment]
@bsclifton Do you have a time schedule for the in page translation by now? I'm from Denmark and living abroad in Latvia, so this feature is really a most for me before I can migrate to Brave.

**Comment by FelikZ** [comment]
I have similar situation!

**Comment by pfuhrmann** [comment]
Just switched back to Chrome (sadly) because of this feature missing. Let's hope this will be implemented soon so I can come back.

**Comment by sieunhando** [comment]
I have this error too. The translation right click is not work.

**Comment by dijonkitchen** [comment]
FYI, the Google Translate extension still works on Brave: https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb/related

**Comment by pfuhrmann** [comment]
@dijonkitchen extension was mentioned here several times, however, it is by no means replacement to built in translations system.

For once, you have to be translating every single page as you are navigating and it does not remember which sites you requested to translate when you visit next time.

There were some good points mentioned by Brave devs about how Google Chrome is sending API requests to detect whether a page is in other languages than English. I do not care for that, I just need feature when I rick-click and select `Translate to English`, it will translate a page. No need for detection of languages. And this way privacy-concerned user can decide when to send the request to Google Translate API.

**Comment by hex0cter** [comment]
Agree with @pfuhrmann that the extension is no way to replace the built-in feature.
  
Chrome allows language based translation. Therefore users can disable translation of certain languages.  It would be even greater if Brave can provide site based translation, just for the security and privacy's sake. 

Just an idea.

**Comment by bsclifton** [comment]
@yrliou is making great progress with this, last I checked 😄 We have a backend component which will proxy requests, preserving your anonymity.  You can view that in detail here:
https://github.com/brave/go-translate

**Comment by FelikZ** [comment]
@bsclifton thank for sharing
@yrliou that is awesome, thank you for your work. How do you plan to avoid google translate rate limit? AFAI Understand it will run on brave server IPs.

**Comment by fernandosouza** [comment]
It's working on Nightly version. Thank you, guys.

**Comment by manishmaharjan** [comment]
@yrliou , do you have any timeline when this feature would be available in the official release? thanks

**Comment by bbondy** [comment]
You can check the version on this issue in the milestone section: 0.65.x

Then cross reference against our release schedule here: 
https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule

wich gives:
June 4, 2019

You can download a newer build though to try it out today: 
Dev channel: https://brave.com/download-dev/ (should get this version within a day if it's not there already)
Nightly channel: https://brave.com/download-nightly/

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.98 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2006

**Comment by manishmaharjan** [comment]
@yrliou , It seems likes after  v0.65.118 update, "Translate to English" option is not even available during right clicking in non-english web pages. It was working fine until beta release but seems like something went wrong with this release.

**Comment by yrliou** [comment]
@manishmaharjan We disabled the translation service in release channel (which the latest version of it is v0.65.118) for now due to cost performance. In the mean time, you might want to grab and use Beta, Dev, or Nightly for now if you want to use the translation service.

**Comment by manishmaharjan** [comment]
@yrliou , That sounds like the biggest deal breaker. Was waiting more than 2 months for this feature to be released and very sad to hear that the most anticipated feature has been now disabled. Do you have an estimated time frame when this would be released in a stable version? 

Also, When you referred as due to cost performance, do you mean google translate rate limit? If yes, how is it being planned further to integrate?

**Comment by rebron** [comment]
@manishmaharjan I don't have a timeline for you on the translation service hitting release channel. 

As @yrliou mentioned, you can try the feature in the Beta channel which is the most like release channel. Alternatively, translation extensions are available for Brave in the Chrome Web store.   

We're currently using Microsoft Translate for this service as you'll see in Beta/Dev/Nightly channels. We'd love your feedback on the feature in Beta channel though.

**Comment by pfuhrmann** [comment]
@rebron what I do not understand is that it was mentioned that cost performance is not good. How is that going to be mitigated in the future releases? Can we expect this feature ever hit stable channel?

**Comment by rebron** [comment]
@pfuhrmann We're actively working with and evaluating translation providers to come up with a relationship that will get costs structured in a way that makes sense. Yes, the goal is to get this feature out to release channel.

**Comment by serpro69** [comment]
Thank you for working on releasing it! For some reason the google translate extension is not working for me on Brave, so really looking forward to getting this functionality built-in

**Comment by odmera** [comment]
Thank,  enable this feature!
+1

**Comment by pfuhrmann** [comment]
@rebron I would be happy to give micro portions of BAT for each translation or on a monthly basis to support this feature. Completely understand that what you guys are creating is open-source and free.

**Comment by alirezaghey** [comment]
Just wanted to add my 2 cents about how important this feature is. Cheer!

**Comment by manishmaharjan** [comment]
@bsclifton @yrliou @rebron 
I wonder if this ticket should still be in open state? 
Do you guys happen to have any status update so far with respect to translation providers and releasing this feature? Lots of people would really appreciate if the great work that has been done so far could be enabled in the release channel. :) 
Thanks!

**Comment by bsclifton** [comment]
@manishmaharjan good call- I'll re-open as this is not enabled for our release channel

We're still working through the provider part - @rebron would you be able to give an update?

**Comment by danielb2** [comment]
Seems like a workaround is to do:

https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=YOUR_URL_HERE

**Comment by mserajnik** [comment]
> Seems like a workaround is to do:
> 
> https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=YOUR_URL_HERE

That does work, although it's causing issues in some cases. E.g., when you want to use a password manager with browser integration. Since the domain will then be `translate.google.com` (and not the actual website domain), you can't autofill the credentials to log in (unless you add `translate.google.com` to the domain list in the manager, which will get tedious to select from when you have multiple sites).

I know, that's a first world problem, but still pretty annoying.

I imagine it will also cause issues for browser extensions/user scripts that are meant to access/enhance/modify specific sites for the same reason.

**Comment by danielb2** [comment]
btw, also to make it easier it's possible to use this together with the search engine manager: chrome://settings/searchEngines?search=search

**Comment by manishmaharjan** [comment]
@rebron, Has there been any phenomenal progress with respect to translation providers for this feature?  We would highly appreciate if you could provide us some update? Thank you :)

**Comment by git10135405** [comment]
The translation of the webpage into the language you want, this comfortable user experience can not be overemphasized, I also very much hope that it will soon be used in the brave. thank you very much!

**Comment by sepehr** [comment]
> _"I would be happy to give micro portions of BAT for each translation or on a monthly basis to support this feature."_

I happily second this.

**Comment by wout** [comment]
Today I updated Brave and saw this feature appear. I am not happy about it. Is there a way to disable this pop-up?

![image](https://user-images.githubusercontent.com/107324/66188673-2d368800-e688-11e9-896e-1947583e9d6e.png)

I never want to translate a page and I do not want to install the extension. But the pop-up appears every time I visit a page that is not in English. Even every time I visit the same page again, which is quite annoying.

**Comment by simrobin** [comment]
@wout just found that you can disable it in the language settings (you need to open `Language` dropdown: 
![disable-translate](https://user-images.githubusercontent.com/10052336/66198543-ec953980-e69c-11e9-999e-9027440b0932.png)

**Comment by 2635599** [comment]
@wout sounds like you have no business going to any site that's not in english. your post is very rude. if i were @simrobin i sure as hell wouldn't help you.

**Comment by wout** [comment]
@simrobin Thank you so much for pointing that out. :tada: I barely noticed the `Language` dropdown.

**Comment by wout** [comment]
@2635599 I live in Europe and regularly visit sites in English, Spanish, Dutch, German and French, all languages I can read very well. If a pop-up appears on every other page you visit, and you can not find how to disable it within a few clicks, you get annoyed.

**Feature request:**
Provide an option to disable the “Install google translate” pop-up. Something similar to: “Never offer to install this plugin”.

**Comment by rickdsanchez** [comment]
I would echo the suggestion by @wout 

The recent update made Brave very non-friendly to people who speak several languages. The pop-up appears every single time even on the pages that one visited before.

Is there any way to disable this pop-up?

**Comment by git10135405** [comment]
The Google Translate plugin was unable to translate the page and reported an error:
Refused to load the script 'https://translate.google.com/translate_a/element.js?cb=TECB_1E07F158C6FA4460B352973E9693B329&client=tee&hl=zh-CN' because it violates the following Content Security Policy directive: "script-src github.githubassets.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by kjozwiak** [comment]
> The Google Translate plugin was unable to translate the page and reported an error

Mind sharing which page you were browsing when you hit the above issue?

**Comment by git10135405** [comment]
> > The Google Translate plugin was unable to translate the page and reported an error
> 
> Mind sharing which page you were browsing when you hit the above issue?

https://github.com/brave/brave-browser/issues/208

**Comment by GiacomoK** [comment]
> I would echo the suggestion by @wout
> 
> The recent update made Brave very non-friendly to people who speak several languages. The pop-up appears every single time even on the pages that one visited before.
> 
> Is there any way to disable this pop-up?
> 
> EDIT: It appears that there is a way to disable it on the per-language basis in the "Language" menu in the "Settings". I wonder if it makes sense to have a global "disable translations" checkbox in that pop-up?

You right, I have the same problem. It is very annoying to have popup message any single page loading.

**Comment by manishmaharjan** [comment]
@rebron, Could you throw us a status update on this feature? Did you guys already find any translation providers for releasing this feature? Thank you :)

**Comment by rebron** [comment]
@manishmaharjan 
Per the original issue https://github.com/brave/brave-browser/issues/208#issue-324183494 we are matching Chrome behavior by offering the Google Translate extension to achieve translation parity though we will continue to evaluate translation partners. We did implement this feature sans extension with Microsoft translation services in Nightly/Dev/Beta but weren't able to proceed with them as a service provider. 

We can probably close this one out and create a new one when we do move to different translation provider or model for providing the translation service.

We're also updating the dialog so users have a clearer way to don't show the dialog again. That's captured here: https://github.com/brave/brave-browser/issues/6340

**Comment by manishmaharjan** [comment]
@rebron , Thanks for providing some updates. Since this feature was never released in my opinion closing this issue doesn't sound like a good idea as an almost complete feature has already been implemented based on this issue. 

Please also note that using google translation plugin would not be a viable solution as using as core functionality. For instance, in the mobile device it is still not able to provide translation features. 

Since it has been more than a year, how likely brave would find translation provider? What is the biggest bottleneck on having Google/Microsoft as a translation provider? Is it a cost or something else is blocking from having them as a translation partner?

**Comment by pfuhrmann** [comment]
Honestly, watching this issue over the past year, there is a minuscule chance that they will ever find a suitable provider. I commented on the same already back in June.

See my comments above about possible solutions with microtransactions that didn't receive any response from the developers. Brave is great browser and I wish I could use it, but sadly, this is a dealbreaker for me and for many others.

**Comment by ultrasound1372** [comment]
I tried to use the google translation extension but it isn't seeming to work, trying to translate the page https://ux.getuploader.com/foobar2000/ as an example page in Japanese. Trying to translate uploader.jp, just in case the tld mattered, also didn't work. Says it has access, when I click it it pops up a box with an edit field, a translate button, and a translate the page link. Click the link, dismiss the box, nothing happens.

**Comment by w4cky** [comment]
Hey guys, what´s the current status on this options?

**Comment by srirambv** [comment]
@w4cky  translation is available from `0.69.x` onwards. When you visit a page that is not in English you should be prompted to install the translation extension. This was implemented as part of #5561 

@bsclifton we should consider closing this in favour of #5561 ?

**Comment by w4cky** [comment]
@srirambv  Google chrome does it more conveniently because it immediately translates the page in its window.

**Comment by manishmaharjan** [comment]
> @rebron , Thanks for providing some updates. Since this feature was never released in my opinion closing this issue doesn't sound like a good idea as an almost complete feature has already been implemented based on this issue.
> 
> Please also note that using google translation plugin would not be a viable solution as using as core functionality. For instance, in the mobile device it is still not able to provide translation features.
> 
> Since it has been more than a year, how likely brave would find translation provider? What is the biggest bottleneck on having Google/Microsoft as a translation provider? Is it a cost or something else is blocking from having them as a translation partner?

@srirambv

**Comment by rebron** [comment]
Closing since original issue as described was completed with https://github.com/brave/brave-browser/issues/5561 and shipped with 69.x. Please file separate issues for feature enhancements (additional or other translation providers), suggestions, or bugs with the current implementation.

**Comment by manishmaharjan** [comment]
@rebron , that was a complete unprofessional move. You even failed to answer aforementioned question, but instead just decided to close this issue straightly. If brave as a company wants to just close the issue without addressing the core issue first then there might be a lot of question about a **trust**. 

Moreover, awesome work done by @yrliou as part of releasing this feature is also lost.  

Closing this issue means that this might never hit to release version now. There might not have any better ways to track this core underlying issues unless Brave wants to admit that this core feature would not be released to end customer as part of the core feature. 

If Brave have clear intension of releasing this as a core feature then we would highly suggest that please keep this issue in an open state and have some milestone for releasing. This is a major feature that a lot of people are expecting. Hope Brave would decide the right thing. 
Thanks 

CC. @bbondy @bsclifton

**Comment by bsclifton** [comment]
Hi there @manishmaharjan 

- I personally believe the overall feature request in this issue has been addressed 👍 which is why this issue is closed
- You are correct - the solution chosen to address this is NOT a directly comparable experience to what is in Chrome, unfortunately
    - We could have done a better job explaining why we chose this route
    - Chrome translates it in page (which @w4cky mentions is more convenient)
    - The work @yrliou did is great and I would like to see it used too
    - Cost is an issue though, which is why we changed course. These translation calls use a token which charges per-translation call (whether we use Google, Microsoft, or another provider)
    - What @pfuhrmann proposed with micro-transactions (to offset cost) is definitely interesting, but we should capture that overall proposal (ex: being able to chip in on service calls which have a cost using BAT) in it's own issue not related to translations (I can help flag the appropriate folks)
- We can create a new issue to track the request of a directly comparable translate feature. I'm more than happy to create this. However, it's not on our roadmap as a company (at least, at the moment) to implement, because of cost. So while we can have an issue to track it, it would be open perpetually (until something changes).

**Comment by rebron** [comment]
@manishmaharjan Sorry about closing the issue without answering your questions, I think @bsclifton replies answered them though. I closed this issue out because the feature request has been addressed and we're not doing any additional work within this issue, we're not discussing designs, implementation details, or creating prs attached to this issue any longer.

As we've done with other features/feature requests/enhancements, we can create specific and actionable issues that we can better address to move the feature along. Again, sorry for the lack of clarity.

**Comment by ultrasound1372** [comment]
It prompted me to install the extension. I'm fine with that. But I couldn't actually, translate the page. It just stayed in its original language. Is it because I'm using a screen reader?

**Comment by marie228** [comment]
Hi, there are so many posts on this subject, I'm a little lost.
If the option is available with version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit), where can I find it and how to activate it? 
Thanks! ,-)

**Comment by serial02** [comment]
Hello Team @brave-browser-releases 

 There is a prediction when the Brave automatic translator will be working normally. Here in the Linux version it doesn't work as it can be seen in the image below:

https://imgur.com/O95bDXO

![O95bDXO](https://user-images.githubusercontent.com/32621790/75098627-4c7e7500-5597-11ea-9f78-5a960682507a.gif)

**Comment by crogonint** [comment]
Here's your missing translate service. Upvote this:
https://yahoo.uservoice.com/forums/341361-yahoo-homepage/suggestions/40044514-bring-back-babelfish

**Comment by dtantono** [comment]
@serial02 may I know what kind of plugin do you use for translation?

**Comment by grahamperrin** [comment]
### S3.Translator

https://chrome.google.com/webstore/detail/s3translator/debnnjfbneojbmioajinefnflopdohjk

I use it with Firefox – https://addons.mozilla.org/addon/s3_translator/

**Comment by ultrasound1372** [comment]
Will this work on file URLs? I have some local files that need translation that get updated a lot.

**Comment by dtantono** [comment]
yes, I know some of the translations are broken and it will take some time to translate the web page. So, it will be nice if brave have built-in translation features like google chrome or Microsoft Edge.

**Comment by grahamperrin** [comment]
> Will this work on file URLs? …

I don't know, but if you test I'll be interested in the result. 

Bear in mind: translation by Google so I should not make the attempt with anything that's sensitive or confidential. 

Thanks.

**Comment by dtantono** [comment]
@grahamperrin for firefox I strongly recommend this (https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) because I translate the webpage without jumping to other tabs

**Comment by grahamperrin** [comment]
> translate the webpage without jumping to other tabs 

S3.Translator does the same, and more; you can try it at (for example) https://www.s3blog.org/s3gt.html

S3.Translator: 

* forewarns the end user before downloading the executable code
* forewarns before attempting to translating secure (https) content

… and so on. Historically, it was a pick of the month: 

* [November 2013 Featured Add-ons | Mozilla Add-ons Blog](https://blog.mozilla.org/addons/2013/11/01/november-featured-add-ons/)

**Comment by dtantono** [comment]
this addon (https://addons.mozilla.org/addon/s3_translator/) looks ok. But, the main drawback is this popup sometimes occurred in certain sites and this addon ((https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)) does not have this problem which is replicate the same experience as Google Chrome and Microsoft Edge   [
<img width="392" alt="Screenshot_2021-01-28_10-32-50" src="https://user-images.githubusercontent.com/29157187/106077110-448a6600-6154-11eb-9629-fde581313e2d.png">
](url)

**Comment by grahamperrin** [comment]
> … quite annoying …

It's the forewarning that I mentioned in my previous comment. 

Users might not understand the implications. Enhancement request: http://forums.mozillazine.org/viewtopic.php?f=48&t=2829503&p=14884322#p14884322

**Comment by dtantono** [comment]
@grahamperrin if this addon (https://addons.mozilla.org/addon/s3_translator/) have an option/checkboxes to allow the user to translate the HTTPS page to prevent that popup appears. I think that will be a great choice.

**Comment by Ghedeon** [comment]
I'm confused about the status of this issue.
Google Translate extension is installed. There is no translate icon in the address bar and no context action to translate the page.

`Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (x86_64)`

**Comment by crogonint** [comment]
I'm pretty sure that Brave is intentionally NOT supporting Google Spyware in their browser. That's why I recommended the Yahoo (Babelfish) service above. it's open source and reliable.

I have NO IDEA why some developer marked the status of this as closed. I'm pretty sure they haven't fulfilled the service yet.

Unless they did it upstream and didn't tell anybody?? Devs?

**Comment by dtantono** [comment]
@crogonint Apertium (https://www.apertium.org/index.eng.html?dir=eng-epo#translation) is also open source and it is a good option as well

**Comment by bsclifton** [comment]
@crogonint issue was closed because we don't have a way to offer the functionality at the moment. We did explore using Microsoft language APIs and @yrliou got it working- but there is still a significant cost associated with those. Recommending the extension which does translate doesn't have any operating cost for us

On the API side, each call to Google/Microsoft/whoever is translating has a per-transaction cost.  We can potentially open this issue again and mark it as blocked. We'd need help ID'ing a vendor which could help provide this and also not violate the user's privacy (since pages and content will be sent to vendor)

**Comment by manishmaharjan** [comment]
@bsclifton , I do understand you, but those extensions are not always working optimally. Most importantly, to my knowledge there is no any extensions that would be working in **Brave mobile version**. Has there been any plan on how to support translation feature in mobile?

Also, has there been any internal calculation done on how much costs would come towards brave possession on opting for inbuilt translation through some vendors? Has there been also some work done internally in negotiating those costs for the translation service, like volume license, etc. ? This issue has taken indefinitely longer time to resolve fully and still there hasn't been any viable solution towards this most prominent translation problem. if the costs is not too high, then we believe some alternative ways of mitigating the costs should be planned without compromising this vital feature.

**Comment by grahamperrin** [comment]
Posted to Reddit it November 2019: 

* [Bergamot – a project to add and improve client-side machine translation in a web browser – led by University of Edinburgh, in partnership with three other universities and Mozilla : TranslationStudies](https://old.reddit.com/r/TranslationStudies/comments/dtppt3/bergamot_a_project_to_add_and_improve_clientside/)

– this three-year project is funded until the end of 2021. 

https://old.reddit.com/r/TranslationStudies/comments/dtppt3/-/f6y1yq2/ tl;dr 

> … There's so much work in this area, it's difficult to know where to start. …

**Comment by crogonint** [comment]
@rebron Yes, I know. I don't even know why you would pursue cost oriented
solutions. That's WHY I suggested Yahoo / Babelfish above. SURELY, there's
an open source version of that floating around somewhere. It was the first
and the best. It was blowing translations out of the water before Google
had their first micro-cluster talking together coherently. If you hit brick
walls, hit up the Internet Archive people. If anyone has the inside scoop
on old internet tech, it's those guys.
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.

**Comment by zcraber** [comment]
Maybe this possible by relying on open-source machine translation APIs like [Argos Translate](https://github.com/argosopentech/argos-translate) or [LibreTranslate](https://github.com/uav4geo/LibreTranslate).

**Comment by crogonint** [comment]
Now that's bizarre.. I just mentioned this discussion yesterday in a
conversation on the F-droid forums about the need for an open source
solution to replace Google Translate.

You might be interested in checking there, maybe everybody could team up
and get a ball rolling or something. :D
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.

**Comment by Samk19** [comment]
+1 for open source language translation specially on ios and android app where we cannot install the extension 

Please do implement an opensourced language translation feature in your mibile apps

**Comment by git10135405** [comment]
In today’s internationalization, brave-browser should support in-page translation, but GitHub and some websites cannot be translated only with the Google Translate plugin.

**Comment by Samk19** [comment]
Any update regarding translation feature coming to brave mobile app?

**Comment by stephyswe** [comment]
> ### S3.Translator
> https://chrome.google.com/webstore/detail/s3translator/debnnjfbneojbmioajinefnflopdohjk
> 
> I use it with Firefox – https://addons.mozilla.org/addon/s3_translator/

Best solution by far. S3. Can set homepages to be directly translated. It was afew clicks but on each route it translate automatically. Lifesafer!

**Comment by Samk19** [comment]
But not a soln for mobile version of brave as extensions support is not available in ios nor Android

**Comment by dtantono** [comment]
@stephyswe this is much more efficient than S3 https://github.com/FilipePS/Traduzir-paginas-web

**Comment by tachibana-shin** [comment]
Why doesn't Brave use the same API as Vivaldi did?

**Comment by blutch112** [comment]
Maybe something similar to the firefox translations extension that works locally.
[https://addons.mozilla.org/fr/firefox/addon/firefox-translations/](url)
