### ISSUE TITLE
Add fingerprint unlock option while restoring wallet

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#20807]
## Description 
Unable to use fingerprint unlock (Biometric authentication) when the wallet is reset then restored. It is an effect of [clear fingerprint after wallet reset](https://github.com/brave/brave-core/pull/12076) implementation.

## Steps to reproduce 

   1. Setup wallet
   2. Reset wallet from settings
   3. Restore wallet, lock it and notice, there is no option to unlock via fingerprint

## Actual result 
No way to unlock wallet after reset

## Expected result
Allow user to add biomatric authentication on wallet restoration screen

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? not yet, but will after [12076 PR](https://github.com/brave/brave-core/pull/12076)

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: Pie and above
   
## Brave version
1.37.9

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

It is an effect of [clear fingerprint after wallet reset](https://github.com/brave/brave-core/pull/12076) implementation.

### Additional 
Need a change in the restore wallet design or flow to enable biomatric authentication unlock.

cc: @jamesmudgett @SergeyZhukovsky

**Comment by phil-mason** [comment]
@Pavneet-Sing is anyone working on it or is there an ETA?
For me, it is annoying since before the restore, I was used to it.

**Comment by Pavneet-Sing** [comment]
@phil-mason It is not in progress and sorry for the inconvenience. We will escalate to add this soon. Thanks for reporting.

**Comment by Brave-Matt** [comment]
+1 
![image](https://user-images.githubusercontent.com/3299098/221309606-a064112c-f753-40cf-88be-daaca7977a96.png)

**Comment by phil-mason** [comment]
@Pavneet-Sing 
Great, thank you very much for the information :)

**Comment by kjozwiak** [comment]
The above requires `1.50.117` or higher for `1.50.x` verification 👍

**Comment by Pavneet-Sing** [comment]
Update: Using fingerprint to unlock wallet during reset wallet will available soon in the upcoming release https://github.com/brave/brave-core/pull/17875 & https://github.com/brave/brave-core/pull/17911
cc: @phil-mason @Brave-Matt

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.50.120 x64 build

- Verified restoring an account via seed phrase prompts to enable Biometric unlock
- Verified enabling fingerprint unlock works on restoring wallet
- Verified on a restored account in older version, upgrade to 1.52.15 doesn't prompt for fingerprint unlock
- Verified restoring wallet with an already created wallet with fingerprint prompts to enable Biometric unlock
