### ISSUE TITLE
Adblock Element Hiding Issue with Gmail

### ISSUE THREAD

**Issue by Ryan-Goldstein** [brave/brave-browser#20804]
## Description 

An element hiding rule in chrome://adblock is not collapsing the item or hiding the links within Gmail like uBlock Origin does with the same custom filter.

## Steps to Reproduce

1. With Shields Up and `##[href*="blogtrottr.com"]` added to the Custom Filters box at the bottom of brave://adblock, there is a large gap at the bottom in this email within Gmail, along with links that should be hidden: [Doctor Of Credit_ Amazon_ Get $10 Off $50 when Using 1 Discover Point.zip](https://github.com/brave/brave-browser/files/7973221/Doctor.Of.Credit_.Amazon_.Get.10.Off.50.when.Using.1.Discover.Point.zip)
2. Loading the same same email in Gmail with `##[href*="blogtrottr.com"]` added to 'My filters' in uBlock Origin, that box is collapsed and the links are hidden.

## Actual result:
With `##[href*="blogtrottr.com"]` as a Brave custom filter:
![image](https://user-images.githubusercontent.com/8300089/151852190-b1a6720a-8539-4538-ab3d-9dff758b9af1.png)

## Expected result:
With `##[href*="blogtrottr.com"]` as a uBlock Origin custom filter:
![image](https://user-images.githubusercontent.com/8300089/151852395-6845fcb0-cf98-438a-abaa-e9712ed8f06a.png)

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A (the issue is with Brave Shields)
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A (Chrome doesn't have Brave Shields)

## Miscellaneous Information:

I'd be happy to forward the email to anyone's Gmail address so they can reproduce this themselves. I copied the HTML to a separate hosted webpage, but the issue isn't reproduceable there, so it appears to only happen within Gmail.

**Comment by antonok-edm** [comment]
@Ryan-Goldstein I believe this is related to https://github.com/brave/brave-browser/issues/19229, which should no longer be an issue in v1.35+. any chance you could try this out on Beta or Nightly?

**Comment by Ryan-Goldstein** [comment]
Thanks for the quick response. I can confirm that the beta build (Version 1.36.75 Chromium: 98.0.4758.66 (Official Build) beta (64-bit)) does fix this issue. I did try the beta and nightly in my testing before posting this issue, but it's certainly possible I made a mistake, such as not including the proper filter or not reloading the page or similar.

I'll close out this issue. Thanks again!
