### ISSUE TITLE
Hidden Bookmarks bar visible in new tab

### ISSUE THREAD

**Issue by lucas-sg** [brave/brave-browser#20801]
**Description**
The hidden bookmarks bar setting stops working when opening a new tab. This makes loading take longer after having opened a new tab. Plus, if I set the bookmarks bar to be hidden, it should remain that way.

**Steps to Reproduce**

   1. Have sites on your Bookmarks bar.
   2. Set Bookmarks bar to hidden in the settings (Ctrl/Cmd + Shift + B).
   3. Open a new tab.
   4. See that the Bookmarks bar is visible. 
   5. Go to a website in said new tab. It should take longer to load than if the Bookmarks bar was visible, or if it was already hidden in an already opened site and then navigated to a new site.

  
**Actual result:**
Bookmarks bar visible in new tab. Websites taking longer to load from a new tab due to the Bookmarks bar having to appear and disappear.

**Expected result:**
Bookmarks bar hidden as set in settings. Websites taking the same amount of time to load from a new tab with the Bookmarks bar hidden.

**Brave version (brave://version info)**

Brave: 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)
Revision: d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS: macOS Version 12.2 (Build 21D49)

**Comment by rebron** [comment]
Hi @lucas-sg If you go to brave://settings/appearance and toggle off `Always show bookmarks on the new tab page` does that work for you?

**Comment by lucas-sg** [comment]
@rebron yes, thank you! Sorry for the silly issue.
