### ISSUE TITLE
Update "Pending Contributions" line item in Rewards summary

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20819]
## Description

As suggested by design team (@jenn-rhim and @minkyeongshin):

- [ ] Update pending contributions line to be this: `Pending contributions 12.00 BAT 10.00 USD`. It will follow same format as other line items. The "Pending contributions" text itself will be clickable and open up the pending contributions list view.
- [ ] Reorder the pending contributions line item to the bottom of the summary, under Monthly Tips.  

**Existing screenshot of UI for reference:**

![image](https://user-images.githubusercontent.com/11497541/151916923-2a9717db-b251-4d83-8dc8-b0b1662c7a39.png)

**Comment by MadhaviSeelam** [comment]
Verified `Passed` using

Brave | 1.38.75 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 11 Version 21H2 (Build 22000.593)

- Install 1.38.x
- Launch Brave 
- Tip unverified user (cnn.com)
- Open `brave://rewards` and view `Rewards Summary` 
- Verified `Pending contributions` line is moved to last row below `Monthly Tips`
- Verified the update to `Pending contributions` format and it is the same format as others in the summary page - `Pending contributions 17.50 BAT	15.28 USD`
- Verified `Pending contributions` is a clickable link and it opens up the `Pending contributions list view` as this is existing functionality
- Removed all `Pending contributions` and close the view
- `Pending contributions` line is no longer displayed

ex1|ex2|ex3
----|---|---
<img width="950" alt="Rewards summary 138x" src="https://user-images.githubusercontent.com/98358127/161160827-431a7773-72ea-4095-b7d0-a1a911519c2e.png">|<img width="950" alt="pending contributions view" src="https://user-images.githubusercontent.com/98358127/161160836-c233b1bf-7d42-4163-998c-52aa46c266be.png">|<img width="950" alt="removed pending contributions" src="https://user-images.githubusercontent.com/98358127/161161228-1289b06a-bed3-4288-9194-047034c49499.png">

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.38.83

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

Steps:

1. installed `1.38.83`
2. launched Brave 
3. tipped unverified user (`cnn.com`)
4. opened `brave://rewards` and viewed `Rewards Summary` 
5. verified `Pending contributions` line is moved to last row below `Monthly Tips`
6. verified the update to `Pending contributions` format and it is the same format as others in the summary page - `Pending contributions 5.00 BAT	4.00 USD`
7. verified `Pending contributions` is a clickable link and it opens up the `Pending contributions list view` as this is existing functionality
8. removed all `Pending contributions` and closed the view
9. `Pending contributions` line is no longer displayed

example | example | example | example
--------|----------|----------|----------
<img width="1281" alt="Screen Shot 2022-04-07 at 6 33 57 PM" src="https://user-images.githubusercontent.com/387249/162345970-1e34cef7-a0c2-4116-a305-7a1ba3e1ad92.png"> | <img width="1119" alt="Screen Shot 2022-04-07 at 6 34 15 PM" src="https://user-images.githubusercontent.com/387249/162345975-064a7055-8274-4c4e-9b82-232ea37dfe94.png"> | <img width="1119" alt="Screen Shot 2022-04-07 at 6 34 26 PM" src="https://user-images.githubusercontent.com/387249/162345977-a54e3322-dd34-4431-a7cc-6d9fdf20cc1f.png"> | <img width="1235" alt="Screen Shot 2022-04-07 at 6 34 33 PM" src="https://user-images.githubusercontent.com/387249/162345979-a1825c91-7a45-415c-8601-494f4b5bbfe7.png">
