### ISSUE TITLE
Select what to clear on exit

### ISSUE THREAD

**Issue by OpenSourceMovement** [brave/brave-browser#20815]
Hi, I apologize if you get a lot of this but

The Clear Browsing Data on Exit feature on Desktop is really useful. 
Won't it be cool to make it happen on Android too?

Cheers, Nick.

**Comment by bsclifton** [comment]
@OpenSourceMovement it should be available?

When you go to Settings, under `Features` there is `Brave Shields & privacy`.  Pick that and then you'll find a section called `Clear browsing data`. This should do the trick!

Let us know please
cc: @anthonypkeane in case there is a more visible way to show this

**Comment by OpenSourceMovement** [comment]
Right, I also meant there should be an option 
wherein you can pick what data to delete on exit. 

Like this:
![1](https://user-images.githubusercontent.com/98789761/152112044-fbd3e579-df9d-412e-a635-83baf3823a6c.png)
