### ISSUE TITLE
Missing translations for Tips section

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20828]
## Description 
Missing translations for Tips section

## Steps to reproduce 

   1. Sent locale to non-EN US 
   2. Open `brave://rewards`
   3. Scroll down Tips section uses English locale

## Actual result 

<img width=300 src=
![image](https://user-images.githubusercontent.com/17010094/152010937-9b47c5fc-f608-4804-992d-423815389b63.png>

## Expected result
<img width=300 src=https://user-images.githubusercontent.com/17010094/152010906-a8c3de6d-1c23-4e0f-bb8e-fbc646bdc737.png>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes when 1.35.99 is released
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone 
   - Android version:11
   
## Brave version
1.25.99

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Miyayes @mkarolin

**Comment by stephendonner** [comment]
Also an issue with 

Brave | 1.35.99 Chromium: 98.0.4758.87 (Official Build) （x86_64）
-- | --
変更履歴 | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS バージョン11.6.1（ビルド20G224）

Using Japanese as my language:

<img width="1596" alt="スクリーンショット 2022-02-01 午前9 43 44" src="https://user-images.githubusercontent.com/387249/152022230-d132b215-5ade-4f03-9ef3-27d04f381e9a.png">

**Comment by kjozwiak** [comment]
Moving into `1.35.x` as we'll need a new RC that includes https://github.com/brave/brave-browser/issues/20834 either way which was a blocker. So we'll include https://github.com/brave/brave-core/pull/12096.

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/12096 was merged into `1.35.x`.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno5 with Android 11 running 1.35.100 x64 build
- Verified tips section is now fully translated
![image](https://user-images.githubusercontent.com/17010094/152110333-48a8abc6-6948-411b-b75e-9b075c45a8fe.png)
