### ISSUE TITLE
WebUI perf: allow split JS bundles

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#2082]
**_tl,dr_: we can't predict the name / amount of JS files after a webpack build, so let's dynamically build the GRD elements based on webpack's output.**

JS bundles are 1mb+ and contain resources that aren't necessarily needed for the initial view. This is a larger issue for android, but is also an issue for desktop since we want to reduce popup load time to 100ms.

Whilst a large portion of these JS bundles (often 30%-40%) can be removed by moving static fonts to `chrome://resources` (https://github.com/brave/brave-browser/issues/2083), splitting up any further requires dynamic webpack import syntax. This results in an unknown quantity of named `[number].chunk.js` files, which get requested via XHR. To further complicate: Release and Debug builds will generate a different number of these chunk files, often with a different number sequence.

This is an issue since we do not just bundle up an entire directory of files, but instead use grit / GRD files to bundle each named assets for the build, even for extensions.

I propose that we generate part of the GRD at build-time, after webpack has successfully run, based on the actual files that are output in the current build environment.
- Generate a .grdp file for each web-ui run, based on target output directory
- Each generated .grdp file should be generated inside then `gen/` directory structure, and not committed.
- Each generated .grdp will be statically references from a GRD(p) inside the `src/` structure
- Extensions will not need to know the contents of the GRDP file, since the crx will handle serving the assets
- Brave's WebUIDataSource can iterate over the grit-generated .cc output IDs to enable serving under respective `chrome://xyz/abc` path. There are examples of this in chromium code

Risk should be low or comparable to existing build structure since:
- If webpack fails to generate output then the build will fail.
- In the current build process, if webpack outputs unexpected filenames / content, the build will still succeed.

Preliminary work for the android codebase was done in https://github.com/brave/browser-android-tabs/pull/814/commits/8df9185232228134e2c234568da325c012286987 This includes the JS splitting but not the GRDP generation, and cannot be merged as-is whilst it has hard-coded js file names in the GRDP file, since they differ on Release and Debug.

**Comment by petemill** [comment]
cc @bridiver @bbondy in case you want to say "don't generate GRD files at compile time"

**Comment by petemill** [comment]
Note that this is a higher priority for android, which is why I've been working on it now

**Comment by petemill** [comment]
From feedback with @bridiver new plan that I have working is to have generated resources generate their own pak via a generated GRD. Then they can get re-packed with any static resources to the original pak file.

**Comment by srirambv** [comment]
@petemill does this require QA Verification?

**Comment by petemill** [comment]
@srirambv technically no outward changes, so marked as no QA
