### ISSUE TITLE
Only one regional adblock filter list is selected in brave://adblock

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#20825]
Some locales have more than one list, but only one list is selected on clean install

## Steps to Reproduce

1. Clean profile
1. Start Brave in Polish (PL) locale
1. Open `brave://adblock`

## Actual result:

One one list is selected for PL locale even though there are 3
![image](https://user-images.githubusercontent.com/34715963/151995064-2cf47442-75b8-4e2c-bab5-1ee0efbd3b09.png)

## Expected result:
All 3 lists are selected
![image](https://user-images.githubusercontent.com/34715963/151995117-e6f4cc6d-0c17-4b4f-9d8d-b93a5c20adf5.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.35.99 Chromium: 98.0.4758.87 (Official Build) (64-bit) 
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @antonok-edm

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by antonok-edm** [comment]
[All 3 of these lists](https://github.com/brave/adblock-resources/blob/master/filter_lists/regional.json#L332-L364) have `"langs": ["pl"]` in the descriptor, so I suspect the issue is with the in-browser preselection logic.

**Comment by btlechowski** [comment]
Added `OS/Android` as `brave://adblock` is available on Android. Also added `QA/Test-All-Platforms` as each platform may set language differently.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.86 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

#### Confirmed the 3 Polish filter-list options were pre-selected when I set macOS to `Polish` for my language/region

example | example
---------|---------
<img width="1312" alt="Screen Shot 2023-03-12 at 6 37 59 PM" src="https://user-images.githubusercontent.com/387249/224589213-59bcc2c4-cc85-47be-9f23-622a60dc7bbe.png"> | <img width="1312" alt="Zrzut ekranu 2023-03-12 o 18 33 00" src="https://user-images.githubusercontent.com/387249/224589217-b8925161-c464-4876-8df2-b5076fc16288.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

<details>

Verified all 3 filter lists are selected
![image](https://user-images.githubusercontent.com/34715963/226993637-5fe78c92-9877-49af-bd8d-badffa39f761.png)



</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.50.107 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.50.113`

Verified test plan from the description and https://github.com/brave/brave-core/pull/17261

#### Clean profile
<details>

Verified all 3 filter lists are selected
![image](https://user-images.githubusercontent.com/34715963/226993637-5fe78c92-9877-49af-bd8d-badffa39f761.png)



</details>

#### Migration - unchanged
<details>

1.49.x - only one filter list is selected
![image](https://user-images.githubusercontent.com/34715963/226994586-706c5b13-c3c5-4d3b-9242-ffa7122d50bd.png)


Verified all 3 filter lists are selected after upgrade
![image](https://user-images.githubusercontent.com/34715963/226994772-0441c993-2716-4ad5-b44c-587647b031e1.png)



</details>

#### Migration - changed
<details>

1.49.x - only one filter list is selected
![image](https://user-images.githubusercontent.com/34715963/226995478-91e357ac-1652-440e-b631-964379ec7fe2.png)


Verified nothing changed after upgrade
![image](https://user-images.githubusercontent.com/34715963/226996001-f4a33c3d-e14b-4b55-98bd-5832021a075c.png)



</details>
