### ISSUE TITLE
Update description text in Tips component in Rewards settings page to be factually correct regarding tipping buttons and possibilities on Android

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20827]
## Description

Currently, the text in the Tips component in Rewards settings page (1.34.x) makes reference to Reddit, Github, Twitter, etc., as well as inline tipping buttons. These do not exist on Android, so the text should be changed for accuracy. (Android also doesn't support Reddit nor Twitter at this time in general.)

Perhaps get this into 1.35.x hotfix, or 1.36. 

**Screenshot of current text for reference:**

![image](https://user-images.githubusercontent.com/11497541/152037005-29f1cdc1-f6a2-4e91-a975-bc54d26e5abe.png)

Ideally, the text we use should be universal across Android and Desktop. It's better not to have to maintain two separate strings, one for desktop, one for Android. 

## Solution

Approved by Ryan McFadden (Feb 1, 2022): 

`See the one-time tips you've given to websites & creators. Learn more about tipping.`

"Learn more" will link out to the following page: https://support.brave.com/hc/en-us/articles/360021123971-How-do-I-tip-websites-and-Content-Creators-in-Brave-Rewards- 

_This text will be the same across both desktop and Android UIs._

**Comment by rmcfadden3** [comment]
Per Slack convo w/ @Miyayes , let's go with:

"See the one-time tips you've given to websites & creators. <Learn more about tipping.>"

(where "learn more…" links to a help article about how to tip sites & creators)

**Comment by mkarolin** [comment]
@Miyayes, wanted to confirm: should the entire sentence "Learn more about tipping." be a link or just the words "Learn more"?

**Comment by Miyayes** [comment]
@mkarolin second option, let's go with: "Learn more about tipping".

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on 

```

Brave | 1.37.52 Chromium: 98.0.4758.102 (Official Build) nightly (64-bit)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | Windows 10 Version 21H2 (Build 19044.1526)

```
- Verified the description from the issue
![image](https://user-images.githubusercontent.com/38657976/154218325-f2ca7742-9725-40a0-af45-e2a6066a6bdf.png)

- Confirmed click on `Learn more` redirects to https://support.brave.com/hc/en-us/articles/360021123971-How-do-I-tip-websites-and-Content-Creators-in-Brave-Rewards-

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.97 Chromium: 98.0.4758.102 (Official Build) beta (x86_64)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | macOS Version 11.6.3 (Build 20G415)

Steps:
1. new profile
2. loaded `brave://rewards`
3. clicked to enable Brave Rewards
4. scrolled down to the `Tips` section and read the text/checked the link

Confirmed text change
Confirmed linked `Learn more about tipping` text goes to `https://support.brave.com/hc/en-us/articles/360021123971-How-do-I-tip-websites-and-Content-Creators-in-Brave-Rewards-`

light theme | dark theme
------------|------------
<img width="1312" alt="Screen Shot 2022-02-17 at 3 21 26 PM" src="https://user-images.githubusercontent.com/387249/154588536-657d6692-368a-4987-8718-d1c82d3e04c6.png"> | <img width="1312" alt="Screen Shot 2022-02-17 at 3 22 02 PM" src="https://user-images.githubusercontent.com/387249/154588543-49b2207a-9f17-4b7c-a62b-cf9e625a5c59.png">

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.105 x64 build
- Verified Tips section now has <code>See the one-time tips you've given to websites & creators.  <a href=#>Learn more about tipping</a></code>
- Verified `Learn more about tipping` loads `https://support.brave.com/hc/en-us/articles/360021123971-How-do-I-tip-websites-and-Content-Creators-in-Brave-Rewards`

https://user-images.githubusercontent.com/17010094/155659952-e1049a3a-dc82-4d8d-b3f5-a2b854c99b7f.mp4

**Comment by Uni-verse** [comment]
Verification completed using `1.36.105, Chromium 99.0.4844.45`

**PASSED** on `Samsung Galaxy S21` | `Android ARM`  | `Android 12`

Acceptance Criteria:

- [ ] Verified changed text: `See the one-time tips you've given to websites & creators. Learn more about tipping.`
- [ ] Tips Card contains updated description text when navigating to brave://rewards
- [ ] Updated description text when viewing details for Tips card
- [ ] Tips Card - "Learn more" will link out to the following page: https://support.brave.com/hc/en-us/articles/360021123971-How-do-I-tip-websites-and-Content-Creators-in-Brave-Rewards-
- [ ] Tips View Details - "Learn more" will link out to the following page: https://support.brave.com/hc/en-us/articles/360021123971-How-do-I-tip-websites-and-Content-Creators-in-Brave-Rewards-

Tips Card | Details | Learn more link
-|-|- 
<img width="418" alt="Screen Shot 2022-02-25 at 11 09 29 AM" src="https://user-images.githubusercontent.com/17885425/155773789-999bcf21-85f9-4376-b49c-d3b0d12fed20.png"> | <img width="418" alt="Screen Shot 2022-02-25 at 11 09 41 AM" src="https://user-images.githubusercontent.com/17885425/155773800-2b099735-cac9-4908-b9a3-5b995929bffd.png"> | <img width="417" alt="Screen Shot 2022-02-25 at 11 10 03 AM" src="https://user-images.githubusercontent.com/17885425/155773802-0a749be5-c376-4900-93bc-804938053222.png">
