### ISSUE TITLE
Build out Hide Balances Feature in Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20838]
## Description 
Build out Hide Balances Feature in Wallet

![Screen Shot 2022-02-01 at 6 12 41 PM](https://user-images.githubusercontent.com/40611140/152077900-b62073c6-01eb-4149-8143-dd417f42fe7b.png)

**Comment by Uni-verse** [comment]
Verification completed using

```
Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.1 (Build 21C52)
```

- Verified hiding balances on portfolio page
- Hiding balance in portfolio will also apply when opening asset page
- Verified able to hide balances on asset page

![Screen Shot 2022-03-28 at 11 51 39 AM](https://user-images.githubusercontent.com/17885425/160467392-bfd3e3dd-b5f8-4ef4-9951-5766b674e305.png)
![Screen Shot 2022-03-28 at 11 52 10 AM](https://user-images.githubusercontent.com/17885425/160467398-84eea6e3-791f-4dca-b4fb-a7d209c6b8af.png)
