### ISSUE TITLE
[Android] Wallet state text is different between Rewards settings page and Panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#20830]
## Description 

When KYC'd uphold wallet is connected, uphold UI is different in settings page and BR panel.

## Steps to reproduce 

1. Clean profile 1.35.98
2. Enable staging flags
3. Enable rewards via BR panel
4. Click on Verify wallet and connect existing uphold KYC'd uphold account
5. Open BR panel --> It shows `Wallet Verified` click on it shows the uphold old UI which has 4 options `1. Add funds 2. Withdraw funds 3. Go to my uphold acct 4. Disconnect from brave rewards`
6. Open brave://rewrads -->panel shows `My wallet` click on it shows 2 options `1. Go to my uphold acct 2. Logout from uphold`

## Actual result 
![image (2)](https://user-images.githubusercontent.com/38657976/152014431-1225af64-d4b7-4e13-8980-79567cd4faae.png)

 `My wallet` | `Wallet Verified`
--------------|----------
![image](https://user-images.githubusercontent.com/38657976/152016263-d8b9fd03-e520-438a-bac5-a6fc8c02b44a.png) | ![image](https://user-images.githubusercontent.com/38657976/152016364-86db3b87-4e8f-4614-a32e-d5074174ca5c.png)

^^ Note this screenshot doesn't necessarily contain the right text -- it just shows that the panel and the settings page don't match! 

## Expected result

Uphold UI should be same in both places
## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? not sure

## Device details
   - Install type (ARM, x86): ARM Tablet
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: Samsumg Galaxt Tab A7 version 11
   
## Brave version
1.35.98

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Miyayes @LaurenWags  @deeppandya @srirambv

**Comment by Miyayes** [comment]
In all cases, it should just say "Verified" moving forward. We should remove "Wallet" language, as in https://github.com/brave/brave-browser/issues/19768

**Comment by Miyayes** [comment]
States should say:

Unverified
Verified
Logged out

**Comment by Miyayes** [comment]
I think this might've been resolved with https://github.com/brave/brave-core/pull/13518/files too? @vinodghai

**Comment by Miyayes** [comment]
@deeppandya I think this is done, right?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using `1.48.148`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` running `Android 9`

### Gemini

`brave://rewards` | `Rewards panel`
------------------|-----------------

### Uphold

`brave://rewards` | `Rewards panel`
------------------|-----------------

### bitFlyer

`brave://rewards` | `Rewards panel`
------------------|------------------
