### ISSUE TITLE
Magnet Window Manager

### ISSUE THREAD

**Issue by DevPrestigious** [brave/brave-browser#20839]
Description of the issue:
When using Brave Browser with MacOS and the Magnet https://magnet.crowdcafe.com/
When I use the two, it will say “Can’t Be More Narrow.” I cannot resize my windows easily with Magnet or BetterSnapTool; this is an issue only with Brave Browser. It does not happen in any other applications.

How can this issue be reproduced?**

Download and Install Brave Browser on Mac.
Download and Install Magnet (Window Resize tool) application.
Wait about a day after a fresh install of Brave Browser.
Try to resize a window with the snap tool, and it won’t let you.
Expected result: I should be able to snap my windows like every other Mac application with Magnet.

Brave Version( check About Brave):
Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (arm64)

Additional Information: Attached is a video of what the problem looks like. Sorry, I can’t upload the video since I’m a new user.

(https://drive.google.com/file/d/14lXLdll6byBbEzvEATMFjomRUV_U7IJ2/view?usp=sharing)

What I’ve tried:
Reinstalling the OS, then a clean install of both Brave and Magnet. I’ve tried using other browsers, and I’ve been attempting using Bettersnaptool as well. A magnet alternative.

I have concluded it is a Brave issue. I don’t know how to fix it now or if I can fix it.

**Comment by rebron** [comment]
@DevPrestigious Other browsers work properly like Chrome, Firefox, or Safari? This is Brave specific? Do you have any extensions installed that might be causing the issue?

**Comment by DevPrestigious** [comment]
Thank you so much for your reply!
Yes, other browsers/applications work just fine.
I thought it might be some extension, so after I clean installed the OS and Brave browser, I used brave browser without any extensions or profiles set up. Just to see. And after about a day, it started breaking again. I noticed it would break when I tried to put the browser into a corner.

**Comment by Kociamber** [comment]
I'm experiencing exactly the same behavior with Brave browser and Magnet app. The difference in my case is that I'm using an additional screen with my MacBook - window positioning works more or less fine on the laptop's screen (sizing is off though) and I'm always getting "Can’t Be More Narrow" message while trying to position the window on the external screen.

**Comment by DevPrestigious** [comment]
> I'm experiencing exactly the same behavior with Brave browser and Magnet app. The difference in my case is that I'm using an additional screen with my MacBook - window positioning works more or less fine on the laptop's screen (sizing is off though) and I'm always getting "Can’t Be More Narrow" message while trying to position the window on the external screen.

I'm having the same issue as well while using an external monitor. I'm both happy and sad that I'm not the only one having this issue, I've tried nearly everything to get this working.

**Comment by DevPrestigious** [comment]
Found the solution.
https://rectangleapp.com/

Thank you to a Reddit post I stumbled upon.
https://www.reddit.com/r/mac/comments/rx2zfn/bettersnaptool_and_magnet_not_working_for_google/

It turns out this may have been an exclusively chromium-based and magnet (but with a different window manager) it works fine) problem all along. I'm grateful I finally got it sorted out.

**Comment by DevPrestigious** [comment]
Found the solution.
https://rectangleapp.com/

Thank you to a Reddit post I stumbled upon.
https://www.reddit.com/r/mac/comments/rx2zfn/bettersnaptool_and_magnet_not_working_for_google/

It turns out this may have been an exclusively chromium-based and magnet (but with a different window manager) it works fine) problem all along. I'm grateful I finally got it sorted out.
