### ISSUE TITLE
In Spanish,`I have a sync code` button overlaps the white background on brave://settings/braveSync/setup

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20836]
## Description 

In Spanish,`I have a sync code` button overlaps the white background on brave://settings/braveSync/setup

## Steps to Reproduce

   1. switch system language to Spanish
   2. new profile
   3. launch Brave
   4. open `brave://settings/braveSync/setup`
   5. look at the buttons in relation to the white background

## Actual result:

<img width="1747" alt="Captura de pantalla 2022-02-01 a las 13 07 27" src="https://user-images.githubusercontent.com/387249/152059803-88e47f8a-1491-4a25-8e9e-380b628f4970.png">

## Expected result:

Should probably have the white background be wider, to accommodate the extra length of these buttons

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.35.99 Chromium: 98.0.4758.87 (Official Build) (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

**Comment by AlexeyBarabash** [comment]
Right now this looks as
![image](https://user-images.githubusercontent.com/24739341/211579096-08f6154b-f8d8-409a-b88a-4e7218e979f0.png)

This was fixed by https://github.com/brave/brave-core/pull/14821
