### ISSUE TITLE
Possible race condition when starting IPFS node

### ISSUE THREAD

**Issue by mcamou** [brave/brave-browser#20845]
## Description 

The first time that you click on "Open Using IPFS" you get an error, "Can't load IPFS resources using local node". If you reload the page it works. It looks like a race condition: Brave is not waiting for the IPFS node to finish initializing before trying to load the content.

## Steps to Reproduce

   1. Open a fresh instance of Brave
   2. Go to a page that is backed on IPFS (e.g. https://protocol.ai)
   3. Click on "Open Using IPFS"

## Actual result:

An error page stating "Can't read IPFS resources using local node". If you reload the page it works.

## Expected result:

The page should show up the first time.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Have not tried it
- Can you reproduce this issue with the nightly channel? Have not tried it

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, since Chrome does not have native IPFS support

## Miscellaneous Information:

This might have to do with the size of the IPFS block store (since startup time will depend on the size).

```
$ ipfs --api /ip4/127.0.0.1/tcp/45005 repo stat
NumObjects: 345
RepoSize:   17103248
StorageMax: 1000000000
RepoPath:   /home/mario/.config/BraveSoftware/Brave-Browser/brave_ipfs
Version:    fs-repo@11
```

**Comment by spylogsster** [comment]
Hi @mcamou,
This seems fixed in Nightly, can you please check if possible and let us know if still reproduced, thanks

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
