### ISSUE TITLE
Unable to add Google account on macOS when Brave is set as default browser

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#20848]
## Description 
When Brave is set as the default browser and you attempt to add an internet account - specifically Google. A web view modal should appear allowing you to sign-in. This web view is blank when Brave is set as the default browser, so the user is unable to authenticate.

## Steps to Reproduce

   1. Set Brave as default browser (System Preferences -> General -> Default web browser).
   2. Attempt to add a Google account (System Preferences -> Internet Accounts -> Google).
  
## Actual result:
Blank screen appears with spinning load icon. See attached screenshots.

## Expected result:
Google sign-in screen displays allowing user to authenticate.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | macOS Version 12.2 (Build 21D49)

## Version/Channel Information:
N/A

## Other Additional Information:
Resolves when you set the default browser to Safari.

## Miscellaneous Information:
N/A

![2_blank_modal](https://user-images.githubusercontent.com/28269287/152201582-f5eb0e91-5c23-4954-81c1-8027a2d08fed.png)
![1_internet_accounts](https://user-images.githubusercontent.com/28269287/152201593-591e3fc0-b56d-445f-a249-a52f338dfc0a.png)

**Comment by rebron** [comment]
@ryanbr Any ideas on this one. AOL and Yahoo! works ok.

**Comment by rebron** [comment]
@tfc3000 Can you toggle the first button for this setting brave://settings/socialBlocking for Google logins and see if that's working for you?

**Comment by tfc3000** [comment]
@rebron confirming it's working when that toggle is enabled. Makes sense now. Thanks!

**Comment by therightstuff** [comment]
> @tfc3000 Can you toggle the first button for this setting brave://settings/socialBlocking for Google logins and see if that's working for you?

@rebron i've just hit the same issue, i'm stuck with an open modal (making it impossible to switch to anything but my brave browser, which is default) and nothing's opening in brave itself. i looked at the socialBlocking but everything's enabled, so not sure where to go from here other than to re-install chrome and set it to the default browser just while i try to authenticate my macos account

**Comment by therightstuff** [comment]
@rebron i have good news, my attempt to use chrome has demonstrated that this is *not* an issue with brave, i get exactly the same behavior when chrome is my default browser.

**Comment by therightstuff** [comment]
(for anyone wondering, i'm on an old macbook running big sur 11.7.7)
