### ISSUE TITLE
BRAVE HEATS MY DEVICE

### ISSUE THREAD

**Issue by DrMahad** [brave/brave-browser#20841]
PLEASE USE THE TEMPLATE BELOW TO PROVIDE INFORMATION ABOUT THE ISSUE. 
INSUFFICIENT INFO WILL GET THE ISSUE CLOSED. IT WILL ONLY BE REOPENED AFTER SUFFICIENT INFO IS PROVIDED-->

## Description 

When I installed brave on my device it heats up my device completely, it uses more resources than chrome. I run many heavy programs on my laptop but it run doesn't run a single time but when I install brave on my laptop my laptop's fan start running on full speed.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Hi @XF-AULTER We'll need more information. We can help troubleshoot at https://community.brave.com/ We need more than what you've provided such as your operating system, what version of Brave your running and possibly information from brave://gpu/

In the mean time, if you turn off brave://settings/system Hardware acceleration, it may address some of your issues.
