### ISSUE TITLE
Make Asset Selectable in the Visible Asset Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20857]
## Description 
We should make the Asset Selectable in the Visible Asset Modal and not just the checkbox.

![Screen Shot 2022-02-02 at 5 13 08 PM](https://user-images.githubusercontent.com/40611140/152259600-02538c88-7525-4742-a2a9-a9ff40c44811.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12118>brave/brave-core#12118</a></li>
         <li>Verified able to click on asset item to be added or removed from the list</li>
         <li>Verified searching for an asset and clicking on it either adds it or removes it</li>
         <li>Verified custom tokens can also be added or removed by clicking on the token name</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/153138886-a5c102d2-51cf-474f-bcb0-660c8f8b0404.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153139409-682b71c9-8d08-422e-b799-e7e2515d9986.mov >
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153139689-2fbf83d8-f76e-4563-b4e5-1d30c05268fd.mov>
      </td>
   </tr>
</table>
