### ISSUE TITLE
Settings Icon Needs Dark Theme

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20859]
## Description 
The settings icon for `Advanced Settings` in the `Confirm Transaction` panel needs to be updated for Dark Themes

![Screen Shot 2022-02-02 at 5 44 26 PM](https://user-images.githubusercontent.com/40611140/152262705-47b79782-eadc-4eab-b199-9ed7059a2f3d.png)
![Screen Shot 2022-02-02 at 5 48 33 PM](https://user-images.githubusercontent.com/40611140/152262714-589a6582-1c96-4df5-b345-56d0dc8c0d60.png)

**Comment by Uni-verse** [comment]
Verification completed using

```
1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
--
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
```

- Setting icon is displayed in dark theme
- Settings icon is functional
 
![Screen Shot 2022-03-28 at 11 32 22 AM](https://user-images.githubusercontent.com/17885425/160463922-5f97dd83-82a6-473f-9005-fa84468da359.png)
