### ISSUE TITLE
Apply generic cosmetic filters from brave://adblock even in "Standard" Shields blocking mode

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#20855]
This is actually the original issue reported in https://github.com/brave/brave-browser/issues/19085, which morphed into a _different_ problem because of an update to `https://www.circleci.com` and another report added as a comment...

...anyways, it should be possible to add a `###idname` or `##.classname` rule to the Custom Filters box in brave://adblock, and have that applied regardless of element first-party status even in Standard shields mode. This should also work for regional lists and lists added through custom subscriptions.

**Comment by Uni-verse** [comment]
Verification in Progress for Android ARM
