### ISSUE TITLE
Return all EVM Network Tokens in Portfolio Page

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20854]
## Description 
In preparation for Multi chain support we need to separate `Selected Network` logic from the `Portfolio` page and display all tokens from all networks.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">  1.38.106 Chromium: 101.0.4951.41 (Official Build)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12595>brave/brave-core#12595</a></li>
         <li>Verified tokens from all networks are listed on portfolio</li>
         <li>Verified tokens from all networks are listed when searched on visible assets dialog</li>
         <li>Verified tokens from all networks are listed</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165061737-b43a5dd7-f021-42dd-90bd-6493af6689ca.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165061122-9771c618-98d1-4c74-9cc8-e75201893e98.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165061051-ccd6e16c-498a-4955-8315-2b5de536f3c2.mov>
      </td>
   </tr>
</table>
