### ISSUE TITLE
Crash when closing/opening many Brave News tabs with tab groups disabled

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20850]
## Description 

Crash when closing/opening many Brave News tabs with tab groups disabled

(Found while testing the fix for https://github.com/brave/brave-browser/issues/20769.)

## Steps to reproduce 

1. install `1.37.20` or higher
2. launch Brave
3. tap through onboarding
4. tap on the 3-dots menu on the bottom toolbar
5. tap Settings
6. tap Appearance
7. tap to set Enable Tab Groups to Off
8. tap RELAUNCH NOW
9. swipe down
10. tap to Show Brave News
11. open a bunch of new-tab pages
12. now, tap to close/undo/open new ones
13. repeat steps 11-2 until you crash

## Actual result 

Crashes

https://user-images.githubusercontent.com/387249/152208559-653fc602-c1cd-4989-b4ec-f52f983b8306.mp4

## Expected result

No crash

## Issue reproduces how often 

100%, in time

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

`1.37.20, Chromium 98.0.4758.87`

cc @alexsafe @srirambv @mattmcalister

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.36.99, Chromium 98.0.4758.102` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

Followed my steps to reproduce, and confirmed no crash when rapidly closing 25+ tabs and then opening new ones.

example | example | example | example | example | example
----------|----------|-----------|-----------|-----------|----------
![Screenshot_20220218-160933](https://user-images.githubusercontent.com/387249/154777304-96e08789-23eb-4445-9c05-90b731cc88e1.png) | ![Screenshot_20220218-160951](https://user-images.githubusercontent.com/387249/154777301-71dc4423-2d02-4258-ada9-895fda9d8ec3.png) | ![Screenshot_20220218-161026](https://user-images.githubusercontent.com/387249/154777347-5baafb71-f3af-4bfb-ba1b-8756a3c2f977.png) | ![Screenshot_20220218-161022](https://user-images.githubusercontent.com/387249/154777350-e10fdead-1984-42f5-b87e-bd45b6a1f206.png) | ![Screenshot_20220218-161020](https://user-images.githubusercontent.com/387249/154777351-4fda8663-849a-4033-a419-083212836832.png) | ![Screenshot_20220218-161016](https://user-images.githubusercontent.com/387249/154777352-be446e45-885c-4292-b027-8946ddf5d734.png)
