### ISSUE TITLE
Add missing 't' in 'transmited' in Brave Rewards panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#2085]
**Issue:** Letter 't' is missing from 'transmited'. This is a typographical error. Please see below.

![image](https://user-images.githubusercontent.com/11497541/48293267-41f4a680-e44c-11e8-8759-f8cad32e00b1.png)

Issue should have been captured with https://github.com/brave/brave-browser/issues/1724 (which has been _closed_), but does not seem to be live in 0.56.12 MacOS.

**Comment by kjozwiak** [comment]
@davidtemkin unfortunately it looks like https://github.com/brave/brave-browser/issues/1724 only fixed the spelling mistake on the front page of `brave://rewards` but didn't fix it within `brave://rewards` as pointed mentioned above. @Miyayes suggested we try taking this into the hotfix as it's a pretty silly spelling mistake. We're going to have a lot more eyes on this page once the `muon` -> `b-c` migration occurs.
