### ISSUE TITLE
Report of casting votes on snapshot w/ Ledger

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20864]
https://community.brave.com/t/error-when-trying-to-sign-cast-vote-on-snapshot-org-with-ledger-via-brave-wallet/332945

**Comment by Pharkie** [comment]
Yes, same exact issue. Makes Brave Wallet unusable for me and going back to Metamask 😮‍💨

**Comment by srirambv** [comment]
@spylogsster provided a test plan for this so will be testing it on the beta build

**Comment by srirambv** [comment]
Verification passed as part of https://github.com/brave/brave-browser/issues/18833#issuecomment-1050886299. Confirmed with @spylogsster verification from #18833  is sufficient
