### ISSUE TITLE
User unable to register an ENS domain

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20863]
See here: 
https://community.brave.com/t/bug-unable-to-register-ens-domain/333327

**Comment by bbondy** [comment]
Just registered a new .eth and it worked fine. Closing this.

**Comment by butla** [comment]
I'm having a problem with this.

What I'm doing / what's happening:
- I go on "https://app.ens.domains/name/<domain name>/register".
- open Brave Wallet from the icon next to the address bar -> press "connect"
- I'm now "connected" with https://app.ens.domains
- the ENS page is still telling me that there are no wallets connected

**Comment by rishiraj88** [comment]
Is it working fine now, @butla ?

**Comment by butla** [comment]
@rishiraj88 Yup, looks like it's working now. The site connects with the Brave Wallet.
