### ISSUE TITLE
excluding sites via x sometimes results in one single site having a huge % value

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2086]
## Description 
I tried removing some sites via the x icon in popup which displays the full list of auto contribute sites, and I noticed that sometimes one of my sites gets displayed with a crazy huge percentage.

## Steps to Reproduce

   1. Visit a bunch of non-YouTube sites.
   2. Watch a playlist on YouTube with a bunch of videos (this was primarily to increase the number of sites in my auto contribute table quickly, I currently have almost 100). 
   3. Once you get to almost 100 sites, open brave://rewards (keep playlist running in background)
   4. Open the popup showing all auto-contribute sites
   5. Start deleting some of the sites with 0%

## Actual result:
See that a site shows up at the bottom with a crazy huge percentage value which changes (probably because the playlist is still running in the background)

![screen shot 2018-11-09 at 7 27 23 pm](https://user-images.githubusercontent.com/28145373/48295006-170f5000-e456-11e8-9f6b-0eb6ac071bb9.png)

## Expected result:
No site should have that large of a % value

## Reproduces how often: 
Unsure

## Brave version (brave://version info)

Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? unsure

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
This was also reported on community but with some different steps: 
https://community.brave.com/t/cannot-exclude-website-from-brave-rewards/36708/10

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/9wzd09/brave_rewards_bug/

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/incorrect-attention-percentages-displayed/38300/2

**Comment by ryanml** [comment]
Spent some time today trying to reproduce on master, and was unable. Will give it another shot but if STR can change in any way to help better find the expected result that'd be great

cc: @NejcZdovc

**Comment by LaurenWags** [comment]
@ryanml the only real direction I have is that it seems to be related to upgraded profiles. i.e., you started with 0.55.18 (first release channel build) and enabled rewards, started adding sites to your a-c table, etc. Then you upgraded each time one was available (0.55.20 then 0.55.22, etc). I know I personally encountered this when trying to reproduce https://github.com/brave/brave-browser/issues/1693.

**Comment by GeetaSarvadnya** [comment]
+1 from community

https://community.brave.com/t/duckduckgo-com-4294967295-attention/39770/3

**Comment by da2x** [comment]
The specific number we're seeing here, 4294967295 (0xffffffff), is the maximum you can hold in an **unsigned integer**. Could be caused by setting a value to -1 somewhere 

Does excluding a website change a value somewhere from 1 to 0? If this could be executed twice then it would result in a -1. QA can try double-excluding a site (clicking fast? busy hard drive?) to reproduce the issue.

**Comment by michaelw** [comment]
Same issue, I did not exclude any website at all:
```Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)```

![screen shot 2018-12-26 at 18 39 49](https://user-images.githubusercontent.com/346824/50463243-6d214f80-093f-11e9-9ba3-1f396f5f2f70.png)

**Comment by funwhilelost** [comment]
I'm seeing a similar thing in my Windows 10 installation.  When I start excluding sites from auto-contribute things start to get weird: percentages add up to many 100's of percent.  So I go back to "reset" my auto contribute and then it shows some normal looking values, and a handful and MAXINT at the bottom:

Before reset:
![autocontribute](https://user-images.githubusercontent.com/127476/51716661-7d862200-1ff2-11e9-8c20-e26de1a5d38b.jpg)

After reset:
![reset](https://user-images.githubusercontent.com/127476/51716654-765f1400-1ff2-11e9-9e5e-4608a0392ce7.jpg)

**Comment by mbacchi** [comment]
Saw the same issue on the dev channel build `Version 0.62.11 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)` on Linux.
![screenshot from 2019-02-28 13-13-47](https://user-images.githubusercontent.com/6763301/53595648-0694f980-3b5b-11e9-9064-95f94f730507.png)

**Comment by NejcZdovc** [comment]
closing as stale
