### ISSUE TITLE
Use colored brave talk icon when there already opened tab for brave talk

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#20865]
Like below image, brave talk icon should be colored when browser has tab that loads brave talk at least one.
![Screenshot from 2022-02-03 11-39-10](https://user-images.githubusercontent.com/6786187/152272686-1da93480-4986-4c44-8035-3159a35a5052.png)

If browser doesn't include brave talk tab, icon will not be colored one.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.37.36 Chromium: 98.0.4758.87 (Official Build) nightly (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1466)

### Steps:
1. installed `1.37.36`
2. loaded `brave://flags`
3. set `Enable Sidebar` to `Enabled`
4. clicked `Relaunch`
5. loaded `talk.brave.com` (1), `nbcnews.com`, and `talk.brave.com` (2) in tabs
6. confirmed the `Brave Talk` icon changed to its colored version
7. clicked on the `nbcnews.com` (middle) tab
8. clicked on the `Brave Talk` icon in Sidebar
9. confirmed I cycled to the right, to the `talk.brave.com` (2) tab
10. clicked it again
11. confirmed I cycled back to the left, to the original `talk.brave.com` (1) tab
12. closed both `Brave Talk` tabs
13. confirmed the `Brave Talk` icon went back to gray

step 2 | step 6 | step 9 | step 11 | step 13
-------|---------|--------|---------|---------
![20865-1](https://user-images.githubusercontent.com/387249/153302789-e9b67638-b9a9-4085-ac81-0d6a287e0f47.png) | ![20865-4](https://user-images.githubusercontent.com/387249/153302853-8a495d57-7536-4571-88d8-4728d91e7632.png) | ![20865-5](https://user-images.githubusercontent.com/387249/153303085-bdd741fc-505a-4e45-bb79-cfc90fb97068.png) | ![20865-4](https://user-images.githubusercontent.com/387249/153303147-f79525ff-fef4-45aa-b96e-1e6cdd637736.png) | ![20865-7](https://user-images.githubusercontent.com/387249/153303209-4f9b1e22-0ded-40c8-8e82-ebfe2eda42a9.png)
