### ISSUE TITLE
Add ChainID to the jsonRpcService getBalance Methods

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20873]
## Description 
For multi chain support we will need to get balances for all visible tokens on each network.
Currently it will only return a balance of a token for the current `Selected Network` and is being handled in the backend.

If we could do something similar to what was implemented here https://github.com/brave/brave-core/pull/11791
and allow to pass in a `ChainID` for the `getBalance`, `getERC20TokenBalance` and `getERC721TokenBalance` methods in the `jsonRpcService`.

**Update**: As discussed in slack we’ll modify those chain ids with “solana:” prefix to have no prefix. And then anywhere that asks for chain id we’ll also ask for CoinType.  And for Filecoin we’ll just have chain_id as an empty string. Any API will have two required parameters, CoinType and then ChainId

**Comment by darkdh** [comment]
superseded by https://github.com/brave/brave-browser/issues/21095

**Comment by darkdh** [comment]
reopen because we should be able to get balance for any token regardless of selected networks
