### ISSUE TITLE
Do not round amount values from swap quote

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20872]
Incorrect rounding can result in failure to estimate gas in case the value exceeds account balance. Example below 👇 :

https://user-images.githubusercontent.com/3684187/152383123-6c20c059-cf11-4923-ba73-e36c141524bc.mp4

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12127>brave/brave-core#12127</a></li>
         <li>Verified decimal value isn't rounded off when focus is changed from input field</li>
         <li>Verified the steps for ETH-> BAT and BAT-> ETH</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/153145660-89e1a337-0cf1-4619-95cb-af6502050223.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153147684-db11a5df-5eb8-47cd-a650-e3d38b386c65.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153148777-e2441343-4057-4b9c-8621-a47d4a65787f.mov>
      </td>
   </tr>
</table>
