### ISSUE TITLE
Remove brave://flags entry for Sidebar

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#20876]
## Description 
Currently, the sidebar feature is behind a flag - brave://flags/#sidebar

We're starting to add some good features (recently adding bookmarks, making the Brave Talk link more usable). We can leave sidebar as OFF by default for now

Let's remove the flag so that the feature can start to be discovered. It's visible in the hamburger menu already 😄 
![image](https://user-images.githubusercontent.com/4733304/152421230-47eb9c47-812f-42e3-adae-2c0307468e12.png)

also remove `On click` from show options.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.56 Chromium: 98.0.4758.102 (Official Build) nightly (x86_64)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | macOS Version 11.6.3 (Build 20G415)

Confirmed `Sidebar` is no longer present in `brave://flags`
Confirmed context-menu and `Settings` choices for Sidebar no longer have `On click`
Confirmed options worked

`1.37.45`, `brave://flags` | `1.37.56`, `brave://flags` | 1.37.56, `brave://settings/appearance` | `1.37.56`, `context-menu`
--------|--------|---------|------------
<img width="1168" alt="Screen Shot 2022-02-17 at 4 18 19 PM" src="https://user-images.githubusercontent.com/387249/154594027-258533b5-4a10-4bac-8074-fce3e972972f.png"> | <img width="1281" alt="Screen Shot 2022-02-17 at 4 09 04 PM" src="https://user-images.githubusercontent.com/387249/154593955-b56af19c-10a5-40aa-a3ee-194c029cdcb3.png"> | <img width="1168" alt="Screen Shot 2022-02-17 at 4 19 49 PM" src="https://user-images.githubusercontent.com/387249/154594115-77e89b7e-6294-4b80-b6d4-45652d648eba.png"> | <img width="1166" alt="Screen Shot 2022-02-17 at 4 26 35 PM" src="https://user-images.githubusercontent.com/387249/154594333-f2f7264d-6a0c-4795-8e3d-13af9942825f.png">

**Comment by MadhaviSeelam** [comment]
Brave |	1.37.91 Chromium: 99.0.4844.51 (Official Build) beta (64-bit) 
---|--- 
Revision |	d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS |	Windows 11 Version 21H2 (Build 22000.556)

Verified following;
`#sidebar` flag is not available in `brave://flags`
`Show Sidebar` is available in `hamburger` menu with show options of 'Always', 'On mousoever', 'never'
`On click` is not available in `Show Sidebar` show options
`Show Sidebar Enabled` is available `brave://settings/appearance` with menu options 'Always', 'On mousoever', 'never'
Sidebar options in the context-menu displayed
All `Sidebar` options worked as expected
`Show Sidebar` available in in `hamburger` menu for  `private tor window`
`Show Sidebar` available in in `hamburger` menu for `private window`
`Show Sidebar` available in `hamburger` menu for `guest window`  

ex1|ex2|ex3|ex4|ex5|ex6|ex7|ex8
---|---|---|---|---|---|---|---
<img width="1550" alt="Sidebar_flag_not available" src="https://user-images.githubusercontent.com/98358127/158267433-d5c45ccd-82e1-465c-ab37-0c84cb9440dd.png">|<img width="1550" alt="hamburger menu" src="https://user-images.githubusercontent.com/98358127/158267849-cfa0dc58-c4a3-4036-8e34-9fe6877ba638.png">|<img width="1550" alt="sidebar-mouseover" src="https://user-images.githubusercontent.com/98358127/158267929-99d979aa-c471-4d72-bb92-8c628b7751ff.png">|<img width="1550" alt="sidebar" src="https://user-images.githubusercontent.com/98358127/158268049-acb15634-0207-437e-b99f-538d44f5bd81.png">|<img width="1550" alt="regualarindow" src="https://user-images.githubusercontent.com/98358127/158267627-41a363ae-b318-4ad5-a181-119a1a1475fc.png">|<img width="1550" alt="Tor Window" src="https://user-images.githubusercontent.com/98358127/158268253-fdedba84-30fb-4ab7-babd-775f4fa7e01c.png">|<img width="1550" alt="private window" src="https://user-images.githubusercontent.com/98358127/158268422-2fd8187d-d9a0-40ad-b21d-19991837a2f2.png">|<img width="1550" alt="guestwindow" src="https://user-images.githubusercontent.com/98358127/158268558-b896ce1c-4c1c-402e-a508-fc2d828e0b7d.png">
