### ISSUE TITLE
[Android] Enable Brave News flag by default

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#20875]
1. Open a new profile with Android
- Brave News should be enabled immediately (no wait for restart for griffin flag)

**Comment by kjozwiak** [comment]
Adding missing `1.37.x` milestone as https://github.com/brave/brave-core/pull/11983 was merged into `master` which is `1.37.x` at this point. QA also went through https://github.com/brave/brave-variations/pull/213#issuecomment-1039452200 and removed the `BraveNewsStudy` from Griffin via https://github.com/brave/brave-variations/pull/222.

We'll be uplifting this into `1.36.x` as Brave News is slated for `1.36.x`. CCing @mattmcalister @alexsafe

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by Uni-verse** [comment]
Verification completed on release branch `v.36.105, Chromium 99.0.4844.45`

**PASSED** on `Samsung Galaxy S21` running `Android 12`

- [ ] Brave News should be enabled immediately (no wait for restart for griffin flag)

Startup | Enabled
-|-
![Screen Shot 2022-02-24 at 11 18 57 AM](https://user-images.githubusercontent.com/17885425/155592825-e0a01e47-147a-4512-93e4-6d8ec449022b.png) | ![Screen Shot 2022-02-24 at 11 22 37 AM](https://user-images.githubusercontent.com/17885425/155592835-4c65af86-855b-46fb-b458-2883114f285a.png)
