### ISSUE TITLE
Not getting BAT for new tab page ads

### ISSUE THREAD

**Issue by newuser-web** [brave/brave-browser#20874]
## Description 
Not receiving BAT for new tab page ads. An error is seen in the log file ' Failed to fire new tab page ad'

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): 
   - Device type (Phone, Tablet, Phablet): 
   - Android version: 11
   
## Brave version
1.34.81

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by newuser-web** [comment]
![IMG_20220213_130510](https://user-images.githubusercontent.com/67158882/153743727-c0b15698-719f-458a-b6c1-8894cbb1a7e8.jpg)
These errors are coming all the time. @SergeyZhukovsky @srirambv

**Comment by newuser-web** [comment]
https://community.brave.com/t/no-payout-on-viewing-sponsored-image-for-many-days-errors-in-logs/270851/16

Looks like this problem was previously fixed for Windows. I am viewing it on Android device.

**Comment by newuser-web** [comment]
https://community.brave.com/t/no-payout-on-viewing-sponsored-image-for-many-days-errors-in-logs/270851/16

Looks like this problem was previously fixed for Windows. I am facing it on Android device.

**Comment by tmancey** [comment]
> https://community.brave.com/t/no-payout-on-viewing-sponsored-image-for-many-days-errors-in-logs/270851/17
> 
> Looks like this problem was previously fixed for Windows. I am facing it on Android device.

@newuser-web thanks for sending the info. Can you please visit https://whatismyipaddress.com/ and send a screenshot and also send a screenshot of your system region/locale via email again. Thanks

**Comment by tmancey** [comment]
@newuser-web the reason you are not being paid is because you have your region set to English (United States) and you are based in India. Please change your region to match your location, i.e. English (India). Thank you

**Comment by tmancey** [comment]
Closing issue as working as expected as user is viewing US NTP SI in India. Thanks

**Comment by newuser-web** [comment]
> @newuser-web the reason you are not being paid is because you have your region set to English (United States) and you are based in India. Please change your region to match your location, i.e. English (India). Thank you

My region is already selected as India. You are referring about language section. Please see the screenshot again. Region is India.

**Comment by newuser-web** [comment]
That's not the case. Don't close this issue.

![Screenshot_2022-02-14-22-54-59-01_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/67158882/153915226-005e8161-33f3-40dd-b50f-02ebfd5c5ce7.jpg)

**Comment by newuser-web** [comment]
> At this time we have no NTP SI running in India, if they are shown it would mean the region/locale/ip do not match for india. Thanks

![IMG_20220214_230231](https://user-images.githubusercontent.com/67158882/153916213-273637e1-5463-4a38-b2c2-57f373eea95f.jpg)

Location- IN ( Detected using my IP address)
Also SI ads are available in India.

**Comment by tmancey** [comment]
Ah yes there are some there today, ok can you send me the region settings of this device and the ip address location (screenshots) and I will investigate further. However, before I can investigate the device has to have region set to India and also ip address set to india. And a browser restart. Thanks

**Comment by tmancey** [comment]
This creative is from the US catalog and will not reward users in India. It is likely that this creative was download due to first having English (United States) selected.

Now that you have changed your region to English (India) the next update should remove this US only creative from your device.

**Comment by newuser-web** [comment]
But my region was always selected as India. I only changed my default language.Today it was working. I'll share the details once this issue resurfaces again ( I'm facing it after every 2 days).

**Comment by tmancey** [comment]
We use the default language. And the default language was English (United States). Thanks

**Comment by newuser-web** [comment]
![IMG_20220220_205812](https://user-images.githubusercontent.com/67158882/154850459-3ddd0fb0-2c0d-4d5e-ba2e-f11a4e7e1940.jpg)
I am getting this error after seeing only 5-6 NTP ads in a day. I have mailed you the log file.

**Comment by newuser-web** [comment]
@tmancey I'm getting this error now. It shows this error every day from the beginning of the day. I have not reached the 20 ads limit. It gets resolved for 1-2 hours then again same error occurs. I am facing this issue everyday.
![IMG_20220223_223009](https://user-images.githubusercontent.com/67158882/155369128-3d178e6f-8de9-4e7d-a41a-c0696e9ecc99.jpg)

**Comment by tmancey** [comment]
@newuser-web however many have you seen? This is also based on a rolling 24 hour period.

**Comment by newuser-web** [comment]
It doesn't update everyday at midnight. I see this error in the morning or afternoon, even when I haven't seen any ad in a day. I suddenly start getting rewards around 4 or 5 PM and then for the next 4-5 hours I am getting this error. Not seeing hourly limit error.

**Comment by tmancey** [comment]
I would need to know how many NTP SI you have seen in the last 24 hours, please email terry@brave.com with screenshots of the 30 day ads history for the relevant day. Thanks

**Comment by newuser-web** [comment]
where can i find it? Do I need to download the log file from Rewards Internals?

**Comment by tmancey** [comment]
@newuser-web ads history is not on Android at this time. Please keep an eye to see how many NTP ads you see over the next 24 hours. Thanks
