### ISSUE TITLE
Inconsistent naming of 24-word mnemonic import option 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20885]
## Description 
Inconsistent naming of 24-word mnemonic import option 

## Steps to reproduce 

   1. Import 24-word mnemonic on desktop and Android
   2. Both has different wording. 

## Actual result 

Android | Desktop
-- | --
<img width=800 src="https://user-images.githubusercontent.com/17010094/152507154-52a74b48-9579-4ae4-bb7b-37cfd6cb5dfa.png"> | <img width=500 src=https://user-images.githubusercontent.com/17010094/152507034-cd5e9361-3648-4ec4-a575-2b79bae5b371.png>

## Expected result
Same wording on both

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.36.85 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @jamesmudgett @Pavneet-Sing @Douglashdaniel

**Comment by Pavneet-Sing** [comment]
ATM, The desktop and android designs are different, though discussed with James to implement keep it same as desktop. Will update the design after prioritizing.

**Comment by srirambv** [comment]
Verification  passed on the following devices running 1.37.89 x64 beta build
- Verified 24-word mnemonic import options is now same as desktop

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/157853830-a744b4ed-85a1-41ef-a654-1f7d58bcf347.png> | <img width=350 src=https://user-images.githubusercontent.com/17010094/157853863-8d2cabea-15a9-41f7-b56e-f94282cc248e.png>
