### ISSUE TITLE
Set custom nonce for transactions 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20887]
Android version of #19705

> Allow advanced setting of nonce for transactions. Expose a settings icon on send confirmation panel to set custom nonce.

cc: @SergeyZhukovsky @wchen342 @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
Closing this as this has been resolved by [PR #12584](https://github.com/brave/brave-core/pull/12584)

**Comment by srirambv** [comment]
Verification passed as part of https://github.com/brave/brave-browser/issues/21459#issuecomment-1110889913. Removing Release notes label as this is pretty much same as https://github.com/brave/brave-browser/issues/21459.
