### ISSUE TITLE
ETH fiat amounts are always zero

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20883]
**Affects `1.35.x` only - not reproducible on either `1.34.x` or `1.36.x` (or newer).**

<img width="1440" alt="Screen Shot 2022-02-02 at 2 54 06 PM" src="https://user-images.githubusercontent.com/3684187/152507051-97bf71ac-e4a6-4f76-b7a1-2cb46c2a064d.png">

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/12139 was uplifted into `1.35.x`.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12139>brave/brave-core#12139</a></li>
         <li>Verified fiat prices are no longer 0</li>
         <li>Verified fiat prices are showing in USD (default)</li>
         <li>Verified changing the default base currency to shows the corresponding fiat price value in the new base currency value</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/153160570-faf244cf-ef6d-4fdf-9fde-e878a7331185.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153160694-058a5ed3-aa36-4445-95ba-3b69f6037aad.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/153160831-853cd24b-5437-4349-b7a4-e3f8e4d7f08a.mov>
      </td>
   </tr>
</table>
