### ISSUE TITLE
Browser crash when swap input value is large

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20881]
## Description 
Browser crash when swap input value is large. Found this while testing https://github.com/brave/brave-core/pull/12127

## Steps to reproduce 

   1. Install 1.37.25
   2. Open swap and enter value
   3. Update input value and browser crashes

## Actual result 

https://user-images.githubusercontent.com/17010094/152474436-f8935380-0f7b-4809-957a-a4f5058506c4.mp4

Prod Crash ID: https://share.backtrace.io/api/share/NXkA6RyPex2GQrQIHKLAtp0
Nightly Crash ID: https://share.backtrace.io/api/share/h7r2QdSlMygdM29NMPFZR3

**Note: On prod when it crashes it goes back to Wallet onboarding screen. But when closed and reopened it shows locked screen. This doesn't happen on Nightly though**

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @onyb

**Comment by onyb** [comment]
We merged https://github.com/brave/brave-core/pull/11948 on Desktop to prevent users from entering values that do not comply with the decimals of the related asset (18 in this case). We should have something like that on Android.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.35.101 x64 build
- Verified steps from issue description
- Verified no browser crash when swap input value is large
- Verified Swap button shows `Unknown Error` when input value is large than available balance

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/153130495-b5f76d7b-af6c-43bc-b28d-f788b726c1b4.mp4> | <video src=https://user-images.githubusercontent.com/17010094/153130456-35675426-d99f-405a-871a-c8832873bc06.mp4>
