### ISSUE TITLE
Locally calculated ads earnings and actual BAT received will not match

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#20889]
It is very likely that locally calculated ads earnings and actual BAT received will not match since it takes sometimes few days to cash in unblinded payment tokens. 
The reason is that their timestamps are out of sync.
Client uses ad view timestamp
Server uses cashed in timestamp
It could easily happen that user would view an ad in the first month but cashed it in the next month.
Client would see the earning for the first month
Server would see the earning for the next month

## Steps to Reproduce

1. Clean profile 1.34.x
1. in 1.34.x in January - View an ad but do not cash in the unblinded payment token
1. in 1.34.x in Feb - Cash in the unblinded payment token
1. upgrade to 1.35.x
1. Check `Current earnings this month` and `Ads received this month`

## Actual result:

Client thinks that the transaction is from January (view timestamp)
Server thinks the transaction is from February (cash in timestamp)

Related issue https://github.com/brave/brave-browser/issues/20868

## Expected result:
We need better messaging so we don't confuse users.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.35.100 Chromium: 98.0.4758.87 (Official Build) (64-bit) 
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @tmancey @rebron @jsecretan @iambrianfung

**Comment by tmancey** [comment]
@btlechowski can you please retest this against https://github.com/brave/brave-core/pull/12128, thanks

**Comment by tmancey** [comment]
Maybe can be more descriptive on amounts carried over from previous months:
```
You earnt 20.00 BAT in January, 15.00 BAT will arrive in 6 days and 5.00 BAT will be carried over to this months earnings
Current earnings this month: 5.000
Ads Received this month: 5
```

**Comment by tmancey** [comment]
Closing as stale
