### ISSUE TITLE
Show seed words in red when they are not selected in order

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20886]
Android version of https://github.com/brave/brave-browser/issues/19736

https://github.com/brave/brave-core/pull/11926 is only for Desktop hence logging Android specific issue

**Comment by simoarpe** [comment]
Closing this as we have adopted a different layout.
Figma design link: https://www.figma.com/design/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=6223-70942&m=dev
