### ISSUE TITLE
Reset doesn't clear market value on Swap screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20880]
## Description 

Reset doesn't clear market value on Swap screen. 

## Steps to Reproduce

   1. Install 1.35.25
   2. Select Swap and input value so Market value is loaded automatically
   3. Click on Reset button, All inputs are cleared but market value for the token is not

## Actual result:

https://user-images.githubusercontent.com/17010094/152471346-f7b3b948-17a1-4ef3-a9d1-c704ffd0d98c.mp4

## Expected result:
Should reset all values

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.37.25 Chromium: 98.0.4758.87 (Official Build) nightly (64-bit)
-- | --
Revision | `e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @onyb @muliswilliam

**Comment by Uni-verse** [comment]
Verification completed using

```
1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
--
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
```

- Using `Reset` button will clear the values on swap modal

https://user-images.githubusercontent.com/17885425/160465506-60e1b3f3-012e-45b5-86ea-ab7d629ed3e5.mov
