### ISSUE TITLE
No Tipping Option on YouTube (or Twitch)

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2089]
## Description 
No tipping button is presented while on YouTube and/or Twitch.

## Steps to Reproduce
*From a fresh profile…*
1. Enable Brave Rewards, claim grant.
2. Open https://www.youtube.com/watch?v=Wq-YZJ2CR0I in a tab.
3. Open https://twitch.tv/ninja in a tab.
4. Expand Rewards Panel for both tabs.

## Actual result:
Some panels don't offer a tipping option

## Expected result:
Tipping should be offered on both YouTube and Twitch

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.57.3

### Additional Information

![image](https://user-images.githubusercontent.com/815158/48299077-7e94c200-e48d-11e8-9bf4-08cd77bbae5f.png)

Potentially related to #1814

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/888
* Additional testing notes can be found here https://github.com/brave/brave-browser/issues/1814#issuecomment-462960051
