### ISSUE TITLE
Revert redirect-url feature

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#20892]
## Description 

Revert functionality provided by https://github.com/brave/brave-browser/issues/18542
Given that we don't plan on using redirect-url feature in the near-term, we should remove it to reduce security and bug surface. More details (including QA) in https://github.com/brave/brave-browser/issues/18542. 

@stephendonner

**Comment by stephendonner** [comment]
@ShivanKaul mind helping us with a test plan here?  How does the following look, as a start?

Steps:
1. new profile
2. load `brave://flags`
3. verify no flag in `brave://flags`
4. open Developer Tools | Network panel
5. visit each of the sites listed from https://github.com/brave/brave-browser/issues/18542#issuecomment-966336542

Confirm we don't replace requests (using internal redirects?), and those resources return a `200 OK`.

cc @brave/legacy_qa

**Comment by ShivanKaul** [comment]
@stephendonner I think the QA plan would be reverse of https://github.com/brave/brave-browser/issues/18542#issuecomment-966336542. I can send the DAT file again. What you mentioned in ^ sounds perfect, but given the deployed filter list it would be sufficient to check only the rules on https://raw.githubusercontent.com/brave/adblock-lists/master/brave-lists/brave-sugarcoat.txt i.e. check https://dell.com for `ensighten.com/dell/marketing/code/280f261e277ca609b7450f5304929274.js` and https://live.house.gov for `google-analytics.com/analytics.js`

**Comment by stephendonner** [comment]
@ShivanKaul please do send me the `DAT` file again.

Question: So we're not completely removing this, correct?  (Given you pointed to rules for `dell.com` and `live.house.gov`.)

**Comment by ShivanKaul** [comment]
We are removing it completely - only those two rules are currently being bundled.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.36.106 Chromium: 99.0.4844.45 (Official Build) (64-bit)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | Windows 10 Version 21H2 (Build 19044.1526)

```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.36.107 Chromium: 99.0.4844.45 (Official Build) (x86_64)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | macOS Version 11.6.3 (Build 20G415)

### Case 1: no `adblock-redirect` in `brave://flags`

Steps:
1. installed `1.36.107`
2. launched Brave
3. loaded `brave://flags`
4. typed `adblock-redirect`

Confirmed no match for `adblock-redirect`

<img width="1312" alt="Screen Shot 2022-02-28 at 10 11 04 AM" src="https://user-images.githubusercontent.com/387249/156037548-5b589b3e-da21-4f55-81b9-ba7cc9ca5adf.png">


### Case 2: regression-testing of removal

Steps:
1. installed `1.36.107`
2. launched Brave
3. shut down
4. copied `resources.json` and `rs-ABPFilterParserData.dat` to `/Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser/cffkpbalmllkdoenhmdmpbkajipdjfam/1.0.1228`
5. relaunched Brave
6. clicked on `hamburger` menu, chose `More tools` -> `Developer Tools`
7. clicked on the `Network` pane
8. loaded `reuters.com`
9. loaded `amazon.jobs`
10. loaded `fedex.com`
11. loaded `sky.it`

Confirmed no `async-sugarcoat-{hex}.js` redirects for various ad/tracking resources.

`reuters.com` | `amazon.jobs` | `fedex.com` | `sky.it`
---------------|----------------|-------------|--------
<img width="1312" alt="Screen Shot 2022-02-28 at 10 58 55 AM" src="https://user-images.githubusercontent.com/387249/156045403-91dfd423-8a61-4edc-a76d-b8734a5ab30d.png"> | <img width="1312" alt="Screen Shot 2022-02-28 at 11 03 55 AM" src="https://user-images.githubusercontent.com/387249/156045540-1233e936-bec3-440b-b35b-e92741a97f50.png"> | <img width="1312" alt="Screen Shot 2022-02-28 at 11 06 55 AM" src="https://user-images.githubusercontent.com/387249/156045596-80b06800-5cf7-4d9a-a3d0-91a26fc9d689.png"> | <img width="1430" alt="Screen Shot 2022-02-28 at 11 20 28 AM" src="https://user-images.githubusercontent.com/387249/156045650-70768d36-eb27-426c-b011-df716178c4b8.png">





### Case 3: sugarcoat inline script replacement

Steps:
1. installed `1.36.107`
2. launched Brave
3. shut down
4. copied `resources.json` and `rs-ABPFilterParserData.dat` to `/Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser/cffkpbalmllkdoenhmdmpbkajipdjfam/1.0.1228`
5. relaunched Brave
6. clicked on `hamburger` menu, chose `More tools` -> `Developer Tools`
7. clicked on the `Network` pane
8. loaded `https://shivankaul.com/adblock-redirect-test.html`
12. clicked on `hn.js`
13. clicked on the `Preview` pane

Confirmed inline script replacement

1.36.107 | 1.35.104
---------|---------
<img width="1312" alt="Screen Shot 2022-02-28 at 9 35 26 AM" src="https://user-images.githubusercontent.com/387249/156039470-fafe46b7-0ad5-48cf-ba3a-fdbc01289087.png"> | <img width="1312" alt="Screen Shot 2022-02-28 at 10 45 55 AM" src="https://user-images.githubusercontent.com/387249/156040590-3ee9b55a-f592-4892-9063-62f5097f6e4f.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.107 Chromium: 99.0.4844.45 (Official Build) (64-bit) 
--|--
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | Linux

### Case 1: no `adblock-redirect` in `brave://flags`

Steps:
1. installed `1.36.107`
2. launched Brave
3. loaded `brave://flags`
4. typed `adblock-redirect`

Confirmed no match for `adblock-redirect`

<img width="1595" alt="Screen Shot 2022-02-28 at 4 31 48 PM" src="https://user-images.githubusercontent.com/387249/156085157-f28c2546-f559-43ba-a6f9-aecc9bbba214.png">


### Case 2: regression-testing of removal

Steps:
1. installed `1.36.107`
2. launched Brave
3. shut down
4. copied `resources.json` and `rs-ABPFilterParserData.dat` to `~/.config/BraveSoftware/Brave-Browser/cffkpbalmllkdoenhmdmpbkajipdjfam/1.0.1229`
5. relaunched Brave
6. clicked on `hamburger` menu, chose `More tools` -> `Developer Tools`
7. clicked on the `Network` pane
8. loaded `reuters.com`
9. loaded `amazon.jobs`
10. loaded `fedex.com`
11. loaded `sky.it`

Confirmed no `async-sugarcoat-{hex}.js` redirects for various ad/tracking resources.

`reuters.com` | `amazon.jobs` | `fedex.com` | `sky.it`
---------------|----------------|-------------|--------
<img width="1595" alt="Screen Shot 2022-02-28 at 5 12 53 PM" src="https://user-images.githubusercontent.com/387249/156085933-c6fc3fb8-8b09-4d75-8eab-0749efeded3d.png"> | <img width="1595" alt="Screen Shot 2022-02-28 at 4 55 26 PM" src="https://user-images.githubusercontent.com/387249/156085199-7804cc9a-221a-446e-914e-31ae7c40919d.png"> | <img width="1595" alt="Screen Shot 2022-02-28 at 4 58 19 PM" src="https://user-images.githubusercontent.com/387249/156085206-6661c4ce-94d2-4548-9531-cd9750b5274f.png"> | <img width="1595" alt="Screen Shot 2022-02-28 at 5 00 59 PM" src="https://user-images.githubusercontent.com/387249/156085213-952f833d-3ff6-4818-a4a9-4ef285aad405.png">




### Case 3: sugarcoat inline script replacement

Steps:
1. installed `1.36.107`
2. launched Brave
3. shut down
4. copied `resources.json` and `rs-ABPFilterParserData.dat` to `~/.config/BraveSoftware/Brave-Browser/cffkpbalmllkdoenhmdmpbkajipdjfam/1.0.1229`
5. relaunched Brave
6. clicked on `hamburger` menu, chose `More tools` -> `Developer Tools`
7. clicked on the `Network` pane
8. loaded `https://shivankaul.com/adblock-redirect-test.html`
12. clicked on `hn.js`
13. clicked on the `Preview` pane

Confirmed inline script replacement

1.36.107 | 1.35.103
---------|---------
<img width="1595" alt="Screen Shot 2022-02-28 at 5 20 45 PM" src="https://user-images.githubusercontent.com/387249/156086663-7c627fe1-e4fc-41f1-b6b1-ec2589b0afbc.png"> | <img width="1595" alt="Screen Shot 2022-02-28 at 5 29 20 PM" src="https://user-images.githubusercontent.com/387249/156087451-66402fdd-a38a-40b8-a26b-8216023576c5.png">

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.36.107 Chromium: 99.0.4844.45 (Official Build) (64-bit)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | Windows 10 Version 21H2 (Build 19044.1526)

```
### Case 1: no `adblock-redirect` in `brave://flags`

Steps:
1. installed `1.36.107`
2. launched Brave
3. loaded `brave://flags`
4. typed `adblock-redirect`

Confirmed no match for `adblock-redirect`
