### ISSUE TITLE
[Android] Implement Rewards settings in Android settings 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20894]
## Description

Android analog of this: https://github.com/brave/brave-browser/issues/18158 (However, Android doesn't have brave://settings, so adapted appropriately.)

There is a Rewards section already in Android settings, but it doesn't contain many settings or toggles. Presumably, we would fill that subsection with all the Rewards settings. 

cc: @anthonypkeane

**Comment by deeppandya** [comment]
@Miyayes is this issue still valid ? as @zenparsing is making brave://rewards page responsive for desktop/android
