### ISSUE TITLE
Brave news - widget menu unusable (tablet only)

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20899]
## Description 

After scrolling down then coming back the ... menu is not clickable

## Steps to reproduce 

   1. Opt in News and scroll down
   2. Scroll back up all the way so the widget is visible
   3. Try to tap on the ... menu

## Actual result 
Nothing happens

## Expected result
The edit widget menu shows

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.104 x64 build
- Verified steps from issue description
- Verified able to tap on widget menu when Brave News is enabled

https://user-images.githubusercontent.com/17010094/155358460-51d83c27-acf8-45c8-bbb9-b4762578b64d.mp4
