### ISSUE TITLE
From balance isn't updating for Swap

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#20897]
Go to a Swap screen in Brave Wallet and observe that From Balance is never updated.
It started to happen on 1.37.x version only.

**Comment by Uni-verse** [comment]
Verification completed using Beta `1.37.103, Chromium 100.0.4896.46`

Test Devices: 
Samsung Galaxy S21 | Android 12
Samsung Galaxy Tab S7 | Android 11

- From balance is updating for Swap screen. 

https://user-images.githubusercontent.com/17885425/159799165-63d7aa6c-d04b-4dc2-b3fc-f2a3048a0d9d.mp4
