### ISSUE TITLE
Add Network Identifications to Portfolio Asset Item

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20902]
## Description 
To prepare for Multi Chain support we need to add network identifications to the `Portfolio Asset Item`

1) Add small `Network` icon next to the `Asset` icon
2) Add the `Network` name next to the `Asset` symbol

![image](https://user-images.githubusercontent.com/40611140/152613962-adab22f0-8716-410f-9863-e42175bd1d85.png)

**Comment by Uni-verse** [comment]
Verification completed using

```
1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
--
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
```

- [X] Add small Network icon next to the Asset icon
- [X] Add the Network name next to the Asset symbol

OP | FTM | AVAX | BSC | MATIC | ETH
-|-|-|-|-|-
![Screen Shot 2022-03-28 at 11 10 13 AM](https://user-images.githubusercontent.com/17885425/160460711-b37abfa3-1b97-46e3-b1e3-29a747b21cbf.png) | ![Screen Shot 2022-03-28 at 11 10 24 AM](https://user-images.githubusercontent.com/17885425/160460714-440869fb-cbc1-4c77-8965-1486e47c927f.png) | ![Screen Shot 2022-03-28 at 11 10 33 AM](https://user-images.githubusercontent.com/17885425/160460715-028dac66-c3b5-4a36-b280-a1f8c2be6bfd.png) | ![Screen Shot 2022-03-28 at 11 10 46 AM](https://user-images.githubusercontent.com/17885425/160460717-8234de29-3024-49bc-ae11-42bea914c0a9.png) | ![Screen Shot 2022-03-28 at 11 10 53 AM](https://user-images.githubusercontent.com/17885425/160460722-499a3492-8867-49de-ab2f-b2273bc02367.png) | ![Screen Shot 2022-03-28 at 11 11 02 AM](https://user-images.githubusercontent.com/17885425/160460724-d4c3192e-cc16-46a8-a424-d9213aa680db.png)
