### ISSUE TITLE
Shortcuts don't work properly on non-English keyboard

### ISSUE THREAD

**Issue by mojtabast** [brave/brave-browser#2090]
## Description 
When I switch to Persian on my keyboard, shortcuts don't work. I should switch to English keyboard to use shortcuts like `cmd + t` for open a tab. 

## Steps to Reproduce

   1. Switch to a non-English keyboard
   2. Try to use shortcuts. for example: `cmd + t`

## Actual result:
Doesn't work.

## Expected result:
It should works same as English keyboard.

## Brave version (brave://version info)
Brave	0.25.2
V8	6.9.427.23
rev	8ea2a9c
Muon	8.1.8
OS Release	18.0.0
Update Channel	Release
OS Architecture	x64
OS Platform	macOS
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	69.0.3497.100

I'm using Brave on MacOS Mojave.

**Comment by srirambv** [comment]
You are on muon browser which is deprecated. Please upgrade to the new [Brave Browser](https://brave.com/download).
