### ISSUE TITLE
Stop Crypto Wallet extension if user selected native Brave Wallet 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20905]
The setting only requires a new tab but it’s safest to restart after because if for example you have the crypto wallets extension loaded then it doesn’t close down until you restart and that can cause problems.  We should just prompt to restart I agree.

**Update**: In slack discussed if crypto wallets extension is started, it would need to be stopped when setting is not set to crypto wallets.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12178>brave/brave-core#12178</a></li>
         <li>Verified when default wallet provider is changed to <code>Brave Wallet</code> or <code>Brave Wallet (Prefer Extensions)</code>, ERC Wallet extension is disabled</li>
         <li>Verified changing back to Deprecated wallet doesn't start automatically, need to enable the extension manually</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/154946968-5a501d58-6ff1-416f-805a-5c3d81c98e74.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154946586-6ae7c338-487f-43b0-b451-51300f4e1f39.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154946207-03d71f70-c7bd-412c-a909-0a9e68e8c255.mov>
      </td>
   </tr>
</table>
