### ISSUE TITLE
Brave news - removing all widgets pushes the news cards up too much

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20901]
## Steps to reproduce 

   1. Opt in news
   2. Remove all widgets
   3. 

## Actual result 

News cards get pushed up and end up close to the middle on the screen

## Expected result

News should stay in the low end of the screen after widgets are removed

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by alexsafe** [comment]
@srirambv not sure if this is a duplicate, haven't found one though.

**Comment by Uni-verse** [comment]
Verification completed using `1.37.42, Chromium 98.0.4758.87`

**PASSED** on `Samsung GS 21` | `Android 12`

- Verified news stays on the lower end of the screen once widgets are removed.

Scenarios Tested:

- Brave news bar is displayed after widgets are removed while scrolling news
- User able to click on news posts, return to homepage
- User able to open brave news menu from bar
- User is able to re-add widget on homepage
- Opening new tabs

![Screenshot_20220212-013015_Brave - Nightly](https://user-images.githubusercontent.com/17885425/153651697-e5e8ae6e-d3fd-46fa-9717-03bd4c8bc6a5.jpg)

**Comment by srirambv** [comment]
Removing QA pass labels as this need to be retested again as its being uplifted to 1.36.x

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by Uni-verse** [comment]
Verification completed on release branch `1.36.105, Chromium 99.0.4844.45`
**PASSED** on `Samsung Galaxy S21` | `Android 12` | `ARM`

- Removing widgets does not push cards higher

Scenarios Tested:

- Brave news bar is displayed after widgets are removed while scrolling news
- User able to click on news posts, return to homepage
- User able to open brave news menu from bar
- User is able to re-add widget on homepage
- Opening new tabs via tray tab, menu
- Using reload button in hamburger menu takes user to top of homepage view

<img width="418" alt="Screen Shot 2022-02-24 at 5 26 53 PM" src="https://user-images.githubusercontent.com/17885425/155636461-8299268b-cba9-4f7f-8bb0-1c46f9817d6e.png">
