### ISSUE TITLE
Brave news - Reload menu button issue

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#20900]
## Description 
Reload menu button is not scrolling up to show the widgets view 

## Steps to reproduce 

   1. opt in news
   2. scroll a bit through the cards
   3. tap on the refresh menu

## Actual result 

The feed stays at the same place

## Expected result
Should go to the default home view with the widgets and image credits visible

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by alexsafe** [comment]
@srirambv I remember you mentioned this in a meeting, i created an issue, i didn't see one, so sorry if it's a duplicate

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` running `Android 12` using `1.37.42, Chromium 98.0.4758.87`

**PASS** - Selecting reload from the hamburger menu will reset view to default home view

**Comment by srirambv** [comment]
Need to retest the issue again as its being uplifted. Removing the QA pass labels

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by Uni-verse** [comment]
Verification completed on release branch `1.36.105, Chromium 99.0.4844.45`
**PASSED** on `Samsung Galaxy S21` | `Android 12` | `ARM`

- Tapping on reload button in hamburger menu will show widget view
- Reload button brings view back to top of tab when widgets are removed
- Reload button brings view back to top of tab when homepage icon is disabled
- Reload button works when brave news is disabled

https://user-images.githubusercontent.com/17885425/155634101-b2e643d5-e25b-4deb-94b4-84f229da02ab.mp4

**Comment by srirambv** [comment]
Verification failed on Samsung Tab A with Android 10 running 1.36.105. Refreshing the new tab page doesn't reset view to NTP view after scrolling through the feed. Logged https://github.com/brave/brave-browser/issues/21318
