### ISSUE TITLE
Rejected transactions load block chain explorer page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20922]
## Description 
Rejected transactions load block chain explorer page

## Steps to reproduce 

   1. Install 1.36.85 and enable wallet
   2. Initiate a transaction and reject it
   3. Go to asset details and click on the rejected transaction, loads block chain explorer which shows error page

## Actual result 

https://user-images.githubusercontent.com/17010094/152729793-f182ce57-feb1-4aef-8067-4c552ab10781.mp4

## Expected result
Should not load block chain explorer for rejected transactions

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.36.85 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @Pavneet-Sing @wchen342

**Comment by Pavneet-Sing** [comment]
Thanks for noticing it, I also noticed the same while fixing the linked issue and wanted to discuss the expected outcome when a reject transaction is clicked. As per this ticket expected behavior is ideal but we should show something to the user when a reject transaction is clicked, probably a message like "No details available for rejected transactions" or something?

**Comment by srirambv** [comment]
We should do the same as desktop. #19454 for reference

**Comment by Pavneet-Sing** [comment]
Desktop just hides the menu option, but on android, we can disable to click option but I feel like it would be great if we show a Toast (pop-up message for 1-2 seconds) to inform users about why nothing happened when a rejected transaction is clicked. what does iOS do when a rejected transaction is clicked? nothing (and click is disabled for the rejected transaction?)

**Comment by srirambv** [comment]
On iOS there is context menu shown on long press to open block explorer for confirmed transactions. But this option is not shown for rejected transactions. Probably follow the same as it was before do nothing for rejected transactions. That way it would have (somewhat) parity between all platforms
<img width=300 src=https://user-images.githubusercontent.com/17010094/152790016-c941ff09-32bb-48bf-a905-d5ba2b50d8a2.png>

**Comment by jamesmudgett** [comment]
disable

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.43.74 x64 Beta build
- Verified steps from issue description
- Verified no error page is loaded when a rejected transaction is clicked
- Verified on Solana/Ethereum/Polygon network transactions

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/185544323-ba0da6df-3a67-42e6-993c-5fd780115757.mp4> | <video src=https://user-images.githubusercontent.com/17010094/185545977-ac90f592-7125-4473-bc16-7dc06e1ab3e6.mp4>
