### ISSUE TITLE
Activate brave talk tab that has active session during the iterate by talk panel icon

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#20921]
## Description 

When user clicks sidebar talk icon, activate talk tab that has activate session(audio or video are unmuted) than inactive sesssion.

## Steps to Reproduce

   1. Open several brave talk tabs
   2. Make some tabs active session
   3. Make some tabs inactive session
   4. Clicks talk icon

## Actual result:

Active session should be iterated first

## Expected result:
it doesn't care active state now

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by mattmcalister** [comment]
Closing
