### ISSUE TITLE
PDF embed on a site that require login doesn't open.

### ISSUE THREAD

**Issue by bitcoinuser** [brave/brave-browser#2092]
## Description 

PDF embed on a site that require login doesn't open.

## Steps to Reproduce

   1.  Go to: https://pje.tjdft.jus.br/pje/login.seam?loginComCertificado=false
   2.  Login on site. (It's a government service, so not possible external users register on the site)
   3.  Go to site url: https://pje.tjdft.jus.br/pje/Processo/ConsultaProcesso/Detalhe/listAutosDigitais.seam?idProcesso=895132&ca=204877a3c129bdc3adb085b41b569d37c7a88930e85758aa9848bbe9b5ced0278eceb6272e2ea39feb225548eed06c7e

## Actual result:

![captura de tela de 2018-11-10 12-08-47](https://user-images.githubusercontent.com/1178856/48302245-677fbf80-e4e1-11e8-840a-13d0b3ff897d.png)

## Expected result:

See the pdf embed.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Versão 0.56.12 Chromium: 70.0.3538.77 (Versão oficial) 64 bits

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Didn't test

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by bbondy** [comment]
There's a different fix for 0.56.x and 0.57.x, could you try the beta build? https://brave.com/download-beta/

**Comment by bitcoinuser** [comment]
Same problem on Brave: Versão 0.57.6 Chromium: 71.0.3578.31 (Versão oficial) beta 64 bits

Obs. If some Brave team would like my login and password to test, I can give you. Send me an email where I can send the credencial.

![captura de tela de 2018-11-10 19-36-23](https://user-images.githubusercontent.com/1178856/48306456-29ee5700-e520-11e8-8426-445fffb6f13c.png)

**Comment by bbondy** [comment]
@bitcoinuser if you don't mind sharing the site, I'll get a fix in.  brian@brave.com

**Comment by Liunkae** [comment]
This problem appears to be fixed in the latest dev version (0.59.2). @bitcoinuser Please try the latest dev version: https://github.com/brave/brave-browser/releases.

**Comment by bsclifton** [comment]
Closing as this appears to be fixed, per comment by @cndouglas

**Comment by bitcoinuser** [comment]
Not fixed for me. I still have the same problem.

**Comment by bsclifton** [comment]
@bitcoinuser OK great- thanks for the info. 

We'll make sure we test this again once we have a final fix for some related issues (as it should fix this issue too)

**Comment by bsclifton** [comment]
@bitcoinuser we have a potential fix for this which is available in our NIGHTLY channel:
https://brave.com/download-nightly/

Would you be able to download and try this out? (you can always uninstall afterwards). I don't have a clear way to test this- as you're reporting an issue on a specific site

**Comment by bitcoinuser** [comment]
Fixed.

**Comment by bsclifton** [comment]
@bitcoinuser awesome! Thanks for confirming 😄
