### ISSUE TITLE
[Sync] Disable expiring of devices

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#20937]
It is required to disable Chromium's feature of expiring old (>56 days) devices in the sync chain. For the existing browser profiles the devices should be re-fetched from the server.

We need this because now the number of devices is limited to 50 per the sync chain and some users have an error of max num devices in chain, but in their list there are less than 50.

**Comment by stephendonner** [comment]
While not actively blocked, setting `QA-Blocked` while I work on refining the testplan 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.37.89 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

### Steps:
1. launched desktop using `--sync-url=https://sync-v2.brave.software/v2`
2. joined the provided test Sync chain using code words
3. confirmed I saw the `HAPPYUBU7` devices
4. launched Android using `--sync-url=https://sync-v2.brave.software/v2`
5. joined the Sync chain by scanning the QR code on desktop, from Android
6. confirmed I saw the `HAPPYUBU7` devices
7. confirmed my Android, Windows, and iOS devices could all see each other in the chain

`Win10` | `macOS` | `Android` | `iOS?`
----------|-----------|----------|----------
<img width="1312" alt="Screen Shot 2022-03-12 at 10 39 27 AM" src="https://user-images.githubusercontent.com/387249/158030808-6646b52f-29d5-4aa1-8233-48558979b252.png"> | <img width="1312" alt="Screen Shot 2022-03-12 at 10 39 27 AM" src="https://user-images.githubusercontent.com/387249/158030847-7dbc50e6-fd6e-486b-b1ec-4863838f1705.png"> | ![Screenshot_20220312-102430](https://user-images.githubusercontent.com/387249/158030855-c46f590f-8d45-4d66-be9b-02b4c8ab485b.png) | [iOS?]

Will return to verify with iOS

**Comment by Uni-verse** [comment]
Verification **PASSED** on `Android ARM` using version Beta `1.37.94, Chromium 99.0.4844.74`

Device: `Samsung Galaxy S21` running `Android 12`

- Verified able to connect to the staging sync chain using STR from slack thread: 

1. Disconnect network
2. Install Browser via APK
3. Enable dev tools and add the command line string --sync-url=https://sync-v2.brave.software/v2
4. Quit browser after relaunch
5. Connect back to network and relaunch browser, should start using staging URL for Sync

![Screen Shot 2022-03-16 at 1 40 52 PM](https://user-images.githubusercontent.com/17885425/158689942-23033e27-3c0b-4932-8556-db69565aa85a.png)

**Comment by Uni-verse** [comment]
Verification **PASSED** on `Android ARM` using version Beta `1.37.94, Chromium 99.0.4844.74`

Device: `Samsung Galaxy Tab S7` running `Android 11`

- Verified able to connect to the staging sync chain using STR from slack thread:
- Scanned QR Code from desktop sync chain

1. Disconnect network
2. Install Browser via APK
3. Enable dev tools and add the command line string --sync-url=https://sync-v2.brave.software/v2
4. Quit browser after relaunch
5. Connect back to network and relaunch browser, should start using staging URL for Sync
6. Navigate to settings > sync and scan sync QR code

![Screen Shot 2022-03-16 at 2 31 36 PM](https://user-images.githubusercontent.com/17885425/158694677-02d4f2e0-e949-4cf9-b09c-84e6fc0f2c8e.png)
