### ISSUE TITLE
Prevent build output getting invalidated when retrying with Goma off

### ISSUE THREAD

**Issue by mihaiplesa** [brave/brave-browser#20939]
Currently disabling Goma after doing local builds with it enabled invalidates the cache on macOS. Add option to pass `--offline` to `autoninja` which might fix.

**Comment by goodov** [comment]
This should work. I can think of it this way to keep things sane: `--use_goma=offline`.

**Comment by mihaiplesa** [comment]
@bridiver @goodov can this be closed? Or it needs the hermetic toolchain for non-Goma builds as well?

**Comment by bridiver** [comment]
this only applies to goma so I think it can be closed

**Comment by goodov** [comment]
we should close this. It's impossible to get same binaries with/without `--use_goma`. `--goma_offline` is added for that.
