### ISSUE TITLE
Desktop mode doesn't work always 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20936]
Reports of desktop mode now working on last release 

>Every time a new tab opens i need it to be desktop version. And it was working fine until after a few hours even though the settings were already for desktop view new tabs always opened in mobile view. Wt hell.

> Since the last update, the desktop view function has to be activated manually all the time, although it is activated in the settings.

> In the latest edition, desktop mode is not functioning.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` running `Android 12` using `1.37.42, Chromium 98.0.4758.87`

**PASS** - User is able to request desktop sites
**PASS** - Desktop sites work in private tabs
**PASS** - Globally setting desktop site opens tabs in desktop view

![Screenshot_20220212-053834_Brave - Nightly](https://user-images.githubusercontent.com/17885425/153683355-c397936c-97f2-499f-99aa-98a8e47c666a.jpg)
