### ISSUE TITLE
Gas Fee not Converted to ETH in Transaction Details Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20941]
## Description 
Gas Fee is not being Converted to ETH in Transaction Details Panel

![image](https://user-images.githubusercontent.com/40611140/152840475-3fd8e2e2-3884-4fb6-a3a5-cc99990d0c84.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12165>brave/brave-core#12165</a></li>
         <li>Verified transaction fee is showing ETH value correctly</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/154942464-510ef9ce-2af7-4ed6-97b5-1c9911858b19.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/154942287-73e9630b-8576-4e28-a949-bbc12a47858d.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/154942025-9829257a-fcfd-4f20-a479-8eaa21bb2a46.png>
      </td>
   </tr>
</table>
