### ISSUE TITLE
meusdividendos.com site doesn't work correctly 

### ISSUE THREAD

**Issue by bitcoinuser** [brave/brave-browser#2094]
## Description 

On Brave, after I login on http://meusdividendos.com/ I don't see some informations that appear on on Chrome or Opera.

## Steps to Reproduce

   1. Go to http://meusdividendos.com/ and click on top right (Entrar) to login.
   2. After login, click on profile avatar on top left
   3. 

## Actual result:

Should appear the page with graphs and some more informations. But on Brave only appear this:

![captura de tela de 2018-11-10 17-03-28](https://user-images.githubusercontent.com/1178856/48305046-f05f2100-e50a-11e8-8545-7ee40e4a5548.png)

## Expected result:

Appear the graphs and other informations. See what appear on Opera browser:

![captura de tela de 2018-11-10 17-06-55](https://user-images.githubusercontent.com/1178856/48305053-0a006880-e50b-11e8-8864-445c59ea1de9.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Versão 0.56.12 Chromium: 70.0.3538.77 (Versão oficial) 64 bits

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? I didn't test

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

If you need my login and password, I can give it to a person of Brave team. After you reproduce the problem, I change the password.

**Comment by ryanbr** [comment]
A bit late, not sure if you're still using Brave @bitcoinuser  Still an issue?
