### ISSUE TITLE
Fix monthly/weekly wallet usage ping parameter

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#20956]
## Description
Monthly and weekly usage flags for the wallet parameter in the usage ping, are set to true every day in the month and week. This results in inaccurate monthly and weekly user stats for the wallet.

The wallet usage monthly and weekly flags should only be set to true once during the relevant period, if the wallet was used in the period.

## Steps to Reproduce

Testers can use the [faketime](https://github.com/wolfcw/libfaketime) CLI to fake the system time for the browser process.

MITM proxy is recommended to see the usage ping query parameters. The parameter to look out for is `walletActive`. The value is a bitfield: LSB is daily use, second bit is weekly use, MSB is monthly use. Example: A `walletActive` value of 7 would indicate a monthly, weekly and daily use.

  0. Set current date to Feb 8, 2022
  1. Install browser with a fresh state
  2. Allow usage ping to occur, activate wallet, close browser
     - confirm usage ping walletActive=0 (inactive)
  3. Increment the date by one day
  4. Open browser, wait for usage ping, open wallet, and close the browser
     - confirm usage ping walletActive=7 (daily, weekly, monthly)
  5. Increment the date by one day
  6. Open browser, wait for usage ping, and close the browser
     - confirm usage ping walletActive=1 (daily)
  7. Increment the date by 7 days
  8. Open browser, wait for usage ping, open wallet, and close the browser
     - confirm usage ping walletActive=0 (no use since last report)
  9. Increment the date by one day
  10. Open browser, wait for usage ping, and close the browser
     - confirm usage ping walletActive=3 (daily, weekly)
  11. Set date to the first day in the next month
  12. Open browser, wait for usage ping, open wallet, and close the browser
     - confirm usage ping walletActive=0 (no use since last report)
  13. Increment the date by one day
  14. Open browser, wait for usage ping, and close the browser
     - confirm usage ping walletActive=7 (monthly, daily, weekly)

## Actual result:

Usage pings:

1. Correct. walletActive=0
2. Correct. walletActive=7
3. Incorrect. walletActive=7
4. Incorrect. walletActive=4
5. Incorrect. walletActive=7
6. Incorrect. walletActive=4
7. Correct. walletActive=7

## Expected result:

See notes in test plan above.

## Reproduces how often:
Easily reproduced

## Desktop Brave version:

Building from source.

Brave: 1.37.30 Chromium: 98.0.4758.87 (Developer Build) (64-bit)
Revision: e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758
OS: Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Raising PR soon. Will request uplift for upcoming release.

**Comment by DJAndries** [comment]
Related issue: brave/brave-browser#17059

**Comment by DJAndries** [comment]
Please refer to new test plan in PR once merged.

**Comment by GeetaSarvadnya** [comment]
@DJAndries Need a few clarifications on the test plan, please find my testing observations below:

- In step 8, I am getting `wallet=1` and usage pings are as below
![image](https://user-images.githubusercontent.com/38657976/155593611-1aef574b-e62f-4391-ae9f-abafcf799ad3.png)

**Comment by DJAndries** [comment]
@GeetaSarvadnya `wallet` is a bitfield.

Least significant bit = daily
Second bit = weekly
Most significant bit = monthly

Here is a description for each value:
0: no usage
1: daily
2: weekly

**Comment by GeetaSarvadnya** [comment]
@DJAndries The description is very ambiguous, e.g, for the value `6: monthly and weekly 

What are the criteria to calculate the monthly usage ping as `true`? In a month period, how many days are considered for monthly pings calculation, what is the start and end day period in a month? 
- In a month if I use the wallet two days in each week (8days), does the monthly usage considered true?
- In a month if I use the wallet only one day in 1st week, does the monthly usage considered true?
- In a month if I use the wallet for 1 day in 1st week, and 3 weeks did not open the browser, does the monthly usage considered true?
- In a month if I use my wallet for 2 days in the 1st week, 3 days in the 2nd week, 4 days in the 3rd week, and 5days in the 4th week, what should be the monthly usage pings? Is there any threshold value considered for the monthly usage ping calculation if so, what is the threshold value?

Also, how does the weekly usage calculation happen? what is the start and end day time period for weekly pings calculation? does it consider only Monday to Sunday time period? 

I have verified the PR https://github.com/brave/brave-core/pull/12310 and found a few bugs, looks like pings are not working as mentioned in the https://github.com/brave/brave-browser/issues/20956#issuecomment-1050245090. I have set up a call to discuss the wallet usage pings in detail. Thanks!

**Comment by DJAndries** [comment]
As discussed over the call, monthly usage is determined by calendar month and weekly usage is determined by the ISO week number of the year

**Comment by kjozwiak** [comment]
Will require `1.36.108` and https://github.com/brave/brave-core/pull/12277 to be uplifted into `1.36.x` as well. Labelling as `QA/Blocked` till https://github.com/brave/brave-core/pull/12277 is uplifted.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-core/pull/12449 was uplifted into `1.36.x`. However, this should be QA'd alongside https://github.com/brave/brave-core/pull/12277 using `1.36.109` or higher.

As discussed during the b-b meeting, @GeetaSarvadnya will run through a subset of the cases as this was already thoroughly verified on Nightly.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.36.109 x64 build
* Verified test plan from issue description

<details>
<summary>Case 1: <code>&wallet=0</code> - <b>Passed</b></summary>
<br>

- Set system date to today (March 3rd)
- Clean install and launch browser
- Verified wallet usage ping `&wallet` is appended to the browser usage ping 
- Verified wallet usage ping is `wallet=0` as no wallet is created
- Verified daily usage ping is as expected, `daily=true` , `weekly=true` & `monthly=true`
![image](https://user-images.githubusercontent.com/17010094/156526902-0edfcb9a-74fd-45e0-97f9-cc22e974855a.png)

</details>

<details>
<summary>Case 2: <code>&wallet=7</code> - <b>Passed</b></summary>
<br>

- Set system date to today (March 3rd)
- Clean install and launch browser
- Verified wallet usage ping is `wallet=0` as no wallet is created
- Verified daily usage ping is as expected `daily=true` , `weekly=true` & `monthly=true`
- Create wallet and then quit browser 
- Move device date ahead by 1 day to March 4th
- Relaunch browser
- Verified wallet usage ping is `wallet=7` as expected
- Verified daily usage ping is as expected, `daily=true`, `weekly=false` & `monthly=false`
![image](https://user-images.githubusercontent.com/17010094/156526938-2e6bed3a-108f-4056-a62a-55994aa67a09.png)

</details>

<details>
<summary>Case 3: <code>&wallet=1</code> - <b>Passed</b></summary>
<br>

- Set system date to today (March 3rd)
- Clean install and launch browser
- Create wallet and quit browser
- Move device date to 4th March
- Relaunch browser and unlock wallet
- Quit browser 
- Move device date to 5th March
- Relaunch browser and unlock wallet
- Verified wallet usage ping is `wallet=1` as expected
- Verified daily usage ping is as expected , `daily=true`, `weekly=false` & `monthly=false`
![image](https://user-images.githubusercontent.com/17010094/156526969-d9b6490d-ae2b-4ce3-bf03-e6c20dbb7151.png)

</details>

<details>
<summary>Case 4: <code>&wallet=3</code> - <b>Passed</b></summary>
<br>

- Set system date to today (March 3rd)
- Clean install and launch browser and create wallet
- Quit browser and move device date to 4th March
- Relaunch browser and unlock wallet
- Quit browser and move device date to 5th March
- Relaunch browser and unlock wallet
- Quit browser and move device date to 12 March
- Relaunch browser and unlock wallet
- Quit browser and move device date to 19 March
- Relaunch browser and unlock wallet
- Verified wallet usage ping is `wallet=3` as expected
- Verified browser usage ping is also as expected, `daily=true`, weekly=true` & `monthly=false`
![image](https://user-images.githubusercontent.com/17010094/156526994-67952ad5-ee10-4b51-8d32-6aae79f81710.png)

</details>

<details>
<summary>Case 5: <code>&wallet=5</code> - <b>Passed</b></summary>
<br>

- Set system date to March 31st
- Clean install and launch browser and create wallet
- Quit browser and move device date to April 1st
- Relaunch browser and unlock wallet
- Quit browser and move device date to April 2nd
- Relaunch browser and unlock wallet
- Verified wallet usage ping is `wallet=5` as expected
![image](https://user-images.githubusercontent.com/17010094/156527024-425b53c3-604e-4578-ba15-35c8d4b583bd.png)

</details>

<details>
<summary>Upgrade Profile</summary>
<br>

- Install 1.35.102 and enable walelt
- Upgrade to 1.36.109
- Quit browser and move device date ahead by 1 day
- Relaunch browser and verified wallet usage ping is set to `wallet=7` as the pings are sent for the first time after upgrade
- Verified browser usage pings are `daily=true`, `weekly=false` & `monthly=false`

</details>
