### ISSUE TITLE
Ads completely stopped, new tab page ads show but no bat earned. Total monthly ads received hasn't changed.

### ISSUE THREAD

**Issue by CCStreamZ** [brave/brave-browser#20957]
## Description 

All ads pop out ads have completely stopped. The new tab page ads show, but not Bat is given, and Total monthly ads count doesn't change either. When I check logs all types of errors. This on in particular is odd:  [Feb 07, 2022, 2:47:20.9 PM:INFO:ad_notification_serving.cc(117)] Ad notification not served: Not allowed due to permission rules

LOGS: 

[Feb 07, 2022, 2:47:20.9 PM:INFO:ad_notification_serving.cc(117)] Ad notification not served: Not allowed due to permission rules
[Feb 07, 2022, 2:47:26.3 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 03 (64.5:0:3600 s)
[Feb 07, 2022, 2:47:26.3 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 06 (64.5:0:3600 s)
[Feb 07, 2022, 2:47:26.7 PM:INFO:ad_transfer.cc(51)] Visited URL does not match the last clicked ad
[Feb 07, 2022, 2:47:26.7 PM:INFO:conversions.cc(239)] Checking URL for conversions
[Feb 07, 2022, 2:47:26.7 PM:INFO:text_classification_processor.cc(63)] Classified text with the top segment as personal finance-personal finance
[Feb 07, 2022, 2:47:26.8 PM:INFO:conversions.cc(302)] No conversions found for visited URL
[Feb 07, 2022, 2:47:39.5 PM:VERBOSE2:tab_manager.cc(86)] Tab id 178 is visible
[Feb 07, 2022, 2:47:39.5 PM:VERBOSE2:tab_manager.cc(104)] Opened a new tab with id 178
[Feb 07, 2022, 2:47:39.5 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 0D (65.5:0:3600 s)
[Feb 07, 2022, 2:47:39.5 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 0B (65.5:0:3600 s)
[Feb 07, 2022, 2:47:39.5 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 14 (65.5:0:3600 s)
[Feb 07, 2022, 2:47:39.7 PM:VERBOSE2:tab_manager.cc(77)] Tab id 178 was updated
[Feb 07, 2022, 2:47:39.7 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 11 (65.5:0:3600 s)
[Feb 07, 2022, 2:47:39.8 PM:INFO:ad_transfer.cc(51)] Visited URL does not match the last clicked ad
[Feb 07, 2022, 2:47:39.8 PM:INFO:conversions.cc(199)] URL is not supported for conversions
[Feb 07, 2022, 2:47:39.8 PM:INFO:ads_impl.cc(187)] Visited URL is not supported
[Feb 07, 2022, 2:47:39.8 PM:INFO:uphold.cc(114)] Uphold wallet is not VERIFIED.
[Feb 07, 2022, 2:47:44.4 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 0B (65.5:0:3600 s)
[Feb 07, 2022, 2:47:44.4 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 04 (65.5:0:3600 s)
[Feb 07, 2022, 2:47:44.6 PM:VERBOSE2:tab_manager.cc(77)] Tab id 178 was updated
[Feb 07, 2022, 2:47:44.6 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 11 (65.5:0:3600 s)
[Feb 07, 2022, 2:47:44.6 PM:INFO:ad_transfer.cc(51)] Visited URL does not match the last clicked ad
[Feb 07, 2022, 2:47:44.6 PM:INFO:conversions.cc(199)] URL is not supported for conversions
[Feb 07, 2022, 2:47:44.6 PM:INFO:ads_impl.cc(187)] Visited URL is not supported
[Feb 07, 2022, 2:47:49.2 PM:VERBOSE2:tab_manager.cc(86)] Tab id 179 is visible
[Feb 07, 2022, 2:47:49.2 PM:VERBOSE2:tab_manager.cc(104)] Opened a new tab with id 179
[Feb 07, 2022, 2:47:49.2 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 0D (66.5:0:3600 s)
[Feb 07, 2022, 2:47:49.2 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 0B (66.5:0:3600 s)
[Feb 07, 2022, 2:47:49.2 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 14 (66.5:0:3600 s)
[Feb 07, 2022, 2:47:49.4 PM:VERBOSE2:permission_rule_util.cc(25)] You do not have enough unblinded tokens
[Feb 07, 2022, 2:47:49.4 PM:INFO:new_tab_page_ad.cc(54)] New tab page ad: Not allowed due to permission rules
[Feb 07, 2022, 2:47:49.4 PM:INFO:ads_impl.cc(853)] Failed to fire new tab page ad kViewed event for uuid d8cb641d-418c-4d37-b15a-507fca101d3a and creative instance id 9aae69da-175c-47d2-b0a8-44ec69a01c07
[Feb 07, 2022, 2:47:49.4 PM:VERBOSE2:tab_manager.cc(77)] Tab id 179 was updated
[Feb 07, 2022, 2:47:49.4 PM:VERBOSE6:user_activity.cc(44)] Triggered event: 11 (66.5:0:3600 s)
[Feb 07, 2022, 2:47:49.5 PM:INFO:ad_transfer.cc(51)] Visited URL does not match the last clicked ad
[Feb 07, 2022, 2:47:49.5 PM:INFO:conversions.cc(199)] URL is not supported for conversions
[Feb 07, 2022, 2:47:49.5 PM:INFO:ads_impl.cc(187)] Visited URL is not supported
[Feb 07, 2022, 2:47:49.5 PM:INFO:uphold.cc(114)] Uphold wallet is not VERIFIED.
[Feb 07, 2022, 2:47:53.4 PM:INFO:uphold.cc(114)] Uphold wallet is not VERIFIED.
[Feb 07, 2022, 2:47:57.1 PM:INFO:ads_impl.cc(214)] Browser state changed to idle
[Feb 07, 2022, 2:48:19.5 PM:INFO:uphold.cc(114)] Uphold wallet is not VERIFIED.
[Feb 07, 2022, 2:48:49.5 PM:INFO:uphold.cc(114)] Uphold wallet is not VERIFIED.
[Feb 07, 2022, 2:48:54.4 PM:INFO:uphold.cc(114)] Uphold wallet is not VERIFIED.
[Feb 07, 2022, 2:49:19.5 PM:INFO:uphold.cc(114)] Uphold wallet is not VERIFIED.
[Feb 07, 2022, 2:49:49.5 PM:INFO:uphold.cc(114)] Uphold wallet is not VERIFIED.
[Feb 07, 2022, 2:49:54.2 PM:INFO:refill_unblinded_tokens.cc(118)] RequestSignedTokens
[Feb 07, 2022, 2:49:54.2 PM:VERBOSE2:refill_unblinded_tokens.cc(119)] POST /v2/confirmation/token/{payment_id}
[Feb 07, 2022, 2:49:54.2 PM:VERBOSE6:refill_unblinded_tokens.cc(129)] URL Request:
  URL: https://ads-serve.brave.com/v2/confirmation/token/137eea68-6f84-43b8-8882-2aceb8771346
  Content: {"blindedTokens":["iIsqv9WTL1dYgbJGgEA3th98Nm0Pun0JejRUREtEJl8=","QAGddrnEmrwMMjCfk6cP0wmvF2cZn2pENbo81rNwbm4=","njwp8M+BNU8OMoWE0gKzNgJcEUT8oqcV3ovry22nZCk=","OiqcEwf5vczEMS81bfQw8BlKEAmnK+VL1elVRkLmZHs=","2hOBOmhw7OnHliMi4nT+SdP+VRxNg3yMfJF3Iqa1kVs=","htvVpuA7io8Klob7/2zKTciyWTszZH085RTNBrY540Q=","jBanLaID1wupS6nhft3EZUEEZ4TiRFewcg9t7GDiLTQ=","1oQm/THl+5DDfzoTK6phJBTmpPp/R2uhSsn+1gAeWRQ=","Qo3GEqCTrqwDyG3/oNcc2dAq9u1NpRp4FtojWTrgsQ0=","GoK4H1uwji9v1J65moPveGKXLxm4pjhnDz0IOQ+vZXA=","7hBY+wDJTYwHwRKxLr5AlKcs/wr92rT6DTGXVrfEPTw=","NLpw/4bn9Jb1bHMS3qNHnD6RFMRqzqii+cVdhRfD8C4=","IFE7y09s/EUIv8BCouvQkFIQzQlLkvwdL7+CzLa/5Ts=","Ah/lDQBOHwoQWhjGOfQCGl6qgjrHg8W+IFWR1l4lmWs=","rrwL4bMW+rnjwHo0LLxL92Gi8bJWet7BD/nynTBZxT8=","8HqYbqX5K6MRK1PxP5o/I879oK6WKCEq0u+XDSK8vFg=","pICjwNZZyaLUtbLcbhi+jm9j+Zjo51uanC5gX2007WQ=","Llv5u3rARtbpo4S0Nhsct920kbNgetPit12lNJLjCXo=","3BwCo/5YYbYPV7Pbal0fNfq8Qg8tkoRKUGPp+vdRHlY=","Ks+PTOG5EJivMtXAHGrlhMV3NM4iShUlXvOlqqNgonw=","1sE3dnwr5EyCEvhbStnGgwubuUgfa4c2Q3Ex7R2fhgs=","LveJRe1ITGr6oSv/Jjtb2uKMPXa+gHWvgfl3n9w1a2w=","fO0ZQGc2xlUn7V5pUL4xhXdWFfbGmdDzpMOHQxqBLmo=","hsFQ4A3uio4ci4KOkT1bxFN992oBSgRsGksm941ouVM=","pFH7WR6CaatL250o4nupEfEPt4qQagssnPM+wyODpTE=","2A59HBEZKZ2wISx0xwuJje2g1+8RpUov7Z2GaDimAQc=","buKbDhz0Jhim1J5SqcQMXo3frxpGxvvICwMCyYUjeVg=","2KUpl24red9J0cguJJrpeZOAooi91qDohWhxFPo6qRo=","JMZ/qyDC87OBkNs/6L0wpwUYIHo4Vcw6LtxRq9hkjAs=","KmakbDuYC5zgzV01NB8aR25YqJ8Dq2YSELfoUkbMKDE=","SE/48kvN6K5B3ZtKGpHYNMtwfnnG9PfEe7+v22M9SSQ=","UNOYaFc6L7k8mn2zqeklvPgYPyFoE9N2xsyuJJBtJVI=","ACBaDsY8GZ/tyaU9+DHpksRQ5JAmPNvBqCUiVfTAg2o=","Hj8jMkZR9IERDAiVbZHfouvJ9400Zkfl7+QTumTZJnY=","tN5bIBxAvIBFJvrVuDfmIVmnydwMaEazD6HUZ+im2FU=","gpZGpoQtHbqiNlf556MXz+rYVcarf8D0pl9swnBejQQ=","Btk7MHwExWsVw3hF1JBujZ7zFkxX9LRwI/lBSuxPVGs=","GAJrWeUtQzIF3WscbkAMsudDpMVjDIlRq6VAHey7Uns=","ttYbm5PCAuLB904EoyD5LlehffMSuHlxh40QS4sfhlg=","KvQ7LJiJq7RDxPvxnK9asnSPLkpZ+1buW2Y60XcDcxE=","oMpLFtAym4E1RCLnOSbhX70UsChDZImG2z4jN7J5kis=","PPcSKt9b/VCFeYJOatKoRleD73C+qLf873NlQELPJ1c=","FKJ+HNxycnuq6LCWUHJaNFMjqsZxXCw9PVYGnjULISo=","0nIGBjVT4SA1JBtreHI7KsUtwg2JynmLIy+/adcpSig=","TpbD1iF59RBzufARlZ8zBn82COVxYHfHYBq0IczIOi8=","zhC1VGm4nVEe2Yz+W2GTC0K8hF+usMXmq6YHZzstB04=","zBT5NMsUfcxMZTo1nmwacRnI/h2TmkhMGOqi2sLlsjQ="]}
  Content Type: application/json
  Method: kPost
[Feb 07, 2022, 2:49:54.4 PM:INFO:refill_unblinded_tokens.cc(139)] OnRequestSignedTokens
[Feb 07, 2022, 2:49:54.4 PM:VERBOSE6:refill_unblinded_tokens.cc(141)] URL Response:
  URL: https://ads-serve.brave.com/v2/confirmation/token/137eea68-6f84-43b8-8882-2aceb8771346
  Response Status Code: 429
  Response: {"error":"Number of allowed tokens exceeded","statusCode":429}
[Feb 07, 2022, 2:49:54.4 PM:INFO:refill_unblinded_tokens.cc(145)] Failed to request signed tokens
[Feb 07, 2022, 2:49:54.4 PM:INFO:refill_unblinded_tokens.cc(364)] Retry refilling unblinded tokens in 0 hours, 37 minutes, 42 seconds at 3:27 PM

## Brave version (info found on brave://version)
[Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (64-bit)](https://brave.com/latest/)

## Miscellaneous Information:
State Level ad targeting option is completely gone. 

I used Brave built in private window with Tor for the first time the other day to try it out and just wonder if there is any correlation. Literally was working fine a few days ago but all of the sudden everything stopped, maybe it was the update I really don't know. I have a decent amount of Bat earned and I really don't want to lose that. I hope there is a fix.

**Comment by newuser-web** [comment]
Change your default language according to your location. For example It may be English (US) and you are in the UK. So in that case change it to English (UK).

**Comment by tmancey** [comment]
Closing issue as working as expected.
