### ISSUE TITLE
Page not loading only in Brave Browser

### ISSUE THREAD

**Issue by avndp** [brave/brave-browser#2096]
## Description 
I've been browsing the official MI.Com website for downloading the Mi Unlock tool. The link is: http://www.miui.com/unlock/index_en.html. When you click on the "Unlock" button, it's doing nothing, whereas in all other browsers, it's working.

## Steps to Reproduce
   1. Enter the link: http://www.miui.com/unlock/index_en.html (or) http://unlock.update.miui.com
   2. Click on "Unlock" button
   3. Thats it. It shows nothing.

## Actual result:
It's doing nothing, not opening any link, instead showing the same web page. 

## Expected result:
It should open the next web page.

## Brave version (brave://version info)
Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - NO, even though I turn off the Shield, its now working.
- Is the issue reproducible on the latest version of Chrome?  - NO. It's opening fine in Chrome.

**Comment by srirambv** [comment]
@avndp @kirkins http://www.miui.com/unlock/apply.php seems to work fine on all channels now with default shields settings. It redirects to a login page on account.xiaomi.com. 

Going to close the thread for now and we continue the discussion  here and reopen the thread if required.
