### ISSUE TITLE
Reset wallet doesn't remove the Dapp connections 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20966]
## Description 

Reset wallet doesn't remove the Dapp connections 

## Steps to Reproduce

   1. Create a wallet
   2. Link to wallet with multiple Dapps
   3. Reset wallet
   4. Go to `brave://settings/content/ethereum`, none of the Dapp connections are removed

## Actual result:

Reset wallet doesn't remove the Dapp connections 

## Expected result:
Not sure may be reset since we reset everything else?

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy @jamesmudgett @Douglashdaniel

**Comment by HEagle18** [comment]
Still an issue. Just tested on 1.48.

**Comment by Douglashdaniel** [comment]
cc: @darkdh @yrliou

**Comment by darkdh** [comment]
We should also clear the content settings for wallet (Ethereum + Solana) when reset, otherwise when the user creates new wallet that has different addresses, those permissions are unusable.

**Comment by yrliou** [comment]
^ exactly, just assigned myself to this, will take care of this when I'm available.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.62.99 Chromium: 120.0.6099.62 (Official Build) beta (64-bit)
-- | --
Revision | 0f3e892de210168e788b3418961f94c4d0c5942a
OS | Windows 11 Version 22H2 (Build 22621.2792)

- Verified steps from issue description and [brave/brave-core#20840](https://github.com/brave/brave-core/pull/20840)
- Verified resetting wallet also removes the saved Dapp connection info for both Ethereum and Solana accounts

https://github.com/brave/brave-browser/assets/17010094/ff9e72cf-cac5-452e-ba5f-c76c81fad0cd
