### ISSUE TITLE
`Desktop site` not working as expected under hamburger menu. Follow up to #20936

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#20963]
## Description 

Once https://github.com/brave/brave-browser/issues/20936 was fixed by https://github.com/brave/brave-core/pull/12164, we regressed how the `Desktop site` setting worked under the `Hamburger Menu`. Example:

* when `Desktop Mode` is disabled (default), tapping on `Desktop site` doesn't load the desktop version (nothing happens)
* when `Desktop Mode` is enabled via `Site Settings`, tapping on `Desktop site` doesn't load the mobile version (nothing happens)

## Steps to reproduce 

Prerequisite: you'll need to make sure you have a build that includes https://github.com/brave/brave-core/pull/12164 which is `1.37.31` or higher.

   1. download/install brave (ensure it's `1.37.31` or higher)
   2. skip onboarding (not needed/saves time)
   3. load any website (used https://boardgamegeek.com in my case)
   4. tap on the `Hamburger Menu` --> `Desktop site` (notice that the desktop version isn't being loaded)
   5. enable `Desktop Mode` via `Hamburger Menu` -> `Settings` -> `Site Settings`
   6. load https://cnn.com and tap on `Hamburger Menu` --> `Desktop site` (notice that the mobile version isn't being loaded)

## Actual result 

Looks like `Desktop site` stopped working/regressed even further once https://github.com/brave/brave-core/pull/12164 landed.

## Expected result

`Desktop site` should work as expected:
* if `Desktop Mode` is disabled, clicking on `Desktop site` should load the desktop version
* if `Desktop Mode` is enabled, clicking on `Desktop site` should load the mobile version

## Issue reproduces how often 

100% reproducible using the STR/Cases mentioned above

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `No`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

However, the `Desktop` feature is broken due to C98 hence https://github.com/brave/brave-browser/issues/20936.

## Device details

   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 12`
   
## Brave version

* `1.37.31 Chromium: 98.0.4758.87` - **Reproduced**
* `1.37.32 Chromium: 98.0.4758.87` - **Reproduced**

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.101 x64 build

**Desktop site via menu**
- Verified loading a page and then selecting `Desktop site` from menu reloads the page in desktop mode
- Verified unchecking the `Desktop site` reloads the current page loaded in desktop mode back to mobile view
- Verified enabling the setting via menu is only applicable to that particular tab
- Verified opening a new tab doesn't have the setting enabled by default
- Verified enabling `Desktop site` and loading a page loads it in desktop mode. 
- Verified visiting a different site on the same tab loads the new page in desktop mode
- Verified this works on both normal and private tabs

 **Desktop Mode via Site Settings**
- Verified `Desktop Mode`option is disabled by default under site settings
- Verified enabling the setting applies `Desktop site` on all new tabs
- Verified enabling the setting only applies to new tabs being loaded
- Verified with setting enabled, loading a site in a new tab loads the desktop version of the page
- Verified disable the `Desktop site` option from menu reloads the page into mobile view
- Verified with `Desktop Mode` enabled and `Desktop site` disabled on a page, closing the tab and restoring it loads in mobile view
- Verified disabling `Desktop site` loads mobile view. Loading the same site in a new tab loads in desktop mode
- Verified the setting works for both normal and private tabs
------------
Verification passed on Samsung Tab A with Android 11 running 1.35.101 x64 build

**Desktop site via menu**
- Verified loading a page and then selecting `Desktop site` from menu reloads the page in desktop mode
- Verified unchecking the `Desktop site` reloads the current page loaded in desktop mode back to mobile view
- Verified enabling the setting via menu is only applicable to that particular tab
- Verified opening a new tab doesn't have the setting enabled by default
- Verified enabling `Desktop site` and loading a page loads it in desktop mode. 
- Verified visiting a different site on the same tab loads the new page in desktop mode
- Verified this works on both normal and private tabs

 **Desktop Mode via Site Settings**
- Verified `Desktop Mode`option is disabled by default under site settings
- Verified enabling the setting applies `Desktop site` on all new tabs
- Verified enabling the setting only applies to new tabs being loaded
- Verified with setting enabled, loading a site in a new tab loads the desktop version of the page
- Verified disable the `Desktop site` option from menu reloads the page into mobile view
- Verified with `Desktop Mode` enabled and `Desktop site` disabled on a page, closing the tab and restoring it loads in mobile view
- Verified disabling `Desktop site` loads mobile view. Loading the same site in a new tab loads in desktop mode
- Verified the setting works for both normal and private tabs
