### ISSUE TITLE
Brave forgets directory where last file was downloaded when saving files via "save as"

### ISSUE THREAD

**Issue by HalfTough** [brave/brave-browser#2097]
## Description 
When downloading files using "save page as…" or "save image…" options from drop down menu, brave forgets last used location and opens dialog for saving file in either "Downloads" od "Documents".

## Steps to Reproduce
   1. Right click on an image on a page
   2. Save image…
   3. Pick location and save
   4. Right click on another image
   5. Save image…

## Actual result:
Dialog shows "Downloads" or "Documents" directory.

## Expected result:
Dialog should show directory in which last file was saved.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 0.25.2
V8 | 6.9.427.23
rev | 8ea2a9c
Muon | 8.1.8
OS Release | 4.15.0-38-generic
Update Channel | Wersja
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

### Additional Information
I'm using KDE and file dialog used by Brave also appears to be KDE/qt file dialog.

**Comment by srirambv** [comment]
You are on muon browser which is deprecated. Please manually upgrade to [Brave browser](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux)
