### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by spphinslove** [brave/brave-browser#20978]
"up" in here should be 开启.so the corret display is "屏蔽 开启 对于此网站"
"down" in here should be 关闭.so the corret display is "屏蔽 关闭 对于此网站"
![屏幕截图 2022-02-08 233058](https://user-images.githubusercontent.com/11383988/153020204-dc3ab50b-9bb5-49b6-b55c-45a3dd7bfc17.png)
![屏幕截图 2022-02-08 233110](https://user-images.githubusercontent.com/11383988/153020233-dda07139-4e67-4fa5-8b64-691872c51319.png)

**Comment by rebron** [comment]
Closing as stale/invalid. Fixed with Shields v2.
