### ISSUE TITLE
[Android] Missing Month Message on rewards 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20972]
## Description 
Missing Month Message on rewards 

## Steps to reproduce 
No idea

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/152980051-7a290709-8d33-409f-af9f-dd5d27d54bb2.png)

## Expected result
No such error message

## Issue reproduces how often 
No idea

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
GPS build 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Miyayes @brave/legacy_qa @brave/rewards-client @deeppandya

**Comment by Miyayes** [comment]
This should be resolved in 1.35.x, as this UI was replaced. 1.35.x now at 100% rollout on Android store, so all users should upgrade.

**Comment by srirambv** [comment]
This is fixed after upgrading to 1.35.100 so closing it
