### ISSUE TITLE
DevTools crashes immediately

### ISSUE THREAD

**Issue by JakobJingleheimer** [brave/brave-browser#20971]
I searched yesterday for issues containing "devtools" but found nothing related.

## Description 

When loading a particular app, DevTools immediately crashes and closes itself. Or if the project is already open and DevTools is opened, DevTools opens and then immediately crashes and closes itself.

The issue does not occur in the same version of Chrome (98.0.4758).

I have not been able to narrow down what could be the cause.

The issue first appeared last week, which appears to coincide with the release of Brave 1.35.100.

## Steps to Reproduce

I've only been able to reproduce on an internal site; I'll try to figure out a repro and update this when I do.

## Reproduces how often: 

100% of the time

## Brave version

Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (x86_64)

macOS 12.2

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No

- Does the issue resolve itself when disabling Brave Rewards?
No

- Is the issue reproducible on the latest version of Chrome?
No

**Comment by OscarDCorbalan** [comment]
I hit the same problem, and couldn't narrow it down to anything particular. Other browsers (Chrome/Firefox/Safari/Edge) work fine where Brave's dev tools crashes

**Comment by EagleLizard** [comment]
I'm also seeing this as of updating today
OS: MacOS 12.1
Brave: V1.35.100

**Comment by Mottoweb** [comment]
Getting the same issue, but I have something particular, dev tools crashed when I disable Shields.

**Comment by crash83k** [comment]
I've been encountering this issue for months. On my end, this is really common when I'm working on an Angular application. Recently we started using Redux/NgRx, and the crashing became a little more common, but was happening long before then.

Ubuntu 21.10 (it's been happening since before I was on 20.10, though)
Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (64-bit)

Also, I don't know if this is a memory issue possibly. But I had this issue on both a 32GB and 128GB machine. In all cases there was at least 5GB free when these crashes happen.

**Comment by dpflueger** [comment]
I get it on a local single-spa application with Vue.js.
I activated logging and the error is 
`[16236:16472:0210/143617.676:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 18`

**Comment by Chumbees** [comment]
I see this on one app I work with, uses AngularJS, and seems to only happen on certain pages

Brave version V1.35.101

**Comment by crash83k** [comment]
> 

Good point. I'm doing that as well, and totally forgot about shields. I have to run with shields down as well for our work.

**Comment by tiubrian** [comment]
I'm in the same situation where I can't turn on shields since my work requires shields off. So I've unfortunately have had to use alternative browsers.

**Comment by JakobJingleheimer** [comment]
I have Site Shield disabled for the domain, so Site Shield _shouldn't_ be a candidate for my case.

**Comment by TwiggyBuffalo** [comment]
I have the same issue on:

OS: macOS Monterey 12.0.1
Brave: 1.35.101 Chromium: 98.0.4758.87

**Comment by Joxtacy** [comment]
I am having the same issue. I posted a comment in a similar issue. https://github.com/brave/brave-browser/issues/21154#issuecomment-1042607217

**Comment by DanjiSes** [comment]
I am having the same issue. On [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (arm64) Mac Big Sur 11.5.2

**Comment by EagleLizard** [comment]
Still seeing this after the recent update:
MacOS Monterey 12.2.1
Brave Version 1.35.103
Chromium: 98.0.4758.102 (Official Build) (x86_64)

**Comment by trentrand** [comment]
It appears to be fixed in the latest update!

MacOS Monterey 12.0.1
Brave Version 1.36.109
Chromium: 99.0.4844.51 (Official Build) (arm64)

**Comment by Joxtacy** [comment]
Working for me as well!

MacOS Monterey 12.2.1
Brave Version 1.36.109
Chromium: 99.0.4844.51 (Official Build) (x86_64)
