### ISSUE TITLE
Connected sites menu item opens and perform search rather than opening the setting

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#20974]
## Description 

Connected sites menu item opens and perform search rather than opening the setting

## Steps to Reproduce

   1. Connect to a dapp
   2. Click on panel, menu, connected site
   3. Opens a new tab and performs search for `Ethereum` 

## Actual result:

Connected sites menu item opens and perform search rather than opening the setting

## Expected result:
Should probably just load the Ethereum settings page rather than searching for `Ethereum`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.36.86 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | `e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by Uni-verse** [comment]
Verified using 

```
Brave	1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64) 
Revision	5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS	macOS Version 12.1 (Build 21C52)
```
- Opening wallet panel, clicking on menu > `connected sites` opens `brave://settings/content/ethereum` page
