### ISSUE TITLE
Apple Trackpad Crashing

### ISSUE THREAD

**Issue by willin** [brave/brave-browser#20989]
## Description 

Brave is awesome. however, i bought a trackpad 2021 for my mac, it' crashing and crashing again.

## Steps to Reproduce

just use gesture

## Expected result:

just like use bluetooth mouse

## Reproduces how often: 

perhaps every time

## Brave version (brave://version info)

[版本 1.35.100 Chromium: 98.0.4758.87（正式版本） (arm64)](https://brave.com/latest/)

## Other Additional Information:

macos 12.1 with m1 max (14'), apple trackpad 3rd generation (2021)

**Comment by bsclifton** [comment]
Apologies that we missed this - @willin if you are still using Brave, please let us know if you have ran into any issues with this.

I'll close issue now - but if it's still happening and you're able to respond and can help find more info, I can re-open.
