### ISSUE TITLE
Routinely clear out or expire stale creator info from `publisher_info_db` so that browser fetches fresh creator info upon next visit

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20980]
## Description

For example, if a Twitter creator changes their name, and a user had already visited that Twitter account prior to the name change, it will retain the old string and show the old name string in the Rewards panel. The name is essentially cached with no expiration. 

## Solution

Clear out stale creator entries from `publisher_info_db` periodically so that the browser fetches new information next time the user visits the creator's page.

**Comment by mkarolin** [comment]
**QA steps to verify:**
1. In Brave, navigate to a twitter page you own, e.g. twitter.com/supergood
2. Open the Rewards panel and note `supergood` shown in the panel
3. In twitter settings (account settings) change your name (handle) to something else, e.g. extragood
4. In Brave, navigate to the page twitter.com/extragood
Before the fix:
5. Open the Rewards panel and note `supergood` is still shown in the panel
With the fix:
5. Open the Rewards panel and note `extragood` is now shown in the panel

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.41.77 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 10 Version 21H2 (Build 19044.1766)

```

**Comment by stephendonner** [comment]
## Verified `PASSED` using Brave

1.41.82 | Chromium: 103.0.5060.66 (Official Build) beta (64-bit) 
--|--
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Linux

### Confirmed changing display name in Twitch updates it in the Rewards panel

example | example
---------|---------
<img width="1220" alt="Screen Shot 2022-06-29 at 10 51 54 AM" src="https://user-images.githubusercontent.com/387249/176503746-cfa2660a-8394-4164-8eea-6a08efcc3fea.png"> | <img width="1220" alt="Screen Shot 2022-06-29 at 10 52 37 AM" src="https://user-images.githubusercontent.com/387249/176503757-8bf27b7e-0aa0-4e9d-bf1c-cf9876a11859.png">

**Comment by Uni-verse** [comment]
Verification in progress on Android ARM
