### ISSUE TITLE
Google Docs is completely bugged in Brave Beta

### ISSUE THREAD

**Issue by MaXfAa** [brave/brave-browser#20981]
## Description 

Google Docs is completely buggy and **unusable**. Unable to read, missing the end of the lines, unable to move around the document (neither with the mouse, nor with the arrows)

## Steps to Reproduce

   1. Just go to any Google Docs 

## Actual result and expected result:

Example n°1:
Brave:
![image](https://user-images.githubusercontent.com/71935156/153028236-71966aa3-fd20-4d03-9109-e3beed6bc44a.png)

Edge:
![image](https://user-images.githubusercontent.com/71935156/153028409-da4f9bf2-1c62-439a-8e3c-c5f8c38f1e1b.png)
By the way, it can be seen that the document has one page on Brave when in reality it has two.

Example n°2:
Brave
![image](https://user-images.githubusercontent.com/71935156/153028726-58cc817d-2354-4cc2-9dc2-053634385bf1.png)

Edge:
![image](https://user-images.githubusercontent.com/71935156/153028865-910cb98a-7af8-4b30-8487-06aa03d1111d.png)

## Reproduces how often: 

This bug is present all the time and on all Google Docs !

## Brave version (brave://version info)

Brave: 1.36.83 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
Revision: e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS: Windows 11 Version 21H2 (Build 22000.469)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes: 
![image](https://user-images.githubusercontent.com/71935156/153030363-d9f35646-87e1-4d98-9c74-78d618ebda79.png)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Brave Shields is always disabled (to avoid conflicts with uBlock)
- Does the issue resolve itself when disabling Brave Rewards? 
Brave Rewards is always disabled
- Is the issue reproducible on the latest version of Chrome? 
No, it works fine (in Edge)

**Comment by Areckleh** [comment]
+1 Twitter 
Brave Nightly Version 1.40.41 Chromium: 101.0.4951.54 (Official Build) nightly (64-bit)
No issues on Edge
![image](https://user-images.githubusercontent.com/43886134/167723859-e4a4dcc9-9628-4115-9baf-9f8de5a49eac.png)

**Comment by GeetaSarvadnya** [comment]
I have verified the issue on Windows 10 a couple of times, Issue is not reproducible.

```

Brave | 1.36.83 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

**Comment by MaXfAa** [comment]
> @MaXfAa @Areckleh Try disabling hardware acceleration in `brave://settings/system`

It doesn't change anything 😢

**Comment by Areckleh** [comment]
@ryanbr @MaXfAa No change after disabling Hardware Acceleration.

> @MaXfAa @Areckleh Try disabling hardware acceleration in `brave://settings/system`

**Comment by MadhaviSeelam** [comment]
Verified the issue on Windows 11, disabling and enabling `Use hardware acceleration when available` in brave://settings/system, couldn't reproduce. 
```
Brave | 1.39.100 Chromium: 101.0.4951.61 (Official Build) beta (64-bit)
-- | --
Revision | 3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS | Windows 11 Version 21H2 (Build 22000.613)
```

**Comment by PhysGuy01** [comment]
You'll have to enable fingerprinting for that website for it to work

**Comment by MaXfAa** [comment]
> You'll have to enable fingerprinting for that website for it to work

Ooooooh! Thank you sooo much 🔥
