### ISSUE TITLE
"backup" should be "back up" in Rewards dialog

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#20987]
## Description 

"backup" should be "back up" in Rewards dialog

## Steps to Reproduce

   1. install `1.37.33` or later
   2. enable Rewards
   3. I forget exact steps, but get to the state where it shows the following `Backup your wallet` alert dialog.

## Actual result:

<img width="1593" alt="Screen Shot 2022-02-08 at 4 57 24 PM" src="https://user-images.githubusercontent.com/387249/153103790-1f98f003-c3dd-44ab-be3a-f355917ed5c8.png">

## Expected result:

All three instances of `backup` there should read `back up` (with correct case).

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.33 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

cc @rmcfadden3

**Comment by rmcfadden3** [comment]
Yep, great eyes, @stephendonner! In this case it's an imperative / verb, so it should be "Back up" as 2 separate words.

**Comment by adarrssh** [comment]
Hey, I am new here. Can you assign me this issue?

**Comment by shivampapat** [comment]
Hi @stephendonner . Raised PR for the same. Please review :  https://github.com/brave/brave-core/pull/12260

**Comment by bhattabhi013** [comment]
Is this issue resolved? Can I work on it?

**Comment by zenparsing** [comment]
Fixed in https://github.com/brave/brave-core/pull/12341
