### ISSUE TITLE
SKU SDK should be able to handle more than one environment

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#20984]
## Description 
Right now, if SKU SDK is enabled (behind brave://flags/#skus-sdk flag) - you also need to set an environment flag (brave://flags/#skus-environment)

When this is set, you can only login to that environment because the SKU SDK code will use that hardcoded environment for the incoming calls on the account.brave.software/account.bravesoftware.com/account.brave.com website

## Steps to Reproduce

   1. Set brave://flags/#skus-sdk flag to enabled
   2. Set brave://flags/#skus-environment to `development`
   3. Try to login to https://account.brave.com

## Actual result:
Page gets stuck loading

## Expected result:
User should be able to login to page

## Reproduces how often: 
100%

## Desktop Brave version:
1.37.33 (Nightly / Desktop / Windows)

**Comment by stephendonner** [comment]
+1

When someone gets cycles to look at this, it'd be good to take this on, as it would reduce a bit of confusion for testers and dogfooding folks.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.62 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 13.0 (Build 22A5295i)

### Steps:
1. installed `1.42.62`
2. launched Brave
3. set `brave://flags/#skus-sdk` to `Enabled`
4. restarted Brave
5. loaded, created an account on, and logged in to each of the following environments: `development`, `staging`, `production`

**NOTE**: `brave://flags/#skus-environment` is no longer present; it's dynamic, now.

`brave://flags/#skus-sdk`
-------------------------
<img width="1156" alt="Screenshot 2022-07-13 at 1 12 16 PM" src="https://user-images.githubusercontent.com/387249/178828381-79564d64-de35-4f6a-8f80-93a381a48cf9.png">



`development` (`account.brave.software`) | `staging` (`account.bravesoftware.com`) | `production` (`account.brave.com`)
----|------|-----
<img width="1312" alt="Screenshot 2022-07-13 at 1 15 03 PM" src="https://user-images.githubusercontent.com/387249/178827654-75d26552-9248-4af8-a5c9-35b7273d3e64.png"> | <img width="1312" alt="Screenshot 2022-07-13 at 1 16 10 PM" src="https://user-images.githubusercontent.com/387249/178827656-1fb9ec7d-70f6-456c-968a-dc44763b1c07.png"> | <img width="1312" alt="Screenshot 2022-07-13 at 1 25 24 PM" src="https://user-images.githubusercontent.com/387249/178827998-4a00e61b-ee79-46f6-9e61-1ac4fcbd547b.png">

**Comment by Uni-verse** [comment]
Verification in progress on Samsung GS 21 & Tab S7 using

Brave	1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Android 12; Build/SP1A.210812.016

**Comment by MadhaviSeelam** [comment]
Verification `In-progress` using 
```
Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 11 Version 21H2 (Build 22000.795)
```

Steps:

1. installed 1.42.78
2. launched Brave
3. set brave://flags/#skus-sdk to Enabled
4. restarted Brave
5. loaded, created an account on, and logged in to each of the following environments: development, staging, production

NOTE: brave://flags/#skus-environment is no longer present; it's dynamic, now.
brave://flags/#skus-sdk

Ex1|Ex2|Ex3
----|----|----
<image width="950" alt="850" src="https://user-images.githubusercontent.com/98358127/181660354-50e91b2a-8af5-456e-93c2-e410194ec1f4.png">|<image width="950" alt="850" src="https://user-images.githubusercontent.com/98358127/181660490-80cb0235-4eb1-4437-80b7-0c05fbce2f1d.png">|<image width="950" alt="850" src="https://user-images.githubusercontent.com/98358127/181660470-67616ff8-3d4e-4194-938d-cb5b9663ecdb.png">|
