### ISSUE TITLE
Address bar shows wrong address

### ISSUE THREAD

**Issue by HalfTough** [brave/brave-browser#2098]
## Description 
After closing tab while address bar is selected, tab to which brave will switch to will keep old address.

## Steps to Reproduce
   1. Have at least two tabs opened
   2. Select address bar
   3. Close current tab using keyboard shortcut

## Actual result:
Tab changed, but address bar still shows address of closed tab

## Expected result:
Address should reflect active tab.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 0.25.2
V8 | 6.9.427.23
rev | 8ea2a9c
Muon | 8.1.8
OS Release | 4.15.0-38-generic
Update Channel | Wersja
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

### Additional Information
This is especially troubling, because address bar is selected by default when switching to previously unopened new tab.

**Comment by srirambv** [comment]
You are on muon browser which is deprecated. Please manually upgrade to [Brave browser](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux)
