### ISSUE TITLE
Add Network Icon to Network Selector Button

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20986]
## Description 
Add Network Icon to the Network Selector Buttons.

![Screen Shot 2022-02-08 at 1 25 31 PM](https://user-images.githubusercontent.com/40611140/153071551-3f9b7d62-d96c-46e0-9f7a-36ebb37a947e.png)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.3 (Build 21E230)
```
