### ISSUE TITLE
When balance cannot be fetched from custodian or user is in `Logged out` state, use unavailable text or "- -" for the Rewards balance

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20991]
## Description

When a user is in a logged out state and can't query their balance from their custodian, their balance will usually show 0.0 BAT (since all vBAT has already been userdrained to the custodian).

<img src="https://user-images.githubusercontent.com/11497541/153180119-8f102852-6bb4-4aeb-b186-41b142d040bd.png" width=300px>

- [ ] Rewards panel
- [ ] Rewards settings page
- [ ] Rewards NTP widget

**Update:** This will also happen when custodian has downtime and the balance cannot be fetched. So, might be more general than when user is in a logged out state. 

## Solution

Use "N/A" (or some other string), which may be less alarming to users than seeing a declaration of `0.0 BAT`.

**Comment by Miyayes** [comment]
Even if user is in a logged out state and receives some vBAT (an edgier case), I still think it's more beneficial to show N/A. The user can either disconnect from their custodian completely to get rid of N/A and see their vBAT there, or they can connect again and then the vBAT will be instantly userdrained.

**Comment by Miyayes** [comment]
This will help enforce correct vBAT vs. BAT balance states: https://github.com/brave/brave-browser/issues/21588

**Comment by Miyayes** [comment]
Using dashes instead of N/A:

![image](https://user-images.githubusercontent.com/11497541/164554509-4edcbeab-4ee1-4bb9-8872-5a4c7458da47.png)

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.41.77 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 10 Version 21H2 (Build 19044.1766)

```
