### ISSUE TITLE
window.ethereum is not available after reloading page

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#20993]
## Description 

if users have opened tabs that work with `window.ethereum` object and enable native Brave Wallet using another tab then the object will not be available after reloading tabs. it becomes available only after opening a new instance of tabs.

## Steps to Reproduce

   1. Set Wallet type preference to None
   2. Open chainlist.org in a new tab
   3. Set Wallet type preference to Brave Wallet
   4. Go to tab with chainlist.org and reload it
   5. check `window.ethereum` object in console

## Actual result:

the object is not available

## Expected result:

the object available and work as expected

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12193>brave/brave-core#12193</a></li>
         <li>Verified when default provider is set to <code>None</code>, <code>window.ethereum</code> returns <code>undefined</code></li>
         <li>Verified after changing default provider from <code>None</code> to <code>Brave Wallet</code>, <code>window.ethereum</code> returns a response when the same page is reloaded</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/154948217-c955814f-738d-4d9a-b181-e4403f12ee0a.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154947949-9df4edd3-7996-4d6f-aa06-687ee7d96195.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154947655-6b1006e8-407b-4f7e-808e-ac00f054945f.mov>
      </td>
   </tr>
</table>
