### ISSUE TITLE
Empty bookmark folders in Sidebar lack selection/highlight color.

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21004]
## Description 

Empty bookmark folders in Sidebar lack selection/highlight color.

## Steps to Reproduce

   1. install `1.37.36`
   2. load `brave://flags`
   3. enable `Enable Sidebar`
   4. click `Relaunch`
   5. click on `Bookmarks` in the Sidebar
   6. single- or context-click on any EMPTY bookmark folder

## Actual result:

No selection/highlight of the clicked folder.

## Expected result:

As in `brave://bookmarks`, when clicking on a folder, there should be a selection color applied to it.

actual | expected
------|-----------
<img width="1204" alt="Screen Shot 2022-02-09 at 11 10 18 AM" src="https://user-images.githubusercontent.com/387249/153272903-b0224018-d73b-4934-b3b9-8523b38be96c.png"> | <img width="1312" alt="Screen Shot 2022-02-09 at 11 10 00 AM" src="https://user-images.githubusercontent.com/387249/153272838-6aafd779-7431-4ed2-9e5b-3804b35431b8.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.36 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

cc @simonhong @rebron

**Comment by rebron** [comment]
Closing as stale. We're using a different sidebar panel now.
