### ISSUE TITLE
Addresses are duplicated when multiple keyring enabled

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#21015]
## Description 

Enable multiple keyrings and Import 1 address from Ledger and it will be shown 3 times on the page
![image](https://user-images.githubusercontent.com/2965009/153353187-ee979f0b-4e21-46e9-8b11-c472744a40d4.png)

## Steps to Reproduce

   1. Enable multiple keyrings
   2. Import 1 account from Ledger
   2. Check wallet page
   3. it will be shown 3 times

## Actual result:

address duplicated

## Expected result:

1 address shown

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by spylogsster** [comment]
it happens because we save hardware addresses separately from a keyring in preferences:
```
          "keyrings":
            {
                "default":
                {
                    "account_metas": {},
                    "imported_accounts":[],
                },
                "hardware": {
                    "3939e7b....55157e81ae7": {
                          "account_metas": {},
                    }
                },
                "filecoin": {},
                "solana": {}
            }
```
Eventually it duplicated for each keyring, proposed fix is to determine target keyring based on https://github.com/brave/brave-core/blob/master/components/brave_wallet/browser/keyring_service.cc#L149 coin type and put  hardware accounts under dedicated keyring like this:
```
          "keyrings":
            {
                "default":
                {
                    "account_metas": {},
                    "imported_accounts":[],
                    "hardware": {
                        "3939e7b....55157e81ae7": {
                              "account_metas": {},
                        }
                    },
                },
                "filecoin": {
                    "hardware": {
                        "4939e7b....55157e81ae7": {
                              "account_metas": {},
                        }
                    },
                },
                "solana": {
                    "hardware": {
                        "5939e7b....55157e81ae7": {
                              "account_metas": {},
                        }
                    },
                }
            }
```

**Comment by lukemulks** [comment]
I am observing the same as above, and am also observing double the qty of asset and represented value of assets in Portfolio view. 

The wallet icon menu is displaying true asset values. 

Only observing double values in brave://wallet/crypto/portfolio 

Observed from 2 machines, both on latest Nightly on Windows 10.
