### ISSUE TITLE
Follow up of # 18394 - P3A_Rewards enable duration metrics for hour/day/week/month are not working as expected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21017]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/18394
P3A_ rewards enable duration metrics for hour/day/week/month are not working as expected
## Steps to Reproduce

   1. Clean profile 1.36.x
   2. Enable rewards
   3. Open the brave://local-state file and confirm `Brave.Rewards.EnabledDuration` metrics value is  `1` as expected
   4. Close the browser
   4. Set the system clock ahead by 1 day 
   5. Relaunch the browser and disable/reset rewards via `Manage your wallet`
   6. Reload the brave://local-state file 
   7. Look for `Brave.Rewards.EnabledDuration` metrics 
   8. `Brave.Rewards.EnabledDuration` metrics value is `0` instead of `3` 
   
**Note:**  Repeat the steps for hour/week/month

## Actual result:

Rewards enable duration metrics for hour/day/week/month are not working as expected

## Expected result:
`Brave.Rewards.EnabledDuration` metrics should give correct response for hour/day/week/month

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.36.87 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1503)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rillian @brave/legacy_qa @Miyayes @mattmcalister

**Comment by rillian** [comment]
I think the various preference settings may be overwriting each other's P3A state; the browsertest only verifies the `brave_ads.enabled` switch. It's possible resetting the virtual wallet isn't tracked correctly as well. But I've not been able to confirm either of those is the ultimate issue.

The question is to be simplified in #21030, so I think we shouldn't investigate further and instead see if the new measurement in that issue is reliable.

**Comment by GeetaSarvadnya** [comment]
As per the above comments https://github.com/brave/brave-browser/issues/21017#issuecomment-1048063844. closing the issue as invalid
