### ISSUE TITLE
IPFS flyout menu items should have an ellipsis, as they require further user input

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21011]
## Description 

IPFS flyout menu items should have an ellipsis, as they require further user input

## Steps to Reproduce

   1. install `1.37.37`
   2. launch Brave
   3. load `ipns://ipfs.io`
   4. click on `Use a Brave local IPFS node`
   5. click on the 3-dots menu
   6. click on the `IPFS` `-> flyout menu
   7. examine the menu options

## Actual result:

They are missing `...` ellipses

<img width="1482" alt="Screen Shot 2022-02-09 at 3 21 21 PM" src="https://user-images.githubusercontent.com/387249/153308237-69cfa0a8-04f3-47e7-bc9e-7938886778b8.png">

## Expected result:

Nearly everything except for `Open Files` (since that doesn't require further user input) should read, e.g. `Import and Share a File...` , etc.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.37 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.3 (Build 21E5196i)

cc @spylogsster @lidel

**Comment by stephendonner** [comment]
cc @jessicaschilling for UX input

**Comment by jessicaschilling** [comment]
@stephendonner — @lidel can help you find a contact for UI input. I'm no longer affiliated.

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
