### ISSUE TITLE
Enable sidebar in private window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21013]

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.43 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. enabled `Enable Sidebar` via `brave://flags`
4. opened a `Private Window with Tor`
5. opened a `Private Window`
6. opened a `Guest` window

Confirmed all windows opened with a working Sidebar.

Private Window with Tor | Private Window | Guest window
------------------------|------------------|---------------
<img width="1312" alt="Screen Shot 2022-02-11 at 11 17 04 AM" src="https://user-images.githubusercontent.com/387249/153655747-2e90994f-d2c2-4fd7-9bb4-96e95ba5c55c.png"> | <img width="1312" alt="Screen Shot 2022-02-11 at 11 16 33 AM" src="https://user-images.githubusercontent.com/387249/153655857-292a0005-6153-498d-bb20-7e7b99f1fd3d.png"> | <img width="1312" alt="Screen Shot 2022-02-11 at 11 16 47 AM" src="https://user-images.githubusercontent.com/387249/153655821-b116e179-e0ce-41be-aac6-c2d09e392a7a.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.86 Chromium: 99.0.4844.51 (Official Build) beta (64-bit) 
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Ubuntu 18.04 LTS

<details>

Private
![image](https://user-images.githubusercontent.com/34715963/157730752-15889138-90f7-494a-a247-d791329d8316.png)
Private with Tor
![image](https://user-images.githubusercontent.com/34715963/157730796-d95e1239-0c10-43b2-b09b-9930a7d72d33.png)
Guest
![image](https://user-images.githubusercontent.com/34715963/157730842-621eed41-c458-4377-89fc-bffca1963cc1.png)
Other profile
![image](https://user-images.githubusercontent.com/34715963/157730924-63caf3f1-e8d4-4658-bf7b-84ee33c65d2f.png)

</details>

**Comment by MadhaviSeelam** [comment]
Brave |	1.37.87 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
---|--
Revision | 	d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | 	Windows 11 Version 21H2 (Build 22000.556)

- Clean profile
- Launched `Brave`
- opened a `Private Window with Tor`
- opened a `Private Window`
- opened a `Guest window`

Verified all three windows opened with a Sidebar as a default

Note:  `Enable Sidebar` flag is no longer available in Brave://flags.   The flag was removed with #[20876](https://github.com/brave/brave-browser/issues/20876)

Private Window with Tor|Private Window|Guest Window
---|---|---
<img width="700" alt="private window with tor" src="https://user-images.githubusercontent.com/98358127/157917717-f87a3637-de05-46e3-b0b3-77b0551afcf3.png"> | <img width="700" alt = "private window" src = "https://user-images.githubusercontent.com/98358127/157918156-a20f2f04-dc0f-4f52-bbe3-ff858eb62ba9.png"> | <img width= "700" alt="guest window" src= "https://user-images.githubusercontent.com/98358127/157918459-5a4c2fc0-35be-47ce-a663-aa33782f5f04.png">
