### ISSUE TITLE
Browser blocking site logos also apart from Ads

### ISSUE THREAD

**Issue by avndp** [brave/brave-browser#2101]
## Description 
Brave is blocking website logos also in many websites. For example: https://aavo.in , whereas in all other browsers the logo is displaying even though the adblockers are enabled.

## Steps to Reproduce
Open the site https://aavo.in in Brave browser and you can see the logo is not opened / blocked. The same is visible in all other browsers

## Actual result:
![image](https://user-images.githubusercontent.com/32923858/48329501-1c93b280-e66f-11e8-8d00-7ea7220caf3f.png)

## Expected result:
![image](https://user-images.githubusercontent.com/32923858/48329509-22899380-e66f-11e8-841d-2a28b4869c54.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? - Not checked

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  - NO, even though the shield is turned off, still it blocks the logo.
- Is the issue reproducible on the latest version of Chrome? - NO, in Chrome it's working fine.

**Comment by kirkins** [comment]
Seems to be fixed
