### ISSUE TITLE
Sidebar bookmarks item icon has glitches

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21014]
Non active state image has glitches.
<img width="54" alt="image" src="https://user-images.githubusercontent.com/6786187/153318557-95700f4c-8055-44a7-91f8-690d4243e096.png">

Active state image is fine.
<img width="74" alt="image" src="https://user-images.githubusercontent.com/6786187/153318663-f8004e9d-c7c4-48a5-ad44-f06bc6798830.png">

**Comment by kjozwiak** [comment]
Above issue requires `1.37.98` or higher for verification on `1.37.x`.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.37.98 Chromium: 99.0.4844.74 (Official Build) beta (64-bit)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the STR from the description and ensured the Sidebar bookmarks item icon doesn't have a glitch

Non-active state | Active state
--|--
![image](https://user-images.githubusercontent.com/38657976/158984722-07078ec3-e036-4e0e-be60-00c3fedd24e6.png) | ![image](https://user-images.githubusercontent.com/38657976/158984831-62e27da9-2319-4629-8722-277e881f917d.png)

**Comment by simonhong** [comment]
@GeetaSarvadnya non active icon should not be colored one.
If colored one is visible when bookmarks panel is closed, it's bug.
and non colored icon had glitches.

**Comment by GeetaSarvadnya** [comment]
@simonhong I have captured the mouse hover on the bookmarks icon
