### ISSUE TITLE
Auto-contribute Bug

### ISSUE THREAD

**Issue by Kaleb542** [brave/brave-browser#21025]
Hello,
 
I have never had my auto-contribute turned on, but it was activated without my consent and gave away 5 BAT from my wallet. The amount lost is 5 BAT from my uphold wallet.

I know this has been a problem before and tried to message the refund email, but is has been closed. Any help on a refund is much appreciated.

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by Kaleb542** [comment]
I am yet to hear anything about refunding these BAT or making the situation right. I'd someone could reach out, that would be great.

**Comment by hollons** [comment]
Thanks for your patience @Kaleb542. Could you submit a ticket using this link and selecting 'no form' https://support.brave.com/hc/en-us/requests/new?ticket_form_id=360001330571, or write into Community.brave.com directly? We'll get this resolved and ensure that no BAT is lost. The most common cause for this is that when a new device is linked to your custodial wallet, AC is turned ON by default. Thanks again for reporting.

**Comment by Kaleb542** [comment]
Thanks for your response @hollons. I have had a post open for 5 days on the community page and have not heard anything back. Can you bump this to the CS team or something? Many thanks. 
https://community.brave.com/t/auto-contribute-stole-my-funds/340373

**Comment by hollons** [comment]
Thanks for sharing the link @Kaleb542! Will get this resolved now.

**Comment by zenparsing** [comment]
The underlying UX issue will get resolved by https://github.com/brave/brave-browser/issues/15308
