### ISSUE TITLE
Bad speedreading on https://aws.amazon.com/blogs/

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#21022]
https://aws.amazon.com/blogs/security/category/security-identity-compliance/aws-secrets-manager/

![Screenshot from 2022-02-11 00-37-37](https://user-images.githubusercontent.com/3109556/153464507-d7a4ea24-5ead-45ff-a6e7-9a4ecc703f32.png)

Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.39.39 Chromium: 100.0.4896.79 (Official Build) nightly (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

<img width="1786" alt="Screen Shot 2022-04-07 at 1 32 51 PM" src="https://user-images.githubusercontent.com/387249/162291169-63dd7abb-2722-44d4-975a-7d436d4b6ace.png">
