### ISSUE TITLE
npm run init command takes forever when repository is forked

### ISSUE THREAD

**Issue by Jagruti1610** [brave/brave-browser#21020]
## Steps to Reproduce

   1. Fork brave-browser repository.
   2. Follow instructions from read me file.
   3. Execute: npm run init .

## Actual result:

![Screenshot from 2022-02-10 20-33-58](https://user-images.githubusercontent.com/28809492/153436345-e7e6b840-f35a-491b-8d73-3ef30b97d552.png)

In the Read me file it is mentioned that it takes around 45 minutes. In my case, it has been more than an hour.

## Expected result:
Ideally, I am not sure how long it should take. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Thanks for the report @Jagruti1610 - maybe we we need to update the time. It takes a REALLY long time to get the Chromium source code due to the history. What you shared above looks 100% correct; it's in the middle of getting the history

Closing as this is expected - once you get this setup though, you can use `npm run sync` and it'll never take that long again. I always keep the source on my machine 😄 If you run `init` again on accident instead of `sync`, it's still safe if you have the source. Updating is always faster

**Comment by Jagruti1610** [comment]
I will be more than happy to help with documentation. Any guidance to start?

**Comment by bsclifton** [comment]
@Jagruti1610 sure - maybe you can share where you saw the 45 mins and then a proposed update? If on the wiki, I can help you get this updated 😄 If it's in the README.md or CONTRIBUTING.md, we can do a pull request

**Comment by Jagruti1610** [comment]
@bsclifton I saw this here https://github.com/brave/brave-browser/blob/master/README.md#clone-and-initialize-the-repo

**Comment by Jagrutiti** [comment]
I would also like to point out instances where I had to get help and didn't find it in the document (maybe  I missed, not sure) :

 Got the following errors with the build command: `  npm run build --- command`

**1.** `TypeError: __init__() got an unexpected keyword argument 'capture_output'`
 **Solution**: Make `Python 3.7` default `python3 --version` in Ubuntu. This solution could differ in other OS.


**2.** `FAILED: failed gen/third_party/blink/renderer/core/css/parser/at_rule_descriptors.cc`
**Solution:** Install additional dependencies from [here](https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md#Install-additional-build-dependencies)

**Comment by bsclifton** [comment]
@Jagrutiti updated the wiki - I fixed the broken link which went to prerequisites and added a note for Python 3 (as you captured here):
https://github.com/brave/brave-browser/wiki/Linux-Development-Environment

If you want to fork this repo, you can edit `https://github.com/brave/brave-browser/blob/master/README.md` and then submit proposed changes as a pull request 😄

**Comment by Jagrutiti** [comment]
@bsclifton I have made a PR here: https://github.com/brave/brave-browser/pull/21253

**Comment by pras92** [comment]
>It takes a REALLY long time to get the Chromium source code due to the history.

For reference, it is 28GB of download (gclient) and post download, takes about: 
~8 hrs for "Resolving deltas".
4 hrs & running with no ETA, for an unknown process (post checking objects, with no info on what's happening)

On a 8GB DDR4, i7-7700HQ, SSD with average consumption of 88% Memory, 6% CPU, 49% Disk. Try running git on GPU instead. 
The setup process couldn't be crappier.
