### ISSUE TITLE
Bad speedreading https://www.circle.com/blog/solana-pay

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#21023]
https://www.circle.com/blog/solana-pay

![Screenshot from 2022-02-11 00-40-48](https://user-images.githubusercontent.com/3109556/153465074-6bbc76ac-771b-4fe2-b84c-ecad48c69f2b.png)

Brave | 1.37.26 Chromium: 98.0.4758.87 (Official Build) nightly (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.39.10 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed the issue with `beta`, and the fix in `nightly`.

`beta` | `1.39.10, nightly`
-------|------------------
<img width="1312" alt="Screen Shot 2022-03-28 at 1 36 54 PM" src="https://user-images.githubusercontent.com/387249/160483493-96187c77-ccca-4c95-b7a4-36261e53e325.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 1 39 44 PM" src="https://user-images.githubusercontent.com/387249/160483499-ec14f17e-cf1c-4e5c-a835-f335a2dc1ce0.png">
