### ISSUE TITLE
Profiles with a lot of cookies are hanging just after downloading the main frame document

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#21029]
Profile with a lot of cookies will load news.ycombinator.com in ~850ms. Different user profile _in the same running browser instance_ will get ~250ms. There seems to be a hang in the browser process just after the first document request and before the resource requests.
![image](https://user-images.githubusercontent.com/741836/153504613-0e81fe8b-4ad8-4a48-aa0b-111cae911976.png)

After diving in to the issue where with a profile that has a lot of cookies, the hang seems to be in `RenderFrameHostImpl::CommitNavigation`
![image](https://user-images.githubusercontent.com/741836/153504686-96c8987c-2b1d-431c-8721-e07fbb56197f.png)

In fact, the hang is here: https://github.com/chromium/chromium/blob/d1924a490f88d7cf2e952007029520cfba5b13c9/content/browser/renderer_host/render_frame_host_impl.cc#L10935
```
        partition->OpenLocalStorageForProcess(
            process_id, commit_params->storage_key,
            storage_info->local_storage_area.InitWithNewPipeAndPassReceiver());
```

This code path is only run if the feature flag `NavigationThreadingOptimizations` is enabled, which it is by default in the code. However, at least for desktop, Chrome seems to have disabled it.

I am unsure if this affects Android.

**Comment by bsclifton** [comment]
Re-opening as issue is only fixed in staging

**Comment by kjozwiak** [comment]
Going to close this off as we disabled `NavigationThreadingOptimizations` was disabled on at `100%` on both Nightly & BETA and at `5%` on `RELEASE` on Friday as per https://github.com/brave/brave-variations/pull/217. Later today, we bumped `RELEASE` to `50%` via https://github.com/brave/brave-variations/pull/221. If things are looking stable, we're going to push to `100%` tomorrow.

QA has verified the above via https://github.com/brave/brave-variations/pull/217#issuecomment-1036657679. @bsclifton @petemill please re-open if you don't agree 👍
