### ISSUE TITLE
Update P3A rewards enabled question to measure ads

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#21030]
## Description 

Recently we added `Brave.Rewards.EnabledDuration` but there isn't really a good definition of "Rewards Enabled". We used to have a settings toggle for rewards overall, but it's been removed and currently we look at a combination of ads and autocontribute opt-in settings.

@miyayes asked me to alter the measurement to just report how long ads were enabled. This is the more relevant question.

**Comment by Miyayes** [comment]
Thanks @rillian, I think we should rename the question just to avoid confusion (unless it introduces a lot of wrinkles).

**Comment by Miyayes** [comment]
My intuition is that "resetting Brave Rewards" doesn’t count as disabling Brave Ads, so it doesn't need to be a QA test case for this question. The user is probably resetting Brave Rewards for a different reason, and therefore it's not exactly the kind of behavior we’re interested in knowing about (namely, the user going and explicitly disabling Brave Ads itself). 

Let me know if that creates any problems or makes sense to you too! @rillian

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries Is the wiki updated to reflect these changes?

**Comment by kjozwiak** [comment]
Verification **`PASSED`** on `Samsung S10+` running `Android 12` using the following build(s):

```


```

Went through the STR/Cases outlined via https://github.com/brave/brave-core/pull/12371 & https://github.com/brave/brave-browser/issues/21030#issuecomment-1092057586.
 
**_Clean profile_**

<details>
<summary>Case 1: Ads was never ON_Brave.Rewards.AdsEnabledDuration=0_PASSED</summary>

- Verified that when rewards is NOT enabled, the metrics `Brave.Rewards.AdsEnabledDuration` response value is `0`

![Screenshot_20220426-021353_Brave](https://user-images.githubusercontent.com/2602313/165234093-7a96d61f-3379-4a7f-9ce4-ffc1bf32ec7a.jpg)

</details>

<details>
<summary>Case 2: Ads is still ON_Brave.Rewards.AdsEnabledDuration=1_PASSED</summary>

- Verified that when rewards is enabled, the metrics `Brave.Rewards.AdsEnabledDuration` response value is `1`

![Screenshot_20220426-021443_Brave](https://user-images.githubusercontent.com/2602313/165234125-f610f94c-28aa-4225-b7e4-4de7b5dc8464.jpg)

</details>

<details>
<summary>Case 3: Ads was enabled less than three hours in past_Brave.Rewards.AdsEnabledDuration=2_PASSED</summary>

**Case 1_enable and disable Ads in a minute**
- Clean profile 1.38x
- Enable rewards and disable Ads switch
- Open brave://local-state file
- Ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `2` as Ads is disabled within three hours

![Screenshot_20220426-021657_Brave](https://user-images.githubusercontent.com/2602313/165235607-4398fb0e-1ab4-44f5-8894-aa32fce9cf61.jpg)

**Case 2_disable Ads in < 3 hours**
- Clean profile 1.38.x
- Enable rewards and close the browser
- Set the system time ahead by 2 hours
- Relaunch the browser
- Disable the Ads switch
- Open brave://local-state file
- Ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `2` as Ads is disabled within three hours

![Screenshot_20220426-042118_Brave](https://user-images.githubusercontent.com/2602313/165235633-0fe4621f-bf45-40fa-aae1-89df53b1b985.jpg)

**Case 3_disable Ads exactly at 3 hours:** 
- Clean profile 1.38.x
- Enable rewards and close the browser
- Set the system time ahead by exact 3 hours
- Relaunch the browser
- Disable the Ads switch
- Open brave://local-state file
- Ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `3` as Ads is disabled exact at 3 hours

![Screenshot_20220426-052142_Brave](https://user-images.githubusercontent.com/2602313/165235672-e528663e-6034-4b74-bd42-cf889d7bfc24.jpg)

**Case 4_disable Ads after 3 hours:** 

- Clean profile 1.38.x
- Enable rewards and close the browser
- Set the system time ahead by 3 hours 2 mins 0 secs
- Relaunch the browser
- Disable the Ads switch
- Open brave://local-state file
- Ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `3` as Ads is disabled after 3 hours

![Screenshot_20220426-052538_Brave](https://user-images.githubusercontent.com/2602313/165235726-3005b6a5-4858-4b72-bea8-60df44078caa.jpg)

</details>

<details>
<summary>Case 4: Ads was enabled less than three days in past_Brave.Rewards.AdsEnabledDuration=3_PASSED</summary>

**Case 1: disable ads in < 3days**

1. Clean profile 1.38.x
2. Enable rewards and close the browser
3. Set the system date ahead by 1 or 2 days (<3days)
4. Relaunch the browser
5. Disable ads switch
6. Open brave://local-state
7. `Brave.Rewards.AdsEnabledDuration` response value is `3` as Ads is disabled within 3days

![Screenshot_20220428-023002_Brave](https://user-images.githubusercontent.com/2602313/165237182-ebf90c95-2b40-4f15-9872-fce100849625.jpg)

**Case 2: disable ads exactly on the 3rd day**

1. Clean profile 1.38.x
2. Enable rewards and close the browser
3. Set the system date ahead by 3days 
4. Relaunch the browser
5. Disable Ads switch
6. Open brave://local-state
9. Ensured that the `Brave.Rewards.AdsEnabledDuration` response value is `4` as Ads is disabled on the 3rd day

![Screenshot_20220429-023239_Brave](https://user-images.githubusercontent.com/2602313/165237276-b7034e16-13ef-4e87-89e6-5cc61f53e480.jpg)

**Case 3: disable ads after 3days**

1. Clean profile 1.38.x
2. Enable rewards and close the browser
3. Set the system date ahead by 3 days 2 mins 00 seconds 
4. Relaunch the browser
5. Disable Ads switch
6. Open brave://local-state
11. Ensured that the `Brave.Rewards.AdsEnabledDuration` response value is `4` as Ads is disabled after 3days

![Screenshot_20220429-023649_Brave](https://user-images.githubusercontent.com/2602313/165237306-b1a4d799-8a1a-455a-905b-64b0377090d1.jpg)

</details>

<details>
<summary>Case 5: Ads was enabled less than three weeks in past_Brave.Rewards.AdsEnabledDuration=4_PASSED</summary>

Case 1: disable ads in < three weeks

- Clean profile 1.38.x
- Enable rewards and close the browser
- Set the system time ahead by 3=>days & <=20days
- Relaunch browser
- Disable Ads switch
- Open brave://local-state file
- Ensured that the `Brave.Rewards.AdsEnabledDuration` response value is `4` as Ads is disabled within 3 weeks

![Screenshot_20220506-024021_Brave](https://user-images.githubusercontent.com/2602313/165238131-e9a957b6-1520-4d96-9496-960f6b76fe1d.jpg)

Case 2: disable ads exactly on the 3rd week (21st day)

- Clean profile 1.38.x (Apr 11th)
- Enable rewards and close the browser
- Set the system time ahead by 21days (May 2nd)
- Relaunch browser
- Disable Ads switch
- Open brave://local-state file
- Ensured that the `Brave.Rewards.AdsEnabledDuration` response value is `5` as Ads is disabled on the 3rd week

![Screenshot_20220517-024232_Brave](https://user-images.githubusercontent.com/2602313/165238150-a738966b-b717-4619-b20c-744b132dc538.jpg)

</details>

<details>
<summary>Case 6: Ads was enabled less than three months in past_Brave.Rewards.AdsEnabledDuration=5_PASSED</summary>

**Case 1:** Passed

- Clean profile 1.38.x
- Enable rewards and close the browser
- Set the system date 21=>days <=89
- Relaunch the browser
- Disable Ads switch
- Open brave://local-state file
- Ensured that the `Brave.Rewards.AdsEnabledDuration` response value is `5` as Ads is disabled within 3 months

**Case 2:** - Passed

- Clean profile 1.38.x
- Enable rewards and close the browser
- Set the system date ahead by 90 days
- Relaunch the browser
- Disable Ads switch
- Open brave://local-state file
- Ensured that the `Brave.Rewards.AdsEnabledDuration` response value is `5` as expected (Discussed with @DJAndries: 30.44 days as a "month" (that's the average length of a month) multiply that by three and we get 91.32, so 90 days would not trigger a value of `6`)

</details>

<details>
<summary>Case 7: Ads was enabled more than three months in past_Brave.Rewards.AdsEnabledDuration=6_PASSED</summary>

- Clean profile 1.38.x
- Enable rewards and close the browser
- Set the system date ahead by 91 days (greater than 3 months)
- Relaunch the browser
- Disable Ads switch
- Open brave://local-state file
- Ensured that the `Brave.Rewards.AdsEnabledDuration` response value is `6`
![image](https://user-images.githubusercontent.com/38657976/162799259-c49cdc07-1cd7-46f4-a6eb-c10724622a9b.png)

</details>

<details>
<summary>Case 8: Reset rewards_Brave.Rewards.AdsEnabledDuration=0_PASSED</summary>

- Clean profile 1.38.x
- Enable rewards
- Open brave://local-state file
- Ensured `Brave.Rewards.AdsEnabledDuration` response value is `1` as expected
- Reset the rewards via `Manage Brave Rewards`
- Reload the brave://local-state file and brave://rewards page
- Restart the browser
- Ensured that the `Brave.Rewards.AdsEnabledDuration` response value is `0` as expected
![image](https://user-images.githubusercontent.com/38657976/162801334-b1cb1c58-a949-48b2-b7e3-671d41224815.png)

</details>


**_Upgrade profile_**

<details>
<summary>Case 1: Enable Rewards and upgrade the profile_PASSED</summary>

- Install `1.37.x beta` build and enabled rewards and upgraded the profile to `1.38.x` and ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `1` as expected
- Disable Ads switch in 1.38.x upgraded profile and ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `2` as expected

</details>

<details>
<summary>Case 2: Enable Rewards and disable Ad switch and then upgrade the profile_PASSED</summary>

- Install `1.37.x beta` build and enabled rewards and disable Ads switch and upgraded the profile to `1.38.x` and ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `0` as expected

</details>

<details>
<summary>Case 3: Enable Rewards and disable AC switch and then upgrade the profile_PASSED</summary>

- Install `1.37.x beta` build and enabled rewards and disable rewards AC switch and upgraded the profile to `1.38.x` and ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `1` as expected

</details>

<details>
<summary>Case 4: Enable Rewards and disable Ads and AC switches manually and then upgrade the profile_PASSED</summary>
- Install `1.37.x beta` build and enable rewards disable Ads and AC switches and upgraded the profile to `1.38.x` and ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `0` as expected

</details>

<details>
<summary>Case 5: Enable Rewards and reset rewards and then upgrade the profile_PASSED</summary>
- Install `1.37.x beta` build and enable rewards and reset rewards and upgraded the profile to `1.38.x` and ensured that the metrics `Brave.Rewards.AdsEnabledDuration` response value is `0` as expected
</details>
