### ISSUE TITLE
Follow up to #20543: Ad notification count increased to one without viewing Ads/Custom ads/NTPSI in an upgraded profile

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#21031]
Follow up to: https://github.com/brave/brave-browser/issues/20543

The following upgrade path fails: 1.34.x->1.35.x->1.36.x

The bad state acquired in 1.35.x is not fixed in 1.36.x

## Steps to Reproduce

1. Clean profile 1.34.x
1. 1.34.x: Enable ads and rewards
1. Open `brave://rewards` 
1. Check ads view count
1. Close browser
1. Upgrade to 1.35.x
1. Open `brave://rewards` and reload it 3 times
1. Check ads view count
1. Close browser
1. Upgrade to 1.36.x
1. Open `brave://rewards` and reload it 3 times
1. Check ads view count

## Actual result:

ads view count is `1` in `brave://rewards`
The bad state from 1.35.x is transferred to 1.36.x

![image](https://user-images.githubusercontent.com/34715963/153517640-01445d94-677e-41e4-a61c-cc3e2504b010.png)

## Expected result:
ads view count is `1` in `brave://rewards`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Verification passed on

Brave | 1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Ubuntu 18.04 LT

cc @brave/legacy_qa @rebron @tmancey @jsecretan

**Comment by tmancey** [comment]
It has been accepted that any user who has upgraded to 1.35.x will be in a broken state until the beginning of the following month.

**Comment by tmancey** [comment]
Closing as wont fix
