### ISSUE TITLE
Hide all unsupported test networks along with custom networks for Swap screens

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21039]
## Description 
https://github.com/brave/brave-core/pull/12204 fixed hiding custom EVM's which are added where Buy & Swap is unsupported. Similarly we should hide test networks for Swap as its only allowed on Mainnet and Ropsten

## Steps to reproduce 

   1. Open Swap screen
   2. Select Network dropdown
   3. Able to select unsupported test networks

## Actual result 

https://user-images.githubusercontent.com/17010094/153558989-ce14b1e5-2b21-4c28-87dd-26693ee25a2b.mp4

## Expected result
Should hide unsupported test networks

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @Pavneet-Sing

**Comment by kjozwiak** [comment]
Removing this from the `1.37.x` milestone as this hasn't been labelled as `release/blocking` nor has it been finished as it's still in the backlog.

**Comment by HEagle18** [comment]
@Douglashdaniel this work is redundant after your work gets shipped on desktop, correct ? as in the networks will be hardcoded in on swaps ?
