### ISSUE TITLE
Browser crash when selecting 'Send to your devices'

### ISSUE THREAD

**Issue by anshumanpati6** [brave/brave-browser#21035]
## Description 
Brave crashes when clicking on send to device in Android.

## Steps to reproduce 

   1. Open the menu
   2. Click on share
   3. Select 'send to your devices'

## Actual result 
Browser crashes.

## Expected result
Should show list of other devices to send the tab to.

## Issue reproduces how often 
Easily reproduced.

## Version/Channel Information:

Brave Android Stable Channel 1.35.100

- Can you reproduce this issue with the current Play Store version? 
- Yes

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.35.100

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards?
- No
- Is the issue reproducible on the latest version of Chrome? 
- No

**Comment by srirambv** [comment]
Can you submit the crash report via `brave://crashes`and share the crash ID here? Make sure you enable the send crash reports in settings 

cc: @SergeyZhukovsky

**Comment by anshumanpati6** [comment]
Crash ID - 028b0100-251c-ba07-0000-000000000000

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.102 x64 build
- Verified enabling Sync everything shows the device when `Send to devices` is selected
- Verified able to send the open tab to other device in sync chain 
- Verified other devices in sync chain receive the open tabs that are sent via Sync
- Verified no crash on either devices in Sync chain when an open tab is sent
- Verified no crash on sending device when the receiving device is offline

**Comment by Uni-verse** [comment]
Verification completed using `Brave 1.35.102, Chromium 98.0.4758.102`

Device: `Samsung Galaxy S21` / `Android 12`

- Verified no crash occurs when user selects and opens 'Send to Devices' share option
- Verified synced devices show up in 'Send to Devices'
- Verified selected devices successfully receive the open tab link
- Verified no crash on sending device when the receiving device is offline

Tx | Rx
-|-
![Screenshot_20220217-043642_Brave](https://user-images.githubusercontent.com/17885425/154361448-1b489a92-63bf-46c8-9d2f-abb098adbd74.jpg) | ![Screen Shot 2022-02-16 at 1 37 51 PM](https://user-images.githubusercontent.com/17885425/154361410-5d7acb9c-66d2-4c02-a840-8b1fe0b94e5c.png)

**Comment by marc0der** [comment]
Hi all! This issue seems to be back in 1.37.110. The browser crashes consistently every time I send to my devices from my Google Pixel 5.

**Comment by steveharman** [comment]
> Hi @srirambv! This issue seems to be back in 1.37.110. The browser crashes consistently every time I send to my devices from my Google Pixel 5, Android 12. Please shout if I can do anything to help reproduce the issue.

Same issue is back for me too, same version (Android)

**Comment by samartnik** [comment]
New issue was created for this one https://github.com/brave/brave-browser/issues/22128
Should be fixed in version `1.37.113` of higher.
