### ISSUE TITLE
State-level ad targeting setting is not shown after regional format changes

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#21038]
Steps to reproduce:

- Set `State-level ad targeting` browser setting value to `Indiana` (or any value except `Auto-detected`)
- Change `Regional format` Windows setting to `English (Australia)`. Restart the browser.
- `State-level ad targeting` browser setting becomes hidden. This is expected.
- Change `Regional format` Windows setting back to `English (United States)`. Restart the browser again.

## Actual result:
- `State-level ad targeting` browser setting remains hidden.

## Expected result:
- `State-level ad targeting` browser setting becomes visible.

## Reproduces how often: 
Easily reproduced

**Comment by btlechowski** [comment]
`QA/Blocked ` by https://github.com/brave/brave-browser/issues/24313

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.42.83 Chromium: 104.0.5112.69 (Official Build) (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

### locale change

#### locale: `US`, geo: `US-CA` 
![image](https://user-images.githubusercontent.com/34715963/181822080-454f871d-585d-46a3-b49d-5027275d5e24.png)

#### locale: `PL`, geo: `US-CA` 
![image](https://user-images.githubusercontent.com/34715963/181822643-a7626443-917d-4ae2-9b21-ba59b6c077d5.png)

#### locale: `US`, geo: `US-CA` 
![image](https://user-images.githubusercontent.com/34715963/181822818-5083afd8-8771-446b-aa48-06db16fc17b4.png)



### geo changed
#### locale: `US`, geo: `US-CA` 
![image](https://user-images.githubusercontent.com/34715963/181822818-5083afd8-8771-446b-aa48-06db16fc17b4.png)


#### locale: `US`, geo: `PL-02` 

![image](https://user-images.githubusercontent.com/34715963/181823464-a32c6d80-187c-48e3-8092-74e84b647fac.png)

#### locale: `US`, geo: `US-CA` 
![image](https://user-images.githubusercontent.com/34715963/181823759-ba71b4fa-f931-4e43-aca6-ad6644e2d490.png)
