### ISSUE TITLE
P3A_Follow up of #18394 - Rewards enabled duration cannot be tested on Android until the rewards reset issue is fixed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21043]
## Description 

P3A_Follow up of #18394 - Rewards enabled duration cannot be tested on Android until the rewards reset issue is fixed
## Steps to reproduce 

   1. Clean profile 1.36.x
   2. Enable rewards
   3. Set the system date ahead by a week or a day
   4. Disable/reset rewards
   5. Unable to reset rewards in Android, which is known, and  issue is already logged https://github.com/brave/brave-browser/issues/8776
   6. Unable to test the Rewards enabled duration due to #8776 

## Actual result 

Rewards enabled duration cannot be tested on Android until the rewards reset issue is fixed
## Expected result
Should be able to test the issue once #8776 is fixed

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): on both ARM and Tab
   - Android version:
   
## Brave version
1.36.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? na
- Does the issue resolve itself when disabling Brave Rewards? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional information

cc: @brave/legacy_qa @Miyayes @rillian @srirambv

**Comment by Miyayes** [comment]
Given https://github.com/brave/brave-browser/issues/21232, I think this will no longer apply. 

My intuition is that "resetting Brave Rewards" doesn’t count as disabling Brave Ads, because the user is probably resetting Brave Rewards for a different reason, and therefore it's not exactly the kind of behavior we’re interested in knowing about (namely, the user going and explicitly disabling Brave Ads). cc: @rillian
