### ISSUE TITLE
Make custom network fields readonly when its set as default

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21047]
## Description 
To avoid confusion of being editable, when a custom network is set as default, make the fields readonly so user doesn't try to edit it.

## Steps to reproduce 

   1. Install 1.37.42 nightly build
   2. Create a custom network entry and set it as default
   3. Open Wallet Settings from Wallet menu and select network
   4. Tap on the network to open details
   5. Tap on a field, brings up keyboard to edit but doesn't allow to save it

## Actual result 
Custom network fields look editable but can't save it when its set as default network

## Expected result
Make custom network fields readonly when its set as default

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version:all
   
## Brave version
1.37.42

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @Pavneet-Sing

**Comment by Uni-verse** [comment]
Verified on `Samsung Tab S7` & `Samsung GS 21` running `version 12` using

```
Brave	1.41.94 Chromium: 103.0.5060.114 (Official Build) (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Android 12; Build/SP1A.210812.016
```

Use Case 1: Add custom network via DApp (chainlist.org)

- Confirmed custom network is readonly when set as active
- Confirmed user can edit network and submit new changes when its not active
- Confirmed when custom network can be edited will be indicated by the 3 dot menu

Use Case 2: Manual entry of custom network

- Confirmed readonly when set as active
- Confirmed user can edit, remove and set as active when network is not default. New changes can be submitted. 
- Confirmed when custom network can be edited will be indicated by the 3 dot menu

Network Info | Custom Networks
-|-
![screenshot-1657243552529](https://user-images.githubusercontent.com/17885425/177899375-53ddc1b5-f238-4adc-9eb3-54cb7a2a229d.png) | ![screenshot-1657243724815](https://user-images.githubusercontent.com/17885425/177899379-64f460ef-89a3-49ea-8dbf-8e9f5607dbba.png)
![screenshot-1657245346380](https://user-images.githubusercontent.com/17885425/177901137-5ceda4a4-35d1-4786-a99c-8f4048284c0e.png) | ![screenshot-1657245370974](https://user-images.githubusercontent.com/17885425/177901142-1ed25c8d-e8bd-4cd8-84d1-b8a877901723.png)
