### ISSUE TITLE
Brave sync be ready to receive bookmark before folder

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#2104]
## Description 

Android team and iOS team mentioned it is possible to receive bookmark created sync record before parent bookmark folder created record. In this case in brave-core the bookmark will remain orphaned. Never see this situation with brave-core.

## Steps to Reproduce

No steps to reproduce it for sure.
May be emulated with auto-test.

## Actual result:

The bookmark remains orphaned. Folder is created after and remains empty.

## Expected result:
After arriving folder created record, child bookmark should be moved into. Or if folder and bookmark arrived in the same list, list should be sorted by time, as Android browser does.

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}

**Comment by AlexeyBarabash** [comment]
This is a duplicate of https://github.com/brave/brave-browser/issues/2133 .

**Comment by darkdh** [comment]
close this issue because we need QA verifying #2133
