### ISSUE TITLE
Button padding too large on wallet form

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#21056]
## Description 
Button padding too large on wallet form

https://github.com/brave/brave-browser/issues/20962

## Steps to reproduce 

1. Tap menu > settings
2. Select Brave Wallet
3. Create wallets, skip back up
4. From the wallet dashboard, access the settings menu
5. Select Networks
6. Select + Add Network
7. Observe the button of the add network form

## Actual result 
Button too bulky for the text

![Screenshot_20220211-232400_Brave - Nightly](https://user-images.githubusercontent.com/17885425/153641084-5cee9100-e0f1-4b71-b94e-9a1fa00c050f.jpg)

## Expected result
Padding should be reduced around the text

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy S21 `(2400x1080)
   - Android `version: 12`
   
## Brave version
`1.37.42, Chromium 98.0.4758.87`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Uni-verse** [comment]
Reproduced on `Samsung Galaxy S21 `running `Android 12` using version `1.40.75, Chromium 102.0.5005.61`

- Button still looks fat but is now center-aligned and contains margin between the bottom of the page. 

Add Network Form | Version
-|-
![screenshot-1654188070613](https://user-images.githubusercontent.com/17885425/171681939-b80cd55b-b881-4e68-950b-69dfb1df84ba.png) | ![screenshot-1654188090248](https://user-images.githubusercontent.com/17885425/171681943-563810b1-7ab7-4f1f-97c7-5047c4419824.png)

**Comment by srirambv** [comment]
cc: @jamesmudgett

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.105 x64 build
- Verified button is as per [spec ](https://www.figma.com/file/jZrVG7dsi5npXFTDC6LDGn/Crypto?node-id=0%3A1)

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/174725237-45e0f2ba-f30f-41b0-ba01-09a40f725fdc.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/174725253-932209f3-ae78-48f7-9c34-27b1cccb97dd.png>

@Uni-verse the button seems to be as per spec. Please open a new issue for design discussion on different use of button styling and cc @jamesmudgett and @minkyeongshin
