### ISSUE TITLE
Update toast notification background color in Rewards panel (Feb 2022)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21058]
## Description

- [ ] Change toast notification background color 
- [ ] Change color of: https://github.com/brave/brave-browser/issues/21058#issuecomment-1036512669

Update to darker background color:

![image](https://user-images.githubusercontent.com/11497541/153650173-9bb60efe-057a-4aaa-8072-904607d1417c.png)

Applies to the background color of _all_ toast notifications, not just the one pictured above.

Previous, as reference:

![image](https://user-images.githubusercontent.com/11497541/153650208-e853e068-2919-4b77-af19-79b860f47c43.png)

**Comment by minkyeongshin** [comment]
Can we also change the x button color from #5E6175 to #84889C? To make this button more visiable? I updated button color on the Figma file 
https://www.figma.com/file/ag8i1OV5vpvn4SiOhW2c0f/Github-fixes?node-id=0%3A1

**Comment by minkyeongshin** [comment]
<img width="536" alt="Screen Shot 2022-02-11 at 10 48 45" src="https://user-images.githubusercontent.com/86380734/153651548-16fcbe89-edc3-4d37-9105-f53606a2962b.png">

**Comment by umeshthakre** [comment]
Hello sir, I am new to opensource and would like to contribute to this project. can you please explain me what needs to be done

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)
```
