### ISSUE TITLE
Wire up Add Solana Account to UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21054]
## Description 
1. Wire up the `AddAccount` method in the UI to allow adding a `Solana` account.
2. Use `GetWalletInfo` method to get `Solana` account information and display it in the UI.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.37.84 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12236> brave/brave-core#12236</a></li>
         <li>Verified create an account lists Solana as an option for creating a new account</li>
         <li>Verified Solana option is listed for <code>Create Account</code>, <code>Import</code>, <code>Import from hardware wallet</code></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td><b><code>brave://flags/#brave-wallet-solana</code></b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/157391120-5b141d89-ac70-4391-8a91-d7c1fc74284c.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/157390582-22fe8d45-c728-4b62-b0b1-25af301a6fdb.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/157390003-b5a276bf-f3de-4f0f-9834-5c217f2f402c.png>
      </td>
   </tr>
   <tr>
      <td><b>Create Account</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/157391133-0bb3122c-62c2-4dfe-9394-68ec8b6ef2ee.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/157390619-c239db93-a6fc-4b1a-bd8f-1f6d9318bbd1.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/157390043-e6d7eeb9-01c7-4417-ab63-1034505a196b.png>
      </td>
   </tr>
   <tr>
      <td><b>Import</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/157391161-71d0f152-3c38-4d47-a504-4be59003c83e.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/157390654-b35925c0-1bd0-4eee-a668-1e6f3342541b.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/157390068-adce0ddb-4322-4860-97db-9401a81b0eb0.png>
      </td>
   </tr>
   <tr>
      <td><b>Import from hardware wallet</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/157391175-0873716c-7a1d-44f4-a382-c52f18596279.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/157390690-c7878c27-3eb9-4f92-b055-5121f44f2b02.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/157390089-10d81f6e-a3b9-46af-99c6-e6ab251e7dfc.png>
      </td>
   </tr>
</table>
