### ISSUE TITLE
Dropped transactions are never retired in our Wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#21051]
During a Zoom call with a user here:
https://community.brave.com/t/unable-to-send-funds-out-of-brave-wallet/335479/20

We seen that he had a transaction in his transaction list that was "Pending" but on Etherscan it was "Dropped".  
Our UI keeps it at Pending because it never gets Confirmed. 
A dropped transaction can happen when the fees are too low and miners need room in their mempool. They will never be re-picked up unless the transaction is re-broadcast. 
https://info.etherscan.com/transaction-dropped-replaced/

This suggests we should have a way to re-broadcast a transaction.  When that option is selected, our panel should also have an in UI message that gas fees are configured too low and will likely be dropped.  That message can be given even for new transactions when a user manually edits their gas fees to something that doesn't make sense vs the current gas values.  

Also we should surface the pending transactions more because they can be hard to find for users.  All future transactions will remain pending if one is pending because the nonce must be sequential. E.g. something like if there's a new transaction being made and there's an old pending one older than a day, we should warn and ask if the user would like to remove that transaction locally.

**Comment by jamesmudgett** [comment]
![eb0d0a64fd57526339bc2537d3503788af609e09](https://user-images.githubusercontent.com/318119/153985003-e8aa6d74-cdf2-40fc-802c-7c17bc6cddc4.png)

@rmcfadden3 

We need to find a better way to communicate the following:
- A pending transaction that is not going through (gas issue) is likely to prevent future send transactions from going through.
- The failing "pending" transaction needs to be cancelled before a new one may be sent, or it will need to be completed.

There are a couple of approaches:
1. A new transaction can be "forced" but will require that we perform some things in an automatic way and this will probably not be desireable.
2. Update the messaging and link to pending list, something like, "We have detected a pending transaction that has not yet completed and will prevent this transaction from executing. View pending transactions"

**Comment by jamesmudgett** [comment]
Will need to also query that the "Submitted" transaction are > 1day old (24hr) before showing this message
![Screen Shot 2022-02-24 at 11 50 06 AM](https://user-images.githubusercontent.com/318119/155582135-cd1a05b9-27d5-484d-8074-ffd3623a3123.png)

**Comment by jamesmudgett** [comment]
@rmcfadden3 can you check over message formatting, and provide any edits?

**Comment by bbondy** [comment]
> Will need to also query that the "Submitted" transaction are > 1day old (24hr) before showing this message

To clarify: If any "Submitted" transaction exists > 1 day old.

**Comment by rmcfadden3** [comment]
@jamesmudgett — per our Zoom just now, here's some proposed copy for that panel message:

**Transaction backlog**

You're attempting to start a new transaction while you have previously submitted transactions that have not been processed. This incomplete transaction will block any new ones from being submitted. Learn more.

[] Clear & replace the incomplete transaction(s)

**Comment by bbondy** [comment]
Pls say confirmed instead of processed

**Comment by rmcfadden3** [comment]
@jamesmudgett — per @bbondy, here's updated copy:

**Transaction backlog**

You're attempting to start a new transaction while you have previously submitted transactions that have not been confirmed. This will block any new ones from being submitted. Learn more.

[] Clear & replace the incomplete transaction(s)

**Comment by simoarpe** [comment]
@bbondy , @Douglashdaniel is this issue still open?
[Last comment ](https://github.com/brave/brave-core/pull/12439#issuecomment-1585057407) in https://github.com/brave/brave-core/pull/12439 states the issue has been addressed.

Context: I was checking the Android counterpart https://github.com/brave/brave-browser/issues/21305.

**Comment by Douglashdaniel** [comment]
https://github.com/brave/brave-core/pull/12439#issuecomment-1585057407
