### ISSUE TITLE
Tipping doesn't do anything

### ISSUE THREAD

**Issue by junkguy** [brave/brave-browser#2106]
## Description 
Tipping lets you go through the process to send a tip, but wallet's BAT amount doesn't change and the tip is not listed in brave://rewards/

## Steps to Reproduce

   1. In brave://rewards/, restore a wallet from a recovery key.  The wallet has previous user grants, but is not self funded.
   2. On any site, click the rewards icon, click "Send A Tip...", select any amount of BAT, click "Send my tip"
   3. "Thank You" popup appears.
   4. Overall BAT amount is unchanged.

## Actual result:
   BAT amount is unchanged after tipping.  On brave://rewards/, "Tips" section is empty

## Expected result:
   BAT amount should be deducted by the tipped amount.

## Reproduces how often: 
   Always (when using a restored wallet.  Haven't tried with a new wallet)

## Brave version (brave://version info)

Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Don't know

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No

- Is the issue reproducible on the latest version of Chrome? 
N/A

### Additional Information
The restored wallet was from the Muon version of Brave.

**Comment by LaurenWags** [comment]
Hey @junkguy - I'd like to get some additional information from you so the team can investigate but some of it is sensitive (it pertains to your wallet). Are you a member of our community (community.brave.com)? You can DM me there - I'm LaurenWags on community as well. Or if you're on Twitter, my handle is bravelaurenwags and we can DM there.

**Comment by Brave-Matt** [comment]
+1 for this but I'm not sure if this is a widespread issue or specific to some users:
https://www.reddit.com/r/brave_browser/comments/9vmn4y/brave_version_05612_now_available_on_release/e9mxnrm/?context=3&utm_content=context&utm_medium=message&utm_source=reddit&utm_name=frontpage

**Comment by eljuno** [comment]
+1s from Community https://community.brave.com/t/brave-rewards-for-publishers/37390?u=eljuno

**Comment by rebron** [comment]
We think users from 55.22.x upgrading to 56.x are experiencing this issue. Would like to get this fixed for 0.57.x

**Comment by NejcZdovc** [comment]
@kjozwiak @LaurenWags do we have STR for this one?

**Comment by LaurenWags** [comment]
@NejcZdovc I connected with the OP. seems like their wallets are now allowing them to tip. I'm wondering if at the time of attempting to tip there was a server issue which prevented them from doing so, which we've experienced before. So, it seems like we might be better served by putting in some kind of notification which lets users know that the server is unable to complete their tip request at present time. I did some looking and I'm wondering if this issue https://github.com/brave/brave-browser/issues/1481 cover that scenario? cc @kjozwiak

**Comment by LaurenWags** [comment]
@NejcZdovc doesn't that have potentially sensitive info on my wallet?

**Comment by NejcZdovc** [comment]
@LaurenWags is this not staging testing wallet?

**Comment by LaurenWags** [comment]
@NejcZdovc no, this was on Production.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/send-a-tip-function-not-working/38958?u=eljuno

**Comment by kiwina** [comment]
`PUT /v2/wallet/xxxxxxxxxxx`
`{"statusCode":400,"error":"Bad Request","message":"Response Error: 400 Bad Request"}`

**Comment by LaurenWags** [comment]
Logged https://github.com/brave/brave-browser/issues/2453 to improve error flow for tipping.

**Comment by Biglulux** [comment]
I also have an issue where tipping doesn't work, where in some cases I don't get the option to tip at all for some websites. It seems to be random. The tip button also appears for some YouTubers, but not for others. Their verified status does not seem to make a difference. For example, I can tip GitHub (and GitHub is not verified) right now, but I cannot tip Google.
Version: Version 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit). Live release.

**Comment by NejcZdovc** [comment]
closing as stale
