### ISSUE TITLE
Swap Container Dynamic Sizing Bug

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21061]
## Description 
Currently there is a styling bug with the `Swap` container that is not allowing it to dynamically grow when errors are shown.

![Screen Shot 2022-02-11 at 12 15 05 PM](https://user-images.githubusercontent.com/40611140/153655527-c494a47b-fdb0-4cea-984e-da5bb24e81dc.png)

**Comment by Uni-verse** [comment]
Verification completed using

```
Brave	1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64) 
Revision	5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS	macOS Version 12.1 (Build 21C52)
```
-  Expanding/collapsing slippage field does not overflow text
-  Generating slippage error does not change ui/overflow

set slippage | expand/collapse
-|-
<img width="329" alt="Screen Shot 2022-03-29 at 2 21 00 PM" src="https://user-images.githubusercontent.com/17885425/160709704-f9961025-fe14-4b6b-9857-5613558e62f8.png"> |<img width="320" alt="Screen Shot 2022-03-29 at 2 21 18 PM" src="https://user-images.githubusercontent.com/17885425/160709706-595d34db-dfb1-403f-b153-bd7bf152c4c7.png">
