### ISSUE TITLE
Some characters are not shown properly on the Rewards panel [follow up to #19594]

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#21062]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/19594

Characters in some creator names aren't displaying properly on the panel.

## Steps to Reproduce

   1. Clean profile, production
   2. Enable rewards
   3. Visit the below sites and open the panel:
   - https://vimeo.com/user23166500
   - https://vimeo.com/soniglf
   - https://vimeo.com/agorgec

## Actual result:

Example | Example | Example
----- | ----- | -----
<img width="430" alt="A" src="https://user-images.githubusercontent.com/28145373/153666865-2dbf5467-6928-40e1-8978-1c31446273de.png"> | <img width="430" alt="B" src="https://user-images.githubusercontent.com/28145373/153666875-19c1975f-cd32-46ce-b9aa-f1d58dacbfe4.png"> | <img width="434" alt="C" src="https://user-images.githubusercontent.com/28145373/153666884-0c1d2b81-d76b-45f6-9e81-f9e8af889063.png">

## Expected result:

Creator names to be displayed properly

## Reproduces how often: 

easily

## Desktop Brave version:

Brave | 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.2.1 (Build 21D62)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by Miyayes** [comment]
# Verified / passed

Used `Brave Local Data Updater - Version: 1.0.691` which contains the fix as confirmed by @emerick.

Version: 1.46.144 Chromium: 108.0.5359.128 (Official Build) (x86_64) launched prior using `--use-dev-goupdater-url`

Using test cases in issue:

![image](https://user-images.githubusercontent.com/11497541/208528983-6aff83e9-0427-4aaf-b799-27735fc40e8f.png)

![image](https://user-images.githubusercontent.com/11497541/208529001-ce34a7f9-0b79-47a4-ab82-009a503cc729.png)

![image](https://user-images.githubusercontent.com/11497541/208528952-eb591895-dee5-47e1-a5db-bc15eae97bce.png)

# Regression tests (passed)

Trying some other "normal" Vimeo channels (without character issues)

![image](https://user-images.githubusercontent.com/11497541/208529152-1d37f14d-7a75-4e0e-9feb-29756477c9c5.png)

![image](https://user-images.githubusercontent.com/11497541/208529192-b7c5224a-67f8-4acf-b7bf-0bd8e7a8a667.png)
