### ISSUE TITLE
Settings icon should have Show Sidebar options, instead of opening the Settings window

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21060]
## Steps to Reproduce

   1. install `1.37.43`
   2. launch Brave
   3. load `brave://flags`
   4. set `Enable Sidebar` to `Enabled`
   5. click to `Relaunch`
   6. click on the `Settings` gear icon on the bottom left

## Actual result:

It goes to `brave://settings`

<img width="1676" alt="Screen Shot 2022-02-11 at 10 57 12 AM" src="https://user-images.githubusercontent.com/387249/153652738-f3c61053-a002-4cb3-9c49-696b32f0ee9a.png">

## Expected result:

brave://settings/?search=sidebar

<img width="720" alt="Screen Shot 2022-03-15 at 12 03 49 AM" src="https://user-images.githubusercontent.com/5951041/158324214-e48fa6a5-9b1b-4c28-95ac-81b83146f37c.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.43 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

**Comment by rebron** [comment]
cc: @bradleyrichter @simonhong

**Comment by bradleyrichter** [comment]
I think the original plan was to take the user to the sidebar settings panel in the main settings UI. Assuming we can deep link there, I think this would provide more flexibility.

**Comment by simonhong** [comment]
@bradleyrichter @rebron How about using brave://settings/?search=sidebar for this button's target?
@stephendonner `On click` optoin will be removed via https://github.com/brave/brave-core/pull/12161

**Comment by kjozwiak** [comment]
Above issue requires `1.37.98` or higher for verification on `1.37.x`.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.37.98 Chromium: 99.0.4844.74 (Official Build) beta (64-bit)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the STR from the description and ensured, click on `Show settings` in the sidebar opens up the Show sidebar options
![image](https://user-images.githubusercontent.com/38657976/158989833-5d1f8d08-4431-4896-b4fe-414606060de6.png)
