### ISSUE TITLE
Auto-contribute percentages are incorrect as they are not adding up to 100% when "Show non-verified sites in list" is toggled off in brave://settings/rewards

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#21065]
## Description 

<details>
<summary>Auto-contribute percentages are incorrect as they are not adding up to 100% when "Show non-verified sites in list" is toggled off in brave://settings/rewards </summary>

## Steps to Reproduce

1. Clean profile 
2. Launch Brave
3. Skip welcome tour
4. Change to staging env in QA prefs
5. Enable Rewards
6. Open a non- verified site - https://twitter.com/
7. Stay on the site to record the attention percentage (80%)
8. Visited a verified site -[twitter.com/emerick](http://twitter.com/emerick)
9. Recorded percentage (17%)
10. Visited one more non verified site (cnn.com)
11. Recorded percentage (7%)
12. Toggle off "Show non-verified sites in list" in brave://settings/rewards
13. Click Brave Rewards in the navbar

## Actual result:
Emerick on Twitter (twitter.com/emerick) percentage was 13%
</details>

Example | Example | Example
----- | ----- | -----
<img width="430" alt = "Screenshot 1- verified and non verified sites add up to 100 percent" src = "https://user-images.githubusercontent.com/98358127/153684436-5dfadf4d-395e-4abd-9fad-28c4526b7037.png"> | <img width = "430" alt = "screenshot 2 -toggle off settingsrewards" src = "https://user-images.githubusercontent.com/98358127/153684548-e474ffe0-30c8-4c00-af28-2ea7dcc51350.png"> | <img width = "430" alt = "screenshot 3- auto-contribute percentage was incorrect" src = "https://user-images.githubusercontent.com/98358127/153684562-d65f303a-15a6-424c-b4e7-959324069828.png">

## Expected result:
Emerick on Twitter (twitter.com/emerick) should display 100%

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.35.101   Chromium: 98.0.4758.87 (Official Build) (64-bit)
-- | --
Revision |   e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS  | Windows 11   Version 21H2 (Build 22000.493)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

cc @Miyayes @brave/legacy_qa

**Comment by zenparsing** [comment]
Note that the percentages appear to readjust when setting is changed from the rewards page.

**Comment by LaurenWags** [comment]
@MadhaviSeelam I believe the comment from @zenparsing under https://github.com/brave/brave-browser/issues/21065#issuecomment-1041921564 is correct based on our discussion. However, could you double check when you have a moment?

**Comment by MadhaviSeelam** [comment]
This is working as expected i.e. Auto-contribute percentages are correct and adding up to 100% if "Show non-verified sites in list check box is unchecked in Auto-Contribute Settings in Brave://rewards.  Closing the issue.

Example 
---------
<img width="323" alt="Verified list -100%" src="https://user-images.githubusercontent.com/98358127/155229158-84c5615f-03df-4a3a-b03c-c1e9833dcb3f.png">
