### ISSUE TITLE
Unexpected end of JSON input - YouTube Thumbnail Error

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#2107]
## Description 

Whenever I try to change my YouTube's thumbnail picture, I just can't and gives mt this error: "Unexpected end of JSON input"

## Steps to Reproduce

   1. Upload A Video To YouTube
   2. Go To YouTube Studio (Old one)
   3. Try to change the thumbnail

## Actual result:

![image](https://user-images.githubusercontent.com/8920923/48369489-62786700-e6bf-11e8-9002-3d463746921a.png)

## Expected result:
![image](https://user-images.githubusercontent.com/8920923/48369582-a4a1a880-e6bf-11e8-9681-aac131b5a06a.png)

## Reproduces how often: 

Everytime, it's not working

## Brave version (brave://version info)

0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
I don't know
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by srirambv** [comment]
I couldnt reproduce the error. Could you try recording a video of this using [Licecap](https://www.cockos.com/licecap/).

**Comment by havokenterprises** [comment]
I also have this issue when uploading youtube videos. It works fine in Chrome.

**Comment by pvfpvf** [comment]
I believe this problem is not browser-specific. It happens to me all the time using Chrome. It is affecting quite a lot of youtube creators, but obviously not the majority or youtube would have noticed it. It is probably a bug in youtube's client Javascript or in their server code. The error is obviously given by json.parse but in what context I don't know.

**Comment by VikOlliver** [comment]
FYI It happens when I use Chromium too.

**Comment by allenfonseca** [comment]
Changing my 3rd-party cookies worked for me.

A lot of the time when a website's functionality isn't working for me, I find temporarily changing my cookie settings will make it work.

In Chrome: Settings -> Advanced -> Content Settings -> Cookies -> Block Third-Party Cookies (Turn this off, then back on if you would like after you are finished).

Hope this helps!

**Comment by pvfpvf** [comment]
Thanks, Allen. I just tried that. It does stop the explicit JSON error message, but the upload still doesn't happen and instead I get this error in Chrome browser. Probably some other security feature in newer Chrome browsers. It's just a bit annoying that Google owns youtube, Google tightens Chrome security and encourages us to use it, and they can't even get their own software to work with it!
![youtube_json_err](https://user-images.githubusercontent.com/29895975/55674148-8c1d6f00-58a8-11e9-9281-fbe04d895aec.jpg)

**Comment by NightTerrors-B** [comment]
I got this error because while my YouTube video was uploading, I WAS DOING OTHER WORK, AND I SWITCHED MY GOOGLE ACCOUNT TO THE GOOGLE ACCOUNT OF MY FATHER.  When I switched the account back, and I attempted to change the thumbnail, I was successful. I no longer received the error "Unexpected end of JSON input".

**Comment by h00diesoul** [comment]
Hey. Just had exactly same issue myself. Workaround: do it in Firefox. I'm not sure what's happening behind the scenes, but this worked.

**Comment by pvfpvf** [comment]
Neither solution suggested by NightTerrors-B or h00diesol fixes it for me. I've always been able to use Studio beta to change the trhumbnail after upload has finished. And I think I'm logged in correctly to Google and Youtube.

**Comment by VikOlliver** [comment]
Yeah, I have to resort to Studio Beta too.

**Comment by glewisut** [comment]
I had the same issue because I was switched to a different account in a different tab.  Once I switched back, no problemo.

**Comment by sanles1** [comment]
Issue was fixed when i used a different browser

**Comment by irawatpravin** [comment]
hi,
I have solved the problem. First of all read the terms and conditions of the thumbnail.
Switch You YouTube account to STUDIO BETA. and then click on your video that you want to add thumbnail. now upload thumbnail and its done. Dont thank me You can subscribe my channel its 
https://www.youtube.com/channel/UClLGKXetgERax9gHzhRLn7Q?view_as=subscriber

**Comment by ManulMax** [comment]
I tried different file formats. but couldn't be able to solve it.
