### ISSUE TITLE
when taping open in new tab for youtube and some sites , it opens the mobile version

### ISSUE THREAD

**Issue by fsheidaiee** [brave/brave-browser#21077]
## Description 
even when I enable desktop version in site settings, when taping open in new tab for youtube (from google results) and some sites , it opens the site in mobile version
## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Please update to 1.35.101 when available. This is fixed as part of #20963. Closing as invalid
