### ISSUE TITLE
Rewards is off but still getting notifications

### ISSUE THREAD

**Issue by unlucio** [brave/brave-browser#21072]
## Description 
Even tho I turned the Rewards program off, I still get ADV notifications (and it doesn't even give me any token)
<img width="1117" alt="Screenshot 2022-02-13 at 18 31 46" src="https://user-images.githubusercontent.com/778799/153767292-be54ae0b-d435-4024-a4a9-f39e734c8515.png">

## Steps to Reproduce
   1. Turn "Brave private ads"
   2. Verify you still get spammy/scammy stuff
   3. Be annoyed

## Actual result:
I'm still getting targeted and receive ADV notifications

## Expected result:
Not been bothered by ADV notifications any more

## Reproduces how often: 
Once turned it off even one single notification would been too much.

## Brave version (brave://version info)

Brave | 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.1 (Build 21C52)
JavaScript | V8 9.8.177.9
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/lucio/Library/Application Support/BraveSoftware/Brave-Browser/Default
Linker | lld
Variations | AdRewardsStudy:NextPaymentDayBraveDebounceStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledForceDisableBlinkFeatures:EnabledMacCoreLocationBackendStudy:EnabledNativeCosmeticFilteringStudy:EnabledNavigationThreadingOptimizationsCompat:DefaultPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Disabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? idk
- Can you reproduce this issue with the nightly channel? idk

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? The problem happens when I disable Brave Rewards
- Is the issue reproducible on the latest version of Chrome? Chrome doesn't have this feature

## Miscellaneous Information:
While I enrolled in the program finding it a good idea, I was very disappointed for being flooded by scam/phishing stuff so I had to turn it off. So still getting that spam is double anoying.

**Comment by btlechowski** [comment]
I am unable to reproduce on Ubuntu

Brave | 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit) 
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Ubuntu 18.04 LTS

Notification ads were not shown when Brave ads is disabled in `brave://rewards` 

Brave ads disabled in `brave://rewards` and Brave News disabled
```
[13882:13882:0215/094931.697834:VERBOSE1:ads_service_impl.cc(1771)] P2A histograms suspended
[13882:13882:0215/094931.698197:VERBOSE1:ads_service_impl.cc(697)] Shutting down ads
[13882:13882:0215/094931.720197:VERBOSE1:ads_service_impl.cc(713)] Successfully shutdown ads
```

Brave ads disabled in `brave://rewards` and Brave News enabled
```
[2446:2446:0215/100807.488442:VERBOSE1:ads_impl.cc(213)] Browser state changed to idle
[2446:2446:0215/100810.497253:VERBOSE1:ads_impl.cc(229)] Browser state changed to unidle after 17 s
[2446:2446:0215/100811.461270:VERBOSE1:browser_manager.cc(65)] Browser window is inactive
```

**Comment by tmancey** [comment]
@unlucio we cannot reproduce. Would you be available for a screen-share so we can look into this further? Thanks, Terry

**Comment by unlucio** [comment]
@btlechowski @tmancey indeed is not systematic, but more sporadic and it kinds of look random.
Yes I would be available for a call on CET time.

Feel free to email me @gmail.com (same name).

**Comment by tmancey** [comment]
@unlucio do you have multiple profiles? If so, can you please check if ads are enabled on another profile. Thank you, Terry

**Comment by unlucio** [comment]
@tmancey yes I have, and yes they're off.
<img width="374" alt="Screenshot 2022-02-19 at 17 23 42" src="https://user-images.githubusercontent.com/778799/154809463-2109364f-86ac-4349-9537-3784896be682.png">
and I just got another one
(and the fact they're pretty much all scams is kind of very disappointing)

**Comment by tmancey** [comment]
@unlucio if you could email me at terry@brave.com with suitable times and I will reply with a link so we can investigate further. My timezone is GMT-5. Thank you
