### ISSUE TITLE
Payout issue

### ISSUE THREAD

**Issue by achapkowski** [brave/brave-browser#21074]
The January payouts never happened, what do I do?

I have tried multiple avenues but have received no responses.

**Comment by Miyayes** [comment]
I would try https://community.brave.com or /r/BATProject on reddit. You can also DM me your brave://rewards-internals (general info tab) on Reddit. My account is /u/bat-chriscat. You'll need to send the right information to the support team for them to handle your case.

**Comment by achapkowski** [comment]
Thank you
