### ISSUE TITLE
[Android] Add error messaging when ad earnings cannot be claimed due to Android SafetyNet failure

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21076]
## Description

Refer to designs and text (@Miyayes). 

_________________

**If user is claiming via Rewards panel**

1. User presses to claim ad earnings
2. If device fails SafetyNet, pop up an error toast notification with the following test: TBD

**If user is claiming via Brave Rewards settings page**

1. User presses to claim ad earnings
2. If device fails SafetyNet, pop up an error modal on the Rewards settings page with the following text: TBD

**Comment by Miyayes** [comment]
cc: @rmcfadden3 @anthonypkeane @timchilds Text suggestions here would be appreciated.

**Comment by rmcfadden3** [comment]
@Miyayes — do you have design mocks or anything for this (even if they just have placeholder text)? That would give me a feel for how much real estate we're working with.
