### ISSUE TITLE
Investigate and fix Arbitrum transaction failures

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#21084]
## User reports

* https://community.brave.com/t/unable-to-send-eth-arbitrum-chain/317080/10
* https://community.brave.com/t/unable-to-send-funds-out-of-brave-wallet/335479/21
* https://community.brave.com/t/brave-wallet-not-allowing-0-gas-price-on-arbitrum-test-network/308777/13

### Finding 1

Default gas limit for simple `AETH` transfers is always **`21000`**.

<img width="256" alt="Screenshot 2022-02-14 at 8 53 07 PM" src="https://user-images.githubusercontent.com/3684187/153892438-28effa7d-34ae-4264-bb4e-04c5ba3eb82b.png">

🔴 Gas limit on Arbitrum mainnet is typically **`500,000`**. See [example](https://arbiscan.io/tx/0x6170cee694eadfffe654935a49dbf29c597133586beae6ed2110fbc428cb5d5e).

### Finding 2

Unsuspecting users who publish transactions with **`21000`** gas, do NOT get helpful error messages from the Arbitrum client.
They get **not enough funds for gas** instead of something like "gas limit not enough".

### Finding 3

The `eth_estimateGas` RPC method behaves a bit differently compared to Ethereum's JSON-RPC spec. Example:

**With the `TAG` param ("latest"):**

```
$ curl -s https://arb1.arbitrum.io/rpc -X POST -H "Content-Type: application/json" -d '{"id":1,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0xa92D461a9a988A7f11ec285d39783A637Fdd6ba4","to":"0xbc5d6cd6f7225bfCCc58F7B75AaeB641ECCD5419","value":"0xe8d4a51000"}, "latest"]}' | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32602,
    "message": "too many arguments, want at most 1"
  }
}
```

**Without the `TAG` param:**

```
curl -s https://arb1.arbitrum.io/rpc -X POST -H "Content-Type: application/json" -d '{"id":1,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0xa92D461a9a988A7f11ec285d39783A637Fdd6ba4","to":"0xbc5d6cd6f7225bfCCc58F7B75AaeB641ECCD5419","value":"0xe8d4a51000"}]}' | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x7425c"
}
```

🔴 `TAG` is an optional parameter. See [docs](https://docs.alchemy.com/alchemy/apis/arbitrum#eth_estimategas).

Didn't find any usage of `TAG` in their node's source code: https://github.com/OffchainLabs/arbitrum/blob/c1624cd0efdeaf6bb1d3c19ba402082cf5bba4a0/packages/arb-rpc-node/web3/ethclient.go#L124-L138

**Comment by kjozwiak** [comment]
This was originally uplifted/scheduled to go into a `1.35.x` HF but never ended up being released. It will go out via `1.36.x` as we won't be having another `1.35.x` release at this point.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.36.106 Chromium: 99.0.4844.45 (Official Build) (64-bit)
-- | --

Revision | `edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}`
OS | Linux

- Verified steps from [brave/brave-core#12267](https://github.com/brave/brave-core/pull/12267)

https://user-images.githubusercontent.com/17010094/155712880-5af63417-5f1e-43b5-97ab-5175e95f7f53.mp4
