### ISSUE TITLE
using `CHROMN` as attribution when quick searching using Bing (not default SE) for upgraded profiles - follow up to 20659

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#21085]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/20659

Using quick search for Bing (`:b` followed by search term) in omnibox when Bing is not the default SE, still uses `PC=U316&FORM=CHROMN` in the URL bar for upgraded profiles.

Clean profiles (with 1.36.x) behave as expected.

See discussion under https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1644511815398559?thread_ts=1643942748.480089&cid=CHGKGMHDJ

## Steps to Reproduce

Scenario 1:

1. Install 1.35.101. 
2. Launch to create a profile, search using default SE (Brave search). 
3. Close. 
4. Rename profile to Beta. 
5. Launch with latest 1.36.x. 
6. Do a new search from omnibox (ex. `:b hats`). 
7. Resulting URL contains `PC=U316&FORM=CHROMN`.

Scenario 2:

1. Install 1.35.101. 
2. Do not change default SE (Brave search). 
3. Search using Bing via omnibox (ex. `:b shoes`). 
4. Resulting URL contains `PC=U316&FORM=CHROMN`. 
5. Close. 
6. Rename profile to Beta. 
7. Launch with latest 1.36.x Beta version. 
8. Do a new search from omnibox (ex. `:b hats`). 
9. Resulting URL contains `PC=U316&FORM=CHROMN`.

## Actual result:

Quick search for Bing (`:b`) from omnibox on upgrade profiles where Bing is not the default SE still has `PC=U316&FORM=CHROMN` in the search URL. Does not reproduce when Bing is the default SE or on a clean profile w/ Bing quick search with 1.36.x.

## Expected result:

Bing search URL should not contain `PC=U316&FORM=CHROMN`

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.2.1 (Build 21D62)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @simonhong

**Comment by bsclifton** [comment]
OK found root cause! will work on a fix here 😄

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.37.53 Chromium: 98.0.4758.102 (Official Build) nightly (64-bit)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | Windows 10 Version 21H2 (Build 19044.1566)

Scenario 1 - Brave search -> upgrade

1. Install `1.35.103`.
2. Launch to create a profile, search using default SE (Brave search).
3. Close.
4. Rename profile to `Brave-Browser-Nightly`.
5. Launch with latest `1.37.x.`
6. Do a new search from omnibox (ex. `:b hats`).

Confirmed resulting URL does **NOT** contain `PC=U316&FORM=CHROMN.`

example | example | example
----------|-----------|----------
![21085-1](https://user-images.githubusercontent.com/387249/154380494-f7d271b6-6d2f-48de-b5ee-f9bc90573ca2.png) | ![21085-2](https://user-images.githubusercontent.com/387249/154380495-b0ce93a1-7ef9-4c0f-9bde-5a5ac3361ea9.png) | ![21085-3](https://user-images.githubusercontent.com/387249/154380496-21c1ae28-1cd0-4a2a-bb33-e040ee536d2e.png)


Scenario 2 - Bing search -> upgrade

1. Install `1.35.103`.
2. Do not change default SE (Brave search).
3. Search using Bing via omnibox (ex. `:b shoes`).
4. Resulting URL contains `PC=U316&FORM=CHROMN`.
5. Close Brave.
6. Rename profile to `Brave-Browser-Nightly`.
7. Launch with latest `1.37.x` version.
8. Do a new search from omnibox (ex. `:b hats`).


Confirmed final resulting URL does **NOT** contain `PC=U316&FORM=CHROMN.`

example | example | example | example
----------|-----------|----------|-----------
![21085-4](https://user-images.githubusercontent.com/387249/154380587-6f376795-bf47-4448-82ab-36289dc75f16.png) | ![21085-5](https://user-images.githubusercontent.com/387249/154380589-e51a8715-da27-416c-8212-98612c9a3238.png) | ![21085-6](https://user-images.githubusercontent.com/387249/154380591-fe435818-48b4-4253-8eeb-f0300e98f582.png) | ![21085-7](https://user-images.githubusercontent.com/387249/154380595-4691b7b3-0525-45ed-8e1b-0ea16bfa8a6b.png)

Scenario 3: Clean profile

1. installed `1.37.53`
2. changed default search engine to Bing
3. searched using Bing from the omnibox (`shoes`)

Confirmed resulting URL does **NOT** contain `PC=U3166&FORM=CHROMN`

example | example | example
----------|----------|----------
![21085-8](https://user-images.githubusercontent.com/387249/154381910-4775b33a-d31c-4f81-82fa-e5e3d7d12475.png) | ![21085-9](https://user-images.githubusercontent.com/387249/154381912-bcc2b836-bd32-4b5a-b8a9-5bd09d3bf396.png)



Scenario 4: Upgrade w/Bing as default

1. installed `1.35.103`
2. changed default search engine to Bing
3. searched using Bing from the omnibox (e.g. `shoes`)
4. confirmed the resulting URL contains `PC=U3166&FORM=CHROMN`
5. closed Brave
6. renamed profile to `Brave-Browser-Nightly`
7. launched `1.37.53`
8. searched using the omnibox (e.g. `laptop`)

Confirmed resulting URL does **NOT** contain `PC=U3166&FORM=CHROMN`

example | example | example | example | example
----------|----------|-----------|-----------|-----------
![21085-10](https://user-images.githubusercontent.com/387249/154382506-1e7eaca3-ab92-4a0d-9ba5-420e08095421.png) | ![21085-11](https://user-images.githubusercontent.com/387249/154382508-3dc0d19c-eb98-4c17-b48c-00b44d98382f.png) | ![21085-12](https://user-images.githubusercontent.com/387249/154382511-db36b3a9-cc4d-4f27-8ed0-9bd79c834bee.png) | ![21085-13](https://user-images.githubusercontent.com/387249/154382512-1e3ecfdf-c4f8-4920-9a90-c479a0cfe0ea.png) | ![21085-14](https://user-images.githubusercontent.com/387249/154382513-84cb8942-7b67-487f-b495-73a8ab44ac20.png)

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.36.99 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | Windows 10 Version 21H2 (Build 19044.1526)

```
