### ISSUE TITLE
Disable Your devices link for desktop also

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#21082]
This is a follow-up issue for https://github.com/brave/brave-core/pull/12232.
`Your devices` link must be disabled for desktop as well.
STR:
1. Create the sync chain with 2 devices, one of then is desktop and the 2nd is either desktop or Android
2. Enable `Open tabs` data type on both devices
3. On desktop click share button at the address bar on the right.
4. Actual: `Your devices` link is in device list
 Expected:  not to have `Your devices` link is in device list

Also on debug builds that causes failed [DCHECK](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/send_tab_to_self/send_tab_to_self_bubble_view_impl.cc;l=227;drc=5a74d281a2e732499ecf67f5d31dca5b85b44563;bpv=0;bpt=1)

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.53 Chromium: 98.0.4758.102 (Official Build) nightly (64-bit)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | Windows 10 Version 21H2 (Build 19044.1566)

Followed the inline steps to reproduce.

example | example
----------|----------
![21082-1](https://user-images.githubusercontent.com/387249/154349806-ccf54d87-3196-47e4-b265-e41631a38316.png) | ![21082-2](https://user-images.githubusercontent.com/387249/154349813-bdc75b38-9df8-46ae-991b-5b2831c1bedd.png)

**Comment by kjozwiak** [comment]
Will require `1.36.103` or higher.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.104 Chromium: 98.0.4758.109 (Official Build) beta (x86_64)
-- | --
Revision | 03268453da2c7409eb1ee934d97abfc6f3b45420-refs/branch-heads/4758@{#1179}
OS | macOS Version 11.6.3 (Build 20G415)

Steps:
1. installed `1.36.104`
2. launched Brave
3. clicked on the hamburger menu
4. clicked on `Sync`
5. clicked on `Start a new chain`
6. toggled `Open tabs` to `ON`
7. launched `1.36.104` on Android
8. tapped on the 3-dots menu
9. tapped on `Settings`
10. tapped on `Sync`
11. tapped on `Scan or enter a sync code`
12. scanned the QR from step 5
13. tapped on `Data preferences`
14. tapped to toggle `Open tabs` to `ON`
15. back on desktop, loaded `github.com`
16. clicked on the `Share` icon in the URL bar
17.  clicked on `Send to Your Devices`

Confirmed only the active Android device showed up, not desktop.

<img width="1312" alt="Screen Shot 2022-02-23 at 9 02 51 AM" src="https://user-images.githubusercontent.com/387249/155370932-33b42f2b-80e3-475a-a23e-c8749eff851a.png">
