### ISSUE TITLE
Crash while opening a new tab with news enabled

### ISSUE THREAD

**Issue by eisklwksjs** [brave/brave-browser#21087]
## Description 
Brave browser crashes when a new tab is opened via "+" icon; surprisingly it works fine if a tab is created via - open in new tab or open in background tab options

## Steps to reproduce 

   1. open brave browser and enable #brave-news tag
   2. restart brave
   3. open a new tab via "+" icon

## Actual result 
Brave crashes

## Expected result
Brave should open a new tab

## Issue reproduces how often 
Everytime

## Version/Channel Information:

1.35.101
- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? donno
- Can you reproduce this issue with the current Play Store Nightly version?donno

## Device details
   - Install type (ARM, x86): armv8
   - Device type (Phone, Tablet, Phablet): android
   - Android version: 10
   
## Brave version
1.35.101

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@eisklwksjs even though there's a flag available to enable Brave News on `1.35.x`, the feature is actually scheduled to release with `1.37.x` which is slated for `March 29, 2022` as per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule. A lot of the issues, including the one you're running into have already been addressed/fixed via `1.37.x`.

I would recommend turning it off on `1.35.x` and either wait for `1.37.x` to come out or download the latest Nightly via GPS 👍
