### ISSUE TITLE
IPFS, Tor, and Onion icons should be the same (all open new tabs)

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21092]
## Description 

IPFS, Tor, and Onion icons should be the same (all open new tabs)

## Steps to Reproduce

   1. install `1.37.46`
   2. launch Brave
   3. load `ipns://ipfs.io`
   4. click `Use a Brave local IPFS node`
   5. load `https://ipfs.io`
   6. look at the `IPFS` icon in the URL bar

## Actual result:

The icon is different than our `Tor` and `Onion` icons, all of which open in a new tab.

example | example
----------|----------
![Screenshot 2022-02-14 123613](https://user-images.githubusercontent.com/387249/153943411-feb40190-5351-45a2-98a7-68903bae0a4e.png) | ![image](https://user-images.githubusercontent.com/387249/153943777-e574a854-6e61-4015-8cb2-edc5e0c1fa87.png)

## Expected result:

`IPFS`, `Tor`, and `Onion` should all have the same icon; not sure which is correct.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.46 Chromium: 98.0.4758.87 (Official Build) nightly (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1526)

cc @rebron @spylogsster

**Comment by stephendonner** [comment]
Looks like https://github.com/brave/brave-browser/issues/21028 was resolved (albeit with `.onion` rather than `Onion`, which is fine) along with this.

**Comment by spylogsster** [comment]
@stephendonner yes, https://github.com/brave/brave-browser/issues/21028 can be closed

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
<html>
<body>
<!--StartFragment-->

Brave | 1.37.52 Chromium: 98.0.4758.102 (Official Build) nightly (64-bit)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | Windows 10 Version 21H2 (Build 19044.1526)

<!--EndFragment-->
</body>
</html>
```
- Verified the STR from the description and ensured IPFS, Tor and Onion icons are same

IPFS:
![image](https://user-images.githubusercontent.com/38657976/154264758-fd8cb115-450a-40d1-8657-e3c6c05d1f2c.png)

TOR:
![image](https://user-images.githubusercontent.com/38657976/154264826-d13d3e20-d42a-4953-a8f6-1ee004122cab.png)
