### ISSUE TITLE
Send Not Showing Error for Insufficient Balance

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21094]
## Description 
Send is not showing `Error` for `Insufficient Balance`

![Screen Shot 2022-02-14 at 2 27 41 PM](https://user-images.githubusercontent.com/40611140/153949385-248fcb82-29d4-44fc-8d30-7a0169c5a8cb.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12257>brave/brave-core#12257</a></li>
         <li>Verified <code>Insufficient balance</code> error message is shown when ever the input value goes beyond the total available balance even to the last decimal value</li>
         <li>Verified <code>Insufficient balance</code> error message is shown on both widget and panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/154944222-7df7e2f3-7791-4af6-92e4-bddaa8ef8118.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154943833-13cda97d-434e-4e44-a0b9-310189f815f2.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154943568-3cc60267-c318-476a-b3ba-78c171d165d3.mov>
      </td>
   </tr>
</table>
