### ISSUE TITLE
Update l10n for 1.35.x (Chromium 98) - Part 2.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#21097]
Download the latest l10n from Transifex.

Test plan:

https://github.com/orgs/brave/teams/legacy_qa should run through a few locals just to make sure that nothing obvious has regressed. Shouldn't spend too much time on this though.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.35.102 Chromium: 98.0.4758.102 (Official Build) (64-bit)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | Windows 10 Version 21H2 (Build 19044.1526)

```
