### ISSUE TITLE
Double Trouble

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#21098]
Help.

![Screenshot 2022-02-15 at 11 46 04 AM](https://user-images.githubusercontent.com/99705572/153988973-ca780d70-5a6c-4ace-a04d-ba46ae79688e.png)

Browser Version: 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)
OS: Mac

**Comment by srirambv** [comment]
The new shields behind flag is not yet ready. Closing as invalid. Also please include details in the issue so its clear
