### ISSUE TITLE
Add a "zero balance" answer for the Rewards WalletBalance P3A question

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#21091]
## Description 

The `Brave.Rewards.WalletBalance.2` will be replaced by `Brave.Rewards.WalletBalance.3`. A "wallet created, rewards enabled, zero BAT balance" answer will be added to the list of answers for the new question. Here are all the answers for the new question:

0. Brave Rewards never enabled
1. Wallet created, Brave Rewards disabled (ads and auto-contribution disabled)
2. 0 BAT
3. 1 BAT or more, under 10 BAT
4. 10 BAT or more, under 50 BAT
5. 50 BAT or more

Will update wiki after merge.

## Miscellaneous Information:

Will raise PR soon.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.37.82 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1526)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries I am getting the response value as `5` for the wallet balance of `50 BAT`. Looks like you need to update the test plan for the response value `4` in the description

![image](https://user-images.githubusercontent.com/38657976/157067970-44b527e2-f839-433a-a5a8-92f074663b55.png)

**Comment by GeetaSarvadnya** [comment]
@DJAndries `1. Wallet created, Brave Rewards disabled` 
As per the description, the response `1` should be shown when the wallet is created and Rewards is enabled. When we say rewards disabled, does it mean to disable both  `Brave Private Ads` and AC switch? or disable any one of the switches? how this is been implemented. I have tried the combinations below and I am getting the response value `1` in cases 2,3 and 4.

1. When both switches are ON - I am getting the response as `2` (wallet balance is zero) 
2. When both switches are OFF - I am getting the response as `1` (Wallet created, Brave Rewards disabled)
3. When the Ads switch is ON and AC is OFF - I am getting the response as `1` (Wallet created, Brave Rewards disabled)
4. When the Ads switch is OFF and AC is ON - I am getting the response as `1` (Wallet created, Brave Rewards disabled)

 cc: @Miyayes @LaurenWags

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` until @GeetaSarvadnya questions are resolved.

**Comment by DJAndries** [comment]
> @DJAndries `1. Wallet created, Brave Rewards disabled` As per the description, the response `1` should be shown when the wallet is created and Rewards is disabled. When we say rewards disabled, does it mean to disable both `Brave Private Ads` and `AC` switches? or disable any one of the switches? how this is been implemented. I have tried the combinations below and I am getting the response value `1` in cases 2,3 and 4.
> 
> 1. When both switches are ON - I am getting the response as `2` (wallet balance is zero) - Expected
> 2. When both switches are OFF - I am getting the response as `1` (Wallet created, Brave Rewards disabled)
> 3. When the Ads switch is ON and AC is OFF - I am getting the response as `1` (Wallet created, Brave Rewards disabled)
> 4. When the Ads switch is OFF and AC is ON - I am getting the response as `1` (Wallet created, Brave Rewards disabled)
> 
> cc: @Miyayes @LaurenWags

The first two cases are expected. A value of 2 is also expected for the last two cases, however, there is no guarantee that the value would update right way. I recommend refresh the Rewards page after changing the settings, and then checking the local state.

**Comment by GeetaSarvadnya** [comment]
@DJAndries Even after multiple page reload (brave://rewards) or browser restart, cases 3 and 4 are reproducible and return the value `1`. Looks like a bug, going to log an issue

**Comment by DJAndries** [comment]
> @DJAndries Even after multiple page reload (brave://rewards) or browser restart, cases 3 and 4 are reproducible and return the value `1`. Looks like a bug, going to log an issue

Discussed more with @GeetaSarvadnya , we are unable to reproduce this issue
