### ISSUE TITLE
sidebar options in settings UI doesn't have bottom border

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21099]
As captured below, sidebar options has redundant top border and bottom border is missed.
It should have bottom border only.
<img width="736" alt="Screen Shot 2022-02-15 at 2 03 21 PM" src="https://user-images.githubusercontent.com/6786187/153995941-a7dc6fa8-3bfb-46e3-809f-82222241be53.png">

STR
1. Enable sidebar flags
2. Load brave://settings/?search=sidebar
3. Check Sidebar options border

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.50 Chromium: 98.0.4758.87 (Official Build) nightly (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1526)

Steps:
1. install `1.37.50`
2. launch Brave
3. enabled Sidebar via `brave://flags`
4. clicked to `Relaunch`
5. loaded `brave://settings/appearance`
6. confirmed the Settings UI now has the correct top/bottom border for `Show Sidebar`

pre-fix | post-fix
--------|---------
![21099-1](https://user-images.githubusercontent.com/387249/154135458-9ce8575b-2721-4d8b-9522-5022bfae0656.png) | ![21099-2](https://user-images.githubusercontent.com/387249/154135461-82cb8dc2-a978-452a-8d4e-9c45970d7f0d.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.83 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/157133025-d4fcc981-531f-49d8-b7bf-d5126fd44cd9.png)
![image](https://user-images.githubusercontent.com/34715963/157133046-fbd60576-1490-472d-8f5c-726352032a0a.png)

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.37.91 Chromium: 99.0.4844.51 (Official Build) beta (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.3 (Build 21E230)

`dark` | `light`
-------|--------
<img width="1286" alt="Screen Shot 2022-03-14 at 10 58 42 PM" src="https://user-images.githubusercontent.com/387249/158316450-b95e0170-deb6-4150-80e2-c6578349de1a.png"> | <img width="1286" alt="Screen Shot 2022-03-14 at 10 59 13 PM" src="https://user-images.githubusercontent.com/387249/158316456-b8f5cfb5-03cd-42bd-8de7-2c1a47a802f7.png">
