### ISSUE TITLE
NTP image in "zoomed in" after reload

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#21096]
## Description 

NTP image gets cropped after refresh
## Steps to reproduce 

   1. Opt-in brave news and observe the NTP background image
   2. Any type of reload works. Either hit refresh, or send the tap the tab number to get to the tab navigator, or go to an article than come back
   3. The background image looks cropped in. Easier to see on the ads images

## Actual result 
 
![screenshot_20220206-010023](https://user-images.githubusercontent.com/5214149/154094095-1c7945a3-7d14-4dae-8f04-7c2fc834e8cd.png)

## Expected result

Background images should be fully and clearly visible
![screenshot_20220206-010851](https://user-images.githubusercontent.com/5214149/154094150-75b58b9f-f163-4196-a5cf-5a247577ea54.png)

## Issue reproduces how often 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): all devices
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
@alexsafe mind attaching images/videos of the problem?  It helps us quickly identify where to verify and test around; thanks!

**Comment by alexsafe** [comment]
@stephendonner I uploaded the screenshots you took when you found it. Let me know when you get to it if you have trouble reproducing.

**Comment by kjozwiak** [comment]
Will require `1.36.99` or higher.

**Comment by stephendonner** [comment]
Verified `PASSED` using `Brave` `1.36.99, Chromium 98.0.4758.102` on a `Google Pixel XL` (`arm64`) running `Android 9.0`

Followed the original steps to reproduce and all images -- both ads and backgrounds -- are scaled properly.


https://user-images.githubusercontent.com/387249/154631571-8cf8658a-94d6-4300-93ae-4b7f2447a0c7.mp4
