### ISSUE TITLE
Max fee is not updated when base fee changes

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#21105]
Steps to reproduce:
1. Create an EIP-1559 transaction and open the "Edit gas" screen.
    <img width="319" alt="Screenshot 2022-02-15 at 6 12 00 PM" src="https://user-images.githubusercontent.com/3684187/154064199-b8137ce0-2337-4106-b9e0-e325adbc02a1.png">
2. Select "Custom gas".
3. Wait for the base fee to change.
4. **Expected behaviour:** the max fee also changes in response to change in base fee.

This is only reproducible on **1.36.x** or earlier.

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/12264 was merged into `1.36.x`.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12264>brave/brave-core#12264</a></li>
         <li>Verified the base fee updates every 15 secs</li>
         <li>Verified <code>Per-gas price limit</code> updates as and when base fee updates</li>
         <li>Verified suggested fee is also showing correct values</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/154950342-85fe5ea0-4d14-4a34-8285-8f862ab00d31.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154949614-88b76465-b1c9-4699-84b2-71a72295f652.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/154949257-a220c4cc-9da8-469a-ab02-b01ef27b19be.mov>
      </td>
   </tr>
</table>
