### ISSUE TITLE
Minimum visits for publisher relevancy setting not being respected

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2110]
## Description 
If I change the 'Minimum visits for publisher relevancy' setting from default (1 visit) to something else (5 or 10 visits), sites get added to the table after 1 visit and show 0%.

## Steps to Reproduce

   1. Clean profile, enable Rewards.
   2. Open Auto-Contribute Settings.
   3. Change 'Minimum visits for publisher relevancy' to 5 or 10.
   4. Close Auto-Contribute Settings.
   5. Open a new tab and visit a site.
   6. Wait 10s or so.
   7. Go back to Rewards page.

## Actual result:
Site is added to table with 0% attention. If you continue to visit the site until the number of visits is reached, the site % does not adjust, it stays at 0%.

![numberofvisits](https://user-images.githubusercontent.com/28145373/48376539-35b15900-e699-11e8-9082-adedc286600e.gif)

## Expected result:
Setting should be respected. Site should not be added until number of visits is achieved.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta(64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes, reproduced on beta.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa to check on other platforms

**Comment by LaurenWags** [comment]
@rebron after the muon upgrade this issue will likely become more prevalent as current muon users will probably have this setting configured. cc @kjozwiak

**Comment by btlechowski** [comment]
Still reproducible

Brave | 0.59.30 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Windows 7

**Comment by NejcZdovc** [comment]
@btlechowski was not added yet

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1399
