### ISSUE TITLE
Allow contributions to non-verified sites setting is not being respected

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2111]
## Description 
If I uncheck the 'Allow contributions to non-verified sites' setting, non-verified sites are added to the table with 0% attention until a verified site is added. Then all percentage values get recalculated. 

If 'Allow contributions to non-verified sites' is unchecked, non-verified sites should not be added to Auto-Contribute table.

## Steps to Reproduce

   1. Clean profile, enable Rewards.
   2. Open Auto-Contribute Settings.
   3. Uncheck 'Allow contribution to non-verified sites'
   4. Close Auto-Contribute Settings.
   5. Open a new tab and visit a non-verified site (such as ecosia.org). Wait 10s or so.
   6. Go back to Rewards page, site is added with 0% attention.
   7. Open a new tab and visit a verified site (such as duckduckgo.com). Wait 10s or so.
   8. Go back to Rewards page, site is added and all percentage values for Attention have been recalculated.
   9. If you continue to add non-verified sites at this point, they will get added with 0% attention until a verified site is visited, at which point Attention will be recalculated for all sites in the list.

## Actual result:
![allowcontribtononverified-short](https://user-images.githubusercontent.com/28145373/48377780-b0c83e80-e69c-11e8-87db-1987874ccacb.gif)

## Expected result:
If 'Allow contributions to non-verified sites' is unchecked, non-verified sites should not be added to the Auto-Contribute table. This is how this setting worked in Brave Payments.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta(64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes reproduced on beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa to check on other platforms

**Comment by LaurenWags** [comment]
@rebron after the muon upgrade this issue will likely become more prevalent as current muon users will probably have this setting configured. cc @kjozwiak

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Linux

* Verified test steps from https://github.com/brave/brave-core/pull/1042
