### ISSUE TITLE
Treat adding built-in items to sidebar differently than other pages

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21124]
When bookmarks manager is loaded in active tab, user can add it as a shortcut in sidebar.
But, sidebar provides bookmarks panel as a default items.
So, we should add bookmarks builtin item instead of shortcut if it's removed.
This can apply also to all other builtin items.(talk, wallet).

STR:
1. Remove brave talk builtin item
2. Load brave talk in active tab
3. Try to add current tab(talk) via `+` dialog

Actual result - add item bubble shows two entries (one for current active tab and removed builtin item)
![Screenshot 2022-02-17 101730](https://user-images.githubusercontent.com/6786187/154385592-d612a3d5-ab0d-4521-9654-dfe0eb21ce92.png)

Expected result - add item bubble should show one entry (builtin talk item)
![Screenshot 2022-02-17 101416](https://user-images.githubusercontent.com/6786187/154385749-cf28e043-a495-411a-adaf-44bcc5a5f03d.png)
Also add item button should be disabled when builtin sidebar item is already used.
![image](https://user-images.githubusercontent.com/6786187/154396935-121e0188-e1aa-420a-877b-ca6c0c99531d.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.37.65 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1566)

### Steps:

1. installed `1.37.65`
2. launched Brave
3. loaded `talk.brave.com`
4. hovered over the `+` icon

Confirmed no `Add [Brave Talk] to Sidebar` popup

![21124-1](https://user-images.githubusercontent.com/387249/155238083-98bf90b6-512e-41fd-ac98-77b732578355.png)

### Case: remove/add Brave Talk icon

1. installed `1.37.65`
2. launched Brave
3. context-clicked on the Brave Talk icon
4. clicked on `Remove`
5. loaded `talk.brave.com`
6. hovered over `+` button
7. confirmed I was offered to add `Brave Talk`
8. clicked to add Brave Talk


Confirmed the Brave Talk icon was added


example | example
----------|---------
![21124-3](https://user-images.githubusercontent.com/387249/155238129-4f5bf7b6-e4c6-4ef7-9c0d-203ef7ba1747.png) | ![21124-4](https://user-images.githubusercontent.com/387249/155238133-c3a50d56-59c9-41c8-8de6-db270973db62.png)

### Case: Add history

1. installed `1.37.65`
2. launched Brave
3. loaded `brave://history`
4. hovered over the `+` icon in SIdebar
5. confirmed I saw `Add history to sidebar` dialog
6. confirmed the `+` icon is disabled once `history` was added to Sidebar

![21124-6](https://user-images.githubusercontent.com/387249/155238318-db1ee69d-d858-48a4-b9c9-066c24b83970.png)

### Case: no prompt for built-in Bookmarks

1. installed `1.37.65`
2. launched Brave
3. loaded `brave://bookmarks`
4. hovered over the `+` icon

Confirmed no `Add [bookmarks] to Sidebar` popup


![21124-5](https://user-images.githubusercontent.com/387249/155238315-c1541ba9-0670-41b4-9d56-9da4bfe861ac.png)
