### ISSUE TITLE
Cloning tab viewing a PDF requires refresh

### ISSUE THREAD

**Issue by jmoss20** [brave/brave-browser#2113]
## Description 

Cloning a tab that's viewing a PDF requires a refresh before the tab contents load.

EDIT: it appears that this is actually a problem unique to PDFs (local and remote), editing this post to reflect that.

## Steps to Reproduce

   1. Open a PDF.
   2. Clone tab that's viewing the PDF.

## Actual result:

![screen shot 2018-11-13 at 3 20 42 am](https://user-images.githubusercontent.com/6434630/48403251-219a4580-e6f3-11e8-8014-251863e4c0c2.png)

## Reproduces how often: 

Reproduces consistently -- has yet to not reproduce on my end.

## Brave version (brave://version info)

Brave | 0.25.2
-- | --
V8 | 6.9.427.23
rev | 8ea2a9c
Muon | 8.1.8
OS Release | 16.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Unsure.

### Website problems only:  
Shields are disabled for PDFs, does not reproduce on Chrome.

**Comment by srirambv** [comment]
@jmoss20 You are on the older muon browser which is deprecated. Please upgrade to the new [Brave Browser](https://brave.com/download).
