### ISSUE TITLE
Add toggle password visibility to password input

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#21139]
## Description 
Currently, password inputs do not provide a way for the user to toggle password visibility.

<img width="1143" alt="Screenshot 2022-02-16 at 16 37 27" src="https://user-images.githubusercontent.com/48117473/154276171-fb875c3a-08c7-4a35-b53f-d64051ab378d.png">

## Actual result:
Add a button to allow users to toggle password visibility

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.37.84 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12298> brave/brave-core#12298</a></li>
         <li>Verified show/hide password is shown on onboarding and lock screen</li>
         <li>Verified typing password and pressing tab puts selector to show/hide password button and works with keyboard as well</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/157371733-38bc923b-e741-4ed1-867b-ac92b76d4791.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/157371373-fa2712b4-7c88-4548-862b-a0992ee563be.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/157371257-2a66b97a-0e1a-481d-ac6d-fb941f09557a.mov>
      </td>
   </tr>
</table>
