### ISSUE TITLE
Remove margin top for Swap disclaimer message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21138]
## Description 

Keeping `margin-top: 8px` causes the Swap disclaimer message to be pushed down to the edge of the swap box 

## Steps to Reproduce

   1. Install 1.37.52 x64 nightly build
   2. Open Swap on widget
   3. Swap disclaimer text is very close to the edge of the widget border

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/154262542-b9a9e6a6-e8e0-4642-8742-a4f5ed49c457.png)

## Expected result:
Remove `margin-top: 8px` fixes the alignment issue
![image](https://user-images.githubusercontent.com/17010094/154263023-84de159b-40a8-431b-9f75-297915ef549b.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.37.52 Chromium: 98.0.4758.102 (Official Build) nightly (64-bit)
-- | --
Revision | `273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}`
OS | Windows 11 Version Dev (Build 22543.1000)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @Douglashdaniel @onyb

**Comment by Douglashdaniel** [comment]
Was address in https://github.com/brave/brave-browser/issues/21061
Closing as duplicate.
