### ISSUE TITLE
Error when importing an account on a clean profile

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#21137]
## Description 

There are 2 issues on the first import:
1) Raw error message shown if Ledger device locked
2) Accounts import failed after this message when device unlocked

## Steps to Reproduce

   1. Clean profile after install
   2. Connect and lock ledger
   3. Create/Restore Brave Wallet
   4. Try to import accounts when device locked
   5. See error message with $1
   6. Unlock Ledger and import accounts
   7. Import failed

## Actual result:

Wrong error message and unable to import accounts first time

## Expected result:

Correct error message and accounts can be imported

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.37.107 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.593)
```

Verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/21137#issue-1139778723.
