### ISSUE TITLE
Unable to set custom gas outside strict limits

### ISSUE THREAD

**Issue by scmart** [brave/brave-browser#21147]
When trying to set a "Per-gas price limit" on an ETH transaction, the "Save" button seems to always be grayed out unless it is above some number, seemingly the current base fee.

## Steps to Reproduce

Attempt to set a lower custom gas price.

## Actual result:

The wallet doesn't allow setting the gas price.

## Expected result:

The wallet does allow setting the gas price.

**Comment by tbrent** [comment]
+1! The inability to set this precisely is going to drive me back to Metamask, and nobody wants that

**Comment by scmart** [comment]
@spylogsster @srirambv @onyb @darkdh


This is actually a pretty big issue for a lot of people.

**Comment by Emperornero** [comment]
I am also having this issue, and it's a major pain in my ass. 

I don't mind waiting for a transaction to go through, what I don't want to do is pay $60 for a $100 swap transaction.

**Comment by jamesmudgett** [comment]
Related https://github.com/brave/brave-browser/issues/22648

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/22648#issuecomment-1446123598

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per discussion with @srirambv - going to use #22648 in 1.49.x desktop release notes.
