### ISSUE TITLE
`Brave Private Ads` text is not translated to other locales like Germany and France 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21141]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/21097
Brave Private Ads is not translated to other locales like Germany and France 

## Steps to Reproduce

   1. Set OS locale to Germany or France
   2. Enable Rewards
   3. Brave Private Ads is not translated to other locales like Germany and France 

## Actual result:

`Brave Private Ads` text is not translated to other locales like Germany and France 
![image](https://user-images.githubusercontent.com/38657976/154286342-98d81a7b-5d37-4449-a80b-3dbe03d04202.png)

## Expected result:
`Brave Private Ads` text should be translated to other locales like Germany and France 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.35.102 Chromium: 98.0.4758.102 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
Betriebssystem | Windows 10 Version 21H2 (Build 19044.1526)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by rebron** [comment]
@GeetaSarvadnya This should be fixed in the next pull. Can we recheck 1.36 once the translations are merged in.

**Comment by GeetaSarvadnya** [comment]
@rebron The text Brave Private Ads is translated in other locales like Germany and France - Verified in `1.36.116 - Windows 10 x64`

Germany | France
----|----
![image](https://user-images.githubusercontent.com/38657976/158753036-194bb720-4a7d-4879-9746-750b5017d323.png) | ![image](https://user-images.githubusercontent.com/38657976/158753716-96518246-0c91-4627-b3b1-26103bb3bdac.png)
