### ISSUE TITLE
Crash on wallet creation

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#21153]
An original discussion is here https://community.brave.com/t/brave-browser-wallet-will-not-let-me-create-a-wallet/340575
Basically the user reported that they are not able to create a wallet, it crashes on onboarding.
Crash stack:
https://brave.sp.backtrace.io/p/brave/debug?time=hour&filters=(_rxid%3D%225d310000-7c5a-c307-0000-000000000000%22%2Cplat%3DAndroid)&debug=(%222fb9c52%22,0,0)

**Comment by kjozwiak** [comment]
This was originally uplifted/scheduled to go into a `1.35.x` HF but never ended up being released. It will go out via `1.36.x` as we won't be having another `1.35.x` release at this point.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.36.105 x64 nightly build

- Verified able to create wallet without crash when Fingerprint unlock is enabled
- Verified able to create wallet without crash when Fingerprint unlock is not enabled
- Verified when fingerprint is not enabled, locking and unlocking the wallet doesn't cause any crash

Verification passed on Samsung Tab A with Android 10 running 1.36.105 x64 nightly build

- Verified able to create wallet without crash when Facial recognition is disabled
- Verified with facial unlock disabled on the device, locking and unlocking the wallet doesn't cause any crash
