### ISSUE TITLE
Sidebar item add bubble is anchored at wrong place

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21151]
When browser window doesn't have enough space to show item add bubble anchor position is changed implicitely.
Due to this bubble is shown like below.
![Screenshot 2022-02-17 094318](https://user-images.githubusercontent.com/6786187/154382977-ced15797-b69b-451c-bb6c-904a22fb959e.png)

Bubble should be anchored to add button like below.
![Screenshot 2022-02-17 094452](https://user-images.githubusercontent.com/6786187/154383021-1b19a1c5-9dfa-42e6-939b-e4f93edd30be.png)

STR:
1. Launch browser and reduce browser window
2. Hover mouce over add item button

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.68 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 11 Version 21H2 (Build 22000.527)

Followed the steps above and resized the window at various dimensions; confirmed the `Add to Sidebar` flyout was aligned with the `+` at each time.

example | example | example
---------|----------|---------
![21151-1](https://user-images.githubusercontent.com/387249/155398315-5dce5b01-ce4e-4d1a-a8a7-0491814433bd.png) | ![21151-2](https://user-images.githubusercontent.com/387249/155398317-067d16e9-165b-410a-93c4-7235f4305d1e.png) | ![21151-3](https://user-images.githubusercontent.com/387249/155398320-5923a990-bfae-4bcb-b09b-c54afce50392.png)
