### ISSUE TITLE
Check for keyboard input / middle click when processing click on sidebar shortcuts

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21157]
## Description 
Sidebar is a great new feature on Nightly. It has a feature where you can click the `+` icon to add the site you're currently viewing as a shortcut to the sidebar

It would be great if this used similar logic to following links inside a web page (or similar to the bookmarks manager inside the sidebar). Basically Ctrl + Click opening in a new tab, middle click the link to open in a new tab, etc.

**Comment by simonhong** [comment]
Bookmarks bar behavior. Sidebar shortcut item should have same behavior.
Ctrl + click, middle click - opens in new background tab
Shift + click - opens in new window.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.37.65 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1566)

### Steps:
1. install `1.37.65`
2. launched Brave
3. loaded `brave.com`
4. hovered over the `+` icon in Sidebar
5. choose `Add to Sidebar - brave.com` from the popup
6. left-clicked on the `Brave` favicon in Sidebar
7. ctrl-clicked/middle-clicked on the `Brave` favicon in Sidebar
8. shift-clicked on the `Brave` favicon in Sidebar

Confirmed:
6. opened `brave.com` in the current tab
7. opened `brave.com` in a new tab
8. opened `brave.com` in a new window

step 5 | step 6 | step 7 | step 8
----------|----------|-----------|----------
![21157-1](https://user-images.githubusercontent.com/387249/155240374-8ffb5f9b-f9ab-4af8-8c51-5089509871e1.png) |  ![21157-2](https://user-images.githubusercontent.com/387249/155240376-c8518cce-fbc7-4805-a8df-5df67a1cdd5b.png) | ![21157-4](https://user-images.githubusercontent.com/387249/155240381-146e9dfd-b1df-49b6-8c11-530210b3f4cc.png) | ![21157-3](https://user-images.githubusercontent.com/387249/155240377-41555e60-d9a6-4768-9630-7da78344fa93.png)
