### ISSUE TITLE
Login again every new start from Brave

### ISSUE THREAD

**Issue by Titanfinger** [brave/brave-browser#2115]
## Description 
Every time i start Brave i have to Login to google account again and change the dark design on youtube.

## Steps to Reproduce

1. Just Login to google
2. close brave
3. Restart brave

## Brave version (brave://version info)
Version 0.55.22 Chromium: 70.0.3538.77 (Offizieller Build) (64-Bit)

**Comment by srirambv** [comment]
I can't reproduce on the release channel. What OS are you running? Do you close the browser using the `X` button or exit from the hamburger menu?
