### ISSUE TITLE
Add to sidebar bubble is only dismissed when clicked outside 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21156]
## Description 

Add to sidebar bubble is only dismissed when clicked outside 

## Steps to Reproduce

   1. Visit a page in a new tab
   2. Hover over the <kbd>+</kbd> icon in the sidebar
   3. Add to sidebar bubble is shown 
   4. Move away from the <kbd>+</kbd>, bubble is not closed. Have to click outside to close it

## Actual result:

https://user-images.githubusercontent.com/17010094/154416064-94186ad6-75d9-4932-97b1-249d893cfdc7.mov

## Expected result:
Should close the bubble if the mouse cursor moves away from the <kbd>+</kbd> button avoiding unnecessary clicks 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.37.53 Chromium: 98.0.4758.102 (Official Build) nightly (arm64)
-- | --
Revision | `273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes if flag enabled
- Can you reproduce this issue with the beta channel? Yes if flag enabled
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @rebron

**Comment by rebron** [comment]
cc: @bradleyrichter

**Comment by bradleyrichter** [comment]
@srirambv is correct since it should be hover-in, move-out. We could add a delay to the hover state and add a click state which would remain open until click-outside.

**Comment by simonhong** [comment]
MO, giving more delays for showing when hovered would be better because button also interacts with click event.
Currently, sidebar item add bubble is shown very easily.
and I think clicking outside of bubble seems fine for dismissing

**Comment by simonhong** [comment]
FYI, `200ms` delay is given on hover to prevent launching item add bubble when user just bypass on the add button.

**Comment by bradleyrichter** [comment]
@simonhong 200ms delay sounds good. I assume the suer can also click on it immediately to open?

**Comment by simonhong** [comment]
@bradleyrichter Yes, user can click to launch it to open immediatley.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1.  installed `1.45.75`
2. launched browser
3. loaded `cnn.com`
4. hovered over the sidebar item `+` button
5. waited
6. confirmed tooltip reads `Add to Sidebar` (and confirmed no Sidebar "bubble" appeared)
7. clicked on the `+` button
8. confirmed I got the `Add to Sidebar` "bubble"
9. clicked again on the `+` button to dismiss
10. confirmed the `Add to Sidebar` "bubble" was dismissed
11. clicked in various places outside the "bubble"
12. confirmed the "bubble" was dismissed

![add-to-sidebar](https://user-images.githubusercontent.com/387249/192642027-cde93704-39b5-40ff-bc87-3e8ad9c53ebe.gif)
