### ISSUE TITLE
Developer Panel is not opening (closes immediately) upon clicking inspect element.

### ISSUE THREAD

**Issue by kulkarnisaumitra98** [brave/brave-browser#21154]
## Description 

Upon clicking on inspect element the developer panel opens and closes immediately, this doesn't seem to be happening with all the websites, it is only happening with certain websites which are running behind VPN (Not sure if that is correct correlation).

## Steps to Reproduce
Note:- Happens only with certain websites (Was only able to reproduce for my work websites which run behind VPN), I have not been able to reproduce this with any other websites

   1. Right click, open inspect element
   2. Developer panel opens and closes immediately

## Actual result:

Developer panel opens and closes immediately

## Expected result:
Developer panel should not close and hence user should be able to debug using developer panel

## Reproduces how often: 

This issue seems to be reproducing only for my work websites running behind VPN, (Not sure if that is correct correlation) but with one of the those works websites, it is reproducing every time.

## Brave version (brave://version info)

[Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel? - Sorry, didn't try
- Can you reproduce this issue with the nightly channel? - Sorry, didn't try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - No
- Does the issue resolve itself when disabling Brave Rewards? - No
- Is the issue reproducible on the latest version of Chrome? - No

## Miscellaneous Information:

System logs, if that helps.

```
Feb 17 09:24:33  Brave Browser Helper (GPU)[1272]: getattrlist failed for /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver: #2: No such file or directory
Feb 17 09:24:33 Brave Browser Helper (GPU)[1272]: getattrlist failed for /Library/GPUBundles/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
Feb 17 09:24:33 Brave Browser Helper (GPU)[1272]: getattrlist failed for /System/Library/Extensions/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
Feb 17 09:24:33 Brave Browser Helper (GPU)[1272]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Feb 17 09:24:36  Brave Browser Helper[1302]: Libnotify: notify_register_coalesced_registration failed with code 9 on line 2835
Feb 17 09:24:39  Brave Browser Helper[1310]: Libnotify: notify_register_coalesced_registration failed with code 9 on line 2835
Feb 17 09:24:53  Brave Browser Helper[1333]: Libnotify: notify_register_coalesced_registration failed with code 9 on line 2835
Feb 17 09:25:26  Brave Browser Helper[1333]: Libnotify: notify_register_coalesced_registration failed with code 9 on line 
```

**Comment by Joxtacy** [comment]
I am having this same issue. I am also running the same version `Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)`.

I tested this in the Nightly Build `Version 1.37.53 Chromium: 98.0.4758.102 (Official Build) nightly (x86_64)` and I'm having the same problem there. 

Not sure if this is related, but it doesn't happen for me when first navigating to a website. For me it happens when I interact with a webapp in an iframe that I am serving from localhost.
More specifically, it is when I am in my org in [Freshdesk](https://freshdesk.com) and trying to serve a local app with the [Freshworks CLI](https://developers.freshdesk.com/v2/docs/freshworks-cli/).

**Comment by DanjiSes** [comment]
+1

**Comment by awdhootlele** [comment]
Similar one here - https://github.com/brave/brave-browser/issues/20971

**Comment by kulkarnisaumitra98** [comment]
Closing this in favour of https://github.com/brave/brave-browser/issues/20971
