### ISSUE TITLE
Fast/Hard scroll on widgets brings up the news feed rather than scrolling through the widget

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21166]
## Description 
Fast/Hard scroll on widgets brings up the news feed rather than scrolling through the widget

## Steps to reproduce 

   1. Optin to News
   2. Open an NTP
   3. Do a fast/hard scroll on widget, scrolls down the news feed
   4. Only a smooth/slow scroll allows to scroll through the widget

## Actual result 

https://user-images.githubusercontent.com/17010094/154451694-e1adc570-3647-40c7-b992-14e435bddcd0.mp4

## Expected result
Should be able to capture fast/hard scroll on widget 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.37.55

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Reproduces for me using 1.36.109, not hard or fast scrolling, just trying to switch between stats and top sites view. Most of the time (80% or so?) I can't switch between the two views, it just keeps trying to give me Brave News.

**Comment by bsclifton** [comment]
Can we use swipe left/right for cycling through widget? Instead of up/down?

**Comment by kjozwiak** [comment]
@bsclifton @alexsafe labelled this as `P2` as we'll need to get this fixed/addressed before enabling Brave News. Also mentioning https://github.com/brave/brave-browser/issues/13714 as this might address the above which was discussed as a possible solution.

**Comment by bsclifton** [comment]
Closing as `wontfix` - no longer relevant after https://github.com/brave/brave-core/pull/12743
