### ISSUE TITLE
New setting bar is retained when tab tray is opened causing it to look glitched when opening new tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21169]
## Description 
New setting bar is retained when tab tray is opened causing it to look glitched when opening new tab

## Steps to reproduce 

   1. Enable News
   2. Scroll down news so settings bar is shown 
   3. Open tab tray and open a new tab
   4. News settings bar is retained on tab tray and then repaints over the tab making it look janky/unpolished

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/154465803-cf7f3b31-6991-4947-97ca-8fad558b2375.png>

## Expected result
UI Transition should be smooth similar to iOS and not feel janky at all

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.37.55

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @mattmcalister

**Comment by Uni-verse** [comment]
Verification **PASSED** on release branch `1.36.105, Chromium 99.0.4844.45`

Device: `Samsung Galaxy S21` | `Android 12` | `ARM`

- [ ] Transition is smooth when opening new tab in tab tray 
- [ ] News settings bar is not retained when opening new tab

https://user-images.githubusercontent.com/17885425/155615738-12259a61-8681-455f-8ae5-e90e131bbc41.mp4
