### ISSUE TITLE
Add third option to Ledger accounts to support old derivation paths

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#21171]
## Description 

Before https://github.com/brave/brave-browser/issues/19883 we used wrong derivation paths and for compatibility need to add a thrid option to the list as Deprecated (not recommended)

## Steps to Reproduce

   1. Install old brave version
   2. Import ledger Legacy account
   3. Update version, reset wallet and try import again, should be able to import same old accounts

## Actual result:

old accounts are not visible

## Expected result:

old accounts are visible

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
This was originally uplifted/scheduled to go into a `1.35.x` HF but never ended up being released. It will go out via `1.36.x` as we won't be having another `1.35.x` release at this point.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.106 Chromium: 99.0.4844.45 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified </li>
         <li>Verified installing older version (1.32.53) and enabling native wallet and importing Ledger wallets works fine</li>
         <li>Copied the added address from the above setup</li>
         <li>Upgraded to 1.36.106 nightly build</li>
         <li>Verified a new option for <code>Deprecated (Not recommended)</code> option is shown</li>
         <li>Verified searching for the address from step 3 lists the accounts when <code>Deprecated (Not recommended)</code> option is selected </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td><b>1.32.106 Install</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/155747256-37181756-dc3c-4a40-8473-882cc9180078.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/155752249-dd374522-d1dc-4b50-a430-9096a353da43.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/155751223-84026aef-dd38-4e17-842a-e35137a85112.png>
      </td>
   </tr>
   <tr>
      <td><b>Search on Live</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/155747442-8be557cf-1f92-4389-b3b3-cfbde762531a.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/155752292-099b30a6-6299-4f24-8963-0ce68c05b321.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/155751247-8790dac2-3f5f-4f34-be57-4c7a59149d48.png>
      </td>
   </tr>
   <tr>
      <td><b>Search on Legacy</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/155747502-5be29428-5f9f-45d8-ad4d-68f439050a2f.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/155752319-6864d8e2-ab6f-4469-905d-63f961088451.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/155751288-fdb2b986-3bf0-42f4-9ebc-1e5babbd7307.png>
      </td>
   </tr>
   <tr>
      <td><b>Search on Deprecated</b>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/155747547-1143a181-ece8-497a-a0bc-16b0a8d68f10.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/155752362-929a2d4b-ad66-450b-bb4d-b7d9fee04c49.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/155751319-5f63df18-6211-4359-8bab-940046ad521b.png>
      </td>
   </tr>
</table>
