### ISSUE TITLE
Wallet icon needs to more lighter similar to Talk and Bookmarks

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21172]
## Description 

Wallet icon needs to more lighter similar to Talk and Bookmarks

## Steps to Reproduce

   1. Install nightly build
   2. Set browser to dark theme
   3. Wallet is barely visible but on hover shows the correct hover state

## Actual result:

No Hover | On hover
-- | --
![image](https://user-images.githubusercontent.com/17010094/154504113-bb9827ed-9c73-4b9b-8e27-2ab8363c727e.png) | ![image](https://user-images.githubusercontent.com/17010094/154504227-05e0a453-6b36-4758-8079-1c09ed942515.png)

## Expected result:
Should be same as the other two default buttons 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.37.53 Chromium: 98.0.4758.102 (Official Build) nightly (arm64)
-- | --
Revision | `273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}`
OS | macOS Version 12.1 (Build 21C52)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @simonhong

**Comment by simonhong** [comment]
This is duplicated issue - https://github.com/brave/brave-browser/issues/21100

**Comment by simonhong** [comment]
Wallet icon was not updated when theme changed during the runtime.
New window after changing theme has proper wallet icon color.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.37.84 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified wallet icon is clearly visible on both dark and light mode</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td><b>Light theme</b>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/157250467-e9465e7d-5e02-4899-bd50-c7faeaac328c.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/157250077-c1315f4e-a817-4c12-841a-6958463d72e2.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/157250060-f0129e8d-5aea-4c3c-9aed-632b6614cef0.mov>
      </td>
   </tr>
   <tr>
      <td><b>Dark theme</b>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/157250505-ba5315a4-97df-448b-b217-3bc99f76206a.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/157250069-63c259b4-589c-4089-965c-fecfa298c3ff.mov>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/157249764-273d7a73-83ee-4e96-8d11-475d0e703ca2.mov>
      </td>
   </tr>
</table>
