### ISSUE TITLE
Build out Request Public Key Panel UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21177]
## Description 
Reuse the our `Sign Message` panel to create a `Request encryption public key` panel
See https://github.com/brave/brave-browser/issues/19276 for more info.

**Comment by srirambv** [comment]
Moving to 1.39.x as this is dependent on https://github.com/brave/brave-core/pull/12840 which is part of 1.39.x

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12386>brave/brave-core#12386</a></li>
         <li>Verified Encrypt and Decrypt panels are shown correctly</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169810449-984d00a7-91b0-427e-b5a4-15e4c7f80374.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169810699-c9cd9881-9f42-4be9-bae0-a807eb3b3ffc.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169810470-f71fa1b2-be1d-4dde-adcc-a9e566345630.mov>
      </td>
   </tr>
</table>
