### ISSUE TITLE
Deprecate Brave Ads `ads-serve` production `v1/getstate` endpoint and use `ads-static`

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#21181]
Deprecate Brave Ads `ads-serve` production `v1/getstate` endpoint and use `ads-static`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.86 Chromium: 99.0.4844.51 (Official Build) beta (64-bit) 
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/12338

Verified `ads-static` is used for `v1/getstate`. Verified proper country is returned
![image](https://user-images.githubusercontent.com/34715963/157658857-1b5bafdf-f197-466d-a716-f68fc17a21b1.png)

Verified staging still connects to  `ads-serve`
![image](https://user-images.githubusercontent.com/34715963/157659428-9afb94b2-65d4-4cec-8d63-715e3869f04f.png)

 Verified for US
![image](https://user-images.githubusercontent.com/34715963/157659706-bb2a0da5-975a-45d5-9239-ef96cf7d9e28.png)
