### ISSUE TITLE
Brave news Ad looks too long on certain tablets

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#21182]
## Description 
Tested on Samsung A7 lite.

## Steps to reproduce 

   1. Opt in news and scroll until you encounter an ad
   2. Notice the height of the card
   3. 

## Actual result 
Takes most of the screen space on portrait

![Screenshot_20220217-111048_Brave - Beta](https://user-images.githubusercontent.com/5214149/154583769-9ccbf8e1-0afe-4979-b413-6ddcc8bab26a.jpg)

## Expected result
 This expected result needs to be optimised too for differents dpis, on this tablet model all cards have a bit too much space in between the elements. Maybe address this in a future/next  update as part of further polishing

![Screenshot_20220217-110639_Brave - Nightly](https://user-images.githubusercontent.com/5214149/154583844-4965c99c-6783-4f8c-a2b9-4e1f42f003ef.jpg)

## Issue reproduces how often 
Easy with the right tablet

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Labelling this as `QA/No` after speaking with @srirambv. Currently we don't have a way to use the staging server for Brave News like we have on iOS. @srirambv mentioned he spent ~1hr trying to get an inline ad to appear. If we get the ability to switch to the staging server before Brave News goes out on Tuesday, we can revisit.

@srirambv once you create the issue, just mention it in here for more context 👍

**Comment by srirambv** [comment]
https://github.com/brave/brave-browser/issues/21257 is logged for adding a setting to switch to Staging server for Brave News via QA pref. This will help a lot in QA'ing in future
