### ISSUE TITLE
Use brave-core Transifex l10n for Android

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2118]
This task is to re-use scripts for brave-core l10n on Transifex for Android.

There are some advantages to doing this like:
- Not having to pay for the same string translations twice
- Having descriptions for translators on Transifex

**Comment by rebron** [comment]
@bbondy can you prioritize this one?

**Comment by bsclifton** [comment]
I'm pretty sure this is resolved now with Android Core 😄

cc: @mkarolin and @SergeyZhukovsky in case I'm wrong
