### ISSUE TITLE
rewards icon made visible after upgrading after user has disabled it via `Appearance` settings

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#21183]
## Description 

Rewards icon is being re-enabled/made visible after upgrading even though the user has disabled it via `Settings` -> `Appearance`. Sound like running through https://github.com/brave/brave-core/pull/12182 for a `1.36.x` uplift via https://github.com/brave/brave-core/pull/12228.

## Steps to reproduce 

   1. install `1.37.56 Chromium: 98.0.4758.102`
   2. skip all the on-boarding and disable the rewards icon via `Settings` -> `Appearances` -> `Show Brave Rewards icon in address bar`
   3. upgrade to `1.37.57 Chromium: 98.0.4758.102` and notice that the rewards icon has been enabled/visible once again

## Actual result 

Reward icon is being re-enabled after upgrading and not respecting the  `Show Brave Rewards icon in address bar` setting

## Expected result

Brave should respect users preferences and not re-enable the rewards icon if it's disabled by the user

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? Can't check due to https://github.com/brave/brave-browser/issues/20633
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 12`
   
## Brave version

* `1.37.57 Chromium: 98.0.4758.102`

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @anthonypkeane @deeppandya @Uni-verse @srirambv

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.36.105 x64 build
- Verified disabling rewards button on 1.35.102 and upgrading to 1.36.105 retains the setting and hides rewards button
- Verified re-enabling the toggle asks for restart prompt
- Verified once restarted, rewards button is shown in URL bar and able to opt-into rewards

https://user-images.githubusercontent.com/17010094/155673455-3b7cd6b1-80f9-4515-ac37-705122b6f270.mp4

-------------------
Verification passed on Samsung Tab A  with Android 10 running 1.36.105 x64 build
- Verified disabling rewards button on 1.35.102 and upgrading to 1.36.105 retains the setting and hides rewards button
- Verified re-enabling the toggle asks for restart prompt
- Verified once restarted, rewards button is shown in URL bar and able to opt-into rewards

https://user-images.githubusercontent.com/17010094/155674487-19298d1a-9e68-40ae-9907-f272ca3aa07b.mp4
