### ISSUE TITLE
Block outgoing calls to `clientservices.googleapis.com` on startup

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21187]
## Description 
Block outgoing calls to `clientservices.googleapis.com` on startup

## Steps to reproduce 

   1. Install CR 99 build
   2. Connect device to Charles Proxy/Fiddler
   3. Check startup connections. There is an outbound request for `clientservices.googleapis.com` 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/154610883-c9561766-fd10-4146-a969-9881e417a1ac.png)

## Expected result
No outbound calls to `clientservices.googleapis.com` 

## Issue reproduces how often 
Easy 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes on CR99 build

## Device details
   - Install type (ARM, x86): Arm
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.37.54

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @mkarolin @fmarier @samartnik

**Comment by Uni-verse** [comment]
Verification completed on release branch `1.36.105, Chromium 99.0.4844.45`
**PASSED** on `Samsung Galaxy S21` | `Android 12` | `ARM`

- No outbound calls to clientservices.googleapis.com on startup

<img width="1792" alt="Screen Shot 2022-02-24 at 4 21 04 PM" src="https://user-images.githubusercontent.com/17885425/155630730-8b3519d4-073c-4292-b13a-c564379c729d.png">
