### ISSUE TITLE
Crash when trying to restore wallet

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#21195]
## Steps to Reproduce

   1. Reset wallet
   2. Set wallet type as `Brave wallet (prefer extension)`
   3. Set wallet type as `Brave wallet`
   4. Open wallet in new tab
   5. Click by Restore button

## Actual result:

Browser crashed

## Expected result:

Browser is not crashed

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Uni-verse** [comment]
Verification PASSED using

```
1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
--
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.1 (Build 21C52)

```
 Not repro using STR above - https://github.com/brave/brave-browser/issues/21195#issue-1143067538
 
 - Verified able to load wallet in new tab
 - Verified restoring wallet seed
