### ISSUE TITLE
Suggest unlimited approvals as default in Swap

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#21198]
Brave Wallet currently suggests the current balance as a the default allowance value on the token contracts for 0x exchange proxy. This is done for security reasons, but creates a lot of friction in the UX and costs a lot in fees due to repeated on-chain transactions. The proposal is to have one-time Unlimited allowance suggested by our Swap, but warn the users about it during transaction confirmation.

### Test plan

For the QA steps, please try to reproduce the demo in the linked PR. Also try to test the following:
* Approve an unlimited amount for a token, and verify the transaction on the blockchain.
* Same as above, but for a smaller custom amount.

**Comment by kjozwiak** [comment]
This will require `1.36.106` or newer.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.36.106 Chromium: 99.0.4844.45 (Official Build) (64-bit)
-- | --
Revision | `edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}`
OS | Linux

- Verified test plan from issue description
- Verified when Activating a token panel shows `Unlimited allowance requested` warning message
- Verified able to change to custom allowance value
- Verified once custom allowance value is set it never shows `Unlimited allowance requested` message again
- Verified able to set to different custom value and approve transaction

https://user-images.githubusercontent.com/17010094/155715707-4067117b-3806-4925-bb4a-88b2317839db.mp4

Confirmed with @onyb verification on one platform is sufficient
