### ISSUE TITLE
Debug crash when changing theme color (due to VPN button)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21190]
## Description 
There is a debug crash after changing theme. 

I think we need to add a value in https://github.com/brave/brave-core/blob/master/browser/themes/theme_properties.cc representing the color used for VPN button. It's looking for ID `10029` and not finding it. 

## Steps to Reproduce

   1. New profile
   2. Set `brave://flags/#skus-sdk` to ENABLED
   3. Set `brave://flags/#brave-vpn` to ENABLED
   4. Restart browser
   5. Visit `brave://settings/manageProfile`
   6. Change your theme color 

## Actual result:
The console shows:
```
[11952:56368:0217/233156.255:FATAL:theme_properties.cc(133)] Check failed: false. This color should only be queried through ThemeService.
Backtrace:
        base::debug::CollectStackTrace [0x00007FF9A8D86B72+18] (C:\bb2\src\base\debug\stack_trace_win.cc:305)
        base::debug::StackTrace::StackTrace [0x00007FF9A8C58142+18] (C:\bb2\src\base\debug\stack_trace.cc:197)
        logging::LogMessage::~LogMessage [0x00007FF9A8C789BA+138] (C:\bb2\src\base\logging.cc:588)
        logging::LogMessage::~LogMessage [0x00007FF9A8C79D10+16] (C:\bb2\src\base\logging.cc:581)
        `anonymous namespace'::GetLightModeColor [0x00007FF98D94402B+551] (C:\bb2\src\chrome\browser\themes\theme_properties.cc:133)
        ThemeProperties::GetDefaultColor [0x00007FF98D943C46+128] (C:\bb2\src\chrome\browser\themes\theme_properties.cc:309)
        ThemeHelper::GetColor [0x00007FF98CE76C18+352] (C:\bb2\src\chrome\browser\themes\theme_helper.cc:297)
        ThemeService::BrowserThemeProvider::GetColor [0x00007FF98CE70DA4+148] (C:\bb2\src\chrome\browser\themes\theme_service.cc:250)
        BraveVPNButton::UpdateColorsAndInsets [0x00007FF98B69390B+283] (C:\bb2\src\brave\browser\ui\views\toolbar\brave_vpn_button.cc:102)
        ToolbarButton::OnThemeChanged [0x00007FF98C9EF208+24] (C:\bb2\src\chrome\browser\ui\views\toolbar\toolbar_button.cc:448)
```

If you comment out the DCHECK or run a release build, it shows the border as red:
![image](https://user-images.githubusercontent.com/4733304/154630705-006ee111-e50f-4f21-b32f-f44b9373c9c7.png)

## Expected result:
It should have a nice contrasted border, similar to defaults on dark mode and light mode
![image](https://user-images.githubusercontent.com/4733304/154630760-5bcabd5c-6594-4c56-8c6e-021af4838ade.png)
![image](https://user-images.githubusercontent.com/4733304/154630805-bd51c5b8-648a-4154-92ab-eb85dbd3286b.png)

## Reproduces how often: 
100%

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.65 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1566)

Steps:
1. installed `1.37.65`
2. launched Brave
3. set `brave://flags/#skus-sdk` to `Enabled`
4. set `brave://flags/#brave-vpn` to `Enabled`
5. clicked on the `Relaunch` button
6. opened `brave://settings/manageProfile`
7. changed themes a few times, restarted, etc.

Confirmed the theme switches took, and the `VPN` button's border was its normal color.

example | example
----------|----------
![21190-2](https://user-images.githubusercontent.com/387249/155235073-63acdd5c-6c94-4282-8561-e0d50013f4ea.png) | ![21190-3](https://user-images.githubusercontent.com/387249/155235099-b8d00762-006e-415c-b07f-573abcfde794.png)



Filed https://github.com/brave/brave-browser/issues/21242.

**Comment by bsclifton** [comment]
Marking as `QA/No` because it needs to be a debug build in order to crash. Situations with a Release build would fail too - where it would showing a RED border around the VPN button. We could test for that actually
