### ISSUE TITLE
Rebrand and updates

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#212]
URL's
- [x] Get help with Brave points to google support on about brave
- [x] Sign into Brave under bookmarks menu
![image](https://user-images.githubusercontent.com/17010094/40423219-cfce65c2-5e5f-11e8-9ca1-8e8d0ae15348.png)
- [x] Help center in bookmarks points to Google support, should point to https://community.brave.com
![image](https://user-images.githubusercontent.com/17010094/40423587-0e1e4fc6-5e61-11e8-8cdb-8cb37618330a.png)
- [x] Webview crash `Learn more` points to Google support [page ](https://support.google.com/chrome/answer/95669?visit_id=0-636626742849149159-508934227&p=e_awsnap&rd=1). Should point to Brave wiki or https://community.brave.com
![image](https://user-images.githubusercontent.com/17010094/40423701-544f2f56-5e61-11e8-978b-18462d34bafa.png)
- [x] Sign in on chrome://apps page 
![image](https://user-images.githubusercontent.com/17010094/40424033-5932be4c-5e62-11e8-877d-12c24cd187b7.png)
- [x] Reset settings modal link to Google support [page](https://support.google.com/chrome/answer/3296214?visit_id=0-636626742849149159-508934227&p=ui_reset_settings&rd=1). Should be linked to Brave wiki or https://community.brave.com (Settings -> System -> Reset)
![image](https://user-images.githubusercontent.com/17010094/40424174-be20680e-5e62-11e8-83ba-4a879c16a544.png)
- [x] Search engine URL points to Google support [page](https://support.google.com/chrome/?p=settings_omnibox). 
![image](https://user-images.githubusercontent.com/17010094/40424463-abd0c288-5e63-11e8-89d5-bbd6215250e5.png)
- [x] Privacy and security under advanced settings points to Google support [page ](https://support.google.com/chrome/?p=settings_privacy)
![image](https://user-images.githubusercontent.com/17010094/40424511-d139ed88-5e63-11e8-8735-bf999614dbec.png)
- [x] Access password from any device under advance settings links to https://passwords.google.com/ (Settings-> Advanced -> Passwords and Forms -> Manage password
![image](https://user-images.githubusercontent.com/17010094/40424638-21cf3334-5e64-11e8-80a7-2a1deb04c43a.png)
- [x] Help button on Manage password link to Google support [page](https://support.google.com/chrome/?p=settings_password)
![image](https://user-images.githubusercontent.com/17010094/40424735-5bcd05e8-5e64-11e8-8631-84748ad56514.png)
- [x] Get extensions points to Chrome webstore on chrome://extensions, Link/icon should be changed
- [x] Do not track info modal has link to Google support [page](https://support.google.com/chrome/?p=settings_do_not_track)
![image](https://user-images.githubusercontent.com/17010094/40483146-fc753446-5f24-11e8-9cc3-4e6234f0e817.png)
- [x]  Brave API keys notification upon launch. Learn more links to Google [page](https://www.chromium.org/developers/how-tos/api-keys). Either remove the notification or change the link
![image](https://user-images.githubusercontent.com/17010094/40520447-0b003aaa-5f94-11e8-9c48-483734b3f7a7.png)
- [x]  chrome://extensions shows link to Google [webstore ](https://chrome.google.com/webstore/category/extensions) this is on 2e9c470007729e3199dbc091b3f16ecec21942a3
![image](https://user-images.githubusercontent.com/17010094/40586673-79627660-6193-11e8-885f-f72d957fbe6c.png)
- [x] Advanced Font settings links to Google webstore [page](https://chrome.google.com/webstore/detail/advanced-font-settings/caclkomlalccbpcdllchkeecicepbmbm)
Settings -> Customize fonts -> Advanced Font setting
![image](https://user-images.githubusercontent.com/17010094/40588181-9406002c-61a7-11e8-9057-75cbd4489c9d.png)
- [x] Content settings info button links to Google support [page](https://support.google.com/chrome/answer/114662?visit_id=0-636630567183043677-765668258&p=settings_manage_exceptions&rd=2) Settings -> Content settings
![image](https://user-images.githubusercontent.com/17010094/40591254-c13111e8-61db-11e8-8fa8-386e82d0bff0.png)

Icons
- [x] Brave icon for chrome pages and in chrome://settings/help

Settings
- [x] Google Cloud print option
- [ ] Settings -> Accessibility - Points to Chrome Webstore
- [x] Google support link when an search result isn't shown (see sceenshot)
![image](https://user-images.githubusercontent.com/17010094/40401278-9f0cf58a-5e13-11e8-854f-5a2087cb3445.png)
- [x] User sign in button 
![image](https://user-images.githubusercontent.com/17010094/40423181-ad23f2d0-5e5f-11e8-97ed-8aed0181350e.png)
- [ ] Themes links to opening Google webstore (Settings -> Appearance -> Themes)
![image](https://user-images.githubusercontent.com/17010094/40424266-14694a78-5e63-11e8-9a7d-7b85929e9f6b.png)
~- [ ] Remove Chrome person 1 from bookmark import modal~ 
![image](https://user-images.githubusercontent.com/17010094/40424891-ccc9c2d6-5e64-11e8-81ed-f8377a783d65.png)
- [x] Manage other people opens up a new user management window which contains Chrome icon needs to be replaced with Brave icon
![image](https://user-images.githubusercontent.com/17010094/40424916-e6728402-5e64-11e8-935a-4a89f65839e3.png)
- [ ] Remove `Sign in to Brave is disabled by the administrator of this device.` from people menu
![image](https://user-images.githubusercontent.com/17010094/40484382-60fc40c2-5f29-11e8-821c-d2084f572c92.png)
- [x] Context menu in text box shows option to Ask Google for suggestions
![image](https://user-images.githubusercontent.com/17010094/40632205-66b259ac-62b2-11e8-95ae-4c698815789c.png)

cc: @bbondy

**Comment by simonhong** [comment]
Also change uninstall survey url - `GetUninstallSurveyUrl()` in `google_chrome_distribution.cc`.

**Comment by srirambv** [comment]
- [ ] History -> Tabs from other devices asks for Google sign in 
![image](https://user-images.githubusercontent.com/17010094/41481645-c63667dc-70a0-11e8-83a9-3cc45bfe5c5d.png)

**Comment by srirambv** [comment]
@yrliou  I still the Brave API keys message on the release build(1c4f830) and on packaged build. 

Search still points to Google support page
![search](https://user-images.githubusercontent.com/17010094/41487876-61221360-70b8-11e8-9f6f-0750eb4eaab7.gif)

Privacy still points to Google Support page
![privacy](https://user-images.githubusercontent.com/17010094/41487882-687693e8-70b8-11e8-8347-11dba2819254.gif)

Content settings info still points to Google support page
![content](https://user-images.githubusercontent.com/17010094/41487971-bc4d56c8-70b8-11e8-8433-0b028bd4226c.gif)

DNT still points to Google support page
![dnt](https://user-images.githubusercontent.com/17010094/41488028-f48a1828-70b8-11e8-80d4-bc43ab2dd066.gif)

**Comment by srirambv** [comment]
- [ ] Saved password notification shows `Sign in to Chrome` that needs to be reworded

![image](https://user-images.githubusercontent.com/17010094/41503531-e08d3f02-71a4-11e8-86c5-a1485d4bd58f.png)

**Comment by srirambv** [comment]
Windows 8.1 launches a window after install that says Chrome. Needs to be rebranded. Windows 8.1 specific 
![windows8-brave-core](https://user-images.githubusercontent.com/17010094/41811378-73b2d4fe-76dc-11e8-9449-144c8b164030.gif)

**Comment by srirambv** [comment]
- [ ] Settings -> Content Setting -> PDF -> PDF Documents says `Download PDF files instead of automatically opening them in Chrome`
![image](https://user-images.githubusercontent.com/17010094/41824647-d97813ac-77e1-11e8-8227-0fa176c01b41.png)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified no `Google signin ` on any settings page
* Verified all help links points to community.brave.com (later to be replaced with specific support links)
* Verified no `Chromium` icons shown anywhere 
* Verified no settings has the word `Chrome` or `Chromium` in it
* Verified password/cc modal doesn't have Google signin 
* Verified spellcheck option is renamed to Brave but should have been removed (#1623)
