### ISSUE TITLE
Ubuntu - "List of sources not found" error when installing release build

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2120]
## Description 

I have users reporting that they're unable to install release or beta via terminal instructions. When testing, I was also unable to install and received the following errors:
![image](https://user-images.githubusercontent.com/3299098/48438411-c7bc6e80-e738-11e8-964d-1b5418c07d2e.png)

This was tested on a fresh install of both Ubuntu and Brave browser. Note that the errors are thrown after entering the `sudo apt update` command.
@diracdeltas @mbacchi @mihaiplesa 
## Steps to Reproduce

   1. Open terminal in Ubuntu
   2. Enter install instructions via [readthedocs ](https://brave-browser.readthedocs.io/en/stable/installing-brave.html#linux) or [help center](https://support.brave.com/hc/en-us/articles/360018666072-Linux-Installing-Brave-from-Terminal-)

## Actual result:

As screenshot above indicates, errors are thrown after `sudo apt update` is entered in the terminal

## Expected result:
Brave should install

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Release/Beta/Dev

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information
Here is one user report, will dig for others if they would be useful to have:
https://www.reddit.com/r/brave_browser/comments/9wrtzf/installation_of_brave_release_channel_in_ubuntu/

**Comment by avndp** [comment]
Beta can be installed with these instructions: https://aavo.in/steps-how-to-install-brave-browser-in-ubuntu-18-10-cosmic-cuttlefish/

**Comment by Brave-Matt** [comment]
![image](https://user-images.githubusercontent.com/3299098/48513816-b2ffd980-e811-11e8-9a65-35dc68b54032.png)

**Comment by mbacchi** [comment]
By appending to the list each time you're not removing the other malformed entries. Once you run this command one time you don't need to do it again. Remove all but the last line of the file `/etc/apt/sources.list.d/brave-browser-release-bionic.list` and try again. Also, remove the file `/etc/apt/sources.list.d/brave-` as it must have been a mistake and is not being used.

**Comment by mihaiplesa** [comment]
That '-a' has to be taken out from tee in the docs.

**Comment by Brave-Matt** [comment]
☝️  This solved the issue on my end
Docs should probably be updated.

**Comment by Brave-Matt** [comment]
Have a user still reporting the same error after removing the `-a` from tee command. Haven't had anyone else report yet. https://www.reddit.com/r/brave_browser/comments/9wrtzf/installation_of_brave_release_channel_in_ubuntu/e9pzfgs

**Comment by bbondy** [comment]
Setting missing milestone to 0.59.x and missing `QA/Yes` label.
