### ISSUE TITLE
`Load new content` button remains after disabling Brave News

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21204]
## Description 

`Load new content` button remains after disabling Brave News

## Steps to reproduce 

   1. install `1.37.60`
   2. launch Brave
   3. swipe down
   4. opt in to Brave News
   5. swipe down
   6. tap and hold on any article
   7. choose `Disable content from [source]`; wait until you see `Load new content`
   8. tap on the `Settings` icon
   9. tap to toggle `Show Brave News` to `OFF`
   10. tap on the `x` on the window
   11. note the `Load new content` orange button remains

## Actual result 

`Load new content` button remains.

![Screenshot_20220218-231402](https://user-images.githubusercontent.com/387249/154791408-447d12e8-ce10-4337-aba6-f8db70b1c0c2.png)

## Expected result

Should be an empty tab.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`.
   
## Brave version

`1.37.60, Chromium 99.0.4844.35`

cc @alexsafe @srirambv @mattmcalister

**Comment by kjozwiak** [comment]
Will require `1.36.103` or higher.

**Comment by stephendonner** [comment]
Verified `PASSED` using `Brave` `1.36.104, Chromium 98.0.4758.109` on a `Google Pixel XL` (`arm64`) running `Android 9.0`.

Followed my original steps to reproduce and confirmed after disabling Brave News, the `Load new content` button artifact is gone.

example | example
---------|---------
![Screenshot_20220223-004617](https://user-images.githubusercontent.com/387249/155287394-6f8ae4bb-f9c4-4b26-9078-88519cf3513e.png) | ![Screenshot_20220223-004631](https://user-images.githubusercontent.com/387249/155287409-eb4e2014-2eb7-4d95-920c-b394989b967a.png)
