### ISSUE TITLE
Add IPFS local node retention P3A question

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#21203]
## Description 

Adding a new P3A question to determine IPFS local node retention: Was the IPFS local node ever used? If so, is it still enabled?

The bucket values will be:
0: Never installed
1: Installed, and enabled
2: Installed, not used any more

## Miscellaneous Information:

Will raise PR soon.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.37.84 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1526)

```
