### ISSUE TITLE
Add Rewards onboarding messaging in Rewards NTP widget

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21202]
## Description

When users opt into Rewards during initial browser welcome onboarding (brave://welcome), they are sent to brave://rewards settings page. 

<img src="https://user-images.githubusercontent.com/11497541/154727580-24f21c0f-8c82-42b4-8872-505724e15b0f.png" width=350px>

## Solution

1. Send user to NTP 
2. Rewards NTP widget will have a message like "Configure your Brave Rewards earning settings now, and take a tour!" and a button that leads to Rewards settings page or Rewards panel (depending on desired UX) with the existing Rewards onboarding. This messaging will _always_ live in the NTP widget between state [1] and [2] (see below).

## References

**State [1]**
<img src="https://user-images.githubusercontent.com/11497541/154752259-386f9661-776a-4b25-83ac-5d336c54c513.png" width=150px>

**State [2]**
<img src="https://user-images.githubusercontent.com/11497541/154752036-70f39cc0-2213-48d8-89e1-61edb6add470.png" width=150px>

@rebron

**Comment by Miyayes** [comment]
@zenparsing Do we know/have a value that tracks whether user has "completed" Rewards onboarding? If so, then I imagine we wouldn't want to show this onboarding messaging in the NTP Rewards widget if the user went and completed Rewards onboarding somewhere else (e.g., via the Rewards panel or Rewards settings page).

**Comment by zenparsing** [comment]
@Miyayes Currently, we don't track whether the user has completed onboarding. Instead, we use the `rewards.enabled` preference to whether they've ever opted-in to Rewards. If they've never opted in, then we show the "Enable Rewards" button which is then tied to onboarding.

Adding a new state between "never enabled" and "enabled" would require us to add some kind of state (probably another pref).

**Comment by rebron** [comment]
@Miyayes After chatting with @Sam-Sibley We'd like to open up the panel from the NTP widget and go into the onboarding/intro flow from there.

**Comment by rebron** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/21811
