### ISSUE TITLE
Get latest production release Version programatically

### ISSUE THREAD

**Issue by szepeviktor** [brave/brave-browser#21208]
## Description 
I'm managing Brave browser manually in a user directory on Windows.

https://github.com/brave/brave-browser/releases/latest points to a Nightly release.
What I can do now is parsing brave.com/latest/ web page `//div[@class="box"]/h2[@id="desktop"]/following-sibling::h3/strong`
It gives `V1.35.103`.

Do you happen to have an API that responds with the latest production release version?
Thank you!

**Comment by szepeviktor** [comment]
@bsclifton Could you help me with my extreme edge case?

**Comment by bsclifton** [comment]
@szepeviktor we don't have an API for this - but I do have a much easier way you can get the latest *RELEASE* versions 😄 

You can parse out the links from https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md

Releases at the top are newer of course - and they point directly to the tag (where the signed binaries are). This should be a good way to get them. Let me know if this works!

**Comment by szepeviktor** [comment]
Witty! Witty! You offer a Markdown document instead of an HTML document 🤣 🤣 🤣
