### ISSUE TITLE
Crash on start Linux (Brave nigthly)

### ISSUE THREAD

**Issue by pmoralesp** [brave/brave-browser#21218]
## Description 

Brave nightly 1.37.61 crash on start. Worked well for months, but started to fail since Nightly v1.37.59 ~~or maybe Nightly v1.37.58~~.

Brave 1.37.58 was the last version that worked.

- 1.37.58 ✅ 
- 1.37.59 ❌ 
- 1.37.61 ❌ 
- 1.37.62 ❌ 
- 1.37.64 ❌ 
- 1.37.65 ❌ 

## Steps to Reproduce

   1. Open Brave Nightly
   2. 
   3. 

## Actual result:

```
[36080:36080:0221/111239.911178:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
thread '<unnamed>' panicked at 'An external domain resolver must be set when the `embedded-domain-resolver` feature is disabled.', /home/ubuntu/workspace/brave-browser-build-linux-x64-nightly/src/brave/build/rustup/0.1.9/registry/src/github.com-1ecc6299db9ec823/adblock-0.4.3/src/url_parser/mod.rs:105:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[0221/111240.028129:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0221/111240.028385:ERROR:elf_dynamic_array_reader.h(64)] tag not found
/opt/brave.com/brave-nightly/brave-browser: línea 48: 36045 Abortado                (`core' generado) "$HERE/brave" "$@"

```

## Expected result:

Don't crash at start.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave 1.37.61 (Nightly channel)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **No**
- Can you reproduce this issue with the beta channel? **No**
- Can you reproduce this issue with the nightly channel? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **Not applicable**
- Does the issue resolve itself when disabling Brave Rewards? **Not applicable**
- Is the issue reproducible on the latest version of Chrome? **No (Chrome 100.0.4892.0 (Build oficial) dev 64 bits)**

## Miscellaneous Information:

* OS: Arch Linux 86_64
* Kernel 5.16.10-arch1-1
* DE: Gnome 41.4
* CPU: Intel i7-9750H (12) @ 4.500GHz
* GPU 1: Intel CoffeeLake-H GT2 [UHD Graphics 630]
* GPU 2: NVIDIA GeForce GTX 1660 Ti Mobile
* Crash with both GPU.

Downgrade to 1.37.58 solves the problem.

**Comment by srirambv** [comment]
Repro'd the crash only on upgrade when installed 1.37.64. Clean profile works just fine. 

cc: @iefremov

**Comment by beisiris** [comment]
I have a clean install.. 
1 - Clean install - Crash 
2 - Uninstall 
3 - Fresh install AUR (brave-nightly-bin 1.37.64-1)
4 - Crash.

Can open on private windows ..

**Comment by DesignatedJM02** [comment]
I did a clean install of Nightly - Still crashed.
Like the comment a few ones above, I can open inPrivate / Incognito tab, just fine

**Comment by antonok-edm** [comment]
Should be fixed in the next Nightly release (1.37.67)

**Comment by pmoralesp** [comment]
1.37.67 works flawless 🚀 . Thanks @antonok-edm

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.37.92 Chromium: 99.0.4844.51 (Official Build) beta (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)
```

Confirmed able to do a clean install of `1.37.92`. Confirmed no crash on start up. Confirmed able to relaunch several times without issue.

Confirmed able to upgrade from `1.36.104` --> `1.37.92` without issue. Confirmed no crash when relaunching after upgrade. Confirmed able to relaunch several times without issue.

**Comment by beisiris** [comment]
thank you..
