### ISSUE TITLE
Adding CoingecoID should only show the value for the selected asset rather than at portfolio 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21217]
## Description 

Adding CoingecoID should only show the value for the selected asset rather than at portfolio. Found while testing #20581

## Steps to Reproduce

   1. Add a custom asset view
   2. Add `bitcoin` for `CoingeckoID` in the custom asset details
   3. Entire portfolio and other existing tokens values are listed in BTC value rather than the one that is added 

## Actual result:

Adding CoingecoID should only show the value for the selected asset rather than at portfolio 
<img width="1728" alt="Screen Shot 2022-02-21 at 8 41 44 AM" src="https://user-images.githubusercontent.com/17010094/154966459-b4e32f40-91cc-490c-87c1-d1e8e8ca7b57.png">

## Expected result:
Should only show for the custom token that is added 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (x86_64 translated)
-- | --
Revision | `273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @onyb

**Comment by Douglashdaniel** [comment]
Per internal discussion this is expected behavior.
`CoingeckoID` is for used for getting the accurate price for a token and was added as an option since `symbols` don't always return the correct price information from our API.
Adding `Bitcoin` as a `CoingeckoID` is going to reflect as the price for that token.
