### ISSUE TITLE
Need better text alignment for long account names on Panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21216]
## Description 

Need better text alignment for long account names on Panel

## Steps to Reproduce

   1. Submit a transaction with long account names
   2. Open panel and open transaction history
   3. Text alignment is weird with long names

## Actual result:
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/17010094/154941568-7a72158c-3e12-4e95-8158-b7120d7ca71d.png">

## Expected result:
Probably just have a text details rather than account icons. 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.36.100 Chromium: 98.0.4758.102 (Official Build) beta (x86_64 translated)
-- | --
Revision | `273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @Douglashdaniel @josheleonard @muliswilliam

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12585>brave/brave-core#12585</a></li>
         <li>Verified recent transactions are properly aligned in panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/167375418-52103d96-3be9-47d6-8d21-383076973fb3.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/167376543-1ab60650-6790-44c0-866d-90b083c88b7e.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/167374849-c9fc6230-6aae-4b6a-9391-dd1a193119c9.png>
      </td>
   </tr>
</table>

**Comment by bbondy** [comment]
I think a user could have perceived this issue, so marking as include for release notes.
