### ISSUE TITLE
Anti-adblock on washingtonpost.com

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#21212]
## Description 
Anti-ad on `https://www.washingtonpost.com/national/health-science/fracking-is-not-the-cause-of-quakes-rather-its-frackings-wastewater/2015/04/27/e87a6e82-e9f4-11e4-aae1-d642717d8afa_story.html`

## Steps to Reproduce

   1. Open `https://www.washingtonpost.com/national/health-science/fracking-is-not-the-cause-of-quakes-rather-its-frackings-wastewater/2015/04/27/e87a6e82-e9f4-11e4-aae1-d642717d8afa_story.html`
   2. Anti-adblock on left
   3. 

## Actual result:
![wapo](https://user-images.githubusercontent.com/1659004/154867842-29cefb3b-b7f7-4c12-a26a-227fd0fea2d6.png)

## Expected result:
Don't show anti-adblock

## Reproduces how often: 

Easily

## Brave version (brave://version info)
`Version 1.37.56 Chromium: 98.0.4758.102 (Official Build) nightly (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Seems washingtonpost is using randomised _0x script names, and is fixed in uBO with `washingtonpost.com##^script:has-text(_0x)`

**Comment by antonok-edm** [comment]
I believe this is no longer relevant, but either way - procedural filtering is released as of https://github.com/brave/brave-core/pull/24688 (1.72.18).
