### ISSUE TITLE
Sidebar items re-ordering is broken

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21213]
Sidebar items re-ordering is broken with latest master build.
After droping to new position, item should be moved to new position.
However, item's position is not changed and re-ordering status bar is also not cleared like below.
![image](https://user-images.githubusercontent.com/6786187/154873839-e9dde872-d744-40fa-b83a-86df004e539b.png)

This is not reproducible on latest nightly build `1.37.56`. I assume this regression comes from C99 rebase.
Note: This doesn't happen on macOS.

**Comment by stephendonner** [comment]
Verified `PASSED` using

Brave | 1.37.65 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1566)

Steps:
1. new profile
2. launched Brave
3. clicked on, dragged, and reordered the Sidebar icons dynamically

![drag-and-drop-sidebar](https://user-images.githubusercontent.com/387249/155217234-4c576520-e5f8-4e19-b356-14baadedd697.gif)
