### ISSUE TITLE
Browsing data list is empty in `On Exit` tab in brave://settings/clearBrowserData 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21225]
## Description 

Browsing data list is empty in `On Exit` tab in brave://settings/clearBrowserData 

## Steps to Reproduce

   1. Open 1.37.x 
   2. Navigate to brave://settings/clearBrowserData 
   3. Tap on `On Exit` tab
   4. Browsing data list is empty in `On Exit` tab

## Actual result:

Browsing data list is empty in `On Exit` tab in brave://settings/clearBrowserData 

![image](https://user-images.githubusercontent.com/38657976/155170642-903edf2a-11d6-41cf-ae26-284074aaec80.png)

## Expected result:
Browsing data list should not be empty in `On Exit` tab 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.37.61 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1526)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @mkarolin

**Comment by stephendonner** [comment]
Verified `PASSED` using



Brave | 1.37.66 Chromium: 99.0.4844.35 (Official Build) nightly (x86_64)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | macOS Version 11.6.3 (Build 20G415)

Followed steps above and confirmed the `On Exit` tab and all other tabs are populated and work.

Clicking on `Reset Brave Rewards data...` launches the Rewards dialog.

example | example | example | example | example
---------|----------|---------|----------|----------
<img width="1407" alt="Screen Shot 2022-02-23 at 10 07 49 AM" src="https://user-images.githubusercontent.com/387249/155380428-ef967f1c-a94d-4da0-8780-9bdc23b6fba6.png"> | <img width="1407" alt="Screen Shot 2022-02-23 at 10 01 10 AM" src="https://user-images.githubusercontent.com/387249/155380339-e51feda3-0c12-460e-817a-d2173d472e8e.png"> | <img width="1407" alt="Screen Shot 2022-02-23 at 10 03 58 AM" src="https://user-images.githubusercontent.com/387249/155379957-67888985-88ef-47f9-aee2-60128759f427.png"> | <img width="1407" alt="Screen Shot 2022-02-23 at 10 01 55 AM" src="https://user-images.githubusercontent.com/387249/155379991-2a22904b-16dc-4a1f-8e58-69b1a84aeb1d.png"> | <img width="1407" alt="Screen Shot 2022-02-23 at 10 05 35 AM" src="https://user-images.githubusercontent.com/387249/155380212-68598e92-198a-4133-b595-248431e2d30f.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.36.105 Chromium: 99.0.4844.45 (Official Build) (64-bit)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}

### Steps:
1. installed `1.36.105`
2. launched Brave
3. opened `brave://settings/clearBrowserData`
4. clicked on the `On exit` tab pane

Confirmed the `On exit` pane was populated both with data - both the category types and accrued.

`light` | `dark`
-------|-------
![21225-1](https://user-images.githubusercontent.com/387249/155576829-f114b73f-abfb-47b3-b182-20f3b8d99f30.png) | ![21225-2](https://user-images.githubusercontent.com/387249/155576910-f76b3660-af85-4762-9085-7c2955b0d33b.png)
