### ISSUE TITLE
Implement error modal when user cannot verify Rewards [855]

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21226]
https://github.com/brave/internal/issues/855

**Comment by kjozwiak** [comment]
Requires `1.37.91` or higher for QA verification's via `1.37.x`.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.37.95 Chromium: 99.0.4844.74 (Official Build) beta (64-bit)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```

**Comment by LaurenWags** [comment]
Verified with Google Pixel 3 XL with Android 12 running 1.37.105

* Verification notes can be found under https://github.com/brave/internal/issues/855#issuecomment-1079274885
