### ISSUE TITLE
Add sweepstakes banner to Brave Wallet

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21224]
Banner requirements:
- Sweepstakes banner should be dismissible via close 'x' button. Banner displayed until close or expiration date is reached.
- State of close should be saved 
- Clicking the sweepstakes button should direct to a brave.com/learn page (link to be provided)
- Final copy to be provided
- https://www.figma.com/file/jZrVG7dsi5npXFTDC6LDGn/Crypto?node-id=0%3A1

**Comment by josheleonard** [comment]
@jamesmudgett , do we want the "state of close" to stored in chromium prefs? Or just stored for the session?

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.36.111 Chromium: 99.0.4844.51 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22523.1000)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12389>brave/brave-core#12389</a></li>
         <li>Verified banner graphics is upgraded as per <a href=https://github.com/brave/brave-core/pull/12497>brave/brave-core#12497 </a></li>
         <li>Verified on a clean install when date is set between 7/3/22 - 15/3/22 the promo card is shown</li>
         <li>Verified reloading the wallet page doesn't remove the promo card</li>
         <li>Verified clicking on <code>Earn now!</code> link opens up <code>https://brave.com/sweepstakes/</code></li>
         <li>Verified promo card is only shown once. Closing the card and reloading the page doesn't bring it back</li>
         <li>Verified promo card shows correctly on both light and dark theme</li>
         <li>Verified locking and unlocking the wallet doesn't remove the promo card when campaign is active</li>
         <li>Verified for <code>en-CA</code> locale, the promo card is not shown when campaign is active</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/157028049-219c5698-8fe3-473a-b5ec-bbf1290e6a64.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/157024774-c8283ab3-26ce-4b7e-8f1c-c0a382a9d26a.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/157026491-1eda00af-4a45-40b4-aacf-bfef49e466b3.mov>
      </td>
   </tr>
</table>
