### ISSUE TITLE
Enabling Brave Shields breaks “Sync with system” theme setting on multiple websites.

### ISSUE THREAD

**Issue by Adrian-Samoticha** [brave/brave-browser#21220]
## Description 

When Brave Shields are enabled, websites that offer a “Sync with system” theme setting such that dark mode is automatically enabled if and only if it is enabled on the OS the browser is running on (such as GitHub and YouTube) default to a light theme even when the OS is currently set to dark mode.

Interestingly, YouTube seems to switch to dark mode for a fraction of a second before returning to light mode when dark mode is enabled at an OS level.

I'm aware that blocking websites from accessing OS-related information may help against certain trackers however I believe that if this is intentional, it should be present as an option in the brave-shields panel. Currently, the issue persists despite Brave showing 0 blocked items (on GitHub), which is why I believe this to be a bug. 

## Steps to Reproduce

   1. Open the GitHub website
   2. Navigate to the “Appearance” panel in the Settings menu and set the theme to “Sync with system”
   3. Enable Brave shields

## Actual result:

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/86920182/155008037-094311ae-4a86-4491-993d-954998f87144.png">

## Expected result:
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/86920182/155008089-399dcefe-8f49-48b9-acff-b62f2ec0842d.png">

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.35.103 Chromium: 98.0.4758.102 (Official Build) (arm64)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | macOS Version 12.0.1 (Build 21A559)
JavaScript | V8 9.8.177.11
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/adriansamoticha/Library/Application Support/BraveSoftware/Brave-Browser/Default
Linker | lld
Variations | AdRewardsStudy:NextPaymentDayAdServingStudy:MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=8/MaximumInlineContentAdsPerDay=40BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5BraveDebounceStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledForceDisableBlinkFeatures:EnabledMacCoreLocationBackendStudy:EnabledNativeCosmeticFilteringStudy:EnabledNavigationThreadingOptimizationsCompat:DisabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes.**
- Can you reproduce this issue with the beta channel? **n/a**
- Can you reproduce this issue with the nightly channel? **n/a**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **Obviously, yes.**
- Does the issue resolve itself when disabling Brave Rewards? **No.**
- Is the issue reproducible on the latest version of Chrome? **n/a**

## Miscellaneous Information:

n/a

**Comment by rebron** [comment]
@Adrian-Samoticha I'm not able to reproduce this. Can you make sure brave://settings/appearance Brave Colors is set to Same as macOS and github is set properly, e.g. Day Theme is dark. With the github example, when I switch light and dark them from system settings, everything goes light or dark them the browser and the content.

**Comment by ryanbr** [comment]
Which shields settings exactly is causing it? is there any extensions being used also? @Adrian-Samoticha

**Comment by rebron** [comment]
@Adrian-Samoticha Do you have an extension possibly in conflict here. You can see below, looks like it's working properly. 

https://user-images.githubusercontent.com/5951041/155806896-147f5e86-27b5-4214-b2a0-d7ae54833e0f.mov

**Comment by nastavoi** [comment]
Try to set this flag to disabled. Github, google etc. should then detect system theme just fine.
#brave-dark-mode-block

It was added sometime ago in https://github.com/brave/brave-core/pull/9735

**Comment by Adrian-Samoticha** [comment]
> Try to set this flag to disabled. Github, google etc. should then detect system theme just fine when strict fingerprinting is enabled. #brave-dark-mode-block
> 
> It was added sometime ago in [brave/brave-core#9735](https://github.com/brave/brave-core/pull/9735)

Thanks, this actually did the trick.
