### ISSUE TITLE
Bookmarks folder layout color and style is getting changed upon mouse hover

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21227]
## Description 

Bookmarks folder layout color and style is getting changed upon mouse hover

## Steps to Reproduce

   1. Open brave 1.37.x
   2. Navigate to brave://bookmarks/
   3. Mouse hover on the bookmarks/Other Bookmarks folder
   4. Bookmarks folder layout color and style is getting changed upon mouse hover

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/155181627-e4248d03-5ec7-469c-9f44-79d17e83c9f8.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.37.61 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1526)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.105 Chromium: 99.0.4844.45 (Official Build) (64-bit)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | Windows 10 Version 21H2 (Build 19044.1566)
JavaScript | V8 9.9.115.7

Steps:
1. installed `1.36.105`
2. launched Brave
3. opened `brave://bookmarks/`
4. moused-over / hover on the `Bookmarks` & `Other Bookmarks` folders

Confirmed they look as expected in both `light` and `dark` themes.
Confirmed they have appropriate hover styles applied to the folder icons.

`light` | `dark`
-------|-------
![21227-2](https://user-images.githubusercontent.com/387249/155575484-50a90778-70f4-47b0-920d-4396e0403905.png) |  ![21227-1](https://user-images.githubusercontent.com/387249/155575514-c603d58c-fafc-4037-8441-0ca966f20ddf.png)
