### ISSUE TITLE
IPFS onboarding does not validate postmessage origin

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#21234]
see details at https://github.com/brave/brave-core/security/code-scanning/44?query=ref%3Arefs%2Fheads%2Fmaster

**Comment by stephendonner** [comment]
Quick (and important) enough change to verify on all platforms -> `QA/Test-All-Platforms`.

**Comment by stephendonner** [comment]
Is this code shared with Android's IPFS/gateway support, and should be checked there, too?  @spylogsster @diracdeltas

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.37.84 Chromium: 99.0.4844.51 (Official Build) beta (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.3 (Build 20G415)

### Steps:

Case 1: `Use a Brave local IPFS node`
1. install `1.37.84`
2. launch Brave
3. load `ipns://ipfs.io`
4. click on `Use a Brave local IPFS node`
5. wait for installation

example | example
---------|----------
<img width="1246" alt="Screen Shot 2022-03-08 at 9 17 31 PM" src="https://user-images.githubusercontent.com/387249/157377827-afa940d2-64bd-42a4-94bd-45f60420abaa.png"> | <img width="1075" alt="Screen Shot 2022-03-08 at 9 17 46 PM" src="https://user-images.githubusercontent.com/387249/157377830-f2d774c3-a65f-4b8d-9060-ca8787d2e8f3.png">



Confirmed it loaded `ipns://ipfs.io`

Case 2: `Use a public gateway`
1. install `1.37.84`
2. launch Brave
3. load `ipns://ipfs.io`
4. click on `Use a public gateway`

Confirm it loaded `https://ipfs-io.ipns.dweb.link/` via public gateway

example | example
---------|---------
<img width="1246" alt="Screen Shot 2022-03-08 at 9 17 31 PM" src="https://user-images.githubusercontent.com/387249/157378109-13f7c266-806a-4ecb-b9d8-6d232aa9a3f0.png"> | <img width="928" alt="Screen Shot 2022-03-08 at 9 20 54 PM" src="https://user-images.githubusercontent.com/387249/157378141-42a77a69-8525-45a8-b894-e54fc63b639a.png">

cc @MadhaviSeelam
