### ISSUE TITLE
NTP-SI does not render when desktop dimensions are narrow

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#21235]
## Description 
When opening NTP, the SI will not properly render if the desktop browser dimensions are narrow.

## Steps to Reproduce

   1. Open Brave Browser Beta (1.36.101) with staging
   2. Make browser narrow, similar to portrait mode
   3. Open NTP until SI

## Actual result:
<img width="651" alt="Screen Shot 2022-02-22 at 14 53 04" src="https://user-images.githubusercontent.com/24831890/155208505-852f1501-0d74-4890-84f1-6ae3a46498c7.png">

## Expected result:
Either the NTP-SI background or standard background.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.36.101

## Version/Channel Information:
Confirmed on Beta & Nightly. Did not test on Release.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @LaurenWags

**Comment by LaurenWags** [comment]
Was able to reproduce on M1 when launching with `--use-dev-goupdater-url` from terminal, but did not reproduce on intel macOS using same build.

Steps:
1. Clean profile using 1.36.101, staging env, dev go-updater url (`--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=9,"*/brave_rewards/*"=9,"*/bat-native-ads/*"=9,"*/bat-native-confirmations/*"=9,"*/brave_ads/*"=9,"*/brave_user_model/*"=9 --brave-ads-staging --rewards=staging=true --brave-ads-debug --use-dev-goupdater-url`)
2. Make window as narrow as possible
3. Open NTP until you get to what should be NTP SI
--> M1 does not show NTP SI
--> Intel does show NTP SI

Reproduced using

```
Brave	1.36.101 Chromium: 98.0.4758.102 (Official Build) beta (arm64) 
Revision	273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS	macOS Version 12.2.1 (Build 21D62)
```

<img width="495" alt="M1" src="https://user-images.githubusercontent.com/28145373/155211899-b9cd5a27-8b48-4fe8-881e-26a3e59cc89e.png">


Does not reproduce using

```
Brave | 1.36.101 Chromium: 98.0.4758.102 (Official Build) beta (x86_64)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | macOS Version 12.2.1 (Build 21D62)
```

<img width="496" alt="intel" src="https://user-images.githubusercontent.com/28145373/155211947-5d2caab4-8282-4c31-98e8-d2e436deeb8f.png">

cc @rebron @petemill

**Comment by LaurenWags** [comment]
Reproduces with 1.35.x as well on M1.

```
Brave	1.35.103 Chromium: 98.0.4758.102 (Official Build) (arm64) 
Revision	273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS	macOS Version 12.2.1 (Build 21D62)
```

<img width="498" alt="Screen Shot 2022-02-22 at 3 19 28 PM" src="https://user-images.githubusercontent.com/28145373/155212551-7dd87929-9898-4493-aa84-db6443a3888a.png">

**Comment by rebron** [comment]
cc: @simonhong @petemill

**Comment by simonhong** [comment]
I think this is not an issue. This comes from invalid dev ntp-si components.
Downloaded ntp-si components doesn't have all assets described in photo.json.
According to the photo.json, it has 3 campaigns. but components only includes one campagns.
Because of this, browser can't provide proper assets to NTP.

![Screenshot from 2022-02-23 18-55-20](https://user-images.githubusercontent.com/6786187/155296824-93926f27-0e8f-4540-867b-7123c0dfc085.png)

@petemill , maybe current ntp-si component in dev updater is for test-purpose only?

**Comment by petemill** [comment]
Yes someone had re-deployed staging which meant that some images went missing. The photo.json had multiple campaigns but the jpgs were only from a single campaign. I'm pretty sure this just looked like an issue with narrow viewports due to a coincidence of which SI was showing at the time.
