### ISSUE TITLE
Remove `RewardsEnabledDuration` P3A question 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21232]
## Description

Remove code for P3A question here: https://github.com/brave/brave-browser/issues/18394

Targeting 1.37.x. 

Question being replaced by https://github.com/brave/brave-browser/issues/21030 which is better defined. 

As discussed with @bsclifton @fmarier.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.37.82 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1526)

```

**Comment by LaurenWags** [comment]
Verification in progress with Google Pixel 3 XL with Android 12 running 1.37.105

- Verified the test plan from https://github.com/brave/brave-core/pull/12365

**_Clean profile_**

<details>
<summary>Case 1: Clean profile_remove_rewards enable duration metrics - InProgress</summary>

- Clean profile, launch brave and open brave://local-state file and confirm `Brave.Rewards.EnabledDuration` metric isn't shown
- Clean profile, enable rewards via BR panel and open brave://local-state file and confirm `Brave.Rewards.EnabledDuration`  metric isn't shown

</details>
