### ISSUE TITLE
[Android] Badges on Rewards icon appearing without any corresponding notifications or items

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21236]
## Description

User on Android has Rewards notifications (as if they had claims waiting or other notifications) in their browser, but there are no claims/notifications/anything for the user to view to clear these badge notifications. Clearing browser cache/data also did not remove the notification icons. (Reported by @Brave-Matt.) 

![image](https://user-images.githubusercontent.com/11497541/155209679-3256e607-7d26-45ea-97f8-075b29b8a1b8.png)

**Comment by Brave-Matt** [comment]
One user reporting this is on v1.35.103, Android 10.

**Comment by finned-palmer** [comment]
I'm currently seeing this issue on Android 11, v1.37.112.

I have a red notification badge with the number 1, when I press it I don't see any notifications or actions I can take (such as claiming. I had seen the ability to claim my BAT earlier this week, but had just not done so yet. I'd like to do that now.).

**Comment by deeppandya** [comment]
This issue should be fixed as we have added more notifications.

**Comment by Miyayes** [comment]
@deeppandya I think the idea is that the red bubble would show up before because there was supposed to be a notification, but the toast notification wasn't yet implemented? But now that the toast notifications are implemented, the red badges should always correspond to actual notifications that the user can see inside the Rewards panel?

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.48.154.
