### ISSUE TITLE
Improve deeplink support for brave://wallet 

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#21245]
## Description 

We currently allow for limited support to deeplink users from Brave Ads on desktop push notifications to brave://wallet. 

With Wallet being a high priority for MTU and driving added value for Ads customers, it would be ideal if Brave could provide additional support for deeplinking to Brave Wallet for house ads (for Brave branded products) for additional use cases, to have parity and optimize performance. 

Wallet discovery remains a key area of strategic focus. Deeplinks provide the most direct path to functional transactions from any marketing channel in the browser. 

We also are planning to introduce Swap rewards, which we could deeplink people directly to from ads and other marketing channels in the product, if we introduce better deeplink support for the cases below. 

We currently do not provide support to deeplink to brave://wallet for the following: 
- Push notifications (mobile) 
- Brave News Ads (desktop and mobile) 
- Sponsored Images (desktop and mobile) 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

User story: 

I'm a user that sees a push notification on mobile, a Brave News Ad on any OS, or a Sponsored Image on any OS for Brave Wallet. 

When I click on the ad in any ad unit context above, navigate me directly to brave://wallet.

**Comment by diracdeltas** [comment]
due to the phishing risk we also need to ensure that any links under `brave://wallet` can only be opened by trustworthy contexts like other `brave://` pages. 

1. webpages in general should not be able to link to or open wallet pages. if they attempt to, it should navigate to `about:blank` or similar.
2. i don't think arbitrary sites should be able to send a push notification that directly opens `brave://wallet`.

**Comment by lukemulks** [comment]
good points @diracdeltas - this all was under the context of the already functional use on desktop push notifications that we ran through review, which applied only to select brave:// pages. 

Same context applies here. This is only to be used by Brave, and for brave:// pages; other advertisers should definitely not be able to use brave:// links.

**Comment by lukemulks** [comment]
closing this out as @tmancey has helped with a workaround.
