### ISSUE TITLE
Sidebar item add bubble state is not handled properly after adding item

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21246]
Item add bubble should not be closed if there are adding candidates after adding items.

**STR 1** - bubble has empty area after adding item
1. Start with default sidebar items list
2. Remove bookmarks sidebar item
2. Load www.brave.com at current active tab
3. Mouse over the add button
4. Add **_brave.com_** to sidebar
5. Bubble should not have empty area
<img width="334" alt="image" src="https://user-images.githubusercontent.com/6786187/155245627-db5f4cb8-9328-47f0-8367-0388ce9bb6a6.png">

**STR 2** - add item bubble is closed
1. Start with default sidebar items list
2. Remove bookmarks sidebar item
2. Load www.brave.com at current active tab
3. Mouse over the add button
4. Add **_bookmarks_** sidebar
5. Bubble should not be hidden and bubble has **_brave.com_** item

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.37.67 Chromium: 99.0.4844.35 (Official Build) nightly (x86_64)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | macOS Version 12.3 (Build 21E5222a)

### Case 1: Bubble has empty area after adding item

Steps:

1. Start with default sidebar items list
2. Remove bookmarks sidebar item
3. Load `http://www.brave.com` at current active tab
4. Mouse over the add (`+`) button
5. `Add brave.com` to sidebar
6. Bubble should **not** have empty area

Confirmed there's no empty space in the `Add to Sidebar` bubble

example | example | example | example
---------|---------|----------|----------
<img width="1267" alt="Screen Shot 2022-02-23 at 3 24 46 PM" src="https://user-images.githubusercontent.com/387249/155427466-1aad0649-eeeb-4adb-bed2-773e461b4ba5.png"> | <img width="1075" alt="Screen Shot 2022-02-23 at 3 22 41 PM" src="https://user-images.githubusercontent.com/387249/155427511-7a2078b7-aa84-4d23-bf1a-42f8b65cedaa.png"> | <img width="1267" alt="Screen Shot 2022-02-23 at 3 25 09 PM" src="https://user-images.githubusercontent.com/387249/155427598-83f796a2-758b-4994-be36-642186381620.png"> | <img width="1075" alt="Screen Shot 2022-02-23 at 3 24 17 PM" src="https://user-images.githubusercontent.com/387249/155428018-a45be1e7-60ab-4826-bdaf-770ddac53dd7.png">


### Case 2: `Add to Sidebar` is closed

Steps:

1. Start with default sidebar items list
2. Remove bookmarks sidebar item
3. Load `brave.com` at current active tab
4. Mouse over the add (`+`) button
5. `Add bookmarks` to sidebar
6. Bubble should not be hidden and bubble has `brave.com` item

example | example | example | example
---------|---------|----------|---------
<img width="1267" alt="Screen Shot 2022-02-23 at 3 24 46 PM" src="https://user-images.githubusercontent.com/387249/155427724-c6df69c9-4ded-445f-8738-aa4360d55c87.png"> | <img width="1267" alt="Screen Shot 2022-02-23 at 3 24 59 PM" src="https://user-images.githubusercontent.com/387249/155427762-c3a3820c-41f4-4cc0-9675-216ec7628176.png"> | <img width="1267" alt="Screen Shot 2022-02-23 at 3 25 05 PM" src="https://user-images.githubusercontent.com/387249/155427829-05e90d81-99b2-46e8-9145-6093a37ea9ec.png"> | <img width="1075" alt="Screen Shot 2022-02-23 at 3 24 17 PM" src="https://user-images.githubusercontent.com/387249/155427916-684b3a60-6c3f-4008-8235-027234577549.png">

**Comment by MadhaviSeelam** [comment]
Brave |	1.37.84 Chromium: 99.0.4844.51 (Official Build) beta (64-bit) 
---|---
Revision |	d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS |	Windows 11 Version 21H2 (Build 22000.493)


Testcase 1: Add to Sidebar bubble shouldn't have empty area after adding item

- Install 1.37.x
- Launch Brave
- Remove bookmarks sidebar item from default sidebar items list
- Load `brave.com` at current active tab
- Mouse over the add (+) button
- Add brave.com to sidebar
- Bubble should not have empty area
- Verified that there's no empty space in the `Add to Sidebar` bubble

ex|ex|ex|ex|ex
---|---|---|---|---
<img width="550" alt="bookmarks sidebar" src="https://user-images.githubusercontent.com/98358127/157346502-31a425d7-a9b0-4c59-91da-0fa3e08f9fb4.png">|<img width="550" alt="removedbookmarks" src = "https://user-images.githubusercontent.com/98358127/157347611-868ef060-ab70-4c64-bfce-6b584c38bd56.png"> | <img width="550" alt="load brave" src= "https://user-images.githubusercontent.com/98358127/157346746-f0f980ba-86e2-4ca6-a69e-87882e8c4272.png"> | <img width="550" alt="mouseovertheaddbutton" src = "https://user-images.githubusercontent.com/98358127/157347013-3134a11a-757d-4ffe-b65e-96c8dc1ab1f5.png"> | <img width="550" alt="addbravetosidebar" src = "https://user-images.githubusercontent.com/98358127/157346850-b4165181-8467-43ef-8728-8d4a4557f415.png">

Testcase 2: `Add to Sidebar` is closed

- Fresh profile
- Launch Brave
- Remove bookmarks sidebar item from default sidebar items list
- Load `brave.com` at current active tab
- Mouse over the add (+) button
- `Add bookmarks` to sidebar
- Bubble should not be hidden and bubble has `brave.com` item
- Verified that bubble is displayed and has an 'Add to Sidebar' for brave.com

ex|ex|ex|ex|
---|---|---|---
<img width="550" alt="bookmarks item" src="https://user-images.githubusercontent.com/98358127/157348457-2f0aab4d-f89d-46c9-841a-6c92372540c2.png"> | <img width="550" alt="Screenshot 2022-03-08 165952" src= "https://user-images.githubusercontent.com/98358127/157348506-a36bf98d-7fb2-4e2e-b4d5-5adce71c9661.png"> | <img width="550" alt="Screenshot 2022-03-08 165924" src= "https://user-images.githubusercontent.com/98358127/157348642-8211e4db-ad2f-44e3-b9a8-97efca645422.png"> | <img width="550" alt="Screenshot 2022-03-08 170020" src = "https://user-images.githubusercontent.com/98358127/157348802-c7554e06-1a55-4666-83b6-c717074dfbac.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.95 Chromium: 99.0.4844.74 (Official Build) beta (64-bit) 
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

### Case 1: Bubble has empty area after adding item


**Confirmed there's no empty space in the `Add to Sidebar` bubble**

<details>

![image](https://user-images.githubusercontent.com/34715963/158853808-fe5ce845-de49-4b17-adeb-33cb11919825.png)
![image](https://user-images.githubusercontent.com/34715963/158853861-0fbdd931-da7f-475d-985a-dba6026483fc.png)
![image](https://user-images.githubusercontent.com/34715963/158853988-1a874f3f-10d2-4add-9dbb-cdac004b301a.png)
![image](https://user-images.githubusercontent.com/34715963/158854019-959b6d56-9447-4f37-a0df-e3560ed6bad1.png)

</details>



### Case 2: `Add to Sidebar` is closed

Steps:

1. Start with default sidebar items list
2. Remove bookmarks sidebar item
3. Load `brave.com` at current active tab
4. Mouse over the add (`+`) button
5. `Add bookmarks` to sidebar
6. Bubble should not be hidden and bubble has `brave.com` item

**Confirmed the bubble appears and has an `Add to Sidebar` item for `brave.com`**

<details>


![image](https://user-images.githubusercontent.com/34715963/158855309-47e198ea-490b-434a-9203-2c414334b9db.png)
![image](https://user-images.githubusercontent.com/34715963/158855453-275775a4-bd6a-4c9e-a4de-aa3b6b7775ae.png)
![image](https://user-images.githubusercontent.com/34715963/158855573-8db952bd-7828-4070-876b-6fcb6a358014.png)
![image](https://user-images.githubusercontent.com/34715963/158855630-c67df2db-1108-4391-9343-118b8ff1d417.png)

</details>
