### ISSUE TITLE
VPN button text should be theme/contrast-aware

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21242]
## Description 

VPN button text should be theme/contrast-aware

## Steps to Reproduce

   1.  install `1.37.65`
   2.  launch Brave
   3.  load `brave://flags`
   4. set `Enable experimental Brave VPN` to `Enabled`
   5. click to `Relaunch`
   6. open `brave://settings/manageProfile`
   7. choose a white/very light color set
   8. look at the `VPN` text in the button on the browser toolbar

## Actual result:

It's hard to read `VPN` text due to being white-on-white.

![white-on-white](https://user-images.githubusercontent.com/387249/155233941-7e78a310-2122-438e-8608-9cbc80853797.png)

## Expected result:

The `VPN` text on the button should be theme/contrast-aware.

## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.37.65 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1566)

cc @simonhong @nullhook

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.60 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.3 (Build 20G415)

Confirmed `VPN` text is still visible, changing profiles to light and dark colors

example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2022-03-21 at 12 08 01 PM" src="https://user-images.githubusercontent.com/387249/159346720-75d1efc9-a81c-48d8-aafa-f70075b86e75.png"> | <img width="1312" alt="Screen Shot 2022-03-21 at 12 08 27 PM" src="https://user-images.githubusercontent.com/387249/159346736-0e422f51-0651-4432-92a3-6a3b5c5abf61.png"> | <img width="1312" alt="Screen Shot 2022-03-21 at 12 09 12 PM" src="https://user-images.githubusercontent.com/387249/159346747-b637fd68-2b98-49fc-93c4-86ff8b79b28c.png"> | <img width="1312" alt="Screen Shot 2022-03-21 at 12 09 40 PM" src="https://user-images.githubusercontent.com/387249/159346752-8c288ef0-d6f3-4e84-ba7c-5e4dde31aace.png">

**Comment by LaurenWags** [comment]
Changing to `QA/No` per discussion in today's desktop planning meeting, testing will be covered with https://github.com/brave/brave-browser/issues/15804.
