### ISSUE TITLE
Update Ropsten Test Faucet URL to a working Faucet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21240]
## Description 
The url that we use for Ropsten Test Faucet is no longer active `https://faucet.ropsten.be/`
We need to update to a Faucet that is active.

![Screen Shot 2022-02-22 at 1 35 07 PM](https://user-images.githubusercontent.com/40611140/155215391-16d68bee-3356-464c-a5b3-9a6d4f24dc1a.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.38.104 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12388>brave/brave-core#12388</a></li>
         <li>Verified faucet link is updated to <code>https://faucet.dimensions.network/</code></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><Video src=https://user-images.githubusercontent.com/17010094/164454513-e6318e7f-b50f-413d-8ecf-02196de01e07.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/164454151-9be73bcb-389d-4e65-9af2-1e8b34d01168.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/164454136-e04c0aff-cfba-4e7b-ace1-e0fe0411e4c7.mov>
      </td>
   </tr>
</table>
