### ISSUE TITLE
Settings animation is carried over from chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21256]
## Description 

Settings animation is carried over from chrome
## Steps to Reproduce

   1. Clean profile 1.37.x nightly build with C99
   2. Navigate to brave://settings/
   3. Switch to sidebar menu settings one by one
   4. Settings animation is carried over from chrome

## Actual result:

Settings animation is carried over from chrome

![settings animation](https://user-images.githubusercontent.com/38657976/155275247-b172c1d0-22a9-4461-874c-d41940089723.gif)

## Expected result:
I think this animation should not be there

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.37.65 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1526)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mkarolin @brave/legacy_qa @rebron

**Comment by kjozwiak** [comment]
This will require `1.36.106` or newer.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.106 Chromium: 99.0.4844.45 (Official Build) (x86_64)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | macOS Version 11.6.3 (Build 20G415)

Followed the steps to reproduce and confirmed menu-category transitions are smooth.

![smooth-transition](https://user-images.githubusercontent.com/387249/155766303-dec0df2e-db93-482a-bcbb-b76008ec5b22.gif)
