### ISSUE TITLE
Brave history tooltip icons are carried over from chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21259]
## Description 

Brave history tooltip icons are carried over from chrome
## Steps to Reproduce

   1. Clean profile 1.37.x
   2. Open a few websites 
   3. Navigate to brave://history 
   4. Tooltip icons are carried over from chrome in brave://histrory 

## Actual result:

Brave history tooltip icons are carried over from chrome  

![image](https://user-images.githubusercontent.com/38657976/155294926-49812ef9-552e-4931-bc90-f1516ea9d258.png)

## Expected result:
Tooltip icons should not be shown in brave

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.37.65 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1526)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by kjozwiak** [comment]
This will require `1.36.106` or newer.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.36.106 Chromium: 99.0.4844.45 (Official Build) (x86_64)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | macOS Version 12.2.1 (Build 21D62)
```

Verified no icons on brave://history

<img width="1196" alt="History" src="https://user-images.githubusercontent.com/28145373/155747249-9428783f-6928-4a5e-9531-b053602d8c85.png">
