### ISSUE TITLE
Asset list search is broken

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#21263]
https://user-images.githubusercontent.com/3684187/155314218-1fe84316-c433-4381-84f1-44dd18742070.mov

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.36.112 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 11 Version 21H2 (Build 22000.527)
```

* Verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/12395#issue-1149229129
* Verified able to search visible assets on Send tab
* Verified able to search for assets on Swap tab for both from and to swap fields

![example](https://user-images.githubusercontent.com/2602313/157600756-d551f44c-bb2a-4df6-8cad-ebe9fbbf8996.gif)
