### ISSUE TITLE
Unable to create sync chain without entering a device name

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2126]
## Description 

Unable to create sync chain without entering a device name

## Steps to Reproduce

   1. Launch browser with `--enable-brave-sync`
   2. Open `brave://sync`
   3. Click on `I am new to Sync`
   4. Click `Create Sync` button on popup modal, doesn't use the placeholder text to create a sync chain. Only creates after entering a device name

## Actual result:

https://youtu.be/shYejuYzzKw

## Expected result:
Should be able to user placeholder text to create a sync chain similar to b-l

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Removed QA pass label. Need to verify it against beta again

**Comment by GeetaSarvadnya** [comment]
Verification Passed on

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Windows

- Verified the STR mentioned in issue.
![image](https://user-images.githubusercontent.com/38657976/49467185-dd98ed00-f827-11e8-9c99-348a47f09f71.png)
