### ISSUE TITLE
Switching back and forth to NTP causes News feed to show up rather than retaining NTP view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21269]
## Description 
Switching back and forth to NTP causes news feed to jump into view rather than retaining NTP view

## Steps to reproduce 

   1. Install 1.36.x beta build and enable news
   2. Open a new tab, shows NTP view with widgets 
   3. Switch to an existing tab or open a second tab and go back to original tab, News feed jumps to fill NTP view

## Actual result 

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/155353883-f80675be-d0f7-4eed-9e3b-6a6738d4807d.mp4> | <video src=https://user-images.githubusercontent.com/17010094/155353941-787c5ff1-64d9-4109-95b5-7c23a92f2348.mp4>

## Expected result
Should retain NTP view unless user scrolls down the news feed

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.36.104

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.38.63, Chromium 100.0.4896.46`

Followed the steps to reproduce, and confirmed no `fill-in` on new-tab pages with Brave News.


https://user-images.githubusercontent.com/387249/159546947-db3ee694-1245-467b-91ce-b01e02d1e35a.mp4

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `Pixel 6` running `Android 12` using `1.37.105 Chromium: 100.0.4896.46`
* Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 12` using `1.37.105 Chromium: 100.0.4896.46`

Verified using the STR/Cases and examples via https://github.com/brave/brave-browser/issues/21269#issue-1148259823 & https://github.com/brave/brave-browser/issues/21269#issuecomment-1075460576.
