### ISSUE TITLE
Clear data graphics shows the incognito icon in the PT and TOR tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21261]
## Description 

Clear data graphics shows the incognito icon in the PT and TOR tabs

## Steps to Reproduce

   1. Clean profile 1.35.x or 1.37.x
   2. Open a PT/TOR window
   3. Open Hamburger menu
   4. Navigate to More tools->clear browsing data

## Actual result:

Clear data graphics shows the incognito icon in the PT and TOR tabs
![image](https://user-images.githubusercontent.com/38657976/155305736-ac0507b8-6f91-4ad1-ae9f-ff24fa28f9f8.png)

## Expected result:
Looks like the graphic needs to be removed

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.37.65 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1526)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by GeetaSarvadnya** [comment]
@rebron Looks like the graphic needs to be removed from brave as it's driven from chrome.

**Comment by LaurenWags** [comment]
Reproduced with

```
Brave | 1.35.104 Chromium: 98.0.4758.109 (Official Build) (x86_64)
-- | --
Revision | 03268453da2c7409eb1ee934d97abfc6f3b45420-refs/branch-heads/4758@{#1179}
OS | macOS Version 12.2.1 (Build 21D62)
```

<img width="385" alt="Screen Shot 2022-02-25 at 4 00 20 PM" src="https://user-images.githubusercontent.com/28145373/155802356-1aeb7b34-8d60-4f4b-a4a8-874703d2da71.png">

**Comment by Sam-Sibley** [comment]
To clarify the expected result, do we expect this graphic to be removed entirely, so it is a text based dialog.
Or
Do we expect the Icongito icon to be removed from the graphic itself

**Comment by kjozwiak** [comment]
The above will require `1.37.99` or higher for verifications on `1.37.x`

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.37.106 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the STR from the description and ensured the graphics is removed from the PT and TOR tab windows

Private window | TOR window
--- | ---
![image](https://user-images.githubusercontent.com/38657976/160350912-629421bb-6a41-4e8a-bd4e-37301361a3b1.png) | ![image](https://user-images.githubusercontent.com/38657976/160351173-c3ec91cd-b509-4f65-9a68-82c0e8b68aad.png)
