### ISSUE TITLE
Brave News setting bar is not shown on the tab when loading homepage

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21267]
## Description 
Brave News setting bar is not shown on the tab when loading homepage

## Steps to reproduce 

   1. Enable News
   2. Scroll down and load an article
   3. Click on the home button and scroll down the feed, settings bar is not shown
   4. Open a new tab and scroll down feed, shows settings bar

## Actual result 

https://user-images.githubusercontent.com/17010094/155342353-3d4a19f1-3d80-4a8c-924b-9a64df4d75ff.mp4

## Expected result
Should show the settings bar when scrolled down the news feed

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.36.104

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe

**Comment by stephendonner** [comment]
I can still reproduce this using Brave `1.38.63, Chromium 100.0.4896.46` on a `Google Pixel XL` running `Android 9.0`.

**Comment by stephendonner** [comment]
> I can still reproduce this using Brave `1.38.63, Chromium 100.0.4896.46` on a `Google Pixel XL` running `Android 9.0`.

Filed https://github.com/brave/brave-browser/issues/21833 for this.
