### ISSUE TITLE
Add Swap functionality to Polygon network with 0x

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#21264]
**Definition of done:**
1. Swap tab is active on Polygon mainnet.
2. A preloaded list of ERC20 tokens on Polygon is available.
3. Polygon logo is displayed in the appropriate places - network, MATIC token, network overlay on tokens, etc.
4. Users are able fetch quotes and exchange tokens on Polygon.

**Comment by skylarsdaddy011316** [comment]
Fuck off

**Comment by kjozwiak** [comment]
Requires `1.37.94` or later for verification using `1.37.x`.

**Comment by Uni-verse** [comment]
Verification PASSED using 

```
1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
--
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.1 (Build 21C52)

```
- [x] Swap tab is active on Polygon mainnet.
- [x] A preloaded list of ERC20 tokens on Polygon is available.
- [x] Polygon logo is displayed in the appropriate places - network, MATIC token, network overlay on tokens, etc.
- [x] Users are able fetch quotes and exchange tokens on Polygon. 

[Swap Txn Hash](https://polygonscan.com/tx/0x961042100f72761bc30de6ea83b9363fe91b1a55069706a72e41c7c5c0e2b2c6)

1 | 2 | 3 | 4 | 5
-|-|-|-|-
<img width="277" alt="Screen Shot 2022-03-25 at 5 17 55 PM" src="https://user-images.githubusercontent.com/17885425/160217188-b06dad4c-3bf8-45b8-91dc-8d44b22d9ea7.png"> | <img width="330" alt="Screen Shot 2022-03-25 at 5 18 05 PM" src="https://user-images.githubusercontent.com/17885425/160217189-d4b7bfd7-bafe-434f-9b57-cdf7f8392933.png"> | <img width="639" alt="Screen Shot 2022-03-25 at 5 21 26 PM" src="https://user-images.githubusercontent.com/17885425/160217191-e13320fb-4801-4951-9700-3d30ab7193d9.png"> | <img width="350" alt="Screen Shot 2022-03-25 at 5 23 30 PM" src="https://user-images.githubusercontent.com/17885425/160217193-f5cee681-fecc-4efc-90ed-cba968212c2b.png"> |<img width="403" alt="Screen Shot 2022-03-25 at 5 23 19 PM" src="https://user-images.githubusercontent.com/17885425/160217388-48824fa9-958e-49e1-af5d-58de47da7d91.png">
