### ISSUE TITLE
Brave branded bookmarks folder icons are not shown in the bookmarks manager

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21262]
## Description 

Brave branded bookmarks folder icons are not shown in bookmarks manager

## Steps to Reproduce

   1. Clean profile 1.37.x
   2. Import bookmarks from Firefox or chrome 
   3. Open brave://bookmarks/
   4. Bookmarks folders are not brave branded

## Actual result:

Brave branded bookmarks folder icons are not shown in the bookmarks manager

**1.37.x**
![image](https://user-images.githubusercontent.com/38657976/155310229-90effed8-4813-4615-95b1-6730847c4ecb.png)

**1.35.x**
![image](https://user-images.githubusercontent.com/38657976/155311222-8072e9d9-17dc-42b1-8ed4-6ecbe7431af6.png)

## Expected result:

Bookmarks folder should have brave branded folder icons
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by mkarolin** [comment]
Both of those icons come from Chromium. We didn't rebrand those. The change is part of Chromium rebranding in cr99.
