### ISSUE TITLE
Brave Updates Experience

### ISSUE THREAD

**Issue by jazzybeat** [brave/brave-browser#21276]
I really got tired of seeing these annoying never-ending updates. While I understand the importance of security I don't believe every update is critical and we need to have more flexibility on how often this dialog should pop up.

My suggestion is below.

![Brave Update 1](https://user-images.githubusercontent.com/815706/155380178-7c8d50e9-1868-4201-a8f1-a9404a630d8c.png)

![Brave Update 2](https://user-images.githubusercontent.com/815706/155379682-2d72db6c-7da4-4d84-bfea-ea10aaf98db4.png)

**Comment by rebron** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/9562
