### ISSUE TITLE
When wallet is not yet created and user tries to reset the wallet, the wallet reset process should not continue

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21274]
## Description 

When wallet is not yet created and user tries to reset the wallet, the wallet reset process should not continue

## Steps to Reproduce

   1. Clean profile 1.35.x or 1.37.x
   2. Open brave://rewards
   3. Tap on `Manage Your wallet`
   4. Click on Reset 
   5. Message is shown as `Are you sure you want to reset your Rewards Wallet?`
   6. This message needs to be rephrased, when the user tries to reset the wallet when the wallet is not created, the user should get a message as the `wallet is not yet created` and it should not continue the reset process

## Actual result:

When wallet is not yet created and the user tries to reset the wallet, the wallet reset process should not continue
![image](https://user-images.githubusercontent.com/38657976/155371492-c0a76f0a-3e99-4ae6-9285-09dbe7364047.png)

## Expected result:

When wallet is not yet created and user tries to reset the wallet, the wallet reset process should not continue
## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.37.68 Chromium: 99.0.4844.35 (Official Build) nightly (64-bit)
-- | --
Revision | f60a827ddb87f1c403e07713751a5551d5856ac0-refs/branch-heads/4844@{#579}
OS | Windows 10 Version 21H2 (Build 19044.1526)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @Miyayes @LaurenWags

**Comment by LaurenWags** [comment]
@Miyayes should the whole "Manage your wallet" area even be shown if you haven't opted into Rewards yet?

**Comment by Miyayes** [comment]
It makes the most sense if we just not show the Manage Your Wallet button.

**Comment by Miyayes** [comment]
No longer valid.
