### ISSUE TITLE
Extra translation settings option under language settings with C99

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#21285]
## Description 
Translation settings option introduced with C99 under Settings > Languages. 

## Steps to reproduce 

Precondition: Nightly installed with Chromium 99.x

   1. Navigate to Settings > Languages
   2. Observe menu content
   3. 

## Actual result 
Translation settings option displayed

![Screen Shot 2022-02-23 at 1 42 35 PM](https://user-images.githubusercontent.com/17885425/155421632-c44438e9-0490-457a-86b9-ee695f49256c.png)

## Expected result
Translation should be removed from the language settings

![Screen Shot 2022-02-23 at 1 44 06 PM](https://user-images.githubusercontent.com/17885425/155421685-3ad911c8-844c-4c4d-9bc3-b2361122c800.png)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `Android ARM`
   - Device type (Phone, Tablet, Phablet): `Galaxy GS 21 5G`
   - Android version: `Android 12`
   
## Brave version
`1.37.67, Chromium 99.0.4844.35`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
This will require `1.36.106` or newer.

**Comment by Uni-verse** [comment]
Verification completed using `1.36.107, Chromium 99.0.4844.45`

Device: `Samsung Galaxy S21` | `Android 12` | `ARM install`

- Verified translation settings section is removed in the language settings menu

Settings | Version
-|-
![Screen Shot 2022-02-28 at 1 53 59 PM](https://user-images.githubusercontent.com/17885425/156065327-1035cbe8-e684-435d-bc54-3adbdcb3f0a4.png) | ![Screen Shot 2022-02-28 at 1 54 35 PM](https://user-images.githubusercontent.com/17885425/156065330-8e24ea48-1f54-4c08-bd09-6016f7d7c1ac.png)

**Comment by Uni-verse** [comment]
Note: 'The Brave's Language' section is a new feature introduced in C99. User is now able to change settings within this menu without accessing the system settings.

https://bravesoftware.slack.com/archives/D02U31T0UG0/p1646086804216629
