### ISSUE TITLE
Ephemeral storage tests returning unexpected results

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#21289]
## Description 
Ephemeral storage tests returning different results for scenarios where cooking blocking is set to allow and blocked

Failing on 1.37.42, 1.37.67
Impacts C98, C99 Versions

## Steps to reproduce 

   1. Clean install
   2. Open new tab and navigate to url: https://dev-pages.brave.software/storage/ephemeral-storage.html
   3. Confirm Cookie blocking drop down has 'Cross-site cookie blocking' selected by default
   4. Begin Test by Tapping 'Start test' 
   5. Follow instructions through step # 3
   6. Observe results for test # 3
   7. Proceed to test # 4
   8. Observe results for test # 4
   9. Reset test by tapping the 'reset test' button
   10. Select 'Allow All Cookies' from dropdown
   11. Confirm Shields settings allow all cookies
   12. Begin test
   13. Follow instruction through test # 4
   14. Observe results for test # 4
 

## Actual result 
Not as expected

 Cookie Setting | Version | Test | Status 
 -|-|-|-
 Cross Site Blocked | 1.37.42 (C98) | Test #3 | FAIL
 Cross Site Blocked | 1.37.42 (C98) | Test #4 | FAIL
 All Allowed | 1.37.42 (C98) | Test #4 | FAIL
  Cross Site Blocked | 1.37.67 (C99) | Test #3 | FAIL
 Cross Site Blocked | 1.37.67 (C99) | Test #4 | FAIL
 All Allowed | 1.37.67 (C99) | Test #4 | FAIL
 

## Expected result
see expected result on test page

## Issue reproduces how often 
Easily, Repro rate: 100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21 
   - Android version: Android 12
   
## Brave version
`1.37.42, Chromium 98.x`
`1.37.67, Chromium 99.0.4844.35`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Uni-verse** [comment]
@timchilds Checked this on `Nightly` build for `MacOS` (`1.42.16 Chromium: 103.0.5060.53`) and I am seeing similar failures for the ephemeral tests. For the `Block cross-site cookie` tests, steps 3 & 4 are not returning the expected results and for `Allow all cookie` tests, step 4 is returning different result than expected. Perhaps these are tested differently on Desktop?

CC: @kjozwiak @srirambv

**Comment by srirambv** [comment]
@Uni-verse  just going through the steps again and I see different values when the test is done for Allow all cookies only not for block cross site cookies. Even if you just start the test with allow all cookies on the site it repro's 

cc: @pes10k

**Comment by Uni-verse** [comment]
Closing this one as invalid due to testing/tester/STR error. The ephemeral storage tests are working as expected on Android ARM/Android ARM Tablet using the latest 1.41.x release build.

cc: @kjozwiak @timchilds
