### ISSUE TITLE
adding summary for `Show autocomplete in address bar` toggle

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#21287]
## Description 

We should add a short summary under the `Show autocomplete in address bar` setting that explains what it does as we have several `autocomplete` settings available which might confuse users.

For reference, it was added in `1.36.x` via https://github.com/brave/brave-browser/issues/19647.

## Steps to reproduce 

   1. launch `1.36.x` (this was added via https://github.com/brave/brave-browser/issues/19647)
   2. go into `Hamburger Menu` -> `Settings` -> `Brave Shields & privacy`
   3. scroll to the bottom and notice that `Show autocomplete in address bar` doesn't have a summary

## Actual result 

![image](https://user-images.githubusercontent.com/2602313/155434731-1399db7b-1d03-41a5-b634-c375436e45a3.png)

## Expected result

We should add a short summary to explain what this toggle does as users might get confused/not have enough context

## Issue reproduces how often 

100% reproducible using the STR mentioned above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A` (it will be once `1.36.x` is released)
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 12`
   
## Brave version

```
1.37.67 Chromium: 99.0.4844.35
```

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @anthonypkeane

**Comment by timchilds** [comment]
@rmcfadden3 can you please help with copy for the summary? Something like:

> Displays website suggestions in the address bar based on your history and bookmarks.

**Comment by rmcfadden3** [comment]
@timchilds — I like your description. Just a couple small tweaks to:

"Displays website suggestions based on your bookmarks and browsing history."

I removed "in the address bar" since that info already appears in the name of the setting.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (32-bit)
--- | ---
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Android 13;
```

![summaryUpdate](https://user-images.githubusercontent.com/2602313/176259560-9c88a5e1-3087-4069-90cf-7bfa5af56f70.png)
