### ISSUE TITLE
Sync warn modal needs refactoring

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2128]
## Description 

Sync warn modal needs refactoring

## Steps to Reproduce

   1. Enable sync on beta with `--enable-brave-sync`
   2. Click on `I have an existing Sync code` 
   3. Click `Setup Sync` without entering any code or device name, shows the warn message which is just plain text (see screenshot)

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/48456129-e0a23f80-e78b-11e8-8f6e-6cebf61d3ef9.png)
![image](https://user-images.githubusercontent.com/17010094/48456328-a4bbaa00-e78c-11e8-84ef-61d6cde1934b.png)

## Expected result:
Should show proper error message which is refactored

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

#2126 also needs a warning similar to this if a device name is mandatory
@rebron @bbondy @kjozwiak added to 1.x backlog as this is just a refactor which isn't priority but if needed please add it to 0.57.x milestone.

**Comment by cezaraugusto** [comment]
cc @bradleyrichter @rossmoody

**Comment by kjozwiak** [comment]
Assuming this will be addressed in the sync v2 ui?

**Comment by cezaraugusto** [comment]
ya correct

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/49952055-55020700-ff21-11e8-8744-53f8a5c3f0ad.png)
