### ISSUE TITLE
blank tab shows instead of second NTP SI - follow up to 17450

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#21282]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/17450

Only seeing one NTP SI campaign, not 2 as expected per https://bravesoftware.slack.com/archives/CQGTGBNH1/p1644989014004659.

## Steps to Reproduce

   1. Clean profile with 1.36.104, launched with `/Applications/Brave\ Browser\ Beta.app/Contents/MacOS/Brave\ Browser\ Beta --args --enable-logging=stderr --brave-ads-staging --rewards=staging=true --use-dev-goupdater-url`.
   2. Opened new tabs looking for NTP SI

Video: https://bravesoftware.slack.com/archives/CQGTGBNH1/p1645648329981859?thread_ts=1644989014.004659&cid=CQGTGBNH1

## Actual result:

Sometimes saw NTP SI from one campaign, but when I should have seen NTP SI from the second campaign it was just a blank tab:

<img width="1423" alt="Screen Shot 2022-02-23 at 3 07 24 PM" src="https://user-images.githubusercontent.com/28145373/155404066-25074070-d367-4906-a167-6507308fdd19.png">

## Expected result:

Multiple NTP SI campaigns showing as expected.

## Reproduces how often: 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes 1.36.x
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @petemill

**Comment by petemill** [comment]
This was because someone had deployed different content to the staging server, whilst they were testing a branch of code from before the support for multiple campaigns was merged. Therefore it sent an update to all devices with images from only 1 campaign, even though the SI data file itself contained metadata about all the campaigns. Hence the blank background and logos.
