### ISSUE TITLE
brave won't start

### ISSUE THREAD

**Issue by jefer94** [brave/brave-browser#21281]
## Description 

brave won't start

## Steps to Reproduce

Open `Brave Nightly` version 99 in `Windows 11`

## Actual result:

brave won't start

## Expected result:

Can open Brave without it crash

## Reproduces how often: 

Every time I run Brave, of 20 try one could open but I close if because I try to open the browser in compatibility mode and I close it to try without it, after y try the same configuration but doesn't work

## Brave version (brave://version info)

99

## Version/Channel Information:

- Can you reproduce this issue with the current release? 

???

- Can you reproduce this issue with the beta channel? 

???

- Can you reproduce this issue with the nightly channel? 

Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 

No

- Does the issue resolve itself when disabling Brave Rewards? 

No

- Is the issue reproducible on the latest version of Chrome? 

The latest Chrome nightly is the version 101 and it works

## Miscellaneous Information:

I wan't lose my tabs 🙁

**Comment by bsclifton** [comment]
@jefer94 curious if you're running any of the following:
- Anti-virus software
- Epic Games (Fortnite, etc) - which installs Easy Anti-Cheat
- Any other gaming programs (anti-cheat software like Punkbuster or GameGuard)

Something you can try is to rename the `brave.exe` executable as `chrome.exe` and see if that works

**Comment by bsclifton** [comment]
Also @jefer94  - we did have a known crash captured with https://github.com/brave/brave-browser/issues/21218 which was recently fixed. If you are able to update Nightly (you can re-download and install over current install; you won't lose anything https://brave.com/download-nightly/) that might fix the issue too

**Comment by jefer94** [comment]
I'm try to reinstall it, the web when the web installation ends it not open
![image](https://user-images.githubusercontent.com/3018142/155424440-f89f2582-94c2-42a6-93c3-7b2af3bf98d3.png)

**Comment by jefer94** [comment]
I also can't see the window of Brave is never appear, but exist many process of `brave.exe` and then they are close without do anything

**Comment by jefer94** [comment]
> @jefer94 curious if you're running any of the following:

> - Anti-virus software

Windows defender

> - Epic Games (Fortnite, etc) - which installs Easy Anti-Cheat

The anticheat of Valorant

> - Any other gaming programs (anti-cheat software like Punkbuster or GameGuard)

I think nothing

> Something you can try is to rename the brave.exe executable as chrome.exe and see if that works

Let me try

**Comment by jefer94** [comment]
That's normal?

![image](https://user-images.githubusercontent.com/3018142/155425187-dde7d0ec-2592-4770-8afe-8299aac20db3.png)

**Comment by jefer94** [comment]
And now I can open the browser 🤷‍♂️, I´ll to let know tomorrow about if the issue is resolved, I wan't close it again 😂

**Comment by jefer94** [comment]
The bug is not solved, I need try to open the browser many times to can open it

![image](https://user-images.githubusercontent.com/3018142/155496046-3c2b88ae-b915-4520-a9d4-be900b202f08.png)

**Comment by rebron** [comment]
cc: @Brave-Matt

**Comment by Brave-Matt** [comment]
@jefer94 can you try launching hte browser using the following steps and see i this makes any difference? Note that these steps are for Windows 10, but should work just fine for Win11 as well:

1. Find the shortcut for Brave (generally on Desktop), right-click and select `Properties` from the context menu.
2. Click into the “Target” field, and type `--disable-gpu` at the end of the path. Note that you must type this outside of the quotes with a space between the flag and quotes. It should look something like this:

    ![image](https://user-images.githubusercontent.com/3299098/155759338-ccb2ab80-e480-4428-bb84-bf9a76185203.png)
3. Click `Apply` then `OK` then open the modified shortcut you just created.
4. Assuming this worked and you’re able to view Brave, open the main menu on the top-right
Navigate to `Settings --> Advanced --> System --> Hardware Acceleration`
Ensure this option is off. If not, toggle it off and relaunch
5. Now, return to the modified shortcut, remove the `--disable-gpu` flag from the Target path and launch Brave using that shortcut.

**Comment by jefer94** [comment]
I will try this solution the next time 👍

**Comment by jefer94** [comment]
I had two days the browser is not crashed

**Comment by jefer94** [comment]
I don't need follow the instrutions of @Brave-Matt to solved this issue, after a update the browser stop of fail
