### ISSUE TITLE
PWA won't launch after upgrading to v1.35.104

### ISSUE THREAD

**Issue by artooro** [brave/brave-browser#21295]
## Description 

I have a couple of PWA's that I use on a daily basis, and after upgrading Brave to v1.35.104 this morning they both bounce a couple of times in the dock but fail to open.

## Steps to Reproduce

   1. Attempt to open a PWA app that worked in previous version (1.35.103)

## Actual result:

The app bounces a couple of times and in the console log I see the following error

## Expected result:
For the app to open

## Reproduces how often: 

Every time

## Brave version (brave://version info)

1.35.104 Chromium: 98.0.4758.109 (Official Build) (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I downgraded my Brave installation to v1.35.103 and now the PWA apps open again.

**Comment by kjozwiak** [comment]
@artooro thanks for the feedback/report 👍 We're aware of the issue and will use https://github.com/brave/brave-browser/issues/21302 as the main issue to track the work. We'll get this fixed via `1.36.x` which is scheduled to be released Tuesday as per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates.
