### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by albas99** [brave/brave-browser#21303]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.35.104  Chromium: 98.0.4758.109
Operating System: Mac OS X 12.2.1

URL (if applicable) where crash occurred:
All my PWAs(YouTube, YouTube Music, Typefully, Daily Dev, Whimsical, Draw io, Replit)
Can you reproduce this crash?
Just open any of the brave PWAs

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/47df0000-4796-cc07-0000-000000000000
Another Crash ID: crash/41da0000-4796-cc07-0000-000000000000
Another Crash ID: ace30000-4796-cc07-0000-000000000000

**Comment by albas99** [comment]
There's a more detailed version of the same issue created here #21302

**Comment by rebron** [comment]
Closing as duplicate.
