### ISSUE TITLE
PWAs do not launch after upgrading to V1.35.104

### ISSUE THREAD

**Issue by craigmdennis** [brave/brave-browser#21302]
## Test plan
1. Fresh profile
2. Visit https://twitter.com
3. Go to hamburger menu; pick `More tools` > `Create shortcut...`
4. When window pops up, check the box `Open in new window`

### Expected result
PWA should work; you can use it (sign into Twitter, etc).

### Actual result
Twitter PWA will crash immediately

## Description
Here is an associated community post: https://community.brave.com/t/updating-to-1-35-104-breaks-all-pwas/346680

This is from the Mac Console when opening the install dialog, installing, and trying to open the installed app:

```
error	17:45:39.637301+0000	kernel	Sandbox: mdworker_shared(7777) deny(1) file-read-data /Users/craigmdennis/Applications/Brave Browser Apps.localized/.localized ()
error	17:45:39.642031+0000	mdworker_shared	Error (non-fatal) enumerating <private>: Error Domain=NSCocoaErrorDomain Code=257 "The file “.localized” couldn’t be opened because you don’t have permission to view it." UserInfo={NSURL=file:///Users/craigmdennis/Applications/Brave%20Browser%20Apps.localized/.localized, NSFilePath=/Users/craigmdennis/Applications/Brave Browser Apps.localized/.localized, NSUnderlyingError=0x157724780 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
error	17:45:39.703677+0000	mdworker_shared	Error (non-fatal) enumerating <private>: Error Domain=NSCocoaErrorDomain Code=257 "The file “.localized” couldn’t be opened because you don’t have permission to view it." UserInfo={NSURL=file:///Users/craigmdennis/Applications/Brave%20Browser%20Apps.localized/.localized, NSFilePath=/Users/craigmdennis/Applications/Brave Browser Apps.localized/.localized, NSUnderlyingError=0x152e21820 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
error	17:45:40.179830+0000	tccd	failed to get text offset for /Users/craigmdennis/Applications/Brave Browser Apps.localized/Twitter.app/Contents/MacOS/app_mode_loader[7778]: (#3) No such process
error	17:45:40.687342+0000	kernel	1 duplicate report for Sandbox: mdworker_shared(7777) deny(1) file-read-data /Users/craigmdennis/Applications/Brave Browser Apps.localized/.localized ()
error	17:45:40.758764+0000	tccd	failed to get text offset for /Users/craigmdennis/Applications/Brave Browser Apps.localized/Twitter.app/Contents/MacOS/app_mode_loader[7783]: (#3) No such process
error	17:45:43.861502+0000	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for accessing={<TCCDProcess: identifier=app_mode_loader, pid=7787, auid=501, euid=501, binary_path=/Users/craigmdennis/Applications/Brave Browser Apps.localized/Twitter.app/Contents/MacOS/app_mode_loader>}, requesting={<TCCDProcess: identifier=com.apple.appleeventsd, pid=505, auid=55, euid=55, binary_path=/System/Library/CoreServices/appleeventsd>},
error	17:45:43.994489+0000	runningboardd	RBSStateCapture remove item called for untracked item 396-375-4410 (target:[app<application.com.brave.Browser.app.jgeocpdicgmkeemopbanhokmhcgcflmi.8979265.8979274(501)>:7787])
error	17:45:43.994535+0000	runningboardd	RBSStateCapture remove item called for untracked item 396-346-4411 (target:[app<application.com.brave.Browser.app.jgeocpdicgmkeemopbanhokmhcgcflmi.8979265.8979274(501)>:7787])
error	17:45:43.994573+0000	runningboardd	RBSStateCapture remove item called for untracked item 396-346-4409 (target:[app<application.com.brave.Browser.app.jgeocpdicgmkeemopbanhokmhcgcflmi.8979265.8979274(501)>:7787])
error	17:45:44.003897+0000	kernel	Sandbox: gamed(2853) deny(1) file-read-data /Users/craigmdennis/Applications/Brave Browser Apps.localized/Twitter.app
error	17:45:44.286789+0000	tccd	failed to get text offset for /Users/craigmdennis/Applications/Brave Browser Apps.localized/Twitter.app/Contents/MacOS/app_mode_loader[7793]: (#3) No such process
error	17:45:44.288223+0000	runningboardd	RBSStateCapture remove item called for untracked item 396-346-4417 (target:[app<application.com.brave.Browser.app.jgeocpdicgmkeemopbanhokmhcgcflmi.8979265.8979274(501)>:7793])
error	17:45:44.288264+0000	runningboardd	RBSStateCapture remove item called for untracked item 396-568-4415 (target:app<application.com.brave.Browser.app.jgeocpdicgmkeemopbanhokmhcgcflmi.8979265.8979274(501)>)
error	17:45:46.067034+0000	tccd	failed to get text offset for /Users/craigmdennis/Applications/Brave Browser Apps.localized/Twitter.app/Contents/MacOS/app_mode_loader[7805]: (#3) No such process
```

_Originally posted by @craigmdennis in https://github.com/brave/brave-browser/issues/7205#issuecomment-1050105821_

**Comment by albas99** [comment]
Same issue here, at first I thought it was with. my computer alone and created an issue directly from the brave crashes page with the crash ID. Guess I'll just close that issue and mention this issue for more clarification.

**Comment by bsclifton** [comment]
Seems the root cause is this commit:
https://chromium.googlesource.com/chromium/src/+/e660f5610cf324520b9db9ce86259424df1f15fb

Need to understand what went wrong here. Callstack looks like this:
```
[ 00 ] crash_reporter::DumpWithoutCrashing()
[ 01 ] crash_reporter::DumpWithoutCrashing()
[ 02 ] base::debug::DumpWithoutCrashing()
[ 03 ] (anonymous namespace)::DumpError(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
[ 04 ] apps::AppShimManager::BuildAppShimRequirementStringFromFrameworkRequirementString(__CFString const*)
[ 05 ] apps::AppShimManager::IsAcceptablyCodeSigned(int) const
[ 06 ] apps::AppShimManager::OnShimProcessConnectedAndAllLaunchesDone(std::__1::unique_ptr<AppShimHostBootstrap, std::__1::default_delete<AppShimHostBootstrap> >, apps::AppShimManager::ProfileState*, chrome::mojom::AppShimLaunchResult)
[ 07 ] apps::AppShimManager::LoadAndLaunchApp_OnProfilesAndAppReady(std::__1::vector<base::FilePath, std::__1::allocator<base::FilePath> > const&, apps::AppShimManager::LoadAndLaunchAppParams const&, base::OnceCallback<void (apps::AppShimManager::ProfileState*, chrome::mojom::AppShimLaunchResult)>)
[ 08 ] base::internal::Invoker<base::internal::BindState<void (apps::AppShimManager::*)(std::__1::vector<base::FilePath, std::__1::allocator<base::FilePath> > const&, apps::AppShimManager::LoadAndLaunchAppParams const&, base::OnceCallback<void (apps::AppShimManager::ProfileState*, chrome::mojom::AppShimLaunchResult)>), base::WeakPtr<apps::AppShimManager>, std::__1::vector<base::FilePath, std::__1::allocator<base::FilePath> >, apps::AppShimManager::LoadAndLaunchAppParams, base::OnceCallback<void (apps::AppShimManager::ProfileState*, chrome::mojom::AppShimLaunchResult)> >, void ()>::RunOnce(base::internal::BindStateBase*)
[ 09 ] base::internal::Invoker<base::internal::BindState<content::RenderFrameHostImpl::RunBeforeUnloadConfirm(bool, base::OnceCallback<void (bool)>)::$_10, base::OnceCallback<void (bool)> >, void (bool, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&)>::RunOnce(base::internal::BindStateBase*, bool, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&)
[ 10 ] apps::AppShimManager::LoadProfileAndApp_OnAppEnabled(base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, base::OnceCallback<void (Profile*)>)
[ 11 ] base::internal::Invoker<base::internal::BindState<void (extensions::BluetoothLowEnergyEventRouter::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, base::OnceCallback<void ()>), base::WeakPtr<extensions::BluetoothLowEnergyEventRouter>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, base::OnceCallback<void ()> >, void ()>::RunOnce(base::internal::BindStateBase*)
[ 12 ] apps::AppShimManager::LoadProfileAndApp_OnProfileAppRegistryReady(base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, base::OnceCallback<void (Profile*)>)
[ 13 ] base::internal::Invoker<base::internal::BindState<void (extensions::BluetoothLowEnergyEventRouter::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, base::OnceCallback<void ()>), base::WeakPtr<extensions::BluetoothLowEnergyEventRouter>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, base::OnceCallback<void ()> >, void ()>::RunOnce(base::internal::BindStateBase*)
[ 14 ] <name omitted>
[ 15 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*)
[ 16 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[ 17 ] base::MessagePumpCFRunLoopBase::RunWork()
[ 18 ] base::mac::CallWithEHFrame(void () block_pointer)
[ 19 ] base::MessagePumpCFRunLoopBase::RunWorkSource(void*)
```

**Comment by kjozwiak** [comment]
Will require `1.36.108` or higher.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.36.108 Chromium: 99.0.4844.51 (Official Build) (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)
```

<details>
<summary>Case 1 - confirming shortcut does not crash on launch - PASSED</summary>

Verified steps from https://github.com/brave/brave-browser/issues/21302#issuecomment-1050189531

1. Visited site
2. Open hamburger menu
3. Select More Tools > Create Shortcut
4. Select "Open as window" > Create
5. Shortcut opens and does not crash
6. Close shortcut window, leave browser open
7. Open from created shortcut under /Users/<username>/Applications/Brave Browser Apps
8. Shortcut opens and does not crash
9. Close browser and shortcut window
10. Open from created shortcut under /Users/<username>/Applications/Brave Browser Apps
11. Browser and shortcut window open and do not crash
12. Close browser
13. Put shortcut in dock
14. Open shortcut from dock
15. Browser and shortcut open and do not crash

</details>

**Comment by stephendonner** [comment]
## Verified `PASSED` with

Brave | 1.36.108 Chromium: 99.0.4844.51 (Official Build) (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.3 (Build 20G415)

<details>
<summary>Case 1 - confirming shortcut does not crash on launch - PASSED</summary>

Verified steps from https://github.com/brave/brave-browser/issues/21302#issuecomment-1050189531

1. Visited site (brave.com)
2. Open hamburger menu
3. Select More Tools > Create Shortcut
4. Select "Open as window" > Create
5. Shortcut opens and does not crash
6. Close shortcut window, leave browser open
7. Open from created shortcut under /Users/username/Applications/Brave Browser Apps
8. Shortcut opens and does not crash
9. Close browser and shortcut window
10. Open from created shortcut under /Users/username/Applications/Brave Browser Apps
11. Browser and shortcut window open and do not crash
12. Close browser
13. Put shortcut in dock
14. Open shortcut from dock
15. Browser and shortcut open and do not crash

</details>

<details>
<summary>Case 2 - confirmed able to login to Twitter on shortcut - PASSED</summary>

Verified steps from https://github.com/brave/brave-browser/issues/21302#issue-1149576399

1. Visited site (twitter.com)
2. Open hamburger menu
3. Select More Tools > Create Shortcut
4. Select "Open as window" > Create
5. Shortcut opens and does not crash
6. Confirm able to login to twitter and navigate around
7. Close shortcut window, leave browser open
8. Open from created shortcut under /Users/username/Applications/Brave Browser Apps
9. Shortcut opens and does not crash
10. Confirm able to navigate around twitter in shortcut window
11. Close browser and shortcut window
12. Open from created shortcut under /Users/username/Applications/Brave Browser Apps
13. Browser and shortcut window open and do not crash
14. Confirm able to navigate around twitter in shortcut window
15. Close browser
16. Put shortcut in dock
17. Open shortcut from dock
18. Browser and shortcut open and do not crash
19. Confirm able to navigate around twitter in shortcut window

</details>

Additional tests from https://github.com/brave/brave-core/pull/12418#issuecomment-1054989483:

<details>
<summary>Test Case 3 - uninstalling PWA - PASSED</summary>

1. visit https://www.cnn.com
2. create a PWA via `Hamburger Menu` -> `More Tools` -> `Create Shortcut...` (`Open as window` selected)
3. ensured that CNN is launched in a separate window once the PWA is created
4. ensured that you can uninstall the PWA via the `Hamburger Menu` (need to be within the PWA window)

</details>

<details>
<summary>Test Case 4 - "Open as window" not selected - PASSED w/ note</summary>

1. visit https://www.cnn.com
2. create a PWA via `Hamburger Menu` -> `More Tools` -> `Create Shortcut...` (`Open as window` not selected)
3. ensured that clicking on the PWA shortcut opens a https://www.cnn.com tab within a new window
4. ensured that you can move around the PWA shortcut to different locations and it still works as expected

Note, step 3 seems to work differently for me than some others. However, step 3 is also consistent with how this works on Chrome for me. Could be specific to some configuration on my machine.

</details>

<details>
<summary>Test Case 5 - Upgrade - PASSED</summary>

1. Install 1.35.103 and create PWA (with "Open as window" selected). Confirm PWA works as expected.
2. Update to 1.35.104, see PWA is broken
3. Update to 1.36.x RC 
4. click on the previously created PWA shortcut and a PWA window should launch with site created in step 1.

</details>

----------------

Verified with

[insert macOS-arm64/M1 build here]

Verified tests from https://github.com/brave/brave-core/pull/12418#issuecomment-1054989483:

<details>
<summary>Test Case 1 - "Open as window" selected - PASSED</summary>

* visit https://www.cnn.com
* create a PWA via `Hamburger Menu` -> `More Tools` -> `Create Shortcut...` (`Open as window` selected)
* ensured that CNN is launched in a separate window once the PWA is created
* ensured that launching the PWA via the shortcut works without issues when Brave is opened & closed
* ensured that you can move around the PWA shortcut to different locations and it still works as expected
* ensured that you can uninstall the PWA via the `Hamburger Menu` (need to be within the PWA window)

</details>

<details>
<summary>Test Case 2- "Open as window" not selected - PASSED</summary>

* visit https://www.cnn.com
* create a PWA via `Hamburger Menu` -> `More Tools` -> `Create Shortcut...` (`Open as window` not selected)
* ensured that clicking on the PWA shortcut opens a https://www.cnn.com tab within an existing window
* ensured that you can move around the PWA shortcut to different locations and it still works as expected

</details>

<details>
<summary>Test Case 3 - Upgrade Case - PASSED</summary>

* download/install `1.35.104` (PWA via `Open as window` broken on this build)
* visit https://www.cnn.com and create a PWA using `Open as window` (you'll notice it's broken)
* upgrade to `1.36.108`
* click on the previously created PWA shortcut and a PWA window should launch with CNN opened

</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS High Seirra 10.13.6 x64` using the following build(s):

* `Test Case #1` ("Open as window" selected) - **PASSED**
* `Test Case #2` ("Open as window" not selected) - **PASSED**
* `Test Case #3` (Upgrade Case) - **PASSED**

```
Brave | 1.36.108 Chromium: 99.0.4844.51 (Official Build) (x86_64)
--- | ---
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 10.13.6 (Build 17G14042)
```

Verification **PASSED** on `macOS Seirra 10.12.6 x64` using the following build(s):

* `Test Case #1` ("Open as window" selected) - **PASSED**
* `Test Case #2` ("Open as window" not selected) - **PASSED**
* `Test Case #3` (Upgrade Case) - **PASSED**

```
Brave | 1.36.108 Chromium: 99.0.4844.51 (Official Build) (x86_64)
--- | ---
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 10.12.6 (Build 16G2136)
```

STR/Cases used for the above platforms/macOS versions:

#### `Test Case #1` ("Open as window" selected)

* visit https://www.cnn.com
* create a PWA via `Hamburger Menu` -> `More Tools` -> `Create Shortcut...` (`Open as window` selected)
* ensured that CNN is launched in a separate window once the PWA is created
* ensured that launching the PWA via the shortcut works without issues when Brave is opened & closed
* ensured that you can move around the PWA shortcut to different locations and it still works as expected
* ensured that you can uninstall the PWA via the `Hamburger Menu` (need to be within the PWA window)

#### `Test Case #2` ("Open as window" not selected)

* visit https://www.cnn.com
* create a PWA via `Hamburger Menu` -> `More Tools` -> `Create Shortcut...` (`Open as window` not selected)
* ensured that clicking on the PWA shortcut opens a https://www.cnn.com tab within an existing window
* ensured that you can move around the PWA shortcut to different locations and it still works as expected

#### `Test Case #3` (Upgrade Case)

* download/install `1.35.104 Chromium: 98.0.4758.109` (PWA via `Open as window` broken on this build)
* visit https://www.cnn.com and create a PWA using `Open as window` (you'll notice it's broken)
* upgrade to `1.38.12 Chromium: 99.0.4844.51`
* click on the previously created PWA shortcut and a PWA window should launch with CNN opened

**Comment by jspizziri** [comment]
This issue is closed but it seems like there's still a lot of testing going on. Perhaps I just don't understand the process? I'd love to know when it might actually be released to the general public.

**Comment by stephendonner** [comment]
> This issue is closed but it seems like there's still a lot of testing going on. Perhaps I just don't understand the process? I'd love to know when it might actually be released to the general public.

You can find the tentative release dates via https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule.
