### ISSUE TITLE
Dropped transactions are never retired in our Wallet (Android)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#21305]
Android version of issue [21051-Dropped transactions are never retired in our Wallet](https://github.com/brave/brave-browser/issues/21051).

Handle dropped transaction.

**Comment by Pavneet-Sing** [comment]
Update: On hold, as the proposed solution isn't quick enough to produce the 100% desired flow accuracy, although, may work in ideal conditions, with a forever stuck/dropped transaction, so WIP with sporadic discussion.

**Comment by simoarpe** [comment]
This issue is the Android counterpart of https://github.com/brave/brave-browser/issues/21051 that is marked with a P3 priority.
I'm lowering the priority to P3 to match #21051 priority, and asked for clarification around current state.

**Comment by simoarpe** [comment]
Status update: it's an old issue and is no longer needed since we increased the gas estimations. We can close it.
