### ISSUE TITLE
Duplicate entries added after entering correct code words

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2130]
## Description 

Duplicate entries added after entering correct code words

## Steps to Reproduce

   1. Launch brave beta with `--enable-brave-sync`
   2. Create sync chain on profile, copy code words
   3. Remove profile completely
   4. Create a new profile with `--enable-brave-sync`
   5. Paste the code from step 2 but misspell a word
   6. Click on `Create Sync`, no error message is shown for incorrect words typed in
   7. Correct misspell word and click on `Create Sync`, doesn't show sync chain created instantly, need to keep clicking on create sync 
   8. Once sync chain is created shows the device listed from step 5 

## Actual result:

https://youtu.be/7UC3_ZoCdUY

## Expected result:
1. Should show warning message when wrong code words is entered
2. Should have a waiter message when sync chain is being created
3. Should not have previous attempts added as devices on the sync chain

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @brave/legacy_qa to verify on other platforms as well 
cc: @darkdh @AlexeyBarabash @SergeyZhukovsky

**Comment by darkdh** [comment]
I'm confused by duplicate entries. In your video, device list contains "Linux" and "Test" is expected. Removing profile doesn't mean it will be removed from sync chain

**Comment by AlexeyBarabash** [comment]
Agree with @darkdh .
Expected pt.3 `Should not have previous attempts added as devices on the sync chain` could not be implemented because sync seed and device id are stored in profile.

**Comment by AlexeyBarabash** [comment]
Expected pt.1 `Should show warning message when wrong code words is entered` has own issue assigned 
https://github.com/brave/brave-browser/issues/2103

**Comment by AlexeyBarabash** [comment]
Splitted expected result points by issues:
**Should show warning message when wrong code words is entered**
   https://github.com/brave/brave-browser/issues/2103
   https://github.com/brave/brave-browser/issues/2128
**Should have a waiter message when sync chain is being created**
  https://github.com/brave/brave-browser/issues/2227
**Should not have previous attempts added as devices on the sync chain**
  it cannot be fixed

**Comment by darkdh** [comment]
as https://github.com/brave/brave-browser/issues/2130#issuecomment-441287488 stated,
some phenomenons are duplicated of other issues and duplicate devices scenario is invalid
so close the issue here
