### ISSUE TITLE
Transaction status is not updated sometimes for pending transactions

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21300]
## Description 

We have a `transactionStatusChanged` action that gets called by `OnTransactionStatusChanged` observer
```
handler.on(WalletActions.transactionStatusChanged.getType(), async (store: Store, payload: TransactionStatusChanged) => {
  const status = payload.txInfo.txStatus
  if (status === BraveWallet.TransactionStatus.Confirmed || status === BraveWallet.TransactionStatus.Error) {
    await refreshBalancesPricesAndHistory(store)
  }
})
```
which will update `Balances` if a transactions status has changed to `Confirmed` or `Error`.

Currently `OnTransactionStatusChanged` is not firing when a transactions status has changed to `Confirmed` until you `lock` and `unlock` the wallet.

**Comment by yrliou** [comment]
This issue is due to block tracker not being run so we didn't get the update. The reason that lock & unlock updates it is because when you unlock it would trigger the block tracker to start when there are pending transactions.

**Comment by yrliou** [comment]
See test plan in https://github.com/brave/brave-core/pull/12555#issue-1164529596

**Comment by Uni-verse** [comment]
Verification completed on desktop using:

```
Brave | 1.37.102 Chromium: 99.0.4844.83 (Official Build) dev (x86_64)
-- | --
Revision | b11086e62d7c1a44b0942ac5568d22a425c7ae35-refs/branch-heads/4844_74@{#5}
OS | macOS Version 12.1 (Build 21C52)
```
Txn Hash: 0xee8bc52e4e9d59e4797fc73325aa074654ef86ef240e7b81348c75fb8955af56

Test Plan: 
https://github.com/brave/brave-core/pull/12555#issue-1164529596

- Verified transaction status is updated to `confirmed` in brave://settings/wallet/accounts

![Screen Shot 2022-03-23 at 10 27 55 AM](https://user-images.githubusercontent.com/17885425/159765284-11f25a51-25a0-439f-904e-192effbef5d7.png)
![Screen Shot 2022-03-23 at 10 28 12 AM](https://user-images.githubusercontent.com/17885425/159765290-50edc35f-2867-4a40-9354-b00211a132d2.png)
![Screen Shot 2022-03-23 at 10 32 27 AM](https://user-images.githubusercontent.com/17885425/159765294-31780ada-91ad-4926-95e3-0a25ed2c8e53.png)

**Comment by Uni-verse** [comment]
Verification completed on `Android ARM` using Beta `1.37.101, Chromium 99.0.4844.83`

Devices: 
`Samsung Galaxy S21` running `Android 12`

Txn Hash: 0xc043b4f4d4bb8cc008883a68d4383ab4441e8fea5e3ceea59971b71064ab9abf

- Verified transaction status is updated to confirmed under wallet accounts

Submitted | Confirmed
-|-
![Screen Shot 2022-03-23 at 11 59 59 AM](https://user-images.githubusercontent.com/17885425/159776605-76823e68-db23-47ee-bda1-b3290026e3f3.png) | ![Screen Shot 2022-03-23 at 12 00 09 PM](https://user-images.githubusercontent.com/17885425/159776609-0c3a680f-01fc-49e0-8bfc-a37eb519cb5f.png)

**Comment by Uni-verse** [comment]
Verification in Progress on` iOS` using beta version `1.37 (22.3.22.17) BraveCore 1.37.101 (99.0.4844.83)`

Test Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2

iOS 15: 
...

iPad (iOS 15):
...

iOS 14: 
Submitted | Confirmed
-|-
![IMG_2623](https://user-images.githubusercontent.com/17885425/159780368-bea71651-3a8e-42ba-87eb-0936f190920e.PNG) | ![IMG_2624](https://user-images.githubusercontent.com/17885425/159780377-6f66f564-c03a-474c-8b1e-3f34e611bd66.PNG)
