### ISSUE TITLE
Implement a Refresh Balances Interval

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21304]
## Description 
We need to implement an `Refresh Balances` interval in the Wallet to refresh a users balance every 30 - 60 seconds.

**Comment by Uni-verse** [comment]
Verified using

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.3.1 (Build 21E258)

- Verified balance refreshes on the portfolio page and the wallet panel

https://user-images.githubusercontent.com/17885425/163606354-d4928be9-791d-401a-bfc4-acbdfc101923.mov 

https://user-images.githubusercontent.com/17885425/163606339-0938ed24-323c-4fc7-8a11-c57c101d16a4.mov
