### ISSUE TITLE
Implement add network button in Network Selector Screen

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#21301]
## Description 
Implement "Add" network button in [Network Selector Screen](https://github.com/brave/brave-core/pull/12396) to show the "add network" screen.

**Comment by Pavneet-Sing** [comment]
Hey @maurobuss, no worries and thanks for showing your interest. One easy way is to go through the linked PR changes https://github.com/brave/brave-core/pull/12396 and you can find the [NetworkSelectorActivity](https://github.com/brave/brave-core/blob/master/android/java/org/chromium/chrome/browser/crypto_wallet/activities/NetworkSelectorActivity.java) there as well. Happy coding!

**Comment by PratikshitGuptaI** [comment]
Is the problem solved?I would love to contribute! @Pavneet-Sing

**Comment by jatinmark** [comment]
Can you assign it to me, i want to work on this issue.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48.154/1 x64 build
- Verified Add network button is shown in the network selector screen
- Verified clicking on the add button loads the add network page
- Verified able to successfully add a network and it gets listed in the custom networks
- Verified adding the same details similar to existing one updates the default network 
- Verified removing the custom network resets the default list

Oppo Reno 5 (Android13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/216879808-155e7b71-4c75-4e9f-85e8-1f48e5b9fba2.mp4> | <video src=https://user-images.githubusercontent.com/17010094/216880133-7b6cb71b-368b-4cbe-aca5-e9876d6360f5.mp4>
