### ISSUE TITLE
Stripe session/checkout error trying to purchase VPN with experimental SKU SDK

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21314]
## Description 

Stripe session/checkout error trying to purchase VPN with experimental SKU SDK; found while testing -- and blocks -- https://github.com/brave/brave-browser/issues/20557

## Steps to Reproduce

   1. install `1.36.105`
   2. launch Brave using `--vmodule="*/skus/*"=1 --enable-logging=stderr`
   3. set `Enable experimental SKU SDK` to `Enabled`
   4. set `Experimental SKU Environment` to `Enabled`
   5. click to `Relaunch`
   7. load `account.brave.software`
   8. enter basic auth creds for site
   9. enter an email and click `Get login link` (I used [premium-test-04@mailinator.com](mailto:premium-test-04@mailinator.com))
   10. check your email inbox (above case: `https://www.mailinator.com/v4/public/inboxes.jsp?to=premium-test-04`)
   11. click `Log in to Brave` or the link in the email
   12. click on `Browse plans`
   13. scroll down and click on `Buy now` for `Brave VPN Subscription`
   14. enter payment details on `https://checkout.stripe.com/pay/cs_test…`
   15. click `Subscribe`
   16. you should get a `Complete your purchase...` screen
   17. click on `Complete payment`

## Actual result:

You'll end up on a screen like this

URL: `https://account.brave.software/account/?intent=provision&order_id=c9e0c6e9-3903-4828-af70-cfd8bf4a578e`

<img width="1312" alt="Screen Shot 2022-02-24 at 5 31 35 PM" src="https://user-images.githubusercontent.com/387249/155639016-99f3a20e-2a70-4620-8d1d-46d3b61df738.png">

Clicking `Complete payment` yields this:

<img width="1312" alt="Screen Shot 2022-02-24 at 5 32 42 PM" src="https://user-images.githubusercontent.com/387249/155636686-0ddc1a48-ce74-4350-9529-68f791d0a814.png">

## Expected result:

This is as far as you can currently get; means you have a valid subscription.

<img width="1319" alt="Screen Shot 2022-02-24 at 5 06 08 PM" src="https://user-images.githubusercontent.com/387249/155635907-9473567e-cf31-4b4a-b532-57f53c1e89c5.png">

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @evq @bsclifton @mattmcalister @srirambv @rebron

**Comment by bsclifton** [comment]
Closing as I believe this is resolved now

**Comment by bsclifton** [comment]
Re-opening because I forgot there was a cache fix in https://github.com/brave/brave-core/pull/12175
