### ISSUE TITLE
[Android] Update "Verify" to say "Unverified" in Rewards when user is in unverified state

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21316]
## Description

Android version of https://github.com/brave/brave-browser/issues/21315 

- [ ] Update text in Rewards panel
- [x] Update text in Rewards settings page (inherited for free if fixed here Android version of https://github.com/brave/brave-browser/issues/21315 on desktop)

**Comment by LaurenWags** [comment]
Verification in progress on Pixel 3 XL with Android 12 running 1.38.80

Confirmed panel/rewards page shows "Unverified" for unverified user:

Panel | brave://rewards
----- | -----

Confirmed once I verified with the following custodians, the "Unverified" text was updated as expected:

Gemini Panel | Gemini brave://rewards | Uphold Panel | Uphold brave://rewards | bitFlyer Panel | bitFlyer brave://rewards
----- | ----- | ----- | ----- | ----- | -----

![bF panel](https://user-images.githubusercontent.com/28145373/162043370-e29e3068-4d73-4519-890e-85ad896199c2.png) | ![bF settings](https://user-images.githubusercontent.com/28145373/162043389-82b7524e-780a-4c71-bd91-b0aa79f50a1b.png)


Also confirmed that when explicitly disconnecting from above custodians (Click on "Verified" > Choose "Disconnect from custodian"), the UI changes back to "Unverified" as expected.
