### ISSUE TITLE
Wallet backup reminder banner

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21312]
remove the word "crypto"

expected result
![Screen Shot 2022-02-24 at 6 58 36 PM](https://user-images.githubusercontent.com/318119/155633414-d8ac0a98-f064-45d3-8460-386bda121ef4.png)

**Comment by Uni-verse** [comment]
Verified using 

```
Brave | 1.38.80 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.1 (Build 21C52)
```

`Pass` - remove the word "crypto" from the wallet backup reminder

![Screen Shot 2022-04-06 at 4 00 35 PM](https://user-images.githubusercontent.com/17885425/162087396-14a9ddb2-998f-41cf-ab4d-e59fa9faa2fe.png)

Android UI (1.38.82)

![Screen Shot 2022-04-06 at 4 01 34 PM](https://user-images.githubusercontent.com/17885425/162087422-c1e5fd33-adb7-46c1-bd42-64886e353949.png)
