### ISSUE TITLE
Sync device name should have restricted length

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2131]
## Description 
Sync device name should have restricted length

## Steps to Reproduce

   1. Launch brave beta with `--enable-brave-sync` flag
   2. Give sync name which has too many chars along with special chars and numbers

## Actual result:
Allowing sync name is accepting too many chars
![image](https://user-images.githubusercontent.com/38657976/48457642-64d6e000-e7e9-11e8-997d-12bd0ee45358.png)

## Expected result:
 There should be restriction for sync name length

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?

Yes on beta build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by cezaraugusto** [comment]
😱

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified laptops no longer have the option of having a user entered name
