### ISSUE TITLE
Clicking solve on adaptive captcha notification doesn't show captcha if auto-contribute disabled

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#21311]
## Description 
Users with auto-contribute disabled in Rewards are not able to complete scheduled adaptive captchas.

## Steps to Reproduce

   1. Schedule an adaptive captcha for a particular wallet id
   2. Have that user enable Rewards, disable auto-contribute, and restart the browser
   3. Exhaust unblinded tokens by viewing/rating ads
   4. Eventually, notification will appear for scheduled captcha
   5. Click Solve on the notification

## Actual result:

Nothing happens. Rewards panel doesn't open and captcha doesn't appear.

## Expected result:
Rewards panel should open and display the captcha to solve.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Current nightly

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by emerick** [comment]
cc: @gpestana @Miyayes

**Comment by kjozwiak** [comment]
Will require `1.36.107` or higher.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.36.107 Chromium: 99.0.4844.45 (Official Build) (x86_64)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | macOS Version 12.2.1 (Build 21D62)
```

Verification notes can be found under https://github.com/brave/internal/issues/857#issuecomment-1054299509

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.36.107 Chromium: 99.0.4844.45 (Official Build) (64-bit)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | Windows 11 Version 21H2 (Build 22000.527)
```

Verification notes can be found via https://github.com/brave/internal/issues/857#issuecomment-1054680063.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 	1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Ubuntu 18.04 LTS

Verified in https://github.com/brave/internal/issues/857
