### ISSUE TITLE
Reloading tab while scrolled into feed doesn't reset to NTP view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21318]
## Description 
Reloading tab while scrolled into feed doesn't reset to NTP view

## Steps to reproduce 

   1. Enable News
   2. Scroll down the feed for a bit
   3. Reload using the URL bar refresh button
   4. Feed doesn't reset to NTP view, stays in the same position

## Actual result 

https://user-images.githubusercontent.com/17010094/155660504-4e6c9b3b-20f1-42a9-a407-7889a8f7dcae.mp4

## Expected result
Should reset view similar to #20900

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes when released
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): TAblet
   - Android version: 10
   
## Brave version
1.36.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NNA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe

**Comment by alexsafe** [comment]
@srirambv I was wondering though what would be the desired behaviour here? Seems we have different results on different platforms. On desktop(linux) i see that refreshing causes the news to take over the screen and there is a reload going on because the background changes, but the NTP view is no longer there. On iOS the refresh button has no effect.

**Comment by srirambv** [comment]
I think we should retain the current news feed position and just update the background image but like you said on desktop when you reload via Ctrl+R or use the refresh button it jumps to the start of feed and updates the background image. Here's how it looks on Windows using master

https://user-images.githubusercontent.com/17010094/156500961-657d75a7-d553-4947-809a-aff89cc92f87.mov
