### ISSUE TITLE
Custom RSS feed without image has cramped layout

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21320]
## Description 

Custom RSS feed without image has cramped layout

## Steps to Reproduce

   1. install `1.38.1`
   2. launch Brave
   3. open a new-tab page
   4. scroll down
   5. click on `Show Brave News` to opt-in
   6. click on `Customize`
   7. in `Feed URL` enter `https://www.reutersagency.com/feed/?best-topics=political-general&post_type=best`
   8. click `Add source`
   9. click the `X`
   10. wait
   11. click on `Load new content` when it appears
   12. look for the Reuters feed content

## Actual result:

Layout isn't the best

<img width="1312" alt="Screen Shot 2022-02-24 at 9 49 01 PM" src="https://user-images.githubusercontent.com/387249/155662343-0114ba53-8882-4775-9195-3f7e1b56a034.png">

## Expected result:

Layout makes sense, given the lack of sized content for the box grid

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.38.1 Chromium: 99.0.4844.45 (Official Build) nightly (x86_64)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | macOS Version 11.6.3 (Build 20G415)

cc @alexsafe @mattmcalister @petemill

**Comment by mattmcalister** [comment]
Need design help to address this @bradleyrichter

**Comment by Luisnil18** [comment]
Sorry! adding new RSS feeds does not load an image.

![image](https://user-images.githubusercontent.com/80606035/181639222-acb3da19-f285-41e0-a640-2895443111cf.png)

**Comment by mattmcalister** [comment]
This will be fixed in front end UX upgrade work. Closing.
