### ISSUE TITLE
Console logs error when sync is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2132]
## Description 

Console logs error when sync is enabled

## Steps to Reproduce

   1. Enable sync using `--enable-brave-sync`
   2. Open `brave://bravesync` and open dev tools (F12)
   3. Create a sync chain by entering a device name 
   4. Console logs error
   5. Same errors while joining a sync chain as well

## Actual result:

~https://youtu.be/189rrSZTGAY~
Edit: Updated link  https://youtu.be/b4i3GL27tk0

## Expected result:
Should not log any errors

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta build
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Reproduced on Windows when joining to a sync chain created on Linux
cc: @darkdh @AlexeyBarabash @brave/legacy_qa

**Comment by kjozwiak** [comment]
@srirambv can you post the errors into a code insert or maybe post a screenshot? The YT video that was uploaded doesn't seem to be working. I get the following error whenever I attempt to view it:

```
Video unavailable
This video has been removed by the user
```

**Comment by srirambv** [comment]
Not sure how the video got removed. I'll reupload the video. Here's the console log
```
load_time_data.js:217 Unexpected condition on chrome://bravesync/: Could not find value for remove
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: [undefined] (remove) is not a string
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: Could not find value for remove
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: [undefined] (remove) is not a string
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: Could not find value for remove
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: [undefined] (remove) is not a string
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: Could not find value for remove
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: [undefined] (remove) is not a string
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: Could not find value for remove
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: [undefined] (remove) is not a string
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: Could not find value for remove
expect @ load_time_data.js:217
load_time_data.js:217 Unexpected condition on chrome://bravesync/: [undefined] (remove) is not a string
```

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.7 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

* Verified using STR from description

**Comment by srirambv** [comment]
Removed QA pass label. Need to verify it against beta again
