### ISSUE TITLE
Cards before branded list cards are smaller in size 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21323]
## Description 
Cards before branded list cards are smaller in size 

## Steps to reproduce 

   1. Enable news and scroll down
   2. Cards before branded list is smaller in size

## Actual result 

Tablet | Mobile
-- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/155669319-1475dd4a-4edd-4f94-b360-ed59aeee2a0e.png> | <img width=290 src=https://user-images.githubusercontent.com/17010094/155669592-bcb027b3-a5ca-4583-a82a-5dcda857e3c6.png>

## Expected result
All cards should be of same size

## Issue reproduces how often 
Easy 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes when 1.36.x goes to release
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.36.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.38.63, Chromium 100.0.4896.46` on a `Google Pixel XL` running `Android 9.0`.

Confirmed that branded `Brave`, `Health`, etc., categories had right-sized content before them.

example | example
---------|---------
![Screenshot_20220322-162500](https://user-images.githubusercontent.com/387249/159592717-e830f660-69ad-4afd-b5f0-301cab49572e.png) | ![Screenshot_20220322-162522](https://user-images.githubusercontent.com/387249/159592724-a0d2ef92-5a93-428b-80ce-6f09c2e0f763.png)

**Comment by Uni-verse** [comment]
Verification completed us version
```
1.37.105 Chromium: 100.0.4896.46 (Official Build) (32-bit) 
Revision	5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
```

Devices: 
`Samsung Galaxy S21` | `Android 12`
`Samsung Galaxy Tab S7` | `Android 11`

**PASS** - Verify cards before branded list cards are the same size
**PASS** - Verify cards in news feed in portrait
**PASS** - Verify cards in news feed in landscape mode
**FAIL** - Switching from landscape to portrait and vice versa doesn't change change the size of the cards.  

mobile | tablet
-|-
![Screen Shot 2022-03-24 at 2 45 56 PM](https://user-images.githubusercontent.com/17885425/160017494-ac961e02-aadc-4096-bc3b-66ffe1e3c130.png) | ![Screen Shot 2022-03-24 at 2 49 32 PM](https://user-images.githubusercontent.com/17885425/160017501-f9f01892-679b-47b7-a51d-08416b18e9d7.png)

Issue encountered: 

https://user-images.githubusercontent.com/17885425/160017690-72fca547-a218-421e-a84f-96e065169c40.mp4
