### ISSUE TITLE
Rewards info modal should not be shown if Brave news or Brave News opt-in modal is shown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21321]
## Description 
Rewards info modal should not be shown if Brave news or Brave News opt-in modal is shown

## Steps to reproduce 

   1. Install 1.36.x build
   2. Open a tab with SI before opt-in to News
   3. Scroll past the opt-in card, shows rewards info modal

## Actual result 

https://user-images.githubusercontent.com/17010094/155663097-1003c689-3a21-4e3c-bb31-b9f04027cceb.mp4

## Expected result
No rewards info modal as per @mattmcalister 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes when 1.36.x is released
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.36.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @mattmcalister

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.38.63` on a `Google Pixel XL` running `Android 9.0`.

Steps:
1. installed `1.38.63`
2. launched Brave
3. opened a new-tab page with a Sponsored Image
4. swiped down
5. confirmed no Sponsored-Image Rewards banner below the Brave News "peeking" card
6. enabled Brave News
7. swiped down
8. confirmed no Sponsored-Image Rewards banner below the Brave News "peeking" card


https://user-images.githubusercontent.com/387249/159560252-195cfdf4-44e5-404d-828b-6588289ed7fd.mp4

**Comment by Uni-verse** [comment]
Verification completed using version

```
1.37.105 Chromium: 100.0.4896.46 (Official Build) (32-bit) 
Revision	5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
```

Devices:
`Samsung Galaxy S21` | `Android 12`
`Samsung Galaxy Tab S7` | `Android 11`

- Verified rewards info modal not shown when Brave News or Brave News opt-in modal is shown

https://user-images.githubusercontent.com/17885425/160024734-7db29d95-cd9a-4f6b-902d-1ad1dc328d01.mp4 

https://user-images.githubusercontent.com/17885425/160024837-ee8e74f8-0b79-4f15-bc91-f570e25038e7.mp4
