### ISSUE TITLE
On Linux brave (snap), There's a balance different between wallet dialog (correct) and Wallet home screen (incorrect)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#21332]
## Description 

Wallet home shows an incorrect balance but the dialog shows it correctly.

## Steps to Reproduce

   1. Login wallet
   2. Compare the balance on wallet dialog and wallet from settings

## Actual result:

![Screenshot from 2022-02-25 14-27-09](https://user-images.githubusercontent.com/11755381/155687727-99c3ca10-d104-4db7-93d5-f9ead80b8977.png)

## Expected result:
Show same balance

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Version 1.35.103 Chromium: 98.0.4758.102

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Seeing this only on Linux, Correct on MacOs, haven't checked windows. could due to the different is brave versions, i have the updated one from Snap.

**Comment by Douglashdaniel** [comment]
This is expected behavior,
`Portfolio` page shows the balances between all accounts,
`Panel` only shows the balance of the current selected account.

**Comment by Douglashdaniel** [comment]
While on the `Portfolio` page if you click on `Ethereum` you will see the `Balance` for each account.
