### ISSUE TITLE
Add Loading skeletons to assets list and transactions and any other sections to improve UX

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#21339]
![skeleton-loading](https://user-images.githubusercontent.com/48117473/155740766-d4d96603-140d-4d27-82b1-d41e6b225005.jpeg)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">  1.38.107 Chromium: 101.0.4951.41 (Official Build)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12507>brave/brave-core#12507</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165287546-ca046372-25f0-4f2d-add7-f9c282d60ba9.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165287284-9397008d-9c0c-411c-bfb9-b30a1d43c6a8.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165287233-025e9d24-620d-4431-bdb5-5e875b360e06.mov>
      </td>
   </tr>
</table>
