### ISSUE TITLE
Adding a contract address auto-populates previously added custom token details 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21337]
## Description 

Adding a contract address auto-populates previously added custom token details 

## Steps to Reproduce

   1. Add a custom token for visible asset on Ropsten
   2. Close the custom visible asset dialog
   3. Copy a different token contract address to clipboard
   4. Add custom token and paste in the contract address from previous step, auto-populates the data for the first token added in step 1 
   5. Copy wallet address and paste it in the contract address, auto-populates the previous token details from step 4

Note: closing the dialog after it auto-populates and trying to add again doesn't auto-populate it 

## Actual result:

https://user-images.githubusercontent.com/17010094/155713639-46238b1b-8345-4bc7-98f8-e66238999e05.mp4

## Expected result:
Should only auto-populate if the token is already in the visible list but not enabled

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.36.106 Chromium: 99.0.4844.45 (Official Build) (64-bit)
-- | --
Revision | `edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard

**Comment by Uni-verse** [comment]
Verified using 

```
Brave	1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64) 
Revision	8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS	macOS Version 12.3.1 (Build 21E258)
```

- Adding a contract address does not auto-populate fields with previously added token details
