### ISSUE TITLE
[Followup #20406] SI CTA Button moves along when swiped up to reveal Brave News

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21331]
## Description 
[Followup #20406] SI CTA Button moves along when swiped up to reveal Brave News

## Steps to reproduce 

   1. Install 1.36.105
   2. Enable Brave News via flag
   3. Open a new tab with SI
   4. Scroll up to view Brave News opt-in card
   5. SI CAT button also moves up from its position
   6. Brave rewards info modal is shown below the News opt-in card [#21321](https://github.com/brave/brave-browser/issues/21321)

## Actual result 

https://user-images.githubusercontent.com/17010094/155683888-a6e286d8-8725-443e-9292-d119ba3a5eff.mp4

## Expected result
Per internal discussion the fade in should be more quicker for SI CTA button

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes with 1.36.x in release
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.36.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe @mattmcalister @kjozwiak

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.38.63, Chromium 100.0.4896.46` on a `Google Pixel XL` running on `Android 9.0`.

Confirmed this is no longer an issue, due to removing the Sponsored Image call-to-action modal in https://github.com/brave/brave-browser/issues/21321#issue


https://user-images.githubusercontent.com/387249/159568080-e069c0e5-2950-4861-8749-e21bb4a9ebd7.mp4

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 12` using `1.37.105 Chromium: 100.0.4896.46`

* ensured that the SI CTA modal doesn't appear at the bottom when the Brave News opt-in card is visible under NTP
  * opened several SI NTP and ensured it wasn't appearing while the opt-in card was visible
* ensured that the SI CTA modal appears correctly under SI NTP when the Brave News opt-in card isn't visible
* ensured that the SI CTA modal was working as expected when rewards hasn't been enabled
* ensured that the SI CTA modal worked as expected when rewards has already been enabled

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
![Screenshot_20220324-234907](https://user-images.githubusercontent.com/2602313/160051491-68388f6f-e6d8-455b-b162-f0dad352f17d.png) | ![Screenshot_20220324-234621](https://user-images.githubusercontent.com/2602313/160051498-13b02abc-f867-42d1-9dde-085305925416.png) | ![Screenshot_20220324-234949](https://user-images.githubusercontent.com/2602313/160051515-06339aa9-abdd-46bf-b75f-23d50069f671.png)
