### ISSUE TITLE
Trezor One with 1.10.5 version fails to sign typedata

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21338]
## Description 

Trezor One with 1.10.5 version fails to sign typedata

## Steps to Reproduce

   1. Connect Trezor One with firmware 1.10.5
   2. Visit https://metamask.github.io/test-dapp
   3. Connect Trezor account and try to sign typedata v3/v4, fails with firmware error

## Actual result:

https://youtu.be/Ah2wWlMRa2M

## Expected result:
Should be able to sign as min firmware requirement is met

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 1.36.106 Chromium: 99.0.4844.45 (Official Build) (arm64)
-- | --
Revision | `edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes when 1.36.x is released
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Worked fine when testing for uplift ([brave/brave-core/#12265 (comment)](https://github.com/brave/brave-core/pull/12265#issuecomment-1047420040))

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster

**Comment by yrliou** [comment]
It has been a while, @srirambv is this version still relevant? Also I would like to make it P3 or even P4 if it's a specific older version.

**Comment by srirambv** [comment]
I don't have a Trezor One with that firmware anymore so not possible to check. I did check with the firmware `1.12.1` and sign transactions work on Trezor One. Closing as stale/invalid
