### ISSUE TITLE
Tapping on custom RSS feed title deletes feed

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21348]
## Description 

Tapping on custom RSS feed title deletes feed

## Steps to reproduce 

   1. install `1.38.6`
   2. launch Brave
   3. tap the 3-dots menu
   4. tap `Settings`
   5. tap `Brave News`
   6. tap to toggle `Show Brave News` to `ON`
   7. tap on `Add source`
   8. input `https://brave.com/blog/index.xml`
   9. tap `Search`
   10. wait for the feed to populate in the sources list
   11. tap on the feed title (NOT the toggle)

## Actual result 

Tapping on the feed title deletes the feed.

https://user-images.githubusercontent.com/387249/155833681-f47fc6aa-7186-4101-a83c-219b2c4ba1b6.mp4

## Expected result

Not sure it should do anything, but definitely not delete.

## Issue reproduces how often 
100%

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `9.0`
   
## Brave version
`1.38.6, Chromium 99.0.4844.45`

cc @alexsafe @mattmcalister

**Comment by alexsafe** [comment]
@mattmcalister should we do something about this until we implement the new design? and if so what would the design look like? normally the 'Android' thing would be to be able to tap on the Source and then go into a detail page where you can view/edit/delete .

We can also just not remove it and just disable for now.

**Comment by mattmcalister** [comment]
for now, let's match iOS behavior and allow users to toggle on/off but leave the feed in place.

**Comment by alexsafe** [comment]
@mattmcalister sounds good. the only thing is that iOS allows to swipe the source horizontally and that reveals a Delete button. So i guess match sans that ?:)

**Comment by mattmcalister** [comment]
I got it. Closing.

**Comment by stephendonner** [comment]
> @stephendonner this issue is irrelevant with new brave news settings changes. Can you please confirm and close the issue ?

Looks like @mattmcalister beat me, but yes, I can confirm this isn't a problem any longer due to the new design, using:

```
Brave	1.54.6 Chromium: 114.0.5735.35 (Official Build) canary (32-bit)
Revision	2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

example | example | example
---------|----------|---------
![Screenshot_20230525-090521](https://github.com/brave/brave-browser/assets/387249/12b87dca-8ec4-43ef-ac80-be102173413a) | ![Screenshot_20230525-090530](https://github.com/brave/brave-browser/assets/387249/7388bfb9-dcdb-4e2c-9f72-27dd136c0a13) | ![Screenshot_20230525-090537](https://github.com/brave/brave-browser/assets/387249/7afae11d-2be1-474b-bd35-ceff2c0b9792)
