### ISSUE TITLE
Reset sync should show warning message to user, if sync is already established between two devices

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2134]
## Description 
Reset sync should show warning message to user, if sync is already established between two devices

## Steps to Reproduce

   1.  Launch brave beta with `--enable-brave-sync` flag
   2.  Sync two devices and make sure sync is established b/n 2 devices (Bookmarks are imported and 
         synced between two devices)
   3.  Click on Reset sync on Device1
   4. Observe that there is no warning message displayed

## Actual result:
Click on Reset Sync is not showing any waring message

## Expected result:
Click on Reset sync should show warning message to user, if sync is already established b/n devices

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
 Yes on beta build
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by cezaraugusto** [comment]
fixed by https://github.com/brave/brave-core/pull/917

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.57.7 Chromium: 71.0.3578.53 (Official Build) beta (64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Windows

**Comment by srirambv** [comment]
Removed QA pass label. Need to verify it against beta again

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Windows



![image](https://user-images.githubusercontent.com/38657976/49474332-6fa9f100-f83a-11e8-8d45-b8dc486f8bf3.png)
