### ISSUE TITLE
[Android] Cannot verify with Uphold if user has Uphold app installed

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21342]
## Description

When a user has the Uphold app installed, the Uphold mobile app intervenes in the linking process, and the linking flow cannot complete. The user will see an error. Normally, the user should complete the linking process via Uphold inside the Brave browser, but when the Uphold app is installed, it interrupts the process and does not link back properly.

cc: @brave/rewards-support @Brave-Matt

**Comment by Miyayes** [comment]
Wasn't able to reproduce on Nightly (?) but will doublecheck @deeppandya

**Comment by Miyayes** [comment]
@srirambv In order to test:

1. Download and install Uphold app
2. Try to verify with Uphold in Brave Rewards
3. Check if it opens into the Uphold app, or the entire OAuth flow remains inside the Brave Browser

**Comment by deeppandya** [comment]
@Miyayes @srirambv do we have any update on the verification ?

**Comment by srirambv** [comment]
Just rechecked this issue and can't repro it. While authenticated into Uphold App, trying to authorize Uphold account loads the page rather than switching to the app. Tried on both nightly and release

**Comment by Miyayes** [comment]
Seems to have resolved itself... @brave/user-support-team <-- let us know if you still see any reports of this.
