### ISSUE TITLE
Add global fingerprint/ad-blocking configuration P3A questions

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#21345]
## Description 

Adding two new P3A questions for Shields global configuration:

What is the global fingerprinting shields setting?
0: Disabled
1: Standard
2: Aggressive

What is the global ad block shields setting?
0: Disabled
1: Standard
2: Strict

## Miscellaneous Information:

Will raise PR soon.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.38.75 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```

**Comment by Uni-verse** [comment]
Verified using

```
Brave	1.38.105 Chromium: 101.0.4951.41 (Official Build) (64-bit) 
Revision	93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS	Android 12; Build/SP1A.210812.016
```
Devices:
Samsung Galaxy Tab S7 | Android 12
Samsung Galaxy S21 | Android 12

- Verified the test plan from https://github.com/brave/brave-core/pull/12415

**Global Shield & FingerPrint Settings**

- [ ] Aggressive setting will have value of `2`
- [ ] Standard setting will have value of `1`
- [ ] Disabled setting will have value of `0`

**Upgraded Profile:**

Case 1: Standard Setting:` PASS`
Case 2: Aggressive Settings: `FAIL` -  https://github.com/brave/brave-browser/issues/22063, https://github.com/brave/brave-browser/issues/22064
Case 3: Disabled: `FAIL`  https://github.com/brave/brave-browser/issues/22064, https://github.com/brave/brave-browser/issues/22063

Tablet | Mobile
-|-
![Screen Shot 2022-04-22 at 11 36 41 AM](https://user-images.githubusercontent.com/17885425/164777177-cd879d11-ac24-451d-adc6-1c31bcc20228.png) | ![Screen Shot 2022-04-22 at 11 32 18 AM](https://user-images.githubusercontent.com/17885425/164777166-6c8a2814-1f62-40b4-8517-4df3624f2bba.png)
