### ISSUE TITLE
Some shortcuts doesn't work when sidebar bookmarks panel has focus

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21359]
All browser shortcuts should be work regardless of sidebar panel open status.

STR
1. Open sidebar bookmarks panel
2. Give focus to bookmarks panel by clicking any empty area of bookmarks
3. Try `ctrl`(or `cmd`) + `l`(lower `L`) to give focus to location bar
    Or Try `ctrl`(or `cmd`) + `t` to create new tab

Actual result: location bar doesn't get focus
Expected result: location bar gets focus

**Comment by kjozwiak** [comment]
Requires `1.37.90` or higher for QA verification's via `1.37.x` .

**Comment by stephendonner** [comment]
## Verified `PASSED` using



Brave | 1.37.91 Chromium: 99.0.4844.51 (Official Build) beta (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.3 (Build 21E230)

### Steps:
1. opened Sidebar `bookmarks` panel by clicking on the `Bookmarks` icon in the Sidebar
2. gave focus to bookmarks panel by clicking an empty area
3. pressed `command` + `l` to give focus to location bar
4. also pressed `command` + `t` to create a new tab
5. and `command`+ `o` (lower `O`) to open a file
6. finally `command` + `s` to `Save as...`

#### Confirmed macOS shortcuts all worked
#### Confirmed appropriate focus/focus states

`initial focus` | `ctrl + l` |  `ctrl + t`  | `ctrl + o` | `ctrl + s`
----------|-----------|----------|-----------|----------
<img width="1120" alt="Screen Shot 2022-03-14 at 5 12 30 PM" src="https://user-images.githubusercontent.com/387249/158281206-2c0069ca-213f-46fa-9465-e857f334d48e.png"> | <img width="1120" alt="Screen Shot 2022-03-14 at 5 11 57 PM" src="https://user-images.githubusercontent.com/387249/158281885-19b7c29f-2440-4ff7-8250-a407da4232b4.png"> | <img width="1120" alt="Screen Shot 2022-03-14 at 5 11 49 PM" src="https://user-images.githubusercontent.com/387249/158281960-df8e46d6-8629-400a-ada1-155ca5db6760.png"> | <img width="1312" alt="Screen Shot 2022-03-14 at 3 36 27 PM" src="https://user-images.githubusercontent.com/387249/158282009-fcd18ed1-75fc-4016-927f-bab2ec9d92e3.png"> | <img width="1120" alt="Screen Shot 2022-03-14 at 5 12 11 PM" src="https://user-images.githubusercontent.com/387249/158282155-707036d9-8a73-4dee-9d58-4df53d1251f7.png">

**Comment by MadhaviSeelam** [comment]
Verified 'Passed' using

      Brave |	1.37.98 Chromium: 99.0.4844.74 (Official Build) beta (64-bit) 
      --|--
      Revision |	fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
      OS |	Windows 11 Version 21H2 (Build 22000.556)

Steps:

-  opened Sidebar bookmarks panel by clicking on the Bookmarks icon in the Sidebar
-  gave focus to bookmarks panel by clicking an empty area
-  pressed ctrl + l to give focus to location bar
-  pressed ctrl  + t to create a new tab
- Clicked on the Bookmarks icon in the Sidebar to close
- Retested above shortcuts (ctrl+l) and (ctrl+t) and they work same as expected as above

initial|ctrl+l|ctrl+t|bookmarksclosed
----|---|---|---|
<img width="1200" alt="initial focus" src="https://user-images.githubusercontent.com/98358127/159092777-f9593126-2292-4734-ba7b-fe3c81e7cab4.png">|<img width="1200" alt="ctrl+l" src="https://user-images.githubusercontent.com/98358127/159092963-2767bc67-8040-469e-9530-026509541abe.png">|<img width="1200" alt="ctrl+t" src="https://user-images.githubusercontent.com/98358127/159093041-e74d3eae-9c60-4343-8e58-24ce048ec59c.png">|<img width="1200" alt="Bookmarks closed" src = "https://user-images.githubusercontent.com/98358127/159093168-2dc7d1dd-302c-4f4d-b0af-e91e269ab404.png">
