### ISSUE TITLE
Brave Stats about ad and tracker blocking on New Tab page records stats from private windows also

### ISSUE THREAD

**Issue by vishupal4185** [brave/brave-browser#21354]
## Steps to Reproduce

   1. Open a new window in private mode and another normally
   2. Open youtube.com with shields enabled
   3. Notice the Brave stats in normal window

## Actual result:

Numbers in Brave stats increases as new trackers and ads are blocked in incognito mode.

## Expected result:
Numbers do not increase in Brave stats

## Reproduces how often: 

Everytime

## Brave version (info found on brave://version)

1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by vishupal4185** [comment]
### :Info from brave://version

Brave	1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit) 
Revision	273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS	Windows 10 Version 21H2 (Build 19044.1526)
JavaScript	V8 9.8.177.11
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.0.0 Safari/537.36
Command Line	"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --blink-settings=disallowFetchForDocWrittenScriptsInMainFrame=true --enable-quic --ignore-gpu-blocklist --enable-features=BlockInsecurePrivateNetworkRequests,BraveAdblockCnameUncloaking,BraveAdblockCookieListDefault,BraveAdblockCosmeticFiltering,BraveAdblockCspRules,BraveAdblockDefault1pBlocking,BraveAdblockRedirectUrl,BraveDebounce,BraveDomainBlock,BraveExtensionNetworkBlocking,CosmeticFilterSyncLoad,EnableTLS13EarlyData,EphemeralStorage,ExtensionWorkflowJustification,ExtensionsMenuAccessControl,FencedFrames:implementation_type/shadow_dom,JXL,LensRegionSearch,LiveCaption,MediaSessionWebRTC,OmniboxKeywordSpaceTriggeringSetting,ParallelDownloading,PartitionedCookies,PlaybackSpeedButton,PostQuantumCECPQ2,Prerender2,PrivacyReview,ReduceUserAgent,ScrollableTabStrip:minTabWidth/72,SharedHighlightingV2,SharingHubDesktopAppMenu,SharingHubDesktopOmnibox,StrictExtensionIsolation,StrictOriginIsolation,UseBraveTranslateGo,WebUIDownloadShelf --disable-features=AutofillCreditCardAuthentication,BraveDarkModeBlock,BraveNews,BraveRewardsVerboseLogging,ChromeWhatsNewUI,ForceMajorVersion100InUserAgent,NtpModules,OmniboxDynamicMaxAutocomplete,OmniboxPedalsBatch2NonEnglish,OmniboxRichAutocompletion,SyncTrustedVaultPassphraseRecovery,SystemKeyboardLock,WebXRIncubations --flag-switches-end
Executable Path	C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\Vibhanshu\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	AdRewardsStudy:NextPaymentDay
BraveDebounceStudy:Enabled
ConversionsStudy:NewDefaultPattern
Default1pBlockingStudy:Disabled
EphemeralStorageStudy:Enabled
FencedFrames:AboutFlags
ForceDisableBlinkFeatures:Enabled
NativeCosmeticFilteringStudy:Enabled
NavigationThreadingOptimizationsCompat:Disabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
RequestAdsEnabledApiStudy:Enabled
SpeedreaderReleaseStudy:Disabled
TabScrolling:AboutFlags

**Comment by diracdeltas** [comment]
I think this was originally an intentional product decision so that users who mainly or only browse in private mode can see nonzero stats. I'm not seeing much of a fingerprinting risk here but cc @pes10k

**Comment by pes10k** [comment]
@vishupal4185 thank you for filing the issue, but im going to mark this `wontfix` since it was an intentioanl product decision and doesn't (as best we can tell) carry any privacy risk to users

**Comment by vishupal4185** [comment]
@pes10k @diracdeltas @bridiver @mattmcalister Its a reminder ping.
