### ISSUE TITLE
Incorrect error message adding duplicate RSS-feed URLs

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21352]
## Description 

Incorrect error message adding duplicate RSS-feed URLs

## Steps to Reproduce

   1.  install `1.38.6`
   2. launch Brave
   3. open a new-tab page
   4. scroll to show the Brave News opt-in dialog
   5. click on `Show Brave News` button
   6. click on `Customize` on the bottom right of the window
   7. input `https://slate.com/feeds/all.rss` to the `Feed Url` textfield
   8. click on `Add source`
   9. confirm you see `Slate Magazine` listed under `Your Sources`
   10. input `https://slate.com/feeds/all.rss` again into that textfield
   11. click `Add source`
   12. look at the resulting error messaging

## Actual result:

Red message saying `Sorry, we couldn't find a feed at that address.`

example | example
---------|---------
<img width="1185" alt="Screen Shot 2022-02-26 at 5 47 00 AM" src="https://user-images.githubusercontent.com/387249/155845654-8d325755-739c-4c04-9867-5d108e2af85b.png"> | <img width="1185" alt="Screen Shot 2022-02-26 at 5 47 06 AM" src="https://user-images.githubusercontent.com/387249/155845583-3b568c43-eabe-4165-aa28-625309448a19.png">

## Expected result:

It's a duplicate feed, so this error message is incorrect.  It should either disallow by disabling the `Add source` button, or have a more-specific error message.

## Reproduces how often: 

100%

## Brave version (brave://version info)

`1.38.6`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @petemill @mattmcalister @srirambv

**Comment by mattmcalister** [comment]
Fixed in Settings upgrade
