### ISSUE TITLE
Recent beta+nightly are considerable slow compared to main 

### ISSUE THREAD

**Issue by gbil** [brave/brave-browser#21353]
## Description 
Recent beta (and nightly) are much slower especially on heavy sites compared to the normal release. All versions installed from play store

## Steps to reproduce 

   1. Install brave beta or nightly from play store
   2. Keep default settings   
   3. browse some heavy sites eg. www.kotsovolos.gr or www.plaisio.gr
 

## Actual result 
Pages take a long time to render AND if using keyboard you can clearly see how slow it is to use at that point keyboard shortcuts like ctrl+t to open a new tab

## Expected result
Pages should render quite fast and keyboard shortcuts should be responsive during loading of sites

## Issue reproduces how often 
every time

## Version/Channel Information:

Beta 
Nightly 

- Can you reproduce this issue with the current Play Store version? NO 
- Can you reproduce this issue with the current Play Store Beta version?  YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):  Samsung Tab S5e, Samsung S10e
   - Android version: 11 and 12 
   
## Brave version
1.37.75

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

**Comment by vishalnandagopal** [comment]
Same issue. Popular sites like YouTube also feel very sluggish, and mouse clicks take too long to respond to elements on the site.

For example, clicking pause and the video actually pausing are 5 seconds apart.

**Comment by gbil** [comment]
Also chrome beta 99.0.4844.48 does NOT present the same issues, so this must be something that Brave is changing

**Comment by vishalnandagopal** [comment]
@gbil can you change the label to OS/Windows or Desktop?

**Comment by gbil** [comment]
> @gbil can you change the label to OS/Windows or Desktop?

My report is for Android specifically

**Comment by vishalnandagopal** [comment]
> My report is for Android specifically

Okay, I saw keyboard shortcuts and assumed you were reporting about the desktop app.
