### ISSUE TITLE
Support the `eth_subscribe` method with the `"newHeads"` param

### ISSUE THREAD

**Issue by add-tech** [brave/brave-browser#21350]
## Description 
When i want use the brave wallet on snowtrace, to make a transaction, snowtrace send the transaction to the wallet.
I click on confirm, and after that i have this error :
Failed to subscribe to new newBlockHeaders to confirm the transaction receipts. { "error": { "code": -32601, "message": "the method eth_subscribe does not exist" }, "id": 8, "jsonrpc": "2.0" }

## Steps to Reproduce
   1. go on https://snowtrace.io/address/
   2. find a contract
   3. use function on write contract like "approve" : https://snowtrace.io/token/0xd586e7f844cea2f87f50152665bcbc2c279d8d70#writeContract
   4. accept the transaction on brave wallet

## Actual result:
Failed to subscribe to new newBlockHeaders to confirm the transaction receipts. { "error": { "code": -32601, "message": "the method eth_subscribe does not exist" }, "id": 6, "jsonrpc": "2.0" }

## Expected result:
transaction should be accepted

## Brave version (brave://version info)
[Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/)

## Version/Channel Information:
- Can you reproduce this issue with the current release? 
- yes

**Comment by kunal266** [comment]
same error with [hacketh.io](https://web3.ethglobal.com/), I had to use chrome and install metamask to use the same

**Comment by vinh-perfectstorm** [comment]
same error with brave wallet

**Comment by bbondy** [comment]
@nvonpentz if you have a chance could you look into what we need here in more detail?

**Comment by adhanot** [comment]
Honestly, without disrespecting you, I have trouble understanding how this little bug can take so long.
And especially why you launched a wallet if we can't use it.
I'm a BAT holder and a brave user since years but honestly it pisses me off. Nobody will use your wallet if it's full of bugs and you take months to fix them.
