### ISSUE TITLE
Secondary ssh path in event of DNS outage due to cyber attack

### ISSUE THREAD

**Issue by unicomp21** [brave/brave-browser#21365]
Quick question.  In the event of a dns outage, is there another way for me to have my customers run the brave browser?  Like via ssh tunnel?  Where a specially formatted url will allow a user to connect to my server via pre-registered ssh public key?

I realize it sounds silly, but these sorts of questions always sound silly until it actually happens.  We've had crazier things happen in the not too distant past.

**Comment by excalq** [comment]
I suspect that in a severe cyber attack, DNS would be just one layer of many areas affected. Also, it's quite easy to change DNS servers to another (like 1.1.1.1/8.8.8.8). I don't see how this question relates to Brave, as it's an HTTP browser, not an SSH client.
