### ISSUE TITLE
Toolbar not being enabled on device 2, when bookmarks are synced into toolbar

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2136]
## Description 
Imported bookmarks from Chrome browser into brave (Device 1- Windows 10). Bookmarks are imported succssfully on Win10 and toolbar bookmarks and folders are displayed properly in win10. After sync with device 2 (Windows 8), toolbar bookmarks and folders are not shown in Toolbar section on Device2.

## Devices

Device 1 - Windows 10 (sync creator)
Device 2- Windows 8 

## Steps to Reproduce

   1.  Launch brave beta with `--enable-brave-sync` flag
   2.  Create sync chain on Device 1
   3.  Make sure sync is established between two device 
   4.  Import bookmarks from Chrome browser on Device 1
   5.  Wait untill bookmarks synced on Device 2 (Based on amount of BM's)
   6. Open chrome://bookmarks/ and make sure all the bookmarks are synced in Device 2
   7. Observe that the bookmarks and folders are not shown in toolbar section on Device 2

## Actual result:
Device 1 - Windows 10

![image](https://user-images.githubusercontent.com/38657976/48480925-e4889d00-e831-11e8-9d82-c5d660c41be2.png)

Device 2 - Windows 8

Toolbar section is empty 

![image](https://user-images.githubusercontent.com/38657976/48481070-48ab6100-e832-11e8-8026-34502dd7075a.png)

## Expected result:
After sync toolbar bookmarks and folders should be shown in toolbar section on device2

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta build
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Bookmark toolbar was not enabled by default on Win8 (Device 2). I have just tested again by enabling `Show bookmarks bar` settings on win8. Now i could see toolbar bookmarks and folders imported properly on Win 8.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7 x64

Second device was Windows 10 x64.

Used Test Plan from https://github.com/brave/brave-core/pull/962. Checked STR from OP.
