### ISSUE TITLE
Opt+Shift+Arrow within Address bar on macOS does not select text

### ISSUE THREAD

**Issue by itzkakarot** [brave/brave-browser#21362]
## Description 
Within the Address Bar, holding Option + Shift while pressing the left or right arrow key is supposed to select whole words at a time. This worked fine in previous version of Brave. Today, pressing Opt+Shift+Left Arrow doesn't do anything, unless you release the key combination and press Option a second time, then the appropriate Select action will occur.

## Steps to Reproduce

   1. Place cursor within Address Bar, preferably at the end of a word or before a slash
   2. Hold Option and Shift, press the Left arrow key

## Actual result:
Cursor doesn't move, and no text gets selected. You must press Option a second time and then the text gets selected as expected.

## Expected result:
All the text of the last "word" should be selected. Words are separated by spaces, slashes and special characters.

## Reproduces how often: 
100% reproducible

## Brave version (brave://version info)
Brave | 1.35.104 Chromium: 98.0.4758.109 (Official Build) (arm64)
Revision | 03268453da2c7409eb1ee934d97abfc6f3b45420-refs/branch-heads/4758@{#1179}
OS | macOS Version 12.2.1 (Build 21D62)

## Version/Channel Information:
Production

- Can you reproduce this issue with the current release?  **Yes**
- Can you reproduce this issue with the beta channel?  **Untestsd**
- Can you reproduce this issue with the nightly channel?  **Untestsd**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  **No**
- Does the issue resolve itself when disabling Brave Rewards?  **No**
- Is the issue reproducible on the latest version of Chrome?   **No**

## Miscellaneous Information:
This is a strange issue.

**Comment by rebron** [comment]
@itzkakarot Command+Shift plus the arrow key left or right should be providing what you're expecting in terms of text selection.

**Comment by itzkakarot** [comment]
@rebron I'm using macOS. Control+Shift+Arrow selects the entire line in the URL bar. (as expected) The "select word" functionality in all other macOS apps is Option+Shift+Arrow. Please reopen this issue.
