### ISSUE TITLE
Optimize greaselion startup performance 

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#21366]
For some reason we create a lot internal extensions named `greaselion-xx`. It leads to allocate some structures for each of them.
Moreover in may places chromium has linear search over all extensions therefore the number should be reasonable.

Therefore we suspect that have some noticeable performance impact.
The proposal:
~~1. measure the performance impact of these extensions~~
2. merge all the extensions into the one(?) or find another way to optimize this.

<img width="466" alt="image (9)" src="https://user-images.githubusercontent.com/45488748/156010808-e54e146c-0ee5-4bdf-b568-918529ef2c95.png">

**Comment by iefremov** [comment]
cc @pilgrim-brave

**Comment by atuchin-m** [comment]
The impact was investigated here: https://github.com/brave/brave-browser/issues/33724
![image](https://github.com/brave/brave-browser/assets/45488748/2df86da7-de6f-4c29-8554-c117d0de0f06)

**Comment by atuchin-m** [comment]
Closed in favor of https://github.com/brave/brave-browser/issues/40873
