### ISSUE TITLE
sidebar shortcut items should have latest favicon

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21360]
Sidebar shortcut doesn't show latest favicon. It should use latest one.

STR
1. Set light theme and load github in active tab
2. Add github to sidebar panel
3. Sidebar github shortcut uses dark color favicon
4. Set dark theme and load github again

Actual result - Sidebar github shortcut still uses dark color favicon 
Expected result - It should use light color favicon

FYI, New window has latest icon because shortcut uses latest one when it's initialized.
But it's not updated after its initialization is done.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.21 Chromium: 99.0.4844.51 (Official Build) nightly (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.3 (Build 20G415)

Steps:

1.  installed `1.38.21`
2. launched Brave
3. confirmed `light` theme set already
4. loaded `github.com` in active tab
5. added `github.com` to Sidebar via its menu
6. noted favicon is dark, when using `light` theme
7. changed theme to `dark`
8. confirmed `favicon` remained dark
9. reloaded `github.com`

Confirmed github.com's favicon was now light.

step 4 | step 5 | steps 7-8 | step 9
---------|----------|---------|-------
<img width="934" alt="Screen Shot 2022-03-03 at 5 39 23 PM" src="https://user-images.githubusercontent.com/387249/156683295-59c5c326-fe2e-4c45-ae9b-15ad60f08119.png"> | <img width="934" alt="Screen Shot 2022-03-03 at 5 39 30 PM" src="https://user-images.githubusercontent.com/387249/156683303-6b618c6b-0595-4b64-b242-a0b181321ea1.png"> | <img width="1169" alt="Screen Shot 2022-03-03 at 5 39 56 PM" src="https://user-images.githubusercontent.com/387249/156683311-53d342fb-a752-4733-8d95-0664399d4fd9.png"> | <img width="1169" alt="Screen Shot 2022-03-03 at 5 40 02 PM" src="https://user-images.githubusercontent.com/387249/156683312-6a2342e9-1f99-4d20-a578-c7a1e81ed7ff.png">

**Comment by kjozwiak** [comment]
Requires `1.37.90` or higher for QA verification's via `1.37.x` .
