### ISSUE TITLE
Sync chain creation fails after system comes online

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2137]
## Description 

Sync chain creation fails after system comes online

## Steps to Reproduce

   1. Launch brave with `--enable-brave-sync`
   2. Disconnect device from network
   3. Open Brave Sync and click on `I am new to Sync`
   4. Type in a device name and click `Setup Sync`, modal dismissed without any warning
   5. Close modal and try again with a different device name, doesn't show any warning message
   6. Connect device back to network and try creating sync chain again, doesn't work
   7. Restart browser and try again works fine and sync chain gets created

## Actual result:

https://youtu.be/1OPqo5b7aKE

## Expected result:
Browser shouldn't be capable of creating sync chain when device comes online and without having to restart the browser

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @brave/legacy_qa @darkdh @AlexeyBarabash

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 10 x64

When device is offline, `No Internet connection` modal is shown.
Going online will create a sync chain on next attempt.

There are some special cases when the `No Internet connection` modal is not shown https://github.com/brave/brave-browser/issues/2468
