### ISSUE TITLE
pylint warnings in `signing_helper.py`

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21376]
## Description 
Changes to [signing_helper.py](https://github.com/brave/brave-core/blob/master/script/signing_helper.py) in https://github.com/brave/brave-core/pull/12418 caused pylint to run for the entire file. There are some warnings (all low severity except one normal)

signing_helper.py:17	Warning	reimported	Normal	1
signing_helper.py:46	Convention	bad-continuation	Low	1
signing_helper.py:52	Convention	line-too-long	Low	1
signing_helper.py:65	Convention	line-too-long	Low	1
signing_helper.py:70	Convention	line-too-long	Low	1
signing_helper.py:85	Convention	line-too-long	Low	1
signing_helper.py:99	Convention	line-too-long	Low	1
signing_helper.py:106	Convention	line-too-long	Low	1
signing_helper.py:144	Convention	trailing-whitespace	Low	1
signing_helper.py:144	Convention	line-too-long	Low	1

**Comment by kjozwiak** [comment]
Thanks for getting this fixed @bsclifton 👍
