### ISSUE TITLE
Device name and code words content cuts off the sync screen.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21371]
## Description 

Device name and code words content cuts off the sync screen.

## Steps to Reproduce

   1. Clean profile 1.36.107
   2. Navigate to sync settings
   3. Establish syn between two devices
   

## Actual result:

Device name and code words content cuts off the sync screen.
![Screenshot_20220228-225954_Brave](https://user-images.githubusercontent.com/38657976/156037646-eaab8127-f7a4-4cc4-911c-f7b51b43ea1d.jpg)
![Screenshot_20220228-230510_Brave](https://user-images.githubusercontent.com/38657976/156037657-f35168b1-1d41-40f9-af2d-baf5401b73e1.jpg)
## Expected result:

should not be any alignment issue

## Reproduces how often: 

Easy

## Brave version (info found on brave://version)

1.36.107
## Version/Channel Information:

- Can you reproduce this issue with the current release?Yes in (1.35.103) but not in 1.35.101
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel?Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

CC: @brave/legacy_qa @samartnik @SergeyZhukovsky

**Comment by Uni-verse** [comment]
Doesn't repro on Android ARM mobile using 1.36.107

Device: Samsung Galaxy S21 | Android 12

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.110 x64 build
- Verified steps from issue description
- Verified text/graphics on Sync screens are not cut off

Add Device | Device List | QR Code | Code Words
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/156966061-2f223b00-c20c-4cab-ae75-b97786afa347.png) | ![image](https://user-images.githubusercontent.com/17010094/156966097-69bad28e-21fa-4d7e-bdec-456c7a188eca.png) |  ![image](https://user-images.githubusercontent.com/17010094/156966066-5d8ff74f-ae70-49b8-b55b-261411e4db84.png) | ![image](https://user-images.githubusercontent.com/17010094/156966080-7d8545a5-2f6a-428a-b813-ba8287318f42.png)
