### ISSUE TITLE
`Open in new tab in group` option is shown upon long press on any top tiles in Android Tab

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21380]
## Description 

`Open in new tab in group` option is shown upon long press on any top tiles in Android Tab
## Steps to reproduce 

   1. Clean profile `1.36.108`
   2. Open an NTP
   3. Long press on any top tiles

## Actual result 

`Open in new tab in group` option is shown upon long press on any top tiles in Android Tab
![image](https://user-images.githubusercontent.com/38657976/156201367-62feeb53-e5f3-4beb-9902-afe2709cc6d3.png)

## Expected result
Option should not be shown

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Not sure
- Can you reproduce this issue with the current Play Store Nightly version? Not sure

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Table
   - Android version: Android 11
   
## Brave version
1.36.108

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome?NA 

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @samartnik @anthonypkeane

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.36.110 x64 build
- Verified steps from issue description
- Verified on both clean install and upgrade, `Open in new tab group` option is not shown for tablets when long pressed on top tiles or on links on webpage

News Disabled | News Enabled | News Opted-In | Long Press Context menu 
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/156966627-9ee42300-39d1-4018-a9f3-17873a611777.png) | ![image](https://user-images.githubusercontent.com/17010094/156966632-89172746-6397-4b9c-b14b-62e2c5d35e66.png) | ![image](https://user-images.githubusercontent.com/17010094/156966771-1317eef8-2aa9-4d6b-a730-1d9e821cc5ce.png) | ![image](https://user-images.githubusercontent.com/17010094/156966642-752245f0-3986-4361-86c1-26f9351de227.png)
