### ISSUE TITLE
Translations missing on Arch based distros

### ISSUE THREAD

**Issue by MafiaInc** [brave/brave-browser#2138]
## Description 
Labels and text in Brave Rewards menu appears with i18n prefixes.

## Steps to Reproduce

   1. Open any site
   2. Click on Brave Rewards button located in the end of the location bar
   3. Observe the text on labels and buttons

## Actual result:
![image](https://user-images.githubusercontent.com/1325853/48483720-e7c55e00-e81c-11e8-9db3-bde152e9881c.png)

## Expected result:
To not have "i18n" prefixes on text.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave	0.56.12 Chromium: 70.0.3538.77 (Official Build) unknown (64-bit)
Revision	0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS	Linux
JavaScript	V8 7.0.276.32
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Command Line	/usr/lib/brave-bin/brave --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,kAutofillServerCommunication --flag-switches-begin --flag-switches-end --
Executable Path	/usr/lib/brave-bin/brave
Profile Path	/home/marto/.config/BraveSoftware/Brave-Browser/Default
Variations	...

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Yes, this is 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
 No, not site specific.
- Is the issue reproducible on the latest version of Chrome? 
 Not relevant for Chrome

### Additional Information
More system details:
Operating System: Arch Linux 
KDE Plasma Version: 5.14.3
Qt Version: 5.11.2
KDE Frameworks Version: 5.52.0
Kernel Version: 4.19.1-arch1-1-ARCH
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-5300U CPU @ 2.30GHz
Memory: 7,7 GiB of RAM

**Comment by NejcZdovc** [comment]
cc @bbondy will this be fixed with the latest language fix?

**Comment by bbondy** [comment]
no

**Comment by droidman** [comment]
If you compile brave on arch the bug is fixed.

**Comment by srirambv** [comment]
This should be fixed already 
![image](https://user-images.githubusercontent.com/17010094/56512328-0b43b180-64fd-11e9-891b-6f58b3150263.png)
![image](https://user-images.githubusercontent.com/17010094/56512356-1dbdeb00-64fd-11e9-808a-25a495ccfd98.png)

This is fixed on the community maintained arch bin. Closing the issue as fixed
