### ISSUE TITLE
Wallet: Localhost Network Chain Id and Port are Hardcoded, Not Shown in UI

### ISSUE THREAD

**Issue by excalq** [brave/brave-browser#21391]
## Description 

As a Web3 dApp developer, I'm testing multiple applications against Brave's native wallet. These applications are running locally in Truffle and Hardhat "sandbox" chains, running on various ports, typically 8545 or 9545.

The Brave wallet has a hardcoded "Localhost" network, which uses Ganache's RPC URI: `http://localhost:7545/`, as well as the standard "dev" chainId: `1337`. 

This is not configurable in the UI, and is actually hardcoded in [components/brave_wallet/browser/brave_wallet_utils.cc](https://github.com/brave/brave-core/blob/5b576ef6125c629d3c876f335a9927f7ca5c208d/components/brave_wallet/browser/brave_wallet_utils.cc#L75):

```
const char kGanacheLocalhostURL[] = "http://localhost:7545/";
```

As this network does not exist in [`brave://settings/wallet/networks`](brave://settings/wallet/networks), it was difficult to determine the port it was hardcoded with, fortunately Brave is open source. Still makes for a less optimal developer experience.

## Steps to Reproduce

   1. Run a development Web3 stack locally, on a port other than 7545, which uses chain id `1337`.
   2. Attempt to add a new network to Brave's networks, using chain id `1337`.

## Actual result:
1. An error will appear: `This network is already added.` (As chain ids must be unique to RPC addresses)

## Expected result:
1. Preferably the Wallet UI should show pre-populated networks' configurations (Chain Ids, RPC URLs, etc.), as MetaMask does, in the Wallet Settings UI.
2. Non-production/Development/Testnets should have editable RPC urls, including port.

## Reproduces how often: 
Easily reproduced, using settings to add a non-port 7545 network with chain id `1337`.

## Brave version (brave://version info)

```
Brave | 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)
-- | --
Revision | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | Linux
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

Yes, this issue is present in both Current and Nightly, provided in Debian PPAs.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
N/A

## Miscellaneous Information:
N/A

**Comment by bbondy** [comment]
cc @jamesmudgett we need some kind of UI in our settings for this, can you propose something? Maybe just listing the built in networks for overrides?

**Comment by yrliou** [comment]
I think this can be closed now as we do show localhost entries in brave://settings/wallet/networks.
<img width="636" alt="Screenshot 2023-11-06 at 1 35 52 PM" src="https://github.com/brave/brave-browser/assets/4730197/3a645464-cb1f-45c0-b215-28c480d1bc83">
