### ISSUE TITLE
Focus handling when sidebar panel webview is opened and closed

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21393]
When sidebar panel opens, give focus to sidebar panel.
When sidebar panel closes, clear focus. Browser window's root view will get focused.

STR 1 - panel open
1. Open sidebar bookmarks panel

* Actual result - bookmarks panel don't have focus
* Expected result - bookmarks panel has focus
  After opening bookmarks panel, first tab gives focus to first element in the panel

STR 2 - panel close
1. Open sidebar bookmarks panel
3. Click any area in sidebar bookmarks panel to get focus
4. Close sidebar bookmarks panel

* Actual result - web page in active tab gets focused always.
If active tab is github.com, we can see below `Skip to content` element after panel is closed.
        <img width="457" alt="image" src="https://user-images.githubusercontent.com/6786187/156279056-feb91130-8e69-4ecc-92a5-4baf2893b7f2.png">
* Expected result - Focus is cleared

**Comment by kjozwiak** [comment]
Requires `1.37.90` or higher for QA verification's via `1.37.x` .

**Comment by stephendonner** [comment]
## Verified `PASSED` using



Brave | 1.37.90 Chromium: 99.0.4844.51 (Official Build) beta (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.3 (Build 21E230)



## Case One: panel open
1. installed `1.37.90`
2. launched Brave
3. clicked on the `Bookmarks` icon in the Sidebar
4. to check focus, pressed `tab`


#### Confirmed `tab` cycled through UI elements in their index

example | example
----------|----------
<img width="1312" alt="Screen Shot 2022-03-13 at 3 33 27 AM" src="https://user-images.githubusercontent.com/387249/158055838-e9cec0ab-4a6a-4171-a10a-00df0d139a14.png"> | <img width="1312" alt="Screen Shot 2022-03-13 at 3 33 33 AM" src="https://user-images.githubusercontent.com/387249/158055840-0860326b-513b-478b-ae62-dda6d22a363a.png">




## Case Two: panel close
1. installed `1.37.90`
2. launched Brave
3. clicked on the `Bookmarks` icon in the Sidebar
4. clicked to expand a folder with a bookmark
5. pressed `tab` to select the bookmark
6. clicked on the `Bookmarks` icon in the Sidebar to close the panel

#### Confirmed NO `Skip to content` (from test plan) present on panel close.  (I was able to trigger that accessibility navigation hint normally via `tab` which is expected in that context.)

example | example
---------|----------
<img width="1592" alt="Screen Shot 2022-03-13 at 3 41 18 AM" src="https://user-images.githubusercontent.com/387249/158055907-9746517a-066b-4a88-baf3-436d444ee996.png"> | <img width="1592" alt="Screen Shot 2022-03-13 at 3 41 24 AM" src="https://user-images.githubusercontent.com/387249/158055913-c6453b96-cdd2-417d-9dbe-02d5b61f377a.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.95 Chromium: 99.0.4844.74 (Official Build) beta (64-bit) 
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

#### panel open

Verified bookmarks panel has focus
![image](https://user-images.githubusercontent.com/34715963/158858194-dae7800d-a593-4109-84f1-9d63f2424b8b.png)

#### panel close

Verified focus is cleared
![image](https://user-images.githubusercontent.com/34715963/158858562-f9b2f12c-109e-4537-a335-98031f2ccadd.png)

**Comment by MadhaviSeelam** [comment]
Verified 'Passed' using

      Brave |	1.37.98 Chromium: 99.0.4844.74 (Official Build) beta (64-bit) 
      --|--
      Revision |	fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
      OS |	Windows 11 Version 21H2 (Build 22000.556)

Case One: panel open
------------------------

- installed 1.37.98
- launched Brave
- clicked on the Bookmarks icon in the Sidebar
- to check focus, pressed tab to focus on the first element in the panel
- Confirmed tab cycled through UI elements in their index

panel open
----|
<img width="1000" alt="CASE ONE" src = "https://user-images.githubusercontent.com/98358127/159078228-f0dff36d-1419-4e4b-9a67-205849b6a742.png">


Case Two: panel close
------------------------

- installed 1.37.98
- launched Brave
- clicked on the Bookmarks icon in the Sidebar
- clicked to expand a folder with a bookmark
- pressed tab to get focus
- Clicked on the Bookmarks icon in the Sidebar to close the panel
- Confirmed NO Skip to content (from test plan) present on panel close. 

panel close
----|
<img width="1000" alt="CASE TWO" src="https://user-images.githubusercontent.com/98358127/159078386-0d88e1b8-ed02-4fba-ae76-6f88b9a918cc.png">
