### ISSUE TITLE
`Add to Mobile` or `Add a Computer` strings are misaligned under `Add New Device`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#21395]
## Description 

Both the `Add to mobile device` & `Add a computer` strings are misaligned/overlapping the button during sync setup

## Steps to reproduce 

   1. download/install `1.38.15 Chromium: 99.0.4844.51`
   2. setup a sync chain with another device (desktop/android combination used in this particular case)
   3. once you have a sync chain created, go into `Settings` -> `Sync` -> `Add New Device`

## Actual result 

![Screenshot_20220301-204111_Brave - Nightly](https://user-images.githubusercontent.com/2602313/156280283-58d12f9c-695e-471a-823e-0c7a046859a2.jpg)

## Expected result

![Screenshot_20220301-204801_Brave](https://user-images.githubusercontent.com/2602313/156280301-4367ca43-bfa6-4982-af3e-9351ced8f41a.jpg)

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A` (C99 related)
- Can you reproduce this issue with the current Play Store Beta version? `Yes` (C99 has been merged into `1.37.x`)
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy Tab A`
   - Android version: `Android 11`
   
## Brave version

`1.38.15 Chromium: 99.0.4844.51`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @samartnik @SergeyZhukovsky @Uni-verse @GeetaSarvadnya @anthonypkeane @srirambv

**Comment by srirambv** [comment]
This is mostly a side effect of #21317 on smaller screen so we should probably fix that even though it was decided not to fix it as part of https://github.com/brave/brave-browser/issues/21372#issuecomment-1054643238

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 11` using `1.36.110 Chromium 99.0.4844.51`

![Screenshot_20220307-001858_Brave](https://user-images.githubusercontent.com/2602313/156972928-a49f7676-cffe-48de-95c8-909a8405d942.jpg)
