### ISSUE TITLE
Compact shields doesn't accommodate 3 digits

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#214]
## Description 
Compact shields doesn't accommodate 3 digits

## Steps to Reproduce

   1. Build from source
   2. Visit icloud.com and set shields to `Block all fingerprinting`
   3. Blocked count goes to 3 digits but only the first digit is visible

 ## Actual result:
![shields count](https://user-images.githubusercontent.com/17010094/40400848-f4e212a8-5e11-11e8-9071-7446fc5b7041.gif)

## Expected result:
Should accommodate 3 digits in compact shields

**Comment by bbondy** [comment]
QA notes:
Use inspect extension for dev tools and then use dom inspector to ensure it is correct. You need to enable dev mode for extensions in about:extensions first.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/45899348-8ea3f580-bdaa-11e8-99b3-610b789efdea.png)
