### ISSUE TITLE
[Suggestion] brave dev version

### ISSUE THREAD

**Issue by Hrushal-Nikhare** [brave/brave-browser#21405]
## Description 
like chrome & fire fox can brave also have a dev version to help with development on brave

**Comment by Hrushal-Nikhare** [comment]
Hi @rebron, if i want to download the dev version of brave will it install seperately or will it fuse into my normal brave?

**Comment by rebron** [comment]
@Hrushal-Nikhare It will install separately.

**Comment by Hrushal-Nikhare** [comment]
then what is the difference between dev standalone & just dev @rebron
