### ISSUE TITLE
Hide Brave Rewards card (during brave://welcome)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21400]
## Test plan
1. Fresh profile
2. Launch Brave
3. brave://welcome screen will show
4. Hit next until you get to end
5. Brave Rewards card should NOT show

## Description 
Desktop onboarding shows `brave://welcome` which acts as a welcome tour. It has an intro card, import, shields and P3A, and lastly Brave Rewards. We should tie the the Brave Rewards card to a configuration value so that we can easily turn on and off

Let's default this to off to start

**Comment by bsclifton** [comment]
This might not be possible to do; the value won't be fetched from variation service until 2nd launch

**Comment by rebron** [comment]
Related issue: https://github.com/brave/brave-browser/issues/21202

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.36.115 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the description from the issue and confirmed Brave Rewards card is removed from the welcome onboarding flow

Example | Example | Example
--|--|--
![image](https://user-images.githubusercontent.com/38657976/158317805-e36e1a6e-ddd4-471d-b8c8-44deae11949a.png) | ![image](https://user-images.githubusercontent.com/38657976/158317827-ce475a8c-6cdd-4835-8eb3-e1aa5ebc49e2.png) | ![image](https://user-images.githubusercontent.com/38657976/158317863-0ae4594d-4751-4cdc-8a8b-b3deab7eaff8.png) | ![image](https://user-images.githubusercontent.com/38657976/158317893-119bc7e4-86f0-47c7-8977-65dd0c0db855.png)
