### ISSUE TITLE
Option to install Brave in a custom location, with or without administrator privileges

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#21409]
This would enable:
* Installation/update without administrator privileges
* Auto updates across systems (including on Linux where that feature is missing)
* Installation on systems where the user can only write to $HOME
* Portable installations (e.g. on pendrives)

Tor Browser does this in their own way (at least on Linux). You can install the package system-wide, as an administrator, but when a user starts the browser, it actually installs itself in $HOME and runs/auto-updates from there. The one wrinkle I see with this approach is the ownership of the files installed in $HOME - the user can modify any of them. This means they can update, but it also opens up some potential security risks.

Relevant [Slack thread](https://bravesoftware.slack.com/archives/CG7GV6M7Z/p1638918729027500?thread_ts=1638897702.020100&cid=CG7GV6M7Z).

**Comment by wknapik** [comment]
This could be generalized to installation in a custom location, with, or without administrator privileges. That would also enable portable installations on usb sticks, etc.

**Comment by wknapik** [comment]
This is a duplicate of https://github.com/brave/brave-browser/issues/598. Closing.

**Comment by rebron** [comment]
Closing per last comment.
