### ISSUE TITLE
Switch off Brave Rewards definitely 

### ISSUE THREAD

**Issue by PascalDk** [brave/brave-browser#21408]
## Description 

Brave Rewards logo keeps showing up while I disabled it. 

Feels like marketing harassment. 

## Steps to reproduce

1. Install Brave
2. In the settings, switch off Brave Rewards
3. Find it back in the URL bar anyway 

## Actual result 

Brave Rewards keeps showing up in the url bar 

## Expected result 

Switch off Brave Rewards/Wallet and never see their name or logo anywhere (or just in a Dedicated Reward/Wallet menu) 

## Issue reproduces how often 

Always. 
   
## Brave Version 
Beta 1.37.72 
I don't have that problem on Regular and Nightly version 

![Screenshot_20220302-142228.jpg](https://user-images.githubusercontent.com/5103378/156369944-3a19d538-c59f-475c-a8de-4fbaea07a4a2.jpg) 

![Screenshot_20220302-141918.jpg](https://user-images.githubusercontent.com/5103378/156370001-2a82efc8-699d-476a-bbe4-fb822a093ab7.jpg)

![Screenshot_20220302-142459.jpg](https://user-images.githubusercontent.com/5103378/156370456-4c1c6be2-7358-40eb-8320-8c4d353a2b50.jpg)

**Comment by Miyayes** [comment]
I think you're looking at the wrong setting :). In Settings, go to `Appearance > ...` and you'll find a toggle for the Brave Rewards icon. @PascalDk

**Comment by PascalDk** [comment]
OK, then the request is : deactivate the Rewards should delete the icon also.

Should I create a new issue or edit this thread instead ?
