### ISSUE TITLE
Tooltip for unsupported swap needs some padding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21402]
## Description 

Tooltip for unsupported swap needs some padding

## Steps to Reproduce

   1. Add a custom network that doesn't support Swap
   2. Open panel and hover over the swap button to show tooltip
   3. There is no padding to the right for the tooltip

## Actual result:

Linux | Windows | macOS
-- | -- | --
<img width=1000 src=https://user-images.githubusercontent.com/17010094/156308803-3d2391af-1b09-4a55-b3ea-23e22e41ac21.png> | <img width=800 src=https://user-images.githubusercontent.com/17010094/156310786-a9999d19-a592-4061-945f-897b1409c935.png> | <img width=1000 src=https://user-images.githubusercontent.com/17010094/156310659-5e1b8305-cba4-4427-84d6-49280a30a0cd.png>

## Expected result:
Padding to the right

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.36.108 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | `d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes when 1.36.x goes to release
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by HEagle18** [comment]
Closing out this issue, as we don't have it swaps 2.0.
