### ISSUE TITLE
Add timestamp/id to Brave Ads user data

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#21419]

**Comment by jsecretan** [comment]
@tmancey to link additional information

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

Verified `createdAtTimestamp` and `systemTimestamp`.
Verified timestamps are in ISO 8601 format with minutes, seconds and milliseconds set to 0.

![image](https://user-images.githubusercontent.com/34715963/162633721-4d8f5ee7-641f-4f9d-92a4-244745b09f44.png)

Verified after failed creation of the confirmation, the retry contains `createdAtTimestamp` and `systemTimestamp`
1st confirmation:
![image](https://user-images.githubusercontent.com/34715963/162634525-b9d0d1d5-382c-41cb-8d65-7184a4de3f5d.png)
2nd confirmation has the same `createdAtTimestamp` and `systemTimestamp` attached
![image](https://user-images.githubusercontent.com/34715963/162634559-51550392-3e4b-471b-8767-68b3a3e82346.png)
