### ISSUE TITLE
`Open in new tab` is opening tabs within groups rather than opening them separately 

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#21427]
## Description 

When tapping on `Open in new tab`, tabs will open within groups rather than being opened separately when using `1.38.16` or later. I'm assuming it regressed due to https://github.com/brave/brave-core/pull/12455.

## Steps to reproduce 

   1. download/install `1.38.19 Chromium: 99.0.4844.51`
   2. launch and skip all the on-boarding (not needed to reproduce the issue)
   3. open a new tab so it populates the `Top Sites` widget with websites (the first tab on install won't have websites loaded)
   4. long tap on any of the websites and tap on `Open in new tab` (notice that the tab count doesn't increase and it's not being grouped)
   5. long tap on another website and select  `Open in new tab` (notice that the tab count doesn't increase and it's not being grouped)
   6. tap the `+` button which should still say `2` and you'll notice that the websites that you opened are grouped
   7. go back to the NTP and you'll see the websites that you opened previously finally appearing in the group
   8. tap/load wikipedia and open any link using `Open in new tab` (notice it's being grouped)

## Actual result 

Example of issue occurring --> https://youtu.be/9nM5Bms4XUE (tabs being opened in groups)

## Expected result

Tapping/Opening tabs via `Open in new tab` shouldn't be placing the tabs into groups

## Issue reproduces how often 

100% reproducible using the STR/Cases mentioned above (also see example video).

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `No`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes` (related to https://github.com/brave/brave-core/pull/12455)

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 12`
   
## Brave version

`1.38.19 Chromium: 99.0.4844.51`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.36.110 x64 build
- Verified steps from issue description
- Verified open in a new tab loads the top-tile or link in a new tab
- Verified open in a new tab increments the tab count 
- Verified open in a new tab group on top-tile or a link creates a tab group and shows the bottom bar for tab group. 
- Verified pressing `+` inside the tab group creates a new tab inside the existing tab group
- Verified opening and closing the tab tray doesn't cause any issues with existing tabs or group them into a new tab group
- Verified on both clean install and upgrade install
- Verified on both normal tabs and private tabs

https://user-images.githubusercontent.com/17010094/156968331-b976840d-2d62-4cbd-85a6-88dbf368500c.mp4
