### ISSUE TITLE
When swapping to an asset not in your visible assets we should prompt to add the asset, via wallet confirmation.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21428]
Would save a step for a better UX

**Comment by jamesmudgett** [comment]
Prompt user when tapping "Swap"

**Comment by yrliou** [comment]
Reverted via https://github.com/brave/brave-core/pull/12820 because it broke test-unit on master.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.108 Chromium: 101.0.4951.67 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/12826>brave/brave-core#12826</a></li>
         <li>Verified selecting token in the Swap field automatically adds the token in the visible asset list</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169112374-77eb3dbe-e459-405c-a93a-fdd8244da1c9.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/169122158-8f92f3ce-f07c-4fb7-9157-53beb16e8e59.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169121659-d01d88c1-bf9a-46b9-8f80-cc45ad38900d.mov>
      </td>
   </tr>
</table>
