### ISSUE TITLE
Reset swap inputs after completing a swap

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21429]
The assets reset to default ETH->BAT but the input fields are unchanged which looks like a bug.

**Comment by jamesmudgett** [comment]
https://user-images.githubusercontent.com/318119/156499343-181f8282-a064-4f74-ae79-f8025f15ee93.mov

**Comment by LangLangBart** [comment]
How did you place your bookmarks vertically?

**Comment by jamesmudgett** [comment]
@LangLangBart in brave nightly you can find it in setting
![Screen Shot 2022-03-03 at 7 58 19 AM](https://user-images.githubusercontent.com/318119/156579278-3edac109-3a29-4506-a1c6-fd6d540a8dc3.png)
s

**Comment by josheleonard** [comment]
Latest branding / copy
<img width="301" alt="Screen Shot 2022-03-07 at 8 18 56 AM" src="https://user-images.githubusercontent.com/30185185/157079321-ffaf562e-d154-4b8a-bfac-d1e9e756fb94.png">
<img width="305" alt="Screen Shot 2022-03-07 at 8 19 19 AM" src="https://user-images.githubusercontent.com/30185185/157079324-289fc1ef-ac21-4c8e-b6bd-c9570f252233.png">

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12509>brave/brave-core#12509</a></li>
         <li>Verified swap input fields are reset to 0 after initiating a transaction</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/167351866-30284ed3-36b0-424a-bf78-5a61c71f81d1.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/167350700-dddc10c2-e781-4ff9-81bb-44961fd61800.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/167350761-f556a42d-5842-406e-94aa-71ff5e1d0d6e.mov>
      </td>
   </tr>
</table>
