### ISSUE TITLE
How to disable Brave shield completely and globally

### ISSUE THREAD

**Issue by Haxy89** [brave/brave-browser#2142]
Too many sites are broke because of Brave shield, how to disable it?
I am using Brave 0.56.12

**Comment by srirambv** [comment]
You can use the shields settings to check which setting is breaking the site and report so that we can have a look and fix it.

**Comment by Haxy89** [comment]
I cant disable shield for some sites. When I disable shield after reload it is still enable.

**Comment by srirambv** [comment]
Can't reproduce that. Mind recording the steps?
