### ISSUE TITLE
Wallet graph blur layer covers network selector

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21423]
![Screen Shot 2022-03-02 at 4 18 00 PM](https://user-images.githubusercontent.com/318119/156459243-e5aa12ca-56e0-4539-9f20-46974398a6a8.png)

**Comment by Uni-verse** [comment]
Verified on

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.1 (Build 21C52)

- Blur layer not visible in the network selector

https://user-images.githubusercontent.com/17885425/163031138-8ab1f28a-099e-46c1-aeaa-8963f0dc437e.mov
