### ISSUE TITLE
Web pages do not follow system dark mode

### ISSUE THREAD

**Issue by Shadowvaporwarez** [brave/brave-browser#21420]
## Description 

Brave Browser does not allow web pages to follow system dark mode on Android 12. Using the flag in brave://flags for auto dark mode for web contents produces bizzare results (for example Brave Search is turned into bizzare dark colours rather than requesting the dark mode theme).

## Steps to Reproduce

   1. Load up Google.com
   2. Load up duckduckgo.com
   3. Load up search.brave.com

## Actual result:

The above pages remain in light mode despite the system being in dark mode, and using the flag converts the light nice page to dark mode target than requesting the dark theme from the website

## Expected result:
To automatically follow system dark mode for web pages that support it

## Reproduces how often: 

Easily reproduced

## Brave version (info found on brave://version)

1.35.103

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/a
- Can you reproduce this issue with the dev channel? N/a
- Can you reproduce this issue with the nightly channel? N/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:

This functions as intended on Chrome and Bromite

**Comment by debian-user-france1** [comment]
Same on Manjaro Brave (Browser is set to dark mode, KDE too).
Brave automatically reloads pages if the theme is changed (bright/dark). This feature works as intended, the pages are dark after switching from bright mode to dark mode, but after a reload of the page or just in general clicking on links switches the page back to the bright design. Happens everywhere.

**Comment by debian-user-france1** [comment]
It happens if fingerprinting blocking is set to strong only. It's a bit annoying because there should be an option to still pass the theme through.

**Comment by waldyrious** [comment]
Please prepend "[Android]" to the title of this issue, as was done in #14685 for Linux. This helps with discoverability (i.e. when searching for issues).

**Comment by debian-user-france1** [comment]
> Please prepend "[Android]" to the title of this issue, as was done in #14685 for Linux. This helps with discoverability (i.e. when searching for issues).

We don't mean that. Our problem is that the fingerprinting of brave on strong always instructs the site to use light mode (to protect privacy?)

**Comment by waldyrious** [comment]
> We don't mean that. 

I don't follow. What is it that you don't mean?

**Comment by mpfaff** [comment]
> https://www.reddit.com/r/brave_browser/comments/lk70ip/force_dark_mode_all_websites/

I've done that already. Imo, it's a bug that this isn't the default.

**Comment by meduzen** [comment]
As mentioned earlier, this isn’t an Android only issue, but is linked to fingerprinting (see https://github.com/brave/brave-core/pull/9735).

I would consider having either a clear indication that strict fingerprint blocks dark mode, either a way to opt-out of it, or even better: browsers should have (probably as a button in their menu bar or as an [item near the padlock](https://twitter.com/meduzen/status/1518229115551297538/photo/2)) a fast and easily reachable way to switch theme (3 options: light, dark, system), in addition to the browser settings.

In the meantime, the current status of dark mode in Brave is confusing for the following reasons:
- There’s no warning that strict fingerprinting can block dark theme: I thought for months it was a bug in Brave and it’s only now (tired of this _bug_) that I finally searched for “brave browser dark mode not applied” and could found this issue.
- Dark theme is an accessibility feature first (I’m used to not use Brave in the evening) for some users, and a “cosmetic” feature for others. You don’t especially expect it to be linked to fingerprint (and I might be mistaken, but it’s a very common feature with probably a very low fingerprint impact).

Finally, for anyone arriving here: the flag to opt-out of this restriction is at [brave://flags/#brave-dark-mode-block](brave://flags/#brave-dark-mode-block).

**Comment by waldyrious** [comment]
> Finally, for anyone arriving here: the flag to opt-out of this restriction is at brave://flags/#brave-dark-mode-block.

Thank you! :heart:
