### ISSUE TITLE
Fix typo in Brave Menu from "New private window with Tor" to "New Private window with Tor"

### ISSUE THREAD

**Issue by Cleveho** [brave/brave-browser#21432]
## Steps to Reproduce

   1. Check if Private window with Tor is Enabled - brave://settings/extensions
   3. Click on Hamburger Menu
   4. See "New private window with Tor"

## Actual result:
"New private window with Tor"

![New private window with Tor](https://user-images.githubusercontent.com/48880976/156521109-fe4dc596-08c6-4deb-8cc8-0158e5f97175.png)

## Expected result:
"New Private window with Tor"

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave	1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit) 
Revision	d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS	Windows 11 Version 21H2 (Build 22000.493)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by GeetaSarvadnya** [comment]
@Cleveho Thanks for logging the issue.

cc: @rebron

**Comment by TheAresjej** [comment]
@Cleveho The issue has been solved for some time. 😃
![img](https://github.com/brave/brave-browser/assets/19390797/5202a658-165c-4245-8561-9f8ab9ab2c7b)
Version 1.65.133 Chromium: 124.0.6367.208 (Official Build)

**Comment by rebron** [comment]
Closing as stale. For Windows: "New private window" and "New private window with Tor" are the correct text labels.
