### ISSUE TITLE
Github.com in Dark Mode Turns Complete White while Blocking Elements

### ISSUE THREAD

**Issue by Cleveho** [brave/brave-browser#21431]
## Steps to Reproduce

   1. Go to https://github.com/Brave or Google.com ( In Dark mode)
   2. Right Click & Select Block Elements
   3. Page Turns Complete White (Elements not visible)

## Actual result:
Unable to block elements on GitHub Repositories page in dark mode (Page turn white).

![Screenshot-Github.com)](https://user-images.githubusercontent.com/48880976/156517591-8f5689f7-d763-4216-9edb-8939832b8d91.png)

## Expected result:
Should be able to block elements on GitHub Repositories page in dark mode.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave	1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit) 
Revision	d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS	Windows 11 Version 21H2 (Build 22000.493)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Issue doesn't happen on Github.com but only in GitHub Repositories page /
eg - https://github.com/brave/

**Sites Also Affected** **(Same Steps to Reproduce as Above)**
https://www.google.com/
https://www.bhaskar.com/
https://www.aajtak.in/

**Comment by antonok-edm** [comment]
Appears to be fixed now (I think this was related to https://github.com/brave/brave-browser/issues/29185)
