### ISSUE TITLE
Disable the send button when custom per-gas tip or price is set to below the recommended limit as doing so results in failed transaction

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#21445]
## Description 
Transaction resulting in error when custom per-gas tip or price is set below the recommended/initial limit.

## Steps to reproduce 

   1. Open send to initiate a transaction
   2. Fill the amount and account details, click send
   3. Select edit "gas fee" and set the per gas tip or price below the initial values

## Actual result 
Transaction is being errored out

## Expected result
Disable the send button (same UX like iOS) to inform the user to avoid setting low prices as doing so results in errored transaction. Keep the same UX as iOS.

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.35.103

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

This can be done on OS/Desktop, confirm it with @jamesmudgett

**Comment by Pavneet-Sing** [comment]
Discussed with @jamesmudgett to keep it same as desktop and android. iOS probably need to update it.

**Comment by bbondy** [comment]
@Pavneet-Sing can we close this? If this is an iOS issue pls add it to brave/brave-ios

**Comment by HEagle18** [comment]
Closing out. Chatted with iOS team they don't need this issue either.
