### ISSUE TITLE
A way to disable Brave Lens for image search.

### ISSUE THREAD

**Issue by KayLeung** [brave/brave-browser#21442]
## Description 

In Chrome, you can disable Google Lens with "chrome://flags/#enable-lens-region-search"

## Expected result:
Disable "chrome://flags/#enable-lens-region-search" and search using Google Image instead.

## Brave version (brave://version info)

V1.36.109

## Version/Channel Information:

- Can you reproduce this issue with the current release?  YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the nightly channel? YES

**Comment by rebron** [comment]
@KayLeung That same flag is in Brave. brave://flags/#enable-lens-region-search Does that work for you?

**Comment by KayLeung** [comment]
> @KayLeung That same flag is in Brave. brave://flags/#enable-lens-region-search Does that work for you?

Nope. That's why I created this issue. Thanks.

**Comment by bsclifton** [comment]
+1 from folks in https://old.reddit.com/r/brave_browser/comments/t5kzur/how_do_i_turn_off_this_brave_lens_thing_i_just/

**Comment by bsclifton** [comment]
cc: @emerick in case we can put a regex exception in the localization scripts (ex: don't translate `Google Lens`)

**Comment by EyeSalt** [comment]
Flags won't disable it for me either. Brave v1.36.109. Very annoying when a feature is enabled without asking, especially when disabling it is taken away.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.36.115 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the test plan from the description 
- Confirmed `Search Google for image` context menu item is shown when right-clicking on any image

Google as default SE | `Search Google for image` context menu
--|--
![image](https://user-images.githubusercontent.com/38657976/158333069-97591ad0-e1f3-4cf8-8e84-b8183a476119.png) | ![image](https://user-images.githubusercontent.com/38657976/158333217-3df7b787-d16c-4bd1-b700-a800e051e50d.png)
