### ISSUE TITLE
Implement browser support for Brave Search Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#21446]

**Comment by IronMaltese** [comment]
Does this PR mean that Brave Search ads will reward bat in the the browser, because that's the only reason why I don't use brave search :)

**Comment by tmancey** [comment]
brave search is great without ads :-), keep an eye out for more posts concerning product improvements.

**Comment by stephendonner** [comment]
@aseren @tmancey this needs a testplan; would one of you mind providing a detailed one for starters, given its importance?  cc @brave/qa-team

**Comment by aseren** [comment]
@stephendonner, the implemented functionality needs be tested in this issue: https://github.com/brave/brave-browser/issues/23002
