### ISSUE TITLE
`Brave.Wallet.UsageDaysInWeek=0` & `Brave.Wallet.UsageMonthly.2=0` doesn't work for Android

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21448]
## Description 
`Brave.Wallet.UsageDaysInWeek=0` & `Brave.Wallet.UsageMonthly.2=0` doesn't work for Android

## Steps to reproduce 
Follow steps from https://github.com/brave/brave-browser/issues/21063#issuecomment-1058097153

## Actual result 
Value 0 is not set for `Brave.Wallet.UsageDaysInWeek` & `Brave.Wallet.UsageMonthly.2`

## Expected result
Should set 0 value for both metrics

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes when 1.36.x Release 2 goes out on Android
- Can you reproduce this issue with the current Play Store Beta version? Yes I guess
- Can you reproduce this issue with the current Play Store Nightly version? Yes I guess

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.36.109

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @DJAndries @GeetaSarvadnya @bbondy

**Comment by GeetaSarvadnya** [comment]
Verified the issue in Desktop `1.36.109` - Issue is not reproducible in Windows 10 x64.

The issue is reproducible in Android Tab `1.36.109`

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.36.115 x64 build

<details>
<summary><code>Brave.Wallet.UsageDaysInWeek=0</code> - <b>Passed</b></summary>

- Set device date to March 1st
- Clean install and enable wallet
- Move device date ahead by 1 week
- Relaunch browser and check local-state, shows `Brave.Wallet.UsageDaysInWeek`
- Quit browser and move device date ahead by 1 day
- Relaunch browser and check local-state, shows `Brave.Wallet.UsageDaysInWeek=1`
- Quit browser and move device date ahead to next Monday
- Relaunch browser and check local-state, shows `Brave.Wallet.UsageDaysInWeek=0`
- Quit browser and move device date ahead to next Tuesday
- Relaunch browser and check local-state, still shows `Brave.Wallet.UsageDaysInWeek=0` 

![image](https://user-images.githubusercontent.com/17010094/158370855-de5d661e-34d5-428e-bbc4-7770b79449b3.png) | ![image](https://user-images.githubusercontent.com/17010094/158370871-ee92af38-b371-4abf-a0ef-004eadf1acad.png)
-- | --

</details> 
<details>
<summary><code>Brave.Wallet.UsageMonthly.2=0</code> - <b>Passed</b></summary>

- Set device date to March 1st
- Clean install and enable wallet
- Quit browser and move device date ahead by 1 month April 1st
- Relaunch browser
- Refresh local-state, shows `Brave.Wallet.UsageMonthly.2`=0
- Quit browser and move device date ahead by 1 month May 1st
- Relaunch browser
- Refresh local-state, still stays `Brave.Wallet.UsageMonthly.2=0`
- Quit browser and move device date ahead by a week to May 8th
- Relaunch browser
- Refresh local-state still stays `Brave.Wallet.UsageMonthly.2=0`

![image](https://user-images.githubusercontent.com/17010094/158370925-c425a0dd-24cb-4b47-8977-07c57c43e915.png) | ![image](https://user-images.githubusercontent.com/17010094/158370905-57200adc-a60f-4715-b7c0-51a60af29487.png) | ![image](https://user-images.githubusercontent.com/17010094/158370937-114790cd-ab70-4a8e-b8a6-16af5c8de3a1.png) | ![image](https://user-images.githubusercontent.com/17010094/158370968-bf78cdc4-c08f-42ca-a93e-68773c2ddc59.png)
-- | -- | -- | --

</details>
