### ISSUE TITLE
Add Brave Talk to Android menu

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#21447]
Brave Talk is available in the menu on iOS but it is not yet there on Android. An option to go to Brave Talk at talk.brave.com should be added.

**Comment by deeppandya** [comment]
@mattmcalister what should be the position ?

**Comment by timchilds** [comment]
@deeppandya between "Set as default browser" and "Brave Rewards" makes sense to me. Unless @mattmcalister has another idea? The Android menu is looking a little unwieldy - we should try to clean it up at some point.

**Comment by timchilds** [comment]
@deeppandya checking with the design team now.

**Comment by Sam-Sibley** [comment]
Brave talk icon for Settings menu is here:
https://www.figma.com/file/QqaIjdrXobryTT3Zd9wcKM/Android-settings?node-id=21%3A1

**Comment by deeppandya** [comment]
@mattmcalister do we need to add brave talk menu in main menu on NTP ?

**Comment by mattmcalister** [comment]
yes, probably best just above Rewards

**Comment by bsclifton** [comment]
Reopening after https://github.com/brave/brave-core/pull/14585 reverted; we missed assigning Milestone and `QA/Yes`, and `Release notes/include` labels on here
