### ISSUE TITLE
Allow custom feed to be disabled rather than just remove it completely

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21449]
## Description 

Allow custom feed to be disabled rather than just remove it completely

## Steps to Reproduce

   1. Add a custom source to News feed via RSS
   2. Android shows a toggle which when disabled removes the custom feed 
   3. Desktop has a more menu button which only allows to remove and not disable it

## Actual result:

No way to disable custom source only remove it completely

## Expected result:
Provide option to disable as well rather than completely removing it 

## Reproduces how often: 

Easy

## Desktop Brave version:

All

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @petemill @alexsafe @mattmcalister @brave/legacy_qa

**Comment by stephendonner** [comment]
See also https://github.com/brave/brave-browser/issues/21348

**Comment by mattmcalister** [comment]
Closed along with https://github.com/brave/brave-browser/issues/21348
