### ISSUE TITLE
Folder created on Android shows up without name 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2144]
## Description 

Folder created on Android shows up without name 

### Devices
Device 1: Desktop Beta (sync chain creator)
Device 2: Samsung Tab (Android 8.1)

## Steps to Reproduce

   1. Enable Sync on desktop 
   2. Sync Android using QR code
   3. Create a bookmark folder on Android and wait for it to sync on desktop 
   4. Creates a folder without name and contains any bookmarks added on Android 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/48509480-3b38ab80-e81f-11e8-8137-77b2aa1bca87.png)
![image](https://user-images.githubusercontent.com/17010094/48509493-4d1a4e80-e81f-11e8-8ee6-655513d3b616.png)

## Expected result:
Should show the folder name correctly that was created on Android

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by AlexeyBarabash** [comment]
Here are the reason why this happened:
```
##brave-core##
Bookmark send ->       
Folder send ->	       
			BookmarkChangeProcessor::BookmarkNodeToSyncBookmark
			bookmark->site.title = base::UTF16ToUTF8(node->GetTitledUrlNodeTitle());
			bookmark->site.customTitle = base::UTF16ToUTF8(node->GetTitle());
		
Bookmark recieve ->    
Folder receive ->      
			model->SetTitle(node, base::UTF8ToUTF16(bookmark.site.title));

##Android##
Bookmark send -> 
			formRequestByBookmarkItem
			title:bookmarkItem.getTitle()
			customTitle:""

Folder send -> 		CreateBookmarkRecord
			title:""
			customTitle:<>
			

Bookmark receive -> 	
Folder receive ->
			BookmarkResolver uses first non-empty
			1) title 
			2) custom 
```
			

According to 
https://cs.chromium.org/chromium/src/components/bookmarks/browser/bookmark_node.cc?sq=package:chromium&g=0&l=102
BookmarkNode::GetTitledUrlNodeTitle
and 
BookmarkNode::GetTitle
return the same data.

I thought in brave-sync `bookmark->site.title` means the title received from html/head field, but `bookmark->site.customTitle` is the value, which is set when bookmark info is edited manually. But I see I cannot diffirentiate it in Chromium bookmark. So going to apply into brave-core fix to use either `bookmark.site.title` or `bookmark->site.customTitle`.
@SergeyZhukovsky @samartnik

**Comment by AlexeyBarabash** [comment]
Made PR https://github.com/brave/brave-core/pull/954 .

**Comment by LaurenWags** [comment]
Attempted to test with `0.57.8` beta on macOS however, since https://github.com/brave/brave-browser/issues/2211 was implemented on b-c, b-c points to prod and the latest Android Sync build available points to Staging, this cannot be tested until we have an updated Android build pointing to production for Sync. Confirmed with @srirambv and marking as `QA/Blocked` until we have an Android build we can test with.
cc @kjozwiak

**Comment by bbondy** [comment]
Removed 0.58.x and 0.59.x labels since only the smallest version it was merged to should be indicated.

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows


Windows:
![image](https://user-images.githubusercontent.com/38657976/49874692-23b40900-fe45-11e8-83d4-baa41b3fc2e3.png)

Android:

![image](https://user-images.githubusercontent.com/38657976/49874804-7b527480-fe45-11e8-8c76-42a5c9176303.png)
