### ISSUE TITLE
P3A settings shows 'anonymise' spelling in en_US locale

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#21456]
## Description 

@pes10k reported that brave://settings/privacy says "This completely anonymised info helps Brave estimate the overall usage of certain features and make them better for you." even in a US locale.

We should use "anonymize" instead and leave "anonymise" to the en_GB translation.

## Steps to Reproduce

   1. Set locale to US English
   2. Visit brave://settings/privacy
   3. Search in page for 'anonymise'

## Actual result:

String contains UK spelling.

## Expected result:

Should use US spelling.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Verified in Brave beta 1.37.77.

## Version/Channel Information:

Happens on all channels. The spelling was introduced in July 2021.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.23 Chromium: 99.0.4844.51 (Official Build) nightly (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.3 (Build 20G415)

Confirmed the spelling of `anonymized` is correct for en-US locale:

before | after
-------|------
<img width="1312" alt="Screen Shot 2022-03-04 at 8 24 27 AM" src="https://user-images.githubusercontent.com/387249/156800935-e8f22035-4b13-45fd-8c38-639a62c45c9d.png"> | <img width="1369" alt="Screen Shot 2022-03-04 at 8 24 07 AM" src="https://user-images.githubusercontent.com/387249/156800969-58e4dea5-6735-4224-87c0-33a69c4de45b.png">
