### ISSUE TITLE
Automatic redirects to IPFS via gateway don't always work

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21454]
## Description 

Automatic redirects to IPFS via gateway don't always work

This is with `go-ipfs` `0.11.0` but also reproduces with the `0.12.0` release.

## Steps to Reproduce

   1. install `1.38.20`
   2. launch Brave
   3. open `brave://settings/ipfs`
   4. toggle `Redirect IPFS resources to the configured IPFS gateway` to `On`
   5. load `https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`

## Actual result:

It remains on `https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`

<img width="1312" alt="Screen Shot 2022-03-03 at 11 05 14 AM" src="https://user-images.githubusercontent.com/387249/156635732-2d792107-3602-4a23-9db0-7153cbb148c3.png">

## Expected result:

Per `https://github.com/brave/qa-resources/blob/654c91cbf44d25cf74c5143c5cb42477458fa7b4/wikitemplate-IPFS.md#automatic-redirects-to-ipfs` it should go to `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.38.20 Chromium: 99.0.4844.51 (Official Build) nightly (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.3 (Build 20G415)

cc @spylogsster @lidel @MadhaviSeelam

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.73 Chromium: 107.0.5304.62 (Official Build) beta (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.46.73`
2. launched Brave
3. opened `brave://settings/ipfs`
4. toggled `Redirect IPFS resources to the configured IPFS gateway` to `Enabled`
5. loaded the respective URLs shown below
6. clicked on the `Use a Brave local IPFS node` and `Use a public gateway` options, separately
7. confirmed the correct URLs loaded

### `QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`

`brave://settings/ipfs` | `interstitial page` | `local IPFS node` | `public gateway`
---------|----------|---------|---------
<img width="1336" alt="Screen Shot 2022-10-21 at 2 39 23 PM" src="https://user-images.githubusercontent.com/387249/197294257-651773bf-3d7a-4b50-a5c0-ae62f4c18d53.png"> | <img width="1336" alt="Screen Shot 2022-10-21 at 2 39 41 PM" src="https://user-images.githubusercontent.com/387249/197294355-64a41487-6dc5-422b-ae41-61a91346a837.png"> | <img width="1336" alt="Screen Shot 2022-10-21 at 2 39 53 PM" src="https://user-images.githubusercontent.com/387249/197294356-99c6e519-70eb-4cbe-8cc9-3be48f0548d9.png"> | <img width="1312" alt="Screen Shot 2022-10-21 at 2 40 43 PM" src="https://user-images.githubusercontent.com/387249/197294357-9702f4bf-c782-46fb-a2cd-79e8117f5946.png">

### `Wikipedia`

**Comment by yrliou** [comment]
It was reverted on master https://github.com/brave/brave-core/pull/15597, revert to beta is still pending uplift, I think we need to reopen this issue and ping uplift team to merge the revert on beta. cc @cypt4

**Comment by kjozwiak** [comment]
@yrliou @bridiver going to remove this issue from `1.46.x` due to reverting the above work via https://github.com/brave/brave-core/pull/15649. I'll remove the `QA Pass-macOS` label as this will need to be rechecked again once the code/fix is remerged. Assuming we can re-use this issue 👍

**Comment by stephendonner** [comment]
Removed `QA Pass-macOS` since we'll need to re-verify this in 1.47.x.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.108 Chromium: 108.0.5359.71 (Official Build) beta (arm64)
-- | --
Revision | `1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}`
OS | macOS Version 13.0.1 (Build 22A400)


- Verified steps from issue description
- Verified when Automatic redirect to IPFS gateway is enabled and resolve set to gateway it loads `https://dweb.link/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`
- Verified when Automatic redirect to IPFS gateway is enabled and resolve set to local node it loads `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/`
- Verified when redirect is set to Ask loads the interstitial state



brave://settings/ipfs | interstitial page | local IPFS node | public gateway
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/205671710-90323cf0-3067-4171-bc11-4ad84a4a9a76.png) | ![image](https://user-images.githubusercontent.com/17010094/205671917-b9dcc6c1-308d-4877-b28b-02ac4f93d397.png) | ![image](https://user-images.githubusercontent.com/17010094/205671623-572f1f86-f005-40c9-bd0e-3e6c5828247e.png) | ![image](https://user-images.githubusercontent.com/17010094/205671789-c5e4c3a1-61e0-4a3a-b192-2b6df4e4021c.png)
