### ISSUE TITLE
Can no longer mute tabs in Brave Dev or Brave Beta

### ISSUE THREAD

**Issue by christianjuth** [brave/brave-browser#2145]
## Description 
Chrome offers the ability to mute tabs when audio is playing - tested on official Google Chrome on OSX Mojave Version 70.0.3538.102 (Official Build) (64-bit) - and I am pretty sure this worked on Brave a few weeks ago. I am guessing this is part of Chromium and Brave inherited this feature. However, this feature no longer works on Brave Dev or Brave Beta.

## Steps to Reproduce

   1. Open Brave Dev or Brave Beta
   2. Navigate to YouTube and play any video
   3. Speaker icon should appear on the tab next to the x close button as audio plays 
   4. Icon appears but is no longer clickable (should toggle tab mute when clicked)

## Actual result:
Icon appears in the tab when audio is playing but is not clickable.

## Expected result:
Icon should be clickable and should mute tab.

## Reproduces how often: 
Issue occurs on every attempt on specified browser versions.

## Brave version (brave://version info)

* Brave Dev - Version 0.57.4 Chromium: 71.0.3578.31 (Official Build) dev (64-bit)
* Brave Beta  - Version 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)

### Reproducible on current release:
- Issue occurs on Brave dev and beta builds 

### Website problems only:  
-  Disabling Brave Shields doe not fix the issue
- The issue is not reproducible on the latest version of Chrome

### Additional Information
Also tested in a privet tab since I have browser extensions installed. Speaker icon appears but is still not clickable (see image below). 

<img width="1014" alt="screen shot 2018-11-14 at 7 42 32 pm" src="https://user-images.githubusercontent.com/5768801/48522359-579c0e80-e846-11e8-9ceb-ea1f09b03da4.png">

*Disclaimer: This picture is not meant to endorse Ariana Grande. That was just the first video on the front page of YouTube.*

**Comment by Liunkae** [comment]
+1 from me.

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta(64-bit)
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Mac OS X

Workaround: Right-click the tab and click Mute/Unmute Site.

**Comment by simonhong** [comment]
Duplicated with https://github.com/brave/brave-browser/issues/2025
