### ISSUE TITLE
Add a way to reset local transaction / nonce information (android)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#21457]
Android implementation of [Add a way to reset local transaction / nonce information](https://github.com/brave/brave-browser/issues/19760), to add a reset transaction and nonce option in the settings.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.38.108 x64 build
- Verified test plan from [brave/brave-core#12493](https://github.com/brave/brave-core/pull/12493)
- Verified a new setting for clearing custom nonce and transaction info is available under `Settings -> Brave Wallet`
- Verified clearing removes all transaction data locally

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/165502711-e6036285-ead1-464e-a065-9946cd283266.mp4> | <video src=https://user-images.githubusercontent.com/17010094/165502747-6cd5ad8a-c4b9-47e4-b5fe-2acb7645884a.mp4>
