### ISSUE TITLE
Add native API to access the Ratios server's markets coingecko proxy endpoint for frontend use

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#21455]
## Description
The overall goal is to give the frontend access to the coingecko endpoint for returning top currencies.  We proxy calls to coingecko, through the ratios server here https://github.com/brave-intl/bat-go/pull/1234.  So we need to expose an API in C++ for the frontend code to use that hits the new ratios endpoint.

Add to AssetRatioService from components/brave_wallet/common/brave_wallet.mojom.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/20674#issuecomment-1254693712
