### ISSUE TITLE
Remove refcode from P3A reports

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#21460]
## Description 

Per discussion today, we no longer use the `refcode` field of the P3A measurement associated metadata, and so we should stop reporting it.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.38.75 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```

**Comment by rillian** [comment]
Yes, that's ok. The change only affects P3A.

**Comment by Uni-verse** [comment]
Verification completed on Samsung GS 21, Samsung Tab S7 using 

```
Brave	1.38.107 Chromium: 101.0.4951.41 (Official Build) (64-bit) 
Revision	93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS	Android 12;
```

Fresh Profile:

- Confirmed requests made to the p3a-json.brave.com endpoint should not contain a refcode field at all.

Upgrade Profile:

- Setting up a profile with refcode and then upgrading to 1.38 will send metrics without the refcode .
- Collect metrics with refcode, upgrade the profile and then move the clock one week ahead will send new reports without refcode.

1.37 | 1.38
-|-
<img width="749" alt="Screen Shot 2022-04-26 at 9 33 02 PM" src="https://user-images.githubusercontent.com/17885425/165423642-fca3e9bd-c303-4cca-a74e-02c80cbaa9a0.png"> | <img width="918" alt="Screen Shot 2022-04-26 at 9 27 56 PM" src="https://user-images.githubusercontent.com/17885425/165423640-7b273bc8-c8d6-4c8a-bbdf-bdc04763ffdd.png">
