### ISSUE TITLE
Make adding custom RSS feed easier similar to iOS 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21468]
## Description 

Make adding custom RSS feed easier similar to iOS 

## Steps to Reproduce

   1. Open customize news 
   2. Type in `https://news.google.com` as custom source
   3. Add source throws error 

## Actual result:

https://user-images.githubusercontent.com/17010094/156713813-c8f32ff5-4f71-4f9f-b8b0-b8d061067e43.mp4

## Expected result:
Similar to iOS where it auto detects the available RSS feed and lists it so user can enable which ever is required

https://user-images.githubusercontent.com/17010094/156714565-d764cb61-5ce4-43dc-b639-0e7487aba4f7.MP4

## Reproduces how often: 

Easy

## Desktop Brave version:

All

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes for Desktop
- Can you reproduce this issue with the beta channel? Yes for Desktop 
- Can you reproduce this issue with the nightly channel? Yes for both Desktop and Android

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @alexsafe @petemill @mattmcalister

**Comment by petemill** [comment]
This is already supported

**Comment by kjozwiak** [comment]
> This is already supported

Closing the issue as this was labelled as `closed/duplicate` and `closed/stale`. As per the above, it's already being supported.
