### ISSUE TITLE
Enable first run dialog on Windows

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#21464]
First run dialog is launched on macOS and linux (see https://github.com/brave/brave-browser/issues/12679)
We want to launch it on Windows also.

**Comment by MadhaviSeelam** [comment]
Brave | 1.38.71 Chromium: 100.0.4896.46 (Official Build) beta (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

Clean Install 1.38.x
Launch Brave
Verified  FirstRun dialog is displayed

<img width = "900" alt="First run dialog on windows"  src="https://user-images.githubusercontent.com/98358127/160684919-404f4fa2-76a9-4ef0-8cb1-0e0fbf224740.png">

Note: There was a design change so dialog design will not match to mockup in this story.  There is a follow up and tested UI and functionality as part of #21694

**Comment by kjozwiak** [comment]
We'll need to re-test this via `1.37.x` as we're uplifting it into the `1.37.x` maintenance release via https://github.com/brave/brave-core/pull/12692. The above will require `1.37.111` or higher for verification using `1.37.x`.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.37.113 Chromium: 100.0.4896.88 (Official Build) (64-bit)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
