### ISSUE TITLE
ModalBackupRecovery dialogue should used updated component

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#2146]
The updated component is available as of `brave-ui@0.34.1`, slight modification will need to be made to `pageWallet.tsx` to use `number` type for `activeTabId`

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/909
