### ISSUE TITLE
ipfs.io blog isn't loading over IPNS when local node is installed

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21462]
## Description 

ipfs.io blog isn't loading over IPNS when local node is installed

## Steps to Reproduce

   1. install `1.38.21`
   2. launch Brave
   3. load `ipns://ipfs.io`
   4. click on `Use a Brave local IPFS node`
   5. wait for installation to complete
   6. load `https://blog.ipfs.io/24-uncensorable-wikipedia`
   7. click on the `IPFS` button/badge in the URL bar

## Actual result:

Land on `http://blog.ipfs.io.ipns.localhost:48081/24-uncensorable-wikipedia/`

![ipfs-1](https://user-images.githubusercontent.com/387249/156658315-7f8e5498-0f7e-4ace-8344-68ebf31e67ab.png)

## Expected result:
According to our test plan, it should be `ipns://blog.ipfs.io/24-uncensorable-wikipedia` - not sure if this is still correct?

![ipfs-2](https://user-images.githubusercontent.com/387249/156658370-4fd695c6-7a95-46dd-8c9b-fcc384e8d0a2.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.38.21 Chromium: 99.0.4844.51 (Official Build) nightly (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1566)

cc @spylogsster @lidel @MadhaviSeelam

**Comment by lidel** [comment]
Yes, this is a bug, native protocol scheme (in this case, `ipns://`)  should be used when local node is enabled.

**Comment by stephendonner** [comment]
Sorry, plum forgot!
