### ISSUE TITLE
Brave News - "velocity" (when scrolling up) stops when top is reached

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21475]
## Description

For me, as I'm using it on Beta for example... it seems just fine. There is a behavior which maybe he is referring to...
If you scroll back up after you're done with news, usually it's always having a velocity. When it gets to the top of news, it stops bascially. This might be what he is reporting

[clifton](https://app.slack.com/team/U13AH4AJY)  [11 hours ago](https://bravesoftware.slack.com/archives/C02SC5AKTAS/p1646378917730699?thread_ts=1646368195.141459&cid=C02SC5AKTAS)
then you have to try and swipe back up to get back to the regular NTP that you expect (instead of the "velocity" of moving up just naturally taking you to the top of NTP)

## Steps to reproduce 

   1. Fresh profile
   2.  Use a build with News enabled (ex: Beta, 1.37.80)
   3. Open a new tab
   4. You can see News poking up from the top of NTP
   5. Scroll down, opt-in to Brave News
   6. When feed is showing, go ahead and scroll down. You'll notice the swipe creates a velocity or momentum as it scrolls down.
   7. Scroll back up and try to reach the top of the NTP

## Actual result 
The velocity immediately stops when it gets near the top. It takes three full swipes to get back to where you can see the stats / bookmarks / widget

For reference- where it stops first time:
<img src="https://user-images.githubusercontent.com/4733304/156820926-76c3e142-db34-4c23-99b0-1ed7648ab8ae.png" width="250px">

When you do another big swipe up (swipe 2), this is as far as it gets:
<img src="https://user-images.githubusercontent.com/4733304/156821008-f239ac8f-056b-43d4-ad9a-a2df9acebd4b.png" width="250px">

When you try a 3rd time, it finally gets there
<img src="https://user-images.githubusercontent.com/4733304/156821050-7f66939d-6950-476a-9ee7-652bc43ec081.png" width="250px">

## Expected result
The velocity shouldn't have stopped; it should keep naturally scrolling and get to the top (where screenshot 3 shows)

## Issue reproduces how often 
100%

**Comment by kjozwiak** [comment]
Above will require `1.38.105` or higher for `1.38.x` verification.

**Comment by Uni-verse** [comment]
Verified using `1.38.105, Chromium 101.0.4951.41`

Devices: 
`Samsung GS21` | `Android 12`
`Samsung Tab S7` | `Android 12`

**Acceptance Criteria**

- Scrolling velocity/performance when scrolling back to top is constant and will stop at top of homepage.
- Scrolling down from beginning of the news feed was consistent and did not snag.
- Scrolling through news feed was smooth.
- Able to scroll through feed in landscape on mobile and tablet devices.
- Scroll velocity is reduced over time and will eventually stop.
- News feed will fetch new data as user scrolls down without delay. 

Issues noted: Scrolling from the top of the new tab page will stop when news feed begins - https://github.com/brave/brave-core/pull/12865#issuecomment-1104456103


https://user-images.githubusercontent.com/17885425/164803279-b5776734-099d-4914-97bf-4ff7583eb081.mp4

https://user-images.githubusercontent.com/17885425/164803305-57abf648-6b21-49f3-9e68-5d1b00170ba6.mp4
