### ISSUE TITLE
[Android] Add QR code scanner to address bar

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#21478]
**Summary**
A QR code scanner is already available in the iOS app. We should add the same feature to Android to be consistent.

**Requirements**
- When the URL bar is tapped, display a QR icon in the address bar (to the left of voice search icon). 
- On tap, opens a QR scanner in modal (same modal stye as tab groups?)
- On successful scan, opens website.
- Include back icon for user to back out of the QR scanner (see mockup).
- Copy: same as iOS (see mockup).

**Mockup**
![image](https://user-images.githubusercontent.com/28269287/156837012-e57b5007-4e0c-44be-a57a-4ea7eddc8555.png)

**Comment by aman-m1** [comment]
Can we have the ability to scan QR code from a file (image) as well that can be picked from device?

**Comment by Uni-verse** [comment]
Verified using the following build(s):

```
Brave	1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
Revision	2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS	Android 12; Build/SP1A.210812.016
```

- Verified QR code scanner icon is in the url bar when curser is present
- Verified tapping code scanner will launch the modal
- Verified webpage is loaded on successful scan
- Verified tapper the `back arrow` will close the QR code scanner modal
- Verified scanning `webpage url` will launch the webpage or populate in the url box
- Verified scanning QR code for `crypto wallet address` populates the value in the url box
- Verified copy is same as on iOS

Example | Example | Example
-|-|-
![screenshot-1666189176599](https://user-images.githubusercontent.com/17885425/196747060-d9289859-f8fc-440e-badf-49dafdf7df6b.png) | ![screenshot-1666189203869](https://user-images.githubusercontent.com/17885425/196747092-35337d53-6ee1-415f-b6f7-57c558ec5d11.png) | ![screenshot-1666190508754](https://user-images.githubusercontent.com/17885425/196747124-a5d64cb2-3618-4a09-8742-e8a831ad38bc.png)
![screenshot-1666195128052](https://user-images.githubusercontent.com/17885425/196747236-7e406ea8-0817-4ccc-a93d-32e70ca586b5.png) | ![screenshot-1666195229939](https://user-images.githubusercontent.com/17885425/196747246-435acc2f-07be-484b-bda0-98fb9a45af0f.png) | ![screenshot-1666195112128](https://user-images.githubusercontent.com/17885425/196747305-9f226265-84d9-49b2-ae3e-5b2ca9c7d02b.png)
