### ISSUE TITLE
update "Manage your wallet" wording - follow up to 19768

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#21472]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/19768

The "Manage your wallet" button on brave://rewards should say "Manage Brave Rewards" and when you click on the button, the popup should also say "Manage Brave Rewards" per https://github.com/brave/brave-browser/issues/19768#issue-1064632419.

So, there are 2 places to update:
- [ ] Fix text on button in Rewards settings page
- [ ] Fix text inside Manage Your Wallet popup modal which is accessed via button

## Steps to Reproduce

   1. Using 1.37.x open brave://rewards page
   2. Opt-in if you have not already
   3. Locate "Manage your wallet" section under the wallet panel
   4. Click on button

## Actual result:

Button | Modal
----- | -----
<img width="1196" alt="Screen Shot 2022-03-04 at 11 54 08 AM" src="https://user-images.githubusercontent.com/28145373/156805824-bdb5b377-8789-4725-8757-f61006ba48dd.png"> | <img width="731" alt="Backup" src="https://user-images.githubusercontent.com/28145373/157278679-585c9a3f-2f46-45fc-ba84-eb56648af1d1.png">

## Expected result:

Per #19768 both button and modal title should say "Manage Brave Rewards"

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.82 Chromium: 99.0.4844.51 (Official Build) beta (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by LaurenWags** [comment]
@zenparsing please note updated issue description 👍🏻

**Comment by kjozwiak** [comment]
Requires `1.37.91` or higher for QA verification's via `1.37.x`.
