### ISSUE TITLE
Implement swap on BSC, Avalanche, Optimism, Fantom, and Celo

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#21473]

**Comment by kjozwiak** [comment]
Above will require `1.37.99` or later for verifications on `1.37.x`.

**Comment by Uni-verse** [comment]
Verification in progress using

```
Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.1 (Build 21C52)
```
Transaction Hash:

[Celo Testnet Alfajores](https://alfajores-blockscout.celo-testnet.org/tx/0x105210ebcdbaed6a7d145ef0755ae9172aa0e32f6e8220d4c680616f1c9e7c5b/token-transfers
)

[Fantom Opera](https://ftmscan.com/tx/0x65c8c1d1b3a6b64a689bf882787088308e138fca943368f22f5d85d6a09a7aa2  )

[Binance Testnet](https://testnet.bscscan.com/tx/0x4a2345409e6077a6188c54ded81a3753b20b5a13257e03d98d9846cc9a77eb43  )

[Avalanche Fuji Testnet](https://testnet.snowtrace.io/tx/0x41fe9a26d10e34ac33a83c7bdc229620c8711e25b8e9a26b3cea17127c6b03b7)
  
  Optimism: Test net not available (Issue Coming)
  
![Screen Shot 2022-03-28 at 1 53 06 PM](https://user-images.githubusercontent.com/17885425/160486031-c1e5e157-b3b7-4685-b866-0031d1e29c4e.png)
![Screen Shot 2022-03-28 at 1 53 57 PM](https://user-images.githubusercontent.com/17885425/160486043-c41f7490-e3b3-4d37-838d-2bd24a848e50.png)
![Screen Shot 2022-03-28 at 1 54 15 PM](https://user-images.githubusercontent.com/17885425/160486046-bef3e963-d32f-473c-8b95-c9d24da5fd6f.png)
![Screen Shot 2022-03-28 at 2 00 28 PM](https://user-images.githubusercontent.com/17885425/160486426-459da9f2-ed5f-40ba-a271-ca7b436b40ab.png)
