### ISSUE TITLE
TypeError when trying to submit IPFS gateway address

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21479]
## Description 

TypeError when trying to submit IPFS gateway address

## Steps to Reproduce

   1. install `1.38.23`
   2. launch Brave
   3. open `brave://settings/ipfs`
   4. click on the `Change` button on `IPFS Public Gateway Address`
   5. enter `https://infura-ipfs.io`
   6. click `Submit`
   7. look in the JS console for errors

## Actual result:

Nothing happens

```
settings.js:406 Uncaught (in promise) TypeError: this.fire is not a function
    at settings.js:406:500
```

<img width="1544" alt="Screen Shot 2022-03-04 at 12 38 43 PM" src="https://user-images.githubusercontent.com/387249/156839630-c87a1d75-2223-4918-ae74-4436c4b4c637.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.38.23 Chromium: 99.0.4844.51 (Official Build) nightly (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.3 (Build 20G415)

cc @spylogsster @lidel @MadhaviSeelam

**Comment by stephendonner** [comment]
@spylogsster I ran into this on `1.36.109` - can you please take a look when you get a chance?  Thanks!

**Comment by srirambv** [comment]
This seems to be fixed. I don't see any errors in console. Just error about Origin isolation error when trying to add.

**Comment by stephendonner** [comment]
> This seems to be fixed. I don't see any errors in console. Just error about Origin isolation error when trying to add.

This was fixed by https://github.com/brave/brave-browser/issues/26104.  I'll mark it a duplicate.
