### ISSUE TITLE
Disable default peeking card

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#21477]
## Description 

As per 
https://bravesoftware.slack.com/archives/C0816QH3R/p1646406893336039?thread_ts=1646254593.006359&cid=C0816QH3R

News opt-in card is not shown by default. Instead it is available in Brave news Settings.

## Steps to reproduce 

   1. Go to Settings-Brave news
   2. Enable Brave news
   3. Close settings - Opt in card should show
   4. Click show news and news feed should appear

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.36.110 
**Clean Install**
- Verified on clean install there is no Brave News Opt-in peeking card is shown
- Verified once enabling Brave News shows the opt-in card on the next NTP
- Verified closing the opt-in card, and enabling show Brave News via settings enables the news feed on NTP

**Upgrade Install**
- Verified upgrading from 1.35.102, doesn't show the opt-in card by default
- Verified user is still enable to enable Brave news via Settings
- Verified once Brave News is enabled, opt-in card is shown on NTP
- Verified closing the opt-in card, and enabling show Brave News via settings enables the news feed on NTP

Clean Install | Upgrade Install
-- | --
<video src=https://user-images.githubusercontent.com/17010094/157018683-08a92a2c-8f1d-4e9b-922b-325d3e1531cf.mp4> | <video src=https://user-images.githubusercontent.com/17010094/157018743-5be6c789-5638-4ce0-842b-ea6f7b0a67dd.mp4>

-------
Verification passed on Samsung Tab A with Android 10 running 1.36.110 
**Clean Install**
- Verified on clean install there is no Brave News Opt-in peeking card is shown
- Verified once enabling Brave News shows the opt-in card on the next NTP
- Verified closing the opt-in card, and enabling show Brave News via settings enables the news feed on NTP

**Upgrade Install**
- Verified upgrading from 1.35.102, doesn't show the opt-in card by default
- Verified user is still enable to enable Brave news via Settings
- Verified once Brave News is enabled, opt-in card is shown on NTP
- Verified closing the opt-in card, and enabling show Brave News via settings enables the news feed on NTP

Clean Install | Upgrade Install
-- | --
<video src=https://user-images.githubusercontent.com/17010094/157019856-782acba5-86c5-45bd-a401-f26a6c12f43c.mp4> | <video src=https://user-images.githubusercontent.com/17010094/157019897-c1f5de03-d2cb-41b3-8a27-6d381d514f3c.mp4>
