### ISSUE TITLE
Inaccurate usage ping wallet parameter after update to 1.36.x

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#21476]
## Description 

When the wallet usage ping fixes were introduced, updates from earlier versions to 1.36.x were not considered in regards to the impact of internal state. In order to calculate the wallet activity flag, we compare the "last unlock time" to the "last reported unlock time". The latter timestamp was what was added to 1.36. By default, that time is set to the start of Unix epoch (1970-01-01). If they used their wallet in a previous version, and then updated to 1.36, the wallet flag would be set to 7 upon startup, since the "last unlock time" would be greater than 1970-01-01.

This results in inflated stats, since any user that used their wallet in a previous version at any point in time would be considered a monthly user after updating.

## Steps to Reproduce

   1. Install 1.35.x. Use the wallet.
   2. Upgrade to 1.36.x. Advance system time by one day. Open the browser.
   3. Using MITM proxy, verify that the `wallet` parameter of the usage ping is set to 7.

## Actual result:

`wallet` parameter is set to 7 after updating.

## Expected result:

`wallet` parameter should be set to 0 after updating.

## Reproduces how often: 
Easily

## Desktop Brave version:
1.36.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

Will raise PR soon

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.36.110 x64 build
- Verified steps from [brave/brave-core#12488](https://github.com/brave/brave-core/pull/12488)
- Verified steps from issue description as well
- Verified installing 1.35.102 and creating wallet sends a ping with `walletActive=0`
- Verified upgrading to 1.36.110 and moving the device date ahead by 1 day and relaunching the browser sends a ping with `wallet2=0`
- Verified using wallet after upgrade and moving device date ahead by 1 more day and relaunching the browser sends a ping with `wallet2=7` 


1.35.102 ping | 1.36.110 ping before wallet use | 1.36.110 ping after wallet use
-- | -- | --
<img src="https://user-images.githubusercontent.com/17010094/156970025-2a0b130e-99a0-438b-9d0f-2bb252b84f30.png"> | <img src="https://user-images.githubusercontent.com/17010094/156970033-3e4d8211-0f1c-4039-9832-55599e319cbc.png"> | <img src="https://user-images.githubusercontent.com/17010094/156970036-1381baf3-a804-403e-a03b-c28f5a3d42a1.png">
