### ISSUE TITLE
Adjust wording on monthly statement - follow up to 19768

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#21481]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/19768

The title of the monthly statement should say "Brave Rewards Activity" per https://github.com/brave/brave-browser/issues/19768#issue-1064632419. However you'll notice in screenshot below that it says "Brave Rewards Brave Rewards Activity". Per discussion with @Miyayes gray text should just say "Activity" (Perhaps he can advise if the gray text should be removed altogether here? It might look weird to have "Brave Rewards" in black and then "Activity" in gray.)

## Steps to Reproduce

   1. Using 1.37.x open brave://rewards page
   2. Opt-in if you have not already
   3. Open Monthly Statement

## Actual result:

<img width="445" alt="Screen Shot 2022-03-04 at 3 58 15 PM" src="https://user-images.githubusercontent.com/28145373/156841949-3f3e3525-5151-432d-88b6-fc6c2b637521.png">

## Expected result:

Per #19768 should say "Brave Rewards Activity"

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.82 Chromium: 99.0.4844.51 (Official Build) beta (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by aman-m1** [comment]
Also "Manage your wallet" hasn't changed (v1.38.23). Which should be "Manage Brave Rewards" as per https://github.com/brave/brave-browser/issues/19768#issue-1064632419

**Comment by LaurenWags** [comment]
np, thanks @aman-m1. If you see more please feel free to log issues for them 👍🏻

**Comment by kjozwiak** [comment]
Requires `1.37.91` or higher for QA verification's via `1.37.x`.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.37.91 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the STR from the description and ensured updated wording `Brave Rewards Activity` is displayed on the monthly statement
![image](https://user-images.githubusercontent.com/38657976/158196966-80d6b77e-ccff-4151-85e6-f8561a6a578b.png)
