### ISSUE TITLE
Don't show `Start using Rewards` NTP promo if Rewards widget is visible

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#21483]
## Description 

There should only by one CTA promo shown to the user to `Start using Rewards`. 

## Steps to Reproduce

   1. Create a new profile. 
   2. Create a new tab until reaching a NTPSI promo.
   3. Notice two CTAs to Start using Rewards.

## Actual result:

![image](https://user-images.githubusercontent.com/5951041/156865060-b41073b8-63c7-4e05-83cb-30905950d21b.png)

## Expected result:
Should only have one call out to start using Rewards.

## Reproduces how often: 

easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @Miyayes @zenparsing

**Comment by Miyayes** [comment]
I think this is resolved. We just eliminated the blue tooltip in bottom left corner.
