### ISSUE TITLE
Adjust wording on Monthly Statement when using custodial wallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#21482]
## Description 

When using a custodial wallet (Uphold, Gemini), and auto contribute is performed, on the Monthly Statement the word "wallet" is used. Per https://github.com/brave/brave-browser/issues/19768 we're moving away from use of the word "wallet" so this seems like a candidate for adjustment.

## Steps to Reproduce

   1. Install 1.37.x staging env with short retry interval (ex. `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=9,"*/brave_rewards/*"=9,"*/bat-native-ads/*"=9,"*/bat-native-confirmations/*"=9,"*/brave_ads/*"=9,"*/brave_user_model/*"=9 --brave-ads-staging --rewards=staging=true,reconcile-interval=5,retry-interval=60 --brave-ads-debug`
   2. Enable Rewards, link KYC'd Uphold or Gemini account
   3. Add sites to AC list, wait for AC to complete
   4. Look at Monthly Statement

## Actual result:

Uphold example below, but I believe Gemini behaves similarly. N/A for bitFlyer.

<img width="947" alt="Screen Shot 2022-03-04 at 4 27 27 PM" src="https://user-images.githubusercontent.com/28145373/156844455-2d252777-d532-4e03-b328-09f335498826.png">

## Expected result:

Probably just say Uphold or Gemini in parenthesis, no "wallet"

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.82 Chromium: 99.0.4844.51 (Official Build) beta (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a (but yes)
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by kjozwiak** [comment]
Requires `1.37.91` or higher for QA verification's via `1.37.x`.
