### ISSUE TITLE
Add missing collapse/expand arrows for bookmark folders in Sidebar

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21484]
## Description 

Add missing collapse/expand arrows for bookmark folders in Sidebar

## Steps to Reproduce

   1. install latest `nightly`
   2. launch Brave
   3. import `https://github.com/brave/qa-resources/blob/master/brave_sorted_1000.html`
   4. click on the `Bookmarks` icon in the Sidebar
   5. look at the nested folders

## Actual result:

Nested folders are missing the collapse/expand arrows

<img width="1312" alt="Screen Shot 2022-03-04 at 6 52 42 PM" src="https://user-images.githubusercontent.com/387249/156865065-90d83c25-7585-4b71-8f6c-58af12d43fa2.png">

## Expected result:

Compare with the native Bookmarks view

<img width="1369" alt="Screen Shot 2022-03-04 at 9 52 48 AM" src="https://user-images.githubusercontent.com/387249/156865069-b53bfd8b-19c2-4580-93cb-014c0a2e7cd6.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.38.23 Chromium: 99.0.4844.51 (Official Build) nightly (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.3 (Build 20G415)

cc @simonhong @rebron

**Comment by rebron** [comment]
cc: @aguscruiz

**Comment by aguscruiz** [comment]
Is there a reason why we can't use the same design assets and style for both?

**Comment by simonhong** [comment]
Sidebar bookmarks panel UI needs more customizing as we forked upstream's sidepanel bookmarks page
and only our folder icon is applied.
And, bookmarks manager page's icon should be updated to ours.

**Comment by aguscruiz** [comment]
@simonhong can we just reuse the bookmark manager's styles, icons and sizes for the sidebar view?

Let me know if you need more specifics, but basically so they both look the same.

**Comment by rebron** [comment]
Closing as stale. @stephendonner I believe we addressed this issue before releasing bookmarks sidebar panel.

**Comment by stephendonner** [comment]
> Closing as stale. @stephendonner I believe we addressed this issue before releasing bookmarks sidebar panel.

Yup, looks good to me with 

Brave | 1.47.33 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

The "twisties" -- expand/collapse arrows -- are back:

<img width="1198" alt="Screen Shot 2022-11-01 at 9 53 26 AM" src="https://user-images.githubusercontent.com/387249/199292307-f2f2a2bc-7da0-4e7c-8c01-8ac264f8c435.png">
