### ISSUE TITLE
Bookmarks is sent via sync even when bookmark sync is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2148]
## Description 

Bookmarks is sent via sync even when bookmark sync is disabled

## Devices
Device 1: Desktop b-c 0.57.6
Device 2: Samsung Tab (Android 8.1)

## Steps to Reproduce

1. Import 5k bookmarks file on b-c
2. Enable sync on b-c
3. Disable bookmark sync on b-c
4. Visit any site in a new tab and add it as bookmark
5. Add an Android device to sync chain
6. Several bookmarks are sync'd on Android even though bookmark sync is disabled in step 3

## Actual result:

b-c sync code 
![image](https://user-images.githubusercontent.com/17010094/48527304-b4a0c000-e858-11e8-9a70-492c1ca99e5f.png)
Bookmarks on b-c
![image](https://user-images.githubusercontent.com/17010094/48527333-d26e2500-e858-11e8-8368-0f1869820ea9.png)
![image](https://user-images.githubusercontent.com/17010094/48527346-dbf78d00-e858-11e8-8d70-41f1a361719a.png)
Sync code on Android
![image](https://user-images.githubusercontent.com/17010094/48527357-e44fc800-e858-11e8-9178-e0a180cd0227.png)
Bookmarks on Android
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17010094/48527489-57593e80-e859-11e8-9638-df26b01cf6ab.gif)

## Expected result:
Should not sync any bookmarks if b-c has bookmark sync disabled 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on Beta
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@darkdh agree that disable bookmark sync doesn't mean delete all bookmarks from chain but without it being enabled on b-c why is Android pulling in bookmarks ? 

>This is expected behavior, Android pulls existing bookmarks from sync chain.

This is correct if bookmark sync is enabled on b-c but in this scenario its disabled before adding the mobile device to the chain so ideally there shouldn't be any bookmarks available to be pulled in by Android

>The scenario you should check is after disable bookmark sync, "NEW ADDED" bookmarks on brave-core shouldn't appear in Android.

This is correct but what happens here is the existing bookmarks are getting sync'd to Android when bookmark sync is turned off on b-c which is still a bug.

**Comment by darkdh** [comment]
if you don't want Android pulling bookmarks, disable the bookmark sync on Android.
As long as you don't delete sync chain, bookmarks will always be there.
bookmark sync switch only control brave-core send/pull new bookmarks, it will not affect other devices.

**Comment by darkdh** [comment]
and your title is not even accurate. Some bookmarks has already been sent when you enable sync.
You should revise your steps to 

1. Enable sync on b-c
2. Disable bookmark sync on b-c
3. Import 5k bookmarks file on b-c

**Comment by srirambv** [comment]
I dont think the steps needs to be revised. The one you are mentioning is a different scenario. The scenario here is I already have bookmarks on my profile and then enable sync and turn off bookmark sync which is correctly mentioned in the original str.

**Comment by srirambv** [comment]
>if you don't want Android pulling bookmarks, disable the bookmark sync on Android. 

Android doesn't allow you turn off only that setting similar to b-c. Its either on or off so this is invalid

**Comment by srirambv** [comment]
Ok. I'll add a feature request for Android to have the switch to avoid this scenario

**Comment by AlexeyBarabash** [comment]
This issue has STR which are not actual since new design. At the current time it is impossible to add only one device in the chain. Also with PR https://github.com/brave/brave-core/pull/2016 brave-core does not sends data to sync cloud until sync chain contains 2 or more devices.
