### ISSUE TITLE
enabling/disabling `Brave News` via setting puts it into a weird state until users taps on `Show Brave News` via NTP

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#21493]
## Description 

When a user enables `Brave News` via `Hamburger` -> `Brave News` after https://github.com/brave/brave-core/pull/12489 has been merged and then goes back to the `Brave News` settings, they'll notice that `Show Brave News` toggle is disabled even though the on-boarding card was already enabled. Enabling the setting once again creates a weird state where it looks like Brave News is completely enabled but the on-boarding card still appears via NTP. Sometimes the fee will load and sometimes you'll get the on-boarding card. To fix this situation/state, a user needs to tap on `Show Brave News` via the on-boarding card.

My guess is that when you disable/enable multiple times, Brave News thinks it's still enabled but the user only enabled the card and never specifically toggled `Show Brave News`. But this part is missing from the `Settings` page if you enable/disable.

![image](https://user-images.githubusercontent.com/2602313/156908692-ca33a315-fc50-4b1e-961d-268552491df3.png)

## Steps to reproduce 

   1. download/install `1.38.25 Chromium: 99.0.4884.51`
   2. tap on `Hamburger Menu` -> `Brave News` and toggle `Enable Brave News` and close the settings page via `x`
   3. should see the Brave news on-boarding card enabled/visible via NTP
   4. tap on `Hamburger Menu` -> `Brave News` and notice that the toggle is disabled
   5. enable the toggle once again and you'll notice that this time, it's missing the `Show Brave News` isn't being displayed
   6. close the `Brave News` setting page via `x` and you'll notice the news feed is visible
   7. open a NTP again and you'll notice that the on-boarding card is being displayed rather than the news feed

Pressing the `X` on the on-boarding card or tapping on `Show Brave News` will remove the user from the weird state.

## Actual result 

Example of the issue --> https://youtu.be/l2lls1mU4II

## Expected result

Users shouldn't be getting into a state where the feed is supposed to be appearing but they're still getting the on-boarding card.

## Issue reproduces how often 

100% reproducible using the STR/Cases mentioned above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

Once  https://github.com/brave/brave-core/pull/12489 is uplifted into BETA/Release, all channels will have the above issue.

## Device details

   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 12`
   
## Brave version

```
1.38.25 Chromium: 99.0.4884.51
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @alexsafe @bsclifton @srirambv @Uni-verse @anthonypkeane

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.36.115 x64 build
- Verified steps from issue description
- Verified enabling/disabling Brave News via settings doesn't put it into a weird state like before
- Verified enabling and not opting-in to news and closing the active NTP doesn't cause any issue
- Logged [#21659](https://github.com/brave/brave-browser/issues/21659)
