### ISSUE TITLE
Beach-balling on macOS when adding large RSS feed sources

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21490]
## Description 

Beach-balling on macOS when adding large RSS feed sources

## Steps to Reproduce

   1. install `1.38.23`
   2. launch Brave
   3. open a new-tab page
   4. click on `Customize` at the bottom right
   5. click on `Brave News`
   6. enable Brave News
   7. under Your Sources, enter `https://planet.mozilla.org/rss10.xml`
   8. click `Add source`
   9. wait / "beach ball" a bit
   10. click to (try to) focus the `Feed Url` textfield
   11. wait / "beach ball" a bit
   12. enter `https://planet.mozilla.org/rss20.xml`
   13. click `Add source`

## Actual result:

`NOTE:` Sadly, the beach balls don't show up on this screencast.  So, instead, you can picture them appearing in the pauses between the last `Add source` success and me clicking on the textfield to focus it (and trying to paste the URL until I'm able).

![brave-news-beachball](https://user-images.githubusercontent.com/387249/156881293-285813d8-e346-4294-b797-8f918aded52e.gif)

## Expected result:

No "beach balls", or at least minimal.

## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.38.23 Chromium: 99.0.4844.51 (Official Build) nightly (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.3 (Build 21E5227a)

cc @petemill @mattmcalister @kjozwiak @srirambv

**Comment by fallaciousreasoning** [comment]
Duplicates #23909

**Comment by stephendonner** [comment]
> Duplicates #23909 (which is fixed)

Thanks for fixing!
