### ISSUE TITLE
New tab dashboard shows wrong time

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#215]
## Description 
New tab dashboard shows wrong time

## Steps to Reproduce

   1. Build from source
   2. Open a new tab 
   3. Dashboard shows wrong time (for me it was showing one hour behind)

 ## Actual result:
New tab dashboard shows wrong time

## Expected result:
Should show proper time

## Reproduces how often: 

Easy

**Comment by bbondy** [comment]
@srirambv could you reverify?
@cezaraugusto landed some new code from this using the same code as on browser-laptop.

**Comment by srirambv** [comment]
This looks fixed on  aa02380
