### ISSUE TITLE
How can I re-enable the auto goto web archive function?

### ISSUE THREAD

**Issue by wuyudi** [brave/brave-browser#21503]
## Description 

I click the `don't show again` button on the banner. Now I can't figure out where to turn it on again.

I have checked brave://flags, brave://settings, but found nothing.

## Steps to Reproduce

   1. go to a 404 page, like this https://www.whitehouse.gov/energy/climate-change
   2. click `don't show again`

## Actual result:

I want to show the banner again.

## Expected result:

 The banner shows again.

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Brave | 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Linux
JavaScript | V8 9.9.115.8
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end
Executable Path | /usr/lib/brave-bin/brave
Profile Path | /home/w/.config/BraveSoftware/Brave-Browser/Default
Variations | AdRewardsStudy:NextPaymentDayAdServingStudy:MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=8/MaximumInlineContentAdsPerDay=40AdvertiserSplitTestStudy:GroupABraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5BraveDebounceStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledExtendedVariationsSafeMode4:Default4ForceDisableBlinkFeatures:EnabledNativeCosmeticFilteringStudy:EnabledNavigationThreadingOptimizationsCompat:DisabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Disabled

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel?  yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? maybe.
- Does the issue resolve itself when disabling Brave Rewards? maybe.
- Is the issue reproducible on the latest version of Chrome? no, chrome doesn't have this function.

**Comment by asaneh** [comment]
#7756 #21476 #21476 #20971 #21417

**Comment by rebron** [comment]
@wuyudi You can enable the 404 banner prompt here brave://settings/braveHelpTips

**Comment by wuyudi** [comment]
just for others:
![image](https://user-images.githubusercontent.com/30024051/157082606-dbcc6643-522e-4679-8935-9cb7b81b8648.png)

I searched for `archive`, so I missed it.
