### ISSUE TITLE
Add News custom RSS P3A questions

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#21519]
## Description 

Add two new News P3A questions, for custom RSS feeds:

How many external feeds did you add last week?
`Brave.Today.WeeklyAddedDirectFeedsCount`

0) None
1) 1
2) 2
3) 3
4) 4
5) 5
6) 6 to 10
7) More than 10

How many external feeds do you have in total?
`Brave.Today.DirectFeedsTotal`

0) None
1) 1
2) 2
3) 3
4) 4
5) 5
6) 6 to 10
7) More than 10

## Miscellaneous Information:

Will raise PR soon.

**Comment by DJAndries** [comment]
cc @mattmcalister

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```
