### ISSUE TITLE
Switch blinded token requests to use new mywallet endpoint

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#21516]
## Description 

In order to better specify the privacy properties of the various ads endpoints, we want to change the hostnames to explicitly reflect the specific use according to our privacy policy:

The following endpoints should be reconfigured to go to mywallet.ads.brave.com, with the same path as current

- /v1/getstate
- /v2/confirmation/token/{paymentId}
- /v2/confirmation/payment/{paymentId}

All other endpoints on ads-serve.brave.com should instead go to anonymous.ads.brave.com

---------------------------------

**Anonymous (`anonymous.ads.*`):**
`GET /v1/issuers/`
`POST /v2/confirmation/{confirmation_id}/{credential}`
`GET /v2/confirmation/{confirmation_id}/paymentToken`

**Non anonymous (`mywallet.ads.*`):**

`PUT /v2/confirmation/payment/{payment_id}`
`GET /v2/confirmation/token/{payment_id}?nonce={nonce}`
`POST /v2/confirmation/token/{payment_id}`
`GET /v{n}/catalog` falls back to `ads-static` for production environment
`GET /v1/getstate` falls back to `ads-static` for production environment

**Comment by ShivanKaul** [comment]
@jsecretan can we make sure that the new endpoints are cert-pinned? @diracdeltas

**Comment by diracdeltas** [comment]
see here for where ads-serve is currently pinned: https://github.com/brave/brave-core/blob/c215ec61bd7632a1235be014606361d4e2b32fac/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc#L460

**Comment by tmancey** [comment]
@jsecretan `GET /v{n}/catalog` and `GET /v1/getstate` will fall back to `ads-static` for production environment, is this still required?

**Comment by evq** [comment]
@jsecretan I believe we discussed moving `GET /v1/getstate` to a new `geo.ads.brave.com`, were you also thinking we'd create a `static.ads.brave.com` for `GET /v{n}/catalog` for consistency? I assume all can point to the existing cloudfront distribution

**Comment by tmancey** [comment]
@evq is the catalog not geo based? Ok it is not by country/region but it is by country

**Comment by jsecretan** [comment]
Sounds good to me, sorry for being slow on this, here is the new issue https://github.com/brave/devops/issues/7274

**Comment by btlechowski** [comment]
Added `QA/Blocked` till problems with staging are resolved

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.100 Chromium: 101.0.4951.61 (Official Build) beta (64-bit)
-- | --
Revision | 3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS | Ubuntu 18.04 LTS

### Staging
#### geo - GET geo.ads.bravesoftware.com

<details>

![image](https://user-images.githubusercontent.com/34715963/168051496-7faf05de-89ab-4845-b7df-63a7d29c9d0e.png)



</details>

#### catalog - GET static.ads.bravesoftware.com

<details>

![image](https://user-images.githubusercontent.com/34715963/168051563-80ed71a4-fb4c-4c48-ad8d-29efa28bb4ad.png)


</details>

#### issuers - GET static.ads.bravesoftware.com

<details>

![image](https://user-images.githubusercontent.com/34715963/168051628-3e81433c-51f9-41fc-8e53-152548ff9454.png)


</details>

#### unblinded tokens - POST mywallet.ads.bravesoftware.com

<details>

![image](https://user-images.githubusercontent.com/34715963/168051727-d399277e-59ab-4d0f-9b8c-d4c5d80413b9.png)

</details>

#### unblinded tokens - GET mywallet.ads.bravesoftware.com

<details>

![image](https://user-images.githubusercontent.com/34715963/168051807-ff79f24f-fd59-4d2b-925a-36030194f09b.png)


</details>

#### redeem unblinded tokens - PUT mywallet.ads.bravesoftware.com

<details>

![image](https://user-images.githubusercontent.com/34715963/168053933-4de4e7fa-b34c-4a6f-89a4-9030b982eca8.png)

</details>

#### confirmation - POST anonymous.ads.bravesoftware.com

<details>

![image](https://user-images.githubusercontent.com/34715963/168052480-bf2ddc57-983d-4ec8-afd0-d25c061a7b57.png)


</details>

#### confirmation - paymentToken - GET anonymous.ads.bravesoftware.com

<details>

![image](https://user-images.githubusercontent.com/34715963/168052525-70d87665-12f6-41ff-87b6-dcac2b507343.png)


</details>
