### ISSUE TITLE
Branding issue: Google Lens shows as Brave Lens

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21512]
## Description 
See https://github.com/brave/brave-browser/issues/21442 for full information

In the menu, `Search image with Brave Lens` can show up.

![image](https://user-images.githubusercontent.com/4733304/156670108-098a487f-b43e-480d-a25a-e0d7eed2b44d.png)

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.36.115 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the test plan from the description

**Comment by LaurenWags** [comment]
Changed to `release-notes/exclude` per discussion with @kjozwiak @rebron
