### ISSUE TITLE
scroll on NTP widget doesn't work well

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#21511]
## Description 
Up/down scrolling on the NTP widget to access top sites/stats doesn't work well on smaller screen.

## Steps to reproduce 

   1. Install 1.35.103.
   2. Confirm able to scroll on widget (up/down) to access top sites and stats without issue.
   3. Upgrade to 1.36.111 or install fresh
   4. Notice scrolling on widget isn't as easy. It seems better than it was with Brave News enabled by default, but it's still not great.

Note - on 1.35.x NTP photographer credit is visible in lower left corner of NTP. On 1.36.x this credit is only shown with slight scroll of NTP. 

## Actual result 

difficult to scroll on widget

## Expected result

easy to scroll on widget

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  1.35.x no, 1.36.x yes
- Can you reproduce this issue with the current Play Store Beta version? yes (see https://github.com/brave/brave-browser/issues/21166)
- Can you reproduce this issue with the current Play Store Nightly version? yes (see https://github.com/brave/brave-browser/issues/21166)

## Device details
   - Install type (ARM, x86): x86
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 6
   
## Brave version
1.36.111

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @srirambv @anthonypkeane @acatarineu

**Comment by bsclifton** [comment]
Should be closed out when we address https://github.com/brave/brave-browser/issues/21166 - which I think we'll address by implementing https://github.com/brave/brave-browser/issues/13714

**Comment by bsclifton** [comment]
Closing as `wontfix` - no longer relevant after https://github.com/brave/brave-core/pull/12743
