### ISSUE TITLE
Swaps: Too many decimal places error, too easy to get

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21527]
When selecting 25% ETH balance then selecting USDC, got this error immediately after estimator returned too many decimal places.

![Screen Shot 2022-03-08 at 8 11 18 AM](https://user-images.githubusercontent.com/318119/157254923-4c2d8cb6-7fb3-4034-8d6b-b6878995e510.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">  1.38.107 Chromium: 101.0.4951.41 (Official Build)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12567>brave/brave-core#12567</a></li>
         <li>Verified switching to USDC after setting a preset value doesn't throw the error</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165293945-5aa388c3-7c64-4dfb-b54f-a2a01eb1c606.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165292102-baff845d-4a8f-49eb-9fc5-a17ef4ff75b2.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165291784-b11f9d55-f9c6-4154-85a1-012b54affaf6.mov>
      </td>
   </tr>
</table>
