### ISSUE TITLE
Custom amounts for Brave Rewards not showing in drop down

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#2152]
## Test plan
See https://github.com/brave/brave-core/pull/910

## Description 
While implementing https://github.com/brave/brave-core/pull/736/ I noticed that custom amounts (ex: values not in the drop-down) are not being added to the drop-down after being set via `RewardsServiceImpl::SetContributionAmount`.

## Steps to Reproduce / test plan for peer review

   1. Build from master
   2. In the code somewhere, call `RewardsServiceImpl::SetContributionAmount` and pass a value like 13
   3. Visit `brave://rewards` and notice that the amount is not shown in the drop down

## Actual result:
For me it defaulted to 20?

## Expected result:
It should show 13

## Reproduces how often: 

100%

## Brave version (brave://version info)
master (https://github.com/brave/brave-core/commit/d76c7244f392a6692d5e46ce4bd5f1fee426e8ab)

### Reproducible on current release:
n/a, since it involves writing code (discovered while importing from Muon)

**Comment by NejcZdovc** [comment]
@kjozwiak @rebron @srirambv set this to 0.57 so it will be fixed for muon import. Please adjust it if you think we should not land it there

**Comment by NejcZdovc** [comment]
adde QA/No as we don't have good steps for QA to use

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Windows

- Verified the STR mention in the https://github.com/brave/brave-core/pull/910
