### ISSUE TITLE
drag and drop within bookmark folder on bookmarks bar does not work in certain cases

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#21529]
## Description 

Some users are reporting problems with drag and drop of bookmarks on the bookmarks bar. 

See https://community.brave.com/t/impossible-to-reorganize-bookmarks-manually/349427/8 as an example.

I have reproduced this in a few cases below, mainly centered around ordering of bookmarks within a folder from the bookmarks bar. Note, re-ordering folder contents from brave://bookmarks appears to be working as expected.

Reproduces with Chrome 99.0.4844.51.

## Steps to Reproduce

Pre-req: Set up some bookmarks + a folder with some contents (or you can import from [bookmarks_3_8_22 copy.txt](https://github.com/brave/brave-browser/files/8206857/bookmarks_3_8_22.copy.txt) on a clean profile - just rename to .html before importing). 

Once you have the above, try the following scenarios

Scenario 1:
1. Expand the folder on the bookmarks bar
2. Select a bookmark and attempt to move it to another position in the same folder (ex. move D between A and B if using bookmarks from above)
3. Bookmark does not move to new position in folder -- white line appears where you want to drop it, but bookmark does not move.

Scenario 2: 
1. Visit a site not bookmarked (ex. rebron.org)
2. Highlight the full URL
3. Drag the URL onto the folder and wait for the folder to expand 
4. Attempt to drop the URL in a specific place (ex. between B and C)
5. Bookmark is not placed into folder, folder remains expanded in view until you click on it to close the folder 
Note - if you just drop the URL onto the folder without waiting for the folder to expand, the URL is added to your folder as a bookmark. It appears as though specifically trying to place the URL in a certain position cannot be achieved this way.

<img width="1197" alt="Screen Shot 2022-03-08 at 9 16 08 AM" src="https://user-images.githubusercontent.com/28145373/157255753-205cfded-18da-4d0f-8493-78dd09b203e2.png">

Scenario 3:
1. Select a bookmark from the bookmarks bar
2. Drag the bookmark onto the folder and wait for the folder to expand 
3. Attempt to drop the Bookmark in a specific place (ex. between C and D)
4. Bookmark is not placed into folder, folder remains expanded in view until you click on it to close the folder 
Note - if you just drop the bookmark onto the folder without waiting for the folder to expand, the bookmark is added to your folder. It appears as though specifically trying to place the bookmark in a certain position cannot be achieved this way.

<img width="1193" alt="Screen Shot 2022-03-08 at 9 21 01 AM" src="https://user-images.githubusercontent.com/28145373/157256503-529d6de4-e73e-43e3-b2d6-66b48b2fe339.png">

## Actual result:

Unable to order bookmarks in the cases above

## Expected result:
Able to order bookmarks

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.36.111 Chromium: 99.0.4844.51 (Official Build) (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes 1.37.x
- Can you reproduce this issue with the nightly channel? yes 1.38.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? yes - 99.0.4844.51

## Miscellaneous Information:

cc @Brave-Matt @stephendonner

**Comment by LaurenWags** [comment]
from @mkarolin - https://bugs.chromium.org/p/chromium/issues/detail?id=1302138

**Comment by Brave-Matt** [comment]
Multiple user reports:
https://community.brave.com/t/cannot-save-bookmark-by-dragging-url-to-folder/349194/3
https://community.brave.com/t/impossible-to-reorganize-bookmarks-manually/349427/13

**Comment by zdenys** [comment]
The same is happening in Chrome of which there are various reports too:
- https://support.google.com/chrome/thread/153383864/dragging-url-to-folder-and-dropping-in-specific-order-doesn-t-work-anymore?hl=en
- https://www.reddit.com/r/chrome/comments/t87ow8/cant_drag_and_drop_anything_in_bookmarks/

**Comment by mvargasmoran** [comment]
Hello, is there any solution for this?
The issue has some features: 

- While dragging, the bookmark folders, not just dragging to plain (global) bookmarks bar, the folder opens, let's you choose subfolders,  
- On mousepress release, the folder remains open, the bookmark is not added, and the bookmarks folder navigation stays on top even clicking outside
- To close the opened folders, one needs to go and click over the top folder.

is there a switch, experimental feature or plugin to fix this?

**Comment by starvational** [comment]
> The same is happening in Chrome of which there are various reports too:
> 
> * https://support.google.com/chrome/thread/153383864/dragging-url-to-folder-and-dropping-in-specific-order-doesn-t-work-anymore?hl=en
> * https://www.reddit.com/r/chrome/comments/t87ow8/cant_drag_and_drop_anything_in_bookmarks/

Looks like it's been fixed in Chrome and deployed to their stable channel:
https://bugs.chromium.org/p/chromium/issues/detail?id=1302138

Wondering when Brave will fix this.  I'm seeing this issue (Mac OSX) and I'm on the latest version of Brave.

**Comment by mvargasmoran** [comment]
@Metis77 that didn't worked for me... maybe it's because I have subfolders.

**Comment by Metis77** [comment]
@mvargasmoran true, that worked only for the root folders.

**Comment by mvargasmoran** [comment]
This was Poggers 👍

**Comment by stephendonner** [comment]
@LaurenWags I didn't test extensively but LGTM (drop targets actually work where indicated, etc.) 👍 



Brave | 1.36.117 Chromium: 99.0.4844.74 (Official Build) (x86_64)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | macOS Version 11.6.3 (Build 20G415)
