### ISSUE TITLE
Add remove observer function in tx_service

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#21525]
Add "removeObserver" method in TxService for clean up and avoiding unexpected callbacks or unexpected leaks etc.

cc: @yrliou

**Comment by yrliou** [comment]
@Pavneet-Sing Tx service observers are managed by `mojo::RemoteSet`, `mojo::RemoteSet<mojom::TxServiceObserver> observers_` in tx_service.h, we don't need to have RemoveObserver method.
`mojom::TxService` also only has `AddObserver` defined.
See https://source.chromium.org/chromium/chromium/src/+/main:mojo/public/cpp/bindings/remote_set.h;l=34-36?q=mojo::RemoteSet&ss=chromium for more details.

**Comment by Pavneet-Sing** [comment]
@yrliou thanks for the details. I may soon use `mojom::TxService`'s  observer for some short lived use-and-throw objects so just wanted to make sure that It might not end-up creating memory leaks or something.
