### ISSUE TITLE
Negative timestamp in Brave Ads log when successfully redeeming an unblinded token

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#21533]
<img width="1315" alt="Screen Shot 2022-03-08 at 10 25 09 AM" src="https://user-images.githubusercontent.com/1188719/157269130-dccc086f-4d1a-4d3f-8010-715770456c9b.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.100 Chromium: 101.0.4951.61 (Official Build) beta (64-bit)
-- | --
Revision | 3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS | Ubuntu 18.04 LTS

No negative timestamp when redeeming an unblinded token
