### ISSUE TITLE
US country code incorrectly stripped from P3A reports

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#21534]
## Description 

In #21460 I inadvertently stripped the US country code from P3A report metadata. This is an important region with many users, so stripping it harms our understanding of browser use without improving user privacy.

`US` should be added to the list of generally-accepted country codes for reporting.

## Steps to Reproduce

   1. Install with US locale
   2. Observe P3A report metadata
   3. 

## Actual result:

Country code is `other`

## Expected result:
Country code should be `US`.

## Reproduces how often: 

Always

## Desktop Brave version:

1.38.28

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rillian** [comment]
Resolved in brave/brave-core#12512

**Comment by GeetaSarvadnya** [comment]
@rillian I can see country_code `IN` even though my system locale is set to `US`. Also I have even tried connecting wireguad VPN but still I see country code `IN` - Verified the issue in the brave version `1.38.74`

**Comment by rillian** [comment]
@GeetaSarvadnya I don't think this is a specific regression; the issue being addressed here is reporting "other" instead of "US". Probably brave is using something other than the system locale to set the country code.

I'll need to investigate further to offer a test strategy.

**Comment by GeetaSarvadnya** [comment]
@rillian Thanks for the response, the `country-code` which is fetched in the Charles ("IN") is from the network I think, I might be wrong. The country code I see in brave://local-state is "US". 

![image](https://user-images.githubusercontent.com/38657976/161495158-ce45fae3-85ff-46fe-8f97-4650489994b8.png)

**Comment by rillian** [comment]
@GeetaSarvadnya, the country code sent with P3A message is [derived from the timezone](https://github.com/brave/brave-core/blob/v1.39.34/components/p3a/brave_p3a_service.cc#L391-L392) rather than the locale. So if you set the system timezone to `US/Eastern`, `America/New York`, or similar you should see the expected `US` country code in P3A reports, independent of the configured language or other locale settings.

**Comment by GeetaSarvadnya** [comment]
@rillian Thanks for the clarification.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```

**Comment by Uni-verse** [comment]
Verified using `1.38.104, Chromium 101.0.4951.41` on `Samsung Galaxy S21` running `Android 12`

- Confirmed `country_code: us` is being appended to the request
- Confirmed that "country_code" is "US" in JSON message

1 | 2
-|-
![Screen Shot 2022-04-21 at 11 39 05 AM](https://user-images.githubusercontent.com/17885425/164532220-1b665759-251f-44a5-9607-8e72e9100b34.png) | ![Screen Shot 2022-04-21 at 11 43 59 AM](https://user-images.githubusercontent.com/17885425/164532235-5d1d0d3d-3c7b-4c18-8a54-9c3c72e72c04.png)

**Comment by Uni-verse** [comment]
Verified using `1.38.104, Chromium 101.0.4951.41` on `Samsung Galaxy S21` running `Android 12`

- Confirmed country_code: us is being appended to the request
- Confirmed that "country_code" is "US" in JSON message

1 | 2
-|-
![screenshot-1650576216896](https://user-images.githubusercontent.com/17885425/164554763-9f3661a4-e1e9-4350-85ba-a06f1fcba13e.png) | ![Screen Shot 2022-04-21 at 2 22 00 PM](https://user-images.githubusercontent.com/17885425/164554793-c22e77ad-9efc-49e7-8a20-90534d1eb9c4.png)
