### ISSUE TITLE
Increase spacing between account assets and transactions header

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21532]
+20px

![Screen Shot 2022-03-08 at 8 46 15 AM](https://user-images.githubusercontent.com/318119/157261616-3e87fa7d-241a-465e-87dd-0aa94a285fa5.png)

**Comment by Uni-verse** [comment]
Verified on

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.1 (Build 21C52)

- [x] Increase spacing between account assets and transactions header

![Screen Shot 2022-04-12 at 11 26 57 AM](https://user-images.githubusercontent.com/17885425/163029431-906c8886-f349-422c-9dc3-7cab049a9867.png)
