### ISSUE TITLE
Brave Rewards settings page - match all components to design system

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21540]
## Description

We should replace all with Poppins. Also, we should match all design requirements laid out in Figma and implement design system components.

## Solution

Make all Poppins as pictured below.

<img src="https://user-images.githubusercontent.com/11497541/157323220-d5e53a87-d162-405f-a359-f0cd159dae06.png" height=400px>

## Current for reference

Current, as of 1.36.x: 

<img src="https://user-images.githubusercontent.com/11497541/157323317-38acdc45-4fdd-4a9e-94e2-eed5696fe187.png" height=400px>

**Comment by Alzamer** [comment]
I'd like to work on it, can somebody assign me?

**Comment by petemill** [comment]
This has been split up - the change to Poppins from Muli is addressed by https://github.com/brave/brave-browser/issues/25527
