### ISSUE TITLE
Add Shields domain-specific ad/fingerprint block setting questions

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#21546]
## Description 
Adding four Shields P3A questions:

On how many domains has the user set the adblock setting to be lower (block less) than the default?
On how many domains has the user set the adblock setting to be higher (block more) than the default?
On how many domains has the user set the FP setting to be lower (block less) than the default?
On how many domains has the user set the FP setting to be higher (block more) than the default?

Bucket values:

0) 0
1) 1-5
2) 6-10
3) 11-20
4) 21-30
5) 31+

## Miscellaneous Information:

Will raise PR soon.

**Comment by DJAndries** [comment]
cc @pes10k

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.39.84 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

**Comment by Uni-verse** [comment]
Verification in Progress for OS/Android
