### ISSUE TITLE
Blank page on  https://portal.cms.gov/portal/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#21548]
## Description 
Opening `https://portal.cms.gov/portal/` and no login shows.

## Steps to Reproduce

   1. Open `https://portal.cms.gov/portal/`
   2. Shows no login in Brave
   3. 

## Actual result:
![cms gov-brave](https://user-images.githubusercontent.com/1659004/157348751-9d33adfa-3f5b-4067-bc3e-da801c49d5cd.png)

## Expected result:
(Show login)
![cms gov-chrome](https://user-images.githubusercontent.com/1659004/157348680-ec6414d2-b3b0-4c1b-ae35-3c819be7105a.png)

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Caused by brand checks: `navigator.userAgentData.brands`
<img width="446" alt="screen_shot_2022-03-08_at_17 50 54" src="https://user-images.githubusercontent.com/1659004/157348491-e236aacd-05da-433d-bae4-72bfa3b55097.png">

Was reported https://community.brave.com/t/webpage-wont-load-properly-under-windows-or-android-app/353750/2

**Comment by pilgrim-brave** [comment]
fix was reverted so reopening this issue
