### ISSUE TITLE
Broken Placeholder Icons for ERC721 tokens

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21549]
## Description 
Placeholder Icons are broken for `ERC721` tokens on the `Accounts` subview page
![Screen Shot 2022-03-08 at 6 19 45 PM](https://user-images.githubusercontent.com/40611140/157359134-6e05f6e3-2b2a-4568-88bc-59921f94ed77.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.38.104 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12538>brave/brave-core#12538</a></li>
         <li>Verified ERC721 tokens show placeholder icon correctly</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/164457684-9679a761-3989-4ed7-8a11-76d9dee9f847.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/164457274-ad57f367-4663-4b03-bafe-fe0f25c43297.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/164456735-60540c7b-18a9-4f9b-ad97-948f4d8f671a.png>
      </td>
   </tr>
</table>
