### ISSUE TITLE
Download fails on packetpub

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2154]
## Description 

From Community 

>With Brave Software (not on Chromium…), I can’t download my eBook on packtpub…
>
>![image](https://user-images.githubusercontent.com/17010094/48562909-2f9dc100-e8c1-11e8-8f7e-501727d7893a.png)

## Steps to Reproduce

   1. Visit https://www.packtpub.com/packt/offers/free-learning
   2. Try downloading 
   3. 

## Actual result:

Download fails
![image](https://user-images.githubusercontent.com/17010094/48562999-607df600-e8c1-11e8-9ef8-57bb13fa81a2.png)

## Expected result:
Should download

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  
No
- Is the issue reproducible on the latest version of Chrome? 
No, file downloads on Chrome correctly

**Comment by saurabh2804** [comment]
I would like to confirm that i am facing the same issue. I am on Version 0.58.18 of brave and Linux MInt 19.1.

**Comment by ryanbr** [comment]
Testing this @srirambv 

`https://www.packtpub.com/free-learning`  click on a free book, then select a chapter, seems to be working. Can you confirm?
