### ISSUE TITLE
Remove `microsoft-edge` protocol handler

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21553]
## Description 
Originally captured with https://github.com/brave/brave-browser/issues/13875 and https://github.com/brave/brave-browser/issues/17558, we had added a way to set the `microsoft-edge` handler
![image](https://user-images.githubusercontent.com/4733304/157398378-8c666815-c9c0-4d44-a7cb-9250a572849c.png)

This was patched by Microsoft in Windows 11 breaking the feature and it eventually this patch made its way to Windows 10 also. If you try to open a search after setting it, you're presented with Microsoft Edge only options
![image](https://user-images.githubusercontent.com/4733304/157398918-0b4149ae-6299-45a4-bc9d-ee2e980e7a73.png)

We can likely remove this code completely (added in https://github.com/brave/brave-core/pull/9778 and https://github.com/brave/brave-core/pull/10879)

**Comment by stephendonner** [comment]
+1000

**Comment by kjozwiak** [comment]
@bsclifton @rebron something we want to get uplifted into `1.37.x`?

**Comment by bsclifton** [comment]
@kjozwiak we definitely can- let me create one and share

**Comment by kjozwiak** [comment]
Will require `1.37.100` or higher for `1.37.x` verifications.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.37.106 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```

- Confirmed ms-edge protocol handling is removed from the brave://settings/system

1.36.119 | 1.37.106
-- | --
![image](https://user-images.githubusercontent.com/38657976/160345578-c29e8049-8606-48e7-8407-3dbd6e0650bd.png) | ![image](https://user-images.githubusercontent.com/38657976/160345987-f218a852-a4f6-4603-b70d-416c30579836.png)
