### ISSUE TITLE
Exclude ERC721 Tokens in Swap

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21550]
## Description 
We should exclude `ERC721` tokens in our `Swap` coin selection

![Screen Shot 2022-03-08 at 8 38 55 PM](https://user-images.githubusercontent.com/40611140/157368400-562f057c-2ac8-43da-a3e0-416a32e7fd0e.png)

cc: @onyb @josheleonard

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12976>brave/brave-core#12976</a></li>
         <li>Verified NFT's are not listed in Swap</li>
         <li>Verified NFT's are still being listed under Send tab</li>
         <li>Verified NFT's are not listed in Swap in panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/167355347-ed06cd6a-0ee3-4970-aeff-e9dbb71747b8.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/167355359-ec344641-9e03-4cac-af79-60c624a0bbd9.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/167355370-56381c0e-cbb8-4af4-ba71-829d4e142d62.mov>
      </td>
   </tr>
</table>
