### ISSUE TITLE
website issues: documents.adobe.com

### ISSUE THREAD

**Issue by Northshoot** [brave/brave-browser#2155]
## Description 

The website https://na1.documents.adobe.com/public/agreements/view/ wont load with shields up in brave.
If you guys need to test, I can send invite to sign a document :)

## Steps to Reproduce

   1.  Follow the link to sign/view/download document
   2. Only footer and header will load but not the document

## Actual result:

<img width="1674" alt="2018-11-15_09-17-06" src="https://user-images.githubusercontent.com/7857361/48569701-4c34fb80-e8b7-11e8-85b6-dec77edeb66f.png">

## Expected result:

Document overview, signing, download capabilities 
## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 0.57.4 Chromium: 71.0.3578.31 (Official Build) dev (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Mac OS X
JavaScript | V8 7.1.302.12
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.31 Safari/537.36
Command Line | /Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev -psn_0_45067 --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev
Profile Path | /Users/hai/Library/Application Support/BraveSoftware/Brave-Browser-Dev/Default

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

Disabling Brave Shield fixes the issue.

**Comment by rebron** [comment]
workaround, disabling shields should give you access to adobe.com and likely to sign document as well.

@rebron me to test signing a document in adobe.

**Comment by ryanbr** [comment]
Issue still exists because login cookie from `echosign.com` is being blocked.

**Comment by ryanbr** [comment]
Also implemented a site trackers fix: https://github.com/easylist/easylist/commit/afcf234038bd30a5d26e727d3556b5ff47af7eb4

**Comment by ryanbr** [comment]
@Northshoot  is this still an issue? Just tested by logging in to adobe and convert documents, and view a few docs.

**Comment by rebron** [comment]
Closing per last comment. @Northshoot We can reopen if you're still running into this issue.
