### ISSUE TITLE
Update Brave's Windows updater (Omaha)

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#21564]
## Description 

In https://github.com/brave/omaha/pull/45, some statistics collection is disabled in Brave's auto-updater on Windows. For this change to reach users, we need to release a new version of the auto-updater.

In my opinion, the following PRs in brave/omaha should be merged on the way to achieving the above:

 1. https://github.com/brave/omaha/pull/45 this is the meat of the implementation (little there is).
 2. https://github.com/brave/omaha/pull/46 this increments the version number of the updater so users can receive it via auto-updates.
 3. https://github.com/brave/omaha/pull/43 this is a non-functional build process change, which we might as well merge into our mainline at this point.
 4. https://github.com/brave/omaha/pull/47 speeds up the build process by using parallel compilation.

Once the above are merged, we need to update the `omaha` dependency in Brave's `DEPS` file. Then, we need to build the new updater (happens as part of Brave's normal build) and upload its binaries to the update server. @mihaiplesa did this in November last year and will know whether it is done automatically as parts of Brave's release builds, or whether it needs to be done manually.

**Comment by mherrmann** [comment]
@mihaiplesa I'm re-opening this because we had to rollback yesterday.

The reason for the rollback is that we saw an increasing number of CI builds fail with the following error:

    "C:\go/bin/go.exe" run C:\ws\src\brave\vendor\omaha\omaha/../common/certificate_tag/certificate_tag.go -set-superfluous-cert-tag=Gact2.0Omaha -padded-length=8206 -out scons-out\opt-win\obj\standalone\UNOFFICIAL_BraveBrowserStandaloneUntaggedNightlySetup_99_1_38_52.exe scons-out\opt-win\obj\standalone\authenticode_UNOFFICIAL_BraveBrowserStandaloneUntaggedNightlySetup_99_1_38_52.exe
    go: cannot find GOROOT directory: C:\go
    scons: *** [scons-out\opt-win\obj\standalone\UNOFFICIAL_BraveBrowserStandaloneUntaggedNightlySetup_99_1_38_52.exe] Error 2
    scons: building terminated because of errors.
    Error in hammer.bat:96.

**Comment by mherrmann** [comment]
Closing this issue in favor of #22060.

**Comment by LaurenWags** [comment]
@mherrmann is it ok to mark this one as `QA/No` as we will test this with https://github.com/brave/brave-browser/issues/22060 ?

**Comment by mherrmann** [comment]
@LaurenWags yes!
