### ISSUE TITLE
remove `sync this device` interface

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2156]
this is not needed per design spec

<img width="826" alt="screen shot 2018-11-14 at 9 00 50 pm" src="https://user-images.githubusercontent.com/4672033/48573698-31cd4300-e8f4-11e8-8322-93ca386ec329.png">

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

![screen shot 2018-11-29 at 11 21 39 am](https://user-images.githubusercontent.com/28145373/49235876-043eca00-f3c9-11e8-965e-d3c8817f865f.png)

**Comment by srirambv** [comment]
Removed QA pass label. Need to verify it against beta again

**Comment by btlechowski** [comment]
Verification passed on


Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7 x64

![image](https://user-images.githubusercontent.com/34715963/49819172-00ba2400-fd75-11e8-88ac-3ce2302c34a6.png)
