### ISSUE TITLE
Add asset balance on asset "From" in swaps, wallet

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21565]
![Screen Shot 2022-03-08 at 8 10 39 PM](https://user-images.githubusercontent.com/318119/157488546-e217bbb6-eadd-4dd8-8d4f-75daa9d29ab2.png)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/26632#issuecomment-1409052849
