### ISSUE TITLE
Add method in `KeyringService` to validate a users wallet password

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#21576]
## Description 

If you call `Unlock` with the wrong password currently the wallet locks, even if the wallet was already unlocked when you called it. We want to add a way to enable/disable biometric unlock without restoring your wallet via the settings screen, but biometric unlock requires saving the users password to the keychain and we don’t hold onto the users password once they unlock the wallet.

We need a method on `KeyringService` that allows a user to enter their password to validate it is correct regardless of if the users wallet is locked/unlocked.

Needed for https://github.com/brave/brave-ios/issues/4485

**Comment by yrliou** [comment]
cc @supermassive
