### ISSUE TITLE
Enabling Tor mode by default (under Properties) opens 2 windows

### ISSUE THREAD

**Issue by ShadowOne333** [brave/brave-browser#21579]
## Description 
Adding the `--tor` argument at the end of the "Target" box opens up two Brave Private Tor windows, instead of just one,
This behaviour is also mirrored if trying to add the --tor argument in Brave's pinned icon in the Taskbar.

## Steps to Reproduce

   1. Right click on the Brave browser's icon, either under Desktop or the pinned icon on Taskbar (Windows 10)
   2. Select "Properties"
   3. Add the `--tor` argument at the end of the path found in the Shortcut tab inside the target box. Ex: `"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --tor`
   4. Apply and save the changes
   5. Try opening up Brave with Private+Tor by double clicking on the Desktop icon, or clicking on the pinned icon on the Taskbar.
   6. Brave will open up 2 windows instead of only one. (Tor and Tor 2)

## Expected result:
Opening Brave after making the change to open Tor mode by default should open up only one window.

## Reproduces how often: 
Easily reproduced each time one tries to open Brave after making the changes, both by clicking on the Desktop icon and by clicking on the pinned icon in Taskbar.

## Brave version (brave://version info)
Brave | 1.36.111 Chromium: 99.0.4844.51 (Official Build) (64-bit)
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H1 (Build 19043.1586)

## Other Additional Information:
Using the --incognito argument instead of --tor opens up a single window, as expected.
It's only the --tor argument that causes the issue.

**Comment by 86x** [comment]
can confirm this happens with the current linux version, too. To add to the story, this behavior seems to be new since I am 100% sure that previously only one window was opened when using the --tor option. The --incognito option continues to work properly btw.

brave-browser --version output:
Brave Browser 99.1.36.111

**Comment by ShadowOne333** [comment]
I'd also like to ask if there's a way to automatically start Brave in either Incognito or Tor mode in Linux, as it doesn't have a way to modify the argument given to it when opening it from the Activities overview or as an icon in favorites/Applications list.

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
I can confirm this also happens in MacOS when opening from the terminal
` $ ./Brave\ Browser.app/Contents/MacOS/Brave\ Browser --tor`

MacOS 12.4 (21F79)
Brave Version: 1.39.122  Chromium: 102.0.5005.115 (Official Build)  (arm64)

**Comment by Dyras** [comment]
Thread on the Brave forum about this: https://community.brave.com/t/opening-tor-with-terminal-opens-2-tor-window/356755

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.81 Chromium: 109.0.5414.46 (Official Build) nightly (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 13.2 (a) (Build 22D7750270d)

### Steps:
1. installed `1.48.81`
2. launched Brave using `--tor` on the commandline

### Confirmed I only got one new `Private Window with Tor`

`1.48.81` | `1.46.44`
----------|---------
<img width="1197" alt="Screenshot 2022-12-22 at 11 00 11 PM" src="https://user-images.githubusercontent.com/387249/209288426-b531a75d-b7cb-47c6-883c-2ff525bc2f8f.png"> | <img width="1544" alt="Screenshot 2022-12-22 at 11 18 20 PM" src="https://user-images.githubusercontent.com/387249/209290670-076aad7f-26ab-4b54-ad15-a9c25b57ed3b.png">

**Comment by btlechowski** [comment]
`QA/Test-All-Platforms` as each platform handles windows differently.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
Steps:

installed 1.48.132
launched Brave using --tor on the commandline

#### Confirmed I only got one new Private Window with Tor

1.48.132|1.47.177
----|-----
<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/213577842-aa566b28-e83a-4e7e-b427-4b7ce6d7956b.png">|<img width="680" alt="image" src="https://user-images.githubusercontent.com/98358127/213578193-14a3f789-46e5-431a-8858-b5ce14399fb1.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Linux
```
Steps:

- installed `1.48.132`
- launched Brave using `--tor `on the commandline

#### Confirmed I only got one new `Private Window with Tor`

1.48.132|1.47.171
-------|--------
<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/214053387-7d3d0a9c-9913-4aa7-9d09-6cffcd8a74c6.png">|<img width="761" alt="image" src="https://user-images.githubusercontent.com/98358127/214054922-8187ff7a-013f-4f3d-a8c0-ca6a25870322.png">
