### ISSUE TITLE
Remove unnecessary scroll bar on shields v2 for details view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21570]
## Description 

Remove unnecessary scroll bar on shields v2 for details view

## Steps to Reproduce

   1. Enable Shields v2 flag
   2. Visit any site and open shields
   3. Expand to advance view and click on blocked items, shows unnecessary scrollbars

## Actual result:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/17010094/157500672-f763c41e-0962-4fbf-9f70-d34a069f7cd4.png">

## Expected result:
Only show scrollbar when there is an overflow from visible box

## Reproduces how often: 

Easy

## Brave version (brave://version info)

With flag enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @nullhook @aguscruiz

**Comment by MadhaviSeelam** [comment]
Brave | 1.38.71 Chromium: 100.0.4896.46 (Official Build) beta (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

Install 1.38.x
Launch `Brave`
Enable `brave://flags/#brave-shields-v2`
Click `Relaunch`

<Summary>Scenario 1: No scrollbar displayed if there is no overflow of blocked items</Summary>
<details>

Visited https://www.euronews.com/news/international
Open `Shields` and expand to `Advance Controls`
Click on the count (16) for Trackers and ads blocked 
Verified there is no scrollbar displayed that listed blocked items in the box

ex1|ex2
----|---
<img width="930" alt="shields v2 enabled" src="https://user-images.githubusercontent.com/98358127/160699760-6c4d08f2-03b0-4a71-9b13-84d8941cf132.png">|<img width="950" alt="No scrollbar" src="https://user-images.githubusercontent.com/98358127/160699892-2557b741-0c3b-42bf-8612-2f29fee885f6.png">
</details>

<Summary>Scenario 2:  Scrollbar displayed if there is overflow of blocked items </Summary>
<details>
Visited another site, youtube.com
Play a video
Opened `Shields` and expand to `Advance Controls`
Clicked on the count (40) for Trackers and ads blocked 
Clicked on (+) for one of the items to expand
Verified scrollbar displayed when there is an overflow from visible box

ex
---
<img width="930" alt="scrollbar-overflow" src="https://user-images.githubusercontent.com/98358127/160700035-a12a84a4-b6df-47d3-83dd-543496d0daa3.png">

</details>
