### ISSUE TITLE
Default wallet setting needs new tab when moving from "Brave Wallet" setting to "Brave Wallet (prefer extensions)"

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#21571]
There is a bug I noticed with the default wallet setting. If it is set to “Brave Wallet” then we don’t allow window.ethereum to be overwritten.
If you later change to “Brave Wallet (Prefer Extensions)” it requires a new tab for an extension to be able to overwrite it.

**Comment by kjozwiak** [comment]
Requires `1.37.94` or later for verification using `1.37.x`.

**Comment by Uni-verse** [comment]
Verification completed using 

```
Brave	1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64) 
Revision	5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS	macOS Version 12.1 (Build 21C52)
```
- Able to connect dapp with MM after setting Brave Wallet (prefer extension) as option. 

Test Plan - https://github.com/brave/brave-core/pull/12561#issue-1165396508

- Install MM
- Set Brave Wallet as default wallet
- Open dapp
- Set Brave Wallet(prefer extension) as default option
- Reload dapp tab and check that it works well with MM
