### ISSUE TITLE
Dismiss or close button is missing in grants notification in NTP widget

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21587]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/15146

Unable to dismiss the UGP grants notification from NTP widget as there is no x close button in 1.37.x but it exists in 1.36.x. If there is an Ad grant waiting to be claimed, the ad grants notification will not be shown on the NTP widget until UGP grants is claimed
## Steps to Reproduce

   1. Clean profile 1.37.x staging env
   2. Enable rewards
   3. Open an NTP 
   4. Dismiss or close button is missing in grants notification in NTP widget

## Actual result:

Dismiss or close button is missing in grants notification in NTP widget
![image](https://user-images.githubusercontent.com/38657976/157692714-64dc3f71-3b11-4724-bdf1-66238aac441f.png)

## Expected result:
Dismiss or close button should be present in the grants notification in NTP widget

1.36.x
![image](https://user-images.githubusercontent.com/38657976/157692848-a26796fb-fbe2-43c4-9539-9dfadebfa755.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.37.87 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @Miyayes @zenparsing @LaurenWags

**Comment by zenparsing** [comment]
One solution might be to prioritize Ad grants over UGP grants in this display.

**Comment by Miyayes** [comment]
Given that:

1. There is a workaround (you can get around this in other parts of the UI, such as Rewards settings page, and perhaps Rewards panel) 

2. It would be better to avoid more design resources on UI/UX handling of this and adding an `x`

We should just:

>One solution might be to prioritize Ad grants over UGP grants in this display.

Seems like a simple, clean solution.
