### ISSUE TITLE
Implement vBAT submission for userdrain when user is in `logged out` Rewards wallet state 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21588]
## Description

Currently, vBAT is only submitted to be userdrained if the user's Rewards wallet state is `verified`. 

## Solution

Make the browser also submit vBAT to be userdrained even if the user is in a `logged out` state.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
- Verified the test plan from the description https://github.com/brave/brave-browser/issues/21588#issue-1165409190

<details>
<summary>Case 1: Uphold_Verify that browser submits the vBAT to the custodian wallets when the user is in logged out state</summary>

</details>

<details>
<summary>Case 2: Gemini_Verify that the browser submits the vBAT to the custodian wallets when the user is in logged out state</summary>

</details>

<details>
<summary>Case 3: bitFlyer_Verify that browser submits the vBAT to the custodian wallets when the user is in logged out state</summary>

</details>

**Comment by aman-m1** [comment]
@Miyayes Will this work for a user who was verified before but got unverified after Rewards wallet verification with Uphold and Gemini got disabled but Uphold and Gemini still offer their services, say, in India? Meaning, Ad rewards would continue to be deposited in their custodial accounts?

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarmx64.apk_1.40.99`
