### ISSUE TITLE
`Shields v2`: No text/tooltip on hovering on the Shields icon

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#21581]
## Description 

Hovering on the Shields icon doesn't show any text.

## Steps to Reproduce

   1. Install `Brave Nightly`.
   2. Enable `brave://flags/#brave-shields-v2` `->` `Relaunch`.
   3. Open a random website, for example `brave.com`.
   4. Hover on the Shields icon.

## Actual result:

![brave_8Ai4iFBSNX](https://user-images.githubusercontent.com/20608253/157601052-c6b08eb4-67e2-4374-914d-8f50118f3126.gif)

## Expected result:
There should be a text on hover.

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.32 Chromium: 99.0.4844.51 (Official Build) nightly (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

**Comment by Tonev** [comment]
@nullhook 

Does https://github.com/brave/brave-core/pull/12523 resolve this issue? 

Particularly the following: 

> Added tooltip on the new shields icon

**Comment by nullhook** [comment]
Yes, resolves: https://github.com/brave/brave-browser/issues/17369

**Comment by Tonev** [comment]
Okay, thank you! You can add this issue as a keyword in your pull request so merging will automatically close it, too, if you like :+1:

**Comment by MadhaviSeelam** [comment]
Verified `Passed` using

Brave | 1.38.74 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 11 Version 21H2 (Build 22000.556)

- Install 1.38.x
- Launched Brave
- Enabled `brave://flags/#brave-shields-v2`
- Enabled `brave://flags/#brave-shields-v1`
- Clicked `Relaunch` 
- Both Shields displayed 
- Visited Brave.com
- Hovered over v1 Shields icon and text displayed as `Brave shields Want access to this site` as expected
- Hovered over v2 Shields and tooltip text displayed as `Brave Shields` 
- Disabled `brave://flags/#brave-shields-v1`
- v2 Shields icon displayed
- Visited Washingtonpost.com
- Hovered over v2 Shields icon and text displayed as `Brave Shields 19 Trackers, ads and more blocked` 

ex1|ex2|ex3
---|---|---
<img width="950" alt="enabled both v1 and V2" src="https://user-images.githubusercontent.com/98358127/160914160-3c46e81e-cfa2-4583-8a4e-44d208c476a9.png">|<img width="950" alt="shields v1v2" src="https://user-images.githubusercontent.com/98358127/160913864-c5b67cb2-9f49-4d71-8e8c-44b3e0d35884.png">|<img width="950" alt="shields v1v2-2" src="https://user-images.githubusercontent.com/98358127/160913806-d7b75ed0-47e5-42f3-910b-8aab5c39251f.png">
