### ISSUE TITLE
Swipe back not working on some web site

### ISSUE THREAD

**Issue by kocoai** [brave/brave-browser#21585]
## Description 

Swipe back produce a horizontal scroll instead of Back action on some web page

## Steps to Reproduce

   1. Go to https://www.egaliteetreconciliation.fr/-Revue-de-presse-.html
   2. Click on an article in the list
   3. Try to swipe back

## Actual result:

A scroll horizontal to the right occur

## Expected result:
A back action

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.36.111 Chromium: 99.0.4844.51 (Official Build) (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)
JavaScript | V8 9.9.115.8
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- **Yes**
- Can you reproduce this issue with the beta channel? 
- **Do not try**
- Can you reproduce this issue with the nightly channel? 
- **Do not try**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- **No**
- Does the issue resolve itself when disabling Brave Rewards? 
- **No**
- Is the issue reproducible on the latest version of Chrome? 
- **Do not try**

**Comment by rebron** [comment]
@kocoai I'm not able to reproduce this. I was thinking resizing the window does it but doesn't look like it. Do you have an extension that might be conflicting. On swipe for me, it's going back (or forward depending on direction).

**Comment by kocoai** [comment]
Hi @rebron, I just update brave today

Brave | 1.36.112 Chromium: 99.0.4844.51 (Official Build) (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)
JavaScript | V8 9.9.115.8
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

I can not reproduce the bug either, It seem fixed.
