### ISSUE TITLE
`Shields v2`: Some texts need a change

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#21583]
## Description 

Just a typo and inconsistency.

## Steps to Reproduce

   1. Install `Brave Nightly`.
   2. Enable `brave://flags/#brave-shields-v2` `->` `Relaunch`.
   3. Open a random website, for example `brave.com`.
   4. Open the Shields panel via the Shields icon.
   5. Click on `Advanced Controls`.

## Actual result:

![muOaXS6aXe](https://user-images.githubusercontent.com/20608253/157603087-a994e8bf-1298-41d5-992d-689583c5824f.png)

## Expected result:
1. `Note: this may reduce Brave privacy protections.` `->` `Note: this may reduce Brave's privacy protections.`
2. `Filter Lists` and `Global defaults` `->` (`Filter lists` and `Global defaults`) or (`Filter Lists` and `Global Defaults`) so there is consistency.

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.32 Chromium: 99.0.4844.51 (Official Build) nightly (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

**Comment by Tonev** [comment]
In addition to this issue, I found out that `Learn more`, `Filter Lists`, and `Global defaults` options don't do anything. Please, let me know if you would like me to open another ticket for that, or is there one already? Thanks.

@stephendonner @nullhook

**Comment by stephendonner** [comment]
> In addition to this issue, I found out that `Learn more`, `Filter Lists`, and `Global defaults` options don't do anything. Please, let me know if you would like me to open another ticket for that, or is there one already? Thanks.
> 
> @stephendonner @nullhook @kjozwiak

👋  I think that's expected for now given it's still behind a feature flag; that said, perhaps @nullhook is ready to hit this heavily with bugs (I think so, but will let him confirm 👍 ).

**Comment by nullhook** [comment]
> Note: this may reduce Brave privacy protections.

the above was copied from Figma

> In addition to this issue, I found out that Learn more, Filter Lists, and Global defaults options don't do anything. Please, let me know if you would like me to open another ticket for that, or is there one already? Thanks.

i'll be addressing this https://github.com/brave/brave-core/pull/12523

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.39.10 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

Used the original steps to reproduce from https://github.com/brave/brave-browser/issues/21583#issue-1164816369.

Confirmed `Brave's privacy protections`

<img width="892" alt="Screen Shot 2022-03-28 at 4 07 44 PM" src="https://user-images.githubusercontent.com/387249/160502205-582c48b0-4742-453b-b05c-b82a9155f22b.png">


@Tonev mind filing separately for the `Filter Lists` -> `Filter lists` issue?

**Comment by Tonev** [comment]
Sorry for getting late to you, @stephendonner, somehow missed your email. There was no need for a new ticket as @nullhook addressed the matter in the same pull request, just at a later point so your testing wasn't able to catch it.

<html>
<body>


Brave | 1.39.22 Chromium: 100.0.4896.60 (Official Build) nightly (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 7 Service Pack 1 (Build 7601)


</body>
</html>

![image](https://user-images.githubusercontent.com/20608253/161110886-ad98700a-bc78-4d0b-a17f-48f83be5b1d8.png)

**Comment by MadhaviSeelam** [comment]
Verified `Passed` using

Brave | 1.38.77 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 11 Version 21H2 (Build 22000.593)

Install 1.38.77
Launch Brave
Enable brave://flags/#brave-shields-v2 -> Relaunch.
Visited brave.com.
Open the Shields panel via the Shields icon.
Verified Shields V2 text for `Brave's privacy protections`

<img width="950" alt="Shields v2-text change" src="https://user-images.githubusercontent.com/98358127/161337874-5a077905-c594-43b1-b64e-e745a01353ef.png">

**Comment by MadhaviSeelam** [comment]
@Tonev Figma designs (Latest Rev) needs update as well FYI

<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/161338337-94e7f8cb-6649-48bd-9204-42b355d61531.png">

**Comment by Tonev** [comment]
@MadhaviSeelam

Thanks for telling me, but I'm afraid I won't be able to do anything about it. If folks keep updating the designs, and the designs don't future the changes from this ticket, I'm afraid it would be a lost cause - someone will update through a PR, and then someone else's PR that updates the designs will erase the previous PR's changes.

CC: @rebron @stephendonner @aguscruiz for thoughts on the matter, please!
