### ISSUE TITLE
Allow for VPN on Beta

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21598]
## Description 
Changes needed so that VPN can move from Nightly to Beta with 1.38 😄 

1. VPN functionality is tied to the Nightly channel at the moment (via build flag). We should expose this feature on brave://flags/#brave-vpn for Beta also.

2. VPN for Desktop is also requiring that SKU SDK (brave://flags/#skus-sdk) is enabled. We should enable the SKU SDK feature by default

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.39.84 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

Followed the testplan at https://github.com/brave/brave-browser/issues/21598#issue-1166088243.

#### Confirmed, from the testplan:

> 1. VPN functionality is tied to the Nightly channel at the moment (via build flag). We should expose this feature on brave://flags/#brave-vpn for Beta also.

All three flags are available:
1. `brave://flags/#brave-vpn`
2. `brave://flags/#skus-environment`
3. `brave://flags/#skus-sdk`

`SKUs` | `VPN` 
--------|------
<img width="1312" alt="Screen Shot 2022-04-28 at 6 39 09 PM" src="https://user-images.githubusercontent.com/387249/165873059-01b35126-0204-48a9-890b-cf0d46de8aee.png"> | <img width="1312" alt="Screen Shot 2022-04-28 at 6 39 14 PM" src="https://user-images.githubusercontent.com/387249/165873062-7dbf2151-c08c-44ca-a034-54d675a32b51.png">



> 2. VPN for Desktop is also requiring that SKU SDK (brave://flags/#skus-sdk) is enabled. We should enable the SKU SDK feature by default

#### Confirmed via entering `window.chrome.brave` into the `Developer Tools` `Console` yielded `window.chrome.braveSkus`, without enabling `brave://flags/#skus-sdk` (left as `Default` as seen in screenshot).

### Steps:
1. install `1.39.84`
5. launch Brave using `--vmodule="*/skus/*"=1 --enable-logging=stderr`
6. set `Enable Experimental Brave VPN` to `Enabled` 
7. set `Experimental SKU Environment` to `Development`
8. click `Relaunch`
9. load `account.brave.software`
10. enter basic auth creds for site
11. enter an email address and click `Get login link`
12. check your email inbox
13. click `Log in to Brave` or the link in the email
14. click on `Browse plans`
15. scroll down and click on `Buy now` for `Brave VPN Subscription`
16. enter payment details on `https://checkout.stripe.com/pay/cs_test…`
17. click `Subscribe`
18. you should get a `Complete your purchase...` screen
19. click on `Complete payment`

#### Confirmed I could successfully (and automatically) connect to VPN via the icon and its toggle, in the URL bar.

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2022-04-28 at 6 10 21 PM" src="https://user-images.githubusercontent.com/387249/165872149-78959ae9-e3c1-4ddf-837f-def5f1e69065.png"> | <img width="1759" alt="Screen Shot 2022-04-28 at 6 16 53 PM" src="https://user-images.githubusercontent.com/387249/165872326-2272dfa1-ee82-4d5b-9dc7-aa9c62a1af40.png"> | <img width="1680" alt="Screen Shot 2022-04-28 at 5 54 44 PM" src="https://user-images.githubusercontent.com/387249/165872786-1f918610-17ee-49a6-96a9-3715c1014463.png"> | . | <img width="1759" alt="Screen Shot 2022-04-28 at 6 20 13 PM" src="https://user-images.githubusercontent.com/387249/165872332-7d142fec-6a27-4fdf-89bb-a8e45070521c.png">

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.39.101 Chromium: 101.0.4951.64 (Official Build) beta (64-bit)
-- | --
Revision | d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
Followed the testplan at https://github.com/brave/brave-browser/issues/21598#issue-1166088243.

### Steps:
1. install `1.39.84`
5. launch Brave using `--vmodule="*/skus/*"=1 --enable-logging=stderr`
6. set `Enable Experimental Brave VPN` to `Enabled` 
7. set `Experimental SKU Environment` to `Development`
8. click `Relaunch`
9. load `account.brave.software`
10. enter basic auth creds for site
11. enter an email address and click `Get login link`
12. check your email inbox
13. click `Log in to Brave` or the link in the email
14. click on `Browse plans`
15. scroll down and click on `Buy now` for `Brave VPN Subscription`
16. enter payment details on `https://checkout.stripe.com/pay/cs_test…`
17. click `Subscribe`
18. you should get a `Complete your purchase...` screen
19. click on `Complete payment`

#### Confirmed I could successfully (and automatically) connect to VPN via the icon and its toggle, in the URL bar.

example | example | example | example | example
---------|----------|---------|----------|---------
