### ISSUE TITLE
`Add to Sidebar` text is truncated in Bulgarian locale

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#21597]
## Description 

Hovering on the `+` icon in the sidebar will display truncated text while Brave is displayed in Bulgarian.

## Steps to Reproduce

   1. Set Brave to be displayed in Bulgarian.
   2. Make sure Sidebar is displayed.
   3. Open a page that can be added to the Sidebar, for example `brave://settings/`.
   4. Hover on the `+` icon in the Sidebar.

## Actual result:

![Untitled](https://user-images.githubusercontent.com/20608253/157811582-afe781bb-9d5b-46fa-8c14-7a4ec586498a.png)

## Expected result:
I guess it could be made so any text longer than X to be displayed on 2 lines to avoid truncation. 

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.35 Chromium: 99.0.4844.51 (Official Build) nightly (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

**Comment by rebron** [comment]
cc: @simonhong

**Comment by simonhong** [comment]
@rebron Which one is more better for long string? Multi line vs. Single line
![Screenshot 2022-03-14 153922](https://user-images.githubusercontent.com/6786187/158118532-f6c09e36-c462-47fb-be4c-6e2aa040b155.png)
![Screenshot 2022-03-14 154103](https://user-images.githubusercontent.com/6786187/158118536-0facff0a-efd2-45f4-bf3e-b773e74d6d8b.png)

**Comment by rebron** [comment]
@simonhong Single line.

**Comment by kjozwiak** [comment]
Above issue requires `1.37.98` or higher for verification on `1.37.x`.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.37.98 Chromium: 99.0.4844.74 (Официално издание) beta (64 бита)
-- | --
Ревизия | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
ОС | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the STR from the description and ensured `Add to Sidebar` text is NOT truncated in Bulgarian locale

Normal window | Private window | TOR window
--|--|--
![image](https://user-images.githubusercontent.com/38657976/158981637-282ccdbf-8fba-4a3b-8539-d78d21f1cbf1.png) | ![image](https://user-images.githubusercontent.com/38657976/158982096-b6d112f4-eb1f-42c0-a572-c9a326650220.png) | ![image](https://user-images.githubusercontent.com/38657976/158982146-84653043-a9a2-4eec-8e24-4d7403f21d2c.png)
