### ISSUE TITLE
Blocked count highlight doesn't cover entire number

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21601]
## Description 

Blocked count highlight doesn't cover entire number

## Steps to Reproduce

   1.  install `1.38.35`
   2. launch Brave
   3. enable `Shields V2` via `brave://flags`
   4. restart Brave
   5. sit on an XHR-happy page (any Facebook one will do)
   6. check the Shields-blocked count via the icon-tip in the URL bar
   7. once it reaches `99+`, click on it to expand the flyout panel
   8. click to open its `Advanced controls` sub-panel
   9. hover over the number for `Trackers & ads blocked (standard)`
   10. note the highlight paint region

## Actual result:

<img width="1312" alt="Screen Shot 2022-03-11 at 12 41 01 AM" src="https://user-images.githubusercontent.com/387249/157833842-8933eca0-785e-4dae-afca-da0b4e72ab21.png">

## Expected result:

Should paint the entire number with the hover highlight 

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.38.35 Chromium: 99.0.4844.51 (Official Build) nightly (arm64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 11.6.4 (Build 20G417)

cc @nullhook @rebron @sri

**Comment by rebron** [comment]
We stopped at 99+ for Shield v1. Need a decision here if we want to go with actual numbers in v2.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.60 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.3 (Build 20G415)

0 | 1 | <99 | 99+ | details
--|---|---|----|-----
<img width="1312" alt="Screen Shot 2022-03-21 at 10 57 56 AM" src="https://user-images.githubusercontent.com/387249/159341712-6fff22eb-ef4d-45c7-8fac-8dcb13839720.png"> |<img width="1312" alt="Screen Shot 2022-03-21 at 10 50 53 AM" src="https://user-images.githubusercontent.com/387249/159341755-30db9ae4-ac50-438a-bb47-0443c0e5d41f.png"> | <img width="1312" alt="Screen Shot 2022-03-21 at 10 56 18 AM" src="https://user-images.githubusercontent.com/387249/159341876-5229ee36-39f4-490e-9d28-8050b6a1a00e.png"> | <img width="1312" alt="Screen Shot 2022-03-21 at 10 57 15 AM" src="https://user-images.githubusercontent.com/387249/159341966-8fce87ef-543d-4f6a-bc1c-dfde8803de2f.png"> | <img width="1312" alt="Screen Shot 2022-03-21 at 10 57 23 AM" src="https://user-images.githubusercontent.com/387249/159341991-f71f724b-54d9-4bf3-b5b3-6bb4dd092aad.png"> | <img width="1312" alt="Screen Shot 2022-03-21 at 10 57 23 AM" src="https://user-images.githubusercontent.com/387249/159342215-17660df1-4842-4827-8082-36c75ef3bd99.png">
