### ISSUE TITLE
Proxy requests for CRLSets through crlsets[n].brave.com

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#2160]

**Comment by jumde** [comment]
Reverted: https://github.com/brave/brave-core/pull/986 (master and 0.58.x)

**Comment by diracdeltas** [comment]
also need to proxy the update.googleapis.com request from #2280

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1581
* Verified test plan from description: no connections to sites listed in description and CRLSet has non-zero version number:
![Screen Shot 2019-05-08 at 1 35 23 PM](https://user-images.githubusercontent.com/28145373/57396295-1dc61800-7198-11e9-9263-db87e1a83eda.png)
![Screen Shot 2019-05-08 at 1 48 41 PM](https://user-images.githubusercontent.com/28145373/57396296-1f8fdb80-7198-11e9-954f-7f2139c65be8.png)
