### ISSUE TITLE
Shields UI refresh still shows blocked count when setting is off

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#21613]
## Description 

In brave://settings there is an option to not display the blocked count in the shields action icon. This is not respected by the shields refresh button.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/741836/157929264-00150cc4-fcdb-48e7-b8eb-64d917a4e51f.png">

## Steps to Reproduce

   1.  open settings
   2. turn "Show the number of blocked items on the Shields icon" off
   3. Go to a tab with blocked items

## Actual result:

Blocked count is still shown

## Expected result:
Blocked count is not shown

v 1.38.27

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.60 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.3 (Build 20G415)

Steps:
1. install `1.38.60`
2. launched Brave
3. loaded `ign.com` and clicked on an article
4. confirmed I saw blocked count on the Shields icon
5. confirmed `Show the number of blocked items on the Shields icon` is toggled to `ON`
6. toggled the above to `OFF`
7. reloaded the `ign.com` page
8. confirmed I no longer saw the blocked count on the Shields icon


example | example
---------|---------
<img width="1680" alt="Screen Shot 2022-03-22 at 1 47 05 PM" src="https://user-images.githubusercontent.com/387249/159574733-54ad20ca-a79b-414a-8dbb-c3fbd48965fc.png"> | <img width="1679" alt="Screen Shot 2022-03-22 at 1 47 28 PM" src="https://user-images.githubusercontent.com/387249/159574801-f83e7a58-6d94-465b-a9ea-deddfe6c0132.png">

**Comment by MadhaviSeelam** [comment]
Brave | 1.38.77 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 11 Version 21H2 (Build 22000.593)

- Install 1.38.77
- launched `Brave`
- Visited `theverge.com` and clicked on an article
- confirmed I saw blocked count on the `Shields icon`
- confirmed `Show the number of blocked items on the Shields icon` is toggled to `ON`
- toggled the above to `OFF`
- reloaded the `theverge.com` page
- confirmed I no longer saw the blocked count on the `Shields icon`

ex1|ex2
---|---
<img width="950" alt="blocked items" src="https://user-images.githubusercontent.com/98358127/161323211-a3ee2f11-7d3e-4c1b-b04d-e21f3c3523e9.png">|<img width="950" alt="turned off shields" src="https://user-images.githubusercontent.com/98358127/161323217-7bfe423f-8bee-4319-bce8-d92c8ab5ea1d.png">
