### ISSUE TITLE
brave_wallet_js_handler refactor

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#21615]
We want to move all JSON request, response parsing out from js handler as it is in a renderer process currently. iOS platform would be able to reuse most of functionality if we do that.
We need to retest basically DApps functionality to make sure nothing is broken there.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">  1.38.106 Chromium: 101.0.4951.41 (Official Build)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified able to connect to Dapps and disconnect without any issues</li>
         <li>Verified able to perform a <a href=https://etherscan.io/tx/0x2e5a24584a62ae65f5d78781e6e3c2157081999733aa83bbcd9220b8a3e65457>transaction</a> on the Dapp without issues</li>
        </ul>
      </td>
   </tr>
</table>
