### ISSUE TITLE
Replace P3A version field with an is-up-to-date flag

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#21622]
## Description 

P3A reports are tagged with various metadata about the install, including the exact version number. There's a lot of variation here and early/late adopters stand out, reducing anonymity.

The version is useful to look for the effect of features or bugs which are known to transition with a particular release. In practice before/after partitions are often all that is of interest. With the weekly P3A measurement cadence, the release number is more fine-grained than we need.

Instead, we should report just a binary measurement of whether the client is up to date with the current release. `current_release: true | false`. Combined with the release channel information this should be sufficient to determine the effects of code changes over time.

## Miscellaneous Information:

The browser already checks for available updates, at least on desktop. This could be implemented by comparing the available update to the currently-installed version and seeing if the install is older by more than some fixed time window, say 2 weeks. Where the update information isn't available, comparing the age of the installed release to some window based on our release cadence, say 4 weeks, could work as a fallback.

If this is infeasible, an alternative is to report only the major and minor version numbers: `1.38.x` instead of `1.38.37` for example.

**Comment by DJAndries** [comment]
As per internal discussion, the client will compare its current version with the new "latest_version" field in the usage ping response. If the user has disabled the usage ping, a fallback method involving the last browser update event will be used. If the last browser update was performed over four weeks ago, an outdated browser version will be assumed.

**Comment by DJAndries** [comment]
There is a weakness to the fallback approach. If a user installs an older version of the browser, and turns off the usage ping, P3A messages from this user will incorrectly indicate an up-to-date installation for 4 weeks after the install.

**Comment by rillian** [comment]
In addition to looking at a P3A response, I think the browser already checks for updates on some platforms. If so, it would be good to integrate that information as well. E.g. [on windows](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/upgrade_detector/upgrade_detector.h) we might be able to do something like `UpgradeDetector::GetInstance()->is_outdated_install()`.

**Comment by rillian** [comment]
Actually, I think that implementation determines out-of-date-ness by just [comparing](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/upgrade_detector/upgrade_detector_impl.cc;l=251-268) the current time to [base::GetBuildTime()](https://source.chromium.org/chromium/chromium/src/+/main:base/build_time.h). So this seems no different from our proposed time-based fallback.

**Comment by DJAndries** [comment]
Closing with "wont fix". A while ago, a change was made to report only the major and minor components of the version. We can revisit if we don't have enough measurements to meet _k_.
