### ISSUE TITLE
Confirmation state in swap

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21637]
After clicking swap the swap widget should change from the input state to a pending transaction state that gives some progress/status on the pending swap. Could also be bypassed to perform an other swap.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Linux

- Verified steps from [brave/brave-core#15079](https://github.com/brave/brave-core/pull/15079)
- Verified panel shows individual state of the transactions 

https://user-images.githubusercontent.com/17010094/197759871-0371fd0c-6460-47c0-852a-4e6e34deb4fd.mp4


------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15079](https://github.com/brave/brave-core/pull/15079)
- Verified panel shows individual state of the transactions 

https://user-images.githubusercontent.com/17010094/197726065-0c2dbb70-09c1-429d-ae44-207c8bcee4c3.mp4

------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (arm64)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15079](https://github.com/brave/brave-core/pull/15079)
- Verified panel shows individual state of the transactions 

https://user-images.githubusercontent.com/17010094/197735353-1334331a-7a88-486e-ac1a-f78b03ebdf13.mov
