### ISSUE TITLE
Refactor database

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#2163]
Currently our API is tightly connected to activity table. Because of that we need to do a lot of hacks to get data about publisher. We are also missing visits column in activity_info table.

We need to split this info simpler API.

**Comment by LaurenWags** [comment]
@NejcZdovc @rebron @kjozwiak is this issue in the correct milestone? Shouldn't it be in 0.61.x?

**Comment by NejcZdovc** [comment]
@LaurenWags this was merge into 0.60 https://github.com/brave/brave-core/pull/1356

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

* Verified general Rewards regression and flow over several builds, but most recently with the one above.
