### ISSUE TITLE
[Android] brave://rewards settings page is blank

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21649]
## Description

User seeing a blank brave://rewards settings page. This was an issue in the past but was fixed https://github.com/brave/brave-browser/issues/10492, so might be a regression.

## Case 1

>Brave Version - 1.35.103 Android 11 Samsung M51 / SM51-M515F Not a custom OS and no rooting. It started 2 days back when i cleared cache. I am still getting ads and i am still getting rewards in estimated earnings. On that day itself before clearing cache, i had verified my uphold account and transferred my BAT for the 1st time. After transferring i logged out my uphold account from brave browser and cleared cache. I have never installed brave beta or brave nightly.

Summary: Starting happening after user cleared cache 

cc: @srirambv

**Comment by Miyayes** [comment]
>1.36.112
Android version: 11
OnePlus 6
Not rooted, no custom OS
In the past two weeks and has persisted after I updated the app today. Similar to OP, I cleared my cache around then so maybe that's related?

**Comment by Brave-Matt** [comment]
I have another Community user with the same issue. They have the following setup:

> Samsung M515F / One UI Core version 3.1
> Android 11
> Brave 1.36.112
User also stated that this issue occurred after they had cleared their cache

**Comment by Brave-Matt** [comment]
+1 on Community, user has:
> Device name - OnePlus Nord
Model - AC2001
OS - OxygenOs 11.1.9.9.AC01DA (Stable Release)

**Comment by Brave-Matt** [comment]
Wanted to note that another user reporting this is unable to verify their wallet for this same reason. Selecting `Verify wallet` lands them on a blank white screen. cc @Miyayes 
Recording attached:

https://user-images.githubusercontent.com/3299098/160197688-1b87e93a-acaf-4f37-946c-88b5b0bb3cef.mp4

**Comment by djak250** [comment]
I also contributed to that community thread.
Device Name - Samsung ZFold 3
Model - SM-F926U1
OS - One UI 4.1

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/blank-rewards-page-on-browser/366742

**Comment by djak250** [comment]
Looks like the page shows up in the nightly, at least for me. Good news.

**Comment by Miyayes** [comment]
Awaiting confirmation from @Brave-Matt who's working with a user.

**Comment by Miyayes** [comment]
@srirambv Do you know if this is resolved with https://github.com/brave/brave-browser/issues/22113?

**Comment by djak250** [comment]
It's working for me now on the main release channel

**Comment by aman-m1** [comment]
+1 from community on v1.39.102- https://community.brave.com/t/blank-page-in-brave-rewards/406301
