### ISSUE TITLE
Update Buy/Send/Swap tabs new UI

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21641]
New UI for buy/send/swap widget supports more features

![Screen Shot 2022-03-13 at 8 34 51 PM](https://user-images.githubusercontent.com/318119/158090164-c16c7f0b-d79c-4ca3-81da-3018a7f57855.png)
![Screen Shot 2022-03-13 at 8 35 06 PM](https://user-images.githubusercontent.com/318119/158090167-640b6d7b-2be7-4a8d-80cc-feec865c875a.png)

**Comment by srirambv** [comment]
Is there a mobile specific UI being done for this v2?

**Comment by onyb** [comment]
Issue is quite stale and superseded by Wallet 2.0
