### ISSUE TITLE
Failed to log into Pocket using Google account

### ISSUE THREAD

**Issue by shinglyu** [brave/brave-browser#2164]
## Description 

Trying to log into Pocket using google account failed. This happens both in the Pocket chrome extension and the getpocket.com website.

## Steps to Reproduce

   1. Go to https://getpocket.com
   2. Click "Log in"
   3. Select "Log in with Google"
   4. Google account pops up, select the account we want to use

## Actual result:

The google account popup closes, but the pocket page doesn't log in, it stays in the login screen

## Expected result:
The google account popup closes and the pocket page is logged in

## Reproduces how often: 

Easily reporduced

## Brave version (brave://version info)

Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Haven't checked

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Does setting allow all cookies in shields allow to login?

**Comment by shinglyu** [comment]
I don't quite get your question. But shields are all down, and cookies are allowed in the setting

**Comment by shinglyu** [comment]
Ah sorry I see. Yes if I set to "Allow all cookies" in the global shields defaults, it works. Maybe it would be better to whitelist this cookie?

**Comment by srirambv** [comment]
This is a known issue. We are tracking it here https://github.com/brave/brave-browser/issues/1380. I'll close this as duplicate and added +1 there

**Comment by bbondy** [comment]
FYI: This should be fixed on Dec 6th with the 0.57.x release.
