### ISSUE TITLE
[De-AMP] Follow up issues for Android

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#21643]
Noting down follow ups for https://github.com/brave/brave-core/pull/11750

- Add settings UI for Android
- Manual test on Android
- Enable feature flag on Android

**Comment by kjozwiak** [comment]
@srirambv @Uni-verse in case you guys run through the above on `1.38,x`, cases can be found via https://github.com/brave/brave-core/pull/13001#issuecomment-1105932391 which were copied over from https://github.com/brave/brave-core/pull/11750#issue-1094407255.

Above requires `1.38.105` or higher for `1.38.x` verification 👍

**Comment by Uni-verse** [comment]
Verification in progress using 1.38.106

Duplicated the STR/Cases by @kjozwiak which were outlined via https://github.com/brave/brave-core/pull/13001#issuecomment-1105932391 in the testing on Nightly. 

<summary>Test Case 1: Inspecting AMP elements on pages</summary>
<details>

1. Disable `Auto-redirect AMP pages` in `brave://settings/privacy`
2. Disable Enable De-AMP flag - `brave://flags/#brave-de-amp`
4. Relaunch Brave
5. Visit AMP page `https://shivankaul.com/brave/de-amp/test-small-amp.html`.
    - Inspected element  and  `amp` attribute will be shown in the top level `<html amp>` tag for the AMP page  and has canonical link that redirects to html <link rel="canonical" href="https://brave.com/">
6. Close the tab and visit another AMP page `https://shivankaul.com/brave/de-amp/test-small-amp-with-lightning.html`
    - Inspected element and it contains lightning symbol in  the top-level `<html ⚡>` tag for the AMP page and has canonical link that redirects to html <link rel="canonical" href="https://brave.com/">
7. Close the tab and visit `https://shivankaul.com/brave/de-amp/test-no-canonical-link.html` 
    - Inspected element and it doesn't contain any canonical links or top-level tags
8. Close the tab and visit  `https://shivankaul.com/brave/de-amp/test-wrong-scheme.html` 
    - Inspected element for canonical link that is non-HTTP(s) - `<link rel="canonical" href="ipfs://QmcniBv7UQ4gGPQQW2BwbD4ZZHzN3o3tPuNLZCbBchd1zh">`
9. Close the tab and visit `https://shivankaul.com/brave/de-amp/test-small-amp-same-canonical.html`
    - Inspected the element and it has canonical link that is pointed to original/same URL
10. Close the tab and visit `https://www.buzzfeed.com/amphtml/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap`
    - Inspected the element and it has canonical link that is pointed `https://www.buzzfeed.com/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap`

example | example | example | example | example | example | example | example
-|-|-|-|-|-|-|-
![Screen Shot 2022-04-25 at 1 02 27 PM](https://user-images.githubusercontent.com/17885425/165166580-519dc38d-f85f-4c11-b47a-4102ec765945.png) | ![Screen Shot 2022-04-25 at 12 33 50 PM](https://user-images.githubusercontent.com/17885425/165164707-3c60de57-ac34-4eb8-bcad-f39241683d07.png) | ![Screen Shot 2022-04-25 at 12 37 13 PM](https://user-images.githubusercontent.com/17885425/165164712-17b69703-c6ee-4f30-a80e-80b1e73ea126.png) | ![Screen Shot 2022-04-25 at 12 38 47 PM](https://user-images.githubusercontent.com/17885425/165164716-fa5dc8f3-3677-4af5-91c3-a2e0a4e7c533.png) | ![Screen Shot 2022-04-25 at 12 41 19 PM](https://user-images.githubusercontent.com/17885425/165164720-1be74f55-1188-4249-81a6-f885005a63a5.png) | ![Screen Shot 2022-04-25 at 12 43 05 PM](https://user-images.githubusercontent.com/17885425/165164723-8594f902-b57d-4748-94b2-301f0fc7b825.png) | ![Screen Shot 2022-04-25 at 12 45 25 PM](https://user-images.githubusercontent.com/17885425/165164727-3501ef0a-c216-40e7-9d29-c91addaf4a88.png) | ![Screen Shot 2022-04-25 at 12 48 23 PM](https://user-images.githubusercontent.com/17885425/165164729-2770f33c-6409-4699-adfc-e6d3d38c1366.png) | ![Screen Shot 2022-04-25 at 12 48 23 PM](https://user-images.githubusercontent.com/17885425/165166290-69c432a1-65be-4f82-aa31-314e8814d31e.png)



</details>

<summary>Test Case 2</summary> 
<summary>Test Case 3</summary> 
<summary>Test Case 4</summary> 
<summary>Test Case 5</summary>
<summary>Test Case 6</summary>
<summary>Test Case 7</summary>
<summary>Test Case 8</summary>
<summary>Test Case 9</summary>
<summary>Test Case 10</summary>
<summary>Test Case 11</summary>
<summary>Test Case 12</summary>

**Comment by kjozwiak** [comment]
After speaking with @ShivanKaul, running through the mobile cases should be enough and tablet can be skipped. Tablet doesn't use AMP as much as the mobiles due to the view usually being `Desktop` due to the bigger screens. However, double checked and ensured that the feature has been enabled by default.
