### ISSUE TITLE
Add logic in fetch-order-credentials for v2 time-limited credentials

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#21646]
## Test plan
Would be covered in the general VPN testing. See https://github.com/brave/brave-browser/issues/25680 for more information.

## Description
Credentialing used by the SKU SDK system ("time limited credentials").

See security review for more detailed information: 
https://github.com/brave/security/issues/738

**Comment by bsclifton** [comment]
Marking as `QA/No` only because this will be tested within the scope of the VPN project

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/15465
