### ISSUE TITLE
Add a Select Network field in the Custom Asset Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21656]
## Description 
We need a `Select Network` field to the `Add Custom Asset` modal to allow adding custom assets for any chain.

![Screen Shot 2022-03-14 at 7 51 47 PM](https://user-images.githubusercontent.com/40611140/158290164-15f43a2d-6731-46fd-bbbe-b367e4dd2eb9.png)

**Comment by Uni-verse** [comment]
Verified using 

```
Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.1 (Build 21C52)
```
- Verified network selector in the Custom Asset Modal.
- Entering the contract address will populate the fields.
- Added asset will show up in the portfolio page.
- Asset added will contain the appropriate pin.
- Added asset will correctly display USD value of the asset.

![Screen Shot 2022-04-07 at 4 49 12 PM](https://user-images.githubusercontent.com/17885425/162340970-2c45cc7a-dc58-4522-8651-75f1b7739cea.png)

![Screen Shot 2022-04-07 at 5 30 17 PM](https://user-images.githubusercontent.com/17885425/162341381-c8f28735-0bf4-495e-88e5-b621fd26c9e6.png)


Issues Encountered: 
- Added an asset contract that doesn't match network will result in some assets showing up in a loading state on the portfolio page. Ex: Added GALA Eth mainnet contract address but selected Binance Smart Chain Mainnet as the network in the form. This didnt populate automatically but after filling in the details and adding the asset, the result looks like below image. 

![Screen Shot 2022-04-07 at 4 50 55 PM](https://user-images.githubusercontent.com/17885425/162341504-6cf1e9a6-5087-49fb-b036-8d1dbdfa74df.png)
