### ISSUE TITLE
Use correct icon for Wallet in the sidebar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#21655]
## Description 

Current Wallet icon in the sidebar should be using the most current set which is the same one used in the navigation toolbar.

## Steps to Reproduce

   1. Use beta and nightly and notice wallet icon in the sidebar. It should be the same as the one in the navigation toolbar.

## Actual result:

<img width="89" alt="Screen Shot 2022-03-14 at 2 59 30 PM" src="https://user-images.githubusercontent.com/5951041/158268219-f343d2ff-7b70-4af9-83bd-969d1a3b0cb0.png">

## Expected result:
<img width="38" alt="Screen Shot 2022-03-14 at 2 59 45 PM" src="https://user-images.githubusercontent.com/5951041/158268250-cd7f94ec-b149-43cb-bf28-868c12306219.png">

## Brave version (brave://version info)

1.37.x and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

[placeholder for Figma link and assets]

**Comment by aguscruiz** [comment]
Figma is here
https://www.figma.com/file/xWGBM3qWbu3RLuZqZGwynk/Icons?node-id=124%3A10694

Icon name: "brave-wallet" (Can't link directly but @simonhong is mentioned on the icon)

**Comment by kjozwiak** [comment]
Above issue requires `1.37.98` or higher for verification on `1.37.x`.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.37.98 Chromium: 99.0.4844.74 (Official Build) beta (64-bit)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the STR from the description and ensured the correct icon is displayed for the wallet

Light mode | Dark mode
--|--
![image](https://user-images.githubusercontent.com/38657976/158988535-795c408b-a62d-4eeb-bb72-b9874067af58.png) | ![image](https://user-images.githubusercontent.com/38657976/158988661-ee438bee-43df-460e-b00c-63470158e77e.png)
