### ISSUE TITLE
Add showTestNetworks user pref in Settings

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21650]
## Description 
We need a `showTestNetworks: boolean` user pref in `brave://settings/wallet` to allow users to decide if they want to see `Test Networks` as an option in their wallet. Could be just a `boolean` value and the `Front-end` can filter out those networks or vice versa if we want to handle on the backend.

**Comment by srirambv** [comment]
Does Android inherit this changes or should that be done separately? 

cc: @SergeyZhukovsky @wchen342 @Pavneet-Sing

**Comment by SergeyZhukovsky** [comment]
@srirambv it's a front-end work, need to be done separately on mobile

**Comment by kjozwiak** [comment]
The above requires `1.39.110` or higher for `1.39.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13098>brave/brave-core#13098</a></li>
         <li>Verified new setting called <code>Show test networks</code> is available under <code>brave://settings/wallet/networks</code></li>
         <li>Verified setting is disabled by default hence no test network is shown by default</li>
         <li>Verified enabling the settings shows all test networks for default networks(Solana/Ethereum)</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Show test networks <code>Off</code>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169752470-6e4f76c7-7572-4b9a-b137-19e2d0302f09.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169752957-652eea15-f53b-44e4-9d7e-b76dabf03389.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169753026-d308ce7b-f43f-43f8-81c7-9c64a75b2775.png>
      </td>
   </tr>
   <tr>
      <td>Show test networks <code>On</code>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169752679-6b54a14e-51cf-4350-8095-253d3d38b591.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169752971-7582e3bf-ae2a-4cd0-86d4-71daf062d1ef.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169753044-67e7f2ce-a1a9-4f15-a8e5-1830b00d3bb3.png>
      </td>
   </tr>
   <tr>
      <td>Test networks shown network selector
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169752789-948b281a-107f-4041-98ce-a7c40ef7e56b.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169752998-8ab611fc-6749-48bc-8da1-eebd94699e19.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169753062-d4431906-4d22-4fa6-971f-acd49a32ed01.png>
      </td>
   </tr>
   <tr>
      <td>Test networks not visible on network selector
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169752888-d52e39b6-1959-4b21-baca-5217e718e674.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169753012-a115c517-628d-4325-86ca-9bcce07ba789.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169753086-189ae772-0000-4d81-afc9-076edab8ec99.png>
      </td>
   </tr>
</table>
