### ISSUE TITLE
Need proper text alignment for really long token names 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21659]
## Description 

Need proper text alignment for really long token names 

## Steps to Reproduce

   1. Add custom networks (BSC)
   2. Open Swap Tab and scroll down the token list
   3. Tokens with long name aren't properly aligned

## Actual result:

https://user-images.githubusercontent.com/17010094/158303729-22e84ec3-7f14-402f-98e1-5a39c013399e.mov

Note: Not an issue on panel 

Panel | Swap Widget
-- | --
<img src="https://user-images.githubusercontent.com/17010094/158303830-dddbd194-57a2-49ca-9900-cb20ed676d82.png"> | <img src="https://user-images.githubusercontent.com/17010094/158303868-fbbb5569-c8c8-4358-aada-2981c662e7ef.png">

## Expected result:
Proper text alignment for long named tokens

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.38.43 Chromium: 99.0.4844.51 (Official Build) nightly (64-bit)
-- | --
Revision | `d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}`
OS | Windows 11 Version 22H2 (Build 22572.1)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @Douglashdaniel @josheleonard

**Comment by Uni-verse** [comment]
Verified using 

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.3.1 (Build 21E258)

- Using STR from above, verified long token names are aligned properly (left)

https://user-images.githubusercontent.com/17885425/163061643-f0902422-2ee6-457a-9c9b-b865437b4b30.mov
