### ISSUE TITLE
Don't impose WebSockets limits on Extensions

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#21661]
Currently we limit WebSockets connections for Extensions as part of https://github.com/brave/brave-browser/issues/19990 implementation. We don't need to do this.

See https://github.com/brave/brave-browser/issues/19990#issuecomment-1067046344

**Comment by stephendonner** [comment]
@goodov 👋 mind rounding our a test plan for this?  cc @brave/qa-team and setting `QA/Blocked` until we've got that; thanks!

**Comment by goodov** [comment]
> @goodov 👋 mind rounding our a test plan for this? cc @brave/qa-team and setting `QA/Blocked` until we've got that; thanks!

This can be tested by running a simple extension which creates WebSocket connections and shows that there are no limits (it can create much more than 10 connections).

[ws-extension-test.zip](https://github.com/brave/brave-browser/files/8370041/ws-extension-test.zip)

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.71 Chromium: 100.0.4896.46 (Official Build) beta (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

Steps:
1. install 1.38.71
2. launch Brave
3. install `https://github.com/brave/brave-browser/files/8370086/ws-extension-test.zip`
4. click the button
5. note the # of successfully created WebSockets connections

Confirmed we hit well over 10; in my limited testrun, it took until `65` before we started having connection-establishing/maintaining errors.

`25` `WebSockets` | `64+` `WebSockets`
---------|---------
<img width="1491" alt="Screen Shot 2022-03-29 at 1 22 08 PM" src="https://user-images.githubusercontent.com/387249/160702010-5ef1acdb-b1b7-4ef4-b56b-9a27a4a11184.png"> | <img width="1491" alt="Screen Shot 2022-03-29 at 1 28 00 PM" src="https://user-images.githubusercontent.com/387249/160702019-cfda53d4-0702-4508-ac66-a616e81c9837.png">

**Comment by stephendonner** [comment]
@goodov asking on behalf of @brave/qa-team - are there really (easily) testable Android steps, here?  🙏

**Comment by goodov** [comment]
> @goodov asking on behalf of @brave/qa-team - are there really (easily) testable Android steps, here? 🙏

There're no extensions, so this task is not applicable for Android.

**Comment by LaurenWags** [comment]
Linking confirmation that this is resolved from https://github.com/brave/brave-browser/issues/19990#issuecomment-1080599784

**Comment by MadhaviSeelam** [comment]
Verified `Passed` using

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 21H2 (Build 22000.593)


- install 1.38.83
- launch Brave
- installed https://github.com/brave/brave-browser/files/8370086/ws-extension-test.zip
- click the start button
- note the # of successfully created WebSockets connections

Confirmed we hit well over 10.

25 web sockets| 64+
---|---
<img width="956" alt="25+sockets" src="https://user-images.githubusercontent.com/98358127/162249440-3a16aae7-f172-4d48-871a-5fdb0297e330.png">|<img width="961" alt="64+ sockets" src="https://user-images.githubusercontent.com/98358127/162249484-35e13624-f326-43ec-8758-ba4ef37194ae.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

Confirmed I hit well over 10; 

![image](https://user-images.githubusercontent.com/34715963/162815001-82ef4a6c-104b-47bc-8360-9d3adb4d752a.png)
