### ISSUE TITLE
Dapp needs to communicate with unauthorized wallet

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#21678]
![Screen Shot 2022-03-15 at 8 53 01 AM](https://user-images.githubusercontent.com/318119/158430638-2579f0eb-5db6-4535-9e09-98147eb206f3.png)

When a Dapp notification fires and the wallet is not authenticated.

**Comment by Pavneet-Sing** [comment]
Closing: https://github.com/brave/brave-core/pull/12703/commits/f8a896d1eca8cf303c4873b374aa27e45c1b8750
