### ISSUE TITLE
Typescript is parsing too many files each time

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#2168]
Typescript config is making it try to type-check and compile every single *.ts[x] and *.js file inside `brave/components/**` every time it runs (which is for every `transpile_web_ui` target). This has the following issues:

- Adds to build time
- Makes a target error if there is an typescript issue in a completely independent target
- Creates unknown issues if there are untracked or unknown *.(ts|js|tsx) files in the source tree (e.g. out of memory issues when files are moved and generated files left in place, as happened recently)

## What do we want?
Typescript only type-checks and compiles files in the TS entrypoint and any modules that it imports.

Initial testing shows that we can replace our tsconfig.json / includes section simply with:
```
  "include": [
    "./components/definitions/*"
  ]
```
which resolves all the above issues.

**Comment by srirambv** [comment]
@petemill does this need QA verification?

**Comment by petemill** [comment]
This fixes a build issue only. Marked as no QA
