### ISSUE TITLE
Double Trouble (Brave Adblock)

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#21696]
## Description 

2 Brave Adblockers?

## Steps to Reproduce

 No idea how to reproduce.

## Actual result:
![1](https://user-images.githubusercontent.com/101682268/158499113-3b6f7f3c-c47a-43d0-ba6e-793e37b049a6.png)

## Expected result:
![1](https://user-images.githubusercontent.com/101682268/158499122-fc4700c8-7c69-404c-a6ab-41fc6a2b2d99.png)

## Reproduces how often: 

Intermittent issue, no steps to produce.

## Brave version (brave://version info)

Brave	1.36.112 Chromium: 99.0.4844.51 (Official Build) (x86_64) 
Revision	d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS	macOS Version 11.0.1 (Build 20B50)
JavaScript	V8 9.9.115.8
User agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Command Line	/Users/sean/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --enable-features=AllowedToFallbackToCustomAdNotifications,BraveAdblockCnameUncloaking,BraveAdblockCollapseBlockedElements,BraveAdblockCookieListDefault,BraveAdblockCosmeticFiltering,BraveAdblockCspRules,BraveAdblockDefault1pBlocking,BraveDarkModeBlock,BraveDebounce,BraveDomainBlock,BraveDomainBlock1PES,BraveEphemeralStorageKeepAlive,BraveExtensionNetworkBlocking,BraveFirstPartyEphemeralStorage,BraveNTPBrandedWallpaperDemoName,BraveNTPSuperReferralWallpaperName,BraveNews,BraveRewardsGemini,BraveRewardsVerboseLogging,BraveShieldsPanelV2,BraveSync,BraveWalletFilecoin,CosmeticFilterSyncLoad,CustomAdNotifications,DecentralizedDns,EphemeralStorage,Ipfs,NativeBraveWallet,Speedreader,UseBraveTranslateGo --flag-switches-end
Executable Path	/Users/sean/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/sean/Library/Application Support/BraveSoftware/Brave-Browser/Default
Linker	lld
Variations	AdRewardsStudy:NextPaymentDay
BraveDebounceStudy:Enabled
ConversionsStudy:NewDefaultPattern
Default1pBlockingStudy:Disabled
EphemeralStorageStudy:Enabled
ExtendedVariationsSafeMode4:Default4
ForceDisableBlinkFeatures:Enabled
MacCoreLocationBackendStudy:Enabled
NativeCosmeticFilteringStudy:Enabled
NavigationThreadingOptimizationsCompat:Disabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
RequestAdsEnabledApiStudy:Enabled
SpeedreaderReleaseStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Actually No
- Can you reproduce this issue with the nightly channel? Actually No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  Nope
- Does the issue resolve itself when disabling Brave Rewards? Nope
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by ryanbr** [comment]
Is `brave://flags/#brave-shields-v2` enabled? @OpenSourcery123
