### ISSUE TITLE
Option to Whitelist Ads

### ISSUE THREAD

**Issue by OpenSourcery123** [brave/brave-browser#21698]
Hoping for an easier way to support my favorite creators without having to give up privacy (whitelisting trackers)

Is this on your roadmap? Or is that the whole point of why BAT exists?

This also applies to mobile if possible :)

**Comment by Miyayes** [comment]
That's kind of the point of why BAT exists! You can Tip and Auto-Contribute to creators using the Brave Rewards system. There are actually a lot of creators in our platform (over a million registered), and lots of major sites like Wikipedia.org. 

You can earn BAT to tip to creators by enabling Brave Private Ads (which don't harm your privacy, and pay you). Or, you can fund your Brave Rewards balance yourself with BAT that you've purchased elsewhere.
