### ISSUE TITLE
Follow up to first run dialog on Windows

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#21694]
## Description 

Update text and button actions to reflect design.

## Design/Expected result
see: https://github.com/brave/brave-browser/issues/21694#issuecomment-1068576929

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Follow-up from https://github.com/brave/brave-browser/issues/21464

**Comment by bradleyrichter** [comment]
Title: Ready for the best privacy online?

Body: Set Brave as your default browser to get Brave’s privacy protections on every web page you open.  

No button: Maybe later

Yes button: Set Brave as default


Preview:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/13509546/158490669-92c0310a-895f-4104-951a-e74dbe3a477d.png">

**Comment by MadhaviSeelam** [comment]
Verified `In-Progress`

Brave | 1.38.70 Chromium: 100.0.4896.46 (Official Build) beta (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

**Comment by kjozwiak** [comment]
We'll need to re-test this via `1.37.x` as we're uplifting it into the `1.37.x` maintenance release via https://github.com/brave/brave-core/pull/12692.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.37.113 Chromium: 100.0.4896.88 (Official Build) (64-bit)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
