### ISSUE TITLE
Weird flash when closing dev tools 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#217]
## Description 
Weird flash when closing dev tools 

## Steps to Reproduce
   1. Build from source
   2. Visit icloud.com and enable Block all fingerprinting
   3. Open shields, right click on FP count and click inspect
   4. Hover above the contents in dev tool and close the dev tools
   5. Main window goes blank and then shows up 

 ## Actual result:
![devtools](https://user-images.githubusercontent.com/17010094/40401563-034bfcde-5e15-11e8-80aa-c67b34d668b4.gif)

## Expected result:
Main window should not flash 

## Reproduces how often: 
2/5 times

**Comment by bbondy** [comment]
@srirambv still an issue with latest master Release build?

**Comment by srirambv** [comment]
Issue fixed on master release build.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
