### ISSUE TITLE
0x Swaps should compare against CoinGecko for bad prices

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#21704]
In the back-end swap API we should check our CG proxy to compare the swap price to make sure the user is getting a good price within some threshold. Maybe 5%?

The back-end should add a hint to the front end that the price is not good.

**Comment by onyb** [comment]
This is now available in Swap V2. Head over to brave://wallet/swap to test.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/26632#issuecomment-1409052849
