### ISSUE TITLE
User cannot verify Rewards wallet (Uphold): infinite spinner and "processing" error modal

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#21719]
## Description 

1. User tries to verify Rewards wallet with Uphold
2. They get stuck on a "Your request is still being processed, please wait" error modal, with infinite spinner

<img src="https://user-images.githubusercontent.com/11497541/158696488-58f20bab-c947-4449-9213-5337becbcfbb.png" height=300px>

cc: @hollons @areckleh

**Comment by szilardszaloki** [comment]
[One of the users](https://community.brave.com/t/48-hours-for-the-brave-mobile-to-finish/353097) seems to have run into a temporary Uphold endpoint (`/me` perhaps) failure. Based on their `brave://rewards-internals` screenshot, they were already linked to Uphold when they filed the issue.

**Comment by szilardszaloki** [comment]
As far as @Areckleh's user, I'm waiting for their logs, but I suspect that this is the case there, too.

**Comment by szilardszaloki** [comment]
@Miyayes Let me know if there are other users hitting the same issue!

**Comment by szilardszaloki** [comment]
Took a look at the logs.
There's a good chance the issue is related to https://github.com/brave/brave-browser/issues/21057.

**Comment by Areckleh** [comment]
Hi I wanted to bring attention that this is affecting multiple Android users. 


Description: 
Android users who were previously connected with Uphold are now in a disconnected state. When trying to reconnect they are shown the processing request without outputting an error OR if they have Uphold app installed it will redirect and give "Something went wrong. Please try again". 

Support intervention:
Troubleshooting with asking users to temporarily uninstall Uphold app if this might possibly be the issue. No change.
Checking if their device passes SafetyNet. Pass and no change.
Requested logs for any insight what might be happening. Possibly attributed to https://github.com/brave/brave-browser/issues/21057

Here are a handful of cases found through support. 
https://bravesoftware.zendesk.com/agent/tickets/127807
https://bravesoftware.zendesk.com/agent/tickets/128408
https://bravesoftware.zendesk.com/agent/tickets/129631
https://bravesoftware.zendesk.com/agent/tickets/127815
https://bravesoftware.zendesk.com/agent/tickets/129393
https://bravesoftware.zendesk.com/agent/tickets/129286

**Comment by Miyayes** [comment]
This is probably just intermittently invalid Rewards profile issue on Android.
