### ISSUE TITLE
Bug in NTP push items off the page.

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#21717]
## Description 

Bug in NTP push items off the page.

![Screenshot_20220316-105924](https://user-images.githubusercontent.com/7606853/158679901-adb35015-a73c-4691-bcea-e49c99bad764.png)

![Screenshot_20220316-110033](https://user-images.githubusercontent.com/7606853/158679891-723c9e0c-4bf7-4a50-b0b3-85b8b89c98f6.png)

**Comment by deeppandya** [comment]
irrelevant at this time.
