### ISSUE TITLE
Handle case when update to unapproved transaction fails

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#21714]
Create any EVM transaction and enter a float value for gas limit.

<img width="321" src="https://user-images.githubusercontent.com/3684187/158659263-f2e4fb2b-9dc6-4a03-9e05-a4c763a1da3d.png">

The following two things are observed:
* Clicking on Save gives the impression that the unapproved transaction was successfully updated, whereas in fact it failed due to bad gas limit value.
* If we wait for a few seconds, the panel crashes, possibly due to some bad arithmetic operation when base fee is refreshed.

Expected results:
* only integer values are allowed for gas limit.
* user sees an error indicating that the save was not taken into account.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.108 Chromium: 101.0.4951.67 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/12979>brave/brave-core#12979</a></li>
         <li>Verified setting gas limit to 0 shows error message and disables <code>Send</code> button </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169107742-af27b2ee-0add-44a1-bb91-8815c2dc6286.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169107917-fae7290f-4f50-4e5c-b44a-e14e75942ad4.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169107869-88c2c21a-d66b-41f6-81e3-24dca1e44c79.png>
      </td>
   </tr>
</table>
