### ISSUE TITLE
set Show sidebar settings for release, beta, and nightly

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#21726]
## Description 

For release channel, set Show sidebar as Never.
For beta and nightly channels, set Show sidebar as Always.

## Expected result:

   1. New install or a create a new profile with a release build 1.37.x RC, beta and nightly build via hamburger menu.
   2. Notice no sidebar in release build but available to show or show on mouseover.
   3. Notice sidebar is default Show Always for beta and nightly channels.

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a. Starting with 1.37.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
Above issue requires `1.37.98` or higher for verification on `1.37.x`.

**Comment by LaurenWags** [comment]
Added `QA/Blocked` as this requires an RC with 1.37.x to test.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-browser/releases/tag/v1.37.105 is available

**Comment by MadhaviSeelam** [comment]
Verification `Passed`

Brave | 1.39.7 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

- Install 1.39.x
- Launch Brave
- Verified `Sidebar` is available is in `Normal Window`, `Private Window` and `Private Window with TOR`
- Verified  `Show Sidebar` is set to `Always` as a default in `Normal window` when right clicked on `Sidebar`
- Verified `Show Sidebar Enabled` entry is set to 'Always in `brave://settings/Appearance`
- Verified `Show Sidebar` is set to `Always` as a default in `Normal Window`
- Verified `Show Sidebar` is set to `Always` as a default in `Private Window`
-  Verified `Show Sidebar` is set to `Always` as a default in `Private Window with TOR`

ex1|ex2|ex3|ex4|ex5
---|---|---|---|---
<img width="952" alt="Nigtly-sidebar-always" src="https://user-images.githubusercontent.com/98358127/160215664-4e3b4dba-0d29-4d08-a847-bb0258ef8a3f.png">|<img width="953" alt="Nightly-TOR-Private-Hamburger-menu-sidebar" src="https://user-images.githubusercontent.com/98358127/160215688-5c1240c6-c166-49b7-a244-3189de941b41.png">|<img width="953" alt="Night-sidebar-showsidebar" src="https://user-images.githubusercontent.com/98358127/160215870-f9709c0c-8a2f-4cca-91d6-af85cbb75ccf.png">|<img width="958" alt="nightlyprivatewindow-showsidebar" src="https://user-images.githubusercontent.com/98358127/160215881-d749789d-1700-4dac-b8f7-e589f4c651e5.png">|<img width="953" alt="Nightly-TOR-Private-Hamburger-menu-sidebar" src="https://user-images.githubusercontent.com/98358127/160215891-b5baf3e7-5293-4a83-ae7e-47510e436e4f.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.106 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

----



Brave | 1.38.69 Chromium: 100.0.4896.46 (Official Build) beta (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

-----




Brave | 1.39.5 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)



`release` - `Show Sidebar -> Never` | Settings
----------|---------
<img width="1312" alt="Screen Shot 2022-03-27 at 6 33 25 PM" src="https://user-images.githubusercontent.com/387249/160312042-2770dc7e-e68c-4075-88e7-0da933eda719.png"> | <img width="1312" alt="Screen Shot 2022-03-27 at 6 33 40 PM" src="https://user-images.githubusercontent.com/387249/160312045-fbd88dcd-7f9f-4fba-9cec-a267c30dd976.png">


`beta` - `Show Sidebar -> Always` | Settings
--------|--------
<img width="1591" alt="Screen Shot 2022-03-27 at 6 34 10 PM" src="https://user-images.githubusercontent.com/387249/160312047-c0bb0e09-65b7-4425-ab1f-79b705bf0425.png"> | <img width="1312" alt="Screen Shot 2022-03-27 at 6 34 22 PM" src="https://user-images.githubusercontent.com/387249/160312048-2ab57b09-537d-4223-879e-9e54699d24b8.png">


`nightly` - `Show Sidebar -> Always` | Settings
---------|---------
<img width="1591" alt="Screen Shot 2022-03-27 at 6 34 35 PM" src="https://user-images.githubusercontent.com/387249/160312050-422e2a9c-932a-49c7-988b-724e94f2d49f.png"> | <img width="1312" alt="Screen Shot 2022-03-27 at 6 34 46 PM" src="https://user-images.githubusercontent.com/387249/160312052-cc71c6a6-5571-4bb9-863c-12b4cf5155cf.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.107 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Ubuntu 18.04 LTS


![image](https://user-images.githubusercontent.com/34715963/160472075-5ff7983c-205e-40fb-aad5-1413093acd48.png)|![image](https://user-images.githubusercontent.com/34715963/160472108-98bef0e0-7786-465b-acef-973e4c582ada.png)
-- | --

Verification passed on

Brave | 1.38.70 Chromium: 100.0.4896.46 (Official Build) beta (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Ubuntu 18.04 LTS


![image](https://user-images.githubusercontent.com/34715963/160472683-266e2948-83a7-4e1c-b64f-24e2cd5aa44f.png)|![image](https://user-images.githubusercontent.com/34715963/160472728-1051daab-e1b9-4e85-a4d9-95753207c45c.png)
-- | --

Verification passed on

Brave | 1.39.10 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Ubuntu 18.04 LTS


![image](https://user-images.githubusercontent.com/34715963/160473112-c9bab8a1-f68a-4849-b153-971ee7bb098d.png)|![image](https://user-images.githubusercontent.com/34715963/160473194-effeb52a-c3c3-49b6-a088-5fff8128f0f9.png)
-- | --
