### ISSUE TITLE
Add ability to Undo when cutting or deleting bookmark from bookmarks sidebar panel 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#21720]
## Description 

When cutting or deleting a bookmark or folder from the bookmarks panel, selecting Undo or command-Z/ctrl-Z does not undo the deletion of the bookmark or folder.

## Steps to Reproduce

   1. Open up the bookmarks sidebar panel. (1.37.x and higher)
   2. Add a folder and add a bookmark of your choice. 
   3. Open context menu via right click and cut or delete folder or bookmark of your choice. Notice that Undo does not restore the folder or bookmark from either cutting or deleting.

## Actual result:

Folder or bookmark is gone without ability to undo/restore on cut or delete of selection.

## Expected result:
Ability to undo a cut or delete of bookmarks and folders via shortcut on menu.

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @simonhong

**Comment by moisestohias** [comment]
Why on earth, no confirmation check before deleting a folder form the bookmakr is implemented.  
Many times I try to **add** a new bookmark, I accidentally click "**delete**" instead and delete the entire folder, which is silly. Please implement a confirmation feature.

**Comment by simonhong** [comment]
@rebron WDYT about delete confirmation?

**Comment by rebron** [comment]
<img width="407" alt="Screenshot 2024-03-13 at 9 03 17 AM" src="https://github.com/brave/brave-browser/assets/5951041/0c749561-88cc-4fc4-b156-65c8dbf4ac93">
Closing as stale. Undo functionality is available with the newer side panel.
