### ISSUE TITLE
Yearn.finance (YFI) token misspelled in "Buy" token list

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#21721]
## Description 

Yearn.finance coin is displayed as Year.finance in the "Buy" tab of the buy/send/swap widget

## Steps to Reproduce

   1.  Unlock wallet
   2. Click "Buy"
   3. Click the asset dropdown button
   4. Observe Yearn.finance mispelling

## Actual result:

![Screen Shot 2022-03-16 at 1 16 30 PM](https://user-images.githubusercontent.com/30185185/158702418-348d15a3-dbac-4104-8746-11de56faac7c.png)

## Expected result:
Yearn.finance should be displayed instead of "Year.finance"

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.36.112 Chromium: 99.0.4844.51 (Official Build) (arm64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.3 (Build 21E230)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified token name is correctly spelt</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/22683>#22683</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/166638723-d982c8af-daaf-4e1c-ba02-72a1f9f2498c.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/166637959-e46d54b0-026d-4f99-94b8-1630ea1c26f7.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/166638033-74f89c86-bef3-4952-b621-9fd88036d255.png>
      </td>
   </tr>
</table>
