### ISSUE TITLE
Can't Make A Search In Tor Window + Unsolvable CAPTCHAS

### ISSUE THREAD

**Issue by Nihal247** [brave/brave-browser#21730]
## Description 
It's very difficult to make a search in Tor window from the address bar since Brave Search has become the default search engine in Tor window. Every search gets stuck in an endless loop of unsolvable CAPTCHAs. Either roll back to the previous settings or give users the option to chose any other search engine.

## Steps to Reproduce

   1. Open a Tor window.
   2. Perform any search in the address bar.
   3. Endless loop of CAPTCHAs need to be solved.

## Actual result:

A search can't be made + Brave Search CAPTCHAs are unsolvable.

https://user-images.githubusercontent.com/80682093/158786556-d4b288e6-8fa3-4457-94c5-c364d92d4127.mp4

## Expected result:
Should perform a regular search just like in Normal and Private windows.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.36.116

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by GeetaSarvadnya** [comment]
Strange! @Nihal247 Could you let us know the information below:
- which platform are you seeing this issue on? 
- Is this Windows OS? 
- could you also mention your region, please?  
- are there any extensions installed in your browser? If so, please mention the name of the extensions
- Is this a clean profile or an upgraded profile?

**Comment by Nihal247** [comment]
> Strange! @Nihal247 Could you let us know the information below:
> 
> * which platform are you seeing this issue on?

Windows 11 22000.556
> * Is this Windows OS?

Yes!
> * could you also mention your region, please?

India
> * are there any extensions installed in your browser? If so, please mention the name of the extensions

Yes, Bitwarden is installed
> * Is this a clean profile or an upgraded profile?

It's a clean profile.

**Comment by GeetaSarvadnya** [comment]
cc: @rebron @simonhong

**Comment by GeetaSarvadnya** [comment]
@Nihal247 Could you please check and let us know whether you are able to clear/resolve the captcha or not? Thanks!

**Comment by Nihal247** [comment]
> @Nihal247 Could you please check and let us know whether you are able to clear/resolve the captcha or not? Thanks!
> 
@GeetaSarvadnya I've reproduced the issue multiple times now, and I can perform a search most of the times now , but not sure if the CAPTCHAs needs to be improved, so I'll close this one, and will recreate a CAPTCHA issue if I continuously face it, and thanks for your quick response!

**Comment by GeetaSarvadnya** [comment]
@Nihal247 Glad to hear that you can perform the search in TOR now. I will let the dev team about it. Thanks!

@remusao User reported that they can perform the search in TOR but still they reproduce the Captcha issue couple of times.

**Comment by remusao** [comment]
Thanks for the feedback @Nihal247 and @GeetaSarvadnya,

To make sure I understand correctly, when you say that you can perform a search most of the time and that the issue could still be reproduced multiple times, I understand that from time to time solving the captcha redirects to having to solve another captcha instead of redirecting to the search results (the issue). Is that correct?

**Comment by Nihal247** [comment]
> To make sure I understand correctly, when you say that you can perform a search most of the time and that the issue could still be reproduced multiple times, I understand that from time to time solving the captcha redirects to having to solve another captcha instead of redirecting to the search results (the issue). Is that correct?

Yes, you understood it correctly :)

**Comment by remusao** [comment]
Thanks for confirming, we're looking into it.
