### ISSUE TITLE
Display a confirmation screen after transaction is approved

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#21733]
Additionally display the provider error if the transaction approval failed.

**Comment by Uni-verse** [comment]
Verified on

```
Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.1 (Build 21C52)
```
Error | Recent Txn | Submitted
-|-|-
![Screen Shot 2022-04-12 at 11 03 32 AM](https://user-images.githubusercontent.com/17885425/163027551-bb01c629-ad0f-42f2-a2c1-3f25f1dc3de3.png) | ![Screen Shot 2022-04-12 at 11 03 48 AM](https://user-images.githubusercontent.com/17885425/163027555-c5bf866f-2bb3-4fb1-abb8-98feceb5e226.png) | ![Screen Shot 2022-04-12 at 11 05 53 AM](https://user-images.githubusercontent.com/17885425/163027556-1e1de197-f975-47af-b2d3-8006fe85fe34.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.38.100 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | `ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}`
OS | Linux

- Verified steps from [brave/brave-core#12653](https://github.com/brave/brave-core/pull/12653)
- Verified confirmation screen is persisted after a transaction
- Verified error has a info icon next to it
- Verified hover over the info icon shows the error message in tooltip
- Verified error info is not persisted for ever. Is removed when the panel is closed after a transaction 
- Encountered [#22394](https://github.com/brave/brave-browser/issues/22394)

Error | Error Info | Submitted | Confirmed | Recent Trx
-- | -- | -- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/164014710-b0ea8191-fe70-4187-bb08-2f2bf17d9b29.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/164019771-be40d1c6-a4f5-4dcf-86b8-5e56354ee75d.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/164014664-f64e58e5-56b8-46c6-ad76-c29b48a2b90f.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/164014849-c48129f3-7005-4164-a636-683a7894d2c9.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/164014771-7c5d45df-8236-48ad-93e8-aa37990550b8.png>

-----------
Verification passed on 

Brave | 1.38.100 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | `ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}`
OS | Windows 11 Version 22H2 (Build 22572.201)

- Verified steps from [brave/brave-core#12653](https://github.com/brave/brave-core/pull/12653)
- Verified confirmation screen is persisted after a transaction
- Verified error has a info icon next to it
- Verified hover over the info icon shows the error message in tooltip
- Verified error info is not persisted for ever. Is removed when the panel is closed after a transaction 
- Encountered [#22394](https://github.com/brave/brave-browser/issues/22394)

Error | Error Info | Submitted | Confirmed | Recent Trx
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/164018674-3f22e4d6-ee77-4beb-bcff-0007d1c5a58a.png) | ![image](https://user-images.githubusercontent.com/17010094/164018656-6d7e49aa-e85a-434b-83e1-b92a17b42b61.png) | ![image](https://user-images.githubusercontent.com/17010094/164018718-a2dd33a6-f0f7-40d1-95ea-899deaa99857.png) | ![image](https://user-images.githubusercontent.com/17010094/164018742-c3aa666b-a4b3-421f-83bd-5c43d1059927.png) | ![image](https://user-images.githubusercontent.com/17010094/164018697-96eee710-3e07-4693-bf7c-6c99dbe3aef4.png)
