### ISSUE TITLE
Loop in VPN panel UX when can't connect to server

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#21732]
Need an option to go back to the 'home' state of the panel
![image](https://user-images.githubusercontent.com/71029/158830032-e920bc97-efda-40a2-a93c-02819d5a73cf.png)

**Comment by nullhook** [comment]
self note: might need to explicitly call `resetConnectionState` so main panel doesn't have connection not allowed note.

**Comment by aguscruiz** [comment]
Design for this error state is here:
https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/Desktop-VPN?node-id=236%3A15620&t=6kIBZ0Cf1WqJwzMe-1

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.5 (Build 20G1225)

### Steps:
1. installed `1.51.77`
2. launched Brave
3. loaded `account.brave.software` ([staging still has issues](https://bravesoftware.slack.com/archives/C021S0FN3V1/p1680708821136979?thread_ts=1679338016.337709&cid=C021S0FN3V1), currently)
4. purchased, configured, and connected to `BraveVPN`
5. disabled `Wi-Fi`
6. let it go to `Disconnected`
7. clicked on `USA (West)`
8. chose another location and clicked `Connect`
9. confirmed I got into the `Couldn't connect to server` dialog
10. clicked `< Brave VPN`
11. confirmed I was returned to the server-region selection
12. confirmed I could change regions and reconnect

example | example | example
---------|----------|---------
<img width="1362" alt="Screen Shot 2023-04-05 at 4 02 01 PM" src="https://user-images.githubusercontent.com/387249/230230757-b41e08b2-e9a9-4525-8efc-3a0d699db408.png"> | <img width="1362" alt="Screen Shot 2023-04-05 at 4 02 13 PM" src="https://user-images.githubusercontent.com/387249/230230777-69e5579f-b02f-49a1-a5ef-158aa1d16c5b.png"> | <img width="1362" alt="Screen Shot 2023-04-05 at 4 04 08 PM" src="https://user-images.githubusercontent.com/387249/230231171-b885135b-a0f7-4591-8310-3c1f9a336cbb.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.51.84 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```


### Steps:
1. installed `1.51.77`
2. launched Brave
3. loaded `account.brave.software` ([staging still has issues]
4. purchased, configured, and connected to `BraveVPN`
5. disabled `Wi-Fi`
6. let it go to `Disconnected`
7. clicked on `USA (West)`
8. chose another location and clicked `Connect`
9. confirmed I got into the `Couldn't connect to server` dialog
10. clicked `< Brave VPN`
11. confirmed I was returned to the server-region selection
12. confirmed I could change regions and reconnect

example | example | example
---------|----------|---------
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/98358127/231270180-1440d31f-c0c3-4512-8075-21beb7bf5199.png">|<img width="1362" alt="image" src="https://user-images.githubusercontent.com/98358127/231270256-765c6ef0-f5c7-42e8-a3c9-b2ae1792a5d7.png">|<img width="1362" alt="image" src="https://user-images.githubusercontent.com/98358127/231270278-e3dd8875-912b-43e9-af4c-20261a138bc6.png">
