### ISSUE TITLE
Unable to launch x86-64 nightly build of CR100 on macOS

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21743]
## Description 

Unable to launch x86-64 nightly build of CR100 on macOS (crashes and permissions dialogs)

Found while trying to test https://github.com/brave/brave-browser/issues/21739

## Steps to Reproduce

   1. download `https://brave-jenkins-build-artifacts.s3.amazonaws.com/test-brave-browser-build-macos-x64/618/Brave-Browser-Nightly-x64.dmg`
   2. double-click to extract
   3. run the installer
   4. launch Brave

## Actual result:

example | example
---------|--------
<img width="372" alt="Screen Shot 2022-03-17 at 2 28 52 PM" src="https://user-images.githubusercontent.com/387249/158898696-1a2fb07b-d24b-45e6-937a-5fc3eb7e6e3c.png"> | <img width="1112" alt="Screen Shot 2022-03-17 at 2 25 15 PM" src="https://user-images.githubusercontent.com/387249/158898729-89d41f11-ef6e-4d9a-bc8e-5380dc132ef4.png">

## Expected result:

No crash, and Brave launches

## Reproduces how often: 

100%

## Brave version (brave://version info)

- Can you reproduce this issue with the current release? `no`
- Can you reproduce this issue with the beta channel? `no`
- Can you reproduce this issue with the nightly channel? `no`

cc @kjozwiak @emerick @LaurenWags

**Comment by stephendonner** [comment]
FWIW, it's also happening with `https://brave-jenkins-build-artifacts.s3.amazonaws.com/test-brave-browser-build-macos-arm64/152/Brave-Browser-Nightly-arm64.dmg`

**Comment by stephendonner** [comment]
@emerick did you want to close this one out with the info about the signing-key mishap?

**Comment by emerick** [comment]
The QA test job for Mac was accidentally run with the "CI" keychain instead of the "Release" keychain, resulting in an invalidly signed app. @mkarolin reran the job with the correct keychain and we were good.

Will follow up with @mihaiplesa to see if it would make sense to make "Release" the default (or even only) choice.
