### ISSUE TITLE
Allow to send FIL transactions in webui

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#21748]
## Description 

In order to send FIL we need to support it in sending views and allow to get balances separately for specific coin

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12667>brave/brave-core#12667</a></li>
         <li>Verified able to perform ETH transaction successfully</li>
        </ul>
      </td>
   </tr>
</table>

**Comment by bbondy** [comment]
marking as exclude since it won't be released until 1.40.x to users
