### ISSUE TITLE
AT&T chat support not working even with shields down

### ISSUE THREAD

**Issue by J-Reis** [brave/brave-browser#2174]
## Description 
att.com online support does not work using Brave.

## Steps to Reproduce
   1. navigate to att.com & log into existing account
   2. navigate to any account summary page
   3. Select 'Chat Available' in lower right corner

## Actual result:
Pages load, normally but no chat box ever appears

## Expected result:
'Chat Available' box in lower right allows launching of support chat dialogue

## Reproduces how often: 
always

## Brave version (brave://version info)
Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux

### Reproducible on current release:
I don't know, only have release channel installed.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional Information
Screenshot show expected result from Chrome (70.0.3538.102) and missing chat option in Brave (0.56.12)
![2018-11-17_05-14-24pm](https://user-images.githubusercontent.com/23666144/48666726-10ec2580-ea8d-11e8-822c-af3b1da0af84.png)
![2018-11-17_05-13-51pm](https://user-images.githubusercontent.com/23666144/48666727-10ec2580-ea8d-11e8-8ebf-b4ac3a6b9a8f.png)

**Comment by ryanbr** [comment]
@J-Reis  Hey, is this issue still valid in Brave release?
