### ISSUE TITLE
Cannot use "Sign in with Google" option for app.mysms.com

### ISSUE THREAD

**Issue by J-Reis** [brave/brave-browser#2175]
## Description 
mysms web app cannot be logged into using Brave if mysms account uses a Google account for it's login. Selecting the "Sign in with Google" option offered on the mysms page, results in a separate window being launched, persisting for a few moments without content, then closing. No login is performed and the mysms app cannot be accessed.

In Chrome/Firefox: selecting "Sign in with Google" opens a separate window in which active Google accounts are displayed as a list, and an appropriate set of credentials can be selected. The window then closes and loading of the mysms web app proceeds as expected.

## Steps to Reproduce

   1. having an active mysms account & mobile app
   2. navigate to app.mysms.com
   3. select "Sign in with Google"

## Actual result:
A small window pops up briefly then disappears.

## Expected result:
Ability to select appropriate Google account and proceed with logging in to mysms web app.

## Reproduces how often: 
always

## Brave version (brave://version info)
Brave	0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
Revision	0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS	Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Unknown I only have release channel installed.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional Information
N/A

**Comment by eljuno** [comment]
+1s from Community with different websites https://community.brave.com/t/cant-sign-in-to-any-website-using-google-sign-in/38109?u=eljuno

> any website offering Google sign-in e.g. getpocket.com or soundcloud.com

**Comment by ryanbr** [comment]
can you confirm @J-Reis  this was resolved? Just tested in Brave release, seems okay. Got the google popup without issue.

**Comment by J-Reis** [comment]
Apologies. Yes, to my recollection this has been resolved for a few releases/updates now & has been working "as expected" for some time.

**Comment by gendolookin** [comment]
Has this problem returned for anyone else?  I tried to login to geek.wish.com with an error using brave, but worked with firefox. I see this error: An error occurred with Google! Please try again.

Also tried with getpocket.com  Google sign in popup works, choose the account I want to use. Popup disappears but never logs in.

**Comment by bsclifton** [comment]
@gendolookin we do see to have a Google Auth problem at the moment, which we're tracking with https://github.com/brave/brave-browser/issues/5869 (in case you'd like to subscribe)

**Comment by XxxMikeyxxX** [comment]
The pop up does appear, but it doesn't seem to carry the authentication token over when you return to the requesting website. On thingiverse I use google log in, but I can't use Brave on anything I use google (which is everywhere it is available). It's more secure than remembering passwords for each site as the site only has a token that doesn't show your password.
