### ISSUE TITLE
Item edit feature needs to be provided when same item (settings) is added multiple times

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21751]
## Description 

Item edit feature needs to be provided when same item (settings) is added multiple times

## Steps to Reproduce

   1. Clean profile 1.37.98
   2. Navigate to brave://settings
   3. Click on each side bare menu in the settings page and add each page to the sidebar
   4. Mouse hover on the added item in the sidebar
   5. Tooltip `Settings` is shown for each item instead of a particular page ( e.g brave://settings/getStarted, brave://settings/appearance)

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/158997576-1babc715-f45e-4932-8cda-4776c1dffc19.png)
![sidebar_add settings](https://user-images.githubusercontent.com/38657976/158998325-281ac9b0-c16f-45f8-95ff-aafd532413a8.gif)

## Expected result:
Item edit feature needs to be provided when same item (settings) is added multiple times

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.37.98 Chromium: 99.0.4844.74 (Official Build) beta (64-bit)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 10 Version 21H2 (Build 19044.1586)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @simonhong

**Comment by rebron** [comment]
I'm going to close this as a wontfix. I don't think we'll see folks adding Settings in the sidebar.
