### ISSUE TITLE
VPN doesn't connect on first try

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#21755]
https://user-images.githubusercontent.com/71029/159056962-3e54d106-6970-4aab-b493-3c72b087d70d.mov

**Comment by bsclifton** [comment]
@mattmcalister watched the clip like 5 times; not exactly sure what's going on?

It won't connect unless you hit the toggle switch? Are you just seeing something weird when clicking the VPN button itself?

**Comment by mattmcalister** [comment]
Updated the video. It should be clearer now. After opening the browser I then click the VPN icon. Then I click the Connect button. It fails. Then I try again and it works. That first failure after a new browser session happens every time.

**Comment by mattmcalister** [comment]
Closing. I haven't seen this in a long time.
