### ISSUE TITLE
VPN panel has a flickering issue

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#21754]
https://user-images.githubusercontent.com/71029/159007992-8bf74fb4-ef1d-4d1d-8bc3-375e62f1de24.mov

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.62 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 11.6.7 (Build 20G630)



#### See (complete) verification notes over in https://github.com/brave/brave-browser/issues/22882#issuecomment-1183528850.
