### ISSUE TITLE
Search domains for RSS feeds to add in Your Sources

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#21768]
Brave News allows users to add RSS feeds by feed URL. Users should be able to add a domain which then triggers a search for any autodiscovery feed URLs at that domain.

**Comment by stephendonner** [comment]
Took a stab at this, but marking `QA/Blocked` until we've got a few more working multple-feed sources for autodiscovery (`https://news.com` example from test plan isn't working).

Asked in https://bravesoftware.slack.com/archives/CU56GUJ1H/p1651081419613779

**Comment by stephendonner** [comment]
> Took a stab at this, but marking `QA/Blocked` until we've got a few more working multple-feed sources for autodiscovery (`https://news.com` example from test plan isn't working).
> 
> Asked in https://bravesoftware.slack.com/archives/CU56GUJ1H/p1651081419613779

@timchilds gave me a couple multiple-feed sources to check out; no longer blocked:

https://www.fightmag.com.au/
https://talksport.com/sport/boxing/

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 

Brave | 1.39.83 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.4 (Build 21F5063e)


Shared steps:
1. install 1.39.83
2. launch Brave
3. open a new-tab page
4. scroll down
5. click on `Show Brave News`
6. click on `Customize`
7. enter feed URL
8. click on `Add source`
9. click on individual `+` icons for each feed


URL | results | added | in Brave News
----|---------|-------|----------------
fightmag.com | <img width="1312" alt="Screen Shot 2022-04-27 at 5 41 23 PM" src="https://user-images.githubusercontent.com/387249/165653997-28052b21-cd01-47d3-8022-b8dffa221188.png">  | <img width="1312" alt="Screen Shot 2022-04-27 at 5 42 58 PM" src="https://user-images.githubusercontent.com/387249/165653949-7ccc0d47-c961-44ad-8c79-9bf35ab11e3c.png"> | <img width="1312" alt="Screen Shot 2022-04-27 at 5 42 18 PM" src="https://user-images.githubusercontent.com/387249/165654044-afeaaf9a-be9e-4e74-955f-5660347be2a9.png">
talksport.com/sport/boxing | . | . | 
theisleofthanetnews.com | . | . | 
stephendonner.wordpress.com | <img width="1264" alt="Screen Shot 2022-04-27 at 5 32 12 PM" src="https://user-images.githubusercontent.com/387249/165653286-c42fa19c-b431-4f7f-a5e3-0872717e47e1.png"> | <img width="1264" alt="Screen Shot 2022-04-27 at 5 31 48 PM" src="https://user-images.githubusercontent.com/387249/165653277-9cae7746-c776-4180-88f9-7b5a2e881a7e.png"> | <img width="1264" alt="Screen Shot 2022-04-27 at 5 35 43 PM" src="https://user-images.githubusercontent.com/387249/165653289-a0df8106-5b84-431b-9426-d4256d0426ab.png">




Filed: https://github.com/brave/brave-browser/issues/22583
