### ISSUE TITLE
Display swap order sources and routing information

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#21761]
Swap order sources and their proportion can be accessed from the `sources` field of the full quote. The source names however must be mapped to human readable names or logos.

For order route, the information is available in the `fillData` field. Special care must be taken to handle case when there are multiple sources and complex order route (perhaps for exotic token pairs).

**Paraswap inspiration:**
<img src="https://user-images.githubusercontent.com/3684187/159023128-013ba47d-e18b-4773-93a9-cd5101fdd817.png">

⚠️ For us to display the route in the panel during transaction confirmation, it is essential that the quote is refreshed live within the panel, which is not the case today. Quotes on fast chains become obsolete very quickly, including the route.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/26632#issuecomment-1409052849
