### ISSUE TITLE
Crash Report (Brave crashing on all Extentions interactions of on/off) (Can't Remove Extentions) (Extentions 'active' inteactions crash brave)

### ISSUE THREAD

**Issue by hkdroidin** [brave/brave-browser#21776]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.36.116  Chromium: 99.0.4844.74
Operating System: Windows NT 10.0.19043

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Extensions being removed / disabled ; flicking any settings on/off
2. Brave Browser >Rewards button at the top being clicked on. 
3. Since 16th anything related to Extentions Or Brave fuctions/features have been causing me forced closing/crashs
4. Especially security extensions since they're actively reacting and when second they interact, it crashs,

Had no issues yesterday 16th till midnight getting off, Now today getting on I noticed crashs from Extensions or brave reacting to interaction of either of each other. I noticed once i switched Profile, crash stopped. but second I installed a new extension on a new profile no matter the extension it doesn't want to be removed or disabled/buttons features switched on/off, any interaction too it. Second you click remove/button switch it crashs/closes all Brave.exe opened. 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/52260200-8c38-e807-0000-000000000000

**Comment by rebron** [comment]
@hkdroidin Thanks for the report. Can you update to our latest 1.36.119 and see if you're still getting this crash.
