### ISSUE TITLE
[hackerone] show eTLD+1 prominently in wallet

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#21787]
https://hackerone.com/reports/1514823

see thread here: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1647647313657369

**Comment by diracdeltas** [comment]
expected behavior:

1. wallet permissions panel(s) should show the full hostname of the site wrapped, not clipped
2. the eTLD+1 of the hostname should be in bold

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.96 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22616.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12701>brave/brave-core#12701</a></li>
         <li>Verified eTLD+1 is shown in bold on panel while transacting with a Dapp</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168007918-82efd624-9c2c-4431-8d92-db89103469c3.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/168016041-f6a92658-b1e8-4f22-82f2-44b9918b8f19.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168010643-396c147b-c9e6-4059-9cb8-438ff6b43f21.png>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168007843-76e3a989-db23-4441-98b9-cde2f9d72de6.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/168016063-444ffa69-7a24-4667-8325-964e09323f71.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168010729-0fafeed2-cbc8-4312-b45c-218673db386f.png>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168007614-2aa3eb43-62e0-429c-90ed-ca675928ab6c.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/168016101-7fe0e859-90b3-48e1-9a3b-775c5d1adb02.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168010775-ef369c84-19cd-46ff-9327-6280de2d4b0f.png>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168007638-45479e97-2717-4412-8ddf-c3d89d46f01c.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/168016122-7803ce36-f399-4038-a92c-7c7d74edf537.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168010806-e4961c6a-463c-4773-981e-1189b7e4dcae.png>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168008013-024f132c-e38d-424f-aec0-ac3de2f03e8d.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/168016142-9fa674e7-1fb7-4861-b3d5-f60d418439d4.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168010827-3c4b0e0d-e439-44e3-8439-655658602de2.png>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168008104-fcb6b020-7b2b-4921-9152-352b9796a9dc.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/168016155-b53041b2-ffeb-45c0-8e74-4fcc01deca67.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168010844-17e96ebb-150b-40d0-82ee-7b1482e31186.png>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168008342-95c37cd2-30ce-4b8c-8ad3-9e5a578548ff.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/168016185-29be35ca-26e1-4897-84f7-1f490896a60d.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168010868-2a762357-6ec2-45c9-9f6f-4533dfe43d10.png>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168008392-eb8796b3-a507-4870-88e9-60ab6a1a9789.png>
      </td>
      <td><img width=900 src=https://user-images.githubusercontent.com/17010094/168016210-c3531252-796e-4eea-8dfd-98f028c42b1d.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168010885-d972e237-b661-40f8-a917-58cea322a71c.png>
      </td>
   </tr>
</table>
