### ISSUE TITLE
The toggle of `Auto-redirect AMP pages` is visible inside other pages at `brave://settings/privacy`

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#21788]
## Description 

The toggle of the new `Auto-redirect AMP pages` feature is currently visible in all other pages at the `brave://settings/privacy` section.

## Steps to Reproduce

   1. Install `Brave Nightly`.
   2. Open `brave://settings/privacy`.
   3. Open either of the following pages: `Cookies and other site data`, `Security`, `Site and Shields Settings` (the toggle will be visible in all site settings pages too).
   4. Take a look at the right corner of the newly opened page, where the search functionality is located.

## Actual result:

![actual](https://user-images.githubusercontent.com/20608253/159231190-363fd9d2-31e4-42fd-870b-f04e4ef76211.png)

Clicking on the toggle will enable/disable `Auto-redirect AMP pages` feature at `brave://settings/privacy`.

## Expected result:
![expected](https://user-images.githubusercontent.com/20608253/159231232-61d1de7f-9390-4260-b9b1-c64fe0f87a2b.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.57 Chromium: 99.0.4844.74 (Official Build) nightly (64-bit)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

CC: @ShivanKaul

**Comment by kjozwiak** [comment]
Reproduced on `Win 11 x64` using the following build(s):

```
Brave | 1.38.57 Chromium: 99.0.4844.74 (Official Build) nightly (64-bit)
--- | ---
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 11 Version 21H2 (Build 22000.556)
```

```
Brave | 1.38.62 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)
```

**`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|---------------
![securityToggle](https://user-images.githubusercontent.com/2602313/159416967-ff93b31e-3081-4af7-93d1-315601244136.png) | ![cookieToggle](https://user-images.githubusercontent.com/2602313/159416976-a6eeb1de-bfcf-45da-8cb0-fa8c23f767a3.png) | ![cookieToggle2](https://user-images.githubusercontent.com/2602313/159416980-f786e6d7-daac-4a10-870b-fdd41095e613.png) | ![insecureContentToggle](https://user-images.githubusercontent.com/2602313/159416989-d98a048b-995d-4f9e-9ed4-9e331e2d1050.png)

**Comment by Tonev** [comment]
@kjozwiak 

Excuse me for the off-topic, but I have to ask since I'm not aware - is it already time for `Auto-redirect AMP pages` to be translated in other languages? The current issue is about the feature so I would like to know if I should to open a follow up issue regarding my question. Thank you :+1:

**Comment by kjozwiak** [comment]
Removing this from the `1.38.x` milestone as it's still opened and not labelled as `release/blocking`. @ShivanKaul once https://github.com/brave/brave-core/pull/12694 lands into `master` (which is `1.39.x` now), you'll need to move this issue `1.39.x` as well. We'll want to uplift into `1.38.x` as well.

**Comment by kjozwiak** [comment]
> @kjozwiak
> 
> Excuse me for the off-topic, but I have to ask since I'm not aware - is it already time for `Auto-redirect AMP pages` to be translated in other languages? The current issue is about the feature so I would like to know if I should open a follow up issue regarding my question. Thank you 👍

Believe we'll get translations for the above once we start doing translations for `1.38.x` but I could be wrong. CCing @mkarolin @rebron who know a more about the translation process.

**Comment by kjozwiak** [comment]
Above will require `1.38.69` or older for `1.38.x` verification.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.39.7 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed `Auto-redirect AMP pages` toggle is in the right place, and works
Confirmed no more rogue `De-amp` pref entries

`Settings` | `Cookies and other site data` | `Security` | `Site and Shields Settings`
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2022-03-28 at 11 49 31 AM" src="https://user-images.githubusercontent.com/387249/160467212-c547eb98-22b6-470f-84fa-1f9c6dff0b45.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 11 51 18 AM" src="https://user-images.githubusercontent.com/387249/160467224-39810000-de10-4805-b385-4256e683430a.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 11 51 29 AM" src="https://user-images.githubusercontent.com/387249/160467229-df0242b3-720c-42a3-8fc3-02d7b8776a87.png"> | <img width="1312" alt="Screen Shot 2022-03-28 at 11 51 36 AM" src="https://user-images.githubusercontent.com/387249/160467234-050870c5-78d4-44ce-bf8d-9eae3652a4dc.png">
