### ISSUE TITLE
DApps: Address the security concern to show eTLD+1 of max 255 characters (site+domain) and show site origin in Panels

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#21798]
## Description 
- Update the android implementation and UI for eTLD+1 (site+domain) in `brave_permission_dialog` layout and delegate as per [eTLD+1 standards](https://github.com/brave/brave-browser/issues/21787#issuecomment-1074806905). The 255 chars limit should have no issue but verify it with real data [-done].
Make sure the [discussed details are being shown](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1647984512691899?thread_ts=1647647313.657369&cid=C023VS4HJ6Q).
- Show origin on all request panels, equivalent to desktop issue https://github.com/brave/brave-browser/issues/21904 or iOS https://github.com/brave/brave-ios/issues/5188

## Steps to reproduce 

   1. Create a DApp wallet connectivity request with lengthy eTLD+1
   2. A eTLD+1 with 255 chars (max) is not bold and origin is not displayed 

## Actual result 
A  eTLD+1 is not bold in DApps permission panel and origin is not displayed

## Expected result
- [Show eTLD+1 should be bold and completely visible](https://github.com/brave/brave-browser/issues/21787#issuecomment-1074806905)
- Origin info should be displayed

## Issue reproduces how often 
Not yet merged in master

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? NA

### Additional information

Also add/replace the root view with `ScrollView` for lengthy values.

cc: @diracdeltas

**Comment by diracdeltas** [comment]
@Pavneet-Sing actually the maximium allowed length for a label in DNS is 63 characters. so eTLD+1 won't be much more than ~70 characters total.

we should always make sure to show the eTLD+1 clearly so that it's visible without any scrolling.

for subdomains, which can be a lot longer, scrolling makes sense to me

cc @darkdh @nuo-xu

**Comment by diracdeltas** [comment]
and actually the total length of the domain should be <255 characters according to the DNS spec; however i'm not sure if there are workarounds. https://serverfault.com/questions/580249/is-there-a-maximum-subdomain-depth

**Comment by Pavneet-Sing** [comment]
Got it, then length of 255 character will not be a concern on Android without scroll. Possible UI adapter could be is to show a warning or something, when the length exceeds and if it too long then at-best we can make the whole screen scroll able and keep the whole domain and subdomain visible (instead of defining a specific height of the domain and subdomain section).

**Comment by kjozwiak** [comment]
The above requires `1.40.78` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.40.101
- Verified steps from [brave/brave-core#12701](https://github.com/brave/brave-core/pull/12701)
- Verified eTLD+1 is shown prominent on panel
- Logged [#23513](https://github.com/brave/brave-browser/issues/23513)

Connect Account | Approve Tx | Approve Network | Switch Network | Sign Message | Encryption message
-- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/174057651-f6ec455c-7dcf-4eb2-b299-f1ad9d2271c1.png) | ![image](https://user-images.githubusercontent.com/17010094/174057695-13ba7388-a70a-407d-9d82-5b8e76ca53f3.png) | ![image](https://user-images.githubusercontent.com/17010094/174057715-e90e1a43-7fa5-445c-87e7-aa6d6d1a78b2.png) | ![image](https://user-images.githubusercontent.com/17010094/174057772-aed65d83-d892-49d8-8c51-22674b787d1f.png) | ![image](https://user-images.githubusercontent.com/17010094/174057799-0a30a16e-caab-46bb-ab0c-d10fa312afa0.png) | ![image](https://user-images.githubusercontent.com/17010094/174057825-d0d44ce7-7e9d-4e4a-915c-29439ceb32f6.png)

Verification passed on Samsung Tab A with Android 10 running 1.40.101
- Verified steps from [brave/brave-core#12701](https://github.com/brave/brave-core/pull/12701)
- Verified eTLD+1 is shown prominent on panel
- Encountered [#23513](https://github.com/brave/brave-browser/issues/23513) & [#23514](https://github.com/brave/brave-browser/issues/23514)

Connect Account |  Approve Network | Switch Network | Connected State | Sign Message | Encryption message
-- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/174059318-6d69131b-a41e-4f02-b124-f489116464bf.png) | ![image](https://user-images.githubusercontent.com/17010094/174059338-1625fddf-00e7-499f-bd99-a623a6c91070.png) | ![image](https://user-images.githubusercontent.com/17010094/174059360-1f926e35-9ca7-4178-ae41-e4d96ecb720a.png) | ![image](https://user-images.githubusercontent.com/17010094/174059394-d6e4f67c-512a-4455-a134-4c6e21a82c7f.png) | ![image](https://user-images.githubusercontent.com/17010094/174059449-e55fc34d-4c64-49f6-8750-cb63622071f3.png) | ![image](https://user-images.githubusercontent.com/17010094/174059463-db0b0365-fd97-4771-9cbb-11787fb21758.png)
