### ISSUE TITLE
Removing a custom filter doesn't restore the blocked element until a browser restart

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#21797]
## Description 

Discovered an issue with Brave's `Block element` feature in `Beta` and `Nightly`.

If a user would like to restore a blocked element, they will have to restart the browser in addition to deleting the entry from the `Custom Filters` field at `brave://adblock/`.

## Steps to Reproduce

   1. Install `Brave Beta` or `Brave Nightly`.
   2. Open a random website, for example `brave.com`.
   3. Block an element using Brave's `Block element` feature.
   4. Open `brave://adblock`.
   5. Delete the entry from the `Custom Filters` field.
   6. Refresh the website you used in the second step.

## Actual result:

https://user-images.githubusercontent.com/20608253/159415115-7f0b947a-29f3-4350-99af-a23f58271253.mp4

## Expected result:

https://user-images.githubusercontent.com/20608253/159344461-6e431035-0d9b-42ea-9afd-00ad23c752d0.mp4

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.37.97 Chromium: 99.0.4844.74 (Official Build) beta (64-bit)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

<html>
<body>

Brave | 1.38.60 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

CC: @antonok-edm

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue on `Windows 10 x64 - 1.42.68`

```
Brave | 1.42.68 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```

**Comment by ryanbr** [comment]
Should be resolved now, we added `"Save"` button. Couldn't repo this. Feel free to re-open if its still an issue. @Tonev
