### ISSUE TITLE
Unable to join a Sync Chain on iOS (not enough words)

### ISSUE THREAD

**Issue by g1sbi** [brave/brave-browser#21792]
## Description 
I am unable to join a sync chain from my iPhone. After pasting the recovery sentence, I get a "not enough words" error.

## Steps to Reproduce

   1.  Open a fresh instance of Brave on iOS
   2. Try to join a sync chain through either QR code or recovery sentence
   3. Get stuck on QR loading / get a "not enough words" error with sentence.

## Actual result:
When using a QR code, the app just loads forever. Instead, when using the recovery sentence it says I didn't use enough words.

## Expected result:
I expect to be able to join the sync chain.

## Reproduces how often: 
Easily reproduced.

## Brave version (info found on brave://version)
Version 1.36 (22.3.11.16)

**Comment by JoJoHa-rgb** [comment]
having the same problem - is there a solution?

**Comment by naisanzaa** [comment]
+1 same
