### ISSUE TITLE
Verify that ipfs crash handling works as expected

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#21794]
it should restart ipfs node after crash, for example, kill node in the task manager.

**Comment by spylogsster** [comment]
checked on win and osx, if node crashed we do not restart it automatically, but it will be started on next ipfs navigation cc @lidel

**Comment by lidel** [comment]
I think this is a sensible default. Do we log the stdout/stderr somewhere? We print known errors there, including panic traces caused by executable being corrupted due to faulty disk etc

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
