### ISSUE TITLE
toggles appearing via top right corner in several `brave://settings` submenu's 

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#21805]
## Description 

When viewing several `brave://settings` submenu's like `brave://settings/security` & `brave://settings/cookies`, you'll notice that there's toggle buttons appearing at the top right corner of the page.

## Steps to Reproduce

   1. launch brave and visit either `brave://settings/security` or  `brave://settings/cookies`
   2. notice the toggles appearing via the top right of the screen (see examples below)

## Actual result:

**`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|---------------
![securityToggle](https://user-images.githubusercontent.com/2602313/159416967-ff93b31e-3081-4af7-93d1-315601244136.png) | ![cookieToggle](https://user-images.githubusercontent.com/2602313/159416976-a6eeb1de-bfcf-45da-8cb0-fa8c23f767a3.png) | ![cookieToggle2](https://user-images.githubusercontent.com/2602313/159416980-f786e6d7-daac-4a10-870b-fdd41095e613.png) | ![insecureContentToggle](https://user-images.githubusercontent.com/2602313/159416989-d98a048b-995d-4f9e-9ed4-9e331e2d1050.png)

## Expected result:

**`Example`** | **`Example`**
---------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/159417194-2f76aa68-efcd-499a-9b18-ccb83f4662de.png) | ![image](https://user-images.githubusercontent.com/2602313/159417250-174ec6d9-398c-485b-aa63-2c6e45504225.png)

## Reproduces how often: 

100% reproducible using the STR/Cases mentioned above.

## Brave version (brave://version info)

```
Brave | 1.38.57 Chromium: 99.0.4844.74 (Official Build) nightly (64-bit)
--- | ---
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 11 Version 21H2 (Build 22000.556)
```

```
Brave | 1.38.62 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by Tonev** [comment]
@kjozwiak :wave: 

Duplicate of https://github.com/brave/brave-browser/issues/21788

**Comment by kjozwiak** [comment]
@Tonev thanks 👍 Closing this one and will update yours. Thanks for filing! I mentioned it to the team so hopefully it gets addressed before it makes it into `BETA` & `Release`.
