### ISSUE TITLE
`Hide Brave Wallet icon on toolbar` is not translated

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#21808]
## Description 

Found out the option that allows users to hide the wallet icon via a right-click is not translated in other languages. I quickly tested `Bulgarian` and `Polish`, it's quite possible that the string is not translated in more languages as well.

The feature is currently available in `Brave Nightly` and `Brave Beta`.

## Steps to Reproduce

   1. Install `Brave Nightly` or `Brave Beta`.
   2. Set the browser to be displayed in a language different than `English`, you could try in `Bulgarian` or `Polish`, for example.
   3. Make sure `Show Brave Wallet icon on toolbar` is enabled via `brave://settings/wallet`.
   4. Right-click on the `Brave Wallet` icon on the toolbar.

## Actual result:

![image](https://user-images.githubusercontent.com/20608253/159452417-5f18435c-cd9b-4eda-9427-5f73ef0d36c8.png)

## Expected result:
`Hide Brave Wallet icon on toolbar` should be translated.

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.60 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

<html>
<body>

Brave | 1.37.97 Chromium: 99.0.4844.74 (Official Build) beta (64-bit)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

CC: @mkarolin 

P.S If you take a closer look at the screenshot, you'll notice that the new `Privacy and security` rename that `CR100` brought us is also not translated. I'll wait until you merge an updated `CR100 l10n package`, and will open a ticket for it if necessary :+1:

**Comment by Tonev** [comment]
https://github.com/brave/brave-browser/issues/21963 didn't fix the issue. I checked `Bulgarian` and `Polish` once again.

<html>
<body>


Brave | 1.39.18 Chromium: 100.0.4896.60 (Official Build) nightly (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 7 Service Pack 1 (Build 7601)


</body>
</html>

**Comment by mkarolin** [comment]
Thanks @Tonev! Unfortunately, the translations for those two languages aren't available yet ☹️. They should be coming in a follow up l10n round.

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.37.114 Chromium: 100.0.4896.88 (Официално издание) (x86_64)
-- | --
Ревизия | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
ОС | macOS Version 12.3.1 (Build 21E258)
```

Confirmed translation in a few languages

Spanish | Polish | Bulgarian
----- | ----- | -----
<img width="483" alt="Spanish" src="https://user-images.githubusercontent.com/28145373/163179879-5098fcfd-6d51-401b-abd9-4ea6fb4bdc8e.png"> | <img width="352" alt="Polish" src="https://user-images.githubusercontent.com/28145373/163179890-ff8f0873-98a0-4415-92c5-357ded86814e.png"> | <img width="447" alt="Bulgarian" src="https://user-images.githubusercontent.com/28145373/163179899-ba86f5b7-065a-4e19-84c9-e1f72c1e529f.png">
