### ISSUE TITLE
Shouldn't get `Update available` dialog using backgrounded Sparkle updater

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21802]
## Description 

Shouldn't get `Update available` dialog using backgrounded Sparkle updater

Found while testing https://github.com/brave/brave-browser/issues/9562.

## Steps to Reproduce

   1. as an Admin user, install `1.37.92` (`https://github.com/brave/brave-browser/releases/tag/v1.37.92`)
   2. as a Guest user, launch Brave using `--update-feed-url=https://updates.bravesoftware.com/sparkle/Brave-Browser/test-beta/appcast.xml --enable-logging=stderr --vmodule=sparkle_glue=5,brave_relaunch_handler_mac=5 2>&1`
   3. shut Brave down
   4. log out of macOS
   5. log back in as a Guest user
   6. advance system time by 3+ hours
   7. launch Brave using `--update-feed-url=https://updates.bravesoftware.com/sparkle/Brave-Browser/test-beta/appcast.xml --enable-logging=stderr --vmodule=sparkle_glue=5,brave_relaunch_handler_mac=5 2>&1`
   8. wait (might need a restart; ensure to retain commandline-arguments)
   9. choose `Check Automatically` when prompted to `Check for updates automatically?`

## Actual result:

`Check for updates automatically?` | `Software Update`
-----------------------------------|---------------------
<img width="550" alt="Screen Shot 2022-03-21 at 8 04 23 PM" src="https://user-images.githubusercontent.com/387249/159397003-d7cf9d78-92c7-40f8-9ec3-d8954ef9297e.png"> | <img width="732" alt="Screen Shot 2022-03-21 at 8 04 31 PM" src="https://user-images.githubusercontent.com/387249/159396378-3a486a4e-21cb-4375-8a0d-13a30346fee8.png">

You'll get `A new version of Brave Browser Beta is available!` dialog

## Expected result:

Since we're doing background updates, we shouldn't present this upgrade dialog.

## Reproduces how often: 

100%

## Brave version (brave://version info)

`1.37.100` (from `1.37.92`

cc @mihaiplesa @mherrmann @LaurenWags @kjozwiak

**Comment by mherrmann** [comment]
Reproduces for me too (also without the command-line args). Epic find @stephendonner. Thank you. Will investigate the cause and work on a fix (cc @mihaiplesa).

**Comment by mherrmann** [comment]
(For the record: Also the "Check for updates automatically?" popup should not appear to the best of my knowledge.)

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.39.14` on macOS `11.6.5`.  `Went from 1.39.10 -> 1.39.14`

### Steps:

1. as an Admin user, install `1.37.92` (`https://github.com/brave/brave-browser/releases/tag/v1.37.92`)
2. as a Guest user, launch Brave using `--update-feed-url=https://updates.bravesoftware.com/sparkle/Brave-Browser/test-beta/appcast.xml --enable-logging=stderr --vmodule=sparkle_glue=5,brave_relaunch_handler_mac=5 2>&1`
3. shut Brave down
4. log out of macOS
5. log back in as a Guest user
6. advance system time by 3+ hours
7. launch Brave using `--update-feed-url=https://updates.bravesoftware.com/sparkle/Brave-Browser/test-beta/appcast.xml --enable-logging=stderr --vmodule=sparkle_glue=5,brave_relaunch_handler_mac=5 2>&1`

#### Confirmed I was successfully updated on app restart, without any software-update popups appearing.

example | example | example | example
---------|---------|----------|---------
<img width="669" alt="Screen Shot 2022-03-29 at 10 05 57 AM" src="https://user-images.githubusercontent.com/387249/160907278-677a3e1c-5e2e-40c8-85b9-11b1894560ea.png"> | <img width="1680" alt="Screen Shot 2022-03-29 at 1 32 14 PM" src="https://user-images.githubusercontent.com/387249/160907236-110c7b40-a177-4fa9-a914-251f5c4aac77.png"> | <img width="1680" alt="Screen Shot 2022-03-29 at 1 32 52 PM" src="https://user-images.githubusercontent.com/387249/160907260-af9350a7-2198-4c37-893d-4e5fa871fd48.png"> | <img width="1680" alt="Screen Shot 2022-03-29 at 1 33 35 PM" src="https://user-images.githubusercontent.com/387249/160907271-a466824d-a068-47d2-8849-326ee974aee0.png">

**Comment by rebron** [comment]
This is being reverted in 1.39.x: https://github.com/brave/brave-core/pull/12916

Related comment: 
https://github.com/brave/brave-browser/issues/21813#issuecomment-1079628421
