### ISSUE TITLE
Update first run dialog text on macOS and Linux

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#21804]
## Description 
Update first run dialog text on macOS and Linux to match current Windows version.

## Actual result:

<img width="501" alt="131174148-cda8c7db-49a1-4d2f-9240-f1df0aac207b" src="https://user-images.githubusercontent.com/5951041/159415402-f97ad715-eac5-4e3e-ae96-8d8a96502a26.png">

## Expected result:
![158931105-bf6518bd-35e5-4f6f-bc87-87e213876986](https://user-images.githubusercontent.com/5951041/159415484-6142bf9d-98b5-4974-ad7e-90a25511aa93.png)

Replace "Welcome to Brave" with "Ready for the best privacy online?"
Replace "To ensure the best privacy online..." with "Set Brave as your default browser..."

## Brave version (brave://version info)

Target 1.37.x/1.38.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Related: https://github.com/brave/brave-browser/issues/21694

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.39.51 Chromium: 100.0.4896.88 (Official Build) nightly (x86_64)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | macOS Version 11.6.5 (Build 20G527)


`Light` theme

focused | unfocused
--------|-----------
<img width="512" alt="Screen Shot 2022-04-12 at 4 20 53 PM" src="https://user-images.githubusercontent.com/387249/163070149-3786d60a-93e6-4b58-932d-5dfcfd43729b.png"> |  <img width="468" alt="Screen Shot 2022-04-12 at 4 20 57 PM" src="https://user-images.githubusercontent.com/387249/163070162-7a234077-a3fc-4e0d-9dc1-96b2a1a1b696.png">


`Dark` theme

focused | unfocused
---------|-----------
<img width="512" alt="Screen Shot 2022-04-12 at 4 23 27 PM" src="https://user-images.githubusercontent.com/387249/163070316-3731cc4a-d09d-4b42-a017-a9ff9ab4f2f3.png"> | <img width="468" alt="Screen Shot 2022-04-12 at 4 23 30 PM" src="https://user-images.githubusercontent.com/387249/163070319-5df65296-6821-4a97-9df9-975fb513c83e.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.100 Chromium: 101.0.4951.61 (Official Build) beta (64-bit)
-- | --
Revision | 3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS | Ubuntu 18.04 LTS


Light mode:
![image](https://user-images.githubusercontent.com/34715963/167806144-21998198-2943-4004-866c-fbabeb02b0c4.png)

Dark mode:
![image](https://user-images.githubusercontent.com/34715963/167823505-6fc21d8c-4688-4c7c-bd79-d54aa0fc832c.png)

Polish locale:
![image](https://user-images.githubusercontent.com/34715963/167825639-028bd4ed-853d-4b40-af91-369bab9a38b4.png)
