### ISSUE TITLE
Tab grouping option should be optional, forcing tab grouping layout is a downgrade to UX

### ISSUE THREAD

**Issue by JoaoHamerski** [brave/brave-browser#21814]
## Description 
Recently Brave Mobile just removed completely the old tabs view from the app.

This layout was removed:
![old](https://9to5google.com/wp-content/uploads/sites/4/2019/09/chrome-android-tab-list.png.png)

While this is the only one available:
![new](https://9to5google.com/wp-content/uploads/sites/4/2019/09/chrome-android-tab-grid.png)

The old one should still be available, it's incomparable better and more user friendly: 
- In the new layout (where you can group tabs and probably 0.01% of people do it), most of time you have to drag your thumbs to the top of the screen to select a tab or close it, which is very annoying; In the old one you only need to swipe the center of screen to navigate between tabs, ands swipe to any side to close the tab.
- In the old one you an clearly see the tab title and a have a better view o the site thumbnail, in the new one this is reduced.

## Brave version
1.36.116

### Additional information

This is annoying a lot of people, just check the Google Play or App Store recent avaliations.

**Comment by bsclifton** [comment]
Thanks for the report @JoaoHamerski - we have an open issue tracking this which you can find here:
https://github.com/brave/brave-browser/issues/21556

We're evaluating what it would take to add this back in

**Comment by bsclifton** [comment]
New issue created to track this work 👍 
https://github.com/brave/brave-browser/issues/22028
