### ISSUE TITLE
Bookmarks panel blank 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#21819]
## Description 

Bookmarks panel is blank, likely due to chromium 100.

## Steps to Reproduce

   1. Update to 1.38.60 or higher with Chromium 100.x
   2. Open bookmarks sidebar panel.
   3. Notice the bookmarks panel is blank

## Actual result:

<img width="332" alt="screenshot_2022-03-22_141428" src="https://user-images.githubusercontent.com/5951041/159577937-215291a0-ab06-412b-9f9a-81924f59650e.png">

## Expected result:
<img width="256" alt="Screenshot 2022-03-22 142055" src="https://user-images.githubusercontent.com/5951041/159578062-cc5bf6bf-26dc-4a27-870b-2538e20feaa6.png">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.38.60 but specifically looks to be Chromium 100 related.

## Version/Channel Information:

- Can you reproduce this issue with the current release? soon
- Can you reproduce this issue with the beta channel? soon
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Reproduced the issue in 1.37.103 Chromium: 100.0.4896.46
- Verified the issue in `1.37.105` issue is fixed and working fine, verification notes are linked in https://github.com/brave/brave-browser/issues/21699#issuecomment-1072331554 (Case 2: Sidebar_Bookmarks settings)

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

example | example
---------|--------
<img width="1610" alt="Screen Shot 2022-03-26 at 11 47 48 PM" src="https://user-images.githubusercontent.com/387249/160270095-c67ea48d-1e1f-42e7-b6c1-0284042c240d.png"> | <img width="1610" alt="Screen Shot 2022-03-26 at 11 48 58 PM" src="https://user-images.githubusercontent.com/387249/160270115-64c9b89c-ae15-43bd-a3c8-004cbeca402b.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.107 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/160471371-8e67ba1b-14cd-41bc-bc1e-e68593779d8b.png)
