### ISSUE TITLE
Open Rewards onboarding tour from NTP widget

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#21811]
## Description 

When users select "Start using Rewards" from the NTP Brave Rewards widget, we should open the Brave Rewards panel and show users the Rewards onboarding tour.

## Steps to Reproduce

   1. Install latest version of browser or create  a new profile
   2. Notice Brave Rewards panel and select Start using Rewards button.
   3. Brave Rewards panel changes to 0.00, etc. Users should be taken to Rewards tour.

## Actual result:

<img width="281" alt="Screenshot 2022-03-22 081539" src="https://user-images.githubusercontent.com/5951041/159515783-ea43b15e-28b1-4024-bbd8-e65c34941216.png">

## Expected result:
<img width="609" alt="Screenshot 2022-03-22 081121" src="https://user-images.githubusercontent.com/5951041/159515807-1d89a1c9-3136-41d3-af1d-970d1ac092e7.png">
<img width="488" alt="Screenshot 2022-03-22 081156" src="https://user-images.githubusercontent.com/5951041/159515819-3646778e-7d2e-4c8d-b6ef-0fd7610d401f.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc: @Miyayes

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)



<Summary>Testcase 1: Rewards onboarding tour should be shown when clicked on 'Start using Rewards` from NTP Brave Rewards widget </Summary>

<details>

- Install 1.38.74
- Launch Brave
- `Set Brave as default` on the first run dialog
- Click` Skip welcome tour`
- Click `Start using Rewards` on the `Brave Rewards Panel` on NTP
- Rewards Onboarding tour is shown 
- Complete the tour

ex1|ex2|ex3
---|---|---
<img width="1026" alt="Screen Shot 2022-04-07 at 5 50 29 PM" src="https://user-images.githubusercontent.com/387249/162342129-302d3f3d-1b08-434c-93e2-6638df72474f.png"> | <img width="1026" alt="Screen Shot 2022-04-07 at 5 50 43 PM" src="https://user-images.githubusercontent.com/387249/162342137-9667a80e-d41e-47bc-aa23-bae25d4c5409.png"> | <img width="1026" alt="Screen Shot 2022-04-07 at 5 50 46 PM" src="https://user-images.githubusercontent.com/387249/162342139-8cf0e818-ea4c-42e6-9d34-0c4aae484598.png">

</details>

<Summary>Testcase 2: Rewards onboarding tour will not be shown from NTP widget once `Start Using Rewards` was clicked  previously <Summary>
<details>

Pre requisites:

1. User has previously clicked `Start using Rewards` button on NTP Rewards widget
2. User has previously clicked NTP SI Brave Rewards widget

- Launch a new profile
- Clicked `Start using Rewards` button from prerequisites options
- Disable Ads from brave://rewards
- Return back to NTP and `Brave Rewards` widget shows `Start using Rewards`
- Click `Start using Rewards`
- Rewards tour is not shown

ex1|ex2|ex3
---|---|---


</details>

<Summary> Testcase 3: Rewards onboarding tour will be shown from NTP Rewards widget even if the user has completed rewards tour from Brave Rewards panel </Summary>
<details>

-  New profile
- Launch Brave
- `Set Brave as default` on the first run dialog
- Click` Skip welcome tour`
- Click on the Rewards icon in the URL and complete onboarding tour from Brave Rewards panel
- `Start Using Rewards` button will be disappeared form Brave Rewards widget on NTP
- Disable Ads from `brave://rewards`
- Open a NTP and Click `Start using Rewards`
- Rewards onboarding tour is displayed

ex1|ex2|ex3|ex4
---|---|---|---

</details>

<Summary>Testcase 4: Rewards onboarding tour will be shown from NTP widget even if the user has completed rewards tour from the Rewards page </Summary>
<details>

- New profile 
- Launch Brave
- `Set Brave as default` on the first run dialog
- Click` Skip welcome tour`
- Open `brave://rewards`
- Click Start using Brave Rewards and complete onboarding tour 
- Disable Ads in `brave://settings/rewards`
- Open NTP and Click `Start using Rewards`
- Rewards Onboarding tour should be displayed

ex1|ex2|ex3|ex4|ex5
---|---|---|---|---

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

<Summary>Testcase 1: Rewards onboarding tour should be shown when clicked on Start using Rewards from NTP Brave Rewards widget</Summary>

<details>

- Install `1.38.83`
- Launch Brave
- `Set Brave as default` on the first run dialog
- Click` Skip welcome tour`
- Click `Start using Rewards` on the `Brave Rewards Panel` on NTP
- Rewards Onboarding tour is shown 
- Complete the tour


![image](https://user-images.githubusercontent.com/34715963/162810402-f26c2a4b-1d96-4a3b-8a58-111b1557be5f.png)
![image](https://user-images.githubusercontent.com/34715963/162810448-9f83ab98-8fb6-4644-9f5c-59cb9daa6b12.png)
![image](https://user-images.githubusercontent.com/34715963/162810485-21e3ea02-2fe5-4625-9ec0-6f9857c5eea7.png)


</details>

<Summary>Testcase 2: Rewards onboarding tour will not be shown from NTP widget once Start Using Rewards was clicked  previously</Summary>

<details>

Prerequisites:
1. User has previously clicked `Start using Rewards` button on NTP Rewards widget
2. User has previously clicked NTP SI Brave Rewards widget
- Launch a new profile
- Clicked `Start using Rewards` button from prerequisites options
- Disable Ads from `brave://rewards`
- Return back to NTP and `Brave Rewards` widget shows `Start using Rewards`
- Click `Start using Rewards`
- Rewards tour is not shown

![image](https://user-images.githubusercontent.com/34715963/162810862-10d10051-0d1a-42fd-9901-f0dfa1a7bbce.png)
![image](https://user-images.githubusercontent.com/34715963/162812524-15ec287a-2c2a-465d-aefa-f98484017776.png)
![image](https://user-images.githubusercontent.com/34715963/162812594-f2acffa2-1ba1-47ad-be85-c2ceec639a52.png)


</details>

<Summary> Testcase 3: Rewards onboarding tour will be shown from NTP Rewards widget even if the user has completed rewards tour from Brave Rewards panel</Summary>
<details>

-  New profile
- Launch Brave
- `Set Brave as default` on the first run dialog
- Click` Skip welcome tour`
- Click on the Rewards icon in the URL and complete onboarding tour from Brave Rewards panel
- `Start Using Rewards` button will be disappeared form Brave Rewards widget on NTP
- Disable Ads from `brave://rewards`
- Open a NTP and Click `Start using Rewards`
- Rewards onboarding tour is displayed

![image](https://user-images.githubusercontent.com/34715963/162813178-4ef9a267-8780-4f33-be5f-2bec30b2d029.png)
![image](https://user-images.githubusercontent.com/34715963/162813204-4f7c0017-f72a-4deb-a24b-344b13555173.png)
![image](https://user-images.githubusercontent.com/34715963/162813237-28f1ac94-e831-43f6-86b9-146acfdbf775.png)
![image](https://user-images.githubusercontent.com/34715963/162813313-5b444fcc-6d9b-44a2-abd7-7d77ca7af0af.png)



</details>

<Summary>Testcase 4: Rewards onboarding tour will be shown from NTP widget even if the user has completed rewards tour from the Rewards page </Summary>
<details>

- New profile 
- Launch Brave
- `Set Brave as default` on the first run dialog
- Click` Skip welcome tour`
- Open `brave://rewards`
- Click Start using Brave Rewards and complete onboarding tour 
- Disable Ads in `brave://settings/rewards`
- Open NTP and Click `Start using Rewards`
- Rewards Onboarding tour should be displayed

![image](https://user-images.githubusercontent.com/34715963/162813482-b06271f3-0411-4941-b477-f1731669a69b.png)
![image](https://user-images.githubusercontent.com/34715963/162813521-c2f6c2ab-09ed-45c7-8bef-7a9d6fdabd55.png)
![image](https://user-images.githubusercontent.com/34715963/162813547-644db1b3-12db-4b2a-ac28-e7be10b23da2.png)
![image](https://user-images.githubusercontent.com/34715963/162813573-5b55b553-cf4d-453e-9539-3e0a61b57665.png)
![image](https://user-images.githubusercontent.com/34715963/162813641-7a543e73-d905-4a69-915e-382c5c54cf5f.png)
