### ISSUE TITLE
unable to mute on macOS via tab audio icon after Chromium 100

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#21829]
## Description 

Found by @stephendonner 

After Chromium 100 was merged to master, Nightly can no longer mute tabs by clicking on the audio icon on a tab.

This worked with Nightly 1.38.57 (Chromium 99) and does not work with Chromium 100 versions of Nightly (1.38.59, 

## Steps to Reproduce

   1. Download latest Nightly with Chromium 100
   2. Visit a site with audio (such as a youtube video)
   3. See audio icon on the tab once video starts to play
   4. Click on audio icon, nothing happens, video is not muted

## Actual result:

Clicking on the audio icon of a tab does nothing

## Expected result:

Clicking on the audio icon of a tab should mute the tab

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.38.65 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.3 (Build 21E230)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.36.x no
- Can you reproduce this issue with the beta channel? 1.37.x no
- Can you reproduce this issue with the nightly channel? 1.38.x yes, after chromium 100 merged

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 

```
Brave | 1.38.65 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```

**Comment by kjozwiak** [comment]
Above requires `1.37.106` or higher for `1.37.x` verification.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.106 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed I was able to `mute` and `unmute` audio of playing YouTube (and other) media, at will.

`muted` | `unmuted`
---------|---------
<img width="1312" alt="Screen Shot 2022-03-27 at 10 56 36 AM" src="https://user-images.githubusercontent.com/387249/160294310-edae713c-4edb-428f-9768-05ade70f3fd4.png"> | <img width="1312" alt="Screen Shot 2022-03-27 at 10 56 41 AM" src="https://user-images.githubusercontent.com/387249/160294318-9b3d3581-05e3-4dea-9325-93b503fd6c89.png">
