### ISSUE TITLE
Limit action_pool for high -j value

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#21828]
We need to do this manually since we don't enable `use_goma` in gn now:
https://github.com/chromium/chromium/blob/2a5d8f98e4e8b10c3bd1d34b616b328b32126bee/build/toolchain/BUILD.gn#L15-L17

**Comment by kjozwiak** [comment]
Adding missing `1.39.x` milestone as this was merged into `master` via https://github.com/brave/brave-core/pull/12715.
