### ISSUE TITLE
Previous version standalone installers are not working for windows, only the latest version installer is working

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2182]
## Description 
Previous version standalone installers are not working for windows. Only the latest version is working fine.

I tried installing standalone installer `BraveBrowserStandaloneSetup.exe_0.56.14` it worked/installed successfully without any issues ( before installing 0.56.14 standalone installer, i was having Brave (0.25.2), Bravebeta(0.57.5), BraveNightly(old) versions installed in my machine). When i tried installing `BraveBrowserStandaloneSetup.exe_0.56.12', it throws an error saying " your computer has more recent versions of brave installed", then i have removed Brave from below places, and installed again but no success.

1. Uninstall all Brave versions from `Control Panel` 
2. Removed `BraveSoftware` from `AppData\Local\BraveSoftware`
3. Removed `BraveSoftware` from  `C:\Program Files (x86)\BraveSoftware`
4. Delete  `Brave`,  `BraveNightly`,  from `AppData\Roaming\`

Note:  Installer `BraveBrowserStandaloneSetup.exe_0.56.14` works  irrespective of other brave versions installed in machine

## Steps to Reproduce

Prerequisites 1: Make sure you have Brave versions installed on your machine (Brave/Bravebeta/BraveDev/BraveNightly)

Prerequisites 2: Make sure you dont have Brave installed in your machine (Uninstall all versions from control panel, Remove `AppData\Local\BraveSoftware`, Remove `C:\Program Files (x86)\BraveSoftware`, Remove brave, bravebeta, bravedev, bravenightly from `AppData\Roaming\`)

Prerequisites 3: Make sure you have only profile directory `AppData\Local\BraveSoftware`. Uninstall all brave versions from control panel.

TestPlan 1:

   1. Prerequisites 1 setup
   2. Install `BraveBrowserStandaloneSetup.exe_0.56.12`
   3. Verify that error message throws (mentioned in Acuatl result)
   4. Install `BraveBrowserStandaloneSetup.exe_0.56.14` 
   5. Observe that 0.56.14 insatlled without any issues.

Test Plan 2:
  1. Prerequisites 2 setup
  2. Install `BraveBrowserStandaloneSetup.exe_0.56.12`
  3. Verify that error message throws (mentioned in Acuatl result)
  4. Install `BraveBrowserStandaloneSetup.exe_0.56.14` 
  5. Observe that 0.56.14 insatlled without any issues.

Test Plan 3:

  1. Prerequisites 3 setup
  2. Install `BraveBrowserStandaloneSetup.exe_0.56.12`
  3. Verify that error message throws (mentioned in Acuatl result)
  4. Install `BraveBrowserStandaloneSetup.exe_0.56.14` 
  5. Observe that 0.56.14 insatlled without any issues.

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/48689959-ab19ae00-ebf2-11e8-85c9-12f93a65935a.png)

## Expected result:
Previous version offline installers should work without any issues.

## Reproduces how often: 
Always

## Brave version (brave://version info)
 Offline installer - BraveBrowserStandaloneSetup.exe_0.56.12

### Reproducible on current release:
NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by btlechowski** [comment]
Not reproducible on Windows 7 x64.

Steps:
1. Uninstall all Brave versions
2. Install Brave 0.56.12 through standalone installer
3. Check Brave version in chrome://version
4. Install Brave 0.56.14 through standalone installer
5. Check Brave version in chrome://version

Checked few times.

**Comment by GeetaSarvadnya** [comment]
Issue is working fine on Win7 , Win 8 and Win10. Only in one case it's not working for that already a defect #1855 is logged and is in Open state. Hence closing this issue as invalid.
