### ISSUE TITLE
Ropsten testnet faucet expired using wallet buy tab

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#21823]
## Description 
Switching to Ropsten and using `buy` to get ether will bring up expired faucet page

## Steps to Reproduce

   1. From Brave Wallet dash, change network to 'Ropsten Testnet' using the dropdown
   2. Navigate to wallet `Buy` tab
   3. Click on `get ether` button

## Actual result:

![Screen Shot 2022-03-22 at 5 25 43 PM](https://user-images.githubusercontent.com/17885425/159599576-0c59f419-ca63-4749-9723-13b19ced1a02.png)

## Expected result:
Functional testnet faucet source page

## Reproduces how often: 

Easily

## Brave version (brave://version info)

`Version 1.37.102 Chromium: 99.0.4844.83 (Official Build) dev (x86_64)`
`MacOS`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Uni-verse** [comment]
Closing Dup

https://github.com/brave/brave-browser/issues/21240

**Comment by srirambv** [comment]
Closing as dupe as this is fixed and verified here https://github.com/brave/brave-browser/issues/21240#issuecomment-1105117791

**Comment by srirambv** [comment]
Reopening as the fix is only for desktop. Android needs to pickup the change as well. 

cc: @Pavneet-Sing @wchen342 @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
we need to move that to c++ level and receive via mojo to avoid such problems in the future. In that case we would change in one place and all platforms would get it updated. I guess iOS has it expired as well @srirambv ? cc @bbondy on thoughts about moving it to mojo.

**Comment by bbondy** [comment]
```

struct NetworkInfo {
  string chain_id;
  string chain_name;
  array<string> block_explorer_urls;
  array<string> icon_urls;
  array<string> rpc_urls;
  string symbol;
  string symbol_name;
  int32 decimals;
  CoinType coin;
  NetworkInfoData? data;
};

```

Maybe adding `array<string> faucet_urls` or just 1 url even

@yrliou may have more thoughts.

**Comment by srirambv** [comment]
> I guess iOS has it expired as well @srirambv ? 

@SergeyZhukovsky Yes same problem on iOS as well.

**Comment by jamesmudgett** [comment]
Setup a docs site that has a list of faucets

**Comment by srirambv** [comment]
We should probably remove all testnet's and just link to Goreli and Sepolia post merge

**Comment by DaniloRoque501** [comment]
https://github.com/brave/brave-browser/issues/21823#
