### ISSUE TITLE
Missing serial comma in Brave Shields icon tooltip

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21834]
## Description 

Missing serial comma in Brave Shields icon tooltip

Per https://github.com/brave/brave-browser/issues/17369#issue-962209812

## Steps to Reproduce

1. install `1.38.66`
2. launch Brave 
3. load a site with known trackers (`cnn.com`)
4. hover over the Shields icon in the URL bar
5. look at the tooltip text

## Actual result:

`X Trackers, ads and more blocked` (note the missing serial/Harvard/Oxford comma)

<img width="1316" alt="Screen Shot 2022-03-23 at 11 22 37 AM" src="https://user-images.githubusercontent.com/387249/159769463-287f3914-b40b-4ebd-9845-524a9f028a99.png">

## Expected result:

`X Trackers, ads, and more blocked`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.38.66 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.3 (Build 21E230)

cc @nullhook @rmcfadden3

**Comment by rmcfadden3** [comment]
Yes! Need this Oxford comma, plz!

**Comment by Tonev** [comment]
@stephendonner 

Feel free to assign me as I have opened a pull request that will resolve the issue :+1:

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.39.7 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed the tooltip now reads `Brave Shields X Trackers, ads, and more blocked` (with the Oxford comma).

Thanks @Tonev and @nullhook ❤️

**Comment by MadhaviSeelam** [comment]
Verified `Passed` using

Brave | 1.39.10 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

Confirmed the tooltip now reads Brave Shields X Trackers, ads, and more blocked (with the Oxford comma).

<img width = "980" alt="brave shields tooltip text" src="https://user-images.githubusercontent.com/98358127/160504128-64d846ef-651c-42e9-abac-7f079bd192e1.png">
