### ISSUE TITLE
Filter swapAssetOptions by Network

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21839]
## Description 
`swapAssetOptions` is returning assets from all networks (chainId's), should only show assets for the `SelectedNetwork`

**Comment by kjozwiak** [comment]
Above requires `1.38.82` or higher for verification on `1.38.x`.

**Comment by Uni-verse** [comment]
Verified using 

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.3.1 (Build 21E258)

- Ensured assets options in swap are shown based on selected network
- Verified assets option on Ropsten, Eth mainnet, BSC, Polygon, Fantom

https://user-images.githubusercontent.com/17885425/163619033-5f1ad16d-fa11-4201-9b3c-2bc1187a04a6.mov
