### ISSUE TITLE
Add version number when sending confirmations

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#21836]
Add version number to payload when sending confirmations, i.e. `{"versionNumber":"1.2.3.4"}`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.73 Chromium: 101.0.4951.34 (Official Build) nightly (64-bit)
-- | --
Revision | 8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}
OS | Ubuntu 18.04 LTS

`view`
![image](https://user-images.githubusercontent.com/34715963/164291594-36aea72a-04e5-44e8-a4e0-92f654fc4ba8.png)
![image](https://user-images.githubusercontent.com/34715963/164293764-4376d893-bdc4-4f3f-96b1-1476406894a4.png)

`dismissed`
![image](https://user-images.githubusercontent.com/34715963/164294060-94b3597c-5a34-40c8-9f0c-c69379573aeb.png)

**Comment by kjozwiak** [comment]
Above will require `1.38.104` or higher for `1.38.x` verification.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.105 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/164783239-9c4ba5b1-d1e7-4357-a835-c08a954791b3.png)
