### ISSUE TITLE
Send is showing Not a valid address Error for empty field

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21838]
## Description 
The `Send` tab is showing a `Not a valid address` error for an empty `To Address` field

![Screen Shot 2022-03-23 at 6 42 52 PM](https://user-images.githubusercontent.com/40611140/159819849-058c9b62-9c1b-40e1-9ca8-6addc889f29d.png)

**Comment by kjozwiak** [comment]
Above requires `1.38.82` or higher for verification on `1.38.x.`
