### ISSUE TITLE
Toggle password visibility button gets focused

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#21845]
## Description 
Need to press Tab key twice to switch from Password field to Confirm Password field.

## Steps to Reproduce

   1. Start restoring wallet on brave://wallet 
   2. Type something in Password field 
   3. Press tab

## Actual result:
Input cursor disappears 

## Expected result:
Input cursor should appear in Confirm Password field

## Reproduces how often: 
Easily reproduced

## Version/Channel Information:
- Brave Nightly

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.68 Chromium: 102.0.5005.50 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13273>brave/brave-core#13273</a></li>
         <li>Verified pressing tab in password field sets focus to show/hide password button</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/170045342-6b0bccd2-2bf1-49f9-a1d8-d6c080d6314e.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/170307396-e4717529-f7b2-49d3-b2a4-ec6dcacc4bfc.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/170307302-5ad5f464-ffbc-4be4-9e1b-19c06577501d.mov>
      </td>
   </tr>
</table>
