### ISSUE TITLE
When sidebar is not enabled the text `Show Sidebar Enabled` is shown in the brave://settings/appearance

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21842]
## Description 

When sidebar is not enabled the text `Show Sidebar Enabled` is shown in the brave://settings/appearance
## Steps to Reproduce

   1. Clean profile 1.37.x 
   2. Open brave://settings/appearance
   3. Observe the text `Show Sidebar Enabled` when `Never` is selected 
   4. Reload brave://settings/appearance
   5. Text is still `Show Sidebar Enabled`
   6. Change the settings to `Always` or `On mouseover`
   7. Sidebar is enabled and text is `Show Sidebar Enabled` as expected
   8. Change the settings to `Never` again
   9. Sidebar is disabled and text is `Show Sidebar Disabled` as expected
   10. Reload brave://settings/appearance
   11. Text is reset back to `Show Sidebar Enabled` when `Never` is selected  - which is incorrect

## Actual result:

![sidebar](https://user-images.githubusercontent.com/38657976/159907585-bbff98c3-1fc8-47a0-a433-22a966247d8f.gif)

![image](https://user-images.githubusercontent.com/38657976/159906646-3570b19d-8b0c-438b-8544-fa2a8a87758d.png)

## Expected result:

When `Never` is selected the text should be displayed as `Show Sidebar Disabled` 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 10 Version 21H2 (Build 19044.1586)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @simonhong

**Comment by Tonev** [comment]
This bug made it into the latest release. Maybe it would be appropriate it to get it fixed soon as it might confuse a lot of users as it is right now.

**Comment by MadhaviSeelam** [comment]
Verification `In-Progress` 

Brave | 1.39.84 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

- Installed 1.39.84 
- Launched Brave
- Opened brave://settings/appearance
- Verified the default option for `Show Sidebar Enabled` is `Always` for Beta 
- Correct label displayed for the option `Show Sidebar Enabled`
- Change settings from `Always` to `Never`
- Sidebar disappears and the label for the option reads `Show Sidebar Disabled`
- Reload brave://settings/appearance
- The label for the option still reads `Show Sidebar Disabled`
- Change `Never` to `Always`
- Verified Sidebar shows and the label for the option reads `Show Sidebar Enabled`
- Reload brave://settings/appearance
- Verified `Always` is still shown as the value for `Show Sidebar Enabled`
- Verified `On mouseover` label and settings work as expected

Always|Always->Never|Reload|Always|on mouseover
---|---|---|---|---
<image width="850" alt="sidebar-always" src="https://user-images.githubusercontent.com/98358127/165792571-9806b9c5-3f8f-4451-985a-8ed140c719f2.png">|<image width="850" alt="sidebar-never" src="https://user-images.githubusercontent.com/98358127/165792664-9584d7c9-a07b-4a02-8571-f2c6495ac201.png">|<image width="850" alt="sidebar-reload-never" src="https://user-images.githubusercontent.com/98358127/165792738-53f8db51-582e-4371-b16a-54267829bb6f.png">|<image width="850" alt="sidebar-always" src="https://user-images.githubusercontent.com/98358127/165792571-9806b9c5-3f8f-4451-985a-8ed140c719f2.png">|<image width="850" alt="sidebar-mouseover" src="https://user-images.githubusercontent.com/98358127/165793707-3adf1fd6-3abe-4258-b6a9-92854db4c2c2.png">
