### ISSUE TITLE
"Not secure" warning when accessing the Brave onion site in http-nowhere mode

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#21847]
## Description 

If you enable `Upgrade connections to HTTPS` and `Always use secure connections` and type brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion in the address bar and submit, you'll end up with the warning screen about the site not supporting https, which is incorrect.

![image](https://user-images.githubusercontent.com/1129003/159940376-a49f663a-b921-44b8-b83b-31121028454a.png)

## Steps to Reproduce

   1. Enable `Upgrade connections to HTTPS` and `Always use secure connections`
   2. Type brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion in the address bar and hit enter
   3. See the warning

## Actual result:

Warning

## Expected result:
No warning

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.38.57 Chromium: 99.0.4844.74 (Official Build) nightly (64-bit)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

```console
$ torify curl -fsSLI brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion
HTTP/1.1 307 Temporary Redirect
Date: Thu, 24 Mar 2022 14:23:12 GMT
Content-Type: text/html
Connection: keep-alive
Location: https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/

HTTP/1.1 200 OK
Date: Thu, 24 Mar 2022 14:23:14 GMT
Content-Type: text/html
Connection: keep-alive
ETag: "28fba00b87c21a3c2eadb946cc788041"
x-amz-server-side-encryption: AES256
x-amz-version-id: uc_rPNUctkbjkeQzjS23ck2NQg3ZHsfm
Accept-Ranges: bytes
Content-Security-Policy: connect-src 'self' https://survey.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://subscriptions.bsg.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://app.sgwidget.com; default-src 'none'; media-src 'self'; font-src 'self'; frame-ancestors 'self' https://blog.batcommunity.org; frame-src 'self' https://5x499s74bts.typeform.com https://html5-player.libsyn.com https://social-growth.bravesoftware.com https://try.bravesoftware.com https://survey.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://www.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://player.vimeo.com https://boards.greenhouse.io https://www.surveymonkey.com https://public.tableau.com https://www.slideshare.net https://docs.google.com https://www.youtube-nocookie.com https://js.driftt.com; img-src 'self' data: https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://basicattentiontoken.org https://analytics.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://boards.greenhouse.io https://secure.gravatar.com https://blog.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://*.ggpht.com https://*.jtvnw.net; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://survey.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://djtflbt20bdde.cloudfront.net https://analytics.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion https://boards.greenhouse.io https://js.driftt.com; style-src 'self' 'unsafe-inline' https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion; object-src 'self'; manifest-src 'self'; upgrade-insecure-requests;
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Referrer-Policy: strict-origin-when-cross-origin
Cross-Origin-Opener-Policy: same-origin
Permissions-Policy: interest-cohort=()
Onion-Location: https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/index.html
Vary: Accept-Encoding
X-Cache: Hit from cloudfront
X-Amz-Cf-Pop: SEA73-P1
X-Amz-Cf-Id: J5c1UNk60MvTTe-INvlwBqK06uC5rvz62EAHYwGxUIlV95zPSFnvmg==

$
```

**Comment by diracdeltas** [comment]
note that as part of https://github.com/brave/brave-browser/issues/21681, onion sites will be considered secure regardless of https

**Comment by wknapik** [comment]
Closing per [above](https://github.com/brave/brave-browser/issues/21847#issuecomment-1077864854).

**Comment by jayschwa** [comment]
This "Not secure" warning still occurs on onion sites in Brave v1.43.89.
