### ISSUE TITLE
You are using an unsupported command-line flag: --no-sandbox. Stability and security will suffer.

### ISSUE THREAD

**Issue by wildcard-f8** [brave/brave-browser#21849]
When I open the browser it shows a message that says: You are using an unsupported command-line flag: --no-sandbox. Stability and security will suffer.

Version 1.36.111 Chromium: 99.0.4844.51 (Official Build) unknown (64-bit)](https://brave.com/latest/)

Manjaro

**Comment by diracdeltas** [comment]
where did you install brave? none of our official builds use this flag by default.

**Comment by wknapik** [comment]
Manjaro is based on Arch and our [instructions at brave.com/linux](https://brave.com/linux/#manjaro) advise installing the binary packages from [AUR](https://aur.archlinux.org/packages/brave-bin), just like on Arch.

Just checked on Arch, where the AUR packages were installed according to official instructions - if I start instances of release/beta/nightly, the only sandbox related options visible in `ps` output are:
* `--no-zygote-sandbox`
* `--service-sandbox-type=none`
* `--service-sandbox-type=utility`

The packages I have installed are:
* brave-bin 1:1.36.122-1
* brave-beta-bin 1.38.69-1
* brave-nightly-bin 1.39.7-1

I'm using the hardened kernel, so the snap package is not usable on my system without extra options:
```console
% snap run brave
[2066642:2066642:0328/140235.398216:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! You probably need to enable user namespaces in your kernel. See https://brave.com/linux for more info.
[0328/140235.399294:ERROR:ptracer.cc(567)] ptrace: Input/output error (5)
[...]
[0328/140235.423960:ERROR:elf_dynamic_array_reader.h(64)] tag not found
/snap/brave/151/opt/brave.com/brave/brave-browser: line 48: 2066642 Trace/breakpoint trap   (core dumped) "$HERE/brave" "$@"
%
```
but the error indicates that the binary is started without the `--no-sandbox` switch and supplying it explicitly on the command line makes the browser start without the above error.

**Comment by wknapik** [comment]
@wildcard-f8 could the `--no-sandbox` option be added on your machine, rather than coming from the Brave package itself? For instance you might have it in ~/.config/chrome-flags.conf, or you might be using an alias that appends the option? Please specify how the package was installed.

**Comment by wildcard-f8** [comment]
From the official repository.

**Comment by wildcard-f8** [comment]
No installed it from the Manjaro Official Repository.

**Comment by wknapik** [comment]
I see Manjaro has a [Brave package in their community repo](https://gitlab.manjaro.org/packages/community/brave/-/tree/master). 

And they disable the sandbox if unprivileged user namespaces are disabled:
https://gitlab.manjaro.org/packages/community/brave/-/blob/master/brave.sh#L13
https://gitlab.manjaro.org/packages/community/brave/-/blob/master/PKGBUILD#L55

I'm not sure why they're doing it. I'm running Arch with unprivileged user namespaces disabled and I'm running Brave without the `--no-sandbox` option.

**Comment by wknapik** [comment]
Hey @philmmanjaro. Could you please drop the `--no-sandbox` option from the [Manjaro Brave package](https://gitlab.manjaro.org/packages/community/brave/-/blob/master/brave.sh#L13)?

**Comment by wknapik** [comment]
Contacted the three listed Brave Browser package maintainers via email.

**Comment by wknapik** [comment]
Just noticed this was fixed by Stefano 3 weeks ago in https://gitlab.manjaro.org/packages/community/brave/-/commit/500bde21e25510ca0c593caab94e5cec3796f9fd (thanks!). Closing.
