### ISSUE TITLE
Advanced Solana NFT gallery support (backend/core changes)

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#21858]
This issue is to track the investigation and implementation of NFT support on Solana.

**Comment by yrliou** [comment]
From a quick look at it, it's just SPL token and the supply is 1.
https://spl.solana.com/token#example-create-a-non-fungible-token
Token is created with 0 decimals and only one token will be mint at first, then minting will be disabled, after that there will be only one and only token.

**Comment by bbondy** [comment]
This issue should include displaying it in the gallery

**Comment by yrliou** [comment]
For basic support (display correct quantity and show it as NFT), see https://github.com/brave/brave-browser/issues/25864
To display its meta data (like actual images) in the gallery, we need to do implement meta data parsing specific to Solana NFT.

**Comment by nvonpentz** [comment]
I found these steps for retrieving Solana NFT metadata https://gist.github.com/TomLisankie/0ccb57bdb82d9bf464aa9b9786e213e3.

Based on https://github.com/brave/brave-browser/issues/25864#issuecomment-1297575252, I gather that we will already have the NFT account(s) and those will be supplied as arguments to the metadata mojo API.  So we should be able to skip steps (1) and (2) for now, though those could be used for Solana asset discovery.  We would implement steps (3) through (5), and hopefully could reuse existing code for steps (6) - (8).
