### ISSUE TITLE
Cannot use the Trello website

### ISSUE THREAD

**Issue by MrTeeXD** [brave/brave-browser#2185]
## Description 
I cant use the Trello.com website and access my own board on there because it does not fully load the website and i cannot log in there.

## Steps to Reproduce

   1. Go to trello.com
   2. Try logging in to your account
   3. See error by looking at your own board not loaded correctly

## Actual result:
Trello looks like this now in Brave : 
![screenshot 80](https://user-images.githubusercontent.com/37266538/48723843-64e33f80-ec30-11e8-964d-f9fb0f3ef462.png)

## Expected result:
I want it to look like this : 
![screenshot 84](https://user-images.githubusercontent.com/37266538/48724222-4fbae080-ec31-11e8-8579-b286260bb47e.png)

## Reproduces how often: 
Everytime

## Brave version (brave://version info)
My OS is Windows 10 and my Brave version is 0.57.6 with Chromium 71.0.3578.31

### Reproducible on current release:
- It does reproduce on Brave Beta

### Website problems only:  
When i disable and enable the shields, it does not fix the problem, it just stays there

### Additional Information
Please get this fixed

**Comment by vegasje** [comment]
I am able to load Trello without issue on macOS 10.13.6 and Brave 0.56.12.

Possible this is limited to Windows?

**Comment by tomlowenthal** [comment]
Does the same thing happen with Shields down?

**Comment by MisterTeeXD** [comment]
Update : Trello.com managed to load in a Private Tor Tab with no problem and does not load in a new public tab.

**Comment by ron7684** [comment]
No issues for me on Windows 10 1803 (17134.472) with Brave 0.58.16
