### ISSUE TITLE
When hovered on Wallet icon in the Sidebar, tooltip text should read as Brave Wallet

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#21864]
## Description 

When hovered on Wallet icon in the Sidebar, tooltip description should read Brave Wallet

## Steps to Reproduce

   1. Install 1.37.x
   2. Launch Brave
   3. Hover over `Wallet ` favicon in the `Sidebar`

## Actual result:

 The tooltip text shows `Wallet`
<img width="1000" alt="Wallet tooltip text" src="https://user-images.githubusercontent.com/98358127/159987578-7f182855-85a7-4a49-9f92-e690c821b9c9.png">

## Expected result:
 The tooltip text should display `Brave Wallet`

## Desktop Brave version:

Brave | 1.38.67 Chromium: 100.0.4896.46 (Official Build) beta (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:
 N/A

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes ([Version 1.39.2 Chromium: 100.0.4896.46)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
@rebron

**Comment by MadhaviSeelam** [comment]
Verified `Passed` using

Brave | 1.39.10 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

`Brave Wallet` widget text is correctly displayed in the Sidebar when hovered over

<img width="950" alt="Brave Wallet" src="https://user-images.githubusercontent.com/98358127/160478518-85306257-c85a-4225-a912-ee0cf994793a.png">

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.39.18 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed the tooltip now reads `Brave Wallet`

![Uploading Screen Shot 2022-03-30 at 12.37.20 PM.png…]()
