### ISSUE TITLE
Mouse pointer Figma design show hand pointer but 1.37.x install show arrow

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#21865]
## Description 
Mouse pointer Figma design show hand pointer but 1.37.x install show Arrow

## Steps to Reproduce

   1. Install 1.37.x
   2. Launch Brave
   3. Hover over on any favicons  eg. Brave Talk

## Actual result:
Mouse pointer is Arrow

<image width = "1000" alt="mouse pointer" src="https://user-images.githubusercontent.com/98358127/159990356-f3191570-8560-4fda-800c-2d7f4ad637ab.png">

## Expected result:
Mouse pointer should be hand pointer as per the Figma mockup

## Reproduces how often: 
 Easily

## Desktop Brave version:

Brave | 1.38.67 Chromium: 100.0.4896.46 (Official Build) beta (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:
 N/A

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Yes (Version 1.39.2 Chromium: 100.0.4896.46)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
@rebron

**Comment by aguscruiz** [comment]
@rebron changed!
https://www.figma.com/file/xOdKFSr3P5AXSAbP2r8ung/?node-id=3693%3A65920

**Comment by rebron** [comment]
Closing as fixed. Thanks @aguscruiz
