### ISSUE TITLE
Use redux hooks in transaction confirmation panel - subtask of #21382

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#21869]
## Description 
Subtask of https://github.com/brave/brave-browser/issues/21382

Use react-redux hooks to alleviate ["prop-drilling"](https://kentcdodds.com/blog/prop-drilling#what-is-prop-drilling) in the **Transaction Confirmation panel screen.**

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified transaction panel is retained after a successful transaction</li>
         <li>Verified clicking on the hash in transaction panel opens the block explorer and closes the panel</li>
         <li>Verified transaction status is updated when the transaction panel is kept open</li>
        </ul>
      </td>
   </tr>
</table>
