### ISSUE TITLE
When Brave Wallet is selected second time/subsequently, the focus sets to password unlock page always instead of the existing page

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#21861]
## Description 
When Brave Wallet selected second time/subsequently, the focus sets to password unlock page always instead of the existing page

## Steps to Reproduce

   1. Install `1.37.x `
   2. Launch `Brave`
   3. Click `Wallet `on the `Sidebar`
   4. `Welcome to the new Brave Wallet` onboarding page is displayed
   5. Click Get Started and setup password
   6. Wallet portfolio page is displayed
   7. Close and relaunch the browser 
   8. Click on `Wallet `in the `Sidebar` again

## Actual result:

   `Enter password to unlock wallet` page displayed

## Expected result:
  As per the user story, when Wallet is selected again, the focus sets on the existing page. In my testing it should be `Wallet `portfolio page.

## Desktop Brave version:

Brave | 1.38.67 Chromium: 100.0.4896.46 (Official Build) beta (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:
 N/A

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes ([Version 1.38.67 Chromium: 100.0.4896.46)

## Other Additional Information: 

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
@rebron

**Comment by srirambv** [comment]
Closing and relaunching browser locks the wallet. So seems to be working as expected. @MadhaviSeelam can you mention which user story is this about? Also just to be sure you are relaunching the browser and not just closing the wallet tab correct because step 8 doesn't mention about launching browser when step 7 says close browser

**Comment by MadhaviSeelam** [comment]
Closing the issue as the functionality working as expected.  Closing `wallet `tab and reselecting it from `Sidebar` sets the focus on existing page.  Closing and relaunching the browser locked wallet.
