### ISSUE TITLE
Greaselion temp folders are not cleaned up when extensions are updated

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#21866]
## Description

When Greaselion updates its extensions (for example, because Greaselion scripts have been updated or because the user has changed a relevant preference), the folders containing unloaded extensions are not cleaned up until the browser is closed.

## Expected Result

When Greaselion extensions are updated, the folders for unloaded extensions should be cleared.

**Comment by bsclifton** [comment]
Might be a duplicate of https://github.com/brave/brave-browser/issues/21210

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)
```

**Comment by HaruRose** [comment]
May seem late and out of place now, but I've just deleted 50GB and 320.000 files from my temp folder, which was inside Greaselion extension.
