### ISSUE TITLE
wallet mnemonic issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#21874]
see https://bravesoftware.slack.com/archives/C03907M5KB3/p1648184045529289 for details

QA repro steps: https://bravesoftware.slack.com/archives/C03907M5KB3/p1648217135541719?thread_ts=1648212664.335699&cid=C03907M5KB3

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.37.107 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)
```

Verification notes can be found via https://github.com/brave/internal/issues/863#issuecomment-1081429637.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.107 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Ubuntu 18.04 LTS

Verified in https://github.com/brave/internal/issues/863#issuecomment-1081882151

**Comment by stephendonner** [comment]
Verification `PASSED` using 

Brave | 1.37.107 Chromium: 100.0.4896.46 (Official Build) (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)



Verified in https://github.com/brave/internal/issues/863#issuecomment-1082273072.
