### ISSUE TITLE
switching to a NTP with Brave News feed enabled feels janky (lots of flickering)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#21873]
## Description 

When you're switching to a NTP that has the Brave News feed visible, you'll notice that the entire experience seems pretty janky. Whenever you switch into a tab with Brave News enabled, you'll notice that the entire tab "flickers" and you'' sometimes see the Brave News feed quickly flicker before appearing in the NTP.

This could also be related to NTP generally taking longer to load background images which makes it seem pretty janky/not a smooth experience overall.

## Steps to reproduce 

   1. install brave and enable Brave news
   2. once enabled, leave a NTP that's displaying the widgets but also has the Brave News feed visible/enabled
   3. open a new tab and load a random website (used wikipedia.com on this instance)
   4. switch back and forth between the two tabs and notice the flicking/appearance of jank

## Actual result 

* example of the issue on `Pixel 6` --> https://youtu.be/TmkKwOXLt-0
* example of the issue on `Samsung Galaxy Tablet A` ---> https://youtu.be/9Z1lymhPMVg

## Expected result

Opening NTP with/without the Brave News feed should feel a lot smoother compared to what we have currently.

## Issue reproduces how often 

100% reproducible when using the STR/Cases outlined above. You should notice tabs "flickering" which gets worse with Brave News enabeld.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 12`
   
## Brave version

* `1.37.105 Chromium: 100.0.4896.46` - **Reproduced**
* 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @alexsafe @bsclifton @anthonypkeane @Uni-verse @srirambv @mattmcalister

**Comment by timchilds** [comment]
@kjozwiak I see the same flickering behavior on my device (Samsung Galaxy A51 / Android 11).

**Comment by timchilds** [comment]
Unsure if this is related, but I also see a red border flicker when initially opening the app. Perhaps some excess gpu load issue. https://stackoverflow.com/questions/13453131/disable-the-red-border-in-android-ics

https://user-images.githubusercontent.com/28269287/160203461-8a218fab-3738-4bbc-ab7c-0e2ba6a3b838.mp4

**Comment by kjozwiak** [comment]
Above requires `1.38.98` or higher for `1.38.x` verification.

**Comment by Uni-verse** [comment]
Verified using `1.38.99, Chromium 100.0.4896.51`

Devices: 
Samsung Galaxy S21 | Android 12

- Ensured switching/opening NTP with Brave News feed enabled does not produce alot of flickering. Although, there still seems to be some flickering during the transition but it's an improvement i think. 

https://user-images.githubusercontent.com/17885425/164086515-043a5043-1e9c-49cd-a711-004db5aee9de.mp4
