### ISSUE TITLE
Tap on the Private tab favicon on the top right corner in the normal window opens up the normal window with Private tab content

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#21877]
## Description 

Tap on the Private tab favicon on the top right corner in the normal window opens up the normal window with Private tab content
## Steps to reproduce 

1. Clean profile 1.37.105
2. Click on the 3 dot menu and select `New Private tab` 
3. Confirmed private tab is shown as expected
4. In the Private tab, click on the 3 dot menu and select `New tab`
5. Confirmed Normal tab is shown as expected
6. Tap on the Private tab favicon on the top right corner in the normal window
7. Private tab is not shown, instead Private tab content `This is a private Tab` is shown on the Normal tab background
8. Repeat step 6 multiple times and observed the same result as step 7

## Actual result 

Tap on the Private tab favicon on the top right corner in the normal window opens up the normal window with Private tab content
## Expected result
Tap on the Private tab favicon on the top right corner in the normal window should open up the Private tab 
## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes in 1.36.116
- Can you reproduce this issue with the current Play Store Beta version? Not sure
- Can you reproduce this issue with the current Play Store Nightly version?Not sure

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Tab A7
   - Android version: Android 11
   
## Brave version
1.37.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik @SergeyZhukovsky @anthonypkeane @brave/qa-team @bsclifton

**Comment by kjozwiak** [comment]
Above requires `1.37.107` or newer for `1.37.x` verification.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarm64.apk_1.37.107`
