### ISSUE TITLE
Wire up Displaying Solana Transactions in UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21892]
## Description 
Wire up Displaying Solana Transactions in UI

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12853>brave/brave-core#12853</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169541613-41f5b155-c267-48f2-94cf-ef5235a6242e.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169542248-ac707340-d86e-4631-aef8-a139b836222e.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169542193-d2b7561b-a923-4529-847f-6b0855d1701a.mov>
      </td>
   </tr>
</table>
