### ISSUE TITLE
Display origin when performing actions in Brave Wallet (signing transactions etc.)

### ISSUE THREAD

**Issue by ugwst-sec** [brave/brave-browser#21904]
## Description 
This is a Brave Wallet Desktop feature request to display origin when performing actions such as:

signing transactions, creating token, personal signature, sending ETH / tokens etc.

Other crypto wallets such as metamask / coinbase wallet have this feature implemented to prevent any confusion / mistakes when performing these important actions.

## Steps to Reproduce
Invoke any action in Brave Wallet - origin is not shown.

(only when connecting to website)

## Actual result:
Origin not shown when executing wallet actions.

## Expected result:
Origin shown when executing wallet actions.

## Reproduces how often: 
Always.

## Miscellaneous Information:
Example; metamask; origin shown:

https://ugwst.com/metamask.png

**Comment by Liuminjin** [comment]
You have to synchronize your wallet and then you debug it

**Comment by yrliou** [comment]
This is currently blocked by https://github.com/brave/brave-browser/issues/21915 for the backend work.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13054> brave/brave-core#13054</a></li>
         <li>Verified origin is shown on wallet panel for all actions</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Signature request
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169243700-25e3807a-8eda-45af-81ea-30543d87e56e.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/169243934-8e364218-dfc1-4629-bfce-22813cf84729.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169242949-d4e08e67-54a4-454e-9770-678e2c2c2e1b.png>
      </td>
   </tr>
   <tr>
      <td>Add token 
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169243739-0fbda00e-f651-4924-a19f-8d1c08bf4db3.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/169244225-73e68232-59d5-4114-938b-2de2af817ac1.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169242734-794cd4f6-b790-43cc-8d89-a2721b6ddc80.png>
      </td>
   </tr>
   <tr>
      <td>Transaction details
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169243778-d508eb52-ae05-4468-b42f-a6f31341b975.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/169244670-d2396de5-c0df-4372-afec-2d29e8bd58e3.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169243326-e91e3742-93de-4334-a25b-4035c1c12764.png>
      </td>
   </tr>
</table>
