### ISSUE TITLE
Store initiator origin info for DAPP requests

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#21915]
We need to store initiator's origin for dapp requests that would prompt UI for user to confirm.

See `BraveWalletJSHandler::SendAsync`, `BraveWalletJSHandler::Send`, `BraveWalletJSHandler::Request` for entry points.
See `BraveWalletProviderImpl::CommonRequestOrSendAsync` for how backend start to process different methods. 

Besides sendEthTransaction requests that would be get from pending transactions. UI get those pending requests in https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/panel/async/wallet_panel_async_handler.ts#L171-L194. We need to provide initiator's origin for all these DAPP requests to UI.

https://github.com/bbondy/eth-manual-tests and https://metamask.github.io/test-dapp/ might be useful for testing.

**Comment by yrliou** [comment]
eTLD+1 is also needed to be stored, see https://github.com/brave/brave-core/pull/12701.

**Comment by diracdeltas** [comment]
does this also need to be done for iOS/android? i noticed https://github.com/brave/brave-ios/issues/5218

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.96 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22616.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Same domain
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168072885-4b2c95dc-52f3-47fc-b049-5b75039d6451.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/168077543-25316926-a2f7-4d3e-9760-886932f5fb7f.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168077355-817d2961-9499-4e5c-97bb-eee8ab32f844.png>
      </td>
   </tr>
   <tr>
      <td>Different domain
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168072941-93a2df8e-c8c9-447b-83f5-cd2f527de41f.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/168077606-0fb2626a-16b6-474a-8af1-a0b525acfbbf.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168077375-de0b13cf-a368-46db-8d3c-029d8193ddbe.png>
      </td>
   </tr>
</table>
