### ISSUE TITLE
Labels for settings in the Shields v2 Panel and settings page don't match design

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#21916]
Not linking to the gdoc (its in the figma file) but the labels for many of the drop-down options in the shields panel and brave://settings/shields have not been updated to match the new discussed labels.

**Comment by nullhook** [comment]
we'll update labels on `brave://settings/shields` as a follow up issue to shields panel v2. This issue would only resolve on v2 panel first. cc @rebron

**Comment by kjozwiak** [comment]
Above requires `1.38.85` or higher for `1.38.x` verification.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.105 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

I re-tested with the above build, didn't update new screenshots.

Verification notes can be found in https://github.com/brave/brave-browser/issues/22084#issuecomment-1106033737.

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.38.105 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

#### 1. `Shields Panel`: Verified over in https://github.com/brave/brave-browser/issues/22084#issuecomment-1106033737

#### 2. `brave://settings/shields`: Will be verified over in https://github.com/brave/brave-browser/issues/21926

#### 3. `Shields Panel & "brave://settings/shields"`: Both also extensively tested both explicitly and implicitly via https://github.com/brave/brave-browser/issues/18630#issuecomment-1101766982
