### ISSUE TITLE
Show full url like in Chrome

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#2192]
## Description 

Everytime I click on the URL, I have to click another time so it shows the full URL with https://.
This is so annoying! Chrome removed it few months ago, and Brave should as well.

**Comment by fmarier** [comment]
This corresponds to the "Omnibox UI Hide Steady-State URL Scheme" feature flag in `chrome://flags`. Disabling it will always show the full URL.

**Comment by Liunkae** [comment]
Thanks @fmarier! Disabling `#omnibox-ui-hide-steady-state-url-scheme` in brave://flags does show the https protocol part of the URL.

![](https://user-images.githubusercontent.com/19424103/50241376-f6a7af00-038c-11e9-966d-72a04020e2f3.png)

![](https://user-images.githubusercontent.com/19424103/50241422-15a64100-038d-11e9-96b5-617547e5d6ba.png)

**Comment by LlamaFarma** [comment]
Is it just me, but this doesn't work for me fully. 

For instance, if I go to www.google.com, it shows in the address bar as https://google.com.
If I click twice in the address bar it changes to the 'real' URL and shows https://www.google.com. 
When I click away, the www goes. 

I find this really annoying - I want to know the exact URL I'm on. Is there any way to fix it?

**Comment by Liunkae** [comment]
@LlamaFarma You also need to disable the setting `#omnibox-ui-hide-steady-state-url-trivial-subdomains`
Go to `brave://flags#omnibox-ui-hide-steady-state-url-trivial-subdomains` and change it to Disabled:
![](https://user-images.githubusercontent.com/19424103/54629316-53c30780-4a45-11e9-95f3-35997cc21fca.png)

**Comment by LlamaFarma** [comment]
Thanks - that worked @Liunkae . 
So, to summarise - if you want it to work the same way as Chrome, you need to disable both these settings...
#omnibox-ui-hide-steady-state-url-scheme
#omnibox-ui-hide-steady-state-url-trivial-subdomains

**Comment by Madis0** [comment]
Hiding the protocol is fine - the lock/warning icon displays the status more accurately anyway (mixed content and whatnot). 

However, hiding the `www.` is what received the huge backlash for a good reason - it is simply inaccurate. See also: https://bugs.chromium.org/p/chromium/issues/detail?id=883038

**Comment by drauch** [comment]
Yep, please set "#omnibox-ui-hide-steady-state-url-trivial-subdomains" to Disabled by default! :+1:

**Comment by rebron** [comment]
Looks like this was addressed with https://github.com/brave/brave-browser/issues/4283 
cc: @jumde 

We're showing full url by default in nightly and we'd be reverting from what we're doing in current release build. cc: @toml

**Comment by bsclifton** [comment]
Thanks for confirming, @rebron - this is indeed closed. I'll move it to the 0.68.x milestone 😄

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.119 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

Verified steps from the description

![image](https://user-images.githubusercontent.com/34715963/62657307-7ad39480-b966-11e9-9dcd-1190790c12bb.png)
