### ISSUE TITLE
Continue executing all cosmetic scriptlets even if one fails

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#21932]
https://github.com/brave/adblock-lists/pull/811 was intended to fix the anti-Brave page on https://www.uploadbank.com/yt9ri1rtc0fg, but the scriptlets are not injecting correctly. Each scriptlet needs to be wrapped in a try/catch block to prevent this from happening, like uBlock Origin does.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.39.18 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 11.6.5 (Build 20G527)

### Steps:
1. installed `1.39.18`
2. launched Brave
3. loaded `https://www.uploadbank.com/yt9ri1rtc0fg`
4. clicked on pictures of trains
5. clicked a checkbox
6. clicked `Download`

#### Confirmed I was presented with the `VLC` file download, without any interstitial pages warning about using Brave.

`1.36.122` | `1.37.109` | `1.39.18` (1) | `1.39.18` (`2`) | `1.39.18` (`3`) | `1.39.18` (`4`) | `1.39.18` (`5`)
---------|---------|---------------|---|--|--|--
<img width="1312" alt="Screen Shot 2022-03-30 at 2 13 09 PM" src="https://user-images.githubusercontent.com/387249/160933624-e51fbea1-d4b6-43ac-89fb-2c8718d42029.png"> | <img width="1312" alt="Screen Shot 2022-03-30 at 2 18 38 PM" src="https://user-images.githubusercontent.com/387249/160933664-6012cb41-b569-4f0c-acdb-4e90e9b1e8c2.png"> | <img width="1609" alt="Screen Shot 2022-03-30 at 2 13 47 PM" src="https://user-images.githubusercontent.com/387249/160933740-84e9d853-748f-4edc-814c-346d03db2e55.png"> |<img width="1609" alt="Screen Shot 2022-03-30 at 2 14 03 PM" src="https://user-images.githubusercontent.com/387249/160933748-26368bc5-c4bb-4ffd-bff4-24a9657b75db.png"> | <img width="1609" alt="Screen Shot 2022-03-30 at 2 14 07 PM" src="https://user-images.githubusercontent.com/387249/160933752-80db4f1d-d92b-43f3-9fe5-b6979408bc07.png"> | <img width="1609" alt="Screen Shot 2022-03-30 at 2 14 14 PM" src="https://user-images.githubusercontent.com/387249/160933754-3489f1f5-b6d1-4661-b091-7fe2edf0d3e7.png"> | <img width="1609" alt="Screen Shot 2022-03-30 at 2 14 17 PM" src="https://user-images.githubusercontent.com/387249/160933756-a1b321af-6526-49c8-9e6e-bd008d7399f9.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.38.75 Chromium: 100.0.4896.60 (Official Build) beta (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 11.6.5 (Build 20G527)

### Steps:
1. installed `1.38.75`
2. launched Brave
3. loaded `https://www.uploadbank.com/yt9ri1rtc0fg`
4. clicked through acknowledgement checkboxes and a CAPTCHA
5. clicked on `Download`


#### Confirmed I was served the correct file without any warnings

example | example | example | example | example
---------|---------|----------|---------|----------
<img width="1788" alt="Screen Shot 2022-03-31 at 12 03 58 PM" src="https://user-images.githubusercontent.com/387249/161130752-3ca89c25-ee8d-4c9e-b53d-112a4efe5847.png"> | <img width="1788" alt="Screen Shot 2022-03-31 at 12 04 13 PM" src="https://user-images.githubusercontent.com/387249/161130761-e0cd1e1c-37da-490c-bfec-c425823c7494.png"> | <img width="1788" alt="Screen Shot 2022-03-31 at 12 04 16 PM" src="https://user-images.githubusercontent.com/387249/161130768-a07e13c9-e871-486b-a5bc-07151db00a46.png"> | <img width="1788" alt="Screen Shot 2022-03-31 at 12 04 20 PM" src="https://user-images.githubusercontent.com/387249/161130770-4dd75cc5-6923-49cf-983d-1526ae1cea71.png"> | <img width="1788" alt="Screen Shot 2022-03-31 at 12 04 24 PM" src="https://user-images.githubusercontent.com/387249/161130773-0b4f99ae-34b5-4dae-b0ee-58a62b8ed48b.png">

**Comment by MadhaviSeelam** [comment]
Verified `Passed` using

Brave | 1.38.80 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 21H2 (Build 22000.593)


Steps:

> - Installed `1.38.80`
> - launched `Brave`
> - loaded `https://www.uploadbank.com/yt9ri1rtc0fg`
> - clicked through acknowledgement checkboxes and a CAPTCHA
> - clicked on `Download`

- Confirmed I was served the correct file without any warnings/roadblocks/interstitials

ex1|ex2|ex3|ex4|ex5
---|---|---|---|---
<img width="950" alt="screenshot1" src="https://user-images.githubusercontent.com/98358127/161831961-d0b17622-87bc-4911-a65a-c67db137e9ea.png">|<img width="950" alt="screenshot2" src="https://user-images.githubusercontent.com/98358127/161832111-af5dc136-14c9-4bb8-b79b-e42a2f632eaf.png">|<img width="950" alt="screenshot3" src="https://user-images.githubusercontent.com/98358127/161832252-47c1cd56-76c0-4b38-af89-c4d8de8d8c78.png">|<img width="930" alt="screenshot4" src="https://user-images.githubusercontent.com/98358127/161832541-e9e230da-dbfe-4b8f-ba49-bf25d79a836c.png">|<img width="950" alt="screenshot5" src="https://user-images.githubusercontent.com/98358127/161832676-f3dbe7e5-baa3-4d68-b450-9922b6b7fb81.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

- Confirmed I was served the correct file without any warnings/roadblocks/interstitials

![image](https://user-images.githubusercontent.com/34715963/162809089-de3a57ee-0b71-4a12-8051-da0fb0151b41.png)|![image](https://user-images.githubusercontent.com/34715963/162809115-651ebacf-ed5b-4251-8442-b6e0a6de1a97.png)|![image](https://user-images.githubusercontent.com/34715963/162809168-03aa1ed8-1ca4-4643-aef6-dfad914fa020.png)|![image](https://user-images.githubusercontent.com/34715963/162809204-169526f6-fce4-4cf8-976a-24dfeb64040c.png)|![image](https://user-images.githubusercontent.com/34715963/162809229-1225a63e-69cf-466c-936b-d97e434889bd.png)
--|--|--|--|--

**Comment by Uni-verse** [comment]
Verification completed using `1.38.103, Chromium 100.0.4896.127` on `Samsung Galaxy S21` running `Android 12`

- Confirmed I was served the correct file without any warnings/roadblocks/interstitials

1 | 2 | 3 | 4 | 5
-|-|-|-|-
![Screen Shot 2022-04-20 at 4 50 27 PM](https://user-images.githubusercontent.com/17885425/164343222-a8c6c46e-f089-4ef7-aa6b-48fe083e8e13.png) | ![Screen Shot 2022-04-20 at 4 51 10 PM](https://user-images.githubusercontent.com/17885425/164343223-0c4f8608-942b-4da8-acbd-5c5e31338624.png) | ![Screen Shot 2022-04-20 at 4 51 28 PM](https://user-images.githubusercontent.com/17885425/164343224-c49215e5-c2a9-4f3a-bf38-354218d43364.png) | ![Screen Shot 2022-04-20 at 4 52 28 PM](https://user-images.githubusercontent.com/17885425/164343228-fdf2ffe8-205a-4c24-a1a5-79ddf5b7afaf.png) | ![Screen Shot 2022-04-20 at 4 49 13 PM](https://user-images.githubusercontent.com/17885425/164343217-77ee60ca-0363-4eaf-96ea-e2014ffa4e38.png)

**Comment by Uni-verse** [comment]
Verification completed using `1.38.103, Chromium 100.0.4896.127` on `Samsung Galaxy Tab S7` running `Android 12`

Test URL: https://www.uploadbank.com/yt9ri1rtc0fg

- Confirmed I was served the correct file without any warnings/roadblocks/interstitials

1 | 2 | 3 | 4
-|-|-|-
![Screen Shot 2022-04-20 at 4 58 17 PM](https://user-images.githubusercontent.com/17885425/164343837-6f8fe6f9-6624-4860-9770-4c62c1cc582a.png) | ![Screen Shot 2022-04-20 at 4 58 35 PM](https://user-images.githubusercontent.com/17885425/164343838-e384219d-94e0-4f05-8aee-9680263d1df3.png) | ![Screen Shot 2022-04-20 at 4 58 49 PM](https://user-images.githubusercontent.com/17885425/164343841-9f125798-b66b-4203-b9fd-8dbff6b8c4e9.png) | ![Screen Shot 2022-04-20 at 5 01 43 PM](https://user-images.githubusercontent.com/17885425/164343842-42eed706-ae06-49b0-b079-873d8b60ab75.png)
