### ISSUE TITLE
Brave should find and cleanup older versions and offer upgrade

### ISSUE THREAD

**Issue by danielandastro** [brave/brave-browser#2193]
## Description 
Brave browser should find older versions of brave on first launch and offer to import and do cleanup of installation

It should import data, then uninstall it

Brave should also give users a prompt to upgrade to Brave-Browser

**Comment by Liunkae** [comment]
For the last item, see brave/browser-laptop#15315.

**Comment by srirambv** [comment]
Migration process will auto import bookmarks/stats/history/payments etc. Please see the [project board](https://github.com/brave/brave-browser/projects/12) for muon-b-c migration. This will give you a clear idea as to what is being done for migration.

**Comment by bbondy** [comment]
We will leave it installed for the user to uninstall but we will do an upgrade as of 0.57.x

**Comment by nirholas** [comment]
Glad this being fixed. I wanted to keep my initial install with wallet along with tracker, ad, https, time saved on my browser. The obvious solution was backing up your wallet from you initial install then  downloading a fresh version of Brave and importing the initial wallet into the new browser. Thanks for the updates!
