### ISSUE TITLE
Crash on Mac Nightly

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#21934]
Reported by @ShivanKaul: 
`I just got a crash when clicking on Brave Shields in Nightly for https://d3ward.github.io/toolz/adblock.html. I got it twice in a row but seems fine now.
`

<pre>
Brave Version: 1.38.60  Chromium: 100.0.4896.46
Operating System: Mac OS X 11.6.0
Uploaded Crash Report ID:	70f40200-a473-f107-0000-000000000000
</pre>

The crash stack tip:
<pre>
1
<…>
‎/Users/jenkins/jenkins/workspace/brave-browser-build-macos-x64-nightly/src/out/Release/../../ui/base/resource/resource_bundle.cc:1162
2
l10n_util::GetStringUTF16
‎/Users/jenkins/jenkins/workspace/brave-browser-build-macos-x64-nightly/src/out/Release/../../ui/base/resource/resource_bundle.cc:771
3
…::ToolTask::ToolTask
‎/Users/jenkins/jenkins/workspace/brave-browser-build-macos-x64-nightly/src/out/Release/../../chrome/browser/task_manager/providers/web_contents/tool_task.cc:17
4
…::ToolTag::CreateTask
‎/Users/jenkins/jenkins/workspace/brave-browser-build-macos-x64-nightly/src/out/Release/../../buildtools/third_party/libc++/trunk/include/__memory/unique_ptr.h:725
5
…::WebContentsEntry::CreateTaskForFrame
‎/Users/jenkins/jenkins/workspace/brave-browser-build-macos-x64-nightly/src/out/Release/../../chrome/browser/task_manager/providers/web_contents/web_contents_task_provider.cc:337
6
…::WebContentsObserverList::NotifyObservers<…>
‎/Users/jenkins/jenkins/workspace/brave-browser-build-macos-x64-nightly/src/out/Release/../../content/browser/web_contents/web_contents_impl.h:1516
7
<…>
</pre>

**Comment by LaurenWags** [comment]
cc @rebron since this is 1.38.x / shields v2

**Comment by nullhook** [comment]
this should be fixed: https://github.com/brave/brave-core/pull/12984

**Comment by kjozwiak** [comment]
Above requires `1.38.102` or higher for `1.38.x` verification.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (x86_64)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | macOS Version 11.6.5 (Build 20G527)

With both existing and new profiles, loaded `https://d3ward.github.io/toolz/adblock.html` and toggled Shields `DOWN`/`UP` without issue/crashing.
