### ISSUE TITLE
Handle big numbers for TokenId's in UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21939]
## Description 
We need to handle big numbers for `ERC721` tokenId's in the UI
![Screen Shot 2022-03-28 at 1 36 43 PM](https://user-images.githubusercontent.com/40611140/160473929-e120e323-b8ac-4bd4-9b72-ac3521e2a122.png)

![Screen Shot 2022-03-28 at 1 47 26 PM](https://user-images.githubusercontent.com/40611140/160475430-789452ce-ca09-4b20-81d1-c35f58fba5b9.png)

**Comment by muliswilliam** [comment]
@Douglashdaniel Should we show an ellipsis if the number id past a certain length?

**Comment by Douglashdaniel** [comment]
Is no longer an issue, closing as `Invalid`
