### ISSUE TITLE
Add `isBraveWallet` property to `window.ethereum`

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#21949]
## Description 
A standard being used by web3 apps is to check that an injected wallet is present using `window.ethereum[is<WalletName>]`
eg. `window.ethereum.isMetaMask`

We already set `window.ethereum.isMetaMask` to `true` for compatibility with MetaMask

We should also set `window.ethereum.isBraveWallet` to `true`, so that web apps can detect that Brave Wallet is available for connecting

## Actual result:
`window.ethereum.isMetaMask` is `true`
`window.ethereum.isBraveWallet` is undefined

## Expected result:
`window.ethereum.isMetaMask` is `true`
`window.ethereum.isBraveWallet` is `true`

## Miscellaneous Information:

Example of a library checking for injected providers: https://github.com/Web3Modal/web3modal/blob/master/src/providers/injected/index.ts

**Comment by kjozwiak** [comment]
Above requires `1.38.82` or newer for `1.38.x` verification.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">  1.38.106 Chromium: 101.0.4951.41 (Official Build)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12794>brave/brave-core#12794</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165086456-a03bdb4b-dc1f-467d-9970-16957305c3b1.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165086299-68b4d801-ec86-4cf3-b487-4254994a9bf1.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165086257-bd08e0aa-e261-4eab-968f-25a08eaf34b7.mov>
      </td>
   </tr>
</table>

**Comment by PvanHengel** [comment]
Hi - we are trying to use this from iOS Mobile, and it does not seem to be set I see @srirambv  and @avinassh posted about this, but I have the latest version and it does not seem to be working?  Any update on iOS / Android?  Is there another way to detect we are using the brave wallet?

**Comment by josheleonard** [comment]
> Hi - we are trying to use this from iOS Mobile, and it does not seem to be set I see @srirambv and @avinassh posted about this, but I have the latest version and it does not seem to be working? Any update on iOS / Android? Is there another way to detect we are using the brave wallet?

You can try [this method](https://wallet-docs.brave.com/ethereum/wallet-detection/#asynchronous-detection-using-web3_clientversion) for detecting Brave. I verified that isBraveWallet detection is working on Android.

**Comment by StephenHeaps** [comment]
> Hi - we are trying to use this from iOS Mobile, and it does not seem to be set I see @srirambv and @avinassh posted about this, but I have the latest version and it does not seem to be working? Any update on iOS / Android? Is there another way to detect we are using the brave wallet?

Hey @PvanHengel, thanks for the report. We've opened an issue on the iOS repo to track this.
https://github.com/brave/brave-ios/issues/6059

**Comment by devstein** [comment]
Hi -- I updated my browser yesterday and now `window.ethereum.isBraveWallet` is no longer working. It's breaking connect modals like [Picket](https://picketapi.com/). Here is the error 

```
window.ethereum.isBraveWallet()
VM98:14 Uncaught TypeError: Illegal invocation: Function must be called on an object of type JSEthereumProvider
    at Reflect.get (<anonymous>)
    at Object.get (<anonym
```

**Comment by devstein** [comment]
Hi @josheleonard thank you! Setting brave as the default wallet in `brave://settings/web3` fixed it for me. When did this behavior change? `window.ethereum.isBraveWallet` used to be `undefined` rather than throw an error. I've been using Brave and `window.ethereum.isBraveWallet` for almost a year without issue.

**Comment by josheleonard** [comment]
@devstein , this may have been caused by this PR: https://github.com/brave/brave-core/pull/15498
We are looking into this now

**Comment by yrliou** [comment]
@devstein I can't seem to reproduce on v1.49.120 for that error, what `Default Ethereum wallet` setting did you have as the brave://settings/web3 before?
I tested with it set as extension and have metamask installed, can connect without issue and running `window.ethereum.isBraveWallet` in the console returns `undefined` for me.
