### ISSUE TITLE
getERC721TokenBalance Parsing Error

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21941]
## Description 
The `getERC721TokenBalance` method is returning an error if the current `SelectedNetwork` is not the same as the `Tokens` network.

```
balance: ""
error: -32700
errorMessage: "A response parsing error has occurred"
```

https://user-images.githubusercontent.com/40611140/160478455-a80609f1-c6e8-4e1c-aaf4-c2f0f4c9546e.mov

**Comment by yrliou** [comment]
It's because when we added chain_id to GetERC721TokenBalance, we forgot to update GetERC721OwnerOf and pass chain_id into it to let it use the right network.

**Comment by kjozwiak** [comment]
Added missing `1.39.x` milestone as this landed in `master` via https://github.com/brave/brave-core/pull/12790.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">  1.38.106 Chromium: 101.0.4951.41 (Official Build)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12790>brave/brave-core#12790</a></li>
         <li>Verified NFT Tokens are listed even when network is changed and page is refreshed</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165085131-393c5fed-8a8f-4819-9e88-50331e4e406b.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165084267-ae93014b-2a45-4f81-a506-96dc1173b811.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165084254-30933eae-67cc-42e9-b1d4-b20c4e659fd7.mov>
      </td>
   </tr>
</table>
