### ISSUE TITLE
Brave Shields blocked-count tooltip should be multi-line

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21943]
## Description 

Brave Shields blocked-count tooltip should be multi-line

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `cnn.com`
   4. hover over the Shields icon
   5. read the tooltip

## Actual result:

Tooltip text is a single line; see below

<img width="875" alt="160472514-1ee9ec4c-2b62-40c6-9251-685431f7e503" src="https://user-images.githubusercontent.com/387249/160485234-1033ab6a-edad-4780-85f5-c730796e31f3.png">

## Expected result:

It should be a multi-line tooltip, per https://github.com/brave/brave-browser/issues/17369#issuecomment-1081129578

![128423351-dc0685f7-e3cf-4fd8-b14f-82aba45a965f](https://user-images.githubusercontent.com/387249/160485445-cf1e4401-0373-4df0-a4cb-5c87583b52f3.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.10 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 11.6.5 (Build 20G527)

cc @jenn-rhim @nullhook

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.39.18 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 11.6.5 (Build 20G527)


<img width="375" alt="Screen Shot 2022-03-30 at 12 18 53 PM" src="https://user-images.githubusercontent.com/387249/160913897-32aaa4dc-2c68-419f-b289-8198db894dad.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

Brave | 1.39.83 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

Verified Brave Shields blocked-count tooltip is multi-line

- Installed 1.39.83 
- Launch Brave
- Load cnn.com
- Hover over the Shields icon
- Tooltip displayed multi-line

<img width="950" alt="shields" src="https://user-images.githubusercontent.com/98358127/165651905-54c5f1df-46e8-411f-a10c-c80fedea0d28.png">
