### ISSUE TITLE
Make Default button is not displayed in brave://settings

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#21954]
## Description 
`Make Default` button is not displayed in the `brave://settings` when `Maybe later` button selected on first run dialog on Windows

## Steps to Reproduce

<Summary>Scenario 1: `Make Default` button should be available in `brave://settings` </Summary>
<details>

   1. Clean install
   2. Launch `Brave`
   3. First run dialog `Ready for the best privacy online?` is displayed
   4. Clicked `Maybe later` to dismiss the dialog 
   5. Navigate to `brave://settings`
   6. Verify Default browser entry shows `Make default` button

## Actual result:
`brave://settings` displayed `Brave is your default browser` and `Make Default` button not available
However, 1.39.x - Nightly does display `Make default` button as expected

<img width="980" alt="dialog" src="https://user-images.githubusercontent.com/98358127/160507596-abee3ac7-486f-432b-b292-ad4823c3492b.png">

## Expected result:
Default browser entry should show "Make default" button
</details>

<Summary>Scenario 2: Click `x` on the dialog</Summary>
<details>

   1. Clean Profile
   2. Launch `Brave`
   3. First run dialog `Ready for the best privacy online?` is displayed
   4. Clicked `x` to dismiss the dialog 
   5. Navigate to `brave://settings`
   6. Verify Default browser entry shows `Make default` button

## Actual result:
`brave://settings` displayed `Brave is your default browser` and `Make Default` button not available
However, 1.39.x - Nightly does display `Make default` button as expected

<img width="980" alt="dialog" src="https://user-images.githubusercontent.com/98358127/160507596-abee3ac7-486f-432b-b292-ad4823c3492b.png">

## Expected result:
Default browser entry should show "Make default" button
</details>

<Summary>Scenario 3: The dialog should display buttons same order as the mockup </Summary>
<details>

   1. Clean install
   2. Launch `Brave`
   3. First run dialog `Ready for the best privacy online?` should be displayed
   4. Verify the dialog matches to the mockup

## Actual result:
The order is reversed in 1.38.x and dialog show "Set Brave as default" and "Maybe later" 

<img width="900" alt=" dialog" src="https://user-images.githubusercontent.com/98358127/160508277-b96627d2-b007-4da5-a857-05b749c55522.png">

## Expected result:
Mockup shows "Maybe later" and "Set Brave as default" order
</details>

## Reproduces how often: 

Easily

## Brave version (brave://version info)
Brave | 1.38.70 Chromium: 100.0.4896.46 (Official Build) beta (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.556)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
cc @simonhong

**Comment by GeetaSarvadnya** [comment]
@MadhaviSeelam Could you test this again? I have verified the issue, it's working for me. Please make sure brave is not set as the default browser prior to verifying this issue.

**Comment by MadhaviSeelam** [comment]
Closing this as scenario 1 &  scenario 2 are working as expected.  Filed a new issue for scenario 3 #22255
