### ISSUE TITLE
Move userAssetList methods out of Container

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#21962]
## Description 
We need to refactor and move `userAssetList`, `fullAssetBalance`, `fullPortfolioBalance` methods out of the `Page` container and into the `useAssets` and `useBalance` hooks.

**Comment by muliswilliam** [comment]
@Douglashdaniel The values are no longer in `container.tsx`, they are now accessed using PageSelectors. Do you think this refactor is still necessary

**Comment by Douglashdaniel** [comment]
This issue is no longer relevant, closing as `not-actionable`
