### ISSUE TITLE
Not obvious how to install extensions

### ISSUE THREAD

**Issue by flip111** [brave/brave-browser#2196]
Hi, i just installed brave on ubuntu 18.10 using these instructions https://brave-browser.readthedocs.io/en/latest/installing-brave.html#ubuntu-16-04

When i go to extensions and type in "search extensions" i don't find any extensions i want. So i think hmm what's up with that? Then i open chromium and i notice the same, so i'm actually searching in the extensions i have already installed (d0h). But i know in chromium it's possible to install extensions so i click the hamburger menu at the top left and see at the bottom "Open Chrome Web Store" aah there it is a found it. Then i go back to brave, no link to chrome webstore. I try to the chrome web store manually and i am actually able to install an extension. For me as younger person who is also into software it was already confusing, i can only imagine for people who are older or not as well versed into computer stuff how they should go about adding extra functionality in their browser. I think their only option now is being told by somebody else because i could not find anything in Brave browser about installing new extensions.

Also would be cool if brave would just offer to install the same extensions from chromium when importing bookmarks and such.

**Comment by srirambv** [comment]
There won't be any option similar to Chromium to open extension store from hamburger menu. But however if you visit `brave://extensions` it will provide a link to open Chrome Web Store  from there.
