### ISSUE TITLE
Remove GetEstimatedTime API that uses etherscan proxy

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#21979]
We have an API that we expose from etherscan for `GetEstimatedTime`.

Do we still use it? 
I didn't see it used on Desktop and Android front end. @nuo-xu @kylehickinson how about iOS
@SergeyZhukovsky and @Douglashdaniel could you confirm it's not used on Android and Desktop?

**Comment by nuo-xu** [comment]
@bbondy iOS does not use it.

**Comment by Douglashdaniel** [comment]
I see it in `brave_wallet.mojom` but doesn't look like it being used anywhere in the `Front-end` for `Desktop`.

**Comment by SergeyZhukovsky** [comment]
nothing on Android related to that as well
