### ISSUE TITLE
Allow linking Android purchased VPN to account.brave.com

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21972]
## Description 
We should add a new link in `Settings` > `Brave Firewall + VPN` section

- For spec, search Google Drive for `UX Flow for Redeeming VPN paid via Mobile IAP`
- Design issue https://github.com/brave/design/issues/16

New option would be something like (see design issue for exact copy):
`Link purchase to your Brave account to use on other devices`

Clicking would open the account page with a specific intent set. URL will be like https://account.brave.com/?intent=connect-receipt&product=vpn (see https://github.com/brave/account-brave-com/issues/24 for final details)

When that page is visited, the website will be able to read the receipt (see https://github.com/brave/brave-browser/issues/21942 and https://github.com/brave/account-brave-com/issues/24)

## Latest design (from Figma) - where the button is added
<img src="https://user-images.githubusercontent.com/4733304/195145446-31b6749c-2cae-4c08-843a-027810ee3cf4.png" width="256px">

![image](https://user-images.githubusercontent.com/4733304/195145624-4097f3e0-6a8b-4b4f-860a-41811bccef20.png)

**Comment by bsclifton** [comment]
Blocked on https://github.com/brave/brave-browser/issues/20374 - but we can at least create a mock up / finalize text

cc: @Sam-Sibley, @aguscruiz 
(for more info, hit me up on Slack!)

**Comment by aguscruiz** [comment]
I can take on this one @bsclifton. DM coming up

**Comment by bsclifton** [comment]
See Figma here:
https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/Mobile-VPN?node-id=1662%3A21300
