### ISSUE TITLE
Reduce adblock filter memory usage by optimizing unused regex rules

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#21970]
As discovered by @atuchin-m, there is an extra ~7MB that can be saved by optimizing the `regex` field of `NetworkFilter` in `adblock-rust`. [This was fixed in `adblock-rust`](https://github.com/brave/adblock-rust/pull/204) as of v0.5.2.

**Comment by atuchin-m** [comment]
For QA: we should verify, that browser process memory consumption became 7mb less.
A possible scenario:
1. Launch browser without the fix with one saved tab `about:blank`
2. Wait 15 sec.
3. Check browser process memory footprint in the internal task manager (see a screenshot)
4. Repeat a few times to make the results stable (3-5 times)
5. Repeat 1-4 for browser with the fix

**Comment by MadhaviSeelam** [comment]
Brave | 1.39.86 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

And 

Brave | 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)
And

Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.613)



Compared browser memory consumption on 1.39.86 to 1.38.109 and 1.37.105 and consumption is significantly less in Beta.  

1.39.86 Chromium: 101.0.4951.41
<details>

ex1|ex2|ex3|ex4|ex5
---|---|---|---|---
<img width="750" alt="Beta" src="https://user-images.githubusercontent.com/98358127/166075219-378a0d93-2d4b-4b45-af1e-e4e123e665ae.png">|<img width="750" alt="Beta2" src="https://user-images.githubusercontent.com/98358127/166075228-d086320c-c820-42be-9149-745517e94c93.png">|<img width="750" alt="Beta3" src="https://user-images.githubusercontent.com/98358127/166075242-252d7bd9-eb39-4eed-8b6c-a52fc5bd92ac.png">|<img width="750" alt="Beta4" src="https://user-images.githubusercontent.com/98358127/166075250-1f4c25e7-aad9-4016-8acb-d39ec261c59e.png">|<img width="955" alt="Beta5" src="https://user-images.githubusercontent.com/98358127/166075259-95dbca1d-e5fa-4ed8-9d7e-a51f90587348.png">

</details>

1.38.109 Chromium: 101.0.4951.41
<details>

ex1|ex2|ex3|ex4|ex5
---|---|---|---|---
<img width="750" alt="138-1" src="https://user-images.githubusercontent.com/98358127/166075637-73b4a579-898d-4156-bec4-78ce8d2d0b98.png">|<img width="750" alt="138-2" src="https://user-images.githubusercontent.com/98358127/166075667-d3a0320b-9f96-4e2d-92cb-89ec952e4c98.png">|<img width="750" alt="138-3" src="https://user-images.githubusercontent.com/98358127/166075678-602fd294-1a58-4c81-802e-36df6e892b55.png">|<img width="750" alt="138-4" src="https://user-images.githubusercontent.com/98358127/166075685-d61af186-f95a-40d5-a953-9b94efc8f656.png">|<img width="750" alt="138-2" src="https://user-images.githubusercontent.com/98358127/166075687-3a8759fd-63bc-4f6c-b6ef-111910c87a8d.png">

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.39.87 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)
```

Verified test plan from https://github.com/brave/brave-browser/issues/21970#issuecomment-1082626487.

Compared 1.38.109 (current Release channel version) and 1.39.87 (current Beta channel version).
Browser memory footprint was decreased in 1.39.x.

1.38.109 | 1.39.87
----- | -----
<img width="1190" alt="1 38 108" src="https://user-images.githubusercontent.com/28145373/166258958-8f0935fa-883d-4b4b-a82f-9ff5b1326fa9.png"> | <img width="1193" alt="1 39" src="https://user-images.githubusercontent.com/28145373/166258969-66080b7d-d2f1-4c71-aa45-41981ca02df9.png">

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.39.87 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
--|--
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

to compare against

Brave | 1.38.109 Chromium: 101.0.4951.41 (Official Build) (x86_64)
--|--
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

#### Confirmed, for my setup, that we dropped around 15MB in resident-set-size, on average.

`Build` | `Median`
------|-----
1.38.109 | 120 (120.4)
**1.39.87** | **105 (105.4)**

**Breakdown:**

`1.38.109` (in MB) | `1.39.87` (in MB)
---------|--------
119 | 110
121 | 105
119 | 105
124 | 103
119 | 104

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.100 Chromium: 101.0.4951.61 (Official Build) beta (64-bit)
-- | --
Revision | 3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS | Ubuntu 18.04 LTS

On 5 point average, 1.39.x uses 8MB less memory 

Example 1.38.x:
![image](https://user-images.githubusercontent.com/34715963/167883400-dd608ea6-b6ca-40ad-a39a-0f02d4e15c7c.png)

Example 1.39.x
![image](https://user-images.githubusercontent.com/34715963/167884600-4451498a-70c6-420a-b605-f07b20d1e4dc.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)
--- | ---
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Android 12; Build/SP1A.210812.016
```

**`1.38.119 (370.2 MB)`** | **`1.38.119 (318 MB)`** | **`1.38.119 (304.5 MB)`** | **`1.38.119 (302.4 MB)`** | **`1.38.119 (316.2 MB)`**
-------------------------|---------------------------|--------------------------|--------------------------|--------------------------
![image](https://user-images.githubusercontent.com/2602313/169887959-e86278f9-2c7d-4b5a-bf1c-6717a7776d30.png) | ![image](https://user-images.githubusercontent.com/2602313/169888529-948e798f-86bd-4c80-8b4f-8af66391711e.png) | ![image](https://user-images.githubusercontent.com/2602313/169888907-374cc6a2-ca71-4488-be16-b585870594c9.png) | ![image](https://user-images.githubusercontent.com/2602313/169891544-ee338729-6bae-4c04-872a-1e11032644c6.png) | ![image](https://user-images.githubusercontent.com/2602313/169892326-28525708-f1cb-4d84-a689-b2500eeeddc7.png)


**`1.39.111 (310.6 MB)`** | **`1.39.111 (314 MB)`** | **`1.39.111 (312 MB)`** | **`1.39.111 (297.7 MB)`** | **`1.39.111 (308.3 MB)`**
-------------------------|---------------------------|--------------------------|--------------------------|--------------------------
![image](https://user-images.githubusercontent.com/2602313/169889261-9e3dfe0c-2d9a-47b6-b87f-f59c06c27d5b.png) | ![image](https://user-images.githubusercontent.com/2602313/169892774-de8ca067-3c4e-4994-bf8e-1d4eeb2a47f8.png) | ![image](https://user-images.githubusercontent.com/2602313/169893142-d79486d8-95e7-4651-9f45-2058e3148b09.png) | ![image](https://user-images.githubusercontent.com/2602313/169893538-b12062a6-8aef-406b-94fe-0033dbec447f.png) | ![image](https://user-images.githubusercontent.com/2602313/169893947-4b20cec7-6fa7-47e0-9ef0-a48e16f00d04.png)
