### ISSUE TITLE
`Shields v2`: `Block cross-site cookies` should be `Block cookies` at `brave://settings/shields`

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#21983]
## Description 

Just a small typo.

## Steps to Reproduce

   1. Install `Brave Nightly`.
   2. Open `brave://settings/shields`.
   3. Check the text regarding cookies blocking.

## Actual result:

`Block cross-site cookies`

## Expected result:
Should be just `Block cookies` as setting up Brave to block all cookies will result in
![Untitled](https://user-images.githubusercontent.com/20608253/160898103-2f812566-e73b-417e-875a-a24cb78c9b88.png)

which doesn't make sense. Users wouldn't be able to tell whether all cookies are blocked or only third-party cookies are blocked.

Another confusion could occur when users set the setting to `Disabled`. That doesn't clearly state what cookies are blocked/allowed.

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.39.18 Chromium: 100.0.4896.60 (Official Build) nightly (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

@rebron @nullhook

**Comment by rebron** [comment]
Thanks for filing @Tonev. We should've checked first. Going to dupe this one though to #22035

**Comment by Tonev** [comment]
Weird decision, but it's all right since we got the issue fixed.
