### ISSUE TITLE
Passwords, Search Engine, and Autofill are not imported from Firefox

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2198]
## Description 
Passwords, Search Engine, and Autofill are not imported from Firefox. Other data, History, Bookmarks, Cookies are imported from Firefox.

## Steps to Reproduce

   1. Have Firefox installed with data for History, Bookmarks, Cookies, Passwords, Search Engine, and Autofill data.
   2. Close Firefox.
   3. Launch Brave (I used a clean profile).
   4. Import all data from Firefox.
   5. Verify History, Bookmarks, Cookies are imported.

## Actual result:
Passwords, Search Engine, and Autofill are not imported.

## Expected result:
Passwords, Search Engine, and Autofill are imported.

## Reproduces how often: 

Easily

## Brave version (brave://version info)
Reproduced on various release channel versions listed below:

Brave | 0.56.14 Chromium: 70.0.3538.102 (Official Build) (64-bit)
-- | --
Revision | 4bbeebac88fdc09c97265e47c205868bbd190497-refs/branch-heads/3538@{#1077}
OS | Mac OS X

Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

Brave | 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes, reproduced on Beta

Brave | 0.57.6 Chromium: 71.0.3578.31 (Official Build) beta(64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Mac OS X

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? see https://github.com/brave/brave-browser/issues/2198#issuecomment-440439619

**Comment by iefremov** [comment]
Lauren, could you please specify the Firefox version? Is it a 64 or 32 bit build?

**Comment by LaurenWags** [comment]
sure, @iefremov I'm using 
<img width="649" alt="screen shot 2018-11-20 at 12 11 34 pm" src="https://user-images.githubusercontent.com/28145373/48790504-7e7e9880-ecbd-11e8-9fbd-af81de32a5b5.png">

**Comment by btlechowski** [comment]
Checked importing of passwords on Windows 7 x64(Firefox 64) and Ubuntu 17.10(Firefox 57) Brave 0.56.14.
Passwords were imported. 

Autofill is not accessible for me in Firefox - this is apparently by design.

**Comment by LaurenWags** [comment]
Checked Chrome's behavior. Using Firefox version from https://github.com/brave/brave-browser/issues/2198#issuecomment-440352917 and the below Chrome version,

Google Chrome | 70.0.3538.102 (Official Build) (64-bit)
-- | --
Revision | 4bbeebac88fdc09c97265e47c205868bbd190497-refs/branch-heads/3538@{#1077}
OS | Mac OS X

This is what Chrome offered to import
![screen shot 2018-11-20 at 4 40 25 pm](https://user-images.githubusercontent.com/28145373/48804592-04f9a100-ece3-11e8-9701-00a517fa8029.png)

however, only history and bookmarks were imported. Passwords, search engine, and autofill were not imported.

**Comment by garrettr** [comment]
I can reproduce on macOS. The following error is probably related:

```
[58171:17923:1129/121002.613957:ERROR:nss_decryptor_mac.mm(32)] Failed to load nss3 libdlopen(/Users/garrettr/Library/Application Support/Firefox/Profiles/vjy5vxa3.Test Brave Firefox Importer/libnss3.dylib, 1): image not found
[58171:17923:1129/121002.618771:ERROR:nss_decryptor_mac.mm(32)] Failed to load nss3 libdlopen(/Applications/Firefox.app/Contents/MacOS/libnss3.dylib, 1): Library not loaded: @executable_path/libmozglue.dylib
  Referenced from: /Applications/Firefox.app/Contents/MacOS/libnss3.dylib
  Reason: image not found
```

We don't touch any of the upstream code for importing saved passwords, search engines, or autofill form data, so it's possible some or all of these issues also affect upstream Chromium.

**Comment by brachna** [comment]
Not all of my Firefox history seems to be imported.

**Comment by garrettr** [comment]
> Not all of my Firefox history seems to be imported.

@brachna Thanks for the heads up. That's probably both a separate issue and also an issue in upstream Chromium, because we don't make any modifications to `FirefoxImporter::ImportHistory` for Brave.

Nonetheless, we'd like to ensure the best possible experience for all of our users. Could you share any more detailed information on the behavior your encountered? The most helpful thing would be if you could share a copy of the affected Firefox profile directory with one of Brave's engineers; if you're willing to do so, you could email me: grobinson at brave.com.

**Comment by brachna** [comment]
Yes, Brave, Chrome and Opera show the same behavior, so it must be Chromium code.
Sorry, I can't share my files.
Currently I'm trying to generate correct "History" file myself through Python.
I can tell you that looking at Firefox's "places.sqlite" file - all the information is there in moz_places table.
Brave's "History" file doesn't have all those in its urls table.

**Comment by Brave-Matt** [comment]
+1 from Community: 
https://community.brave.com/t/cant-import-passwords-from-firefox-macos/49785

**Comment by neofutur** [comment]
just a +1 . same problem here,i spent 15 years using firefox and badly need to import saved logins/pass ( and also the master password feature to protect them all )

**Comment by rebron** [comment]
related and dependent on https://github.com/brave/brave-browser/issues/6521

**Comment by rebron** [comment]
+1 from #6538

**Comment by LaurenWags** [comment]
Still reproduces with 1.38.104

```
Brave | 1.38.104 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)
```

**Comment by rebron** [comment]
cc: @spylogsster

**Comment by bsclifton** [comment]
Talked with @spylogsster - we have already got Autofill import and Password import. Search import is a bit difficult (requires new dependencies we'd rather not add yet) and we're not importing search yet for other browsers. We can capture that separately
