### ISSUE TITLE
`teverifiques` should be `te verifiques` in Brave Rewards wallet dialog

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21980]
## Steps to Reproduce

1. change your region + language to `Spanish` (Espana)
2. install `1.37.109`
3. launch Brave
4. open brave://rewards
5. click on `Gestionar Brave Rewards`
6. in the first tab, look at the last link and preceding text

## Actual result:

`te recomendamos que teverifiques.`

<img width="1312" alt="Captura de pantalla 2022-03-30 a las 9 20 28" src="https://user-images.githubusercontent.com/387249/160883873-56e17f26-1c74-4553-8e9f-4a730aff1205.png">

## Expected result:
`te recomendamos que te verifiques.`

## Brave version (brave://version info)

Brave | 1.37.109 Chromium: 100.0.4896.60 (Build oficial) (x86_64)
-- | --
Revisión | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
Sistema operativo | macOS Versión 11.6.5 (Compilación 20G527)

cc @mkarolin

**Comment by kjozwiak** [comment]
Above requires `1.37.114` or higher for `1.37.x` verification.

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.37.114 Chromium: 100.0.4896.88 (Build oficial) (x86_64)
-- | --
Revisión | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
Sistema operativo | macOS Versión 12.3.1 (Compilación 21E258)
```

Confirmed translation updated.

<img width="695" alt="Captura de Pantalla 2022-04-13 a las 8 30 40 a m" src="https://user-images.githubusercontent.com/28145373/163180262-039343c5-faf3-429b-ae00-5849fd2f3115.png">
