### ISSUE TITLE
Sidebar "on mouseover" transition should be smoother

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#21992]
## Description 

When side bar is enabled with `On mouseover` selected, the Sidebar "animation" is rather jerky and just sort of appears/disappears when the cursor is positioned on the left side of the screen:

https://user-images.githubusercontent.com/3299098/160921197-a16a4e73-6262-418d-bc2b-8d79e0d1656a.mov

While this is not a massive deal, I do think the feature could look/feel cleaner and more polished if we were to add a transition time when showing the Sidebar to give it a "smoother" feel.

Some examples:

- https://www.cssscript.com/demo/smooth-collapsible-sidebar-navigation/
- https://tympanus.net/Development/SidebarTransitions/# ("Slide in on top" option)
- https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_collapse_sidebar

**Comment by NumDeP** [comment]
Yeah I agree. I just used it for the first time on Youtube and the jittering of certain components on the site makes your eyes feel funny.

**Comment by rainer2208** [comment]
Hi,  yes I also fell that the sidebar isn't as smooth as it could be. 

When it appears, it just pushes the website to the right., what does not feel good. Instead it could just slide over the site. The experience would be a lot smoother.

**Comment by Brave-Matt** [comment]
Bumping this thread since more features are being added to the sidebar (such as reading list). This is obviously not a browser breaking issue, but I think its worth further polishing/refining features like. 

In the attached example, clicking the reading list on pops out right away (still jerky, as is in the original issue here), but then closes wonky — separately almost from the sidebar itself:

https://user-images.githubusercontent.com/3299098/186480716-6302abaa-1efd-412c-974d-381ad5d790ca.mov

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.58.78 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
-- | --
Revision | ca260d83d1ffda3cb35bff4bdc3251f30f9c8ccd
OS | Windows 10 Version 22H2 (Build 19045.3271)
```

### Confirmed sidebar open/close operations are smoother/less janky.  (I set framerate in my screen capture to 30 fps; it'll appear slightly smoother, even, in person.)

![show-sidebar-smooth](https://github.com/brave/brave-browser/assets/387249/b9af5d74-293e-4829-9b3a-acbe04d3c37d)
