### ISSUE TITLE
[Android VPN] [Beta User Feedback] Change VPN Icon

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#21995]
**User 1 Feedback**
Please change the "Brave Firewall + VPN" icon notification that appears and stays while connected to something different. It looks like a Brave Ad notification causing me to keep accidentally checking for an ad to dismiss.

**User 2 Feedback**
When connected to the VPN, there's a Brave icon in the system top bar. It is exactly the same as the one when I get an ad. I think it would be better if the icon is different from Brave Ad.

Also on this icon, I guess it would be nice to have a little detail showing the state of the connection. For example red icon not connected, orange currenty connecting, green connected. I said colors, but could be something else

**User 3 Feedback**
The notification is meaningless, no information about how much data have been transmitted, which server you're connected to, and the icon can be confused with Brave Rewards ads

![image](https://user-images.githubusercontent.com/28269287/160929052-db00ef9e-a9c7-4b3b-a8aa-d268dca55d24.png)

**Comment by timchilds** [comment]
The design team will work on a new icon. I'll attach when it's ready.

**Comment by timchilds** [comment]
@deeppandya here is the Figma for new VPN logo:
https://www.figma.com/file/QqaIjdrXobryTT3Zd9wcKM/Android-settings?node-id=0%3A1#176348315

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` & `Galaxy Tab S7` using version 

```
Brave	1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit) 
Revision	0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS	Android 12; Build/SP1A.210812.016

```
- Confirmed VPN notification icon will have separate design from brave ads
- Confirmed VPN icon will be displayed in the top bar when VPN is enabled. 
- Confirmed notifications in the tray will use the VPN icon. 

Mobile | Tablet 
-|-
![screenshot-1653329148158](https://user-images.githubusercontent.com/17885425/169881253-9e4c4443-0afd-4c66-928c-9d1c13fc4571.png) | ![screenshot-1653329267369](https://user-images.githubusercontent.com/17885425/169881256-1089cae0-0497-47f7-b43a-62dbd513ce4e.png) 

Top Bar

![Screen Shot 2022-05-23 at 11 07 37 AM](https://user-images.githubusercontent.com/17885425/169881335-82b7e8d2-ecfb-4d89-bce1-f4f0312a0948.png)
