### ISSUE TITLE
Make url bar suggestion provider work from top 500

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#22]
- [x] Make URL bar suggestions work from top 500
- [x] Disable search suggestions by default always

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

**Comment by elibroftw** [comment]
brave://settings/?search=use+a+prediction
