### ISSUE TITLE
`State-level ad targeting` string needs renaming in brave://settings/rewards

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22001]
## Description 

`State-level ad targeting` string needs renaming in brave://settings/rewards

## Steps to Reproduce

   1. install `1.39.18`
   2. launch Brave
   3. open `brave://rewards/`
   4. opt-in to Rewards
   5. click on the `Settings` icon for Brave Private Ads
   6. look at the term used there: `Regional ad relevance`
   7. open `brave://settings/rewards`
   8. look at the term used there: `State-level ad targeting`

This was renamed over in https://github.com/brave/brave-browser/issues/21291 for `brave://rewards`, but missed for `Settings`.

## Actual result:

`brave://settings/rewards` | `brave://rewards`
---------------------------|------------------
<img width="1609" alt="Screen Shot 2022-03-30 at 3 25 58 PM" src="https://user-images.githubusercontent.com/387249/160942272-6da56ae4-bfbe-465f-9b95-7c94e3d982e8.png"> | <img width="1609" alt="Screen Shot 2022-03-30 at 3 26 03 PM" src="https://user-images.githubusercontent.com/387249/160942276-1fe33c09-9b76-4d49-8212-363828a2ec59.png">

## Expected result:

It should read `Regional ad relevance` everywhere.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.18 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 11.6.5 (Build 20G527)

cc @tmancey @Tonev

**Comment by Tonev** [comment]
@stephendonner @tmancey :wave: 

:point_down: 
https://github.com/brave/brave-core/pull/12847

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - `1.38.75`

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.39.39 Chromium: 100.0.4896.79 (Official Build) nightly (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed the string in brave://settings/rewards now reads `Regional ad relevance`.

<img width="1485" alt="Screen Shot 2022-04-07 at 1 14 11 PM" src="https://user-images.githubusercontent.com/387249/162288596-9a03441c-394a-44d8-8b5b-9bd364b36590.png">
