### ISSUE TITLE
`brave://settings/rewards` incorrectly says Brave Rewards are disabled 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#22003]
## Description

@lukaslevert noticed that brave://settings/rewards reports that his Brave Rewards are not enabled, even though he is using Brave Rewards and is verified.

His simultaneous screenshots:

![image](https://user-images.githubusercontent.com/11497541/160954217-c4dbff27-06c8-452b-ba75-d7cf30eb4fc8.png)
![image](https://user-images.githubusercontent.com/11497541/160954230-e99f062f-2210-4932-93a4-405698ae01b5.png)

cc: @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment]
@lukaslevert - Did you reset rewards and enable AC and Ads switches manually?

I can reproduce the issue in the rewards reset case, the steps are mentioned below:

1. Clean profile 
2. Enable rewards via BR panel/NTP/Hamburger menu
3. Make sure rewards is enabled in both `brave://rewards/` and `brave://settings/rewards`
4. Reset the rewards via `Manage Brave Rewards`
5. Make sure rewards in disabled in `brave://settings/rewards`
6. Make sure Ads and AC switches are OFF and rewards is disabled in brave://rewards
7. Enable the Ads and AC switches manually in the brave://rewrads page
8. Reload the `brave://settings/rewards` page
9. _Rewards is still in disabled mode in settings page although it'e enabled in brave://rewards page_

**Comment by lukaslevert** [comment]
Hey Geeta,

I haven't reset rewards, but I have turned them on and off a handful of
times for client demos while walking them through Brave Ads and how a user
can opt-in/out of advertising.

Could that be the cause here?

Thanks,

**Comment by GeetaSarvadnya** [comment]
Tried a bunch of cases with Ads/AC enables/disable multiple times unable to reproduce the issue that @lukaslevert mentioned. I could reproduce the issue 100% only with the reset rewards case (mentioned above https://github.com/brave/brave-browser/issues/22003#issuecomment-1084424796) 

While testing the issue, found a new bug https://github.com/brave/brave-browser/issues/22022. Not sure it's expected or not.
cc: @Miyayes @emerick @zenparsing

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.39.86 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)
```

**Comment by MadhaviSeelam** [comment]
Brave | 1.39.95 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Windows 11 Version 21H2 (Build 22000.613)


- Install 1.39.95
- Launch brave
- Enable Rewards
- Visit brave://rewards
- Reset Rewards via "Manage Brave Rewards" button
- Confirmed brave://rewards page showed "opt-in" overlay after resetting rewards
- Confirmed panel showed rewards onboarding when selected after resetting rewards
- Confirmed brave://settings/rewards showed correct state (enabled or disabled depending on step)

ex1|ex2|ex3|ex4|ex5
---|---|---|---|---
<img width="600" alt="ResetRewards" src="https://user-images.githubusercontent.com/98358127/167515868-041e6874-6041-435b-a147-167c2fa4021e.png">|<img width="600" alt="RewardsPage" src="https://user-images.githubusercontent.com/98358127/167516029-8d7cbccc-9a7a-4637-b3a8-7a8cf6cc3e5c.png">|<img width="600" alt="RewardsPanel" src="https://user-images.githubusercontent.com/98358127/167516089-65a9da85-d90d-4711-8a54-2291b0b50362.png">|<img width="600" alt="Rewardsdisabledafterreset" src="https://user-images.githubusercontent.com/98358127/167515946-478c01c8-3568-41b9-9c30-0787301fb323.png">|<img width="600" alt="Rewardsenabled" src="https://user-images.githubusercontent.com/98358127/167516144-2d8ab03a-b9a2-4f86-a469-a7a181e2a7ff.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.100 Chromium: 101.0.4951.61 (Official Build) beta (64-bit)
-- | --
Revision | 3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/12877#issue-1192154898
- Confirmed brave://rewards page showed "opt-in" overlay after resetting rewards
![image](https://user-images.githubusercontent.com/34715963/167861584-e54b2fd5-c31b-4a5c-8483-22281143f1ef.png)
- Confirmed panel showed rewards onboarding when selected after resetting rewards
![image](https://user-images.githubusercontent.com/34715963/167861751-7f8b46d1-528a-4a8c-8dd5-38f06e1ae08f.png)
- Confirmed brave://settings/rewards showed correct state (enabled or disabled depending on step from test plan)
![image](https://user-images.githubusercontent.com/34715963/167861715-d43856df-1038-4375-b04b-dd6c2c3ac9f5.png)
