### ISSUE TITLE
Shields' toggle buttons are different colors

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22004]
## Description 

~Shields' toggle buttons are different colors~ Small toggles have animated gradients but shouldn't.

## Steps to Reproduce

   1. install `1.39.18`
   2. launch Brave
   3. load any website
   4. click on the `Shields` icon in the URL bar
   5. toggle both `Block Scripts` and `Upgrade connections to HTTPS` to `ON`

## Actual result:

Both are...different colors?

<img width="337" alt="Screen Shot 2022-03-30 at 6 14 42 PM" src="https://user-images.githubusercontent.com/387249/160957606-b220805b-e447-45aa-bcbe-b285a1f86046.png">

## Expected result:

Same color?

## Brave version (brave://version info)

Brave | 1.39.18 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 11.6.5 (Build 20G527)

cc @MadhaviSeelam @LaurenWags @GeetaSarvadnya @jenn-rhim

**Comment by aguscruiz** [comment]
Updated designs address the issue:
https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Brave-Shields?node-id=1220%3A26674

**Comment by kjozwiak** [comment]
Above requires `1.38.85` or higher for `1.38.x` verification.

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.38.88 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

#### Followed my original steps to reproduce, and confirmed the small toggle buttons are blurple, and match the Figma spec.

#### `Light` theme

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-04-11 at 11 44 47 AM" src="https://user-images.githubusercontent.com/387249/162808727-687acb63-ff85-4ec5-bd04-273d6c83aa0f.png"> | <img width="1312" alt="Screen Shot 2022-04-11 at 11 44 58 AM" src="https://user-images.githubusercontent.com/387249/162808742-39b6d31f-37d7-4c3a-b6fc-cad7dfeb2dbb.png">



#### `Dark` theme

example | example
---------|----------
<img width="1312" alt="Screen Shot 2022-04-11 at 11 49 44 AM" src="https://user-images.githubusercontent.com/387249/162809013-f6908299-b77e-49d4-a7c0-948f7c70ffc5.png"> | <img width="1312" alt="Screen Shot 2022-04-11 at 11 49 51 AM" src="https://user-images.githubusercontent.com/387249/162809019-ac78b1a4-b71f-40c4-aac1-76e05db500e1.png">
