### ISSUE TITLE
Bug or future trend ?

### ISSUE THREAD

**Issue by Wallymick** [brave/brave-browser#22006]
Is it just me or did I somehow miss it... 
Did the developers at Brave (beta version ) merge the Brave Shields button with Brave Rewards? 
Because I found that I no longer had the Brave Shields button and after many searches when activating Brave Rewards in Appearance tab the Shields button appeared...and when deactivating it both disappear....
Tested on two different pc with the same result so i exclud is something releated to user profile.
Brave Beta version is 1.38.71

**Comment by Tonev** [comment]
https://github.com/brave/brave-browser/issues/21830

The bug will be gone after you update your `Brave Beta` once the update becomes available :+1:

**Comment by Wallymick** [comment]
Let's hope so, because since v.1.38.67 when I noticed to v.1.38.71 nothing has changed.

**Comment by Tonev** [comment]
@Wallymick 

I just updated my `Brave Beta` from `1.38.71` to `1.38.75` and can confirm that the issue no longer exists. Hiding `Brave Rewards` doesn't hide the `Brave Shields` icon.

**Comment by Wallymick** [comment]
Just updated few seconds ago and i confirm that this issue is no longer exists.
Thank you @Tonev

**Comment by kirill-dev-pro** [comment]
So are you going to close the issue or what? @Wallymick

**Comment by Wallymick** [comment]
Thanks for feedback!
