### ISSUE TITLE
Upgrade to Chromium 70.0.3538.110

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2200]
For QA:
Only a security issue was fixed, so please just make sure Chromium version bump happened.

**Comment by kjozwiak** [comment]
Verified on `macOS 10.14 x64` using the following build:

Brave | 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
-- | --
Revision | ca97ba107095b2a88cf04f9135463301e685cbb0-refs/branch-heads/3538@{#1094}
OS | Mac OS X
