### ISSUE TITLE
display sidebar on the right

### ISSUE THREAD

**Issue by lazymonkey2** [brave/brave-browser#22019]
## Description 

please add option to display sidebar on the right

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Sa-Ja-Di** [comment]
Fully agreeing with this request, if you add such a feature make it at least a bit more customizable, its about time that Brave gets some customization features, but if you do, ensure you make them work correctly and not just bare-bone and call it a day.

**Comment by maxwellt** [comment]
+1, for Linux users who have a dock which pops up when the mouse touches the left side of the screen it would be handy to display the Brave sidebar on the other side so the two actions don't "collide"

**Comment by dehidehidehi** [comment]
+1

**Comment by rebron** [comment]
Closing as stale. https://github.com/brave/brave-browser/issues/30397 Default is on the right as of 1.56.x and was available on the right side on earlier versions.
