### ISSUE TITLE
sidebar should be resizable

### ISSUE THREAD

**Issue by lazymonkey2** [brave/brave-browser#22018]
## Description 

the sidebar should be resizable when is opened, like when it is showing bookmarks.
I have many bookmarks in nested folders, and I cannot use the sidebar, it is too small.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by 424344** [comment]
any news?
