### ISSUE TITLE
workspaces like opera

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#22017]
## Description 

now that you have enabled the sidebar please add workspaces support like in opera browser.

in opera you can create different workspaces, and choose the one you want using buttons in the sidebar.
choosing a workspace should hide (not close!) all the current tabs and display the ones from the chosen workspace.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tenapps2** [comment]
Microsoft Edge Gets Workspaces:
https://petri.com/microsoft-edge-workspaces-website-typo-protection/

Opera has workspaces natively. Firefox have workspaces (aka Tab Groups) via STG extension, and Vivaldi has advanced tab management.

It's time to add workspaces to Brave too.

**Comment by NoahSchiffman** [comment]
I would switch from Opera GX, to Brave, if Brave got native workspaces the same as Opera.

**Comment by bsclifton** [comment]
This is a great request 😄 We have an issue tracking this already with https://github.com/brave/brave-browser/issues/11096

I'm going to close this one as a duplicate - thanks for reporting

**Comment by 424344** [comment]
I don't think this is a duplicate of 11096, and should be reopened.

In 11096 it is requested ability to manually save and load groups of tabs.

Instead in this issue I was suggesting to let the browser do the saving and loading:
a user just creates a workspace, deletes it and switches between workspaces.
then the browser automatically remembers the tabs in each workspace, without user intervention.
what I want is a "photo" of all tabs  and groups, constantly updated by the browser.

this is how work the firefox extension "simple tab groups" and I'd like to have in Brave the same functionality.

Moreover in 11096 they do not speak about *hiding* tabs, which instead is important in this issue:
when changing workspace the currently openend tabs are hidden (not closed) so that, in case I
return to the workspace, I'll see the older hidden tabs: they won't be reloaded from scratch.
(think about email: I could start writing an email, change worspace to check some info, then
go back to the previous email workspace, and continue writing my email... no data loss).

So please reopen this issue. 
Thank you.

**Comment by saranvdev** [comment]
Reopen please.

**Comment by 424344** [comment]
yes, I agree it should be reopened.
now even vivaldi has implemented workspaces as described in this issue. 
please note that they already had the ability to load and save tabs, like in issue #11096.
they do get that this issue is not a duplicate of #22896, and implemented both features.
please take a look at vivaldi workspaces and implmenent something similar.
thank you.

**Comment by tgienger** [comment]
Yes Yes YES I'm finding myself using OPERA of all things because of their workspace implementation and I need to be pulled free again!! SAVE ME!!

**Comment by mejoebob** [comment]
Why is the request to reopen being ignored? This is *not* a duplicate.
I'm hitting the same issue as others. At first, I felt a tug back to opera - if anything, for the workspaces.
The few extensions (Workspace Manager and Workspaces) are okay substitutes but they open a new workspace in a new window.
For now, I'm going to stay with Brave, but the built-in workspaces would be nice.
I understand, however, that if I want a "light" browser, I have to be willing to sacrifice bells and whistles.

**Comment by jstnklnr** [comment]
I agree, that this should be re-opened. It is currently the only issue that is keeping me from using brave.
It does not have to be overly complex to keep the browser as light weight as possible.

Just a way to not "see" all tabs at once as it can get quite full at times.
Also really helpful when working on different projects / tasks.

**Comment by vdawg-git** [comment]
Please reopen this. This is the only feature I am missing in Brave (which is already my favorite Browser)

**Comment by mejoebob** [comment]
I totally forgot about this until my email showed the comment from vdawg-git.
As a software developer, I understand that not everything is as simple as it sounds. But is nobody on the Brave team even noticing this? As mentioned by myself and others, this does not seem to be a duplicate.
In any case, although I may use Brave occasionally, I moved on to Vivaldi or even Opera. Vivaldi is very powerful and flexible (just takes some time to get used to).

**Comment by bsclifton** [comment]
The only reason this issue is closed is because there's already an open GitHub issue tracking Workspaces

Please see and subscribe to https://github.com/brave/brave-browser/issues/11096 for updates. Maybe @rebron can share an update

I'll close this issue as there's nothing new to add - please bring the conversation over to https://github.com/brave/brave-browser/issues/11096. Thanks! 😄
