### ISSUE TITLE
Need space between blocked count and `Trackers & ads` in Shields panel

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22012]
## Description 

Need space between blocked count and `Trackers & ads` in Shields panel

## Steps to Reproduce

   1. install `1.39.18`
   2. launch Brave
   3. load a high-tracker-count website and/or be patient
   4. get at least 100 trackers (I think; I had 300+ in this tab's session)
   5. click on the `Brave Shields` icon in the URL bar
   6. click to expand the `Advanced Controls` section of the panel
   7. click on the `99+` for the first option, `Aggressively block trackers & ads`

## Actual result:

<img width="1206" alt="Screen Shot 2022-03-31 at 1 27 50 AM" src="https://user-images.githubusercontent.com/387249/161012885-fb209977-8186-419b-90e1-1132aa2d5493.png">

## Expected result:

A space in-between `306` and `Trackers & ads`

## Reproduces how often: 

Not 100% for me yet

## Brave version (brave://version info)

Brave | 1.39.18 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 12.3 (Build 21E230)

cc @nullhook @Tonev

**Comment by kjozwiak** [comment]
Above requires `1.38.85` or higher for `1.38.x` verification.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.88 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed for `100+` (and <`1,000`) values.

`light` mode

`100+` | `1,000+`
---------|---------
<img width="1187" alt="Screen Shot 2022-04-11 at 10 47 46 PM" src="https://user-images.githubusercontent.com/387249/162889514-a15f1cf3-e32e-4621-b0bb-44777773172d.png"> | <img width="1429" alt="Screen Shot 2022-04-11 at 5 13 08 PM" src="https://user-images.githubusercontent.com/387249/162866705-81dbcd26-03b1-4c40-935f-1b077f4d1e4e.png">



`dark` mode

`100+` | `1,000+`
---------|---------
<img width="1187" alt="Screen Shot 2022-04-11 at 10 47 06 PM" src="https://user-images.githubusercontent.com/387249/162889413-9f3db6e4-8a88-45fb-afa7-8a333ce45bd8.png"> | <img width="1346" alt="Screen Shot 2022-04-11 at 7 13 22 PM" src="https://user-images.githubusercontent.com/387249/162866641-dc11c80e-9343-4c2b-96a1-f3febb087b2b.png">
