### ISSUE TITLE
[Meta-issue] Add policy options to allow disabling BAT

### ISSUE THREAD

**Issue by donateur** [brave/brave-browser#22029]
## Description 
**EDIT: This has been modified at the suggestion of @bsclifton to cover any desktop client.**

**Edit: This is now a meta-issue for:** 
- [x] Add policy option to disable Brave Rewards https://github.com/brave/brave-browser/issues/25151
- [x] Add policy option to disable Brave Wallet https://github.com/brave/brave-browser/issues/25383
—@Miyayes 

I wish to roll out Brave on (Linux) desktops for a security-conscious client, however they do not not allow BAT or any crypto-currency transactions on their network.  If I could forcibly disable BAT features using policy then I will be permitted to go ahead.

I originally asked this as a question in #18921 but it seems there are no policy options to disable BAT features.

By "BAT features" I mean anything which would generate crypto-currency network traffic as they will detect it.  We need (Linux) policy options to;
* Disable Brave Rewards
* Disable Brave Sponsored Images (in new tabs)
* Disable Brave Wallet
I think we can allow Brave News, so long as the ads in it do not generate crypto-currency transactions at the client-side (that is they don't generate income for the viewer)

## Brave version (brave://version info)
Latest Brave for Linux 64-bit.

Thank you in advance!

**Comment by donateur** [comment]
Please add labels "enterprise" and "OS/Linux"

**Comment by mxipby** [comment]
I agree with this, I think it makes sense.

**Comment by diracdeltas** [comment]
in case it's helpful, i believe you can accomplish all of these things on a default install of Brave by simply not opting into rewards. although sponsored images on new tab and Brave News will appear, they will not generate any crypto transactions or income because the user doesn't have a wallet in the first place.

however i can understand the use case for enforcing this via policy so +1 from me

**Comment by donateur** [comment]
> Please add labels "enterprise" and "OS/Linux"

Is anyone able to do that please?  TIA!

**Comment by bsclifton** [comment]
Label added, thanks @donateur. I modified title as it's applicable to all platforms
cc: @Miyayes

**Comment by donateur** [comment]
Thanks @bsclifton .  I'll modify the original text to reflect that this is now not-platform specific.

**Comment by donateur** [comment]
To be clear, we'll need a way to apply these on Linux - admx templates won't work ;)

**Comment by lukemulks** [comment]
IIRC, there is a setting in brave://settings that provides users with the option to remove all Rewards icons in the browser that could probably be enabled by default in an `enterprise` mode.

Would be ideal to keep Sponsored Image default as-is, unless we apply Aggressive Shields mode by default in an enterprise mode.

Same ^ for News Ads. 

Mentioning as these are commercial units, and default Shields do not block Search Ads (across SEs), and platform-native / 1p ads including Twitter Promoted Content, Reddit 1p Sponsored and sponsored placements on other domains  (examples: sponsored/paid/promoted 1p on quora, coinmarketcap.com, coingecko.com, etc. )

Point being, there have been concerns re: Brave special casing Brave Ads with Brave Search from other SEs surfaced (and resolved) when Premium was introduced.  

In those cases, concerns surfaced were about Brave making it more difficult to block our own Ads vs other SEs via Aggressive mode.

In this case, it's the inverse. Brave commercial units should not be special cased in enterprise mode if commercial units are not blocked elsewhere.

**Comment by neil-timmerman** [comment]
Some midsize companies could roll out Brave as the default browser for the enterprise but, yes, we need the ability to disable ads and rewards. It's the wrong optics for the enterprise.

**Comment by donateur** [comment]
Hello again,

We're unable to roll out Brave until this feature is completed.  While an option to allow disabling BAT won't generate any money from my client's business, it will expose new users to Brave.  Can you please consider this a higher priority?

Thank you!

**Comment by Miyayes** [comment]
> Hello again,
> 
> We're unable to roll out Brave until this feature is completed. While an option to allow disabling BAT won't generate any money from my client's business, it will expose new users to Brave. Can you please consider this a higher priority?
> 
> Thank you!

Just noting that we have a pull request open for this, so this should be resolved soon. This will be broken out into two different policy toggles: one for Rewards specifically https://github.com/brave/brave-browser/issues/25151, and one for Brave Wallet (WIP). You can disable both if you please. @donateur

**Comment by donateur** [comment]
> Just noting that we have a pull request open for this, so this should be resolved soon. This will be broken out into two different policy toggles: one for Rewards specifically #25151, and one for Brave Wallet (WIP). You can disable both if you please. @donateur

Thank you very much!

**Comment by mkarolin** [comment]
Resolved via https://github.com/brave/brave-browser/issues/25151
 and https://github.com/brave/brave-browser/issues/25383.
Marking as `QA/No` since both of the subtasks were marked as `QA/Yes`.

**Comment by Miyayes** [comment]
Hi @donateur, this is complete. You can start rolling out Brave soon (starting in the version where these take effect).
