### ISSUE TITLE
[Android VPN] [Beta User Feedback] Server timeout causes  host vs. location mismatch in settings

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#22023]
**User Feedback**
When I selected the Japan server, it said i was connected to the NY server.

I've been able to reproduce the Japan/NY bug, please see the screenshot attached.
It says Location Japan but above you can see Host New York.

It doesn't happen every time but I feel like when there's a connection timeout on this Japan server, it keeps the previous host (I selected NY) but changes the location name to Japan. And when I lookup my IP location on a website, it says that I'm in NY.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/28269287/161100241-e6d631c1-39ef-4528-9cb5-cae83d1b7378.png">

**Comment by bbondy** [comment]
Was there a pull request which fixed this issue?

**Comment by deeppandya** [comment]
@bbondy it was updated here : https://github.com/brave/brave-core/pull/10692. we came across this issue during first internal testing and it was happening because of race condition.

**Comment by bbondy** [comment]
Please add an appropriate milestone or closed/ label.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.39.115 Chromium: 102.0.5005.78 (Official Build) (64-bit)
--- | ---
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Android 12; Build/SP1A.210812.016
```

Went through the STR/Cases mentioned via https://github.com/brave/brave-browser/issues/22023#issue-1188315597 and basically ensured that `Location` & `Host` matched. Switched a bunch of locations in quick succession for ~5-10min and never ran into the issue where the `Location` & `Host` were mismatched. Examples:

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|-----------------
![Screenshot_20220530-012604_Brave](https://user-images.githubusercontent.com/2602313/170922875-0ced377a-6a4d-475a-81aa-9b2f95866b18.jpg) | ![Screenshot_20220530-012619_Brave](https://user-images.githubusercontent.com/2602313/170922876-7b0115a8-6761-461f-a80e-ebde94a73307.jpg) | ![Screenshot_20220530-012631_Brave](https://user-images.githubusercontent.com/2602313/170922877-2ba795c7-2aae-4789-953d-9eaa22bb8057.jpg) | ![Screenshot_20220530-012546_Brave](https://user-images.githubusercontent.com/2602313/170922879-fd0974d0-a197-4052-928c-7d10485eaf8b.jpg) | ![Screenshot_20220530-012532_Brave](https://user-images.githubusercontent.com/2602313/170922881-70cf5bce-2fb8-4a19-87ee-d4156314471f.jpg)
