### ISSUE TITLE
Re-enable rewards via NTP doesn't enable AC switch, reload page also doesn't enable AC

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22022]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/22003
Re-enable rewards via NTP doesn't enable AC switch, reload page also doesn't enable AC
## Steps to Reproduce

   1. Clean profile 1.37.109 or 1.38.x
   2. Enable rewards via BR panel/NTP/Hamburger menu
   3. Make sure Ads and AC switches are turned ON in brave://rewards
   4. Turn OFF both the switches manually
   5. Open an NTP or existing NTP
   6. Click on `Start using rewards`  
   7. Ads switch is enabled AC switch is in OFF state

## Actual result:

Re-enable rewards via NTP doesn't enable AC switch, reload page also doesn't enable AC

## Expected result:
Looks like AC switch also needs to be enabled

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @emerick

**Comment by Miyayes** [comment]
This is intentional behavior to avoid unsuspecting A-C re-enablement. Thanks!
