### ISSUE TITLE
Update Transaction Info UI for Filecoin info

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#22020]
Filecoin and Ethereum transactions have different data to be shown to user, need to update UI
https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/hooks/transaction-parser.ts#L89
to show all FIL transaction data
https://github.com/brave/brave-core/blob/master/components/brave_wallet/common/brave_wallet.mojom#L819

**Comment by kjozwiak** [comment]
The above will require `1.40.94` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.95 Chromium: 102.0.5005.115 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13665>brave/brave-core#13665</a></li>
         <li>Verified transaction UI for Filecoin shows correct details</li>
         <li>Verified transaction panel shows address of the receiving accounts</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/173343152-f49546c6-2a96-4ba6-99b0-3ab9e963b3f6.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173343284-56609ed7-22d6-4fcb-98a7-4d46a5584fc1.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173343243-7074e1e9-22d2-4201-ad83-8e1b2cc05ec8.mov>
      </td>
   </tr>
</table>
