### ISSUE TITLE
Clicking on Shields, VPN or Wallet icons should toggle panel shown/hidden; it remains shown

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22026]
## Description 

Filing as proxy for @Miyayes who found this 🤜 🤛 

Clicking on Shields icon should toggle panel shown/hidden; it remains shown

## Steps to Reproduce

1. install `1.39.22`
2. launch Brave
3. load `brave.com`
4. click (and let go) on the `Brave Shields` icon in the URL bar
5. confirm the panel opens
6. click the `Brave Shields` icon again to dismiss

## Actual result:

After the click event is done, the Shields panel still remains.

![open-panel-click](https://user-images.githubusercontent.com/387249/161141223-cf3f0108-bfdd-41bd-99d9-502430ef5636.gif)

## Expected result:

Clicks should toggle the shown/hidden state of the panel, as it does in `1.37.x` and earlier.  The 2nd click after opening the panel should dismiss it.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.22 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 11.6.5 (Build 20G527)

cc @nullhook @Tonev @Miyayes @rebron

**Comment by kjozwiak** [comment]
The above will require `1.38.105` or higher for `1.38.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```
- Confirmed that clicking on the shield on any site opens up the shield panel, click on the shield icon again dismiss the shield panel on the website

Also Confirmed:

clicking the icon invokes a doorhanger panel, which remains until further, specific click(s)
clicking inside the panel does NOT dismiss (expected)
clicking again on the icon dismisses the doorhanger panel
clicking anywhere outside of the doorhanger panel dismisses it
panel is dismissed upon pressing esc
