### ISSUE TITLE
Saved bookmark and history gone after force shutdown

### ISSUE THREAD

**Issue by jffaust** [brave/brave-browser#22038]
## Description 
Bookmarks and history that happen during a browsing session are lost if Brave exits unexpectedly.

## Steps to Reproduce
   1. Open Brave
   2. Navigate to some sites
   3. Bookmark a site
   4. Shutdown your computer while Brave is still opened
   5. Start your computer
   6. Open Brave
   7. Brave asks to restore the previous session, click Restore
   8. Brave remembers the pages that were open but the history and the bookmark is lost

## Actual result:
I am losing saved bookmarks and history from the previous day

## Expected result:
Brave remembers the history and the bookmarks even if it doesn't shut down normally

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave: 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit) 
Revision: 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS: Linux

**Comment by jffaust** [comment]
I just did a test and the bookmark was kept so maybe it's not that easily reproducible :/

**Comment by rebron** [comment]
@jffaust Let us know if this is an issue you can consistently reproduce.
