### ISSUE TITLE
Optimize Brave Ads startup performance

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#22033]
Currently Bat ads startup logic is linear and single threaded. Need to refactor Bat ads to make it possible to parallelize loading/parsing of resources. See comment (https://github.com/brave/brave-core/pull/12834#discussion_r839661269)

It is good to add performance measurements prior to this fix: https://github.com/brave/brave-browser/issues/21106

**Comment by tmancey** [comment]
Closing as will be resolved by https://github.com/brave/brave-browser/issues/29888
