### ISSUE TITLE
Wire up SPL tokens and Send in UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22039]
## Description 
Wire up the ability to add a SPL tokens and sending SPL tokens in UI

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)
-- | --
Revision | `f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}`
OS | Windows 11 Version 22H2 (Build 22621.1)

- Verified test plan from [brave/brave-core#12939](https://github.com/brave/brave-core/pull/12939)
- Verified able to send an SPL token 
- Verified transaction confirmation is shown 
- Encountered [#22966](https://github.com/brave/brave-browser/issues/22966)

https://user-images.githubusercontent.com/17010094/169550917-6ee8cee1-6fa9-4d8b-82e4-c6547a78822b.mov
