### ISSUE TITLE
Block cross-site cookies heading label should read `Block cookies`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22035]
## Description 

Block cross-site cookies heading label should read `Block cookies`

## Steps to Reproduce

   1. install `1.39.22`
   2. launch Brave
   3. open `brave://settings/shields`
   4. read label and options for `Block cross-site cookies`

## Actual result:

The label is `Block cross-site cookies` and includes...`All` and `Only cross-site` options, the latter of which is made redundant by the (incorrect) label

example | example
---------|---------
<img width="720" alt="Screen Shot 2022-04-01 at 12 11 36 AM" src="https://user-images.githubusercontent.com/387249/161226132-f9329227-38c3-46f0-bc72-6c1e0baf21c5.png"> | <img width="717" alt="Screen Shot 2022-04-01 at 12 11 45 AM" src="https://user-images.githubusercontent.com/387249/161226134-7a52bd3f-b825-425b-b043-63ae1e116faf.png">

## Expected result:

Label should probably just read `Block cookies`, which would fit with the other labels, as well as its own options

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.22 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 12.3 (Build 21E230)

cc @jenn-rhim @nullhook @pes10k @rebron @MadhaviSeelam @Tonev

**Comment by Tonev** [comment]
Sorry, @stephendonner, I should have pinged you along @rebron and @nullhook :disappointed: 

https://github.com/brave/brave-browser/issues/21983

**Comment by Tonev** [comment]
Please, assist me with review/merge so we get this fixed :point_right: https://github.com/brave/brave-core/pull/12862
