### ISSUE TITLE
Improve Easylist Cookie blocking

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#22032]
## Description 
Missing cookie messages, that should be blocked

## Steps to Reproduce

Some examples, With 

   1. Open `https://jobsinkyoto.com/` ###cookieConsentModal  is unblocked.  jobsinkyoto.com##.vm--overlay is blocked
   
![jobs-netw](https://user-images.githubusercontent.com/1659004/161189693-beaf7f6a-97e6-40d0-bd6f-da133cd0385d.png)

**jobsinkyoto.com:**
Implemented here: https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_general_hide.txt#L2364

   2. Open `https://safehaven.io/`  safehaven.io###cookie-law-info-bar  & safehaven.io##body,html:style(height: auto !important; overflow: auto !important) is unblocked
   
![safehaven](https://user-images.githubusercontent.com/1659004/161190228-9e596c03-1338-4b03-b892-97cd57a42e6f.png)

**safehaven.io:**
Implemented here: https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_specific_uBO.txt#L309
`safehaven.io###cookie-law-info-bar`
`safehaven.io##body,html:style(height: auto !important; overflow: auto !important)`

## Expected result:
Block the cookie messages

## Reproduces how often: 
Enable Easylist Cookie via chrome://flags/#brave-adblock-cookie-list-default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Tested in Nightly `[Version 1.39.22 Chromium: 100.0.4896.60`

**Comment by ryanbr** [comment]
From https://community.brave.com/t/dk-com-cookie-policy/365710  `https://www.dk.com/us/` should be blocked in standard mode.  Using the filter `##dk-cookie-warning`

**Comment by ryanbr** [comment]
![airbnb4](https://user-images.githubusercontent.com/1659004/161838950-e02c4b7a-e4c3-4296-bacc-ba6bab1cda06.png)

Airbnb.com

```
easylist_cookie/easylist_cookie_general_hide.txt:###main-cookies-banner-container
easylist_cookie/easylist_cookie_general_hide.txt:##[data-testid="main-cookies-banner-container"]
```

**Comment by antonok-edm** [comment]
Also mentioning https://publicholidays.ee/ and https://www.overhemden.com/kronstadt-heren-overhemd-dean-bordeaux-rood-mao-flanel-regular-fit-ks3434bordeauxmel#01a7abd36065c0ad4c1159ddb9afa1e1 from a thread in Slack for QA testing purposes.

@ryanbr From my own testing, https://github.com/brave/brave-core/pull/12917 should fix all of these sites.

**Comment by kjozwiak** [comment]
Above requires `1.38.86` or higher for `1.38.x` verification.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.99 Chromium: 100.0.4896.127 (Official Build) beta (x86_64)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | macOS Version 12.4 (Build 21F5048e)

* enabled `brave://flags/#brave-adblock-cookie-list-default` and ensured that `Easylist-Cookie List - Filter Obtrusive Cookie Notices` was enabled via `brave://adblock` when the browser was restarted
* ensured that the `Review our cookie policy` overlay under https://jobsinkyoto.com wasn't being displayed
* ensured that the `The Safe Haven website uses cookies.` overlay under https://safehaven.io wasn't being displayed
* ensured that the `Your Privacy` modal at the bottom of the screen under https://www.airbnb.ca wasn't being displayed
* ensured that the `Overhemden.com - Overhemden specialist van Nederland & België` overlay under https://www.overhemden.com/kronstadt-heren-overhemd-dean-bordeaux-rood-mao-flanel-regular-fit-ks3434bordeauxmel#01a7abd36065c0ad4c1159ddb9afa1e1 wasn't being displayed
* ensured that the `This site uses cookies and by continuing to browse it you are agreeing to our target use of cookies. Read our cookies policy.` modal at the top of https://www.dk.com/us/ wasn't being displayed

brave://flags | jobsinkyoto.com | safehaven.io | airbnb.com | overhemden.com | dk.com/us
-------------|-----------------|--------------|-------------|-------------------|----------
<img width="1312" alt="Screen Shot 2022-04-18 at 4 19 23 PM" src="https://user-images.githubusercontent.com/387249/163891927-54d4808f-8d1e-41ea-80e1-caa54206de84.png"> | <img width="1312" alt="Screen Shot 2022-04-18 at 4 14 36 PM" src="https://user-images.githubusercontent.com/387249/163891752-8ac76dc8-503d-4db0-9ce6-4804350ad0ea.png"> | <img width="1312" alt="Screen Shot 2022-04-18 at 4 14 48 PM" src="https://user-images.githubusercontent.com/387249/163891764-2928ff9f-b3c0-46ce-8d3f-d038ceaedf2f.png"> | <img width="1312" alt="Screen Shot 2022-04-18 at 4 14 59 PM" src="https://user-images.githubusercontent.com/387249/163891767-ce6ab02a-29bd-4e03-a863-93d713dea004.png"> | <img width="1312" alt="Screen Shot 2022-04-18 at 4 15 12 PM" src="https://user-images.githubusercontent.com/387249/163891768-f99ccb61-ced9-4db0-b796-b7ef0391055e.png"> | <img width="1312" alt="Screen Shot 2022-04-18 at 4 15 42 PM" src="https://user-images.githubusercontent.com/387249/163891770-3ff4a3fb-b796-4169-a622-4a09a2c431e4.png">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` running `Android 12` using 

```
Brave	1.38.104 Chromium: 101.0.4951.41 (Official Build) (64-bit) 
Revision	93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS	Android 12; Build/SP1A.210812.016
```

- enabled brave://flags/#brave-adblock-cookie-list-default and ensured that Easylist-Cookie List - Filter Obtrusive Cookie Notices was enabled via brave://adblock when the browser was restarted

- ensured that the Review our cookie policy overlay under https://jobsinkyoto.com/ wasn't being displayed

- ensured that the The Safe Haven website uses cookies. overlay under https://safehaven.io/ wasn't being displayed

- ensured that the Your Privacy modal at the bottom of the screen under https://www.airbnb.ca/ wasn't being displayed

- ensured that the Overhemden.com - Overhemden specialist van Nederland & België overlay under https://www.overhemden.com/kronstadt-heren-overhemd-dean-bordeaux-rood-mao-flanel-regular-fit-ks3434bordeauxmel#01a7abd36065c0ad4c1159ddb9afa1e1 wasn't being displayed

- ensured that the This site uses cookies and by continuing to browse it you are agreeing to our target use of cookies. Read our cookies policy. modal at the top of https://www.dk.com/us/ wasn't being displayed

Safehaven | Jobsinkyoto | adblock | airbnb | overhemden | dk
-|-|-|-|-|-
![screenshot-1650587888662](https://user-images.githubusercontent.com/17885425/164576194-49ce5840-663f-4aff-b4ac-b9eb024b62f6.png) | ![screenshot-1650587897141](https://user-images.githubusercontent.com/17885425/164576196-f221d782-0ec5-4390-afca-b3d2fa8ee83d.png) | ![screenshot-1650587905944](https://user-images.githubusercontent.com/17885425/164576197-87397c18-894f-4c23-ab38-a4a06e6dd87c.png) | ![screenshot-1650588090965](https://user-images.githubusercontent.com/17885425/164576199-95724e85-7c75-41f4-8201-eadb2073dcda.png) | ![screenshot-1650588683972](https://user-images.githubusercontent.com/17885425/164576202-164cdad5-1ed5-482d-9586-5ccb3b09c498.png) | ![screenshot-1650588738525](https://user-images.githubusercontent.com/17885425/164576203-4a0444c8-0452-4804-930e-6cfc15232d44.png)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` running `Android 12` using 

```
Brave	1.38.104 Chromium: 101.0.4951.41 (Official Build) (64-bit) 
Revision	93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS	Android 12; Build/SP1A.210812.016
```

- enabled brave://flags/#brave-adblock-cookie-list-default and ensured that Easylist-Cookie List - Filter Obtrusive Cookie Notices was enabled via brave://adblock when the browser was restarted

- ensured that the Review our cookie policy overlay under https://jobsinkyoto.com/ wasn't being displayed

- ensured that the The Safe Haven website uses cookies. overlay under https://safehaven.io/ wasn't being displayed

- ensured that the Your Privacy modal at the bottom of the screen under https://www.airbnb.ca/ wasn't being displayed

- ensured that the Overhemden.com - Overhemden specialist van Nederland & België overlay under https://www.overhemden.com/kronstadt-heren-overhemd-dean-bordeaux-rood-mao-flanel-regular-fit-ks3434bordeauxmel#01a7abd36065c0ad4c1159ddb9afa1e1 wasn't being displayed

- ensured that the This site uses cookies and by continuing to browse it you are agreeing to our target use of cookies. Read our cookies policy. modal at the top of https://www.dk.com/us/ wasn't being displayed

adblock | Jobsinkyoto | safehaven | airbnb | overhemden | dk
-|-|-|-|-|-
![screenshot-1650590418315](https://user-images.githubusercontent.com/17885425/164578433-1af5b2fb-316a-4886-b510-37fdab8dbd49.png) | ![screenshot-1650590514349](https://user-images.githubusercontent.com/17885425/164578435-e498e56d-f388-4571-abce-a6ca31fda90d.png) | ![screenshot-1650590562071](https://user-images.githubusercontent.com/17885425/164578436-5bd00d2d-93f2-4fc1-b203-9311d36bc3a1.png) | ![screenshot-1650590588773](https://user-images.githubusercontent.com/17885425/164578439-583a78ac-5f76-43d2-8e85-e38deb2f0fe3.png) | ![screenshot-1650590622154](https://user-images.githubusercontent.com/17885425/164578441-a6122f46-47a4-4c3d-a16f-fcb5de0093a2.png) | ![screenshot-1650590650906](https://user-images.githubusercontent.com/17885425/164578443-3b0b971a-91b6-435c-8189-efa41c83e7a3.png)
