### ISSUE TITLE
Refactor useTransactionParser to remove prop-drilling

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22041]
## Description 
Use react-redux hooks to alleviate ["prop-drilling"](https://kentcdodds.com/blog/prop-drilling#what-is-prop-drilling) in the useTransactionParser hook.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [brave/brave-core#14022](https://github.com/brave/brave-core/pull/14022)
- Verified transactions looks correct in portfolio and panel 

Portfolio Token View | Transaction confirmation (Panel) | Transaction History (Panel)
-- | -- | --
<img width=1200 src=https://user-images.githubusercontent.com/17010094/186737738-0387d5ab-3227-4867-8837-487d131a8edc.png> | ![image](https://user-images.githubusercontent.com/17010094/186737655-09ffe99c-b805-4150-bcd8-ed6b3172bbee.png) | ![image](https://user-images.githubusercontent.com/17010094/186737887-2bbc3463-aab3-49a8-862b-418df1ecc910.png)

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14022](https://github.com/brave/brave-core/pull/14022)
- Verified transactions looks correct in portfolio and panel 

Portfolio Token View | Transaction confirmation (Panel) | Transaction History (Panel)
-- | -- | --
<img width=1800 src=https://user-images.githubusercontent.com/17010094/186736107-3ed45a0b-0815-40e9-8324-ce6206d3c48d.png> | ![image](https://user-images.githubusercontent.com/17010094/186736168-33a5d3f6-b8f2-409e-9475-16718a4dd466.png) | ![image](https://user-images.githubusercontent.com/17010094/186736426-b695ad04-a0b1-4745-bf16-8d6cd19c1fe8.png)

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14022](https://github.com/brave/brave-core/pull/14022)
- Verified transactions looks correct in portfolio and panel 

Portfolio Token View | Transaction confirmation (Panel) | Transaction History (Panel)
-- | -- | --
<img width=1200 src=https://user-images.githubusercontent.com/17010094/186738862-d10deb71-c7c5-4a96-b650-17f5011b1f8a.png> | ![image](https://user-images.githubusercontent.com/17010094/186738906-b5a673c5-a1c2-4634-95e1-79ac172e383b.png) | ![image](https://user-images.githubusercontent.com/17010094/186738880-9fd48014-3207-432f-8312-dcdb5d0909af.png)
