### ISSUE TITLE
Add ability to dock Inspect Element on macOS

### ISSUE THREAD

**Issue by seaside98** [brave/brave-browser#2205]
On macOS when opening Inspect Element it always opens as a popup window. There is no option to dock it at the bottom or on the side like you can in both Chrome and the Windows version of Brave. As a web developer using Brave this would be really helpful to me.

**Comment by Liunkae** [comment]
Please make sure you are using the latest version of Brave: https://brave.com/download

The developer tools have the following docking options in the latest version (0.56.14).
![](https://user-images.githubusercontent.com/19424103/48815755-2c616580-ed05-11e8-9347-34f5de7446e1.png)

**Comment by seaside98** [comment]
You are right, I did not have the latest version.
