### ISSUE TITLE
Tab mouseover misnames web pages that begin with chrome

### ISSUE THREAD

**Issue by alanhoyle** [brave/brave-browser#22069]
## Description 
When a web site is at a domain that begins with "chrome" brave replaces "chrome" with "brave" in the tab's tool-tip that pops up with the mouse hovers over the tab.  

## Steps to Reproduce

   1. Go to a web site that begins with "chrome" e.g. [chromeunboxed.com](https://chromeunboxed.com/) or [chromeosreview.com](https://chromeosreview.com)
   2. Hover the mouse over the tab

Note that this is hard to grab a screenshot of at least on a mac.  As soon as I hit any of the modifier keys required to take a screenshot, the tooltip disappears.  I had to do a screen recording and take a screenshot of that.  

## Actual result:

The tooltip says "braveunboxed.com"

![Screen Shot 2022-04-04 at 10 58 55 AM](https://user-images.githubusercontent.com/289779/161574217-8c6e4b87-9793-4760-900f-23ac058d1724.png)

or "braveosreview.com"
![Screen Shot 2022-04-04 at 11 16 33 AM](https://user-images.githubusercontent.com/289779/161575937-7ee1adfc-873a-43fd-96cf-841f44383809.png)

## Expected result:
The tooltip should say  "chromeunboxed.com" or "chromeosreview.com"

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? untested.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? untested
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

My guess is that this is done by a naive regex like `s/^chrome/brave/` when that should be something more like `s/^chrome:\/\//brave:\/\//`

**Comment by bsclifton** [comment]
cc: @mkarolin @emerick @cdesouza-chromium

**Comment by kjozwiak** [comment]
Above requires `1.37.114` or higher for `1.37.x` verification.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.37.114 Chromium: 100.0.4896.88 (Official Build) (x86_64)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | macOS Version 12.3.1 (Build 21E258)
```

**Comment by LaurenWags** [comment]
Great, thanks for the confirmation @alanhoyle 😄
