### ISSUE TITLE
Incorrect Fingerprintblocking response values for `Strict, may break sites` and `Disabled` shield settings in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22064]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/21345
Incorrect Fingerprintblocking response values for `Strict, may break sites` and `Disabled` shield settings in an upgraded profile

## Steps to Reproduce

   1. Clean profile `1.37.103`
   2. Open brave://local-state
   3. Ensure `Brave.Shields.FingerprintBlockSetting` is not shown in the local state file as expected
   4. Change the Fingerprintblocking global shield settings to `Strict, may break sites` or `Disabled`
   5. Open brave://help and auto-update the brave to the latest beta version `1.38.x`
   6. Reload the brave://local-state file
   7. `Brave.Shields.FingerprintBlockSetting` response value is `1` instead of 2 or 0 based on  `Strict, may break sites` or `Disabled` 
   selection
   

## Actual result:

Incorrect Fingerprintblocking response values for `Strict, may break sites` and `Disabled` shield settings in an upgraded profile
## Expected result:

`Brave.Shields.FingerprintBlockSetting` response value should be  `2` if adblocking shield settings is set to `Strict, may break sites`  in 1.37.x 
`Brave.Shields.FingerprintBlockSetting` response value should be  `0` if adblocking shield settings is set to `Disabled` in 1.37.x
## Reproduces how often: 

100 %

## Brave version (brave://version info)

Brave | 1.38.75 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
```

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)
--- | ---
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | Android 11; Build/RP1A.200720.012
```

#### `Test Case #1`

* installed `1.38.113 Chromium: 101.0.4951.61`
* set the default `Block fingerprinting` to `Strict, may break sites` via the `Brave Shields & privacy` settings
* updated Brave to `1.39.109 Chromium: 102.0.5005.50`
* checked `brave://local-state` and ensured that `Brave.Shields.FingerprintBlockSetting` was set as `2` as per the following:

![Screenshot_20220520-002902_Brave](https://user-images.githubusercontent.com/2602313/169450929-72215e0b-5baf-49c4-8d97-906785c057c3.jpg)

#### `Test Case #2`

* installed `1.38.113 Chromium: 101.0.4951.61`
* set the default `Block fingerprinting` to `Disabled` via the `Brave Shields & privacy` settings
* updated Brave to `1.39.109 Chromium: 102.0.5005.50`
* checked `brave://local-state` and ensured that `Brave.Shields.FingerprintBlockSetting` was set as `0` as per the following:

![Screenshot_20220520-003513_Brave](https://user-images.githubusercontent.com/2602313/169451332-5515fe3c-5756-4d41-9623-4729ba04d675.jpg)
