### ISSUE TITLE
Lower values in IPFS Swarm.ConnMgr

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#22068]
Brave should follow the suit and change the values to:

```
config.Swarm.ConnMgr.GracePeriod = "20s"
config.Swarm.ConnMgr.LowWater = 20
config.Swarm.ConnMgr.HighWater = 40
```

Rationale: 
- Connection Manager controls how many connections are kept around when idle. 
- Historically these values were high, but they no longer need to be (we have better DHT, QUIC etc).
- Less connections means lower bandwidth and CPU usage when user is not actively browsing `ipfs://` resources. 
- IPFS Desktop ships with less  expensive values (https://github.com/ipfs/ipfs-desktop/pull/2055)

cc @autonome @spylogsster

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.39.51 Chromium: 100.0.4896.88 (Official Build) nightly (x86_64)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | macOS Version 11.6.5 (Build 20G527)

#### Confirmed installation and basic smoketest of IPFS
#### Confirmed new values

### Steps:
1. installed `1.39.51`
2. loaded `ipns://[docs.]ipfs.io`
3. clicked on `Install a Brave local IPFS node`
4. checked various IPFS resources

example | example | example | example | example
-------|----|-----|-----|-------
<img width="1312" alt="Screen Shot 2022-04-12 at 3 43 26 PM" src="https://user-images.githubusercontent.com/387249/163067410-a067e069-de85-48a2-92fe-6b0bc7d16638.png"> | <img width="1312" alt="Screen Shot 2022-04-12 at 3 44 11 PM" src="https://user-images.githubusercontent.com/387249/163067463-d884b2c0-8133-46b8-a132-5eacdfe0b37d.png"> | <img width="1312" alt="Screen Shot 2022-04-12 at 3 44 21 PM" src="https://user-images.githubusercontent.com/387249/163067591-9a5a573c-df74-420e-bf82-8f4998aab1e4.png"> | <img width="1312" alt="Screen Shot 2022-04-12 at 3 44 26 PM" src="https://user-images.githubusercontent.com/387249/163067597-9199a875-2df7-42b1-bb30-ab4e52ef33ec.png"> | <img width="1312" alt="Screen Shot 2022-04-12 at 3 48 23 PM" src="https://user-images.githubusercontent.com/387249/163067601-5c919354-7bf0-45c1-b40b-22f95133f1d6.png">
